### ISSUE TITLE
Clarify usage off SharedCalendarSyncStartDate 

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/office-docs-powershell#10000]
On the https://learn.microsoft.com/powershell/module/exchange/set-mailboxcalendarfolder#-sharedcalendarsyncstartdate, we have the following note:

Notes:

You use this parameter on the shared calender's mailbox, not the delegate's mailbox.
Users need to have FullDetails, Editor, or Delegate access to the specified shared calendar.
Setting this parameter might cause events in the shared calendar to briefly disappear from view while the calendar is resynchronized.

This phrase "You use this parameter on the shared calender's mailbox, not the delegate's mailbox.", should be replaced with something like this: "You use this parameter on the shared calendar, in the delegate's mailbox. The command would be something like: Set-MailboxCalendarFolder -Identity "delegate@domain.com:\Name of shared calendar" -SharedCalendarSyncStartDate <input date>

**Comment by chrisda** [comment]
@Alex-Catalin, Description of the first bullet changed to:

> You use this parameter on the shared calendar in delegate's mailbox. For example, `Set-MailboxCalendarFolder -Identity "delegate@contoso.com:\Name of shared calendar" -SharedCalendarSyncStartDate`.

OK?

**Comment by Alex-Catalin** [comment]
Hi Chris,


Yes, that's about it!

Thank you,
Alex

**Comment by yogkumgit** [comment]
@Alex-Catalin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
