### ISSUE TITLE
Cannot remove a member who is an owner using powershell

### ISSUE THREAD

**Issue by nmistry77** [MicrosoftDocs/office-docs-powershell#10004]
When trying to remove an owner who is also member using p$ command below, i receive the following error

Microsoft.Exchange.Management.Recipient.GroupOwnersCannotBeRemovedException|Only Members who are not owners can be removed from group. Please remove <user> as owners before removing them as members.

I can achieve the same using GUI.

Can you please update/fix this anomaly as I would like to update 150 Unified Groups using P$ rather than using GUI which is quite cumbersome.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c927c29-65b9-2633-4d44-7a73e052efc4
* Version Independent ID: cdc7b8b3-daf4-3e34-8dce-615128a25904
* Content: [Remove-UnifiedGroupLinks (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/remove-unifiedgrouplinks?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-UnifiedGroupLinks.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Remove-UnifiedGroupLinks.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@nmistry77, can't you use PowerShell to assign different group owners, and then remove the members you want?

Other than that, you should open a support ticket.

**Comment by nmistry77** [comment]
> @nmistry77, can't you use PowerShell to assign different group owners, and then remove the members you want?
> 
> Other than that, you should open a support ticket.

Hi Chris, the issue is "Cannot remove an owner who is also a member", I can certainly add a new Owner as per your suggestion but that would not solve the issue I am facing where I am trying to remove a member who is also an Owner.

Also note I can achieve the same using the GUI where the same Owner who is also the member can be removed from the members. (seem's like a bug to me in P$)

**Comment by chrisda** [comment]
Cool. Then a support ticket is the best way to go.

**Comment by yogkumgit** [comment]
@nmistry77 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
