### ISSUE TITLE
guidance for locking themselves out?

### ISSUE THREAD

**Issue by SiegfriedB2** [MicrosoftDocs/office-docs-powershell#10001]
Since I have seen this twice on the web now, it might be good to mention that if they accidentally locked out themselves (and/or everybody), they need no create a new user which then will have PS access again. Or alternatively, provide guidance on how to exclude a user. Like get-user | Where-Object {$_.userprincipalname -ne 'xxx@xxx.com'} | Set-User -RemotePowerShellEnabled $false

**Comment by chrisda** [comment]
@SiegfriedB2, I added the following note to the [Enable or disable access to Exchange Online PowerShell]( https://learn.microsoft.com/powershell/exchange/disable-access-to-exchange-online-powershell) (which is what I presume we're talking about here?

  > [!IMPORTANT]
  > Don't run commands like `Get-User | Set-User -RemotePowerShellEnabled $false` to universally remove remote PowerShell access without considering admin accounts. Use the procedures in this article to selectively remove remote PowerShell access, or preserve admin access for at least one account by using the following syntax in your removal command: `Get-User | Where-Object {$_.UserPrincipalName -ne 'admin@contoso.onmicrosoft.com'} | Set-User -RemotePowerShellEnabled $false`.
  >
  > If you accidentally lock yourself out of remote PowerShell access, create a new admin user account, and then use that account to give yourself remote PowerShell access.

OK?

**Comment by yogkumgit** [comment]
@SiegfriedB2 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
