### ISSUE TITLE
Get-ProtectionAlert -Identity "xxxxxx" cannot be used

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/office-docs-powershell#10007]
[Get-ProtectionAlert -Identity "Malicious Email Campaign" Or any other Identity like this does not work. Identities for these policies are more complex for these policies and look like as follows: FFO.extest.microsoft.com/Microsoft Exchange Hosted Organizations/f00ed340-8f84-4eb4-83f3-0075a22b262e/Configuration/Suspicious email sending patterns detected]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b618c0fd-8f9b-77ee-b4a9-61fbc19ddbef
* Version Independent ID: 00bc0e3e-d37b-1af7-fed0-b1871044f75c
* Content: [Get-ProtectionAlert (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-protectionalert?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-ProtectionAlert.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-ProtectionAlert.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeroenDronkers, I just tried it in PowerShell 5.1 and PowerShell 7.2.6. There is (no longer?) an alert policy named "Malicious Email Campaign", so I changed the example to use "Malware campaign detected after delivery", but the command using the regular/friendly name as the Identity value worked fine for me:

```powershell
Get-ProtectionAlert -Identity "Malware campaign detected after delivery"
```

Are you using the latest version of the module (v3.0.0)? Are you connecting using CBA/app-only authentication?

**Comment by JeroenDronkers** [comment]
Thanks Chris,


I tried yesterday running Get-ProtectionAlert -Identity "Suspicious connector activity" and it didn’t work but today it does, so I am not sure what went wrong.

Also Get-ProtectionAlert -Identity "Malware campaign detected after delivery" works fine.





Thanks for having checked this.



Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
***@***.******@***.***>

[abc]
﻿
Team Manager | Frances Early ***@***.******@***.***>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center

**Comment by yogkumgit** [comment]
@JeroenDronkers Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
