### ISSUE TITLE
Description attribute?

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10012]
In the O365 Teams Admin portal, there is a description field, but for the life of me, I can't see this anywhere in the current attributes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d724d21-5a9b-4610-349a-cc43e1b77fa3
* Version Independent ID: 359415a2-239c-c5cb-a12b-879e24643189
* Content: [Set-CsTeamsAudioConferencingPolicy (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csteamsaudioconferencingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsAudioConferencingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsAudioConferencingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @sarollins 
It's true however the cmdlet still doesn't add the ability to set it.
Thank you,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
