### ISSUE TITLE
Get-User Example Should Use -AND

### ISSUE THREAD

**Issue by Spence10873** [MicrosoftDocs/office-docs-powershell#10022]
[Enter feedback here]
The _Important_ blue box near the top with the example for Get-User | Where-Object{$_.UserPrincipalName..... should use -AND instead of -OR when filtering users. The way it's written, no matter how many UPNs you add, you get the same number of results from the Get-User cmd.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d03c6ce2-687b-e138-939b-413014d1c81a
* Version Independent ID: 9fe6c492-d0fe-e454-6574-06de8cd31a21
* Content: [Control remote PowerShell access to Exchange servers](https://learn.microsoft.com/en-us/powershell/exchange/control-remote-powershell-access-to-exchange-servers?view=exchange-ps&viewFallbackFrom=exchange-ps%22%20%5Cl%20%22use-the-exchange-management-shell-to-enable-or-disable-remote-powershell-access-for-a-user)
* Content Source: [exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Spence10873, confirmed and fixed.

Thanks for the feedback.

Closing.
