### ISSUE TITLE
MicrosoftTeams Powershell module errors when using Application-based authentication (AccessTokens), 4.7.1-preview

### ISSUE THREAD

**Issue by captainhook** [MicrosoftDocs/office-docs-powershell#10025]
Hi folks,

We are able to run the following in a PowerShell terminal on desktop and as expected everything works fine:
```
Connect-Teams
Set-CsPhoneNumberAssignment -Identity $SAM -PhoneNumber "$Tel" -PhoneNumberType DirectRouting

```

We are now trying to build some automation and have followed Microsoft's guide '[Connect to MicrosoftTeams using Application-based Access Tokens](https://learn.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps#example-5-connect-to-microsoftteams-using-application-based-access-tokens)':

```
$ClientSecret   = "[redacted]"
$ApplicationID = "[redacted]"
$TenantID = "[redacted]"

$graphtokenBody = @{   
   Grant_Type    = "client_credentials"   
   Scope         = "https://graph.microsoft.com/.default"   
   Client_Id     = $ApplicationID   
   Client_Secret = $ClientSecret   
}  

$graphToken = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$TenantID/oauth2/v2.0/token" -Method POST -Body $graphtokenBody | Select-Object -ExpandProperty Access_Token 

$teamstokenBody = @{   
   Grant_Type    = "client_credentials"   
   Scope         = "48ac35b8-9aa8-4d74-927d-1f4a14a0b239/.default"   
   Client_Id     = $ApplicationID   
   Client_Secret = $ClientSecret 
} 

$teamsToken = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$TenantID/oauth2/v2.0/token" -Method POST -Body $teamstokenBody | Select-Object -ExpandProperty Access_Token 

Connect-MicrosoftTeams -AccessTokens @("$graphToken", "$teamsToken")
Set-CsPhoneNumberAssignment -Identity $SAM -PhoneNumber "$Tel" -PhoneNumberType DirectRouting
```

We see the following error:
```
Set-CsPhoneNumberAssignment_Set: C:\Users\amiah\Documents\PowerShell\Modules\MicrosoftTeams\4.7.1\custom\Merged_custom_PsExt.ps1:1298
Line |
1298 |              Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNum …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Powershell administered domain is unexpectedly null/empty
```

According to MS documentation, "[For *-Cs cmdlets - no API permissions are needed.](https://learn.microsoft.com/en-us/MicrosoftTeams/teams-powershell-application-authentication#setup-application-based-authentication)", so for our App Registration we have added no API permissions to the App Registration. **Is this correct?** If so, how would it work with no application permissions?

In case that is not correct and we do in fact need to set API permissions, I have also tried adding the following Application permissions (not delegated):
```
PS > $($graphToken | Get-JWTDetails).Roles | sort
AppCatalog.ReadWrite.All
Channel.Delete.All
ChannelMember.ReadWrite.All
ChannelSettings.ReadWrite.All
Group.ReadWrite.All
TeamSettings.ReadWrite.All
User.Read.All
PS > $($teamsToken | Get-JWTDetails).Roles | sort
application_access
```

Rerunning my `Set-CsPhoneNumberAssignment` command now returns the following error:
```
Set-CsPhoneNumberAssignment_Set: C:\Users\amiah\Documents\PowerShell\Modules\MicrosoftTeams\4.7.1\custom\Merged_custom_PsExt.ps1:1298
Line |
1298 |              Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNum …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access Denied.
```

**Comment by pbafna03** [comment]
Hi @captainhook, 

Are the relevant Azure AD admin roles assigned to the app? 

Thanks,

**Comment by captainhook** [comment]
> Hi @captainhook,
> 
> Are the relevant [Azure AD admin roles](https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles#teams-roles-and-capabilities) assigned to the app?
> 
> Thanks,

Hi @pbafna03,

Ah, I did completely miss that out!
I have added 'Teams communications administrator' role and retested - it is working :)

Is Grant-CsOnlineVoiceRoutingPolicy supported using App-based auth?

**Comment by pbafna03** [comment]
Thanks for confirming @captainhook. 

Policy Grants are not yet supported with application-based auth but will be rolled out soon.

**Comment by pbafna03** [comment]
@captainhook - Policy grants are also supported now.

**Comment by trust11** [comment]
> > Hi @captainhook,
> > Are the relevant [Azure AD admin roles](https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles#teams-roles-and-capabilities) assigned to the app?
> > Thanks,
> 
> Hi @pbafna03,
> 
> Ah, I did completely miss that out! I have added 'Teams administrator' role and retested - it is working :)
> 
> Is Grant-CsOnlineVoiceRoutingPolicy supported using App-based auth?

Hi How did you do that?  I am searching for that since 8 houres

**Comment by captainhook** [comment]
> > > Hi @captainhook,
> > > Are the relevant [Azure AD admin roles](https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles#teams-roles-and-capabilities) assigned to the app?
> > > Thanks,
> > 
> > 
> > Hi @pbafna03,
> > Ah, I did completely miss that out! I have added 'Teams administrator' role and retested - it is working :)
> > Is Grant-CsOnlineVoiceRoutingPolicy supported using App-based auth?
> 
> Hi How did you do that? I am searching for that since 8 houres

Azure Active Directory > Roles and Administrators > Teams Administrator > Add Assignment > search and select your App Registration

voila :)

**Comment by trust11** [comment]
@captainhook Thank you. 
Wow, that is so inconvenient. Why are only Users listed. How on Earth should I guess that I need to search for something which is not listed? Don't like that at all, but it works now. Many thanks.
