### ISSUE TITLE
Get-CsApplicationAccessPolicy truncates list of APPs

### ISSUE THREAD

**Issue by kkoellner** [MicrosoftDocs/office-docs-powershell#10035]
Get-CsApplicationAccessPolicy   truncates list of Apps.  Either this command should have a switch to provide the whole list of if that functionality exists elsewhere, the documentation for Get-CsApplicationAccessPolicy should point to it.

> Get-CsApplicationAccessPolicy -Identity "Test-policy" 

Identity    : Tag:Test-policy
AppIds      : {b747fe91-1356-418b-965e-27b6abddf4b9, 7bb97176-4520-4477-a2ae-8eb7543c2759, c60a71c4-48e7-46f5-b6e6-32e45cf61239, 66caad95-0f7e-46f0-85fa-68e3bcfe7b6c…}
Description : description here

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6533a7d-ddc4-eef1-cca6-0ee4786163ef
* Version Independent ID: 8958282d-6816-c8c3-cd0b-07b50681aacf
* Content: [Get-CsApplicationAccessPolicy (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/get-csapplicationaccesspolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsApplicationAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsApplicationAccessPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @frankpeng7
* Microsoft Alias: **frpeng**

**Comment by get-itips** [comment]
Hello @kkoellner 
That's a normal behavior behind PowerShell when one of the properties is an array, you can expand into that with

`(Get-CsApplicationAccessPolicy -Identity "Test-policy").AppIds`

As here we are limited to documentation fixes and improvements, we will proceed closing this.

Thank you,

**Comment by kkoellner** [comment]
That explanation is great and meets my needs.

I work on five integrations and I'm the only engineer on the project.  As much as I'd like to learn everything there is to know about MS-Graph APIs, powershell, Teams, etc.  I don't have near the bandwidth to do that so I just look up what I absolutely need to know and sometimes can find a little trick that's needed to get something like the command above to get all the App IDs for an application policy.

**Comment by get-itips** [comment]
Glad to hear @kkoellner Ken.
