### ISSUE TITLE
Code in 'Important' section wrongly uses -or instead of -and

### ISSUE THREAD

**Issue by Noraa5** [MicrosoftDocs/office-docs-powershell#10030]
In the 'Important' section at the top of the page, it wrongly uses `-or` instead of `-and` in the code.  
Instead of  `Get-User | Where-Object {$_.UserPrincipalName -ne 'admin1@contoso.com' -or $_.UserPrincipalName -ne 'admin2@contoso.com'...} | Set-User -RemotePowerShellEnabled $false` 
it should be `Get-User | Where-Object {$_.UserPrincipalName -ne 'admin1@contoso.com' -and $_.UserPrincipalName -ne 'admin2@contoso.com'...} | Set-User -RemotePowerShellEnabled $false`.
By having `-or` it will set all the listed users' access to false because it will always meet the other conditions of not being the other users listed.  This is the opposite of what the code is intended to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d03c6ce2-687b-e138-939b-413014d1c81a
* Version Independent ID: 9fe6c492-d0fe-e454-6574-06de8cd31a21
* Content: [Control remote PowerShell access to Exchange servers](https://learn.microsoft.com/en-us/powershell/exchange/control-remote-powershell-access-to-exchange-servers?view=exchange-ps&viewFallbackFrom=exchange-ps%22%20%5Cl%20%22use-the-exchange-management-shell-to-enable-or-disable-remote-powershell-access-for-a-user)
* Content Source: [exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Noraa5, yes. Fixed yesterday #10022.

Thanks for the feedback.

Closing
