### ISSUE TITLE
Issue with Connect-IPPSession to DelegatedOrganisation

### ISSUE THREAD

**Issue by Adzino1** [MicrosoftDocs/office-docs-powershell#10031]
Hey,

Running into an issue with our scripts here - We are unable to use the Connect-IPPSession with the -DelegatedOrganisation parameter.

Getting Access Denied and A strange issue here 
![image](https://user-images.githubusercontent.com/115543795/195111688-0f8bcfb2-3fac-4a4f-abbe-93e00ae43ab7.png)

Let me know if you need more info!

I've been to MS and The MS community who've pointed me here.

Any help will be appreciated!

**Comment by chrisda** [comment]
@Adzino1, are you using v3.0.0 of the ExchangeOnlineManagement module?

Notice that the description for the DelegatedOrganization parameter in [Connect-IPPSSession](https://learn.microsoft.com/powershell/module/exchange/connect-ippssession) is 'reserved for internal Microsoft use'.

You should open a support ticket and ask.

**Comment by yogkumgit** [comment]
@Adzino1 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Adzino1** [comment]
> @Adzino1 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only. We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

Funnily enough, Microsoft asked me to come to Git and ask :)

**Comment by chrisda** [comment]
@Adzino1, unless you hear otherwise, presume DelegatedOrganization doesn't work on Connect-IPPSSession. After all, the documentation says, "reserved for internal Microsoft use".

I'm asking some other sources (the same sources the support ticket people should have been asking!), but I'm pretty sure they would have told me about it based on the recent GA launch of v3.0.0, and the massive feature/documentation updates required for it.

**Comment by chrisda** [comment]
@Adzino1, apparently, DelegatedOrganization is expected to work. You must be using v3.0.0 of the module, and you must also use the AzureADAuthorizationEndpointUri parameter in the command.

Report back here if that doesn't work. I've updated the documentation accordingly.

**Comment by Adzino1** [comment]
Hey, using this command here -

Connect-IPPSSession -DelegatedOrganization 'xxx.onmicrosoft.com' -AzureADAuthorizationEndpointUri 'https://login.microsoftonline.com/common' 

Still getting Access denied errors

running exchange online module 3.0.0
![image](https://user-images.githubusercontent.com/115543795/196723529-606d0032-b2f0-4740-b67b-4be5ce90bce3.png)

**Comment by chrisda** [comment]
@Adzino1, how is your support ticket about this going? Is it still open?

**Comment by Adzino1** [comment]
@chrisda Sent them the updated info, as I have here. Just waiting on a response.

**Comment by yogkumgit** [comment]
@Adzino1 Any response.

**Comment by Adzino1** [comment]
@yogkumgit Hey, yes they've informed us that it only works with GDAP permissions - we are currently testing, during our early test with it was still getting Access denied. We are in contact with a Azure Lighthouse support also.

**Comment by yogkumgit** [comment]
@Adzino1 Thanks. If you find it suitable and no update is required in the documentation, please feel free to close this issue.

**Comment by yogkumgit** [comment]
@Adzino1 We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also. We proceed to close it.
