### ISSUE TITLE
Please warn about disabling RPS for Health Mailboxes 

### ISSUE THREAD

**Issue by Niehweune** [MicrosoftDocs/office-docs-powershell#10039]
Although the article warns about blindly disabling RPS for everyone (including admins) and suggest using an attribute or 'list of users' approach to exclude admins, this isn't enough.

You should also mention health mailboxes, since disabling RPS for those users will cause the RPS healthset to fail (with a very ugly error because 'AuthZ-RemotePowerShellNotEnabledException' isn't handled properly by the probe.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d03c6ce2-687b-e138-939b-413014d1c81a
* Version Independent ID: 9fe6c492-d0fe-e454-6574-06de8cd31a21
* Content: [Control remote PowerShell access to Exchange servers](https://learn.microsoft.com/en-us/powershell/exchange/control-remote-powershell-access-to-exchange-servers?view=exchange-ps&viewFallbackFrom=exchange-ps%22%20%5Cl%20%22use-the-exchange-management-shell-to-enable-or-disable-remote-powershell-access-for-a-user)
* Content Source: [exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Niehweune, added 'health monitoring mailboxes' in the example of what to preserve.

> In your haste to quickly and globally disable remote PowerShell access in your organization, beware of commands like `Get-User | Set-User -RemotePowerShellEnabled $false` without considering administrator accounts, service accounts, or health monitoring mailboxes that need remote PowerShell access.

OK?

**Comment by Niehweune** [comment]
Perfect 👌
