### ISSUE TITLE
PowerShell cmdlet "Set-UnifiedGroup" cannot be replaced with Graph

### ISSUE THREAD

**Issue by vogla** [MicrosoftDocs/office-docs-powershell#10040]
The PowerShell cmdlet [Set-UnifiedGroup](https://learn.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup) **cannot** be replaced with Graph! Most of the relevant group properties, such as "mail" and "proxyAdresses", are _read-only_ in Graph. It is frustrating for partners and developers that existing deficits of the Graph API in the area of group management and Exchange are not documented and not recognised.

I am referring to [this article](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps), that again wrongly assumes in this context: "You can use Microsoft Graph instead."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication in Exchange Online PowerShell and Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@vogla, I changed the offending line to say:

> You can use Microsoft Graph to replace most of the functionality from those cmdlets.

OK?

**Comment by yogkumgit** [comment]
@vogla Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by vogla** [comment]
Thank you for correcting the offending line! Even though it is a small change, it helps to clarify that Graph is not just a drop-in replacement for the PowerShell cmdlets yet.
