### ISSUE TITLE
Invalid DirectRoutingTelephoneNumber '1'

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10042]
Issuing the following command

Get-CsPhoneNumberAssignment -Top 80 -NumberType CallingPlan -PstnAssignmentStatus UserAssigned | Select AssignedPstnTargetId, LocationId, TelephoneNumber

we are seeing the following error

Get-CsPhoneNumberAssignment : Invalid DirectRoutingTelephoneNumber '1'
At line:1 char:1
+ Get-CsPhoneNumberAssignment -Top 80 -NumberType CallingPlan -PstnAssi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ TelephoneNumb...= 80, Skip =  }:<>f__AnonymousType56`15) 
[Get-CsPhoneNumberAssignment_Get], Exception
    + FullyQualifiedErrorId : 
BadRequest,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsPhoneNumberAssignment_Get

How can this be corrected?  I would hope that the cmdlet just returns the data and if it's invalid, the burden is upon the caller to deal with it

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bfb9351-75be-abb8-c8ac-bf08f51d08a1
* Version Independent ID: c7925810-6411-9371-7a04-fc28a4c827ec
* Content: [Get-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@sarollins Thanks for the feedback. If you are fine with replying with your tenantid and date/time of when you saw this error, please do. Otherwise please open a Microsoft support case with your tenantid and date & time of when you did the above cmdlet such that we can investigate what's going on.

**Comment by JensTrier** [comment]
@sarollins I could repro the error you are seeing by configuring an on-premises AD user with the msRTCSIP-Line attribute set to 'tel:1' and synching the user to M365 via AAD Connect.

I assume your configuration is the same. To correct it, you need to find the user and clear the msRTCSIP-Line attribute. You can find the user using Get-AdUser -Filter {msRTCSIP-Line -eq 'tel:1'} in on-premises AD PowerShell.

We are looking into bypassing such invalid phone numbers, but for now you need to correct the numbers before Get-CsPhoneNumberAssignment shows any output.

Feel free to close this issue.

**Comment by JensTrier** [comment]
@sarollins we have implemented the change to bypass these invalid Direct Routing phone numbers. Please have a look.

Feel free to close this issue

**Comment by yogkumgit** [comment]
@JensTrier Thank you very much for sharing this explanation. @sarollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
