### ISSUE TITLE
Difference between Get-SPOPublicCdnOrigins and Get-SPOTenantCdnOrigins

### ISSUE THREAD

**Issue by gr79** [MicrosoftDocs/office-docs-powershell#10057]
I am confused by the difference between Get-SPOPublicCdnOrigins and Get-SPOTenantCdnOrigins -CdnType Public (and all variants such as New-SPOPublicCdnOrigins and Add-SPOTenantCdnOrigins, etc.)

They sound the same, but when I ran Get-SPOTenantCdnOrigins -CdnType Public, I get a list of CDNs, while if I run Get-SPOPublicCdnOrigins I get nothing.

Moreover, when I run Get-SPOTenantCdnEnabled -CdnType Public, I get a value of "True" (so public CDNs should be enabled), while if I try to run New-SPOPublicCdnOrigins, I get: "CDN feature is not enabled by the tenant administrator"

Thank you for the explanation.

![196385590-1646f3b0-adcb-4d92-8804-da33bd33cbe7](https://user-images.githubusercontent.com/40117213/196420575-0dda14b6-9956-468a-8fbc-abc9b8d7ac27.png)

**Comment by get-itips** [comment]
Hello @gr79 
I am looking into this.

**Comment by get-itips** [comment]
Hello @gr79 please see this https://github.com/MicrosoftDocs/office-docs-powershell/issues/2226
