### ISSUE TITLE
Get-Place and Set-Place do not work with synchronized room mailboxes at all

### ISSUE THREAD

**Issue by exactmike** [MicrosoftDocs/office-docs-powershell#10058]
Per the documentation [here](https://learn.microsoft.com/powershell/module/exchange/set-place) I expect to be able to set non-mastered attributes for synchronized room mailboxes using Set-Place and to view the current configuration for a synchronized room mailbox using Get-Place.  However, when attempt is made to use the cmdlets in this way they are unable to locate the recipient object:

Error: "Ex6F9304|Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException|The operation couldn't be performed because object 'REDACTED' couldn't be found . . ."

Is the documentation in error or has an issue been introduced by a change that is preventing these cmdlets from performing as expected?

**Comment by chrisda** [comment]
@exactmike, are you using the latest version of the ExchangeOnlineManagement module (v3.0.0)?

If you're using the EXO V3 module, are you connecting with or without the _UseRPSSession_ switch?

If you're using the EXO V3 module, are you connecting using certificate-based authentication (CBA)?

**Comment by exactmike** [comment]
Yes, I'm using the latest version of the ExchangeOnlineManagement (v.3.0.0).  I am NOT using -UseRPSSession. I am NOT using Certificate-based authentication.  Calling Connect-ExchangeOnline either with no parameters at all or with -UserPrincipalName.

**Comment by chrisda** [comment]
@exactmike, you should open a support ticket. In the meantime, you can try running the connect command with the _UseRPSSession_ switch to see if that makes a difference.
