### ISSUE TITLE
Unable to set ReportToOriginatorEnabled parameter

### ISSUE THREAD

**Issue by csbescos** [MicrosoftDocs/office-docs-powershell#10059]
Need the ability to redirect NDRs when sending messages to unified groups.  Traditionally this is done by setting the ReportToManagerEnabled and ReportToOriginatorEnabled parameters on the group. 

Would like to be able to set these parameters on a unified group.  The parameters exist today, but we are unable to edit using the cmdlet:

```powershell
set-unifiedgroup -Identity "Marketing Department" -ReportToManagerEnabled $true -ReportToOriginatorEnabled $false

ReportToManagerEnabled                 : False
ReportToOriginatorEnabled              : True
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80326e44-6beb-8983-57ab-8333608c504b
* Version Independent ID: 8962c0dc-72a3-208a-33de-6a89cd56b6fc
* Content: [Set-UnifiedGroup (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@csbescos, your best way forward is to open a support ticket about this.

**Comment by csbescos** [comment]
I have an open case. Feel free to close if there is nothing further.

**Comment by chrisda** [comment]
Feel free to report back here if any updates to documentation will help.

Closing.
