### ISSUE TITLE
Get-EXOMailbox returns wrong value for roommailbox property isShared when filter condition present.

### ISSUE THREAD

**Issue by hmoritarts** [MicrosoftDocs/office-docs-powershell#10060]
When running Get-EXOMailbox on ExO V2/V3 Module, incorrect value is returned. "IsShared" attribute is supposed to be False for a RoomMailbox, but if -Filter option is used, True is returned instead.
It only occurs in RoomMailbox. It does not occur in UserMailbox.
The issue occurs in all RoomMailboxes.
It does not occur when using the Get-Mailbox command. This only occurs when using the Get-ExOMailbox command.

Please describe in the document that the above unintended behavior will occur.

**Comment by hmoritarts** [comment]
Repro Steps:
Connect to Exchange Online and perform the following steps
==========
// property definition
$mailboxProperties = @("Name","UserPrincipalName","IsShared")
 
// filter definition
$mailboxFilter = "(Alias -like '*kaigi1*') -and (RecipientTypeDetails -eq 'UserMailbox' -or RecipientTypeDetails -eq 'RoomMailBox')";
 
// Command execution (with filters)
Get-EXOMailbox -ResultSize unlimited -Filter $mailboxFilter -Properties $mailboxProperties
 
ExternalDirectoryObjectId : 75e19c2a-2b7d-42ab-b4a1-7b1fdc3156c8
IsShared                  : True
UserPrincipalName         : kaigi1-reo@reoland.onmicrosoft.com
Alias                     : kaigi1-reo
DisplayName               : kaigi1-reo
EmailAddresses            : {smtp:kaigi1-reo@reoland.onmicrosoft.com, SMTP:kaigi1-reo@reoland.xyz}
PrimarySmtpAddress        : kaigi1-reo@reoland.xyz
RecipientType             : UserMailbox
RecipientTypeDetails      : RoomMailbox
Identity                  : kaigi1-reo
(Omitted)
Guid                      : 9bd6d111-5592-45d9-8d1c-9785f1a62672
 
// Command execution (without filters)
Get-EXOMailbox "kaigi1-reo" -Properties $mailboxProperties
 
ExternalDirectoryObjectId : 75e19c2a-2b7d-42ab-b4a1-7b1fdc3156c8
IsShared                  : False
UserPrincipalName         : kaigi1-reo@reoland.onmicrosoft.com
Alias                     : kaigi1-reo
DisplayName               : kaigi1-reo
EmailAddresses            : {smtp:kaigi1-reo@reoland.onmicrosoft.com, SMTP:kaigi1-reo@reoland.xyz}
PrimarySmtpAddress        : kaigi1-reo@reoland.xyz
RecipientType             : UserMailbox
RecipientTypeDetails      : RoomMailbox
Identity                  : kaigi1-reo
(Omitted)
Guid                      : 9bd6d111-5592-45d9-8d1c-9785f1a62672
==========
 
Repro results:
 "IsShared" value returned incorrect value "True" when executing command with Filter option.

**Comment by chrisda** [comment]
@hmoritarts, if you're using v3.0.0 of the module, you should open a support ticket about this.

You can try a different connection method, i.e., if you're connecting in REST API mode without the _UseRPSSwitch_ try connecting using the _UseRPSSwitch_, or vice-versa. If you're connecting in app-only (certificate-based authentication) mode, try using 'regular' mode.

**Comment by yogkumgit** [comment]
@hmoritarts Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
