### ISSUE TITLE
Please fix table on page

### ISSUE THREAD

**Issue by jdurlewanger** [MicrosoftDocs/office-docs-powershell#10066]
[The table is too large for the displayed area and the slider is at the bottom. This is extremely unpleasant. This is a very long list. If you want to look at one of the first items you have to scroll down to the bottom of the page slide over and scroll all the way back up.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://learn.microsoft.com/en-us/powershell/exchange/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/filter-properties.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Known issue. In fact, this was also an issue back in 2018 and earlier when we were still on TechNet. No good answer, except to architect the topic to not use a table.

You can also use the left and right arrow keys to scroll horizontally.

**Comment by DMoenks** [comment]
I thought about how to possibly rework this into a different format, while keeping some of the original table approach and without ending up with too much vertical scrolling. A proposed approach for the first two properties is shown below as an example.
The property "headers" could as well be made into real headers, allowing readers to directly navigate/link to specific properties, but this might end up with a quite large table-of-contents. I can't estimate how that might look in the final documentation, unfortunately.

**AcceptMessagesOnlyFrom**
|LDAP display name|Available on cmdlets|Value|
|---|---|---|
|_authOrig_|**Get-DistributionGroup** <br> **Get-DynamicDistributionGroup** <br> **Get-Mailbox** <br> **Get-MailContact** <br> **Get-MailPublicFolder** <br> **Get-MailUser** <br> **Get-RemoteMailbox** <br> **Get-UnifiedGroup**|String or `$null`|

This filter requires the distinguished name of the individual recipient (a mailbox, mail user, or mail contact). For example, `Get-DistributionGroup -Filter "AcceptMessagesOnlyFrom -eq 'CN=Yuudai Uchida,CN=Users,DC=contoso,DC=com'" or Get-DistributionGroup -Filter "AcceptMessagesOnlyFrom -eq 'contoso.com/Users/Angela Gruber'"`.
To find the distinguished name of the individual recipient, replace _<RecipientIdentity>_ with the name, alias, or email address of the recipient, and run this command: `Get-Recipient -Identity "<RecipientIdentity>" | Format-List Name,DistinguishedName`.
Although this is a multivalued property, the filter will return a match if the property contains the specified value.

**AcceptMessagesOnlyFromDLMembers**
|LDAP display name|Available on cmdlets|Value|
|---|---|---|
|_dLMemSubmitPerms_|**Get-DistributionGroup** <br> **Get-DynamicDistributionGroup** <br> **Get-Mailbox** <br> **Get-MailContact** <br> **Get-MailPublicFolder** <br> **Get-MailUser** <br> **Get-RemoteMailbox** <br> **Get-UnifiedGroup**|String or `$null`|

This filter requires the distinguished name or canonical distinguished name of the group (a distribution group, mail-enabled security group, or dynamic distribution group). For example, `Get-Mailbox -Filter "AcceptMessagesOnlyFromDLMembers -eq 'CN=Marketing Department,CN=Users,DC=contoso,DC=com'"`. or `Get-Mailbox -Filter "AcceptMessagesOnlyFromDLMembers -eq 'contoso.com/Users/Marketing Department'"`. <br> To find the distinguished name of the group, replace _\<GroupIdentity\>_ with the name, alias, or email address of the group, and run one of these commands: `Get-DistributionGroup -Identity "<GroupIdentity>" | Format-List Name,DistinguishedName` or `Get-DynamicDistributionGroup -Identity "<GroupIdentity>" | Format-List Name,DistinguishedName`. <br> Although this is a multivalued property, the filter will return a match if the property _contains_ the specified value.
