### ISSUE TITLE
Unattended scripting in delegation scenarios - wrong link

### ISSUE THREAD

**Issue by joschibaer** [MicrosoftDocs/office-docs-powershell#10077]
The article mentioned in the first note for unattended scripting in delegated scenarios (CSP Partner doing operations in customer environments) the link is not correct, and is misleading:

> App-only authentication does not support delegation. Unattended scripting in delegation scenarios is supported with the Secure App Model. For more information, go [here](https://learn.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth#exchange).

The link should rather go to <https://learn.microsoft.com/powershell/partnercenter/multi-factor-auth#exchange-online-powershell>

However, the guidance itself is misleading since it only describes this approach with Exchange Online PowerShell v1 using Basic authentication, for v2/v3 ExO PowerShell the same approach does not work. Not sure if the correct statement should be "not supported at all" or if there is different guidance available.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication in Exchange Online PowerShell and Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by yogkumgit** [comment]
@chrisda Kindly update

**Comment by chrisda** [comment]
Resource identified. Waiting for information.

**Comment by chrisda** [comment]
Still in progress. Nothing to report. I have no value add here; I'm waiting for additional information.

**Comment by chrisda** [comment]
The topic has been updated for delegated scenarios in [this pull request](https://github.com/MicrosoftDocs/office-docs-powershell/pull/10294/files), so I'm closing this issue.

Thanks for the feedback.
