### ISSUE TITLE
Enable-PnPResponsiveUI Documentation makes not mention of files needed to be downloaded

### ISSUE THREAD

**Issue by westerdaled** [MicrosoftDocs/office-docs-powershell#1007]
The commandlet documentation makes no mention of the files we need to download from the PnPTools project.
[SharePointResponsiveUI ](https://github.com/westerdaled/PnP-Tools/tree/master/Solutions/SharePoint.UI.Responsive)

Can I assume these files are still needed and not "auto downloaded"  by the commandlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf79eb7b-2b14-e146-912b-c1e6ea3b8c17
* Version Independent ID: f75b46eb-50e4-8809-5650-8ba12c161200
* Content: [Enable-PnPResponsiveUI (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/enable-pnpresponsiveui?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Enable-PnPResponsiveUI.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Enable-PnPResponsiveUI.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by VesaJuvonen** [comment]
Files are actually not needed. Needed assets are automatically provisioned from inside of the PowerShell cmdlet assembly, so there's no requirement to have those files downloaded. They are provided for a reference if someone would like to adjust them and use them outside of the context of this cmdlet.
