### ISSUE TITLE
Set-CsAutoAttendant - Issue with cmdlet in 4.8.0

### ISSUE THREAD

**Issue by dtavb** [MicrosoftDocs/office-docs-powershell#10083]
With TeamsModule 4.8.0 I am not able to set some simple values for an autoattendant, example "Name"

scenario:
PS C:\Users\Administrator> $aa = Get-CsAutoAttendant -Identity YOURID
PS C:\Users\Administrator> $aa.Name
test-aa10
PS C:\Users\Administrator> $aa.Name = "mynewfancyobject"
PS C:\Users\Administrator> Set-CsAutoAttendant -Instance $aa

Error message:
I have deleted the IDs, specified in the ( )

Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsAutoAttendant : An application endpoint with specified ID ([deleted unknown ID]) was not found in tenant ([deleted myTenantID]). Please give correct parameter value.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.8.0\custom\Merged_custom_PsExt.ps1:7407 char:13
\+             $internalOutput = Microsoft.Teams.ConfigAPI.Cmdlets.inter ...
\+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = c1...AutoAttendant }:<>f__AnonymousType74`2) [Set-CsAutoAttendant_SetExpanded], UndeclaredResponseException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsAutoAttendant_SetExpanded

What do you think about this?
The "[deleted unknown ID]" is really unkown for me, this ID is not used for any callqueue, autoattendant or resource account.
I have no idea what this exeption means.

Any help would be nice!

Thanks

**Comment by JensTrier** [comment]
@dtavb thanks for the feedback! I'm not able to repro this using my own test tenant. My recommendation is to open a Microsoft support case and they will work with you to get it investigated.

**Comment by dtavb** [comment]
ok, thanks for your help.

**Comment by yinzh798** [comment]
Could you use below cmdlet to see if [deleted unknown ID] is any part of auto attendant json string?

$aa = Get-CsAutoAttendant -Identity YOURID
$aa | ConvertTo-Json
