### ISSUE TITLE
Cmdlet not available

### ISSUE THREAD

**Issue by JXG2300** [MicrosoftDocs/office-docs-powershell#10085]
Get-AcceptedDomain cmdlet not available - fyi

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JXG2300, it's available to me in my plain Microsoft 365 E5 organization. If it's not visible to you, it could be an RBAC issue.

When I run the following commands:

```powershell
$Perms = Get-ManagementRole -Cmdlet Get-AcceptedDomain

$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}
```

I get the following output (obviously custom role groups removed):

```powershell
Role                RoleAssigneeType RoleAssigneeName
----                ---------------- ----------------
Distribution Groups RoleGroup        Organization Management
Distribution Groups RoleGroup        Recipient Management

Role                  RoleAssigneeType       RoleAssigneeName
----                  ----------------       ----------------
O365SupportViewConfig PartnerLinkedRoleGroup O365 Support View Only

Role                 RoleAssigneeType RoleAssigneeName
----                 ---------------- ----------------
Retention Management RoleGroup        Records Management
Retention Management RoleGroup        Compliance Management
Retention Management RoleGroup        Organization Management

Role                RoleAssigneeType RoleAssigneeName
----                ---------------- ----------------
Distribution Groups RoleGroup        Organization Management
Distribution Groups RoleGroup        Recipient Management

Role                  RoleAssigneeType       RoleAssigneeName
----                  ----------------       ----------------
O365SupportViewConfig PartnerLinkedRoleGroup O365 Support View Only

Role                 RoleAssigneeType RoleAssigneeName
----                 ---------------- ----------------
Retention Management RoleGroup        Records Management
Retention Management RoleGroup        Compliance Management
Retention Management RoleGroup        Organization Management

Role                 RoleAssigneeType     RoleAssigneeName
----                 ----------------     ----------------
MyDistributionGroups RoleAssignmentPolicy Default Role Assignment Policy

Role            RoleAssigneeType RoleAssigneeName
----            ---------------- ----------------
Mail Recipients RoleGroup        Recipient Management
Mail Recipients RoleGroup        Organization Management
Mail Recipients RoleGroup        Custom Mail Recipients
Mail Recipients RoleGroup        Test Mail Recipients Only role

Role                    RoleAssigneeType RoleAssigneeName
----                    ---------------- ----------------
View-Only Configuration RoleGroup        Hygiene Management
View-Only Configuration RoleGroup        Organization Management
View-Only Configuration RoleGroup        Compliance Management
View-Only Configuration RoleGroup        View-Only Organization Management

Role                        RoleAssigneeType RoleAssigneeName
----                        ---------------- ----------------
Remote and Accepted Domains RoleGroup        Organization Management
```

Role                        RoleAssigneeType RoleAssigneeName
----                         ----------------     ----------------
MyDistributionGroups RoleAssignmentPolicy Default Role Assignment Policy

Role            RoleAssigneeType RoleAssigneeName
----            ---------------- ----------------
Mail Recipients RoleGroup        Recipient Management
Mail Recipients RoleGroup        Organization Management
Mail Recipients RoleGroup        Custom Mail Recipients
Mail Recipients RoleGroup        Test Mail Recipients Only role

Role                    RoleAssigneeType RoleAssigneeName
----                    ---------------- ----------------
View-Only Configuration RoleGroup        Hygiene Management
View-Only Configuration RoleGroup        Organization Management
View-Only Configuration RoleGroup        Compliance Management
View-Only Configuration RoleGroup        View-Only Organization Management

Role                        RoleAssigneeType RoleAssigneeName
----                        ---------------- ----------------
Remote and Accepted Domains RoleGroup        Organization Management
```
 
Do you see something similar when you run those commands?

**Comment by yogkumgit** [comment]
@JXG2300 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
