### ISSUE TITLE
Connect-IPPSSession fails with error on Linux

### ISSUE THREAD

**Issue by Clifra-Jones** [MicrosoftDocs/office-docs-powershell#10098]
After upgrading to Exchange Online Powershell V3 I cannot connect to Security & Compliance.
Connect-IPPSSession throws the following error.

ResourceUnavailable: Processing data from remote server ps.compliance.protection.outlook.com failed with the following error message:
ERROR_WSMAN_INVALID_SELECTORS: The WS-Management service cannot process the request because the request contained
invalid selectors for the resource.  For more information, see the about_Remote_Troubleshooting Help topic.

I've removed and re-installed PSWSMan and I am not able to connect to Exchange Online using the -UseRPSSession (this did not work until I re-installed WSMan)

Below is a verbose attempt to connect:

Connect-IPPSSession -UserPrincipalName x-cwilliams@.... -Verbose    VERBOSE: Returning precomputed version info: 3.0.0
VERBOSE: ModuleVersion: 3.0.0
VERBOSE: [ThreadID: #] Trying to get a new token from AAD
VERBOSE: [ThreadID: #] Trying to acquire token silently as UPN is given
VERBOSE: [ThreadID: #] Successfully able to force refresh a token in user based flow either because token is expired or claims is passed silently.
VERBOSE: [ThreadID: #] Successfully got a token from AAD
VERBOSE: Importing cmdlet 'Add-EXOClientTelemetryWrapper'.
VERBOSE: Importing cmdlet 'New-CmdletLogger'.
VERBOSE: Importing cmdlet 'New-EXOClientTelemetryFilepath'.
VERBOSE: Importing cmdlet 'Push-EXOTelemetryRecord'.
VERBOSE: Importing cmdlet 'Clear-ActiveToken'.
VERBOSE: Importing cmdlet 'Get-ConnectionContext'.
VERBOSE: Importing cmdlet 'Get-ConnectionInformation'.
VERBOSE: Importing cmdlet 'Get-EXOBanner'.
VERBOSE: Importing cmdlet 'Get-HelpFiles'.
VERBOSE: Importing cmdlet 'New-EXOModule'.
VERBOSE: Importing cmdlet 'New-ExoPSSession'.
VERBOSE: Importing cmdlet 'Test-ActiveToken'.
VERBOSE: ConnectionContext Removed
ResourceUnavailable: Processing data from remote server ps.compliance.protection.outlook.com failed with the following error message:
ERROR_WSMAN_INVALID_SELECTORS: The WS-Management service cannot process the request because the request contained
invalid selectors for the resource.  For more information, see the about_Remote_Troubleshooting Help topic.

**Comment by chrisda** [comment]
@Clifra-Jones, you should open a support ticket. Report back here with any information that can help improve documentation.

**Comment by yogkumgit** [comment]
@Clifra-Jones Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
