### ISSUE TITLE
Set-User and WindowsEmailAddress/PrimarySMTPAddress

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/office-docs-powershell#10091]
Today we learnt that running set-user against an account where the PrimarySMTPAddress does not match the WindowsEmailAddress , the command will verify if those two attributes match, and if not, it will update PrimarySMTPAddress property value to WindowsEmailAddress. This is in an Exchange On-Premises environment.

It may be of help to document this behavior in the command page, as I have not seen this behavior documented anywhere else, and it seems like this may be impactful for organizations that have this type of configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae09acf-5413-eb3c-e4c7-2481b7b178f5
* Version Independent ID: d0d555a7-de13-0173-7a8c-e13587b334bc
* Content: [Set-User (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-user?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-User.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-User.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dkotars, the description of the WindowsEmailAddress parameter alludes to what you're saying. I remember doing a bunch of testing and updating the description several years ago:

> Using the WindowsEmailAddress parameter on a recipient has one of the following results:
>
> - In environments where the recipient is subject to email address policies (the EmailAddressPolicyEnabled property is set to the value True for the recipient), the WindowsEmailAddress parameter has no effect on the WindowsEmailAddress property or the primary email address value.
> - In environments where the recipient isn't subject to email address policies (the EmailAddressPolicyEnabled property is set to the value False for the recipient), the WindowsEmailAddress parameter updates the WindowsEmailAddress property and the primary email address to the same value.

And, the PrimarySmtpAddress parameter also alludes to this (but from the other direction):

> If you set the EmailAddressPolicyEnabled parameter to $false, you can specify the primary address using the PrimarySmtpAddress parameter, but that means the email addresses of the mail user no longer automatically updated by email address policies.
>
> The PrimarySmtpAddress parameter updates the primary email address and WindowsEmailAddress property to the same value.

So, what additional information needs to be said and where to say it?

**Comment by dkotars** [comment]
Hi Chris - Nope I think we're good then. I know myself, customer and a few peers most likely didn't read all the way down. Let me point that out. Sorry for the fire drill. :-(

**Comment by chrisda** [comment]
OK.

Thanks for the feedback.

Closing
