### ISSUE TITLE
Connect-MicrosoftTeams doesn't pass device info

### ISSUE THREAD

**Issue by read-0nly** [MicrosoftDocs/office-docs-powershell#10092]
I can't tell if I just missed the documentation on this or if it's actually just the base behavior, but Connect-MicrosoftTeams fails conditional access for not passing the device cert on authentication, leaving an entry with no device info in signin audit logs. This makes it fail anything checking for device state, either azure trust type or intune compliance.

Since the app it uses to connect is also not a valid target for ConAcc exceptions, I can't seem to open up just an exception for this traffic either.

Did I miss something? I see there's a certthumbprint parameter, but that seems to be for app login, not to provide the device info. Would there be another way to instruct connect-microsoftteams to include device auth on login?

**Comment by read-0nly** [comment]
looks like the preview version of the module handles proper modern auth - this might fix the device auth issue to. will update (and close) if it does

**Comment by get-itips** [comment]
Hello @read-0nly 
Here, we are limited to documentation fixes and improvements, is there any article you see needs a fix? Didn't test it myself but if the Teams PowerShell currently doesn't provide that you can propose that here https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

Thanks

**Comment by read-0nly** [comment]
Sorry, you can go ahead and close this, and i'll follow up there if necessary
