### ISSUE TITLE
Issue about using "Manager" for -RecipientFilter

### ISSUE THREAD

**Issue by Kylex0407** [MicrosoftDocs/office-docs-powershell#10090]
Hi team, I get confused about the using of Manager in [this article](https://learn.microsoft.com/powershell/exchange/recipientfilter-properties#:~:text=of%20the%20group.-,Manager,-manager).

![2](https://user-images.githubusercontent.com/66714240/198176975-06743af9-72e6-4ba1-819f-4c8c435c4740.png)

Here is test in my tenant:
![1](https://user-images.githubusercontent.com/66714240/198177038-7c121ec4-5aa6-486e-b0fc-5a92a851dda3.png)

When use "-ne $null", I could find this mailbox. But cannot find this mailbox when use "Manager -eq "Admin_User"".

This caused that I don't know which value should be used when try to create a distribution group based on Manager.

Could you help me about this one?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3762ada1-99d6-fa6d-fbd7-524003f8c3b2
* Version Independent ID: 03e801b7-fa14-b5fb-8600-131c9e73292f
* Content: [Filterable properties for the RecipientFilter parameter](https://learn.microsoft.com/en-us/powershell/exchange/recipientfilter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/recipientfilter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/recipientfilter-properties.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Kylex0407, in the past, I've found that many of those 'identify the user' properties require the DistinguishedName (DN) value, and I confirmed that here. When you use the DistinguishedName value for the manager, it works:

```powershell
PS C:\Users\jdoe> Get-Mailbox "Admin User" | Format-List DistinguishedName

CN=Admin User,OU=contoso.onmicrosoft.com,OU=Microsoft Exchange Hosted Organizations,DC=NAMPR18A002,DC=PROD,DC=OUTLOOK,DC=COM

PS C:\Users\jdoe> Get-Recipient -RecipientPreviewFilter {Manager -eq 'CN=Admin User,OU=contoso.onmicrosoft.com,OU=Microsoft Exchange Hosted Organizations,DC=NAMPR18A002,DC=PROD,DC=OUTLOOK,DC=COM'}

Name    RecipientType
----    -------------
OUB1    UserMailbox
```

Curiously, the following easier version does not work:

```powershell
PS C:\Users\jdoe> $x = (Get-Mailbox "Admin User").DistinguishedName
PS C:\Users\jdoe> $x

CN=Admin User,OU=contoso.onmicrosoft.com,OU=Microsoft Exchange Hosted Organizations,DC=NAMPR18A002,DC=PROD,DC=OUTLOOK,DC=COM

PS C:\Users\jdoe> Get-Recipient -RecipientPreviewFilter {Manager -eq $x}
```
