### ISSUE TITLE
Get-UrlTrace and Get-SafeLinksDetailReport

### ISSUE THREAD

**Issue by BaDBob1** [MicrosoftDocs/office-docs-powershell#10100]
Hey all, I've been having this issue for several weeks. I believe "Get-UrlTrace" was deprecated, and I now find Get-SafeLinksDetailReport in the Microsoft documentation.

For several weeks, however, all I get when running "Get-SafeLinksDetailReport" (no matter what arguments are being used) is We cannot currently process your request, please wait a few minutes and try again
  +CategoryInfo : InvalidOperation: (:) [Get-SafeLinksDetailReport], FfoReportingException.

I need to try and get a definite answer to this click that happened on the 24th before the 7 day window expires, so does anyone know how I can get click data now?

**Comment by chrisda** [comment]
@BaDBob1, according to [here](https://learn.microsoft.com/microsoft-365/security/office-365-security/view-email-security-reports#email-security-report-changes-in-the-microsoft-365-defender-portal)  Get-URLTrace was deprecated in June 2021, and any links to the Get-URLTrace topic redirect to Get-SafeLinksAggregateReport.

It appears that Get-SafeLinksAggregateReport has data for the last 90 days, so you should try that.

But, you should also open a support ticket about the problems with Get-SafeLinksDetailReport.

**Comment by BaDBob1** [comment]
Thanks Chris and that's what I ended up doing. They're working on it now.

**Comment by yogkumgit** [comment]
@BaDBob1 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
