### ISSUE TITLE
BypassSecurityGroupManagerCheck not a valid parameter

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/office-docs-powershell#10106]
V3 module installed.

When executing Remove-DistributionGroupMember in PowerShell 7 in an Azure Function in a DoD Tenant the following error occurs:

ERROR: A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'

Everything else seems to work correctly other than this parameter. Last time it was known to work for me was in version 2.0.5 in a commercial tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c15e59ac-c8d2-eb5e-deb0-711f09b3abe0
* Version Independent ID: 7b7e2adc-1ae1-abce-9028-28e7e3b4d66b
* Content: [Remove-DistributionGroupMember (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/remove-distributiongroupmember?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-DistributionGroupMember.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Remove-DistributionGroupMember.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jebalert, you should open a support ticket. Report back here if there's anything we can do to improve the documentation.

**Comment by yogkumgit** [comment]
@jebalert Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
