### ISSUE TITLE
sha1 certificate requirement

### ISSUE THREAD

**Issue by cohaw** [MicrosoftDocs/office-docs-powershell#10101]
Some feedback on certificate usage inconsistencies discovered during our journey from basic authentication to modern authentication, specifically with regards to Exchange Online (EOLv2).  

Things seem to be getting better in terms of how examples are starting to be presented for both "PowerShell 7" (core) and "Windows PowerShell".  Thank you!

One thing that I was just grappling with and seems odd is the requirement to use a sha1 certificate with EOLv2's Connect-ExchangeOnline when using Windows PowerShell.  The error message is very misleading as it states that the certificate could not be used for signing and possible reasons include use of .NET 4.6 or to use a (non-CNG) certificate, (it was not CNG, it was sha256).  This seems like something that needs to be addressed, since sha1 was found to be insecure back in 2005.  

EOLv2 on PowerShell 7 works fine with a SHA256 certificate.  And interestingly, Microsoft.Graph works fine with a SHA256 certificate from Windows PowerShell.  For now, I will use two certificates with my app registration, one for EOLv2 and one for Microsoft.Graph.

To be clear:

Works: Windows PowerShell + EOLv2 + sha1 cert
Works: Windows PowerShell + Microsoft.Graph + sha256 cert
Works: PowerShell 7 + EOLv2 + sha256 cert
Works: PowerShell 7 + Microsoft.Graph + sha256 cert

Does not work: Windows PowerShell + EOLv2 + sha256 cert

**Comment by chrisda** [comment]
@cohaw, you should open a support ticket about this, to a) complain about the misleading error, and b) to ask why PowerShell 5.1 only works with a SHA1 cert and not a SHA256 cert.

The [existing documentation](https://learn.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#step-3-generate-a-self-signed-certificate) does say that a SHA1 certificate is required, but that is, I'm sure, presuming Windows PowerShell 5.1 with no consideration for PowerShell 7. So, based on your testing, that statement might require clarification.

You didn't say, but I would presume that PowerShell 7 works fine with a SHA1 certificate?

It seems to make sense for the CBA connections to support SHA256 certificates (both in Exchange Online PowerShell and Security & Compliance PowerShell) in Windows PowerShell 5.1.

And, of course, make sure you're using the latest version of the module, which is now v3.0.0, and is referred to as the EXOV3 module.

**Comment by yogkumgit** [comment]
@cohaw Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
