### ISSUE TITLE
Issue with CsEffectiveTenantDialPlan for inbuilt Dialplan for CN

### ISSUE THREAD

**Issue by ranukher** [MicrosoftDocs/office-docs-powershell#10104]
when we dial any number with Zero in MSTeams in China its taking the default dialplan and omitting leading zero hence long distance calls are failing

Description=CN Long Distance Dialing Rule;Pattern=^0(\d+)$;Translation=+86$1;Name=CN Long Distance;IsInternalExtension=False

this pattern needs to be modified to include zero

suggested change 
Pattern=^0(\d+)$ --> Pattern=^(0\d+)$

**Comment by ranukher** [comment]
it seems PstnNumberService is overriding tenant dialplan rules is there a way to modify it?
MS Ticket Number #33626218

**Comment by get-itips** [comment]
Hello @ranukher 
How are you? Here, we are limited to documentation fixes and improvements, is there any article that you see needs a fix?
Thanks

**Comment by ranukher** [comment]
I think its not related to Powershell module, rather its an advisory TM455097.
hence closing it. Thanks for the help guys
