### ISSUE TITLE
Set-MailboxMessageConfiguration -SignatureHtml update needed

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/office-docs-powershell#10111]
Now, that Feature ID: 60371 - Outlook for Windows: Signature cloud settings - are GA
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Outlook&searchterms=60371

This page / documentation needs to be updated, on how to set the SignatureHtml.

Set-MailboxMessageConfiguration -Identity user@domain.com -SignatureHtml 'test signature'

Existing Note should be removed:

> Note: This parameter doesn't work if the Outlook roaming signatures feature is enabled in your cloud-based organization. Currently, the only way to make this parameter work again is to open a support ticket and ask to have Outlook roaming signatures disabled in your organization.

And information on how to set the SignatureHtml for various signatures can be updated via powershell, since Outlook roaming signatures feature enabled on tenant level.

Thank you,
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36d9fd24-705e-4fa4-7ab0-9c35c31b013e
* Version Independent ID: 9cab50c8-7f41-40e2-ae3f-1be6ae94b28e
* Content: [Set-MailboxMessageConfiguration (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-mailboxmessageconfiguration?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by hkusulja** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/issues/8537

**Comment by hkusulja** [comment]
@chrisda "Outlook roaming signatures" are not anymore beta, they are GA, as per https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Outlook&searchterms=60371
so please check with product group about powershell info / update docs

**Comment by chrisda** [comment]
@hkusulja, I'm confused. That link you provided says this:

> Your Signature settings are stored in the cloud, so your experience is consistent when you access Outlook for Windows on any computer. This feature has been delayed and will only be available in Beta Channel.
 
That's the only reason I added the Beta Channel thing in my suggested text.

So, are we back to the old days where SignatureHtml just works for everyone no matter what? No caveats or stipulations?

Or, is it the case where if you have Outlook roaming signatures enabled in your organization, then the SignatureHtml parameter doesn't work?

**Comment by hkusulja** [comment]
@chrisda Outlook roaming signatures are not anymore delayed, anda are not beta anymore, they are fully available and GA as per link above.

**Comment by jkrrv** [comment]
I'm confused.  I had support disable roaming signatures in my organization a few months ago.  Can I now have them re-enabled, but now be able to set SignatureHtml content via PowerShell?  This is a pretty messy rollout.
