### ISSUE TITLE
App tokens - connect works, but can't access data

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10124]
I'm using 4.9.0 of the Teams Powershell module and have followed the instructions on how to connect to Microsoft Teams and am abled to log in (and verified that tokens have proper information), but when I attempt to call Get-CsOnlineUser, I get 

Get-CsOnlineUser : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following
error message : The client cannot connect to the destination specified in the request. Verify that the service on the
destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service
running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following
command on the destination to analyze and configure the WinRM service: "winrm quickconfig". For more information, see
the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Get-CsOnlineUser
    + CategoryInfo          : ResourceUnavailable: (:) [Get-CsOnlineUser], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Teams.C
   onfigApi.Cmdlets.GetCsOnlineUser

I'm able to connect using user tokens with the same tenant/client IDs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed0dce05-8bfd-0bfa-3753-0eb193852703
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by pbafna03** [comment]
Hi @sarollins, 

1 possible reason could be the Admin roles, can you please check if the relevant [Admin roles](https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles#teams-roles-and-capabilities) are assigned and try with a fresh Connect-MicrosoftTeams. 

Also, assuming this is from the Commercial environment?

**Comment by pbafna03** [comment]
Hi @sarollins, 

It didn't come through properly in the above comment; however, I was not referring to the App permissions rather the Admin Roles assigned to the app (ref - https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles#teams-roles-and-capabilities).

**Comment by yogkumgit** [comment]
@pbafna03 Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
