### ISSUE TITLE
ProxySBC parameter explanation missing

### ISSUE THREAD

**Issue by pgavrailov** [MicrosoftDocs/office-docs-powershell#10129]
The explanation of the ProxySBC is not available in Parameters section

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a99ede2-bbc2-c56d-6fb0-33db74417f54
* Version Independent ID: cf4bfc0e-fd8d-d5ca-5432-798af72a8885
* Content: [Set-CsOnlinePSTNGateway (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csonlinepstngateway?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@pgavrailov Thanks for the feedback. I have a PR out that adds it. Feel free to close this issue.
