### ISSUE TITLE
Start-ManagedFolderAssistant - Missing informations about parameters

### ISSUE THREAD

**Issue by McDoMaster** [MicrosoftDocs/office-docs-powershell#10120]
Hi,

This page is missing some details about parameters, specially on :
1. **-B2DumpsterArchiver**
2. -**B2IPMArchiver**

Those parameter seems to be useful in Exchange Online.

Also, the parameters aren't specified in the man of _Start-ManagedFolderAssistant_

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0404960d-05e8-6e6f-8063-ebed163ecefd
* Version Independent ID: d79b2d09-a176-d22e-e5ad-49a8fa22df2a
* Content: [Start-ManagedFolderAssistant (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/start-managedfolderassistant?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@McDoMaster, empty parameter descriptions are a known issue, especially with 1300+ cmdlets and 13,000+ parameters. See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for more details.

Do you have links to other content that mentions using these parameters?

Consider the web topics the single source of truth. Those same topics are converted into XML and checked back into code for help at the command line, but that process occurs rather infrequently.

**Comment by yogkumgit** [comment]
@McDoMaster Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by luckman212** [comment]
So back to the original question: any idea what `-B2DumpsterArchiver` actually does? @yogkumgit @chrisda

**Comment by chrisda** [comment]
@luckman212, I do not, and I don't really know who to ask. If was important, other sources would be telling you to use it for particular scenarios. Since that apparently isn't happening, I wouldn't worry about it.

**Comment by luckman212** [comment]
Ok @chrisda. I stumbled in here looking for a way to kickstart a dehydration of the Primary mailbox into the IPA (In-Place Archive) and had already tried `Start-ManagedFolderAssistant`. According to my research, there is nothing that can be done other than "wait" ([up to 7 days][1], apparently!) 📆 📆 📆 📆 📆 📆 📆

[1]: https://learn.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide&tabs=teams-retention#how-long-it-takes-for-retention-policies-to-take-effect
