### ISSUE TITLE
New Alert with Condition

### ISSUE THREAD

**Issue by mfalc** [MicrosoftDocs/office-docs-powershell#10147]
Hi! I'm trying to create a custom activity alert with condition, but this error appear:

"**New-ActivityAlert**: Parameter set cannot be resolved using the specified named parameters."

Can you specify how -Condition works? 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a8e72ae-dd9a-86af-996f-150840021663
* Version Independent ID: 0d1876a0-608d-c28c-4e94-7ce2fc9f44cd
* Content: [New-ActivityAlert (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-activityalert?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ActivityAlert.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ActivityAlert.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Your best way forward is to open a support ticket.

**Comment by yogkumgit** [comment]
@mfalc Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
