### ISSUE TITLE
Please update parameters for Set-CsTeamsMessagingPolicy

### ISSUE THREAD

**Issue by rsta7540** [MicrosoftDocs/office-docs-powershell#10141]
[Enter feedback here]
Could the updated parameter options please be reviewed for this cmdlet?  Under syntax options, there is one that just says "-Allow" and when I connect to a tenant and choose Get-CsTeamsMessagingPolicy I see several more parameters that can likely be set for the policy, namely:

AllowChatWithGroup
AllowCommunicationComplianceEndUserReporting
AllowFluidCollaborate
AllowFullChatPermissionUserToDeleteAnyMessage
AllowPasteInternetImage
AllowSecurityEndUserReporting
AllowSmartCompose
AllowUserDeleteChat
AllowVideoMessages

However, I don't see the parameter AllowUserEditMessage, which is listed on the doc as an available parameter in the cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed7e3515-4648-49c1-487c-dffc4eb55d23
* Version Independent ID: 0ba323cf-90ea-58bd-2f77-9826e1450d53
* Content: [Set-CsTeamsMessagingPolicy (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csteamsmessagingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMessagingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsMessagingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@get-itips Please update.

**Comment by get-itips** [comment]
@yogkumgit Already investigating this.
@rsta7540 Some or all these parameters are from features not yet released, I am trying to confirm and I'll get back. Thanks

**Comment by get-itips** [comment]
Some info
AllowChatWithGroup and AllowSecurityEndUserReporting
    - Added recently
    - In process of being rolled out
 
AllowUserDeleteChat
- Was just added to the doc.
