### ISSUE TITLE
Parameter AllowPrivateTeamDiscovery takes no values

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/office-docs-powershell#10155]
Hi,
the Paramter -AllowPrivateTeamDiscovery allows no change. I've tried it in various tenants to set it to false or true. No error occurs but the value keeps null.

**Comment by wmblocker** [comment]
Hi @yogkumgit, what was your need to set this property? The feature that is controlled by this attribute is not rolled out yet.

**Comment by get-itips** [comment]
Exactly, the feature is not yet rolled out, once it is available, it will be documented.
Thanks
