### ISSUE TITLE
Error in page

### ISSUE THREAD

**Issue by GhostWins** [MicrosoftDocs/office-docs-powershell#10158]
[Введите отзыв здесь]
Hello, i found error in page
-IncludeOrgContent
{{ Fill IncludeOrgContent Description }}

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта learn.microsoft.com с вопросом на GitHub.*

* ID: 0f7f0a23-5b87-02f2-5bce-eddc3413f7f4
* Version Independent ID: 6694e76a-b1e0-9cc6-08ab-beb0cf388e75
* Content: [New-ComplianceSearch (ExchangePowerShell)](https://learn.microsoft.com/ru-RU/powershell/module/exchange/New-ComplianceSearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@GhostWins , empty parameter descriptions are a known issue, especially with 1300+ cmdlets and 13,000+ parameters. See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for more details.

Do you have links to other content that mentions using this parameter? Or are you just reporting that the description is empty?

**Comment by yogkumgit** [comment]
@GhostWins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
