### ISSUE TITLE
Get-QuarantineMessageHeader hangs

### ISSUE THREAD

**Issue by ssndu** [MicrosoftDocs/office-docs-powershell#10151]
Get-QuarantineMessageHeader hangs for a very long time and doesn't return even though the parameters passed are correct, module is up to date and connection to exchange is up. There is no exception thrown either.
Kindly help to fix this.
Already tried various combinations as shown in the documentation.
Get-QuarantineMessageHeader -Identity  <message id>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e7eb500-7eb4-9613-3213-8d89ad116408
* Version Independent ID: fb745f9b-9c80-eab2-c3de-f3c32af982f4
* Content: [Get-QuarantineMessageHeader (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-quarantinemessageheader?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-QuarantineMessageHeader.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-QuarantineMessageHeader.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ssndu, you should open a support ticket. Report back here with any improvements to the documentation.

**Comment by ssndu** [comment]
Thx for the quick response! Kindly share a link for the same!

**Comment by chrisda** [comment]
From any admin center (for example, security.microsoft.com), click the greenish 'Need help?' thing at the bottom right:

![image](https://user-images.githubusercontent.com/33166947/202310775-a8be7787-64b1-4a19-96ba-4f94d76eac72.png)

**Comment by yogkumgit** [comment]
@ssndu Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
