### ISSUE TITLE
Export-QuarantineMessage hangs

### ISSUE THREAD

**Issue by ssndu** [MicrosoftDocs/office-docs-powershell#10152]
Export-QuarantineMessage hangs for a very long time and doesn't return even though the parameters passed are correct, module is up to date and connection to exchange is up. There is no exception thrown either.
Kindly help to fix this.
Already tried various combinations as shown in the documentation.
Export-QuarantineMessage -Identity  <message id>
Having the same issue with Get-QuarantineMessageHeader.

Get-QuarantineMessage works fine, i'm able to fetch the list of messages and identities.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e7eb500-7eb4-9613-3213-8d89ad116408
* Version Independent ID: fb745f9b-9c80-eab2-c3de-f3c32af982f4
* Content: [Get-QuarantineMessageHeader (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-quarantinemessageheader?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-QuarantineMessageHeader.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-QuarantineMessageHeader.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ssndu, you should open a support ticket about this.

**Comment by yogkumgit** [comment]
@ssndu Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
