### ISSUE TITLE
Get-CSOnlineUser "GetSteppablePipeline" error when utilized via a PowerShelL JEA Session

### ISSUE THREAD

**Issue by dotnvo** [MicrosoftDocs/office-docs-powershell#10161]
Hoping someone here can assist, I can't assess whether there's an update to the Microsoft Teams module that may help or perhaps I need to change something, but I'll do my best to explain.

Currently, we are utilizing JEA (Just Enough Administration) for a web front end to connect to a PowerShell backend. The web app is essentially a tool we provide to end users and IT pros at our organization to essentially provide the ability to look up information about users to help troubleshoot problems.

We often create 'wrapper' commands to expose to our web front end that utilize all sorts of modules. This works really well as JEA locks things down like providers etc. and if a command needs those things, we can simply do a wrapper command instead of exposing the actual command to our front end.  We currently use the Microsoft Teams module (I've been using 4.9 in our test environment) to pull information (for example, `Get-Team`, `new-team`, `set-team` are all commands we use in our custom 'wrapper' commands). This works just fine. However, we are migrating to Teams Telephony and we are working on a new feature which involves getting information from Get-CSOnlineUser. We created a wrapper command for it, locally and via a normal remote session, the wrapper command works as expected. We can run the command and it returns data. The command really is simple, here's what's doing the 'work':

```powershell
try {
            $TeamsUser = Get-CsOnlineUser -Identity $UPN

            #return data to console
            $TeamsUser
            
        } catch {

            $errMsg = "Attempting Get-CSOnlineUser failed for $UPN. " + $_.Exception.Message
            Write-Error -Exception $_.Exception -Message $errMsg -ErrorAction Stop
        }
```

I think this is a pretty common thing to do with JEA as the docs also mention wrapper commands quite a bit. In this case, so far it's very simple - just trying and catching terminating errors and retossing the error out in the error stream. Again, no issues, this works when we use it locally or via a normal remote session. However, via a JEA powershell session we run into this error:

```powershell
Attempting Get-CSOnlineUser failed for USERHERE. Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element produced an object that was
not valid. It must result in a command name, a script block, or a CommandInfo object."
At line:1 char:1
+ Invoke-Command -Session $session -ScriptBlock {Get-CCICSOnlineUser -U ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], MethodInvocationException
    + FullyQualifiedErrorId : System.Management.Automation.MethodInvocationException,Get-CCICSOnlineUser
```

I modified the JEA session configuration to allow for FullLanguage temporarily (We run the session as a RestrictedRemoteServer in NoLanguage mode), and re-registered the config. To confirm it was working in fulllanguage mode I did a few things like.. see if I could assign and use variables in that session, which I could. However, the behavior did not change for the command above and I still received the GetSteppablePipeline error. I tracked down the code to this file starting around line 5804 in 4.9: https://www.powershellgallery.com/packages/MicrosoftTeams/4.9.0/Content/exports%5cProxyCmdletDefinitionsWithHelp.ps1 the function for this cmdlet starts around 5804. It seems like others were expressing some similar issues here: https://learn.microsoft.com/en-us/answers/questions/750440/exception-calling-34getsteppablepipeline34-while-u.html but this thread died and I'm not sure it's exactly what I'm seeing.

I have been trying some other versions of the Teams module as well but no luck yet.

Unfortunately, I'm feeling stumped and not sure where to go from this point. I am not sure this is an 'issue' with the module or not and figured creating an issue might be the best place to start as my google - fu has not returned much info regarding our specific use case. 

Thanks in advance for any assistance!

**Comment by dotnvo** [comment]
FYI, still impactful for 4.9.1. I'm currently using a workaround. Instead of simply calling the `Get-CSOnlineUser` in my wrapped function, I'm creating an entirely new runspace (by way of creating a PowerShell Object) then adding a script in that PowerShell Object, reconnecting Teams via a new session, and invoking it, then disposing it.

**Comment by get-itips** [comment]
Hello @dotnvo 
How are you?
For your request, the best would be to open a support request, as here we are limited to documentation changes and improvements, like typos or incorrect information.
Thanks

**Comment by get-itips** [comment]
I'll pass your feedback on @dotnvo thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @dotnvo Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
