### ISSUE TITLE
Update for new Place tags please

### ISSUE THREAD

**Issue by NHawk257** [MicrosoftDocs/office-docs-powershell#10167]
There appears to be new flags for this cmdlet, please update to include the "SpaceType", "CustomSpaceType" and "Desks" options.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7af332a3-efc1-49aa-24c2-64b5031a2420
* Version Independent ID: f47bc209-aa9e-f337-1cfa-b8a727a9f780
* Content: [Set-Place (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-place?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
SpaceType over the last two years, SpaceType has been [added](https://github.com/MicrosoftDocs/office-docs-powershell/pull/6846), [removed](https://github.com/MicrosoftDocs/office-docs-powershell/pull/7308), and then [added again](https://github.com/MicrosoftDocs/office-docs-powershell/pull/10175/commits/5b0e89461f70be3a345c454977a1d19677bde879).

I'll look into CustomSpaceType and Desks.

**Comment by chrisda** [comment]
Be advised that in my plain Microsoft 365 E5 tenant, I don't see any of those parameters on Set-Place (including SpaceType).

Perhaps they're in the process of being rolled out?

**Comment by yogkumgit** [comment]
@NHawk257 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by NHawk257** [comment]
It doesn't look like anything was done? If these commands are in the process of being rolled out, MS needs to update this documentation. I am seeing this in my E3 tenant.

**Comment by yogkumgit** [comment]
@chrisda

**Comment by chrisda** [comment]
@NHawk257, today I examined the available parameters on the Set-Place cmdlet in a Microsoft 365 Business Premium tenant, a Microsoft 365 E3 tenant, and a Microsoft 365 E5 tenant using the following command, and I got the following output in all three:

 ```powershell
PS C:\Users\jdoe> (Get-Command Set-Place).parameters.keys | Sort-Object

AsJob
AudioDeviceName
Building
Capacity
City
Confirm
CountryOrRegion
Debug
Desks
DisplayDeviceName
ErrorAction
ErrorVariable
Floor
FloorLabel
GeoCoordinates
Identity
InformationAction
InformationVariable
IsWheelChairAccessible
Label
MTREnabled
OutBuffer
OutVariable
Phone
PipelineVariable
PostalCode
State
Street
Tags
Verbose
VideoDeviceName
WarningAction
WarningVariable
WhatIf
```

As you can see, no SpaceType or CustomSpaceType parameters, but I now see a Desks parameter. So, I added a note to the existing SpaceType parameter description about it not being available everywhere, and I added the Desks parameter empty.

I created a workspace as described [here](https://learn.microsoft.com/exchange/troubleshoot/outlook-issues/create-book-workspace-outlook#how-to-create-a-workspace) and attempted to add a value for Desks (which is of type RecipientIdParameter[], meaning one or more recipients) using every conceivable identity value for an existing mailbox, and I kept getting the error:

`Parameter 'Desks' cannot be used with place type ''`

If I tried the command on a plain room mailbox, I got the error:

`Parameter 'Desks' cannot be used with place type 'Room'`

I see _property_ values SpaceType and CustomSpaceType in the output of Get-Place, but we don't document the output of most Get- cmdlets (too many changing and unmodifiable properties).

Also, I'm curious: in your organization, what is the output of the following commands? (I get nothing):

```powershell
$Perms = Get-ManagementRole -Cmdlet Set-Place -CmdletParameters SpaceType

$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}
```

**Comment by NHawk257** [comment]
Hi Chris,

As of today, I am seeing the same as you are with the set-place cmdlet. I
also do not see any management roles for SpaceType or CustomSpaceType but I
do for "Desks".

When I do get-place however, I am still seeing the flags with no values set
to them:
[image: image.png]

Best regards,
Evan Ashdown.

**Comment by chrisda** [comment]
@NHawk257, thanks for the response. I did some further testing and determined that the Type parameter on Set-Mailbox has a new value of Desks:

```powershell
PS C:\Users\jdoe> Set-Mailbox touchdown -Type oiewf8oew89o

Cannot process argument transformation on parameter 'Type'. Cannot convert value "oiewf8oew89o" to type "Microsoft.Exchange.Management.RecipientTasks.ConvertibleMailboxSubType". Error: "Unable to match the identifier name oiewf8oew89o to a valid enumerator name. Specify one of the following enumerator names and try again:
Regular, Shared, Room, Equipment, Workspace, Desk"
```

Yet when I try to change the value of an existing Room, Equipment, or Workspace mailbox to Desk, I get the following error:

```powershell
PS C:\Users\chrisda> Set-Mailbox touchdown -Type Desk

Converting mailbox type to "Desk" isn't allowed.
    + CategoryInfo          : NotSpecified: (touchdown:ADUser) [Set-Mailbox], ErrorMailboxTyp...llowedException
    + FullyQualifiedErrorId : [Server=MW4PR15MB4332,RequestId=c71fb2f3-880d-4aee-96bc-bf6efcd7475,TimeStamp=1/4/2023 5:48:39 PM] [Failure   Category=Cmdlet-ErrorMailboxTypeConversionNotAllowedException] 4917A7B4,Microsoft.Exchange.Management.RecipientTasks.SetMailbox
```

I get the same error when I try to adjust the [create a Workspace](https://learn.microsoft.com/exchange/troubleshoot/outlook-issues/create-book-workspace-outlook#how-to-create-a-workspace) instruction with the Type value Desks (instead of Workspace), and I get the same error.

It would appear that the Desk parameter on Set-Place and the Desk Type value on Set-Mailbox aren't fully functional.

**Comment by yogkumgit** [comment]
@NHawk257 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
