### ISSUE TITLE
Get-csTeamsMeetingPolicy :Invalid Credential Provide valid credential

### ISSUE THREAD

**Issue by bbteam17** [MicrosoftDocs/office-docs-powershell#10168]
Hi All,
Env:
pwsh: 7.3.0
 MicrosoftTeams: 4.9.0 ( win && linux  have same issue) 

we have an issue   in same session 
![image](https://user-images.githubusercontent.com/32478068/203295305-76f24f03-7916-4880-80a9-302f738f9cfb.png)

I also try  execute in docker  container , when I restart  container then  working again  but  same problem occurs  randomly in few minute later.

**Comment by pbafna03** [comment]
Hi @bbteam17, 

This issue is specific to version 4.9.0 and was fixed in 4.9.1, please check with that. 

Thanks,
