### ISSUE TITLE
Provided Instructions for Connect-IPPSSession with cert thumbprint do not work 

### ISSUE THREAD

**Issue by nccerhostmaster** [MicrosoftDocs/office-docs-powershell#10162]
Examples provided are
`Connect-ExchangeOnline -CertificateFilePath "C:\Users\navin\Desktop\automation-cert.pfx" -CertificatePassword (Get-Credential).password -AppID "36ee4c6c-0812-40a2-b820-b22ebd02bce3" -Organization "contosoelectronics.onmicrosoft.com"`

`Connect-IPPSSession -CertificateThumbPrint "012THISISADEMOTHUMBPRINT" -AppID "36ee4c6c-0812-40a2-b820-b22ebd02bce3" -Organization "contosoelectronics.onmicrosoft.com`"

After substituting known working values for the thumbprint, App ID and Org, the Connect-ExchangeOnline command works as expected.

However the Connect-IPPSSession command does not work. Instead, it provides an interactive user authentication prompt, which causes the connection to fail. This appears to be due to a bug in the module which assumes the existence of an environment value that only exists in Powershell Core, not in Windows. 
To work around this bug you can define the missing environment value 

`$Global:IsWindows = $true`

https://serverfault.com/questions/1113075/connect-ippssession-with-certificatethumbprint-cmdlet-showing-sign-in-popup

The documentation should be clarified to indicate that it only works with Powershell Core unless the workaround is applied. 
The module should also be fixed to not depend on Core, but that's a different bug report. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication in Exchange Online PowerShell and Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps&source=docs#connection-examples)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
OK. I added the following note to the Connection Examples section:

> - If a **Connect-IPPSSession** command present a login prompt, run the command: `$Global:IsWindows = $true` before the **Connect-IPPSSession** command.

OK?

**Comment by yogkumgit** [comment]
@nccerhostmaster Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
