### ISSUE TITLE
More information required

### ISSUE THREAD

**Issue by Hazmoid** [MicrosoftDocs/office-docs-powershell#1016]
Need to include all the other variables that can be used when using this command.  many of these are $True or $False settings 
AutomateProcessing
AllowConflicts
BookingWindowInDays
MaximumDurationInMinutes
AllowRecurringMeetings
EnforceSchedulingHorizon
ScheduleOnlyDuringWorkHours
ConflictPercentageAllowed
MaximumConflictInstances
ForwardRequestsToDelegates
DeleteAttachments
DeleteComments
RemovePrivateProperty
DeleteSubject
AddOrganizerToSubject
DeleteNonCalendarItems
TentativePendingApproval
EnableResponseDetails
OrganizerInfo
ResourceDelegates
RequestOutOfPolicy
AllRequestOutOfPolicy
BookInPolicy
AllBookInPolicy
RequestInPolicy
AllRequestInPolicy
AddAdditionalResponse
AdditionalResponse
RemoveOldMeetingMessages
AddNewRequestsTentatively
ProcessExternalMeetingMessages
RemoveForwardedMeetingNotifications
MailboxOwnerId
Identity
IsValid
ObjectState

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06dae8a0-738e-1da1-afad-509c66d39ae1
* Version Independent ID: 7fb9a458-130f-35e2-8754-21b4a38ff5dd
* Content: [Get-CalendarProcessing (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-calendarprocessing?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nsshommo** [comment]
@Hazmoid Thanks for your query. We will get back to you very soon.

**Comment by chrisda** [comment]
@Hazmoid, to be clear, the items you listed are properties in the output, not actual parameter that are available on the cmdlet (if they were parameters, they would definitely be documented). We typically don't go into a lot of detail about the output of cmdlet reference topics (the exceptions are reporting cmdlets). Often, there are properties returned by a Get- cmdlet that aren't even available on the corresponding New- or Set- cmdlets.

But, I hear what you're saying, so I added this line to the DESCRIPTION section:
For details about the properties that are returned in the output of this cmdlet, see Set-CalendarProcessing (https://docs.microsoft.com/powershell/module/exchange/mailboxes/set-calendarprocessing).

Thanks for the feedback.
