### ISSUE TITLE
Certificate based authentication connecting to Security & Compliance

### ISSUE THREAD

**Issue by katskar** [MicrosoftDocs/office-docs-powershell#10178]
Hi,

I have tested version 3.0.0 and certificate based authentication. 

**This works fine:** _Connect-ExchangeOnline -AppId <appid> -CertificateThumbprint <cert thumbprint> -Organization <tenant>.onmicrosoft.com_

**However, connecting to Security & Compliance gives the login prompt:**
_Connect-IPPSSession -AppId <appid> -CertificateThumbprint <cert thumbprint> -Organization <tenant>.onmicrosoft.com_

I rolled back to version 2.0.6-Preview and both connections work fine.

-Katrin

**Comment by katskar** [comment]
Some of the characters went missing in the commands, but you get the picture. organization is my tenant.onmicrosoft.com.

**Comment by katskar** [comment]
Thanks :-)

**Comment by chrisda** [comment]
@katskar, you should open a support ticket about this.
