### ISSUE TITLE
Custom Dimension Name count and the Custom Dimension Value does not match ?

### ISSUE THREAD

**Issue by LanstarGermany** [MicrosoftDocs/office-docs-powershell#10188]
can this be a bug?  Fired the command with only basic parameters ...

```powershell
$ExportActivityExplorer = Export-ActivityExplorerData -StartTime $StartTime -EndTime $EndTime -PageSize 5000 -OutputFormat Csv
Custom Dimension Name count and the Custom Dimension Value does not match.
    + CategoryInfo          : InvalidResult: (:) [Export-ActivityExplorerData], ArgumentException
    + FullyQualifiedErrorId : [Server=VI1EUR06WS042,RequestId=40870449-65ee-45cf-a78e-2e7e7842cdb8,TimeStamp=30/11/2022 16:50:57] [FailureCategory=Cmdlet-ArgumentException] EF4 
   8231D,Microsoft.Exchange.Management.LabelAnalytics.ExportActivityExplorerData
    + PSComputerName        : eur06b.ps.compliance.protection.outlook.com
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f188a25-7afc-f6cf-5d2a-5bc9fd08ca1f
* Version Independent ID: 33ed55ee-de0e-2c0c-2141-9a21083392cd
* Content: [Export-ActivityExplorerData (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/export-activityexplorerdata?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Export-ActivityExplorerData.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Export-ActivityExplorerData.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@LanstarGermany, you should open a support ticket and ask. Report back here with any findings that can help improve the documentation.

**Comment by yogkumgit** [comment]
@LanstarGermany  Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
