### ISSUE TITLE
Authentication_ExpiredToken 

### ISSUE THREAD

**Issue by GorCed** [MicrosoftDocs/office-docs-powershell#10187]
When running against tennants with massive amounts of teams (90k+) I experience the following error.

////
get-team : Error occurred while executing 
Code: Authentication_ExpiredToken
Message: Your access token has expired. Please renew it before submitting the request.
InnerError:
  RequestId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  DateTimeStamp: 2022-11-23T23:19:30
HttpStatusCode: Authentication_ExpiredToken
At line:14 char:6
+ $c = get-team |select -skip $s | select -first $a
+      ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Team], ApiException
    + FullyQualifiedErrorId : Microsoft.Teams.PowerShell.TeamsCmdlets.ErrorHandling.ApiException,Microsoft.Teams.PowerShell.TeamsCmdlets.GetTeam

////

**Comment by get-itips** [comment]
Hello @GorCed 
Here, we are limited to documentation changes and improvements.
For your inquiry the best seems to create a support request, that way, it can reach the product team in case a modification has to be done to the cmdlet/module.
Thank you,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @GorCed Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
