### ISSUE TITLE
-PageCookie parameter explaination is not so clear.

### ISSUE THREAD

**Issue by PramodShedbal** [MicrosoftDocs/office-docs-powershell#10186]
[-PageCookie parameter explaination is not so clear]

Tenant admins may get confuse on how to get this parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f188a25-7afc-f6cf-5d2a-5bc9fd08ca1f
* Version Independent ID: 33ed55ee-de0e-2c0c-2141-9a21083392cd
* Content: [Export-ActivityExplorerData (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/export-activityexplorerdata?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Export-ActivityExplorerData.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Export-ActivityExplorerData.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@PramodShedbal Hope this comment is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by PramodShedbal** [comment]
Thank you @yogkumgit . It would be great if we could add a link to the available filters in this article.

**Comment by chrisda** [comment]
I have no comment.
