### ISSUE TITLE
#SYNTAX is absent

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1019]
Syntax part is absent here. The parameter and example part is also absent. I have searched Technet and didn't find anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 285ff9c8-19c0-d58f-ec16-7ba563a14fa5
* Version Independent ID: 579e58b6-2920-e79e-baa6-87bb67673566
* Content: [Copy-CsVoicePolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/copy-csvoicepolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Copy-CsVoicePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Copy-CsVoicePolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
Synopsis and Description state: "This cmdlet has been deprecated for use with Lync Server 2013 and Lync Online. Administrators should use the Grant-CsVoicePolicy cmdlet to assign voice policies to Lync Online tenant accounts." Closing this one out.
