### ISSUE TITLE
[teams-4.9.1] Get-CsOnlineUser param AccountType

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10198]
Please update description of `AccountType` param to include some more explanation about the meaning of the values?
E.g. it is what's the difference between "User" and "SfbOnPremUser"

The following screenshot shows correlation between "AccountType" and "InterpretedUserType"; and it is not clear at all what's the difference between "User" and "SfbOnPremUser" values

![image](https://user-images.githubusercontent.com/31003608/205245952-da1ec0fa-9b78-4d9a-82ff-f19e28ec189f.png)

```text
Get-Module -Name MicrosoftTeams | select Name, Version

Name           Version
----           -------
MicrosoftTeams 4.9.1


$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @shivtorov 
Looking into this.
Thanks

**Comment by get-itips** [comment]
I could get the information that the article will be updated soon

**Comment by isrumnon** [comment]
Hi @shivtorov can you reach out to me on Teams regarding this issue - isrumnon@microsoft.com

Deleting this message for privacy reasons

**Comment by isrumnon** [comment]
Hi @shivtorov, if the issue is still persisting please reach out to me on Teams. I have shared my alias on the previous reply (you might have got a mail for the same)
