### ISSUE TITLE
AllowMultipleResources parameter not documented

### ISSUE THREAD

**Issue by mastermind3043** [MicrosoftDocs/office-docs-powershell#10199]
My Exchange Online subscription shows a new property "AllowMultipleResources" which is not documented in this page.
Would be nice to know what it does
![image](https://user-images.githubusercontent.com/61656987/205324400-1a287820-84ba-4b74-88a6-dc8282199a4f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d95eb528-ab96-b415-981c-35d50c90dba0
* Version Independent ID: 0433f43b-538d-8000-a11d-69b4a5c97e0e
* Content: [Set-CalendarProcessing (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-calendarprocessing?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mastermind3043, I checked in my ordinary M365 E5 tenant, and I don't see a parameter named AllowMultipleResources on the Set-CalendarProcessing cmdlet.

Available _parameters_, we document. Available _properties in the output of Get- cmdlets_, we typically don't document. The only exception is reporting cmdlets.

The output of a Get- cmdlet inevitably contains the results of parameters from the corresponding New- and Set- cmdlets, although the names might be different. It's also very common to see additional properties in the output of a Get- cmdlet that have nothing to do with what's available on New- or Set-. For example:

- Datacenter only stuff.
- On-premises Exchange only stuff.
- Vestiges from old features that are no longer available.
- New stuff that isn't configurable yet.

Are you seeing documentation from anywhere else that describes setting an AllowMultipleResources value?

**Comment by mastermind3043** [comment]
@chrisda 
Thanks for the detailed explanation. Indeed the Set- cmdlet does not recognize this property as a parameter. I guess it qualifies as _New stuff that isn't configurable yet_.
