### ISSUE TITLE
Able to add MailUniversalDistributionGroup to MailUniversalSecurityGroup through EXO V2

### ISSUE THREAD

**Issue by Steven-Copermans** [MicrosoftDocs/office-docs-powershell#10192]
**Tested commands**
- Update-DistributionGroupMember
- Add-DistributionGroupMember

**Issue**
Using the EXO V2 module, I can add a MailUniversalDistributionGroup to a 'Mail-Enabled Security Group'.
When using the Exchange Online Admin center to add members to a group, MailUniversalDistributionGroups don't even show up.

The main problem I'm having with this, is that Azure AD does not recognize these groups as members (either through PowerShell, Graph API, Azure AD UI, ...
But they are visible in the Exchange Online Admin center & through the use of 'Get-DistributionGroupMember'.

**Expected behaviour**
Relevant Cmdlets should throw an error

**Comment by chrisda** [comment]
@Steven-Copermans, you should open a support ticket about this.
