### ISSUE TITLE
Missing input values

### ISSUE THREAD

**Issue by Frankverharen** [MicrosoftDocs/office-docs-powershell#10193]
Which values are possible for the  -IPAudioMobileMode in the  New-CsTeamsMobilityPolicy
I cannot find it in this document

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7a5f310-effe-ee9f-3750-2537f6d9cde3
* Version Independent ID: c82404cf-1c8b-f76c-822a-2f2f6b9ae18c
* Content: [New-CsTeamsMobilityPolicy (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/new-csteamsmobilitypolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsMobilityPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsTeamsMobilityPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Thanks for your feedback, adding the information
