### ISSUE TITLE
Azure Bot Service work with Federation?

### ISSUE THREAD

**Issue by mefree98** [MicrosoftDocs/office-docs-powershell#102]
Can a CsOnlineApplicationEndpoint be granted a CsExternalAccessPolicy? I have an Azure bot I would like to be able to respond to federated contacts.

**Comment by kenwith** [comment]
I confirmed with @islubin that CsOnlienApplicationEndpoint is currently only for users but she looped in @nkramer whose team owns graph integrations and how policies around those integrations will work (coming soon). Thank you for this feedback @mefree98 ! It is greatly appreciated by the product teams!
