### ISSUE TITLE
New-CsCallQueue missing option that is available in TAC

### ISSUE THREAD

**Issue by darwincr** [MicrosoftDocs/office-docs-powershell#10200]
The Teams Powershell commands New-CsCallQueue and Set-CsCallQueue contain the WelcomeMusicAudioFileId but they dont contain anything like a WelcomeTextToSpeechPrompt

If you setup a teams call queue from teams admin center it does have an option to set a TTS mesasge instead of audio file

Is it not supported in powershell the feature of setting a welcome TTS message in a queue?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b26bf80-4e1f-4172-e003-29fd1a28928c
* Version Independent ID: 7d0d9c25-c6f1-4ae3-b4e3-3b6de536ffa3
* Content: [New-CsCallQueue (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/new-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by darwincr** [comment]
Skip Voicemail System Message is another parameter that is present in teams admin center but i cant find it

**Comment by get-itips** [comment]
Hello, @darwincr I am looking into this

**Comment by get-itips** [comment]
I could confirm this is not currently available but it is planned to be added.
