### ISSUE TITLE
PolicyTemplateInfo is referenced but missing

### ISSUE THREAD

**Issue by DKMiller71** [MicrosoftDocs/office-docs-powershell#10211]
Documentation references a parameter for PolicyTemplateInfo. Details say " Fill PolicyTemplateInfo Description", but no description of valid values or other syntax provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b83609af-4934-9137-7348-abbf61d279de
* Version Independent ID: 51a9a1b5-3b6c-6f28-4cde-01cb3c1a454b
* Content: [New-RetentionCompliancePolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-retentioncompliancepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-RetentionCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DKMiller71, empty parameter descriptions are the price of doing business with 1300+ Exchange cmdlets and 13,000+ related parameters. I can account for availability of parameters in a plain M365 tenant, but I can't account for intent or functionality (Do they work? Are they supposed to be available?). See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for an in-depth explanation.

Do you have links to other content that mentions using this parameter? Or are you just reporting that the description is empty?

**Comment by DKMiller71** [comment]
@chrisda I am working on Compliance Retention Policies and was trying to determine what this parameter did and how I should use it.

**Comment by chrisda** [comment]
@DKMiller71, unless you see information about that parameter from other sources, I would say don't worry about it.

**Comment by yogkumgit** [comment]
@DKMiller71 Hope this comment is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
