### ISSUE TITLE
Documentation says see Example 9 - but no Example 9 exists

### ISSUE THREAD

**Issue by DKMiller71** [MicrosoftDocs/office-docs-powershell#10212]
The documentation under -Filters refers the reader to Example 9, which does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1aa7139-e8c1-3f04-3f00-390d25ceb3d5
* Version Independent ID: 0a9ff2fa-2110-7b63-aeab-0b44fb4c9bc3
* Content: [New-ComplianceSecurityFilter (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-compliancesecurityfilter?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DKMiller71, fixed.

In the future, you too can make fixes like this yourself (no need to open a GitHub issue about it first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing.
