### ISSUE TITLE
Missing documentation for excluding SharePoint and OneDrive

### ISSUE THREAD

**Issue by DKMiller71** [MicrosoftDocs/office-docs-powershell#10213]
Documentations describe filters to exclude mailboxes to prevent a SharePoint admin from searching Exchange mailboxes.  It also mentions that you need a filter to exclude OneDrive and SharePoint sites to prevent an Exchange admin from searching Sharepoint or OneDrive - but no syntax is provided.  And "Site_Path -notlike '*'" fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1aa7139-e8c1-3f04-3f00-390d25ceb3d5
* Version Independent ID: 0a9ff2fa-2110-7b63-aeab-0b44fb4c9bc3
* Content: [New-ComplianceSecurityFilter (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-compliancesecurityfilter?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DKMiller71, [this topic](https://learn.microsoft.com/microsoft-365/compliance/permissions-filtering-for-content-search) seems to be the most authoritative source, and even it doesn't have examples about how to exclude all SharePoint sites.

You should open a support ticket and ask. Report back here with any findings that can help improve the documentation.

**Comment by yogkumgit** [comment]
@DKMiller71 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
