### ISSUE TITLE
Grant-CsTeamsInteropPolicy does not accept Alias for -Identity parameter

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/office-docs-powershell#1021]
`Grant-CsTeamsInteropPolicy` throws an `"Object reference not set to an instance of an object."` error for some users when you only provide the `Alias` rather than the full `UserPrincipleName`/SIP address to the `-Identity` parameter. Other `*-Cs*` accept the `Alias` without worry.

_Example **failure** using `Alias`_
![image](https://user-images.githubusercontent.com/6205899/40061007-d793e90a-584f-11e8-9fd2-9438f93b6a8c.png)

_Example **success** using `Alias`_
![image](https://user-images.githubusercontent.com/6205899/40061303-83ac9ad4-5850-11e8-9994-8cdd8fb0b1c5.png)

There are additional notes, issues and specifics within Microsoft Partner ticket 10196471

**Comment by kenwith** [comment]
@webash - I also noticed in the Description for the cmdlet reference that the cmdlet is being replaced. Here is the documentation on that one and it explains what to use instead of the Grant-CsTeamsInteropPolicy cmdlet. https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsinteroppolicy?view=skype-ps   Closing this one out but please re-open if you have more questions.

**Comment by webash** [comment]
@kenwith so the documentation on this is **very** unclear. TeamsInteropPolicies have only just been created as of a few months ago, and enable our users to choose in the Teams client whether they receive calls in SfB or in Teams. The TeamsUpgradePolicy does not do this, and is about defining where a user will be forced to receive calls. Is the Skype/Teams team going to be releasing something more clear than the typo-filled documentation present for `Grant-CsTeamsInteropPolicy` and `Grant-CsTeamsUpgradePolicy`?

**Comment by kenwith** [comment]
@webash - I agree it is very unclear and I apologize. I will take on following up with the product teams and support on how to make this clearer.

**Comment by kenwith** [comment]
@webash - just an update. Content being cleaned up. In rush to get the content out I wasn't thorough and am learning from it. Here is Pull Request on this: https://github.com/MicrosoftDocs/office-docs-powershell/pull/1031/files

To directly answer your question above, yes, there is also a significant amount of content being developed to clarify the story and process and I will add the links to these cmdlets as well as soon as it publishes. I will leave this issue open until I get the links to the coming documentation to clarify the story into the referenced cmdlets.

**Comment by webash** [comment]
Thanks. We were early adopters of the TeamsInteropPolicy as it appeared to be the way forward for helping those who wanted to live in Teams and move away from SfBO. We're struggling to make sense of the current state. Thanks for your help so far.

**Comment by webash** [comment]
Most notably this guidance is confusing:

> TeamsInteropPolicy are assigned only one of these three built-in instances for which CallingDefaultClient = ChatDefaultClient, and for which AllowEndUserClientOverride = false. The other instances are no longer valid configurations and will not be supported. 

When running `Get-CsTeamsInteropPolicy` for our tenant, we have 6 policies shown. All of which are built-in. We currently grant the policy which includes `AllowEndUserClientOverride = true; Chat = Default; Calling = Default` because it allows our users to choose where things are routed. If they have issues with Teams calling, they can quickly and easily drop themselves back to SfBO. The new guidance is saying that there will instead be an 'Upgrade' policy, but no upgrade needs to occur because both are living side-by-side? Additionally, the Upgrade policy mode is called 'TeamsOnly', which again isn't helpful because our users still need to use SfBO because Teams has broken Skype for Business/Teams federation.

Hopefully the content coming clarifies all of this.

**Comment by kenwith** [comment]
This is really helpful and I am getting this to the product team to incorporate into the docs. Thank you!

**Comment by kenwith** [comment]
@webash - the article from the PM is now live. You can find it here: https://docs.microsoft.com/en-us/MicrosoftTeams/migration-interop-guidance-for-teams-with-skype

I am also going to add the link to each of the cmdlets. There will be more guidance coming too but I wanted to get this out to you. Thanks for your patience and being proactive on this!
