### ISSUE TITLE
-User parameter mentions Security Groups - but should be mail-enabled

### ISSUE THREAD

**Issue by MiBurtan** [MicrosoftDocs/office-docs-powershell#10223]
according to https://learn.microsoft.com/exchange/recipients-in-exchange-online/manage-permissions-for-recipients

mailbox permissions work only with mail-enabled security groups, nothing is mentioned for simple security groups.
however, Powershell allows you to add the permissions & mentions only "security groups" at -User parameter, no error thrown, but the permission itself is then denied for the security group member

expected result - to replace "security groups" with "mail-enabled security groups"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8c466ef-c24d-7acf-ae68-d8c860dc26f8
* Version Independent ID: 42020e48-b76f-cda4-b261-87e6e2721599
* Content: [Add-MailboxPermission (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/add-mailboxpermission?view=exchange-ps&source=docs#-user)
* Content Source: [exchange/exchange-ps/exchange/Add-MailboxPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Add-MailboxPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@MiBurtan Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by MiBurtan** [comment]
Hi Chris, hi Yogesh,

Thank you for both the replies here.
I have further been to Engineering team with this query, and had the confirmation from Brad Hughes (Prin Escal Eng EEE-DEV) that the Add-MailboxPermission cmdlet should NOT allow adding non mail-enabled Security Groups.

Please see below answer the official answer:
 Ok, I've figured out that this is definitely by design. Apparently now when you create non-mail-enabled security groups they are still synced to EXO, however they are invisible to tenant admins. They are RecipientType = Group and RecipientTypeDetails = ExchangeSecurityGroup.  The current code in Add-MailboxPermission allows these types to be added but they should not be valid for permissions.  I'm creating a work-item to make it so these groups cannot be added at all, which should be the correct behavior.

You can follow up with him directly in case of any further questions or concerns.

Have a great day ahead!
Mihaela

**Comment by chrisda** [comment]
@MiBurtan, thanks. I updated the User parameter description with the information you provided.

**Comment by MiBurtan** [comment]
Hi Chris,

Thank you for the update!
Do you know when will this appear in the documentation?
I can see Add-MailboxPermission (ExchangePowerShell) | Microsoft Learn<https://learn.microsoft.com/en-us/powershell/module/exchange/add-mailboxpermission?view=exchange-ps> still shows the old value
[Graphical user interface, text, application, email  Description automatically generated]

Thank you,
Mihaela

**Comment by chrisda** [comment]
@MiBurtan, likely Tu 1/3 ~11:00AM PST (GMT-8).
