### ISSUE TITLE
Get-MoveRequestStatistics: -Analysis and -DiagnosticOnly have "{{ Fill Analysis Description }}"

### ISSUE THREAD

**Issue by danieljphelps** [MicrosoftDocs/office-docs-powershell#10225]
The help for Get-MoveRequestStatistics has no useful information for the -Analysis and -DiagnosticOnly switches. It has the "{{ Fill Analysis Description }}" label in both entries in the document.

This makes it nearly impossible to understand how these items are intended to be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b058d48-3c1e-bcb6-4070-00b144ddc03d
* Version Independent ID: c37947e6-2308-0c18-34ba-25d82f71e2ec
* Content: [Get-MoveRequestStatistics (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-moverequeststatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MoveRequestStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-MoveRequestStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@danieljphelps, whether they're supposed to be used or not is the main question.

Empty parameter descriptions are the price of doing business with 1300+ Exchange cmdlets and 13,000+ related parameters. I can account for availability of parameters in a plain Microsoft 365 tenant, but I can't account for intent or functionality (Do they work? Are they supposed to be available?). See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for an in-depth explanation.

Are you being directed by other content to use those parameters?

**Comment by danieljphelps** [comment]
Since we know that much of Microsoft's documentation is machine-generated, it's surprising (well, maybe not) that a given switch/parameter isn't documented somewhere. I am doing some testing with Get-MoveRequestStatistics, and am trying to understand what the various options actually do. These two are not documented at all, which makes it difficult to know what they're for. (Apparently nobody else has figured it out, as I haven't found the answers elsewhere online just yet.)

**Comment by chrisda** [comment]
@danieljphelps, a rhetorical question, but is it better or worse to acknowledge an available parameter in empty fashion, or to simply leave an available parameter not documented at all? Either way leads to issues.

When it comes to comparing what's documented vs. what's available, I've found it's better to have empty parameter descriptions like this. It starts a discussion/notification process that often leads to the empty parameters being documented, especially when blogs or other content are telling people to use that parameter.

And when I say documented, there's 'documented', and then there's 'documented'. I'd rather have {{ Fill <Parameter> Description }} and not some sit and spin, I'm just guessing description like "The <Blah> parameter does <blah>", simply to check some box that the parameter description is not empty.

It's definitely a balancing act.

**Comment by danieljphelps** [comment]
I agree that at least acknowledging that there is an option is a good start, but it's really just that - a start. But the options can be found by using tab-complete to see them. Those of us who spend a lot of time in PowerShell then try and find what the options are supposed to do.

For example, I was wondering what the -ReportOnly option did, and found a discussion on GitHub (involving you, I think) where the documentation was ultimately updated to reflect that being an internal Microsoft option.

I'm ultimately trying to find more efficient ways of getting the DataConsistencyScore for a given Exchange Online move request. Get-MoveRequestStatistics seems to take a while to execute, and I've been experimenting with the various options for the cmdlet in hopes of finding one that returns the value more quickly.

As a former newspaper editor, "{{ Fill <Parameter> Description }}" is kind of like "Headline Goes Here" in a newspaper. :)

**Comment by yogkumgit** [comment]
@danieljphelps  Hope this comment is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
