### ISSUE TITLE
Resource account type different in O365 / PowerShell

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10228]
When I execute the following to get information on a resource account

Get-CsOnlineApplicationInstance -Identity 5e001de2-e2b0-4314-a25d-b04f6e70b024 | Select *

ApplicationId     : 11cd3e2e-fccb-42ad-ad00-878b93575e07
DisplayName       : Jasper de Zoet
ObjectId          : 5e001de2-e2b0-4314-a25d-b04f6e70b024
PhoneNumber       :
TenantId          : a5c32d43-5d6f-41a1-a3da-1390153869b6
UserPrincipalName : jdezoet@unimaxlab.com

The ApplicationId indicates this is a call queue (ce933385-9390-45d1-9512-c8d228074e07 is for AutoAttendant)

But when I look in the teams admin portal, it indicates this has a Resource account type of Auto Attendant

![image](https://user-images.githubusercontent.com/45109285/206577842-0152a2ed-ef8e-42b0-a29c-055a3a8032c8.png)

Is there a different cmdlet I should be using?  Also, how do I get access to the Voice routing policy field that now shows up in the teams admin portal

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcb4263-0469-d3fe-d1f8-f3e84
![ResourceAccountTypeWrong](https://user-images.githubusercontent.com/45109285/206577803-00509573-2ec3-488d-ae55-5e933895211c.png)
35c950a
* Version Independent ID: 144af0b9-1753-7988-70fd-60b50f832847
* Content: [Get-CsOnlineApplicationInstance (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/get-csonlineapplicationinstance?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineApplicationInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineApplicationInstance.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @sarollins 
I tested and received the expected guid for AA.
You should query the Voice Routing Policy like this 

`get-csonlineuser aa@contoso.com | fl OnlineVoiceRoutingPolicy`

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
