### ISSUE TITLE
Command fail

### ISSUE THREAD

**Issue by Degies** [MicrosoftDocs/office-docs-powershell#10229]
None of the commands here seem to work on an exch 2016 server. Not in the Exch module or powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1131a3b-58d5-9857-2dd7-217a8424e720
* Version Independent ID: cf1fa48d-dd87-bbd5-507c-7c75705bd36a
* Content: [Get-MailboxPermission (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-mailboxpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailboxPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-MailboxPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Degies, in the [Exchange Management Shell](https://learn.microsoft.com/powershell/exchange/open-the-exchange-management-shell) or [connections using remote Powershell](https://learn.microsoft.com/powershell/exchange/connect-to-exchange-servers-using-remote-powershell), that command should work as documented. There are 4 parameters that are available only in Exchange Online PowerShell, so those definitely won't work in Exchange 2016 PowerShell:

- GroupMailbox
- IncludeSoftDeletedUserPermissions
- IncludeUnresolvedPermissions
- SoftDeletedMailbox

After that, role-based access control [(RBAC)](https://learn.microsoft.com/exchange/permissions/feature-permissions/rbac-permissions) takes over. If your account is member of the Organization Management role group, you should be fine. Get- cmdlets aren't as heavily restricted as New- or Set- cmdlets.

Using the procedures described in [this topic](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions), Get-MailboxPermission is available in the following roles/role groups:

```powershell
[PS] C:\>$Perms = Get-ManagementRole -Cmdlet Get-MailboxPermission
[PS] C:\>$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleA
ssigneeType,RoleAssigneeName}

Role            RoleAssigneeType RoleAssigneeName
----            ---------------- ----------------
Mail Recipients        RoleGroup Organization Management
Mail Recipients        RoleGroup Recipient Management



Role                 RoleAssigneeType RoleAssigneeName
----                 ---------------- ----------------
View-Only Recipients        RoleGroup Compliance Management
View-Only Recipients        RoleGroup Help Desk
View-Only Recipients        RoleGroup Hygiene Management
View-Only Recipients        RoleGroup Organization Management
View-Only Recipients        RoleGroup View-Only Organization Management
```

**Comment by yogkumgit** [comment]
@Degies Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
