### ISSUE TITLE
How to add a dispotion power automate link with powershell

### ISSUE THREAD

**Issue by ayoubelasryRoot** [MicrosoftDocs/office-docs-powershell#10221]
From the documentation, I don't see how we can add a power automated flow link for disposition from PowerShell.

![image](https://user-images.githubusercontent.com/15128999/206315509-049e4c3b-2d44-4324-aca1-52b7a1793157.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: caf95a3e-2a7e-9ab7-dc57-88bd96afc97f
* Version Independent ID: 4e502366-5470-6b75-7076-902a383eba83
* Content: [New-ComplianceTag (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-compliancetag?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceTag.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceTag.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ayoubelasryRoot, two choices:

- Use the UI to create a test one with that selection, and then use the corresponding Get- cmdlet to see the property values, and then use that property/value to create one using the corresponding New- cmdlet.
-  Open a support ticket and ask.

Either way, report back here with any information that can help improve the documentation.

**Comment by yogkumgit** [comment]
@ayoubelasryRoot Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
