### ISSUE TITLE
Not just any onmicrosoft.com domain

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/office-docs-powershell#10259]
The article says to use an .onmicrosoft domain

> Note: Use an .onmicrosoft.com domain for the value of this parameter. Otherwise, you might encounter permission-related issues when you run commands in the app context.

However, it's possible to add multiple oonmicrosoft.com domains (see link below). User added onmicrosoft.com domains also have permission-related issues support says is by design.

https://learn.microsoft.com/microsoft-365/admin/setup/add-or-replace-your-onmicrosoftcom-domain#add-a-new-onmicrosoftcom-domain

The "initial onmicrosoft.com" domain appears to be the only one supported at this time.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13d88f18-3cc8-5f18-8d61-ff7f5fa4e314
* Version Independent ID: 60f9a029-69f3-e65c-6816-fbd414790ce3
* Content: [Connect-ExchangeOnline (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by jonwbstr** [comment]
I'm not entirely sure I'm interpreting the reply correctly. Below they talk about default domain, which can be changed to a not onmicrosoft.com domain...

Most organizations including the one where we had this issue has the initial on Microsoft.com domain as default. I can confirm if changing the default domain makes a difference in a few days.


> We recommend partners to use the default tenant domain value in the parameter ''DelegatedOrganization" , to access the resources within the concerned tenants. Using any other value may cause issues related to permissions and may limit the access to app resources.

**Comment by jonwbstr** [comment]
My mistake, the "default" domain is not an onmicrosoft.com domain for this tenant and also experienced issues. I use the term "initial domain" because that's what the API calls it. The partner center uses the term "primary domain name" in one place and the customer "domain name" in another.

Cheers!

**Comment by chrisda** [comment]
@jonwbstr, I don't know where you go the following quote, so there's nothing I can do about it:

> We recommend partners to use the default tenant domain value in the parameter ''DelegatedOrganization" , to access the resources within the concerned tenants. Using any other value may cause issues related to permissions and may limit the access to app resources.

But, I did change the references to 'primary onmicrosoft.com domain' in the CBA topic and the DelegatedOrganization and Organization parameter descriptions in Connect-ExchangeOnline and Connect-IPPSSession as you can see in the referenced pull request.

If you want to change anything, you can do it yourself. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

**Comment by jonwbstr** [comment]
That was  a quote from support, thanks!

**Comment by chrisda** [comment]
OK. Thanks for the feedback. Closing.
