### ISSUE TITLE
Change to -SharedCalendarSyncStartDate paramater

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/office-docs-powershell#10260]
We need to correct the cmdlet example for this parameter on https://learn.microsoft.com/powershell/module/exchange/set-mailboxcalendarfolder#-sharedcalendarsyncstartdate.

Instead of `Set-MailboxCalendarFolder -Identity "delegate@contoso.com:\Name of shared calendar" -SharedCalendarSyncStartDate` it should be `Set-MailboxCalendarFolder -Identity "delegate@contoso.com:\Calendar\Name of shared calendar" -SharedCalendarSyncStartDate`.

We also need to note that the word "Calendar" needs to be written as the user sees it in his Outlook, so it needs to be in the user's native language; i.e., if we are speaking about German, that it would be "delegate@contoso.com:\Kalender\Name of shared calendar".

Thank you,
Alex Cazacu

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 720289db-3b4d-a6f8-2fea-09317467bae2
* Version Independent ID: f987f693-7e54-d6f6-4f1a-49374b89550f
* Content: [Set-MailboxCalendarFolder (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-mailboxcalendarfolder?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Alex-Catalin, fixed.

In the future, you can make fixes like this directly without opening an Issue first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
