### ISSUE TITLE
Missing mention of required client-site basic authentication setting

### ISSUE THREAD

**Issue by WimVandierendonck** [MicrosoftDocs/office-docs-powershell#10264]
According to the accepted answer on below question and my personal experience it is still necessary to enable Basic authentication client-side.
https://learn.microsoft.com/en-us/answers/questions/1031403/connect-ippssession-with-modern-auth.html
This fact is not mentioned on this page. 
It would be helpful if it did mention it, it is still mentioned on the Connect-ExchangeOnline page for certain scenario's.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 945ab2ea-22ae-814f-8898-fe84b7f29870
* Version Independent ID: 5383d152-988d-b1ee-4957-db5fb6213754
* Content: [Connect-IPPSSession (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/connect-ippssession?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-IPPSSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Connect-IPPSSession.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@WimVandierendonck, I added a link back to the main [Connect to Security & Compliance PowerShell](https://learn.microsoft.com/powershell/exchange/connect-to-scc-powershell) topic in the DESCRIPTION section.

All of the prerequisite information is contained in the topic [About the Exchange Online PowerShell module](https://aka.ms/exov3-module), which is linked to from the Connect-IPPSSession topic and is also linked to from the Connect to Security & Compliance PowerShell topic. I would contend those topics are the first stop for any/all questions related to connecting. The cmdlet reference topic is basically "for more information" about how the individual parameters work.

**Comment by WimVandierendonck** [comment]
Thanks for your updates.
We only started using Connect-IPPSSession after having experienced the shift from having to have basic authentication enabled client-side to not having to have it enabled to use Connect-ExchangeOnline. We were not expecting this to be needed anymore for any cmdlet of EXO V3. Because Connect-ExchangeOnline was working were not expecting to have to go look back at the prerequisites.
So according to me it could help to have an extra mention of it in this article.

**Comment by chrisda** [comment]
Yeah, see the updates in the [second commit](https://github.com/MicrosoftDocs/office-docs-powershell/commit/ee0f85ec7b2f3ae6ec644b57af6d550ba3791bb1):

> **Note**: Currently, this cmdlet still requires Basic authentication to be enabled in WinRM on the local computer. For more information, see [Prerequisites for the Exchange Online PowerShell module](https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#prerequisites-for-the-exchange-online-powershell-module).

OK?

**Comment by WimVandierendonck** [comment]
Excellent.
Thank you.

**Comment by chrisda** [comment]
You're welcome.

Thanks for the feedback.

Closing
