### ISSUE TITLE
Connect-ExchangeOnline not working the same way between modules v2 and v3

### ISSUE THREAD

**Issue by ogouret1** [MicrosoftDocs/office-docs-powershell#10273]
I have started checking all the scripts that use module V2 for my client, I have 2 questions :

- Concerning the Parameter "CommandName" : is there a way to load no cmdlet (only the GET-EXO*) ? In module "v2" i used "-CommandName @()" but it doesn't work anymore with module V3.

- Concerning the Parameter "FormatTypeName": What are the possible values ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13d88f18-3cc8-5f18-8d61-ff7f5fa4e314
* Version Independent ID: 60f9a029-69f3-e65c-6816-fbd414790ce3
* Content: [Connect-ExchangeOnline (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ogouret1, for the first bullet, you should open a support ticket.

For the second bullet, it appears that the FormatTypeName parameter is related to the output of the Get-FormatData parameter. I used a junk value for the parameter and I got the following error:

> Running the Get-FormatData command in a remote session returned no results.

I'll try to update the parameter description. Its Type value is `String[]`, which means it takes multiple text value separated by commas.

**Comment by ogouret1** [comment]
ok, thank you for your quick response

**Comment by yogkumgit** [comment]
@ogouret1 Hope this comment is helpful for you.  We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
