### ISSUE TITLE
New parameters

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/office-docs-powershell#1027]
There are three new parameters associated with this command which are not documented -

SkipDomainValidationForMailUser
SkipDomainValidationForSharedMailbox 
SkipDomainValidationForMailContact 

These allow customers to skip the step that validates the proxy addresses associated with the object are all Accepted Domains.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71eba022-5ade-59d2-b557-c27e821fde1f
* Version Independent ID: 6d2fd8b7-a445-6eba-5b8a-2338e6ac84de
* Content: [Add-RecipientPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/add-recipientpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Add-RecipientPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Add-RecipientPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kellybos I added the new parameters as you described in PR #1037.

Thanks for the feedback.
