### ISSUE TITLE
Missing description text for 'AdditionalAccountsEnabled'

### ISSUE THREAD

**Issue by jalrok** [MicrosoftDocs/office-docs-powershell#10276]
Published description only includes placeholder text.

"
This parameter is available only in the cloud-based service.

{{ Fill AdditionalAccountsEnabled Description }}
"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 022da80e-29cd-f6b5-aa00-48e2d16c4be8
* Version Independent ID: c3353c03-e416-f693-104f-6b6f5955b721
* Content: [Set-OwaMailboxPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jalrok, empty parameter descriptions are a known issue when dealing with 1300+ cmdlets and 13,000+ parameters. Availability vs. functionality of a parameter are two different things. See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) here for a detailed explanation.

So, are you being directed to use that parameter from other content, or are you just pointing out the fact that it's empty?

**Comment by jalrok** [comment]
I was doing an audit of our mailbox polices, both on-prem and cloud. Since
I was unfamiliar with some of the *enabled* settings, I was relying on the
documentation to validate the functionality. In this case, we want to make
sure that 'AdditionalAccountsEnabled' doesn't allow people to use 3rd party
cloud services.

I realize that some settings are for future use, or are deprecated, but the
documentation should state that. Several other settings say something along
the lines of "reserved for internal use", so at least in that case I know
it's not something to worry about (or at least nothing I have control
over). When the doc has something like "{{Fill ...... Description }}" it
just looks like it was forgotten about, and I'm left to determine if it's a
security/policy risk to the business.
