### ISSUE TITLE
Example 1 description and PowerShell do not match

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/office-docs-powershell#10289]
Adaptive Scope Example 1 for Project X states 
`(CountryorRegion = US or Canada) And Department = Finance`

However the PowerShell creates a different Adaptive scope
`(CountryorRegion= US or CA) And Department is not equal to Finance`

This can be confirmed by checking when looking at the created adaptive scope in the Purview admin center
![image](https://user-images.githubusercontent.com/69439002/210177888-2fa44866-130a-4b51-b60e-075893aaf7f0.png)

The correct Powershell to match the description is 
`New-AdaptiveScope -Name "Project X" -LocationType User -FilterConditions @{"Conditions" = @(@{"Conditions" = @(@{"Value" = "US"; "Operator" = "Equals"; "Name" = "CountryOrRegion"}, @{"Value" = "Canada"; "Operator" = "Equals"; "Name" = "CountryOrRegion"}); "Conjunction" = "Or"}, @{"Value" = "Finance"; "Operator" = "Equals"; "Name" = "Department"}); "Conjunction" = "And"}
`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69d37363-bc98-5c58-f378-043fb127e21d
* Version Independent ID: b26cd2ad-41fc-e783-ba78-5bc795097281
* Content: [New-AdaptiveScope (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-adaptivescope?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-AdaptiveScope.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-AdaptiveScope.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@nikki-c, fixed as you described.

Thanks for the feedback.

Closing
