### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/office-docs-powershell#1028]
In the example, the second line in the command should't it be:
New-SPExcelBlockedFileType -FileType XLSM -ExcelServiceApplication $sa, instead of : 
New-SPExcelBlockedExcelFileType -FileType XLSM -ExcelServiceApplication $sa 
? 

The provided example does not work.
Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d2b617-01f7-8576-e797-1346b612c01e
* Version Independent ID: 5b3f4939-af07-d080-dbba-d6ec08b1bedf
* Content: [New-SPExcelBlockedFileType (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spexcelblockedfiletype?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPExcelBlockedFileType.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPExcelBlockedFileType.md)
* Service: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
thank you for your comment.  I have updated and republished topic.
