### ISSUE TITLE
The StartDate can't be older than 92 days from today

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/office-docs-powershell#10291]
Can you update the Start section to include

The StartDate can't be older than 92 days from today.

If you use a start date that is longer than 92 days you will see the following error message

![image](https://user-images.githubusercontent.com/69439002/210178342-4242ab9a-4195-4288-9925-574636edc133.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69d37363-bc98-5c58-f378-043fb127e21d
* Version Independent ID: b26cd2ad-41fc-e783-ba78-5bc795097281
* Content: [New-AdaptiveScope (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-adaptivescope?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-AdaptiveScope.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-AdaptiveScope.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@nikki-c, no worries, but the affected topic/cmdlet was Get-DataRetentionReport, not New-AdaptiveScope, which confused me for a second.

I added the sentence you requested. In the future, you too can make changes like this (and the changes from your other two issues) yourself (no need to open an issue first). Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
