### ISSUE TITLE
-FilterConditons section the example and PowerShell do not match

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/office-docs-powershell#10290]
The text states

> User or Group: Active Directory attributes. For example, for the condition "('Country or region' equals 'US' or 'Canada') and 'Department' equals 'Finance'", use the following syntax: @{"Conditions" = @(@{"Conditions" = @(@{"Value" = "US"; "Operator" = "Equals"; "Name" = "CountryOrRegion"}, @{"Value" = "CA"; "Operator" = "Equals"; "Name" = "CountryOrRegion"}); "Conjunction" = "Or"}, @{"Value" = "Finance"; "Operator" = "NotEquals"; "Name" = "Department"}); "Conjunction" = "And"}

The correct PowerShell is
`@{"Conditions" = @(@{"Conditions" = @(@{"Value" = "US"; "Operator" = "Equals"; "Name" = "CountryOrRegion"}, @{"Value" = "Canada"; "Operator" = "Equals"; "Name" = "CountryOrRegion"}); "Conjunction" = "Or"}, @{"Value" = "Finance"; "Operator" = "Equals"; "Name" = "Department"}); "Conjunction" = "And"}
`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f296664a-de4a-4045-17a0-9a7b50b7980d
* Version Independent ID: 9d9b1cdf-ae45-0565-30b2-13266c29f6b7
* Content: [Set-AdaptiveScope (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-adaptivescope?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-AdaptiveScope.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-AdaptiveScope.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@nikki-c, fixed in both New-AdaptiveScope and Set-AdaptiveScope.

Thanks for the feedback.

Closing.
