### ISSUE TITLE
AllowPrivateTeamDiscovery not supported

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10298]
I'm using version 4.9.1 of the MicrosoftTeams PowerShell Module and when I try to create a new teams channel policy, I get the error

New-CsTeamsChannelsPolicy -Identity "Test" -AllowPrivateChannelCreation $True -AllowPrivateTeamDiscovery $True

A parameter cannot be found that matches parameter name 'AllowPrivateTeamDiscovery'.

Even though the release notes for 4.9.1 say "Functionality remains the same as previous implementation"

Is this a bug or should this be replaced with EnablePrivateTeamDiscovery?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a705a9a-ef02-2453-6267-e0b2908a2ad9
* Version Independent ID: 1a93b451-ab23-3290-0c36-bb8498d01bdb
* Content: [New-CsTeamsChannelsPolicy (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/new-csteamschannelspolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for your feedback, updating the article
