### ISSUE TITLE
Get-Recipient returns different information if I am also running Security & Compliance PowerShell

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/office-docs-powershell#10292]
I have noticed that when I use `Get-Recipient` it returns different information if I am also running Security & Compliance PowerShell.

For example, just running Exchange Online PowerShell  (Connect-ExchangeOnline) the user's CountryorRegion is populated. However when I am also running Security & Compliance PowerShell (Connect-IPPSSession) then the CountryorRegion is blank. There seem to be several difference

**Comment by chrisda** [comment]
@nikki-c, I would say that's by design. Even though several of the same cmdlets are available in both PowerShell environments, they are two completely different PowerShell environments with different RBAC and parameter availability, and are therefore likely to behave differently.

**Comment by yogkumgit** [comment]
@nikki-c Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
