### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by trust11** [MicrosoftDocs/office-docs-powershell#10303]
```
$graphtokenBody = @{   
   Grant_Type    = "client_credentials"   
   Scope         = "https://graph.microsoft.com/.default"   
   Client_Id     = $ApplicationID   
   Client_Secret = $ClientSecret   
}  

$graphToken = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$TenantID/oauth2/v2.0/token" -Method POST -Body $graphtokenBody | Select-Object -ExpandProperty Access_Token 

$teamstokenBody = @{   
   Grant_Type    = "client_credentials"   
   Scope         = "48ac35b8-9aa8-4d74-927d-1f4a14a0b239/.default"   
   Client_Id     = $ApplicationID   
   Client_Secret = $ClientSecret 
} 

$teamsToken = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$TenantID/oauth2/v2.0/token" -Method POST -Body $teamstokenBody | Select-Object -ExpandProperty Access_Token 

$accessTokens = @("$graphToken", "$teamsToken")

```
this code works, but then I get always an Access Error. When I call Get-CsAutoAttendant

PS C:\WINDOWS\system32> Get-CsAutoAttendant -First 10
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get-CsAutoAttendant : Access Denied.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.1\custom\Merged_custom_PsExt.ps1:3921 char:13
+             $internalOutput = Microsoft.Teams.ConfigAPI.Cmdlets.inter ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ First = 10, S...ludeStatus =  }:<>f__AnonymousType16`8) [Get-CsAutoAttendant_Get1], UndeclaredResponseException
    + FullyQualifiedErrorId : Forbidden,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsAutoAttendant_Get1

Where can I find easy which permissions are necessary? And how to set them lost already 8h work time :-(

Thx
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8eda0b1-3667-3124-946f-bbc581120725
* Version Independent ID: 450eaa1b-b14b-c248-790e-13eb583e434b
* Content: [Get-CsAutoAttendant (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/get-csautoattendant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsAutoAttendant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsAutoAttendant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by captainhook** [comment]
See #10025
