### ISSUE TITLE
The is no description for a switch

### ISSUE THREAD

**Issue by nicoride93** [MicrosoftDocs/office-docs-powershell#10319]
The switch -BccBlocked doesnt have a description 
![image](https://user-images.githubusercontent.com/5413171/211570436-d5537300-b130-4cce-829b-99a440fd4f21.png)

I dont know if that is intended to be like that or is actually an issue

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73241a5f-aabf-89a3-ce35-6c790b0a10cd
* Version Independent ID: 8742e952-e7d1-1bcf-73cd-c6fec3ec483b
* Content: [New-DistributionGroup (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-distributiongroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-DistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-DistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@nicoride93, it's intended to acknowledge the availability of the parameter without knowing whether it's supposed to be available (yet?) or if it's fully functional. See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) here for a detailed explanation about empty parameter descriptions.

Are you being directed to use that parameter from other content, or are you just pointing out the fact that it's empty?

**Comment by nicoride93** [comment]
Sorry for the delay.

Yes it answer my question

Thanks all!
