### ISSUE TITLE
-AllowConflicts clarification

### ISSUE THREAD

**Issue by timjordanatteck** [MicrosoftDocs/office-docs-powershell#10312]
For flag -allowconflicts change wording of 

The AllowConflicts parameter specifies whether to allow conflicting meeting requests. Valid values are:

    $true: Conflicts are allowed. The recurring meeting

to

The AllowConflicts parameter specifies whether to allow conflicting meeting requests. Valid values are:

    $true: Conflicts are allowed. **A** recurring meeting

as the allow conflicts flag is applicable to both recurring and individual meetings and the current wording is confusing to make it seem like it only applies to recurring.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d95eb528-ab96-b415-981c-35d50c90dba0
* Version Independent ID: 0433f43b-538d-8000-a11d-69b4a5c97e0e
* Content: [Set-CalendarProcessing (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-calendarprocessing?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@timjordanatteck, OK. Fixed.

In the future, you too can make changes like this yourself without opening an issue first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
