### ISSUE TITLE
 Installing the module for Skype for Business Online? The link explains the TeamsModule installation.

### ISSUE THREAD

**Issue by trust11** [MicrosoftDocs/office-docs-powershell#10310]
Hi. I just need installing the module for Skype for Business Online. When I follow the [link](https://learn.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell), then it is explained how to install the Microsoft Teams Module. But the Module does not have the cmdlets which Skype for Business has.

Any ideas?

Cheers Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2648ec32-2716-4f6e-20f1-1a989aa8cc45
* Version Independent ID: 53e81f24-1e27-9c50-439b-7916e7d1045d
* Content: [SkypeForBusiness Module](https://learn.microsoft.com/en-us/powershell/module/skype/?source=recommendations&view=skype-ps)
* Content Source: [skype/skype-ps/skype/skype.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/skype.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @trust11 
SfBO module was deprecated and cmdlets were incorporated into the Teams PS Module.
What is the cmdlet you are not finding in the Teams PS module?
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @trust11 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
