### ISSUE TITLE
AllowUserDeleteChat parameter missing from Set-CsTeamsGuestMessagingConfiguration

### ISSUE THREAD

**Issue by munindersingh** [MicrosoftDocs/office-docs-powershell#10328]
AllowUserDeleteChat parameter missing from Set-CsTeamsGuestMessagingConfiguration in https://learn.microsoft.com/en-us/powershell/module/skype/set-csteamsguestmessagingconfiguration?view=skype-ps&branch=main

But its present in Powershell if we run Get-CsTeamsGuestMessagingConfiguration/Set-CsTeamsGuestMessagingConfiguration

**Comment by get-itips** [comment]
Hello @munindersingh 
Parameter has been added to the article.
Thanks!
