### ISSUE TITLE
VideoDeviceName example

### ISSUE THREAD

**Issue by matthewalkr** [MicrosoftDocs/office-docs-powershell#10348]
In example 1, VideoDeviceName is given as "InFocus WXGA Projector". However, I think the VideoDeviceName is the camera, not the screen. This example is misleading. There is a separate "ScreenDeviceName" parameter.

Suggest amending example 1 from "VideoDeviceName" to "ScreenDeviceName"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7af332a3-efc1-49aa-24c2-64b5031a2420
* Version Independent ID: f47bc209-aa9e-f337-1cfa-b8a727a9f780
* Content: [Set-Place (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-place?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@matthewalkr, I changed the example to use the DisplayDeviceName parameter (there's no ScreenDeviceName parameter).

OK?
