### ISSUE TITLE
Get-TeamsAppInstallation:  Missing command

### ISSUE THREAD

**Issue by hanielc** [MicrosoftDocs/office-docs-powershell#10353]
I tried installing two versions of the Microsoft.Teams module (4.6.0 and 4.9.1), and both are missing the Get-TeamsAppInstallation.  How can I get it?

**Comment by pbafna03** [comment]
Hi @hanielc, 

As per the [documentation](https://learn.microsoft.com/th-th/powershell/module/teams/get-teamsappinstallation?view=teams-ps), Get-TeamsAppInstallation at the moment is available only in preview versions. You can check with 4.9.2-preview, ref - https://www.powershellgallery.com/packages/MicrosoftTeams/4.9.2-preview.

Thanks,

**Comment by yogkumgit** [comment]
@pbafna03 Thank you very much for sharing this explanation. @ Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
