### ISSUE TITLE
A parameter cannot be found that matches parameter name 'EnablePrivateTeamDiscovery'

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10356]
I see that the documentation has been updated to show the renamed parameter (EnablePrivateTeamDiscovery), but this does not appear to be valid for versions 4.6.0, 4.7.0 and 4.9.0 of the Teams PowerShell module, as a Get-Help Set-CsTeamsChannelPolicy, still shows the old parameter name

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e8708f8-3be7-7dc6-f3fa-0c889b203ee1
* Version Independent ID: d6fd2904-158d-7831-cab4-277c99d4d23a
* Content: [Set-CsTeamsChannelsPolicy (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csteamschannelspolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @sarollins 
You can find it in 4.9.1 version

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
