### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by kamikazzi1** [MicrosoftDocs/office-docs-powershell#1035]
https://docs.microsoft.com/en-us/powershell/module/skype/new-cscalleridpolicy?view=skype-ps  
this page isn't even complete..  How did this pass any form of quality checks?

**Comment by kenwith** [comment]
@kamikazzi1 - thanks for opening this issue. There is a project underway to get these cmdlet references complete with examples and descriptions. When I migrated from TechNet to docs.microsoft.com a number of cmdlets didn't pull complete content. I am getting this fixed asap and you should see examples within the next couple of weeks for all cmdlets. If you do not please open any issue or contact me directly. Thanks for taking the time on reporting!
