### ISSUE TITLE
Remove-MgUserPhoto went missing

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/office-docs-powershell#10351]
Hi,

**Remove-MgUserPhoto** which you linked here went missing after **1.12.2** https://www.powershellgallery.com/packages/Microsoft.Graph.Users/1.12.2

Is there a new way?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7be034d-0d10-d4e6-fa01-4dc8e6aa6259
* Version Independent ID: e1765bb9-508a-dfe2-c514-1c754f3751d0
* Content: [Remove-UserPhoto (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/remove-userphoto?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-UserPhoto.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Remove-UserPhoto.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@PehDeh, that's more of a Microsoft Graph question. You should open a support ticket and ask.

**Comment by PehDeh** [comment]
yeah but the doku is not correct anymore, so you might want to update it.

**Comment by yogkumgit** [comment]
@chrisda

**Comment by chrisda** [comment]
OK. Reference removed.

Thanks for the feedback.

Closing
