### ISSUE TITLE
Some Text on this page is highlighted in pink when using dark mode browser settings

### ISSUE THREAD

**Issue by DDog80sRocked** [MicrosoftDocs/office-docs-powershell#10359]
I have my Edge settings using dark mode and some parts of text on this page are randomly highlighted in pink.  See screenshot.  
![2023-01-20 15_33_57-Window](https://user-images.githubusercontent.com/42620867/213809559-a40653a6-e701-46cc-adc5-c69373278b11.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80326e44-6beb-8983-57ab-8333608c504b
* Version Independent ID: 8962c0dc-72a3-208a-33de-6a89cd56b6fc
* Content: [Set-UnifiedGroup (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DDog80sRocked, that's odd. I switched myself to dark mode and refreshed the page, but I had no highlghts.

Try switching from dark back to light, refresh the page, then switch back to dark and refresh the page?

**Comment by DDog80sRocked** [comment]
Looks like it's not having the issue today.  I guess this can be closed.  Thanks.
