### ISSUE TITLE
Extension example

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/office-docs-powershell#10357]
Please change your ;ext=100 example to a non-3digit example.  3 digit extensions if I recall correctly are not technically support, or at the very least just a really bad idea, due to potential conflicts with service number normalization rules.  If you're going to use extensions, they should be 4 or 5 digit, or higher I suppose, but don't start people off with the worst example and plant bad ideas.

My two cents anyway.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@Korbyn72 Thanks for the feedback. Not aware of any issues with using 3 digit extensions. Are you referring to conflicts with say dialing 911/112?

**Comment by yogkumgit** [comment]
@JensTrier has the issue been addresses, Please update. Thanks

**Comment by JensTrier** [comment]
Yes, it has.

**Comment by yogkumgit** [comment]
@Korbyn72 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Korbyn72** [comment]
Yah, sorry for my delay.  It wasn't that there was so much an issue, just a bad practice, due to conflicts with service numbers, like 911, 411, 311, 112... ect.  I also believe once upon a time ago, MS stated they would support 3 digit extensions.  I generally try to steer customers away from extensions, but if you're going to do it, do it right and without risk.
