### ISSUE TITLE
Parameter missing in documentation

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/office-docs-powershell#10367]
There is a 'WebHookUrl' parameter that is available in the cmdlet, but it is not listed in the list of parameters on the page documentation. 

The availability / presence of this parameter was published in this tech community article back in May '22 - 

[Extending Microsoft Purview Ecosystem with new APIs, Power Automate and built-in integrations
](https://techcommunity.microsoft.com/t5/security-compliance-and-identity/extending-microsoft-purview-ecosystem-with-new-apis-power/ba-p/3401529#:~:text=Custom%20Webhook%20Trigger%20For%20developers%20who%20are%20interested,a%20registered%20Webhook%20with%20the%20configured%20JSON%20body.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: caf95a3e-2a7e-9ab7-dc57-88bd96afc97f
* Version Independent ID: 4e502366-5470-6b75-7076-902a383eba83
* Content: [New-ComplianceTag (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-compliancetag?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceTag.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceTag.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kstat, I tried the following command in two different Microsoft 365 E5 tenants, and I see no WebHookUrl parameter:

```powershell
PS C:\Users\jdoe> (Get-Command New-complianceTag).parameters.keys | Sort-Object
AsJob
Comment
ComplianceTagForNextStage
Confirm
Debug
ErrorAction
ErrorVariable
EventType
FilePlanProperty
FlowId
Force
InformationAction
InformationVariable
IsRecordLabel
IsRecordUnlockedAsDefault
MultiStageReviewProperty
Name
Notes
OutBuffer
OutVariable
PipelineVariable
Regulatory
RetentionAction
RetentionDuration
RetentionType
ReviewerEmail
Verbose
WarningAction
WarningVariable
WhatIf
```

Perhaps it's in the process of being rolled out?

**Comment by kstat** [comment]
I'm using the ExchangeOnlineManagement PS module version 3.0.0. The below are outputs from the console, which include the WebHookUrl parameter.  

```
PS C:\Users\jdoe> Get-Module Ex* 
```
ModuleType |Version    |PreRelease |Name                                |ExportedCommands
---------- |-------    |---------- |----                                |----------------
Script     |3.0.0                 ||ExchangeOnlineManagement            |{Get-ConnectionInformation, Get-EXOCasMailbox, Ge…

Below cmdlet shows the presence of the param:

```
PS C:\Users\jdoe> (Get-Command New-complianceTag).parameters.keys | Sort-Object
AsJob
AutoApprovalPeriod
Comment
ComplianceTagForNextStage
Confirm
Debug
ErrorAction
ErrorVariable
EventType
FilePlanProperty
FlowId
Force
InformationAction
InformationVariable
IsRecordLabel
IsRecordUnlockedAsDefault
MultiStageReviewProperty
Name
Notes
OutBuffer
OutVariable
PipelineVariable
Regulatory
RetentionAction
RetentionDuration
RetentionType
ReviewerEmail
Verbose
WarningAction
WarningVariable
WebHookUrl
WhatIf 
```

**Comment by chrisda** [comment]
OK. We'll keep this issue open for "a while" to let the feature/parameter saturate. I need to see it to be able to run [platyPS](https://github.com/PowerShell/platyPS) to add it to the topic.

**Comment by yogkumgit** [comment]
@chrisda

**Comment by chrisda** [comment]
That parameter is still not visible to me in my tenant.

**Comment by yogkumgit** [comment]
@chrisda

**Comment by chrisda** [comment]
That parameter is still not visible to me in my tenant.

**Comment by chrisda** [comment]
WebHookUrl is still not visible in my tenant.

**Comment by chrisda** [comment]
@kstat, I'm told the WebHookUrl parameter isn't supposed to be available, so I added it to New/Set-ComplianceTag with the following description:

> This parameter is reserved for internal Microsoft use.

Thanks for the feedback.

Closing
