### ISSUE TITLE
Resource account type different in O365 / PowerShell

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10369]
When I execute the following to get information on a resource account

Get-CsOnlineApplicationInstance -Identity 02BBD029-B061-4F6B-A1F6-50F0095DBF4C | Select ApplicationId, DisplayName

ApplicationId                                                DisplayName
11cd3e2e-fccb-42ad-ad00-878b93575e07 Lunch Counter

The ApplicationId indicates this is a call queue (ce933385-9390-45d1-9512-c8d228074e07 is for AutoAttendant)

But when I look in the teams admin portal, it indicates this has a Resource account type of Auto Attendant

![image](https://user-images.githubusercontent.com/45109285/214175584-03857518-3d95-4ee0-acbc-02c8a936fa81.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcb4263-0469-d3fe-d1f8-f3e8435c950a
* Version Independent ID: 144af0b9-1753-7988-70fd-60b50f832847
* Content: [Get-CsOnlineApplicationInstance (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/get-csonlineapplicationinstance?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineApplicationInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineApplicationInstance.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by shivtorov** [comment]
Are you sure you don't have multiple resource accounts with the same DisplayName?
Maybe you are looking at two different accounts?
(In my tenants, DisplayName for AA and CQ are always the same)

```powershell
Get-CsOnlineApplicationInstance -ResultSize ([System.Int32]::MaxValue) | where DisplayName -like '*Lunch*' | select ApplicationId, DisplayName, UserPrincipalName
```

**Comment by sarollins** [comment]
Yes

***@***.***

**Comment by get-itips** [comment]
Hello @sarollins 
I could not reproduce the behavior you describe.
I think the better would be to open a support request from your tenant.
Thank you
