### ISSUE TITLE
Missing description for cmdlet parameters

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/office-docs-powershell#10366]
Certain parameters listed on the page do not have any description provided.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: caf95a3e-2a7e-9ab7-dc57-88bd96afc97f
* Version Independent ID: 4e502366-5470-6b75-7076-902a383eba83
* Content: [New-ComplianceTag (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-compliancetag?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceTag.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceTag.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kstat, empty parameter descriptions are a known issue when we're dealing with (now) 1400+ Exchange-related cmdlets with 14,000+ parameters. Availability and functionality are two different things. See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) here for a detailed explanation about empty parameter descriptions.

So, are you being directed to use any of those undocumented parameters by blogs, MC Posts, or other content? Or are you just pointing out that the descriptions are empty?

**Comment by kstat** [comment]
Understood about this being a known issue. Feel free to resolve this based on your comments.

**Comment by chrisda** [comment]
OK.

Thanks for the feedback.

Closing
