### ISSUE TITLE
New-CsOnlineApplicationInstance as an application returns Access Denied

### ISSUE THREAD

**Issue by mplm17** [MicrosoftDocs/office-docs-powershell#10363]
Hi,

I'm trying to create a resource account for Teams with the cmdlet New-CsOnlineApplicationInstance, run as an application:

````
Connect-MicrosoftTeams -CertificateThumbprint **** -ApplicationId **** -TenantId ****

Account                              Environment Tenant                               TenantId
-------                              ----------- ------                               --------
****				     AzureCloud  **** 				      ****

New-CsOnlineApplicationInstance -userprincipalname cqteamstest@mydomain.com -applicationID 11cd3e2e-fccb-42ad-ad00-878b93575e07 -displayname "Call Queue Teams Test"
New-CsOnlineApplicationInstance : Access Denied.
At Line:1 : 1
+ New-CsOnlineApplicationInstance -userprincipalname cqteamstest2@mydom ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : ({ body = Micros...CreateRequest }:<>f__AnonymousType6`1) [New-CsOnlineApplicationInstance], UndeclaredResp
   onseException
    + FullyQualifiedErrorId : Forbidden,Microsoft.Teams.ConfigApi.Cmdlets.NewCsOnlineApplicationInstance
````

After some research, I've found that this cmdlet is not supported yet to be running as an app:
> ### Cmdlets Supported
> All cmdlets are supported now, **except for the cmdlets mentioned below**.
> 
> New-Team
> **[Get|Set|New|Sync]-CsOnlineApplicationInstance**
> *-CsUserCallingSettings
> *-CsUserCallingDelegate
> *PolicyPackage*
> *-CsTeamsShiftsConnection*
> *-CsBatchTeamsDeployment*

Found here: https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication

So the 'Access Denied' error is logical.

1) Does the New-CsOnlineApplicationInstance cmdlet is planned to be supported by app-based authentication soon?

2) If I have to use the credential based authentication, what role should I give to the user? I've seen in some other issues/comments that the Teams Administrator was sufficient. But I have a colleague which have this role and is not able to create Resource Accounts in the [Teams Admin Portal](https://admin.teams.microsoft.com/company-wide-settings/resource-accounts).

It could be great to have the informations about the permissions requiered to run the cmdlets, directly in the cmdlet reference, as here: https://learn.microsoft.com/en-us/powershell/module/skype/new-csonlineapplicationinstance?view=skype-ps
(Like in Microsoft Graph: https://learn.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=http) and also the information about what authentication gives access to this cmdlet.

Thanks for your answers

**Comment by get-itips** [comment]
Hello @mplm17 

1. I know that new cmdlets are in the process of being added. If I know something I'll get back and post it here.
2. I was able to create a Teams resource account using a Teams administrator role.

Thanks for your feedback!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @mplm17 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
