### ISSUE TITLE
Using cmdlet to create a retention label with a 'KeepAndDelete' retention action fails erroneously

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/office-docs-powershell#10368]
Please advise if this should be logged elsewhere as this is not a documentation issue, but an issue observed with the cmdlet itself. 

When attempting to create a retention label using the 'KeepAndDelete' retention action, the cmdlet fails erroneously. Refer sample cmdlet input below and the erroneous output - 

`New-ComplianceTag -Name "Test Label with WebHook" -WebHookUrl "Dummy_webhook_URL" -RetentionType ModificationAgeInDays -RetentionAction KeepAndDelete -RetentionDuration 3 -MultiStageReviewProperty '{"MultiStageReviewSettings":[{"StageName":"Stage1","Reviewers":[admin@xyz.onmicrosoft.com]},]}' -IsRecordLabel $true -IsRecordUnlockedAsDefault $false` 

Expected the label to be created as a Record Label can have a 'KeepAndDelete' retention action, which is what was specified as an input parameter. Above cmdlet fails erroneously with below output in the console - 

`New-ComplianceTag: The value 'KeepAndDelete' specified for RetentionAction parameter is invalid, due to IsRecordLabel parameter valid only for retention action Keep and KeepAndDelete.`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: caf95a3e-2a7e-9ab7-dc57-88bd96afc97f
* Version Independent ID: 4e502366-5470-6b75-7076-902a383eba83
* Content: [New-ComplianceTag (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-compliancetag?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceTag.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceTag.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kstat, you should open a support ticket about this issue. Report back here if you discover anything that can help improve the documentation.
