### ISSUE TITLE
The example uses the -Country parameter, but the proper parameter is -CountryOrReigon

### ISSUE THREAD

**Issue by UserPrincipalName** [MicrosoftDocs/office-docs-powershell#10373]
The example uses the -Country parameter, but the proper parameter is -CountryOrReigon

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb216fc0-e37c-9d40-e055-96dbc82e6383
* Version Independent ID: b766db14-fa49-370b-e676-22efcd9da076
* Content: [New-CsOnlineLisCivicAddress (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/new-csonlineliscivicaddress?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@UserPrincipalName thanks for the feedback! Will fix it. Feel free to close this issue
