### ISSUE TITLE
Acceptable CIDR range and IP limits

### ISSUE THREAD

**Issue by lonstev** [MicrosoftDocs/office-docs-powershell#10374]
EOP only recognizes down to /24 subnets for TABL entries.  This should be called out in our documentation.  Additionally, we should call out the number of IPs that we allow here, as that isn't documented either.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d38e4a8-dfd9-b933-48bd-9bf8f6b1f2a8
* Version Independent ID: 557d00d7-6e50-5498-8dd4-1a22641d01bf
* Content: [New-TenantAllowBlockListSpoofItems (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-tenantallowblocklistspoofitems?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-TenantAllowBlockListSpoofItems.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@lonstev, I could make the argument that cmdlet reference topics aren't the best place to repeat such information. The limits for each type of entry are described in the "What do you need to know before you begin?" sections of the respective how-to topics (which also contain PowerShell instructions):

- [Email (and spoof)](https://learn.microsoft.com/microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure#what-do-you-need-to-know-before-you-begin)
- [Files](https://learn.microsoft.com/microsoft-365/security/office-365-security/tenant-allow-block-list-files-configure#what-do-you-need-to-know-before-you-begin)
- [URLs](https://learn.microsoft.com/microsoft-365/security/office-365-security/tenant-allow-block-list-urls-configure#what-do-you-need-to-know-before-you-begin)

Nevertheless, in New-TenantAllowBlockListSpoofItems, I added this sentence to the SpoofedUser parameter description:

> For spoofed senders, the maximum number of entries is 1024.

And in New-TenantAllowBlockListItems, I added the following sentences to the Entries parameter description:

> For senders, files, and URLs the maximum number of allow entries for each type is 500, and the maximum number of block entries for each type is 500 (1000 entries total for each type).
>
> The maximum number of characters in a file entry is 64 and the maximum number of characters in a URL entry is 250.

OK?

**Comment by lonstev** [comment]
Hi Chris,

This is perfect, thank you.  A bit of redundancy, yes, but I think it will help to have this information available in this doc as well.

Thanks!

Lonny Stevens
Support Escalation Engineer, M365 Government
Empowering, Helping, and Advising Customers

Customer Service & Support
+1 (425) 703-1114
***@***.******@***.***>

**Comment by chrisda** [comment]
OK.

Thanks for the feedback.

Closing.
