### ISSUE TITLE
The member 'FileList' in the module manifest is not valid

### ISSUE THREAD

**Issue by chriszohno** [MicrosoftDocs/office-docs-powershell#10383]
I followed the C# sample to connect to Exchange Online PowerShell.  I got this error:

The member 'FileList' in the module manifest is not valid: The path is not of a legal form.. Verify that a valid value is specified for this field in the 'C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\3.1.0\ExchangeOnlineManagement.psd1' file.

Do you have any idea what might be the reason?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75e7a156-cd45-796e-b916-912fd0377668
* Version Independent ID: d6afee4b-3324-705c-ddb9-a9f232146cb9
* Content: [Use C# to connect to Exchange Online PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/connect-to-exo-powershell-c-sharp?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exo-powershell-c-sharp.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/connect-to-exo-powershell-c-sharp.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chriszohno** [comment]
Thanks! I thought it was caused by old .Net Framework. My projects were using .Net Framework 4.6.1. I am getting the same errors after switching to .Net Framework 4.8.

**Comment by yogkumgit** [comment]
@chriszohno Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
