### ISSUE TITLE
Isssue with -IncludeDetailedLabelActions parameter in Get-Label command

### ISSUE THREAD

**Issue by OVar3la** [MicrosoftDocs/office-docs-powershell#10392]
Hello,

We have a script to perform a backup of the sensitivity labels that uses the Get-Label command with the -IncludeDetailedLabelActions $true parameter.

We are getting an error.:
![image](https://user-images.githubusercontent.com/60465209/215744146-e71a066e-6262-42e8-8674-8526f18ab062.png)

PS C:\PSOld> Get-Label -IncludeDetailedLabelActions $true
Cannot process argument transformation on parameter 'Identity'. Cannot convert value "True" to type 
"Microsoft.Office.CompliancePolicy.Tasks.ComplianceRuleIdParameter". Error: "Invalid cast from 'System.Boolean' to 
'Microsoft.Office.CompliancePolicy.Tasks.ComplianceRuleIdParameter'."
    + CategoryInfo          : InvalidData: (:) [Get-Label], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-Label
    + PSComputerName        : eur06b.ps.compliance.protection.outlook.com

Module version ExchangeOnlineManagement: 3.1.0

Any help will be welcome.

Thanks in advance

**Comment by chrisda** [comment]
@OVar3la, it appears IncludeDetailedLabelActions changed from being a Boolean parameter ($rue/$false) to a switch parameter (no value). The last time I checked in late August, it was still Boolean, so the change happened within the last 4 months.

I updated the topic accordingly.

OK?

**Comment by OVar3la** [comment]
The issue is that even treating it as a switch (without the $true value), many of the characteristics of the label are not gathered, p.e color, protection, marking, etc.

Thank you very much for your help!

**Comment by yogkumgit** [comment]
@OVar3la Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
