### ISSUE TITLE
Property "IsInternal" and "AllowedOOFType" are synchronous.

### ISSUE THREAD

**Issue by MithunRathinam** [MicrosoftDocs/office-docs-powershell#10406]
Hello Team,

Please add below note into this public documentation.

->Property IsInternal and AllowedOOFType are synchronous.

•	Set AllowedOOFType:InternalLegcy, IsInternal will be changed to $True automatically.
•	Same way, set IsInternal:$False, AllowedOOFType automatically synced to ExternalLegacy.

Regards,
Mithun Rathinam
Exchange Beta engineer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a6df3cb-3d8f-8b72-9312-7b20e1f941d7
* Version Independent ID: b99e2346-2fd6-c6af-1be1-2b29418ba4c2
* Content: [Set-RemoteDomain (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-remotedomain?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-RemoteDomain.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-RemoteDomain.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MithunRathinam, I added the following text to the descriptions of AllowedOOfType and IsInternal:

> The value of this parameter is affected by the value of the [AllowedOOFType | IsInternal] parameter, and vice-versa:
>
> - If you change the AllowedOOFType parameter to the value InternalLegacy, the IsInternal parameter is changed to the value $true.
> - If you change the IsInternal parameter to the value $false, the AllowedOOFType parameter is changed to the value ExternalLegacy.

OK?

**Comment by MithunRathinam** [comment]
@chrisda , Looks Good Chris. Thank you

**Comment by chrisda** [comment]
Thanks for the feedback.

Closing
