### ISSUE TITLE
Isssue with -IncludeDetailedLabelActions parameter in Get-Label command

### ISSUE THREAD

**Issue by OVar3la** [MicrosoftDocs/office-docs-powershell#10413]
The result of the command with or without the -IncludeDetailedLabelActions parameter, today is the same. Previously with the parameter and the switch to $true the result showed more information, before "Settings", as you can see in the following images:

File -> WI_LabelBackup.json has been executed today with the parameter -IncludeDetailedLabelActions
File -> 2022-06-08_LabelBackup.json is an old file obtained in June 2022. Some attributes do not match, such as the "tooltip" or "color", as it is a previous version... It was executed with the parameter and switch -IncludeDetailedLabelActions $true

![image](https://user-images.githubusercontent.com/60465209/216328353-c87562a9-1f89-497b-b532-0b70d250551c.png)

![image](https://user-images.githubusercontent.com/60465209/216325968-8ee61eec-6cf2-49ad-a560-0312db46f8b9.png)

Has the behavior of the parameter changed, is it possible to get this data in another way?

Thanks in advance for your help.

**Comment by chrisda** [comment]
@OVar3la, you should open a support ticket and ask. Report back here with any findings that can help improve the documentation.

Unclear whether this new behavior is intentional or unintentional.

**Comment by yogkumgit** [comment]
@OVar3la Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks
