### ISSUE TITLE
Typo in the article

### ISSUE THREAD

**Issue by MatiLag** [MicrosoftDocs/office-docs-powershell#10423]
In the description of the example there is a mistake in the recipient. Should be adele@contoso.com
![image](https://user-images.githubusercontent.com/113982925/216811197-772cd4b6-095c-4dbb-9760-403ae986cdd3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37f94b78-3cf4-2200-fae8-b85664ba01ce
* Version Independent ID: 0036d9e4-4a4d-8113-269f-801728138f5d
* Content: [Test-Message (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/test-message?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Test-Message.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Test-Message.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MatiLag, fixed.

In the future, you too can make changes like this directly without opening an issue first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
