### ISSUE TITLE
Email user with telephone number information param missing

### ISSUE THREAD

**Issue by PhilGude** [MicrosoftDocs/office-docs-powershell#10422]
[Enter feedback here]
If using Teams Admin Center for the same function there is a possibility to «  Email user with telephone number information » Why don’t we have the same exposed in a parameter ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@PhilGude Thanks for the feedback! The phone number assignment cmdlet does not support sending the e-mail to the user with the phone number information. We have it in our backlog to add that support, but currently no guarantee or ETA for when it might happen.

As a work-around you can send the e-mail from PowerShell using one of the options available for this, this blog has some ideas https://practical365.com/send-email-powershell-graph/

Feel free to close this item
