### ISSUE TITLE
No error while using older than 90 days start date

### ISSUE THREAD

**Issue by PramodShedbal** [MicrosoftDocs/office-docs-powershell#10425]
Hi Team,
Recently I ran the cmdlet Search-AdminAuditLog with the parameters -StartDate 1/1/2022 and -EndDate 2/1/2023, but I did not receive an error even though the start date is older than 90 days. The cmdlet ran successfully, but I only received the output for the last 90 days, which is as expected.

However, some customers are confused and think that admin audit logs are available for a full year.

**Comment by yogkumgit** [comment]
@PramodShedbal Please indicate which document you are referring to. Thanks

**Comment by chrisda** [comment]
@PramodShedbal, questions:

- I presume you're talking about Exchange Online and not on-premises Exchange Server?
- Is the ask to say the max date range is 90 days?

**Comment by PramodShedbal** [comment]
Hi Chris,

Yes, I’m talking about exchange online. in EXO Powershell if we use the
StartDate more than 90 days, it doesn't throw an error.

referring to this article
https://learn.microsoft.com/en-us/exchange/security-and-compliance/exchange-auditing-reports/view-administrator-audit-log
we can only get the admin audit logs for 90 days.

Audit log entries are kept for 90 days. When an entry is older than 90
days, it's deleted.



However, this article
https://learn.microsoft.com/en-us/powershell/module/exchange/search-adminauditlog?view=exchange-ps
 doesn't talk about 90 days period.


Regards,

Pramod

**Comment by chrisda** [comment]
OK. I added the following line to the DESCRIPTION section:

> In Exchange Online PowerShell, data is available for the last 90 days. You can enter dates older than 90 days, but only data from the last 90 days will be returned.

**Comment by PramodShedbal** [comment]
Thank you so much, Chris.
It really helps the support and customers.

Regards,
Pramod

**Comment by yogkumgit** [comment]
@PramodShedbal Nice that  this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
