### ISSUE TITLE
App tokens / Certificate thumbprint - connection works, but error executing cmdlets

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10436]
When I connect using either app tokens or a certificate thumbprint, after the connection it appears to work as it provides the usual account/tenant feedback

![image](https://user-images.githubusercontent.com/45109285/217318666-52fa6025-1b22-4ec6-bfaf-098cf204471e.png)

If I enter wrong information for token/certificate, PS does provide error information

Once connected, if I try to execute a cmdlet, I get the error

get-csonlineuser : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following
error message : The client cannot connect to the destination specified in the request.

My O365 app registration has the following permissions

![image](https://user-images.githubusercontent.com/45109285/217319090-6ca00b71-9e36-4e1e-87ba-f5fc30fafc9c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed0dce05-8bfd-0bfa-3753-0eb193852703
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by sarollins** [comment]
I also have this role assigned to the O365 app registration

![image](https://user-images.githubusercontent.com/45109285/217356149-5892aeb2-c6e3-47c1-9a3b-9e7e914c0af6.png)

**Comment by pbafna03** [comment]
@sarollins - please try with removing the "application_access_custom_sba_appliance" permission assigned to Skype and Teams Tenant Admin API. And post removing the permission, after a few minutes please do Disconnect-MicrosoftTeams and then Connect-MicrosoftTeams.

**Comment by sarollins** [comment]
Good morning

I made the change you recommended, waited 30 minutes, but I’m still getting the same error

**Comment by sarollins** [comment]
***@***.***

**Comment by sarollins** [comment]
![image](https://user-images.githubusercontent.com/45109285/217673908-99134007-d37f-49ca-bd9f-998cedc90891.png)

**Comment by pbafna03** [comment]
Thanks @sarollins for sharing the updated API permissions, now on trying with a fresh PowerShell instance, is the error same as before?

**Comment by sarollins** [comment]
Yes, a new session for both app tokens and certificate thumbprint yields the same error as before

**Comment by shivtorov** [comment]
I guess you run `Connect-MicrosoftTeams` code as a script, and then trying to use `Get-CsOnlineUser` outside of the script.

Have you tried to execute both `Connect-MicrosoftTeams` and `Get-CsOnlineUser` in the same scope, i.e. both inside the script or both outside the script?

Try adding `Get-CsOnlineUser` into your ".\connect_sfbo_certThumb.ps1" script

**Comment by sarollins** [comment]
Yes, we do

After starting new PS sessions, I execute the commands together, not from a script and I still get the same error for both application tokens and certificate thumbprint

**Comment by yogkumgit** [comment]
@pbafna03

**Comment by yogkumgit** [comment]
@pbafna03 Please comment.

**Comment by pbafna03** [comment]
> @pbafna03 Please comment.

Generally, this error is only seen when the "application_access_custom_sba_appliance" permission is assigned to the app used. But removing that doesn't seem to be helping in this specific instance, so would suggest raising a support request with the details around tenant, app info & the team can check/update accordingly. 

Thanks,

**Comment by yogkumgit** [comment]
@sarollins Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
