### ISSUE TITLE
Not possible to assign channel to CQ using Set-CsCallQueue

### ISSUE THREAD

**Issue by pgavrailov** [MicrosoftDocs/office-docs-powershell#10449]
hi team , 
When I run 
Set-CsCallQueue -Identity $CQID -ChannelId $voiceChannelID

to assign a channel to an existing CQ I get the following error 

FullyQualifiedErrorId : InternalServerError,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsCallQueue_SetExpanded
ErrorDetails          : Something went wrong. Please try again after sometime.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86ade68d-5dc0-c598-a659-8b018cef3e26
* Version Independent ID: 67efa086-edb0-2828-cc14-4c245290e4f3
* Content: [Set-CsCallQueue (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @pgavrailov 
For your scenario, the best would be to contact Support, as here we are limited to documentation issues and improvements.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @pgavrailov Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by pawanmisra** [comment]
@pgavrailov I am also facing the same issue, were you able to fix it? If yes how?
