### ISSUE TITLE
Register-SPOHubsite treating same site with CAPS and small letters as different

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/office-docs-powershell#1044]
is this a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 114697af-1b15-2582-49af-7ae2a8fe1cb0
* Version Independent ID: 6ed31c1e-1706-318b-5030-0e74dd9e875e
* Content: [Register-SPOHubSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/register-spohubsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Register-SPOHubSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Register-SPOHubSite.md)
* Service: **sharepoint-powershell**
* Product: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen a SPO cmdlet for you to review. thanks

**Comment by mganeshphani** [comment]
This probably is not a duplicate entry in my tenant... There is a uncovered scenario in SharePoint Hubsites… 
-> Promote an existing site  as hubsite
-> Delete the site
-> Clear the site from recycle bin as well from backend
-> Create a new site with same name
-> Promote the new site as hubsite

Now you will see two hubsite entries with same underlying site name.. I have three sites in my tenant with such behavior, logged office support ticket(10315684) to remove old hubsite entries

**Comment by marrellsanders** [comment]
@mganeshphani Not saying this is not a bug issue, but I do know you can create multiple sites collections with the same name if the URL is different. I know for sure when you create a site in Teams with the same name, it just appends a number to the url to allow it to create the new site. So curious if your three hubs sites have different URL's?  Just curious, agreed should probably be something to address from Microsoft side.

**Comment by AndreaBarr** [comment]
@mganeshphani Thank you for this feedback

I want to make sur this potential but gets handled properly. Support can handle this to resolution.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
