### ISSUE TITLE
ExchangeOnlineManagement v3 - Cmdlet needs proxy error with some commands when using token authentication

### ISSUE THREAD

**Issue by aconn21** [MicrosoftDocs/office-docs-powershell#10446]
I have recently converted a customer to GDAP authentication. I am able to connect fine using the method documented here: https://learn.microsoft.com/powershell/partnercenter/exchange-online-gdap-app?view=partnercenterps-3.0

I am able to run Get commands fine, e.g. get-mailbox or get-mailboxpermission

However when I try to make a change, I get a 'Cmdlet needs proxy' error. Example:

![image](https://user-images.githubusercontent.com/7642455/217953406-54296216-0d40-43e1-8b8f-8785a15494fc.png)

The above command works fine if I just run Connect-ExchangeOnline and authenticate as Global Admin. So it seems the error is specific to Token Based Auth and GDAP?

**Comment by chrisda** [comment]
@aconn21, a newer 3.1.0 version of the EXO V3 module dropped about a month ago, so you can try that if you aren't already using it.

The next step would be to open a support ticket.

**Comment by aconn21** [comment]
I can confirm I'm using the latest version of 3.1.0, I've logged a ticket, using this issue for them to reference. Lets see how premier support goes.
