### ISSUE TITLE
Connect-IPPSSession doesn't work on Apple M1 Macos Ventura 13.1

### ISSUE THREAD

**Issue by zhipingliu32** [MicrosoftDocs/office-docs-powershell#10458]
When run cmdlet Connect-IPPSSession on powershell installed 7.3.2 installed on MacOS Apple M1 Ventura 13.1 for accessing security and compliance powershell:
It gives error:
OperationStopped: Unable to load shared library 'libpsrpclient' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment
variable:  dlopen(/usr/local/microsoft/powershell/7/libpsrpclient.dylib, 0x0001): tried: '/usr/local/microsoft/powershell/7/libpsrpclient.dylib' (mach-o file, but is an
incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/microsoft/powershell/7/libpsrpclient.dylib' (no such file),
'/usr/local/microsoft/powershell/7/libpsrpclient.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')) dlopen(libpsrpclient.dylib, 0x0001):
tried: 'libpsrpclient.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibpsrpclient.dylib' (no such file), '/usr/lib/libpsrpclient.dylib' (no such file, not in
dyld cache), 'libpsrpclient.dylib' (no such file), '/usr/local/lib/libpsrpclient.dylib' (no such file), '/usr/lib/libpsrpclient.dylib' (no such file, not in dyld cache)
dlopen(/usr/local/microsoft/powershell/7/liblibpsrpclient.dylib, 0x0001): tried: '/usr/local/microsoft/powershell/7/liblibpsrpclient.dylib' (no such file),
'/System/Volumes/Preboot/Cryptexes/OS/usr/local/microsoft/powershell/7/liblibpsrpclient.dylib' (no such file), '/usr/local/microsoft/powershell/7/liblibpsrpclient.dylib' (no
such file) dlopen(liblibpsrpclient.dylib, 0x0001): tried: 'liblibpsrpclient.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibpsrpclient.dylib' (no such
file), '/usr/lib/liblibpsrpclient.dylib' (no such file, not in dyld cache), 'liblibpsrpclient.dylib' (no such file), '/usr/local/lib/liblibpsrpclient.dylib' (no such file),
'/usr/lib/liblibpsrpclient.dylib' (no such file, not in dyld cache) dlopen(/usr/local/microsoft/powershell/7/libpsrpclient, 0x0001): tried:
'/usr/local/microsoft/powershell/7/libpsrpclient' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/microsoft/powershell/7/libpsrpclient' (no such file),
'/usr/local/microsoft/powershell/7/libpsrpclient' (no such file) dlopen(libpsrpclient, 0x0001): tried: 'libpsrpclient' (no such file),
'/System/Volumes/Preboot/Cryptexes/OSlibpsrpclient' (no such file), '/usr/lib/libpsrpclient' (no such file, not in dyld cache), 'libpsrpclient' (no such file),
'/usr/local/lib/libpsrpclient' (no such file), '/usr/lib/libpsrpclient' (no such file, not in dyld cache) dlopen(/usr/local/microsoft/powershell/7/liblibpsrpclient, 0x0001):
tried: '/usr/local/microsoft/powershell/7/liblibpsrpclient' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/microsoft/powershell/7/liblibpsrpclient' (no such
file), '/usr/local/microsoft/powershell/7/liblibpsrpclient' (no such file) dlopen(liblibpsrpclient, 0x0001): tried: 'liblibpsrpclient' (no such file),
'/System/Volumes/Preboot/Cryptexes/OSliblibpsrpclient' (no such file), '/usr/lib/liblibpsrpclient' (no such file, not in dyld cache), 'liblibpsrpclient' (no such file),
'/usr/local/lib/liblibpsrpclient' (no such file), '/usr/lib/liblibpsrpclient' (no such file, not in dyld cache)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication in Exchange Online PowerShell and Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@zhipingliu32, you should open a support ticket about this.

**Comment by JoeCMorgan** [comment]
Was there any update on this @zhipingliu32? We're seeing the same issue on powershell version 7.3.6.

**Comment by zhipingliu32** [comment]
> Was there any update on this @zhipingliu32? We're seeing the same issue on powershell version 7.3.6.
Run the command before "Connect-IPPSSession".
Install-Module -Name PSWSMan
Install-WSMan
