### ISSUE TITLE
More than two Application Instance types

### ISSUE THREAD

**Issue by vlethiec** [MicrosoftDocs/office-docs-powershell#10468]
Hello, 

The documentation page mentions two application IDs and suggests that are the only ones. 

`The following are the application ID's for each type of application instance types:
Auto Attendant: ce933385-9390-45d1-9512-c8d228074e07 Call Queue: 11cd3e2e-fccb-42ad-ad00-878b93575e07`

But based on my customer tenants, I already know around 20 others application IDs. 
The applications IDs are third party products and are the same whatever the customer. 

Two points: 

- The documentation should explain that are not the only ones possible. 

- Do you know a way to get the associated products or a documentation page listing them?

Regards, 

Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: edc6081b-f6d4-f2c3-b12e-5f4df83c31e6
* Version Independent ID: 5cf5edef-643f-10a1-8247-4e14d06ff675
* Content: [Set-CsOnlineApplicationInstance (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csonlineapplicationinstance?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@vlethiec Thanks for the feedback and a good suggestion. I'm not aware if any central list for these other application IDs.

**Comment by yogkumgit** [comment]
@JensTrier
