### ISSUE TITLE
Disconnect-ExchangeOnline  connection prefix support

### ISSUE THREAD

**Issue by jlowery99** [MicrosoftDocs/office-docs-powershell#10479]
The Connect-ExchangeOnline cmdlet supports a -Prefix argument to create multiple ExchangeOnline connections but there is no way to disconnect a specific connection.  Disconnect-ExchangeOnline unconditionally closes all open connections.  This greatly reduces the usefulness of prefixed sessions/connections.

In ExoV2 the underlying PSSession objects could be tracked and closed, but since ExoV3 does not use PSSessions this approach no longer works.

Please add prefixed-connection support to Disconnect-ExchangeOnline, either as a prefixed noun or a -Prefix argument.

**Comment by chrisda** [comment]
@jlowery99, send your request to exocmdletpreview[at]service[dot]microsoft[dot]com.

**Comment by jlowery99** [comment]
Done, thank you.
