### ISSUE TITLE
Presence of command in multiple o365 forests is confusing

### ISSUE THREAD

**Issue by cablechewer** [MicrosoftDocs/office-docs-powershell#10475]
The Get-AdminAuditLogConfig cmdlet is available to users who use Connect-IPPSSession and Connect-ExchangeOnline.  Each of these is a separate Exchange Forest (Connect-IPPSSession connects to the Exchange Online Protection Forest, while Connect-ExchangeOnline connects to the Exchange Mailbox Forest for your tenant) and will return different results.  This is because each Exchange Forest maintains its own configuration.  If you use BOTH connect commands, you may return data from the wrong forest.

If you are checking the UnifiedAuditLogIngestionEnabled setting, make sure that you only run Connect-ExchangeOnline.  
Alternative options to avoid any confusion related to the presence of the command in both forests are to:
1. Only use Connect-ExchangeOnline when you intend to use this cmdlet to check properties in Office 365
2. If you use connect-IPPSSession make sure you use the -Prefix parameter to add a prefix that distinguishes the instance of the Get-AdminAuditLogConfig cmdlet in the Exchange Online Protection Forest from the one in the Exchange Mailbox Forest.

Additional notes for reviewer:
I tried to create Internet ready text above.  However, I don't know if I need to call out the specifics of what each Forest is or if that is a detail that customers don't really need to know.

This same comment may need to be cross posted to https://learn.microsoft.com/microsoft-365/compliance/audit-log-enable-disable

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12092dd4-4226-8d65-987a-14119277bc28
* Version Independent ID: 8cb30ac7-81f3-14d1-7d8a-142b06d647c4
* Content: [Get-AdminAuditLogConfig (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-adminauditlogconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-AdminAuditLogConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-AdminAuditLogConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cablechewer, I made the following changes:

- The Get-AdminAuditLogConfig cmdlet wasn't tagged as being available in Security & Compliance PowerShell, even though it has been for a long time. I decorated it as such.
- I added the following text to the DESCRIPTION section of Get-AdminAuditLogConfig:

  > To check the UnifiedAuditLogIngestionEnabled value in the output of this cmdlet, run the command in Exchange Online PowerShell. The value in Security & Compliance PowerShell is always False and the Set-AdminAuditLogConfig cmdlet (and the UnifiedAuditLogIngestionEnabled parameter) is not available to change it.

- I added the following alert to the Get-AdminAuditLogConfig procedure in [Search the audit log in the compliance portal](https://learn.microsoft.com/microsoft-365/compliance/audit-log-search):

  > [!IMPORTANT]
  > Be sure to run the previous command in Exchange Online PowerShell. Although the **Get-AdminAuditLogConfig** cmdlet is also available in Security & Compliance PowerShell, the *UnifiedAuditLogIngestionEnabled* property is always `False`, even when audit log search is turned on.

- The Get-AdminAuditLogConfig procedure in [Turn auditing on or off](https://learn.microsoft.com/microsoft-365/compliance/audit-log-enable-disable) already had the following alert:

  > [!NOTE]
  > Be sure to run the previous command in Exchange Online PowerShell. You can't use Security & Compliance PowerShell to run this command.

  But I changed it to match the stronger alert from the previous topic.

Changes should be visible Tu 2/21 @ ~10:45AM GMT-8.

**Comment by yogkumgit** [comment]
@cablechewer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
