### ISSUE TITLE
SourceMeetingType for Skype Hybrid Configuration only

### ISSUE THREAD

**Issue by LaureVDH** [MicrosoftDocs/office-docs-powershell#10472]
I am testing the MMS for a customer who has not setup Skype Hybrid Configuration (3 source Skype forests and only 1 tenant). As far as my test go, it seems that you can not specific -SourceMeetingType SfB to only update the Skype Meetings invite when your user have been enabled directly in TeamsOnly mode with TeamsUpgradePolicy set to "UpgradeToTeams", and when Skype is not in Hybrid mode. That could be interesting to specify in the cmdlets requirements when using the PS MMS Cmdlets.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23cbf94a-fe74-20f2-764f-e8fbe6910ffa
* Version Independent ID: 7a8f5cc1-e717-e142-b488-54713a288583
* Content: [Start-CsExMeetingMigration (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/start-csexmeetingmigration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Start-CsExMeetingMigration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Start-CsExMeetingMigration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for your feedback
