### ISSUE TITLE
no longer works

### ISSUE THREAD

**Issue by pthedavie** [MicrosoftDocs/office-docs-powershell#10470]
A valid identity is required to request tokens on behalf of them Parameter name: identity

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8aee06d-30f5-4dd9-4d65-82cfca32849b
* Version Independent ID: fa87b9ae-bea0-17cd-c5a7-9efaac8f7392
* Content: [Set-CsOnlineVoicemailUserSettings (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csonlinevoicemailusersettings?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@pthedavie Thanks for the feedback. The team is investigating this issue. Feel free to close this item.

**Comment by yogkumgit** [comment]
@pthedavie Thank you very much for the contribution and sharing this feedback. As suggested, we proceed here to close it. Appreciate and encourage you to share your feedback in future also.

**Comment by pthedavie** [comment]
Thanks very much
Be well
