### ISSUE TITLE
[Set-CsUserCallingSettings] No Mention to to Set GroupNotificationOverride to $Null or Empty Value

### ISSUE THREAD

**Issue by platinarock** [MicrosoftDocs/office-docs-powershell#10471]
Hello , 

I would like to set GroupNotificationOverride to $Null otherwise this value overrides the Notificationsettings value in the GroupMembershipDetails when you make [Get-CsUserCallingSettings] Best Regards
Example 9
PowerShell

Set-CsUserCallingSettings -Identity user2@contoso.com -GroupNotificationOverride 'Mute'

This example shows how to set the group notification override for user2@contoso.com. This setting overrides any specific notification setting set for the user on any call group the user is a member of.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31cb9cc1-fa53-871b-aead-ff43bf5eacee
* Version Independent ID: 5e56da56-6255-3751-d1ca-6dc49c2c1376
* Content: [Set-CsUserCallingSettings (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsUserCallingSettings.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@platinarock Thanks for the feedback. When you set the GroupNotificationOverride to Ring or Banner, the Teams client is honoring the group notification set on the call group, so basically the same as the initial setting of Null.

An example: User A is a member of User B's call group. The notification setting in User B's call group for User A says Banner. User A has GroupNotificationOverride set to Ring. When a call is forwarded to User A from User B's call group, User A will only get Banner, not the ring.

If you set GroupNotificationOverride to Mute for a user, that setting will precedence over the setting on the call group for the user.

When testing this, you might have to restart the Teams client for changes to the notification settings to take immediate effect.

I'll try to make the above clearer in the documentation page.

**Comment by platinarock** [comment]
Hello ,
@JensTrier 
Thanks you very much for your feedback .

Regards

**Comment by yogkumgit** [comment]
@JensTrier Please update.

**Comment by JensTrier** [comment]
I addressed this in PR 10511

**Comment by yogkumgit** [comment]
@platinarock Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
