### ISSUE TITLE
Better definition of FalsePostive flag

### ISSUE THREAD

**Issue by athornfam2** [MicrosoftDocs/office-docs-powershell#10487]
Long story but MS has blocked thousands and thousands of messages and we were looking at a script to report filtered messages back to MS or to their ML based system to remove a flag on our account. However, the description of the flag -ReportFalsePositive doesn't seem to be the best and we wanted to submit it as a issue for it to be better described. Doesn't say where it goes whether that's MS, Exchange admins, etc..

![image](https://user-images.githubusercontent.com/74559383/220480264-30bd45c9-0ac3-4615-a458-1802602ba5e5.png)

**Comment by chrisda** [comment]
@athornfam2, I changed the first sentence in the description to:

> The ReportFalsePositive switch specifies whether to report the message as a false positive to Microsoft (good message marked as bad). You don't need to specify a value with this switch.

In looking at the various [release from quarantine options for admins](https://learn.microsoft.com/microsoft-365/security/office-365-security/quarantine-admin-manage-messages-files#take-action-on-quarantined-email), that's the only explanation that made sense.

OK?

**Comment by athornfam2** [comment]
Yes, appreciated!
