### ISSUE TITLE
RemoveCanceledMeetings - description missing

### ISSUE THREAD

**Issue by robnorthpower** [MicrosoftDocs/office-docs-powershell#10481]
Hi,

The description is missing for the RemoveCanceledMeetings parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d95eb528-ab96-b415-981c-35d50c90dba0
* Version Independent ID: 0433f43b-538d-8000-a11d-69b4a5c97e0e
* Content: [Set-CalendarProcessing (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-calendarprocessing?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@robnorthpower, empty parameter descriptions are a known issue when we're dealing with 1400+ Exchange-related cmdlets with 14,000+ parameters. Availability and functionality are two different things. See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) here for a detailed explanation about empty parameter descriptions.

So, are you being directed to use that parameter by other sources, or are you just reporting that the description is empty?
