### ISSUE TITLE
Problems with ExchangeOnline module in runbooks

### ISSUE THREAD

**Issue by kpinel** [MicrosoftDocs/office-docs-powershell#10489]
We have just noticed that our runbooks are hitting an error managing mailboxes
![image](https://user-images.githubusercontent.com/875143/220488077-45ed4c41-a1c5-45e2-bd27-8c3ff6876244.png)
This has been occurring over the last few days.
Confirmed that the runbook is using the latest version. 3.1.0 
![image](https://user-images.githubusercontent.com/875143/220488226-dd5df5fa-22af-4f91-a0d7-4989a4be0353.png)
Version on my machine is also the same
![image](https://user-images.githubusercontent.com/875143/220488293-543610d1-d488-458b-a118-8fd04ff31442.png)
No information about this online

**Comment by chrisda** [comment]
@kpinel, you should open a support ticket about this. Report back here with any information that can improve the documentation.

**Comment by kpinel** [comment]
Thanks for the feedback.
I did open a ticket in conjunction with this and what we discovered towards the end of yesterday was that we need to install **PowerShellGet** and **PacketManager** into the runbook modules to allow modules such as this and pnp.PowerShell to perform those self checks. 
We don't have pnp.PowerShell in runbooks as yet and I think, from memory, you can disable the checks in that module.

**Comment by chrisda** [comment]
@kpinel, if you know what to say and where to say it, I would encourage you to make any updates as you see fit to the topic. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md). Just @ include me in the pull request comments so I can edit/approve.

**Comment by kpinel** [comment]
@chrisda 
done. Also trying to get some changes made in the automation accounts blades to have these cmdlets automatically included. Doubt I'll get any traction on that though

**Comment by yogkumgit** [comment]
@kpinel Thank you very much for the contribution . If you find it suitable please proceed to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
