### ISSUE TITLE
Descriptions missing for parameters

### ISSUE THREAD

**Issue by robnorthpower** [MicrosoftDocs/office-docs-powershell#10482]
Hi,

I don't see parameter descriptions for AllowDistributionGroup, AllowMultipleResources, EnforceAdjacencyAsOverlap

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d95eb528-ab96-b415-981c-35d50c90dba0
* Version Independent ID: 0433f43b-538d-8000-a11d-69b4a5c97e0e
* Content: [Set-CalendarProcessing (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-calendarprocessing?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@robnorthpower,  just checked and I don't see any parameter with those names on Set-CalendarProcessing in my standard Microsoft 365 E5 tenant.

Are you listing parameters or properties in the output of Get-CalendarProcessing? If you're talking about properties in the output, we make no effort to document those for most cmdlets; too much churn and too many instances of unconfigurable properties.

**Comment by robnorthpower** [comment]
I'm sorry about that. I can see that these are properties delivered by the Get-CalendarProcessing cmdlet, but not in Set. Please consider this issue closed
