### ISSUE TITLE
OTPEnabled dependecies?

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/office-docs-powershell#10483]
Hi Team, is the OTPEnabled boolean in dependency to the enabled OTP Provider in Azure AD or can we enable OME OTP without enabling OTP on Azure AD level at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9edd072e-c0a9-352b-05e0-1572d512d931
* Version Independent ID: 6e8b9549-55f9-36bd-d8a1-8a219eaf0c71
* Content: [Set-OMEConfiguration (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-omeconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OMEConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-OMEConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SRE93, you should open a support ticket and ask. Report back here with any findings that can help improve documentation.

**Comment by yogkumgit** [comment]
@SRE93 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
