### ISSUE TITLE
Add below NOTE to this Public Document

### ISSUE THREAD

**Issue by MithunRathinam** [MicrosoftDocs/office-docs-powershell#10499]
Hello Team,

Please add below NOTE to this public doc : https://learn.microsoft.com/powershell/module/exchange/set-hostedconnectionfilterpolicy

NOTE:
The ability to add IPv6 ranges is not supported.

Regards,
Mithun Rathinam
Exchange Beta Engineer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 806036e6-b150-fb4a-aace-e433ddb0c6c1
* Version Independent ID: 89078856-c629-97a2-b505-9364a844a160
* Content: [Set-HostedConnectionFilterPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-hostedconnectionfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-HostedConnectionFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-HostedConnectionFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MithunRathinam, done.

Thanks for the feedback.

Closing
