### ISSUE TITLE
Does SCC PowerShell support adding Mail-enabled security groups?

### ISSUE THREAD

**Issue by tokitamo-ms** [MicrosoftDocs/office-docs-powershell#10490]
I find the description of the -Member parameter inconsistent.

- Mail-enabled security groups (don't use in Security & Compliance PowerShell)
- You can't add security groups or mail-enabled security groups as members of the role group in the Microsoft Purview portal. You should add them via PowerShell with this parameter.

Does this mean that only Purview role groups can add Mail-enabled security groups in SCC PowerShell?
If so, I think a statement that Defender role groups don't support adding Mail-enabled security groups is necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80fd6b52-f2cb-57b4-e7b4-3a82e6dab656
* Version Independent ID: 38341c18-e6c8-50ac-42e2-ed6c51b86b66
* Content: [Add-RoleGroupMember (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/Add-RoleGroupMember?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Add-RoleGroupMember.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Add-RoleGroupMember.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@tokitamo-ms, that second statement was added in [this pull request](https://github.com/MicrosoftDocs/office-docs-powershell/pull/10242) from December:

> Confirmed with the engineering team who manages the UI in the Microsoft Purview Portal, the current legacy picker to select the members has no ability to select Security Groups and will be retired in the following months. The new picker is able to select Security Group and will replace the old one. Hence, we need to update this article for now to inform customer and guide them to use the cmdlet.

I confirmed the statement about not being able to use the Purview compliance portal or the Defender portal to add mail-enabled security groups.

But, that statement seemed weird and out of place, so I removed it.

I also removed the "(don't use in Security & Compliance PowerShell" text after the mail-enabled security groups bullet. I confirmed you can definitely add a mail-enabled security group to a role group using Security & Compliance PowerShell.

OK?

**Comment by yogkumgit** [comment]
@tokitamo-ms Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
