### ISSUE TITLE
[teams] CsUserCallingSettings - GroupNotification types description

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10498]
Could you please add to this article some description of the expected behaviour for `-GroupNotificationOverride` parameter values (Ring, Mute and Banner) for:

* Native Teams Phones (such as Poly CCX series)
* Teams app for PC
* Teams app for smartphone

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31cb9cc1-fa53-871b-aead-ff43bf5eacee
* Version Independent ID: 5e56da56-6255-3751-d1ca-6dc49c2c1376
* Content: [Set-CsUserCallingSettings (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsUserCallingSettings.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
I added more explanation in PR 10511, but I don't necessarily feel it is the role of this PS doc page to have details on how each Teams client react on the setting.

**Comment by get-itips** [comment]
Thanks @JensTrier
