### ISSUE TITLE
Need to add RTMP-in controls

### ISSUE THREAD

**Issue by StainlessSteele** [MicrosoftDocs/office-docs-powershell#10491]
The teams PowerShell module now supports the parameter: AllowedStreamingMediaInput 
it has two possible values, blank or RTMP.
if set to RTMP, users assigned that corresponding policy can use RTMP in services when they schedule meetings. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
Thanks for your feedback!
