### ISSUE TITLE
Do the windows prequisites need an update re: min .Net version for 3.0+?

### ISSUE THREAD

**Issue by drdenson** [MicrosoftDocs/office-docs-powershell#10500]
Hi Team - in working with a customer to troubleshoot some .Net errors when using the 3.0/3.1 version of the module, we discovered that having the 4.7.1 .net version as described in this article did NOT correct the 'assembly not found' errors, but updating .net to 4.8.0 did correct the issue.

getting error after installing or updating module to Ver3 or Ver3.1, works fine with version 2.0.5
Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Is it possible that the pre-requisites have changed, and as such, the documentation should be updated accordingly?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module and V3 module](https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#windows)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
Issue resolve in email thread that resulted in PR #10569.

Closing
