### ISSUE TITLE
Filter on Identity with -like not working

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10527]
Every combination of using the Filter parameter on the Identity attribute with a like command results in an error (using 4.9.3 of the MicrosoftTeams PowerShell module)

Whether I use
Get-CsOnlineUser -Filter {Identity -like "00*"} | Select Identity
or
Get-CsOnlineUser -Filter {Identity -like '00*'} | Select Identity
or
Get-CsOnlineUser -Filter "Identity -like '00*'" | Select Identity
or
Get-CsOnlineUser -Filter 'Identity -like "00*"' | Select Identity

The error returned is like
Get-CsOnlineUser : AADGraph Request failed with BadRequest. AAD Code  Message .
Parameter name: https://graph.windows.net/<tenantId>/users?api-version=1.61-internal&$select=
assignedPlans,cloudMSRtcIsSipEnabled,preferredLanguage,shadowProxyAddresses,displayName,jobTitle,givenName,surname,acco
untEnabled,streetAddress,cloudSipLine,cloudSipProxyAddress,sipProxyAddress,state,userPrincipalName,proxyAddresses,objec
tId,usageLocation,dirSyncEnabled,UserType,country,department,provisionedPlans,cloudMSRtcOwnerUrn,tenantId,deletionTimes
tamp,cloudMSRtcServiceAttributes,cloudMSRtcPolicyAssignments,mailNickname,companyName,postalCode,city&$top=100&$filter=
(startswith(ObjectId, %2700%27))
At line:1 char:1
+ Get-CsOnlineUser -Filter {Identity -like "00*"} | Select Identity
+ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
    + CategoryInfo          : InvalidOperation: ({ PageSize = , ...eleteduser =  }:<>f__AnonymousType92`12) [Get-CsOnl
   ineUser], Exception
    + FullyQualifiedErrorId : BadArgument,Microsoft.Teams.ConfigApi.Cmdlets.GetCsOnlineUser

and if I use

Get-CsOnlineUser -Filter Identity -like "00*" | Select Identity
or
Get-CsOnlineUser -Filter Identity -like '00*' | Select Identity

I get an error like

Get-CsOnlineUser : A parameter cannot be found that matches parameter name 'like'.
At line:1 char:35
+ Get-CsOnlineUser -Filter Identity -like "00*" | Select Identity
+                                   ~ ~ ~
    + CategoryInfo          : InvalidArgument: (:) [Get-CsOnlineUser], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-CsOnlineUser

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @isrumnon
* Microsoft Alias: **isrumnon**

**Comment by isrumnon** [comment]
Hi @sarollins is this the case only when you use the "-identity" property or have you been able to replicate this elsewhere?

In the meantime, you can check out TPM 5.0.0 that is releasing tomorrow (2nd March) which addresses issues with the wildcard "*" operator along with a few other updates. The changes have been documented here:
https://learn.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps

**Comment by sarollins** [comment]
Hello Isaiah

We have some clients who have 200K users and PS runs out of memory when attempting to get all the users at once, so our solution would be to use the Identity attribute to get all the users in smaller chunks.  All other attributes run into issues due to special characters or not having a fairly even distribution

I will attempt this tomorrow when 5.0.0 comes out

**Comment by sarollins** [comment]
Hello Isaiah

Just downloaded version 5.0.0 and do not get the long error message for queries like

Get-CsOnlineUser -Filter {Identity -like "00*"} | Select Identity

But now PS is returning the error

Correlation id for this request : 1b5f07a9-afa9-4054-99d7-6f2fce9b58ce
Get-CsOnlineUser : Filter couldn't be parsed.
At line:1 char:1
+ Get-CsOnlineUser -Filter {Identity -like "00*"} | Select Identity
+ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
    + CategoryInfo          : InvalidOperation: ({ PageSize = , ...eleteduser =  }:<>f__AnonymousType92`12) [Get-CsOnl
   ineUser], Exception
    + FullyQualifiedErrorId : BadArgument,Microsoft.Teams.ConfigApi.Cmdlets.GetCsOnlineUser

**Comment by isrumnon** [comment]
@sarollins so we don't support the "-like" operator on Identity since we figured it's a GUID. Can you help me understand why you would need this and alternatively if filtering on things like alias or company can be used instead?

**Comment by sarollins** [comment]
Hello Isaiah



Our product (written in C++, with some C#) helps manage UC systems, (Microsoft Teams being one of them) and we have clients who have 200K+ users.



When these clients attempt to download the user data to our system using PowerShell/cmdlets, they either run into a PS out of memory or a timeout issue, so we need to break down these into smaller chunks.  We used to accomplish this with the -LdapFilter feature (Get-CsOnlineUser -LdapFilter "(objectGUID=\00*)" | Select <selected attributes>), but last year Microsoft deprecated this feature.



The GUID attribute works great because it provides a fairly even distribution of users and it avoids issues of trying to use a name field, and having to worry about non-english characters (Á, É, Ó, etc.)



Because Microsoft does not support -Top/-Skip options for the Get-CsOnlineUser, like they do for some other cmdlets, this is why we are needing to use -Filter with the -like feature

**Comment by isrumnon** [comment]
@sarollins so the timeout or out of memory issues should not be happening anymore with TPM 5.0.0. Would this help?

**Comment by sarollins** [comment]
If 5.0.0 alleviates the out of memory/timeout issues, then yes, that should work, although I would suggest to the development team the benefits of implementing top/skip parameters, like in Graph API with the skiptoken

I will see if one of our clients can test this out and get back to you

**Comment by sarollins** [comment]
Good morning Isaiah

We finally found a customer to try using 5.0.0 and from a new PS session they issue the command

Get-CsOnlineDialInConferencingUser | Select AllowTollFreeDialIn, ServiceNumber, SipAddress, TollFreeServiceNumber

And after 5,049 seconds they get the following error

AADSTS500133: Assertion is not within its valid time range. Ensure that the access token is not expired before using it for user assertion, or request a new token. Current time: 2023-03-12T09:08:57.3937926Z, expiry time of assertion 2023-03-12T09:08:57.0000000Z.

   Trace ID: b1147f2a-c209-4fa9-a129-4f0983297500

   Correlation ID: 62665b31-ccd7-46c6-8104-76113383b981

   Timestamp: 2023-03-12 09:08:57Z

So, I think there are still issues that need to be addressed

**Comment by yogkumgit** [comment]
@isrumnon

**Comment by isrumnon** [comment]
Hi @sarollins I forgot to mention that the timeout issues are only resolved for Get-CsOnlineUser. I hope you and your customers are not facing issues anymore with this cmdlet.

As for Get-CsOnlineDialInConferencingUser, I'm afraid I am not the right point of contact for this

**Comment by yogkumgit** [comment]
@tiburd Please help us in forwarding to the right  point of contact. Thanks

**Comment by tiburd** [comment]
Sent email seeking the correct contact....

**Comment by dstrome** [comment]
hi all,

We aren't able to provide product support through GitHub Issues. If you need further help resolving the errors you're encountering, please contact Microsoft Support.
