### ISSUE TITLE
Get-CsOnlineApplicationInstance : access denied when doing Certificate based login

### ISSUE THREAD

**Issue by Fimlore** [MicrosoftDocs/office-docs-powershell#10539]
when using a Certificate with Connect-MicrosoftTeams, the csOnlineApplicationInstance cmdlets all return Access Denied

```
Connect-MicrosoftTeams -CertificateThumbprint $CertificateThumbprint -ApplicationId $ApplicationID -TenantId $TenantID
```

```
Get-CsOnlineApplicationInstance
new-CsOnlineApplicationInstance 
```

all result in Access Denied, even though the Service Principal used has the  Teams Administrator role.

![TeamsCertificateIssue](https://user-images.githubusercontent.com/20944149/222173265-926bc67b-d482-47b2-a35c-aca95156bcaa.png)

this is using Module 4.9.3, on PoSH 7.3.3, both inside and outside of VSCode

**Comment by pbafna03** [comment]
Currently [Get|Set|New|Sync]-CsOnlineApplicationInstance cmdlets are not supported for Application based auth, ref: https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication#cmdlets-supported

**Comment by yogkumgit** [comment]
@Fimlore Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Ankhimes** [comment]
New-CsApplicationAccessPolicy -Identity Meeting-policy-dev -AppIds "72f988bf-86f1-41af-91ab-2d7cd011db47" -Description "Online meeting policy - contoso town"
Correlation id for this request : 085634f6-b424-4017-b549-79f2beb7f528
**New-CsApplicationAccessPolicy : Access Denied.
At line:1 char:1**

**Comment by pbafna03** [comment]
@Ankhimes - please check if the requisite AAD Admin roles are assigned to the app. Ref - [link](https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication#setup-application-based-authentication:~:text=Assign%20Azure%20AD%20roles%20to%20the%20application.%20Refer%20to%20this%20Assign%20a%20role%20procedure%2C%20but%20search%20for%20the%20application%20instead%20of%20a%20user.).
