### ISSUE TITLE
how to handle backslash and other special character in mailboxfolderidparamer

### ISSUE THREAD

**Issue by bpw320** [MicrosoftDocs/office-docs-powershell#10536]
```powershell
add-mailboxfolderpermisson  "user:\cases\github\office " -user jdoe -accessrights reviewer
```

there is a folder named cases 

a subfolder name: github\office

the above PowerShell command won't work since it cannot find the folder

Question: how to handle backslash in subfolder name, so the above PowerShell can process "gitHub\office" as a subfolder name?

Thanks

**Comment by yogkumgit** [comment]
@bpw320 Please indicate which document you are referring to. Thanks

**Comment by chrisda** [comment]
@bpw320, I don't think it's a problem with backslashes.

I initially thought there might be a thing where all those weird mailbox identifiers except email address worked only in on-premises Exchange server (which I confirmed they did). But, the weird mailbox identifiers also worked fine in Exchange Online when I tested with `Identity "<User>:\Inbox"` (quotes required only if the \<User\> value has spaces).

I even made your same folder path in a mailbox and assigned permissions to it. No issues:

```powershell
PS C:\Users\bob> Add-MailboxFolderPermission -Identity bob:\Cases\GitHub\Office -User eb7458d5-085a-455d-9e11-dcc3aa159cad -AccessRights Reviewer

FolderName           User                 AccessRights                                     SharingPermissionFlags
----------           ----                 ------------                                     ----------------------
Office               Jane Done        {Reviewer}
```

I even tried it in remote PowerShell mode and REST API mode.

I happen to be running v3.2.0-Preivew1 of the module, but I doubt that matters. Are you running v3.1.0?

**Comment by bpw320** [comment]
Thank you for this

but for your example, folder name is office, can you test if works for  folder named: "GitHub\Office"  under Cases folder? Thanks

**Comment by chrisda** [comment]
@bpw320, sorry, I get it now.

I created a folder under the Cases folder named "a\b"

When I run the command `Get-MailboxFolder bob:\Cases -GetChildren` I get really weird results:

```powershell
PS C:\Users\bob> Get-MailboxFolder bob:\Cases -GetChildren | fl

Name                      : a\b
Identity                  : bob:?Cases?a\b
ParentFolder              : bob:\Cases
FolderStoreObjectId       : LgAAAAAJCg7D9RH7RoGJ6ej7bk8sAQAennTJ5bNGSo2zZHZQQ344AAWXiKQ/AAAB
FolderSize                : 0
HasSubfolders             : False
FolderClass               : IPF.Note
FolderPath                : {Cases, a\b}
AssociatedDumpsterFolders :
DefaultFolderType         : None
ExtendedFolderFlags       :
MailboxOwnerId            : bob
IsValid                   : True
ObjectState               : Unchanged

Name                      : GitHub
Identity                  : bob:\Cases\GitHub
ParentFolder              : bob:\Cases
FolderStoreObjectId       : LgAAAAAJCg7D9RH7RoGJ6ej7bk8sAQAennTJ5bNGSo2zZHZQQ344AAWXiKQ8AAAB
FolderSize                : 0
HasSubfolders             : True
FolderClass               : IPF.Note
FolderPath                : {Cases, GitHub}
AssociatedDumpsterFolders :
DefaultFolderType         : None
ExtendedFolderFlags       :
MailboxOwnerId            : bob
IsValid                   : True
ObjectState               : Unchanged
```

See the Identity value `bob:?Cases?a\b`? Those question marks are really the "U+FFFE noncharacter" character.

I tried `\\` and `<backtick>\` to escape the blackslash character, and it didn't work. I even tried using the FolderStoreObjectId value, and that didn't work either.

Other than opening a support ticked and asking, I think the conclusion is: don't use the backslash character in the folder name.

**Comment by chrisda** [comment]
And, I also tried:

```powershell
-Identity "bob:\Cases\a0x2Fb"

-Identity "bob:\Cases\a&#92;b"

-Identity "bob:\Cases\a0x2Fb"

-Identity "bob:\Cases\a&bsol;b"
```

And none of those worked, either.

**Comment by bpw320** [comment]
Thank you Chris.  In my work environment, a user has almost 1600
folder/subfolders, and a lot of names have backslash.

**Comment by chrisda** [comment]
@bpw320, it looks like this has been a problem since time immemorial (back to Exchange 2007) where Outlook allows creating folder names with backslashes, yet back-end cmdlets don't work with those folders. It's also a problem in public folder names.

I found [this similar issue](https://community.spiceworks.com/topic/2215674-how-to-rename-folders-and-subfolders-with-in-shared-mailbox-using-powershell) where the trouble was with "/" in the folder name, and the (rather bizarre solution) was to change them to "\".

But, perhaps you can use the approach in the answer to script-o-matically change the "\" to "-" or some other benign character?

**Comment by bpw320** [comment]
Thanks Chris. I ended up creating a custom console app using exchange web
services. to enumerate folder/subfolders recursively and apply permissions
