### ISSUE TITLE
MicrosoftTeams module: Set-CsTeamsMeetingPolicy is not working with -ErrorAction, -InformationAction, -WarningAction, etc.

### ISSUE THREAD

**Issue by romanleshchenko** [MicrosoftDocs/office-docs-powershell#10532]
If run `Set-CsTeamsMeetingPolicy` without `-ErrorAction` or `-InformationAction` parameter it works fine, but If I specify `-ErrorAction` or `-InformationAction` I get an error

_`Set-CsTeamsMeetingPolicy: You are not authorized to perform this action Please refer to documentation`_

![image](https://user-images.githubusercontent.com/83818285/221937968-7c7f0c28-1cba-4b4f-8411-d68e92f28f27.png)

**Detailed error:**
![teams](https://user-images.githubusercontent.com/83818285/221936536-4089957b-10a3-43ab-bc1c-ca86347dfac1.png)

Module: MicrosoftTeams
Version: 4.9.3
Cmdlet: Set-CsTeamsMeetingPolicy

**Comment by get-itips** [comment]
Hello, I'm working on this to understand if we need to update the documentation. Thank you

**Comment by sdwheeler** [comment]
@get-itips This is a product bug not a documentation issue. This needs to be reported to the Product team.

**Comment by get-itips** [comment]
> @get-itips This is a product bug not a documentation issue. This needs to be reported to the Product team.

Thanks @sdwheeler we'll try to pass this feedback, closing this issue for now.
