### ISSUE TITLE
Example Credit Card Number in Help File

### ISSUE THREAD

**Issue by mike-m2cloud** [MicrosoftDocs/office-docs-powershell#10547]
The help file as part of this module (Microsoft.Exchange.RemoteConnections-Help.xml) contains an example credit card number and patient identifier number. This causes scanning tools for sensitive data to trigger (as required for PCI DSS compliance). The example data should be obfuscated in some way to avoid these sensitive data detections.

![image](https://user-images.githubusercontent.com/91850251/222241927-1227e55b-503e-4a48-8a72-25a195ca4e24.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d2b736d-b112-f0c7-c404-7889b1878845
* Version Independent ID: c0578017-3a0c-d493-da78-c31f74b8522a
* Content: [Test-DataClassification (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/test-dataclassification?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Test-DataClassification.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Test-DataClassification.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mike-m2cloud, I'll take suggestions as to how to obfuscate.

It also appears that you're talking about updating the version of the topic in the MAML XML file in code.

I can update the Test-DataClassification topic on the web, and then generate a new Microsoft.Exchange.RemoteConnections-Help.xml file. But then someone will need to check that MAML XML file into code.

**Comment by mike-m2cloud** [comment]
In terms of obfuscation, it can probably just be as simple as replacing one of the blocks of 4 digits to 'x's

**Comment by chrisda** [comment]
@mike-m2cloud, I changed the digits to x's. If you want me to generate the MAML XML files so you can check them back into code (and thus replace the 'bad' version of the topic with the updated version, just let me know via email.

**Comment by yogkumgit** [comment]
@mike-m2cloud Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
