### ISSUE TITLE
Please update below Transport rule parameter Limits .

### ISSUE THREAD

**Issue by MithunRathinam** [MicrosoftDocs/office-docs-powershell#10557]
Hi Team,

Please update below Transport rule parameter Limits .

1) -RejectMessageReasonText 
The actual Limit is 1024 characters .

2) -GenerateNotification
The actual Limit is 5120 Characters.

Regards,
Mithun Rathinam.
Exchange Beta Engineer

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f48ae8ec-b719-c4db-c259-02e4f9e779b5
* Version Independent ID: 96f609a7-578e-5568-adb3-61f483997870
* Content: [Set-TransportRule (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-transportrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-TransportRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-TransportRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MithunRathinam, interesting that no limit was mentioned in either of those parameters in New-TransportRule or Set-TransportRule. But, I added the limits to both parameters in both cmdlet topics as you suggested.

Thanks for the feedback.

Closing

**Comment by MithunRathinam** [comment]
Thanks Chris
