### ISSUE TITLE
AllowTasksFromTranscript not available in the Doc although visible in our Get-CsTeamsMeetingPolicy outputs

### ISSUE THREAD

**Issue by LaureVDH** [MicrosoftDocs/office-docs-powershell#10567]
We have no information about AllowTasksFromTranscript  in the Doc in Get-CsTeamsMeetingPolicy page despite I can see that "Enabled" in the outputs of my Get cmdlet. Is it possible to add more info ? 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @LaureVDH I'm working on this

**Comment by tiburd** [comment]
Sent email to @LaureVDH
