### ISSUE TITLE
I get compile error in sample code

### ISSUE THREAD

**Issue by VincentXu2021** [MicrosoftDocs/office-docs-powershell#10564]
PowerShell ps = PowerShell.Create(runspace);
Above line reported compile error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75e7a156-cd45-796e-b916-912fd0377668
* Version Independent ID: d6afee4b-3324-705c-ddb9-a9f232146cb9
* Content: [Use C# to connect to Exchange Online PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/connect-to-exo-powershell-c-sharp?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exo-powershell-c-sharp.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/connect-to-exo-powershell-c-sharp.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@VincentXu2021, make sure you're running the latest public version of the ExchangeOnlineManagement module (currently v3.1.0) and that you can connect successfully using the normal, manual method without using C#.

You might also verify that your PowerShellGet and PackageManagement modules are the latest public versions.

You can also verify that you don't have multiple versions of any of these modules by running `Get-InstalledModule -AllVersions` and uninstalling any Preview versions that you might find.

After that, you should open a support ticket. Report back here with any findings that can help improve the documentation.

**Comment by yogkumgit** [comment]
@VincentXu2021 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
