### ISSUE TITLE
Consider changing or removing section on unattended scripts

### ISSUE THREAD

**Issue by BHoggs** [MicrosoftDocs/office-docs-powershell#10562]
In the section: `Connect to Security & Compliance PowerShell without a login prompt (unattended scripts)`, a link is provided to the documentation for using App-Only authentication. This is a good option and should stay.

However the example that follows is simply using plain-text authentication with a user account. This is not only bad security practice, but it seems irrelevant to the heading.

Either:
* The disclaimer should be changed to RED
* Provide a better example using a more secure method
* Just remove the example altogether and leave only the link to the correct article.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps#connect-to-security--compliance-powershell-without-a-login-prompt-unattended-scripts)
* Content Source: [exchange/docs-conceptual/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/connect-to-scc-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@BHoggs, [Connect to Exchange Online PowerShell](https://learn.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell) had the exact same issue.

I chose the option from your third bullet point: Just remove the example altogether and leave only the link to the correct article.

Thanks for the feedback.

Closing.

**Comment by BHoggs** [comment]
That was quick, awesome work!
