### ISSUE TITLE
Get-CsOnlineUser -Filter performance

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10566]
just wanted to pass "Thank you" message to the engineering team.
I don't know what you guys 've done recently, but the performance of `Get-CsOnlineUser` with `-Filter` parameter has improved tremendously this week compared to what it was before.

Thank you

And my apology for using github issue inappropriately

**Comment by tiburd** [comment]
@shivtorov 
Thank you very much for taking the time to say "thank you"! I've passed it on to the product team - they appreciate your feedback.
Best wishes!
