### ISSUE TITLE
Get-EXOMailbox like filter fails when using single quotation marks.

### ISSUE THREAD

**Issue by kieranwalsh** [MicrosoftDocs/office-docs-powershell#10572]
I'm using  ExchangeOnlineManagement version 3.1.0 and wish to list all mailboxes without a CustomAttribute2 attribute. Here is a sample:

    Get-EXOMailbox -ResultSize 10 -Properties  CustomAttribute2 -Filter {CustomAttribute2 -like ''} | Select-Object Name, Customattribute2

Unfortunately, it fails with this error:

```
Get-EXOMailbox : Error while querying REST service. HttpStatusCode=400 ErrorMessage={"error":{"code":"BadRequest","message":"Invalid filter clause","innererror":{"message":"Invalid filter 
clause","type":"Microsoft.Exchange.Admin.OData.Core.ODataServiceException"}}}}
At line:1 char:1
+ Get-EXOMailbox -ResultSize 10 -Properties  CustomAttribute2 -Filter { ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ProtocolError: (:) [Get-EXOMailbox], RestClientException
    + FullyQualifiedErrorId : An error occurred while processing this request.,Microsoft.Exchange.Management.RestApiClient.GetExoMailbox
```
 
If you change the line to use double quotation marks like this:

    Get-EXOMailbox -ResultSize 10 -Properties  CustomAttribute2 -Filter {CustomAttribute2 -like ""} | Select-Object Name, Customattribute2

The line works fine.  This is against `about_Quoting_Rules`, and it's a massive pain when you have automatic code refactoring in VSCode, as any time a non-expandable string is spotted using double quotes, those are automatically converted to single quotes.

**Comment by kieranwalsh** [comment]
I have found a workaround:

    Get-EXOMailbox -ResultSize 10 -Properties  CustomAttribute2 -Filter {CustomAttribute2  -eq $null} | Select-Object Name, Customattribute2

But I think the double quotes issue should be fixed all the same.

**Comment by chrisda** [comment]
@kieranwalsh, I highly recommend opening a support ticket about this. The issue will (eventually) get in front of the people who can fix it.

**Comment by yogkumgit** [comment]
@kieranwalsh Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
