### ISSUE TITLE
Why does this cmdlet dont have any implementation information

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/office-docs-powershell#1058]
This commandlet doesn't look like exist in SPO module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f4f56f0-6c56-b65b-080a-af1b941cebb2
* Version Independent ID: ffbbac19-52a8-0ba9-5137-9c831697bc37
* Content: [Get-SPO365LinkSettings (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spo365linksettings?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPO365LinkSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPO365LinkSettings.md)
* Service: **sharepoint-powershell**
* Product: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen for your review. thanks

**Comment by tseward** [comment]
@Techwriter40 Updated in #1074

**Comment by VesaJuvonen** [comment]
Document removed from the SPO side.
