### ISSUE TITLE
Why does this cmdlet dont have any implementation information

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/office-docs-powershell#1059]
No Description or example... doesn't exist in SPO module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbaba231-7df2-8f4e-a761-0a9b395c5665
* Version Independent ID: 5a7bc4be-bf47-e722-9be6-70b58dd0da5c
* Content: [Set-SPO365LinkSettings (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spo365linksettings?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPO365LinkSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPO365LinkSettings.md)
* Service: **sharepoint-powershell**
* Product: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen for your review. thanks

**Comment by tseward** [comment]
@Techwriter40 Updated in #1068.

**Comment by VesaJuvonen** [comment]
This is SP server-side cmdlet, so removed from the SPO side.
