### ISSUE TITLE
The -purge parameter does not exist in v.3.0.0 of ExchangeOnlineManagement

### ISSUE THREAD

**Issue by KeysAU** [MicrosoftDocs/office-docs-powershell#10594]
-Purge parameter does not exist in v.3.0.0 on ExchangeOnlineManagement

![image](https://user-images.githubusercontent.com/38932932/223954586-642e52f4-52e9-401e-b466-bf192ddb72ad.png)

How are we supposed to purge emails?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fad8adee-7f9d-757b-2069-95ecab232747
* Version Independent ID: c71194df-8f65-15aa-3ed2-b370b8c3f629
* Content: [New-ComplianceSearchAction (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-compliancesearchaction?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@KeysAU, the following call-out is in the Purge parameter description in [Get-ComplianceSearchAction](https://learn.microsoft.com/powershell/module/exchange/get-compliancesearchaction), but not in New-ComplianceSearchAction, even though it applies to both:

> **Note**: In Security & Compliance PowerShell, this parameter is available only in the Search and Purge role. By default, this role is assigned only to the Organization Management role group.

I'll add that note to the Purge and PurgeType parameter descriptions in New-ComplianceSearchAction.

Version of the module shouldn't matter, although the current version is v3.1.0. Another possibility is the whole [remote PowerShell vs. REST API](https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#updates-for-the-exo-v3-module) connections.

But, the most likely issue is the account that you're connecting with doesn't have the Search and Purge role assigned.

**Comment by chrisda** [comment]
Correction: The Search and Purge role is now assigned to the Organization Management AND Data Investigator role groups.

**Comment by yogkumgit** [comment]
@KeysAU Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
