### ISSUE TITLE
Get-CsOnlineVoiceUser is deprecated

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10603]
This cmdlet is deprecated (screenshot below)

please add a note to the SYNOPSIS of this article as well as update the list of deprecated cmdlets in [that](https://learn.microsoft.com/microsoftteams/teams-powershell-supported-versions) article.

![image](https://user-images.githubusercontent.com/31003608/224465559-172ef4a7-4f9d-44ec-9745-42c6f30fe996.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cd68eb1-f954-e205-39a8-8f2963d339ef
* Version Independent ID: 8ca09c2e-d142-5a71-d29b-df31b6ea210a
* Content: [Get-CsOnlineVoiceUser (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/get-csonlinevoiceuser?view=skype-ps&source=docs)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineVoiceUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineVoiceUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by yogkumgit** [comment]
@shivtorov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
