### ISSUE TITLE
Connect-Ippssession using Managed Identity

### ISSUE THREAD

**Issue by jachaohk** [MicrosoftDocs/office-docs-powershell#10605]
Hello,

We use the Security and Compliance PowerShell module (part of EXO) in Azure Automation to automate retention policies.  We are currently connecting using the Connect-IPPSession using CBA authentication however we would like to start using managed identity if possible.  The connect-exchangeonline cmdlet currently can use the managed identity option.  Any idea when connect-ippssession will be able to use manage identity to connect?  

Azure Automation will sunset the use of Run-As accounts in September and this is the only cmdlet we have left that uses the run-as account cert.  Rather than create a new enterprise application in AAD to support CBA, we would like to just use the managed identity.

Thanks,

**Comment by chrisda** [comment]
@jachaohk, you can try asking at exocmdletpreview[at]service[dot]microsoft[dot]com.

**Comment by yogkumgit** [comment]
@jachaohk Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
