### ISSUE TITLE
Update Microsoft Teams Powershell documentation

### ISSUE THREAD

**Issue by SebastianPiendl** [MicrosoftDocs/office-docs-powershell#10604]
Since the Skype for Business Powershell module functionality has been moved to the Microsoft Teams Powershell module, please update the documentation for this command.

**Comment by yogkumgit** [comment]
@SebastianPiendl Please indicate which document you are referring to and which command you are mentioning here. Thanks

**Comment by get-itips** [comment]
Hello @SebastianPiendl 
Recently I edited the article to add a reference to the parameter from this cmdlet that works for teams, please see under "-EnablePrivacyMode" in the article.

Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @SebastianPiendl Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
