### ISSUE TITLE
Remove prerelease feature warning

### ISSUE THREAD

**Issue by JonLmsft** [MicrosoftDocs/office-docs-powershell#10618]
Hi - This feature has been released. Please remove the following prerelease warning and roadmap links from the -SendFromAliasEnabled parameter:

Note: This feature is in Preview and has not yet been officially released. Do not enable it if you are not willing to lose certain functionality or have a degraded experience. An official announcement will be released via the EHLO blog and Message Center in due time.

For more information about the availability of the Outlook for the web changes, see the [Microsoft 365 roadmap item](https://www.microsoft.com/microsoft-365/roadmap?filters=Exchange&searchterms=59437). For Outlook for Windows, see this [Microsoft 365 roadmap item](https://www.microsoft.com/microsoft-365/roadmap?filters=Outlook&searchterms=64123).

Page: https://learn.microsoft.com/powershell/module/exchange/set-organizationconfig#-sendfromaliasenabled

Thanks!

**Comment by chrisda** [comment]
@JonLmsft, done.

In the future, you too can make changes like this directly without opening a GitHub issue first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
