### ISSUE TITLE
Timeout received trying to get conferencing data

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10615]
With a new PowerShell session (connecting using User Tokens), using 5.0.0 of the Teams module, when this command is issued

Get-CsOnlineDialInConferencingUser | Select AllowTollFreeDialIn, ServiceNumber, SipAddress, TollFreeServiceNumber

We get the following error after 5,049 seconds

AADSTS500133: Assertion is not within its valid time range. Ensure that the access token is not expired before using it for user assertion, or request a new token. Current time: 2023-03-12T09:08:57.3937926Z, expiry time of assertion 2023-03-12T09:08:57.0000000Z.

   Trace ID: b1147f2a-c209-4fa9-a129-4f0983297500

   Correlation ID: 62665b31-ccd7-46c6-8104-76113383b981

   Timestamp: 2023-03-12 09:08:57Z

The only filtering mechanism has been deprecated and there is no provisions for -top/-skip, so we're looking for solutions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a78c07b-1a7e-b36c-e3c1-8e610638ff79
* Version Independent ID: 02174a2a-5102-5479-f72f-c9bf0691bf9b
* Content: [Get-CsOnlineDialInConferencingUser (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by sarollins** [comment]
We are using an app.  When you say interactive session, I'm confused as to what you mean.  How does an application have an interactive session?

**Comment by get-itips** [comment]
@sarollins It does not, that's why it is either interactive (when a user does it) or an app.

I'll check if Get-CsOnlineDialInConferencingUser is supported for app-based auth.

**Comment by sarollins** [comment]
I'm sorry, I was confusing this with another issue with application tokens and realize you were talking about user tokens (I believe), which makes sense

FWIW, most of our clients "insist" on using some kind of MFA (tokens and hopefully when we get some bandwidth with Microsoft, certificates) to sign into O365 to access their Teams information

**Comment by get-itips** [comment]
@sarollins I checked and received feedback that it might be token expiration and that certificate-based auth should be more suitable for your scenario. Can you test with CBA?
If you are still facing issues, the best would be to open a support request from your tenant.
Thank you

**Comment by sarollins** [comment]
I have an open issue with Microsoft regarding issues we are having when we log into O365 using a certificate, so currently, no we cannot test certificates right now

I know that 5.0.0 fixed the timeout issue for the Get-CsOnlineUser cmdlet.  Do you think this same fix could be applied to this cmdlet?

**Comment by get-itips** [comment]
@sarollins I don't know but I already shared this feedback.
