### ISSUE TITLE
set-CsUser : This cmdlet has been deprecated.

### ISSUE THREAD

**Issue by passports** [MicrosoftDocs/office-docs-powershell#10625]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76cebc8c-7403-8981-a993-ed1079eb513c
* Version Independent ID: 015533c1-6a15-3dc1-083d-3370bdc3915d
* Content: [Set-CsUser (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello, current article says

> Note: Using this cmdlet for Microsoft Teams users has been deprecated. Use the new [Set-CsPhoneNumberAssignment](https://learn.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment) and [Remove-CsPhoneNumberAssignment](https://learn.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment) cmdlets instead.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @passports Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
