### ISSUE TITLE
Lacking email notification information

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/office-docs-powershell#10649]
When assigning numbers via Teams admin portal there is a user notification email option enabled by default.  The information on this page is lacking any reference to that at all.  At minimum, if the user email notification is not available via this command it should be mentioned that no email will go out with this command.  Currently I do not have any way to know if using this command will generate an email or not, I should not have to be left guessing by official documentation.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
Thanks for your feedback, I'm working on this

**Comment by ssmiller60** [comment]
Did the document get updated with this information?

**Comment by get-itips** [comment]
I asked the article's author and the decision was to leave as-is. Documentation informs what the command does, not the other way around.
Thank you for your feedback!
