### ISSUE TITLE
Set-SPOSiteOffice365Group throws access denied error 

### ISSUE THREAD

**Issue by prattay56** [MicrosoftDocs/office-docs-powershell#10645]
Set-SPOSiteOffice365Group : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

This command fails to create M365 group if the SharePoint admin is not the current site owner/Admin.
Same happens with Get-SPOUser 

If I make the SPO admin as the site admin or owner, it works.
Is it by design?
 from SPO admin standpoint it is very difficult.
![image](https://user-images.githubusercontent.com/74849664/226857848-020b5240-8e65-4046-8573-d3bb1d07d59c.png)

**Comment by get-itips** [comment]
Hello @prattay56 
I could reproduce and I'll update the article.
Thanks for your feedback
