### ISSUE TITLE
SessionOption no longer valid

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/office-docs-powershell#10658]
Connect-MicrosoftTeams : A parameter cannot be found that matches parameter name 'SessionOption'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2abd383-7815-9404-41ba-72bbedb5208a
* Version Independent ID: 88342584-33e2-47c6-baf1-81644d5cc7a5
* Content: [New-CsOnlineSession (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/new-csonlinesession?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsOnlineSession.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @SharePointBlackBelt Vincent, how are you?

You opened the issue for the article `New-CsOnlineSession` but the error references `Connect-MicrosoftTeams`.
The article for `Connect-MicrosoftTeams` does not list `SessionOption` and `New-CsOnlineSession` is no longer included.

Can you please clarify?

Thank you

**Comment by SharePointBlackBelt** [comment]
"Skype for Business Online Connector [e.g., New-CsOnlineSession] is currently part of the latest Teams PowerShell module [e.g., Connect-MicrosoftTeams] and we are no longer required to connect Skype for Business Online". 
Ref: https://answers.microsoft.com/en-us/msteams/forum/all/new-module-no-longer-contains-the-new/d50d30f1-9068-4016-b09b-60b39918aeef
So if the S4BO commands are rolled into Teams PS module, then SessionOption should be an option, right?

**Comment by get-itips** [comment]
@SharePointBlackBelt 
 S4BO commands are rolled into Teams PS module however as the note says this one is deprecated.
SessionOption is not part of Connect-MicrosoftTeams.

**Comment by SharePointBlackBelt** [comment]
Ahh, OK, sorry. Closing
