### ISSUE TITLE
Example code and documentation references Operator flag which is ambigious.

### ISSUE THREAD

**Issue by Atreidae** [MicrosoftDocs/office-docs-powershell#10655]
When attempting to use the "Operator" parameter on New-CsAutoAttendant the cmdlet will throw an error advising the parameter is ambiguous as it can match multiple parameters

```
New-CsAutoAttendant : Parameter cannot be processed because the parameter name 'Operator' is ambiguous. Possible matches include: -OperatorEnableSharedVoicemailSystemPromptSuppression -OperatorEnableTranscription -OperatorId -OperatorType.
```

Examples 1,2 and 4 code need to be updated as well as the "operator" parameter documentation needs to be updated

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79cc312f-6b92-afa7-e50f-3ea302e58be2
* Version Independent ID: 9c3b6b02-ace5-9345-7fb6-24c09ed685e9
* Content: [New-CsAutoAttendant (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/new-csautoattendant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsAutoAttendant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @Atreidae James,
What version of the Teams PowerShell are you using?
I'm using latest stable (5.1.0) and I still have `-Operator` parameter
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Atreidae Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
