### ISSUE TITLE
Cmdlet's to create Teams Message cards and send messages to Teams

### ISSUE THREAD

**Issue by srikanthbyram** [MicrosoftDocs/office-docs-powershell#10661]
I do not find New-TeamsMessageCard and Send-TeamMessage cmdlets in your module when downloaded .Can you suggest the module to get those.

**Comment by get-itips** [comment]
Hello @srikanthbyram 
Those cmdlets do not exist, where did you read about those? Please clarify.
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @srikanthbyram Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
