### ISSUE TITLE
Help still refers to EXO V2 instead of EXO V3 (Probably general issue)

### ISSUE THREAD

**Issue by B-Art** [MicrosoftDocs/office-docs-powershell#10686]
help Get-Clutter -Examples

NAME
    Get-Clutter

SYNOPSIS
    This cmdlet is available only in the cloud-based service.

    Use the Get-Clutter cmdlet to view Clutter settings for mailboxes in your organization. Note : We recommend that yo
    u use the Exchange Online PowerShell **_V2_** module to connect to Exchange Online PowerShell. For instructions, see Conn
    ect to Exchange Online PowerShell (https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powers
    hell).

    For information about the parameter sets in the Syntax section below, see Exchange cmdlet syntax (https://docs.micr
    osoft.com/powershell/exchange/exchange-cmdlet-syntax).

    -------------------------- Example 1 --------------------------

    Get-Clutter -Identity "Constancia Pena"

    This example returns the Clutter settings for the user Constancia Pena.

**Comment by B-Art** [comment]
Maybe create a general link to aka.ms/... Where it refers to the latest EXO helpversion?

**Comment by chrisda** [comment]
@B-Art, you must be talking about `Get-Help` at the command line? The article on the web is fine:

<https://learn.microsoft.com/powershell/module/exchange/get-clutter>

Help at the command line will get updated the next time help from the web is converted and checked in to code, which is rather infrequent.

**Comment by yogkumgit** [comment]
@B-Art Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
