### ISSUE TITLE
[teams5.1] Get-CsOnlineApplicationInstance ignores ResultSize param

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10688]
Cmdlet Get-CsOnlineApplicationInstance ignores ResultSize param.
Ideally, the bug shall be fixed in the cmdlet.
If no plans to fix, then at least it should be documented in this article.

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS> Get-Module -Name MicrosoftTeams | select Name, Version

Name           Version
----           -------
MicrosoftTeams 5.1.0


PS> Get-CsOnlineApplicationInstance -ResultSize 5 | measure

Count    : 129

```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcb4263-0469-d3fe-d1f8-f3e8435c950a
* Version Independent ID: 144af0b9-1753-7988-70fd-60b50f832847
* Content: [Get-CsOnlineApplicationInstance (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/get-csonlineapplicationinstance?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineApplicationInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineApplicationInstance.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by get-itips** [comment]
Hello @shivtorov I'll try to report this.
