### ISSUE TITLE
Incorrect Syntax in Example 1 code

### ISSUE THREAD

**Issue by Atreidae** [MicrosoftDocs/office-docs-powershell#10687]
Hey team, Example 1 uses the .ObjectID parameter for OperatorObjectID on the first line

```$operatorObjectId = (Get-CsOnlineUser operator@contoso.com).ObjectId```

This is the name of the attribute in AzureAD. However, the Get-CsOnlineUser returns the Identity property. 

``` $operatorObjectId = (Get-CsOnlineUser operator@contoso.com).Identity ```
The above code would be a suitable replacement.

I'm running through the other examples at the moment as I've noticed some weirdness in the cmdlets relating to AutoAttendants recently, So expect a full more issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79cc312f-6b92-afa7-e50f-3ea302e58be2
* Version Independent ID: 9c3b6b02-ace5-9345-7fb6-24c09ed685e9
* Content: [New-CsAutoAttendant (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/new-csautoattendant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsAutoAttendant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by Atreidae** [comment]
Example 2 has the same issue

**Comment by get-itips** [comment]
Thanks for your feedback
