### ISSUE TITLE
Change Log - 

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1069]
It would be helpful if changes to the SPO Cmdlets were identified in a change log so that when a new version is available for download at https://www.microsoft.com/en-us/download/details.aspx?id=35588 we could easily determine what has changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5691fbb3-502b-9a33-97a0-92410a3ea924
* Version Independent ID: 6b24c981-ebf7-cdef-877d-0984be7734dc
* Content: [SharePoint Online Cmdlets](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/sharepoint-online-cmdlets?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/sharepoint-online-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/sharepoint-online-cmdlets.md)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for your feedback

I want to make sure your suggestion gets the proper attention. 

I know the product teams are always looking for user feedback and how to make the OneDrive / SharePoint better. They keep a close tab on User Voice [https://sharepoint.uservoice.com](https://sharepoint.uservoice.com) and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too. 
 
Thank you for your contribution to make the docs better! Much appreciated!

**Comment by DeanGross** [comment]
@AndreaBarr   I'm not suggesting a change to the application, I'm suggesting a change to the docs. I thought uservoice was for application suggestions and this github repo for the docs.

**Comment by AndreaBarr** [comment]
@DeanGross sorry for the misunderstanding. 

The closest thing we have right now is the commit history: https://github.com/MicrosoftDocs/office-docs-powershell/commits/master. I agree it would be ideal for a curated list . I agree a curated list would be ideal. I'll make sure that the doc team gets this feedback.
