### ISSUE TITLE
Search-UnifiedAuditLog Error : Write-ErrorMessage : One or more errors occurred.  

### ISSUE THREAD

**Issue by prattay56** [MicrosoftDocs/office-docs-powershell#10693]
Un able to run : Search-UnifiedAuditLog   exchange cmdlet.

_Write-ErrorMessage : One or more errors occurred.
At C:\Users\amand\AppData\Local\Temp\tmpEXO_0qswdiv2.54a\tmpEXO_0qswdiv2.54a.psm1:1120 char:13_

Able to run  Get-EXOMailbox 
I am the global admin 
![image](https://user-images.githubusercontent.com/74849664/229875756-fea61f49-1a1e-40e7-b283-e2954429e852.png)

AAD role group I am a part of 

![image](https://user-images.githubusercontent.com/74849664/229875896-1bf26711-a488-46d4-b218-09616a8880ae.png)

Surprisingly I can use GUI to gather unified audits.
![image](https://user-images.githubusercontent.com/74849664/229983836-dfbf01ee-18a3-4b12-92a2-389c553d6b8f.png)

![image](https://user-images.githubusercontent.com/74849664/229984083-c0de2f30-b3d6-477e-b629-e99519c42485.png)

**Comment by kathyblasco** [comment]
I have the same issue. This was after I ran windows PowerShell 'update-module'. I am also having issues with PnP.PowerShell. Both PnP.PowerShell and ExchangeOnlineManagement were updated.

Current PnP.PowerShell version is: 2.1.1
Current ExchangeOnlineManagement version is: 3.1.0

**Comment by prattay56** [comment]
I am not sure about pnp powershell. But yes Exchange module has some issues for sure.

**Comment by invictus-ir** [comment]
Same issue here, I think the Search-UnifiedAuditLog cmdlet is broken, have it in multiple tenants.

**Comment by joshlemon** [comment]
+1 
Getting the same issues with `Search-UnifiedAuditLog` and trying to search for logs that definitely existed yesterday.

**Comment by s-mahmood** [comment]
Facing exactly the same, hope there is a fix soon..

**Comment by damienfinck** [comment]
Same problem for multiple tenants. Hope to have a quick resolution...

**Comment by damienfinck** [comment]
Error on the Microsoft side: "Admins may see inaccurate Power BI usage metrics for certain audit events in the Microsoft 365 admin center".

Incident solved on my side.

**Comment by invictus-ir** [comment]
Yup it works again, thanks for the update!

**Comment by s-mahmood** [comment]
Working from my side as well.

**Comment by prattay56** [comment]
Looks like it is resolved.

**Comment by yogkumgit** [comment]
@damienfinck Thanks. Closing.
