### ISSUE TITLE
Get data in bulk

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10705]
We have many clients whose user base is in the 50K range with one client that has around 200K users.

Attempting to call this cmdlet for each and every user adds tremendous overhead and thus makes getting this data EXTREMELY slow

In the past, with some cmdlets, I was able to pipe in a list of identities to increase performance (in lieu of being able to troubleshoot errors), but when I attempt to do this with this cmdlet, I see this is not allowed?

We are looking for any kind of information on how to avoid doing this user by agonizing user.

Also, is there a specific user attribute that we can look at to determine if we should even bother calling this cmdlet if there is no data?  Because we call this cmdlet for each user, we frequently see error messages like

The specified user 'bd60dac2-4aa1-46a6-ba93-a858351b47fc' cannot be found or does not belong to the tenant.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25f6b51c-576b-a810-e03c-bc04c4531256
* Version Independent ID: f5ff8710-ff93-f967-ec62-8d23ffc2cc4b
* Content: [Get-CsOnlineVoicemailUserSettings (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/get-csonlinevoicemailusersettings?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineVoicemailUserSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineVoicemailUserSettings.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by get-itips** [comment]
Hello @sarollins 
I'll try to pass this feedback along.

**Comment by get-itips** [comment]
I was able to pass this feedback along.

**Comment by yogkumgit** [comment]
@sarollins  Thank you very much for your kind feedback. Your valuable feedback is forwarded to internal team.  Concerning team will evaluate and take the appropriate action, as per their schedule. Here we are limited to documentation fixes and improvements only. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
