### ISSUE TITLE
Error in Feature Schedule-send

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/office-docs-powershell#10700]
I think the command has currently a wrong configuration for the feature Schedule-send. Tested with Exchange Online PowerShell 3.2.0-Preview: https://www.powershellgallery.com/packages/ExchangeOnlineManagement/3.2.0-Preview2

If I try to set the configuration 

`Set-DefaultTenantMyAnalyticsFeatureConfig -Feature "Schedule-send" -IsEnabled $true -PrivacyMode "Opt-out"
`

then the parameter set is different. 

```
Cannot validate argument on parameter 'Feature'. The argument "Schedule-send" does not belong to the set
"dashboard,add-in,digest-email,meeting-effectiveness-survey,meeting-effectiveness-survey-sampling-rate,scheduled-send,all".
```

If I use scheduled-send the system cannot set the configuration due to an internal error. 

`The calling client sent a bad request to the service
`

I assume the parameter set should be Schedule-send.

Regards
Tobias

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9a7d768-8d99-0cfd-eb9e-9315336ec837
* Version Independent ID: 7b8eb5ce-e480-432a-b58c-1f084b751088
* Content: [Set-DefaultTenantMyAnalyticsFeatureConfig (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-defaulttenantmyanalyticsfeatureconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-DefaultTenantMyAnalyticsFeatureConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by TobiasAT** [comment]
Seems the issue is not the feature parameter, the PrivacyMode parameter is not working. In all configurations with an error. 

`Set-DefaultTenantMyAnalyticsFeatureConfig -PrivacyMode Opt-in   

Set-DefaultTenantMyAnalyticsFeatureConfig : The calling client sent a bad request to the service.`

**Comment by chrisda** [comment]
Checking

**Comment by TobiasAT** [comment]
Thanks @chrisda, will contact them via mail.

**Comment by DanielTavella** [comment]
Hi All,
We are facing the same issue with this cmdlet, have you find the chance to fix it somehow?
Thanks a lot!
Daniel

**Comment by TobiasAT** [comment]
Not yet. Sent an email to the Preview team, got a response the command owners should check this, but no more states. But it's a Preview, so probably less prio.

**Comment by TobiasAT** [comment]
@DanielTavella Preview3 of the Exchange PowerShell modules solves the issue. The cause was a missing Premium license, like the [Viva Insights license](https://www.microsoft.com/en-us/microsoft-viva/insights) or a full Viva Insights service plan.
