### ISSUE TITLE
Empty parameter description in Get-LabelPolicy

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/office-docs-powershell#10712]
Please add description for the ForceValidate parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dcaf4f84-e02f-a826-255e-79c476c4e7d9
* Version Independent ID: 6010e999-6e66-8209-2a5f-94238a297135
* Content: [Get-LabelPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-labelpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-LabelPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-LabelPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@asdcristi, empty parameter descriptions are a known issue when we're dealing with 1400+ Exchange-related cmdlets with 14,000+ parameters. Availability and functionality are two different things. See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for a detailed explanation about empty parameter descriptions.

Seeing as how you're a Microsoft employee, do you have inside information about what that parameter does? Is there public documentation elsewhere that's directing people to use that parameter? And, that ForceValidate parameter is available in the following cmdlets with a currently empty description:

Get-AutoSensitivityLabelPolicy
Get-AutoSensistivityLabelRule
Get-DlpCompliancePolicy
Get-DlpPolicy

If all you're looking for is a non-empty description, I can write a gem that says absolutely nothing:

> The ForceValidate switch forces validation of the sensitivity label. Valid values are:
>
> - $true: The sensitivity label is validated.
< - $false: The sensitivity label is not validated. This is the default value.

**Comment by yogkumgit** [comment]
@asdcristi Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
