### ISSUE TITLE
Empty parameter description in Get-DlpCompliancePolicy

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/office-docs-powershell#10713]
Please add description for the ForceValidate parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 478d6619-e9e9-9d38-4946-8596fc9231d1
* Version Independent ID: c7ea6bb8-11f8-0b88-e84b-9a57b5b14d1f
* Content: [Get-DlpCompliancePolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-dlpcompliancepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-DlpCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@asdcristi, exact same comments as <https://github.com/MicrosoftDocs/office-docs-powershell/issues/10712>.
