### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1071]
Please provide a change log/revision history so that we can easily learn about changes to the cmdlets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03f9b8-7a1f-81e7-e8c2-0286f0cd3ffb
* Version Independent ID: 931924d1-2be2-bc20-41a6-0b86fc65db07
* Content: [Microsoft Teams cmdlet reference](https://docs.microsoft.com/en-us/powershell/teams/intro?view=teams-ps)
* Content Source: [teams/docs-conceptual/intro.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/docs-conceptual/intro.md)
* Service: **teams-powershell**
* Product: **unspecified**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@DeanGross - you can follow every change in detail from the source GitHub repository located here: https://github.com/MicrosoftDocs/office-docs-powershell 

Here are some details about how to follow a repository: https://help.github.com/articles/watching-and-unwatching-repositories/

**Comment by DeanGross** [comment]
Thanks, I realize that I can do that in GitHub, but many of the other sets of documentation make it easier by having an actually What's new page, see https://docs.microsoft.com/en-us/cloud-app-security/release-notes and https://docs.microsoft.com/en-us/intune/whats-new and https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-whats-new or https://blogs.msdn.microsoft.com/powershell/2018/05/02/dsc-resource-kit-release-may-2018/ or

**Comment by kenwith** [comment]
@DeanGross - it is a great idea and something we don't have right now. I will bring this up to the product teams about adding this.
