### ISSUE TITLE
Duplicate syntax at top

### ISSUE THREAD

**Issue by TetraAsh** [MicrosoftDocs/office-docs-powershell#10718]
syntax blocks at top of page are duplicated

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03921866-8345-7e01-e873-3ec191191fbf
* Version Independent ID: cb374ec2-99c3-7186-66ed-c037a678e946
* Content: [New-UnifiedGroup (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@TetraAsh, syntax blocks are derived from how the cmdlet was coded. I typically don't mess with them, unless it's obvious that one or more of them are 100% identical to each other (which indicates non-customer available parameters are involved).

There's always one or more mutually exclusive parameters in each syntax block (or there should be).

**Comment by yogkumgit** [comment]
@TetraAsh Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by TetraAsh** [comment]
Ok, after a diffchecker against the blocks, I discovered their are subtle differences. 
Would it be worth adding context as to what the different blocks are for, there are 4 different syntax blocks for the same command.

**Comment by chrisda** [comment]
@TetraAsh, all Exchange-related cmdlets have the following link at the bottom of the SYNOPSIS (Introduction) section:

> For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).

That's as close as we're going to get to what you're asking for.

As an aside, I liked the way Exchange cmdlets rendered on the old TechNet site pre-2018: each parameter set contained ONLY the unique parameters in that set. The common parameter in all sets were in a big set at the bottom, although even that was not always perfect (parameters in some sets, but not all).
