### ISSUE TITLE
Navigation between PowerShell module documentation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1072]
Please update the left and/or right side navigation so that we can more easily get to the documentation for other PowerShell modules, i.e. it would be helpful if we could easily navigate between the various Office 365 modules (teams, exchange, sharepoint, etc). Currently there is not even any way to navigate back up to the master PowerShell page at https://docs.microsoft.com/en-us/powershel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03f9b8-7a1f-81e7-e8c2-0286f0cd3ffb
* Version Independent ID: 931924d1-2be2-bc20-41a6-0b86fc65db07
* Content: [Microsoft Teams cmdlet reference](https://docs.microsoft.com/en-us/powershell/teams/intro?view=teams-ps)
* Content Source: [teams/docs-conceptual/intro.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/docs-conceptual/intro.md)
* Service: **teams-powershell**
* Product: **unspecified**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
Related to: https://github.com/MicrosoftDocs/office-docs-powershell/issues/1073

**Comment by kenwith** [comment]
Perfect scenario for PowerShell Module Browser: https://docs.microsoft.com/en-us/powershell/module. Added a cross link to it.

**Comment by DeanGross** [comment]
Thanks, that browser is handy, but how do we get to it from this site? it seems the only way is to come to this thread. It would be great if that was inlcuded on the home page or the left side navigation

**Comment by kenwith** [comment]
@DeanGross - it is a good idea. These are all open source now and owned by community, product team, MVPs and experts like you, etc...   I agree a way to get between modules would be helpful. Perhaps you could create a pull request to make it happen and we can get it reviewed by some people? The navigation on the left is pulled from files here: https://github.com/MicrosoftDocs/office-docs-powershell/tree/master/teams/docs-conceptual    for Teams and there is a similar for every module. I know that the 'conceptual' topics.. those in the top part of the navigation can be added to fairly easily.. maybe an article there that is a link to other modules?

**Comment by yogkumgit** [comment]
@kenwith  Thank you very much for sharing this explanation. @DeanGross 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
