### ISSUE TITLE
-SourceFolder Parameter is missing in this article

### ISSUE THREAD

**Issue by PramodShedbal** [MicrosoftDocs/office-docs-powershell#10731]
Hi Team,

Please add -SourceFolder and the folders in the article so that the admin can choose the folders to restore the items. 
this parameter was present in the past.

**Comment by chrisda** [comment]
@PramodShedbal, which article are we talking about?

**Comment by yogkumgit** [comment]
@PramodShedbal We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
