### ISSUE TITLE
Update Start-ManagedFolderAssistant documentation for -AggMailboxCleanup

### ISSUE THREAD

**Issue by blacktirion** [MicrosoftDocs/office-docs-powershell#10733]
Please update the Cmdlet documentation for Start-ManagedFolderAssistant. The parameter I have just recently used is -AggMailboxCleanup. This appears to be a parameter/function pairing that allows a more "Aggressive" cleanup cycle in the case where a user's mailbox items are not moving to archive even though the policies are set and the retention is met.

I would update the documentation, but I am not entirely sure of the entire functionality of this parameter, and neither is INFOSYS support that Microsoft contracts with. This should also be sent out to Microsoft contractors as a KB that could fix the above behavior, if appropriate.

**Comment by chrisda** [comment]
@blacktirion, that parameter is currently described as "reserved for internal Microsoft use", which is never done arbitrarily.

Are you being directed to use that parameter in other Microsoft content (blocks, articles, etc.)?

**Comment by blacktirion** [comment]
No other content references this command, but it appears to fix issues as I described above. The Microsoft Premier/Unified support contractor was not aware of this flag yet it appeared to be the fix for the issue. I wouldn't have wasted my time with support if this flag was documented with its functionality. 

There does appear to be another user who ran in it on this old technet thread: https://social.technet.microsoft.com/Forums/ie/en-US/56260407-4b15-407e-9079-2a97c79abf0c/retention-tags-expired-items-not-deleted-from-deleted-items?forum=exchange2010 (2nd reply from bottom)

If Microsoft's contracted support is not aware of how to fix these types of issues, and it falls on the customer to discover a method to fix these issues, then it should be documented so that customers do not wasted time engaging with support if they aren't going to have any solutions.

**Comment by chrisda** [comment]
@blacktirion, I added the following description to the parameter:

> The AggMailboxCleanup switch specifies a more aggressive processing cycle if items aren't moving as quickly as they should. You don't need to specify a value with this switch.

It should be visible by ~ 4:00PM F 4/14 PDT (GMT-7).

OK?

**Comment by blacktirion** [comment]
Thank you @chrisda!

**Comment by chrisda** [comment]
Thanks for the feedback.

Closing
