### ISSUE TITLE
-WhatIf has no effect

### ISSUE THREAD

**Issue by badsector-82** [MicrosoftDocs/office-docs-powershell#10732]
![image](https://user-images.githubusercontent.com/47413182/231984368-43c07957-5615-4919-9048-49407aafa33d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94495258-5811-ddb9-396b-72bfe78d0503
* Version Independent ID: 0c471358-9c06-0e84-2a9e-457d8954ea47
* Content: [Set-CsTeamsClientConfiguration (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csteamsclientconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsClientConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsClientConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @badsector-82 
Thanks for your feedback, I'll propose to edit the article stating that.
