### ISSUE TITLE
Self-Signed Certificates?

### ISSUE THREAD

**Issue by tinojr** [MicrosoftDocs/office-docs-powershell#10739]
I'm just curious why this article is recommending self-signed certificates for CBA. Why not list alternatives such as Microsoft PKI or 3rd party CA?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication in Exchange Online PowerShell and Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@tinojr, the feature owners are still looking into this, but I can give you my initial thoughts:

After reading through the article, we never actually say that we recommend a self-signed certificate. We certainly don't talk about using third-party CA certs or Microsoft PKI, which in and of itself can be inferred as a recommendation. The article does mention a recommended *method* for creating a self-signed cert of the two different methods described (which could also be misinterpreted as a recommendation for self-signed certs).

Other than the time spent creating the self-signed cert if you don't need to, there doesn't appear to be a clear benefit or detriment to self-signed vs. third-party certs. The main issue with self-signed certs in most scenarios is the lack of device/client trust, but that doesn't seem to be an issue with CBA. Is there actually a benefit to the lack of widespread trust of the self-signed cert in the CBA scenario? It's a bit of a stretch, but that's all I could think of.

**Comment by yogkumgit** [comment]
@tinojr Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by tinojr** [comment]
Sorry, I am slow to respond. I was at PS summit last week. Yes, this can be misinterpreted to think self-signed cert is recommended and safe. I think it's important that security teams are aware of a need for certificates rather than a developer making a self-signed cert and forgetting about it. Security teams can better track certificates and revoke when necessary. While MITM is not guaranteed with self-signed certs, it can increases the likelihood. We use Microsoft PKI and did a lot of trial and error to figure out that a web-server template was the one to use.  Since the default in using new-selfsignedcertificate cmdlet is to use a default type of 'SSLServerAuthentication' then it makes sense why a self-signed cert (using cmdlet) worked. I just think Microsoft needs to place more emphasis and guidance on non-self-signed certificates.

**Comment by chrisda** [comment]
@tinojr, I made some changes to the article in a branch. I toned-down the references from "self-signed certificates" to "certificates" and changed Step 3 to differentiate between self-signed and Microsoft PKI.  Anything you could add or clarify in the Microsoft PKI bit would be appreciated. You don't need to write wholesale procedures, just important words or terms.

I was hoping I could simply link off to existing Microsoft PKI procedure articles. I found [this](https://learn.microsoft.com/en-us/mem/configmgr/core/plan-design/network/example-deployment-of-pki-certificates), but I'm not sure which section best applies (if any)?

Anyway, my proposed changes are visible here:

<https://github.com/MicrosoftDocs/office-docs-powershell/blob/CBACert-chrisda/exchange/docs-conceptual/app-only-auth-powershell-v2.md#step-3-generate-a-certificate>

Just click Edit (pencil icon) on that page and make your changes. Further instructions if you need them are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

**Comment by tinojr** [comment]
Thanks @chrisda . Let me ping my security team to get the steps they performed. They generated a pfx and cer for me, but i know we can extract the cer from the pfx, so maybe we focus on how to generate pfx for a web server, then i can add a few lines of code to extract cer.

**Comment by tinojr** [comment]
Ok, sorry for delay. I spoke with one of our senior security folks and they generally make all their CSR's with OpenSSL, sometimes ignoring us infrastructure folks who send them a CSR, anyway in this case they generated the CSR via OpenSSL. Then they used that to paste into MS PKI and select web-server template, then exported and used OpenSSL again to generate the PFX and CER files. I am recognizing this is their preference, when thinking of another cert they created for me. I still think it's technically possible to do the whole thing in MS PKI, but i'm sorry i don't have the exact steps for you. I suppose just listing it the way you have it, lowering emphasis form self-signed and listing MS PKI as an option is good for now. When i get time, i'll try to setup MS PKI in my lab and see if i can reproduce steps (not anytime soon). Thanks again for being receptive to feedback.
