### ISSUE TITLE
Navigation between module documentation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1073]
Please update the left and/or right side navigation so that we can more easily get to the documentation for other PowerShell modules, i.e. it would be helpful if we could easily navigate between the various Office 365 modules (teams, exchange, sharepoint, etc). Currently there is not even any way to navigate back up to the master PowerShell page at https://docs.microsoft.com/en-us/powershel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d426f1f-d15b-4ba5-d980-fea5fa044188
* Version Independent ID: f10f10c6-974a-a748-732d-d7a7a4d9a5c7
* Content: [Overview](https://docs.microsoft.com/en-us/powershell/sharepoint/overview?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/overview.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/overview.md)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by kenwith** [comment]
@DeanGross - this is a great idea and I will look into how we can do this. I will track this across all Office modules in https://github.com/MicrosoftDocs/office-docs-powershell/issues/1072 and will close this one. Thanks for feedback!
