### ISSUE TITLE
New-SafeAttachmentPolicy: -MakeBuiltInProtection remains undocumented

### ISSUE THREAD

**Issue by matsimon** [MicrosoftDocs/office-docs-powershell#10747]
The Option `-MakeBuiltInProtection` of `New-SafeAttachmentPolicy` seems to have a placeholder description:
```
{{ Fill MakeBuiltInProtection Description }}
```

A merged PR that updated `Set-SafeAttachmentPolicy` indicates, that it is likely for Microsoft internal use only 
and should either be marked as such, or dropped entirely from public documentation like in this PR
* #9189

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5dbd0ff3-ce5b-81a8-8e01-f7274426f6dc
* Version Independent ID: e239c1a3-e93b-810e-35b2-f7fcea5d5f07
* Content: [New-SafeAttachmentPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-safeattachmentpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-SafeAttachmentPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@matsimon, I added the "reserved for internal Microsoft use" description.

I wouldn't get too hung up on empty parameter descriptions. When you have 1400+ cmdlets and 14,000+ parameters, empty parameter descriptions are part of the story. Parameter availability vs. functionality are two different things.

In this particular case, I know about Built-in protection, and I can't imagine any reasonable scenarios where customers need to manually designate a Safe Links policy or a Safe Attachments policy as part of Built-in protection. It's likely that the parameter is used by the Microsoft 365 Defender portal when you turn on Built-in protection for the first time.

Thanks for the feedback.

Closing

**Comment by chrisda** [comment]
And, I actually used a different description based on the RecommendedPolicyType description:

> The MakeBuiltInProtection parameter is used for Built-in protection policy creation as part of [Preset security policies](https://learn.microsoft.com/microsoft-365/security/office-365-security/preset-security-policies). Don't use this parameter yourself.

**Comment by matsimon** [comment]
It's understandable that such things can slip through in the vast amount of cmdlets. Nonetheless I appreciate that you when ahead an clarified the description on the switch. It does actually help customers and partners to avoid using switches meant for Microsoft-internal use. 😃
