### ISSUE TITLE
Document key pair generation using other tools

### ISSUE THREAD

**Issue by MushyMiddle** [MicrosoftDocs/office-docs-powershell#10745]
In step 3 (https://learn.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#step-3-generate-a-self-signed-certificate), you should document the requirements for a key pair so other tools can be used (OpenSSL, Keychain Access, etc.).  Not everyone wants to use PowerShell for everything, and it's a lot easier to manage key pairs using other tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication in Exchange Online PowerShell and Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MushyMiddle, your comment is semi-related to Issue #10739 (why are we only promoting the use of self-signed certs)? That's being looked into, and you can see my thoughts in the other issue.

**Comment by yogkumgit** [comment]
@MushyMiddle Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
