### ISSUE TITLE
Missing description for -RemoveCanceledMeetings

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [MicrosoftDocs/office-docs-powershell#10743]
Missing description for -RemoveCanceledMeetings

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d95eb528-ab96-b415-981c-35d50c90dba0
* Version Independent ID: 0433f43b-538d-8000-a11d-69b4a5c97e0e
* Content: [Set-CalendarProcessing (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-calendarprocessing?view=exchange-ps#parameters)
* Content Source: [exchange/exchange-ps/exchange/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@TurnItOff-OnAgain, empty parameter descriptions are a known issue when we're dealing with 1400+ Exchange-related cmdlets with 14,000+ parameters. Availability and functionality are two different things. See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for a detailed explanation about empty parameter descriptions.

 Are you being directed to use that parameter from other content? Or are you just pointing out that the description is empty?

**Comment by TurnItOff-OnAgain** [comment]
I am not being directed to use this. I was looking at the documentation while using the command and noticed that the documentation is incomplete. I was not sure if it was not complete on purpose, or was an oversight.

Looking through the explanation about empty parameters, it makes no sense. There are parameters out there that are known, that have a function, and that function is known, but you won't update the documentation about it? Having a lot of cmdlets and parameters doesn't seem like a good reason to purposefully have incomplete documentation. The initial report you linked is 2 years old. Someone can't take time in two years to add a description?

**Comment by yogkumgit** [comment]
@TurnItOff-OnAgain Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
