### ISSUE TITLE
How can I determine the "rule" associated with an entry

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10761]
We're trying to replicate your UI in our product.  For the O365 UI field "Select a rule" you have 4 choices:

Advanced setup
Number starting or ending with
Phone number range
Single number

There are only 7 attributes available

* Description - no
* Identity / TreatmentId - from what I see, these are both the same and indicate the name of the routing rule
* Target - no, the action for rule
* TargetType - no, indicates what the GUID in the Target is
* TreatmentPriority - no, the evaluation order

Which leaves us with Pattern.  While parsing it, I could determine if it is a range (by the length of the attribute), I don't see how I could accurately determine if it was from Advanced setup, Number starting or ending with, nor Single number rules

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a10113f-d621-f44f-e46a-c6878b77936a
* Version Independent ID: b9656c23-7729-eb45-12ba-56001465dbc1
* Content: [Get-CsTeamsUnassignedNumberTreatment (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/get-csteamsunassignednumbertreatment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by get-itips** [comment]
Hello @sarollins 
I'm afraid here we are limited to documentation changes and improvements.
For this you can try opening a support request.
Thanks,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
