### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1076]
Please provide information about how to install the Skype for Business cmdlets, something like what is done for the SharePoint online cmdlets at https://docs.microsoft.com/en-us/powershell/sharepoint/overview?view=sharepoint-ps would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6172d49e-6905-e979-bddb-6822a01eafc7
* Version Independent ID: b04220e0-2087-d566-e357-1ac46cd2d7b8
* Content: [Skype for Business cmdlet reference](https://docs.microsoft.com/en-us/powershell/skype/intro?view=skype-ps)
* Content Source: [skype/docs-conceptual/intro.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/docs-conceptual/intro.md)
* Service: **skypeforbusiness-powershell**
* Product: **unspecified**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@DeanGross - really great idea and thanks for providing feedback!

**Comment by kenwith** [comment]
Here is link: https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell I also added with this PR: https://github.com/MicrosoftDocs/office-docs-powershell/pull/1289
