### ISSUE TITLE
Incomplete Documentation Entries - B2DumpsterArchiver and B2IPMArchiver

### ISSUE THREAD

**Issue by Mattheww65** [MicrosoftDocs/office-docs-powershell#10766]
The following titles are showing tags, and have incomplete documentation entries:

B2DumpsterArchiver - {{ Fill B2DumpsterArchiver Description }}
B2IPMArchiver - {{ Fill B2IPMArchiver Description }}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0404960d-05e8-6e6f-8063-ebed163ecefd
* Version Independent ID: d79b2d09-a176-d22e-e5ad-49a8fa22df2a
* Content: [Start-ManagedFolderAssistant (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/start-managedfolderassistant?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Mattheww65, empty parameter descriptions are a known commodity. Availability vs. functionality are two different things. You can read more about it [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).

Are you being directed to use these parameters in other content?
