### ISSUE TITLE
Get-EXOMobileDeviceStatistics LastSuccessSync

### ISSUE THREAD

**Issue by fizdalf** [MicrosoftDocs/office-docs-powershell#10778]
If I pull data with this script instead of the non-EXO version, the LastSuccessSync value doesn't show, or only in some occasions, there doesn't seem to be a logic behind it. Just most mobile devices won't have a value.

I'm forced to use the non-EXO version. Is this intended?

**Comment by chrisda** [comment]
@fizdalf, a couple of things to think about:

- What version of the ExchangeOnlineManagement module are you using? The latest public version is 3.1.0. You can try using a newer Preview version of the module (currently 3.2.0-Preview3) to see if that helps.
- Are you connecting in REST API mode or Basic authentication mode (using the UseRPSSession switch)? Try one vs. the other.

If you're using v3.1.0, you can open a support ticket. And/or, you can try sending the information to `exocmdletpreview[at]service[dot]microsoft[dot]com.`

**Comment by yogkumgit** [comment]
@fizdalf Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
