### ISSUE TITLE
Reference to Get-MailUser and SoftDeleted

### ISSUE THREAD

**Issue by Ritty5** [MicrosoftDocs/office-docs-powershell#10775]
The SoftDeleted is not a documented parameter on Get-MailUser, the parameter that is documented is SoftDeletedMailUser.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc998569-646c-cd20-c3cd-b5d07e6f62ee
* Version Independent ID: b7d7d129-9092-8e7d-5bc1-e49e24b54603
* Content: [Remove-MailUser (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/remove-mailuser?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-MailUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Remove-MailUser.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Ritty5, fixed.

Similarly, the correct parameter name on Get-Mailbox is SoftDeletedMailbox, and I found and fixed a couple of incorrect references for that as well.

Thanks for the feedback.

Closing
