### ISSUE TITLE
Set-SPOTenant corrections needed

### ISSUE THREAD

**Issue by tomresing** [MicrosoftDocs/office-docs-powershell#108]
Set-SPOTenant has multiple occurrences of what looks like placeholder text. This was reported to me by a customer and there is a comment on the page from another customer stating similar.

The first occurrence I see is in the Examples section. There are two statements that appear to be notes to the author to fill the placeholder text will real example code and descriptions.

> PS C:\> {{ Add example code here }}

> {{ Add example description here }}

There are multiple parameters with text like this:

> {{Fill CommentsOnSitePagesDisabled Description}}

**Comment by kenwith** [comment]
Thanks for opening this issue @tomresing ! Looking into this with you and some others to get resolved.

**Comment by kenwith** [comment]
Just an update, I am working with @nsshommo to get these descriptions filled in. He will be submitting Pull Requests soon.

**Comment by tomresing** [comment]
Thanks for the update, @kenwith. I did chat with Kirk Stark about the situation today, too.

**Comment by kenwith** [comment]
Set-SPOTenant has been updated. Closing this issue. Thank you for feedback!

Also, at the same time most of the other SPO cmdlets were fixed and those that still had placeholder are being tracked and updated. @VesaJuvonen  working on that portion along with product team. Any other specific instances feel free to open another issue. Thanks all! Docs are better for it. :)

**Comment by tomresing** [comment]
Great work! Published version is very much improved. https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps
