### ISSUE TITLE
Release-QuarantineMessage cmdlet is not available in ExchangeOnlineManagement module

### ISSUE THREAD

**Issue by ktb-jcm** [MicrosoftDocs/office-docs-powershell#10808]
While both ExchangePowershell and ExchangeOnlineManagement modules have the "Get-QuarantineMessage" cmdlet available, the "Release-QuarantineMessage" cmdlet is **not** available in ExchangeOnlineManagement.

Overall the powershell documentation for the Exchange-related commands is not correctly or clearly delineating what is available for on-prem 20th century Exchange servers and modern 21st century cloud-based solutions.

1. Update the documentation accordingly.
2. Add support for "Release-QuarantineMessage" to the ExchangeOnlineManagement module.

**Comment by chrisda** [comment]
@ktb-jcm, Release-QuarantineMessage is available in Exchange Online PowerShell and in Security & Compliance PowerShell.

Few cmdlets are actually in the ExchangeOnlineMangement module itself. Those cmdlets are listed [here](https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#cmdlets-in-the-exchange-online-powershell-module).

Other than the obvious Connect/Disconnect cmdlets, all other cmdlets in the module are useless until you connect to Exchange Online PowerShell or Security & Compliance PowerShell.

I would disagree about the attribution of which cmdlets/parameters are available in what version of Exchange: each topic has an 'applicable' tag at the top, and each individual parameter has an 'Applicable' tag in its metadata that I endeavor to review ~quarterly.

You're right in the sense that cmdlets in the ExchangeOnlineManagement module itself are odd ducks that don't really fit, but all of them except Connect-IPPSSession are fundamentally Exchange Online PowerShell cmdlets.

If you're saying that you don't have access to Release-QuarantineMessage when you connect to Exchange Online PowerShell using the ExchangeOnlineManagement module, [check your RBAC permissions in Exchange Online PowerShell](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions). Here are the results from my Microsoft 365 E5 tenant:

```powershell
PS C:\Users\jdoe> $Perms = Get-ManagementRole -Cmdlet Release-QuarantineMessage
PS C:\Users\jdoe> $Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}

Role           RoleAssigneeType RoleAssigneeName
----           ---------------- ----------------
Security Admin RoleGroup        Organization Management
Security Admin RoleGroup        Security Administrator

Role              RoleAssigneeType RoleAssigneeName
----              ---------------- ----------------
Transport Hygiene RoleGroup        Organization Management
Transport Hygiene RoleGroup        Hygiene Management
```

If you aren't a member of any of those role groups, then you won't have access to the cmdlet.

**Comment by ktb-jcm** [comment]
We don't have Exchange on-prem. It's all cloud-first.
I have messages in quarantine I want to release en masse.
I can't do that with ExchangeOnlineManagement.

Docs have misleading indicators:
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/85756464/d75f1162-4aff-4526-8e59-946feed15546)

Since the quarantine messages are, in fact, **not** in our environment until release, why is the Get-QuarantineMessage cmdlet available, but not the release option?

This is nonsensical.

**Comment by ktb-jcm** [comment]
To put it another way, I can't use ExchangePowershell, because of course we don't have an exchange server:

```
> Import-Module ExchangePowerShell
Import-Module : Exchange Server system variable ExchangeInstallPath missing.
At line:1 char:1
+ Import-Module ExchangePowerShell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Exchange Server...llPath missing.:String) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : Exchange Server system variable ExchangeInstallPath missing.,Microsoft.PowerShell.Commands.ImportModuleCommand

```
Unless you're saying I have to do this **on** the Exchange server. Which, of course, is impossible.

**Comment by chrisda** [comment]
@ktb-jcm, the ExchangeOnlineManagement module is the mechanism that allows you to connect to Exchange Online PowerShell; there's no other way to connect.

Have you tried following the instructions in this article to connect?

[Connect to Exchange Online PowerShell](https://learn.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell)

Those instructions have nothing to do with Exchange Server. The ExchangeOnlineManagement module doesn't work in on-premises Exchange.

**Comment by ktb-jcm** [comment]
@chrisda Sorry for the delay, been busy. Yes I've successfully connected with the ExchangeOnlineManagement powershell, and yes I definitely have permission to release message in quarantine. 
I can easily retrieve the messages in quarantine, but the "Release-Quarantine" cmdlet simply doesn't exist, even after I've imported the module and connected.

Here's a redacted sceenshot illustrating the issue:
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/85756464/51c6ac71-9e60-40c9-9091-e7f44a4a3faa)

I'm using a WVD, due to restrictions on my work laptop, and authenticating with an admin account. The admin account gets its permissions via AAD group and role membership. Nothing unusual here. Cmdlet simply doesn't exist.

**Comment by chrisda** [comment]
@ktb-jcm, see my earlier comments:

If you're saying that you don't have access to Release-QuarantineMessage when you connect to Exchange Online PowerShell using the ExchangeOnlineManagement module, [check your RBAC permissions in Exchange Online PowerShell](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions). Here are the results from my Microsoft 365 E5 tenant:

```powershell
PS C:\Users\jdoe> $Perms = Get-ManagementRole -Cmdlet Release-QuarantineMessage
PS C:\Users\jdoe> $Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}

Role           RoleAssigneeType RoleAssigneeName
----           ---------------- ----------------
Security Admin RoleGroup        Organization Management
Security Admin RoleGroup        Security Administrator

Role              RoleAssigneeType RoleAssigneeName
----              ---------------- ----------------
Transport Hygiene RoleGroup        Organization Management
Transport Hygiene RoleGroup        Hygiene Management
```

If you aren't a member of any of those role groups, then you won't have access to the cmdlet.

**Comment by chrisda** [comment]
I should add that Organization Management = Global Administrator in AAD, and Security Administrator = Security Administrator in AAD. Hygiene Management is exclusive to Exchange Online.

I would also say check your EXO Module version (v3.1.0 is current) and your connection mode: are you connecting using the RPSSession switch (traditional remote PowerShell cmdlets) or without the switch (REST API mode)? Whichever way you're using, try the other way to see if that makes a difference.

**Comment by yogkumgit** [comment]
@ktb-jcm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
