### ISSUE TITLE
Direction IntraOrg

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/office-docs-powershell#10806]
The -Direction parameter for Get-MailDetailATPReport should include IntraOrg as one of the supported values.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72a47576-e439-efc4-6a22-c9c6a11edbe3
* Version Independent ID: bd26162f-3fde-657a-0eb1-c6b49fbdccc7
* Content: [Get-MailDetailATPReport (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-maildetailatpreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailDetailATPReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-MailDetailATPReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mrkeiths, fixed. It also appears that Direction in Get-MailTrafficATPReport also supports IntraOrg, so I added it there.

In the future, you too can make changes like this yourself directly. Instruction are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
