### ISSUE TITLE
-AsJob description is absent

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1080]
The description of -AsJob parameter is not present in the cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e17ba3b2-f818-6a09-411d-aa8563705325
* Version Independent ID: e62b6323-aba4-5286-70f0-fcccd8cf23be
* Content: [Get-CsTenant (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Get-CsTenant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTenant.md)
* Service: **skypeforbusiness-powershell**
* Product: **unspecified**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
All Skype cmdlets are undergoing audit and being tracked internally to make sure every cmdlet has an example and descriptions.
