### ISSUE TITLE
No Description for -Recycle Parameter

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/office-docs-powershell#1081]
There is no description for the -Recycle Parameter to say what it does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c175be-fbdb-d99d-8106-4635f3e6ddc6
* Version Independent ID: 3054989c-a9fb-74aa-9121-fdb24b1a3f65
* Content: [Remove-PnPList (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnplist?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPList.md)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen to review

**Comment by VesaJuvonen** [comment]
thx @NPrice99, this will be fixed with the June 2018 content refresh for PnP PowerShell cmdlets. Appreciate the input.
