### ISSUE TITLE
Foreach statement makes EXO cmdlets much slower

### ISSUE THREAD

**Issue by yukiiis** [MicrosoftDocs/office-docs-powershell#10816]
When **foreach statement** is used, **Get-MailboxPermission** is way faster than **Get-ExoMailboxPermission**. 50min vs 3h.
We have about 4000 mailboxes.  Does anyone know why this happens as according to the document, EXO cmdlets should be faster than the old ones.

Sample code below:
```powershell
# If Type is EXO, the EXO Cmdlet will run.

$type = 'EXO'

$global:AllUserMailboxInfo = Get-EXOMailbox -Filter {RecipientTypeDetails -eq 'UserMailBox'} -PropertySets Minimum -ResultSize unlimited

$permissions = foreach ($user in $AllUserMailboxInfo)
{
    if ($type -eq 'EXO')
    {$user | Get-EXOMailboxPermission -verbose:$false}
    else
    {$user | Get-MailboxPermission -verbose:$false}
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module and V3 module](https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#properties-and-property-sets-in-the-exchange-online-powershell-module:%7E:text=nine%20exclusive%20Get%2DEXO*%20cmdlets%20for%20Exchange%20Online%20PowerShell%20that%20are%20optimized%20for%20speed%20in%20bulk%20data%20retrieval%20scenarios%20(thousands%20and%20thousands%20of%20objects))
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@yukiiis, if you're using v3.1.0 of the ExchangeOnlineManagement module, try using the latest Preview version to see if that helps (v3.2.0-Preview3). Or if you're using a Preview version of the module, try switching to v3.1.0.

You can try sending details to `exocmdletpreview[at]service[dot]microsoft[dot]com` to see if they have any suggestions.

**Comment by yukiiis** [comment]
Thanks @chrisda ! I was using v3.1.0, Have just installed the latest Preview version (v3.2.0-Preview3), but still the same. EXO cmdlets took much longer to complete.

**Comment by yogkumgit** [comment]
@yukiiis Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
