### ISSUE TITLE
Teams Calling Delegates Added Via PowerShell With Manage Settings $true Do Not Appear Within The Teams Client Under Settings > General > Manage Delegates.

### ISSUE THREAD

**Issue by ajacks88** [MicrosoftDocs/office-docs-powershell#10821]
I am writing several PowerShell scripts to automate the setting of calling delegates on some of our Teams accounts. When using the New-CsUserCallingDelegate or Set-CsUserCallingDelegate cmdlets to either add/update a delegate for another account, those delegators do not appear within the Teams client under Settings > General > Manage Delegates > People you support.

When adding a delegate manually via the Teams client, however, those delegates do show up correctly.

Example: 

User A has no calling delegates configured.

Admin runs the following command after Connect-MicrosoftTeams
New-CsUserCallingDelegate -Identity UserA@something.com -Delegate UserB@Something.com -MakeCalls $True -ReceiveCalls $True -ManageSettings $True

Admin then runs the following command:
Get-CsUserCallingSettings -Identity UserA@Something.com

Admin verifies that User B is indeed set as a delegate of User A

User A goes into their Teams client and navigates to Settings > General > Manage Delegates > People you support, and nothing is listed.

Please let me know if you need any additional information.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d6e47fb-b461-2cc4-ff82-58f9cea5ed85
* Version Independent ID: 5995223b-6cfd-5c2d-3ada-3d576624b773
* Content: [Set-CsUserCallingDelegate (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsUserCallingDelegate.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by ajacks88** [comment]
I have waiting in case it just takes some time, but it does not appear to be updating. I also closed out my teams client to see if that would do it, it didn't change anything.

**Comment by ajacks88** [comment]
I've also verified the added delegate is not showing up via the web client either.

**Comment by ajacks88** [comment]
Just kidding, i figured it out. I was using two specific users to test my scripts, and i had both User A and User B as delegates of each other, and it seems teams does not like that and will hide you from the list of "people i support" if you are both delegates of each other. It may be worth noting this scenario in the documentation for the powershell cmdlets, or perhaps even within the teams client where you can add/remove delegates.

Feel free to close this out

**Comment by get-itips** [comment]
@ajacks88 Thanks Andy.
@yogkumgit Closing.
