### ISSUE TITLE
Could we have some examples for -ClientSideComponentId  and -ClientSideComponentProperties 

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/office-docs-powershell#1082]
Hi
Could we have some examples for ClientSideComponentId and ClientSideComponentProperties please ?

Thanks

Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b38e3d82-0583-ad60-4cac-6407ce43615c
* Version Independent ID: e114139d-1dad-eecd-fe0e-29f834096d7c
* Content: [Add-PnPField (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpfield?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPField.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPField.md)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen to review

**Comment by erwinvanhunen** [comment]
Thank you @NPrice99 : Added in PR https://github.com/SharePoint/PnP-PowerShell/pull/1605

**Comment by VesaJuvonen** [comment]
Closed based on the update from @erwinvanhunen as PR is merged.
