### ISSUE TITLE
Parameter PolicyType has a wrong description

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/office-docs-powershell#10825]
Hi,

the parameter PolicyType has the same description as the parameter PolicyName. Can you please update the article accordingly to show the available parameters.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b185b8d0-fa84-7ea6-4531-cf4eb6cc26fd
* Version Independent ID: 24754aee-bff2-fa16-e7e6-af45362fd916
* Content: [New-CsBatchPolicyAssignmentOperation (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/new-csbatchpolicyassignmentoperation?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for your feedback!
