### ISSUE TITLE
Page contains wrong documentation

### ISSUE THREAD

**Issue by v-2caque** [MicrosoftDocs/office-docs-powershell#10834]
The explanation for parameter -filter1 is wrong.

It contains examples with symbol = like -> -Filter1 = @("Activity", "LabelApplied", "LabelRemoved")

> If you use this parameter with other filter parameters, AND behavior is used across parameters. For example:
>
> -Filter1 = @("Activity", "LabelApplied", "LabelRemoved") -Filter2 = @("Workload", "Exchange") returns records with the activity values LabelApplied or LabelRemoved for the Exchange workload. In other words, ((Activity eq LabelApplied) OR (Activity eq LabelRemoved)) AND (Workload eq Exchange)._

And this is wrong.

This parameter has to be executed without = like its reflected on the example 4 of the article:

```powershell
Export-ActivityExplorerData -StartTime "07/06/2022 07:15 AM" -EndTime "07/08/2022 11:08 AM" **-Filter1 @("Activity", "FileArchived") -OutputFormat Csv**
```

If you executed with = you will receive:

```powershell
PS C:\Users\outlook> Export-ActivityExplorerData -StartTime 2023/04/12 -EndTime 2023/05/11 -Filter1 = @("Activity", "LabelApplied") -Filter2 = @("Activity", "LabelApplied")
Cannot validate argument on parameter 'Filter1'. The number of provided arguments (1) is fewer than the minimum number of allowed arguments (2). Provide 
more than 2 arguments, and then try the command again.
    + CategoryInfo          : InvalidData: (:) [Export-ActivityExplorerData], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Export-ActivityExplorerData
    + PSComputerName        : eur01b.ps.compliance.protection.outlook.com
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f188a25-7afc-f6cf-5d2a-5bc9fd08ca1f
* Version Independent ID: 33ed55ee-de0e-2c0c-2141-9a21083392cd
* Content: [Export-ActivityExplorerData (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/export-activityexplorerdata?view=exchange-ps#example-4)
* Content Source: [exchange/exchange-ps/exchange/Export-ActivityExplorerData.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Export-ActivityExplorerData.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@v-2caque, fixed.

In the future, you too can make changes like this yourself; no need to open an issue first. For instructions, see [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
