### ISSUE TITLE
[Set-CsAutoAttendant] Not Mentionned to set ForceListenMenuEnabled to $True 

### ISSUE THREAD

**Issue by platinarock** [MicrosoftDocs/office-docs-powershell#10835]
Hello, For the ForceListenMenuEnabled parameter, it is not mentionned to set it to True with the Set-CsAutoAttendant command.

Set-CsAutoAttendant -Instance $autoAttendant

Set-CsAutoAttendant: Could not find a parameter matching parameter name 'ForceListenMenuEnabled'.

In C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\5.1.0\custom\Merged_custom_PsExt.ps1:7964 car:94

+ ... igAPI.Cmdlets.internal\Set-CsAutoAttendant @PSBoundParameters @httpPi ...

+ CategoryInfo: InvalidArgument: (:) [Set-CsAutoAttendant], ParentContainsErrorRecordException

+ FullyQualifiedErrorId: NamedParameterNotFound,Set-CsAutoAttendant

we can pass it to False but not to true

Could you have any answers on this?

Best regards

Pierre

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8aedf07e-205e-ebe8-6351-1c1956f99b85
* Version Independent ID: c18defb2-97e8-1196-dc32-47260dad5c09
* Content: [Set-CsAutoAttendant (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csautoattendant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsAutoAttendant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsAutoAttendant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @platinarock 

It seems ForceListenMenuEnabled is a SwitchParameter and not a boolean
I'll update the article.

Thanks for your feedback!
