### ISSUE TITLE
Parameter is not described

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1084]
-AllowFederatedParticipantJoinAsSameEnterprise parameter is not described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb630b9-b94d-a647-ca21-821e1d520b21
* Version Independent ID: ede8297e-aa49-fc5e-23bb-2d678bc23e6b
* Content: [Set-CsConferencingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Set-CsConferencingPolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsConferencingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsConferencingPolicy.md)
* Service: **skypeforbusiness-powershell**
* Product: **unspecified**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
All Skype cmdlets are undergoing audit and being tracked internally to make sure every cmdlet has an example and descriptions.
