### ISSUE TITLE
Parameters -Action Missing other values

### ISSUE THREAD

**Issue by JBines** [MicrosoftDocs/office-docs-powershell#10852]
Hey party ppl! 

Other values Search, Preview, Purge, Export should be detailed as well as, providing multiple values is not supported, although the cmdlet will not throw an error. 

Cheers
J

Parameters
-Action

The Action parameter specifies that type of search action that the filter is applied to. A valid value for this parameter is All, which means the filter is applied to all search actions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1aa7139-e8c1-3f04-3f00-390d25ceb3d5
* Version Independent ID: 0a9ff2fa-2110-7b63-aeab-0b44fb4c9bc3
* Content: [New-ComplianceSecurityFilter (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-compliancesecurityfilter?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceSecurityFilter.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JBines, curiously, the Action parameter was fully described in New-ComplianceSearchAction, so I just copied the values and the description of values from there.

Thanks for the feedback.

Closing
