### ISSUE TITLE
Documentation missing: "-IsMemberAllowedToEditContent"

### ISSUE THREAD

**Issue by dunck** [MicrosoftDocs/office-docs-powershell#10861]
Documentation for `IsMemberAllowedToEditContent` parameter is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80326e44-6beb-8983-57ab-8333608c504b
* Version Independent ID: 8962c0dc-72a3-208a-33de-6a89cd56b6fc
* Content: [Set-UnifiedGroup (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dunck, empty parameter descriptions are a known commodity. Availability vs. functionality are two different things. You can read more about it [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).

Are you being directed to use that parameter in other content?
