### ISSUE TITLE
Security & Compliance PowerShell module: eDiscovery cmdlets are not available when using app-only authentication.

### ISSUE THREAD

**Issue by romanleshchenko** [MicrosoftDocs/office-docs-powershell#10867]
Hi Team!

I would like to use my own Azure application so I can work with the Security & Compliance cmdlets. So I've created a multitenant Azure application and added Exchange.ManageAsApp API permission (application scope) and granted it.

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/83818285/aaab2964-b2f3-46b4-bdff-8e6654d967e9)

After that I added 2 Azure built-in roles for app service principal:

- Exchange Administrator
- Compliance administrator

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/83818285/def884c7-cfa2-419f-b301-5fe6ee8cc86b)

All the steps above I did based on [MS documentation](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#step-1-register-the-application-in-azure-ad).

I also assigned all needed roles in MS Purview portal based on [this documentation](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-assign-permissions?view=o365-worldwide#assign-ediscovery-permissions).

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/83818285/1b305cff-afc4-4e91-9c26-611319db7943)

So, when I get a token from `https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/token`

using the following body:

```
client_id: <client_id>
client_secret <client_secret>
scope: https://outlook.office365.com/.default
grant_type: client_credentials
```

I use this token to connect to Security & Compliance:

```
$accessToken = "<access_token>"

$exTokValue = (ConvertTo-SecureString "Bearer $accessToken" -AsPlainText -Force)

$exCred = New-Object System.Management.Automation.PSCredential("<tenant_upn>", $exTokValue)

$exUrl = "https://ps.compliance.protection.outlook.com/powershell-liveid?BasicAuthToOAuthConversion=true"

$O365Sess = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri $exUrl -Credential $exCred -Authentication Basic -AllowRedirection

Import-PSSession $O365Sess
```

So, as a result I get all commands in the session, **except eDiscovery commands** like, [Add-eDiscoveryCaseAdmin](https://learn.microsoft.com/en-us/powershell/module/exchange/add-ediscoverycaseadmin), [Get-eDiscoveryCaseAdmin](https://learn.microsoft.com/en-us/powershell/module/exchange/get-ediscoverycaseadmin).

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/83818285/3e8cf8f6-f7af-4828-b9ae-fb853c3e2bb3)

Can you help me what I am missing something?

**Comment by romanleshchenko** [comment]
Hi Team!

Any updates on this ticket?

**Comment by chrisda** [comment]
@romanleshchenko, I can find no trace of it in documentation now, but I would swear there was a long-standing issue about eDiscovery cmdlets not working in CBA.

The version of the module you're using is important; if you're using v3.1.0, you can and should open a support ticket about your issues. Report back here with any findings that can help improve the documentation.

If you're using a Preview version of the module, your only recourse is to send email to `exocmdletpreview[at]service[dot]microsoft[dot]com`.

**Comment by nmf-at-bain** [comment]
I am having the same issue in version 3.1.0 - Did you ever get this figured out?

Created service principal for application and added to eDiscovery admin role group; granted manage_as_app API permissions; connect with CBA to EXO and IPPS. I am able to run any cmdlet within the scope of the app's privileges EXCEPT Get-ComplianceCase and other eDiscovery-related commands

**Comment by romanleshchenko** [comment]
the issue hasn't been resolved, why it's closed?

**Comment by yogkumgit** [comment]
@romanleshchenko Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
