### ISSUE TITLE
Parameter description absent

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1087]
-AsJob parameter description is not present. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8d01537-2e7a-b4d2-1cd8-d23070112dc6
* Version Independent ID: 52dc0d21-6d06-2a75-a801-8befbbb0eadc
* Content: [New-CsEdgeAllowList (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/New-CsEdgeAllowList?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsEdgeAllowList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsEdgeAllowList.md)
* Service: **skypeforbusiness-powershell**
* Product: **unspecified**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
All Skype cmdlets are undergoing audit and being tracked internally to make sure every cmdlet has an example and descriptions.
