### ISSUE TITLE
Get-EXOMailbox fails with Get-EXOMailbox : Could not load file or assembly 'Microsoft.Data.Services.Client, Version=5.8.4.0

### ISSUE THREAD

**Issue by lgaudreau** [MicrosoftDocs/office-docs-powershell#10875]
I'm frequently seeing the following error when running the Get-EXOMailbox command on a particular server:

Get-EXOMailbox : Could not load file or assembly 'Microsoft.Data.Services.Client, Version=5.8.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Windows Version:
Windows Server 2019 Datacenter
ExchangeOnlineManagement module 3.1.0
.NET Framework 4.8 (4.8.03761, release 528049)

This seems to have started after upgrading to the Exchange v3 module, but is inconsistent.  The error doesn't happen every time but prevents running scripts that rely on 'Get-EXOMailbox'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75cb7bca-b0ec-5cb0-ef5b-98fece1cd9de
* Version Independent ID: 24006ac8-9938-6dfd-738f-b66ef7e1174f
* Content: [Get-EXOMailbox (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-exomailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-EXOMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-EXOMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@lgaudreau, see this article:

https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#powershellget-for-rest-based-connections-in-windows

Beta versions of PackageManagement or PowerShellGet can apparently cause issues, so check for that.

If that isn't helpful, your best way forward is to open a support ticket. Report back here with any updates that can help improve documentation.

**Comment by lgaudreau** [comment]
Oh no - my apologies, this is just for the documentation.  Thank you for the link.  We're not using pre-release or beta versions but will review it in more depth.

**Comment by chrisda** [comment]
@lgaudreau, you might consider trying a newer Preview release version of the EXO Modulee to see if that helps. Also, whichever connection method you're using with the Connect-ExchangeOnline command (remote PowerShell mode with the UseRPSSession switch or REST API mode without using the UseRPSSession switch) try using the other method to see if that helps.

**Comment by yogkumgit** [comment]
@lgaudreau Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
