### ISSUE TITLE
Search-UnifiedAuditLog Error : Write-ErrorMessage : One or more errors occurred when connected to delegated tenants

### ISSUE THREAD

**Issue by elliotmunro** [MicrosoftDocs/office-docs-powershell#10873]
Hi there,

When connecting to delegated tenants exchange via the Exchange Online Managment Module, or the old RPS powershell method, we are unable to run search-unifiedauditlog commands. 

This is the error message when connecting via the old RPS module: 
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/10905707/f69c92dc-6f59-4599-91fb-aec95999ec52)

This is the error message when connecting via the new ExchangeOnlineManagement Module v3.1.0: 
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/10905707/a8fc7c32-d07f-438d-bc34-1a0fbf6b001a)

We are able to retrieve logs successfully only when connected via a global admin for the tenant, not when connected to a delegated tenant with our delegated partner admin accounts.

Using the new module, we have tested with access token and certificate based authentication, both methods allow us to run commands like get-mailbox, get-messagetrace etc, but not search-unifiedauditlog.

Let me know if you need any more information.

Cheers,
Elliot Munro

**Comment by chrisda** [comment]
@elliotmunro, if you're using v3.1.0 of the module, you should open a support ticket about this.

If you're using a Preview version, your only option is to send email to `exocmdletpreview[at]service[dot]microsoft[dot]com`.

**Comment by chrisda** [comment]
@elliotmunro, there was a similar complaint in Issue #10870 (search-unifiedauditlog not working) although without the delegated tenants angle, which is why I didn't close this issue as a duplicate.

The person in that issue said the issue seems to have gone away today.

Can you confirm or deny?

**Comment by elliotmunro** [comment]
Hi Chris, 

Thanks for your reply and apologies for missing your first message.

I've just tested and can confirm that search-unifiedauditlog is working for delegated tenants now also. Thanks for your followup on this one.

Cheers
Elliot

**Comment by chrisda** [comment]
OK.

Thanks for the feedback.

Closing
