### ISSUE TITLE
search-unifiedauditlog: Write-ErrorMessage : One or more errors occurred.

### ISSUE THREAD

**Issue by kathyblasco** [MicrosoftDocs/office-docs-powershell#10870]
Executing the following:
`    search-unifiedauditlog -SessionId $session -startdate $lastrun -enddate $today -ObjectIds "https://$($env:Tenant).sharepoint.com/sites/ROIOperationalLeadership/*" -Formatted -ResultSize 1000 -SessionCommand ReturnNextPreviewPage -debug -verbose |Export-Csv -path $file -append
`
The following is the result:
VERBOSE: Returning precomputed version info: 3.1.0
VERBOSE: POST with -1-byte payload
VERBOSE: Query 1 failed.
Write-ErrorMessage : One or more errors occurred.
At C:\Users\kathy\AppData\Local\Temp\tmpEXO_dpabnssg.vcp\tmpEXO_dpabnssg.vcp.psm1:1120 char:13
+             Write-ErrorMessage $ErrorObject
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Search-UnifiedAuditLog], Exception
    + FullyQualifiedErrorId : [Server=PH0PR22MB2662,RequestId=2a7f38ab-a80f-88db-4f67-35d06ac39585,TimeStamp=Mon, 22 May 2023 17:31:16 GMT],Write-ErrorMessage

[EXO_RESTCmdletLogs-20230522-172824019.csv](https://github.com/MicrosoftDocs/office-docs-powershell/files/11534554/EXO_RESTCmdletLogs-20230522-172824019.csv)

This same issue occurred about 1 month ago. That issue: [https://github.com/MicrosoftDocs/office-docs-powershell/issues/10693]

I am the global admin for our tenant.

**Comment by chrisda** [comment]
@kathyblasco, if you're using v3.1.0 you can and should open a support ticket about this.

If you're using a Preview version of the module, your only avenue is sending an email to `exocmdletpreview[at]service[dot]microsoft[dot]com`.

**Comment by kathyblasco** [comment]
Hi @chrisda,
I am using v3.1.0. This same issue occurred about 1 month ago. I can open a ticket. Please advise on where I would do that.

**Comment by chrisda** [comment]
@kathyblasco:

<https://learn.microsoft.com/microsoft-365/admin/get-help-support>

**Comment by kathyblasco** [comment]
I submitted a ticket with Microsoft. Ticket # is: 2305230040009859.
I will post any updates I get from them.

**Comment by geoffblack** [comment]
I submitted a ticket, as well. Support called me and I referred them to this issue and the question post. They said they would confer with backend engineers and get back to me later today.

**Comment by chrisda** [comment]
OK.

Thanks for the feedback.

Closing.
