### ISSUE TITLE
external number call forwarding for call queue agents

### ISSUE THREAD

**Issue by aphutter** [MicrosoftDocs/office-docs-powershell#10879]
is there any way to get calls ringing a CQ's agent to be forwarded to the number they set for forwarding in their teams app without having to set the queue's timeout threshold to 0 and forwarded to their external number?

Thank you very much

**Comment by shivtorov** [comment]
@aphutter 
You can't give users ability to manage queue settings.
But you can use a dummy account in front of your call queue as a workaround (you configure your agents as delegates for this dummy account, so they can tweak call forwarding settings of the dummy account to route calls to the desired destination)

For Example:

If your original setup was:
1. Inbound call arrives to AA
2. AA plays announcement and sends the call to CQ
3. CQ offers the call to agents

Then modified setup would be:
1. Inbound call arrives to AA
2. AA plays announcement and sends the call to DUMMY USER
3. DUMMY USER's call forwarding settings set to redirect all calls to CQ
4. CQ offers the call to agents

Your agent is configured as Delegate for DUMMY USER, thus they can re-direct calls to an external number.

I usually license DUMMY USER with "Microsoft Teams Shared Devices" SKU

**Comment by get-itips** [comment]
Thanks for providing an alternative solution @shivtorov 
As here we are limited documentation fixes, closing this now.
