### ISSUE TITLE
-BccBlocked missing description

### ISSUE THREAD

**Issue by bruceburge** [MicrosoftDocs/office-docs-powershell#10880]
exchange/exchange-ps/exchange/Set-DistributionGroup.md
The description has 
{{ Fill BccBlocked Description }}

**Comment by chrisda** [comment]
@bruceburge, empty parameter descriptions are a known commodity. Availability vs. functionality are two different things. You can read more about it [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).

Are you being directed to use that parameter in other content?

**Comment by bruceburge** [comment]
No I am a end user trying to use the documentation

**Comment by chrisda** [comment]
@bruceburge, blank parameter descriptions are part of doing business with 1400+ cmdlets and 14,000+ parameters. Having available but unknown parameters documented with blank parameter descriptions is the best out of a series of not too great options.

Unless that parameter somehow fulfills a scenario for you, I would say don't worry about it (hence my question about other documentation sources telling you to use it).

**Comment by bruceburge** [comment]
It took me all of a single query to find out where the [exchange team explains it purpose,](
https://techcommunity.microsoft.com/t5/exchange-team-blog/block-bcc-messages-to-distribution-groups-in-exchange-online/ba-p/2235170) I'm sorry you consider not documenting the feature set of commands "part of doing business." 

I get that is a large number of commandlets, but not having them documented is just a serious down fall, if they are made available for public use, they should be documented, and accepting that it isn't shows a series problem within the culture of those managing this.

**Comment by chrisda** [comment]
@bruceburge, I added the following for the BccBlocked parameter in New-DistributionGroup and Set-DistributionGrouo:

> The BccBlocked parameter specifies whether members of the group don't receive messages if the group is used in the Bcc line. Valid values are:
>
> - $true: If the group is used in the Bcc line, members of the group don't receive the message, and the sender receives a non-delivery report (also known as an NDR or bounce message). Other recipients of the message aren't blocked. If an external sender uses the group in the Bcc line, members of the group aren't blocked. For nested groups, the message is blocked only for members of the top-level group.
> - $false: There are no restrictions for using the group in the Bcc line of messages. This is the default value.

If you would like to edit/improve, instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
