### ISSUE TITLE
Set-CSCallQueue command taking 1-3 hours to set user as as agent

### ISSUE THREAD

**Issue by aphutter** [MicrosoftDocs/office-docs-powershell#10892]
The user object id being set is only immediately updated in the users field and not the agent field of the command output which seems to take another 2 hours on average to set properly and have the agent active in the line.

Would include a screenshot but the output has too much personal data.

`Set-CsCallQueue -Identity 456 -Name "myCallQueue" -Users "987"`

> 
TenantId                                             : 123
Name                                                 : myCallQueue
Identity                                             : 456
RoutingMethod                                        : Serial
DistributionLists                                    : 
Users                                                : 987                                                  
DistributionListsLastExpanded                        : 2023-05-28 4:13:11 PM +00:00
Agents                                               : 333, OptIn
AllowOptOut                                          : False
ConferenceMode                                       : True
PresenceBasedRouting                                 : False
AgentsCapped                                         : False
AgentsInSyncWithDistributionLists                    : False
AgentAlertTime                                       : 45
LanguageId                                           : en-US
OverflowThreshold                                    : 200
OverflowAction                                       : Forward
OverflowActionTarget                                 : letsgobrandon
OverflowSharedVoicemailTextToSpeechPrompt            : 

Thank you

**Comment by get-itips** [comment]
Hello @aphutter how are you?
Here we are limited to documentation changes and fixes.
Is there any part of the documentation that you think needs a fix? Otherwise the best would be to open a support request from your tenant. 
Thank you
