### ISSUE TITLE
Can you put in some documentation on how this can be worked on SubSites?

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/office-docs-powershell#1089]
Is it possible to use this information on subsites in a site collection?
will this command give superset of users in all sites under site collection or will only look at the parent site level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2412565f-011a-5665-7c3b-e3fe4eae0ee2
* Version Independent ID: 30fda315-30f6-09e0-342c-63940e05208b
* Content: [Get-SPOUser (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spouser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUser.md)
* Service: **sharepoint-powershell**
* Product: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
Users and Groups are always 'stored' at the Site Collection level, even if via the UI they only appear in a subweb. So if you have a SharePoint Group at /sites/mysite/subweb1, you will always query /site/mysite as that is where the group actually resides.

**Comment by Techwriter40** [comment]
@mganeshphani, did Trevor answer your question?

**Comment by mganeshphani** [comment]
@tseward Agreed that users and Groups are stored at site collection level.. however if I don't inherit the permissions from parent site and add additional users at subsite level.. how can I correlate the user to subsite? can you guide me on this, please?

**Comment by AndreaBarr** [comment]
@mganeshphani Thank you for this feedback

It seems like Trevor answered your first question but not the follow up question you had so I am going to get this into the backlog for the PowerShell Team so we can get you the answers you need. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @mganeshphani thanks for your comments, as @tseward said users and groups are stored at SC level, I confirm you can not use Get-SPOUser to retrieve the list of users in a subsite. I think you need to explore other possibilities like CSOM. Hope this info guides you in the right direction.
@yogkumgit I think we can close this now.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @mganeshphani  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
