### ISSUE TITLE
Security & Compliance Powershell: Set-DlpComplianceRule -ExceptIfRecipientDomainIs not working any more

### ISSUE THREAD

**Issue by lexios** [MicrosoftDocs/office-docs-powershell#10900]
The commands to modify a rule's Exception Domains stopped working a while back.

The below always comes back empty.

```
Get-DlpComplianceRule -Identity "DLPRULE" | fl ExceptIfRecipientDomainIs

ExceptIfRecipientDomainIs : {]
```

If we try to add a domain there we get no error as per below.

```
Set-DlpComplianceRule -Identity "DLPRULE" -ExceptIfRecipientDomainIs somedomain.com
WARNING: BlockAccessScope is configured 'PerUser', however policy has no Sharepoint or One Drive For Business workloads. The action will behave same as 'BlockAccess $true' in Exchange.
```

But then, when we Get-DlpComplianceRule, it is still empty.

```
Get-DlpComplianceRule -Identity "DLPRULE" | fl ExceptIfRecipientDomainIs

ExceptIfRecipientDomainIs : {]
```

So, there is no way for us to maintain the list of domains anymore.
This was working fine until it broke down a couple of weeks ago.

Possibly, other settings of the same cmdlets have also stopped working.

**Comment by chrisda** [comment]
@lexios, you should open a support ticket. Report back here with any information that can help improve the documentation.
