### ISSUE TITLE
ExceptIfRecipientDomainIs is not working any more in DlpComplianceRule cmdlets

### ISSUE THREAD

**Issue by lexios** [MicrosoftDocs/office-docs-powershell#10903]
The ExceptIfRecipientDomainIs does not work anymore. Possibly other attributes do not work anymore.
If you try on a test tenant you will see that those attributes are not updated via the UI or via Powershell.
Are they still in use?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c915e0e-3b66-4c89-f371-c9e1cb5ea498
* Version Independent ID: d8a07eb3-3290-1b91-490a-e2ab8990e5b1
* Content: [Set-DlpComplianceRule (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-dlpcompliancerule?view=exchange-ps#-exceptifrecipientdomainis)
* Content Source: [exchange/exchange-ps/exchange/Set-DlpComplianceRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-DlpComplianceRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@lexios, out of curiosity, are you having this issue in relation to also using the AdvandedRule parameter? I'm told that other parameters don't work if you're also using the AdvancedRule parameter

**Comment by yogkumgit** [comment]
@lexios Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
