### ISSUE TITLE
"Expired or Invalid pagination request. Default Expiry time is 00:30:00" Error when returning 1000 or more entries with Get-User - Exchange Online Powershell V3 with Certificate Based Authentication

### ISSUE THREAD

**Issue by SHaofanlv** [MicrosoftDocs/office-docs-powershell#10907]
After upgrading to EXO v3.1.0， When I use certificate-based authentication for Exchange Online and the Get-User command ($UserList = Get-User -ResultSize unlimited) returns over 1000 users, I get the below error every time:

"Expired or Invalid pagination request. Default Expiry time is 00:30:00"

Newer commands, like Get-ExoMailbox, work fine regardless of the number of users/objects.

 

Is this a expected change in V3 module? How can I avoid this error when running Get-User? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module and V3 module](https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SHaofanlv, the intent of the \*-ExO* cmdlets like Get-EXOUser is to work better/faster/more efficiently with a large number of objects. That being said, there are a couple of things you can try:

- Are you connecting in remote PowerShell mode (using the _UseRPSSession_ switch in the Connect-ExchangeOnline command) or REST API mode (not using the _UseRPSSession_ switch)? Whichever method you're using, try the other to see if it helps.
- Consider upgrading to the latest Preview version of the module (currently, v3.2.0-Preview4) to see if that helps.

If neither of those suggestions work, you can open a support ticket (provided you're using v3.1.0; they won't help you if you're using a Preview version). Or, if you want to stick with the Preview version of the module, you can ask at `exocmdletpreview[at]service[dot]microsoft[dot]com`.

**Comment by grahamr975** [comment]
@chrisda

I hope you're doing well.

This error is specific to v3.1.0 when using REST API certificate authentication. We're trying to get away from RPS mode since it's depreciating at the end of June.

The -ExO commands work fine, but not every command has an ExO version, such as Get-User or Get-Contact. Attempting to return 1000+ objects with one of the non ExO command types results in the "Expired or Invalid pagination request. Default Expiry time is 00:30:00" error.

**Comment by JeremyTBradshaw** [comment]
Hi all, just want to let you know that I too experience this problem and am going to raise it with the EXO cmdlet preview feedback email.  If they have anything to help I'll share.  It's certainly a common new issue which seems like a MAJOR step backwards all of a sudden.  All my bigger tenants running scripts to report on all mailboxes are encountering this.  REST-backed original Cmdlets did NOT get the same TLC as those special 9-10 ***-EXO*** cmdlets.

**Comment by grahamr975** [comment]
@JeremyTBradshaw I agree with your concerns. As a heads up, I was able to get around the expired pagination bug in my own script by removing the "-ConnectionUri" parameter when I call "Connect-ExchangeOnline". I'd give that a try to see if it works for you. I've also heard that tenets had better luck when using their ".onmicrosoft.com" domain name for the "-Organization" parameter.

**Comment by JeremyTBradshaw** [comment]
@grahamr975 thanks for the advice.  Here's how I'm connecting in my script (calling connectEXO from elsewhere in the same script:
```powershell
function connectEXO {
    try {
        $connectEXOParams = @{

            AppId         = $Script:mgTokenParams['ApplicationId']
            Organization  = $Script:mgTokenParams['TenantId']
            Certificate   = Get-ChildItem $Script:mgTokenParams['CertificateStorePath']
            CommandName   = @('Get-Mailbox', 'Get-MailboxStatistics')
            ShowBanner    = $false
            ShowProgress  = $false
            WarningAction = 'SilentlyContinue'
            ErrorAction   = 'Stop'
        }
        Connect-ExchangeOnline @connectEXOParams
    }
    catch {
        sendFailureNotification -Message 'Failed on Connect-ExchangeOnline.' -ErrorRecord $_ -PassThru |
        writeLog @writeLogParams -PassThru | Write-Warning
        disconnectEXO
        throw
    }
}
```

The value in TenantId is actually already using the onmicrosoft.com domain for -Organization.
```powershell
@{
    aad   = @{

        TokenParams            = @{

            ApplicationId        = 'fcd470f0-9e9f-4271-9a68-c341c2c1cc1d'
            TenantId             = '_hidden_.onmicrosoft.com' #<--: Using FQDN instead of Guid so we can also use this with Connect-ExchangeOnline's -Organization parameter.
            CertificateStorePath = 'Cert:\CurrentUser\My\123109FEA040C3E83B9DE443FFA3B74C1FF2B6B3'
```

But it's good to hear people are reporting improvements through this kind of tinkering which gives me something to work with while waiting for solutions.

**Comment by chrisda** [comment]
If you're using a Preview version of the module, support won't help you. That's where `exocmdletpreview[at]service[dot]microsoft[dot]com` is your only recourse.

If you're using a GA version of the module, support should help you. Help is a relative term in that they almost certainly can't fix the problem right then and there. What they can do (and this is the important part) is pass the problem on to the product team that owns the module, where they can diagnose/validate/test and possibly fix the problem in a future version of the module.

Getting the 'this doesn't work right' information to the product team is important.
