### ISSUE TITLE
Connect-ExchangeOnline with accessToken is not working from a 21vianet tenant.

### ISSUE THREAD

**Issue by qquiuc** [MicrosoftDocs/office-docs-powershell#10908]
Hi  Team
We are using a exchange powershell to manage sharepoint online, we are trying to connect to the exchange online powershell with a access token that we get from the application created in our own tenant, but it fails to connect, with error 401.
![test](https://github.com/MicrosoftDocs/office-docs-powershell/assets/18695819/72dfee55-0054-460c-914c-d1ae5395b9cb)
![WXWorkCapture_16856769096677](https://github.com/MicrosoftDocs/office-docs-powershell/assets/18695819/63f29cc9-80ed-4001-af1b-666bfcc2b232)
Please help to confirm which permission we need to connect to exchange online powershell in 21vianet?

**Comment by chrisda** [comment]
Checking

**Comment by qquiuc** [comment]
Hi  Team,
Any update on this?
Thanks

**Comment by chrisda** [comment]
@qquiuc, you should open a support ticket about this. Report back here with any information that can help improve the documentation.

**Comment by qquiuc** [comment]
We do have opened a ticket for the MS support, but we didn't got any useful information.
Ticket NO: SR_20230602233531

**Comment by yogkumgit** [comment]
@qquiuc Please follow up with support. We proceed to close it as here we are limited to documentation fixes and improvements only. Thank you.
