### ISSUE TITLE
Descriptions for SkipDomainValidationForXXX missing

### ISSUE THREAD

**Issue by New-Authentication** [MicrosoftDocs/office-docs-powershell#10916]
For parameters
-SkipDomainValidationForMailContact
-SkipDomainValidationForMailUser
-SkipDomainValidationForSharedMailbox

The description is just:
{{ Fill SkipDomainValidationForMailContact Description }}
{{ Fill SkipDomainValidationForMailUser Description }}
{{ Fill SkipDomainValidationForSharedMailbox Description }}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0de94ad-58e2-3ba9-e854-8acd7591fb2c
* Version Independent ID: 691f3292-81aa-6367-8b67-bf37aef2deb5
* Content: [Remove-RecipientPermission (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/remove-recipientpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-RecipientPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Remove-RecipientPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@New-Authentication, empty parameter descriptions are a known commodity. Availability vs. functionality are two different things. You can read more about it [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).

Are you being directed to use these parameters in other content?

**Comment by New-Authentication** [comment]
@chrisda Thank you for your reply. I'm currently troubleshooting a problem with the Remove-RecipientPermission and these three parameters could possible do what I need, but I really don't know what they're doing. I have not been directed to use them - their names just look interesting.

**Comment by New-Authentication** [comment]
@chrisda Thank you for that. And in the mean time I solved my issue (user error). Closing.
