### ISSUE TITLE
PQMT: [Exchange] The parameter description on the "New-MigrationEndpoint" document page states "{{Fill (parameter name) Description }}"

### ISSUE THREAD

**Issue by v-mshimbo** [MicrosoftDocs/office-docs-powershell#10936]
[Document URL]
https://learn.microsoft.com/en-us/powershell/module/exchange/new-migrationendpoint?view=exchange-ps

[Description]
The parameter description on the "New-MigrationEndpoint" document page states "{{Fill (parameter name) Description }}".
The following parameter description says "{{ Fill (parameter name) Description }}".
-AcceptUntrustedCertificates
-ApplicationId
-AppSecretKeyVaultUrl
-RemoteTenant
If this statement is not necessary, please delete it.

[Actual result]
The following parameter description says "{{ Fill (parameter name) Description }}".
-AcceptUntrustedCertificates
-ApplicationId
-AppSecretKeyVaultUrl
-RemoteTenant

[Expected result]
Delete the parameter description of "{{ Fill (Parameter Name) Description }}" if it is unnecessary.
Or, if the text needs to be replaced, replace it correctly.

[Source] 
Japan Internal Feedback 

[Copied from]
https://microsoftapc.sharepoint.com/:li:/t/NTO-Japan/E9YoS9Ky0_RElpFViECKLcUBius696eI1sLOklPlGb1l_w?e=gPe3oc
![20230607RING](https://github.com/MicrosoftDocs/office-docs-powershell/assets/136293932/e9aa6cd5-205c-4309-87cc-e6512a6ee280)

**Comment by chrisda** [comment]
@v-mshimbo, empty parameter descriptions are a known commodity. Availability vs. functionality are two different things. You can read more about it [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).

Are you being directed to use these parameters in other content?

**Comment by v-mshimbo** [comment]
@chrisda, I have read the contents of [this link](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).
I understood that undocumented parameters are marked {{Fill (parameter name) Description}}. I just don't think the issue has been resolved.
Is it possible to omit the {{Fill (parameter name) Description}} if there is no description that should be included?
If you don't know what {{Fill (parameter name) Description}} indicates, you may think it is an omission in the documentation or something.

"Are you being directed to use these parameters in other content?"
-> Sorry. What exactly do you mean by "other content"? Thanks.

**Comment by yogkumgit** [comment]
@v-mshimbo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
