### ISSUE TITLE
Set-CsTeamsCallingPolicy -AllowCallRedirect

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10933]
Description of `-AllowCallRedirect` parameter is very unclear.
Could you please update to be more specific?

E.g.

> Setting this parameter provides the ability to configure call redirection capabilities on Teams phones.

What exactly is *redirection capabilities*? Is it the ability to set call forwarding & simultaneous ring settings? Or it is about call transfer?

What is "Teams phones"? [Configure SIP Gateway](https://learn.microsoft.com/microsoftteams/sip-gateway-configure#sync-policy-changes-to-sip-devices-to-enforce-policies) article says it is mandatory to enable this setting for **SIP phones** to work. Does it also applicable to Teams Android phones? What about MTRoW / MTRoA / SurfaceHub?

> When set to Enabled users will have the ability to redirect received calls. However, when set to Disabled the user will not have such ability.

These two sentences just waste readers' time to state the obvious (that "AllowCallRedirect" will "allow to redirect call"). It should have explained instead the difference between "AllowCallRedirect" and "AllowCallForwarding" (sounds remarkably similar)

> There's no UX implemented for its management

Considering that UX = User Experience, this sentence is very confusing. Is it trying to say that it is not visible to **admins** in TAC GUI?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8fa7e55-c3b1-7b37-f395-736ec82868a0
* Version Independent ID: 4630697b-375e-85f2-25b1-b944bc6dad5f
* Content: [Set-CsTeamsCallingPolicy (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@shivtorov Thanks for your feedback. I'll have a look and update. Feel free to close this issue.

**Comment by shivtorov** [comment]
@JensTrier Thank you for updating the article.
I checked the new description in your PR.
However, it is still not exactly clear to me what to expect when I change this parameter to Enabled/Disabled.

For example, today I have:

- AllowCallRedirect = Disabled in all existing policies.
- On Teams IP Phones (Poly CCX series handsets) that have SignInMode = UserSignIn policy applied, users **do** have access to menu item that allows to change call forwarding settings
- On Teams IP Phones (Poly CCX series handsets) that have SignInMode = CommonAreaPhoneSignIn or SignInMode = MeetingSignIn policy applied, users do **not** have access to menu item that allows to change call forwarding settings

Should I expect that this parameter to show/hide the menu item for call forwarding on phones with CommonAreaPhoneSignIn  only?

**Comment by JensTrier** [comment]
@shivtorov I still plan to make changes to the parameter description. Please stay tuned.

**Comment by JensTrier** [comment]
@shivtorov Setting the parameter has currently no function. I'm marking the parameter for internal Microsoft use only.

**Comment by shivtorov** [comment]
@JensTrier, thank you for clarification

pls also update [sip-gateway-configure](https://learn.microsoft.com/en-au/microsoftteams/sip-gateway-configure#sync-policy-changes-to-sip-devices-to-enforce-policies) article that refers to this cmdlet

**Comment by JensTrier** [comment]
The parameter description has been updated in PR #11023 to reflect usage by SIP Device Gateway.

**Comment by yogkumgit** [comment]
@JensTrier Thank you very much for the contribution and updating the documentation with PR. @shivtorov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
