### ISSUE TITLE
Call from script?

### ISSUE THREAD

**Issue by bkemp-bocomo** [MicrosoftDocs/office-docs-powershell#1093]
how can you call the module from a script? I noticed once installed I can run a powershell and import-module to get the connect-exopssession command. I have several scripts that I user this to generate my connection:

$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.outlook.com/powershell -Credential $O365Cred -Authentication Basic -AllowRedirection
                Import-PSSession $Session
                Set-Location 'S:\Network Administration\Office365 Powershell'
                .\office365.ps1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* Product: **unspecified**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mwucbs** [comment]
Sadly you can't connect with  $cred inside script, when you have enabled MFA.
You must type user/pass everytime, witch is a major drawback for administrators.
I'd like MS to make this more easy.

regarding your quiestion you can import the exo modul in your script with this:

Import-Module $((Get-ChildItem -Path $($env:LOCALAPPDATA + "\Apps\2.0\") -Filter Microsoft.Exchange.Management.ExoPowershellModule.dll -Recurse).FullName | ?{ $_ -notmatch "_none_" } | select -First 1)
#		$EXOSession = New-ExoPSSession -UserPrincipalName $UPN
#		Import-PSSession $EXOSession -AllowClobber
