### ISSUE TITLE
Connect-IPPSSession still opening a login prompt v3.1.0

### ISSUE THREAD

**Issue by jaya1971** [MicrosoftDocs/office-docs-powershell#10945]
I am trying to use CBA with a thumbprint.  Doesn't matter if I use Windows PowerShell 5.1 or PowerShell Core 7.3.4, I am prompted with a login prompt.  I've tried using the "$Global:IsWindows = $true" variable but it still persists in both.  I have no issues using the Connect-ExchangeOnline authentication method.

I need this to work with unattended automations and up until recently, we've been using basic auth but we would like to move away from it.

Connect-IPPSSession -AppId $clientid -CertificateThumbprint $thumbprint -Organization $org

Any ideas?

**Comment by chrisda** [comment]
@jaya1971, I presume you meant v3.1.0, so I corrected the title.

Try using the latest Preview version of the module (v3.2.0-Preview4) to see if that helps. That version also contains the UseRPSSession switch on the Connect-IPPSSession cmdlet so you can try remote PowerShell vs. REST API mode to see if that helps.

**Comment by jaya1971** [comment]
@chrisda,
Thank you for the title change.  I will try using the new version but RPS isn't an option.  We were using RPS with basic auth but we're moving away from that and using the more secure option with the REST API.  Also, as I understand, the RPS will be deprecated as of 7/1/23, unless I misread.  

As of now, the workaround is to connect to exchangeonline first, then connect to ippssession using the certificate file, rather than the thumbprint.
