### ISSUE TITLE
Provide a value to accept SiteId as input

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/office-docs-powershell#1094]
I wanted to delete some redundant hubsite entries in my tenant.. however I am not able to do so, because this was only accepting SiteURL.. rather than SiteId or HubSiteId.. had to go through back channel to address this scenario for now.. but if the commandlet accepts the SiteId, then it would be helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6174c55-f04d-107b-c343-af74ae3e254b
* Version Independent ID: 8e82c555-eafe-ce07-e27f-74b943d96c7e
* Content: [Unregister-SPOHubSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/unregister-spohubsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Unregister-SPOHubSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Unregister-SPOHubSite.md)
* Service: **sharepoint-powershell**
* Product: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by mganeshphani** [comment]
![image](https://user-images.githubusercontent.com/22988320/40455696-c3e56ce8-5eb3-11e8-880e-832dbb07f368.png)

**Comment by mganeshphani** [comment]
Please see Office support ticket: 10315684 
if you need snapshot of the scenario

**Comment by hrfmjp** [comment]
I can delete Hub Site by using latest SPO Management Shell(16.0.7625.1200): Unregister-SPOHubSite <SiteId>

**Comment by AndreaBarr** [comment]
@mganeshphani Thank you for this feedback

I want to make sure you are able to delete that duplicate HubSite's Id. Support can handle this to resolution.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
