### ISSUE TITLE
Add an export-clixml example.

### ISSUE THREAD

**Issue by jprknight** [MicrosoftDocs/office-docs-powershell#10954]
In Microsoft support we ask customers to run this all the time to import into MRSExplorer.ps1 and analyse the migration batch / user, please add this example.

```powershell
Get-MoveRequestStatistics tony@contoso.com -IncludeReport -DiagnosticInfo verbose | Export-CliXml MoveReport.xml
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b058d48-3c1e-bcb6-4070-00b144ddc03d
* Version Independent ID: c37947e6-2308-0c18-34ba-25d82f71e2ec
* Content: [Get-MoveRequestStatistics (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-moverequeststatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MoveRequestStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-MoveRequestStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jprknight, I added your suggestion as example 6 in the Get-MoveRequestStatistics topic. Feel free to make any changes.

In the future, you too can make changes like this directly. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
