### ISSUE TITLE
Grant-CsTenantDialPlan -WhatIf/-Confirm not implemented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10962]
pls update the article with a warning that `-WhatIf` / `-Confirm` parameters are not implemented (bug).

---
general feedback (@isrumnon):

1. it is a common problem with multiple "new/refreshed" cmdlets in the module - they declare SupportsShouldProcess in the CmdletBinding, but not actually implementing it.
2. many new/refreshed cmdlets don't properly support pipeline.
e.g.:
- we can't run `Get-CsOnlineUser -Filter "xxx" | Set-CsPhoneNumberAssignment -EnterpriseVoiceEnabled $true`, thus have to use workarounds like `Get-CsOnlineUser -Filter "xxx" | foreach-object { Set-CsPhoneNumberAssignment -EnterpriseVoiceEnabled $true -Identity $_.Identity }`
- at least some `Grant-Cs` cmdlets fails on empty pipeline. for example `Get-CsOnlineUser -Filter "xxx" | Grant-CsTenantDialPlan -PolicyName REDMOND` throwing errors in case of empty pipeline

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb40b45f-5982-fcca-66fa-8fa03f723648
* Version Independent ID: 72abb3bd-b9d5-6b10-04f7-d46f3bd49688
* Content: [Grant-CsTenantDialPlan (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/grant-cstenantdialplan?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsTenantDialPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Grant-CsTenantDialPlan.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by get-itips** [comment]
Thanks for your feedback @shivtorov
