### ISSUE TITLE
Get-ActivityExplorerData Filter by Policy Name / Rule Name

### ISSUE THREAD

**Issue by ricov98** [MicrosoftDocs/office-docs-powershell#10966]
Hi,

With the action Export-ActivityExplorerData in https://learn.microsoft.com/powershell/module/exchange/export-activityexplorerdata

Is it possible to filter by policy name / the rule name / the sensitive information type like in https://learn.microsoft.com/powershell/module/exchange/get-dlpsidetectionsreport

And is there any command that I can use to export all the data from the Content Explorer instead of the Activity Explorer?

Thank you.

**Comment by chrisda** [comment]
@ricov98, you should open a support ticket and ask. Report back here with any information that can help improve documentation.
