### ISSUE TITLE
Top/Skip parameter issues

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10964]
Using versions 5.2.0 and 5.3.0 of the MicrosoftTeams Powershell Module, I'm seeing issues when I issue the -Skip parameter during execution

Because we don't have a lot of test data, in order to test this feature for our clients who have tens of thousands of phone numbers, I use a small Top and Skip value.  Without submitting these parameters I get a list of 80 or so phone numbers

PS D:\Docs\PS\SFBO> Get-CsPhoneNumberAssignment | Select TelephoneNumber

TelephoneNumber
---------------
+14175554108
+14705795060
+15050098815
+15050098822
+15555552345
+15555553600;ext=3613
+15594928985
+15595003808
+15632314330
+16042368956
+16086659337
+16122043627;ext=33
+16122043678
...

Then when I start getting this list in small batches (testing), the Skip statement stops working after the 4th submission

PS D:\Docs\PS\SFBO> Get-CsPhoneNumberAssignment -Top 1 | Select TelephoneNumber

TelephoneNumber
---------------
+14175554108

PS D:\Docs\PS\SFBO> Get-CsPhoneNumberAssignment -Top 1 -Skip 1 | Select TelephoneNumber

TelephoneNumber
---------------
+14705795060

PS D:\Docs\PS\SFBO> Get-CsPhoneNumberAssignment -Top 1 -Skip 2 | Select TelephoneNumber

TelephoneNumber
---------------
+15050098815

PS D:\Docs\PS\SFBO> Get-CsPhoneNumberAssignment -Top 1 -Skip 3 | Select TelephoneNumber

TelephoneNumber
---------------
+15050098822

PS D:\Docs\PS\SFBO> Get-CsPhoneNumberAssignment -Top 1 -Skip 4 | Select TelephoneNumber
PS D:\Docs\PS\SFBO>

If I attempt to get the list 2 at a time, -Top 2 -Skip 4 returns only 1 value instead of 2

PS D:\Docs\PS\SFBO> Get-CsPhoneNumberAssignment -Top 2 | Select TelephoneNumber

TelephoneNumber
---------------
+14175554108
+14705795060

PS D:\Docs\PS\SFBO> Get-CsPhoneNumberAssignment -Top 2 -Skip 2 | Select TelephoneNumber

TelephoneNumber
---------------
+15050098815
+15050098822

PS D:\Docs\PS\SFBO> Get-CsPhoneNumberAssignment -Top 2 -Skip 4 | Select TelephoneNumber

TelephoneNumber
---------------
+15555552345

PS D:\Docs\PS\SFBO> Get-CsPhoneNumberAssignment -Top 2 -Skip 6 | Select TelephoneNumber

TelephoneNumber
---------------
+15555553600;ext=3613
+15594928985

PS D:\Docs\PS\SFBO> Get-CsPhoneNumberAssignment -Top 2 -Skip 8 | Select TelephoneNumber

TelephoneNumber
---------------
+15595003808
+15632314330

I'd hate to release our software to our clients attempting to get 500 phone numbers at a shot, only to find out we didn't get the entire list

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bfb9351-75be-abb8-c8ac-bf08f51d08a1
* Version Independent ID: c7925810-6411-9371-7a04-fc28a4c827ec
* Content: [Get-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
Documentation for using both Top & Skip added in PR #11023. Actual issue when using both is being investigated.

**Comment by yogkumgit** [comment]
@JensTrier Thank you very much for the contribution and updating the documentation with PR. @sarollins Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by JensTrier** [comment]
@sarollins fyi, the issue with using Top and Skip at the same time should have been fixed and I can't repro it anymore. Thanks for reporting this!
