### ISSUE TITLE
Error ExchangeOnlineManagement v3.2.0 Get-EXOMailbox returns Error 500

### ISSUE THREAD

**Issue by asterictnl-lvdw** [MicrosoftDocs/office-docs-powershell#10972]
I get the following error on the newly installed ExchangeOnlineManagement PowerShell v3.2.0 cmdlet:

```
Get-EXOMailbox : Error while querying REST service. HttpStatusCode=500 ErrorMessage={"error":{"code":"InternalServerErr
or","message":"The call to Microsoft Exchange Active Directory Topology service on server 'TopologyClientTcpEndpoint (l
ocalhost)' returned an error. Error details Active Directory server  is not available. Error message: Active directory
response: The LDAP server is unavailable..","innererror":{"message":"The call to Microsoft Exchange Active Directory To
pology service on server 'TopologyClientTcpEndpoint (localhost)' returned an error. Error details Active Directory serv
er  is not available. Error message: Active directory response: The LDAP server is unavailable..","type":"Microsoft.Exc
hange.Data.Directory.ADTransientException"}}}}
```

Specifications:
```
Windows Version: Windows 11 Version 23H2 OS Build 25393.1
Cmdlet Version: 3.2.0 [latest]
Cmdlet Version Working: 3.1.0
PowerShell: 5.1
Problems with Command: Get-EXOMailbox
```

Is it an issue with the cmdlet? This seems to be an issue with the REST service as it is resulting into a 500 error which could not be on my side. We have the Exchange in our Microsoft 365 environment so no on-premise environment.

~LvdW

**Comment by chrisda** [comment]
@asterictnl-lvdw, you should open a support ticket about this. I just upgraded to v3.2.0 and it works fine in my Microsoft 365 E5 tenant.

**Comment by asterictnl-lvdw** [comment]
@chrisda When you manually login with connect and the ipps it works. But if you have it in a script it doesn't work. I shall put a reproduction script in the next reply.

**Comment by asterictnl-lvdw** [comment]
Please save this as a .ps1 file and run it as you normally should:

```
$Username = 'example@contoso.com' #Change the Username here
# In the new version IPPSSession can hide the banner now as well as a Banner shows up at the moment!
Connect-ExchangeOnline -UserPrincipalName $Username -ShowBanner:$false
Connect-IPPSSession -UserPrincipalName $Username -ShowBanner:$false
#When executing one or both it might already give an error about an instance object, unknown why that happens.
		$ExchangeSetting = Get-SharingPolicy | Where-Object { $_.Domains -like '*CalendarSharing*' }
		$affectedmailboxes = @()
		$mailboxes = Get-EXOMailbox -ResultSize Unlimited  #Here is where the timeout should occur
		foreach ($mailbox in $mailboxes)
		{
			# Get the name of the default calendar folder (depends on the mailbox's language) 
			$calendarFolder = [string](Get-ExoMailboxFolderStatistics $mailbox.PrimarySmtpAddress -FolderScope Calendar | Where-Object { $_.FolderType -eq 'Calendar' }).Name
			# Get users calendar folder settings for their default Calendar folder # calendar has the format identity:\<calendar folder name> 
			$calendar = Get-MailboxCalendarFolder -Identity "$($mailbox.PrimarySmtpAddress):\$calendarFolder"
			if ($calendar.PublishEnabled)
			{
				Write-Warning "Calendar publishing is enabled for $($mailbox.PrimarySmtpAddress) on $($calendar.PublishedCalendarUrl)"
				$affectedmailboxes += "Calendar publishing is enabled for $($mailbox.PrimarySmtpAddress) on $($calendar.PublishedCalendarUrl)"
			}
		}
```
@chrisda 

Could you confirm you get NO errors if you run this in a .ps1 script.

Please let me know.

~LvdW

**Comment by asterictnl-lvdw** [comment]
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/99249102/a92e6c45-9bfe-407b-8b8f-feb7f520bd30)
@chrisda 

Also here the prove of pasting this above script into a new .ps1 file and run it from the command line.

**Comment by chrisda** [comment]
@asterictnl-lvdw, I ran your script and got the timeout error.

I see your script is connecting to ExO PowerShell and S&C PowerShell at the same time. There was [another issue about this](https://github.com/MicrosoftDocs/office-docs-powershell/issues/10952) that was never resolved.

When I used your script to connect to ExO PowerShell only, I didn't get the timeout error. It found a user where calendar sharing was enabled, but the script never seemed to end (I had to CTRL+C to get out of it).

Now that v3.2.0 is Generally Available (GA), you can and should open a support ticket about this issue, which seems to be more about connecting to ExO and S&C PowerShell in the same session.

**Comment by asterictnl-lvdw** [comment]
@chrisda it's a pity that Microsoft doesn't take this issue seriously and it seems to only happen in version 3.2.x since they changed something about the authentication schema. I will send the data to the email address which is in the other issue and keep this issue updated.

To be continued...

**Comment by tinojr** [comment]
This same issue happens to me on two separate computers. It only happens when I connect to EXO and Compliance PowerShell in the same console session. This just started happening last week, and I've had EXO V3.2 installed for three weeks.

**Comment by joturney** [comment]
Try running the Connect-IPPSSession first and then the Connect-ExchangeOnline if you need both connections. It looks like the Connect-IPPSSession cmdlet clobbers something in the ExchangeOnline connection if run in the opposite order ¯\_(ツ)_/¯
```
Connect-IPPSSession -UserPrincipalName $Username -ShowBanner:$false -Verbose
Connect-ExchangeOnline -UserPrincipalName $Username -ShowBanner:$false -Verbose
Disconnect-ExchangeOnline -Confirm:$false
```
