### ISSUE TITLE
-NotificationGroup description is confusing, implying email notifications will be sent

### ISSUE THREAD

**Issue by jim-dickinson** [MicrosoftDocs/office-docs-powershell#10975]
Hi! Per any and all descriptions for this property it is suggestive that notifications will be send via email to members of the list. Our testing indicates that only an "important" teams message is sent in a group chat to members of the list. There doesn't even seem to be a way to set this to "urgent" so that Teams will also then send an email of the Urgent message...so even with that creative attempt no email is being sent out.

Would you mind updating the verbiage to be clear that the notification only goes out via Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 600b453c-8a25-4c1d-3ccc-8ad9070c84fd
* Version Independent ID: afcaa2cc-3505-f358-a15e-f970ddac33f9
* Content: [Set-CsTeamsEmergencyCallingPolicy (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csteamsemergencycallingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@jim-dickinson Thanks for the feedback. I'll update the text to make it clear it happens via Teams chat.

**Comment by yogkumgit** [comment]
@JensTrier Thank you very much for the contribution and updating the documentation with PR. @jim-dickinson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
