### ISSUE TITLE
New-AddressList in Exchange Online

### ISSUE THREAD

**Issue by mikelabca** [MicrosoftDocs/office-docs-powershell#10982]
Hello,

Documentation says New-AddressList is supported for Exchange Online, but I believe its no longer supported.

Can this doc be updated if this is correct ?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60c54a88-3f74-3e5c-a7fc-ecee2b49e81c
* Version Independent ID: 0b2ef8ba-662b-48b8-7c06-6ff38e086ab9
* Content: [New-AddressList (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-addresslist?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-AddressList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-AddressList.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mikelabca, New-AddressList is definitely *available* in Exchange Online. As described in the article, you need the Address Lists role to see it.

I'll be the first to admit that availability doesn't necessarily mean functionality. Do you have a link to a blog post or other announcement that talks about Address List creation going away in Exchange Online?

**Comment by yogkumgit** [comment]
@mikelabca Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
