### ISSUE TITLE
Make Sharepoint online management shell module Installable like AzureRM

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/office-docs-powershell#1098]
Currently users have to download and install the binaries to make use of SPO commands... why don't you make it uniform as AzureRM/SharepointPNPOnline, which is downloadable on the fly from scripts using Install-Module and side-side installation

**Comment by kenwith** [comment]
I will defer to @Techwriter40 and @VesaJuvonen but I believe this has to do with how SharePoint (and Exchange - see https://github.com/MicrosoftDocs/office-docs-powershell/issues/1085#issuecomment-391791976) though I am not positive SharePoint uses remoting as @chrisda replied but I know SharePoint uses snap-ins and not modules (though this could likely change in future and I know there have been conversations about it).

**Comment by Techwriter40** [comment]
@VesaJuvonen I will defer to Vesa for final decision.

**Comment by AndreaBarr** [comment]
@mganeshphani Thank you for this feedback. 

I found a uservoice sugestoin for this and have upvoted for it. The uservoice url is https://sharepoint.uservoice.com/forums/330318-sharepoint-administration/suggestions/13660995-add-sharepoint-powershell-module-to-azure-gallery.

I know the product teams are always looking for user feedback and how to make the OneDrive / SharePoint better. They keep a close tab on User Voice [https://sharepoint.uservoice.com](https://sharepoint.uservoice.com) and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too. 
 
Thank you for your contribution to make the docs better! Much appreciated!
