### ISSUE TITLE
[teams] New-CsTeamsNdiAssuranceSlate is not documented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10997]
It appears that New-CsTeamsNdiAssuranceSlate is not documented despite being referenced in [Microsoft Teams PowerShell Release Notes](https://learn.microsoft.com/microsoftteams/teams-powershell-release-notes) article

**Comment by get-itips** [comment]
Hello @shivtorov 
I could get the information that the team expects to document this cmdlet in the near future and I was instructed to close this for the moment.
Thank you
