### ISSUE TITLE
[teams] [Get|Set|New|Remove|Grant]-CsOnlineAudioConferencingRoutingPolicy are not documented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10992]
It appears that [Get|Set|New|Remove|Grant]-CsOnlineAudioConferencingRoutingPolicy are not documented despite being referenced in [On-network Conferencing for Audio Conferencing](https://learn.microsoft.com/microsoftteams/audio-conferencing-on-network) article

**Comment by get-itips** [comment]
Hello @shivtorov 
I could get the information that the team expects to document those cmdlets in the near future and I was instructed to close this for the moment.
Thank you
