### ISSUE TITLE
[teams] [Get|Set|New|Remove|Grant]-CsTeamsVdiPolicy are not documented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10994]
It appears that [Get|Set|New|Remove|Grant]-CsTeamsVdiPolicy are not documented despite being referenced in [Teams for Virtualized Desktop Infrastructure](https://learn.microsoft.com/microsoftteams/teams-for-vdi#disable-audio-and-video-settings-for-vdi) article

**Comment by get-itips** [comment]
Hello @shivtorov I'm working on this and the other related issues you created, thank you for your feedback.

**Comment by get-itips** [comment]
Hello @shivtorov 
I could get the information that the team expects to document those cmdlets in the near future and I was instructed to close this for the moment.
Thank you
