### ISSUE TITLE
Forest is empty or null. Couldn't retrieve forest details from context header

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10990]
Using version 5.3.0 of the Teams module, when I attempt to change the DisplayName parameter, I get the error

Forest is empty or null. Couldn't retrieve forest details from context header

I've verified this isn't computer specific and when I use version 5.2.0, I get no error

I am using user tokens to connect to O365 and if I use application tokens, I get the error

Access denied

for both version 5.3.0 and 5.2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: edc6081b-f6d4-f2c3-b12e-5f4df83c31e6
* Version Independent ID: 5cf5edef-643f-10a1-8247-4e14d06ff675
* Content: [Set-CsOnlineApplicationInstance (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csonlineapplicationinstance?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@sarollins Thanks for the feedback. The issue with forest is empty or null is a known issue that we are working on fixing.

**Comment by yogkumgit** [comment]
@sarollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
