### ISSUE TITLE
[teams] [Get|Set|New|Remove|Grant]-CsTeamsUpdateManagementPolicy are not documented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10993]
It appears that [Get|Set|New|Remove|Grant]-CsTeamsUpdateManagementPolicy are not documented despite being referenced in [Enable the new Microsoft Teams toggle for your organization](https://techcommunity.microsoft.com/t5/microsoft-teams-blog/enable-the-new-microsoft-teams-toggle-for-your-organization/ba-p/3781345) blog post.

**Comment by get-itips** [comment]
Hello @shivtorov I'm looking into this

**Comment by get-itips** [comment]
Hello @shivtorov 
I could get the information that the team expects to document those cmdlets in the near future and I was instructed to close this for the moment. I'll have to add the same comment to the other similar issues too.
Thank you
