### ISSUE TITLE
[teams] [Get|Set]-CsTeamsMessagingConfiguration are not documented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10995]
It appears that [teams] [Get|Set]-CsTeamsMessagingConfiguration are not documented despite being referenced in [Manage messaging policies in Teams](https://learn.microsoft.com/microsoftteams/messaging-policies-in-teams) article

**Comment by get-itips** [comment]
Hello @shivtorov 
I could get the information that the team expects to document those cmdlets in the near future and I was instructed to close this for the moment.
Thank you
