### ISSUE TITLE
what does '-IsPolicyOverrideApplied' do? it takes a [System.Boolean]

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/office-docs-powershell#10999]
this cmdlet...

Set-MalwareFilterPolicy -IsPolicyOverrideApplied

...is provided in Exchange Online Management 3.2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76492554-a89b-db9e-d68c-e706cc2babe9
* Version Independent ID: e72f7a07-bf76-0487-9c7b-fb79b2fe9c41
* Content: [Set-MalwareFilterPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-malwarefilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@anwarmahmood1, that parameter isn't useful to customers.

I added it to the article with the description:

> This parameter is reserved for internal Microsoft use.

Thanks for the feedback.

Closing
