### ISSUE TITLE
Articles for Set-CsPlatformServiceSettings / Get-CsPlatformServiceSettings are missing.

### ISSUE THREAD

**Issue by kenwith** [MicrosoftDocs/office-docs-powershell#110]
*-CsPlatformServiceSettings cmdlets are discussed here:
https://support.microsoft.com/en-us/help/4036633/we-can-t-sign-you-in-because-you-aren-t-set-up-to-use-skype-for 
https://support.microsoft.com/en-us/help/4043637/enable-skype-on-mac-to-restrict-external-access-in-skype-for-business

But there don't seem to be any cmdlet references yet. These need to be added.

**Comment by kenwith** [comment]
Just a quick update. I am working on this and also documenting the process. Since the references are all open source now anyone can do it. The tool to generate the stubbed content is called PlatyPS and it is found here: https://github.com/PowerShell/platyPS   

I will keep updating this article as I document it, NEW_CMDLETS.md, which can be found in repo_docs folder or also a link from the main README. Still working on it though.

**Comment by kenwith** [comment]
@nsshommo is working on some of these issues. This is duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/111 so closing this one out.

**Comment by nsshommo** [comment]
This issue is also discussed in the following issue:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/111
So, it can be merged with that one.
