### ISSUE TITLE
MI connection: Followed instructions but doesn't work

### ISSUE THREAD

**Issue by Videsh-Lingabavan** [MicrosoftDocs/office-docs-powershell#11008]
I've followed the instructions in the article but I still can't get my runbooks to authenticate to Exchange online using a managed identity.

Despite assigning Exchange administrator role to the managed identity whenever I try connecting with that managed identity i get:

Failed
UnAuthorized (UnAuthorized)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba626583-a2d3-00ba-6b8e-69e89e7af74c
* Version Independent ID: 4da53073-acc6-c813-8a2d-c0200f9494bf
* Content: [Use Azure managed identities to connect to Exchange Online PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/connect-exo-powershell-managed-identity?view=exchange-ps#step-3-store-the-user-assigned-managed-identity-in-a-variable)
* Content Source: [exchange/docs-conceptual/connect-exo-powershell-managed-identity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/connect-exo-powershell-managed-identity.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Videsh-Lingabavan, [this other issue](https://github.com/MicrosoftDocs/office-docs-powershell/issues/10942) talks about the need to create a new service principal.

Can you confirm or deny?

**Comment by Videsh-Lingabavan** [comment]
Hi Chris,

Thanks for replying, using a user managed identity, I tried following to Exchange online:

New-ServicePrincipal -AppId manageduserclientid -ServiceId manageduserobjectid
And
New-ServicePrincipal -AppId manageduserobjectid -ServiceId manageduserclientid

Either I get this when running on Azure with a runbook:
***@***.***
Or when running on hybrid worker:
***@***.***

Here is the powershell code I am running:
***@***.***

Many Thanks,

Videsh Lingabavan
Solutions Architect | Joseph Hage Aaronson LLP

D:  +44 (0)20 7851 8875
M: +44 (0)7809 337 321
T:  +44 (0)20 7851 8888

**Comment by yogkumgit** [comment]
@Videsh-Lingabavan Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
