### ISSUE TITLE
Switches missing descriptions. 

### ISSUE THREAD

**Issue by irideostriches** [MicrosoftDocs/office-docs-powershell#11004]
Explanations for adaptivescope, b2dumpsterarchiver and b2ipmarchive are missing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0404960d-05e8-6e6f-8063-ebed163ecefd
* Version Independent ID: d79b2d09-a176-d22e-e5ad-49a8fa22df2a
* Content: [Start-ManagedFolderAssistant (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/start-managedfolderassistant?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@irideostriches, empty parameter descriptions are a known commodity. Availability vs. functionality are two different things. You can read more about it [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).

Are you being directed to use these parameters in other content? Or are you just pointing out that they're empty?

**Comment by yogkumgit** [comment]
@irideostriches Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
