### ISSUE TITLE
Issue With Teams PowerShell Module : Get-TeamUser returns 0 values incorrectly

### ISSUE THREAD

**Issue by inseu** [MicrosoftDocs/office-docs-powershell#11002]
I am using the MicrosoftTeams PowerShell Module version 5.1.0. 

When you run the script below (we have approx. 1500 Teams) we get 0 owners sometimes which is wrong. 

Connect-MicrosoftTeams -Credential (Get-Credential);
$allActiveTeams = Get-Team -Archived $false;
foreach($team in $allActiveTeams ){
        $listOwners = Get-TeamUser -GroupId $team.GroupId -Role Owner | Sort-Object Name;
        Write-Host $listOwners.Count;
}

With the previous version 4.2.0 we didn't have this issue.

**Comment by get-itips** [comment]
Hello @inseu 
How are you?
As here we are limited to documentation fixes, I tried to see if we needed to update any article, however I wasn't able to reproduce what you have experienced, the best would be to open a support request, if you identified that a team is returning 0 owners but you verified it has.
Thank you,

**Comment by get-itips** [comment]
Thanks for returning and sharing that information.
