### ISSUE TITLE
DeclineEventsForScheduledOOF Declines AND Cancels Events

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/office-docs-powershell#11006]
Please update the **DeclineEventsForScheduledOOF** parameter to note that it not only declines all events the user is attending, but if they're the organizer of an event it will *cancel* the event occurance (any any subsequent occurrences occurring in that time frame) for all the other attendees.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47db52ff-7c4b-3051-5414-3e1288216c1e
* Version Independent ID: 0e49597f-47e8-ec2a-9e1b-46bc465643cb
* Content: [Set-MailboxAutoReplyConfiguration (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-mailboxautoreplyconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxAutoReplyConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailboxAutoReplyConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@pyoungberg, are we talking about DeclineEventsForScheduledOOF or DeclineAllEventsForScheduledOOF? Or maybe the result is the same for both, with DeclineEventsForScheduledOOF requiring manual cancellation, while DeclineAllEventsForScheduledOOF automatically cancels?

Feel free to modify the article directly with what you want to say. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

**Comment by pyoungberg** [comment]
@chrisda you're correct, the result is the same for both. Thank you!
