### ISSUE TITLE
Request for more information on this page

### ISSUE THREAD

**Issue by badsector-82** [MicrosoftDocs/office-docs-powershell#11003]
It is not clear if Editor by itself gives permission to accept/decline meeting requests or it must be used in conjunction with SharingPermissionFlags:
"Editor: CreateItems, DeleteAllItems, DeleteOwnedItems, EditAllItems, EditOwnedItems, FolderVisible, ReadItems"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b48ac9a9-ae8b-7656-49b3-b0fcbc862dae
* Version Independent ID: cc3abf30-b1d7-3ca0-ca3a-5437bf8ad7fb
* Content: [Set-MailboxFolderPermission (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-mailboxfolderpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxFolderPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailboxFolderPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@badsector-82, the description of the AccessRights parameter explains what each individual permission does, and then describes the individual permission that are in the available roles. That information goes back to the Exchange 2007 days.

Because there's no mention of anything calendar related in AccessRights other than AvailabilityOnly and LimitedDetails, I would say, yes, the value Delegate from SharinPermissionFlags is also required to manage meeting requests.

**Comment by badsector-82** [comment]
> @badsector-82, the description of the AccessRights parameter explains what each individual permission does, and then describes the individual permission that are in the available roles. That information goes back to the Exchange 2007 days.
> 
> Because there's no mention of anything calendar related in AccessRights other than AvailabilityOnly and LimitedDetails, I would say, yes, the value Delegate from SharinPermissionFlags is also required to manage meeting requests.

Managed to do a quick test today and with Editor access and no SharingPermissionFlags, there's an option to accept/decline but one has to manually click on the meeting. "Delegate" shared permission flag sends emails. If you think that could be helpful information, you can do the needful testing and add this to the documentation.

**Comment by chrisda** [comment]
@badsector-82, thanks for the testing! I added the following line to the AccessRights description in Add-MailboxFolderPermission and Set-Add-MailboxFolderPermission:

> When the Editor role is applied to calendar folders, delegates can accept or decline meetings by manually selecting the meeting request in the mailbox. In Exchange Online, to send meeting requests to delegates where they can accept or decline meetings, also use the SharingPermissionFlags parameter with the value Delegate.

Feel free to modify directly in the article. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing

**Comment by chrisda** [comment]
@badsector-82, thanks for the testing! I added the following line to the AccessRights description in Add-MailboxFolderPermission and Set-Add-MailboxFolderPermission:

> When the Editor role is applied to calendar folders, delegates can accept or decline meetings by manually selecting the meeting request in the mailbox. In Exchange Online, to send meeting requests to delegates where they can accept or decline meetings, also use the SharingPermissionFlags parameter with the value Delegate.

Feel free to modify directly in the article. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
