### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by NetDesignIT** [MicrosoftDocs/office-docs-powershell#1101]
This information is supposedly about updating a Site script, but I don't see how the new script is referenced here, or how a new version of a script updates an existing one. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6baad09-eb72-cf76-e6d1-773e0212020d
* Version Independent ID: cc05315e-1b4b-6704-74ae-6459cef5bb0b
* Content: [Set-SPOSiteScript (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Set-SPOSiteScript?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteScript.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteScript.md)
* Service: **sharepoint-powershell**
* Product: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen for your review

**Comment by AndreaBarr** [comment]
@NetDesignIT Thank you for this feedback

I am going to get this over to the PowerShell team for investigation and updating so we can clear up the confusion. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @NetDesignIT Thanks for your feedback and suggestion!

Document has been updated after you created this issue, please see 

https://github.com/MicrosoftDocs/office-docs-powershell/commit/22fe807866caeb4630290b3ae946e7c0d1aff0ed?diff=split

Hope this clarifies how the new site script is referenced.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @NetDesignIT  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
