### ISSUE TITLE
LanguageBlockList accepts lowercase, but portal expects uppercase

### ISSUE THREAD

**Issue by kbni** [MicrosoftDocs/office-docs-powershell#11024]
If lowercase values are supplied for LanguageBlockList as per this documentation, the security portal will throw an error. We have been advised by Microsoft 365 support to supply uppercase values for LanguageBlockList - seems like this should be considered a bug with the portal, rather than an error in the documentation - but I'm not sure where to report this.

Should this documented be updated to indicate that uppercase is required? (which goes against ISO 639-1)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 164c3337-1862-be67-7e1d-ea8055b88791
* Version Independent ID: 3cb06add-3cb6-7cb8-779b-a681e03ab4fb
* Content: [Set-HostedContentFilterPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-hostedcontentfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kbni, I updated the description and values to use uppercase.

> The LanguageBlockList parameter specifies the email content languages that are marked as spam when the EnableLanguageBlockList parameter value is $true. A valid value is a supported uppercase ISO 639-1 two-letter language code:
>
> AF, AR, AZ, BE, BG, BN, BR, BS, CA, CS, CY, DA, DE, EL, EN, EO, ES, ET, EU, FA, FI, FO, FR, FY, GA, GL, GU, HA, HE, HI, HR, HU, HY, ID, IS, IT, JA, KA, KK, KL, KN, KO, KU, KY, LA, LB, LT, LV, MI, MK, ML, MN, MR, MS, MT, NB, NL, NN, PA, PL, PS, PT, RM, RO, RU, SE, SK, SL, SQ, SR, SV, SW, TA, TE, TH, TL, TR, UK, UR, UZ, VI, WEN, YI, ZH-CN, ZH-TW, and ZU.

Thanks for the feedback.

Closing
