### ISSUE TITLE
"Set-UnifiedGroup -CalendarMemberReadOnly" no longer working

### ISSUE THREAD

**Issue by dsmith-dsb** [MicrosoftDocs/office-docs-powershell#11047]
As of the June update, this cmdlet no longer works and gives a "Set-UnifiedGroup: Object reference not set to an instance of an object." error when trying to run. See powershell output below

PS /home/dave> Connect-ExchangeOnline

----------------------------------------------------------------------------------------
This V3 EXO PowerShell module contains new REST API backed Exchange Online cmdlets which doesn't require WinRM for Client-Server communication. You can now run these cmdlets after turning off WinRM Basic Auth in your client machine thus making it more secure. 

Unlike the EXO* prefixed cmdlets, the cmdlets in this module support full functional parity with the RPS (V1) cmdlets.

V3 cmdlets in the downloaded module are resilient to transient failures, handling retries and throttling errors inherently. 

However, REST backed EOP and SCC cmdlets are not available yet. To use those, you will need to enable WinRM Basic Auth. 

For more information check https://aka.ms/exov3-module

----------------------------------------------------------------------------------------

PS /home/dave> Set-UnifiedGroup **** -CalendarMemberReadOnly         
Set-UnifiedGroup: Object reference not set to an instance of an object.
PS /home/dave> Get-UnifiedGroup ****                                                             

Name                                                  DisplayName GroupType PrimarySmtpAddress
----                                                  ----------- --------- ------------------
**********************************            ******        Universal     *******@*****.com

PS /home/dave> Set-UnifiedGroup ***** -CalendarMemberReadOnly:$true
Set-UnifiedGroup: Object reference not set to an instance of an object.

**Comment by chrisda** [comment]
@dsmith-dsb, you should open a support ticket about this.

**Comment by linkmaster6** [comment]
I would like to reopen this as I tired this morning and I am still getting the error "Object reference not set to an instance of an object"

**Comment by chrisda** [comment]
@linkmaster6, sure. But, this isn't a technical forum; this location tracks **documentation** issues.

As described earlier, you should open a support ticket to report this. Report back here with any information that can help improve the documentation. Unclear at this point if this is a transitory issue (meaning, it should work but currently doesn't for some reason) or if it's a known, "always will be this way" issue (in which case the documentation needs to be updated).

There has been a lot of back and forth about M365 Group cmdlets and lack of support based on versions of the module and connection methods (CBA, MI, etc.). It's telling to me that a bunch of other M365 Group cmdlets are listed as not working, but not Set-.
