### ISSUE TITLE
Error trying to use parameter InboundFederatedCallRoutingTreatment

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#11045]
Using version 5.1.0 of the MicrosoftTeams Powershell Module, if I ask for the parameters for this cmdlet, I see that InboundFederatedCallRoutingTreatment is a valid parameter

New-CsTeamsCallingPolicy -Identity Test | Get-Member

   TypeName: Deserialized.Microsoft.Rtc.Management.WritableConfig.Policy.Teams.TeamsCallingPolicy

Name                                 MemberType   Definition

GetType                              Method       type GetType()
ToString                             Method       string ToString(), string ToString(string format, System.IFormatPr...
AllowCallForwardingToPhone           NoteProperty bool AllowCallForwardingToPhone=True
AllowCallForwardingToUser            NoteProperty bool AllowCallForwardingToUser=True
AllowCallGroups                      NoteProperty bool AllowCallGroups=True
AllowCallRedirect                    NoteProperty string AllowCallRedirect=Disabled
AllowCloudRecordingForCalls          NoteProperty bool AllowCloudRecordingForCalls=False
AllowDelegation                      NoteProperty bool AllowDelegation=True
AllowPrivateCalling                  NoteProperty bool AllowPrivateCalling=True
AllowSIPDevicesCalling               NoteProperty bool AllowSIPDevicesCalling=False
AllowTranscriptionForCalling         NoteProperty bool AllowTranscriptionForCalling=False
AllowVoicemail                       NoteProperty string AllowVoicemail=UserOverride
AllowWebPSTNCalling                  NoteProperty bool AllowWebPSTNCalling=False
AutoAnswerEnabledType                NoteProperty string AutoAnswerEnabledType=Disabled
BusyOnBusyEnabledType                NoteProperty string BusyOnBusyEnabledType=Disabled
CallRecordingExpirationDays          NoteProperty int CallRecordingExpirationDays=60
DataSource                           NoteProperty string DataSource=Memory
Description                          NoteProperty string Description=Everyone
EnableWebPstnMediaBypass             NoteProperty bool EnableWebPstnMediaBypass=False
Identity                             NoteProperty string Identity=Tag:JoelX
InboundFederatedCallRoutingTreatment NoteProperty string InboundFederatedCallRoutingTreatment=RegularIncoming
InboundPstnCallRoutingTreatment      NoteProperty string InboundPstnCallRoutingTreatment=RegularIncoming
Key                                  NoteProperty Deserialized.System.Management.Automation.PSCustomObject Key=Scope...
LiveCaptionsEnabledTypeForCalling    NoteProperty string LiveCaptionsEnabledTypeForCalling=DisabledUserOverride
MusicOnHoldEnabledType               NoteProperty string MusicOnHoldEnabledType=Disabled
PopoutAppPathForIncomingPstnCalls    NoteProperty object PopoutAppPathForIncomingPstnCalls=null
PopoutForIncomingPstnCalls           NoteProperty string PopoutForIncomingPstnCalls=Disabled
PreventTollBypass                    NoteProperty bool PreventTollBypass=False
SpamFilteringEnabledType             NoteProperty string SpamFilteringEnabledType=Enabled

Yet, when I attempt to set the parameter, I get the error

New-CsTeamsCallingPolicy -Identity MS -InboundFederatedCallRoutingTreatment RegularIncoming
New-CsTeamsCallingPolicy : A parameter cannot be found that matches parameter name
'InboundFederatedCallRoutingTreatment'.
At line:1 char:39
+ ... lingPolicy -Identity MS -InboundFederatedCallRoutingTreatment Regular ...
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-CsTeamsCallingPolicy], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-CsTeamsCallingPolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d765cdb-1d9e-0bf6-f1ea-52d7ef72e596
* Version Independent ID: 60558e3a-9a9c-16f3-1443-d924fb659c80
* Content: [New-CsTeamsCallingPolicy (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@sarollins Thanks for the feedback. My suggestion is to use the newer versions like 5.2.0 or 5.3.0, where the cmdlet works as expected.

**Comment by yogkumgit** [comment]
@sarollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
