### ISSUE TITLE
Search-MessageTrackingReport is an Exchange OnPremise only cmdlet

### ISSUE THREAD

**Issue by jprknight** [MicrosoftDocs/office-docs-powershell#11042]
This cmdlet does not work in Exchange Online. It is an OnPremise only cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cdba4-be2c-5d46-2428-3c5c5e431836
* Version Independent ID: af14b0bc-1114-69e4-0d39-75f6bb44decd
* Content: [Search-MessageTrackingReport (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/search-messagetrackingreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Search-MessageTrackingReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Search-MessageTrackingReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jprknight, right. That's why at the top of the article, it says:

 > This cmdlet is functional only in on-premises Exchange.

Availability and functionality are not always the same thing. Search-MessageTrackingReport is _available_ in Exchange Online PowerShell; I just checked.

**Comment by jprknight** [comment]
Perfect thank you. I missed that level of detail.

**Comment by jprknight** [comment]
.
