### ISSUE TITLE
Is there an alternative to Remove-CsVoiceNormalizationRule ?

### ISSUE THREAD

**Issue by abanajiger** [MicrosoftDocs/office-docs-powershell#11058]
[Enter feedback here]
The page mentions that the Remove command is deprecated, are there any alternatives to remove the normalization rules from a Dial Plan?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2628dc83-b262-8217-eea4-ae79aaeea4f5
* Version Independent ID: b5b2e5ee-1d71-938e-7e77-9e2bc2eeb2b9
* Content: [Remove-CsVoiceNormalizationRule (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by JensTrier** [comment]
@abanajiger Example 4 in the PS cmdlet page for [Set-CsTenantDialPlan](https://learn.microsoft.com/en-us/powershell/module/skype/set-cstenantdialplan?view=skype-ps) shows how to remove a normalization rule from a tenant dial plan. Is that what you are looking for?

**Comment by abanajiger** [comment]
@JensTrier Yes, Sir! This is exactly what I am looking for. Thank you for the comment, sorry, I should have looked harder before posting it here.
