### ISSUE TITLE
Get-CsOnlineVoicemailUserSettings & Set-CsOnlineVoicemailUserSettings Not Finding Users

### ISSUE THREAD

**Issue by nathanielhoh** [MicrosoftDocs/office-docs-powershell#11056]
Have recently been unable to use both commands, getting error:

```
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get-CsOnlineVMUserSetting : The specified user ............... cannot be found or does not belong to the tenant.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\5.3.0\custom\Merged_custom_PsExt.ps1:5771 char:13
+             $result = Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get- ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = Identity = it...tvault.net.au }:<>f__AnonymousType2`1) [Get-CsOnlineVMUserSetting_Get], RestException
    + FullyQualifiedErrorId : 400,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsOnlineVMUserSetting_Get
```

```
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsOnlineVMUserSetting : The specified user ............... cannot be found or does not belong to the tenant.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\5.3.0\custom\Merged_custom_PsExt.ps1:9722 char:13
+             $result = Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set- ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = it...emailSettings }:<>f__AnonymousType77`2) [Set-CsOnlineVMUserSetting_SetExpanded], RestException
    + FullyQualifiedErrorId : 400,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsOnlineVMUserSetting_SetExpanded
```

However can successfully retrieve the user using Get-CsOnlineUser and can see and change the User's voicemail settings directly in the Teams admin center. This is occurring for all user's across multiple tenants.

**Comment by pbafna03** [comment]
Hi @nathanielhoh, 

Can you please try this with version 5.2.0?

**Comment by shivtorov** [comment]
@nathanielhoh 
Mentioned voicemail cmdlets were always unreliable in searching users by UserPrincipalName.
It appears that they can find by name properly licensed + SIP & voice enabled users.

An immediate workaround that seems to provide 100% success rate is to refer to accounts by their GUID.

Example:

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/31003608/00eec052-f27d-4051-affe-2141fe83cb82)

**Comment by yogkumgit** [comment]
@pbafna03

**Comment by pbafna03** [comment]
> @pbafna03

@JensTrier can better guide on this.

**Comment by JensTrier** [comment]
We are documenting that these cmdlets don't support UPN as Identity. I'll add a feedback item for the relevant team to add supporting UPN.

**Comment by yogkumgit** [comment]
@JensTrier Thank you very much for sharing this explanation. @nathanielhoh Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
