### ISSUE TITLE
-EnablePortalTrackingLog parameter mentioned in documentation for Set-IRMConfiguration does not actually exist

### ISSUE THREAD

**Issue by amaiman** [MicrosoftDocs/office-docs-powershell#11057]
https://learn.microsoft.com/microsoft-365/compliance/audit-log-encrypted-messages#enabling-message-access-audit-logs-in-powershell

Documentation is incorrect as the parameter `-EnablePortalTrackingLogs` does not exist in `Set-IRMConfiguration` in the Exchange Online v3 module.  It looks like it was added in v2 and then regressed/removed from v3.  Would appreciate it if you could have the product team look at this as there doesn't appear to be a way to enable this logging now that v2 has been deprecated.

```powershell
Set-IRMConfiguration : A parameter cannot be found that matches parameter name 'EnablePortalTrackingLogs'.
At line:1 char:22
+ Set-IRMConfiguration -EnablePortalTrackingLogs $True
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-IRMConfiguration], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-IRMConfiguration

```

Other people have noticed and commented on an older issue: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9438
Opening this as a new issue so that someone will take a look at it.  Please do not close this issue without either updating the documentation to show that this feature is no longer available or having the product team make the product functionality match the documentation.  The parameter still shows with `Get-IRMConfiguration` but cannot be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebaffb3-b4a1-9ba1-d6cb-cea3befecc89
* Version Independent ID: 8b7b857e-4090-d865-79dc-5e14f6fa7748
* Content: [Set-IRMConfiguration (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-irmconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-IRMConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-IRMConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@amaiman, a minor point, but there are very few commands contained in the ExchangeOnlineManagement module itself. Those are all described [here](https://learn.microsoft.com//powershell/exchange/exchange-online-powershell-v2#cmdlets-in-the-exchange-online-powershell-module). So, from that angle, it makes little difference which version of the module you're using to connect, except for issues related to the connection *method* itself (REST API vs. remote PowerShell, certificate based authentication, managed identity, and C#).

The primary arbiter of cmdlets/parameters that aren't in the module itself is RBAC. When I use the methods described in [this article](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions), the parameter is most definitely available to me in a plain Microsoft 365 E5 tenant:

```powershell
PS C:\Users\jdoe> $Perms = Get-ManagementRole -Cmdlet Set-IrmConfiguration -CmdletParameters EnablePortalTrackingLogs
PS C:\Users\jdoe> $Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}

Role                          RoleAssigneeType RoleAssigneeName
----                          ---------------- ----------------
Information Rights Management RoleGroup        Compliance Management
Information Rights Management RoleGroup        Organization Management
```

I know the encryption/OMEv2 story has been changing over the last several months, but even after all of that, a dedicated article for using the EnablePortalTrackingLogs parameter survived:

[Encrypted message portal activity log by Microsoft Purview Advanced Message Encryption]((https://learn.microsoft.com/microsoft-365/compliance/audit-log-encrypted-messages)

So, the parameter definitely still exists.

**Comment by amaiman** [comment]
I'm using a Global Administrator account (which gives the 'Organization Management' role), so RBAC shouldn't be the issue.  It sounds like what may actually be the issue is that Microsoft may have locked this feature behind an E5 licensing requirement.  If this is the case, that should be made clearer in the documentation.

**Comment by chrisda** [comment]
@amaiman, I'm not aware of any licensing restrictions, for what that's worth.

I tried those same commands in a Microsoft 365 Business Premium tenant, and it was still available.

You're not connecting via managed identity or CBA or anything like that? And you're not simultaneously connecting to Exchange Online PowerShell and Security & Compliance PowerShell in the same window?

**Comment by amaiman** [comment]
ExangeOnlineManagement version 3.2.0, connecting with interactive modern authentication (entered username/password, confirmed MFA), only `Import-Module ExchangeOnlineManagement` and `Connect-ExchangeOnline` used.  Same results in the Cloud Shell with `Connect-EXOPSSession`.

I tried using my test tenant (which has E5 Developer) and also got the same results there that the parameter doesn't exist.

RBAC looks good on the production tenant, "Information Rights Management" is present:

```
PS C:\temp> $Perms = Get-ManagementRole -Cmdlet Set-IrmConfiguration -CmdletParameters EnablePortalTrackingLogs
PS C:\temp> $Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}

Role                          RoleAssigneeType RoleAssigneeName
----                          ---------------- ----------------
Information Rights Management RoleGroup        Compliance Management
Information Rights Management RoleGroup        Organization Management

PS C:\temp> Get-ManagementRoleAssignment -GetEffectiveUsers | Where-Object {$_.EffectiveUserName -eq "redacted"} | Select-Object Role | Where-Object {$_.Role -eq "Information Rights Management"}

Role
----
Information Rights Management
Information Rights Management
```

**Comment by chrisda** [comment]
Checking

**Comment by samschan-ms** [comment]
Yes, enableportaltrackinglog parameter requires E5 licenses. this is not available to E3 feautres. the documentation is part of the Advanced Message Encryption solution.

**Comment by chrisda** [comment]
@amaiman, I added this sentece to the top of the parameter description:

> **Note**: This parameter is available only in organizations with Microsoft Purview Advanced Message Encryption. For more information, see [Advanced Message Encryption](https://learn.microsoft.com/microsoft-365/compliance/ome-advanced-message-encryption).

Thanks for the feedback.

Closing
