### ISSUE TITLE
Get-Help Grant-CsTeamsCallingPolicy shows invalid usage

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/office-docs-powershell#11062]
PowerShell 7.3.5
Teams Online PowerShell Module version 5.3.0

When you run "Get-Help Grant-CsTeamsCallingPolicy", you will be shown valid syntaxes.
However, the first listed syntax is invalid and cannot be used when executing the command.
This error is not present in Teams PowerShell module version 4.6.0, so it must have been introduced later.

To reproduce, run:
```
PS C:\> Get-Help Grant-CsTeamsCallingPolicy

NAME
    Grant-CsTeamsCallingPolicy

SYNTAX
    Grant-CsTeamsCallingPolicy [<CommonParameters>]

    Grant-CsTeamsCallingPolicy [[-PolicyName] <string>] -Identity <string> [<CommonParameters>]

    Grant-CsTeamsCallingPolicy [-Group] <string> [[-PolicyName] <string>] -Rank <int> [<CommonParameters>]

    Grant-CsTeamsCallingPolicy [-Global] [[-PolicyName] <string>] [-Force] [<CommonParameters>]

ALIASES
    None

REMARKS
    None

PS C:\> Grant-CsTeamsCallingPolicy
Grant-CsTeamsCallingPolicy: Cannot determine which grant to execute
PS C:\>
```

**Comment by pbafna03** [comment]
Hi @donlassini, 

Thanks for reporting this, we'll get this fixed soon in subsequent Teams PowerShell module releases.
