### ISSUE TITLE
Security & Compliance Powershell documentation invalid

### ISSUE THREAD

**Issue by mheck-lm** [MicrosoftDocs/office-docs-powershell#11064]
The Security & Compliance Powershell documentation contains information about the ExchangeOnlineManagement module instead of the SecurityComplianceCenter module.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/connect-to-scc-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mheck-lm, in a cruel twist of fate, there is no SecurityComplianceCenter module. You connect to both Exchange Online PowerShell and Security & Compliance Center PowerShell using the same module that happens to be named ExchangeOnlineManagement.

If it's any consolation, you use different commands to connect: Connect-ExchangeOnline for ExO PowerShell and Connect-IPPSSession for S&C PowerShell.

**Comment by mheck-lm** [comment]
@chrisda I'm sorry for the inconvenience. We got confused by the documentation and found a non-Microsoft Module named SecurityComplianceCenter. This mislead me to the point, that I thought the documentation is wrong.
Sorry again and thanks for clarifying.
