### ISSUE TITLE
RPS deprecation not mentioned

### ISSUE THREAD

**Issue by rsparnaaij** [MicrosoftDocs/office-docs-powershell#11074]
This article is missing the information to promote the deprecation of RPS. At the very least, the -UseRPSSession parameter description should contain a link to; [Deprecation of Remote PowerShell in Exchange Online – Re-enabling or Extending RPS support](https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-remote-powershell-in-exchange-online-re-enabling/ba-p/3779692)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13d88f18-3cc8-5f18-8d61-ff7f5fa4e314
* Version Independent ID: 60f9a029-69f3-e65c-6816-fbd414790ce3
* Content: [Connect-ExchangeOnline (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rsparnaaij, I added a Note to the description of the UseRPSSession parameter, I removed the mention of UseRPSSession in Example 1, and I eliminated the example that used the UseRPSSession parameter.

Thanks for the feedback.

Closing
