### ISSUE TITLE
RPS deprecation not mentioned on about page

### ISSUE THREAD

**Issue by rsparnaaij** [MicrosoftDocs/office-docs-powershell#11075]
This About article is missing the information to promote the deprecation of RPS.

At the very least, the section "Turn on Basic authentication in WinRM" should contain a link to; [Deprecation of Remote PowerShell in Exchange Online – Re-enabling or Extending RPS support](https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-remote-powershell-in-exchange-online-re-enabling/ba-p/3779692)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module and V3 module](https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#turn-on-basic-authentication-in-winrm)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rsparnaaij, I added/updated Notes and links everywhere to say the remote PowerShell in ExO is gone, and will be gone in Security & Compliance PowerShell.

Thanks for the feedback.

Closing
