### ISSUE TITLE
"Pick up held" and "Join active" calls in delegate settings

### ISSUE THREAD

**Issue by vlethiec** [MicrosoftDocs/office-docs-powershell#11084]
Hello, 

Do you know when the new attributes "Pick up held calls" and "Join active calls" will be offered by the "Set-CsUserCallingDelegate" cmdlet?

We are starting to receive requests for these features. 

Source: https://insider.microsoft365.com/en-us/blog/enhancements-for-delegation-in-teams-phone
 
Thanks in advance for your feedback. 

Regards, 

Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d6e47fb-b461-2cc4-ff82-58f9cea5ed85
* Version Independent ID: 5995223b-6cfd-5c2d-3ada-3d576624b773
* Content: [Set-CsUserCallingDelegate (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsUserCallingDelegate.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by get-itips** [comment]
Hello @vlethiec I could get information that is expected for later this year.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @vlethiec Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
