### ISSUE TITLE
Azure Automate: Connect-Exchange Online throws error on Certificate object use

### ISSUE THREAD

**Issue by albourne-dev** [MicrosoftDocs/office-docs-powershell#11088]
The below code works on Automate Runtime 5.1 and EXOv3.2 module
The below code throws the error shown below on Runtime 7.1 and 7.2.
```
$EXOCertObj = Get-AutomationCertificate -Name CertificateStoredInAzureAutomateAccount 


# Do cert auth against EXO 
try {
Connect-ExchangeOnline -Certificate $EXOCertObj `
	-AppID "xxxxxxxx-30f1-4b96-bb4f-4153e6609e45" `
	-Organization "org.onmicrosoft.com" 
	} catch {
		write-output "Cannot connect to EXO"
		Exit
	}
```

```
Failed

OperationStopped: C:\ModulesV2\User\ExchangeOnlineManagement\netCore\ExchangeOnlineManagement.psm1:739
Line |
 739 |                      throw $_.Exception.InnerException;
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0,
     | Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
```

**Comment by chrisda** [comment]
@albourne-dev, verify that you don't have Beta versions of the PackageManagement or PowerShellGet modules by running the following command: `Get-InstalledModule PackageManagement -AllVersions; Get-InstalledModule PowerShellGet -AllVersions`.

Otherwise, you should open a support ticket. Report back here with any information that can help improve the documentation.

**Comment by albourne-dev** [comment]
@chrisda I found the following installed on the Azure Automate provided session.
None was a prerelease.

I then installed the latest versions of both via Modules in Azure Automate.

Do you believe I should re-run the update of the EXOv2 to EXOv3 now? 
Could this relate to solving the error seen?

Also, which channel should I use to open a ticket for this?

`   Directory: C:\powershell7\Modules

ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Script     1.4.7                 PackageManagement                   Desk     

    Directory: C:\ModulesV2\User

ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Script     1.4.8.1               PackageManagement                   Desk     

    Directory: C:\powershell7\Modules

ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Script     2.2.5                 PowerShellGet                       Desk     

    Directory: C:\ModulesV2\User

ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Script     2.2.5                 PowerShellGet                       Desk     `

**Comment by chrisda** [comment]
@albourne-dev, you can try uninstalling and reinstalling the ExchangeOnlineManagement module if you like.

To open a support ticket, see [here](https://learn.microsoft.com/microsoft-365/admin/get-help-support).
