### ISSUE TITLE
Connect-ExchangeOnline throws error from within a Windows Server service process.

### ISSUE THREAD

**Issue by LainRobertson** [MicrosoftDocs/office-docs-powershell#11092]
Hi, folks.

I ran into this issue a very long time ago but found it did not exist on ExchangeOnlineManagement module version 2.0.5, so I've avoided dealing with it until today, where it seems 2.0.5 no longer works.

I'm not looking to examine why 2.0.5 worked as I've only been using it all this time as a workaround for the fact that 3.x never did.

I've updated to 3.2.0, which still contains the issue described below, and it's this version I'm looking to try and find a resolution for.

### Exception (taken from the log file)

<pre>
2023-07-19 19:06:32: at Connect-ExchangeOnline<Process>, C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\3.2.0\netFramework\ExchangeOnlineManagement.psm1: line 743
at <ScriptBlock>, C:\Data\Scripts\ps.exo.cewa.edu.au\Invoke-MIMPSBeginImport.ps1: line 76
at <ScriptBlock>, C:\windows\TEMP\5l5mjkmo.ps1: line 27
Cannot update the manifest file 'C:\Users\<i>accountName</i>\AppData\Local\Temp\tmpEXO_f2qn0x4u.k0p\tmpEXO_f2qn0x4u.k0p.psd1' because the manifest is not valid. Verify that the manifest file is valid, and then try again.'Cannot convert 'System.String' to the type 'System.Management.Automation.SwitchParameter' required by parameter 'Verbose'. '.
</pre>

### Code extract (PowerShell)
<pre>
#region Establish Exchange Online session.
try
{
    # Commandlets to load.
    $CommandsToImport = [string[]] @(
        "Get-AddressBookPolicy"
        , "Get-AddressList"
        , "Get-GlobalAddressList"
        , "Get-OfflineAddressBook"
    )

    $UICred = $Credential.GetNetworkCredential();
    $Thumbprint = $UICred.Password;
    Out-File -FilePath $LogFile -Append -InputObject "Thumbprint being used: $($Thumbprint).`n`$VerbosePreference: $VerbosePreference";

    Connect-ExchangeOnline -ShowBanner:$false -PageSize ($OpenImportConnectionRunStep.PageSize) -CommandName $CommandsToImport -Organization ($UICred.Domain) -AppId ($UICred.UserName) -CertificateThumbprint $Thumbprint -ErrorAction:Stop | Out-Null;
}
catch
{
    Out-File -FilePath $LogFile -Append -InputObject "$([datetime]::Now.ToString($Timestamp))`: $($_.ScriptStackTrace)`n$_.Exception";
    throw;
}
#endregion
</pre>

### Environment
<pre>
PS C:\Data> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.4644
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.4644
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
</pre>

<pre>
PS C:\Data> Get-Module -ListAvailable -Name ExchangeOnlineManagement | ft -AutoSize Version, Name

Version Name
------- ----
3.2.0   ExchangeOnlineManagement
</pre>

### Scenario
The PowerShell script is called from within a Windows service, i.e. it is not an interactive session.

When the same Connect-ExchangeOnline command from above is run in a PowerShell session from an interactive logon (i.e. when I log on and run it), the error cannot be reproduced, even when setting $VerbosePreference to different values prior to the Connect-ExchangeOnline call.

As an observation, I do not have any issues with calls made using commandlets from the the Microsoft.Graph.* or Az.* modules. It seems to be something specific to ExchangeOnlineManagement when executing under a process that is a Windows Server service, and only after module version 2.0.5 (which has been running fine for just over a year now.)

Because this is running inside a Windows Server service process (the FIMSynchronizationService service from Microsoft Identity Manager 2016 SP2), I've assumed I cannot leverage the -Debug parameter since I've always found it requires interactive input (even with -Confirm:$false), but if I'm wrong about that, let me know and I'll look to test with it.

### Expected outcome
That functionality provided by the ExchangeOnlineManagement module continues to succeed when running within a Windows Server service process as it did in 2.0.5 (and prior, though how far earlier I'm unsure.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13d88f18-3cc8-5f18-8d61-ff7f5fa4e314
* Version Independent ID: 60f9a029-69f3-e65c-6816-fbd414790ce3
* Content: [Connect-ExchangeOnline (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@LainRobertson, you should open a support ticket about this.

You can also try sending the information to `exocmdletpreview[at]service[dot]microsoft[dot]com` to see if they can help.

**Comment by LainRobertson** [comment]
Hi, @chrisda.

The past couple of minutes has yielded a new and interesting development.

I decided to see what paring back further data might yield purely on a whim (classic "Hail Mary" approach), and by including the "-SkipLoadingFormatData" parameter, the call to Connect-ExchangeOnline has succeeded, as have all the subsequent Exchange-related commandlets.

For clarity, this is the call syntax that has succeeded:

<pre>
Connect-ExchangeOnline -ShowBanner:$false -PageSize ($OpenImportConnectionRunStep.PageSize) -CommandName $CommandsToImport -Organization ($UICred.Domain) -AppId ($UICred.UserName) -CertificateThumbprint $Thumbprint -ErrorAction:Stop <i>-SkipLoadingFormatData</i> | Out-Null;
</pre>

This can only be considered a workaround as it's still a bug that this is even necessary, but subsequent to further testing later today (it's 1:19am here and I just can't bring myself to finish testing now), I'm going to take the easy route and go with it.

Cheers,
Lain

**Comment by LainRobertson** [comment]
Just a quick follow-up to say that adding the "-SkipLoadingFormatData" parameter has proven to be a resilient workaround to the bug, having resolved the same issue across multiple servers and over multiple executions.

Cheers,
Lain

**Comment by chrisda** [comment]
@LainRobertson, per the referenced pull requests, I added the following note to the SkipLoadingFormatData parameter description and added information to the 'Connect to Exchange Online PowerShell' article:

> Use this switch to avoid errors when connecting to Exchange Online PowerShell from within a Windows service.

I would encourage you to send your detailed research and logs to `exocmdletpreview[at]service[dot]microsoft[dot]com` to see if they can fix the issue in a future release of the module.

**Comment by LainRobertson** [comment]
Thanks, @chrisda.

I've forwarded this to the address you've provided, and with the documentation note you've added would be happy to see this closed.

Cheers,
Lain
