### ISSUE TITLE
CertificateThumbprint parameter is supported only in Microsoft Windows.

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/office-docs-powershell#11096]
Is there any information why the -CertiticateThumbprint parameter is only supported in Windows?
Other modules like the Microsoft.Graph module support CertificateThumbprint also under macOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication in Exchange Online PowerShell and Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@joergrenn, you're welcome to try using the CertificateThumbprint parameter on non-Windows systems using the latest version of the module (v3.2.0) that was released just a few weeks ago.

You can also send the question to `exocmdletpreview[at]service[dot]microsoft[dot]com`. You likely won't get specifics about dates, but you might at least find out if the issues is even being worked on.

**Comment by joergrenn** [comment]
@chrisda, thanks for the suggestion.
I have tried v3.2.0, but the parameter is not available in macOS.
I will send my question via mail and see if I get a response. 
There's probably not more we can do here for now.
