### ISSUE TITLE
Get-CsPhoneNumberAssignment lacking parameter for unlimited / all results

### ISSUE THREAD

**Issue by sofbkeller** [MicrosoftDocs/office-docs-powershell#11104]
Please add a Parmeter which allows the query of all phone number assignments rather than requiring an arbitrary integer of the max lookup amount.

**Comment by shivtorov** [comment]
@sofbkeller, you can always use value = "[type]::MaxValue" in such situations.
i.e.
```powershell
Get-CsPhoneNumberAssignment -Top ([int]::MaxValue)
```

**Comment by get-itips** [comment]
Thanks @shivtorov for that tip
