### ISSUE TITLE
limit of 500 numbers are seen 

### ISSUE THREAD

**Issue by techbev** [MicrosoftDocs/office-docs-powershell#11116]
the get-csphonenumberassignment command has a limit of 500. Cx has requested an update to reflect this. 

heI was able to loop the command and skip the gathered results to retrieve all 2300 results

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bfb9351-75be-abb8-c8ac-bf08f51d08a1
* Version Independent ID: c7925810-6411-9371-7a04-fc28a4c827ec
* Content: [Get-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/Get-CsPhoneNumberAssignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by shivtorov** [comment]
It makes sense to add an additional example to the article to demo how to retrieve all results:

```powershell
Get-CsPhoneNumberAssignment -Top ([int]::MaxValue)
```

**Comment by JensTrier** [comment]
@techbev thanks for providing this feedback to improve the documentation!

**Comment by get-itips** [comment]
The edit to the article is on the approval process

**Comment by techbev** [comment]
Hi Tina,

When will this update show on public facing Microsoft Doc site?

Thank you for your help.

Bev

Best Regards,

Bev Sebastian
Teams/Skype Support Escalation Engineer (SEE)
Hours: 9am to 6pm PDT
Manager: John Kindt ***@***.******@***.***>)
