### ISSUE TITLE
[New|Set]-CsTeamsMeetingPolicy params

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#11138]
pls document missing params for [New|Set]-CsTeamsMeetingPolicy

|Cmdlet|Undocumented paramters|
|---|---|
| [New-CsTeamsMeetingPolicy](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md)|AllowAnnotations, AllowAvatarsInGallery, AllowCarbonSummary, AllowDocumentCollaboration, AllowExternalNonTrustedMeetingChat, AllowImmersiveView, AllowLocalRecording, AllowMeetingCoach, AllowTasksFromTranscript, AllowWatermarkCustomizationForCameraVideo, AllowWatermarkCustomizationForScreenSharing, AttendeeIdentityMasking, AudibleRecordingNotification, ChannelRecordingDownload, ConnectToMeetingControls, ExplicitRecordingConsent, InfoShownInReportMode, LiveInterpretationEnabledType, QnAEngagementMode, RoomPeopleNameUserOverride, WatermarkForCameraVideoOpacity, WatermarkForCameraVideoPattern, WatermarkForScreenSharingOpacity, WatermarkForScreenSharingPattern|
| [Set-CsTeamsMeetingPolicy](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)|AllowAnnotations, AllowAvatarsInGallery, AllowCarbonSummary, AllowDocumentCollaboration, AllowExternalNonTrustedMeetingChat, AllowImmersiveView, AllowLocalRecording, AllowMeetingCoach, AllowTasksFromTranscript, AllowWatermarkCustomizationForCameraVideo, AllowWatermarkCustomizationForScreenSharing, AttendeeIdentityMasking, AudibleRecordingNotification, ConnectToMeetingControls, ExplicitRecordingConsent, InfoShownInReportMode, QnAEngagementMode, RoomPeopleNameUserOverride, WatermarkForCameraVideoOpacity, WatermarkForCameraVideoPattern, WatermarkForScreenSharingOpacity, WatermarkForScreenSharingPattern|

**Comment by get-itips** [comment]
Hello @shivtorov I'm working on getting this information, thank you

**Comment by get-itips** [comment]
Hello, I could get the information that the team expects to document those cmdlets in the near future.
