### ISSUE TITLE
duplicate articles for Remove-CsOnlineTelephoneNumber

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#11134]
there are two `Remove-CsOnlineTelephoneNumber.md` articles in this repo with different content.

- [teams/teams-ps/Remove-CsOnlineTelephoneNumber.md](/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/Remove-CsOnlineTelephoneNumber.md)
- [skype/skype-ps/skype/Remove-CsOnlineTelephoneNumber.md](/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Remove-CsOnlineTelephoneNumber.md)

**Comment by get-itips** [comment]
Hello @shivtorov 
Nice catch, I'll see what is decided and get back.
Thanks
