### ISSUE TITLE
Get-MultiGeoRegion permissions for application-based authentication in Teams PowerShell Module not documented

### ISSUE THREAD

**Issue by hoetz** [MicrosoftDocs/office-docs-powershell#11132]
I have used this documentation to use the Teams Powershell via app based auth:
https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication

In general, this is working. Today I wanted to execute the CmdLet 
`Get-MultiGeoRegion -EntityType User -EntityId [UPN]`

This results in an error when connecting via AppId / Certificate.
`Get-MultiGeoRegion: {"error":"Client is not authorized to make call to this service"}`

It is working when connecting interactively with a Teams Administrator.

The command is mentioned in this article and it would be helpful to get clarification on the permissions needed: https://learn.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-capabilities-in-teams-in-microsoft-365?view=o365-worldwide

Via Fiddler I found out that the command is calling the endpoint `https://migrationsvc.teams.microsoft.com:8653/api/v1.0/`

**Comment by get-itips** [comment]
Hello @hoetz Florian, I'll try to confirm if Get-MultiGeoRegion is app-based auth compatible.
Thank you

**Comment by get-itips** [comment]
The article will be updated to reflect that Get-MultiGeoRegion does not work with app-based auth yet.
