### ISSUE TITLE
Add callout for allowing sync of policies prior to creating a new one

### ISSUE THREAD

**Issue by MSFT-SeanG** [MicrosoftDocs/office-docs-powershell#11153]
Per documentation on the "Set-CaseHoldPolicy" cmdlet, there's a callout for full policy sync across an organization. We expect that this also happens during "New-CaseHoldPolicy", as it too needs to sync policies.

Adding a request here to add the "Note" outlined in the top of <https://learn.microsoft.com/powershell/module/exchange/set-caseholdpolicy> to this document as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ee25f1c-d3bf-82b6-40ce-dbf4acd052dd
* Version Independent ID: 46187cd1-47cd-f7c4-4720-e612eb370884
* Content: [New-CaseHoldPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-caseholdpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-CaseHoldPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-CaseHoldPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MSFT-SeanG, I copied the Note over from Set to New, with some obviously required edits based on the update of existing vs. the creation of new. Unclear if everything in the update is actually true. Feel free to edit directly in the article as needed.

> **Note**: Running this cmdlet causes a full synchronization across your organization, which is a significant operation. If you need to create multiple policies, wait until the policy distribution is successful before running the cmdlet again for the next policy. For information about the distribution status, see [Get-CaseHoldPolicy](https://learn.microsoft.com/powershell/module/exchange/get-caseholdpolicy).

Thanks for the feedback.

Closing
