### ISSUE TITLE
Set-ActivityAlert -Name parameter not accepted

### ISSUE THREAD

**Issue by BrianDagan** [MicrosoftDocs/office-docs-powershell#1116]
Contrary to the documentation here (https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/set-activityalert?view=exchange-ps), the Set-ActivityAlert cmdlet does not accept a Name parameter and instead returns the error "A parameter cannot be found that matches parameter name 'Name'."

**Comment by chrisda** [comment]
@BrianDagan, I replaced the existing description for the Name parameter with "reserved for internal Microsoft use" .

Thanks for the feedback.
