### ISSUE TITLE
Are shared mailboxes supported?

### ISSUE THREAD

**Issue by riohedfield** [MicrosoftDocs/office-docs-powershell#11169]
Hello :), 

I hope you're doing well, I need your input whether this cmdlet (Enable-App, as well as New-App, Remove-App ...) should work when dealing with shared mailboxes.
I would like to be able to manage add-ins that are assigned to shared mailbox but I don't seem to be able to do that

1. When I run Get-App -OrganizationApp I see a list of add-ins, but this same list I cannot find in the GUI (Admin portal etc...). Can you tell if it's manageable from the GUI?

2. When I run this cmdlet on a shared mailbox (Get-App -Mailbox Sharedmailbox@domain.com), I get a list of apps. 
Some of the apps that I get when I run (Get-App -OrganizationApp) are not present when I run (Get-App -Mailbox Sharedmailbox@domain.com).
I then try to add an app (previously listed in Get-App -OrganizationApp) to the shared mailbox using (Enable-App -Mailbox SharedMailbox@domain.com -Identity "AppId")
I don't get an error, but nothing happens.

See screenshot:

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/59142439/c2f1abb4-8b82-41cb-be3d-9750d8890d7d)

Thank you 
Br

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d467ff3f-e206-3e0f-d3e1-87f79c03ba20
* Version Independent ID: a0592470-94b5-fd12-ca80-85763c181329
* Content: [Enable-App (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/enable-app?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Enable-App.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Enable-App.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@riohedfield, you should open a support ticket about this. Report back here with any information that can help improve the documentation.

**Comment by yogkumgit** [comment]
@riohedfield Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
