### ISSUE TITLE
CsPhoneNumberAssignment functions Failing in GCC High environment

### ISSUE THREAD

**Issue by andrewgsauer** [MicrosoftDocs/office-docs-powershell#11162]
We've recently begun seeing errors when trying to interact with functions with the noun CsPhoneNumberAssignment, particularly "get" and "set".

We connect to the Teams Environment "TeamsGCCH" using: Connect-MicrosoftTeams -TeamsEnvironmentName TeamsGCCH 

Connection is successful though we do see a warning: "WARNING: Invalid Teams Environment name for Migration API"

But we are able to mostly do what we need. Once we run a Get-CsPhoneNumberAssignment, we see an error for "resource not found":

> Get-CsPhoneNumberAssignment : Resource not found.
>At line:1 char:1
>+ Get-CsPhoneNumberAssignment
>    + CategoryInfo          : InvalidOperation: ({ TelephoneNumb...p = , Skip =  }:<>f__AnonymousType56`15) [Get-CsPho
>   neNumberAssignment_Get], RestException`1
>    + FullyQualifiedErrorId : NotFound,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsPhoneNumberAssignment_
>   Get

Similarly, we see the following when attempting to Set-CsPhoneNumberAssignment:

>Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNumberAssignment : Resource not found.
>At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\5.0.0\custom\Merged_custom_PsExt.ps1:1321 char:13
>             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNum ...
>    + CategoryInfo          : InvalidOperation: ({ Identity = ma...iceEnabled =  }:<>f__AnonymousType101`5) [Set-CsPho
>   neNumberAssignment_Set], RestException`1
>    + FullyQualifiedErrorId : NotFound,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsPhoneNumberAssignment_
>   Set

We've attempted on several tenants, several accounts, several computer on multiple networks.

**Comment by JensTrier** [comment]
@andrewgsauer Thanks for the feedback. These cmdlets are not available in the GCCH cloud. For phone number assignment you should be using Set-CsUser

**Comment by yogkumgit** [comment]
@andrewgsauer Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
