### ISSUE TITLE
Limits for parameters are not documented

### ISSUE THREAD

**Issue by jeremyhagan** [MicrosoftDocs/office-docs-powershell#11168]
Through experimentation I have discovered that the ExceptIfSubjectOrBodyContainsWords parameter is limited to 128 characters. It would be great if you could include all of these limitations in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f48ae8ec-b719-c4db-c259-02e4f9e779b5
* Version Independent ID: 96f609a7-578e-5568-adb3-61f483997870
* Content: [Set-TransportRule (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-transportrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-TransportRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-TransportRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by DMoenks** [comment]
For comparison, the documentation on [Set-DlpComplianceRule](https://learn.microsoft.com/powershell/module/exchange/set-dlpcompliancerule) seems to have such limits documented for the individual parameters. It would be interesting though, if these limits are actually based on service limits, such as those listed in [Journal, transport, and inbox rule limits](https://learn.microsoft.com/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#journal-transport-and-inbox-rule-limits), as this would allow to simple reference those.

**Comment by chrisda** [comment]
@jeremyhagan, I confirmed the limit is 128 characters in Exchange 2010 to 2019 and in Exchange Online. I updated the parameter descriptions accordingly.

The same parameters (and some other related ones) in New/Set-InboxRule have a limit of 255 characters, so I updated the information in those parameter descriptions as well.

Thanks for the feedback.

Closing
