### ISSUE TITLE
Issue with connection information for REST-based connections

### ISSUE THREAD

**Issue by devyodamaster** [MicrosoftDocs/office-docs-powershell#11170]
Microsoft quality is equal  les than 0.
As a proof:

Documentation:
<html><body>
<p>Scenarios where you can use <strong>Get-ConnectionInformation</strong> are described in the following table:</p>
<div class="has-inner-focus">

Scenario | Expected output
-- | --
Run before a Connect-ExchangeOnline or Connect-IPPSSession command. | Returns nothing.
Run after a Connect-ExchangeOnline or Connect-IPPSSession command that connects in remote PowerShell mode. | Returns nothing (use Get-PSSession).
Run after Connect-ExchangeOnline or Connect-IPPSSession command that connects in REST API mode. | _Returns one connection information object._
Run after multiple REST-based Connect-ExchangeOnline or Connect-IPPSSession commands. | Returns a collection of connection information objects.
Run after multiple Connect-ExchangeOnline or Connect-IPPSSession commands that connect in remote PowerShell mode and REST API mode. | _Returns one connection information object for each REST-based session._

</div>
</body>
</html>

**If you already have connection and want to create another one and you use  "Run after Connect-ExchangeOnline" you will recive all connections not ONE as you mentioned "Returns one connection information object."**

**Who created that documentation?
Why "Connect-ExchangeOnline" not giving output like "Get-ConnectionInformation" on creating connection?
Are you testing before submitting our updates?**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module and V3 module](https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by DMoenks** [comment]
Your scenario doesn't seem to match scenario 3 from the table provided in the documentation, as you opened at least two connections based on your description, but would better fit scenario 5, where **Get-ConnectionInformation** _returns one connection information object for each REST-based session_. The table could possibly be shortened for clarity, but it seems to be technically correct.

The question _Why "Connect-ExchangeOnline" not giving output like "Get-ConnectionInformation" on creating connection?_ might better be directed at the email address provided in section [Report bugs and issues for the Exchange Online PowerShell module](https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#report-bugs-and-issues-for-the-exchange-online-powershell-module) though.

**Comment by chrisda** [comment]
DMoenks is correct in his assessment of the documentation and the path forward to point out the issue.

Closing.
