### ISSUE TITLE
-PreviewOnly parameter does not work as described

### ISSUE THREAD

**Issue by gtimread** [MicrosoftDocs/office-docs-powershell#11177]
The -PreviewOnly parameter does not appear to work as described. Using this parameter returns output for the discovered meetings indicating that they have actually been queued for cancellation. e.g. `Remove-CalendarEvents -Identity user1@contoso.com -CancelOrganizedMeetings -QueryWindowInDays 1095 -PreviewOnly -Verbose` returns for example

```powershell
Confirm
Are you sure you want to perform this action?
The meeting(s) will be canceled and removed from the calendar. This action cannot be undone.
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
```

Entering Y to display the results returns output that lists the discovered meetings, but suggests that they have actually been queued for cancellation (for example):
 "The recurring meeting with subject "lunch" has been queued for cancellation."

Running Remove-CalendarEvents a second time against the same mailbox _without_ the -PreviewOnly parameter e.g. `Remove-CalendarEvents -Identity user1@contoso.com -CancelOrganizedMeetings -QueryWindowInDays 1095 -Verbose`, returns no results - indicating that the previously discovered meetings were indeed cancelled when -PreviewOnly was used.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e391a2ce-71ef-bf07-c9bb-0d8cb322f57e
* Version Independent ID: 5e1a15c4-4f78-c1df-e119-901340e720f6
* Content: [Remove-CalendarEvents (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/remove-calendarevents?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-CalendarEvents.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Remove-CalendarEvents.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gtimread, you should open a support ticket about this. Logically, the PreviewOnly parameter should behave as described.
