### ISSUE TITLE
Not able to get all data back, getting timeoutissue

### ISSUE THREAD

**Issue by davidbeiler1** [MicrosoftDocs/office-docs-powershell#11174]
Hi,

We have been using this code for quite some time up until a week ago it stopped working, we are now receiving a timeout issue when we try to get back more then 20 days worth of data.

```powershell
Get-module -Name ExchangeOnlineManagement -ListAvailable
Install-Module -Scope CurrentUser -Name ExchangeOnlineManagement -Force
$TLS12Protocol = [System.Net.SecurityProtocolType] 'Ssl3 , Tls12'
[System.Net.ServicePointManager]::SecurityProtocol = $TLS12Protocol
Register-PSRepository -Default -ErrorAction SilentlyContinue
Connect-IPPSSession -UserPrincipalName username -ErrorAction SilentlyContinue


$StartDate = (Get-Date).AddDays(-20).ToShortDateString()
$EndDate = (Get-Date).AddDays(-1).ToShortDateString()
$PageSize = 5000
$respage = ''
$lastpage = $false
$list = [System.Collections.ArrayList]::new() 
[parameter(Position=0, Mandatory=$true)][AllowNull()][System.Collections.ArrayList] $list
$list.clear()
while ($lastpage -ne $True){

$res = Export-ActivityExplorerData -StartTime $StartDate -EndTime $EndDate -PageSize $PageSize -PageCookie $respage -OutputFormat csv

$results = $res.ResultData | ConvertFrom-Csv -ErrorAction SilentlyContinue
    
    $respage = $res.Watermark 
    $lastpage = $res.LastPage
    $null = $list.Add($res.ResultData)
    Write-Host $lastpage
    }

try{
$list | convertFrom-csv -ErrorAction SilentlyContinue | Select-Object Happened, User, FilePath, FileExtension, FileSize, PolicyName, RuleName, RuleActions, RecordIdentity, Workload | Export-Csv -Path "D:\Tableau Output\M365 DLP Activity Explorer.csv" -NoTypeInformation 
}catch{"Script did not Complete"
}
write-host $res.TotalResultCount
```

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/142458387/250e8089-99eb-4a06-b8c1-a25a1d23626d)

**Comment by chrisda** [comment]
@davidbeiler1, you should open a support ticket about this.

**Comment by davidbeiler1** [comment]
like with our microsoft rep?

**Comment by chrisda** [comment]
Sure. Or use the **Help & support** link in the admin center at <https://admin.microsoft.com>:

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/33166947/58d24e7c-a054-4161-a150-96440494e774)

**Comment by chrisda** [comment]
Not to my knowledge. A support ticket is the best way to go.

**Comment by LanstarGermany** [comment]
i have learned today that when using EXO v3.3 the problem does not occur again, can you confirm ? https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#rest-api-connections-in-the-exo-v3-module  and  https://www.powershellgallery.com/packages/ExchangeOnlineManagement/3.3.0

**Comment by yogkumgit** [comment]
@davidbeiler1 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
