### ISSUE TITLE
Use Azure managed identities to connect to Exchange Online PowerShell

### ISSUE THREAD

**Issue by OursonBleu** [MicrosoftDocs/office-docs-powershell#11182]
If you're using exo 3.0 and up with an automation account. The module has non mentioned dependencies with packagemanagement and powershellget.

These modules are required for Connect-ExchangeOnline command to work in an automation account.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba626583-a2d3-00ba-6b8e-69e89e7af74c
* Version Independent ID: 4da53073-acc6-c813-8a2d-c0200f9494bf
* Content: [Use Azure managed identities to connect to Exchange Online PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/connect-exo-powershell-managed-identity?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-exo-powershell-managed-identity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/connect-exo-powershell-managed-identity.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@OursonBleu, REST-based connections (all connections after ~July 15, 2023) require PowerShellGet and PackageManagement:

https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#powershellget-for-rest-based-connections-in-windows

> [REST-based connections](https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#updates-for-the-exo-v3-module) in Windows require the PowerShellGet module, and by dependency, the PackageManagement module. Consideration for these modules is more for PowerShell 5.1 than PowerShell 7, but all version of PowerShell benefit from having the latest versions of the modules installed. For installation and update instructions, see [Installing PowerShellGet on Windows](https://learn.microsoft.com/powershell/scripting/gallery/installing-psget).

Unclear to me if an additional call-out is required for MI connections.

**Comment by OursonBleu** [comment]
@chrisda I got a bit too many customers not knowing that they need both modules to make it work.

The problem is also coming from an update of exo 2.0 to 3.+ and RPS being disabled/removed.

People only see the need to update the modules and that it should work.

The dependency/need is also not listed on the module
https://www.powershellgallery.com/packages/ExchangeOnlineManagement/3.2.0

**Comment by chrisda** [comment]
@OursonBleu, I added call-outs anywhere and everywhere for the PowerShellGet/PackageManagement dependency with REST API connections per the referenced pull request.

Thanks for the feedback.

Closing
