### ISSUE TITLE
Attributes not returned

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#11193]
If I send this

Get-CsCallQueue | Select Identity, NoAgentSharedVoicemailAudioFilePromptFileName

I get the following

Identity                             NoAgentSharedVoicemailAudioFilePromptFileName
896fd4e4-6d18-495a-964f-5771ddacba5d
7109ec5e-b581-4a11-ad3b-653f4992d5b1
69967e78-33cc-477c-8f89-bb6f7d7567cc
e4a35e08-edcf-44a7-b082-a2754448f182
3bb3addb-81da-411f-b57b-3c6257e8a72a
13f70a2a-b515-420a-b276-ff5053a55f4a
fbcaed5e-9fa7-4298-a756-07980a9ec058
b1638f57-55e2-4110-933d-d211388bb18b
55bf155a-c7bf-4519-97eb-10876b3f82f5
51cee67b-4c94-4d6a-874d-75fa06924af0
a9af4823-f9ca-47e7-99a7-6caea2b9f563
8b86d7e3-c39e-4e5e-8537-486f7fe7ccf2
0db26a7b-486d-437a-b1f8-3eda320e8271
efcdc6c4-219d-410d-b786-76996bbaf8b1
0d4577f5-dfb4-4bd1-843c-c29a5c3d38e2
55880154-1db3-462f-86ef-1d339fe81a7e
d2187857-4011-41b2-b44a-2019ee167526
a9a46bb4-8fc6-41be-af07-91d8f193b334
878a2726-9f42-432f-8200-39811fe7baed
c41c5c99-1c8e-4c85-a245-ae58f5bd1c61
1e6cf2c7-ebd7-4391-bd6e-1d6f05b9ba69
ccedc7ff-bcb3-4bed-8561-cdd9d8162a23
9e9b53ea-2245-4e86-b646-8079dede7abd

But if I specify a specific record

Get-CsCallQueue -Identity fbcaed5e-9fa7-4298-a756-07980a9ec058 | Select Identity, NoAgentSharedVoicemailAudioFilePromptFileName

I see this attribute

Identity                             NoAgentSharedVoicemailAudioFilePromptFileName
fbcaed5e-9fa7-4298-a756-07980a9ec058 Alarm01.wav

It seems to be all the file name attributes so far and happens in versions 5.2.0 and 5.5.0 of the MicrosoftTeams module

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2523879-a846-25cf-c296-1f8b27b8c8dd
* Version Independent ID: 9a704476-5542-7035-b2fd-4463dbfa755f
* Content: [Get-CsCallQueue (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/get-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@get-itips

**Comment by CLYVR** [comment]
@get-itips Sorry for my delay.  Looks like a bug.  I've created a bug VSO item for the team:

https://skype.visualstudio.com/DefaultCollection/SBS/_workitems/edit/3417244

**Comment by get-itips** [comment]
Thanks @CLYVR 
Closing this as it isn't a documentation issue.
