### ISSUE TITLE
Connect-MicrosoftTeams -UseDeviceAuthentication is undocumented

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/office-docs-powershell#11190]
PowerShell Core 7.3.6
Microsoft Teams PS module 5.4.0

If you open a PS session from the Azure Portal, you're asked to use
> Connect-MicrosoftTeams -UseDeviceAuthentication

But these do not give any information on this feature:
> Get-Help Connect-MicrosoftTeams -Full
> Get-Help Connect-MicrosoftTeams -Online

The parameter exists and works, it will even be discovered if you use tab completion.

**Comment by get-itips** [comment]
Thanks for your feedback!
