### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by bwilsonms** [MicrosoftDocs/office-docs-powershell#11197]
This is missing several parameters.
This has a total of 9 settings that can be applied.
AllowedQuestionTypesMode
AllowedTownhallRecordingPublishTypes
AllowedWebinarRecordingPublishTypes
AllowEmailEditing
AllowEventIntegrations
AllowTownhalls
AllowWebinars
Description
EventAccessType

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e62daee4-40e0-caef-0923-ad81c92dd24c
* Version Independent ID: 9090cecf-6d21-071f-f0d7-af1255e7b320
* Content: [Set-CsTeamsEventsPolicy (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/set-csteamseventspolicy?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
@navirdee I'm working on this
