### ISSUE TITLE
Federation limit?

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/office-docs-powershell#11195]
Is there a limit on the number of domains that can be added to the AllowedDomains list?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06796aa5-dd45-a0e9-b6f1-c2786abd8036
* Version Independent ID: 1ef8e42a-4405-5e99-b2ac-547d60b53a70
* Content: [Set-CsTenantFederationConfiguration (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by shivtorov** [comment]
@buildbod, in my tenant when using MicrosoftTeams module v.5.5.0, the limit for AllowedDomains is 4000 elements.

```powershell
$list = New-Object Collections.Generic.List[String]
1..4000 | foreach-object { $list.add("domain$_.com") }
Set-CsTenantFederationConfiguration -AllowedDomainsAsAList $list
```

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/31003608/d139241f-a17a-47c3-b792-3dba6027a225)

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/31003608/991ae860-fee3-4b39-a9b3-beb9065f3298)

**Comment by buildbod** [comment]
Thought as much. It would be good to get the amount listed in the documentation and the limits for the service.




CONFIDENTIAL

**Comment by get-itips** [comment]
A proposal to document that limit was already submitted here https://github.com/MicrosoftDocs/office-docs-powershell/pull/11205 if it gets approval, it will be on the article. Thank you

**Comment by nbgbe2** [comment]
@shivtorov thanks for sharing that detail.

**Comment by yogkumgit** [comment]
@buildbod PR is merged. Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
