### ISSUE TITLE
What is the definition of OCSADApplicationContact?

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1120]
Where can I find the definition of OCSADApplicationContact?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efc4a20e-f34b-f8e3-0f4b-758e1d7c58eb
* Version Independent ID: 534bce43-a0af-a223-8fc8-b7bdb0a32a83
* Content: [New-CsTrustedApplicationEndpoint (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/New-CsTrustedApplicationEndpoint?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTrustedApplicationEndpoint.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTrustedApplicationEndpoint.md)
* Service: **skypeforbusiness-powershell**
* Product: **unspecified**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
Added to backlog to address. Closing this one out.

**Comment by get-itips** [comment]
@nsshommo Thanks for your feedback, does the definition on the _Description_ section of the article 

> A trusted application endpoint is an Active Directory contact object that enables routing of calls to a trusted application

is what you are looking for?

**Comment by kenwith** [comment]
@get-itips - yes that is great! I think this one can be closed out. If you see any issues by @nsshommo then those are ones he brought forward from the old TechNet system. He is on our team in the Teams channel now too. :) So for these he opened he wasn't the one that originally submitted it.. it was submitted anonymously to the old TechNet system before we moved everything to open source on GitHub. @AndreaBarr - I think this one can be closed out in the internal backlog. Thanks!

**Comment by get-itips** [comment]
Great! Thank you.

**Comment by AndreaBarr** [comment]
@kenwith Okay I closed it in the backlog.
