### ISSUE TITLE
Wording is incorrect for command argument

### ISSUE THREAD

**Issue by Shoehorner** [MicrosoftDocs/office-docs-powershell#11218]
There are some grammatical errors in the -HiddenFromExchangeClientsEnabled property description text. 

**This is how the text currently reads:**

- To enable this setting, you don't need to specify a value with this switch. The Microsoft 365 Group is hidden from Outlook experiences. The group isn't visible in the Outlook left-hand navigation and isn't be visible in the global address list (GAL). The group name won't resolve during the creation a new message in Outlook. The group can still receive messages, but users can't search for or browse to the group in Outlook or Outlook on the web. Users also can't find the group by using the Discover option in Outlook on the web. Additionally, the HiddenFromAddressListsEnabled property will also be set to true to prevent the group from showing in the GAL and in the Offline Address Book (OAB).
- To disable this setting, use this exact syntax: -HiddenFromExchangeClientsEnabled:$false. The Microsoft 365 Group is not hidden from Outlook experiences. The group will be visible in the GAL and other address lists. This is the default value.
- If Microsoft 365 Groups are hidden from Exchange clients, users cannot view the option to subscribe or unsubscribe to a Microsoft 365 Group.

**Here is how it should read:**

- To enable this setting, you don't need to specify a value with this switch. The Microsoft 365 Group is hidden from Outlook experiences. The group isn't visible in the Outlook left-hand navigation and the group isn't visible in the global address list (GAL). The group name won't resolve during the creation of a new message in Outlook. The group can still receive messages, but users can't search for or browse to the group in Outlook or Outlook on the web. Users also can't find the group by using the Discover option in Outlook on the web. Additionally, the HiddenFromAddressListsEnabled property will also be set to true to prevent the group from showing in the GAL and in the Offline Address Book (OAB).
- To disable this setting, use this exact syntax: -HiddenFromExchangeClientsEnabled:$false. The Microsoft 365 Group will then not be hidden from Outlook experiences. The group will be visible in the GAL and other address lists. This is the default value.
- If Microsoft 365 Groups are hidden from Exchange clients, users cannot view the option to subscribe or unsubscribe to a Microsoft 365 Group.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80326e44-6beb-8983-57ab-8333608c504b
* Version Independent ID: 8962c0dc-72a3-208a-33de-6a89cd56b6fc
* Content: [Set-UnifiedGroup (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Shoehorner, fixed.

In the future, you too can make fixes like this yourself without opening an issue first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
