### ISSUE TITLE
Release-QuarantineMessage -Delete

### ISSUE THREAD

**Issue by grzegorzwierzbicki** [MicrosoftDocs/office-docs-powershell#11210]
Release-QuarantineMessage -? reports that there is now a -Delete switch that is not described anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d772e8c6-e3d4-f09d-dce5-c17567d812d1
* Version Independent ID: 042cd41c-b87f-9363-4757-1dc250496b5e
* Content: [Release-QuarantineMessage (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/release-quarantinemessage?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Release-QuarantineMessage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Release-QuarantineMessage.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@grzegorzwierzbicki, I ran the following command in a plain Microsoft 365 E5 tenant in both Exchange Online PowerShell and Security & Compliance PowerShell and saw no Delete switch:

```powershell
PS C:\Users\chrisda> (Get-Command Release-QuarantineMessage).parameters.keys | Sort-Object
ActionType
AllowSender
Confirm
Debug
EntityType
ErrorAction
ErrorVariable
Force
Identities
Identity
InformationAction
InformationVariable
OutBuffer
OutVariable
PipelineVariable
ReleaseToAll
ReportFalsePositive
User
Verbose
WarningAction
WarningVariable
WhatIf
```

If you run that same command, do you see it?

**Comment by yogkumgit** [comment]
@grzegorzwierzbicki Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
