### ISSUE TITLE
Filter1 @("FilePath", "\\fs1\common\") error 

### ISSUE THREAD

**Issue by terrycvu** [MicrosoftDocs/office-docs-powershell#11214]
I use command to search for sensitive info type it has error
Export-ActivityExplorerData: |System.ArgumentException|Invalid Filter Name

here is command:

```powershell
Export-ActivityExplorerData -StartTime (Get-Date).add(-7) -EndTime (Get-Date) -Filter1 @("FilePath", "\\FS1\FIN") -OutputFormat JSON -PageCookie Watermark -PageSize 5000
Error:
Export-ActivityExplorerData: |System.ArgumentException|Invalid Filter Name
```

Do you have any method to filter "FilePath" and "SensitiveInfoTypeData"?

**Comment by terrycvu** [comment]
if I did not use Filter I received error with "Invalid length for a Base-64 char array or string."
Command:
Export-ActivityExplorerData -StartTime (Get-Date).add(-7) -EndTime (Get-Date) -OutputFormat JSON -PageCookie Watermark -PageSize 5000
Error:
Export-ActivityExplorerData: |System.FormatException|Invalid length for a Base-64 char array or string.

**Comment by terrycvu** [comment]
The issue above link to Microsoft Purview Active Explore

**Comment by chrisda** [comment]
@terrycvu, you should open a support ticket. Report back here with any findings that can help improve the documentation.
