### ISSUE TITLE
Error in New-PSSession with OAuth token code snippet

### ISSUE THREAD

**Issue by z0diack** [MicrosoftDocs/office-docs-powershell#11217]
The code snippet includes: 
```
$oauthTokenAsPassword = ConvertTo-SecureString "<EncodedOAuthToken>'  -AsPlainText -Force

$o365cred = New-Object System.Management.Automation.PSCredential ("admin@contoso.onmicrosoft.com", $oauthTokenAsPassword)

$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/PowerShell-LiveID/?DelegatedOrg=delegated.onmicrosoft.com&BasicAuthToOAuthConversion=true&email=SystemMailbox{bb558c35-97f1-4cb9-8ff7-d53741dc928c}@delegated.onmicrosoft.com -Credential $o365cred -Authentication Basic -AllowRedirection

Import-PSSession $Session
```

At the `<EncodedOAuthToken>` it uses " to start and ' to close, so the rest of the snippet is shown as in quotation marks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps#step-2-connect-and-authenticate)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@z0diack, fixed.

In the future, you too can make fixes like this yourself without opening an issue first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedbck.

Closing
