### ISSUE TITLE
Maximum number of entries supported by the -Members parameter in New-DistributionGroup cmdlet

### ISSUE THREAD

**Issue by stukey** [MicrosoftDocs/office-docs-powershell#11230]
Please update the documentation for New-DistributionGroup cmdlet to specify the maximum number of entries that can be added via the -Members parameter when creating a new distribution group using the New-DistributionGroup Exchange Online cmdlet. The documentation for the Update-DistributionGroupMember cmdlet specifies a maximum of 10,000 entries, but this is not documented for the New-DistributionGroup cmdlet.

**Comment by chrisda** [comment]
@stukey, OK, done.

Thanks for the feedback.

Closing

**Comment by stukey** [comment]
Thanks!
