### ISSUE TITLE
Get-ComplianceSearchAction -identity returns null reference

### ISSUE THREAD

**Issue by couradeus** [MicrosoftDocs/office-docs-powershell#11237]
### Background
Using EXO Unattended workflow to connect to Connect-IPPSSession, and followed the official articles to create a service principal associated with the Azure App, which was subsequently added to eDiscovery manager. 

Using such an approach, the identity that creates the search/exports will be named FFO, and when running Get-ComplianceSearchAction -Identity <ActionNames>, the existing actionnames that were not created by FFO will return a null exception. This problem can hit users who are transiting their security and compliance shell to the rest module. since their old mode of access would be of a different identity. 

Running Get-ComplianceSearchAction, with no switches returns all results. But the filtering can work by passing the whole set of results and using where. e.g Get-ComplianceSearchAction | where {$_.searchname -eq '<ActionName>'}

This could be potentially due to the service principal only having the permission to eDiscovery Manager, since this role only allows access to search/actions created by itself. 

However, elevating the service principal to eDiscovery Administrator doesn't help. It seem that service principal isn't working well with eDiscovery Administrator, because when running the command to remove the service principal, e..g Remove-RoleGroup - Member "<Service Principal Name>", there was an error saying user does not exist when it does. 

Microsoft should look into making the service principal work with eDiscovery Administrator

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5742b678-0ea4-720a-e598-1a943b94bca5
* Version Independent ID: b74df581-0143-996a-b3b4-663f31d2eb71
* Content: [Get-ComplianceSearchAction (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-compliancesearchaction?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@couradeus, you should open a support ticket about this.

**Comment by yogkumgit** [comment]
@couradeus Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
