### ISSUE TITLE
Connect-MicrosoftTeams -AccessTokens  is not working 

### ISSUE THREAD

**Issue by bbteam17** [MicrosoftDocs/office-docs-powershell#11251]
I am trying connect  with  Access tokens   , 
Step by Step : 

Env: 

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Linux 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
5.5.0                MicrosoftTeams                      PSGallery            Microsoft Teams cmdlets module for Windows PowerShell and PowerShell Core.…

Create new app registration  
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/32478068/8829ef4f-dcda-468f-b623-8bbe80f67f85)

then try  
with below script 
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/32478068/454867f3-2b40-4126-9649-88962c2950bf)

result as below 
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/32478068/b2f4fc2f-ab86-42ce-af19-b6b41c728574)

**_Where am I making a mistake?_**

**Comment by get-itips** [comment]
Hello @bbteam17 
Here we are limited to documentation issues and fixes, please be sure to follow the steps here https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication in case you continue to have issues it is advised to open a support request from your tenant. Thank you

**Comment by bbteam17** [comment]
Hi  @get-itips ,
 thanks for  your answer,
 But  I am already testing it according to the instructions in the link you gave.  

I am trying  "Connect using Access Tokens:" steps, 

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/32478068/1c6247bd-9304-4662-bef0-42bf147bbf1c)

in your doc ,  3. and 4.  requirements (self sign SSL cert)    I think we don't need those   for  my  test way.   is it still need ? 

Another question,  I already  assign   "Teams Administrator" role  to my app registration.  is there something wrong ? 

  
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/32478068/4b3f9da0-088d-48fa-8294-0d29238317c8)

 

I can see  like above   in teams administrator  but    when I go to   registration page then   open Roles and administrators   I cant  see  " Teams Administrator " role  in there .  

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/32478068/8bec2f92-a0bb-41c9-8625-bde35487efa1)


but still same result .
thx &regards,

**Comment by get-itips** [comment]
You will still need to follow every step including certificate.

**Comment by bbteam17** [comment]
Hi Again ,  

I tried   as below , 
create new  cert  via , 
`sudo openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout ./pwshCert/pwsh.key -out ./pwshCert/pwsh.cert.pem  -config config`

also add trusted cert 
`sudo cp ./pwshCert/pwsh.cert.pem  /usr/local/share/ca-certificates/
sudo update-ca-certificates `


 

then upload to  my app reg.
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/32478068/60feff37-e038-4f65-90e9-12643b028939)

then tried both way  , 

`echo  "with cert"
Connect-MicrosoftTeams -Certificate ./cert/pwshCert/pwsh.cert.pem     -ApplicationId $ApplicationID -TenantId $TenantID
echo "______________________________________________________________________________"


echo "with -CertificateThumbprint"

Connect-MicrosoftTeams -CertificateThumbprint $thumpprint -ApplicationId $ApplicationID -TenantId $TenantID

echo "______________________________________________________________________________"`

result  is 
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/32478068/4a4a9f25-5b99-4839-8d42-7c4cf057f916)

any idea ?
thx ,

**Comment by bbteam17** [comment]
I create new  App registration  then   try  all  step by step , and now its working  ... thanks a lot. 

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/32478068/73efb33f-978b-4212-b723-990c0484f2db)
