### ISSUE TITLE
AllowCreatePrivateChannels is missing

### ISSUE THREAD

**Issue by yaozkiierobin19** [MicrosoftDocs/office-docs-powershell#11258]
The parameter for AllowCreatePrivateChannels is missing, even though it exists in the Teams PowerShell Module.

This parameter was present before on the documentation, but is now missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fff5e98-436e-f79c-e176-767f8de772e5
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Thanks for your feedback!
