### ISSUE TITLE
Possible Memory leak? EXO v3 PS in Azure Functions

### ISSUE THREAD

**Issue by iyerusad** [MicrosoftDocs/office-docs-powershell#11264]
Recently migrated from powershell _EXO v2_ to **EXO v3** within Azure Functions V4 hosted environment. 

The last and only change git commit is very small -- just a few lines of code changing to EXO v3 as required module and using newer v3 approach for checking if connection active -- remainder of code is same as before. The commit screenshot below

Run two daily Azure Functions, one of which uses fairly simple `Get-Mailbox` command. Since upgrading to Exo V3 the function will run a couple times but after a week or two will start crashing with Out of Memory errors. Similar issues with other Azure Function that uses `Get-DistributionGroup` -- complains of memory issues within week or two.

Looking at the Azure App Service Plan (will refer to as "VM"), the logs show the memory spiking to ~80% and then crashing. Thinking this might of had something to do with dedicated instance's relatively little RAM, I upgraded the hosting instance to VM that has double the CPU and RAM allocation -- once again job ran daily without issue for 1-2 weeks and now is again crashing seemingly consistently. The now larger RAM of VM shows same as before - RAM is spiking to upper limit and seemingly crashing (seems like possible memory leak).

I suspect restarting the VM will clear up these issues for 1 to 2 weeks, but have avoided restarting it for now in case needed for debugging.

**Thoughts? Additional info needed?**

Error messages (in Azure Function logs):
---
> WARNING: Connecting to ExchangeOnline -> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. at Newtonsoft.Json.JsonTextReader.PrepareBufferForReadData(Boolean append, Int32 charsRequired) at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired) at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote) at Newtonsoft.Json.JsonTextReader.ParseValue() at Newtonsoft.Json.JsonTextReader.Read() at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments) at Newtonsoft.Json.Linq.JTokenWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments) at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Microsoft.Exchange.Management.ExoPowershellSnapin.NewEXOModule.ProcessRecord() at System.Management.Automation.Cmdlet.DoProcessRecord() at System.Management.Automation.CommandProcessor.ProcessRecord()

> Result: Failure Exception: Connecting to ExchangeOnline -> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. at Newtonsoft.Json.JsonTextReader.PrepareBufferForReadData(Boolean append, Int32 charsRequired) at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired) at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote) at Newtonsoft.Json.JsonTextReader.ParseValue() at Newtonsoft.Json.JsonTextReader.Read() at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments) at Newtonsoft.Json.Linq.JTokenWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments) at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Microsoft.Exchange.Management.ExoPowershellSnapin.NewEXOModule.ProcessRecord() at System.Management.Automation.Cmdlet.DoProcessRecord() at System.Management.Automation.CommandProcessor.ProcessRecord() Stack: at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input) at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke) at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync) at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings) at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings) at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings) at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings) at System.Management.Automation.PowerShell.Invoke[T]() at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellExtensions.InvokeAndClearCommands[T](PowerShell pwsh) in D:\a\_work\1\s\src\PowerShell\PowerShellExtensions.cs:line 45 at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeNonOrchestrationFunction(DurableController durableController, IDictionary outputBindings) in D:\a\_work\1\s\src\PowerShell\PowerShellManager.cs:line 301 at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeFunction(AzFunctionInfo functionInfo, Hashtable triggerMetadata, TraceContext traceContext, RetryContext retryContext, IList`1 inputData, FunctionInvocationPerformanceStopwatch stopwatch) in D:\a\_work\1\s\src\PowerShell\PowerShellManager.cs:line 230 at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.InvokeFunction(AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch, InvocationRequest invocationRequest) in D:\a\_work\1\s\src\RequestProcessor.cs:line 336 at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequestImpl(StreamingMessage request, AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch) in D:\a\_work\1\s\src\RequestProcessor.cs:line 308

**Azure Function:** `msExch-Get-MailBox`
---
```powershell
using namespace System.Net
param($Request)
$funcName = "msExch-Get-MailBox"

##########################
#   Starting Function:   #
##########################
Write-Information "Started Function: $funcName"

function errorHandler{
  #Version: errorHandlerPS-0.1
  param (
    [Parameter(Position = 0, Mandatory=$true)][Object[]]$errorObj,
    [Parameter(Position = 1, Mandatory=$false)][string]$prefix,
    [Parameter(Position = 2, Mandatory=$false)][switch][Alias("fatal")]$exception
  )

  $errorMsg = "$errorObj"
  if ($prefix) {$errorMsg = "$prefix $errorMsg"}
  if ($exception) {$exceptions.Add($errorMsg) | Out-Null}
  else {$errors.Add($errorMsg) | Out-Null}
  Write-Warning $errorMsg
}
function noErrors{
  #Version: noErrorsPS-0.1
  if ($errors.count -eq 0 -and $exceptions.count -eq 0) {return $true}
  else {return $false}
}

$errors = [System.Collections.ArrayList]@()
$exceptions = [System.Collections.ArrayList]@()
$appRegistrationID = "**snipped**"
$tenantDomain = "**snipped**.onmicrosoft.com"
$certName = "ExchangeAZFuncAuth";
$isConnected = $false;
$mailboxes = $null;
$result = $null;

# Locate App Registration and Certificate
$cert = Get-ChildItem -Path "Cert:/**/MY" -Recurse | Where-Object {$_.Subject -Match "$certName"};
if ($cert) {Write-Host "Located auth cert, thumbprint: $($cert.thumbprint)"}
else {errorHandler -err "FATAL: Was unable to find authentication certificate (name: '$certName')" -fatal}

# ExchangeOnline: Connect to session
if (noErrors -and $cert -and $cert.thumbprint) {
  Write-Information "Importing Module: ExchangeOnlineManagement"
  Import-Module ExchangeOnlineManagement

  if (([bool](Get-Command -Name "Connect-ExchangeOnline" -ErrorAction SilentlyContinue))) {
    try {
      Write-Information "ExchangeOnline: Connecting..."
      Connect-ExchangeOnline -Certificate $cert -AppId $appRegistrationID -Organization $tenantDomain -Showbanner:$false -EA Stop

      $isConnected = Get-AcceptedDomain

      if ($isConnected) {Write-Information " -- Connected to ExchangeOnline session."}
      else {throw " -- Failed to connect."}
    }
    catch {errorHandler -err $_.Exception -pre "Connecting to ExchangeOnline ->" -fatal}
  } else {errorHandler -err "Couldn't find command (Connect-ExchangeOnline), is the module loaded??" -fatal}
}

# ExchangeOnline: Get mailboxes
if (noErrors -and $session) {
  if (([bool](Get-Command -Name "Get-Mailbox" -ErrorAction SilentlyContinue))) {
    Write-Information "ExchangeOnline: Getting mailboxes..."
    $mailboxes = Get-Mailbox
    Write-Information " -- Finished getting mailboxes."
  } else{errorHandler -err "Couldn't find command (Get-Mailbox), is the module loaded??"}
}

# ExchangeOnline: Close the session
if ($isConnected) {
  try {
    Write-Information "ExchangeOnline: Closing session..."
    Disconnect-ExchangeOnline -Confirm:$false
    Write-Information " -- Closed."
  }
  catch {
    errorHandler -err $_.Exception -pre "ExchangeOnline: Failed to close session! ->"
  }
}

# Define the result
if ($mailboxes) {
  $result = @{
    mailboxes = $mailboxes
  }
}


######################
# Wrap up the function
######################
if ($result) {
  $httpResponse = [HttpResponseContext]@{
    StatusCode = 200
    Body = $result
  }
} elseif ((!$result) -and (noErrors)) {
  errorHandler("Unknown failure: No errors logged but function did NOT complete as expected")
}

if ($exceptions.count -gt 0) {
  Write-Error "Exit: 500; Encountered fatal error"
  $httpResponse = [HttpResponseContext]@{
    StatusCode = 500
    Body = @{
      message = "FATAL failure: server side failure"
      exceptions = $exceptions -join ', '
      errors = $errors -join ', '
    }
  }
} elseif ($errors.count -gt 0) {
  #Not 422 since no inputs, any errors = 500
  Write-Warning "Exit: 500; Encountered errors during execution"
  $httpResponse = [HttpResponseContext]@{
    StatusCode = 500
    Body = @{
      message = "Exit: 500; Encountered errors during execution"
      errors = $errors -join ', '
    }
  }
}
Write-Information "Finished Function: $funcName"

#Return/Apply the HTTP Response
Push-OutputBinding -Name Response -Value $httpResponse
if ($exceptions.count -gt 0 -or $errors.count -gt 0) {
  throw "$($exceptions -join ', ') $($errors -join ', ')" # Must throw exception for AzureFunctions to mark as failed (even 500s)
}
```

**Git commit migrating to EXO v3** (no newer commits):
---
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/25647368/a76e32e9-d54a-410a-b612-ab574dbf5601)

**Comment by chrisda** [comment]
@iyerusad, make sure you're using the latest version of the ExchangeOnlineManagement module (v3.3.0, which came out just last week).

Otherwise, you can either see how your Azure goes, or you can open a support ticket about this problem.

**Comment by iyerusad** [comment]
**Seeing failures with 3.3.0** oddly like clockwork at near or exactly 16 runs. Appears to be possible accumulating/progressive memory leak.


Previous debug:
-----
Module version within AzFuncs: **3.2.0**

**Note:** Azure Functions only allows wildcards on major versions, e.g. `Major.*` -- couldn't do `Major.Minor*` nor `Major.Minor.*`

I let the job fail consistently for a number of days **then restarted the Web App**. Here is the memory usage in the Web App metrics:
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/25647368/39d68bf4-20c8-4182-a6aa-3f6a6c16fa12)

It previously failed after ~13 days/runs. Was able to repro on 16th attempt after Web App restart and continued to crash for next few attempts.

Upped to `3.3.0`. Failed on exactly 16th run again.

**Comment by yogkumgit** [comment]
@iyerusad Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by iyerusad** [comment]
Small note: https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps
![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/25647368/89efec45-32ee-497e-9ae0-39b881eddbfc)
Points you to https://github.com/MicrosoftDocs/office-docs-powershell/issues (here).

**Comment by chrisda** [comment]
@iyerusad, duly noted.
