### ISSUE TITLE
SourceFolder accepted values doesn't include DiscoveryHoldsItems

### ISSUE THREAD

**Issue by WillMartin58** [MicrosoftDocs/office-docs-powershell#11266]
While the page specifically says that DiscoveryHoldsItems is a valid value in the text explaining what the values will return, the accepted values section only includes "DeletedItems | RecoverableItems | PurgedItems".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21b1cd9d-df2e-d4d6-52e2-d3fbdfb9db9f
* Version Independent ID: e675173d-290a-dee0-62a4-5485cf3d2570
* Content: [Restore-RecoverableItems (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/restore-recoverableitems?view=exchange-ps#-sourcefolder)
* Content Source: [exchange/exchange-ps/exchange/Restore-RecoverableItems.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Restore-RecoverableItems.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@WillMartin58, I confirmed that DeletedItems, RecoverableItems, and PurgedItems are valid values in on-premises Exchange Server and the cloud, while DiscoveryHoldsItems is valid only in the cloud.

That **Accepted values:** YAML property for a parameter is interesting, but shouldn't be the definitive word on acceptable values (that's what the description is for). Out of 14,000+ parameters in Exchange-related cmdlets, only 48 have a value for that property. Some of that has to do with the age of the cmdlet/parameter and when it was documented (old = we didn't used to pick up that value, even if it was available).

Anyway, I cleaned up the SourceFolder description in Get-RecoverableItems and Restore-RecoverableITems, and I removed the **Accepted values:** property from the YAML block.

Thanks for the feedback.

Closing
