### ISSUE TITLE
Missing value 'Shared' for parameter -Type

### ISSUE THREAD

**Issue by mrjulian** [MicrosoftDocs/office-docs-powershell#1126]
Don't know if this is the right place but I would like to ask if there is planned an option to convert remote user mailboxes to remote shared mailboxes with the parameter "-Type" in future?

Regards,
Julian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f329d9dd-6a2f-1b04-6cfe-40183d03826e
* Version Independent ID: cf7fa5f9-45f6-49d3-29e0-aa3aef6ad602
* Content: [Set-RemoteMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/set-remotemailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/Set-RemoteMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/Set-RemoteMailbox.md)
* Service: **exchange-powershell**
* Product: **unspecified**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nsshommo** [comment]
@mrjulian Thanks for your valuable feedback. We will get back to you as early as possible.

**Comment by chrisda** [comment]
@mrjulian, currently, the available values for the Type parameter on Set-RemoteMailbox are Regular, Room, and Equipment. Do you have specific information that a new 'Shared' value is coming? Is this new value available in your environment?

Thanks for the feedback

**Comment by mrjulian** [comment]
@chrisda, I don't have information about a new value for this parameter. I am just wondering why such an important option is missing.

**Comment by Mike-Crowley** [comment]
There is now a -shared parameter but only revealed when you run /prepareAD from the latest CU. See here for detail: https://support.microsoft.com/en-us/help/4133605/cmdlets-to-create-modify-remote-shared-mailbox-in-on-premises-exchange

**Comment by chrisda** [comment]
@mrjulian, @Mike-Crowley, I installed CU10 on a 2016 server and ran setupe.exe /PrepareAD as described in the KB article. The new Shared switch was added to Enable-RemoteMailbox and New-RemoteMailbox, but not Set-RemoteMailbox. The command `Get-ManagementRoleEntry *\*-RemoteMailbox -Parameters Shared` returns:

```
Name                           Role                      Parameters
----                           ----                      ----------
New-RemoteMailbox              Mail Recipient Creation   {AccountDisabled, ACLableSync
Enable-RemoteMailbox           Mail Recipients           {Alias, Archive, ArchiveName,
``` 

I updated New-RemoteMailbox and Enable-RemoteMailbox, but not Set-RemoteMailbox.

Can you confirm or deny?

**Comment by chrisda** [comment]
Related to #1294 and #1295.

**Comment by Mike-Crowley** [comment]
Per the KB, for set only, you’re supposed to use “-Type Shared”


-Mike Crowley

**Comment by chrisda** [comment]
@Mike-Crowley, well that was rather obvious. Perhaps if I actually read that KB article more closely I would have noticed. Anyway, I updated the parameter description for the Type parameter.

Thanks for the feedback.

**Comment by Mike-Crowley** [comment]
I nearly missed it myself.


-Mike Crowley

________________________________

**Comment by mrjulian** [comment]
@Mike-Crowley @chrisda, that's good news. Thanks very much!
