### ISSUE TITLE
Typo in the description of  SkipLoadingCmdletHelp paramter documentation

### ISSUE THREAD

**Issue by satyajit321** [MicrosoftDocs/office-docs-powershell#11265]
The help text for SkipLoadingCmdletHelp incorrectly captures SkipLoadingFormatData in the description instead of SkipLoadingCmdletHelp. Its not clear of we need to use both the skips or using SkipLoadingFormatData, skips both.

**-SkipLoadingCmdletHelp**
Note: This parameter is available in version 3.3.0 or later of the module.

The **SkipLoadingFormatData** switch avoids downloading the cmdlet help files for REST API connections. You don't need to specify a value with this switch.

https://learn.microsoft.com/powershell/module/exchange/connect-exchangeonline#-skiploadingcmdlethelp

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13d88f18-3cc8-5f18-8d61-ff7f5fa4e314
* Version Independent ID: 60f9a029-69f3-e65c-6816-fbd414790ce3
* Content: [Connect-ExchangeOnline (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@satyajit321, it was a copy/paste error that I fixed. One parameter doesn't affect the other (you need to use both if you don't want cmdlet output formatting and you also don't want local help files).

Thanks for the feedback.

Closing

**Comment by satyajit321** [comment]
What about the help text in the EXO module, it has the same issue as well. In ExchangeOnlineManagement 3.3.0 as well.

PS satyajit> get-module ExchangeOnlineManagement

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.3.0      ExchangeOnlineManagement            {Add-VivaModuleFeaturePolicy, Get-ConnectionInformation, G...


PS satyajit> help Connect-ExchangeOnline **-Parameter SkipLoadingCmdletHelp**

-SkipLoadingCmdletHelp [<SwitchParameter>]
    Note : This parameter is available in version 3.3.0-Preview1 or later of the module.

    The SkipLoadingFormatData switch avoids downloading the cmdlet help files for REST API connections. You don't need
    to specify a value with this switch.

    When you use this switch, you don't get local help files for any cmdlet.

    This switch doesn't work with the UseRPSSession switch.

    Required?                    false
    Position?                    named
    Default value                False
    Accept pipeline input?       False
    Accept wildcard characters?  false

**Comment by chrisda** [comment]
@satyajit321, the help file is locked into that version of the module. The next release of the module (likely, a 3.4.0 Preview release) will have the updated help. We can't update help in the current v3.0.0 version without re-releasing the module. The web version of help is always the single source of truth.
