### ISSUE TITLE
Set-CsTeamsCallingPolicy identity?

### ISSUE THREAD

**Issue by scerazy** [MicrosoftDocs/office-docs-powershell#11276]
PS C:\WINDOWS\system32> Set-CsTeamsCallingPolicy -AutoAnswerEnabledType Enabled

cmdlet Set-CsTeamsCallingPolicy at command pipeline position 1
Supply values for the following parameters:
Identity:

What identity would that be?
There should be none required:
https://learn.microsoft.com/en-us/microsoftteams/set-up-auto-answer-on-teams-android

**Comment by shivtorov** [comment]
@scerazy, `-Identity` is the name of the policy, e.g. `Global`.
See examples https://learn.microsoft.com/powershell/module/skype/set-csteamscallingpolicy
