### ISSUE TITLE
Support requested for en_us as an alternate language to the site

### ISSUE THREAD

**Issue by samyaktelsang** [MicrosoftDocs/office-docs-powershell#1128]
While adding an alternate language to a site as a site admin, choosing Spanish requires me to have a es_es file. 
However, I am looking to add an es_us file to my site.
Office as well as SharePoint do support es_us localization and I'm looking for help as to how I could add it as an alternate language to my site.

Procedure followed to add an alternate language:
Gear Icon > Site Settings > Language Settings
Check Spanish radio button

Anticipated behavior:
Page translated to spanish

Actual behavior:
Page isn't localized and is displayed in English

However, If I include the es_es translation, the feature works as expected.

**Comment by AndreaBarr** [comment]
@samyaktelsang Thank you for this feedback

I want to make sure you get the appropriate help for this page translation. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
