### ISSUE TITLE
ModerateMessageByUser parameter is not accepting string arrays

### ISSUE THREAD

**Issue by BW-Pega** [MicrosoftDocs/office-docs-powershell#11280]
The documentation says ModerateMessageByUser can be set to multiple moderators by using this format: `@{ModerateMessageByManager = <$true | $false>; ModerateMessageByUser = @("emailaddress1","emailaddress2",..."emailaddressN")}`.

This generates an error of `Set-DlpComplianceRule: |Microsoft.Exchange.Management.UnifiedPolicy.InvalidModerateActionException|Invalid value specified for key 'ModerateMessageByUser'`.

If I use a comma separated string instead of an array of strings, then it works. `@{ModerateMessageByManager = <$true | $false>; ModerateMessageByUser = "emailaddress1,emailaddress2,emailaddressN"}`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c915e0e-3b66-4c89-f371-c9e1cb5ea498
* Version Independent ID: d8a07eb3-3290-1b91-490a-e2ab8990e5b1
* Content: [Set-DlpComplianceRule (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-dlpcompliancerule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-DlpComplianceRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-DlpComplianceRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@BW-Pega, I updated the description of the Moderate parameter in New-DlpComplianceRule and Set-DlpComplianceRule.

Thanks for the feedback.

Closing
