### ISSUE TITLE
Inaccurate instruction.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1129]
Instructions would not support high availability if CMS is moved to a SQL AlwaysOn backend without additional steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9082d9a-5cfe-f210-c2e7-afc56226b252
* Version Independent ID: 1ad7b4fb-2c78-d0c5-d8de-2ac2c7910127
* Content: [Move-CsManagementServer (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Move-CsManagementServer?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Move-CsManagementServer.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Move-CsManagementServer.md)
* Service: **skypeforbusiness-powershell**
* Product: **unspecified**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@papandms can you help validate this issue and what needs to be updated in article? Thanks!
