### ISSUE TITLE
Missing WelcomeTextToSpeechPrompt parameter

### ISSUE THREAD

**Issue by BrianMcNeese** [MicrosoftDocs/office-docs-powershell#11297]
Appears this parameter was added to [New|Set]-CsCallQueue in module 4.9.3 but the parameter isn't documented.

For reference:
https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes
https://www.powershellgallery.com/packages/MicrosoftTeams/4.9.3

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86ade68d-5dc0-c598-a659-8b018cef3e26
* Version Independent ID: 67efa086-edb0-2828-cc14-4c245290e4f3
* Content: [Set-CsCallQueue (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
Thanks for your feedback
