### ISSUE TITLE
Get-Place documentations has missing parameters

### ISSUE THREAD

**Issue by BlackC0ffee** [MicrosoftDocs/office-docs-powershell#11290]
When using the cmdlet Get-Place Online, you also have the option to use the parameter -type, but this is not documented. There are three types: Space, Room and RoomList. Can this be added to the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d99dd69d-054a-0186-b3b8-58668c21c582
* Version Independent ID: 0995c497-8527-e42f-8f45-bb225499b239
* Content: [Get-Place (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-place?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@BlackC0ffee, added.

The addition required other changes (Identity is now optional, two different parameter sets, and I added a third example using Type).

Thanks for the feedback.

Closing
