### ISSUE TITLE
ExchangeOnlineManagement "Exception: Cannot access the variable '$HelpFileNames' because it is a private variable" when using a session configuration file

### ISSUE THREAD

**Issue by nicot4e** [MicrosoftDocs/office-docs-powershell#11306]
Using version 3.3.0 of the ExchangeOnlineManagement module and running pwsh with a configuration file I get the following error:
`Exception: Cannot access the variable '$HelpFileNames' because it is a private variable.`
ExchangeOnlineManagement version 3.2.0 has the same issue.

I've prepared a simple reproduction scenario which also shows the issue in Windows, in reality, we have a more complex configuration file and setup in Docker.
Using the attached files ([exo.zip](https://github.com/MicrosoftDocs/office-docs-powershell/files/12717175/exo.zip)) it can be reproduced by running:
`pwsh -ConfigurationFile configuration.pssc -Command ./exo.ps1`

We've experimented with overriding the Export-ModuleMember cmdlet which seems to suppress this issue but in turn causes other problems. It may have something to do with how the module is loaded when using a session configuration file.

**Comment by chrisda** [comment]
@nicot4e, you should open a support ticket about this. Report back here with any information that can help improve the documentation.
