### ISSUE TITLE
Object could not be found

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/office-docs-powershell#1131]
Example 1 above never worked for me. I would always get a message that the RulePackage could not be found, even though I could see it with the Get-DLPSensitiveInformationTypeRulePackage:

"The operation couldn't be performed because object 'ExampleRulePack' couldn't be found on 'FfoConfigurationSession'.

The workaround for me was to assign the rule pack as a variable and then pipe that to the Remove-DLPSensitiveInformationTypeRulePackage cmdlet:

$Rule = Get-DlpSensitiveInformationTypeRulePackage -Identity "ExampleRulePack"
$Rule | Remove-DlpSensitiveInformationTypeRulePackage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1deafad2-859f-ed72-964b-76a836075ddb
* Version Independent ID: 16befd27-8fcc-14bf-9500-d1a628542059
* Content: [Remove-DlpSensitiveInformationTypeRulePackage (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/remove-dlpsensitiveinformationtyperulepackage?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Remove-DlpSensitiveInformationTypeRulePackage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Remove-DlpSensitiveInformationTypeRulePackage.md)
* Service: **exchange-powershell**
* Product: **unspecified**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@terrogin, I updated the example as you described.
