### ISSUE TITLE
Confirm enabled by default for this command but not documented

### ISSUE THREAD

**Issue by justin-leopold** [MicrosoftDocs/office-docs-powershell#11311]
Title explains the feedback. This command was wrapped into a complex workflow and due to it's default confirm:$true action it took some debugging to discover why the workflow was failing to run. Could possibly be noted on the documentation page since this is not a "destructive" command.

Happy to explain further or send along a suggestion if desired. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 905b56a4-91c2-700a-4faf-a1cb66bda24a
* Version Independent ID: 0b002a83-d61f-7cbe-78db-a317d1377d8c
* Content: [Add-RecipientPermission (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/add-recipientpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Add-RecipientPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Add-RecipientPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@justin-leopold, I added the following line at the end of the Confirm description:

> This cmdlet has a built-in pause, so use `-Confirm:$false` to skip the confirmation.

Thanks for the feedback.

Closing
