### ISSUE TITLE
what is user foo?

### ISSUE THREAD

**Issue by Orta373** [MicrosoftDocs/office-docs-powershell#11328]
Something seems to be missing here.  the sentence about add user foo and then re-adding the user as owner does not work if the user is not also already in group membership of the team itself.

What does it mean when the doc says first Add-TeamChannelUser -User foo to add them to the members list, then Add-TeamChannelUser -User foo -Role Owner

it makes it sound like there is a user called foo or this is some hidden command.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd91d571-ca88-5766-2666-d6a4d34cdbed
* Version Independent ID: 2481b258-b593-e323-90f0-e9ca6e7797bf
* Content: [Add-TeamChannelUser (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Add-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by DMoenks** [comment]
As the introduction seemed to both cause confusion and duplicate part of the examples provided later on, I tried to rewrite that part for clarity
