### ISSUE TITLE
Get-Team -DisplayName still returns partial matches, contrary to the documentation

### ISSUE THREAD

**Issue by PerePasqual** [MicrosoftDocs/office-docs-powershell#11323]
Hi,

Yesterday I wrote a new comment both on 
https://github.com/MicrosoftDocs/office-docs-powershell/issues/7636 (closed)
and
https://github.com/MicrosoftDocs/office-docs-powershell/pull/7692 (closed),
but none of the team members seem to care about that.

Still neither the behaviour of Get-Team -DisplayName has been fixed or the documentation has been rewritten properly to describe what the parameter does.

The docs still reads:

"Filters to return teams **with a full match to the provided displayname**.". That's false.

And then it continues like:

"As displayname is not unique, this acts as a filter rather than an exact match. Note that this filter value is case-sensitive."

As displayname is not unique and we can have several teams with exactly the same name, that should be the only case when this command with this parameter could and should several results, but this is not an excuse for this acting "as a filter rather than an exact match". It could have been implemented not as a filter but (as wrongly stated in the docs) as an exact and in the case of not unique displayname the behaviour could and should be the same as it's now, returning several results but only for an exact match.

You want to return partial matches, then you should include the ability of using wildcards in the displayname, as "MyTeam%" or so; that's the standard behaviour elsewhere.

This buggy behaviour may potentially be affecting thousands of users that are not aware of it and are using the parameter in production environment and lead to al kind of unexpected behaviour, like happened in my case.

Not having the ability to get a team by its EXACT displayname renders the whole cmdlet unreliable / useless.

**Comment by get-itips** [comment]
Thanks for your feedback, I am proposing a better description of the actual behavior.
