### ISSUE TITLE
Get-CalendarNotification - cmdlet deprecated

### ISSUE THREAD

**Issue by bsj17** [MicrosoftDocs/office-docs-powershell#11322]
When I try to execute Get/Set-CalendarNotification it gives me error that cmdlet has been deprecated. Tested in ExO module  3.1.0 and 3.3.0. behavior is the same. Returned URL https://aka.ms/tmrn does not point to learn pages. Please update documentation.

```powershell
Get-CalendarNotification -Identity AdeleV
Get-CalendarNotification: |Microsoft.Exchange.Management.Tasks.DeprecatedCmdletException|This cmdlet has been deprecated. Go to **https://aka.ms/tmrn** to learn more.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30397bf5-9cf6-7ff1-f02a-dcd4252b0228
* Version Independent ID: a6a39c85-378c-b7cc-8da5-c59b901a63cd
* Content: [Get-CalendarNotification (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-calendarnotification?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-CalendarNotification.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-CalendarNotification.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bsj17, I modified the Get-CalendarNotification and Set-CalendarNotification topics to be on-premises Exchange only with the following note at the top:

> **Note**: This cmdlet has been deprecated in Exchange Online PowerShell. The text message notification service has been discontinued in Microsoft 365.

Thanks for the feedback.

Closing
