### ISSUE TITLE
Unclear documentation for the output of Get-ConnectionInformation cmdlet

### ISSUE THREAD

**Issue by kemats** [MicrosoftDocs/office-docs-powershell#11331]
What output Get-ConnectionInformation cmdlet returns is unclear. It is difficult for developers to leverage the output of this cmdlet in their scripts. It would be great if details of output are well described like the documentation of Get-PSSession cmdlet.

https://learn.microsoft.com/powershell/module/microsoft.powershell.core/get-pssession#outputs

https://learn.microsoft.com/dotnet/api/system.management.automation.runspaces.pssession?view=powershellsdk-7.3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da3de055-6124-c8ab-49af-8b9ab1bf2f77
* Version Independent ID: db4ed03b-4af6-a2d3-b971-d05929377174
* Content: [Get-ConnectionInformation (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-connectioninformation?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-ConnectionInformation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-ConnectionInformation.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kemats, output information added in the DESCRIPTION section. You can make any changes directly. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing.
