### ISSUE TITLE
"sharewithmailuser" is "sharedwithmailuser" 

### ISSUE THREAD

**Issue by teraco** [MicrosoftDocs/office-docs-powershell#11340]
The Get-Recipient page says "sharedwithmailuser" and when I actually run the command, it says "sharedwithmailuser". This page says "sharedwithmailuser", which is incorrect.

https://learn.microsoft.com/powershell/module/exchange/get-recipient#-recipienttypedetails

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73d6ce18-0ec7-7509-4b9c-f8bb49d93e42
* Version Independent ID: f87de628-1dd2-d169-ab30-57c117ae3d0b
* Content: [Get-User (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-user?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-User.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-User.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@teraco, fixed.

In the future, you too can make changes like this directly; no need to open an issue first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
