### ISSUE TITLE
How to change the Holiday of an instance of a holiday call flow for an attendant

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#11367]
I have the following code

$newSchedule = Get-CsOnlineSchedule -Id 7180d617-d9a5-46d3-be7c-6472c8c4a713
$aa = Get-CsAutoAttendant -Identity 8a5e6a41-5da8-4746-8f43-ff4a8e6cfe20
$aa.Schedules = $aa.Schedules | Where-Object { $_.Name -ne "My Holiday" }
$aa.Schedules += @($newSchedule)
Set-CsAutoAttendant -Instance $aa

When I look at $aa.Schedules, it does show that the old schedule (with name of My Holiday) has been replaced by the new one and the Set-CsAutoAttendant shows no errors, yet when I get the AutoAttendant record again, the Schedules show the original holidays

What is the proper way to do this?

Also, how can you tie which instance of Schedules to the corresponding CallFlows instance?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8aedf07e-205e-ebe8-6351-1c1956f99b85
* Version Independent ID: c18defb2-97e8-1196-dc32-47260dad5c09
* Content: [Set-CsAutoAttendant (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csautoattendant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsAutoAttendant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsAutoAttendant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by JensTrier** [comment]
@sarollins You need to do something like this:


$ns=Get-CsOnlineSchedule -Id c12eb567-d72e-443a-8b78-1382c2484248
$greeting = New-CsAutoAttendantPrompt -ActiveType TextToSpeech -TextToSpeechPrompt "We are closed for winter vacation. Please call back later."
$menuOption = New-CsAutoAttendantMenuOption -DtmfResponse Tone1 -Action Announcement -Prompt $greeting
$menu = New-CsAutoAttendantMenu -Name "Winter Vacation Menu" -MenuOptions @($menuOption) -Prompts $greeting
$callFlow = New-CsAutoAttendantCallFlow -Name "Winter Vacation" -Greetings @($greeting) -Menu $menu
$callFlowId = $callFlow.Id
$callHandlingAssociation = New-CsAutoAttendantCallHandlingAssociation -Type Holiday -ScheduleId $ns.Id -CallFlowId $callFlowId

$aa=Get-CsAutoAttendant -Identity 5e4fee32-2c0d-4dd0-bd3c-454bba817a6e
$aa.CallHandlingAssociations += @($callHandlingAssociation)
$aa.CallFlows += @($callFlow)
Set-CsAutoAttendant -Instance $aa

**Comment by yogkumgit** [comment]
@JensTrier  Thank you very much for sharing this explanation. @sarollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
