### ISSUE TITLE
Notification Mode needs explanation

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/office-docs-powershell#11361]
NotificationMode has no explanation, other than what NotificationDialOutNumber mentions, which does not adequately explain things (in fact I think it makes it more confusing because if the call can't be unmuted what are the NotificationMode settings for then?)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fe9f7ba-98ec-1f20-7154-de77e6a38543
* Version Independent ID: 81e7837c-3c13-b6f1-2e89-6bb9e822dde6
* Content: [New-CsTeamsEmergencyCallingPolicy (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencycallingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by get-itips** [comment]
Hello @TorrenManson I'm working on this

**Comment by get-itips** [comment]
Hello @TorrenManson 

> Conferenced in and are unmuted: A Teams chat message is sent to the users and groups that you specify and they can unmute to listen and participate in the conversation between the caller and the PSAP operator.

Can not be unmuted only for the PSTN participant, VoIP participant can unmute if the setting allows it.

I'll improve the parameter description.
