### ISSUE TITLE
Add-TeamChannelUser : Object reference not set to an instance of an object  NullReferenceException

### ISSUE THREAD

**Issue by blatnis17** [MicrosoftDocs/office-docs-powershell#11376]
This error occurs when I want to add  the owner in the **Shared** MS Tema channle
Add-TeamChannelUser -GroupId "cd****ss" -DisplayName "XXXX" -User "UPN" -Role Owner
Add-TeamChannelUser : Object reference not set to an instance of an object.
At line:1 char:1
+ Add-TeamChannelUser -GroupId "cd****ss" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamChannelUser], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Teams.PowerShell.TeamsCmdlets.AddTeamChannelUser

I can add user to Shared MS Teem channel without owner role :
Add-TeamChannelUser -GroupId "cd****ss" -DisplayName "XXXX" -User "UPN"    

Module version of MicrosoftTeams is 5.2.0

**Comment by blatnis17** [comment]
After adding the user to the group, I tried the following command :
1. Command : Add-TeamChannelUser -GroupId "cd****ss" -DisplayName "XXXX" -User "UPN" 
2. Command Add-TeamChannelUser -GroupId "cd****ss" -DisplayName "XXXX" -User "UPN" -Role Owner

I don't get the error for command 2, but the user is not the owner either.

If I use the debug switch :
VERBOSE: Done performing authorization
VERBOSE: Executing Add-TeamChannelUser for parameters GroupId: cd****ss, DisplayName: XXXX, User: UPN, Role: Owner, TenantId: 
DEBUG: Making an api call to the uri: https://graph.microsoft.com/beta/teams/cd****ss/channels?$filter=tolower(DisplayName) eq tolower('XXXX')

**Comment by get-itips** [comment]
Hello @blatnis17 
Here we are limited to documentation issues and fixes.

The article for [Add-TeamChannelUser](https://learn.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps) specifies it is to be used for private channels, so not sure about the behavior in Shared ones.

Thanks,

**Comment by cyr0nk0r** [comment]
This shouldn't have been closed. This has been a bug as far back as December 2022. A fix was released specifically released to address this bug. I logged it directly with Microsoft (Case # 33149197)

This sounds like a regression.
