### ISSUE TITLE
Pipelining Get-EXOMailboxFolderStatistics to Get-EXOMailboxFolderPermissions

### ISSUE THREAD

**Issue by PSonander** [MicrosoftDocs/office-docs-powershell#11387]
Hi

Get-EXOMailboxFolderStatistics generates a field called Identity for each folder in the format "Mailbox\Folder" while Get-EXOMailboxFolderPermissions expects an Identity on the pipeline in the format "Mailbox:\Folder". A small ":" prevents from pipelining the commands.

Peter

**Comment by chrisda** [comment]
@PSonander, the same issue also exists in GetMailboxFolderStatistics and Get-MailboxFolderPermission. You can try making a suggestion at `exocmdletpreview[at]service[dot]microsoft[dot]com`.

**Comment by shivtorov** [comment]
workaround is to perform format conversion manually like this:

```
Get-EXOMailboxFolderStatistics -UserPrincipalName user@domain.com | Where-Object Identity -match Archive | Get-EXOMailboxFolderPermission -Identity { $_.Identity -replace '\\',':\' }
```

**Comment by yogkumgit** [comment]
@shivtorov Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
