### ISSUE TITLE
MigrateFilesAndFoldersWithInvalidChars Parmeter

### ISSUE THREAD

**Issue by ryszardcopa** [MicrosoftDocs/office-docs-powershell#11388]
I don't see parameter -MigrateFilesAndFoldersWithInvalidChars, there is only -ReplacementOfInvalidChar in PS5 and PS7. Documentation is not valid.

When I check get-module it showing version 1.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e84226d2-c4c1-7cc0-3eab-dc0fe86fbaa9
* Version Independent ID: 73bb0f00-1909-6eb1-3a8c-247149480c9a
* Content: [Register-SPMTMigration (SharePointMigrationTool)](https://learn.microsoft.com/en-us/powershell/module/spmt/register-spmtmigration?view=spmt-ps)
* Content Source: [spmt/spmt-ps/spmt/Register-SPMTMigration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/spmt/spmt-ps/spmt/Register-SPMTMigration.md)
* Service: **spmt-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @ryszardcopa 
The parameter has been deprecated, I'll remove it from the article

source https://learn.microsoft.com/en-us/sharepointmigration/new-and-improved-features-in-the-sharepoint-migration-tool#spmt-341200

Thanks for your feedback
