### ISSUE TITLE
Not working/available

### ISSUE THREAD

**Issue by monsterapp** [MicrosoftDocs/office-docs-powershell#1139]
This command does not appear to be available under 2.26.1805.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec9d15e-0cea-3966-d30c-eb7f939cb694
* Version Independent ID: fcda0fff-544d-8d04-d942-e66e671f5744
* Content: [Add-PnPStoredCredential (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpstoredcredential?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPStoredCredential.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPStoredCredential.md)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen for your review.

**Comment by VesaJuvonen** [comment]
Actually, it is. It's not there if you use the preview .NET standard version, but if you install PnP PowerShell from PowerShell gallery, it is included properly in the machine.
