### ISSUE TITLE
New-AutoSensitivityLabelRule -HeaderMatchesPatterns

### ISSUE THREAD

**Issue by StephenM-CC** [MicrosoftDocs/office-docs-powershell#11419]
When using the "HeaderMatchesPatterns" parameter, providing a Hash Table (as per the documentation) with Header and String pattern creates a Rule that contains the Header and then a separate rule for each character in the Match string, e.g.

New-AutoSensitivityLabelRule -Name "test" -Policy "PolicyName" -HeaderMatchesPatterns @{"Header"="String"}

Produces a rule containing:
Header: S
Header: t
Header: r
Header: i
Header: n
Header: g

Any attempt to force the use of a strong type in PowerShell results in the same output. Inserting a premade hash table (defining a variable and substituting it in the input for -HeaderMatchesPatterns) produces the same result. Any attempt to provide data other than a Hash Table results in a mismatched type error.

This rule can be created correctly in the M365 portal GUI, but then providing the hash table output by the Get-AutoSensitivityLabelRule (in the HeaderMatchesPatterbns value) back to Set-AutoSensitivityLabelRule or New-AutoSensitivityLabelRule provides an invalid input error.

Is this a bug with the input, or user error?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 324976b7-f841-b9c1-1daa-57b64f79d31d
* Version Independent ID: 3125eaae-6015-7d4b-f15d-f4fe88b08a8f
* Content: [New-AutoSensitivityLabelRule (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-autosensitivitylabelrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-AutoSensitivityLabelRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@StephenM-CC, you should open a support ticket about this. Report back with any findings that can help improve the documentation.
