### ISSUE TITLE
No roles have permission to run the -WhatIf parameter with Delete-QuarantineMessage

### ISSUE THREAD

**Issue by frbjly** [MicrosoftDocs/office-docs-powershell#11415]
The -WhatIf parameter doesn't work with this cmdlet. It throws the following error message:

```
Write-ErrorMessage : ExB880D8|Microsoft.Exchange.Configuration.Authorization.CmdletAccessDeniedException|The "WhatIf" parameter can't be used on the "Delete-QuarantineMessage" cmdlet because it isn't present in the role definition for the current user. Check the management roles assigned to you, and try again.
At C:\Users\XXX\AppData\Local\Temp\169\tmpEXO_dzngcuhj.cph\tmpEXO_dzngcuhj.cph.psm1:1190 char:13
+             Write-ErrorMessage $ErrorObject
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Delete-QuarantineMessage], CmdletAccessDeniedException
    + FullyQualifiedErrorId : [Server=DB5PR10MB7666,RequestId=1a669ad2-0a06-fcd0-ea1e-d25c20e7f623,TimeStamp=Wed, 25 Oct 2023 08:55:38 GMT],Write-ErrorMessage
```

It seems that there are no roles with permission to run the cmdlet with this parameter Running the following commands gives no result:

```
$Perms = Get-ManagementRole -Cmdlet Delete-QuarantineMessage -CmdletParameters WhatIf
$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}

```
For reference I ran them for another parameter and got the expected result:

```
$Perms = Get-ManagementRole -Cmdlet Delete-QuarantineMessage -CmdletParameters HardDelete
$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}

Role              RoleAssigneeType RoleAssigneeName       
----              ---------------- ----------------       
Transport Hygiene RoleGroup        Hygiene Management     
Transport Hygiene RoleGroup        Organization Management

Role           RoleAssigneeType RoleAssigneeName        
----           ---------------- ----------------        
Security Admin RoleGroup        Organization Management 
Security Admin RoleGroup        SecurityAdmins_-21872738
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54c93f73-0b14-ae66-5f31-c60f86dcfc40
* Version Independent ID: d8c0aa20-0abd-5766-f437-18f884ffc3ab
* Content: [Delete-QuarantineMessage (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/delete-quarantinemessage?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Delete-QuarantineMessage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Delete-QuarantineMessage.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@frbjly, I presume you were in Exchange Online PowerShell and not in Security & Compliance PowerShell? The WhatIf switch doesn't work for any cmdlet in Security & Compliance PowerShell, and the affected articles say so (including this one):

> The WhatIf switch simulates the actions of the command. You can use this switch to view the changes that would occur without actually applying those changes. You don't need to specify a value with this switch.
>
> The WhatIf switch doesn't work in Security & Compliance PowerShell.

**Comment by frbjly** [comment]
@chrisda, That is correct, I am using Exchange Online PowerShell - not Security & Compliance PowerShell. For reference I checked what the output is if I run the same commands for the "Release-QuarantineMessage" cmdlet (which has the same limitation regarding Security & Compliance PowerShell) and as you can see the result is different from the one I get for "Delete-QuarantineMessage":

```
$Perms = Get-ManagementRole -Cmdlet Release-QuarantineMessage -CmdletParameters WhatIf

$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}

Role              RoleAssigneeType RoleAssigneeName       
----              ---------------- ----------------       
Transport Hygiene RoleGroup        Hygiene Management     
Transport Hygiene RoleGroup        Organization Management

Role           RoleAssigneeType RoleAssigneeName        
----           ---------------- ----------------        
Security Admin RoleGroup        Organization Management 
Security Admin RoleGroup        SecurityAdmins_-21872738
```

**Comment by chrisda** [comment]
@frbjly, OK. Since WhatIf doesn't work in ExO PowerShell or S&C PowerShell, I changed the description to:

> This parameter is reserved for internal Microsoft use.

Thanks for the feedback.

Closing
