### ISSUE TITLE
-HighCompleteness parameter not documented

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#11429]
Not sure what it does, but have seen it fail like this:

```powershell
ConvertFrom-Json: Conversion from JSON failed with error: Unexpected character encountered while parsing value: ▼. Path '', line 0, position 0.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75b757c9-b775-8294-91f7-870bead6a907
* Version Independent ID: 54ebab36-97bb-cd9f-6eb2-12198af885e2
* Content: [Search-UnifiedAuditLog (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/search-unifiedauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeremyTBradshaw, I can confirm that the parameter (switch) is available, so I added it to the article with an empty description.

Are you being directed to use this parameter in other content?

**Comment by JeremyTBradshaw** [comment]
Hi @chrisda , nope.  I was working on a script today, using Microsoft.Graph.Security module, then searching Audit log for the Malware detected entry so I can get the file name.  In reviewing the parameters, came across this one, wondered, and boom here we are.

**Comment by yogkumgit** [comment]
@JeremyTBradshaw Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
