### ISSUE TITLE
Get-CsOnlineApplicationInstance has parameter -Identities shown when using tab completion

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/office-docs-powershell#11425]
Import the Teams PS module version 5.7.1

Type Get-CsOnlineApplicationInstance, space, hyphen and press tab a few times
Among the parameters shown is -Identities
but that parameter is not allowed according to Get-Help and the online web page.

Also, if you run e.g.
```
Get-CsOnlineApplicationInstance -Identities x
Get-CsOnlineApplicationInstance: A parameter cannot be found that matches parameter name 'Identities'
```

Running PowerShell 7.3.9 on Windows 10 22H2, Teams PS module 5.7.1.

**Comment by get-itips** [comment]
Hello @donlassini 
Thanks for your feedback, however we are limited to documentation fixes and improvements, I'll try to pass this on.
