### ISSUE TITLE
Get-CsOnlineApplicationInstance outputs correlation ID at some errors

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/office-docs-powershell#11427]
Run the following:
```
PS> Get-CsOnlineApplicationInstance -Identity x
Correlation id for this request : 448fdb30-6146-4fb6-b163-ca074d516f8a
Get-CsOnlineApplicationInstance: userId was not found
```

The correlation ID should not be shown.

Then run this to suppress errors and warnings:
```
Get-CsOnlineApplicationInstance -Identity x -ErrorAction SilentlyContinue -WarningAction SilentlyContinue
Correlation id for this request : 3c069112-9f0d-4c27-80e8-e837d48b342c
```
You still get the correlation ID text; I think it's sent directly to the console, just like Write-Host does.

MicrosoftTeams module, version 5.7.1.
```
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by donlassini** [comment]
I have noticed the same behaviour for Get-CsOnlineUser:
```
> Get-CsOnlineUser -Identity xxx
Correlation id for this request : 0afe1216-16bf-4a7a-ad00-0a2b5c6c2f77
Get-CsOnlineUser: userId was not found
```

**Comment by raduflorinadrian** [comment]
You can use Filter instead of Identity. 
Get-CsOnlineUser -Filter {UserPrincipalName -like "test*"}
Using Filter I'm not getting the correlation message! ;)

https://learn.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps

**Comment by donlassini** [comment]
> You can use Filter instead of Identity. Get-CsOnlineUser -Filter {UserPrincipalName -like "test*"} Using Filter I'm not getting the correlation message! ;)
> 
> https://learn.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps

Good workaround, I will look at that for my scripts.
I have a suspicion that other cmdlets also does this; I've observed it since July 19th using Teams PS version 5.3.0. I have not yet examined this further in detail, though, but I will next week.

**Comment by get-itips** [comment]
Hello @donlassini 
How are you?
I'm not receiving any correlation id in both cmdlets, I'm running 5.7.1
Thanks

**Comment by shivtorov** [comment]
> Hello @donlassini How are you? I'm not receiving any correlation id in both cmdlets, I'm running 5.7.1 Thanks

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/31003608/d0521f50-19a9-4be4-a31c-e01b81690f1d)

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
@donlassini I'll try to report this however here we are limited to documentation issues and fixes.
