### ISSUE TITLE
No access to Connect-IPSSession

### ISSUE THREAD

**Issue by unknowndpi** [MicrosoftDocs/office-docs-powershell#11434]
If you're using version 3.2.0 or later of the module, and you don't use the UseRPSSession switch in the Connect-IPPSSession command, you have access to REST API cmdlets only

== The 'UseRPSSession' switch does not exist/work with Connect-IPPSSession. Info needs updating as there's no way to run 'Get-ComplianceSearch'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/connect-to-scc-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@unknowndpi, fixed, including a bunch of other v3.4.0 module updates.

Are you saying that Get-ComplianceSearch doesn't work at all in regular, manual user connection mode (not CBA, MI, C#, etc.)?

**Comment by unknowndpi** [comment]
I'm no longer able to replicate the issue. I suspect it occurred when running 3.2.0 preview, upgraded to 3.4.0 but likely something was still cached. All works OK now, even with WinRM basic is disabled (great news)

**Comment by chrisda** [comment]
@unknowndpi, cool.

Thanks for the feedback.

Closing
