### ISSUE TITLE
Get-CS* cmdlets results in 401 in Azure Function and managed identity usage

### ISSUE THREAD

**Issue by DanielMisch** [MicrosoftDocs/office-docs-powershell#11433]
Connect-MicrosoftTeams -Identity
Get-CsPhoneNumberAssignment -TelephoneNumber "0123456"

All scopes and role assignments done as described.

What am i missing?

Greets, Daniel

**Comment by shivtorov** [comment]
@DanielMisch , the [help article](https://learn.microsoft.com/powershell/module/teams/connect-microsoftteams?view=teams-ps#parameters) says the following:

> ### -Identity
> Login using managed service identity in the current environment. This is currently not supported for *-Cs cmdlets. 

I don't know if the parameter description is still true, but I would not even attempt to use an auth method if the documentation explicitly says it is "not supported"

**Comment by get-itips** [comment]
Thanks @shivtorov
