### ISSUE TITLE
Search-Mailbox cmdlet removed in cloud-based env

### ISSUE THREAD

**Issue by mennojonkers** [MicrosoftDocs/office-docs-powershell#11447]
> Note: In cloud-based environments, the Search-Mailbox cmdlet is being deprecated in favor of [New-ComplianceSearch](https://learn.microsoft.com/en-us/powershell/module/exchange/new-compliancesearch) and related eDiscovery cmdlets.

By now it seems this cmdlet has been removed in the cloud-based env.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 734c1949-1689-5120-4fc9-54f8b377b541
* Version Independent ID: 054a07d6-870b-d941-1ec3-2bd12506d043
* Content: [Search-Mailbox (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/search-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Search-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Search-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mennojonkers, I checked in two different Microsoft 365 E5 tenants, and it's still available.

**Comment by mennojonkers** [comment]
Thanks for the quick reply. Maybe my observation is premature. We're using Microsoft 365 Business Standard. In a pwsh session, after the Connect-ExchangeOnline, I get:
```
PS /home/jonkers> Search-Mailbox
Search-Mailbox: The term 'Search-Mailbox' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
whereas New-ComplianceSearch does resolve. I've not use Search-Mailbox in the past, there may be some setup I'm missing here.

**Comment by yogkumgit** [comment]
@mennojonkers Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
