### ISSUE TITLE
Parameter -user

### ISSUE THREAD

**Issue by miguelrodriguezeicke** [MicrosoftDocs/office-docs-powershell#11441]
Parameter -user is only accepting Mail attribute of users, not UPN. Please adjust description

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f38da792-01bc-28ad-7727-794075e150c9
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @miguelrodriguezeicke 
How are you?
I tested this, and I could use both the email and upn to get teams with the user.
Thanks,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @miguelrodriguezeicke Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
