### ISSUE TITLE
Include accepted values for ConnectorType parameter

### ISSUE THREAD

**Issue by richfaj** [MicrosoftDocs/office-docs-powershell#11451]
We should consider adding the accepted values for ConnectorType parameter (e.g. OnPremise and Partner)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c38a9b3d-3c15-3a0f-dc38-4ee357e0c800
* Version Independent ID: 4e5c08ec-a2d4-63a4-27f0-e08445f64f8a
* Content: [Start-HistoricalSearch (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/start-historicalsearch?view=exchange-ps#-connectortype)
* Content Source: [exchange/exchange-ps/exchange/Start-HistoricalSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Start-HistoricalSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@richfaj, I added the following description:

> The ConnectorType parameter filters the results by the connector type. Valid values are:
>
> - OnPremises
> - Partner

Feel free to add anything else you like. It's really easy. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

You are also more than welcome to tackle any of the other empty parameter descriptions in that article:

- BlockStatus
- CompressFile
- EncryptionTemplate
- EncryptionType
- SmtpSecurityError
- TLSUsed
- Url

Thanks for the feedback.

Closing
