### ISSUE TITLE
RecipientAdministrativeUnitScope

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/office-docs-powershell#11461]
What version does support this parameter?

-RecipientAdministrativeUnitScope

I can't find it.

**Comment by yogkumgit** [comment]
@BakkerJan Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
