### ISSUE TITLE
Export-ContentExplorerData : The term 'Export-ContentExplorerData' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by jsk999** [MicrosoftDocs/office-docs-powershell#11469]
I do have ExchangePowerShell module installed but I can't get "Export-ContentExplorerData" to work on my computer.
I get error shown in the image below:

![image](https://github.com/MicrosoftDocs/office-docs-powershell/assets/46309537/ad9ec558-bb77-4a15-8f6e-2aedff40da87)

Any ideas/suggestions on how to fix this?

**Comment by chrisda** [comment]
@jsk999, did you [connect to Security & Compliance PowerShell](https://learn.microsoft.com/powershell/exchange/connect-to-scc-powershell) using the Connect-IPPSSession cmdlet? After you connect, it should be available.

The module itself has very few cmdlets baked into it (you can see them [here](https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#cmdlets-in-the-exchange-online-powershell-module) if you're interested). But other than the connection cmdlets, none of them work unless you connect to Exchange Online PowerShell or Security & Compliance PowerShell first.

**Comment by yogkumgit** [comment]
@jsk999 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
