### ISSUE TITLE
Add-TeamUser - update the method to allow external users not in our AD - currently it fails.

### ISSUE THREAD

**Issue by rickmcguire** [MicrosoftDocs/office-docs-powershell#11479]
Please add the ability to use Add-TeamsUser to allow adding users not in our AD already as a guest. 

I regularly need to add 50 - 1000 users to a Team where the majority of the users are not in the Microsoft domain and not in our AD.  The Add-TeamsUsers method fails. I understand this is a current limitation, but for my scenario, I really need to enhance this to support other emails not in our domain (maybe add the users to AD in the background like Teams does when using the UI?)

**Comment by get-itips** [comment]
Hello @rickmcguire Rick,
Here we are limited to documentation issues and fixes, for feature request you can use https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472
