### ISSUE TITLE
Add the ability to add a user with a Tag using the Add-TeamUser method.

### ISSUE THREAD

**Issue by rickmcguire** [MicrosoftDocs/office-docs-powershell#11477]
When adding a lot of users to a Team would like to be able to add a tag as well, currently have to go into Teams to create or tag users once they are added.

**Comment by get-itips** [comment]
Hello @rickmcguire Rick,
Here we are limited to documentation issues and fixes, for feature request you can use https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472
