### ISSUE TITLE
No information about the output

### ISSUE THREAD

**Issue by katlim-br** [MicrosoftDocs/office-docs-powershell#11480]
No information about the output

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b60b5c4e-7698-eefc-e515-ff6c59689e05
* Version Independent ID: 66daa134-52e6-dc2d-52f7-920718a6f0ff
* Content: [New-TenantAllowBlockListItems (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-tenantallowblocklistitems?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@katlim-br, I typically see questions about the output of cmdlets associated with Get- cmdlets, not New-.

If you're talking about the OUTPUTS section, we don't manually populate that information. There used to be an automatic mechanism that would keep up output types. You can see it in the OUTPUT section of older cmdlets. But that hasn't been available for 5+ years.

Most of what's provided in that section is determined by code. I looked back at several raw dumps of the New-TenntAllowBlockList Iems cmdlet from [platyPS](https://github.com/PowerShell/platyPS), and the OUTPUTS section is empty.

**Comment by katlim-br** [comment]
well, Get- doesnt show the actual output neither.

I had to test the New- command to see the output (which means I added an entry for nothing).

This is for a short-lived task I'm doing so I dont care much about this, but I feel like it is not in Microsoft users best interest to have an incomplete documentation.

Thanks for your prompt response.
