### ISSUE TITLE
Example 4 has a (Important) missing parameter (-Format FxStream)

### ISSUE THREAD

**Issue by MaJoMS** [MicrosoftDocs/office-docs-powershell#11493]
In the Example 4, the example do not export into PerUserPST. INstead it is exporting into msg format. This is because the paramater -Format FxStream is missing. The correct Example 4 should look like: "**New-ComplianceSearchAction -SearchName "Case 321 All Sites" -Export -SharePointArchiveFormat SingleZip -ExchangeArchiveFormat PerUserPst ### **-Format FxStream****"

Please replace the example and make a note into the parameter "-ExchangeArchiveFormat" that -Format FxStream is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fad8adee-7f9d-757b-2069-95ecab232747
* Version Independent ID: c71194df-8f65-15aa-3ed2-b370b8c3f629
* Content: [New-ComplianceSearchAction (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-compliancesearchaction?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MaJoMS, fixed as you described.

In the future, you too can make changes like this directly without opening an Issue first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
