### ISSUE TITLE
userprincipalname isn't a valid parameter - connect-ippssession

### ISSUE THREAD

**Issue by csando** [MicrosoftDocs/office-docs-powershell#11490]
Userprincipalname isnt a valid paramater.

Connect-ippssession -userprincipalname

returns
"a parameter cannot be found that matches userprincipalname"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/connect-to-scc-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@csando, if the ExchangeOnlineManagement module is installed, the cmdlet and parameter should be avaialble

https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#install-and-maintain-the-exchange-online-powershell-module

The current version is 3.4.0, released about a month ago.

**Comment by csando** [comment]
> @csando, if the ExchangeOnlineManagement module is installed, the cmdlet and parameter should be available
> 
> https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#install-and-maintain-the-exchange-online-powershell-module
> 
> The current version is 3.4.0, released about a month ago.

Oh yes!

My thanks. I had 3.1.0, Strangely I had updated the module, but had to uninstall and reinstall to get 3.4.0
