### ISSUE TITLE
Is WordPDF or PDF supported to remove bindings 

### ISSUE THREAD

**Issue by mdittakavi** [MicrosoftDocs/office-docs-powershell#1155]
Hi Team,

is the below article still applies to SharePoint 2016 with office online server 2016.  we are trying to set PDF's to open in mobile default app instead of office online and found below article.

https://support.microsoft.com/en-au/help/2912639/mobile-viewing-pdf-files-with-office-web-apps  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efa0d990-8de7-ae7c-8e6f-39f57458dbb8
* Version Independent ID: 37fa1783-b4b1-6de5-ca43-51937371c79d
* Content: [Remove-SPWOPIBinding (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/remove-spwopibinding?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Remove-SPWOPIBinding.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Remove-SPWOPIBinding.md)
* Service: **unspecified**
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
The article you linked says Office Online Server in the applies to. The `Remove-SPWOPIBinding` cmdlet says SharePoint Server 2016 in the applies to.

**Comment by mdittakavi** [comment]
Remove-SPWOPIBinding is applies to SP2016. It is known.

I am asking about WordPDF mobile view support.

Thanks and Regards,
Murali Dittakavi
Integration & Collaboration Technical Lead

**Comment by tseward** [comment]
Right, the article is very clear that MobilePDF is not available in OOS.

**Comment by AndreaBarr** [comment]
@mdittakavi Thank you for this feed back.

It looks like Trevor has answered your questions above. I am going to close this issue, if it is not resolved please re-open.
