### ISSUE TITLE
is this still applicable in SharePoint 2016 office online server 2016

### ISSUE THREAD

**Issue by mdittakavi** [MicrosoftDocs/office-docs-powershell#1156]
we are trying to provision users to open the PDF in mobile browsers using mobile pdf application.

we can't see mobileview binding for wordpdf.

https://support.microsoft.com/en-au/help/2912639/mobile-viewing-pdf-files-with-office-web-apps   

is the above article still applies to SP2016 with OOS2016

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fab6a93b-d987-3639-d863-2b2f850b4ce4
* Version Independent ID: 2dd95bd9-4566-2ff0-a0ce-2d3687de126b
* Content: [Set-SPWOPIBinding (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spwopibinding?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPWOPIBinding.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPWOPIBinding.md)
* Service: **unspecified**
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@MikePlumleyMSFT need guidance since it applies to OOS.  thanks

**Comment by MikePlumleyMSFT** [comment]
@Techwriter40 please assign to @lorenahuangliu

**Comment by Techwriter40** [comment]
@lorenahuangliu for your review

**Comment by mdittakavi** [comment]
Remove-SPWOPIBinding is applies to SP2016. It is known.

I am asking about WordPDF mobile view support.

**Comment by AndreaBarr** [comment]
@mdittakavi Thank you for this feedback

This seems to be a duplicate issue of https://github.com/MicrosoftDocs/office-docs-powershell/issues/1155 . Closing issue. If this issue is not resolved please reopen the original issue.
