### ISSUE TITLE
Extra parameter in example

### ISSUE THREAD

**Issue by DanishIslam07** [MicrosoftDocs/office-docs-powershell#1157]
In the example, it shows one extra paraemeter "HubSite" which is not applicable for "Remove-PnPHubAssoication" command. 

Please remove this parameter. Correct example should be-
Remove-PnPHubSiteAssociation -Site https://tenant.sharepoint.com/sites/mysite

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a34e81-3375-ae68-0675-b8a680362e6f
* Version Independent ID: 5485c39d-f5fa-bf3f-c860-bdc5759bb997
* Content: [Remove-PnPHubSiteAssociation (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnphubsiteassociation?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPHubSiteAssociation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPHubSiteAssociation.md)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen for your review

**Comment by VesaJuvonen** [comment]
Fixed with the upcoming June content refresh. Thanks @DanishIslam07 for reporting.
