### ISSUE TITLE
EXAMPLE 1 Error

### ISSUE THREAD

**Issue by Leumas09** [MicrosoftDocs/office-docs-powershell#1158]
The function name is misspelled it's Test-PnPListItemIsRecord not Test-PnPListItemAsRecord

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd5caf54-9dfd-c604-ab24-1a0847eb387b
* Version Independent ID: 6aa21351-19f1-e365-fde9-8d1cc99205c0
* Content: [Test-PnPListItemIsRecord (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/test-pnplistitemisrecord?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Test-PnPListItemIsRecord.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Test-PnPListItemIsRecord.md)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen for your review

**Comment by VesaJuvonen** [comment]
Thx @Leumas09 for reporting. Will be fixed in the June release when docs are re-generated - within next 7 days.
