### ISSUE TITLE
Need to find users connected to front-end servers individually.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1166]
Looking to find which users are connected to particular front-end servers. Options only seems to give a catch all or everything. Need to break it down by servers. So far none on the forums has found a way. They either mention do the catch all then sort it out manually or try individually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ae4fb7-9fbf-5eb4-8141-512eb33e05c0
* Version Independent ID: 6b7e2d65-28b5-c102-4e15-44a5dfc57dcd
* Content: [Get-CsUserPoolInfo (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Get-CsUserPoolInfo?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsUserPoolInfo.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsUserPoolInfo.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by jordanmills** [comment]
Did you try get-csuserpoolinfo?

**Comment by kenwith** [comment]
Looks like there are examples in Get-CsUserPoolInfo as Joran suggested. Closing this out but if you see a place where the docs should be clearer please re-open. Thanks!
