### ISSUE TITLE
Need help toggling privacy settings.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1167]
How can I toggle privacy settings on a local system with a powershell script? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42a673c8-cbcd-0bc5-9b7e-40179236a825
* Version Independent ID: bebd5bcf-7be1-0cb1-7427-9cc5e7d9a5db
* Content: [Set-CsPrivacyConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Set-CsPrivacyConfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsPrivacyConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsPrivacyConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
Examples have been added to the cmdlet.
