### ISSUE TITLE
Connect-SPOService MFA support

### ISSUE THREAD

**Issue by pgemme** [MicrosoftDocs/office-docs-powershell#1168]
There is never a prompt for MFA logins during connection. Only the standard 

> Connect-SPOService : The sign-in name or password does not match one in the Microsoft account system. 

I had to disable the Global Administrator's MFA to get around this.

**Comment by VesaJuvonen** [comment]
If you execute the Connect-SPOService without providing credentials, you will be prompted for the auth window, which is supporting MFA. 

```
 Connect-SPOService -Url https://yourtenant-admin.sharepoint.com
```

**Comment by pgemme** [comment]
I had only been providing the username; good call, completely missed this. Thanks.
