### ISSUE TITLE
Need help understanding TargetFqdn

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1169]
Don't understand the following description about TargetFqdn:
"TargetFqdn must point to the internal edge of the proxy server to which federated SIP traffic is directed" 

What exactly this means? Internal edge of the proxy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29666e86-628b-019e-cbaa-5d8b6dd3884a
* Version Independent ID: 75a7a4ec-a163-d06e-558d-6373f880e0f0
* Content: [Test-CsFederatedPartner (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Test-CsFederatedPartner?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Test-CsFederatedPartner.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Test-CsFederatedPartner.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by get-itips** [comment]
it has been resolved @AndreaBarr
