### ISSUE TITLE
Adding multiple sites in one array

### ISSUE THREAD

**Issue by paralyz3** [MicrosoftDocs/office-docs-powershell#1173]
A key use for this cmdlet for our organisation would be to add multiple sites in one array, instead of doing this on a per-site basis. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6338721-5bad-7526-8328-428bc420a0e9
* Version Independent ID: b69c571d-ab9f-80f1-eed1-9008e6cd5b76
* Content: [Add-SPOHubSiteAssociation](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spohubsiteassociation?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubSiteAssociation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubSiteAssociation.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen for your review

**Comment by VesaJuvonen** [comment]
This is just matter of using ForEach in your script. Since each customer will have their own grouping, we can't really provide end-to-end example, but the For each process in Powershell is well documented in the following article https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object?view=powershell-6

**Comment by Christian-Anton** [comment]
$hub = <URL-to-hub-site>
get-unifiedgroup | foreach-object { Add-SPOHubSiteAssociation -HubSite $hub -Site $_.SharePointSiteUrl }

**Comment by get-itips** [comment]
Hello @paralyz3 
As @VesaJuvonen suggested, you can accomplish what you want using a ForEach loop.
Besides that, as this is a resource to report issues in Documentation, we will proceed closing this, you can always create a suggestion on user voice too https://sharepoint.uservoice.com/
Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @paralyz3 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
