### ISSUE TITLE
Need to find archiving data time.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1175]
Could you add the archiving data time, when open a session? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c65d1f36-f93e-033c-178d-b68fa01025c7
* Version Independent ID: d6fb6d8a-6c43-1dba-7f92-47369e36d4d6
* Content: [Export-CsArchivingData (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Export-CsArchivingData?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Export-CsArchivingData.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Export-CsArchivingData.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
This cmdlet is discussed further in the conceptual content: https://docs.microsoft.com/en-us/skypeforbusiness/manage/archiving/export-archived-data. I will add a cross link as well.
