### ISSUE TITLE
Need clarification.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1177]
Do you have a global option for all user to allow unauthenticated callers to be the first people in a meeting. If not, then they will wait in the lobby until an authenticated user joins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7d9d1da-e548-5f48-b0b1-18ef69c0caac
* Version Independent ID: 2f967ff1-cb4f-2394-cf10-ed8f5188a0c6
* Content: [Set-CsMeetingConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Set-CsMeetingConfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsMeetingConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsMeetingConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
The parameter to do this is: `-AssignedConferenceTypeByDefault ` however it is a security issue to open meetings to public without a meeting organizer.
