### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1178]
How to get this command down to my local machine powershell? A link would be also helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae79fa4-f881-d28c-d505-e3e1faf91a73
* Version Independent ID: 057f00d3-8e7c-1971-7d79-0c4e77017aa6
* Content: [Get-CsUserReplicatorConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Get-CsUserReplicatorConfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsUserReplicatorConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsUserReplicatorConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
The cmdlet is installed when Skype for Business is installed on a server. You can access the commands in the Skype for Business Server Management Shell. Here is a link: https://docs.microsoft.com/en-us/skypeforbusiness/manage/management-shell
