### ISSUE TITLE
Need to know who can run this cmdlet?

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1180]
What happened to "Who can run this cmdlet?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a81211-154e-7c33-7abd-95cbcb8cf87f
* Version Independent ID: d09ce2ed-2df4-1189-6573-466eb3880150
* Content: [New-CsCommonAreaPhone (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/New-CsCommonAreaPhone?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsCommonAreaPhone.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsCommonAreaPhone.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
I don't follow this one but with more details I can help track down. I will close for now but feel free to re-open.
