### ISSUE TITLE
Need to get powershell module for Get-CsUser

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1182]
Where can i get the powershell module for Get-CsUser?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04a4a893-ff38-930b-20e5-31231b1859a7
* Version Independent ID: 53c97d7c-8c81-5387-011c-2aa97d64fe4e
* Content: [Get-CsUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Get-CsUser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by jordanmills** [comment]
Install the SFB administrative tools.  It doesn't have to be done on an SFB server.  

https://docs.microsoft.com/en-us/skypeforbusiness/deploy/install/install-administrative-tools
