### ISSUE TITLE
Need to add note.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1184]
You should note: IPv6 doesn't work with this. As soon as you enable IPv6 on the Edge server, this fails every time. If you confirm, then I can update and submit a PR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29666e86-628b-019e-cbaa-5d8b6dd3884a
* Version Independent ID: 75a7a4ec-a163-d06e-558d-6373f880e0f0
* Content: [Test-CsFederatedPartner (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Test-CsFederatedPartner?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Test-CsFederatedPartner.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Test-CsFederatedPartner.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@tomkau - can you confirm if this is expected behavior that IPv6 does not work with this cmdlet?
