### ISSUE TITLE
Need to add note about -disastermode parameter.

### ISSUE THREAD

**Issue by nsshommo** [MicrosoftDocs/office-docs-powershell#1185]
The parameter -disastermode is required for an enterprise pool if the back end SQL services are down but the front end servers are still up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82df2601-dba8-dbf2-edd3-4bc26bbc6cde
* Version Independent ID: 2a955fed-121a-e8d7-4034-84be8db61e13
* Content: [Invoke-CsPoolFailOver (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Invoke-CsPoolFailOver?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Invoke-CsPoolFailOver.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Invoke-CsPoolFailOver.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
Added note with PR: https://github.com/MicrosoftDocs/office-docs-powershell/pull/1289 thank you!
