### ISSUE TITLE
How is the documentation sync'd?

### ISSUE THREAD

**Issue by microsmith** [MicrosoftDocs/office-docs-powershell#119]
How is the documentation for these cmdlets sync'd between here and docs.microsoft.com? I may be interested in updating some of the samples and descriptions, but don't know where to start.

**Comment by kenwith** [comment]
@microsmith that would be awesome if you would want to update some examples and descriptions! docs.microsoft.com pulls its content directly from this repository. This repository has a 'master' branch and a 'live' branch. The master branch goes to review.docs.microsoft.com and is currently, unfortunately, behind a Microsoft login. The live branch goes directly to docs.Microsoft.com and once merged it will appear on the live site in a few minutes. To get started you can follow the README that shows up at the bottom of the main repo and the simple method is to use the GitHub web interface. Ping me and I can guide you through it! Looking forward to your contributions!
