### ISSUE TITLE
'NotificationEmails' parameter no longer working in Exchange Online as of June 5th, 2018.

### ISSUE THREAD

**Issue by jsmartbnl** [MicrosoftDocs/office-docs-powershell#1201]
As of June 5th, 2018, using the 'NotificationEmails' parameter no longer works with a session connected to Exchange Online: 

```
A parameter cannot be found that matches parameter name 'NotificationEmails'.
At C:\Windows\TEMP\tmp\tmp.psm1:1873 char:9
+         $steppablePipeline.End()
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Complete-MigrationBatch],  
   ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Complete-MigrationBatch
    + PSComputerName        : outlook.office365.com
```

It's not clear if this is a change in the module or just a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a26d294-9e92-9f8c-974e-ef3778555672
* Version Independent ID: 3ed72874-9342-7c2f-55e7-538074909b51
* Content: [Complete-MigrationBatch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/complete-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/Complete-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/Complete-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jsmartbnl the NotificationEmails parameter currently has the "available only in on-premises Exchange" disclaimer at the top of the description.

Granted, the Applicable: tag after the description has the values "Exchange Server 2013, Exchange Server 2016, Exchange Online" but that's an artifact of the TechNet to docs.microsoft.com migration that I have since fixed.

Thanks for the feedback.
