### ISSUE TITLE
EnableDialInConferencing is not applicable to SfB Online

### ISSUE THREAD

**Issue by naminakao** [MicrosoftDocs/office-docs-powershell#1203]
Based on the following work item, EnableDialinConferencing is not applicable to SfB Online. But [this page](https://docs.microsoft.com/en-us/powershell/module/skype/new-csconferencingpolicy?view=skype-ps) does not mention that. Please add EnableDialinConferencing to "The following parameters are not applicable to Skype for Business Online: ".

Title: 1451047 Remove EnableDialinConferencing as a MeetingPolicy knob that can be customized by tenant admins
URL: https://skype.visualstudio.com/SBS/_workitems/edit/1451047

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17c02d1-21b6-0a17-666f-fedf38e3b42a
* Version Independent ID: 57e7e1ae-a8c1-8355-92db-b77955b68174
* Content: [New-CsConferencingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csconferencingpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsConferencingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsConferencingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@naminakao - please submit a Pull Request to update the article and I will merge it in based on the VSO item you referenced. Instructions for making edits are available in the README here: https://github.com/MicrosoftDocs/office-docs-powershell

**Comment by naminakao** [comment]
@kenwith - I created Pull request.
https://github.com/MicrosoftDocs/office-docs-powershell/compare/master...naminakao:patch-1
