### ISSUE TITLE
Exchange Online Remote PowerShell Module is not a module

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/office-docs-powershell#1205]
Either the name needs to be fixed, or it needs to be made a module.  Having an actual module, especially if it were published to the powershell gallery, would be far preferable.

**Comment by AndreaBarr** [comment]
@jordanmills Thank you for this feedback

I will get this over to the PowerShell team to get the article updated for this. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by yogkumgit** [comment]
@jordanmills Thank you very much for your kind suggestion. At present we are keeping the status quo, however the suggestion is noted can be taken into account in future. 

We are closing this issue and encourage you to keep posting the suggestions that need content update.
Thanks once again for your time.

**Comment by yogkumgit** [comment]
@officedocsbot close
