### ISSUE TITLE
i am a Hotmail user, can i access Hotmail Exchange Online PowerShell?

### ISSUE THREAD

**Issue by caclp** [MicrosoftDocs/office-docs-powershell#1218]
i need to change some settings of my Hotmail Account (eg. ImapForceICalForCalendarRetrievalOption), so i tried to connect exchange online power shell interface, but i got the following error.

PS C:\WINDOWS\system32> $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $LiveCred -Authentication Basic -AllowRedirection
New-PSSession : [outlook.office365.com] Processing data from remote server outlook.office365.com failed with the following error message: [AuthZRequestId=857c5ad4-180a-4361-aa0b-6da395a808a8][FailureCategory=AuthZ-CmdletAccessDeniedException] Failed to get group
 accounts sids of user S-1-2827-409600-2240630158. Exception: AuthzInitializeContextFromSid failed for User SID: S-1-2827-409600-2240630158. For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:12
+ $Session = New-PSSession -ConfigurationName Microsoft.Exchange -Conne ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : IncorrectProtocolVersion,PSSessionOpenFailed
PS C:\WINDOWS\system32>

**Comment by chrisda** [comment]
@caclp, there isn't a PowerShell environment for Hotmail.
