### ISSUE TITLE
Add Option to set Channel Favourites

### ISSUE THREAD

**Issue by makorus** [MicrosoftDocs/office-docs-powershell#1220]
This is not an issue, this is more a feature request.

Please add an option to the "New-TeamChannel" and "Sew-TeamChannel" to enable us setting a specific or a new channel as a favourite for the entire team.

This is extremely important to us; We're planning to move from an open source solution to Microsoft Teams for our students (approx. 400 teachers and 5000 students here). Setting channel favourites seems silly, but is absolutely necessary for us. Not having the possibility to set channel favourites could be a reason NOT to move to Microsoft Teams.

Please add this feature as soon as possible; The rollout should start within 5 weeks.

**Comment by kenwith** [comment]
@makorus - thank you for this feedback. I am going to surface this to the product team and also if I could ask you to open this at: https://microsoftteams.uservoice.com/forums/555103-public because uservoice is where all facets of product team look for exactly this type of feedback. This is really good information. I was just in an all day meeting Monday discussing Teams for Education and I am going to find the right people in that meeting and also email them directly with this one. Thank you for taking the time on providing this!

**Comment by makorus** [comment]
@kenwith - thank you very much for your reply. I've just opened a UserVoice idea.
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/34553959-add-option-to-set-channel-favourites-via-powershel

Thank you for your support.

**Comment by kenwith** [comment]
@makorus - perfect thanks!

**Comment by makorus** [comment]
@kenwith Any news so far? The rollout will start in 3 weeks, not having this option could be a reason for my client not to use MS Teams. Silly, I know, but we're talking about a high number of channels, so I totally get my clients point.

**Comment by kenwith** [comment]
@islubin - do you know if it will be possible soon to set a teams channel as a favorite for an entire team? @makorus has it as a critical requirement for ~4,500 users. Thanks for any info you can share @islubin

**Comment by makorus** [comment]
@islubin and @kenwith any news so far? I'm really really sorry for being so pushy, I hate doing this, but as I previously explained: This will be a dealbreaker for my client's ~4500 users. Some voices at my client's company are already asking for a deadline and are proposing Slack instead. I really need an answer from you guys as soon as possible. Thank you for your understanding

**Comment by kenwith** [comment]
@makorus - it is really important and no need to say sorry. I want to make sure this gets answered ASAP. I think the fastest way will be to open a service ticket in your tenant and they can then either answer right away or escalate to get it answered right away. Here is a quick video: https://www.youtube.com/watch?v=puuOy0sEg1Y 

We will keep pushing on our side too so let us know if you get an answer from the service ticket and also I can update the docs with any new info.

**Comment by islubin** [comment]
@kenwith and @makorus, any feature requests (rather than clarification on powershell documentation) should be funneled and followed up on through UserVoice which is the primary forum for raising concerns or new feature requests.

**Comment by makorus** [comment]
Well, too bad, the client just cancelled the entire project on these grounds. It's just a real shame that we lost a project that HUGE. I'll have to explain this to my supervisor. The customer will be using Slack instead because it offers a better manageability..

@kenwith thanks anyway for your effort.
