### ISSUE TITLE
The Remove-ComplianceTag cmdlet seems to be gone

### ISSUE THREAD

**Issue by MarcoJanse** [MicrosoftDocs/office-docs-powershell#1223]
When connected to Exchange Online, I cannot find the Remove-ComplianceTag cmdlet:

"Get-Command -noun compliance*" doesn't give me any relevant cmdlets to remove tags. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3460f6-0eaa-8f6f-e684-833ce077618c
* Version Independent ID: 7980acef-b066-9e4b-a1cf-408acbb5bdec
* Content: [Remove-ComplianceTag (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-retention/remove-compliancetag?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-retention/Remove-ComplianceTag.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-retention/Remove-ComplianceTag.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MarcoJanse, according to the topic, Remove-ComplianceTag is only available in Security & Compliance Center PowerShell. Those connection instructions are here [Connect to Office 365 Security & Compliance Center PowerShell](https://docs.microsoft.com/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell).

Thanks for the feedback.

**Comment by Ankit0710** [comment]
This doesn't seems to work and we get below error even after connecting to SNC powershell:

![untitled](https://user-images.githubusercontent.com/58715947/70490814-72ae8000-1b25-11ea-8cb7-93143294505e.png)
