### ISSUE TITLE
Admin Support for Teams

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1226]
This module is inherently useless to most admins because it violates the principle of least permission. MS needs to redesign this module so that it can be used by admins (the people that write scripts) without requiring them to be in a Team. Admins can work with Groups and Sites without belonging to them and the same concept is needed for Teams

**Comment by kenwith** [comment]
@DeanGross - thanks for this feedback. I have sent it to the Teams product team to make sure this is on their radar if it wasn't already. Keep feedback coming!
