### ISSUE TITLE
Get-MailboxJunkEmailConfiguration Prefixes Error

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#1232]
When the following conditions are met:

- you connect to Exchange Online via PowerShell as an Admin
- you import cmdlets with prefixes using ```Import-PSSession```
- you run ```Get-MailboxJunkEmailConfiguration``` against some other mailbox

You get the following error:
> Error on proxy command 'Get-MailboxJunkEmailConfiguration -Identity:'user@domain.com'' to server
DM6PR14MB2460.namprd14.prod.outlook.com: Server version 15.20.0841.0000, Proxy method RPS:
The WinRM client cannot process the request. The connection string should be of the form
[<transport>://]<host>[:<port>][/<suffix>] where transport is one of "http" or "https". Transport, port and suffix are
optional. The host may be a hostname or an IP address. For IPv6 addresses, enclose the address in brackets - e.g.
"http://[1::2]:80/wsman". Change the connection string and try the request again.
[Server=BN7PR14MB2209,RequestId=23756254-7e1d-47a7-9c55-fb19832416ad,TimeStamp=6/13/2018 12:45:51 PM] .
    + CategoryInfo          : NotSpecified: (:) [Get-MailboxJunkEmailConfiguration], CmdletProxyException
    + FullyQualifiedErrorId : Microsoft.Exchange.Configuration.CmdletProxyException,Microsoft.Exchange.Management.Stor
   eTasks.GetMailboxJunkEmailConfiguration
    + PSComputerName        : ps.outlook.com

If you run the same cmdlet ```Get-MailboxJunkEmailConfiguration``` against your own mailbox, everything works just fine.

Please kindly advise.

**Comment by chrisda** [comment]
@YuriySamorodov, at the risk of being too basic, you're connecting using the official Exchange Online PowerShell connection instructions [here](https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell)? I connected to an E3 organization and ran `Get-MailboxJunkEmailConfiguration -Identity <SomeOtherMailbox>` and I received results and no errors (there was quite a long pause, however).

And I presume your computer meets all of the prerequisites as described in the Connection topic?

There were reports of PowerShell connection issues back in December (the error was different "Server Error in '/PowerShell-LiveID' Application. Runtime Error") but that was fixed by January.

Is that the only cmdlet that's giving you errors?

**Comment by chrisda** [comment]
@YuriySamorodov, I didn't pick up on the fact that you were using prefixes. I connected again using prefixes on the session ran the command again, and it still worked (`Get-abcMailboxJunkEmailConfiguration -Identity <SomeOtherMailbox>`). If you're using prefixes, are you connecting to multiple PowerShell environments at the same time? If so, what are they, and if you connect only to Exchange Online PowerShell, does the command work?

**Comment by YuriySamorodov** [comment]
@chrisda 
Hello Chris! Thank you for the heads up. Indeed I am using my own script to connect to Office365. You may want to take a look:
https://github.com/YuriySamorodov/Misc/blob/master/New-Office365Session.ps1

I dug a little bit further and noticed the following in the error message:
> Proxy method RPS:
The WinRM client cannot process the request. 

In fact I have implemented "ProxyMethod" parameter earlier this month to overcome an issue where you would not be able to set user photo while connected with PSWS. It looks like that that I faced an issue like this: https://support.microsoft.com/en-us/help/3067263/remote-powershell-cmdlet-fails-in-an-exchange-server-2013-environment

> This issue occurs because the access token of the current Exchange administrator is so large that it exceeds the connection string length limitation in the Windows Remote Management (WinRM) component. The connection string length limitation is hard-coded to 2,048 bytes.


I guess I have to create a PR make a note somewhere in the article:
https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/get-mailboxjunkemailconfiguration?view=exchange-ps

However, should ```get-mailboxjunkemailconfiguration``` be working via PRS?

**Comment by chrisda** [comment]
@YuriySamorodov, yes definitely. All of the Exchange workloads are based on remote PowerShell (it's the only way to connect to cloud-based services or on-premises servers), so all cmdlets are expected to work.

We have a topic that describes how to connect to all Office 365 services from a single Windows PowerShell window: [Connect to all Office 365 services in a single Windows PowerShell window](https://docs.microsoft.com/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window). Perhaps you can use the information in your script?
