### ISSUE TITLE
Unregister-SPOHubSite not accepting GUID for SpoHubSitePipeBind

### ISSUE THREAD

**Issue by stvpwrs** [MicrosoftDocs/office-docs-powershell#1244]
I have a "ghost" Hub Site where the site got deleted before the hub was removed. When trying to use Unregister-SPOHubSite with the GUID of the Hub Site from Get-SPOHubSite it throws the following error:

```
Unregister-SPOHubSite : Cannot bind parameter 'Identity'. Cannot convert value "a3da3d77-4454-4514-8cc6-4f3f2679aa8e" to type "Microsoft.Online.SharePoint.PowerShell.SpoHubSitePipeBind". Error: "SpoHubSitePipeBind Url"
At C:\Users\steve\Desktop\Hub Check.ps1:9 char:33
+ Unregister-SPOHubSite -Identity a3da3d77-4454-4514-8cc6-4f3f2679aa8e
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Unregister-SPOHubSite], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Online.SharePoint.PowerShell.UnregisterSPOHubSite
 
```

I thought this might be a type error with the GUID, but the following didn't help:

`$guid = [GUID]"a3da3d77-4454-4514-8cc6-4f3f2679aa8e"`

```
Unregister-SPOHubSite : Cannot bind parameter 'Identity'. Cannot convert the "a3da3d77-4454-4514-8cc6-4f3f2679aa8e" value of type "System.Guid" to type "Microsoft.Online.SharePoint.PowerShell.SpoHubSitePipeBind".
At C:\Users\steve\Desktop\Hub Check.ps1:11 char:33
+ Unregister-SPOHubSite -Identity $guid
+                                 ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Unregister-SPOHubSite], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Online.SharePoint.PowerShell.UnregisterSPOHubSite
```

I hope I am missing something about passing a GUID, otherwise I think there may be an issue with using a GUID with this CMDLET.

**Comment by AndreaBarr** [comment]
@stvpwrs Thank you for this feedback

I want to make sure this gets handle appropriately. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
