### ISSUE TITLE
Wrong command name display in example

### ISSUE THREAD

**Issue by senjaliya143** [MicrosoftDocs/office-docs-powershell#1247]
On this Page
https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/uninstall-spsolution?view=sharepoint-ps

There are example provided of Uninstall-SPSolution but in example it shows "PS C:\>Uninstall-**SPUserSolution** -Identity contoso_solution.wsp"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19a7b449-a64b-72d8-3d04-20c0810d65ce
* Version Independent ID: 0d44d5ab-998d-d005-26f3-d8fc1ba773af
* Content: [Uninstall-SPSolution (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/uninstall-spsolution?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Uninstall-SPSolution.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Uninstall-SPSolution.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
updated PR..
