### ISSUE TITLE
Preview word on mobile device does not show picture.

### ISSUE THREAD

**Issue by doushichao** [MicrosoftDocs/office-docs-powershell#1252]
Preview word on mobile device does not show picture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f8f0b1e-5bb1-fa0e-c4a4-472f2e79daee
* Version Independent ID: 73e72246-58de-68e3-cc8a-2bfe4b7e0c9c
* Content: [New-OfficeWebAppsFarm (officewebapps)](https://docs.microsoft.com/en-us/powershell/module/officewebapps/new-officewebappsfarm?view=officewebapps-ps)
* Content Source: [officewebapps/officewebapps-ps/officewebapps/New-OfficeWebAppsFarm.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/officewebapps/officewebapps-ps/officewebapps/New-OfficeWebAppsFarm.md)
* Product: **office-online-server-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@doushichao Thank you for this feedback

I want to make sure this gets addressed so I am sending it over to the PowerShell team.

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot unassign @lorenahuangliu

**Comment by dariomws306** [comment]
Hi @doushichao, thank you for your feedback.

Could you kindly give me more detail about the issue you noticed?

Thanks!

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and digging deep into it.  @doushichao We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
