### ISSUE TITLE
New-CsTeamsMeetingPolicy cmdlet not available

### ISSUE THREAD

**Issue by arturopolanco** [MicrosoftDocs/office-docs-powershell#1255]
I realized this cmdlet is not available in any of out tenants, even for global admin.  Though, the remove and set ones are available.  Is it still rolling out or what's going on?

**Comment by kenwith** [comment]
@tomkau is looking into this.

**Comment by islubin** [comment]
@kenwith and @arturopolanco - this is still rolling out.

**Comment by kenwith** [comment]
Added a note about rolling out so that if someone reading about it and they don't see it they will know. Thanks all! Here is the PR: https://github.com/MicrosoftDocs/office-docs-powershell/pull/1308
