### ISSUE TITLE
Search-UnifiedAuditLogs by ObjectIds is not working for group objects

### ISSUE THREAD

**Issue by fredericklin** [MicrosoftDocs/office-docs-powershell#1256]
When viewing the Object ID from the Azure Portal, the Object ID is populated correctly:

![image](https://user-images.githubusercontent.com/15693856/41561595-368a72fc-72ff-11e8-9775-dc5b8a52645e.png)

The Object ID that is returned from a Search-UnifiedAuditLogs query (top-level property) is not populated correctly:

`{"CreationTime":"2018-06-15T00:07:41","Id":"40716041-3e0c-4099-9ed9-aaf4c82d8434","Operation":"Update
group.","OrganizationId":"redacted","RecordType":8,"ResultStatus":"success","UserKey":"redacted","UserType":0,"Version":1,"Workload":"AzureActiveDirectory","ObjectId":"Not
Available","UserId":"redacted","AzureActiveDirectoryEventType":1,"ExtendedProperties":[{"Name":"Classification","Value":"[Confidential] => [Protected]; "},{"Name":"Included Updated
Properties","Value":"Classification"},{"Name":"TargetId.GroupType","Value":"Unified"}],"Actor":[{"ID":"redacted","Type":5},{"ID":"redacted","Type":3},{"ID":"Office 365 SharePoint Online","Type":1},{"ID":"redacted","Type":4},{"ID":"User_redacted","Type":2}],"ActorContextId":"redacted","InterSystemsId":"redacted","IntraSystemId":"redacted","Tar
get":[{"ID":"Group_redacted","Type":2},{"ID":"TST Rename Tester - Remove old email","Type":1}],"TargetContextId":"redacted"}`

Searching for the Object ID does not work and yields no results:

`Search-UnifiedAuditLog -StartDate 6/14/2018 -EndDate 6/18/2018 -ObjectIds 40716041-3e0c-4099-9ed9-aaf4c82d8434`

Searching for "Not Available" gives results:

`Search-UnifiedAuditLog -StartDate 6/14/2018 -EndDate 6/18/2018 -ObjectIds "Not Available"`

**Comment by AndreaBarr** [comment]
@fredericklin Thank you for this feedback

I want to make sure this gets addressed properly. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
