### ISSUE TITLE
New-SPOSite needs corrections/details and examples

### ISSUE THREAD

**Issue by michaelblumenthal** [MicrosoftDocs/office-docs-powershell#126]
There are no descriptions for ANY of the parameters.  There is no example either.  This is well known and likely frequently used functionality. 
Here's an example that could be used:
`New-SPOSite -Url https://mytenant.sharepoint.com/sites/sales -Owner TheSPadmin@mytenant.onmicrosoft.com -StorageQuota 1000 -CompatibilityLevel 15 -LocaleID 1033 -ResourceQuota 300 -Template "STS#0" -TimeZoneId 13 -Title "Sales"`

Note that the documentation must explain what units the storage quota is measured in - is it MB or GB? 
What are the acceptable values for CompatibilityLevel? Where can I find the list of LocaleIDs?  What's a resource?  Where can I find a list of Template IDs?  Where can I find a list of TimeZone IDs?

The problem document is at https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/new-sposite?view=sharepoint-ps

**Comment by tomresing** [comment]
Thanks so much for reading and commenting! I see there is a pending pull request for an example for new-sposite https://github.com/MicrosoftDocs/office-docs-powershell/pull/118 feel free to add descriptions to any you can. It’s easy. Just hit the pencil and enter your description on the .md file in this repository

**Comment by kenwith** [comment]
This has been fixed for most of the SPO cmdlets. Thank you for reporting! Also, any that are still lacking documentation are being tracked in a spreadsheet and @VesaJuvonen  along with the product team are working through them. The community really appreciates your feedback and the docs are better for it. :)
