### ISSUE TITLE
Where has this cmdlet gone from Exchange Online?

### ISSUE THREAD

**Issue by bdelamotte83** [MicrosoftDocs/office-docs-powershell#1271]
The term 'Enable-UMMailbox' is not recognized.......

Get-Command *umm* - nope, not there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e92104-ab9d-d186-95bf-ce95b1b1cd68
* Version Independent ID: d0098c54-1c5c-85c4-f264-8214ba814a92
* Content: [Enable-UMMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/unified-messaging/enable-ummailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/unified-messaging/Enable-UMMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/unified-messaging/Enable-UMMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by bdelamotte83** [comment]
![image](https://user-images.githubusercontent.com/40377918/41576161-2e2f9c20-73c9-11e8-936c-1d7a471f5cf6.png)

**Comment by chrisda** [comment]
@bdelamotte83, I tried Enable-UMMailbox on two different real-world E5 tenants and an E3 tenant and it was available to me.

It appears you get access to the cmdlet by the **UM Mailboxes** RBAC role. You can verify this by running the command:

```
Get-ManagementRoleEntry *\Enable-UMMailbox
```

What results do you get after running that command?

**Comment by bdelamotte83** [comment]
![image](https://user-images.githubusercontent.com/40377918/41627622-5ced7942-7464-11e8-9305-34c9d7901252.png)

**Comment by bdelamotte83** [comment]
Found the issue.
The account for some reason was no longer a global admin for O365. The account had a customized admin setup, which had full administration rights to everything excluding Dynamics 365 and Message Center. I probably should have checked that rather than assuming the account was still a Global Admin. Too many fingers in the pie!
Although I would have excepted being a full Exchange Administrator would have allowed me to run the Enable-UMMailbox cmdlet. I guess not.

**Comment by chrisda** [comment]
@bdelamotte83, I'm glad you found the answer. To see the permissions that are required to run a specific cmdlet, see [Find the permissions required to run any Exchange cmdlet](https://docs.microsoft.com/powershell/exchange/exchange-server/find-exchange-cmdlet-permissions).
