### ISSUE TITLE
Support RPS Proxy Method for Exchange Online Remote Powershell Module with MFA

### ISSUE THREAD

**Issue by AzureGuineaPig** [MicrosoftDocs/office-docs-powershell#1287]
Need to Set-UserPhoto, specifying the connection URI of https://outlook.office365.com/powershell-liveid/?proxyMethod=RPS.

This is not currently supported in the Exchange Online Remote Powershell Module when used in conjunction with the Connect-EXOPSSession cmdlet.  

Can't use basic auth, as the connecting account has MFA enabled.

Disabling MFA is NOT an acceptable workaround.

**Comment by chrisda** [comment]
@AzureGuineaPig, apparently, you can enable the Trusted IPs feature to allow regular ExO PowerShell connections from defined intranet IPs without disabling MFA on the account. For details, see the last bullet in the What do you need to know before you begin? section at: https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.

Does that help?
