### ISSUE TITLE
please update this article to include the new -shared parameter 

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/office-docs-powershell#1294]
This also requires a manual invocation of /prepareAD, as explained here: https://support.microsoft.com/en-us/help/4133605/cmdlets-to-create-modify-remote-shared-mailbox-in-on-premises-exchange

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3d8932-e958-6be5-1dd7-b0731115c4dd
* Version Independent ID: 2345fd23-d401-fbc7-38c0-4eb3c7695f0e
* Content: [Enable-RemoteMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/enable-remotemailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/Enable-RemoteMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/Enable-RemoteMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Topic updated. Closing
