### ISSUE TITLE
Says it's available in exchange online, but it is not

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/office-docs-powershell#1298]
this cmdlets is not available in exo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c6c666-7221-7984-82a5-d731fee0ac3d
* Version Independent ID: 6970ac1a-0aaa-c625-24db-e3db2296b6f8
* Content: [Search-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/Search-Mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jordanmills, to use the cmdlet, you need to have the Mailbox Search or Mailbox Import Export roles, and by default, those aren't assigned to any role groups (including Organization Management). Typically, we call that sort of thing out, but it was missing from this topic for some reason, so I added it.

Thanks for the feedback
