### ISSUE TITLE
Owner must also have a mailbox

### ISSUE THREAD

**Issue by Lady-MCSE** [MicrosoftDocs/office-docs-powershell#1300]
I would suggest this change for the -Owner switch: "Specifies the user name of the site collection’s primary owner. The owner must be an email address for a user instead of a security group or an email-enabled security group." Using a demo tenant, I created a new user account with username@demotenant.onmicrosoft.com.  The account exists and can be used to log onto sharepoint sites in the demo tenant.  But using New-SPOSite with the -Owner switch and specifying that username@demotenant.onmicrosoft.com wouldn't work.  Looking deeper, the account didn't have an exchange license, and in Exchange admin it had no mailbox.  Once I specified one of the pre-created accounts that came with the tenant, things were good.  Note that the old SP2010 command switch was -OwnerAlias and also could not take a simple username, required the valid email address.  Thanks!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5af79bd0-1525-b5d8-b65a-05f9b5a13267
* Version Independent ID: 1b98f96f-942b-679d-b43f-1dc74da1e547
* Content: [New-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/new-sposite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@Lady-MCSE   Thank you very much for your kind feedback. Considering your valuable feedback, we have logged this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

User Voice Link: https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/17485486-provide-feature-to-identify-sharepoint-site-from-g

**Comment by Lady-MCSE** [comment]
Thank you for the update.  My suggestion was more about the documentation than about a feature change.  The documentation currently states that the -owner switch "Specifies the user name of the site collection’s primary owner. The owner must be a user instead of a security group or an email-enabled security group." This statement as written is true, however I would still suggest changing "user name" and "user" to read "email address" because the command doesn't work when used with an account that doesn't also have an email assigned. (Note that a typical user principal name for an account may look like an email address and still not work with this command.)

**Comment by yogkumgit** [comment]
@Lady-MCSE Thank you very much for your comment. I will get it reviewed again and update here.

**Comment by CarlLee165** [comment]
Hi all, I also experienced the issue with -Owner but I'm struggling with the New-SPOSite commandlet not passing the -Title parameter. All of my sites are getting created with "<OurOrganizationName> Team Site" as their title and not the text we provided.

**Comment by get-itips** [comment]
Hi @Lady-MCSE Thanks for your comments and suggestion, we really appreciate them.
I tested in a lab, and I was able to confirm that use the Owner parameter works when the user account is mail enabled, but you need to specify user account name always, for example, if the user is jhealy@contoso.com but email address is joe.healy@contoso.com you will have to use jhealy@contoso.com as Owner parameter. I will add a note to the documentation thanks to your finding.

@CarlLee165 I tested in a lab an Title parameter was correctly honored.

**Comment by CarlLee165** [comment]
Hi all,
Thank get-itips, I did some additional testing after my post and found my issue. It was related to the "Owner" not having an email address attached.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Lady-MCSE  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
