### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by accomando** [MicrosoftDocs/office-docs-powershell#1305]
In the example the identity is passed as the relative url of the OOB page:"C:\PS&gt;Set-SPCustomLayoutsPage -Identity "_layouts/accessdenied.aspx" " ;  but value must be one of the following: None, AccessDenied, Confirmation, Error, Login, RequestAccess, Signout, or WebDeleted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5547462-66be-d856-b49c-f7dc205fb8e8
* Version Independent ID: 2dc13864-106a-d2ca-98bb-bcf9636dcf21
* Content: [Set-SPCustomLayoutsPage (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/Set-SPCustomLayoutsPage?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPCustomLayoutsPage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPCustomLayoutsPage.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@accomando can you please create a pull request and add the specific change to the example.?
