### ISSUE TITLE
Add Change Log

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1318]
Please add a Change Log that documents the cmdlet changes when new versions of the management shell are issued.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65bf2c0b-b0ec-2748-e47e-af66011efe30
* Version Independent ID: be3968f4-d766-0b45-384b-c51c47328a86
* Content: [SharePoint Online PowerShell](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/index?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

The closest thing we have right now is the commit history: https://github.com/MicrosoftDocs/office-docs-powershell/commits/master . I agree it is ideal for a cultured list though and will make sure the doc team gets the feedback
