### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1328]
Please provide installation instructions or a link to that information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102a89dc-8bb7-e76e-f570-3d6bde7e8308
* Version Independent ID: 3eb619c5-db95-9a42-4c83-9778572f00fc
* Content: [SharePoint Server Cmdlets](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
the intent of this page is not for installation instructions, as there is no installation for Server cmdlets. The link goes to the listing of all Server cmdlets.

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

It looks like Kirk handled your issue. I am going to close this issue. If it's not resolved please reopen the issue.
