### ISSUE TITLE
-MessageCopyForSendOnBehalfEnabled available for user mailboxes

### ISSUE THREAD

**Issue by siebeh** [MicrosoftDocs/office-docs-powershell#1337]
`-MessageCopyForSendOnBehalfEnabled` and `-MessageCopyForSentAsEnabled` are available for user mailboxes as well as shared mailboxes.  

https://blogs.technet.microsoft.com/exchange/2017/03/28/sent-items-behavior-control-comes-to-exchange-online-user-mailboxes/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5b0c5d-0466-d55a-1f7b-0b2d25a316fd
* Version Independent ID: 07b0c093-eb6b-4834-3cd4-d8f2af6ca0f5
* Content: [Set-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@siebeh, I fixed this. The updated topic will publish soon.
