### ISSUE TITLE
InPlaceHolds - people need acces

### ISSUE THREAD

**Issue by Tarjei99** [MicrosoftDocs/office-docs-powershell#1339]
Hi,

When people leave a company, there might be a in-Place hold on their mailbox. It is very common that their co-workers will need to access their mailbox, but not change anything.

So it would help a lot if users of active mailboxes could read the content of soft deleted mailboxes after being given access to them (Add-MailboxPermission).

**Comment by AndreaBarr** [comment]
@Tarjei99 Thank you for this feedback

I know the product teams are always looking for user feedback and how to make the OneDrive / SharePoint better. They keep a close tab on User Voice [https://sharepoint.uservoice.com](https://sharepoint.uservoice.com) and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too. 
 
Thank you for your contribution to make the docs better! Much appreciated!
