### ISSUE TITLE
set-team access type is not valid

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/office-docs-powershell#1350]
doesn't seem to work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd6bccff-1bef-c88c-ff70-2ccdfb48ecc0
* Version Independent ID: 01f33478-352d-c7ae-0c49-784fa1c1fd67
* Content: [Set-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/set-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@bakerm00 - thank you for submitting feedback. I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs. Let's keep this open until resolved.

**Comment by bakerm00** [comment]
its a painful process - but 0.9.3 does not have "-accesstype" available.  so what version of the module does?

**Comment by bakerm00** [comment]
I got the default response that "this page you reference does say beta" - you got some missing code; please fix.

**Comment by bakerm00** [comment]
update from service ticket
<>
"As per your query I have consulted with my backend PG team for the Global availability of accesstype parameter in Set-Team powershell command as it is still in Beta phase.
Unfortunately there is no ETA at the moment which they can provide and when will it be available GA.
Also we have tried inhouse and this optional parameter is not available for us too."
<ends>

**Comment by kenwith** [comment]
Thanks for fix! and thanks for reporting @bakerm00 Here is Pull Request that fixes: https://github.com/MicrosoftDocs/office-docs-powershell/pull/1368  Also, these are all open source now so if you see something and what to make an update go ahead and submit a PR. Thank you!
