### ISSUE TITLE
Set-OMEConfiguration and missing parameters

### ISSUE THREAD

**Issue by KatjaBF** [MicrosoftDocs/office-docs-powershell#1354]
Hi!
The descriptions of the following parameters are missing from Set-OMEConfiguration cmdlet.

IntroductionText
ReadButtonText

Br Katja

https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/set-omeconfiguration?view=exchange-ps

**Comment by KatjaBF** [comment]
Hi!
The optional parameters name is ReadButtonText.

Br Katja

**Comment by KatjaBF** [comment]
Sorry. Wrong button

**Comment by chrisda** [comment]
@KatjaBF, I fixed it. As described in your other Issue #1363, I've alerted the responsible parties to complete the descriptions for these new but empty parameters. Feed free to take a crack at the description yourself.

Thanks for the feedback.
