### ISSUE TITLE
This parameter is reserved for internal Microsoft use

### ISSUE THREAD

**Issue by fergusstrachan** [MicrosoftDocs/office-docs-powershell#1364]
Come on, if the command isn't ready for use, don't publish it!
Are you saying it's not yet supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b7e2c02-ff5d-7c4b-8f34-69597480f600
* Version Independent ID: 364f7cd0-3fd1-6401-cb46-6fb104b97ac3
* Content: [Set-MailboxPlan (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailboxplan?view=exchange-ps#required-parameters)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-MailboxPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-MailboxPlan.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@fergusstrachan, I confirmed the parameters that were really documented are available, and the ones that contain "reserved for internal Microsoft use" aren't available so I removed them.

Thanks for the feedback.

**Comment by fergusstrachan** [comment]
Thanks, I think. :-)
I haven't tried them yet so don't know if they work, but in any case when will they be available?

**Comment by chrisda** [comment]
@fergusstrachan, the documented parameters (the ones that didn't have "reserved for internal Microsoft use" for the description)  have been available for some time. The updated topic published a few days ago.

**Comment by fergusstrachan** [comment]
Sorry Chris, I wasn't clear. I was referring to the "internal only" switches, when will they be available?

**Comment by chrisda** [comment]
@fergusstrachan, I don't think those 'reserved for internal Microsoft use' parameters' were ever available to 'ordinary' Live@edu/Office 365 customers (the exception might be Office 365 Dedicated). I can go back as far as 2009, and the vast majority parameters were 'reserved for internal Microsoft use' even back then.
