### ISSUE TITLE
Palette not pallette

### ISSUE THREAD

**Issue by Lady-MCSE** [MicrosoftDocs/office-docs-powershell#1374]
In Example 2, the variable $themepallette (two L's) is used which doesn't match the $themepalette used further up, and is an incorrect spelling of the word palette.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a99ae6ea-f1ca-1d6f-bdda-abc8cf4082ae
* Version Independent ID: 066c87bc-6767-ae13-7f31-d9591f7e0536
* Content: [schema: 2.0.0](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spotheme?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTheme.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTheme.md)
* Service: **sharepoint-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by VesaJuvonen** [comment]
Fixed with #1375.
