### ISSUE TITLE
PS script to Pull user Mailbox MFA status 

### ISSUE THREAD

**Issue by ShafiqUK** [MicrosoftDocs/office-docs-powershell#1382]
Hi, 

I am looking for PS script to pull User mailbox data with MFA status (Enable, Disbaled or Enforced) (excluding shared mailbox). Thanks

**Comment by AndreaBarr** [comment]
@ShafiqUK Thank you for this feedback

I want to make sure you get the script you need. Support can handle this to resolution.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
