### ISSUE TITLE
Start-SPOSiteContentMove - More information would be very helpful

### ISSUE THREAD

**Issue by GaetanLongree** [MicrosoftDocs/office-docs-powershell#1386]
Currently looking into the possibility of automating moving SharePoint online sites through PowerShell, however due to lack of documentation, I am unable to assert whether this command could help me or not.
Since I have not test environment at my disposal, it's hard for me to conduct any sort of conclusive tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab43a7d9-79d4-5f40-f49f-1f90c2af1583
* Version Independent ID: a54c713c-4995-30d6-c500-bd13152e8190
* Content: [Start-SPOSiteContentMove (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/start-spositecontentmove?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteContentMove.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteContentMove.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hi @GaetanLongree how are you? thanks for your suggestion, could you please be more specific on the information you want to be in the documentation for that cmdlet?

Thanks

**Comment by GaetanLongree** [comment]
This dates back from when I was working on a project that needed an automated method of moving subsites between sites on SharePoint Online.

As my original description states, the documentation at the time was not complete and did not provide enough information on the function/features, scope and uses of this command.

Since I'm no longer working on the project, I can't elaborate further on the follow-up of this command uses for that specific use case.

**Comment by get-itips** [comment]
Hi @GaetanLongree Exactly, documentation at the time was different, now it's more complete about function and features. Thanks!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @GaetanLongree  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
