### ISSUE TITLE
-UnScopedTopLevel not available on my Tenants

### ISSUE THREAD

**Issue by dahager** [MicrosoftDocs/office-docs-powershell#1387]
Hi!
The parameter -UnScopedTopLevel for the command New-ManagementRole is not avaialble on my Exchange Online Tenants, tried it on different tenant.

Please check that and if it is not part of EXO Powershell please modify 

Applies to: | Exchange Server 2010, Exchange Server 2013, Exchange Server 2016, **Exchange Online, Exchange Online** Protection
-- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aad91a-004d-a2bc-660b-eab1f7f95c76
* Version Independent ID: d084f4fc-2742-9363-1c7d-ed3dbc84af8a
* Content: [New-ManagementRole (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/role-based-access-control/new-managementrole?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/role-based-access-control/New-ManagementRole.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/role-based-access-control/New-ManagementRole.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dahager, I determined that the UnScopedTopLevel switch is a) only available in on-premises Exchange and b) is only available by the Unscoped Role Management role, which isn't assigned to any role groups by default.

This situation also affects the Add-ManagementRoleEntry, New-ManagementRoleAssignment, Remove-ManagementRole, and Set-ManagementRoleEntry cmdlets, so I fixed them.

Furthermore, I also found that the Force switch is only available in the cloud, so I fixed that, too.

Thanks for the feedback.
