### ISSUE TITLE
Available codes

### ISSUE THREAD

**Issue by StacyRacks** [MicrosoftDocs/office-docs-powershell#1391]
Needs a list of available values for parameters 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c70f90-3a15-483f-5715-cfcede60ac67
* Version Independent ID: e2fcf849-3d75-91c5-31f5-be2fbc6f945f
* Content: [Set-SPWebApplicationHttpThrottlingMonitor (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spwebapplicationhttpthrottlingmonitor?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPWebApplicationHttpThrottlingMonitor.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPWebApplicationHttpThrottlingMonitor.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
What specifically are you looking for? Not all parameters have well defined values. As noted in some of the parameters, you need to use the `get-` cmdlet to return the available values.

**Comment by StacyRacks** [comment]
Was looking for the different values that can be used for category and counter combinations



Processor  % processor time - https://blogs.technet.microsoft.com/wbaer/2010/04/22/http-request-monitoring-and-throttling/
Asp.net   requests current - https://social.technet.microsoft.com/Forums/office/en-US/f39ea4cd-b7e8-429d-ac5a-72a9f7119312/http-throttling-aspnet-requests-current-50018


Memory available mbytes

Thanks in advance for any changes,  the info is out there on the web, just thought it would be a nice add to this page https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spwebapplicationhttpthrottlingmonitor?view=sharepoint-ps

**Comment by tseward** [comment]
Open perfmon.msc. Based on what you see, those are the categories/counters you can specify (though not all will be useful). There are too many values to list.

**Comment by Techwriter40** [comment]
@StacyRacks thank you for your comment. There are too many variables to list based on your environment, so there is no set values that this cmdlet can return. For now, I am closing the comment, but feel free to reopen another comment or pull request to request a specific change.  thanks

**Comment by StacyRacks** [comment]
Thanks Kirk,  seems like it can pull back the counters from within perfmon for the category, makes sense, thanks for looking into it.


Thank you for choosing Rackspace Hosting, the #1 cloud company

[cid:image001.png@01D415E8.20721390]

**Comment by StacyRacks** [comment]
Thanks, really appreciate it, makes sense


Thank you for choosing Rackspace Hosting, the #1 cloud company

[cid:image001.png@01D415E8.A7B267B0]
