### ISSUE TITLE
PopSuppressReadReceipt

### ISSUE THREAD

**Issue by greg2k** [MicrosoftDocs/office-docs-powershell#1398]
Any explanation as to why -PopSuppressReadReceipt defaults to $false, when this behavior is contrary to the "spirit", so to speak, of the Read Receipt feature? Many senders outside Office 365 get false positives and assume their recipient has read the message, when theoretically all they've done is received the message in their email client after a POP download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9398dd25-94e7-a8f8-6d97-f150173bb4da
* Version Independent ID: 6f19f636-20d5-bc97-68be-30b313f107b8
* Content: [Set-CASMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-casmailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-CASMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-CASMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@greg2k, according to the parameter description, the value $false generates two read receipts: one on message download, and other when the message is opened.

Is this description accurate or does I need to be changed?
