### ISSUE TITLE
Is there a way i can associate a sharepoint site to Unified Group manually?

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/office-docs-powershell#1400]
Get-UnifiedGroup &lt;xyz@contoso.com&gt; returns an object that has a member named SharePointSiteUrl property.. which is get and set property.. technically if I change this, how can I write back?

or Set-UnifiedGroup doesn't have a way to override the sharepoint site url's or override the YammerEmailAddress… is there some other way I can do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd7d69db-be49-179e-94ce-635337c98d07
* Version Independent ID: 9e372e66-5c7e-4d9a-56de-a35ae353fa09
* Content: [Set-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@mganeshphani Thank you for this feedback

I want to make sure your unified group issue gets handled appropriately. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
