### ISSUE TITLE
when we can have sharepoint online commands in mac

### ISSUE THREAD

**Issue by peterremote1980** [MicrosoftDocs/office-docs-powershell#1401]
hi, when we can have sharepoint online commands in mac?

**Comment by VesaJuvonen** [comment]
Whenever we get our CSOM APIs and PowerShell implemented in the .NET Core version. There's currently no ETA, but work is in the roadmap. For now, you can use the Office 365 CLI in the non-Windows machine to manipulate some of the tenant settings - https://pnp.github.io/office365-cli/.
