### ISSUE TITLE
Workloads Affected

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1402]
Please identify the workloads that are affected when the ConnectorsEnabled value is set to False. My testing indicates that this affects Outlook Web App, Teams and SharePoint Online, but there may be other services that are also impacted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3ab3f0-cc05-e279-8876-6da0b323bcac
* Version Independent ID: bfb49814-d60b-564a-25cc-f902dfa42b10
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DeanGross, the workloads affected are Outlook, SharePoint, Teams, and Yammer. I've updated the topic accordingly.

Thanks for the feedback.
