### ISSUE TITLE
-Principals

### ISSUE THREAD

**Issue by 4rtorias** [MicrosoftDocs/office-docs-powershell#1418]
"Principals" is a required parameter, yet there is no example of how to use it and the description is about as unhelpful as possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 114697af-1b15-2582-49af-7ae2a8fe1cb0
* Version Independent ID: 6ed31c1e-1706-318b-5030-0e74dd9e875e
* Content: [Register-SPOHubSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/register-spohubsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Register-SPOHubSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Register-SPOHubSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by VesaJuvonen** [comment]
Thanks for reporting this. We have now updated the sample accordingly and included some additional description on the documentation.

**Comment by 4rtorias** [comment]
Awesome, thanks!!


Respectfully,

Matthew Silcox

Senior Systems Administrator                                                    [cid:4714d2db-c38a-4985-9f2c-a8376d061840]     330.672.1290<mailto:msilcox@kent.edu>
Infrastructure Engineering | Information Services                      [cid:138fb8bb-b5b5-42c5-b604-6cfa3dce15d5]     msilcox@kent.edu<mailto:msilcox@kent.edu>
Kent State University


   [cid:985b2fa1-0e06-4f9f-8702-671c6dff6b53] <https://www.certmetrics.com/amazon/public/badge.aspx?i=3&t=c&d=2017-05-01&ci=AWS00247756>
________________________________

**Comment by beckybertram** [comment]
Is it possible to also show an example of how you pass in the Principals parameter? Is it usernames or what? I can't find examples anywhere. Thanks!
