### ISSUE TITLE
Please add 30 days data limitation for this command.

### ISSUE THREAD

**Issue by liyunjun** [MicrosoftDocs/office-docs-powershell#1436]
Seems like this command can only get the latest 30 days data, the old data is removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c152757-94e4-ddb4-6322-9dadc33b130d
* Version Independent ID: 3292ae2d-f7e6-ef13-9287-de083147a1cd
* Content: [Get-CsUserSession (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csusersession?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsUserSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsUserSession.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
This was added. Thanks for reporting and sorry for delay in closing.
