### ISSUE TITLE
MFA?

### ISSUE THREAD

**Issue by BeMor** [MicrosoftDocs/office-docs-powershell#1437]
Please could you advise how this can be done with an account which has MFA enabled? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Office 365 Security & Compliance Center PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md)
* Service: **o365-security-and-compliance**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@BeMor, see the topic: [Connect to Office 365 Security & Compliance Center PowerShell using multi-factor authentication](https://docs.microsoft.com/powershell/exchange/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell).
