### ISSUE TITLE
Need to assign role for this to be available

### ISSUE THREAD

**Issue by GarrettRobinson** [MicrosoftDocs/office-docs-powershell#1440]
As stated in New-GlobalAddressList, and also applies here:
By default in Exchange Online, the Address List role isn't assigned to any role groups. To use any cmdlets that require the Address List role, you need to add the role to a role group. For more information, see the "Add a role to a role group" section in the topic, Manage role groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cecbe245-8bcd-0247-f334-01754d0a69d1
* Version Independent ID: c9c2f732-afb3-38b6-c378-4fe3a909a918
* Content: [New-AddressList (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/email-addresses-and-address-books/new-addresslist?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/email-addresses-and-address-books/New-AddressList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/email-addresses-and-address-books/New-AddressList.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@GarrettRobinson, I cleaned up the Address List**s** role call-out in the existing cmdlets (\*-AddressBookPolicy, \*-GlobalAddressList, and \*-OfflineAddressBook), and added it to the \*-AddressList cmdlets. I also removed it from some other on-premises only cmdlets that didn't need it.

Thanks for the feedback
