### ISSUE TITLE
terrible

### ISSUE THREAD

**Issue by 2009gautamkumar** [MicrosoftDocs/office-docs-powershell#1443]
terrible

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4447fcc6-9add-90b4-227f-357ebaf3ae94
* Version Independent ID: 2b94ca7b-6651-de39-0f77-fcd6b37a2da5
* Content: [Test-OutlookConnectivity (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/test-outlookconnectivity?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Test-OutlookConnectivity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Test-OutlookConnectivity.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@2009gautamkumar, is there anything specific? I'm happy to make any updates that you might find helpful...
