### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/office-docs-powershell#1446]
Returns an error:
Import-CsUserData : The term 'Convert-CsLegacyUserData' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b25266b4-534a-11da-e13b-8fa8b8ede85a
* Version Independent ID: ad597f5f-b460-d8cc-c257-3ddbfb7270a3
* Content: [Import-CsUserData (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/import-csuserdata?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Import-CsUserData.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Import-CsUserData.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@jordanmills - Sorry for the delay on this.  This should work and I am not sure why it isn't and am not a subject matter expert on this one. I think the best way forward is if you can open a service ticket / support request so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.
