### ISSUE TITLE
SharePoint Online Management Shell does not work because of certificate issues

### ISSUE THREAD

**Issue by ChrisAV81** [MicrosoftDocs/office-docs-powershell#1447]
Latest version of SharePoint Online Management Shell (16.0.7813.1200) doesn't work. When trying to import the module, I get the following error message. Seems to be some kind of certificate issue.

PS C:\windows\system32> import-module Microsoft.Online.SharePoint.PowerShell
import-module : Errors occurred while loading the format data file:
C:\Program Files (x86)\SharePoint Online Management Shell\Microsoft.Online.SharePoint.PowerShell\Microsoft.Online.Share
Point.PowerShell.ps1xml, , C:\Program Files (x86)\SharePoint Online Management Shell\Microsoft.Online.SharePoint.PowerS
hell\Microsoft.Online.SharePoint.PowerShell.ps1xml: The file was skipped because of the following validation exception:
 File C:\Program Files (x86)\SharePoint Online Management Shell\Microsoft.Online.SharePoint.PowerShell\Microsoft.Online
.SharePoint.PowerShell.ps1xml cannot be loaded. A certificate chain processed, but terminated in a root certificate whi
ch is not trusted by the trust provider..
At line:1 char:1
+ import-module Microsoft.Online.SharePoint.PowerShell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by kenwith** [comment]
@ChrisAV81 - thank you for submitting feedback. I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. They can help nail down certificate issue and what will be a solution.

Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
