### ISSUE TITLE
remove no longer exist parameters from set-csmediaconfiguration article

### ISSUE THREAD

**Issue by bament-hun** [MicrosoftDocs/office-docs-powershell#1451]
We are still listing no longer available optional parameters in the New/Set-CsMediaConfiguration articles.
https://docs.microsoft.com/en-us/powershell/module/skype/set-csmediaconfiguration?view=skype-ps
https://docs.microsoft.com/en-us/powershell/module/skype/new-csmediaconfiguration?view=skype-ps

it cause misunderstanding in our customers

Currently listed optional parameters
  [-EnableQoS &lt;Boolean&gt;]
   [-EnableSiren &lt;Boolean&gt;]
   [-EncryptionLevel &lt;EncryptionLevel&gt;]
   [-MaxVideoRateAllowed &lt;MaxVideoRateAllowed&gt;]
   [-Force]
   [-WhatIf]
   [-Confirm]
   [-EnableAdaptiveBandWidthEstimation &lt;Boolean&gt;] - not available anymore
   [-EnableG722StereoCodec &lt;Boolean&gt;] - not available anymore
   [-EnableH264Codec &lt;Boolean&gt;] - not available anymore
   [-EnableInCallQoS &lt;Boolean&gt;] *Only in Skype for business server
   [-EnableRtpRtcpMultiplexing &lt;Boolean&gt;] *Only in Skype for business server
   [-InCallQoSIntervalSeconds &lt;UInt16&gt;] *Only in Skype for business server
   [-EnableVideoBasedSharing &lt;Boolean&gt;] *Only in Skype for business server
   [&lt;CommonParameters&gt;]
New parameter which is missing from the articles:
    -WaitIceCompletedToAddDialOutUser -available parameter in the latest build for Skype for Business server 2015
no data what is this parameter for.

Supporting Data:
they were a while ago already depreciated:
confirmed in my lab environment by using the latest Skype for Business Server 2015 or Lync Server 2013 bits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d1b5f4d-f6bc-df5f-eb7f-dbfde16a8c12
* Version Independent ID: 32115627-278f-a31a-6529-8428138e7e43
* Content: [Set-CsMediaConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csmediaconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsMediaConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsMediaConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by bament-hun** [comment]
@kenwith #1452 
As requested, attached the Lync and SkypeForBusiness module, captured by platyPS
[lync_module.zip](https://github.com/MicrosoftDocs/office-docs-powershell/files/2205046/lync_module.zip)
[SkypeForBusiness_module.zip](https://github.com/MicrosoftDocs/office-docs-powershell/files/2205038/SkypeForBusiness_module.zip)

**Comment by kenwith** [comment]
One last note, we are currently working on the process to get the XML generated from the Markdown checked into the code for the product so that when you run PlatyPS or Get-Help you will see the recent content from GitHub. Right now there is a delta between XML in product and the Markdown on GitHub. Should be solved soon though.

**Comment by bament-hun** [comment]
@kenwith I will give it a try. I working a lot with officedocs and got frequent requests from our customers to amend or confirm some articles on UC. So every knowledge on this is useful for later usage. Let you know how it went

**Comment by bament-hun** [comment]
@kenwith performed the required changes, however I cannot see how can I add the Lync 2013 part, do I need to manually edit the parameters which is not available in Lync Server 2013.
for example put some and additional note in the description *Skype For Business Server 2015 only 
Is there any official way how contributors can do this?

**Comment by kenwith** [comment]
@bament-hun - you are a machine of efficiency! This is awesome! You deserve an award for helping the community with this. :)

There is an 'applicable' tag for the entire cmdlet that shows up in the metadata at the very top of the file when you are in edit mode.

There is also an 'applicable' tag for each parameter that shows up in the metadata for it. So a cmdlet might be applicable for 2013 and 2015 but a parameter might have only appeared in 2015 so on that particular cmdlet the applicable would only show for 2015.

Let me know if that makes sense and I can provide more info.

**Comment by bament-hun** [comment]
@kenwith it makes sense, however I cannot find my edited changes from Friday. it has been declined and I need to do again or?

**Comment by kenwith** [comment]
@bament-hun - were you able to submit a pull request? It should show up here: https://github.com/MicrosoftDocs/office-docs-powershell/pulls

Then when product team approves it gets 'merged' into the documentation.

**Comment by bament-hun** [comment]
@kenwith ok, missed to click on the Create pull request at the end, but at least I was able to add the applicable tag

**Comment by kenwith** [comment]
@bament-hun - awesome! I will work on getting these approved and merged in. Great work!
