### ISSUE TITLE
remove no longer exist parameters from new-csmediaconfiguration article

### ISSUE THREAD

**Issue by bament-hun** [MicrosoftDocs/office-docs-powershell#1452]
We are still listing no longer available optional parameters in the New/Set-CsMediaConfiguration articles.
https://docs.microsoft.com/en-us/powershell/module/skype/set-csmediaconfiguration?view=skype-ps
https://docs.microsoft.com/en-us/powershell/module/skype/new-csmediaconfiguration?view=skype-ps

it cause misunderstanding in our customers

Currently listed optional parameters
  [-EnableQoS &lt;Boolean&gt;]
   [-EnableSiren &lt;Boolean&gt;]
   [-EncryptionLevel &lt;EncryptionLevel&gt;]
   [-MaxVideoRateAllowed &lt;MaxVideoRateAllowed&gt;]
   [-Force]
   [-WhatIf]
   [-Confirm]
   [-EnableAdaptiveBandWidthEstimation &lt;Boolean&gt;] - not available anymore
   [-EnableG722StereoCodec &lt;Boolean&gt;] - not available anymore
   [-EnableH264Codec &lt;Boolean&gt;] - not available anymore
   [-EnableInCallQoS &lt;Boolean&gt;] *Only in Skype for business server
   [-EnableRtpRtcpMultiplexing &lt;Boolean&gt;] *Only in Skype for business server
   [-InCallQoSIntervalSeconds &lt;UInt16&gt;] *Only in Skype for business server
   [-EnableVideoBasedSharing &lt;Boolean&gt;] *Only in Skype for business server
   [&lt;CommonParameters&gt;]
New parameter which is missing from the articles:
    -WaitIceCompletedToAddDialOutUser -available parameter in the latest build for Skype for Business server 2015
no data what is this parameter for.

Supporting Data:
they were a while ago already depreciated:
confirmed in my lab environment by using the latest Skype for Business Server 2015 or Lync Server 2013 bits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cfe4ca2-2937-6d43-d5a5-6ff69f875b12
* Version Independent ID: 201bfd87-be00-ab2e-38b8-0a3a7c3f0081
* Content: [New-CsMediaConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csmediaconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsMediaConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsMediaConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@bament-hun - I think this was in the pull request. If not please re-open. Please let me know if you are internal to Microsoft too and I can connect you with the product team so you can work with them to get clarity on how the docs can be better.
