### ISSUE TITLE
-SearchQuery section does not have a proper reference link

### ISSUE THREAD

**Issue by behrouzamiri** [MicrosoftDocs/office-docs-powershell#1453]
-SearchQuery section, reference you to a web page which speaks about KQL and some hints about using it in "SharePoint" and not Exchange.
it would be great if you refer us to a page that actually show us any searchquery keyword that we can use in exchange, for example to search only inside SENT items folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c6c666-7221-7984-82a5-d731fee0ac3d
* Version Independent ID: 6970ac1a-0aaa-c625-24db-e3db2296b6f8
* Content: [Search-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/search-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@behrouzamiri, I conferred with the subject matter owner, and apparently the best topic we have for Exchange properties and KQL is  https://docs.microsoft.com/exchange/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators, so I replaced the existing link.

Thanks for the feedback.

**Comment by behrouzamiri** [comment]
Thanks @chrisda , this new reference is awesome. I couldn't find this page via search and I was always end up to your article, which actually is a pretty good article, but I was not able to go further. now it's fixed because of your kindness. thanks a lot.
