### ISSUE TITLE
Remove-SPAppPrincipalPermission and set-spappprincipalpermission mismatch on scope param

### ISSUE THREAD

**Issue by waaromikniet** [MicrosoftDocs/office-docs-powershell#1454]
In the Remove-SPAppPrincipalPermission the parameter scope is mentioned. It has different values than the scope param in set-spappprincipalpermission. The params described in Remove-SPAppPrincipalPermission don't work for SharePoint 2013. But you can use the same scope variables described in set-spappprincipalpermission

#1455

**Comment by AndreaBarr** [comment]
@waaromikniet Thank you for this feedback

I will get this over to the PowerShell team for updating. Thank you for taking the time to make the docs better. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @waaromikniet 
Thanks for your feedback and finding this out! we appreciate it.
Values for Scope had been updated after you created this issue https://github.com/MicrosoftDocs/office-docs-powershell/commit/f25a56c0dfe2a5cdd32597ef42e2757e1dc60cd7#diff-6e03e1e61242e6303d6ac3b57e94da45 to match to those of Set-SPAppPrincipalPermission

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @waaromikniet  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
