### ISSUE TITLE
LinkedReceiveConnector is discontinued in Exchange 2013, 2016

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/office-docs-powershell#1456]
Hi, this Option is no longer available in Exchange 2013 and 2016. But the description of the Article tells us that this options are valid for Exchange 2010, 2013 and 2016 which is not true for this command option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7b9147-7a6d-765b-86fe-a77d360f07b6
* Version Independent ID: 1e07c553-cb5c-84d7-2824-4675db73dbd3
* Content: [Set-SendConnector (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/set-sendconnector?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Set-SendConnector.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Set-SendConnector.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@myfope the cmdlet reference topics are now single-sourced for Exchange 2010, 2013, 2016, Exchange Online, Office 365 Security & Compliance Center, and Exchange Online Protection.

The **Applicable** property value in the parameter description only contains the value Exchange Server 2010, but I went ahead and added 'This parameter is available only in Exchange 2010" text at the top of the parameter description.

Thanks for the feedback.
