### ISSUE TITLE
Get-PublicFolderItemStatistics - CreationTime needs explanation

### ISSUE THREAD

**Issue by cgeising** [MicrosoftDocs/office-docs-powershell#1465]
When requesting Get-PublicFolderItemStatistics for a specific public folder and querying for the CreationTime of the Folder Emails the reported CreationTime is sometimes different from the Timestamp which is shown in OWA for the corresponding Email.
Unfortunately there is no documentation about the CreationTime Property: 
https://msdn.microsoft.com/en-us/library/microsoft.exchange.data.storage.management.publicfolderitemstatistics.creationtime.aspx

I am using the following command in my script:
Get-PublicFolderItemStatistics -Identity $Folder.Identity | Select CreationTime, Subject, Identity | Sort CreationTime

The CreationTime Property needs an explanation and I would like to understand which scenarios can lead to a difference in CreationTime vs OWA timestamp.

**Comment by AndreaBarr** [comment]
@cgeising Thank you for this feedback

I want to make sure you get this information on CreationTime Property. I am sending this over to the PowerShell team for investigation and documentation. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @cgeising thanks for your comments, we really appreciate them.
Took the time to test this in my lab.
CreationTime is, as the doc you referenced says, a DateTime property, and the difference you are seeing with the OWA timestamp probably is because DateTime property shows the time in GMT/UTC and OWA shows the time based on user selection in OWA settings.
Hope this information is useful and responds your question. cc @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @cgeising  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
