### ISSUE TITLE
connect-microsoftteams with credential causes error

### ISSUE THREAD

**Issue by robbert-vanandel** [MicrosoftDocs/office-docs-powershell#147]
Using the following code.

    $secpasswd = ConvertTo-SecureString "password" -AsPlainText -Force
    $mycreds = New-Object System.Management.Automation.PSCredential ("username@domain.com", 
    $secpasswd)
    
    Connect-MicrosoftTeams -Credential $mycreds;

Causes this set of errors to appear

    Connect-MicrosoftTeams : One or more errors occurred.: AADSTS75005: The request is not a valid SAML 2.0 protocol message.
    Trace ID: 5dc9b749-95d6-47d9-b3fe-2419a4161600
    Correlation ID: a720051b-196a-43b2-9ae2-bc44544bbd53
    Timestamp: 2018-02-08 20:11:47Z
    At z:\PowerShell\create-ms-teams.ps1:22 char:1
    + Connect-MicrosoftTeams -Credential $mycreds; 
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AadAuthenticationFailedException
        + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
     
    Connect-MicrosoftTeams : One or more errors occurred.
    At z:\PowerShell\create-ms-teams.ps1:22 char:1
    + Connect-MicrosoftTeams -Credential $mycreds;
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AggregateException
        + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
     
    Connect-MicrosoftTeams : AADSTS75005: The request is not a valid SAML 2.0 protocol message.
    Trace ID: 5dc9b749-95d6-47d9-b3fe-2419a4161600
    Correlation ID: a720051b-196a-43b2-9ae2-bc44544bbd53
    Timestamp: 2018-02-08 20:11:47Z
    At z:\PowerShell\create-ms-teams.ps1:22 char:1
    + Connect-MicrosoftTeams -Credential $mycreds; 
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AdalServiceException
        + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
     
    Connect-MicrosoftTeams :  Response status code does not indicate success: 400 (BadRequest).
    At z:\PowerShell\create-ms-teams.ps1:22 char:1
    + Connect-MicrosoftTeams -Credential $mycreds; 
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], HttpRequestException
        + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
     
    Connect-MicrosoftTeams : {"error":"invalid_request","error_description":"AADSTS75005: The request is not a valid SAML 2.0 protocol message.\r\nTrace ID: 
    5dc9b749-95d6-47d9-b3fe-2419a4161600\r\nCorrelation ID: a720051b-196a-43b2-9ae2-bc44544bbd53\r\nTimestamp: 2018-02-08 
    20:11:47Z","error_codes":[75005],"timestamp":"2018-02-08 
    20:11:47Z","trace_id":"5dc9b749-95d6-47d9-b3fe-2419a4161600","correlation_id":"a720051b-196a-43b2-9ae2-bc44544bbd53"}
    At z:\PowerShell\create-ms-teams.ps1:22 char:1
    + Connect-MicrosoftTeams -Credential $mycreds; 
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], Exception
        + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
     
    Connect-MicrosoftTeams : One or more errors occurred.: AADSTS75005: The request is not a valid SAML 2.0 protocol message.
    Trace ID: 5dc9b749-95d6-47d9-b3fe-2419a4161600
    Correlation ID: a720051b-196a-43b2-9ae2-bc44544bbd53
    Timestamp: 2018-02-08 20:11:47Z
    At z:\PowerShell\create-ms-teams.ps1:22 char:1
    + Connect-MicrosoftTeams -Credential $mycreds;
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Connect-MicrosoftTeams], AadAuthenticationFailedException
        + FullyQualifiedErrorId : Microsoft.Open.Teams.CommonLibrary.AadAuthenticationFailedException,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
     

I am working on an automated process, so I need a way to connect to Teams without user interaction.

**Comment by islubin** [comment]
This looks like an error in your script rather than in the cmds itself.  Are there any special characters in your password that need to be escaped?

**Comment by robbert-vanandel** [comment]
No, it just uses letters and numbers.

**Comment by kenwith** [comment]
@robbert-vanandel  - I am not a SME in this area but one thing to troubleshoot would be to get credentials with:   $mycreds = Get-Credential    on your workstation then type in the pop-up box.. and see if that still gives the error

**Comment by kenwith** [comment]
Also, just to capture for others that might stumble upon this discussion.. there is a really good blog post by Matt Soseman that is related, here: https://blogs.technet.microsoft.com/skypehybridguy/2017/11/07/microsoft-teams-powershell-support/

**Comment by robbert-vanandel** [comment]
Hi, @kenwith , yes I've done that as well.  The blog post is what I had used in the beginning. The problem is that I need to be able to do this unattended, so having a pop up window that requires me to log in manually would not work.

**Comment by yeshwanthjagannath** [comment]
@robbert-vanandel - try the below:
 Instead of passing the username again:

Connect-MicrosoftTeams -AccountId 'username@domain.com' #-Credential $mycreds;

Just pass your credentials ($mycreds) as below:

Connect-MicrosoftTeams $mycreds;

Let us know how it goes.

Cheers,
Yesh

**Comment by doctordns** [comment]
One suggestion is to use -Verbose on the call to Connect-MicrosoftTeams. If it's like other Azure cmdlets, it might show the specific web calls being made along with their parameters. I do not have access to Teams to test this theory.

**Comment by SamCosby** [comment]
IDP is outputting invalid SAML information. Needs to have SAML 2.0 vs. SAML 1.0 for the module to connect.

**Comment by kenwith** [comment]
@SamCosby , sorry I don't totally follow.. could you expand on identity provider outputting invalid SAML? How would this be updated? This seems like a great issue for a blog or added content to the Notes in the cmdlet. Really great information to capture.

**Comment by kenwith** [comment]
Also, not sure if same issue but added a link: https://github.com/MicrosoftDocs/office-docs-powershell/issues/156

**Comment by SamCosby** [comment]
Sure. I worked with the customer on this one. The IDP that they were using was only allowing the use of SAML1.0 when trying to auth via basic authentication. Which in turn, isn't expected to work because we expect either OAUTH2 (which is used when doing just connect-microsofteams), or SAML2.0.

**Comment by kenwith** [comment]
Awesome, thank you! I added a Pull Request to get this info captured in notes. If anyone wants to adjust what I said please go ahead and submit updated pull request. Thanks all!

https://github.com/MicrosoftDocs/office-docs-powershell/pull/162

**Comment by bwells79** [comment]
Sorry to resurrect this, but I'm configuring our IdP to try to fix this issue, and I'm finding some discrepancies.  

@SamCosby mentions that Azure requires SAML 2.0.  This works as expected for connect-microsoftteams, as the pop-up window essentially acts a browser and uses WS-Fed.  All good.

The issue comes with anything that needs to use the STS.  Currently, the STS is configured for SAML 1.1 per the vendor (PingFederate), not the 2.0 mentioned above.

The STS Integration guide (https://www.microsoft.com/en-us/download/confirmation.aspx?id=41185) states that "The token is structured based on a SAML 1.1 token...", which I can confirm the IdP is putting out (namespace portion of a decoded assertion from a fiddler trace):

xmlns:saml="urn:oasis:names:tc:SAML:1.0:assertion

It seems that 1.1 should be the correct setting.  I realize the document I have is from 2016 and may be old, which leads to:

1. Is there a newer document to reference?
2.  If I manage to change the token type to 2.0, what are the effects on apps / clients that currently work fine with the 1.1 type?  It's not a win if everyone's Outlook stops working.

**Comment by AndrewCi** [comment]
Why is this closed? I am still having this issue. I haven't figured out a way to connect to Teams using the credential object. In my particular case I am trying to authenticate using Azure PowerAutomate.

**Comment by ajacks88** [comment]
Still running into this issue, anyone have a fix?

**Comment by philrice** [comment]
Im having this issue also - Azure PowerAutomate + connect-microsoftteams with a runas account or any other service account 

Is there a special way to do this or can it be confirmed that it doesnt work and isnt going to at least
