### ISSUE TITLE
Get-SPOExternalUser Will Not Return all users

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#1470]
Please find details in the article below:
[https://absolute-sharepoint.com/2018/03/bug-in-get-spoexternaluser-powershell-not-all-external-users-are-returned-anymore.html](url)
In short: ```Get-SPOExternalUser``` will not return all users.

**Comment by AndreaBarr** [comment]
@YuriySamorodov Thank you for this feedback


It looks like this was already dealt with. I am going to close this issue. If the issue is not resolved please reopen the original issue. Thank you.
