### ISSUE TITLE
Failing to create Subsites using PnP module

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/office-docs-powershell#1481]
Connect-PnPOnline "&lt;SiteCollectionURL&gt;"
$ctx = Get-PnPContext
$Subsite = New-Object -TypeName Microsoft.SharePoint.Client.WebCreationInformation
$Subsite.Title = "Some Example Site Title"
$Subsite.Url = "ExampleSubSitename"
$Subsite.WebTemplate = "SITEPAGEPUBLISHING#0"
$Subsite.UseSamePermissionsAsParentSite = $true
$SubWeb = $ctx.Web.Webs.Add($Subsite)

Error:
====
Cannot convert argument "parameters", with value: "Microsoft.SharePoint.Client.WebCreationInformation", for "Add" to
type "Microsoft.SharePoint.Client.WebCreationInformation": "Cannot convert the
"Microsoft.SharePoint.Client.WebCreationInformation" value of type
"Microsoft.SharePoint.Client.WebCreationInformation" to type "Microsoft.SharePoint.Client.WebCreationInformation"."
At line:1 char:1
+ $SubWeb = $ctx.Web.Webs.Add($Subsite)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3240d3-6a7d-fc4b-62fd-d3a5375d8a4a
* Version Independent ID: 561212df-4dab-92b7-b634-57d53d313c6f
* Content: [PnP PowerShell overview](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by mganeshphani** [comment]
Is anyone monitoring this repo? its been 4 days since I seeked help here, but no comments so far

**Comment by kenwith** [comment]
@mganeshphani - @VesaJuvonen monitors for PnP but I believe he is on vacation right now. I think the main community for PnP is over at: [https://github.com/SharePoint/PnP-PowerShell](https://github.com/SharePoint/PnP-PowerShell). I am afraid your issue might get stale in this repo since this is just for the cmdlets themselves. Please let me know if you open an issue in the PnP community and let's cross link so if anyone sees this here they can find you in the community location.

**Comment by mganeshphani** [comment]
@kenwith thankyou.. I created following issue
https://github.com/SharePoint/PnP-PowerShell/issues/1664

**Comment by kenwith** [comment]
@mganeshphani - perfect, thank you! Much appreciated your helping and engaging in the community.
