### ISSUE TITLE
Identity parameter does not accept GUID

### ISSUE THREAD

**Issue by mschultz-bcbsne** [MicrosoftDocs/office-docs-powershell#1483]
Connected to Exchange Online via PowerShell, I have been unable to pass a GUID to the identity parameter as this page indicates. I'm attempting to use the output of Get-MailPublicFolder (which contains the GUID) to retrieve the full path to the public folder with Get-PublicFolder.

With the following code:
$MailPF = Get-MailPublicFolder | where {$_.primarysmtpaddress -eq 'myfolder@domain.com'}
Get-PublicFolder -Identity $MailPF.GUID

get-publicfolder returns an error: Cannot process argument transformation on parameter 'Identity'. Cannot convert the "GUIDHERE" value of type "System.Guid" to type "Microsoft.Exchange.Configuration.Tasks.PublicFolderIdParameter".

The documentation should include an example of how to pass a GUID to the identity parameter, or the text indicating a GUID can be used should be removed if the Identity parameter only accepts the full path to the folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c43e2506-2cce-f232-24b5-64755bfa2eaf
* Version Independent ID: 7c604d12-69c0-e35b-683e-3e60226b0aad
* Content: [Get-PublicFolder (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/sharing-and-collaboration/Get-PublicFolder?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/sharing-and-collaboration/Get-PublicFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/sharing-and-collaboration/Get-PublicFolder.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mschultz-bcbsne, apparently, there is no GUID property available on Get-PublicFolder. There's a MailRecipientGuid property whose value is the same as the GUID property value from Get-MailPublicFolder, but when I changed your command to:

Get-PublicFolder -Identity $MailPF.**MailRecipientGUID**

All I get as a result is:

```
Name                                                        Parent Path
----                                                        -----------
IPM_SUBTREE
```

as if I ran Get-PublicFolder by itself without any identity arguments. It looks like Get-PublicFolder demands an Identity value using the "\\TopLevelPublicFolder\\PublicFolder" syntax and nothing else.

I updated the Identity parameter description to remove GUID as an acceptable value in Get-PublicFolder, Remove-PublicFolder, and Set-PublicFolder.

Thanks for the feedback.
