### ISSUE TITLE
Needs more clarity in docs on how translation rules apply.

### ISSUE THREAD

**Issue by kevinkrautle** [MicrosoftDocs/office-docs-powershell#1486]
During testing of New-CsSipResponseCodeTranslationRules I noticed a behavior that needs to be called out that a translation rule is only applied if the PSTNGateway does not have a more specific configuration in a CSTrunkConfiguration.

I suggest the following change to the description in the end of the paragraph:
...Translation rules can be assigned to the global scope, the site scope, or to the service scope (for the PSTN Gateway service only). [These rules are strictly applied from most specific declared configuration (PSTN Gateway) to most general (Global). If a PSTN Gateway has a specific trunk configuration (CsTrunkConfiguration) declared, it takes priority over site, and site takes priority over global.]

Thanks

-Kevin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8254c9df-36c4-a561-9f31-a57a3923204d
* Version Independent ID: 25b93d7b-f5e5-8df6-5f3b-8635d146bc70
* Content: [New-CsSipResponseCodeTranslationRule (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/New-CsSipResponseCodeTranslationRule?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsSipResponseCodeTranslationRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsSipResponseCodeTranslationRule.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@kevinkrautle - I was able to get this into the backlog for the Skype team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. And sorry for the long delay!

I made a note to request the team to update this when the work is complete.
