### ISSUE TITLE
new-teamuser with Edu Template

### ISSUE THREAD

**Issue by apearcebfc** [MicrosoftDocs/office-docs-powershell#1489]
I've been doing some testing with add-teamuser with the edu templates and having trouble getting a team updated on the application with the correct names.  I know this is in beta at the moment but here are some tests i've done and hope to find a resolution.

I create 3 teams.  The first is a normal team, 2nd is the EDU_Class template and the 3rd being EDU_PLC.  
I'm adding a set of owners and members to each of the teams when it created.  

When i create a normal team everything works find, add the different members and the owners however when i try the add-teamusers for the same people and code (only changing the creation of the group) it does not add the same people.  Out of the 6 lines of code, it only adds the first own as a member and then ignores the rest.  I've also tried where the first add-teamuser is directly added as a owner rather than a member and then made an owner and have the same experience.

This is an edu license and the users who are being added as owners have a faculty license.  The one that is being added as just a member is a student license.

Any help?  Code below

$NewGroup1 = New-Team -DisplayName "normal" -Alias "plc3" -AccessType Private
Add-TeamUser -Role member -User "user1@tenant.onmicrosoft.com" -GroupId $NewGroup1.groupid
Add-TeamUser -Role owner -User "user1@tenant.onmicrosoft.com" -GroupId $NewGroup1.groupid
Add-TeamUser -Role member -User "user2@tenant.onmicrosoft.com" -GroupId $NewGroup1.groupid
Add-TeamUser -Role member -User "user3@tenant.onmicrosoft.com" -GroupId $NewGroup1.groupid
Add-TeamUser -Role owner -User "user3@tenant.onmicrosoft.com" -GroupId $NewGroup1.groupid

$NewGroup2 = New-Team -DisplayName "plc" -Alias "plc" -Template EDU_PLC
Add-TeamUser -Role member -User "user1@tenant.onmicrosoft.com" -GroupId $NewGroup2.groupid
Add-TeamUser -Role owner -User "user1@tenant.onmicrosoft.com" -GroupId $NewGroup2.groupid
Add-TeamUser -Role member -User "user2@tenant.onmicrosoft.com" -GroupId $NewGroup2.groupid
Add-TeamUser -Role member -User "user3@tenant.onmicrosoft.com" -GroupId $NewGroup2.groupid
Add-TeamUser -Role owner -User "user3@tenant.onmicrosoft.com" -GroupId $NewGroup2.groupid

$NewGroup3 = New-Team -DisplayName "class" -Alias "class" -Template EDU_Class
Add-TeamUser -Role member -User "user1@tenant.onmicrosoft.com" -GroupId $NewGroup3.groupid
Add-TeamUser -Role owner -User "user1@tenant.onmicrosoft.com" -GroupId $NewGroup3.groupid
Add-TeamUser -Role member -User "user2@tenant.onmicrosoft.com" -GroupId $NewGroup3.groupid
Add-TeamUser -Role member -User "user3@tenant.onmicrosoft.com" -GroupId $NewGroup3.groupid
Add-TeamUser -Role owner -User "user3@tenant.onmicrosoft.com" -GroupId $NewGroup3.groupid

**Comment by islubin** [comment]
Thanks @apearcebfc. Can you share what powershell module version you're running (is it 0.9.3)?  If you aren't running 0.9.3 please update!

For further troubleshooting we'll need the actual tenant that you're running in and the group information, so please create a support ticket so we can investigate offline.

**Comment by kenwith** [comment]
@apearcebfc - as Isabella mentioned we want to make sure this gets resolved ASAP. Sorry for the delay on this response. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
