### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by after8b49** [MicrosoftDocs/office-docs-powershell#1495]
Are you sure about this? The commands look the same to me for enable & disable...

This example disable remote PowerShell access for the user named Therese Lindqvist.
Set-User "Therese Lindqvist" -RemotePowerShellEnabled $false

This example enables remote PowerShell access for the user named Sirirat Kitjakarn.
Set-User "Sirirat Kitjakarn" -RemotePowerShellEnabled $false

On a minor point of grammar, the first line should be "This example disables...", not "This example disable..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d03c6ce2-687b-e138-939b-413014d1c81a
* Version Independent ID: 9fe6c492-d0fe-e454-6574-06de8cd31a21
* Content: [Control remote PowerShell access to Exchange servers](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/control-remote-powershell-access-to-exchange-servers?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/control-remote-powershell-access-to-exchange-servers.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/control-remote-powershell-access-to-exchange-servers.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@after8b49, you are correct; those were all typos, and I fixed them all.

Thanks for the feedback.
