### ISSUE TITLE
PerformanceLevel parameter description is out of order?

### ISSUE THREAD

**Issue by mauledbyjesus** [MicrosoftDocs/office-docs-powershell#1501]
I believe this is what was meant:

Reduced: Total number of threads = number of processors

Partly Reduced: Total number of threads = number of processors, Max Threads/host = number of processors

Maximum: Total number of threads = 4 times the number of processors, Max Threads/host = 16 time the number of processors

...but even that doesn't really make sense. &gt;.&lt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e31f1b9-b0a1-ed2e-c0df-abdff22ea0e8
* Version Independent ID: 2bf1bd67-9a2f-d122-f184-3308a6ba5226
* Content: [Set-SPEnterpriseSearchService (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/Set-SPEnterpriseSearchService?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPEnterpriseSearchService.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPEnterpriseSearchService.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by edixon-github** [comment]
Bumping this issue... the doc for PerformanceLevel was updated, but the new doc makes no sense, seems contradictory, and lacks information that was previously available.

Here is an example of how it used to read:
-PerformanceLevel 
Specifies the relative number of threads for the crawl component performance.
The type must be one of the following values: Reduced, PartlyReduced, or Maximum. The default value is Maximum.

Reduced: Total number of threads = number of processors, Max Threads/host = number of processors. 

Partly Reduced: Total number of threads = 16 times the number of processors , Max Threads/host = 8 plus the number of processors. Threads are assigned Below Normal priority.

Maximum: Total number of threads = 32 times the number of processors, Max Threads/host = 8 plus the number of processors. Threads are assigned Normal priority.

**Comment by yogkumgit** [comment]
@Techwriter40 Can you please confirm that comment given by a user is right? Some users are creating issues on this documentation saying it's contradictory.

**Comment by yogkumgit** [comment]
@Techwriter40 Can we confirm this is right? Some users are creating issues on this documentation saying it's contradictory.

**Comment by Techwriter40** [comment]
@tklarsen Tone, can you please review the comment by Yogkumgit and verify the accuracy of the PerformanceLevel parameter?  There seems to be some contradictory and need clarity.  Thanks.

**Comment by tklarsen** [comment]
The documentation of this parameter looks wrong. Am backtracking to the correct version from back in 2015 and will update from that.

**Comment by get-itips** [comment]
Hi @mauledbyjesus thanks for your comment, we really appreciate them. @tklarsen has updated the document to clarify this. Thank you.

**Comment by yogkumgit** [comment]
@get-itips and @tklarsen  Thank you very much for the contribution. @mauledbyjesus  Hope this is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
