### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by asumner** [MicrosoftDocs/office-docs-powershell#1505]
on the docs. domain the commands documentation links at the bottom don't work. They go back to the same page.
Introduction to the SharePoint Online management shell
Set up the SharePoint Online Management Shell Windows PowerShell environment

**Comment by AndreaBarr** [comment]
@asumner Thank you for this feedback

I want to make sure this link gets fixed. I am sending this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
