### ISSUE TITLE
-ContentDateFrom -ContentDateTo 

### ISSUE THREAD

**Issue by spikedfuel** [MicrosoftDocs/office-docs-powershell#1512]
what happened to -ContentDateFrom -ContentDateTo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a6c085b-ef16-d0f6-fd86-dbde22bb5937
* Version Independent ID: 3bfb96ec-7789-ce56-6062-df2076dca3b0
* Content: [New-CaseHoldRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-ediscovery/new-caseholdrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-ediscovery/New-CaseHoldRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-ediscovery/New-CaseHoldRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@spikedfuel see pull request [1466](https://github.com/MicrosoftDocs/office-docs-powershell/commit/3a9560f0c50b95f9afd31d4301166f0aaac0bd21#diff-6cc7e8b2930893caa90a5a0192d56960). Apparently, those parameters were removed.

From an email thread I was on:

I believe that adding a date range to a query-based hold isn’t going to create a time-based hold. It will merely place items that match the query on hold (for example, “hold items that were received between 1/1/2017 and 10/19/2017”). Those items will be placed on hold for as long as the hold is in effect. To remove the hold from those items, the hold needs to be deleted from the corresponding eDiscovery case or by closing or deleting the eDiscovery case. Holds associated with eDiscovery cased are intended to be relatively short-lived, that is for the duration of a legal case or an investigation. When the case/investigation is complete, the case is closed and holds are removed.

The only way to create a “time-based hold” in the Office 365 Security & Compliance Center is by using a retention policy.
