### ISSUE TITLE
Bulk Import Contacts to Office365 - hopeless!

### ISSUE THREAD

**Issue by swedishpotato** [MicrosoftDocs/office-docs-powershell#1522]
I thought office365 was supposed to be advanced? However, when it comes to importing contacts for the organisations to share (which is hidden under the "Users" tab - why?) I find I can only add them laboriously one at a time! To do a bulk import requires installing and running Powershell (whatever the hell that is). Surely Office365 can't be this backwards in 2018? I want to import a few contacts via CSV from another system and I am faced with this nonsense. Amazing. Microsoft is so user unfriendly, still! get a grip.

**Comment by kenwith** [comment]
@swedishpotato - thank you for submitting feedback. PowerShell is a command line utility for working with items in bulk. I am sorry you are experiencing so much frustration with Office 365.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. The support engineers will be able to guide you on the best way to import a few contacts and if it is possible to use a CSV file. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
