### ISSUE TITLE
incorrect translate

### ISSUE THREAD

**Issue by nakawankuma** [MicrosoftDocs/office-docs-powershell#1524]
キーワードが翻訳されていますので、要注意
Web ページ 
番地
とか

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [フィルター パラメーターのプロパティをフィルター処理可能](https://docs.microsoft.com/ja-jp/powershell/exchange/exchange-server/recipient-filters/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell.ja-JP/blob/master/exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@nakawankuma このフィードバックをありがとう。

私は調査と更新のためにこれをLOCチームに渡しています。

私はこれをPowerShellチームのバックログに入れることができました。 チームはこれを優先順位付けしてスプリントプランにします。 レポートを作成していただきありがとうございます。 とても有難い。
 
私は仕事が完了したらチームにこれを更新するよう要請するメモを作った。

**Comment by TinaMcN** [comment]
@nakawankuma フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 1週間以内に修正する必要があります。(Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It should be fixed within a week.)
