### ISSUE TITLE
Age limit description wrong.

### ISSUE THREAD

**Issue by jubbing** [MicrosoftDocs/office-docs-powershell#1525]
"-DefaultPublicFolderAgeLimit
The DefaultPublicFolderAgeLimit parameter specifies the default age limit for public folders across the entire organization. A public folder is automatically deleted when this age limit is exceeded. This attribute applies to all public folders in the organization that don't have their own AgeLimit setting."

This is misleading as it does not delete the public folder but the contents of the public folder that pass the age limit. In other words the public folder itself is not deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3ab3f0-cc05-e279-8876-6da0b323bcac
* Version Independent ID: bfb49814-d60b-564a-25cc-f902dfa42b10
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jubbing, I changed the description to this:

The DefaultPublicFolderAgeLimit parameter specifies the default age limit for **the contents of public folders** across the entire organization. **Content in a public folder is** automatically deleted when this age limit is exceeded. This attribute applies to all public folders in the organization that don't have their own AgeLimit setting.

**To specify a value, enter it as a time span: dd.hh:mm:ss where d = days, h = hours, m = minutes, and s = seconds. Or, enter the value $null. The default value is blank ($null). **

Thanks for the feedback.
