### ISSUE TITLE
Missing instructions on creating a test user

### ISSUE THREAD

**Issue by baarsd** [MicrosoftDocs/office-docs-powershell#1527]
The documentation states "To create a test user, run the following command." but there is no instructions about how to create the test user

Thanks,
Dylan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c1d4ea-c784-9493-f7ce-6f1666d187d4
* Version Independent ID: 51c5c0f3-a2b5-dcaf-3dd4-ee74ef88e9a0
* Content: [Test-FederationTrust (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/test-federationtrust?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/Test-FederationTrust.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/Test-FederationTrust.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@baarsd, thanks for the feedback. This was a TechNet to docs.microsoft.com migration issue that affected a total of 8 Test- cmdlet reference topics. I fixed them all.
