### ISSUE TITLE
Please provide the definitions for all of the event types found on the mailtrafficreport

### ISSUE THREAD

**Issue by mlletech** [MicrosoftDocs/office-docs-powershell#1528]
Advanced phish filter
Anti-malware engine
Anti-spoof: Intra-org
ATP safe links
General phish filter
Malicious URL reputation
Message passed
Phish
Phish ZAP
User impersonation
ZAP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb20809-8f21-dfd3-23bf-bbfb82679619
* Version Independent ID: be54b158-1672-5ae9-6a6d-139a7850c67b
* Content: [Get-MailTrafficReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/reporting/get-mailtrafficreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/reporting/Get-MailTrafficReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/reporting/Get-MailTrafficReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@mlletech Thank you for this feedback

I will get this to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by mimi-msft** [comment]
HI, these values are not currently returned in the Get-MailTrafficReport cmdlet

Perhaps this comment was meant to be left on the Get-MailTrafficATPReport support doc? In which case, the values have been updated there: https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/get-mailtrafficatpreport?view=exchange-ps

**Comment by get-itips** [comment]
Hi @mlletech thanks for your comments and suggestion!
Definitions for the event types had been added to the document that @mimi-msft pasted here.
@yogkumgit I think we can close this now.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips and @mimi-msft  Thank you very much for the contribution and sharing this explanation. @mlletech  Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
