### ISSUE TITLE
Module location

### ISSUE THREAD

**Issue by FrederikLeed** [MicrosoftDocs/office-docs-powershell#1530]
WHERE is this module located? Is this documentation for the MicrosoftTeams module located in the PSGallery or?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94694082-c529-5654-1734-57514ec17a1f
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [Microsoft Teams PowerShell](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
Sorry, I know it is setup whacky. There are actually 2 files for landing depending on how someone gets to the area on docs.microsoft.com. I added your changes to the intro.md file too and should be live shortly.

**Comment by kenwith** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/pull/1533
