### ISSUE TITLE
Incorrect advice in 'How to connect to Exchange Online with PowerShell page

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/office-docs-powershell#1532]
in the page https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps#feedback 

It says: _To enable Windows PowerShell to run signed scripts, run the following command in an elevated Windows PowerShell window (a Windows PowerShell window you open by selecting Run as administrator):_. I feel this is incorrect.

Once you enable the execution policy to allow running of scripts,  you can always run signed scripts. What setting execution policy to RemoteSigned does is to restrict the machine from running unsigned scripts that came from 'remote'.  If you can run scripts, then you can copy them to a local host, remove the 'remote' marker on the file and run them locally. 

Forcing remotesigned can be a good security measure. It does take effort and cost and offers security benefit in larger and more complex organisations.  I feel it does not need to be covered in _this_ document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@doctordns, I think you'll agree that the execution policy needs to be changed to **something** other than its default value of 'Restricted':

- 'Unrestricted' works but is a security vulnerability, and we can't recommend it (similar to why we can't use example passwords like 'password' in official documentation.)

- 'AllSigned' doesn't work for the purposes of connecting to Exchange Online PowerShell.

That leaves 'RemoteSigned' as the best, most secure option possible for this scenario.

If youdidn't like the phrase 'To enable Windows PowerShell to run signed scripts,...', I changed it to more closely match the description of RemoteSigned in the [Set-ExecutionPolicy](https://docs.microsoft.com/powershell/module/microsoft.powershell.security/set-executionpolicy) topic:
'To require all PowerShell scripts that you download from the internet are signed by a trusted publisher,...'.

Thanks for the feedback

**Comment by doctordns** [comment]
Nice change. 

One further question: does the discussion of signing actually need to be on this page? It's nothing important with respect to the scope of the page. Could the discussion of signing be removed?

**Comment by chrisda** [comment]
I'm happy to take input on what you'd like me to change, but I don't see much discussion happening in the topic, unless you're talking about this phrase, "Windows PowerShell needs to be configured to run scripts, and by default, it isn't."

The default Set-ExcecutionPolicy value on any version of Windows is 'Restricted', and from the description of this value from [Set-ExecutionPolicy](https://docs.microsoft.com/powershell/module/microsoft.powershell.security/set-executionpolicy): "Does not load configuration files or run scripts. Restricted is the default execution policy."

So, logically following the chain of events: the default value will prevent you from connecting to Exchange Online PowerShell, so you need to change it to *something* else, and the best option is 'RemoteSigned'. As I see it, the only discussion about script signing that's happening in the topic is explaining what the default value 'Restricted' does, and what the 'RemoteSigned' value we're telling you to change it to does. I think a little bit of background about what each value does is helpful, especially for organizations with a Security Officer whom you need to convince the need for the change on your computer.

**Comment by doctordns** [comment]
Thanks for the comments. And I agree with much of what you say. 

Thing is - this has NOTHING to do with Exchange On-Line PowerShell as such. There is nothing special about execution policy and Exchange. Scripts that use these cmdlets are the same as any other script.  Execution policy affects any script in the same way. So calling it out here is really not all that helpful. 

This page is talking about how to use EOL. Anyone who is competent enough to use the information really should know about execution policy. Would you really advocate having the discussion about execution policy hundreds of times throughout docs.microsoft.com?

When I am teaching PowerShell, execution policy and profiles are things I cover.  So I am suggesting we remove any mention of execution policy here, unless there is something special or otherwise about Exchanger On-Line PowerShell. I daresay that if a user gets an execution policy problem, they are almost certain to google it and find the answers on pages elsewhere.  So let's simplify this page, and stop teaching other aspects of PowerShell that are somewhat extraneous.
