### ISSUE TITLE
Revert to Global Policy?

### ISSUE THREAD

**Issue by dbetlow** [MicrosoftDocs/office-docs-powershell#1535]
Once you grant someone access to a custom dial plan, how do you set them back to the Global plan?  When trying to Grant-CsTenantDialPlan -Identity Global, it gives an error that Global isn't a user policy...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd56a7e7-56ca-116a-3a8b-ad4c2ea5f544
* Version Independent ID: 72abb3bd-b9d5-6b10-04f7-d46f3bd49688
* Content: [Grant-CsTenantDialPlan (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-cstenantdialplan?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsTenantDialPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsTenantDialPlan.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@dbetlow - thank you for submitting feedback. 

I am not sure on the answer and want to make sure this error gets resolved for you regarding the grant-CsTenantDialPlan cmdlet.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by greiginsydney** [comment]
I've just submitted a pull request to add an Example 2 to the article that addresses this question. The trick is to Grant a policy name of $Null.
