### ISSUE TITLE
Method deprecated

### ISSUE THREAD

**Issue by stemy-msft** [MicrosoftDocs/office-docs-powershell#1537]
This method is being deprecated as of January 29, 2018. See details, and information on replacement MS Graph APIs available at
https://techcommunity.microsoft.com/t5/Office-365-Blog/Announcing-the-General-Availability-of-Microsoft-Graph-reporting/ba-p/137838.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53ea7ef0-38d7-965f-7c03-0282afd485fb
* Version Independent ID: 6d529bfa-3b57-b838-d37b-e054405544bf
* Content: [Get-ConnectionByClientTypeDetailReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/reporting/get-connectionbyclienttypedetailreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/reporting/Get-ConnectionByClientTypeDetailReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/reporting/Get-ConnectionByClientTypeDetailReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@stemy-msft, what's the issue? There's a big note at the top of the topic that says:

This cmdlet will be deprecated after January 29, 2018. For information about the available replacement Microsoft Graph reports in Office 365, see the subtopics of Working with Office 365 usage reports in Microsoft Graph (https://go.microsoft.com/fwlink/p/?LinkID=865135).

Are you saying the target link should be replaced?

**Comment by stemy-msft** [comment]
The issue was not enough coffee this morning.  I managed to miss the blurb at the top.
