### ISSUE TITLE
developer

### ISSUE THREAD

**Issue by mic8989** [MicrosoftDocs/office-docs-powershell#1538]
Before I have seen the categorized comlets for SharePoint. Do we still have those?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102a89dc-8bb7-e76e-f570-3d6bde7e8308
* Version Independent ID: 3eb619c5-db95-9a42-4c83-9778572f00fc
* Content: [SharePoint Server Cmdlets](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@mic8989 thank  you for your submission. At this time we do not have categories, but something we are considering. More of GitHub logistics that is preventing us at this time.. thank you
