### ISSUE TITLE
Please elaborate on the use of "-Path" in combination with "-Source"

### ISSUE THREAD

**Issue by nils-a** [MicrosoftDocs/office-docs-powershell#1544]
The only example given in the page gives a relative file-uri as Path and `ObjectModel` as "Source".
What does that mean? Which format should "Path" have, if "Source" would be `CorporateCatalog` or `Marketplace` (an url? some guid?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c8a25e-c9c4-e959-00cc-e79915a9c962
* Version Independent ID: b12fef77-6a75-a078-886a-da48233dde18
* Content: [Import-SPAppPackage (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/import-spapppackage?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Import-SPAppPackage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Import-SPAppPackage.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
These should define the 'source' of the app or where you downloaded it from (not in a literal sense, potentially), think more or less from an admin or end user perspective. Did the App come from the SharePoint Marketplace or was it added to the Corp Catalog (so it appears under 'From my org').

**Comment by Techwriter40** [comment]
closing comment as explanation giving by @tseward .
