### ISSUE TITLE
Missing Parameter

### ISSUE THREAD

**Issue by curspice** [MicrosoftDocs/office-docs-powershell#1547]
Example 2 is missing the -User parameter, which is required with the resource forest user ID to which the mailbox is to be reconnected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2300ad7-d7ac-203c-59cb-177e1f18e736
* Version Independent ID: 604f51aa-0a63-2eae-ede6-3e27653059ba
* Content: [Connect-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/connect-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Connect-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Connect-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@curspice, you're saying LinkedMasterAccount isn't enough? Do you need to specify both LinkedMasterAccount AND User? Or just User and not LinkedMasterAccount?

**Comment by AndreaBarr** [comment]
@curspice Thank you for this feedback

I am going to get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
