### ISSUE TITLE
ThirdPartyFileProvidersEnabled

### ISSUE THREAD

**Issue by Obenscripe** [MicrosoftDocs/office-docs-powershell#1553]
ThirdPartyFileProvidersEnabled - Seems to be missing - can we have a description of this attribute please. Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ca7906-9f33-2991-9da9-a626e5e45c46
* Version Independent ID: 5f388b3c-fb47-f7a0-e648-07cb3e59cf72
* Content: [Set-OwaMailboxPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/Set-OwaMailboxPolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@Obenscripe Thank you for this feedback

I will get this over to the PowerShell team so we can get this updated. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by Obenscripe** [comment]
Hi Andrea
Thanks for getting this done. I managed to catch the document while the
function was being updated. It's all clear now.

Many Thanks

Dan Warwick

**Comment by AndreaBarr** [comment]
@Obenscripe Thank you for updating us on this I will close this as resolved.
