### ISSUE TITLE
Start-SPOSiteRename cmdlet is missing in docs

### ISSUE THREAD

**Issue by nikrampi** [MicrosoftDocs/office-docs-powershell#1554]
Start-SPOSiteRename is lacking documentation alike other similar cmdlets (see #1386)
There is no scaffolding page either on GitHub under office-docs-powershell

**Comment by AndreaBarr** [comment]
@nikrampi Thank you for this feedback

I will get this over to the PowerShell team so we can get this documented. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
While documenting I've found that the cmdlet is not working properly (issue #3086) ...

**Comment by yogkumgit** [comment]
@VesaJuvonen  if you find it suitable please merge this PR

**Comment by yogkumgit** [comment]
@j0rt3g4 Thank you very much for the contribution and updating the documentation with PR. @nikrampi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
