### ISSUE TITLE
0.9.3 doesn't have -Visibility

### ISSUE THREAD

**Issue by SamCosby** [MicrosoftDocs/office-docs-powershell#1556]
This document is misleading as it stands, as -AccessType is what should be set (today) for Private/Public. The -Visibility parameter doesn't exist. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@islubin FYI.

@SamCosby - what should we change? Willing to submit a PR or guide me?

**Comment by SamCosby** [comment]
Talked to some colleagues and this looks like it is being worked on already (@islubin correct me if I'm wrong here :) ).

**Comment by SamCosby** [comment]
Set-Team currently has the -Visibility parameter, but New-Team only can use -AccessType (for now).

**Comment by islubin** [comment]
It’s an inconsistency between the new- and set- cmdlets – I’ll update the docs to reflect current state and then update again once the bug fix is in.

**Comment by kenwith** [comment]
I saw the PR. Thanks for updates!
