### ISSUE TITLE
New-HostedConnectionFilterPolicy

### ISSUE THREAD

**Issue by trahman-hm** [MicrosoftDocs/office-docs-powershell#1558]
Is there a New-HostedConnectionFilterPolicy command that should be documented in this list as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586e8b44-035e-adae-2847-b5288bc6898d
* Version Independent ID: 03dda286-85d7-41ca-a6dd-f88ef8d89dc6
* Content: [Set-HostedConnectionFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/set-hostedconnectionfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedConnectionFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedConnectionFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@trahman-hm there used to be a New-HostedConnectionFilterPolicy topic, but it was removed around four years ago. At that time, the only policy was the default one, and you couldn't create new ones or remove the default one (I found the old email about it).

But, I checked just now and I had access to the New-HostedConnectionFilterPolicy cmdlet in a tenant, and it ran without error for me. But the real question is: does it work as expected?
