### ISSUE TITLE
New-UnifiedGroup -Owner and -Members parameter description

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#1566]
Today I was working with the New-UnifiedGroup cmdlet to automate the process of creating Office 365 groups. I ran in to the following issue:

```
New-UnifiedGroup -Owner 'MeganB@xyz.OnMicrosoft.com' -DisplayName "dev1"
Objekt "MeganB@xyz.OnMicrosoft.com" nicht gefunden. Stellen Sie sicher, dass es richtig geschrieben wurde, oder geben Sie ein anderes Objekt an.
    + CategoryInfo          : NotSpecified: (:) [New-UnifiedGroup], RecipientTaskException
    + FullyQualifiedErrorId : [Server=MR2P264MB0418,RequestId=9de872cc-a75b-4502-adb1-3f79bdf35831,TimeStamp=10.08.2018 08:56:17] [FailureCategory=Cmdlet-RecipientTaskException] E3 
   E2DB48,Microsoft.Exchange.Management.RecipientTasks.NewUnifiedGroup
    + PSComputerName        : outlook.office365.com
```
The parameter `Owners` should process anything, "that uniquely identifies the owner. For example: [...]

Email address"

What am I missing or is the documentation wrong?

The cmdlet completes successfully when I use the part in front of '@'.

The very same applies for the `Members` parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 316bada1-dbc7-f07a-4afa-d67330edef50
* Version Independent ID: d9380f67-a05a-ddd0-425c-af7023222c69
* Content: [New-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/new-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/New-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/New-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by andikrueger** [comment]
Another error - which contradicts the documentation:
```
New-UnifiedGroup -Owner 'MeganB','LidiaH' -DisplayName "dev1"
Cannot process argument transformation on parameter 'Owner'. Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type 
"Microsoft.Exchange.Configuration.Tasks.RecipientIdParameter".
    + CategoryInfo          : InvalidData: (:) [New-UnifiedGroup], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-UnifiedGroup
    + PSComputerName        : outlook.office365.com
```

It's not possible to add several owners at the same time.

**Comment by chrisda** [comment]
@andikrueger you are correct about the multiple owners thing. You can only add one Owner when you create the group with New-UnifiedGroup. Afterwards, you use the Add-UnifiedGroupLinks and/or Remove-UnifiedGroupLinks cmdlets to add multiple owners. I updated the Owner parameter description to reflect this.

I did a bunch of testing and confirmed the rest of the description is accurate: Owner really does accept any unique identifier for a mailbox: I used Name, DisplayName, Alias (and I made sure these values were different for the mailbox I was adding as an owner), PrimarySmtpEmailAddress, SamAccountName, and DistinguishedName.

I'm just throwing out ideas here, but is it possible that there's a typo in the email address you specified? The user's mailbox is alive and well (not soft-deleted)? Any valid email address of a mailbox or mail user should work.

Thanks for the feedback.

**Comment by heckshmek** [comment]
I ran into this same issue and was mislead by the text "You can specify multiple owners separated by commas" in the documentation. Can this document be updated?

**Comment by kenwith** [comment]
@heckshmek - thanks for the feedback and taking the time to make the docs better. This is a perfect case for the open source nature of the docs now. As experts like you run into an issue you can quickly bring up the issue. Much appreciated!

@chrisda - OK with the suggestion?

**Comment by chrisda** [comment]
@heckshmek, I updated the Owner parameter description to indicate single value only (again).

Thanks for the feedback.
