### ISSUE TITLE
Issue while enabling Private CDN for multiple site collections and sub-sites through foreach loop using PowerShell script

### ISSUE THREAD

**Issue by pratyusha-kodumuri** [MicrosoftDocs/office-docs-powershell#1567]
I have a requirement to enable Private CDN origin to a custom document library for multiple sharepoint site collections and subsites using PowerShell. I have written CSOM PowerShell code to read all sub sites and trying to add new Origin using "Add-SPOTenantCdnOrigin -CdnType Private -OriginUrl &lt;OriginURL&gt; -Confirm:$false" command but after successfully enabling CDN origin for  few subsites, I am facing below issue:

Add-SPOTenantCdnOrigin : Value cannot be longger than 5000.
At line:1 char:1
+ Add-SPOTenantCdnOrigin -CdnType Private -OriginUrl "OriginURL"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-SPOTenantCdnOrigin], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.AddTenantCdnOrigin

I could not find this type of error anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9a4ae73-5f75-79bb-8bde-0ff57a5a7519
* Version Independent ID: 2cb872ee-33af-a8d4-09ab-cdaebd17ddd2
* Content: [Add-SPOTenantCdnOrigin (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spotenantcdnorigin?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTenantCdnOrigin.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTenantCdnOrigin.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by pratyusha-kodumuri** [comment]
Please find the below screen shot for reference
![cdn_error](https://user-images.githubusercontent.com/41156305/44026068-89d7598e-9f0f-11e8-9e54-c964c60c8259.png)

**Comment by pratyusha-kodumuri** [comment]
![image](https://user-images.githubusercontent.com/41156305/44026116-a82a9770-9f0f-11e8-9444-abdca915ab77.png)

Please find the attached file in preview for the issue reference

**Comment by AndreaBarr** [comment]
@pratyusha-kodumuri Thank you for this feedback

I want to make sure this error is addressed properly. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by koskila** [comment]
Apologies for commenting on an old ticket, but this is the only result on Google when searching with the error message "Add-SPOTenantCdnOrigin : Value cannot be longger than 5000." (probably because of the typo in the error message itself).

@pratyusha-kodumuri, how were you able to resolve this issue?

**Comment by kenwith** [comment]
@trent-green

**Comment by yogkumgit** [comment]
@pratyusha-kodumuri Thank you for reporting this feedback here. This list is focused on content issues and I want to make sure your immediate product issue does not get lost in this list. If you would please open a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team.
