### ISSUE TITLE
Sr. SharePoint Analyst

### ISSUE THREAD

**Issue by ellenkong** [MicrosoftDocs/office-docs-powershell#1571]
It would be very helpful to know what permissions are required in order to run each command.  The SPO Developer documentation says that SPO Admin is all that is needed.  Yet, as an SPO Admin, I cannot run this command to see whether CDNs exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1cbddc-26b2-84bd-cbce-7d47b34d7da2
* Version Independent ID: 19bba570-f209-9d5d-f9cc-50413b46071f
* Content: [Get-SPOTenantCdnEnabled (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantcdnenabled?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantCdnEnabled.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantCdnEnabled.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@ellenkong Thank you for this feedback

It should be the only permissions you need, as this is not working I want to get you over to support for hands on help. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
