### ISSUE TITLE
Insufficent information about REST and EWS

### ISSUE THREAD

**Issue by Yorkwu1** [MicrosoftDocs/office-docs-powershell#1572]
There are very detailed information about the relationship between REST and EWS on the document for Set-OrganizationConfig. 
-EwsBlockList 
-EwsEnabled 
In the description about above parameters, it provides a detailed explanation. 

Could you please also update this document accordingly? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9398dd25-94e7-a8f8-6d97-f150173bb4da
* Version Independent ID: 6f19f636-20d5-bc97-68be-30b313f107b8
* Content: [Set-CASMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-casmailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-CASMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-CASMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Yorkwu1 I made the descriptions of all EWS related parameters consistent across Set-OrganizationConfig and Set-CASMailbox. I also cleaned them up and improved them.

Thanks for the feedback.
