### ISSUE TITLE
Teams -Reached catch method Error occurred while executing Code: GeneralException Message: Failed to start/restart provisioning of Team InnerError 

### ISSUE THREAD

**Issue by vinit14360** [MicrosoftDocs/office-docs-powershell#1573]
I was trying to create Teams using Powershell script as below
$GroupID = (New-Team -DisplayName $TeamName -AccessType Private -Description $TeamDescription).GroupId

in general this code execute well and it creates the Teams succesfully.but some time once in 100 times i have received the Following error:

Reached catch method Error occurred while executing Code: GeneralException Message: Failed to start/restart provisioning of Team InnerError: RequestId: d7bba0bc-950b-4a7b-af6b-be80d3a542a7 DateTimeStamp: 2018-08-03T10:10:58 HttpStatusCode: GeneralException

Need to undertsand why this Exception Occured

**Comment by kenwith** [comment]
@vinit14360 - thank you for submitting feedback. 

I am not sure why this exception occurred. I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by vinit14360** [comment]
Thanks Ken for your prompt reply.

We have raised a service Ticket with MS office 365 Support. will update you about the outcome.
