### ISSUE TITLE
Cannot enable Litigation Hold

### ISSUE THREAD

**Issue by liampkemp** [MicrosoftDocs/office-docs-powershell#1574]
When trying to set litigation hold in Exchange Online PowerShell Module
e.g.
```
Set-Mailbox <mailbox> -litigationholdenabled $true
#OR
Set-Mailbox | Set-Mailbox -litigationholdenabled $true
```
The following error is returned.

> A parameter cannot be found that matches parameter name 'litigationholdenabled'.
>     + CategoryInfo          : InvalidArgument: (:) [Set-Mailbox], ParameterBindingException
>     + FullyQualifiedErrorId : NamedParameterNotFound,Set-Mailbox
>     + PSComputerName        : outlook.office365.com

This behavior is different than when connecting to exchange online with 
```
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
import-pssession $session
```

**Comment by liampkemp** [comment]
Please disregard,
A permissions issue was preventing this.
Thanks

**Comment by kenwith** [comment]
@liampkemp - great info though for a tip in the article that if that error is seen check for a permission issue. Things like this are really valuable so thank you for taking the time to submit feedback.
