### ISSUE TITLE
The $false parameter shouldnt be there

### ISSUE THREAD

**Issue by AndyTuke** [MicrosoftDocs/office-docs-powershell#1575]
Docs say that the cmdlet does not take any parameters, so that shouldn't be there.  I guess someone copied the example from the set cmdlet and forgot to remove it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb86a30f-a479-7b2b-41b0-3f8acbbd17be
* Version Independent ID: fcde0b09-6c66-4439-023e-4ac346bb7568
* Content: [Get-SPOHideDefaultThemes (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Get-SPOHideDefaultThemes?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHideDefaultThemes.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHideDefaultThemes.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@AndyTuke Thank you for catching this

I will get this over to the PowerShell team so we can get this updated. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
Created PR# https://github.com/MicrosoftDocs/office-docs-powershell/pull/2790 to make corrections in the document.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @AndyTuke  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
