### ISSUE TITLE
Is this command still relevant?

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftDocs/office-docs-powershell#1578]
Since Microsoft announced new REST web service to access the IP data in JSON and CSV formats (http://aka.ms/o365ip) is this command will be still working?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faa26b0f-4e34-d61e-c7c9-835ed52f4e65
* Version Independent ID: 3163707e-aae4-69ef-b857-f32a941001a8
* Content: [Get-HybridMailflowDatacenterIPs (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/get-hybridmailflowdatacenterips?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/Get-HybridMailflowDatacenterIPs.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/Get-HybridMailflowDatacenterIPs.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dstrome can you clarify anything here?

**Comment by dstrome** [comment]
I'm not aware of any plans to deprecate this cmdlet at this time.
