### ISSUE TITLE
DesignateAsPresenter

### ISSUE THREAD

**Issue by roberthstrand** [MicrosoftDocs/office-docs-powershell#1589]
DesignateAsPresenter says in the description that the default is "Company", while underneath it says that it's "None".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7d9d1da-e548-5f48-b0b1-18ef69c0caac
* Version Independent ID: 2f967ff1-cb4f-2394-cf10-ed8f5188a0c6
* Content: [Set-CsMeetingConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csmeetingconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsMeetingConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsMeetingConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@roberthstrand Thank you for this feedback

I will get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
Created PR#https://github.com/MicrosoftDocs/office-docs-powershell/pull/2791 to make the correction on doc.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @roberthstrand  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
