### ISSUE TITLE
PARAMVALUE is what ?

### ISSUE THREAD

**Issue by yssky** [MicrosoftDocs/office-docs-powershell#1596]
-UserCertificateReplicationThreshold
PARAMVALUE: UInt64

-WinFabMaxLogsSizeMb
PARAMVALUE: Int32
Please add a complete explanation！！！

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea2ff0f3-33bf-46c5-84f5-7753b83b8a95
* Version Independent ID: e73a03b9-5a68-e0f3-86fa-0e722239437e
* Content: [New-CsRegistrarConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csregistrarconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsRegistrarConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsRegistrarConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@yssky Thank you for this feedback

I will get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by yogkumgit** [comment]
@kenwith after reserch @get-itips says:
New-CsRegistrarConfiguration
Has two param values that lack documentation
WinFabMaxLogsSizeMb
I understand it belongs to Windows Fabric and a possible description could be the maximum log file size in Mb, please confirm.
the other is UserCertificateReplicationThreshold
It's obviously referencing the user certification but we need more information to write a description to update the documentation.

**Comment by get-itips** [comment]
Hi @yssky thanks, your suggestion improved the documentation as we added a description for the mentioned parameters.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @yssky 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
