### ISSUE TITLE
Where is the categorized SharePoint PowerShell comdlets?

### ISSUE THREAD

**Issue by mic8989** [MicrosoftDocs/office-docs-powershell#1599]
Where is the categorized SharePoint PowerShell comdlets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a90c18-81d3-0ae4-0abb-a4fa9c331f4b
* Version Independent ID: bbfcc73a-2696-527e-8e6d-95b5bc8b7f17
* Content: [SharePoint Server PowerShell](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/sharepoint-server.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/sharepoint-server.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
It is part of #1376 but is not complete.

**Comment by AndreaBarr** [comment]
@mic8989 Thank you for this feedback

It looks like Trevor has answered your question so I am going to close this issue. If this issue is not resolved please reopen the issue.
