### ISSUE TITLE
Update required properties

### ISSUE THREAD

**Issue by rroddy24** [MicrosoftDocs/office-docs-powershell#1600]
When using Start-HistoricalSearch, at least one of these parameters is required, and we list them all as Optional, with no note anywhere regarding one of them being required:
-MessageID
-SenderAddress
-RecipientAddress

If you try to run the command without one of these, you will get an error:
You must specify at least a message ID, a sender, or a recipient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a22164-2df5-5dc2-9292-df60df018a53
* Version Independent ID: 1d96478c-230b-889e-68ed-9a8ab9484be5
* Content: [Start-HistoricalSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/Start-HistoricalSearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Start-HistoricalSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Start-HistoricalSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rroddy24, from the binary value of Required or Optional, I can see why these parameters aren't treated as Required; it's too subtle, and those Required/Optional values are determined by code, so I don't want to muck with them (especially in this case).

So I added the following text to each of the 3 existing required parameters in PR #1645 :

You also need to specify at least one of the following values in the command: MessageID, RecipientAddress, or SenderAddress.

Thanks for the feedback.
