### ISSUE TITLE
Example 1

### ISSUE THREAD

**Issue by BrianJE** [MicrosoftDocs/office-docs-powershell#1601]
Example 1's description looks wrong, it got copy and pasted from example 2. Based on the description of the switch '-Identity' it should get a mobile device named "TonySmith".

Also, as '-Mailbox' is required are we allowed to search for a specific device name like that? Or would it require:
Get-MobileDevice -Mailbox "Redmond\TonySmith" -Identity "TonySmith"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 675ea59e-0042-9e34-5ba7-0dfbee208dc8
* Version Independent ID: 62c903ea-94ae-8aa6-59ca-9adc1540c3d7
* Content: [Get-MobileDevice (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/get-mobiledevice?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/devices/Get-MobileDevice.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/Get-MobileDevice.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@BrianJE it appears the intent of Example 1 and Example 2 were to simply illustrate using different Mailbox identity values. I found that rather lame, so I replaced it with better examples.

Regarding Mailbox vs. Identity, according to the parameter sets (syntax blocks), you can't use Mailbox and Identity in the same command, and Identity is optional (you can run Get-MobileDevice by itself to get a big list). In other words, Mailbox is required only in Set2.

- Mailbox requires a unique mailbox identifier (Name, GUI, DN, etc.).

- Identity is of type MobileDeviceIdParameter, which (according do the description) is either a GUID value, the Name value (iPhone§\<biglongnumber\> or iPad§Appl\<bignumber\>) or Identity value <username>\ExchangeActiveSyncDevices\\<Name\> where \<Name\> is like iPhone§\<biglongnumber\> or iPad§Appl\<bignumber\>.

**Comment by andypituch** [comment]
Can this be corrected... not sure how this issue was closed when the Example was not updated? Example 1 is still incorrect as it attempts to find a mobile device ID named "TonySmith" and not the devices for the "tonySmith" mailbox (which would be -mailbox "TonySmith")

cmd should be: _Get-MobileDevice -Mailbox "TonySmith"_

**Comment by chrisda** [comment]
@andypituch, I fixed it. Changes are winging their way live now.

**Comment by andypituch** [comment]
Thank you! Looks good :)
