### ISSUE TITLE
Undo-SoftDeletedUnifiedGroup: Please stop 'offering' just the absolute minimum of Docs.

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/office-docs-powershell#1604]
Hello
it's really a shame that M$$ is no longer answering the very obvious questions in the 'Docs'. We know: it's annoying to write Docs, but it should not be obvious that M$$ hates it to write them.

For example, the 'Docs' for Undo-SoftDeletedUnifiedGroup does not answer many very basic questions:

- If there is a SoftDelete: how can we permanently delete soft deleted objects?
- If there is a SoftDelete: how can directly delete objects without using SoftDelete?
- How can we get a list of all SoftDeleted Objects?

It's a shame that M$$ writes much less useful / incomplete Docs than our apprentices are doing it - in their 2nd / 3dr year. At least, they answer all obvious questions.

**Comment by kenwith** [comment]
@schittli - It has been a shift moving to an open source system with GitHub. I am sorry it has come across as we don't like to write the docs. Thanks for pointing out this deficiency and I am adding it to the backlog for the writing team so we can get this addressed. Any areas you find that need more attention please keep the feedback coming so it can get in the backlog and get prioritized and addressed.

I added a note to the backlog item to reply to this thread when the SoftDelete content is added.

**Comment by chrisda** [comment]
@schittli, I added the following paragraph to the DESCRIPTION section of the Undo-SoftDeletedUnifiedGroup cmdlet topic:

To display all soft-deleted Office 365 groups in your organization, use the Get-AzureADMSDeletedGroup cmdlet in Azure Actived Directory PowerShell. To permanently remove (purge) a soft-deleted Office 365 group, use the Remove-AzureADMSDeletedDirectoryObject cmdlet in Azure Active Directory PowerShell. For more information, see [Permanently delete an Office 365 group](https://support.office.com/article/b7c66b59-657a-4e1a-8aa0-8163b1f4eb54#bkmk_perm).
