### ISSUE TITLE
Enumerate full data sets with cmdlets if you are a global administrator

### ISSUE THREAD

**Issue by fredericklin** [MicrosoftDocs/office-docs-powershell#1605]
If an account is a global administrator, could it be made so that the cmdlet would enumerate the full data set instead of only those that the account is a member of?

Examples:
- Get-Team should get **all** teams in the tenant
- Get-TeamChannel -ObjectId _guid_ should return the properties of the team channel.  Instead, I am getting an AccessDenied error because my account isn't a member of the Office 365 Group for the team.

**Comment by AndreaBarr** [comment]
@fredericklin Thank you for this feedback.

I will get this over to the PowerShell Team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@fredericklin Thank you for bringing this to our notice. This cmdlet is now fixed in the latest module 0.9.6.

Now, Get-team gets all teams in the tenant and get-teamchannel -groupid returns properties of the team channel if you are an administrator.

Thank you for reporting and making the docs better. Much appreciated.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @fredericklin  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by fredericklin** [comment]
@msbemba @yogkumgit @AndreaBarr Thank you!
