### ISSUE TITLE
Get-CsPoolUpgradeReadinessState not available in Skype for Business Server 2019

### ISSUE THREAD

**Issue by NeeranjanShettar** [MicrosoftDocs/office-docs-powershell#1610]
I do notice the command [ **Get-CsPoolUpgradeReadinessState** ] isn't available in Skype for Business Server 2019, however the [document ](https://docs.microsoft.com/en-us/powershell/module/skype/get-cspoolupgradereadinessstate?view=skype-ps) still shows this command applies to Skype for Business Server 2019. 

I am not sure if this command is deprecated. It's a feedback to add in Skype for Business 2019 if it is missed else I would love to know if it is deprecated intentionally due to valid technical reason.

**Comment by AndreaBarr** [comment]
@NeeranjanShettar Thank you for this feedback


I will get this over to the PowerShell team for investigation and updating. 


I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by NeeranjanShettar** [comment]
Thanks, will look forward to see the updates..

**Comment by AndreaBarr** [comment]
@NeeranjanShettar No updates yet. The PowerShell team is prioritizing this into a sprint.

**Comment by NeeranjanShettar** [comment]
Well, i think this should be taken care immediately \ soon, as today itself the Skype for Business server 2019 is General Available.

**Comment by kenwith** [comment]
@NeeranjanShettar - are you on the product team by any chance? The cmdlets are self-service and owned by the product team. I can try to escalate to them unless you happen to be on that team?

**Comment by NeeranjanShettar** [comment]
@kenwith - I am not from product team, please try escalating to them .. Thanks..

**Comment by NeeranjanShettar** [comment]
@kenwith  - any updates here, it's been long time no updates/response here. thanks in advance.

**Comment by AndreaBarr** [comment]
@get-itips Could you please investigate this?
