### ISSUE TITLE
Command Permissions

### ISSUE THREAD

**Issue by raymondlittle100** [MicrosoftDocs/office-docs-powershell#1623]
Might be useful to document the minimum permissions levels needed to run this i.e. I tried to run this as a SP admin but this seems to return an error. The site creates but I get an error which is probably related to creating an O365 group

New-PnPSite : {"d":{"CreateGroupEx":{"__metadata":{"type":"Microsoft.SharePoint.Portal.GroupSiteInfo"},"DocumentsUrl":null,"ErrorMessage":null,"GroupId":"64cf2376-e695-4bd3-9661-e71ce9c3eb25","SiteStatus":1,"SiteUrl":null}}}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5e3530-a63e-71ce-97c8-c904619aafa8
* Version Independent ID: 2c961b64-5c27-6331-b704-716ccfb8c5a7
* Content: [New-PnPSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpsite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@raymondlittle100 Thank you for this feedback

I will get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @raymondlittle100 , thank you for your feedback.

SharePoint Online Administrators can create Office 365 groups.

Did you try with New-PnPTenantSite?

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @raymondlittle100  Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
