### ISSUE TITLE
Organization prefix/suffix parameter is missing

### ISSUE THREAD

**Issue by Azaama** [MicrosoftDocs/office-docs-powershell#1625]
Hi,

In our company, a naming convention have been set for Microsoft Teams.
When trying to create a team with New-Team, we receive the following error.

> Code: Request_BadRequest
> Message: The property is missing a required prefix/suffix per your organization's Group naming requirements.

Can you help on this please ?

Thanks in advance.

**Comment by AndreaBarr** [comment]
@Azaama Thank you for this feedback

I want to make sure you get the proper answers. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
