### ISSUE TITLE
AutoRetryCount attribute

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/office-docs-powershell#1647]
AutoRetryCount is no longer a valid attribute for New-MigrationBatch in Exchange Online. Please update the article accordingly, by removing Exchange Online from the "applicable" section of the attribute explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf2e681a-0bba-7d71-e367-44266ea40a4a
* Version Independent ID: 8fbe3c52-c74a-1e09-1318-177643594bd0
* Content: [New-MigrationBatch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/new-migrationbatch?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Alex-Catalin, confirmed. I also found some other parameters that were either on-prem only or cloud-only, and marked them as appropriate. I also found a new cloud-only parameter (ExcludeDumpsters).

Thanks for the feedback.
