### ISSUE TITLE
Connect-EXOPSSession overwrites $UserPrincipalName

### ISSUE THREAD

**Issue by ChrisMagnuson** [MicrosoftDocs/office-docs-powershell#1653]
Based on the [this blog article](https://ingogegenwarth.wordpress.com/2018/02/02/exo-ps-mfa/) you can see that the exchange online modules sets `$Global:UserPrincipalName` and checks whether it is set as a part of its logic to tell what state it is in.

This is causing us errors as we use $UserPrincipalName in our provisioning scripts.

At the very least this should be renamed something unique so that it isn't as likely to collide with user scripts, something like `$Global:ExchangeOnlineModuleUserPrincipalName`.

I have tried to find where I can submit this as an issue and this is the only place I could locate that might be able to get this information in the right hands so that this can be fixed.

**Comment by AndreaBarr** [comment]
@ChrisMagnuson Thank you for this feedback

I will get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by yogkumgit** [comment]
@ChrisMagnuson   Thank you very much for your kind feedback. Considering your valuable feedback, we have logged this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

User Voice Link: https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/33378199-ise-support-for-connect-exopssession
