### ISSUE TITLE
Typo: "date rage" -> "date range"

### ISSUE THREAD

**Issue by brentlightsey** [MicrosoftDocs/office-docs-powershell#1655]
Typo noticed: "all events in a specified date **rage**" rather than "**range**".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d47105-b32e-f0f8-3e71-db411c6abe7c
* Version Independent ID: 338beb1b-1f13-0a77-9ac3-1c4fe542b612
* Content: [Search-UnifiedAuditLog (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@brentlightsey I fixed it.

Thanks for the feedback.
