### ISSUE TITLE
-Tenant is NOT a valid parameter.  

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/office-docs-powershell#1657]
It should be -TenantID.  PowerShell autocomplete does allow this cmdlet however it fails.  You must use -TenantID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e2e6c7-2f77-9ade-ce60-9e19a5e60093
* Version Independent ID: 394e4f42-7e87-e0d2-c34f-2e0ab45af85e
* Content: [Set-CsHostedVoicemailPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cshostedvoicemailpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsHostedVoicemailPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsHostedVoicemailPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@dinocaputo Thank you for this feedback

I will get this over to the PowerShell team so we can update this cmdlet.

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @dinocaputo , thank you for your feedback.

I have tried in a SfB 2015 Server lab environment with the latest updates and I only see -tenant parameter on New/Set-CsHostedVoicemailPolicy cmdlet/s. I cannot see -TenantID.

Could you double check? Where you see -TenantID? Thank you!

**Comment by dinocaputo** [comment]
Hmm.  Clearly this has changed since I tested it in September ;-)  
As I just retested it either "-tenant" or "-tenantID" function when using a set-csHostedVoicemailPolicy cmdlet.  When I submitted "-tenant" did NOT function.  
The confusing part is a get-csHostedVoiceMailPolicy shows the attribute as "TenantID" but the cmdlet docs show -Tenant.  As I mentioned it appears either parameter now works.  Not sure if that is expected behaviour or not.

**Comment by dariomws306** [comment]
Thank you for your fast reply.

I have verified Get- and I also see -Tenant there.

![image](https://user-images.githubusercontent.com/33589238/52526587-ad435400-2c99-11e9-8ee9-c4e2ad929c5e.png)

**Comment by dinocaputo** [comment]
Yes but what I mean is this:
![image](https://user-images.githubusercontent.com/32268083/52526610-5897dd00-2c89-11e9-8357-d2dcc1bcb846.png)

**Comment by dariomws306** [comment]
Interesting... I cannot run this cmdlet with -TenantID in my lab neither I get it when I run Get-CsHostedVoiceMailPolicy.

![image](https://user-images.githubusercontent.com/33589238/52526891-6d32a000-2c9e-11e9-81a7-889b6136584c.png)

Based on what we have been testing, do you think we should update this article?

Thank you!

**Comment by dinocaputo** [comment]
I’m running SfB Server 2019. You?

Sent from my iPhone

On Feb 9, 2019, at 5:11 PM, Dario Woitasen <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting... I cannot run this cmdlet with -TenantID in my lab neither I get it when I run Get-CsHostedVoiceMailPolicy.

[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F33589238%2F52526891-6d32a000-2c9e-11e9-81a7-889b6136584c.png&data=02%7C01%7C%7Cbecf8950ef674ad0464808d68edb8b3b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636853470909836491&sdata=5IkN2iaMFhCTqCWJfp5Oa%2Ff%2B54L%2F3s%2BICyCmAwwQkDA%3D&reserved=0>

Based on what we have been testing, do you think we should update this article?

Thank you!

**Comment by dariomws306** [comment]
2015... It should be the same for this but...

**Comment by dariomws306** [comment]
Hi @dinocaputo , do you think we should update this doc?

I think if -Tenant works for all versions it's a good idea to leave it as it is.

Thank you.

**Comment by dinocaputo** [comment]
I guess there is no update required since both -Tenant and -TenantID work.  I still think the there is confusion between the set and the get version of the cmdlets however...  If the PG agrees then they can make the decision to update the cmdlets or the docs.

**Comment by dariomws306** [comment]
I have added a note about this. You can check https://github.com/MicrosoftDocs/office-docs-powershell/pull/2886.

Thanks!

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR if you find it suitable.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @dinocaputo  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
