### ISSUE TITLE
-SummarizeBy Domain

### ISSUE THREAD

**Issue by MichaelMc64** [MicrosoftDocs/office-docs-powershell#1660]
This parameter needs additional examples or clarification. I have about 20 domains in my tenant. When I run the command given in Example 3, there is a column for domain in the result returned. However, that column is completely blank. Domain is also blank if it is the only value I give for summarizeby.  I was hoping to get a summary for each domain. Instead, it appears this parameter does nothing so I need to run a report for each individual domain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb20809-8f21-dfd3-23bf-bbfb82679619
* Version Independent ID: be54b158-1672-5ae9-6a6d-139a7850c67b
* Content: [Get-MailTrafficReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/reporting/Get-MailTrafficReport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/reporting/Get-MailTrafficReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/reporting/Get-MailTrafficReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by MichaelMc64** [comment]
Additional testing:

Running the command in example 2 also returned results with the domain column all blank. Running that same command using the -domain switch fixes that problem. However, when using "-domain all", there are many rows (about 40) where domain is blank and about 7 rows showing a domain of "Others". I've no idea how to interpret the blank domains or the domain of "Others".

Adding "-Summarizeby domain" results in domain being all blank again, regardless of whether the -domain parameter specifies a single domain, all, or is not present at all.

**Comment by AndreaBarr** [comment]
@MichaelMc64 Thank you for this feedback

I will get this over to the PowerShell team so we can get more examples in this article. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @MichaelMc64 , thank you for your feedback.

When you use -SummarizeBy Domain, it's ok that you don't see the domain because it summarizes all the domains in one line. The same happen when you use -SummarizeBy EventType.

When you use or not the parameter -Domain is explained in the parameter description, based on your testing it works as expected. Please check the description and let me know if you think it's not well explained.

Thank you!

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @MichaelMc64 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
