### ISSUE TITLE
Output from this cmdlet requires some explanation

### ISSUE THREAD

**Issue by MichaelMc64** [MicrosoftDocs/office-docs-powershell#1662]
Running the command in the example given gives a list of email addresses with a heading of C1. Piping the command to Format-table gives a shorter list of results than without, though still only shows the single column of C1.
Running the command with | Format-List gives the email address as the value for C1, a number for C2 (possible the number of messages?), and C3 which is always blank. Some explanation of what C1, C2, and C3 are would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 471b3917-4928-2b98-d91a-46e2490701eb
* Version Independent ID: c5d7a298-2c11-1141-b697-65e34b39c93b
* Content: [Get-MailTrafficSummaryReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/reporting/get-mailtrafficsummaryreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/reporting/Get-MailTrafficSummaryReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/reporting/Get-MailTrafficSummaryReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@MichaelMc64 Thank you for this feedback

I will make sure that this gets over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @MichaelMc64 , thank you for your feedback. I am working on it.

Let me try to get more information about C1, C2 and C3 properties.

**Comment by dariomws306** [comment]
I have added some explanation about this.

Thanks!

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR if you find it suitable.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @MichaelMc64  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
