### ISSUE TITLE
This cmdlet usage need to be clarified

### ISSUE THREAD

**Issue by mrik23** [MicrosoftDocs/office-docs-powershell#1665]
If we use "-Role Owner" the user is only added to as Owner of the group, this seems fine with Teams but not with all workloads.

For example, if an user is only set as Owner of a Group and not a member, that user will not see the plan associated with the Office 365 group in Planner (or it is Planner that doesn't work correctly).

When we create an Office 365 Group from Teams, Outlook or SharePoint, we are added as both member and owner, so I guess it is the right way.

Maybe you should make Add-TeamUser to add the user as member and owner, or you should clarify the documentation so we first add the user as member and then as owner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da0c53f2-1c62-14f6-6371-f54bf86b0c24
* Version Independent ID: aac162db-a9c0-fbfb-dd40-526e94d3bef8
* Content: [Add-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamuser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@mrik23 Thank you for this feedback

I will get this over to the PowerShell team so we can get this article updated. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @mrik23 , thank you for your feedback.

I am adding a line to let readers know that if they use this cmdlet to add an owner, they need to run this cmdlet again to add him as member.

**Comment by dariomws306** [comment]
PR:
https://github.com/MicrosoftDocs/office-docs-powershell/pull/2786

**Comment by moegitree** [comment]
Agree with @mrik23. But I found the explanation part added by @adriomws306 is missed now (5/30). 
I can see from article history that it was overwritten in Apr 24.
Teams PowerShell Module 1.0 was released in the same day. But cmdlet's add owner movement remained the same as commented by @mrik23.

Sorry but could you confirm this case one more time?

**Comment by dariomws306** [comment]
Hi @paarthchothani,

Could you help with this?

It's true that you get different behavior. If you add an owner from the Team Client or Web, the owner is also added as member in the Office 365 group. If you add an owner from Powershell, it's not added as a member in the Office 365 group. Then you can get some issues or different experience as @mrik23 and @moegitree commented.
So I think the article should have a note about this.

Thanks!
