### ISSUE TITLE
Boundaries and limits

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/office-docs-powershell#1666]
Is there any limit in the size of the web site that can be exported by using this cmdlet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0320cbf-e634-8ded-cd0f-7289fee2bc5e
* Version Independent ID: 0011fd58-8ccd-1bd8-939e-91976e4f07c3
* Content: [Export-SPWeb (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/export-spweb?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Export-SPWeb.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Export-SPWeb.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@LuigiBruno thank you for your recent comment.  I have checked with the product team and there is no limit that they see. thank you.

**Comment by LuigiBruno** [comment]
@Techwriter40 Thank you.
