### ISSUE TITLE
Example is incorrect

### ISSUE THREAD

**Issue by ykuijs** [MicrosoftDocs/office-docs-powershell#1667]
The example is mentioning the cmdlet Repartition-SPEnterpriseSearchLinksDatabases, which should be Move-SPEnterpriseSearchLinksDatabases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96bad38-081e-945d-3faf-de934d936c06
* Version Independent ID: 0a74c992-ef80-b833-9160-5e6cf7a63fc5
* Content: [Move-SPEnterpriseSearchLinksDatabases (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/move-spenterprisesearchlinksdatabases?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Move-SPEnterpriseSearchLinksDatabases.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Move-SPEnterpriseSearchLinksDatabases.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@ykuijs Thank you for this feedback

I looks like Trevor is updating this. We are just waiting on some verifications. I am going to close this until the merge is complete. 


@tseward Can you please double check the verification on this merge request, there are a few errors that came up.
