### ISSUE TITLE
Basic Auth?

### ISSUE THREAD

**Issue by STHorstman** [MicrosoftDocs/office-docs-powershell#1671]
Is it on the roadmap to provide a solution that doesn't require basic authentication to be enabled? Every other Microsoft security recommendation says to turn it off and here we have to turn it on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@STHorstman Thank you for this feedback

I will get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by xencon** [comment]
There is a uservoice post on this exact topic: https://office365.uservoice.com/forums/264636-general/suggestions/20570782-allow-winrm-authentication-other-than-basic-when-c

Upvote!

**Comment by kenwith** [comment]
I just up voted it too. :)

**Comment by STHorstman** [comment]
Thanks xencon! 3 votes up.

**Comment by jeffabreunig** [comment]
Any update on bringing MFA to this solution? I would like to be able to manage my clients' tenants in PowerShell with the delegated permissions without having to remove MFA... With Microsoft's pending implementation of a baseline protection policy to require MFA for admins, it seems a bit ridiculous that this wouldn't work... 

https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/baseline-protection

**Comment by AndreaBarr** [comment]
@jeffabreunig No update here but you can check the user voice they post updates there. 

There is a uservoice post on this exact topic: https://office365.uservoice.com/forums/264636-general/suggestions/20570782-allow-winrm-authentication-other-than-basic-when-c

**Comment by student-forever** [comment]
@AndreaBarr I just wanted to check in and confirm if there are any updates on the sprint plan you specified for the backlog in Powershell team. I know I would appreciate any reference number or case number for the said sprint plan, along with an approximate ETA.

**Comment by kenwith** [comment]
@student-forever - there is no item in backlog for the document. I think it was a miscommunication. The item for this feature request is in the User Voice link posted above. The product teams keep track of feature requests in User Voice. We are just focused on the content help here.
