### ISSUE TITLE
Misleading Error Message

### ISSUE THREAD

**Issue by psykokwak4** [MicrosoftDocs/office-docs-powershell#1673]
Seems like the `local` and `action` are switched in the error message, for a wrong cmdlet such as: `New-PolicyTipConfig wrong\wrong -Value wrong`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0893f2-47a8-a67b-bf46-d58c7d4a950c
* Version Independent ID: 5d10065e-44fd-76f1-e5f4-70bb9dec06b1
* Content: [New-PolicyTipConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/new-policytipconfig?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/New-PolicyTipConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/New-PolicyTipConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@psykokwak4 Thank you for this feedback

I will get this over to the PowerShell Team so we can get this investigated and updated. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @psykokwak4 , thank you for your collaboration.

I see your point:
Name must be in the form locale\action where **_action_** can be: "zh-CHS, en, fr, de, ja, zh-CHT, it, ko, pt, ru, es, ar, cs, da, nl, fi, el, he,
hu, no, pl, pt-PT, sv, tr, ro, th, fil-PH, hi, id, lv, ms, uk, vi, bg, hr, et, lt, sr, sk, sl, eu, ca, zh-HK, fa, gl, is, kk, sr-Cyrl-CS,
ur, af, sq, am-ET, hy, as-IN, bn-IN, bn-BD, bs-Cyrl-BA, bs-Latn-BA, ka, gu, ha-Latn-NG, ig-NG, iu-Latn-CA, ga-IE, xh-ZA, zu-ZA, kn, km-KH,
quc-Latn-GT, rw-RW, sw, kok, ky, lo-LA, lb-LU, mk, ms-BN, ml-IN, mt-MT, mi-NZ, mr, ne-NP, nn-NO, or-IN, ps-AF, pa, quz-PE, nso-ZA, tn-ZA,
si-LK, ta, tt, te, uz, cy-GB, wo-SN, yo-NG" and **_locale_** can be: "NotifyOnly, RejectOverride, Reject, Url".  If action is URL, then name must
be "Url" with no locale.

Let me check how we can manage it.

**Comment by psykokwak4** [comment]
zh-CHS seems to be the locale

**Comment by dariomws306** [comment]
Yes, it should be:

Name must be in the form locale\action where **_locale_** can be: "zh-CHS, en, fr, de, ja, zh-CHT, it, ko, pt, ru, es, ar, cs, da, nl, fi, el, he,
hu, no, pl, pt-PT, sv, tr, ro, th, fil-PH, hi, id, lv, ms, uk, vi, bg, hr, et, lt, sr, sk, sl, eu, ca, zh-HK, fa, gl, is, kk, sr-Cyrl-CS,
ur, af, sq, am-ET, hy, as-IN, bn-IN, bn-BD, bs-Cyrl-BA, bs-Latn-BA, ka, gu, ha-Latn-NG, ig-NG, iu-Latn-CA, ga-IE, xh-ZA, zu-ZA, kn, km-KH,
quc-Latn-GT, rw-RW, sw, kok, ky, lo-LA, lb-LU, mk, ms-BN, ml-IN, mt-MT, mi-NZ, mr, ne-NP, nn-NO, or-IN, ps-AF, pa, quz-PE, nso-ZA, tn-ZA,
si-LK, ta, tt, te, uz, cy-GB, wo-SN, yo-NG" and **_action_** can be: "NotifyOnly, RejectOverride, Reject, Url". If action is URL, then name must
be "Url" with no locale.

**Comment by yogkumgit** [comment]
@psykokwak4   Thank you very much for your kind feedback. Considering your valuable feedback, we have logged this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

User Voice Link: https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/36860689-new-policytipconfig
