### ISSUE TITLE
Exchange server 2010 & 2016, secondary email adresses

### ISSUE THREAD

**Issue by Romulucius** [MicrosoftDocs/office-docs-powershell#1683]
Hello,

We host mailboxes on both Exchange server 2010 & 2016, but lately we have been encountering an error concerning the following cmdlet:

 Set-Mailbox -Identity "<account_cname>" -EmailAddresses @{add="<secondary email>"}

This cmdlet works fine on Exchange 2016, but returns the followin error on 2010:

La cmdlet ne peut pas fonctionner sur un serveur Exchange 2013 ou ultÃ©rieur.     + CategoryInfo          : NotSpecified: (MBOX14:ADObjectId) [Set-Mailbox], TaskInvaliOperationException     + FullyQualifiedErrorId : BE1E2900,Microsoft.Exchange.Management.RecipientTasks.SetMailbox

(The cmdlet cannot work on an Exchange 2013 server or higher)

I also tried the following syntaxes without success:
Set-Mailbox "<account_cname>" -EmailAddresses "SMTP:<primary email>","<secondary email>"
Set-Mailbox "<account_cname>" -EmailAddresses "SMTP:<primary email>,<secondary email>"

Am I missing something?

Thanks in advance for your Help!

**Comment by AndreaBarr** [comment]
@Romulucius Thank you for this feedback

I want to get this script issue addressed properly. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
