### ISSUE TITLE
Connect-SPOService and a delegated delegated partner administrator with modern authentication

### ISSUE THREAD

**Issue by vinkobedek** [MicrosoftDocs/office-docs-powershell#1684]
I keep getting 401 when trying to connect to a customer tenant when using Connect-SPOService -Url https://{tenant}-admin.sharepoint.com/. 
I can normally connect to the admin center by using the browser or if using username password directly when calling Connect-SPOService.

Is there something that i am missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85cea8f8-239d-1f73-f13a-a5a3148b66e5
* Version Independent ID: ca809b64-206c-4dfa-7c79-b0a45979e953
* Content: [Connect-SPOService (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@vinkobedek Thank you for this feedback

I want to make sure your script issue is handled properly. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
