### ISSUE TITLE
ReportInterval unit?

### ISSUE THREAD

**Issue by Borkason** [MicrosoftDocs/office-docs-powershell#1687]
What units are used in ReportInterval? I assume minutes, but it would be good to know for certain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf2e681a-0bba-7d71-e367-44266ea40a4a
* Version Independent ID: 8fbe3c52-c74a-1e09-1318-177643594bd0
* Content: [New-MigrationBatch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/New-MigrationBatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@Borkason Thank you for this feedback

I will get this over to the PowerShell team so we can get the intervals area of this article update. Thank you for taking the time to make the docs better. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @Borkason , thank you for your feedback.

It's TimeSpan:
https://docs.microsoft.com/en-us/dotnet/api/system.timespan

You can set minutes, hours, seconds... Some examples:
10:00:00 (10 hours)
00:10:00 (10 minutes)

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @Borkason  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
