### ISSUE TITLE
CompleteAfter use-case?

### ISSUE THREAD

**Issue by Borkason** [MicrosoftDocs/office-docs-powershell#1688]
It would be nice to give an example use-case for using CompleteAfter. Why would you want to delay completion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf2e681a-0bba-7d71-e367-44266ea40a4a
* Version Independent ID: 8fbe3c52-c74a-1e09-1318-177643594bd0
* Content: [New-MigrationBatch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/New-MigrationBatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@Borkason Thank you for this feedback

I will get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by yogkumgit** [comment]
@chrisda  please review this PR and kindly merge it if you find it suitable
