### ISSUE TITLE
Did you miss an argument for New-UnifiedGroup?

### ISSUE THREAD

**Issue by carlossanlop** [MicrosoftDocs/office-docs-powershell#1691]
The -ErrorAction argument is missing among the supported arguments. Most commands (if not all) support this argument so the user can create PS scripts that automate tasks, and they can catch any exceptions by forcing the cmdlet to break on an error, by using -ErrorAction Stop. This cmdlet fails when the -ErrorAction argument is added, which makes it difficult to catch errors in scripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 316bada1-dbc7-f07a-4afa-d67330edef50
* Version Independent ID: d9380f67-a05a-ddd0-425c-af7023222c69
* Content: [New-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/new-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/New-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/New-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@yeiacatl Thank you for this feedback

I will get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by yeiacatl** [comment]
Thank you very much! Where can I check if the cmdlet has been updated?

**Comment by AndreaBarr** [comment]
@yeiacatl You can check the document or you can keep an eye on this issue page. When the document is updated we will make a comment here on this issue letting you know that the document has been updated.

**Comment by yeiacatl** [comment]
Hi @AndreaBarr, I noticed you reopened this. Is this being actively investigated now? Or has it been fixed already?

**Comment by AndreaBarr** [comment]
@yeiacatl We have changed our policy again so we re-opened the issues waiting to be worked on and I assinged one of our issue coordinators to this so that we can get this worked on.

**Comment by dariomws306** [comment]
Hi @carlossanlop , thank you for your feedback.

I see that -ErrorAction:Inquire and -ErrorAction:SilentlyContinue are available for this cmdlet, but not others.

**Comment by carlossanlop** [comment]
The one that is required to catch exceptions is Stop.
I am not sure if Inquire would help.

**Comment by yogkumgit** [comment]
@carlossanlop   Thank you very much for your kind feedback. Considering your valuable feedback, we have logged this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

User Voice Link: https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/34912696-adding-error-actions-parameters-available-in-remot

**Comment by m00nd** [comment]
@AndreaBarr  is it resolved, -ErrorAction Stop has been added or not?

**Comment by asajrawat211993** [comment]
Why is it closed? I don't see this resolved yet.

**Comment by dariomws** [comment]
Hi @m00nd and @asajrawat211993,

Here we can help to update/fix the article. As -ErrorAction Stop is not added to the code we cannot add it.
Please, vote in the following link as it´s the better way to reach the product group to request a feature:
https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/34912696-adding-error-actions-parameters-available-in-remot

Thanks!
