### ISSUE TITLE
Add-PnPClientSideWebPart missing documentation on WebPartProperties

### ISSUE THREAD

**Issue by ollij** [MicrosoftDocs/office-docs-powershell#1694]
I think there is a big problem with Add-PnPClientSideWebPart and Set-PnPClientSideWebPart on the missing documentation on WebPartProperties parameter. 

Currently we are forced to spend hours of work to figure out how to set different properties of the web part while inserting it from the provisioning code. For example I just used hours to find out that Image web part:
- has property "captionText" which can be used to set the text under the image
- has property "urlLink" which can be used to set the link for the image

Currently we are forced to examine the different properties (such as HtmlPropertiesData or PropertiesJson) of the existing web parts - or right down guess what the property names might be. This shouldn't be as hard as it is. 

The information that should be here in the dev docs is outdated in various blogs and forum discussions.

**Comment by gautamdsheth** [comment]
Does [this](https://sharepoint.stackexchange.com/a/241707/8068) help ? Basically, just add your OOTB or custom SPFx webpart on the workbench page and configure it there. After that export the data and use it in your PS. This has worked well for me !

**Comment by VesaJuvonen** [comment]
This is not about missing cmdlet documentation as the needed properties are based on the web part design. We cannot provide documentation on the structure as they depend o how you have implemented your custom web part or which 1st party web part you are using. 

You can add a web part to a workbench and then get the needed configuration from there by clicking Web part Data - that's exactly why the capability was added on the workbench.

As needed documentation is not dependent on this cmdlet and it can be sorted out from the workbench, closing this. We are not looking into documenting different web part structures in the context of this helpful web part as there would not be anyway keeping them up to date. Please use the workbench for the updated configuration.
