### ISSUE TITLE
Not applicable to SP 2010

### ISSUE THREAD

**Issue by semopz** [MicrosoftDocs/office-docs-powershell#1695]
This command is not available in build 14.0.7015.1000 yet the article says that it applies to SharePoint 2010

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e5a912c-7460-a1f4-df44-63125419e1cb
* Version Independent ID: 16c85642-21ea-2748-4194-ab24a99da218
* Content: [Set-SPEnterpriseSearchFileFormatState (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/Set-SPEnterpriseSearchFileFormatState?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPEnterpriseSearchFileFormatState.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPEnterpriseSearchFileFormatState.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@semopz Thank you for this feedback

It looks like Trevor has updated the article and is waiting on verification. 

@tseward Can you check the verification on this.
