### ISSUE TITLE
two more clarifications which can save lots of time

### ISSUE THREAD

**Issue by h-david-a** [MicrosoftDocs/office-docs-powershell#1696]
1. You have to remove ALL ad objects which have msRTCSIP-PrimaryUserAddress property populated with sip address from removed domain. (like stale objects)
2. After domain removal, make sure to remove it from EDGE server certificates, otherwise, Skype will consider this domain as internal (even if it is totally removed from topology) and federation won't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3080c5cb-93e9-d7ca-8f66-2034678d04d9
* Version Independent ID: bcccebdd-48f1-15e2-d62e-96fd962e521b
* Content: [Remove-CsSipDomain (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/remove-cssipdomain?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Remove-CsSipDomain.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Remove-CsSipDomain.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@h-david-a Thank you for this feedback

I will get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
