### ISSUE TITLE
Global admin rights

### ISSUE THREAD

**Issue by ItsBradMorgan** [MicrosoftDocs/office-docs-powershell#1701]
Is there anyway to do this without needing Global Admin rights? I would like to delegate to collection owners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369ac4a3-96b9-7d17-eaf1-5b7bb2f12928
* Version Independent ID: cd322085-07d6-64f4-4aaa-d9200e3191aa
* Content: [Add-SPOUser (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spouser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOUser.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@ItsBradMorgan thank you for your feedback.  To my knowledge, there is no way to run a SPO cmdlet unless you have global admin rights. no way around this unfortunately.
