### ISSUE TITLE
How many sites can be added to HubSite

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/office-docs-powershell#1702]
Do we have a limit on how many sites can be added to HubSite?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 114697af-1b15-2582-49af-7ae2a8fe1cb0
* Version Independent ID: 6ed31c1e-1706-318b-5030-0e74dd9e875e
* Content: [Register-SPOHubSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/register-spohubsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Register-SPOHubSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Register-SPOHubSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by marrellsanders** [comment]
Per Mark Kashman, there is not currently a limit. 
"You can associate any number of of team sites and communication sites to the hub site."
https://techcommunity.microsoft.com/t5/SharePoint-AMA/Maximum-number-of-sites-associated-with-a-Hub-site-and-user/m-p/175076/highlight/true#M315

**Comment by AndreaBarr** [comment]
@ravick4u Thank you for this feedback

It looks like Marrell answered this for you so I am going to close this issue. If this issue is not resolved please reopen this issue.

**Comment by ravick4u** [comment]
Thanks @marrellsanders

**Comment by AndreaBarr** [comment]
closing again
