### ISSUE TITLE
-Identity should be a username, not a "valid URL"

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/office-docs-powershell#1703]
From the article under -Identity, the 2nd line should be deleted.
Specifies the GUID or login name of the user to be returned.
The type must be a valid URL, in the form http://server_name, or GUID, in the form1234-5678-9807.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7dac065-12ea-d063-d94f-2a0c8e17ae7f
* Version Independent ID: e1ef9913-238c-fb67-961b-faeec16c335b
* Content: [Get-SPUser (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spuser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Get-SPUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Get-SPUser.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@SharePointBlackBelt thank you for your feedback, but can you please resubmit this as a Pull request instead of a comment please.  thank you.
