### ISSUE TITLE
Lightmode explanation/rewrite needed

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/office-docs-powershell#1705]
-LightMode

"The LightMode switch tells the command to perform only a test logon to the server by using the POP3 protocol. You don't need to specify a value with this switch."

And then:

"If you don't use this switch, the command also tests sending and receiving a message using the POP3 protocol."

First off.  Nothing SENDS using POP3, its a receive only protocol.  Second off, lightmode seems to be the only way to get a success.  If I do not specify Lightmode, I get an error that my mailbox is in a different site.  Please explain what this is doing more?  So what really does this switch do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1a8e655-ad2e-1919-5c25-c42b5ed38c55
* Version Independent ID: 1655a847-38fc-894e-c9e4-e561e79a6383
* Content: [Test-PopConnectivity (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/test-popconnectivity?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Test-PopConnectivity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Test-PopConnectivity.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@chrislehr Thank you for catching this.

I agree this needs to be updated with the correct information.

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @chrislehr , thank you for your feedback.

What version of Exchange are you using? I think you could get this error if you are trying with Exchange 2013 or later.

I am removing "sending" from description.

**Comment by dariomws306** [comment]
PR:
https://github.com/MicrosoftDocs/office-docs-powershell/pull/2784

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @chrislehr  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
