### ISSUE TITLE
unable to use security groups to manage client access rule

### ISSUE THREAD

**Issue by adeelx78** [MicrosoftDocs/office-docs-powershell#1706]
can we use client access rule to block access to outlook for IOS /Android and mobile native client using security group / Azure AD dynamics group ?

 I am able to test it by entering user UPN but this can not be used as scale out solution. I am looking to use AAD dynamic group or mail enabled SG to manage users scope.

This is the powerShell command I am using to create the rule. don't see any parameter where I can provide security group object ID to define set of users.

New-ClientAccessRule -UsernameMatchesAnyOfPatterns 

if we can not use security group (AAD dynamic or static) with above comandlet then how we can build a scale able solution ?

**Comment by chrisda** [comment]
@adeelx78, client access rules are meant to block _protocol_ access (PowerShell, POP, IMAP, EWS, OWA, EAC, etc.) to Exchange Online. For more information, see this topic: https://docs.microsoft.com/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules.

Blocking access to Exchange Online by a specific application on a mobile device seems more like a job for Intune.

**Comment by adeelx78** [comment]
i understand that. i need to know how i can use below parameters with "New-ClientAccessRule" to block protocol for some set of users who are part of particular security group ? 

UsernameMatchesAnyOfPatterns
UserRecipientFilter

i am sorry if i wasn't clear on my question before.

**Comment by AndreaBarr** [comment]
@adeelx78 Thank you for this feedback

I want to make sure you get the correct help needed for this permissions issue. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
