### ISSUE TITLE
BookingsEnabled available in E16?

### ISSUE THREAD

**Issue by psykokwak4** [MicrosoftDocs/office-docs-powershell#1707]
&gt; This parameter is available only in the cloud-based service.

Seems like `-BookingsEnabled` is available for some 2016 CU updates(e.g. CU10).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3ab3f0-cc05-e279-8876-6da0b323bcac
* Version Independent ID: bfb49814-d60b-564a-25cc-f902dfa42b10
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@psykokwak4, I checked on an Exchange 2016 CU10 server, and the BookingsEnabled parameter wasn't available on Set-OrganizationConfig. That's not to say that it won't be made available in the future.

I also took the opportunity to verify the other parameters in the topic (some were erroneously tagged as on-premises only or cloud-only).

Thanks for the feedback.

**Comment by psykokwak4** [comment]
Seems strange:
```
PS C:\Users\Hybrid> Set-OrganizationConfig -BookingsEnabled:$false
PS C:\Users\Hybrid> Get-ExchangeServer | Format-List Name, Edition, AdminDisplayVersion


Name                : TESTSERVER
Edition             : StandardEvaluation
AdminDisplayVersion : Version 15.1 (Build 1531.3)
```

**Comment by psykokwak4** [comment]
And from this [documentation](https://technet.microsoft.com/en-us/library/hh135098(v=exchg.150).aspx), the above version means Exchange 2016 CU10? Or that doc also has issue?

Exchange Server 2016 CU10 | June 19, 2018 | 15.01.1531.003
-- | -- | --

**Comment by AndreaBarr** [comment]
@psykokwak4 Thank you for this feedback

I am adding this to the backlog so that Chris can track it properly. 

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
