### ISSUE TITLE
still not support mac

### ISSUE THREAD

**Issue by peterremote1980** [MicrosoftDocs/office-docs-powershell#1709]
PS /Users/peter/workspace/ServiceHelpDesk&gt; Connect-SPOService -Url https://$orgName-admin.sharepoint.com                                                                                      
Connect-SPOService : The type initializer for 'Microsoft.Win32.Registry' threw an exception.
At line:1 char:1
+ Connect-SPOService -Url https://$orgName-admin.sharepoint.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-SPOService], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.Online.SharePoint.PowerShell.ConnectSPOService

PS /Users/peter/workspace/ServiceHelpDesk&gt;  $PSVersionTable                                                                                                                                   

Name                           Value                                                                                                                                                         
----                           -----                                                                                                                                                         
PSVersion                      6.0.3                                                                                                                                                         
PSEdition                      Core                                                                                                                                                          
GitCommitId                    v6.0.3                                                                                                                                                        
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64                                                 
Platform                       Unix                                                                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                                                       
WSManStackVersion              3.0                      

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b23d72-33ed-a6a1-a442-a5e5cf039f9f
* Version Independent ID: 4247cf37-3667-2007-7251-46ed80f58ef5
* Content: [Getting started with SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@peterremote1980 Thank you for this feedback

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by drewhammond** [comment]
also waiting for mac support

**Comment by tseward** [comment]
I would suggest posting this feature request at https://sharepoint.uservoice.com/forums/330318-sharepoint-administration.

Keep in mind the *-SPO* cmdlets require .NET Framework 4.x, thus are not compatible with non-Windows OSes, like Linux or macOS.

**Comment by andrewconnell** [comment]
I know it's not the same as the request, but for those of you waiting for MacOS support, check out the [Office 365 CLI](https://pnp.github.io/office365-cli). It's cross-platform & while it may not have every capability as the POSH service, it's quickly getting to parity. 

If there's something missing, submit an issue/feature request or jump in and help. It's a PnP community project with a lot of activity.

**Comment by VesaJuvonen** [comment]
Classic PowerShell is not supported on the Mac/Apple/Linux machines. You can use the [Office 365 CLI](https://aka.ms/o365cli) as a short term workaround. There is also work being done to support .NET Standard with CSOM APIs, which will enable PowerShell Core... which will be then supported also on another than Windows machines, but no ETAs at this point. Closing this as answered.

**Comment by freshyogurt** [comment]
When will it be supported in Mac OS?

**Comment by TOWA-GitHub** [comment]
Still not working. Would be nice.

**Comment by jawad-aziz-farhad** [comment]
Not working on **macOS Big Sur** with **Mircorsoft.Online.SharePoint.PowerShell** Version **16.0.2171...**

**Comment by AinoL** [comment]
Still not working

**Comment by sewaroo** [comment]
Still not working :(

**Comment by berot3** [comment]
So why is this closed?

I tried just now with v7.3.0-preview.7

uninstalled and installed again Microsoft.Online.SharePoint.PowerShell 16.0.22810.12000
- https://www.powershellgallery.com/packages/Microsoft.Online.SharePoint.PowerShell/16.0.22810.12000
- which was updated 25 days ago
- according to powershellgallery it is not compatible to linux/macos 😪

and getting `Connect-SPOService : The type initializer for 'Microsoft.Win32.Registry' threw an exception.`

**Comment by dmuensterer** [comment]
Very unfortunate, that this is still not working on MacOS.

**Comment by ravanelli** [comment]
Still the same error "Microsoft.Online.SharePoint.PowerShell 16.0.23109.12000" no Mac support

**Comment by flotpg** [comment]
Also not working in Azure / M365 Cloud Shells.
![CleanShot 2023-08-08 at 23 01 53@2x](https://github.com/MicrosoftDocs/office-docs-powershell/assets/20798074/215af0be-1250-46bc-aa29-2f5bb43ed46a)
