### ISSUE TITLE
(403) Forbidden

### ISSUE THREAD

**Issue by Kagemae** [MicrosoftDocs/office-docs-powershell#1711]
I'm trying to use this to update a custom user property from a local file but we're getting the following error:

New-PnPUPABulkImportJob : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ New-PnPUPABulkImportJob -Connection $ctx -Folder $folder -Path $path  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-PnPUPABulkImportJob], WebException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.UserProfiles.NewUPABulkImpor 
   tJob

Script is as below:

$folder = "profile"
$path = "C:\profile\profile.json"

Connect-PnPOnline -Url https://walesandwesthousing.sharepoint.com -UseWebLogin

New-PnPUPABulkImportJob -Folder $folder -Path $path -IdProperty "email" -UserProfilePropertyMapping @{"payroll"="PayrollNumber"}

We're using GA credentials, I've confirmed that the 'folder' has contribute permissions.

Any help would be greatly appreciated.

Jason.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d731745-680b-fe7d-78fc-6757460f67b3
* Version Independent ID: 17045452-597a-b77e-897d-8af47dfae727
* Content: [New-PnPUPABulkImportJob (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpupabulkimportjob?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPUPABulkImportJob.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPUPABulkImportJob.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@Kagemae Thank you for this feedback. 

I want to make sure this script issue gets addressed. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
