### ISSUE TITLE
ClassicAttachmentsEnabled not available in some CU updates for E16?

### ISSUE THREAD

**Issue by psykokwak4** [MicrosoftDocs/office-docs-powershell#1713]
Seems like `ClassicAttachmentsEnabled` is not available in Exchange 2016 RTM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ca7906-9f33-2991-9da9-a626e5e45c46
* Version Independent ID: 5f388b3c-fb47-f7a0-e648-07cb3e59cf72
* Content: [Set-OwaMailboxPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-owamailboxpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@psykokwak4 Thank you for this feedback

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
