### ISSUE TITLE
Add QuickLinks webpart with links

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/office-docs-powershell#1717]
Hi,

I am able to add QuickLinks web part with below PowerShell but would like to see if there is a way I can add links as well with PowerShell command.

Add-PnPClientSideWebPart -Page "NewPage.aspx" -DefaultWebPartType:QuickLinks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f213768f-9bc2-36e3-fe0a-d1c3b7f33b08
* Version Independent ID: 3481fdb9-51ed-da91-2aa2-fd3745512f45
* Content: [Add-PnPClientSideWebPart (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpclientsidewebpart?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPClientSideWebPart.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPClientSideWebPart.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@ravick4u Thank you for this feedback

I want to make sure your script question gets answered properly. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by ravick4u** [comment]
@AndreaBarr This is related to PnP question and not sure why it needs a support ticket.

"Add-PnPClientSideWebPart" command does not have the option to add links to the quick link web part and I am looking for a way where I can add links to quick links web part with PnP PowerShell.

**Comment by AndreaBarr** [comment]
@ravick4u Sorry for the misunderstanding. If this if a PnP question we need to have it over in the PnP repo area. 

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  
 
Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
