### ISSUE TITLE
New-Team provisioning and applications w/ group lockdown

### ISSUE THREAD

**Issue by kf4ape** [MicrosoftDocs/office-docs-powershell#1719]
Ran into an issue with leveraging new-team and planner within teams...also we have group creation locked down to select folks in azure ad...if I build a group with new-unifiedgroup or from with in teams itself, the owner which is not a member of the locked down group can add planner without issue...however if I leverage new-team, the owner has to be a member of that group to allow planner into the team

**Comment by islubin** [comment]
@kf4ape  can you share information about how/where you're adding planner for both of these scenarios?

**Comment by kf4ape** [comment]
via the teams application, inside the team, I select the "+" in the channel tab, then select planner...users are licensed for planner also

**Comment by kf4ape** [comment]
once planner has been added to the application by someone that is allowed to create groups, subsequent planner additions by the owner other owners

**Comment by kf4ape** [comment]
here is the doc on the lockdown methodology I used - https://support.office.com/en-us/article/manage-who-can-create-office-365-groups-4c46c8cb-17d0-44b5-9776-005fced8e618

**Comment by islubin** [comment]
@kf4ape can you file a support case for this distinction, with repro steps for what error you get in Teams for adding planner if the group is created via new-unifiedgroup vs if the group is created via new-team?  I don't totally understand the path you're following, but if you file a support case they'll be able to help you troubleshoot.

**Comment by kf4ape** [comment]
I dont know if closed would be appropriate yet as it only happens with new-team commandlet and is not reproducible via normal team provisioning via teams application

**Comment by AndreaBarr** [comment]
@kf4ape Thank you for this feedback

The next time you have this issue come up we want to make sure it's documented and worked on by support so please open a support ticket. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by kf4ape** [comment]
Ticket has been opened and escalated...seems if the group is created with new-unifiedgroup and then add the script executor via add-unifiedgrouplinks as owner it will work (provided the group and teams syncs up in time, I have a 30 sec wait)...that is another issue I believe MS is working also, where executor needs to be an owner of the team/group to do features...

**Comment by AndreaBarr** [comment]
@kf4ape Thank you for this update. Please let us know what the resolution is when it's resolved.

**Comment by kf4ape** [comment]
So after some chats it appears that in order for planner to work, the individual must be an owner & member of the group...now via the gui, its not an issue...but via ADD-TEAMUSER it is...when I added the person as the owner, it didnt add as member, and when I added member, it nullified their owner status and rights despite being listed in 365 as an owner...I had to add as member first, then again to elevate them to owner...

doesnt matter right now anyway as I am getting general exceptions since last night with the commands, regardless of PC or site...all running 0.9.5

**Comment by kf4ape** [comment]
now that its back up and running...seems to be ADD-TEAMUSER as the possible root...now if I add a user with member role, then do owner, sticks as member...weird

**Comment by kf4ape** [comment]
so MS finally was able to reproduce the issue with ADD-TEAMSUSER...when leveraging powershell you need to run the following to flag a user as both OWNER and MEMBER...so they are now aware and hopefully will get the ADD-TEAMUSER fixed so that if you just add the role of owner it adds to both or something...also NEW-TEAM does the same, only adds the user to the owner, not memeber...

Add-TeamUser -GroupId $groupid -User $Owner
Add-TeamUser -GroupId $groupid -User $Owner -Role Owner
remove-TeamUser -GroupId $groupid -User $Owner -Role Owner
Add-TeamUser -GroupId $groupid -User $Owner -Role Owner

**Comment by msbemba** [comment]
@kf4ape Thank you for the update. This has been fixed in the latest teams module 0.9.6. The cmldet add-teamuser -role owner now adds the user as owner and member, same goes well with the new-team cmdlet.

Thank you for reporting and making the docs better. Much appreciated.

**Comment by kf4ape** [comment]
I was told it was NOT in 0.9.6

**Comment by msbemba** [comment]
@kf4ape Tried both the cmdlets New-team as well as add-teamuser it is now working as expected in 0.9.6. A user, when set as owner, is showing up as a member as well while using both the cmdlets. let us know if you still have issues, we may need to take the support route if it isnt working for your tenant.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @kf4ape  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
