### ISSUE TITLE
Rights required ?

### ISSUE THREAD

**Issue by JereckNET** [MicrosoftDocs/office-docs-powershell#1724]
Which permission/role does the user running this command needs on O365 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3cfbecc-18fb-bcb3-e852-33c023d283d8
* Version Independent ID: f2aa58c4-6725-1fc0-c5aa-398e42aa6f0b
* Content: [Add-PnPOffice365GroupToSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpoffice365grouptosite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPOffice365GroupToSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPOffice365GroupToSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@JereckNET Thank you for this feedback

This is a duplicate issue of https://github.com/MicrosoftDocs/office-docs-powershell/issues/1725. I am closing this issue.
