### ISSUE TITLE
Rights required ?

### ISSUE THREAD

**Issue by JereckNET** [MicrosoftDocs/office-docs-powershell#1725]
Which permission/role does the user running this command needs on O365 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a411ea94-f481-6bdc-8440-5f42fd8c86a3
* Version Independent ID: e85a164c-287a-a404-f798-e490ae802804
* Content: [New-PnPTenantSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnptenantsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPTenantSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPTenantSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@JereckNET Thank you for this feedback

I agree this information should be in the article. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @JereckNET , thank you for your feedback.

To run SharePoint Online cmdlets you need SharePoint Online Administrator permission.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @JereckNET  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
