### ISSUE TITLE
Module needed?

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/office-docs-powershell#1726]
Having some issue trying to set the address policys, in the module I have some of the required parameters are missing. When I try to access the module needed (on top of the page) I get 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6557027-9f33-615e-42c2-c77fd5b3fe2c
* Version Independent ID: b2b2b514-120e-1181-c1d2-42c07f45f5cd
* Content: [New-EmailAddressPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/email-addresses-and-address-books/new-emailaddresspolicy?view=exchange-ps#required-parameters)
* Content Source: [exchange/exchange-ps/exchange/email-addresses-and-address-books/New-EmailAddressPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/email-addresses-and-address-books/New-EmailAddressPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by xNiklasJern** [comment]
Thanks for the response @chrisda 

Still having some issues finding the correct parameters. Earlier I've tried several different ways to connect to Exchange Online, due to MFA. In powershell ISE
https://www.powershellgallery.com/packages/ExchangeOnlineShell/2.0.2
https://blogs.technet.microsoft.com/richardroddy/2018/04/04/using-powershell-ise-to-connect-to-exchange-online-when-mfa-is-enabled/
Non of the ways gives me the possibility user the required parameters, I  get the same issue if i disable MFA on my admin account and connect the way that you have linked to.

**Comment by chrisda** [comment]
@xNiklasJern can you connect to Exchange Online using regular PowerShell with MFA using the regular connection instructions: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell)?

The only other thing that could be going on is an RBAC/custom roles issue. There's nothing particularly weird about the email address policies cmdlet (nothing is restricted by default):

```
PS C:\Users\Administrator> Get-ManagementRoleEntry *\New-EmailAddressPolicy

Name                           Role                      Parameters
----                           ----                      ----------
New-EmailAddressPolicy         E-Mail Address Policies   {Confirm, EnabledEmailAddressTemplates, EnabledPrimarySMTPA…

PS C:\Users\Administrator> Get-ManagementRoleEntry *\New-EmailAddressPolicy | select -ExpandProperty Parameters
Confirm
EnabledEmailAddressTemplates
EnabledPrimarySMTPAddressTemplate
ErrorAction
ErrorVariable
IncludeUnifiedGroupRecipients
ManagedByFilter
Name
OutBuffer
OutVariable
Priority
WarningAction
WarningVariable
WhatIf
```

So what parameters are missing?

**Comment by xNiklasJern** [comment]
thanks again for you reply.
Yes that works, but I haven't gotten it to work with powershell ISE (thats the reason why I use the other suppliments)

I'm missing the "-IncludedRecipients", "-RecipientFilter" and the all of the custom attributes. But I just now noticed that these dont have Exchange Online on 'applies to' (my bad, sorry).
Does this mean you can't filter who to apply the Addresspolicy to if it is cloud only users?

Regards,

**Comment by chrisda** [comment]
Apparently, that's correct. The Get-ManagementRoleEntry command I ran earlier in the thread shows every possible parameter that's available for New-EmailAddressPolicy, regardless of whether you have the required role assigned or not.

Looking for the -IncludedRecipients and -RecipientFilter parameters on any cmldets in Exchange Online, they're only available for New/Set-GlobalAddressList, New/Set-AddressList, and New/Set-DynamicDistributionGroup
