### ISSUE TITLE
AllowedOOFType parameter lacking descriptions for the Type

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#1728]
This MSDN page shows the descriptions:
https://msdn.microsoft.com/en-us/library/dd207273(v=exchsrvcs.149).aspx

It seems like they should also be here on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59cfe39-9c00-1a50-be14-0d8e58754529
* Version Independent ID: c8c00bed-da63-654e-d44f-6c83d967821e
* Content: [Set-RemoteDomain (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/set-remotedomain?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Set-RemoteDomain.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Set-RemoteDomain.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeremyTBradshaw, OK. Done.

Thanks for the feedback.

**Comment by JeremyTBradshaw** [comment]
Thanks!
