### ISSUE TITLE
Got error when supplying PerUserZip as -ArchiveFormat:

### ISSUE THREAD

**Issue by skille** [MicrosoftDocs/office-docs-powershell#1732]
Cannot validate argument on parameter 'ArchiveFormat'. The argument "PerUserZip" does not belong to the set "SinglePst,PerUserPst,IndividualMessage,SingleFolderPst" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e154eb-3e1c-b4a5-418e-5be55b581255
* Version Independent ID: 00b93f90-663f-c277-c7de-09c184b4a322
* Content: [New-ComplianceSearchAction (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-compliancesearchaction?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@skille, we're investigating. We think that ArchiveFormat is for SharePoint/OneDrive, and ExchangeArchiveFormat is for Exchange.

We were able to confirm that in the Security & Compliance Center UI, exporting results from a search that includes SharePoint/OneDrive locations and ZIP compression results in PerUserZip in the ArchiveFormat property -- even if you've selected a PST export option for Exchange.

Stay tuned.

**Comment by chrisda** [comment]
@skille we figured it out/ It turns out the ArchiveFormat parameter isn't used anymore (but it's still available). Instead, use the SharePointArchiveFormat parameter for SharePoint and OneDrive export and compression options.

Thanks for the feedback.
