### ISSUE TITLE
Max length of output? Search-UnifiedAuditLog

### ISSUE THREAD

**Issue by rjacob60** [MicrosoftDocs/office-docs-powershell#1733]
Hi - Is there a maximum length of the Json string output from the Search-UnifiedAuditLog cmdlet ?
Looking at a recent output example in both Notepad and Notepad ++ it looks like lines are getting truncated at 3062 characters and so I'm having a few spots where the Json string isn't getting closed/completed.

**Comment by AndreaBarr** [comment]
@rjacob60 Thank you for this feedback

I want to make sure this gets answered and added to the docs. 

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@rjacob60 this limit is documented in the topic on searching the audit log in the O365 Security & Compliance Center: https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance#more-information-about-exporting-audit-log-search-results 

Coincidentally, the engineering team is looking into increasing this limit; we'll update the topic if/when this limit is changed.

**Comment by rjacob60** [comment]
Thanks - I think the problem is that the cmdlet is passing back an invalid Json string because of the truncation.  I would be OK with truncation if it was happening in a specific field(s) so that the Json string can always be valid Json.  Having to decide if the string is good/bad creates some challenges and in some case we just throw the entire record out from processing.

**Comment by yogkumgit** [comment]
@rjacob60   Thank you very much for your kind feedback. Considering your valuable feedback, we have logged this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

User Voice Link: https://office365.uservoice.com/forums/264636-general/suggestions/32392399-exceed-the-results-limit-when-using-search-unified

**Comment by rjacob60** [comment]
Hi @AndreaBarr  - why is this closed?  I think the part that is missing is that the truncation is causing the creation of an invalid json string.  100% OK to truncate values within the the json, but the end result should always be a valid json.  Maybe I'm missing something?  I'm 100% OK with truncation as long as the output is still valid.

**Comment by kenwith** [comment]
@rjacob60 - this repository is for the documentation and as the thread above pointed out the documentation already points to the correct location to describe this behavior. The product teams look at User Voice (link above) for issues and suggestions for the product itself. Hope that explains and thanks for taking the time to surface issues you find. Any documentation issues please open here so we can get addressed asap. Thanks again!

**Comment by rjacob60** [comment]
I just wanted to check in to make sure everyone understands my expectations, and to see if this is what may (or may not be...?) getting fixed.
1.  100% with truncation of the string that comes out of the cmdlet, I understand that there may be individual elements that could make this output indefinitely long.
2.  NOT OK with truncation of the JSON string because it makes the output invalid, and not a valid JSON object.  This is making it very difficult for us to us standard tools to deserialize the JSON output

**Comment by kenwith** [comment]
@rjacob60 - completely agree and I up-voted the user voice link above so product team can get that feedback. Anyone else reading this thread please up-vote on User Voice too (if you agree) so we can get traction. Another approach is if anyone has a specific example in your environment where the JSON is getting truncated then please open a service ticket in your tenant and support can escalate to product team. We can tackle on all fronts to get this surfaced.

**Comment by get-itips** [comment]
@rjacob60 up-voted!

**Comment by ChrisParrBIE** [comment]
https://office365.uservoice.com/forums/264636-general/suggestions/35050720-correct-3-060-character-limit-issues-in-unified-au This User Voice link seems more appropriate to the truncation issue.
