### ISSUE TITLE
Awful documentation of probes

### ISSUE THREAD

**Issue by JdeFalconr** [MicrosoftDocs/office-docs-powershell#1736]
The different probes here are not documented at all - what they do and how they work. As a result you have no idea (besides the name of the probe, which in itself is rather vague) what you're testing and how it tests. See https://social.technet.microsoft.com/Forums/office/en-US/c8321498-6470-43d0-ae38-8859ecbeb6aa/probes-for-testoutlookconnectivity?forum=Exch2016PS for detail on my complaint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4447fcc6-9add-90b4-227f-357ebaf3ae94
* Version Independent ID: 2b94ca7b-6651-de39-0f77-fcd6b37a2da5
* Content: [Test-OutlookConnectivity (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/test-outlookconnectivity?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Test-OutlookConnectivity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Test-OutlookConnectivity.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by kenwith** [comment]
@AndreaBarr - please create a backlog item for this one and we will get this on the backlog.

**Comment by AndreaBarr** [comment]
@kenwith The backlog item has been created

**Comment by chrisda** [comment]
@JdeFalconr, it appears that the syntax and some names have changed. I updated the topic with the probes that I 100% know will work. If you like, you can try these additional probes and report back here:

Possible replacements for the defunct OutlookRpcCtpProbe and OutlookMapiHttpCtpProbe values:

- Outlook.Protocol\OutlookRpcDeepTestProbe\OutlookMailboxCTPProbe

- OutlookMapiHttp.Protocol\OutlookMapiHttpDeepTestProbe\OutlookMailboxCTPProbe

New probes that look interesting:

- Outlook.Protocol\OutlookRpcDeepTestProbe\OutlookMailboxCTPProbe:

- OutlookMapiHttp.Protocol\OutlookMapiHttpDeepTestProbe\OutlookLogonToArchiveMapiHttp

**Comment by dariomws306** [comment]
Thank you @chrisda!!

**Comment by chrisda** [comment]
@JdeFalconr, I'm going to close this out now. Thanks.
