### ISSUE TITLE
New-SupervisoryReviewRule -Condidtion parameter does not require braces { } 

### ISSUE THREAD

**Issue by hanzhumsft** [MicrosoftDocs/office-docs-powershell#1739]
I'm a member of Office 365 Security and Compliance team. I work on supervision related feature.

The New-SupervisoryReviewRule doc page says the -Condidtion parameter needs braces { } around the whole filter. This is not correct. Braces are not required here. If there are braces, the rule probably will not work.

For example, 
-Condition "((((Direction:Inbound) OR (Direction:Outbound))) AND (((Reviewee:user@test.com))))"
is correct, but
-Condition "{(((Direction:Inbound) OR (Direction:Outbound))) AND (((Reviewee:user@test.com)))}"
is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab8fce83-3aa0-d912-9042-39fb3d8188e7
* Version Independent ID: 28ae7ff6-bbe0-831f-4ce6-f312532f2ca4
* Content: [New-SupervisoryReviewRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/new-supervisoryreviewrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance/New-SupervisoryReviewRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance/New-SupervisoryReviewRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hanzhumsft, thanks for the feedback. I updated the topic as you described.
