### ISSUE TITLE
Ambiguity around access/associate

### ISSUE THREAD

**Issue by pschaeflein** [MicrosoftDocs/office-docs-powershell#1740]
This page sometimes uses the word "access" and sometimes uses the word "associate." Which operation is affected by this cmdlet? 

I would expect that access means the ability to view/update the content of a site (subject to permission levels set in the site collection that is the hub. 

I would expect that associate means the ability to move a site collection into the hub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c406f02-6894-fda9-10f8-def836cd4270
* Version Independent ID: bb70a9a3-6a38-912c-4c5a-5d4063065941
* Content: [Grant-SPOHubSiteRights (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/grant-spohubsiterights?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Grant-SPOHubSiteRights.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Grant-SPOHubSiteRights.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@pschaeflein Thank you for this feedback

I agree this needs to be updated and clarified. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @pschaeflein , thank you for your feedback.

I am replacing "Grants rights to users or mail-enabled security groups to access the hub site" for "Grants rights to users or mail-enabled security groups to associate their site with a hub site".

**Comment by dariomws306** [comment]
PR:
https://github.com/MicrosoftDocs/office-docs-powershell/pull/2773

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @pschaeflein  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
