### ISSUE TITLE
UnScopedTopLevel side-effects

### ISSUE THREAD

**Issue by fdari** [MicrosoftDocs/office-docs-powershell#1741]
The UnScopedTopLevel switch results in a "precanned" and uneditable role. The parameter description does not indicate this, nor does the example where this switch is used. Please fix documentation or functionality? Also, I'd like to be able to do something with my freshly created empty role, even just to delete it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aad91a-004d-a2bc-660b-eab1f7f95c76
* Version Independent ID: d084f4fc-2742-9363-1c7d-ed3dbc84af8a
* Content: [New-ManagementRole (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/role-based-access-control/new-managementrole?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/role-based-access-control/New-ManagementRole.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/role-based-access-control/New-ManagementRole.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@fdari, I updated and standardized the descriptions for UnScopedTopLevel parameter in Add-ManagementRoleEntry, New-ManagementRole,New-ManagementRoleAssignment, Remove-ManagementRole, and Set-ManagementRole to clarify that unscoped top-level roles can only contain custom scripts or non-Exchange cmdlets, and to see [this topic](https://technet.microsoft.com/library/dd876886.aspx) for more information.

Thanks for the feedback.
