### ISSUE TITLE
AppSharingBitRateKb and VideoBitRateKb are applicable to Skype for Business Online

### ISSUE THREAD

**Issue by naminakao** [MicrosoftDocs/office-docs-powershell#175]
The parameters, AppSharingBitRateKb and VideoBitRateKb, can be set on SfB online.
Currently Description section says they are not applicable to SfB Online.

**Comment by kenwith** [comment]
Seems duplicate with issue #176 . Working to resolve that one. If this is not a duplicate please reopen.
