### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by ronaldmavarez** [MicrosoftDocs/office-docs-powershell#1750]
The template is not valid when running the import on my Dev environment, it may not be the same SharePoint version as my PROD environment.

Error:
Import-PnPTermGroupFromXml -Path C:\Users\Administrator\Desktop\TermStorePP.xml
Import-PnPTermGroupFromXml : The provided template is not valid!
At line:1 char:1

I exported the terms from my PROD environment using:
Export-PnPTermGroupToXml -Out C:\TermStorePP.xml

This is my xml file header:
&lt;pnp:TermGroups xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema"&gt;

Any ideas? I already tried changing the header to 2016/05 or 2018/05 and still not working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2234c93-be32-5af0-8f84-d7011588f3ac
* Version Independent ID: 470a21a4-8354-cff1-b59a-cd82742f47ba
* Content: [Import-PnPTermGroupFromXml (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/import-pnptermgroupfromxml?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Import-PnPTermGroupFromXml.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Import-PnPTermGroupFromXml.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@ronaldmavarez Thank you for this feedback

I want to make sure this script issue gets resolved for you. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
