### ISSUE TITLE
Make Set-SPOTenant -UserVoiceForFeedbackEnabled:$false have effect on all modern pages

### ISSUE THREAD

**Issue by KoenZomers** [MicrosoftDocs/office-docs-powershell#1752]
In issue https://github.com/MicrosoftDocs/office-docs-powershell/issues/508 it was being requested to fix an issue where using Set-SPOTenant -UserVoiceForFeedbackEnabled:$false would not remove the feedback link on modern pages. This issue has been closed now, however when applying this, it does only remove the feedback from the modern Site Pages. Not from any other modern page like the list views or the site contents. This makes its behavior inconsistent and confusing.

Please fix it so that Set-SPOTenant -UserVoiceForFeedbackEnabled:$false will have influence on ALL modern SharePoint Online pages.

**Comment by mrik23** [comment]
Yes please, make it so the settings is on all modern pages and views. If we could also remove the mobile app thing with the same flag or another.

**Comment by KoenZomers** [comment]
This has now been fixed, see: https://github.com/MicrosoftDocs/office-docs-powershell/issues/508#issuecomment-430152475
