### ISSUE TITLE
This will not remove an owner

### ISSUE THREAD

**Issue by lloydmills** [MicrosoftDocs/office-docs-powershell#1755]
From my experience with this cmdlet, it will not remove an owner when running the command as a global administrator.  You must first change the owners role to "member" using the Add-TeamUser cmdlet (ensuring that there is another Owner left on the team) and then you can use the Remove-TeamUser cmdlet to remove the user.  I think the document needs to be update to reflect this information.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8d16f25-be6f-06eb-2cd7-9e64eab124e0
* Version Independent ID: a8181f1a-e575-410a-d5a4-0214c427b92d
* Content: [Remove-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/remove-teamuser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Remove-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Remove-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@lloydmills Thank you for this feedback

I agree that this needs to be update. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by anhlqn** [comment]
We can remove the team owner directly by specifying the -Role parameter. For example:

Remove-TeamUser -GroupId 31f1ff6c-d48c-4f8a-b2e1-abca7fd399df -User dmx@example.com -Role Owner

**Comment by anhlqn** [comment]
Take it back, running the command with -Role Owner change the role from Owner to Member.

**Comment by get-itips** [comment]
Hi @lloydmills thanks for taking the time to submit feedback!

I reviewed the document and saw that it has a note that says "Note: last owner cannot be removed from the team." when you tested this cmdlet, the user you tried to remove was indeed the last owner?

Thanks.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @lloydmills  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by harp365** [comment]
I am still confused with this personally. So I can find all users that are members of teams using get-teamuser -role member but when I was running the remove-user, perhaps need to do an update I could only specify owner as role. Logic would dictate that you are saying even if the user is an owner remove them. So I though, OK I will omit this switch and it will basically just remove members but if they are an owner leave them in tact. However not specifying role has removed an owner. So I will try with member but reading the comments that will still not just remove where member? Why can it not track same logic as its get equivalent?

**Comment by harp365** [comment]
Going to see if a pipe into remove user after get-teamuser -role member suffices but this really needs clarifying. As an interim, not sure which is easier but a whatif would be nice as that way we could at least confirm what is going to happen as a result of executing a command rather than inadvertently removing an owner

**Comment by get-itips** [comment]
@harp365  please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/4465

**Comment by harp365** [comment]
Thanks but there is still no option to just remove only where member. Also I will test again but I am sure I exhibited removal of an owner. Like I say a what if would be good to be sure
