### ISSUE TITLE
Script is wrong

### ISSUE THREAD

**Issue by parlevjo2** [MicrosoftDocs/office-docs-powershell#1758]
RecipientTypeDetails is missing a dash in front of it. Should be:
$AllUsers = Get-Mailbox -ResultSize unlimited -RecipientTypeDetails UserMailbox

**Comment by AndreaBarr** [comment]
@parlevjo2 Thank you for this feedback

I will make sure this gets updated. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @parlevjo2 , thank your for you collaboration.

Are you talking about this article?
https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/get-mailboxjunkemailconfiguration?view=exchange-ps

If yes, it was fixed:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/1569

Thank you!
