### ISSUE TITLE
Script line gives error Specify a unique value.

### ISSUE THREAD

**Issue by parlevjo2** [MicrosoftDocs/office-docs-powershell#1759]
$AllUsers | foreach {Get-MailboxJunkEmailConfiguration -Identity $_.Identity} | etc
Identity          Enabled BlockedSendersAndDomains
--------          ------- ------------------------
...
Multiple mailbox users match identity "xxxxxxxx". Specify a unique value.

This script line is better, because now it can handle every mailbox. Also foreach with Capitals.
$AllUsers | ForEach {Get-MailboxJunkEmailConfiguration -Identity $_.Guid.ToString()}

**Comment by dariomws306** [comment]
Hi @parlevjo2 , thank you for your feedback.

I couldn't find the article you are talking about. Could you gently let me know that it is? Thank you!

**Comment by parlevjo2** [comment]
It was https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/get-mailboxjunkemailconfiguration?view=exchange-ps. It is already fixed.
Fix is: foreach {Get-MailboxJunkEmailConfiguration -Identity $_.UserPrincipalName}

**Comment by dariomws306** [comment]
Thank you!
