### ISSUE TITLE
no definitions available for object properties

### ISSUE THREAD

**Issue by MichaelMc64** [MicrosoftDocs/office-docs-powershell#1760]
The link to outputs gives information on the object model of properties, but there is no explanation of what that property represents. For example, I run Get-MailboxSearch and some searches show a ResultSizeEstimate and a ResultSizeCopied with the same value. Others show a ResultSizeEstimate of however many bytes the search returned, but a ResultSizeCopied value of zero. What does ResultSizeCopied represent? Copied to where? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dad7408-41e4-2065-8ed5-9ee0cb261ae7
* Version Independent ID: 90cc83a8-538c-74b4-6013-c09f83cf9c8f
* Content: [Get-MailboxSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/get-mailboxsearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/Get-MailboxSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/Get-MailboxSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws306** [comment]
Hi @MichaelMc64 , thank you for your collaboration.

Could you help me and elaborate further to understand this?

Get-MailboxSearch returns a MailboxSearchObject, it could be null, 1 object or more than 1. And here is more information about this type of object:
https://docs.microsoft.com/en-us/previous-versions/office/exchange-server-api/ff329175(v=exchg.150)

Thank you!

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @MichaelMc64 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
