### ISSUE TITLE
Requirement to open the correct Powershell ISE

### ISSUE THREAD

**Issue by jfrancis2** [MicrosoftDocs/office-docs-powershell#1784]
This article forgets to mention that if you don't open the (x86) version of Powershell ISE, the commands will not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b57b66-2364-0e9d-e627-5eeb77238675
* Version Independent ID: 78fd7932-06f9-37c7-8928-250b3884d89e
* Content: [Connect to Exchange servers using remote PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/connect-to-exchange-servers-using-remote-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@jfrancis2 Thank you for this feedback

I will make sure this gets updated. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @jfrancis2 , thank you for your comment and collaboration. 

You have to open Windows PowerShell (not x86) to connect to Exchange Online PowerShell. Not x86 neither Windows PowerShell ISE (Windows PowerShell Integrated Scripting Environment).

Let me know if I am not clear or if I can help you with something else.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @jfrancis2 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
