### ISSUE TITLE
When trying to run get-SPOUserOneDriveLocation receive error

### ISSUE THREAD

**Issue by Eno423** [MicrosoftDocs/office-docs-powershell#1785]
I receive an error that states I must have Multi-geo tenant. 

I dont recall seeing this as a req for this command

get-SPOUserOneDriveLocation : Error Code: -4,This tenant is not a Multi-Geo tenant. The operation you are trying to perform is only supported on 
Multi-Geo tenants.
At line:1 char:1
+ get-SPOUserOneDriveLocation -UserPrincipalName $user.UserPrincipalNam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-SPOUserOneDriveLocation], Exception
    + FullyQualifiedErrorId : Error Code: -4,This tenant is not a Multi-Geo tenant. The operation you are trying to perform is only supported on Mu 
   lti-Geo tenants.,Microsoft.Online.SharePoint.PowerShell.GetSPOUserPersonalSiteLocation

**Comment by AndreaBarr** [comment]
@Eno423 Thank you for this feedback

I want to make sure you get assistance with this error code promptly. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
