### ISSUE TITLE
Revoke-SPObjectSecurity needs to be moved to SharePoint Server docs

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/office-docs-powershell#1786]
This cmdlet needs to be moved to SharePoint Server. It does not apply to SPO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f61f7dc-fba8-36b9-7d90-c5caa479b918
* Version Independent ID: 05f541c7-015d-a526-8e59-4ca0d485c7e8
* Content: [Revoke-SPObjectSecurity (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/revoke-spobjectsecurity?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPObjectSecurity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPObjectSecurity.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@tseward Thank you for this feedback

I'll make sure to get this into the backlog. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
