### ISSUE TITLE
HiddenFromExchangeClientsEnabled Positional Parameter

### ISSUE THREAD

**Issue by GarrettRobinson** [MicrosoftDocs/office-docs-powershell#1787]
Set-UnifiedGroup TestGroup -HiddenFromExchangeClientsEnabled $true
Success

Set-UnifiedGroup TestGroup -HiddenFromExchangeClientsEnabled $false
A positional parameter cannot be found that accepts argument 'False'.

Set-UnifiedGroup TestGroup -HiddenFromExchangeClientsEnabled:$false
Works only when a colon is added

**Comment by chrisda** [comment]
@GarrettRobinson, apparently HiddenFromExchangeClientsEnabled is a switch parameter. I'm not sure when this happened (not sure if it was ever really Boolean as previously described).

So, as you've discovered, the 'enable' syntax is either `-HiddenFromExchangeClientsEnabled` or `-HiddenFromExchangeClientsEnabled:$true` (obscure, but it does work for switch parameters). The 'disable' syntax is `-HiddenFromExchangeClientsEnabled:$false`.

I've updated the topic accordingly. Thanks for the feedback
