### ISSUE TITLE
How can we use Remove-ActiveSyncDeviceClass in Exchange Online?

### ISSUE THREAD

**Issue by jfoe1** [MicrosoftDocs/office-docs-powershell#1791]
How can we use Remove-ActiveSyncDeviceClass in Exchange Online so that we can clean up the ActiveSync device class list like we can do in on premises?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 389563ba-829b-14ba-ca66-5f503c7559df
* Version Independent ID: 45e5a64c-3010-0bb2-0d56-ee1c8ac3ac17
* Content: [Remove-ActiveSyncDeviceClass (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/remove-activesyncdeviceclass?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/devices/Remove-ActiveSyncDeviceClass.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/Remove-ActiveSyncDeviceClass.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jfoe1, it appears that Remove-ActiveSyncDeviceClass isn't available in Exchange Online. I found [this blog post](https://thoughtsofanidlemind.com/2016/05/09/the-automatic-cleanup-of-old-exchange-activesync-device-partnerships/) that talks about old ActiveSync devices, and includes PowerShell code at the bottom to remove (or, if slightly modified, view) EAS partnerships based on the last time the device synched.
