### ISSUE TITLE
Get-OfflineAddressBook does not exist in Exchange Online

### ISSUE THREAD

**Issue by pstasik** [MicrosoftDocs/office-docs-powershell#1795]
Get-OfflineAddressBook does not exist in Exchange Online.  It is not an available cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b398c2-a057-0525-29ba-e75a0cdbb1d3
* Version Independent ID: 6098ea27-d6d3-c44e-2b1f-9d2755fc096d
* Content: [Get-OfflineAddressBook (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/email-addresses-and-address-books/get-offlineaddressbook?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/email-addresses-and-address-books/Get-OfflineAddressBook.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/email-addresses-and-address-books/Get-OfflineAddressBook.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@pstasik, from the topic:

In Exchange Online, this cmdlet is available only in the Address Lists role, and by default, the role isn't assigned to any role groups. To use this cmdlet, you need to add the Address Lists role to a role group (for example, to the Organization Management role group). For more information, see the "Add a role to a role group" section in Manage role groups (https://technet.microsoft.com/library/jj657480.aspx).
