### ISSUE TITLE
New-Team - Alias Parameter should have a more detailed description

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#1796]
The current description for the Alias parameter could be improved to give more details about usage and what this parameter is good for.

-Alias
An alias name without any spaces. Team Alias Characters Limit - 64. The value for alias has to be unique and will be used during the Office 365 Group creation as primarysmtpaddress for this team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@andikrueger - would you be willing to submit a Pull Request with the updates? :)  I can guide you on how to do it. You would get contributor credit. Otherwise @AndreaBarr can get this into our backlog so we can get it in a sprint plan. Either way, thanks for feedback and taking the time to make the docs better. Much appreciated!

**Comment by kenwith** [comment]
Also, just FYI the directions for submitting a Pull Request are in the README here: https://github.com/MicrosoftDocs/office-docs-powershell

**Comment by andikrueger** [comment]
@kenwith I will submit a PR.
