### ISSUE TITLE
Get-SPOExternalUser cmdlet reference needs updates.

### ISSUE THREAD

**Issue by kenwith** [MicrosoftDocs/office-docs-powershell#180]
The Get-SPOExternalUser cmdlet reference needs updates.

**Comment by kenwith** [comment]
Original comment that showed up on the docs.microsoft.com site is below. This GitHub repository is the source and articles are also surfaced on docs.microsoft.com One IMPORTANT note is that the docs.microsoft.com articles will be changing in the near future to use GitHub Issues. The link to the docs.microsoft.com article is: https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spoexternaluser?view=sharepoint-ps 

fredericklin Jan 4, 2018

Tested this with OneDrive for Business/My site.  There has been a change to how a guest user is represented in the object model and so this cmdlet is no longer returning accurate information.  If a guest user was invited with a link and code for access, this cmdlet does not return them.   You can find these users by running Get-SPOUser -site $urlOfSite and then filter by LoginName matching "urn:spo:guest#*".  Legacy guest users will still be "#ext#"

**Comment by nsshommo** [comment]
Tracking down the PM on this one. After finding PM we can get this updated.

**Comment by kenwith** [comment]
@TroyStarr - might know who we can contact.

**Comment by AndreaBarr** [comment]
@kenwith Thank you for this feedback

I am going too add this to the PowerShell Backlog so that we can keep track of the progress on this. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by DeanGross** [comment]
@AndreaBarr it has been over 2 months, can you please check on the status of this

**Comment by kenwith** [comment]
@DeanGross - the original issue was already closed and resolved. There are examples now in the cmdlet. Are you requesting an example for what fredericklin mentioned in the thread above? Or are you asking about something to be changed in the cmdlet itself?

**Comment by vladcatrinescu** [comment]
@kenwith Does the Get-SPOExternalUser now return users invited using Modern Sharing and accessing the site with a PIN instead of logging in witha Windows Account?  What version was this corrected in as I can't seem to be able to see the fix

**Comment by vladcatrinescu** [comment]
Here is an image with the latest SPO module from the PowerShell Gallery that shows how the Get-SpoExternalUser does not return all external users in a SC. 

![image](https://user-images.githubusercontent.com/16143190/50850266-5b7c7680-1347-11e9-84ab-a0156d235eab.png)

**Comment by kenwith** [comment]
@trent-green

**Comment by yogkumgit** [comment]
@kenwith  Thank you for reporting this feedback here. This list is focused on content issues and I want to make sure your immediate product issue does not get lost in this list. If you would please open a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team
