### ISSUE TITLE
API does not use file size nor file path length limits of Sharepoint online

### ISSUE THREAD

**Issue by Selmiltone** [MicrosoftDocs/office-docs-powershell#1830]
New-SPOMigrationPackage cmdlet
The cmdlet does still not work with files bigger than 2GB or files with UNC path length longer than 260 characters??? Although there were a few release since these limits have been increased in Sharepoint online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ee57d94-f380-db4c-ad3a-dfbac43b4508
* Version Independent ID: a63a9702-6edc-0eb6-2008-fe5daba686fc
* Content: [New-SPOMigrationPackage (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/new-spomigrationpackage?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/New-SPOMigrationPackage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/New-SPOMigrationPackage.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@Selmiltone Thank you for this feedback

I agree, if we have increased these limits then it should be able to handle the larger files and path links. I want to get this in front of the PowerShell team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@Selmiltone I don't know the timelines that the PowerShell team are working with so I don't know what is going to be in the next release.

**Comment by j0rt3g4** [comment]
Working on it. :)

**Comment by yogkumgit** [comment]
@j0rt3g4  Thank you very much for the contribution and updating the documentation with PR. @Selmiltone Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
