### ISSUE TITLE
-Identity seems to be not required

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#1831]
[Enter feedback here]
When testing the New-CsSimpleUrlConfiguration CMD let, it did not required the -identity. If I didn't applied that, the new simpleURL was applied to the "Global".

For me the only required is "SimpleURL" -parameter. But again, that is marked as optional.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9780eb0d-20d4-c03e-3383-44526e3f17be
* Version Independent ID: 84918dc2-4fe0-5fe9-833f-9f2eaa649091
* Content: [New-CsSimpleUrlConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cssimpleurlconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsSimpleUrlConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsSimpleUrlConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@Petri-X  Thank you for this feedback. 

We apricate you pointing out the -identity being not necessary and the one marked as optional as being necessary. I'll make sure this gets over to the PowerShell team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hi @Petri-X 

Thanks for taking the time to submit feedback.
I analyzed the information you gave us and I think that New-CsSimpleUrlConfiguration without -identity was accepted and applied to Global because it was the first time a Simple URL Configuration was made in your environment, so there was no Global configuration at that moment.

If you then try to use New-CsSimpleUrlConfiguration (without -identity) when there is a Global scope present, it will throw an error asking for it.

Could it be that the case in your environment?

If that is the case, we will proceed adding a Note to the documentation to clarify this.

We really appreciate your feedback.

**Comment by Petri-X** [comment]
Hi Get-iTips

Yes you are correct. Now when testing that again, it is actually requires the -identity now also when the Global has been defined.

Aslo need to say, that when now running the command:
**New-CsSimpleUrlConfiguration -Identity Site:SkypeSite1**
it goes smoothly. So in that sence -simpleURL is not required anymore.

But this really depends if you already have simpleURL configuration done or not.

**Comment by kenwith** [comment]
@get-itips - can you let us know if there is an associated Pull Request (PR) for this one? Really great work. @Petri-X - thanks for taking the time to report this and get this figured out. This is a great example of your collaborative efforts making the content better for the community!

**Comment by get-itips** [comment]
Created a PR to clarify this on the doc.
Thank you @kenwith @Petri-X

**Comment by kenwith** [comment]
awesome, thanks! would you mind pasting the link to the PR in here and GitHub will automatically cross reference. Or you can also paste the link to this issue in the PR and GitHub will mention in here automatically.

**Comment by get-itips** [comment]
That was what I did ;) it's referenced in the PR and was cross ref here.


---- On mié, 13 feb 2019 18:40:59 -0300 notifications@github.com wrote ----

awesome, thanks! would you mind pasting the link to the PR in here and GitHub will automatically cross reference. Or you can also paste the link to this issue in the PR and GitHub will mention in here automatically.

**Comment by kenwith** [comment]
oh I see it now! 👍

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Petri-X  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
