### ISSUE TITLE
Is it possible to export a list with no content?

### ISSUE THREAD

**Issue by alextopol** [MicrosoftDocs/office-docs-powershell#1832]

**Comment by AndreaBarr** [comment]
@alextopol Thank you for this feedback

My instincts are to say no we can't export a list with no content but I'm not sure that this is the correct answer. Let me get this inquiry in front of the PowerShell team for confirmation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@chrisda Is there a resolution for this issue?

**Comment by Techwriter40** [comment]
to my knowledge this can not be done.
