### ISSUE TITLE
It would be helpful to know what permissions are required to run these commands.

### ISSUE THREAD

**Issue by ellenkong** [MicrosoftDocs/office-docs-powershell#1860]
I'm a global admin and SPO admin, but I'm getting "Access denied.  You do not have permission to perform this action or access this resource." when simply doing a Get-SPOTenantCdnEnabled -CdnType Private.  + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerUnauthorizedAccessException,Microsoft.Online.SharePoin
   t.PowerShell.GetTenantCdnEnabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1cbddc-26b2-84bd-cbce-7d47b34d7da2
* Version Independent ID: 19bba570-f209-9d5d-f9cc-50413b46071f
* Content: [Get-SPOTenantCdnEnabled (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantcdnenabled?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantCdnEnabled.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantCdnEnabled.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@ellenkong Thank you for this feedback

I am not sure what permissions are needed. Let me get this over to the PowerShell team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by VesaJuvonen** [comment]
This cmdlet requires tenant administrative permissions. Added that now also on the documentation.
