### ISSUE TITLE
Suggest using UserPrincipalName

### ISSUE THREAD

**Issue by w00dbury** [MicrosoftDocs/office-docs-powershell#1861]
In the for-each loop on example 2 you may want to use UserPrincipalName as the identity.

Replace:
Get-MailboxJunkEmailConfiguration -Identity $_.Identity

With:
Get-MailboxJunkEmailConfiguration -Identity $_.UserPrincipalName

It's possible to have duplicate Identity values but not UserPrincipalName values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64eec30c-8fee-b6ee-de2b-dd2cb1b339c0
* Version Independent ID: 678ecad3-b2e1-ceb5-d02f-9807b6a2dedc
* Content: [Get-MailboxJunkEmailConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/get-mailboxjunkemailconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Get-MailboxJunkEmailConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Get-MailboxJunkEmailConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@w00dbury OK. Done.

Thanks for the feedback.
