### ISSUE TITLE
New-ExoPSSession with delegated partner rights

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/office-docs-powershell#1868]
How to use New-ExoPSSession and specify delegated tenant for which to connect?

For New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri  ...., is working
Since: https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-exchange-online-tenants-with-remote-windows-powershell-for-delegated

However, when using New-ExoPSSession , value from -ConnectionUri , is causing the Internal server error, on Exchange Online service side.
Reference: https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps

Please fix this, since MS Partners can not use their accounts (which are secure with MFA) and have delegated admin access to customers Exchange Online tenants...

**Comment by hkusulja** [comment]
I am aware of trusted Ip option, however this is not allowed within us and is not enough good solution.

How can, MS partner, be secure (have MFA) and manage customers (delegated admin) ..., this is half of the product, and I do not see any progress on this for months/years..., Also I can not find uservoice where to submit that "idea" as a feature, if so.

Also, documentation should say, that delectation is not supported.

I think it will be easier to fix that ConnectionUri is working within New-ExoPSSession ....

**Comment by chrisda** [comment]
@hkusulja believe it or not, your best bet is to file a support case with Microsoft. That will get your issue directly in front of the people who can make a difference.

**Comment by hkusulja** [comment]
@chrisda  - they just open documentation from the same link, and say "sorry, it is not supported".
Can you say it also more in clear way in documentation?

**Comment by chrisda** [comment]
@hkusulja, don't know the details as to _why_ it doesn't work, but I added information in both MFA connection topics and the DAP connection topic to say that the Exchange Online PowerShell Module and MFA don't work in DAP environments.

Thanks for the feedback.
