### ISSUE TITLE
How To Set Site Group Owner

### ISSUE THREAD

**Issue by Jonathanval** [MicrosoftDocs/office-docs-powershell#1869]
Is really easy to set a new user owner through PowerShell however how you can archive the same assigning a group as owner??. 

Always it says "The specified user "Group Name" could not be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 901772a6-b15b-d19e-c799-f1fad627c1f8
* Version Independent ID: af5eca43-afb6-2cdb-8cd1-48b722cc5671
* Content: [Set-SPOSiteGroup (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spositegroup?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteGroup.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@Jonathanval Thank you for this feedback

I want to make sure you get the appropriate help with this Group Name error you keep seeing. I want to get you over to Support. They have more resources to help dig in and figure out what is going on. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
