### ISSUE TITLE
Connect-SPOService doesn't work with credentials and legacy auth disabled

### ISSUE THREAD

**Issue by rayterrill** [MicrosoftDocs/office-docs-powershell#1875]
It's a best practice on the identity side to disable legacy auth, but the Connect-SPOService cmdlet doesn't work with a credential parameter (for scripted operations) - it appears to fallback to legacy auth. It looks like the native oauth flow only works with interactive login. :(

It looks like there's a reg hack to force oauth: https://blogs.technet.microsoft.com/jasonross/2017/10/04/sharepoint-online-management-shell-forcing-modern-authentication/.

Sure would be nice if we could pass a parameter to use oauth, or maybe default to oauth going forward, something.

**Comment by AndreaBarr** [comment]
@rayterrill  Thank you for this feedback

I'll get this over to the PowerShell team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by yogkumgit** [comment]
@rayterrill   Thank you very much for your kind feedback. Considering your valuable feedback, we have logged this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

User Voice Link: https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/9613035-powershell-sharepoint-multi-factor-authenticatio
