### ISSUE TITLE
Two parameters -ExcludedCodecs and –CodecPriority are not right now supported/implemented.

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/office-docs-powershell#1877]
Hi Team,
Two parameters -ExcludedCodecs and –CodecPriority are not right now supported/implemented. Please help to update the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63a495ab-16d4-4f7f-d17e-5b1a9779247f
* Version Independent ID: cf4bfc0e-fd8d-d5ca-5432-798af72a8885
* Content: [Set-CSOnlinePSTNGateway (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinepstngateway?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CSOnlinePSTNGateway.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CSOnlinePSTNGateway.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@XixiHuang333 Thank you for this feedback. 

I will get this information about these parameters over to the PowerShell team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by XixiHuang333** [comment]
any update on this request?
Customer check the Direct Routing configuration and see that the Codecs options are still missing, yet the Microsoft documentation still refers to Codec Priority (-ExcludedCodecs and –CodecPriority).

**Comment by AndreaBarr** [comment]
@get-itips Could you please investigate this?

**Comment by get-itips** [comment]
Yes. Sure. I will look into this.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @XixiHuang333 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by bertrandsophie** [comment]
Page New-CsOnlinePSTNGateway has not been updated...
