### ISSUE TITLE
bad notes at the top

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/office-docs-powershell#1883]
this article says "IMPORTANT: TeamsUpgradePolicy has replaced TeamsInteropPolicy" yet the article on the other cmdlet has the exact opposite message at the top.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b2b7946-2b7d-a741-18d0-fbbfa16b535c
* Version Independent ID: b3da946f-fd0d-d324-534d-6bd71dc76e4b
* Content: [Get-CsTeamsUpgradePolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csteamsupgradepolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Get-CsTeamsUpgradePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTeamsUpgradePolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@Mike-Crowley Thank you for this feedback 

I'll get this information over to the PowerShell team so we can get these to articles investigated. I'm going to also make this comment on the other issue that you have as well. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kenwith** [comment]
@Mike-Crowley - I am not seeing this one.. they both say the same thing the way I read it. The TeamsUpgradePolicy has definitely replaced the TeamsInteropPolicy. Where are you seeing the opposite? We will need to get it fixed asap. Thanks.

**Comment by dariomws306** [comment]
PR:
https://github.com/MicrosoftDocs/office-docs-powershell/pull/2767
