### ISSUE TITLE
bad notes at the top (related to #1883)

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/office-docs-powershell#1884]
this article says "IMPORTANT: TeamsInteropPolicy has been replaced by TeamsUpgradePolicy." yet the article on the other cmdlet has the exact opposite message at the top.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b37f6ef0-492a-abe8-77b9-c8ba9f4d52fb
* Version Independent ID: a2455db6-096b-aca1-3dc1-031fec4f3bb2
* Content: [Get-CsTeamsInteropPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csteamsinteroppolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Get-CsTeamsInteropPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTeamsInteropPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by islubin** [comment]
One says that TeamsInteropPolicy has **_been_** replaced by TeamsUpgradePolicy, the other says that TeamsUpgradePolicy has replaced TeamsInteropPolicy.  The been is the key message here.

**Comment by Mike-Crowley** [comment]
aha ok, you're right. This is distracting wording however. I would expect to see the note at the top of the legacy article and nothing to distract the reader if they've landed on the current article/method.

**Comment by AndreaBarr** [comment]
@Mike-Crowley Thank you for this feedback 

I'll get this information over to the PowerShell team so we can get these to articles investigated. I'm going to also make this comment on the other issue that you have as well. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
PR:
https://github.com/MicrosoftDocs/office-docs-powershell/pull/2767
