### ISSUE TITLE
Default Policy Names

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/office-docs-powershell#1886]
Ok, this was so annoying I just had to translate all the weird policy names for you all :)
Names have a prefix BposS, ex: BposSVoipDisabledNoRec
Configuration legend: N = None, A = Audio Only, V = Audio and Video, H = Audio and Video HD, R = Record conversations and meetings, C = For compliance, turn off non-archive features
VoipDisabledNoRec: N
AllModalityNoRecNoVideo: A
AllModalityNoRecMinVideoBW: V
AllModalityNoRec: H
VoipDisabled: N, R
AllModalityNoVideo: A, R
AllModalityMinVideoBW: V, R
AllModality: H, R
IMPOnlyNoRec: N, C
DataProtectionNoVideo: A, C
DataProtectionMinVideoBW: V, C
DataProtection: H, C
IMPOnly: N, R, C
AllModalityNoFTNoVideo: A, R, C
AllModalityNoFTMinVideoBW: V, R, C
AllModalityNoFT: H, R, C

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ceb390f-bd1a-a107-48e7-5561451877a9
* Version Independent ID: 32d13d63-161c-40f9-57ad-5a33dfd4cc97
* Content: [Grant-CsConferencingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csconferencingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsConferencingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsConferencingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@toxarisswe Thank you for this feedback

We apricate you translating all the policy names. I'll get this over to the PowerShell team so they can handle this appropriately. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @toxarisswe , thank you for your comment. Are you suggesting that all those information should be in the article?

If you run next command you can check all the policies and their settings in Excel:
Get-CsConferencingPolicy | Export-Csv out.csv

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @toxarisswe  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
