### ISSUE TITLE
[Enter feedback here]$h = (Get-Date).AddHours(-1) $logs = dir 'C:\' -Recurse '*.log' | Sort-Object CreationTime # Find the last 5 log files created in the past hour. $logs.Where({$_.CreationTime -gt $h}, 'Last', 5)   --- #### Document Details  ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*  * ID: cbe6e195-f640-0f1b-dae0-1d5ed62da207 * Version Independent ID: fa3de13d-0fab-7a99-3346-1f7764686781 * Content: [Exchange cmdlet syntax](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/exchange-cmdlet-syntax?view=exchange-ps) * Content Source: [exchange/docs-conceptual/exchange-server/exchange-cmdlet-syntax.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/exchange-cmdlet-syntax.md) * Service: **exchange-online** * GitHub Login: @chrisda * Microsoft Alias: **chrisda**

### ISSUE THREAD

**Issue by SOFIE96** [MicrosoftDocs/office-docs-powershell#1889]
[Enter feedback here]$h = (Get-Date).AddHours(-1)
$logs = dir 'C:\' -Recurse '*.log' | Sort-Object CreationTime
# Find the last 5 log files created in the past hour.
$logs.Where({$_.CreationTime -gt $h}, 'Last', 5)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbe6e195-f640-0f1b-dae0-1d5ed62da207
* Version Independent ID: fa3de13d-0fab-7a99-3346-1f7764686781
* Content: [Exchange cmdlet syntax](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/exchange-cmdlet-syntax?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/exchange-cmdlet-syntax.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/exchange-cmdlet-syntax.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SOFIE96, by default, Exchange Server log files are stored in %EXCHANGEINSTALLPATH% (C:\Program Files\Microsoft\Exchange Server\V15\); for example, the Logging folder, the TransportRoles\Logs folder, etc. So you can save a bunch of time by starting in the %EXCHANGEINSTALLPATH% folder.

For your commands:

```
$h = (Get-Date).AddHours(-1)
$logs = dir 'C:' -Recurse '*.log' | Sort-Object CreationTime
$logs.Where({$_.CreationTime -gt $h}, 'Last', 5)
```

That middle line is key. As it's written, you need to be in the folder/path that you want to search. If you want to search the whole C: drive, run `cd c:\` first or use the value 'C:\' in the command. For example:

```
$logs = dir 'C:\' -Recurse '*.log' | Sort-Object CreationTime
```

If you want to search just the Exchange Server folder, you can use the %EXCHANGEINSTALLPATH% environment variable like this:

```
$logs = dir $env:ExchangeInstallPath -Recurse '*.log' | Sort-Object CreationTime
```

I tested using that last command, and it worked.
