### ISSUE TITLE
Different Get-SpoSite results

### ISSUE THREAD

**Issue by YohannT** [MicrosoftDocs/office-docs-powershell#1900]
Hello,

I noticed a difference between the result obtained by two Get-SPOSite commands for the same user on the same tenant.
Get-SPOSite -IncludePersonalSite $true -Limit All -Filter "Url -like 'my_URL'" | select Title,Url,ConditionalAccessPolicy
Get-SPOSite -Identity "my_URL" | select Title,Url,ConditionalAccessPolicy

The difference is on the **ConditionalAccessPolicy** property. It is set to **AllowFullAccess** with the first command and **BlockAccess** with the second command.
The right property is given by the second command. But to check the status of this property on all OneDrive with the second command, it is extremely long.
Do I have an incorrect setting? Is it a bug in the powershell module?

Microsoft.Online.Sharepoint.Powershell module version 16.0.8029.0
Thanks

**Comment by AndreaBarr** [comment]
@YohannT Thank you for this feedback

I am not sure why you are getting two different answers with these commands. I want to get you over to support. They have a lot more resources than we do here to dig in and see what is going on. If it is a potential bug then the will be able to document it and take it from there to get a resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
