### ISSUE TITLE
No examples?

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/office-docs-powershell#1902]
This article needs examples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6316f255-a35c-8a88-2459-bdf8dd0a3787
* Version Independent ID: fdbaf4a2-51b1-7e63-4b15-48327f1c8915
* Content: [New-SPWebApplication (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spwebapplication?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPWebApplication.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPWebApplication.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
There is one example. Do you want additional examples, and if so, what scenarios do you need?

**Comment by SharePointBlackBelt** [comment]
Something like what I would see in PoweShell using Get-help with -examples switch.

Vince
________________________________

**Comment by tseward** [comment]
@SharePointBlackBelt Can you elaborate? `Get-Help` example format is a bit different than the normal help.
