### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sharon1188** [MicrosoftDocs/office-docs-powershell#1908]
There is an extra apostrophe before -hubsite in 

> Add-SPOHubSiteAssociation https://contoso.sharepoint.com/sites/Research `
-HubSite https://contoso.sharepoint.com/sites/Marketing

that doesn't need to be there.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6338721-5bad-7526-8328-428bc420a0e9
* Version Independent ID: b69c571d-ab9f-80f1-eed1-9008e6cd5b76
* Content: [Add-SPOHubSiteAssociation](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spohubsiteassociation?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubSiteAssociation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubSiteAssociation.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@sharon1188 Thank you for this feedback

I have created a pull request to remove those apostrophes that weren't needed. It now just needs to be reviewed and merged to the live document. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by VesaJuvonen** [comment]
Fixed.
