### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ddexter26** [MicrosoftDocs/office-docs-powershell#1910]
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spodeletedsite?view=sharepoint-ps#related-links
First two Hyper links are broken, circles back to same page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13d75cb6-7da1-0173-6721-6137c258a317
* Version Independent ID: e87ab201-c6de-e1cf-04b4-0617f11deb7e
* Content: [Get-SPODeletedSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spodeletedsite?view=sharepoint-ps#related-links)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPODeletedSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPODeletedSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@ddexter26 Thank you for this feedback

We appricate you pointing out these broken links. I'll get this over to the PowerShell team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by VesaJuvonen** [comment]
Fixed to the docs - issue existed in multiple docs and they have all been fixed.
