### ISSUE TITLE
New-Team cmdlets getting Failed with Bad request

### ISSUE THREAD

**Issue by vinit14360** [MicrosoftDocs/office-docs-powershell#1915]
From Today morning we are experiencing the Teams Creation using Power shell cmdlets getting failed.

cmdlet code :

New-Team -DisplayName Test

Reached catch method Error occurred while executing 
Code: Request_BadRequest
Message: A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value.
InnerError:
  RequestId: 3865c9bc-f1d3-4653-be9e-a44bb1d5690c
  DateTimeStamp: 2018-10-19T09:42:20
HttpStatusCode: Request_BadRequest

but the same Team using user interface of Team we are able to create. could you please look into this. We have Automated Teams Creation running in PROD Environment using the Powershell cmdlet.

**Comment by AndreaBarr** [comment]
@vinit14360 Thank you for this feedback

I am not sure why the code failed. Let me get this over to the PowerShell team for investigation.  If you need expidited help please contact Support. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tchinnin** [comment]
Hi, Got the exact same error message when trying to create a team using Powershell cmdlet New-Team.
I'm able to Connect-MicrosoftTeams and Get-Team but the New-Team failed
![image](https://user-images.githubusercontent.com/46782173/51316864-37f7b100-1a56-11e9-8508-e6d14bf487cf.png)
Any update ?

**Comment by AndreaBarr** [comment]
@dariomws306 Can you investigate this?

**Comment by tchinnin** [comment]
It's fine, my module wasn't up to date with 0.9.6 it works fine !
Thanks

**Comment by dariomws306** [comment]
Hi @vinit14360 , what version are you using? Thanks!

**Comment by vinit14360** [comment]
HI @dariomws306 @AndreaBarr ,

I did contacted Microsoft support that day and they have suggested me to upgrade the PowerShell version since they have modified some of code in new Version. so i updated the Team Module and it worked fine. we can close this thread

**Comment by dariomws306** [comment]
@vinit14360 , ok, thank you, good to know it's fixed. We will close it.

**Comment by jerryyasir** [comment]
I am getting this error only when authenticating to Azure AD Application with Certificate Authentication.  

New-Team : Error occurred while executing 
Code: Request_ResourceNotFound
Message: Resource '7dc36d15-7ddd-47d3-b11b-fa56eb4d25b0' does not exist or one of its queried reference-property objects are not present.
InnerError:
  RequestId: 46c506b8-c93d-48b8-9470-f894c6d5851f
  DateTimeStamp: 2019-01-18T19:31:54
HttpStatusCode: Request_ResourceNotFound
At C:\Users\jyasir\OneDrive - DXC Production\PowerShell Scripts\Create-TeambyCSV.ps1:89 char:12
+ ...     $Team = New-Team -Alias $team.MailNickName -displayname $team.Tea ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-Team], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.NewTeam
###########################################
I can run Get Teams after certificate auth but not New-Team
###########################################
Authentication with basic cloud based identity does not produce this error.


$ApplicationID = "5dbebc00-9595-433c-XXX"
$CertificateThumbprint = "E476495E402XXX"
$tenantId = 'e4e9d3e7-5b3b-4203-ab84-XXX'

Connect-MicrosoftTeams -ApplicationId $ApplicationID -CertificateThumbprint $CertificateThumbprint -TenantId $tenantId -LogFilePath "C:\temp\TeamsError.txt"
$Team = New-Team -Alias $team.MailNickName -displayname $team.TeamName -AccessType $team.TeamType -Description $team.Description -Classification $team.Classification -Verbose

Log
[New-Team-ErrorWithCertificatevsBasicCredentials.txt](https://github.com/MicrosoftDocs/office-docs-powershell/files/2774324/New-Team-ErrorWithCertificatevsBasicCredentials.txt)

**Comment by HaloX69** [comment]
I am using Connect-MicrosoftTeams with an app reg certificate to authenticate successfully, but experiencing the exact same exception, Request_ResourceNotFound, when I run New-Team.

**Comment by kenwith** [comment]
@HaloX69 - this list is for the docs and I want to make sure your issue doesn't get lost, if you would please open a support service ticket in your tenant. You can find it under Support in the left hand nav and an option to open a new service request. The support engineers will be able to identify if perhaps there is a bug or something going on and they can escalate immediately to product team too. If there is something you find that you think should be in the docs please let me know or if you want to contribute your knowledge I can guide you to submit a Pull Request so you show as a contributor ( https://github.com/MicrosoftDocs/office-docs-powershell/graphs/contributors ).. either way thank you for sharing your knowledge here.
