### ISSUE TITLE
Upgrade silently fails if you have a groups email address book policy

### ISSUE THREAD

**Issue by dsolodow** [MicrosoftDocs/office-docs-powershell#1944]
Took quite some time running this down with a support case, but if you have an email address book policy that includes GroupMailbox (created with -IncludeUnifiedGroupRecipients), your groups will fail to upgrade without throwing any errors. 
It is necessary to remove the addressBookPolicy in order for the upgrade to succeed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e592c000-368e-f430-75ca-51d4c4b0c831
* Version Independent ID: 7e16242b-dcdf-1c57-83e2-b67c4118bbc7
* Content: [Upgrade-DistributionGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/upgrade-distributiongroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Upgrade-DistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Upgrade-DistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dsolodow, thanks for the information. I updated the topic.
