### ISSUE TITLE
SfBWithTeamsCollabWithNotify does not work at all

### ISSUE THREAD

**Issue by TeamParcee** [MicrosoftDocs/office-docs-powershell#1946]
After running the following command, I get no errors, but Teams and Skype clients do not change.

Grant-CsTeamsUpgradePolicy -PolicyName SfBWithTeamsCollab -Identity xxxxx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0dd44c-bfc9-5f82-68c4-7b469129e8a5
* Version Independent ID: ea015ee3-54e2-e402-d533-c8a9a15557e8
* Content: [Grant-CsTeamsUpgradePolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsupgradepolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@TeamParcee Thank you for this feedback

I want to make sure this command issue gets it's appropriate attention. I want to get you over to Support who has more resources to dig in and find a resolution for this issue. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
