### ISSUE TITLE
Online Version Link

### ISSUE THREAD

**Issue by davidguest44** [MicrosoftDocs/office-docs-powershell#1953]
The link does not point to a documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8949c8-410d-2c67-6282-b2ec5a5b30ae
* Version Independent ID: 1946599a-0475-f36a-254e-7826dcf719aa
* Content: [Get-MailboxLocation (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailboxlocation?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-MailboxLocation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-MailboxLocation.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@davidguest44 it looks like the Get-MailboxLocation topic was never published on TechNet before the migration to GitHub/docs.microsoft.com, so the redirect doesn't work. I changed the link to point directly to the topic on docs.microsoft.com.

Thanks for the feedback.
