### ISSUE TITLE
Missing "-SMTPClientAuthenticationDisabled"

### ISSUE THREAD

**Issue by dcnoren** [MicrosoftDocs/office-docs-powershell#1954]
I do not see "-SMTPClientAuthenticationDisabled" shown in this list, where it is indeed an option on the cmdlet. When added, please also document the relationship with the same "-SMTPClientAuthenticationDisabled" command for the get- / set-transportconfig. For example, if set to "true" on transportconfig and blank on a casmailbox, what is the result? If "true" on transportconfig and "false" on casmailbox, what is the result? Etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a094fce-b575-e92b-1993-ef599808cb96
* Version Independent ID: a87d5b1f-f2ab-4f52-7edd-96abdf4c59c9
* Content: [Get-CASMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/get-casmailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Get-CASMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Get-CASMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dcnoren , I added the parameter to Set-CASMailbox, including the description of how to disable for the org, but enable for a few mailboxes.

Thanks for the feedback.

**Comment by dcnoren** [comment]
Thanks. I see it on set-casmailbox now, but not on get-casmailbox. Just FYI. Of course set is more important.

**Comment by chrisda** [comment]
@dcnoren I'm not seeing SMTPClientAuthenticationDisabled as a _parameter_ on Get-CASMailbox. I'm sure it appears as a _property_ in the output of `Get-CASMailbox -Identity <user> | Format-List`, but we typically don't go into depth about properties of Get- cmdlets unless the output of the cmdlet is paramount (reporting cmdlets).
