### ISSUE TITLE
Search-UnifiedAuditLog SharePoint Record Type Does Not Work

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#1955]
### Issue Description
When you run `Search-UnifiedAuditLog` with SharePoint specified as RecordType, it will return you events of other record types like ExchangeItems and Microsoft Teams.
### Steps to reproduce

1. Open PowerShell
2. Connect to Exchange Online
3. Run  the following command

`$test = Search-UnifiedAuditLog -StartDate ( Get-Date ).AddDays(-3)  -EndDate ( Get-Date ).AddDays(-2) -RecordType SharePoint -ResultSize 5000  ; $test | group RecordType
`

4. The following result is expected:

![image](https://user-images.githubusercontent.com/5260172/47365675-b9080c00-d6e4-11e8-8ca9-7711dfc8b276.png)

### Expected Behavior
When you run When you run `Search-UnifiedAuditLog` with SharePoint specified as RecordType it should return only those events for which RecordType is "SharePoint". In this case it should not return any other records

**Comment by AndreaBarr** [comment]
@YuriySamorodov Thank you for this feedback

I will get this search issue over to the PowerShell team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@YuriySamorodov, I ran these two separate commands in Exchange Online PowerShell:

```
$test = Search-UnifiedAuditLog -StartDate (Get-Date).AddDays(-3) -EndDate (Get-Date).AddDays(-2) -RecordType SharePoint
$test | group RecordType
```

And I got the result:

```
Count  Word
-----  ----
    5  SharePoint
```

By definition, the value $test can only contain SharePoint record types or be empty if there aren't any of them; I'm not sure why it would display other types, too.

**Comment by YuriySamorodov** [comment]
@chrisda Thanks for looking into this Chris. The problem must have been somewhere between a keyboard and a chair.

Sorry for the false alarm. 
May I please ask you to close this case?
