### ISSUE TITLE
No longer limited to E5/ATP

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/office-docs-powershell#1956]
according to announcement MC150492 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2878f068-28f3-25d2-50e5-1356fd0b412d
* Version Independent ID: 0f79c2ee-4878-3db8-5a42-ed2dd36b2f87
* Content: [Get-PhishFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/get-phishfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Get-PhishFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Get-PhishFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@Mike-Crowley Thank you for this feedback

I will get this updated information over to the PowerShell team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@Mike-Crowley I removed the 'requires E5/ATP' text from Get-PhishFilterPolicy and Set-PhishFilterPolicy.
