### ISSUE TITLE
Typo in NotifyOutboundSpamRecipients

### ISSUE THREAD

**Issue by sbalogunpcgus** [MicrosoftDocs/office-docs-powershell#1958]
Under the description of parameter -NotifyOutboundSpamRecipients "The specified recipients receive notifications when the value of the NotifyOutboundSpamRecipients parameter is $true." should read "The specified recipients receive notifications when the value of the NotifyOutboundSpam parameter is $true"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465aff8b-94d1-258b-0558-a35f2261fc0b
* Version Independent ID: 3b7917f1-4d63-e881-5653-4fc4ac84038a
* Content: [Set-HostedOutboundSpamFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/set-hostedoutboundspamfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedOutboundSpamFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedOutboundSpamFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@sbalogunpcgus I fixed this.
