### ISSUE TITLE
Get-SPOUserOneDriveLocation missing synopsis and description

### ISSUE THREAD

**Issue by VesaJuvonen** [MicrosoftDocs/office-docs-powershell#197]
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Get-SPOUserOneDriveLocation?view=sharepoint-ps is missing synopsis.

**Comment by get-itips** [comment]
Hi ! Thanks for your comments, we really appreciate them.
Synopsis and Description has been added after you opened this issue. Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @VesaJuvonen  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
