### ISSUE TITLE
use -match instead of -eq

### ISSUE THREAD

**Issue by ServerCare** [MicrosoftDocs/office-docs-powershell#1971]
Get-MailboxStatistics -Database db5 | where {$_.DisconnectReason -match "SoftDeleted"}

This work also when using remoting (-eq doesn't)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07942b55-03ff-2bf8-fa73-1427cdc49681
* Version Independent ID: 0464c6e0-ebe1-ab7c-1b93-1db1b2846de8
* Content: [Remove-StoreMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailbox-databases-and-servers/remove-storemailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailbox-databases-and-servers/Remove-StoreMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailbox-databases-and-servers/Remove-StoreMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@ServerCare Thank you for this feedback

 We apricate you pointing out this issue with the syntax. I will get this over to the PowerShell team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@ServerCare I updated the example as you described.

Thanks for the feedback
