### ISSUE TITLE
Get-Team update (0.9.5) doesn't return correct Teams

### ISSUE THREAD

**Issue by CloudDesignBox** [MicrosoftDocs/office-docs-powershell#1974]
In the new release (0.9.5), we have noticed that Get-Team returns teams that a user is not a member or owner of. 

I assumed this might be because the command now runs as an administrator showing all Teams. However, random teams are still missing from the list (even if we are a member or owner of those Teams).

Downgrading to version 0.9.3 fixes the issue.

**Comment by CloudDesignBox** [comment]
@kenwith is this anything you can advise on?

**Comment by AndreaBarr** [comment]
@CloudDesignBox  Thank you for this feedback

We apricate you pointing out this potential bug. Let me get this information over to the PowerShell team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by CloudDesignBox** [comment]
@AndreaBarr Thank you!

**Comment by kenwith** [comment]
@islubin - FYI on potential bug in latest module.

@CloudDesignBox - If you wouldn't mind please open a service ticket in your tenant. They can group these together with other service tickets so that @islubin team can get this figured out.

@AndreaBarr - do you have that link on how to open a service ticket handy?

**Comment by CloudDesignBox** [comment]
@kenwith I've added this as a service ticket in the tenant. We have noticed this in a couple of our customer tenancies so far but i think it is related to the PowerShell module not the tenant. Happy to provide further information via email if required.

**Comment by islubin** [comment]
@CloudDesignBox  I will wait for the support ticket to come through! The ability to get all teams in an organization didn't exist in the 0.9.3 release, so when you say that it works in 0.9.3 what functionality are you referring to?

**Comment by AndreaBarr** [comment]
@CloudDesignBox and @kenwith Here is the link I have for opening a ticket. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by CloudDesignBox** [comment]
@AndreaBarr Thanks I logged this yesterday but not had a response yet.

**Comment by AndreaBarr** [comment]
@CloudDesignBox  Okay great. I am going to close this issue for now. Please let us know what the resolution is when you get it.

**Comment by CloudDesignBox** [comment]
This has now been replicated to MS support. I'll update you when i know more....

**Comment by CloudDesignBox** [comment]
Latest update from MS Support:

It seems to be an issue with lot of tenants as I am also able to replicate this on my end with the same behavior.
We have raised this with the concerned teams through internal ticket and waiting to hear back from them.
I will update you soon on the same.

**Comment by AndreaBarr** [comment]
It looks like this issue has been resolved. I am closing this issue at this time. Please re-open this issue if it is not resolved.

**Comment by CloudDesignBox** [comment]
This has not been resolved and is now happening in version 1.9.6. I'm still in talks with Microsoft to resolve this.

**Comment by dariomws306** [comment]
Hi @CloudDesignBox , thank you for your time and feedback on this.

Do you have an update from support? Thanks!

**Comment by CloudDesignBox** [comment]
@dariomws306 They have recently got back to me but i am no longer using PowerShell - we are now using the Graph API which responds as expected.
I'm still keen to get to the bottom of it but we no longer have access to the tenancies to replicate this for the Microsoft Team. Are you experiencing the same issue?

**Comment by dariomws306** [comment]
@CloudDesignBox thank you!

The way to manage this kind of issues is to open a support ticket, and you did it.

I have tried from my side and I can get all the teams running Get-Team alone, but I have tried with -User and I get some Teams that the user is not member of.
I think product group is still working on this cmdlet because you can see this in the article:
"Note: This cmdlet is currently in Beta."
"Note: we are still backfilling existing teams to get returned by this command."

**Comment by CloudDesignBox** [comment]
I'm happy to close this as we are no longer using the PowerShell commandlets. However it would be useful to clearly state that there will be different behaviour with different releases of Teams PowerShell.
