### ISSUE TITLE
Misspelling on page

### ISSUE THREAD

**Issue by mcwetzel** [MicrosoftDocs/office-docs-powershell#1975]
Exchange Management Shell documentation

The topic "Exchange cmdles systax"  appears instead of "syntax"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c916371e-aef0-f91e-e04d-16110358a306
* Version Independent ID: bd073f8e-ba80-25ed-0fe4-286641e9f043
* Content: [Exchange Server PowerShell (Exchange Management Shell)](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/exchange-management-shell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/exchange-management-shell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/exchange-management-shell.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@mcwetzel Thank you for this feedback

It appears that Chris fixed this issue for us. If this issue is not resolved please re-open this issue.
