### ISSUE TITLE
(401) Unauthorized  - New-PnPUPABulkImportJob

### ISSUE THREAD

**Issue by jdubreui** [MicrosoftDocs/office-docs-powershell#1977]
Hi, with an **Azure AD application authentication:** 
Connect-PnPOnline -Url $SiteURL -AppId $appid -AppSecret $appsecret

We got a 401 unauthorized on this : 
`New-PnPUPABulkImportJob -Folder "$folder" -Path $data -IdProperty $userLookupKey -UserProfilePropertyMapping $propertyMap`

We try to : 

- Give **azure AD permission** on SharePoint called "User.ReadWrite.All"
- Give permission on this APP on sharepoint tenant admin(/_layouts/15/appinv.aspx.)
`<AppPermissionRequests AllowAppOnlyPolicy="true">
    <AppPermissionRequest Scope="http://sharepoint/content/tenant" 
     Right="FullControl" />
  <AppPermissionRequest Scope="http://sharepoint/social/tenant" 
     Right="FullControl" />
 </AppPermissionRequests>`

There is any solution or we have to use global admin account ?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jdubreui how are you?
I fired up a lab to test this and I could confirm that, currently, this cmdlet only will work using user accounts and not AppId/AppSecret.
As you might know, PnP cmdlets are community-driven, I kindly ask you to suggest this idea to the community, please start looking here https://docs.microsoft.com/en-us/sharepoint/dev/community/community
We will proceed closing this one.
Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @jdubreui 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
