### ISSUE TITLE
Search-UnifiedAuditLog OutVariable Does not Work

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#1978]
### Summary 
When running `Search-UnifiedAuditLog` with `-OutVariable` parameter, it would not save anything in the variable

### Proof
![image](https://user-images.githubusercontent.com/5260172/47565674-fdd4b280-d931-11e8-9de7-dbfa1f7286d7.png)

![image](https://user-images.githubusercontent.com/5260172/47565688-075e1a80-d932-11e8-9921-9ec6498ff5be.png)

### Steps to reproduce

Connect to Exchange Online with PowerShell
Run the following command:
Search-UnifiedAuditLog -StartDate (get-date).AddDays(-1) -EndDate ( Get-Date ).AddDays(-0.5)  -OutVariable a

### Expected Behavior
Command should fill variable specified in `-Outvariable` parameter
Additionally, it is expected to have append functionality with `-Outvariable +'VariableName'`

**Comment by YuriySamorodov** [comment]
Managed to find a solution. 
It appears we have to create ArrayList and assign it to some variable before we can use it it `-Outvariable`
```
$start = (Get-Date).AddDays(-1)
$end = (Get-Date).AddDays(-0.5)
$auditData = New-Object System.Collections.ArrayList
Search-UnifiedAuditLog -StartDate $start -EndDate $end -OutVariable +auditData | Out-Null
```
![image](https://user-images.githubusercontent.com/5260172/47570059-e13e7780-d93d-11e8-9a4f-8b6585de0b56.png)

**Comment by AndreaBarr** [comment]
@YuriySamorodov Thank you for this feedback and solution. 

@chrisda I wanted to make sure this issue and solution was on your radar.
