### ISSUE TITLE
Creating a new team and adding a new member as owner issue

### ISSUE THREAD

**Issue by yeshwanthjagannath** [MicrosoftDocs/office-docs-powershell#1982]
Creating a new team and adding a new member as owner of the same script, does not elevate the user to a owner. Instead retains the user as a member. This has been happening on more than a handful of occasions. I am running the 0.9.5 build and i have never had this issue before.

**Comment by AndreaBarr** [comment]
@yeshwanthjagannath Thank you for this feedback

Support Service Engineers are tracking all issues with 0.9.5 release. Please open a Service Ticket to make sure this potential bug gets documented. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y
