### ISSUE TITLE
The documentation for "Set-SPOTenant -LegacyAuthProtocolsEnabled" is misleading

### ISSUE THREAD

**Issue by koskila** [MicrosoftDocs/office-docs-powershell#1994]
I think there's a small but misleading issue within the documentation for "Set-SPOTenant -LegacyAuthProtocolsEnabled".

It says "Setting this parameter prevents Office clients using non-modern authentication protocols from accessing SharePoint Online resources." (implicitly saying, that setting the parameter to $True prevents non-modern authentication), when more accurate description would be "Setting this parameter **to $False** prevents Office clients using non-modern authentication protocols from accessing SharePoint Online resources."

The current description is kind of the wrong way around, right?

**Comment by VesaJuvonen** [comment]
PR merged and additional details now included. Thanks @koskila.
