### ISSUE TITLE
Get-PnPTenantRecycleBinItem deliver wrong results

### ISSUE THREAD

**Issue by marc-decker** [MicrosoftDocs/office-docs-powershell#2013]
The Results from the output Get-PnPTenantRecycleBinItem are wrong. There been Sites in that are not available and couldn't get restored. Get-SPDeletedSite deliver different Results and I have no idea where this information comming from.

**Comment by AndreaBarr** [comment]
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell

@VesaJuvonen Would you like me to open this in the SharePoint repo?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @marc-decker How are you? Thanks for your feedback.
I tested in my lab and got the same results using Get-PnPTenantRecycleBinItem and Get-SP**O**DeletedSite.
Please be sure to run the latest updated version of the PnP module.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @marc-decker 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
