### ISSUE TITLE
Error adding multiple E-mails

### ISSUE THREAD

**Issue by Pasark** [MicrosoftDocs/office-docs-powershell#2016]
Get the following error when adding multiple emails using the above syntax:
Set-PnPRequestAccessEmails -Emails @( someone@example.com; someoneelse@example.com )

Set-PnPRequestAccessEmails : Cannot bind argument to parameter 'Emails' because it is an empty array.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d60fca92-0e4a-dbed-8e57-1b8a7ed9bc97
* Version Independent ID: 334d0158-383e-3232-7255-1eef47d70cd7
* Content: [Set-PnPRequestAccessEmails (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnprequestaccessemails?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPRequestAccessEmails.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPRequestAccessEmails.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell

@VesaJuvonen Would you like me to open this in the SharePoint repo?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Pasark Thanks for your feedback.
I created an issue on the corresponding repo, please follow that issue for later updates about your inquiry.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for reporting the issue in Sharepoint repository and linking here and also sharing this explanation. @Pasark   Hope this comment is helpful for you. These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to follow https://github.com/SharePoint/PnP-PowerShell/

**Comment by yogkumgit** [comment]
@officedocsbot close
