### ISSUE TITLE
Copyable code on this page is blank

### ISSUE THREAD

**Issue by JoshJ-MSFT** [MicrosoftDocs/office-docs-powershell#2017]
Copyable code on this page is blank

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e12b6666-7fca-c74f-d3dc-dcbe5813941f
* Version Independent ID: 2b604b84-f43d-dc99-9688-87e3d61dd1d8
* Content: [New-CsClsScenario (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csclsscenario?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsClsScenario.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsClsScenario.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@JoshJ-MSFT Thank you for pointing this out

I will get this over to the PowerShell team for investigation

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
it has been resolved @AndreaBarr
