### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/office-docs-powershell#2020]
This is wrong: Get-OrganizationConfig Export-Cli c:\myFile.xml
it's supposed to be: Get-OrganizationConfig | Export-CliXML c:\myFile.xml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 127e4827-2493-4709-6b1c-62bba341e3ab
* Version Independent ID: e4bf79e9-b3ab-3a24-3a0d-76cafb04d9f6
* Content: [Get-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/get-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Get-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Get-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@itguysocal I fixed it. Thanks for the feedback.
