### ISSUE TITLE
This method is being deprecated as of January 29, 2018 

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftDocs/office-docs-powershell#2043]
Please make a not about it at the beginning of this document?
This method is being deprecated as of January 29, 2018. See details, and information on replacement MS Graph APIs available at https://techcommunity.microsoft.com/t5/Office-365-Blog/Announcing-the-Ge
neral-Availability-of-Microsoft-Graph-reporting/ba-p/137838.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6cebf66-365a-fbd5-4ad6-a611ed687bc4
* Version Independent ID: 98defefb-2df3-2b57-b777-c6f057e9ecae
* Content: [Get-ConnectionByClientTypeReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/reporting/Get-ConnectionByClientTypeReport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/reporting/Get-ConnectionByClientTypeReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/reporting/Get-ConnectionByClientTypeReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by Michal-Ziemba** [comment]
Hi,
I mean, In the article, on the beginning there is not information that the command is deprecated


Pozdrawiam / Best regards,
Michał  Ziemba

**Comment by chrisda** [comment]
@Michal-Ziemba are you talking about the topic on the web or the topic from the command line? The note I mentioned has been in the web topic for months:

![image](https://user-images.githubusercontent.com/33166947/48019454-5b15f400-e0e8-11e8-9856-fb19f69f9665.png)

If it isn't in the help topic from the command line (`Get-Help Get-ConnectionByClientTypeReport`), it should be there sometime before the end of the year (a code check-in is required).

**Comment by Michal-Ziemba** [comment]
Hi Chris,
I swear it wasn’t on the webpage of the command, but apparently it is.
Forget about it.


Pozdrawiam / Best regards,
Michał  Ziemba
