### ISSUE TITLE
Missing Examples

### ISSUE THREAD

**Issue by marmstrong94** [MicrosoftDocs/office-docs-powershell#2044]
This article is missing examples for the parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd14836b-18f6-4bcf-e4d6-42b358cd7aa1
* Version Independent ID: 903196a7-6899-c6df-a3aa-fa29bd1d1ba5
* Content: [Get-CsCallerIdPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-cscalleridpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsCallerIdPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsCallerIdPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@marmstrong94 Issue is looked into, and PR is created for updating the documentation. Appreciate, you pointed out this to us.

**Comment by kenwith** [comment]
Awesome, can we get link to the PR @yogkumgit ?

**Comment by yogkumgit** [comment]
PR https://github.com/MicrosoftDocs/office-docs-powershell/pull/2702/files

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @marmstrong94  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
