### ISSUE TITLE
Add-TeamUser

### ISSUE THREAD

**Issue by carolynblanding** [MicrosoftDocs/office-docs-powershell#2055]
Please add ability to modify display name when adding new users with Add-TeamUser

**Comment by yogkumgit** [comment]
@carolynblanding  Thank you very much for your kind feedback. Considering your valuable feedback, we have logged this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

User Voice Link: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33356242-guest-display-name
