### ISSUE TITLE
Not working - Cannot process argument because the value of argument "path" is null. 

### ISSUE THREAD

**Issue by a7259w** [MicrosoftDocs/office-docs-powershell#2064]
Doesn't work for me and I get no reply when asking on Technet.
Can you please resolve?
https://social.technet.microsoft.com/Forums/msonline/en-US/30ce1b57-6dc7-462d-b4fa-24950ed3fc27/connect-to-exchange-online-powershell-using-multifactorauthentication-error-when-loading?forum=onlineservicesexchange

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@a7259w I cannot. Since this isn't a documentation issue, your best bet is to file a support case.
