### ISSUE TITLE
Example 2 is missing '-Location'

### ISSUE THREAD

**Issue by marehmat** [MicrosoftDocs/office-docs-powershell#2069]
$nodes = Get-PnPNavigationNode -QuickLaunch
PS:&gt;$nodes | Select-Object -First 1 | Remove-PnPNavigationNode -Force

should be 

$nodes = Get-PnPNavigationNode -Location QuickLaunch
PS:&gt;$nodes | Select-Object -First 1 | Remove-PnPNavigationNode -Force

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53df4ad8-9006-4d5c-8829-a1c481dac939
* Version Independent ID: 15dfc257-8c5f-63d6-ffe7-f7a7163c25bf
* Content: [Remove-PnPNavigationNode (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpnavigationnode?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPNavigationNode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPNavigationNode.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by khorne3** [comment]
Hey @marehmat -- thanks for your contribution. It looks, though, that the command is correct, since the value for  `-Location` is `-QuickLaunch` (see [optional parameter description here](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpnavigationnode?view=sharepoint-ps)).

**Comment by kenwith** [comment]
Regarding PnP cmdlets.. I posted a message here: https://github.com/MicrosoftDocs/office-docs-powershell/issues/2450   @khorne3 we will need to update the Wiki on best way to handle these since the community for PnP is actually over at github.com/sharepoint.  Let's see what @VesaJuvonen recommends. CC @nenonix and @AndreaBarr

**Comment by VesaJuvonen** [comment]
Thanks @marehmat for submitting absolutely valid documentation fix. We have now updated the documentation and pushed the update to the official documents. Thanks for your input and contributions around these topics.

Fixed with #2488.
