### ISSUE TITLE
Get-SPOUserOneDriveLocation Throws Muli-Geo Error

### ISSUE THREAD

**Issue by MatthewMcD** [MicrosoftDocs/office-docs-powershell#2071]
Attempting to use this cmdlet in a demo and getting a multi-geo error. If this is ONLY for multi-geo tenants it should be documented that way.

Error:
Get-SPOUserOneDriveLocation : Error Code: -4,This tenant is not a Multi-Geo tenant. The 
operation you are trying to perform is only supported on Multi-Geo tenants. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d10d69af-d0bc-a9f5-cfdb-4a206d2e11c8
* Version Independent ID: 61b19b32-618e-e014-9097-1f69b8154af8
* Content: [Get-SPOUserOneDriveLocation (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spouseronedrivelocation?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserOneDriveLocation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserOneDriveLocation.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by dnwhittaker** [comment]
...and if it is for Multi-Geo tenants, then what's the cmdlet that works?
