### ISSUE TITLE
Suspect: Enabling pre-requisites for guest access to Teams set LegacyAuthProtocolsEnabled to $false

### ISSUE THREAD

**Issue by fredericklin** [MicrosoftDocs/office-docs-powershell#2073]
Yesterday, we enabled guest access to Office 365 groups, Teams, and SharePoint Online.  Today, all of our unattended SharePoint Online management Powershell scripts that are triggered on a schedule in Azure Automation stopped working.  I do not know if there is a correlation between these two.  I found out some time later that the LegacyAuthProtocolsEnabled property from SPOTenant has been set to $false.  I've set the property to $true and after some time, our Powershell scripts started to work again.

This is what we did to enable guest access:

``` Powershell
# 1: Enable guest sharing in Azure tenant:
# https://portal.azure.com/#blade/Microsoft_AAD_IAM/UsersManagementMenuBlade/UserSettings/menuId/
# Go to "Manage external collaboration settings"
# [Yes] Guest users permissions are limited
# [Yes] Admins and users in the guest inviter role can invite
# [Yes] Members can invite
# [No] Guests can invite
#
# The production setting is currently [Yes][Yes][No][No]
#
# 2: Enable guest access in Office 365 groups:
# https://admin.microsoft.com/AdminPortal/Home#/Settings/ServicesAndAddIns
# Go to "Office 365 Groups"
# [On] Let group members outside the organization access group content
# [On] Let group owners add people outside the organization to groups
#
# These settings enable guest access to only Unified Group objects in Azure AD.
# Allow 2-24 hours for the change to take effect. 
#
# The production setting is currently [OFF]
#
# 3: Enable guest access in Microsoft teams. NOTE: Use the new Teams admin portal; Below description not accurate.
# # https://admin.microsoft.com/AdminPortal/Home#/Settings/ServicesAndAddIns
# Go to "Microsoft Teams" -> Settings by user/license Type
#
# [Guest] Select the user/license type you want to configure
#	[On] Turn Microsoft Teams on or off for all users of this type
#
# The production setting is currently [Guest][Off]

# 
# 4: Enable guest access in SharePoint and OneDrive for Business:
# https://mytenant-admin.sharepoint.com/_layouts/15/online/ExternalSharing.aspx
# Go to "Sharing outside your organization"
#
# [True] Allow users to invite and share with authenticated external users
#
# The production setting is currently the same as the intended setting (no change)
#
# 5: Configure guest link sharing for SharePoint Online
#
# This allows explicit sharing to guest users but does not allow anonymous links.
#
# Connect-SPOService -Url <SharePoint Online Admin Center URL, ex: https://mytenant-admin.sharepoint.com>
# Set-SPOTenant -SharingCapability ExternalUserSharingOnly
#
# The prouction setting is currently "ExternalUserSharingOnly" (no change)
#
```

If there is a property being set, it would be nice to have this documented when enabling guest access.  Also, like #540 , we need a way to use the SharePoint Online Management Shell using modern/more secure auth flows while running unattended.  Perhaps leverage app registrations in Azure AD?  If there is a current method, we need some guidance in the docs.  Thank you!

**Comment by msbemba** [comment]
That is right, you need to Set-SPOTenant -LegacyAuthProtocolsEnabled $True so that the scheduled scripts and unattended access work without issues. 

You can't force Modern Authentication when you use the Connect-SPOService cmdlet in Microsoft SharePoint Online Management Shell, unless you add an undocumented registry key to your client computer. You need to add the following registry subkey on the client computer to force Modern Authentication.

[HKEY_CURRENT_USER\Software\Microsoft\SPO\CMDLETS]

"ForceOAuth" = dword:00000001

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @fredericklin 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
