### ISSUE TITLE
"list details about Data Loss Prevention (DLP) rule matches for SharePoint Online and OneDrive for Business in"

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/office-docs-powershell#2078]
This is a module for Exchange Online (isn't it?), but your introduction says this applies to SharePoint Online and OneDrive for Business.  Which is it?

When I try to run this command, and I *know* there are reports in Exchange because they appear in the EAC, nothing appears.  What's going on?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f04d48-7267-e9e4-0b1c-efb99d571286
* Version Independent ID: 21a2271e-b300-cf93-481b-88feed613563
* Content: [Get-DlpDetailReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/get-dlpdetailreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpDetailReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpDetailReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@anwarmahmood1 when the 'unified DLP' feature was first introduced in the Security & Compliance Center (different from the original document fingerprinting DLP in Exchange Online), the DLP feature only worked for SharePoint Online and OneDrive for Business. Exchange Online was added later. I added Exchange Online to the description.
