### ISSUE TITLE
"a summary of Data Loss Prevention (DLP) rule matches for SharePoint Online and OneDrive for Business in" - not Exchange Online?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/office-docs-powershell#2079]
This is a module for Exchange Online (isn't it?), but your introduction says this applies to SharePoint Online and OneDrive for Business. Which is it?

When I try to run this command, and I know there are reports in Exchange because they appear in the EAC, nothing appears. What's going on?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f8a3f90-77e6-17bc-96da-86656c83b621
* Version Independent ID: 1cff5de0-c3bd-489e-5fef-a2a6d6e55d89
* Content: [Get-DlpDetectionsReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/get-dlpdetectionsreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpDetectionsReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpDetectionsReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@anwarmahmood1 when the 'unified DLP' feature was first introduced in the Security & Compliance Center (different from the original document fingerprinting DLP in Exchange Online), the DLP feature only worked for SharePoint Online and OneDrive for Business. Exchange Online was added later. I added Exchange Online to the description.

Thanks for the feedback.

**Comment by anwarmahmood1** [comment]
Does that mean this command only works for Unified DLP only, and not Exchange Online DLP policies?

**Comment by chrisda** [comment]
@anwarmahmood1 judging by the parameter names like _DlpCompliancePolicy_ and _DlpComplianceRule_, I'd say that's a safe bet.
