### ISSUE TITLE
why no examples?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/office-docs-powershell#2080]
they would really help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f8a3f90-77e6-17bc-96da-86656c83b621
* Version Independent ID: 1cff5de0-c3bd-489e-5fef-a2a6d6e55d89
* Content: [Get-DlpDetectionsReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/get-dlpdetectionsreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpDetectionsReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpDetectionsReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by anwarmahmood1** [comment]
oops! there is an example!  but it is very basic!

**Comment by chrisda** [comment]
@anwarmahmood1 do you have any suggestions for what would be a "good" example?
