### ISSUE TITLE
Should the URL be updated?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/office-docs-powershell#2081]
After connecting, it reports...

WARNING: Your connection has been redirected to the following URI:
"https://eur03b.ps.compliance.protection.outlook.com/powershell-liveid?PSVersion=4.0 "

Should the URL in this documentation be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Office 365 Security & Compliance Center PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md)
* Service: **o365-security-and-compliance**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by anwarmahmood1** [comment]
ignore this comment

**Comment by chrisda** [comment]
@anwarmahmood1 I don't think so. Redirection is expected for different regions, datacenters, or versions of SCC PowerShell for an organization.
