### ISSUE TITLE
Prefix option?  Just like Import-PSSession -Prefix "Exo"

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#2083]
I like to add a prefix (e.g. Get-ExoMailbox, Get-ExoCasMailbox, Get-ExoOrganizationRelationship) to my EXO PowerShell sessions.  This allows me to connect to Exchange on-premises at the same time, without worrying about the commands from each session conflicting.

I see there is already a -PSSessionOption parameter but I'm having trouble figuring out if this might be the means to accomplish setting a prefix.  Can you please provide guidance for the -PSSessionOption parameter?  Depending on if it does or doesn't enable setting a prefix, I will go and do the UserVoice feature suggestion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeremyTBradshaw it would probably be easier to use -Prefix on your connection to the on-premises Exchange server.

**Comment by JeremyTBradshaw** [comment]
You know, agreed.  That is a perfect solution, with the only drawback being me having to break a habit 😁.

Thanks.  Feel free to close but if an explanation of when and how to use the PSSessionOption was available, just in case, that would be bonus points!
