### ISSUE TITLE
-AddCreatorAsMember Is Boolean

### ISSUE THREAD

**Issue by cloudedturtle** [MicrosoftDocs/office-docs-powershell#2086]
The documentation states that the parameter is a Boolean value, but has the "default" value of "None" which is not a Boolean. Documentation is also not clear on the usage. The description states that the Creator will be added as an Owner and as a result also a member. This would imply that the default value would be True and I could opt out as the "Owner/Member" by setting this value to False. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by khorne3** [comment]
Hi @cloudedturtle! I just wanted to follow up with you on this issue -- are you referring to the `-owner` parameter? If so, it looks like it's been updated since you logged this request, but if not, please let me know.

**Comment by cloudedturtle** [comment]
It appears that this was deprecated as noted in the updated documentation. However, it also appears that the functionality was actually replaced by the -Owner parameter. 
Thanks

**Comment by kenwith** [comment]
@cloudedturtle - thanks for this, do you think it needs a note in the -Owner parameter with more info or explains how it is replaced?

**Comment by get-itips** [comment]
Hello @cloudedturtle **thanks for your feedback. We really appreciate it.**

I tested the scenario in my lab and I can confirm that:

- AddCreatorAsMember has been deprecated as of 0.9.6 release

- Owner has replaced the setting and works exactly like the article states, if not specified, the user running the cmdlet will be added as owner (and team member), if it is specified, the specified user will be the Team owner (and team member).

**Hope this information helps you.**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @cloudedturtle 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
