### ISSUE TITLE
Does this commandlet accept an input parameter for a GroupID? 

### ISSUE THREAD

**Issue by cloudedturtle** [MicrosoftDocs/office-docs-powershell#2088]
This is not listed in the Inputs section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8450991f-9f85-4d87-51b3-efa8e1004a24
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by Mike-Crowley** [comment]
According to @islubin in comment #2222 the only parameter is -user and it is only used to return the membership of the currently connected user, regardless of the value of the -user parameter. Strange.

**Comment by dariomws306** [comment]
Hi @cloudedturtle , thank you for your feedback.

-GroupID is not listed and it's not accepted. You can only use -User.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @cloudedturtle 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
