### ISSUE TITLE
ErrorAction support in MicrosoftTeams

### ISSUE THREAD

**Issue by cloudedturtle** [MicrosoftDocs/office-docs-powershell#2089]
Errors stop progress when using MicrosoftTeams commands. -ErrorAction parameter is not an optional parameter.

**Comment by get-itips** [comment]
Hi @cloudedturtle   thanks for your feedback,  I see that this wouldn't cause a change in documentation.  @yogkumgit can you kindly help here?

**Comment by yogkumgit** [comment]
@cloudedturtle  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
