### ISSUE TITLE
Channel Restore

### ISSUE THREAD

**Issue by Chukaka** [MicrosoftDocs/office-docs-powershell#2091]
Will there be a seperate command to restore deleted channels?

Currently, the only way to do a channel restore is to proceed manually in the "Manage Team &gt; Channels &gt; Deleted" section and click on the Restore button .

If you try to recreate a channel with the same DisplayName as one that was deleted, you get this error:
New-TeamChannel : Error occurred while executing
Code: NameAlreadyExists
Message: Channel name already existed, please use other name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd44b411-4b59-b90f-0b82-ad0a87652854
* Version Independent ID: 2c52cc4e-47a1-be0d-8860-1011adf061fd
* Content: [New-TeamChannel (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-teamchannel?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Chukaka
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
