### ISSUE TITLE
ConvertTo-SPOMigrationTargetedPackage bad userGroup.xml convertion

### ISSUE THREAD

**Issue by Selmiltone** [MicrosoftDocs/office-docs-powershell#2102]
Hello,
When using the ConvertTo-SPOMigrationTargetedPackage command, the usergroup.xml is not well converted.
Groups are always marked as deleted and their login is not converted to a proper Sharepoint Online login so that right could be reported from the source to the sharepoint online target.
Below is a  UserGroup.xml sample, after convertion:
<?xml version="1.0" encoding="utf-8"?>
<UserGroupMap xmlns="urn:deployment-usergroupmap-schema">
  <Users>
    <User Id="2" Name="RisdWriters" Login="c:0-.f|rolemanager|SOME-ID" Email="" IsDomainGroup="true" IsSiteAdmin="false" IsDeleted="true" Flags="0" />
    <User Id="4" Name="Abbey Begay" Login="i:0#.f|membership|user294@sometenant.onmicrosoft.com" Email="user294@sometenant.onmicrosoft.com" IsDomainGroup="false" IsSiteAdmin="false"  IsDeleted="false" Flags="0" />
  </Users>
  <Groups />
</UserGroupMap>

**Comment by msbemba** [comment]
@Selmiltone Can you attach the sample .XML file? and also brief us on the type of migration?

**Comment by msbemba** [comment]
@Selmiltone  The cmdlet ConvertTo-SPOMigrationTargetedPackage converts the XML files and saves them as a new set of targeted migration package metadata files to the target directory.

The next time you have this issue come up we want to make sure it's documented and worked on by support so please open a support ticket.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y
