### ISSUE TITLE
Cannot update property if user has not logged in

### ISSUE THREAD

**Issue by LouFarho** [MicrosoftDocs/office-docs-powershell#2103]
When using this command to bulk update multiple users, it only updates users who have logged into Office 365. Is this by design?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f14cc56-c5e8-3d16-71fd-3742a355aff1
* Version Independent ID: 8f22f503-b757-9446-f50a-3506ba59fe93
* Content: [Set-PnPUserProfileProperty (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpuserprofileproperty?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPUserProfileProperty.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPUserProfileProperty.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by VesaJuvonen** [comment]
That is by design as the actual profile object is created when the user first-time signs in to the SharePoint Online.
