### ISSUE TITLE
Missing Content on Moving the Meeting Room to Skype for Business Online

### ISSUE THREAD

**Issue by NeeranjanShettar** [MicrosoftDocs/office-docs-powershell#2104]
As per  the article - https://support.microsoft.com/en-us/help/4020991/enables-the-move-csmeetingroom-cmdlet-to-move-a-meeting-room-from-on-p ; this cmdlet Move-CsMeetingRoom must be able to move the meeting room from Skype for Business On-Prem to Skype for Business Online tenant. However this document is not updated new parameters i.e. "-hostedmigrationoverrideurl" and "-Credential" and also need to mention about the support of Moving the meeting rooms to Online. Please have this reviewed and get the required content updated ASAP. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 391cf9b9-34b2-3292-18fa-07bb09c1e670
* Version Independent ID: 370170a5-4ffd-bd24-d185-bab2b1f1e151
* Content: [Move-CsMeetingRoom (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Move-CsMeetingRoom?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Move-CsMeetingRoom.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Move-CsMeetingRoom.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by NeeranjanShettar** [comment]
Any updates here ? it's been long time no response. Thanks in advance.

**Comment by dariomws306** [comment]
Hi @NeeranjanShettar , thanks for your feedback.

I am updating this article.
