### ISSUE TITLE
Get-MoveRequestStatistics -ReportOnly Returns Encoded Strings

### ISSUE THREAD

**Issue by DougChandler** [MicrosoftDocs/office-docs-powershell#2117]
When calling Get-MoveRequestStatistics -ReportOnly against Office365 (Exchange Online), the return is an array of encoded strings. Get-MoveRequestStatistics -IncludeReport operates correctly.
According to the documentation, this should be an array of report entries not encoded strings.

**Comment by chrisda** [comment]
@DougChandler I updated the ReportOnly parameter description in this and other cmdlet topics that have it to state that the results returned are encoded strings.

Thanks for the feedback.
