### ISSUE TITLE
Command requires IIS to be restarted

### ISSUE THREAD

**Issue by LouFarho** [MicrosoftDocs/office-docs-powershell#2119]
Please provide a warning that the command may require the IIS be restarted for the change to take affect.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d77b895-234c-9584-7806-2c39a7d607d0
* Version Independent ID: 3ce7d735-77bd-25e4-a961-ef9e3195ecaf
* Content: [Move-SPSite (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/move-spsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Move-SPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Move-SPSite.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@LouFarho, thank you for your feedback. to properly service your request, can you be more specific on what change you would like to see and where the change would be implemented?  thank you.
