### ISSUE TITLE
Trim branches

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/office-docs-powershell#2121]
There are a bunch of merged and closed branches in the repo https://github.com/MicrosoftDocs/office-docs-powershell/branches/all
When using the web editor, the branch list is getting long and would benefit from removing the old branches

**Comment by VesaJuvonen** [comment]
Thanks @nschonni - absolutely valid comment and we absolutely need to get these cleaned. Ping @kenwith as the primary coordinator of this repository.

**Comment by kenwith** [comment]
Good catch on this! I deleted a number of the older branches and the 'patch-x' branches.. also sent an email to other admins to check their branches and will remove any branches over 90 days without being updated. Thanks again for catch!
