### ISSUE TITLE
ReadReceiptsEnabledType explanation

### ISSUE THREAD

**Issue by savusca** [MicrosoftDocs/office-docs-powershell#2133]
Can you please provide an explanation for the -ReadReceiptsEnabledType attribute?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c15f298f-ba92-a6fe-fcc1-af88ffbfc6f1
* Version Independent ID: 0ba323cf-90ea-58bd-2f77-9826e1450d53
* Content: [Set-CsTeamsMessagingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmessagingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMessagingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMessagingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
Hi @savusca , Thank you for your helpful feedback. I am working to complete this description.

**Comment by dariomws306** [comment]
Hi @savusca , it's done!

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation. @savusca 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
