### ISSUE TITLE
Teams: Owner getting Access Denied on Set-TeamMemberSettings

### ISSUE THREAD

**Issue by silmer** [MicrosoftDocs/office-docs-powershell#2138]
What I want: To be able to create a team using New-Team, then update settings using Set-TeamMemberSettings.

What is actually happening: Creating user (me) is seemingly added as owner automatically during creation (checked using Get-TeamUser). However, when I call Set-TeamMemberSettings I get access denied. We then checked the Teams client and in the "Manage team" settings the user is only listed as "member". Adding other members as owner, removing and re-applying the user-account as owner in Powershell does not fix the issue.

A workaround is to set the user as owner manually from "Manage team" in the Teams client. That seems to correctly set the user as owner, allowing Set-TeamMemberSettings to be used from Powershell, however, that is not a viable solution for our project.

Would be very thankful for any other suggestions on workarounds while this is being looked at!

Steps to reproduce: Run the following in Powershell (tested in Teams module 0.9.3 and 0.9.5):

```
Connect-MicrosoftTeams -Credential $Credentials
$TeamsTitle = "Dummy 123"
$TeamsAlias = "Dummy123"
$group = New-Team -DisplayName $TeamsTitle -Alias $TeamsAlias -AccessType "Public"
Get-TeamUser -GroupId $group.GroupId
Set-TeamMemberSettings -GroupId $group.GroupId -AllowCreateUpdateChannels false
```

Adding error output:

> Code: AccessDenied
> Message: Failed to execute Skype backend request SetThreadPropertyRequest.
> InnerError:
>   RequestId: bddf2afd-e1d5-472c-afe1-0e5a71e95548
>   DateTimeStamp: 2018-11-16T10:51:16
> HttpStatusCode: AccessDenied
> At line:1 char:1
> + Set-TeamMemberSettings -GroupId $group.GroupId -AllowCreateUpdateChan ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Set-TeamMemberSettings], ApiException
>     + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.SetMemberSe 
>    ttings
>

**Comment by msbemba** [comment]
The cmdlet is currently in Beta and lets you provision a new Team for use in Microsoft Teams and will create an O365 Unified Group to back the team.  Perhaps, It was a temporary issue? Let me know if this works now, If it doesn't could you also check the properties on the unified group if it is set correctly?

Connect-MicrosoftTeams -Credential $Credentials
$TeamsTitle = "Dummy 123"
$TeamsAlias = "Dummy123"
$group = New-Team -DisplayName $TeamsTitle -Alias $TeamsAlias -AccessType "Public"
Get-TeamUser -GroupId $group.GroupId
Set-TeamMemberSettings -GroupId $group.GroupId -AllowCreateUpdateChannels $false

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @silmer  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
