### ISSUE TITLE
get-inboxrule doesnt show hidden rules on exchange online

### ISSUE THREAD

**Issue by ponsaelius** [MicrosoftDocs/office-docs-powershell#2140]
Get-Inboxrule is really good to help diagnose users who have set rules, forgotten them or rules that disobey company policy.

The maddening bit is that hidden rules are excluded from the online version. You have to go back to users and run /cleanrules. Often it is a pain point as users struggle with command line options.

Exchange online would benefit from being able to view, disable and remove "hidden" or corrupted rules.

**Comment by chrisda** [comment]
@ponsaelius, I agree. I suggest that you file a support case and see what they suggest.

Thanks for the feedback.
