### ISSUE TITLE
Remove-PnPNavigationNode -Location QuickLaunch -All doesn't work, my work around

### ISSUE THREAD

**Issue by tristian2** [MicrosoftDocs/office-docs-powershell#2157]
from the documentation at https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpnavigationnode?view=sharepoint-ps

"removing all nodes" example number 5 doesn't seem to work for me, as it want the ids of the navigation items

i ran something like this and it works for my needs
`$navNodes = Get-PnPNavigationNode -Location TopNavigationBar
$navNodes | ForEach-Object {write-host $_.id; Remove-PnPNavigationNode -Identity $_.id -force} 
`
ty

**Comment by VesaJuvonen** [comment]
Closing based on the comment.
