### ISSUE TITLE
the command does not delete a file with # in its name

### ISSUE THREAD

**Issue by nalhemyariirexorg** [MicrosoftDocs/office-docs-powershell#2158]
when using the command with -force files with # in their name are not being deleted, any work around for this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c71852-b29d-30f8-e279-20c4dbb5e01f
* Version Independent ID: 78ced12f-e034-d3a5-0a49-a2bc3e4d0e50
* Content: [Remove-PnPFile (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpfile?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPFile.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell

@VesaJuvonen Would you like me to open this in the SharePoint repo?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @nalhemyariirexorg 
**Thanks for your feedback.**
I tried the scenario involving the _Remove-PnpFile_ cmdlet in my lab and could succesfully delete a file with # in the name using either -Force or not. So, apparently, no documentation needs to be modified.

Hope this information helps you.

**Thanks**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @nalhemyariirexorg 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by nalhemyariirexorg** [comment]
I tried it again, getting the same issue, i cannot delete a file using this command if the filename have a # in it

Connect-PnPOnline -Url https://XXXX.sharepoint.com/sites/Test-Noor-Team2
Remove-PnPFile -SiteRelativeUrl "/Shared%20Documents/Communications/CrazyFileName#1#.docx"
i get the confirmation window poping up, i click yes, doc is not removed

**Comment by get-itips** [comment]
Hello @nalhemyariirexorg 
I tried with the exact name that you provided, and it worked.
Please be sure not to use %20 in /Shared Documents/
Thanks

**Comment by nalhemyariirexorg** [comment]
Hello @get-itips i ran the following command, still no luck in removing the file
Remove-PnPFile -SiteRelativeUrl "/Shared Documents/Communications/CrazyFileName#1#.docx"

**Comment by get-itips** [comment]
@nalhemyariirexorg Please be sure you run the last updated version of the module and that the docx file is not checked-out.

**Comment by nalhemyariirexorg** [comment]
Now its working :)

Updated pnp, removed %20 from url

SharePointPnPPowerShellOnline 3.8.1904.0 -> Works
SharePointPnPPowerShellOnline 3.4.1812.2 -> Did no work

Thank you

**Comment by get-itips** [comment]
Glad to hear.
