### ISSUE TITLE
pipeline handling broken

### ISSUE THREAD

**Issue by phillkOCCM** [MicrosoftDocs/office-docs-powershell#2159]
tried get-unifiedgroup | select ID | get-unifiedgrouplinks -identity $_.id -linktype members 
..says its null
tried  just -identity $_ -linktype members

also says its null..
seems to be broken .
Ppl wonder why everyone thinks powershell is hard, its because no one  consistently documents how things output to pipe or input.

**Comment by chrisda** [comment]
@phillkOCCM, how well (or not well) cmdlets pipeline with each other varies across products and features. I tested this, and it works for individual O365 groups:

```
$x = Get-UnifiedGroup -Identity <GroupAlias>
Get-UnifiedGroupLinks -Identity $x.Alias -LinkType Members
```

Is this what you're looking for?
