### ISSUE TITLE
The use of force command is throwing error.

### ISSUE THREAD

**Issue by codejith** [MicrosoftDocs/office-docs-powershell#2163]
Is there any update on using the force command with Remove-MigrationBatch cmdlet ? If so kindly update the content.

Also I tried to delete a duplicate migration batch with the same name. We can't delete the duplicate batch with exact name using the cmdlet remove-migrationbatch. So is there any option to do so ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46dcb655-2215-6937-811c-00fe93edd0ff
* Version Independent ID: bb878cd0-c500-e789-dece-430673c00c31
* Content: [Remove-MigrationBatch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/remove-migrationbatch?view=exchange-ps#examples)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/Remove-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/Remove-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@codejith I confirmed the Force switch is only available in on-premises Exchange Server, so I updated the topic accordingly.

As far as your second question, the only identity value on a migration batch object appears to be the Identity property that contains the name of the migration batch. The object doesn't have the typical unique identifiers like GUID or DistinguishedName. Can you go into the [EAC](https://docs.microsoft.com/Exchange/exchange-admin-center) at **Recipients** > **Migration** and delete the correct job from there?

**Comment by jbostoen** [comment]
I'm in a similar situation where people - even MSFT employees - tell me to use that switch.

But worse: what to do now with corrupt batches? I got four batches stuck (maybe one is just corrupt though). How to force this?

**Comment by chrisda** [comment]
@jbostoen, can you confirm that the batches can't be seen and deleted in the EAC? If not, I would suggest that you file a support case.

**Comment by jbostoen** [comment]
You could see them, but there seemed stuck. I wanted to file a support case but it was impossible. Anyhow, I got it fixed myself now.
