### ISSUE TITLE
Remove-PnPNavigationNode -Location QuickLaunch -All doesn't work, my work around...

### ISSUE THREAD

**Issue by tristian2** [MicrosoftDocs/office-docs-powershell#2164]
"removing all nodes" example number 5 doesn't seem to work for me, as it want the ids of the navigation items

i ran something like this and it works for my needs
$navNodes = Get-PnPNavigationNode -Location TopNavigationBar $navNodes | ForEach-Object {write-host $_.id; Remove-PnPNavigationNode -Identity $_.id -force} 
ty

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53df4ad8-9006-4d5c-8829-a1c481dac939
* Version Independent ID: 15dfc257-8c5f-63d6-ffe7-f7a7163c25bf
* Content: [Remove-PnPNavigationNode (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpnavigationnode?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPNavigationNode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPNavigationNode.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell

@VesaJuvonen Would you like me to open this in the SharePoint repo?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tristian2 thanks for your feedback.
I reviewed and checked on my lab what you are saying and created a PR to improve the cmdlet's documentation.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @tristian2 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
