### ISSUE TITLE
I had hoped for more.

### ISSUE THREAD

**Issue by Boledy** [MicrosoftDocs/office-docs-powershell#2165]
I  have thousands of old groups in my tenancy.  I need a way to find and delete groups that have not been used for a couple  of years. Something like get-unifiedGroup -unused 430 =$true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38bb8d4e-9525-b291-ac2e-71c7da02984d
* Version Independent ID: 02753e62-8b57-90cc-bf6e-9f69661c3135
* Content: [Remove-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/Remove-UnifiedGroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Remove-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Remove-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Boledy, try this: [Finding Obsolete Office 365 Groups with PowerShell](https://www.petri.com/identifying-obsolete-office-365-groups-powershell).
