### ISSUE TITLE
Article needs to be modified.

### ISSUE THREAD

**Issue by SanguptaMSFT** [MicrosoftDocs/office-docs-powershell#2166]
Article has following example which is incorrect.
Set-CsAuthConfig -BlockWindowsAuthExternally

Correct:

Set-CsAuthConfig -Scenario BlockWindowsAuthExternally

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26656471-f4e4-3dbe-b915-5230400d7b7f
* Version Independent ID: 4dc006ee-6bf8-a929-94f7-499a5af1f7a1
* Content: [Set-CsAuthConfig (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csauthconfig?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsAuthConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsAuthConfig.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
Hi @SanguptaMSFT , thank for your feedback.

It was fixed, please check.

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and sharing this explanation. @SanguptaMSFT Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
