### ISSUE TITLE
please add documentation on  the ShowPeoplePickerSuggestionsForGuestUsers parameter.

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/office-docs-powershell#2173]
Can B2B collaboration users access SharePoint Online and OneDrive?
 However, the ability to search for existing guest users in SharePoint Online by using the people picker is Off by default. To turn on the option to search for existing guest users, set ShowPeoplePickerSuggestionsForGuestUsers to On. You can turn this setting on either at the tenant level or at the site collection level. You can change this setting by using the Set-SPOTenant and Set-SPOSite cmdlets. With these cmdlets, members can search all existing guest users in the directory. Changes in the tenant scope don't affect SharePoint Online sites that have already been provisioned.

ref: https://docs.microsoft.com/en-us/azure/active-directory/b2b/faq

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1c6b2b-5af6-acce-b7e8-bf784bb0973e
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Thank you @Josverl for your suggestion, I created a PR to add a description for the referenced parameter.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Josverl  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
