### ISSUE TITLE
Get-SPOHubsite also returns deleted Hubsites

### ISSUE THREAD

**Issue by tbuntain** [MicrosoftDocs/office-docs-powershell#2175]
I ran this command in my tenant today and it returned a hub site that was deleted a couple of months ago. I am not sure if that is the intent but I did not see it documented that it also returns deleted sites as well as active sites. Apologies if this has already been mentioned.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2a3e04-1dd7-df88-d04b-c1a2b41cceb3
* Version Independent ID: a17de3ab-7de2-11ba-b39c-528d0dd61702
* Content: [Get-SPOHubSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spohubsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHubSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHubSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tbuntain** [comment]
Just answered my own question. You have to Unregister the site as a Hub Site before deleting the site

**Comment by kenwith** [comment]
@tbuntain - thanks for sharing your experience on this. We will get the doc updated with the knowledge.

@tseward - maybe one you could submit a PR to add clarity?
