### ISSUE TITLE
New-SupervisoryReviewRule -Condidtion parameter does require quotation marks

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftDocs/office-docs-powershell#2179]
As I can see, the command example where the -Condition parameter is given without quotation marks trigger an error. 
The correct example string should be:
New-SupervisoryReviewRule -Name "EU Brokers Rule" -Policy "EU Brokers Policy" -SamplingRate 100 -Conditions "((NOT(Reviewee:US Compliance)) -AND (Reviewee:EU Brokers) -AND ((trade) -OR (insider trading)) -AND (NOT(approved by the Contoso financial team)))"

Besides, there is no information about who is the reviewer or how to point a reviewer. Does this command give a possibility to point out the reviewer account or group?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab8fce83-3aa0-d912-9042-39fb3d8188e7
* Version Independent ID: 28ae7ff6-bbe0-831f-4ce6-f312532f2ca4
* Content: [New-SupervisoryReviewRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/New-SupervisoryReviewRule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance/New-SupervisoryReviewRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance/New-SupervisoryReviewRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Michal-Ziemba I added quotation marks as you suggested.

As far as reviewers, it appears that you specify those in the policy (the [New-SupervisoryReviewPolicyV2](https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance/new-supervisoryreviewpolicyv2) or [Set-SupervisoryReviewPolicyV2](https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance/new-supervisoryreviewpolicyv2) cmdlets, which is identified in the rule by the _Policy_ parameter.

Thanks for the feedback.
