### ISSUE TITLE
Force does not work (anymore?) in Exchange Online

### ISSUE THREAD

**Issue by jbostoen** [MicrosoftDocs/office-docs-powershell#2180]
Same problem as with 'Remove-MigrationBatch'.
What is the alternative?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f87d9e58-d684-160a-a3e6-88d6b2f09518
* Version Independent ID: dc4facba-6a17-2d88-b2f2-67adda01c667
* Content: [Remove-MigrationUser (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/remove-migrationuser?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/Remove-MigrationUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/Remove-MigrationUser.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jbostoen, I updated the Remove-MigrationUser topic to indicate that the Force parameter is on-premises only.

Believe it or not, the best way to get an answer for your question about alternatives is to file a support ticket.
