### ISSUE TITLE
Get-messagetrace is misleading

### ISSUE THREAD

**Issue by jbakar** [MicrosoftDocs/office-docs-powershell#2181]
The Exchange Online get-messagetrace command only limits results for the past 10 days of the -startdate and -enddate but it allows user to enter eventhough its out of scope(10 days) limit and not telling user about the mistake. User may think there was no result within that specific time period where actually it is an out-of-bound query. Please have this corrected

**Comment by chrisda** [comment]
@jbakar, I added the information to the Description section of the Get-MessageTrace cmdlet topic.

Thanks for the feedback
