### ISSUE TITLE
Incorrect Documentation: Includes Parameter Missing

### ISSUE THREAD

**Issue by stuck-on-starting** [MicrosoftDocs/office-docs-powershell#2183]
The documentation states that this cmdlet has an Includes parameter but it is unavailable.

(GET-Command Get-PnPSubWebs).parameters
Key
---
Identity
Recurse
Web
Connection
Verbose
Debug
ErrorAction
WarningAction
ErrorVariable
WarningVariable
OutVariable
OutBuffer
PipelineVariable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69038c45-7684-c7f5-4174-b26a9b67fd24
* Version Independent ID: 6c599783-23a6-9715-a73f-47aad1317a5d
* Content: [Get-PnPSubWebs (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpsubwebs?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSubWebs.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSubWebs.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell

@VesaJuvonen Would you like me to open this in the SharePoint repo?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @stuck-on-starting **Thanks for your feedback**.

I tested the described scenario on my lab and can confirm that _includes_ is available:

(GET-Command Get-PnPSubWebs).parameters

```
Key                 Value
---                 -----
Identity            System.Management.Automation.ParameterMetadata
Recurse             System.Management.Automation.ParameterMetadata
Web                 System.Management.Automation.ParameterMetadata
Connection          System.Management.Automation.ParameterMetadata
Verbose             System.Management.Automation.ParameterMetadata
Debug               System.Management.Automation.ParameterMetadata
ErrorAction         System.Management.Automation.ParameterMetadata
WarningAction       System.Management.Automation.ParameterMetadata
InformationAction   System.Management.Automation.ParameterMetadata
ErrorVariable       System.Management.Automation.ParameterMetadata
WarningVariable     System.Management.Automation.ParameterMetadata
InformationVariable System.Management.Automation.ParameterMetadata
OutVariable         System.Management.Automation.ParameterMetadata
OutBuffer           System.Management.Automation.ParameterMetadata
PipelineVariable    System.Management.Automation.ParameterMetadata
Includes            System.Management.Automation.ParameterMetadata
```

I could also use it:

```
Get-PnPSubWebs -Recurse -Includes "WebTemplate","Description" | Select ServerRelativeUrl, WebTemplate, Description

ServerRelativeUrl       WebTemplate Description
-----------------       ----------- -----------
/sites/lpsite/sub1 STS
/sites/lpsite/sub  STS
```

Please be sure to run the last updated version of PnP modules.

Hope this information has helped you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @stuck-on-starting 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
