### ISSUE TITLE
RequireWIFIForIPAudio

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/office-docs-powershell#2185]
Apparently the RequireWIFIForIPAudio parameter was deprecated from version 6.0.9319.534.
The top part of the documentation reflects this, but the parameter is still mentioned in the parameter description later in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1886f463-a9a3-d9d6-b368-2bf11c66832e
* Version Independent ID: 5935451c-1f89-93a8-7cd6-9b7c20426596
* Content: [New-CsMobilityPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csmobilitypolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsMobilityPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsMobilityPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
Hi @donlassini , thank you for your feedback.

It was not depreciated, on the contrary, please check the following link:
https://support.microsoft.com/en-us/help/4132310/requirewififoripaudio-isn-t-applied-for-skype-for-business-ios-android

**Comment by yogkumgit** [comment]
PR:  https://github.com/MicrosoftDocs/office-docs-powershell/pull/2682
