### ISSUE TITLE
Please add details regarding rule conditions and exceptions to the article.

### ISSUE THREAD

**Issue by VishalTSP** [MicrosoftDocs/office-docs-powershell#2186]
Please add details regarding rule conditions and exceptions to the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceeb00d4-65da-0ea5-8089-f16a2f348eb7
* Version Independent ID: 0f4286f0-13dc-0f83-3943-4c51fd715f94
* Content: [Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@VishalTSP, the [New-TransportRule](https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance/new-transportrule) and [Set-TransportRule](https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance/set-transportrule) topics are as detailed as thye're going to get, unless you have comments about missing parameters, or specific parameter descriptions that are incomplete or contain errors.

The "regular" topic (which is much more in-depth and easier to read) is here: [Mail flow rule conditions and exceptions (predicates) in Exchange Online](https://docs.microsoft.com/Exchange/security-and-compliance/mail-flow-rules/conditions-and-exceptions).
