### ISSUE TITLE
More Details

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/office-docs-powershell#2188]
Both these must be true to be effective
-DeclineEventsForScheduledOOF $true -DeclineAllEventsForScheduledOOF $true 

These are all required to decline future events
-AutoDeclineFutureRequestsWhenOOF $true -DeclineMeetingMessage "oof cant book" -CreateOOFEvent $true -OOFEventSubject   "oof cant book" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3aa0b9-dbc1-075e-901f-fa091ceff700
* Version Independent ID: f764ed33-552b-d2b6-6089-f01fcd91c19d
* Content: [Set-MailboxAutoReplyConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailboxautoreplyconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-MailboxAutoReplyConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-MailboxAutoReplyConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws306** [comment]
Hi @stephenc01, thank you for your feedback.

DeclineEventsForScheduledOOF should be used with EventsToDeleteIDs or DeclineAllEventsForScheduledOOF, both are mutually exclusive. I think it's well explained in the article. Also there are more conditions explained in the article.

Set DeclineMeetingMessage when you use AutoDeclineFutureRequestsWhenOOF is optional, the same apply for CreateOOFEvent and OOFEventSubject. I think it's explained in the article.

**Comment by dariomws306** [comment]
All of them requiere that AutoReplyState parameter is set to Scheduled.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @stephenc01 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @stephenc01 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
