### ISSUE TITLE
Get-Team is blank or not showing all groups

### ISSUE THREAD

**Issue by kf4ape** [MicrosoftDocs/office-docs-powershell#219]
I have seen something with get-teams similar to my interactions with PowerBI. if the powershell user is NOT a member of the group, they can not see the group when executing get-team or adjusting it, even as a global admin. sort of defeats the purpose of powershell for automating groups. Granted I can use unified group commands to gather members, etc, but if I wanted to troubleshoot, look at settings in the groups or reset select settings due to HR or other reasons, I am sorta of screwed

**Comment by kenwith** [comment]
@kf4ape - thank you for submitting this for the beta cmdlets. It is highly appreciated and I know for a fact @islubin tracks and views this feedback and directly incorporates it into the product so the general release will be the best it has ever been. I am not sure on an answer right now so will leave this issue open and update as I can from product team.

**Comment by islubin** [comment]
@kf4ape, tank you for your feedback - we appreciate it!.  This is a known limitation of the Beta cmdlets and is something we're working to change in the upcoming releases.

**Comment by kf4ape** [comment]
Awesome! thanks guys
