### ISSUE TITLE
Cmdlets for Bots and Apps integration in Teams?

### ISSUE THREAD

**Issue by kzuenkler-avanade** [MicrosoftDocs/office-docs-powershell#2193]
Cmdlets for Bots and Apps integration in Teams?
I am still missing cmdlets to add new bots into teams. What are the plans to integrate this?

**Comment by msbemba** [comment]
Currently, the Cmdlets are not included in the module 0.9.6. We shall update you once there are plans for integration.

**Comment by yogkumgit** [comment]
@kzuenkler-avanade   Thank you very much for your kind feedback. Considering your valuable feedback, we have logged this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

User Voice Link: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33715255-bot-capability
