### ISSUE TITLE
Use a list of specific users - Error in script

### ISSUE THREAD

**Issue by ToughItOut** [MicrosoftDocs/office-docs-powershell#2196]
The command used to loop through each user throws an error related to Identity:
"Cannot bind argument to parameter 'Identity' because it is null."

Listed above:
$NPS | foreach {Set-User -Identity $_.MicrosoftOnlineServicesID -RemotePowerShellEnabled $false}

I believe it should be:
$NPS | foreach {Set-User -Identity $_ -RemotePowerShellEnabled $false}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d193a89-ffbc-90ab-990e-0e36b7845496
* Version Independent ID: 12a028e5-d1ce-12ab-2da8-c46d4815754c
* Content: [Enable or disable access to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/disable-access-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/disable-access-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/disable-access-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ToughItOut, OK, I'll change it, but I tested it based on this [Issue](https://github.com/MicrosoftDocs/office-docs-powershell/issues/2106) and using -Identity $_.MicrosoftOnlineServicesID worked for me then.

**Comment by ToughItOut** [comment]
Thanks! I think it only applies to the "Use a list of specific users" section because we are loading a list of account names (email addresses) as the identity from the text file, so it is specifically set, versus the other scenarios where we are capturing the account in a variable in a previous step via the get-user command.
