### ISSUE TITLE
move-spuser windows claims example needed

### ISSUE THREAD

**Issue by tomresing** [MicrosoftDocs/office-docs-powershell#221]
@tseward pointed out this comment could be applied, with some refinement:

> If your site uses CLAIMS based authentication you MUST include the i:0#.w| when referencing usernames and enclose in quotes
> Also - at least on our site - you CANNOT use -Identity "DOMAIN\USERNAME"
> 
> -Identity requires an SPUser object.
> 
> Here is the CORRECT method - again, at least what works for us:
> 
> $user = Get-SPUser -web siteurl "i:0#.w|domain\username"
> Move-SPUser -Identity $user -NewAlias "i:0#.w|domain\username" -IgnoreSID

**Comment by kenwith** [comment]
Thanks @tseward and @tomresing  for opening this issue and providing this feedback to make the docs better. @Techwriter40 - do you know who we could confirm to put this in as an example to the *-SPUser cmdlets?

**Comment by tomresing** [comment]
Hi @kenwith, I forgot to mention that @tseward agreed to update and test the script and submit as a pull request.

**Comment by kenwith** [comment]
That would be awesome! I will look for the pull request. For quick start guide be sure to check README. Thanks!

**Comment by tseward** [comment]
PR #222 submitted for this.

**Comment by VesaJuvonen** [comment]
Closing as fixed with #222.
