### ISSUE TITLE
SPO / PNP change site url?

### ISSUE THREAD

**Issue by AlexRademeyer** [MicrosoftDocs/office-docs-powershell#2212]
Hi,

I have tried to change a site URL using SPO and PNP cmdlets but I have not been successful.
Based on the errors I see it seems like this function might not even be supported in Sharepoint Online.

Can anyone confirm?

If this is possible, does anyone have the verbs/ syntax to be used?

Thanks

**Comment by VesaJuvonen** [comment]
Changing an URL for the existing site is not yet supported. This capability is planned to get released during 2019.

**Comment by AlexRademeyer** [comment]
hey! Thanks for your feedback, can you confirm if this is released yet?
Thanks

**Comment by AlexRademeyer** [comment]
hey! Thanks for your feedback, can you confirm if this is released yet? 
Or a release date? 
Not sure why this is closed unless it has been solved (i.e. released).
Thanks

**Comment by get-itips** [comment]
Hello, as @VesaJuvonen said, this functionality is not yet available.
Documentation will be available once it is released.
Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @AlexRademeyer Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by AlexRademeyer** [comment]
Hello.
No?
It's not helpful at all? Since it is not a solution or an explanation.

but keeping this issue alive is not helping anyway. 
I just hope i hear about it when this functionality is released (hopefully 2019 is still the right year.).

**Comment by kenwith** [comment]
@trent-green is the PM that owns this and maybe he can give us more information. He did let @get-itips know that it is not yet available but I agree with @AlexRademeyer that it would be nice to have more information since we are already well into August of 2019.

@trent-green - can you give us any more info? :)

**Comment by trent-green** [comment]
@kenwith all we can say is sometime during Q3 2019
