### ISSUE TITLE
View user's TeamsUpgradePolicy

### ISSUE THREAD

**Issue by mike-yam** [MicrosoftDocs/office-docs-powershell#2220]
"Grant-CsTeamsUpgradePolicy -PolicyName IslandsWithNotify -Identity mike@contoso.com" works perfectly. However, how can we get the user's existing TeamsUpgradePolicy during phased approach?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0dd44c-bfc9-5f82-68c4-7b469129e8a5
* Version Independent ID: ea015ee3-54e2-e402-d533-c8a9a15557e8
* Content: [Grant-CsTeamsUpgradePolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsupgradepolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by Mitch-P97** [comment]
Mike, Any word?  I, too, would like to be able to run reports and manage deployment intelligently.

**Comment by j0rt3g4** [comment]
Thank you very much for reporting this query @mike-yam .
I agree that you will get the information you want using the @midiman369 code.

Additionally you can get the output on CSV or Html format,

```
#For CSV
$objUsers = Get-CSOnlineUser | select UserPrincipalName, teamsupgrade*
$objusers | ConvertTo-Csv -NoTypeInformation | Out-File "$env:USERPROFILE\desktop\TeamsUpgrade.csv"
```

```
#ForHtml
$objUsers = Get-CSOnlineUser | select UserPrincipalName, teamsupgrade*
$objusers | ConvertTo-Html | Out-File "$env:USERPROFILE\desktop\TeamsUpgrade.html""

```
This will create an  HTML  file on the Desktop of the current user with the name "TeasUpgrade.html"
