### ISSUE TITLE
information missing

### ISSUE THREAD

**Issue by JoshJ-MSFT** [MicrosoftDocs/office-docs-powershell#2221]
I'm looking at the .chm file from lync 2013 and even it has this:  Who can run this command?

Who can run this cmdlet: By default, members of the following groups are authorized to run the Update-CsAddressBook cmdlet locally: RTCUniversalUserAdmins, RTCUniversalServerAdmins. To return a list of all the role-based access control (RBAC) roles this cmdlet has been assigned to (including any custom RBAC roles you have created yourself), run the following command from the Windows PowerShell prompt:

Get-CsAdminRole | Where-Object {$_.Cmdlets –match "Update-CsAddressBook"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5e9e230-71c0-f3c2-066c-897d144d0f3c
* Version Independent ID: 503cd60a-ecd2-d76f-61d5-14a0df80ba34
* Content: [Update-CsAddressBook (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/update-csaddressbook?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Update-CsAddressBook.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Update-CsAddressBook.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@JoshJ-MSFT - this is great info. Please feel free to submit a Pull Request to add to the appropriate docs. Guidance on creating a PR in the README in the root of the source repo: https://github.com/MicrosoftDocs/office-docs-powershell

**Comment by JoshJ-MSFT** [comment]
I'm confused.  This information used to be in our documentation.  Then it got removed.  Why do I have to jump through some hoop to get it back?  Isn't that what you guys do?
