### ISSUE TITLE
Returns All Teams

### ISSUE THREAD

**Issue by jennabourgeois** [MicrosoftDocs/office-docs-powershell#2222]
This cmdlet does not seem to be working.  I execute it by passing a guest account and it returns every team in our system.  Since I only added the guest to one team, I sure hope that they do not have access to every one of my teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8450991f-9f85-4d87-51b3-efa8e1004a24
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by Mike-Crowley** [comment]
That's pretty dumb. What is the point of a parameter that ignores the value. Furthermore, it seems very unlikely someone with the wherewithal to use PowerShell against their tenant, simply wants to know what teams they are personally a member of.

**Comment by msbemba** [comment]
@Mike-Crowley  Thank you for your feedback. We did a test with the latest teams module (0.9.6) and it looks like it is working as expected. Wherein, Get-team provides all teams that are present in the tenant and get-team -user abcd@contoso.com provides all teams that the user abcd@contoso.com is a member of. I will be updating the document shortly with accurate information.

**Comment by msbemba** [comment]
Created PR# https://github.com/MicrosoftDocs/office-docs-powershell/pull/2918 for changes in the document.

**Comment by yogkumgit** [comment]
@kenwith Please merge this PR if you find it suitable

**Comment by tonerz82** [comment]
This still not working with version 1.0.0.  The command returns all Teams after specifying a user in the user parameter.  I posted this issue on the community forum here:
https://techcommunity.microsoft.com/t5/Microsoft-Teams/Get-Team-User-PowerShell-for-Teams/m-p/501790#M30709
