### ISSUE TITLE
-Server switch

### ISSUE THREAD

**Issue by rtpcrew** [MicrosoftDocs/office-docs-powershell#2223]
Attempted to use the -Server switch on Exchange 2016 CU11 and it did not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf6e1bcc-a2b8-fa56-220b-c1366342004e
* Version Independent ID: 5c8a40b9-7aa5-c2e1-88e4-6ade4b1d3386
* Content: [New-OfflineAddressBook (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/email-addresses-and-address-books/new-offlineaddressbook?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/email-addresses-and-address-books/New-OfflineAddressBook.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/email-addresses-and-address-books/New-OfflineAddressBook.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rtpcrew, the parameter description says "This parameter is available or functional only in Exchange Server 2010." and the Applicable: tag only has the value Exchange Server 2010.

So, the parameter is only available in Exchange 2010.
