### ISSUE TITLE
Admin roles

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/office-docs-powershell#2224]
Folks, can you please update the documentation with the correct list of Admin roles required to run this cmdlet. For the record, Get-CsAdminRole is NOT available for SfBO and we cannot use the example given:

Get-CsAdminRole | Where-Object {$_.Cmdlets -Match "\&lt;DesiredCmdletName\&gt;"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c152757-94e4-ddb4-6322-9dadc33b130d
* Version Independent ID: 3292ae2d-f7e6-ef13-9287-de083147a1cd
* Content: [Get-CsUserSession (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csusersession?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsUserSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsUserSession.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by get-itips** [comment]
Hi @michevnew thanks for your comments and suggestions! We really appreciate them.

It's true that Get-CsAdminRole is not present in SFBO, I'll update the documentation to reflect this.

Answering your question, you need to be a Skype For Business Admin to run Get-CsUserSession, you could also run that command using other roles that include it, please see https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide#what-can-the-office-365-admin-roles-do-in-exchange-online-sharepoint-online-and-skype-for-business-online

Hope this information was helpful.

Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @michevnew  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
