### ISSUE TITLE
Sample incorrect

### ISSUE THREAD

**Issue by sottenad** [MicrosoftDocs/office-docs-powershell#2225]
The samples list the -OriginScope parameter, which is no longer accepted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae8029d-a9b9-f522-65f4-b0afb0a3399a
* Version Independent ID: b9c6a1d5-40f2-098c-372b-55ed3a1756bb
* Content: [Remove-SPOTenantCdnOrigin (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spotenantcdnorigin?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantCdnOrigin.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantCdnOrigin.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by VesaJuvonen** [comment]
Fixed with the #2490 changes.
