### ISSUE TITLE
New-SPOPublicCdnOrigin vs Add-SPOTenantCdnOrigin

### ISSUE THREAD

**Issue by sottenad** [MicrosoftDocs/office-docs-powershell#2226]
Is New-SPOPublicCdnOrigin effectively the same as Add-SPOTenantCdnOrigin with the -CdnType set to Public?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94777b17-c20f-7255-6eba-3b627af18d33
* Version Independent ID: 260314aa-c449-08c9-abc0-b98ab4ac030a
* Content: [New-SPOPublicCdnOrigin (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/new-spopubliccdnorigin?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/New-SPOPublicCdnOrigin.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/New-SPOPublicCdnOrigin.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by VesaJuvonen** [comment]
Yes. That's exactly what it is. Technically it's "left-overs" from the time before -CdnType was introduced.
