### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#2230]
where can we find the log of changes to the SPO cmdlets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65bf2c0b-b0ec-2748-e47e-af66011efe30
* Version Independent ID: be3968f4-d766-0b45-384b-c51c47328a86
* Content: [SharePoint Online PowerShell](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by kenwith** [comment]
@DeanGross - you can see the history on the GitHub file. It tracks every commit and merge. This applies for the repo as a whole and also each individual file. To see the history for a specific file, navigate to that file in the GitHub repo (tip, if you are looking at the file on docs.microsoft.com then you can click the Edit button in upper right of page to go directly to GitHub source) and then click the History button. You will see all of the commit history and can click and see changes. There are different views to see the changes but the one I prefer shows red for removed text and green for added text.

Here are some references:
https://help.github.com/articles/differences-between-commit-views/
https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History
