### ISSUE TITLE
-ReportOnly information is a little sparce

### ISSUE THREAD

**Issue by DougChandler** [MicrosoftDocs/office-docs-powershell#2232]
For -ReportOnly, why is this returned as encoded strings? This requires different handling from -IncludeReport.
What encoding is used? Base64?
Could more information please be added for this option so that we can code against it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549910d8-771a-2c38-c750-77f563b54878
* Version Independent ID: b956cdcb-3c3b-edd3-80b1-9573128a7414
* Content: [Get-MoveRequestStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/get-moverequeststatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/Get-MoveRequestStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/Get-MoveRequestStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DougChandler here's the only additional information I was able to find:

When -ReportOnly is specified, the cmdlet will actually *NOT* output the RequestStatistics object. 
It will only output the list of report entries, which can then be attached to another separately loaded
RequestStatistics object like this:

```
$r = Get-MoveRequestStatistics $id
$reportEntries = Get-MoveRequestStatistics $id -ReportOnly
$r.PopulateReport($reportEntries)
```

But that code snippet returns no results (I replaced ID with the name of a mailbox from Get-MailboxMove).

**Comment by DougChandler** [comment]
I can get the -ReportOnly to return string data, but I cannot get it to decode without knowing how it is encoded. I have tried Base64 / Unicode / ASCII / etc, but cannot get it to show the report data.
I just need to know how it is encoded.

**Comment by chrisda** [comment]
@DougChandler, apparently this parameter isn't meant to be available to the general public. I've changed the description to say "reserved for internal Microsoft use". Sorry for the confusion.
