### ISSUE TITLE
Optional parameter "filter"

### ISSUE THREAD

**Issue by gerickes** [MicrosoftDocs/office-docs-powershell#2233]
It could be helpful to mention on which property I can use the "filter" parameter. For excample it won't work for the property "SharingCapability".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fbda735-74ec-2f4e-9c75-dd133e87320e
* Version Independent ID: 599c8c2e-6e02-f27f-1009-2640296d5d10
* Content: [Get-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Thanks for your comment @gerickes I'll update the document based on it.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @gerickes Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by michevnew** [comment]
So I still dont see any list of properties we can use with Filter, why was this closed? Can we please get the list of available properties added? And maybe remove the text about -filter being not functional.

**Comment by kenwith** [comment]
@michevnew - re-opened and we can ask @get-itips if he would be able to provide a link to the PR to resolve the issue. We can use this same issue to update doc based on your feedback too. Thanks for taking the time to contribute areas for improvement.

**Comment by kenwith** [comment]
Also, @trent-green owns SharePoint Online PowerShell so looping him in here too.

**Comment by ringsaroundus** [comment]
The filter documentation is still not updated.    You need to use the proper format when filtering.

Get-SPOSite -Filter {Owner -eq "owner@google.com"} 

It should work with these properties
LastContentModifiedDate
Status
ResourceUsageCurrent
ResourceUsageAverage
StorageUsageCurrent
LockIssue
WebsCount
CompatibilityLevel
Url
LocaleId
LockState
Owner
StorageQuota
StorageQuotaWarningLevel
ResourceQuota
ResourceQuotaWarningLevel
Template
Title
AllowSelfServiceUpgrade
DenyAddAndCustomizePages
SharingCapability

**Comment by get-itips** [comment]
Hello everyone,
Some months ago I added [this commit](https://github.com/MicrosoftDocs/office-docs-powershell/commit/75eb00645cb6fd006d091ad5a57f7c5fd9b90542) about Filter parameter not being functional at the time, will revisit this to see if it has changed since then.

**Comment by yogkumgit** [comment]
@tseward Please review this PR #4828

**Comment by tseward** [comment]
@yogkumgit looks like that PR was already merged.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @gerickes Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ravick4u** [comment]
I tried Get-SPOSite -Filter {Title -like "test"} and it gives me an error message "Filtering is not supported for property Title." Am I missing something ?

**Comment by get-itips** [comment]
> I tried Get-SPOSite -Filter {Title -like "test"} and it gives me an error message "Filtering is not supported for property Title." Am I missing something ?

Yes. Title is not yet supported. 

> Currently, you can filter by these properties: Owner, Template, LockState, Url.
