### ISSUE TITLE
After using powershell to create a Team I am unable to create a plan

### ISSUE THREAD

**Issue by CombineLabs** [MicrosoftDocs/office-docs-powershell#2234]
After using PowerShell to create a Team I am unable to create a plan, I just upgraded to the latest version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94694082-c529-5654-1734-57514ec17a1f
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [Microsoft Teams PowerShell](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps#teams)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by DaanvanBeek** [comment]
Do you mean a Planner plan? In my experience adding a Planner Tab to a Team is not impacted by whether or not you created it through powershell.
If so, are you able to access the relevant SharePoint site?
If not, what do you mean exactly?

Best regards,

**Comment by Niekoesj** [comment]
Ha i had the same issue! No-one believed me... but the work-around is;
Do not add OWNERS... but madd the owner first as MEMBER and then re-run the command to change it to OWNER. :-) then the Planner/plans can be created!

**Comment by kf4ape** [comment]
Niekoesj, I had the same issue a few months ago and discovered a crazy work around...had a case with MS Premier for about amonth...they are aware of the bug and its pending release cycle (not in 0.9.6)...this also applies to groups in outlook also

Add-TeamUser -GroupId $groupid -User $Owner
Add-TeamUser -GroupId $groupid -User $Owner -Role Owner
remove-TeamUser -GroupId $groupid -User $Owner -Role Owner
Add-TeamUser -GroupId $groupid -User $Owner -Role Owner

**Comment by get-itips** [comment]
Hi @CombineLabs thanks for your comments,  I see that this wouldn't cause a change in any of the cmdlet's documentation.  @yogkumgit can you kindly help here?

**Comment by yogkumgit** [comment]
@CombineLabs  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
