### ISSUE TITLE
Cmdlet for creating school (AdministrativeUnit - EDU School)

### ISSUE THREAD

**Issue by ftunholm** [MicrosoftDocs/office-docs-powershell#2235]
Is there any plans to support creation of AdministrativeUnits but as EDU School type?

I have yet to find a way to do this in other powershell modules. There seems to be some special extension to AdministrativeUnit object type to make it an EDU School. If there is a workaround please tell.

**Comment by chrisda** [comment]
@ftunholm, is there a specific topic that you're asking about?

**Comment by chrisda** [comment]
@ftunholm, when you're talking about features or directions to fix or workaround something, you best bet is to open a support ticket. That gets your issue directly in front of people who can answer your questions and/or fix the problem.
