### ISSUE TITLE
Adjust the Antiphishfilterpolicy

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/office-docs-powershell#2236]
Hello,
I think that it would make sense to combine the articles:
https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/get-phishfilterpolicy?view=exchange-ps

https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-phishfilterpolicy?view=exchange-ps

My opinion is that they explain both for 50% how to adjust the SpoofAllowBlockList. This means that the following should be explained in one article:

First:
PS C:\&gt; $file = "C:\tmp\Summary Spoofed Internal Domains and Senders.csv"; Get-PhishFilterPolicy -Detailed -SpoofAllowBlockList -SpoofType Internal | Export-CSV $file
Described in: https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/get-phishfilterpolicy?view=exchange-ps

Second: 
Rename the file "Summary Spoofed Internal Domains and Senders.csv" to: Spoofed Senders.csv 
Edit the file and remove the entry for Google.com *
Then run:
PS C:\&gt; Get-PhishFilterPolicy -Detailed -SpoofAllowBlockList | Export-CSV "C:\tmp\Spoofed SendersEhlo.csv"; $UpdateSpoofedSenders = Get-Content -Raw "C:\tmp\Spoofed Senders.csv"; Set-PhishFilterPolicy -Identity Default -SpoofAllowBlockList $UpdateSpoofedSenders​
Described in: https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-phishfilterpolicy?view=exchange-ps

Third: To check the results:
Get-PhishFilterPolicy -SpoofAllowBlockList -Detailed

Thanks
jedronke@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad1f9b3-c2d8-042a-86e3-9af5673c5d9f
* Version Independent ID: 64d6d41e-9161-82ea-9e2b-9a31d8625630
* Content: [Set-PhishFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-phishfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Set-PhishFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Set-PhishFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeroenDronkers, each cmdlet is documented separately because of PowerShell help at the command line (Get-Help <CmdletName>). There are other instances where a cmdlet depends on the output of another cmdlet to work correctly.

Thanks for the feedback.
