### ISSUE TITLE
Example 2 - missing Identity

### ISSUE THREAD

**Issue by gminer485** [MicrosoftDocs/office-docs-powershell#2239]
Example 2 should be $UserList = Get-CASMailbox -Filter {HasActiveSyncDevicePartnership -eq $true -and -not DisplayName -like "CAS_{*"} | Get-Mailbox; $UserList | foreach {Get-MobileDeviceStatistics -Mailbox $_.Identity}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75cc24b8-6540-468b-8f26-cab48d090a1d
* Version Independent ID: bb330fd2-9aa6-e9fd-beee-184b1c0a1d80
* Content: [Get-MobileDeviceStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/get-mobiledevicestatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/devices/Get-MobileDeviceStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/Get-MobileDeviceStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gminer485, I updated the topic.

Remember, this is GitHub, so [you can update the topic](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md) directly from the web (it's more like a _request_ to update, which goes live after it's approved).

Thanks for the feedback.
