### ISSUE TITLE
Ex2019

### ISSUE THREAD

**Issue by chrisreboot** [MicrosoftDocs/office-docs-powershell#2253]
parameter -UnScopedTopLevel appears to be missing in Exchange 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aad91a-004d-a2bc-660b-eab1f7f95c76
* Version Independent ID: d084f4fc-2742-9363-1c7d-ed3dbc84af8a
* Content: [New-ManagementRole (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/role-based-access-control/new-managementrole?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/role-based-access-control/New-ManagementRole.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/role-based-access-control/New-ManagementRole.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@chrisreboot from the parameter description in the topic:

By default, this parameter is only available in the UnScoped Role Management role, and that role isn't assigned to any role groups. To use this parameter, you need to add the UnScoped Role Management role to a role group (for example, to the Organization Management role group). For more information, see the "Add a role to a role group" section in Manage role groups (https://technet.microsoft.com/library/jj657480.aspx).

I confirmed by running this command on an Exchange 2019 server:

```
Get-ManagementRoleEntry *\New-ManagementRole -Parameters UnscopedTopLevel
```
