### ISSUE TITLE
Export-PnpTaxonomy not working for SharePoint 2013 Onpremise while exporting term store to a text file

### ISSUE THREAD

**Issue by adarshawasthi** [MicrosoftDocs/office-docs-powershell#2257]
Export-PnpTaxonomy not working while exporting term store to a text file. It was working 2 days ago

**Comment by adarshawasthi** [comment]
#2084

**Comment by AndreaBarr** [comment]
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell

@VesaJuvonen Would you like me to open this in the SharePoint repo?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @adarshawasthi 
Thanks for your feedback.
I tested in my lab and had no issues exporting to a file.
Please be sure you are running the latest version of the PnP module.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @adarshawasthi 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
