### ISSUE TITLE
EnableAssignedConferenceType 

### ISSUE THREAD

**Issue by sischanz** [MicrosoftDocs/office-docs-powershell#2261]
EnableAssignedConferenceType is not valid for Skype for Business Online. I tested it on my lab tenant with the following result:
Set-CsMeetingConfiguration -EnableAssignedConferenceType $True
You are not permitted to invoke Set-CsMeetingConfiguration with the following parameters:
 EnableAssignedConferenceType
    + CategoryInfo          : NotSpecified: (:) [Set-CsMeetingConfiguration], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.Rtc.Management.Internal.SetHostedMeetingConfiguration
   Cmdlet
    + PSComputerName        : admin2e.online.lync.com

Some colleagues pointed me to the following page, that seems to be related to this:
https://docs.microsoft.com/en-gb/skypeforbusiness/audio-conferencing-in-office-365/reset-a-conference-id-for-a-user#feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7d9d1da-e548-5f48-b0b1-18ef69c0caac
* Version Independent ID: 2f967ff1-cb4f-2394-cf10-ed8f5188a0c6
* Content: [Set-CsMeetingConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csmeetingconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsMeetingConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsMeetingConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by EvgenyArtemyev** [comment]
I've got the same issue

**Comment by EvgenyArtemyev** [comment]
I do believe the property is not available for SfB Online.

**Comment by yogkumgit** [comment]
@sischanz and @EvgenyArtemyev  Expert has looked into the issue and PR is created for updating the documentation. Thanks for raising this issue. Will appreciate your contribution in the future as well.

**Comment by kenwith** [comment]
@yogkumgit - can we get a link to the PR too?  When you paste the link in here or in the Issue then GitHub will automatically link them.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @sischanz  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
