### ISSUE TITLE
Clarity for the -Alias parameter in New-Team cmdlet

### ISSUE THREAD

**Issue by veronicageek** [MicrosoftDocs/office-docs-powershell#2263]
By running the **Get-Help New-Team -Full** in PowerShell, and referring to the `-Alias` parameter, the output says different from the docs.
The output in PowerShell says "*Same as displayName without any spaces. Team Alias Characters Limit - 64*". But the docs say it only has to be a unique name (re O365 Group in the background).

I had a look at the #1796, however, it would mean that it only has to be unique, AND NOT be mandatory for it to be the DisplayName w/o spaces then?

Can we get some clarity?
Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-gb/powershell/module/teams/New-Team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
Hi @veronicageek , thank you for your contribution.

I think someone update the description of this parameter:
"The Alias parameter specifies the alias for the associated Office 365 Group. This value will be used for the mail enabled object and will be used as PrimarySmtpAddress for this Office 365 Group. The value of the Alias parameter has to be unique across your tenant.
For more details about the naming conventions see here: New-UnifiedGroup, Parameter: -Alias."

Conclusion: Alias hast to be unique across tenant and it could be different to DisplayName.

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and sharing this explanation. @veronicabeek
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
