### ISSUE TITLE
The remote server returned an error: (401) Unauthorized

### ISSUE THREAD

**Issue by spjeff** [MicrosoftDocs/office-docs-powershell#2264]
NOTE 1 - Be sure to connect with "https://tenant-admin.sharepoint.com" URL context aand upload to "Documents" library here within Admin site.

Attempting to open context to root admin "https://tenant.sharepoint.com" will give error:
New-PnPUPABulkImportJob: The remote server returned an error: (401) Unauthorized

NOTE 2 - Be sure to use connection type "TenantAdmin" (automatically set when opening "-admin" URL)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d731745-680b-fe7d-78fc-6757460f67b3
* Version Independent ID: 17045452-597a-b77e-897d-8af47dfae727
* Content: [New-PnPUPABulkImportJob (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpupabulkimportjob?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPUPABulkImportJob.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPUPABulkImportJob.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr I put in a fix for this as well.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @spjeff 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
