### ISSUE TITLE
Examples have not been provided

### ISSUE THREAD

**Issue by eric-lavalley** [MicrosoftDocs/office-docs-powershell#2267]
It does not appear that the Examples section of this document have been populated. They appear to still contain the text of the document template. Currently, Example 1 says "Insert example commands for example 1."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b13225c6-1dc5-0ece-2c49-d316c67b1fce
* Version Independent ID: 0819916a-a6d4-eda2-d2cd-46eb82aa2796
* Content: [Get-DlpSiDetectionsReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/get-dlpsidetectionsreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpSiDetectionsReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpSiDetectionsReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@eric-lavalley. OK. Examples added.

Thanks for the feedback.
