### ISSUE TITLE
error on performanceLevel parameter

### ISSUE THREAD

**Issue by rg54** [MicrosoftDocs/office-docs-powershell#2272]
Hello,

It seems to have an error concerning "PerformanceLevel" parameter, because according to this page, "Reduced" and "Maximum" modes have the same number of threads ("Total number of threads = number of processors" in the 2 cases), which is illogical.

This other article give other values :
https://blogs.msdn.microsoft.com/sambetts/2013/11/05/changing-indexer-performance-setting-in-sharepoint-20102013/

And the most important value influenced by this parameter ("Max Threads/host") is not detailed for all the cases.

Thanks in advance for correction.
Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e31f1b9-b0a1-ed2e-c0df-abdff22ea0e8
* Version Independent ID: 2bf1bd67-9a2f-d122-f184-3308a6ba5226
* Content: [Set-SPEnterpriseSearchService (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spenterprisesearchservice?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPEnterpriseSearchService.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPEnterpriseSearchService.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr I put in a fix for this one.
