### ISSUE TITLE
Importing only certain command and not all of the cmdlets

### ISSUE THREAD

**Issue by tomgold182** [MicrosoftDocs/office-docs-powershell#2273]
Hi all , when I am performing 
```
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://<ServerFQDN>/PowerShell/ -Authentication Kerberos -Credential $UserCredential
```
I am getting all 713 cmdlets of the exchange mgmt server.
What should I to if i want to import only 1 or 2 cmdlets?

**Comment by chrisda** [comment]
@tomgold182 from the documentation for the [Import-PSSession](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/import-pssession) command, you can apparently specify the cmdlets you want using a variety of methods. So you run:

```
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://<ServerFQDN>/PowerShell/ -Authentication Kerberos -Credential $UserCredential
```

and then in the next command, you specify the cmdlets you want:

```
Import-PSSession $Session -DisableNameChecking -Commands "Cmdlet1","Cmdlet2"...
```

The $Session command just connects you to the server; the Import-PSSession command is what gives you the cmdlets.
