### ISSUE TITLE
Set-PnPDefaultColumnValues - Multiple Fields, Same Folder

### ISSUE THREAD

**Issue by nattomatto** [MicrosoftDocs/office-docs-powershell#2276]
In looking at the client_LocationBasedDefaults.html, for a manually set folder, the defaults are set as multiple DefaultValues in the same folder e.g.:
`<a href="/sites/appdev/nfmt/Two%20Default%20Spike/Manual%20Entry"><DefaultValue FieldName="Column1">Manual Column1 Value</DefaultValue><DefaultValue FieldName="Column2">Manual Column2 Value</DefaultValue></a>`

However, using the Set-PnPDefaultColumnValues two commands must be used to make the settings on the proper folder.  This results in two, or more depending on the number of commands sent, the following in the client_LocationBasedDefaults.html is observed:
`<a href="/sites/appdev/nfmt/Two%20Default%20Spike/PS%20Entry"><DefaultValue FieldName="Column2">PS Column2 Value</DefaultValue></a>
<a href="/sites/appdev/nfmt/Two%20Default%20Spike/PS%20Entry"><DefaultValue FieldName="Column1">PS Column1 Value</DefaultValue></a>`

When dropping files in the library, it is observed that only the last value, the one that comes first in the list, is set.

**Comment by AndreaBarr** [comment]
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell

@VesaJuvonen Would you like me to open this in the SharePoint repo?

**Comment by nattomatto** [comment]
I put it there.  Thanks

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for reporting the issue in Sharepoint repository and linking here and also sharing this explanation. @nattomatto  Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
