### ISSUE TITLE
New-PnPSite -Url parameter

### ISSUE THREAD

**Issue by Leif-Frederiksen** [MicrosoftDocs/office-docs-powershell#2283]
I cannot get the -url parameter to work:
New-PnPSite : A parameter cannot be found that matches parameter name 'Url'. I have version 3.4.1812.2.

Using -alias is not good for me, since I want some sites to be created as https://tenant/sites/site name and others as https://tenant/teams/site name

I had hoped for -url in order to accomplish this dynamic setup. Any ideas on how to make it happen?

Regards
Leif

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5e3530-a63e-71ce-97c8-c904619aafa8
* Version Independent ID: 2c961b64-5c27-6331-b704-716ccfb8c5a7
* Content: [New-PnPSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by henrycollet** [comment]
The behaviour is inconsistent. For Communication sites use the -Url parameter with the full url ie. https://tenant.sharepoint.com/sites/contoso
For Team sites use the -Alias parameter i.e. contoso. The /sites/ or /teams/ url part is then defined by the policy as per the SharePoint Admin settings
Oh, and -SiteDesign doesn’t work for Team sites...

**Comment by henrycollet** [comment]
As a follow-up, Communication sites are always under /sites/; Team sites can be /sites/ or /teams/ dependant on policy. If you want some Teams sites as /sites/ and some as /teams/ you'd have to keep switching the policy.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Leif-Frederiksen How are you?
Thanks for your feedback.
I can confirm that, currently, _Url_ parameter only works for Communication type sites, and _Alias_ only works for Modern Team Sites, you can conclude this looking at the examples that are provided in the article.
Also, article has been updated since the time you submitted this issue and you maybe want to take a look at it now.

Besides that, I will create a PR to improve the article clearly stating this limitations.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Leif-Frederiksen Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
