### ISSUE TITLE
Undo Grant-CsTeamsUpgradePolicy for a user

### ISSUE THREAD

**Issue by scporse** [MicrosoftDocs/office-docs-powershell#2284]
I ran Grant-CsTeamsUpgradePolicy -PolicyName UpgradeToTeams -Identity &lt;myself&gt;
How do I undo this / revert my user to the global csteamsupgradepolicy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0dd44c-bfc9-5f82-68c4-7b469129e8a5
* Version Independent ID: ea015ee3-54e2-e402-d533-c8a9a15557e8
* Content: [Grant-CsTeamsUpgradePolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsupgradepolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by cjwolford** [comment]
Will it let you set the policy with Grant-CsTeamsUpgradePolicy -PolicyName $Null and thus inherit the tenant setting?

**Comment by midiman369** [comment]
@cjwolford

Yes, this appears to work.

**Comment by msbemba** [comment]
Added an example Cmdlet to the doc which illustrates how to revert changes made to a single user., thus inheriting the tenant setting. Created PR # https://github.com/MicrosoftDocs/office-docs-powershell/pull/2854
