### ISSUE TITLE
Get-ActiveSyncDeviceStatistics Error on example 3

### ISSUE THREAD

**Issue by HareBear** [MicrosoftDocs/office-docs-powershell#2304]
$UserList = Get-CASMailbox -Filter {HasActiveSyncDevicePartnership -eq $true -and -not DisplayName -like "CAS_{*"} | Get-Mailbox $UserList | foreach {Get-ActiveSyncDeviceStatistics -Mailbox $_}

Gives me 
The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take
pipeline input.
    + CategoryInfo          : InvalidArgument: (xxxx/-U...ev/username:PSObject) [Get-Mailbox], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectNotBound,Get-Mailbox
    + PSComputerName        :servername.xxxxxxxx.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9d90b2-695e-59b0-92c2-ab9bcf43a78e
* Version Independent ID: 5647aff0-b7e9-a057-a63d-03b667a8c4b4
* Content: [Get-ActiveSyncDeviceStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/get-activesyncdevicestatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/devices/Get-ActiveSyncDeviceStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/Get-ActiveSyncDeviceStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@HareBear, the "|" before the Get-Mailbox command is a typo; it should be ";".

**Comment by javperx** [comment]
On this same command, I get this error
$UserList = Get-CASMailbox -Filter {HasActiveSyncDevicePartnership -eq $true -and -not DisplayName -like "CAS_{*"}; Get-Mailbox $UserList | foreach {Get-ActiveSyncDeviceStatistics -Mailbox $_}
Cannot process argument transformation on parameter 'Identity'. Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type 
"Microsoft.Exchange.Configuration.Tasks.MailboxIdParameter".
    + CategoryInfo          : InvalidData: (:) [Get-Mailbox], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-Mailbox
    + PSComputerName        : outlook.office365.com
