### ISSUE TITLE
Handlers switch could do with link to the list of available handlers

### ISSUE THREAD

**Issue by jimmywim** [MicrosoftDocs/office-docs-powershell#2338]
It'd be useful if there was a page that had the list of enum values for the -Handlers switch, with a brief description of what each handler will extract.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 451dc826-b072-5bcd-e98d-319ee82d73fe
* Version Independent ID: c0c6ad38-e86c-cd0c-ac01-033791404e25
* Content: [Get-PnPProvisioningTemplate (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPProvisioningTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPProvisioningTemplate.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell

@VesaJuvonen Would you like me to open this in the SharePoint repo?

**Comment by expiscornovus** [comment]
Had the same question and found this article. 

Just for the other people who end up in this thread via a search engine, the list of handlers can be found here:
https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/Model/Handlers.cs
https://techcommunity.microsoft.com/t5/SharePoint-Developer/Where-are-the-OOTB-Handlers-for-Get-PnPProvisioningTemplate/td-p/177815

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jimmywim thanks for your feedback.
I created a PR to improve the article adding a link to the Handlers enumeration.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @jimmywim Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
