### ISSUE TITLE
Update Description to include a note about requiring Enable-CsComputer to be run.

### ISSUE THREAD

**Issue by NicholasBurkhammer** [MicrosoftDocs/office-docs-powershell#2340]
Add note (this is confirmed via RFC to PG) in Description section (https://docs.microsoft.com/en-us/powershell/module/skype/set-csauthconfig?view=skype-ps#description) stating:

"Note:  After changing the CsAuthConfig, you must run Enable-CsComputer on each Skype for Business Server machine in order for the changes to take effect."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26656471-f4e4-3dbe-b915-5230400d7b7f
* Version Independent ID: 4dc006ee-6bf8-a929-94f7-499a5af1f7a1
* Content: [Set-CsAuthConfig (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csauthconfig?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsAuthConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsAuthConfig.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
@kenwith and @AndreaBarr  , we should close this.
