### ISSUE TITLE
Problem with switch OrganizationApp

### ISSUE THREAD

**Issue by mirkub2** [MicrosoftDocs/office-docs-powershell#2344]
According to this https://stackoverflow.com/questions/53833013/new-app-powershell-command-fails-on-exchange-online-if-organizationapp-property

this command returns error:
New-App -OrganizationApp -Url https://ManifestfileUrl/Manifest.xml -ProvidedTo SpecificUsers -UserList "some.users"

I can contact you with ISV, who detected, that this problem appeared last days.

**Comment by get-itips** [comment]
Hi @mirkub2 thanks for your comments and suggestion.

As the link you referenced, running this cmdlet now gives a message suggesting you need now to use Centralized Deployment cmdlets. https://docs.microsoft.com/en-us/office365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins#add-or-remove-users-from-an-add-in 

 If you need the app to be applied to every user in the Organization or Tenant, you could use the AssignToEveryone parameter with the value set to $true of Set-OrganizationAddInAssignments cmdlet.

Hope you find this information helpful. Thanks.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @mirkub2  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
