### ISSUE TITLE
More examples on Get-PnPSite

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#2346]
Please provide some examples of how to use the Includes parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 285bcd81-9af9-0d59-a080-30eb16f29b09
* Version Independent ID: 612198a1-9b84-18e7-d8bb-509eca30c8a1
* Content: [Get-PnPSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DeanGross Thanks for your feedback. I created a PR to improve the documentation of this cmdlet, based on your suggestion. Hope you find it useful.
Thanks again

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
