### ISSUE TITLE
-NewURL description

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#2348]
The description of the -NewURL param discusses changing the Language which does not seem correct. Please fix the description or the param name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2961cab8-c2d4-e90b-6d78-666a4dc16823
* Version Independent ID: d9e27a2c-8408-95ba-6d88-46e63fe878a1
* Content: [Set-PnPSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hi Dean thanks for your contribution, I reviewed the code behind this cmdlet and it has the same comment on the NewURL param, so it seems that is the root of this issue https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Site/SetSite.cs  I opened an issue there so when they correct the comment, we can fix on cmdlet doc https://github.com/SharePoint/PnP-PowerShell/issues/1810 @AndreaBarr

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
