### ISSUE TITLE
Disable Flows param

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#2349]
What kind of flows does this disable? is it MS Flows or classic SP Workflows? What is the user experience when this param set? does it hide the Flows button on the ribbons, do they get an error or warning?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2961cab8-c2d4-e90b-6d78-666a4dc16823
* Version Independent ID: d9e27a2c-8408-95ba-6d88-46e63fe878a1
* Content: [Set-PnPSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell

@VesaJuvonen Would you like me to open this in the SharePoint repo?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DeanGross how are you?
Here you might find the answers you are looking for about what type of Flows this parameter disables and the expected behaviour to the user:
https://social.technet.microsoft.com/wiki/contents/articles/39331.sharepoint-online-verifying-and-modifying-flows-policy-in-site-using-powershell.aspx

Hope this information helps you.

**Comment by DeanGross** [comment]
Thanks that is some good information. It seems to me that it should be incorporated into the docs site. Can this be done?

**Comment by get-itips** [comment]
Hello @DeanGross I created a PR to improve cmdlet's documentation based on your feedback.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
