### ISSUE TITLE
Placeholder text in add-spogeoadministrator

### ISSUE THREAD

**Issue by tomresing** [MicrosoftDocs/office-docs-powershell#235]
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spogeoadministrator?view=sharepoint-ps
has placeholder text like 
{{Fill in the Description}}
{{Fill in the Synopsis}} 
and 
{{ Add example description here }}

**Comment by nsshommo** [comment]
@tomresing Thanks for your feedback. We are working on this.

**Comment by kenwith** [comment]
An audit is currently underway for all Skype cmdlets along with adding missing content where found. I will continue on to SPO cmdlets after.

**Comment by AndreaBarr** [comment]
@tomresing Thank you for this feedback.

I am creating a backlog item for this for the PowerShell team so we can track to progress and get you updated once it's complete. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@tomresing Thank you for the feedback. The Placeholder text's have been replaced with accurate information pertaining to the document.

Thank you for reporting and making the docs better.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @tomresing  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
