### ISSUE TITLE
Other way(s) to get the Connect-EXOPSSession module?

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/office-docs-powershell#2350]
Is the Connect-EXOPSession module available to install via other methods?  Or can we get a direct link to it that doesn't require going through the Exchange Online admin portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@NeighborGeek the module is only available in the Exchange admin center (EAC).

**Comment by rpodric** [comment]
And:
http://aka.ms/exopspreview

**Comment by NeighborGeek** [comment]
@rpodric  Thanks for the update.  That link seems to be a direct download of a clickonce application.  Is there any documentation to go with that?  I'm not familiar with this method of distributing a powershell module, so I'm not sure how to work with this file.

**Comment by phillkOCCM** [comment]
they need to make this so we can leverage the ISE.
