### ISSUE TITLE
Where is the Skype module

### ISSUE THREAD

**Issue by jxs0900** [MicrosoftDocs/office-docs-powershell#2353]
Please provide the information needed to find this module like a DIRECT link to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 406867d0-0233-4c2e-683a-6ecc2d4d1743
* Version Independent ID: 53e81f24-1e27-9c50-439b-7916e7d1045d
* Content: [SkypeForBusiness](https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps)
* Content Source: [skype/skype-ps/skype/skype.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/skype.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by jamesrhea** [comment]
Hi @jxs0900. Are you looking for the instructions here? https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell

This includes a link to download the Skype for Business Online Connector module along with installation instructions.

**Comment by kenwith** [comment]
@jamesrhea - Yes, I think that is exactly the link. @jxs0900 - thanks for pointing out this link is needed in the listing page. I did try to add it there but the skype.md file is unique in that it provides a Table of Contents (TOC). Now that we have had this on GitHub for a little while I will check again if we can add links to the overview page. I will report back here shortly after I check.

**Comment by kenwith** [comment]
@jamesrhea - I submitted a Pull Request here: https://github.com/MicrosoftDocs/office-docs-powershell/pull/2354   this will be a bit of a test so we will have to see if it works. Once the PR finishes it's checks, if there aren't errors, let's merge it and see how it looks then we can close this issue out.

It is a great point @jxs0900 submitted that this is needed for the listing page for each cmdlet.

**Comment by kenwith** [comment]
Ok, looks like it worked this time and no errors! Here is the link: https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps

Let me know if you spot any issues and we can adjust. Thanks all!

PS - @jamesrhea - one note I remembered so I will post here.. if there are links to docs.microsoft.com articles you can remove the   en-us  from the link.. I did this in the PR.. that way when the person opens the link it uses the language of their browser.
