### ISSUE TITLE
Only returning some Teams

### ISSUE THREAD

**Issue by ebahsadmin** [MicrosoftDocs/office-docs-powershell#2358]
Any update on the backfilling of existing Teams? Running get-team only returns about half of our tenant teams/teams that the user is a member of

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8450991f-9f85-4d87-51b3-efa8e1004a24
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/Get-Team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by get-itips** [comment]
Hi @ebahsadmin how are you? Thanks for sharing feedback, we really appreciate it.
We will investigate if backfilling is done and the cmdlet returns all teams that a user is member of. Thank you

**Comment by get-itips** [comment]
Hi @ebahsadmin I confirmed that backfilling of existing teams is complete, created a PR to modify the document.
Thank you!

**Comment by kenwith** [comment]
Merged! Thanks all!
