### ISSUE TITLE
can set mailbox autoresponse update mailboxes on cloud or prem?

### ISSUE THREAD

**Issue by phillkOCCM** [MicrosoftDocs/office-docs-powershell#2360]
so we are in a situation where management has approved a process that frequently allows for users Out of Ofifce message to be updated. we utilize set-mailboxautoreplyconfiguration. To simplify the process, we are integrating it in automation & was wondering if this could be made to be mailbox location agnostic?

**Comment by chrisda** [comment]
@phillkOCCM, it doesn't appear so. The Set-MailboxAutoReplyConfiguration cmdlet requires the mailbox as an identifier.
