### ISSUE TITLE
DefaultAuthenticationPolicy parameter missing

### ISSUE THREAD

**Issue by JaMcCarter** [MicrosoftDocs/office-docs-powershell#2363]
The -DefaultAuthenticationPolicy parameter that is live in the Exchange Online CMDLET appears to be missing from this doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3ab3f0-cc05-e279-8876-6da0b323bcac
* Version Independent ID: bfb49814-d60b-564a-25cc-f902dfa42b10
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JaMcCarter, I added it.

Thanks for the feedback.

**Comment by JaMcCarter** [comment]
Thanks for adding that. When an authentication policy has been set as default using this CMDLET should it not reflect in the properties of a newly created user? I ask because it's not. Our newly onboarded users are not getting this policy, or at least I can't tell that they are as the property value is empty. Is that the expected behavior? If so it would be lovely if the documentation could indicate that somehow.
