### ISSUE TITLE
Example missing the group GUID

### ISSUE THREAD

**Issue by damianscoles** [MicrosoftDocs/office-docs-powershell#2366]
Example 1 isn't a complete example.  The group listed in the description is not included in the command.  If a group is not specified, then this error is displayed "New-DeviceTenantRule : Missing an argument for parameter 'ExclusionList'. Specify a parameter of type 'System.Object' and try again."  The correct example would be something like this 'New-DeviceTenantRule -ExclusionList &lt;GUID of Group&gt;'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccb34850-6729-d166-a2d9-7d8dec89a24b
* Version Independent ID: 2b9e2cd9-bea1-67f9-d2d0-e9bfe017e2e1
* Content: [New-DeviceTenantRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/new-devicetenantrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/devices/New-DeviceTenantRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/New-DeviceTenantRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@damianscoles, I fixed it.

Thanks for the feedback.
