### ISSUE TITLE
missing "Enable" and "Disable" words in the -Force parameter definition

### ISSUE THREAD

**Issue by behrouzamiri** [MicrosoftDocs/office-docs-powershell#2367]
in the -Force parameter definition, there are typos. article says "In this case you have to disable feature first with -SPFeature"
obviously, this should be Disable-SPFeature instead of -SPFeature (the word disable is missing).
same thing with the enable part (Enable-SPFeature instead of -SPFeature).
also, "In this case you have to disable feature first with" is formated as PowerShell code instead of mentioned cmdlets.

I know this is not a big deal, but I'm just in love with everything Microsoft ! , then I always want Microsoft keeps being perfect. good is not enough for you guys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b925905c-40e6-8b6f-4a12-e0b6c8d98c29
* Version Independent ID: ee4f8510-bfe7-ffc1-3d9a-0cb1641abe34
* Content: [Enable-SPFeature (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/enable-spfeature?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Enable-SPFeature.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Enable-SPFeature.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign this to me.
