### ISSUE TITLE
Exchange Online PowerShell to apply Retention Tags to Personal Folders and subfolders

### ISSUE THREAD

**Issue by msilinda** [MicrosoftDocs/office-docs-powershell#2383]
Looking for PowerShell commands to apply Retention Tags to Personal Folders and all folders and email under a specific personal folder, for Exchange Online.  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3665db68-7dd8-2e93-1797-505eb77a22ce
* Version Independent ID: 9cf5b8f2-a6aa-e79b-70e7-cfe5c1aee69c
* Content: [Get-RecoverableItems (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-recoverableitems?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-RecoverableItems.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-RecoverableItems.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by markjjo** [comment]
@msilinda The short answer is no, it's not possible for an admin to auto-apply personal tags to personal folders in user mailboxes. Admins can use retention policies to apply the Default Policy tag (DPT) to any item in the mailbox and can use Retention Policy Tags (RPT) to apply  to default folders. Only users can apply personal tags to items/folders in their mailbox to: "Manually to items and folders 
Users can automate tagging by using Inbox rules to either move a message to a folder that has a particular tag or to apply a personal tag to the message [by using client-side rules]." For more info, see https://docs.microsoft.com/en-us/Exchange/security-and-compliance/messaging-records-management/retention-tags-and-policies.
