### ISSUE TITLE
Intermittent Issues while exporting from SharePoint 2013 term store

### ISSUE THREAD

**Issue by adarshawasthi** [MicrosoftDocs/office-docs-powershell#2392]
While exporting the Global term store, this command is giving intermittent issues like sometimes it is not printing anything and sometimes only few term stores are getting exported. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9187caf-5e67-8e30-1ede-aaa71c0a7b95
* Version Independent ID: 837a8373-78a5-b871-fee8-d3eb86acdeec
* Content: [Export-PnPTaxonomy (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/export-pnptaxonomy?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Export-PnPTaxonomy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Export-PnPTaxonomy.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell

@VesaJuvonen Would you like me to open this in the SharePoint repo?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @adarshawasthi how are you?
Thanks for your feedback.
I could not reproduce this issue, it seems that some intermittent connection issue happened to your environment. No further documentation changes needs to be done.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @adarshawasthi 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
