### ISSUE TITLE
PowerShell ISE

### ISSUE THREAD

**Issue by merlin25** [MicrosoftDocs/office-docs-powershell#2394]
Is there an option to use PowerShell ISE like Exchange Online?
Import-Module $((Get-ChildItem -Path $($env:LOCALAPPDATA + "\Apps\2.0") -Filter Microsoft.Exchange.Management.ExoPowershellModule.dll -Recurse).FullName | ?{ $_ -notmatch "none" } | select -First 1)
$EXOSession = New-ExoPSSession -UserPrincipalName $UPN
Import-PSSession $EXOSession -AllowClobber

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b188049-5302-25da-5bd2-89401be1db96
* Version Independent ID: a1d18859-a50d-acd2-1ef1-3729925dc1f1
* Content: [Connect to Office 365 Security & Compliance Center PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell.md)
* Service: **o365-security-and-compliance**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@merlin25, check this out: https://blogs.technet.microsoft.com/richardroddy/2018/04/04/using-powershell-ise-to-connect-to-exchange-online-when-mfa-is-enabled/:

```
$CreateEXOPSSession = (Get-ChildItem -Path $env:userprofile -Filter CreateExoPSSession.ps1 -Recurse -ErrorAction SilentlyContinue -Force | Select -Last 1).DirectoryName
. "$CreateEXOPSSession\CreateExoPSSession.ps1"
```

If this works for you, please come back and close this issue. If it doesn't work, let's continue the discussion.

**Comment by merlin25** [comment]
Got it working … Thanks
