### ISSUE TITLE
Add links to disclaimer text

### ISSUE THREAD

**Issue by intared** [MicrosoftDocs/office-docs-powershell#2398]
I'd like to add a link to our privacy policy in the -DisclaimerText parameter of Set-OMEConfiguration.

HTML does not work.

The default text includes a link, so it would seem possible.

The docs only cover plain text.

**Comment by dariomws306** [comment]
Hi @intared , thank you for your feedback.

I am working on it, let me see if I can find how we can add a link here. Thank you again.

**Comment by chrisda** [comment]
@intared, according to the main topic about OME: https://docs.microsoft.com/office365/securitycompliance/add-your-organization-brand-to-encrypted-messages, links aren't possible for any of the text values. I presume you could add your Privacy Policy's URL, but the link wouldn't be hot.
