### ISSUE TITLE
Cached PW?

### ISSUE THREAD

**Issue by rpodric** [MicrosoftDocs/office-docs-powershell#2404]
The first time I used this module and ran the "Connect-EXOPSSession..." line, I got the expected authentication window and logged in.  In subsequent uses of that line in the days that followed, I only saw the auth window flash by, and I assumed that the PW was cached somewhere. All was well, for a while.

About a month later now, and I'm being prompted every time, which is extremely annoying.  What's the trick?  Whatever it is, I apparently managed it accidentally before, so it can't be that difficult. Was Credential Manager used for this?

At first, I thought the module had updated itself, accounting for the change in behavior, but I'm not aware that it does that or even if there has been more than one version. No, I think something about the system changed, throwing it off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by povlhp** [comment]
I have the MFA on every session, and when it times out every hour or so, I must reauthenticate.
At home with my low priv users, I have chosen to allow the browser/O365 to trust my MFA and my PWD for 30 days.
I think the persistent cookie should be saved by the system.

**Comment by kenwith** [comment]
This is a really great discussion, I wonder if something should be added to the doc to make it clear what is going on and security considerations of allowing browser/O365 trust of MFA, etc...? @chrisda - what do you think?

**Comment by rpodric** [comment]
Does anyone know what changed?  It did used to be persistent, at least optionally. If there's a way to do what povlhp is saying, and tell it to trust the PWD for 30 days or whatever, I don't see that option. I just see the standard O365 login form.

**Comment by rpodric** [comment]
That is what I use, and it used to do what you say. But a month ago, it started consistently asking for the PW, which it doesn't remember.

**Comment by msbemba** [comment]
@rpodric Thank you for your feedback. It is by design that When you use the Exchange Online Remote PowerShell Module, your session will end after one hour and you will have to reauthenticate using your 2fa credentials to connect again. The document also talks about another option  to avoid this issue, which is to  use Trusted IPs to bypass MFA for connections from your intranet, Trusted IP's can be used to connect to Exchange online using the below module 

https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps

**Comment by rpodric** [comment]
@msbemba 

1) Why is it then that for the first few months of my use of Exchange Online Remote PowerShell Module that the authentication was cached (note that this isn't in reference to the hour time-out but the ability to run it from day to day without re-authenticating every single time)?  However I did it before, it was purely by accident, and I have no idea how to do it again.

BTW, I don't have 2fa enabled. Why am I using this module then?  Because I've disabled basic authentication.

2) That Trusted IP idea looks great, except I can't use the original Exchange Online connectivity method any longer since I've disabled basic authentication for all, as MS recommends.

**Comment by msbemba** [comment]
@rpodric Thank you for the explanation. It is by design that the module session will end after one hour and you will have to re-authenticate using your credentials. While I understand that this worked for you before, we would really appreciate if you could contact the support team for your o365 tenant and let us know if there is any change that is required in this document. Thanks again for bringing this to our notice.

**Comment by rpodric** [comment]
@msbemba Please re-read what I wrote. I made a point to emphasize that I'm not referring to the hour time-out.

I'm referring to the need to supply a password every single time the product is used. Maybe @povlhp can shed some light on this, since above he alluded to knowing how to re-establish trust (what I referred to as caching).

**Comment by yogkumgit** [comment]
@rpodric  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with your valuable of information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by rpodric** [comment]
They're not going to have the slightest idea about something this fine-grained. It would be the waste of a week trying to explain it to them. I'll wait to hear back from @povlhp.

**Comment by jordanmills** [comment]
It's probably related to your Kerberos ticket.  I'll bet you were using a domain-joined computer on prem with a valid logon token in the past.  The client was directing you to an internal ADFS endpoint, it authenticated with the current Kerberos token, and you never noticed anything more than window appearing and disappearing quickly.  Something related to that changed, and now you can't be authenticated against internal ADFS with that token.
