### ISSUE TITLE
What unit of measurement does the returned property Size use?

### ISSUE THREAD

**Issue by AndrewJCo** [MicrosoftDocs/office-docs-powershell#2405]
This page forces you to click and search through several other pages to try and figure out what gets returned in the Size field. Eventually I ended up at this page https://docs.microsoft.com/en-us/previous-versions/office/exchange-server-api/jj959067%28v%3dexchg.150%29 which tells me nothing. 

Did I miss something or is the unit of measurement for Size not documented anywhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3d7f9c1-78f0-5869-2e87-94c56c914316
* Version Independent ID: f7927615-71e8-069b-d2f3-0cae30092cd1
* Content: [Get-MessageTrace (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/get-messagetrace?view=exchange-ps#outputs)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Get-MessageTrace.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Get-MessageTrace.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws306** [comment]
Hi @AndrewJCo , thank you for your feedback.

Are you talking about -PageSize? It's an Int32 value.

Thank you again.

**Comment by yogkumgit** [comment]
@dariomws306 and @chrisda Thank you very much for the contribution and sharing this explanation. @AndrewJco  Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
