### ISSUE TITLE
Blocked by Conditional Access

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/office-docs-powershell#2406]
When accessing via this method the source IP will be a Microsoft IP Address from the "Exchange Filtering" application in conditional access. If you have IP whitelist these will fail. You must use ADAL/MFA method to access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Office 365 Security & Compliance Center PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md)
* Service: **o365-security-and-compliance**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@stephenc01 is there a specific statement in the topic that needs to be added or corrected?

**Comment by stephenc01** [comment]
It should be added, with IP based conditions access rules this connection method is. Or supported.

**Comment by yogkumgit** [comment]
@chrisda please merge the PR#3497

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @stephenc01 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
