### ISSUE TITLE
Set-SPOSite - Need CSOM Reference

### ISSUE THREAD

**Issue by narulasrinivas** [MicrosoftDocs/office-docs-powershell#2408]
Hi folks....I'm able to stop page comments using `CommentsOnSitePagesDisabled` property in `Set-SPOSite` powershell command. 

Please help me point to the same property (`CommentsOnSitePagesDisabled` ) in CSOM.

Anyhelp would be highly appreciated.

**Comment by khorne3** [comment]
Hi @narulasrinivas. Is this close to what you are looking for? 

[Powershell in SharePoint: Disable comments on modern pages in entire site using CSOM](https://social.technet.microsoft.com/wiki/contents/articles/52346.powershell-in-sharepoint-disable-comments-on-modern-pages-in-entire-site-using-csom.aspx)

**Comment by narulasrinivas** [comment]
Hey @khorne3  Thanks lot. 

Can we use the `CommentsOnSitePagesDisabled ` as a propery bag value to update in CSOM or is there any other equivalent property for that?

**Comment by tseward** [comment]
You can use https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/mt844966(v=office.15) via CSOM.

**Comment by narulasrinivas** [comment]
@tseward  - Thank you. I'll give a try.

**Comment by VesaJuvonen** [comment]
Closing as an answered issue.
