### ISSUE TITLE
Space in username

### ISSUE THREAD

**Issue by jackpoz** [MicrosoftDocs/office-docs-powershell#2409]
Example 1 has a space in the Identity parameter after the \ character, "Contoso \jdoe" instead of "Contoso\jdoe"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebf30b69-b6b3-2d23-e1c7-d156893319f0
* Version Independent ID: 3a5066e3-5b52-a5df-7356-80fa445a5ff1
* Content: [Remove-SPUser (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/remove-spuser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Remove-SPUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Remove-SPUser.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
change has been made and republished
