### ISSUE TITLE
Startdate and Enddate

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/office-docs-powershell#2410]
I'm confused - the article states "Although the cmdlet accepts date ranges older than 7 days, only information about the last 7 days are returned" but using the startdate and enddate parameters, I can pull data from over 30 days ago. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f04d48-7267-e9e4-0b1c-efb99d571286
* Version Independent ID: 21a2271e-b300-cf93-481b-88feed613563
* Content: [Get-DlpDetailReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/get-dlpdetailreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpDetailReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpDetailReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws306** [comment]
Hi @terrogin ,

Thank you for your feedback.

I have asked and it shouldn't return data beyond the 7 days. Could you kindly open a support ticket so product group can follow up on this problem?

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

Thank you!

**Comment by yogkumgit** [comment]
@terrogin  Thank you very much for posting this issue. Considering the nature of the issue, as Dario advised, please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

**Comment by terrogin** [comment]
Thanks - I've opened a couple tickets regarding a number of issues with the cmdlet and inconsistent behavior. I'll update once we figure out what's going on.

**Comment by dariomws306** [comment]
Hi @terrogin,

How did it go with Microsoft support?

Thanks!

**Comment by terrogin** [comment]
Not good. The cmdlet seem entirely broken and support has not figured out the various issues. For example, just looking at DLP reports today, the cmdlet only reports back positive DLP hits for one day last month  (9/16) despite the fact that I have positive DLP hits every day for the last 30 days which we can see in the dashboard and in reports. Additionally, 9/16 is not within the last 7 days, though the cmdlet is only supposed to report for the last 7 days.

**Comment by dariomws306** [comment]
@chrisda, do you think you can help here? Thank you!

**Comment by dariomws306** [comment]
Hi @terrogin, thank you for your comments.

Did you try [Get-DlpSiDetectionsReport](https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance-dlp/get-dlpsidetectionsreport) instead of Get-DlpDetailReport?

**Comment by yogkumgit** [comment]
@dariomws   Thank you very much for the contribution and digging deep into it.  @terrogin  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
