### ISSUE TITLE
Allow/Block Domains and subdomain handling

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/office-docs-powershell#2413]
The domain allow/block needs additional details.  For instance, Wildcards are not accepted so *.microsoft.com cannot be added.  So if I add microsoft.com does that mean subs would automatically be included?  I see the -matchsubdomains is reserved.  What if a customer wanted to block spammer.com but allow crm.spammer.com?  If I populate those to allow/blocked domains correctly, would it work as I expect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e1bc61-af1f-a9c1-72fe-ece163efc0f6
* Version Independent ID: 2ba3f316-1872-5670-22b3-94f1c4cfcb0f
* Content: [Set-HostedContentFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/Set-HostedContentFilterPolicy?view=exchange-ps#optional-parameters)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedContentFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedContentFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws306** [comment]
Hi @chrislehr , thank you for your contribution.

I think you have the answer in this article:
https://docs.microsoft.com/en-us/office365/securitycompliance/create-organization-wide-safe-sender-or-blocked-sender-lists-in-office-365

"If you allow top-level domains, it's likely that email you don't want will be delivered to an inbox."

"If you block top-level domains, it's likely that email you want will be marked as spam."

**Comment by chrislehr** [comment]
I disagree.

Doesn’t at all clear up this question:

What if a customer wanted to block @spammer.com but allow @crm.spammer.com?

Or what if I want to allow @legitcompany.com but block @spam.legitcompany.com

**Comment by dariomws306** [comment]
What if a customer wanted to block @spammer.com but allow @crm.spammer.com?
If you add spammer.com to the block domain list it will also block crm.spammer.com. So your option here is to use a rule to block only spammer.com:
https://docs.microsoft.com/en-us/office365/securitycompliance/create-organization-wide-safe-sender-or-blocked-sender-lists-in-office-365#use-the-eac-to-create-a-transport-rule-that-blocks-messages-sent-from-a-domain-or-user

Or what if I want to allow @legitcompany.com but block @spam.legitcompany.com
If you add spam.legitcompany.com to the block domain list, it will block spam.legitcompany.com and for example *.spam.legitcompany.com, but not legitcompany.com.

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and sharing this explanation. @chrislehr
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
