### ISSUE TITLE
Database Name in the Example

### ISSUE THREAD

**Issue by KRyan318** [MicrosoftDocs/office-docs-powershell#2414]
The database name in Example 1 is 'State Service,' which is not an appropriate name for a database. Suggest changing Example 1 database name to 'StateSvcDB1' as stated in the "-Database" explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00b0f73a-d574-3473-6587-b7cf6f929abb
* Version Independent ID: eb32f3d4-9570-b527-017f-7a2472acd13d
* Content: [New-SPStateServiceApplication (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spstateserviceapplication?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPStateServiceApplication.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPStateServiceApplication.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

@KRyan318 why is this database name not appropriate? It is a valid name.

**Comment by tseward** [comment]
@KRyan318 while DBAs may have issues with the naming, it is not an invalid database name. SharePoint handles spaces within database names.

DBAs, if they're the ones to manage the SQL Servers, should be providing guidance based on company policy for the SharePoint admin and/or pre-provisioning databases.

**Comment by KRyan318** [comment]
Great, thanks!
