### ISSUE TITLE
SafeForAnonymous Description

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/office-docs-powershell#2417]
Replace {{Fill SafeForAnonymous Description}} with"Enables this managed property to be returned for queries executed by anonymous users. Enable this setting for managed properties that do not contain sensitive information and are appropriate for anonymous users to view."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efec0d67-d9c9-a290-1b60-54f66faee077
* Version Independent ID: 8b54b9cb-9231-9170-6130-794c175b2d7b
* Content: [New-SPEnterpriseSearchMetadataManagedProperty (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spenterprisesearchmetadatamanagedproperty?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchMetadataManagedProperty.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchMetadataManagedProperty.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.
