### ISSUE TITLE
Parameter 'VariantType'

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/office-docs-powershell#2418]
WARNING: Parameter 'VariantType' is obsolete.
WARNING: Obsolete parameter ignored: '-VariantType'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b73fae0-a1f9-352b-8347-4046832cd549
* Version Independent ID: bdd62bda-8704-aaed-c45c-6774fb4843c9
* Content: [New-SPEnterpriseSearchMetadataMapping (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spenterprisesearchmetadatamapping?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchMetadataMapping.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchMetadataMapping.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr, assign to me, please.
