### ISSUE TITLE
Exceptions for EO cmdlet help in powershell sessions

### ISSUE THREAD

**Issue by gmkeif** [MicrosoftDocs/office-docs-powershell#2440]
Up until December last year, at least for us, Exchange Online Powershell cmdlet help was available using `Get-Help` in the shell. However, after the Christmas break, the only response we get is:
```
Get-Help : Exception calling "Invoke" with "0" argument(s): "Cannot find path '' because it does
not exist."
At line:1 char:1
+ Get-Help Get-Mailbox
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Help], MethodInvocationException
    + FullyQualifiedErrorId : CmdletInvocationException
```
It's the same issue irrespective of the cmdlet. I know I'm not the only one suffering from this malady. When may we see the issue resolved in the shell instead of having to hunt and peck through the website?

**Comment by chrisda** [comment]
@gmkeif, I've been seeing this myself since June. It has something to do with Windows PowerShell. I highly encourage you to file a support case.
