### ISSUE TITLE
Get-PnPAvailableApp does not exist

### ISSUE THREAD

**Issue by nils-a** [MicrosoftDocs/office-docs-powershell#2444]
The examples 3 and 4 use the command `Get-PnPAvailableApp` - however it does not exist. 
Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a35e307-24b0-6bd3-f60d-62a253bd973f
* Version Independent ID: 17b2e303-31bd-2ed9-48ca-2fc3c82e66bb
* Content: [Install-PnPApp (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/install-pnpapp?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Install-PnPApp.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Install-PnPApp.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by khorne3** [comment]
Hi @nils-a, `Get-PnPAvailableApp` should be `Get-PnPApp`. I'll update the docs.
