### ISSUE TITLE
Publish-PnP doesn't add PnPApp onto site under -Scope Site

### ISSUE THREAD

**Issue by samyaktelsang** [MicrosoftDocs/office-docs-powershell#2447]
**Reporting an Issue or Missing Feature**

Publishing an app onto the site app catalog doesn't make it available to the end user.
Getting a "Get It" button after using Publish-PnPApp -Identity <app-id from site> -Scope Site on a site collection appcatalog. Publish-PnPApp (default is -Scope tenant) works without problems.

**Expected behavior**

Publish-PnPApp -Scope Site should add the app onto the site automatically and user should not have to click "Get It".

![getitissuenotavailable](https://user-images.githubusercontent.com/33766839/50867720-0cdbd600-1361-11e9-8217-6739ea4436e1.png)

**Actual behavior**

When using Publish-PnPApp on a site collection appcatalog, the following happens:

![getitissue](https://user-images.githubusercontent.com/33766839/50866330-64c50d80-135e-11e9-90b2-089063b129ca.png)

I notice that this is an issue when this script is run using AzureDevOps as part of the release process.
Am I supposed to use a different cmdlet in order to ensure that the site has newest version of the app? 

**Steps to reproduce behavior**

Create a new teamsite.

Add site collection appcatalog:

Connect-SPOService <admin-url>
Add-SPOSiteCollectionAppCatalog -Site <teamsite-url>
Create default spfx webpart:
yo @microsoft/sharepoint

Build and package:

gulp bundle --ship
gulp package-solution --ship
Connect to site:
Connect-PnpOnline <teamsite-url>

_Upload, publish and install:_

```
$appInTenant = Add-PnPApp -Path $Path -Overwrite -Scope tenant -Publish -Verbose
$appInSite = Add-PnPApp -Path .\sharepoint\solution\test-app.sppkg  -Scope Site -Overwrite
Publish-PnPApp -Identity $appInSite.Id -Scope Site
Install-PnPApp -Identity $appInSite.Id -Scope Site
```

**Which version of the PnP-PowerShell Cmdlets are you using?**

- [ ] PnP PowerShell for SharePoint 2013
- [ ] PnP PowerShell for SharePoint 2016
- [X] PnP PowerShell for SharePoint Online

**What is the version of the Cmdlet module you are running?**
3.4.1812.2

**How did you install the PnP-PowerShell Cmdlets?**

- [ ] MSI Installed downloaded from GitHub
- [X] Installed through the PowerShell Gallery with Install-Module
- [ ]   Other means
  
Highly appreciate your help! @pauldalyii @VesaJuvonen  @KoenZomers @RobinDijkstra @BorisLand

**Comment by RobinDijkstra** [comment]
If the app already is already installed on the site collection, you have to use Update-PnpApp instead of Install-PnPApp.
Why do you add the app to the site collection appcatalog as well as the tenant appcatalog? When the app is added to the tenant appcatalog, you don't need the '-scope site' to install the app in the site collection.

**Comment by samyaktelsang** [comment]
Thank you @RobinDijkstra . My understanding of Installing or Upgrading a PnPApp to the catalog is as follows:

```
function InstallOrUpgrade-PnpApp {
[CmdletBinding()]
    param (
        [string]
        $Path
        [string]
        $Url
        [string]
        $Credential
    )
    begin {
    }
    process {
        #Connect to tenant
        Connect-PnPOnline -Url $url -Credentials $credential
        $appInTenant = Add-PnPApp -Path $Path -Overwrite -Scope tenant -Publish -Verbose

        #Connect to site
        Connect-PnPOnline -Url $url -Credentials $credential
        $appInSite = Add-PnPApp -Path .\sharepoint\solution\test-app.sppkg -Scope Site -Overwrite
        
        if($appInSite.CanUpgrade -eq $true) {
        Upgrade-PnpApp -Identity $appInSite.Id -Scope Site
        } elseIf($appInSite.InstalledVersion -eq $null) {
        Install-PnPApp -Identity $appInSite.Id -Scope Site
        }
        Publish-PnPApp -Identity $appInSite.Id -Scope Site
        }
    end {
    }
}
```
**Call above script for version 1 of the app:**

#in this case, test-app.sppkg contains a package version # 1.0.0.0, and Install-PnpApp should be called
InstallOrUpgrade-PnpApp -Path .\sharepoint\solution\test-app.sppkg
#after the 1.0.0.0 version of the sppkg file is passed to InstallOrUpgrade-PnpApp, _Get It_ is not visible at this url (https://$(TenantName).sharepoint.com/sites/<ProjectName>/_layouts/15/addanapp.aspx#mcg=2), as expected.

**Call above script for version 2 of the app:**
 
#in this case, test-app.sppkg contains a package with version # 1.0.0.1, and Upgrade-PnpApp should be called
InstallOrUpgrade-PnpApp -Path .\sharepoint\solution\test-app.sppkg
#after the 1.0.0.1 version of the sppkg file is passed to InstallOrUpgrade-PnpApp, Get it is visible at this url (https://$(TenantName).sharepoint.com/sites/<ProjectName>/_layouts/15/addanapp.aspx#mcg=2). This is not expected. We expect _Get It_ to not be displayed.

Is there something I am missing? Appreciate your help.

**Comment by RobinDijkstra** [comment]
I think you've got the order wrong. The order should be:
- Add-PnPApp
- Publish-PnPApp
- Install-PnPApp or Update-PnPApp

**Comment by samyaktelsang** [comment]
Thanks @RobinDijkstra . I modified my function in the following way as per your suggestion:

```
function InstallOrUpgrade-PnpApp {
[CmdletBinding()]
    param (
        [string]
        $Path
        [string]
        $Username
        [string]
        $Credential
    )
    begin {
    }
    process {
        #Connect to tenant
        Connect-PnPOnline -Url $url -Credentials $credential

        do{
            $secondsToSleep = 5
            Write-Verbose "Waiting $secondsToSleep seconds for app to be added"
            Start-Sleep -Seconds $secondsToSleep
            try{
                $appInTenant = Add-PnPApp -Path $Path -Overwrite -Scope tenant -Publish -Verbose
            }
            catch {
                $removePnpError=$True
            }
	    }while($removePnpError -eq $true)

        

        #Connect to site
        Connect-PnPOnline -Url $url -Credentials $credential
        do{
            $secondsToSleep = 5
            Write-Verbose "Waiting $secondsToSleep seconds for app to be added"
            Start-Sleep -Seconds $secondsToSleep
            try{
                $appInSite = Add-PnPApp -Path .\sharepoint\solution\test-app.sppkg -Scope Site -Overwrite
            }
            catch {
                $removePnpError=$True
            }
	    }while($removePnpError -eq $true)
        
        Publish-PnPApp -Identity $appInSite.Id -Scope Site

        if($appInSite.CanUpgrade -eq $true) {
            Upgrade-PnpApp -Identity $appInSite.Id -Scope Site
        } else {
            Install-PnPApp -Identity $appInSite.Id -Scope Site
        }
        }
    end {
    }
}
```

However, even after Publishing the app before install or update, I find that 'Get It' appears on my site catalog and the app hasn't been updated. Any conditional check or command let I might be missing? Highly appreciate your help @RobinDijkstra .
 
#in this case, test-app.sppkg contains a package with version # 1.0.0.0, and Install-PnpApp should be called
InstallOrUpgrade-PnpApp -Path .\sharepoint\solution\test-app.sppkg
#after the 1.0.0.0 version of the sppkg file is passed to InstallOrUpgrade-PnpApp, Get it is not visible at this url (https://$(TenantName).sharepoint.com/sites/<ProjectName>/_layouts/15/addanapp.aspx#mcg=2), as expected.
 
#in this case, test-app.sppkg contains a package with version # 1.0.0.1, and Upgrade-PnpApp should be called
InstallOrUpgrade-PnpApp -Path .\sharepoint\solution\test-app.sppkg
#after the 1.0.0.1 version of the sppkg file is passed to InstallOrUpgrade-PnpApp, Get it is visible at this url (https://$(TenantName).sharepoint.com/sites/<ProjectName>/_layouts/15/addanapp.aspx#mcg=2). This is not expected. We expect Get it to not be displayed.

**Comment by RobinDijkstra** [comment]
I see a typo, could you try it with Up**d**atePnP-App instead of Up**gr**adePnP-App?

**Comment by samyaktelsang** [comment]
Thanks @RobinDijkstra . I have been using [UpdatePnP-App ](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/update-pnpapp?view=sharepoint-ps)command let. Tried it once again to confirm the above behavior. I still find the 'Get It' displayed in the catalog.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @samyaktelsang how are you?
I took the time to test this in my lab and could not reproduce. Also, as this is specifically for documentation issues, no further PRs on documentation needs to be done. @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @samyaktelsang 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
