### ISSUE TITLE
-ConditionalCustomAttributeX

### ISSUE THREAD

**Issue by ServerCare** [MicrosoftDocs/office-docs-powershell#2449]
really guys... identical text for -ConditionalCustomAttribute1 up to 15?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f74a1-badd-e304-55d8-1981f86c5440
* Version Independent ID: e51876c4-c39d-a1b6-4624-599eb8f823d8
* Content: [New-DynamicDistributionGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/new-dynamicdistributiongroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/New-DynamicDistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/New-DynamicDistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by ServerCare** [comment]
Hi Chris, 

No, it seems to me the identical text with each item 1 through 15 is simply too much of a good thing. Since the use of each attribute is identical, the text should reflect this in a more concise manner.

**Comment by chrisda** [comment]
@ServerCare any suggestions? In the absence of other feedback, I would say something like "This parameter specifies additional information about the recipient that you can use for filtering or other custom identification requirements."

**Comment by ServerCare** [comment]
I would leave the original text in place where -ConditionalCustomAttribute1 is discussed, and then refer to that text for the other ConditionalCustomAttribute's. for example:

 "Like ConditionalCustomAttribute1, this parameter specifies additional information about the recipient that you can use for filtering or other custom identification requirements."

Suggested minor changes for the original text: 
Second paragraph: "the OR Boolean operator" changed to "Boolean operators" to reflect that other Boolean operators can be used also.

Third paragraph: "You can't use this parameter with the RecipientFilter parameter. " changed to
"You can't use this parameter in combination with the RecipientFilter parameter. "

Also: at ConditionalCustomAttribute1 it seems the text is there twice...(copy/paste error?)

**Comment by chrisda** [comment]
@ServerCare , sorry, I kind of lost track of this, and I kept confusing CustomAttribute X with ConditionalCustomAttributeX (I know the difference; it was just me). So the rest of my comments are about definitely about ConditionalCustomAttributeX.

I updated the descriptions to an extent, but not exactly everything you asked for:

> First paragraph: "Like ConditionalCustomAttribute1, this parameter specifies additional information about the recipient that you can use for filtering or other custom identification requirements."

Each parameter description is supposed to be self-contained, although they certainly refer to each other (for example, when one parameter is dependent on another). The whole topic isn't really meant to be read like a book.

> Second paragraph: "the OR Boolean operator" changed to "Boolean operators" to reflect that other Boolean operators can be used also.

With precanned filters (any parameter name that starts with Conditional), multiple values for a parameter (property) are always OR, and multiple parameters (properties) are always AND; there's no way to change this. The only way to have control over the Boolean operators for multiple values and multiple properties is to not use a precanned filter, and Conditional parameters can only be used with precanned filters.

> Third paragraph: "You can't use this parameter with the RecipientFilter parameter. " changed to
"You can't use this parameter in combination with the RecipientFilter parameter. "

I said: You use this parameter in combination with the IncludedRecipients parameter as part of a precanned filter. You can't use any Conditional parameters in combination with the RecipientFilter parameter (which is used to create custom OPath filters).

> Also: at ConditionalCustomAttribute1 it seems the text is there twice...(copy/paste error?)

Yes, I removed that.

I also took the opportunity to customize/standardize/fix the ConditionalCustomAttributeX, CustomAttributeX, ExtensionCustomAttributeX, IncludedRecipients, and RecipientFilter parameter descriptions across all cmdlets, and to account for differences in New- (add only) vs. Set- (add, remove, or replace).

Thanks for the feedback.
