### ISSUE TITLE
Get-StaffHubUsersForTenant not recognized

### ISSUE THREAD

**Issue by jjinatlanta** [MicrosoftDocs/office-docs-powershell#2451]
I installed the version 1.0.2 of this module, and Get-StaffHubUsersForTenant command is not recognized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e18b11da-9130-95b5-0c59-5cac70621dba
* Version Independent ID: 34db617c-b231-e423-11fe-20bd9c3bb929
* Content: [Get-StaffHubUsersForTenant (staffhub)](https://docs.microsoft.com/en-us/powershell/module/staffhub/get-staffhubusersfortenant?view=staffhub-ps)
* Content Source: [staffhub/staffhub-ps/staffhub/Get-StaffHubUsersForTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/staffhub/staffhub-ps/staffhub/Get-StaffHubUsersForTenant.md)
* Service: **staffhub-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by msbemba** [comment]
The Cmdlet is in Beta stage and Get-StaffHubUsersForTenant is not exported when connecting to microsoftstaffhub module 1.0.2

Below are the cmdlets that are currently exported under the module1.0.2 
Key                        Value
---                        -----
Add-StaffHubMember         Add-StaffHubMember
Add-StaffHubShift          Add-StaffHubShift
Add-StaffHubTeam           Add-StaffHubTeam
Connect-StaffHub           Connect-StaffHub
Get-StaffHubMember         Get-StaffHubMember
Get-StaffHubTeamsForTenant Get-StaffHubTeamsForTenant
Import-StaffHubMember      Import-StaffHubMember
Import-StaffHubShift       Import-StaffHubShift
Import-StaffHubTeam        Import-StaffHubTeam
Remove-StaffHubMember      Remove-StaffHubMember
