### ISSUE TITLE
No examples or parameter explanations

### ISSUE THREAD

**Issue by bruceredfern** [MicrosoftDocs/office-docs-powershell#2457]
There are only place saver parameter descriptions.  At least one example would help too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2417b89a-3510-d766-7433-90eba2c1fe44
* Version Independent ID: 70f8079c-9500-009c-d579-05f92f535a0c
* Content: [Get-CsOnlineApplicationEndpoint (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineapplicationendpoint?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineApplicationEndpoint.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineApplicationEndpoint.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by lindspea** [comment]
Hi @bruceredfern. Thank you for your valuable contribution to help improve MS docs.  We will work together to resolve this issues soonest.

**Comment by dariomws306** [comment]
Hi @bruceredfern , thanks for your feedback. I am updating some well know parameters here and adding an example.

**Comment by lindspea** [comment]
@AndreaBarr this can be closed.
