### ISSUE TITLE
-RejectMessageReasonText and -RejectMessageEnhancedStatusCode can't be used simultaneously

### ISSUE THREAD

**Issue by h-david-a** [MicrosoftDocs/office-docs-powershell#2480]
Correction needed:
If -RejectMessageReasonText specified, status code is defaulted to "5.7.1"
If -RejectMessageEnhancedStatusCode  specified, RejectMessageReasonText is set to "Delivery not authorized, message refused"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0adf9c04-ae08-35ee-4551-18ddfa30a3ad
* Version Independent ID: 4aea3a31-183c-b05c-b7b2-bbea03e1981e
* Content: [Set-TransportRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/set-transportrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance/Set-TransportRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance/Set-TransportRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@h-david-a Issue is looked into, and PR is created for updating the documentation. Appreciate, you pointed out this to us.

**Comment by yogkumgit** [comment]
@h-david-a thanks for taking out some time to open this issue. Appreciate and encourage you to do the same in future also.
