### ISSUE TITLE
Missing Parameters

### ISSUE THREAD

**Issue by zokiol** [MicrosoftDocs/office-docs-powershell#2484]
Hi,
There seem to be a few new parameters that perhaps came with the July CU.  I am interested in the following parameters that I also have for this cmdlet that are not documented here:

OverrideAuthTypeForExternalClients
OverrideAuthTypeForInternalClients

Please add the new parameters to the documentation and explain what options they take and their effects.  
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0012cc5b-842a-457f-c93b-08ac1250e7e3
* Version Independent ID: 5e27a0ad-29e7-dfea-48ad-0ce50c67924c
* Content: [Set-CsWebServiceConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cswebserviceconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsWebServiceConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
Hi @zokiol , thank you for your feedback. I am working on it.

**Comment by dariomws306** [comment]
I am updating the description of these parameters:
https://github.com/MicrosoftDocs/office-docs-powershell/pull/2793
