### ISSUE TITLE
How to provide credentials with 2FA?

### ISSUE THREAD

**Issue by hugoabernier** [MicrosoftDocs/office-docs-powershell#2495]
One of my client's tenant has two-factor authentication enabled. I am unable to use PowerShell to migrate content from 2013 to Office 365. After calling Register-SPMTMigration and Add-SPMTTask without issues, calling Start-SPMTMigration returns:
`Start-SPMTMigration : Username or password for target site ______ is not correct`.
I suspect it relates to 2FA. I tried using an app password instead without any luck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaf9ad0e-f0fe-518a-33fa-ea108de06846
* Version Independent ID: 9cb845e5-400c-ce30-c4eb-4ee8ee79ba46
* Content: [Start-SPMTMigration (spmt)](https://docs.microsoft.com/en-us/powershell/module/spmt/start-spmtmigration?view=spmt-ps)
* Content Source: [spmt/spmt-ps/spmt/Start-SPMTMigration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/spmt/spmt-ps/spmt/Start-SPMTMigration.md)
* Service: **spmt-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by hugoabernier** [comment]
Update: tested exact same script to another tenant without 2FA and was successful. Help with dealing with 2FA would be greatly appreciated.

**Comment by tseward** [comment]
I suspect 2FA is incompatible with the tool similar to other tooling from the SharePoint PG. E.g. the Hybrid Config Wizard or the cmdlets to copy Taxonomy terms from the local farm to SPO.

**Comment by nbalauro** [comment]
Do not supply credentials when you invoke "Register-SPMTMigration". This will prompt for login and mfa interactively.

**Comment by msbemba** [comment]
@hugoabernier Thank you for your feedback. This document covers the usage of the cmdlet Start-SPMTMigration using basic authentication as there is no specific Microsoft.SharePoint.MigrationTool.PowerShell module available for 2FA at the moment. Having said that,  the work around provided by @nbalauro should helpful as you can skip supplying credentials when you invoke "Register-SPMTMigration" which will prompt for Credentials interactively.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @hugoabernier  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
