### ISSUE TITLE
Chrome download works fine

### ISSUE THREAD

**Issue by spacklewoof** [MicrosoftDocs/office-docs-powershell#2498]
As of Chrome Version 71.0.3578.98 (Official Build) (64-bit) the download works fine.

"Note: Internet Explorer or Edge is required because the download in the next step uses ClickOnce, so Google Chrome or Mozilla Firefox won't work."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nenonix** [comment]
@spacklewoof  Thank you for this helpful feedback. Maybe we could say "A browser that uses ClickOnce (like Internet Explorer or Edge) is needed for the download in the next step."  Would that work for you?

**Comment by spacklewoof** [comment]
Works for me!  Thanks for the follow up!

sent from smart phone. please ignore spelling or contextual grammar issues. thank you.

________________________________
