### ISSUE TITLE
TermSetPath for default site collection term group

### ISSUE THREAD

**Issue by Madserker** [MicrosoftDocs/office-docs-powershell#2515]
Hello,

It would be nice if we could use some kind of parameter to specify the process to use the default site collection term group, since the term group name changes across diferent site collections.

Is there any option to do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2690c5-d59a-fe9c-2810-3a8141096d36
* Version Independent ID: edbc02e9-96ac-ee9b-0a3d-c115d7c38745
* Content: [Add-PnPTaxonomyField (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnptaxonomyfield?view=sharepoint-ps#required-parameters)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTaxonomyField.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTaxonomyField.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell

@VesaJuvonen Would you like me to open this in the SharePoint repo?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Madserker Thanks for your feedback.
I can confirm that there isn't currently, an option or parameter to indicate to the process to use the default SC term group in this cmdlet without specifically setting it to the cmdlet. But the community is continually improving the cmdlets.

Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Madserker 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
