### ISSUE TITLE
Set-PnPList Typo

### ISSUE THREAD

**Issue by leifucd** [MicrosoftDocs/office-docs-powershell#2527]
I noticed a typo on Set-PnPList document, ListExperience parameters were listed as Auto, NewExperience or ClassExperience. Should be ClassicExperience instead of ClassExperience.

**Comment by AndreaBarr** [comment]
e have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  
 
Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.
