### ISSUE TITLE
Size limitation

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/office-docs-powershell#2550]
Is there any limit to the size of a site collection that can be backed up using this cmdlet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7709132-eaba-7ae9-8f3d-76fe40cc4420
* Version Independent ID: 7f5b5c75-601b-02d2-fd14-a4092aec52e8
* Content: [Backup-SPSite (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/backup-spsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Backup-SPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Backup-SPSite.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by msbemba** [comment]
@LuigiBruno SharePoint site collection backup and restore is only supported for a maximum site collection size of 100 GB. For larger site collections, the complete content database must be backed up. If multiple site collections larger than 100 GB are contained in a single content database, backup and restore operations can take a long time and are at risk of failure.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @LuigiBruno  
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by LuigiBruno** [comment]
> @LuigiBruno SharePoint site collection backup and restore is only supported for a maximum site collection size of 100 GB. For larger site collections, the complete content database must be backed up. If multiple site collections larger than 100 GB are contained in a single content database, backup and restore operations can take a long time and are at risk of failure.

Thank you @msbemba.

**Comment by LuigiBruno** [comment]
> @msbemba  Thank you very much for the contribution and sharing this explanation. @LuigiBruno
> Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

Sure.
Thank you @yogkumgit.
