### ISSUE TITLE
SPO Cmdlets in SharePoint-Server repo

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/office-docs-powershell#258]
The documentation for the cmdlets [ConvertTo-SPOMigrationEncryptedPackage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/ConvertTo-SPOMigrationEncryptedPackage.md) and [ConvertTo-SPOMigrationTargetedPackage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/ConvertTo-SPOMigrationTargetedPackage.md) should be moved out of the sharepoint-server repo as they are only deployed with the SharePoint Online Management Shell.

**Comment by VesaJuvonen** [comment]
Fixed now. Thx for reporting.
