### ISSUE TITLE
Delay when adding guest users with Add-TeamUser

### ISSUE THREAD

**Issue by oddmk79** [MicrosoftDocs/office-docs-powershell#2635]
I'm trying to automate the process of adding guest users to Teams with PowerShell using the following process;

1. New-AzureADMSInvitation -InvitedUserDisplayName "Ola Nordmann" -InvitedUserEmailAddress example@mail.com -InviteRedirectURL https://myapps.azure.com -SendInvitationMessage $true
2. Add-TeamUser -GroupId 83c6dd07-60fd-4632-b653-51ba5fce31a4 -User example@mail.com
3. Get-TeamUser -GroupId 83c6dd07-60fd-4632-b653-51ba5fce31a4

![2](https://user-images.githubusercontent.com/34348181/51523253-8d073e80-1e2b-11e9-8f69-9d34f35aa828.png)

So from the PowerShell side the user is invited and successfully added to the Team, but when looking at the Team using the Teams Client or web browser and clicking Manage Team, the user are not listed there.

![4](https://user-images.githubusercontent.com/34348181/51523256-91cbf280-1e2b-11e9-897f-e896bfffab09.png)

Logging in as the guest user who shows as added in PowerShell does not see the Team.
The guest user receives the invitation from Step 1 above, but does not receive any notifications about being added to the Team.

If I wait for 1-6 hours (not a consistent delay) the user shows up under Manage Team in the Teams Client/web browser and guest user will see the Team when he/she logs on. In the example above the guest user was added to the Team 10:23 with PowerShell and didn't show up under Manage Team before 13:09. (I also see the same delay when using Microsoft Graph)
 
Inviting a guest user with the Teams Client or the web browser is working fine, no delays, and guest user will get a notification about the Team he/she is invited to.

So questions are;
1. Is the delay when adding guest users to Teams with PowerShell by design? How long can we expect the delay to be?
2. Is it possible to notify guest users who are added to a Team through PowerShell? (Guest users is notified when added through GUI)

**Comment by yogkumgit** [comment]
@oddmk79  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
