### ISSUE TITLE
Question about Security Group Membership

### ISSUE THREAD

**Issue by macslui** [MicrosoftDocs/office-docs-powershell#2636]
Is there any commandlet we can use to force user membership "recompilation" (ad security group for federated domain + cloud only security group) once a member become part of a new security group? Seems that this is not propagate to SPO permission when this security group is set in a SharePoint group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e28b2b9-6c62-d3f2-6c82-30a1d5f7a0fd
* Version Independent ID: 4e7a66a5-51fa-cf5a-4146-77e84b14b8ab
* Content: [Revoke-SPOUserSession (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/revoke-spousersession?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by j0rt3g4** [comment]
Right now we don't have any cmdlet that does what you're asking for, I would formally invite you to create a formal request thru the SPO user's voice in this link: https://sharepoint.uservoice.com/

**Comment by yogkumgit** [comment]
@macslui  Thank you very much for your kind feedback. Considering your valuable feedback and as suggested by @j0rt3g4  please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
