### ISSUE TITLE
[Skype]Error when running New-CsOnlineApplicationEndpoint 

### ISSUE THREAD

**Issue by odd-mithril** [MicrosoftDocs/office-docs-powershell#2637]
When i run the  script:
New-CsOnlineApplicationEndpoint   
-ApplicationId "guid"  
-Name "sampleapp2" 
-Uri "sip:sample2@mytenant.onmicrosoft.com" 
-Tenant "guid"

Below is the error:

Cmdlet 调用错误
    + CategoryInfo          : NotSpecified: (:) [New-CsOnlineApplicationEndpoint], CmdletInvocationException
    + FullyQualifiedErrorId : 处理 cmdlet 请求时出错,Microsoft.Rtc.Management.Hosted.PlatformService.NewPlatformServiceAppEndpointConfigCmdlet
    + PSComputerName        : admin0f.online.lync.com

{
  "error":{
    "code":"","message":"An error has occurred.","innererror":{
      "message":"Application: '019cfa47-bc9c-4bda-8ab4-4c9096a756fe'","type":"Microsoft.Skype.EnterpriseVoice.CbdService.DataAccess.EntityNotFoundException","stacktrace":"   at Microsoft.Skype.EnterpriseVoice.Common.Contracts.CheckNonNull[T,TException](T val, String msg
)\r\n   at Microsoft.Skype.EnterpriseVoice.CbdService.DataAccess.AppEndpointOperations.<ValidateInsertStateAsync>d__45.MoveNext() in D:\\a\\_work\\202\\s\\BVD\\CBD\\DataAccess\\Operations\\AppEndpointOperations.cs:line 1692\r\n--- End of stack trace from previous locati
on where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Skype.EnterpriseVoice.CbdService.DataAcce
ss.AppEndpointOperations.<InsertAsync>d__8.MoveNext() in D:\\a\\_work\\202\\s\\BVD\\CBD\\DataAccess\\Operations\\AppEndpointOperations.cs:line 111\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.E
xceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Skype.EnterpriseVoice.CbdService.Controller.BvdEntitiesAccessor`3.<AddEntity>d__5.MoveNext() in D:\\a\\_work\\202\\s\\
BVD\\CBD\\CBDService.FrontEnd\\Controller\\BvdEntitiesAccessor.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.Task
Awaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Skype.EnterpriseVoice.Common.OData.Controller.NavEntitiesController`2.<AddEntity>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System
.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack tra
ce from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.
ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter
.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionD
ispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"
    }
  }
}

Can someone give suggestions?
Thank everyone so much.

**Comment by PrasenjitSaha** [comment]
I also got same error.

**Comment by odd-mithril** [comment]
> I also got same error.

Does the error message contains "D:\a\_work\202\s\BVD\CBD\DataAccess\Operations\AppEndpointOperations.cs"

**Comment by get-itips** [comment]
Hi @odd-mithril   thanks for your feedback,  I see that this wouldn't cause a change in documentation.  @yogkumgit can you kindly help here?

**Comment by yogkumgit** [comment]
@odd-mithril  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
