### ISSUE TITLE
Scope of this command

### ISSUE THREAD

**Issue by jtpaulson** [MicrosoftDocs/office-docs-powershell#2640]
Is the URL parameter scoped to a single site collection or the tenant?  If I am looking to monitor the health of SPO and One Drive for business sites, do I target the tenant admin URL, the one drive sites managed path, or each individual One Drive site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4df1d574-df84-cd28-4f7e-f113b71a7b15
* Version Independent ID: c5d02e48-eef1-c4fe-6aa2-5778629274d0
* Content: [Get-PnPHealthScore (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnphealthscore?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPHealthScore.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPHealthScore.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot unassign @yogkumgit

**Comment by j0rt3g4** [comment]
Hello @jtpaulson 
I've added an example 3 that makes clears the scope of the URL parameter, and defined it as it should have been.

The cmdlet receives a single Url parameter so you'd need to get the Onedrive for business  *my addresses* and then used them, I've created an advanced example to get this done.

**Comment by j0rt3g4** [comment]
@yogkumgit  [PNP PR #1989](https://github.com/SharePoint/PnP-PowerShell/pull/1989)

**Comment by johnofsaints** [comment]
In the past 30 days, the health score for the SharePoint top level of one Dubai customer, 
was always at high(unhealthy) levels during UK working hours. 

The same SharePoint website wasn't even being used in production yet. 

Does this mean that the scope of the command is to monitor the health of a server that is being shared by other Microsoft customers? Can we use this information to justify latency in the customer SharePoint website and raise the issue to Microsoft? 

[https://github.com/johnofsaints/SPO365mon/raw/master/SPO365man%20Dashboard.jpg](30SPHealthMonitor)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @jtpaulson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
