### ISSUE TITLE
Example 1

### ISSUE THREAD

**Issue by Bjorn80** [MicrosoftDocs/office-docs-powershell#2644]
You forgot to save the page after adding the example^^

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 697aeb1e-aa03-92a8-e488-c87d5ba6f4d4
* Version Independent ID: 114f4cb4-fbad-f50f-ec82-2495764e26c8
* Content: [Stop-SPDistributedCacheServiceInstance (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/stop-spdistributedcacheserviceinstance?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Stop-SPDistributedCacheServiceInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Stop-SPDistributedCacheServiceInstance.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me.

@Bjorn80 what you see is actually correct/intentional. While the cmdlet exists, it shouldn't be used in this form. This is why the example is blank and below that you see "Please see referenced article instead of using this cmdlet directly.".

**Comment by Bjorn80** [comment]
@tseward  Ok, thanks for info.
