### ISSUE TITLE
PrivacyMode parameter value incorrect

### ISSUE THREAD

**Issue by gunterda** [MicrosoftDocs/office-docs-powershell#2685]
When setting the PrivacyMode the correct value is "opt-out" and not "optout"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9022a-0dc1-19d3-0eee-deb2b354852b
* Version Independent ID: 4291c5c9-0c3c-6f14-15ee-fcf4ad3b7c8d
* Content: [Set-UserAnalyticsConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/reporting/set-useranalyticsconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/reporting/Set-UserAnalyticsConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/reporting/Set-UserAnalyticsConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gunterda, all of the values for the PrivayMode parameter were wrong. They should be:

- Excluded (not Exclude)

- Opt-In (not OptIn)

- Opt-Out (not OptOut)

Thanks for the feedback.
