### ISSUE TITLE
"The '<' operator is reserved for future use." error thrown w/ "Get-MessageTrace -MessageId <...XXX@...XXX....namprd03.prod.outlook.com>

### ISSUE THREAD

**Issue by bingoglossy** [MicrosoftDocs/office-docs-powershell#2686]
"The '&lt;' operator is reserved for future use." error thrown w/ "Get-MessageTrace -MessageId &lt;...XXX...@...XXX....namprd03.prod.outlook.com&gt;

Under "-MessageId" above there is "Be sure to include the full Message ID string. This may include angle brackets." but clearly the error it throws above does not jive with the documentation.

Please fix this or point out what I'm not seeing.

Thanks!

P.S. Full text from pwsh with PII redacted:

"Get-MessageTrace -MessageId &lt;...XXX...@...XXX....namprd03.prod.outlook.com&gt;
At line:1 char:29
+ Get-MessageTrace -MessageId &lt;...XXX...@...XXX....@X ...
+                             ~
The '&lt;' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3d7f9c1-78f0-5869-2e87-94c56c914316
* Version Independent ID: f7927615-71e8-069b-d2f3-0cae30092cd1
* Content: [Get-MessageTrace (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/get-messagetrace?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Get-MessageTrace.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Get-MessageTrace.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bingoglossy, does it work if you surround the MessageID value in quotes?

```
Get-MessageTrace -MessageId "<...XXX...@...XXX....namprd03.prod.outlook.com>"
```

It should work with angle brackets (or anything else) if the value is surrounded by quotes.

**Comment by bingoglossy** [comment]
Chris, that was it!
I humbly ask that an example be added to:
https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/get-messagetrace?view=exchange-ps
and all of the other reference locations so it can be made easy for others.
Thanks!

**Comment by chrisda** [comment]
@bingoglossy, I updated the MessageID parameter description.

Thanks for the feedback.
