### ISSUE TITLE
Please update and- or refer to MFA 

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/office-docs-powershell#2691]
Microsoft pushes really HARD for all Admins to use MFA and will soon ENFORCE it for all Azure admins. Please update this document as the above does NOT work when you do as Microsof asks, see

https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@blouwagie Thank you for your feedback. Would you be able to point us on which part of the document needs a change? I was able to connect to the module as mentioned in the document, 

If you don't receive any errors, you connected successfully. A quick test is to run an Exchange Online cmdlet, for example, Get-Mailbox, and see the results.

If you receive errors, check the following requirements:

1)To help prevent denial-of-service (DoS) attacks, you're limited to three open remote PowerShell connections to your Exchange Online organization.

2)The account you use to connect to Exchange Online must be enabled for remote PowerShell. 

3)TCP port 80 traffic needs to be open between your local computer and Office 365. It's probably open, but it's something to consider if your organization has a restrictive Internet access policy.

**Comment by woelfi22** [comment]
Following this guide gives me:

PS C:\Users\Admin_******> $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.o
ffice365.de/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
New-PSSession : [outlook.office365.de] Connecting to remote server outlook.office365.de failed with the following
error message : WinRM cannot complete the operation. Verify that the specified computer name is valid, that the
computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows
access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote
computers within the same local subnet. For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:12
+ $Session = New-PSSession -ConfigurationName Microsoft.Exchange -Conne ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotin
   gTransportException
    + FullyQualifiedErrorId : WinRMOperationTimeout,PSSessionOpenFailed

**Comment by woelfi22** [comment]
I forgot to mention: it worked until very recently, we have changed nothing, on my firewall log I see outlook.office365.de not answering my outgoing request.

**Comment by msbemba** [comment]
@woelfi22  Looks like you are not using the MFA module which could be the part of the problem.

As mentioned in Note in our document, If using MFA or Modern Auth use the below method:- https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps

**Comment by woelfi22** [comment]
Well we never used MFA, and it worked perfectly. What has changed? Apart from that, I hate to click buttons that say "configure" in O365 Admin Backend (under "Hybrid" ) without any information about what that button does. Obviously more than just "download".

**Comment by yogkumgit** [comment]
@blouwagie  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by VNJoe** [comment]
FIX YOUR DOCUMENT!
