### ISSUE TITLE
Point to the need to connect via MFA

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/office-docs-powershell#2692]
Microsoft pushes really HARD for all Admins to use MFA and will soon ENFORCE it for all Azure admins. Please update this document as the above does NOT work when you do as Microsof asks, see

https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f089a8d5-643e-527e-3f5e-93ee4b7660e0
* Version Independent ID: 848584ea-f6f0-340d-f65d-c58ee19181ed
* Content: [Get-DistributionGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/get-distributiongroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Get-DistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Get-DistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@blouwagie  it is same as https://github.com/MicrosoftDocs/office-docs-powershell/issues/2691 raised by you. Advise to reach out to support.

**Comment by yogkumgit** [comment]
@blouwagie Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
