### ISSUE TITLE
Adding multiple users to team groups

### ISSUE THREAD

**Issue by kpinel** [MicrosoftDocs/office-docs-powershell#2694]
The documentation isn't clear but is there an option, comma separated list as per add-adgroupmember, or do I need to create a for/next loop?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da0c53f2-1c62-14f6-6371-f54bf86b0c24
* Version Independent ID: aac162db-a9c0-fbfb-dd40-526e94d3bef8
* Content: [Add-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamuser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by k33bz** [comment]
Add-ADGroupMember supports an array for adding multiple users as shown in the documentation as:   [-Members] <ADPrincipal[]>
With that in mind, Add-TeamUser only takes in a string, not an array. According to this documentation, you would need to put Add-TeamUser in an array.
To change that behavior you can submit feedback at https://microsoftteams.uservoice.com

**Comment by get-itips** [comment]
Hi @kpinel thanks for your comments, as @k33bz example says, currently there is no way to pass an array to Add-TeamUser, but you could create a for loop with it in the meantime. Also as @k33bz says, you could submit this idea to uservoice. Hope this information has helped you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @kpinel 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
