### ISSUE TITLE
Connect via OAuth...

### ISSUE THREAD

**Issue by jmcadams-r7** [MicrosoftDocs/office-docs-powershell#2696]
Hi all, 

I'm in a situation where my script won't be able to give the user feedback to provide MFA credentials, and I'm bashing my head against the wall trying to figure out how to hit this with a delegated application account. The only workaround seems to be to provide a user without MFA enabled when coming from certain IPs. 

Is there an easier way to bypass MFA for delegated services or accounts to the compliance and security center?

**Comment by get-itips** [comment]
Hi @jmcadams-r7  thanks for your feedback,  I see that this wouldn't cause a change in documentation.  @yogkumgit can you kindly help here?

**Comment by yogkumgit** [comment]
@jmcadams-r7  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jmcadams-r7** [comment]
Is there a solution to this issue? Is it possible to use powershell to get into a machine with MFA without prompting the user for creds?
