### ISSUE TITLE
Remove hybrid using GUI

### ISSUE THREAD

**Issue by kgazar** [MicrosoftDocs/office-docs-powershell#2699]
Please i need to know how to remove hybrid configuration using ECP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 387a6dbf-23fc-9be7-60df-a6475a6826e0
* Version Independent ID: a006b07d-83bd-49d1-14f1-e9cd9bc09ba2
* Content: [Remove-HybridConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/remove-hybridconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/Remove-HybridConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/Remove-HybridConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by get-itips** [comment]
Hi @kgazar   thanks for your feedback,  I see that this wouldn't cause a change in cmdlet's documentation.  @yogkumgit can you kindly help here?

**Comment by yogkumgit** [comment]
@kgazar  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
