### ISSUE TITLE
Incorrect Output Reference

### ISSUE THREAD

**Issue by rjohnson13** [MicrosoftDocs/office-docs-powershell#2707]
The outputs section refers to a page with Exchange Management Shell cmdlet input and output types, but start-compliancesearch is not listed on that page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99da4279-1686-2fe4-c33b-a16857c14704
* Version Independent ID: f23de949-1abb-36a5-2b1c-b20bf0c968d4
* Content: [Start-ComplianceSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/start-compliancesearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/Start-ComplianceSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/Start-ComplianceSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for taking this over.
