### ISSUE TITLE
-WhatIF switch doesn't work

### ISSUE THREAD

**Issue by s1satya** [MicrosoftDocs/office-docs-powershell#2709]
Hi,

I am working on a script to assign conference numbers and in my testing i had -WhatIf switch but the script ended up setting the dialin bridge anyway, this seems to be a bug to me.  Can anyone validate this at Microsoft?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbbc1361-de46-0f01-f7cc-ea31425f6f45
* Version Independent ID: 626fd6f0-1a91-cae2-b5ca-083688a2ce39
* Content: [Set-CsOnlineDialInConferencingUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinedialinconferencinguser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineDialInConferencingUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineDialInConferencingUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by unkn0wnvariable** [comment]
Still not working. As above, I just discovered this whilst testing a script that unexpectedly made the changes when it was only supposed to be telling me if it would work or not.

**Comment by tomkau** [comment]
The WhatIf parameter was not implemented for this cmdlet.  A note can be added to the docs to indicated this.

**Comment by get-itips** [comment]
Hello @tomkau proposed thru a PR clarifying this. Please review. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @s1satya Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
