### ISSUE TITLE
Update to parameters

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/office-docs-powershell#2710]
Items are missing. For example SendAs under -AuditAdmin

Supported audit operations for Admin are None, Create, FolderBind, MessageBind,
SendAs, SendOnBehalf, SoftDelete, HardDelete, Update, Move, Copy, MoveToDeletedItems and UpdateFolderPermissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5b0c5d-0466-d55a-1f7b-0b2d25a316fd
* Version Independent ID: 07b0c093-eb6b-4834-3cd4-d8f2af6ca0f5
* Content: [Set-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by jantoney** [comment]
That 'supported' line I copied from a powershell error when connected to Exchange Online, however it seems that it also supports UpdateCalendarDelegation and UpdateInboxRules.
However MailboxLogin is not supported. May need a comment advising that it's OnPrem only?

**Comment by chrisda** [comment]
@jantoney, thanks for looking into this. I, too, did a bunch of investigation related to Exchange 2010 RU25, Exchange 2013 CU22, Exchange 2016 CU12, Exchange 2019 CU1, and a E5 tenant (no preview or flighting).

Too much to list here, but there were values missing, and the default values were a lot of times different across the various environments. I updated the parameter descriptions accordingly.
