### ISSUE TITLE
Please provide more information to possible values

### ISSUE THREAD

**Issue by Annyya** [MicrosoftDocs/office-docs-powershell#2712]
Is there a website about more information to the possible values? Please give an example how to set fields viable/not visable in a view or sorting/filtering by fileds. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68f7e89f-5efe-eb73-121b-51218829022b
* Version Independent ID: 061e5fa4-a472-4e62-f691-9b8cc4cff705
* Content: [Set-PnPView (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpview?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPView.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPView.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Annyya thanks for your feedback.
You would need to use the ViewQuery property, I encourage you to dig into that.
Also, I created a PR to improve the cmdlet's documentation based on your feedback.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Annyya Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
