### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/office-docs-powershell#2722]
I wish docs.microsoft.com could find another way to make long tables navigable.  The horizontal scrollbar is always at the bottom and there's no easy way to scroll side-to-side when you're dealing with an entry high up in the table.  I'm on a 16x9 monitor and still can't view the entire width of the table on this document.  I usually wind up highlighting the rows I'm interested in and pasting them to Excel or a Word table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/recipient-filters/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@FC-EricWeller, I agree. TechNet had the same problem (the horizontal scroll bar didn't float in a relative position at the bottom of your current vertical position in the topic; it was only available at the absolute bottom of the topic.)

The secret workaround is to click anywhere inside the table, and you can use the left and right arrow keys on the keyboard to scroll horizontally. I hope this helps.
