### ISSUE TITLE
example 2 has incorrect parameter name

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/office-docs-powershell#2724]
The parameter of -userid in example 2 is incorrect, it should be -identity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5114258-0905-68ac-ab72-1a379c2cbcba
* Version Independent ID: 6cbf3f1c-99f7-53d4-be30-5cc3ffbeb842
* Content: [Get-CsMeetingMigrationStatus (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csmeetingmigrationstatus?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsMeetingMigrationStatus.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsMeetingMigrationStatus.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by jamesrhea** [comment]
@TorrenManson, based on the remainder of the doc, it looks like you're correct. There is no `-UserId` parameter. I'll make this update. Thanks for the catch!
