### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by maruthigadde** [MicrosoftDocs/office-docs-powershell#2730]
user1@contoso.harepoint.com  -  s is missing in sharepoint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0de85f88-fd9e-ee72-9e0a-28480c2306d2
* Version Independent ID: e314a2e5-4f2a-a251-0e82-a4b238d918a8
* Content: [Export-SPOQueryLogs (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/export-spoquerylogs?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Export-SPOQueryLogs.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Export-SPOQueryLogs.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by maruthigadde** [comment]
Example 1 exports the query log for a user who has the e-mail address user1@contoso.harepoint.com to the two files user1@contoso.sharepoint.com_queries.csv and user1@contoso.sharepoint.com_personalQueries.csv, in the current working folder.

**Comment by jamesrhea** [comment]
Thanks for pointing out the typo, @maruthigadde. I'll get this fixed.
