### ISSUE TITLE
Incomplete Documentation

### ISSUE THREAD

**Issue by rjohnson13** [MicrosoftDocs/office-docs-powershell#2736]
There is incomplete documentation regarding this cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49fd66d7-4607-7c61-2d7d-ff71272c587c
* Version Independent ID: 77d487a4-b22c-49d1-123b-4c07f45eaa57
* Content: [Invoke-ComplianceSearchActionStep (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/invoke-compliancesearchactionstep?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/Invoke-ComplianceSearchActionStep.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/Invoke-ComplianceSearchActionStep.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rjohnson13, thanks for the feedback. Apparently, this cmdlet relates to a feature that isn't ready yet, so I've change pretty much everything in the topic to say, "This cmdlet is reserved for internal Microsoft use."
