### ISSUE TITLE
How do you get the results from start-managedFolderAssistant

### ISSUE THREAD

**Issue by SeaGT** [MicrosoftDocs/office-docs-powershell#2741]
I have manually run the start-managedFolderAssistant on several users mailboxes every day for the last 5 days. Multiple folders should be getting archived but nothing is occurring, why?  Why don't you include several examples of using this command AND tell users how they will confirm that the command worked?

**Comment by dariomws306** [comment]
Hi @SeaGT , thank you for your feedback!

I am adding some related link to help on MRM troubleshooting.

You can check some information with Export-MailboxDiagnosticLogs -ExtendedProperties and you can see in Outlook with Retention Policy is applying to your folders.

**Comment by yogkumgit** [comment]
@chrisda please review this PR 2929 and merge if it meets your expectations.

**Comment by chrisda** [comment]
Done. Closing.
