### ISSUE TITLE
Wrong information about Autodiscover service connection point

### ISSUE THREAD

**Issue by SignorelliDenis** [MicrosoftDocs/office-docs-powershell#2742]
The text says that "The Autodiscover service connection point pointer resides in Active Directory and contains the names of the Exchange Web Services URLs." 

As far as I know that's not true, the Service Connection Point created by Export-AutoDiscoverConfig cmdlet contains only the information about "LDAP://targetdomain" in the ServiceBindingInformation attribute and the "accepted domains" in the keyword attribute.  There is nothing about Exchange Web Services.

Ref: https://blogs.technet.microsoft.com/exchange/2008/02/13/configuration-tips-and-common-troubleshooting-steps-for-multiple-forest-deployment-of-autodiscover-service/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6df92f58-d91f-2ca9-9b4a-8c1f05ac7dae
* Version Independent ID: 6abe45ef-c9b2-27b4-66f7-4f7d9eeadd73
* Content: [Export-AutoDiscoverConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/Export-AutoDiscoverConfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Export-AutoDiscoverConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Export-AutoDiscoverConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws306** [comment]
Hi @SignorelliDenis , thank you for your feedback!

I am fixing this.

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR 2930 if you find it in order.

**Comment by chrisda** [comment]
Done. Closing.
