### ISSUE TITLE
Enclose with quotes.

### ISSUE THREAD

**Issue by ingjemch** [MicrosoftDocs/office-docs-powershell#2744]
The Message ID values should be enclosed in quotes (" or ') because if you type the command as given in the example, it will fail telling you that &lt; or &gt; characters are reserved for further use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 258342bd-0747-ae87-67f6-d3224d4e8b26
* Version Independent ID: 253abb29-229d-654e-f4ca-f9314947fa4f
* Content: [Get-QuarantineMessage (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/get-quarantinemessage?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Get-QuarantineMessage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Get-QuarantineMessage.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ingjemch, OK, fixed.

Thanks for the feedback.
