### ISSUE TITLE
Get-MessageTrace is missing results unless searching windows is 30 minutes.

### ISSUE THREAD

**Issue by zaicnupagadi** [MicrosoftDocs/office-docs-powershell#2750]
Hello, all has been described here https://paweljarosz.wordpress.com/2019/02/06/get-messagetrace-exchange-online-and-lots-of-missing-results-workaround/. Generally happened to me a few times, so decided to let you guys know, when searching for results I am only able to find particular message when the search windows is 30 minute. Otherwise when pipelining the results by | ? {$_.messageid -match ...} or | ? {$.sender -match..} doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3d7f9c1-78f0-5869-2e87-94c56c914316
* Version Independent ID: f7927615-71e8-069b-d2f3-0cae30092cd1
* Content: [Get-MessageTrace (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/get-messagetrace?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Get-MessageTrace.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Get-MessageTrace.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by zaicnupagadi** [comment]
I think we might close it - I need to use pagination for this, just saw this.

**Comment by dariomws306** [comment]
Hi @AndreaBarr , could you close it? It's not a real issue based on the last comment.

Thank you so much!
