### ISSUE TITLE
Missing preposition?

### ISSUE THREAD

**Issue by Loomb13** [MicrosoftDocs/office-docs-powershell#2752]
Hello!
The sentence below is missing the preposition afer exist. S.b either in or within&
 
Parameters that exist different parameter sets are mutually exclusive (they can't be used together in the same command).

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: cbe6e195-f640-0f1b-dae0-1d5ed62da207
* Version Independent ID: fa3de13d-0fab-7a99-3346-1f7764686781
* Content: [Синтаксис командлетов Exchange](https://docs.microsoft.com/ru-ru/powershell/exchange/exchange-server/exchange-cmdlet-syntax?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/exchange-cmdlet-syntax.md](https://github.com/MicrosoftDocs/office-docs-powershell.ru-RU/blob/master/exchange/docs-conceptual/exchange-server/exchange-cmdlet-syntax.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Loomb13, you are correct. I took the opportunity to rewrite that area of text.

Thanks for the feedback.
