### ISSUE TITLE
The "Applies to field" is incorrect

### ISSUE THREAD

**Issue by peferre** [MicrosoftDocs/office-docs-powershell#2756]
The following parameters are not available to Exchange Online as suggested in the "Applies to:" fields:
[-DomainController &lt;Fqdn&gt;]; [-Features &lt;None | MultiBatch | Endpoints | UpgradeBlock | PAW&gt;]; [-MaxConcurrentMigrations &lt;Unlimited&gt;]; [-MaxNumberOfBatches &lt;Int32&gt;] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91c983a-cdd4-1ba3-dfa7-0110d8c656a0
* Version Independent ID: 0205b3c8-3170-aab7-ca52-0b9195c52131
* Content: [Set-MigrationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/Set-MigrationConfig?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/Set-MigrationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/Set-MigrationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@peferre it appears that the Set-MigrationConfig cmdlet went from on-prem only to on-prem + cloud in the semi-recent past (note the "This cmdlet is available only in on-premises Exchange." disclaimer in the introduction). I cleaned up the topic as you described (I fully completed the remaining work required to switch the topic to on-prem + cloud).

Thanks for the feedback.

**Comment by peferre** [comment]
Thanks Chris,

That helps a lot! :) Great job!

Best regards,

Pedro

Get Outlook for Android<https://aka.ms/ghei36>
