### ISSUE TITLE
What are the max values for IPListBlocked?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/office-docs-powershell#2757]
Is this limited by entries, or overall attribute size, or? In my testing, I was able to add 1173 IPs, but since that is such an unusual number, I wanted to confirm it is a reliable one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3ab3f0-cc05-e279-8876-6da0b323bcac
* Version Independent ID: bfb49814-d60b-564a-25cc-f902dfa42b10
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Mike-Crowley according to the same question at the following link, and the TechNet blog in the last answer to the thread, the limit for any value like this is approximately 1200 entries (or 1176, according to the other guy's testing of this specific parameter).

https://techcommunity.microsoft.com/t5/Exchange/Limits-for-maximum-addresses-in-the-IPListBlocked-when-using-set/td-p/108826

**Comment by Mike-Crowley** [comment]
Thank you. I feel like this information belongs in the article here.


-Mike Crowley

________________________________

**Comment by chrisda** [comment]
OK, I added it, but I fear I've opened a big can of worms as it appears that any property like this has the upper limit of 1200 entries, and there are a lot of properties like this. I also don't like the fact that I need to say "approximately 1200 entries".

**Comment by Mike-Crowley** [comment]
When the limit is approximate like this, its usually due to the underlying attribute/storage size or something, since there obviously is some sort of specific limit somewhere. Perhaps you could inquire into that and list it instead?
