### ISSUE TITLE
Documentation Feedback

### ISSUE THREAD

**Issue by jitsvjoseph** [MicrosoftDocs/office-docs-powershell#2759]
SharePoint 2019 is given in the section "Product that applies to" under the description of the property "-PartitionMode". As Multi Tenancy is not supported in SP2019, this should not be applied to SP2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7da900-06f8-efbe-49bf-ff3f5706cc94
* Version Independent ID: fde41041-2591-01b8-459d-2f9642682189
* Content: [Register-SPWorkflowService (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/register-spworkflowservice?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Register-SPWorkflowService.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Register-SPWorkflowService.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@jitsvjoseph thank you for your feedback. You are correct, and I have made the change and in the process of republishing article.  thanks
