### ISSUE TITLE
Filterable Properties -> Guid would be awesome if it accepted wildcards

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#2765]
I noticed recently that all AD objects are pretty much perfectly 'load-balanced' by the first character of the Guid.  That is, take all your mailboxes:

>$Mailboxes = Get-Mailbox -ResultSize:Unlimited

Then, group them by the first character of the Guid (objectGuid):

>$Mailboxes | select @{n='Guid_1st_Char';e={$_.Guid.ToString().chars(0)}} | group Guid_1st_Char | sort Name

Prepare to be amazed!!.  Now, this gives everyone in the world, 16 near-equal-length groupings of their objects - GREAT!!.

Now.. if the Guid filterable property could accept wildcards, we could do:

>$Guid0 = Get-Mailbox -Filter "Guid -like '0*'"
>$Guid1 = Get-Mailbox -Filter "Guid -like '1*'"
..and so on. 

But we can't because Guid doens't accept wildcards :(.  Would be nice!

**Comment by yogkumgit** [comment]
@JeremyTBradshaw   Thank you very much for your kind feedback. Considering your valuable feedback, we have logged this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
User Voice Link: https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/15219555-granular-permissions-on-user-properties-at-a-prope
