### ISSUE TITLE
SharePoint Online

### ISSUE THREAD

**Issue by DRamalho92** [MicrosoftDocs/office-docs-powershell#2770]
When using the command Get-PnPRecycleBinItem the property FileLeafName don't exist. It works if you use LeafName instead. 

Get-PnPRecycleBinItem | ? LeafName -like "*.docx" | Clear-PnpRecycleBinItem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8ffc74-6836-0a88-f1e2-2962b487ca4e
* Version Independent ID: 89967280-3b45-01d3-99c5-e9854da371fa
* Content: [Clear-PnPRecycleBinItem (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/clear-pnprecyclebinitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Clear-PnpRecycleBinItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Clear-PnpRecycleBinItem.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DRamalho92 **Thanks for your feedback.**
As the article indicates in _Outputs section_, this cmdlet returns a Microsoft.SharePoint.Client.RecycleBinItem object. Please see here the properties that it exposes https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/ee536442(v%3doffice.15)

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @DRamalho92 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by sparkitect** [comment]
@officedocsbot - Requesting reopen since the text in EXAMPLE 1 is still incorrect. The documentation linked to by @get-itips indicates that FileLeafRef is not a valid property of a Microsoft.SharePoint.Client.RecycleBinItem while LeafRef is...

**Comment by get-itips** [comment]
Hello @sparkitect Jim, how are you? Hope you are doing great.
We are now requesting a new procedure for PnP cmdlets & Documentation issues, if you feel this needs to be reopen, I need to kindly redirect you to this [other resource](https://github.com/SharePoint/PnP-PowerShell/), please create an issue there, PnP cmdlets are community-driven, a member of the community will pick your request there and do the follow-up.
Thank you

**Comment by sparkitect** [comment]
Hi @get-itips,

Are you saying that if there is a technical error in the text on this page (https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/clear-pnprecyclebinitem?view=sharepoint-ps) then I should't use the Feedback form on 'This page' but should go somewhere else and try to track down the corresponding source code file and enter an Issue there?

Seems a bit confusing and convoluted to me...

**Comment by get-itips** [comment]
> Hi @get-itips,
> 
> Are you saying that if there is a technical error in the text on this page (https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/clear-pnprecyclebinitem?view=sharepoint-ps) then I should't use the Feedback form on 'This page' but should go somewhere else and try to track down the corresponding source code file and enter an Issue there?
> 
> Seems a bit confusing and convoluted to me...

Hello @sparkitect I can understand your frustration, it is not my decision, I know the team is working on a fix, however, currently, it is the way to go. Thank you

**Comment by sparkitect** [comment]
Hi again, @get-itips.

The 'other resource' link you provided me just goes to the root of the repository. From there I go to Documentation, which just informs me that the documentation has been moved here (docs.microsoft.com). 

I appreciate you taking the time on this; I love to help, but unfortunately, I don't have the bandwidth to figure this out right now.

But at least I know the documentation wrong, thanks to @DRamalho92 who originally posted the issue ;)

**Comment by get-itips** [comment]
@sparkitect Thanks for understanding, this is the exact [link](https://github.com/SharePoint/PnP-PowerShell/issues/new).
