### ISSUE TITLE
BulkThreshold is not for internal use

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/office-docs-powershell#2772]
It can be set through the EAC and from powershell, it's the threshold for bulk mail. It's the BCL threshold, use a lower number to classify more bulk mail as spam.

https://docs.microsoft.com/en-us/office365/securitycompliance/bulk-complaint-level-values

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de4b3451-117a-6079-1c0c-e305438e8b2f
* Version Independent ID: 6d85b0b2-2fe2-77db-baee-17303ae27d5a
* Content: [New-HostedContentFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/new-hostedcontentfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/New-HostedContentFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/New-HostedContentFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jonwbstr, the parameter was documented in Set-HostedContentFilterPolicy, but not New.

Thanks for the feedback.
