### ISSUE TITLE
Operation is not multi-value without hidden param LogicalOperationName

### ISSUE THREAD

**Issue by cammurray** [MicrosoftDocs/office-docs-powershell#2776]
Using the 'operation' param, you cannot specify multiple values as the documentation states, as this relies on another param called 'LogicalOperationName' which is not exposed to the user.

Attempting to use comma seperated values will result in:
Multiple operations provided . Please provide a logical operation name
    + CategoryInfo          : NotSpecified: (:) [New-ProtectionAlert], MissingLogicalOperationNameException
    + FullyQualifiedErrorId : [Server=ME1AUS01WS008,RequestId=1d097dd3-ccf7-419b-b0e7-243b1525f721,TimeStamp=9/02/2019 12:01:49 AM] [FailureCategory=Cmdlet-MissingLogicalOperationNam
   eException] E669639E,Microsoft.Office.CompliancePolicy.Tasks.NewProtectionAlert
    + PSComputerName        : aus01b.ps.compliance.protection.outlook.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377db2e9-ac51-6e70-b3a8-93ef91fa537a
* Version Independent ID: c141a958-2cd7-1596-fbee-ff69e773a1ba
* Content: [New-ProtectionAlert (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/new-protectionalert?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance/New-ProtectionAlert.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance/New-ProtectionAlert.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by cammurray** [comment]
Full command below:

`PS C:\Users\camurray> New-ProtectionAlert -Category AccessGovernance -Name "Privilege Escalation 2" -NotifyUser cam@filtered.info -ThreatType Activity -AggregationType None -Operation "Add role member to role","GrantAdminPermission"

Multiple operations provided . Please provide a logical operation name
    + CategoryInfo          : NotSpecified: (:) [New-ProtectionAlert], MissingLogicalOperationNameException
    + FullyQualifiedErrorId : [Server=ME1AUS01WS008,RequestId=1d097dd3-ccf7-419b-b0e7-243b1525f721,TimeStamp=9/02/2019 12:01:49 AM] [FailureCategory=Cmdlet-MissingLogicalOperationNam
   eException] E669639E,Microsoft.Office.CompliancePolicy.Tasks.NewProtectionAlert
    + PSComputerName        : aus01b.ps.compliance.protection.outlook.com`

**Comment by chrisda** [comment]
@cammurray, very interesting. The Operation parameter is of Type MultiValuedProperty, so it does accept multiple values. But the parameter interactions for the cmdlet demand that multiple values for Operation also require the unavailable LogicalOperationName parameter.

Should I just remove the line about it accepting multiple values?

**Comment by cammurray** [comment]
Hey @chrisda 

Well, you have a little bit of a dilemma there!

I don't believe LogicalOperationName is exposed as you've mentioned and it certainly isn't documented on the page.

So I guess this is a question of if we want the documentation to be truly **technically** correct based on what the property is or **theoretically** correct based on what you can do. 

I would say that we should remove the line about accepting multiple values until we/and if we present out LogicalOperationName. That would be my vote. Assists removing confusion from a user perspective.

**Comment by chrisda** [comment]
@cammurray, I worded my way around it (technically accepts multiple values but doesn't). Thanks for the feedback.

**Comment by AlMargoi** [comment]
@chrisda , @cammurray 1 year later, the documentation still states the same (multiple values accepted) while we cannot add multiple values with the "Operation" parameter. 
Is there an update you could share?

**Comment by eric-lavalley** [comment]
@chrisda @cammurray More than 2 years out here and the documentation is still wrong/the Operation parameter does not accept multiple values. Any updates?

**Comment by chrisda** [comment]
@AlMargoi, @eric-lavalley, Yikes!. It looks like I mistakenly updated the Operation (singular) parameter in the wrong topic (New-ActivityAlert). Strange how no one complained about how _that_ description was now wrong, nor did it match the corresponding Operation parameter description on Set-ActivityAlert. Anyway, I fixed New-ActivityAlert back to how it was, and I replaced the 'multiple values' line with the following text in New/Set-ProtectionAlert:

> Although this parameter is technically capable of accepting multiple values separated by commas, multiple values don't work.

That fixes the documentation side. If you want to get traction about actually allowing the parameter to accept multiple values, you need to open a support case. That will bring the issue to the forefront, and the product engineers will need to make a decision about it.
