### ISSUE TITLE
Connect-EXOPSSession does not work when User Profile Disks (UPDs) are enabled

### ISSUE THREAD

**Issue by andy2002a** [MicrosoftDocs/office-docs-powershell#2783]
When I attempt to use Connect-EXOPSSession on an RDS server that has User Profile Disks enabled I get the following error:

New-ExoPSSession : Service returned error. Check InnerException for more details
At C:\Users\XXXXXXXX\AppData\Local\Apps\2.0\24VQBVLG.GAB\944JPN15.MGR\micr..tion_1975b8453054a2b5_0010.0000_10d85008035862c6\CreateExoPSSession.ps1:292 char:30
+ ... PSSession = New-ExoPSSession -UserPrincipalName $UserPrincipalName.Va ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], AdalServiceException
    + FullyQualifiedErrorId : Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException,Microsoft.Exchange.
   Management.ExoPowershellSnapin.NewExoPSSession

This does not occur on an identical server that does not have UPDs enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by KevinTechExec** [comment]
Please check the command 
````
winrm set winrm/config/client/auth @{Basic="true"}
````
When run on Windows 10 it returns

````
~ $ winrm set winrm/config/client/auth @{Basic="true"}
Error: Invalid use of command line. Type "winrm -?" for help.
````

**Comment by andy2002a** [comment]
> Please check the command
> 
> ```
> winrm set winrm/config/client/auth @{Basic="true"}
> ```
> When run on Windows 10 it returns
> 
> ```
> ~ $ winrm set winrm/config/client/auth @{Basic="true"}
> Error: Invalid use of command line. Type "winrm -?" for help.
> ```

I got the same error:

 ```
winrm set winrm/config/client/auth @{Basic="true"}
Error: Invalid use of command line. Type "winrm -?" for help.
```

**Comment by yogkumgit** [comment]
@andy2002a  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by RoyRK07** [comment]
Cmdlet will work below , please try

Should be run with single quote ''
winrm set winrm/config/client/auth '@{Basic="true"}'

**Comment by chrisda** [comment]
@KevinTechExec, @andy2002a, @RoyRK07, the topic describes how to run the command in a Command Prompt (i.e., a DOS window), and I even recently added bold formatting to call out that fact. It works correctly as written. Extra quotes are required only if you try to run the command in Windows PowerShell.
