### ISSUE TITLE
Recipient Type MailboxUser

### ISSUE THREAD

**Issue by Ful56uk** [MicrosoftDocs/office-docs-powershell#2789]
is MailboxUser incorrect, shouldn't it be usermailbox as recipient type for exchange online?

**Comment by chrisda** [comment]
@Ful56uk, what topic or context are we talking about? You are correct in that the RecipientType and/or RecipientTypeDetails parameters on the Get-Mailbox, Get-Recipient, and Get-User cmdlets use the value UserMailbox.

**Comment by Ful56uk** [comment]
Hi 

This page with the example

https://docs.microsoft.com/en-us/powershell/module/exchange/email-addresses-and-address-books/new-addresslist?view=exchange-ps

**Comment by chrisda** [comment]
@Ful56uk, thanks. I fixed it.
