### ISSUE TITLE
BlockUrls Parameter instructions wrong

### ISSUE THREAD

**Issue by AzureGuineaPig** [MicrosoftDocs/office-docs-powershell#2792]
Written as: The BlockUrls parameter specifies the URLs that are always blocked by Safe Links scanning. You can specify multiple values separated by semicolons.

Correction to be made: You can specify multiple values separated by commas. 

Using semicolons does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f989bf3c-3ed0-3dc2-3e9e-4643c85eec9f
* Version Independent ID: c14642cb-4623-8f30-cf51-6b8176a6893a
* Content: [Set-AtpPolicyForO365 (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-atppolicyforo365?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Set-AtpPolicyForO365.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Set-AtpPolicyForO365.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@AzureGuineaPig, OK I fixed it as you described.

Thanks for the feedback.
