### ISSUE TITLE
A way to hide one or more specific themes

### ISSUE THREAD

**Issue by Christian-Stahl** [MicrosoftDocs/office-docs-powershell#2794]
As my understanding we can hide all default themes, what's about to just hide one or more specific themes by it's name? In my case I want to create let's say four custom themes + keep four of the default themes. Well I can copy the JSON from defaults I want to keep, and make custom out of them, but I do think it would be a nice option to hide the themes I don't want that my users should use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb86a30f-a479-7b2b-41b0-3f8acbbd17be
* Version Independent ID: fcde0b09-6c66-4439-023e-4ac346bb7568
* Content: [Get-SPOHideDefaultThemes (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spohidedefaultthemes?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHideDefaultThemes.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHideDefaultThemes.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by j0rt3g4** [comment]
The solution for this issue  PR #3099. Basically added the information about the author and DateTime as a note.

There's no such of action right now dear @Christian-Stahl, but it can be added using the User's voice or SPO https://sharepoint.uservoice.com/

**Comment by yogkumgit** [comment]
@j0rt3g4 Thank you very much for the contribution and updating the documentation with PR. @christian-Stahl Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
