### ISSUE TITLE
Is there a way we can update existing webpart

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/office-docs-powershell#2802]
Is there a way we can update existing web part? or do we have a PowerShell command which updates existing web part?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bffb6769-cd46-08c6-2685-bf81ae5023ef
* Version Independent ID: a58bc279-47f9-86b7-9709-19a8c210dcfb
* Content: [Add-PnPWebPartToWebPartPage (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpwebparttowebpartpage?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPWebPartToWebPartPage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPWebPartToWebPartPage.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ravick4u how are you?
**Thanks for your feedback**.
Currently, there is no cmdlet available to update an existing one, you can take a look at Set-PnpWebPartProperty though.

Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ravick4u 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
