### ISSUE TITLE
Optional parameters missing description

### ISSUE THREAD

**Issue by m3ch-mania** [MicrosoftDocs/office-docs-powershell#2804]
Some of the optional parameters (such as ClientAdalAuthOverride) are missing a description and instead have filler text such as "{{Fill ClientAdalAuthOverride Description}}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b940ec3-fba8-8b31-48b2-76092639d4c5
* Version Independent ID: e33808fa-72f8-5b61-2a30-7da4ac2dffc4
* Content: [Set-CsOAuthConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csoauthconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOAuthConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOAuthConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
Hi @m3ch-mania , thank you for your feedback.

I am applying some updates to the article based on your feedback.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @m3ch-mania Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
