### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by kingtamara** [MicrosoftDocs/office-docs-powershell#2805]
I'm currently trying to use the Add-PNPNavigationNode cmdlet to populate my navigation in the top nav bar.

I keep getting this error when I try to add new nodes under an existing one.

"Add-PnPNavigationNode : Method "GetNodeById" does not exist."

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @kingtamara Thanks for your feedback.
I could confirm in my lab that I was able to add a Navigation Node under an existing one using the article's example on the article.
Please be sure to run the latest version of the module.
Hope this information helps you.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @kingtamara 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
