### ISSUE TITLE
Product Feedback for SharePoint-PnP links to this repository

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/office-docs-powershell#2810]
[This site](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnpmicrosoftgraph?view=sharepoint-ps) links to the office-docs-powershell repo.

I guess it should link to https://github.com/SharePoint/PnP-PowerShell/issues instead?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Weishaupt Thanks for your comments.
Actually, as the documentation for the article is stored in office-docs-powershell repo it is ok and intended that the feedback _of the documentation_ points to it.
Hope this information clarifies it.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Weishaupt 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
