### ISSUE TITLE
Wrong description for Example 5 

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/office-docs-powershell#2811]
Example 5 claims that it will add demo@contoso.com as an *additional* owner to the group.

In oppose the documentation for the parameter `-Owners` states: The array UPN values of owners to set to the group. *Note: Will replace owners.*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7c0144-3d70-5812-617f-3ab914aca3eb
* Version Independent ID: f188ada0-7d29-0c95-fa51-c0a62a71a8d0
* Content: [Set-PnPUnifiedGroup (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpunifiedgroup?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPUnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPUnifiedGroup.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Weishaupt Thanks for your feedback.
I tested in a lab and could confirm what you submitted here, I created a PR to correct the documentation of the article.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Weishaupt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
