### ISSUE TITLE
Content type is read only

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/office-docs-powershell#2812]
I got an error when I try to remove a content type from the list.

Remove-PnPContentTypeFromList : The content type "&lt;mycontnettype&gt;" at "/&lt;mymanagedpath&gt;/&lt;mysite&gt;/&lt;mylist&gt;" is read only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4c7ee0d-9f58-e62f-4d12-55aaf5eace53
* Version Independent ID: 279235ea-0f9b-5a0a-5220-660e1c2b29a5
* Content: [Remove-PnPContentTypeFromList (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpcontenttypefromlist?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPContentTypeFromList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPContentTypeFromList.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ravick4u how are you? Thanks for your feedback.
I could reproduce the error and it is expected when the Content Type is set as Read Only. 
https://docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-contenttype

Please check if the content type that you are trying to delete is not read only.

Hope this information helps you.

Thanks.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ravick4u 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
