### ISSUE TITLE
Example of how to update Allowed list

### ISSUE THREAD

**Issue by Arcass** [MicrosoftDocs/office-docs-powershell#2816]
Hi, 
Would be helpful to include an example of how to update the allowed list as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8d01537-2e7a-b4d2-1cd8-d23070112dc6
* Version Independent ID: 52dc0d21-6d06-2a75-a801-8befbbb0eadc
* Content: [New-CsEdgeAllowList (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csedgeallowlist?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsEdgeAllowList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsEdgeAllowList.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
Hi @Arcass , thank you for your feedback.

These examples are under Set-CsTenantFederationConfiguration help. Please check example 2, 3 and 4 on:
https://docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps#examples

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @Arcass 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
