### ISSUE TITLE
Commands not working as expected

### ISSUE THREAD

**Issue by ramonabadea** [MicrosoftDocs/office-docs-powershell#2817]
Hi guys,

Could someone please review thes command and see if they are still up to date/working properly? 
 For the property -ShowPeoplePickerSuggestionsForGuestUsers when used with Set-SPOSite (and also with Set-SPOTenant) the results are not working as expected.

Looking forward for your actions!!
Best regards,
Ramona

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1c6b2b-5af6-acce-b7e8-bf784bb0973e
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by ramonabadea** [comment]
Super! Thanks so much! Please feel free to contact me directly if any other details are needed on this. Looking forward for your replies!

**Comment by j0rt3g4** [comment]
Hi @ramonabadea what is the error you're getting?
because I was not able to find any malfunction of the cmdlets in my environment.

Thank you for the report and I'd be waiting for more details.

**Comment by ramonabadea** [comment]
Hi Jose,

There is no error that I am receiving. It's just when I run the cmdlet it doesn't do what's expected.

Thanks

**Comment by j0rt3g4** [comment]
Hi @ramonabadea  This contact is not for documentation people, this should be validated with support or partner. So I'd recommend you to create a support ticket on the Administration panel on your O365 tenant

**Comment by yogkumgit** [comment]
@ramonabadea Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
