### ISSUE TITLE
Command not working as expected with some properties

### ISSUE THREAD

**Issue by ramonabadea** [MicrosoftDocs/office-docs-powershell#2818]
Hi guys,
Could someone please review these commands and see if they are still up to date/working properly?
I have used the following and they're not working as expected:
Set-SPOTenant -SearchResolveExactEmailOrUPN $true
Set-SPOTenant -UseFindPeopleInPeoplePicker $true
Set-SPOTenant -ShowPeoplePickerSuggestionsForGuestUsers $true
Please also add the proper documentation for all commands as for example the property SearchResolveExactEmailOrUPN does not have a proper description when checking on the help in PowerShell.
Looking forward for your actions!!
Best regards,
Ramona

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428a5954-392c-f7ad-bac4-553adf74e08e
* Version Independent ID: 44fdecf2-1977-3171-9d04-02c0fefb16c9
* Content: [Set-SPOTenant (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by ramonabadea** [comment]
Super! Thanks so much! Please feel free to contact me directly if any other details are needed on this. Looking forward for your replies!

**Comment by j0rt3g4** [comment]
I didn't found any issues with the boolean values, I've added examples on each, and the SearchResolveExactEmailOrUPN parameter is documented:

Please use: 
```powershell
get-help Set-SPOTenant -Detailed
```
and you'l get [http://prntscr.com/n0ermq](Imagel)

**Comment by ramonabadea** [comment]
Hi,

For example:     
1) Set-SPOSite -SearchResolveExactEmailOrUPN <$true | $false>
        Removes the search capability from People Picker.
        The valid values are:
        * Recently resolved names will still appear in the list.
        * False- Restores default search functionality.

As per documentation, this set to true should resolve names in People Picker and set to false from my understanding should not resolve names in People Picker? What does 'restore default search functionality' really means?

2) Set-SPOTenant -UseFindPeopleInPeoplePicker $true 

This parameter is not documented in Get-Help Set-SPOTenant -Detailed. The only documentation is on  https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps and honestly is not clear at all what this does. 

3) Set-SPOTenant -ShowPeoplePickerSuggestionsForGuestUsers $false should prevent guest users of appearing in People Picker, but it doesn't work. Try it yourself :).. And yes, I have cleared the cache and everything..

I am open to a conversation and more than that, to show you exactly how these cmdlets do not behave as expected.

**Comment by j0rt3g4** [comment]
### About 1. Set-SPOSite -SearchResolveExactEmailOrUPN <$true | $false>

_1. False (default) - Starts with/partial name search functionality is available. 
Disables starts with for all users/partial name search functionality for all SharePoint users, except SharePoint Admins._

- If you are a regular user, you can find people using the start with and the partial name functionality.
-  If you are an administrator, you can see people using the start with and the partial name functionality.

_
2. True - Disables starts with for all users/partial name search functionality for all SharePoint users, except SharePoint Admins._

- If you are a user, you won't be able to search people on the directory people with full UPN or partial.
- If you are an administrator, you can find people using the start with and the partial name functionality.

### 2 Set-SPOTenant -UseFindPeopleInPeoplePicker $true
It's documented probably in the version of the Get-Help that you have is not there. I tested it on mine and you're right is not there. Then I ran the update-Help, and it doesn't update it yet. So as a workaround use the -online parameter
PowerShell
Get-Help Set-SPOTenant -Online
```
### 3 Set-SPOTenant -ShowPeoplePickerSuggestionsForGuestUsers $false 

> should prevent guest users from appearing in People Picker, but it doesn't work. Try it yourself :). And yes, I have cleared the cache and everything.


This can be probably seen with the author of the cmdlet

**Comment by yogkumgit** [comment]
@ramonabadea Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
