### ISSUE TITLE
New-Team -Group fails when providing GroupId

### ISSUE THREAD

**Issue by rolleddice** [MicrosoftDocs/office-docs-powershell#2819]
When trying to convert a Group to Teams the documentation states that I should specify the GroupId in this parameter. When doing this I get an error

New-Team -Group &lt;GroupID&gt;

New-Team : Error occurred while executing 
Code: ItemNotFound
Message: Failed to execute MS Graph backend request GetGroupInternalApiRequest. The server failed to respond correctly. Response Code: NotFound, Reason: Reason: Not Found, Correlation headers: ***

When using New-Team -Group &lt;ExternalDirectoryObjectId&gt; it works correctly.

Is this correct or am I missing something?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
Hi @rolleddice , thank you for your feedback.

It's true, I have tested and you should use ExternalDirectoryObjectId.

**Comment by yogkumgit** [comment]
@Ken please merge this PR

**Comment by yogkumgit** [comment]
@kenwith Please review the PR and Merge it, if you find it suitable

**Comment by yogkumgit** [comment]
@officedocsbot close
