### ISSUE TITLE
Why can nobody make a good search function except google, and even they aren't good at it anymore.

### ISSUE THREAD

**Issue by Josh9001** [MicrosoftDocs/office-docs-powershell#2820]
![ms search](https://user-images.githubusercontent.com/47663530/52855419-400c4480-3119-11e9-9e3f-971caaf0e8fd.png)

**Comment by Josh9001** [comment]
"No results", even though I'm on the goddam page, had to search google to find it mind you, even though it was there the whole time.

**Comment by yogkumgit** [comment]
@Josh9001 Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
