### ISSUE TITLE
Command does not work as expected 

### ISSUE THREAD

**Issue by ramonabadea** [MicrosoftDocs/office-docs-powershell#2821]
Hi all,

I have this question, first of all: for the Identity parameter in the first example, where would we get the ID of the item if it is deleted (I want to refer here to the Audit Log)? 

Could you please inform, if possible, where would one find the item ID after it's deleted in the Audit Log of the deletion event (assuming we can't see the item in the Deleted Items in the RB - possible scenario: we can have a lot of items and could not find it in the list)? :) 
I noticed that the ObjectID in the Audit appears only as the path, thus can't be used.

Also, the example provided in the article, Get-PnPRecycleBinItem | ? FileLeafName -like "*.docx" | Restore-PnpRecycleBinItem is not quite right. If an user would try to use it, he won't succeed. 
The right way would be:
 Get-PnPRecycleBinItem | where -Property LeafName -like '*.docx'
 Get-PnPRecycleBinItem | ? {$_.LeafName -like '*.docx'}

Thank you in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a801b64d-a533-6c80-e8d2-8ceba6552945
* Version Independent ID: c1d2ada4-de0e-d434-b138-8fa1b904eef3
* Content: [Restore-PnPRecycleBinItem (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/restore-pnprecyclebinitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Restore-PnpRecycleBinItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Restore-PnpRecycleBinItem.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by ramonabadea** [comment]
Thanks.

**Comment by get-itips** [comment]
Hello @ramonabadea thanks for your feedback.
To obtain the Id needed for the Restore-PnPRecycleBinItem you need to use the Get-PnPRecycleBinItem cmdlet that outputs it to console.
I created a Pull Request to correct the 2nd example based on your feedback. Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ramonabadea Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
