### ISSUE TITLE
Add-PnPClientSideText adding html code not parsing base64 encoded images

### ISSUE THREAD

**Issue by cbadouin** [MicrosoftDocs/office-docs-powershell#2822]
Hi all,

I am trying to create new pages in SharePoint Online with the command **Add-PnPClientSideText** and successfully inserted html code with the **text parameter** like _Add-PnPClientSideText -text <html code>_. Now I am also trying to insert images which are base 64 encoded, e.g.  
`<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
    9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />`.
Sadly, this code seems to be ignored?! As a result, in the source code of the established site there is an empty image tag like `<img alt="Red dot" />`.

Is there a workaround or am I doing something wrong?
Thanks in advance!

**Comment by ravinleague** [comment]
Inserting Images is not implemented in the Add-PnPClientSideText. I had the same requirement and what I have done is replaced the <img .../> with an Image Web part using - 
Add-PnPClientSideWebPart -Page $pageWhereImageWPhastoBeAdded -DefaultWebPartType Image -WebPartProperties @{imageSource=$imageSrc}

**Comment by cbadouin** [comment]
> Inserting Images is not implemented in the Add-PnPClientSideText. I had the same requirement and what I have done is replaced the <img .../> with an Image Web part using -
> Add-PnPClientSideWebPart -Page $pageWhereImageWPhastoBeAdded -DefaultWebPartType Image -WebPartProperties @{imageSource=$imageSrc}

@ravinleague It's working! Thank you!!

**Comment by ravinleague** [comment]
But how do you change the image after adding it ?   
  

  
  

  
  
>

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @cbadouin thanks for your feedback.
As @ravinleague suggested and note that you already tried, you can use an Image webpart to accomplish that.
@ravinleague to update the webpart's image you could use Set-PnPClientSideWebPart with the PropertiesJson parameter
We will proceed closing this issue as this has no impact on documentation.
Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @cbadouin 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
