### ISSUE TITLE
Missing Event

### ISSUE THREAD

**Issue by JeanNetryValere** [MicrosoftDocs/office-docs-powershell#2824]
Hi, it seems there is a missing event switch parameter for "Opening or downloading documents, viewing items in lists, or viewing item properties". Many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce3e7e39-d315-4843-4af4-57c5040d509f
* Version Independent ID: 7e61202d-4b8c-3018-b161-f99890cc7724
* Content: [Set-PnPAuditing (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpauditing?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPAuditing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPAuditing.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @JeanNetryValere how are you? If you refer to Sharepoint Online that event is not available for audit, more information here https://support.office.com/en-us/article/View-audit-log-reports-b37c5869-1b47-4a82-a30d-ea20070fe527
But if you refer to Sharepoint on-premises I checked the source code of the cmdlet and does not include it, so no furthers edits will be done to the documentation.
In the future if the cmdlet includes this, it will be reflected in the article.
**Thank you**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @JeanNetryValere 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by JeanNetryValere** [comment]
@get-itips Hello, thanks for your reply: that was exactly the point, the enum value is missing compared to GUI options. Maybe the request should be created through Uservoice channel instead.

**Comment by get-itips** [comment]
Hello @JeanNetryValere 
Maybe you want to visit this resource https://docs.microsoft.com/en-us/sharepoint/dev/community/community as you may now, Sharepoint-PnP is community driven, and receives contributions and feedback on different channels.
Hope this information helps you.

**Comment by yogkumgit** [comment]
@officedocsbot close
