### ISSUE TITLE
Parameter "DefaultMeetingDuration"

### ISSUE THREAD

**Issue by matteosabbatini** [MicrosoftDocs/office-docs-powershell#2833]
Hello, I noticed that no matter which value we set for the parameter "DefaultMeetingDuration", the default duration of a new meeting depends on the time scale the mailbox has set on its Outlook or OWA calendar.
So, e.g., a mailbox has a time scale of 15 minutes on its Outlook calendar and a value of 30 for "DefaultMeetingDuration", when creating a new calendar appointment/meeting the duration shown initially will be of 15 minutes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ef0bf7-3f9a-773d-7aa4-e167145400b8
* Version Independent ID: d035e696-2d26-a97d-a303-273b85266d1f
* Content: [Set-MailboxCalendarConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-mailboxcalendarconfiguration?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-MailboxCalendarConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-MailboxCalendarConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws306** [comment]
Hi @matteosabbatini , thanks for your feedback.

I see there are more people with this issue:
https://techcommunity.microsoft.com/t5/Outlook/Calendaring-Changing-the-default-meeting-time/td-p/90999

**Comment by yogkumgit** [comment]
@matteosabbatini Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by chrisda** [comment]
@matteosabbatini, it appears the  DefaultMeetingDuration parameter isn't supposed to be available to customers. It obviously is available, but it doesn't work so I updated the parameter description to say "reserved for internal Microsoft use".
