### ISSUE TITLE
Optional Parameters Missing

### ISSUE THREAD

**Issue by dahager** [MicrosoftDocs/office-docs-powershell#2840]
Optional Parameters Missing:
like -AllowRemoveUser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c1fc1a-c9b4-a9bc-47c4-7cd3488fece7
* Version Independent ID: 8102a7bb-e0ef-0f8b-b9b8-67a45ecf076f
* Content: [New-CsTeamsMessagingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmessagingpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsTeamsMessagingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsMessagingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
Hi @dahager , thank you for your feedback.

I am traying to get some information about this parameter.

**Comment by yogkumgit** [comment]
@kenwith please review the PR and merge it if you find it suitable.

**Comment by yogkumgit** [comment]
@officedocsbot close
