### ISSUE TITLE
Required Permissions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#2850]
What permissions (roles) are required to run these cmdlets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03f9b8-7a1f-81e7-e8c2-0286f0cd3ffb
* Version Independent ID: 931924d1-2be2-bc20-41a6-0b86fc65db07
* Content: [Microsoft Teams cmdlet reference](https://docs.microsoft.com/en-us/powershell/teams/intro?view=teams-ps)
* Content Source: [teams/docs-conceptual/intro.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/docs-conceptual/intro.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by tseward** [comment]
@DeanGross similar to the PnP cmdlets, these don't require a specific role. Any user may leverage them to manipulate objects they have rights over.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @DeanGross 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
