### ISSUE TITLE
Credential permissions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#2851]
What type of permissions (role) are required to use the Connect cmdlet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ee082c9-735d-3f8a-7bc4-b2d4f175c784
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
Hi @DeanGross , thank you for your feedback.

You can connect if you are admin or have a teams license.

If you are admin you can manage any Team, if you have a license assigned you can manage Teams you are the owner and create new Teams.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @DeanGross 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
