### ISSUE TITLE
Missing Parameter

### ISSUE THREAD

**Issue by BrianMcNeese** [MicrosoftDocs/office-docs-powershell#2857]
The parameter 'EnableUdcLite' and its description are missing. Can we get it added to the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f39f89-35c5-d98e-d37d-ae6e44c7a8ba
* Version Independent ID: 4b62010f-bb47-5754-1d8e-79f1e2772d6d
* Content: [Set-CsCdrConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cscdrconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsCdrConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsCdrConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @BrianMcNeese Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
