### ISSUE TITLE
Creating duplicate site does not throw error

### ISSUE THREAD

**Issue by wy62** [MicrosoftDocs/office-docs-powershell#2867]
When using New-PnPSite to create a site collection in SharePoint Online, if a site collection with the same URL already exists no error is thrown or message provided to say this. It simply returns the URL that was provided in the URL parameter and it looks like (from the SharePoint Admin Center) no site is created.

I would expect an error to be thrown. Tested this when attempting to create communication sites.

PnP Powershell version: 3.5.1901.0

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @wy62 Thanks for your feedback.
As you may know, this issue repo is for issues specifically for documentation. I created an issue with the description you provided and linked it here. Please refer to that issue for updates.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for reporting the issue in Sharepoint repository and linking here and also sharing this explanation. @wy62 Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
