### ISSUE TITLE
EnableSafeLinksForO365Clients

### ISSUE THREAD

**Issue by CraigUpic** [MicrosoftDocs/office-docs-powershell#2870]
Unable to use Set-AtpPolicyForO365 -EnableSafeLinksForO365Clients &lt;$true | $false&gt; as it does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f989bf3c-3ed0-3dc2-3e9e-4643c85eec9f
* Version Independent ID: c14642cb-4623-8f30-cf51-6b8176a6893a
* Content: [Set-AtpPolicyForO365 (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-atppolicyforo365?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Set-AtpPolicyForO365.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Set-AtpPolicyForO365.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@CraigUpic, did you mean EnableSafeLinksForClients? That parameter is available to me in an E5 tenant, and appears to work for me just fine. I can't find reference to an EnableSafeLinksForO365Clients parameter on any cmdlet in Exchange.

**Comment by CraigUpic** [comment]
No actually mean EnableSafeLinksForO365Clients; from what I can tell maybe the value is always true?

**Comment by chrisda** [comment]
@CraigUpic, are you saying you see the EnableSafeLinksForO365Clients **property** in the output of Get-AtpPolicyForO365, and you're looking for the corresponding EnableSafeLinksForO365Clients **parameter** on Set-AtpPolicyForO365? There doesn't seem to be one. Therefore, the value is always true.

**Comment by dariomws306** [comment]
Hi @CraigUpic , thank you for your feedback.

Do you have any doubt on this?

**Comment by yogkumgit** [comment]
@dariomws306  and @chrisda Thank you very much for the contribution and sharing this explanation. @CraigUpic Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
