### ISSUE TITLE
Small error

### ISSUE THREAD

**Issue by nextor11** [MicrosoftDocs/office-docs-powershell#2880]
In the examples section, example 1 shows a PowerShell command being run against mailbox julia@contoso.com, but the description of that example mentions a different mailbox, lila@contoso.com :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eb6d9af-d969-62f1-b40a-3ac95620b348
* Version Independent ID: 823d09f7-f638-23c1-a000-0231d21d82f8
* Content: [Remove-MailboxUserConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/remove-mailboxuserconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Remove-MailboxUserConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Remove-MailboxUserConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@nextor11, OK. Fixed. Be advised that you also have the power to fix these kind of issues directly in topics. For more information, see  https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md.
