### ISSUE TITLE
The parameter -Whatif is not being honored when used together with -Force for Invoke-CsComputerFailOver

### ISSUE THREAD

**Issue by rito2k** [MicrosoftDocs/office-docs-powershell#2881]
Executing "Invoke-CsComputerFailOver -Force -Whatif" will indeed trigger the Failover, so we have an incompatibility of using both parameters together, and it shall be noted in the documentation. Some sort of description like "-Force overrides the effect of the -Whatif parameter" shall be included.
Thinking the -Whatif use will be just giving information and describe the possible process is not accurate, since the failover will happen, which could lead to an unintentional failover of the server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2de71d2-6792-7bcc-0064-bfade0a3786d
* Version Independent ID: b342568c-752d-5ec4-dd0e-a3599f6887c7
* Content: [Invoke-CsComputerFailOver (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/invoke-cscomputerfailover?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Invoke-CsComputerFailOver.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Invoke-CsComputerFailOver.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by mypil** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @rito2k Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
