### ISSUE TITLE
Get|Set-AtpPolicyForO365 -EnableSafeLinksForWebAccessCompanion <$True|$False?

### ISSUE THREAD

**Issue by CraigUpic** [MicrosoftDocs/office-docs-powershell#2894]
It appears that you cannot set the EnableSafeLinksForWebAccessCompanion property when using Set-AtpPolicyForO365. I have one tenant that has this set to $True somehow and the rest I'm seeing it's $False. Where does this property map to when using the Web UI and can this switch be added so that we can manage it?

**Comment by CraigUpic** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/commit/f8ac0ea19347127f6e60d12c592134b7a54b3743

I see this states it is for internal use but it doesn't explain why one tenant is true and the other is false. Does this switch tie to some UI element but not available via PowerShell?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@CraigUpic Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
