### ISSUE TITLE
Need to list behavior when value is set to None or null

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/office-docs-powershell#2906]
It's not clear in the article what the expected behavior is when the value is not set. (null or none)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbf61d7d-bda0-9656-465d-9b519ed17b5e
* Version Independent ID: 2bb4825d-eedc-c8e2-3f51-0cafd652eadd
* Content: [Set-CsClientPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Set-CsClientPolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsClientPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsClientPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
Hi @TheBluLion , thank you for your feedback.

It is none. None means that if you do not use the parameter it will not modify anything. Therefore, if you edit a policy, the cmdlet will only modify the parameters that you specify.

**Comment by TheBluLion** [comment]
That didn’t answer my question.
The question is, if the attribute is not set(null) what is the original or default behavior experienced by the end user on first start/login of the application?

Eu Nice

**Comment by dariomws306** [comment]
Hi @TheBluLion , could you please give me an example? Thanks!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @TheBluLion , it's a Set- cmdlet, so if the attribute is not set, it won't change it.

The first time you create a policy with New-CsClientPolicy, if you don't set all the attributes some of them will get a default value.

**Comment by TheBluLion** [comment]
I understand the behavior of the cmdlet- however in the event that the csclient policy attribute is not set (blank), what is default behavior of the policy?
What does the user experience if that attribute is blank?

**Comment by dariomws306** [comment]
@TheBluLion , ok I understand your question now. It should be defined on New-CsClientPolicy:
https://docs.microsoft.com/en-us/powershell/module/skype/new-csclientpolicy

But there you can see "Keep in mind that client policies differ from many other policies in that most of the policy settings do not have default values."

Few of them have default value... But most do not... Let me try to get more information on this and I will add it to New-CsClientPolicy.

**Comment by TheBluLion** [comment]
Thanks Dario- the article lists the behavior if the attribute is set to true or false, but not what the behavior if is the value is unset/null. I think that is the gap that the customer is asking to be covered.

**Comment by dariomws306** [comment]
Thank you. I understand this, I am trying to get more information about it.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @TheBluLion Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
