### ISSUE TITLE
Clarity for -Template

### ISSUE THREAD

**Issue by dakneeul1** [MicrosoftDocs/office-docs-powershell#2915]
Is the -Template EDU_Class parameter the only way currently to create 'class notebooks' within teams? It would be so much easier to add these 'modularly' onto channels, I am creating distribution groups then converting them to teams - it seems this might not be possible?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dakneeul1 Thank you very much for your kind feedback. Considering your valuable feedback, we suggest you to log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Here is the link you can go and register your feedback:

https://microsoftteams.uservoice.com/forums/555103-public 

Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
