### ISSUE TITLE
Add-PnPClientSidePage created page change content type automatically against library's content type order

### ISSUE THREAD

**Issue by EbenLLF** [MicrosoftDocs/office-docs-powershell#2921]
**Issue:**
When the Site Pages lirbary has more than one Site Page based content type, the page created with command Add-PnPClientSidePage will change content type automatically to the first Site Page based content type in lirbary content type order. 

**Reproduce steps:**
1. Create two content type based on Site Page content type, and add them to Site Pages lirbary. For example, name them **SitePage1** and **SitePage2**.
2. Set **SitePage1** as default content type and SitePage2 as the seconde one in order.
3. Run Add-PnPClientSidePage -Name "NewPage" to create a new page.
4. Check the content type of this new page in UI, it will display **SitePage1**. 
5. Change the default content type of Site Pages library to **SitePage2**.
6. Back to Site Pages lirbary and open the new page to access it. 
7. Refresh Site Pages library to check content type of the new page, you will find the content type is changed to "SitePage2".

I found the command has no parameter to specify content type for the new page, so the new page will follow the default setting of library. Need option to assign content type when creating a new client side page.

**Comment by EbenLLF** [comment]
Currently, we could use CSOM to update the Content Type TWICE to make it persist, but if someone could provide a complete fix for this issue, it is much appreciated!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @EbenLLF 
Thanks for your feedback. I followed the described steps exactly as you described and could not reproduce it.
The new page created with **Add-PnPClientSidePage** never changed to SitePage2 content type.

Also, actually, Add-PnPClientSidePage has a _-ContentType_ parameter that you can use, I also tested it and it works ok.

Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @EbenLLF 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
