### ISSUE TITLE
Error: Formula can't be empty.

### ISSUE THREAD

**Issue by BipulRaman** [MicrosoftDocs/office-docs-powershell#2923]
`Add-PnPField -List "Test" -Type Calculated -InternalName "MyField" -DisplayName "MyTest" -Formula ="[Title]"`

Below error message displayed for above command. It works when we remove `-List Param`
```
Add-PnPField : Formula can't be empty.
At C:\Users\bipul\Desktop\CreateField\CreateField.ps1:15 char:1
+ Add-PnPField -List "Test" -Type Calculated -InternalName "MyField" -D ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPField], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Fields.AddField
```

**Comment by BipulRaman** [comment]
https://github.com/SharePoint/PnP-PowerShell/issues/1811
ISSUE reported on correct repository on above link. This repository seems to be dedicated for documentation only.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@BipulRaman  Thank you very much for the contribution and creating the reference issue in Share point repository. Hence closing the issue here. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
