### ISSUE TITLE
-BdcObjectType flag refers to "BdcCatalog" as a valid argument, but it should be just "Catalog"

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/office-docs-powershell#2931]
The -BdcObjectType flag says:

    The type must be one of the following valid metadata object types: BdcCatalog, Model, LobSystem, 
    LobSystemInstance, or Entity.

This contradicts the Get-Help for that commandlet, which says:

    SYNTAX
        Get-SPBusinessDataCatalogMetadataObject -BdcObjectType &lt;Catalog | Model |
        LobSystem | LobSystemInstance | Entity&gt; -ServiceContext

It should just be "Catalog" (unless it is different on different versions; I am using SP2013).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e322d6c3-cf85-1b80-8738-bc87eb364c7d
* Version Independent ID: 334f5489-f9dd-d4bd-b92c-bb658e2dcb1b
* Content: [Get-SPBusinessDataCatalogMetadataObject (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spbusinessdatacatalogmetadataobject?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Get-SPBusinessDataCatalogMetadataObject.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Get-SPBusinessDataCatalogMetadataObject.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me please.
