### ISSUE TITLE
Describe the difference or relationships between Get-SPDeletedSite and Remove-SPSite

### ISSUE THREAD

**Issue by nils-a** [MicrosoftDocs/office-docs-powershell#2932]
Please describe what a "deleted site" is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fd81a6d-e48b-a67c-d13c-52cad3f0ff16
* Version Independent ID: 6bb3a543-fa4c-2ccc-8c02-34a8ff5cad74
* Content: [Get-SPDeletedSite (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spdeletedsite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Get-SPDeletedSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Get-SPDeletedSite.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by nils-a** [comment]
Maybe simply add some hint along the lines of
 > Deleted Sites are sites in the process of gradual delete, 
 > see https://blogs.technet.microsoft.com/wbaer/2010/08/02/gradual-site-delete-in-sharepoint-2010/
 > or `Remove-SPSite -GradualDelete`

**Comment by Techwriter40** [comment]
@nils-a thank you for your feedback. I have updated the article to include what a deleted site is. thank you.
