### ISSUE TITLE
Example would be better if it showed how to create $principal

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/office-docs-powershell#2945]
The example includes this line, but it doesn't say what $principal is:

    Grant-SPObjectSecurity $security $principal "Full Control"

Maybe add something like this?
    $principal = New-SPClaimsPrincipal -Identity contoso\myaccount -IdentityType WindowsSamAccountName

Also, when viewing this example in powershell using Get-Help, there are no newlines between the separate commands, so it looks like this:

C:\PS&gt;$security = Get-SPServiceApplicationSecurity $serviceApp
-AdminGrant-SPObjectSecurity $security $principal "Full
Control"Set-SPServiceApplicationSecurity $serviceApp -Admin $security

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 608c8faf-3dae-491a-da16-9b12f81eef79
* Version Independent ID: fdf61ba5-e005-5190-6bb6-9a8de055f627
* Content: [Set-SPServiceApplicationSecurity (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spserviceapplicationsecurity?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPServiceApplicationSecurity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPServiceApplicationSecurity.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr please assign this to me.
