### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by jbenade** [MicrosoftDocs/office-docs-powershell#2950]
The attribute -UserPrincipalName has duplicate description with conflicting info:
#1 - .. available only in on-premises … Applies to: .. Exchange Online
#2 - nothing different except: Applies to:...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382668a2-9a33-6c7f-fd72-a3518b29f72b
* Version Independent ID: e185d010-8800-4ae9-d6c4-6536124e32dd
* Content: [New-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/new-mailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/New-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/New-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jbenade:

**Issue**1: You are correct, the Exchange Online value doesn't belong there (I confirmed UserPrincipalName isn't available in Exchange Online), so I removed it.

**Issue 2**: If you look closely at the YAML tag blocks and the Required values, you'll see that for some parameter sets, UserPrincipalName is required, and for others it's optional (I bolded the values for clarity):

Type: String
Parameter Sets: User, Arbitration, AuditLog, RemoteArchive
Aliases:
Applicable: Exchange Server 2010, Exchange Server 2013, Exchange Server 2016, Exchange Server 2019
**Required: True**
Position: Named
Default value: None
Accept pipeline input: False
Accept wildcard characters: False

Type: String
Parameter Sets: AuxAuditLog, DisabledUser,Discovery, EnableRoomMailboxAccount, Equipment, Linked, LinkedRoomMailbox, Migration, Room, Scheduling, Shared
Aliases:
Applicable: Exchange Server 2010, Exchange Server 2013, Exchange Server 2016, Exchange Server 2019
**Required: False**
Position: Named
Default value: None
Accept pipeline input: False
Accept wildcard characters: False

When that happens, two YAML blocks are required per the cmdlet reference topic schema.

Thanks for the feedback.
