### ISSUE TITLE
Get-MobileDevice Example Error

### ISSUE THREAD

**Issue by haydeniv** [MicrosoftDocs/office-docs-powershell#2952]
https://docs.microsoft.com/en-us/powershell/module/exchange/devices/get-mobiledevice?view=exchange-ps

Under Example 2:
`Get-MobileDevice -ResultSize -unlimited | Format-Table -Auto DeviceModel,Identity`
should be
`Get-MobileDevice -ResultSize unlimited | Format-Table -Auto DeviceModel,Identity`

The dash before "unlimited" should be omitted.  Unlimited is the value of the "ResultSize" parameter, not an addition parameter of Get-MobileDevice.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and updating the documentation with PR. @haydeniv  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
