### ISSUE TITLE
URL trace "Custom date range"

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/office-docs-powershell#2953]
Hello,

When running a URL trace with start date more than 7 days ago and not changing the end date, an error will be thrown.
This article should mention that the date-range cannot be more than 7 days.

Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5522e1-7041-205a-7a97-1622118d9d58
* Version Independent ID: 0e5702db-abe5-9172-cab6-676952313b66
* Content: [Get-UrlTrace (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/get-urltrace?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Get-UrlTrace.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Get-UrlTrace.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@chrisda can you help me to confirm this?
Thank you

**Comment by get-itips** [comment]
Hi @JeroenDronkers thanks for your feedback, we will improve the article based on your suggestion.
**Thank you**

**Comment by yogkumgit** [comment]
@chrisda please merge this PR, if you find it suitable.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @JeroenDronkers Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by aldoug** [comment]
This document really needs some description around the Output values. I can advise on some of these (as they are sometimes confusing). Please reach out to me if necessary.

**Comment by get-itips** [comment]
Hello @aldoug I see that you opened another issue https://github.com/MicrosoftDocs/office-docs-powershell/issues/3338 we will handle your inquiry in that one. This one will stay closed. thanks.
