### ISSUE TITLE
add-pnpfile -folder doesn't accept full URL

### ISSUE THREAD

**Issue by ianbruckner** [MicrosoftDocs/office-docs-powershell#2955]
The add-pnpfile commandlet will not accept the full URL for the folder parameter as find-pnpfile does.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ianbruckner thanks for your feedback. That is true, and the examples show that the relative url of the folder is used. So I do not identify the need to change the documentation.
As you may know, this issue resource is to report specifically issues in documentation, if you want to change this behavior let me suggest a feedback or user voice resource, as you may know also, Sharepoint PnP is community driven, I encourage you look here for that kind of resources https://docs.microsoft.com/en-us/sharepoint/dev/community/community

Thank You!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ianbruckner 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
