### ISSUE TITLE
add-pnpfile returns new date stamp, but doesn't upload file

### ISSUE THREAD

**Issue by ianbruckner** [MicrosoftDocs/office-docs-powershell#2956]
When add-pnpfile is used to add a file that previously existed in a folder (file was previously renamed or deleted), the command returns a file object complete with new date stamp, but no file is uploaded.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ianbruckner thanks for your feedback.
I tested in my lab and did not get the same results, the file was uploaded correctly even if it was present and either deleted or renamed before. Please be sure of running the last version of the module.
I see that no changes in documentation needs to be done.
We appreciate your feedback.
Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ianbruckner 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
