### ISSUE TITLE
Example 1 does not work (ex2016)

### ISSUE THREAD

**Issue by mailgut** [MicrosoftDocs/office-docs-powershell#2996]
Example 1 does not work: 
Update-PublicFolderMailbox -Identity PF_marketing -SuppressStatus
It sayes: supressstatus is invalid if not used with 'InvokeSynchronizer'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370b6a41-7766-a863-aad6-93b560c62df5
* Version Independent ID: 2cda209e-2e96-ded8-4d80-ce07053be4ab
* Content: [Update-PublicFolderMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/sharing-and-collaboration/update-publicfoldermailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/sharing-and-collaboration/Update-PublicFolderMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/sharing-and-collaboration/Update-PublicFolderMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mailgut, Example 2 doesn't work, either. They both work if you remove the SuppressStatus switch, which I did.

Thanks for the feedback
