### ISSUE TITLE
Parameter missing description

### ISSUE THREAD

**Issue by grtaylo** [MicrosoftDocs/office-docs-powershell#3001]
**-CloudRecordingServiceSupport**
Current description:
{{Fill CloudRecordingServiceSupport Description}}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17c02d1-21b6-0a17-666f-fedf38e3b42a
* Version Independent ID: 57e7e1ae-a8c1-8355-92db-b77955b68174
* Content: [New-CsConferencingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csconferencingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsConferencingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsConferencingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith Please merge the PR #3810

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @grtaylo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
