### ISSUE TITLE
Search-Mailbox KQL and UTF-8 encoding

### ISSUE THREAD

**Issue by rcarsey1** [MicrosoftDocs/office-docs-powershell#3002]
We've seen an increase in the amount of incoming junkmail/phishing where the From: and Subject: are UTF-8 MIME encoded.  What used to be a simple Get-Mailbox | Search-Mailbox -Delete is now complicated.  

For instance, a phishing email with the headers:  From: =?UTF-8?B?UGF0cmljayBMZWFoeQ==?= <patrick.leahy@my.com>    and  Subject: =?UTF-8?B?SGVsbG8=?=    seem to be un-searchable/findable with the existing Search-Mailbox query syntax.  If it indeed is possible, then I simply ask for an example to be provided in the Search-Mailbox or KQL documentation.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @rcarsey1 thanks for your feedback.
I think Support services will help you on this one, @yogkumgit can you kindly redirect him ?
Thank you

**Comment by yogkumgit** [comment]
@rcarsey1  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
