### ISSUE TITLE
Missing parameter information

### ISSUE THREAD

**Issue by wwejason** [MicrosoftDocs/office-docs-powershell#3004]
The parameter BookingType is missing all details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a9c45b-34dd-c1c8-89f0-84f3d968eac4
* Version Independent ID: ec9c910c-25f2-f36a-8f75-ce052f0e8be6
* Content: [Set-CalendarProcessing (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/Set-CalendarProcessing?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@wwejason, OK. Added. Thanks for the feedback.
