### ISSUE TITLE
"User" Parameter section is duplicated

### ISSUE THREAD

**Issue by jeffreymcclain** [MicrosoftDocs/office-docs-powershell#3008]
The parameter titled "user" has two identical sections.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb509e0a-2371-d5b8-6462-c0f29e6c8152
* Version Independent ID: b8fdd337-395d-0c42-4ff1-9a0969a9d578
* Content: [Add-MailboxPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/add-mailboxpermission?view=exchange-ps#examples)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Add-MailboxPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Add-MailboxPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jeffreymcclain, this is a topic rendering issue with docs.microsoft.com. You'll notice that the underlying GitHub source topic doesn't have duplicate User parameter sections. This definitely has something to do with the multiple YAML blocks in the parameter (required when a parameter is required in some parameter sets, but optional in others). I'm actively seeking a solution.

Thanks for the feedback
