### ISSUE TITLE
Cannot Enable a Disabled Custom Feature

### ISSUE THREAD

**Issue by qazqwertish** [MicrosoftDocs/office-docs-powershell#3010]
For the OOB features there is no problem, but for the custom ones (for example, the feature for the application customizers in SPFx) once the feature is disabled it does not appear anymore and cannot be enabled.

Even trying with Microsoft Flow and making a REST call (_api/web/features/add) it throws an error saying "Feature with Id 'GUID' is not installed in this farm, and cannot be added to this scope.", but using the SharePoint Interface we can see it in the list of features and we can enable it manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f50b0868-05d6-c9f8-2b53-077c5bf2514f
* Version Independent ID: 9d5eac86-0b31-5bae-3a55-ee67d4d54440
* Content: [Enable-PnPFeature (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/enable-pnpfeature?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Enable-PnPFeature.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Enable-PnPFeature.md)
* GitHub Login: @vesajuvonen
* Microsoft Alias: **vesaj**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot unassign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @qazqwertish thanks for your feedback.
As you may know, this issue repo is for issues specifically for documentation. I created an issue with the description you provided and linked it here. Please refer to that issue for updates.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for reporting the issue in Sharepoint repository and linking here and also sharing this explanation. @qazqwertish  Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
