### ISSUE TITLE
MessageBind Deprecation in favor of MailItemsAccessed

### ISSUE THREAD

**Issue by blalonde** [MicrosoftDocs/office-docs-powershell#3012]
Command: Set-Mailbox

Looks like MessageBind isn't supported anymore and is replaced by MailItemsAccessed :
https://office365itpros.com/2019/01/06/exchange-online-message-access-audit/ 

Also, it looks like setting MailItemsAccessed is not completely available now... Do have any updates on this ? See my post here (blalonde12)
https://social.technet.microsoft.com/Forums/en-US/ae02b692-b34e-474b-b43a-b2a72ad1cff5/auditlog-messagebind-deprecated?forum=Exch2016PS

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @blalonde thanks for your feedback, we appreciate it.

Article for Set-Mailbox says that MessageBind is deprecated (it is still there so does not mean is not supported anymore)

MailItemsAccessed is still being rolled out for some tenants. If you need to know when will be available  I suggest contact Support, @yogkumgit will kindly redirect you.

Thank you.

**Comment by yogkumgit** [comment]
@blalonde Thank you very much for posting this issue. Considering the nature of the issue, as advised by @get-itips  that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
