### ISSUE TITLE
Access denied when provisioning new site based on template

### ISSUE THREAD

**Issue by edcuzz** [MicrosoftDocs/office-docs-powershell#3015]
I followed the tutorial to create a console application to create a template based on one spo site and apply it to a target site. I am able to successfully create the template but when it get's to the provisioning step for the new site I get an access denied error. My user is an site admin. Anyone know what the permissions need to be for the Apply-PnPProvisiongTemplate command.

I am running the 3.6.1902.0 version of OfficeDevPnP.Core library.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
I think this is likely due to including resources from the Style Library; if this is a Modern Team site it won't let you add this. What needs to be done is exclude the Style Library, however this isn't something you can do OOTB. I'm also looking to find a solution for this and will be looking to create one to provide to the public.

**Comment by tseward** [comment]
@edcuzz do you have any files in the site you're attempting to make a template from within the Site Assets library (sorry, not style library)?

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and digging deep into it.  @edcuzz  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
