### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by TashunkoWitko** [MicrosoftDocs/office-docs-powershell#3017]
The example should be:
Register-SPAppPrincipal -site $site.RootWeb […]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf861e60-d88b-0a5d-2321-efdb0e281d8f
* Version Independent ID: 901da99f-c80d-743f-e0ff-f9c53bd2922a
* Content: [Register-SPAppPrincipal (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/register-spappprincipal?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Register-SPAppPrincipal.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Register-SPAppPrincipal.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.
