### ISSUE TITLE
Additional Properties or update documentation 

### ISSUE THREAD

**Issue by kasperbolarsen** [MicrosoftDocs/office-docs-powershell#3018]
It seems like alot of the properties on the Groups are not available. Perhaps it would be a good idea to add the workaround to the documentation , like this:

$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $targetcred -Authentication Basic -AllowRedirection
Import-PSSession $Session -AllowClobber
Set-UnifiedGroup -Identity $destination -UnifiedGroupWelcomeMessageEnabled:$false

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @kasperbolarsen , thank you for you feedback.

Could you let me now the article you are talking about? Maybe this one:
https://docs.microsoft.com/powershell/module/exchange/users-and-groups/set-unifiedgroup

Thanks!

**Comment by kasperbolarsen** [comment]
@dariomws306
That would be https://docs.microsoft.com/en-us/graph/api/reportroot-getsharepointsiteusagedetail?view=graph-rest-beta

**Comment by dariomws306** [comment]
Hi @kasperbolarsen , did you delete your last comment?

**Comment by kasperbolarsen** [comment]
@dariomws306 , sorry the comment I deleted was related to another issue. The article I was refering to is https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpunifiedgroup?view=sharepoint-ps as I think it would be a good idea to show how to handle the cases where the PnP command doesn't cover that property

**Comment by dariomws306** [comment]
Thank you @kasperbolarsen.

Ok I understand your idea however I think this article is very specific to Set-PnPUnifiedGroup and its capabilities. The standard cmdlet to modify Unified Groups is Set-UnifiedGroup and you should follow its help to modify all attributes.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @kasperbolarsen Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
