### ISSUE TITLE
Please add information to connect to O365 GCCH

### ISSUE THREAD

**Issue by scossio** [MicrosoftDocs/office-docs-powershell#3021]
You only have to change the endpoint, but since info is provided for Germany and China, figured if it's worth adding it for US GCCH:

$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.compliance.protection.office365.us/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection

Tested and it works. 
Sergio

**Comment by chrisda** [comment]
@scossio, OK. Done.
