### ISSUE TITLE
Cannot switch off folder creation in doc lib

### ISSUE THREAD

**Issue by OpenHabitat** [MicrosoftDocs/office-docs-powershell#3028]
Using this command does nothing:
Set-PnPList -Identity 'Policy Documents' -EnableFolderCreation $true

I even tried this - but still does nothing:
Set-PnPList -Identity 'Policy Documents' -EnableFolderCreation $false

Please help with this. I have to do a bulk update on about 50 document libraries, and this PNP command does not work as expected.

Many thanks,
Tony.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbab5a2d-0c37-bb2c-f2d9-989bc2a59d05
* Version Independent ID: 2f512ab6-be40-1fb2-9f8a-d1bc692537ce
* Content: [Set-PnPList (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplist?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPList.md)
* GitHub Login: @vesajuvonen
* Microsoft Alias: **vesaj**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @OpenHabitat **thanks for your feedback.**
I tested in my lab the exact steps you have taken and could not reproduce what happened to you. The switch EnableFolderCreation worked as expected. So appears that documentation changes do not need to be done.
Please be sure to run the last version of the module.
**Thank you**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @OpenHabitat 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
