### ISSUE TITLE
Add-PnPTaxonomyField missing options for Navigation and properties

### ISSUE THREAD

**Issue by CrackerboxOnline** [MicrosoftDocs/office-docs-powershell#3032]
Term sets are more frequently being used to store navigation components.  e.g the SP Starter Kits collabFooter but the Add-PnPTaxonomyField does not include options to set the navigation URL or local property settings (used to define a parameter and value to display an icon against each entry).

Extending the Add-PnPTaxonomyField cmdlet to include navigation URL settings and local property key|value pairs would make reading a backed up link hierarchy through PowerShell to consistently deploy navigation hierarchies between dev|test|prod environments.  In this DevOps world its regularly being a requirement that this be scriptable to ensure consistency.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @CrackerboxOnline  as you may know, this issue resource is to report specifically issues in documentation, and I see, based on the description that you give, that might be more suitable for a feedback or user voice resource, as you may know also, Sharepoint PnP is community driven, I encourage you look here for that kind of resources https://docs.microsoft.com/en-us/sharepoint/dev/community/community

Hope this information helps you.

**Comment by VesaJuvonen** [comment]
Closing this as it's a feature request and not about issues in the documentation. Request itself does make sense.
