### ISSUE TITLE
Coda for Exchange Online

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/office-docs-powershell#3033]
I think this document needs a coda near the top which clarifies that new e-mail address policies are not supported for user mailboxes in Exchange Online.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6557027-9f33-615e-42c2-c77fd5b3fe2c
* Version Independent ID: b2b2b514-120e-1181-c1d2-42c07f45f5cd
* Content: [New-EmailAddressPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/email-addresses-and-address-books/new-emailaddresspolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/email-addresses-and-address-books/New-EmailAddressPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/email-addresses-and-address-books/New-EmailAddressPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@FC-EricWeller, I updated the SYNOPSIS (Introduction) of Get/New/Remove/Set-EmailAddressPolicy to say:

 In Exchange Online, email address policies are only available for Office 365 groups.

Thanks for the feedback.
