### ISSUE TITLE
get-sposite retuning an error

### ISSUE THREAD

**Issue by davecober** [MicrosoftDocs/office-docs-powershell#3060]
Seems to have started in the last week. Same thing happens if I narrow it to a single site ( -identity [domain].sharepoint.com/sites/[example]) but has a different number for "position".

```
get-sposite : The type of data at position 1669 is different than the one expected.
At line:1 char:1
+ get-sposite
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SPOSite], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.Online.SharePoint.PowerShell.GetSite
```

**Comment by j0rt3g4** [comment]
Same here:
```powershell
get-SPOSite : The type of data at position 1640 is different than the one expected.
At line:1 char:1
+ get-SPOSite https://farubonon.sharepoint.com/sites/visio | select *
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SPOSite], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.Online.SharePoint.PowerShell.GetSite
```

**Comment by davecober** [comment]
Looks like a larger issue.

SP175669 - PowerShell commands issue
Status:Service degradation
User impact:Admins are unable to run Remote PowerShell commands.
Latest message:Title: PowerShell commands issue

User Impact: Admins are unable to run Remote PowerShell commands.

Current status: After an investigation into recent changes, we’ve identified a configuration issue that was introduced in a recent update to the SharePoint Online service that is preventing admins from running Remote PowerShell commands. We’re reverting the update, which is expected to resolve impact.

Scope of impact: Your organization is affected by this event, and may impact any administrator attempting to run Remote PowerShell commands.

Preliminary root cause: A configuration issue introduced in a recent SharePoint Online update is preventing admins from running Remote PowerShell commands. 

Next update by: Wednesday, March 13, 2019, at 8:00 PM UTC

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @davecober 
First of all, thanks for your feedback.
As you may know, this issue resource is specifically to report about issues currently present in documentation. Based on the description you provided, that is more suitable for Support Resources related to Office 365, this might be a good start https://support.office.com/en-us/sharepoint
Besides that, I tried the cmdlet and currently is working without any issues.
No further documentation changes need to be made.
Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @davecober 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
