### ISSUE TITLE
Module: exchange link broken

### ISSUE THREAD

**Issue by AlBrough** [MicrosoftDocs/office-docs-powershell#3061]
the Module: exchange link at the top of the page lands on a 404 not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32336a14-3346-1850-13f1-665df4927cc6
* Version Independent ID: b941743d-319c-41b9-9c9b-6e707756261d
* Content: [Get-UserPrincipalNamesSuffix (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/active-directory/get-userprincipalnamessuffix?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/active-directory/Get-UserPrincipalNamesSuffix.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/active-directory/Get-UserPrincipalNamesSuffix.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@AlBrough, this is a known issue that we've almost fixed.

**Comment by dariomws** [comment]
The Exchange module link issue was fixed this week. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
