### ISSUE TITLE
Examples Missing From Description Section

### ISSUE THREAD

**Issue by jdotto02** [MicrosoftDocs/office-docs-powershell#3066]
The Description section has two sentences beginning with "This example lists the probes running...", but neither of the two examples are listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4447fcc6-9add-90b4-227f-357ebaf3ae94
* Version Independent ID: 2b94ca7b-6651-de39-0f77-fcd6b37a2da5
* Content: [Test-OutlookConnectivity (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/Test-OutlookConnectivity?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Test-OutlookConnectivity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Test-OutlookConnectivity.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@jdotto02, that was an artifact of the TechNet to docs.microsoft.com migration. I added the missing examples. Thanks for the feedback.
