### ISSUE TITLE
How do you run the resulting PowerShell windows as an administrator?

### ISSUE THREAD

**Issue by bingoglossy** [MicrosoftDocs/office-docs-powershell#3067]
How do you run the resulting PowerShell windows as an administrator?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by bingoglossy** [comment]
Daniel knew the answer:

Start-Process Powershell -Verb runAs

http://www.danielclasson.com/powershell-how-to-elevate-to-administrator-permissions-within-a-powershell-window/

**Comment by ocean2706** [comment]
The resulting powershell is executed on o365 cloud environment. There is no need to run with conventional RunAs administrator as long as the user you use for authentication have administrative rights on o365 tenant.

**Comment by dariomws306** [comment]
Hi @bingoglossy, thank you for your collaboration.

Do you need more help?

**Comment by yogkumgit** [comment]
@bingoglossy Hope the comments have helped you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
