### ISSUE TITLE
The DefaultAccessLevel parameter description is misleading

### ISSUE THREAD

**Issue by austinmccollum** [MicrosoftDocs/office-docs-powershell#3076]
The DefaultAccessLevel parameter description is misleading.  The current description says it "specifies access level for new devices."  In reality, changing from the default ALLOW to QUARANTINE or BLOCK will effect existing partnerships as well as new devices.

I recommend changing the description for the DefaultAccessLevel to this:
"The DefaultAccessLevel parameter specifies the access level for new and existing device partnerships. Valid values are Allow,Block or Quarantine. The default value is Allow.  Changing from the default to Quarantine or Block will immediately effect all existing devices connected unless device access rules or individual allow/block list entries exist"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 750a108a-2566-c322-30d2-4ed9743375db
* Version Independent ID: eec9bb15-d3c2-ec66-5a1d-6669b20fe297
* Content: [Set-ActiveSyncOrganizationSettings (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/set-activesyncorganizationsettings?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/devices/Set-ActiveSyncOrganizationSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/Set-ActiveSyncOrganizationSettings.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@austinmccollum, OK. Done. Thanks for the feedback. Remember, you can make updates like this to topics yourself. See https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md.
