### ISSUE TITLE
ISE make the exchange MFA thing work with the ise dear god ISE & mfa exchange please

### ISSUE THREAD

**Issue by phillkOCCM** [MicrosoftDocs/office-docs-powershell#3077]
ISE make documentation, or adjust this so I can run connect-exopssession from my ISE . don't neglect your tools, the ISE please make this work with the ISE.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @phillkOCCM thanks for your feedback, actually, this system is for creating issues with current articles on docs, I think your suggestion is more suitable for Powershell UserVoice https://windowsserver.uservoice.com/forums/301869-powershell can you kindly visit there?

Thank you

**Comment by yogkumgit** [comment]
@phillkOCCM  Thank you very much for your kind feedback. As suggested please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
