### ISSUE TITLE
Incorrect example for ExchangeAutodiscoverAllowedDomains

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#3078]
If adding the Allowed domains as requested I receive an error:

-ExchangeAutodiscoverAllowedDomains "*.contoso.com","*.fabrikam.com"

**Set-CsOAuthConfiguration : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'ExchangeAutodiscoverAllowedDomains'. Specified method is not
supported.**

Question 1: 
Should it be:
  -ExchangeAutodiscoverAllowedDomains "*.contoso.com;*.fabrikam.com"
or
  -ExchangeAutodiscoverAllowedDomains {"*.contoso.com","*.fabrikam.com"}

Question 2:
What is the default behaviour if the value is $null?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b940ec3-fba8-8b31-48b2-76092639d4c5
* Version Independent ID: e33808fa-72f8-5b61-2a30-7da4ac2dffc4
* Content: [Set-CsOAuthConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csoauthconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOAuthConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOAuthConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @Petri-X 
Thanks for your feedback, I tested it and then created a PR to improve the article based on your suggestion.
**Thank you!**
About default behaviour when this value is not set: _it will not allow any domain to be redirected to_.

**Comment by yogkumgit** [comment]
@kenwith please merge this PR if you find it suitable.

**Comment by Petri-X** [comment]
Hi again @get-itips 
Unfortunately you need to explain a bit this:
"_About default behaviour when this value is not set: it will not allow any domain to be redirected to._"
Have this something to do with cases when Autodiscover points to on-premises as primary, but the mailbox locates in Exchange Online (*@*.onmicrosoft.com). Is that the redirection which is blocked by default? Or how do you expecting to see issues when this is not enabled?

When testing e.g. with Test-CsExStorageConnectivity, this setting seems to be not affected by this.

**Comment by get-itips** [comment]
Hello @Petri-X 

Yes, that could be a valid case, when Autodiscover is pointing onprem but the mailbox is online and the redirection for example needs to take you to an .outlook.com fqdn.

As this system is intended for issues related specifically to documentation, I kindly suggest you continue on  Support resources, @yogkumgit will kindly redirect you.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Petri-X Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

Also as advised here contact to support for further clarifications.
 https://docs.microsoft.com/office365/admin/contact-support-for-business-products

**Comment by yogkumgit** [comment]
@officedocsbot close
