### ISSUE TITLE
type parameter is not reserved and can be used, please update the doc

### ISSUE THREAD

**Issue by Smartboss88** [MicrosoftDocs/office-docs-powershell#3081]
type parameter is not reserved and can be used, please update the doc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94092e4-9e46-ab25-23a5-d3c35229896e
* Version Independent ID: b52fc145-0aea-d238-6ca3-9a42952c832d
* Content: [New-AuthServer (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/new-authserver?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/organization/New-AuthServer.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/New-AuthServer.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Smartboss88, it's definitely available, but can you provide an example that actually works?

Most of the normal cmdlet usage is like this (no Type parameter):

```
New-AuthServer -Name <Name> -AuthMetadataUrl https://accounts.accesscontrol.windows.net/<o365domain>/metadata/json/1
```

This command:

```
C:\>New-AuthServer -Name Test -Type <ADFS or MicrosoftACS or LinkedIn or Facebook or AzureAD>
```

Gives the error `Parameter set cannot be resolved using the specified named parameters.`

So, even though it's available, I'm not so sure it works.

**Comment by Smartboss88** [comment]
Sure. This is used for hybrid modern authentication for Exchange.

New-AuthServer -Name "evoSTS" -AuthMetadataUrl https://login.windows.net/ssmhealth.com/FederationMetadata/2007-06/FederationMetadata.xml -Type AzureAD

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chrisda** [comment]
@Smartboss88, I updated the topic. Closing.
