### ISSUE TITLE
Cmdlet is not available on Exchange Online?

### ISSUE THREAD

**Issue by DigitalFrog007** [MicrosoftDocs/office-docs-powershell#3082]
Just tried to use this cmdlet, and get the error that it is not a recognized cmdlet.  I am running an EXOPSession and have admin access.  Did this cmdlet get deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3665db68-7dd8-2e93-1797-505eb77a22ce
* Version Independent ID: 9cf5b8f2-a6aa-e79b-70e7-cfe5c1aee69c
* Content: [Get-RecoverableItems (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/Get-RecoverableItems?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-RecoverableItems.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-RecoverableItems.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by DigitalFrog007** [comment]
nvm - it was the role "Mailbox Input Output" that I needed, that and giving it about 15 min for the role permission to propagate and take effect.

**Comment by chrisda** [comment]
@DigitalFrog007, OK. Closing.
