### ISSUE TITLE
Document needs more detail.

### ISSUE THREAD

**Issue by ajhstn** [MicrosoftDocs/office-docs-powershell#3088]
From the example above, this command Set-CASMailboxPlan -Identity ExchangeOnlineEnterprise -ActiveSyncEnabled $false -PopEnabled $false, disabled ActiveSync and POP..

Can you please clarify when in the authentication flow does the block occur, eg before or after the credentials have been passed to azure ad, pre auth, post auth, these are important details, and secondly what do you mean by block?  Are we talking 404 or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07f6d529-3fc4-9ab8-d1e7-53dee583e32c
* Version Independent ID: e7fa50a4-2123-fa59-fd73-496bdb7b50c9
* Content: [Set-CASMailboxPlan (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-casmailboxplan?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/set-CASMailboxPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/set-CASMailboxPlan.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ajhstn, to block pre-authentication, you need to use authentication policies as described in https://docs.microsoft.com/Exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.

Set-CASMailbox and Set-CASMailboxPlan should work in the same way. When you try to setup the connection in the POP or IMAP client, it will act like the mailbox doesn't exist. If the client app is already configured, you block access, and they try to connect again, they'll likely get an error.
