### ISSUE TITLE
Get-MessageTrace pipe to Get-MessageTraceDetail

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#3089]
```Get-MessageTrace -StartDate "09/11/2017 00:00:00" -EndDate "09/15/2017 00:00:00" -PageSize 10 -Page 1 | Get-MessageTraceDetail | Select-Object Date, MessageTraceID, Event, Data, Detail | Out-GridView```

It seems the last event of the first MessageTraceID keeps repating itself and was added next to last event of the next MessageTraceID. And its data keep growing. Please see below image for the clear representation of the issue. 
![image](https://user-images.githubusercontent.com/5260172/54534080-ac8a9580-499c-11e9-8c64-31abe4971975.png)

Below image is the correct MessageDetail of MessageTraceId 2b87f940-0eee-4c39-71a9-08d4f9757430 
![image](https://user-images.githubusercontent.com/5260172/54534104-bf9d6580-499c-11e9-83ec-a6f0b8cc52a4.png)

And below image is the correct MessageDetail of MessageTraceId f602c9c7-2a5b-4a5a-1256-08d4f8e9ba58 
![image](https://user-images.githubusercontent.com/5260172/54534139-cd52eb00-499c-11e9-900b-dc621bc4e0c5.png)

Can you please check why it is happening?

Thanks in advance.

```
> $PSVersionTable

Name Value 
---- ----- 
PSVersion 5.1.14393.1198 
PSEdition Desktop 
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...} 
BuildVersion 10.0.14393.1198 
CLRVersion 4.0.30319.42000 
WSManStackVersion 3.0 
PSRemotingProtocolVersion 2.3 
SerializationVersion 1.1.0.1 
```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @YuriySamorodov how are you?

This is to inform  of issues in docs articles, is there any article that you see presents issues and need to be improved? if not, @yogkumgit will kindly redirect you to some   support resources that will help you with your issue.

Thank you

**Comment by yogkumgit** [comment]
@YuriySamorodov Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
