### ISSUE TITLE
SPONLINE: Unable to delete folders that have sub-folders and/or files

### ISSUE THREAD

**Issue by ravinleague** [MicrosoftDocs/office-docs-powershell#3096]
In SharePoint Online, Remove-PnPFolder does not delete folders that have sub folders or files inside it. Is there a workaround ?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ravinleague 
First of all, thanks for your feedback.
As you may know Remove-PnPFolder is part of sharepoint-pnp module, a community driven effort.
I tested in a lab, and could succesfully use Remove-PnPFolder to delete a folder and it's child items, files and folders, so could not reproduce what you told. I see that no further documentation changes need to be made.
**Thank you**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ravinleague 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
