### ISSUE TITLE
Defaulfencrypten

### ISSUE THREAD

**Issue by ivanja81** [MicrosoftDocs/office-docs-powershell#3100]
I believe the default configuration is not require encryption but support encryption. I check this in my lab for both 2015 and 2019,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d1b5f4d-f6bc-df5f-eb7f-dbfde16a8c12
* Version Independent ID: 32115627-278f-a31a-6529-8428138e7e43
* Content: [Set-CsMediaConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csmediaconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsMediaConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsMediaConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ivanja81 thanks for your feedback, we really appreciate it.
I tested the cmdlet in two labs and I have got RequireEncryption.

**Comment by ivanja81** [comment]
As default?

**Comment by ivanja81** [comment]
Ping me directly please on my MSFT account.

**Comment by get-itips** [comment]
Hello @ivanja81 thanks for your feedback.
As we confirmed that RequireEncryption is still the default, we can safely close this issue @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ivanja81 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
