### ISSUE TITLE
No Examples

### ISSUE THREAD

**Issue by StacyRacks** [MicrosoftDocs/office-docs-powershell#3102]
This page and all the access services powershell pages are junk.  You can get the same info in powershell, which also does not have any examples.  This is really garbage, add some examples.  Is it possible to restore the access services app from a previous farm if you do not have that previous farm config db

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7d2b7a0-f1d6-03e9-5ab2-f729b833c2ff
* Version Independent ID: 37fed31a-ab1e-8884-6b66-79bc69f09377
* Content: [Set-SPAccessServicesDatabaseServer (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spaccessservicesdatabaseserver?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPAccessServicesDatabaseServer.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPAccessServicesDatabaseServer.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr go ahead and assign to me. As noted in https://github.com/MicrosoftDocs/office-docs-powershell/issues/588, these should have the attention of the PG, but I'll take another pass at trying to fix this article.

**Comment by yogkumgit** [comment]
@officedocsbot assign @tseward

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @StacyRacks Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
