### ISSUE TITLE
Missing 4 parameters

### ISSUE THREAD

**Issue by ivanja81** [MicrosoftDocs/office-docs-powershell#3103]
PS C:\Users\sfbadmin&gt; Get-CsMediaConfiguration

Identity                           : Global
EnableQoS                          : False
EncryptionLevel                    : SupportEncryption
EnableSiren                        : False
MaxVideoRateAllowed                : Hd720p15M
EnableH264StdCodec                 : False
EnableInCallQoS                    : True
InCallQoSIntervalSeconds           : 10
EnableRtpRtcpMultiplexing          : True
EnableVideoBasedSharing            : True
WaitIceCompletedToAddDialOutUser   : False
EnableDtls                         : False
EnableRtx                          : False
EnableSilkForAudioVideoConferences : False
EnableAVBundling                   : False
EnableServerFecForVideoInterop     : False
EnableReceiveAgc                   : False
EnableDelayStartAudioReceiveStream : False

Can you add these also?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d1b5f4d-f6bc-df5f-eb7f-dbfde16a8c12
* Version Independent ID: 32115627-278f-a31a-6529-8428138e7e43
* Content: [Set-CsMediaConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csmediaconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsMediaConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsMediaConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by ivanja81** [comment]
Hi,
-Enable264 is not visible anymore in the command. I believe it's better to remove it.

**Comment by get-itips** [comment]
Hello @ivanja81 I created a PR to add a description for some parameters, expect to complete for other parameters by product team soon.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ivanja81 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
