### ISSUE TITLE
Exchange Online with MFA from Powershell Core?

### ISSUE THREAD

**Issue by HeyMrJ** [MicrosoftDocs/office-docs-powershell#3104]
Hi,

Are there any plans to change the way the Exchange Online MFA module tries to present the login window so that it works with Powershell Core?
Right now it throws the error _New-ExoPSSession : Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified._
It's possible to connect to most of the other services with Powershell Core when MFA is enabled, but not Exchange Online (and probably Security and Compliance Portal)

It seems like it has something to do with the way the module tries to present the login window, and I suppose that it's a limitation in DotNet Core. 
But there must be other ways to display the login page since it works for both MSOnline and SPO?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@HeyMrJ  Thank you very much for your kind feedback. Considering your valuable feedback, we request you to log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Please follow the link given here. Thanks again for taking out some time and sharing your feedback. 

 https://windowsserver.uservoice.com/forums/301869-powershel

**Comment by yogkumgit** [comment]
@officedocsbot close
