### ISSUE TITLE
Results are only bound if Get-ComplianceSearchAction is given the Name directly

### ISSUE THREAD

**Issue by jdgregson** [MicrosoftDocs/office-docs-powershell#3106]
I found that, even though you can call `Get-ComplianceSearchAction` with no arguments and get back a list of ComplianceSearchActions, you can't reliably select one using `Where-Object` as the `Results` field will not be bound to any data. For example, if I reference the ComplianceSearchAction like this:

    PS C:\Users\username> $result = Get-ComplianceSearchAction "test54321_Preview"
    PS C:\Users\username> $result.Results
    {Location: j**********@********.com; Sender: J**** ******n; Subject: test 54321; Type: Email; Size: 33477; Received Time: 3/20/2019 10:05:05 PM; Data Link: data/All/...eml}

the `Results` field shows the results as expected. However, if I use `Where-Object` like this:

    PS C:\Users\username> $result2 = Get-ComplianceSearchAction | Where-Object {$_.Name -eq "test54321_Preview"}
    PS C:\Users\username> $result2.Results
    {}

the `Results` fields is empty. The only difference I have found between these two methods is that `NumBindings` is 0 when `Where-Object` is used:

    PS C:\Users\username> $result,$result2 | Select Name,Identity,NumBindings

    Name              Identity                             NumBindings
    ----              --------                             -----------
    test54321_Preview 4c9c96a9-2d5f-43d7-0205-08d6ad80dd6d           1
    test54321_Preview 4c9c96a9-2d5f-43d7-0205-08d6ad80dd6d           0

I feel that this should be noted in the documentation somewhere, since it took a significant amount of my time to find.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d76d344-a9c0-056d-583b-c1b6da96d97a
* Version Independent ID: eafc1a71-5d29-734a-da6b-bb40fa392c80
* Content: [Get-ComplianceSearchAction (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/get-compliancesearchaction?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/Get-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/Get-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @jdgregson, thank you for your feedback.

I have tested it and I don't have the same behaviour:
![image](https://user-images.githubusercontent.com/33589238/56002745-e5ffa980-5c99-11e9-9e80-0e335b10d52b.png)

**Comment by jdgregson** [comment]
@dariomws306 Thanks for taking a look. That's interesting. I was able to reproduce both your results and my results. Perhaps this is a bug affecting only the `preview` action? If you have a chance, it would be interesting to see if you can reproduce it using the `preview` action.

![powershell_2019-04-11_21-34-52](https://user-images.githubusercontent.com/3778841/56012662-59a5b480-5ca2-11e9-9a5d-1c8d7b1c6405.png)

**Comment by dariomws306** [comment]
@jdgregson same here:
![image](https://user-images.githubusercontent.com/33589238/56044621-f7869700-5d15-11e9-938a-6209cd74a38d.png)

We are here to help with documentation issues not with product bugs. So I need to ask you if you can open a support ticket for this. We will really appreciate that.

**Comment by jdgregson** [comment]
@dariomws306 This is seeming like a bug to me, so I'd really like to open a report against the relevant project. The best I can figure, this should be opened against the `exchange` module, since [this doc](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/get-compliancesearchaction?view=exchange-ps) indicates that `Get-ComplianceSearchAction` is part of the `exchange` module. Unfortunately, I am unable to find a repo on GitHub for that module. I've searched the Microsoft, OfficeDev, and PowerShell project pages and found no related repos.

Do you know where I can find the repo for this module, or how else I would go about filing such a bug report?

**Comment by dariomws306** [comment]
@jdgregson the place to report a bug is Support, Github is for documentation issues and User Voice to request/sugged new features.
Sorry but I have to insist you to open a support ticket. We will really appreciate that.

**Comment by yogkumgit** [comment]
@jdgregson  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
