### ISSUE TITLE
Unified Messaging cmdlets ar missing in Exchange 2019 CU1

### ISSUE THREAD

**Issue by AleBros** [MicrosoftDocs/office-docs-powershell#3110]
I've been struggling trying to find and import this cmdlets into Exchange 2019 on premise installation, but there is no one UM cmdlet into PowerShell.
In the following link it seems to be discontinued
https://docs.microsoft.com/en-us/exchange/new-features/discontinued-features?view=exchserver-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d9927a-23d0-c113-caaf-83b01780ff1f
* Version Independent ID: bdfaa15e-077b-7858-6196-443f0af3b828
* Content: [Get-UMService (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/unified-messaging/get-umservice?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/unified-messaging/Get-UMService.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/unified-messaging/Get-UMService.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@AleBros, there is no UM in Exchange 2019. But, the UM cmdlets were supposed to remain in Exchange 2019 only for coexistence with Exchange 2016 and Exchange 2013.

Are you running Exchange 2019 RTM or CU1?

**Comment by AleBros** [comment]
I am running CU1.
First I installed without CU1.
Without CU1, ECP interface returned an error when I was clicking on "unified messaging" into the server property for Exchange 2019; The error's description was that Exchange server was not listed in the domain controller.
The Exchange 2013 was working fine.

Then I installed CU1 and the new error message in ECP was that Get-UMService cmdlet is unknown, both for Exchange 2019 and Exchange 2013 (so 2013 stopped working).
Opening EMC I got that no "UM" cmdlets are available in 2019, and in 2013 are still available.

**Comment by chrisda** [comment]
@AleBros, I think the intent was for UM management on Exchange 2019 servers from the Exchange Management Shell Only.

In the EAC on my 2019 CU1 server, I see no Unified Messaging "tab" on the left (it jumps from Mobile to Servers). But, the cmdlets are available to me.

Does this command run for you without error and return (many) results?

```
Get-ManagementRoleEntry *\*-UM*
```

**Comment by AleBros** [comment]
The command works without any error and lists 132 CmlLets.

There is also the `Get-UMService` command which is listed in this way:
`[PS] C:\Windows\system32>Get-ManagementRoleEntry *\Get-UMService`
`Name                           Role                      Parameters`
`----                           ----                      ----------`
`Get-UMService                  View-Only Configuration   {Debug, DomainController, ErrorAction, ErrorVariable, Identity, OutBuffer, OutVariable, Verbose,...`
`Get-UMService                  Unified Messaging         {Debug, DomainController, ErrorAction, ErrorVariable, Identity, OutBuffer, OutVariable, Verbose,...`
`Get-UMService                  Exchange Servers          {Debug, DomainController, ErrorAction, ErrorVariable, Identity, OutBuffer, OutVariable, Verbose,...`
`Get-UMService                  O365SupportViewConfig     {Debug, DomainController, ErrorAction, ErrorVariable, Identity, OutBuffer, OutVariable, Verbose,...`


but when I type Get-UMService i get (italian version):
`Get-UMService : Termine 'Get-UMService' non riconosciuto come nome di cmdlet, funzione, programma eseguibile o file script. Controllare l'ortografia del`
`nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In riga:1 car:2`
`+  Get-UMService`
`+  ~~~~~~~~~~~~~`
`    + CategoryInfo          : ObjectNotFound: (Get-UMService:String) [], CommandNotFoundException`
`    + FullyQualifiedErrorId : CommandNotFoundException`

I start thinking that I have some PowerShell configuration lack,
I'll investigate.

Thanks for interesting in my issue.

**Comment by AleBros** [comment]
![ecp-unifiedmessaging](https://user-images.githubusercontent.com/40704063/56793712-e1480300-680c-11e9-840d-74ea62829d47.PNG)
I did attach a screenshot for the Exchange Control Panel path in which I get the error.

**Comment by chrisda** [comment]
@AleBros, I see the same thing on my Exchange 2019 server (in my one server test organization):

![image](https://user-images.githubusercontent.com/33166947/56820923-fcf9dc00-6801-11e9-8837-fc7882dc99be.png)

And, I've confirmed that even though the UM cmdlets are present in RBAC, they aren't actually available. Get-UM, Set-UM, etc. do not tab complete, and Get-UMService returns that same error in the screenshot, so something is blocking access to all UM cmdlets.

At this point, you should open a support ticket. Please report back here if they give you an answer.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and sharing this explanation. 
@AleBros Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:  

https://docs.microsoft.com/office365/admin/contact-support-for-business-products

**Comment by yogkumgit** [comment]
@officedocsbot close
