### ISSUE TITLE
SharePoint PowerShell pages are broken on docs.microsoft.com

### ISSUE THREAD

**Issue by TroyStarr** [MicrosoftDocs/office-docs-powershell#3113]
1. Browse to https://docs.microsoft.com/powershell/sharepoint/ and click on any of the following links:
a. [SharePoint Server cmdlets](https://docs.microsoft.com/powershell/module/sharepoint-server/)
b. Reference > [sharepoint-online](https://docs.microsoft.com/powershell/module/sharepoint-online/?view=sharepoint-ps)
c. Reference > [sharepoint-server](https://docs.microsoft.com/powershell/module/sharepoint-server/?view=sharepoint-ps)
2. Browse to https://docs.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets?view=sharepoint-ps and click on the following link:
a. [SharePoint Server cmdlets](https://docs.microsoft.com/powershell/module/sharepoint-server/index?view=sharepoint-ps)

**Result:**
You get HTTP 404 "Page not found" errors from docs.microsoft.com.

**Expected Result:**
We shouldn't have broken links in our SharePoint PowerShell documentation.  You should be taken to the expected content.

**Comment by kenwith** [comment]
@TroyStarr - checking.

**Comment by kenwith** [comment]
Getting the same for all pages..  https://docs.microsoft.com/en-us/powershell/module/skype/  and others.. checking with the team that owns docs.microsoft.com now.

**Comment by kenwith** [comment]
Update - talking with the team that owns docs.microsoft.com now... all Office PowerShell links appear to be down.. they are working on it now.

**Comment by kenwith** [comment]
Fixed for everything but Exchange. Team is still working on the Exchange cmdlets page. @TroyStarr thanks for reporting!

**Comment by TroyStarr** [comment]
Thanks @kenwith !
