### ISSUE TITLE
Get-MailTrafficReport doesn't return 180 days worth of data

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/office-docs-powershell#3119]
Running Get-MailTrafficReport only returns data for the last two weeks. At the time of this comment, that is from 3/8/19 through 3/22/19. Including the startdate and enddate parameters like so: (Get-MailTrafficReport -StartDate 01/01/2019 -EndDate 03/22/2019) it returns data from 1/1/19 through 1/28/2019. Based on this documentation, I should be seeing results from as far back as September 2018 using just Get-MailTrafficReport, and I should see all data between January and the end of March when using the -StartDate and -EndDate parameters. This is consistent across two tenants. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb20809-8f21-dfd3-23bf-bbfb82679619
* Version Independent ID: be54b158-1672-5ae9-6a6d-139a7850c67b
* Content: [Get-MailTrafficReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/reporting/get-mailtrafficreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/reporting/Get-MailTrafficReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/reporting/Get-MailTrafficReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @terrogin, thank you for your feedback.

I am trying this cmdlet and it's working good here. I can return data from 10/12/2018 to today (04/11/2019).
Did you try adding "-PageSize 5000"?

Also this works for me:
Get-MailTrafficReport -Direction Inbound -StartDate 01/01/2019 -EndDate 04/11/2019 -PageSize 5000

**Comment by terrogin** [comment]
This is interesting. I have access to two tenants and both display the same issues. I tried using the -PageSize parameter and that certainly makes a difference. Running your same command, I return 101 days of data, which is accurate. Without the -PageSize parameter, I only return 45 days even when specifying a StartDate and EndDate. I checked for the count of days as well and pasted my output below.

PS C:\> Get-MailTrafficReport -Direction Inbound -StartDate 01/01/2019 -EndDate 04/11/2019 -PageSize 5000 | Select -Unique Date | Measure
Count    : 101

PS C:\> Get-MailTrafficReport -Direction Inbound -StartDate 01/01/2019 -EndDate 04/11/2019 | Select -Unique Date | Measure
Count    : 45

...and running the cmdlet by itself, I only get back 15 days worth of data:

PS C:\> Get-MailTrafficReport | Select -Unique Date | Measure
Count    : 15

PS H:\> Get-MailTrafficReport -Direction Inbound | Select -Unique Date | Measure
Count    : 15

________________________________

**Comment by dariomws306** [comment]
If you have a lot of data it won't show you all, only the first 1000 entries by default. Max is 5000.

To see all you should use a combination of -Page and -PageSize.

I hope it's useful for you.

**Comment by terrogin** [comment]
I'm not sure I fully understand. If I use Get-MailTrafficReport by itself with a PageSize of 5000, I have 552 results. If I use the same cmdlet with a StartDate and EndDate and a PageSize of 5000, I have 3,693 results. Why would the command with the StartDate and EndDate return more data than the cmdlet without the StartDate and EndDate if both specify a PageSize of 5000? For example:

PS C:\> Get-MailTrafficReport  -StartDate 01/01/2019 -EndDate 04/11/2019 -PageSize 5000 | Measure
**Count    : 3693**

PS C:\> Get-MailTrafficReport -PageSize 5000 | Measure
**Count    : 552**

**Comment by dariomws306** [comment]
Sorry, I wanted to say that if you have more than 5000 entries you should also use the -Page parameter.

Based on your latest examples I think all is running fine for you, rigth?

**Comment by terrogin** [comment]
Not really - Based on the first two commands below, there are only 552 entries on page 1 and 2 combined when not using the StartDate and EndDate parameters. However, when using the StartDate and EndDate parameters, I see over 3000 results. Why do I not see over 3000 results when using the first two commands though? I'm not even using the -Page parameter in the last example to return the 3693 results.

PS C:> Get-MailTrafficReport -Page 1 -PageSize 5000 | Measure
Count : 552

PS C:> Get-MailTrafficReport  -Page 2 -PageSize 5000 | Measure
Count : 0

PS C:> Get-MailTrafficReport -StartDate 01/01/2019 -EndDate 04/11/2019 -PageSize 5000 | Measure
Count : 3693

**Comment by dariomws306** [comment]
Get-MailTrafficReport alone will return only 2 weeks as you said.

If you run:
Get-MailTrafficReport -StartDate 01/01/2019 -EndDate 04/11/2019 -PageSize 5000 | Measure
It returns 3693 entries, looks fine. If you remove "-PageSize 5000" it will return only 1000 entries.

But I should say that you should use StartDate and EndDate to avoid mistakes.

**Comment by terrogin** [comment]
Okay thank you, that all makes sense

________________________________

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @terrogin 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
