### ISSUE TITLE
Table formatting broken

### ISSUE THREAD

**Issue by jschlackman** [MicrosoftDocs/office-docs-powershell#3121]
The table formatting is broken and currently not rendering correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/recipient-filters/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jschlackman, the table renders fine on GitHub, but not on docs.microsoft.com. Looking into it.

**Comment by chrisda** [comment]
@jschlackman, the table formatting has been fixed.

Thanks for the feedback.
