### ISSUE TITLE
Connect-PNPOnline using local certificate without PFX?!

### ISSUE THREAD

**Issue by spplante** [MicrosoftDocs/office-docs-powershell#3125]
Hi there,

When deploying to azure, we are using the app-only pattern where we basically connect to Azure AD using an AppID and a local non-exportable certificate. When we initially created the certificate, we stored the private key of the certificate (pfx) in the AAD application key credentials and leaved the public key in the local certificates store.

This pattern is perfect because you don't have to carry around a PFX file or hash, the only way you can connect to Azure AD is by being on the actual server which has the local certificate installed and you can't export the certificate, hence why this is the pattern privileged by our organization in terms of security standards.

With Connect-PNPOnline, I tried all the different implementations using certificates but the problem is that they are all requiring the user to provide the certificate's private key (pfx), which seems odd because that's pretty much the equivalent of carrying a password isn't it?

It would be really useful to have an implementation of Connect-PNPOnline using only an AppId and the path to the local certificate, without having to pass the private key. If we could have something like the Connect-AzureAD command which supports this it would be great :

```PowerShell
Connect-AzureAD -TenantId "..." -CertificateThumbprint "[local certificate thumb print]" -AppId "..."
```

I am sure I am not the only one struggling with this

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @spplante as you may know, this issue resource is to report specifically issues in documentation, and I see, based on the description that you give, that might be more suitable for a feedback or user voice resource, as you may know also, Sharepoint PnP is community driven, I encourage you look here for that kind of resources https://docs.microsoft.com/en-us/sharepoint/dev/community/community

Hope this information helps you.

**Comment by spplante** [comment]
Thanks @get-itips, no problem!
