### ISSUE TITLE
Cmdlet does not work to update properties of Tag:DisallowCalling

### ISSUE THREAD

**Issue by ThePangy** [MicrosoftDocs/office-docs-powershell#3131]
Does this only work for the Global calling policy? When trying to run this against Tag:DisallowCalling it returns an error "Set or Remove host tab instance is not allowed." There is also not a corresponding New-CsTeamsCallingPolicy. This seems useless if you cannot create a new policy, cannot update an existing policy, and none of the existing policies are configured as needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f1bf407-1ad6-77d9-4ef1-4bc821576912
* Version Independent ID: 4630697b-375e-85f2-25b1-b944bc6dad5f
* Content: [Set-CsTeamsCallingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by piqueora** [comment]
Same pb. I confirm the comment and need of modifying the inappropriate existing calling policies without modifying the global one.

**Comment by dariomws306** [comment]
Hi @ThePangy , thank you for your feedback.

It is not yet possible to modify tag policies. I understand that it would be useful if we can do it.

I should suggest that you request this feature on User Voice:
https://www.skypefeedback.com/
https://microsoftteams.uservoice.com/forums/555103-public

**Comment by yogkumgit** [comment]
@ThePangy  Thank you very much for your kind feedback. as suggested by @dariomws306 please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by y5158** [comment]
> dariomws306

Is issue resolved?

I am also getting the same error: "Set or Remove host tab instance is not allowed."

**Comment by dariomws** [comment]
@y5158 set or remove a default tag instance is not allowed yet. You can create a new one from the Teams Admin Center and then use this cmdlet to modify it.

**Comment by y5158** [comment]
If we are not able to modify these default policies (tag:EduStudent, tag:EduFaculty, tag: Default) then why these default policies are shown in the response of cmdlets? Is it glitch?

**Comment by dariomws** [comment]
@y5158 my apologies but I don't have that information. Here we are limited to improve docs.microsoft.com.
