### ISSUE TITLE
Get-PnPList causes Azure Runbook to Suspend

### ISSUE THREAD

**Issue by pdhimate** [MicrosoftDocs/office-docs-powershell#3134]
This does not work when run within an Azure Automation Runbook. The execution is retried for 3 times and finally the Runbook is suspended without any error or message. Any workarounds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a9e9119-9db3-081d-ae57-c16b7740f2c2
* Version Independent ID: baf42f0a-9e63-ec81-fefb-b1c8dde5672e
* Content: [Get-PnPList (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnplist?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPList.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @pdhimate how are you?
This issue resource is specifically to address issues on documentation, as you might know, PnP cmdlets are community-driven, I kindly ask you to suggest this inquiry to the community, as it seems you need support on your situation, please start looking here https://docs.microsoft.com/en-us/sharepoint/dev/community/community
We will proceed closing this one.
Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @pdhimate 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
