### ISSUE TITLE
-PermanentlyDelete section has example  which is not formatted as example

### ISSUE THREAD

**Issue by mariobesen** [MicrosoftDocs/office-docs-powershell#3135]
It would be nice if parameter "-PermanentlyDelete" would have its example formatted like in other parts of this page, or at least move it to "Examples" section

For example, Get-Mailbox -Identity Laura -SoftDeleted | Remove-Mailbox -PermanentlyDelete

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c2fcd6e-73de-a00c-0296-5dbad6541977
* Version Independent ID: 4303e5b7-a703-daa4-a747-6ac202460c9f
* Content: [Remove-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/remove-mailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Remove-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Remove-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mariobesen, I made a third example. Thanks for the feedback.
