### ISSUE TITLE
Set-RetentionCompliancePolicy multiple (10) parameters with help text placeholders

### ISSUE THREAD

**Issue by msjoat** [MicrosoftDocs/office-docs-powershell#3138]
Set-RetentionCompliancePolicy (office-docs-powershell/exchange/exchange-ps/exchange/policy-and-compliance-retention/Set-RetentionCompliancePolicy.md) has 10 parameters with help text placeholders, e.g. 

{{Fill AddDynamicScopeLocation Description}}

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @msjoat, thank you for your feedback.

I have removed 2 parameters, they doesn't exist anymore. I am trying to get more information about the others 8.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @msjoat Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
