### ISSUE TITLE
Set-SPOTenant -UserVoiceForFeedbackEnabled:$false seems to have no effect on modern pages

### ISSUE THREAD

**Issue by gonadn** [MicrosoftDocs/office-docs-powershell#3145]
Set-SPOTenant -UserVoiceForFeedbackEnabled:$false on two tenants and nothing changes.
I tried it on my developer tenant and on customer production tenant without any luck.
Ref issue #508 it was an bug and has been fixed, but in my case no effect after running the powershell command. Feedback button on the right corner is still there....

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @gonadn **Thanks for your feedback.**
I tested in my test tenant and verified that the -UserVoiceForFeedbackEnabled:$false hid the Feedback button, it took some hours to reflect though. Based on this, I do not identify that a change in documentation is needed.
Thank You

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @gonadn 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
