### ISSUE TITLE
What are the values for MobileOperatorId?

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/office-docs-powershell#3146]
I assume that one value of MobileOperatorId will correspond to a single cell provider.  But what are those values?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07704e18-d2c8-d709-7394-6103107a7794
* Version Independent ID: 1b36d735-ad6a-015c-5be9-c50737d2d90f
* Content: [Set-TextMessagingAccount (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-textmessagingaccount?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-TextMessagingAccount.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-TextMessagingAccount.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jordanmills, I updated the topic with the values that are currently available in OWA (although the parameter takes any random number that you throw at it.

United States:

- AT&T: 15001

- Sprint PCS: 15004

- T-Mobile: 15005

- Verizon Wireless: 15006

Canada:

- Bell: 17001

- Telus Mobility: 17002

Romania:

- Orange Romania: 18001

**Comment by jordanmills** [comment]
I couldn't find a list like that anywhere.  That's exactly what I need for now.  Thanks!
