### ISSUE TITLE
Disconnect-MicrosoftTeams throws unsupressable error when not connected 

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/office-docs-powershell#3151]
the following code throws errors that cannot be suppressed 

``` powershell
#Microsoft Teams 
Import-Module MicrosoftTeams
Disconnect-MicrosoftTeams -ErrorAction SilentlyContinue
```
error: 
```
Disconnect-MicrosoftTeams : Object reference not set to an instance of an object.
At line:1 char:1
+ Disconnect-MicrosoftTeams -ErrorAction SilentlyContinue
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Disconnect-MicrosoftTeams], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Open.Teams.CommonLibrary.DisconnectMicrosoftTeams

```

expected is that this code does not throw an error at all ( possibly a warning) and defenitly not when the error action is specified as SilentlyContinue 

Also wrapping the code in a try /catch does not work , which is double bad

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Josverl, thank you for your comment.

Docs feedback is available to help with documentation issues. In this case I think it's a product bug so please you should open a support ticket.

Thanks!

**Comment by Josverl** [comment]
Well, I followed the link for comments on the documentation page. Can you at least add a page or  pointer to the documentation to file product bugs.

N b. Lots of other msft documentation pages allow for both. And lacking other guidance, even I as an internal msft resource struggle to find were to submit such feedback.

Should I file a documentation bug on that?

Regards, Jos

Regards,
Jos Verlinde

________________________________

**Comment by dariomws306** [comment]
Thank you for this feedback @Josverl 

I want to make sure you get the proper assistance for this issue. Lets get you over to support who has the resources to find a resolution for this issue.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by yogkumgit** [comment]
@officedocsbot close
