### ISSUE TITLE
Recommended parameter for -Identity

### ISSUE THREAD

**Issue by Languafe** [MicrosoftDocs/office-docs-powershell#3152]
What is the recommended approach to specifying the -Identity parameter? I realize I can provide either a group's display name or its alias/e-mail address, but several Office 365 groups can have the same display name, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86af7740-3abd-2245-0141-aa4a484ecbca
* Version Independent ID: db3f5b2e-9978-19ef-3da0-28e9e14bdf76
* Content: [Add-UnifiedGroupLinks (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/Add-UnifiedGroupLinks?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Add-UnifiedGroupLinks.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Add-UnifiedGroupLinks.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Languafe, correct. The display name value in virtually all objects in the Exchange universe does not have a uniqueness requirement, so I removed display name from that parameter description, as well as a bunch of others.

There really is no recommended approach as to how to identify an O365 group; you should be able to use any value that is required to be unique. Obviously, some values (alias, email address) are much easier to work with than others (GUID, DN).
