### ISSUE TITLE
JournalEnabled parameter is incorrect

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/office-docs-powershell#3153]
-JournalEnabled 
The JunkEmailEnabled parameter specifies whether the Junk Email folder and junk email management are available in Outlook on the web.
$true: The Junk Email folder and junk email management are available in Outlook on the web. This is the default value.
$false: The Junk Email folder and junk email management aren't available in Outlook on the web.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be262e6d-2342-9d63-e807-ad931f15b847
* Version Independent ID: b20464e1-8659-1d1c-5010-c73526f440ca
* Content: [Set-OwaVirtualDirectory (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access-servers/set-owavirtualdirectory?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access-servers/Set-OwaVirtualDirectory.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access-servers/Set-OwaVirtualDirectory.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@vboyev-MSFT, do you have a correct description that you would want me to use instead?

**Comment by chrisda** [comment]
@vboyev-MSFT, ugh; I didn't read closely enough. Clearly, that's a copy/paste error talking about the JunkeMailEnabled parameter in the JournalEnabled parameter. I fixed them both.

Thanks for the feedback.
