### ISSUE TITLE
Get-PNPGroup does not return Domain groups used in SharePoint Online

### ISSUE THREAD

**Issue by istavnit** [MicrosoftDocs/office-docs-powershell#3158]

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @istavnit thanks for your feedback.
Yes, currently, that is the expected behaviour of the cmdlet, as the article says Returns a specific _SharePoint group_ or all _SharePoint groups_ in site.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @istavnit 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
