### ISSUE TITLE
Doesn't exist onprem. 

### ISSUE THREAD

**Issue by DimaRazb** [MicrosoftDocs/office-docs-powershell#3161]
The commandlet does not exist onprem. Then, applies to line 
Applies to:
Exchange Server 2016, Exchange Server 2019, Exchange Online
should  be aligned to only EXO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2926ab00-f736-742e-7987-82e540be4322
* Version Independent ID: b49ac1e0-44ce-30b2-c2bf-246968125990
* Content: [Restore-RecoverableItems (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/restore-recoverableitems?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Restore-RecoverableItems.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Restore-RecoverableItems.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot close
