### ISSUE TITLE
New-ComplianceTag -FilePlanProperty

### ISSUE THREAD

**Issue by beigewell** [MicrosoftDocs/office-docs-powershell#3165]
I would like to add new File Plan Properties and configure these as a bulk import the powershell seems to be partly there but it is hard to work out what it is expecting.

I have tried entering the fileplanpropertydepartment and adding a new department but this crashes the powershell?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92aaa6d0-68c3-57b6-7f87-0f954ef252f1
* Version Independent ID: 984fcc50-f5fc-548e-fb50-f818a1bcf564
* Content: [New-ComplianceTag (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-retention/new-compliancetag?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-retention/New-ComplianceTag.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-retention/New-ComplianceTag.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Thank you @chrisda!!

Do we have some information to add in the description area?

**Comment by beigewell** [comment]
can this be documented with examples as I am still getting failures on my tenant?

Name: Administration
WARNING: An unexpected error has occurred and a Watson dump is being generated: Failed to parse File plan
metadata value.

**Comment by bongo-ho** [comment]
Seeing same - where can add in properties (as per the @beigewell's screenshot) via UI but there's no apparent way to manage via powershell for fileplan properties. Any news, details, description would be useful.

**Comment by bongo-ho** [comment]
@chrisda - I've systematically been trying every variation of switches, parameter variables and strings based on -FilePlanProperty flag. Export of a tag which has the FilePlanMetadata added via the ComplianceCentre UI shows pared Descriptor and Value e.g. 

{"Settings":[{"Key":"FilePlanPropertyDepartment","Value":"Finance"},{"Key":"FilePlanPropertyCitation","Value":"Commodity Exchange Act"},{"Key":"FilePlanPropertyReferenceId","Value":"1"},
{"Key":"FilePlanPropertyAuthority","Value":"Business"},{"Key":"FilePlanPropertyCategory","Value":"Administration"}]}

 - but there is apparently no combination with which to create/update these on a ComplianceTag using PowerShell. The documentation in gitHub is the same as on docs - neither of which have accurate, or useful examples or explanation on how to use this flag. Is there any progress on atleast updating the documentation to be more complete - or even working example of how to utilise it?

**Comment by chrisda** [comment]
@beigewell, @bongo-ho, I received information about valid values for FilePlanProperty, and I've updated the topic. The syntax is very complex.

**Comment by beigewell** [comment]
Thanks @chrisda Is it possible to get one example? I can see the update to -FilePlanProperty
{{ Fill FilePlanProperty Description }} on the docs page or have you updated the valid values somewhere else?

**Comment by chrisda** [comment]
@beigewell, the description is basically an example. Use the Get-FilePlanProperty* cmdlets to get the name values, then use the two commands as descfribed to store the values in a variable to use for the parameter.

I realize the cmdlet reference topics for the 27 file plan property cmdlets aren't live yet; I'm looking into it. When those publish, they will contain examples of how to create the file plan properties themselves.

**Comment by beigewell** [comment]
@chrisda @bongo-ho brilliant thanks I’ll check it out happy Easter

**Comment by bongo-ho** [comment]
Thanks @chrisda . 
I understand that were missing documentation, but all the commands are available when run them. I've been working on script for while, so slotting in the -FilePlanProperty wasn't difficult. Have found an issue with -ReferenceId attribute. 

Adding metadata via UI for ReferenceId will block the user adding duplicates:
![image](https://user-images.githubusercontent.com/49170074/56396817-d03f4500-6294-11e9-83c9-b425c3164cff.png)

The ComplianceCentre FilePlan UI guides you to create an unique ReferenceId per item, although no constraints on format (its a string). This is acceptable when using number-referencing convention. 

Via powershell the command errors if you *DONT* use an existing ReferenceId when creating a new label, or when update using "Set-"
![image](https://user-images.githubusercontent.com/49170074/56396869-17c5d100-6295-11e9-918d-ffcb315058db.png)

I have tried multiple variations this morning and proven it's not script reference, but the command and incorrect validation on service.

Q: Do we raise a bug here? Or is this a separate issue?

**Comment by bongo-ho** [comment]
@chrisda @beigewell I've gone ahead and posted a new issue with bit more detail about reproducing issues. See: https://github.com/MicrosoftDocs/office-docs-powershell/issues/3251.

Thanks for help with this Chris
