### ISSUE TITLE
Mention of an undocumented/inexistent parameter

### ISSUE THREAD

**Issue by bethouxa** [MicrosoftDocs/office-docs-powershell#3166]
In the section about the -PrimarySMTPAddress parameter, you mention an EmailAddresses parameter:

"The PrimarySmtpAddress parameter specifies the primary return email address that's used for the recipient. If it's available on this cmdlet, you can't use the **EmailAddresses** and PrimarySmtpAddress parameters in the same command."

A search for this parameter on this page does not yield anything, and the best results when seaching for "EmailAddresses RemoteMailbox" point to this page. This parameter does not seem to be documented anywhere, but I'd really be interested in such a parameter if it allow me to specify multiple email addresses for a new user.

This mention also appears in the documentation of the Enable-RemoteMailbox cmdlet, in the section about the same parameter, -PrimarySmtpAddress.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb103c0b-9021-3a77-0bf6-601df9a0fe38
* Version Independent ID: 561d8c53-5019-4a31-efa1-c2b635818f5a
* Content: [New-RemoteMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/new-remotemailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/New-RemoteMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/New-RemoteMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@bethouxa, that text is a result of trying to use the same description for the same parameter across multiple cmdlets. The PrimarySMTPAddress parameter is available in 23 cmdlets. The EmailAddresses parameter is available in 12 of those. I cleaned them all up so they match what's actually available on the cmdlet: I either removed that sentence entirely, or I changed it to "You can't use the EmailAddresses and PrimarySmtpAddress parameters in the same command."

Although the EmailAddresses parameter isn't available on New-RemoteMailbox, it is available on Set-RemoteMailbox.

Does that help?

**Comment by dariomws306** [comment]
Thank you @chrisda!!

@bethouxa, does the update help you?

Thanks.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution. @bethouxa Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
