### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by jcallaghan** [MicrosoftDocs/office-docs-powershell#3168]
Could you please clarify the permissions "Requires Tenant administrator permissions" i.e. Global Administrator or SharePoint Administrator. TIA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00564430-e36d-1a32-8e0d-0e76a41a7bc2
* Version Independent ID: e03ea6c2-482f-8add-46dd-e83727af4fe5
* Content: [Set-SPOOrgNewsSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spoorgnewssite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOOrgNewsSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOOrgNewsSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @antonlabunets
* Microsoft Alias: **antonla**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @jcallaghan , thank you for your feedback.

I am updating this article to detail permissions.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @jcallaghan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by paylord** [comment]
@yogkumgit  While it seems logical that this should be able to be set by a SharePoint Admin, does it not need a tenant admin to connect to Connect-SPOService?  Is there another way to do this or should this just be documented as tenant admin?
