### ISSUE TITLE
Link to Skype 2019 equivalent 

### ISSUE THREAD

**Issue by jyoungComputerTalk** [MicrosoftDocs/office-docs-powershell#3169]
Please have a link to the SFB 2019 equivalent for this command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c9c3b1-7919-bd59-9ee8-5e2198c61fac
* Version Independent ID: 4a0f1966-0c42-e2ba-1c61-c6602dcc9a46
* Content: [Get-CsPoolUpgradeReadinessState (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-cspoolupgradereadinessstate?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Get-CsPoolUpgradeReadinessState.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsPoolUpgradeReadinessState.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @jyoungComputerTalk , thank you for your feedback.

You should use Get-CsUpgradeDomainInfo instead of Get-CsPoolUpgradeReadinessState for Skype for Business 2019. But there isn't an article for this cmdlet yet so I cannot put the link here.

**Comment by yogkumgit** [comment]
@kenwith please merge the PR #3809

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @jyoungComputerTalk  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
