### ISSUE TITLE
Get-DlpSensitiveInformationTypeRulePackage - Identity "Microsoft Rule Package" | Format-List

### ISSUE THREAD

**Issue by geneagoe** [MicrosoftDocs/office-docs-powershell#3170]
There is a space between "-" and "Identity"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e86a033-a386-9720-6ef8-a98b6681ec52
* Version Independent ID: 46bd22ba-d92e-c781-fdc6-5a0303985bd8
* Content: [Get-DlpSensitiveInformationTypeRulePackage (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/get-dlpsensitiveinformationtyperulepackage?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpSensitiveInformationTypeRulePackage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpSensitiveInformationTypeRulePackage.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@geneagoe, I fixed it, but in the future, so can you. See https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md.

**Comment by geneagoe** [comment]
Thank you Chris,

I will do it in the future 😊

Best Regards,
--
George Marian Neagoe

EMEA Office 365 Outlook Escalations
Customer Services and Support


george.neagoe<mailto:a-geneag@microsoft.com>@microsoft.com
Mon-Fri 10 - 7 GMT +2

[Microsoft]
﻿
If you have any feedback about my work, please let either me or my manager Ioan Catrea know at iocatrea@microsoft.com<mailto:iocatrea@microsoft.com>
