### ISSUE TITLE
Related Links broken

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/office-docs-powershell#3171]
I want to find the equivalent command for Exchange Online (Hybrid) but the "Online Version" link in the "Related Links" section just loops back to this same on-premises page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b1a8a89-e8cc-08f5-7a68-39bc9625f6e3
* Version Independent ID: 789a67d2-ff71-e607-f531-338c2b66b2cb
* Content: [Enable-DistributionGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/Enable-DistributionGroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Enable-DistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Enable-DistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@thommck, the intent of that Online Version link in the RELATED LINKS section is to provide a web link from command line help when you run the command:

```
Get-Help <Cmdlet> -Online
```

More to the point, there is no PowerShell environment for Hybrid; a cmdlet is either available in Exchange Online PowerShell, Exchange Server PowerShell (2010, 2013, 2016, or 2019), or both. I would presume the only kinds of groups that are visible and synchronized to Exchange Online in a hybrid environment would be mail-enabled universal security groups. If you are in a hybrid environment, I would assume that you can run this cmdlet in the Exchange Management Shell in an on-premises Exchange server to mail-enable existing universal security groups in your Active Directory.
