### ISSUE TITLE
Link to Module Broken  +  Please link to what to do to get access to this command

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/office-docs-powershell#3175]
1.  On top of page shows Link to Module Exchange: 404 - Page not found
2.  Please link to what to do to get access to this command "Get-OMEConfiguration".
3.  I read somewhere there are parameters to this command, what are they?
Thank you
Bart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ae2cba-8c1d-ebd1-9834-f5a4881830cc
* Version Independent ID: 6134df0d-c336-4288-c704-63cf742c0c5e
* Content: [Get-OMEConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/get-omeconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/encryption-and-certificates/Get-OMEConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/encryption-and-certificates/Get-OMEConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@blouwagie:

1. Known issue; we're working on it. Technically, there is no "Exchange" module.

2. Interesting suggestion. The Exchange Online PowerShell connection instructions are in the conceptual area "above the line" in the section on the left side of the page: https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.

3. Normally, most cmdlets have some parameters. These would be visible in the SYNTAX section at the top of the topic, and explained fully and individually further down in the topic. But, there are no parameters available for Get-OMEConfiguration. Get- commands only allow you to view, not change properties. On the other hand the [Set-OMEConfiguration](https://docs.microsoft.com/powershell/module/exchange/encryption-and-certificates/set-omeconfiguration) has lots of parameters.

**Comment by dariomws** [comment]
The Exchange module link issue was fixed this week. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
