### ISSUE TITLE
”Enable-MailUser“ Search failed by PowerShell Module Browser

### ISSUE THREAD

**Issue by chuanjiao10** [MicrosoftDocs/office-docs-powershell#3176]
1 Search ”Enable-MailUser“ can get right link in bing.com. the link is:
 https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/enable-mailuser?view=exchange-ps

2 type 'enable-m' ,or  type 'enable-ma', search failed by PowerShell Module Browser
look:
**exchange module in the PowerShell Module Browser**
https://docs.microsoft.com/en-us/powershell/module/

**Comment by chrisda** [comment]
@chuanjiao10, we're working on the problem of Exchange cmdlets in the PowerShell module browser. It's a recent issue.

Thanks for the feedback.
