### ISSUE TITLE
How to hide themes on classic team sites?

### ISSUE THREAD

**Issue by jjinatlanta** [MicrosoftDocs/office-docs-powershell#3179]
I've made this setting on our tenant, and it hides default themes on Modern team sites, but sites that are created as a classic team site show a theme picker on the settings (gear) menu which shows other themes - even for non-admin/non-site-owners. How can we disable that theme picker?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad190894-c814-d07b-9477-bd866a4d9516
* Version Independent ID: 19fb8638-dc5f-c6c8-f0a7-142a79c7d0af
* Content: [Set-SPOHideDefaultThemes (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spohidedefaultthemes?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHideDefaultThemes.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHideDefaultThemes.md)
* Service: **sharepoint-powershell**
* GitHub Login: @vesajuvonen
* Microsoft Alias: **vesaj**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @jjinatlanta, thank you for your feedback.

You cannot disable the theme picker on Classic Sites. I have added a note to the article to specify this.

**Comment by VesaJuvonen** [comment]
Fixed with #3279.
