### ISSUE TITLE
BUG - ExchangeLocation gets cleared when search name has space and search is assigned to a case.

### ISSUE THREAD

**Issue by zaicnupagadi** [MicrosoftDocs/office-docs-powershell#3181]
Hi,

I noticed that when creating a compliance search like this:
New-ComplianceSearch -Name "Search 1" -ExchangeLocation "all" -ContentMatchQuery "test123 OR 123qwe" 
it all works and ExchangeLocatoin is {ALL}, but when creating it like this:
New-ComplianceSearch -Name "Search 1" -ExchangeLocation "all" -ContentMatchQuery "test123 OR 123qwe" -case "1234"
Exchange location is empty. I fugured out that it is a matter of space in the name of the search.

To sum up:

When creating a compliance search and name of the search contains a space - it is not an issue UNTIL you would like it to be assigned to a case - in such situation search name cannot contain a space sign as then the ExchangeLocation attribute is cleared.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e72de6a-dd0f-e6e3-c4b1-63ee1cf752e8
* Version Independent ID: 228e51b7-a16a-1e5d-11c9-95cdc30b23dd
* Content: [New-ComplianceSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-compliancesearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@zaicnupagadi, thanks for writing that up. I updated the description of the Name and Case parameters accordingly.
