### ISSUE TITLE
This is not

### ISSUE THREAD

**Issue by CallMeByMyName** [MicrosoftDocs/office-docs-powershell#3182]
This is not a PSModule or PSSnapin.

What is process to add Connect-EXOPSSession on ISE VSCode and another ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connexion à Exchange Online PowerShell avec l’authentification multifacteur](https://docs.microsoft.com/fr-fr/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell.fr-FR/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @CallMeByMyName, thank you for your comment.

Here you can find the information your are looking for:
https://blogs.technet.microsoft.com/richardroddy/2018/04/04/using-powershell-ise-to-connect-to-exchange-online-when-mfa-is-enabled/

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @CallMeByMyName Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by jordanmills** [comment]
Install-Module CreateExoPsSession

It doesn't do the implicit session reconnection thing yet, but it's an actual module, not the fake module from the MS site.
