### ISSUE TITLE
Install is not working

### ISSUE THREAD

**Issue by S3l3ct3d** [MicrosoftDocs/office-docs-powershell#3183]
When using IE to download and install, I get a popup. "Application Install - Security Warning" Your administrator has blocked this application because it potentially poses a security risk. 

Name: Microsoft Exchange Online Powershell Module

From: cmdletpswmodule.blob.core.windows.net

I am using IE, tried Edge as well. Uninstalled all third-party AV products, disabled Windows Defender real time protection and still nothing works. Any assistance would be helpful.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@S3l3ct3d, it should work. Are there GPO or other IE/Edge restriction for the Internet zone?

**Comment by S3l3ct3d** [comment]
nope, I checked with our infrastructure team and there are not any GPO restrictions set. I am installing as local admin.

**Comment by chrisda** [comment]
@S3l3ct3d, I'm sorry, but the best course of action is to open a support ticket. When you find the answer, please report back here and I'll update the topic if required.

**Comment by franklesniak** [comment]
I ran into this, too. The workaround for me was to navigate to this key in the registry:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\Security\TrustManager\PromptingLevel
and configure the values "Internet", "LocalIntranet", and "TrustedSites" to "Enabled".
