### ISSUE TITLE
Currently not working

### ISSUE THREAD

**Issue by Troy-Phillips** [MicrosoftDocs/office-docs-powershell#3188]
This page/function should be removed until it is working/supported.  Looks like this was added too early

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1b44e3-4af5-1458-d931-72a0f698732b
* Version Independent ID: 1751767f-1d8a-7750-35b9-725b5a3ad705
* Content: [Start-SPOSiteRename (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/start-spositerename?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteRename.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteRename.md)
* Service: **sharepoint-powershell**
* GitHub Login: @joseOrtega
* Microsoft Alias: **j0rt3g4**

**Comment by Troy-Phillips** [comment]
Error Code: -5,It's not supported

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by smazhar007** [comment]
This command doesn't work, is there any timeline when this will be supported?

**Comment by DavidCunhaMsft** [comment]
This cmdlet is only available for the Preview admin center. Please Enroll here: https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR3CCKNES_u9Bul1dZT-hbi5UNTFUODdKQVNFQUJMRzAxTVhUMUsyWFlOOC4u

**Comment by get-itips** [comment]
Hello everyone,
Thanks for your feedback.
I can confirm that the cmdlet is not yet available for production use.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Troy-Phillips 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
