### ISSUE TITLE
The "WhatIf" does not work.

### ISSUE THREAD

**Issue by zaicnupagadi** [MicrosoftDocs/office-docs-powershell#3189]
The "WhatIf" does not work - it creates a search.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c994114-5ddc-27b5-dcd4-88ddfdf8c9d3
* Version Independent ID: 126d4801-9617-e8f6-49cb-76feff8f4dd2
* Content: [New-MailboxSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-mailboxsearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-MailboxSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-MailboxSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @zaicnupagadi, thank you for your feedback.

It's true, I have tried this on Exchange Online and it created the search. Where did you try it?

![image](https://user-images.githubusercontent.com/33589238/61654243-5f903600-ac92-11e9-9b9d-7915267fb339.png)

**Comment by dariomws306** [comment]
I have tried it on Exchange 2016 and same issue.

Also there is a typo in the whatif message: "What if: New **MaibloxSearch** Legal-ProjectX."

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #3891

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @zaicnupagadi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
