### ISSUE TITLE
Dumpster (the "purges" folder) is searched  by default, and shouldn't be - serious GDPR issue.

### ISSUE THREAD

**Issue by zaicnupagadi** [MicrosoftDocs/office-docs-powershell#3190]
When running New-MailboxSearch it searched dumpster by default and shouldn't be. Only "Search-Mailbox -Searchdumpster:$false" works correctly, please rectify it as this can be serious GDPR issue as people are getting emails they should not supposed to see any more.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @zaicnupagadi, thank you for your feedback.

I have tried this and you are right, -Searchdumpster:$true is applied by default with New-MailboxSearch. I have updated the article.

To request a change to this behaviour I have to recommend you go to User Voice (https://office365.uservoice.com/), we are here to help on documentation issues/updates. To feature change request you should go to User Voice.

This paramater only applies to Exchange 2010 and it will be out of support on January 14, 2020. So I understand that this feature update/request won't be taked into consideration.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @zaicnupagadi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
