### ISSUE TITLE
Exchange 2010

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/office-docs-powershell#3191]
Hello, this article should also apply to Exchange 2010 but Exchange 2010 does not have the same attributes on send connectors as Exchange 2013/2016. For example -TlsCertificateName is not recognized by Exchange 2010.
I would make a different article applicable to Exchange 2010.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7b9147-7a6d-765b-86fe-a77d360f07b6
* Version Independent ID: 1e07c553-cb5c-84d7-2824-4675db73dbd3
* Content: [Set-SendConnector (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/set-sendconnector?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Set-SendConnector.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Set-SendConnector.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeroenDronkers, if you look at the Applies To value for each parameter in its description, you'll see which version of Exchange server the parameter applies to. If a parameter is 2010 only, we typically call that out as the first sentence of the description.

Part of the move of content from TechNet to docs.microsoft.com was single-sourcing of topics, and the issue you describe is a direct result of that.
