### ISSUE TITLE
https and not http

### ISSUE THREAD

**Issue by kenwith** [MicrosoftDocs/office-docs-powershell#3192]
All links should use https. If there are any links that are http:// then we need to change them to https://

**Comment by kenwith** [comment]
One thing to be aware of is that we should differentiate between URLs used in cmdlet help examples vs. URLs to content we’re hosting.  So if a cmdlet help example is using "http://servername" as a parameter value, we should probably leave that as is.  But if cmdlet help is referring to something we’re hosting at go.microsoft.com, technet.microsoft.com, or docs.microsoft.com, we should update those to use SSL

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @kenwith Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
