### ISSUE TITLE
SPO permissions listed

### ISSUE THREAD

**Issue by bartbilliet** [MicrosoftDocs/office-docs-powershell#3194]
"You must be assigned the global administrator role on the SharePoint Online site on which you are running the PowerShell cmdlet."

This phrase doesn't make sense to me. You cannot be a 'global administrator' on a specific SPO site. Global Administrator is a tenant-wide role. You could be a Site Collection Administrator for a specific site though. 
For running SPO powershell cmdlets, I think no more than SharePoint Online Administrator should be required? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d426f1f-d15b-4ba5-d980-fea5fa044188
* Version Independent ID: f10f10c6-974a-a748-732d-d7a7a4d9a5c7
* Content: [Overview](https://docs.microsoft.com/en-us/powershell/sharepoint/overview?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/docs-conceptual/overview.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/overview.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @bartbilliet 
Thanks for your feedback.
I created a Pull Request to correct the documentation with the correct permission needed.
**Thank you.**

**Comment by yogkumgit** [comment]
@Techwriter40 please merge PR #3330

**Comment by yogkumgit** [comment]
Gentle reminder @Techwriter40 please merge PR #3330

**Comment by Techwriter40** [comment]
I've had this talk before with the product team, and we agree the current guidance is correct.  so I will not be accepting this change.

**Comment by bartbilliet** [comment]
It might be correct, but it's not specific (least-privilege)? For none of the SharePoint Online cmdlets you would require a Global Administrator (tenant-wide) role. None of our SharePoint Online delegated admins have a 'Global Administrator' role assigned, still they can use the SharePoint Online cmdlets without any issues.

**Comment by get-itips** [comment]
Hello @Techwriter40 I read your comment about not to change the article, did you see the answer by @bartbilliet ? if you still think to close this issue please do. Thanks @yogkumgit

**Comment by get-itips** [comment]
Ok @trent-green merged the PR, so this can be closed now.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @bartbilliet Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
