### ISSUE TITLE
Default request timeout is wrong

### ISSUE THREAD

**Issue by Koning53** [MicrosoftDocs/office-docs-powershell#3195]
It actually is 1800000. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f910a5c-5883-6394-19a3-4cf1670c431f
* Version Independent ID: 4451fe4c-df86-34a8-0db0-46a47e70b5a5
* Content: [Connect-PnPOnline (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Koning53 thanks for your feedback!
I created a PR to correct the documentation of this cmdlet.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Koning53 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
