### ISSUE TITLE
The output for Start-SPMTMigration could be improved as an object

### ISSUE THREAD

**Issue by AspenForester** [MicrosoftDocs/office-docs-powershell#3200]
In Version 1.0 of Module Microsoft.SharePoint.MigrationTool.PowerShell, the output of Start-SPMTMigration is just text telling the user the Migration is complete, whether all tasks were successful or not, and where to find the logs.

I think most PowerShell users would find it far more desirable to get that information in the form of an object that includes the number of files scanned, filtered, migrated, time elapsed, and log file location.

In fact, everything that's in the "SummaryReport" CSV should just be output as an object.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @AspenForester 

First of all, **thanks for your feedback, we really appreciate it**.
This issue resource is specifically to report issues with documentation, besides that, I tested the cmdlet to verify the current behaviour and information on screen. Based on that, I think your feedback is more suitable for a User Voice proposal, please visit https://sharepoint.uservoice.com/

**Thank you.**

**Comment by yogkumgit** [comment]
@AspenForester as advised please log an issue as User Voice,  concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by AspenForester** [comment]
Thanks! I will do that!

**Comment by yogkumgit** [comment]
@officedocsbot close
