### ISSUE TITLE
Microsoft Teams and PowerShell-Support - it's a shame what M$ is offering

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/office-docs-powershell#3204]
Good evening

We've got here because we have clicked a link to give feedback to the M$ Teams PowerShell Module Product.

We tried to automate M$ Teams using PowerShell - and after one year, it's still a nightmare. There are still no commands to add / delete Users from Channels? After more than one year, the PowerShell Module is still in Beta, which means: not professionally tested and released?

Because the M$ UserVoices are largely ignored, it probably doesn't help here either:
It's really a shame that M$ didn't manage to provide a useful, complete and tested PowerShell module for M$ Teams automation within the last year.

Maybe M$ should increase the license costs once more to make it worthwhile to provide professional tools for the half a million users you will probably have within some month?

Kind regards,
Thomas

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by justjeff2018** [comment]
Agree, managing a large environment with Teams is a nightmare with these scripts, need improvements from templates to pulling more channel data.

**Comment by dariomws306** [comment]
Hi @schittli and @justjeff2018, thank you for feedback.

As you wrote above User Voice is the place to request new features or improvements. My apologies but docs feedback is to fix/updates documentation.

**Comment by yogkumgit** [comment]
@schittli  Thank you very much for your kind feedback. Considering your valuable feedback, we request you to create an issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
Uservoice link - https://microsoftteams.uservoice.com/.

**Comment by yogkumgit** [comment]
@officedocsbot close
