### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/office-docs-powershell#3211]
As such, the database is required to periodically synch its contents with the information stored in Active Directory.

synch = sync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7b18252-c184-3bf0-413f-495cdb45dd77
* Version Independent ID: 18f8f5df-f960-33d2-3cfa-1140f31a98eb
* Content: [Update-CsUserDatabase (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/update-csuserdatabase?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Update-CsUserDatabase.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Update-CsUserDatabase.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @jantoney, thank you for your contribution.

I am fixing this.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @jantoney Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
