### ISSUE TITLE
Apply-PnPTenantTemplate fails using app-only 

### ISSUE THREAD

**Issue by silmer** [MicrosoftDocs/office-docs-powershell#3212]
**What I expect:** To be able to apply a tenant template using an established connection in app-only context (or an appropriate error message telling me that I cannot).
The following line was run:
`Apply-PnPTenantTemplate -Path .\prov.pnp`

**This is the error I'm getting:**

> | Apply-PnPTenantTemplate : Object reference not set to an instance of an object.
> | At line:1 char:1
> | + Apply-PnPTenantTemplate -Path .\prov.pnp
> | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> |     + CategoryInfo          : NotSpecified: (:) [Apply-PnPTenantTemplate], NullReferenceException
> |     + FullyQualifiedErrorId : | System.NullReferenceException,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate

**Details from Get-PnPException:**
> Message          : Object reference not set to an instance of an object.
> Stacktrace       :    at SharePointPnP.PowerShell.Commands.Base.SPOnlineConnection.CloneContext(String url)
>                       at SharePointPnP.PowerShell.Commands.Base.PnPAdminCmdlet.BeginProcessing()
>                       at System.Management.Automation.Cmdlet.DoBeginProcessing()
>                       at System.Management.Automation.CommandProcessorBase.DoBegin()
> ScriptLineNumber : 1

**More information:**
I am able to successfully apply the template when connected with an admin user context. The error occurs when attempting to apply the template after (successfully) connecting with a clientid and certificate.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @silmer Thanks for your feedback, we really appreciate it.
I created a PR to add the required permission to run this cmdlet, you can find more information here
https://developer.microsoft.com/en-us/office/blogs/pnp-webcast-introduction-to-pnp-tenant-templates/

Thank you!

**Comment by yogkumgit** [comment]
@VesaJuvonen  please merge PR #2053 
( sent you an email request as well)

**Comment by yogkumgit** [comment]
@VesaJuvonen please merge  PR #2053

**Comment by yogkumgit** [comment]
Gentle reminder @VesaJuvonen please merge PR #2053

**Comment by get-itips** [comment]
Hello @silmer how are you? PR merging is beying delayed a little, it will be merged in the next days I think, but you can look at it as it is referenced here.
We will proceed closing this.
Thank you for your feedback that improved the documentation.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for reporting the issue in Sharepoint repository and linking here and also sharing this explanation. @silmer   Hope this comment is helpful for you. These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
