### ISSUE TITLE
Conditional Access parameters are missing

### ISSUE THREAD

**Issue by ilantz** [MicrosoftDocs/office-docs-powershell#3217]
The parameters mentioned on https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/Unmanaged-Device-Access-Policies-are-Generally-Available/ba-p/188805 are missing.

-ConditionalAccessPolicy -LimitedAccessFileType -AllowEditing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1c6b2b-5af6-acce-b7e8-bf784bb0973e
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @vesajuvonen
* Microsoft Alias: **vesaj**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ilantz thanks for your feedback.
Information was added in this commit https://github.com/MicrosoftDocs/office-docs-powershell/commit/aa450ea2cb787b2cd8a8f0d9d8d06b513b179c74#diff-af32071bc66e8b86dceb665fd96f8f5e 

It can take some time to reflect into the "live" version of the article. I will check why in this case it's taking longer and try to get back with news.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ilantz 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
