### ISSUE TITLE
Conditional Access parameters are missing 

### ISSUE THREAD

**Issue by ilantz** [MicrosoftDocs/office-docs-powershell#3219]
The parameters mentioned on https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/Unmanaged-Device-Access-Policies-are-Generally-Available/ba-p/188805 are missing.

-ConditionalAccessPolicy -LimitedAccessFileType -AllowEditing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428a5954-392c-f7ad-bac4-553adf74e08e
* Version Independent ID: 44fdecf2-1977-3171-9d04-02c0fefb16c9
* Content: [Set-SPOTenant (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Service: **sharepoint-powershell**
* GitHub Login: @vesajuvonen
* Microsoft Alias: **vesaj**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ilantz thanks for your feedback.
I created a PR that should correct the article so the missing information can appear. It can take some days to reflech into the live version.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ilantz 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
