### ISSUE TITLE
Is this page up-to-date?

### ISSUE THREAD

**Issue by ykuijs** [MicrosoftDocs/office-docs-powershell#3220]
Is this page up-to-date? I cannot find the Add-SPOSiteCollectionAppCatalog, Get-SPOSiteCollectionAppCatalogs and Remove-SPOSiteCollectionAppCatalog cmdlets for example, which were added in the November 2017 update of the SPO Management Shell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65bf2c0b-b0ec-2748-e47e-af66011efe30
* Version Independent ID: be3968f4-d766-0b45-384b-c51c47328a86
* Content: [SharePoint Online PowerShell](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/index?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by ykuijs** [comment]
Quick check between the cmdlets documented here and the cmdlets available in the module reveals that 51 cmdlets are not documented here. Probably a good idea to add these as well:

- Add-SPOSiteCollectionAppCatalog
- Add-SPOTenantCentralAssetRepositoryLibrary
- Approve-SPOTenantServicePrincipalPermissionGrant
- ConvertTo-SPOMigrationEncryptedPackage
- ConvertTo-SPOMigrationTargetedPackage
- Enable-SPOCommSite
- Export-SPOQueryLogs
- Export-SPOUserProfile
- Get-SPOBrowserIdleSignOut
- Get-SPOBuiltDesignPackageVisibility
- Get-SPOCrossGeoMoveReport
- Get-SPODataEncryptionPolicy
- Get-SPOGeoMoveCrossCompatibilityStatus
- Get-SPOHomeSite
- Get-SPOMultiGeoCompanyAllowedDataLocation
- Get-SPOMultiGeoExperience
- Get-SPOOrgNewsSite
- Get-SPOSiteCollectionAppCatalogs
- Get-SPOSiteDataEncryptionPolicy
- Get-SPOSiteRenameState
- Get-SPOStorageEntity
- Get-SPOTenantCentralAssetRepository
- Get-SPOUnifiedGroup
- Get-SPOUnifiedGroupMoveState
- Register-SPODataEncryptionPolicy
- Remove-SPOHomeSite
- Remove-SPOMultiGeoCompanyAllowedDataLocation
- Remove-SPOOrgNewsSite
- Remove-SPOSiteCollectionAppCatalog
- Remove-SPOSiteCollectionAppCatalogById
- Remove-SPOStorageEntity
- Remove-SPOTenantCentralAssetRepositoryLibrary
- Remove-SPOUserInfo
- Remove-SPOUserProfile
- Restore-SPODataEncryptionPolicy
- Set-SPOBrowserIdleSignOut
- Set-SPOBuiltDesignPackageVisibility
- Set-SPOHomeSite
- Set-SPOMultiGeoCompanyAllowedDataLocation
- Set-SPOMultiGeoExperience
- Set-SPOOrgAssetsLibrary
- Set-SPOOrgNewsSite
- Set-SPOSiteOffice365Group
- Set-SPOStorageEntity
- Set-SPOUnifiedGroup
- Set-SPOWebTheme
- Start-SPOSiteRename
- Start-SPOUnifiedGroupMove
- Stop-SPOSiteContentMove
- Update-SPODataEncryptionPolicy
- Update-UserType

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by justjeff2018** [comment]
Agree - these need to be kept more up to date in docs and ver.  More comms needed

**Comment by KCCross** [comment]
Bumping priority.

**Comment by kenwith** [comment]
@KCCross  ..  @trent-green owns SPO powershell.. can you help Trent?
