### ISSUE TITLE
FYI: This cmdlet removes the search results from target mailbox

### ISSUE THREAD

**Issue by ejacobsen-glofin** [MicrosoftDocs/office-docs-powershell#3221]
If you are using the "MailboxSearch" functions for moving mail between mailboxes, know that when you remove the mailbox search, the search results (i.e. the transferred mail) are deleted from the target mailbox as well. This basically renders the "MailboxSearch" functions useless for us unless we want to have tons of legacy searches left out there for eternity. Turned to this option because of the 10,000 mail item cap on the "Search-Mailbox" cmdlet, but now I'll have to look at other options. How is transferring mail between mailboxes not easier to do with Exchange Online? This is a pretty crucial piece of functionality for a mail server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c98e4ab-746f-fa70-3992-e6c02d745735
* Version Independent ID: 9cda7362-55a8-49ec-4bf3-6115435ae168
* Content: [Remove-MailboxSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/remove-mailboxsearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/Remove-MailboxSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/Remove-MailboxSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @ejacobsen-glofin, thank you for your feedback.

Did you try moving/coping the items outside the Search folder? I understand that there isn't another way to do it.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @ejacobsen-glofin Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by eljacobsen12** [comment]
Sorry for the late response. I did try copying the mail to another folder outside of the search folder, and the mail was still there after removing the mailbox search. We use this function for offboarding users and transferring their mail to another mailbox though, and adding the step to copy all of the mail to another folder is a massive pain.
