### ISSUE TITLE
Does not describe how to use a PnP Context 

### ISSUE THREAD

**Issue by alirobe** [MicrosoftDocs/office-docs-powershell#3226]
e.g. https://gist.github.com/BasantPandey/7a138044cfd4007d6ec1cc03b80a2d0c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0545cff2-9bfb-b9cb-218b-00242ed6f0fc
* Version Independent ID: c1f7a5e1-ab36-29ad-aa29-dbe72efa6b16
* Content: [Get-PnPContext (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpcontext?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPContext.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPContext.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @alirobe Thanks for your feedback!
I created a PR to improve the documentation adding another example.
Thank you

**Comment by yogkumgit** [comment]
@VesaJuvonen  please merge the PR #2048 
( sent you a request in the email as well)

**Comment by yogkumgit** [comment]
@VesaJuvonen Please merge PR #2048

**Comment by yogkumgit** [comment]
Gentle reminder @VesaJuvonen Please merge PR #2048

**Comment by get-itips** [comment]
Hello @alirobe  how are you? PR merging is beying delayed a little, it will be merged in the next days I think, but you can look at it as it is referenced here.
We will proceed closing this.
Thank you for your feedback that improved the documentation.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for reporting the issue in Sharepoint repository and linking here and also sharing this explanation. @alirobe  Hope this comment is helpful for you. These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
