### ISSUE TITLE
Missing info for MCDB required parameters.

### ISSUE THREAD

**Issue by MrSundh** [MicrosoftDocs/office-docs-powershell#3227]
As configuration of Meta Cache Database described in https://docs.microsoft.com/en-us/Exchange/high-availability/database-availability-groups/metacachedatabase-setup?view=exchserver-2019 use a function called "Validate-DagParameters" which check that the following parameters not are Null och 0:

- AutoDagDatabaseCopiesPerVolume
- AutoDagTotalNumberOfDatabases
- AutoDagDatabaseCopiesPerDatabase
- AutoDagTotalNumberOfServers

The command used to set these is Set-DatabaseAvailabilityGroup, documented in this document.
Problem is that all except AutoDagDatabaseCopiesPerVolume have the desription "This parameter is reserved for internal Microsoft use.".

Any plan to update the info so admins can know what the purpose and how to calculate the parameters correctly? 
Especially now when it is required for MCDB configuration. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acfaa415-876c-ed87-df08-50f0bcf52923
* Version Independent ID: 9a7c0518-d9b1-7558-97d6-8920b9221f0d
* Content: [Set-DatabaseAvailabilityGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/database-availability-groups/set-databaseavailabilitygroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/database-availability-groups/Set-DatabaseAvailabilityGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/database-availability-groups/Set-DatabaseAvailabilityGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@MrSundh, you are correct. However, this identical problem is already being tracked in another GitHub issue: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/789, so I'm closing this one as a duplicate.

Thanks for the feedback.
