### ISSUE TITLE
Module link is broken

### ISSUE THREAD

**Issue by silmer** [MicrosoftDocs/office-docs-powershell#3229]
The link to "sharepoint-pnp" leads to a "not found" page. This is the same for (as far as I can tell) all articles on PnP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726aca9d-6df0-6691-bc00-f913ebee663f
* Version Independent ID: 34f7d6c0-930b-c46a-f1e1-1b8719a38991
* Content: [Get-PnPConnection (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpconnection?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPConnection.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPConnection.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @silmer Thanks for your feedback.
I created a Pull Request to add the required module article, it should be live in a couple of days.
**Thank you!**

**Comment by get-itips** [comment]
Hello! Good news, the article has been created and does not give a 404 anymore.
We will close this issue. Thanks.

**Comment by VesaJuvonen** [comment]
Closing as fixed.

**Comment by 2ndcahl** [comment]
Thank you for the work!
