### ISSUE TITLE
EwsAllowOutlook

### ISSUE THREAD

**Issue by DavidOgborne** [MicrosoftDocs/office-docs-powershell#3230]
Changing EwsAllowOutlook to False breaks Free/Busy for all version of Outlook. I'm running the latest build of Outlook and this setting caused Free/Busy to fail. The documentation says that this is for 2007 but it affects all versions of Outlook. 

Will the EwsAllowMacOutlook also break all version of Outlook for Mac?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@DavidOgborne, I assume you are talking about [Set-OrganizationConfig](https://docs.microsoft.com/powershell/module/exchange/organization/set-organizationconfig)? Those same two parameters are also available in [Set-CasMailbox](https://docs.microsoft.com/powershell/module/exchange/client-access/set-casmailbox). OrganizationConfig = everyone and CasMailbox = individual users, but the behavior of the parameters is the same. Here are the descriptions from Set-CasMailbox:

> The EwsAllowMacOutlook parameter enables or disables access to the mailbox by Outlook for Mac clients that use Exchange Web Services (for example, Outlook for Mac 2011 or later).

> The EwsAllowOutlook parameter enables or disables access to the mailbox by Outlook clients that use Exchange Web Services. Outlook uses Exchange Web Services for free/busy, out-of-office settings, and calendar sharing.

I replaced the old descriptions with these descriptions.

Thanks for the feedback
