### ISSUE TITLE
Example is empty

### ISSUE THREAD

**Issue by rajeshkhanikar** [MicrosoftDocs/office-docs-powershell#3232]
It says "{{ Add example code here }}", but I think there should be some example PowerShell codes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd34e9be-829e-d048-a3b0-6fde0f184286
* Version Independent ID: 94d85a29-36cf-1159-d5bc-6c5bd6ad4be3
* Content: [Set-SPSiteSubscriptionProfileConfig (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spsitesubscriptionprofileconfig?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPSiteSubscriptionProfileConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPSiteSubscriptionProfileConfig.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @rajeshkhanikar 
Thanks for your feedback.
I created a PR to add an example to the documentation.
Thank you!

**Comment by yogkumgit** [comment]
@Techwriter40  Please merge PR #3336

**Comment by yogkumgit** [comment]
Gentle reminder @Techwriter40 Please merge PR #3336

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @rajeshkhanikar Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
