### ISSUE TITLE
Get-Team needs more information

### ISSUE THREAD

**Issue by rpstester** [MicrosoftDocs/office-docs-powershell#3235]
Not sure if this is the right place, but I wanted to say that _Get-Team_ (PowerShell for Microsoft Teams) needs more output information.  With _Set-Team_, you can set the Alias, Classification, and Visibility, so with _Get-Team_, you should be able to read those values.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @rpstester, thank you for your feedback.

Now in the latest version (1.0) you are getting all this information:

PS C:\windows\system32> Get-Team -GroupId 7574734d-eca0-4736-9fec-1672b4b0b863 | fl


GroupId                           : 7574734d-eca0-4736-9fec-1672b4b0b863
DisplayName                       : Contoso IT
Description                       : Welcome to the IT team.
Visibility                        : Public
MailNickName                      : ContosoIT
Classification                    :
Archived                          : False
AllowGiphy                        : True
GiphyContentRating                : moderate
AllowStickersAndMemes             : True
AllowCustomMemes                  : True
AllowGuestCreateUpdateChannels    : False
AllowGuestDeleteChannels          : False
AllowCreateUpdateChannels         : True
AllowDeleteChannels               : True
AllowAddRemoveApps                : True
AllowCreateUpdateRemoveTabs       : True
AllowCreateUpdateRemoveConnectors : True
AllowUserEditMessages             : True
AllowUserDeleteMessages           : True
AllowOwnerDeleteMessages          : True
AllowTeamMentions                 : True
AllowChannelMentions              : True

If you think it's not enough and you want to suggest to improve it, please go to https://microsoftteams.uservoice.com/.

**Comment by yogkumgit** [comment]
@rpstester  Thank you very much for your kind feedback. As suggested, please log this issue to user voice.  Concerning team will evaluate and take the appropriate action, as per their schedule.  This channel is dedicated to improve the existing documentation. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
