### ISSUE TITLE
What is Classification

### ISSUE THREAD

**Issue by rpstester** [MicrosoftDocs/office-docs-powershell#3236]
What is a team classification? I'm not sure what to put on this parameter (although I can leave it blank), and I can't find a way to read the value from existing teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd6bccff-1bef-c88c-ff70-2ccdfb48ecc0
* Version Independent ID: 01f33478-352d-c7ae-0c49-784fa1c1fd67
* Content: [Set-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/set-team?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Set-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @rpstester Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
