### ISSUE TITLE
Please Add Whatif/Confirm to the PowerShell cmdlets for Teams

### ISSUE THREAD

**Issue by rpstester** [MicrosoftDocs/office-docs-powershell#3237]
I'm not sure if this is the correct place.  Please add Whatif/Confirm/ShouldProcess support for all the Remove- PowerShell cmdlets for Microsoft Teams module.  e.g. _Remove-TeamChannel_ should always ask "Are you sure", and should have a -WhatIf mode telling you what it would do. 
Thank you.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @rpstester 
Thanks for your feedback, actually, that is something you should suggest here https://microsoftteams.uservoice.com/forums/555103-public on Teams UserVoice, as this issue resource is specifically to address issues in current documentation.
Thank you

**Comment by yogkumgit** [comment]
@rpstester  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
