### ISSUE TITLE
Format parameter doesn't appear to match Exchange Online Options

### ISSUE THREAD

**Issue by ld0614** [MicrosoftDocs/office-docs-powershell#3238]
When running the command 
```
New-ComplianceSearchAction -SearchName $searchName -ErrorAction Stop -Export -Format BodyText
```
I get the error message: Unable to execute the task. Reason: 'BodyText' is not a valid value for parameter Format.

Does BodyText still exist as an option?

I also noticed when running the command 
```
New-ComplianceSearchAction -SearchName $searchName -ErrorAction Stop -Export -Format Message
```
I got the Error:
Cannot process argument transformation on parameter 'Format'. Cannot convert value "Message" to type 
"Microsoft.Exchange.Compliance.TaskDistributionCommon.ObjectModel.ComplianceDataTransferFormat". Error: "Unable to match the identifier name Message to a valid enumerator name. 
Specify one of the following enumerator names and try again:
Unknown, FxStream, Mime, Msg, BodyText"
At C:\Users\leo.darcy\AppData\Local\Temp\tmp_ml5wgqm0.apb\tmp_ml5wgqm0.apb.psm1:9458 char:9
+         $steppablePipeline.End()
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-ComplianceSearchAction], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-ComplianceSearchAction
    + PSComputerName        : gbr01b.ps.compliance.protection.outlook.com

Running
```
New-ComplianceSearchAction -SearchName $searchName -ErrorAction Stop -Export -Format Msg
```
Does work which suggests that the documentation just needs updating as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e154eb-3e1c-b4a5-418e-5be55b581255
* Version Independent ID: 00b93f90-663f-c277-c7de-09c184b4a322
* Content: [New-ComplianceSearchAction (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-compliancesearchaction?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ld0614, confirmed. I changed the value 'Message' to 'Msg' and I removed the BodyText value.

Thanks for the feedback.
