### ISSUE TITLE
Inconsistent Record counts

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/office-docs-powershell#3243]
When using the Get-DLPDetailReport cmdlet with the StartDate and EndDate parameters, I receive an inconsistent volume of returned data. For example, I am looking at the count for two separate time periods:

&gt; Get-DLPDetailReport -StartDate "3/18/2019 12:00 AM"  -EndDate "03/19/2019 12:00 AM" -pagesize 5000 | measure
Count    : 136

&gt; Get-DLPDetailReport -StartDate "3/19/2019 12:00 AM"  -EndDate "03/20/2019 12:00 AM" -pagesize 5000 | measure
Count    : 4448

Based on the above, if I search for data covering both time periods in the same query, I should get back 4,584 results. However, I don't get back that many results:

&gt; Get-DLPDetailReport -StartDate "3/18/2019 12:00 AM"  -EndDate "03/20/2019 12:00 AM" -pagesize 5000 | measure
Count    : 4448

Is there something I'm doing wrong or this is unexpected behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f04d48-7267-e9e4-0b1c-efb99d571286
* Version Independent ID: 21a2271e-b300-cf93-481b-88feed613563
* Content: [Get-DlpDetailReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/get-dlpdetailreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpDetailReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpDetailReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @terrogin, thank you for your feedback.

It looks like you are running the commands in the right way so I should kindly suggest that you open a support ticket to report this issue/bug.

**Comment by yogkumgit** [comment]
@terrogin Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
