### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by vaderj** [MicrosoftDocs/office-docs-powershell#3245]
does not exist:

https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/index?view=sharepoint-ps 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5691fbb3-502b-9a33-97a0-92410a3ea924
* Version Independent ID: 6b24c981-ebf7-cdef-877d-0984be7734dc
* Content: [| Microsoft Docs](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/sharepoint-online-cmdlets?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/sharepoint-online-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/sharepoint-online-cmdlets.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
I just clicked it; it's a valid link.

**Comment by vaderj** [comment]
I was running into a bunch of broken links that day, but it's working for me now as well. Thanks!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @vaderj 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
