### ISSUE TITLE
New-ComplianceTag -FilePlanProperty Bug when using ReferenceId attribute

### ISSUE THREAD

**Issue by bongo-ho** [MicrosoftDocs/office-docs-powershell#3251]
Adding metadata to FilePlanProperties on a ComplianceTag via UI in ComplianceCentre for ReferenceId -  ![image](https://user-images.githubusercontent.com/49170074/56397549-62951800-6298-11e9-8fce-b1f71ce92a6f.png)

...will block the user adding duplicates:
![image](https://user-images.githubusercontent.com/49170074/56397573-7ccef600-6298-11e9-923c-68931782c616.png)

The ComplianceCentre FilePlan UI guides you to create an unique ReferenceId per item, although no constraints on format (its a string). Using number-referencing convention here is expected, and is typical across various platforms, so not unexpected.

I create a new ComplianceTag via powershell and the command errors if you DONT use an existing ReferenceId when creating a new label, or when update using "Set-"

1. Existing ReferenceIds on UI created items
![image](https://user-images.githubusercontent.com/49170074/56397638-d1727100-6298-11e9-8e9d-802dde509cea.png)

2. JSON generated using the approach from documentation: 
![image](https://user-images.githubusercontent.com/49170074/56397658-e3541400-6298-11e9-8e5b-b156cc691a26.png)

3. Error generated by PowerShell trying to create a new items, with *new* ReferenceId
![image](https://user-images.githubusercontent.com/49170074/56397682-fbc42e80-6298-11e9-9b5d-42488da02b37.png)

..re-run the PowerShell command using existing ReferenceId e.g. 20/1.0, and creates item - with duplicate referenceid. which is now visible in the UI

![image](https://user-images.githubusercontent.com/49170074/56397749-7d1bc100-6299-11e9-92f9-d1cdb03f2039.png)

I have tried multiple variations

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hello, thanks for your feedback.

I think your question is more suitable for support resources like:
 https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10

docs.microsoft.com feedback is to help in documentation issues, not product issues.

Hope this information helps you.

**Comment by yogkumgit** [comment]
@bongo-ho Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. 

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
