### ISSUE TITLE
Ability to pull Channel Email address via powershell to allow tenant-wide posting.

### ISSUE THREAD

**Issue by justjeff2018** [MicrosoftDocs/office-docs-powershell#3252]
Need ability to pull a team site channel(s) email address to allow direct posting to each Team site (or all) for status updates / communication.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @justjeff2018, thank you for your feedback.

You cannot get the Team email address using Get-Team. You should use Get-UnifiedGroup. Each Team is associated to an Office 365 Group and the associated SharePoint document library, and each channel is a folder under the document library, so channels doesn't have email addresses.

To request this on Get-Team please go to https://microsoftteams.uservoice.com/.

**Comment by yogkumgit** [comment]
@justjeff2018  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
