### ISSUE TITLE
Help wanted: Who owns staffhub PS Move cmdlets?

### ISSUE THREAD

**Issue by juliogiraldo** [MicrosoftDocs/office-docs-powershell#3256]
I'm interested on try the Move-StaffhubXXXX cmdlets or debug it. 

Thanks,

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @juliogiraldo, thank you for your feedback.

StaffHub will be retired soon:
https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts/microsoft-staffhub-to-be-retired

So you should use Teams. Hope this information is useful for you.

**Comment by juliogiraldo** [comment]
Thanks @dariomws306, for that reason I need an update version of Powershell module, the cmdlet to move is not on git repository. (https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts/move-staffhub-teams-to-shifts-in-teams)

**Comment by dariomws306** [comment]
You're welcome.

Ok I understand what you need. Move-StaffHubTeam is not available yet but should be very soon. I will try to get more information.

**Comment by dariomws306** [comment]
It should be available in some days:

"The capability discussed in this article hasn't yet been released. It's been announced, and is coming soon, towards the middle of May 2019. If you're an admin, you can find out when this will be available in the Message Center (in the Microsoft 365 admin center)."

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @juliogiraldo 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by juliogiraldo** [comment]
@dariomws306 thank you for the info!! I'll wait impatient to it.

**Comment by dariomws306** [comment]
You're welcome!

**Comment by yogkumgit** [comment]
@officedocsbot close
