### ISSUE TITLE
Get-FilePlanPropertyCategory -Identity fails to retrieve default Categories

### ISSUE THREAD

**Issue by bongo-ho** [MicrosoftDocs/office-docs-powershell#3257]
Use Get-FilePlanPropertyCategory to list all items and can see both default and my categories:

![image](https://user-images.githubusercontent.com/49170074/56476676-07f5f900-64f0-11e9-8864-b03687ac2bb2.png)

Try to retrieve specific data on the system default category e.g. Payroll and get error
![image](https://user-images.githubusercontent.com/49170074/56476682-1e9c5000-64f0-11e9-8b2d-b35057155481.png)

when run command to retrieve information on a category I've just created it works:
![image](https://user-images.githubusercontent.com/49170074/56476717-99fe0180-64f0-11e9-98a5-624e0a6b2f72.png)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@bongo-ho, confirmed, so you should probably open a support ticket.

Strangely, for the built-in category named Payroll in my tenant, the Id, Identity, and DistinguishedName values look nothing like your Monkies custom category where the command works:

![image](https://user-images.githubusercontent.com/33166947/56679382-cbee9f80-6679-11e9-908b-e0a3ed1e976b.png)

I tried those values for Identity, and got the same error.

Report back here when you get an answer.
