### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by mbakerae** [MicrosoftDocs/office-docs-powershell#3264]
This add-in does not seem to support the Mac version of pshell; is there an alternate method for Mac?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@mbakerae, that's correct. Only Windows as described in the [What do you need to know before you begin?](https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps#what-do-you-need-to-know-before-you-begin) section.

**Comment by freshwreckage** [comment]
Your best bet is to use Remote Desktop, and do the work on another machine/VM. That's how I have to do it as a Mac User. It's kind of a pain, but not so bad. Also... given MS's penchant for moving the goal post and as often omitting requisite info from their help docs, I would not think that your query should elicit an unhelpful, snarky and passive aggressive comment though. But... that's just my humble opinion; I could be wrong.

**Comment by chrisda** [comment]
@freshwreckage, my intent wasn't to be unhelpful, snarky, or passive aggressive. I apologize if my response came across that way.

Where I fell down was answering the second part of (what I know realize was) a two-part question: what's the workaround? Thankfully, you stepped in and provided the answer.

Our intent isn't to omit perquisites from help docs. I've updated that topic as proactively as possible over the years as new operating systems and versions of the WMF appear. It's always a juggling act keeping the PowerShell connection instructions up-to-date and synchronized between Exchange Server, Exchange Online (regular and MFA), Exchange Online Protection, Security & Compliance Center (regular and MFA), and even the DAP Exchange Online instructions over [here](https://docs.microsoft.com/office365/enterprise/powershell/connect-to-exchange-online-tenants-with-remote-windows-powershell-for-delegated).

Having the topics on docs/GitHub is immensely helpful in that regard, as customers raise issues that force attention to the subject.

In that vein, do you think merely not mentioning PowerShell for Mac/Linux in the prerequisites is enough? Or should we explicitly call out that PowerShell for Mac/Linux isn't supported, and then mention Remote Desktop as the workaround?

**Comment by mbakerae** [comment]
@chrisda, My preference would be to have it called out specifically that Mac/Linux is not supported, and ideally information on whether or not the feature is on the roadmap for future inclusion in other environments.

**Comment by chrisda** [comment]
@mbakerae I added a note to the ExO MFA topic and the SCC MFA topic. I have no nsight into roadmaps or plans for the future about this.

Thanks for the feedback.
