### ISSUE TITLE
Does not work with other date formats than en-US

### ISSUE THREAD

**Issue by edbrlt** [MicrosoftDocs/office-docs-powershell#3280]
This command does not work, if you dont have a computer that is set up with EN-US date format setting. A serious problem, when working with powershell scripts on computers with different setting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2981d45e-739b-d932-163b-26569622b65c
* Version Independent ID: f5d9d7dd-3eb5-8d47-171d-84c550ef42d2
* Content: [Get-CalendarDiagnosticObjects (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-calendardiagnosticobjects?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-CalendarDiagnosticObjects.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-CalendarDiagnosticObjects.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @edbrlt, thank you for your feedback.

It's true, seems to be a bug.

**Comment by dariomws306** [comment]
Hello, thanks for your feedback.

I think your question is more suitable for support resources like:
https://support.microsoft.com/

docs.microsoft.com feedback is to help in documentation issues, not product issues.

Hope this information helps you.

**Comment by yogkumgit** [comment]
@edbrlt Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. 

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
