### ISSUE TITLE
Add entries for GCC High and DoD

### ISSUE THREAD

**Issue by kerbos** [MicrosoftDocs/office-docs-powershell#3281]
Please add lines to the table for GCC High and DoD like the below in section 'Connect to Exchange Online PowerShell by using MFA':

Office 365 offering ConnectionUri parameter value AzureADAuthorizationEndPointUri parameter value

Office 365 Not used Not used

Office 365 Germany https://outlook.office.de/PowerShell-LiveID https://login.microsoftonline.de/common

Office 365 GCC High https://outlook.office365.us/powershell-liveid https://login.microsoftonline.us/common

Office 365 DoD https://webmail.apps.mil/powershell-liveid https://login.microsoftonline.us/common

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps&viewFallbackFrom=exchange-ps%5D#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@kerbos, OK. Done. Thanks for the feedback.
