### ISSUE TITLE
Forcedeletion switch does not appear to be available anymore with remove-dlpcompliancepolicy

### ISSUE THREAD

**Issue by joefunk** [MicrosoftDocs/office-docs-powershell#3283]
The 'Forcedeletion' switch does not appear to be available anymore with remove-dlpcompliancepolicy command.  This is useful in cases where the DLP policy is hung in a pending deletion state for extended periods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b41d5a-c85c-e5d9-90c8-90c1277a223f
* Version Independent ID: 8baa76bc-2f5b-fb0c-ba2b-2d8b5d491763
* Content: [Remove-DlpPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/remove-dlppolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Remove-DlpPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Remove-DlpPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by jegilber** [comment]
Why is this close?
