### ISSUE TITLE
The 'Forcedeletion' switch does not appear to be available anymore

### ISSUE THREAD

**Issue by joefunk** [MicrosoftDocs/office-docs-powershell#3284]
The 'Forcedeletion' switch does not appear to be available anymore with remove-dlpcompliancepolicy command. This is useful in cases where the DLP policy is hung in a pending deletion state for extended periods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a78aa0ce-c818-1e95-2e37-8725c7b3cc90
* Version Independent ID: 3e14521e-ef75-4328-e753-31e7b59fd481
* Content: [Remove-DlpCompliancePolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/remove-dlpcompliancepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Remove-DlpCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Remove-DlpCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @joefunk, thank you for your feedback.

It's true, this parameter was removed. You can use User Voice to request that product group returnt it to this cmdlet.

**Comment by yogkumgit** [comment]
@joefunk  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback. Here is the link
https://microsoftteams.uservoice.com/

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by yogkumgit** [comment]
@officedocsbot reopen

**Comment by yogkumgit** [comment]
@chrisda Please merge PR #3353

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @joefunk Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
