### ISSUE TITLE
Update comments for SFBOnly and SFBOnly with notify in the TeamsUpgradePolicy table 

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/office-docs-powershell#3286]
The comments for TeamsUpgradePolicy SFBOnly and SFBOnlyWithNotify say that they currently just set a preferred client, and will restrict teams functionality in the future.  This is no longer the case.  As per the "Important" note a little further down the page: 
"IMPORTANT When users are in any of the Skype for Business modes (SfBOnly, SfBWithTeamsCollab, SfBWithTeamsCollabAndMeetings), calling and chat functionality in the Teams app are disabled. Similarly, when users are in the SfBOnly or SfBWithTeamsCollab modes, meeting scheduling is disabled."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0dd44c-bfc9-5f82-68c4-7b469129e8a5
* Version Independent ID: ea015ee3-54e2-e402-d533-c8a9a15557e8
* Content: [Grant-CsTeamsUpgradePolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsupgradepolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @NeighborGeek Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
