### ISSUE TITLE
 Get-SPOTenantLogEntry Command not working.

### ISSUE THREAD

**Issue by MaxKraft** [MicrosoftDocs/office-docs-powershell#3294]
Get-SPOTenantLogEntry is not available for us. is there any plan to make it available for everyone? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09da7b62-1030-7e2e-03c3-388925add9c9
* Version Independent ID: 83480c70-9a33-06a8-d9a8-a4189ad7af5d
* Content: [Get-SPOTenantLogEntry (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantlogentry?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantLogEntry.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantLogEntry.md)
* Service: **sharepoint-powershell**
* GitHub Login: @vesajuvonen
* Microsoft Alias: **vesaj**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by deafwing** [comment]
agreed ... this does nothing me as well ... even running the command alone without params returns squat

**Comment by ravick4u** [comment]
Not working for me as well. No error/No output.

**Comment by Excuse-me-sir** [comment]
According to MS, this will not be allowed.
https://sharepoint.uservoice.com/forums/330318-sharepoint-administration/suggestions/11485845-get-in-sharepoint-online-the-uls-entries-for-your

**Comment by chandreshgit** [comment]
It will not work, SharePoint Engineer has removed this since 2015. 

You can send the support desk a copy of the correlation ID, it takes a week or two on average from what my sys admins have told me (They put in all our requests). You will either get the log lines, a translation of what happened or be told it is internal.

**Comment by get-itips** [comment]
Hello everyone,
Thanks for your feedback.
I can confirm that the cmdlet is of internal use.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @MaxKraft 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
