### ISSUE TITLE
New-ComplianceSearchAction does not see "ActionName" parameter.

### ISSUE THREAD

**Issue by zaicnupagadi** [MicrosoftDocs/office-docs-powershell#3295]
New-ComplianceSearchAction does not look on the mentioned parameter when creating the action - it creates name relying on the search itself.

**Comment by zaicnupagadi** [comment]
This means as well that I ma not able to create few searches, let's say I got 33 emails in each mailbox and I would like to purge them, I need to run mentioned command 4 times - but cannot run this simultaneously - with different names. It does not allow me to create another search action - I need to wait between each and every search action creation :/

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by markjjo** [comment]
@zaicnupagadi Seems there are a couple of issues here. The ActionName parameter is used to support bulk actions on searches that are associated with eDiscovery cases in the Security & Compliance Center, and I don't think is applicable to your issue. I would recommend that you used the Search-Mailbox -DeleteContent cmdlet in Exchange Online. You can delete 10K items but you can only run it against a single target mailbox. But you can re-run the same command and just change the target mailbox. See https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/Search-Mailbox?view=exchange-ps and https://docs.microsoft.com/en-us/office365/securitycompliance/search-for-and-delete-messagesadmin-help
