### ISSUE TITLE
This page should call out why we should use the UPN instead of domain\name format

### ISSUE THREAD

**Issue by 1RedOne** [MicrosoftDocs/office-docs-powershell#3298]
https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/connect-to-exchange-servers-using-remote-powershell?view=exchange-ps#connect-to-a-remote-exchange-server

In this page it says to use UPN format when providing a credential, which is uncommon.  It shoudl explain why we need to do this.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@1RedOne, my guess is it has something to do with Kerberos authentication, but that's just a guess. Also unusual is requiring http, not https in the second step, which is also called out, but not explained.

I'm not sure I agree that the 'why' is terribly important; it just adds more text to the topic. The fact that it is called out that you must use the UPN value is what's important. But, I'm open to comment/criticism on this point.

**Comment by dariomws306** [comment]
Thank you for your reply @chrisda!

**Comment by yogkumgit** [comment]
@chrisda  and @dariomws306  Thank you very much for the contribution and sharing this explanation. @1RedOne Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
