### ISSUE TITLE
-DisableExportedNodes does not work

### ISSUE THREAD

**Issue by rimroot** [MicrosoftDocs/office-docs-powershell#3300]
-DisableExportedNodes does not disable any rooms.

ComponentName                                                         Version     
-------------                                                         -------     
Skype for Business Server 2015, Core Components                       6.0.9319.537
Skype for Business Server 2015, Performance Counter Cumulative Update 6.0.9319.259
Skype for Business Server 2015, Persistent Chat                       6.0.9319.534

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 048c1b74-0188-9319-017d-d2b49837f245
* Version Independent ID: 53f9623a-2901-3fac-9cce-aa96f88062b6
* Content: [Export-CsPersistentChatData (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/export-cspersistentchatdata?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Export-CsPersistentChatData.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Export-CsPersistentChatData.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hello, thanks for your feedback.

I think your question is more suitable for support resources like:
https://support.microsoft.com/

docs.microsoft.com feedback is to help in documentation issues, not product issues.

Hope this information helps you.

**Comment by yogkumgit** [comment]
@rimroot Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. 

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
