### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by Nateb1121** [MicrosoftDocs/office-docs-powershell#3301]
"Use the Update-GlobalAddressList cmdlet to update the recipients included ina global address list (GAL)." should be "Use the Update-GlobalAddressList cmdlet to update the recipients included in a global address list (GAL)." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0a2a405-3983-b3e4-0926-db4bf2b8c426
* Version Independent ID: ececdd71-0c10-cfe0-74ce-923a3344d51a
* Content: [Update-GlobalAddressList (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/email-addresses-and-address-books/update-globaladdresslist?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/email-addresses-and-address-books/Update-GlobalAddressList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/email-addresses-and-address-books/Update-GlobalAddressList.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Nateb1121 , I fixed it. But in the future, you can, too. See https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md
