### ISSUE TITLE
Example #3

### ISSUE THREAD

**Issue by esammann** [MicrosoftDocs/office-docs-powershell#3303]
Example #3 on this page has an uppercase W in the claims portion of the user, second line of the PS command.  This was throwing an error for me in PowerShell.  I changed it to a lowercase w and it worked okay.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb0c56a-83cb-5238-3b8c-28f67adb679e
* Version Independent ID: ca5d028b-7fcd-7ace-6710-77982a682853
* Content: [Move-SPUser (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/Move-SPUser?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Move-SPUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Move-SPUser.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@officedocsbot assign @tseward

**Comment by tseward** [comment]
@AndreaBarr assign to me, please. Bot doesn't seem to work for me :)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit
