### ISSUE TITLE
Incomplete information

### ISSUE THREAD

**Issue by thomascwiley** [MicrosoftDocs/office-docs-powershell#3304]
This document appears to be incomplete.  e.g. {{ Add example code here }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fab4e86c-f8f6-36fa-874c-756e5a88f0ae
* Version Independent ID: 307f2569-889a-b887-9536-d91d26fe184e
* Content: [Get-CsOnlineDialOutPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialoutpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialOutPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDialOutPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith please merge PR #3347

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @thomascwiley Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
