### ISSUE TITLE
Example 2 (alternate locale) doesn't work in Exchange Online

### ISSUE THREAD

**Issue by Cutriss** [MicrosoftDocs/office-docs-powershell#3305]
The above Example 2 doesn't work in Exchange Online. It generates the following error:

WARNING: An unexpected error has occurred and a Watson dump is being generated: Argument objectId is null
Parameter name: objectId
Argument objectId is null
Parameter name: objectId
    + CategoryInfo          : NotSpecified: (:) [New-MessageClassification], ArgumentNullException
    + FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.Exchange.Management.SecureMail.NewMessageClassification
    + PSComputerName        : outlook.office365.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8edfe1-3c01-2130-eb99-483e29c61f0b
* Version Independent ID: 800241fb-2ab8-f0a3-7637-0addec012040
* Content: [New-MessageClassification (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/new-messageclassification?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance/New-MessageClassification.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance/New-MessageClassification.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Cutriss, confirmed. I changed the text of the example to say it was for on-premises Exchange, and I changed the parameter description for Locale to say that it only works in on-premises Exchange.

Thanks for the feedback.

**Comment by Weishaupt** [comment]
@chrisda Locale is still a visible parameter in the Exchange Online PowerShell. What is the plan here? I'd love to see locale support for this feature.
