### ISSUE TITLE
How to read output file from Get-CalendarDiagnosticObjects?

### ISSUE THREAD

**Issue by skyydogg01** [MicrosoftDocs/office-docs-powershell#3306]
What does it all mean?  I need to know what the numbers in ResponseType, AppointmentState, and MeetingRequestType.  I can figure out the rest but those are coded and I have not found anywhere that explains the results.  Thanks.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @skyydogg01, thank you for your feedback.

@chrisda, coud you help with this? Could we get more information about Get-CalendarDiagnosticObjects output? Thanks!

**Comment by yogkumgit** [comment]
@chrisda kindly reply to Dario

**Comment by chrisda** [comment]
@skyydogg01, OK Fixed.

**Comment by dariomws306** [comment]
Thanks!

**Comment by skyydogg01** [comment]
Thank you!

**Comment by skyydogg01** [comment]
I'm sorry.  I didn't mean to reopen ticket.
