### ISSUE TITLE
Set-TeamPicture not present in version 1.0

### ISSUE THREAD

**Issue by mrik23** [MicrosoftDocs/office-docs-powershell#3312]
The cmdlet Set-TeamPicture seems gone from version 1.0. You should update this page, but it would be good to know why it has been removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb0ae61a-ece2-5d6a-7676-c1b33b12c246
* Version Independent ID: 5629326e-995c-4494-811f-80a0bb042233
* Content: [Set-TeamPicture (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/set-teampicture?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-TeamPicture.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-TeamPicture.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @mrik23, thank you for your feedback.

We should leave this article there because it's not available now in 1.0 but it's planned:
https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-overview#differences-between-preview-and-generally-available-microsoft-teams-powershell-module

**Comment by mrik23** [comment]
@dariomws306 OK so maybe add something on that page to indicated it's not yet available in GA version 1.0. 

Also will there be a preview module available? It seems to be what's indicated your link, but I don't find any.

**Comment by dariomws306** [comment]
@mrik23, in the article I sent you please check the table. The last cmdlet is Set-TeamPicture and in the last column (Available in 1.0) you can see "No, planned".

Thanks.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @mrik23 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
