### ISSUE TITLE
$_.Identity cause a failure on large accounts with users that have the same name

### ISSUE THREAD

**Issue by mwilliams7247** [MicrosoftDocs/office-docs-powershell#3313]
I had to modify the command as follows, using the Alias to ensure unique names

$mbx = Get-Mailbox -RecipientTypeDetails UserMailbox -ResultSize Unlimited
$mbx | foreach {Get-TextMessagingAccount -Identity $_.Alias | where {($_.NotificationPhoneNumberVerified -eq $true)} | Format-Table Identity,NotificationPhoneNumber}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786aa766-5ad7-082f-53bb-0b953224f412
* Version Independent ID: 2cdcbfda-01b4-2859-14d2-268cd9cb51bd
* Content: [Get-TextMessagingAccount (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/get-textmessagingaccount?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/client-access/Get-TextMessagingAccount.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Get-TextMessagingAccount.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mwilliams7247 this issue was fixed in PR #3299, although the person used $.Identity instead of $.Alias. Both values require uniqueness. Did you find $.Identity didn't work?

**Comment by mwilliams7247** [comment]
It crashes on both actually which is odd as alias is unique


________________________________

**Comment by chrisda** [comment]
@mwilliams7247, I changed the value from $.Identity to $.Alias.
