### ISSUE TITLE
Returns All Teams in version 1.0.0

### ISSUE THREAD

**Issue by tonerz82** [MicrosoftDocs/office-docs-powershell#3323]
This still not working with version 1.0.0. The command returns all Teams after specifying a user in the user parameter. I posted this issue on the community forum here:
https://techcommunity.microsoft.com/t5/Microsoft-Teams/Get-Team-User-PowerShell-for-Teams/m-p/501790#M30709

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
@tonerz82 Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:

https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
