### ISSUE TITLE
ErrorAction is not honored on Add-TeamUser 

### ISSUE THREAD

**Issue by EHLOBen** [MicrosoftDocs/office-docs-powershell#3326]
If you provide -ErrorAction SilentlyContinue on Add-TeamUser, and then specify something that results in an error (Adding an Owner who is already an Owner for example) the error is still outputted. this doesn't happen for other modules such as get-mailbox invalidentry -ea silentlycontinue

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by EHLOBen** [comment]
Might just be my session, requires more testing - apologies for any alarm!

**Comment by yogkumgit** [comment]
@EHLOBen  We always appreciate any feedback that improves the content in the Microsoft docs. No need to apologies.Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also. We are going to close this issue.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by MattAlex151** [comment]
I'm seeing this same behaviour. Assigning the output to a variable or even piping to Out-Null still blats out an error.
