### ISSUE TITLE
Users role

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#3327]
When then user parameter is used, does it return groups/teams in which the user is an Owner or Member?
I'd like to be able to get the Teams that are owned by someone, but not the ones in which they are only a member. Currently this require multiple modules and a somewhat complicated script. It would be helpful if we could just do a Get-Team -User upn -Role owner

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8450991f-9f85-4d87-51b3-efa8e1004a24
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @DeanGross, thank you for your feedback.

Considering the nature of the request, it is advised that please go to User Voice:
https://microsoftteams.uservoice.com

**Comment by yogkumgit** [comment]
@DeanGross  Thank you very much for your kind feedback. Considering your valuable feedback, we request you to log this issue as User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
