### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by eugmeister** [MicrosoftDocs/office-docs-powershell#3329]
Example 3 is incorrect it should be 

Get-PnPNavigationNode -Location TopNavigationBar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6633c99f-3565-84cf-f11a-cd055df5885e
* Version Independent ID: 40ba47f1-40f3-b4c4-cc93-fa29841595c2
* Content: [Get-PnPNavigationNode (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpnavigationnode?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPNavigationNode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPNavigationNode.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @eugmeister thanks for your feedback.
This has already been fixed https://github.com/SharePoint/PnP-PowerShell/commit/fbddf5134e7397ea029e007cf9db37fc9aade421 but the change still does not reflect on the live article.
Hopefully the change will appear in a couple of days.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for reporting the issue in Sharepoint repository and linking here and also sharing this explanation. @eugmeister  Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
