### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#3334]
I cannot find any type of change log describing changes to the powershell module. Does this exist? if so, please add it to these docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6172d49e-6905-e979-bddb-6822a01eafc7
* Version Independent ID: b04220e0-2087-d566-e357-1ac46cd2d7b8
* Content: [Skype for Business cmdlet reference](https://docs.microsoft.com/en-us/powershell/skype/intro?view=skype-ps)
* Content Source: [skype/docs-conceptual/intro.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/docs-conceptual/intro.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @DeanGross, thank you for your feedback.

There isn't a special place to see the updates on the module. You can get some information about new cmdlets and parameters on each Cumulative Update:
https://docs.microsoft.com/en-us/skypeforbusiness/sfb-server-updates#skype-for-business-server-2015-update-history

Also you can find documentation updates on Github:
https://github.com/microsoftdocs/office-docs-powershell

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @DeanGross 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by DeanGross** [comment]
Thanks, but that is disappointing, other modules do have this information, see https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#version-history. It would be nice the module documentation authors could do something similar for every module.

**Comment by dariomws306** [comment]
Hi @DeanGross, sorry but at the moment the best place to get this information is Cumulative Updates information and Github.

Thanks.

**Comment by yogkumgit** [comment]
@officedocsbot close
