### ISSUE TITLE
Outputs need detailing

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/office-docs-powershell#3338]
This document really needs some description around the Output values. I can advise on some of these (as they are sometimes confusing). Please reach out to me if necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5522e1-7041-205a-7a97-1622118d9d58
* Version Independent ID: 0e5702db-abe5-9172-cab6-676952313b66
* Content: [Get-UrlTrace (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/get-urltrace?view=exchange-ps#outputs)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Get-UrlTrace.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Get-UrlTrace.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @aldoug Thanks for your feedback.
I created a PR to improve the documentation of this cmdlet adding a link to more info about the Safe Links feature.
Thank you

**Comment by yogkumgit** [comment]
@chrisda please merge PR #3342

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @aldoug Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by aldoug** [comment]
Sorry, where I can I see the update?



Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 09:00 - 18:00
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by get-itips** [comment]
Hello @aldoug you can see the updated version of the article, it's live now, and includes a link to more information. @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @aldoug Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by aldoug** [comment]
There's still nothing listed under "Outputs"?

**Comment by get-itips** [comment]
Hello @aldoug 
The reason I chose to add a link with more detailed information to interpret the Safe Link reports in the Description section is because the output of this cmdlet is an array Object[] and that is not so useful to understand the results.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @aldoug We appreciate any feedback that improves the content in the Microsoft docs.

Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
