### ISSUE TITLE
operations parameter link does not have all operations

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/office-docs-powershell#3339]
The parameter description for -operations says to check https://go.microsoft.com/fwlink/p/?LinkId=708432 for operation IDs.  That list is incomplete.  It has no operations for power bi, for example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d47105-b32e-f0f8-3e71-db411c6abe7c
* Version Independent ID: 338beb1b-1f13-0a77-9ac3-1c4fe542b612
* Content: [Search-UnifiedAuditLog (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/search-unifiedauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by markjjo** [comment]
@jordanmills Here is the list of PowerBI activities that are logged: https://docs.microsoft.com/en-us/power-bi/service-admin-auditing#activities-audited-by-power-bi 

We will update the link that you cited to point to the section in the audit log topic where activities for each Office 365 service is discussed. https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance?redirectSourcePath=%252farticle%252f0d4d0f35-390b-4518-800e-0c7ec95e946c#audited-activities

**Comment by chrisda** [comment]
Fixed. Closing
