### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by marshalanson** [MicrosoftDocs/office-docs-powershell#3340]
Example 3 contains a typo.

Should be "New-MailboxRestoreRequest"

The "L" is missing from Mail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 514e13f3-66b0-e6ed-a914-4784823665d6
* Version Independent ID: 4028ab31-0d94-8136-bf5b-a49942417900
* Content: [New-MailboxRestoreRequest (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/new-mailboxrestorerequest?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/New-MailboxRestoreRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/New-MailboxRestoreRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@marshalanson, this was fixed per pull request #3346. In the future, you, too can make updates to topics. See https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md.

Closing.
