### ISSUE TITLE
Conflicting information for the -operations parameter

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/office-docs-powershell#3341]
There is a note that states that operations will accept multiple entries, but only works on one, but the example powershell provides 2 comma separated entries. The manage alerts GUI also allows selection of multiple operations- which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3169e419-58de-09fc-f449-fb1c96b52e27
* Version Independent ID: 86bc91e7-a5c8-779d-0b87-894f0d5ca174
* Content: [New-ActivityAlert (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/new-activityalert?view=exchange-ps#parameters)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance/New-ActivityAlert.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance/New-ActivityAlert.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@TheBluLion, I updated the example to use one value. Thanks for the feedback.
