### ISSUE TITLE
Inadequately documented UnblockUnsafeSenderPromptEnabled

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/office-docs-powershell#3350]
The following text does not explain anything about what this feature does. Search the web "unblock unsafe senders in Outlook" returns no results.

-UnblockUnsafeSenderPromptEnabled
The UnblockUnsafeSenderPromptEnabled parameter specifies whether to enable or disable the prompt to unblock unsafe senders in Outlook on the web. Valid values are:

$true: The prompt to unblock unsafe senders is enabled. This is the default value.

$false: The prompt to unblock unsafe senders is disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3ab3f0-cc05-e279-8876-6da0b323bcac
* Version Independent ID: bfb49814-d60b-564a-25cc-f902dfa42b10
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by kenwith** [comment]
Thank you for providing feedback and making the docs better @SwiftOnSecurity . :)  These are all open source now and getting better and better because of people that are active like you. We will get this worked on and improved. Much appreciated for taking the time!

**Comment by dariomws306** [comment]
@chrisda, do you think you can help me with this?

I couldn't find more information about UnblockUnsafeSenderPromptEnabled.

**Comment by yogkumgit** [comment]
@chrisda Please answer the query by @dariomws306

**Comment by dariomws306** [comment]
Hi @SwiftOnSecurity, thank you for your feedback.

This parameter is not used actually. I have added a new description.

Thanks!

**Comment by yogkumgit** [comment]
@dar Thank you very much for the contribution and updating the documentation with PR. @SwiftOnSecurity  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
