### ISSUE TITLE
Inadequately documented RefreshSessionEnabled

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/office-docs-powershell#3351]
This configuration option does not give adequate context or guidance on the correct setting or why it would be changed.
Because this has security ramifications this should be explained.

-RefreshSessionEnabled
The RefreshSessionEnabled parameter specifies whether to enable or disable the use of refresh tokens when using OpenID Connect for authentication. Valid values are:

$true: Refresh tokens are enabled.

$false: Refresh tokens are disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3ab3f0-cc05-e279-8876-6da0b323bcac
* Version Independent ID: bfb49814-d60b-564a-25cc-f902dfa42b10
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
@chrisda, do you think you can help me with this?

I couldn't find more information about RefreshSessionEnabled.

**Comment by chrisda** [comment]
@SwiftOnSecurity, it appears this parameter is no longer used. I've changed the description to "This parameter is reserved for internal Microsoft use."

Thanks for the feedback.
