### ISSUE TITLE
example 3 has syntax error 

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/office-docs-powershell#3355]
The SIPAccessService parameter must have port, it can't be just a FQDN, see below:

[PS] C:\windows\system32&gt;Get-UMService e2013.lab.com |Set-UMService -SIPAccessService sfbFEpool.lab.com
Cannot process argument transformation on parameter 'SIPAccessService'. Cannot convert value
"sfbFEpool.lab.com" to type "Microsoft.Exchange.Data.ProtocolConnectionSettings". Error: "The string
'sfbFEpool.lab.com' has an invalid format. The correct format is &lt;host name&gt;:&lt;port
number&gt;[:&lt;encryption type&gt;]."

Please change example 3 to the following (the addition of :5061 is required) 

Set-UMService -Identity MyUMServer -DialPlans MySIPDialPlan -MaxCallsAllowed 50 -SipAccessService northamerica.lyncpoolna.contoso.com:5061 -UMStartupMode TLS

In addition, please update the following section to clarify that it is Lync/SFB Front End pool, instead of Edge pool. Because in Exchange 2010, the SIPAccessService is supposed to be Lync Edge pool so IT admins may get confused.

-SIPAccessService

The SIPAccessService parameter specifies the FQDN and TCP port of the nearest Lync Server Front End pool or Skype for Business Server Front End pool location for inbound and outbound calls from remote Lync or Skype for Business users located outside of the network. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17eb8018-52ba-52cc-9872-f23a00ad5609
* Version Independent ID: 1f5618c6-5a4a-b9a7-67a9-4382280e2afd
* Content: [Set-UMService (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/unified-messaging/set-umservice?view=exchange-ps&viewFallbackFrom=exchserver-2016)
* Content Source: [exchange/exchange-ps/exchange/unified-messaging/Set-UMService.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/unified-messaging/Set-UMService.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@howardzhangmsft, OK. Updated as you described.

Thanks for the feedback.
