### ISSUE TITLE
Teams PowerShell Module 1.0 error InvalidAuthenticationToken

### ISSUE THREAD

**Issue by makorus** [MicrosoftDocs/office-docs-powershell#3356]
Hi everyone,
as of version 1.0, the Set-Team command results in an "InvalidAuthenticationToken" error sometimes.

This is the full error message:

> Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException: Error occurred while executing 
> Code: InvalidAuthenticationToken
> Message: Access token validation failure.
> InnerError:
>   RequestId: 0a078885-3643-4aa8-8ec0-e0832d20e7ff
>   DateTimeStamp: 2019-05-06T11:23:14
> HttpStatusCode: InvalidAuthenticationToken
> 
>    bei Microsoft.TeamsCmdlets.PowerShell.Custom.Utils.HttpUtilities.Patch[T](HttpClient httpClient, Uri requestUri, T content)
>    bei Microsoft.TeamsCmdlets.PowerShell.Custom.SetTeam.ProcessRecord()
>    bei System.Management.Automation.CommandProcessor.ProcessRecord()

Running the same command a few seconds later usually works, so this seems like a temporary issue. But this is quite annoying as we have somewhat 200 teams and use a PowerShell script to manage those. Our script fails since we installed the most recent version of this PowerShell module.

Any ideas how to fix this or is this a known issue?

**Comment by makorus** [comment]
Looks like this error also appears randomly using any other MSTeams PowerShell Cmdlet. Just had this error message after executing Get-Team:

> Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException: Error occurred while executing 
> Code: InvalidAuthenticationToken
> Message: Access token validation failure.
> InnerError:
>   RequestId: aa1d74a6-fc66-4a42-a242-93ce7b4565c1
>   DateTimeStamp: 2019-05-06T12:39:22
> HttpStatusCode: InvalidAuthenticationToken
> 
>    bei Microsoft.TeamsCmdlets.PowerShell.Custom.Utils.HttpUtilities.Get[T](HttpClient httpClient, Uri requestUri)
>    bei Microsoft.TeamsCmdlets.PowerShell.Custom.Utils.HttpUtilities.GetAll[T](HttpClient httpClient, Uri requestUri)
>    bei Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeam.ProcessRecord()
>    bei System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by makorus** [comment]
Any news on this?

**Comment by dariomws306** [comment]
@makorus Thank you very much for posting this issue. 

Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: 
https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. 
Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by makorus** [comment]
> @makorus Thank you very much for posting this issue.
> 
> Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:
> https://docs.microsoft.com/office365/admin/contact-support-for-business-products
> 
> We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information.
> Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

@dariomws306 thank you for your reply. I guess someone else reported this issue as well via service ticket. The error messages didn't pop up anymore, our script runs daily at 9PM. Yesterday it worked flawlessly, so I'll see if it stays like this. Thanks anyway!
