### ISSUE TITLE
Wrong parameter description

### ISSUE THREAD

**Issue by JensTrier** [MicrosoftDocs/office-docs-powershell#3357]
The text explaning AllowCallForwardingToPhone is wrong. This is not related to call park.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f1bf407-1ad6-77d9-4ef1-4bc821576912
* Version Independent ID: 4630697b-375e-85f2-25b1-b944bc6dad5f
* Content: [Set-CsTeamsCallingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith  Please merge PR #3394

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @JensTrier Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
