### ISSUE TITLE
Missing Parameters Documentations and Examples

### ISSUE THREAD

**Issue by MIBadran** [MicrosoftDocs/office-docs-powershell#3358]
[-SourceMeetingType <MmsSourceMeetingTypes>]
     [-TargetMeetingType <MmsTargetMeetingTypes>]

What those could be and what is the default?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @MIBadran Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
