### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by MIBadran** [MicrosoftDocs/office-docs-powershell#3359]
[-SourceMeetingType &lt;MmsSourceMeetingTypes&gt;]
     [-TargetMeetingType &lt;MmsTargetMeetingTypes&gt;]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83a8070-4efb-0b72-b518-3b00f58cc252
* Version Independent ID: 7a8f5cc1-e717-e142-b488-54713a288583
* Content: [Start-CsExMeetingMigration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/start-csexmeetingmigration?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Start-CsExMeetingMigration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Start-CsExMeetingMigration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @MIBadran Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
