### ISSUE TITLE
Hex Code for White is Wrong

### ISSUE THREAD

**Issue by mhendric** [MicrosoftDocs/office-docs-powershell#3361]
The hex code for white is 0xffffff, not 0x000000.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aabcc26e-242d-1342-24af-a419a129e91d
* Version Independent ID: 110aa234-6fb0-ff5c-fe5c-10b86147b9ce
* Content: [Set-OMEConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/set-omeconfiguration?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@mhendric, fixed. In the future, you can fix issues like this, too. See https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md.

Thanks for the feedback.
