### ISSUE TITLE
Is the existing layout impacted?

### ISSUE THREAD

**Issue by eximo84** [MicrosoftDocs/office-docs-powershell#3367]
We use modern pages on a classic site but would like to convert the root to a modern communication site to take advantage of the mega menu and new layout functionality.  Will our existing root site pages be impacted in anyway by running this command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 052c9917-ce90-f835-fa87-db8c0e492038
* Version Independent ID: 4c7ea433-77d3-22c9-9931-07ba83d0baca
* Content: [Enable-SPOCommSite](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Enable-SPOCommSite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @DC Padur
* Microsoft Alias: **dipadur**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by divyachapan** [comment]
Modern pages that had the left nav experience will now have the horizontal nav experience. The content of the pages will be centered. Other than that, no impact to existing pages.

**Comment by get-itips** [comment]
Hello @eximo84 thanks for your feedback.
As the author of the article has already replied, we will proceed closing this one.
Thank You!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @eximo84 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
