### ISSUE TITLE
classic pub feature warning -- more details please.

### ISSUE THREAD

**Issue by cdebbo** [MicrosoftDocs/office-docs-powershell#3369]
re: "should not have had the classic publishing feature"
Is this referring to the "SharePoint Server Publishing" site feature? What happens if this was enabled in the past? Is there anything users can do to 'fix' this so that modern comm. site an be enabled? Thx.

**Comment by lhuswe** [comment]
Most of the root-sites i manage have SharePoint Server Publishing activated, how can i convert these?

**Comment by tseward** [comment]
At the moment they cannot. If you've ever activated the Publishing feature, then it won't be possible to use Enable-SPOCommSite. @chrisda this should be labeled as an SPO cmdlet rather than SP Server.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @cdebbo 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
