### ISSUE TITLE
Setting Extension for Phone Number

### ISSUE THREAD

**Issue by angiurgiu** [MicrosoftDocs/office-docs-powershell#3373]
Hello! I've been struggling to set an extension on an onprem number using Set-CsUser -OnPremLineURI. The extension is reflected in onprem AD, but dirsync is blocked for the user as a consequence of the extension being assigned. Removing the extension, dirsync is working again. The user has an E5 license assigned. Any ideas why the sync from localAD to AzureAD is failing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82154a26-a125-e7ea-8731-a8c4472fe735
* Version Independent ID: 015533c1-6a15-3dc1-083d-3370bdc3915d
* Content: [Set-CsUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by dariomws306** [comment]
Hi @angiurgiu, thank you for your feedback.

Could you explain in more detail your scenario?

Usually you get "Can not update OnPremLineURI as the user has dirsynced onpremise LineURI" when the user have some value on the onprem msRTCSip-Line attribute. If you cleanup this attribute the issue should be fixed.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @angiurgiu 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
