### ISSUE TITLE
Root sites with publishing

### ISSUE THREAD

**Issue by pedropablo** [MicrosoftDocs/office-docs-powershell#3374]
What will happen with a root site that has/had publishing feature? Command will just fail? Something can break? Requirement #3 is heartbreaking because Publishing pages was "the way" to create a communication intranet, I don't have a single tenant that kept a vanilla team site page for the main welcome page :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 052c9917-ce90-f835-fa87-db8c0e492038
* Version Independent ID: 4c7ea433-77d3-22c9-9931-07ba83d0baca
* Content: [Enable-SPOCommSite](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Enable-SPOCommSite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @DC Padur
* Microsoft Alias: **dipadur**

**Comment by divyachapan** [comment]
If you current have or have in the past activated the classic publishing the cmdlet will fail and there will be no impact to your site.  There is an upcoming feature that maybe of help to you in this case.
https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=51259

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by balbany** [comment]
Adding my angst to that expressed by @pedropablo. There can't be many tenants that meet this criteria. Was there any research done to establish the usefulness of this cmdlet? While the ability to swap out the root site is great, it doesn't help with now needing to migrate content from the root site when this would otherwise be completely unecessary.

**Comment by JohnMongell** [comment]
Regarding Current limitations:  The site must have quick launch site navigation enabled. How do I do this?
Why would anyone put a link to outdated WSS 3.0 documentation in a SPO new feature instruction?

**Comment by get-itips** [comment]
Hello everyone thanks for your feedback.
As the author of the article has replied to the original inquiry we will proceed closing this one.
Also, to suggest feedback and changes on cmdlet's behavior, I encourage you to visit https://sharepoint.uservoice.com/
Thank you

**Comment by yogkumgit** [comment]
@pedropablo  Thank you very much for your kind feedback. Considering your valuable feedback, we request please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
