### ISSUE TITLE
New-Team Alias error message

### ISSUE THREAD

**Issue by nalhemyariirexorg** [MicrosoftDocs/office-docs-powershell#3375]
Getting an error running the following command

Connect-MicrosoftTeams -AccountId myaccount@example.com
$group = New-Team -alias "TestTeam" -displayname "Test Teams" -Visibility "private"

Source: https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps

Error: New-Team : A parameter cannot be found that matches parameter name 'alias'.
At line:1 char:19
+ $group = New-Team -alias "TestTeam" -displayname "Test Teams" -Visibi ...
+                   ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-Team], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.TeamsCmdlets.PowerShell.Custom.NewTeam

MS Teams PS version 1.0

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
@yogkumgit, tha article was updated 8 days ago to replace -Alias with -MailNickName.

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and sharing this explanation. @nalhemyariirexorg Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
