### ISSUE TITLE
New-Team Alias error message

### ISSUE THREAD

**Issue by nalhemyariirexorg** [MicrosoftDocs/office-docs-powershell#3376]
Getting an error running the following command

Connect-MicrosoftTeams -AccountId myaccount@example.com
$group = New-Team -alias "TestTeam" -displayname "Test Teams" -Visibility "private"

Source: https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps

Error: New-Team : A parameter cannot be found that matches parameter name 'alias'.
At line:1 char:19

$group = New-Team -alias "TestTeam" -displayname "Test Teams" -Visibi ...
              ~~~~~~
CategoryInfo : InvalidArgument: (:) [New-Team], ParameterBindingException
FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.TeamsCmdlets.PowerShell.Custom.NewTeam
MS Teams PS version 1.0


https://github.com/MicrosoftDocs/office-docs-powershell/issues/3375

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by 4rtorias** [comment]
Getting the same thing, I'm not sure -Alias was intended to be referenced in the provided script (Example 3).

**Comment by Dennisblotenburg** [comment]
The -Alias parameter is not available since version 1.
In place of the -Alias param, you can use -MailNickName to set the "alias".
So the correct example from script 3 should be the follow:
$group = New-Team -MailNickName "TestTeam" -displayname "Test Teams" -Visibility "private"

**Comment by dariomws306** [comment]
@yogkumgit, tha article was updated 8 days ago to replace -Alias with -MailNickName.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @nalhemyariirexorg Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
