### ISSUE TITLE
Specifying which groups are supported

### ISSUE THREAD

**Issue by cmcapellan** [MicrosoftDocs/office-docs-powershell#3379]
Please clarify which groups are supported in -SentToMemberOf.

Appears that groups must be mail enabled or dynamic distribution lists, regular AD or Azure AD groups will not work. This is not clearly spelled out elsewhere, would have saved me a lot of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d78681-c911-cbfb-756e-2f5461c20e3b
* Version Independent ID: 835805e2-de47-1627-54db-505b3c58595e
* Content: [Set-SafeAttachmentRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-safeattachmentrule?view=exchange-ps#inputs)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Set-SafeAttachmentRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Set-SafeAttachmentRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@cmcapellan, yeah, I can see how that would be confusing.

The _SentToMemberOf_ parameter is available in 12 Exchange/Exchange Online cmdlets: New/Set-AntiPhishRule, New/Set-SafeAttachmentsRule, New/Set-SafeLinksRule, New/Set-HostedContentFilterRule, New/Set-MalwareFilterRule, and New/Set-TransportRule, all of which were designed and implemented long ago.

I changed 'groups' to 'distribution groups, dynamic distribution groups, or mail-enabled security groups', which was the right thing to do now that non-mail-enabled AAD groups are in the mix. Virtually all of the Exchange/Exchange Online cmdlets that I can think of are designed only to work with email-related recipents (the natual excepting being commands like Enable-Mailbox, Enable-MailUser, or Enable-MailContact that mail-enable non-mail-enabled objects).

Thanks for the feedback.
