### ISSUE TITLE
Availability for PowerShell Core?

### ISSUE THREAD

**Issue by dsolodow** [MicrosoftDocs/office-docs-powershell#3381]
Since this module is currently in Azure Cloud Shell, it obviously works under PowerShell Core on Linux. This suggests it should be possible to publish this module to the PowerShell Gallery for cross platform use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@dsolodow, per #3264, the module isn't supported in PowerShell for Mac, so I assumed it also didn't work in the other PowerShell Core 'workloads' (Linux and Windows Nano). But, we all know what happens when you assume something.

So I should change the note to simply say the module doesn't work in PowerShell for Mac?

**Comment by dsolodow** [comment]
So, the module currently available for download requires Windows PowerShell (note Core, so no Linux, Mac, Nano as you said).
*However* there is a version of the module in Cloud Shell, and Cloud Shell is PowerShell Core on Linux. That means (as far as I can determine) that there exists a version of the module that works with PowerShell Core on Linux, and therefore **probably** works on other versions of PowerShell Core. That version doesn't see to be available/downloadable as of yet however.

So what we probably need is for the version of the module installed in Cloud Shell to be published out to the PowerShell Gallery.

**Comment by dariomws306** [comment]
Hi @dsolodow and @chrisda, thank you for your comments.

Maybe this request should be sent to Product Group and/or added on https://office365.uservoice.com/.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @dsolodow 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
