### ISSUE TITLE
Broken Exchange link

### ISSUE THREAD

**Issue by RadioActiveLamb** [MicrosoftDocs/office-docs-powershell#3385]
The link to the Exchange module at the very top of the page is broken "Module: exchange" - https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3d8932-e958-6be5-1dd7-b0731115c4dd
* Version Independent ID: 2345fd23-d401-fbc7-38c0-4eb3c7695f0e
* Content: [Enable-RemoteMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/enable-remotemailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/Enable-RemoteMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/Enable-RemoteMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@RadioActiveLamb, this is a known issue for the last several weeks. We're Investigating.

**Comment by dariomws306** [comment]
Hi @RadioActiveLamb, thank you for your feedback.

This is a well known issue and we are looking on to it.

**Comment by dariomws** [comment]
The Exchange module link issue was fixed this week. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
