### ISSUE TITLE
-Server is not available

### ISSUE THREAD

**Issue by copenhaus** [MicrosoftDocs/office-docs-powershell#3389]
added "-Server &lt;servername&gt;" parameter to the command and I get:

Parameter set cannot be resolved using the specified named parameters.
    + CategoryInfo          : InvalidArgument: (:) [Get-MailboxDatabase], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Get-MailboxDatabase

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4795ace8-eac9-2052-30b1-5891f47cd9e2
* Version Independent ID: 7bc08610-adab-6ce8-1bf3-0edfc1b7a82e
* Content: [Get-MailboxDatabase (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailbox-databases-and-servers/get-mailboxdatabase?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailbox-databases-and-servers/Get-MailboxDatabase.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailbox-databases-and-servers/Get-MailboxDatabase.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@copenhaus, if I understand your comment correctly, you are saying that Example 3 in the topic didn't work? You are correct because the example used -Identity and -Server in the same command which (according to the SYNTAX blocks at the top of the topic) isn't allowed. I updated the example.

Thanks for the feedback.
