### ISSUE TITLE
Feature request to the Restore-recoverableitems

### ISSUE THREAD

**Issue by Divya-RP** [MicrosoftDocs/office-docs-powershell#3391]
Can we add the feature to include the restore Discoveryholds  folder as well. 

Sourcefolder include Discoveryholds. Currently it only supports DeletedItems | RecoverableItems | Purgeditems

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Divya-RP, thank you very much for posting this issue. Considering the nature of the issue, it is advised that please put this request on User Voice:
https://office365.uservoice.com/

We are here to help on docs.microsoft.com improvement, we cannot help you on feature requests. I also invite you to use feedback option again in docs.microsoft.com to help us improve it.

**Comment by yogkumgit** [comment]
@Divya-RP   Thank you very much for your kind feedback. Considering your valuable feedback, we requet you to log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by Divya-RP** [comment]
Thank you @yogkumgit and @dariomws306 for suggesting user voice. 

The Doc article gives an option to share feedback about Product as well which transfers GitHub page.

https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/restore-recoverableitems?view=exchange-ps

**Comment by dariomws306** [comment]
Hi @Divya-RP, thank you for your reply.

Feedback on docs.microsoft.com (wich transfers to Github) is the best place to request articles updates or fix. User Voice is the best place to request new features.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @Divya-RP 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
