### ISSUE TITLE
Set-SPOSite -LockState

### ISSUE THREAD

**Issue by jerryyasir** [MicrosoftDocs/office-docs-powershell#3392]
"ReadOnly" is a new state for LockState parameter.  Please update the documentation.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jerryyasir Thanks for your feedback, I tested and could verify that the ReadOnly parameter value is available now. I created a Pull Request to improve the article. Thanks

**Comment by yogkumgit** [comment]
@trent-green  Please merge PR #3428

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @jerryyasir Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
