### ISSUE TITLE
-Title in the example on this page doesn't work

### ISSUE THREAD

**Issue by esammann** [MicrosoftDocs/office-docs-powershell#3393]
The example in this page uses the -Title parameter, but PowerShell says "A parameter cannot be found that matches parameter name 'Title'.

I also found this other post where someone else has the same problem:
https://social.technet.microsoft.com/Forums/office/en-US/a35190e7-02c9-43ca-9a85-f5bee19256d3/powershell-setspweb-error?forum=sharepointadminprevious

For what it is worth though, it seems like -Title should be a parameter you can set with this command.  I mean if you can set the description, the relative URL, the theme and the template then why can't you set the TITLE.  The link above where the other person had the same problem also has an alternative, so at least there is a way.  Still Set-SPWeb could be a nice one-liner solution if MS will fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070681a3-b609-a62b-85d1-93c9a6fc2985
* Version Independent ID: 961ff1c0-3c08-83a7-4aed-b955c8498695
* Content: [Set-SPWeb (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/Set-SPWeb?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPWeb.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPWeb.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
@yogkumgit this one is missing the -Name parameter. The examples should replace -Title with -Name.


```
    -Name <>
        Specifies the new name of the Web.

        Required?
        Position?                    Named
        Default value
        Accept pipeline input?
        Accept wildcard characters?  false
```

**Comment by get-itips** [comment]
@tseward Hello Trevor, which version did you test and find the -Name parameter? I tested in Sharepoint 2013 and is not there. (Title isn't also there). But maybe if you had the chance to test on 2016/2019 I'll add a note. Thank You.

**Comment by tseward** [comment]
@get-itips my bad. No, the only available parameter is -Identity.

**Comment by get-itips** [comment]
Hello @esammann Thanks for your feedback.
We could verify, that Title isn't available to be set using this cmdlet, so I created a Pull Request to correct the article, we appreciate your feedback.
I agree that title should be available, please have a look at this resource to suggest that idea https://sharepoint.uservoice.com
Thank you

**Comment by yogkumgit** [comment]
@Techwriter40  Please merge PR #3441

**Comment by yogkumgit** [comment]
Gentle reminder @Techwriter40 Please merge PR #3441

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @esammann Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
