### ISSUE TITLE
Searching is Not properly scoped

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#3409]
When i do a search on this page, i get results from many other repositories. It should be limited to SPO documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65bf2c0b-b0ec-2748-e47e-af66011efe30
* Version Independent ID: be3968f4-d766-0b45-384b-c51c47328a86
* Content: [SharePoint Online PowerShell](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/index?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DeanGross 
Thanks for your feedback.
If you mean to the functionality of the magnifying glass in the page, that is the behavior of all docs.microsoft.com and is intended to work like that.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @DeanGross 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
