### ISSUE TITLE
How to get CDN origins for specific scope

### ISSUE THREAD

**Issue by Damag3d** [MicrosoftDocs/office-docs-powershell#3412]
There is no OriginScope parameter like in Remove-SPOTenantCdnOrigin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e4ea598-827b-f445-0904-34715521e9cd
* Version Independent ID: 45c5b70d-a4c3-d134-95a8-415ff2365f01
* Content: [Get-SPOTenantCdnOrigins (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantcdnorigins?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantCdnOrigins.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantCdnOrigins.md)
* Service: **sharepoint-powershell**
* GitHub Login: @vesajuvonen
* Microsoft Alias: **vesaj**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Damag3d 
Thanks for your feedback.
I can confirm that -OriginScope is not present in the Get-SPOTenantCdnOrigins cmdlet.
I suggest you to visit this resource https://sharepoint.uservoice.com/ to propose this to the product team.
Thank you

**Comment by yogkumgit** [comment]
@Damag3d  Thank you very much for your kind feedback. Considering your valuable feedback, we request you to log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by Damag3d** [comment]
@yogkumgit I do not get your logic here. We faced the issue that customer had Office 365 CDN set up. It became inaccessible. When we have checked if any CDNs are working then Get-SPOTenantCdnOrigins showed none. We wanted to doublecheck if CDNs are enabled on specific sites.
Also publishing feature sets up CDNs automatically. Inability to properly manage CDNs, can result in
1. security risks - when CDN used is managed by 3rd party
2. broken UI - our case
3. temporary loss of data - our case
Current behavior is such that Office 365 enables it automatically, but then does not provide tools to manage it neither via UI or PowerShell.

**Comment by get-itips** [comment]
Hello @Damag3d 
Thanks again for your feedback. We understand what you said, although this issue resource is only to address issues in documentation based on current functionality, for example, missing or wrong description for existing parameters, typos or missing examples.
In this case, the functionality that you are looking for is not currently present, so you either need to suggest it on user voice, or contact support services here https://support.microsoft.com or https://support.office.com/home/contact

Hope this information has clarified things out.

Thank you

**Comment by yogkumgit** [comment]
@Damag3d  Thank you very much for your kind feedback. Kindly follow the advise offered by Andres, this is the only way forward. If any documentation update would have required, we could happily do that.  Hope  you agree with us. Please keep posting your suggestions regarding improvements in the documentation. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
