### ISSUE TITLE
How to define originscope?

### ISSUE THREAD

**Issue by Damag3d** [MicrosoftDocs/office-docs-powershell#3413]
There is no OriginScope parameter like in Remove-SPOTenantCdnOrigin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9a4ae73-5f75-79bb-8bde-0ff57a5a7519
* Version Independent ID: 2cb872ee-33af-a8d4-09ab-cdaebd17ddd2
* Content: [Add-SPOTenantCdnOrigin (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Add-SPOTenantCdnOrigin?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTenantCdnOrigin.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTenantCdnOrigin.md)
* Service: **sharepoint-powershell**
* GitHub Login: @vesajuvonen
* Microsoft Alias: **vesaj**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Same as https://github.com/MicrosoftDocs/office-docs-powershell/issues/3412 we are closing this one.

**Comment by yogkumgit** [comment]
@Damag3d  Thank you very much for your kind feedback. Considering your valuable feedback, we request you to log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot as

**Comment by yogkumgit** [comment]
@officedocsbot close
