### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by waelschakaki** [MicrosoftDocs/office-docs-powershell#3414]
Hello,
the documentation is missing for this Powershell command could you please update it ?
Regards,
Wael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afaf5510-5002-f560-8cd3-122839d7abad
* Version Independent ID: 0ed4badd-3a93-90a3-84e9-b2270eda84a5
* Content: [Set-CsOnlineVoiceApplicationInstance (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceapplicationinstance?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineVoiceApplicationInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineVoiceApplicationInstance.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @
* Microsoft Alias: **Danny Levin**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @waelschakaki Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
