### ISSUE TITLE
Missing info for the majority of the parameters available for this cmdlet

### ISSUE THREAD

**Issue by grtaylo** [MicrosoftDocs/office-docs-powershell#3415]
Most of the parameters listed on this page have filler text associated with them, and no information regarding their functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15ee29c2-2f1b-c9d2-3556-729a5f42046c
* Version Independent ID: be7d6eb1-06c9-f368-0034-904a1399a281
* Content: [Set-CsOnlineApplicationEndpoint (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlineapplicationendpoint?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineApplicationEndpoint.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineApplicationEndpoint.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @grtaylo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
