### ISSUE TITLE
Connecting with Application Service Principal?

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/office-docs-powershell#3417]
Is it possible to connect to Office 365 using an Application Service Principal?  If so, how (provide a link or include the steps)?  If not, then this should be stated in the documentation.  Thank you.

**Comment by lesterw1** [comment]
I came across this, which seems to indicate that it is NOT possible...  This should be documented to state this.

[https://github.com/MicrosoftDocs/azure-docs/issues/10717]

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @lesterw1 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
