### ISSUE TITLE
The Description is wrong

### ISSUE THREAD

**Issue by alanbmhs** [MicrosoftDocs/office-docs-powershell#3423]
Deletes a previously created TeamsMeetingPolicy. "Any users with no explicitly assigned policies will then fall back to the default policy in the organization." Except that's not what happens - Powershell states that the policy is currently assigned and I should remove the assignment before removing the policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc1cb4c-d165-a991-c382-0eb01de9ddfe
* Version Independent ID: b3a1ea84-d636-6f6f-40e1-6e8da2ce904c
* Content: [Remove-CsTeamsMeetingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/remove-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Remove-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Remove-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith Please merge PR #3476

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @alanbmhs Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
