### ISSUE TITLE
-Force question

### ISSUE THREAD

**Issue by esammann** [MicrosoftDocs/office-docs-powershell#3425]
Is -Force really used on an Import-SPWeb command?  If so then what does it do?  I understand the use on the Export-SPWeb command but it's not really clear on the import side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae171b60-a096-2eef-d096-2c560553ac54
* Version Independent ID: b825e536-7724-f08a-677b-8c36d9102ade
* Content: [Import-SPWeb (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/import-spweb?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Import-SPWeb.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Import-SPWeb.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @esammann thanks for your feedback.
The article includes the description of the force parameter as _Forcefully overwrites the export package if it already exists._ and that is what it does.
Does that answers your question?
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @esammann Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by esammann** [comment]
Hello @get-itips and @yogkumgit
I would have to say that doesn't answer my question.  The -Force makes sense on the Export-SPWeb because it will overwrite a previously exported package if one was previously exported to the same location.  However, Import-SPWeb doesn't export anything, therefore there is no export package to overwrite.  It doesn't seem like this parameter makes sense here.

If the -Force were to overwrite a SharePoint site then that might make sense.  However, that seems to be handled with the -UpdateVersions flag.  Therefor the -Force parameter on the Import-SPWeb is confusing.

Thanks,

**Comment by get-itips** [comment]
Hello @Techwriter40 how are you?
The description for -Force parameter in Import-SPWeb cmdlet's article seems to have been copied from Export-SPWeb cmdlet's article, can you confirm please the use of -Force parameter in Import-SPWeb? I pulled my lab and could not find any difference using -Force parameter. Thanks

**Comment by yogkumgit** [comment]
@Techwriter40  Please reply to Andres's question

**Comment by Techwriter40** [comment]
I checked a TDS build of SharePoint Server 2016. The Force parameter does exist and is part of the syntax.

**Comment by get-itips** [comment]
Exactly @Techwriter40 that has already been verified by me, the cmdlet includes the Force parameter but the Force parameter does nothing actually and the description on the article is not accurate too. Please check. Thanks

**Comment by yogkumgit** [comment]
@Techwriter40  kindly confirm Force parameter is working or not and does this documentation needs  to be updated?

**Comment by yogkumgit** [comment]
Gentle reminder @Techwriter40 kindly confirm Force parameter is working or not and does this documentation needs to be updated?

**Comment by get-itips** [comment]
Hello @Techwriter40 kindly tell me if you have seen my comment about Force parameter current behavior thanks.

**Comment by get-itips** [comment]
Hello @Techwriter40 kindly tell me if you have seen my comment about Force parameter current behavior thanks.

**Comment by tseward** [comment]
Based on a decompile, I don't see that `-Force` is referenced at all.

**Comment by get-itips** [comment]
Many Thanks @tseward for that information, so that I think, reinforces my conclusion.

**Comment by yogkumgit** [comment]
@trent-green Will you be able to please help us here.

**Comment by SharePointBlackBelt** [comment]
Please just remove the -Force switch from this documentation as is must have been copied over from Export-SPWeb, but it serves no purpose on Import-SPWeb since an export package is not created, and is therefor impossible to overwrite an existing export package.

**Comment by tseward** [comment]
Not quite. The documentation isn't a copy -- `Import-SPWeb` and `Export-SPWeb` both have the `-Force` parameter. This means that this would need to be resolved in the product prior to the document. With that said, what can be done is the documentation can be updated to indicate that this parameter has no effect.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @esammann Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
