### ISSUE TITLE
-UpdateVersions question

### ISSUE THREAD

**Issue by esammann** [MicrosoftDocs/office-docs-powershell#3426]
Sorry, another question.  In -UpdateVersions it says the default is 1 if the parameter is not used.  What does 1 equate to: Append, Ignore, or Overwrite?

Also, an example of this would be nice as well.  It took me a few times to get it right.  I kept trying Add because it says -Add new versions to the current file.

Thanks,
Eric 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae171b60-a096-2eef-d096-2c560553ac54
* Version Independent ID: b825e536-7724-f08a-677b-8c36d9102ade
* Content: [Import-SPWeb (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/import-spweb?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Import-SPWeb.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Import-SPWeb.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @esammann 
Thanks for your feedback.
1 corresponds to "Append" see [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.deployment.spupdateversions?view=sharepoint-server)
I'll create a pull request to improve the article clarifying this.
Thank you

**Comment by yogkumgit** [comment]
@Techwriter40 please merge the PR #3451

**Comment by esammann** [comment]
Thank you.  It might be helpful to know what all of the other numbers for the options are as well.  For example, what number corresponds to Overwrite and Ignore?

**Comment by get-itips** [comment]
Hello @esammann 
If you search for the SPUpdateVersions enumeration, you will find documentation corresponding to it, which lists the corresponding numbers for each option https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.deployment.spupdateversions?view=sharepoint-server

Hope this information helps you.

**Comment by yogkumgit** [comment]
Gentle reminder @Techwriter40 please merge the PR #3451

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @esammann Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
