### ISSUE TITLE
The requested operation is part of an experimental feature that is not supported in the current environment.

### ISSUE THREAD

**Issue by SteveClements** [MicrosoftDocs/office-docs-powershell#3429]
I've been trying this for the last couple of days on a tenant with "Targeted release to org" set.

But I'm seeing... 
Enable-SPOCommSite : The requested operation is part of an experimental feature that is not supported in the current environment.

Latest version of SharePoint.PowerShell installed.  16.0.8812.1200

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @SteveClements 
Thanks for your feedback.
I think that your inquiry is more suitable for Office 365 support services, you can access it creating a support ticket directly from your tenant admin or https://support.office.com/

Hope this information helps you.
Thank you

**Comment by yogkumgit** [comment]
@ Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. 

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
