### ISSUE TITLE
Choose web browser with -UseWebLogin

### ISSUE THREAD

**Issue by anthonywhite** [MicrosoftDocs/office-docs-powershell#3430]
It looks like -UseWebLogin still uses the IE7 web browser control. If so, are there any plans to upgrade to Microsoft.Toolkit.Forms.UI.Controls.WebView?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f910a5c-5883-6394-19a3-4cf1670c431f
* Version Independent ID: 4451fe4c-df86-34a8-0db0-46a47e70b5a5
* Content: [Connect-PnPOnline (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @anthonywhite 
Thanks for your feedback. This issue resource is specifically to report about issues in documentation, as you might know, Sharepoint PnP cmdlets are community driven, and they have specific resources to suggest bugs, ideas and feedback, please visit here to more information https://docs.microsoft.com/en-us/sharepoint/dev/community/community

Hope this information helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @anthonywhite 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
