### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by stylerOD** [MicrosoftDocs/office-docs-powershell#3431]
This method doesn't import Exchange cmdlets to the local session. None are available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b57b66-2364-0e9d-e627-5eeb77238675
* Version Independent ID: 78fd7932-06f9-37c7-8928-250b3884d89e
* Content: [Connect to Exchange servers using remote PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/connect-to-exchange-servers-using-remote-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @stylerOD, thank you for your comment.

Could you kindly let me know what cmdlets you run? I have tested this cmdlet and it works for me. Thanks.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and digging deep into it.  @stylerOD We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
