### ISSUE TITLE
Missing -complement on New-CsOnlineSchedule

### ISSUE THREAD

**Issue by JensTrier** [MicrosoftDocs/office-docs-powershell#3437]
I believe the examples are missing the -complement on the New-CsOnlineSchedule cmd, since the callhandling is defined as afterhours

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0637a09-b222-08c8-c379-ddf503c42ae6
* Version Independent ID: ba49f51d-6c7b-be1e-098c-8e8bf3fe2ba0
* Content: [New-CsAutoAttendantCallHandlingAssociation (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csautoattendantcallhandlingassociation?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendantCallHandlingAssociation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsAutoAttendantCallHandlingAssociation.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @JensTrier, thank you for your feedback.

I understand that you define the business hours and when you define "-Type AfterHours" it works in a similar way to wich -Complement works with New-CsOnlineSchedule.

**Comment by yogkumgit** [comment]
@kenwith Please merge PR #3473

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @JensTrier Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
