### ISSUE TITLE
Heading not displaying correctly

### ISSUE THREAD

**Issue by Adam157** [MicrosoftDocs/office-docs-powershell#3438]
Document heading markdown not rendering correctly

Displays as "#Skype for Business cmdlet reference" in regular font, not H1 heading

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a585e3a-7e9d-83c0-a836-f76ef19d5af6
* Version Independent ID: 90f4954a-d2c0-65cb-eeea-4089b4239d67
* Content: [| Microsoft Docs](https://docs.microsoft.com/en-us/powershell/skype/?view=skype-ps)
* Content Source: [skype/docs-conceptual/index.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/docs-conceptual/index.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Adam157, thank you for your feedback.

Looks like you have fixed it:
https://github.com/MicrosoftDocs/office-docs-powershell/commit/a3a5346635df602389531d7064af6e6404eb415d

It could take some days to get the approval.

Thanks!

**Comment by yogkumgit** [comment]
@kenwith kindly approve this change

**Comment by dariomws306** [comment]
Hi @yogkumgit, it's approved and it's live in docs.microsoft.com.

**Comment by yogkumgit** [comment]
@dariomws306  and @Adam157  Thank you very much for the contribution and sharing this explanation. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
