### ISSUE TITLE
DirectReportsGroupAutoCreationEnabled 

### ISSUE THREAD

**Issue by ernelso** [MicrosoftDocs/office-docs-powershell#3444]
-DirectReportsGroupAutoCreationEnabled 
$true: The automatic creation of direct report Office 365 groups is enabled. This is the default value.

I believe the default value was $true at a previous point, but that changed a couple years back when we stopped the update for automatic creation of these groups.  The Default value is $false in my O365 tenant.  Please correct documentation for this parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3ab3f0-cc05-e279-8876-6da0b323bcac
* Version Independent ID: bfb49814-d60b-564a-25cc-f902dfa42b10
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@ernelso, confirmed and topic updated to $false as the default value.
