### ISSUE TITLE
<Request>Please add "UserPrincipalName" to the examples of the value that uniquely identified the user.

### ISSUE THREAD

**Issue by AkikoTsukahara** [MicrosoftDocs/office-docs-powershell#3445]
<Request from our customers>
We were just wondering if it’s possible to add “UserPrincipanName” to the examples of the value that uniquely identifies the user since our customers often ask us if they could use “UserPrincipalName” instead of using the four examples described in the Docs.

Title : Set-User
URL : https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-user?view=exchange-ps

-Identity
The Identity parameter specifies the user that you want to modify. You can use any value that uniquely identifies the user. For example:

・Name
・Distinguished name (DN)
・Canonical DN
・GUID

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by YuriySamorodov** [comment]
Updated #3462

**Comment by yogkumgit** [comment]
@chrisda please merge PR #3462

**Comment by yogkumgit** [comment]
@officedocsbot close
