### ISSUE TITLE
Get-Teams Alias error message

### ISSUE THREAD

**Issue by SveinMorten** [MicrosoftDocs/office-docs-powershell#3446]
Getting an error running the following command

Connect-MicrosoftTeams -AccountId myaccount@example.com
Get-Team -Alias "TestTeam"

The doc clearly states that this parameter can be used: https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps

However, I'm getting the following error message:
Get-Team : A parameter cannot be found that matches parameter name 'Alias'.
At line:1 char:10
+ Get-Team -Alias "Test-Team"
+          ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Team], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeam

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @SveinMorten 
Thanks for your feedback!
In version 1.0.0 of Teams Module, the parameter has been changed to MailNickName.
I created a Pull Request to modify the documentation based on this, and referenced to it here.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @SveinMorten Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
