### ISSUE TITLE
Example 1 is mostly inaccurate.

### ISSUE THREAD

**Issue by marshalanson** [MicrosoftDocs/office-docs-powershell#3447]
I just tried the code form example 1 and had to remove almost every parameter. I could only use "-name" and "-SourceMailboxes". All the rest gave me an error, "A parameter cannot be found that matches parameter name"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c994114-5ddc-27b5-dcd4-88ddfdf8c9d3
* Version Independent ID: 126d4801-9617-e8f6-49cb-76feff8f4dd2
* Content: [New-MailboxSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-mailboxsearch?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-MailboxSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-MailboxSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@marshalanson, are you using Exchange Online or a specific version of Exchange Server? According to the topic, Also, does your account have the Mailbox Search role assigned to it (likely through a role group membership)? The Mailbox Search role isn't assigned to the Organization Management role group (administrators) by default.

I copy/pasted the example in ExO tenant and Exchange 2016, and the only error I got was about (naturally) non-existent recipients.

**Comment by marshalanson** [comment]
I am running on-prem 2016. My account has mailbox search permissions. I can create a search no problem. My issue is, the command parameters are no longer available. Try that command again, but with a live user.

**Comment by chrisda** [comment]
@marshalanson, I used live mailboxes and the command worked just fine; no errors. I ran the following command, and every parameter in Example 1 was available to me (I sorted the output and removed common parameters for clarity).

```
[PS] C:\>(get-command New-MailboxSearch).parameters | ft Key

Key
---
AllPublicFolderSources
AllSourceMailboxes
Confirm
Description
DomainController
EndDate
EstimateOnly
ExcludeDuplicateMessag
Force
InPlaceHoldEnabled
InPlaceHoldIdentity
IncludeKeywordStatisti
IncludeUnsearchableIte
ItemHoldPeriod
Language
LogLevel
MessageTypes
Name
Recipients
SearchQuery
Senders
SourceMailboxes
StartDate
StatusMailRecipients
TargetMailbox
WhatIf
```
