### ISSUE TITLE
Parameter description seems wrong

### ISSUE THREAD

**Issue by Toanan** [MicrosoftDocs/office-docs-powershell#3449]
The parameter -RequiresJoinApproval has the same description as the -Description parameter. 
No big deal, just a little correction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c10dd5-d549-f13c-49bb-62803472c573
* Version Independent ID: 7e6d3b3a-aa2b-eb52-65e6-f875447d58a2
* Content: [Set-SPOHubSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spohubsite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHubSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHubSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by Toanan** [comment]
I just realised same for -SiteDesignId

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Toanan thanks for your feedback, I created a pull requests to add the missing descriptions. Thank you again

**Comment by yogkumgit** [comment]
@trent-green Please merge the PR #3477

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Toanan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
