### ISSUE TITLE
Set-AntiPhishPolicy missing EnableUnauthenticatedSender

### ISSUE THREAD

**Issue by Justfyn** [MicrosoftDocs/office-docs-powershell#3450]
Set-AntiPhishPolicy, Get-AntiPhishPolicy are missing the new '-EnableUnauthenticatedSender'

https://docs.microsoft.com/en-us/office365/securitycompliance/unverified-sender-feature

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Justfyn Thanks, I created a Pull Request to add the missing param.

**Comment by yogkumgit** [comment]
@chrisda Please merge PR #3501

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Justfyn Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
