### ISSUE TITLE
Set-AntiPhishPolicy missing EnableMailboxIntelligenceProtection

### ISSUE THREAD

**Issue by ryshirak** [MicrosoftDocs/office-docs-powershell#3456]
Could you add the description about Set-AntiphishPolicy -EnableMailboxIntelligenceProtection True/False for below?

https://docs.microsoft.com/en-us/office365/securitycompliance/learn-about-spoof-intelligence

https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-antiphishpolicy?view=exchange-ps

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @chrisda How are you? Hope you are doing great.
EnableMailboxIntelligenceProtection parameter does not currently have a description in Set-AntiPhishPolicy documentation but EnableMailboxIntelligence has.
Can you kindly provide the difference within this two? They seem to correspond to this, in UI

![image](https://user-images.githubusercontent.com/36666927/59209229-2b98ff80-8b81-11e9-841c-476a4e5a0bf2.png)


Thank you

**Comment by chrisda** [comment]
@ryshirak, @get-itips, I added the parameter as well as a few others I found to both New-AntiPhishPolicy and Set-AntiPhishPolicy. Thanks for the feedback.
