### ISSUE TITLE
Get-PnPListItem - PageSize Does Not Work when Query is specified

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#3457]
It looks like Get-PnPListItem seems to be ignoring PageSize when Query is specified.
I keep getting "Get-PnPListItem : The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator." error
![image](https://user-images.githubusercontent.com/5260172/58249847-9916f480-7d68-11e9-829d-1f58e1389f85.png)

However, if I run ```Get-PnPListItem -ListName $ListName -PageSize 5000``` it works just fine and returns correct item count:
![image](https://user-images.githubusercontent.com/5260172/58249923-cf547400-7d68-11e9-93fa-d99328f1ae15.png)

I have the most recent SharePointPnPPowerShellOnline module installed
![image](https://user-images.githubusercontent.com/5260172/58249993-fad75e80-7d68-11e9-8b24-12bf69918502.png)$

And using PowerShell 5.1
![image](https://user-images.githubusercontent.com/5260172/58250043-1b9fb400-7d69-11e9-9c74-cf7103bc3056.png)

Please advise.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @YuriySamorodov thanks for your feedback.
Let me tell you that this issue resource is specifically to address issues in documentation, so your request is needs to be treated as an issue in cmdlet's behavior, besides that, this is already submitted here https://github.com/SharePoint/PnP-PowerShell/issues/879 we will proceed closing this one.

**Comment by yogkumgit** [comment]
@officedocsbot close
