### ISSUE TITLE
Account permissions required to run New-PnPUPABulkImportJob

### ISSUE THREAD

**Issue by SinghGurd** [MicrosoftDocs/office-docs-powershell#3461]
Please document the account permissions required to run this command New-PnPUPABulkImportJob. If this command requires SharePoint Admin permissions to run then please document a way for users to do that where legacy auth is disabled and MFA is enabled. We need our script to run unattended and thus providing credentials isn't an option.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @SinghGurd 
Thanks for your feedback. Let me kindly tell you that there are currently opened issues that talk about MFA support in PnP modules and some alternatives, please have a look at these

https://github.com/SharePoint/PnP-PowerShell/issues/146

https://github.com/SharePoint/PnP-PowerShell/issues/1744

Hope this information gets you in the right direction,
Thank you

**Comment by SinghGurd** [comment]
Thank you for sharing the links...I had a read through those and didn't find a solution. I do know we can use Connect-PnpOnline with -UseWebLogin parameter. In fact, i use that in some of my own scripts.

However, problem with this particular script is that it needs to run '**unattended**'. We run this script using a scheduled task.

**Comment by get-itips** [comment]
Hello @SinghGurd 

For that, I need to kindly suggest that you make that suggestion to the PnP community, as you might know, PnP modules are community driven, please continue this using this resource as a starting point https://docs.microsoft.com/en-us/sharepoint/dev/community/community

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @SinghGurd 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
