### ISSUE TITLE
Calendar example

### ISSUE THREAD

**Issue by SirJewDanielBerg** [MicrosoftDocs/office-docs-powershell#3463]
an example with :\calendar would be very useful to put here as the article does not mention this at all and that will most likely be the first thing that people are trying to do when searching for this command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58b8319-7543-3ac8-95c1-162c38b44746
* Version Independent ID: a4856d58-0bfb-5dc7-abad-c20aad5eb579
* Content: [Get-MailboxFolderPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailboxfolderpermission?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-MailboxFolderPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-MailboxFolderPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @SirJewDanielBerg Thanks for your feedback.
I created a Pull Request adding an example querying the permissions on a Calendar folder.
Thank you

**Comment by yogkumgit** [comment]
@chrisda  please merge PR #3505

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @SirJewDanielBerg Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
