### ISSUE TITLE
Link to get-mailboxpermission

### ISSUE THREAD

**Issue by SirJewDanielBerg** [MicrosoftDocs/office-docs-powershell#3464]
Often times people will need to first check calendar permissions and then mailbox permissions, just like I've had to.

A short sentence mentioning that people should go to https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailboxpermission?view=exchange-ps if they are trying to check permissions on the entire account would be very useful to put up here, as, people browsing to this page for the first time will not notice it in the left panel and won't know what that command is. Think of it as a bit of disambiguation like you have on Wikipedia when you search for something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58b8319-7543-3ac8-95c1-162c38b44746
* Version Independent ID: a4856d58-0bfb-5dc7-abad-c20aad5eb579
* Content: [Get-MailboxFolderPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailboxfolderpermission?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-MailboxFolderPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-MailboxFolderPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @SirJewDanielBerg 
First of all, thanks for your feedback. We appreciate it.
I am agree with you that the probability of finding a cmdlet name similar to another is high but Docs currently does not offer disambiguation for any cmdlet as the cmdlets have a self-explanatory name based on the Verb-Noun pair, so this time I decided not to proceed with this suggestion. Hope you understand.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @SirJewDanielBerg 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
