### ISSUE TITLE
Incorrect parameter values

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#3465]
[Enter feedback here]
The document says:

> **-ResetType**
> Type of reset to be performed. Allowed values are:
> Invalid
> Permanent
> Transient

But CMDLet says:
_**Specify one of the following enumerator names and try again: Permanent, Transient, Recreate**_

Of course it would be great also if you could clarify with few words what are the differences between these.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ef75a04-cd1e-3707-cc06-2c88b6886b7c
* Version Independent ID: 1806c180-85f1-0c5d-acc2-c18a8f1139a4
* Content: [Reset-CsRoutingGroup (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/reset-csroutinggroup?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Reset-CsRoutingGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Reset-CsRoutingGroup.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by YuriySamorodov** [comment]
Fixed in #3478

**Comment by Petri-X** [comment]
That was quick fix ! :D

But would be still possible to add clarification for them? Now there are three options, but nobody seems to know what are the differences.

**Comment by get-itips** [comment]
Hello @Petri-X thanks for your feedback, finally, we are close to close this now as I created a pull request to add the missing description, thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Petri-X Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
