### ISSUE TITLE
What do you do you if you have publishing enabled?

### ISSUE THREAD

**Issue by bmersereau** [MicrosoftDocs/office-docs-powershell#3469]
What do you do with this error?

"Classic publishing feature is currently enabled"...

Will this be addressed in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 052c9917-ce90-f835-fa87-db8c0e492038
* Version Independent ID: 4c7ea433-77d3-22c9-9931-07ba83d0baca
* Content: [Enable-SPOCommSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Enable-SPOCommSite%C2%A0?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @bmersereau thanks for your feedback
There is an specific resource for feature requests so I will need to redirect you that way, kindly visit https://sharepoint.uservoice.com please submit there that inquiry, Thank You!

**Comment by yogkumgit** [comment]
@bmersereau  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
