### ISSUE TITLE
Dates Wrong

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#3470]
Still getting error: Enable-SPOCommSite : The requested operation is part of an experimental feature that is not supported in the current
environment.

This page says it should work after 5/15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 052c9917-ce90-f835-fa87-db8c0e492038
* Version Independent ID: 4c7ea433-77d3-22c9-9931-07ba83d0baca
* Content: [Enable-SPOCommSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Enable-SPOCommSite%C2%A0?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by awvala** [comment]
We are also on Targeted Release for our organization and still receiving error: Enable-SPOCommSite : The requested operation is part of an experimental feature that is not supported in the current
environment as of 5/28/19.

**Comment by get-itips** [comment]
Hello @trent-green can you kindly shine some light here on this matter? I appreciate

**Comment by kwoodVisions** [comment]
Yes, please update us on this as I've been waiting a long time for this feature and would love to use it.

**Comment by trent-green** [comment]
The paragraph has been updated to reflect the most recent updates for the feature.  Thanks

**Comment by pyoungberg** [comment]
Didn't see anything change in the paragraph above... it still states that Targeted Release would have it available after the 15th. Haven't spoken to anyone that has gotten this to work for their tenancy yet - was the rollout for Targeted Release delayed, or are you hopping straight to GA in the next week or two like the article implies?

**Comment by get-itips** [comment]
@pyoungberg As @trent-green said, changes should be reflected soon, as the changes are not already being reflected, you can see the commit for these changes here https://github.com/MicrosoftDocs/office-docs-powershell/commit/96277b32eaf5faa18b298509bed894746542b3a1#diff-10d599650067fcfcd152e0666f40f283

Hope this information helps you. This change should go live soon.

**Comment by pyoungberg** [comment]
Rollout delayed until at least Q3, got it. Thanks for the info!

**Comment by blods** [comment]
Grrrr - so frustrating. Our Intranet home page has been in limbo for 6 months, awaiting this change.

**Comment by joostvdlinden** [comment]
I am also facing this issue. For months I am receiving this error... how long does it take for this update to roll out......

**Comment by pyoungberg** [comment]
@get-itips / @trent-green can you update the article again please? We're in Q4 and the feature still hasn't rolled out to GA so the reference to 'more info in Q3' is misleading. You could probably just link it to https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=46338 and call it good.

**Comment by get-itips** [comment]
Hello @pyoungberg Paul, I'll update the article as you requested. Thanks

**Comment by yogkumgit** [comment]
@officedocsbot reopen

**Comment by yogkumgit** [comment]
@trent-green Please merge this PR #4174

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @danmyhre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
