### ISSUE TITLE
Under Example 2, I think instead of Remove-CsVoiceRoutingPolicy it must be Remove-CsOnlineVoiceRoutingPolicy

### ISSUE THREAD

**Issue by rajeshkhanikar** [MicrosoftDocs/office-docs-powershell#3471]
Instead of Get-CsVoiceRoutingPolicy -Filter "tag:*" | Remove-CsVoiceRoutingPolicy
Get-CsVoiceRoutingPolicy -Filter "tag:*" | Remove-CsOnlineVoiceRoutingPolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 167c86dd-8032-f620-a094-73e39612b3cb
* Version Independent ID: 2233a887-1c30-5654-ed4a-6ab750f2ff7d
* Content: [Remove-CsVoiceRoutingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/remove-csvoiceroutingpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Remove-CsVoiceRoutingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Remove-CsVoiceRoutingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @rajeshkhanikar 
Thanks for your feedback.
You can't pipe the result of a SfB OnPrem cmdlet to a SfB Online cmdlet. Correct me if I understood wrong your inquiry.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @rajeshkhanikar 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
