### ISSUE TITLE
Where is "Search-UnifiedAuditLog" ?

### ISSUE THREAD

**Issue by jschrap** [MicrosoftDocs/office-docs-powershell#3472]
I'm checking out to see if the "InativeUsersLast90Days.ps1" script delivers - or how to make it work for us. One of the packages it uses is:  **Search-UnifiedAuditLog**  
I can't locate it in the powershellgallery. Where else should I be looking?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by YuriySamorodov** [comment]
@jschrap Please be advised ```Search-UnifiedAuditLog``` is available in Exchange Online PowerShell. [Proof](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog?view=exchange-ps)

**Comment by get-itips** [comment]
Hello @jschrap thanks for your feedback.
@YuriySamorodov pointed in the right direction to locate the cmdlet, so we will proceed closing this one.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  and @YuriySamorodov  Thank you very much for the contribution and sharing this explanation. @jschrap Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
