### ISSUE TITLE
Is there a parameter `AddtoLatestVersion` ?

### ISSUE THREAD

**Issue by nils-a** [MicrosoftDocs/office-docs-powershell#3480]
Example 2 shows:

&gt; Install-SPSolution -Identity contoso_solution.wsp -GACDeployment -AddtoLatestVersion $true

However, `AddtoLatestVersion` is not mentioned anywhere else.

Please document it, if it's a valid parameter or change the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d922a32-981c-8e08-9359-b7f5e21b1aa4
* Version Independent ID: a0f9af58-42af-202c-10f3-dbb09b17595e
* Content: [Install-SPSolution (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/install-spsolution?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Install-SPSolution.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Install-SPSolution.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @nils-a Thanks for your feedback.
-AddtoLatestVersion has been replace by -CompatibilityLevel, which is the next example.
I'll create a Pull Request to remove the example containing the old parameter.
Thank you!

**Comment by yogkumgit** [comment]
@Techwriter40  Please merge this PR #3509

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @nils-a 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
