### ISSUE TITLE
unable to silence warning when attempting to delete mailbox rules. 

### ISSUE THREAD

**Issue by ThirstyAdmin** [MicrosoftDocs/office-docs-powershell#3482]
When running the following command, and corrupt mailbox rules exist you are unable to silence the warning you receive. 

try{Get-InboxRule -Mailbox $account | Remove-InboxRule -confirm:$false -ErrorAction SilentlyContinue -WarningAction SilentlyContinue}catch{throw "Error | There was an issue removing mailbox rules:" + $_.exception.message}

the error you will receive if there are corrupted rules is: 
Warning: The inbox rule 'name of rule' contains errors. To resolve the error please edit the rule, or re-create it. 

In all attempts to suppress the warning using -WarningAction SilentlyContinue, and even | out-null at the end of the command does nothing, the warning still shows up.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ThirstyAdmin 
Thanks for your feedback. I do not see that you referenced any specific article to be improved here.
This issue system is specifically to address issues in documentation.
It seems that your inquiry is more suitable for support resources https://support.microsoft.com/en-us/hub/4343728/support-for-business
Hope this information helps you.

**Comment by yogkumgit** [comment]
@ThirstyAdmin Thank you very much for posting this issue. Considering the nature of the issue, as advised please open a service ticket in your tenant and follow with them for the resolution. 

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
