### ISSUE TITLE
What does declaring somethng as a record do?

### ISSUE THREAD

**Issue by powercycle** [MicrosoftDocs/office-docs-powershell#3492]
it would be good if there was a short description about what this actually accomplishes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0312471-d10e-7498-f947-959fe2a51cbc
* Version Independent ID: 43797547-d167-c086-5c2f-1b92a92cf92d
* Content: [Set-PnPListItemAsRecord (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplistitemasrecord?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItemAsRecord.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItemAsRecord.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @powercycle thanks for your feedback.
This has to do with Sharepoint Records Management functionality.
I created a pull request to add a link to more information about this feature.
Thank you.

**Comment by yogkumgit** [comment]
@Techwriter40  please merge this PR #2113

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @powercycle Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
