### ISSUE TITLE
what is AuxPrimary - appreciate if more info about it would be provided 

### ISSUE THREAD

**Issue by limin365** [MicrosoftDocs/office-docs-powershell#3498]
as title, great thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8949c8-410d-2c67-6282-b2ec5a5b30ae
* Version Independent ID: 1946599a-0475-f36a-254e-7826dcf719aa
* Content: [Get-MailboxLocation (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailboxlocation?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-MailboxLocation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-MailboxLocation.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @chrisda Can you shed some light here on the meaning of AuxPrimary?
I could get the meaning for MainArchive and AuxArchive, so if we also get the other ones I could improve the article. Thanks!!

**Comment by get-itips** [comment]
Hello @limin365 
@chrisda has updated the article pushing a commit to it, you will see the reflected changes shortly.
We will proceed closing this thread now.
We appreciate your feedback that has improved the article.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @limin365 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
