### ISSUE TITLE
For classic experience only

### ISSUE THREAD

**Issue by JoeAyre** [MicrosoftDocs/office-docs-powershell#3512]
Unless I'm mistaken, Add-PnPJavaScriptLink and Add-PnPJavaScriptBlock techniques will only work in SharePoint Classic Experience. As such, mentioning this in the description would be helpful to those trying to do something similar in SharePoint Modern Experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96d4471-c5ae-78d8-e557-31cf4f62a36d
* Version Independent ID: 1d57aca6-da48-c2fc-9ab6-14d2c07af72c
* Content: [Add-PnPJavaScriptLink (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpjavascriptlink?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPJavaScriptLink.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPJavaScriptLink.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @JoeAyre thanks for your feedback.
I created a pull request to improve the documentation of the referenced cmdlet.
Thank you

**Comment by yogkumgit** [comment]
@erwinvanhunen Please merge the PR https://github.com/SharePoint/PnP-PowerShell/pull/2136

**Comment by yogkumgit** [comment]
@erwinvanhunen Gentle reminder Please merge the PR SharePoint/PnP-PowerShell#2136

**Comment by kenwith** [comment]
@VesaJuvonen - 27 days ago.. can you help us get this resolved?

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @erwinvanhunen thanks for merging it. @JoeAyre  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
