### ISSUE TITLE
Modules are not getting loaded

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/office-docs-powershell#3515]
I ran 'Install-Module -Name Microsoft.Online.SharePoint.PowerShell' command and successfully installed "Microsoft.Online.SharePoint.PowerShell" module. When I ran "Get-Module -Name Microsoft.Online.SharePoint.PowerShell -ListAvailable | Select Name,Version" command I can see the module is available and gives me below result.

Name                                   Version
----                                   -------
Microsoft.Online.SharePoint.PowerShell 16.0.8924.1200

But when I try to execute "Connect-SPOService" command got below error

Connect-SPOService : The term 'Connect-SPOService' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ Connect-SPOService
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-SPOService:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

When I try to load the module manually with 'Import-Module Microsoft.Online.SharePoint.PowerShell' command got below error

Import-Module : Could not load type 'Microsoft.SharePoint.Administration.DesignPackageType' from assembly
'Microsoft.SharePoint.Client, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.
At line:1 char:1
+ Import-Module Microsoft.Online.SharePoint.PowerShell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b23d72-33ed-a6a1-a442-a5e5cf039f9f
* Version Independent ID: 4247cf37-3667-2007-7251-46ed80f58ef5
* Content: [Getting started with SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ravick4u 
Thanks for your feedback.

I followed the steps in the article and it works

![image](https://user-images.githubusercontent.com/36666927/59779940-8c19f200-928f-11e9-989b-381b753d93a4.png)

Also, Connect-SPOService is recognized without needing to import-module (but you could also run it)

As the documentation works I do not see that it needs to be modified, as this issue resource is specifically to address issues in documentation, I kindly suggest you to either remove the module and reinstall, or contact support at https://support.microsoft.com

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ravick4u 
Hope this comment is helpful for you. Considering the nature of the issue, as advised that please open a service ticket in your tenant and follow with them for the resolution.

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by arowswell** [comment]
This isn't resolved. I've uninstalled and re-installed the module and still it cannot find the cmdlet Connect-SPOService.

**Comment by arowswell** [comment]
This is the error when trying to Import-Module (which I understand isn't required, but might explain why the Connect cmdlet is missing)

System.TypeLoadException: Could not load type
                        'Microsoft.SharePoint.Administration.DesignPackageType' from assembly
                        'Microsoft.SharePoint.Client, Version=16.0.0.0, Culture=neutral,
                        PublicKeyToken=71e9bce111e9429c'.
                           at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly,
                        ObjectHandleOnStack retTypes)
                           at System.Reflection.RuntimeAssembly.GetExportedTypes()
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly
                        assembly, String name)
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflectio
                        n(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean                                                                                                                                                                                   isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String                                                                                                                                                                                     helpFile, Type& randomCmdletToCheckLinkDemand, Type& randomProviderToCheckLinkDemand)
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly                                                                                                                                                                                   assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean
                        isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String&                                                                                                                                                                                    helpFile)
                           at
                        System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly                                                                                                                                                                                   assembly, PSModuleInfo module)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo
                        parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly
                        assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options,
                        ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean                                                                                                                                                                                      loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule,                                                                                                                                                                                      String fileName, String moduleBase, String prefix, SessionState ss, Object privateData,
                        ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found,                                                                                                                                                                                  Boolean& moduleFileFound)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo                                                                                                                                                                                     parentModule, ModuleSpecification moduleSpecification, String moduleBase, Boolean
                        searchModulePath, String prefix, SessionState ss, ImportModuleOptions options,
                        ManifestProcessingFlags manifestProcessingFlags, Boolean loadTypesFiles, Boolean
                        loadFormatFiles, Object privateData, Boolean& found, String shortModuleName, Nullable`1
                        manifestLanguageMode)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String
                        moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable
                        localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion,
                        Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid,
                        ImportModuleOptions& options, Boolean& containedErrors)                                                                                                                                                                                                                            at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule,                                                                                                                                                                                      String fileName, String moduleBase, String prefix, SessionState ss, Object privateData,                                                                                                                                                                                         ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found,                                                                                                                                                                                  Boolean& moduleFileFound)                                                                                                                                                                                                                                                          at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo                                                                                                                                                                                           parentModule, String moduleName, String fileBaseName, String extension, String moduleBase,                                                                                                                                                                                      String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags                                                                                                                                                                                            manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)                                                                                                                                                                                                                 at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingMultiVersionModuleBase(String                                                                                                                                                                                     moduleBase, ImportModuleOptions importModuleOptions, Boolean& found)                                                                                                                                                                                                               at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo                                                                                                                                                                                           parentModule, Boolean found, IEnumerable`1 modulePath, String name, SessionState ss,                                                                                                                                                                                            ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, PSModuleInfo&                                                                                                                                                                                     module)                                                                                                                                                                                                                                                                            at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModul                                                                                                                                                                                 eOptions importModuleOptions, String name)                                                                                                                                                                                                                                         at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()                                                                                                                                                                                                            at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by KirkMunro** [comment]
@get-itips This is actually a documentation issue. The Microsoft.Online.SharePoint.Module will not load in PowerShell if [SharePoint Client Components](https://www.microsoft.com/en-ca/download/details.aspx?id=42038) are installed. The documentation describing how to install this module must identify this incompatibility, because this is the root cause of the error reported above.

**Comment by get-itips** [comment]
> @get-itips This is actually a documentation issue. The Microsoft.Online.SharePoint.Module will not load in PowerShell if [SharePoint Client Components](https://www.microsoft.com/en-ca/download/details.aspx?id=42038) are installed. The documentation describing how to install this module must identify this incompatibility, because this is the root cause of the error reported above.

Hello @KirkMunro Kirk, how are you? 👍 Thanks for your feedback.
I installed the SharePoint Client Components on my lab and I can import, connect and run cmdlets of the Microsoft.Online.SharePoint.Module without issues

![image](https://user-images.githubusercontent.com/36666927/80104308-26506380-854d-11ea-9327-01943053a2bd.png)
