### ISSUE TITLE
OnQuickLaunch is obsolete. Please update doc page for New-PnPList

### ISSUE THREAD

**Issue by semopz** [MicrosoftDocs/office-docs-powershell#3517]
The PnP cmdlet warns that QuickLaunchOptions is obsolete. The OnQuickLaunch property/parameter should be used instead which accepts a QuickLaunchOptions Enum in the Microsoft.SharePoint.Client namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cc382c3-3ec0-c486-b797-35ea2c852a16
* Version Independent ID: 0f92a4c2-4bd6-4fad-95b2-b3d0f06612f1
* Content: [New-PnPList (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnplist?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPList.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @semopz 
Thanks for your feedback.
Actually, OnQuickLaunch is a switch parameter in the cmdlet, it is either True or False, see [here](https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Lists/NewList.cs)

The documentation of PnP cmdlets, reflects the documentation that is present in the source code, and currently, it says for OnQuickLaunch: _Switch parameter if this list should be visible on the QuickLaunch_ So I do not see a need to modify current documentation.

Thank you for your valuable feedback

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @semopz 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
