### ISSUE TITLE
Set-MailboxCalendarConfiguration bad example provided for weatherlocations

### ISSUE THREAD

**Issue by klishb** [MicrosoftDocs/office-docs-powershell#3520]
Per documentation:

This parameter uses the syntax: LocationId:<LocationID>;Name:<Name>;Latitude:<Latitude>;Longitude:<Longitude>. For example, LocationId:105808079;Name:Redmond, WA;Latitude:47.679;Longitude:-122.132.

If you use that syntax it produces this result:

{LocationId:locationid:105808079;Name:Redmond, WA;Latitude:47.679;Longitude:-122.132}

If you manually use OWA to set the value it results in this being stored for that value:

{LocationId:105808079;Name:Redmond, WA;Latitude:47.679;Longitude:-122.132}

This example actually produces the expected result:

get-mailbox  | set-mailboxcalendarconfiguration -weatherlocations '105808079;Name:Redmond, WA;Latitude:47.679;Longitude:-122.132'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ef0bf7-3f9a-773d-7aa4-e167145400b8
* Version Independent ID: d035e696-2d26-a97d-a303-273b85266d1f
* Content: [Set-MailboxCalendarConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/Set-MailboxCalendarConfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-MailboxCalendarConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-MailboxCalendarConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by klishb** [comment]
Followup troubleshooting this morning.  I found that even though the PowerShell value looked correct the weather location not actually working as expected for the end user.  Apparently my original command I had a lowercase "L" on the locationId.  It's case sensitive and if you specify a capital L then the value also looks correct in PowerShell, but this time it works as expected for the end user.

I guess we can close this issue.  The example syntax works correctly.  My apologies.

**Comment by yogkumgit** [comment]
@klishb Thank you very much for the contribution and sharing this explanation. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
