### ISSUE TITLE
Missing Options on LinkType

### ISSUE THREAD

**Issue by thmeyer-msft** [MicrosoftDocs/office-docs-powershell#3522]
For the Switch LinkType there missing some Options
You can use the following values for LinkType: Members | Owners | Subscribers | Aggregators | EventSubscribers (5 pieces) 
But in the sentence above valid values are:
There only named 3 values. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77a564cf-b454-d046-070b-ddc0c05c7a7f
* Version Independent ID: 055a9698-c1cc-174d-6c66-33c3bf21a55c
* Content: [Get-UnifiedGroupLinks (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/get-unifiedgrouplinks?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroupLinks.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroupLinks.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by thmeyer-msft** [comment]
Hey Guys, thanks for fixing but I think the same issue exist in the Set-Unified... & Remove-Unified.. Articles

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @thmeyer-msft 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
