### ISSUE TITLE
Example 5 uses incorrect parameter

### ISSUE THREAD

**Issue by dantshin** [MicrosoftDocs/office-docs-powershell#3523]
Example 5 refers to non-existent parameter -SiteLogoPath. It should be -LogoFilePath

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2961cab8-c2d4-e90b-6d78-666a4dc16823
* Version Independent ID: d9e27a2c-8408-95ba-6d88-46e63fe878a1
* Content: [Set-PnPSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @dantshin thanks for your valuable feedback.
I created a pull request to correct the documentation of the cmdlet.
Thank you

**Comment by yogkumgit** [comment]
@erwinvanhunen  Please merge the Corrected set logo example https://github.com/SharePoint/PnP-PowerShell/pull/2131

**Comment by yogkumgit** [comment]
@erwinvanhunen Gentle reminder. Please merge the Corrected set logo example SharePoint/PnP-PowerShell#2131

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @erwinvanhunen thanks for merging it. @dantshin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
