### ISSUE TITLE
Export-AutoDiscoverConfig command authenticates on the target domain controller with LDAP Simple Bind

### ISSUE THREAD

**Issue by jwojnar** [MicrosoftDocs/office-docs-powershell#3524]
The article should mention that the Export-AutoDiscoverConfig command authenticates on the target domain controller with LDAP Simple Bind. So if the target domain controller requires LDAP Signing ("Domain controller: LDAP server signing requirements" -> "Require signature"), the Export-AutoDiscoverConfig command fails with the error: "A more secure authentication method is required for this server.".

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #3575

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @jwojnar Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
