### ISSUE TITLE
Get-PnPUser -web subsite1 -WithRightsAssigned

### ISSUE THREAD

**Issue by JennyExe** [MicrosoftDocs/office-docs-powershell#3526]
The following command is returning users from all of the site collection, not the specified subsite Get-PnPUser -web subsite1 -WithRightsAssigned

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @JennyExe Thanks for your feedback, this is a known bug, and is related to the nature of the cmdlet inheriting from a base class (PNPWebCmdlet) that includes it.
I will add a reference to this issue [here](https://github.com/SharePoint/PnP-PowerShell/issues/2056)
And we will proceed closing this one.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @jennyExe
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
