### ISSUE TITLE
Add-TeamUser - Guest account not working

### ISSUE THREAD

**Issue by simon-scym** [MicrosoftDocs/office-docs-powershell#3529]
When you use the Add-TeamUser to add an, Existing and active, Guest account it is not visible in team but visible in Team Admin.  And the guest user does not have access to the Team

**Comment by simon-scym** [comment]
My bad, it needs some delay before it refresh...

**Comment by chenxizhang** [comment]
I found the deloy maybe 2-3 hours or even longer. How can we add the guest quickly?
