### ISSUE TITLE
Get-Team by -DisplayName not working

### ISSUE THREAD

**Issue by FedeFigueredo** [MicrosoftDocs/office-docs-powershell#3530]
Hi! I can get data with Get-Team filtering by every parameter (-GroupId, -User, etc) but it´s not working using -DisplayName <string> (i.e.: "Test #3"). Powershell just shows a blinking white script, I can´t write any other command and I ´ve to close the console. Please solve this issue because I need to program at my work in Accenture (really big Microsoft client) batch scripts that runs this command...

![Untitled](https://user-images.githubusercontent.com/49570839/59060816-567d0e00-8878-11e9-9da1-7b50a4844f47.jpg)

Thanks in advance

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @FedeFigueredo thanks for your feedback.
I tested with the exact display name that you are testing and it worked for me
![image](https://user-images.githubusercontent.com/36666927/59778998-db5f2300-928d-11e9-8bfa-e20cadaa68fd.png)

Please be sure to run the latest version of the Teams module.
Also, as this issue resource is specifically to address of issues in Documentation, I encourage you to visit support resources of your tenant or https://support.microsoft.com/ if you continue with this issue.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @FedeFigueredo 
Hope this comment is helpful for you. Considering the nature of the issue, as advised that please open a service ticket in your tenant and follow with them for the resolution. 

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by FedeFigueredo** [comment]
Thanks! Forgot to respond. The problem is that is taking forever. About 15 minutes to retrieve an answer from the server. It searches in ALL the existing Teams created in every organization? Or just filters in the Teams owned by my organization? And also user can query any Team created by everyone? Tought I would be limited by my organization but I can see you (outside my organization) can get data from Teams I´ve created within my organization.
