### ISSUE TITLE
Missing parameter

### ISSUE THREAD

**Issue by Florin-JustPlus** [MicrosoftDocs/office-docs-powershell#3536]
From Git:
[Parameter(Mandatory = false, HelpMessage = @"If a theme is already present, specifying this will overwrite the existing theme")]
        public SwitchParameter Overwrite { get; set; }
You should update current page with "Overwrite" parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc5bbf0-de64-2053-6f85-2d61c741ed49
* Version Independent ID: 4cfa875f-7550-cb50-259a-b097d851c100
* Content: [Add-PnPTenantTheme (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnptenanttheme?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTenantTheme.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTenantTheme.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Florin-JustPlus thanks for your feedback.

In the case of PnP cmdlet,s the cmdlet gets reflect into the article, so it seems in this case that they are not in sync. I'll create a bug in the PnP repo referencing this issue and we will proceed closing this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for reporting the issue in Sharepoint repository and linking here and also sharing this explanation. @Florin-JustPlus   Hope this comment is helpful for you. These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue.

**Comment by yogkumgit** [comment]
@officedocsbot close
