### ISSUE TITLE
Details Missing

### ISSUE THREAD

**Issue by TheWatcherNode** [MicrosoftDocs/office-docs-powershell#3540]
Hi there,

I have now noticed that this page is missing a lot of information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1de935ce-1b09-28e1-3d57-7993891973a8
* Version Independent ID: 1e5178a1-e518-b6d0-3074-0a9cf2eab664
* Content: [Get-CsAdditionalInternalDomain (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csadditionalinternaldomain?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsAdditionalInternalDomain.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsAdditionalInternalDomain.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @TheWatcherNode thanks for your feedback.
I created a pull request to add the missing details.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @TheWatcherNode Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
