### ISSUE TITLE
Ensure-PnPFolder should be Resolve-PnPFolder

### ISSUE THREAD

**Issue by jimdavis66** [MicrosoftDocs/office-docs-powershell#3543]
There's no such thing as Ensure-PnPFolder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b385a5-4bb6-e858-d114-df8b6b41114f
* Version Independent ID: e9821d8f-8e0b-5939-9f3e-43bffb6a0e7b
* Content: [Get-PnPFolder (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpfolder?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFolder.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jimdavis66 
Thanks for your feedback.
Actually, Ensure-PnpFolder is an [alias](https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Files/ResolveFolder.cs) of Resolve-PnpFolder, so the hint in the referenced article still works.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @jimdavis66 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
