### ISSUE TITLE
Missing parameter in example

### ISSUE THREAD

**Issue by rtenklooster** [MicrosoftDocs/office-docs-powershell#3544]
`Get-PnPNavigationNode -TopNavigationBar `
Should be:
`Get-PnPNavigationNode -Location TopNavigationBar`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6633c99f-3565-84cf-f11a-cd055df5885e
* Version Independent ID: 40ba47f1-40f3-b4c4-cc93-fa29841595c2
* Content: [Get-PnPNavigationNode (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpnavigationnode?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPNavigationNode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPNavigationNode.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @rtenklooster thanks for your feedback
This was fixed in the source code [here](https://github.com/SharePoint/PnP-PowerShell/commit/fbddf5134e7397ea029e007cf9db37fc9aade421#diff-84c5b42aa54c26555cd09acb645b62bb) but could take a while to be reflected in docs.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @rtenklooster 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
