### ISSUE TITLE
Example Unclear 

### ISSUE THREAD

**Issue by Dusted1969** [MicrosoftDocs/office-docs-powershell#3546]
Whilst Example 1 above will execute it expects a value to be entered for TargetedGroups as that is a REQUIRED value.  This should be made more clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 693f12cd-c3c6-c797-0fe0-88f0bbfa276c
* Version Independent ID: 1a1e7369-e6da-0d71-5340-ac83678e433f
* Content: [Set-DeviceConditionalAccessRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/set-deviceconditionalaccessrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/devices/Set-DeviceConditionalAccessRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/Set-DeviceConditionalAccessRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @dusted1969 thanks for your feedback.
I created a pull request to correct the example, as I could verify, it should be merged and live in a couple of days.
Thanks again

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #3583

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Dusted1969 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
