### ISSUE TITLE
Members of the GAL are NOT treated as trusted senders.  We have tested this this by adding contacts and very clear it does not work. 

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/office-docs-powershell#3548]
False = All email addresses in the global address list (GAL) are automatically considered as trusted senders, so you don't need to add them to the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56f33c82-9803-421e-5b26-b396239e6165
* Version Independent ID: 5ff7a257-a9b8-fba7-aeb0-a032bda799a9
* Content: [Set-MailboxJunkEmailConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/set-mailboxjunkemailconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Set-MailboxJunkEmailConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Set-MailboxJunkEmailConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @SquirrelAssassin 
Thanks for your feedback.

As this resource is to address issues specifically in documentation, I need to kindly redirect you to [support resources](https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online) or [uservoice](https://office365.uservoice.com) for you to report this not intended behavior in your tenant.

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @SquirrelAssassin 
Hope this comment is helpful for you. Considering the nature of the issue, as advised that please open a service ticket in your tenant and follow with them for the resolution.
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
