### ISSUE TITLE
Missing Event Types in Description

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/office-docs-powershell#3549]
I was looking for more information regarding event types for this cmdlet, specifically "EncryptionManual" and "EncryptionPolicy." The description section states "The following list describes all possible event types for messages" but these event types are not included. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb20809-8f21-dfd3-23bf-bbfb82679619
* Version Independent ID: be54b158-1672-5ae9-6a6d-139a7850c67b
* Content: [Get-MailTrafficReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/reporting/get-mailtrafficreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/reporting/Get-MailTrafficReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/reporting/Get-MailTrafficReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@chrisda Chris, do you think we can get more information about all possible values of Event Type in Mail Traffic Report? Thank you

**Comment by yogkumgit** [comment]
@chrisda please reply to the query asked by @get-itips

**Comment by get-itips** [comment]
Hello @chrisda can you kindly help us with this? Thank you!

**Comment by get-itips** [comment]
Hello @chrisda can you kindly help us with this? Thank you!

**Comment by KCCross** [comment]
Still working on this one.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and updating the documentation with PR. @get-itips  thanks to you too.   @terrogin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
