### ISSUE TITLE
Set-UnifiedGroup Hide group from GAL looking for C# code

### ISSUE THREAD

**Issue by KristofVanGils** [MicrosoftDocs/office-docs-powershell#3550]
Hi there! I would like to find out which code is behind Set-UnifiedGroup at 
https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-unifiedgroup?view=exchange-ps so we can integrate this in our c# project.

property we want to set: -HiddenFromAddressListsEnabled <$true | $false>

Which libraries do I need to look into?
Does this work with MFA?

Thx in advance!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @KristofVanGils 
Thanks for your feedback, although this issue resource is specifically to report issues in current articles.
I kindly suggest to review if Microsoft Graph can help you to do what you need, see https://docs.microsoft.com/en-us/graph/api/resources/groups-overview?view=graph-rest-1.0#office-365-groups

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @KristofVanGils 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
