### ISSUE TITLE
Groups object are encoded with numbers - how do I display the group names

### ISSUE THREAD

**Issue by plagooms** [MicrosoftDocs/office-docs-powershell#3551]
Hello,
When I ran this command, I get great result however the "groups" column is showing only numbers.  it is kind of difficult to replace those value because I need to lookup the group names and sometimes groups value has 2 or more groups on it.  

how do i replace that value/s with valid group name/s?

$site = siteurl   #fixed variable

cmdlet: 
get-pnpuser -WithRightsAssigned | select title, groups, email, $site

sample output:
Title                            Groups             Email                                https://domain/sites/siteurl
-----                            ------             -----                                ----------------------------------------
IO.Messaging.APA     {610, 27}          IO.Messaging.APA@domain.com      ---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ec7ac7-3858-172e-ec9c-ab7c948ae2cf
* Version Independent ID: 3a171d0d-f00d-36fd-44c3-c6bb08222b14
* Content: [Get-PnPUser (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpuser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPUser.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @plagooms 
Thanks for your feedback.
Actually this resource is intended to address issues in documentation, besides that, I recommend that you save the result to a variable and iterate the Groups member that the [User](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee542337%28v%3doffice.15%29) class has, I encourage you to read the Sharepoint CSOM referenced documentation to better understand how to handle the results.

Hope this is useful to you.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @plagooms 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by plagooms** [comment]
Thank you Andres.

For some reason, when I store the output to a variable and try  a loop, the value for column "Groups" is like the attached.
Any ideas?

get-pnpuser -WithRightsAssigned | select Title, Email, Groups, $siteurl | Export-Csv -path c:\temp\test.csv -Append -NoTypeInformation



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by plagooms** [comment]
This is how the output looks like in console...the "Groups" column has values

get-pnpuser -WithRightsAssigned | select Title, Email, Groups, $siteurl

Title                            Email                                Groups             https://hostname.domain/sites/sitename
-----                            -----                                ------             ----------------------------------------
user1                 user1@domain.com       {}
user2                 user2@domain.com         {36}


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by get-itips** [comment]
Hello @plagooms 
I kindly suggest you to visit [this resource](https://docs.microsoft.com/en-us/sharepoint/dev/community/community) to ask those questions, as you might know, PnP cmdlets are community-driven, so there is a big community that will help you in your scenario.

Other than that, the article does not need an update so we must keep this closed.

**Comment by yogkumgit** [comment]
@officedocsbot close
