### ISSUE TITLE
-Keysize

### ISSUE THREAD

**Issue by scottclarke1** [MicrosoftDocs/office-docs-powershell#3552]
Hi Guys
What purpose does a parameter serve, in this case the -Keysize if the only available value is 1024? There are lots of posts around the internet and on official Microsoft forums and pages about providing the option to increase the keysize to 2048, is there any further news on this?
See the following for example;
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_domains/2048-bit-dkim-key-not-accepted-in-office-365-dns/0aedfb57-f952-4fde-aa1e-3cf403e05e0b
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc7677b-b991-5569-3dfc-eed6476c9689
* Version Independent ID: 984ee7a6-2a9d-771c-1b94-89a9be45c79e
* Content: [New-DkimSigningConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/new-dkimsigningconfig?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/New-DkimSigningConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/New-DkimSigningConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @scottclarke1 Thanks for your feedback.
This issue resource is specifically to address issues in documentation.
Your suggestion is present on the User Voice [here](https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/19243120-set-dkim-key-size-to-2048-by-default) and according to that, it is currently in development.
Thank you.

**Comment by yogkumgit** [comment]
@scottclarke1  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
