### ISSUE TITLE
Issues with Remove-TeamUser

### ISSUE THREAD

**Issue by karinileby** [MicrosoftDocs/office-docs-powershell#3553]
I am trying to demote a team owner using Remove-TeamUser. As I read this article the following should demote an owner to a member Remove-TeamUser -GroupId &lt;GroupId&gt; -User &lt;UPN&gt; -Role Owner. However, this does not seem to be working as expected. For the record, the team in question does have multiple owners so I’m not trying to demote the last owner. I have replicated the following results in two different tenants, these are my findings;
Running Remove-TeamUser -GroupId &lt;GroupId&gt; -User &lt;UPN&gt; -Role Owner does apparently remove the user’s ownership. The user is listed as a member of the team both in the team admin center and by using the cmdlet get-teamuser, however the user also loses access to the team, despite still being listed as a member.
By following the command above with Remove-TeamUser -GroupId &lt;GroupId&gt; -User &lt;UPN&gt; and then Add-TeamUser -GroupId &lt;GroupId&gt; -User &lt;UPN&gt;, the user regains access to the team and is correctly listed as a member of the team both in the teams admin center and by getting tema membership using powershell.
I have also tried to remove an owner from the group entirely by running Remove-TeamUser -GroupId &lt;GroupId&gt; -User &lt;UPN&gt;. This also gives some strange results; The user loses access to the team, but is still listed in the teams admin center and through get-teamuser as an owner. When adding the user back to the team, the user will have member rights, but will still be listed as an owner. The user cannot be promoted to be an owner as this will return an error saying “One or more added object references already exist for the following modified properties: 'owners'”. This mismatch creates confusion.
Either, this is an issue with the cmdlet that needs to be fixed or the documentation needs to be updated to reflect the limitations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8d16f25-be6f-06eb-2cd7-9e64eab124e0
* Version Independent ID: a8181f1a-e575-410a-d5a4-0214c427b92d
* Content: [Remove-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/remove-teamuser?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Remove-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Remove-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @karinileby thanks for your feedback.
Please follow this pull request https://github.com/MicrosoftDocs/office-docs-powershell/pull/3542 where this is being discussed.
We will proceed closing this one and continue there.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @karinileby 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
