### ISSUE TITLE
an example would be nice

### ISSUE THREAD

**Issue by WillemVerwijs** [MicrosoftDocs/office-docs-powershell#3565]
an example would be nice. or a few

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82154a26-a125-e7ea-8731-a8c4472fe735
* Version Independent ID: 015533c1-6a15-3dc1-083d-3370bdc3915d
* Content: [Set-CsUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by WillemVerwijs** [comment]
I mean an example with using lineuri and perhaps other options as well

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @WillemVerwijs thanks for your feedback.
I created a pull request to add another example to the article.
Thank you

**Comment by yogkumgit** [comment]
@kenwith Please merge the PR https://github.com/MicrosoftDocs/office-docs-powershell/pull/3598

**Comment by get-itips** [comment]
@yogkumgit PR has been merged, can you close this one? Thanks

**Comment by WillemVerwijs** [comment]
closed
