### ISSUE TITLE
adding an azure AD group to permission

### ISSUE THREAD

**Issue by MMAgeek** [MicrosoftDocs/office-docs-powershell#3566]
How can we directly add an azure AD group to a list permission? the command doesnt seem to find any Azure AD groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efe3a0af-7832-8c57-58e3-eecc231d9910
* Version Independent ID: 2c7c0174-15d6-a4f6-4ec9-e43f4cfec01c
* Content: [Set-PnPListPermission (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplistpermission?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListPermission.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @MMAgeek 
Thanks for your feedback.
As you might know, PnP cmdlets are community-driven, as this resource is specifically to address about issues in documentation, I kindly encourage you to visit this resource to make that feature-suggestion https://docs.microsoft.com/en-us/sharepoint/dev/community/community

Thank you!

**Comment by MMAgeek** [comment]
Hi @get-itips I managed to work out how to do it, i will submit a PR for the documentation cmdlet examples.

**Comment by get-itips** [comment]
Hello @MMAgeek glad to hear! that would be a great contribution, please, take into account that documentation changes for PnP cmdlets must be done directly into source code repo, dev branch here https://github.com/SharePoint/PnP-PowerShell/blob/dev/Commands/Lists/SetListPermission.cs, then, those additions are reflected in this articles.
Thank you!

**Comment by get-itips** [comment]
Hello @MMAgeek how are you? did you manage to create the PR in the Pnp-Powershell repo as I told you? Please reference it here so we can close this issue. thank you!

**Comment by get-itips** [comment]
Hello @MMAgeek how are you? did you manage to create the PR in the Pnp-Powershell repo as I told you? Please reference it here so we can close this issue. thank you!

**Comment by get-itips** [comment]
Hello @MMAgeek 
As we did not hear back from you, and the original request is more suitable to support than a documentation issue, we need to proceed on closing this one.
Please, if you still have the example you were looking for, don't hesitate to propose it as I told you, so it can go back to the community.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @MMAgeek We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
