### ISSUE TITLE
Users list

### ISSUE THREAD

**Issue by tijs0289** [MicrosoftDocs/office-docs-powershell#3568]
The data format/layout in the users.txt what should this be? With or without enters/spaces, quotes? 
It could take up to 24 hours? after making 3 versions of the users.txt (with quotes, without, with breaks, without) etc it seems to provision after a couple of minutes! but we have to check manually each time!
Also we need another scrip in order grant control to a secondary admin for every users.
Please give us an easier option in the GUI or Powershell to preprovision all Onedrives without the user having to go there in order for it to provision. This manual scripting is a major headache with data migrations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f61076b-1d49-4f87-b400-fff52d067ea8
* Version Independent ID: 8173ce51-c1ef-50be-2069-1ccd3d0ab5b3
* Content: [Request-SPOPersonalSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/request-spopersonalsite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tijs0289 thanks for your feedback.
There is no mention of a txt file in the referenced article where you created this issue.
About your suggestions, I need to kindly suggest visit User Voice https://sharepoint.uservoice.com which is the resource to share ideas for new features.
Thank you

**Comment by yogkumgit** [comment]
@tijs0289  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
