### ISSUE TITLE
Wrong examples

### ISSUE THREAD

**Issue by francescopoli** [MicrosoftDocs/office-docs-powershell#3569]
The given example 2 to remove the ManagementRoleEntry is not working. The Remove-ManagementRoleEntry is not getting the right information.
The way to remove entries, could be like using this way:
assuming there is a "Get Full Recipient Permissions" ManamentRole that use "Mail Recipients" as parent role, and you want to remove all the cmdLets except the Get-RecipientPermissions, the command will be:
Get-ManagementRoleEntry "Get Full Recipient Permissions\*" | where{$_.Name -notlike "Get-RecipientPermission"} | %{Remove-ManagementRoleEntry -Identity "$($_.id)\$($_.name)" -Confirm:$false}
So you will be getting all the roles, not matching the where, and iterate with the foreach(%) each entry, and strip it out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6daa55-5aef-a10c-968b-b122a08bfed9
* Version Independent ID: 261e1bab-48f9-0ab9-e852-da0b446e08b7
* Content: [Remove-ManagementRoleEntry (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/role-based-access-control/remove-managementroleentry?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/role-based-access-control/Remove-ManagementRoleEntry.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/role-based-access-control/Remove-ManagementRoleEntry.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @francescopoli 
Thanks for your feedback, that will improve this article!
I could verify that the current example is not working, and I will add the one that you provided (with small corrections as I could verify)

Thank you!

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR https://github.com/MicrosoftDocs/office-docs-powershell/pull/3596

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @francescopoli Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
