### ISSUE TITLE
SfBO/Teams: Get-CSHuntGroup returns no results now

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/office-docs-powershell#3570]
We built all our Skype for Business Online Call queues using the [Skype for Business Online PowerShell module](https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps). We have received no notification that this interface has been deprecated, however when I now attempt to pull the CSHuntGroup list using [Get-CSHuntGroup](https://docs.microsoft.com/en-us/powershell/module/skype/get-cshuntgroup?view=skype-ps), nothing is returned.

Is this documentation now out of date, after the move of call queues and auto attendants to Teams? If so, what is the programmatic way to interact with the telephony features?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @webash 
Thanks for your feedback.
This is what I could find out, Attendant/Call Queues service is in the process of being updated, please see [here](https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Auto-Attendant-and-Call-Queues-Service-Update/ba-p/564521). Once the Product Team finalizes the onboarding, the documentation will reflect it and/or make the necessary changes. 
In the meantime I can suggest you to try with the [Get-CsCallQueue](https://docs.microsoft.com/en-us/powershell/module/skype/get-cscallqueue?view=skype-ps) cmdlet and also, create a support ticket at your tenant, if that does not work either.
Hope this information is helpful to you.

Thank You

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @webash
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by webash** [comment]
@yogkumgit These the *-CsHuntGroup cmdlets are already deprecated, because call queues have been moved from Skype for Business to Teams. The documentation should be updated *before* changes are made to the product, not after. It is unsurprising that the documentation here has not been updated, as nobody was given notification of this upgrade beyond a loosely worded blog post after the fact. At the very least a 'these commands are deprecated' note at the top could be added, linking people to the *-CsCallQueue cmdlets.

**Comment by webash** [comment]
@get-itips thanks for your response; I later did find this blog post that you've linked to. This was published on the 13th of May 2019, but yet the documentation still has not been updated as of 2019-06-24, so my post is still quite valid. Documentation should not follow release. Documentation should be **before** release. Otherwise how will people know how to use a function? This continues to be a theme of the SfB/Teams voice deployment/engineering processes and it is starting to grind my gears.

As part of this poorly communicated (not even something in the message center!) change, PSTN redirects from AAs and CQs has been removed, stated to return in "upcoming features". This is also terrible release management, since the PSTN redirection feature has been in use in many places.

**Comment by get-itips** [comment]
@webash I agree with you that documentation should be changed before, what I described is what actually happen.
@islubin can you, from Teams side, help us here to give some more info to @webash ? I appreciate.

**Comment by get-itips** [comment]
Hello @islubin i was wondering if you had time to review this, thank you i appreciate.

**Comment by kenwith** [comment]
I believe Jamie, @nomorephones , owns PowerShell now for Teams.

**Comment by get-itips** [comment]
That's good to know, thanks @kenwith

**Comment by kenwith** [comment]
Sent an email to @nomorephones Jamie, and @tomkau  Tom to see how we can get this figured out and resolved.

**Comment by get-itips** [comment]
Hello @webash 

After an internal conversation, I could get this information, _Get-CsHuntGroup has been migrated all the existing HuntGroups to new Modern Portal, Teams admin center, which also brings new set of cmdlets. So the users should be using Get-CsCallQueue. The old cmdlets are deprecated and will be removed at some point._

Hope this information helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @webash 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
