### ISSUE TITLE
Now that I have the group, how to find its members

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/office-docs-powershell#3579]
Please link to a related topic especially such as " Now that I have the group, how to find its members "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d063d71b-c1d5-e995-9e0d-a3daf646c712
* Version Independent ID: 7cff679f-a994-e371-a227-b8c5635f1aa2
* Content: [Get-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/get-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @blouwagie 
Thanks for your feedback.
I think you refer to the capability that offers the Get-UnifiedGroupLinks cmdlet, there is already a reference to it in this article that says _To view members, owners and subscribers for Office 365 Groups, use the Get-UnifiedGroupLinks cmdlet._

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @blouwagie
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
