### ISSUE TITLE
listItemAllFields shows blank fields

### ISSUE THREAD

**Issue by val43** [MicrosoftDocs/office-docs-powershell#3581]
Hi, I need to retrieve the element ID of some folders in some Sharepoint sites.
Once I got the object identified with a variable I would like to be able to retrieve the ID, but using the $folder.id method doesn't work, it's a known bug. 
Using $folder.listItemAllFields doesn't work either!!

This is how to replicate:
```
$cred = get-credential
$site = "https://mytenant.sharepoint.com/sites/mysite/mysubsite"
Connect-PNPOnline -url $site -credential $cred
Get-PnpFolderItem -FolderSiteRelativeUrl "/Documenti condivisi" #italian for "/Shared documents"
# see listed content and choose a folder
$folder = Get-PnPFolder -Url "Documenti condivisi/test"
$folder.ListItemAllFields

#blank results
Id    Title                                              GUID
--    -----                                              ----


```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @val43 thanks for your feedback.
This issue resource is specifically intended to address issues in documentation.
Said that, this is already reported [here](https://github.com/SharePoint/PnP-PowerShell/issues/2061)
I will create a reference to your issue here and we will proceed closing this one.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @val43 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
