### ISSUE TITLE
Complete examples please

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/office-docs-powershell#3587]
Please provide complete simple and complex examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53ee528c-476e-271b-1283-ee57938d7532
* Version Independent ID: 5c98b1ee-9dc7-b1fe-2db7-af1d86d2fcb3
* Content: [Recipient filters in Exchange Management Shell commands](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/recipient-filters/recipient-filters?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/recipient-filters/recipient-filters.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/recipient-filters/recipient-filters.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @blouwagie, thank you for your feedback.

There are some examples in the article. Could you elaborate further about what do you think we can do to improve this document?

Thank you!

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and digging deep into it.  @blouwagie   We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by blouwagie** [comment]
Not sure what response you need.

Bart Louwagie
Holmes, NY
bart@louwagie.com
845 202 0239 (google voice)
http://louwagie.com
https://www.linkedin.com/in/bart-louwagie/

(when conference call <https://www.uberconference.com/bart40> is needed)

**Comment by dariomws306** [comment]
Hi @blouwagie,

There are 6 examples in the article. I am kindly asking you if we can tell us in more detail how we can improve this document.

Thanks!

**Comment by blouwagie** [comment]
Hi,
THank you for replying Dario
Right now I no longer know which document that refers to and I'm about to
be off for two weeks.
Feel free to close as, this time, I really can't get back to this for two
weeks.
Regards
Bart

Bart Louwagie
Holmes, NY
bart@louwagie.com
845 202 0239 (google voice)
http://louwagie.com
https://www.linkedin.com/in/bart-louwagie/

(when conference call <https://www.uberconference.com/bart40> is needed)

**Comment by dariomws306** [comment]
Ok, thank you @blouwagie!

You can open this issue again after these two week if you think you contribute to improve this article.

**Comment by yogkumgit** [comment]
@officedocsbot close
