### ISSUE TITLE
No mention of AutoEnableArchiveMailbox parameter for the Set-OrganizationConfig cmdlet

### ISSUE THREAD

**Issue by dustindortch** [MicrosoftDocs/office-docs-powershell#3600]
For `Set-OrganizatonConfig`, the `-AutoEnableArchiveMailbox` parameter is not mentioned nor any discussion of how it behaves:

1. When are archive mailboxes created:
    - Only for new mailboxes?
    - During a nightly process?
2. Does it apply only to mailboxes that are licensed appropriately?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @dustindortch, thank you for your feedback.

I think this parameter it's not available to use:
![image](https://user-images.githubusercontent.com/33589238/60588727-11aca000-9d6e-11e9-9153-9a995701c3d7.png)

But I will try to get more information.

**Comment by dustindortch** [comment]
It worked for me, but no archives have auto enabled:
![image](https://user-images.githubusercontent.com/25554532/60594165-50dcf000-9d72-11e9-9691-ad54011f9826.png)

**Comment by dariomws306** [comment]
Thank you @dustindortch. I know it's a feature that customer requested but I am not sure if it's general available.

I am trying to get this information.

**Comment by dariomws306** [comment]
Hi @dustindortch,

I have got some information from the Product Group. They are working on this feature but it's still not available. I have added this parameter to the article but with "This parameter is reserved for internal Microsoft use" as description.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @dustindortch Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
