### ISSUE TITLE
Suggestion for new -ExcludePurgesFolder parameter for New-ComplianceSearch cmdlet

### ISSUE THREAD

**Issue by msbeane443** [MicrosoftDocs/office-docs-powershell#3612]
Hello,

I've recently been given responsibility for search and purge operations for emails in our Office365 tenant.  Our mailboxes are all configured with LitigationHold enabled meaning if I run a purge operation and then re-run the search, the result set still includes the documents that should have been moved to the Purges folder when the Purge search action was run.  If I want to be sure that the offending messages are no longer in the mailbox I need to add myself to the mailbox permissions and open the mailbox using Outlook on the web to search for the message.  This is less than ideal.

Please consider modifying the New-ComplianceSearch cmdlet to allow specification of a -ExcludePurgesFolder switch which would return results without the messages that have been processed by a Purge search action.

Regards,

msbeane443
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e72de6a-dd0f-e6e3-c4b1-63ee1cf752e8
* Version Independent ID: 228e51b7-a16a-1e5d-11c9-95cdc30b23dd
* Content: [New-ComplianceSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-compliancesearch?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @msbeane443, thank you for your feedback.

Are you proposing to add a new parameter to this cmdlet? (ExcludePurgesFolder) I am not sure if I understand.

**Comment by msbeane443** [comment]
Hi @dariomws306,

What I am proposing is the addition of a -ExcludePurgesFolder parameter to the New-ComplianceSearch cmdlet so that results returned from the search would not include emails that have been hard deleted from the mailbox.  The default value for the parameter would be False meaning that all messages matching the search query are returned even if they are located in the Purges folder.

For example:

New-ComplianceSearch -Identity someaddress@tenantname.onmicrosoft.com -ContentMatchQuery 'from:sender@hotmail.ca' -ExcludePurgesFolder

If the search did not return email messages that had been hard deleted (but still contained in the Purges folder since LitigationHold is enabled) it would not be necessary to add a mailbox permission to allow for the mailbox(es) to be searched to confirm that the emails have truly been hard deleted.

Thanks.

Scott

**Comment by dariomws306** [comment]
Thank you @msbeane443, now I understand.

Add ExcludePurgesFolder parameter could be a good feature for this cmdlet. But we cannot help here, docs feedback is to improve documentation not to request new features.
Please, I encourage you to go to User Voice to request this feature:
https://office365.uservoice.com/

Also, actually with New-ComplianceSearch you can exclude Purge folder. It's not easy, but you can:
https://docs.microsoft.com/en-us/office365/securitycompliance/use-content-search-for-targeted-collections?redirectSourcePath=%252fen-us%252farticle%252fUse-Content-Search-in-Office-365-for-targeted-collections-e3cbc79c-5e97-43d3-8371-9fbc398cd92e#step1

**Comment by yogkumgit** [comment]
@msbeane443  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by weyCC81** [comment]
#please-open

Please add one of the Attributes, as the FolderId is changing form Mailbox to Mailbox... I am not able to search over multiple Mailbox in a specific Folder.
- FolderPath 
- FolderType 
- RecoverableItemsFolder

Supported Types:
https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide

**Comment by chrisda** [comment]
@weyCC81, all we can do here is fix documentation. I suggest that you open a support case.
