### ISSUE TITLE
Changes to the default protection alerts do not appear in Get-ProtectionAlert

### ISSUE THREAD

**Issue by cammurray** [MicrosoftDocs/office-docs-powershell#3613]
When performing a change to one of the default protection alerts, for instance; "User restricted from sending email", these changes do not appear to be reflected by performing the Get-ProtectionAlert.

You can replicate this behaviour by modifying, for instance, the notification users by adding a new user. When running Get-ProtectionAlert on a default alert, it will always say "TenantAdmins" even though you've added another Notification User.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51d54fa-4505-9f5a-c737-23927c3fa5f3
* Version Independent ID: 937d76b1-48ab-dd34-a432-27db5b6284dd
* Content: [Get-ProtectionAlert (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/get-protectionalert?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance/Get-ProtectionAlert.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance/Get-ProtectionAlert.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @cammurray, thank you for your feedback.

Please check Set-ProtectionAlert cmdlet help. You cannot edit default alerts:
https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance/set-protectionalert

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @cammurray 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
