### ISSUE TITLE
Missing description for parameter 'HiddenGroupMembershipEnabled'

### ISSUE THREAD

**Issue by Borkason** [MicrosoftDocs/office-docs-powershell#3616]
Missing description for parameter 'HiddenGroupMembershipEnabled'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd7d69db-be49-179e-94ce-635337c98d07
* Version Independent ID: 9e372e66-5c7e-4d9a-56de-a35ae353fa09
* Content: [Set-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-unifiedgroup?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Borkason, thank you for your feedback.

There is a line in the cmdlet description:
"The HiddenGroupMembershipEnabled parameter is only available on the New-UnifiedGroup cmdlet. You can't change this setting on an existing Office 365 Group group."

Also, this parameter is not available in this cmdlet.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @Borkason 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
