### ISSUE TITLE
Description for HiddenFromAddressListsEnabled parameter inaccurate

### ISSUE THREAD

**Issue by Borkason** [MicrosoftDocs/office-docs-powershell#3617]
&gt; $true: The Office 365 Group is hidden from the GAL and other address lists. The group can still receive messages, but users can't search for or browse to the group in Outlook or Outlook on the web. Users also can't find the group by using the Discover option in Outlook on the web. **For users that are members of the Office 365 Group, the group will still appear in the navigation pane in Outlook and Outlook on the web.**

Whether the group will be displayed or hidden in the Outlook navigation pane is controlled via the parameter `-HiddenFromExchangeClientsEnabled`, which defaults to `$true` (members don't see the group in the Outlook navigation pane).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd7d69db-be49-179e-94ce-635337c98d07
* Version Independent ID: 9e372e66-5c7e-4d9a-56de-a35ae353fa09
* Content: [Set-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-unifiedgroup?view=exchange-ps#parameters)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Borkason, thank you for your feedback.

I think the documentation is fine. It's just a line to let you know that "-HiddenFromAddressListsEnabled $true" won't affect the group to be displayed or not in the clients. Anyway, I will try to add a minor update to avoid misunderstandings.

**Comment by yogkumgit** [comment]
@chrisda please merge the PR #3647

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @Borkason Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
