### ISSUE TITLE
Link to module: exchange is not working (404)

### ISSUE THREAD

**Issue by 2ndcahl** [MicrosoftDocs/office-docs-powershell#3620]
The link does not work:
https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e72de6a-dd0f-e6e3-c4b1-63ee1cf752e8
* Version Independent ID: 228e51b7-a16a-1e5d-11c9-95cdc30b23dd
* Content: [New-ComplianceSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-compliancesearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @2ndcahl, thank you for your feedback.

Sorry, could you let me know where you find this link?

I think you should try:
https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/New-ComplianceSearch/?view=exchange-ps

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and digging deep into it.  @2ndcahl We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by 2ndcahl** [comment]
@dariomws306 
Sorry for the vague problem description - I thought I put in more of a description.
The link is on this page:
https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/New-ComplianceSearch?view=exchange-ps

Under the page Title "New-ComplianceSearch", there is a link "Module: exchange". It's the module link that is broken.

**Comment by dariomws306** [comment]
Hi @2ndcahl, don't worry, it's hard to find and hard to get directions to find it.

But... I could find it. It's interesting, I think it's automatic but let me ask internally what we can do with this issue.

Thanks!

**Comment by dariomws306** [comment]
An internal work item has been created to fix this issue, it should be fixed in the next days.

**Comment by yogkumgit** [comment]
@2ndcahl internal team has confirmed that work item is created and added in the backlog. It will be taken up as per the internal schedule. Documentation will be updated by internal team, once work item is tested and closed. I am proceeding here to close this issue as no further action is required at this moment.  
Thanks again for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dariomws** [comment]
The Exchange module link issue was fixed this week. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by 2ndcahl** [comment]
Perfect, looks good now. Thank you for the fix.
