### ISSUE TITLE
Connect to Exchange Online PowerShell by using MFA 

### ISSUE THREAD

**Issue by fbsall** [MicrosoftDocs/office-docs-powershell#3621]
Greetings. 

When I type the following command: Connect-EXOPSSession -UserPrincipalName &lt;my_o365@email.com&gt;
a blank window opens then fade away after a few seconds, which means that I was not able to proceed with steps 3 and 4. 

I get this warning: 
WARNING: The names of some imported commands from the module 'tmp_mabtaarz.jdt' include unapproved verbs that might
make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

However, even if I didn't enter my password I was successfully connected. The test with Get-Mailbox retrieves all the mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @fbsall, thank you for your feedback.

Do you have Single Sign-On enabled?

Docs.microsoft.com feedback is to improve documentation. We cannot help you on specific issues here. I should suggest you to open a support ticket.

Thanks!

**Comment by dariomws306** [comment]
@fbsall, thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
