### ISSUE TITLE
Lack on MA/MFA details

### ISSUE THREAD

**Issue by tiagoroxo** [MicrosoftDocs/office-docs-powershell#3626]
[This document should add information for the scenarios on where Modern Authentication(MA) it's enabled and Multi-Factor Authentication(MFA)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c68752-3b36-518f-8cf1-7a4e2aa8cf15
* Version Independent ID: 98b9a798-e232-0b2c-ee0f-857071885c1d
* Content: [Move-CsUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Move-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Move-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @tiagoroxo, thank you for your feedback.

To connect to Skype for Business Online Powershell you should use these steps:
https://docs.microsoft.com/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell

You have 2 different instructions if you are using MFA or not.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @tiagoroxo 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by tiagoroxo** [comment]
> Hi @tiagoroxo, thank you for your feedback.
> 
> To connect to Skype for Business Online Powershell you should use these steps:
> https://docs.microsoft.com/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell
> 
> You have 2 different instructions if you are using MFA or not.

Thanks for your feedback. THe page explains MFA, not MA and my feedback it's about this page that does not explain how to move the users in sush scenarios.

**Comment by dariomws306** [comment]
Your welcome.

This document explain how this cmdlet works. For more information about move users from SfB Onprem to Online there are other articles, for example:
https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-between-on-premises-and-cloud
https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-from-on-premises-to-skype-for-business-online

For authentication to SfB Online powershell the article I sent you before is the reference.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @tiagoroxo 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
