### ISSUE TITLE
"Fields" parameter unclear, add another example

### ISSUE THREAD

**Issue by jeffreymcclain** [MicrosoftDocs/office-docs-powershell#3627]
$items = Get-PnPListItem -List Tasks
foreach ($item in $items) {
echo $item["CustomField"] #dot operator doesn't work
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51027f4b-155d-58c3-a020-3e80629567ce
* Version Independent ID: 12045879-94af-fd90-66a0-8f3db00a579f
* Content: [Get-PnPListItem (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnplistitem?view=sharepoint-ps#parameters)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPListItem.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jeffreymcclain 
Thanks for your feedback.
Correct me if I understood wrong your example, but you need to use it slightly different

Once you get the single ListItem object, you can call the FieldValues method like this:

`$item.FieldValues["CustomColumn"]`

To get the value of that CustomColumn. You can use the same method to get the value of an OOB column.

To my opinion this is showed in the Example 4 so I do not see a need to add or modify an example.

I expect that this helps you.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @jeffreymcclain 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
