### ISSUE TITLE
Please recheck typo

### ISSUE THREAD

**Issue by Premian** [MicrosoftDocs/office-docs-powershell#3628]
As per the blog Content Type replication job could run SharePoint Online?? is this typo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df6e4f97-6e98-78ec-dff6-2b95502d620a
* Version Independent ID: 4b99b800-f88b-413d-f943-8cdb8027211d
* Content: [Stop-SPContentTypeReplication (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/stop-spcontenttypereplication?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Stop-SPContentTypeReplication.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Stop-SPContentTypeReplication.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
@yogkumgit this should be *from* SharePoint Online instead of *to*.

**Comment by yogkumgit** [comment]
@Techwriter40 Please merge the PR #3663

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Premian Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
