### ISSUE TITLE
Component argument is missing WebScheduler Value

### ISSUE THREAD

**Issue by ThomasBIDAULT** [MicrosoftDocs/office-docs-powershell#3629]
Could you add "WebScheduler" to the -Component possible value ? This Component value is used to define custom URL for Web Scheduler.

More information https://blogs.technet.microsoft.com/praj/2016/04/04/configuring-web-scheduler-in-skype-for-business-2015-environment/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e0c8f64-4fae-829c-5f05-9a98cb587d1f
* Version Independent ID: 4e5bd46e-a76a-3e28-5594-b5631bab8e11
* Content: [New-CsSimpleUrl (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cssimpleurl?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsSimpleUrl.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsSimpleUrl.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith Please merge the PR #3666

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @ThomasBIDAULT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
