### ISSUE TITLE
how do I filter Office 365 groups?  the cmdlet list doesn't include get-unifiedgroup, even though get-unifiedgroup takes a -filter parameter

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/office-docs-powershell#3630]
if they aren't the same as these, then what are they?  Can you create a separate page?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://docs.microsoft.com/en-gb/powershell/exchange/exchange-server/recipient-filters/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @anwarmahmood1, thank you for your feedback.

There were a similar issue:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/1668

@chrisda, do you think we can add Get-UnifiedGroup here?
https://docs.microsoft.com/powershell/exchange/exchange-server/recipient-filters/filter-properties

Thanks!

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #3826

**Comment by yogkumgit** [comment]
@get-itips  and @tseward Please review the PR #3826

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @anwarmahmood1 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
