### ISSUE TITLE
Missing descritopn for paramter BypassMode

### ISSUE THREAD

**Issue by waelschakaki** [MicrosoftDocs/office-docs-powershell#3631]
Hello ,
there is another parameter\switch to this command which is BypassMode, what are the option and what is the decription of this parameter ?
Regards,
Wael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63a495ab-16d4-4f7f-d17e-5b1a9779247f
* Version Independent ID: cf4bfc0e-fd8d-d5ca-5432-798af72a8885
* Content: [Set-CsOnlinePSTNGateway (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinepstngateway?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by waelschakaki** [comment]
Hello,
any update about this parameter ?

**Comment by dariomws306** [comment]
Hi @waelschakaki, product team is still working on these parameters so they aren't fully available at the moment.
I am waiting for more information from them, I will update the document in some days.

**Comment by tomkau** [comment]
Hi @dariomws306.  here is the information I received from the team regarding BypassMode

Values are "None", "Always" and "OnlyForLocalUsers". By setting "Always" mode you indicate that your network is fully routable. If a user usually in site "Seattle", travels to site "Tallinn" and tries to use SBC located in Seattle we will try to deliver the traffic to Seattle assuming that there is connection between Tallinn and Seattle offices. With "OnlyForLocaUsers" you indicate that there is no direct connection between sites. In example above, the traffic will not be send directly from Tallinn to Seattle.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @waelschakaki Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
