### ISSUE TITLE
Inaccurate results for user filter 

### ISSUE THREAD

**Issue by umutge** [MicrosoftDocs/office-docs-powershell#3632]
When Teams Admin queries an user's teams memberships (Get-Team -User &lt;id&gt;), the result includes extra groups that are not queried member of. It lists correct query results, plus some other groups that querying (Teams Admin) account is member of.

Accurate result can be retrieved only when querying user is Global Admin role member.

As the command is built on top of Graph, I believe delegated and application permissions get mixed up in Teams PS endpoint. 

Quote from https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=cs :
With user delegated permissions this operation only works for the 'me' user. With application permissions, it works for all users by specifying the specific user id. ('me' alias is not supported with application permissions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8450991f-9f85-4d87-51b3-efa8e1004a24
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @umutge, thank you for your feedback.

Similar issues were reported before:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/2222

Please kindly open a support ticket so they can help you. We are here to help to improve docs.microsoft.com documentation.

**Comment by yogkumgit** [comment]
@umutge  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link:            https://docs.microsoft.com/office365/admin/contact-support-for-business-products

**Comment by yogkumgit** [comment]
@officedocsbot close
