### ISSUE TITLE
Pause Migration Cmdlet

### ISSUE THREAD

**Issue by nellymo** [MicrosoftDocs/office-docs-powershell#3634]
Is there a possibility of adding a Pause-Migration cmdlet or a Set-Migration cmdlet with a pause parameter for a migration job?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @nellymo, thank you for your feedback.

Are you talking about pause migration to Exchange Online?

You can use this cmdlet:
https://docs.microsoft.com/powershell/module/exchange/move-and-migration/suspend-moverequest

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and digging deep into it.  @nellymo Hope this comment is helpful for you. We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
