### ISSUE TITLE
Example 2 error

### ISSUE THREAD

**Issue by mdhirt** [MicrosoftDocs/office-docs-powershell#3637]
Hi,

On my exchange 2013 server Example 2 was not working. 

I found that by adding the Name property to the Mailbox parameter  for Get-ActiveSyncDeviceStatistics resolved it for me.

I expect this is because the objects returned by Get-CASMailbox are not Mailbox objects as required by the Mailbox parameter of Get-ActiveSyncDeviceStatistics, however giving the parameter the CASMailbox object Name property is enough for the function to identify the mailbox.

$UserList = Get-CASMailbox -Filter {HasActiveSyncDevicePartnership -eq $true -and -not DisplayName -like "CAS_{*"}; Get-Mailbox $UserList | foreach {Get-ActiveSyncDeviceStatistics -Mailbox $_.Name}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9d90b2-695e-59b0-92c2-ab9bcf43a78e
* Version Independent ID: 5647aff0-b7e9-a057-a63d-03b667a8c4b4
* Content: [Get-ActiveSyncDeviceStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/get-activesyncdevicestatistics?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/devices/Get-ActiveSyncDeviceStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/Get-ActiveSyncDeviceStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mdhirt** [comment]
Just found the examples for Get-MobileDeviceStatistics which work much better and should probably be used in preference to Get_ActiveSyncDeviceStatistics because it is being depreciated.

https://docs.microsoft.com/en-us/powershell/module/exchange/devices/get-mobiledevicestatistics?view=exchange-ps

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @mdhirt, thank you for your feedback.

You replied by yourself. This article has a note about that you have to use Get-MobileDeviceStatistics for Exchange 2013 or later.

Anyway, I have used your feedback to remove Exchange 2013, 2016, 2019 and online from this article.

Thanks again!

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #3664

**Comment by yogkumgit** [comment]
@dariomws306  and @chrisda  Thank you very much for the contribution and updating the documentation. @mdhirt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
