### ISSUE TITLE
Example uses "-Identity" as a parameter but it should be "-Path"

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/office-docs-powershell#3638]
-Identity is not a valid parameter for this commandlet; it should be -Path

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a06bdcc-a7ff-b88f-be6a-d19c009df655
* Version Independent ID: b147436d-1916-218d-1c74-5a86ae5e78f2
* Content: [New-SPEnterpriseSearchCrawlRule (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spenterprisesearchcrawlrule?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchCrawlRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchCrawlRule.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot close
