### ISSUE TITLE
OU and RecipientContainer are not actually valid for Exchange Online

### ISSUE THREAD

**Issue by mnooseman** [MicrosoftDocs/office-docs-powershell#3639]
Exchange Online cannot see on premise OU Structure, and OU Structure doesn't exist in Azure AD.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f74a1-badd-e304-55d8-1981f86c5440
* Version Independent ID: e51876c4-c39d-a1b6-4624-599eb8f823d8
* Content: [New-DynamicDistributionGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/New-DynamicDistributionGroup?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/New-DynamicDistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/New-DynamicDistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mnooseman, I get your point, but the facts are:

- The Get-OrganizationalUnit cmdlet is available in Exchange Online PowerShell, and when you run:

   ```
   Get-OrganizationalUnit | Format-Table Name
   ```

   You get the output:

   > contoso.onmicrosoft.com <br/> Soft Deleted Objects

  Granted, this isn't terribly helpful as ALL user objects are in a single OU.

- The following command works in Exchange Online PowerShell:

   ```
   New-DynamicDistributionGroup -Name "Test DDG" -OrganizationalUnit contoso.onmicrosoft.com -RecipientContainer contoso.onmicrosoft.com -IncludeRecipients "MailboxUsers,MailContacts" -ConditionalDepartment "Marketing","Sales"
   ```

So, we're in the weird position where the parameters are available, they work, but they work in the same way as if you didn't use them at all. I could add a note to that effect in the parameter descriptions. Something like:

> [!NOTE]
> Although this parameter is available in Exchange Online, there's only one usable OU in an Exchange Online organization, so using this parameter has no effect.

Or, I'll take suggestions.

**Comment by chrisda** [comment]
I added the note to the OrganizationalUnit and RecipientContainer parameter descriptions in New-DynamicDistributionGroup and Set-DynamicDistributionGroup.

Closing
