### ISSUE TITLE
Downloading Exchange Online Powershell on Edge wont work

### ISSUE THREAD

**Issue by jebujohn** [MicrosoftDocs/office-docs-powershell#3640]
With the new chromium build, the click once will only work on Explorer. Took me an hour to figure that edge browser, newer builds wont work. Can you confirm or change text here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
ClickOnce isn't supported with Chrome. When current documentation mentions 'Edge', it is going to refer to the EdgeHTML application as Chromium Edge hasn't RTM'ed. Make sure to submit a bug in Chromium Edge indicating it doesn't work -- I also submitted one.

**Comment by dariomws306** [comment]
Hi @jebujohn, thank you for your feedback.

@tseward point you in the right direction. For the time being "Edge browser" in docs.microsoft.com doesn't mean chromium-based version because it's still on preview.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @jebujohn 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
