### ISSUE TITLE
Media-configuration is not correct

### ISSUE THREAD

**Issue by ivanja81** [MicrosoftDocs/office-docs-powershell#3650]
Directly from SFB 2019 server.
PS C:\Users\sfbadmin&gt; Get-CsMediaConfiguration

Identity                           : Global
EnableQoS                          : False
EncryptionLevel                    : SupportEncryption
EnableSiren                        : False
MaxVideoRateAllowed                : Hd720p15M
EnableH264StdCodec                 : False
EnableInCallQoS                    : True
InCallQoSIntervalSeconds           : 10
EnableRtpRtcpMultiplexing          : True
EnableVideoBasedSharing            : True
WaitIceCompletedToAddDialOutUser   : False
EnableDtls                         : False
EnableRtx                          : False
EnableSilkForAudioVideoConferences : False
EnableAVBundling                   : False
EnableServerFecForVideoInterop     : False
EnableReceiveAgc                   : False
EnableDelayStartAudioReceiveStream : False

There is no 
1. EnableSilk
2. AdaptiveBandwith

Can you change accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d1b5f4d-f6bc-df5f-eb7f-dbfde16a8c12
* Version Independent ID: 32115627-278f-a31a-6529-8428138e7e43
* Content: [Set-CsMediaConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csmediaconfiguration?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsMediaConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsMediaConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ivanja81 thanks for your feedback, I created a pull request to propose some changes based on it, you can take a look at it as it is referenced here and, if approved by reviewers, will be merged in a couple of days.
Thank you

**Comment by ivanja81** [comment]
Looks good. Thanks

**Comment by yogkumgit** [comment]
@kenwith Please merge this PR #3667

**Comment by get-itips** [comment]
Hello @yogkumgit please close this one. thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ivanja81 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
