### ISSUE TITLE
Adding Owners

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#3654]
The PowerShell command forces you to add a user to the members list before it can be added as a owner.  The UI in AAD or the M365 admin portal does not enforce this.  This restriction should be removed from PowerShell or it should be documented as to why PowerShell is enforcing this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86af7740-3abd-2245-0141-aa4a484ecbca
* Version Independent ID: db3f5b2e-9978-19ef-3da0-28e9e14bdf76
* Content: [Add-UnifiedGroupLinks (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/add-unifiedgrouplinks?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Add-UnifiedGroupLinks.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Add-UnifiedGroupLinks.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @danmyhre thanks for your feedback.
To propose a change to the behavior of the cmdlet, I need to kindly suggest visit https://office365.uservoice.com/
and I created a pull request, to propose adding a note about adding an user first as a member before making it an owner.
Thank you!

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #3668

**Comment by danmyhre** [comment]
Found an existing UV related to this: 
https://office365.uservoice.com/forums/286611-office-365-groups/suggestions/17893165-addition-and-removal-owner-of-office-365-groups-w

Documentation still needs to be updated until this bug is fixed.

**Comment by get-itips** [comment]
Hello @danmyhre 
Great to hear you found an existing UV for this.
As I commented earlier, I created a pull request to add a note stating the requirement before adding an owner, the behavior is not a bug, since the powershell module is clearly returning a message describing this need.
Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @danmyhre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
