### ISSUE TITLE
PermissionKind Enumeration

### ISSUE THREAD

**Issue by davehax** [MicrosoftDocs/office-docs-powershell#3655]
https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee536458(v%3Doffice.15)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35794b40-f55c-8a71-325a-8075c10bc007
* Version Independent ID: 05ddab16-0ef1-e487-257e-fe27786fbb31
* Content: [Add-PnPRoleDefinition (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnproledefinition?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPRoleDefinition.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPRoleDefinition.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
@yogkumgit Also fix the Example #4 where it has "PS>" in the example.

**Comment by get-itips** [comment]
Hello @davehax thanks for this contribution.
I created a pull request into the Pnp-Powershell repo (you can see it referenced here) to add the provided link to the PermissionKind enum.
It could take some time to be reflected.
Thank you

**Comment by get-itips** [comment]
@yogkumgit PR was merged, you can safely close this thread now. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @davehax Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
