### ISSUE TITLE
Teams: Get-team errors when getting data for partner tenants

### ISSUE THREAD

**Issue by KelvinTegelaar** [MicrosoftDocs/office-docs-powershell#3656]
I've found that since version 1.0 it is no longer possible to use get-team for a different tenant than your own, using the -tenantID or -tenantname option. We are getting the error:

Get-TeamChannel : Error occurred while executing Code: BadRequest Message: Current authenticated context is not valid for this request. This occurs when a request is made to an endpoint that requires user sign-in. For example, /me requires a signed-in user. Acquire a token on
behalf of a user to make requests to these endpoints. Use the OAuth 2.0 authorization code flow for mobile and native apps and the OAuth 2.0 implicit flow for single-page web apps. InnerError: RequestId: 0c58b4ce-6674-45ba-a33a-a204284d7a4f DateTimeStamp: 2019-06-16T19:48:04 HttpStatusCode: BadRequest
The previous version of the module does work when using get-team, but also gives this error on get-teamfunsetting. 

Tried with both credentials, and an AADToken, it seems that as a delegate getting the "funsettings" is not allowed. I believe this is an oversight/bug maybe :)

**Comment by KelvinTegelaar** [comment]
Update: on version 1.1 the error has changed:

n error occurred while fetching team with groupId:{xxx-guid}
Error occurred while executing
Code: GeneralException
Message: userObjectId cannot be null or whitespace.
Parameter name: userObjectId
InnerError:
  RequestId: ec4d3a12-0b1b-465a-ae0b-59ae8db9eac4
  DateTimeStamp: 2019-07-03T11:28:41
HttpStatusCode: GeneralException

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @KelvinTegelaar thanks for your feedback.
As this issue resource is specific to address issues present in documentation, I need to kindly suggest support resources to address your inquiry, either by creating a support ticket in your tenant or visiting https://support.office.com/home/contact

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by KelvinTegelaar** [comment]
The response by Microsoft Support is that they do not give scripting support or support on the cmdlets by modules. aka, hitting a brick wall.

**Comment by KrishnaG-MSFT** [comment]
@KelvinTegelaar Is this issue resolved ? If yes, may i know what was done to resolve it ?

**Comment by KelvinTegelaar** [comment]
The issue is not resolved as Microsoft support stated the cannot support us on the PowerShell module, and have no way of contacting any development team. I expect this issue to just end up unresolved. The issue can remain closed as I am not going to spend any energy on this :)

**Comment by Eric-Fang** [comment]
OK, the problem is still here....
