### ISSUE TITLE
Search-Mailbox should output results to the shell, not to pst

### ISSUE THREAD

**Issue by SHAGGAR** [MicrosoftDocs/office-docs-powershell#3657]
Search-Mailbox sends results to a pst rather than to the shell.  This isn't very useful since the point of using the shell is to manipulate the results via the shell.  

Search-Mailbox should be able to return mail items to the shell as some type of individual mail item object that can be manipulated like any other powershell object.  

This would allow you to do things like export to useful formats like csv, do automated diagnostics on headers, or preview results before using -DeleteContent.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @SHAGGAR 
Thanks for your feedback.
As this issue resource is to address issues currently present in documentation, I need to kindly suggest visit Office 365 User Voice  https://office365.uservoice.com/ to propose that feature request
Thank you

**Comment by yogkumgit** [comment]
@SHAGGAR  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested Please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
