### ISSUE TITLE
Request-SPOPersonalSite UserEmails

### ISSUE THREAD

**Issue by MrDoNotBreak** [MicrosoftDocs/office-docs-powershell#3658]
Hello,
Currently the parameter -UserEmails is a bit misleading. To provision the OneDrive for Business for a user does it not use the UPN (which should be identical to email of course - key word: should be...). So should this parameter not read: -Upns instead ie:

Request-SPOPersonalSite -upns []

Or alternatively it could use -Accounts so it would be more inline with some of the PNP Cmdlets (Get-PNPUserProfileProperty)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @MrDoNotBreak 
Thanks for your feedback.
This issue system is specific to report issues in documentation, for feature requests, I need to kindly redirect you to https://sharepoint.uservoice.com/

Thank you

**Comment by yogkumgit** [comment]
@MrDoNotBreak  Thank you very much for your kind feedback. Considering your valuable feedback, we request you to log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
