### ISSUE TITLE
Published date

### ISSUE THREAD

**Issue by darioca** [MicrosoftDocs/office-docs-powershell#3660]
It would be nice to know when this page was published and when this command has been (or is being, or will be) realeased.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8deb61c-91a1-7e4c-cf56-d682026c6011
* Version Independent ID: 7d8c994d-8673-27dc-04ab-3c5c104c0daa
* Content: [Add-SPOOrgAssetsLibrary (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spoorgassetslibrary?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md)
* Service: **sharepoint-powershell**
* GitHub Login: @maesfaha@microsoft.com
* Microsoft Alias: **maesfaha@microsoft.com**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@Maralesfahanpoor can you help us with the information this user is requesting? thank you

**Comment by Maralesfahanpoor** [comment]
This page was published on 6/20/2019 and we started rolling out to TR(Targeted release) on 6/24.
The feature (and thus, the commands) are at 100% TR with Prod rollout coming soon.

**Comment by kenwith** [comment]
Thanks for the information on TR and also just for the thread and @darioca - the content is all open source on GitHub so anyone can see full history and even make changes. To get to the GitHub source click the Edit button at the top of the article on docs.microsoft.com. That will take you to the GitHub source. Then you can click History and see the history of the article. Here is direct link: https://github.com/MicrosoftDocs/office-docs-powershell/commits/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md

**Comment by hkusulja** [comment]
This is not resolved, the info from published date should be on a page, and still is not...

**Comment by kenwith** [comment]
The engine on docs.microsoft.com does not display the publish date for reference content. I will ask the group that owns the rendering engine again but this was not something they were prioritizing. To see the history of reference content you need to view the GitHub file.

**Comment by darioca** [comment]
In my opinion, users shouldn't have to go to GitHub to see that a page has been published/edited on xx/yy/zzzz.
 
 
    On Tuesday, 16 July 2019, 16:25:07 BST, Ken Withee <notifications@github.com> wrote:  
 
 
The engine on docs.microsoft.com does not display the publish date for reference content. I will ask the group that owns the rendering engine again but this was not something they were prioritizing. To see the history of reference content you need to view the GitHub file.

**Comment by yogkumgit** [comment]
@darioca  it is a good suggestion. Probably you can propose this in Uservoice.  @kenwith thanks for sharing this explanation. @darioca Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by hkusulja** [comment]
@yogkumgit please do not close this ticket, until this docs issue and information on this page is resolved.

**Comment by yogkumgit** [comment]
@kenwith Please advise

**Comment by kenwith** [comment]
Checking with Den who is a PM on the team that owns it. Will report back.

**Comment by rloutlaw** [comment]
I'm the PM owner PowerShell reference experiences. I've opened up a customer suggestion for investigation on this issue for our reference infrastructure. This doesn't mean that we'll do the exact ask (add the date of last commit to the reference page to the docs) without adding additional context on the versions of the PowerShell modules the cmdlets shipped with. The context for the date
