### ISSUE TITLE
"Grant-CsMobilityPolicy -Identity "abc@example.com" -PolicyName $Null" does not work

### ISSUE THREAD

**Issue by VincentCheng-Hatch** [MicrosoftDocs/office-docs-powershell#3661]
Grant-CsMobilityPolicy -Identity "Vincent.Cheng@hatch.com" -PolicyName $Null

does not work. Gives me following error:

This policy must be assigned a value compatible with the user's subscription and location. It cannot be $null.
    + CategoryInfo          : InvalidOperation: (Grant-CsMobilityPolicy:String) [Grant-CsMobilityPolicy], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.Rtc.Management.AD.Cmdlets.AssignOcsMobilityPolicyCmdlet
    + PSComputerName        : admin1a.online.lync.com

------------------
Was looking at the article about he command:
https://docs.microsoft.com/en-us/powershell/module/skype/Grant-CsMobilityPolicy?view=skype-ps

says but apparently it is not working.: 

To unassign a per-user policy previously assigned to a user, set the PolicyName to a null value ($Null):

-PolicyName $Null

----------------

I am able to assign another policy to replace the assigned policy but couldn't find a way to remove a policy from user.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @VincentCheng-Hatch, thank you for your feedback.

It works for me:
![image](https://user-images.githubusercontent.com/33589238/61672482-296aaa80-acc2-11e9-954e-8965484d5128.png)

Where are you trying? SfBO or on-premises?

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and digging deep into it.  @VincentCheng-Hatch We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
