### ISSUE TITLE
Get-pnpUser don;t have batch option to retrive users 

### ISSUE THREAD

**Issue by sachin1981** [MicrosoftDocs/office-docs-powershell#3662]
Get-pnpUser don;t have batch option to retrive users 

if site collection has large number of users above command throwing timer out error 

like in get list there is  option get data into batches can we include similar feature in this  command as well

**Comment by sachin1981** [comment]
we use below command to increase timeout  but it will make big call to sharepoint 
$context.Requesttime ='5000*10000 
i would suggest batch option for his command

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sachin1981 
Thanks for your feedback.
This issue resource is specifically to report issues in documentation.
For feature requests, as PnP Powershell is community-driven you will need to propose that idea starting to look here https://docs.microsoft.com/en-us/sharepoint/dev/community/community
Thank you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @sachin1981 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
