### ISSUE TITLE
Clear-PnPRecycleBinItem Fails Because of List View Threshold

### ISSUE THREAD

**Issue by gunnerman1** [MicrosoftDocs/office-docs-powershell#3672]
When using commands such as `Clear-PnPRecycleBinItem` or `Get-PnPRecycleBinItem`, the command fails if there are more than 5000 items in the recycle bin with error:
```
Clear-PnPRecycleBinItem : The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator.
At line:8 char:1
+ Clear-PnPRecycleBinItem -All -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Clear-PnPRecycleBinItem], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.RecycleBin.ClearRecycleBinItem
```

Currently, there is no way to limit the number of items requested to get around this. 

I have tried suggested commands such as `Clear-PnPRecycleBinItem -All -Force | select -last 50` however, this command is not expected to work nor does it because it is of course making the request before processing the selection.

This is problematic because it seems the recycle bin cannot be emptied, even from the SharePoint Settings web portal when the number of items is large.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @gunnerman1 
Thanks for your feedback.
This issue resource is specifically to report issues in documentation.
For feature requests or bug reports, as PnP Powershell is community-driven you will need to propose that idea/submit that bug starting to look here https://docs.microsoft.com/en-us/sharepoint/dev/community/community
Thank you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @gunnerman1 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
