### ISSUE TITLE
Addhour? Example 1

### ISSUE THREAD

**Issue by RaghuramP** [MicrosoftDocs/office-docs-powershell#3674]
In Example 1 Addhour is mentioned, this should be Addhours..

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @RaghuramP, thank you for your feedback.

Could you please let us know what is the article you are reference?

**Comment by RaghuramP** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteContentMove.md
Example 1

-Raghu

________________________________

**Comment by yogkumgit** [comment]
@trent-green please merge the PR #3739

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @RaghuramP Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
