### ISSUE TITLE
PowerShell modules NOT installed

### ISSUE THREAD

**Issue by vaderj** [MicrosoftDocs/office-docs-powershell#3681]
"After installing SPMT, the PowerShell dlls are copied to %userprofile%\Documents\WindowsPowerShell\Modules."

But there was no modules folder in my "WindowsPowerShell" folder, so I created it and reinstalled, but still - no PowerShell module.  Is the PowerShell module no longer supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05e3922b-d403-c2d9-a4fd-febebc1e19e0
* Version Independent ID: 2beef352-a396-6211-23d6-59d5e7fe0afd
* Content: [SharePoint Migration Tool](https://docs.microsoft.com/en-us/powershell/module/spmt/?view=spmt-ps#feedback)
* Content Source: [spmt/spmt-ps/spmt/spmt.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/spmt/spmt-ps/spmt/spmt.md)
* Service: **spmt-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @vaderj 
Thanks for your feedback, I can confirm that the modules are installed in the location specified in the documentation

![image](https://user-images.githubusercontent.com/36666927/61406694-97196f80-a899-11e9-9423-5d5914d7dcaa.png)

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @vaderj 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by jasonwbaxter** [comment]
There was a useful tip which helped me overcome this issue is to copy the Windows Powershell Folder into OneDrive--> My documents , Think that this should be a sticky post.
