### ISSUE TITLE
Typo - Restore

### ISSUE THREAD

**Issue by bhanuchintha** [MicrosoftDocs/office-docs-powershell#3684]
Team, 

Instead of Restore keyword, you have used Reset at many places in this page. Can you please take care.

Thanks & Regards,
Bhanu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c22f4a4-0cf2-48f7-3fbd-1b2b556be3e7
* Version Independent ID: 3c66eb02-9056-be8c-30e4-1049bf5ad8b8
* Content: [Restore-PnPTenantRecycleBinItem (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/restore-pnptenantrecyclebinitem?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Restore-PnPTenantRecycleBinItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Restore-PnPTenantRecycleBinItem.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @bhanuchintha thanks for your feedback.
I created a pull request to correct the documentation.
Thank you

**Comment by bhanuchintha** [comment]
Thanks @get-itips

**Comment by get-itips** [comment]
@yogkumgit PR was merged, you can safely close this thread now. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @bhanuchintha Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
