### ISSUE TITLE
Determine relation between EventType and Actions

### ISSUE THREAD

**Issue by sub2d** [MicrosoftDocs/office-docs-powershell#3686]
With this cmdlet one can list EventType and Actions but no way to determine which actions are related EventType and vice versa.

One could guess by browsing trough cmdlets "Get-MailDetail&lt;report type&gt;Report"
Get-MailDetailATPReport          
Get-MailDetailDlpPolicyReport    
Get-MailDetailMalwareReport      
Get-MailDetailReport             
Get-MailDetailSpamReport         
Get-MailDetailTransportRuleReport

Without relations this cmdlet is useless, with relations it would be great source of information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e7c9124-46d3-a451-8577-eafe3c2b015e
* Version Independent ID: 567a724c-4041-b0be-bf22-a6ea6a8e524f
* Content: [Get-MailFilterListReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/reporting/get-mailfilterlistreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/reporting/Get-MailFilterListReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/reporting/Get-MailFilterListReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @sub2d, thank you for your feedback.

We are here to help you to improve docs.microsoft.com. I think it's more like a feature change or request. In this case I recommend:

**Comment by yogkumgit** [comment]
@sub2d  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
