### ISSUE TITLE
Useroverride does not work with anonymous unless you use LineUri

### ISSUE THREAD

**Issue by dstowers73** [MicrosoftDocs/office-docs-powershell#3690]
The user will not have the ability to toggle anonymous on and off even with EnableUserOverride set unless you use the Lineuri (or likely service option).  It -will not- work if you set it to anonymous.  If you do that you always want it on anonymous and ignores the EnableUserOverride.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a73df595-25dd-4c21-a0b4-52e69c0d3405
* Version Independent ID: d35f0a4f-897a-1d8d-f2be-be8b12f2350f
* Content: [Set-CsCallingLineIdentity (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Set-CsCallingLineIdentity?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsCallingLineIdentity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsCallingLineIdentity.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @dstowers73, thank you for your feedback.

Sorry for the delay. I have tried this and it works:

![image](https://user-images.githubusercontent.com/33589238/62905220-e68b7800-bd3f-11e9-98b5-a9eb8570b97f.png)

![image](https://user-images.githubusercontent.com/33589238/62905249-028f1980-bd40-11e9-9f4b-dc9557ca73be.png)

**Comment by dariomws306** [comment]
![image](https://user-images.githubusercontent.com/33589238/62905354-85b06f80-bd40-11e9-8c19-d4a98d1ddf2f.png)

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @dstowers73 Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
