### ISSUE TITLE
Example 1 incorrect?

### ISSUE THREAD

**Issue by Jazpuk** [MicrosoftDocs/office-docs-powershell#3691]
Should example 1 above have $true at the end?  Description seems to state that we are enabling transcription for this group. By having it as $false this would disable it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f74481ed-c034-046f-2d45-23096b4dce9b
* Version Independent ID: 7a7a44a1-e01e-da96-d1a0-a876487dcb4c
* Content: [New-CsTeamsMeetingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith  Please merge the PR #3732

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @Jazpuk Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
