### ISSUE TITLE
Missing info about OrgAssetType

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/office-docs-powershell#3692]
There is a property OrgAssetType which can be also OfficeTemplateLibrary, ImageDocumentLibrary

Please update the docs and describe values and intended use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8deb61c-91a1-7e4c-cf56-d682026c6011
* Version Independent ID: 7d8c994d-8673-27dc-04ab-3c5c104c0daa
* Content: [Add-SPOOrgAssetsLibrary (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spoorgassetslibrary?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md)
* Service: **sharepoint-powershell**
* GitHub Login: @maesfaha@microsoft.com
* Microsoft Alias: **maesfaha@microsoft.com**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Maralesfahanpoor can we add the information about OrgAssetType parameter the user is talking about to this article? I could verify that, at least with version 16.0.9021.0 of Powershell module.

**Comment by Maralesfahanpoor** [comment]
Hello, We will update the Documentation ASAP, 
Until then, OrgAssetType indicates the type of document library in Organization Assets and for now, ImageDocumentLibrary is the only supported value and It will be set by default.

**Comment by get-itips** [comment]
Hello, as the author @Maralesfahanpoor has replied and the documentation for the parameter is coming soon, we will proceed closing this one for now. @yogkumgit

**Comment by hkusulja** [comment]
@get-itips , sorry, how can you close this github issue, when something is in production, but not documented still..., when it will be documented, than it can be closed.

**Comment by get-itips** [comment]
@hkusulja as the author of the article explained, default value is the only supported value, meaning that if you do not specify anything, that will be used, so it is not in production (at least, not fully) but if you do not agree :) , it is ultimately @Maralesfahanpoor and @yogkumgit call.
Thanks.

**Comment by yogkumgit** [comment]
@Maralesfahanpoor can you propose by when this documentation can be updated?

**Comment by Maralesfahanpoor** [comment]
In one week.

**Comment by get-itips** [comment]
Hello @hkusulja documentation has been updated by @Maralesfahanpoor we will proceed closing this.
Thank you both

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and giving this confirmation. @hkusulja 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
