### ISSUE TITLE
Guest Users

### ISSUE THREAD

**Issue by walkerk77** [MicrosoftDocs/office-docs-powershell#3693]
Guest users are now available in Teams.  The Add-TeamUser command only works for tenant addresses.  Request the ability to add guest members via PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da0c53f2-1c62-14f6-6371-f54bf86b0c24
* Version Independent ID: aac162db-a9c0-fbfb-dd40-526e94d3bef8
* Content: [Add-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/Add-TeamUser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by get-itips** [comment]
Hello @walkerk77 thanks for your feedback, although this issue resource is specifically to report issues in current documentation, for feature requests, I need to kindly suggest visit the Microsoft Teams User Voice here https://microsoftteams.uservoice.com/forums/555103-public
Thank you

**Comment by yogkumgit** [comment]
@walkerk77  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
