### ISSUE TITLE
New-PnpSite - Group not Site Collection

### ISSUE THREAD

**Issue by sohailmerchant** [MicrosoftDocs/office-docs-powershell#3700]
The documentation needs to be updated.  -Alias and -Url feedback has already been noted, but this command create a Office 365 Group not a site collection 'Creates a new site collection'.  This makes it confusing with cmdlet 'New-PnPUnifiedGroup'

It would be good to cross link the cmdlet which create a modern site collection.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sohailmerchant 
Thanks for your feedback.
Your issue report is missing the article reference, so it seems you created this issue directly in the repo.
Can you reference the article you think needs to be updated?
I am assuming you refer to the [New-PnpSite article](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpsite) 

Using the last version of the PnP Powershell I could use it to create a site, as the documentation says.

Please tell me if I understood ok.
Thank you

**Comment by get-itips** [comment]
Hello @sohailmerchant how are you? Reaching back to you to know if you could see my comment, otherwise we will proceed closing this one.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @sohailmerchant We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by sohailmerchant** [comment]
Sorry for not responding earlier.  Here is the link for the docs: https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpsite

The cmdlet New-PnpSite create modern group site and New-PnPTenantSite create a classic site. So the docs is not correct.

I have a latest version of PNP PowerShell installed i.e. 3.12.

Thanks

**Comment by get-itips** [comment]
I am sorry @sohailmerchant but I am confused
In the first message you say that the New-PnpSite creates an Office 365 Group not a SC.
In the last message you say that the cmdlet creates a Modern Site and New-PnpTenantSite creates a classic one, this is stated in the document:

> The New-PnPSite cmdlet creates a new site collection for the current tenant. Currently only 'modern' sites like Communication Site and the Modern Team Site are supported. If you want to create a classic site, use New-PnPTenantSite.

Please kindly clarify what you see is wrong with the documentation.

**Comment by sohailmerchant** [comment]
I am sorry for causing confusion.  My point was that New-pnpsite creates office 365 group not a modern site collection.  When you will create a site using this cmdlet you will see its says on top 'private group' and 'conversation' link which has mailbox attached.  If we create a modern site collection/team site there is no mailbox attached it is just a site.  Hope this make sense.

**Comment by get-itips** [comment]
Hello @sohailmerchant 
Thanks for your clarification.
This is what I did

_Created a Modern/Team Site using the New-PnpSite cmdlet
Created a Modern/Team Site using the UI_

both resulted in

_Team Site with "Private Group" label
Mailboxes were created for both_

Please correct me if I am wrong, but I identified no difference between the UI and Powershell.

Thank you

**Comment by sohailmerchant** [comment]
This is a correct behavior and this what I was trying to highlight i.e. it creates a 'Private Group' not just a modern team site.  There is label 'Private Group' and you will also see 'Conversation' link on the left navigation on the site.   The cmdlet page says on top that 'Creates a new site collection' which I believe is incorrect since it is creating a group like the cmdlet `New-PnpUnifiedGroup`

The cmdlet `New-PnPTenantSite` when I used it yesterday it created only classic site collection but when I used it today with all the parameters required it created a modern team site (not a group, no private group label nor conservation link).

The following three cmdlets documentation needs to be reviewed in my opinion as it is very confusing.
New-PnpTenantSite
New-PnpUnifiedGroup
New-PnpSite

Happy to speak on phone / skype if it is easier.

**Comment by get-itips** [comment]
Ok understood.
I'll create a pull request in the PnP-Powershell repo to propose changing some wording and cross link here.
If it gets approved by the PnP team, it will get reflected.
Thanks

**Comment by yogkumgit** [comment]
@erwinvanhunen Kindly merge the PR: Changing some wording about what is being created #2211

**Comment by yogkumgit** [comment]
@erwinvanhunen humbly request you please merge this PR and help us to resolve this issue.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @erwinvanhunen thanks for merging this PR. @sohailmerchant Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
