### ISSUE TITLE
Enhance Set-PnPSite -LockState with ReadOnly

### ISSUE THREAD

**Issue by kasperbolarsen** [MicrosoftDocs/office-docs-powershell#3701]
[Enter feedback here]
Related to #3392 : it would be very nice if Set-PnPSite -LockState would be able to handle "ReadOnly" :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2961cab8-c2d4-e90b-6d78-666a4dc16823
* Version Independent ID: d9e27a2c-8408-95ba-6d88-46e63fe878a1
* Content: [Set-PnPSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsite?view=sharepoint-ps#)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @kasperbolarsen 
Thanks for your feedback, although this issue system is to report issues in documentation, to propose new features, I kindly redirect you to this resource: https://docs.microsoft.com/en-us/sharepoint/dev/community/community as a start.

Thank you

**Comment by kasperbolarsen** [comment]
Thanks, but I have a very hard time finding any "suggest feature/enhancement" link there. Can you help me out?

**Comment by get-itips** [comment]
The link I provided has a link to the uservoice section for Sharepoint Dev 

https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform

Hope is useful to you.

**Comment by kasperbolarsen** [comment]
Should PnP specific enhancements be requested there? The Spo version already has the ReadOnly option but the PnP version does not

**Comment by get-itips** [comment]
> Should PnP specific enhancements be requested there? The Spo version already has the ReadOnly option but the PnP version does not

Yes, It is linked from the PnP resources.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @kasperbolarsen 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
