### ISSUE TITLE
Add -Archive parameter to Set-Team

### ISSUE THREAD

**Issue by makorus** [MicrosoftDocs/office-docs-powershell#3707]
Please add the ability to archive a specific group via PowerShell.

As of now, we can use the Graph REST API to archive a group (see: https://docs.microsoft.com/en-us/graph/api/team-archive?view=graph-rest-1.0).

This is rather inconvenient, considering the fact that we use an extremely complex PowerShell script to manage all our teams.

Example:
Set-Team -GroupId <insert-group-ID-here> -Archived $true

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by makorus** [comment]
Bump

**Comment by get-itips** [comment]
Hello @makorus thanks for your feedback, although this issue resource is specifically to report issues in documentation, not feature requests, so I kindly need to redirect you to https://microsoftteams.uservoice.com

Thank you

**Comment by yogkumgit** [comment]
@makorus  Thank you very much for your kind feedback. Considering your valuable feedback, as suggested please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
