### ISSUE TITLE
URL trace

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/office-docs-powershell#3734]
Why not making this article complete by explaining that URL trace can be simply run from the Exchange Admin Center (the GUI). Most customers are happier with using the GUI compared to powershell.
There is AFAIK no article explaining how to run a URL trace from the EAC which I think should have a higher priority than doing this from powershell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5522e1-7041-205a-7a97-1622118d9d58
* Version Independent ID: 0e5702db-abe5-9172-cab6-676952313b66
* Content: [Get-UrlTrace (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/get-urltrace?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Get-UrlTrace.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Get-UrlTrace.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@JeroenDronkers, this topic and the 1200+ around it are cmdlet reference topics for Exchange-related PowerShell. These are the same topics that are used for `Get-Help <CmdletName>` at the command line (although the topics on the web will always be more up-to-date).

The Get-UrlTrace topic isn't meant to be a "here's how you use URL trace" conceptual or procedural topic; it merely documents the available settings on the cmdlet.

There doesn't appear to be any existing conceptual/procedural content for using URL trace. Is that what you're asking for? I searched for "exchange online url trace" in Bing and Google, and this cmdlet reference topic was the number one result.

**Comment by JeroenDronkers** [comment]
Hello, Yes I was indeed asking for an article that explains conceptual/procedure for using URL trace. Customers would appreciate that more I believe then just a powershell reference.
Thanks

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and sharing this explanation. @JeroenDronkers 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot as
