### ISSUE TITLE
SPMT logon to GCC High When passing SPOCredential

### ISSUE THREAD

**Issue by davemedvitz** [MicrosoftDocs/office-docs-powershell#3735]
When passing SPOCredential to Register-SPMTMigration, with my tenant in GCC High, I continually get logon errors as follows:

Microsoft.SharePoint.MigrationTool.MigrationLib.Common.AADAuthenticationException: unknown_user_type: Unknown User Type ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: unknown_user_type: Unknown User Type

The tool runs successfully when not trying to pass credentials (no -SPOCredential switch) and entering them when prompted.

This is necessary to script/automate some large data migrations.

Thanks
Dave

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 176873a5-a509-6337-0aa9-7db8ead2e863
* Version Independent ID: 73bb0f00-1909-6eb1-3a8c-247149480c9a
* Content: [Register-SPMTMigration (spmt)](https://docs.microsoft.com/en-us/powershell/module/spmt/register-spmtmigration?view=spmt-ps#feedback)
* Content Source: [spmt/spmt-ps/spmt/Register-SPMTMigration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/spmt/spmt-ps/spmt/Register-SPMTMigration.md)
* Service: **spmt-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @davemedvitz  thanks for your feedback, however this issue resource is specifically to report issues in documentation, not issues or potential bugs, as that is to be handled by support services, so I need to kindly redirect you to https://support.office.com/ or create a support ticket directly on your tenant.

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @davemedvitz 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution.

**Comment by yogkumgit** [comment]
@officedocsbot close
