### ISSUE TITLE
Change order of Address Book Policy on exchange online.

### ISSUE THREAD

**Issue by tonghien22890** [MicrosoftDocs/office-docs-powershell#3742]
May i change order of address list in Address Book Policy on exchange online?
May i set OfflineAddressBook in Address Book Policy to null or remove it or change display name of it on Address Book Policy?

**Comment by saeidshoar** [comment]
> آیا می توانم سفارش لیست لیست را در خط مشی کتاب آدرس در تبادل آنلاین تغییر دهم؟ 
> آیا می توانم Ad-AddressAddressBook را در خط مشی کتاب آدرس تنظیم کنم تا آن را حذف یا حذف کنم یا تغییر نام آن در خط مشی کتاب آدرس؟

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tonghien22890 how are you?
I could not understand your issue report, is anything wrong that you see in documentation that you think needs to be corrected? IF you are looking for support, I need to kindly redirect you to https://support.microsoft.com/en-us
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @tonghien22890 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
