### ISSUE TITLE
Example 1

### ISSUE THREAD

**Issue by 4rtorias** [MicrosoftDocs/office-docs-powershell#3744]
Example 1 specifies -SafeAttachmentsPolicy instead of -SafeLinksPolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1b351a5-e978-5105-f187-85cd1558c43b
* Version Independent ID: e83ad526-e84e-e4cd-b622-af4bd4a8044c
* Content: [New-SafeLinksRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/new-safelinksrule?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/New-SafeLinksRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/New-SafeLinksRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @4rtorias thanks for your feedback, I created a pull request to correct the article based on your finding, thank you

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #3761

**Comment by yogkumgit** [comment]
@chrisda Humble reminder Please merge the PR #3761

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @4rtorias Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
