### ISSUE TITLE
Number of results

### ISSUE THREAD

**Issue by bilginbaldji** [MicrosoftDocs/office-docs-powershell#3745]
The command returns only 100 results if a larger number is not specified via -First parameter. The information for the default behaviour is missing in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4504ef6f-28cd-bf4e-bf26-02a0acf292b8
* Version Independent ID: 7a12f628-6004-f100-4112-a95f4d4df8ff
* Content: [Get-CsOnlineDialInConferencingUserInfo (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguserinfo?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialInConferencingUserInfo.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUserInfo.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tomkau can you confirm this limitation? Thank you!

**Comment by get-itips** [comment]
Hello @tomkau can you kindly help us to confirm this limitation? Thank you!

**Comment by tomkau** [comment]
Hello @get-itips-- I reviewed the code and can confirm that 100 is the default value for the -First parameter if not specified

**Comment by get-itips** [comment]
Thanks @tomkau will create a pull request to reflect this. Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @bilginbaldji Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
