### ISSUE TITLE
Missing parameter SetAssociatedGroup

### ISSUE THREAD

**Issue by hosebei** [MicrosoftDocs/office-docs-powershell#3746]
When I'm using the New-PnpGroup cmdlet, I do have an Parameter named "-SetAssociatedGroup". But i can't find that on this page? Could please update, or direct me where I can find information about this Parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44489c78-274c-2c09-cd51-16f6ed183317
* Version Independent ID: eadbb80c-20fb-9bec-a996-325762c315d4
* Content: [New-PnPGroup (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpgroup?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPGroup.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @hosebei thanks for your feedback.
The parameter you are looking for is obsolete, if you look at the source code of the cmdlet: 

`        [Parameter(Mandatory = false)] // Not promoted to use anymore. Use Set-PnPGroup `
`        [Obsolete("Use Set-PnPGroup.")] `
 `       public AssociatedGroupType SetAssociatedGroup = AssociatedGroupType.No `

You will notice what is recommended to use instead.

Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @hosebei 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by John471** [comment]
Paramater -DisallowMembersViewMembership
This seems confusing. In the UI there is no option to disallow Members from viewing the membership of the group. Rather, there are two options for who is allowed to view membership 1) *Only* Group Members 2) Everyone. Please clarify what this parameter does and how to use it. "DisallowMembersViewMembership" is highly un-intuitive.
