### ISSUE TITLE
Certain include parameters require full control access rather than just read

### ISSUE THREAD

**Issue by Hannes-Git** [MicrosoftDocs/office-docs-powershell#3747]
When trying to get a PnPWeb, certain parameters require the PnPConnection (ie using AppID/AppSecret to have Full Control right (<AppPermissionRequests AllowAppOnlyPolicy="true">) rather than just read, which is an issue for a pure reporting scenario. 

Ie With read-only access, Get-PnPWeb -Includes RequestAccessEmail, UseAccessRequestDefault results in an Get-PnPWeb : Access denied. You do not have permission to perform this action or access this resource.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Hannes-Git 
Thanks for your feedback.
This issue resource is specifically to report issues in documentation.
PnP cmdlets are community-driven, so to report bugs, issues and feature requests, the resource to start is https://docs.microsoft.com/en-us/sharepoint/dev/community/community

Hope this info helps you.

**Comment by get-itips** [comment]
Another option @Hannes-Git 

Create an issue here https://github.com/SharePoint/PnP-PowerShell/issues

with full and complete information of what you experienced.

Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Hannes-Git 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
