### ISSUE TITLE
EOP SA powershell endpoint

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/office-docs-powershell#3749]
The EOP Stand Alone powershell endpoint mentioned in this article is incorrect. Using the above will fail. The correct endpoint is:
 https://ps.protection.outlook.de/powershell-liveid/
The article should mention that for EOP SA this (old) endpoint should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5aa434-8ccb-43a3-3f3b-f400e4663b2f
* Version Independent ID: 8a7187a1-fe53-6bf0-b517-6225c8cb3233
* Content: [Connect to Exchange Online Protection PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-eop/connect-to-exchange-online-protection-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-eop/connect-to-exchange-online-protection-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-eop/connect-to-exchange-online-protection-powershell.md)
* Service: **eop**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @JeroenDronkers 
Thanks for your feedback.

I tested the EOP Stand Alone endpoint currently in the article and I could successfully connect, and I noticed that you shared a .de link, are you using Office 365 for Germany?

**Comment by JeroenDronkers** [comment]
Hello
The endpoint mentioned in the article is for the Security & Compliance Center. It is not the endpoint for  Exchange Online Protection (EOP Stand Alone) which is https://ps.protection.outlook.de/powershell-liveid/
Basically the title of the article is incorrect. This should be "Connect to Sec. & Compl. Center by powershell.

Hope that clarifies...
Thanks

**Comment by chrisda** [comment]
@JeroenDronkers, the value https://ps.protection.outlook.de/powershell-liveid/ is already called out as the _ConnectionUri_ value for Office 365 Germany in Step 2 (in the **Note**).

It looks like [this commit](https://github.com/MicrosoftDocs/office-docs-powershell/commit/f8d23301a2fae83c338b9650bd10f155e2411b41#diff-5975c4aa2161f13e96d789e19461aca2) back in April changed the main _ConnectionUri_ value from https://ps.protection.outlook.com/powershell-liveid/ to https://ps.**compliance**.protection.outlook.com/powershell-liveid/ in Step 2.

I'll change it back to https://ps.protection.outlook.com/powershell-liveid/ (I had my doubts about that April change, anyway...).

Thanks for the feedback.
