### ISSUE TITLE
Specify a document library?

### ISSUE THREAD

**Issue by hvandesa** [MicrosoftDocs/office-docs-powershell#3756]
Is there a way to specify the Document Library similar to SetAuditReportStorageLocation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce3e7e39-d315-4843-4af4-57c5040d509f
* Version Independent ID: 7e61202d-4b8c-3018-b161-f99890cc7724
* Content: [Set-PnPAuditing (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpauditing?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPAuditing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPAuditing.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @hvandesa 
Thanks for your feedback.
This issue system is specifically to report issues in documentation.
Said that, PnP cmdlets are community-driven, if you have an idea that could be a feature request, you can start looking here https://docs.microsoft.com/en-us/sharepoint/dev/community/community 

I looked into this cmdlet's source code and it is not possible. https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Site/SetAuditing.cs

Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @hvandesa 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
