### ISSUE TITLE
RequireIntune parameter

### ISSUE THREAD

**Issue by LeoW-MS** [MicrosoftDocs/office-docs-powershell#3760]
In the command description, it says the switch RequireIntune is not applicable to Skype for Business Online.  Yet in the switch description for RequireIntune  it say Applies to: Skype for Business Online
Which of the two is correct? 

Also the description of the parameter is missing.

The following parameters are **not applicable to Skype for Business Online**: AllowAutomaticPstnFallback, AllowCustomerExperienceImprovementProgram, AllowExchangeConnectivity, AllowSaveCallLogs, AsJob, Description, EncryptAppData, Force, Identity, Instance, PipelineVariable, **RequireIntune**, Tenant, VoiceSettings

-**RequireIntune** 
{{Fill RequireIntune Description}}
Type: | Boolean
Position: | Named
Default value: | None
Accept pipeline input: | False
Accept wildcard characters: | False
Applies to: | **Skype for Business Online**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6649dcf4-56ce-60d9-9686-f7757d3a84f7
* Version Independent ID: 9363269d-d208-ff75-55d3-dbcd9224a1b4
* Content: [Set-CsMobilityPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csmobilitypolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsMobilityPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsMobilityPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tomkau Can we confirm the description for the mentioned parameter? Thank you

**Comment by get-itips** [comment]
Hello @tomkau Can you kindly confirm the description for the mentioned parameter and if it is onprem only? Thank you

**Comment by get-itips** [comment]
Hello @tomkau Did you have chance to review my comment? Thank you

**Comment by tomkau** [comment]
@get-itips  Checked the code and the parameter does not apply to online

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @LeoW-MS Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
