### ISSUE TITLE
add-unifiedgrouplinks skipping users due to error

### ISSUE THREAD

**Issue by nhoj01** [MicrosoftDocs/office-docs-powershell#3762]
Hello:

I seem to be running into an issue when using **Add-UnifiedGroupLinks** to to add members to a group. The command works if the group member names are all correct, however if one of the group member names is incorrect, all the members from that group are skipped as opposed to just the user id that's incorrect.

So for the sample listed below
group1 has an incorrect id _member3.com#EXT#_ all members are skipped
group2 has no incorrect ids all members are added correctly. 

command I am running:

$groups = Import-Csv -Path C:\temp\groupinfo_0729.csv
**csvfile**
name,members
group1, id1 id2 id3.com#EXT#
group2, id1 id2

$groups | ForEach-Object {Add-UnifiedGroupLinks -Identity $_.name -LinkType Members -Links $_.members.split()}

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @nhoj01 
Thanks for your feedback.
This issue system is specifically to report issues in documentation.
Your report seems more suitable for support services, kindly open a support ticket on your tenant.
Also if the cmdlet's behavior is that, you can always propose a change thru https://office365.uservoice.com/
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @nhoj01  Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution.
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

https://docs.microsoft.com/office365/admin/contact-support-for-business-products

**Comment by yogkumgit** [comment]
@officedocsbot close
