### ISSUE TITLE
new-unifiedgroup cmd does not create SharePoint

### ISSUE THREAD

**Issue by nhoj01** [MicrosoftDocs/office-docs-powershell#3765]
Hello:

I used the new-unified group command to bulk create several Office 365 groups for a tenant to tenant migration. 

The command created the groups but lo and behold it did not create the SharePoint sites. This is not mentioned  in the documentation. Is this the intended behavior? Does the command just create the group and none of the associated services?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @nhoj01 
Thanks for your feedback.
I could verify what exactly you describe, but essentially, the documentation does not says that it will create Sharepoint site groups or any associated services, so I do not see there anything to change.
You could also explore creating the group using Microsoft Graph to see if the Sharepoint Site is created along.
Hope this info helps you.

**Comment by nhoj01** [comment]
Hello @get-itips

My reason for using that command is as I mentioned because I am doing a tenant to tenant migration and needed to bulk create office 365 groups which I presumed would also create the SharePoint sites since when you create a office 365 group in the gui it creates a sharepoint site. 

But I guess that was my mistake, thanks for your feedback.
