### ISSUE TITLE
-WindowsAuthentication $true x 2

### ISSUE THREAD

**Issue by Wallace4444** [MicrosoftDocs/office-docs-powershell#3769]
The section for -WindowsAuthentication states $true twice. Second row should be $false I imagine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be262e6d-2342-9d63-e807-ad931f15b847
* Version Independent ID: b20464e1-8659-1d1c-5010-c73526f440ca
* Content: [Set-OwaVirtualDirectory (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access-servers/set-owavirtualdirectory?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/client-access-servers/Set-OwaVirtualDirectory.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access-servers/Set-OwaVirtualDirectory.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Wallace4444 
Thanks for your feedback, based on it, I'll create a pull request to correct the article.
Thank you

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #3786

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Wallace4444 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
