### ISSUE TITLE
Move-CsUser document missing the -MoveConferenceData parameter

### ISSUE THREAD

**Issue by NebulaMillennium** [MicrosoftDocs/office-docs-powershell#3773]
The document for Move-CsUser is missing the -MoveConferenceData parameter. This parameter can be found in PowerShell itself:

PS C:\Users\Johnny> help move-csuser -Parameter moveconferencedata

-MoveConferenceData <SwitchParameter>
    When present, moves meeting and conference data for users being transferred to a different Registrar pool. Note that you should not use the MoveConferenceData parameter if you are
    moving users as part of a disaster recovery procedure. Instead, you should rely on the backup service for moving conference data as part of a disaster recovery procedure.

    Required?                    false
    Position?                    Named
    Default value
    Accept pipeline input?       False
    Accept wildcard characters?  false

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@bjwhalen Hello, I tracked down the history of Move-CsUser documentation and I saw that you are the author of the [pull request](https://github.com/MicrosoftDocs/office-docs-powershell/pull/1231) that removed the MoveConferenceData parameter from the article, can you kindly clarify what was the reason behind that? I tested in SfB 2019 and the parameter is still there.
Thanks for clarifying this.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @NebulaMillennium We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by NebulaMillennium** [comment]
@yogkumgit This issue is not resolved. It appears @get-itips asked @bjwhalen for info on why the -MoveConferenceData parameter was removed from the documentation. I do not see an answer from @bjwhalen and the parameter is still missing from the document at https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps

Why did you close the request? Can you please reopen it until it is resolved?

**Comment by yogkumgit** [comment]
@NebulaMillennium Yes you are right. Apologies. This is mistakenly done by me. Thanks for correction.

**Comment by yogkumgit** [comment]
@bjwhalen please reply to @get-itips query and kindly help.

**Comment by get-itips** [comment]
Hello @NebulaMillennium thanks for your feedback.
We could finally get information about why it was missing, I created a pull request to add it back with some notes, if it is approved, it will go on the live version.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @NebulaMillennium Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
