### ISSUE TITLE
Get-Team fetches Team by -GroupId in 5 secs but takes 3 to 5 minutes with -MailNickName

### ISSUE THREAD

**Issue by FedeFigueredo** [MicrosoftDocs/office-docs-powershell#3775]
Hi! I would like to know if its normal for this command to take only 4 secs to fetch a Team from server when GroupId parameter is used, and about 3 to 5 minutes (!) to fetch it when -MailNickName parameter is used. I´m working with clients with massive records of Microsoft Teams and they can provide me only display name or mailNickName. Causing a really slow script that takes more time than a human to complete its tasks. Does the search algorithim searches for teams with this -MailNickName in ALL the teams of the world? Or it only searches in the teams within the organization where the autenthicated user belongs?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @FedeFigueredo Thanks for your feedback.
This issue system is specifically to report issues currently present in documentation, for feature requets, bug reports or in this case, support (that could lead to a bug report) I need to kindly redirect you to creating a support ticket directly on your tenant using the Office 365 admin panel.
Hope this information gets you in the right direction to answer your query.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @FedeFigueredo 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution.

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

Link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by FedeFigueredo** [comment]
Thanks for your reply! I will consult with my Tenant. Greetings
