### ISSUE TITLE
Connect-PnPOnline using AppID and AppSecret is not working in Azure Automation Runbook

### ISSUE THREAD

**Issue by Veeraramkumar** [MicrosoftDocs/office-docs-powershell#3779]
When I tried to use the below PS command to access the Sharepoint site from my local machine, it executed successfully.
Connect-PnPOnline -AppId '83afc512-acad-4934-9745-2e79a00725e0' -AppSecret '8wyeC3I4Kd1D8iEVtk5JKPYYjjmw5oGv7Jzcw9GLi7M=' -Url $siteUrl

But when I tried to use the same command in Azure Automation Runbooks,
 it fails.
Fail in the sense, stream got suspended after 3 attempts
![PSIssue](https://user-images.githubusercontent.com/19631175/62226421-d38bb600-b3d7-11e9-9947-936959c8e358.PNG)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Veeraramkumar Thanks for your feedback.

This issue resource is specifically to address issues on documentation, as you might know, PnP cmdlets are community-driven, so I need to kindly ask you to suggest this inquiry to the community, as it seems you need support on your situation, please start looking here https://docs.microsoft.com/en-us/sharepoint/dev/community/community

Thank you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Veeraramkumar 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please initiate query in community and follow there for the resolution.
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
