### ISSUE TITLE
Whats the magic formula to get this command to run?!

### ISSUE THREAD

**Issue by CaseyRoot** [MicrosoftDocs/office-docs-powershell#3784]
I was able to run this command without a hitch in my sandbox environment.  Now I am trying to run in production and keep running into errors.  First one - unauthorized.  Gave the account global admin access.  Try again - next error.  You do not have access.  Not sure what is going on and at this point I rebuild my site design.  Next error - File Not Found.  What does file not found mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d2946aa-f7cb-e211-75d3-e8fa432a3aed
* Version Independent ID: 60554dbd-1fb6-2603-64df-bc4e0a0fb233
* Content: [Invoke-PnPSiteDesign (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/invoke-pnpsitedesign?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Invoke-PnPSiteDesign.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Invoke-PnPSiteDesign.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @CaseyRoot 
Thanks for your feedback, digging a little in the documentation for PnP cmdlets I could find this:

 
>Add-PnPSiteDesignTask
This command is intended to replace Invoke-PnPSiteDesign and is useful when you need to apply a large number of actions or multiple site scripts.

[Source](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpsitedesigntask?view=sharepoint-ps)

If you still have issues after trying with that other cmdlet, please take into account that this issue resource is specifically to address issues on documentation, as you might know, PnP cmdlets are community-driven, so you will need to start looking here https://docs.microsoft.com/en-us/sharepoint/dev/community/community to look for support and help from the community.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @CaseyRoot 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
