### ISSUE TITLE
details on values for ClientAdalAuthOverride

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/office-docs-powershell#3787]
Accepted values:	NoOverride, Allowed, Disallowed

but what does each mean? Especially the NoOverride

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b940ec3-fba8-8b31-48b2-76092639d4c5
* Version Independent ID: e33808fa-72f8-5b61-2a30-7da4ac2dffc4
* Content: [Set-CsOAuthConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csoauthconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOAuthConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOAuthConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomtau
* Microsoft Alias: **tomkau**

**Comment by tomtau** [comment]
I was pinged about this issue, but I guess the GitHub login should have been @tomkau ?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @TiloGit 
Thanks for your feedback, I created a pull request to propose some additions to the article to explain the values. If it gets approved, it will then be on the live version.
Thank you

**Comment by yogkumgit** [comment]
@tomkau Please merge the PR #3814

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @TiloGit Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
