### ISSUE TITLE
Need deleted group owners and members

### ISSUE THREAD

**Issue by vilmarci** [MicrosoftDocs/office-docs-powershell#3790]
Please add the -IncludeSoftDeletedGroups option like the Get-UnifiedGroup command has.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77a564cf-b454-d046-070b-ddc0c05c7a7f
* Version Independent ID: 055a9698-c1cc-174d-6c66-33c3bf21a55c
* Content: [Get-UnifiedGroupLinks (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/get-unifiedgrouplinks?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroupLinks.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroupLinks.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @vilmarci thanks for your feedback.
This issue system is specific to report issues in documentation, for feature requests, I need to kindly redirect you to https://office365.uservoice.com/
Thank you

**Comment by yogkumgit** [comment]
@vilmarci  Thank you very much for your kind feedback. Considering your valuable feedback, as advised, please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close
