### ISSUE TITLE
Example 2 statement update request.

### ISSUE THREAD

**Issue by sujithnair79** [MicrosoftDocs/office-docs-powershell#3792]
https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/enable-remotemailbox?view=exchange-ps

Enable-RemoteMailbox "Kim Akers" -RemoteRoutingAddress "kima@contoso.mail.onmicrosoft.com" -Archive

This example does the following:
 <<-- Mail-enables an existing on-premises user. -->> This needs to be removed.
 <<-- Creates the associated mailbox in the service. -->> This needs to be removed.
 Creates an archive mailbox in the service for the mailbox.
 To mail-enable an on-premises user, create the associated mailbox in the service, enable the archive mailbox in the service and include the Archive switch with the Enable-RemoteMailbox cmdlet.

In order to configure archive mailbox in service primary mailbox should be either provisioned in On-Prem or On Cloud.

The cmdlet will in the example two will error out:
 Parameter set cannot be resolved using the specified named parameters.

If you remove the remoteroutingaddress paramter you will see the following exception which would validate that the recipient type isn't supported for this task unless primary mailbox is not provisioned.
 This task does not support recipients of this type. The specified recipient domain.com/OU/User is of type User. Please make sure that this recipient matches the required recipient type for this task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3d8932-e958-6be5-1dd7-b0731115c4dd
* Version Independent ID: 2345fd23-d401-fbc7-38c0-4eb3c7695f0e
* Content: [Enable-RemoteMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/enable-remotemailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/Enable-RemoteMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/Enable-RemoteMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sujithnair79 thanks for your feedback.
I am proposing thru a pull request, to change the example number 2 to a working example.
Hopefully, if the article author approves it, it will go live.
Thank you

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #3815

**Comment by sujithnair79** [comment]
> Hello @sujithnair79 thanks for your feedback.
> I am proposing thru a pull request, to change the example number 2 to a working example.
> Hopefully, if the article author approves it, it will go live.
> Thank you

Thanks Andres.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @sujithnair79 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by sujithnair79** [comment]
I could not understand if this change is approved and if in deed we have the change effective. I do not see any update in the doc yet.

**Comment by get-itips** [comment]
Hello @sujithnair79 the PR was merged and it will take a while to be reflected live. Please check back in a few days.

**Comment by sujithnair79** [comment]
This change is still not updated. The example description is still incorrect.

**Comment by get-itips** [comment]
Hello @sujithnair79 Can you please be more descriptive about why you see that the description is still incorrect? Thank you, I appreciate.

**Comment by sujithnair79** [comment]
[Image]


Please refer to my previous comment in the below link and currently what is displayed in article.

https://github.com/MicrosoftDocs/office-docs-powershell/issues/3792

Thanks,
Sujith Nair

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by get-itips** [comment]
@sujithnair79 already see your previous comment but I think it needs more descriptive explanation by you, what are you trying to achieve, did you try the correct example, etc. 
thanks

**Comment by yogkumgit** [comment]
@sujithnair79 Please reply

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @sujithnair79 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
