### ISSUE TITLE
Workaround to Returns all teams that a use belongs to  

### ISSUE THREAD

**Issue by korniienkoalexis** [MicrosoftDocs/office-docs-powershell#3795]
https://github.com/korniienkoalexis/Get-Team

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @korniienkoalexis 
Thanks for your feedback.
Is there any specific article that you think needs to be corrected?
I see that you created a function to satisfy a special need, maybe you can propose it in [teams uservoice](https://microsoftteams.uservoice.com/)
Thanks for your contribution

**Comment by korniienkoalexis** [comment]
https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps

It actually specifies

Example 1
PS> Get-Team -User dmx1@example.com
Returns all teams that a user (dmx1@example.com) belongs to

**Comment by get-itips** [comment]
Hello @korniienkoalexis thanks for your contribution! As your comment will remain at the bottom of the article it will be very useful.

Similar issue were reported before:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/2222  
Fyi, the team is investigating this issue.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @korniienkoalexis Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
