### ISSUE TITLE
Which one to use?

### ISSUE THREAD

**Issue by oradcliffe** [MicrosoftDocs/office-docs-powershell#3796]
Is there a reason to use this one, import-csonlineaudiofile, vs the other seemingly very similar cmdlet, new-csonlineaudiofile?

https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlineaudiofile?view=skype-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3916b31e-3c98-3a5d-f034-1bcff3e8d8fc
* Version Independent ID: cc63afcc-727b-c972-eb11-21d6a15f1d0e
* Content: [Import-CsOnlineAudioFile (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Import-CsOnlineAudioFile.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomtau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @oradcliffe 
Thanks for your feedback.
From what I could investigate, New-CsOnlineAudioFile was part of _Organizational Auto Attendant First Generation cmdlets_ (-CsOrganizationalAutoAttendant) and Import-CsOnlineAudioFile is part of _second generation cmdlets_ (-CsAutoAttendant) which is now the support cmdlets to create Auto Attendant and Call Queues configurations.
Also I am pretty sure that @tomkau can confirm my thoughts. 
Thank you

**Comment by tomkau** [comment]
Hello @get-itips, your investigation is correct.  Import is part of second-gen, while New is first gen.  The first gen cmdlets will be removed in the near future

**Comment by yogkumgit** [comment]
@get-itips  and @tomkau  Thank you very much for the contribution and sharing this explanation. @oradcliffe Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
