### ISSUE TITLE
How to retrieve already existing audio files?

### ISSUE THREAD

**Issue by oradcliffe** [MicrosoftDocs/office-docs-powershell#3797]
Is there a get-csonlineaudiofile or similar?  I have not found anything like that yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3916b31e-3c98-3a5d-f034-1bcff3e8d8fc
* Version Independent ID: cc63afcc-727b-c972-eb11-21d6a15f1d0e
* Content: [Import-CsOnlineAudioFile (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Import-CsOnlineAudioFile.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomtau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @oradcliffe 
I can confirm you that there is no such cmdlet yet available.
You can propose new features and ideas here https://microsoftteams.uservoice.com/
Thank you

**Comment by yogkumgit** [comment]
@oradcliffe  Thank you very much for your kind feedback. Considering your valuable feedback, as advised, please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by DEberhardt** [comment]
I have not found a UserVoice for this request, so I created a new one: 
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40995259-more-powershell-commands-for-csonlineaudiofile-ge

Is there any news from the Product team in the last 11 months?

Thanks,
David
