### ISSUE TITLE
Dashes used in tables cannot be searched in a browser

### ISSUE THREAD

**Issue by corbob** [MicrosoftDocs/office-docs-powershell#3800]
The dashes used in the charts (like Remove-PnPWorkflowSubscription) is not a normal dash (perhaps it's U+2011?), and can't be searched on the page. Is there a reason to use this over the normal dash that a PowerShell user might expect to find?

It appears perhaps this is a regression of #827 :thinking:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3240d3-6a7d-fc4b-62fd-d3a5375d8a4a
* Version Independent ID: 561212df-4dab-92b7-b634-57d53d313c6f
* Content: [PnP PowerShell overview](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @corbob 
Thanks for your feedback.
The issues at this repo are exclusively to report issues in documentation, in this case, of PnP cmdlets.
So the right resource to follow this issue in the cmdlet is the one you have linked, which I see now that has been re-opened.
Please use that issue to share your scenario and follow up.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @corbob 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by corbob** [comment]
Well I'm really confused... I opened the issue from the page that had an issue. After opening the issue on the page, I came to github and was doing some searching on issues and found #827. so I edited the issue to add this. 827 was and still is closed. So is that to mean that this issue won't be resolved? or that someone with the permissions to do it should reopen 827?

**Comment by get-itips** [comment]
Hello @corbob 
Exactly, as you referenced that issue, a notification should arrive for the person in charge of the other repo, but I'll leave a message there too.

**Comment by get-itips** [comment]
Hello @corbob finally, i am proposing thru a pull request, a change in the code of the hyphens, if it gets approved, it will be reflected. thank you

**Comment by yogkumgit** [comment]
@kenwith Please merge the #3874

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @corbob Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
