### ISSUE TITLE
Support for Exchange Online

### ISSUE THREAD

**Issue by stwils** [MicrosoftDocs/office-docs-powershell#3802]
The end of the second paragraph states, "Importing .pst files is not possible in Exchange Online." Yet the article states that it applies to exchange online, so not sure if this used to be the case and wasn't updated.

Also, Is there any way to disable the alerts or notifications that appear in ECP for an import job? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3507900e-ff74-4f59-e2c4-af9cd3a21c28
* Version Independent ID: e9bab61c-cd18-f186-5eca-f1748ac816ab
* Content: [New-MailboxImportRequest (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/new-mailboximportrequest?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/New-MailboxImportRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/New-MailboxImportRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @stwils 
Thanks for your feedback.
I will create a pull request to propose removing that sentence from the article, as it is supported in ExOnline, (FilePath parameter is not though)
Thank you

**Comment by yogkumgit** [comment]
@chrisda  Please merge the PR #3831

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @stwils Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
