### ISSUE TITLE
-RecipientFilter. Document syntax for using parameters

### ISSUE THREAD

**Issue by flowt-au** [MicrosoftDocs/office-docs-powershell#3807]
The docs say: Use braces { } around the whole OPath syntax string.

But, if you do that, it seems you cannot use parameters in the Recipient Filter e.g. to add or set the filter via a CSV import process. 

See the following SO post for the correct syntax:

https://stackoverflow.com/questions/57408192/how-to-set-recipientfilter-on-new-dynamicdistributiongroup-using-a-variable

An example in these docs would not go astray! ;-)

Thanks,
Murray

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 184179e3-79bb-1955-4f7e-0fa09a72805b
* Version Independent ID: d1f72351-d8bc-8d47-bf3c-8d47c25fb443
* Content: [Set-DynamicDistributionGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-dynamicdistributiongroup?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Set-DynamicDistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Set-DynamicDistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @flowt-au 
Thanks for your feedback
I am proposing thru a pull request, the addition of an example and a clarification to the RecipientFilter parameter, when using variables, as I could verify.
Thank you

**Comment by flowt-au** [comment]
Thanks!

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #3840

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @flowt-au Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
