### ISSUE TITLE
-WithRightsAssigned not working

### ISSUE THREAD

**Issue by angelstephen** [MicrosoftDocs/office-docs-powershell#3822]
Command 1 - Get-PnPUser
Command 2 - Get-PnPUser -WithRightsAssigned

Bot the commands return the same results. Command 2 - Still returns all users from the User Information List who currently now does not have access to the site..  I have the latest PNP module version and did not include Identity parameter. Please help!

-WithRightsAssigned
If provided, only users that currently have any kinds of access rights assigned to the current site collection will be returned. Otherwise all users, even those who previously had rights assigned, but not anymore at the moment, will be returned as the information is pulled from the User Information List. Only works if you don't provide an -Identity.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @angelstephen 
Thanks for your feedback, the issues in this repo are specific to report problems in documentation, for issues using the cmdlets, you should look into the Pnp-Powershell repo.
But I found that a similar issue you are describing is already [reported here](https://github.com/SharePoint/PnP-PowerShell/issues/1816), please have a look and follow up there.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @angelstephen 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
