### ISSUE TITLE
New-DLPKeywordDictionary creation fails if the size of the keywords list/files is > 100KB

### ISSUE THREAD

**Issue by mayurnjoshi** [MicrosoftDocs/office-docs-powershell#3834]
When uploading a File from UI or creating it from PowerShell the command fails with the error as below. Is this a limitation of the product and if so are there any workarounds?

The keword dictionary file size exceeds the maximum file size of 100 KB..
    + CategoryInfo          : NotSpecified: (:) [Set-DlpKeywordDictionary], ErrorKeywordDic...nvalidException
    + FullyQualifiedErrorId :

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @chrisda 
I made some tests and had trouble uploading large csv files as the user here, can we confirm which is the limit? So I can add it to the article. 

Thanks

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #3888

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @mayurnjoshi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mayurnjoshi** [comment]
Can I also ask what would be a mechanism to make this work should we need to import a new keyword dictionary that has a lot of keywords? For instance, in our case, we have 13000 keywords for detecting ICD 10 identifiers in Spanish.

**Comment by get-itips** [comment]
Hello @mayurnjoshi how are you? I need to kindly suggest to ask support services of your tenant, as we are limited to address issues currently in documentation. Thank you

**Comment by mayurnjoshi** [comment]
Fair enough, thanks for your response.
