### ISSUE TITLE
Fix Documentation

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/office-docs-powershell#3837]
Several pieces are incomplete, it they are production ready update them. If they are not remove them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7456f5b5-7de8-2c8f-b165-8f6b4e380499
* Version Independent ID: 9ea298f4-8f11-0e52-9d73-bf0192dc3c9e
* Content: [New-RetentionCompliancePolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-retention/new-retentioncompliancepolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-retention/New-RetentionCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-retention/New-RetentionCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @stephenc01 
Thanks for your feedback.
After investigating, I created a pull request to update the article with the missing information, still needs author approval, if it gets approved, it will be reflected.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @stephenc01 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
