### ISSUE TITLE
Optional Parameters are incorrect

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/office-docs-powershell#3838]
Per the documentation only name is required.

New-RetentionCompliancePolicy -Name "Default 5 Year Retention [US1]"
Parameter set cannot be resolved using the specified named parameters.
    + CategoryInfo          : InvalidArgument: (:) [New-RetentionCompliancePolicy], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,New-RetentionCompliancePolicy
    + PSComputerName        : nam03b.ps.compliance.protection.outlook.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7456f5b5-7de8-2c8f-b165-8f6b4e380499
* Version Independent ID: 9ea298f4-8f11-0e52-9d73-bf0192dc3c9e
* Content: [New-RetentionCompliancePolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-retention/new-retentioncompliancepolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-retention/New-RetentionCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-retention/New-RetentionCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @stephenc01 
Thanks for your feedback.
Unless I am not seeing it, I did not find the Required attribute in this article. So if i am not wrong, it is not stating that name is the only parameter required.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution.  @stephenc01 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close

**Comment by sinfloodmusic** [comment]
I found I was able to get this working with the following command.  For some reason it needs to be fed the 'ExchangeLocation' but s ok with getting a null variable.
```
New-RetentionCompliancePolicy -Name $Name -ExchangeLocation $null
```
