### ISSUE TITLE
Correct first bullet point in Note

### ISSUE THREAD

**Issue by austinmccollum** [MicrosoftDocs/office-docs-powershell#3839]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by austinmccollum** [comment]
Currently Note section has bullet point:
"• You can't use the Exchange Online Remote PowerShell Module to connect to Exchange Online PowerShell and Security & Compliance Center PowerShell in the same session (window). You need to use separate sessions of the Exchange Online Remote PowerShell Module."

This is incorrect.  Here's a better explanation:
"In order to use both Security and Compliance powershell commands with Exchange Online commands in the Exchange Online Remote Powershell Module for MFA, you need to first connect with connect-ippsession commandlet.  Once that imports the commands, you'll have a new commandlet available, new-exopssession.  Here's an example of connecting to both within the same window and using a proxy defined by NETSH:
netsh winhttp set proxy 23.101.182.102:8888 "localhost;*.fabrikam.com"  
$ProxySetting = New-PSSessionOption -ProxyAccessType WinHttpConfig 
Connect-IPPSSession -PSSessionOption $ProxySetting 

#Then you can add the Exchange Online commands too, and add a prefix to prevent any conflict with connection to on premises or the security and compliance commands which share a few of these commands.

$EXOSession = New-ExoPSSession -pssessionoption $ProxySetting
Import-PSSession $EXOSession -Prefix EXO 
"

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @austinmccollum 
Thanks for your feedback and contribution.
I created a pull request to update this article and the Security & Compliance one.
The author @chrisda will review it and if he agrees, it will be merged.
Thank you

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #3868

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @austinmccollum Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
