### ISSUE TITLE
No explaination for `PendingDeletion` value for `Mode` parameter 

### ISSUE THREAD

**Issue by smadala** [MicrosoftDocs/office-docs-powershell#3842]
Please add detail explanation for `PendingDeletion` value for `Mode` parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1904f4-fe24-714c-46da-ab43195fc04c
* Version Independent ID: 58c66395-6df4-9d6e-abef-e4ec2b0d63ce
* Content: [New-DlpCompliancePolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/new-dlpcompliancepolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/New-DlpCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/New-DlpCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @smadala 
PendingDeletion is not a valid settable value, that is the reason is not under 

> Valid values are:

It is only a transient value that the policy can get when an administrator fires up the delete DLP policy command either from UI or Ps until it is really deleted.
Hope this info has helped you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @smadala 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
