### ISSUE TITLE
Set-User ignores -whatif (Exchange Online)

### ISSUE THREAD

**Issue by lc9er** [MicrosoftDocs/office-docs-powershell#3844]
Apologies if this is not the appropriate venue, but I couldn't find another location to submit a bug report.

Issue:

Set-User username@example.com -AuthenticationPolicy SuperStrictPolicy **-whatif**

The whatif is accepted as a parameter, but ignored, and the authentication policy gets updated.

Service: Exchange Online
Command: Set-User

**Comment by yogkumgit** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3842

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #3927

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @lc9er Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
