### ISSUE TITLE
Missing g in the example

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/office-docs-powershell#3847]
et-SPEnterpriseSearchAdministrationComponent -SearchApplication $ssa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733679f-6c5a-bff3-d5b4-6d795af5c9ca
* Version Independent ID: 4bd88e36-a3bc-ee68-7eab-32a117e0e19e
* Content: [Get-SPEnterpriseSearchAdministrationComponent (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spenterprisesearchadministrationcomponent?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Get-SPEnterpriseSearchAdministrationComponent.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Get-SPEnterpriseSearchAdministrationComponent.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @repton-infinity thanks for that. Created a pull request to correct the article. thank you

**Comment by yogkumgit** [comment]
@kenwith  Please merge the PR #3875

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @repton-infinity Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
