### ISSUE TITLE
Access denied and CDN warning

### ISSUE THREAD

**Issue by jcallaghan** [MicrosoftDocs/office-docs-powershell#3848]
Hi team. I am getting an error whilst trying to enable this in a UK tenant. I get an access denied error. You do not have permission to perofrm this action or access this resource. This occurs with SP admin and global admin. Furthermore, in my own UK tenant I have been able to do this but get a warning about enabling a CDN. Please can you share more information about this as I don't think I can proceed due to security requirements?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8deb61c-91a1-7e4c-cf56-d682026c6011
* Version Independent ID: 7d8c994d-8673-27dc-04ab-3c5c104c0daa
* Content: [Add-SPOOrgAssetsLibrary (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spoorgassetslibrary?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md)
* Service: **sharepoint-powershell**
* GitHub Login: @Maralesfahanpoor
* Microsoft Alias: **maesfaha**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jcallaghan 
How are you? I need to kindly redirect you to support services of your tenant, as this resource is specifically to report issues in documentation.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @jcallaghan 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution.
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by yogkumgit** [comment]
@officedocsbot close
