### ISSUE TITLE
Example section just has placeholder content

### ISSUE THREAD

**Issue by vardhan1990** [MicrosoftDocs/office-docs-powershell#3849]
https://docs.microsoft.com/en-us/powershell/module/teams/Get-TeamHelp?view=teams-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab658c47-3403-b6bc-36b3-cd6ad656ba7f
* Version Independent ID: 4676fdae-f3a1-a1da-e4d0-b4f815bd7c04
* Content: [Get-TeamHelp (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/Get-TeamHelp?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Get-TeamHelp.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamHelp.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello, thanks for noticing this, created a pull request to fix this. thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @vardhan1990 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
