### ISSUE TITLE
Floornumber and nickname parameters not recognized 

### ISSUE THREAD

**Issue by homerggg** [MicrosoftDocs/office-docs-powershell#3851]
I can get the Set-Place command to work perfectly, with the exception of the floornumber and nickname parameters. Those parameters cannot be found. I don't really need them but I would sure like to know why.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ef4fb7-736b-99e8-796b-c1d02410a7e4
* Version Independent ID: 0fb75415-2bd2-a880-aa9e-a06c76d9ddc4
* Content: [Set-Place (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-place?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #3858

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @homerggg Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
