### ISSUE TITLE
The required backslash for the -identity switch is not understood

### ISSUE THREAD

**Issue by evandimsby** [MicrosoftDocs/office-docs-powershell#3852]
Of all the odd notation that may be required for all sorts of cmdlets, have to use a " \ " backslash seems very out-of-the-ordinary, especially since that \ is not included as part of the notation when running "Get-PublicFolderMailboxMigrationRequest"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f13363-bab8-99c0-4db3-fd90df12befc
* Version Independent ID: 01832b93-e46e-a977-fc86-a9d1fd10a8f8
* Content: [Get-PublicFolderMailboxMigrationRequestStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/get-publicfoldermailboxmigrationrequeststatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMailboxMigrationRequestStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/Get-PublicFolderMailboxMigrationRequestStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @evandimsby, thank you for your feedback.

Could you put a screenshot here? I want to see the output you get when you run "Get-PublicFolderMailboxMigrationRequest". Thanks!

**Comment by evandimsby** [comment]
![PF screenshot](https://user-images.githubusercontent.com/43911824/63357944-4a153700-c338-11e9-9cc7-3d1225f907c6.PNG)
The screenshot shows different combinations with and without the backslash, and with and without the -identity switch specified

**Comment by evandimsby** [comment]
![get-pf](https://user-images.githubusercontent.com/43911824/63358140-8e083c00-c338-11e9-9245-5f8779ad8f3f.PNG)
And here is just Get-PublicFolderMailboxMigrationRequest by itself

**Comment by dariomws306** [comment]
Thank you very much!

Documentation looks good because you need to use the backslash. Do you want to understand why you need to use the backslash here? Or do you think there is something that we can do to improve the document?

**Comment by evandimsby** [comment]
Yes, understanding for why the \ is needed in this case, please.

**Comment by dariomws306** [comment]
Ok, let me check if I can get this information.

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and digging deep into it. @evandimsby 
If you see a documentation update is required, please feel free to open an issue for the same. Please keep contributing with your suggestions to improve the documentation.
