### ISSUE TITLE
ClientId samples do not work as expected

### ISSUE THREAD

**Issue by cperson** [MicrosoftDocs/office-docs-powershell#3855]
When working to Connect using AzureAD App Only, the following combination is the only thing that works for me: 

Connect-PnPOnline -Url $adminUrl  -Tenant "&lt;tenant&gt;.onmicrosoft.com" -CertificatePath &lt;PATHTO&gt;.pfx -ClientId $azureApplicationId -CertificatePassword (ConvertTo-SecureString -AsPlainText $azureApplicationIdPassword -Force)

This seems a bit off compared to the docs as I need to provide Client ID, Cert Path, and Cert Password here. Without the Cert Path, I get the following: 
Connect-PnPOnline : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:18

Why is the certificate even necessary?  

I have tried the following paths as suggested in the docs with no success: 

PS CMD: 
Connect-PnPOnline -Url $adminUrl -ClientId $azureApplicationId -Tenant "&lt;tenant&gt;.onmicrosoft.com" -CertificatePath &lt;PATHTO&gt;.pfx

Result:
Connect-PnPOnline : The specified network password is not correct.

PS CMD: 
Connect-PnPOnline -Url $adminUrl -ClientId $azureApplicationId -Tenant "&lt;tenant&gt;.onmicrosoft.com" -Thumbprint "&lt;AZURETHUMB&gt;"

RESULT: 
Connect-PnPOnline : Value cannot be null.
Parameter name: certificate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f910a5c-5883-6394-19a3-4cf1670c431f
* Version Independent ID: 4451fe4c-df86-34a8-0db0-46a47e70b5a5
* Content: [Connect-PnPOnline (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @cperson there is currently an open issue about this, here https://github.com/SharePoint/PnP-PowerShell/issues/2181 please follow up there

**Comment by cperson** [comment]
> Hello @cperson there is currently an open issue about this, here [SharePoint/PnP-PowerShell#2181](https://github.com/SharePoint/PnP-PowerShell/issues/2181) please follow up there

Thanks. I believe this is still valid, however, as this issue is geared specifically towards the inacurracy of the docs.

**Comment by get-itips** [comment]
> > Hello @cperson there is currently an open issue about this, here [SharePoint/PnP-PowerShell#2181](https://github.com/SharePoint/PnP-PowerShell/issues/2181) please follow up there
> 
> Thanks. I believe this is still valid, however, as this issue is geared specifically towards the inacurracy of the docs.
I understand your point however the Docs reflect the desired behavior, and as the functionality is in the process of being fix, I do not see anything to change in the article.

I will add a message to that issue to get the attention of the PnP team, that, as you might know, it is maintained by the community.

**Comment by cperson** [comment]
> > > Hello @cperson there is currently an open issue about this, here [SharePoint/PnP-PowerShell#2181](https://github.com/SharePoint/PnP-PowerShell/issues/2181) please follow up there
> > 
> > 
> > Thanks. I believe this is still valid, however, as this issue is geared specifically towards the inacurracy of the docs.
> 
> I understand your point however the Docs reflect the desired behavior, and as the functionality is in the process of being fix, I do not see anything to change in the article.
> 
> I will add a message to that issue to get the attention of the PnP team, that, as you might know, it is maintained by the community.

I don't think it's ideal to close _this_ issue before _that_ issue is resolved. Leaving this issue open will hopefully prevent other users relying on the Docs from going down a rabbit hole. 

"Hov did that so hopefully you won't have to go through that" - Jay-Z

**Comment by wobba** [comment]
Hi,
I'll look at the examples and try to clean them up.

For app-only SharePoint access you need a certificate - that's just how it is. 

You either need to point to a certificate path, a certificate thumbprint, or provide the values using the PEM values inline.

See https://github.com/SharePoint/PnP-PowerShell/tree/master/Samples/SharePoint.ConnectUsingAppPermissions for how to set up a certificate with an AAD application. If your certificate has a password, then this has to be included as well.

[Example 16](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md#------------------example-16------------------) has a link to this sample.

I'll add some more samples in the help on Connect-PnPOnline, matching the sample documentation, to make this easier.

**Comment by wobba** [comment]
@cperson I've updated the help docs with two new samples taken from the above linked documentation which will be updated for next release.

**Comment by yogkumgit** [comment]
@wobba  Thank you very much for the contribution and sharing this explanation. @cperson 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
