### ISSUE TITLE
Unable to set -LockState Readonly on particular Site Collection (all other works fine)

### ISSUE THREAD

**Issue by FedeFigueredo** [MicrosoftDocs/office-docs-powershell#3856]
I'm attempting to set a Site Collection from **Unlock** to **Readonly**. This Site Collection happens to be "https://tenant.sharepoint.com", so I'm unsure if that factors into it. I'm running:

Set-SPOSite https://tenant.sharepoint.com -LockState Readonly

When I do this with any other Site Collection like "https://tenant.sharepoint.com/sites/pwa", it unlocks just fine, but for this Site Collection, I get the error:

![Capture](https://user-images.githubusercontent.com/49570839/63350859-93638780-c334-11e9-85c6-250d387787fe.JPG)

Any ideas?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @FedeFigueredo 
AFAIK you can't set the LockState property of the root tenant site collection.
Will propose adding a note to the article.
Thank you

**Comment by yogkumgit** [comment]
@trent-green Please merge the PR #3883

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @FedeFigueredo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by FedeFigueredo** [comment]
There´s not any chance of fixing this bug? So -LockState property can be used on root tenant site collection.

**Comment by get-itips** [comment]
Hello @FedeFigueredo please submit the proposal here https://sharepoint.uservoice.com/ as that is the right resource to propose ideas/features.
Thank you

**Comment by FedeFigueredo** [comment]
OK @get-itips. Thanks!
