### ISSUE TITLE
Second Example do not work

### ISSUE THREAD

**Issue by alphacentrino** [MicrosoftDocs/office-docs-powershell#3857]
Get-Mailbox -Filter {ArchiveGuid -ne $null -and ArchiveDomain -ne $null} -ResultSize Unlimited | Test-ArchiveConnectivity
You get error:
The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do no
t match any of the parameters that take pipeline input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f4be7e-5d1c-14ca-3525-a86ac06a5632
* Version Independent ID: 87591c2b-0555-6b9d-a1f1-5752d3479329
* Content: [Test-ArchiveConnectivity (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/test-archiveconnectivity?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance/Test-ArchiveConnectivity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance/Test-ArchiveConnectivity.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @alphacentrino, thank you for your feedback.

Could you send me some screenshots? What happen when you run "Get-Mailbox -Filter {ArchiveGuid -ne $null -and ArchiveDomain -ne $null} -ResultSize Unlimited"?

Are you running this on Exchange 2016/19?

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and digging deep into it.  @alphacentrino We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
