### ISSUE TITLE
Problem with purging the messages after some time.

### ISSUE THREAD

**Issue by zaicnupagadi** [MicrosoftDocs/office-docs-powershell#3863]
Hey,

I've created a GDPR mechanism to remove emails, after estimating number of mailboxes with New-ComplianceSearch, after a week or so (after users review items that going to be deleted) I wanted to run action -purge, but instead of message about message removal, I got:
```
Unable to execute the task. Reason: The results for "GDPR ISUPER-18815" aren't up to date. Please update the search results to get the most current estimate.
At C:\Users\pjarosz_admin\AppData\Local\Temp\tmp_lj4uov0e.x1h\tmp_lj4uov0e.x1h.psm1:9920 char:9
+         $steppablePipeline.End()
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-ComplianceSearchAction], ComplianceJobTaskException
    + FullyQualifiedErrorId : [Server=HE1ExxxWS004,RequestId=af873c54-22d1-42f6-ac9f-88f46124f2ec,TimeStamp=21.08.2019 10:51:15] [FailureCategory=Cmdlet-ComplianceJobTaskException] 452F1F31,Microsoft.Office.ComplianceJob.Tasks.NewComplianceSearchAction
    + PSComputerName        : eur02b.ps.compliance.protection.outlook.com
```
Could you please provide information after what time the results do expire?

Important: Even "-Force" swoitch does not supress the message, and I got the message anyhow.

Now need to think about re-runnig it one more time at the end of the whole process.

**Comment by zaicnupagadi** [comment]
I got the idea - that in the meantime there might be some more messages with particular phrases - but what if some organizations - like my client - would like to run that anyhow - can we do '-Force' to help in this and bypass the error?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @zaicnupagadi thanks for your feedback.
Updating the search results is an expected outcome if the search is older than 7 days:

>If the results for a search are older than 7 days, you are prompted to update the search results. 


[Source ](https://docs.microsoft.com/en-us/office365/securitycompliance/export-search-results)

In this case, the -Force parameter will not help.

Hope this info helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @zaicnupagadi 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
