### ISSUE TITLE
EnableReliableConferenceDeletion available or not

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#3864]
Hi,
I have heard different kind of information that EnableReliableConferenceDeletion should be available for on-premises Skype as well, and not only for Skype online. Could you clairfy how it is? And if that is available for on-premises also, could you then write how to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb630b9-b94d-a647-ca21-821e1d520b21
* Version Independent ID: ede8297e-aa49-fc5e-23bb-2d678bc23e6b
* Content: [Set-CsConferencingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csconferencingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsConferencingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsConferencingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomtau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tomkau 
Can you please confirm us if _EnableReliableConferenceDeletion_ is available in the Online version? Tried to use it in the Online version but couldn't.
Thank you

**Comment by tomkau** [comment]
Hi @get-itips, the parameter does not apply to Online.  The documentation is not consistent.  It has the correct information early in the doc:

_The following parameters are not applicable to Skype for Business Online: ApplicationSharingMode, AsJob, AudioBitRateKb, Description, EnableMultiViewJoin, EnableOnlineMeetingPromptForLyncResources, **EnableReliableConferenceDeletion**, FileTransferBitRateKb, Force, Identity, Instance, MaxMeetingSize, MaxVideoConferenceResolution, PipelineVariable, Tenant, and TotalReceiveVideoBitRateKb__

But the parameter itself has the wrong information and needs an update

**Comment by get-itips** [comment]
Hello @tomkau thanks for the info, created a pull request to correct the article.

**Comment by Petri-X** [comment]
Big thanks @get-itips and @tomkau, but is there possible to get the clarification for that also? How to use it and what are the expected results? I understood it should impact how the meetings are stored after the expired time has been reached, but at least by my own experience it seems to have no impact to that.

**Comment by tomtau** [comment]
@tomkau could you possibly fix your GitHub issue reporting https://github.com/MicrosoftDocs/office-docs-powershell/issues/3864#issue-483395047 so that your login appears in the issue details instead of mine? I've been pinged about many issues in this repository even though I have nothing to do with them (I think! :))

**Comment by Petri-X** [comment]
Btw, will you fix the document for **New-CsConferencingPolicy** around this, or does it really requires a separate bug report ? As there is a same problem.

**Comment by get-itips** [comment]
> @tomkau could you possibly fix your GitHub issue reporting [#3864 (comment)](https://github.com/MicrosoftDocs/office-docs-powershell/issues/3864#issue-483395047) so that your login appears in the issue details instead of mine? I've been pinged about many issues in this repository even though I have nothing to do with them (I think! :))

I will fix that, sorry

**Comment by get-itips** [comment]
> Btw, will you fix the document for **New-CsConferencingPolicy** around this, or does it really requires a separate bug report ? As there is a same problem.

I'll review it myself. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Petri-X Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Petri-X** [comment]
Hi @yogkumgit and @get-itips,
Great helps to fix the New- and Set-  :D

But there was another hope than only fixing the "**Applies to**" section. It is also missing the clarification/description. How to use it and what are the expected results? I understood it should impact how the meetings are stored after the expired time has been reached, but at least by my own experience it seems to have no impact to that.

**Comment by get-itips** [comment]
Hello @tomkau can you please give us more information about this parameter? so we can add a description to the article. Thank you

**Comment by tomkau** [comment]
Here's the comment from the code regarding this parameter (EnableReliableConferenceDeletion). 

              If true, we provide instantaneous consistency of distributed conference state, when user deletes a conference. We ensure that the conference state is removed from all replicas when the user deletes the conference.

              If false, we only provide eventual and not instantaneous consistency for conference state deletion.

**Comment by get-itips** [comment]
Thanks @tomkau created a PR to improve the article based on the information you provided.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Petri-X Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
