### ISSUE TITLE
Get-SPOScriptFromList not recognized as command's applet

### ISSUE THREAD

**Issue by Amysno** [MicrosoftDocs/office-docs-powershell#3866]
Hello,
I updated my Microsoft.Online.SharePoint.PowerShell module to version 16.0.9119.1200 because Powershell returned an error when trying to get Script from Event List. This error is the following :
Get-SPOScriptFromList : the term "Get-SPOScriptFromList" is not recognized as a command applet, function, script file nor exe. Please check the writing...
(sorry, translated from french prompt)
Why ? Is the doc updated ? Thanks !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49097b6c-149f-075c-3371-36055d3d7ac1
* Version Independent ID: e72af23f-ac47-2fe7-5830-14998f75587f
* Content: [Get-SPOSiteScriptFromList (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositescriptfromlist?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScriptFromList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScriptFromList.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Amysno 
Thanks for your feedback.
I see that you ran Get-SPOScriptFromList, but the cmdlet you opened the issue for is Get-SPO**Site**ScriptFromList

I could verify that, that cmdlet, is present in the mentioned version of the module.
![image](https://user-images.githubusercontent.com/36666927/63637189-1d229600-c650-11e9-9cb2-7e5b4cd9d786.png)

Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Amysno 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
