### ISSUE TITLE
Set-CalendarProcessing working for UserMailbox recipient type?

### ISSUE THREAD

**Issue by MSg1thub** [MicrosoftDocs/office-docs-powershell#3869]
O365 hybrid tenant with AD hosted locally and all mailboxes in EXO. I connected to remote PS and ran:

Set-CalendarProcessing -Identity UserMailbox@domain.com -AutomateProcessing None

And it was successful! Prior to today it generated an error. Is this cmdlet expanding from only resource mbx use to user mailbox usage as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a9c45b-34dd-c1c8-89f0-84f3d968eac4
* Version Independent ID: ec9c910c-25f2-f36a-8f75-ce052f0e8be6
* Content: [Set-CalendarProcessing (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-calendarprocessing?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @MSg1thub, thank you for your feedback.

You can see this in the article: "Note that this cmdlet is effective only on resource mailboxes".

So, you should use it only on resource mailboxes, but some parameters would work with mailboxes. See this image:

![image](https://user-images.githubusercontent.com/33589238/63979321-f1a80d00-ca8e-11e9-83ac-ed303464e7bf.png)

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @MSg1thub 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
