### ISSUE TITLE
Able to run this command from a workstation

### ISSUE THREAD

**Issue by chairborne33** [MicrosoftDocs/office-docs-powershell#3870]
The documentation states "This cmdlet normally can be run on the affected Mailbox server only. An exception is that this cmdlet can be run on an administrator's workstation when using the ConfigurationOnly parameter with a value of $true." However, I was able to run the command and successfully move a mailbox database multiple times from the Exchange Management shell on my Windows 10 workstation. 

I'm running Exchange Server 2019 CU2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaaf61e7-5bf9-d72e-69fe-f1679ff5fc8c
* Version Independent ID: 06dfb699-6733-97ff-a7a7-4323bd16f3b7
* Content: [Move-DatabasePath (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailbox-databases-and-servers/move-databasepath?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailbox-databases-and-servers/Move-DatabasePath.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailbox-databases-and-servers/Move-DatabasePath.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chairborne33** [comment]
Any update?

**Comment by dariomws306** [comment]
Hi @chrisda,

Could you help with this? I think it could work in Exch 2016/19 (even 2013) but not in Exchange 2010. What do you think?

Thanks!

**Comment by chrisda** [comment]
That sounds reasonable to me.

**Comment by chairborne33** [comment]
It appears the documentation needs some updating.

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #3940

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @chairborne33 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
