### ISSUE TITLE
Set user status

### ISSUE THREAD

**Issue by erossini** [MicrosoftDocs/office-docs-powershell#3871]
Hi,
I'm using **PowerShell** for a lot of thing. I found useful to have this for Microsoft Teams. Although, the most useful feature is to set the user status. I can't find this option in the version 1.0.1

Here I found a lot of functionalities but I think most of them are deprecated.
https://blogs.technet.microsoft.com/skypehybridguy/2017/11/07/microsoft-teams-powershell-support/

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@erossini  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
