### ISSUE TITLE
Get-SPOExternalUser : Could not load type 'Microsoft.SharePoint.Administration.CentralAssetRepository' from assembly 

### ISSUE THREAD

**Issue by westerdaled** [MicrosoftDocs/office-docs-powershell#3872]
Hi
First thing I did is download and install the latest latest SharePoint Online Managment Shell :
16.0.9119.1200

`
connect-SPOService -ul 'https://tenant-admin.sharepoint.com'

Get-SPOExternalUser -PageSize 3
`
![Get-SPOExternalUser error](https://user-images.githubusercontent.com/937208/63518976-05310200-c4ea-11e9-9d56-f1c58d9ae7d3.PNG)

I have tried rebooting but there is still an issue - oh and it freezes the ISE when I get this error.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by westerdaled** [comment]
Thanks for getting back to me .  Can you confirm you tried to reproduce the scenario I showed above both a first release and a UK based live tenant? I am not so sure support can help here given the module loads in a PS 5.3 shell  and I can connect to the tenant admin url .

**Comment by westerdaled** [comment]
Hi @get-itips  ,  Now raised a support request on this . Thanks for the advice.

**Comment by yamineT** [comment]
Hi,
Is this issue fixed now?
I found no solution to automatically remove guests accesses on sites collection.
Thanks
