### ISSUE TITLE
New-ComplianceSearchAction won't work untill user has mailbox

### ISSUE THREAD

**Issue by ryanharnwell** [MicrosoftDocs/office-docs-powershell#3880]
Logging into office.com as admin user I can perform search in Security and Compliance center -  and export messages.

Attempting the same via powershell using New-ComplianceSearchAction errors are returned:

Failed to get recipient 'xxx@yyy.onmicrosoft.com', Fault: IsComplete: False
EX:Organization Id is null for user xxx@yyy.onmicrosoft.com

Does the admin need a mailbox to execute New-ComplianceSearchAction?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by ryanharnwell** [comment]
Yes, I can reproduce on multiple tenants.

Admin user, with the correct role and no mailbox gives the error:

Failed to get recipient 'xxx@yyy.onmicrosoft.com', Fault: IsComplete: False
EX:Organization Id is null for user xxx@yyy.onmicrosoft.com

Assigned an exchange online plan 1 license to the admin user, and then it works without error.

**Comment by get-itips** [comment]
added suggestions by @chrisda thanks

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #3969
