### ISSUE TITLE
-Force

### ISSUE THREAD

**Issue by CaisnCon** [MicrosoftDocs/office-docs-powershell#3885]
Would love to have a -Force param to help Orphaned sites where the group have been deleted but the SharePoint site remains, due to retention. This current method will fail as the site type/template is #Group and thus it will not try to reconnect it to a Group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 901772a6-b15b-d19e-c799-f1fad627c1f8
* Version Independent ID: af5eca43-afb6-2cdb-8cd1-48b722cc5671
* Content: [Set-SPOSiteGroup (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spositegroup?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteGroup.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by CaisnCon** [comment]
Sorry was Set-SPOSiteOffice365Group method

**Comment by yogkumgit** [comment]
@CaisnCon I am closing it and Considering the correct one #3886

**Comment by yogkumgit** [comment]
@officedocsbot close
