### ISSUE TITLE
-Force

### ISSUE THREAD

**Issue by CaisnCon** [MicrosoftDocs/office-docs-powershell#3886]
Would love to have a -Force param to help Orphaned sites where the group have been deleted but the SharePoint site remains, due to retention. This current method will fail as the site type/template is #Group and thus it will not try to reconnect it to a Group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f97f530-5982-64b0-8cf5-02a9f361b75b
* Version Independent ID: f10aeefa-17b4-1929-8e89-b8a2b67ee5fa
* Content: [Set-SPOSiteOffice365Group (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spositeoffice365group?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteOffice365Group.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteOffice365Group.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @CaisnCon 
thanks for your feedback.
I need to kindly redirect you to Sharepoint Uservoice, which is the right resource to propose new ideas or improvements. https://sharepoint.uservoice.com/
Thank you

**Comment by yogkumgit** [comment]
@CaisnCon  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
