### ISSUE TITLE
Get-DlpDetailReport

### ISSUE THREAD

**Issue by ReneOudeNijeweme** [MicrosoftDocs/office-docs-powershell#3887]
using parameters like:
Get-DlpDetailReport -StartDate (get-date).adddays(-1) -EndDate (get-date).AddDays(+1) -DlpCompliancePolicy "DLPname" -EventType DLPPolicyHits -PageSize 5000 |select-object date,actor,title,DlpComplianceRule,eventtype,SensitiveInformationType,SensitiveInformationCount,location
does deliver the keyword hit from dictionaries as hex code (of the root dictionary of the tenant) while in the reports to a mailbox (is defined in policy) the actual keyword hit is expressed.
in the GUI report, the hit is also shown as hex code

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ReneOudeNijeweme 
Thanks for your feedback. I could not fully understand your post sorry, is there any documentation article you see that need a fix?

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @ReneOudeNijeweme We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
