### ISSUE TITLE
edit supported values for -linktype

### ISSUE THREAD

**Issue by sulobr** [MicrosoftDocs/office-docs-powershell#3890]
As per discussion with Engineering team, linktype "Eventsubscribers" is not supported. It is only supported in DCOps. Can we please update this article to remove "Eventsubscribers" as possible option for -Linktype parameter in Add-UnifiedGroupLinks cmdlet? This was verified under VSO escalation 1202753. 

https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/add-unifiedgrouplinks?view=exchange-ps

Additionally, "Aggregators" link type is also not supported for Admin use.  It does throw error "Microsoft.Exchange.Management.Tasks.RecipientTaskException: Aggregators aren't allowed in a non-data-center environment." so it might be best if we remove it from our public documentation as well.

Therefore, this request is to edit/remove EventSubscribers and Aggregators as valid values for LinkType parameters.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda  Please merge this PR #3904

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @sulobr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
