### ISSUE TITLE
URL sample is wrong

### ISSUE THREAD

**Issue by Didierma92** [MicrosoftDocs/office-docs-powershell#3892]
you should add  -admin after the name of your tenant prefix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85cea8f8-239d-1f73-f13a-a5a3148b66e5
* Version Independent ID: ca809b64-206c-4dfa-7c79-b0a45979e953
* Content: [Connect-SPOService (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @Didierma92 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
