### ISSUE TITLE
Wildcard accepted in -RecipientAddress

### ISSUE THREAD

**Issue by boaz-w** [MicrosoftDocs/office-docs-powershell#3893]
Wildcards seem to be accepted for the RecipientAddress parameter unlike stated in the documentation.
For example, Start-HistoricalSearch -RecipientAddress "*@gmail.com" works as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a22164-2df5-5dc2-9292-df60df018a53
* Version Independent ID: 1d96478c-230b-889e-68ed-9a8ab9484be5
* Content: [Start-HistoricalSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/start-historicalsearch?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Start-HistoricalSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Start-HistoricalSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @boaz-w thanks for your feedback. I created a pull request to improve the article. Thank you

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #3908

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @boaz-w Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
