### ISSUE TITLE
Examples are missing

### ISSUE THREAD

**Issue by joshrpg** [MicrosoftDocs/office-docs-powershell#3894]
There aren't any examples. Not sure why #3433 was closed as they stated the same thing and yet it was closed and still no examples...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd72bd68-7de2-8ecd-04e8-8088be1cfbab
* Version Independent ID: 9f1b3291-29b7-a931-ea12-f8ac2db94afe
* Content: [Set-ProtectionAlert (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/set-protectionalert?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance/Set-ProtectionAlert.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance/Set-ProtectionAlert.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @joshrpg thanks for your feedback, I created a pull request to add some examples.
Thank you

**Comment by yogkumgit** [comment]
@chrisda please merge this PR #3907

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @joshrpg Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
