### ISSUE TITLE
Sample #17 error on-premises sharepoint 2019

### ISSUE THREAD

**Issue by Niegrozny** [MicrosoftDocs/office-docs-powershell#3895]
When I'm passing correct parameters I get en error:

Connect-PnPOnline : Exception has been thrown by the target of an invocation.
At line:1 char:1
+ Connect-PnPOnline -Url 'https://mysharepoint.com' -ClientId 'xxxxxxxx ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], TargetInvocationException
    + FullyQualifiedErrorId : System.Reflection.TargetInvocationException,SharePointPnP.PowerShell.Commands.Base.Conne
   ctOnline

although my high trust app is up and running using the same parameters specified

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f910a5c-5883-6394-19a3-4cf1670c431f
* Version Independent ID: 4451fe4c-df86-34a8-0db0-46a47e70b5a5
* Content: [Connect-PnPOnline (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Niegrozny 
Please, follow up here https://github.com/SharePoint/PnP-PowerShell/issues/2181 on issues in cmdlets.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Niegrozny 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
