### ISSUE TITLE
Device Look up

### ISSUE THREAD

**Issue by Jeighsen** [MicrosoftDocs/office-docs-powershell#3897]
I have the name of a device that connected through activesync.  I'm trying to find the username on the domain that is connected to that specific device.  Get-ActiveSyncDeviceClass | group-object  shows me the device.  Is there a way that i can get information of the device and what exchange account is connected through that device?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Jeighsen, thank you for your feedback.

Did you try with Get-MobileDevice?

Please, for this kind of questions open a support ticket or go to https://techcommunity.microsoft.com.

Docs.microsoft.com feedback is available to help us to improve/fix documentacion.

Thank you again!

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @Jeighsen 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
