### ISSUE TITLE
Remove-UMDialplan fails with error "There are UM users who are associated by..."

### ISSUE THREAD

**Issue by patstenl** [MicrosoftDocs/office-docs-powershell#3900]
When trying to remove a UMDialplan ti fails with error "There are UM users who are associated by their UM mailbox policy with the dial plan."

Removed all users from UM with following commands:
Disable-UMMailbox -Identity email
Set-csUser account -HostedVoicemail $false
Grant-CSHostedVoicemailPolicy -identity account -PolicyName ""

Checked if still mailboxes are related to UMDiaplan with:
Get-UMMailbox -ResultSize Unlimited | ? {$_.UMDialPlan -eq "Test"}
No results, so no UMMailboxes are related to this UMDialplan

Removed UMmailboxpolicy with command:
Remove-UMMailboxPolicy -Identity "Test Default Policy"

Last step to remove UMDialPlan with command:
Remove-UMDialPlan -Identity "Test"
returns with error "There are UM users who are associated by their UM mailbox policy with the dial plan."

Any suggestions how to get the UMDialPlan removed?
I am lost :-|

Thanks in advance,
Patrick

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
@patstenl Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and digging deep into it. @patstenl 
If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Please keep contributing with your suggestions to improve the documentation.
