### ISSUE TITLE
Need to fill out description for Properties

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/office-docs-powershell#3902]
Under -Properties, the current text is "{{Fill Properties Description}}". 
So someone needs to fill in some text for the description :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b640892-b0a1-4f20-1e25-fe5f0e97f5b6
* Version Independent ID: 51774b36-90fa-1d9a-5800-1a54d9f70590
* Content: [Get-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailbox?view=exchange-ps#examples)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda  Please merge this PR #3921

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @baardhermansen Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by baardhermansen** [comment]
@yogkumit I can't see any change in the text i commented on, a description is still missing;
-Properties
This parameter is available only in the cloud-based service.

{{Fill Properties Description}}

**Comment by dariomws306** [comment]
Hi @baardhermansen,

The update has been applied but it could take same days to appear in the live article.
