### ISSUE TITLE
Powershell Command doesn't Exist

### ISSUE THREAD

**Issue by Zkallai** [MicrosoftDocs/office-docs-powershell#3903]
This command doesn't exist in the latest alpha version (1.0.6-alpha) of the staffhub powershell commands.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76078a4c-168c-7b8e-8e41-550dcd65b56d
* Version Independent ID: bc1090a1-7b6c-9b2b-1306-5153aace61d6
* Content: [Get-StaffHubShifts (staffhub)](https://docs.microsoft.com/en-us/powershell/module/staffhub/Get-StaffHubShifts?view=staffhub-ps#feedback)
* Content Source: [staffhub/staffhub-ps/staffhub/Get-StaffHubShifts.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/staffhub/staffhub-ps/staffhub/Get-StaffHubShifts.md)
* Service: **staffhub-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Related https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1925

**Comment by kenwith** [comment]
@get-itips - do you know what happened with the related issue #1925? are there other cmdlets that replaced this cmdlet and this reference was published by mistake or are the cmdlets still coming? If you aren't sure I can dig around and find the product team and ask too.

**Comment by get-itips** [comment]
Hello all
I could talk with the PG and the documentation for this cmdlet was incorrectly released, the cmdlet does not exists.
We will proceed closing this one.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Zkallai 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
