### ISSUE TITLE
Add-TeamUser ignore ErrorAction SilentlyContinue

### ISSUE THREAD

**Issue by rezabj** [MicrosoftDocs/office-docs-powershell#3905]
`Add-TeamUser -GroupId $_[0] -User $User.UserPrincipalName -Role Member -ErrorAction SilentlyContinue`
```
Add-TeamUser : Error occurred while executing Add-TeamUser
Code: Request_BadRequest
Message: One or more added object references already exist for the following modified properties: 'members'.
InnerError:
  RequestId: 5016dd1c-32e9-43b5-89c9-77df65200976
  DateTimeStamp: 2019-08-29T07:41:19
HttpStatusCode: Request_BadRequest
At D:\_Git\ITAdmin\GroupSyncWithKonzole\FILTER_TO_Teams\Set-TeamsGrpByKFilters.ps1:78 char:9
+         Add-TeamUser -GroupId $_[0] -User $User.UserPrincipalName -Ro ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamUser], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell
   .Custom.AddTeamUser
```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
@rezabj Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and digging deep into it. @rezabj 
If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Please keep contributing with your suggestions to improve the documentation.

**Comment by gavinmeerwald** [comment]
Why was this ticket closed? The original post was why, despite using "-ErrorAction SilentlyContinue" the error was still thrown?

**Comment by dariomws306** [comment]
Hi @gavinmeerwald,

Because this place is to leave feedback about documentation. In this case you have to open a support ticket.

Thanks!
