### ISSUE TITLE
Are all of the commands on this article live?

### ISSUE THREAD

**Issue by Skempf94** [MicrosoftDocs/office-docs-powershell#3906]
'-EnableFileTransfer' doesn't seem like it is live at the moment, we have attempted to run it, but receive the following error:
"You are not permitted to invoke Set-CsExternalUserCommunicationPolicy with the following parameters: EnableFileTransfer"
Please can we have some clarification on the status of the commands that are currently available? Specifically the EnableFileTransfer command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e6ed2c7-9452-dec6-2b82-efa9947a54e8
* Version Independent ID: be814e59-80a8-4da0-6774-de732e23041f
* Content: [New-CsExternalUserCommunicationPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csexternalusercommunicationpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsExternalUserCommunicationPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsExternalUserCommunicationPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomtau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tomkau Tom
I could verify what the user is here saying, it seems that the parameter _EnableFileTransfer_ hasn't been enabled to be specified by users. Can you please confirm this?
I appreciate.

**Comment by tomkau** [comment]
I sent a note to the team that owns the cmdlet to ask for clarification.

**Comment by get-itips** [comment]
> I sent a note to the team that owns the cmdlet to ask for clarification.

Hello @tomkau , any replies from the team? Thank you

**Comment by get-itips** [comment]
Hello @tomkau Tom could you see our query? Thanks

**Comment by get-itips** [comment]
Hello,
I could confirm that the current and only parameter available to set using this cmdlet is _EnableP2PFileTransfer_ 
For the others, the current statement in the description _This parameter is reserved for internal Microsoft use._ remains, so we will proceed closing this issue.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Skempf94 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
