### ISSUE TITLE
What type of label is this?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#3909]
does this get a sensitivity label, retention label or some other kind of label?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cadf6ff7-00ea-ae7b-7f71-df17fbea55ab
* Version Independent ID: 94d968d2-1605-b79e-c1d2-f23c7702e9ec
* Content: [Get-PnPLabel (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnplabel?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPLabel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPLabel.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DeanGross thanks for your feedback. I created a pull request, referenced here, to propose improving the description of the article, based on your comments, thank you!

**Comment by yogkumgit** [comment]
@VesaJuvonen  Please merge this PR #2228

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DeanGross** [comment]
Thanks, but I don't see any additional information that explains the type of label that is retrieved when the get command is executed. Office 365 has 2 primary types of labels: Retention and Sensitivity, there is also an AAD Group classification label as well as ad-hoc 'labels' from the SPO property bag and other programming objects. It is still not clear to me which of these will be returned by this command or created by the associated Set-PnP Label command. Please add some more information to the description.

**Comment by get-itips** [comment]
Hello @erwinvanhunen can you please answer the question the user is asking here? I would appreciate.

**Comment by erwinvanhunen** [comment]
@DeanGross Get-PnPLabel and Set-PnPLabel will return and set retention labels as defined here:

![image](https://user-images.githubusercontent.com/7666381/67270187-73794d00-f4b8-11e9-9ed1-739a295c01e2.png)

**Comment by yogkumgit** [comment]
@get-itips   and @erwinvanhunen  Thank you very much for the contribution and sharing this explanation. @DeanGross Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
