### ISSUE TITLE
unable to enable basic auth

### ISSUE THREAD

**Issue by sir-wally** [MicrosoftDocs/office-docs-powershell#3910]
&gt; winrm set winrm/config/client/auth @{Basic="true"}
Error: Invalid use of command line. Type "winrm -?" for help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by trir262** [comment]
A more 'PowerShell-friendly' approach is ```Set-Item WSMan:\localhost\Client\Auth\Basic -Value 'True'```, this requires administrative permissions
