### ISSUE TITLE
Maximum hub sites are 2000

### ISSUE THREAD

**Issue by taisino** [MicrosoftDocs/office-docs-powershell#3915]
Maximum number of hub sites is raised to 2000 recently, so please update this document.
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=51933

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 114697af-1b15-2582-49af-7ae2a8fe1cb0
* Version Independent ID: 6ed31c1e-1706-318b-5030-0e74dd9e875e
* Content: [Register-SPOHubSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/register-spohubsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Register-SPOHubSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Register-SPOHubSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @taisino 
Thanks for that! created a pull request to update the article.
Thank you

**Comment by yogkumgit** [comment]
@trent-green Please merge this PR #3937

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @taisino Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
