### ISSUE TITLE
Example 3 Syntax

### ISSUE THREAD

**Issue by RossMcLean77** [MicrosoftDocs/office-docs-powershell#3916]
Should the identity not be enclosed in double quotes as follows:
Get-PnPUser -Identity "i:0#.f|membership|user@tenant.onmicrosoft.com"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ec7ac7-3858-172e-ec9c-ab7c948ae2cf
* Version Independent ID: 3a171d0d-f00d-36fd-44c3-c6bb08222b14
* Content: [Get-PnPUser (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpuser?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPUser.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @RossMcLean77 thanks for your feedback!
I created a pull request, you can take a look as it is referenced here, to propose correcting the example.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @erwinvanhunen Thanks for your support. @RossMcLean77 hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
