### ISSUE TITLE
-DisabledWebpartIds <Guid> Parameter does not exist

### ISSUE THREAD

**Issue by MrTantum** [MicrosoftDocs/office-docs-powershell#3924]
The parameter `-DisabledWebpartIds` does not exist for `Set-SPOSite`.

We have already been wondering why this endpoint is not mentioned in the [CSOM Update from last year](https://developer.microsoft.com/en-us/outlook/blogs/new-sharepoint-csom-version-released-for-sharepoint-online-august-2018/) because this only contained the Tenant endpoint for DisabledWebpartIds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1c6b2b-5af6-acce-b7e8-bf784bb0973e
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
This switch is in `Set-SPOTenant`. @VesaJuvonen was it planned to be part of `Set-SPOSite`?

**Comment by get-itips** [comment]
@trent-green please review the referenced PR if you agree with the removal of the missing parameter.
@MrTantum Thanks for the feedback.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @MrTantum Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
