### ISSUE TITLE
Running this cmdlet, does it imply that security is set accordingly?

### ISSUE THREAD

**Issue by robinmeure** [MicrosoftDocs/office-docs-powershell#3929]
When running this PS cmdlet for a given user who does not have access yet for the given hub, does it imply that the security is set properly and the user can associate their site to the specified hub? Or does the user also needs to be added as a visitor/member/owner of the hub as well (or does the cmdlet take care of that?)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@robinmeure  considering the issue with document details so closing it
