### ISSUE TITLE
Running this cmdlet, does it imply that security is set accordingly?

### ISSUE THREAD

**Issue by robinmeure** [MicrosoftDocs/office-docs-powershell#3930]
When running this PS cmdlet for a given user who does not have access yet for the given hub, does it imply that the security is set properly and the user can associate their site to the specified hub? Or does the user also needs to be added as a visitor/member/owner of the hub as well (or does the cmdlet take care of that?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c406f02-6894-fda9-10f8-def836cd4270
* Version Independent ID: bb70a9a3-6a38-912c-4c5a-5d4063065941
* Content: [Grant-SPOHubSiteRights (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/grant-spohubsiterights?view=sharepoint-ps&lc=1033#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Grant-SPOHubSiteRights.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Grant-SPOHubSiteRights.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @robinmeure 
I tested that and got 

![image](https://user-images.githubusercontent.com/36666927/64354563-0f68fb00-cfd6-11e9-9fd1-5d11aa8e4a94.png)


So you need to grant access to the user to the Hub site for the user to be able to join the user's site to the hub site.

The cmdlet will not take care of that, the cmdlet only does what it says, granting a user the right to associate a site to a hub site.

Hope this info helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it. @robinmeure 
If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Please keep contributing with your suggestions to improve the documentation.
