### ISSUE TITLE
ApplicationID values

### ISSUE THREAD

**Issue by hbro** [MicrosoftDocs/office-docs-powershell#3939]
It's unclear what ApplicationID is supposed to be. According to https://www.lee-ford.co.uk/teams-call-queues-attendants-explained , it's "ce933385-9390-45d1-9512-c8d228074e07" for Auto Attendant or "11cd3e2e-fccb-42ad-ad00-878b93575e07" for Call Queue. Or something else entirely when using a bot.
It could help add this information in the parameter description for ApplicationID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1607d48-fd70-a53e-1d5f-36d15317a1cc
* Version Independent ID: 40631b45-4e4c-38a5-a750-509f4d835690
* Content: [New-CsHybridApplicationEndpoint (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cshybridapplicationendpoint?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsHybridApplicationEndpoint.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsHybridApplicationEndpoint.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@hirenshah1  Please merge the PR #3953

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @hbro Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by hbro** [comment]
Looks great thanks!
