### ISSUE TITLE
Notify participant of declined request from Resource Room

### ISSUE THREAD

**Issue by JanniePC** [MicrosoftDocs/office-docs-powershell#3945]
Please accept my apologies if this is not the correct forum for this request and please advise where I may post this request. 
Is there a way to configure the Recourse Room to notify all participants when it declines a meeting instead of just notifying the organizer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a9c45b-34dd-c1c8-89f0-84f3d968eac4
* Version Independent ID: ec9c910c-25f2-f36a-8f75-ce052f0e8be6
* Content: [Set-CalendarProcessing (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-calendarprocessing?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @JanniePC, thank you for your feedback.

I understand that there is no way to do it. But I can suggest to put this kind of concern here:
https://techcommunity.microsoft.com

We are here to help to improve docs.microsoft.com articles.

Thanks!

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @JanniePC 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
