### ISSUE TITLE
Missing parameter ProxyPool description

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#3946]
What has happend? When running command "get-help move-csuser -full" it list a parameter: "-proxypool" and that is what we have used earlier. Now when reading online documentation, there is no comments about that at all?

But then you do have comment: "_To move a user to Office 365, specify the **ProxyFqdn** of the hosting provider_". But then there is no parameter as "ProxyFqdn".

Is it me only who think this is not fully correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c68752-3b36-518f-8cf1-7a4e2aa8cf15
* Version Independent ID: 98b9a798-e232-0b2c-ee0f-857071885c1d
* Content: [Move-CsUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Move-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Move-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Petri-X 
Thanks for your feedback.
Actually, the full sentence in the online documentation says:

> To move a user to Office 365, specify the ProxyFqdn of the hosting provider **as the Target**. 

And then, in Target it says

> If moving to Office 365, this must be set to the ProxyFqdn value of the hosting provider. In most cases this is sipfed.online.lync.com. The value of the ProxyFqdn can be obtained using Get-CsHostingProvider

About ProxyPool, digging into the commits, I saw that @bjwhalen was the author of the [pr](https://github.com/MicrosoftDocs/office-docs-powershell/pull/1231) that removed the parameter from this article, but found no description in the pr, I see that the parameter is still present in SfB 2019, so can you shed some light here @bjwhalen and @tomkau ? We appreciate.

**Comment by Petri-X** [comment]
You are correct @get-itips ! :)
I just saw a term "proxy" and I could not separate ProxyPool and ProxyFQDN from each others :D

**Comment by get-itips** [comment]
Hello @Petri-X 
I am glad that I could help you, if you agree, we will proceed closing this one.
Thank you

**Comment by Petri-X** [comment]
@get-itips, I still would like to see what about the "-**ProxyPool**". That in my mind is still missing.

**Comment by get-itips** [comment]
> @get-itips, I still would like to see what about the "-**ProxyPool**". That in my mind is still missing.

ok for that, we depend on the current author @hirenshah1 or @bjwhalen

**Comment by yogkumgit** [comment]
@hirenshah1 Please help us with your inputs on this issue.

**Comment by hirenshah1** [comment]
@yogkumgit I am not aware about this change. @bjwhalen can clarify

**Comment by yogkumgit** [comment]
@bjwhalen can you please add here your inputs. Sent you an email as well.

**Comment by yogkumgit** [comment]
@bjwhalen Please respond to our query.

**Comment by get-itips** [comment]
@bjwhalen can you please review this thread and respond to our comments? I appreciate

**Comment by get-itips** [comment]
@hirenshah1 Hiren, can you help us here? thanks

**Comment by get-itips** [comment]
Hello @hirenshah1 or @bjwhalen can you help us here? Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Petri-X Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
