### ISSUE TITLE
The 'floor' attribute should accept values other than integers 

### ISSUE THREAD

**Issue by thomascwiley** [MicrosoftDocs/office-docs-powershell#3949]
To provide clarity to end users on locations of meeting rooms, values other than integers should be allowed, For example, 'Basement' or 'Mezzanine' are common architectural features that cannot be labeled simply by a floor number. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ef4fb7-736b-99e8-796b-c1d02410a7e4
* Version Independent ID: 0fb75415-2bd2-a880-aa9e-a06c76d9ddc4
* Content: [Set-Place (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-place?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @thomascwiley, thank you for your feedback.

This is a feature request or update so the proper place to request it is User Voice:
https://office365.uservoice.com/

Docs feedback is to provide a way to improve documents, not products.

Thanks!

**Comment by yogkumgit** [comment]
@thomascwiley  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
