### ISSUE TITLE
Missing Parameter -ShareByEmailEnabled in Docs

### ISSUE THREAD

**Issue by PowerAppMac** [MicrosoftDocs/office-docs-powershell#3952]
In PowerShell and in EXAMPLE 5 there is a parameter -ShareByEmailEnabled

This paremeter is missing in the Command Reference at the top and in the parameter description.

Please have a look.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @PowerAppMac, thank you for your feedback.

Could you please kindly provide me the link to the article? Or at least the cmdlet name.

Thanks!

**Comment by PowerAppMac** [comment]
Hi. 

 

Sure, it’s the “New-PnPSite” cmdlet:

https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpsite?view=sharepoint-ps

 

Regards

Martin

**Comment by dariomws306** [comment]
Thank you @PowerAppMac,

It works for me:
![image](https://user-images.githubusercontent.com/33589238/64614231-63952600-d3ae-11e9-9060-0c51dab9e153.png)

**Comment by dariomws306** [comment]
@PowerAppMac sorry my mistake, I read your comment again and I will update this article adding this parameter.

**Comment by yogkumgit** [comment]
@VesaJuvonen Please merge this PR #2251

**Comment by dariomws306** [comment]
@PowerAppMac - thank you for the proposal. The PnP cmdlet references are a little different than the rest of the references. The PnP 'source' for the reference actually lives in the cmdlet code itself and each release the reference content is copied over here so it is rendered alongside the rest of the Office cmdlets. The source file for this particular cmdlet is located here: https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Files/AddFile.cs The repo is community driven and maintained and I know they would very much appreciate your contribution. I am going to go ahead and close this and let me know if you have any questions or need me to help or research anything on the PnP side.
