### ISSUE TITLE
Missing details on what output type "Team" is

### ISSUE THREAD

**Issue by patware** [MicrosoftDocs/office-docs-powershell#3955]
It would be helpful to learn more about the Output type "Team".  Properties, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8450991f-9f85-4d87-51b3-efa8e1004a24
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/Get-Team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @patware, thank you for your feedback.

Output is a Team object or a list of Teams. And if you run for example "Get-Team -MailNickName BusinessDevelopment" you will see all the properties of this object. Also, in this article you can find more information and description about the properties:
https://docs.microsoft.com/powershell/module/teams/set-team

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @patware 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
