### ISSUE TITLE
Invoke-PnpSiteDesign : Access Denied.  You do not have permission to perform this action or access this resource.

### ISSUE THREAD

**Issue by CaseyRoot** [MicrosoftDocs/office-docs-powershell#3957]
I am randomly getting this message:  Invoke-PnpSiteDesign : Access Denied.  You do not have permission to perform this action or access this resource.  If I try again or shut down my PS and re-open, authenticate to everything - it will run fine or if I wait a few minutes, it will run fine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d2946aa-f7cb-e211-75d3-e8fa432a3aed
* Version Independent ID: 60554dbd-1fb6-2603-64df-bc4e0a0fb233
* Content: [Invoke-PnPSiteDesign (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/invoke-pnpsitedesign?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Invoke-PnPSiteDesign.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Invoke-PnPSiteDesign.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @CaseyRoot Hope you are doing great.
This resource is specifically to report issues in documentation, for issues in cmdlets or support I need to kindly redirect you to other resources, as PnP cmdlets are community-driven, you should start [here](https://docs.microsoft.com/en-us/sharepoint/dev/community/community)

Hope this info helps you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @CaseyRoot 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution.
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
