### ISSUE TITLE
Conference Room attribute filtering is not active after cmdlets run

### ISSUE THREAD

**Issue by jamesavgarcia** [MicrosoftDocs/office-docs-powershell#3958]
I can see the attributes were added to the rooms but when searching for a room the filter option never appears. cmdlets entered 24 hours ago.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by jamesavgarcia** [comment]
Hi Yogesh,
Was there any other cmdlet needing to be run on our online exchange server to enable the search with filtered attributes? I just checked again this morning and the filter drop down is not in the Browse Rooms options.
Regards,
James Garcia

**Comment by dariomws306** [comment]
Hi @jamesavgarcia, thank you for your feedback.

What cmdlets have you ran?

Anyway, I think considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jamesavgarcia** [comment]
![cmdlet](https://user-images.githubusercontent.com/55000083/64556177-8965f080-d304-11e9-9696-e7e514851d17.JPG)

**Comment by jamesavgarcia** [comment]
Thank you. I will open a ticket and follow up later. much appreciated.

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and digging deep into it. @jamesavgarcia 
If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Please keep contributing with your suggestions to improve the documentation.
