### ISSUE TITLE
Related links and Test-PnPSite

### ISSUE THREAD

**Issue by github33** [MicrosoftDocs/office-docs-powershell#3962]
Is there a clean way to test if a site exists? Something like Test-PnPSite would be nice.
Get-PnPSite currently returns the following message:
Get-PnPSite : The remote server returned an error: (403) Forbidden.
At C:\p\SharePointResources.ps1:249 char:25
+ $dataSiteCollection = $(Get-PnPSite).Url
+                         ~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPSite], WebException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Site.GetSite

If there is a better way to check, would you update the samples section. If there is another command which already does this, please update the related links.

Thanks!

**Comment by github33** [comment]
The following flag cleans up the error output: -ErrorAction Ignore

Here's the code example:
Connect –Url $SearchManagedDataUrl -UseWebLogin $UseWebLogin
$Uri = [System.Uri]$SearchManagedDataUrl
$ds = Get-PnPSite -ErrorAction Ignore
$dataSiteCollection = $ds.Url

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @github33 
Thanks for your feedback.
There isn't currently a cmdlet to test if a Site exists, as you might know, PnP cmdlets are community driven so you can propose or even create that cmdlet as its open sourced.
I need to kindly redirect you to [this resource](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps) as a start

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @github33 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
