### ISSUE TITLE
Installation not working, certificate is expired

### ISSUE THREAD

**Issue by dominikgempeler** [MicrosoftDocs/office-docs-powershell#3964]
Hi,

The installation doesn't work (download via EAC), because the certificate is expired since 2019-09-06.
Can you please sign it with new certificate?

Regards
Dominik

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @dominikgempeler, thank you for your feedback.

Could you please provide more detail? What installation? What article are you referring?

**Comment by dominikgempeler** [comment]
Hi @dariomws306 

sure, i download the ClickOnce-Package from Exchange Admin Center (EAC) => Hybrid => Configure
The ClickOnce package is blocked, because the certificate is expired. See screnshot below.
![grafik](https://user-images.githubusercontent.com/15557069/64589359-398b3600-d3a5-11e9-8160-aee626fc9398.png)

Regards
Dominik

**Comment by dariomws306** [comment]
Thank you @dominikgempeler,

Sorry but I cannot reproduce the issue, I don't get the certificate expired error.

Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dominikgempeler** [comment]
Hey @dariomws306 

Thanks for response, i've opened a ticket on portal. I will come back with answer from MS.

Regards
Dominik

**Comment by dominikgempeler** [comment]
Hey Folks,

The Problem was not the expired certificate, but it was the authorization of ClickOnce-Installation.
Here's the according description to set up the authorization:
https://docs.microsoft.com/de-de/visualstudio/deployment/how-to-configure-the-clickonce-trust-prompt-behavior?view=vs-2015&redirectedfrom=MSDN
After this, the expired certificate is shown as warning (module can be installed) instead of failure (module can't be installed).

Regards
Dominik
