### ISSUE TITLE
Difference Between PrimarySmtpAddress and WindowsEmailAddress Parameters

### ISSUE THREAD

**Issue by nakosenk** [MicrosoftDocs/office-docs-powershell#3966]
Both -WindowsEmailAddress and -PrimarySmtpAddress exist as parameters for Set-Mailbox on Exchange On-Premises, but based on the descriptions for the two parameters it sounds like they do the same thing. 

The only difference I see is that PrimarySmtpAddress has it explicitly called out that it shouldn't be used with -EmailAddresses parameter, but -WindowsEmailAddress doesn't call out that same restriction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5b0c5d-0466-d55a-1f7b-0b2d25a316fd
* Version Independent ID: 07b0c093-eb6b-4834-3cd4-d8f2af6ca0f5
* Content: [Set-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Basically, the WindowsEmailAddress parameter isn't very useful in Exchange environments. Previous descriptions of the parameter said as much. But, I discovered in testing that there was some correlation in some environments to the value of this parameter and the important Exchange email properties (currently documented in the parameter description).

Bottom line, if you want to truly set real and effective email addresses, use the PrimarySmtpAddress or EmailAddresses parameters. I'm hard pressed to even explain the primary scenario or purpose of the WindowsEmailAddress parameter in an Exchange environment.

**Comment by dariomws306** [comment]
Thank you @chrisda for your comment.

I think both are similar but as you can see in the description WindowsEmailAddress is an Active Directory attribute that could be present without Exchange. It's the main difference.

**Comment by nakosenk** [comment]
I think that's a problem with the description of the PrimarySmtpAddress parameter. I recently used it to update Exchange email addresses and it updated the Active Directory Mail attribute, as well. That was expected, but not called out in the documentation.

**Comment by dariomws306** [comment]
Ok... We could add some information on PrimarySmtpAddress and EmailAddresses description to let reader know that when you set primary smtp address, WindowsEmailAddress is also set.

What do you think @chrisda?

**Comment by chrisda** [comment]
Any information about the WindowsEmailAddress property/parameter is really just informational; it has nothing to do with Exchange. I've never heard of a scenario where the WindowsEmailAddress parameter in Exchange or even the WindowsEmailAddress property on the AD object is used for anything in an Exchange organization. Maybe the product team thought there was going to be some need or use for it back in the Exchange 2007 days that never materalized. Or maybe there are some third-party apps that use that value (just guessing).

Anyway, if you feel compelled to say something about WindowsEmailAddress in the PrimarySmtpAddress parameter description in this topic, you should consider confirming or seeing how WindowsEmailAddress and PrimarySmtpAddress behave in cmdlets where they both exist:

- Set-RemoteMailbox

- Set-MailPublicFolder

- Set-DistributionGroup

- Set-DynamicDistributionGroup

- Set-MailContact

- Set-MailUser

**Comment by dariomws306** [comment]
Thank you @chrisda!

I will discuss it with my team.

**Comment by shivtorov** [comment]
"WindowsEmailAddress" and "PrimarySmtpAddress/EmailAddresses"  are different attributes in AD.

"EmailAddresses" is 'proxyAddresses' multi-valued attribute. It holds the list of all addresses of an object, e.g. SMTP Addressess, SIP Addresses, EUM addresses, etc. One of the SMTP addresses should be 'primary'. Thus we have "PrimarySmtpAddress" parameter in cmdlets.

"WindowsEmailAddress" is a single string value stored in 'mail' attribute in AD.

Usually, Exchange Server/Admin has AD permissions to modify all mail-related attributes. Thus when you change "PrimarySmtpAddress/EmailAddresses" using cmdlets such as Set-Mailbox, it updates both 'proxyAddresses' and 'mail' attributes.
But nothing stops you to update 'mail' attribute directly.

Software such as Skype For Business Server/client - will always try to use addresses from 'proxyAddresses' attribute. And use value from 'mail' attribute only if 'proxyAddresses' attribute as a last resort

**Comment by shivtorov** [comment]
value in 'mail' attribute is "user-friendly" (=easy to query and "consume" as-is). For example, many application that can intergrate with LDAP directories such as Active Directory, will use value from 'mail' attribute.

on the other hand, the multi-valued attribute 'proxyAddresses' is harder to query. because it contains a list of addresses and each address is in "technical" format. Thus 3rd party software will try to use 'mail' attribute when possible

**Comment by shivtorov** [comment]
from an Exchange admin perspective, we should only care about  "PrimarySmtpAddress/EmailAddresses" ('proxyAddresses'). And Exchange Server will take care about "WindowsEmailAddress"('mail') automajically.

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #4070 , Thanks

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @nakosenk Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
