### ISSUE TITLE
Item types available for backup

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/office-docs-powershell#3972]
It would be useful to have a list of the possibile values for the "Item" parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f23b9aa2-a77c-7ec5-9d81-751a30d70813
* Version Independent ID: c292dbf7-d1c5-7a3b-cc32-0d9b8fb06a8a
* Content: [Backup-SPFarm (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/backup-spfarm?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Backup-SPFarm.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Backup-SPFarm.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
This wouldn't be practical as it includes things like Web Applications which have display names of whatever the admin has configured. Use the `Backup-SPFarm -ShowTree` to see what can be backed up.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by LuigiBruno** [comment]
> @LuigiBruno what I will do is add the information to the document outside of the -ShowTree parameter to make it more clear that this is the path an admin needs to use in order to select items to back up.

Thank you @tseward.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @LuigiBruno Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by LuigiBruno** [comment]
> @tseward  Thank you very much for the contribution and updating the documentation with PR. @LuigiBruno Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

Thank you @yogkumgit.
