### ISSUE TITLE
The parameter -LongerRetentionEnabled is undocumented

### ISSUE THREAD

**Issue by boaz-w** [MicrosoftDocs/office-docs-powershell#3973]
Although it is implemented in the cmdlet itself, the parameter -LongerRetentionEnabled is not documented in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d47105-b32e-f0f8-3e71-db411c6abe7c
* Version Independent ID: 338beb1b-1f13-0a77-9ac3-1c4fe542b612
* Content: [Search-UnifiedAuditLog (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/search-unifiedauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @boaz-w, thank you for your feedback.

I cannot see this parameter implemented:
![image](https://user-images.githubusercontent.com/33589238/65043905-3d353480-d932-11e9-8b1d-4375d0684686.png)

Could you please paste a screenshot? Thanks!

**Comment by boaz-w** [comment]
Sure,
Please find screenshot attached below

![proof_of_longerretentionperiod_edited](https://user-images.githubusercontent.com/43845493/65061838-6c27c680-d983-11e9-9a5e-2ce40156fa3d.jpg)

**Comment by dariomws306** [comment]
Interesting...

Let me try this on different tenants because in my lab I don't have it. It should be something new.

**Comment by dariomws306** [comment]
Hi @chrisda,

Could you kindly help with this? I have tried with 2 different tenants and there I don't have the LongerRetentionEnabled parameter.

Thanks!

**Comment by chrisda** [comment]
I don't see the parameter in the org I tried, either. But I ran this command:

```
Get-ManagementRoleEntry -Identity *\Search-UnifiedAuditLog -Parameters LongerRetentionEnabled
```

And I got results (no error):

```
Name                           Role                      Parameters
----                           ----                      ----------
Search-UnifiedAuditLog         View-Only Audit Logs      {Debug, EndDate, ErrorAction, ErrorVariable...}
Search-UnifiedAuditLog         Audit Logs                {Debug, EndDate, ErrorAction, ErrorVariable...}
```

So the parameter is in there, but it just isn't available to everyone everywhere (yet).

Let's wait a few weeks and see what happens.

**Comment by dariomws306** [comment]
Thank you!

**Comment by dariomws306** [comment]
@boaz-w,

This parameter will be documented when it's publicly available for everyone. We will close this issue.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @boaz-w 
Hope this information is helpful, appreciate your wait. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
