### ISSUE TITLE
-Identity formats

### ISSUE THREAD

**Issue by ryanharnwell** [MicrosoftDocs/office-docs-powershell#3975]
https://docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps

This does not list the valid formats for -identity

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ryanharnwell 
Thanks for your feedback, currently, the article lists the valid formats

> User Identities can be specified using one of the following formats: 1) the user's SIP address; 2) the user's user principal name (UPN); or, 3) the user's Active Directory display name (for example, Ken Myer).

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ryanharnwell 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
