### ISSUE TITLE
Step 2, Kerberos auth

### ISSUE THREAD

**Issue by dmitton42** [MicrosoftDocs/office-docs-powershell#3981]
The example New-PSSession assumes Kerberos authentication is configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b57b66-2364-0e9d-e627-5eeb77238675
* Version Independent ID: 78fd7932-06f9-37c7-8928-250b3884d89e
* Content: [Connect to Exchange servers using remote PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/connect-to-exchange-servers-using-remote-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @dmitton42, thank you for your feedback.

Could you please elaborate further?

**Comment by yogkumgit** [comment]
@dmitton42 Please provide the detail as asked by Dario
