### ISSUE TITLE
Question: Is it possible to the conversations associated with a channel via PowerShell?

### ISSUE THREAD

**Issue by rajivsr23** [MicrosoftDocs/office-docs-powershell#3988]
Hi,

I would like to know whether it is possible to get the conversations associated with a channel via PowerShell?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @rajivsr23 
Your issue is missing the reference of the specific article you are talking about, can  you please specify it here? thanks

**Comment by yogkumgit** [comment]
@rajivsr23 Please provide the details as asked by Andres.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @rajivsr23 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
