### ISSUE TITLE
Get-DlpDetailReport Not Returning Expected Properties

### ISSUE THREAD

**Issue by glamarche** [MicrosoftDocs/office-docs-powershell#3991]
Expected: Date, Title, Location, Severity, Size, Source, Actor, DLPPolicy, UserAction, Justification, SensitiveInformationType, SensitiveInformationCount, SensitiveInformationConfidence, EventType, Action, ObjectId

Actual Output: Date, Object ID, Source, Title; also note time interval is showing from 2019-08-30 to 2019-09-13, expected 7 days based on description in the docs. (https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/get-dlpdetailreport?view=exchange-ps)

Cmdlet run: Get-DlpDetailReport

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @glamarche, thank you for your feedback.

Could you kindly paste a screenshot here? Please try running "Get-DlpDetailReport | fl".

Thanks!

**Comment by yogkumgit** [comment]
@glamarche please reply to Dario's request

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and digging deep into it.  @glamarche We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by glamarche** [comment]
Hi there, 

Thank you for your help. Running Get-DlpDetailReport | fl worked and I was able to refine the fields as needed afterwards. I apologize for the delay in getting back to you.

**Comment by dariomws306** [comment]
Hi @glamarche, you're welcome! I'm happy that it helps you! Don't worry about the delay!
