### ISSUE TITLE
AssociatedMessagesCopyOption default behaviour contradiction

### ISSUE THREAD

**Issue by koolhand** [MicrosoftDocs/office-docs-powershell#3993]
The documentation for the _AssociatedMessagesCopyOption_ parameter for _New-MailboxRestoreRequest_ says two opposing things about default behaviour: that the default is to copy the associated messages, and that the default is to **not** copy the associated messages.

> ### -AssociatedMessagesCopyOption
> 
> The _AssociatedMessagesCopyOption_ parameter specifies whether associated messages are copied when the request is processed. Associated messages are special messages that contain hidden data with information about rules, views, and forms. **By default, associated messages are copied.** This parameter accepts the following values:
> 
> - _DoNotCopy:_ The **associated messages aren't copied. This is the default option.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 514e13f3-66b0-e6ed-a914-4784823665d6
* Version Independent ID: 4028ab31-0d94-8136-bf5b-a49942417900
* Content: [New-MailboxRestoreRequest (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/new-mailboxrestorerequest?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/New-MailboxRestoreRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/New-MailboxRestoreRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #3997

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @koolhand Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
