### ISSUE TITLE
-HiddenFromExchangeClientsEnabled Is not accepting $true or $false as an argument

### ISSUE THREAD

**Issue by NickJongens** [MicrosoftDocs/office-docs-powershell#3994]
Hi Microsoft, 

I've found an issue with the -HiddenFromExchangeClientsEnabled parameter, which does not accept $true or $false as a parameter; unlike the rest of the document's parameters.

However, I have found a workaround below.

Example Group/Identity: Sales

The powershell command that does not work:
Set-UnifiedGroup -Identity Sales -HiddenFromExchangeClientsEnabled $false

The powershell command works with the following modification:
Set-UnifiedGroup -Identity Sales -HiddenFromExchangeClientsEnabled:$false

I had to navigate a few threads online to discover this.
Can you please update the documentation to reflect? 

Kind Regards,

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @NickJongens, thank you for your feedback.

HiddenFromExchangeClientsEnabled is a swith parameter, not a boolean.

If you want to enable/true it you should use in in this way:
Set-UnifiedGroup -Identity Sales -HiddenFromExchangeClientsEnabled

In the parameter description you can see:
"To enable this setting, you don't need to specify a value with this switch."
"To disable this setting, use this exact syntax: -HiddenFromExchangeClientsEnabled:$false"

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @NickJongens Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
