### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by hegedusgyorgy** [MicrosoftDocs/office-docs-powershell#3995]
The article mention, that "In Exchange 2013 or later, use the Set-MobileMailboxPolicy cmdlet instead."
The correct name of the cmdlet is "Set-MobileDeviceMailboxPolicy"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb83f46-4a84-5e82-db10-bb6c47e8c26b
* Version Independent ID: c21fcc84-10e3-23a9-04cc-d444afbc9ac0
* Content: [Set-ActiveSyncMailboxPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/set-activesyncmailboxpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/devices/Set-ActiveSyncMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/Set-ActiveSyncMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
This has been resolved. Thanks for the feedback.
