### ISSUE TITLE
Item count results blank

### ISSUE THREAD

**Issue by tiru007** [MicrosoftDocs/office-docs-powershell#3999]
Following is the code, which we are trying

PS C:\windows\system32> $folder = Get-PnPFolder -RelativeUrl $listUrl

PS C:\windows\system32> $listUrl
Documents

PS C:\windows\system32> $folder

Name      Type   Items/Size Last Modified       
----      ----   ---------- -------------       
Documents Folder      97843 9/16/2019 5:29:33 AM

PS C:\windows\system32> $folder.Files.Count

PS C:\windows\system32> $list.ItemCount
97848

Folder has 97843 items but $folder.files.count returns blank??
is it a limitation or Known issue

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
You need to include the Files.

```
PS C:\> $folder = Get-PnPFolder -RelativeUrl '/Shared Documents/F1' -Includes Files
PS C:\> $folder.Files

Name           Type Items/Size Last Modified
----           ---- ---------- -------------
Document.docx  File      17059 9/17/2019 3:55:04 PM
Document1.docx File      17057 9/17/2019 3:55:24 PM

PS C:\> $folder.Files.Count
2
```

**Comment by tiru007** [comment]
@tseward  if we need to include files, then $folder.files.count should return blank for other libraries aswell. However its working for other library with smaller file count.
Following is the output

PS E:\> $folder

Name      Type   Items/Size Last Modified        
----      ----   ---------- -------------        
Documents Folder         33 9/18/2019 11:32:30 AM

PS E:\> $folder.Files.Count
33

PS E:\> $list.ItemCount
33

**Comment by tseward** [comment]
If you feel this is a product bug, I would raise the issue at https://github.com/SharePoint/PnP-PowerShell/issues.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @tiru007 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
