### ISSUE TITLE
Descriptions missing

### ISSUE THREAD

**Issue by fjuhasz** [MicrosoftDocs/office-docs-powershell#4002]
Hi,
All of the description part of this page is missing.
Could you correct it?
BR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42ac714d-7612-22df-5011-a23fe40f067d
* Version Independent ID: d9ef9157-fc7d-e1a3-fb3f-fc4615638985
* Content: [Set-CsExternalUserCommunicationPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csexternalusercommunicationpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsExternalUserCommunicationPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsExternalUserCommunicationPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @fjuhasz thanks for your feedback, I created a pull request to add some missing descriptions, @tomkau can you please review the PR and help us find the descriptions I could not complete?
Thank YOU

**Comment by tomkau** [comment]
@get-itips   Hi Andres, sorry for the delay.  The PR looks fine, except for -Tenant parameter.  This should have the same description as used with other cmdlets:  "This parameter is reserved for internal Microsoft use."

**Comment by get-itips** [comment]
Hello @tomkau ok I can edit the Tenant description and also could conclude that all other missing descriptions are also for internal use, as they cannot be currently set

**Comment by yogkumgit** [comment]
@tomkau Please merge this PR #4173

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @fjuhasz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
