### ISSUE TITLE
Wrong example for LocaleSetting

### ISSUE THREAD

**Issue by wbach82** [MicrosoftDocs/office-docs-powershell#4004]
using the statet example for localesetting is just showing an error:

PS C:\&gt; Set-Label -Identity general -LocaleSettings {"localeKey":"DisplayName","Settings":[{"Key":"en-us","Value":"English display name"},{"Key":"de-de",Value":"Deutscher Anzeigena
me"},{"Key":"es-es",Value":"Nombre para mostrar en español"}]}
At line:1 char:57
+ ...  -Identity general -LocaleSettings {"localeKey":"DisplayName","Settin ...
+                                                    ~~~~~~~~~~~~~~
Unexpected token ':"DisplayName"' in expression or statement.
At line:1 char:71
+ ... -Identity general -LocaleSettings {"localeKey":"DisplayName","Setting ...
+                                                                 ~
Missing argument in parameter list.
At line:1 char:90
+ ... ettings {"localeKey":"DisplayName","Settings":[{"Key":"en-us","Value" ...
+                                                          ~~~~~~~~
Unexpected token ':"en-us"' in expression or statement.
At line:1 char:98
+ ... ttings {"localeKey":"DisplayName","Settings":[{"Key":"en-us","Value": ...
+                                                                 ~
Missing argument in parameter list.
At line:1 char:137
+ ... {"Key":"en-us","Value":"English display name"},{"Key":"de-de",Value": ...
+                                                          ~~~~~~~~
Unexpected token ':"de-de"' in expression or statement.
At line:1 char:145
+ ... "Key":"en-us","Value":"English display name"},{"Key":"de-de",Value":" ...
+                                                                 ~
Missing argument in parameter list.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS C:\&gt;

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 48f2421f-0e77-dc9c-8dcf-f97a9374b118
* Version Independent ID: b361e69c-8cbc-6ff8-9edd-9babdd3fbe7a
* Content: [Set-Label (exchange)](https://docs.microsoft.com/de-de/powershell/module/exchange/policy-and-compliance/set-label?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance/Set-Label.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance/Set-Label.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by timKittelberger** [comment]
There is a " missing before the Value in the german part. 
'{"localeKey":"DisplayName","Settings":[{"Key":"en-us","Value":"English display name"},{"Key":"de-de","Value":"Deutscher Anzeigename"}]}' works for me

**Comment by dariomws306** [comment]
Hi @wbach82, thank you for your feedback.

I have verified the article and looks like the word value is enclosed between double quotation marks in the german part. Could you kindly check again please?

**Comment by yogkumgit** [comment]
@wbach82 Please reply to @dariomws306 and confirm the change.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and digging deep into it.  @wbach82 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
