### ISSUE TITLE
To create a new Client-Side page named 'NewPage' under a folder.

### ISSUE THREAD

**Issue by pandiarajank** [MicrosoftDocs/office-docs-powershell#4011]
PowerShell:
Add-PnPClientSidePage -Name "YourFolder/NewPage"

Please add this information in this document.
Thanks
Pandiarajan K

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c05ea2e5-4b7b-b4e1-6925-56329dabdb02
* Version Independent ID: c447d008-f5ea-92bc-e29f-9c9baba6b365
* Content: [Add-PnPClientSidePage (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpclientsidepage?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPClientSidePage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPClientSidePage.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @pandiarajank Thanks for your feedback, I created a pull request, referenced here, to propose this example to the article.
Thank You

**Comment by pandiarajank** [comment]
Thanks

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT  Please Merge this PR -  https://github.com/SharePoint/PnP-PowerShell/pull/2270

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT  thanks for clarifying it in the email that it does not belong to you.

**Comment by yogkumgit** [comment]
@VesaJuvonen Please merge this PR - https://github.com/SharePoint/PnP-PowerShell/pull/2270

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @erwinvanhunen thanks for merging this PR. @pandiarajank Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
