### ISSUE TITLE
Incorrect examples and "Identity"/"EffectiveTenantDialPlanName" parameters  descriptions

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#4012]
**_ISSUE 1_**

Second command in Example 1 is incorrect. It currently says:
`Test-CsEffectiveTenantDialPlan -DialedNumber 14258828080 -Identity 5d3ff00a-8d23-42d0-ac9e-32a2c518bc1c_Global_Vt1TenantDialPlan2`

The correct syntax:
**option 1:**
`Test-CsEffectiveTenantDialPlan -DialedNumber 14255551234 -Identity amos.marble@contoso.com`

**option 2:**
`Test-CsEffectiveTenantDialPlan -DialedNumber 14255551234 -EffectiveTenantDialPlanName 1849827b-a810-40a8-8f77-e94250d4680b_TenantDialPlanRedmond_US`

**_ISSUE 2_**

The description for the example 1 is misleading. It currently says:

> This example gets the Identity of a dial plan that is associated with a dialed number, and applies the retrieved tenant dial plan to normalize the dialed number.

Instead of:
_"This example gets the Identity of a dial plan that is associated with **a dialed number**..."_ ,
it should say something like:
_"This example gets the Identity of a dial plan that is associated with **the specified user**..."_ ,

**_ISSUE 3_**
the description of "**-Identity**" parameter says:

> The Identity parameter is the effective tenant dial plan name in the form of TenantId_GlobalVoiceDialPlan_TenantDialPlan

This is wrong. The Identity parameter is, in fact, accept user's identity, e.g. UPN.
Refer to the specification of "Identity" parameter: "Type - **UserIdParameter**"

**_ISSUE 4_**
the description of "**-EffectiveTenantDialPlanName**" is currently empty.
but it should be something like:
"The EffectiveTenantDialPlanName parameter is the effective tenant dial plan name in the form of TenantId_TenantDialPlan_GlobalVoiceDialPlan"

Also note the naming convention "TenantId_TenantDialPlan_GlobalVoiceDialPlan" instead of "TenantId_GlobalVoiceDialPlan_TenantDialPlan"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2b0251-02e7-b708-75d7-36a27938399a
* Version Independent ID: 78212caa-3706-eccf-ea7f-a595b9010b58
* Content: [Test-CsEffectiveTenantDialPlan (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/test-cseffectivetenantdialplan?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Test-CsEffectiveTenantDialPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Test-CsEffectiveTenantDialPlan.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @shivtorov a pull request has been created to fix the examples and descriptions of parameters. Thank you

**Comment by shivtorov** [comment]
Hmmm... I'm not an expert in English, but it looks like the is a grammar mistake in the following sentence:
"This example tests the given dialed number against an specific identity."

**Comment by yogkumgit** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
@yogkumgit  This PR has been merged, so I cannot do a copy review on it. I agree with shivtorov though, that specific sentence is gramatically incorrect.

**Comment by yogkumgit** [comment]
@JohanFreelancer9 please check again. Thanks.

**Comment by yogkumgit** [comment]
@nenonix @JohanFreelancer9 please check and confirm the update. Thanks.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @shivtorov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
