### ISSUE TITLE
Connect to EOP Powershell with MFA

### ISSUE THREAD

**Issue by austinmccollum** [MicrosoftDocs/office-docs-powershell#4015]
We don't have a doc on how to connect to Exchange Online Protection powershell when MFA is required and the solution isn't obvious.  For example to list ATP policies, we need the EOP commandlets like this: **Get-AtpPolicyForO365**

Here's the analagous articles:
Security and Compliance [https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell?view=exchange-ps] 
Exchange Online [https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps]

The solution is to use the Exchange Online Powershell module for MFA and use the following syntax:

Connect-IPPSSession -UserPrincipalName admin@m365x986865.onmicrosoft.com -ConnectionUri https://ps.protection.outlook.com/powershell-liveid/

This is contrasted with the syntax for connecting to Security and Compliance with MFA is just
Connect-IPPSSession -UserPrincipalName admin@m365x986865.onmicrosoft.com

or Exchange Online with MFA
$EXOSession = New-ExoPSSession -UserPrincipalName admin@m365x986865.onmicrosoft.com
Import-PSSession $EXOSession -Prefix EXO

More Information:
Unlike Exchange Online, once you connect to EOP, it breaks connection to EXO and Security/Compliance center powershell, and vice versa.  There is no "new-EopPSSession" like there is for new-ExoPSSession.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5aa434-8ccb-43a3-3f3b-f400e4663b2f
* Version Independent ID: 8a7187a1-fe53-6bf0-b517-6225c8cb3233
* Content: [Connect to Exchange Online Protection PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-eop/connect-to-exchange-online-protection-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-eop/connect-to-exchange-online-protection-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-eop/connect-to-exchange-online-protection-powershell.md)
* Service: **eop**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Are you using MFA to connect to standalone EOP Standard (not EOP Premium)?

EOP PowerShell in the context of regular Office 365 offerings that already include EOP isn't necessary; everything should already be available in Exchange Online PowerShell.

It's only when you don't have Exchange Online like in standalone EOP offerings that you need to use EOP PowerShell. And even then, standalone EOP Premium (Exchange Enterprise CAL with Services subscriptions) use the regular Exchange Online PowerShell Uri value to connect, so it's basically a subset of Exchange Online PowerShell without mailboxes and other related features/cmdlets.

The only cmdlets that are absolutely unique to EOP PowerShell are only available in standalone EOP Standard: New/Remove/Set-EOPDistributionGroup, New/Remove/Set-EOPMailUser, Set-EOPUser, and Update-EOPDistributionGroupMemember. All other andti-spam, andti-malware, etc. cmdlets are also available in Exchange Online PowerShell (which is the same PowerShell that's used by standalone EOP Premium).

**Comment by austinmccollum** [comment]
Ahhh… you’re right, thanks for that clarification.  The EOP and ATP commands are all part of the Exchange Online session.  I had assumed they would be part of the security and compliance and when I didn’t see them available from there… well, thanks for clearing that up!

-austinmc

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
As a result of this issue, I've updated the language in the EOP PowerShell topics to emphasize standalone.

Thanks for the feedback.
