### ISSUE TITLE
Add an Application Customizer to SharePoint 2019 Sites

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/office-docs-powershell#4016]
I've built and deployed an Application Customizer to SharePoint 2019. It's in the App Catalog, and I can add it to a site manually by going to Site Contents / New App / From Your Organization / Click on the Application Customizer. It gets installed and works as I would expect.

Now I want to add that same Application Customizer to many different sites in the SharePoint 2019 farm, so I've turned to PowerShell. The `Add-PnPCustomAction` cmdlet is available in the 2019 module, I can run it, and see that the app seems to be added by then running `Get-PnPCustomAction`. But the app actually never shows up in the site.

Should this work? 

See my issue in sp-dev-docs for more details: https://github.com/SharePoint/sp-dev-docs/issues/4655

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3351c6-d699-d519-cf03-e6e5bd0eac70
* Version Independent ID: 84b1728c-a818-b4b9-b63f-1630a1eb056d
* Content: [Add-PnPCustomAction (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpcustomaction?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPCustomAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPCustomAction.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by sympmarc** [comment]
Turns out I need to run `Install-PnPApp` on the site before `Add-PnPCustomAction`. Might be a good addition to this doc. 
https://github.com/SharePoint/sp-dev-docs/issues/4655

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sympmarc Marc, thanks for your feedback. Created a pull request to propose adding this to the article.
Thank you

**Comment by sympmarc** [comment]
Sure thing. Thanks for the follow up!

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please Merge this PR - Added the need to run Install-PnpApp #2273

**Comment by yogkumgit** [comment]
@MikeBazMSFT Please merge this PR - https://github.com/SharePoint/PnP-PowerShell/pull/2273

**Comment by MikeBazMSFT** [comment]
@yogkumgit I'm not the content owner.  Not sure who you were going for here but it's not me.

**Comment by yogkumgit** [comment]
@MikeBazMSFT  it was wrong pick from the list. apologies.

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT  Please merge this PR - SharePoint/PnP-PowerShell#2273

**Comment by MikePlumleyMSFT** [comment]
@yogkumgit I'm also not the content owner for this article.

**Comment by yogkumgit** [comment]
@VesaJuvonen Please merge this PR - https://github.com/SharePoint/PnP-PowerShell/pull/2273

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @erwinvanhunen tahnks for merging this PR. @sympmarc Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
