### ISSUE TITLE
-Owners parameter does not seem to exist

### ISSUE THREAD

**Issue by Zerg00s** [MicrosoftDocs/office-docs-powershell#4017]
The page mentions the '-Owners' parameter, but it does not seem to exist. 

New-PnPSite : A parameter cannot be found that matches parameter name 'Owners'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5e3530-a63e-71ce-97c8-c904619aafa8
* Version Independent ID: 2c961b64-5c27-6331-b704-716ccfb8c5a7
* Content: [New-PnPSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Zerg00s** [comment]
Turns out that  -Owners parameter is only available for the Modern Team sites:

![image](https://user-images.githubusercontent.com/2797648/65209583-a027e800-da66-11e9-9c5f-cb6b4c4d1deb.png)

**Comment by siljemda** [comment]
Shouldn't this be updated in the docs before the issue is closed?

**Comment by Zerg00s** [comment]
@siljemda, -Owner switch actually exists. It's just not clear which parameter set has it. So I decided to close it. Of course, better documentation would be nice, but it would be a different issue.

**Comment by silmer** [comment]
Thanks, opened another issue for this.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Zerg00s 
@erwinvanhunen has confirmed that the cmdlet's Owner parameter now supports communications sites. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Zerg00s Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
