### ISSUE TITLE
Minor, but effective, typo

### ISSUE THREAD

**Issue by dogban** [MicrosoftDocs/office-docs-powershell#4021]
The line below, which is in the "connect with MFA" section, has a small typo that is very effective in breaking the meaning of the whole string:
$EXOSession=New-ExoPSSSession -UserPrincipalName &lt;UPN&gt; [-ConnectionUri &lt;ConnectionUri&gt; -AzureADAuthorizationEndPointUri &lt;AzureADUri&gt;]

the 'New-ExoPSSSession' part has too may S, it should read 'New-ExoPSSession'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b188049-5302-25da-5bd2-89401be1db96
* Version Independent ID: a1d18859-a50d-acd2-1ef1-3729925dc1f1
* Content: [Connect to Office 365 Security & Compliance Center PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell.md)
* Service: **o365-security-and-compliance**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Fixed. But, in the future, you can, too. No need to open an issue; just make the fix using the directions here: https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md.

Thanks for the feedback.
