### ISSUE TITLE
Connecting with PowerShell to Exchange Online when your IDP is not exposed externally

### ISSUE THREAD

**Issue by BrettMcClellan** [MicrosoftDocs/office-docs-powershell#4023]
You should make a note somewhere in this article that if your tenant is federated with ADFS, OKTA, PING etc, and your iDP is not exposed publicly, you will not be able to connect to Exchange Online PowerShell with a Federated account.  You will need to create a Cloud Account, grant the appropriate permissions and then follow the steps in this article using the Cloud Account.

We spent numerous hours troubleshooting this within our team as well as Microsoft support before we stumbled upon this solution.

The issue is that Exchange Online PowerShell cannot authenticate the account because the IDP/STS is not reachable. Another solution is to switch the PTA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
OK. Done. I added a bullet at the end of the "How do you know this worked?" section. Feel free to tweak if necessary (https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md).

Thanks for the feedback.

**Comment by BrettMcClellan** [comment]
Looks good!

Thanks!

Brett McClellan
Infrastructure Engineering Specialist
Brett_McClellan@otpp.com
Direct +1 (416) 7306637
www.otpp.com


Ontario Teachers' Pension Plan
5650 Yonge Street, Toronto, Ontario M2M 4H5, Canada

[X]

[X]<http://facebook.com/myOTPP>[X]<http://twitter.com/otppinfo>[X]<http://youtube.com/otppinfo>[X]<https://www.otpp.com/linkedin>

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and updating the documentation. @BrettMcClellan Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
