### ISSUE TITLE
Experimental Feature?

### ISSUE THREAD

**Issue by Anonimiss** [MicrosoftDocs/office-docs-powershell#4026]
When I run the Set-PnPHomeSite command, I get the following error:

"Set-PnPHomeSite : The requested operation is part of an experimental feature that is not supported in the current
environment."

I was under the impression this was pushed.  Am I just too early, or is there really an issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12da9c12-7eff-f43f-67ff-d667d12847d4
* Version Independent ID: bf90101d-939a-08b0-79fd-1032f00eccc7
* Content: [Set-PnPHomeSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnphomesite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPHomeSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPHomeSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Anonimiss Thanks for your feedback.
PnP cmdlets as you might know, are a community-driven effort and are constantly evolving, the documentation for the PnP cmdlets is directly synchronized from the source code in [this repo](https://github.com/SharePoint/PnP-PowerShell) so if a new cmdlet is created there, there will be an article here, even though the feature can be experimental and in development. So there is no really an issue, it is just not ready yet.
Hope this information helps you. Thanks again

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Anonimiss 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
