### ISSUE TITLE
Microsoft Exchange Online PowerShell -> Standardise and Move to PSGallery

### ISSUE THREAD

**Issue by ZanattaMichael** [MicrosoftDocs/office-docs-powershell#4027]
This "module" (A combination of a binary module and some PS functions) needs to be standardized into a PSM1 or PSD1 and moved into the PS Script gallery. This module is not ready for Automation.

The following will need to be completed to bring it up to scratch:

1. Refactor of CreateExoPSSession.ps1 into C#. This does not need to be PowerShell.
1. Compile PowerShell Module with PSM1 and PSD1.
1. Update of Microsoft.Online.CSE.PSModule.Client.exe. I understand that intended use here, and requires a small tweak:
"Import-Module moduleName" (Current this is done in the CreateExoPSSession.ps1)
1. Addition of Support for PSCore. I can see that your are using Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms. PSCore 7 supports XAML and Winforms.
1. Code Signing. Please sign your code.

Thanks,

PowerShellMichael.

**Comment by ZanattaMichael** [comment]
Please let me know if you would like help with refactoring the code to support this.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @ZanattaMichael, thank you for your feedback.

I think you are suggesting a new feature or product update. We are here to help with docs fix/update, to suggest new features please go to:
https://office365.uservoice.com/

Thanks again!

**Comment by yogkumgit** [comment]
@ZanattaMichael  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
