### ISSUE TITLE
Include description for all commands

### ISSUE THREAD

**Issue by nanddeepn** [MicrosoftDocs/office-docs-powershell#4038]
Most of the command have description missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428a5954-392c-f7ad-bac4-553adf74e08e
* Version Independent ID: 44fdecf2-1977-3171-9d04-02c0fefb16c9
* Content: [Set-SPOTenant (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by nanddeepn** [comment]
Thanks @yogkumgit 
PR is raised for this https://github.com/MicrosoftDocs/office-docs-powershell/pull/4039
Please review.

**Comment by yogkumgit** [comment]
@get-itips  and @tseward  please review this PR #4039

**Comment by yogkumgit** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR #4039 . Thanks.

**Comment by JohanFreelancer9** [comment]
Copy Review for PR #4039 done.

**Comment by yogkumgit** [comment]
@get-itips and @tseward please review this PR #4039

**Comment by yogkumgit** [comment]
@trent-green Please merge the PR #4039 , Thanks

**Comment by nanddeepn** [comment]
Hi,
Please let me know, if any additional inputs needed for this PR. Thanks!

**Comment by yogkumgit** [comment]
@nanddeepn Thanks for the follow up. Awaitng @trent-green to merge this PR

**Comment by nanddeepn** [comment]
I could not see this implemented. Any reasons to close?

**Comment by nanddeepn** [comment]
@trent-green , @yogkumgit 
Can you please help to merge this PR.
Thank you in advance

**Comment by yogkumgit** [comment]
@nanddeepn PR is merged and reflected.

**Comment by yogkumgit** [comment]
@nanddeepn Thank you very much for the contribution and updating the documentation with PR. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
