### ISSUE TITLE
ZoneEmphasis parameter not working in Add-PnPClientSidePageSection

### ISSUE THREAD

**Issue by kadu-jr** [MicrosoftDocs/office-docs-powershell#4044]
When using the [Add-PnPClientSidePageSection](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpclientsidepagesection?view=sharepoint-ps) command, the -ZoneEmphasis parameter does not work, No matter what value I set between 0 and 3, the new page section always comes out without background.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @kadu-jr thanks for  your feedback,
I could not reproduce what you describe, are you using Sharepoint Online or Sharepoint Server 2019 as the article says?

**Comment by kadu-jr** [comment]
Hello @get-itips, yes I am using SharePoint Online and the latest version of the PnP powershell. Upon further inspection, I've found [this ](https://github.com/SharePoint/PnP-Sites-Core/issues/2401) issue with the PnP-Powershell that may be the cause of the problem. I noticed every value that I set as argument for this parameter is sent to SharePoint as a string. And if I manually convert it to int after I send the value it seems to work(using REST for example). So my guess is I should wait for this issue to be fixed and try again.

Did you set the ZoneEmphasis successfully using this command?

**Comment by get-itips** [comment]
Hello @kadu-jr I think I did but maybe is not the same scenario as yours, good find! I suggest you add your experience to that thread and follow up there, as this issue repo is specifically to address issues in documentation. Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @kadu-jr 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
