### ISSUE TITLE
Set-PnpTenantCDNPolicy not supporting ExcludeIfNoScriptDisabled

### ISSUE THREAD

**Issue by NikCharlebois** [MicrosoftDocs/office-docs-powershell#4047]
It does not appear as if 'ExcludeIfNoScriptDisabled' was a valid PolicyType value for the Set-PnPTenantCdnPolicy cmdlet. It always throws out the error:

Set-PnPTenantCdnPolicy : The method or operation is not implemented.

When trying to set it. E.g.

Set-PnPTenantCdnPolicy -CDNType 'Private' `
                               -PolicyType 'ExcludeIfNoScriptDisabled' `
                               -PolicyValue 'False'

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello, I see that you opened an issue in the PnP-Powershell https://github.com/SharePoint/PnP-PowerShell/issues/2271 which is the best repo as this is limited for documentation issues. Please follow up there. Thanks

**Comment by NikCharlebois** [comment]
Will do. Closing for now
