### ISSUE TITLE
Clarity about -Owners parameter

### ISSUE THREAD

**Issue by silmer** [MicrosoftDocs/office-docs-powershell#4050]
It would be helpful if the documentation specified that the -Owners parameter can only be used when creating new TeamSites.

Ref https://github.com/MicrosoftDocs/office-docs-powershell/issues/4017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5e3530-a63e-71ce-97c8-c904619aafa8
* Version Independent ID: 2c961b64-5c27-6331-b704-716ccfb8c5a7
* Content: [New-PnPSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
This shouldn't need to be explicitly pointed out in the doc, but rather the parameter sets fixed. By fixing the parameter sets, this would bring it in line with other documentation.

**Comment by get-itips** [comment]
Hello everyone!
I could check the parameter set and it is correctly identified as a team site parameter, but I am also proposing adding this into the article, in the end it is @erwinvanhunen or @VesaJuvonen choice to keep it.

**Comment by get-itips** [comment]
Hello @silmer 
@erwinvanhunen has confirmed that the cmdlet's Owner parameter now supports communications sites.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @silmer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
