### ISSUE TITLE
TentativePendingApproval does not function as described 

### ISSUE THREAD

**Issue by alex-behrens** [MicrosoftDocs/office-docs-powershell#4059]
Apologies if this is not the place for this. I have a resource mailbox with AutomaticProcessing set to AutoAccept, and both TentativePendingApproval and AddNewRequestsTentatively set to false. 

When a user makes an out-of-policy request, the meeting is still shown in the calendar tentatively (I would like it to appear as free until the meeting is accepted).

Get-CalendarProcessing output here: [https://pastebin.com/rUZWu5t7](https://pastebin.com/rUZWu5t7)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @alex-behrens, thank you for your feedback.

I have tested it on EXO and it works for me. My room configuration:

PS C:\Users\Dario> Get-CalendarProcessing "Conf Room Baker" | fl

RunspaceId                          : 7bd52661-376c-4ffd-bd74-97e8deffa5d5
AutomateProcessing                  : AutoAccept
AllowConflicts                      : False
BookingType                         : Standard
BookingWindowInDays                 : 180
MaximumDurationInMinutes            : 1440
AllowRecurringMeetings              : True
EnforceSchedulingHorizon            : True
ScheduleOnlyDuringWorkHours         : False
ConflictPercentageAllowed           : 0
MaximumConflictInstances            : 0
ForwardRequestsToDelegates          : True
DeleteAttachments                   : True
DeleteComments                      : True
RemovePrivateProperty               : True
DeleteSubject                       : True
AddOrganizerToSubject               : True
DeleteNonCalendarItems              : True
TentativePendingApproval            : True
EnableResponseDetails               : True
OrganizerInfo                       : True
ResourceDelegates                   : {MeganB}
RequestOutOfPolicy                  : {}
AllRequestOutOfPolicy               : False
BookInPolicy                        : {}
AllBookInPolicy                     : False
RequestInPolicy                     : {}
AllRequestInPolicy                  : True
AddAdditionalResponse               : False
AdditionalResponse                  :
RemoveOldMeetingMessages            : True
AddNewRequestsTentatively           : True
ProcessExternalMeetingMessages      : False
RemoveForwardedMeetingNotifications : False
MailboxOwnerId                      : Conf Room Baker
Identity                            : Conf Room Baker
IsValid                             : True
ObjectState                         : Changed

**Comment by alex-behrens** [comment]
Thanks @dariomws306 

My question has been answered on another page: [https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_win10-mso_o365b/exchange-online-unapproved-meeting-requests-to/129656bf-d156-49f2-8979-1b9a5ca936fd?messageId=13f3b7ae-c090-4383-a382-8b56c8f7ab4d](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_win10-mso_o365b/exchange-online-unapproved-meeting-requests-to/129656bf-d156-49f2-8979-1b9a5ca936fd?messageId=13f3b7ae-c090-4383-a382-8b56c8f7ab4d) 

The short of it is that I had misinterpreted the wording on the TentativePendingApproval flag to mean that the booking would not be shown in the calendar at all, but in fact it is shown but with the status on the meeting set to 'free'.

Alex
