### ISSUE TITLE
-SendOofMessageToOriginatorEnabled:- The default value is False

### ISSUE THREAD

**Issue by Asrafalim** [MicrosoftDocs/office-docs-powershell#4060]
We need to modify below statement:-

The SendOofMessageToOriginatorEnabled parameter specifies how to handle out of office (OOF) messages for members of the group. Valid values are:

$true: When messages are sent to the group, OOF messages for any of the group members are sent to the message sender. This is the default value. (This is wrong)
	
$false: When messages are sent to the group, OOF messages for any of the group members aren't sent to the message sender. This is the default value. 

Please update and confirm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f2a78c2-a2e3-ce26-7ffb-2caa9a6622a3
* Version Independent ID: 2a579c6c-8a7d-df6f-dd27-b373fee14ee1
* Content: [Set-DistributionGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-distributiongroup?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Set-DistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Set-DistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @Asrafalim Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
