### ISSUE TITLE
Teams, all policies cmdlets failes

### ISSUE THREAD

**Issue by HaraldPfirmann** [MicrosoftDocs/office-docs-powershell#4064]
Hello

I´m use the new MicrosoftTeams 1.0.2, and tests the follow cmdlets:
Get-CsPolicyPackage
Get-CsUserPolicyPackage
Get-CsUserPolicyPackageRecommendation
Grant-CsPUsersPolicyPackage
All failes with error 'At least one error has occurred'

Best regards

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by saragava** [comment]
@HaraldPfirmann would you be able to provide me your tenant id so we could take a closer look. Feel free to reach our to me directly.

**Comment by kenwith** [comment]
I just wanted to remind that this is a public comment area and focused on the docs. I want to make sure no confidential tenant information is passed here please. It sounds like maybe the best option would be to open a support ticket through the Admin Center in your Office 365 tenant.

**Comment by saragava** [comment]
Agreed with @kenwith, please do file a ticket and we'll look into this.

**Comment by HaraldPfirmann** [comment]
Hi

I have this error on 2 different instances. I´m think ist a Problem in the cmdlet and not in the tenant.

Best regards

**Comment by get-itips** [comment]
Hello @HaraldPfirmann 
If you read [this article](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-policy-packages) it says 

> This is a preview or early release feature.

So that feature appears not be ready for production use, I suggest you either wait for it to be available in your tenant or open a ticket as suggested to ask when it will be available.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @HaraldPfirmann 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
