### ISSUE TITLE
Disable page feature "You may also be interested in"

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/office-docs-powershell#4065]
Please provide information on the property switch to disable the page feature "You may also be interested in".
We need to be able to turn this off via PowerShell for all/multiple specific sites, in the same way that we can with these:

Set-SPOSite
   [-CommentsOnSitePagesDisabled <Boolean>]
   [-SocialBarOnSitePagesDisabled <Boolean>]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1c6b2b-5af6-acce-b7e8-bf784bb0973e
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @angoo-atea can you please share a screenshot of what you see in your tenant?
Tried to reproduce in my lab tenant but the feature is not showing up.
Thank you

**Comment by angoo-atea** [comment]
@get-itips 
![image](https://user-images.githubusercontent.com/29600904/66046749-addd7300-e526-11e9-966b-eadbb884d65e.png)

**Comment by get-itips** [comment]
Hello @trent-green is this feature called _RecommendedItems_ at SC level ?

**Comment by whoisbex** [comment]
Isn't is this under Site Features?

![image](https://user-images.githubusercontent.com/56100700/66094397-39164180-e5d7-11e9-9457-68c3e51c131e.png)

**Comment by angoo-atea** [comment]
@whoisbex - that is the feature that I suspect is the one. We need to be able to turn this off via PowerShell for all/multiple specific sites, in the sam way that we can with these:

Set-SPOSite
   [-CommentsOnSitePagesDisabled <Boolean>]
   [-SocialBarOnSitePagesDisabled <Boolean>]

**Comment by get-itips** [comment]
@angoo-atea @whoisbex I too suspect is the one, but as the feature is not showing up in my tenant I can not confirm, and we should wait for @trent-green confirmation.

Besides that, for any new feature for the Set-SPOSite cmdlet [I suggest a user voice suggestion](https://sharepoint.uservoice.com/)

**Comment by trent-green** [comment]
@get-itips there is currently no parameter on Set-SPOSite for this.  The only way to enable or disable this via powershell is with PNP

https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/disable-pnpfeature?view=sharepoint-ps

**Comment by get-itips** [comment]
> @get-itips there is currently no parameter on Set-SPOSite for this. The only way to enable or disable this via powershell is with PNP
> 
> https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/disable-pnpfeature?view=sharepoint-ps

That is clear. What I am trying to find out for the issue creator is the name of the feature, is it RecommendedItems ?

Thanks.

**Comment by trent-green** [comment]
@whoisbex has the correct feature above, "SharePoint Recommendations"

Thanks!

**Comment by trent-green** [comment]
The Feature GUID is: '780AC353-EAF8-4AC2-8C47-536D93C03FD6'

**Comment by get-itips** [comment]
> The Feature GUID is: '780AC353-EAF8-4AC2-8C47-536D93C03FD6'

Ok so that is the same GUID I found out and the feature internally is called RecommendedItems as I mentioned earlier, and appears in the UI as "Sharepoint Recommendations" as @whoisbex could find out.
We will proceed closing  this one. Thanks to everybody.

**Comment by yogkumgit** [comment]
@get-itips and @trent-green  Thank you very much for the contribution and sharing this explanation. @angoo-atea Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by angoo-atea** [comment]
> 
> @get-itips there is currently no parameter on Set-SPOSite for this. The only way to enable or disable this via powershell is with PNP
> 
> https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/disable-pnpfeature?view=sharepoint-ps

@yogkumgit Thanks, the input is useful. However @get-itips @trent-green - will there be an addition to the Set-SPOSite command for this? It would make sense to include it.

**Comment by get-itips** [comment]
Hello @angoo-atea for that inquiry I need to kindly redirect you to [Sharepoint User Voice ](https://sharepoint.uservoice.com/) where your proposal can be taken care of. As this issue system is specific to address issues in documentation.
Thank you
