### ISSUE TITLE
Duplicate examples

### ISSUE THREAD

**Issue by msbeane443** [MicrosoftDocs/office-docs-powershell#4067]
Example 1 and Example 2 are identical except for the Identity of the mailbox.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d6d7e2-723a-47de-6c0b-bb0b061fcc8a
* Version Independent ID: 58558238-fa67-2cb6-d68f-ec07b151323d
* Content: [Set-MailboxSpellingConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-mailboxspellingconfiguration?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-MailboxSpellingConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-MailboxSpellingConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @msbeane443 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
