### ISSUE TITLE
Needs info on potential wait time

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/office-docs-powershell#4068]
Though executing the PowerShell is quick, it seems that it actually takes some time for the new Org Assets Library to show up for users. 

I've created two and Get-SPOOrgAssetsLibrary reports the existence of both, but I've been waiting ~10 minutes for my second one to show up.

How long should I wait before assuming there was a problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8deb61c-91a1-7e4c-cf56-d682026c6011
* Version Independent ID: 7d8c994d-8673-27dc-04ab-3c5c104c0daa
* Content: [Add-SPOOrgAssetsLibrary (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spoorgassetslibrary?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md)
* Service: **sharepoint-powershell**
* GitHub Login: @Maralesfahanpoor
* Microsoft Alias: **maesfaha**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by RachelLambert34** [comment]
Hi Jim,

I've seen it take anywhere from an hour to almost a full day for the assets library to start showing up for users. I noticed your comment was from a couple days ago, is it still not showing up?

Thanks!
Rachel

**Comment by sparkitect** [comment]
It is there now, yes.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @sparkitect Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
