### ISSUE TITLE
unable to set a group as a siteCollectionAdmin

### ISSUE THREAD

**Issue by ImNotSerious** [MicrosoftDocs/office-docs-powershell#4069]
I can run the command successfully to set a user as a siteCollection Admin:

Set-SPOUser -Site 'https://FOO-my.sharepoint.com/personal/first_last_FOO_com' -LoginName Admusr@FOO.onmicrosoft.com -IsSiteCollectionAdmin $false -ErrorAction SilentlyContinue

but if I try to do the same thing with the objectID of a group or its id ($DKJLFDS0-3243H4HF), it fails 
"Set-SPOUser : The user does not exist or is not unique."

if I add the group from the SharePoint admin site and then  run a
Get-SPOUser -Site 'https://FOO-my.sharepoint.com/personal/first_last_FOO_com' |FL
it shows the ObjectID as the Login Name.

there is no Set-SPOGroup and Get-SPOGroup commands. What I am trying to do is go back and fix 1000s of accounts that were set with a single user as the admin, and put a group in there that we can control access and monitor, as well as allow us to easily migrate user Home drives with the sharepoint migrator. as it stands now, I need manually give myself or the group permissions to the OneDrive before I can migrate.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello,

I could successfully use the **claims encoded identity** of a security group in Set-SPOUser:

![image](https://user-images.githubusercontent.com/36666927/66046221-b1a7d000-e4fb-11e9-9695-87010217d5ca.png)

![image](https://user-images.githubusercontent.com/36666927/66046238-c08e8280-e4fb-11e9-84c3-0826288efd1b.png)

Hope this info helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ImNotSerious 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ImNotSerious** [comment]
Thank you, that did help. I was just using the object ID without prepending the Claims encoding tag
c:0t.c|tenant|
