### ISSUE TITLE
Missing param for 'ResetRoleInheritance'

### ISSUE THREAD

**Issue by kachihro** [MicrosoftDocs/office-docs-powershell#4071]
Doco doesn't mention the flag for 'reset role inheritence' - with the ability to 'delete inherited permissions'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbab5a2d-0c37-bb2c-f2d9-989bc2a59d05
* Version Independent ID: 2f512ab6-be40-1fb2-9f8a-d1bc692537ce
* Content: [Set-PnPList (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplist?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPList.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @kachihro 
I need to kindly redirect you to another resource, PnP cmdlets issues should be opened [here](https://github.com/SharePoint/PnP-PowerShell/issues) please first do a search to see if it already exists.
PnP cmdlets are community-driven, that means that anyone can propose changes to them thru a pull request into [the source code](https://github.com/SharePoint/PnP-PowerShell/blob/dev/Commands/Lists/SetList.cs) 
PnP cmdlets documentation is directly reflected from CmdLet's source code documentation, if you decide to propose adding the documentation for that parameter please read and follow the PnP guidelines.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @kachihro 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by kachihro** [comment]
Thanks - but I didn't actually submit an issue - I'd added a page comment here ;
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplist

So - you can reopen, or redirect wherever.   I was just adding a comment.

**Comment by get-itips** [comment]
@kachihro Certainly, and your comment is welcome, I said issue because when you add a comment at the bottom of an article, you are actually opening an issue in the GitHub issue system. Thank you!
