### ISSUE TITLE
how to get latest Staffhub module to include Move-StaffHubTeam as it is not available in v.1.0.2?

### ISSUE THREAD

**Issue by ahsanranjha** [MicrosoftDocs/office-docs-powershell#4072]
We tried to move staffhub to teams but we are not able to install latest version of staffhub module.

**Comment by get-itips** [comment]
The cmdlet is present now in the last version of the module. (1.0.7)

**Comment by yogkumgit** [comment]
@get-itips  Thanks forthe confirmation. @ahsanranjha Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
