### ISSUE TITLE
Created Content Type has Title column marked as Hidden

### ISSUE THREAD

**Issue by hasannaqvi83** [MicrosoftDocs/office-docs-powershell#4083]
After creating site content type using below statements the content type has Title field marked as hidden.

Any idea why ?

$itemCt = Get-PnPContentType -Identity 'Item'
Add-PnPContentType -Name 'Office' -ParentContentType $itemCt -Group $fieldAndCTGroup -ErrorAction SilentlyContinue -Description "Create a new Office Location"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54c6c7b2-e062-2c5e-406b-a15b7aa098e7
* Version Independent ID: 74db5b97-e2f5-dd07-ed22-00b2bd687847
* Content: [Add-PnPContentType (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpcontenttype?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPContentType.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPContentType.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @hasannaqvi83 

I need to kindly redirect you to another resource, PnP cmdlets issues should be opened [here](https://github.com/SharePoint/PnP-PowerShell/issues) please first do a search to see if a similar issue already exists.
PnP cmdlets are community-driven, that means that anyone can propose changes to them thru a pull request into the [source code](https://github.com/SharePoint/PnP-PowerShell)
PnP cmdlets documentation is directly reflected from CmdLet's source code documentation, if you decide to propose modifying the documentation for that parameter please read and follow the PnP guidelines.
**Thank you**

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @hasannaqvi83 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
