### ISSUE TITLE
Sitedesign visible for global administrators

### ISSUE THREAD

**Issue by markgort86** [MicrosoftDocs/office-docs-powershell#4086]
When using this command Grant-SPOSiteDesignRights at a site design. Is it normal behavior that this site design is visible for users that has the global administrator role? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e76298-d276-880e-dec5-0100172b7c7f
* Version Independent ID: 8cf76988-d97c-4b8f-5cba-9038960e6364
* Content: [Grant-SPOSiteDesignRights (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/grant-spositedesignrights?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Grant-SPOSiteDesignRights.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Grant-SPOSiteDesignRights.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @markgort86 
I could verify that is the current and expected behavior.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @markgort86 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
