### ISSUE TITLE
the -Mailbox parameter should NOT be specified when removing a rule and specifying the rule's Identity as parameter.

### ISSUE THREAD

**Issue by jflieben** [MicrosoftDocs/office-docs-powershell#4087]
and if you DO specify the mailbox it should be removed from: "You can't use both the Identity and Mailbox parameters to specify a mailbox."

So, the example in this documentation should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb1ec53-bdea-dd2e-9714-d6e746c93f1f
* Version Independent ID: fa4e7014-b5d5-7e43-b56f-5382d3270fbc
* Content: [Remove-InboxRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/remove-inboxrule?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Remove-InboxRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Remove-InboxRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @jflieben, thank you for your feedback.

It works in my lab:
![image](https://user-images.githubusercontent.com/33589238/66084256-92816080-e544-11e9-8fff-88b229e7b795.png)

**Comment by jflieben** [comment]
Are you using the remote PS module for MFA that has to be installed through the EXO portal? (cuz I was, could be a relevant variable)

**Comment by dariomws306** [comment]
No, but I have used it now and also works. (without MFA enabled)

I should suggest that you please open a support ticket to check it. We are here to help to improve documentation and I think I cannot help you more with this issue.

If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jflieben** [comment]
hmm, still keeps happening here, but it works when not specifying the mailbox so for now I'll close this.
