### ISSUE TITLE
Using @ in exchange powershell remoting (2010)

### ISSUE THREAD

**Issue by vlciho** [MicrosoftDocs/office-docs-powershell#4089]
Hello,

how can i use this:
`Set-MailPublicFolder -Identity Set-MailPublicFolder -Identity "CN=PF1,CN=Microsoft Exchange System Objects,DC=xxxxxxx,DC=local" -GrantSendOnBehalfTo @{add='domain\john.doe'}` in vb.net?

VisualStudio say error, cannot find object @{add='domain\john.doe'}.

Thank you!

vlci

code:
```
            Dim strvalue As String = "@add=""domain\" & _username & ""
            Dim R2 As System.Management.Automation.Runspaces.Runspace = System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(pConnectionInfo)
            R2.Open()
            Dim P2 As System.Management.Automation.Runspaces.Pipeline = R2.CreatePipeline()
            Dim scriptParams As New Command("Set-MailPublicFolder")
            scriptParams.Parameters.Add("Identity", strIdentity)
            scriptParams.Parameters.Add("GrantSendOnBehalfTo", Trim(strvalue))

            P2.Commands.Add(scriptParams)

            Dim results As Collection(Of PSObject) = P2.Invoke()
            R2.Close()

```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @vlciho, thank you for your feedback.

It's out of scope for us because we here to take feedback and improve docs. But please check you domain, is it called "domain"?
"cannot find object" tell us that the command looks good but it cannot find john.doe in the domain called "domain".

If you need more help with this please try with:
https://techcommunity.microsoft.com/ or https://social.msdn.microsoft.com

**Comment by vlciho** [comment]
If i run in Exchange Management Shell on Exchange server, commands is ok. If i use construct for powershell remoting from vb.net,  then visual studio says error "cannot find object @{add='domain\john.doe'}". I thinking maybe is problem with @ character for call remote powershell. Our domain is sure not "domain", this only for example. I don't want write name of our domain. Thanks.

**Comment by dariomws306** [comment]
Ok, understood. Please try to get help here:
https://techcommunity.microsoft.com/ or https://social.msdn.microsoft.com

**Comment by vlciho** [comment]
OK, thanks.
