### ISSUE TITLE
how to add cloud storage (SharePoint doc libs) to Teams Channel via powershell commandlets?

### ISSUE THREAD

**Issue by rdnllc** [MicrosoftDocs/office-docs-powershell#4090]
Is there a method to add a SharePoint doclib to Teams Channel via powershell? I'm tryng to automate a bulk assignment of SharePoint DocLibs to Teams channels.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @rdnllc, thank you for your feedback.

Until now, there is no way to add tabs to a Team Channel using Powershell. In the next link you can see all the available cmdlets:
https://docs.microsoft.com/microsoftteams/teams-powershell-overview

It's a good idea to vote in user voice if you consider this feature something important to add:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/32832346-powershell-cmdlets-for-creating-tabs

**Comment by yogkumgit** [comment]
@rdnllc  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by rdnllc** [comment]
Hi dariomws306,
I think you meant to say that at this time, there are no powershell commandlets to facilitate adding cloud storage to a channel, or adding tabs to channels or any other modifications of team channels. If I wish to comment and vote on uservoice if this is a direction I would like Microsoft to explore. Thanks for the definitive reply, and I have voted to expand powershell into this area. (until now could imply there was no solution until the current powershell update, contextual analysis of this thread negates this meaning, and I'm going with the meaning expressed in this paragraph)

/Robin

**Comment by dariomws306** [comment]
@rdnllc yes, at this time there is no way to add tabs (including SharePoint Document Libraries) to a Team channel using Powershell.

Thank you for your collaboration here and User Voice.

**Comment by yogkumgit** [comment]
@dariomws306 Thanks.
