### ISSUE TITLE
OnPrem

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/office-docs-powershell#4098]
It appears that this is now an onPrem command in Sfb2019 as well.  Discovered when moving users with VVX phones from Lync to Sfb2019 and the BToE switch from Auto to Manual, which is the default setting apparently in 2019...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9621f63e-b11e-790f-9477-739defcb6b3d
* Version Independent ID: 04ad18b4-b54b-d4ef-7bb9-a5800de4304a
* Content: [Set-CsIPPhonePolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csipphonepolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsIPPhonePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsIPPhonePolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Korbyn72 thanks for that, I could verify in my lab that the cmdlet is present in SfB 2019.
I created a pull request to improve the article.
Thank You!

**Comment by yogkumgit** [comment]
@tomkau Please merge this PR #4130 , thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Korbyn72 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
