### ISSUE TITLE
Missing SouldRemoveFromCdn parameter

### ISSUE THREAD

**Issue by AiHirano** [MicrosoftDocs/office-docs-powershell#4099]
When I executed Remove-SPOOrgAssetsLibrary cmd, I was prompted for "SouldRemoveFromCdn" parameter. There is no description in this documentation of what value to pass.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @AiHirano 
Please be sure to run the latest version of Sharepoint Online Powershell module, as that parameter has been removed from the cmdlet [and documentation](https://github.com/MicrosoftDocs/office-docs-powershell/commit/d7934ee86c9b528152e44335d8c07ca92d8869ee#diff-b2d30f82c647d9f5d8d9beb5fbd445ca).

You have to use [Remove-SPOTenantCdnOrigin](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spotenantcdnorigin?view=sharepoint-ps) for the same functionality of that parameter.

Hope this info helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @AiHirano 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
