### ISSUE TITLE
-Tenant description missing

### ISSUE THREAD

**Issue by VladimirGluten47** [MicrosoftDocs/office-docs-powershell#4100]
Tenant description is currently set to "{{Fill Tenant Description}}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9796a2ad-0711-a878-2d2e-a0c2b4e4c76e
* Version Independent ID: b5b2e5ee-1d71-938e-7e77-9e2bc2eeb2b9
* Content: [Remove-CsVoiceNormalizationRule (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @VladimirGluten47 thanks for noticing it, created a pr to add the description, thank you.

**Comment by yogkumgit** [comment]
@tomkau Please merge this PR #4133, Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @VladimirGluten47 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
