### ISSUE TITLE
Align documentation for New-CsOnlinePSTNGateway and Set-CsOnlinePSTNGateway

### ISSUE THREAD

**Issue by stefanoceruti** [MicrosoftDocs/office-docs-powershell#4101]
[Enter feedback here]
New-CsOnlinePSTNGateway and Set-CsOnlinePSTNGateway has different information for the cmdlet attribute.

**Example**:
-**ForwardPai**
Indicates whether the P-Asserted-Identity (PAI) header will be forwarded along with the call. The PAI header provides a way to verify the identity of the caller. The default value is False ($False). Setting this parameter to $true will render the from header anonymous, in accordance of RFC5379 and RFC3325.

**Vs**

-**ForwardPai**
Indicates whether the P-Asserted-Identity (PAI) header will be forwarded along with the call. The PAI header provides a way to verify the identity of the caller.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41b4a6db-5700-446d-1d41-c4361f80beb5
* Version Independent ID: 07bab8fd-a6c5-50d4-4ca5-11829c23d1f6
* Content: [New-CsOnlinePSTNGateway (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinepstngateway?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsOnlinePSTNGateway.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlinePSTNGateway.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @stefanoceruti thanks for noticing that, created a pull request to align the descriptions. Thank you

**Comment by yogkumgit** [comment]
@tomkau Please merge this PR #4134 thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @stefanoceruti Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
