### ISSUE TITLE
Has this command been depreciated?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/office-docs-powershell#4104]
I've run this command in our hybrid environment as global admin and while it doesn't error out, it doesn't return anything either.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9015c432-658e-461c-dfda-2b78024e0696
* Version Independent ID: b9f92b15-cfd3-3a89-71ea-3946fd42806d
* Content: [Get-HybridMailflow (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/get-hybridmailflow?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/Get-HybridMailflow.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/Get-HybridMailflow.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Canis-Lupis, thank you for your feedback.

I have tested in one environment and I have experienced the same behavior. Could you please let me know what onpremises Exchange version do you have?

@chrisda could you help here? Looks like there are more people with the same issue but I think it worked at some point:
![image](https://user-images.githubusercontent.com/33589238/66066565-27be2e00-e520-11e9-8a3f-004fce65d74e.png)
Also, I think HCW uses this cmdlet.

Thanks!

**Comment by Canis-Lupis** [comment]
It is Exchange 2013.

**Comment by chrisda** [comment]
I've confirmed that this cmdlet and Get-HbridMailflowDatacenterIPs are basically deprecated. They're present for some customers, but aren't really used anymore, and I've updated the topics accordingly.

Thanks for the feedback.

**Comment by dariomws306** [comment]
Awesome Chris! Thank you!
