### ISSUE TITLE
Incorrect link for module in PowerShell Gallery

### ISSUE THREAD

**Issue by maps05** [MicrosoftDocs/office-docs-powershell#4106]
I've noticed that in the second paragraph the link to the module in PowerShell gallery is linking to a specific version from 2018:

https://www.powershellgallery.com/packages/Microsoft.Online.SharePoint.PowerShell/16.0.8029.0

It's a minor thing but may cause a distracted user to download an outdated version. Please update it to: https://www.powershellgallery.com/packages/Microsoft.Online.SharePoint.PowerShell to ensure it's always in the latest.

Thanks and keep the good work.

https://www.powershellgallery.com/packages/Microsoft.Online.SharePoint.PowerShell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b23d72-33ed-a6a1-a442-a5e5cf039f9f
* Version Independent ID: 4247cf37-3667-2007-7251-46ed80f58ef5
* Content: [Getting started with SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @maps05 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
