### ISSUE TITLE
ConditionalAccessPolicy switch setting incorrect

### ISSUE THREAD

**Issue by vettekerry** [MicrosoftDocs/office-docs-powershell#4110]
The -ConditionalAccessPolicy switch options show "LimitedAccess" and the correct value is "AllowLimitedAccess"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428a5954-392c-f7ad-bac4-553adf74e08e
* Version Independent ID: 44fdecf2-1977-3171-9d04-02c0fefb16c9
* Content: [Set-SPOTenant (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @vettekerry thanks for noticing that, I could verify that the [enumeration](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/mt813310(v%3Doffice.15)) is correct.
Created a pull request to correct the article.
Thank you!

**Comment by yogkumgit** [comment]
@trent-green Please merge this PR #4140

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @vettekerry Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
