### ISSUE TITLE
Is this command available yet?

### ISSUE THREAD

**Issue by Peter-Ross-C** [MicrosoftDocs/office-docs-powershell#4112]
Hi,

Is this command related to the new Home sites, as shown here https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/SharePoint-home-sites-a-landing-for-your-organization-on-the/ba-p/621933

When attempting to use the command I get a 403 Forbidden error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12da9c12-7eff-f43f-67ff-d667d12847d4
* Version Independent ID: bf90101d-939a-08b0-79fd-1032f00eccc7
* Content: [Set-PnPHomeSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnphomesite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPHomeSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPHomeSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Peter-Ross-C 
Thanks for your feedback.

As you might know, PnP cmdlets are community-driven, so I need to kindly redirect your inquiry to other resources, 

please start here
 https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps

or here https://github.com/SharePoint/PnP-PowerShell/issues

Hope this information helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Peter-Ross-C 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
