### ISSUE TITLE
missing parameters description

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftDocs/office-docs-powershell#4114]
I can see the following parameters available and not described here:
-FullCrawl
-StopHoldCleanup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51b0f75-659d-b200-31a0-299aecdc6193
* Version Independent ID: 609b307f-2f13-2b9b-1205-b5d4258a45d3
* Content: [Start-ManagedFolderAssistant (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-retention/start-managedfolderassistant?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-retention/Start-ManagedFolderAssistant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-retention/Start-ManagedFolderAssistant.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
OK Fixed. Thanks for the feedback.
