### ISSUE TITLE
Granting global policy to individual users

### ISSUE THREAD

**Issue by VladimirGluten47** [MicrosoftDocs/office-docs-powershell#4121]
It's not clear from this document how to grant the global policy to a user which has been granted a more specific policy, as it's not a user policy. Is this done by Remove-CsClientPolicy on the current policy assigned to the user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8af006e0-97b9-714f-4903-3728ba029382
* Version Independent ID: 1f97afe9-91be-427d-f799-065e037fd225
* Content: [Grant-CsClientPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csclientpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsClientPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsClientPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @VladimirGluten47 
As all cmdlets in SfB that include a Global policy, you un-assign a per user policy by granting a $null policy to it, for example

`Grant-CsClientPolicy -Identity "Ken Myer" -PolicyName $null`

This way, Ken Myer user will get the Global policy.

Will propose adding this example to the article.

Hope this information helps you.

**Comment by get-itips** [comment]
On a second view, that information is already in the article. See

> If you set PolicyName to a null value, then the command will unassign any per-user policy assigned to the user. For example:

> Grant-CsClientPolicy -Identity "Ken Myer" -PolicyName $Null

Hope this info helped you out

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @VladimirGluten47 Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
