### ISSUE TITLE
Command is missing error log

### ISSUE THREAD

**Issue by jonimattila** [MicrosoftDocs/office-docs-powershell#4122]
This command runs successful but after doing checks to swapped sites there was some file view web parts and some document library views were referring to old URL location eg. company-sharepoint.com/sites/newintranet instead of root url company-sharepoint.com. Error log parameter would maybe have had this information so could save some trouble.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb8f8e8-1242-363c-be77-038142b4efb9
* Version Independent ID: 54a60006-3d61-4bb9-a040-60fe77ef9f85
* Content: [Invoke-SPOSiteSwap (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/invoke-spositeswap?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md)
* Service: **sharepoint-powershell**
* GitHub Login: @WayneEwington
* Microsoft Alias: **waynewin**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@jonimattila  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
