### ISSUE TITLE
remove-spouser

### ISSUE THREAD

**Issue by AspenForester** [MicrosoftDocs/office-docs-powershell#4127]
The documentation for Remove-SPOUser is particularly incorrect.  The syntax section shows a single paramter set, while the Description claims that it has more than one and proceeds to explain to the user where to learn to more about parametersets.  I don't think I've ever seen another PowerShell command's help do that (nor do I wish to)

I also disagree with the notion that improving help is a feature to be begged for via uservoice.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @AspenForester 
Thanks for your feedback.
I could verify that actually, the cmdlet Remove-SPOUser has only one parameter set, and is the one that is depicted in the documentation.
I will create a pull request to propose improve the description removing that statement and reference this issue you created, thanks for noticing and reporting.
Thank you

**Comment by yogkumgit** [comment]
@trent-green Please merge this PR #4161 , thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @AspenForester Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
