### ISSUE TITLE
SkypeOnlineConnector is missing "New-CsPresencePolicy" cmdlet

### ISSUE THREAD

**Issue by kosset** [MicrosoftDocs/office-docs-powershell#4128]
I am trying to create a new CsPresencePolicy for Skype For Business Online and the cmdlet New-CsPresencePolicy is missing, even though I can run Get-CsPresencePolicy on the same PowerShell session for an existing policy.

In fact, I get the error I get is the following:
![image](https://user-images.githubusercontent.com/9272849/66302645-f4a1e300-e901-11e9-84c7-01597b9ad101.png)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @kosset 
As the article for New-CsPresencePolicy says

> Applies to:
Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019

It is not supported in SfB Online as you are trying to use it.

Hope this information helps you

**Comment by kosset** [comment]
You 're right, thanks @get-itips :)

_closing the issue_
