### ISSUE TITLE
[LOC] invalid link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/office-docs-powershell#4129]
There is a broken link within an article.

**Repro steps**:
1. Go to https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps
2. Search for the "https://docs.microsoft.com/sharepoint/governance/records-management-in-sharepoint-server|SharePoint"
3. Click on the link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link redirects correctly

**GH article:**
https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md

![image](https://user-images.githubusercontent.com/47977325/66305520-c28f8180-e8ff-11e9-9b7c-fcbe2629c486.png)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello it seems there is a typo that is preventing the rendering of the table and that seems to be the cause, created a pull request to try to fix this. thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @OfficeGlobal Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
