### ISSUE TITLE
Autocomplete has -DirectMembershipOnly

### ISSUE THREAD

**Issue by arowswell** [MicrosoftDocs/office-docs-powershell#4131]
But this documentation doesn't list it an option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f74a1-badd-e304-55d8-1981f86c5440
* Version Independent ID: e51876c4-c39d-a1b6-4624-599eb8f823d8
* Content: [New-DynamicDistributionGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/new-dynamicdistributiongroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/New-DynamicDistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/New-DynamicDistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @arowswell, thank you for your feedback.

Could you please give me more detail about what you think is wrong with this article? Thanks!

**Comment by arowswell** [comment]
If you load the module in PowerShell and type New-DynamicDistributionGroup -Direct then press <tab> to autocomplete, it shows -DirectMembershipOnly as a parameter. There is no mention of this on the docs page though.

**Comment by dariomws306** [comment]
@arowswell thank you! Super clear now!

It looks like it's to avoid nested groups membership, but it doesn't work. I think it's still "under construction", I will add something to avoid confusion.

@chrisda maybe you can add something here, thanks!

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4163 , Thanks

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @arowswell Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
