### ISSUE TITLE
module link goes to 404

### ISSUE THREAD

**Issue by fatherjack** [MicrosoftDocs/office-docs-powershell#4138]
When clicking the link with text 'exchange' right under the command name at the top of this page goes to a 404 page does not exist page. The url is "https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/?view=exchange-ps"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b640892-b0a1-4f20-1e25-fe5f0e97f5b6
* Version Independent ID: 51774b36-90fa-1d9a-5800-1a54d9f70590
* Content: [Get-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @fatherjack, thank you for your feedback.

This is a well know issue and the the responsible team is working on it. I hope it's fixed soon.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @fatherjack 
Hope this informatio is helpful and will appreciate your wait. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dariomws** [comment]
The Exchange module link issue was fixed this week. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
