### ISSUE TITLE
Do NOT use Exchange PowerShell console with Exchange online

### ISSUE THREAD

**Issue by cheesecracker** [MicrosoftDocs/office-docs-powershell#4139]
If you have hybrid Exchange, do NOT run the cmdlet in Exchange PowerShell console.  Instead, run in pure PowerShell console.
This is not clearly written out and the error message is very misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28421932-300b-18b5-4a26-1cfc12f1e60d
* Version Independent ID: b5bd9f7a-f780-f5dc-c7d5-4d3dd60c3cb6
* Content: [Set-UserPhoto (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-userphoto?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-UserPhoto.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-UserPhoto.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
@Hi @cheesecracker, thank you for your feedback.

Could you please let me know how to find this message? I cannot find it in the article.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and digging deep into it.  @cheesecracker We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by cheesecracker** [comment]
@dariomws306 
> @hi @cheesecracker, thank you for your feedback.
> 
> Could you please let me know how to find this message? I cannot find it in the article.

Find what message?
-------------
@yogkumgit 
> @dariomws306 Thank you very much for the contribution and digging deep into it. @cheesecracker We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
> Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

I didn't reply because I didn't see your question.  Or are you talking about dariomws306?

**Comment by dariomws306** [comment]
Hi @cheesecracker, I have been testing and this cmdlet should be running on Exchange Management Shell (on-premises) or Exchange Online Powershell, not pure Powershell console.

**Comment by cheesecracker** [comment]
> Hi @cheesecracker, I have been testing and this cmdlet should be running on Exchange Management Shell (on-premises) or Exchange Online Powershell, not pure Powershell console.

That's NOT what I observed and found.

What did you mean by Exchange Online Powershell?  I'm not sure such thing exists.

If you have hybrid Exchange as I wrote, and if you run the command of the matter (Set-UserPhoto) in Exchange Management Shell (on-prem), it will be received by Exchange on-prem which will leads to error message.  Suppose you want to set the photo for an account called user1.  The error message will state that ".... object user1 does not exist in <some DC>...."   The <some DC> is the name of one of the domain controllers.

**Comment by dariomws306** [comment]
Hi @cheesecracker,

I confirm that the cmdlet exist on Exchange Management Shell (on-premises). Also in Exchange Online:
https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell

When you try to use a cmdlet which doesn't exist you get "The term 'XXXXX-XXXXXXXXXX' is not recognized as the name of a cmdlet, function, script file, or operable program". In this case you are getting different error, you have to double check what you are passing to the Identity parameter.

Anyway, in a hybrid environment you should use Set-UserPhoto in Exchange Online "Powershell":
https://support.microsoft.com/help/3062745/user-photos-aren-t-synced-from-the-on-premises-environment-to-exchange

If you have more issues running this cmdlet I kindly suggest that you open a support ticket. Docs feedback is there to improve documentation and we cannot give you product support.

Thank you for understand!

**Comment by yogkumgit** [comment]
@dariomws306 Thanks for the comments, I proceed and close it.
