### ISSUE TITLE
Information Barrier Policies PowerShell cmdlets

### ISSUE THREAD

**Issue by atguilmette-MSFT** [MicrosoftDocs/office-docs-powershell#4145]
Docs say they are "Security and Compliance Center" powershell, but the some of the cmdlets (Get-InformationBarrierPolicy, New-InformationBarrierPolicy, Test-InformationBarrierPolicy) are actually in the Exchange Online module and not in the Security & Compliance Center module.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by atguilmette-MSFT** [comment]
Oddly, after changing my license on my test user account from E3 to E5, the *InformationBarrier policies are now exported in the SCC powershell.  I have a screencap from last night before I changed the license.

**Comment by dariomws306** [comment]
Hi @atguilmette-MSFT, thank you for this feedback.

And thank you for getting back with the second comment!

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much. @atguilmette-MSFT Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
