### ISSUE TITLE
-WhatIf Broken when used from Pipeline

### ISSUE THREAD

**Issue by EverettCooleyPremier** [MicrosoftDocs/office-docs-powershell#4148]
Get-InboxRule -identity 'ruleidentityhere' | Disable-InboxRule -WhatIf 
Does not "WhatIf"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d2a1fc3-a462-5118-8f81-9f8fa6d0519a
* Version Independent ID: 3a8fd05b-cd90-0b5b-fe04-a26288f77733
* Content: [Disable-InboxRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/disable-inboxrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Disable-InboxRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Disable-InboxRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @EverettCooleyPremier Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
