### ISSUE TITLE
there is no -tenant Attribute anymore

### ISSUE THREAD

**Issue by SanguptaMSFT** [MicrosoftDocs/office-docs-powershell#4151]
with SfB 2019 CU1 HF1 there is no -tenant attribute. 
the attribute used to be present in the SfB 2019 RTM version. so we need to correct and update the doc since many customers are getting confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7affa8c7-0cff-84fc-6e1e-06925a7ee0e9
* Version Independent ID: b813cded-e98d-4665-111c-17906b15f4ef
* Content: [New-CsHostedVoicemailPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cshostedvoicemailpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsHostedVoicemailPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsHostedVoicemailPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @SanguptaMSFT, thank you for your feedback.

This is under investigation and it's related to:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2957

You add valuable information, thanks again!

**Comment by kenwith** [comment]
Oh oops, I cannot assign you @hirenshah1 . You might need to connect your GitHub with the Microsoft organization so you are linked. @SanguptaMSFT must have already done that because he gets the "Microsoft submitter" blue label next to his name. :)

**Comment by kenwith** [comment]
Here is some content in FAQ on how to link accounts: https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/repo_docs/FAQ.md#i-am-a-microsoft-employee-but-new-to-github-what-should-i-do

**Comment by kenwith** [comment]
@SanguptaMSFT - @hirenshah1 team owns this area and is fixing this so that -tenant attribute works as per the documentation. Thank you for bringing this issue up. You can reach out to Hiren for their internal task on this item if you want to track it internally.

**Comment by hirenshah1** [comment]
Update on this. The -tenant attribute is removed intentionally as -tenant attribute was applicable for SFB online. However Cloud voicemail is enabled for SFBO instead of Exchange UM. I will update the documentation to remove this -tenant attribute
