### ISSUE TITLE
Looks like a generated Page, no value

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/office-docs-powershell#4153]
Missing Description, missing parameter description. No statement, if it is also working with Teams Direct Routing. Should be updated 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4d23360-4833-2386-b22d-4fe53448aa99
* Version Independent ID: 70dd7cb7-0eea-3adc-a962-a8f911a3522a
* Content: [Get-CsInboundBlockedNumberPattern (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csinboundblockednumberpattern?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith Please helpus merge this PR #4169

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @FrankCarius Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by FrankCarius** [comment]
Only a few update

I think the „Applies to: Skype for Business Online“   should be “Applies to: Skype for Business Online, Microsoft Teams”

Frank



Frank Carius
Enterprise Architect / Partner

T:    +49 5251 304 600

Net at Work GmbH | Am Hoppenhof 32 A | 33104 Paderborn
Zentrale: +49 5251 304 600 | Fax: +49 5251 304 650
Handelsregister Paderborn: HRB 2663 | Geschäftsführer: Uwe Ulbrich
Näheres zur Informationspflicht nach Artikel 13 DS-GVO und zu unserer Verarbeitung Ihrer personenbezogenen Daten erfahren Sie unter https://www.netatwork.de/wp-content/uploads/Datenschutzinformation-für-Geschäftspartner_Net-at-Work_final.pdf
www.netatwork.de




Einführung von Office 365 geplant?
Vergessen Sie nicht Ihre Nutzer mitzunehmen.
Starten Sie jetzt mit dem Change Management Workshop.
https://www.netatwork.de/change-management-start-up-workshop/


Von: Yogesh Kumar <notifications@github.com>
Gesendet: Mittwoch, 16. Oktober 2019 18:31
An: MicrosoftDocs/office-docs-powershell <office-docs-powershell@noreply.github.com>
Cc: Carius, Frank <Frank.Carius@Netatwork.de>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/office-docs-powershell] Looks like a generated Page, no value (#4153)


@dariomws306<https://github.com/dariomws306> Thank you very much for the contribution and updating the documentation with PR. @FrankCarius<https://github.com/FrankCarius> Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dariomws306** [comment]
Thank you @FrankCarius. All these cmdlets are not listed as available in Teams because they are available in the SfB Powershell module, not available in the Teams module.

**Comment by kenwith** [comment]
I know it is confusing because the Skype for Business Online PowerShell module is actually used to change some settings with Teams. The reason for the confusion is that PowerShell uses the module name strictly and there is back end functionality in SfBO module used in Teams. I have heard there is an effort underway to consolidate SfBO and Teams PowerShell modules into a single module to remove the confusion. I am hoping that will happen soon.

**Comment by yogkumgit** [comment]
@kenwith  and @dariomws306  Thank you very much for sharing this explanation. @FrankCarius 
Hope this comment is helpful now. We proceed here to close it. Please keep contributing with your suggestions to improve the documentation.
