### ISSUE TITLE
Import-PnPTaxonomy can't import to current site collection

### ISSUE THREAD

**Issue by XopherDesign** [MicrosoftDocs/office-docs-powershell#4155]
I can use
Export-PnPTaxonomy to export my site collection termset
Export-PnPTaxonomy -IncludeID -TermSet 6d2dd8d8-5de6-4d25-a3e4-a7d12c8498ac -Path c:\temp\output.txt
But my only option for import is to select the termstorename which will always go to global term store instead of the site collection level. 
Import-PnPTaxonomy -Path c:\temp\output.txt
Seems like if you can export from a site collection you should be able to import to a site collection.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @XopherDesign 
I need to kindly redirect you to this other repo for [PnP issues](https://github.com/SharePoint/PnP-PowerShell/issues)
As you might know, PnP cmdlets are community-driven, as your request looks more suitable for a feature request, you can start [here](https://docs.microsoft.com/en-us/sharepoint/dev/community/community) 
Hope this info helps you

**Comment by yogkumgit** [comment]
@XopherDesign  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue at the given link. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
