### ISSUE TITLE
In Example 2, passing the -FileName parameter results in an error.  There is no -FileName parameter required when scanning an entire folder.

### ISSUE THREAD

**Issue by briangig** [MicrosoftDocs/office-docs-powershell#4175]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bfbfdb8-b340-2d59-92ac-f783dc0bff94
* Version Independent ID: 12deef55-24a9-28d5-7bea-f594db667e9e
* Content: [Export-ActiveSyncLog (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/export-activesynclog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/devices/Export-ActiveSyncLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/Export-ActiveSyncLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @briangig, thank you for your feedback.

-FileName parameter is mandatory. Anyway, the example 2 is wrong and I am fixing it.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @briangig Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
