### ISSUE TITLE
Set-PnPUnifiedGroup returns error 'Exception while invoking endpoint  https://login.microsoftonline.com/71f268c4-7140-43cb-bfe5-4f37301ab0ae/oauth2/token.'

### ISSUE THREAD

**Issue by OpenHabitat** [MicrosoftDocs/office-docs-powershell#4176]
Getting this error:  

Set-PnPUnifiedGroup : Exception while invoking endpoint 
https://login.microsoftonline.com/71f268c4-7140-43cb-bfe5-4f37301ab0ae/oauth2/token.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7c0144-3d70-5812-617f-3ab914aca3eb
* Version Independent ID: f188ada0-7d29-0c95-fa51-c0a62a71a8d0
* Content: [Set-PnPUnifiedGroup (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpunifiedgroup?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPUnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPUnifiedGroup.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @OpenHabitat 
I was about to kindly redirect you to this other repo for [PnP issues](https://github.com/SharePoint/PnP-PowerShell/issues) but noticed you already created an [issue](https://github.com/SharePoint/PnP-PowerShell/issues/2314) there
Please follow up on that other repo.

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and digging and linking the issue.. @OpenHabitat Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
