### ISSUE TITLE
New-SPEnterpriseSearchServiceApplication with -WhatIf still creates Search Service Application

### ISSUE THREAD

**Issue by atop-Ilionx** [MicrosoftDocs/office-docs-powershell#4177]
The -WhatIf function doesn't work; it still creates the Search Service Application

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
@atop-Ilionx this is a product bug and would need a ticket opened with the product group.

**Comment by atop-Ilionx** [comment]
Oke… how can I do that or are you doing that?

**Comment by yogkumgit** [comment]
@atop-Ilionx Thank you very much for posting this issue. Considering the nature of the issue, as advised by @tseward , please open a service ticket in your tenant and follow with them for the resolution. 

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
