### ISSUE TITLE
Get-InboxRule Parameter -IncludeHidden not working

### ISSUE THREAD

**Issue by bartlettdn** [MicrosoftDocs/office-docs-powershell#4178]
Get-InboxRule Parameter -IncludeHidden is not working or does not exist.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@bartlettdn, that parameter is available to me in Exchange 2013, 2016 and 2019, and is identified as such in the parameter's Applicable value in the parameter description.

Are you trying to use this in Exchange Online? If so, then, yes; definitely not available. If you're using it in on-prem Exchange, does it return an error? If so, what is the error?

**Comment by bartlettdn** [comment]
I was trying to do this with Exchange Online, I skipped over that part in the documentation - my apologies. Thank you!
