### ISSUE TITLE
Get-PnPUnifiedGroup returns auth error.

### ISSUE THREAD

**Issue by OpenHabitat** [MicrosoftDocs/office-docs-powershell#4184]
When I run this command I get the following auth error:
Get-PnPUnifiedGroup : Exception while invoking endpoint 
https://login.microsoftonline.com/71f268c4-7140-43cb-bfe5-4f37301ab0ae/oauth2/token.
At line:1 char:1
+ Get-PnPUnifiedGroup
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PnPUnifiedGroup], ApplicationException
    + FullyQualifiedErrorId : System.ApplicationException,SharePointPnP.PowerShell.Commands.Graph.GetUn 
   ifiedGroup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53df4ad8-9006-4d5c-8829-a1c481dac939
* Version Independent ID: 15dfc257-8c5f-63d6-ffe7-f7a7163c25bf
* Content: [Remove-PnPNavigationNode (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpnavigationnode?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPNavigationNode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPNavigationNode.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @OpenHabitat

I need to kindly redirect you to this [other repo](https://github.com/SharePoint/PnP-PowerShell/issues) for PnP issues, please first, search if this issue is already created.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @OpenHabitat 
These repos are all open source and the community would welcome to contribute.  Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
