### ISSUE TITLE
-publishedOnly appears to be a flag

### ISSUE THREAD

**Issue by jjinatlanta** [MicrosoftDocs/office-docs-powershell#4185]
-publishedOnly appears to be a flag - it doesn't take a value of $false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90616400-a52d-46ca-fc46-d33208198aae
* Version Independent ID: 434b2697-667f-cc60-f858-d406fbb6eced
* Content: [Get-PnPWorkflowDefinition (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpworkflowdefinition?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWorkflowDefinition.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWorkflowDefinition.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @jjinatlanta 
You can see [here](https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Workflows/GetWorkflowDefinition.cs) that -PublishedOnly is in fact, a SwitchParameter as the documentation says

Also, SwitchParameters in Powershell, if used without specifying $true or $false take the $true value.

For next issues or inquiries about PnP Powershell I need to kindly redirect you [here](https://github.com/SharePoint/PnP-PowerShell/issues) and [here](https://docs.microsoft.com/en-us/sharepoint/dev/community/community).

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @jjinatlanta 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
