### ISSUE TITLE
Connect-MicrosoftTeams : Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its  dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by bskinner33** [MicrosoftDocs/office-docs-powershell#4186]
Trying to add add a team member. I am getting the error below. 

Connect-MicrosoftTeams : Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its 
dependencies. The system cannot find the file specified.

**Comment by tseward** [comment]
Do you have the .NET Framework 4.0 or higher installed on your system?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by bskinner33** [comment]
I found another thread that suggested installing Visual Studio would fix the issue. I installed VS and it did indeed fixed my issue.

I suspect it was because VS updated my .net version.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @bskinner33 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by rlodev67** [comment]
Hey
I have the same issue and I have the .NET Framework installed.
any idea ?

I can't install VS on it.

**Comment by tseward** [comment]
@rlodev67 which version of the Framework(s) do you have installed?

**Comment by anilkumar15** [comment]
MSBuild.exe -version
Microsoft (R) Build Engine version 4.7.2053.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

4.7.2053.0

Connect-MicrosoftTeams : Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Connect-MicrosoftTeams -Credential $credentials

**Comment by rlodev67** [comment]
@tseward , My .net version is 4.7.02053
I try to connect Microsoft Teams with TenantId, CertificateThumbprint and ApplicationId parameters

**Comment by moegitree** [comment]
Got the same problem after I updated my MicrosoftTeams module to version 1.0.3. 
I tried reinstall .net framework 4.8 and fixed it.
Hope this can help.

**Comment by rlodev67** [comment]
Same for me, after installing .net 4.8, I can connect, thanks for the fix @moegitree

**Comment by raypnut** [comment]
thanks for the fix @moegitree after installing .net 4.8, I was able to connect

**Comment by TheITguy666** [comment]
Hi all,
the teams psmodule need .net framework 4.7.2
4.7.02053 is actually just 4.7
https://github.com/MicrosoftDocs/office-docs-powershell/issues/7379

**Comment by jesc516** [comment]
Needed to upgrade to .net 4.8

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.3866
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3866
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1





ModuleType Version    Name
---------- -------    ----
Manifest   1.0.0.0    ActiveDirectory
Manifest   3.1.0.0    Microsoft.PowerShell.Management
Manifest   3.1.0.0    Microsoft.PowerShell.Utility
Binary     2.0.0      microsoftteams
Script     1.2        PSReadline
```

**Comment by yogkumgit** [comment]
@tseward

**Comment by TheITguy666** [comment]
The teams psmodule 3.0 needs at least .net framework 4.7.2 or .net core 2.1
