### ISSUE TITLE
Limited to 50,000 results?

### ISSUE THREAD

**Issue by arowswell** [MicrosoftDocs/office-docs-powershell#4187]
I just ran this and the CSV report I got had 50,001 lines, so minus the header it has 50,000 results. It would be extremely coincidental for this to not be a limitation. Please advise. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a22164-2df5-5dc2-9292-df60df018a53
* Version Independent ID: 1d96478c-230b-889e-68ed-9a8ab9484be5
* Content: [Start-HistoricalSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/start-historicalsearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Start-HistoricalSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Start-HistoricalSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @arowswell, thank you for your feedback.

Could you kindly provide me more detail about what you suggest? Thanks!

**Comment by arowswell** [comment]
Hi Dario. The page doesn't mention any limit of 50,000 results. Yet when I ran the command and got the CSV it had exactly 50,000 results. To me that is too coincidental to just be chance. Is there a 50,000 result limit?

**Comment by dariomws306** [comment]
Thank you @arowswell. Pretty clear, I understand now.

I don't have this information, I will try to get it.

**Comment by yogkumgit** [comment]
@chrisda your input please.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @arowswell Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
