### ISSUE TITLE
Unable to set StorageQuota

### ISSUE THREAD

**Issue by stephane0smith** [MicrosoftDocs/office-docs-powershell#4191]
The Latest version of Microsoft.Online.SharePoint.PowerShell version 16.0.19404.12000 will not modify the size of the storageQuota no error is displayed and no changes are applied. We've used version 16.0.7521.0 and all worked fined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1c6b2b-5af6-acce-b7e8-bf784bb0973e
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by tseward** [comment]
Do you have Automatic or Manual storage allocation selected on your tenant?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by stephane0smith** [comment]
We are set to automatic behavior.

**Comment by tseward** [comment]
@stephane0smith I would assume that is going to override any manual changes you attempt to add.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @stephane0smith 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by stephane0smith** [comment]
I am not willing to override the automatic behavior we had it working in an early verison 7019. with the automatic behavior set to true. If I am not mistaking setting the value to manual is a tenant default value that we don't want to be working with. Why is it that NO Errors is shown for a command that is not applying the correction to the site storageQuota. This issue has been wrongly closed. has no resolution seems to be proven to me.

**Comment by VesaJuvonen** [comment]
There was an unfortunate regression with the previous versions, but that has been now addressed with a new version 19418 - https://www.powershellgallery.com/packages/Microsoft.Online.SharePoint.PowerShell/16.0.19418.12000

We do apologize the inconvenience caused by this. Issue is now luckily resolved.
