### ISSUE TITLE
All currently configured Shared Line Appearances

### ISSUE THREAD

**Issue by JeffreyBrew** [MicrosoftDocs/office-docs-powershell#4193]
Get-CsSlaConfiguration assumes you already know the identities of the currently configured SLAs (Shared Line Appearances).  How can I get a listing of all currently configured SLAs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054fccc9-0d1e-6a10-a033-76337f8c4772
* Version Independent ID: e52a75e9-c638-6053-db7b-34f9f327f82e
* Content: [Get-CsSlaConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csslaconfiguration?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Get-CsSlaConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsSlaConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by kenwith** [comment]
@hirenshah1 - FYI

**Comment by joaolloureiro** [comment]
This is more a design change request than documentation issue

**Comment by dariomws306** [comment]
Thank you @joaolloureiro. So we understand there is no way to do it now.

**Comment by JeffreyBrew** [comment]
> 
> 
> This is more a design change request than documentation issue

Why did the original design not include this standard behavior/functionality that is present in nearly all other Get cmdlets?

Get-CsSlaConfiguration is the only Get cmdlet I know of that doesn't return a complete list of queried items.  For example, Get-CsUser will return a list of all users on a Skype for Business platform.  Once I find the user I am looking for then I can add the -Identity parameter to query that specific user then pipe that user to another cmdlet (i.e.: Move-Csuser or Set-CsUser).  Get-CsSlaConfiguration should have been designed to behave the same similarly.

Every administrator new to a particular Skype for Business environment will need this functionality.

Please update the Get-CsSlaConfiguration to include the standard behavior/functionality that is present in nearly all other Get cmdlets.

**Comment by hirenshah1** [comment]
This is a design change request and not documentation change. We take the requested functionality as feedback and will try to address it in next releases.

**Comment by JeffreyBrew** [comment]
@hirenshah1 Can I get an ETA as to when the functionality I requested will be available?  I am preparing to migrate users from one Skype for Business Server 2015 platform to another.  I need to get a CsSlaConfiguration dump of all existing users on the current platform to recreate on the new platform.

**Comment by hirenshah1** [comment]
Work items get prioritized based on business need at any given time, so I cannot say the exact date when the functionality will be available.

**Comment by JeffreyBrew** [comment]
@hirenshah1 Is it me or am I getting the impression that you are not sensing the urgency of this?  Please escalate this to someone who raise the priority on this.

**Comment by kenwith** [comment]
I searched through User Voice and did not see this request listed so I created it here: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/39620977--get-csslaconfiguration and I voted for it. Anyone that comes across this issue please vote for it as well if this is something you would like to see @hirenshah1 team prioritize.
