### ISSUE TITLE
-DeleteContent documented but missing 

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/office-docs-powershell#4194]
I'm now getting an error that -DeleteContent doesn't exist, although it's still documented on this page. Deprecated doesn't mean "Gone" … the command should still work, OR the page should be modified to indicate what does still work.

'''
A parameter cannot be found that matches parameter name 'DeleteContent'.
    + CategoryInfo          : InvalidArgument: (:) [Search-Mailbox], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Search-Mailbox
    + PSComputerName        : outlook.office365.com
'''

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c6c666-7221-7984-82a5-d731fee0ac3d
* Version Independent ID: 6970ac1a-0aaa-c625-24db-e3db2296b6f8
* Content: [Search-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/search-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by jgwinner** [comment]
Hey, this was my mistake. I didn't have the "Import/Export" role. That's easy to overlook, as that role doesn't show up in the O365 control panel; you have to add it manually.

What threw me is that PowerShell said the command didn't exist, "A parameter cannot be found that matches parameter name 'DeleteContent'." not "You don't have the right permissions.

Maybe a line under the DeleteContent parmater to indicate that somehow.

**Comment by chrisda** [comment]
Maybe. But, Exchange RBAC has acted in this manner since it's inception: if you don't have rights to the cmdlet (or even a parameter on a cmdlet), it's as if the cmdlet/parameter doesn't even exist for you. It's very likely a security consideration.

**Comment by jgwinner** [comment]
Right, I get it, security through obscurity. I'm just saying that it's not obvious when you read the docs that this is an unintended consequence. I wouldn't expect every single parameter to have this warning, but it should be somewhere that this is expected behavior. Maybe it is, and I missed it.

Documentation shouldn't eliminate something because "it's always worked that way". My point is it takes extra effort for a hidden permission on O365 to get this to work, which is not obvious. 

It's embarrassing for me, sure; then again, my companies IT service company didn't know how to do it and they have 10 guys. I'd imagine others are in this boat.

Just a suggestion though, I can see letting people swing.

**Comment by chrisda** [comment]
And, to be fair, this is a rather rare circumstance where a specific *parameter* on a cmdlet is unavailable to anyone/everyone (even admins) by default. Therefore, the only logical place to call that out is in the parameter description itself. Normally, if the whole cmdlet is unavailable by default, we stick a big not at the top of the top explaining this.

I updated the parameter description to move the call-out to the top of the parameter description.

**Comment by jgwinner** [comment]
Wow, thank you! 

Agreed on the rare circumstance.  That's what threw me. I just assumed if the cmdlet was avaiable, I'd done everything right. I was moving fast as I'd been asked to do this and our IT service company didn't really do it. 

I really hope they don't make this command go away, it's so much easier to run than the newer method. Then again ... I guess I could write a PowerShell commandlet to automate the newer method. Honestly, most SMB's will never need the full blown discovery.

The normal use case is a Phishing email that has to be removed ASAP.

Just got one today from Office 365 that my account was suspended. Sorry to ramble, but it amuses me that O365 would fail the sender check and still pass on the email, and not even in 'Junk'. 

        == John ==

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and updating the documentation with PR. @jgwinner Hope this explanation and update are helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future if you see any documentation update that can be helpful for the community. For new features or other issues you can approach either to Usrvoice or Support as this tenant is specifically for documentation improvement.
