### ISSUE TITLE
Get-pnpauditing don’t return “all” in auditflag

### ISSUE THREAD

**Issue by meramkumartrn** [MicrosoftDocs/office-docs-powershell#4195]
Currently the auditflag don’t return “all” it return 71xx. Is that a expected behavior. What s the other auditflag available

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @meramkumartrn 
I need to kindly redirect you to [this other repo](https://github.com/SharePoint/PnP-PowerShell/issues) for PnP issues
As you might know, PnP cmdlets are community-driven, someone from the community will handle your inquiry there.
Hope this info helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @meramkumartrn  Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
