### ISSUE TITLE
Seting Status to Offline sets Database Status in CA to Error

### ISSUE THREAD

**Issue by bjkline** [MicrosoftDocs/office-docs-powershell#4197]
When using Powershell to set the Content Database status and using the Offline value, CA shows the database status as ERROR.

Set the Status to Disabled to get Central Administration to show status of Stopped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8939057b-2dcd-a5fd-1062-6cae12959bd2
* Version Independent ID: eed7bfe2-6112-76b7-9fa6-513db28cfbff
* Content: [Set-SPContentDatabase (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spcontentdatabase?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPContentDatabase.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPContentDatabase.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @bjkline 
I could repro in my lab. Will propose improving the article thru a pr

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please merge this PR #4227

**Comment by MikePlumleyMSFT** [comment]
@yogkumgit PowerShell PRs are handled through a different process. Check with @kenwith

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @bjkline Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
