### ISSUE TITLE
Path parameter in examples

### ISSUE THREAD

**Issue by tom-daly** [MicrosoftDocs/office-docs-powershell#4198]
looks like path parameter doesn't exist but is in the examples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc64f10-0128-4c65-b47a-0e4a79e0d3fb
* Version Independent ID: 64659208-bb51-d718-ba1a-f348fb781be4
* Content: [Uninstall-SPFeature (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/uninstall-spfeature?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Uninstall-SPFeature.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Uninstall-SPFeature.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tom-daly thanks for noticing this, created a pr to correct the article.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @tom-daly Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
