### ISSUE TITLE
Wrong Results

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/office-docs-powershell#4202]
Please review/fix the description: The example of the console output is not formatted as console output. And it looks outdated:  The Property "Numbers" is no longer existing. But you get some other additional Result. here a sample

PSComputerName        : admin2a.online.lync.com
PSShowComputerName    : False
Id                    : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
AnnouncementsDisabled : False
NameRecordingDisabled : False
ServiceNumberCount    : 3
SubscriberNumberCount : 21
DefaultPoolFqdn       :
DefaultBridge         : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Bridges               : {Id = [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx], Name = [Conference Bridge], DefaultServiceNumber
                        = [], IsDefaultBridge = [True], IsShared = [False], Region = [NOAM]}
Domains               : {}
Pools                 : {sippoolblu2a05.infra.lync.com}
TnmAccountId          : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

You could also add a link to Get-CsOnlineTelephoneNumber to retrieve the list of phone numbers in the tenant.

And the commandlet also applies to "Microsoft Teams" and not only SfBOnline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 943ec445-d796-f169-7b20-521b1009869b
* Version Independent ID: f817f9ea-1d3c-a900-1fe4-63450f43a40e
* Content: [Get-CsOnlineDirectoryTenant (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Get-CsOnlineDirectoryTenant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @FrankCarius Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
