### ISSUE TITLE
Incomplete Document

### ISSUE THREAD

**Issue by Chris8au** [MicrosoftDocs/office-docs-powershell#4203]
Hi - It appears this document was not completed as it's still templated with generic wording.  

I was hoping to find the cmdlet to remove a custom Caller ID Policy from a user and set the user back to the Global Caller ID Policy, in Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b449b4-d67e-2503-90e1-fd451c741458
* Version Independent ID: 67e38702-5ad0-3743-07a2-2e91bcaafde7
* Content: [Remove-CsCallingLineIdentity (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/remove-cscallinglineidentity?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Remove-CsCallingLineIdentity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Remove-CsCallingLineIdentity.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @Chris8au Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
