### ISSUE TITLE
Example parameter for Stop-SPAssignment is incorrect

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/office-docs-powershell#4204]
The example gives: Stop-SPAssignment -Identity $gc
But I believe it should be: Stop-SPAssignment -SemiGlobal $gc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60f73f5c-56f4-0a33-5e8a-5bcdabd495f8
* Version Independent ID: 93e42ae8-9335-14ff-8235-b59b0788a9ec
* Content: [Start-SPAssignment (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/start-spassignment?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Start-SPAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Start-SPAssignment.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @repton-infinity thanks for noticing and reporting, created a pr to propose improving the article.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @repton-infinity Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
