### ISSUE TITLE
To be or not to be useful? :)

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#4205]
Hi,
Will you give us a policy based control for the dial-in service for users, or is it the following CMDLets:
Disable-CsOnlineDialInConferencingUser
Enable-CsOnlineDialInConferencingUser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f98e0612-3883-ed72-675f-152a0be06f8d
* Version Independent ID: b5a2130a-0443-ed77-e854-5c4039ebe93f
* Content: [Get-CsOnlineDialinConferencingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialinConferencingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDialinConferencingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @Petri-X 
Yes you can control the status of DialIn Conferencing for a user in Skype For Business Online thru those cmdlets you mention, are they working for you as expected? Is there any documentation you think needs to be fixed?
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @Petri-X We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
