### ISSUE TITLE
Shared Calendars?

### ISSUE THREAD

**Issue by ssimm** [MicrosoftDocs/office-docs-powershell#4210]
I would like my app to use this functionality to limit access to one user's calendars, but including their shared calendars.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1e6041b-99ca-612b-24d6-053fca4ac717
* Version Independent ID: c18596aa-b54c-1b19-6064-952ae2468d41
* Content: [New-ApplicationAccessPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/new-applicationaccesspolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/organization/New-ApplicationAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/New-ApplicationAccessPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @ssimm, thank you for your feedback.

Looks like you are requesting a new feature. Please kindly go to user voice to do this kind of request:
https://office365.uservoice.com/

Thank you!

**Comment by yogkumgit** [comment]
@ssimm  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by ssimm** [comment]
OK, I did.  The title of the request is:
"Daemon Apps should be able to have the same rights as a given user"
Hope it gets to the right person!

**Comment by yogkumgit** [comment]
@ssimm  Thank you very much for your kind feedback and as advised logging this issue in User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback. Appreciate and encourage you to do the same in future also.
