### ISSUE TITLE
SP2019 warns that VariantType parameter is obsolete

### ISSUE THREAD

**Issue by danglund** [MicrosoftDocs/office-docs-powershell#4211]
WARNING: Parameter 'VariantType' is obsolete.
WARNING: Obsolete parameter ignored: '-VariantType'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d003da9-d01d-f3cb-04d6-c1f353815704
* Version Independent ID: 8875040e-ee02-45ce-abd4-392df0f8da38
* Content: [New-SPEnterpriseSearchMetadataCrawledProperty (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spenterprisesearchmetadatacrawledproperty?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchMetadataCrawledProperty.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchMetadataCrawledProperty.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
While it is marked as `Obsolete`, it is also marked as `Required` meaning the cmdlet documentation, wouldn't change as you must still pass the parameter. Unusual to have something marked obsolete and required, though....

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @danglund Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
