### ISSUE TITLE
WhatifPreference problem with Add/Remove UnifiedGroupLinks cmdLets

### ISSUE THREAD

**Issue by Craig323** [MicrosoftDocs/office-docs-powershell#4215]
# What happens
Neither Add-UnifiedGroupLinks or Remove-UnifiedGroupLinks observe the $WhatIfPreference when it is set to $True. When $WhatIfPreference is $True, membership updates are made, there is not any whatif text written to the console.
When you specify "-Whatif:$True" on the actual cmdLet invocation, the whatif text is echoed and membership changes do not occur.

# What should happen
The commands should observe the $WhatIfPrefence in the same way they observe -Whatif.
When $WhatifPreference is true, membership changes should not be made, and whatif text should be shown.

# Version
Client running Windows 10 build 17763
Get-Module shows
Microsoft.Exchange.Management.ExoPowershellModule.dll
Version: 16.0.0.0

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @Craig323 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
