### ISSUE TITLE
Clicking on the link for the command 'Set-DLPComplianceRuleV2' redirects to the page for 'Set-DLPComplianceRule'

### ISSUE THREAD

**Issue by student-forever** [MicrosoftDocs/office-docs-powershell#4218]
Reporting two issues :
1. Clicking on the link for the command 'Set-DLPComplianceRuleV2' redirects to the page for 'Set-DLPComplianceRule'.

2. This page is missing parameters like 'ExceptIfSentTo' for the command Set-Dlp​Compliance​Rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7d3411c-d81f-667b-84d1-6148291f4923
* Version Independent ID: 5da6c19a-ecf7-7cc1-c120-119b12735303
* Content: [Set-DlpComplianceRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/set-dlpcompliancerule?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Set-DlpComplianceRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Set-DlpComplianceRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @student-forever Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
