### ISSUE TITLE
No Documentation on the size (length) that a parameter can be

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/office-docs-powershell#4219]
Hi
The documentation does not detail the length that a parameter (eg ServerRelativePath) can be eg /sites/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz.aspx

Regards

Nigel
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24abe9ef-b73c-515a-d41a-8f88b0c43880
* Version Independent ID: 86b3d2ff-be86-42e6-6bd1-6735525f180e
* Content: [Rename-PnPFile (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/rename-pnpfile?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Rename-PnPFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Rename-PnPFile.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
@NPrice99 it would be the maximum possible based on the overall length limit for the location, up to 400 characters for the full unencoded URL. This would vary from tenant to tenant so an absolute number cannot be provided.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @NPrice99 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
