### ISSUE TITLE
How to use AadAccessToken

### ISSUE THREAD

**Issue by mumukichi** [MicrosoftDocs/office-docs-powershell#4238]
I can't speak English, so I use Google Translate.
It may be unnatural English, but please forgive me.

I don't know how to use aadAccessToken and MsAccessToken properly.

MicrosoftTeams (v1.02) module is used in a script created using Powershell core (v6.1).
(I use Windows 10 Enterprise 18362)

When I used the `Connect-MicrosoftTeams` command, I could use the` New-Teams` command successfully if I authenticated manually.

However, if I use the Access-Token obtained using client_credentials and use the `Connect-MicrosoftTeams` command as shown below, an error will occur in the` New-Teams` command.

Perhaps I only think that I am using the wrong way, but can you tell me how to use it correctly?

> Ms Graph's Directory / User / Group ReadWrite permission is given to applications registered in Azure.

```Powershell
Connect-MicrosoftTeams `
   -AadAccessToken 'xxxxxxxxxxxxxxxxxxxxxxxxx' `
   -MsAccessToken 'xxxxxxxxxxxxxxxxxxxxxxxxx' `
   -AccountId 'Global Administrator Role User'
```

error contents:
```
New-Team: Error occurred while executing
Code: Request_ResourceNotFound
Message: Resource '{tenant-id}' does not exist or one of its queried reference-property objects are not present.
InnerError:
  RequestId: 0e3c076b-4fdd-4d8c-80c1-a0358cdd9d19
  DateTimeStamp: 2019-10-24T04: 03: 13
HttpStatusCode: Request_ResourceNotFound
At line: 1 char: 1
+ New-Team -DisplayName 'test'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo: NotSpecified: (:) [New-Team], ApiException
+ FullyQualifiedErrorId: Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException, Microsoft.TeamsCmdlets.PowerShell.Custom.NewTeam
```

Is this because I use a trial license?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @mumukichi 
I could reproduce what happened to you.

The [Graph API Permissions documentation for Teams](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=http) specifies that to create a Team the required permissions are:

> Delegated (work or school account) | Group.ReadWrite.All

> Application | Group.ReadWrite.All

Said that, and according to that article, the Group must be already be created to call this method

> In order to create a team, the group must have a least one owner.

so, you can use

`new-team -GroupId "8dc9e01e-0e55-45a1-84b4-0a06dd4391a"`

and it will work

This is probably current a limitation of the cmdlet, so I kindly suggest you to visit [Microsoft Teams UserVoice](https://microsoftteams.uservoice.com/) to propose adding this feature to call the cmdlet using DisplayName and connecting thru a token.

Hope this info helps you

**Comment by yogkumgit** [comment]
@mumukichi  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.

**Comment by mumukichi** [comment]
Hello @get-itips, @yogkumgit.
I'm sorry. I completely forgot to comment here after it was resolved.

I contacted Microsoft and resolved it so I'll share the solution.

I only specified the owner explicitly with the Owner parameter when using the command.

ex)
`new-team -GroupId "8dc9e01e-0e55-45a1-84b4-0a06dd4391a" -Owner exampleOwner@ex.contoso.com`

**Comment by get-itips** [comment]
@mumukichi Thanks for getting back and share your feedback to the community.
