### ISSUE TITLE
Update SharePoint Online Management Shell

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/office-docs-powershell#4240]
Is there any plan to implement a way to update an installed SharePoint Online Management Shell to a newer version without having to uninstall it and install the more recent one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e45fe794-97e2-c5c0-ebed-a6f46ae39624
* Version Independent ID: 3e502565-ef4a-989c-d020-ca5a55011f3e
* Content: [What is the SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/introduction-sharepoint-online-management-shell?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/introduction-sharepoint-online-management-shell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/introduction-sharepoint-online-management-shell.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
Yes, use the PowerShell Gallery instead.

https://www.powershellgallery.com/packages/Microsoft.Online.SharePoint.PowerShell

`Install-Module -Name Microsoft.Online.SharePoint.PowerShell`

Make sure to uninstall the MSI prior to installing the above version.

**Comment by LuigiBruno** [comment]
> Yes, use the PowerShell Gallery instead.
> https://www.powershellgallery.com/packages/Microsoft.Online.SharePoint.PowerShell
> Install-Module -Name Microsoft.Online.SharePoint.PowerShell
> Make sure to uninstall the MSI prior to installing the above version.
> https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps.

Thank you, @tseward.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @LuigiBruno 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
