### ISSUE TITLE
Example correction

### ISSUE THREAD

**Issue by Toanan** [MicrosoftDocs/office-docs-powershell#4242]
Hello,
The example 5 : "Set-PnPSite -SiteLogoPath c:\images\mylogo.png" should be Set-PnPSite -LogoFilePath c:\images\mylogo.png
Thanks for this documentation, it helps a lot !
Regards, Antoine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2961cab8-c2d4-e90b-6d78-666a4dc16823
* Version Independent ID: d9e27a2c-8408-95ba-6d88-46e63fe878a1
* Content: [Set-PnPSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Toanan ! thanks for your feedback!
I need to kindly redirect you to this specific [repo](https://github.com/SharePoint/PnP-PowerShell) where you can either open an issue there or propose a PR directly into the [source code of the cmdlet](https://github.com/SharePoint/PnP-PowerShell/blob/dev/Commands/Site/SetSite.cs) which has the documentation that is  reflected later in the article.

Thank You

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for sharing this explanation. @Toanan   Hope this comment is helpful for you. These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to follow the suggested links.
