### ISSUE TITLE
Breaks MS Teams "files" tab

### ISSUE THREAD

**Issue by grantburdon** [MicrosoftDocs/office-docs-powershell#4243]
After renaming a SharePoint site linked to a team in MS Teams, the "files" tab in channels other than "General" do not work.  I can see that the location the "files" tab is looking at is the old location - it hasn't been redirected.  There appears to be no way to update the destination location of this tab either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1b44e3-4af5-1458-d931-72a0f698732b
* Version Independent ID: 1751767f-1d8a-7750-35b9-725b5a3ad705
* Content: [Start-SPOSiteRename (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/start-spositerename?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteRename.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteRename.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @grantburdon 
Hope this comment is helpful for you. 

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
