### ISSUE TITLE
Examples??

### ISSUE THREAD

**Issue by OpenHabitat** [MicrosoftDocs/office-docs-powershell#4249]
Need detailed examples please like other commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb5dff48-59a0-2e9c-695a-f412f753e22e
* Version Independent ID: 50eba678-7255-369a-23ca-51df4a26af89
* Content: [Set-PnPWeb (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpweb?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPWeb.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPWeb.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @OpenHabitat   thanks for your feedback
I need to kindly redirect you to this [specific repo](https://github.com/SharePoint/PnP-PowerShell) where you can open an issue there, as you might know, PnP cmdlets are community-driven, so the community maintainers will pick your request there.

Thank You

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for sharing this explanation. @OpenHabitat  Hope this comment is helpful for you. These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to follow the suggested links.
