### ISSUE TITLE
DisplayName

### ISSUE THREAD

**Issue by Embury1** [MicrosoftDocs/office-docs-powershell#4252]
The description on the parameter -DisplayName in [https://docs.microsoft.com/en-us/powershell/module/teams/new-teamchannel?view=teams-ps](https://docs.microsoft.com/en-us/powershell/module/teams/new-teamchannel?view=teams-ps) is showing the invalid characters | ' " as a bullet-point. I suspect what you meant was to list the dash as an invalid character but accidentally had it interpreted by your markdown engine as a list item.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@kenwith Please merge this PR #4287

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @Embury1 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
