### ISSUE TITLE
Forwarding unanswered calls to phone number does not work

### ISSUE THREAD

**Issue by NislAr98** [MicrosoftDocs/office-docs-powershell#4254]
If you configure the forwarding with  "-UnansweredToOther &lt;telephoneNumer&gt;" and "-UnansweredWaitTime 15" these settings don't have any impact. If you open the forwarding options in the Skype client and simply click ok without any changes, it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abffe3a5-060b-4e67-ce60-4ace8689053b
* Version Independent ID: 38e763e5-1ed2-a9e5-8eca-32daf8dd3050
* Content: [Set-CsUserCallForwardingSettings (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csusercallforwardingsettings?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsUserCallForwardingSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsUserCallForwardingSettings.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @hirenshah1 Can you please confirm if those params are currently under development and not in production use? or if the PG is aware of the current behavior ? Thank you

**Comment by NislAr98** [comment]
I have similar problems with the Set-CsUserTeamMembers cmdlet when executing it for users who have never had team members before.
If I enable simultaneous call for team members after that, the user is not available anymore and all calls are forwarded until I open the team members dialogue in the sfb client and click ok without making any changes.

**Comment by aov-arnold** [comment]
Any ideas? @get-itips @hirenshah1 @yogkumgit

**Comment by aov-arnold** [comment]
Any new developments? We still have the problems. @get-itips @hirenshah1 @yogkumgit

**Comment by hirenshah1** [comment]
we are still investigating this. Apologies for the delay, please be patient

**Comment by aov-arnold** [comment]
How long will it take?

When I do this, it is visible in the GUI and with Get-CsUserCallForwardingSettings but is has no effect:
Set-CsUserCallForwardingSettings <sip-adress of user> -UnansweredToOther "phone number" -UnansweredWaitTime 20 -Force -DisableForwarding

Same with the Set-CsUserTeamMembers Cmdlet.

We need this setting before deploying Skype for Business Server 2019.

**Comment by aov-arnold** [comment]
@hirenshah1 news?

**Comment by kenwith** [comment]
@NislAr98 thank you for the feedback here. I confirmed with @hirenshah1 that the documentation here is correct and they have updated the code to address the issue. The update will be released in CU. The documentation here is correct so I am closing this item without documentation updates. Thank you again for your engagement.

**Comment by genicus** [comment]
I would like to reopen this issue. We have installed the March 2020 CU yesterday and the problem still occurs.

**Comment by bament-hun** [comment]
we are planning to include this into CU4, which will be released around summer 2020

**Comment by ChrisMKV** [comment]
Has the fix been included in the recently released CU4?

**Comment by aov-arnold** [comment]
I will install the update and test it in a few days!
Hopefully it‘s resolved...

**Comment by genicus** [comment]
For us it is still not working... When will this be finally fixed?

**Comment by get-itips** [comment]
@hirenshah1 can you please kindly update us on this? Many thanks

**Comment by aov-arnold** [comment]
After installing "Skype for Business Server 2019 Cumulative Update 4" it seems to work for us.
But I will test it for some more users...

**Comment by hirenshah1** [comment]
Yes our engineer also tried this again and the scenario is found resolved in our testing.
