### ISSUE TITLE
Set-PnPList to Hidden, hides in SharePoint UI, but is visible in OneDrive UI

### ISSUE THREAD

**Issue by oliviadudley** [MicrosoftDocs/office-docs-powershell#4256]
Set-PnPList -Identity LibraryName -Hidden $true 
#Users can still access from OneDrive. Is this the intention? Is there another option to hide from all web interfaces (including Teams)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbab5a2d-0c37-bb2c-f2d9-989bc2a59d05
* Version Independent ID: 2f512ab6-be40-1fb2-9f8a-d1bc692537ce
* Content: [Set-PnPList (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplist?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPList.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
@oliviadudley what are you attempting to do? Setting that property only hides the list from the web UI (and presumably SharePoint app UI, haven't tested).

**Comment by oliviadudley** [comment]
Hi @tseward,
When I hide a document library, others can see it listed in the web version of OneDrive in the "Shared Libraries" section. I'm just wondering if this is by design. If someone can get around my settings by going to OneDrive, it is not truly hidden.

My questions are, should I expect this behavior & is there a know workaround for this issue?

**Comment by tseward** [comment]
Thanks for clarifying. The implementation of the hidden setting only occurs at the SPWeb level and not any context outside of that area. So if a user has it referenced somehow in OneDrive, then it will show up there. No workaround for that use case.

**Comment by oliviadudley** [comment]
Oh no! Does this mean that as long as someone has access to the SharePoint site, they have access to all libraries, no matter how settings are configured? Is there some way to hide the library from the "Shared Libraries" section of OneDrive? I'm beginning to have security concerns.

**Comment by tseward** [comment]
As long as they have ACLs to the object (library), yes they can access it. This isn't a security issue unless you've ACL'ed it, removing their access, and they can still access the library.

**Comment by oliviadudley** [comment]
I see. The issue is they will need read/write access as the doc library is being used in a PowerApp, but those documents should only be edited and viewed there. In this case the issue is not just with users viewing the files in OneDrive, but also Teams, Flow, or File Explorer. Is there a way to allow editing from PowerApps, but hide the data source (SharePoint Library)? (Let me know if this question is better posed elsewhere.)

**Comment by tseward** [comment]
I would post this to SharePoint StackExchange, TechNet/MSDN Forums, Tech Community, or PowerApps/Flow forums.

**Comment by tseward** [comment]
@oliviadudley Did you open a thread on a support forum?

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @oliviadudley as advised please follow with support forums. We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by KaushalKhamar** [comment]
@tseward @yogkumgit 
I have experience the same behavior. But my question is if i hide a document library from SharePoint, It should be hide from both OneDrive for web as well OneDrive for mobile application. 

But if you can check this library is showing in OneDrive for web but on other side same document library is not visible in OneDrive for business application in android/ios. 

So is MicroSoft has written different API/code for OneDrive for Mobile application and web application to get document libraries from SharePoint?

**Comment by piyush1108** [comment]
@KaushalKhamar and the more interesting things is that when we raise the issue in Microsoft and in response . Microsoft given funny response on that "**It is functionality** :( ".

**Comment by tseward** [comment]
If you need this functionality, I would suggest opening a Uservoice entry at http://sharepoint.uservoice.com/.
