### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by lordBrightLord** [MicrosoftDocs/office-docs-powershell#4260]
$sa = New-SPProfileServiceApplication -Name 'User Profile Service Application' -ApplicationPool 'SharePoint Web Services Default' -ProfileDBName Profile -SocialDBName Social -ProfileSyncDBname Sync
New-ProfileServiceApplicationProxy -Name 'User Profile Service Application Proxy' -ServiceApplication $sa -DefaultProxyGroup

Second line should be New-SPProfileServiceApplicationProxy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 961a2c83-0778-31f3-fc58-69c290f569d1
* Version Independent ID: 63ea227b-9a71-c334-4832-2ab889e054fa
* Content: [New-SPProfileServiceApplicationProxy (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spprofileserviceapplicationproxy?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPProfileServiceApplicationProxy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPProfileServiceApplicationProxy.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @lordBrightLord thanks for noticing, created a pr to correct the example.
Thank you

**Comment by yogkumgit** [comment]
@tseward  and @dariomws306 Please review the PR #4276

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @lordBrightLord Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
