### ISSUE TITLE
Set-AntiphishPolicy parameters seem to be invalid

### ISSUE THREAD

**Issue by NikCharlebois** [MicrosoftDocs/office-docs-powershell#4261]
If I run (Get-Command Set-AntiphishPolicy).parameters, I get:

Key                                   Value
---                                   -----
ErrorAction                           System.Management.Automation.ParameterMetadata
EnableUnauthenticatedSender           System.Management.Automation.ParameterMetadata
EnableAntiSpoofEnforcement            System.Management.Automation.ParameterMetadata
OutVariable                           System.Management.Automation.ParameterMetadata
AdminDisplayName                      System.Management.Automation.ParameterMetadata
Verbose                               System.Management.Automation.ParameterMetadata
WhatIf                                System.Management.Automation.ParameterMetadata
WarningVariable                       System.Management.Automation.ParameterMetadata
Debug                                 System.Management.Automation.ParameterMetadata
PipelineVariable                      System.Management.Automation.ParameterMetadata
InformationAction                     System.Management.Automation.ParameterMetadata
Confirm                               System.Management.Automation.ParameterMetadata
EnableAuthenticationSoftPassSafetyTip System.Management.Automation.ParameterMetadata
OutBuffer                             System.Management.Automation.ParameterMetadata
ErrorVariable                         System.Management.Automation.ParameterMetadata
Identity                              System.Management.Automation.ParameterMetadata
AuthenticationFailAction              System.Management.Automation.ParameterMetadata
WarningAction                         System.Management.Automation.ParameterMetadata
EnableAuthenticationSafetyTip         System.Management.Automation.ParameterMetadata
Enabled                               System.Management.Automation.ParameterMetadata
MakeDefault                           System.Management.Automation.ParameterMetadata
TreatSoftPassAsAuthenticated          System.Management.Automation.ParameterMetadata
InformationVariable                   System.Management.Automation.ParameterMetadata
AsJob                                 System.Management.Automation.ParameterMetadata

Which is completely different than the list of parameters listed on:
https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-antiphishpolicy?view=exchange-ps

Is there a possibility that the docs somehow incorrectly refers to the parameters of the New-AntiphishPolicy instead of listing the proper Set-AntiphishPolicy ones?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by NikCharlebois** [comment]
Folks, we can close this one for the moment. Looks like the License assigned to the user defines what parameters the proxy will import. Assiging Security E5 to the user seems to do the trick and loads the documented properties. It may be worthwhile mentioning that requirement in the documentation.

**Comment by yogkumgit** [comment]
@ Thank you very much for the contribution and sharing this explanation. Appreciate and encourage you to do the same in future also.
