### ISSUE TITLE
No longer applies to Skype for Business Online

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#4262]
This cmdlet does not exist in version 7.0.0.0 of the SkypeOnlineConnector module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b71059c2-5587-b5d3-f10c-7c58bda96860
* Version Independent ID: 02d8870c-9e5b-069d-fa01-65819463c3de
* Content: [Get-CsOAuthConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csoauthconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOAuthConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOAuthConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @danmyhre 
That is the version I have and I have that cmdlet after importing the session

![image](https://user-images.githubusercontent.com/36666927/67776742-830c0f00-fa3f-11e9-9e56-18cf885e9fb9.png)

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @danmyhre 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by danmyhre** [comment]
Thanks, it was something on my machine.  I removed and reinstalled the module and now it is working.
