### ISSUE TITLE
What level of access is required for someone to be able to run the set-spositescript cmdlet?

### ISSUE THREAD

**Issue by michaelblumenthal** [MicrosoftDocs/office-docs-powershell#4263]
What level of access do you need in order to run this comlet? Member/Edit, Owner/Full Control, Site Collection Admin, or SharePoint Admin? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22ff33a5-2d76-efa5-5b18-1584e20195d8
* Version Independent ID: 329529cc-8b5a-b71d-0a3a-f686947cab4b
* Content: [Get-SPOSiteScript (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositescript?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScript.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScript.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @michaelblumenthal 
Site Scripts are added and modified at SharePoint tenant level, so, at minimum, a SharePoint Admin is needed.
Hope this info helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @michaelblumenthal Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
