### ISSUE TITLE
String to bytes conversion issue

### ISSUE THREAD

**Issue by IngoGege** [MicrosoftDocs/office-docs-powershell#4264]
The given examples don't work as they will always created one single string and not multiple keywords. The first example creates a dictionary with only one string:
"aarskog's syndrome, abandonment, abasia, abderhalden-kaufmann-lignac, abdominalgia, abduction contracture, abetalipo proteinemia, abiotrophy, ablatio, ablation, ablepharia, abocclusion, abolition, aborter, abortion, abortus, aboulomania, abrami's disease, abramo"
But it should create multiple strings as array:
aarskog's syndrome
abandonment
abasia
abderhalden-kaufmann-lignac
abdominalgia
abduction contracture
abetalipo proteinemia
abiotrophy
ablatio
ablation
ablepharia
abocclusion
abolition
aborter
abortion
abortus
aboulomania
abrami's disease
abramo

The correct PowerShell command would be as follows:
$Keywords = "Aarskog's syndrome","Abandonment","Abasia","Abderhalden-Kaufmann-Lignac","Abdominalgia","Abduction contracture","Abetalipo proteinemia","Abiotrophy","Ablatio","ablation","Ablepharia","Abocclusion","Abolition","Aborter","Abortion","Abortus","Aboulomania","Abrami's disease","Abramo"; $EncodedKeywords = $Keywords | ForEach-Object{[system.Text.Encoding]::UTF8.GetBytes($_+"`r`n")}; New-DlpKeywordDictionary -Identity "Diseases" -Description "Names of diseases and injuries from ICD-10-CM lexicon" -FileData $EncodedKeywords

If you create the dictionary as described in your example, it won't match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b014888-db76-1e1a-d067-bf03148815db
* Version Independent ID: 22ed9044-8fd9-213b-44f9-8965846766b6
* Content: [New-DlpKeywordDictionary (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/new-dlpkeyworddictionary?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/New-DlpKeywordDictionary.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/New-DlpKeywordDictionary.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @IngoGege, thank you for your feedback.

I think the examples are ok:

![image](https://user-images.githubusercontent.com/33589238/67888037-2c7bff00-fb2b-11e9-91d6-1f5689548d90.png)


Second one is your example. Reading the parameter description:

The FileData parameter specifies the terms that are used in the DLP keyword dictionary. This parameter requires a comma-separated list of values that's binary encoded in UTF8. For more information, see the examples in this topic.

**Comment by IngoGege** [comment]
Hi @dariomws306 ,
I get that, but have you actually tried it? If so you will see that there won't be a match. You can compare the decoded bytes and you will see that the list is not a list. It's one line with comma separated words, which is treated by the DLPAgent as one string and therefore won't match.
Ciao,
Ingo

**Comment by dariomws306** [comment]
Thank you @IngoGege.

I didn't try it deeply, only saw that it looks good. I will try it again tomorrow.

**Comment by dariomws306** [comment]
Hi @IngoGege,

Sorry for the delay.

I have been testing it and it's true that the example doesn't match:
![image](https://user-images.githubusercontent.com/33589238/68676469-e1091e00-0538-11ea-8105-508bcaacffd3.png)

But I get the same behaviour with your example:
![image](https://user-images.githubusercontent.com/33589238/68676504-f41bee00-0538-11ea-8c31-927ede6fe564.png)

So I'm trying to find the right way to create the list of strings.

@chrisda maybe you can help.

Thanks to both!

**Comment by IngoGege** [comment]
@dariomws306 @yogkumgit sorry for the delay. Actually I just figured out that the special characters were removed:
`$Keywords = "Aarskog's syndrome","Abandonment","Abasia","Abderhalden-Kaufmann-Lignac","Abdominalgia","Abduction contracture","Abetalipo proteinemia","Abiotrophy","Ablatio","ablation","Ablepharia","Abocclusion","Abolition","Aborter","Abortion","Abortus","Aboulomania","Abrami's disease","Abramo"; $EncodedKeywords = $Keywords | ForEach-Object{[system.Text.Encoding]::UTF8.GetBytes($_+"`r`n")}; New-DlpKeywordDictionary -Identity "Diseases" -Description "Names of diseases and injuries from ICD-10-CM lexicon" -FileData $EncodedKeywords`
The character "`" was missing. I've tested 2 possible solutions and documented them here:
https://ingogegenwarth.wordpress.com/2019/10/31/office-365-dlp-pesky-keyword-dictionaries/

The change you merged needs to be updated.
Ciao,
Ingo

**Comment by dariomws306** [comment]
Thank you @IngoGege!

I have tested and it works perfect. I'm updating example 1 and example 2 also as it has the same problem.

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4446

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @IngoGege Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
