### ISSUE TITLE
Article needs Claims authentication example

### ISSUE THREAD

**Issue by lordBrightLord** [MicrosoftDocs/office-docs-powershell#4266]
Was sent here from trying to create a new web application via PowerShell in SharePoint 2016. It said to use Claims auth, but an example isn't provided of how to construct that within the -AuthenticationProvider parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6316f255-a35c-8a88-2459-bdf8dd0a3787
* Version Independent ID: fdbaf4a2-51b1-7e63-4b15-48327f1c8915
* Content: [New-SPWebApplication (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/New-SPWebApplication?redirectedfrom=MSDN&view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPWebApplication.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPWebApplication.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips and @dariomws306  Please review this PR #4271

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @lordBrightLord Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
