### ISSUE TITLE
 new-pnpterm requires LCID "1033", documentation missing

### ISSUE THREAD

**Issue by holylander** [MicrosoftDocs/office-docs-powershell#4272]
In order to use **new-pnpterm**, I had to use the option 
`-LCID "1033"`
which is not included in the documentation. I think that it should be mentioned, since if don't use such flag, command wont work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c537bdf-b8fc-9735-1870-355e757b531a
* Version Independent ID: 68d5bb2b-9256-601f-7f44-14c447293c91
* Content: [New-PnPTerm (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpterm?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPTerm.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPTerm.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @holylander  ! thanks for your feedback!
I need to kindly redirect you to this specific [repo](https://github.com/SharePoint/PnP-PowerShell) where you can either open an issue there or propose a PR directly into [the source code](https://github.com/SharePoint/PnP-PowerShell/blob/dev/Commands/Taxonomy/NewTerm.cs) of the cmdlet which has the documentation that is reflected later in the article.

Thank You

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for sharing this explanation. @holylander  Hope this comment is helpful for you. These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to follow the suggested links.
