### ISSUE TITLE
Typo :)

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#4274]
Removes-CsOnlinePSTNGateway | ?{$_.Identity -like "*.contoso.com"}
instead of 
Remove-CsOnlinePSTNGateway | ?{$_.Identity -like "*.contoso.com"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c451fd8-202d-1833-c666-f800d6ad6e15
* Version Independent ID: 9152a3e8-15eb-05d8-8ec3-63fc3a124ff6
* Content: [Remove-CsOnlinePSTNGateway (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/remove-csonlinepstngateway?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Remove-CsOnlinePSTNGateway.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Remove-CsOnlinePSTNGateway.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DEberhardt thanks for noticing that, I created a pull request to correct the example.
Thanks again

**Comment by yogkumgit** [comment]
@kenwith  Please merge this PR #4343

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @DEberhardt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
