### ISSUE TITLE
Examples have wrong parameter

### ISSUE THREAD

**Issue by thomasbinder** [MicrosoftDocs/office-docs-powershell#4275]
Some of the examples have the parameter "DatabasePath" but should be plural: "DatabasePaths"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715baf5f-4102-873c-510e-da688b9b5a45
* Version Independent ID: caf92dad-8c31-b9ef-5fc5-ca04085b8620
* Content: [Install-CsDatabase (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/install-csdatabase?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Install-CsDatabase.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Install-CsDatabase.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @thomasbinder how are you? Thanks for noticing this. I created a pull request to correct the article.
Thanks again.

**Comment by yogkumgit** [comment]
@hirenshah1 Please merge the PR #4344

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @thomasbinder Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
