### ISSUE TITLE
Error in description of -Filter parameter

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#4283]
Description of the -Filter parameter contains an usage example:
`-Filter {Enabled -ne $True}`

But if I run this code on my server, it returns an error.

command:
`Get-CsAdPrincipal -Filter { Enabled -ne $true }`

error message:

> Get-CsAdPrincipal : Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Query not supported for property: "Enabled" query: " Enabled -ne $true " position: "2""

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae26e0a-40c8-ad2f-42cf-252d56b6e882
* Version Independent ID: 5b0a78a5-f72c-6166-83f5-2b5194883b99
* Content: [Get-CsAdPrincipal (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csadprincipal?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Get-CsAdPrincipal.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsAdPrincipal.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @shivtorov 
Thanks for noticing this, I could verify that Enabled is not a valid filterable property of this cmdlet.
I created a pull request to correct the documentation on this article
Thanks again.

**Comment by yogkumgit** [comment]
@hirenshah1  Please merge this PR #4345

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @shivtorov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
