### ISSUE TITLE
Exception calling "GetSteppablePipeline" with "1" argument(s)

### ISSUE THREAD

**Issue by toybits** [MicrosoftDocs/office-docs-powershell#4284]
I've got one machine which keeps getting the following error when launching the ExO MFA PowerShell module.

`Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element
produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object."
At C:\Program Files\WindowsPowerShell\Modules\PSLog\5.5.268\PSLog.psm1:557 char:13
+             $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyI ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RuntimeException`

I've removed and readded, removed, rebooted and readded and neither worked. 

I've got three other machines where it's working fine so I'm assuming it's machine specific. 

This is the block it doesn't like in PSLog.psm1 but I'm not good enough at debugging to track down what it's calling.

`            Write-LogEntry -EntryType Information -Message $Object -SupressConsole
            $outBuffer = $null
            if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer))
            {
                $PSBoundParameters['OutBuffer'] = 1
            }
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand('Write-Host', [System.Management.Automation.CommandTypes]::Cmdlet)
            $scriptCmd = {
                & $wrappedCmd @PSBoundParameters
            }
            $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
            $steppablePipeline.Begin($pscmdlet)`

Has anyone else seen this?

**Comment by toybits** [comment]
OK not sure what the problem was. Had to remove AutomatedLab so I could remove the module PSLog

Then ExO started working. Have reinstalled PSLog and ExO still working so will never know what it was.

But busy got to crack on...

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit
