### ISSUE TITLE
Setting Person/Group field fails

### ISSUE THREAD

**Issue by JaeEmAre67** [MicrosoftDocs/office-docs-powershell#4285]
All of the following fail without error. I can look at the backend item and see the original values still there. The column is a person/group field we added and we are using the backend field name, not the frontend. It only allows a single entry, not multiple.

Set-PnPListItem -List $list.Title -Identity $item.Id -Values @{"ContentOwnerMgr"="6"} -SystemUpdate;

Set-PnPListItem -List $list.Title -Identity $item.Id -Values @{"ContentOwnerMgr"="6"};
$item.SystemUpdate();

Set-PnPListItem -List $list.Title -Identity $item.Id -Values @{"ContentOwnerMgr"="6"};
$item.UpdateOverwriteVersion();

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @JaeEmAre67 
I need to kindly redirect you to open an issue in [this other repo](https://github.com/SharePoint/PnP-PowerShell/issues), where will be handled by the PnP community.
Please verify there, if this hasn't been reported in the past.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @JaeEmAre67 
These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
