### ISSUE TITLE
Get-PnpUnifiedGroup is throwing errors

### ISSUE THREAD

**Issue by theplaceboeffect** [MicrosoftDocs/office-docs-powershell#4289]
Hi,

I had some scripts I am working on using Get-PnpUnifiedGroup and it is currently throwing the following errors in all my environments (production and development):

get-pnpunifiedgroup : Object reference not set to an instance of an object.
At line:1 char:1
+ get-pnpunifiedgroup
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PnPUnifiedGroup], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,SharePointPnP.PowerShell.Commands.Graph.GetUnifiedGroup

Do you know if anything has changed in the backend to cause this?

I am using SharePointPnPPowerShell2019 3.12.1908.1.

Thanks.

-mwt

**Comment by tseward** [comment]
Alright did some testing based on feedback... :) Use `Connect-PnPOnline -Graph` and you should be set.

**Comment by theplaceboeffect** [comment]
Thanks for the quick response. I’ll let you know if it worked. If I use this, will I also be able to create s SharePoint objects?

My code is switching between connecting to the -admin and regular sites. Is this a way to be able to do everything with one login?

**Comment by theplaceboeffect** [comment]
Dang. No luck:
```
PS C:\Users\mwt\projects\dataservices\drw-document-portal\powershell> connect-pnponline https://manweitamdev.sharepoint.com -Graph -UseWebLogin
Connect-PnPOnline : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ connect-pnponline https://manweitamdev.sharepoint.com -Graph -UseWebL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-PnPOnline], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,SharePointPnP.PowerShell.Commands.Base.ConnectOnline
```
Strangely, the version I am now seeing using Get-Module is running "SharePointPnPPowerShellOnline" v3.13.1909.0

**Comment by tseward** [comment]
Just use `Connect-PnPOnline -Graph`. You should get a device code authentication prompt in a browser.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by theplaceboeffect** [comment]
@tseward - gotcha - I didn't realize -useweblogin and -graph are mutually exclusive; so it's working now. Thanks!

How do I run my scripts with cached authentication? And why would everything be working before and now it doesn't?

**Comment by tseward** [comment]
@theplaceboeffect The -Graph switch is a device-based logon -- it should just work without explicit credentials after the initial run. Is that not what you're seeing?

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @theplaceboeffect Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by theplaceboeffect** [comment]
@tseward - sorry, I missed that reply. Yes, that worked perfectly. I've since evolved (devolved?) to storing the passwords in an secured string in memory so that I can have unattended scripts. I'm still not perfectly happy with it but it does mean I don't have to babysit my scripts.
