### ISSUE TITLE
Clarity: -Template for Staff Notebooks?

### ISSUE THREAD

**Issue by jefflundberg** [MicrosoftDocs/office-docs-powershell#4292]
The ```-Template``` parameter for ```New-Team``` has ```EDU_Class``` and ```EDU_PLC``` types defined, but no mention of Staff Teams (```EDU_Staff``` for example) as described in the article [Choose a team type to collaborate in Microsoft Teams](https://support.office.com/en-us/article/choose-a-team-type-to-collaborate-in-microsoft-teams-0a971053-d640-4555-9fd7-f785c2b99e67)

Is this supported at all? Am I missing something?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jefflundberg 
Thanks for your feedback, as the article says:

> Note that Templates are not yet supported in our 1.0 PowerShell release.

Also checked with 1.0.2 version as is not yet supported.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @jefflundberg 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jolscr** [comment]
EDU_Staff is now supported in PowerShell? Because in Graph it is... https://docs.microsoft.com/en-us/MicrosoftTeams/get-started-with-teams-templates

**Comment by get-itips** [comment]
> EDU_Staff is now supported in PowerShell? Because in Graph it is... https://docs.microsoft.com/en-us/MicrosoftTeams/get-started-with-teams-templates

Tested with 1.1.10-preview and it is not yet available to use. Hope this info helps you. Thanks
