### ISSUE TITLE
Cannot find commandlet and broken link

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/office-docs-powershell#4297]
First, the broken link at the top of the page. It is listed that this is in the "Exchange" module. When I click the link, there's a 404 error.

Second, this commandlet is not present in the Exchange management Shell for Exchange 2013. Running from a CAS, I see the "Get-MailboxFolderPermission" and "get-MailboxFolderStatistics", but not "Get-MailboxFolder", as this article directs. What module do I need to use it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56a8cdb6-3500-21d9-fa18-b1b0eec61cc3
* Version Independent ID: ab676fe2-59b3-2ca3-f187-70a86f97e1b6
* Content: [Get-MailboxFolder (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailboxfolder?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-MailboxFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-MailboxFolder.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @JLambEJG, thank you for your feedback.

When you try to run this cmdlet you get "cmdlet doesn't exist" or "mailbox doesn't exist"?

Have in mind this statement:
Use the Get-MailboxFolder cmdlet to view folders in your own mailbox. Administrators can't use this cmdlet to view folders in other mailboxes (the cmdlet is available only from the MyBaseOptions user role).

Also, please try to run this cmdlet:
Get-ManagementRole –Cmdlet “Get-MailboxFolder”

If you get something, it's available.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @JLambEJG 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
