### ISSUE TITLE
Paramater -DisallowMembersViewMembership

### ISSUE THREAD

**Issue by John471** [MicrosoftDocs/office-docs-powershell#4320]
Paramater -DisallowMembersViewMembership
This seems confusing. In the UI there is no option to disallow Members from viewing the membership of the group. Rather, there are two options for who is allowed to view membership:-
1) *Only* Group Members
2) Everyone
Please clarify what this parameter does and how to use it. "DisallowMembersViewMembership" is highly un-intuitive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44489c78-274c-2c09-cd51-16f6ed183317
* Version Independent ID: eadbb80c-20fb-9bec-a996-325762c315d4
* Content: [New-PnPGroup (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpgroup?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPGroup.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @John471 

I need to kindly redirect you to this other repo for [PnP issues](https://github.com/SharePoint/PnP-PowerShell/issues)
As you might know, PnP cmdlets are community-driven, a member of the community will pick your request there and handle it, please do a search first in the issues to see if this has been already reported.

Hope this info helps you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @John471 
These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
