### ISSUE TITLE
Example 1 uses wrong command

### ISSUE THREAD

**Issue by SimonSkotheimsvik** [MicrosoftDocs/office-docs-powershell#4321]
The command in Example 1 is using Set-SafeAttachmentsPolicy instead of Set-SafeLinksPolicy which should be covered in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 923dc552-f943-e043-165d-9ed5fb734c6c
* Version Independent ID: fe62e834-2cb1-0a15-0d93-14194ca0e33a
* Content: [Set-SafeLinksPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-safelinkspolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Set-SafeLinksPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Set-SafeLinksPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda  Pleae merge this PR #4392

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @SimonSkotheimsvik Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
