### ISSUE TITLE
example

### ISSUE THREAD

**Issue by WillemVerwijs** [MicrosoftDocs/office-docs-powershell#4322]
so how do I use the Set-OwaMailboxPolicy -OutlookBetaToggleEnabled $false - command in a way that all users have this disabled?
Real-world(!) examples would be so great on pages like this. What can I do get those?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ca7906-9f33-2991-9da9-a626e5e45c46
* Version Independent ID: 5f388b3c-fb47-f7a0-e648-07cb3e59cf72
* Content: [Set-OwaMailboxPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-owamailboxpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @WillemVerwijs, thank you for your feedback.

This document is specific to and you should use Set-CASMailbox to assign this policy. Please check:
https://docs.microsoft.com/exchange/clients-and-mobile-in-exchange-online/outlook-on-the-web/apply-or-remove-outlook-web-app-mailbox-policy#use-exchange-online-powershell-to-apply-an-outlook-on-the-web-mailbox-policy-to-a-mailbox

Also, I am adding several articles to the "Related Links" section. Hope it helps.

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #4385

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @WillemVerwijs Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
