### ISSUE TITLE
Get-CsDialPlan: Appliets to is incorrect

### ISSUE THREAD

**Issue by ssteiner** [MicrosoftDocs/office-docs-powershell#4325]
The Applies to section says it Get-CsDialplan applies to Skype for Business online. Yet, it appears this is no longer correct. When I log into my tenant, it tells me Get-CsDialplan is not a known command. The same goes for Get-CsVoicePolicy. The doc should be updated accordingly. 

And is there a central place where changes in these commandlets are kept? Just noticing the change if a commandlet stops working is somewhat iffy.. isn't there a central changelog somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bce1475-ff1d-ae12-780b-c50164f59841
* Version Independent ID: d78e0a6e-14a9-1a8e-33ad-f209ca1a7197
* Content: [Get-CsDialPlan (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csdialplan?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsDialPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsDialPlan.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by KCarole** [comment]
I have been experiencing the same problem since Monday with Get-CsDialplan and Get-CsVoicePolicy commands. 
These two commands worked last week. 
Is it a bug or a  choice of MS?  
How can we be informed of these changes?

**Comment by get-itips** [comment]
Hello @rogupta @tomkau can you confirm these cmdlets have been removed from SkypeFB Online? I checked and I can confirm that are not present in my tenant but I do want a final confirmation from you.
Thank you

**Comment by jduvillier** [comment]
Same issue here, looks to be since start of November?
Could we please have confirmation whether these cmdlets were retired from the online module?

**Comment by tomkau** [comment]
@get-itips -- heard back from the team that owns these.  They do not apply to online and the documentation should be updated to reflect this.

**Comment by get-itips** [comment]
Ok @tomkau will take care of that. Thanks for letting me know

**Comment by yogkumgit** [comment]
@tomkau Please merge this PR #4492

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ssteiner Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ParaGlideRocks** [comment]
Does the **-Tenant** option still apply?
