### ISSUE TITLE
Exchange v2 online powershell command get-exomailbox -inactiveonly returns incomplete results

### ISSUE THREAD

**Issue by warrenstark** [MicrosoftDocs/office-docs-powershell#4329]
I've noticed in our environment the command 
"get-exomailbox -inactivemailboxonly -resultsize unlimited" returns only a very small subset of our inactive mailboxes. Indeed, it returns exactly the same subset as "get-exomailbox -softdeletedmailbox -resultsize unlimited".

We returned ~2500 mailbox details in both commands but expected over 100k returns; waiting on exact numbers using old get-mailbox still.

I suspect there's an issue with what is happening with -inactivemailboxonly is searching for.

**Comment by warrenstark** [comment]
122k records returned with old get-mailbox -inactivemailboxonly

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @warrenstark, thank you for your feedback.

We are here to help to improve documentation. To suggest product improvements, in this case I can suggest you the next options:
https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Exchange-Admin-Improvements-Announced-at-Microsoft-Ignite-2019/ba-p/982121 (leave a comment here)
https://techcommunity.microsoft.com/t5/Exchange/ct-p/Exchange

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @warrenstark Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
