### ISSUE TITLE
Async missing description

### ISSUE THREAD

**Issue by rfoust** [MicrosoftDocs/office-docs-powershell#4330]
The -Async property is missing a description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b640892-b0a1-4f20-1e25-fe5f0e97f5b6
* Version Independent ID: 51774b36-90fa-1d9a-5800-1a54d9f70590
* Content: [Get-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by rfoust** [comment]
Also, the -Async property is required in addition to -Properties on that particular parameter set. So if you do a "Get-Mailbox -Properties Name" then it prompts for the -Async param.  On this page, it suggests that it's optional:

Get-Mailbox
   [-Async]
   -Properties <String[]>
   [-Archive]

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @rfoust, thank you for your feedback.

I think these parameters aren't still available.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @rfoust Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
