### ISSUE TITLE
Get-EXOMailboxPermission - Error when piped from Get-EXOMailbox

### ISSUE THREAD

**Issue by yoDANIMALgurt** [MicrosoftDocs/office-docs-powershell#4333]
No issue when piping Get-EXOMailbox to Get-MailboxPermission...

```
PS > Get-EXOMailbox -RecipientTypeDetails SharedMailbox -ResultSize Unlimited | Get-EXOMailboxPermission -User 'user@contoso.com'
Get-EXOMailboxPermission : Error while querying REST service. HttpStatusCode=404 ErrorMessage={"error":{"code":"NotFound","message":"An server side error occured.","innererror":{"message":"An server side error
occured.","type":"Microsoft.Exchange.Admin.OData.Core.ODataServiceException"}}}
At line:1 char:76
+ ... Unlimited | Get-EXOMailboxPermission -User 'user@contoso. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ProtocolError: (:) [Get-EXOMailboxPermission], RestClientException
    + FullyQualifiedErrorId : An error occurred while processing this request.,Microsoft.Exchange.Management.RestApiClient.GetExoMailboxPermission
```

exchange/exchange-ps/exchange/powershell-v2-module/Get-EXOMailboxPermission.md

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @yoDANIMALgurt, thank you for your feedback.

It works for me:
![image](https://user-images.githubusercontent.com/33589238/68894168-7d801b80-0705-11ea-8280-ed44f904b33c.png)

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @yoDANIMALgurt Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yoDANIMALgurt** [comment]
@dariomws306 oh ok now it works for me too.
