### ISSUE TITLE
Add OnQuickLaunch switch to Set-PnPList 

### ISSUE THREAD

**Issue by marcdayton** [MicrosoftDocs/office-docs-powershell#4342]

**Comment by marcdayton** [comment]
Can OnQuickLaunch be added to this commandlet Set-PnpList?  Need to be able to add a list to the quicklaunch.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @marcdayton 

I need to kindly redirect you to this [other repo](https://github.com/SharePoint/PnP-PowerShell/issues) for PnP issues
As you might know, PnP cmdlets are community-driven, a member of the community will pick your request there and handle it, please do a search first in the issues to see if this has been already reported.

Hope this info helps you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @marcdayton 
These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
