### ISSUE TITLE
Example 3 wrong

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/office-docs-powershell#4346]
Example 3 is off by three zeroes

Currently it is 
&gt; Set-SPOSite -Identity https://contoso.sharepoint.com -StorageQuota 1500 -StorageQuotaWarningLevel 1400000

and it should be 
&gt; Set-SPOSite -Identity https://contoso.sharepoint.com -StorageQuota 1500 -StorageQuotaWarningLevel 1400

I think example 3 can be deleted completely. As Example 5 does exactly the same and thus example 3 doesn't add any additional value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1c6b2b-5af6-acce-b7e8-bf784bb0973e
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Weishaupt Thanks for your feedback. I created a Pull Request proposing correcting the article.
Thank you

**Comment by yogkumgit** [comment]
@trent-green Please merge the PR #4387

**Comment by Weishaupt** [comment]
What is the benefit of keeping both: Example 3 and 5?

**Comment by get-itips** [comment]
> What is the benefit of keeping both: Example 3 and 5?
Hello Marvin, I'll leave that decision to the article's author. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Weishaupt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
