### ISSUE TITLE
Add "For More Information" section

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/office-docs-powershell#4347]
Consider adding a "For More Information" section at the bottom of the page as follows:

## For More Information
For more information:

* The (ConnectExchangeOnlinePowerShell)[https://gallery.technet.microsoft.com/Connect-to-Exchange-Online-7d7365e0] script on TechNet can assist in installing the *Exchange Online Remote PowerShell* module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @lesterw1, thank you for your feedback.

This script is not official and we cannot add unofficial scripts or articles to docs.microsoft.com.

**Comment by lesterw1** [comment]
Thanks @dariomws306. The install process is tedious and poorly documented elsewhere. I personally spent over an hour trying to find the necessary steps. Perhaps the steps can be re-captured herein as follows:

### To Install the Exchange Online PowerShell Module for MFA
Launch Internet Explorer or Edge and enter the URL https://cmdletpswmodule.blob.core.windows.net/exopsmodule/Microsoft.Online.CSE.PSModule.Client.application".  Alternatively, Login to Exchange Admin Center using Internet Explorer or Edge and go to Hybrid and click the **Configure** button to download the Exchange Online PowerShell Module for MFA. [NOTE: Installation of .application modules only works with Internet Explorer or Edge].

**Comment by dariomws306** [comment]
Hi @lesterw1, the same steps are documented in the article. Please check the third bullet:
https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell#what-do-you-need-to-know-before-you-begin

Or... I think I'm not understanding you.

Please let me know. Thank you!

**Comment by lesterw1** [comment]
Ah so it is.  Perhaps this could be annotated to allow direct install via: 
Launch Internet Explorer or Edge and enter the URL https://cmdletpswmodule.blob.core.windows.net/exopsmodule/Microsoft.Online.CSE.PSModule.Client.application"

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @lesterw1 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
