### ISSUE TITLE
404 Error on all "Module: exchange" links for cmdlets

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/office-docs-powershell#4349]
The text at the top of this page which says: "Module: [exchange](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/?view=exchange-ps)" returns a 404 error.  References on all the other pages such as the Set-OrganizationConfig have the same issue.

As a result, there is no detail on where to find this elusive "exchange" PowerShell module (a search on (PowerShellGallery.com)[https://powershellgallery.com] yields no meaningful results unfortunately.  *Can some information be added about where to install this module from?*  Perhaps add a page for this as I have seen conflicting information. It appears that the **Exchange Management Tools** need to be installed... 

Some leads:
* https://www.msb365.blog/?p=515
* https://blogs.technet.microsoft.com/samdrey/2017/12/17/how-to-load-exchange-management-shell-into-powershell-ise-2/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 127e4827-2493-4709-6b1c-62bba341e3ab
* Version Independent ID: e4bf79e9-b3ab-3a24-3a0d-76cafb04d9f6
* Content: [Get-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/get-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Get-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Get-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @lesterw1, thank you for your feedback.

This is a well known issue and we are looking on to it.

**Comment by yogkumgit** [comment]
@ Thank you very much for sharing this information. @lesterw1 writer will update the document once we reached to the resolution. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dariomws** [comment]
The Exchange module link issue was fixed this week. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
