### ISSUE TITLE
Command is not available in PS session

### ISSUE THREAD

**Issue by adv0cem** [MicrosoftDocs/office-docs-powershell#4352]
After establishing connection to Office 365 Security & Compliance Center using Connect-IPPSSession -UserPrincipalName &lt;my username&gt; New-DlpEdmSchema command is not available in the list of imported commands.
 
Remove-DlpEdmSchema and Get-DlpEdmSchema are available but not New-DlpEdmSchema.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d48d419-9647-b892-5b71-96fcce0325ae
* Version Independent ID: cd7deb2b-2f68-14f2-aeeb-cde75fd21168
* Content: [New-DlpEdmSchema (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/new-dlpedmschema?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/New-DlpEdmSchema.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/New-DlpEdmSchema.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @adv0cem, thank you for your feedback.

I suggest that you open a support case as I can see that the cmdlet is available in my lab tenant:
![image](https://user-images.githubusercontent.com/33589238/69469721-18fe3580-0d71-11ea-9e87-ce99b42f49a4.png)

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @ravick4u
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution.

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
