### ISSUE TITLE
Get TimeZone Command

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/office-docs-powershell#4353]
The command "$TimeZone = Get-ChildItem "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Time zones" | foreach {Get-ItemProperty $\_.PSPath}; $TimeZone | sort Display | Format-Table -Auto PSChildname,Display" doesn't work for me. Outside of troubleshooting this, can you just link us to a doc page that lists the Time Zones in question? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4acd15e-7bab-4251-dbcb-a075611fcdef
* Version Independent ID: 90b61091-8343-7071-e56d-d963096e3f37
* Content: [Set-MailboxRegionalConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/Set-MailboxRegionalConfiguration?redirectedfrom=MSDN&view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-MailboxRegionalConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-MailboxRegionalConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by pyoungberg** [comment]
For those that are curious: https://support.microsoft.com/en-us/help/973627/microsoft-time-zone-index-values

**Comment by pyoungberg** [comment]
Note, when setting "U.S. Mountain Standard Time" I had to remove the (.)'s in the string value. It appears the "Microsoft.Exchange.Data.Storage.Management.ExTimeZoneValue" they're looking for doesn't align to the list I linked above exactly. I'd like to see the Docs team make a new article with the correct values and link it here.

**Comment by chrisda** [comment]
I tried the command as written and it worked for me in these environments:

- Windows 10 v1903 and PowerShell v5.1.18362.145 connected to an Office 365 E5 tenant.

- Exchange Management Shell on Windows Server 2012 R2 and PowerShell v4 connected to Exchange 2016 and Exchange 2013.

- Exchange Management Shell on Windows Server 2016 and PowerShell v5.1.14393.3053 connected to Exchange 2019.

Is there anything peculiar about your PowerShell environment (v6, Core, etc.)?

**Comment by pyoungberg** [comment]
Hi Chris, please see my last comments above. This is the type of info that should be available in a document, not accessed by a script that may or may not work for every user. Could you output the content of running that script into a document and link it here?

**Comment by chrisda** [comment]
There are advantages and disadvantages to each approach.

Having a 'script' (actually, two commands stuck together on one line) that works (important point) is far easier to maintain than a topic with a static list of values that will (notice I didn't say 'might') get-out-of-date or change across different versions of Windows.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @pyoungberg 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
