### ISSUE TITLE
Set-CASMailboxPlan missing settings that are configurable on user basis

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/office-docs-powershell#4357]
I'm missing the possibility to disable SMTPClientAuth on the CASMailboxPlan level. This is possible on a per-user basis, but should IMHO also be possible at the mailbox plan level.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Weishaupt, thank you for your feedback.

We are here to help to improve docs.microsoft.com, we cannot help you new features request. Please to request this feature go to:
https://office365.uservoice.com/

In the next link you can find something similar and you can vote:
https://office365.uservoice.com/forums/264636-general/suggestions/34472356-allow-admins-to-fully-manage-the-casmailboxplan-to

**Comment by yogkumgit** [comment]
@Weishaupt   Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
