### ISSUE TITLE
EWS usage reporting missing in Graph

### ISSUE THREAD

**Issue by umutge** [MicrosoftDocs/office-docs-powershell#4359]
Article claims functionality of Get-Connection​ByClient​Type​Detail​Report commandlet.But this deprecated commandlet used to provide O365 EWS usage, while Microsoft Graph does not.

Graph v1.0 response: https://docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageuserdetail?view=graph-rest-1.0&tabs=http#response
Graph beta response: https://docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageuserdetail?view=graph-rest-beta&tabs=http#response

Are there any plans to include EWS usage (when queried from MS Graph)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53ea7ef0-38d7-965f-7c03-0282afd485fb
* Version Independent ID: 6d529bfa-3b57-b838-d37b-e054405544bf
* Content: [Get-ConnectionByClientTypeDetailReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/reporting/get-connectionbyclienttypedetailreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/reporting/Get-ConnectionByClientTypeDetailReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/reporting/Get-ConnectionByClientTypeDetailReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @umutge, thank you for your feedback.

I think you can get similar information with reportRoot:getEmailAppUsageUserDetail. All you can find in the next place is all what you get:
https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0
Sorry but at this time I cannot provide you here with information about planned feature from the product group.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @umutge 
Hope this comment is helpful for you.If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Please keep contributing with your suggestions to improve the documentation.
