### ISSUE TITLE
Where are the logs saved to?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/office-docs-powershell#4361]
For -LogLevel and -LogOnly where are the logs saved to?  I've run this cmdlet twice, no error, but no emails copied and no folder created in target mailbox.  Can't find the log files anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c6c666-7221-7984-82a5-d731fee0ac3d
* Version Independent ID: 6970ac1a-0aaa-c625-24db-e3db2296b6f8
* Content: [Search-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/search-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Canis-Lupis, thank you for your feedback.

-TargetFolder and -TargetMailbox parameters are mandatory when you use -LogLevel or -LogOnly.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @Canis-Lupis Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Please keep contributing with your suggestions to improve the documentation.
