### ISSUE TITLE
KeySize parameter correction

### ISSUE THREAD

**Issue by Lsvingen** [MicrosoftDocs/office-docs-powershell#4364]
The KeySize parameter has both 1024 and 2048 as accepted values, atleast per version 1.1.166.0 of the MSOnline module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd23aab2-5378-59a2-951f-3d808871f872
* Version Independent ID: fef7c224-f830-5056-685d-c2b61ec22c6c
* Content: [Rotate-DkimSigningConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/rotate-dkimsigningconfig?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Rotate-DkimSigningConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Rotate-DkimSigningConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @Lsvingen Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
