### ISSUE TITLE
ArgumentNullException at using Add-PnPTaxonomyField 

### ISSUE THREAD

**Issue by WuWei42** [MicrosoftDocs/office-docs-powershell#4365]
If I try to excecute the documented example I will get an ArgumentNullException:
```
Add-PnPTaxonomyField -DisplayName "Test" -InternalName "Test" -TermSetPath "TestTermGroup|TestTermSet"
```
Part of the exception message: 
```
 Add-PnPTaxonomyField : Der Wert darf nicht NULL sein.
 Parametername: taxonomyItem
+ Add-PnPTaxonomyField -TermSetPath "Medium" -DisplayName "TaxColTest2" ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPTaxonomyField], ArgumentNullE 
   xception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Fields.Ad 
   dTaxonomyField
```
My target system ist SPO.

Does anyone has the same exception and have probably an workaround for me?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by WuWei42** [comment]
Ok. I have found the solution. 
I have used the termset display name instead of technical name. 
Unfortunatly it is not so easy to find out the technical name of an term to define the correct path.
