### ISSUE TITLE
cant enable side loading

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/office-docs-powershell#4366]
Hello, I want to enable the Side Loading feature. It isn't possible through Web UI (got an error message) and as well using PowerShell:

Set-CsTeamsAppSetupPolicy -Identity global -AllowSideLoading:$true
Invalid value for App Id(s).
    + CategoryInfo          : InvalidArgument: (Microsoft.Rtc.M...sAppSetupPolicy:TeamsAppSetupPolicy) [Set-CsTeamsApp
   SetupPolicy], PSArgumentException
    + FullyQualifiedErrorId : CustomValidationFailed,Microsoft.Rtc.Management.Internal.SetTeamsAppSetupPolicyCmdlet
    + PSComputerName        : admin0e.online.lync.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622b57db-dc8f-4fa7-7f65-5e362dca603d
* Version Independent ID: 91f0f246-e6c5-c2e2-1569-7f27afb28c04
* Content: [Set-CsTeamsAppSetupPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsappsetuppolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsAppSetupPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsAppSetupPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @SRE93 Hope you are doing great.
I tried to set the AllowSideLoading attribute of the Global AppSetupPolicy as you tried and had no issues

![image](https://user-images.githubusercontent.com/36666927/68947834-33467b00-0795-11ea-8f21-96241842224a.png)

I recommend opening a support ticket directly in your tenant if you continue seeing that error, also I will try to contact the product team to find out if this cmdlet is ready for production.

**Comment by yogkumgit** [comment]
@nomorephones  please help us with your explanation on this cmdlet

**Comment by nomorephones** [comment]
@yogkumgit the [documentation for this cmdlet](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsappsetuppolicy?view=skype-ps) states 

> The existence of this cmdlet is being documented for completeness, but do not use this cmdlet. We require that all creation and modification of app setup polices (not including the assignment or removal of policies from users) happens in the Microsoft Teams & Skype for Business Admin Center to ensure that the policy matches your expectations for the end user experience.

**Comment by get-itips** [comment]
Thanks @nomorephones Jamie, did not notice that, so we can close this thread based on that. Thank you again.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @SRE93 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by SRE93** [comment]
Hi, we were using a customized global app policy. We pinned the "Search" app in the sidebar. Unfortunally the search app isnt available any more in Teams App store and that's why I got the error "invalid app id". I resetted the global policy and then I could activate the side loading - per GUI and PowerShell. Thanks to all.

**Comment by get-itips** [comment]
Great to hear, we will proceed closing this again.
