### ISSUE TITLE
Example two has an typo

### ISSUE THREAD

**Issue by sischanz** [MicrosoftDocs/office-docs-powershell#4368]
When executing "Set-CsAuthConfig -Scenario BlockWindowsAuthExternallyAndModernAuthInternally" I receive this: 
Set-CsAuthConfig : Cannot bind parameter 'Scenario'. Cannot convert value "BlockWindowsAuthExternallyAndModernAuthInternally" to type

This works fine:
Set-CsAuthConfig -Scenario BlockWindowsAuthExternalyAndModernAuthInternally

Seems that Externaly is implemented with one l in that case

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26656471-f4e4-3dbe-b915-5230400d7b7f
* Version Independent ID: 4dc006ee-6bf8-a929-94f7-499a5af1f7a1
* Content: [Set-CsAuthConfig (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csauthconfig?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsAuthConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsAuthConfig.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sischanz thanks for noticing.
We managed to report this to the product team and they are now aware of this, and we can expect some news from them too.
We do not tend (and like) to document a bug, but in this case, I was told to add a note until the cmdlet is fixed.
Also found this [support article](https://support.microsoft.com/en-us/help/4346673/new-cmdlets-to-manage-skype-for-business-server-2015-authentication) that documents the parameter with one L.
Thank you
