### ISSUE TITLE
Creating Groups in bulk using powershell

### ISSUE THREAD

**Issue by asajrawat211993** [MicrosoftDocs/office-docs-powershell#4369]
I have created a powershell script for creating groups.
I am using the following command in a for loop
`New-UnifiedGroup -AccessType Public -Alias $groupIdentity -DisplayName $groupDisplayName -Owner $smtpAddress`
I am trying to create a 1000 groups and executing above command for a single time takes around 8 seconds so creating 1000 takes a long time. Is there any command exist using which I can create Groups in bulk just using a single command.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @asajrawat211993, thank you for your feedback.

Sorry, there is now way to do it. Single line yes, but not single command.

Are you using something like "Import-Csv file.csv | New-UnifiedGroup -AccessType Public -Alias $_.GroupIdentity -DisplayName $_.GroupDisplayName -Owner $_.SmtpAddress"?

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @asajrawat211993 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
