### ISSUE TITLE
SPMT MFA in SP onprem

### ISSUE THREAD

**Issue by micholus** [MicrosoftDocs/office-docs-powershell#4371]
Hello.
I'm trying to migrate content from SharePoint 2013 to SPO.
My SP 2013 is using ADFS with MFA authentication.
Is there a way to use the SPMT tool to get the MFA credentials to add a migration task. Something similar to running register-spmtmigration without supplying the credentials which opens the authentication window.
Right now I'm getting the following error when trying to start the migration :
"Task xxxxxxxx  did NOT pass the parameter validation, the error message is 'Username or password for source site"

Regards,
Michal

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by zvoltejinylogin** [comment]
Hello, this is similar to this - https://github.com/MicrosoftDocs/office-docs-powershell/issues/1783 

See my response to authenticate against a tenant that uses MFA, if you use MFA in on-prem scenario, I bet the resolution will be the same, you can't use credentials but have to sign-in via UX.

**Comment by get-itips** [comment]
Hello @micholus 
As @zvoltejinylogin referenced other article where @JoanneHendrickson explained that you have to sign-in via an UX, it's the only supported way.
Thank you

**Comment by get-itips** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/pull/4381

**Comment by yogkumgit** [comment]
@get-itips  thanks for your effort. @JoanneHendrickson  Thank you very much for the contribution and updating the documentation with PR. @micholus Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
