### ISSUE TITLE
DelegatedOrganization is not working?

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/office-docs-powershell#4372]
Connecting to delegated organization parameter is not working, please check with product group and update this documentation accordingly.

Usage example:
`Connect-ExchangeOnline -UserPrincipalName myusername@partnercorp.com -DelegatedOrganization endcustomer.onmicrosoft.com`

It connects to partnercorp.com tenant / current user tenant, and not the delegated organization.

ExchangeOnlineManagement - version 0.3374.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28f6554b-4d67-06d3-7926-1b958653872f
* Version Independent ID: 7a6a1737-afdf-dfd5-67f8-64aa6758ccc4
* Content: [Connect-ExchangeOnline (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/connect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @hkusulja, thank you for your feedback.

V2 module is on preview. Please to provide any feedback about it send an email to this address:
exocmdletpreview@service.microsoft.com

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @hkusulja 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by hkusulja** [comment]
@yogkumgit  - Yes, I have recieved email from the team and they say they will update the docs (or you?) , but currently docs are not correct. Please reopen this and fix it

**Comment by dariomws306** [comment]
Hi @hkusulja,

If you got a reply from the product team, please wait some days so they can take care of it. We cannot update the document.

Thank you!
