### ISSUE TITLE
-MembershipType not available

### ISSUE THREAD

**Issue by TeodoraI** [MicrosoftDocs/office-docs-powershell#4374]
Hi, in my tenant I have private teams and I want to select them by using the MembershipType argument. I installed the last version of MicrosoftTeams PowerShell module, however, I still don't have the option to use the MembershipType argument. Could you give information in which version of the PowerShell module it will be released and when it is expected to be released?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b48c32-ad79-4249-638b-f53f9d76397f
* Version Independent ID: 36d9cfe0-cf60-2fa1-41b4-6c6971042394
* Content: [Get-TeamChannel (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/Get-TeamChannel?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @TeodoraI I am looking into this, trying to contact the Product Team.

**Comment by jimcantor** [comment]
I'm also interested in this - its a showstopper for me because I have 400+ private channels to create

**Comment by kenwith** [comment]
The functionality is available in the test gallery however I don't have information on when it will be released in the main gallery. The latest release in the main gallery is 1.0.3 and it wasn't included in that release. Using the features from the test gallery is documented by @LanaChin here: https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management
