### ISSUE TITLE
In correct information in this article

### ISSUE THREAD

**Issue by Cloudmaister** [MicrosoftDocs/office-docs-powershell#4376]
The statement in purple above "Permission levels are defined by SharePoint Online administrators in the SharePoint Online Administration Center"  is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4992d050-ba30-54b6-7970-4e66ff3995c3
* Version Independent ID: ddc48376-3cb1-5491-7685-9ccc44be9f60
* Content: [New-SPOSiteGroup (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/new-spositegroup?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/New-SPOSiteGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/New-SPOSiteGroup.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Cloudmaister thanks for your feedback.
I created a pull request to propose improving that sentence, if it gets approved, an updated version of the article will be published.
Thanks

**Comment by yogkumgit** [comment]
@trent-green Please merge the PR #4395

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Cloudmaister Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
