### ISSUE TITLE
These instructions are crap.

### ISSUE THREAD

**Issue by biffbolt** [MicrosoftDocs/office-docs-powershell#4384]
The instructions involving Exchange Online do a great job - if your goal is to assign Read permissions to O365 accounts to another O365 account.  Now where are the instructions how to do the same for the on-prem accounts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @biffbolt, thank you for your feedback.

Could you please elaborate in more detail?

This article explains how you can connect to Exchange Online without MFA. If you want to connect/open Exchange Management Shell (on-premises):
https://docs.microsoft.com/powershell/exchange/exchange-server/connect-to-exchange-servers-using-remote-powershell

Or if you have the module installed in the server/workstation you can click on the icon.

**Comment by biffbolt** [comment]
The problem is not with the connection to Exchange Online. Quite the opposite. The instructions explicitly claim to assist the user in running some commands on the *on-premise* Exchange server, and then instead connect the user to Exchange Online and attempt to run the commands there instead.

Fundamentally the syntax of the main commands worked for me, once I figured out that I needed to run them in the local Exchange Management Shell instead and ignore the stuff about connecting to Exhange Online. Given that these are the instructions that Microsoft's documentation pushes out for an O365 migration, however, the error is a dumb one.

Cheers,
James

403-993-7817

________________________________

**Comment by dariomws306** [comment]
This article doesn't mention Exchange On-premises neither Exchange Management Shell.

It states: "On your local computer, open Windows PowerShell and run the following command."

So, probably you will open Windows PowerShell in your computer to access Exchange Online PowerShell, but you can also open it on an Exchange server if you want.
But you don't need to use Exchange Management Shell.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @biffbolt 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
