### ISSUE TITLE
New AcceptGatewayPAIForOutboundCalls  parameter is missing

### ISSUE THREAD

**Issue by bament-hun** [MicrosoftDocs/office-docs-powershell#4386]
Recently we have introduced the following Parameter for trunk configuration:
https://support.microsoft.com/en-us/help/4458692/incorrect-caller-id-shown-on-the-skype-for-business-client-in-a-call
After you apply this update, you have to set the AcceptGatewayPAIForOutboundCalls parameter (this value is false by default) to true to display forwarded number for different trunks. For example:

Set-CsTrunkConfiguration -Identity site:Redmond -AcceptGatewayPAIForOutboundCalls $True

This example modifies a trunk configuration with the Identity site:Redmond to enable the AcceptGatewayPAIForOutboundCalls. The remaining properties for this configuration will keep their existing values.

Please add this parameter also to the webpage, this is available in SfB Server 2015 and 2019 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80f4d755-24e9-d29e-c18e-f380f51835bb
* Version Independent ID: 391c3e3e-146a-501c-1866-569b65c0a754
* Content: [Set-CsTrunkConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cstrunkconfiguration?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsTrunkConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTrunkConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @bament-hun 
Thanks for reporting this. I created a pull request to propose adding this information to the article.
Thank you

**Comment by yogkumgit** [comment]
@hirenshah1 Please merge this PR #4417

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @bament-hun Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
