### ISSUE TITLE
SPO Authentication using App credentials 

### ISSUE THREAD

**Issue by nordtorp** [MicrosoftDocs/office-docs-powershell#4393]
Given your own recommendations to data migration I'm missing the AAD App Credential Authentication to SharePoint online - or have I missed something?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @nordtorp 
To better reply your inquiry I need to know which article are you talking about, do you refer to [Connect-SPOService](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps) cmdlet article?

Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @nordtorp We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
