### ISSUE TITLE
please add a related link

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/office-docs-powershell#4394]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: f68366d5-3aa9-70bb-2da7-8436e8f3cc96
* Version Independent ID: c1f3a26f-09df-0c5d-8e8f-53ce38aca2a8
* Content: [Set-AntiPhishPolicy (exchange)](https://docs.microsoft.com/pl-pl/powershell/module/exchange/advanced-threat-protection/set-antiphishpolicy?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Set-AntiPhishPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@VLG17  Thank you very much for the contribution and updating the documentation with PR. @rafalfitt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
