### ISSUE TITLE
Updating Team Members with Azure AD DL

### ISSUE THREAD

**Issue by krisrajzlive** [MicrosoftDocs/office-docs-powershell#4396]
Is it possible that I can turn on/off to sync the member list with Azure AD Distribution List?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c88db6-7b57-7c5d-264b-ad7b765d2287
* Version Independent ID: c678b927-9100-b4ee-0039-86e37f28d0db
* Content: [Set-TeamMemberSettings (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/Set-TeamMemberSettings?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Set-TeamMemberSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-TeamMemberSettings.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @krisrajzlive 
Thanks for your feedback. 
Set-TeamMemberSettings has been deprecated and replaced by Set-Team, besides that, I don't think that is possible, for feature requests, I invite you to visit https://microsoftteams.uservoice.com/
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @krisrajzlive 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
