### ISSUE TITLE
Missing ability to connect to EXO with serviceprincipal 

### ISSUE THREAD

**Issue by jopgommans** [MicrosoftDocs/office-docs-powershell#4399]
As legacy authentication for Exchange Online will be unusable nearing the end of next year we need to have a way to authenticate to EXO using a service principal the way Azure/MSOL already support. Can this be added in?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by VLG17** [comment]
@jopgommans Which article are you reffering to? Could you please link it?

**Comment by yogkumgit** [comment]
@jopgommans We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
