### ISSUE TITLE
Trick to add Header node

### ISSUE THREAD

**Issue by krishnachaluvadi** [MicrosoftDocs/office-docs-powershell#4400]
Hi, If anyone wants to add a "Header" type node to the navigation, use the below syntax.
Add-PnPNavigationNode -Location TopNavigationBar -Title "your node name" -Url "http://linkless.header"
The above cmdlet adds a node with type, "Header", otherwise, it adds a node of type "Link" and defaults to current site url. Hope it helps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce02f005-8ecf-69cf-6d4d-49d325056725
* Version Independent ID: eaf106fc-2d67-d98d-b276-e17045277b55
* Content: [Add-PnPNavigationNode (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpnavigationnode?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPNavigationNode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPNavigationNode.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @krishnachaluvadi thanks for your feedback!

As you might know, PnP cmdlets are open source and maintained by the community, if you want, you can request that example be added to the documentation, creating a pull request [here](https://github.com/SharePoint/PnP-PowerShell/blob/dev/Commands/Navigation/AddNavigationNode.cs) or you can open an issue in that repo with the same information you posted here so a member of the community picks it up.

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @krishnachaluvadi 
These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
