### ISSUE TITLE
Descriptions swapped

### ISSUE THREAD

**Issue by grahamcropley** [MicrosoftDocs/office-docs-powershell#4407]
The description for the EmergencyDialString and the EmergencyDialMask parameters are the wrong way around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccb12d7a-24b0-fe77-c228-bdca8f9c4eb2
* Version Independent ID: d3f4a454-b6b6-2396-f52c-523512b23105
* Content: [New-CsTeamsEmergencyNumber (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencynumber?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsTeamsEmergencyNumber.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsEmergencyNumber.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @danny-levin
* Microsoft Alias: **dannyle**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @grahamcropley thanks for noticing and reporting, I see that a community member has created a PR to correct the article, I reviewed and once it gets approved it will be in the published version of the article.

**Comment by yogkumgit** [comment]
@danny-levin  Please merge the PR #4422
