### ISSUE TITLE
Error in sample code

### ISSUE THREAD

**Issue by ChebotovViktor** [MicrosoftDocs/office-docs-powershell#4409]
if run MOSS 2019 EE:

```
if ((Get-PSSnapin 'Microsoft.SharePoint.PowerShell' -ErrorAction SilentlyContinue) -eq $null) {
    Add-PSSnapin 'Microsoft.SharePoint.PowerShell'
}
Clear-Host

$proxy = Get-SPServiceApplicationProxy | ?{$_.TypeName -eq 'User Profile Service Application Proxy'}
$security = Get-SPProfileServiceApplicationSecurity -ProfileServiceApplicationProxy $proxy
$everyone = New-SPClaimsPrincipal -Identity 'c:0(.s|true' -IdentityType EncodedClaim
Revoke-SPObjectSecurity -Identity $security -Principal $everyone -Rights 'Create Personal Site'
Set-SPProfileServiceApplicationSecurity -Identity $security -ProfileServiceApplicationProxy $proxy
```

```
Error^ Revoke-SPObjectSecurity : The specified user or domain group was not found.
At C:\Work\UserProfilePremissions\UserProfilePremissions07.ps1:9 char:1
+ Revoke-SPObjectSecurity -Identity $security -Principal $everyone -Rig ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...eObjectSecurity:SPCmdletRevokeObjectSecurity) [Revoke-SPObjectSecurity], SPException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletRevokeObjectSecurity
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e39560d-4312-1e65-c7a1-49eb2ef07bd6
* Version Independent ID: f0d4b39e-efc9-b5fe-f469-ec7f3db8f56e
* Content: [Set-SPProfileServiceApplicationSecurity (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spprofileserviceapplicationsecurity?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPProfileServiceApplicationSecurity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPProfileServiceApplicationSecurity.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
There isn't an error. This works fine given the claim has been previously added. In your case, it means the group wasn't assigned rights on the UPSA prior to running the cmdlet.

**Comment by get-itips** [comment]
Hello @ChebotovViktor 
Please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/4410

**Comment by yogkumgit** [comment]
@tseward Please review the PR #4430

**Comment by yogkumgit** [comment]
@kenwith Please merge this PR #4430 . Thanks.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ChebotovViktor Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
