### ISSUE TITLE
MOSS 2019 EE: Correctly working sample code

### ISSUE THREAD

**Issue by ChebotovViktor** [MicrosoftDocs/office-docs-powershell#4410]
```
$proxy = Get-SPServiceApplicationProxy | Where-Object {$_.TypeName -eq 'User Profile Service Application Proxy'}
$identity = Get-SPProfileServiceApplicationSecurity -ProfileServiceApplicationProxy $proxy.Id -Type UserACL


#Create a claims identity
$Principal = New-SPClaimsPrincipal -Identity "contoso\admSp" -IdentityType WindowsSecurityGroupName


#Grant Permission To the Principal to a Defined Right

######## Check the box: Follow People and Edit Profile
Grant-SPObjectSecurity -Identity $identity -Principal $Principal -Rights "Use Personal Features"
######## Check the box: Create Personal Site (required for personal storage, newsfeed, and followed content) 
Grant-SPObjectSecurity -Identity $identity -Principal $Principal -Rights "Create Personal Site"
######## Check the box: Use Tags and Notes
Grant-SPObjectSecurity -Identity $identity -Principal $Principal -Rights "Use Social Features"
######## Check the box: Disable OneDrive
#Grant-SPObjectSecurity -Identity $identity -Principal $Principal -Rights "Block Default Doclib Access"

#Set the permission on the user profile service FINALLY
Set-SPProfileServiceApplicationSecurity -ProfileServiceApplicationProxy $proxy.id -Type UserACL -Identity $identity -Confirm:$false
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e39560d-4312-1e65-c7a1-49eb2ef07bd6
* Version Independent ID: f0d4b39e-efc9-b5fe-f469-ec7f3db8f56e
* Content: [Set-SPProfileServiceApplicationSecurity (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spprofileserviceapplicationsecurity?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPProfileServiceApplicationSecurity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPProfileServiceApplicationSecurity.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
This could be cleaned up and added as a second example. To keep in line with the existing example:

```
$proxy = Get-SPServiceApplicationProxy | ?{$_.TypeName -eq 'User Profile Service Application Proxy'}
$security = Get-SPProfileServiceApplicationSecurity -ProfileServiceApplicationProxy $proxy
$everyone = New-SPClaimsPrincipal -Identity 'c:0(.s|true' -IdentityType EncodedClaim
Grant-SPObjectSecurity -Identity $security -Principal $everyone -Rights 'All'
Set-SPProfileServiceApplicationSecurity -Identity $security -ProfileServiceApplicationProxy $proxy
```

**Comment by get-itips** [comment]
Hello @tseward I am adding your example to the article thru a pr.
@ChebotovViktor hope this information clarifies your scenario.

**Comment by yogkumgit** [comment]
@tseward Please review the PR#4430

**Comment by yogkumgit** [comment]
@get-itips get Thank you very much for the contribution and updating the documentation with PR. @ChebotovViktor Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
