### ISSUE TITLE
Please update this article

### ISSUE THREAD

**Issue by DynamitePLF** [MicrosoftDocs/office-docs-powershell#4411]
Add a note about CAS Role only servers not responding properly, because they Proxy to MBX role.  CAS Role servers throw an obscure error "There are no Microsoft Exchange 2007 server roles installed" which is pointless to all Admins (rabbit hole error).

Please provide a link to validate CAS Role only servers using: Get-Services MSEX*
Link:  https://social.technet.microsoft.com/Forums/exchange/en-US/c1e40b84-6d85-4f32-b202-d880b89bd7a3/strange-behaviour-testservicehealth-and-exchange-server-2013?forum=exchangesvrgeneral

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed853f0-84a5-d959-9acc-465888cf19cc
* Version Independent ID: 57c7ffb5-cd83-4dfc-60eb-797210fd6ac3
* Content: [Test-ServiceHealth (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/server-health-and-performance/test-servicehealth?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/server-health-and-performance/Test-ServiceHealth.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/server-health-and-performance/Test-ServiceHealth.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4473 . Thanks

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @DynamitePLF Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
