### ISSUE TITLE
Is the policy active without a rule?

### ISSUE THREAD

**Issue by cabtilx** [MicrosoftDocs/office-docs-powershell#4412]
Creating a policy through the GUI automatically creates an associated rule. If using PowerShell to create the policy is it automatically applied to all recipients? There appears to be no documentation on the Set-HostedOutboundSpamFilterRule cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465aff8b-94d1-258b-0558-a35f2261fc0b
* Version Independent ID: 3b7917f1-4d63-e881-5653-4fc4ac84038a
* Content: [Set-HostedOutboundSpamFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/Set-HostedOutboundSpamFilterPolicy?redirectedfrom=MSDN&view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedOutboundSpamFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedOutboundSpamFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@cabtilx Thank you for your feedback. If the policy is created via Powershell it is applied to all recipients.  The attributes available on the set-HostedOutboundSpamFilterRule are minimal as mentioned below and the admins cannot use the PS cmdlet to change the "applied to" parameter as it is not available yet.

[-Identity] <HostedOutboundSpamFilterPolicyIdParameter>
   [-AdminDisplayName <String>]
   [-BccSuspiciousOutboundAdditionalRecipients <MultiValuedProperty>]
   [-BccSuspiciousOutboundMail <Boolean>]
   [-Confirm]
   [-NotifyOutboundSpam <Boolean>]
   [-NotifyOutboundSpamRecipients <MultiValuedProperty>]
   [-WhatIf]
   [<CommonParameters>]

So if the policy needs to be applied to a set of users or groups, then GUI is the only way at the moment. Once all the parameters are included for the cmdlet, you will see an update in the document.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @cabtilx 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Please keep contributing with your suggestions to improve the documentation.

**Comment by cabtilx** [comment]
Hello Sri,

The set-HostedOutboundSpamFilterRule has much more parameters available. It accepts parameters to set the 'From' & 'FromMemberOf' values (although I can't get the 'SenderDomainIs' to work).
The bigger problem is that the GUI will accept any free-text values for the 'FromMemberOf' group and on save the webpage creates a policy but does not create the rule if the group does not exist, causing the policy to be a) applied to everyone and b) not visible in the portal, needing to be removed via PowerShell.

This error/lack of validating sender or group is potentially very dangerous as in our case it created an invisible policy, applied to all staff & started to restrict outbound mail. We were only able to see & remove the policy via PowerShell.

get-help set-HostedOutboundSpamFilterRule
SYNTAX
    Set-HostedOutboundSpamFilterRule [-Identity] <RuleIdParameter> [-From <RecipientIdParameter[]>] [-FromMemberOf <RecipientIdParameter[]>] [-SenderDomainIs <Word[]>] [-ExceptIfFrom <RecipientIdParameter[]>] [-ExceptIfFromMemberOf <RecipientIdParameter[]>] [-ExceptIfSenderDomainIs <Word[]>] [-HostedOutboundSpamFilterPolicy <HostedOutboundSpamFilterPolicyIdParameter>] [-Name <string>] [-Priority <int>] [-Comments <string>] [-DomainController <Fqdn>] [-ProxyToMailbox <MailboxIdParameter>] [-ProxyToServer <string>] [-WhatIf] [-Confirm]  [<CommonParameters>]

Thank you,
Matt

**Comment by chrisda** [comment]
For the record, we are in the process of getting the new *-HostedOutboundSpamFilterRule cmdlets and the corresponding new features in the *-HostedOutboundSpamFilterPolicy cmdlets documented. They should be available soon

**Comment by yogkumgit** [comment]
@chrisda Thanks for this information.
