### ISSUE TITLE
How do I get access to the Private Preview version, so i can use -MembershipType and -Owner?

### ISSUE THREAD

**Issue by jimcantor** [MicrosoftDocs/office-docs-powershell#4414]
How do I get access to the Private Preview version, so i can use -MembershipType and -Owner?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd44b411-4b59-b90f-0b82-ad0a87652854
* Version Independent ID: 2c52cc4e-47a1-be0d-8860-1011adf061fd
* Content: [New-TeamChannel (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/New-TeamChannel?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/New-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@jimcantor - I believe @LanaChin has documented the process here: https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management

**Comment by jimcantor** [comment]
thanks!  wonderful news


Regards, Jim Cantor
jim.cantor@interaage.com.au
0414 593 723

**Comment by jimcantor** [comment]
.
