### ISSUE TITLE
Confirmation of Set-SPOSite command limitation for the group site collection

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/office-docs-powershell#4418]
The group site collection, which associated with Office 365 group, is not allowed to change **some** site-level properties using by Set-SPOSite command.
Ref: [#1555](https://github.com/MicrosoftDocs/office-docs-powershell/issues/1555), [#2695](https://github.com/MicrosoftDocs/office-docs-powershell/issues/2695)

But, if we use the CSOM (Client Side Object Model), we can change all of the site-level properties.

Ex.
・Site.DisableAppViews property
 ・Site.DisableFlows property

Q1. Is the Set-SPOSite command limitation just command limitation for group sitecollection?

Q2. If just command limitation, is it supported operation to use CSOM to change site-level properties that cannot be changed with the Set-SPOSite command for group site collection?

Thanks!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@kefujino Thank you for the feedback. You are correct, As we mentioned in the other two issues( #1555 and #2695) this is a command limitation for a group site collection. Alternatively, you can use CSOM to change properties that cannot be changed with other commands for a group site collection.

It is very well supported to use the SharePoint client object model (CSOM) to retrieve, update, and manage data in SharePoint. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @kefujino 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by kefujino** [comment]
@msbemba
Thank you for your quick answer!!
Very helpful for me.

@yogkumgit
Thank you!
