### ISSUE TITLE
Document "Connect to Exchange Online PowerShell" will be expired after October 13th, 2020?

### ISSUE THREAD

**Issue by Justin-Shi** [MicrosoftDocs/office-docs-powershell#4419]
Hi Team, 

From this [announcement](https://developer.microsoft.com/en-us/office/blogs/end-of-support-for-basic-authentication-access-to-exchange-online-apis-for-office-365-customers/), the basic authentication for Remote Power shell in Exchange online will be retired at October 13th, 2020. Does that means the document "[Connect to Exchange Online PowerShell"](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps) will be expired?
If so, is it possible to add this into the document in case someone relay on this but does not noticed the announcement.

Thanks
-Justin

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@Justin-Shi Thank you for your feedback. We have added a note to the doc via PR https://github.com/MicrosoftDocs/office-docs-powershell/pull/4427

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @Justin-Shi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
