### ISSUE TITLE
Example is incorrect

### ISSUE THREAD

**Issue by damianscoles** [MicrosoftDocs/office-docs-powershell#4420]
The explanation of the example provided for this cmdlet is incorrect.  The example shows the variable $UserCredential which is used to get credentials to connect to Exchange Online.  However, the explanation uses the wrong variable name (twice!):  "The first command gets the user credentials and stores them in the $Credential variable." and "The second command connects the current PowerShell session using the credentials in the $Credential." Please fix this to make it the variable name consistent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28f6554b-4d67-06d3-7926-1b958653872f
* Version Independent ID: 7a6a1737-afdf-dfd5-67f8-64aa6758ccc4
* Content: [Connect-ExchangeOnline (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/connect-exchangeonline?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@damianscoles Thank you for your feedback. We have made changes to the doc via PR https://github.com/MicrosoftDocs/office-docs-powershell/pull/4426 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @damianscoles Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
