### ISSUE TITLE
Please add -IncludeID to Import-PnPTaxonomy

### ISSUE THREAD

**Issue by CTMSASnowfox** [MicrosoftDocs/office-docs-powershell#4423]
We have an usecase where we develop and customize managed metadata and application functionality is bound to GUIDs on the terms. When moving between development and production tenant we need to be able to replicate the entire taxonomy including the GUIDs. However we can export the taxonomy in its entirety including GUIDs (https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/export-pnptaxonomy?view=sharepoint-ps) but not apply the same GUIDs when importing. 
Would it be possible that to add the -IncludeID option to import-pnptaxonomy ?

Thank you in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36c52515-b901-5928-cbe1-641b0c21f975
* Version Independent ID: 700c3b55-3841-f8fc-3fc1-5dad4b6dc7be
* Content: [Import-PnPTaxonomy (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/import-pnptaxonomy?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Import-PnPTaxonomy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Import-PnPTaxonomy.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @CTMSASnowfox 
I need to kindly ask you to post that suggestion in [this repo](https://github.com/SharePoint/PnP-PowerShell/), as you might know, PnP cmdlets are open source and community-driven and maintained, a member of that community will pick up your request there.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @CTMSASnowfox 
These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
