### ISSUE TITLE
Incorrect description of required admin roles to run the cmdlet

### ISSUE THREAD

**Issue by steven-de-bruyne** [MicrosoftDocs/office-docs-powershell#4424]
I believe the sentence "You must be a SharePoint Online global administrator and a site collection administrator to run the cmdlet." is incorrect. 
You are either a "SharePoint Admin" or a "Global Admin".
See Admin Roles documentation: https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide
Also, a site collection administrator is specific to a given site collection and does not apply to deleted sites, nor does it apply to any SPO cmdlets. As an example: It is not because a user was site collection administrator for a given site before it was deleted, that this user will be able to run any SPO cmdlets for that site as you need to be a sharepoint admin or global admin to be able to connect to the admin center site (tenant_name-admin.sharepoint.com).

So, a correct formulation would be:
**"You must be a SharePoint Admin or Global Admin to run the cmdlet."**

I've seen other places in the documentation that use the same sentence, so depending on the outcome of this issue, I can make corrections to the other pages as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af2a878-cf06-c990-d538-aebf00f2a35d
* Version Independent ID: b19b5db8-33da-1ac6-1348-28cc58aef08b
* Content: [Remove-SPODeletedSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spodeletedsite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODeletedSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODeletedSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@steven-de-bruyne Thank you for your feedback. We have made changes to the doc via PR https://github.com/MicrosoftDocs/office-docs-powershell/pull/4447

Thanks
Sri

**Comment by yogkumgit** [comment]
@trent-green Please merge this PR #4447

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @steven-de-bruyne Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
