### ISSUE TITLE
Use the Exchange Online PowerShell V2 module in Azure Automation Account with enabled MFA

### ISSUE THREAD

**Issue by joanabdo** [MicrosoftDocs/office-docs-powershell#4425]
Could you please clarify, how can we use this command in Azure Automation Account?
MFA is enabled for all users

BR,
Joan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by zeroeagle1** [comment]
if possible in a non-interactive way (for backend application)

**Comment by dariomws306** [comment]
Hi @joanabdo, thank you for your feedback.

This module is still in preview so I think MFA is not supported yet. Please provide any feedback about this module to exocmdletpreview@service.microsoft.com.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @joanabdo 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by joanabdo** [comment]
Hi @dariomws306, thanks for your reply, I am gonna send feedback to  exocmdletpreview@service.microsoft.com, regarding my issue
