### ISSUE TITLE
"created by a Timer Job later"

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/office-docs-powershell#4429]
Any way to see that Timer?  Or bypass it?  Show status?  We really can't be waiting 24 hours before determining if commands worked or not.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f61076b-1d49-4f87-b400-fff52d067ea8
* Version Independent ID: 8173ce51-c1ef-50be-2069-1ccd3d0ab5b3
* Content: [Request-SPOPersonalSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/request-spopersonalsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@Canis-Lupis Thank you for your feedback. Unfortunately, It's not possible to configure (change schedule, trigger, Bypass, etc.) timer jobs in SharePoint Online.

However, if need be, you can find out when it last ran using the properties dlc_PolicyUpdateLastRun
and dlc_ExpirationLastRun by accessing SharePoint Online site collection in SharePoint Designer 2013 by going to Site Options. So you can deduce when it is likely to run next.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @Canis-Lupis 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
