### ISSUE TITLE
I really hope this command supports Teams App Setup Policy in the future.  

### ISSUE THREAD

**Issue by erictechtips** [MicrosoftDocs/office-docs-powershell#4433]
It would be nice if this command worked for Teams App Setup Policies.  https://docs.microsoft.com/en-us/MicrosoftTeams/teams-app-setup-policies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f8afd4c-7828-e7e7-dddc-e14673396f39
* Version Independent ID: dabb388b-8614-4b69-4e0a-f0536ab2bab6
* Content: [New-CsGroupPolicyAssignment (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csgrouppolicyassignment?view=teams-ps&source=docs#feedback)
* Content Source: [teams/teams-ps/teams/New-CsGroupPolicyAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsGroupPolicyAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @erictechtips thanks for your feedback.
I need to kindly redirect your suggestion [here](https://microsoftteams.uservoice.com/) that way, will reach the product team and they will hear your idea.
Thank you

**Comment by yogkumgit** [comment]
@erictechtips  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
