### ISSUE TITLE
Is there any way we can update channel visibility using powershell?

### ISSUE THREAD

**Issue by lovethakker02** [MicrosoftDocs/office-docs-powershell#4435]
In New-TeamChannel, if we don't pass membership, sometimes it is creating channel in hidden mode. There is no documentation if we can update that to make it visible to every one. 

Can you please provide details on it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2350a428-0934-b5bb-46fc-3fb30a0578ec
* Version Independent ID: 0274f5da-6af1-57e6-4889-b318f1589477
* Content: [Set-TeamChannel (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/set-teamchannel?view=teams-ps&source=docs#feedback)
* Content Source: [teams/teams-ps/teams/Set-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @lovethakker02 
Thanks for your feedback.
As you might know, these cmdlets currently belong to the beta module, so they are subject to change, the Product Team is probably working on a complete version of the cmdlet.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @lovethakker02 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
