### ISSUE TITLE
RecordType out-of-date

### ISSUE THREAD

**Issue by danieljohansso** [MicrosoftDocs/office-docs-powershell#4436]
RecordType list does not seem to be updated. 

For example using the Search-UnifiedAuditLog command I was able to get records with the record type 'PowerAppsApp' and 'SharePointFieldOperation'. I'm sure there are more that are missing. Also is any of the RecordTypes not being used anymore?

Would be great if you could keep it up-to-date. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d47105-b32e-f0f8-3e71-db411c6abe7c
* Version Independent ID: 338beb1b-1f13-0a77-9ac3-1c4fe542b612
* Content: [Search-UnifiedAuditLog (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/search-unifiedauditlog?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by saimonesh** [comment]
The search-unifiedauditlog seems to have many parameters but description for these parameters were not update like -longerretentionenabled ,-asjob etc.Also please update all the record types

**Comment by msbemba** [comment]
@danieljohansso and @saimonesh Thank you for the feedback. We have added missing record types and the parameter -Asjob to the doc via PR# https://github.com/MicrosoftDocs/office-docs-powershell/pull/4461

@saimonesh The -LongerRetentionEnabled parameter is not documented as it is still in preview for a  few subscriptions as they allow only 90 days retention and a few allow 365 days. This parameter will be documented when it's publicly available for everyone.

Hope this helps!Thanks again for making our docs look better.

Thanks
Sri

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4461 . Thanks.

**Comment by Nazul** [comment]
It is still out of date. Forms was added and it is not listed yet. Stream and Power Apps are not there.

**Comment by msbemba** [comment]
@Nazul  The author has not merged the PR yet. Once it is merged it could take 48 hours to reflect in the live document.

**Comment by danieljohansso** [comment]
Looking at the commit @msbemba, user @Nazul seems to be half correct and half wrong.

https://github.com/msbemba/office-docs-powershell/commit/9e3120be6d7a2084e2757989c253db8a6729a2a8#diff-7ee14ca78ddbff96089432687a985136

I can see that PowerApps* and MicrosoftStream is added but not for example MicrosoftForms. 

I also noticed again that a lot of Record Types are still missing. Using PowerShell I was able to get the following list:

`"ExchangeAdmin, ExchangeItem, ExchangeItemGroup, SharePoint, SyntheticProbe, SharePointFileOperation, OneDrive, AzureActiveDirectory, AzureActiveDirectoryAccountLogon, DataCenterSecurityCmdlet, ComplianceDLPSharePoint, Sway, ComplianceDLPExchange, SharePointSharingOperation, AzureActiveDirectoryStsLogon, SkypeForBusinessPSTNUsage, SkypeForBusinessUsersBlocked, SecurityComplianceCenterEOPCmdlet, ExchangeAggregatedOperation, PowerBIAudit, CRM, Yammer, SkypeForBusinessCmdlets, Discovery, MicrosoftTeams, ThreatIntelligence, MailSubmission, MicrosoftFlow, AeD, MicrosoftStream, ComplianceDLPSharePointClassification, ThreatFinder, Project, SharePointListOperation, SharePointCommentOperation, DataGovernance, Kaizala, SecurityComplianceAlerts, ThreatIntelligenceUrl, SecurityComplianceInsights, MIPLabel, WorkplaceAnalytics, PowerAppsApp, PowerAppsPlan, ThreatIntelligenceAtpContent, LabelExplorer, TeamsHealthcare, ExchangeItemAggregated, HygieneEvent, DataInsightsRestApiAudit, InformationBarrierPolicyApplication, SharePointListItemOperation, SharePointContentTypeOperation, SharePointFieldOperation, MicrosoftTeamsAdmin, HRSignal, MicrosoftTeamsDevice, Microso
ftTeamsAnalytics, InformationWorkerProtection, Campaign, DLPEndpoint, AirInvestigation, Quarantine, MicrosoftForms, ApplicationAudit, ComplianceSupervisionExchange, CustomerKeyServiceEncryption, OfficeNative, MipAutoLabelSharePointItem, MipAutoLabelSharePointPolicyLocation"`

Many of the commands seems to be missing from the list, for example AirInvestigation. Also I was reached by an error when trying to get Record Types for 'MicrosoftTeamsAddOns' as it wasn't able to find that as a valid enumerator.

**Comment by msbemba** [comment]
@danieljohansso Thank you for the feedback. I have added the missed out items for record type on PR# https://github.com/MicrosoftDocs/office-docs-powershell/pull/4461 . Once the PR is merged, the document will be updated with live in 24-48 hours

Thanks again for helping Microsoft Docs look better.
Sriram

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @danieljohansso Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
