### ISSUE TITLE
Where are the logs saved to?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/office-docs-powershell#4437]
Hello,
I am re-opening this question that I had asked previously.  To recap, I'm asking where the log files are stored when you use -LogOnly and -LogLevel.  @dariomws306  responded that -TargetFolder and -TargetMailbox parameters are mandatory when you use -LogLevel or -LogOnly, so my feedback was closed.

This may be true, however, this has nothing to do with logging.  -TargetFolder and -TargetMailbox are where you are copying mail from one mailbox to another.  The description for both commands do not mention anything about logs much less where they are saved.  For that matter, neither do the descriptions for -LogLevel or -LogOnly.

It may be that logs are saved to -TargetFolder in -TargetMailbox.  If this is true, then I feel this needs to be added to this documentation.  Also, if true, what happens to the logs if there is an issue and -TargetFolder never gets created?  As I mentioned in my previous post, I ran Search-Mailbox with no errors, but no mail was copied in the TargetMailbox and no TargetFolder was created.  Since PowerShell isn't giving me an error, I want to check the logs to see what the problem is, put I cannot find them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c6c666-7221-7984-82a5-d731fee0ac3d
* Version Independent ID: 6970ac1a-0aaa-c625-24db-e3db2296b6f8
* Content: [Search-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/search-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Canis-Lupis, it's true, thank you to open a new issue about this.

I'm adding next sentence to the description of -LogLevel parameter:
"When you included this parameter, an email message is created and sent to the mailbox specified by the TargetMailbox parameter. The log file (which is a CSV-formatted file named Search Results.csv) is attached to this email message, and will be located in the folder specified by the TargetFolder parameter. The log file contains a row for each message that's included in the search results when you run the Search-Mailbox cmdlet."

Also, if the TargetFolder cannot be created you will get an error message in the PowerShell window/session.

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4445

**Comment by Canis-Lupis** [comment]
@dariomws306, thanks I think that would be very helpful.  However, as I mentioned,  "I ran Search-Mailbox with no errors, but no mail was copied in the TargetMailbox and no TargetFolder was created. [Since] PowerShell isn't giving me an error...."  

Personally, I don't think log files should be saved in the -TargetFolder.  If you are an admin copying mail from employee A's mailbox to employee B's mailbox, there are corporate privacy policies to consider, so many of us aren't allowed to go looking in mailboxes for log files. I know this has nothing to do with documentation, but perhaps you could pass on a suggestion to whomever that any generated logs should be saved locally, on the computer running the PowerShell command?

**Comment by dariomws306** [comment]
Hi @Canis-Lupis,

The best place to request new features or product updates is:
https://office365.uservoice.com/

Please check if your idea was posted before so you can vote it and to avoid create duplicates.

Thank you!

**Comment by yogkumgit** [comment]
@Canis-Lupis  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
