### ISSUE TITLE
This commandlet is not available in current release

### ISSUE THREAD

**Issue by BrianTJackett** [MicrosoftDocs/office-docs-powershell#4440]
This commandlet for Connect-PnPMicrosoftGraph does not appear to be exported (usable) in the 3.15.1911.0 version of the module.  Has it been replaced by functionality in the Connect-PnPOnline commandlet?  If so (which appears to be the case) please update this article with the version when that change took place and guidance on usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9573bc8c-fba0-3eaf-db73-627140d49883
* Version Independent ID: 668fa277-d259-c6b5-161f-22738bea4a40
* Content: [Connect-PnPMicrosoftGraph (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnpmicrosoftgraph?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPMicrosoftGraph.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPMicrosoftGraph.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @BrianTJackett 
I need to kindly ask you to post that issue in [this repo](https://github.com/SharePoint/PnP-PowerShell/), as you might know, PnP cmdlets are open source and community-driven and maintained, a member of that community will pick up your request there.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @BrianTJackett 
These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
