### ISSUE TITLE
SPO Site Group Membership

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#4441]
Hello,
It would be really handy to be able to add/remove users from SPO Site group with Set-SPOSiteGroup/Add-SPOSiteGroupMember/Remove-SPOSiteGroup

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @YuriySamorodov 

Thanks for your feedback. I'll need to kindly suggest to post that idea [here](https://sharepoint.uservoice.com/)  where it will reach the product team.
Thank you

**Comment by yogkumgit** [comment]
@YuriySamorodov  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
