### ISSUE TITLE
Errors on | select * -first 1

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/office-docs-powershell#4448]
![image](https://user-images.githubusercontent.com/5489996/69516508-7338fb00-0f17-11ea-825a-3c9486cabeba.png)

After connecting when I want to know all the properties inside by using:
```Powershell
Get-EXOMailbox | select * -First 1
```

Got an exception:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0d68f09-e821-5c48-e06d-21fda22243dc
* Version Independent ID: bf67e0fb-ea39-5c9d-4348-f46f815aec53
* Content: [Get-EXOMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/get-exomailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/powershell-v2-module/Get-EXOMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/powershell-v2-module/Get-EXOMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @j0rt3g4, thank you for your feedback.

Please in this case provide your feedback to exocmdletpreview@service.microsoft.com as Exchange PowerShell Module V2 is on preview and you cannot open a support case.
Docs.microsoft.com feedback is there to help to improve documentation.

Thank you!

**Comment by j0rt3g4** [comment]
Ok thank you
