### ISSUE TITLE
Cls default behaviour

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/office-docs-powershell#4449]
Since CU-123, this default appears to have change to just the local computer instead of all nodes in the pool/site/Topology "If you do not include the Computers parameter or the Pools parameter, the Start-CsClsLogging cmdlet will automatically run against all the computers in the topology."

This has basically rendered Jame's Centralized Clslogging script useless in a enterprise environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f9403f-9d29-ad24-8fe2-629938f836bd
* Version Independent ID: b9c6dd32-d183-7c02-2728-9f7550fbae7d
* Content: [Start-CsClsLogging (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/start-csclslogging?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Start-CsClsLogging.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Start-CsClsLogging.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Korbyn72 
Thanks for your feedback.
I could reproduce this behavior in my lab.
I will create a Pull Request to correct the article based on latest cu.
Thank you

**Comment by Korbyn72** [comment]
Ideally, i tgink we all would prefer the default behaviour change back.  I also notice a few of the defaults have changed too, 20 mins instead of 4 hours for how long it will run.

Korbyn Forsman
from Mobile device

________________________________

**Comment by get-itips** [comment]
@Korbyn72 I understand, but here, we are limited to changes in documentation. Please visit the [Skype For Business User Voice](https://www.skypefeedback.com/) to submit your suggestion.
Thank you

**Comment by hirenshah1** [comment]
@Korbyn72 you have mentioned CU-123, I guess this is a typo. Can you please tell which Server version CU you are referring to ?

**Comment by Korbyn72** [comment]
123 is the last 3 digits of the version numbers.  Cu1 isnt documented anywhere publically, so i call it cu-123. Cu-143 is the currently released cu for sfb2019, which is supposedly cu1 hf1, but again not publically documented.  The only real constant to use is the last digits.

Korbyn Forsman
from Mobile device

________________________________

**Comment by get-itips** [comment]
Hello @hirenshah1 just checking if you saw the reply by @Korbyn72 and if you can merge the PR.
Thank you

**Comment by get-itips** [comment]
PR is merged, @yogkumgit please close this thread. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Korbyn72 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
