### ISSUE TITLE
typo at AdditionalResponse parameter

### ISSUE THREAD

**Issue by hegedusgyorgy** [MicrosoftDocs/office-docs-powershell#4450]
In the explanation of the AdditionalResponse parameter the "value of the AdditionalResponse parameter is $true" should be corrected to "value of the **Add**AdditionalResponse parameter is $true".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a9c45b-34dd-c1c8-89f0-84f3d968eac4
* Version Independent ID: ec9c910c-25f2-f36a-8f75-ce052f0e8be6
* Content: [Set-CalendarProcessing (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-calendarprocessing?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@hegedusgyorgy Thank you for your feedback. We have made changes to the doc via PR # https://github.com/MicrosoftDocs/office-docs-powershell/pull/4460

Thanks
Sri

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4460 . Thanks.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @hegedusgyorgy Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
