### ISSUE TITLE
Missing "SkipDiomainVailidation" switches

### ISSUE THREAD

**Issue by PJNield** [MicrosoftDocs/office-docs-powershell#4451]
The folloiwing switches are missing from this cmdlet, which are present on "Add-RecipientPermission":
   [-SkipDomainValidationForMailContact]
   [-SkipDomainValidationForMailUser]
   [-SkipDomainValidationForSharedMailbox]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f40052d-5df1-0d97-4d15-5d7729674f99
* Version Independent ID: 035a874b-950b-f32e-41a6-6fafa46e972f
* Content: [Remove-RecipientPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/remove-recipientpermission?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Remove-RecipientPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Remove-RecipientPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by VLG17** [comment]
@PJNield i have tested and the "Skip" parameters are not available for "Remove-RecipientPermission". Did you test this and get a different result?

**Comment by PJNield** [comment]
HI,

Correct, the skip parameters are not available.

Either the "Remove-RecipientPermission" cmdlet needs to not perform the domain validation at all, or provide the option to skip the domain validation, like "Add-RecipientPermission" has.

**Comment by VLG17** [comment]
@PJNield I recommend posting this feedback [here](https://office365.uservoice.com/forums/273493-office-365-admin). 

This is something the Product Group needs to look into and change, and UserVoice for Office 365 is actively looked at by them for improvement ideas, exactlly like yours. 

Thank you for providing this feedback!

**Comment by yogkumgit** [comment]
@VLG17 Thank you very much for the contribution and sharing this explanation. @PJNield 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
