### ISSUE TITLE
How to use PowerShell to apply custom template?

### ISSUE THREAD

**Issue by 7angjinhao** [MicrosoftDocs/office-docs-powershell#4452]
Hi,
I want to know the whole process of creating sitecollection and applying custom template through PowerShell. And what commands are used.
Thanks

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @7angjinhao 
This issue system is intended to report issues in documentation, besides that, you can start looking [here](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview)
Hope this info helps you

**Comment by 7angjinhao** [comment]
@get-itips Thank you so much

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @7angjinhao 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
