### ISSUE TITLE
AllowFederatedParticipantJoinAsSameEnterprise needs clarification

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/office-docs-powershell#4453]
Please update this parameter as follows:

-AllowFederatedParticipantJoinAsSameEnterprise
PARAMVALUE: $true | $false

Indicates whether a federated user will be admitted into conference directly. The default value is False.
This setting applies to the user who organizes the conference: 
If set to False and AllowAnonymousParticipantsInMeetings is False, federated users will be treated as anonymous users and put into lobby.
If set to True and admission policy is openAuthenticated, federated users are treated as same company users and admitted into conference directly.
If set to True and admission policy is closedAuthenticated, we will also check against pre-set invitee list. If not found, federated users will be put into lobby. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb630b9-b94d-a647-ca21-821e1d520b21
* Version Independent ID: ede8297e-aa49-fc5e-23bb-2d678bc23e6b
* Content: [Set-CsConferencingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csconferencingpolicy?view=skype-ps&source=docs)
* Content Source: [skype/skype-ps/skype/Set-CsConferencingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsConferencingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @howardzhangmsft 
Thanks for noticing and taking the time to submit this feedback.
I created a pull request to improve the description of the parameter based on your suggestion.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @howardzhangmsft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by GauravES** [comment]
>>If set to False and AllowAnonymousParticipantsInMeetings parameter is also set to False, federated users will be treated as anonymous users and put into lobby. If set to True and conference admission policy is set to "Anyone from my organization" or openAuthenticated, federated users are treated as company users and admitted into conference directly. If set to True and conference admission policy is set to "People I Invite" or closedAuthenticated, federated users will be put into the lobby if they were not present in the pre-set invitee list.

Where is the "conference admission policy" being set?  It is not in this powershell command.. 

@howardzhangmsft

**Comment by GauravES** [comment]
Sorry, I meant if this can be set as a Policy rather than when creating the meeting.
Also is this applicable to SfB On-premise as well as Online?
