### ISSUE TITLE
Misleading Title

### ISSUE THREAD

**Issue by ekzp** [MicrosoftDocs/office-docs-powershell#4454]
The article title "SharePoint Online CmdLets" suggests that when I click it, I get a list of cmdlets. Instead I am getting a general blurb about what is the SPO management shell, with no link to where the cmdlets are.

It isn't helping, please fix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e45fe794-97e2-c5c0-ebed-a6f46ae39624
* Version Independent ID: 3e502565-ef4a-989c-d020-ca5a55011f3e
* Content: [What is the SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/introduction-sharepoint-online-management-shell?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/introduction-sharepoint-online-management-shell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/introduction-sharepoint-online-management-shell.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ekzp 
Thanks for your feedback.
The list you are looking for is [this](https://docs.microsoft.com/powershell/module/sharepoint-online/?view=sharepoint-ps)

Will create a PR to improve this article.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ekzp Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
