### ISSUE TITLE
-WhatIf parameter is not working

### ISSUE THREAD

**Issue by atop-Ilionx** [MicrosoftDocs/office-docs-powershell#4455]
When you use the New-SPEnterpriseSearchServiceApplication cmdlet with -WhatIf, it still creates a search service application. This problem is for all version (SP2010, SP2013, SP2016, SP2019)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cc01aa6-e961-b4c3-eb48-5b0b32021582
* Version Independent ID: 0c037896-9742-b831-75a2-14264774dbc1
* Content: [New-SPEnterpriseSearchServiceApplication (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spenterprisesearchserviceapplication?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchServiceApplication.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchServiceApplication.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@atop-Ilionx Thank you for reporting this feedback here. This list is focused on content issues and I want to make sure your immediate product issue does not get lost in this list. If you would please open a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team
