### ISSUE TITLE
Enabling a property to enable hiding

### ISSUE THREAD

**Issue by uowdaniel** [MicrosoftDocs/office-docs-powershell#4456]
Under “-HiddenFrom AddressListsEnabled” it says:
“For users that are members of the Office 365 Group, the group will still appear in the navigation pane in Outlook and Outlook on the web if HiddenFromExchangeClientsEnabled property is enabled.”

I think the correct wording under “-HiddenFrom AddressListsEnabled” should be: 
“For users that are members of the Office 365 Group, the group will still appear in the navigation pane in Outlook and Outlook on the web if HiddenFromExchangeClientsEnabled property is NOT enabled.”
or
“For users that are members of the Office 365 Group, the group will still appear in the navigation pane in Outlook and Outlook on the web UNLESS HiddenFromExchangeClientsEnabled property is enabled.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd7d69db-be49-179e-94ce-635337c98d07
* Version Independent ID: 9e372e66-5c7e-4d9a-56de-a35ae353fa09
* Content: [Set-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@uowdaniel Thank you for your feedback. We have made changes to the document via PR# https://github.com/MicrosoftDocs/office-docs-powershell/pull/4467

Thanks
Sri

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4467 . Thanks

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @uowdaniel Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
