### ISSUE TITLE
Exchange PowerShell instructions need to be updated to include the new module as an option

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/office-docs-powershell#4457]
These instructions only include the Click-to-Run version of the module. Please include the latest module as announced at Ignite:
https://www.powershellgallery.com/packages/ExchangeOnlineManagement/0.3374.9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@webash Thank you for your feedback. We have added steps to the doc via PR# https://github.com/MicrosoftDocs/office-docs-powershell/pull/4468

Thanks
Sri

**Comment by webash** [comment]
@msbemba I've submitted a PR to your changes to include `(as Administrator)` to the instructions.

**Comment by msbemba** [comment]
@webash  Thank you. I have deleted your PR and added them as commits to my PR.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @webash Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
