### ISSUE TITLE
Need PreferredDataLocation parameter as an option for a new Team

### ISSUE THREAD

**Issue by DDog80sRocked** [MicrosoftDocs/office-docs-powershell#4458]
We have strict data location requirements so we need to be able to create new Teams in the correct Geo location in a multi-geo environment.  Is it possible to add a PreferredDataLocation parameter with the New-Team cmdlet?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DDog80sRocked 
For feature requests, I need to kindly redirect you to [Microsoft Teams UserVoice](https://microsoftteams.uservoice.com/) there, your suggestion can reach the product team.
Thank you

**Comment by yogkumgit** [comment]
@DDog80sRocked  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
