### ISSUE TITLE
Need PreferredDataLocation parameter as an option for a New unified group

### ISSUE THREAD

**Issue by DDog80sRocked** [MicrosoftDocs/office-docs-powershell#4459]
We have strict data location requirements so we need to be able to create new Teams in the correct Geo location in a multi-geo environment. Is it possible to add a PreferredDataLocation parameter with the New-Team cmdlet? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 316bada1-dbc7-f07a-4afa-d67330edef50
* Version Independent ID: d9380f67-a05a-ddd0-425c-af7023222c69
* Content: [New-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/new-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/New-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/New-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
#4458 

@DDog80sRocked  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
