### ISSUE TITLE
The action of the -Role isn't clear

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/office-docs-powershell#4465]
After reading through this massive thread (referenced below), it seems that the -Role parameter demotes the user to a member, not removes the user from the team.
I've tested this in MicrosoftTeams module version 1.0.3 and it does in fact demote the user, not removes it.

Proposed change
"Specify the role of the user you are removing from the team."
-TO-
"When Owner is specified, the action will demote the user to a Member of the team. Run the command without -Role to remove the user from the team"

Reference thread: https://github.com/MicrosoftDocs/office-docs-powershell/pull/3542

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8d16f25-be6f-06eb-2cd7-9e64eab124e0
* Version Independent ID: a8181f1a-e575-410a-d5a4-0214c427b92d
* Content: [Remove-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/remove-teamuser?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Remove-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Remove-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jantoney 
I also intervened in the other thread and observed that behavior, we will try to get this to the product team so they confirm and we can impact the doc.
Thank you

**Comment by get-itips** [comment]
Hello @jantoney 
How are you?
I could get more information from the Product Group.

_Changes in BETA:
-Role parameter now accepts both "Owner" and "Member" as possible values.
-If cmdlet is called with -Role parameter as "Member" and if the user is both an owner of the team and a member, then they would be removed from the Team completely. 
-If cmdlet is called with -Role parameter as "Owner" then the user is removed as an owner of the team but stays as a team member,. 
-If the user being removed is the last owner of the team, then an exception is thrown as that should not be allowed._

If you want you could test the BETA of the Teams PowerShell module, these new changes will be pushed to PROD once they become stable, and then, the documentation will be changed.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @jantoney 
Hope this comment is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
