### ISSUE TITLE
wrong cmdlet in example

### ISSUE THREAD

**Issue by jimmo120313** [MicrosoftDocs/office-docs-powershell#4466]
Save-PnPSiteTemplate in example 1 should change to Save-PnPProvisioningTemplate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d008d3c2-90ea-7d79-25cb-a0e0e2344df3
* Version Independent ID: 1c091c95-bbef-66ec-1c16-9b903c1316bb
* Content: [Save-PnPProvisioningTemplate (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/save-pnpprovisioningtemplate?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Save-PnPProvisioningTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Save-PnPProvisioningTemplate.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jimmo120313 hope you are doing great.

I need to kindly redirect you to [this other repo](https://github.com/SharePoint/PnP-PowerShell/), where I suggest you to open an issue there, as you might know, PnP cmdlets are open source & community driven and maintained.
A member of the community will pick your issue there.

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @jimmo120313 
These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
