### ISSUE TITLE
A parameter with name liststoextract cannot be found

### ISSUE THREAD

**Issue by deepalakhani** [MicrosoftDocs/office-docs-powershell#4469]
![image](https://user-images.githubusercontent.com/21203029/69737783-fbc7bf00-1102-11ea-997f-ca146d592721.png)
![ListsToExtract](https://user-images.githubusercontent.com/21203029/69737991-5a8d3880-1103-11ea-9af8-3c9b654a30e3.PNG)

I get above error when trying to use -liststoextract parameter

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @deepalakhani hope you are doing great.

I need to kindly redirect you to [this other repo](https://github.com/SharePoint/PnP-PowerShell/), where I suggest you to open an issue there, as you might know, PnP cmdlets are open source & community driven and maintained.
A member of the community will pick your issue there.

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @deepalakhani 
These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
