### ISSUE TITLE
 Remove-PnPSearchConfiguration does not remove Search Configurations in SharePoint Online

### ISSUE THREAD

**Issue by juanmlarios** [MicrosoftDocs/office-docs-powershell#4476]
I can't see to figure out what this command is supposed to do. I'm trying to export the Query Rules and Remove over 1000 query rules but this command doesn't seem to do anything. Is this a bug? or is this by design? if this is by design what does this command actually do?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @juanmlarios hope you are doing great.

I need to kindly redirect you to [this other repo](https://github.com/SharePoint/PnP-PowerShell/), where I suggest you to open an issue there, as you might know, PnP cmdlets are open source & community driven and maintained.
A member of the community will pick your issue there.

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @juanmlarios 
These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
