### ISSUE TITLE
Missing examples 

### ISSUE THREAD

**Issue by tameemansari** [MicrosoftDocs/office-docs-powershell#4477]
Can examples be updated for many of these commandlets? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8d6f4e-0db4-6038-df71-95d22c3b8e09
* Version Independent ID: 12c6accc-f355-33e0-0479-418e141efb74
* Content: [Set-CsTeamsAppPermissionPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsapppermissionpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsAppPermissionPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsAppPermissionPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tameemansari 

Currently the article mentions not to use this cmdlet yet:

> **The existence of this cmdlet is being documented for completeness**, but **do not use this cmdlet**. We require that all creation and modification of app permission polices (not including the assignment or removal of policies from users) happens in the Microsoft Teams & Skype for Business Admin Center to ensure that the policy matches your expectations for the end user experience.

The Product Team is working on this cmdlet and the documentation, once the cmdlet is released for production, will be updated.

Hope this information helps you.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @tameemansari 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by tameemansari** [comment]
@get-itips and @yogkumgit 

> The Product Team is working on this cmdlet and the documentation, once the cmdlet is released for production, will be updated.

I suggest the skype module documentation - https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps be updated with the list of which cmdlet's are considered good for use and which are not.

**Comment by get-itips** [comment]
Hello @tameemansari we hear your suggestion and will be forwarded to the team accordingly. Thank you
