### ISSUE TITLE
Remove the PSSession when finished using it?

### ISSUE THREAD

**Issue by Justin-Shi** [MicrosoftDocs/office-docs-powershell#4478]
From the doc `[Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)` we can connect to the Exchange Online with command:
Connect-EXOPSSession 
Or 
Connect-EXOPSSession -Credential $cred
I found that a session has been imported after connecting to the Exchange Online, you can get it by cmdet Get-PSSession and it will return:
Id Name            ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            ------------    ------------    -----         -----------------     ------------
  1 WinRM1          outlook.offi... RemoteMachine   Opened        Microsoft.Exchange       Available

So I have a question here, once we finished to use it need we remove the session manually by cmdlet Remove-PSSession? As I know, there are session limitations for connecting to Exchange Online?
Another question is that when I using cmdlet:
Connect-EXOPSSession -Credential $cred
to connect Exchange online, it will use the credentials in $cred for authenticating. It is still modern authentication, right? From Fiddler I saw it called lohgin.windows.net.

Thanks
-Justin

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@Justin-Shi Thank you for your feedback.

1) We have a note in the document now which exactly talks about disconnecting the session and the PS cmdlet to run to disconnect (Get-PSSession | Remove-PSSession).

2) This is still modern Authentication and This module doesn't work with basic auth.

Thanks again for your feedback.
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @Justin-Shi 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
