### ISSUE TITLE
Get-MailDetailTransportRuleRepor

### ISSUE THREAD

**Issue by Rmca81** [MicrosoftDocs/office-docs-powershell#4482]
Hi everyone, I am facing an error when i try to run the Get-MailDetailTransportRuleRepor cmdlet. 
All works ok but the if i try to filtered by -Domain, it doesn´t work.
Example: 
Get-MailDetailTransportRuleRepor -domain mydomain.com -->doesn´t show results.
Get-MailDetailTransportRuleReport| Where-Object{$_.Domain -cmatch "myDomain.com"} --> works ok.

Where could be the error?

Thankyou so much!!!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
@Rmca81 Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
