### ISSUE TITLE
MFA unattended?

### ISSUE THREAD

**Issue by SjoerdV** [MicrosoftDocs/office-docs-powershell#4483]
Please could you advise how this can be done with an account which has **MFA enabled** and it needs to connect in an **unattended** manner in an azure devops pipeline process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Office 365 Security & Compliance Center PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md)
* Service: **o365-security-and-compliance**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by tseward** [comment]
MFA cannot be 'unattended' -- being present is the entire point of MFA. You need to use app principals with a client id/secret or allow the user to connect w/o MFA.

**Comment by SjoerdV** [comment]
Well, disabling MFA is not an option. Using App principles is also not an option for the Security & Compliance cmdlets specifically, I could not find any guidance on that anyway, if you have an article you could link to, please do. I would be very much satisfied if I could use a Location exclusion in the Conditional Access MFA policy without disabling MFA all together, but sadly the cmdlets use PS Remoting so the ip address used to actually make the connection is out of my control. 
The current situation, is clearly something that needs work as managing S&C through Powershell in an unattended manner is a very common thing and we should not be forced to bypass security on the executing account completely, right?

**Comment by tseward** [comment]
When deploying MFA, automation must be a consideration. If an account needs to use these in an automated fashion, MFA must be disabled or you need to look into alternatives, e.g. using client id/secret with APIs (Graph APIs may cover what you're attempting to do, I don't know). You'll need to argue in your org that using MFA on this account will prevent automation from functioning. It is a risk and compliance call.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @SjoerdV 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
