### ISSUE TITLE
Add-TeamChannelUser not working

### ISSUE THREAD

**Issue by siljemda** [MicrosoftDocs/office-docs-powershell#4485]
Microsoft Teams version: 1.0.18 (beta)

Expected behaviour: After connecting to MicrosoftTeams with a Teams admin user account, being able to add the Team owner as a member of a private channel

Actual behaviour:
```
Add-TeamChannelUser : Error occurred while executing Add-TeamChannelUser Code: Forbidden Message: Failed to execute Skype backend request GetThreadRequest. InnerError: RequestId: 0a9db92c-c5c4-43e8-9016-17088a026cc5 DateTimeStamp: 2019-12-02T16:32:52 HttpStatusCode: Forbidden At line:39 char:1 + Add-TeamChannelUser -GroupId $TeamId -User $username -DisplayName $Ch ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [Add-TeamChannelUser], ApiException + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets .PowerShell.Custom.AddTeamChannelUser
```

Steps to reproduce:

```
Connect-MicrosoftTeams -Credential $credential

Add-TeamChannelUser -GroupId $TeamId -User $username -DisplayName $ChannelTitle -ErrorAction Continue
Start-Sleep -s 5
```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @siljemda 
Thanks for your feedback.
This issue system is exclusively to report **issues in documentation**.
Besides that, As you are using the Beta version of the module, as you might know it can have unexpected outcomes, I encourage you to test when it gets to the stable version of the module.

Thank you

**Comment by siljemda** [comment]
> Hello @siljemda
> Thanks for your feedback.
> This issue system is exclusively to report **issues in documentation**.
> Besides that, As you are using the Beta version of the module, as you might know it can have unexpected outcomes, I encourage you to test when it gets to the stable version of the module.
> 
> Thank you

Thanks. you, @get-itips . I hope you'll allow me a follow-up question. I have been unable to find a separate code repository for the module. Powershell Gallery and poshtestgallery both specifically list this repo as its Project site. Do you happen to know where I can view issues for the Teams module?

**Comment by get-itips** [comment]
Hello @siljemda 
I recommend visiting the [Tech Community](https://techcommunity.microsoft.com/t5/forums/filteredbylabelpage/board-id/MicrosoftTeams/label-name/microsoft%20teams) and leaving that feedback there.

**Comment by kenwith** [comment]
@siljemda thanks for the feedback and as @get-itips said the best place is Tech Community. The docs here are open source and rely on experts such as yourself. If you would ever want to make an update you can find details in the README of the repo here https://github.com/MicrosoftDocs/office-docs-powershell. 

The docs are sourced in Markdown and updating it is not for everyone so even opening issues and providing guidance is very much appreciated. And thanks for the testing on the beta release, I know the product team very much appreciates it!
