### ISSUE TITLE
Unregister-SPOHubSite does not respect -Confirm:$false parameter

### ISSUE THREAD

**Issue by rudfoss** [MicrosoftDocs/office-docs-powershell#4502]
The CMDLet `Unregister-SPOHubSite` does not seem to respect the parameter `-Confirm:$false`. Event with this parameter specified it asks me to confirm removal.

Test:
```
Unregister-SPOHubSite -Identity $siteUrl -Confirm:$false
```

Prompts:
```
Confirm
This will remove this site from the list of Hub Sites.
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y
```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @rudfoss how are you?
I could reproduce.
@trent-green Can you kindly fwd this to the product team & please confirm me if you want me to document this in the meantime ? Thanks

**Comment by yogkumgit** [comment]
@rudfoss Thank you for reporting this feedback here. This list is focused on content issues and I want to make sure your immediate product issue does not get lost in this list. If you would please open a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team.
