### ISSUE TITLE
This module still requires WinRM basic authentication?

### ISSUE THREAD

**Issue by felinepc** [MicrosoftDocs/office-docs-powershell#4504]
Running this new module with WinRM basic authentication disabled still yields error:

New-ExoPSSession : Connecting to remote server outlook.office365.com failed with the following error message : The WinRM client cannot process the request. Basic authentication is currently disabled in the client configuration.

Isn't this module supposed to get rid of basic auth? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by eric-ash-1** [comment]
I have the same issue, and cannot change my WinRM authentication setting due to a corporate group policy.

**Comment by dariomws306** [comment]
Hi @felinepc and @eric-ash-1, thank you for your feedback.

As you can read in the article Exchange Online PowerShell V2 cmdlets always use Modern Authentication. You cannot use basic authentication here. But WinRM basic authentication is a requirement to connect.

I have tried this on my lab but let me double check it.

**Comment by felinepc** [comment]
Well WinRM basic auth is a big problem with the old module because many of us have GPO or Intune policies that forbid it for valid reasons. Microsoft itself discourages it with the Intune security baselines. So we'd assume a new module should not have to depend on it.

**Comment by dariomws306** [comment]
Please also provide this feedback to the email address you can find in the first tip of the article.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @felinepc Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by eric-ash-1** [comment]
I would like to point out that the AzureAD module (I'm using 2.0.2.76) worked on my computer even though I have WinRM Basic Auth disabled. Perhaps the Exchange Online module could adopt the same methodology.
