### ISSUE TITLE
fwlink is broken

### ISSUE THREAD

**Issue by John-Hart** [MicrosoftDocs/office-docs-powershell#4512]
The link https://go.microsoft.com/fwlink/?LinkID=187810 in the Description results in a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d922a32-981c-8e08-9359-b7f5e21b1aa4
* Version Independent ID: a0f9af58-42af-202c-10f3-dbb09b17595e
* Content: [Install-SPSolution (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/install-spsolution?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Install-SPSolution.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Install-SPSolution.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @John-Hart 
Thanks for noticing and reporting, created a PR to fix this.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @John-Hart Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
