### ISSUE TITLE
Get-TeamChannelUser not returning Guests

### ISSUE THREAD

**Issue by ccullum** [MicrosoftDocs/office-docs-powershell#4513]
I have guests in a Team and they are added to a private channel.
I know that Guests are seen because if I use Get-TeamUser the guests are returned in the collection.
If I use the command Get-TeamChannelUser on any channel only owners and members are returned, not Guests.  
I have tested this on both a standard channel (General) and a private channel.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ccullum 
As the article says, this cmdlet belongs to the beta version of the Teams Ps module, so Product Team is still working on a production release of it.
Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ccullum 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
