### ISSUE TITLE
Does this have effect for both delegated and application permissions?

### ISSUE THREAD

**Issue by jnxxx** [MicrosoftDocs/office-docs-powershell#4517]
I assume this has effect for application permissions.
But how about delegated permissions, can it also restrict these?
That is, when an application acts on behalf of a user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1e6041b-99ca-612b-24d6-053fca4ac717
* Version Independent ID: c18596aa-b54c-1b19-6064-952ae2468d41
* Content: [New-ApplicationAccessPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/new-applicationaccesspolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/New-ApplicationAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/New-ApplicationAccessPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @jnxxx, thank you for your feedback.

I think you can find your answer here:
https://docs.microsoft.com/graph/auth-limit-mailbox-access

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @jnxxx 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
