### ISSUE TITLE
PowerShell Teams New-Team

### ISSUE THREAD

**Issue by aekins** [MicrosoftDocs/office-docs-powershell#4518]
There doesn't seem to be a way to specify 'Class Team'  when creating a new Team. Please tell me this is possible ???? or there is a good workaround.

**Comment by kenwith** [comment]
@aekins - thank you for taking the time to open an issue here. If I am understanding correctly you are looking for a particular example in the doc for the New-Team cmdlet here: https://docs.microsoft.com/powershell/module/teams/new-team?view=teams-ps    or does it seem like there should be a parameter that is not there? The issues here are focused on the docs so we can definitely help there. If a new feature request needs to be added we can also mention in this issue a User Voice so it can be up voted by anyone that reads this thread.

**Comment by aekins** [comment]
Hi,

I think it is a feature that was present in the preview release, but has 
been (weirdly) deprecated in the 1.0 release. It was the ability to 
create a 'Class' Team.

I don't have time to wait for the glacial 'User Voice' system to work 
its magic (we need a solution now). So I think we'll have to go with 
another solution other than PowerShell Teams.


Thanks
Andy

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by kenwith** [comment]
@aekins - sorry, it took me some time to understand this.. I was chatting with @get-itips and he found these articles: https://support.office.com/en-us/article/create-a-class-team-in-microsoft-teams-fae422eb-58b7-4431-9ff2-a4b9b6ae7c5b  and https://www.microsoft.com/en-us/education/products/teams   when we were reviewing them we think that the class is only available in the teams for education product but we aren't positive. We really want to make sure you get this resolved though and the support engineers would be able to look at your specific tenant and get it figured out for you. They respond very quickly. I agree the User Voice takes a long time and I didn't understand fully before I replied. When you log into your Admin Center you can open a Service Ticket under the Help section. If the parameter only appears with a specific product then we definitely need to update the documentation so it is clear. I will keep this doc issue open and if you don't mind if you could keep me updated.. I wish there was a way I could open a service request on your behalf but unfortunately I cannot. Feel free to loop me into the service ticket if you want.. my email is in my GitHub profile.

**Comment by kenwith** [comment]
Confirmed that you should be able to create a Class Team if you have the education subscription. You should be able to do this in the UI and also PowerShell. If support request stated otherwise please let me know and we will investigate further on what might need to be updated in the documentation.
