### ISSUE TITLE
Change Ensure-PnPFolder to Resolve-PnPFolder

### ISSUE THREAD

**Issue by vettekerry** [MicrosoftDocs/office-docs-powershell#4520]
Please change Ensure-PnPFolder to Resolve-PnPFolder in the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b385a5-4bb6-e858-d114-df8b6b41114f
* Version Independent ID: e9821d8f-8e0b-5939-9f3e-43bffb6a0e7b
* Content: [Get-PnPFolder (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpfolder?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFolder.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@vettekerry  Thanks for raising this issue. We need to kindly redirect you to other repository that is: https://github.com/SharePoint/PnP-PowerShell/issues

As you might know, PnP cmdlets are community-driven, a member of the community will pick your request there and handle it, please do a search first in the issues to see if this has been already reported.
Hope this comment is helpful for you. We proceed here to close it. Thanks again for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
