### ISSUE TITLE
Missing info, wrong link

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/office-docs-powershell#4521]
Example 2 is missing "$Prompt = ", like the start of Example 1.

Link for "online version" brings you back to this same page - was it supposed to go elsewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea21f976-9ffd-f9ba-bd20-aa7c991dc811
* Version Independent ID: 5b1b0625-74a2-3e18-62e9-42c9b95b22cb
* Content: [Export-UMPrompt (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/unified-messaging/export-umprompt?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/unified-messaging/Export-UMPrompt.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/unified-messaging/Export-UMPrompt.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @TorrenManson, thank you for your feedback.

I'm updating example 2.

About the link it needs to be there because there is an internal process which use it. Sorry about that.

**Comment by yogkumgit** [comment]
@chrisda please merge this PR #4545

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and updating the documentation with PR. @TorrenManson  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
