### ISSUE TITLE
new-pnpsite throws error:  New-PnPSite : Parameter set cannot be resolved using the specified named parameters

### ISSUE THREAD

**Issue by naoufalaobali** [MicrosoftDocs/office-docs-powershell#4524]
Connect-PnPOnline -Url "https://example-admin.sharepoint.com"

$csv = import-csv -path "C:\Scripts\Sitesjackup.csv" -delimiter ";"
foreach ($sites in $csv) {

New-PnPSite -Type CommunicationSite -Title $sites.Hubsites 

}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5e3530-a63e-71ce-97c8-c904619aafa8
* Version Independent ID: 2c961b64-5c27-6331-b704-716ccfb8c5a7
* Content: [New-PnPSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpsite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@naoufalaobali  Thanks for raising this issue. We need to kindly redirect you to other repository that is: https://github.com/SharePoint/PnP-PowerShell/issues

As you might know, PnP cmdlets are community-driven, a member of the community will pick your request there and handle it, please do a search first in the issues to see if this has been already reported.
Hope this comment is helpful for you. We proceed here to close it. Thanks again for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
