### ISSUE TITLE
Great tip! Thank you.

### ISSUE THREAD

**Issue by richard-artes** [MicrosoftDocs/office-docs-powershell#4530]
Great tip! Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b23d72-33ed-a6a1-a442-a5e5cf039f9f
* Version Independent ID: 4247cf37-3667-2007-7251-46ed80f58ef5
* Content: [Getting started with SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@richard-artes Thank you very much for the compliment. 
If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
