### ISSUE TITLE
-LinkedinEnabled

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/office-docs-powershell#4533]
Even if we set LinkedinEnabled parameter to True We can't use it as connecting to LinkedIn from OWA is no longer supported. Support statement has been mentioned at https://outlook.office.com/owa/?path=/options/socialnetworks . Can we make changes to the documentation accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ca7906-9f33-2991-9da9-a626e5e45c46
* Version Independent ID: 5f388b3c-fb47-f7a0-e648-07cb3e59cf72
* Content: [Set-OwaMailboxPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-owamailboxpolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4546

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and updating the documentation with PR. @3novsan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
