### ISSUE TITLE
Download of the Exchange PowerShell module does not work using the new Microsoft Edge Version 80.0.355.1 dev (64-bit)

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/office-docs-powershell#4534]
This document identifies that you must use Internet Explorer or Edge to download the Exchange PowerShell module. That is partially correct, but currently the download fails using the new Microsoft Edge browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?redirectedfrom=MSDN&view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by KirkMunro** [comment]
FYI, I just noticed you already answered this when another user called this out; however, the documentation remains the same, and this is confusing for the type of folk who would read this document. You're talking to IT pros who want to download a PowerShell module, and there's a good chance many of them may be using the Chromium-based Edge already -- it would be better if the docs were clear about which browser(s) are required to download the module.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @KirkMunro, thank you for your feedback.

For the time being "Edge browser" in docs.microsoft.com doesn't mean chromium-based version because it's still on Release Candidate state. Edge means EdgeHTML RTM version.

I will add some comment in the document.

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4547 Thanks.

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and updating the documentation with PR. @KirkMunro  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
