### ISSUE TITLE
The help info for Connect-EXOPSSession is not accurate?

### ISSUE THREAD

**Issue by Justin-Shi** [MicrosoftDocs/office-docs-powershell#4536]
Hi All,

When I run cmdlet with Exchange Online PowerShell module, I got info like this:
![image](https://user-images.githubusercontent.com/25170467/70694882-84e21700-1cfb-11ea-809e-8fecb9377bfa.png)
While form my test, the ConnectionURI for Office 365 U.S. Government GCC High is not accurate, when I use this URL to connect the Office 365 U.S. Government GCC High, I will get error like:
_New-ExoPSSession : Connecting to remote server outlook.office365.us failed with the following error message : The WinRM client received an HTTP status code of 440 from the remote WS-Management service. For more information, see the about_Remote_Troubleshooting Help topic._

The url should be: https://outlook.office365.us/PowerShell-LiveID
Even I don't have test tenant for Office 365 U.S. Government DoD, I believe the connection URI has similar issue.

BTW, I have an application which access Exchange Online by RPS with modern authentication, I stripped the module (files like: Microsoft.Exchange.Management.ExoPowershellModule.dll, CreateExoPSSession.ps1) from Microsoft Exchange Online PowerShell module under appdata, I plan to include this module into my application's installer and install them with my application. Is this allowed by Microsoft, please? In [nuget ](https://www.powershellgallery.com/packages/Microsoft.Exchange.Management.ExoPowershellModule/16.0.0.0)there is some one already stripped the module and uploaded it, but I don't want to use it as this is not publish by Microsoft.

Thanks
-Justin

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
@Josverl Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Josverl** [comment]
Hi @dariomws306 ,
I think your comment should be directed at @Justin-Shi.

/jos

**Comment by yogkumgit** [comment]
@Justin-Shi . If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it.
