### ISSUE TITLE
Typo in -LiveCaptionsEnabledType

### ISSUE THREAD

**Issue by nakatenus** [MicrosoftDocs/office-docs-powershell#4537]
There is a typo in the default value of -LiveCaptionsEnabledType. It should say DisabledUserOverride instead of DisabledUserOveride.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18b9baa8-da13-a24f-af31-91d63de13f08
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @nakatenus thanks for noticing and reporting. I created a pull request to fix this typo.
Thank you

**Comment by yogkumgit** [comment]
@tomkau Please merge this PR #4571

**Comment by dannydpa** [comment]
Apart from the values mentioned there is also the option EnabledUserOverride for -LiveCaptionsEnabledType.

**Comment by get-itips** [comment]
Hello @dannydpa it is true but the EnabledUserOverride has been deprecated and you can't actually set it.
![image](https://user-images.githubusercontent.com/36666927/72540048-eb4fdd00-3845-11ea-8199-2d5d4ae0e882.png)

@yogkumgit PR was merged please close this thread. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @nakatenus Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
