### ISSUE TITLE
EnableSafeLinksForClients or EnableSafeLinksForO365Clients

### ISSUE THREAD

**Issue by NiteshSharma2K19** [MicrosoftDocs/office-docs-powershell#4538]
This is too confusing. -EnableSafeLinksForClients is working for one tenant and -EnableSafeLinksForO365Clients is working for another. Example uses -EnableSafeLinksForClients tells what is it doing but later on the page -EnableSafeLinksForO365Clients is describing the same action. I confirmed on 3 different tenants with same subscriptions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f989bf3c-3ed0-3dc2-3e9e-4643c85eec9f
* Version Independent ID: c14642cb-4623-8f30-cf51-6b8176a6893a
* Content: [Set-AtpPolicyForO365 (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-atppolicyforo365?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Set-AtpPolicyForO365.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Set-AtpPolicyForO365.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by NiteshSharma2K19** [comment]
Any updates. This is important. 
Thanks

**Comment by dariomws306** [comment]
Hi @NiteshSharma2K19, thank you for your feedback.

Really this parameter is EnableSafeLinksForClients and I have test in some tenants. Where do you find EnableSafeLinksForO365Clients? Could you let me know what licenses do you have in these tenants?

I'm updating the article.

**Comment by NiteshSharma2K19** [comment]
@dariomws306 
-EnableSafeLinksForO365Clients
The EnableSafeLinksForO365Clients parameter specifies whether Safe Links is enabled for Office 365 apps on desktop clients and the web. Valid values are:

$true: Safe Links are enabled for Office 365 apps. This is the default value.

$false: Safe Links are disabled for Office 365 apps.

This is the definition of the cmdlet on this doc. This is explaining the same action which is described in example 1. This is confusion. 
We have E5 subscription in all three tenants. Please find the links below for two different tenants, where I tried the same using PowerShell.

<img src="https://bvh9ka.bn.files.1drv.com/y4mTag7zUn4jJulRUuWuv-4csS_4zx0sgg37k9IgKtW-vKlvu1jpm0kZFiph6xLDT0xmUfG7E7JBhZyBjj0SjBvznT42cAU2d9-TsHydIgUqooOmHtgcfFfGL5ahRI_kkIbrMFO6J0Zdm_uW-xmT-zzmldfjh0wcIKjuAR-n571ZfOLr6r_SvMqfV5rZdv85jYMdrlQJQa6YjrDUrdbYoqkDg?width=911&height=764&cropmode=none" width="911" height="764" />
<img src="https://bph9ka.bn.files.1drv.com/y4m2u1yznAaN4I5DF8lGcw-DPx94D8pqB2-t4aa0taxoHNJGuiSbrWdNMPr2SFqAK-5ojCDpK_yITL5TmSsmZVpH599yem8ax1BwMBcLVdOxGaAl1g_sgq6by5mGYui_QVF6G9_Nn2jJDf7I2CcSBNYfjpyr1r7oBMSXxW0ClEDLGbFEL_cRGY3DJazWCmpSbd0R0LScZZreYC0nkVzbnn7fw?width=945&height=718&cropmode=none" width="945" height="718" />

**Comment by dariomws306** [comment]
It should be EnableSafeLinksForClients, I'm updating the document. I cannot say why you have EnableSafeLinksForO365Clients in one tenant, sorry.

**Comment by NiteshSharma2K19** [comment]
Can you please guide me what can be done then on the tenant where I am getting the error that "A parameter can not be found that matches parameter name 'EnableSafeLinksForClients"?

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4548

**Comment by chrisda** [comment]
Use which ever one is currently available to you: EnableSafeLinksForClients for most people, and EnableSafeLinksForO365Clients if it happens to be available to you. They are functionally the same, and I'm told that eventually EnableSafeLinksForO365Clients will replace EnableSafeLinksForClients, but the change hasn't been implemented everywhere yet.

**Comment by NiteshSharma2K19** [comment]
Thanks @chrisda , for the explanation. So instead of the changes made by @dariomws306 we should include your comment as a note. This should resolve the confusion. Also, we were getting the below error when we did a test for security analysis.

<img src="https://bfh9ka.bn.files.1drv.com/y4mBVUIahwVrp-4L7gjWNPzrXOlntgnDBcxT2O-26Q7quisYhogpxJtTR6R2o6_GuwiX7-CrG9msIt5Hc5oPBRrNdAG3Vz8FAHLF7ojBCMHwqhYEdfXE9-MhEltxw-xwjI6X2pPwAPV1zsFzI6Lef6TkLZnNEVA84Q3AFGdho04HO8vQJjUqPrRkwBoXJ0EO1NthbBh_DXSxPAr043tMk9BGQ?width=1920&height=1080&cropmode=none" width="1920" height="1080" />

This was there when we have EnableSafeLinksForClients giving False and EnableSafeLinksForO365Clients True.

Thanks again,
Nitesh

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and updating the documentation with PR. @NiteshSharma2K19  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by NiteshSharma2K19** [comment]
Hello @yogkumgit , Can you please also add the Comments suggested by @chrisda . This will help others to understand what is going on with these two Cmdlets. This was confusing to me, even I am working for MS.

**Comment by dariomws306** [comment]
@chrisda What do you think? Should we add a note to let readers know that it would be EnableSafeLinksForO365Clients in the future?

**Comment by dariomws306** [comment]
I have created a new PR to add this comment. @chrisda please approve it if you are agree.

Thanks!

**Comment by yogkumgit** [comment]
@NiteshSharma2K19 Hope this update looks ok now. Thanks for your kind feedback. Appreciate.
