### ISSUE TITLE
Internal Names or Display Names?

### ISSUE THREAD

**Issue by ekongataspect** [MicrosoftDocs/office-docs-powershell#4541]
It would be nice if the documentation included whether the cmdlet is expecting the list and field names as internal names or display names.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a202f2-42cf-9546-b792-7ec236470d9a
* Version Independent ID: 4eb3b331-fe83-e038-eb01-a297f3506a00
* Content: [Get-PnPField (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpfield?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPField.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPField.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ekongataspect 
Hope you are doing great.
I need to kindly redirect you to [this other repo](https://github.com/SharePoint/PnP-PowerShell/issues) to report issues in documentation of PnP or in PnP cmdlets, as you might know, PnP cmdlets are community driven, a member of the community will pick your feedback there and act accordingly.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ekongataspect 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
