### ISSUE TITLE
Link partly broken

### ISSUE THREAD

**Issue by diecknet** [MicrosoftDocs/office-docs-powershell#4542]
The Link [Protecting you against the SSL 3.0 vulnerability](https://blogs.office.com/2014/10/29/protecting-ssl-3-0-vulnerability/) (under "[Description](https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/new-exchangecertificate?view=exchange-ps#description)") is partly broken. If you open the link using a German system, it'll forward to https://www.microsoft.com/de-de/microsoft-365/blog/2014/10/29/protecting-ssl-3-0-vulnerability/, which is broken. https://www.microsoft.com/en-us/microsoft-365/blog/2014/10/29/protecting-ssl-3-0-vulnerability/ works though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13debe35-d71b-6df4-cded-a081fc58b06c
* Version Independent ID: 8dc4d423-81ac-be09-d849-a2e8011594d3
* Content: [New-ExchangeCertificate (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/new-exchangecertificate?view=exchange-ps#description)
* Content Source: [exchange/exchange-ps/exchange/encryption-and-certificates/New-ExchangeCertificate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/encryption-and-certificates/New-ExchangeCertificate.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@diecknet  Thank you for your feedback. We have updated the doc with the correct link Via PR #https://github.com/MicrosoftDocs/office-docs-powershell/pull/4551

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @diecknet  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
