### ISSUE TITLE
missing What de rights are

### ISSUE THREAD

**Issue by pear7777** [MicrosoftDocs/office-docs-powershell#4543]
What are the ricghts you get wen
AvailabilityOnly

LimitedDetails

Reviewer

Editor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e177c731-d40e-699e-1f27-a760cb9265c7
* Version Independent ID: 20849f6f-f601-59cd-dd66-3c028c615847
* Content: [Set-MailboxFolderPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailboxfolderpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-MailboxFolderPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-MailboxFolderPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment]
@pear7777 Thank you for the feedback. The details that you are looking for is added to the parameters section of the document here;-  https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailboxfolderpermission?view=exchange-ps#parameters

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @pear7777 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Everade** [comment]
Still missing some.
Like **Owner**, and a few others.
