### ISSUE TITLE
What module is this cmdlet in?

### ISSUE THREAD

**Issue by A9G-Data-Droid** [MicrosoftDocs/office-docs-powershell#4544]
The module link at the top of the page is dead (404): 
Module:
exchange
https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/?view=exchange-ps

I can't find any module simply named "exchange" like that. So what module is it?

NOTE: I'm using the "Exchange Online Remote PowerShell Module" and it's not found in there, as I expect it should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d9d5ef4-f1e3-259d-637d-3c3424c337c0
* Version Independent ID: 5ee9d8d7-c925-8eca-d32f-5acb3c0ca37d
* Content: [New-OMEConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/new-omeconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/encryption-and-certificates/New-OMEConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/encryption-and-certificates/New-OMEConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @A9G-Data-Droid, thank you for your feedback.

I have verified in a demo tenant and this cmdlet is available in Exchange Online.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @A9G-Data-Droid Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
