### ISSUE TITLE
-ResultSize parameter?

### ISSUE THREAD

**Issue by mmascolino** [MicrosoftDocs/office-docs-powershell#4549]
What is the purpose of the -ResultSize parameter if no matter how I call this commandlet, it requires me to use the -Identity parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cad7e1a-aec3-c898-e3d2-08b4dd97ba1f
* Version Independent ID: a56a59ec-4249-3a5a-0583-078a099debfa
* Content: [Get-Place (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-place?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@mmascolino, good point. ResultSize makes no sense if you can only return one object at a time.

This appears to be the case where ResultSize is available, but shouldn't be. I changed the description to "reserved for internal Microsoft use" for now.

Thanks for the feedback
