### ISSUE TITLE
Does this command works 

### ISSUE THREAD

**Issue by prontohostau** [MicrosoftDocs/office-docs-powershell#4550]
Since this command not works anymore in 2019, We could use it for Move items and folders with -TargetMailboxes. Now which commands allows to move items and folders. Please add new commands

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @prontohostau, thank you for your feedback.

Could you kindly list the command you are referring?

**Comment by yogkumgit** [comment]
@prontohostau  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by prontohostau** [comment]
> Hi @prontohostau, thank you for your feedback.
> Could you kindly list the command you are referring?
Hi @dariomws306 @yogkumgit 
Referring for the command New-MailboxSearch and Mailbox-Search
Just looking for info is it still works.

https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-mailboxsearch

**Comment by dariomws306** [comment]
Hi @prontohostau,

New-MailboxSearch and Search-Mailbox should be still working on-premises but not online.

If you are using Exchange Online you should use New-ComplianceSearch instead, and you can even use it on-premises.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @prontohostau Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
