### ISSUE TITLE
HiddenFromExchangeClientsEnabled

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/office-docs-powershell#4552]
The following statement that appears in the 'Description' section of this doc is no longer valid and should be removed b/c Set-UnifiedGroup supports changing the HiddenGroupMembershipEnabled property:
"The HiddenGroupMembershipEnabled parameter is only available on the New-UnifiedGroup cmdlet. You can't change this setting on an existing Office 365 Group."

Thank you, Keith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd7d69db-be49-179e-94ce-635337c98d07
* Version Independent ID: 9e372e66-5c7e-4d9a-56de-a35ae353fa09
* Content: [Set-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/Set-UnifiedGroup?redirectedfrom=MSDN&view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @mrkeiths, thank you for your feedback.

This parameter is not available in my demo tenant:
![image](https://user-images.githubusercontent.com/33589238/71173462-8ce11000-2241-11ea-92d2-6fee10283231.png)

HiddenFromAddressListsEnabled and HiddenFromExchangeClientsEnabled are available.

**Comment by mrkeiths** [comment]
Hello,
I just re-tested and am really sorry to have wasted your time.  I have a feeling I must have used HiddenFromExchangeClientsEnabled or HiddenFromAddressListsEnabled since this is what resolves using tab.

You're right.  There is no support for HiddenGroupMembershipEnabled using Set-UnifiedGroup.

You can close this request.

Take care, Keith

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @mrkeiths 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dariomws306** [comment]
Don't worry Keith, can happen, thank you for your feedback!
