### ISSUE TITLE
UserAccountControl Property?

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/office-docs-powershell#4553]
The useraccountcontrol property from get-user is not listed. This is used to filter out disabled users. Is there an alternative to identifying disabled users now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9145396-cc72-6e54-4204-6867397e67ea
* Version Independent ID: ca86d515-e4d3-ce0f-11e3-87ddfda38b75
* Content: [Property sets in Exchange Online PowerShell V2 cmdlets](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/cmdlet-property-sets?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/cmdlet-property-sets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/cmdlet-property-sets.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @JustinGrote, thank you for your feedback.

Exchange Online PowerShell V2 module is still on preview. Anyway, with V2 module you can still use V1 cmdlets so you can use Get-User to get disabled users.

Also, you can send feedback to improve V2 here:
exocmdletpreview[at]service[dot]microsoft[dot]com

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @JustinGrote Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
