### ISSUE TITLE
Cannot run any commands from msonline module after connecting to Connect to Exchange Online PowerShell using multi-factor authentication

### ISSUE THREAD

**Issue by Danithak** [MicrosoftDocs/office-docs-powershell#4558]
1) Followed all steps at https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps and Get-Mailbox returns all active mailboxes. 
2) Tried running Remove-MsolUser on a deleted mailbox and it returns:
The term 'remove-msoluser' is not recognized as the name of a cmdlet, function, script file, or       operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
3) Tried running import-module msonline and it returns:
The specified module 'msonline' was not loaded because no valid module file was found in any module directory.
4) Added screenshots for verification; see for yourself.

I'll come back and try again in a day or two to see if anything changes. 

![office-docs-powershell issue 1](https://user-images.githubusercontent.com/6495613/71017466-730dc480-20ab-11ea-987b-8d13484d0236.jpg)
![office-docs-powershell issue 2](https://user-images.githubusercontent.com/6495613/71017469-743ef180-20ab-11ea-9697-a32835346ef0.jpg)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Danithak,

Msol module is different from Exchange Online Module. Please follow the next steps to connect to Azure AD PowerShell:
https://docs.microsoft.com/office365/enterprise/powershell/connect-to-office-365-powershell

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @Danithak 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
