### ISSUE TITLE
how to set it

### ISSUE THREAD

**Issue by WillemVerwijs** [MicrosoftDocs/office-docs-powershell#4564]
A link to a "set" command would be great

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b9940c-4131-2703-1ab3-5840150d075b
* Version Independent ID: b6efe322-a2c9-af80-fab6-7bab5c88bc2e
* Content: [Get-MailboxRegionalConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/get-mailboxregionalconfiguration?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/client-access/Get-MailboxRegionalConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Get-MailboxRegionalConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @WillemVerwijs Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
