### ISSUE TITLE
how to set for all users

### ISSUE THREAD

**Issue by WillemVerwijs** [MicrosoftDocs/office-docs-powershell#4565]
please give an example on how to do this for all users, all at once

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4acd15e-7bab-4251-dbcb-a075611fcdef
* Version Independent ID: 90b61091-8343-7071-e56d-d963096e3f37
* Content: [Set-MailboxRegionalConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-mailboxregionalconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-MailboxRegionalConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-MailboxRegionalConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @WillemVerwijs Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
