### ISSUE TITLE
Missing reference to Teams

### ISSUE THREAD

**Issue by carolynblanding** [MicrosoftDocs/office-docs-powershell#4567]
[States that this applies to Skype for business Online but it applies to online voicemail service which is applicable to Teams as well. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d50f632e-418b-b715-80d1-13af57332435
* Version Independent ID: dbea5fd4-8b55-dd74-dec9-62402d35aaf8
* Content: [Set-CsOnlineVoicemailPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoicemailpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineVoicemailPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineVoicemailPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @carolynblanding 
Thanks for taking the time to report this.
Recently, another person reported something like this, please read the following explanation by @kenwith https://github.com/MicrosoftDocs/office-docs-powershell/issues/4501#issuecomment-562207181 on why we currently can't update the Applies to metadata.

**Comment by carolynblanding** [comment]
OK. Thanks.


Carolyn Blanding

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @carolynblanding Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
