### ISSUE TITLE
Remove user from all office 365 

### ISSUE THREAD

**Issue by Bhawana023** [MicrosoftDocs/office-docs-powershell#4569]
how to remove  a user from no of office 365 group using powershell ?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Bhawana023 
How are you?
This issue system is to report issues currently present in documentation, is there any specific issue you see in an article that needs to be fixed?
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Bhawana023 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Bhawana023** [comment]
Could you please share a name of the document ???

Thanks & Regards
Bhawana

**Comment by get-itips** [comment]
> Could you please share a name of the document ??? Thanks & Regards Bhawana


> To modify members, owners, and subscribers of Office 365 Groups, use the Add-UnifiedGroupLinks and Remove-UnifiedGroupLinks cmdlets

https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/remove-unifiedgrouplinks?view=exchange-ps

**Comment by Bhawana023** [comment]
Hi, 

I tried to use this URL, but i have to pull the Identity from excel sheet(I have exported a excel sheet of  the office 365 group user is member of now). And i am unable to find the parameter to pull the identity from excel sheet to remove no of office365 group from one user.

Example i have one user with 5 office 365 group i want to create script so user would remove from all 5 cloud groups, this Remove-UnifiedGroupLinks is taking identity of one group only.


 I wanted to how to use that excel sheet parameters to pick that group name from the sheet one by one and remove the user from that list of groups.

let me know if you have any questions.

**Comment by get-itips** [comment]
Hello @Bhawana023 
Hope you are doing fine 👍 Need to kindly remind you that this issue system is to report issues currently in documentation, is there any specific issue that you see in documentation that needs to be fixed? 
It seems, based on what you wrote, that you need help using these cmdlets, to get help, I can suggest [Microsoft Tech Community](https://techcommunity.microsoft.com/)

Hope this information helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Bhawana023 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
