### ISSUE TITLE
List parameter bears no difference

### ISSUE THREAD

**Issue by nate1178** [MicrosoftDocs/office-docs-powershell#4570]
The -List parameter information is not correct. It states "The ID, Title or Url of the list." but if i provide it a URL, it returns alert data for all alerts on the site and not just from the URL that is provided. Please correct the documentation or correct the apparent bug 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68f8cbdd-192b-3ee4-01ef-be96d52d815c
* Version Independent ID: 22531cd3-ddfe-36b9-c260-43443318f5af
* Content: [Get-PnPAlert (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpalert?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPAlert.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPAlert.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @nate1178 
Hope you are doing great.
I need to kindly redirect you to this [other repo](https://github.com/SharePoint/PnP-PowerShell/issues) to report issues in documentation of PnP or in PnP cmdlets, as you might know, PnP cmdlets are community driven, a member of the community will pick your feedback there and act accordingly.
Thank you

**Comment by nate1178** [comment]
Hi @get-itips , i merely commented on a ms documentation page, which created this post. Some automation posted it here, and id imagine it would need some updating if this isnt the appropriate forum for the issue reported

**Comment by get-itips** [comment]
Hello @nate1178 exactly, the feedback section puts your comment here, you did good 👍 there is nothing wrong on what you did and we appreciate your feedback.
As the documentation for PnP cmdlets is in this repo, the issues end up here, but on the repo I referenced they will be taken care of.
Would you be so kind opening the same issue but here https://github.com/SharePoint/PnP-PowerShell/issues ?
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @nate1178 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
