### ISSUE TITLE
Wrong title in a Japanese article

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/office-docs-powershell#4574]
This page is for Get-SPOSiteGroup, but the current title in Japanese is Remove-SPOSiteGroup.

https://docs.microsoft.com/ja-jp/powershell/module/sharepoint-online/get-spositegroup?view=sharepoint-ps

![image](https://user-images.githubusercontent.com/13634805/71232295-be86d380-2334-11ea-8404-a680ee08b449.png)

Please check it.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acdde38b-1d4e-9ca4-3300-d1afdcfe0423
* Version Independent ID: 200efa3d-f697-f70a-e625-936e61eea836
* Content: [Get-SPOSiteGroup (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositegroup?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteGroup.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @kefujino 
Thanks for noticing and reporting, we are currently investigating this.

**Comment by OfficeGlobal** [comment]
Topic is MTed. We did re-handoff to check it if helps. If not, we will uplift to HT.

**Comment by get-itips** [comment]
Hello @kefujino article was corrected.
@yogkumgit please close this issue. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @kefujino 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
