### ISSUE TITLE
Exchange Online Get-Mailbxostatistic -database parameter not available

### ISSUE THREAD

**Issue by bedo1976** [MicrosoftDocs/office-docs-powershell#4576]
[Enter feedback here]

This article:
https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailboxstatistics?view=exchange-ps

Applies to:
Exchange Server 2010, Exchange Server 2013, Exchange Server 2016, Exchange Server 2019, Exchange Online

I'm connected to Exchange online but Get-MailboxStatistics -Database doesn't work:

PS C:\Users\bdonl> Get-MailboxStatistics -database EURP189....
A parameter cannot be found that matches parameter name 'database'.
    + CategoryInfo          : InvalidArgument: (:) [Get-MailboxStatistics], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-MailboxStatistics
    + PSComputerName        : outlook.office365.com

In my opinion also -server is not working. Please either update the documentation or enable this commands in exchange online.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ace9785-2983-7bfe-a1a9-c32f04fb4a4a
* Version Independent ID: bd9a7d87-f816-7351-c694-3f80c6331150
* Content: [Get-MailboxStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailboxstatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-MailboxStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-MailboxStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @bedo1976, thank you for your feedback.

If you check the description of -Server and -Database you can see that them apply only to on-premises:
"This parameter is available only in on-premises Exchange."
"Applies to: | Exchange Server 2010, Exchange Server 2013, Exchange Server 2016, Exchange Server 2019"

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @bedo1976 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
