### ISSUE TITLE
Restart of Powershell required after installing PowershellGet module

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/office-docs-powershell#4578]
After doing Install-Module PowershellGet -Force the subsequent command  (Install-Module -Name ExchangeOnlineManagement) was failing with "PowerShellGetFormatVersion ‘2.0’ is not supported by the current version of PowerShellGet."

Another thread helped me by saying I had to restart Powershell again after installing PowershellGet.  That made it work for me.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @pilcherd, thank you for your feedback.

I have been verified this in a new Windows 10 installation and I didn't need to restart powershell. What OS version are you using?

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @pilcherd 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
