### ISSUE TITLE
Update cmdlets for OnPrem

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/office-docs-powershell#4579]
See https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Disabling-Legacy-Authentication-in-Exchange-Server-2019/ba-p/712048

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d36e1da8-8603-5457-b4fa-b1f2edae2533
* Version Independent ID: c8563140-ee8f-5c50-889c-1761baebabe3
* Content: [New-AuthenticationPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/new-authenticationpolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/organization/New-AuthenticationPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/New-AuthenticationPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@trudolf-msft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
