### ISSUE TITLE
How to connect to national clouds?

### ISSUE THREAD

**Issue by victorguo** [MicrosoftDocs/office-docs-powershell#4581]
I'm trying to connect to Office 365 operated by 21Vianet in China. But when I ran the following cmdlet:

```
$cred = Get-Credential
Connect-ExchangeOnline -Credential $cred -ConnectionUri 'https://partner.outlook.cn/PowerShell-LiveID' -AzureADAuthorizationEndpointUri 'https://login.chinacloudapi.cn/common'
```

I got an error:

```
New-ExoPSSession : AADSTS700016: Application with identifier 'fb78d390-0c51-40cd-8e17-fdbfab77341b' was not found in
the directory 'uca4.partner.onmschina.cn'. This can happen if the application has not been installed by the
administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request
to the wrong tenant.
Trace ID: 4d027bdc-0d8c-4965-9433-aa2c4ef01e00
Correlation ID: 896856c0-a2be-4273-a873-66bfd4f1697e
Timestamp: 2019-12-23 17:24:31Z.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\0.3374.9\ExchangeOnlineManagement.psm1:367
char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession
```

If I ran the cmdlet again right away, I got a different error:

```
New-ExoPSSession : AADSTS900144: The request body must contain the following parameter: 'password'.
Trace ID: 467704fb-8e06-46bb-8ee1-f3505f3b1c00
Correlation ID: b6c2505b-2e2c-414b-9c19-fa51fd7e335f
Timestamp: 2019-12-23 17:25:59Z.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\0.3374.9\ExchangeOnlineManagement.psm1:367
char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28f6554b-4d67-06d3-7926-1b958653872f
* Version Independent ID: 7a6a1737-afdf-dfd5-67f8-64aa6758ccc4
* Content: [Connect-ExchangeOnline (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/connect-exchangeonline?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @victorguo, thank you for your feedback.

This module is still in preview so I think 21Vianet in China is not supported yet. Please provide any feedback about this module to exocmdletpreview@service.microsoft.com.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @victorguo 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
