### ISSUE TITLE
Three connections limit

### ISSUE THREAD

**Issue by warleygr** [MicrosoftDocs/office-docs-powershell#4582]
Hello!
Is the three connections limit per PowerShell PID, PC, or public IP Address?
I think the article is not that clear about this.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @warleygr, thank you for your feedback.

It's a limit to the entire organization/tenant. You are limited to 3 remote connections from the same or any PC/Public IP.

**Comment by warleygr** [comment]
Thanks, @dariomws306 !
I believe if I use Azure Automation to run my scripts, there's no connection limit. Am I right?

**Comment by dariomws306** [comment]
I understand that the limit apply in any condition.

**Comment by warleygr** [comment]
Got it. At last, there's no connections limit for different tenants, is it right?
e.g.: Running script with 5 sessions in 5 different Tenants.

**Comment by dariomws306** [comment]
You are right.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @warleygr 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
