### ISSUE TITLE
{{Fill TeamsPolicyOnly Description}} error

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/office-docs-powershell#4583]
The page has this string: '{{Fill TeamsPolicyOnly Description}}'. It should be replaced by the proper content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5c7d2a3-15f1-c4d1-1431-55fa62b914ee
* Version Independent ID: 00316a3a-790d-873c-d6b0-ff4dbb566651
* Content: [Get-RetentionCompliancePolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-retention/get-retentioncompliancepolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-retention/Get-RetentionCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-retention/Get-RetentionCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4596 , Thanks

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @GiantCrocodile Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
