### ISSUE TITLE
Notebook link not working after getting XML.

### ISSUE THREAD

**Issue by sheykh-sleky** [MicrosoftDocs/office-docs-powershell#4584]
https://github.com/SharePoint/PnP-Sites-Core/issues/1915

get-pnpprovisioningtemplate is breaking notebook links.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sheykh-sleky 
Hope you are doing great.
I need to kindly redirect you to this [other repo](https://github.com/SharePoint/PnP-PowerShell/issues) to report issues in documentation of PnP or in PnP cmdlets, as you might know, PnP cmdlets are community driven, a member of the community will pick your feedback there and act accordingly.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @sheykh-sleky 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
