### ISSUE TITLE
EXO V2 DelegatedOrginization Not working

### ISSUE THREAD

**Issue by kendalldTalon** [MicrosoftDocs/office-docs-powershell#4591]
When I try to connect to a customers tenant using the following it connects me to my tenant and not the customers tenant that I have DAP. 
Connect-ExchangeOnline -UserPrincipalName <MyUPN> -DelegatedOrganization <Customers tenantId> or <Customers Default Domain Name>

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @kendalldTalon, thank you for your feedback.

This issue was reported before and Product Group is aware of it:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4372

Should be fixed soon.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @kendalldTalon as suggested concerning team will evaluate and take the appropriate action, as per their schedule. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
