### ISSUE TITLE
 The specified module 'Microsoft.SharePoint.MigrationTool.PowerShell' was not loaded because no valid module file was found

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/office-docs-powershell#4593]
The instructions [here](https://docs.microsoft.com/en-us/sharepointmigration/overview-spmt-ps-cmdlets) say to go to the folder $env:UserProfile\Documents\WindowsPowerShell\Modules\Microsoft.SharePoint.MigrationTool.PowerShell and run: Import-Module Microsoft.SharePoint.MigrationTool.PowerShell 
That creates the error:
Import-Module : The specified module 'Microsoft.SharePoint.MigrationTool.PowerShell' was not loaded because no valid module file was found in any module directory.
And none of the commands work.
I tried on 2 computers and got the same results
Any Workarounds?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Ofer-Gal 
I could not repro, are you, by chance, using OneDrive's folder redirect? 
Can you, cd into that folder? does it exists?
Let us know so, if needed, we can correct the article.

**Comment by Ofer-Gal** [comment]
Not using OneDrive's folder. but I have it installed.
The folder $env:UserProfile\Documents\WindowsPowerShell\Modules\Microsoft.SharePoint.MigrationTool.PowerShell  containes 36 files mostly *.DLL  many start with microsoft.sharepoint.migrationtool.*
I did install it on a server and there Import-Module worked.
So I assume the issue is something to do with windows 10 or some other client application.

**Comment by get-itips** [comment]
Ok, that's weird, I too tried with Windows 10 with no issues at all.
@yogkumgit kindly close this one, if it happens to anyone else, we might have another scenario and it can be re-opened.

**Comment by Ofer-Gal** [comment]
Later I found a workaround to run the  Import-Module against the full path.
So:
"Import-Module $env:UserProfile\Documents\WindowsPowerShell\Modules\Microsoft.SharePoint.MigrationTool.PowerShell" works.
It has something to do with the fact that users like me have Ondrive install too.
Not sure why, but It resolved my issue.

**Comment by get-itips** [comment]
I am happy to hear @Ofer-Gal thanks for your contribution
