### ISSUE TITLE
Set-PnPList -Identity $ListName -BreakRoleInheritance for >5000 items

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/office-docs-powershell#4594]
Breaking inheritance using this cmdlet for large lists fails with an error like "Set-PnPList : The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator."
Is there a force parameter in plan, or a workaround to do this programatically ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbab5a2d-0c37-bb2c-f2d9-989bc2a59d05
* Version Independent ID: 2f512ab6-be40-1fb2-9f8a-d1bc692537ce
* Content: [Set-PnPList (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplist?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPList.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @danone1985 
Hope you are doing great.
I need to kindly redirect you to this [other repo](https://github.com/SharePoint/PnP-PowerShell/issues) to report issues in documentation of PnP or in PnP cmdlets, as you might know, PnP cmdlets are community driven, a member of the community will pick your feedback there and act accordingly.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @danone1985 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
