### ISSUE TITLE
Markdown errors

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/office-docs-powershell#4597]
- {{Fill TenantScopeOnly Description}}
- ` symbol error for 'Test-CsEffectiveTenantDialPlan'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2b0251-02e7-b708-75d7-36a27938399a
* Version Independent ID: 78212caa-3706-eccf-ea7f-a595b9010b58
* Content: [Test-CsEffectiveTenantDialPlan (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/test-cseffectivetenantdialplan?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Test-CsEffectiveTenantDialPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Test-CsEffectiveTenantDialPlan.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @GiantCrocodile Thanks for noticing, created a pr to propose some changes, thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @GiantCrocodile Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
