### ISSUE TITLE
Get-SPOBuiltInDesignPackageVisibility - No Description and Example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4599]
This cmdLet lacks a proper description and example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d3ab176-305a-701d-1029-6bb0d9f1a5f6
* Version Independent ID: 7820f7ad-c372-b18c-4aac-d7ce4c152a14
* Content: [Get-SPOBuiltInDesignPackageVisibility (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spobuiltindesignpackagevisibility?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInDesignPackageVisibility.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInDesignPackageVisibility.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
