### ISSUE TITLE
Get-TeamChannel returns BadRequest response

### ISSUE THREAD

**Issue by sksnips** [MicrosoftDocs/office-docs-powershell#46]
Accessing **Get-TeamChannel** command returns the Bad Request as a response. 
Because it calls the Graph API as 
https://graph.microsoft.com/beta/groups/**GroupID**/team/channels

Instead of

https://graph.microsoft.com/beta/groups/**GroupID**/channels
![get-teamchannel](https://user-images.githubusercontent.com/11997559/32407394-1b587914-c1ae-11e7-881d-26b8f730e180.png)

**Comment by cimares** [comment]
I'm having the same response on all of the TeamChannels cmdlets (Set, Get and New)

**Comment by kenwith** [comment]
I will bring this to product team and get a response.

**Comment by nkramer** [comment]
This is been fixed, let me know if you're still having problems.

**Comment by kenwith** [comment]
Thanks Nick! Closing this out.

**Comment by sksnips** [comment]
Its working now. Thanks Nick & Ken. :)
