### ISSUE TITLE
Get-SPOCrossGeoMoveReport - No description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4600]
This CmdLet lacks a correct description and an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7e4e31b-eae6-abac-6af9-4b1dae4674bb
* Version Independent ID: 364993b1-e909-2f1e-82b8-5eba8bed537f
* Content: [Get-SPOCrossGeoMoveReport (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spocrossgeomovereport?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMoveReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMoveReport.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
