### ISSUE TITLE
Get-SPODataEncryptionPolicy - No example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4601]
This CmdLet lacks an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781f6cb6-e1b5-ef1d-b811-171d9d749f91
* Version Independent ID: b3a23a18-70af-d4c6-dd77-176f90d1d895
* Content: [Get-SPODataEncryptionPolicy (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spodataencryptionpolicy?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataEncryptionPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataEncryptionPolicy.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
