### ISSUE TITLE
Get-SPOMultiGeoExperience - No description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4602]
This CmdLet lacks a correct description and an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0c31fb5-6109-2669-a774-9f8872dcb85a
* Version Independent ID: 0b44b31b-b4ab-7334-c4a1-3fa61af31633
* Content: [Get-SPOMultiGeoExperience (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spomultigeoexperience?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoExperience.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoExperience.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
