### ISSUE TITLE
Get-SPOSiteCollectionAppCatalogs - No synopsis

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4603]
This CmdLet lacks a correct synopsis and parameter description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65032574-5c85-3825-5b4f-6ba2456dfec9
* Version Independent ID: 15c5736a-088c-9b72-b3ba-a4cb143efff7
* Content: [Get-SPOSiteCollectionAppCatalogs (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositecollectionappcatalogs?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteCollectionAppCatalogs.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteCollectionAppCatalogs.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
