### ISSUE TITLE
Get-SPOSiteDataEncryptionPolicy  - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4604]
This CmdLet lacks a correct synopsis, description and an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0770753b-b15c-2721-f340-7056485134ea
* Version Independent ID: 0afba921-7134-49e9-fb8a-6ce313bdfd7f
* Content: [Get-SPOSiteDataEncryptionPolicy (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositedataencryptionpolicy?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteDataEncryptionPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteDataEncryptionPolicy.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
