### ISSUE TITLE
get-spounifiedgroup - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4606]
This CmdLet lacks a correct synopsis, description and an example.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c05f05b1-8065-b304-1c66-39fe957894aa
* Version Independent ID: 1721f1c2-30ae-8f4d-56ba-6051dd58ac99
* Content: [Get-SPOUnifiedGroup (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spounifiedgroup?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroup.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
