### ISSUE TITLE
Get-SPOUnifiedGroupMoveState - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4607]
This CmdLet lacks a correct synopsis, description and an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3e6cf2-0bc6-6bc7-8d95-6a52e058fbf1
* Version Independent ID: 19beb409-12f6-95a7-ee41-04ef979904b4
* Content: [Get-SPOUnifiedGroupMoveState (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spounifiedgroupmovestate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroupMoveState.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroupMoveState.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
