### ISSUE TITLE
New-SPOMigrationEncryptionParameters - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4608]
This CmdLet lacks a correct synopsis, description and an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81307cf5-b7ce-be72-ef31-5171cd46024d
* Version Independent ID: c24ed4ba-f550-4267-0f08-6ab17d3d3667
* Content: [New-SPOMigrationEncryptionParameters (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/new-spomigrationencryptionparameters?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/New-SPOMigrationEncryptionParameters.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/New-SPOMigrationEncryptionParameters.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
