### ISSUE TITLE
Register-SPODataEncryptionPolicy - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4609]
This CmdLet lacks a correct synopsis, description and an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a15badae-030e-173a-4433-118ddf8841a9
* Version Independent ID: 799897d3-ebb0-6e13-c163-98de1a94d909
* Content: [Register-SPODataEncryptionPolicy (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/register-spodataencryptionpolicy?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Register-SPODataEncryptionPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Register-SPODataEncryptionPolicy.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
