### ISSUE TITLE
Remove-SPOMultiGeoCompanyAllowedDataLocation  - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4610]
This CmdLet lacks a correct synopsis, description and an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 729e0653-0e49-6043-fab4-314902cc0860
* Version Independent ID: b3aedf63-c316-6f79-c883-5fa25c121318
* Content: [Remove-SPOMultiGeoCompanyAllowedDataLocation (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spomultigeocompanyalloweddatalocation?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOMultiGeoCompanyAllowedDataLocation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOMultiGeoCompanyAllowedDataLocation.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
