### ISSUE TITLE
Remove-SPOSiteUserInvitations - No synopsis and description given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4611]
This CmdLet lacks a correct synopsis and description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 074a913a-6f98-c246-6873-7e7a98a03ac5
* Version Independent ID: eb201d27-2802-0fbc-7a6b-560c2e3381bd
* Content: [Remove-SPOSiteUserInvitations (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spositeuserinvitations?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteUserInvitations.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteUserInvitations.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@trent-green Please help us with you comment. Thanks

**Comment by tseward** [comment]
@andikrueger from my research, the *-SPOSiteUserInvitations appear to not function, looking into it more.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @andikrueger 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
