### ISSUE TITLE
Restore-SPODataEncryptionPolicy - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4612]
This CmdLet lacks a correct synopsis, description, an example and parameter descriptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f222848e-cf73-4b17-b407-176046075b71
* Version Independent ID: 255bffbe-a565-810b-7b5e-d1330d1668b9
* Content: [Restore-SPODataEncryptionPolicy (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/restore-spodataencryptionpolicy?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Restore-SPODataEncryptionPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Restore-SPODataEncryptionPolicy.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@trent-green Please help us with you comment. Thanks

**Comment by yogkumgit** [comment]
@andikrueger Thank you for reporting this feedback here. This list is focused on content issues and I want to make sure your immediate product issue does not get lost in this list. If you would please open a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
