### ISSUE TITLE
Set-SPOBrowserIdleSignOut - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4613]
This CmdLet lacks a correct synopsis, description and an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5a88408-7f59-1401-4170-7bb49a2db027
* Version Independent ID: 00e03653-1983-a0ba-69c7-61ad80b4245a
* Content: [Set-SPOBrowserIdleSignOut (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spobrowseridlesignout?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBrowserIdleSignOut.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBrowserIdleSignOut.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
