### ISSUE TITLE
Set-SPOBuiltInDesignPackageVisibility - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4614]
This CmdLet lacks a correct synopsis, description, parameter descriptions and an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5932378e-5168-513c-b241-f539f1004b0c
* Version Independent ID: b170a567-8988-aea2-f65e-23b9e01fe019
* Content: [Set-SPOBuiltInDesignPackageVisibility (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spobuiltindesignpackagevisibility?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInDesignPackageVisibility.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInDesignPackageVisibility.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
