### ISSUE TITLE
Set-SPOHomeSite  - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4615]
This CmdLet lacks 
- a correct synopsis
- description 
- parameter descriptions
- an example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 795cb31c-d0fb-fe85-6998-485f0477fed6
* Version Independent ID: 32ad4828-07df-cd7e-cc76-f82f4a573d39
* Content: [Set-SPOHomeSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spohomesite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHomeSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHomeSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
