### ISSUE TITLE
Set-SPOMultiGeoCompanyAllowedDataLocation - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4616]
This CmdLet lacks 
- a correct synopsis
- description 
- parameter descriptions
- an example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5774c443-b0cb-a0b7-c116-ee196a536528
* Version Independent ID: 301e8a08-2659-fdba-3a98-ada9992c0a2f
* Content: [Set-SPOMultiGeoCompanyAllowedDataLocation (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spomultigeocompanyalloweddatalocation?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMultiGeoCompanyAllowedDataLocation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMultiGeoCompanyAllowedDataLocation.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
