### ISSUE TITLE
Set-SPOMultiGeoExperience - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4617]
This CmdLet lacks 
- a correct synopsis
- description 
- parameter descriptions
- an example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df68eb5b-d8b9-f8fa-7434-dfec6b5c456c
* Version Independent ID: 39bfe65b-ae44-2d4b-18ed-c30a404d6d4f
* Content: [Set-SPOMultiGeoExperience (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spomultigeoexperience?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMultiGeoExperience.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMultiGeoExperience.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
