### ISSUE TITLE
Set-SPOUnifiedGroup - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4618]
This cmdLet lacks 
- a correct synopsis
- description 
- parameter descriptions
- an example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62578c9d-40f1-3979-76fa-54cc0405f86b
* Version Independent ID: d1f2ce2c-8e0b-0cad-4c40-e796bab74e2d
* Content: [Set-SPOUnifiedGroup (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spounifiedgroup?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUnifiedGroup.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
