### ISSUE TITLE
Set-SPOWebTheme - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4619]
This cmdLet lacks 
- a correct synopsis
- description 
- parameter descriptions
- an example
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100dca27-8fd7-2646-91d2-dbfbb55e6720
* Version Independent ID: 91a4ab51-7e7d-2800-4739-cc68835c4e0f
* Content: [Set-SPOWebTheme (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spowebtheme?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOWebTheme.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOWebTheme.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
