### ISSUE TITLE
Update-UserType - No synopsis, description and example given

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4622]
This cmdLet lacks 
- a correct synopsis
- description 
- parameter descriptions
- an example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fcad0b0-b70b-62b4-17ae-3529ca4f5a31
* Version Independent ID: 5b8b7059-51ee-4a0d-1a70-089e6e713cdf
* Content: [Update-UserType (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/update-usertype?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Update-UserType.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Update-UserType.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
