### ISSUE TITLE
Not enough details provided

### ISSUE THREAD

**Issue by Gideon122** [MicrosoftDocs/office-docs-powershell#4624]
The descriptions for the various parameters doesn't state whether the parameters are mandatory (required) or not.  I also agree with andikrueger's observations about missing information.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a15badae-030e-173a-4433-118ddf8841a9
* Version Independent ID: 799897d3-ebb0-6e13-c163-98de1a94d909
* Content: [Register-SPODataEncryptionPolicy (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/register-spodataencryptionpolicy?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Register-SPODataEncryptionPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Register-SPODataEncryptionPolicy.md)
* Service: **sharepoint-powershell**
* GitHub Login: @
* Microsoft Alias: ****

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@trent-green can you help me getting the missing information from the product team? Thank you 👍

**Comment by tseward** [comment]
@Gideon122 the Required is present in each Parameter description but is just not showing up on the docs.msft.com site itself. I've asked the team that handles the parser to look into this issue. If you view the markdown in GitHub, you'll see the Required parameter is present.

**Comment by yogkumgit** [comment]
@tseward  and @get-itips Thank you very much for the contribution and updating the documentation with PR. @Gideon122 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
