### ISSUE TITLE
Deprecated syntax

### ISSUE THREAD

**Issue by James-Noble** [MicrosoftDocs/office-docs-powershell#4625]
Example 2 uses incorrect syntax "Get-PnPNavigationNode -QuickLaunch", this should be "Get-PnPNavigationNode -Location QuickLaunch"

Examples 3 and 4 use deprecated syntax - the parameters Location and Title are no longer in the document.  It would be useful if these examples were replaced with one that performs the same job of removing a node with a specific Title, since this is a common task.  I believe the easiest way to do that now is:

Get-PnPNavigationNode -Location QuickLaunch | Where-Object { $_.Title -eq "Home" } | Remove-PnPNavigationNode -Force

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53df4ad8-9006-4d5c-8829-a1c481dac939
* Version Independent ID: 15dfc257-8c5f-63d6-ffe7-f7a7163c25bf
* Content: [Remove-PnPNavigationNode (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpnavigationnode?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPNavigationNode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPNavigationNode.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @James-Noble 
How are you? I need to kindly redirect you to this [other repo](https://github.com/SharePoint/PnP-PowerShell/) to file issues about PnP PowerShell, as you might know, PnP cmdlets are community-driven, a member of the community will pick your issue there and handle it.
Thank you

**Comment by James-Noble** [comment]
I went to the other repo you mentioned, clicked on documentation and the only thing there was was a link back to docs.microsoft.com :)
So I had a bit of further digging around and finally managed to find this:
https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Navigation/RemoveNavigationNode.cs
Presumably I should report the issue on that file since I can't report it on the documentation itself, which is hosted here?

**Comment by get-itips** [comment]
Hello @James-Noble 
Please use [this link](https://github.com/SharePoint/PnP-PowerShell/issues/new) to open the new issue on that repo.
Documentation for PnP cmdlets is directly reflected from PnP cmdlets source code, so yes, that is the place 👍 
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @James-Noble 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
