### ISSUE TITLE
Security Issue?

### ISSUE THREAD

**Issue by Gideon122** [MicrosoftDocs/office-docs-powershell#4627]
I just installed the EXO V2 module.  When I launch it, I'm immediately greeted with the following warning:

Due to a security issue, this version of client module will be deprecated and stop working after 8 Jan, 2020. Please update to latest version on or after 8 Jan, 2020.

I ran the Update-Module -Name ExchangeOnlineManagement command, but I still receive that warning.

Why is that warning being presented?  The way that warning reads, this module will stop working on Jan 9 (five days away as of the writing of this feedback), unless I update only on or after Jan 8th.  Is that correct?  If so, I'd love to know what the justification is for such a stupid requirement to update.  Why can't the update be performed now?

There is also no information provided regarding what the security issue is.  A link would have been helpful to get more information around this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Gideon122, thank you for your feedback.

@chrisda could you kindly help here?

I have been seeing this warning for 1 o 2 weeks.

**Comment by chrisda** [comment]
@Gideon122, as described in the topic, direct any questions or comments regarding the V2 module to exocmdletpreview[at]service[dot]microsoft[dot]com.

Thanks for the feedback.
