### ISSUE TITLE
Example 1

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#4628]
The **Use the Exchange Online PowerShell V2 module** article shows two different ways how to connect to ExchangeOnline V" module - one for **Accounts without MFA enabled** and another for **Accounts with MFA enabled** (Source: [Connect to Exchange Online using the EXO V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#connect-to-exchange-online-using-the-exo-v2-module)).

**Accounts without MFA enabled:**
`Connect-ExchangeOnline -Credential $UserCredential -ShowProgress $true`
**Accounts with MFA enabled:**
`Connect-ExchangeOnline -UserPrincipalName <UPN> -ShowProgress $true`

In my opinion, one of the major benefits of the Exchange Online PowerShell V2 module is the ease of connecting with MFA enabled accounts. Therefore may add this option as a 2nd example to this article as well: [Connect-ExchangeOnline > Examples](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/connect-exchangeonline?view=exchange-ps#examples)
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28f6554b-4d67-06d3-7926-1b958653872f
* Version Independent ID: 7a6a1737-afdf-dfd5-67f8-64aa6758ccc4
* Content: [Connect-ExchangeOnline (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/connect-exchangeonline?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda  please merge the PR #4634

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @Markus-Hanisch Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
