### ISSUE TITLE
Get-EXOMailbox - Select-Object PipelineStoppedException

### ISSUE THREAD

**Issue by mikeburns7** [MicrosoftDocs/office-docs-powershell#4629]
When running the command:
`Get-EXOMailbox -Resultsize Unlimited | Select-Object -First 3`

The results are returned but a terminal error is presented: 

`Get-EXOMailbox : The pipeline has been stopped.`
`At C:\Users\mikeb\Documents\Untitled1.ps1:3 char:2`
`+  Get-EXOMailbox -Resultsize Unlimited  | Select-Object -First 3`
`+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
 `   + CategoryInfo          : ProtocolError: (:) [Get-EXOMailbox], PipelineStoppedException`
    + FullyQualifiedErrorId : The pipeline has been `
 `stopped.,Microsoft.Exchange.Management.RestApiClient.GetExoMailbox`

This prevents a script from continuing to run.
If you run this same query using the traditional 'Get-Mailbox' command, no error is returned.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @mikeburns7, thank you for your feedback.

Same issue: https://github.com/MicrosoftDocs/office-docs-powershell/issues/4448

Please in this case provide your feedback to exocmdletpreview@service.microsoft.com as Exchange PowerShell Module V2 is on preview and you cannot open a support case.
Docs.microsoft.com feedback is there to help to improve documentation.

Thank you!

**Comment by yogkumgit** [comment]
@dariomws306   Thank you very much for the contribution and sharing this explanation. @mikeburns7 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by tudorh** [comment]
This is still an active issue and it should be handled.
