### ISSUE TITLE
SimpleName maximum string

### ISSUE THREAD

**Issue by dannydpa** [MicrosoftDocs/office-docs-powershell#4632]
The SimpleName maximum string quote 'This string can be up to 256 characters' long seems to be incorrect as I get an error in my Tenant when I exceed 49 characters similar as with Identity.  Error message I receive "Maximum SimpleName length cannot exceed 49..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f725c742-6988-ffc1-9945-e8c7f131ce6c
* Version Independent ID: b2b7f60a-4cab-e495-5360-f02018ab8316
* Content: [New-CsTenantDialPlan (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cstenantdialplan?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsTenantDialPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTenantDialPlan.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @dannydpa thanks for noticing and reporting.
Created a pull request to correct the article, as I could repro in my lab.

**Comment by yogkumgit** [comment]
@tomkau Please merge the PR #4642

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @dannydpa Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dannydpa** [comment]
Thank you for the quick response and fix. This is helpful for me.
