### ISSUE TITLE
1st Step

### ISSUE THREAD

**Issue by Chad-Campus** [MicrosoftDocs/office-docs-powershell#4635]
Can the 1st step to be make sure you have the Teams Module installed for Powershell?  Very hard to connect when you do not have the Module installed.

Install-Module -Name MicrosoftTeams

https://www.powershellgallery.com/packages/MicrosoftTeams/1.0.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ee082c9-735d-3f8a-7bc4-b2d4f175c784
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Chad-Campus thanks for your feedback, I created a pull request to propose adding a link to download the module. If it gets approval, it will be reflected on the article. Thank you again

**Comment by yogkumgit** [comment]
@kenwith Please merge the PR #4670 Thanks

**Comment by kenwith** [comment]
Merged.
