### ISSUE TITLE
Confusing wording

### ISSUE THREAD

**Issue by andrewbeaumont** [MicrosoftDocs/office-docs-powershell#4636]
The following statement is confusing:

"In coexistence environments with Exchange 2010 and newer versions of Exchange, don't run newer versions of Remove-MoveRequest to clear completed Exchange 2010 move requests as documented in Clear or Remove Move Requests. If you do, you could delete the mailbox that you just moved. Instead, only use the Exchange 2010 version of Remove-MoveRequest to clear completed Exchange 2010 move requests in coexistence environments."

Changing to something similar to be will ensure the statement is precise:

"In coexistence environments with Exchange 2010 and newer versions of Exchange, don't run newer versions of Remove-MoveRequest to clear completed move requests of mailboxes between Exchange 2010 databases, as documented in Clear or Remove Move Requests. If you do, you could delete the mailbox that you just moved. Instead, only use the Remove-MoveRequest cmdles on an Exchange 2010 server to clear completed Exchange 2010 move requests in coexistence environments. For mailbox moves from an Exchange 2010 database to Exchange 2016 database, the cmdlet can safely be run from the Exchange 2016 server."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1ee6a14-3045-1e8f-91e5-bc7d75519fba
* Version Independent ID: dfc2937b-7a4d-ab7b-8ac6-8532f693ad5f
* Content: [Remove-MoveRequest (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/remove-moverequest?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/Remove-MoveRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/Remove-MoveRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@andrewbeaumont OK. Done. In the future, you can also modify the topic directly without opening an Issue first. See https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md for details.

Thanks for the feedback.
