### ISSUE TITLE
Wording change

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/office-docs-powershell#4638]
The document applies to SFB 2019, but the first line in the document says 2015 and earlier. Needs clarification.

"Returns information about all the users in your organization who have been enabled for Skype for Business Server 2015 or a previous version of the software. This cmdlet was introduced in Lync Server 2010."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04a4a893-ff38-930b-20e5-31231b1859a7
* Version Independent ID: 53c97d7c-8c81-5387-011c-2aa97d64fe4e
* Content: [Get-CsUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@hirenshah1 Please merge the PR #4671 Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @jantoney Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
