### ISSUE TITLE
Private channels PREVIEW

### ISSUE THREAD

**Issue by RikardStrand** [MicrosoftDocs/office-docs-powershell#4639]
Where can I request to be part of the Private Preview for "-MembershipType" switch ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd44b411-4b59-b90f-0b82-ad0a87652854
* Version Independent ID: 2c52cc4e-47a1-be0d-8860-1011adf061fd
* Content: [New-TeamChannel (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-teamchannel?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/New-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @RikardStrand How are you ?
We do not have that information here, I would recommend contacting your account manager in that case to find out how you can proceed. I am sorry I can not help you with more info on that.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for this comment. @RikardStrand  If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
