### ISSUE TITLE
Time required to update signature?

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/office-docs-powershell#4641]
I have added a new domain (for marketing) to our SPF record and need to force update of our DKIM Signature.  How long does this take?  I have read all documents and nowhere does it tell us how long AUTOMATIC is done?  (every 4 days?) and how long does it take if we manually execute this?  Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd23aab2-5378-59a2-951f-3d808871f872
* Version Independent ID: fef7c224-f830-5056-685d-c2b61ec22c6c
* Content: [Rotate-DkimSigningConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/rotate-dkimsigningconfig?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Rotate-DkimSigningConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Rotate-DkimSigningConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Karr, thank you for your feedback.

Did you check this article?
https://blogs.msdn.microsoft.com/tzink/2015/10/30/how-office-365-does-automatic-dkim-key-rotation/

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and sharing this explanation. @Karr 
Hope you checked the suggested link and is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
