### ISSUE TITLE
How to demote an Owner to Member?

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/office-docs-powershell#4645]
Is there a corresponding PowerShell method to demote an Owner to Member?

Logically the following should work, correct?
Add-TeamChannelUser -GroupId &lt;group_id&gt; -DisplayName "&lt;channel-name&gt;" -User &lt;UPN&gt; -Role Member

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74381d05-2e95-4751-4285-752a46eb025f
* Version Independent ID: 2481b258-b593-e323-90f0-e9ca6e7797bf
* Content: [Add-TeamChannelUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @HandyAndyOnGitHub 
Please see the documentation for [Remove-TeamChannelUser](https://docs.microsoft.com/en-us/powershell/module/teams/remove-teamchanneluser?view=teams-ps)

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @HandyAndyOnGitHub Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
