### ISSUE TITLE
2048-bit RSA DKIM keys are now supported

### ISSUE THREAD

**Issue by rhymeswithmogul** [MicrosoftDocs/office-docs-powershell#4653]
Your documentation needs to be updated.  I discovered accidentally that you can use -KeySize 2048 to create a strong DKIM key with this cmdlet.  It should be noted, however, that Ed25519 keys are not yet supported; only RSA ones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc7677b-b991-5569-3dfc-eed6476c9689
* Version Independent ID: 984ee7a6-2a9d-771c-1b94-89a9be45c79e
* Content: [New-DkimSigningConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/New-DkimSigningConfig?redirectedfrom=MSDN&view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/New-DkimSigningConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/New-DkimSigningConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@rhymeswithmogul OK. Done. Note that you, too, can update the topic without having to file an Issue first. For more information, see https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md.

Thanks for the feedback.
