### ISSUE TITLE
How do you connect to Exchange Online using certificate-based authentication?

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/office-docs-powershell#4655]
We have customers who use MFA who would like to use our product that manages Exchange Online via PowerShell with unattended scripts, but they cannot disable MFA. According to https://docs.microsoft.com/en-us/office365/enterprise/office-365-client-support-certificate-based-authentication#supported-powershell-modules, the Exchange Online PowerShell module supports CBA, but I have looked and looked and can't find any other documentation describing how to connect to Exchange Online PowerShell using a registered application and Certificate-based authentication. Can you please flush out the documentation to describe how this is done? MFA/interactive use is only half of the story (and when it comes to automation, it's actually the less important half of the story).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by navgupta1208** [comment]
Hi Kirk

This feature is a work in progress and will be available in a quarter from now.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by KirkMunro** [comment]
Thank you for the fast reply @navgupta1208. This is a very important feature for the Microsoft partner organization that I work with. Will there be preview releases for the forthcoming update that includes CBA support that I could be looped into through a customer connection program, or our partner relationship? I believe it would be mutually beneficial, so that we can make sure it suits the large-scale unattended automation needs that our customers have.

**Comment by KirkMunro** [comment]
@navgupta1208: With the upcoming feature for Exchange, will they support managed identity authentication as well?

Any any response to my last request?

**Comment by dariomws306** [comment]
Hi @KirkMunro, thank you for your feedback.

@chrisda @navgupta1208 could you add something else here? Thanks in advance!

**Comment by navgupta1208** [comment]
Here is the version released privately where this feature is available -
https://www.powershellgallery.com/packages/ExchangeOnlineManagement/0.3527.1

This will be available for wider public starting nextweek.

**Comment by yogkumgit** [comment]
@navgupta1208  and @dariomws306  Thank you very much for the contribution and sharing this explanation. @KirkMunro Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by KirkMunro** [comment]
@navgupta1208 Thank you for sharing that private release. I downloaded this update shortly after your reply 9 days ago, and have started looking at it, but it doesn't seem to include any changes to the `Connect-ExchangeOnline` function. I've performed a file comparison between the old and the new modules, and sure enough, there are no new parameters for this function, so I don't see how this module includes support for certificate-based authentication?

Also, closer inspection of the module raises a few questions about the design, not because it's wrong, but because I'm trying to understand why you're doing things the way they currently are being done:

1. You are not exporting your functions, and instead you define some of the functions that you want exported as global in the script module. Why don't you simply invoke `Export-ModuleMember` for the functions that you want exported instead of declaring them global? And what are you doing to clean up those global functions when the module is removed? There doesn't appear to be any PowerShell code to handle that, so are you doing custom work in a binary module for cleanup?
1. You define a bunch of global variables. Is that really necessary? Why not just define those variables in script scope and reference them from there?

Thank you.

**Comment by smpettit** [comment]
I too would like to get clarification on the certificate-based authentication capability. We need this in order to be able to use this module within Azure Automation. To meet the new partner security requirements we need to be able to authenticate with a certificate as a service principal and use that to reach delegated organisations.

**Comment by dariomws306** [comment]
Hi @KirkMunro and @smpettit,

Please to report bugs or issues, or request features for the "Exchange Online PowerShell V2 module" send you inquiries to:
exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam)
As it's explained in the article. Is the best way to reach the team working on this module.

Thanks!

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @KirkMunro 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dariomws** [comment]
@KirkMunro CBA will be supported. More information:
https://techcommunity.microsoft.com/t5/exchange-team-blog/faster-and-more-reliable-exchange-online-management-using/ba-p/1198604

**Comment by sukh-ava** [comment]
Any update on this. If there is preview release will be happy to test pilot this. We cant use the V2 module in our automations unless we get CBA.

**Comment by dariomws** [comment]
Hi @sukh-ava,

I don´t have more information but can suggest that you follow the Exchange blog to stay up to date about this feature:
https://techcommunity.microsoft.com/t5/exchange-team-blog/bg-p/Exchange

**Comment by navgupta1208** [comment]
@sukh-ava @KirkMunro 

CBA is in limited preview. Please reach out to the feedback alias mentioned when you do Connect-ExchangeOnline and we will add you to the preview.
