### ISSUE TITLE
service defaults?

### ISSUE THREAD

**Issue by jadesolis** [MicrosoftDocs/office-docs-powershell#4656]
"The default value is 0, which means the service defaults are used" where exactly are these service defaults defined?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465aff8b-94d1-258b-0558-a35f2261fc0b
* Version Independent ID: 3b7917f1-4d63-e881-5653-4fc4ac84038a
* Content: [Set-HostedOutboundSpamFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/set-hostedoutboundspamfilterpolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedOutboundSpamFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedOutboundSpamFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @jadesolis, thank you for your feedback.

For more information, see [Sending limits across Office 365 options](https://docs.microsoft.com/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#sending-limits-across-office-365-options).

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @jadesolis 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
