### ISSUE TITLE
WithRightsAssigned Flag Is Making Incorrect Assumptions

### ISSUE THREAD

**Issue by teekayzee** [MicrosoftDocs/office-docs-powershell#4657]
Comment in code:
// If they're in a SharePoint Group, they always have some kind of access rights, so add them all

This isn't the case all the time as there can be SharePoint Groups that aren't used anywhere on a site/list/web etc.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by teekayzee** [comment]
-WithRightsAssigned
If provided, only users that currently have any kinds of access rights assigned to the current site collection will be returned.

Resource: https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpuser?view=sharepoint-ps

**Comment by get-itips** [comment]
Hello @teekayzee 
Thanks for your feedback.
For PnP Issues I need to kindly redirect you to this [other resource](https://github.com/SharePoint/PnP-PowerShell), to file an issue there, as you might know, PnP is community driven, a member of that community will follow up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @teekayzee 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
