### ISSUE TITLE
Module bug

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/office-docs-powershell#4664]
Cannot set domain guids. Get the error below but works in GUI. Module version 16.0.19515.12000

Set-SPOTenantSyncClientRestriction : The property or field 'IsUnmanagedSyncClientForTenantRestricted' has not been initialized. It has not been requested or the request has
not been executed. It may need to be explicitly requested.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e353a8a-e20f-f52b-7a30-8477c50453c9
* Version Independent ID: d4e6657b-9c9b-60c2-db4b-0f0d663f2935
* Content: [Set-SPOTenantSyncClientRestriction (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenantsyncclientrestriction?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantSyncClientRestriction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantSyncClientRestriction.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @stephenc01 
I could set domain guids using that cmdlet with no issues

![image](https://user-images.githubusercontent.com/36666927/72549358-2a862a00-3856-11ea-858a-44a97d2035fc.png)

were you trying to remove this configuration and received that error maybe?
If that is the case, you can use Remove-SPOTenantSyncClientRestriction to make TenantRestrictionEnabled false again.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @stephenc01 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
