### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/office-docs-powershell#4667]
"You need to be assigned permissions in the Office 365 Security & Compliance Center before you can use this cmdlet. For more information, see Permissions in Office 365 Security & Compliance Center." 

Which "permissions" are needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5c7d2a3-15f1-c4d1-1431-55fa62b914ee
* Version Independent ID: 00316a3a-790d-873c-d6b0-ff4dbb566651
* Content: [Get-RetentionCompliancePolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-retention/get-retentioncompliancepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-retention/Get-RetentionCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-retention/Get-RetentionCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @eschrader, thank you for your comment.

You need to check this article to understand what permissions you need to do different operations under Security & Compliance Center:
https://docs.microsoft.com/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center

In this case, you need at least View-Only Retention Management role.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @eschrader 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
