### ISSUE TITLE
No Documentation of Copy-PnPItemProxy

### ISSUE THREAD

**Issue by divyankraj** [MicrosoftDocs/office-docs-powershell#4669]
[Enter feedback here]
There is no Documentation Provided for Copy-PnPItemProxy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f44eceb-fe0e-0ce3-0152-42aa70d97546
* Version Independent ID: 96323849-f655-92c6-bead-b5b054ce0044
* Content: [Copy-PnPItemProxy (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/copy-pnpitemproxy?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Copy-PnPItemProxy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Copy-PnPItemProxy.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @divyankraj 
Thanks for your feedback.
For PnP Issues I need to kindly redirect you to this [other resource](https://github.com/SharePoint/PnP-PowerShell), to file an issue there, as you might know, PnP is community driven, a member of that community will follow up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @divyankraj 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
