### ISSUE TITLE
Problem with Exchange Online v2 Powershell module

### ISSUE THREAD

**Issue by Marcin137** [MicrosoftDocs/office-docs-powershell#4674]
I'm trying to use the new EXO Powershell module in my function, which returns some data. Unfortunately the result returned by the function is overwritten by the object returned during creating PSSession, when connecting to Exchange Online occurs. In the "classical" approach, you could "Out-Null" the result in the Import-PSSession command - here, with Connect-ExchangeOnline cmdlet, it doesn't work. Do you have any idea how can I resolve this issue? 

Best Regards
Marcin

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Marcin137, thank you for your feedback.

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, please contact them at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @Marcin137 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
