### ISSUE TITLE
Where is: AllowedDomainsAsAList

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#4675]
Hi,

Where is the definition for "-AllowedDomainsAsAList" ?`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c71fa24-f273-98ff-c0c6-ce9e5488e7c2
* Version Independent ID: 1ef8e42a-4405-5e99-b2ac-547d60b53a70
* Content: [Set-CsTenantFederationConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Petri-X 
Created a pull request to propose improving the article with the missing information about the parameter. Hopefully, it will be merged.
Thanks for noticing.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Petri-X Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
