### ISSUE TITLE
Duplicate records from API

### ISSUE THREAD

**Issue by eclay1819** [MicrosoftDocs/office-docs-powershell#4677]
When using the PowerShell cmdlet or exporting from the UI, there are duplicate records in the output. I can't find any reference to this behavior in the documentation.

Sample code below - I have reproduced this using the ReturnNextPreviewPage session command with resultsize of 5000 and no paging as well on a different date range. When exporting to CSV from the Security and Compliance page, there are duplicate records in the csv as well.

According to this, the Id in the audit data should be unique:
https://docs.microsoft.com/en-us/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log

The only source I could find that corroborates this behavior is Page 548 of *Mastering Microsoft Power BI: Expert Techniques for Effective Data Analytics and Business Intelligence* By Brett Powell

> 2. An ETL (or ELT) process is executed to access the CSV file and load the new data to a data source:
	The results of each audit log search can contain duplicate rows. However, the Identity column included in the search results can be included to eliminate these duplicate rows.
	
    $AuditData = New-Object System.Collections.ArrayList
    $Results = $true
    
    #Returns 49,479 records via paging and adds the audit data to an array list
    while ($Results) {
       $Results = Search-UnifiedAuditLog -StartDate (Get-Date "11/4/2019 00:00:00") -EndDate (Get-Date "12/10/2019 00:00:00") -Formatted -RecordType PowerBIAudit -SessionCommand ReturnLargeSet -ResultSize 5000 -SessionId "MyVeryUniqueSessionId"
       $Results | ForEach-Object {$null = $AuditData.Add($_.AuditData)}
    }
    
    #Shows that there are 661 non-unique Ids in the audit data - a total of 1390 non-unique records
    $AuditData | Group-Object Id | Where-Object {$.Count -gt 1} | Select Count, Name | Sort Count -Descending

 If this behavior is expected, then it should be documented and a brief example of how to filter those results should be provided. Example code below, though I'm sure there are a few other ways to do this:

    $AuditData | Sort-Object Id -Unique

Edit: Small typo in the foreach-object loop ($.AuditData updated to $_.AuditData)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by kenwith** [comment]
@ev1819 thank you for submitting this feedback. I will have to loop in @chrisda who works on the security and compliance center on how best to take action. @chrisda maybe this information would be better in the reference content for security and compliance center? Thoughts?

**Comment by chrisda** [comment]
@ev1819, are you absolutely sure the duplicate rows are identical to each other in all respects? If so, you should file a support case to find out what's going on.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and sharing this explanation. @ev1819 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

https://docs.microsoft.com/office365/admin/contact-support-for-business-products

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by eclay1819** [comment]
@chrisda @yogkumgit I submitted a support ticket, and this behavior was confirmed to be working as designed. Ticket #18585233

Relevant excerpt:

> To give a quick update.  Product Engineering has stated the following. 
> 
> "It is by design. To avoid missing/losing any audit event, a event might be re-injected twice or more if it has faced any error, so customer could receive multiple copies of a event."

I would highly recommend updating the documentation to reflect this.

**Comment by get-itips** [comment]
@eclay1819 Evan, I will propose adding a note to the article, if @chrisda Chris decides to accept it, it will be reflected.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @eclay1819 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
