### ISSUE TITLE
Names of Cmdlets should not be translated

### ISSUE THREAD

**Issue by fheinicke** [MicrosoftDocs/office-docs-powershell#4682]
The issue is that names of certain cmdlets get automatically translated, tested for German language. Even though some results are funny, I think it should be fixed.

Examples:
- [Set-SPOUser for German](https://docs.microsoft.com/de-de/powershell/module/sharepoint-online/set-spouser?view=sharepoint-ps) -> `Gruppe-Ehegatte` (would be something like `Group-Spouse`).
- [Get-SPOUser](https://docs.microsoft.com/de-de/powershell/module/sharepoint-online/get-spouser?view=sharepoint-ps) -> `Get-Ehepartner`
- [Remove-SPOUser](https://docs.microsoft.com/de-de/powershell/module/sharepoint-online/remove-spouser?view=sharepoint-ps) -> `Remove-Ehegatte`

![grafik](https://user-images.githubusercontent.com/27764426/72435342-272f6780-379e-11ea-854c-37324888e4ad.png)

I found issue #1890 which seems to be related, but was closed 02-2019.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @fheinicke 
The issue has been fixed, thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the conformation. @fheinicke Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
