### ISSUE TITLE
Connect-sposervice exception on PowerShell 7

### ISSUE THREAD

**Issue by chhinton** [MicrosoftDocs/office-docs-powershell#4684]
When attempting to connect to SPO using connect-sposervice on PowerShell 7 RC1 (Windows) an exception is thrown.

Exception:
Connect-SPOService: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

Research led me to issue 3926 in the dotnet/core project [Please implement System.Security.Cryptography.SHA256Cng #3926](https://github.com/dotnet/core/issues/3926).

The closing comment on that issue is:

> We're intentionally keeping the CNG-specific named hashing types out. Using SHA256.Create() is the correct answer on all platforms (and also in .NET Framework).

It looks like the connect-sposervice module needs to be updated

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @chhinton 
As you said, Ps7 is still Release Candidate, so it is under development and prone to errors.
Other than that, I identify no documentation to be changed.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @chhinton 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by poortom1004** [comment]
Well, PS7 is now released to production as of last week but the error still exists.  I hate to say it but @chhinton did warn you guys.

**Comment by chhinton** [comment]
@poortom1004, I was optimistic that this group would be communication with the group that actually supports connect-sposervice.

**Comment by get-itips** [comment]
Hello @poortom1004 & @chhinton here, we are limited to documentation changes, we try to help everyone, said that, you can see here the official Ps 7 [compatibility status with other modules](https://aka.ms/PSModuleCompat) you can see there that SPO isn't still there.

You can also try the new parameter -UseWindowsPowerShell

**Comment by poortom1004** [comment]
The link on compatibility you provided only relates to modules written for Windows, managing Windows, and not anything else.  Just wanted to let you know this.

**Comment by get-itips** [comment]
> The link on compatibility you provided only relates to modules written for Windows, managing Windows, and not anything else. Just wanted to let you know this.

Hello Thomas. 
For a module to be compatible with PowerShell 7, the product group of that module must make it compatible to Ps 7 not the other way around. Said that, that is the list of current compatible modules.

**Comment by AspenForester** [comment]
Import the module explicitly and use the `-UseWindowsPowerShell` parameter.  I'm seeing success with it.

**Comment by chhinton** [comment]
@AspenForester That may work on Windows OS but not on the non-Windows OSs that Powershell 7 supports.

**Comment by get-itips** [comment]
Hello @chhinton 

This is the official announcement where you can be sure that they are working the compatibility of other modules.

> For those modules still incompatible, we’re working with a number of teams to add native PowerShell 7 support, including Microsoft Graph, Office 365, and more.

_Source_ https://devblogs.microsoft.com/powershell/announcing-powershell-7-0/

Once they become compatible we will be able to impact any documentation. As I do not recognize any documentation change to impact right now, we will proceed closing this for now. @yogkumgit please proceed. Thank you

**Comment by jdvuyk** [comment]
> Import the module explicitly and use the `-UseWindowsPowerShell` parameter. I'm seeing success with it.

This indeed works on windows.  but seems like a pretty insane requirement.

**Comment by AspenForester** [comment]
And here we are a year later, PowerShell at version 7.2.1, with the module updated to version 16.0.22208.12000, and it *still* doesn't work with PowerShell because it still depends on 'System.Security.Cryptography.SHA256Cng'.  I know this isn't a documentation problem, but the dev team kinda boned the documentation team by setting the "project home" attribute on PowerShell Gallery to this github repo.

**Comment by sunishissac** [comment]
> > Import the module explicitly and use the `-UseWindowsPowerShell` parameter. I'm seeing success with it.
> 
> This indeed works on windows. but seems like a pretty insane requirement.

It worked in 7.2 only after -UseWindowsPowerShell
