### ISSUE TITLE
Typo for argument 

### ISSUE THREAD

**Issue by danjpadgett** [MicrosoftDocs/office-docs-powershell#4688]
The argument is listed as -SkipFilesWithExtensions but is actually -SkipFilesWithExtension. Please extend this article with more information/examples - e.g. how -SkipFilesWithExtension should be used. 

i.e: -SkipFilesWithExtension "exe","ini" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 176873a5-a509-6337-0aa9-7db8ead2e863
* Version Independent ID: 73bb0f00-1909-6eb1-3a8c-247149480c9a
* Content: [Register-SPMTMigration (spmt)](https://docs.microsoft.com/en-us/powershell/module/spmt/register-spmtmigration?view=spmt-ps#feedback)
* Content Source: [spmt/spmt-ps/spmt/Register-SPMTMigration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/spmt/spmt-ps/spmt/Register-SPMTMigration.md)
* Service: **spmt-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@JarbasHorst  Thank you very much for the contribution and updating the documentation with PR. @danjpadgett Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
