### ISSUE TITLE
How to specify which command to import

### ISSUE THREAD

**Issue by TalismanM** [MicrosoftDocs/office-docs-powershell#4689]
How can I specify which command to import from a session when using the Connect-ExchangeOnline cmdlet? For example the Import-PSSession cmdlet has the _CommandName_ parameter.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @TalismanM, thank you for your feedback.

There is still no way to do it. The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, please contact us at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @TalismanM 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
