### ISSUE TITLE
Incorrect parameter in EXAMPE 3 and EXAMPLE 4 of Export-PnPTaxonomy PowerShell Cmdlet

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#4690]
Please replace "-TermSet" with "-TermSet**Id**" in **EXAMPLE 3** and **EXAMPLE 4** of [Export-PnPTaxonomy Examples section](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/export-pnptaxonomy?view=sharepoint-ps#examples)  as described in the [Syntax](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/export-pnptaxonomy?view=sharepoint-ps#syntax):

> `Export-PnPTaxonomy
>       [-TermSetId <GuidPipeBind>]
>                         [-TermStoreName <String>]
>                         [-Lcid <Int>]
>                         [-IncludeID [<SwitchParameter>]]
>                         [-Path <String>]
>                         [-Force [<SwitchParameter>]]
>                         [-Delimiter <String>]
>                         [-Encoding <Encoding>]
>                         [-Connection <SPOnlineConnection>]`

See my correction proposal below:

**------------------EXAMPLE 3------------------**

`Export-PnPTaxonomy -Path c:\output.txt -TermSetId f6f43025-7242-4f7a-b739-41fa32847254`
Exports the term set with the specified id

**------------------EXAMPLE 4------------------**

`Export-PnPTaxonomy -Path c:\output.txt -TermSetId f6f43025-7242-4f7a-b739-41fa32847254 -Lcid 1044`
Exports the term set with the specified id using Norwegian labels

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9187caf-5e67-8e30-1ede-aaa71c0a7b95
* Version Independent ID: 837a8373-78a5-b871-fee8-d3eb86acdeec
* Content: [Export-PnPTaxonomy (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/export-pnptaxonomy?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Export-PnPTaxonomy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Export-PnPTaxonomy.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit
