### ISSUE TITLE
Is there an easier way now?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/office-docs-powershell#4692]
This article is over 3 years old now.  Is there an easier way now to run Exchange PS commands other than downloading the Exchange management tools or running remote sessions? Especially now with Visual Studio Code?  Like, aren't there exchange modules to import like we can do with AD?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b57b66-2364-0e9d-e627-5eeb77238675
* Version Independent ID: 78fd7932-06f9-37c7-8928-250b3884d89e
* Content: [Connect to Exchange servers using remote PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/connect-to-exchange-servers-using-remote-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Canis-Lupis, thank you for your feedback.

There is no other way to run Exchange PowerShell commands other than Exchange Management Shell installed locally or a remote session.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @Canis-Lupis Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
