### ISSUE TITLE
Get-team returns only the teams for the current user.

### ISSUE THREAD

**Issue by cimares** [MicrosoftDocs/office-docs-powershell#47]
When I use the cmdlet get-teams, it only returns the teams for the current user context. As an Admin, I need to see ALL of the teams currently configured within the environment.

The cmdlet provides a -User parameter, but when this is used to provide a different user context by a Global Admin, the script returns an InvalidRequest with the message "This request is supported in current user context only"

**Comment by Jethro-Seghers** [comment]
that might explain some of my problems: Remove-Team doesn't remove team in the app. Removing the Team Members removes the team in PS -again not in App

**Comment by Jethro-Seghers** [comment]
How do we know if this is being addressed

**Comment by kenwith** [comment]
I will bring this to product team and get a response.

**Comment by nkramer** [comment]
Thanks, as mentioned in the documentation, Get-Team only returns info for the current user. We are working to address it.

Remove-TeamUser, along with many of the other commands, has a delayed effect. The AAD user info is updated immediately, but it can take up to an hour to propagate to other machines. This is not related to the Get-Team issue.

**Comment by kenwith** [comment]
Thanks for bringing this issue up and thanks for details Nick! This is logged with product team. Closing this out.

**Comment by joaovitorhr** [comment]
Hello

any solution to this problem? I am using the Teams module in the latest version and the "Get-Team -user" command always returns the Teams of the user logged in powershell and not the queried user.
