### ISSUE TITLE
Command output explanation

### ISSUE THREAD

**Issue by phoude** [MicrosoftDocs/office-docs-powershell#4700]
It would be nice to explain what the AssociatedHealthScoreCalculator should be interpreted

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df59a943-8abd-5f6f-592c-eba8bf4cdf11
* Version Independent ID: 424ec3ff-1559-8743-c4ff-a9958c482fed
* Content: [Get-SPWebApplicationHttpThrottlingMonitor (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spwebapplicationhttpthrottlingmonitor?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Get-SPWebApplicationHttpThrottlingMonitor.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Get-SPWebApplicationHttpThrottlingMonitor.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @phoude How are you?
Hope you are doing great.

The AssociatedHealthScoreCalculator values are "buckets" that SharePoint uses to calculate the Health Score, for example,

```
Category                        : ASP.NET
Counter                         : Requests Current
Instance                        :
AssociatedHealthScoreCalculator : [6.0,8.0,10.0,12.0,20.0,28.0,44.0,76.0,94.0,5
                                  00.0]
```

If in your environment currently you have 14 ASP.NET Requests, the Health Score will be 4.

You can change the way SharePoint calculates the Health Score thru the [Set-SPWebApplicationHttpThrottlingMonitor](Set-SPWebApplicationHttpThrottlingMonitor) cmdlet, and you also can find more information about mentioned buckets there.

Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @phoude 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
