### ISSUE TITLE
Example 2

### ISSUE THREAD

**Issue by PathToSharePoint** [MicrosoftDocs/office-docs-powershell#4702]
The second example uses a Get, this doesn't look right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46737df0-ab6e-0d27-55eb-ba9e97b67c26
* Version Independent ID: e4ab192f-19b8-584b-9962-7bcf8d55f807
* Content: [Grant-PnPSiteDesignRights (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/grant-pnpsitedesignrights?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Grant-PnPSiteDesignRights.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Grant-PnPSiteDesignRights.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @PathToSharePoint  Thanks for your feedback.
For PnP Issues I need to kindly redirect you to this [other resource](https://github.com/SharePoint/PnP-PowerShell), to file an issue there, as you might know, PnP is community driven, a member of that community will follow up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @PathToSharePoint Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by PathToSharePoint** [comment]
@get-itips @yogkumgit I am not sure to understand. 

I posted my feedback directly at the bottom of this page:
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/grant-pnpsitedesignrights

Why did it end up here then, if it is not the right place?

Just to be clear, what I was reporting is a documentation issue, not an issue with the code itself.

**Comment by get-itips** [comment]
> @get-itips @yogkumgit I am not sure to understand.
> 
> I posted my feedback directly at the bottom of this page:
> https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/grant-pnpsitedesignrights
> 
> Why did it end up here then, if it is not the right place?
> 
> Just to be clear, what I was reporting is a documentation issue, not an issue with the code itself.

@PathToSharePoint You did good, don't worry, It's just the way it is currently with this specific PnP documentation.
The documentation of the PnP articles is directly reflected in this repo from PnP source code, if you look into it, you will find the documentation inside every cmdlet.
That's the reason both PnP documentation issues and cmdlet issues need to be reported in the referenced repo.

Hope this information clarifies better. Thank you
