### ISSUE TITLE
Please include description of -DirectorySearchMethod 

### ISSUE THREAD

**Issue by JensTrier** [MicrosoftDocs/office-docs-powershell#4704]
This parameter is now available on this cmdlet. It can have None, ByName, ByExtension

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41021d0-e1fb-fbfc-2c54-a0041ca7cbab
* Version Independent ID: e145eba4-4363-a2c2-1528-f64c47f8208d
* Content: [New-CsAutoAttendantMenu (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csautoattendantmenu?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendantMenu.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsAutoAttendantMenu.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @JensTrier Thanks for noticing, created a pull request to add the missing parameter to the article.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @JensTrier Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
