### ISSUE TITLE
Get-SPOSite HubSiteId always returns 00000000-0000-0000-0000-000000000000

### ISSUE THREAD

**Issue by evlo** [MicrosoftDocs/office-docs-powershell#4705]
Get-SPOSite HubSiteId always returns 00000000-0000-0000-0000-000000000000 even for the sites where I can clearly see hub correctly set in web administration interface.

EDIT: ok now I see #4510 - this should be documented

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @evlo 
Yes, you found another past issue where the same question was asked, that is usually a behavior found independently of the Ps module used, generally speaking, when a lot of properties need to be retrieved.
@yogkumgit we can close this thread now.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @evlo 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by evlo** [comment]
"this should be documented" in my first post

**Comment by get-itips** [comment]
> "this should be documented" in my first post

@evlo hope you are doing great.
This is called "lazy properties" and is a standard behavior of, not only PowerShell, but we can find this behavior on almost all programming languages.

Found a definition for you in [another article](https://docs.microsoft.com/en-us/configmgr/develop/core/understand/configuration-manager-lazy-properties).

> Some Configuration Manager object properties are relatively inefficient to retrieve. If these properties were retrieved for many instances in a class (as might be done in a query), the response would be considerably delayed. Such properties are considered lazy properties and are not usually retrieved during query operations. However, if these properties are retrieved during a query, they have null or zero values, which might not be the actual value of the property for every instance. Therefore, if you want to get the correct value for lazy properties, you must get each instance individually.
