### ISSUE TITLE
Review Connect-ExchangeOnline Parameter "EnableEXoTelemetry"

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#4707]
The Microsoft documentation section [Use the Exchange Online PowerShell V2 module > Report bugs and issues](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#report-bugs-and-issues) containts the following PowerShell Cmdlet:

`Connect-ExchangeOnline -EnableEXoTelemetry -LogDirectoryPath <Path to store log file> -LogLevel All`

The above stated parameter **EnableEXoTelemetry** is not mentioned in the Microsoft documentation section [Connect-ExchangeOnline > Syntax](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/connect-exchangeonline?view=exchange-ps#syntax) (see below). 
> Connect-ExchangeOnline
>        [[-AzureADAuthorizationEndpointUri] <String>]
>        [-BypassMailboxAnchoring]
>        [[-ConnectionUri] <String>]
>        [-Credential <PSCredential>]
>        [[-DelegatedOrganization] <String>]
>        [-EnableErrorReporting]
>        [[-ExchangeEnvironmentName] <ExchangeEnvironment>]
>        [-LogDirectoryPath <String>]
>        [-PageSize <UInt32>]
>        [[-PSSessionOption] <PSSessionOption>]
>        [-ShowProgress <Boolean>]
>        [-TrackPerformance <Boolean>]
>        [-UseMultithreading <Boolean>]
>        [-UserPrincipalName <String>]
>        [<CommonParameters>]

I assume that the above mentioned code needs to be adjusted from

> `Connect-ExchangeOnline -EnableEXoTelemetry -LogDirectoryPath <Path to store log file> -LogLevel All`

to 
`Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4723

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @Markus-Hanisch Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
