### ISSUE TITLE
changed default behaviour

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/office-docs-powershell#4709]
the Show-CsClsLogging behaviour has changed for unknown reasons.  Since CU build .123, the default behaviour is now to just show the status of JUST the local machine, instead of every machine in the environment.  Not sure why this change happened, would certainly like to have it reverted back, and I'm guessing this is why there have been CLS logging issues every since.  

Rather than change the default behaviour, a new switch could have been added for -local or -localmachine or something... But now we've got to go hunting for each pool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0212a0-8c1a-c3fd-63d8-012e85fdb5aa
* Version Independent ID: f285d451-a80c-64c1-ffe3-e150caad445a
* Content: [Show-CsClsLogging (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/show-csclslogging?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Show-CsClsLogging.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Show-CsClsLogging.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Korbyn72 thanks for noticing, created a pr to propose an improvement to the article to reflect the current behavior.

**Comment by yogkumgit** [comment]
@hirenshah1 Please merge this PR #4923 Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Korbyn72 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
