### ISSUE TITLE
Querying and creating nested terms

### ISSUE THREAD

**Issue by arnieraju** [MicrosoftDocs/office-docs-powershell#4710]
This command is awesome for quickly checking whether a given nested term exists or not using the pipe band separated argument e.g. "Term Group|Term Set|Term Name|2nd Level Term Name|3rd Level Term Name".

From some quick testing, what is missing is the equivalent to create a new nested term via PowerShell using the same syntax.  The new-pnpterm allows us to create a new term, but being able to create a nested hierarchy is a little more involved.

Are there any plans to provide a similar approach for creating a term hierarchy using the New-PnPTerm command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c329267-93e2-cabb-4702-68eefd1b0e8e
* Version Independent ID: 484c3507-b2af-f5a9-23e4-2274a2d29459
* Content: [Get-PnPTaxonomyItem (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnptaxonomyitem?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTaxonomyItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTaxonomyItem.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by arnieraju** [comment]
FYI: Just took at quick look at the PnP-PowerShell project and found the following issue which looks related:  https://github.com/SharePoint/PnP-PowerShell/issues/1704

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @arnieraju  Thanks for your feedback.
For PnP Issues I need to kindly redirect you to this [other resource](https://github.com/SharePoint/PnP-PowerShell), to file an issue there, as you might know, PnP is community driven, a member of that community will follow up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @arnieraju 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
