### ISSUE TITLE
Set-OrganizationConfig -VisibleMeetingUpdateProperties Syntax

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#4711]
It took me quite some time to figure out the required syntax to set the **VisibleMeetingUpdateProperties** parameter.
**Example 6** to set the **VisibleMeetingUpdateProperties** parameter is a bit misleading because the value of this parameter needs to be set as solely one comma separated string value in double quotes. 
[Set-OrganizationConfig > Examples > Example 6](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-organizationconfig?view=exchange-ps#examples)
May use a more complex example to illustrate the required syntax for parameter **VisibleMeetingUpdateProperties** at a glance?

Replace
> **Example 6** 
> `Set-OrganizationConfig -VisibleMeetingUpdateProperties "Location:15"`
> In Exchange Online, this example results in meeting updates being auto-processed (meeting update messages aren't visible in attendee Inbox folders) except if the meeting location changes within 15 minutes of the meeting start time.

with 

**Example 6** 
`Set-OrganizationConfig -VisibleMeetingUpdateProperties "Location,Subject,Body,AllProperties:15"`
 In Exchange Online, this example results in meeting updates being auto-processed (meeting update messages aren't visible in attendee Inbox folders) except any changes to meeting location, subject and body as well as any property changes within 15 minutes of the meeting start time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3ab3f0-cc05-e279-8876-6da0b323bcac
* Version Independent ID: bfb49814-d60b-564a-25cc-f902dfa42b10
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@Markus-Hanisch, I used your example and updated the parameter description to clarify.

Thanks for the feedback.
