### ISSUE TITLE
More missing event types

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/office-docs-powershell#4712]
May we please have a refresh on available event types and their definitions?

AtpGoodMail, Expire (multiple Actions) and Receive (multiple Actions) events are several that are missing.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb20809-8f21-dfd3-23bf-bbfb82679619
* Version Independent ID: be54b158-1672-5ae9-6a6d-139a7850c67b
* Content: [Get-MailTrafficReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/reporting/get-mailtrafficreport?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/reporting/Get-MailTrafficReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/reporting/Get-MailTrafficReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @mrkeiths, thank you for your feedback.

@chrisda do you think we can get more detail about these three events? Thanks!

**Comment by yogkumgit** [comment]
@chrisda Please respond to this query. Thanks.

**Comment by jdrecklessworld** [comment]
event types needing complete definitions:

Event types not listed in documentation.
AdvancedProtectionMalware
AtpGoodMail
DLPMessages
Expire
Receive
SpoofMail
TransportRuleMessages

thanks in advance!

**Comment by dariomws306** [comment]
@mrkeiths and @jdrecklessworld thank you for this feedback.

I'm adding these EventTypes with the description. If you want to double check, I will appreciate that.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @mrkeiths Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
