### ISSUE TITLE
Missing organization parameter?

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/office-docs-powershell#4713]
What is the -organization parameter in example 4?  It is not listed or documented elsewhere in this page, and does not seem to be available in the remote session when I connect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b533bfea-3a27-822a-cff7-c3734c57a2c9
* Version Independent ID: 0df7c84a-3bd3-79da-6a25-6ace0ba627c7
* Content: [Release-QuarantineMessage](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/release-quarantinemessage?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Release-QuarantineMessage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Release-QuarantineMessage.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@jordanmills, I removed the Organization parameter from the example. I'm not sure why it was there.

Thanks for the feedback.
