### ISSUE TITLE
AccessRights flag out of range for Teams Room calendar

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/office-docs-powershell#4717]
I was unable to add the -AccessRights flag of AvailabilityOnly, it was "out of range" for a Teams Room calendar. Is there a default name for a Teams Room Calendar?

Add-MailboxFolderPermission -Identity conferenceroom1@mydomain.com -User office@mydomain.com -AccessRights AvailabilityOnly
Specified argument was out of the range of valid values.
Parameter name: memberRights
    + CategoryInfo          : NotSpecified: (conferenceroom1@mydomain.com:MailboxFolderIdParameter) [Add-MailboxFolderPermission], EnumOutOfRangeException
    + FullyQualifiedErrorId : [TimeStamp=1/21/2020 6:25:14 PM] [FailureCategory=Cmdlet-EnumOutOfRangeException] 9D066817,Microsoft.Exchange.Management.StoreTasks.AddMailboxFolderPermission
    + PSComputerName        : outlook.office365.com

Add-MailboxFolderPermission -Identity conferenceroom1@mydomain.com -User office@mydomain.com -AccessRights EditOwnedItems

FolderName           User                 AccessRights                                                                                                       SharingPermissionFlags
----------           ----                 ------------                                                                                                       ----------------------
Top of Informatio... Office               {EditOwnedItems}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb509e0a-2371-d5b8-6462-c0f29e6c8152
* Version Independent ID: b8fdd337-395d-0c42-4ff1-9a0969a9d578
* Content: [Add-MailboxPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/add-mailboxpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Add-MailboxPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Add-MailboxPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @eschrader, thank you for your feedback.

Maybe I don't understand but I think that you are confusing two cmdlets:
Add-MailboxPermission
Add-MailboxFolderPermission

AvailabilityOnly AccessRight is available on Add-MailboxFolderPermission and you need to specify the calendar folder in the identity parameter. For example:
Add-MailboxFolderPermission -Identity ayla@contoso.com:\Calendar -User julia@contoso.com -AccessRights AvailabilityOnly

More information:
https://docs.microsoft.com/powershell/module/exchange/mailboxes/add-mailboxfolderpermission

**Comment by eschrader** [comment]
Yup, I was unable to move the thread

**Comment by dariomws306** [comment]
Ok, there are something else I can help you?

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @eschrader 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
