### ISSUE TITLE
Installation process doesn't work

### ISSUE THREAD

**Issue by Knurmia** [MicrosoftDocs/office-docs-powershell#4720]
I just followed the process for installing EXO V2 and it seems there's a step missing.

Instead of actually installing ExchangeOnlineManage module, I get this message:

WARNING: The specified module 'ExchangeOnlineManagement' with PowerShellGetFormatVersion '2.0' is not supported by the current version of PowerShellGet. Get the latest version of the PowerShellGet module to install this module, 'ExchangeOnlineManagement'.

The simple fix was to run 'Update-Module -Name PowerShellGet', restart PowerShell and then I was able to install ExchangeOnlineManage without the warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @Knurmia, thank you for your feedback.

What did you get when you run "Install-Module PowershellGet -Force"?

**Comment by bruceburge** [comment]
Latest version of PowershellGet is 2.2.3,

Screen shoot below shows the process of running commands as listed on help page.

![image](https://user-images.githubusercontent.com/6773890/73092313-f9cf7180-3ea1-11ea-9992-5dbc7a6a3b55.png)

**Comment by dariomws306** [comment]
Hi @bruceburge,

Thank you for this information. I have tried in a new Win 10 installation and had the same behavior.

For feedback or issues with Exchange Online PowerShell V2 module I need to send you to this section:
https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#report-bugs-and-issues

Thank you again!

**Comment by bruceburge** [comment]
Not to be a jerk about it, but I mean, really, in this day and age a team at microsoft thinks the best way to handle bug reports, is to have users send an email to contact us at `exocmdletpreview[at]service[dot]microsoft[dot]com` that defeats the point, and does nothing from the other users with the issue. 

I wouldn't have found the work around if not for reading other peoples issues, and using something like, the documented page connected to the product was designed to be able to share solutions.

Using email is a embarrassing huge step back, I mean I don't think Microsoft purchased GitHub so users wouldn't use it right?

**Comment by chrisda** [comment]
@bruceburge, the V2 Module is still in Preivew; that's why @dariomws306 suggested sending the issue to the support alias. Your contribution will help make the feature better.

While sending an email is unusual, it's really the only option for this feature in this Preview state (opening a support ticket for problems would do you no good). I suppose we could have done a Yammer channel instead, but that's no better.
