### ISSUE TITLE
Ability to assign CVI Policy to Groups or OUs

### ISSUE THREAD

**Issue by swinster** [MicrosoftDocs/office-docs-powershell#4727]
Would like to see an ability to assign a policy to groups or Organisation Units, not just global or individually. 

I guess you could pipe the output from `Get-ADuser` into a `ForEach-Object` something like:

```
(get-aduser -Filter * -SearchBase "OU=Finance,OU=UserAccounts,DC=FABRIKAM,DC=COM").UserPrincipalName  |  ForEach-Object {
     Grant-CsTeamsVideoInteropServicePolicy -PolicyName ServiceProviderDisabled -Identity $_
}
```

but this seems a bit long winded (P.S. I haven't tested this either). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0549cc-b860-3c2f-2a35-fdedfff7d31c
* Version Independent ID: 2f30adc3-59e7-5b00-406c-5b5090c1732c
* Content: [Grant-CsTeamsVideoInteropServicePolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsvideointeropservicepolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Grant-CsTeamsVideoInteropServicePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsTeamsVideoInteropServicePolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by swinster** [comment]
FWIW, the `Get-ADUser` may not be entirely appropriate (depending on infrastructure), but you get the idea I'm sure. Perhaps `Get-AzureADUser" or `Get-AzureRmADUser` or `Get-AzADUser` .... to many options....

**Comment by swinster** [comment]
Thinking about this, the AD user stuff is probably not as appropriate as anything that could be used to gather user info on the CS Online side of thing, due to the unique way this stuff hangs together.

For example, if I were to run a `Get-AzureADUser` or `Get-AzureRmADUser`, the admin would need another set of credentials, and possibly this even comes under the responsibility of a different completely different admin group. So, whilst this work great, I think a better solution is needed. 

The `Grant-CsTeamsVideoInteropServicePolicy` comes from the `SkypeOnlinePowerShell.Exe` via the `SkypeOnlineConnector` module, and requires someone to login to the O365 side of things, so a command that can spits out UPNs of users from this are would be more beneficial , such as `Get-CsOnlineUser`. The docs for this command outline the `OU` parameter, then go on to say that it isn't  used!!! 

>This parameter is not used with Skype for Business Online

There is an LDAP filter, although not sure how to construct something that might be of use.

Other than that, I can't find a suitable command that might be able to be used for achieving this within the online management for Teams and what the module allows. Suggestions welcome.

**Comment by get-itips** [comment]
Hello @swinster 
How are you? Hope you are doing good 👍 
Currently, the Identity parameter accepts a UserIdParameter, which, as you said, accepts individual user ids, you could script the cmdlet to run it against a list of users, however I understand that this could not be ideal. For feature requests, I would need to ask you to please [visit this resource](https://microsoftteams.uservoice.com/) to propose the idea, that is a resource that is reviewed by the product team to improve the product.
Hope this information helps you,

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @swinster 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jcmmarq** [comment]
did anyone come up with a good solution for assign CVI policy to security group

**Comment by swinster** [comment]
@jcmmarq  - I think all you can do is vote at https://microsoftteams.uservoice.com/forums/555103-public/suggestions/41995432-grant-csteamsvideointeropservicepolicy-needs-to-be
