### ISSUE TITLE
German translation is Get-Spouse and Remove-Husband

### ISSUE THREAD

**Issue by DennisGaida** [MicrosoftDocs/office-docs-powershell#4728]
I'm sorry if this isn't the correct place to comment on the automatic article translation.

The German translation of this page (https://docs.microsoft.com/de-de/powershell/module/sharepoint-online/get-spouser?view=sharepoint-ps) is `Get-Ehepartner` (*Get-Spouse*) for `Get-SPOUser` and way in the bottom it is `Remove-Ehegatte` (*Remove-Husband*) for `Remove-SPUser`. While this translation is funny it is obviously wrong. Automatic translation should almost never touch code snippets nor should it touch technical PS commands such as all of these documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2412565f-011a-5665-7c3b-e3fe4eae0ee2
* Version Independent ID: 30fda315-30f6-09e0-342c-63940e05208b
* Content: [Get-SPOUser (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spouser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUser.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DennisGaida 
Thanks for noticing and reporting 👍 
I confirmed that the Docs team is aware of this, the translation engine was having some glitches and they were working to fix this.
I see now that, in the German localization, it is correctly ignoring the cmdlet name, and it is showing ok for me, can you confirm?

_Set-ThankYou_

**Comment by DennisGaida** [comment]
@get-itips looks good to me right now.
