### ISSUE TITLE
Access Policies don't apply to Group Calendars / Mailbox

### ISSUE THREAD

**Issue by jdelforno** [MicrosoftDocs/office-docs-powershell#4731]
Groups (Office 365) have a calendar and receive mail to a unified mailbox that we can see in Exchange. There are no restrictions on most APIs for Groups, Users or Calendars. It's either nothing or Read/Write All from a Daemon perspective. 

Being able to restrict the API to have only access to specific groups would be amazing.  Especially if, you could create a Group with a prefix and then use a Dynamic Security Group to allow access to all groups with "Your_Prefix_<GroupName>"

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hello @jdelforno, thanks for your feedback. 

For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/
There, your suggestion will reach the product team.

**Comment by yogkumgit** [comment]
@jdelforno  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
