### ISSUE TITLE
Set-SPOSite deletes all owners when updating with a new one

### ISSUE THREAD

**Issue by FedeFigueredo** [MicrosoftDocs/office-docs-powershell#4735]
Hi! I´ve executed `Set-SPOSite -Identity https://contoso.sharepoint.com/sites/site1 -Owner joe.healy@contoso.com -NoWait` and it indeed added that user as an owner to the site collection. But the problem is that it **deleted all the users** that were previously an owner. I´ve read that this cmdlet "updates" the owner of a site collection. But wouldn´t be an expected behavour to just add this owner  **keeping** the previous ones? Even if I would include all the previous ones as an argument, to avoid them being removed as owners, that wouldn´t work neither. Because this cmdlet only accepts ONE owner as an argument for the `-Owner` parameter.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @FedeFigueredo 
How are you? Hope you are doing good 👍 
I reviewed the cmdlet's documentation and indeed it says it will _update_ the owner, not add an owner to a current list of owners. So I do not identify that the documentation needs to be changed.
I suggest you review the [SharePoint user voice](https://sharepoint.uservoice.com/) to propose changing this behavior.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @FedeFigueredo 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by TerryMoore-dev** [comment]
Just for information  if you use Set-SPOUser -Site Https;//contoso.sharepoint.com -LoginName user@contoso.onmicrosoft.com  -IsSiteCollectionAdmin  $true It will add the user or group to  vice replace Site Collection Owners.
