### ISSUE TITLE
Example is just a placeholder :(

### ISSUE THREAD

**Issue by swinster** [MicrosoftDocs/office-docs-powershell#4736]
As title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c79b5db-9d19-caeb-75ab-866a2581b53d
* Version Independent ID: 2d6390b3-3280-39b7-70ca-5792b57187cc
* Content: [Set-CsVideoInteropServiceProvider (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csvideointeropserviceprovider?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsVideoInteropServiceProvider.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsVideoInteropServiceProvider.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @swinster 
Thanks for noticing 👍
Created a PR to add a working example.

**Comment by yogkumgit** [comment]
@tomkau Please merge this PR #4753 Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @swinster Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
