### ISSUE TITLE
Register-SPMTMigration: -Incremental Parameter Missing

### ISSUE THREAD

**Issue by asthalon** [MicrosoftDocs/office-docs-powershell#4737]
Hello,

With assembly version 3.2.114.2, the _Incremental_ switch listed in the documentation is no longer present.

It appears to have been replaced by the _EnableMultiRound_ parameter, based on what's present but not documented.

The documentation also indicates that the _Incremental_ parameter is set to True by default, however, when executing _Register-SPMTMigration_ with default parameters, _EnableMultiRound_ is set to _false_.

Can you please update the documentation to provide some clarity for these changes?

To be honest, _EnableMultiRound_ seems like an unnecessary name change that obfuscates the purpose of the parameter; _Incremental_ provides a more obvious declaration.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @asthalon How are you? Hope you are doing good.
A Pull Request, not yet merged, is on the way, with [the commit](https://github.com/MicrosoftDocs/office-docs-powershell/pull/4754/commits/145f59eda3ecfaa53be30e236cda9df56fcc6a7f) that updates the documentation to reflect the _EnableMultiRound_.
Thanks

**Comment by get-itips** [comment]
Hello @asthalon 
PR was merged, you can see the live updated version now.
@yogkumgit I think we can close this now

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @asthalon Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by asthalon** [comment]
Thanks folks, appreciate the quick turnaround!
