### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by prasantabhowmik** [MicrosoftDocs/office-docs-powershell#4742]
I am getting the below error.
Get-SPOSiteScriptFromWeb : The term 'Get-SPOSiteScriptFromWeb' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22a8d3e7-7ce9-1dea-e181-dd1e5dc3bd83
* Version Independent ID: b6176424-5594-a1de-5e55-a3c8868beec1
* Content: [Get-SPOSiteScriptFromWeb (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositescriptfromweb?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScriptFromWeb.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScriptFromWeb.md)
* Service: **sharepoint-powershell**
* GitHub Login: @
* Microsoft Alias: ****

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @prasantabhowmik 
How are you?
Did you [install and import](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps) the SharePoint Online module?
Thanks

**Comment by prasantabhowmik** [comment]
Hi @get-itips ,

I am good thanks, hope you are doing well.

Yes I do have installed the SharePoint module installed. 
Currently I am running on 16.0.8615.0 version.

Thanks,
Pras

**Comment by get-itips** [comment]
@prasantabhowmik 
Be sure to update the module version, I am testing with a higher version (16.0.19223.12000) and its present.

**Comment by prasantabhowmik** [comment]
Hi @get-itips ,

Thanks for the reply, Its works for me too after I have updated to the latest version.

Thanks,
Pras

**Comment by prasantabhowmik** [comment]
PS Command Get-SPOSiteScriptFromWeb is available with latest(16.0.19515.0) version.
