### ISSUE TITLE
Example on how to create multilingual default labels for newly created term

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#4746]
Hey folks,
I would like to share an idea, because this has cost me quite some time ...
There is no example on how to create multilingual default labels for a term or related link to the methods of the Term object.
Kudos to this awesome [answer on sharepoint.stackexchange](https://sharepoint.stackexchange.com/questions/268529/how-to-set-other-label-value-of-a-term-set/268550#268550) by [Gautam Sheth](https://sharepoint.stackexchange.com/users/8068/gautam-sheth) and the article [O365 - Create Labels on Managed Metadata Terms using CSOM in PowerShell from a CSV file](https://docs.microsoft.com/en-us/archive/blogs/fromthefield/o365-create-labels-on-managed-metadata-terms-using-csom-in-powershell-from-a-csv-file).
They make use of the **CreateLabel** method of the Term object. I could only find a SharePoint Server API article on this method: [CreateLabel](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.taxonomy.term.createlabel?view=sharepoint-server).
However, I did not even know about these awesome methods beforehand. 

I slightly modified the code to add default labels for other LCID's. This is my suggestion code on how to add multilingual labels whilst creating a new term:

`$context = Get-PnPContext`
`$term = New-PnPTerm -Name "English term" -TermSet "TermSetName" -TermGroup "TermGroupName" -LCID 1033`
`$createLabelDE = $term.CreateLabel("German label", 1031, $true)`
`$context.Load($term)`
`Invoke-PnPQuery`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c537bdf-b8fc-9735-1870-355e757b531a
* Version Independent ID: 68d5bb2b-9256-601f-7f44-14c447293c91
* Content: [New-PnPTerm (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpterm?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPTerm.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPTerm.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Markus-Hanisch Markus,
I need to kindly redirect you to this [other resource](https://github.com/SharePoint/PnP-PowerShell/) to share your contribution, as you might know, PnP cmdlets are community-driven.
You can either create an issue there copying your message or directly propose changing to the source code (which impact the documentation)

**Comment by Markus-Hanisch** [comment]
@get-itips 
[PnP-PowerShell/Documentation/](The https://github.com/SharePoint/PnP-PowerShell/tree/master/Documentation) states; 
> The PnP PowerShell Documentation has moved to [docs.microsoft.com](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps)

**Comment by get-itips** [comment]
> @get-itips
> [PnP-PowerShell/Documentation](https://github.com/SharePoint/PnP-PowerShell/tree/master/Documentation) states:
> 
> > The PnP PowerShell Documentation has moved to [docs.microsoft.com](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps)

Yes, PnP documentation is in docs.microsoft.com

PnP documentation markdown files are reflected in the office-docs-powershell repo directly from the PnP-PowerShell repo, (both under docs.microsoft.com)

Yes, if you create a PR against the source code of the cmdlets (that include the documentation), create it against dev branch.

Hope this info helped you

**Comment by Markus-Hanisch** [comment]
@get-itips 
I created my [pull request on **New-PnPTerm.md**](https://github.com/MicrosoftDocs/office-docs-powershell/pull/4763)

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Markus-Hanisch Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
