### ISSUE TITLE
Is the MembershipType pipe still valid ?

### ISSUE THREAD

**Issue by rickleye** [MicrosoftDocs/office-docs-powershell#4747]
Get-TeamChannel -GroupId af55e84c-dc67-4e48-9005-86e0b07272f9 -MembershipType Private

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b48c32-ad79-4249-638b-f53f9d76397f
* Version Independent ID: 36d9cfe0-cf60-2fa1-41b4-6c6971042394
* Content: [Get-TeamChannel (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @rickleye 
That parameter is valid for Private Preview as the doc says.
Thank you

**Comment by rickleye** [comment]
I have tried it and it doesn’t work. I’ll send you a screen shot

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kenwith** [comment]
@rickleye - we were able to reach the PM for this feature and the parameter has not been released in the Teams PowerShell module yet. You can experiment with it in the Beta module. Here is guidance on this feature: https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management 

And at the top of the article linked above there is a note about installing the beta Teams PowerShell module. Note that it is a separate process than installing the currently released Teams PowerShell module. There is discussion to move the beta module into the same gallery as the currently released module (how Azure currently handles PowerShell module previews) but there is nothing to announce yet so you will need to follow the separate process outlined above.

If you have done this and are still having problems then the best way to move forward would be to open a support service request. You can do that in your Office 365 tenant admin site. The service engineers will then be able to file a bug with the product team and improve the beta PowerShell module before it releases.

Also, I just wanted to say thank you for taking the time to try the beta module and read the documentation and provide feedback on the documentation. Most people don't take the time and I just wanted to let you know it is very much appreciated.
