### ISSUE TITLE
List needs updating

### ISSUE THREAD

**Issue by CloudHotShot** [MicrosoftDocs/office-docs-powershell#4748]
Lots of Get- and Set- commands no longer available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94694082-c529-5654-1734-57514ec17a1f
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [Microsoft Teams PowerShell](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps&source=docs#feedback)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by markgort86** [comment]
I think to solve this issue it's would be nice to deliver the command's that are not available anymore.

**Comment by get-itips** [comment]
Hello @CloudHotShot how are you?
Article has been updated here,  https://github.com/MicrosoftDocs/office-docs-powershell/commit/e9e92e1e8510cf7024f790598bb4b1caddf370ff#diff-5c38a4ff90d0917b275895177b0c5f73 removing the cmdlets that are not present anymore.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation. @CloudHotShot Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
