### ISSUE TITLE
Clarification on parameter combinations

### ISSUE THREAD

**Issue by IdahoR** [MicrosoftDocs/office-docs-powershell#4752]
Attempting to create an Allow rule for basic auth from client networks fails.  
New-ClientAccessRule Allow_BasicAuth -Priority 2 -Action AllowAccess -AnyOfAuthenticationTyp
es BasicAuthentication -AnyOfClientIPAddressesOrRanges (list)

Error message:
Chosen authentication type and protocol combination is invalid. See 'https://go.microsoft.com/fwlink/p/?linkid=869219' for supported combinations.

Please clarify in this article the authentication type/protocol combinations which are valid, and reference the article called out in the error message.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaf29b85-4c0c-1267-cfb7-115bf50926e7
* Version Independent ID: 78639fbd-fd1d-1ab9-e204-c3283d3e8373
* Content: [Set-ClientAccessRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-clientaccessrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-ClientAccessRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-ClientAccessRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @IdahoR, thank you for your feedback.

This information seems to be on both articles. In the Set-ClientAccessRule article I can see it under "Description" section.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @IdahoR 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
