### ISSUE TITLE
Mel6302

### ISSUE THREAD

**Issue by Mel2036** [MicrosoftDocs/office-docs-powershell#4755]
Get-ManagementRoleAssignment -Role "&lt;Role name&gt;"  -GetEffectiveUsers -Delegating $false | Where-Object {$_.EffectiveUserName -ne "All Group Members"} | Format-Table -Auto EffectiveUserName,Role,RoleAssigneeName,AssignmentMethod

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f0a60b-0a31-dd92-53eb-4f7def6319f3
* Version Independent ID: 06ad3c31-d631-cb66-07e7-380f9f923ff9
* Content: [Find the permissions required to run any Exchange cmdlet](https://docs.microsoft.com/en-au/powershell/exchange/exchange-server/find-exchange-cmdlet-permissions?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-server/find-exchange-cmdlet-permissions.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/find-exchange-cmdlet-permissions.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @Mel2036 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
