### ISSUE TITLE
Make get-mailboxfolderpermission and similar commands language-agnostic

### ISSUE THREAD

**Issue by MatBerg2** [MicrosoftDocs/office-docs-powershell#4757]
With New-Mailbox​Export​Request, I can use something like "#Inbox#" to specify wellknown folders regardless of the mailbox language. With get-mailboxfolder, get-mailboxfolderpermission and similar commands I cannot do that (or it is not properly documented). Instead I have to use worarounds to find out the actual name of the Inbox or calender first, which is not very convenient.

It would be great if all Exchange Commands dealing with mailbox folders would support language-independent references to standard folders.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hello @MatBerg2, thank you so much for this feedback. 

For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/.
There, your suggestion will reach the product team.

**Comment by yogkumgit** [comment]
@MatBerg2  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
