### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by do0ds** [MicrosoftDocs/office-docs-powershell#4764]
I noticed when I set an exclusion via the web UI and check the policy via powershell I see it put the URL into 3 different spots: WhiteListedUrls, ExcludedUrls & DoNotRewriteUrls.  I came here to find the difference between the 3, but this page was no help as the first one states it is reserved for Microsoft's use and the second two have the same description.  It left me confused as to what the difference is between them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 923dc552-f943-e043-165d-9ed5fb734c6c
* Version Independent ID: fe62e834-2cb1-0a15-0d93-14194ca0e33a
* Content: [Set-SafeLinksPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-safelinkspolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Set-SafeLinksPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Set-SafeLinksPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @do0ds, thank you for your feedback.

If you try to use WhiteListedUrls or ExcludedUrls you will receive this error:
"The WhiteListedUrls and ExcludedUrls params are deprecated. Use the DoNotRewriteUrls param instead. If you have any scripts that use the WhiteListedUrls and ExcludedUrls params, update them to use the DoNotRewriteUrls param."

I will update the article accordingly.

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4791 Thanks

**Comment by do0ds** [comment]
> Hi @do0ds, thank you for your feedback.
> 
> If you try to use WhiteListedUrls or ExcludedUrls you will receive this error:
> "The WhiteListedUrls and ExcludedUrls params are deprecated. Use the DoNotRewriteUrls param instead. If you have any scripts that use the WhiteListedUrls and ExcludedUrls params, update them to use the DoNotRewriteUrls param."
> 
> I will update the article accordingly.

Great, thanks!

**Comment by chrisda** [comment]
Dario took care of this in his PR #4791, so taking my name off and closing.
