### ISSUE TITLE
What is a "SharePoint Online global administrator?"

### ISSUE THREAD

**Issue by ferringer** [MicrosoftDocs/office-docs-powershell#4769]
There is no such thing (that I am aware of) as a role in O365 or SharePoint Online or Azure Active Directory named "SharePoint Online global administrator." There is a "SharePoint Online service administrator" role and there is an "Office 365 global administrator" role but they are two separate and distinct roles that can be granted independently of each other to user accounts in AAD. Which one of those two roles is this statement referring to?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fd33f1e-906f-183f-87a0-e18b5b8da89d
* Version Independent ID: 2d28b122-8602-a996-2e69-80d552a4392a
* Content: [Get-PnPTenant (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnptenant?view=sharepoint-ps&source=docs)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTenant.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello John, how are you? hope you are doing great.

I need to kindly redirect you to this [other resource](https://github.com/SharePoint/PnP-PowerShell/) for you to share your findings, as you might know, PnP cmdlets are community-driven.
You can either create an issue there copying your message or directly propose changing the source code (which impacts the documentation)

**Comment by ferringer** [comment]
Andres –

I’m not sure I completely understand what you are recommending that I do? Am I supposed to somehow post this question to the PNP cmdlets’ project on GitHub, or take some other kind of action? I apologize for not following what you’re suggesting, and do appreciate any additional guidance you could provide on what I should do next.

Thank you,

John

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by get-itips** [comment]
@ferringer 
John, exactly, please post this finding into the PnP repo, Issues section, a member of the PnP community will pick it up and act accordingly.
Thanks

**Comment by ferringer** [comment]
Will do, thank you very much.

Based on that, I would guess that this item can be closed.

John

________________________________

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ferringer 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
