### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by LastGunslinger** [MicrosoftDocs/office-docs-powershell#4770]
Example 1 on this page is incorrect. It shows the command Remove-PnPOffice365GroupToSite instead of Remove-PnPSiteCollectionAppCatalog, and the parameter used is -Url instead of -Site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 489173d7-dc1d-5572-b329-dc333a7caeb9
* Version Independent ID: ff1b25a9-a59a-cd16-2cf3-061e167648ab
* Content: [Remove-PnPSiteCollectionAppCatalog (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpsitecollectionappcatalog?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPSiteCollectionAppCatalog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPSiteCollectionAppCatalog.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @LastGunslinger Reginald, how are you? Thanks for noticing.

I need to kindly redirect you to this [other resource](https://github.com/SharePoint/PnP-PowerShell/) to share your contribution, as you might know, PnP cmdlets are community-driven.
You can either create an issue there copying your message or directly propose changing the source code (which impacts the documentation)

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @LastGunslinger 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
