### ISSUE TITLE
(Get-SPMTMigration).StatusOfTasks - Incorrect Task Status for Failure (FileShare SourceURI Permissions)

### ISSUE THREAD

**Issue by asthalon** [MicrosoftDocs/office-docs-powershell#4773]
Hello,

When executing a FileShare migration, if the account running the task does not have sufficient permissions to the source directory, the SPMT Session flags the task with Status COMPLETED:

![image](https://user-images.githubusercontent.com/60235362/73319110-68496200-4209-11ea-8fa2-196e79d7a35f.png)

However, failure reports files are generated correctly and indicate the problem; ItemFailureReport_R1.csv & FailureSummary.csv both contain:
![image](https://user-images.githubusercontent.com/60235362/73319222-b9f1ec80-4209-11ea-9e8a-1b9cea5dcbce.png)

In this circumstance, when the entire Source directory is unavailable (as opposed to just empty), the task should terminate with a FAILED status instead of COMPLETED and the ErrorMessage & ErrorID properties should be populated accordingly. From a batching standpoint I have no way to trust the session results other than to run a detection against the file system output now to look for failure files.

I tried the same migration config via .csv import in the SPMT GUI, and unfortunately the result was the same (indicated success, report files show the same errors) so this is not explicitly a PS module issue.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @asthalon 
How are you? Hope you are doing great.
Great that you noticed this, however, here we can only address issues in documentation, so I need to kindly redirect you to Support Services of your tenant to report this.
If, for any reason, this leads to an update that impacts documentation, that is where we can take some action here.
Thank you!

**Comment by asthalon** [comment]
Roger that, thank you!
