### ISSUE TITLE
Unable to use -MembershipType with New-TeamChannel

### ISSUE THREAD

**Issue by zakgold** [MicrosoftDocs/office-docs-powershell#4775]
-MembershipType does not exist as a parameter in version 1.0.3 and MicrosoftTeams module 1.0.19 cannot be found to install with PowershellGet. What's going on here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd44b411-4b59-b90f-0b82-ad0a87652854
* Version Independent ID: 2c52cc4e-47a1-be0d-8860-1011adf061fd
* Content: [New-TeamChannel (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-teamchannel?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @zakgold 
Please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/4747#issuecomment-578902237

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @zakgold 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
