### ISSUE TITLE
Suggested revision for -Archive parameter description 

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#4777]
Hello,

The current description is, in my opinion, incorrect:

> -Archive
> The Archive switch is required to return archive mailboxes in the results. You don't need to specify a value with this switch.

It should instead be something like:

> -Archive
> The Archive switch is required to return only mailboxes which are enabled with an archive mailbox in the results. You don't need to specify a value with this switch.

The distinction is that you get back mailboxes, not archive mailboxes, in the results.  This is confusing especially if one tries to find only archive mailboxes, for example:

`Get-Mailbox -Archive -Database ArchivesDB1`

In this example, `ArchivesDB1` is meant to signify a dedicated database where archive mailboxes are placed (just to help with demonstrating the issue).  The only results that will return, are regular mailboxes which happen to reside on that database, and which are enabled with an archive mailbox.  However, no actual archive mailboxes will be returned.

For this reason it's important that the description states clearly that regular mailboxes are returned.  Even though it returns only mailboxes which are enabled with and archive, it does not return actual archive mailboxes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b640892-b0a1-4f20-1e25-fe5f0e97f5b6
* Version Independent ID: 51774b36-90fa-1d9a-5800-1a54d9f70590
* Content: [Get-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@JeremyTBradshaw, confirmed. The switch simply filters the result by those who have archive mailboxes. I updated the description in Get-Mailbox and Get-EXOMailbox.

Thanks for the feedback.
