### ISSUE TITLE
Misppelling of Connect-EXOPSSession.

### ISSUE THREAD

**Issue by ComputerHabit** [MicrosoftDocs/office-docs-powershell#4778]
Misppelling of Connect-EXOPSSession.
----------------------------------
If your organization has single sign-on (SSO) enabled and you are logged on to a computer as a user in the SSO domain, then Connect-EXPOPSSession may fail with the following error:

https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps#single-sign-on

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@ComputerHabit, fixed. But, in the future, you can fix stuff like this directly; no need to file an Issue first: https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md.

Thanks for the feedback.

**Comment by ComputerHabit** [comment]
Ah I didn’t know that.  Also I might not trust myself.  I misspelled misspell.  :)

________________________________

**Comment by chrisda** [comment]
Well, don't feel too nervous. Your proposed changes need to be approved before they go live, so someone is always double-checking.
