### ISSUE TITLE
Does not completely support AD Synced Resources

### ISSUE THREAD

**Issue by auger282** [MicrosoftDocs/office-docs-powershell#4780]
Set-Place only works completely with cloud created resources.

AD synced resources can only set: label, audiodevicename, videodevicename, displaydevicename, iswheelchairaccessible, floor, floorlabel, capacity, phone

These attributes are only available for cloud created resources: street, city, state, postalcode, countryorregion, geocoordinates, building

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @auger282, thank you for your feedback.

I will test it next week and update the article accordingly.

**Comment by dariomws306** [comment]
I have tested and you are right. If you try to modify these properties for synced rooms you will get "Encountered an internal server error" as them should be modified on-premises using AD or Exchange management tools.
The only property that I cannot say that you are right is Building, since I could modify it.

@chrisda I think the error message should be improved to something like "The operation cannot be performed because the object is being synchronized from your on-premises organization"

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4836 Thanks

**Comment by auger282** [comment]
I see you've added the comments that it should be updated on-prem. These
options aren't available on-prem. Set-place is a cloud only command (as far
as I know).

**Comment by dariomws306** [comment]
You shouldn't use Set-Place on-premises, use AD or Exchange management tools. But give me more time I'm doing more testing.

**Comment by auger282** [comment]
Will do.. I appreciate the help. From what I've found the other attributes
do work in the cloud for set-place for the AD Synced accounts (odd but it
works). I wonder if this is a bug that they all don't work??

**Comment by dariomws306** [comment]
Trying to get more information. I appreciate your patience.

**Comment by auger282** [comment]
Any update? Is there a date in the future when I should check in?
Thanks for your help looking into this.

**Comment by chrisda** [comment]
I updated the topic to say that the cmdlet only works on room mailboxes created in the cloud (not synchronized room mailboxes).

Thanks for the feedback.

Closing.

**Comment by urbantom** [comment]
Hi, I think, the opinion "cmdlet only works on room mailboxes created in the cloud (not synchronized room mailboxes)" is incorrect. I have a cloud-only environment and it is affected by this issue.

**Comment by dariomws** [comment]
Hi @urbantom, thank you for your comment.

Set-Place cmdlet article was updated and you can see this note now:
"Note: In hybrid environments, this cmdlet doesn't work on the following properties on synchronized room mailboxes: City, CountryOrRegion, GeoCoordinates, Phone, PostalCode, State, and Street. To modify these properties on synchronized room mailboxes, use the Set-User or Set-Mailbox cmdlets in on-premises Exchange."
