### ISSUE TITLE
The OU

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/office-docs-powershell#4782]
Does the specified OU only need to include the Skype for Business servers, or does it also need to include all SQL servers used in cases like Enterprise deployments, including cluster nodes and instances too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c581ab28-43ab-f306-993b-f800945c7d2f
* Version Independent ID: 5d680d5d-7467-a858-9afb-b4221cb8a2e2
* Content: [Grant-CsSetupPermission (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-cssetuppermission?view=skype-ps&source=docs)
* Content Source: [skype/skype-ps/skype/Grant-CsSetupPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsSetupPermission.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Korbyn72 
How are you? Hope you are doing good.
This should be ran only against OUs that have Skype For Business Server binaries.

_...computers running Skype for Business Server_

**Comment by Korbyn72** [comment]
Thank you for confirming.  In the case I was troubleshooting, I discover they had embedded the CsUserAdministrator into an IT group that the other CsAdministrators were in.  Membership in CSUserAdministrator has a block/deny preventing the publishing of the Topology.  GPResult /R showed the way.

Admins were correctly in CsAdministor and RTCUniversalServerAdmin, and the OU for where the Skype servers were place was properly prepped.  Not well documented is that CSUserAdministrator membership is “prohibitive”.

Thanks though for confirming SQL isn’t in that requirement list.

Korbyn

**Comment by get-itips** [comment]
Thanks to your for sharing your feedback.
@yogkumgit you can proceed closing this one.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Korbyn72 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
