### ISSUE TITLE
Applying custom semantic colours

### ISSUE THREAD

**Issue by jacksonv1lle** [MicrosoftDocs/office-docs-powershell#4784]
Is it possible to configure the semantic colours using the Add-SPOTheme tool?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jacksonv1lle do you mean Semantic Slots? @trent-green can you confirm this? Thank you 👍

**Comment by jacksonv1lle** [comment]
Hi @get-itips. Yes that's what I meant but I realize now that semantic slots are not related to SharePoint but rather they are a feature of the Office Fabric library.

**Comment by get-itips** [comment]
Ok thanks for clarifying, we can close this now.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @jacksonv1lle 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
