### ISSUE TITLE
Command doesn't exist anymore

### ISSUE THREAD

**Issue by SanguptaMSFT** [MicrosoftDocs/office-docs-powershell#4789]
This command doesn't exist anymore in the Skype for Business online module. please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df5da894-a57f-d870-7a00-29507fb6d37f
* Version Independent ID: e52506bf-d874-625d-2b3e-c4d1c6f3ff54
* Content: [Get-CsTeamsMobilityPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Get-CsTeamsMobilityPolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Get-CsTeamsMobilityPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTeamsMobilityPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @saragava
* Microsoft Alias: **saragava**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @SanguptaMSFT 
Thanks for noticing, we are adding a note thru a PR stating this.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @SanguptaMSFT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
