### ISSUE TITLE
Examples are wrong

### ISSUE THREAD

**Issue by nils-a** [MicrosoftDocs/office-docs-powershell#4795]
The examples are using the parameter `-Name`, which in fact does not exist. 
Please correct the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8137a60-b5ea-297e-61d2-2271da424dba
* Version Independent ID: b3d0d338-bce4-4204-84cf-100e318621c8
* Content: [Start-PnPWorkflowInstance (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/start-pnpworkflowinstance?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Start-PnPWorkflowInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Start-PnPWorkflowInstance.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @nils-a Nils
I need to kindly redirect you to this [other resource](https://github.com/SharePoint/PnP-PowerShell/) to share your contribution, as you might know, PnP cmdlets are community-driven.
You can either create an issue there copying your message or directly propose changing the source code (which impacts the documentation)
Thank You!

**Comment by nils-a** [comment]
Created https://github.com/SharePoint/PnP-PowerShell/issues/2482
