### ISSUE TITLE
Set Outgoing Number from Direct Routing (PSTN)

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/office-docs-powershell#4796]
Who is it possible to set a Phone number form Direct Routing for Outgoing Calls?

`New-CsCallingLineIdentity -Identity "Outgoing" -CallingIdSubstitute "Service" -ServiceNumber "[Phone number]" -EnableUserOverride $false -Verbose`

> WARNUNG: The Service number [Phone number] is not valid. Please ensure that the service number is configured in BVD and belongs to this Tenant.

**Comment by weyCC81** [comment]
Related to:
https://docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps
https://docs.microsoft.com/en-us/powershell/module/skype/set-cscallinglineidentity?view=skype-ps

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @weyCC81 
I think this is not yet supported.
@tomkau Tom, can you confirm please ? Thank you

**Comment by yogkumgit** [comment]
@tomkau Please answer this query. Thanks

**Comment by get-itips** [comment]
Hello @weyCC81 How're you?
Reviewing open issues, I could see that this statement, present in the article, is still valid

> ServiceNumber must be a valid Service Number in the Skype for Business Online online telephone number inventory.

So this is the requirement for now.

There is a uservoice for this [here](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38223676-enable-the-ability-to-use-non-service-numbers-with), I voted.

Hope this info helps you.

**Comment by weyCC81** [comment]
Hi @get-itips 

Thanks for the Answer, even if it is more or less nice 👍 
#please-close

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @weyCC81 
Thanks for your reply, we proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
