### ISSUE TITLE
Page is unfinished

### ISSUE THREAD

**Issue by aidancopps** [MicrosoftDocs/office-docs-powershell#4798]
Content on this page has not been completed. Please update with examples and more information about parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9af8cd-c307-aff5-db34-b9c3864cc32a
* Version Independent ID: ed904d57-f5db-c145-58af-51959bb4c93c
* Content: [Set-CsOnlineDialInConferencingUserDefaultNumber (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinedialinconferencinguserdefaultnumber?view=skype-ps#parameters)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineDialInConferencingUserDefaultNumber.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineDialInConferencingUserDefaultNumber.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @aidancopps 
Thanks for noticing, I created a pull request proposing adding missing descriptions, once reviewed and merged, you will see it impacted on the live version of the article.
Thank you

**Comment by yogkumgit** [comment]
@tomkau Please merge this PR #4825 Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @aidancopps Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
