### ISSUE TITLE
Using this module in C# program

### ISSUE THREAD

**Issue by totoken** [MicrosoftDocs/office-docs-powershell#4802]
I am just sharing this information because I was not able to find this anywhere.  I am not reporting an issue (I'm already in contact with the Support).

If you have a C# code that connects to Exchange Online using the New-PSSession (the old method that uses Basic auth that will be turned off Oct.2020) and wanting to replace with this new module, you can do that by invoking Import-Module in your runspace by providing FullyQualifiedName param with the full path to "Microsoft.Exchange.Management.ExoPowershellModule.dll".  You can find this .dll file in your installation folder of this new module.  You should be able to find this installation folder in something like "%LOCALAPPDATA%\Apps\2.0\??\??\micr..tion_???\".  After invoking Import-Module, you want to run the content of "CreateExoPSSession.ps1" as a script in your runspace.  This .ps1 should be in the installation folder you found.  After that, you should be able to invoke Connect-EXOPSSession in your runspace.   Sample code is attached. 
[ExoRpsModuleTester.zip](https://github.com/MicrosoftDocs/office-docs-powershell/files/4141638/ExoRpsModuleTester.zip)

I did not test with MFA enabled account, but the account I used has been configured so that Basic Auth is not allowed (using new-authenticationpolicy and set-user).  Disconnecting a session can be done by iterating through the get-pssession and closing runspace and invoking remove-pssession on each pssession.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @totoken, thank you for your comment.

The section feedback in docs.microsoft.com is available to get feedback from the community about documentation and improve it.
I think the best place for the information you share (which is very interesting) is a blog or forum. Some ideas:
https://dotnet.microsoft.com/platform/community

**Comment by totoken** [comment]
Hello, @dariomws306.
Thank you for your reply.  I used this feedback because the original article page is the first page that comes up when googling "exchange online powershell modern authentication" so that people can find it.  Would you tie this thread to this page please?:
https://github.com/MicrosoftDocs/office-docs-powershell/issues?utf8=%E2%9C%93&q=%22f2de1272-5e37-c59f-fcb9-34fa66b0d268%22

Thank you,

**Comment by dariomws306** [comment]
@totoken,

This issue is tied to this repository (office-docs-powershell) and a Exchange tag was added:
https://github.com/MicrosoftDocs/office-docs-powershell/issues?utf8=%E2%9C%93&q=exchange

My apologies but I don't understand what else you suggest.

**Comment by totoken** [comment]
Maybe adding f2de1272-5e37-c59f-fcb9-34fa66b0d268 to this thread make it show in https://github.com/MicrosoftDocs/office-docs-powershell/issues?utf8=%E2%9C%93&q=%22f2de1272-5e37-c59f-fcb9-34fa66b0d268%22

**Comment by totoken** [comment]
And it did.  I am closing this "issue" entry.  Thank you!
