### ISSUE TITLE
Page Title is Get-CsOnlineUser

### ISSUE THREAD

**Issue by VladimirGluten47** [MicrosoftDocs/office-docs-powershell#4815]
Super minor feedback, the page title for this page is Get-CsOnlineUser. I believe that page must have been used as a template at some stage, because both this page and the page for Get-CsOnlineVoiceRoutingPolicy have "Get-CsOnlineUser" as a title in the web browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f5162e-0e2d-6e12-046b-ac209e0a43e6
* Version Independent ID: 43cbbe7b-d4d4-a0d9-f096-2e1f87f9860b
* Content: [Get-CsOnlineVoiceRoute (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinevoiceroute?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineVoiceRoute.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineVoiceRoute.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for noticing @VladimirGluten47  , created the pr that fixes it.

**Comment by yogkumgit** [comment]
@tomkau Please merge this PR #4826 Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @VladimirGluten47 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
