### ISSUE TITLE
Browser title is Get-CsOnlineUser

### ISSUE THREAD

**Issue by VladimirGluten47** [MicrosoftDocs/office-docs-powershell#4817]
Super minor feedback, the page title for this page is Get-CsOnlineUser. I believe that page must have been used as a template at some stage, because several pages have "Get-CsOnlineUser" as a title in the web browser.
See #4815 and #4816 for other pages with the same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d4c21d1-c4a9-53f7-b744-39b27862dd27
* Version Independent ID: 07875de5-9ca6-ebab-486e-9078fdfc25d4
* Content: [Set-CsOnlinePstnUsage (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinepstnusage?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlinePstnUsage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlinePstnUsage.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @VladimirGluten47 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
