### ISSUE TITLE
i am using mfa but basic auth is turned off by a corporate rule (gpo) - i can't turn it on

### ISSUE THREAD

**Issue by rlad1** [MicrosoftDocs/office-docs-powershell#4819]
how do i work around basic auth off and no ability to turn it on.  my company will not allow it.  i can not install online exchange powershell correctly.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @rlad1, thank you for your feedback.

Microsoft is working in a new Exchange PowerShell module where you can connect without basic authentication, using modern authentication:
https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2
It's currently in Preview but it should be delivered before October 13, 2020, when basic authentication will be deprecated for Exchange Online:
https://support.microsoft.com/help/4521831/exchange-online-deprecating-basic-auth

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @rlad1 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
