### ISSUE TITLE
What permissions are required?

### ISSUE THREAD

**Issue by aidancopps** [MicrosoftDocs/office-docs-powershell#4820]
It would be helpful to provide information about what permissions are required to run this command. Based on our experience it seems the Teams Service Administrator does not have enough permissions as the command is not imported when connecting via PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82154a26-a125-e7ea-8731-a8c4472fe735
* Version Independent ID: 015533c1-6a15-3dc1-083d-3370bdc3915d
* Content: [Set-CsUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps#description)
* Content Source: [skype/skype-ps/skype/Set-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @aidancopps 
Had to use a Skype For Business Administrator to get access to that cmdlet.
Hope this info helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @aidancopps 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
