### ISSUE TITLE
Descriptions for Examples #1 and #4 are reversed

### ISSUE THREAD

**Issue by spallister** [MicrosoftDocs/office-docs-powershell#4821]
As described in this issue here: https://github.com/SharePoint/PnP-PowerShell/issues/2470#issuecomment-581555415, the descriptions for Examples #1 and #4 are reversed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba509b85-58e0-f1f7-8134-4678339c7097
* Version Independent ID: e3837ec6-d90c-35c4-a563-4313ffb11fb6
* Content: [Get-PnPFile (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpfile?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFile.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @spallister Sean
How are you? Hope you are doing good.
Documentation for PnP is directly reflected from the source code of PnP cmdlets, that reside on this [other repo](https://github.com/SharePoint/PnP-PowerShell/).
So, for any issues with PnP cmdlets, or PnP Documentation, they must be handled on that repo (you referenced an issue from it.
So I need to kindly redirect you to that other repo, a member of the PnP community will handle it.

Thank you

**Comment by spallister** [comment]
Thanks @get-itips - I've opened the new, above-referenced issue there.
