### ISSUE TITLE
ExchangeOnlineManagement does not work with Powershell 7rc2

### ISSUE THREAD

**Issue by fbehrens** [MicrosoftDocs/office-docs-powershell#4834]
```
Connect-ExchangeOnline -Credential $UserCredential -ShowProgress $true

New-ExoPSSession: C:\scripts2\libwba\vendor\ExchangeOnlineManagement\0.3374.9\ExchangeOnlineManagement.psm1:367
Line |
 367 |  … PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'..

 $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

# this is on windows 10 1809
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @fbehrens, thank you for your feedback.

The Exchange Online PowerShell V2 module is currently in Preview and is not supported on PowerShell Core yet.
You need to use Windows PowerShell. Also, it would help if you send this feedback to:
exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam)

Thanks!

**Comment by yogkumgit** [comment]
@dariomws306 Thank you very much for the contribution and sharing this explanation. @fbehrens 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
