### ISSUE TITLE
Missing the AuthenticationPolicy Property

### ISSUE THREAD

**Issue by jdotto02** [MicrosoftDocs/office-docs-powershell#4838]
Please update this document with information on the AuthenticationPolicy property which is supported by at least the Get-User cmdlet. 

An example of how to filter users with this property can be seen on this page:
https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online#how-do-you-know-that-youve-successfully-disabled-basic-authentication-in-exchange-online

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://docs.microsoft.com/en-ca/powershell/exchange/exchange-server/recipient-filters/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4905

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @jdotto02 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
