### ISSUE TITLE
-Region parameter

### ISSUE THREAD

**Issue by scottclarke1** [MicrosoftDocs/office-docs-powershell#4840]
Hey Guys, 
The -Region parameter states that it is reserved for Microsoft internal use, yet the Configure Office 365 Multi Geo documentation for eDiscovery instructs the use of this parameter to permit eDiscovery managers to search outside of the central location and into a specified satellite. 
I think therefore that the documentation on this page may need updating to reflect.
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d1e90c0-2c33-4a3d-f159-a38b5c41bfdc
* Version Independent ID: 1e655960-0311-02bf-7c22-335a5c90cb04
* Content: [New-ComplianceSecurityFilter (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/New-ComplianceSecurityFilter?redirectedfrom=MSDN&view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSecurityFilter.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSecurityFilter.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@scottclarke1, I updated the description of the Region parameter in New-ComplianceSecurityFilter and Set-ComplianceSecurityFilter.

Thanks for the feedback.
