### ISSUE TITLE
Command not not apply when running some switched together 

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/office-docs-powershell#4842]
I am attempting to run the following command to enable sharing and setup a domain list:
set-SPOSite &lt;siteURL&gt; -SharingCapability ExternalUserSharingOnly -SharingDomainRestrictionMode AllowList -SharingAllowedDomainList  "contoso.com fabrikam.com"
 
When I run this it does not set the Sharing capability but also does not return any errors. 
 
Example when a individual site sharing is disabled and you try to enable sharing but limit by domain the sharing setting will not apply. The SPO tenant setting are set to allow for external sharing. The only way I can seem to get it to work is to run it twice first just to set sharing and then 2nd to set the domain list.
	
Enable the sharing - set-SPOSite &lt;siteURL&gt; -SharingCapability ExternalUserSharingOnly
Then setup domains - set-SPOSite &lt;siteURL&gt;  -SharingDomainRestrictionMode AllowList -SharingAllowedDomainList  "contoso.com fabrikam.com"

It seems if I run it all at once the sharing capability does not apply but the domain list will. Based on the first command example I should be able to run all these switches at once. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1c6b2b-5af6-acce-b7e8-bf784bb0973e
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by BrianTJackett** [comment]
I am able to repro the issue that @Padavid describes in my own lab tenant.  Looking at the underlying decompiled code for the PowerShell commandlet I don't see any red flags for code paths that would prevent both sharing capability and domain lists from being updated at the same time.  That may be a limitation of what I can see there though.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello everyone 👍 
I was able to reproduce this in my lab too.
As here we take care of cmdlet documentation, I decided to propose adding an example to the cmdlet's documentation to show this behavior, so we can provide a working solution to everyone reading the cmdlet's documentation, while @trent-green takes note and can inform the product group to find out if this is an intended behavior.
Thank you for your report!

**Comment by yogkumgit** [comment]
@tseward  and @dariomws306 Please review the PR #4887 Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Padavid Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
