### ISSUE TITLE
Some option produce error

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/office-docs-powershell#4845]
When using any of the below parameters an "Encountered an internal server error" occurs. We have found no solution but to leave out the parameters that cause issue, then the remainder of the other parameters will work without issue.
Parameters that cause error: City, CountryOrRegion, GeoCoordinates, PostalCode, State & Street

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ef4fb7-736b-99e8-796b-c1d02410a7e4
* Version Independent ID: 0fb75415-2bd2-a880-aa9e-a06c76d9ddc4
* Content: [Set-Place (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-place?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by NickDorak** [comment]
It appears that the troubled parameters cannot be used if the object is replicated from on-prem AD. Most of the fields can be set within the on-prem AD object and sync to Azure. This exception appears to be missing from the above documentation. 
However, the  "GeoCoordinates" parameter does not sync from on-prem AD and there appears to be no way to set this.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @NickDorak, thank you for your feedback.

We are working on it. Same as https://github.com/MicrosoftDocs/office-docs-powershell/issues/4780.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution. @NickDorak  Kindly check #4780 as PR is created and merged. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by NickDorak** [comment]
That just shows that the problem was ignored and marked "cloud only", which is not entirely true.
The options partially work for on-prem synced objects. There is an issue with Exchange where it thinks (incorrectly) that some fields are managed on-prem, then they are not. There is no way to set the GeoCoordinates filed for example.
This should be escalated to the product team so they can correct the problem. 
Also, the command should throw an appropriate error if using a parameter that can't be used.

**Comment by chrisda** [comment]
@NickDorak, you best option is to open a support case about this.
