### ISSUE TITLE
Connect-Microsoft teams fails to support Application and GCCHigh environment

### ISSUE THREAD

**Issue by mpoulson** [MicrosoftDocs/office-docs-powershell#4855]
When running
Connect-MicrosoftTeams -TeamsEnvironmentName TeamsGCCH -TenantID $tenantId -ApplicationID $applicationId -CertificateThumbprint $thumbPrint

Expected Result: GCCH supports Application based auth

**The result is** 
Connect-MicrosoftTeams : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ connect-microsoftteams -ApplicationId  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-MicrosoftTeams], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @mpoulson Mike 👍 How are you?

As you can see in the [official article](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps) of the cmdlet
_TeamsEnvironmentName_ and _ApplicationId/CertificateThumbprint_ params are on different parameter sets, so you can not use them on the same cmdlet run.

In case you want, you can suggest this to the Teams Product Group visiting [Teams UserVoice](https://microsoftteams.uservoice.com/)

Hope this info helps you

**Comment by yogkumgit** [comment]
@mpoulson  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
