### ISSUE TITLE
-WebTemplate Parameter

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/office-docs-powershell#4858]
In testing, it seems that a value of "1" is also accepted for the WebTemplate parameter, resulting in the Site Design showing up for Communication Site AND Team Site with O365 Group AND Team Site without Office 365 Group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58596a8-0429-e115-0dee-c970783ed80f
* Version Independent ID: 7dea06e7-3411-8b9b-8eea-af3cbc4c3f43
* Content: [Add-SPOSiteDesign (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spositedesign?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteDesign.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteDesign.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sparkitect Jim
How are you ? hope you are doing good.
I could also see this on my tests.
Thanks for reporting this, to my understanding, it could be accepted however if it is not documented probably it is not supported (yet) so I would like to request more information from @trent-green on this one to see if we have to update the documentation.
Thank you

**Comment by yogkumgit** [comment]
@trent-green Please add your comment. Thanks.

**Comment by yogkumgit** [comment]
@sparkitect Thank you for reporting this feedback here. This list is focused on content issues and I want to make sure your immediate product issue does not get lost in this list. If you would please open a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team
