### ISSUE TITLE
StartDate and EndDate parameters - what time zone?

### ISSUE THREAD

**Issue by franklesniak** [MicrosoftDocs/office-docs-powershell#4859]
I thought I would suggest adding a blurb explaining how this cmdlet interprets the StartDate and EndDate with regard to the local time zone, or UTC. It's not clear to me if there is any translation of time zones performed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d47105-b32e-f0f8-3e71-db411c6abe7c
* Version Independent ID: 338beb1b-1f13-0a77-9ac3-1c4fe542b612
* Content: [Search-UnifiedAuditLog (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/search-unifiedauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-UnifiedAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by franklesniak** [comment]
According to this blog, the cmdlet translates your local time zone automatically. It would still be nice to have some updated help text that states this.
https://blog.kloud.com.au/2019/02/06/office365-azurehybrid-building-an-automated-solution-to-pull-office-365-audit-logs/

**Comment by franklesniak** [comment]
OK, I've done some testing and can share the results.

Scenario: an action creates an event on Feb 9, 2020 at 4:05 PM US Central Standard Time (10:05 PM GMT).

From a system configured on US Central Standard Time:
`Search-UnifiedAuditLog -StartDate ([datetime]"2/9/2020 4:00 PM") -EndDate ([datetime]"2/9/2020 4:10 PM")`
will not contain the event (i.e., the time was not converted to UTC).

`Search-UnifiedAuditLog -StartDate ([datetime]"2/9/2020 4:00 PM").ToUniversalTime() -EndDate ([datetime]"2/9/2020 4:10 PM").ToUniversalTime()`
_does_ return the event

And if four hours have elapsed since the event and the current time is Feb 9, 2020 8:05 PM US Central Standard Time (Feb 10, 2020 2:00 AM GMT), then:
`Search-UnifiedAuditLog -StartDate ((Get-Date).AddHours(-4.25)) -EndDate ((Get-Date).AddHours(-3.75))`
also returns the event.

So the query behavior changes depending on how you approach the problem.

The timestamp in the results ("CreationDate") is always in UTC.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@franklesniak, it seems everything in on-prem Exchange Server and Exchange Online stores date/time in UTC. Exchange Server does a very good job of hiding this from you; most any cmdlet that has a date/time parameter seamlessly translates your local date/time/timezone settings back and forth between UTC, and you don't need to worry about it. Not so much in Exchange Online.

I updated the StartDate and EndDate parameter descriptions to say this (borrowed from another parameter):

The EndDate/StartDate parameter specifies the end/start date of the date range. Entries are stored in the unified audit log in Coordinated Universal Time (UTC). If you specify a date/time value without a time zone, the value is in UTC.

To specify a date/time value for this parameter, use either of the following options:

- Specify the date/time value in UTC: For example, `"2018-05-06 14:30:00z"`.

- Specify the date/time value as a formula that converts the date/time in your local time zone to UTC: For example, `(Get-Date "5/6/2018 9:30 AM").ToUniversalTime()`. For more information, see [Get-Date](https://go.microsoft.com/fwlink/p/?LinkID=113313).

If you don't include a timestamp in the value for this parameter, the default timestamp is 12:00 AM (midnight) on the specified date.

Is that OK?

**Comment by franklesniak** [comment]
This looks great. Thanks so much!

**Comment by chrisda** [comment]
Cool. Merging my changes and closing.

Thanks for the feedback.
