### ISSUE TITLE
-Filter with wildcards. 

### ISSUE THREAD

**Issue by BlasMS** [MicrosoftDocs/office-docs-powershell#4860]
The parameter -RecipientTypeDetails follow the same rules than -RecipientPreviewFilter for use wildcards with -filter:

-In cloud-based environments, you can't use a wildcard as the first character. For example, 'Sales*' is allowed, but '*Sales' isn't allowed.

-In on-premises Exchange, wildcards are valid only as the first or last character. For example, 'Sales*' or '*Sales' are allowed, but 'Sa*les' isn't allowed.

Could we check add to the document? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfd8c226-5efd-0f1b-425c-4baede68e191
* Version Independent ID: 1537b71f-7b9e-6cea-bb21-3cedeefbba08
* Content: [Get-Recipient (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/get-recipient?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Get-Recipient.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Get-Recipient.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by BlasMS** [comment]
![RecipientPreviewFilter](https://user-images.githubusercontent.com/60755302/74150825-a596f200-4c02-11ea-9ed7-01aeb19b056a.JPG)
![Get-RecipientOn-Prem](https://user-images.githubusercontent.com/60755302/74150868-c0696680-4c02-11ea-82c1-0dc7929e7f11.JPG)
![RecipientTypeDetails](https://user-images.githubusercontent.com/60755302/74150890-ccedbf00-4c02-11ea-99d5-68d7d56b90fc.JPG)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @BlasMS, thank you for your feedback.

Same as https://github.com/MicrosoftDocs/office-docs-powershell/issues/4861.

Try with:
"Get-Recipient -RecipientTypeDetails GroupMailbox -Filter "Name -like '*ammer'"

**Comment by BlasMS** [comment]
@dariomws306  thanks
