### ISSUE TITLE
Filterable properties for the filter parameter

### ISSUE THREAD

**Issue by BlasMS** [MicrosoftDocs/office-docs-powershell#4861]
Text string properties that accept wildcard characters require the -like operator (for example, "Property -like '*abc'"): 

Depends where environment is based the object:

-In cloud-based environments, you can't use a wildcard as the first character. For example, 'Sales*' is allowed, but '*Sales' isn't allowed.

-In on-premises Exchange, wildcards are valid only as the first or last character. For example, 'Sales*' or 'Sales' are allowed, but 'Sales' isn't allowed.

Could we check add to the document?

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://docs.microsoft.com/pt-pt/powershell/exchange/exchange-server/recipient-filters/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by BlasMS** [comment]
![RecipientPreviewFilter](https://user-images.githubusercontent.com/60755302/74150925-e1ca5280-4c02-11ea-911b-002a02fdb1ba.JPG)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @BlasMS, thank you for your feedback.

I have tried and I saw the same behavior in the cloud and on-premises, with -Filter and -RecipientPreviewFilter. You can use wildcard as the first and last character, not in the middle.

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @BlasMS Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by BlasMS** [comment]
Hi @dariomws306 In the middle returns nothing. 
@yogkumgit @dariomws306  Thanks ;)
