### ISSUE TITLE
ExchangeOnlineManagement 0.3555.1 connecting with MFA enabled account results in session refresh on every command

### ISSUE THREAD

**Issue by js-ware** [MicrosoftDocs/office-docs-powershell#4863]
Every command causes a refresh/relogin for the session:
"Creating a new Remote PowerShell session using MFA for implicit remoting of "Get-Mailbox" command ..."

And trying to pipe one command into another results in error "Cannot invoke the pipeline because the runspace is not in the Opened state. Current state of the runspace is 'Closed'."

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @js-ware, thank you for your feedback.

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, please send an email to exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @js-ware 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
