### ISSUE TITLE
Incorrect syntax in synopsis of command Set-UnifiedGroup

### ISSUE THREAD

**Issue by HansFChristiansen** [MicrosoftDocs/office-docs-powershell#4866]
Would be great if command synopsis matches the varying syntax applicable to parameters.
For example [-HiddenFromExchangeClientsEnabled] is incorrect when referring to the detailed documentation further down - it should instead read [-HiddenFromExchangeClientsEnabled[:$false]] indicating that to disable the function you append the flag with ":$false" and not " $false" as it is for e.g. the parameter -HiddenFromAddressListsEnabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd7d69db-be49-179e-94ce-635337c98d07
* Version Independent ID: 9e372e66-5c7e-4d9a-56de-a35ae353fa09
* Content: [Set-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-unifiedgroup?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@HansFChristiansen, that sounds interesting, but that's really more of an issue with the [platyPS](https://github.com/PowerShell/platyPS) tool that we now use to dump cmdlets to topics. Even back in the TechNet days, the internal tool we used simply used the value <SwitchParameter> with no further details about how it works.

In this specific case, the HiddenFromExchangeClientsEnabled parameter description clearly explains how to reverse/undo/disable the setting:

> To disable this setting, use this exact syntax: -HiddenFromExchangeClientsEnabled:$false.

That's standard for any/all switch parameters in all PowerShell environments, and that's very different from the HiddenFromAddressListsEnabled parameter, which is Boolean.

Thanks for the feedback.

**Comment by HansFChristiansen** [comment]
@chrisda I appreciate that the specific usage exists in the parameter specific documentation for the HiddenFromExchangeClientsEnabled parameter - I just voiced my own opinion that the synopsis, i.e. the part which lists all the parameters available, should mirror the option to have just include the parameter or append it with ":$false" when wanting to disable the parameter that hides the group from Exchange clients.

**Comment by chrisda** [comment]
@HansFChristiansen, duly noted.
