### ISSUE TITLE
Duplicated PowerShell commands

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/office-docs-powershell#4867]
The "This example connects to Exchange Online to manage another tenant" powershell command is identical the one preceeding it.. could you update with the correct example please? ta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@quickclix75, confirmed. I found the original update in a [previous pull request](https://github.com/MicrosoftDocs/office-docs-powershell/commit/c02e520c331ed85e44b8bdf83afb5de5d751b1e1#diff-56eb30a4f21b65b4b26120dd7425f2c6), so I just added it back.

Thanks for the feedback.
