### ISSUE TITLE
Using PowerShell 6 - Connect-PnPOnline fails Could not load type 'System.Security.Cryptography.X509Certificates.X509Certificate2UI'

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/office-docs-powershell#4872]
Hi
When using the new PowerShell 6 with Connect-PnPOnline it fails :_

Connect-PnPOnline : Could not load type 'System.Security.Cryptography.X509Certificates.X509Certificate2UI' from assembly 'System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
At line:1 char:1
+ Connect-PnPOnline -Url https://njpenterprises.sharepoint.com/marketin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], TypeLoadException
+ FullyQualifiedErrorId : System.TypeLoadException,SharePointPnP.PowerShell.Commands.Base.ConnectOnline

What other Modules should I have imported ?

Thanks

Nigel

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @NPrice99 Nigel, how are you? 👍
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by NPrice99** [comment]
Hi @get-itips The command works perfectly with the SharePoint Management shell.  The issue is with the PowerShell 6 not with the PnP team.

Regards

Nigel

**Comment by get-itips** [comment]
> Hi @get-itips The command works perfectly with the SharePoint Management shell. The issue is with the PowerShell 6 not with the PnP team.
> 
> Regards
> 
> Nigel

Nigel, every Product Team is responsible of porting its PowerShell module to the new version of PowerShell, in this case, version 6 introduces changes into its core (from .NET to dotnet core), besides that, in the other repo I pointed out, a member of PnP community will pick up your request and can give you information on when PS6 will be supported.
Hope this info helps you.

**Comment by NPrice99** [comment]
Ah ! Ok thanks.  I was not aware of the division of responsibilities.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @NPrice99 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
