### ISSUE TITLE
Private Channels

### ISSUE THREAD

**Issue by abdndamo** [MicrosoftDocs/office-docs-powershell#4874]
There is a new setting on the TEAMS manage channel interface that was introduced at the beginning of February and this cannot be handled via the Cmdlet.

"Allow members to create private channels"

Is this likely to be included?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @abdndamo 
How are you?
Here we handle documentation updates, I recommend checking the [Teams BETA module](https://www.poshtestgallery.com/packages/MicrosoftTeams) to see if the product group is working on adding that setting to the released version of Set-Team cmdlet.
Hope this info helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @abdndamo 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
