### ISSUE TITLE
Order of Add-TeamsUser

### ISSUE THREAD

**Issue by JohnGGeo** [MicrosoftDocs/office-docs-powershell#4877]
In the article it states,
> It doesn't work in the same way that the Teams application. If you add an owner in the application the user is also added as member to the unified group. Using this cmdlet, it will add the user only as an owner to the unified group, not as a member. Then you can run the cmdlet again to add the user as member.

I tried this and it added them as owners then made them members.
So should this actually be reverse and read something like,

> Then you can run the cmdlet first to add the user as a member then run again and make their role an owner?

In any case why have this? Why not add the user as a member of the unified group when you add them as an owner? Are there any cases I'm not thinking of that would necessitate adding the user only as an owner?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da0c53f2-1c62-14f6-6371-f54bf86b0c24
* Version Independent ID: aac162db-a9c0-fbfb-dd40-526e94d3bef8
* Content: [Add-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamuser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @JohnGGeo John
How are you? Hope you are doing great.
Please correct me if I misunderstood you.
I tried this 

> Using this cmdlet, it will add the user only as an owner to the unified group, not as a member. Then you can run the cmdlet again to add the user as member.

And it worked exactly like that with module version 1.0.3

I could also add first an user as member and then as owner.

The reason behind the cmdlet working like that is out of the scope of the documentation, however I do know that the team is working actively in changing the behavior of the -Role parameter, for example, see [this](https://github.com/MicrosoftDocs/office-docs-powershell/issues/4465#issuecomment-580313762).

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @JohnGGeo 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
