### ISSUE TITLE
Parameters not found

### ISSUE THREAD

**Issue by wiseleaf23** [MicrosoftDocs/office-docs-powershell#4880]
Could it be possible that this documentation is out of date? When creating a new anti-phish policy using this cmdlet, I get errors on the following parameters: -TreatSoftPassAsAuthenticated -EnableAuthenticationSafetyTip -EnableAuthenticationSoftPassSafetyTip

These return an error like:
A parameter cannot be found that matches parameter name 'EnableAuthenticationSoftPassSafetyTip'.
    + CategoryInfo          : InvalidArgument: (:) [New-AntiPhishPolicy], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-AntiPhishPolicy
    + PSComputerName        : outlook.office365.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 619a785f-92c9-70ca-f61f-39daff8bcd71
* Version Independent ID: b909fa38-411a-5bfd-d433-1e7e171ffaa9
* Content: [New-AntiPhishPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/new-antiphishpolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/New-AntiPhishPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/New-AntiPhishPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@wiseleaf23, there are a few different issues at play:

- The description for the _EnableAuthenticationSoftPassSafetyTip_ parameter says, "reserved for internal Microsoft use", which means, even if it's available to you, don't expect it to work. That appears to be the only one of these _Enable\<Whatver\>SafetyTip(s)_ parameters in this state, but that could change (see the next point).

  For what it's worth, I ran the following command in my stock E5 tenant without error:

  ```powershell
  Set-AntiPhishPolicy "Test Policy" -EnableAuthenticationSafetyTip $true -EnableAuthenticationSoftPassSafetyTip $true -EnableSimilarDomainsSafetyTips $true -EnableSimilarUsersSafetyTips $true -EnableUnusualCharactersSafetyTips $true
  ```

- Per this [GitHub Issue in another repo](https://github.com/MicrosoftDocs/microsoft-365-docs/issues/736), there's a lot of turmoil/upheaval in the Safety Tips world (many of the tips are no longer available). I'm trying to get more clarity.

**Comment by wiseleaf23** [comment]
@chrisda thank you for the quick response! In the GUI, it looks like these options are not available (anymore). We used to run a script with this cmdlet for our customers to enable ATP, but we got these errors today.

**Comment by chrisda** [comment]
Now in my test tenant, the EnableAuthenticationSafeTip and EnableAuthenticationSoftPassSafetyTip parameters are no longer available, so I've removed them from the New-AntiPhishPolicy and Set-AntiPhishPolicy cmdlet topics.

Closing.
