### ISSUE TITLE
-SharingAllowedDomainList Limited to 100 domains

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/office-docs-powershell#4883]
It appears that the -SharingAllowedDomainList is limited to only 100 domains. If I try and add 101 I get an error. However via the GUI it appears the limit is 1000 - https://docs.microsoft.com/en-us/sharepoint/restricted-domains-sharing#limiting-domains

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1c6b2b-5af6-acce-b7e8-bf784bb0973e
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello,
I could also reproduce, however, I could not set more than 100 domains also using the GUI, was the limit changed @MikePlumleyMSFT ? Thanks

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please confirm to Andres's observation.

**Comment by MikePlumleyMSFT** [comment]
@StephenRiceMSFT or @MSFTRafLop do you know what the current limit is for restricted domains sharing?

**Comment by MikePlumleyMSFT** [comment]
The limits are 3000 domains at the tenant level and 100 domains at the site level. I've submitted an update to [Restrict sharing of SharePoint and OneDrive content by domain](https://docs.microsoft.com/sharepoint/restricted-domains-sharing) to reflect those numbers.

**Comment by get-itips** [comment]
Thanks @MikePlumleyMSFT

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Padavid 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
