### ISSUE TITLE
Syntax error [winrm : Error: Invalid use of command line. Type "winrm -?" for help.]

### ISSUE THREAD

**Issue by netzoft** [MicrosoftDocs/office-docs-powershell#4884]
winrm set winrm/config/client/auth @{Basic="true"}
should be...
winrm set winrm/config/client/auth '@{Basic="true"}'

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Office 365 Security & Compliance Center PowerShell](https://docs.microsoft.com/en-gb/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md)
* Service: **o365-security-and-compliance**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@netzoft, I tested the original command as written in an elevated Command Prompt in Windows 10 Enterprise v1909, and it ran without error. When I ran your new suggestion with the single quotes, I received the same error as you.

**Comment by dariomws306** [comment]
@chrisda I tested on Win 10 1903, 1709, Win 2012 (not R2) and Win 2016 and needed to use the single quotes.

**Comment by dariomws306** [comment]
Hi @netzoft and @chrisda I just realized that I have test it on Windows PowerShell. You need to run this command in cmd as the article says:
"run this command **in a Command Prompt**"

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @netzoft 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by rvigliotti-sf** [comment]
And if you have variables in the winrm create cmd to specify a certificate for a HTTPS listener, you need to escape them. Example:

`winrm create winrm/config/Listener?Address=*+Transport=HTTPS '@{Hostname="'"$ENV:ComputerName"'";CertificateThumbprint="'"$($Cert.Thumbprint)"'"}'`
