### ISSUE TITLE
MoveToFolder example is inaccurate

### ISSUE THREAD

**Issue by NeedsCoffee** [MicrosoftDocs/office-docs-powershell#4886]
In order to use the -MoveToFolder switch one has to use the format "mailboxId:\ParentFolder\Folder", e.g. -MoveToFolder "postmaster:\Inbox\Alerts". If we use the example that's provided (e.g. "\Inbox\Alerts") then we get "The operation can't be performed on this object because its status isn't valid."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a1afe5f-8679-f208-71c8-aed7d058f152
* Version Independent ID: 66c54ea2-d6a2-4bc6-14d1-32fcaf01913c
* Content: [New-InboxRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/new-inboxrule?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/New-InboxRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/New-InboxRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4906 Thanks

**Comment by chrisda** [comment]
Topic updated. Thanks for the feedback.
