### ISSUE TITLE
Description for -UserList

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#4888]
Move-csUser have a parameter "-userList" but there seems to be no description how to use it:

```
**get-help move-csuser -Parameter userlist**

-UserList <String>
    PARAMVALUE: String

    Required?                    true
    Position?                    Named
    Default value
    Accept pipeline input?       False
    Accept wildcard characters?  false
```
Would you like to add that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c68752-3b36-518f-8cf1-7a4e2aa8cf15
* Version Independent ID: 98b9a798-e232-0b2c-ee0f-857071885c1d
* Content: [Move-CsUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Move-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Move-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @hirenshah1 Can you help us getting the description for it ?

**Comment by get-itips** [comment]
Finally we could get the description for the cmdlet, Pull Request referenced here. Once merged @yogkumgit please close.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Petri-X Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
.
