### ISSUE TITLE
Connect-PnPOnline gives same exception if site does not exist or if user does not have access

### ISSUE THREAD

**Issue by spoman007** [MicrosoftDocs/office-docs-powershell#4889]
When I am using below line
`Connect-PnPOnline -Url https://contoso.sharepoint.com -Credentials (Get-Credential)`

I am getting exception as 
**Connect-PnPOnline : The remote server returned an error: (401) Unauthorized.**

I get this exception in following cases
1. If the user does not have access to site
2. If the site does not exists

I need to check if site exists, I was expecting a 404 if it does not exists.
Is there a way in PNP to check if site does exists

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @spoman007 Sandeep, how are you? 👍
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by spoman007** [comment]
@get-itips Thank you!! I was not sure if it was a missing documentation or an actual issue.
I will open a ticket there.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @spoman007 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
