### ISSUE TITLE
Missing OutlookMobile parameters

### ISSUE THREAD

**Issue by plangone22** [MicrosoftDocs/office-docs-powershell#4890]
I found that these two parameters are available in the cmdlet, but are not documented here:
OutlookMobileHelpShiftEnabled
OutlookMobileSingleAccountEnabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3ab3f0-cc05-e279-8876-6da0b323bcac
* Version Independent ID: bfb49814-d60b-564a-25cc-f902dfa42b10
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #4909 Thanks

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and updating the documentation with PR. @plangone22 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
