### ISSUE TITLE
Conflicting information on mobile client availability

### ISSUE THREAD

**Issue by forminasage** [MicrosoftDocs/office-docs-powershell#4891]
In the top of the document, a note states that call parking is available on mobile clients (true). However, under the "Description" heading, another note says call parking is NOT available in mobile clients (false).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d81650e5-6a66-6730-57ea-80c7f01a6b06
* Version Independent ID: c128f89d-e3b7-677b-7643-8e8132f41209
* Content: [Set-CsTeamsCallParkPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallparkpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsCallParkPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsCallParkPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @forminasage Brandon, how are you? 👍 
I created a pull request to update the article removing the conflicting note.
Thanks for noticing.

**Comment by yogkumgit** [comment]
@tomkau Please merge this PR #4901 Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @forminasage Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
