### ISSUE TITLE
Remove-SPOSiteGroup does not appear to work in SharePoint Online

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/office-docs-powershell#4893]
When testing this cmdlet, I receive a 'Group not found error' (see below).  I also tried providing the Group email address as the Identity parameter, but got the same error.  

I found [this StackOverflow thread](https://sharepoint.stackexchange.com/questions/249092/remove-office365-group-connection-from-site-collection) indicating others users have had a similar experience.

![image](https://user-images.githubusercontent.com/38665906/74483782-666fd780-4e74-11ea-92fd-67dac80cdfa1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b84392a-eba7-4b55-6da1-920a487e86ef
* Version Independent ID: 61bff715-8d49-ad01-d020-5e8e0b19e546
* Content: [Remove-SPOSiteGroup (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spositegroup?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteGroup.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @TracyGH Tracy, how are you? 👍 

In my tests, I was able to remove **SharePoint Groups** created, for example from 

![image](https://user-images.githubusercontent.com/36666927/74536042-e04ba380-4efc-11ea-937a-dfcd17fa28cf.png)

If the group you are trying to remove does not show up when running _Get-SPOSiteGroup_, I don't think it will be available to be removed using that cmdlet.

Hope this information helps you. Besides that, I did not identify an update to the article is necessary.

**Comment by TracyGH** [comment]
Thanks for the response @get-itips!  I see the problem, it's only for removing SharePoint groups - not O365 groups.  I needed something different, which does not appear to be possible.

**Comment by ChrisG42** [comment]
I've found out what you need to do here - use Remove-SPOUser with the -LoginName given as the "siteSecurityGroupLoginName" attribute. You can find this by browsing the site permissions in SharePoint and checking the User/Group properties e.g.

![image](https://user-images.githubusercontent.com/70650815/170684057-5e5b2d22-dbe7-47a2-ad74-1dd10663c2d8.png)

You need that whole string in quotes "c:0t.c|tenant|<ID>" to be able to remove it.
