### ISSUE TITLE
Example 3 wrong

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/office-docs-powershell#4894]
I think the example 3 should be corrected instead of -Filter it should be -SiteUrl.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f480c3ac-70f4-dd19-e86c-7d95821eb901
* Version Independent ID: 64961e66-bdd4-d9ac-c62d-131dbb13092b
* Content: [Get-SPOExternalUser (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spoexternaluser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOExternalUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOExternalUser.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Padavid how are you ? 👍 
Thanks for noticing, I created a pull request to correct the article.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Padavid Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
