### ISSUE TITLE
How to add guest to team

### ISSUE THREAD

**Issue by moegitree** [MicrosoftDocs/office-docs-powershell#4895]
This cmd may cannot be used to add guest to existing team, is that correct?
Need to be clarified in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da0c53f2-1c62-14f6-6371-f54bf86b0c24
* Version Independent ID: aac162db-a9c0-fbfb-dd40-526e94d3bef8
* Content: [Add-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamuser?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Add-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @moegitree how are you ? 👍 
I am proposing thru a PR improving the description for user parameter.
Thank you

**Comment by kenwith** [comment]
It is a really good question and I am not sure if there is a way to invite a guest user to a team using powershell. Do you know @get-itips ?  I can try to track down someone on that team and find out so we can add information if it is possible or not.

**Comment by get-itips** [comment]
@kenwith I am afraid that isn't possible at the time with the current and beta versions of the Teams PowerShell, however we could try, as you said, to track down someone on the team to know if that is on the roadmap.

**Comment by kenwith** [comment]
Ok, thank you. And @moegitree thank you for the idea. I look forward to updating the docs if this becomes possible with this cmdlet.
