### ISSUE TITLE
Set-PnPTenantSite -DisableCompanyWideSharingLinks

### ISSUE THREAD

**Issue by kkazala** [MicrosoftDocs/office-docs-powershell#4897]
Does it override the CompanyWideSharingLinks for all existing sites, in effect calling
Set-SPOSite -Identity &lt;site&gt; -DisableCompanyWideSharingLinks
for each site? Or does it change the setting tenant wide (???) enforcing it for new sites as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a3421f8-18a1-e826-41d2-99ca3e54a468
* Version Independent ID: c47284f0-fa03-017c-4873-f11a5090c75e
* Content: [Set-PnPTenantSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnptenantsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPTenantSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPTenantSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @spoman007 Sandeep, how are you? 👍
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @kkazala 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by kkazala** [comment]
@yogkumgit 
Yes, I do believe the update to documentation is needed. This is why I reported this issue from within the documentation page
May I ask you to look into this? Thank you in advance :)

**Comment by get-itips** [comment]
@kkazala 
Documentation for PnP cmdlets is directly referenced from the PnP source code that is in the repo I pointed out.

**Comment by yogkumgit** [comment]
@kkazala kindly follow the link Andres has suggested. Thanks.

**Comment by kkazala** [comment]
At the bottom of the https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnptenant?view=sharepoint-ps page, there's a Feedback section which we can use to report issues. 
And as a customer, I expect to report the issue there, and Microsoft to either respond or to reassign the issue to another repo
Instead you tell me that it's my job to report the issue again? And you prefer to write me 5 different messages telling me where to report it again, instead of just doing it yourself? 
Wow
I'm just going to test it by myself, it's easier and faster
thank you for your time

**Comment by get-itips** [comment]
> At the bottom of the https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnptenant?view=sharepoint-ps page, there's a Feedback section which we can use to report issues.
> And as a customer, I expect to report the issue there, and Microsoft to either respond or to reassign the issue to another repo
> Instead you tell me that it's my job to report the issue again? And you prefer to write me 5 different messages telling me where to report it again, instead of just doing it yourself?
> Wow
> I'm just going to test it by myself, it's easier and faster
> thank you for your time

Hello @kkazala Kinga, how are you ? 👍 
I can understand your frustration, you are right, the feedback section leads you here, as the team behind it is working on a solution, I was instructed to kindly redirect anyone to the right place where they will get an answer. I am a collaborator on this repo and I try to do my best.

Hope this clarifies it to you, have a nice day!
