### ISSUE TITLE
The Example is incorrect

### ISSUE THREAD

**Issue by bongo-ho** [MicrosoftDocs/office-docs-powershell#4898]
This commandlet requires GUIDs, not fully qualified paths. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e1f526-1699-9e88-7a9e-e217496a38b3
* Version Independent ID: 8a3d9cf2-eaad-77a2-183e-c72bf69f555f
* Content: [Add-SPOHubToHubAssociation (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spohubtohubassociation?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubToHubAssociation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubToHubAssociation.md)
* Service: **sharepoint-powershell**
* GitHub Login: @
* Microsoft Alias: ****

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @bongo-ho how are you?
Tried it in my lab and could not use GUIDs or Urls, I received 

> Add-SPOHubToHubAssociation : Method "ConnectHubSiteToHubSiteById" does not exist.

Did you experience this?

@trent-green how are you? is this cmdlet part of the non-ready for production list? 

Thanks

**Comment by bongo-ho** [comment]
Yes, I also got the error that the method was not implemented.

Thanks
Jonathan


Jonathan | 📨: jonathan@timewespoke.com | 📞: 021 955 738 | L: LinkedIn.com/in/jonathanstuckey | ☕ Latté, 1 sugar

Stuck with Outlook for Android<https://aka.ms/ghei36>. 🙄

________________________________

**Comment by trent-green** [comment]
@get-itips thanks for including me.  

You are correct: this is a placeholder and not production-ready yet :)

**Comment by get-itips** [comment]
Hello @trent-green thanks for sharing that information.
We will proceed to close this for now then @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @bongo-ho 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ITGeekBrian** [comment]
I am running into an issue when attempting to associate a Hub site with another Hub site.  The documentation (https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spohubtohubassociation?view=sharepoint-ps) says to use to the urls as the source and target - this however does not work.

I was redirected to this article as "It seems that the cmdlet “Add-SPOHubToHubAssociation” is not yet ready for production. "  Is there a current way to associate Hub sites?

**Comment by bongo-ho** [comment]
That's fine but can we please put an indication on online docs and the cmdlet help to say its not implemented rather than as an error msg?

The documentation online read like this was usable - and its not.

Also do we have a guesstimate on te timeline for availability of the feature? Obviously sooner rather than later, otherwise the placeholder would not be published...

Cheers
Jonathan


Jonathan | 📨: jonathan@timewespoke.com | 📞: 021 955 738 | L: LinkedIn.com/in/jonathanstuckey | ☕ Latté, 1 sugar

Stuck with Outlook for Android<https://aka.ms/ghei36>. 🙄

________________________________

**Comment by get-itips** [comment]
@trent-green can we get an estimation on when this is expected to be released? Thanks

**Comment by get-itips** [comment]
The cmdlet now outputs a different error message stating that this is not yet implemented

`Add-SPOHubToHubAssociation : The method or operation is not implemented.`

Will also update the article thru a PR. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ITGeekBrian Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mahajangaurav** [comment]
> @trent-green can we get an estimation on when this is expected to be released? Thanks

Hi! I have the same question - is there an ETA regarding this? Thanks!
