### ISSUE TITLE
Connect to Exchange Online PowerShell using multi-factor authentication

### ISSUE THREAD

**Issue by palphonso** [MicrosoftDocs/office-docs-powershell#4902]
The new way of connecting broke all our scripts.
How can we import the new module into ISE?
The module location seems to have changed again and I am unable to figure out how to import it.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by palphonso** [comment]
I am referring to this which now uses Connect-EXOPSSession and the Exchange Online Remote PowerShell Module.

https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps

Because of this, the following article doesn't work anymore.

https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window

**Comment by dariomws306** [comment]
Hi @palphonso, thank you for your feedback.

Feedback section in docs.microsoft.com is there to help to improve documentation. I cannot provide you help with your scripts but I can suggest other channels, like:
https://techcommunity.microsoft.com/

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @palphonso Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
