### ISSUE TITLE
User does not need to be a Global Admin

### ISSUE THREAD

**Issue by Somu76** [MicrosoftDocs/office-docs-powershell#4907]
The statement "You must be a SharePoint Online global administrator to run the cmdlet." is confusing as it seems to imply that you have to be a Global Administrator to run this, since you actually only need to have the "SharePoint Administrator" role in the tenant to use this. Can you confirm and change appropriately.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Somu76 How are you? 👍 
Your description is missing the referenced article, can you please paste the url here?
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @Somu76  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
