### ISSUE TITLE
Unable to set LineURI

### ISSUE THREAD

**Issue by marcos-nuga** [MicrosoftDocs/office-docs-powershell#4912]
Hi,

Unable to set "LineURI". This parameter is restricted within Remote Tenant PowerShell.

How can I clean a LineURI from an User?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @marcos-nuga 
Your description is missing the referenced article on Docs, can you please paste the url of the article here? 
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @marcos-nuga  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
