### ISSUE TITLE
AutoEnableArchiveMailbox still not functional

### ISSUE THREAD

**Issue by scottclarke1** [MicrosoftDocs/office-docs-powershell#4920]
Hey Guys

Please see this for context;
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3600

Can you please provide an update on when this functionality is likely to land? This is key in automating the user provisioning process and there has been no publicized update since July 2019. I've tested this in my tenant and the behaviour is still as @dustindortch mentions.

Please advise what method should be used for automated enablement of the in place archive in lieu of this functionality.

Thanks,

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
No ETA. The advice is to use the bulk enable method as described here: <https://docs.microsoft.com/microsoft-365/compliance/enable-archive-mailboxes#enable-archive-mailboxes>

Closing

**Comment by bmoskal88** [comment]
I still can't find any official mention of what the parameter should be, but I came across those with trial and error.
It worked for me. Hope it helps

To enable:  Set-OrganizationConfig -AutoEnableArchiveMailbox 1  
To Disable:  Set-OrganizationConfig -AutoEnableArchiveMailbox 0

**Comment by tylermontneyacc** [comment]
2 years later and [this](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps#parameters) is still listed as "This parameter is reserved for internal Microsoft use".

What's its status?

**Comment by chrisda** [comment]
@tylermontneyacc, the best way to get an answer is to open a support ticket and ask. Although the Tier 1 person might not be able to help you, when they escalate it, it will get in front of the right people to answer the question.

**Comment by tylermontneyacc** [comment]
Response from support was what I expected:

- Still in development
- No clue as to why the parameter is exposed
- Parameter is for what we think it is

Best workaround is to run a script on schedule to check for new users.
