### ISSUE TITLE
New-CsMediaConfiguration and Set-CsMediaConfguration Pages missing data

### ISSUE THREAD

**Issue by Atreidae** [MicrosoftDocs/office-docs-powershell#4924]
The parameter EnableRtpRtcpMultiplexing has no context on both pages, simply listing as a True/False toggle. No indication on how media is bundled together etc.

![image](https://user-images.githubusercontent.com/8736291/74698004-7f9bce00-5250-11ea-9d2f-46d3639672e0.png)

There parameter EnableVideoBasedSharing on the Set-CsMediaConfiguration page hasn't been filled in at all. No indication of what switching VBSS on or off would do.

![image](https://user-images.githubusercontent.com/8736291/74697986-727edf00-5250-11ea-9621-ffdf65b3d1e6.png)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Atreidae James. How are you? 👍 Thanks for reporting this.
I created a pr proposing a description for both parameters, if it gets approved, they will be reflected on the online version of those articles.
Thanks

**Comment by Atreidae** [comment]
Oh, I didn't realise that we can submit PR's 
Looks like it got merged, I'm cool to close this issue now.
Thanks.
