### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/office-docs-powershell#4926]
I don't see a parameter here for the Version of the Site Script... does SharePoint manage that for me, or will it always be 0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb8de8fb-e92b-a19e-7284-d4f3349b8a51
* Version Independent ID: cbeadec1-6bb8-4b08-846c-48c76d946f5d
* Content: [Add-PnPSiteScript (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpsitescript?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPSiteScript.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPSiteScript.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sparkitect Jim 👍 how are you?

I will need to kindly ask you to visit this other [repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues or PnP Documentation Issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @sparkitect 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
