### ISSUE TITLE
SPO Management PowerShell Module Version 16.0.19724.1200 - 6 cmdLets not documented

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#4930]
There are 6 new cmdLets in version 16.0.19724.12000:

- Get-SPOTenantOrgRelation                         
- Get-SPOTenantOrgRelationByPartner                
- Get-SPOTenantOrgRelationByScenario               
- New-SPOTenantOrgRelation                         
- Remove-SPOTenantOrgRelation                      
- Verify-SPOTenantOrgRelation

There is no documentation available.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by andikrueger** [comment]
@trent-green could you follow up on these articles with details for the documentation?

**Comment by get-itips** [comment]
Hello @andikrueger Andi, how are you? 👍 
Talked with the team and we decided that, in this case, we will add a preview only notice for now, as these cmdlets are not yet ready to be used.
The documentation will be upgraded when they become ready and we have feedback from the product team.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @andikrueger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
