### ISSUE TITLE
QueryWindowInDays parameter now not optional

### ISSUE THREAD

**Issue by mrik23** [MicrosoftDocs/office-docs-powershell#4932]
Seems like since early this month, we have to supply QueryWindowInDays when using this cmdlet, it was not the case before. Can you recheck and update this page if that's not the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae873e5c-9f55-966b-1519-04bd3cb7dce4
* Version Independent ID: 8f35c374-2608-6414-5987-cbedd7b46cf0
* Content: [Remove-CalendarEvents (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/remove-calendarevents?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Remove-CalendarEvents.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Remove-CalendarEvents.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mrik23** [comment]
This is for Exchange Online.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@mrik23, confirmed. The topic was updated on 12/16 to change the QueryWindowInDays parameter from optional to required. <https://github.com/MicrosoftDocs/office-docs-powershell/commit/69e56cb79ba2781a2cb869c2f2e9c5e090a179f3#diff-6e7743df5b89256b212c768aaf6901c2>.

Thanks for the feedback.

Closing
