### ISSUE TITLE
Importing MicrosoftTeams PowerShell module fails when signed scripts are required

### ISSUE THREAD

**Issue by ekdegerman** [MicrosoftDocs/office-docs-powershell#4933]
The MicrosoftTeams PowerShell module fails to import if you have your execution policy set to AllSigned. The error message refers to a bunch of ps1xml files that are unsigned. Other PowerShell modules delivered by Microsoft, e.g. Microsoft.Online.SharePoint.PowerShell and SharePointPnPPowerShellOnline are properly signed and can be imported even with these more secure PowerShell settings.
![image](https://user-images.githubusercontent.com/56835119/74831376-6a3ca780-5315-11ea-9f67-5fe3e8776e7a.png)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ekdegerman how are you? 👍 
Here, we only handle documentation issues, however, I managed to pass this information to the Product Team, and now they are aware of this, as an internal issue has been created.
Thanks for reporting this.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ekdegerman 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
