### ISSUE TITLE
Please add support for additional commands

### ISSUE THREAD

**Issue by HyperionCruiser** [MicrosoftDocs/office-docs-powershell#4935]
I would like to be able to set all parameters in the default cas mailbox plan.  Could you please look into supporting other parameters to set in the plan like you do for the set-casmailbox:
   [-Identity] &lt;MailboxIdParameter&gt;
   [-ActiveSyncAllowedDeviceIDs &lt;MultiValuedProperty&gt;]
   [-ActiveSyncBlockedDeviceIDs &lt;MultiValuedProperty&gt;]
   [-ActiveSyncDebugLogging &lt;Boolean&gt;]
   [-ActiveSyncEnabled &lt;Boolean&gt;]
   [-ActiveSyncMailboxPolicy &lt;MailboxPolicyIdParameter&gt;]
   [-ActiveSyncSuppressReadReceipt &lt;Boolean&gt;]
   [-Confirm]
   [-DisplayName &lt;String&gt;]
   [-DomainController &lt;Fqdn&gt;]
   [-ECPEnabled &lt;Boolean&gt;]
   [-EmailAddresses &lt;ProxyAddressCollection&gt;]
   [-EmwsEnabled &lt;Boolean&gt;]
   [-EwsAllowEntourage &lt;Boolean&gt;]
   [-EwsAllowList &lt;MultiValuedProperty&gt;]
   [-EwsAllowMacOutlook &lt;Boolean&gt;]
   [-EwsAllowOutlook &lt;Boolean&gt;]
   [-EwsApplicationAccessPolicy &lt;EwsApplicationAccessPolicy&gt;]
   [-EwsBlockList &lt;MultiValuedProperty&gt;]
   [-EwsEnabled &lt;Boolean&gt;]
   [-HasActiveSyncDevicePartnership &lt;Boolean&gt;]
   [-IgnoreDefaultScope]
   [-ImapEnabled &lt;Boolean&gt;]
   [-ImapEnableExactRFC822Size &lt;Boolean&gt;]
   [-ImapMessagesRetrievalMimeFormat &lt;MimeTextFormat&gt;]
   [-ImapForceICalForCalendarRetrievalOption &lt;Boolean&gt;]
   [-ImapSuppressReadReceipt &lt;Boolean&gt;]
   [-ImapUseProtocolDefaults &lt;Boolean&gt;]
   [-IsOptimizedForAccessibility &lt;Boolean&gt;]
   [-MAPIBlockOutlookExternalConnectivity &lt;Boolean&gt;]
   [-MAPIBlockOutlookNonCachedMode &lt;Boolean&gt;]
   [-MAPIBlockOutlookRpcHttp &lt;Boolean&gt;]
   [-MAPIBlockOutlookVersions &lt;String&gt;]
   [-MAPIEnabled &lt;Boolean&gt;]
   [-MapiHttpEnabled &lt;Boolean&gt;]
   [-Name &lt;String&gt;]
   [-OutlookMobileEnabled &lt;Boolean&gt;]
   [-OWAEnabled &lt;Boolean&gt;]
   [-OWAforDevicesEnabled &lt;Boolean&gt;]
   [-OwaMailboxPolicy &lt;MailboxPolicyIdParameter&gt;]
   [-PopEnabled &lt;Boolean&gt;]
   [-PopEnableExactRFC822Size &lt;Boolean&gt;]
   [-PopForceICalForCalendarRetrievalOption &lt;Boolean&gt;]
   [-PopMessagesRetrievalMimeFormat &lt;MimeTextFormat&gt;]
   [-PopSuppressReadReceipt &lt;Boolean&gt;]
   [-PopUseProtocolDefaults &lt;Boolean&gt;]
   [-PrimarySmtpAddress &lt;SmtpAddress&gt;]
   [-PublicFolderClientAccess &lt;Boolean&gt;]
   [-ResetAutoBlockedDevices]
   [-SamAccountName &lt;String&gt;]
   [-ShowGalAsDefaultView &lt;Boolean&gt;]
   [-SmtpClientAuthenticationDisabled &lt;Boolean&gt;]
   [-UniversalOutlookEnabled &lt;Boolean&gt;]
   [-WhatIf]
   [&lt;CommonParameters&gt;]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07f6d529-3fc4-9ab8-d1e7-53dee583e32c
* Version Independent ID: e7fa50a4-2123-fa59-fd73-496bdb7b50c9
* Content: [Set-CASMailboxPlan (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-casmailboxplan?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/client-access/set-CASMailboxPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/set-CASMailboxPlan.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@HyperionCruiser, there was a period of time when all of those additional settings were supported. Then, about 4 years ago, most of them were removed (I was the one who removed them). This was obviously an active an conscious decision, although I don't know what that was.

There's nothing we can do about this from a documentation perspective, so closing.

Thanks for the feedback.

**Comment by HyperionCruiser** [comment]
Would you be willing to add just a couple back in then.
UniversalOutlookEnabled
EwsEnabled
OutlookMobileEnabled
OWAEnabled

**Comment by chrisda** [comment]
I am but a lowly writer. If you want code updated to allow these values in Set-CasMailboxPlan, you should open a Support Ticket.
