### ISSUE TITLE
Support for setting -RecipientLimits in Exchange Online

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/office-docs-powershell#4936]
The RecipientLimits param should be updated to reflect info posted on the Exchange Team blog:
https://techcommunity.microsoft.com/t5/exchange-team-blog/customizable-recipient-limits-in-office-365/ba-p/1183228

Limits can now be set in Exchange Online; the default limit can be lowered and a max value of 1000 recipients is now supported.

Thank you,
Keith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5b0c5d-0466-d55a-1f7b-0b2d25a316fd
* Version Independent ID: 07b0c093-eb6b-4834-3cd4-d8f2af6ca0f5
* Content: [Set-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@mrkeiths, I see. The parameter has changed from on-prem only to on-prem + cloud, with different value behavior. I updated the topic.

Thanks for the feedback.

Closing
