### ISSUE TITLE
Problem creating Communication Site where owner UPN is different from e-mail address

### ISSUE THREAD

**Issue by BombPAC** [MicrosoftDocs/office-docs-powershell#4938]
I am using New-PnPTenantSite to create a site with a Communication Site (SITEPAGEPUBLISHING#0) template. I'm trying to set an owner who has a different user name UPN (@domain.com) to their e-mail address (@domain.onmicrosoft.com). The site is created successfully but has the owner is assigned with NT Service\sptimerv4 instead of the actual owner account. 

Other comments:
- When I try and create a site with a Team Site (STS#3) template, it assigns the owner correctly 
- When I try and create a site with a Communication Site template and the user has the same UPN and e-mail address (both are @domain.onmicrosoft.com) it assigns the owner correctly
- I am connecting to the tenant with a client ID and certificate thumbprint

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @BombPAC how are you ? 👍 
I will need to kindly ask you to visit this other [repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues or PnP Documentation Issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @BombPAC 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
