### ISSUE TITLE
Get-TeamHelp not returning all possible commands

### ISSUE THREAD

**Issue by markgort86** [MicrosoftDocs/office-docs-powershell#4940]
This command-let is not returning all possible commands that are available within Microsoft Teams. Only the ones that are visible below: 
Get-TeamHelp
Connect-MicrosoftTeams
Disconnect-MicrosoftTeams
Get-Team
Get-TeamUser
Get-TeamChannel
New-Team
New-TeamChannel
Add-TeamUser
Remove-Team
Remove-TeamChannel
Remove-TeamUser
Set-Team
Set-TeamChannel
Set-TeamArchivedState

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab658c47-3403-b6bc-36b3-cd6ad656ba7f
* Version Independent ID: 4676fdae-f3a1-a1da-e4d0-b4f815bd7c04
* Content: [Get-TeamHelp (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamhelp?view=teams-ps&source=docs#feedback)
* Content Source: [teams/teams-ps/teams/Get-TeamHelp.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamHelp.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @markgort86 Mark 👍 how are you?
I'll try to pass this on to the Product Team for review, as I could repro.
Thank you

**Comment by get-itips** [comment]
Hello @markgort86 Mark 👍 
I managed to inform the Product Team, and an internal issue has been created.
In the meantime, this can be used, in case anyone reads this issue thread

`Get-Command -Module MicrosoftTeams`

Thank you

**Comment by markgort86** [comment]
@get-itips thanks for you're feedback and the information to the product team :-)

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @markgort86 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
