### ISSUE TITLE
Need to force Modern auth on client when using Get-Credential

### ISSUE THREAD

**Issue by bwar01** [MicrosoftDocs/office-docs-powershell#4943]
When connecting with username and password:
$adminUPN="<the full email address of a SharePoint administrator account, example: jdoe@contosotoycompany.onmicrosoft.com>"
$orgName="<name of your Office 365 organization, example: contosotoycompany>"
$userCredential = Get-Credential -UserName $adminUPN -Message "Type the password."
Connect-SPOService -Url https://$orgName-admin.sharepoint.com -Credential $userCredential

The following registry needs to be added to force modern auth
HKEY_CURRENT_USER\Software\Microsoft\SPO\CMDLETS]
"ForceOAuth"=dword:00000001

Once this is done, username and password works along with using stored Credentials in Credential Manager (CredentialManager Module).

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @bwar01 how are you? 👍 

I see that documented [here](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/security/cannot-force-modern-authentication)

Proposed thru a PR adding a link to that article on the Connect to SharePoint Online article.

**Comment by yogkumgit** [comment]
@dariomws306 and @tseward Plese review this PR #4954 Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @bwar01 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
