### ISSUE TITLE
Adding EXOPSession Module to Windows Terminal

### ISSUE THREAD

**Issue by ScriptedAdventures** [MicrosoftDocs/office-docs-powershell#4947]
Unable to add this shell to Windows Terminal.
Would be ideal to have this module included in Terminal as this is meant to be the one stop shop for shells.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment]
Hi @ScriptedAdventures, thank you for your feeback.

The best place to request new features or report issues for Windows Terminal is:
https://github.com/microsoft/terminal/issues

**Comment by dariomws306** [comment]
More information:
https://github.com/microsoft/terminal/issues/3572

**Comment by yogkumgit** [comment]
@dariomws306  Thank you very much for the contribution and sharing this explanation. @ScriptedAdventures Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
