### ISSUE TITLE
-StartAfter

### ISSUE THREAD

**Issue by dusansk** [MicrosoftDocs/office-docs-powershell#4949]
-StartAfter is not available in Exchange 2013 CU15 (A parameter cannot be found that matches parameter name 'StartAfter') nor Exchange 2019 CU4. -StartAfter is available in Set-MoveRequest but not Set-MigrationBatch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b745608-183e-f65c-6902-c691f9234c80
* Version Independent ID: 365b7127-cc37-a0bc-56d6-08a03fadda07
* Content: [Set-MigrationBatch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/set-migrationbatch?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/Set-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/Set-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4947

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@dusansk, the StartAfter parameter is available to me on a 2013 CU15 server and a 2019 CU4 server on the Set-MigrationBatch cmdlet.

I ran the following command on the 2013 and 2019 servers, and I got the same result.

```powershell
[PS] C:\>Get-ManagementRoleEntry *\* -Parameters StartAfter | ft name,role

Name                         Role
----                         ----
Set-MigrationBatch           Migration
New-MigrationBatch           Migration
Set-MoveRequest              Move Mailboxes
New-MoveRequest              Move Mailboxes
New-MailboxRelocationRequest Move Mailboxes
```

If you run this command in your environment, what do you see?

**Comment by dusansk** [comment]
@chrisda 
When I run your command I get the same result:
[PS] C:\Windows\system32>Get-ManagementRoleEntry *\* -Parameters StartAfter | ft name,role

Name                         Role
----                         ----
New-MigrationBatch           Migration
Set-MigrationBatch           Migration
Set-MoveRequest              Move Mailboxes
New-MoveRequest              Move Mailboxes
New-MailboxRelocationRequest Move Mailboxes

But when I want to use it, it doesn't work.

[PS] C:\Windows\system32>Set-MigrationBatch "XXX_DB_02" -StartAfter "02/21/2020 7:00 PM"
A parameter cannot be found that matches parameter name 'StartAfter'.
    + CategoryInfo          : InvalidArgument: (:) [Set-MigrationBatch], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-MigrationBatch
    + PSComputerName        : serverX.domain.com

**Comment by chrisda** [comment]
Topic updated.

Thanks for the feedback.

Closing
