### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by kczauz** [MicrosoftDocs/office-docs-powershell#4951]
Does not seem to work correctly.  I am not in a channel, yet it says I am a member of that channel.  This is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec48e6b6-c93b-a0f1-0144-978ea434b3f0
* Version Independent ID: 28ecb86c-661d-c0ee-6b2c-956c97d02352
* Content: [Get-TeamChannelUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamchanneluser?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Get-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @kczauz How are you? Hope you are doing good. 👍 
Here, we can handle documentation issues, for example, typos or missing information.
For cmdlet-specific issues, I will need to kindly redirect you to create a support ticket directly on your tenant, there, you will receive support about that behavior.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @kczauz 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
