### ISSUE TITLE
The target URL must be the root site or the search center site

### ISSUE THREAD

**Issue by gasperj** [MicrosoftDocs/office-docs-powershell#4955]
Please make this document clear that the command is only valid for swapping the root site or the search center site. (Or better, remove the limitation.) Thanks.

Invoke-SPOSiteSwap : The target URL must be the root site or the search center site
At line:1 char:1
+ Invoke-SPOSiteSwap -SourceUrl $source -TargetUrl $dest -ArchiveUrl $a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-SPOSiteSwap], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.SwapSite

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb8f8e8-1242-363c-be77-038142b4efb9
* Version Independent ID: 54a60006-3d61-4bb9-a040-60fe77ef9f85
* Content: [Invoke-SPOSiteSwap (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/invoke-spositeswap?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md)
* Service: **sharepoint-powershell**
* GitHub Login: @WayneEwington
* Microsoft Alias: **waynewin**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @gasperj Joe how are you ?
Document already has that information

> The target site must be the either:

> The root site at https://tenant-name.sharepoint.com; or
> The search center site at https://tenant-name.sharepoint.com/search.

**Comment by gasperj** [comment]
Agreed. It could be clearer if that key point was in the description. You can close. Thanks.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @gasperj 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by kk-sdsu** [comment]
Why hello there. I think you should have done this three months ago. I just submitted an issue for this exact same thing. Didn't see this existing issue before submitting mine. I sure hope you address this issue now, because it is an issue for your users.
