### ISSUE TITLE
Get-Team Parameter Visibility Accepted Values

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#4956]
While investigating an issue in the Office365DSC repo, I noticed that the `Get-Team` `Visibility` parameter accepts the value `HiddenMembership` as well. This results from the `HiddenGroupMembershipEnabled` switch of the [`New-UnifiedGroup`](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/new-unifiedgroup?view=exchange-ps#parameters) cmdlet and is also mentioned in the [Microsoft Graph API documentation](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/group.md#group-visibility-options).
I tested this in my dev tenant and got the same behavior as shown on your screenshot. 
I teamified the Unifed Group after creation.
```powershell
# Create a new UnifiedGroup
$newUnifiedGroup = New-UnifiedGroup -DisplayName "Hidden Membership" -Alias "HiddenMembership" -AccessType Private -HiddenGroupMembershipEnabled
# Get Unified Group properties
$newUnifiedGroup | Get-UnifiedGroup | Select Identity,HiddenGroupMembershipEnabled

# Get Teams properties
$newUnifiedGroup | Get-Team | Select DisplayName,Visibility 
Get-Team -Visibility "HiddenMembership"
```

For further details, please see my comment in the [Office365DSC repo](https://github.com/microsoft/Office365DSC/issues/349#issuecomment-590073218)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8450991f-9f85-4d87-51b3-efa8e1004a24
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by Markus-Hanisch** [comment]
@yogkumgit:
If you tell me what files I need to edit, I can create a pull request myself.
In the PnP PowerShell team, the Markdown files are generated based on the PowerShell cmdlets.
How is this handled for the PowerShell cmdlet `Get-Team`? Which file(s) do I need to modify?

**Comment by get-itips** [comment]
Hello @Markus-Hanisch Markus
Thanks for reporting, I tested and verified.
Created the PR to improve the article based on your feedback.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Markus-Hanisch Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
