### ISSUE TITLE
typo on "The target site must be the either:"

### ISSUE THREAD

**Issue by mariolonghi** [MicrosoftDocs/office-docs-powershell#4957]
Something is wrong with phrase!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb8f8e8-1242-363c-be77-038142b4efb9
* Version Independent ID: 54a60006-3d61-4bb9-a040-60fe77ef9f85
* Content: [Invoke-SPOSiteSwap (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/invoke-spositeswap?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md)
* Service: **sharepoint-powershell**
* GitHub Login: @WayneEwington
* Microsoft Alias: **waynewin**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @mariolonghi 👍 
Thanks for noticing, created a pr to fix that typo.

**Comment by yogkumgit** [comment]
@WayneEwington Please merge this PR #4971

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @mariolonghi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
