### ISSUE TITLE
ExternalURL missing on Exchange 2019 CU4 (WIN OS 2019)

### ISSUE THREAD

**Issue by dusansk** [MicrosoftDocs/office-docs-powershell#4959]
[PS] C:\Windows\system32&gt;Get-ManagementRoleEntry *\* -Parameters ExternalURL | ft name,role

Name                            Role
----                            ----
New-MapiVirtualDirectory        Exchange Virtual Directories
Set-LogExportVirtualDirectory   Exchange Virtual Directories
Set-OwaVirtualDirectory         Exchange Virtual Directories
New-RestVirtualDirectory        Exchange Virtual Directories
Set-RestVirtualDirectory        Exchange Virtual Directories
Set-WebServicesVirtualDirectory Exchange Virtual Directories
Set-PowerShellVirtualDirectory  Exchange Virtual Directories
Set-OabVirtualDirectory         Exchange Virtual Directories
Set-MapiVirtualDirectory        Exchange Virtual Directories
Set-EcpVirtualDirectory         Exchange Virtual Directories
Set-ActiveSyncVirtualDirectory  Exchange Virtual Directories
New-WebServicesVirtualDirectory Exchange Virtual Directories
New-PowerShellVirtualDirectory  Exchange Virtual Directories
New-OwaVirtualDirectory         Exchange Virtual Directories
New-OabVirtualDirectory         Exchange Virtual Directories
New-EcpVirtualDirectory         Exchange Virtual Directories
New-ActiveSyncVirtualDirectory  Exchange Virtual Directories

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2400d3-c174-0420-8a76-62331cab563c
* Version Independent ID: 935e10ec-262e-e441-5892-3be1c1e5950c
* Content: [Set-AutodiscoverVirtualDirectory (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access-servers/set-autodiscovervirtualdirectory?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/client-access-servers/Set-AutodiscoverVirtualDirectory.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access-servers/Set-AutodiscoverVirtualDirectory.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dusansk** [comment]
It says it works only on Exchange 2010. Sorry. my mistake

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@dusansk, thanks for the correction. Closing
