### ISSUE TITLE
Set-InboundConnector page requires update to include new settings for Enhanced Filtering

### ISSUE THREAD

**Issue by stuartschifter-AMA** [MicrosoftDocs/office-docs-powershell#4960]
Set-InboundConnector page requires update to include new settings for Enhanced Filtering.  Refer to https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb3825d3-960f-65ac-e138-7097cbe65dea
* Version Independent ID: 07b7a66f-c0f2-fb8b-518e-f150fe09ec0f
* Content: [Set-InboundConnector (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/set-inboundconnector?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Set-InboundConnector.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Set-InboundConnector.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@stuartschifter-AMA, done. Thanks for the feedback.

Closing.
