### ISSUE TITLE
Additional information required on -PermanentlyClearPreviousMailboxInfo

### ISSUE THREAD

**Issue by ponsaelius** [MicrosoftDocs/office-docs-powershell#4963]
If you use the -PermanentlyClearPreviousMailboxInfo as a parameter it does more than is described. 

It will not only remove the user mail guid it will also delete the mailbox completely making it unrecoverable. Worse still it will delete an archive mailbox too. In the case of the archive mailbox it seems to leave the archive mailbox guid in place. 

So it does clear the primary mailbox attributes but also permanently deletes the mailbox AND it permanently deletes an archive mailbox without removing the attributes.

Thus, it doesn't appear to work as described in the documentation. 

To be fair there is a onscreen warning. 

Are you sure you want to perform this action?
Delete all existing information about user “Jon@contoso.com"?. This operation will clear existing values from Previous home MDB and Previous Mailbox GUID of the user. After deletion, reconnecting to the previous mailbox that existed in the cloud will not be possible and any content it had will be unrecoverable PERMANENTLY. Do you want to continue?

However, the warning makes no mention of archive mailboxes. It should somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02635647-f6d7-5930-ddd4-1ca51577e066
* Version Independent ID: 307e0743-17fa-dcd1-b642-15811e5171b8
* Content: [Set-User (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-user?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Set-User.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Set-User.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ponsaelius, OK, dire warning added.

Thanks for the feedback.

Closing
