### ISSUE TITLE
Example 1 returns nothing

### ISSUE THREAD

**Issue by hvandesa** [MicrosoftDocs/office-docs-powershell#4968]
Trying to get a list of the components on the page so I can remove them -"Get-PnPClientSideComponent -Page Home" returns nothing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 957300cf-4822-f1e7-5428-454b300e7984
* Version Independent ID: 0adb9dbb-262a-2999-d013-ba750e2321a1
* Content: [Get-PnPClientSideComponent (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpclientsidecomponent?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPClientSideComponent.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPClientSideComponent.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @hvandesa Heather
How are you? 👍
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @hvandesa 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
