### ISSUE TITLE
Parameters removed?

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/office-docs-powershell#4975]
A few parameters are listed in this documentation that do not appear to exist in the command (per get-help) as it exists today.  Perhaps they have been removed, or will be added in a future update? 

Specifically:
ExchangeSenderMemberOf
ExchangeSenderMemberOfException
Priority

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9b42a14-b2a5-2c9c-9adc-34cb65bf389b
* Version Independent ID: bb09ac21-eec1-27b4-db33-ae72c56e7649
* Content: [Set-DlpCompliancePolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/set-dlpcompliancepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Set-DlpCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Set-DlpCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@NeighborGeek, those parameter should be available. Try running this command to see if they're listed:

```powershell
(Get-Command Set-DlpCompliancePolicy).parameters | Format-Table Key
```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and sharing this explanation. @NeighborGeek 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by NeighborGeek** [comment]
@chrisda Thank you, when I run that command it does list the 3 parameters that I thought were missing.  Is there a reason that these would be hidden from the built in help?

**Comment by chrisda** [comment]
@NeighborGeek, I think it's more of an issue of "missing" than "hidden". The cmdlet reference topics on the web are always the most up-to-date. Those same topics are also used for PowerShell help at the command line, but there's always a lag that involves adding them to code, and when that version of Exchange is available (either in quarterly on-prem CUs or in the cloud datacenters). At best, command line help can be even with what's on the web, but that's rarely the case; the difference gets larger and larger as time marches on after the last code check-in of the help files.

I know that historically people have used Get-Help output as a way to show or dump the available Exchange cmdlets/parameters, but that's not a realistic method, anymore. That command I had you run earlier works well, except that it's subject to RBAC (meaning, if you don't have the role assigned to you, you won't see the cmdlets/parameters). Other ways to see available cmdlets/parameters are described in the topic [Find the permissions required to run any Exchange cmdlet](https://docs.microsoft.com/powershell/exchange/exchange-server/find-exchange-cmdlet-permissions).

**Comment by NeighborGeek** [comment]
@chrisda  Interesting.  I thought that powershell functions were self documenting, to a degree, in that just by nature of a parameter existing it would be listed in the help for the command unless it is explicitly set not to.  So I expect that the help for a command will at least list all of the parameters that are available in that version of the command, even if there is no description of the command or parameters.  I guess I misunderstood something when I learned powershell & how it's help worked.  
Thanks!
