### ISSUE TITLE
Detail that the Chromium Edge feature needs to be enabled

### ISSUE THREAD

**Issue by kevball2** [MicrosoftDocs/office-docs-powershell#4979]
Can the article be updated that the Chromium edge feature needs to be enabled (as of right now it is turned off be default) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b188049-5302-25da-5bd2-89401be1db96
* Version Independent ID: a1d18859-a50d-acd2-1ef1-3729925dc1f1
* Content: [Connect to Office 365 Security & Compliance Center PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell.md)
* Service: **o365-security-and-compliance**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kevball2, sure. How do you do that? Is it different than the call-out that's already there?

> **Note**: ClickOnce support is available in the Chromium-based version of Edge at <edge://flags/#edge-click-once>.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by kevball2** [comment]
It the current build I am using (82.0.425.3) The initial setting is default. Then doesn't tell me if it was enabled or disabled by default. Maybe an update to the note That ClickOnce support is available in the Chromium-based version of Edge (but may need be enabled) to give a clearer context that the setting is not enabled by default. Or even just note the feature may not be enabled by default.

**Comment by chrisda** [comment]
@kevball2, OK. Done. Thanks for the feedback.

Closing.
