### ISSUE TITLE
Does New-CsGroupPolicyAssignment work on nested groups?

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/office-docs-powershell#4981]
The article doesn't cover if only members who are direct members of a group will have the policy applied, or if it will work on nested membership (and if so how deep). eg User A is a member of Group One, Group One is a member of Group Two. The Policy is assigned to Group Two. Will User A have the policy applied?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f8afd4c-7828-e7e7-dddc-e14673396f39
* Version Independent ID: dabb388b-8614-4b69-4e0a-f0536ab2bab6
* Content: [New-CsGroupPolicyAssignment (teams)](https://docs.microsoft.com/en-gb/powershell/module/teams/new-csgrouppolicyassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-CsGroupPolicyAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsGroupPolicyAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @thewrabbit How are you?
To be able to identify if a change is needed to articles and reply to your question, I always test the cmdlets under the given scenario, however this time I could not run any -csGroupPolicyAssignment.

I think that cmdlet it is not ready for production use, it is part of the BETA module version. @tomkau Tom, can you confirm this? 👍  Thanks

**Comment by get-itips** [comment]
@tomkau Tom, can you please review my comment? Thank you! 👍

**Comment by yogkumgit** [comment]
Closing, As per comment added in #5056
