### ISSUE TITLE
Do not translate parameters

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/office-docs-powershell#4982]
Parameter like "confirm" and "priority" have been translated into German (DE) "Bestätigen" & "Priorität". Please stop that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6fd9b17-5a2f-6e0a-f25b-a78aa5530b55
* Version Independent ID: 7f729071-f372-8270-a03a-e2d025fba93f
* Content: [New-MoveRequest (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/new-moverequest?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/New-MoveRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/New-MoveRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @trudolf-msft, thank you for your feedback.

@OfficeGlobal could you kindly help with this translation issue? Parameters shouldn't be translated. Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@trudolf-msft , @dariomws the article was HumanTranslated and published live. Parameters were left in ENG

**Comment by dariomws** [comment]
@OfficeGlobal Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution. @trudolf-msft  If you see other  documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
