### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by peterholdridge** [MicrosoftDocs/office-docs-powershell#4983]
I'm getting access denied when I run this cmdlet.
I've installed the latest preview teams powershell modules from the PSTestGallary and I have the new cmdlets. I'm connecting with a Global Admin account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dd1f927-030d-f0ad-06b8-195fa591d095
* Version Independent ID: e10d6b81-2a43-8b8a-7ef8-6734c7c8786f
* Content: [Get-CsGroupPolicyAssignment (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-csgrouppolicyassignment?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Get-CsGroupPolicyAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-CsGroupPolicyAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @peterholdridge Peter 👍 
Those cmdlets are part of the BETA version of the module. So they are not ready for production use.
Please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/4981

**Comment by yogkumgit** [comment]
@tomkau Please respond to the query in #4981

**Comment by AdamJParker** [comment]
How do we test the cmdlets? Running 1.0.21 from test gallery, getting same Access Denied error.

was told from Microsoft Rep "since the cmdlets are in Preview, tenants need to be whitelisted in order for them to work.  We requested your tenant be added at the end of Jan."

**Comment by get-itips** [comment]
Hello @AdamJParker please proceed further with your Microsoft rep about the whitelisting of your tenant, as here are limited to documentation issues, they will be able to help you. Thank you

**Comment by get-itips** [comment]
@yogkumgit Yogesh, no further response from the issue creator, I think we can close this for now. Thanks

**Comment by peterholdridge** [comment]
Yes you can close this. I got my answer

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @peterholdridge 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by umair-iscs** [comment]
Hi, any solution for this Get-CsGroupPolicyAssignment : Access Denied. how can we avoid this, we need to assign the policy to student group as from team admin portal is not applying to all students.
Please help.
