### ISSUE TITLE
Do not depreciate Search-Mailbox, enhance it, or Enhance Compliance search action Purges

### ISSUE THREAD

**Issue by dfsaqwe** [MicrosoftDocs/office-docs-powershell#4985]
The ten item limit on Compliance Search Action purges is too, too little.

Direct example of where we need a much a higher amount: when exchange duplicates hundreds if not thousands of copies of an email item due to item corruption.

I have had numerous tickets with user mailboxes filling up with these corrupted duplicates.  Using Search-Mailbox to delete 10,000 at a time is a blessing in saving time.  But Search-Mailbox cannot target aux archives, so now I must spend DAYS trying to delete these copies using compliance search actions.

We just need a way to effectively delete a mass volume of emails!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @dfsaqwe, thank you for your feedback.

This place is to help us to improve documentation. Please, for product feedback o request features use User Voice:
https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/39431878-keep-search-mailbox

**Comment by yogkumgit** [comment]
@dfsaqwe  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
