### ISSUE TITLE
Set-SPOTenant has multiple undocumented switches

### ISSUE THREAD

**Issue by Zerg00s** [MicrosoftDocs/office-docs-powershell#4986]
Can you, please, document these properties that are available via PowerShell, but not documented on this page?

- EnablePromotedFileHandlers
- DefaultLinkPermission
- AllowDownloadingNonWebViewableFiles
- FilePickerExternalImageSearchEnabled
- EmailAttestationRequired
- EmailAttestationReAuthDays
- SyncPrivacyProfileProperties
- EnableMinimumVersionRequirement
- MarkNewFilesSensitiveByDefault
- EnableAIPIntegration
- AllowCommentsTextOnEmailEnabled
- ConditionalAccessPolicyErrorHelpLink
- BlockDownloadLinksFileType

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428a5954-392c-f7ad-bac4-553adf74e08e
* Version Independent ID: 44fdecf2-1977-3171-9d04-02c0fefb16c9
* Content: [Set-SPOTenant (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Zerg00s Denis.
Just to let you know that I started working on this.

**Comment by get-itips** [comment]
Created a PR to address this issue. PR is linked here.

**Comment by yogkumgit** [comment]
@tseward and @dariomws Please review this PR #5005

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Zerg00s Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
