### ISSUE TITLE
Option -NewTitle DOESN'T WORK

### ISSUE THREAD

**Issue by mvanders** [MicrosoftDocs/office-docs-powershell#4992]
When using the option -NewTitle, one gets an error:

Start-SPOSiteRename : A parameter cannot be found that matches parameter name 'NewSiteTitle'.
At line:4 char:60
+ ... teRename -Identity $url -NewSiteUrl $NewSiteUrl -NewSiteTitle $newTit ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Start-SPOSiteRename], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Online.SharePoint.PowerShell.StartSPOSiteRename

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1b44e3-4af5-1458-d931-72a0f698732b
* Version Independent ID: 1751767f-1d8a-7750-35b9-725b5a3ad705
* Content: [Start-SPOSiteRename (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/start-spositerename?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteRename.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteRename.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @mvanders Marc 👍 
How are you?
Please be sure of running the latest available stable version of the SharePoint Powershell module.
Try to reproduce to see if we had to change something in the documentation but could not repro.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @mvanders 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
