### ISSUE TITLE
Get-SPOSiteRenameState DOESN'T WORK!

### ISSUE THREAD

**Issue by mvanders** [MicrosoftDocs/office-docs-powershell#4993]
When issuing the command, one gets:

Get-SPOSiteRenameState : The term 'Get-SPOSiteRenameState' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-SPOSiteRenameState -Identity https://upcbe47795.sharepoint.com/si ...
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-SPOSiteRenameState:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @mvanders Marc 👍
Same as https://github.com/MicrosoftDocs/office-docs-powershell/issues/4992
Please be sure of running the latest available stable version of the SharePoint Powershell module.
Tried to reproduce to see if we had to change something in the documentation but could not repro.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @mvanders 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
