### ISSUE TITLE
Example mentions wrong command name

### ISSUE THREAD

**Issue by JohnBontjer** [MicrosoftDocs/office-docs-powershell#4996]
Command used in example 1 has a typo 'Get-PnPHubChildSite' instead of 'Get-PnPHubSiteChild'

Notice 'Child' at the end of the noun.
correct command: Get-PnPHubSiteChild

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ec75a87-ea5a-c9c6-b15f-facb7c816760
* Version Independent ID: 002d95a1-c08e-9208-426f-9ca908079be1
* Content: [Get-PnPHubSiteChild (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnphubsitechild?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPHubSiteChild.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPHubSiteChild.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by kenwith** [comment]
@JohnBontjer - thank you for taking the time to submit an issue with this one.

The PnP cmdlet references are a little different than the rest of the Office cmdlet references. The PnP 'source' for the reference actually lives in the cmdlet code itself and each release the PnP maintainers generate the references from code and then copy the markdown over to this location so it is rendered alongside the rest of the Office cmdlet references.

I believe the source file for this particular cmdlet is located here: https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Admin/GetHubSiteChild.cs

The repo is community driven and maintained and I know they would very much appreciate your contribution. If you are open to it I can guide you on how to submit the Pull Request (PR) there to get the fix in the code. In a nutshell, you click on the Edit button for the source cmdlet and then make the edit and then at the bottom of the screen look for buttons to submit a PR. If you get stuck I can help too.
