### ISSUE TITLE
Import-Module microsoftteams: Exception from HRESULT: 0x80131515

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#5000]
Hi,

In our workstation environments we cannot run the install-modules, as administrator accounts must not be able to connect to internet. So I did a manual download for .nupkg. Then I follow the instructions on: [Installing PowerShell modules from a NuGet package](https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-packages/manual-download?view=powershell-7#installing-powershell-modules-from-a-nuget-package)

When I'm trying to import the module I get the following:

```
PS C:\> Import-Module microsoftteams

Import-Module : Could not load file or assembly 'file:///C:\Program Files\WindowsPowerShell\Modules\microsoftteams\net472\Microsoft.Teams.PowerShell.Auth
.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module microsoftteams
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Many of related instructions for the error code ask to remove the block from the file. But in our workstation, we do not store the information:
```
C:\>reg query HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments
    SaveZoneInformation    REG_DWORD    0x2
    HideZoneInfoOnProperties    REG_DWORD    0x1
```

Even so, I ran the following to unblock all of the files:
`PS C:\> Get-childItem -Path "C:\Program Files\WindowsPowerShell\Modules\microsoftteams\"  -Recurse | Unblock-File -Verbose`

Is there any other reasons why this might come?

I have tested to run this with admin account and regular account.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Petri-X 
While I setup my environment to test this... quick question, did it run successfully after you unblocked all the files?
Thanks for the info

**Comment by get-itips** [comment]
Hello @Petri-X 
Finally tested this.
First, I reproduced the error you shared, then, I tried first unblocking the .nupkg file BEFORE renaming it to .zip to extract the contents, and then tried to use it, it imported the microsoftteams module without error.

![image](https://user-images.githubusercontent.com/36666927/75683720-46565b80-5c5d-11ea-95c3-388672611dfc.png)

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Petri-X Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Petri-X** [comment]
@get-itips Hero !!
That really did the trick. And answer for your earlier question, when I did a unblock for all files, that did not work either then.
Big thanks !!   _o/

**Comment by get-itips** [comment]
@Petri-X Glad to hear!
@yogkumgit please close this thread again.
