### ISSUE TITLE
-GraphAPIToken parameter required

### ISSUE THREAD

**Issue by tonyoscard** [MicrosoftDocs/office-docs-powershell#5004]
Need Graph API token parameter in EXO v2. So we can connect multiple services like MSOnline, AzureAD and EXO v2 using same token.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @tonyoscard, thank you for your feedback.

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, contact us at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @tonyoscard 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
