### ISSUE TITLE
Error importing OfficeDevPnP.Core module in Azure Automation account  

### ISSUE THREAD

**Issue by paulpa** [MicrosoftDocs/office-docs-powershell#5007]
Hello team,

we are getting an error when we are trying to import the OfficeDevPnP.Core into Azure Automation account -->Shared Resources --> Modules 

Error importing the module OfficeDevPnP.Core. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: While importing the module, an error occurred while processing the module content. Internal error message: Could not load file or assembly 'Microsoft.SharePoint.Client.Runtime, Version=16.1.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified..

![image](https://user-images.githubusercontent.com/8114060/75681011-bba34a00-5cb8-11ea-8c77-4bd2bbe8de38.png)

we also want to know how to use SharePoint PNP modules in Azure Runbook.

regards
Paul

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @paulpa Paul 👍 
How are you?

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @paulpa 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
