### ISSUE TITLE
Connect-MicrosoftTeams with certificate issue

### ISSUE THREAD

**Issue by bender86** [MicrosoftDocs/office-docs-powershell#5008]
Hi,

I'm trying to connect  with an existing certificate uploaded in my azure App Registration.
I used this 3 parameters but have an issue
$clientID 
$thumbprint 
$tenantID

`#Connect-MicrosoftTeams -ApplicationId $clientID -CertificateThumbprint $thumbprint -TenantId $tenantID -LogFilePath "C:\temp\TeamsError.txt"`

My MicrosoftTeams version is up to date
1.0.3      MicrosoftTeams                      PSGallery            Teams Cmdlets module

Here is the complete error returned when i'm trying a connection:

> Connect-MicrosoftTeams : One or more errors occurred.
At line:1 char:1
+ Connect-MicrosoftTeams -ApplicationId $clientID -CertificateThumbprin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AggregateException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
 
Connect-MicrosoftTeams : Invalid provider type specified.

At line:1 char:1
+ Connect-MicrosoftTeams -ApplicationId $clientID -CertificateThumbprin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], CryptographicException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
 
Connect-MicrosoftTeams : One or more errors occurred.
At line:1 char:1
+ Connect-MicrosoftTeams -ApplicationId $clientID -CertificateThumbprin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MicrosoftTeams], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams

Do you have any suggest to be connected successfully?
Thanks

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @bender86 
How are you?
Those errors are probably related to the method you used to generate the certificate (See the invalid provider error)

I tested the cmdlet to see if any documentation change was needed, as here we are limited to documentation issues, and I could connect successfully when I followed this [other article](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-authenticate-service-principal-powershell#create-service-principal-with-self-signed-certificate) specially the Ps example used for generating the self-signed cert.

I hope this info helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @bender86 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by bsj17** [comment]
> Hello @bender86
> How are you?
> Those errors are probably related to the method you used to generate the certificate (See the invalid provider error)
> 
> I tested the cmdlet to see if any documentation change was needed, as here we are limited to documentation issues, and I could connect successfully when I followed this [other article](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-authenticate-service-principal-powershell#create-service-principal-with-self-signed-certificate) specially the Ps example used for generating the self-signed cert.
> 
> I hope this info helps you.

I can confirm described method in [article](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-authenticate-service-principal-powershell#create-service-principal-with-self-signed-certificate) works.
However if you try to connect to SfB online this fails:

New-CsOnlineSession : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following
error message : The WinRM client cannot process the request. The authentication mechanism requested by the client is no
t supported by the server or unencrypted traffic is disabled in the service configuration. Verify the unencrypted traff
ic setting in the service configuration or specify one of the authentication mechanisms supported by the server.  To us
e Kerberos, specify the computer name as the remote destination. Also verify that the client computer and the destinati
on computer are joined to a domain. To use Basic, specify the computer name as the remote destination, specify Basic au
thentication and provide user name and password. Possible authentication mechanisms reported by server: For more inform
ation, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ New-CsOnlineSession
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], PSRemotingTransportException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession

New-CsOnlineSession : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following
error message : The WinRM client cannot process the request. The authentication mechanism requested by the client is no
t supported by the server or unencrypted traffic is disabled in the service configuration. Verify the unencrypted traff
ic setting in the service configuration or specify one of the authentication mechanisms supported by the server.  To us
e Kerberos, specify the computer name as the remote destination. Also verify that the client computer and the destinati
on computer are joined to a domain. To use Basic, specify the computer name as the remote destination, specify Basic au
thentication and provide user name and password. Possible authentication mechanisms reported by server: For more inform
ation, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ New-CsOnlineSession
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-CsOnlineSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Open.Te
   ams.SfbOnline.CsSession.NewCsOnlineSession
