### ISSUE TITLE
Undocumented Limit on -SenderAddress ?

### ISSUE THREAD

**Issue by HugoExceptOnFire** [MicrosoftDocs/office-docs-powershell#5009]
I have a PowerShell object containing some 600 addresses by doing `$groups = get-DistributionGroup`

I am trying to run this object against Start-HistoricalSearch using `$groups.Primarysmtpaddress`, like this:

`Start-HistoricalSearch -ReportTitle "Distribution Group Report" -startDate 12/10/2019 -endDate 03/02/2020 -ReportType MessageTrace -SenderAddress $groups.Primarysmtpaddress -NotifyAddress <myemail>`

I receive the error: `The Hygiene DAL retried a transient condition the maximum number of times.`

This does not occur if I limit the number of addresses to 100, e.g.:
`Start-HistoricalSearch -ReportTitle "Distribution Group Report" -startDate 12/10/2019 -endDate 03/02/2020 -ReportType MessageTrace -SenderAddress $groups.Primarysmtpaddress[0..99] -NotifyAddress <myemail>`

This limit is not mentioned in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a22164-2df5-5dc2-9292-df60df018a53
* Version Independent ID: 1d96478c-230b-889e-68ed-9a8ab9484be5
* Content: [Start-HistoricalSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/start-historicalsearch?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Start-HistoricalSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Start-HistoricalSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @HugoExceptOnFire, thank you for your feedback.

@chrisda could you kindly help with this? I have verified this information and seems that there is a limit between 100 and 150 addresses.

**Comment by yogkumgit** [comment]
@chrisda Please reply to this query. Thanks

**Comment by chrisda** [comment]
Topic updated. Thanks for the feedback.

Closing
