### ISSUE TITLE
Remove-SPOOrgNewsSite Error

### ISSUE THREAD

**Issue by Anonimiss** [MicrosoftDocs/office-docs-powershell#5010]
Following the documentation, I am attempting to remove an Org News Site by utilizing the following command:

`Remove-SPOOrgNewsSite -OrgNewsSiteUrl https://xxxx.sharepoint.com/sites/xxxx`

I receive the following error:

`Remove-SPOOrgNewsSite : File Not Found.
At line:1 char:1
+ Remove-SPOOrgNewsSite -OrgNewsSiteUrl https://xxxx.sharepoint.com/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-SPOOrgNewsSite], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.SPOTe
   nantOrgNews+RemoveSPOOrgNewsSite`

I ran the Get-SPOOrgNewsSite command and see this site is listed as an Org News site

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by Anonimiss** [comment]
After further troubleshooting, I was able to get the site to successfully be removed from the list.  Closing out ticket as it seems to be working as expected.
