### ISSUE TITLE
-ActiveSyncMailboxPolicy can be set to $null to reset to defaults

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/office-docs-powershell#5014]
It would be helpful to mention that using -ActiveSyncMailboxPolicy with the $null parameter is the best way to select the 'default' policy again 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9398dd25-94e7-a8f8-6d97-f150173bb4da
* Version Independent ID: 6f19f636-20d5-bc97-68be-30b313f107b8
* Content: [Set-CASMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-casmailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-CASMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-CASMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@ChrisAtMAF, is there a reason why you would use the value $null instead of Default (the name of the default policy)? I checked in an Exchange Online tenant and an Exchange 2019 server, and the default value for ActiveSyncMailboxPolicy is Default, not blank.

**Comment by ChrisAtMAF** [comment]
Hi,

When I tested, attempting to reset the value to 'Default' leaves the Get-CASMailbox 'ActiveSyncMailboxPolicyIsDefaulted' property (helpful for determining if a mailbox is not default!) at $False

When I set -ActiveSyncMailboxPolicy to $null, I found that it also reset ActiveSyncMailboxPolicyIsDefaulted back to True.

See https://practical365.com/exchange-server/exchange-server-configure-default-mobile-device-mailbox-policy-activesync/

**Comment by chrisda** [comment]
@ChrisAtMAF, very interesting. I updated the topic as you described.

Thanks for the feedback.

Closing
