### ISSUE TITLE
-Identity parameter set gone for good?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#5015]
Get-MobileDeviceStatistics had an extra parameter set which included the Identity parameter.  This allows for piping results from Get-MobileDevice into Get-MobileDeviceStatistics.  Dropping that functionality is quite a breaking change.  Is this temporary or permanenent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ceddbc7-8b96-be0f-3326-2c38d6d0d034
* Version Independent ID: 95ec2d7f-c5f7-1ab9-a0cc-da9796a92489
* Content: [Get-EXOMobileDeviceStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/get-exomobiledevicestatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/powershell-v2-module/Get-EXOMobileDeviceStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/powershell-v2-module/Get-EXOMobileDeviceStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @JeremyTBradshaw, thank you for your feedback.

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, contact us at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

**Comment by JeremyTBradshaw** [comment]
Ahh, good point and will do.  Thanks.
