### ISSUE TITLE
Get-TeamChannelUser only returns 100 users

### ISSUE THREAD

**Issue by darryn-bryant** [MicrosoftDocs/office-docs-powershell#5021]
We have some private channels with >100 users and this cmd only returns 100.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @darryn-bryant how are you? 👍
As the documentation says,  
[Get-TeamChannelUser](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamchanneluser?view=teams-ps)  is still part of the beta version of the module, so it is subject to changes and adjustments.
Thank you

**Comment by darryn-bryant** [comment]
Hi @get-itips 
Understand it is in beta and I don't expect it to work perfectly.
I just wanted to make sure that this was logged so it can be addressed.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @darryn-bryant 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
