### ISSUE TITLE
New-TeamChannel issue

### ISSUE THREAD

**Issue by acrichlow** [MicrosoftDocs/office-docs-powershell#5024]
I am able to create the channel as a private channel, add a user to the channel, but every singe channel created this way does not have a functioning Files tab within Teams. Any ideas?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/4937 to check if you recognize the same scenario. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the reference. @acrichlow Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
