### ISSUE TITLE
MessageCopyForSentAsEnabled MessageCopyForSendOnBehalfEnabled

### ISSUE THREAD

**Issue by Hoegimator** [MicrosoftDocs/office-docs-powershell#5028]
What about changing the properties of "MessageCopyForSentAsEnabled" and "MessageCopyForSendOnBehalfEnabled" in the default Mailboxplan?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b7e2c02-ff5d-7c4b-8f34-69597480f600
* Version Independent ID: 364f7cd0-3fd1-6401-cb46-6fb104b97ac3
* Content: [Set-MailboxPlan (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailboxplan?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-MailboxPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-MailboxPlan.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @Hoegimator, thank you for your feedback.

This is not available. For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/
There, your suggestion will reach the product team.

**Comment by yogkumgit** [comment]
@Hoegimator  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
