### ISSUE TITLE
SPO cmdlets - Tenant property cmdlet documentation is missing

### ISSUE THREAD

**Issue by VesaJuvonen** [MicrosoftDocs/office-docs-powershell#503]
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-properties

**Get-SPOStorageEntity**
Applies to Office 365, SharePoint Online

Syntax Get-SPOStorageEntity [-Site] [-Key]

**Set-SPOStorageEntity**
Applies to Office 365, SharePoint Online

Syntax Set-SPOStorageEntity [-Site] [-Key] [-Value] [-Description] [-Comments]

**Remove-SPOStorageEntity**
Applies to Office 365, SharePoint Online

Syntax Remove-SPOStorageEntity [-Site] [-Key]

**Comment by AndreaBarr** [comment]
@VesaJuvonen Thank you for this feedback

Let me get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
