### ISSUE TITLE
AssociatedMessagesCopyOption default is NOT "Copy" (it is "DoNotCopy")

### ISSUE THREAD

**Issue by mtudor** [MicrosoftDocs/office-docs-powershell#5032]
The page on New-MailboxExportRequest, in the text for the "Copy" option, states that "Copy" is the default option for the "AssociatedMessagesCopyOption" parameter.  Underneath, the default is listed as "None".  The actual default is "DoNotCopy", it would seem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fab79912-3075-a8be-fc9f-01d0c28c6423
* Version Independent ID: 5bd0b2f9-c51c-74cd-6ac1-3134fde6bf59
* Content: [New-MailboxExportRequest (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/New-MailboxExportRequest?redirectedfrom=MSDN&view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/New-MailboxExportRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/New-MailboxExportRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @mtudor, thank you for your feedback.

Could you kindly elaborate further about how you test it and why you can be sure about it?

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and digging deep into it.  @mtudor  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
