### ISSUE TITLE
Get-PnPTenantSite does not display GUID values when retrieving all sites

### ISSUE THREAD

**Issue by rva3** [MicrosoftDocs/office-docs-powershell#5033]
Running Get-PnPTenantSite or Get-PnPTenantSite -Detailed does not display the actual value of attributes that have GUID data types (GroupId, HubSiteId, RelatedGroupId, SensititvityLabel), the value 00000000-0000-0000-0000-000000000000 is displayed for all sites.  

The expected behavior is that Get-PnPTenantSite -Detailed will return all sites with the correct attribute values based on the following verbiage "By default, not all returned attributes are populated. This switch populates all attributes. It can take several seconds to run. Without this, some attributes will show default values that may not be correct."

The correct GUID attribute values are returned executing the following Get-PnPTenantSite | ForEach-Object { Get-PnPTenantSite -Url $_.Url | select Title,Url,GroupId }

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @rva3 👍  

How are you?

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @rva3 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
