### ISSUE TITLE
Help missing argument names

### ISSUE THREAD

**Issue by MarkWagner** [MicrosoftDocs/office-docs-powershell#5034]
The help for the New-OfficeWebAppsFarm command displays the description for 50+ parameters but does not list the parameter name next to each description.  This makes the help almost meaningless.  Also, most arguments don't show what the Default value is.  This is what I am really after.  

Get-Help New-OfficeWebAppsFarm -full
or
Get-Help New-OfficeWebAppsFarm -detail

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @MarkWagner Mark 👍  how are you?

I am ruling out that you already ran Update-Help so, could you please share a screenshot of what do you see? As I could not repro.

Thanks

**Comment by MarkWagner** [comment]
update-help officewebapps
update-help : Failed to update Help for the module(s) :
'OfficeWebApps'
The Update-Help command failed because the **specified module does not support updatable help**. Use Get-Help -Online or
look online for help for the commands in this module.
At line:1 char:1
+ update-help officewebapps
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (HelpInfoUri:Uri) [Update-Help], Exception
    + FullyQualifiedErrorId : HelpInfoUriNotFound,Microsoft.PowerShell.Commands.UpdateHelpCommand

**Comment by get-itips** [comment]
@MarkWagner can you share a screenshot of what you see?

**Comment by MarkWagner** [comment]
Below is a sample of the output when running the following command.  As you can see, the parameter names are all missing.  Only **- <>** exists where the parameter name should be.

PARAMETERS
    **- <>**
        Enables Customer Experience Improvement Program (CEIP) reporting on all servers in the Office Online Server
        farm.
        Required?
        Position?                    Named
        Default value
        Accept pipeline input?
        Accept wildcard characters?  false

    **- <>**
        Indicates that IIS sites should be provisioned on port 80 for HTTP access. Use AllowHTTP only in environments
        where all computers require IPSEC (full encryption) or in test environments that do not contain sensitive
        files.


        Enabled automatically when you enable SSLOffloaded.



        Required?
        Position?                    Named
        Default value
        Accept pipeline input?
        Accept wildcard characters?  false

    **- <>**
        Indicates that secure store connections can be made by using non-SSL connections (such as HTTP). The default
        is False.


        Use AllowHTTPSecureStoreConnections only in environments where all computers require IPSEC (full encryption)
        or in test environments that do not contain sensitive files.



        Required?
        Position?                    Named
        Default value
        Accept pipeline input?
        Accept wildcard characters?  false

    **- <>**
        Allows outbound HTTP connections from Office Online Server.


        Required?
        Position?                    Named
        Default value
        Accept pipeline input?
        Accept wildcard characters?  false

    **- <>**
        Specifies the location of the global disk cache that is used to store rendered image files. The default
        location is %programdata%\Microsoft\OfficeWebApps\Working\d\.


        Required?
        Position?                    Named
        Default value
        Accept pipeline input?
        Accept wildcard characters?  false

    **- <>**
        Specifies the maximum size of the global disk cache in gigabytes.

**Comment by get-itips** [comment]
Ok, I see now, that seems like a malfunction of the Get-Help cmdlet or a broken help file, here we can only make corrections to online articles.
@kenwith can we pass this feedback to Product Group?

**Comment by kenwith** [comment]
Yes, the one source of truth is the GitHub file and the Get-Help pulls from an XML file that is part of the code.. and right now it is a manual effort that the product team builds the XML file and checks it into code and pushes it out to the services when they push new features.. goal is to get this automated but for now it is manual. I touched on the process a bit in the last paragraph here: https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/repo_docs/ADVANCED.md#confirm-your-work-shows-up-on-docsmicrosoftcom and can provide more info if anyone interested. For example, the command to build the XML file is run using an open source tool called PlatyPS - this command https://github.com/PowerShell/platyPS/blob/master/docs/New-ExternalHelp.md

**Comment by kenwith** [comment]
Also, I am following up with the product team to see when they last shipped an update and to make sure they are including updating the XML help content from GitHub in their push of any updates. Thank you for this information.
