### ISSUE TITLE
Aggregations parameter is not working

### ISSUE THREAD

**Issue by sumitrampal80** [MicrosoftDocs/office-docs-powershell#5035]
In example given above on this page - Add-PnPView -List "Demo List" -Title "Demo View" -Fields "Title","Address" -Aggregations "&lt;FieldRef Name='Title' Type='COUNT'/&gt;" is Aggregation parameter is not available yet? I have updated PnP online and still getting the error "A parameter cannot be found that matches parameter name 'Aggregations'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d9f0311-903f-01a2-478d-28e0a196b5c5
* Version Independent ID: 3adca24b-cf2a-63d1-7eb5-631c6448daca
* Content: [Add-PnPView (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpview?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPView.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPView.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sumitrampal80 👍 
How are you?

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @sumitrampal80 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by sumitrampal80** [comment]
Thanks @get-itips and @yogkumgit for your help. I will post this issue on the provided community link.

Cheers!
