### ISSUE TITLE
Don't confirm deletion of the underlying SQL database

### ISSUE THREAD

**Issue by swatt6400** [MicrosoftDocs/office-docs-powershell#5037]
-Confirm:$false doesn't do it - you still have to confirm the second (SQL Database delete) confirmation.  -Force does the trick, but the documentation for -Force in this article is very generic and doesn't tell you what it forces vs. when not using the -Force switch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ef69247-2ddd-7b7b-711a-046030c863ec
* Version Independent ID: a6db8b6c-5921-3cc6-d252-3880d789f0f5
* Content: [Remove-SPContentDatabase (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/remove-spcontentdatabase?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Remove-SPContentDatabase.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Remove-SPContentDatabase.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @swatt6400 
I will propose thru a PR adding a working example to force without confirmation.
Thanks

**Comment by yogkumgit** [comment]
@kenwith Please merge this PR #5075 , Thanks

**Comment by kenwith** [comment]
Merged.
