### ISSUE TITLE
Set-PNPWebPermissions

### ISSUE THREAD

**Issue by Djdodo666** [MicrosoftDocs/office-docs-powershell#504]
How do I set permissions for a subsite using O365 groups?
I can get the ObjectID of the group using Get-MsolGroup, but how do I use this information for setting the permissions?
We don't use Sharepoint groups.

**Comment by kenwith** [comment]
Hi @Djdodo666 - for the PNP cmdlets you might have better luck in the github.com/sharepoint community.. I will close this one out but if you find an answer and want to put any content back into the reference docs please go ahead and reopen / submit a pull request. Thanks for the feedback.
