### ISSUE TITLE
Azure app or certificate 

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/office-docs-powershell#5043]
Is there a way to use app registration or certificate with the new api? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28f6554b-4d67-06d3-7926-1b958653872f
* Version Independent ID: 7a6a1737-afdf-dfd5-67f8-64aa6758ccc4
* Content: [Connect-ExchangeOnline (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/connect-exchangeonline?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by oppknox** [comment]
This needs to happen stat! In this day and age its unacceptable.

**Comment by chrisda** [comment]
@stephenc01, @oppknox , the EXO V2 module is still in Preview. Please direct questions to exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

Specifically, the question you are asking is about features/capabilities, not documentation, which is even more reason to seek answers from the direct support channel.

Thanks for the feedback.

Closing.

**Comment by stephenc01** [comment]
Feedback sent. Also, each product group has their own channels so it’s confusing to find the right one. Last there is still a disconnect as each group writes their own modules that drift from other groups.
