### ISSUE TITLE
Cmdlet usage is restricted.

### ISSUE THREAD

**Issue by YvonneArnoldus** [MicrosoftDocs/office-docs-powershell#5045]
I'm able to create a Office 365 group with my Tenant created through Power BI and my Power BI Pro license but when I want to turn of the welcome email because we do not need it I get this error:

The following error occurred during validation in agent 'Substrate Only Agent': 'Organization "***" i
s not licensed for Exchange email functionality. Cmdlet usage is restricted.'
    + CategoryInfo          : NotSpecified: (:) [Set-UnifiedGroup], ProvisioningValidationException
    + FullyQualifiedErrorId : [Server=VE1P189MB1149,RequestId=52308e3b-0d09-46d7-8305-427b2f7f8a75,TimeStamp=10-3-2020
    09:23:57] [FailureCategory=Cmdlet-ProvisioningValidationException] F5E444F8,Microsoft.Exchange.Management.Recipie
  ntTasks.SetUnifiedGroup
    + PSComputerName        : outlook.office365.com

So I have no way to turn of the not needed welcome email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd7d69db-be49-179e-94ce-635337c98d07
* Version Independent ID: 9e372e66-5c7e-4d9a-56de-a35ae353fa09
* Content: [Set-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
@YvonneArnoldus Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@YvonneArnoldus  If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks.
