### ISSUE TITLE
New-TeamChannel missing MembershipType and Owner parameters

### ISSUE THREAD

**Issue by eemhong** [MicrosoftDocs/office-docs-powershell#5047]
Hello,

I'm trying to create private channels for newly created teams but i'm unable to use MembershipType and Owner parameters as PowerShell says those do not exist. Even Autocomplete is unable to find them

Eemeli

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @eemhong, thank you for your feedback.

Please check:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4414

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @eemhong 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
