### ISSUE TITLE
Remove-TeamUser missing Role parameters

### ISSUE THREAD

**Issue by Louicha** [MicrosoftDocs/office-docs-powershell#5048]
The argument for the parameter "Role" cannot be checked. The "Member" argument does not belong to the ValidateSet attribute. 
![Anmerkung 2020-03-10 130038](https://user-images.githubusercontent.com/22676238/76310616-67f3ba80-62cf-11ea-849d-53cceb09647a.png)

Module Version Version 1.0.4.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @Louicha,

To remove a member you don't need to use the -Role parameter. Use it only to remove Owners. Thanks!

**Comment by dariomws** [comment]
To add more information, please see:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4465
Member value for -Role parameter will be available in a future release soon.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @Louicha 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
