### ISSUE TITLE
Search by name is not correct

### ISSUE THREAD

**Issue by pconnell99** [MicrosoftDocs/office-docs-powershell#5052]
If I try to use the -Identity "string" syntax I get an error "Get-PnPTerm : Insufficient parameters" -  -Identity will ONLY take a GUID.  Not much use for finding a term by name.

Does this document need updating or is this a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4add3313-4fe9-7198-8c7e-4277ee15569e
* Version Independent ID: 26bd1ade-f573-6c78-f0b5-22c3e32cd1af
* Content: [Get-PnPTerm (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpterm?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTerm.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTerm.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @pconnell99 Paul, how are you ? 👍 
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @pconnell99 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
