### ISSUE TITLE
The New-Team command is Bugged for Private Channels

### ISSUE THREAD

**Issue by 3031539** [MicrosoftDocs/office-docs-powershell#5053]
After using a New-Team to create a new team site lots of problem has occured when using the TEAMS in Desktop mode.

- Unable to delete a private channel (But with the Android version of Teams i am able to delete with the channel)
- Unable to add users to a private channel, the user that I tried to add had a different Licensing of all other users wich was an E5, but all other users weres E3 and (Able to add the user with the Android version of Teams)

If I use the Teams Android App Everything works Good 

Here's Powershell script used to create the Buggy Teams site.

Param(

    [string]$teamname, #The name of the Team
    [string]$teamowner, #The email address of the owner of the Team
    [string]$teamalias #The bit of the teamname you want to be the URL

)

#Obtain credentials
#$cred = Get-AutomationPSCredential -Name "TeamAdminOwner"

$cred = Get-AutomationPSCredential -Name "ART-PS"
#write-output "Credential user:  $creds.UserName "

#Test if Group Exist
try{

    #Connect to Teams PowerShell
    $Teams = Connect-MicrosoftTeams -Credential $cred
    #write-output "TenantDomain: " $teams.TenantDomain

    #Get Teams site if exists
    $ifTeams = Get-Team -MailNickName $teamalias

    if ($ifTeams) {
        write-output $ifteam | convertto-json    
    }
    else{
        write-output "Creating : " $teamalias
        #Create the Team main owner is TeamAdminOwner
        $newteam = New-Team -MailNickName $teamalias -DisplayName $teamname -Owner $creds.UserName -Visibility Private 
                
        #Adding secondary owner users a
        $useradded = add-teamuser -groupid $newteam.GroupID -user $teamowner -Role "Owner"
        #write-output $useradded.
        #Return to Flow the new teams GroupID by passing the object as JSON
        write-output $newteam | convertto-json 
    }

    #Hangup
    Disconnect-MicrosoftTeams

}
Catch [Exception] {
    Write-host $_.Exception.Message -f Red
    Disconnect-MicrosoftTeams
    Return $False
}

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
@3031539 Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@3031539  If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks.
