### ISSUE TITLE
Includes fails using valid terms

### ISSUE THREAD

**Issue by pconnell99** [MicrosoftDocs/office-docs-powershell#5054]
If I try to -Includes  TermSets, TermSets.Item I get

Get-PnPTermGroup : The query expression 'Param_0.TermSets.Item' is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b25a38ab-4933-ea82-a5bd-0a3d92b2548b
* Version Independent ID: b34eb964-c775-4e53-8f5f-a4dbd7cd777b
* Content: [Get-PnPTermGroup (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnptermgroup?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTermGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTermGroup.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @pconnell99 Paul , how are you? 👍 
How are you?

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @pconnell99 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
