### ISSUE TITLE
Access Denied when using New-CsGroupPolicyAssignment

### ISSUE THREAD

**Issue by aidancopps** [MicrosoftDocs/office-docs-powershell#5056]
Attempts to use the *-CsGroupPolicyAssignment cmdlets are giving a Access Denied error even when using a Teams Service Administrator account. Are the cmdlets available for all tenants to use or is this still restricted to certain tenants in a private preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f8afd4c-7828-e7e7-dddc-e14673396f39
* Version Independent ID: dabb388b-8614-4b69-4e0a-f0536ab2bab6
* Content: [New-CsGroupPolicyAssignment (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csgrouppolicyassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-CsGroupPolicyAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsGroupPolicyAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @aidancopps, thank you for your feedback.

@tomkau could you kindly help with this issue? I tested these cmdlets and also get "Access denied" using 1.0.21 module.

**Comment by dariomws** [comment]
Same/similar as/to:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4981
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4983

**Comment by VonRoch** [comment]
I am having the same issue as @dariomws and attempt at using the Get-CsGroupPolicyAssignment gives me an Access Denied error.

**Comment by Padavid** [comment]
I am also have the same issue with Get and New.

**Comment by damirko1003** [comment]
Same for me. Could you please provide a feedback on this issue?

**Comment by matambanadzo** [comment]
Same here. Access denied. Need to know steps on getting our tenant whitelisted.

**Comment by SRSLY-AU** [comment]
I'm also have the same issue. Would desperately like to know the fix, or whatever steps are required to get our tennant whitelisted also.

**Comment by seafordcode** [comment]
I am having the same issue. The full is:

Get-CsGroupPolicyAssignment : Access Denied.
At C:\monedrive\SetPolicyEnviroment.ps1:13 char:1
+ Get-CsGroupPolicyAssignment -GroupId ce4192cf-9d63-4651-960b-461c0e37 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ GroupId = ce4...-461c0e371895 }:<>f__AnonymousType4`1) [Get-CsGroupPolicyAssignme 
   nt_Get1], Exception
    + FullyQualifiedErrorId : Forbidden,Microsoft.Teams.Config.Cmdlets.Cmdlets.GetCsGroupPolicyAssignment_Get1

**Comment by dariomws** [comment]
@tomkau could you kindly help with this issue?

**Comment by tameemansari** [comment]
This is a preview feature and is available only to whitelisted tenants. @tomkau can confirm if the error message received is for tenants who are not part of the preview.

**Comment by bucketspodge** [comment]
Seen this update on the message center.
Updated March 4, 2020: To ensure the best experience we are adjusting the roll-out timeframe for this feature. We apologize for the inconvenience.
Teams administrators will soon be able to assign policies to a batch of users or to a group. We’ll be releasing this in late May (previously March).

This message is associated with Microsoft 365 Roadmap ID 61185.

**Comment by yogkumgit** [comment]
@dariomws  and @tameemansari  Thank you very much for the contribution and sharing this explanation. @aidancopps Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jensmarshall** [comment]
How do you get added to the whitelist? How do you get on the preview list?

**Comment by dariomws** [comment]
Hi @jensmarshall, please check this:
https://docs.microsoft.com/microsoftteams/private-channels-life-cycle-management#install-the-latest-teams-powershell-module-from-the-powershell-test-gallery

**Comment by jensmarshall** [comment]
I have installed the the PSGalleryInt repository, and have version 1.0.22 on one machine & 1.0.21 on the other.  When I run the commands from the page you linked, I receive the Access Denied error message.

**Comment by dariomws** [comment]
Hi @jensmarshall, thank you for your feedback.

Sorry, my mistake. It's not yet available in the preview module. It will be available on May:
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=61185

I think you should contact support to WhiteList your tenant.
