### ISSUE TITLE
The -Purge Description has incorrect hyperlink

### ISSUE THREAD

**Issue by JTApps-1** [MicrosoftDocs/office-docs-powershell#5057]
The hyperlink has incorrect http prefix. the prefix is hhttp instead of http resulting in a dead link.

Here is the hyperlink url:

hhttps://docs.microsoft.com/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e154eb-3e1c-b4a5-418e-5be55b581255
* Version Independent ID: 00b93f90-663f-c277-c7de-09c184b4a322
* Content: [New-ComplianceSearchAction (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-compliancesearchaction?view=exchange-ps&source=docs#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-content-search/New-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@JTApps-1, fixed. In the future, you, too can fix topic problems like this directly without opening a GitHub Issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing.
