### ISSUE TITLE
Set-SPEnterpriseSearchCrawlContentSource  -WhatIf Does Not Work

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#506]
When running `Set-SPEnterpriseSearchCrawlContentSource `with `WhatIf ` parameter, it does not seem like WhatIf parameter works at all.  

![image](https://user-images.githubusercontent.com/5260172/38022653-c4e35012-3288-11e8-80f6-83cd6ac01ee1.png)

Here are the steps to reproduce:

1.  Remove crawl schedule
```
Get-SPEnterpriseSearchServiceApplication | Get-SPEnterpriseSearchCrawlContentSource | Set-SPEnterp
riseSearchCrawlContentSource -ScheduleType Incremental -RemoveCrawlSchedule
```
2. Check crawl schedule existence (should not return anything)
```
Get-SPEnterpriseSearchServiceApplication | Get-SPEnterpriseSearchCrawlContentSource | select -Expa
ndProperty IncrementalCrawlSchedule
```
3.  Test crawl schedule creation with `Whatif ` parameter 
```
Get-SPEnterpriseSearchServiceApplication | Get-SPEnterpriseSearchCrawlContentSource | Set-SPEnterp
riseSearchCrawlContentSource -ScheduleType Incremental -DailyCrawlSchedule -CrawlScheduleRepeatInterval 30 -CrawlSchedul
eRepeatDuration 1440 -CrawlScheduleStartDateTime ( Get-Date ).AddDays(30).Date -WhatIf
```
4. Repeat the step 2 (Check crawl schedule existence (should not return anything)
Get-SPEnterpriseSearchServiceApplication | Get-SPEnterpriseSearchCrawlContentSource | select -Expa
ndProperty IncrementalCrawlSchedule

**Comment by tseward** [comment]
This should likely be reported as a product bug instead of altering the documentation if the switch is indeed not working. Alternatively, if the switch is not intended to function, have it removed from the cmdlet and update the documentation to reflect the switch removal. @Techwriter40

**Comment by Techwriter40** [comment]
@tklarsen can you review and submit bug if needed?  thanks

**Comment by Techwriter40** [comment]
Trevor, thanks. I have passed to our Search writer who will research and file bug if needed.

**Comment by YuriySamorodov** [comment]
@tseward I guess it is a good practice to enable all adjusting cmdlets (with "Update", "Set","Delete", "Remove" etc verbs) with common parameters (like WhatIf,  Verbose). This is a crucial for scripting guys to have an option to test before deleting something.

Anyway, I feel sorry for the inconvenience. Please feel free to drop my documentation request.

**Comment by AndreaBarr** [comment]
@YuriySamorodov Thank you for this feedback

I am closing this ticket upon your request to drop the doccumentation request.
