### ISSUE TITLE
This command will be disabled on April 15, 2020

### ISSUE THREAD

**Issue by Gideon122** [MicrosoftDocs/office-docs-powershell#5061]
Just letting everyone know that, according to https://techcommunity.microsoft.com/t5/exchange-team-blog/disabling-new-moverequest-for-local-mailbox-moves/ba-p/1214776#, this command will be disabled for local moves within Exchange Online.  It will only be available to move mailboxes between Exchange on-premises and Exchange Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6fd9b17-5a2f-6e0a-f25b-a78aa5530b55
* Version Independent ID: 7f729071-f372-8270-a03a-e2d025fba93f
* Content: [New-MoveRequest (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/new-moverequest?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/New-MoveRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/New-MoveRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @Gideon122, thank you for your feedback.

I understand that it's not a very well know or popular feature so I think there is no need to add this information.

@chrisda what do you think?

**Comment by yogkumgit** [comment]
@chrisda please give your opinion. Thanks

**Comment by chrisda** [comment]
Note added to topic.

Thanks for the feedback.

Closing
