### ISSUE TITLE
Rate Limiting for New-Team?

### ISSUE THREAD

**Issue by CoasterKaty** [MicrosoftDocs/office-docs-powershell#5063]
I'm getting a 429 Too Many Requests error if I try to create more than one team every couple of minutes using New-Team. Is there any rate limiting in place (there is nothing about this in any of the docs)?
I was hoping to automate management of some teams but if I can't run New-Team reliably in a loop it's not much good for automation tasks :(

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by mitchbh** [comment]
I have the exact same issue. And i do not create huge amout of teams. Maybe 10-20 a hour. 

New-Team : Error occurred while executing 
 Code: TooManyRequests
 Message: Too Many Requests
 InnerError

**Comment by CoasterKaty** [comment]
I guess after some thought my question is:
Is this by design? In which case, bad as undocumented...
Or is it temporary because the entire world is trying to set up teams for remote working due to Coronavirus, causing huge load on the servers?

**Comment by mitchbh** [comment]
> I guess after some thought my question is:
> Is this by design? In which case, bad as undocumented...
> Or is it temporary because the entire world is trying to set up teams for remote working due to Coronavirus, causing huge load on the servers?

I hope this will be limited to a subscription/user

**Comment by tameemansari** [comment]
@CoasterKaty API throttling limits are at the tenant level for almost all APIs under the graph. Just executing New-Team shouldn't report a HTTP 429 error. I suspect that there are other API calls which are occurring at the point against this tenant whereby graph is throttling APIs. 

Can you share details of what you are doing prior or on the side while executing this new-Team cmdlet? With the v1.0.5 release of the teams module most Get-* cmdlets are able to handle the graph throttling aspects. We intend to expand that to other cmdlets in the coming months.

**Comment by CoasterKaty** [comment]
I wasn’t running anything else and just New-Team in a loop (attempting to create 3 teams from a CSV). Using 0.9.6 because the Template parameter hasn’t made it into 1.0.x yet. Also manually running New-Team twice within 10 seconds caused the second request to fail with Too Many Requests.

There was probably 200 people using Teams via the web interface on the same IP and tenant while I was trying this.

**Comment by mitchbh** [comment]
anything new?

**Comment by dariomws** [comment]
Hi @CoasterKaty and @mitchbh, thank you for your feedback.

Have you tried with version 1.0.5 as @tameemansari said?

Also, I think it's a good idea to open a support ticket as he said there is no limit for this specific cmdlet/graph API, and it could be an issue with your tenant or some tenants.

**Comment by CoasterKaty** [comment]
No, I can’t use anything newer than 0.9.6 until the Template parameter makes it into 1.0.x 😟

**Comment by dariomws** [comment]
Ok, please open a support ticket, I think it the best option here.

If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

**Comment by tameemansari** [comment]
@CoasterKaty can you share your script if thats possible. I recall we making appropriate changes to ensure template support is handled the right way in the BETA module. I can take a look and advise accordingly.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @CoasterKaty 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
