### ISSUE TITLE
Possible spelling error in Example 5?

### ISSUE THREAD

**Issue by osbistonium** [MicrosoftDocs/office-docs-powershell#5066]
Shouldn't the second line read:
$callableEntity = New-CsAutoAttendantCallableEntity -Identity $callableEntityGroup -Type SharedVoicemail -EnableTranscription
The identity variable should be $callableEntityGroup and not $callableEntityId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b10b3afe-6425-f0b7-3eb0-a17c6a9d6fef
* Version Independent ID: 9dec1f94-908b-0992-c986-084449965df0
* Content: [New-CsAutoAttendantCallableEntity (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csautoattendantcallableentity?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @osbistonium Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
