### ISSUE TITLE
Set-SPProjectPermissionMode : A parameter cannot be found that matches parameter name 'AdministratorAccount'.

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/office-docs-powershell#5067]
Examples show using -AdministratorAccount, but this is not a valid parameter, confirmed by testing the command with this parameter on SharePoint 2016 farm with Project Server Service App. Please correct the document by removing -AdministratorAccount parameter from the examples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04a0d8f1-c420-9cb6-6e2a-6a55338028d1
* Version Independent ID: 35bad0fb-a392-8b48-7b23-ffcb3298b46c
* Content: [Set-SPProjectPermissionMode (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spprojectpermissionmode?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPProjectPermissionMode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPProjectPermissionMode.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
@yogkumgit in 2016/2019 (do not have 2013 to test with), the parameter `-AdministratorAccount contoso\John.Woods` does not exist, it can be removed from the example.

**Comment by get-itips** [comment]
Hello @SharePointBlackBelt Vincent 👍 Thanks for noticing this. Created a pull request to correct the examples.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @SharePointBlackBelt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
