### ISSUE TITLE
MaxReceiveSize not working in Exchange Online

### ISSUE THREAD

**Issue by HeinzLm** [MicrosoftDocs/office-docs-powershell#5068]
Hello,

Get-Mailbox -Filter { MaxReceiveSize -gt 100 } or 
Get-Mailbox -Filter "MaxReceiveSize -gt 100" or
Get-Mailbox -Filter "MaxReceiveSize -gt '100'"
work on premise, but not in Exchange Online.

Wrong syntax or limitation? Would these limitations be documented anywhere?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/recipient-filters/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/recipient-filters/filter-properties.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @HeinzLm, thank you for your feedback.

It's documented in the article:

You can only use the Filter parameter to look for the value Unlimited for this property. For example, Get-Mailbox -Filter "MaxReceiveSize -eq 'Unlimited'" or Get-Mailbox -Filter "MaxReceiveSize -ne 'Unlimited'".
You can't use the Filter parameter to look for size values of this property. Instead, use this syntax: Get-Mailbox | where "$_.MaxReceiveSize -<Operator> '<Size>'". For example, Get-Mailbox | where "$_.MaxReceiveSize -gt '50GB'".

**Comment by HeinzLm** [comment]
Hi @dariomws,

funny that the table width is more or less exactly the first four columns including "Value". Never saw the "Comments" column. Even if I have more white space left and right than content.
I would advise on changing that.

Thanks for the hint and info!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @HeinzLm 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
