### ISSUE TITLE
How to install module that has Test-ImapConnectivity for Exchange 2010 on premise?

### ISSUE THREAD

**Issue by kristianjaeger** [MicrosoftDocs/office-docs-powershell#5069]
Where can one find the source or install this module?
https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Test-ImapConnectivity.md

It's not installed by default in PowerShell in 5.1.17763.1007

Test-ImapConnectivity : The term 'Test-ImapConnectivity' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.

Just to clarify, this is in the context of testing IMAP as a client (not using a PS window on the server).

Thanks!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @kristianjaeger, thank you for your feedback.

It's installed by default on Exchange Management Shell, you don't need to install it.

**Comment by kristianjaeger** [comment]
So this cannot be done from the client side? Thanks. I might need my Exchange counter part to do this then. Thanks.

**Comment by dariomws** [comment]
If you want to run it from a workstation, for example, you should install Exchange Management Tools there.

**Comment by kristianjaeger** [comment]
Okay, thank you.  Trying to validate IMAP connectivity from a client and that would be helpful. Cheers.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @kristianjaeger Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
