### ISSUE TITLE
Avoid using aliases

### ISSUE THREAD

**Issue by AspenForester** [MicrosoftDocs/office-docs-powershell#5070]
Example 4 would be better if it did not use aliases
`Get-UnifiedGroup | where-object { -not ($_.ManagedBy) }`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d063d71b-c1d5-e995-9e0d-a3daf646c712
* Version Independent ID: 7cff679f-a994-e371-a227-b8c5635f1aa2
* Content: [Get-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/Get-UnifiedGroup?redirectedfrom=MSDN&view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Get-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @AspenForester Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
