### ISSUE TITLE
Set-SPOUser documentation out of date

### ISSUE THREAD

**Issue by kpinel** [MicrosoftDocs/office-docs-powershell#5072]
Recently updated the module and there appears to be a new switch
-UpdateUserTypeFromAzureAD

Is there a way to remove an admin after we have completed a support ticket? We are starting to get complaints about still having owner access to various OneDrives long after a ticket has been closed

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
@yogkumgit looks like `-UpdateUserTypeFromAzureAD` switches from Guest to Member or visa versa. An Azure B2B user by default is added as a Guest, but if they need more functionality, in Azure AD you can switch them to be a Member.

See https://docs.microsoft.com/en-us/azure/active-directory/b2b/user-properties#can-azure-ad-b2b-users-be-added-as-members-instead-of-guests for more details.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @kpinel 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
