### ISSUE TITLE
anyway to be more specific with "-member"? maybe a hasthable with keys matching identifiers?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/office-docs-powershell#5073]
On its own, "-Member" will try to find a match.  Mostly OK.

But, sometimes, there are multiple, [ambiguous] recipients that match the supplied "member" parameter, so this fails.  I see this with Office 365 group names with display names incorporate an email address or match the "alias" for a mailbox.  PowerShell doesn't know which one you mean, so the operation fails.

I *can* address this by using "$mailboxToAdd = get-mailbox -identity ...; add-distributiongroupmember -member $mailboxToAdd", but that "get-mailbox" additional step adds considerable latency (and work for Microsoft's PowerShell servers!)

If I could do something like...

[hashtable]$mailboxToAdd=@{alias="billgates"}

...that avoids the "get-mailbox" round trip, making everything faster and simpler.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f0166e-7855-9525-c93a-da83f82e48a8
* Version Independent ID: 1808c549-b2cf-cd24-559c-7ef30642b08a
* Content: [Add-DistributionGroupMember (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/add-distributiongroupmember?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Add-DistributionGroupMember.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Add-DistributionGroupMember.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @anwarmahmood1, thank you for your feedback.

Docs feedback is available to help us to improve documentation. In this case, I think there is no need to add this information to the article. The description says "You can use any value that uniquely identifies the recipient".
Maybe you can try with [Get-EXOMailbox](https://docs.microsoft.com/powershell/module/exchange/powershell-v2-module/get-exomailbox).

Also, you can get more help here:
https://techcommunity.microsoft.com/

Thank you again!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @anwarmahmood1  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
