### ISSUE TITLE
Set-PnPUserProfileProperty with Application Permission in Azure Function

### ISSUE THREAD

**Issue by sudharsank** [MicrosoftDocs/office-docs-powershell#5074]
When using **Set-PnPUserProfileProperty** in Azure Function with PowerShell and the permissions has been defined using the **Application Permission**. Once connected to the admin site url using clientid, tenant and cert and try to update the UserProfile Property, it throws the below error

>2020-03-15T07:49:48.239 [Error] Set-PnPUserProfileProperty : Access denied. You do not have permission to perform this action or access this resource.
at run.ps1: line 50
+ Set-PnPUserProfileProperty
+ __________________________
    + CategoryInfo          : WriteError: (:) [Set-PnPUserProfileProperty], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.UserProfiles.SetUserProfileProperty
2020-03-15T07:49:48.411 [Error] Set-PnPUserProfileProperty : Access denied. You do not have permission to perform this action or access this resource.

Attached the screenshot for the reference
![PnP PS Issue](https://user-images.githubusercontent.com/10280385/76697721-99a4c100-66d5-11ea-85da-68487c1f9b08.png)

Below are the permissions given for the application in Azure API Permissions
![Permission List](https://user-images.githubusercontent.com/10280385/76697749-120b8200-66d6-11ea-8e6e-514925501931.png)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sudharsank 👍 

How are you?

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by sudharsank** [comment]
Created the issue on the PnP-PowerShell repo below is the link to that issue.
https://github.com/SharePoint/PnP-PowerShell/issues/2582
So closing this because of duplicate.
