### ISSUE TITLE
Unable to assign custom policy

### ISSUE THREAD

**Issue by Bart-Hoofd** [MicrosoftDocs/office-docs-powershell#5076]
I tried using this to assign a custom TeamsMeetingPolicy policy, but I keep receiving the error "New-CsBatchPolicyAssignmentOperation : Provided policy name is not valid". Does it not support custom policies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d149ca60-bfb7-5077-2643-1a08ad926cca
* Version Independent ID: 24754aee-bff2-fa16-e7e6-af45362fd916
* Content: [New-CsBatchPolicyAssignmentOperation (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csbatchpolicyassignmentoperation?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @Bart-Hoofd, thank you for your feedback.

It's working on my lab:
![image](https://user-images.githubusercontent.com/33589238/76760079-c7d4e000-676b-11ea-85dc-d59634025bab.png)
![image](https://user-images.githubusercontent.com/33589238/76760107-cf948480-676b-11ea-8473-22aacb9b7839.png)

I am using module 1.0.5. Please check your version. They were added in this, they were previously in the preview module.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @Bart-Hoofd Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Bart-Hoofd** [comment]
Documentation is no reflecting any update, and issue still persist? I can also not determine any reason for closing this ticket?

**Comment by dariomws** [comment]
@Bart-Hoofd Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dariomws** [comment]
Hi @Bart-Hoofd, I have additional information about this cmdlet.

Even though the cmdlet is in the stable version of the module, I have confirmation from the product team that it is still in preview so we will maintain the sentence at the top of the article, at least, for now. And that the Product Team is aware of this and working the matter.

**Comment by Bart-Hoofd** [comment]
Hi Dario,

Thanks!

________________________________
Van: Dario Woitasen <notifications@github.com>
Verzonden: dinsdag 7 april 2020 17:44
Aan: MicrosoftDocs/office-docs-powershell <office-docs-powershell@noreply.github.com>
CC: Bart-Hoofd <bart.hoofd@outlook.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/office-docs-powershell] Unable to assign custom policy (#5076)


Hi @Bart-Hoofd<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBart-Hoofd&data=02%7C01%7C%7C1844c83e02a34a014d9b08d7db0a8e25%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637218710682695500&sdata=P1i0QvAdJFPssTTsfSBURznlLr0sNY%2BSUJNnszjwO%2Fk%3D&reserved=0>, I have additional information about this cmdlet.

Even though the cmdlet is in the stable version of the module, I have confirmation from the product team that it is still in preview so we will maintain the sentence at the top of the article, at least, for now. And that the Product Team is aware of this and working the matter.
