### ISSUE TITLE
Can't specifiy long DisplayName while using UnifiedGroup command

### ISSUE THREAD

**Issue by MarwaMS92** [MicrosoftDocs/office-docs-powershell#5079]
Using the command mentioned here:  https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/new-unifiedgroup?view=exchange-ps 
You can't add DisplayName with more than 64 chars however it is mentioned that the limit of chars for the DisplayName is 256 chars. the command is also not working even if the Alias attribute is provided (limit of Alias is up to 64 chars).

The only workaround i found is to use -Name attribute with any dummy data to be able to set Alias to 64 chars and DisplayName to 256 chars.
The article is stating that the -Name attribute is legacy and no longer being used and it gave an example without using it.

Could you please advise on this as it seems that -Name is still required in certain cases.

![image](https://user-images.githubusercontent.com/47694480/76712615-2cb81800-6723-11ea-9bd8-16aad31063ff.png)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dacowan  Thank you very much for the contribution and updating the documentation with PR. @MarwaMS92 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
