### ISSUE TITLE
Action - DynamicDelivery

### ISSUE THREAD

**Issue by Wallace4444** [MicrosoftDocs/office-docs-powershell#5080]
The document seems to be missing DynamicDelivery option under the Actions section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e3c5b08-b828-b680-0aaf-56b6356952a2
* Version Independent ID: 1c76531f-7285-84cc-ae3e-a3c61264a51b
* Content: [Set-SafeAttachmentPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-safeattachmentpolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Set-SafeAttachmentPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Set-SafeAttachmentPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @Wallace4444 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
