### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by npigit** [MicrosoftDocs/office-docs-powershell#5081]
Hello,

I received the bellow message when I try to use the "Priority" switch

A parameter cannot be found that matches parameter name 'Priority'.
    + CategoryInfo          : InvalidArgument: (:) [Set-MoveRequest], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-MoveRequest
    + PSComputerName        : outlook.office365.com

The command that I used is:
Set-MoveRequest -Identity 'My user' -Priority high

I am using the version 0.3582.0 of Exchange Online management
Import-Module ExchangeOnlineManagement; Get-Module ExchangeOnlineManagement # Get ExO V2 current install

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.3582.0   ExchangeOnlineManagement            {Get-EXOCasMailbox, Get-EXOMailbox, Get-EXOMailboxFolderPermission, Get-EXOMailboxFolderStatistic... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14bb8e89-6d0b-a21d-6993-c732d0c8162f
* Version Independent ID: 9558ccf6-35e1-4119-7a1f-6b4159209a12
* Content: [Set-MoveRequest (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/set-moverequest?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/Set-MoveRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/Set-MoveRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @npigit, thank you for your feedback.

This parameter is available only in on-premises Exchange.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @npigit 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by npigit** [comment]
@yogkumgit Thank you for the clarification
