### ISSUE TITLE
swapsite operation not yet supported

### ISSUE THREAD

**Issue by ceejey01** [MicrosoftDocs/office-docs-powershell#5082]
When attempting to swap root site, I get the error: swapsite operation not yet supported. Please assist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb8f8e8-1242-363c-be77-038142b4efb9
* Version Independent ID: 54a60006-3d61-4bb9-a040-60fe77ef9f85
* Content: [Invoke-SPOSiteSwap (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/invoke-spositeswap?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md)
* Service: **sharepoint-powershell**
* GitHub Login: @WayneEwington
* Microsoft Alias: **waynewin**

**Comment by tseward** [comment]
You'll need to wait until your tenant is enabled for this feature.

**Comment by ceejey01** [comment]
Thank you.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by ceejey01** [comment]
Are there criteria for enabling this for tenants? Is there any time frame for this? Is there a Microsoft documentation to back this up so that I can show this to my superiors?

**Comment by tseward** [comment]
It is rolling out currently:

https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=SharePoint&searchterms=57309

**Comment by ceejey01** [comment]
@tseward I really appreciate your assistance

**Comment by ma7mgte** [comment]
I have the latest SPO Management Shell and I do not see the Invoke-SPOSiteSwap command listed.  Am I missing something?

**Comment by tseward** [comment]
@ma7mgte can you please output the version of the module you have installed? `Get-Module` will show it.

**Comment by get-itips** [comment]
@yogkumgit Yogesh, no further response from the user to the question raised by @tseward so I think we can close this issue now. If the user comes back, he can re-open the thread.

**Comment by yogkumgit** [comment]
@get-itips  and @tseward  Thank you very much for the contribution and digging deep into it.  @ceejey01 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
