### ISSUE TITLE
GUI problem in combination with Powershell?

### ISSUE THREAD

**Issue by duracellkonijn22** [MicrosoftDocs/office-docs-powershell#5089]
When adding new Safe attachment policies or safe links policies, the policy isn't showing in the GUI.
When creating policy from GUI, it show up into the get-cmdlets from Powershell

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @duracellkonijn22 Hendrik
Can you please be more detailed and specific on what documentation you have followed, what steps you have taken and what cmdlets you have ran to understand if we need to change any documentation or if we have to redirect you to support of your tenant?
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and digging deep into it.  @duracellkonijn22 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
