### ISSUE TITLE
Apply-PnPTenantTemplate does not work with MFA enabled

### ISSUE THREAD

**Issue by mjarmstrong** [MicrosoftDocs/office-docs-powershell#5096]
Apply-PnPTenantTemplate does not work when MFA is enabled It returns "Apply-PnPTenantTemplate : The remote server returned an error: (403) Forbidden."

What I observed so far:

It does not work when I'm using -useWebLogin
It does not work when I'm using Azure AD Application Permissions (https://github.com/SharePoint/PnP-PowerShell/tree/master/Samples/SharePoint.ConnectUsingAppPermissions)
It does not work when I'm using PnPO365ManagementShell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3240d3-6a7d-fc4b-62fd-d3a5375d8a4a
* Version Independent ID: 561212df-4dab-92b7-b634-57d53d313c6f
* Content: [PnP PowerShell overview](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @mjarmstrong Michael 👍 How are you ?

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by mjarmstrong** [comment]
Hello @get-itips, I am well, thank you. Struggling with a client deployment due to the issue above. I have also opened an issue at the repo you suggested, but have realized that none of the issues there are being addressed. All issues dating back to 2019 are sitting under "Needs Triage".
