### ISSUE TITLE
Get-PnPTenantTemplate

### ISSUE THREAD

**Issue by VishnuMohan259** [MicrosoftDocs/office-docs-powershell#5102]
Hi , Tried to get tenant template of the site but getting different errors
1. Tried to connect with hub site and executed the code ,Got 403 error.
2. After that Connect to Tenant site and executed the code ,got some other error please find the attachment

![TenantTemplate](https://user-images.githubusercontent.com/53042453/76954285-1b932500-6936-11ea-965c-9732f328ae85.png)

How can i get template of hub site and its associated sites?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @VishnuMohan259 Vishnu 👍 How are you ?

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @VishnuMohan259 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
