### ISSUE TITLE
Set-PnPFileCheckedOut does not work?

### ISSUE THREAD

**Issue by tdalon** [MicrosoftDocs/office-docs-powershell#5103]
![image](https://user-images.githubusercontent.com/6458444/76940395-73ac3600-68fa-11ea-970e-f0b1be17dacc.png)
It seems the command [Set-PnPFileCheckedOut](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpfilecheckedout?view=sharepoint-ps) does not work for me. I can run it but the file is not checked-out properly (checked in the web browser)
What am I doing wrong?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tdalon thierry 👍 How are you ?

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @tdalon 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
