### ISSUE TITLE
TEAMS - Powershell Script - create multiple private channels

### ISSUE THREAD

**Issue by gcoad** [MicrosoftDocs/office-docs-powershell#5105]
Hi,

I'm trying to find a script to create multiple private channels (teams already created) with specific owners and users imported from a CSV.

Any ideas ?

Thanks

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by gcoad** [comment]
I tried to create the script by myself but i've an issue with it... Someone can help me please ?

When i launch it, all channels are created (Chan 1 - 2 - 3)
Name and Owners are Ok, Fine !
But only the members of the last CSV line (user6 and user7) are added to all channels ...

CSV Exemple
---------------------------------------------
ChannelName,ChannelDescription,ChannelOwner,ChannelUsers
chan1,desc1,user1@mail.com,user2@mail.com;user3@mail.com
chan2,desc2,user1@mail.com,user4@mail.com;user5@mail.com
chan3,desc3,user1@mail.com,user6@mail.com;user7@mail.com
---------------------------------------------


SCRIPT EXEMPLE
---------------------------------------------
#Script created by GCOAD for Institut Le Rosey
Connect-MicrosoftTeams
$TeamschannelList = Import-Csv -Path C:\teams\Teamsclass.csv 
Foreach ($Teamchannel in $TeamschannelList) {

#Create Channels and set Owner
New-TeamChannel -GroupId ****TeamsIdCensored**** -DisplayName $Teamchannel.ChannelName -Description $Teamchannel.ChannelDescription -MembershipType Private  -Owner $Teamchannel.ChannelOwner
}

#Add members in channels
$Members = $Teamchannel.ChannelUsers.Split(";")
Foreach ($Teamchannel in $TeamschannelList) {
Foreach($Member in $Members) {
Add-TeamChannelUser -GroupId****TeamsIdCensored**** -DisplayName $Teamchannel.ChannelName -User $Member
}
}

---------------------------------------------


Thank you
