### ISSUE TITLE
Applicable on Teams?

### ISSUE THREAD

**Issue by itthing** [MicrosoftDocs/office-docs-powershell#5106]
Is this command applicable with Teams as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ac40f89-1490-e24c-0f87-285ff240bc2d
* Version Independent ID: 7a0f90ee-22e4-75c8-7043-584c232ceb4d
* Content: [Get-CsUserDelegates (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csuserdelegates?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Get-CsUserDelegates.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsUserDelegates.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @itthing 
This cmdlet is only included in the Server version of Skype For Business, as the article indicates.
Hope this information helps you.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @itthing 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
