### ISSUE TITLE
What happens with Disable-Mailbox action?

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/office-docs-powershell#5107]
Please add a note regarding Disable-Mailbox action. What happens? How can you recover those mailboxes?

"When a mailbox is deleted with the Remove-Mailbox cmdlet, it's not actually deleted. It's hidden in Exchange and moved in Active Directory to the organizational unit (OU) Soft Deleted Objects. This enables administrators to recover deleted mailboxes for up to 30 days after deletion."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 398ec853-bc44-657b-3a47-ba4b5d1d54f9
* Version Independent ID: 5a1b03ab-7bad-a8df-f705-1c504f8dfd12
* Content: [Undo-SoftDeletedMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/undo-softdeletedmailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Undo-SoftDeletedMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Undo-SoftDeletedMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and updating the documentation with PR. @trudolf-msft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
