### ISSUE TITLE
Pls Validate the OverflowAction

### ISSUE THREAD

**Issue by rickleye** [MicrosoftDocs/office-docs-powershell#5108]
Could someone pleas validate the Overflow action\Target against https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue. Directions via GUI. We have tried to use the Voicemail option but it does not work either for a person or a group DL.  And such option isnt available in the GUI. It is available for Auto Attendant set up but now for call queue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7364cece-00a4-7e29-4fa9-190db5f9e3dd
* Version Independent ID: 67efa086-edb0-2828-cc14-4c245290e4f3
* Content: [Set-CsCallQueue (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cscallqueue?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@rickleye Rick
I could verify the directions to the overflow action, aren't you seeing that option?

**Comment by rickleye** [comment]
No once I put voicemail for overall action it asks for a target and neither user Id nor guid Id works.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by get-itips** [comment]
are you using the search by display name field ?


> No once I put voicemail for overall action it asks for a target and neither user Id nor guid Id works. Get Outlook for iOS<https://aka.ms/o0ukef>


Ok, please, kindly open a support ticket directly on your tenant, to find out what is happening in your scenario.

**Comment by rickleye** [comment]
This happens on all tenants. I have tried so far. A colleague brought this to me attention. I tried it on mine. And I get the same results. I can send you screen shots if you need

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rickleye** [comment]
Now we are looking at Powershell not GUI. GUI is fine just PSH doesn’t match up.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by get-itips** [comment]
> Now we are looking at Powershell not GUI. GUI is fine just PSH doesn’t match up. Get Outlook for iOS<https://aka.ms/o0ukef>


I assume you are using the -OverflowAction and -OverflowActionTarget parameters right? What are you experiencing?

**Comment by get-itips** [comment]
@rickleye any further comments?

**Comment by rickleye** [comment]
I sent an email yesterday

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by get-itips** [comment]
> I sent an email yesterday Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)


Sorry Rick, I didn't quite understand. did you see my last question? :

> I assume you are using the -OverflowAction and -OverflowActionTarget parameters right? What are you experiencing?

**Comment by rickleye** [comment]
So this is the command that I run.
Overflow action voicemail
Overflowaction Target = DL distribution list.
Set-CsCallQueue -Identity a0916354-8251-4e29-88ff-5af68f5702b4 -DistributionLists 90bcdc1d-0824-4dff-a030-b3acfe16482c -OverflowAction Voicemail -OverflowActionTarget 90bcdc1d-0824-4dff-a030-b3acfe16482c

[cid:image001.jpg@01D6034D.220079F0]

However, when I use a user as an OverflowActiontarget it works.

**Comment by get-itips** [comment]
Ok @rickleye I appreciate the information, from my understanding, that doesn't seems like an issue in documentation but rather an issue with maybe the tenant or the cmdlet, please kindly, open a support ticket on your tenant, they will be able to help you with your issue. Thank you

**Comment by rickleye** [comment]
Okay, I will open a ticket and get back 2 you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @rickleye 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
