### ISSUE TITLE
Get-PnPSearchCrawlLog ItemTime is incorrect

### ISSUE THREAD

**Issue by abates100** [MicrosoftDocs/office-docs-powershell#5113]
Maybe I just don't understand what ItemTime is supposed to represent but if you look at the Raw format it appears to be SPItemModifiedTime(in UTC) +7  Is this something particular to specific tenants?

ex.
CrawlTime       : 3/18/2020 6:18:50 PM
ItemTime        : 3/19/2020 1:18:32 AM

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @abates100 👍 how are you ?

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @abates100 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
