### ISSUE TITLE
Get-pnptenantsite Conditional Access Policy

### ISSUE THREAD

**Issue by msnaveen** [MicrosoftDocs/office-docs-powershell#5118]
I would start saying thanks for the wonderful Module to work with. Well i was working with this module and i figured out that whenever we run get-pnptenantsite -detailed | select ConditionalAccessPolicy,URL i always get the ConditiopnalAccessPolicy to be AllowFullAccess even if i do this for  single URL the same issue, however if i run the get-sposite | select ConditiopnalAccessPolicy ,URL it shows the value to be LimitedAccess. Can you please let me know, if i am seeing this different ?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by msnaveen** [comment]
i also want to add one thing, it is on the for loop we are missing it
$sites = Get-PnPTenantSite -Detailed  -IncludeOneDriveSites
foreach ($site in $sites) {
 
        $site | Select-Object  Url, ConditionalAccessPolicy       
    }

The ConditionalAccessPolicy defaults to full access

If i run against a specific site it shows the correct one.

Sorry for the confusion.

**Comment by msnaveen** [comment]
Hi team, 

I was able to get the details but it is running the same command twice 

NON WORKING
==================
$sites = Get-PnPTenantSite -Detailed -IncludeOneDriveSites
foreach ($site in $sites) {
    $site | Select-Object  Url, ConditionalAccessPolicy       
}

WORKING
=============
$sites = Get-PnPTenantSite -Detailed -IncludeOneDriveSites |select url 
foreach ($site in $sites) {

         Get-PnPTenantSite -Url $site.Url | Select-Object Url, Owner, Template, ConditionalAccessPolicy, Sharing* }

We should not be running twice to get the correct sets of details. I feel the first command should work as it should.

Thanks for looking into this.

**Comment by get-itips** [comment]
Hello @msnaveen how are you ? 👍 
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @msnaveen 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
