### ISSUE TITLE
Bug report: mailNickName containing # or / causes error in scheduling meeting

### ISSUE THREAD

**Issue by Bart-Hoofd** [MicrosoftDocs/office-docs-powershell#5119]
I stumbled on this issue recently: when creating a Team with a mailNickName containing # or /, I was unable to successfully schedule a meeting from within that Team. Replacing these characters (with e.g. _) in the unified group's Alias or EmailAddresses later does not solve the issue, but when omitting the characters from the mailNickname upon creation of the Team, the issue does not show up. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Bart-Hoofd Bart, how are you? 👍 
Although we only handle documentation issues, I will try to pass this along to the product team.
Thank you

**Comment by Bart-Hoofd** [comment]
Thnx!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by get-itips** [comment]
@yogkumgit please close this one. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Bart-Hoofd 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
