### ISSUE TITLE
Disconnect from Exchange Online

### ISSUE THREAD

**Issue by mprentice22153** [MicrosoftDocs/office-docs-powershell#5120]
Now that there is a Connect-ExchangeOnline cmdlet, what is the proper way to disconnect from Exchange Online?  Do we still just remove the PSSession?  Can we get a proper Disconnect-ExchangeOnline cmdlet which actually ends the session?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @mprentice22153, thank you for your feedback.

I understand that you can use "Remove-PSSession -Id 1" (you should check session id).

Anyway:

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, contact us at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

**Comment by mprentice22153** [comment]
Remove-PSSession only removes it from my active PSSessions.  It does not
actually disconnect the session on the server, based on my experience.
Because there is a limitation with the number of active connections a user
can have with Exchange Online, this is preventing us from doing proactive
monitoring and management of our hundreds of customers through our
delegated admin.

We are very happy with the Exchange Online v2 preview.  Just hoping for
some additional features.  Maybe this feature isn't necessarily a
PowerShell feature but one that needs to be implemented on the Exchange
Online servers first?  Is it even possible to disconnect a session by any
method, or do they just time out and fade away?

Matthew

**Comment by dariomws** [comment]
From [Remove-PSSession](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/remove-pssession) article:
"The Remove-PSSession cmdlet closes PowerShell sessions (PSSessions) in the current session. It stops any commands that are running in the PSSessions, **ends the PSSession, and releases the resources that the PSSession was using**."

From [Connect to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell) article:
"Be sure to disconnect the remote PowerShell session when you're finished. If you close the Windows PowerShell window without disconnecting the session, you could use up all the remote PowerShell sessions available to you, and you'll need to wait for the sessions to expire. To disconnect the remote PowerShell session, run the following command.
Remove-PSSession $Session"

If it doesn't work with V2 or if you want to suggest a Disconnect-ExchangeOnline cmdlet, please contact the product team at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

Thanks!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @mprentice22153 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by navgupta1208** [comment]
This cmdlet is now available in April release. 
Disconnect-ExchangeOnline
