### ISSUE TITLE
New-team -Template parameter is not available anymore

### ISSUE THREAD

**Issue by fabtopia** [MicrosoftDocs/office-docs-powershell#5121]
The -template parameters at New-Team is not avaialble animore. It worked with 0.9.3 The at lastest version 1.0.5 the help said it exist but if you want to use it, there will be an error. If you type new-team -t<tab> nothing happend

**Comment by tameemansari** [comment]
Template support for creating new teams is available currently only in the preview module hosted on the PowerShell test gallery. You can follow the install instructions available at [this link](https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels-life-cycle-management#install-the-latest-teams-powershell-module-from-the-powershell-test-gallery).

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @fabtopia as @tameemansari kindly said, Template parameter is part of the preview module.
@yogkumgit Please proceed closing this issue.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @fabtopia 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
