### ISSUE TITLE
Add some info on how to install

### ISSUE THREAD

**Issue by Tweekism** [MicrosoftDocs/office-docs-powershell#5124]
This page should have "Install-Module -Name MicrosoftTeams" at the top, or something...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94694082-c529-5654-1734-57514ec17a1f
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [Microsoft Teams PowerShell](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Tweekism How are you?

I am afraid that, Table of Contents files do not include that information, the information you are looking for is [here](https://docs.microsoft.com/en-us/powershell/teams/intro?view=teams-ps) that leads you [here](https://www.powershellgallery.com/packages/MicrosoftTeams/)

Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Tweekism 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
