### ISSUE TITLE
The command 'Get-PnPAppInstance' is obsolete. Use Get-PnPApp instead

### ISSUE THREAD

**Issue by sagar4u** [MicrosoftDocs/office-docs-powershell#5125]
There is no mention of whether this command is obsolete and also Get-PnPApp command works differently

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e974e718-c739-a184-52d7-94d003303cc1
* Version Independent ID: f550b04f-cf4f-8fc4-d011-3d6c2f56e831
* Content: [Get-PnPAppInstance (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpappinstance?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPAppInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPAppInstance.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sagar4u 👍 how are you?

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by sagar4u** [comment]
I am fine. Thank you. I hope, you too. I'll check and open it there
