### ISSUE TITLE
Related Link Issue

### ISSUE THREAD

**Issue by aprmike** [MicrosoftDocs/office-docs-powershell#5126]
The related links for New-Team and Set-Team link back to the same article (Get-Team)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8450991f-9f85-4d87-51b3-efa8e1004a24
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/Get-Team?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for noticing @aprmike 
Created a PR to correct the article.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @aprmike Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
