### ISSUE TITLE
V2 Get-EXOMailboxStatistics seem to have recently broken at the endpoint

### ISSUE THREAD

**Issue by kevinblumenfeld** [MicrosoftDocs/office-docs-powershell#5128]
Receiving a REST Protocol error. This worked flawlessly since Ignite and only recently broke within a month.

Get-EXOMailboxStatistics -ExchangeGuid &lt;ToString() of GUIDs passed in a foreach loop&gt;

Get-EXOMailboxStatistics : An error occurred while processing this request..
ProtocolError: (:) [Get-EXOMailboxStatistics], Exception
One or more errors occurred., Microsoft.Exchange.Management.RestApiClient.GetExoMailboxStatistics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kevinblumenfeld, please ask this question at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

The EXO V2 module is still in Preview, and that email address is the best place to get answers.

Closing

**Comment by kevinblumenfeld** [comment]
I have done so.  Thank you @chrisda
