### ISSUE TITLE
missing content

### ISSUE THREAD

**Issue by WilliamHCPowell** [MicrosoftDocs/office-docs-powershell#5131]
no example (boilerplate text present)
-Identity parameter has no descriptio
-Ring parameter has no description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147adf03-ad24-cf04-4d2e-b2a25049a78e
* Version Independent ID: 7e8927aa-019e-499d-2664-34eb19782b38
* Content: [Set-CsOnlineDirectoryUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinedirectoryuser?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineDirectoryUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineDirectoryUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@tomkau Tom,
I could see that -Ring parameter accepts "ring1" and "ring2" however I could not find further information about the specific use of this parameter, can you help me with this? I appreciate.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @WilliamHCPowell Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
