### ISSUE TITLE
Adding Rights for Multiple Users at the same time

### ISSUE THREAD

**Issue by msozcelik** [MicrosoftDocs/office-docs-powershell#5132]
Could we add access rights for multiple users using only one command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb509e0a-2371-d5b8-6462-c0f29e6c8152
* Version Independent ID: b8fdd337-395d-0c42-4ff1-9a0969a9d578
* Content: [Add-MailboxPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/add-mailboxpermission?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Add-MailboxPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Add-MailboxPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @msozcelik, thank you for your feedback.

I understand there isn't a cmdlet to achieve this. You should try with foreach and/or import-csv together with Add-MailboxPermission.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @msozcelik 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by msozcelik** [comment]
Thanks for the reply!
As @dariomws suggested, I could be able to add rights for multiple users in a single cmdlet by using ForEach statement.

Example for assigning users full access rights for a resource:

$users = 'adam@contoso.com', 'terry@contoso.com', 'tony@contoso.com'
ForEach ($user in $users)
{
    Add-MailboxPermission `
        -Identity guestroom@contoso.com `
        -User $user `
        -AccessRights FullAccess
}

**Comment by dariomws** [comment]
@msozcelik I'm glad that this helped you. Thank you for this new information.
