### ISSUE TITLE
The term 'Add-TeamChannelUser' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/office-docs-powershell#5139]
Module "MicrosoftTeams" version 1.0.5 is installed, but this command is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74381d05-2e95-4751-4285-752a46eb025f
* Version Independent ID: 2481b258-b593-e323-90f0-e9ca6e7797bf
* Content: [Add-TeamChannelUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by Bart-Hoofd** [comment]
This command is not included in the current version 1.0.5 of the MicrosoftTeams module. The 1.0.5 version is currently limited to these commands: 
Add-TeamUser
Connect-MicrosoftTeams
Disconnect-MicrosoftTeams
Get-CsPolicyPackage
Get-CsUserPolicyPackage
Get-CsUserPolicyPackageRecommendation
Get-Team
Get-TeamChannel
Get-TeamHelp
Get-TeamsApp
Get-TeamUser
Grant-CsUserPolicyPackage
New-Team
New-TeamChannel
New-TeamsApp
Remove-Team
Remove-TeamChannel
Remove-TeamsApp
Remove-TeamUser
Set-Team
Set-TeamArchivedState
Set-TeamChannel
Set-TeamsApp
Get-CsBatchPolicyAssignmentOperation
Get-CsUserPolicyAssignment
New-CsBatchPolicyAssignmentOperation

**Comment by JLambEJG** [comment]
This command is listed in this document, which also links to this very same version (see the overview page). If the command is not contained within the version that you are documenting, then remove the command from the documentation. Otherwise, please provide a link to the module where this command is contained.

**Comment by Aysan-kore** [comment]
I have the same issue MicrosoftTeams Module version installed is 1.0.5, but the Add-TeamChannelUser' is not recognized as the name of a cmdlet

**Comment by isty1974** [comment]
Same issue for me, but channel doesn't have Group ID, it has own ID.
GroupId like this: 31f1ff6c-d48c-4f8a-b2e1-abca7fd399df
ID like this: 19:2db7620785442c5d46387eb8a117264a@thread.tacv2
So, the paramater was incorrect.

**Comment by rlodev67** [comment]
This command is integrated in the preview module, not this one.
You have to install the one from "https://www.poshtestgallery.com/packages/MicrosoftTeams/1.0.21"
if you run the powershell command, be sure to add the repository before.

**Comment by pemile** [comment]
even in 10.0.21 Add-TeamChannelUser is not existing
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-CsBatchPolicyAssignmentOperation               1.0.21     MicrosoftTeams
Function        Get-CsGroupPolicyAssignment                        1.0.21     MicrosoftTeams
Function        Get-CsUserPolicyAssignment                         1.0.21     MicrosoftTeams
Function        New-CsBatchPolicyAssignmentOperation               1.0.21     MicrosoftTeams
Function        New-CsGroupPolicyAssignment                        1.0.21     MicrosoftTeams
Function        Remove-CsGroupPolicyAssignment                     1.0.21     MicrosoftTeams
Function        Set-CsGroupPolicyAssignment                        1.0.21     MicrosoftTeams
Cmdlet          Add-TeamUser                                       1.0.21     MicrosoftTeams
Cmdlet          Connect-MicrosoftTeams                             1.0.21     MicrosoftTeams
Cmdlet          Disconnect-MicrosoftTeams                          1.0.21     MicrosoftTeams
Cmdlet          Get-CsPolicyPackage                                1.0.21     MicrosoftTeams
Cmdlet          Get-CsUserPolicyPackage                            1.0.21     MicrosoftTeams
Cmdlet          Get-CsUserPolicyPackageRecommendation              1.0.21     MicrosoftTeams
Cmdlet          Get-Team                                           1.0.21     MicrosoftTeams
Cmdlet          Get-TeamChannel                                    1.0.21     MicrosoftTeams
Cmdlet          Get-TeamHelp                                       1.0.21     MicrosoftTeams
Cmdlet          Get-TeamsApp                                       1.0.21     MicrosoftTeams
Cmdlet          Get-TeamUser                                       1.0.21     MicrosoftTeams
Cmdlet          Grant-CsUserPolicyPackage                          1.0.21     MicrosoftTeams
Cmdlet          New-Team                                           1.0.21     MicrosoftTeams
Cmdlet          New-TeamChannel                                    1.0.21     MicrosoftTeams
Cmdlet          New-TeamsApp                                       1.0.21     MicrosoftTeams
Cmdlet          Remove-Team                                        1.0.21     MicrosoftTeams
Cmdlet          Remove-TeamChannel                                 1.0.21     MicrosoftTeams
Cmdlet          Remove-TeamsApp                                    1.0.21     MicrosoftTeams
Cmdlet          Remove-TeamUser                                    1.0.21     MicrosoftTeams
Cmdlet          Set-Team                                           1.0.21     MicrosoftTeams
Cmdlet          Set-TeamArchivedState                              1.0.21     MicrosoftTeams
Cmdlet          Set-TeamChannel                                    1.0.21     MicrosoftTeams
Cmdlet          Set-TeamsApp                                       1.0.21     MicrosoftTeams

**Comment by get-itips** [comment]
Hello everyone

Exactly, as the article says, the cmdlet is part of the PS INT gallery (beta module).

I can confirm that, installing the 1.0.21 version of the beta module, the cmdlet IS available:

![image](https://user-images.githubusercontent.com/36666927/77761760-499ff580-7017-11ea-9979-e665d1165503.png)

Please also review [this article](https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management)

**Comment by pemile** [comment]
Hi, After installing 1.0.21 AND disconnect / reconnect Add-TeamChannelUser is available.
Thank's a lot

**Comment by get-itips** [comment]
> Hi, After installing 1.0.21 AND disconnect / reconnect Add-TeamChannelUser is available.
> Thank's a lot

Thanks for getting back to give that information!
@yogkumgit please close this one now.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @JLambEJG 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by irideostriches** [comment]
I struggled to get this working. I ended up deleting the module directory for the production version (1.0.7) and installing 1.1.3. 

This is what worked for me:

PS C:\WINDOWS\system32> Install-Module -Name MicrosoftTeams -RequiredVersion 1.1.3-preview -AllowPrerelease -force -Allo
wClobber
PS C:\WINDOWS\system32> Import-Module microsoftteams
PS C:\WINDOWS\system32> get-command -Module microsoftteams

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-CsBatchPolicyAssignmentOperation               1.1.3      microsoftteams
Function        Get-CsGroupPolicyAssignment                        1.1.3      microsoftteams
Function        Get-CsUserPolicyAssignment                         1.1.3      microsoftteams
Function        New-CsBatchPolicyAssignmentOperation               1.1.3      microsoftteams
Function        New-CsGroupPolicyAssignment                        1.1.3      microsoftteams
Function        Remove-CsGroupPolicyAssignment                     1.1.3      microsoftteams
Function        Set-CsGroupPolicyAssignment                        1.1.3      microsoftteams
Cmdlet          Add-TeamChannelUser                                1.1.3      microsoftteams
Cmdlet          Add-TeamsAppInstallation                           1.1.3      microsoftteams
Cmdlet          Add-TeamUser                                       1.1.3      microsoftteams
Cmdlet          Connect-MicrosoftTeams                             1.1.3      microsoftteams
Cmdlet          Disconnect-MicrosoftTeams                          1.1.3      microsoftteams
Cmdlet          Get-CsOnlinePowerShellEndpoint                     1.1.3      microsoftteams
Cmdlet          Get-CsPolicyPackage                                1.1.3      microsoftteams
Cmdlet          Get-CsUserPolicyPackage                            1.1.3      microsoftteams
Cmdlet          Get-CsUserPolicyPackageRecommendation              1.1.3      microsoftteams
Cmdlet          Get-Team                                           1.1.3      microsoftteams
Cmdlet          Get-TeamChannel                                    1.1.3      microsoftteams
Cmdlet          Get-TeamChannelUser                                1.1.3      microsoftteams
Cmdlet          Get-TeamsApp                                       1.1.3      microsoftteams
Cmdlet          Get-TeamsAppInstallation                           1.1.3      microsoftteams
Cmdlet          Get-TeamUser                                       1.1.3      microsoftteams
Cmdlet          Grant-CsUserPolicyPackage                          1.1.3      microsoftteams
Cmdlet          New-CsBatchPolicyPackageAssignmentOperation        1.1.3      microsoftteams
Cmdlet          New-CsOnlineSession                                1.1.3      microsoftteams
Cmdlet          New-Team                                           1.1.3      microsoftteams
Cmdlet          New-TeamChannel                                    1.1.3      microsoftteams
Cmdlet          New-TeamsApp                                       1.1.3      microsoftteams
Cmdlet          Remove-Team                                        1.1.3      microsoftteams
Cmdlet          Remove-TeamChannel                                 1.1.3      microsoftteams
Cmdlet          Remove-TeamChannelUser                             1.1.3      microsoftteams
Cmdlet          Remove-TeamsApp                                    1.1.3      microsoftteams
Cmdlet          Remove-TeamsAppInstallation                        1.1.3      microsoftteams
Cmdlet          Remove-TeamTargetingHierarchy                      1.1.3      microsoftteams
Cmdlet          Remove-TeamUser                                    1.1.3      microsoftteams
Cmdlet          Set-Team                                           1.1.3      microsoftteams
Cmdlet          Set-TeamArchivedState                              1.1.3      microsoftteams
Cmdlet          Set-TeamChannel                                    1.1.3      microsoftteams
Cmdlet          Set-TeamPicture                                    1.1.3      microsoftteams
Cmdlet          Set-TeamsApp                                       1.1.3      microsoftteams
Cmdlet          Set-TeamTargetingHierarchy                         1.1.3      microsoftteams
Cmdlet          Update-TeamsAppInstallation                        1.1.3      microsoftteams

**Comment by oscamdroid** [comment]
In case it helps anyone, I had the same problem and in the end I managed to solve it using the **MaximunVersion** parameter instead of RequiredVersion.

**Comment by mrskaria** [comment]
I updated to the "current" version of the Teams module, however it still does NOT have the Get-TeamChannelUser included:

![image](https://user-images.githubusercontent.com/73359006/97036123-5812a900-1535-11eb-8b98-c7fe5fc1453d.png)

**Comment by get-itips** [comment]
hello @mrskaria you have to be running 1.1.5-preview to have Add-TeamChannelUser
More information https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install
https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes

**Comment by mrskaria** [comment]
Thank you for  your quick response.  I have tried to add that version to my powershell, but it does not like it.
![image](https://user-images.githubusercontent.com/73359006/97045260-72538380-1543-11eb-969d-e3b1ccd802a4.png)

**Comment by get-itips** [comment]
@mrskaria please try using " " double quotes while specifying the version.

**Comment by mrskaria** [comment]
It still does not like the -RequireVersion parameter
![image](https://user-images.githubusercontent.com/73359006/97045891-91064a00-1544-11eb-950f-334d8644d7d6.png)

**Comment by get-itips** [comment]
@mrskaria Did you update PowerShellGet as the article I referenced says?

**Comment by mrskaria** [comment]
It allowed me to run the module install specifying the older version, however after disconnecting and reconnecting, it still still shows I am running v1.1.6.  Ugh!

**Comment by get-itips** [comment]
> It allowed me to run the module install specifying the older version, however after disconnecting and reconnecting, it still still shows I am running v1.1.6. Ugh!

Michelle, as the documentation says, you can only run one version of the module, so if you need to test the Preview version you would need to uninstall the 1.1.6 first.

> For the best experience, use either General Availability (GA) or Public Preview modules - not both. They're not intended to work together.

Hope this gets you in the right direction.

**Comment by suoko** [comment]
Is PSGallery repo enough to enable this commandlet ?
I really need to add users to channels, can anyone write detailed instructions on how to proceed ?
Thanks

**Comment by phild2015** [comment]
Same issue, I accidentally removed myself as owner of a private channel in Teams and could not add myself back.  Here is what worked for me:

Deleted the current module for Teams (I had 1.1.6 installed) at C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams

Installed version 1.1.3 with PS C:\WINDOWS\system32> Install-Module -Name MicrosoftTeams -RequiredVersion 1.1.3-preview -AllowPrerelease -force -Allo
wClobber

then imported the module

PS C:\WINDOWS\system32> Import-Module -Name MicrosoftTeams

then connected to Teams 

PS C:\WINDOWS\system32> Connect-MicrosoftTeams

made sure the command was there with

PS C:\WINDOWS\system32> Get-Command

![image](https://user-images.githubusercontent.com/15115268/98144836-92b30480-1e98-11eb-9f31-3f1812c19526.png)

Then added myself to the channel first so I would be a member, then upgraded role to owner.  Worked great, thank you!

**Comment by suoko** [comment]
Having Owner as the only role possible is not that practical.
Do we have a solution to add a user as a member ? What about using graph api to do this, would it be possible ?

**Comment by get-itips** [comment]
> Having Owner as the only role possible is not that practical.
> Do we have a solution to add a user as a member ? What about using graph api to do this, would it be possible ?

If you do not specify -Role parameter, it will be added as regular user.

**Comment by suoko** [comment]
> If you do not specify -Role parameter, it will be added as regular user.

Unfortunately no, it's not added at all.
I also noted another problem (minor in this case) with Public teams. You can't add a user to a channel if the user is not a member, I should add it as member first.

**Comment by get-itips** [comment]
> > If you do not specify -Role parameter, it will be added as regular user.
> 
> Unfortunately no, it's not added at all.
> I also noted another problem (minor in this case) with Public teams. You can't add a user to a channel if the user is not a Teams group member, I should add it as member first.

Sorry, I misread your original inquiry, as the cmdlet is still part of the **public preview**, it is subject to changes and testing, so in this case I would recommend to wait for the command to be available in the GA version of the module for the final version of it and also if you want to suggest changes to the cmdlet I would suggest [uservoice](https://microsoftteams.uservoice.com/), that way, it can reach the product team. Thank you!
