### ISSUE TITLE
New-HostedConnectionFilterPolicy

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/office-docs-powershell#5142]
Why is there no documentation for New-HostedConnectionFilterPolicy?

Get-Help New-HostedConnectionFilterPolicy returns minimal information (Name and Syntax info but nothing more)
Get-Command New-HostedConnectionFilterPolicy -Syntax returns expected output
Get-Help New-HostedConnectionFilterPolicy  -Online throws an error

Is this cmdlet supposed to still be supported/available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586e8b44-035e-adae-2847-b5288bc6898d
* Version Independent ID: 03dda286-85d7-41ca-a6dd-f88ef8d89dc6
* Content: [Set-HostedConnectionFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/set-hostedconnectionfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedConnectionFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedConnectionFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
It's my understanding that you should only modify and use the default connection filter policy named Default, so (in theory) only Get-HostedConnectionFilterPolicy and Set-HostedConnectionFilterPolicy are meant to be used. Under that model, New-HostedConnectionFilterPolicy and Remove-HostedConnectionFilterPolicy aren't necessary.

**Comment by mrkeiths** [comment]
@chrisda: I completely agree.  Only the Get/Set cmdlets are needed for maintaining the Default policy if new filter policies are no longer supported.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and sharing this explanation. @mrkeiths 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
