### ISSUE TITLE
"Files cannot be loaded because running scripts is disabled on this system. Provide a valid certificate with which to sign the files." error

### ISSUE THREAD

**Issue by RamkarUmmo** [MicrosoftDocs/office-docs-powershell#5143]
I solved the issue by:
1) Changing directly ExecutionPolicy value to "Bypass" under 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell"
2) Assigning Full Access permissions to the running account over the key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell" by right-clicking it and selecting Permissions

In case of having to run PowerShell under another account (i.e. a service account) and receive "Set-ExecutionPolicy : Access to the registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell' is denied. To change the execution policy for the default (LocalMachine) scope, start Windows PowerShell with the "Run as 
administrator" option. To change the execution policy for the current user, run "Set-ExecutionPolicy -Scope CurrentUser"" error, I just ran this last step (as suggested in the error message itself):

3) Set-ExecutionPolicy -ExecutionPolicy unrestricted -Scope CurrentUser
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5aa434-8ccb-43a3-3f3b-f400e4663b2f
* Version Independent ID: 8a7187a1-fe53-6bf0-b517-6225c8cb3233
* Content: [Connect to Exchange Online Protection PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-eop/connect-to-exchange-online-protection-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-eop/connect-to-exchange-online-protection-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-eop/connect-to-exchange-online-protection-powershell.md)
* Service: **eop**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@RamkarUmmo, so are you saying that the steps already described in the topic didn't work for you? Bypass seems like a really bad security risk; worse than Unrestricted, if that's even possible.

  - Windows PowerShell needs to be configured to run scripts, and by default, it isn't. You'll get the following error when you try to connect:

    > Files cannot be loaded because running scripts is disabled on this system. Provide a valid certificate with which to sign the files.

    To require all scripts that you download from the internet are signed by a trusted publisher, run the following command in an elevated Windows PowerShell window (a Windows PowerShell window you open by selecting **Run as administrator**):

    ```PowerShell
    Set-ExecutionPolicy RemoteSigned
    ```

    You need to configure this setting only once on your computer, not every time you connect.

**Comment by RamkarUmmo** [comment]
That is correct, running Set-ExecutionPolicy RemoteSignedit did not work
for me even in elevated mode. That is why I focused on the registry
permissions. If you prefer to set any other suitable execution policy
setting then you can do it.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and sharing this explanation. @RamkarUmmo 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
