### ISSUE TITLE
only fetches 100 members

### ISSUE THREAD

**Issue by Anvariel** [MicrosoftDocs/office-docs-powershell#5144]
Seems to only fetch 100 members from private channel.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec48e6b6-c93b-a0f1-0144-978ea434b3f0
* Version Independent ID: 28ecb86c-661d-c0ee-6b2c-956c97d02352
* Content: [Get-TeamChannelUser (teams)](https://docs.microsoft.com/en-au/powershell/module/teams/get-teamchanneluser?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Get-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Anvariel 
How are you?

The cmdlet is still part of the beta module so it is under development and subject to changes.
Once it becomes part of the stable module, we can verify if a note stating that in documentation is needed.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Anvariel 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
