### ISSUE TITLE
Example 4 not working

### ISSUE THREAD

**Issue by lordmafi** [MicrosoftDocs/office-docs-powershell#5150]
Hi all,

trying Example 4 is bringing following error:
PS C:\Users\...&gt; $test = New-CsEdgeDomainPattern -Domain "test.com"
PS C:\Users\...&gt; Set-CsTenantFederationConfiguration -AllowedDomains @{Add=$test}
Cannot bind parameter 'AllowedDomains'. Cannot convert the "System.Collections.Hashtable" value of type
"System.Collections.Hashtable" to type "Microsoft.Rtc.Management.WritableConfig.Settings.Edge.IAllowedDomainsChoice".
    + CategoryInfo          : InvalidArgument: (:) [Set-CsTenantFederationConfiguration], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Rtc.Management.Internal.SetTenantFederationConf
   igurationCmdlet
    + PSComputerName        : admin2a.online.lync.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c71fa24-f273-98ff-c0c6-ce9e5488e7c2
* Version Independent ID: 1ef8e42a-4405-5e99-b2ac-547d60b53a70
* Content: [Set-CsTenantFederationConfiguration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by lordmafi** [comment]
It has to be -AllowedDomainsAsAList @{Add=xxx} then it is working

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@lordmafi Martin how are you?

Exactly, Example 4 details how to specify Blocked Domains, not _AllowedDomains_, as you later said, you can use _AllowedDomainsAsAList_ or you can use _New-CsEdgeAllowList_ to create an object acceptable for the _AllowedDomains_ parameter.


Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @lordmafi 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
