### ISSUE TITLE
Add Note on how to import SPO module into regular powershell

### ISSUE THREAD

**Issue by kzu** [MicrosoftDocs/office-docs-powershell#5151]
There is a missing step for those installing the SPO module directly from PowerShell. You need to run the following before issuing SPO commands:

```
Import-Module Microsoft.Online.SharePoint.Powershell
```

There doesn't seem to be any reason to use the "sharepoint shell" other than that line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b23d72-33ed-a6a1-a442-a5e5cf039f9f
* Version Independent ID: 4247cf37-3667-2007-7251-46ed80f58ef5
* Content: [Get started with the SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
With modern versions of PoSh, this isn't necessary given the module is in the default paths (user or machine).

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @kzu Daniel how are you ? 👍 
As @tseward Trevor said, it is not necessary anymore to import the module. 
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @kzu 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
