### ISSUE TITLE
Set SharePoint profile properties groups "c:0t.c|tenant|<group id>"

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#5153]
I was wondering if there is a way to set the "About me" of mail-enabled security groups in the user information list as well? When I view one of the MESG, used for granting access to a site, I can see the blank "About me" info property. When I try to edit the properties for any group "c:0t.c|tenant|&lt;group id&gt;", the "about me" property is not shown on the EditForm.
Or at least to inherit these information from Azure AD / AD?

Final target is to add a description to the MESG name, which follows a name schema which is recognizable for IT staff. However, it is not user-friendly for end users.
Also open for any other idea :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f14cc56-c5e8-3d16-71fd-3742a355aff1
* Version Independent ID: 8f22f503-b757-9446-f50a-3506ba59fe93
* Content: [Set-PnPUserProfileProperty (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpuserprofileproperty?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPUserProfileProperty.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPUserProfileProperty.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Markus-Hanisch  👍 
how are you? 
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Markus-Hanisch Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
