### ISSUE TITLE
Example 7 is just wrong...

### ISSUE THREAD

**Issue by serafing** [MicrosoftDocs/office-docs-powershell#5155]
This whole example should be modified to be simpler because it does not work.

Here is where things start to break down:
Add-DistributionGroupMember -Identity $group -Members $members -BypassSecurityGroupManagerCheck:$true
There is no -Members in Add-DistributionGroupMember.  There is -Member, but it only allows individual items and does not seem to allow arrays.

Cannot process argument transformation on parameter 'Member'. Cannot convert the "System.Collections.ArrayList" value
of type "System.Collections.ArrayList" to type "Microsoft.Exchange.Configuration.Tasks.RecipientWithAdUserGroupIdParame
ter`1[Microsoft.Exchange.Configuration.Tasks.RecipientIdParameter]".
    + CategoryInfo          : InvalidData: (:) [Add-DistributionGroupMember], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Add-DistributionGroupMember
    + PSComputerName        : outlook.office365.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a9c45b-34dd-c1c8-89f0-84f3d968eac4
* Version Independent ID: ec9c910c-25f2-f36a-8f75-ce052f0e8be6
* Content: [Set-CalendarProcessing (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-calendarprocessing?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #5169 Thanks

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @serafing Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
