### ISSUE TITLE
Is there any way to check to see if this has been enabled rather than just run the command and wait for it to error 

### ISSUE THREAD

**Issue by swinster** [MicrosoftDocs/office-docs-powershell#5158]
I suppose something like 

```
Enable-OrganizationCustomization -ErrorAction SilentlyContinue
```

Would swallow the error, but wondered it there was something more elegent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50344cac-af28-c270-ea24-f7c698aee084
* Version Independent ID: 1023728c-6ba1-893a-6cac-a32bccf09ec0
* Content: [Enable-OrganizationCustomization (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/enable-organizationcustomization?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/organization/Enable-OrganizationCustomization.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/Enable-OrganizationCustomization.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
The IsDehydrated property from Get-OrganizationConfig tells the story: False ($false) = the command has already been run; True ($true) = the command has never been run.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and sharing this explanation. @swinster 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by swinster** [comment]
Perfect, thanks @chrisda - just what i was looking for :)

**Comment by chrisda** [comment]
@swinster, I didn't add an example, but I added the information to the Description Section.
