### ISSUE TITLE
404 on link to the module

### ISSUE THREAD

**Issue by FSGHWA** [MicrosoftDocs/office-docs-powershell#5159]
The link where it says "**Module: exchange**" seems to be a dead link pointing to [https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailbox?view=exchange-ps](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailbox?view=exchange-ps). This should be corrected.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @FSGHWA, thank you for your feedback.

An internal ‘work item’ is open so we are working on it. Hope it's fixed soon.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @FSGHWA 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dariomws** [comment]
The Exchange module link issue was fixed this week. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
