### ISSUE TITLE
New-CSONLINESESSION is not documented anywhere

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/office-docs-powershell#5160]
Specifically looking for proxy connection options. In any case, there does not seem to be any documentation regarding New-CSONLINESESSION

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @vboyev-MSFT 
Thanks for reporting.
I created a PR including the article documentation, a review will be made, if accepted, it will be published online.
Thank you

**Comment by kenwith** [comment]
@yogkumgit - I merged the associated PR a few days ago. :)   Let me know if there is something else you needed with assigning me this one.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @vboyev-MSFT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
