### ISSUE TITLE
Get-Team requires an input param or it never returns / hangs

### ISSUE THREAD

**Issue by alohaninja** [MicrosoftDocs/office-docs-powershell#5161]
Imagine lots of people will struggle with this command. For Teams tenants with large domains - we should callout a note that you need to specify an input parameter or `Get-Team` command will run forever.  

Having never used this cmdlet - I assumed it would default to the logged in user for filtering. `Get-Team` would only return results if I passed in my user e.g. `Get-Team -user me@domain.com`.  This would have saved me 20 minutes. 😬

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8450991f-9f85-4d87-51b3-efa8e1004a24
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/Get-Team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @alohaninja Aaron 👍 
How are you ? The article already states that:

> Note: depending on the number of teams and O365 Groups in your organization and which filters you are using, this cmdlet can take upwards of ten minutes to run.

And also, the two examples given use parameters to shorten the number of results.

**Comment by alohaninja** [comment]
@get-itips - this was great info, just needs emphasis added to keep consistent with other docs pages - I  missed this note entirely because it doesn't look like a note!

https://github.com/MicrosoftDocs/office-docs-powershell/pull/5175

**Comment by get-itips** [comment]
@alohaninja Aaron, it is great that you are proposing thru a PR to change it to a formal note, that's the power of open sourced documentation.
Thanks for getting back to give feedback.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and @alohaninja updating the documentation with PR. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
