### ISSUE TITLE
Get-EXOMailbox help examples wrong

### ISSUE THREAD

**Issue by geddyleefan** [MicrosoftDocs/office-docs-powershell#5162]
Getting help for Get-EXOMailbox returns examples using get-mailbox.

-------------------------- Example 1 --------------------------

    Get-Mailbox -ResultSize unlimited

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @geddyleefan, thank you for your feedback.

Please refer to the online help:
https://docs.microsoft.com/powershell/module/exchange/powershell-v2-module/get-exomailbox

Get-Help information for this cmdlet will be updated soon.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @geddyleefan 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
