### ISSUE TITLE
QueryWindowInDays parameter appears to be mandatory

### ISSUE THREAD

**Issue by FoxMic0** [MicrosoftDocs/office-docs-powershell#5163]
The article text states:
If you don't use this parameter, all future meetings on or after the specified start date will be cancelled.

But if you do not specify the parameter (as in Example 1), you are prompted to provide a value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae873e5c-9f55-966b-1519-04bd3cb7dce4
* Version Independent ID: 8f35c374-2608-6414-5987-cbedd7b46cf0
* Content: [Remove-CalendarEvents (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/remove-calendarevents?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Remove-CalendarEvents.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Remove-CalendarEvents.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #5173 Thanks

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @FoxMic0  hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
