### ISSUE TITLE
How to set Organisation default Rule with PowerShell?

### ISSUE THREAD

**Issue by aavdberg** [MicrosoftDocs/office-docs-powershell#5164]
Can only set User policies with powershell, and can't set Organisation default policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 923dc552-f943-e043-165d-9ed5fb734c6c
* Version Independent ID: fe62e834-2cb1-0a15-0d93-14194ca0e33a
* Content: [Set-SafeLinksPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-safelinkspolicy?view=exchange-ps&source=docs#feedback)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/Set-SafeLinksPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/Set-SafeLinksPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @aavdberg, thank you for your feedback.

I think this is what you are looking for:
https://docs.microsoft.com/powershell/module/exchange/advanced-threat-protection/set-atppolicyforo365

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @aavdberg 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
