### ISSUE TITLE
PromoteAs Values are wrong

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#5165]
These are the correct possible values
None, HomePage, NewsArticle, Template

It currently shows HomePage, NewsPage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9cbd838-1888-5be7-348b-c8862d7caedb
* Version Independent ID: 80961074-993c-c395-64d2-2b18bd048e31
* Content: [Set-PnPClientSidePage (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpclientsidepage?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPClientSidePage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPClientSidePage.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @danmyhre Dan 👍
how are you?
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.
Thanks

**Comment by danmyhre** [comment]
This issue was about the documentation, not the cmdlets

**Comment by get-itips** [comment]
> This issue was about the documentation, not the cmdlets

Dan, The documentation of PnP cmdlets is on every cmdlet's source code and it is directly reflected from there.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @danmyhre 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by danmyhre** [comment]
I created a pull request for the doc update I am referring to
https://github.com/MicrosoftDocs/office-docs-powershell/pull/5204

**Comment by get-itips** [comment]
Dan, as said, the documentation for PnP is inside the PnP source code, so you have to target a pull request against this file on the referenced repo
 https://github.com/pnp/PnP-PowerShell/blob/dev/Commands/ClientSidePages/SetClientSidePage.cs

Thanks for your contribution

**Comment by danmyhre** [comment]
I think I found what you are referring to:
https://github.com/pnp/PnP-PowerShell/pull/2599

The page doc had its own editable source, so I didn't realize it was automatically generated.

**Comment by get-itips** [comment]
> I think I found what you are referring to:
> [pnp/PnP-PowerShell#2599](https://github.com/pnp/PnP-PowerShell/pull/2599)
> 
> The page doc had its own editable source, so I didn't realize it was automatically generated.

Exactly, it is automatically generated from the cmdlet's source code, so, if you create a PR against the markdown file, and someone merges it, it will be overwritten anyway.
Thank you for your contribution!
