### ISSUE TITLE
Preview or not?

### ISSUE THREAD

**Issue by Bart-Hoofd** [MicrosoftDocs/office-docs-powershell#5167]
This command is included in the 1.0.5 general no-preview version of the Microsoft Teams; confusing, since it is now labeled as public preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d149ca60-bfb7-5077-2643-1a08ad926cca
* Version Independent ID: 24754aee-bff2-fa16-e7e6-af45362fd916
* Content: [New-CsBatchPolicyAssignmentOperation (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csbatchpolicyassignmentoperation?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Bart-Hoofd thanks, I will take a look at this.

**Comment by get-itips** [comment]
Hello @Bart-Hoofd 
I could get some confirmation, although the cmdlet is included now in the stable version of the module, the product team confirmed that it is still in _preview_ so we will maintain the note at the top of the article, at least, for now.
Hope this information helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Bart-Hoofd 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
