### ISSUE TITLE
Limits ? 

### ISSUE THREAD

**Issue by Chewbee** [MicrosoftDocs/office-docs-powershell#5168]
I have a script which add users
I have 35 users and only 27 are added 
If I rerun of course some of them already exists ... 
But the the are never added ... 

Any clues welcome, here is the script

Try {
    Import-Csv -Path "EYTC.csv" | foreach {
        Add-TeamUser -GroupId 3337d494-dde7-4496-ba18-1bc392203ef7 -user $_.Name
        Write-Output $_.Name
    }
}
#
Catch {}
#
Finally {
    Get-TeamUSer -GroupId 3337d494-dde7-4496-ba18-1bc392203ef7
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da0c53f2-1c62-14f6-6371-f54bf86b0c24
* Version Independent ID: aac162db-a9c0-fbfb-dd40-526e94d3bef8
* Content: [Add-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamuser?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Add-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Chewbee how are you? 👍 

Here, we can handle issues that impact changes in documentation.
If the cmdlet, ran outside your script, works as the documentation says, I can not identify any change needed to the documentation.
Did you try running the Add-TeamUser individually for those users that you see aren't being added?

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Chewbee 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
