### ISSUE TITLE
Names of Cmdlets (PnP) should not be translated

### ISSUE THREAD

**Issue by dinoinyourhead** [MicrosoftDocs/office-docs-powershell#5170]
I'm sorry if this isn't the correct place to comment on the automatic article translation.

The issue is that names of certain cmdlets get automatically translated, tested for German language. 

Examples:

Set-PnPSite for German -> Gruppe-PnPSite
Set-PnPTaxonomyFieldValue -> Gruppe-PnPTaxonomyFieldValue

![image](https://user-images.githubusercontent.com/62758238/77770460-94d0fd00-7045-11ea-9a4b-6f8d4a4835a6.png)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks @dinoinyourhead I reported this and should be fixed shortly.

**Comment by yogkumgit** [comment]
@OfficeGlobal could you kindly help with this translation issue? Thanks!

**Comment by yogkumgit** [comment]
@OfficeGlobal any update please.

**Comment by OfficeGlobal** [comment]
@yogkumgit working on fix, ETA 4/22/2020

**Comment by get-itips** [comment]
> @yogkumgit working on fix, ETA 4/22/2020

Thanks for the update.

**Comment by dinoinyourhead** [comment]
> @yogkumgit working on fix, ETA 4/22/2020
one small remark: this seems to be a "general" problem. By chance I also noticed the translation problems on Exchange PowerShell Docs
https://docs.microsoft.com/de-de/powershell/module/exchange/mailbox-databases-and-servers/set-mailboxserver?view=exchange-ps

![image](https://user-images.githubusercontent.com/62758238/79867482-b2904880-83de-11ea-8e82-719243879e6c.png)

**Comment by yogkumgit** [comment]
@dinoinyourhead Noted. Will share your remark with team. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
