### ISSUE TITLE
Example will fail on the OnPremPhoneNumber format

### ISSUE THREAD

**Issue by wiseleaf23** [MicrosoftDocs/office-docs-powershell#5171]
If we use the number format in the example stated on this page "Set-CsOnlineApplicationInstance -Identity appinstance01@contoso.com -OnpremPhoneNumber tel:+14250000000 -ApplicationId ce933385-9390-45d1-9512-c8d228074e07 -DisplayName "AppInstance01"" - We will get an error stating:

The input of parameter "tel:+31851324567" is not in a valid format. Please provide an input with an acceptable format &lt;tel:&gt;+[number]", e.g. tel:+18005551234 or +14251234567.

The only format that works with this parameter is just +31851324567, without the "tel:" prefix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08e7ee82-a4a2-0138-ffcc-a0746a1ee7c0
* Version Independent ID: 5cf5edef-643f-10a1-8247-4e14d06ff675
* Content: [Set-CsOnlineApplicationInstance (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlineapplicationinstance?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @wiseleaf23 👍 how are you?
Thanks for reporting. I could verify, so I created a pull request to correct the format in the documentation. Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @wiseleaf23 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by pc222** [comment]
I think the error in the cmdlet is back. I tried it with our without "tel:" but I get always the message that the format is wrong.

`Set-CsOnlineApplicationInstance -Identity "srv_test_byot_cq_02@tenant.onmicrosoft.com" -OnpremPhoneNumber "tel:+‪49123456789" -Verbose -ApplicationId "11cd3e2e-fccb-42ad-ad00-878b93575e07"`

or

`Set-CsOnlineApplicationInstance -Identity "srv_test_byot_cq_02@tenant.onmicrosoft.com" -OnpremPhoneNumber "+‪49123456789" -Verbose -ApplicationId "11cd3e2e-fccb-42ad-ad00-878b93575e07"`

**Comment by wiseleaf23** [comment]
@pc222 Could you try without the quotes around the phone number? I know it should not matter, but you can try. Also, you can try using the number in my example, +31851324567

**Comment by get-itips** [comment]
> I think the error in the cmdlet is back. I tried it with our without "tel:" but I get always the message that the format is wrong.
> 
> `Set-CsOnlineApplicationInstance -Identity "srv_test_byot_cq_02@tenant.onmicrosoft.com" -OnpremPhoneNumber "tel:+‪49123456789" -Verbose -ApplicationId "11cd3e2e-fccb-42ad-ad00-878b93575e07"`
> 
> or
> 
> `Set-CsOnlineApplicationInstance -Identity "srv_test_byot_cq_02@tenant.onmicrosoft.com" -OnpremPhoneNumber "+‪49123456789" -Verbose -ApplicationId "11cd3e2e-fccb-42ad-ad00-878b93575e07"`

Hello, tested this again, and it worked with or without the quotes around the OnPremPhoneNumber parameter. Hope this info helps you

**Comment by pc222** [comment]
We still have the issue. We're opened a primer support ticket, but still no solution for more than 3 weeks.
