### ISSUE TITLE
-DisplayName just fails !! 

### ISSUE THREAD

**Issue by Chewbee** [MicrosoftDocs/office-docs-powershell#5172]
I cannot say any better the doc is not correct 
Here is the proof:

PS Microsoft.PowerShell.Core\FileSystem::\\Mac\Home\dev\PS&gt; Get-Team -DisplayName Customer
Get-Team : Impossible de trouver un paramètre correspondant au nom « DisplayName ».
Au caractère Ligne:1 : 10
+ Get-Team -DisplayName Customer
+          ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (:) [Get-Team], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8450991f-9f85-4d87-51b3-efa8e1004a24
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by Rutger-Knijnenburg** [comment]
Have you tried putting the parameter (Customer) in "" double quotes? Works for me perfectly:
Get-Team -DisplayName "NameofTeam"

**Comment by get-itips** [comment]
Hello @Chewbee thanks for your report, I am proposing adding another example to the documentation that specifies using "" as @Rutger-Knijnenburg kindly says.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Chewbee Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
