### ISSUE TITLE
MFA supporting "Security & Compliance Center" module

### ISSUE THREAD

**Issue by dsolodow** [MicrosoftDocs/office-docs-powershell#5176]
Currently the only way to connect to Security & Compliance Center via PowerShell without Legacy Authentication is to install the click-to-run shell from the Exchange Admin Center.
This limits support to Windows PowerShell only, as well as making it hard to integrate with other scripts.

Would be ideal if there was an appropriate module in the Gallery (perhaps the ExchangeOnlineManagement module)?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @dsolodow, thank you for your feedback.

This is the official way to connect using MFA yet. I think that it will be moving in the same way of Exchange to Exchange Online PowerShell V2 in the next couple of months:
https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2

**Comment by dsolodow** [comment]
I was guessing it was on the roadmap, but wanted to poke people about it. :)

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @dsolodow 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
