### ISSUE TITLE
-Identity is not documented

### ISSUE THREAD

**Issue by Agazoth** [MicrosoftDocs/office-docs-powershell#5177]
When running Connect-MicrosoftTeams the -Identity switch is available. This is not documented here. It is not documented in the help in the cmdlet either. But tab-completion reveals it and running the cmdlet with that parameter seems to kinda work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ee082c9-735d-3f8a-7bc4-b2d4f175c784
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Agazoth Axel, thanks for reporting, I will dig into this and get back.

**Comment by tameemansari** [comment]
Thanks for reporting @Agazoth. The connect cmdlet has some issues with the -Identity parameter. This is supposed to allow users to use an Azure Managed Identity to execute subsequently. I am surprised that it worked for you. Can you share details on how you configured your managed identity. 

We should be fixing these issues in the command cmdlet in future releases when the documentation will also be fixed. cc @brandber

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Agazoth 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
