### ISSUE TITLE
EXAMPLE 6 uses "PersistComposedLookFiles" switch not documented in the Cmdlet Syntax

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#5178]
EXAMPLE 6 uses "PersistComposedLookFiles" switch not documented in the Cmdlet Syntax.
The Cmdlet syntax refers to "PersistBrandingFiles" switch. 
Please check.
------------------EXAMPLE 6------------------
Get-PnPProvisioningTemplate -Out template.pnp -PersistComposedLookFiles

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 451dc826-b072-5bcd-e98d-319ee82d73fe
* Version Independent ID: c0c6ad38-e86c-cd0c-ac01-033791404e25
* Content: [Get-PnPProvisioningTemplate (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps#syntax)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPProvisioningTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPProvisioningTemplate.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Markus-Hanisch Markus 👍 

how are you?

The documentation for PnP cmdlets is directly reflected from the cmdlet's source code, that lives in the linked repository.
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.


Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Markus-Hanisch Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
