### ISSUE TITLE
Set-Place projector and display attribute and ability to overwrite once set attributes.

### ISSUE THREAD

**Issue by Jachim208** [MicrosoftDocs/office-docs-powershell#5179]
Hello,

- I think, that -DisplayDeviceName should be split in to display (such as tv), and projector. Many conference rooms contain both of them.
- I'm in need of overwrite option in Set-Place, once I assigned attributes to the conference room, I can't overwrite them with different one. Is it not implemented, or am I missing something?

Thanks

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @Jachim208, thank you for your feedback.

- For feature request please go to:
https://office365.uservoice.com/

- You should be able to update/overwrite attributes using this cmdlet. Please, show us a screenshot if you experience issues doing that.

**Comment by Jachim208** [comment]
Hi @dariomws 
Thank you for your reply.
I think it might have been false alarm. I'm sorry for that.
It took a few days, but new attributes are visible. Is such delay normal?

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @Jachim208 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dariomws** [comment]
@Jachim208, it should take just a couple of minutes, a few days it's not normal.

**Comment by Jachim208** [comment]
@dariomws 
To be honest, it doesn't throw any erros. just executes. But now I have tested it, and it actually takes more than 4 days to update. Though I'm checking it in Outlook Online, not directly on the rooms attributes, so maybe this is the reason.
After all, it seems to work, and replaces previous attributes, so I think we can close the issue.
Tjank you for your help :)
