### ISSUE TITLE
WhatIf parameter does not work for this cmdlet

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#5180]
-WhatIf parameter is ignored by this cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe400cff-c226-6a30-50bc-43f3a44e7eca
* Version Independent ID: fee47d08-63ff-edfe-e845-c8928f5d2acd
* Content: [Set-CsOnlineVoiceUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineVoiceUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineVoiceUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by shivtorov** [comment]
example code to reproduce the issue:
`Set-CsOnlineVoiceUser -Identity user@contoso.com -TelephoneNumber 123456789 -WhatIf`

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @shivtorov thanks for reporting, created a pull request to describe this.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @shivtorov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
