### ISSUE TITLE
Set-CsOnlineVoiceUserBulk not documented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#5181]
The help article for Set-CsOnlineVoiceUserBulk is empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d833f2e0-13f3-9855-6bbe-05c02223d216
* Version Independent ID: 750b544e-66ca-3a01-0a88-77ad880e51b7
* Content: [Set-CsOnlineVoiceUserBulk (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceuserbulk?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineVoiceUserBulk.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineVoiceUserBulk.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@tomkau Tom, can we get more specifics about this cmdlet ? is this cmdlet being retired soon? Thanks

**Comment by tomkau** [comment]
I passed this along to the team that owns the cmdlet

**Comment by tomkau** [comment]
Confirmed that this cmdlet is deprecated and will be removed from the module.

**Comment by get-itips** [comment]
> Confirmed that this cmdlet is deprecated and will be removed from the module.

Thanks @tomkau !

**Comment by yogkumgit** [comment]
@kenwith Please merge this PR #5450 . Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @shivtorov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
