### ISSUE TITLE
PowerShell/GraphAPI: Get all linked SharePoint Libraries (via Add Cloud Storage) in MS Teams

### ISSUE THREAD

**Issue by Oweeboi011** [MicrosoftDocs/office-docs-powershell#5190]
Is there a way to get all "linked SharePoint Libraries" in a Team via powershell? 

We are curretly using **https://graph.microsoft.com/beta/groups/$groupid/drives/root/children** and **https://graph.microsoft.com/beta/groups/$groupid/drives/** but these endpoints only pull out the libraries from the current team. Please advise if I'm missing something here. Thanks in advance.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Oweeboi011 Owee how are you ? 👍 

The issue section of this repo is intended to address issues currently in documentation, for example typos or missing information.
Is there any specific article that you feel needs to be corrected?
It seems that your inquiry would be more suitable for resources like 
https://techcommunity.microsoft.com/
Hope this information helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Oweeboi011 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
