### ISSUE TITLE
Parameters - Permitted Values

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/office-docs-powershell#520]
I think it would be very useful if the permitted values for each parameter were listed and what they did.  eg -Handlers a permitted value is PageHandler

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 451dc826-b072-5bcd-e98d-319ee82d73fe
* Version Independent ID: c0c6ad38-e86c-cd0c-ac01-033791404e25
* Content: [Get-PnPProvisioningTemplate (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPProvisioningTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPProvisioningTemplate.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen for your review.

**Comment by erwinvanhunen** [comment]
We'll consider adding this. In the meantime, the handlers parameter is an enum, this means that you can use PowerShell completion (tab) to loop through the possible handlers. It's on our backlog to create up to date documentation for the Provisioning Engine in general.

**Comment by VesaJuvonen** [comment]
Closing based on comment from @erwinvanhunen.
