### ISSUE TITLE
URL https://go.microsoft.com/fwlink/p/?LinkId=251832 links to Microsoft home page, not documentation

### ISSUE THREAD

**Issue by ChrisParrBIE** [MicrosoftDocs/office-docs-powershell#5201]
The url linked as the location of the admin documentation throughout this set of pages links to the Microsoft home page. I end up at https://www.microsoft.com/en-gb/?ref=go rather than at any documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fbda735-74ec-2f4e-9c75-dd133e87320e
* Version Independent ID: 599c8c2e-6e02-f27f-1009-2640296d5d10
* Content: [Get-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Get-SPOSite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks @ChrisParrBIE created a pr.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution. @ChrisParrBIE Thanks for updating the documentation with PR. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mindbeander** [comment]
[https://github.com/MicrosoftDocs/office-docs-powershell/issues/5201#issuecomment-608394588](https://github.com/MicrosoftDocs/office-docs-powershell/issues/5201#issue-591716775) 
Duplicate of #
