### ISSUE TITLE
Some parameters are ExO-only

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/office-docs-powershell#5203]
Parameters like CompleteAfter or StartAfter are not visible in OnPrem! Please modify the documentation accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf2e681a-0bba-7d71-e367-44266ea40a4a
* Version Independent ID: 8fbe3c52-c74a-1e09-1318-177643594bd0
* Content: [New-MigrationBatch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/new-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please mere the PR #5221 Thanks

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @trudolf-msft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
