### ISSUE TITLE
From vs RURI/To , it is not clear

### ISSUE THREAD

**Issue by antman2001** [MicrosoftDocs/office-docs-powershell#5205]
hi, can you please make this doc more clear as to which parameters effect the actual SIP headers: RURI/To and From. Also please an example where only the From is translated and one where only the RURI/To is translated, not only all(RURI/To,From) in same examples please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d742b37-0207-ed28-504e-819ced1fe237
* Version Independent ID: 998f5d3c-61c5-d9b5-ee80-6e041df602cd
* Content: [New-CsTeamsTranslationRule (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamstranslationrule?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsTranslationRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsTranslationRule.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @filippse
* Microsoft Alias: **filippse**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @antman2001, thank you for your feedback.

In the following article you can find some information and examples:
https://docs.microsoft.com/en-us/microsoftteams/direct-routing-translate-numbers

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @antman2001 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
