### ISSUE TITLE
The Value for the Parameter OnlinePstnGatewayList does not accept here string or "OnlinePstnGateway:"

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#5206]
Tried this just now and it doesn't like the notation as outlined in Example 2:
New-CsOnlineVoiceRoute -Identity Route1 -OnlinePstnUsages @{add="Long Distance"} -OnlinePstnGatewayList @{add="OnlinePstnGateway:sbc1.litwareinc.com"}

Working command:
New-CsOnlineVoiceRoute -Identity Route1 -OnlinePstnUsages @{add="Long Distance"} -OnlinePstnGatewayList "sbc1.litwareinc.com"

The Parameter OnlinePstnGatewayList seems to not accept the Here-String as well as not needing the "OnlinePstnGateway:" Prefix within the string.

Could you please verify this?
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3b5fc22-f087-e2d9-dfdc-728a68c45d8f
* Version Independent ID: 8061dab3-4913-f920-524b-892ac16e1f64
* Content: [New-CsOnlineVoiceRoute (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinevoiceroute?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineVoiceRoute.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineVoiceRoute.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by DEberhardt** [comment]
Here is the Command and the Output

New-CsOnlineVoiceRoute -Identity "Route-1" -Priority "1" -OnlinePSTNGatewayList @{add="OnlinePstnGateway:Gateway1.sbc.domain.com"} -NumberPattern '.*' -Description "Route 1 from Teams via Gateway1";

Cannot create item "Route-1": "Invalid value for TrunkFqdn: Value is not a valid FQDN."
    + CategoryInfo          : InvalidArgument: (Route-1:String) [New-CsOnlineVoiceRoute], PropertyArgumentException
    + FullyQualifiedErrorId : InvalidNew,Microsoft.Rtc.Management.Internal.NewOnlineVoiceRouteCmdlet
    + PSComputerName        : admingb1.online.lync.com

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @DEberhardt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
