### ISSUE TITLE
-Archive parameter throws an error with Exchange Online

### ISSUE THREAD

**Issue by SeaGT** [MicrosoftDocs/office-docs-powershell#5207]
Please provide an example of using -Archive to get info on an In-Place Archive mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560849f0-488f-4ee7-2e91-64ab4598eb70
* Version Independent ID: 8fdde992-e4d8-1238-06ab-eb11857fddaa
* Content: [Export-MailboxDiagnosticLogs (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/export-mailboxdiagnosticlogs?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Export-MailboxDiagnosticLogs.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Export-MailboxDiagnosticLogs.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #5224 Thanks

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @SeaGT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
