### ISSUE TITLE
what gives?

### ISSUE THREAD

**Issue by DanStevensonMSFT** [MicrosoftDocs/office-docs-powershell#5208]
Why would we document a PowerShell cmdlet that is not allowed to be used? Do we hate our admins /that/ much?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8d6f4e-0db4-6038-df71-95d22c3b8e09
* Version Independent ID: 12c6accc-f355-33e0-0479-418e141efb74
* Content: [Set-CsTeamsAppPermissionPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsapppermissionpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsAppPermissionPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsAppPermissionPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @DanStevensonMSFT, thank you for your feedback.

@tomkau @islubin could you kindly help with these cmdlets? Do we have more information about when they will be updated?

**Comment by tomkau** [comment]
@islubin ping

**Comment by yogkumgit** [comment]
@islubin kindly help with these cmdlets query. Thanks

**Comment by kenwith** [comment]
I will pass this information onto the product team and update documentation as necessary.
