### ISSUE TITLE
-Users parameter missing

### ISSUE THREAD

**Issue by MSTejas** [MicrosoftDocs/office-docs-powershell#5209]
-Users switch is missing in the document, which is present when we use this command. May I request document to be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7364cece-00a4-7e29-4fa9-190db5f9e3dd
* Version Independent ID: 67efa086-edb0-2828-cc14-4c245290e4f3
* Content: [Set-CsCallQueue (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cscallqueue?view=skype-ps&source=docs#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @MSTejas Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by MSTejas** [comment]
Great! Thank you so much for updating this, Yogesh.


Regards,
Tejas Haria
