### ISSUE TITLE
Azure PowerShell Function

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/office-docs-powershell#5210]
Hello,
I am following the below articles to create Azure PowerShell function and when I use this command(Set-PnPTraceLog -On -Level Debug) nothing being shown on the screen or in logs.

https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning https://www.youtube.com/watch?v=plS_1BsQAto&t=925s

Is this functionality is still being worked on with Azure Function or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2c4d0f-adfd-cc4b-778f-4e2d2a812058
* Version Independent ID: 9d051428-dc83-8db8-634b-7fa036da3c5d
* Content: [Set-PnPTraceLog (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnptracelog?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPTraceLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPTraceLog.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ravick4u Ravi 👍 
How are you?

The documentation for PnP cmdlets is directly reflected from the cmdlet's source code, that lives in the linked repository.
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.

Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ravick4u 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
