### ISSUE TITLE
All Jobs "NotStarted"

### ISSUE THREAD

**Issue by Cdenby** [MicrosoftDocs/office-docs-powershell#5214]
I've run this a few times and then try to run Get-CsBatchPolicyAssignmentOperation and all job ssit with "NotStarted" as the OverallStatus.

Any hints on that particular message? I didn't receive an error at all:
New-CsBatchPolicyAssignmentOperation -PolicyType TeamsMessagingPolicy -PolicyName Teachers -identity "GUIDofauser"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d149ca60-bfb7-5077-2643-1a08ad926cca
* Version Independent ID: 24754aee-bff2-fa16-e7e6-af45362fd916
* Content: [New-CsBatchPolicyAssignmentOperation (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csbatchpolicyassignmentoperation?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by AdamJParker** [comment]
Having same issue, 2 jobs created more than a week ago, stay as NotStarted. Is there a way to delete or remove them?

**Comment by Cdenby** [comment]
End result here is that they are just incredibly slow.
My first policy assignment batches took 5 hours to complete. A few I started later that day took over 8 hours to complete. At the moment, I have a bunch listed as In Progress and it's been more than 24 hours.
I've not yet seen a week, however.

This borders on just being unusable with this kind of performance.

**Comment by get-itips** [comment]
Hello @Cdenby how are you? 👍 hope you are doing great.
I could get some information from the team, they are aware of this and they are working on it for when the feature comes out of preview. 
I do not identify need to impact documentation for now.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Cdenby 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dinocaputo** [comment]
Are there any kind of metrics on how much faster this operation is vs looping through users one after another?  

I'm also finding that we issue the cmdlet and status stays in "Not Started"

How do we remove or stop these operations?

**Comment by Cdenby** [comment]
I was finding that the "Not Started" was lasting for many hours a few weeks go, but lately, it's been really quick. My last set of 18 policy pushes took about 3 minutes to complete.

**Comment by dinocaputo** [comment]
Mine are running , complete after 1 hour and show all the users as failed.   Not sure why.  Any thoughts?

Sent from my iPhone

On May 9, 2020, at 7:16 PM, Cdenby <notifications@github.com> wrote:

﻿

I was finding that the "Not Started" was lasting for many hours a few weeks go, but lately, it's been really quick. My last set of 18 policy pushes took about 3 minutes to complete.

**Comment by BJGGut3** [comment]
Same issue with 'Not Started' and several 'In Progress'.  Started them 5/7/2020 @ 11:55pm UTC.  Checked 5/8 11am UTC and 8 Completed, 4 In Progress, 10 Not Started.  Here we are on 5/10/2020 @ 7:20pm UTC and there has been no status change since I last checked on 5/8...

**Comment by dinocaputo** [comment]
I have run 4 batches and they are taking anywhere from 40-90 mins per batches of approximately 6000 users.  All end up with ErrorCount = CompletedCount.  How can we get more details as to why they are failing?  I have validated users and they are NOT getting the policy specified.

**Comment by NickBorowitz** [comment]
> I have run 4 batches and they are taking anywhere from 40-90 mins per batches of approximately 6000 users. All end up with ErrorCount = CompletedCount. How can we get more details as to why they are failing? I have validated users and they are NOT getting the policy specified.

I'm having the same problem

**Comment by get-itips** [comment]
Hello everyone.
As already mentioned. We could get information from the team that they are aware of the current behavior of the cmdlet and they are working on it.
Also, even though the cmdlet is in the stable version of the module, **the cmdlet is still in preview**.
Thank you!

**Comment by br1310** [comment]
Hi  Guys,
Anyone is having issue with assignment status completed with error: _"Object is not in   valid state for this operation or there is a delay in propagation."?

I applied to 12000 users but only 50% completed. Rest of them failed with the error.

Thank you
BR

**Comment by dinocaputo** [comment]
Limit your batches to 5000 users.
Everything you are seeing is “expected” right now due to the preview nature of this Cmdlet.  I have similar issues with it.

Sent from my iPhone

On May 16, 2020, at 12:46 PM, br1310 <notifications@github.com> wrote:

﻿

Hi Guys,
Anyone is having issue with assignment status completed with error: _"Object is not in valid state for this operation or there is a delay in propagation."?

I applied to 12000 users but only 50% completed. Rest of them failed with the error.

Thank you
BR

**Comment by br1310** [comment]
Thank you  @dinocaputo 

I limit the batches to 2000 users but still It gives me same error. It seems that status of those users are stored somewhere. Because when I ran second time, it was super quick (task was completed in few seconds)

**Comment by dollar3010** [comment]
Thanks, guy for the info, is it possible to clear all the completed batch, there is a lot of completed job in my batch but I want them to clear?
