### ISSUE TITLE
Get-RetentionCompliancePolicy not available in Azure Automation Runbook

### ISSUE THREAD

**Issue by SleepyBandit** [MicrosoftDocs/office-docs-powershell#5215]
It doesn't seem that the [security and compliance center PowerShell cmdlets](https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell?view=exchange-ps) work in an Azure Automation Runbook. The Runbook jobStream logs that the session is connected and imported but when I call  **Get-RetentionCompliancePolicy** or **Set-RetentionCompliancePolicy** it returns that these cmdlets do not exist.

Below is the Runbook jobStream log
```
Your connection has been redirected to the following URI: 
"https://nam02b.ps.compliance.protection.outlook.com/powershell-liveid?PSVersion=5.1.15063.726"
Get-RetentionCompliancePolicy : The term 'Get-RetentionCompliancePolicy' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.
At line:47 char:1
+ Get-RetentionCompliancePolicy
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-RetentionCompliancePolicy:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Get-Commands does not show either of these listed as available commands. 

When I use the same code but replace the **ConnectionUri** to point to Exchange (https://outlook.office365.com/powershell-liveid/), then it connects similarly but I can call Exchange specific commands like **Get-Mailbox**

Here is the code I've been using for testing. It also works when running locally, just not in Azure Automation.
```
$cred = Get-AutomationPSCredential -Name "Admin"
Import-Module (Import-PSSession $(New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.compliance.protection.outlook.com/powershell-liveid/ -Credential $cred -Authentication Basic -AllowRedirection) -AllowClobber -DisableNameChecking) -Global -DisableNameChecking
Get-RetentionCompliancePolicy
Get-PSSession | Remove-PSSession
```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
@SleepyBandit Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @SleepyBandit 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it.
