### ISSUE TITLE
Missing Type = SharedVoicemail

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#5216]
In the 1st paragraph "SharedVoicemail" is not listed as a valid value for -Type parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b10b3afe-6425-f0b7-3eb0-a17c6a9d6fef
* Version Independent ID: 9dec1f94-908b-0992-c986-084449965df0
* Content: [New-CsAutoAttendantCallableEntity (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csautoattendantcallableentity?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit
