### ISSUE TITLE
Incorrect command

### ISSUE THREAD

**Issue by matambanadzo** [MicrosoftDocs/office-docs-powershell#5218]
The command is incorrect in Example 1. Should be Grant-CsTeamsMobilityPolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb79bedc-145d-7f61-8973-7e9d0aeaf553
* Version Independent ID: f7f4f158-fe61-ccfe-34fb-2e2628b982e2
* Content: [Grant-CsTeamsMobilityPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsmobilitypolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsTeamsMobilityPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsTeamsMobilityPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @saragava
* Microsoft Alias: **saragava**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @matambanadzo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
