### ISSUE TITLE
Translation errors - Set-PnPListItem is translated to Gruppe-PnPListItem in German

### ISSUE THREAD

**Issue by DennisGaida** [MicrosoftDocs/office-docs-powershell#5229]
Set-PnPListItem is translated to Gruppe-PnPListItem in German.

The [German (automatic) translation](https://docs.microsoft.com/de-de/powershell/module/sharepoint-pnp/set-pnplistitem?view=sharepoint-ps) has several errors:

- `Set-PnPListItem` is translated in the title as well as the first code snippet
- The parameter explanations are not translated (e.g. "Accept pipeline input:" or "Accept wildcard characters:" but should be
- The "Outputs" text has spaces inserted, it reads "_Microsoft. SharePoint. Client. ListItem_" though should be _Microsoft.SharePoint.Client.ListItem_

This is actually true for all/almost all PnP cmdlets in the same docs section. `Unpublish-PnPApp` becomes `Aufheben der Veröffentlichung-PnPApp` > https://docs.microsoft.com/de-de/powershell/module/sharepoint-pnp/unpublish-pnpapp?view=sharepoint-ps

Similar to issue #5170 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362042ec-76bf-6da1-4551-a8baa7a26d27
* Version Independent ID: f30dd9c9-c9fc-f3f9-d5f4-ee4e1b8d3f53
* Content: [Set-PnPListItem (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItem.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DennisGaida Dennis
I reported this to the translation team, it should be fixed soon. Thanks for reporting

**Comment by yogkumgit** [comment]
@OfficeGlobal could you kindly help with this translation issue? Thanks!

**Comment by OfficeGlobal** [comment]
@yogkumgit the articles were HumanTranslated and published live

**Comment by DennisGaida** [comment]
The main error is gone, but there is still some untranslated text. Compare to e.g. https://docs.microsoft.com/de-de/sql/tools/sql-server-profiler/sql-server-profiler?view=sql-server-ver15 where **everything** is translated.

- "Applies to" on top is not translated.
- All parameter descriptions e.g. "Accept pipeline input" are not translated

**Comment by get-itips** [comment]
> @yogkumgit the articles were HumanTranslated and published live

Hello @OfficeGlobal are sentences like _Applies to_ and _Accept Pipeline input_ also included in the automatic translation engine?

**Comment by OfficeGlobal** [comment]
@get-itips strings like "Applies to","Accept pipeline input" are not in files we receive for localization
e.g. _Accept pipeline input_ is in code block and it's excluded from loc. in general

**Comment by get-itips** [comment]
> @get-itips strings like "Applies to","Accept pipeline input" are not in files we receive for localization
> e.g. _Accept pipeline input_ is in code block and it's excluded from loc. in general

Understood, so we wouldn't expect those to be translated. Thanks
