### ISSUE TITLE
Can you list what OOTB Handlers are available

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/office-docs-powershell#523]
Can you please list what OOTB handlers are available and what they do please ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8b1360-5133-03ea-c4de-97d7280ef82c
* Version Independent ID: f7354bf2-01b5-c097-3590-326761cc7f20
* Content: [Apply-PnPProvisioningTemplate (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/apply-pnpprovisioningtemplate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Apply-PnPProvisioningTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Apply-PnPProvisioningTemplate.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen another comment for you (PnP)

**Comment by AndreaBarr** [comment]
@NPrice99 Thank you for this feedback 

I'll get this over to the PowerShell team so we can get this updated with the informaiton for the OOTB handlers. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hello @NPrice99 
Thanks for your feedback.
I created a Pull Request to improve the documentation adding the Handlers Enumeration link
Hopefully, it will be live in a couple of days.
Thank you

**Comment by yogkumgit** [comment]
@VesaJuvonen Please merge PR #2091

**Comment by yogkumgit** [comment]
Gentle reminder @VesaJuvonen Please merge PR #2091

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for reporting the issue in Sharepoint repository and linking here and also sharing this explanation. @NPrice99   Hope this comment is helpful for you. These repos are all open source and the community would welcome to contribute. Thanks for taking out some time to open the issue. Appreciate and encourage you to follow https://github.com/SharePoint/PnP-PowerShell/

**Comment by yogkumgit** [comment]
@officedocsbot close
