### ISSUE TITLE
Error code : Bad Gateway, Forbidden, Request_ResourceNotFound

### ISSUE THREAD

**Issue by pemile** [MicrosoftDocs/office-docs-powershell#5230]
hello,
I m using this method, i experienced many many errors, it does not looks this method is very reliable. Very often i have this error, nobody know's why :
Add-TeamChannelUser : Error occurred while executing 
Code: Request_ResourceNotFound
Message: Resource &lt;xxxxxxxxx&gt;  does not exist or one of its queried reference-property objects are not 
present.
InnerError:
  RequestId: 6fa7e2c3-5bde-4baf-81e7-2adbe20d54e9
  DateTimeStamp: 2020-04-03T11:10:02
HttpStatusCode: Request_ResourceNotFound
Au caractère H:\PROJETS\Ms365\Scripts\creation Equipe_v3.ps1:344 : 21
+ ...             Add-TeamChannelUser -GroupId $team.GroupId -DisplayName $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamChannelUser], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdl 
   ets.PowerShell.Custom.AddTeamChannelUser
 
Add-TeamChannelUser : Error occurred while executing 
Code: Request_ResourceNotFound
Message: Resource xxxxxxxxxxxx
 does not exist or one of its queried reference-property objects are not 
present.
InnerError:
  RequestId: 04c9a482-2b2c-4440-be50-09e68689820b
  DateTimeStamp: 2020-04-03T11:10:04
HttpStatusCode: Request_ResourceNotFound
Au caractère H:\PROJETS\Ms365\Scripts\creation Equipe_v3.ps1:346 : 21
+ ...             Add-TeamChannelUser -GroupId $team.GroupId -DisplayName $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamChannelUser], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdl 
   ets.PowerShell.Custom.AddTeamChannelUser
 
While this user is into the team and i just added in the channel as member.

here is the code i used :

#affection propriétaires
                if ( ! $($channelOwners| where {($_ |select user | out-string) -match $proprietaire1}) ) {
				    Add-TeamChannelUser -GroupId $team.GroupId -DisplayName $groupe -User $proprietaire1
                    #Start-Sleep -M 500
                    Add-TeamChannelUser -GroupId $team.GroupId -DisplayName $groupe -User $proprietaire1 -role Owner
				    $retour  =  "AFFECTATION UTI/CANAL proprietaire 1: {0,-30} canal: {1,-10}"-f $proprietaire1, $groupe
				    Write-Host $retour
                    add-content $ficResultat $retour

I also often experieneced error : "Code: Bad Gateway" or "Code: Forbidden" while this action is made by the owner of the /team /channel

Thank you very much for any suggestions.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 74381d05-2e95-4751-4285-752a46eb025f
* Version Independent ID: 2481b258-b593-e323-90f0-e9ca6e7797bf
* Content: [Add-TeamChannelUser (teams)](https://docs.microsoft.com/fr-fr/powershell/module/teams/add-teamchanneluser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by erictechtips** [comment]
I am also having issues using this command.  I get the following error:  

Add-TeamChannelUser : Error occurred while executing
Code: BadGateway
Message: Failed to execute backend request.
InnerError:
  RequestId: 0b6ffc7c-e352-401e-a027-8be592bda1a4
  DateTimeStamp: 2020-04-06T03:17:26
HttpStatusCode: BadGateway
At line:1 char:1
+ Add-TeamChannelUser -GroupId 60913a38-7edb-41a7-a119-d770609c1b3d -Di ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamChannelUser], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdle
   ts.PowerShell.Custom.AddTeamChannelUser

**Comment by get-itips** [comment]
Hello @pemile how are you?

The cmdlet `Add-TeamChannelUser` is still part of the beta module, I could also confirm that the team is aware of this and is working on it.

I did not identify a need to change any documentation for now.

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @pemile 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
