### ISSUE TITLE
Example is blank

### ISSUE THREAD

**Issue by MSTejas** [MicrosoftDocs/office-docs-powershell#5232]
Hi, Example field in this article is blank. Can you please update it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc910c40-6577-8d7b-476c-1234e836706c
* Version Independent ID: ab8f028f-d0f6-25c0-98d0-7f24806744dc
* Content: [Unregister-CsOnlineDialInConferencingServiceNumber (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/unregister-csonlinedialinconferencingservicenumber?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Unregister-CsOnlineDialInConferencingServiceNumber.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Unregister-CsOnlineDialInConferencingServiceNumber.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tomkau Please merge the PR #5268 Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @MSTejas Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
