### ISSUE TITLE
Problem installing MicrosoftTeams powershell module

### ISSUE THREAD

**Issue by tumtum73** [MicrosoftDocs/office-docs-powershell#5233]
PS C:\Users> Install-Module -Name MicrosoftTeams
WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/MicrosoftTeams/1.0.5' is not valid.
PackageManagement\Install-Package : Package 'MicrosoftTeams' failed to download.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\hiiadm...softTeams.nupkg:String) [Install-Package], Excep
   tion
    + FullyQualifiedErrorId : PackageFailedInstallOrDownload,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPac
   kage

I was successful at manually downloading the package 'https://www.powershellgallery.com/api/v2/package/MicrosoftTeams/1.0.5' and am working on maually deploying the nuget package but would love to know why the install-module command is failing.

Manually installing the Nuget package worked.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tumtum73 Stephen 👍 how are you? Hope you are doing great.
Here, we are limited to documentation issues, said that, I tried to reproduce to see if we need to impact any documentation and I had no issues installing Microsoft Teams Ps Module and the location in the error you shared is valid.
I would recommend checking for filtering issues or, if you still can not fix it, please open a support case directly from your tenant. 
Thank you

**Comment by tameemansari** [comment]
@tumtum73 Please run $PSVersionTable and paste the output so we can take an additional look. 

I also anticipate that there are issues with your PowerShellGet package provider. Can you follow instructions [here](https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7) to resolve the install-module problem. 

Please report back so that we can resolve this issue if this fixes your problem.

**Comment by flowt-au** [comment]
FWIW: with the help of Microsoft Support I solved this by updating my .NET framework to the latest version (4.8)
[https://dotnet.microsoft.com/download/dotnet-framework](https://dotnet.microsoft.com/download/dotnet-framework)

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @tumtum73 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
