### ISSUE TITLE
Complete-CsCceApplianceRegistration not documented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#5238]
empty help article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 458d6654-afed-acdc-3213-d957bf531a7a
* Version Independent ID: 5935e46d-2f6e-445b-319e-cf0bf6cd347c
* Content: [Complete-CsCceApplianceRegistration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/complete-cscceapplianceregistration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Complete-CsCceApplianceRegistration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Complete-CsCceApplianceRegistration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
cmdlet appears to be removed from the module @tomkau Tom, can you confirm?

**Comment by tomkau** [comment]
I reached out to the team that owns this cmdlet

**Comment by yogkumgit** [comment]
@officedocsbot assign @pupara

**Comment by get-itips** [comment]
> I reached out to the team that owns this cmdlet

Tom, how are you? Reaching out to you again to understand if you could confirm we can remove the article from Docs as the cmdlet is not present anymore in the last Teams/SfB module. Thanks

**Comment by get-itips** [comment]
@tomkau Tom, can you remove the cmdlet from documentation? it is not in the module anymore it seems. thanks
