### ISSUE TITLE
Complete-CsCceApplianceUnregistration not documented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#5239]
Empty help article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868c7781-9bef-1cea-d0ea-9359e37c258c
* Version Independent ID: c548835b-c922-e60a-2759-c44e3bb8bf28
* Content: [Complete-CsCceApplianceUnregistration (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/complete-cscceapplianceunregistration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Complete-CsCceApplianceUnregistration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Complete-CsCceApplianceUnregistration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Same as https://github.com/MicrosoftDocs/office-docs-powershell/issues/5238

**Comment by yogkumgit** [comment]
@tomkau Please reply to our query as mentioned in the #5238

**Comment by tomkau** [comment]
I reached out to the team that owns this cmdlet

**Comment by yogkumgit** [comment]
@pupara Please update. cc @Kateyanne

**Comment by pbafna03** [comment]
@get-itips / @yogkumgit - please go ahead to remove this also, checked with the relevant team - this is not supported anymore.
