### ISSUE TITLE
Image Sizes

### ISSUE THREAD

**Issue by kylepdx** [MicrosoftDocs/office-docs-powershell#524]
Would be great in the docs where there are images to list the image dimensions.   For example what are the dimensions for the PreviewImage? 
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58596a8-0429-e115-0dee-c970783ed80f
* Version Independent ID: 7dea06e7-3411-8b9b-8eea-af3cbc4c3f43
* Content: [Add-SPOSiteDesign (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spositedesign?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteDesign.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteDesign.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@VesaJuvonen question about SPOSiteDesign

**Comment by ToddBleeker** [comment]
I agree with @kylepdx, the docs should include image sizes.

That said, I looked for the size of the out-of-the-box image provided by Microsoft and they consistently use 400px wide X 421px high PNGs. Hope that helps others that are looking for these dimensions.

In fact, I recommend navigating to the SharePoint Home page, beginning the creation of a Communication Site, choosing the Blank Site Design, then right-clicking to inspect the image element, find the URL in the HTML img src, and using the PNG image at that URL to create the custom preview image for the custom Site Design. It's a great starting place for consistency with the preview images used by Microsoft.

**Comment by AndreaBarr** [comment]
@kylepdx Thank you for this feedback

I am going to get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hello @kylepdx @ToddBleeker I created a pull request to improve the article adding a recommendation for the size of the preview image. Thanks for your feedback.

**Comment by yogkumgit** [comment]
@trent-green Please merge the PR #3420

**Comment by yogkumgit** [comment]
Gentle reminder @trent-green Please merge the PR #3420

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @kylepdx Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
