### ISSUE TITLE
Get-CsOnlineDialinConferencingPolicy not documented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#5240]
Empty help article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f98e0612-3883-ed72-675f-152a0be06f8d
* Version Independent ID: b5a2130a-0443-ed77-e854-5c4039ebe93f
* Content: [Get-CsOnlineDialinConferencingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialinConferencingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDialinConferencingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@tomkau Tom, can we get detailed information about the scenarios where this cmdlet could be used by Administrators? Other than the palpable information based on the cmdlets name and output (_Global, ServiceAllowed, ServiceNotAllowed_) I appreciate.

**Comment by tomkau** [comment]
I've reached out to the owner of this cmdlet

**Comment by get-itips** [comment]
> I've reached out to the owner of this cmdlet

@tomkau Tom, reaching out to you again to see if you could get more info about this cmdlet, it is still present in the module, thanks

**Comment by yogkumgit** [comment]
@pupara Please update. cc @Kateyanne
