### ISSUE TITLE
Get-CsOnlineDialInConferencingUserState not documented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#5241]
Empty help article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56234fd4-baa8-c376-7804-5e27e326a8c3
* Version Independent ID: 751d9ee5-ccee-bd18-4ce3-687a8c2769d2
* Content: [Get-CsOnlineDialInConferencingUserState (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguserstate?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialInConferencingUserState.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUserState.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @shivtorov I am proposing thru a PR to add missing info. Thanks

**Comment by yogkumgit** [comment]
@tomkau Please merge the PR #5266 Thanks

**Comment by yogkumgit** [comment]
@islubin Please give your inputs in PR #5266 Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @shivtorov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
