### ISSUE TITLE
Extra space in example #3

### ISSUE THREAD

**Issue by O365scripts** [MicrosoftDocs/office-docs-powershell#5247]
Example #3 should be adjusted given there is an extra space.
Add-PnPClientSideWebPart -Page "MyPage" -Component "HelloWorld" -Section 1 -Column 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f213768f-9bc2-36e3-fe0a-d1c3b7f33b08
* Version Independent ID: 3481fdb9-51ed-da91-2aa2-fd3745512f45
* Content: [Add-PnPClientSideWebPart (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpclientsidewebpart?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPClientSideWebPart.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPClientSideWebPart.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @O365scripts 👍 How are you?

The documentation for PnP cmdlets is directly reflected from the cmdlet's source code, that lives in the linked repository.
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.

Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @O365scripts 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
