### ISSUE TITLE
To block ActiveSync access for a generic mailbox.

### ISSUE THREAD

**Issue by manasrrp** [MicrosoftDocs/office-docs-powershell#5252]
Scenario: In a organization there is a generic email ID used by Employee_1 who has ActiveSync enabled on his mobile. After he left from that organization ActiveSync to be enabled to new employee Employee_2. Now how to block previous employee Employee_1 and allow new employee Employee_2 only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ade56cc-22bf-0a4b-5d17-b34c8f4cac91
* Version Independent ID: 28eaa44b-2fed-aa95-bd12-07924ef6c164
* Content: [Get-ActiveSyncDevice (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/get-activesyncdevice?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/devices/Get-ActiveSyncDevice.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/Get-ActiveSyncDevice.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @manasrrp, thank you for your feedback.

I think you should revoke/remove permissions for user Employee_1:
https://docs.microsoft.com/exchange/collaboration-exo/shared-mailboxes

Also, you can remove or disable the account, change password, block sign-in, force sign-out. More information:
https://docs.microsoft.com/microsoft-365/admin/add-users/remove-former-employee

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @manasrrp 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
