### ISSUE TITLE
Not all commands function as expected in remote powershell

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/office-docs-powershell#5256]
For example: Get-ExchangeCertificate will not return the services assigned to the certificates, or any detailed information about the certificate.

In comparison, running the same command in the Exchange Management Shell will return the services. 

The documentation should be updated to reflect which commandlets are not supported, or have limited support in a remote powershell session as this affects runinng code in environments such as Visual Code, or the ISE.  There should not be unexpected behaviour by running the same commandlet in a different session.   This should be computer science, not computer science fiction. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b57b66-2364-0e9d-e627-5eeb77238675
* Version Independent ID: 78fd7932-06f9-37c7-8928-250b3884d89e
* Content: [Connect to Exchange servers using remote PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/connect-to-exchange-servers-using-remote-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-server/connect-to-exchange-servers-using-remote-powershell.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @anthonynz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
