### ISSUE TITLE
No cmtlets

### ISSUE THREAD

**Issue by Jaguar83** [MicrosoftDocs/office-docs-powershell#5257]
This page does not list any cmdlets that are available, nor does it provide any useful links to such a reference. Useless Page

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceeb00d4-65da-0ea5-8089-f16a2f348eb7
* Version Independent ID: 0f4286f0-13dc-0f83-3943-4c51fd715f94
* Content: [Exchange Online PowerShell](https://docs.microsoft.com/en-au/powershell/exchange/exchange-online/exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by Jaguar83** [comment]
This link should be on this page:
https://docs.microsoft.com/en-us/powershell/module/exchange/?view=exchange-ps

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @Jaguar83, thank you for your feedback.

Exchange Online cmdlet reference topics are located in the Reference section of this document. Please, check the left pane.

**Comment by dariomws** [comment]
More information:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/818

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @Jaguar83 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
