### ISSUE TITLE
Option to authorize Group

### ISSUE THREAD

**Issue by akasparas** [MicrosoftDocs/office-docs-powershell#5258]
Without Group authorization it is difficult to administer public folders where all/most tenant users should have access. Whenever users change administrator should go through all such public folders and change rights there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85dfe02b-4a29-e5af-0ff9-7fff5de69045
* Version Independent ID: a51a8a0e-d40c-5510-03e7-c1c43822ff8a
* Content: [Add-PublicFolderClientPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/sharing-and-collaboration/add-publicfolderclientpermission?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/sharing-and-collaboration/Add-PublicFolderClientPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/sharing-and-collaboration/Add-PublicFolderClientPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @akasparas, thank you for your feedback.

You can also add a Universal Distribution Group to public folder permissions. You should use the UPN or alias with the -User parameter.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @akasparas 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
