### ISSUE TITLE
Set-SPO not working as expected

### ISSUE THREAD

**Issue by Oweeboi011** [MicrosoftDocs/office-docs-powershell#5259]
We tried on executing the '`Set-SPOSite -Identity $_siteUrl -LockState Readonly`' but we keep on having the issue below. Was there anything changed since? It was working before as we executed it yesterday.

> `Set-SPOSite : https://tenant-my.sharepoint.com/personal/user_com is a OneDrive for Business site collection. The only valid parameters for this type of site collection are '-Identity', '-AllowDownloadingNonWebViewableFiles', '-AllowEditing', '-ConditionalAccessPolicy', '-DefaultLinkPermission', '-DefaultSharingLinkType', '-DisableCompanyWideSharingLinks', '-LimitedAccessFileType', '-LockState', '-Owner', '-SharingAllowedDomainList', '-SharingBlockedDomainList', '-SharingCapability', '-SharingDomainRestrictionMode', '-ShowPeoplePickerSuggestionsForGuestUsers', '-StorageQuota', and '-StorageWarningLevel'.`

Hope you can help us with our issue or guide us if we missed something on our end.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by kefujino** [comment]
@Oweeboi011
Hello,

This issue may have been fixed with the latest version of the module.

I recently experienced a similar error when changing the StorageWarningLevel for a Group site.

The version was 16.0.19814.12000.
>Get-InstalledModule -Name Microsoft.Online.SharePoint.PowerShell -AllVersions

After updating to the latest version (16.0.19927.12000),  the same command works.

>Update-Module -Name Microsoft.Online.SharePoint.PowerShell

For my tenant using the latest version, -LockState ReadOnly also works.

Would you please check and update your module version?

**Comment by kefujino** [comment]
If you use SharePoint Online Management Shell, you can get latest version here.
https://www.microsoft.com/en-us/download/details.aspx?id=35588

**Comment by get-itips** [comment]
Hello @Oweeboi011 how are you? I could verify in my lab what @kefujino kindly shared here, using the latest version of the module, it worked without issues.
Hope this info helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Oweeboi011 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by sparameswaran78** [comment]
all
it is not working and we have updated the module and it same issue. we have tried to increase quota and failed

**Comment by get-itips** [comment]
> all
> it is not working and we have updated the module and it same issue. we have tried to increase quota and failed

Please kindly open a support ticket in your tenant, they will able to help you.

**Comment by toffitomek** [comment]
after updating SP module to newest one my error went away :)

**Comment by kpinel** [comment]
And, it appears to be back in the latest version

```powershell
Get-Module microsoft.online.Sharepoint.powershell | select name,version

Name                                   Version
----                                   -------
microsoft.online.Sharepoint.powershell 16.0.20717.12000


PS D:\Scripts> Set-SPOSite "https://tenant-my.sharepoint.com/personal/$Domain" -LockState NoAccess
Set-SPOSite : https://connectqutedu-my.sharepoint.com/personal/wahry_qut_edu_au is a OneDrive for Business site
collection. The only valid parameters for this type of site collection are '-Identity',
'-AllowDownloadingNonWebViewableFiles', '-AllowEditing', '-ConditionalAccessPolicy', '-DefaultLinkPermission',
'-DefaultSharingLinkType', '-DisableCompanyWideSharingLinks', '-LimitedAccessFileType', '-LockState', '-Owner',
'-SharingAllowedDomainList', '-SharingBlockedDomainList', '-SharingCapability', '-SharingDomainRestrictionMode',
'-ShowPeoplePickerSuggestionsForGuestUsers', '-StorageQuota', and '-StorageWarningLevel'.
At line:1 char:1
+ Set-SPOSite "https://tenant-my.sharepoint.com/personal/$Domain ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-SPOSite], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.SetSite
```
