### ISSUE TITLE
Please include the differences between this and the Teams Only tenants or at least link to the page.

### ISSUE THREAD

**Issue by Coldry** [MicrosoftDocs/office-docs-powershell#5262]
This page states the following:
    Module: skype
    Applies to: Skype for Business Online

So where's the page that explains the details of this command for Teams? Ah... I hear you say, S4B online is Teams Telephony or is being migrated to Teams Telephone. Still, if the command works in a Teams only tenant then it should be included in the Applies to: pointing out the differences. 
OK having said that, I've noticed the "Get-Help Get-CsCallQueue -Full" (output below) command in a Teams Only tenant does return something different. The parameter type of the -Identity parameter shows as &lt;String&gt; not &lt;guid&gt;. Also, a number of the above parameters don't appear Deserialized in the Teams only tenant and there are a couple that isn't mentioned on this page which I guess the S4B Online doesn't have like "MusicOnHoldFileDownloadUri" or does it?

Name                                           MemberType   Definition
----                                           ----------   ----------
GetType                                        Method       type GetType()
ToString                                       Method       string ToString(), string ToString(string format, System.IFormatProvider forma...
DisplayAgents                                  NoteProperty Deserialized.System.Management.Automation.PSCustomObject DisplayAgents=
DisplayApplicationInstances                    NoteProperty string DisplayApplicationInstances=
DisplayDistributionLists                       NoteProperty Deserialized.System.Management.Automation.PSCustomObject DisplayDistributionLi...
DisplayStatistics                              NoteProperty string DisplayStatistics=Current queue size = 0
DisplayUsers                                   NoteProperty Deserialized.System.Management.Automation.PSCustomObject DisplayUsers=
OverflowActionTargetId                         NoteProperty Deserialized.System.Management.Automation.PSCustomObject OverflowActionTargetId=
PSComputerName                                 NoteProperty string PSComputerName=admingb1.online.lync.com
PSShowComputerName                             NoteProperty bool PSShowComputerName=False
RunspaceId                                     NoteProperty guid RunspaceId=
TimeoutActionTargetId                          NoteProperty Deserialized.System.Management.Automation.PSCustomObject TimeoutActionTargetId=
AgentAlertTime                                 Property     System.Int16 {get;set;}
Agents                                         Property     Deserialized.System.Collections.Generic.List`1[[Microsoft.Rtc.Management.Hoste...
AgentsCapped                                   Property     System.Boolean {get;set;}
AgentsInSyncWithDistributionLists              Property     System.Boolean {get;set;}
AllowOptOut                                    Property     System.Boolean {get;set;}
ApplicationInstances                           Property     Deserialized.System.Collections.ObjectModel.ObservableCollection`1[[System.Str...
ConferenceMode                                 Property      {get;set;}
Description                                    Property      {get;set;}
DistributionLists                              Property     Deserialized.System.Collections.ObjectModel.ObservableCollection`1[[System.Gui...
DistributionListsLastExpanded                  Property     Deserialized.System.DateTimeOffset {get;set;}
EnableOverflowSharedVoicemailTranscription     Property      {get;set;}
EnableTimeoutSharedVoicemailTranscription      Property      {get;set;}
Identity                                       Property     System.String {get;set;}
LanguageId                                     Property      {get;set;}
MusicOnHoldFileDownloadUri                     Property      {get;set;}
MusicOnHoldFileName                            Property     System.String {get;set;}
MusicOnHoldResourceId                          Property     System.String {get;set;}
Name                                           Property     System.String {get;set;}
OverflowAction                                 Property     Deserialized.Microsoft.Rtc.Management.Hosted.HuntGroup.Models.OverflowAction {...
OverflowActionTarget                           Property      {get;set;}
OverflowSharedVoicemailAudioFilePrompt         Property      {get;set;}
OverflowSharedVoicemailAudioFilePromptFileName Property      {get;set;}
OverflowSharedVoicemailTextToSpeechPrompt      Property      {get;set;}
OverflowThreshold                              Property     System.Int16 {get;set;}
PresenceBasedRouting                           Property      {get;set;}
RoutingMethod                                  Property     Deserialized.Microsoft.Rtc.Management.Hosted.HuntGroup.Models.RoutingMethod {g...
Statistics                                     Property     Deserialized.System.Collections.Generic.List`1[[Microsoft.Rtc.Management.Hoste...
StatusRecords                                  Property     Deserialized.System.Collections.Generic.List`1[[Microsoft.Rtc.Management.Hoste...
TenantId                                       Property     System.Guid {get;set;}
TimeoutAction                                  Property     Deserialized.Microsoft.Rtc.Management.Hosted.HuntGroup.Models.TimeoutAction {g...
TimeoutActionTarget                            Property      {get;set;}
TimeoutSharedVoicemailAudioFilePrompt          Property      {get;set;}
TimeoutSharedVoicemailAudioFilePromptFileName  Property      {get;set;}
TimeoutSharedVoicemailTextToSpeechPrompt       Property      {get;set;}
TimeoutThreshold                               Property     System.Int16 {get;set;}
UseDefaultMusicOnHold                          Property     System.Boolean {get;set;}
Users                                          Property     Deserialized.System.Collections.ObjectModel.ObservableCollection`1[[System.Gui...
WelcomeMusicFileDownloadUri                    Property      {get;set;}
WelcomeMusicFileName                           Property      {get;set;}
WelcomeMusicResourceId                         Property      {get;set;}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7364cece-00a4-7e29-4fa9-190db5f9e3dd
* Version Independent ID: 67efa086-edb0-2828-cc14-4c245290e4f3
* Content: [Set-CsCallQueue (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-CsCallQueue?view=skype-ps&source=docs)
* Content Source: [skype/skype-ps/skype/Set-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by kenwith** [comment]
@Coldry - thank you for taking the time to provide feedback. The cmdlet's are all open source now and experts such as yourself providing feedback and contributions is what improves the quality and helps the community. I tried to add some content to help make this clearer in this PR here: https://github.com/MicrosoftDocs/office-docs-powershell/pull/5474  Let me know if you think this helps. There is a good conceptual article that @get-itips found that adds more information beyond the simple cmdlet reference topic. I added a link to it in the reference content. I know there is also work by the product teams to bring the Skype for Business Online and Teams PowerShell modules together so that will remove the confusion. I feel your pain though that the SfBO cmdlet's also are used in Teams and I am very much looking forward to a single PowerShell module. In the meantime I can add to the documentation to help add clarification. The way these cmdlet reference articles are generated is the open source PlatyPS tool ( https://github.com/PowerShell/platyPS ). It basically uses reflection to generate the reference content. @get-itips will go ahead and run PlatyPS on this cmdlet and update any new or changed parameters.. and if you have any ideas let us know and it would be great to merge your contributions into the reference article.

**Comment by yogkumgit** [comment]
@kenwith  Thank you very much for the contribution and sharing this explanation. @Coldry 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
