### ISSUE TITLE
GroupCreationEnabled also apply for Outlook Desktop

### ISSUE THREAD

**Issue by RomanNG** [MicrosoftDocs/office-docs-powershell#5263]
Hi, from my testing, the GroupCreationEnabled parameter when set to false will also make the "create group" button in outlook desktop (Office 365 Pro Plus Click To Run) hidden. This parameter does not only impact Outlook On The Web.
Can you confirm it's a normal behavior and update the online documentation accordingly ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ca7906-9f33-2991-9da9-a626e5e45c46
* Version Independent ID: 5f388b3c-fb47-f7a0-e648-07cb3e59cf72
* Content: [Set-OwaMailboxPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/Set-OwaMailboxPolicy?redirectedfrom=MSDN&view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @RomanNG Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
