### ISSUE TITLE
Example 2 - Confusing!

### ISSUE THREAD

**Issue by waelschakaki** [MicrosoftDocs/office-docs-powershell#5267]
Hello,
I think example 2 is a little bit confusing 
New-CsTenantTrustedIPAddress -IPAddress "192.168.0.2" -MaskBits "24"
it should be 192.168.2.0\24 right? or what is the use case of defining one IP "not subnet" with bitmask 24?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3cd4baa-83d8-44f5-7b9e-f2cf23469173
* Version Independent ID: 68a5a8fb-e982-d6ce-c92b-0cc304e9655b
* Content: [New-CsTenantTrustedIPAddress (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cstenanttrustedipaddress?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTenantTrustedIPAddress.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTenantTrustedIPAddress.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @waelschakaki how are you? Will propose changing that in the article. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @waelschakaki Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
