### ISSUE TITLE
Send welcome email

### ISSUE THREAD

**Issue by CaseyRoot** [MicrosoftDocs/office-docs-powershell#5269]
When I use this Add-SPOUser command, it does not sent out the email notifying the user they have been added to the site.  Is there a parameter I can add to send this email out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369ac4a3-96b9-7d17-eaf1-5b7bb2f12928
* Version Independent ID: cd322085-07d6-64f4-4aaa-d9200e3191aa
* Content: [Add-SPOUser (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spouser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOUser.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @CaseyRoot how are you?
This cmdlet currently has no option to do that, I suggest adding the idea to [SharePoint UserVoice](https://sharepoint.uservoice.com/).

**Comment by yogkumgit** [comment]
@CaseyRoot  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
