### ISSUE TITLE
How to add SharePoint PS cmdlet to PowerShell without Admin permissions

### ISSUE THREAD

**Issue by sjlarkin** [MicrosoftDocs/office-docs-powershell#5271]
This article does not cover how I should add the PS cmdlet for SharePoint without a SP admin console or rights. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102a89dc-8bb7-e76e-f570-3d6bde7e8308
* Version Independent ID: 3eb619c5-db95-9a42-4c83-9778572f00fc
* Content: [SharePoint Server Cmdlets](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-server/sharepoint-server-cmdlets.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sjlarkin how are you? 👍 

The article says that you have to be granted SP Shell admin thru Add-SPShellAdmin to be able to run SharePoint cmdlets.

> NOTE: When you install SharePoint Server, the user account from which you run the installation is granted the appropriate permissions to run PowerShell cmdlets. If any users have not been added to run a PowerShell cmdlet, you can use the Add-SPShellAdmin cmdlet to add them.

Hope this clarifies it to you.

**Comment by sjlarkin** [comment]
Thank you. I went back and reread the article, and saw that I need admin privs which I’ll never get. Submitted a request to our SP support team.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @sjlarkin 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
