### ISSUE TITLE
Get-PnPProvisioningTemplate -IncludeAllClientSidePages does not return all pages

### ISSUE THREAD

**Issue by ddbardsley** [MicrosoftDocs/office-docs-powershell#5273]
The IncludeAllClientSidePages parameter for Get-PnPProvisioningTemplate does not return all pages within a site. It only returns the default home site page. Here is what I am using:

Get-PnPProvisioningTemplate -Out $siteTemplateFile -IncludeAllClientSidePages

I have the following PnP-PowerShell version installed on my system.

PS C:\WINDOWS\system32> Get-Module SharePointPnPPowerShell* -ListAvailable| Select-Object Name,Version| Sort-Object Version -Descending

Name                          Version
----                          -------
SharePointPnPPowerShellOnline 3.20.2004.0
SharePointPnPPowerShellOnline 3.19.2003.0
SharePointPnPPowerShellOnline 2.28.1807.0

The output only has the following site pages (note: Pages\DGLProjectsHome.aspx is the default home page):

<pnp:Files>
	<pnp:File Src="Pages\DGLProjectsHome.aspx" Folder="{site}/Pages" Overwrite="true" Level="Published">
	...
        </pnp:File>
        <pnp:File Src="_catalogs\masterpage\oslo.master" Folder="{masterpagecatalog}" Overwrite="true" Level="Published">
	...
        </pnp:File>
        <pnp:File Src="_catalogs\masterpage\seattle.master" Folder="{masterpagecatalog}" Overwrite="true" Level="Published">
	...
        </pnp:File>
 </pnp:Files>

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ddbardsley David 👍 how are you?

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.

Thanks

**Comment by ddbardsley** [comment]
Hi, Thank you. I opened this within the other repo. David.
