### ISSUE TITLE
Functionality such as external sharing and application interfaces are dependent on the policies and permissions defined at the root site

### ISSUE THREAD

**Issue by lammy82** [MicrosoftDocs/office-docs-powershell#5274]
Referring to preparation activity 2 listed when swapping a site to the root site of the tenant:

What does the above mean? Is it implying that whatever sharing settings are defined at the root site, these will apply to all sites within the tenant? That's not how it works. I want the site I am swapping to the root to retain the policies I have defined for it, which are different from the policies applied to other sites in the tenant. Please could this clause be re-written to make it clearer what happens to the sharing settings when the command is run?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb8f8e8-1242-363c-be77-038142b4efb9
* Version Independent ID: 54a60006-3d61-4bb9-a040-60fe77ef9f85
* Content: [Invoke-SPOSiteSwap (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/invoke-spositeswap?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md)
* Service: **sharepoint-powershell**
* GitHub Login: @WayneEwington
* Microsoft Alias: **waynewin**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @lammy82 how are you?
In my lab, I defined the following external sharing for the current root

_"This site can't be shared externally"_

Created a new Communication Site Collection and defined the external sharing as

_"Files and folders on this site can be shared with anyone"_

I ran the cmdlet to swap the newly created sc to be the new root site collection, it retained the external sharing settings of the newly created site "Files and folders on this site can be shared with anyone"

Does that answer your question? also adding @WayneEwington Wayne to confirm.

**Comment by lammy82** [comment]
Hi, thanks - yes, that is the same behaviour I observed when using the command.
Therefore, I don't understand why point 2 exists in the document. The behaviour when swapping to the root site is no different than the behaviour when swapping to any other location. The sharing policies from the source site are maintained at the new location.

What should be listed, is that if you swap a site to the root site then any existing Promoted Links are lost. So those should be noted and then re-created afterwards.

**Comment by get-itips** [comment]
> Hi, thanks - yes, that is the same behaviour I observed when using the command.
> Therefore, I don't understand why point 2 exists in the document. The behaviour when swapping to the root site is no different than the behaviour when swapping to any other location. The sharing policies from the source site are maintained at the new location.
> 
> What should be listed, is that if you swap a site to the root site then any existing Featured Links set up on the SharePoint landing page (/_layouts/15/sharepoint.aspx) are lost. So those should be noted and then re-created afterwards.

Thanks for your feedback. Let's see if @WayneEwington can shed some light here

**Comment by WayneEwington** [comment]
The key point is to ensure that the permissions (including any sharing configuration settings) on the source site match those on the target site (if required). For example, by default the root site collection allows all users in the organization to access it. If a source site that is restricted to a subset of users is moved to the root, then some users will no longer have access which could impact their ability to authenticate and browse to any other site.

**Comment by get-itips** [comment]
> The key point is to ensure that the permissions (including any sharing configuration settings) on the source site match those on the target site (if required). For example, by default the root site collection allows all users in the organization to access it. If a source site that is restricted to a subset of users is moved to the root, then some users will no longer have access which could impact their ability to authenticate and browse to any other site.

Thanks @WayneEwington for clarifying!

**Comment by yogkumgit** [comment]
@get-itips  and @WayneEwington  Thank you very much for sharing this explanation. @lammy82 
Hope these comments are helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
