### ISSUE TITLE
Apply-PnPProvisioningTemplate does not provision the site Navigation

### ISSUE THREAD

**Issue by ddbardsley** [MicrosoftDocs/office-docs-powershell#5277]
I use the following command to acquire the site information which contains the pnp:Navigation tags within the XML template.

Get-PnPProvisioningTemplate -IncludeAllClientSidePages -Out $siteTemplateFile 

I then use the following command to apply the acquired XML template (please note that the required site pages, used by the navigation, are already provisioned on the site).

Apply-PnPProvisioningTemplate -Web $web -Path $templateFile -OverwriteSystemPropertyBagValues -ClearNavigation -IgnoreDuplicateDataRowErrors

**PROBLEM**: The Navigation items are not provisioned to the site (note: the required site pages, used by the navigation tags within the XML template, are already provisioned on the site).

I have the following PnP-PowerShell version installed on my system.

PS C:\Users\david> Get-Module SharePointPnPPowerShell* -ListAvailable| Select-Object Name,Version| Sort-Object Version -Descending

Name                          Version
----                          -------
SharePointPnPPowerShellOnline 3.20.2004.0

**Here is the pnp:Navigation settings from the template file**

      <pnp:Navigation AddNewPagesToNavigation="true" CreateFriendlyUrlsForNewPages="true">
        <pnp:GlobalNavigation NavigationType="Structural">
          <pnp:StructuralNavigation RemoveExistingNodes="false">
            <pnp:NavigationNode Title="Documents" Url="{site}/Pages/DailyReports.aspx">
              <pnp:NavigationNode Title="Daily Reports" Url="{site}/Pages/DailyReports.aspx" />
              <pnp:NavigationNode Title="Specifications" Url="{site}/Pages/Specifications.aspx" />
              <pnp:NavigationNode Title="Shared Documents" Url="{site}/Pages/SharedDocuments.aspx" />
              <pnp:NavigationNode Title="Meeting Minutes" Url="{site}/Pages/MeetingMinutes.aspx" />
            </pnp:NavigationNode>
            <pnp:NavigationNode Title="Drawings" Url="{site}/Pages/SharedDrawings.aspx">
              <pnp:NavigationNode Title="Shared Drawings" Url="{site}/Pages/SharedDrawings.aspx" />
              <pnp:NavigationNode Title="Vendor Drawings" Url="{site}/Pages/VendorDrawings.aspx" />
              <pnp:NavigationNode Title="Released Drawings" Url="{site}/Pages/ReleasedDrawingsViewPages/ReleasedDrawings.aspx" />
            </pnp:NavigationNode>
            <pnp:NavigationNode Title="Photos" Url="{site}/Pages/SitePhotos.aspx" />
            <pnp:NavigationNode Title="Procurement" Url="{site}/Pages/PurchaseCommitments.aspx">
              <pnp:NavigationNode Title="Purchase Commitments" Url="{site}/Pages/PurchaseCommitments.aspx" />
              <pnp:NavigationNode Title="Purchase/Work Authorizations" Url="{site}/Pages/PurchaseWorkAuthorizations.aspx" />
            </pnp:NavigationNode>
            <pnp:NavigationNode Title="Schedules" Url="{site}/Pages/ProjectSchedules.aspx" />
            <pnp:NavigationNode Title="Lists" Url="{site}/Pages/Equipment.aspx">
              <pnp:NavigationNode Title="Equipment" Url="{site}/Pages/Equipment.aspx" />
              <pnp:NavigationNode Title="External Shares" Url="{site}/Pages/ExternalSharesListing.aspx" />
              <pnp:NavigationNode Title="Outstanding Issues" Url="{site}/Pages/OutstandingIssues.aspx" />
            </pnp:NavigationNode>
            <pnp:NavigationNode Title="Bid Packages" Url="{site}/Pages/Bid-Packages-List.aspx" />
            <pnp:NavigationNode Title="Daily Reports Detail" Url="{site}/Pages/DailyReportsDetail.aspx" />
            <pnp:NavigationNode Title="Change Orders" Url="{site}/Pages/ChangeOrders.aspx" />
            <pnp:NavigationNode Title="Sales Agreement" Url="{site}/Pages/SalesAgreement.aspx" />
            <pnp:NavigationNode Title="Subcontract" Url="{site}/Pages/Subcontract.aspx" />
            <pnp:NavigationNode Title="Daily Reports Detail" Url="{site}/Pages/ReportsDetail.aspx" />
            <pnp:NavigationNode Title="Purchase Order" Url="{site}/Pages/PurchaseOrder.aspx" />
            <pnp:NavigationNode Title="Bid Packages" Url="{site}/Pages/BidPackages.aspx" />
            <pnp:NavigationNode Title="Shared Documents" Url="{site}/Pages/SharedDocuments.aspx" />
            <pnp:NavigationNode Title="Shared Drawings" Url="{site}/Pages/SharedDrawings.aspx" />
            <pnp:NavigationNode Title="Specifications" Url="{site}/Pages/Specifications.aspx" />
            <pnp:NavigationNode Title="Instruments" Url="{site}/Pages/Instruments.aspx" />
            <pnp:NavigationNode Title="Equipment" Url="{site}/Pages/Equipment.aspx" />
            <pnp:NavigationNode Title="Meeting Minutes" Url="{site}/Pages/MeetingMinutes.aspx" />
            <pnp:NavigationNode Title="Outstanding Issues" Url="{site}/Pages/OutstandingIssues.aspx" />
            <pnp:NavigationNode Title="Purchase Commitments" Url="{site}/Pages/PurchaseCommitments.aspx" />
            <pnp:NavigationNode Title="Vendor Drawings" Url="{site}/Pages/VendorDrawings.aspx" />
            <pnp:NavigationNode Title="EWAs" Url="{site}/Pages/EWAs.aspx" />
            <pnp:NavigationNode Title="Daily Reports" Url="{site}/Pages/DailyReports.aspx" />
            <pnp:NavigationNode Title="Project Schedules" Url="{site}/Pages/ProjectSchedules.aspx" />
            <pnp:NavigationNode Title="Project Properties" Url="{site}/Pages/ProjectProperties.aspx" />
            <pnp:NavigationNode Title="Site Photos" Url="{site}/Pages/SitePhotos.aspx" />
            <pnp:NavigationNode Title="Design Basis" Url="{site}/Pages/DesignBasis.aspx" />
            <pnp:NavigationNode Title="Bid Packages List" Url="{site}/Pages/Bid-Packages-List.aspx" />
            <pnp:NavigationNode Title="Purchase/Work Authorizations" Url="{site}/Pages/PurchaseWorkAuthorizations.aspx" />
            <pnp:NavigationNode Title="Vendor Drawings By Vendor" Url="{site}/Pages/VendorDrawingsByVendor.aspx" />
            <pnp:NavigationNode Title="Man Hour Summary" Url="{site}/Pages/ManHourSummary.aspx" />
            <pnp:NavigationNode Title="Add To Bid Package" Url="{site}/Pages/AddToBidPackage.aspx" />
            <pnp:NavigationNode Title="External Share" Url="{site}/Pages/ExternalShares.aspx" />
            <pnp:NavigationNode Title="ExternalSharesListing" Url="{site}/Pages/ExternalSharesListing.aspx" />
          </pnp:StructuralNavigation>
        </pnp:GlobalNavigation>
        <pnp:CurrentNavigation />
      </pnp:Navigation>

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by ddbardsley** [comment]
I opened this issue in the pnp/PnP-PowerShell repo. Sorry about the confusion. David
