### ISSUE TITLE
This is not working in Exchange Online.

### ISSUE THREAD

**Issue by kevinzhang999** [MicrosoftDocs/office-docs-powershell#5287]
Applies to:
Exchange Server 2010, Exchange Server 2013, Exchange Server 2016, Exchange Server 2019, Exchange Online
This cmdlet is available only in on-premises Exchange.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f56d9d31-7fec-d066-253d-13ef24cf9b31
* Version Independent ID: ae1640b8-26b0-eddc-8abb-d9309f44c125
* Content: [Get-MessageTrackingReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/get-messagetrackingreport?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Get-MessageTrackingReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Get-MessageTrackingReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge this PR #5307 Thanks

**Comment by chrisda** [comment]
Merged. Closing.
