### ISSUE TITLE
"Revoke-SPObjectSecurity" link goes nowhere

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/office-docs-powershell#5288]
Doesn't look like it is part of the most recent Management Shell cmdlet set, either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65bf2c0b-b0ec-2748-e47e-af66011efe30
* Version Independent ID: be3968f4-d766-0b45-384b-c51c47328a86
* Content: [SharePoint Online PowerShell](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/?view=sharepoint-ps&redirectedfrom=MSDN#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @joshtransient 
How are you?
Thanks for noticing.
The cmdlet belongs to SharePoint Server cmdlets, it was moved by this [PR](https://github.com/MicrosoftDocs/office-docs-powershell/pull/2946/)

However, it was, incorrectly listed on the SharePoint Online TOC as you could identify. Created a PR to correct. Thanks again.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @joshtransient Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
