### ISSUE TITLE
Variable not used

### ISSUE THREAD

**Issue by CedgeTheLedge** [MicrosoftDocs/office-docs-powershell#5290]
In your example 3, $menuPrompt is declared but never used. Is this normal ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0637a09-b222-08c8-c379-ddf503c42ae6
* Version Independent ID: ba49f51d-6c7b-be1e-098c-8e8bf3fe2ba0
* Content: [New-CsAutoAttendantCallHandlingAssociation (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csautoattendantcallhandlingassociation?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendantCallHandlingAssociation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsAutoAttendantCallHandlingAssociation.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @CedgeTheLedge Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
