### ISSUE TITLE
The command never return last access time

### ISSUE THREAD

**Issue by hishikitetsuya** [MicrosoftDocs/office-docs-powershell#5291]
## Problem

This page includes the following statement:

> Information returned includes subject, last modification time, **last accessed time (on-premises Exchange only)**, creation time, attachments, message size, and the type of item.

However, the command never returns last access time info even if on-premises Exchange. Here is an example.

```PowerShell
# Exchange 2010 Legacy PF
[PS] > Get-PublicFolderItemStatistics \test001 | fl *last*

LastModificationTime : 2019/08/27 12:29:25

# Exchange 2010 Modern PF
[PS] > Get-PublicFolderItemStatistics \pf002 | fl *last*

LastModificationTime : 4/7/2020 8:33:29 AM
```

As you can see, the results never show last access time and only include LastModificationTime when we filter the result with `*last*` regardless of the Exchange version. 

## Proposal

Description about last access time should be removed from the sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6b7c43-b67e-7356-d44f-e5ababd8c61c
* Version Independent ID: 5ac3ac6c-5bbd-1c2e-fb1d-42e0112b7b6c
* Content: [Get-PublicFolderItemStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/sharing-and-collaboration/get-publicfolderitemstatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/sharing-and-collaboration/Get-PublicFolderItemStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/sharing-and-collaboration/Get-PublicFolderItemStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @hishikitetsuya Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
