### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by alohaninja** [MicrosoftDocs/office-docs-powershell#5293]
[Installed PS on MacOS using guidance here](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-7), but these [MS Teams CLI commands ](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps)only seem to support WinOS - we should add a note / disclaimer on platforms supported for the CLI. I can[ install the PS module](https://www.poshtestgallery.com/packages/MicrosoftTeams/1.0.21) on MacOS, but can't seem to run any of the commands. 

## Connect-MicrosoftTeams in MacOS `pysh` 
```
Connect-MicrosoftTeams: The term 'Connect-MicrosoftTeams' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

## Note Suggestion
> **Note:** Teams CLI is currently only supported on Windows OS platform 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94694082-c529-5654-1734-57514ec17a1f
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [Microsoft Teams PowerShell](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @alohaninja, thank you for your feedback.

Microsoft Teams PowerShell is supported on Windows PowerShell, not yet in PowerShell Core. Probably next quarter support will be added.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @alohaninja 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
