### ISSUE TITLE
Exchange online doesn't support enable-um command

### ISSUE THREAD

**Issue by Danesh89** [MicrosoftDocs/office-docs-powershell#5294]
Need to remove exchange online from enable-um as um online is completely decommissioned

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @Danesh89, thank you for your feedback.

Same as https://github.com/MicrosoftDocs/office-docs-powershell/issues/5299:

"100% agree that Exchange UM in the cloud is going aware or gone, but the cmdlets are still available. I'm hesitant to remove Exchange Online info until the cmdlets are actually no longer available. It could be a matter of timing (if we wait a bit longer, the cmdlets might go away).

The announcement is here:
https://techcommunity.microsoft.com/t5/exchange-team-blog/retiring-unified-messaging-in-exchange-online/ba-p/608991"

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @Danesh89 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
