### ISSUE TITLE
What about guests?

### ISSUE THREAD

**Issue by winderickxeli** [MicrosoftDocs/office-docs-powershell#5295]
Hi!

Due to a collaboration of two schools, we would like to add several guest users to a team. Is this possible with this powershell module?  Do I need something else? This documentation doesn't explain this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da0c53f2-1c62-14f6-6371-f54bf86b0c24
* Version Independent ID: aac162db-a9c0-fbfb-dd40-526e94d3bef8
* Content: [Add-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamuser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @winderickxeli, thank you for your feedback.

You cannot add guest users using this cmdlet or any other, sorry about that. If you consider it an important feature please put your vote here:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38186131-add-team-guest-user
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18625588-mass-add-users-to-a-channel-or-team

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @winderickxeli 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
