### ISSUE TITLE
Whatif not working disable-inboxrule

### ISSUE THREAD

**Issue by 2MuchLag4you** [MicrosoftDocs/office-docs-powershell#5296]
I just used the Powershell module for exchangeonline ( with 2fa ) 
I haven't had the time to switch to the v2 module but I just had the following issue.

When requesting an inboxrule with get-inboxrule and piping it to disable-inboxrule with the whatif statement does not work.
It will do the following: 

```
PS C:\Users\> Get-InboxRule -Mailbox <SomeUser@organisation>

Name                 Enabled Priority RuleIdentity
----                 ------- -------- ------------
< SomeRule >         True    1        2611323365595545602
PS C:\Users\> Get-InboxRule -Mailbox <SomeUser@organisation> | Disable-InboxRule -WhatIf
PS C:\Users\> Get-InboxRule -Mailbox <SomeUser@organisation>

Name                 Enabled Priority RuleIdentity
----                 ------- -------- ------------
< SomeRule >         False   1        2611323365595545602
```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @2MuchLag4you, thank you for your feedback.

It's documented that -WhatIf parameter does not work with [Disable-InboxRule](https://docs.microsoft.com/powershell/module/exchange/mailboxes/disable-inboxrule). Please check the article and let me know if I can provide more help.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @2MuchLag4you Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
