### ISSUE TITLE
[LOC] Back-Translation "設定-ラベル"→"Set-Label"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-docs-powershell#5297]
🛑 IMPORTANT: You can get your feedback addressed faster if you use the comment section for the article in which you encountered a problem (if available).
![set-label_j](https://user-images.githubusercontent.com/40815708/79323069-b0df0480-7f48-11ea-82da-a6fd2371956d.png)

Link to article:
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/exchange/policy-and-compliance/set-label?view=exchange-ps"

Problem:
What's wrong with the article?
[LOC] Back-Translation "設定-ラベル"→"Set-Label"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48f2421f-0e77-dc9c-8dcf-f97a9374b118
* Version Independent ID: b361e69c-8cbc-6ff8-9edd-9babdd3fbe7a
* Content: [Set-Label (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/set-label?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance/Set-Label.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance/Set-Label.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@OfficeGlobal could you kindly help with this translation issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by yogkumgit** [comment]
@OfficeGlobal any update please

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @yogkumgit article is HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Fixed.
Closed #5297.
Thanks.
