### ISSUE TITLE
Exchange online should be removed as um online is decommissioned

### ISSUE THREAD

**Issue by Danesh89** [MicrosoftDocs/office-docs-powershell#5299]
Please remove exchange online from this page in enable-ummailbox and disable-ummailbox as exchange online um is decommissioned

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e92104-ab9d-d186-95bf-ce95b1b1cd68
* Version Independent ID: d0098c54-1c5c-85c4-f264-8214ba814a92
* Content: [Enable-UMMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/unified-messaging/enable-ummailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/unified-messaging/Enable-UMMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/unified-messaging/Enable-UMMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Danesh89, 100% agree that Exchange UM in the cloud is going aware or gone, but the cmdlets are still available. I'm hesitant to remove Exchange Online info until the cmdlets are actually no longer available. It could be a matter of timing (if we wait a bit longer, the cmdlets might go away).

The announcement is here:
https://techcommunity.microsoft.com/t5/exchange-team-blog/retiring-unified-messaging-in-exchange-online/ba-p/608991

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @Danesh89 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
