### ISSUE TITLE
Exchange Online PowerShell V2 note is not formatted correctly

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/office-docs-powershell#5300]
This page:
```
> [!NOTE] > More content
```

Correct Syntax:
```
> [!NOTE]
> More content
```

I believe the intent was for the note to look like the page below. Unfortunately, it looks like 99% of the pages this note was added to are not using the correct markdown syntax.

https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586e8b44-035e-adae-2847-b5288bc6898d
* Version Independent ID: 03dda286-85d7-41ca-a6dd-f88ef8d89dc6
* Content: [Set-HostedConnectionFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/set-hostedconnectionfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedConnectionFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/antispam-antimalware/Set-HostedConnectionFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jonwbstr, this is a known issue we are working on.

Thanks for the feedback.
