### ISSUE TITLE
Get-PNPUnifiedGroup -ErrorActions not working

### ISSUE THREAD

**Issue by 3031539** [MicrosoftDocs/office-docs-powershell#5302]
When trying to use the -ErrorActions SilentlyContinue no matter it continues on error.

SharePointPnPPowerShellOnline 3.20.2004.0

Get-PnPUnifiedGroup : Code: Request_ResourceNotFound
Message: Resource '1cb8f064-164d-4b76-8f44-012c5491362b' does not exist or one of its queried reference-property objects are not
present.
Inner error
Au caractère Ligne:1 : 1
+ Get-PnPUnifiedGroup -ErrorAction SilentlyContinue -Identity 1cb8f064- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PnPUnifiedGroup], ServiceException
    + FullyQualifiedErrorId : Microsoft.Graph.ServiceException,SharePointPnP.PowerShell.Commands.Graph.GetUnifiedGroup

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @3031539 how are you?
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there.

Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @3031539 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
