### ISSUE TITLE
Get-PnPFolder Related Links are broken

### ISSUE THREAD

**Issue by cbotsikas** [MicrosoftDocs/office-docs-powershell#5309]
The link link is broken. I can only see SharePoint Developer Patterns and Practices but the href is wrong: https://aka.ms/sppnp)[Ensure-PnPFolder](https://github.com/OfficeDev/PnP-PowerShell/blob/master/Documentation/EnsureSPOFolder.md

I suppose the 'Ensure-PnPFolder' should be 'Resolve-PnPFolder' and link to https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/resolve-pnpfolder as noted on previous issues for this article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b385a5-4bb6-e858-d114-df8b6b41114f
* Version Independent ID: e9821d8f-8e0b-5939-9f3e-43bffb6a0e7b
* Content: [Get-PnPFolder (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpfolder?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFolder.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @cbotsikas 👍 how are you?

Documentation for PnP cmdlets is directly reflected from the cmdlet's source code.
So, I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there. 

Thanks

**Comment by yogkumgit** [comment]
@ Thank you very much for the contribution and sharing this explanation. @ 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by cbotsikas** [comment]
@get-itips thanks for letting me know.

Well, actually the linked command was fixed 7 days ago by @erwinvanhunen on [this commit](https://github.com/MicrosoftDocs/office-docs-powershell/commit/de8b2eb8670b24b426b4c20b4c90f2d496bbaa0a#diff-73c0513e0f82876939d34c47e4b9919d), but the broken link issue still exists and I've now noticed that **the related links are broken in all articles with more than one link** (for example [New-PnPProvisioningTemplateFromFolder](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpprovisioningtemplatefromfolder?view=sharepoint-ps#related-links), [Get-PnPFolder](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpfolder?view=sharepoint-ps#related-links)). 
This means that the [documentation generator](https://github.com/pnp/PnP-PowerShell/blob/master/CONTRIBUTING.md#documentation-contributions) has the issue and needs to add a new line between the links. If only i knew how those docs are generated I could even contribute a fix.. 
Does anyone know in which repository/project this generator belongs to so that I could either report the bug or even contribute directly?

**Comment by get-itips** [comment]
> @get-itips thanks for letting me know.
> 
> Well, actually the linked command was fixed 7 days ago by @erwinvanhunen on [this commit](https://github.com/MicrosoftDocs/office-docs-powershell/commit/de8b2eb8670b24b426b4c20b4c90f2d496bbaa0a#diff-73c0513e0f82876939d34c47e4b9919d), but the broken link issue still exists and I've now noticed that **the related links are broken in all articles with more than one link** (for example [New-PnPProvisioningTemplateFromFolder](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpprovisioningtemplatefromfolder?view=sharepoint-ps#related-links), [Get-PnPFolder](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpfolder?view=sharepoint-ps#related-links)).
> This means that the [documentation generator](https://github.com/pnp/PnP-PowerShell/blob/master/CONTRIBUTING.md#documentation-contributions) has the issue and needs to add a new line between the links. If only i knew how those docs are generated I could even contribute a fix..
> Does anyone know in which repository/project this generator belongs to so that I could either report the bug or even contribute directly?

Hello @cbotsikas how are you? The commit that added Related Links to those articles was authored by @erwinvanhunen himself so probably he knows best the engine that is used to generate it, I recommend opening an issue in the repo I referenced before. Thank you
