### ISSUE TITLE
Connect-MicrosoftTeams doesn't work with delegated permissions via Secure App Model

### ISSUE THREAD

**Issue by gavsto** [MicrosoftDocs/office-docs-powershell#5313]
We're an MSP that uses delegated partner permissions to connect to all the 365 environments we support. The methods available in this cmdlet don't seem to work:

Example:

Connect-MicrosoftTeams -TenantId "OurClientsTenantID" -AadAccessToken $aadGraphToken -MsAccessToken $graphToken -AccountID "UPN"

Does not generate an error when I run it. If I then run Get-Team:

Get-Team : Error occurred while executing 
Code: InvalidAuthenticationToken
Message: CompactToken parsing failed with error code: 80049217
InnerError:
  RequestId: 13dcb45f-9fca-42f1-85fc-c884b438e745
  DateTimeStamp: 2020-04-17T09:01:44
HttpStatusCode: InvalidAuthenticationToken

I've spoken to a number of key people who run delegated Powershell in the same way and no-one has been able to get this working. What are my options here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ee082c9-735d-3f8a-7bc4-b2d4f175c784
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hi @gavsto Gavin, just wanted you to know that I am testing this and I will get back to you.

**Comment by get-itips** [comment]
Hello @gavsto Gavin, I tested this and the only way it worked for me was when using application type permissions and not delegated ones.
@tameemansari can you kindly shed some light here? I appreciate.

**Comment by tameemansari** [comment]
Give us a bit of time and we will repro this to identify and report back here.

**Comment by get-itips** [comment]
> Give us a bit of time and we will repro this to identify and report back here.

Thanks @tameemansari

**Comment by get-itips** [comment]
@tameemansari Can you kindly tell me if you have any updates on the repro? Thank you

**Comment by tameemansari** [comment]
Sorry for the delay. Right now we have side effects and issues when partner delegated auth calls occur from our cmdlets. We should be looking to address this before Ignite'20.

**Comment by gavsto** [comment]
@tameemansari Are you suggesting that this is not going to be fixed until September 2020? I currently have absolutely no method to manage our clients teams programmatically at the moment and I know I'm not the only one in this boat.

Please consider attaching a higher priority to this.

**Comment by get-itips** [comment]
@tameemansari Thanks for sharing your feedback and confirming this is known by the product team.

**Comment by KelvinTegelaar** [comment]
I'm completely agreeing with @gavsto. I've made some other bug reports for the graph API for the teams endpoints. Its near impossible to do anything in a completely automated fashion right now.

**Comment by get-itips** [comment]
Hello everyone
Now that we could reach someone from the product team and have confirmation that they are aware of this and they are working on it, as I do not identify any change is needed to current article, we need to proceed closing this for now.
Thank you

**Comment by tameemansari** [comment]
Thanks @gavsto and @KelvinTegelaar for sharing this feedback. If I had an earlier date which I can promise I would have done that. Will do my best to work with the team to push the priority.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @gavsto 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
