### ISSUE TITLE
set-teampicture for team which i am not owner

### ISSUE THREAD

**Issue by alexsoft-pl** [MicrosoftDocs/office-docs-powershell#5317]
I need to set pictures for teams, which i am not owner.
i try to get token (i want use application with delegated rights:
$ReqTokenBody = @{
    Grant_Type    = "Password"
    client_Id     = $clientID
    Client_Secret = $clientSecret
    Username      = $Username
    Password      = $Password
    Scope         = "Group.ReadWrite.All"
} 
$TokenResponse = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$TenantName/oauth2/v2.0/token" -Method POST -Body $ReqTokenBody

then logging to microsoftteams:
Connect-MicrosoftTeams -MsAccessToken $tokenresponse.access_token -AadAccessToken $tokenresponse.access_token -AccountId solarz@office.wit.edu.pl

but if i try to set picture:
set-teampicture : Error occurred while executing
Code: ErrorGroupsAccessDenied
Message: User does not have permissions to execute this action.
InnerError:
  RequestId: 0716a080-4e4a-49b1-8d17-8a373dfe2fc8
  DateTimeStamp: 2020-04-17T16:19:25
HttpStatusCode: ErrorGroupsAccessDenied
At line:1 char:1
+ set-teampicture -groupid dcb9d7d4-a7a0-42f4-9b84-0f4023cab762 -imagep ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-TeamPicture], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdle
   ts.PowerShell.Custom.SetTeamPicture

i have no right to do it - specified application has delegated Group.ReadWrite.All so i am confused what i am doing wrong.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Related to https://github.com/MicrosoftDocs/office-docs-powershell/issues/5313

**Comment by get-itips** [comment]
What do u think @tameemansari ? I appreciate

**Comment by tameemansari** [comment]
Investigating !

**Comment by get-itips** [comment]
> Investigating !

@tameemansari please tell me if the same answer for https://github.com/MicrosoftDocs/office-docs-powershell/issues/5313 applies here, which I think it does. Thank you

**Comment by get-itips** [comment]
@alexsoft-pl Please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/5313#issuecomment-621580808

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @alexsoft-pl 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
