### ISSUE TITLE
Microsoft.Exchange.Data.DataValidationException: DateFormat "M/d/yyyy" isn't valid for current language setting "en-GB". Valid formats include "dd/MM/yyyy, dd/MM/yy, d/M/yy, d.M.yy, yyyy-MM-dd".

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/office-docs-powershell#5318]
I received the following error when trying to switch Language from 'en-GB' to 'en-US':
Microsoft.Exchange.Data.DataValidationException: DateFormat "M/d/yyyy" isn't valid for current language setting "en-GB". Valid formats include "dd/MM/yyyy, dd/MM/yy, d/M/yy, d.M.yy, yyyy-MM-dd".

I found this could be resolved by adding -DateFormat $null and -TimeFormat $null, which appeared to allow the default for the en-US locale to be used.

Can this trick be documented, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4acd15e-7bab-4251-dbcb-a075611fcdef
* Version Independent ID: 90b61091-8343-7071-e56d-d963096e3f37
* Content: [Set-MailboxRegionalConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-mailboxregionalconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-MailboxRegionalConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-MailboxRegionalConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @ChrisAtMAF, thank you for your feedback.

DateFormat parameter description includes the following sentence: "The DateFormat parameter specifies the date format based on the current or specified language for the mailbox.". TimeFormat has a very similar description.
Each language has its corresponding valid values for DateFormat and TimeFormat as the description states.

The description includes a link with some more information:
"For more information about the date format strings, see [Standard Date and Time Format Strings](https://go.microsoft.com/fwlink/p/?LinkId=784852)."

Also, error message is self-explanatory, so for each language you will get valid values if the actual value is not included.

I think adding information about all the valid values for each language will make the article very extensive and won't add real value.

I will be glad to hear if you agree or not.

Thanks!

**Comment by ChrisAtMAF** [comment]
Hi @dariomws. I'm not sure I explained it properly. When running this command to switch *language* between en-gb and en-us

Set-MailboxRegionalConfiguration -Identity "Marcelo Teixeira" -Language en-us

the error occurs. This is because the *default* value for DateFormat under en-us (M/d/yyyy) is not supported under en-gb (which only supports dates with the day first like dd/MM/yyyy or similar)

As a multinational we perform a lot of language shifts. We don't mind which DateFormat or TimeFormat is selected for a particular language - we just want it to work. But if we run the command above, we get a lot of errors.

The options are:
1) Find out a valid DateFormat and TimeFormat for each language setting and hardcode it in
or
2) Set DateFormat and TimeFormat to $null, which appears to tell Set-MailboxRegionalConfiguration to use the default dependent on the Language.

The second is much more convenient when running a script that sets lots of *different* languages. Hence why it would be helpful if the documentation mentioned that this was possible.

**Comment by dariomws** [comment]
I have added the word valid to the description of these parameters, and also an example to set new language with default values for Date, Time and Folders.

**Comment by ChrisAtMAF** [comment]
@dariomws Thanks. Can't see the updates yet but maybe takes some time to appear?

**Comment by dariomws** [comment]
Hi @ChrisAtMAF, it could take some days. Once the Pull Request gets approval, it should be 24hs.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @ChrisAtMAF Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
