### ISSUE TITLE
EXAMPLE 7

### ISSUE THREAD

**Issue by taIConX** [MicrosoftDocs/office-docs-powershell#5319]
Parameter -RowFilter is incorrect, should be corrected to -RowLimit in example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8b96547-c659-bdf3-a6b6-69a2c94689fc
* Version Independent ID: b9aa6d28-19b9-ab4e-1b45-2f1f9629a2c8
* Content: [Get-PnPSearchCrawlLog (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpsearchcrawllog?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSearchCrawlLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSearchCrawlLog.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @taIConX 👍 how are you?

Documentation for PnP cmdlets is directly reflected from the cmdlet's source code.
So, I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues. PnP cmdlets are maintained by the community, a member of it will pick it up there. Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @taIConX 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
