### ISSUE TITLE
Basic auth disable 

### ISSUE THREAD

**Issue by ganlbarone** [MicrosoftDocs/office-docs-powershell#5322]
So the end date has been extended which is good. 

My question here is I heard exo ps sessions are in scope. Will we expect them to break when this change does come through? We have a lot of automation that revolves around using these cmdlets. We also are an Okta customer and disabled legacy Auth long ago so trying to figure out if we are going to have any issue when this does come to pass. 

Using MFA obviously doesn’t work for back end script processes. 

Ty

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @ganlbarone, thank you for your feedback.

If you have Basic Authentication disabled, you are using a connection method (Connect-EXOPSSession or Connect-ExchangeOnline) that uses Modern Authentication on your scripts. In this case, you should not have any issue.

I think you have read this article:
https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-auth-and-exchange-online-february-2020-update/ba-p/1191282

Anyway, a good idea would be to start thinking/preparing your scripts to work with Certificate Based Authentication or Exchange PowerShell V2 (Connect-ExchangeOnline).

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @ganlbarone 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
