### ISSUE TITLE
Error executing new-team

### ISSUE THREAD

**Issue by jklappdev** [MicrosoftDocs/office-docs-powershell#5325]
new-team  was working until about mid-day 4/17/2020.
Around 3pm it stopped working. Not sure if its something in my tenant.
Here is the error:
PS C:\WINDOWS\system32> new-team -DisplayName zzzJKLteamstester1                                                        new-team : Error occurred while executing
Code: BadGateway
Message: Failed to execute backend request.
InnerError:
  RequestId: 0fc85517-0720-4a54-9e6d-aeb12750296c
  DateTimeStamp: 2020-04-18T09:55:18
HttpStatusCode: BadGateway
At line:1 char:1
+ new-team -DisplayName zzzJKLteamstester1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-Team], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdle
   ts.PowerShell.Custom.NewTeam

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by jklappdev** [comment]
This is working now. Not sure if it was an issue at MS or with the
command.  Did you do anything to fix it?

**Comment by get-itips** [comment]
Hello @jklappdev How are you?
As here we are limited to documentation changes, I tried to reproduce to see if we had to impact any documentation but could not, it was probably a transient error.
If this issue appears again for you, I kindly suggest to open a support ticket in your tenant.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @jklappdev 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
