### ISSUE TITLE
incorrect examples

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#5328]
Issues with this article:
1) HTML-header is "Get-CsOnlineUser" instead of expected "New-CsOnlineVoiceRoutingPolicy"
2) Both examples use parameter "Name", but it is not listed a valid parameter for this cmdlet
3) Punctuation can be better in the description of "OnlinePstnUsages" parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62458ec-41d4-06c2-ff1c-72ee763f20fa
* Version Independent ID: fe3dc8ab-7716-32b2-1205-1195e6acbe61
* Content: [New-CsOnlineVoiceRoutingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinevoiceroutingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineVoiceRoutingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineVoiceRoutingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @shivtorov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
