### ISSUE TITLE
unclear "Global" parameter

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#5329]
Issues with this article:
1) HTML-header is "Get-CsOnlineUser" instead of expected "Grant-CsOnlineVoiceRoutingPolicy"
2) All examples are for 1st parameter set. There are no examples for the 2nd parameter set. An example for "-Global" parameter is desirable
3) Description of "Global" parameter is not clear. For example, does it mean it applies to all current users, or also covers all future users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d10ef8a-b9c7-e8a3-5457-25cb192ce92c
* Version Independent ID: 8d1e09fa-7896-56e8-c294-8cac6c35d8d3
* Content: [Grant-CsOnlineVoiceRoutingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @shivtorov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
