### ISSUE TITLE
Broken note syntax

### ISSUE THREAD

**Issue by connordoner** [MicrosoftDocs/office-docs-powershell#5330]
The note-type blockquote at the top of the page is broken.

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b039edde-abde-fc2a-b388-c6a74b3e7e1a
* Version Independent ID: 62f38668-1c72-a555-18f9-b4520863db07
* Content: [New-SafeAttachmentPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/new-safeattachmentpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/advanced-threat-protection/New-SafeAttachmentPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/advanced-threat-protection/New-SafeAttachmentPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
Known issue. Looking into it.

Thanks for the feedback.

Closing.
