### ISSUE TITLE
Connect-MicrosoftTeams from Microsoft Teams PowerShell does not work on Azure Automation

### ISSUE THREAD

**Issue by AndrewCi** [MicrosoftDocs/office-docs-powershell#5331]
I am attempting to connect to Microsoft Teams using Azure Automation. I am using the following code in Azure Automation PowerShell Runbook.

```
# Get the credential from Automation  
$credential = Get-AutomationPSCredential -Name 'O365'  
$userName = $credential.UserName  
$securePassword = $credential.Password  
  
$psCredential = New-Object –TypeName System.Management.Automation.PSCredential –ArgumentList $userName, $securePassword  
 
# Connect to Microsoft Teams  
Connect-MicrosoftTeams -Credential $psCredential
```

I receive the following error:

```
Connect-MicrosoftTeams : One or more errors occurred.: Object reference not set to an instance of an object.
At line:9 char:1
+ Connect-MicrosoftTeams -Credential $psCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
 
Connect-MicrosoftTeams : One or more errors occurred.
At line:9 char:1
+ Connect-MicrosoftTeams -Credential $psCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AggregateException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
 
Connect-MicrosoftTeams : Object reference not set to an instance of an object.
At line:9 char:1
+ Connect-MicrosoftTeams -Credential $psCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AdalException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
 
Connect-MicrosoftTeams : Object reference not set to an instance of an object.
At line:9 char:1
+ Connect-MicrosoftTeams -Credential $psCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], NullReferenceException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
 
Connect-MicrosoftTeams : One or more errors occurred.: Object reference not set to an instance of an object.
At line:9 char:1
+ Connect-MicrosoftTeams -Credential $psCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MicrosoftTeams], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Open.Teams.CommonLibrary.AadAuthenticationFailedException,Microsoft.Open.Teams.C
ommonLibrary.ConnectMicrosoftTeams
```

When I run a simple 'Connect-MicrosoftTeams' locally it works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ee082c9-735d-3f8a-7bc4-b2d4f175c784
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @AndrewCi Andrew, how are you?
As here we are limited to documentation fixes, I tested your scenario in my lab to verify if we need to maybe add a note in the article. I successfully connected and ran Get-Team from an azure runbook.
Hope this info helps you.

**Comment by get-itips** [comment]
Forgot to recommend to open a support ticket directly in your tenant in case you still face issues.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @AndrewCi 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by AndrewCi** [comment]
> Hello @AndrewCi Andrew, how are you?
> As here we are limited to documentation fixes, I tested your scenario in my lab to verify if we need to maybe add a note in the article. I successfully connected and ran Get-Team from an azure runbook.
> Hope this info helps you.

can you share your connection code? it's still not working for me

**Comment by AndrewCi** [comment]
> @get-itips Thank you very much for the contribution and sharing this explanation. @AndrewCi
> Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

can you please re-open this issue? it's not resolved.

**Comment by get-itips** [comment]
> can you share your connection code? it's still not working for me. i believe something needs to be added to the documentation to illustrate the different between prompted connection and programmatic connection.

Hello, it is no different from what you are doing I think.

```
$credential = Get-AutomationPSCredential -Name '365Demo'  
$userName = $credential.UserName  
$securePassword = $credential.Password  
  
$psCredential = New-Object –TypeName System.Management.Automation.PSCredential –ArgumentList $userName, $securePassword  
 
Connect-MicrosoftTeams -Credential $psCredential

Get-Team
```

If you still face issues, I would recommend reinstalling the module into the automation account and/or opening a support ticket directly in your tenant.

Hope this info helps you.

**Comment by irideostriches** [comment]
@AndrewCi Did you get get a resolution for this? I'm running into the same problem.
