### ISSUE TITLE
DisableFacebook:$false

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/office-docs-powershell#5332]
I have successfully disabled Facebook integration with DisableFacebook however I'm not able to roll back the change with DisableFacebook:$false. 

I'm getting WARNING: The command completed successfully but no settings of 'OwaMailboxPolicy-Default' have been modified. Nothing happens and I'm not able to change the value to true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ca7906-9f33-2991-9da9-a626e5e45c46
* Version Independent ID: 5f388b3c-fb47-f7a0-e648-07cb3e59cf72
* Content: [Set-OwaMailboxPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-owamailboxpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-OwaMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @zlDev, thank you for your feedback.

Please, check this support KB:
https://support.microsoft.com/help/2898124/you-can-t-disable-facebook-contact-sync-for-your-office-365-organizati

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @zlDev 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
