### ISSUE TITLE
PrivacyStatementURL not accepted?

### ISSUE THREAD

**Issue by Jens-Lorenz** [MicrosoftDocs/office-docs-powershell#5339]
When setting the parameter for -PrivacyStatementURL I get an error:
"A parameter cannot be found that matches parameter name 'PrivacyStatementUrl'"
I can see the parameter exists with Get-OMEConfiguration (and is empty). Can this not be configured yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aabcc26e-242d-1342-24af-a419a129e91d
* Version Independent ID: 110aa234-6fb0-ff5c-fe5c-10b86147b9ce
* Content: [Set-OMEConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/set-omeconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @Jens-Lorenz, thank you for your feedback.

This parameter is working on my lab tenant:
![image](https://user-images.githubusercontent.com/33589238/80032890-3707c780-84c2-11ea-80b1-db8a42bfa73d.png)

Have in mind that you need Global Admin, Exchange Organization Management, or Exchange Compliance Management roles to run this cmdlet.

**Comment by Jens-Lorenz** [comment]
Hi! I have tried this setting in my test-tenant and in our production tenant and I get the same error in both. I have use an account with global admin permissions.

Test-tenant:
<img width="1110" alt="test-tenant" src="https://user-images.githubusercontent.com/39763894/80065401-593d2c00-853a-11ea-8a93-2d8dcb6f2314.png">

Prod-tenant:
<img width="1111" alt="prod-tenant" src="https://user-images.githubusercontent.com/39763894/80065442-6823de80-853a-11ea-866b-e4e0e8421993.png">

Possibly not hit the tenants yet? (We do have private previews active in both tenants as well, whould this be an explanation...)

**Comment by dariomws** [comment]
Hi!

What happen if you try to complete the parameter using tab? Both Identity and PrivacyStatementUrl.

Also, try with "Get-Command Set-OMEConfiguration".

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @Jens-Lorenz 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Jens-Lorenz** [comment]
Hi! Just as the last comment: when I use tab, it does not complete and the same error happens with the Get-Command | Set-OME Command. I guess I'd better open a support ticket, as this is not a documentation issue but a technical one. Cheers
