### ISSUE TITLE
What is a Knowledge Hub Site?

### ISSUE THREAD

**Issue by kasperbolarsen** [MicrosoftDocs/office-docs-powershell#5344]
I haven't been able to find a definition for a Knowledge Hub Site so perhaps it would be a good idea to add a link to a page that defines this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d419245e-4684-fd57-8353-a4303adb0c05
* Version Independent ID: 28ab402e-1cac-83a0-f512-d4cadfe40987
* Content: [Get-PnPKnowledgeHubSite (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpknowledgehubsite?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPKnowledgeHubSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPKnowledgeHubSite.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello Kasper @kasperbolarsen How are you?

PnP documentation is directly reflected from cmdlet's source code.
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues/questions. PnP cmdlets are maintained by the community, a member of it will pick it up there.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @kasperbolarsen Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
