### ISSUE TITLE
-ImmutableId description has a double-up paragraph.

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#5347]
Just FYI.  Looks like the paragraph was copy/pasted and reworded slightly but the original paragraph was left in place too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb103c0b-9021-3a77-0bf6-601df9a0fe38
* Version Independent ID: 561d8c53-5019-4a31-efa1-c2b635818f5a
* Content: [New-RemoteMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/new-remotemailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/New-RemoteMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/New-RemoteMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @JeremyTBradshaw Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
