### ISSUE TITLE
What does -Force do?

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/office-docs-powershell#5350]
I have not seen "Force" used in a "Get-" command before. Can you add an example of when we should use this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4504ef6f-28cd-bf4e-bf26-02a0acf292b8
* Version Independent ID: 7a12f628-6004-f100-4112-a95f4d4df8ff
* Content: [Get-CsOnlineDialInConferencingUserInfo (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguserinfo?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialInConferencingUserInfo.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUserInfo.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @NickDorak, thank you for your feedback.

I agree with you, I think this parameter is not useful here. I´m suggesting an update, let´s see if it gets approval.

**Comment by yogkumgit** [comment]
@tomkau Please merge this PR #5421

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @NickDorak Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
