### ISSUE TITLE
Is there a -ResultSize option like other O365 PS commands?

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/office-docs-powershell#5351]
How do I specify to return all results?
Other O365 PS commands use the "-ResultSize Unlimited" or "-All". 
The only option above is the "-First", however it generates an warning if you specify more than are available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4504ef6f-28cd-bf4e-bf26-02a0acf292b8
* Version Independent ID: 7a12f628-6004-f100-4112-a95f4d4df8ff
* Content: [Get-CsOnlineDialInConferencingUserInfo (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguserinfo?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialInConferencingUserInfo.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUserInfo.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @NickDorak, thank you for your feedback.

Yes, as you noticed, there is no -ResultSize or -All in this cmdlet. Did you experience a limitation to list all your users that have been enabled for audio conferencing?

Besides -First, with -Skip, -SearchQuery, -Select and -Filter you can filter the cmdlet result.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @NickDorak 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by NickDorak** [comment]
@dariomws 
We noticed the scripts working when web had less than 100 users. Once more people were onboarded, the script didn't fall or produce warning, it just didn't run against any more. 
I did try -Select with a large number, but if you specify more than you have it produces a warning message.
Seems there is no way to get a clean output of all users.

**Comment by dariomws** [comment]
@NickDorak Did you try with "-First 1000"? The default value for his parameter is 100.

**Comment by dariomws** [comment]
@NickDorak You should use the parameter -First to return more than 100 users. Please check:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3745

**Comment by NickDorak** [comment]
@dariomws , sorry I reviewed my code, I was actually using the -Frist (not -Select), and it throws a warning if you specify more than there are existing users.

**Comment by dariomws** [comment]
@NickDorak don't worry. I think you should try with "-Select DialInConferencingOn". In this way, you will list all the users.

**Comment by dariomws** [comment]
@NickDorak, I think there is no document update required, so we are going to close this issue.

Thanks!

**Comment by NickDorak** [comment]
Using -Select without -First, always only provided 100 results.

**Comment by NickDorak** [comment]
The warning message when using -First but more than the exact amount of users is:

> WARNING:  No more online conferencing users available for tenant 11111111-1111-1111-1111-111111111111

**Comment by dariomws** [comment]
> Using -Select without -First, always only provided 100 results.

Yes, the default value for -First is 100. You need to specify it to get more results.
