### ISSUE TITLE
The example 1 is not correct .

### ISSUE THREAD

**Issue by SultanRayes** [MicrosoftDocs/office-docs-powershell#5360]
Hello , 
Please review the example above. I have tried it the LAB and I got error.
While the below syntax workd:
New-EcpVirtualDirectory -WebSiteName 'Default Web Site' -Role ClientAccess -Server SERVERNAME

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cd25dbd-9d0a-cba4-6e1d-4856c2d59c0b
* Version Independent ID: 6d2daecd-9a53-1b39-90fa-6ba90b52c02e
* Content: [New-EcpVirtualDirectory (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access-servers/new-ecpvirtualdirectory?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access-servers/New-EcpVirtualDirectory.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access-servers/New-EcpVirtualDirectory.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @SultanRayes, thank you for your feedback.

In my lab, I have tried removing the ECP virtual directory and then, I ran this command. It works for me, I could recreate the ECP virtual directory.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @SultanRayes 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
