### ISSUE TITLE
Set-DlpSensitiveInformationType - Example 3 -  command not working

### ISSUE THREAD

**Issue by golubenkoff** [MicrosoftDocs/office-docs-powershell#5361]
Hi, Trying to add new fingerprint template files to existing SensitiveInformationType - it is not working - shows no error and not adding
it is only working when  replacing existing with new data but not when adding new to existing - here is my code: 
( scc - is my prefix for commands in Session)
```powershell
$TemplatesFolder = "C:\Scripts\O365\templates_uib\upload\"
$myORG_Fingerprints = Get-SccDlpSensitiveInformationType "myORG Document Fingerprints Package";
$Array             = [System.Collections.ArrayList]($myORG_Fingerprints.Fingerprints); 

foreach ($File in $(gci $TemplatesFolder)){
Write-Host "Processing: " -ForegroundColor DarkGray -NoNewline ; Write-Host $File.Name -ForegroundColor Cyan
    $Template    = $null ; $Template    = get-content $File.FullName -Encoding Byte -ReadCount 0
    $FingerPrint = $null ; $FingerPrint = New-SccDlpFingerprint -FileData $Template -Description "myORG DLP - $($File.Name)"
     $Array.Add($FingerPrint[0]); 
	 }
Set-SccDlpSensitiveInformationType $myORG_Fingerprints.Identity  -Fingerprints $Array -Verbose
```
when creating empty array without existing data - it is working but replacing everything - i need just add new to existing

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @golubenkoff, thank you for your feedback.

I tested it and this example works for me:
![image](https://user-images.githubusercontent.com/33589238/80009645-bb951e80-849f-11ea-8590-bd0194f37684.png)

Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by golubenkoff** [comment]
Hi, yes command working without errors but it is not adding new template to existing....  trying to get-.. after all - and no changes at all. Ticket opened today - but may be here it will be more productive:)

**Comment by dariomws** [comment]
We are here to help improve docs.microsoft.com. I think the example works according to my testing, the "piece of code" you wrote above is a little different. This is why I think you need to contact support.

Hope you understand. Thanks!

**Comment by golubenkoff** [comment]
Ok. Docs is ok :) thanks for help :)
