### ISSUE TITLE
False error message with false "SPOSiteSwap -sourceURL"

### ISSUE THREAD

**Issue by MrDTeach** [MicrosoftDocs/office-docs-powershell#5362]
False error message with false "SPOSiteSwap -sourceURL"

I have the following false error message:

I tried to Swap the main site of my SharePoint Online.
This was the command:
“Invoke-SPOSiteSwap -SourceUrl https://xyz.sharepoint.com/site/NewRootSite -TargetUrl https://xyz.sharepoint.com/search -ArchiveUrl https://xyz.sharepoint.com/sites/OldRootSite -Force”

The Mistake was in the -SourceURL part. “…/site/..” not “…/sites/…”.

The problem is I got a message that told me to perform the “Page Diagnostic Tool” and not something like “The -SourceURL was not found”.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @MrDTeach how are you? Hope you are doing great.
Thanks for your feedback, however, here, we can only make changes or fixes to documentation, for suggested changes to cmdlets behavior or error messages I need to kindly suggest visit [SharePoint UserVoice](https://sharepoint.uservoice.com/).
Hope this information helps you.

**Comment by yogkumgit** [comment]
@MrDTeach  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
