### ISSUE TITLE
New-CsTeamsFeedbackPolicy not documented

### ISSUE THREAD

**Issue by arifC** [MicrosoftDocs/office-docs-powershell#5364]
Please extend the SfBO PowerShell documentation by adding the Cmdlets around Teams feedback policies as described here: https://docs.microsoft.com/en-us/microsoftteams/manage-feedback-policies-in-teams

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @arifC  thanks for noticing and reporting, created a PR including the missing article.

**Comment by get-itips** [comment]
PR has been merged, we can close this now @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @arifC Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
