### ISSUE TITLE
Unable to install the latest MicrosoftTeams Powershell Version 1.0.21 

### ISSUE THREAD

**Issue by lovecmd** [MicrosoftDocs/office-docs-powershell#5368]
Description: Unable to install the latest MicrosoftTeams version 1.0.21 using powershell 5.1

https://www.poshtestgallery.com/packages/MicrosoftTeams/1.0.21

Install-Module -Name MicrosoftTeams -RequiredVersion 1.0.21-> does not work
![UnableToInstallTeamPS1 0 21](https://user-images.githubusercontent.com/64166871/80031152-4c2b2900-84b7-11ea-8d97-d3512d3351c2.JPG)

Install-Module -Name MicrosoftTeams -> installs version 1.0.6, I need version 
https://www.powershellgallery.com/packages/MicrosoftTeams/1.0.6
![Installs1 0 6Teams](https://user-images.githubusercontent.com/64166871/80031298-7a106d80-84b7-11ea-857c-8e2d034c8a29.png)

Add-TeamChannelUser is not available in 1.0.6, Thus, I am trying to install 1.0.21.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@lovecmd 
How are you?
The version you are trying to install is the Teams _Beta_ module and has a different procedure to install, you can follow the steps [here](https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management#teams-powershell-module).

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @lovecmd 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by lovecmd** [comment]
Hi All,

Thank you that worked.

**Comment by lovecmd** [comment]
Thank you all. Those instructions have succesfully helped me.

**Comment by get-itips** [comment]
@lovecmd Glad to hear!
@yogkumgit Please close
