### ISSUE TITLE
Error: Cannot find resource for the request SiteRenameJobs

### ISSUE THREAD

**Issue by philipdac** [MicrosoftDocs/office-docs-powershell#5373]
I run the command "Start-SPOSiteRename -Identity $url -NewSiteUrl $NewSiteUrl -NewSiteTitle $NewSiteTitle -SuppressMarketplaceAppCheck -SuppressWorkflow2013Check" and got the below error. Please suggest if you have any experiences on this error. Thanks.

-------------------------------
CorrelationId: 7d7e4b9f-f049-0000-534a-f33b42d20cbc
Start-SPOSiteRename : Error Code: -1, Microsoft.SharePoint.Client.ResourceNotFoundException,Cannot find resource for the request SiteRenameJobs.
At line:1 char:1
+ Start-SPOSiteRename -Identity $url -NewSiteUrl $NewSiteUrl -NewSiteTi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-SPOSiteRename], Exception
    + FullyQualifiedErrorId : Error Code: -1, Microsoft.SharePoint.Client.ResourceNotFoundException,Cannot find resource for the request SiteRenameJobs.,Microsoft.Online.SharePoint.PowerShell.StartSPOSiteRename

Start-SPOSiteRename : Something is wrong, please check your parameters and retry later.
At line:1 char:1
+ Start-SPOSiteRename -Identity $url -NewSiteUrl $NewSiteUrl -NewSiteTi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-SPOSiteRename], Exception
    + FullyQualifiedErrorId : Something is wrong, please check your parameters and retry later.,Microsoft.Online.SharePoint.PowerShell.StartSPOSiteRename

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @philipdac Philip, how are you? AFAIK that is still a preview feature, besides that, I would suggest opening a support ticket directly in your tenant as here we are limited to documentation fixes.
Thank you

**Comment by philipdac** [comment]
@get-itips Thank you for your response. I was able to rename the site via SharePoint admin center so that you can close the issue now.
Btw, please let me know how to raise a ticket in my tenant, if it is within your spaces.
