### ISSUE TITLE
Clarify the documentation for the -PolicyScopeGroupID parameter and whether Shared Mailboxes can be scoped

### ISSUE THREAD

**Issue by stukey** [MicrosoftDocs/office-docs-powershell#5375]
Please clarify the documentation for the -PolicyScopeGroupID parameter. The documentation implies that it is not possible to scope access to non-user mailboxes (e.g. Shared Mailboxes, Resource Mailboxes, etc.) because the -PolicyScopeGroupID parameter only accepts recipients that are security principals (it states “The following types of recipients are not security principals, so you can't use them with this parameter: Discovery mailboxes, Dynamic distribution groups, Distribution groups, Shared mailboxes”). I understand that the documentation is stating that the recipient you specify via the -PolicyScopeGroupID parameter must be a security principal. However, in my testing, you can still scope a Graph app’s access to Shared Mailboxes by creating a mail-enabled security group and then adding the Shared Mailboxes to said group. If the App Access Policy is configured with the scope set to the security group, then the App’s access is restricted/denied according to the group membership, including any Shared Mailboxes. Hopefully this is the intended and supported behaviour, because we certainly need to be able to scope access to non-user mailboxes via Graph API. If so, then please update the documentation to make it clear that non-user mailboxes can still be scoped by including them in a security group and configuring the scope of the app policy as the group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1e6041b-99ca-612b-24d6-053fca4ac717
* Version Independent ID: c18596aa-b54c-1b19-6064-952ae2468d41
* Content: [New-ApplicationAccessPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/new-applicationaccesspolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/organization/New-ApplicationAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/organization/New-ApplicationAccessPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @stukey, thank you for your feedback.

I will check if it´s supported and give you feedback.

**Comment by dariomws** [comment]
@stukey I have been thinking about this... and I think the description is ok.

You cannot or you won´t assign permissions to not valid security principals. In the case of a shared mailbox (for example support@domain.com), the account password is not known by anyone. So, you cannot or you won´t use this account to authenticate to services or applications.
If you run:
Get-Recipient -Identity support | Select-Object IsValidSecurityPrincipal
You will see it´s not a valid security principal.
If you convert the shared mailbox to user mailbox and run the same command, you will see it´s a valid security principal.
I think that you will give permissions to services or apps to the user mailboxes that are members of a shared mailbox, not to the shared mailbox itself.

More information about security principals:
https://docs.microsoft.com/powershell/module/exchange/users-and-groups/get-securityprincipal

**Comment by stukey** [comment]
Thanks @dariomws. I totally understand your comments, and that shared mailboxes aren’t security principals so cannot be the target of the PolicyScopeGroupId parameter. I just wanted to make it clearer in the documentation that you can still scope an applications’s Graph API access to shared mailboxes by adding the mailboxes as members of a mail-enabled security group and then setting the security group as the target of the policy! I had a small heart attack when I looked at the updated documentation and read the sentence about not being able to use shared mailboxes. Maybe a note in the cmdlet introductory comments to highlight the possibility. For example, we are migrating all of our apps from basic auth to modern auth (as are many of your customers) and the majority of our apps only need access to a few shared mailboxes each, so we are going to use scoped Graph API App Policies to limit the access to said shared mailboxes.

**Comment by dariomws** [comment]
@stukey, ok, I misunderstood it. Sorry about that. I agree with you now, I will add a note. 

If you can, please check it.

Thanks!

**Comment by stukey** [comment]
@dariomws Thank you. Looks good to me. I think that will really help many other customers!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @stukey Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
