### ISSUE TITLE
Info on Throttling if issuing this Grant command on thousands of users

### ISSUE THREAD

**Issue by vicslive** [MicrosoftDocs/office-docs-powershell#5378]
I see some misspelling on the page, instead of teamsupgrade.csv says teasupgrade.csv , small things, anyway, where can we find info about throttling if issuing these to thousands of users at once ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0dd44c-bfc9-5f82-68c4-7b469129e8a5
* Version Independent ID: ea015ee3-54e2-e402-d533-c8a9a15557e8
* Content: [Grant-CsTeamsUpgradePolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsupgradepolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @vicslive, thank you for your feedback. Small or big things, we are always happy to receive feedback to improve docs.microsoft.com.

I´m not sure if I understood the question but I think you are looking for something like:
https://docs.microsoft.com/powershell/module/teams/new-csbatchpolicyassignmentoperation

Please, have in mind that this cmdlet is currently in public preview. Test it carefully.

**Comment by yogkumgit** [comment]
@tomkau Please merge this PR #5420

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @vicslive Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
