### ISSUE TITLE
Update description

### ISSUE THREAD

**Issue by rramdoyal** [MicrosoftDocs/office-docs-powershell#5381]
Update description for the parameter
-ChannelsInChatListEnabledType

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c1fc1a-c9b4-a9bc-47c4-7cd3488fece7
* Version Independent ID: 8102a7bb-e0ef-0f8b-b9b8-67a45ecf076f
* Content: [New-CsTeamsMessagingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmessagingpolicy?view=skype-ps&source=docs)
* Content Source: [skype/skype-ps/skype/New-CsTeamsMessagingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsMessagingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @rramdoyal, thank you for your feedback.

I´m going to try to get more information about this parameter. @tomkau could you kindly help? Thanks!

**Comment by dariomws** [comment]
@tomkau could you kindly help? Thanks!

**Comment by pupara** [comment]
Thanks @dariomws and @yogkumgit. I will find the description and get it updated on the page.

**Comment by dariomws** [comment]
Hi @pupara,

Could you find the description?

Thanks!

**Comment by dariomws** [comment]
Hi @pupara,

Could you find the description?

Thanks!

**Comment by dariomws** [comment]
@yogkumgit it was fixed on the following PR:
https://github.com/MicrosoftDocs/office-docs-powershell/pull/6775

Please close it. Thanks!
