### ISSUE TITLE
Can we associate Remote Event Receiver to document Library

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/office-docs-powershell#5382]
I have multiple document libraries and would like to associate event receiver to each libraries. Is this supported by PnP template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8b1360-5133-03ea-c4de-97d7280ef82c
* Version Independent ID: f7354bf2-01b5-c097-3590-326761cc7f20
* Content: [Apply-PnPProvisioningTemplate (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/apply-pnpprovisioningtemplate?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Apply-PnPProvisioningTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Apply-PnPProvisioningTemplate.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ravick4u  how are you ? 👍 

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues/questions. PnP cmdlets are maintained by the community, a member of it will pick it up there. Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ravick4u 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
