### ISSUE TITLE
Passing array of Visitors/Members/Owners

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/office-docs-powershell#5383]
Is there a way I can pass array of Visitors/Members/Owners to the template?

Currently I can pass individual users like below but with real time scenario its dynamic.

      &lt;pnp:Security AssociatedOwnerGroup="{sitetitle} Owners" AssociatedMemberGroup="{sitetitle} Members" AssociatedVisitorGroup="{sitetitle} Visitors"&gt;
        &lt;pnp:AdditionalOwners&gt;
          &lt;pnp:User Name="{parameter:Owner1}" /&gt;
          &lt;pnp:User Name="{parameter:Owner2}" /&gt;
        &lt;/pnp:AdditionalOwners&gt;
        &lt;pnp:Permissions /&gt;
      &lt;/pnp:Security&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8b1360-5133-03ea-c4de-97d7280ef82c
* Version Independent ID: f7354bf2-01b5-c097-3590-326761cc7f20
* Content: [Apply-PnPProvisioningTemplate (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/apply-pnpprovisioningtemplate?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Apply-PnPProvisioningTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Apply-PnPProvisioningTemplate.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
No, but you could build your XML injecting the AdditionalOwners element as needed.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @ravick4u 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
