### ISSUE TITLE
Example description

### ISSUE THREAD

**Issue by giveitaGo** [MicrosoftDocs/office-docs-powershell#5390]
1. The description for the second example is wrong. It says that it adds the site to the hub. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a34e81-3375-ae68-0675-b8a680362e6f
* Version Independent ID: 5485c39d-f5fa-bf3f-c860-bdc5759bb997
* Content: [Remove-PnPHubSiteAssociation (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnphubsiteassociation?view=sharepoint-ps#syntax)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPHubSiteAssociation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPHubSiteAssociation.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @giveitaGo Robert how are you ? 👍 

PnP documentation is directly reflected from cmdlet's source code.
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues/questions. PnP cmdlets are maintained by the community, a member of it will pick it up there.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @giveitaGo 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
