### ISSUE TITLE
-DesignatedPresenterRoleMode

### ISSUE THREAD

**Issue by ichkoj** [MicrosoftDocs/office-docs-powershell#5397]
I'm unable to find -DesignatedPresenterRoleMode parameter please advise!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18b9baa8-da13-a24f-af31-91d63de13f08
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by mitchelljb** [comment]
I can see that the "DesignatedPresenterRoleMode" is there when polling all settings of the Global policy. When using the "set-csteamsmeetingpolicy -identity global" it will also auto complete the "DesignatedPresenterRoleMode", but i get the message that i'm not permitted. 

Love to see this being released quickly as i receive a lot of questions regarding this topic.

**Comment by get-itips** [comment]
> I can see that the "DesignatedPresenterRoleMode" is there when polling all settings of the Global policy. When using the "set-csteamsmeetingpolicy -identity global" it will also auto complete the "DesignatedPresenterRoleMode", but i get the message that i'm not permitted.
> 
> Love to see this being released quickly as i receive a lot of questions regarding this topic.

Yes, you are correct, the parameter is there, however it is not yet ready to be used, as you said, it currently output an error stating that we can not use it.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ichkoj 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
