### ISSUE TITLE
Get-Team : Error when renewedDateTime = null

### ISSUE THREAD

**Issue by joegasper** [MicrosoftDocs/office-docs-powershell#54]
Get-Team : Error occurred while executing
Code: GeneralException
Message: Failed to parse MS Graph backend response for request GetUserGroupsRequest. Request Url:
https://graph.microsoft.com/edu/me/memberOf/$/microsoft.graph.group?$filter=groupTypes/any(c:c+eq+'U...,
Request Method: GET. The response is invalid, cannot convert to type IList`1Error converting value {null} to type 'System.DateTime'. Path 'value[0].renewedDateTime', line 1, position 2463.
InnerError:
RequestId: d89f7fd7-d77e-4809-8a85-bf05e3dc5337
DateTimeStamp: 2017-11-08T04:32:38
HttpStatusCode: GeneralException
At line:1 char:1
+ Get-Team
+ ~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Get-Team], ApiException
+ FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdle
ts.PowerShell.Custom.GetTeam

If I use the MS Graph Explorer website, and enter that same Request URL above, I do have one group with "renewedDateTime" = null.

------------------
,
"renewedDateTime": null,
"securityEnabled": false,
"sharepointResources": [
------------------

**Comment by kenwith** [comment]
I will bring these to Nick's attention. I saw he just submitted a Pull Request but haven't looked through what was added in descriptions. I will make sure he sees this.

**Comment by nkramer** [comment]
Thanks, we're working on it.

**Comment by kenwith** [comment]
Thanks for feedback. It is logged with product team. Closing this one out. Thanks Joe!
