### ISSUE TITLE
ErrorAction Stop is still not available for New-UnifiedGroup

### ISSUE THREAD

**Issue by asajrawat211993** [MicrosoftDocs/office-docs-powershell#5404]
The -ErrorAction argument is missing among the supported arguments. Most commands (if not all) support this argument so the user can create PS scripts that automate tasks, and they can catch any exceptions by forcing the cmdlet to break on an error, by using -ErrorAction Stop. This cmdlet fails when the -ErrorAction argument is added, which makes it difficult to catch errors in scripts...
I see same kind of issue is opened since 2018.

Is it being resolved/ already resolved?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @asajrawat211993 How are you?
Here, we are limited to documentation issues, for cmdlet's behaviour, the resource is [UserVoice](https://office365.uservoice.com/). Please suggest your idea to add ErrorAction there, that way, it can reach the Product Team.
Hope this information helps you

**Comment by yogkumgit** [comment]
@asajrawat211993  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback.
