### ISSUE TITLE
deprecated?

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/office-docs-powershell#5406]
Also the related Get-CsTeamsMobilityPolicy  is deprecated, so is this set one thesame? In which case a note should be added to the article like the Get one e.g.. NOTE: Please note that this cmdlet was deprecated and then removed from this PowerShell module. This reference will continue to be listed here for legacy purposes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0dcf829-c8b6-7fc5-9f77-2b9c34584dda
* Version Independent ID: a6cd191e-2926-8ba6-5503-fa99c5c21561
* Content: [Set-CsTeamsMobilityPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmobilitypolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMobilityPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMobilityPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @saragava
* Microsoft Alias: **saragava**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for noticing, adding the missing note thru a PR.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @obhayes Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
