### ISSUE TITLE
There's no way to force of disable the prompt for Set-SPOHomeSite

### ISSUE THREAD

**Issue by panggio** [MicrosoftDocs/office-docs-powershell#5409]
I was trying to include it in a DevOps release but it keeps asking for confirmation and doesn't accept Confirm nor Force parameters thus I can't automate the process.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @panggio 
How are you?
For cmdlet changes or suggestions, I need to kindly redirect you to [SharePoint UserVoice](https://sharepoint.uservoice.com)
Thank you

**Comment by yogkumgit** [comment]
@panggio  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
