### ISSUE TITLE
Using EXO2 to access multiple o365 tenants from same powershell session.

### ISSUE THREAD

**Issue by natebarkei** [MicrosoftDocs/office-docs-powershell#5412]
In the old way of connecting to exchange online you could  just create the remote sessions without importing the PSSession. That allowed you to connect to more than one o365 tenant at the same time. How do I accomplish this with the EXO2 version? The connect-ExchangeOnline function automatically imports them into the current user session?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @natebarkei, thank you for your feedback.

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, contact us at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @natebarkei 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
