### ISSUE TITLE
Need a gui

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/office-docs-powershell#5423]
Please add a GUI option to enable and disable modern auth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?redirectedfrom=MSDN&view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @gkens, thank you for your feedback.

Docs.microsoft.com feedback is available to help improve or update documentation. For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/
There, your suggestion will reach the product team.

**Comment by morktron** [comment]
Yes, I feel like I'm back in the 1980's movie 'WarGames'! I'm sure Microsoft is capable of making a GUI for this, otherwise, give me a hola, I'd be happy to help

**Comment by yogkumgit** [comment]
@gkens  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
