### ISSUE TITLE
Missing Parameter for Set-OwaMailboxPolicy 

### ISSUE THREAD

**Issue by magichappens89** [MicrosoftDocs/office-docs-powershell#5425]
Hello,
according to this article about the new "Booking" feature: https://support.microsoft.com/en-us/office/get-access-to-microsoft-bookings-5382dc07-aaa5-45c9-8767-502333b214ce?ui=en-US&rs=en-US&ad=US there is a parameter -BookingsMailboxCreationEnabled but it doesn´t exist. Also couldn´t find it in the module documentation: https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-owamailboxpolicy?view=exchange-ps.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by magichappens89** [comment]
Let me know if further information or error messages are required. Maybe there is even a different way to update the attribute, at least I couldn´t find a method for this. Would be definitely great to disable the feature in the default policy.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @magichappens89 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by magichappens89** [comment]
Not sure what was done exactly? I saw that the documentation was updated but the parameter still doesn´t exist in the module acutally....

**Comment by dariomws** [comment]
Hi @magichappens89,

I have it with the same version:
![image](https://user-images.githubusercontent.com/33589238/80986158-8f19c480-8e06-11ea-82ba-019dafcc5a08.png)

It´s strange. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by magichappens89** [comment]
Ok that is strange cause I can´t find such a parameter in that module. My first guess is that it´s because the feature is not available yet and the command-lets are loaded after connecting to the Exchange? Will definitely open a ticket and let you know about the outcome.
