### ISSUE TITLE
Move-SPSite: What does "-CopyEvents" parameter do?

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/office-docs-powershell#5426]
The current text: `Specifies if events need to be copied.`

1. This is move operation, why is anything being copied?
2. Which "events" are these? Are they user visible? (I assume not because this is off by default)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d77b895-234c-9584-7806-2c39a7d607d0
* Version Independent ID: 3ce7d735-77bd-25e4-a961-ef9e3195ecaf
* Content: [Move-SPSite (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/move-spsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Move-SPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Move-SPSite.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @fowl2 James, How are you ? 👍 
Thanks for your feedback.
This refers to the events of the EventCache table in the source Content Database and it talks about copying them to the destination CDB.
You can find more information about this kind of events [here](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/bb861918(v%3doffice.14)) 
Will create a PR to improve the description.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @fowl2 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
