### ISSUE TITLE
Microsoft Teams Powershell version

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#5428]
Hi,
Could you please clarify what version you are asking us to use in production. The version which support private channels is in my mind version 1.0.18. But few days ago your team released 1.0.6.

If we are using these versions from PoshTestGallery, are we out of the support?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Petri-X 
How are you? Hope you are doing good.
I could get information from Brandon from the Product Team and he told me that:

> 1. For Teams PowerShell, production releases ship monthly. We are also in the process of migrating our beta module to PSGallery (more to come on that shortly..), at which point we'll provide more detailed release notes and differences between both production and beta Teams PowerShell modules. To answer your question around private channels in the beta module, our production release requires v1.0 graph endpoints. The private channels Graph API which underpins our cmdlet is currently in beta. Once it's released to v1.0, we'll ensure it's provided as part of our production release.

 

> 2. If there are errors encountered during beta, we of course want to know about them so they can be fixed prior to their production release. However, production usage is not supported while in beta.

Hope this information clarifies it to you.

Thanks

**Comment by Petri-X** [comment]
@get-itips 
Thank you for sharing this also. So only what I can do is wait :)
Have a great day !
