### ISSUE TITLE
Documentation Incomplete - Sample Data

### ISSUE THREAD

**Issue by tonywoodruff** [MicrosoftDocs/office-docs-powershell#5429]
cmdlet documentation incomplete. Contains sample data {{ Fill User Description }} {{ Fill in the Synopsis }}. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a27412b8-ee1c-f2f1-eaf9-3d86bf3f5dcc
* Version Independent ID: e6c9ea70-3774-8fcc-ed2a-bb42c49531f1
* Content: [Set-CsUserTeamMembers (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csuserteammembers?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsUserTeamMembers.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsUserTeamMembers.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tonywoodruff Thanks for noticing and reporting, created a pr to update the article with missing descriptions.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @tonywoodruff Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
