### ISSUE TITLE
Microsoft Teams PowerShell: Release notes

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#5430]
Hi,
Do you have any plans to release any release notes from these versions you are publishing? Would be super great to set some expectations, and also if some of the errors are fixed in which versions.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@Petri-X How are you?
I could get information from the team and they confirmed me that indeed there are plans to start providing that information in Docs in the near future.
Hope that clarifies it to you.

**Comment by Petri-X** [comment]
@get-itips 
That is would awesome if they can do that!
Big thanks to share this!
