### ISSUE TITLE
Documentation Incomplete - Sample Data

### ISSUE THREAD

**Issue by tonywoodruff** [MicrosoftDocs/office-docs-powershell#5431]
cmdlet documentation incomplete. Contains sample data {{ Fill User Description }} {{ Fill in the Synopsis }}.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0534486e-dcf7-9eef-bd71-ccb7085f67c5
* Version Independent ID: da2bcea3-1a73-dea8-db08-891a99f94944
* Content: [Set-CsUserDelegates (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csuserdelegates?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsUserDelegates.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsUserDelegates.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for noticing and reporting @tonywoodruff created a pr to update the article.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @tonywoodruff Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
