### ISSUE TITLE
Question about last note

### ISSUE THREAD

**Issue by TimAbmgf** [MicrosoftDocs/office-docs-powershell#5435]
The last note in this article (at the time of my post) says:
We highly discourage using the PropertySets parameter with the value All because it slows down the cmdlet and reduces reliability. Always use the PropertySets and Properties parameters to retrieve only the required properties.

What does it mean by 'reduces reliability'.

If I am willing to wait for the results; does that statement mean the information returned is not accurate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @TimAbmgf, thank you for your feedback.

It´s related to the performance of the cmdlet. If you´re willing to wait for the results, they will be accurate.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @TimAbmgf 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
