### ISSUE TITLE
Related Link to SharePoint Pnp is broken

### ISSUE THREAD

**Issue by mikewaretena** [MicrosoftDocs/office-docs-powershell#5439]
Hi, just a quick one the link to SharePoint Developer Paterns and Practices is malformed and links to: 
https://aka.ms/sppnp)[Encoding](https://msdn.microsoft.com/en-us/library/system.text.encoding_properties.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 451dc826-b072-5bcd-e98d-319ee82d73fe
* Version Independent ID: c0c6ad38-e86c-cd0c-ac01-033791404e25
* Content: [Get-PnPProvisioningTemplate (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPProvisioningTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPProvisioningTemplate.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @mikewaretena Miguel how are you?  👍

PnP documentation articles are directly reflected from source code.
I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues/questions. PnP cmdlets are maintained by the community, a member of it will pick it up there. Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @mikewaretena 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
