### ISSUE TITLE
-Prefix "CC"

### ISSUE THREAD

**Issue by uz-it** [MicrosoftDocs/office-docs-powershell#5440]
This parameter is only relevant for the Import-PSSession command.
While in the document it is placed under p.2. So it is probably should be mentioned in the p.3. instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Office 365 Security & Compliance Center PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell.md)
* Service: **o365-security-and-compliance**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @uz-it Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
