### ISSUE TITLE
Wrong parameter in example

### ISSUE THREAD

**Issue by jcoolsen** [MicrosoftDocs/office-docs-powershell#5441]
In this line in the example
$appPrincipal = Get-SPAppPrincipal -NameIdentifier $appIdentifier -Web $site.RootWeb
The 'Web' parameter should be 'Site' instead.
See https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spappprincipal?view=sharepoint-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2da6efca-f475-04cc-85a4-8e491c10ec57
* Version Independent ID: 872c2322-cb2a-6e31-c32e-46fddafcd33d
* Content: [Set-SPAppPrincipalPermission (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/Set-SPAppPrincipalPermission?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPAppPrincipalPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPAppPrincipalPermission.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for noticing and reporting, created a pr

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @jcoolsen Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
