### ISSUE TITLE
Remove policy package

### ISSUE THREAD

**Issue by blyw** [MicrosoftDocs/office-docs-powershell#5444]
How does one undo the changes made by Grant-CsUserPolicyPackage? Can one go back to the defaults i.e. global policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e65b667-c4ee-0580-2b7b-a63431d6f415
* Version Independent ID: 34cd470c-8783-ac88-c812-8daa762efe1b
* Content: [Grant-CsUserPolicyPackage (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/grant-csuserpolicypackage?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Grant-CsUserPolicyPackage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Grant-CsUserPolicyPackage.md)
* Service: **teams-powershell**
* GitHub Login: @etgottli
* Microsoft Alias: **etgottli**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Same as https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4463 
AFAIK it seems there isn't a way right now unless you change every policy involved individually.
I created an user voice entrance and voted for it. Please [see](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40369102-provide-a-way-to-remove-a-policy-package).

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @blyw 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
