### ISSUE TITLE
Issue with Grant-CsGroupPolicyAssignment cmdlet in powershell

### ISSUE THREAD

**Issue by sandunikeshala** [MicrosoftDocs/office-docs-powershell#5452]
I am practicing on tenant creation and configuration in teams for education. I need to assign a policy which is already created for a group in my teams using powershell. So i used this code down below but it gave me a not recognized message in powershell. 

I searched internet but couldnt find a solution.  Only found that there is a difference between those batch policy cmdlets and group policy cmdlets as : think there is an issue due to that

batch policy : This cmdlet is currently in public preview.
group policy: This cmdlet is currently only available in private preview in the pre-release Teams PowerShell module.

![image](https://user-images.githubusercontent.com/64690755/80864318-85298180-8c9f-11ea-84b0-c567b30cdd83.png)
 when I tried batch policy cmdlets they worked but any group policy cmdlets didnt worked and gave the unrecognized message. 

![image](https://user-images.githubusercontent.com/64690755/80864372-cde13a80-8c9f-11ea-89a7-df9462d871eb.png)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sandunikeshala 

The -CsGroupPolicyAssignment cmdlets are currently in private preview only, as it says [here](https://docs.microsoft.com/en-us/microsoftteams/assign-policies).

> One of the Microsoft Teams features discussed in this article, policy assignment to groups, is currently only available in private preview. The Powershell cmdlets for this feature are in the pre-release Teams PowerShell module. To stay on top of the release status of this feature, check out the Microsoft 365 Roadmap.

Once they get to production, full cmdlet documentation should be available. Other than that, I do not see any documentation issue.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @sandunikeshala Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by sandunikeshala** [comment]
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by sandunikeshala** [comment]
Hi thank you for the explanation. But i found those things when I search about these things.
I need to know how to work with this private preview cmd lets and is there any way of doing that.?
Found a document with codes which i can use to assign group policeis from powershell. How can i do them?

Thank you



Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by get-itips** [comment]
@sandunikeshala I understand, however, as those cmdlets are still under development and not for production use, there isn't official documentation other than what you found. Hope you understand.

**Comment by sandunikeshala** [comment]
Thank you so much for your reply.

Is that means I will not be able to assign group policies through powershell?


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by get-itips** [comment]
> Thank you so much for your reply. Is that means I will not be able to assign group policies through powershell? 

I recommend monitoring closely the [roadmap](https://www.microsoft.com/microsoft-365/roadmap?filters=&searchterms=61185) to see when it becomes available.
