### ISSUE TITLE
Force Deletion

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/office-docs-powershell#5460]
The article doesn't discuss how to force a deletion when PowerShell returns "We cannot remove policy '&lt;policyname&gt;' since it is already in pending deletion state."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b41d5a-c85c-e5d9-90c8-90c1277a223f
* Version Independent ID: 8baa76bc-2f5b-fb0c-ba2b-2d8b5d491763
* Content: [Remove-DlpPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/remove-dlppolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Remove-DlpPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Remove-DlpPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @terrogin, thank you for your feedback.

Almost the same than https://github.com/MicrosoftDocs/office-docs-powershell/issues/5461. Please let´s follow it there.

**Comment by dariomws** [comment]
Hi @terrogin,

If you consider this parameter important, I need to kindly redirect you to this resource https://office365.uservoice.com/.
There, your suggestion will reach the product team.

**Comment by yogkumgit** [comment]
@terrogin  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
