### ISSUE TITLE
Article does not discuss how to force deletion

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/office-docs-powershell#5461]
The article doesn't discuss how to force a deletion when PowerShell returns "We cannot remove policy '&lt;policyname&gt;' since it is already in pending deletion state."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a78aa0ce-c818-1e95-2e37-8725c7b3cc90
* Version Independent ID: 3e14521e-ef75-4328-e753-31e7b59fd481
* Content: [Remove-DlpCompliancePolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/remove-dlpcompliancepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Remove-DlpCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Remove-DlpCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @terrogin, thank you for your feedback.

Same as https://github.com/MicrosoftDocs/office-docs-powershell/issues/3283.

**Comment by dariomws** [comment]
Please check this issue:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3284

I have been working on it 1 year ago, it was deleted but I don´t have more information.

**Comment by dariomws** [comment]
Hi @terrogin,

If you consider this parameter important, I need to kindly redirect you to this resource https://office365.uservoice.com/.
There, your suggestion will reach the product team.

**Comment by yogkumgit** [comment]
@terrogin  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
