### ISSUE TITLE
new staffhub cmdlets

### ISSUE THREAD

**Issue by jvondermans** [MicrosoftDocs/office-docs-powershell#547]
Good to see that there are new cmdlets for Staffhub. I'm missing the explanation in which module I can find these.

https://docs.microsoft.com/nl-nl/powershell/module/staffhub/?view=staffhub-ps

**Comment by kenwith** [comment]
@praveenkumathalli pushed a commit for these and might be able to give some guidance on module.

@jvondermans  - this is great feedback and thank you for surfacing this question. @nsshommo and I will add some info to the Notes section of these cmdlet references once we hear from @praveenkumathalli  about the module and how to connect.

**Comment by praveenkumathalli** [comment]
@jvondermans - refer to this page in powershell gallery on how to install the module - https://www.powershellgallery.com/packages/MicrosoftStaffHub/1.0.0-alpha

**Comment by nsshommo** [comment]
Thanks @jvondermans for giving us your feedback. We are working on this issue.

Thanks @praveenkumathalli  for your quick reply. I am going to add this link in the StuffHub cmdlets.

**Comment by jvondermans** [comment]
Great, thanks for the quick response!

**Comment by kenwith** [comment]
The PR is ready to merge. I will just confirm with @praveenkumathalli and then merge these links live. Here is the PR: https://github.com/MicrosoftDocs/office-docs-powershell/pull/552

**Comment by kenwith** [comment]
Just to close this one out. The PR went live. All the StaffHub cmdlets now have a link at the bottom of the article in the Related Links section to the module in the PowerShell Gallery. Here are all the StaffHub cmdlets: https://docs.microsoft.com/en-us/powershell/module/?term=staffhub  

Thanks all!
