### ISSUE TITLE
Are the SET commands unchanged?

### ISSUE THREAD

**Issue by tmunro55** [MicrosoftDocs/office-docs-powershell#5470]
This more of a question than an issue:
I see the EXO V2 cmdlets are all GET verbs. Are the cmdlets for updating mailboxes still the same? Will they be updated in the future as part of this project?

Thank you.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @tmunro55, thank you for your feedback.

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, contact us at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @tmunro55 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
