### ISSUE TITLE
Microsoft Teams: Remove-TeamUser, 'Member' not valid Role value

### ISSUE THREAD

**Issue by loganaz** [MicrosoftDocs/office-docs-powershell#5479]
Microsoft Teams: Remove-TeamUser, 'Member' not valid Role value

MicrosoftTeams  1.0.6
On the Remove-TeamUser command 'Member' should be a valid value for the 'Role' parameter, but is not.
On the Add-TeamUser command 'Member' is a valid value for the 'Role' parameter.

Remove-TeamUser : Cannot validate argument on parameter 'Role'. The argument "Member" does not belong to the set
"Owner" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

https://docs.microsoft.com/en-us/powershell/module/teams/remove-teamuser

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @loganaz 
Thanks for reporting this, I could verify, so I created a PR to update the article.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @loganaz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
