### ISSUE TITLE
May cause confusion

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5482]
"You must be a SharePoint Online global administrator to run the cmdlet."
Is that referring to a SharePoint administrator or a global administrator?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f494bf96-d8d8-4fff-b3dd-6a1ced1f2e1f
* Version Independent ID: eb9895b5-090d-7b07-ef3c-b90266aaf8e4
* Content: [Disconnect-SPOService (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/disconnect-sposervice?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Disconnect-SPOService.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Disconnect-SPOService.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for noticing, created a pr to correct this article and others. Thank you @hwkwicre

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
