### ISSUE TITLE
Remove-SPOUserInfo vs Remove-SPOUser

### ISSUE THREAD

**Issue by BLalanda** [MicrosoftDocs/office-docs-powershell#5485]
Not clear when one or the other should be used.
Also, Remove-SPOUserInfo has an additional parameter - RedactName, that does not show up here and has no explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3aaa97d-31e1-e3bf-ee54-389491b2f103
* Version Independent ID: c0d774e4-de11-bcaf-612d-45154791f8b3
* Content: [Remove-SPOUserInfo (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spouserinfo?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOUserInfo.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOUserInfo.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@BLalanda 
I think the use of `Remove-SPOUser` is clear, removes a SharePoint Online User from a SC or group.
I tried `Remove-SPOUserInfo` and I could not identify what was being removed, I could guess "user information", but after running it I could also run `Export-SPOUserInfo` and get the same information.
@trent-green Can you help us here understading the use cases of _-SPOUserInfo_ cmdlets? Thank you

**Comment by get-itips** [comment]
@tseward Trevor, do you maybe have the missing information here? Thanks

**Comment by tseward** [comment]
@get-itips this is being looked into.

**Comment by get-itips** [comment]
> @get-itips this is being looked into.

Thanks

**Comment by yogkumgit** [comment]
@tseward
