### ISSUE TITLE
Missing information regarding parameter

### ISSUE THREAD

**Issue by BLalanda** [MicrosoftDocs/office-docs-powershell#5486]
Parameter UpdateUserTypeFromAzureAD is not referred here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c17eed23-057f-b4bf-6dcb-89cbee07f912
* Version Independent ID: a2573286-0817-7148-03b8-fbc0c3c8c5e2
* Content: [Set-SPOUser (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spouser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @BLalanda Please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/5072#issuecomment-599257074
While we look for further information to update the article.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @BLalanda Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
