### ISSUE TITLE
Inaccurate description for set-adminauditlogconfig example #1

### ISSUE THREAD

**Issue by DailenG** [MicrosoftDocs/office-docs-powershell#5487]
The text for Example #1 states the command logs for all cmdlets and all parameters except for Get cmdlets but the example does not appear to reflect that Get cmdlets are excluded

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a039162-b676-3085-db11-6a0c8933e69e
* Version Independent ID: 2a46468f-0af9-4b1a-3003-8a24cfa5dea5
* Content: [Set-AdminAuditLogConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/set-adminauditlogconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-audit/Set-AdminAuditLogConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-audit/Set-AdminAuditLogConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @DailenG Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
