### ISSUE TITLE
Powershell MFA

### ISSUE THREAD

**Issue by Jimbos10** [MicrosoftDocs/office-docs-powershell#549]
It would be great if you could provide more native support for MFA in your existing powershell applications such as ISE.

**Comment by AndreaBarr** [comment]
@Jimbos10 Thank you for engaging with the community here for the docs

Native Support for MFA inside the existing apps sounds like a great idea.

I know the product teams are always looking for user feedback and how to make the OneDrive / SharePoint better. They keep a close tab on User Voice [https://sharepoint.uservoice.com](https://sharepoint.uservoice.com) and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too. 
 
Thank you for your contribution to make the docs better! Much appreciated!
