### ISSUE TITLE
Examples have incorrect syntax

### ISSUE THREAD

**Issue by nickiapalucci** [MicrosoftDocs/office-docs-powershell#5493]
https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/get-exomailboxfolderpermission?view=exchange-ps#examples
Appears to be older related cmdlet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e94700a3-3834-fdb7-2acc-13eb22eec9b5
* Version Independent ID: 144b44d0-d97f-8afb-b9e1-c2c42a8d88b4
* Content: [Get-EXOMailboxFolderPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/get-exomailboxfolderpermission?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/powershell-v2-module/Get-EXOMailboxFolderPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/powershell-v2-module/Get-EXOMailboxFolderPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @nickiapalucci Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
