### ISSUE TITLE
HYPERLINK?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5495]
Example 2 returns one user or security group account whose user name is HYPERLINK "mailto:melissa.kerr@contoso.com" melissa.kerr@contoso.com from the site collection https://contoso.sharepoint.com/sites/finance.
Seems that this HYPERLINK thing is an error caused by copy paste.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2412565f-011a-5665-7c3b-e3fe4eae0ee2
* Version Independent ID: 30fda315-30f6-09e0-342c-63940e05208b
* Content: [Get-SPOUser (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spouser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUser.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @hwkwicre Thanks for noticing and reporting.
Created a PR to update the article.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
