### ISSUE TITLE
Creating and associating a MS Team with existing O365 Group

### ISSUE THREAD

**Issue by patrickabel** [MicrosoftDocs/office-docs-powershell#55]
Can the **New-Team** cmdlet be used to create a team and associate it with an existing O365 Group via a groupID as you can currently in the UI?

This will be critical for integration with Site Designs, site templating, etc.

```
New-Team -DisplayName <String> [-Description <String>] [-Alias <String>] [-Classification <String>]
 [-AccessType <String>] [-AddCreatorAsMember <Boolean>]
```

**Comment by kenwith** [comment]
I will bring these to Nick's attention. I saw he just submitted a Pull Request but haven't looked through what was added in descriptions. I will make sure he sees this.

**Comment by nkramer** [comment]
Great suggestion, we're working on it.

**Comment by patrickabel** [comment]
Great to hear – thanks @nkramer @kenwith!

**Comment by kenwith** [comment]
Thanks for feedback. Closing this one out.
