### ISSUE TITLE
 New-CsBatchPolicyAssignmentOperation  fails every time.

### ISSUE THREAD

**Issue by NickBorowitz** [MicrosoftDocs/office-docs-powershell#5500]
` get-aduser -searchbase "ou=students,dc=district,dc=int" -filter "emailaddress -like '*'" -properties * | select emailaddress |
    Select-Object -Property $Properties |
    ConvertTo-Csv -NoTypeInformation | # Convert to CSV string data without the type metadata
    Select-Object -Skip 1 | # Trim header row, leaving only data columns
    Set-Content -Path "C:\users\admin\desktop\Students.csv"

$user_ids = Get-Content "c:\users\admin\desktop\students.csv"
write-output "$user_ids"
New-CsBatchPolicyAssignmentOperation -PolicyType TeamsMeetingPolicy -PolicyName "EDUStudent_Custom" -identity $user_ids -OperationName "Students" 
`

I run this and every user fails. I've tried the UPN and the Email address, it shows up takes a few hours then every user shows up as failed. What am I missing?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by NickBorowitz** [comment]
anything?

**Comment by get-itips** [comment]
Please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/5214#issuecomment-610590404 and also take into account:
>Note: This cmdlet is currently in public preview.

**Comment by NickBorowitz** [comment]
They finish running, it's just the all fail and nothing applies.

**Comment by get-itips** [comment]
Hello as already mentioned, please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/5500#issuecomment-626865890 we will proceed closing this one for now. Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution. @NickBorowitz  If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
