### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5509]
-DisabledWebPartIds 
PARAMVALUE: [,,...]
What is [,,...]??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428a5954-392c-f7ad-bac4-553adf74e08e
* Version Independent ID: 44fdecf2-1977-3171-9d04-02c0fefb16c9
* Content: [Set-SPOTenant (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@hwkwicre  Thanks for noticing and reporting, created a pr to fix the parameter description.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
