### ISSUE TITLE
How to "1. Confirm SAML 2.0 is being used."

### ISSUE THREAD

**Issue by PeterWxin** [MicrosoftDocs/office-docs-powershell#5511]
1. Confirm SAML 2.0 is being used.
May I know how to

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ee082c9-735d-3f8a-7bc4-b2d4f175c784
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/Connect-MicrosoftTeams?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@PeterWxin Peter how are you? Hope you're doing great 👍 

That is usually information that _Identity Providers_ provide on their specification of supported features and also that information was needed when the external IDP was configured on the tenant, if any. (For example AD-FS)
I recommend checking with your IDP vendor in your specific scenario.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @PeterWxin 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
