### ISSUE TITLE
Not in released Module

### ISSUE THREAD

**Issue by ewillman** [MicrosoftDocs/office-docs-powershell#5512]
This page does NOT indicate that this cmdlet (Get-TeamsAppInstallation) is only available in a beta- or pre-release, but this cmdlet does not exist in the current released version of the MicrosoftTeams PowerShell package.  This page should be updated to reflect its un-release status (or the package needs to be fixed to include this cmdlet).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f40e287-2683-a3af-adf5-ad375a3e5d16
* Version Independent ID: b1d4c5a9-783b-8dbd-d669-fe1fa0472167
* Content: [Get-TeamsAppInstallation (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamsappinstallation?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-TeamsAppInstallation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamsAppInstallation.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@ewillman  Thanks for noticing and reporting, a fix to the documentation is on the way.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ewillman Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
