### ISSUE TITLE
Exchange Online PowerShell - Remoting must be enabled

### ISSUE THREAD

**Issue by jakezatecky** [MicrosoftDocs/office-docs-powershell#5515]
The included requirements fail to mention that PSRemoting must be enabled. Otherwise, the associated winrm commands fail with a message similar to the following:

```
WSManFault
    Message = The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig".
Error number:  -2144108526 0x80338012

The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig".
```

To alleviate this, the guide should mention the PowerShell Remoting requirements:

```
Enable-PSRemoting
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @jakezatecky, thank you for your feedback.

I think the author decided to not include id because WinRM is enabled by default and you should disable it with Disable-PSRemoting.

@chrisda could you kindly help here? Do you think we can add it? Thanks!

**Comment by jakezatecky** [comment]
Hello @dariomws, I do not believe Windows Remote Management is enabled by default. I ran the following command on a newer machine, and it failed with the same error as with the previous machine:

```
winrm get winrm/config/client/auth
```

My anecdotal evidence suggests that Windows 10 does not enable this service by default. However, it may very well be that Windows Server instances (as opposed to client instances) have Remote Management enabled by default.

---

As an aside, the same article mentions that Basic Authentication must be enabled and provides a command to enable if it is disabled. I can verify that Basic Authentication for WinRM is enabled by default.

Since Basic Authentication is enabled by default, whereas anecdotal evidence suggests WinRM is not by default, it stands to reason that a brief mention of enabling of the WinRM service would fit in with the article contents

Thanks!

**Comment by dariomws** [comment]
I have verified and it´s true, WinRM is not enabled by default on Windows client. I will add a note. Thanks!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @jakezatecky Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
