### ISSUE TITLE
Not to understand syntax to remove 	-ExternalConnectionSettings

### ISSUE THREAD

**Issue by pear7777** [MicrosoftDocs/office-docs-powershell#5519]
Not to understand syntax to remove 	-ExternalConnectionSettings
Thsi just doesn't telle me how to dio ths. Is this Microosft??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e2b003-51ed-8624-07d8-e30d6ebc6c8e
* Version Independent ID: 246383d8-41d0-1c15-0233-c10778e28dd5
* Content: [Set-ImapSettings (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-imapsettings?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-ImapSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-ImapSettings.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @pear7777, thank you for your feedback.

For example, if you want to remove the following values: "ServerName1:993:TLS" and "ServerName2:443:SSL", you should run the following command:
Set-ImapSettings -ExternalConnectionSettings @{Remove="ServerName1:993:TLS","ServerName2:443:SSL"}

More information:
https://docs.microsoft.com/exchange/modifying-multivalued-properties-exchange-2013-help

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @pear7777 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
