### ISSUE TITLE
Is UCS supported for contacts and contact groups migration from SfBO to TeamsOnly?

### ISSUE THREAD

**Issue by voutit** [MicrosoftDocs/office-docs-powershell#5522]
Is UCS supported for contacts and contact groups migration from SfBO to TeamsOnly or is it required to change this back to Skype for Business Server for the contacts to appear in Teams client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88b7259a-0e0e-0794-eb93-62fe07cc3a6e
* Version Independent ID: c359bdc8-b9f3-8c06-1142-15bee03ddf1b
* Content: [Invoke-CsUcsRollback (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/invoke-csucsrollback?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Invoke-CsUcsRollback.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Invoke-CsUcsRollback.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @voutit 
This is documented in a note [here](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-from-on-premises-to-teams). 

> Unified Contact Store should be disabled on the on-prem SfB account for the contact to be moved to Teams.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @voutit 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
