### ISSUE TITLE
AllowSharedNotes Parameter description

### ISSUE THREAD

**Issue by sfarouk-MS** [MicrosoftDocs/office-docs-powershell#5523]
AllowSharedNotes Parameter description in this document is not clear. Is it related to Teams meeting notes, or OneNotes ?

 
I'd checked the description from other Policy https://docs.microsoft.com/en-us/powershell/module/skype/set-csconferencingpolicy?view=skype-ps and it seems related to OneNote.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18b9baa8-da13-a24f-af31-91d63de13f08
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @sfarouk-MS How are you? Hope you are doing great.
This is related to Teams Meeting Notes. And this is the behavior when disabled.
 
![image](https://user-images.githubusercontent.com/36666927/81701749-cf99c380-9440-11ea-94cb-18c998221bd7.png)

Hope this information clarifies it to you.

**Comment by sfarouk-MS** [comment]
Thank you so much appreciate if we can update the document to make it more clear and differentiate between OneNote

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @sfarouk-MS Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
