### ISSUE TITLE
MS Teams: Get-TeamGuestSettings powershell version 5.1.17858

### ISSUE THREAD

**Issue by LindaSchaar** [MicrosoftDocs/office-docs-powershell#5540]
Hi All,

I want to check with powershell if a specific team has allow external user turned on. How do i check this in powershell? If i use Get-Team I only see this info DisplayName/ Visibility / Archived/ MailNickName/ Description but no allow external users only on tenant level, but i want it on team level.

I hope to hear soon

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @LindaSchaar How are you?

You have to leverage the use of another cmdlet and another module, as teams in Microsoft Teams are essentially Office 365 Groups.
For example [Get-UnifiedGroup](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/get-unifiedgroup?view=exchange-ps) | Where-Object {$_.AllowAddGuests -eq $true}

Other than that, I don't recognize further issues with the documentation. I hope the information helps you.

**Comment by LindaSchaar** [comment]
Hello @get-itips ,

Thank you for the help. Yes i am fine. I will try this command.

Linda
