### ISSUE TITLE
Link to SPRegionalSettings.TimeZones are dead

### ISSUE THREAD

**Issue by jesper-ego** [MicrosoftDocs/office-docs-powershell#5541]
The link in section about TimeZoneID seems dead... Should redirect to https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spregionalsettings.timezones

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5af79bd0-1525-b5d8-b65a-05f9b5a13267
* Version Independent ID: 1b98f96f-942b-679d-b43f-1dc74da1e547
* Content: [New-SPOSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/new-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks @jesper-ego for noticing and reporting. A fix is on the way.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @jesper-ego Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
