### ISSUE TITLE
Great!

### ISSUE THREAD

**Issue by florinbarbu** [MicrosoftDocs/office-docs-powershell#5552]
Finaly, I succeded to change my OnDrive Storage! Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85cea8f8-239d-1f73-f13a-a5a3148b66e5
* Version Independent ID: ca809b64-206c-4dfa-7c79-b0a45979e953
* Content: [Connect-SPOService (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Connect-SPOService?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for your feedback.
@yogkumgit please close this issue.
