### ISSUE TITLE
What are the includes?

### ISSUE THREAD

**Issue by jdelforno** [MicrosoftDocs/office-docs-powershell#5553]
I've tried to read: https://github.com/pnp/PnP-PowerShell/tree/master/Commands/Web

But I feel like I'm missing part of the equation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd309d38-78a2-4bf4-7114-a02796d12663
* Version Independent ID: 163348ba-ba40-e8e3-76ad-f8741a213ee0
* Content: [Get-PnPWeb (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpweb?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWeb.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWeb.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @jdelforno How are you?

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues/questions. PnP cmdlets are maintained by the community, a member of it will pick it up there. Thank you!

**Comment by jdelforno** [comment]
@get-itips Good thanks, yourself?

That's interesting, so it's community driven but provided documentation is on the Microsoft Documentation website. Noted.

**Comment by get-itips** [comment]
> @get-itips Good thanks, yourself?
> 
> That's interesting, so it's community driven but provided documentation is on the Microsoft Documentation website. Noted.

Hello @jdelforno John, I am good thanks.
The experts and contributors of PnP that can answer your inquiry reside on the repository I referenced.
Also, the documentation for PnP cmdlets is directly referenced from cmdlet's source code, on that repository also.
Hope this information clarifies it to you! have a good day.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @jdelforno 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
