### ISSUE TITLE
Overview Link is broken

### ISSUE THREAD

**Issue by ahamin01** [MicrosoftDocs/office-docs-powershell#5554]
Please, check the overview Link as it's invalid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 719f5227-2b47-3487-99bb-222d18d43552
* Version Independent ID: e7833ab4-d2b1-5840-4f2c-dda86599d3af
* Content: [Microsoft Whiteboard Admin](https://docs.microsoft.com/en-us/powershell/module/whiteboard/?view=whiteboard-ps)
* Content Source: [whiteboard/whiteboard-ps/whiteboard/whiteboard.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/whiteboard/whiteboard-ps/whiteboard/whiteboard.md)
* Service: **whiteboard-powershell**
* GitHub Login: @tbrosman
* Microsoft Alias: **tbrosman**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @ahamin01 thanks for noticing and reporting, A PR is on the way to fix this.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ahamin01 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
