### ISSUE TITLE
Missing parameter in the example

### ISSUE THREAD

**Issue by ahamin01** [MicrosoftDocs/office-docs-powershell#5555]
This example command is not totally complete, as it's missing the Whiteboard Id. Hence, the command should be 

Set-WhiteboardOwner -OldOwnerId 00000000-0000-0000-0000-000000000001 -NewOwnerId 00000000-0000-0000-0000-000000000002 -WhiteboardId 00000000-0000-0000-0000-000000000003

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 937e93de-d8b7-3a9e-571a-1f4cfe4726bf
* Version Independent ID: d2823029-ec76-95c7-b931-56fe6a2f11ba
* Content: [Set-WhiteboardOwner (whiteboard)](https://docs.microsoft.com/en-us/powershell/module/whiteboard/set-whiteboardowner?view=whiteboard-ps)
* Content Source: [whiteboard/whiteboard-ps/whiteboard/Set-WhiteboardOwner.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/whiteboard/whiteboard-ps/whiteboard/Set-WhiteboardOwner.md)
* Service: **whiteboard-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for noticing and reporting @ahamin01 I could verify so I created a PR to improve the article based on your feedback. Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @ahamin01 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
