### ISSUE TITLE
Missing Parameter - SafeTransferEnabled 

### ISSUE THREAD

**Issue by shawnharry** [MicrosoftDocs/office-docs-powershell#5556]
This page needs updating as there are a number of missing parameters

-AllowCalling (May be legacy)
-AllowWebPSTNCalling
-SafeTransferEnabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f1bf407-1ad6-77d9-4ef1-4bc821576912
* Version Independent ID: 4630697b-375e-85f2-25b1-b944bc6dad5f
* Content: [Set-CsTeamsCallingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by shawnharry** [comment]
Also after enabling SafeTransferEnabled Safe Transfer doesn't work. Can you advise if/when SafeTransferEnabled will be functional and fully working.

**Comment by get-itips** [comment]
Hello @shawnharry 
Thanks for your feedback, I will propose adding missing parameters thru a Pull Request.
And also I will ask the author to share further details to try to expand the proposed descriptions even more.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @shawnharry Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
