### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by WillemVerwijs** [MicrosoftDocs/office-docs-powershell#5557]
Install-Module PowershellGet -Force
error:
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2/'.
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'Powershell
'. Try Get-PSRepository to see all available registered module repositories.

Can you please provide a fix or additional info for those who get this error.

So how do I know anyone reads this and how do I know action is taken?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/nl-nl/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by TheBluLion** [comment]
I had errors on install-module exchangeonlinemanagement
Looks like the module has been moved from the nuget repository to the psgallery.
install-module exchangeonline -repository psgallery

You may not need to install and update powershellget anymore, although I was able to still do so by running install-module powershellget -repository psgallery 

the document does need to be updated, though.

**Comment by dariomws** [comment]
Hi @WillemVerwijs, thank you for your feedback.

Please check the following article to install PowershellGet depending on the version of Windows/PowerShell:
https://docs.microsoft.com/powershell/scripting/gallery/installing-psget

If you are using Win 8.1 or 2012 R2:
https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5725
This issue was reported and the articles will be updated soon.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @WillemVerwijs Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
