### ISSUE TITLE
Set-SPOsite -DenyAddAndCustomizePages issue  on team sites

### ISSUE THREAD

**Issue by Bart2s4** [MicrosoftDocs/office-docs-powershell#5558]
Since in need to upload an old doc  template. I always used the set-sposite -DenyCustomizePages 0  command, but a few weeks ago i always receive an error. I even donwloaded and installed the new sharepoint online management shell, still same issue. Wierd enough, is that in the documentation of Microsoft docs it still is a valid command.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Bart2s4 How are you?
Tried to use that parameter to see if we need to change documentation and received no errors. Are you still facing errors?
Thanks

**Comment by Bart2s4** [comment]
No the problem has been solved at the backend, all  customers can use the function again, even in team sites

**Comment by get-itips** [comment]
> No the problem has been solved at the backend, all customers can use the function again, even in team sites

Thanks for returning and sharing your feedback.
@yogkumgit You can close this now.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Bart2s4 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
