### ISSUE TITLE
PSSessionOption example

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/office-docs-powershell#5561]
Hello, please share an example of how to use the PSSessionOption parameter. 

Specifically, how can I pass the CommandName option with a value?

```powershell
Import-PSSession $EXOSession -CommandName "Get-OrganizationConfig" -AllowClobber
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28f6554b-4d67-06d3-7926-1b958653872f
* Version Independent ID: 7a6a1737-afdf-dfd5-67f8-64aa6758ccc4
* Content: [Connect-ExchangeOnline (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/connect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by jonwbstr** [comment]
Just noticed the example talks about using New-PSSessionOption was hard to spot because of line wrapping. Sadly neither of the things I want to do are a PSSessionOption. :(

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @jonwbstr, thank you for your feedback.

In the parameter description you can see how you can use it:
"The PSSessionOption parameter specifies the PowerShell session options to use in your connection to Exchange Online. You store the output of the New-PSSessionOption command in a variable (for example, $Options = New-PSSessionOption <Settings>), and you use the variable name as the value for this parameter (for example, $Options)."

Please, let me know if you think we need to add or update something.

**Comment by jonwbstr** [comment]
It's fine, the only improvement you might consider is putting the example
command on its own line to improve visibility a little. I did spot it after
the 3rd glance.

**Comment by dariomws** [comment]
Like this?

The PSSessionOption parameter specifies the PowerShell session options to use in your connection to Exchange Online. You store the output of the New-PSSessionOption command in a variable, for example:
$Options = New-PSSessionOption <Settings>
And you use the variable name as the value for this parameter (for example, $Options).

**Comment by jonwbstr** [comment]
Yes, that was my thought exactly

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @jonwbstr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
