### ISSUE TITLE
Example 2 description missleading

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/office-docs-powershell#5562]
The example below implies that you need -UserPrincipalName and -ShowProgress to connect using an account with MFA enabled. ShowProgress is $true by default. 

Perhaps a better example would be to use -ShowProgress:$False with an explanation of, "This command connects the current PowerShell session hiding the progress bar and using chris@contoso.com account, which is MFA enabled.
```
Example 2

Connect-ExchangeOnline -UserPrincipalName chris@contoso.com -ShowProgress $true
This command connects the current PowerShell session using chris@contoso.com account, which is MFA enabled.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28f6554b-4d67-06d3-7926-1b958653872f
* Version Independent ID: 7a6a1737-afdf-dfd5-67f8-64aa6758ccc4
* Content: [Connect-ExchangeOnline (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/powershell-v2-module/connect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/powershell-v2-module/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by jonwbstr** [comment]
Actually, I don't know what showprogress does. Ran the command with the value of $true and $false and didn't notice a difference in experience...

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
@jonwbstr, thank you for your feedback.

I tested it and you are right. Please, provide the feedback related to V2 module in the way this article state:
https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2#report-bugs-and-issues

**Comment by dariomws** [comment]
@jonwbstr,

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, contact us at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

When you report an issue, be sure to include the log files in your email message.

To generate the log files, replace <Path to store log file> with the output folder you want, and run the following command:
Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @jonwbstr 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
