### ISSUE TITLE
Example 1 and 3 are incorrect

### ISSUE THREAD

**Issue by Paco2015** [MicrosoftDocs/office-docs-powershell#5568]
Example 1 should be:
Get-Mailbox -ResultSize unlimited | Get-MailboxAutoReplyConfiguration 

Example 3 should be removed as it seems to be duplicate to Example 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 027c3a5d-02a5-d524-e46c-09b1f00685d1
* Version Independent ID: 3bab8ec5-6318-4bf8-4d0a-c340be25cf5e
* Content: [Get-MailboxAutoReplyConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailboxautoreplyconfiguration?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-MailboxAutoReplyConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-MailboxAutoReplyConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @Paco2015  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
