### ISSUE TITLE
How do I use a Direct Routing number with a Calling Line Identity Policy

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#5575]
Hello,
Service Numbers are great to be used, but Customers are asking us for using TDR Numbers as well.
I explored adding Service Numbers but they are Microsoft Numbers.
How would I use a Direct Routing number with this Policy?

Thanks,
David

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DEberhardt David, how are you?
AFAIK using a number that isn't a service number isn't available yet.
The best resource to suggest that is UserVoice and I found an [uservoice suggestion](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38223676-enable-the-ability-to-use-non-service-numbers-with) that matches your request and I voted for it.

Hope this helps you,

**Comment by DEberhardt** [comment]
Thank you. I also voted for it. :)

**Comment by yogkumgit** [comment]
@DEberhardt  Thank you very much for your kind feedback. Thanks for the vote. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
