### ISSUE TITLE
Get-CsOnlineVoiceApplicationInstance

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#5577]
Hello,

the Set-Command exists, but there is currently no way to query an OnPremTelephoneNumber set for an Application Instance.

As this is vital to verify its application (outside the Web portal), can this one please be provided?

Thank you,
David

**EDIT**: Sorry, found that Get-CsOnlineApplicationInstance shows the PhoneNumber set with Set-CsOnlineVoiceApplicationInstance. I expected it to be shown differently. Please close.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@DEberhardt Thank you very much for the contribution and sharing this explanation. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
