### ISSUE TITLE
rescheduled

### ISSUE THREAD

**Issue by johnreece2019** [MicrosoftDocs/office-docs-powershell#5579]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c93a65-a404-6a2b-6e0b-c9142eade407
* Version Independent ID: 8fa169c0-74f3-92b0-4bcf-cb31bf616c9c
* Content: [Get-SPOUserAndContentMoveState (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spouserandcontentmovestate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserAndContentMoveState.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserAndContentMoveState.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @johnreece2019 
Can you please specify what is the issue with the article?
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @johnreece2019 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
