### ISSUE TITLE
Bulk change

### ISSUE THREAD

**Issue by seb-sudo** [MicrosoftDocs/office-docs-powershell#5580]
Is it possible to bulk change attributes for users? 
All of my users have their prompt language by default set to en-US and I want to change them to en-GB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0146821-d9a4-35c0-7b68-e9b35521a0f3
* Version Independent ID: fa87b9ae-bea0-17cd-c5a7-9efaac8f7392
* Content: [Set-CsOnlineVoicemailUserSettings (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoicemailusersettings?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @seb-sudo How are you?
Not possible without creating, for example, a PowerShell script and using other cmdlet like [Get-CsOnlineUser](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps) to obtain the identity parameter needed by Set-CsOnlineVoicemailUserSettings

Other than that I do not recognize any issue with documentation. I hope this information guides you in the right direction. Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @seb-sudo 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
