### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/office-docs-powershell#5588]
I was able to upgrade module successfully with below command

Update-Module SharePointPnPPowerShell*

But after the upgrade now I see two versions of the module. Is that expected behavior? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3240d3-6a7d-fc4b-62fd-d3a5375d8a4a
* Version Independent ID: 561212df-4dab-92b7-b634-57d53d313c6f
* Content: [PnP PowerShell Overview](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps#updating)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by lesjtay** [comment]
Same problem and I get this error.
PS C:\Windows\System32> get-help Set-PnPListItem -online


Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
Set-PnPListItem                   Cmdlet    SharePointPnPPowerShellO… Updates a list item
Set-PnPListItem                   Cmdlet    SharePointPnPPowerShellO… Updates a list item
Get-Help: Multiple Help topics were found. Use only one Help topic with the -Online option.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by hwkwicre** [comment]
I have the same question as ravick4u

**Comment by get-itips** [comment]
Hello everyone
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/) a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ravick4u 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
