### ISSUE TITLE
Applies to 

### ISSUE THREAD

**Issue by MIBadran** [MicrosoftDocs/office-docs-powershell#5591]
This Applies top Teams as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9af8cd-c307-aff5-db34-b9c3864cc32a
* Version Independent ID: ed904d57-f5db-c145-58af-51959bb4c93c
* Content: [Set-CsOnlineDialInConferencingUserDefaultNumber (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinedialinconferencinguserdefaultnumber?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineDialInConferencingUserDefaultNumber.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineDialInConferencingUserDefaultNumber.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@MIBadran 
Please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/5405#issuecomment-624118384

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and guidance. @MIBadran Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
