### ISSUE TITLE
Smarthost that uses 587

### ISSUE THREAD

**Issue by freakynl** [MicrosoftDocs/office-docs-powershell#5599]
Hi,

any clues on how to set it to use port 587 on the smarthost? Don't see any parameters to specify a port and it doesn't like '-SmartHosts relay.fqdn.tld:587'

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197a2ea2-b2a9-8d28-d724-1ec049eaa6b4
* Version Independent ID: e4a8d18c-7259-fc35-42a9-6adce0a1b772
* Content: [Set-OutboundConnector (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/set-outboundconnector?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mail-flow/Set-OutboundConnector.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mail-flow/Set-OutboundConnector.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@freakynl, it's not possible. Inbound and Outbound connectors in the service are for standard server-to-server connections between SMTP servers/devices. No consideration for specifying ports.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by freakynl** [comment]
That's unfortunate.

Thanks for the re' :)

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @freakynl Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
