### ISSUE TITLE
Whatif parameter does not work!

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#560]
Whatif parameter does not work. Be careful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67a1fb9d-8199-7574-276a-d32482fd1f7d
* Version Independent ID: d6d3f5ba-d91b-2968-d6a8-588ec3c65e86
* Content: [Update-SPSolution (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/update-spsolution?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Update-SPSolution.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Update-SPSolution.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@YuriySamorodov Thank you for this feedback

I am going to get this over to the PowerShell team so we can figure this out and get the article updated. 


I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by yogkumgit** [comment]
@YuriySamorodov Thank you for reporting this feedback here. This list is focused on content issues and I want to make sure your immediate product issue does not get lost in this list. If you would please open a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team.
