### ISSUE TITLE
ExternalMailExpiryInterval

### ISSUE THREAD

**Issue by leifdavisson** [MicrosoftDocs/office-docs-powershell#5602]
The new property is missing from this page. ExternalMailExpiryInterval 

Get-omeconfiguration 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ae2cba-8c1d-ebd1-9834-f5a4881830cc
* Version Independent ID: 6134df0d-c336-4288-c704-63cf742c0c5e
* Content: [Get-OMEConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/get-omeconfiguration?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/encryption-and-certificates/Get-OMEConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/encryption-and-certificates/Get-OMEConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by leifdavisson** [comment]
Can you update the set-omeconfiguration page as well?  Also I wasn't able to set the expiry time to 30 days.

**Comment by dariomws** [comment]
Hi @leifdavisson, thank you for your feedback and help us to improve docs.

ExternalMailExpiryInterval is not available in Get-OMEConfiguration. It´s documented in Set- and New-. Also, you cannot set it in the default OME configuration. I added a sentence about that.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @leifdavisson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
