### ISSUE TITLE
ExternalMailExpiryInterval

### ISSUE THREAD

**Issue by leifdavisson** [MicrosoftDocs/office-docs-powershell#5603]
Missing new property type and how to set the property. 

ExternalMailExpiryInterval 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aabcc26e-242d-1342-24af-a419a129e91d
* Version Independent ID: 110aa234-6fb0-ff5c-fe5c-10b86147b9ce
* Content: [Set-OMEConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/set-omeconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@leifdavisson, same issue and resolution as #5602, so closing.
