### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by balajigunasekaran** [MicrosoftDocs/office-docs-powershell#5606]
Both these examples doesnt work and they dont match the command at the top.

New-SPClaimProvider -Name "MyClaimProvider" -Type "MyClaimProvider.Providers.CustomProvider" -AllWebApplications
New-SPClaimProvider -Name "MyClaimProvider" -Type "MyClaimProvider.Providers.CustomProvider" -Scope (Get-SPWebApplication https://test)
Error: A parameter cannot be found that matches parameter name Scope

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60bc6a16-d0c5-6cd6-9976-4e02899a9206
* Version Independent ID: f965da93-81ac-d9ed-4bb7-b9d88bd246c5
* Content: [New-SPClaimProvider (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spclaimprovider?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPClaimProvider.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPClaimProvider.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @balajigunasekaran Thanks for noticing and reporting. Created a pull request against this article to correct it.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @balajigunasekaran Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by balajigunasekaran** [comment]
Thanks to @get-itips and @yogkumgit. Good luck.

**Comment by balajigunasekaran** [comment]
Thanks to @get-itips and @yogkumgit. Good luck.
