### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5609]
Cmdlet Parameter Sets (https://go.microsoft.com/fwlink/?LinkID=187810).
Link doesn't work

For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at https://go.microsoft.com/fwlink/p/?LinkId=251831 (https://go.microsoft.com/fwlink/p/?LinkId=251831).
Repeated link, second one doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ac87fde-0d91-d0cc-6c9e-444917652bec
* Version Independent ID: 10d9bf8c-a1ab-1cfe-c831-127d9d924fd2
* Content: [Remove-SPODataConnectionSetting (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spodataconnectionsetting?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODataConnectionSetting.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODataConnectionSetting.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by hwkwicre** [comment]
Related Links
Get-SPODataConnectionSetting
this one also doesn't work

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by hwkwicre** [comment]
Related Links
Get-SPODataConnectionSetting
Also doesn't work

**Comment by get-itips** [comment]
Thanks for reporting @hwkwicre

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
