### ISSUE TITLE
This is incomplete.   

### ISSUE THREAD

**Issue by ejorczyk** [MicrosoftDocs/office-docs-powershell#561]
Example: "Insert Descriptive Text" and "Provide the topic introduction here." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9af8cd-c307-aff5-db34-b9c3864cc32a
* Version Independent ID: ed904d57-f5db-c145-58af-51959bb4c93c
* Content: [Set-CsOnlineDialInConferencingUserDefaultNumber (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinedialinconferencinguserdefaultnumber?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineDialInConferencingUserDefaultNumber.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineDialInConferencingUserDefaultNumber.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by nsshommo** [comment]
@ejorczyk Thanks for letting us know.

@islubin Can you guide me on this one?

**Comment by alorman** [comment]
Seriously, please finish the example, at least!

**Comment by nsshommo** [comment]
@alorman Thanks for stopping by. It is under procedure.

**Comment by nsshommo** [comment]
@Oscar Ruiz Garcia Can you help me filling this up?

**Comment by kenwith** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/issues/747

**Comment by mgarza1812** [comment]
Noticed -whatif doesn't seem to work perhaps user error but, this is the command I ran anyway. Thanks.

Set-CsOnlineDialInConferencingUserDefaultNumber -FromNumber 6498873547 -ToNumber 6432880312 -CountryOrRegion "NZ" -WhatIf -verbose

**Comment by kenwith** [comment]
This is in process to be fixed along with a full audit of all cmdlet to have content. This is being tracked internally.
