### ISSUE TITLE
Parameter

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5610]
-NoWait 
PARAMVALUE: SwitchParameter
Maybe add some description?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af2a878-cf06-c990-d538-aebf00f2a35d
* Version Independent ID: b19b5db8-33da-1ac6-1348-28cc58aef08b
* Content: [Remove-SPODeletedSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spodeletedsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODeletedSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODeletedSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @trent-green Trent how are you? I could not get information about the use of the `-NoWait` parameter, can you help me here? Thank you

**Comment by get-itips** [comment]
@trent-green 
Ok This is what I could get from `-NoWait` description for other parameters in SPO:

> Continues without the status being polled. Polling the action can slow it's progress

> Specifies to continue executing script immediately.

and

> This parameter is reserved for internal Microsoft use.

So the definition for this cmdlet probably is one of those.

**Comment by hwkwicre** [comment]
It should be "its" instead of "it's"
