### ISSUE TITLE
Be more precise about parameter MAPIEnabled

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/office-docs-powershell#5614]
Can you be more precise what's the effect if you disable MAPIEnabled for an ExO mailbox please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9398dd25-94e7-a8f8-6d97-f150173bb4da
* Version Independent ID: 6f19f636-20d5-bc97-68be-30b313f107b8
* Content: [Set-CASMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-casmailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-CASMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-CASMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and updating the documentation with PR. @trudolf-msft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
