### ISSUE TITLE
Parameter ActiveType

### ISSUE THREAD

**Issue by kaiwessels** [MicrosoftDocs/office-docs-powershell#5615]
When choosing under Parameters "-ActiveType" value "None" is not an option

New-CsAutoAttendantPrompt -ActiveType none       

A prompt needs to have data for one type (Text-to-Speech or Audio File) set.
At C:\Users\kai.wessels\AppData\Local\Temp\tmp_14paw12f.iht\tmp_14paw12f.iht.psm1:21053 char:9
+         $steppablePipeline.End()
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-CsAutoAttendantPrompt], OaaCmdletException
    + FullyQualifiedErrorId : PromptTypeDataNotSet,Microsoft.Rtc.Management.Hosted.OAA.V2.NewCsAaPromptCmdlet
    + PSComputerName        : admin1e.online.lync.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd5b3914-3cb5-7278-7ba3-d2ec209e7017
* Version Independent ID: 8ee37e01-7b8c-424f-9164-87d10d4ba1ae
* Content: [New-CsAutoAttendantPrompt (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csautoattendantprompt?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendantPrompt.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsAutoAttendantPrompt.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @kaiwessels 
How are you? Hope you are doing great.

Actually, as I saw that you ran `New-CsAutoAttendantPrompt -ActiveType none`

the error is telling you that you either need to use `-AudioFilePrompt` or `-TextToSpeechPrompt` parameters.

If you run, for example

`$ttsPrompt = New-CsAutoAttendantPrompt -TextToSpeechPrompt "Welcome to Contoso!" -ActiveType none`

You can specify none as a value for ActiveType:

![image](https://user-images.githubusercontent.com/36666927/82698761-c3ccaf00-9c41-11ea-99eb-3e0a2fa530b3.png)

Hope this clarifies it to you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @kaiwessels 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
