### ISSUE TITLE
Same Thing as Updating Column?

### ISSUE THREAD

**Issue by mushieslushie** [MicrosoftDocs/office-docs-powershell#562]
Does this just get the 'content' from the 'Wiki Content' column (WikiField) or does this do something else?  Would getting and updating the value of the Wiki Content column result in the same outcome?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dc81e82-9707-dbb6-26f0-c6c1872ca620
* Version Independent ID: fe6c6701-7495-6b2f-531c-7c1e0a0b83b2
* Content: [Get-PnPWikiPageContent (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpwikipagecontent?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWikiPageContent.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWikiPageContent.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by VesaJuvonen** [comment]
Luckily PnP PowerShell is open source, so we can trace back on what this actually does. In short answer is **true**. It provides the Wiki Content column with following steps.

The actual implementation of `Get-PnPWikiPageContent` is in the following location and it uses PnP Sites Core CSOM extension (like all PnP PowerShell cmdlet) - https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Publishing/GetWikiPageContent.cs

Code calls `Web.GetWikiPageContent(ServerRelativePageUrl)` CSOM extension which is available from https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs#L50

This in turn is using native oob CSOM and returns the `WikiField` value as follows.

```
        public static string GetWikiPageContent(this Web web, string serverRelativePageUrl)
        {
            if (string.IsNullOrEmpty(serverRelativePageUrl))
            {
                throw (serverRelativePageUrl == null)
                  ? new ArgumentNullException(nameof(serverRelativePageUrl))
                  : new ArgumentException(CoreResources.Exception_Message_EmptyString_Arg, nameof(serverRelativePageUrl));
            }

            var file = web.GetFileByServerRelativeUrl(serverRelativePageUrl);

            web.Context.Load(file, f => f.ListItemAllFields);

            web.Context.ExecuteQueryRetry();

            return file.ListItemAllFields["WikiField"] as string;
        }
```
