### ISSUE TITLE
Address Target Site Limitations Earlier in this Documentation

### ISSUE THREAD

**Issue by kk-sdsu** [MicrosoftDocs/office-docs-powershell#5621]
Please adjust the language at the top of this page, as the current language at the top: "Invokes a job to swap the location of a site with another site while archiving the original site" is really misleading. Most people won't read all the way down to the section on the target parameter to find out that it's only good for the root site or search site. If not at the top of the page, at least put it in the Description section with the other usage warnings.

I ask that you do this to help other busy developers like me who aren't going to read every last word on this page. I hope you do so that other devs don't waste hours of their day prepping for a site swap, only to get a very frustrating error message informing them of an issue, which (in my opinion) this documentation failed to do well. Time to go disappoint some users with the news that their site can't be swapped...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb8f8e8-1242-363c-be77-038142b4efb9
* Version Independent ID: 54a60006-3d61-4bb9-a040-60fe77ef9f85
* Content: [Invoke-SPOSiteSwap (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/invoke-spositeswap?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md)
* Service: **sharepoint-powershell**
* GitHub Login: @WayneEwington
* Microsoft Alias: **waynewin**

**Comment by kk-sdsu** [comment]
I see that I am not the first developer to raise an issue regarding a usability issue of this documentation. I ask that you update the doc this time, as for us as users, having this information buried deep on the page obviously does not help us.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @kk-sdsu How are you? 👍 Thanks for your feedback.
I am proposing to add a note to the description thru a pull request against the article.
If it gets approval, it will be reflected online.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @kk-sdsu Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
