### ISSUE TITLE
WhatIf switch not listing changes

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/office-docs-powershell#5622]
When I add the WhatIf switch to the Update-DistributionGroupMember command. It does not show how it would update the distribution group if applied.
I was expecting that with WhatIf it lists the changes that would occur.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de156666-501b-d45e-f755-70273f2a29de
* Version Independent ID: 3e873980-c99b-0cfb-1e8a-0af4314d2d97
* Content: [Update-DistributionGroupMember (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/update-distributiongroupmember?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Update-DistributionGroupMember.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Update-DistributionGroupMember.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @yogkumgit, thank you for your feedback and help us to improve docs.

I tested it and looks like it´s working as expected:
![image](https://user-images.githubusercontent.com/33589238/82487245-838bf600-9ab4-11ea-8199-a00537cc7394.png)

For more information: https://techcommunity.microsoft.com/t5/itops-talk-blog/powershell-basics-don-t-fear-hitting-enter-with-whatif/ba-p/353579#

If you want to suggest a product improvement:
https://office365.uservoice.com/

**Comment by yogkumgit** [comment]
@dariomws I think you meant @joergrenn :)

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @joergrenn 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
