### ISSUE TITLE
Ability for cert to be installed in Machine Store instead

### ISSUE THREAD

**Issue by sukh-ava** [MicrosoftDocs/office-docs-powershell#5630]
[Please allow cert to be installed and referenced in Local machine store. Installing it on user store ties it to a specific user which is less than ideal. If the user leaves the project  this will cause a problem.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/app-only-auth-powershell-v2?view=exchange-ps&source=docs)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @sukh-ava, thank you for your feedback.

Feedback in docs.microsoft.com is available to help us to improve it. As it seems to be more a feature request I have to suggest you that try with these channels:
https://office365.uservoice.com/
https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2#report-bugs-and-issues

**Comment by yogkumgit** [comment]
@sukh-ava  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
