### ISSUE TITLE
Connect-ExchangeOnline not honouring proxy settings

### ISSUE THREAD

**Issue by CrazyCodeUK** [MicrosoftDocs/office-docs-powershell#5638]
When trying to run connect-exchangeonline from a server that requires a proxy to access external sites with white-listing required. The following error is received:

New-ExoPSSession : Connecting to remote server outlook.office365.com failed with the following error message : The
client cannot connect to the destination specified in the request. Verify that the service on the destination is
running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the
destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the
destination to analyze and configure the WinRM service: "winrm quickconfig". For more information, see the
about_Remote_Troubleshooting Help topic.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\0.4578.0\ExchangeOnlineManagement.psm1:426
char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-ExoPSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Exchang
   e.Management.ExoPowershellSnapin.NewExoPSSession

We have verified all the required URI's we can identify, and these are white-listed through the proxy, including oulook.office365.com.

When checking against the firewall logs it looks like parts of the connection process are not conforming with the proxy settings

Get-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings' | Select-Object ProxyServer, ProxyEnable

ProxyServer              ProxyEnable
-----------              -----------
&lt;our proxy host&gt;           1

At the same time as connections are going through to the proxy we are getting a large amount of connections trying to go  through to a wide variety of microsoft IP's direct with a destination port of 443. Some examples:
52.97.179.226
40.100.174.2
40.100.175.146
40.90.137.126
40.90.23.206

Do some parts of the module not honour the proxy settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @CrazyCodeUK, thank you for your feedback. We are here to take feedback to help us to improve docs.microsoft.com. I cannot provide you with support or take feedback for product improvement.

Please, check the following links maybe they can help you:
https://docs.microsoft.com/office365/enterprise/urls-and-ip-address-ranges
https://docs.microsoft.com/microsoft-365/enterprise/networking-configure-proxies-firewalls
https://connectivity.office.com/

If these articles doesn´t help, please provide feedback about EXO V2 module here:
https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2#report-bugs-and-issues
Or open a support ticket. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Thank you again!

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @CrazyCodeUK 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
