### ISSUE TITLE
Get-Team runs forever

### ISSUE THREAD

**Issue by ajacks88** [MicrosoftDocs/office-docs-powershell#5642]
We have 700+ teams in our tenant. We are attempting to automate some various things within teams, but when attempting to get a list of all teams and their associated properties the Get-Team cmdlet never finishes. I saw in the other issues posted here that it is expected for it to take awhile, but I've tested on three separate machines and each time i ended up having to kill the session after 3 hours. Am i just not giving it enough time, or is there actually an issue? 

Let me know if any additional information would be helpful.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @ajacks88, thank you for your feedback and help us to improve docs.microsoft.com.

You can find more information here, as he reported the same behaviour: https://github.com/MicrosoftDocs/office-docs-powershell/issues/5018. The product team is working on improvement. I will also send them this information.

Thanks again!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @ajacks88 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
