### ISSUE TITLE
-Properties parameter is not working

### ISSUE THREAD

**Issue by lciprianionut** [MicrosoftDocs/office-docs-powershell#5644]
Hello,

The -Properties parameter with * is not working, only for named properties are working.

PS C:\WINDOWS\System32&gt; Get-EXOCasMailbox -Properties *owa* -Identity ID
Get-EXOCasMailbox : Some of requested properties are not valid. InvalidProperties = *owa*

PS C:\WINDOWS\System32&gt; Get-EXOCasMailbox -Properties owa* -Identity ID
Get-EXOCasMailbox : Some of requested properties are not valid. InvalidProperties = owa*

Get-EXOCasMailbox -Properties OwaMailboxPolicy -Identity ID
This is working.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70681e65-e8fb-afe9-dc1b-ffa85e2d1c34
* Version Independent ID: 515298c6-f788-7c65-1c68-a6b5b2e91b3a
* Content: [Get-EXOCasMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-exocasmailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-EXOCasMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-EXOCasMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @lciprianionut Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
