### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5646]
Specifies the login name of the user who's data is exported.
Should be "whose data"
Also link https://go.microsoft.com/fwlink/p/?LinkId=251832 (https://go.microsoft.com/fwlink/p/?LinkId=251832).
repeated and second one doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc0fd6e0-6ff6-a7b0-24ad-444ce88b59c6
* Version Independent ID: 40a453b7-15c5-7f66-d556-0c9bb1bc2a10
* Content: [Export-SPOUserProfile (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/export-spouserprofile?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Export-SPOUserProfile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Export-SPOUserProfile.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
