### ISSUE TITLE
Set-RemoteMailbox and the ACLableSyncedObjectEnabled parameter

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/office-docs-powershell#565]
Hi,

The ACLableSyncedObjectEnabled parameter is now available to tenants and makes the msExchRecipientDisplayType set to ACLableSyncedMailboxUser when using the New/Enable-RemoteMailbox cmdlets.  When using the parameter with the Set-RemoteMailbox no action is taken on the mailbox.  The following warning is displayed - 

WARNING: The command completed successfully but no settings of 'object' have been modified.

Not sure if this is expected behavior or not.

Thanks,
Kelly

**Comment by chrisda** [comment]
@dstrome, can you locate a hybrid person who can answer this question?

**Comment by AndreaBarr** [comment]
@kellybos Thank you for this feedback

I am going to get this over to the PowerShell team for investigation. This might be a bug and if it is they will be able to get it addressed. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by greatwallx2** [comment]
Is there any update on this? we are being impacted by this issue

**Comment by chrisda** [comment]
@kellybos, @LuisEmilioR, is the Set-RemoteMailbox still available to you in Exchange Online PowerShell? In my stock E5 tenant, that cmdlet isn't available to me (no RBAC role contains it). In other words the command:

```
Get-ManagementRoleEntry *\Set-RemoteMailbox
```
returns no results. Perhaps it was exposed in Exchange Online by mistake and then removed?

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and sharing this explanation. @kellybos 
Hope this comment is helpful for you.  If you have any suggestions that can improve this document please feel free to revert. Thanks for taking out some time to open the issue.

**Comment by yogkumgit** [comment]
@officedocsbot close
