### ISSUE TITLE
New Parameter AllowNDIStreaming

### ISSUE THREAD

**Issue by bzyg7b** [MicrosoftDocs/office-docs-powershell#5652]
There is a new parameter available for Set-CsTeamsMeetingPolicy of -AllowNDIStreaming but it is not documented, is this a WOP feature or is NDI in Teams live?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @bzyg7b, thank you for your feedback and help us to improve docs.microsoft.com.

This parameter is not available at this time. Maybe the product team is working on a new feature but I don´t have this information. Hope you understand.

**Comment by bzyg7b** [comment]
Thanks for the reply, I guess it must have been added in the admin settings ahead of the product team making a release.
