### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/office-docs-powershell#5655]
Most of the New-Team parameters are Boolean, and most have a default value of "None". What does that mean? I would expect it to be True or False. If it is literally none, then it would mean that the parameter is required, but has no default. But it clearly is not required, as they are not set in the example code. So, if it is not set, what is the real "default" value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @Air-Git Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Air-Git** [comment]
Excellent, thanks. That's the solution. The default values are now clear.
