### ISSUE TITLE
Should be more clear that the command is not present in Exchange Online if it is missing.

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/office-docs-powershell#5658]
This command recently stopped appearing for me, I've tried both regular implicit remoting and the exchangeonlinemanagement preview module. Can this be confirmed?
![image](https://user-images.githubusercontent.com/15258962/82614370-8baf6880-9b7c-11ea-9b40-fda42037fccb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f5c012-649d-94d7-90d9-b92770da3ae8
* Version Independent ID: d76ce569-1f36-a857-4619-39382597eb55
* Content: [Search-AdminAuditLog (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/search-adminauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Search-AdminAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Search-AdminAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by JustinGrote** [comment]
Turns out this is a permissions issue, but the documentation is not clear enough to troubleshoot.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda Please merge the PR #5659 Thanks

**Comment by yogkumgit** [comment]
@chrisda  Thanks
