### ISSUE TITLE
ACLableSyncedObjectEnabled is now available to customers

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/office-docs-powershell#566]
The ACLableSyncedObjectEnabled parameter now allows customer admins to run the Enable-RemoteMailbox cmdlet and specify the object be an ACLableSyncedMailboxUser.  The documentation should be updated to provide this information for customers. -Kelly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3d8932-e958-6be5-1dd7-b0731115c4dd
* Version Independent ID: 2345fd23-d401-fbc7-38c0-4eb3c7695f0e
* Content: [Enable-RemoteMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/Enable-RemoteMailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/Enable-RemoteMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/Enable-RemoteMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Based on this issue and #567, I updated the ACLableSyncedObjectEnabled parameter/switch descriptions in Enable-RemoteMailbox, New-RemoveMailbox, Set-RemoteMailbox, and Set-Organization.
