### ISSUE TITLE
Article not complete

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5661]
Lots of {{ Fill in the Description }} 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02956d3d-520f-f9d9-11d4-e5cf60fcbead
* Version Independent ID: 5e586104-edeb-22ef-35fe-b266e8c5942c
* Content: [New-SPOTenantOrgRelation (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/new-spotenantorgrelation?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/New-SPOTenantOrgRelation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/New-SPOTenantOrgRelation.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @hwkwicre Thanks for your report, the article will be completed it comes out of preview.

> Currently this cmdlet is part of pre-release functionality

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @hwkwicre 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
