### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5664]
https://go.microsoft.com/fwlink/?LinkID=187810
This broken link appears in many articles, not just this one.
Please fix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2685d81b-b18e-ff84-333d-623f86be27e5
* Version Independent ID: b3f45fb2-eb83-d601-0f7d-57df79ddfb59
* Content: [Get-SPProduct (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spproduct?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Get-SPProduct.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Get-SPProduct.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
