### ISSUE TITLE
Purpose of keeping -UsageLogMaxSpaceGB parameter when it's not used by all SharePoint versions this page is applicable to

### ISSUE THREAD

**Issue by desmondkung** [MicrosoftDocs/office-docs-powershell#5666]
This article page applies to SharePoint Server 2010, 2013, 2016, and 2019.

-UsageLogMaxSpaceGB 
The parameter is not used in SharePoint Server.
Applies to:
SharePoint Server 2010, SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019

What's the point of keeping this parameter here when the parameter is totally inapplicable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dc8a481-11f1-3808-dd61-efc74bbd4249
* Version Independent ID: 524f48c5-f0ac-b3d3-575d-ee541c54bde1
* Content: [Set-SPUsageService (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spusageservice?view=sharepoint-ps&source=docs#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageService.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageService.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for noticing and reporting @desmondkung

**Comment by desmondkung** [comment]
> Thanks for noticing and reporting @desmondkung

You're welcome!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @desmondkung Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
