### ISSUE TITLE
RecordingStorageMode info missing

### ISSUE THREAD

**Issue by Obleyer** [MicrosoftDocs/office-docs-powershell#5668]
I would appreciate to know which are the available values for RecordingStorageMode in addition to Stream. 

Is it possible to store the data directly to the client hard disk ?

Thanks in advance

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@Obleyer Please provide the name of document you are referring to. Thanks

**Comment by yogkumgit** [comment]
@Obleyer We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by MrHinsh** [comment]
https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps
