### ISSUE TITLE
Missing details for parameter DeliverMessageAfterScan

### ISSUE THREAD

**Issue by stmccartney** [MicrosoftDocs/office-docs-powershell#5669]
The current version of Exchange Online PowerShell includes a parameter called DeliverMessageAfterScan, which corresponds to the Safe Links policy option "Wait for URL scanning to complete before delivering the message" in the UI, but this is not documented on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9665202f-dbb0-8c82-27b2-524f142529c7
* Version Independent ID: 1f9c9751-e9f0-a4bd-40de-7ba68739610a
* Content: [Set-SafeLinksPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-safelinkspolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@stmccartney, quite coincidently, I made massive updates to that topic (and New-SafeLinksPolicy and Set-ATPPolicyForO365) yesterday to match currently UI/reality (#5656). I just haven't pulled them to live yet. I'll do that now.

Thanks for the feedback.

Closing
