### ISSUE TITLE
ACLableSyncedObjectEnabled 

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/office-docs-powershell#567]
The ACLableSyncedObjectEnabled parameter now allows customer admins to run the Enable-RemoteMailbox cmdlet and specify the object be an ACLableSyncedMailboxUser.  The documentation should be updated to provide this information for customers. -Kelly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb103c0b-9021-3a77-0bf6-601df9a0fe38
* Version Independent ID: 561d8c53-5019-4a31-efa1-c2b635818f5a
* Content: [New-RemoteMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/New-RemoteMailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/federation-and-hybrid/New-RemoteMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/federation-and-hybrid/New-RemoteMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Based on this issue and #566, I updated the ACLableSyncedObjectEnabled parameter/switch descriptions in Enable-RemoteMailbox, New-RemoveMailbox, Set-RemoteMailbox, and Set-Organization.
