### ISSUE TITLE
Needs detail on expected behavior with Exchange Online

### ISSUE THREAD

**Issue by chscott** [MicrosoftDocs/office-docs-powershell#5671]
"Note: In Exchange Online, this cmdlet doesn't activate/enable a mailbox the same way it does in on-premises Exchange. To add a mailbox for an existing Azure AD account, you can simply add a license to the account by using the Set-MsolUserLicense cmdlet."

It's good to say that the behavior is different, but what is the difference? The way it is written implies that it will work (differently), but I get this error:

This task does not support recipients of this type. The specified recipient $user is of type UserMailbox. Please make sure that this recipient matches the required recipient type for this task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4712aef1-e05a-5711-684f-8c82ed7d1663
* Version Independent ID: 06ad90f5-2591-8180-3679-9f18a4525546
* Content: [Enable-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/enable-mailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Enable-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Enable-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@chscott, I reworded the note:

 Note: In Exchange Online, this cmdlet doesn't activate/enable mailboxes for existing users. To add a mailbox for an existing Azure AD account, you need to add a license to the account as described in [Assign licenses to user accounts](https://docs.microsoft.com/office365/enterprise/powershell/assign-licenses-to-user-accounts-with-office-365-powershell).

Basically, what you can do in Exchange Online is controlled by the parameters that are available in Exchange Online. I just confirmed the availability of parameters (some were incorrect) and modified the note to say this:

**Note**: In Exchange Online, you use this cmdlet to add archive mailboxes for existing users and  to enable auto-expanding archives. To add a mailbox for an existing Azure AD account, you need to add a license to the account as described in [Assign licenses to user accounts](https://docs.microsoft.com/office365/enterprise/powershell/assign-licenses-to-user-accounts-with-office-365-powershell).

Thanks for the feedback.

Closing
