### ISSUE TITLE
Summarization

### ISSUE THREAD

**Issue by carvalhorui** [MicrosoftDocs/office-docs-powershell#5672]
Is it possible to summarize network subnets inside a network site?
As example, if I have 192.168.0.0/24 and 192.168.1.0/24 on the same site, can I just create one TenantNetworkSubnet with 192.168.0.0/23?
Does Microsoft identify if a user is inside a network with a different bitmask or should I add the actual bitmask for each network?
This information is really important when we are configuring large topologies.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e478d695-809b-d6ef-8688-7c6b8eac3d77
* Version Independent ID: c2d63f83-b6db-236b-ba5b-5ee412c701b2
* Content: [New-CsTenantNetworkSubnet (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cstenantnetworksubnet?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/New-CsTenantNetworkSubnet.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTenantNetworkSubnet.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @carvalhorui, thank you for your feedback and help us to improve docs.microsoft.com.

Yes, you can summarize network subnets in this way. You need to add each internal network/subnet and trusted external IPs/subnets, but it also depends on the feature that you are configuring. For more information, please see:
https://docs.microsoft.com/microsoftteams/location-based-routing-plan
https://docs.microsoft.com/microsoftteams/direct-routing-media-optimization
https://docs.microsoft.com/microsoftteams/configure-dynamic-emergency-calling
https://docs.microsoft.com/microsoftteams/manage-your-network-topology

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @carvalhorui 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by carvalhorui** [comment]
Hello @dariomws! Thank you for your reply and sorry for the delay on mine.
I just think that when you say "You need to add each internal network/subnet", it conflicts with the possibility of summarization. The goal is to configure Local Media Optimization and the scenario is a site where a costumer has several internal networks like 10.1.1.0/24, 10.1.2.0/24, 10.1.3/24, 10.1.X.0/24... The Trusted IP for all of the networks is the same, but when I'm going to add the NetworkSubnets, I'm not sure if I could just add 10.1.0.0/16 for the whole NetworkSite. I mean, I can, but I'm not really sure if Microsoft will identify if a user with IP/Bitmask like 10.1.34.12/24 belongs to a NetworkSubnet 10.1.0.0/16. That would be great if Microsoft does this, but it's not clear for me if it will yet, sorry. Thanks again!

**Comment by dariomws** [comment]
Hi @carvalhorui, don´t worry.

Yes, I think you can just add 10.1.0.0/16. My apologies but I cannot provide you with this kind of support in more detail.
Docs feedback is available to improve documentation, we cannot provide any kind of support here. If you need more help, I think a better way is contact support, Microsoft Consulting Services or Fast Track.
If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
https://www.microsoft.com/industry/service
https://www.microsoft.com/fasttrack

Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @carvalhorui 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
