### ISSUE TITLE
Get-EXOMailboxPermission on Shared Mailbox where Identity contains ampersand

### ISSUE THREAD

**Issue by SteveAmico** [MicrosoftDocs/office-docs-powershell#5673]
It appears that when the Get-EXOMailboxPermission cmdlet is used on a Shared Mailbox where the Identity contains an ampersand, an error is thrown.  For example:

PS C:\ps-scripts> $mailbox.Identity
FP&A

PS C:\ps-scripts> Get-EXOMailboxPermission -Identity $mailbox.Identity
Get-EXOMailboxPermission : An error occurred while processing this request.. 
At line:1 char:1
+ Get-EXOMailboxPermission -Identity $mailbox.Identity
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ProtocolError: (:) [Get-EXOMailboxPermission], Exception
    + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.Exchange.Management.RestApiClie 
   nt.GetExoMailboxPermission

The corresponding Get-MailboxPermission cmdlet using the old V1 New-PSSession connection does not have this issue.  Thanks!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @SteveAmico, thank you for your feedback and help us to improve docs.microsoft.com.

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, contact us at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

When you report an issue, be sure to include the log files in your email message.

To generate the log files, replace <Path to store log file> with the output folder you want, and run the following command:
_Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All_

**Comment by SteveAmico** [comment]
Hi, Dario -

I was following the instructions on this page on how to provide feedback.
https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps

I did that through GitHub as requested, but I will also send mail to the address that you provided.  Thanks!


Steve Amico | IT Systems / Business Analyst
Kodak Alaris Inc. | 336 Initiative Drive, Rochester, NY 14624
steven.amico@kodakalaris.com<mailto:steven.amico@kodakalaris.com>
www.kodakalaris.com<http://www.kodakalaris.com/>
[cid:image001.png@01D6329F.CFD9E1C0]
Information contained in this e-mail transmission may be privileged, confidential and covered by the Electronic Communications Privacy Act, 18 U.S.C. Sections 2510-2521.

If you have received this e-mail transmission in error, please treat it as you would like your own email sent in error to be treated and

  *   notify us immediately by return email of the error and

  *   delete the message from your system without reading, forwarding or copying it.

Thank you in advance for your courtesy!



Controlled

**Comment by dariomws** [comment]
Thanks again for taking out some time to help us. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @SteveAmico 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
