### ISSUE TITLE
Wrong Description in Example 1 & 3

### ISSUE THREAD

**Issue by dh4099** [MicrosoftDocs/office-docs-powershell#5675]
The example states " If a file named company.aspx already exists, it won't perform the move." But the example code refers to company.docx.   Therefore I believe the example should state " If a file named company.doc already exists, it won't perform the move."

Example 3 has same type of issue....the code and description do not match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc0498c8-0815-f23b-39ea-7692bf4bab16
* Version Independent ID: 7bc9ccc7-b9f9-bbae-7c80-aa5dedb0d3f2
* Content: [Move-PnPFile (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/move-pnpfile?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Move-PnPFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Move-PnPFile.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @dh4099 
Thanks for your feedback. 
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/) a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @dh4099 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
