### ISSUE TITLE
Enabled property no longer presented

### ISSUE THREAD

**Issue by waceylanier** [MicrosoftDocs/office-docs-powershell#5678]
Using `Get-AntiPhishPolicy | Format-Table Name,Enabled,IsDefault` or any other variation trying to `Select-Object Enabled`, the Enabled property no longer exists for any AntiPhishing policy (default or custom). Both show a status of On in the webUI. Is this property being phased out?

![image](https://user-images.githubusercontent.com/19218185/82703625-e3f87000-9c39-11ea-94c3-93a405bf6a04.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4ed9e51-cc0a-f794-d33b-db719b5fff17
* Version Independent ID: 27c2961d-a66c-4f55-d52f-f9911dcd2185
* Content: [Get-AntiPhishPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-antiphishpolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Get-AntiPhishPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-AntiPhishPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@waceylanier, it appears you are running the command in an E3 or other Exchange Online organization without ATP?

The UI and the cmdlets are tightly coupled, so if a setting is available in the UI for a feature, it's also available in the corresponding cmdlets in PowerShell. The reverse isn't necessarily true; there are many examples of settings that are only available on cmdlets and not in the UI.

There are lots of \*Policy and \*Rule cmdlet 'families' in the service. Typically, you enable or disable the policy by using the  \*Rule cmdlet. For anti-phishing policies, there are separate Enable-AntiPhishRule and Disable-AntiPhishRule cmdlets for that purpose.

For anti-spam policies, enabled/disabled is stored in the State property on the Get-AntiPhishRule cmdlet (and I've seen that same property values use in other \*Rule cmdlets):

```powershell
PS C:\Users\chrisda> Get-AntiPhishRule | Format-List name,state

Name  : test
State : Enabled

Name  : Chrisda Test APP
State : Enabled
```

I realize that New-AntiPhishPolicy and Set-AntiPhishPolicy both have an Enabled parameter, which is unusual; I'm not sure what it means. As I said, in every other policy/rule feature that I can think of, you enable/disable in the rule cmdlet, not the policy cmdlet.

Here's what I see in my E5 tenant:

```powershell
PS C:\Users\chrisda> Get-AntiPhishPolicy | fl name,*enable*

Name                                : Office365 AntiPhish Default
Enabled                             : True
...

Name                                : PS Test
Enabled                             : True
...

Name                                : test
Enabled                             : True
...

Name                                : Chrisda Test APP
Enabled                             : False
...
```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by waceylanier** [comment]
@chrisda Thank you for your reply.

Please let me know if I am understanding you correctly + additional assumptions:

1. In the case of the Anti-Phishing Policy (E3-!ATP), an anti-phishing policy is enabled or disabled by the <Enable | Disable>-Anti-PhishRule, not necessarily by what the value of the Enabled property of Get-AntiPhishPolicy is?

2. Does this also apply to the Default Policy? _My main concern as I am trying to determine if the Default AntiPhishPolicy is enabled or if it can be disabled at all._

3. Assuming that *Rule governs the user \ domain scope, does this mean that the Default *Policy isn't being applied globally unless a *Rule is created & associated with it? 

4. Extending this question beyond the Default AntiPhishPolicy to the Default SafeLinks Policy. Is SafeLinks not truly protecting the tenant unless there is a SafeLinks Rule associated that configures the user scope?

**Comment by chrisda** [comment]
1. Yes, for custom policies that have been manually created. I would recommend creating a test policy in the UI (which creates the required policy and rule in PowerShell), disable it in the UI, and then check the property values in PowerShell. I'm certain that the State property in Get-AntiPhishRule will be Disabled, but I'm unsure of the Enabled property value in Get-AntiPhishPolicy and if/how it relates.

2. You can't disable the default anti-phishing policy. It's always enabled.

3. For the default policy, there's no corresponding rule in PowerShell. It's automatically applied to all recipients, and you can't filter who it applies to. And, per the previous point, it's always on, and you can't disable it. You can see the default policy with Get-AntiPhishPolicy, but there's no corresponding rule found with Get-AntiPhishRule.

4. Thankfully, I had to update the *-SafeLinks* and *-SafeAttachment* cmdlet topics last week, so I can speak intelligently. The default settings that are applied to all users are controlled by the Get/Set-ATPForO365 cmdlets (for both Safe Links and Safe Attachments). Only custom Safe Links policies (or Safe Attachment policies) have the policy + rule relationship in PowerShell. See [this topic](https://docs.microsoft.com/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp?view=o365-worldwide#atp-safe-links-policy-settings) for more information. I updated it last week.

**Comment by waceylanier** [comment]
@chrisda I really appreciate you helping me out.

**Comment by waceylanier** [comment]
@chrisda what if you delete the "Office365 AntiPhish Default"? (E5-Dev)

![image](https://user-images.githubusercontent.com/19218185/83170414-1b539a80-a0da-11ea-8873-a81005aa477e.png)

![image](https://user-images.githubusercontent.com/19218185/83170382-0e36ab80-a0da-11ea-8ee2-0079e4fd9eea.png)

**Comment by chrisda** [comment]
@waceylanier, in most cases, you can't delete the default policy (any type of policy). Whether or not the policy is actually the default policy is displayed by the IsDefault property on the policy. You can turn a custom policy into the default policy by using the MakeDefault switch on the Set- cmdlet, which then decouples the corresponding rule from the policy so the policy applies to everyone. There can be only one default policy

I didn't know you could force the deletion with the Force switch, but the question is, **why would you want to?** Unless the policy is very complex, and it would be too much effort to transfer the settings from the custom policy to the default policy, I can't think of any realistic scenarios where you would benefit from  turning a custom policy into the default policy and then deleting the built-in default policy.

**Comment by waceylanier** [comment]
@chrisda it is not that I would want to, but since it is possible I am trying to understand what happens when it is removed when there are no custom policies defined.

I would **assume** that if there are custom policies (regardless of user\domain scope), that $customPolicy's configured protections \ actions would still work.

Context: I break things to better understand them - from the PoV of an inept admin, insider threat, and\or attacker.
