### ISSUE TITLE
Microsoft code singing certificate expired on Exchange online V2 PowerShell module

### ISSUE THREAD

**Issue by dejanforo** [MicrosoftDocs/office-docs-powershell#5687]
Microsoft code singing certificate which is used to sign the Exchange Online V2 PowerShell module code has expired on May 2nd 2020 

<img width="303" alt="Microsoft code signing certificate expired" src="https://user-images.githubusercontent.com/53783806/82761511-52386080-9dfb-11ea-8d5f-b615360d8d93.png">

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dejanforo This issue is logged twice. So closing this one.
