### ISSUE TITLE
Article not complete

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5689]
Lots of
{{Fill Description}}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c99496f8-8869-aaf0-111e-65a6b6ba317b
* Version Independent ID: 11e16700-bb04-4b6a-fc82-fcd27e0f2a3a
* Content: [Set-CsOnlineNumberPortOutOrderPin (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinenumberportoutorderpin?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineNumberPortOutOrderPin.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineNumberPortOutOrderPin.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
