### ISSUE TITLE
Incomplete Article

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5693]
Lots of
{{Fill Description}}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f623dc5-07a8-b14c-b2a3-cecc1b0fe444
* Version Independent ID: cab90d23-801c-a5c1-af55-3af7ebb81642
* Content: [Copy-SPAccessServicesDatabaseCredentials (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/copy-spaccessservicesdatabasecredentials?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Copy-SPAccessServicesDatabaseCredentials.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Copy-SPAccessServicesDatabaseCredentials.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@MikeBazMSFT Pleas reply and oblige. Thanks

**Comment by MikeBazMSFT** [comment]
@yogkumgit You apparently tagged the wrong person. I don't see a reason for me to be tagged here.

**Comment by yogkumgit** [comment]
> @yogkumgit You apparently tagged the wrong person. I don't see a reason for me to be tagged here.

Apologies.

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Pleas reply and oblige. Thanks

**Comment by tseward** [comment]
@yogkumgit assign to me. This cmdlet does exist in 2019/2016 and likely exist in 2013 -- I'll spin up my VM later to verify.

**Comment by get-itips** [comment]
@tseward Trevor, any updates from your lab? did you find the cmdlets I couldn't in my lab version? Thanks
