### ISSUE TITLE
Get-FailedContentIndexDocuments Documentation not clear

### ISSUE THREAD

**Issue by mnegrinho** [MicrosoftDocs/office-docs-powershell#5694]
[Enter feedback here]
The existing documentation is not clear regarding the support of the cmdlet Get-FailedContentIndexDocuments in Exchange Online. While is says that the document applies to Exchange Online, it also wrongly states that the cmdlet is only available in on-premises environment.
![image](https://user-images.githubusercontent.com/20125463/82896091-3fce3c00-9f4d-11ea-8218-8a5ba446f9cc.png)
It's not true. The cmdlet is also available in Exchange Online despite it's implementation is somehow different from on-premises environment and ending always with the same error. Always existing with the "The component operation has failed".
![image](https://user-images.githubusercontent.com/20125463/82896507-f92d1180-9f4d-11ea-88f1-072deb29e542.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d543b7d1-e33b-a9f8-3c07-9355cb515054
* Version Independent ID: 6ebdf127-8c1a-42ca-3a85-534bae6300ed
* Content: [Get-FailedContentIndexDocuments (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-failedcontentindexdocuments?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-FailedContentIndexDocuments.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-FailedContentIndexDocuments.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mnegrinho, this appears to be a case where the cmdlet is available in the cloud, but it doesn't work. Also, I get the same error in Exchange 2019, but it runs without error in Exchange 2010 to Exchange 2016. I updated the introduction sentence accordingly.

Thanks for the feedback.

Closing
