### ISSUE TITLE
Boolean default value: None

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/office-docs-powershell#5697]
I am unable to understand what a boolean default value of "None" can mean. I can understand that, if you use the parameter, you need to supply a value: $true or $false. But what is the value of the attribute of a team if you don't use the (optional) parameter? How could anyone know, except by trial and error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/New-Team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @Air-Git, thank you for your feedback and help us to improve docs.microsoft.com.

The default value of each parameter in this article was updated this week. Please, check it and let me know if there is something else missing.

Thank you again!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @Air-Git 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
