### ISSUE TITLE
New-Team : Error occured while executing

### ISSUE THREAD

**Issue by m-neill** [MicrosoftDocs/office-docs-powershell#57]
When trying to create a new team I get the following error.
![image](https://user-images.githubusercontent.com/3170943/32678529-e9ccd6a8-c61f-11e7-920c-a7f7540f7c6d.png)

**Comment by kenwith** [comment]
I am not sure on this one. It looks like it isn't able to even run the cmdlet. This would be a good issue to open a support ticket on. I will leave this open though if anyone else can comment to help figure this out. I am sure others will run into the same issue too.

**Comment by ravgupms** [comment]
@m-neill - Is it consistently happening for you?

**Comment by m-neill** [comment]
I sorry for the late response.  Where would I open a support ticket for it?

I tried on two different O365 subscriptions and tested again today.  Still running into the same issue.

**Comment by kenwith** [comment]
When you sign into the admin page of your tenant you can open a service request there. Sign into your tenant then in the waffle menu (looks like a waffle icon) in the upper left choose Admin. Then on the left side there should be a Support tab. When you click that you should see a "New service request" option. Note that the UI might be slightly different depending on what version you are seeing.

**Comment by ravgupms** [comment]
We have published v0.9.1 which contains fix for New-Team. Let us know in case you face any other problem.

**Comment by kenwith** [comment]
Thanks @ravgupms  !  Closing this one out.
