### ISSUE TITLE
broken link appears in many articles

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5701]
https://go.microsoft.com/fwlink/?LinkID=187810
is a broken link and appears in many articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a0a17e0-a215-62a6-0a13-66b187dda502
* Version Independent ID: 2059a880-3689-67f0-ec01-3d7f717ae4ef
* Content: [Get-SPWorkflowConfig (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spworkflowconfig?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Get-SPWorkflowConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Get-SPWorkflowConfig.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
