### ISSUE TITLE
What exactly is ConferenceMode?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#5702]
Please clarify wht ConferenceMode is, how it differes to "normal".
The Product page does not mention this feature at all.

And please don't tell me to raise a ticket from within my tenant, this is a generic functionality which is documented, yet not understandable. Please clarify :)

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4128d55a-2a26-47be-04e7-6a71eece2143
* Version Independent ID: 7d0d9c25-c6f1-4ae3-b4e3-3b6de536ffa3
* Content: [New-CsCallQueue (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @DEberhardt, thank you for your feedback and help us to improve docs.microsoft.com.

@tomkau could you kindly help here to provide more information about this parameter? Thanks!

**Comment by CLYVR** [comment]
Conference Mode Disabled:  CQ call is presented to agent.  Agent answers.  Media streams are setup.  Depending on geographic location of the CQ call and agent there can be a delay in setting up the media streams which may result in some dead air and/or the first part of the conversation being cut off.

Conference Mode Enabled: CQ call is put into conference.  Agent answers and is brought into conference.  Media streams are already setup when agent is brought into conference.  No dead air or first bit of conversation being cut off.

**Comment by pupara** [comment]
@dariomws , thanks for submitting the edit. I would like to propose the following text. let me know if you are ok editing your submission. 
Conference Mode is Disabled: CQ call is presented to agent. Agent answers and media streams are setup. Based on geographic location of the CQ call and agent, there may be a slight delay in setting up the media streams which may result in some dead air and the first part of the conversation may being cut off.


Conference Mode is Enabled: CQ call is put into conference. Agent answers and is brought into conference. Media streams are already setup when agent is brought into conference thus no dead air and first bit of conversation may not be cut off.

**Comment by dariomws** [comment]
@pupara done! Thanks!

**Comment by DEberhardt** [comment]
Thank you very much! This is very helpful :)
