### ISSUE TITLE
Why is the no Set-TeamTag command to set Tags (to use @mention)

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/office-docs-powershell#5703]
Hello
it's sad that Microsoft calls the @mention feature in Teams 'Tags', because all the world uses 'Tags' to tag content.

Anyway:
why is there no PowerShell command to define / modify Teams Tags?
This would help a lot because this "Tags" usually defines Sub-Teams like e.g. the Marketing Team - which is the same on many projects. And each Team must manually define the same Tag.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hello @schittli, thank you for your feedback and help us to improve docs.microsoft.com.

For feature requests, I need to kindly redirect you to this resource https://microsoftteams.uservoice.com/. There, your suggestion will reach the product team.

**Comment by schittli** [comment]
Thank you very much, @dariomws for your answer,
but as we all know, 'uservoice' just has a nice name - in reality, it only serves to shut customers up: "Write it down and start to hope", is the message. The last time I had checked the statistics, only 1-2% of all items were reviewed at all. This is a shame for M$$!

So, please, if you (Microsoft) has no inner motivation to correct obvious bugs, then you can simply close the ticket. This would be more honest than recommending the 'uservoice' data grave.

**Comment by dariomws** [comment]
Hi @schittli,

If the item in uservoice get enough votes, it will be probably reviewed. If the item has only one vote it won´t be probably reviewed. There are thousands of items in uservoice with one vote, and a small number are popular and have hundreds or thousands of votes, that's why you see that only a few of them are reviewed.
A very good example:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/17010055-show-video-for-all-people-in-video-meeting

**Comment by schittli** [comment]
Hello @dariomws

Do you really want this discussion? It's very easy to prove that I'm right.

But yes, you're right: there are actually a few very few (compared to all issues) good examples.
But there are many examples which are ignored even if there are many UserVoices. 

Btw: Your 'great' example was ignored for about 3 years. Doesn't M$$ has Product Owners who understand that the requested feature "Show video for all people in Video meeting" is an important thing?? Do you really need 55'000 paying customers to ask for it?

Additionally, it is also true that UserVoices is a data grave because M$$ does not maintain them. 
If it were a professional issue system, a team would edit the inbox and summarize similar issues (do I really have to explain this?). It is obvious that M$$ does ignores thosee best practices, too.

Last but not least, there are also a lot of UserVoices with real error reports. 
Now the big question: how many paying customers have to make the effort to find the right UserVoice, study all the unmaintained to find similar issues and after one hour, finally give 1 Voice to it?

No, M$$ has almost no inner motivation to fix bugs or to finally complete missing features like this issue here. I'm sure it will get done - sometime.

**Comment by dariomws** [comment]
My apologies, you are totally right. I sent this information to the product group. This resource is specifically to improve docs.microsoft.com, it's all I can do.

Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @schittli 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
