### ISSUE TITLE
Syncronized Accounts / CountryInfo

### ISSUE THREAD

**Issue by BohrenAn** [MicrosoftDocs/office-docs-powershell#5705]
Hi,

Your statement is incorrect.
"Note that this cmdlet works only on room mailboxes that were created in the cloud (not on synchronized room mailboxes)."

The commandlet works also on synced AD Accounts. Except for these Parameters  "Street","PostalCode", "City", "State", "CountryOrRegion", "GeoCoordinates" and "Phone".

What parameter has to go in here. An Example would be very helpful.
 [-CountryOrRegion <CountryInfo>]

Regards
Andres

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 116f4327-66e8-52aa-5616-734e7f0930f5
* Version Independent ID: f47bc209-aa9e-f337-1cfa-b8a727a9f780
* Content: [Set-Place (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-place?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @BohrenAn, thank you for your feedback and help us to improve docs.microsoft.com.

A similar issue was opened some time ago. Please, check it for more information:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4780

**Comment by BohrenAn** [comment]
Hi @dariomws 

Thank's for mentioning the  #4780 Issue.
I updated the topic to say that the cmdlet only works on room mailboxes created in the cloud (not synchronized room mailboxes).

That is not true. Since you can use the Set-Place commandlet also on syncronized Accounts. Except for a frew Parameters. That is why i opened up this Issue

**Comment by dariomws** [comment]
Hi @BohrenAn,

Thank you again for your feedback. "Note that this cmdlet works only on room mailboxes that were created in the cloud (not on synchronized room mailboxes)." was added to the article because using this cmdlet on synchronized accounts is not fully supported.
If it works with some parameters you can use it but again, it´s not fully supported.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @BohrenAn 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by BohrenAn** [comment]
>If it works with some parameters you can use it but again, it´s not fully supported.
Could you then please clarify what is supported and what is not. As far as i can see, today only a few Attributes are not writeable, because they are synced from On-Prem.

Also i would like to know more about my second Question

What parameter has to go in here. An Example would be very helpful.
[-CountryOrRegion ]

Thank's and Regards
Andres

**Comment by dariomws** [comment]
Hi Andres,

Not sure about your question, I think it´s related to the possible values you can use on this parameter. You can find them searching for "ISO 3166-1 two-letter country code".

Also, I changed the word "works" by "is supported", and added one example including -CountryOrRegion. Hope it´s what you need.

Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by BohrenAn** [comment]
Hi Dario,

>Also, I changed the word "works" by "is supported", and added one example including -CountryOrRegion. Hope it´s what you need.

I am not very happy to just change the wording :)
1) If it is not supported - then somehow the new Roomfinder Feature in Outlook on the Web seems to be incomplete. Only supporting CloudOnly Szenarios would limit its use dramatically. As i see in my daily life, that most of the Enterprises uses AAD Connect to syncronize theyr Active Directory.

2) If it is only partly supportet - or only several Parameters can't be used, it would be nice to know. I had tested it with a synced mailbox and where thinking the cmdlet was somehow broken, until i tried with a CloudOnlyMailbox. And then tested Parameter by Parameter also on a synchronized Mailbox. I found out that only these Properties can't be set on a synchronized Mailbox
[-Street <String>]
[-PostalCode <String>]
[-City <String>]
[-State <String>]
[-Phone <String>]
[-CountryOrRegion <CountryInfo>]
[-GeoCoordinates <GeoCoordinates>]

Maybe check the Comments on this Article. Someone lost his work spent on using the Command.
https://techcommunity.microsoft.com/t5/exchange-team-blog/how-to-configure-the-new-room-finder-in-outlook/bc-p/1420928#M28320

Thanks for the Update. I tried with your example on CloudOnly Room Mailbox.

PS C:\> Set-Place -Identity SitzungszimmerCloudOnly -CountryOrRegion "AU"
Interner Serverfehler.
    + CategoryInfo          : NotSpecified: (:) [Set-Place], TaskException
    + FullyQualifiedErrorId : [Server=DB8PR10MB2683,RequestId=3b672a46-b386-42d5-997d-25933426a6ec,TimeStamp=01.06.2020 15:03:50] [FailureCategory=C
   mdlet-TaskException] 7129A5A6,Microsoft.Exchange.Management.RecipientTasks.SetPlace
    + PSComputerName        : outlook.office365.com

The Documentation says the Value has to be the Type "CountryInfo". My Search lead to this. But i have no clue, how to create that type in Powershell.
https://docs.microsoft.com/en-us/previous-versions/office/exchange-server-api/ff327656(v=exchg.150)

**Comment by dariomws** [comment]
Hi @BohrenAn, the article was updated based on new information from the product group. You will see it live in some hours.

Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by fbastone** [comment]
Has there been any further update on this?  I experienced attributes such as AudioDeviceName, VideoDeviceName, etc dissappear after a few days.  We are in hybrid mode and the room was created directly online.  Please advise.
