### ISSUE TITLE
Disconnect-ExchangeOnline always prompts for confirmation

### ISSUE THREAD

**Issue by jrandRTCC** [MicrosoftDocs/office-docs-powershell#5706]
The command Disconnect-ExchangeOnline will always prompt for confirmation. The -confirm switch appears to do nothing. This is an issue for scripting.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @jrandRTCC, thank you for your feedback and help us to improve docs.microsoft.com.

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, contact us at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

When you report an issue, be sure to include the log files in your email message.

To generate the log files, replace <Path to store log file> with the output folder you want, and run the following command:
Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All

Source: https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2#report-bugs-and-issues

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @jrandRTCC 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
