### ISSUE TITLE
AgentAlertTime diverges between NEW and SET commands

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#5709]
Buenas dias!

https://docs.microsoft.com/en-us/powershell/module/skype/new-cscallqueue?view=skype-ps
states 30-180s for the AgentAlertTime parameter

https://docs.microsoft.com/en-us/powershell/module/skype/set-cscallqueue?view=skype-ps
states 15-180s for the same

I know 15s is a valid setting, as I can see it on live CallQueues, so I am going to assume that New-CsCallQueue requries an update.
Could not test whether the commandlet lets you define it, though the UI does.

Side note: I do remember that Skype had 10s for this, which was useful for Serial to cut down on the time needed to find an agent. Are there any changes planned to this?

Thank you,
David
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4128d55a-2a26-47be-04e7-6a71eece2143
* Version Independent ID: 7d0d9c25-c6f1-4ae3-b4e3-3b6de536ffa3
* Content: [New-CsCallQueue (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hola David, muchas gracias por tu comentario y por ayudarnos a mejorar docs.microsoft.com.

Hi David, thank you for your feedback and help us to improve docs.microsoft.com. 

You´re right, 15 seconds is the start value, I´m updating the New-CsCallQueue article. Sorry, but I don´t have any information about if it will be updated to 10 seconds.

**Comment by DEberhardt** [comment]
Hola y gracias! I am learning still :)
No worries about the roadmap, if someone has it though, or even already considered it I'd be happy to know, but not a main criteria at the moment. 
More important is that there is consistency now :)

**Comment by yogkumgit** [comment]
@dariomws dar Thank you very much for the contribution and updating the documentation with PR. @DEberhardt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
