### ISSUE TITLE
Add parameter DefaultLinkToExistingAccess

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#5710]
The PowerShell cmdlet [Set-SPOSite](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnptenant?view=sharepoint-ps) offers to set the default Sharing link to "Existing Access" by means of the `DefaultLinkToExistingAccess` switch, e.g.
```powershell
Set-SPOSite -Identity https://contoso.sharepoint.com/sites/site1 -DefaultLinkToExistingAccess
```

Is there any chance that is parameter will be added on Tenant level as well?
For example in the [Set-PnPTenant](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnptenant?view=sharepoint-ps) cmdlet?

Another related question: 
Why does the parameter `DefaultSharingLinkType` not include an option to go for "ExistingAccess" or alike? The documentation states the following:
> ### -DefaultSharingLinkType
> [...]
> The values are: None Direct Internal AnonymousAccess

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Markus-Hanisch 
Markus, how are you?
Sorry if I misunderstood your message, if I do, please let me know, however I think that your inquiries will be better suited for [SharePoint UserVoice](https://sharepoint.uservoice.com/). As here we are limited  to documentation fixes.

**Comment by Markus-Hanisch** [comment]
@get-itips 
Well, maybe you are right. Can you tell me where I can find the Code for the existing Cmdlet `Set-SPOSite` cmdlet.
Maybe I can figure out how to adjust the PnPSite cmdlet accordingly to provide the same parameter(?)

**Comment by get-itips** [comment]
@Markus-Hanisch 
Markus, thanks for getting back.
SharePoint Online cmdlets are not open-sourced (Set-SPOSite),  so you have the option to suggest changes and additions using a resource like user voice, however SharePoint PnP cmdlets are open sourced and they are community-driven. I recommend visiting [this resource](https://github.com/pnp/PnP-PowerShell) and also you can find the code for Set-PnPSite [here](https://github.com/pnp/PnP-PowerShell/blob/dev/Commands/Site/SetSite.cs).

Hope this helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Markus-Hanisch Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
