### ISSUE TITLE
Publish item/file without approval

### ISSUE THREAD

**Issue by evlo** [MicrosoftDocs/office-docs-powershell#5712]
Set-PnPFileCheckedIn can't produce major version if library does not have content approval, just drafts, it does not work for items.

Would be nice to have option to use pnp to publish items

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @evlo 
How are you ? 

I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/) a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @evlo 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
