### ISSUE TITLE
Not supported by PST Import team

### ISSUE THREAD

**Issue by moditpro365** [MicrosoftDocs/office-docs-powershell#5714]
This should be noted that it is not supported by the PST Upload team to do PST imports into Exchange Online and should instead use the documented method [here](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7d1f46c-b436-12ee-42b9-616963520de7
* Version Independent ID: 1ad16056-d5c5-a815-c6d6-8e38b96fdbd8
* Content: [New-MailboxImportRequest (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-mailboximportrequest?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/New-MailboxImportRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MailboxImportRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @moditpro365, thank you for your feedback and help us to improve docs.microsoft.com.

Are you from Microsoft?

@chrisda could you kindly help to confirm this information? I understand that if you upload the PST files to an Azure Storage you can use this cmdlet with -AzureBlobStorageAccountUri and -AzureSharedAccessSignatureToken parameters.

**Comment by moditpro365** [comment]
I wrote an entire process to migrate enterprise wide PSTs to Online Archive. When I opened a support request to Microsoft about errors or issues I was seeing I was told it wasn’t a supported method for importing PSTs and to use the documented process in the link I provided initially. Considering the time spent developing the process with the use of the PowerShell cmdlet, it seems right it should be documented if it’s not supported. I was using the process as documented on the page. Here’s the response I received from MSFT:

“Use PowserShell directly to create MRS Import requests is NOT supported by the "PST Import service team". As this completely bypasses all the orchestration that our O365 PST Import service performs on top of MRS import requests (monitoring of transient failures between Azure and EXO, refresh of the updates of the import requests in the Import service UI etc).

You should use PowerShell simply to monitor statuses of MRS Import requests (Get-MailboxImportRequest and/orGet-MailboxImportRequestStatistcs) and NOT New/Suspend/Resume/Remove-MailboxImportRequest, unless if advised by us while troubleshooting issues.

The only supported scenario is :

1/ Upload the PSTs using azcopy.exe (or ship a drive containing the PSTs), into the dedicated Azure Storage blob that is created by our "O365 PST Import service" the first time customer retrieves a SAS key from his Import service portal.
We cannot choose the type of Storage to be used in this scenario.

2/ Use our Import service portal to create a PST Import job (by submitting a CSV mapping file). This service will connect to the dedicated Azure Storage blob (created in the step above) and will create and monitor all the individual MRS Import requests and orchestrate all the process.”

**Comment by dariomws** [comment]
@moditpro365 thank you so much for all this very detailed information. I´m applying an update to the article, and I´m waiting now for approval.

Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by moditpro365** [comment]
Sounds good!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @moditpro365 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
