### ISSUE TITLE
Clarification on Alias and PrimarySmtpAddress

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/office-docs-powershell#5719]
In the document it says "When you create an Office 365 Group without using the EmailAddresses parameter, the Alias value _you specify_ (my italics) is used to generate the primary email address". But in the next paragraph it says that, if you don't specify an alias, then one is created. In that case, is the primary smtp address generated, or not?
If you swapped the two paragraphs around, would it be correct to say (paraphrasing):

1. If you don't specify a primary smtp address, or other email addresses, then one is created automatically from the alias value [omit "you specify"] and the primary mail domain of the tenant
2. If you don't specify an alias, then one is automatically created?

i.e. the primary smtp address will be created from the alias, whether you specified it or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e8ec16-da68-43b4-0cc0-32a450245747
* Version Independent ID: cb374ec2-99c3-7186-66ed-c037a678e946
* Content: [New-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@Air-Git, yeah there's a lot going on in there. Both of your numbered statements are true. And now that I look at it, it's actually more clear if you reverse the order (and remove the "you specify" text):

- If you don't use the Alias parameter when you create an Office 365 Group, the value of the DisplayName parameter is used for the Alias value. Spaces are removed, unsupported characters are converted to question marks (?), and numbers may be added to maintain the uniqueness of the Alias value.

- When you create an Office 365 Group without using the EmailAddresses parameter, the Alias value is used to generate the primary email address (\<alias\>@\<domain\>). Supported Unicode characters are mapped to best-fit US-ASCII text characters. For example, U+00F6 (ö) is changed to oe in the primary email address.

I updated the topic in this way.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for updating the documentation with PR. @Air-Git 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
