### ISSUE TITLE
Permissions needed to use CmdLet

### ISSUE THREAD

**Issue by Forket** [MicrosoftDocs/office-docs-powershell#5721]
It would be nice to mention which permission needed to use this function.
As from practice, I can connect to site using Azure App having Sites.Read.All permission but getting "Access denied" error when sending email

![image](https://user-images.githubusercontent.com/6735288/83116649-5b138580-a0cc-11ea-872a-c15ec4d7ae90.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdca22e-1adf-6a28-a894-64f2abb8b56a
* Version Independent ID: a5827980-5bce-8033-a520-d1bc22060df5
* Content: [Send-PnPMail (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/send-pnpmail?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Send-PnPMail.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Send-PnPMail.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Forket 
How are you?
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/) a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Forket 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
