### ISSUE TITLE
Unable to Filter AddressBookPolicy on Get-Mailbox or Get-EXOMailbox

### ISSUE THREAD

**Issue by JFPHC** [MicrosoftDocs/office-docs-powershell#5724]
Unable to use the -filter to filter by AddressBookPolicy on either the Get-Mailbox or Get-EXOMailbox command, I can get all then filter with a Where-Object but this makes the script take considerably longer

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @JFPHC, thank you for your feedback and help us to improve docs.microsoft.com.

I tested it in my lab and it´s working:
![image](https://user-images.githubusercontent.com/33589238/83299305-4dddc000-a1cc-11ea-8885-946913d161ac.png)

In the following article:
https://docs.microsoft.com/powershell/exchange/exchange-server/recipient-filters/filter-properties
You can find this information:
"This filter requires the distinguished name of the address book policy. For example, Get-Mailbox -Filter "AddressBookPolicy -eq 'CN=Contoso ABP,CN=AddressBook Mailbox Policies,CN=Contoso Corporation,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=contoso,DC=com'".
You can find the distinguished names of address book policies by running this command: Get-AddressBookPolicy | Format-List Name,DistinguishedName."

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @JFPHC 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
