### ISSUE TITLE
Default StartDate?

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/office-docs-powershell#5725]
[Enter feedback here]

The article doesn't mention how far back this cmdlet looks by default, or that the startdate cannot be older than 30 days from the current date. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143f2a00-fe2c-cbdb-0378-6da3bddcd04a
* Version Independent ID: adbde313-92e0-aef0-ab45-3d68078db792
* Content: [Get-MailDetailTransportRuleReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-maildetailtransportrulereport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailDetailTransportRuleReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MailDetailTransportRuleReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @terrogin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
