### ISSUE TITLE
Inaccuracy in Alias

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/office-docs-powershell#5727]
In the document it says "When you create an Office 365 Group without using the EmailAddresses parameter, the Alias value you specify is used to generate the primary email address". But in the next paragraph it says that, if you don't specify an alias, then one is created. In that case, is the primary smtp address generated, or not?
If you swapped the two paragraphs around, would it be correct to say (paraphrasing):

1. If you don't specify a primary smtp address, or other email addresses, then one is created automatically from the alias value [omit "you specify"] and the primary mail domain of the tenant
2. If you don't specify an alias, then one is automatically created?

i.e. the primary smtp address will be created from the alias, whether you specified it or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e8ec16-da68-43b4-0cc0-32a450245747
* Version Independent ID: cb374ec2-99c3-7186-66ed-c037a678e946
* Content: [New-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Air-Git, this appears to be the exact same question about the same cmdlet in #5719, which I answered and fixed, so I'm closing this one.

**Comment by Air-Git** [comment]
Sorry about that. In my Github, the issue showed as not submitted.
