### ISSUE TITLE
Alias values not respected by GUI

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/office-docs-powershell#5728]
I don't know the right place to record this, but the special characters allowed in an Alias are not allowed if you create a group in one of the Office 365 portals. These only allow underscore, dash, period and single quote.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e8ec16-da68-43b4-0cc0-32a450245747
* Version Independent ID: cb374ec2-99c3-7186-66ed-c037a678e946
* Content: [New-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Air-Git, the important question is: if you create the O365 group in PowerShell using a character that's not available in the portal, what happens? Does the O365 become unmanageable in the portal? If so, that's definitely worth calling out in the cmdlet reference topic.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the contribution and digging deep into it.  @Air-Git We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
