### ISSUE TITLE
Correction to New-ClientAccessRule parameters

### ISSUE THREAD

**Issue by DGuest44** [MicrosoftDocs/office-docs-powershell#573]
In the parameters for the command the -UsernameMatchesAnyOfPatterns states that "This parameter accepts text and the wildcard character (*) (for example, *jeff*, but not jeff*)"

In the summary table at the bottom it states "Accept wildcard characters: False" 

One of these statements must be incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ff3b1b-938c-1858-043f-bc6f8fc9a156
* Version Independent ID: 754c6644-e09e-5474-f6a3-4da35fb068c1
* Content: [New-ClientAccessRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/new-clientaccessrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/New-ClientAccessRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/New-ClientAccessRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nsshommo** [comment]
Thanks @DGuest44 for your feedback. After consulting with @chrisda I am updating this cmdlet now.

Accept wildcard characters will be True for the parameter named -UsernameMatchesAnyOfPatterns.
