### ISSUE TITLE
Incorrect example in Remove-ComplianceTag

### ISSUE THREAD

**Issue by pkothare** [MicrosoftDocs/office-docs-powershell#5736]
Example 1 for [`Remove-ComplianceTag`](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-compliancetag?view=exchange-ps) has the incorrect command reference:

```
IRemove-ComplianceTag -Identity "HR Content"
```
It should be:

```
Remove-ComplianceTag -Identity "HR Content"
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b35332a-710e-625a-16b1-630918916181
* Version Independent ID: d15fb035-fa45-7db9-e098-91f6859d8690
* Content: [Remove-ComplianceTag (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-compliancetag?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-ComplianceTag.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-ComplianceTag.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit
