### ISSUE TITLE
Last example - wrong parameter

### ISSUE THREAD

**Issue by matzhoog** [MicrosoftDocs/office-docs-powershell#5738]
The last example has parameter "-RowFilter", but I think it should be "-RowLimit" instead.

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: e8b96547-c659-bdf3-a6b6-69a2c94689fc
* Version Independent ID: b9aa6d28-19b9-ab4e-1b45-2f1f9629a2c8
* Content: [Get-PnPSearchCrawlLog (sharepoint-pnp)](https://docs.microsoft.com/sv-se/powershell/module/sharepoint-pnp/get-pnpsearchcrawllog?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSearchCrawlLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSearchCrawlLog.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @matzhoog 
Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/) a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @matzhoog 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
