### ISSUE TITLE
Workload Property Inaccurate

### ISSUE THREAD

**Issue by ryanwalker726** [MicrosoftDocs/office-docs-powershell#5742]
Whenever querying the Workload property, it always lists all workloads (except for Teams), regardless of which workload the retention policy is actually applied.

PS C:\WINDOWS\system32> Get-sccRetentionCompliancePolicy
 
```
Name                    Workload                                                      Enabled Mode   
----                    --------                                                      ------- ----   
Exchange Online         Exchange, SharePoint, OneDriveForBusiness, Skype, ModernGroup True    Enforce
OneDrive for Business   Exchange, SharePoint, OneDriveForBusiness, Skype, ModernGroup True    Enforce
SharePoint Online       Exchange, SharePoint, OneDriveForBusiness, Skype, ModernGroup True    Enforce
Teams Chat              Exchange, SharePoint, OneDriveForBusiness, Skype, ModernGroup True    Enforce
Teams Retention         Exchange, SharePoint, OneDriveForBusiness, Skype, ModernGroup True    Enforce

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90b171a4-fec4-ce7c-6b09-9b1225a6306f
* Version Independent ID: b8406904-02b5-2b53-36d2-d9a428f32455
* Content: [Get-RetentionCompliancePolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-retentioncompliancepolicy?view=exchange-ps#description)
* Content Source: [exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-RetentionCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @ryanwalker726, thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ryanwalker726** [comment]
Thank you, Dario...  I have opened a ticket in my tenant and can also
reproduce in a trial tenant that I created.  Our case rep. indicated that
the property is working as designed and suggested that I submit a change
request for the documentation to be updated (hence this thread).

Either the property is broken or the documentation is wrong, but contacting
support for both has pointed me to the other.

Thanks,
Ryan

**Comment by dariomws** [comment]
@ryanwalker726, ok I agree. I´m applying an update to the article until the cmdlet is updated and show actual workload in the policy.

Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @ryanwalker726 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ryanwalker726** [comment]
Thank you very much, Dario and Yogesh.

I've sent a follow-up to my case rep. to encourage them to forward it to
the product team to be addressed at a technical level, but at least now the
public documentation reflects the actual behavior of the property.

I appreciate your assistance.

Thanks,
Ryan
