### ISSUE TITLE
LastUserAction property has been dropped

### ISSUE THREAD

**Issue by TheBigBear** [MicrosoftDocs/office-docs-powershell#5746]
[Enter feedback here]
the older Get-MailboxStatistics cmdlet used to support the LastUserActionTime property. the only way to now surface that I am aware of is to use Export-MailboxDiagnosticsLog that is badly documented and I believe it should have been kept as a selectable property in this new EXO cmdlet.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68aa3776-5347-6299-e566-33f018a2e96c
* Version Independent ID: 9feff981-1e32-11f6-2417-062e09ddaa3a
* Content: [Get-EXOMailboxStatistics (exchange)](https://docs.microsoft.com/en-gb/powershell/module/exchange/get-exomailboxstatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-EXOMailboxStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-EXOMailboxStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by TheBigBear** [comment]
And the whole consistency across ps cmdlets of related properties LastUserInteractionTime or LastUserActionTime reporting really needs improving. As it is quite inconsistent. And the meaning of the various Last.... terms could really also do with documentation that explains and actually says what they mean and what they do not indicate as well. So that articles like these 3 do not all come to different assumptions and suggestions of 'best' practice. 

https://petri.com/exchange-online-exposes-new-mailbox-activity-data

https://www.michev.info/Blog/Post/2408/new-properties-added-to-get-mailboxstatistics-output

https://gallery.technet.microsoft.com/office/Export-Office-365-Users-05819ea5

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @TheBigBear, thank you for your feedback.

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, contact us at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

When you report an issue, be sure to include the log files in your email message.

To generate the log files, replace <Path to store log file> with the output folder you want, and run the following command:
Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @TheBigBear 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by aakash-shah** [comment]
Just to close the loop on this since it is linked in web searches, we can specify `-Properties LastUserActionTime` to get the LastUserActionTime. So in your example, you can use this to retrieve this property:
`Get-EXOMailboxStatistics -Identity 'USER-UPN' -Properties LastUserActionTime | Select LastUserActionTime`
