### ISSUE TITLE
Site title not renaming

### ISSUE THREAD

**Issue by VishnuMohan259** [MicrosoftDocs/office-docs-powershell#5749]
Hi ,
I tried to rename Modern sharepoint site with o365 groups

Start-SPOSiteRename -Identity https://{tenant}/sites/ABCD -NewSiteUrl https://{tenant}/sites/ABCDRenamed -NewSiteTitle ABCDRenamed

It renamed my url successfully but the office group related to the site not renaming. I tried to rename manually from admin center which is working perfectly. I'm using sharepoint online management shell latest version so issue is not related to that . Please let me know what will be the cause of the issue

Thanks and Regards

Vishnu

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @VishnuMohan259 How are you?
The feature is still in preview, as the article says.
And also, AFAIK this cmdlet will not rename the related group, I recommend this resource to add that suggestion https://sharepoint.uservoice.com/

Hope this info helps you.

**Comment by VishnuMohan259** [comment]
Hi,

Thanks for the replay.

 I mean I can rename site URL but can't change site name. Intially it renaming but when I try to refresh the url site name going back to old name.  I tried to check group at that time then found that sitename and group name are related. So my question is simple is it possible to change sitename ? If yes then i'm not able to update with this command. Is there any other option from where I can update site name instead of updating whole url.

Thanks and regards 

Vishnu

**Comment by get-itips** [comment]
> Hi,
> 
> Thanks for the replay.
> 
> I mean I can rename site URL but can't change site name. Intially it renaming but when I try to refresh the url, site name going back to old name. I tried to check group at that time then found that sitename and group name are related. So my question is simple is it possible to change sitename ? If yes then i'm not able to update with this command. Is there any other option from where I can update site name instead of updating whole url.
> 
> Thanks and regards
> 
> Vishnu

Try with https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite using the -Title parameter

**Comment by VishnuMohan259** [comment]
Hi ,

Thanks for the quick response. I tried to execute the command but returning error that site collection is group site collection

![Error](https://user-images.githubusercontent.com/53042453/83595453-aec81800-a57f-11ea-9a25-0d5d5d5cfcfe.PNG)

**Comment by get-itips** [comment]
@VishnuMohan259 
How are you ? Forgot about the fact that you were trying to change **the title** for a group connected site collection, right?
I think that, for now, you will have to change the site title thru the admin panel or Settings - Site Information. I found the suggestion in [uservoice](https://sharepoint.uservoice.com/forums/330318-sharepoint-administration/suggestions/39796861-changing-the-office-36-group-site-title-using-powe).

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @VishnuMohan259 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
