### ISSUE TITLE
GroupId

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/office-docs-powershell#5759]
We can create a team from an existing Office 365 ("Unified") group, by specifying the "GroupId". 
But what is a "GroupId"? GroupId does not seem to be a property of a Unified Group, at least not when using Get-UnifiedGroup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by Air-Git** [comment]
GroupId is a property of a team, at least it is the id of the parent group. But it is not a property of a Unified group, which has id, identity, alias, GUID but not GroupId. It seems illogical to create a team from a Unified group by asking for something that is not a property of the group.
It seems to make more sense either to ask for one of the properties of the Unified Group, when creating a team from it. We already use Get-UnifiedGroup with -Identity. If it must be the Object Id of the AAD group, then maybe the parameter name should be changed to Object Id.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Air-Git 
In my tests, I used the _ExternalDirectoryObjectId_ UnifiedGroup property

![image](https://user-images.githubusercontent.com/36666927/83757728-4f353f80-a647-11ea-9a60-3538fdd3f29d.png)

![image](https://user-images.githubusercontent.com/36666927/83757826-75f37600-a647-11ea-89a1-67efb7f0909f.png)

I can understand that the "GroupId" name can be misleading, for that, I kindly ask you to create a suggestion to [Teams UserVoice](https://microsoftteams.uservoice.com/).

What I can do at Documentation level, is add a text to the article clarify and help users like you, to find the correct id.

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Air-Git Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Air-Git** [comment]
I think all it needs in the documentation is to say that GroupId refers to the ExternalDirectoryObjectId of the parent group.
I think the misunderstanding in the cmdlet arises because GroupId is a property of the team, but obviously the team with that property does not exist before you create it from a unified group, which does NOT have that property.

**Comment by get-itips** [comment]
@Air-Git a clarifying note it's on the way to be published on the live version of the article. Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Air-Git Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
