### ISSUE TITLE
Need a CmdLet to create Contact Groups

### ISSUE THREAD

**Issue by markdmac** [MicrosoftDocs/office-docs-powershell#5761]
My company just forced us to switch from Skype to Teams.  Skype allowed Distribution Lists in chat, but Teams does not.  We need cmdlets for: 
New-ContactGroup 
New-ContactGroupMember
Remove-ContactGroup
Remove-ContactGroupMember

This will at least allow us to get the members of a DL and pipe that to be added to a contact group.  There are hundreds of upvotes for this topic in UserVoice.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94694082-c529-5654-1734-57514ec17a1f
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [Microsoft Teams PowerShell](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @markdmac ! how are you?
We are limited to documentation changes and fixes here, and exactly as you said, UserVoice is the place to suggest that kind of idea for it to reach the product team. Can you share the suggestion url so I can vote for it? Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @markdmac 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
