### ISSUE TITLE
Create team from group

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/office-docs-powershell#5763]
The MS-recommended way to create a team is to create a unified group first, then create a team from it. I think this is just because of the sync delay between AAD and Teams Service.
Currently this means we need to authenticate twice when creating the team: once to Exchange Online or Azure AD to find the Id of the group with the display name we intend to use; and once to Teams to create the new team.
If we use MFA, as strongly recommended, then we can't authenticate to Exchange Online with \-Credential. We need to supply a UPN. But when we authenticate to Teams, we cannot supply the already supplied UPN. We have to type it again. 
Is there a way to avoid having to type the username and password twice? Or maybe we should turn to Microsoft Graph?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Air-Git 

I know the team is constantly trying to improve the PowerShell module, and they listen to suggestions in [Teams UserVoice](https://microsoftteams.uservoice.com/), if you want to suggest that. As here we are limited to documentation changes, said that, can you kindly share the article that states this 

> The MS-recommended way to create a team is to create a unified group first, then create a team from it.

Maybe I can check if that is still the recommendation.

Thank you

**Comment by Air-Git** [comment]
It's the recommendation in the Graph documentation. [Creating Teams](https://docs.microsoft.com/en-us/graph/teams-create-group-and-team). But I think this is simply a pointer to the fact that groups take time to be available, You need to set properties of the group e.g. to disable welcome notifications, so you need to use Exchange Online anyway, and may as well use it to create the group first.

**Comment by get-itips** [comment]
@Air-Git I agree with you, Exchange Online Ps allows you to better customize a group, so probably you will start with it.
If you still want to suggest any idea to the Product Team, remember  you can use the UserVoice I referenced.

**Comment by Air-Git** [comment]
I'm afraid I have no expectation that User Voice will result in any changes. My only aim is to help make the documentation accurate and helpful for an engineer trying to implement it.

**Comment by get-itips** [comment]
> I'm afraid I have no expectation that User Voice will result in any changes. My only aim is to help make the documentation accurate and helpful for an engineer trying to implement it.

I appreciate you coming here to leave feedback, maybe this feedback is useful for you or can pass it along @tameemansari ? I appreciate.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Air-Git 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
