### ISSUE TITLE
Connect-MicrosoftTeams not working in GCC High when using -AadAccessToken

### ISSUE THREAD

**Issue by patrickabel** [MicrosoftDocs/office-docs-powershell#5764]
In the process of building out a SPO Site/Teams provisioning solution for a client, I have stumbled upon a but with the **Connect-MicrosoftTeams** cmdlet and am hoping to get some assistance.

For context, my solution uses an AAD app (running with app-only permissions) to extend SharePoint Site Designs through an Automation Runbook in Azure (running PowerShell). However, the issue reported below was run locally to limit variables here.

### Issue
When connecting to **Connect-MicrosoftTeams** for a GCC High tenant, the following property must be supplied: **-TeamsEnvironmentName TeamsGCCH**. This works fine when authenticating via a prompt with a username and password. However, this fails when authenticating by supplying a **-AadAccessToken** parameter. See error below:
![image](https://user-images.githubusercontent.com/1153976/83330780-326bc700-a257-11ea-9369-a0d107a5f49a.png)

The issue looks to be unique to the combination of -TeamsEnvironmentName and -AadAccessToken as if I omit either, the connection will work (although won't suffice for my solution).

**Working by omitting the -TeamsEnvironmentName parameter:**
![image](https://user-images.githubusercontent.com/1153976/83330837-7ced4380-a257-11ea-9c8c-9a06b4ffba7e.png)

**Working by omitting the -AadAccessToken parameter:**
![image](https://user-images.githubusercontent.com/1153976/83330852-91314080-a257-11ea-8dcc-2ff3594d3ae4.png)

Please advise! Based on my testing, Connect-MicrosoftTeams simply doesn't work when needing to both connect to a GCC High tenant and needing to pass parameters to authenticate via a token (app-only) instead of requiring user-input.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @patrickabel How are you?
Yes, they are in different parameter sets so currently you won't be able to use them at the same time.
I know this information could be useful as feedback for @tameemansari

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @patrickabel 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
