### ISSUE TITLE
Clarification regarding WinRM

### ISSUE THREAD

**Issue by Backspaze** [MicrosoftDocs/office-docs-powershell#5765]
According to [this section](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#what-do-you-need-to-know-before-you-begin) WinRM needs to be enabled, but according to [this paragraph](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps#version-035820) you should be able to: 
> Use EXO V2 cmdlets even if WinRM Basic Auth is disabled on client machine.

...with the added note that:

> Note that remote PowerShell cmdlets require WinRM Basic Auth, and they won't be available if it's disabled.

If WinRM needs to be enabled then that means that the service needs to be running. I don't have that service running (but I've checked that Basic authentication is enabled) but am still able to use the Exchange Online PowerShell V2 module without issues so far.

So if I interpret the quotes above correctly it means that I will be able to use the Exchange Online PowerShell V2 module without limitations even if WinRM is disabled/not running, and I really only need to run the service if I want to be able run other remote PowerShell commands on the client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @Backspaze Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
