### ISSUE TITLE
Meaning of "Identity"

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/office-docs-powershell#5766]
I am puzzled by the use of "Identity" in Get-UnifiedGroup and Set-UnifiedGroup. The text says: "You can use any value that uniquely identifies the Office 365 Group" and gives examples. "DisplayName" is not among the examples, and is not unique, but it is the obvious property to use, and it works. The examples given in Get-UnifiedGroup use DisplayName as the identity. 
The Identity, Id and ExternalDirectoryObjectId properties are not among the examples, but they are unique. 
If I want to find or get a specific group, knowing only the DisplayName, should I use `Get-UnifiedGroup -Identity <"displayname">`, or should I use `Get-UnifiedGroup | Where-Object DisplayName -eq <"displayname">` and is there a difference in the result?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcaec742-3a89-4db8-cd4b-67be1bcfc0b6
* Version Independent ID: a409bc35-132a-98d5-2476-1b80db491cba
* Content: [Get-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @Air-Git, thank you for your feedback and help us to improve docs.microsoft.com.

I have to recommend that you use the values listed in the article, but you can use Display Name and it will produce the same output for Get-UnifiedGroup -Identity <"displayname"> and Get-UnifiedGroup | Where-Object DisplayName -eq <"displayname">.

**Comment by Air-Git** [comment]
The problem is: if I search on a unique Id, I expect to get back one object. If I search on a non-unique Id, I expect to get back an array of objects, even if the array contains only one.
So, if I then want a property of the object e.g $group.ExternalDirectoryObjectId, I will get it from the unique object, but I won't get it from the array of one object.
Identity is supposed to be unique, and so should return an object with a unique identity. But if I Get-UnifiedGroup with "DisplayName" it should return an array of objects with that display name, in which case $group.ExternalDirectoryObjectId would be $null.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @Air-Git Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
