### ISSUE TITLE
Article Incomplete 

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5767]
Contents such as {{Fill in the Description}} and parameters with descriptions only PARAMVALUE: String

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1b368db-141a-a5ac-1823-c0b31dc4cdd1
* Version Independent ID: 54531cfa-2f4b-590e-0b74-4227849d95ae
* Content: [Set-CsOnlineLisCivicAddress (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlineliscivicaddress?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineLisCivicAddress.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineLisCivicAddress.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @junya
* Microsoft Alias: **junya**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@kaishuipinggai Jundong, can you kindly enlighten us with the missing descriptions on the referenced article?

- ValidationStatus
- CompanyTaxId
- CityAlias

Thanks

**Comment by kaishuipinggai** [comment]
Sorry for the late response
ValidationStatus - Specifies the carrier partner validation status. in some countries, we validate against partner if the addresses are valid. This should not be exposed to the TA, I don't know why it's showing. We can just mentioned this is for Microsoft internal use only.
CompanyTaxId  - This is used for Calling plans, it is an optional field where Companies/Tenants can store their TaxId for any regulatory reasons. Company Tax ID is also the Company unique ID assigned by the government services.
CityAlias  - CityAlias is the short form of the city name.

**Comment by yogkumgit** [comment]
@kenwith Please merge the PR #5810 Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by hwkwicre** [comment]
Actually, there's still {{Fill in the Description}} in the article. 😮

**Comment by get-itips** [comment]
> Actually, there's still {{Fill in the Description}} in the article. 😮

Fixed in a new PR. Thanks
