### ISSUE TITLE
Get-MailTrafficReport StartDate cannot be older than 92 days from today

### ISSUE THREAD

**Issue by vsetiawan-bittitan** [MicrosoftDocs/office-docs-powershell#5770]
As the title says, I'm trying to run Get-MailTrafficReport to retrieve data from more than 92 days ago but I'm getting this error:
> Invalid StartDate value. The StartDate can't be older than 92 days from today.

The cmdlet page says that you can view details about message traffic in your organization for the last 180 days. In that case, why am I receiving the error above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a170c55-9dff-bdc0-9719-51f5fa0ce1df
* Version Independent ID: 0c193860-e3df-d25d-846f-c502587c4ad2
* Content: [Get-MailTrafficReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailtrafficreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailTrafficReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MailTrafficReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by vsetiawan-bittitan** [comment]
So is it confirmed that the issue is with the documentation?

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @vsetiawan-bittitan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
