### ISSUE TITLE
Direct routing call ID 

### ISSUE THREAD

**Issue by bzyg7b** [MicrosoftDocs/office-docs-powershell#5773]
Direct routing call ID is apparently possible according to this [UserVoice ](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35022145-allow-service-numbers-from-a-sip-trunk-via-teams-d)post but assigning it with `New-CsCallingLineIdentity -Identity "UKOrgAA" -CallingIdSubstitute "Service" -ServiceNumber "<direct routing number>" -EnableUserOverride $false -Verbose` fails, is there another cmdlet that should be used instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44879cab-fc84-1a8c-7a1d-b747c9d5c093
* Version Independent ID: 03768800-44a7-a670-0e84-a9f40f6b2cca
* Content: [New-CsCallingLineIdentity (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsCallingLineIdentity.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by DEberhardt** [comment]
following, as I am interested in the outcome of this as well :)

**Comment by dariomws** [comment]
Hi @bzyg7b, thank you for the great feedback.

You can also assign it from the Admin Center:
https://docs.microsoft.com/microsoftteams/caller-id-policies
Please, check if you have the option available as they are rolling out this feature and maybe it´s not yet available in your tenant.

More information about New-CsCallingLineIdentity:
https://docs.microsoft.com/microsoftteams/set-the-caller-id-for-a-user

You can use a service number or anonymous, not any number. Check this line from the article:
"ServiceNumber must be a valid Service Number in the Skype for Business Online online telephone number inventory"

**Comment by DEberhardt** [comment]
I have read the article too and scratched my head what "valid" means.
A Direct Routing number is not accepted by the command, so I guess it isn't valid.

Is there a plan to extend the ServiceNumber to also allow Direct Routing Numbers?

**Comment by dariomws** [comment]
You need a cloud phone number, Direct Routing numbers doesn´t work:
https://docs.microsoft.com/microsoftteams/getting-service-phone-numbers

I don´t have information about if it´s in the roadmap, but you can vote this feature and follow it for some update here:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38223676-enable-the-ability-to-use-non-service-numbers-with

**Comment by bzyg7b** [comment]
@dariomws thanks for the reply, in that case can user voice 
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35022145-allow-service-numbers-from-a-sip-trunk-via-teams-d
be re-opened as that is what it is asking for and had 380 votes vs the new one with 33
Would I need to speak to the user voice team in order to raise this?

**Comment by dariomws** [comment]
@bzyg7b the user voice case you are talking is related to Call Queues and Auto Attendant, it's not related to Caller ID configuration.
And I don't have permissions to manage user voice cases, I can only apply updates to docs.microsoft.com.

Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by bzyg7b** [comment]
@dariomws my bad, I didn't spot that it was only related to call queues and auto attendants.
Thanks for your help, much appreciated.
