### ISSUE TITLE
Clarify group type

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#578]
Please state that these are SharePoint groups and not any other type of group. This will help decrease the chance of confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c804225-8b1e-f7e7-3baf-825330eeba9c
* Version Independent ID: 1f2e229b-dbe4-f408-8f6d-a3e18138e3cb
* Content: [Get-PnPGroup (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpgroup?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPGroup.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by nsshommo** [comment]
@DeanGross  - thank you for the feedback. For the PnP cmdlets you can add content by updating the source at github.com/sharepoint. 
@VesaJuvonen  can confirm and close this one out. Thanks!

**Comment by erwinvanhunen** [comment]
Good one @DeanGross : fixed by this PR: https://github.com/SharePoint/PnP-PowerShell/pull/1511

**Comment by VesaJuvonen** [comment]
Needed changes have been applied. We'll get the docs updated with the next release. Closing as a fixed issue.
