### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by fahrulmustari6** [MicrosoftDocs/office-docs-powershell#5784]
Follow

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@fahrulmustari6 Please describe what to update. Thanks.

**Comment by yogkumgit** [comment]
@fahrulmustari6 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
