### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5791]
https://go.microsoft.com/fwlink/?LinkID=187810

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9c22ac3-8dae-8a10-39b0-afd87d765b00
* Version Independent ID: 3e5ead12-b087-95d5-74b8-cabd2d357910
* Content: [New-SPAuthenticationProvider (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spauthenticationprovider?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPAuthenticationProvider.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPAuthenticationProvider.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @hwkwicre thanks for reporting, this was fixed in a recent pr.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @hwkwicre 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
