### ISSUE TITLE
Private Channel with no Membership

### ISSUE THREAD

**Issue by LarsAdesso** [MicrosoftDocs/office-docs-powershell#5792]
In the past we have problems with notification in Teams in combination with planner. So a Microsoft support engineer recommend that we remove the person from the team and renew the membership.

Allocations and authorizations were retained and did not have to be made again.

But: The Person had create a private channel an when they come back, the private channel have no menbership. Also the cmd add-teamchanneluser doenst work, so we have no access to this private channel. (see screenshot)

![AddTeamChannel User](https://user-images.githubusercontent.com/66317294/83530291-cfdf2900-a4eb-11ea-945d-14ec0d70f04f.png)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
@LarsAdesso Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please follow this issue with support.
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
