### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by stephent122** [MicrosoftDocs/office-docs-powershell#5793]
[Enter feedback here]
In the remove-inboxrule cmdlet I would like to see the ability to clean out all rules including hidden rules rather than have to instruct users to use outlook.exe /cleanrules.

Suggestion

remove-inboxrule -mailbox jo@contoso.com -cleanrules 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 619045f2-4093-ef53-8b1f-4674a7fc478b
* Version Independent ID: fcf4649d-4571-76cf-c309-f6c6aba08184
* Content: [Remove-InboxRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-inboxrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-InboxRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-InboxRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hello @stephent122, thanks for your feedback. 

For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/.
There, your suggestion will reach the product team.

**Comment by yogkumgit** [comment]
@stephent122  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
