### ISSUE TITLE
Connect-EXOPSSession - OAuth or Certificate based authentication

### ISSUE THREAD

**Issue by mattmckinstry** [MicrosoftDocs/office-docs-powershell#5794]
As part of our product we need to do automated, non-human driven EXO PowerShell remote calls on behalf of our customers.

Can Connect-EXOPSSession be extended to accept OAuth tokens or a Certificate in order to authenticate?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @mattmckinstry, thank you for your feedback.

Certificate-Based Authentication will be added to the Exchange PowerShell Module version 2. For more information, please check:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @mattmckinstry Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
