### ISSUE TITLE
Does not remove immediately

### ISSUE THREAD

**Issue by Bart-Hoofd** [MicrosoftDocs/office-docs-powershell#5795]
This command does not remove the label, instead places it in Mode "PendingRemoval". In my opinion the documentation should properly reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7118491-42f7-17eb-9707-026b3265ccb7
* Version Independent ID: ad50092c-4dda-e377-42df-55188d7ac5aa
* Content: [Remove-Label (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-label?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-Label.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-Label.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @Bart-Hoofd, thank you for your feedback and help us to improve docs.microsoft.com.

It could remain in the "PendingRemoval" state for several hours after it's finally deleted. Also, you can try to force deletion with -ForceDeletion parameter. I realized that it´s not in the article, I´m adding it.

**Comment by Bart-Hoofd** [comment]
Hi Dario,

Thanks; in my case the labels didn't disappear for at least 72 hours, but removing them using the -ForceDeletion parameter worked perfectly.

Greetz,
Bart
________________________________
Van: Dario Woitasen <notifications@github.com>
Verzonden: vrijdag 5 juni 2020 18:06
Aan: MicrosoftDocs/office-docs-powershell <office-docs-powershell@noreply.github.com>
CC: Bart-Hoofd <bart.hoofd@outlook.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/office-docs-powershell] Does not remove immediately (#5795)


Hi @Bart-Hoofd<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBart-Hoofd&data=02%7C01%7C%7Cd93e9d25ed754fe341f208d8096a57f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637269699624883218&sdata=2Rs2Qvth5g7TYgmPye00igPppGRtXMkPJQwRZ1DNdDk%3D&reserved=0>, thank you for your feedback and help us to improve docs.microsoft.com.

It could remain in the "PendingRemoval" state for several hours after it's finally deleted. Also, you can try to force deletion with -ForceDeletion parameter. I realized that it´s not in the article, I´m adding it.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @Bart-Hoofd 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
