### ISSUE TITLE
Applies to?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5801]
The article says it 
Applies to:
SharePoint Server 2013, SharePoint Server 2016
But since it's SPO I thought it applies to SharePoint Online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ac87fde-0d91-d0cc-6c9e-444917652bec
* Version Independent ID: 10d9bf8c-a1ab-1cfe-c831-127d9d924fd2
* Content: [Remove-SPODataConnectionSetting (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spodataconnectionsetting?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODataConnectionSetting.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODataConnectionSetting.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @hwkwicre 
It's SPO because of "ODATA", it is just a coincidence, there is a clarification note on the article.

> This cmdlet applies to an on-premises environment only. You cannot use this command in the SharePoint Online Management Shell.

**Comment by hwkwicre** [comment]
Thanks for the answer.
Then why does it show
Module:
sharepoint-online
And the article is under SharePoint online?

**Comment by get-itips** [comment]
> Thanks for the answer.
> Then why does it show
> Module:
> sharepoint-online
> And the article is under SharePoint online?

Thanks, that was already reported recently and the team is working on it.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @hwkwicre 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
