### ISSUE TITLE
Missing module installation instructions

### ISSUE THREAD

**Issue by jreed5** [MicrosoftDocs/office-docs-powershell#5802]
Only as FYI. Overview hyperlink is invalid or inaccessible publicly. The URL it points to is:
https://docs.microsoft.com/en-us/powershell/docs-conceptual/overview?view=whiteboard-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 719f5227-2b47-3487-99bb-222d18d43552
* Version Independent ID: e7833ab4-d2b1-5840-4f2c-dda86599d3af
* Content: [Microsoft Whiteboard Admin](https://docs.microsoft.com/en-us/powershell/module/whiteboard/?view=whiteboard-ps)
* Content Source: [whiteboard/whiteboard-ps/whiteboard/whiteboard.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/whiteboard/whiteboard-ps/whiteboard/whiteboard.md)
* Service: **whiteboard-powershell**
* GitHub Login: @tbrosman
* Microsoft Alias: **tbrosman**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @jreed5 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
