### ISSUE TITLE
Regarding -  remove folder with sub-folders and files

### ISSUE THREAD

**Issue by Rupalikothawade** [MicrosoftDocs/office-docs-powershell#5813]
the documentation does not make it clear, if remove folder will delete folder along with subfolders and files within the folder.
Or if there is any specific parameter to be used to do it recursively.
Or its mandatory to clear the content of the folder prior to this script.

Thanks and regards,
Rupali Kothawade

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 774fc341-8404-97e5-5200-d052c6d40875
* Version Independent ID: e49a74d3-05c2-8d62-c80c-e9de45fe7164
* Content: [Remove-PnPFolder (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpfolder?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPFolder.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Rupalikothawade How are you ?
Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/) a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Rupalikothawade Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
