### ISSUE TITLE
Move folders with content

### ISSUE THREAD

**Issue by Rupalikothawade** [MicrosoftDocs/office-docs-powershell#5814]
Documentation is not clearing about if the this command will move all the subfolders and files will be moved or only the content from specific listed will be moved?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e5cdf1f-03a1-32fb-40c0-6c34dc342279
* Version Independent ID: a8bccd70-dec4-2de0-332a-fb2e8a2d7fa0
* Content: [Move-PnPFolder (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/move-pnpfolder?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Move-PnPFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Move-PnPFolder.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/5813#issuecomment-639485649
