### ISSUE TITLE
Get-EXOMailbox

### ISSUE THREAD

**Issue by lciprianionut** [MicrosoftDocs/office-docs-powershell#5815]
Hello,

Regarding the PropertySets parameter, please update documentation for below issues.

1) **All** is missing from valid values in the PropertySets parameter for Get-EXOMailbox.
This is working: Get-EXOMailbox -PropertySets All -Id alias

2) Although is stated that "Wildcards ( * ) are supported." for PropertySets parameter, this is not working, only for named properties is working.

PS C:\WINDOWS\System32> Get-EXOMailbox -Identity alias -PropertySets r*
Get-EXOMailbox : Cannot bind parameter 'PropertySets'. Cannot convert value "r*" to type "Microsoft.Exchange.Management.RestApiClient.GetExoMailbox+PropertySet". Error: "Unable to match the identifier name r* to a valid enumerator name.
Specify one of the following enumerator names and try again:
All, Minimum, AddressList, Archive, Audit, Custom, Delivery, Hold, Moderation, Move, Policy, PublicFolder, Quota, Resource, Retention, SCL, SoftDelete, StatisticsSeed"

3) Audit is present 2 times in PropertySets. Should be: All, Minimum, AddressList, Archive, Audit, Custom, etc.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97567116-dc3d-047c-a10e-0af8460cbaae
* Version Independent ID: 24006ac8-9938-6dfd-738f-b66ef7e1174f
* Content: [Get-EXOMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-exomailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-EXOMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-EXOMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @lciprianionut Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
