### ISSUE TITLE
new oauth functionality not working

### ISSUE THREAD

**Issue by KelvinTegelaar** [MicrosoftDocs/office-docs-powershell#5817]
When following instructions on https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/app-only-auth-powershell-v2.md and connecting using an existing service principal and client-secret we're getting an error that the password is too long:

New-ExoPSSession : AADSTS50052: The password entered exceeds the maximum length of '256'. Please reach out to your admin to reset the password.

The accesstoken is always 1000+ characters. Thus this error will always happen.

Token generation example code:
```
$ExchangeRefreshToken = 'LongRefreshTokenpreviouslyretrieved"
$token = New-PartnerAccessToken -ApplicationId 'a0c73c16-a7e3-4564-9a95-2bdf47383716'-RefreshToken $ExchangeRefreshToken -Scopes 'https://outlook.office365.com/.default'
$tokenValue = ConvertTo-SecureString "$($token.AccessToken)" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential($upn, $tokenValue)

```

Login example code:
`Connect-ExchangeOnline -Credential $credential`

Returned error code:
```
New-ExoPSSession : AADSTS50052: The password entered exceeds the maximum length of '256'. Please reach out to your admin to reset the password.
Trace ID: 3b878102-3588-49a7-b966-394fcd7fa600
Correlation ID: 77a4d5ed-3358-4e4c-90f4-0680d68e40fd
Timestamp: 2020-06-04 11:32:50Z.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\1.0.1\ExchangeOnlineManagement.psm1:445 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession
```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @KelvinTegelaar, thank you for your feedback and help us to improve docs.microsoft.com.

This article is not available yet on docs.microsoft.com. More information here:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
"We're hard at work on Service Principal and Certificate Based Auth support to provide a solution to those wanting non-interactive scenarios (we will blog about this separately)."

I think it will be published soon, you can follow the Exchange Teams blog for updates.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @KelvinTegelaar Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by SearchForTheCode** [comment]
How can this be closed? It is still unfixed to date ( have the newest  PowerShell Modules).
Still getting the same password length error when using the Access token from a client id/secret based oauth authentification.

**Comment by dariomws** [comment]
Hi @SearchForTheCode, thank you for your comment.

An access token is not yet supported for Connect-ExchangeOnline. The following articles do not mention it:
https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2
https://docs.microsoft.com/powershell/module/exchange/connect-exchangeonline

From the last one:
"The Credential parameter specifies the username and password that's used to connect to Exchange Online PowerShell. Typically, you use this parameter in scripts or when you need to provide different credentials that have the required permissions. Don't use this parameter for accounts that use multi-factor authentication (MFA).

Before you run the Connect-ExchangeOnline command, store the username and password in a variable (for example, $UserCredential = Get-Credential). Then, use the variable name ($UserCredential) for this parameter.

After the Connect-ExchangeOnline command is complete, the password key in the variable is emptied.

To specify the password for a certificate file, don't use this parameter; use the CertificatePassword parameter instead."

You can also use -CertificateFilePath, -CertificateThumbPrint, or -Certificate to authenticate using a certificate, as you can see in both articles.

You can find more information on the following issue:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/6171

**Comment by SearchForTheCode** [comment]
Okay thank you for that update. As we implement scripts for our customers, the certificate way ( which we are currently using for testing) is not the suitable way for long term, as this means to much effort for the customer. An easy to create client id / secret is way more easier to handle for the casual customer. Thats why we rely on that. 

The reason we dont use user based authentication is because MFA will be forced soon, so there will be no user accounts left without MFA and theirfore we need an alternative to connect to powershell. Certificate is working but like i said we want to minimize the effort on customer side. Therefore i hope the Connect-ExchangeOnline module will support access token soon ( are theire any estimates on that?)

Also in this script we access data via the REST API to get GRAPH / Service Healt Info. This works of course with the access token and certificate, but we want it to work with the access token via client id / secret.

**Comment by dariomws** [comment]
@SearchForTheCode  I think there is no ETA for this. From the Exchange Team Blog:
"We're hard at work on Service Principal and Certificate Based Auth support to provide a solution to those wanting non-interactive scenarios (we will blog about this separately)."
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
The Exchange Team blog is the best place to pay attention to know when it´s released.

**Comment by SearchForTheCode** [comment]
Yeah thank you, so it means further waiting .
