### ISSUE TITLE
Add-PnpListItem threshold error when using -Folder

### ISSUE THREAD

**Issue by micamend** [MicrosoftDocs/office-docs-powershell#5818]
Try to upload data with Add-PnPListItem -List $myList -Values $val -Folder $myfolder, which works fine for a few month a throws a threshold error  since a few days. Possible that 5000 limit of folders were reached. Is there a get in  command, that force that error?

**Comment by yogkumgit** [comment]
@officedocsbot assign

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @micamend How are you?

Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/) a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @micamend 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
