### ISSUE TITLE
Details needed regarding DateTime values and time zone

### ISSUE THREAD

**Issue by Katydude** [MicrosoftDocs/office-docs-powershell#5820]
[Enter feedback here]
When submitting values for a list item, the example given for DateTime is a simple string, e.g. "5/15/2020 14:22". What timezone would the server use for 14:22? Is it possible to supply the timezone with the value or will the server always interpret the timezone according to server settings, i.e. the timezone assigned to the site collection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362042ec-76bf-6da1-4551-a8baa7a26d27
* Version Independent ID: f30dd9c9-c9fc-f3f9-d5f4-ee4e1b8d3f53
* Content: [Set-PnPListItem (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItem.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Katydude how are you ?

Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/) a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Katydude 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
