### ISSUE TITLE
Pipeline for Get to Set-CsOnlineApplicationInstance not working?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#5821]
Hello,

Piping Get-CsOnlineApplicationInstance to Set-CsOnlineApplicationInstance prompts for $Identity.
This should come through though...
Get-CsOnlineApplicationInstance on its own (with the UPN) works 
Set-CsOnlineApplicationInstance on its own (with the UPN) works
Piping doesn't. 

PS C:\Users\David> Set-CsOnlineApplicationInstance -Identity $UPN8 -DisplayName "My TestAA Account8 - NEW"

RunspaceId        : xxxxxxxx-xxxx-xxxx-a7b7-b3e5ca0d23c4
ObjectId          : xxxxxxxx-xxxx-xxxx-b2da-0c5753b07e75
TenantId          : xxxxxxxx-xxxx-xxxx-b3d8-ebcf7cb64977
UserPrincipalName : TestAAAccount8@arkadinplatform.onmicrosoft.com
ApplicationId     : 11cd3e2e-fccb-42ad-ad00-878b93575e07
DisplayName       : My TestAA Account8 - NEW
PhoneNumber       : 

PS C:\Users\David> Get-CsOnlineApplicationInstance -Identity $UPN8 | Set-CsOnlineApplicationInstance -DisplayName "My TestAA Account8 - NEW"
cmdlet Set-CsOnlineApplicationInstance at command pipeline position 1
Supply values for the following parameters:
Identity: 

-----------
Parameters are defined as follows:
param(
    
    [Alias('ea')]
    ${ErrorAction},

    [Alias('vb')]
    [switch]
    ${Verbose},

    ${DisplayName},

    [Alias('wi')]
    [switch]
    ${WhatIf},

    [Alias('infa')]
    ${InformationAction},

    [Alias('wv')]
    ${WarningVariable},

    [Alias('db')]
    [switch]
    ${Debug},

    [Alias('pv')]
    ${PipelineVariable},

    ${OnpremPhoneNumber},

    [Alias('cf')]
    [switch]
    ${Confirm},

    [Alias('ob')]
    ${OutBuffer},

    [Alias('ev')]
    ${ErrorVariable},

    ${Identity},

    ${Tenant},

    [Alias('wa')]
    ${WarningAction},

    [Alias('ov')]
    ${OutVariable},

    ${ApplicationId},

    [switch]
    ${Force},

    [Alias('iv')]
    ${InformationVariable},

    [switch]
    ${AsJob})

Looks like $Identity is not defined as accepting Input via Pipeline.

My PowerShell knowledge is still growing, so I am not 100% sure on this.

Thanks,
David
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08e7ee82-a4a2-0138-ffcc-a0746a1ee7c0
* Version Independent ID: 5cf5edef-643f-10a1-8247-4e14d06ff675
* Content: [Set-CsOnlineApplicationInstance (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlineapplicationinstance?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @DEberhardt, thank you for your feedback.

I´m not sure if I understand the problem here. It´s true that these cmdlets doesn´t support pipelines. Most PowerShell cmdlets are designed to support pipelines, but not these.

**Comment by DEberhardt** [comment]
If it is intentional not to pipe here, it is fine :)
I just thought to do that...

**Comment by dariomws** [comment]
I think these cmdlets have a special way to handle them, that´s why pipe doesn´t work, I think it´s by design.

Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DEberhardt** [comment]
will do, cheers! :)
