### ISSUE TITLE
Installing PNP from local files

### ISSUE THREAD

**Issue by CTFlorian** [MicrosoftDocs/office-docs-powershell#5825]
My work environment is very locked down.  When running PowerShell as a local admin, I don't have internet access.  Therefore, I need to get PNP setup using the MSI downloaded files. 
I followed the instructions on the PNP Page: 

**Setup files**
You can download setup files from the releases section of the PnP PowerShell repository. These files will up be updated on a monthly basis. Run the install and restart any open instances of PowerShell to use the cmdlets.

- Downloaded the file
- I opened Powershell as admin.  
- Ran the SHarePointPnPPowerShellOnline.msi
- Installed successfully.

When I list the available modules, SharePointPnPPowerShellOnline is not there.
Am I missing something?  Where can I find the detailed instructions for installing PNP from downloaded MSI Files?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @CTFlorian How are you?

Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/) a member of the PnP community will handle your request there.
Thank you!

**Comment by CTFlorian** [comment]
Thanks. I will do so!
    	
    	

    	Thanks.-----------------------Christopher Florian
    
  




On Tue, Jun 9, 2020 at 2:33 PM -0500, "Andres Mariano Gorzelany" <notifications@github.com> wrote:















Hello @CTFlorian How are you?


Thanks for your feedback.

I need to kindly redirect you to open PnP cmdlets issues here a member of the PnP community will handle your request there.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @CTFlorian 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
