### ISSUE TITLE
Show/Hide Channels

### ISSUE THREAD

**Issue by paulwittle** [MicrosoftDocs/office-docs-powershell#5836]
I can see why this cmdlet was deprecated but can you not create a cmdlet that really is about updating the settings for a particular team member? 

I want to be able to set a channel to show for a particular member whilst leaving the default setting of the team to be hide. This doesn't appear to be possible by design but it would be really useful and the user can always hide it again later if they want to override the organisation default. 

I would be interested to know your thoughts on this?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c88db6-7b57-7c5d-264b-ad7b765d2287
* Version Independent ID: c678b927-9100-b4ee-0039-86e37f28d0db
* Content: [Set-TeamMemberSettings (teams)](https://docs.microsoft.com/en-gb/powershell/module/teams/set-teammembersettings?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-TeamMemberSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-TeamMemberSettings.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @paulwittle Paul, how are you?
Here, we are limited to documentation fixes or changes.
I think that your inquiry will be best suited for [Microsoft Teams UserVoice](https://microsoftteams.uservoice.com/).

**Comment by yogkumgit** [comment]
@paulwittle  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
