### ISSUE TITLE
Output missing

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/office-docs-powershell#5837]
It would be very helpful to include sample output as well: what kind of object is returned?

It is difficult to simulate blocked users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e610245-c4d5-2fed-a4c3-c798bdfe48d9
* Version Independent ID: 15c13ed0-ee87-ddba-34e3-fead3acdb532
* Content: [Get-BlockedSenderAddress (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-blockedsenderaddress?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-BlockedSenderAddress.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-BlockedSenderAddress.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @bartvermeersch, thank you for your feedback and help us to improve docs.microsoft.com.

With this cmdlet, you will get a list of users. I´m adding some information about the input and output.

**Comment by bartvermeersch** [comment]
Thanks!
