### ISSUE TITLE
UserList parameter details is incomplete

### ISSUE THREAD

**Issue by PJNield** [MicrosoftDocs/office-docs-powershell#5839]
[Enter feedback here]
The details for the UserList parameter should state that the parameter is the full path to the file that contains the list of users to be migrated, with the list of users in the file formated as a comma separated list of SIP addresses, as shown in the example. 

And example of using the parameter needs to be supplied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c68752-3b36-518f-8cf1-7a4e2aa8cf15
* Version Independent ID: 98b9a798-e232-0b2c-ee0f-857071885c1d
* Content: [Move-CsUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Move-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Move-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @PJNield Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
