### ISSUE TITLE
Example code missing 

### ISSUE THREAD

**Issue by JThornley** [MicrosoftDocs/office-docs-powershell#5840]
https://docs.microsoft.com/en-us/powershell/module/skype/set-csusercallforwardingsettings?view=skype-ps#examples

Example code section is left with placeholder information 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abffe3a5-060b-4e67-ce60-4ace8689053b
* Version Independent ID: 38e763e5-1ed2-a9e5-8eca-32daf8dd3050
* Content: [Set-CsUserCallForwardingSettings (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csusercallforwardingsettings?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsUserCallForwardingSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsUserCallForwardingSettings.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @JThornley Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
