### ISSUE TITLE
Documentation for parameter 'AllowPSTNUsersToBypassLobby' missing

### ISSUE THREAD

**Issue by SaschaSeipp** [MicrosoftDocs/office-docs-powershell#5841]
It seems the new parameter `-AllowPSTNUsersToBypassLobby` is in the Powershell cmdlet, and it's working, but unfortunately it is not yet documented here. It is already documented in the page for `Set-CsTeamsMeetingPolicy`, though.
Just stumbled upon that when creating a new meetings policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f74481ed-c034-046f-2d45-23096b4dce9b
* Version Independent ID: 7a7a44a1-e01e-da96-d1a0-a876487dcb4c
* Content: [New-CsTeamsMeetingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @SaschaSeipp Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
