### ISSUE TITLE
FileSize clarification

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#5842]
Hello,

I was troubleshooting why my 2.3MB MP3 file generates the following error when importing with Get-Content:
`The current deserialized object size of the data received from the remote client computer exceeded the allowed maximum object size. The current deserialized object size is 10572800. The allowed maximum object size is 10485760`

First, tough luck that I went over by a few bytes... you could have let me off with a warning, officer ;)

Here is my "but".
All Documentation state that Audio Formats for Teams Call Queues and Auto Attendants are to be provided in "WMA, MP3 and WAV, max 5 MB".
What it doesn't tell is whether the file must be 5MB in compressed or deserialised state.
Get-Content can deal with 10MB files (apparently), however, I may only feed it files that have 5MB?
This makes it hard to gauge and verify in scripts. Do I need to try to run get-Content and get the length of the resulting object before passing it on?

Could you clarify the metric please?

As a follow-up to that one, could you also mention that this command is good for Call Queues? :)

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349e0a5f-08de-8562-61c8-4a411f6609ca
* Version Independent ID: 81058714-af07-7c3a-be46-bebeec57cbbb
* Content: [New-CsOnlineAudioFile (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlineaudiofile?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineAudioFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineAudioFile.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @DEberhardt, thank you for your feedback and help us to improve docs.microsoft.com.

I think that the cmdlet you´re looking for is:
[Import-CsOnlineAudioFile](https://docs.microsoft.com/powershell/module/skype/import-csonlineaudiofile)
From the article:
"The Content parameter represents the content of the audio file. Supported formats are WAV (uncompressed, linear PCM with 8/16/32-bit depth in mono or stereo), WMA (mono only), and MP3. The audio file content cannot be more 5MB."

**Comment by DEberhardt** [comment]
Yes, I did notice that I was using the wrong cmdlet^^.
Was wondering why the Id was never populated :)

So, is this one different in terms of file sizes?

**Comment by dariomws** [comment]
Same file size restriction apply here:
"The audio file content cannot be more 5MB."
