### ISSUE TITLE
Contradiction on Get-InboxRule Page

### ISSUE THREAD

**Issue by devO365** [MicrosoftDocs/office-docs-powershell#5844]
In parameters section it says:

> -IncludeHidden
> This parameter **works only in on-premises Exchange**.
> 
> The IncludeHidden switch specifies whether to include hidden Inbox rules in the results. You don't need to specify a value with this switch.
> 
> TABLE 6
> Type:	SwitchParameter
> Position:	Named
> Default value:	None
> Accept pipeline input:	False
> Accept wildcard characters:	False
> Applies to:	Exchange Server 2013, Exchange Server 2016, Exchange Server 2019, **Exchange Online**

Correct me if I'm wrong, but Exchange Online can not be on-premises.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84aac716-f03b-5e8f-f83c-090babb1d6c1
* Version Independent ID: 47a23a34-3ee2-1874-3ce7-03e3219e2e16
* Content: [Get-InboxRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-inboxrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-InboxRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-InboxRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@devO365, this is likely the case where the parameter is AVAILBLE in Exchange Server and Exchange Online, but it only WORKS in Exchange Server. Typically, we don't use language like, "This parameter only works in..." unless there's some weird issue like this going on.

Accurate tagging is important for help at the command line, so sometimes we need to make compromises like this.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @devO365 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
