### ISSUE TITLE
This doesn't make sense

### ISSUE THREAD

**Issue by NavishkarSadheo** [MicrosoftDocs/office-docs-powershell#5845]
"Remove-OwaVirtualDirectory **permanently removes an Outlook on the web virtual directory or directories.** When you use this cmdlet, **make sure that you don't accidentally delete the default Outlook on the web virtual directory**."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41643880-7ef3-07fb-0030-42f31e2a4ffb
* Version Independent ID: 35af8383-3dc5-bd8f-b9ee-a608de6f3c01
* Content: [Remove-OwaVirtualDirectory (exchange)](https://docs.microsoft.com/en-za/powershell/module/exchange/remove-owavirtualdirectory?view=exchange-ps#examples)
* Content Source: [exchange/exchange-ps/exchange/Remove-OwaVirtualDirectory.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-OwaVirtualDirectory.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @NavishkarSadheo, thank you for your feedback.

You can use this cmdlet to remove OWA virtual directories created using New-OwaVirtualDirectory. Please, be careful and don´t remove the default virtual directory.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @NavishkarSadheo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
