### ISSUE TITLE
First line

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5855]
Why is there a . in the first line of the article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12d2ab3d-0471-0ab3-4575-ed084b325b67
* Version Independent ID: f0109b72-f41e-220c-0737-740cf97364ed
* Content: [Get-SPOBrowserIdleSignOut (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spobrowseridlesignout?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBrowserIdleSignOut.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBrowserIdleSignOut.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for reporting @hwkwicre

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
