### ISSUE TITLE
BadGateway Error while executing Add-TeamChannelUser

### ISSUE THREAD

**Issue by stylishworker** [MicrosoftDocs/office-docs-powershell#5856]
Hi this cmdlet was working just fine a month ago now it seems to be broken kindly look into it.

Add-TeamChannelUser : Error occurred while executing Add-TeamChannelUser
Code: BadGateway
Message: Failed to execute backend request.
InnerError:
  RequestId: f6b9acbf-ebf9-46f4-8fe3-4a8de8k5e715b
  DateTimeStamp: 2020-06-09T10:07:33
HttpStatusCode: BadGateway
At line:1 char:1
+ Add-TeamChannelUser -GroupId 7f7013f5-7dkce-49be-9f2b-9bc8c8bbf83f -Di ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamChannelUser], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.AddTeamChannelUser

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @stylishworker How are you? Hope you are doing good.
Here we are limited to documentation fixes or changes, besides that, let me tell you that the cmdlet is still in preview as it is only included in the PS INT gallery (beta), the article includes a note about that. 
Hope this is helpful for you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @stylishworker 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
