### ISSUE TITLE
Get-ExoCasMailbox Parameter Sets missing SmtpClientAuthenticationDisabled

### ISSUE THREAD

**Issue by mprentice22153** [MicrosoftDocs/office-docs-powershell#5861]
Please add SmtpClientAuthenticationDisabled to the Minimum parameter set for Get-ExoCasMailbox.  Since the Minimum includes the *Enabled it makes sense to also include the SmtpClientAuthenticationDisabled value.  We can use this option instead if it is not added to the minimum:
get-exocasmailbox -PropertySets minimum -Properties SmtpClientAuthenticationDisabled

Thank you.

Matthew

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @mprentice22153, thank you for your feedback.

Docs feedback is available to help us to improve docs.microsoft.com. If you want to provide feedback for a Exchange Online PowerShell v2 Cmdlet feature request or change, please use the following resources:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
https://office365.uservoice.com/forums/273493-office-365-admin?category_id=96338

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @mprentice22153 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
