### ISSUE TITLE
Difference in quantity of items returned between Get-CasMailbox and Get-ExoCasMailbox

### ISSUE THREAD

**Issue by mprentice22153** [MicrosoftDocs/office-docs-powershell#5862]
It appears Get-ExoCasMailbox returns all mailboxes that existed, rather than the active mailboxes.  In a customer environment, all the users originally were licensed with E3 and the mailboxes were created.  The mailbox service was removed from each license and the mailboxes are no longer active.  We even used the set-user -PermanentlyClearPreviousMailboxInfo.  We properly see 4 mailboxes with Get-CasMailbox but still see the large quantity with Get-ExoCasMailbox.

Output differences:
get-exocasmailbox -resultsize unlimited |measure
Count    : 1728

get-casmailbox -resultsize unlimited |measure
Count    : 4

Thank you,
Matthew

**Comment by dariomws** [comment]
Hi @mprentice22153, thank you for your feedback.

Docs feedback is available to help us to improve docs.microsoft.com. If you want to provide feedback for an Exchange Online PowerShell v2 Cmdlet feature request or change, please use the following resources:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
https://office365.uservoice.com/forums/273493-office-365-admin?category_id=96338

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @mprentice22153 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
