### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5865]
The wording of the description part reads kind of redundant and confusing to me.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d805b7c7-3edf-e3ee-08ee-5cb4d695f1d8
* Version Independent ID: 805ba310-0d2e-1528-66c4-4b78fbf8da7c
* Content: [Get-SPOTenantSyncClientRestriction (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantsyncclientrestriction?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantSyncClientRestriction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantSyncClientRestriction.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for your feedback @hwkwicre

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
