### ISSUE TITLE
setting values for Location type field

### ISSUE THREAD

**Issue by sachindekate** [MicrosoftDocs/office-docs-powershell#5866]
How to set value for Location type field?

Trying to set value as `{ 'DisplayName': 'full address', 'Address':{ 'State':'state value', 'City':'city value', 'PostalCode':'zip value', 'Street':'street value'}}` . It is setting the value however I am getting error _format-default : The collection has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested._
Also in Edit form, it doesn't show the value.

Please suggest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c4c313-d931-b106-36e7-ae44cfb2e238
* Version Independent ID: a1969a78-7325-8946-c27f-8320b7bbed75
* Content: [Add-PnPListItem (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPListItem.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by sachindekate** [comment]
Hi,
I could resolve format-default error, however still struggling to find proper way add/edit values to Location Type field so that it loads correctly in Edit form

**Comment by get-itips** [comment]
Hello @sachindekate Sachin, how are you ?

Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/) a member of the PnP community will handle your request there.
Thank you!

**Comment by sachindekate** [comment]
This [blog post](https://powerusers.microsoft.com/t5/News-Announcements/How-to-update-a-SharePoint-location-field-from-PowerApps-using/ba-p/211377) helped me to form JSON in right format to add/update Location type field.
