### ISSUE TITLE
Invalid value for -AuditDelegate parameter

### ISSUE THREAD

**Issue by matthieumartineau** [MicrosoftDocs/office-docs-powershell#5867]
The document states that UpdateCalendarDelegation is a valid value for -AuditDelegate paramater on Exchange Online.

Based on my tests, this value is not accepted and generate an error. I've talk with the FastTrack team and they confirm to me that it is an error inside this documentation.

Can you take this point and correct the Set-Mailbox documentation page please?

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e79e0e9-786b-dbfa-df44-9436545f00aa
* Version Independent ID: 153ce2d2-dab5-9c8f-c511-ee3bc8ee2dbc
* Content: [Set-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @matthieumartineau Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
