### ISSUE TITLE
An issue with many articles

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5875]
For permissions and the most current information about Windows PowerShell for SharePoint Online, see the online documentation at https://go.microsoft.com/fwlink/p/?LinkId=251832 (https://go.microsoft.com/fwlink/p/?LinkId=251832).
The link is repeated and second one is broken

The exact same issue happens with many articles in SharePoint Online Powershell
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3824c5-6b67-a548-314c-f97a7386e661
* Version Independent ID: 496d21c4-a547-3f32-644e-a3830149c181
* Content: [Get-SPOTenant (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenant.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks @hwkwicre did a mass replace on several articles.

**Comment by hwkwicre** [comment]
Thank you!

https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spoappinfo?view=sharepoint-ps
Just to let you know some other articles such as this one have the same issue but was missed.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by get-itips** [comment]
> Thank you!
> 
> https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spoappinfo?view=sharepoint-ps
> Just to let you know some other articles such as this one have the same issue but was missed.

Yes, you can still find some other articles, we will continue scanning for cases like this, as text changes slightly the search can be inaccurate at times. Please continue raising an issue if you find an article that I didn't detect. Thank you

**Comment by hwkwicre** [comment]
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantlogentry?view=sharepoint-ps
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spowebtemplate?view=sharepoint-ps
https://docs.microsoft.com/ja-jp/powershell/module/sharepoint-online/remove-spouser?view=sharepoint-ps

Here's some more

**Comment by get-itips** [comment]
Thanks @hwkwicre from those, only one needed update, the others are already fixed on a soon to be merged pull request, usually it takes some days for everyone to see the impact of the fixes. I appreciate your report and please open another issue if, after some days, you found others. Thank you
