### ISSUE TITLE
New/Set-SPAccessServices* cmdlets need PG attention

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/office-docs-powershell#588]
The New- and Set-SPAccessServices* cmdlets need information from the PG. They're not documented in the product help. @Techwriter40

**Comment by AndreaBarr** [comment]
@tseward Thank you for this feedback

I will get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by StacyRacks** [comment]
Hi, Has the the sprint team lost their track shoes?  This is still jacked up.  No examples of what the powershell commandlets do and zero synopsis of what they are for?  Is there anyway to restore a access 2010 or 2013 service application from a different farm to a new farm with same content db but different config db?

**Comment by tseward** [comment]
PRs submitted.
