### ISSUE TITLE
Other Labels are not included in Export-PnPTaxonomy

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/office-docs-powershell#5883]
I have many "Oter Lables" for each term and I need to export them and import to the production SPO.
How can I include them?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Ofer-Gal How are you?

Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Ofer-Gal 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
