### ISSUE TITLE
Add-SPOSiteDesignTask - Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by bvdinesh** [MicrosoftDocs/office-docs-powershell#5889]
We have large site with more than 30 list and library. So we have split into 4 site scripts due to limit of 100000 characters. After we have added 4 site scripts into site using below code

Add-SPOSiteDesign -Title "My customer tracking" -WebTemplate "64" -SiteScripts script1.id,script2.id,script3.id,script4.id -Description "Tracks key customer data in a list" -PreviewImageUrl "https://contoso.sharepoint.com/SiteAssets/site-preview.png" -PreviewImageAltText "site preview"

After when we try to apply Add-SPOSiteDesignTask throwing below error 

 
"Operation is not valid due to the current state of the object"  any idea? how to resolve or root cause

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @bvdinesh Dinesh, how are you?
For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @bvdinesh 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
