### ISSUE TITLE
The prefix adds the prefix to the commands, but the prefixed commands aren't functional

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/office-docs-powershell#5891]
Connect-ExchangeOnline -UserPrincipalName xxx  -Prefix Legacy

Once connected, I can do Get-Legacy[tab] and cycle through the various commands.  Looks fine.
But when I run one:

PS C:\> Get-LegacyAcceptedDomain
Get-Command : The term 'Get-LegacyAcceptedDomain' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.

But if I run it without the prefix, the command works fine.

PS C:\> Get-AcceptedDomain

Name                           DomainName                     DomainType                   Default
----                           ----------                     ----------                   -------
xxxx

So, seems like the prefix-command is "known", but isn't tied to the real command for some reason.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d3f5e8b-3af1-22e4-6b11-8a3e159d3987
* Version Independent ID: 60f9a029-69f3-e65c-6816-fbd414790ce3
* Content: [Connect-ExchangeOnline (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
@J-Fedor, Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

You can also provide this feedback here:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623

**Comment by J-Fedor** [comment]
MS fixed it.

“I am running back-end diagnostics for help fix the issue, this diagnostics will fix any object failure, backend glitches, validate configuration, upgrade scripting in the backend.”

Had to wait 12 hours before testing, but whatever voodoo they did appears to have fixed it.



John Fedor
Principal Architect
Direct:
Support Desk
630.592.6240
630.592.6260
visit peters.com today!
​Stay up-to-date and follow us on social media!
Protect your employees and devices as they return to work wherever they are, learn how to HERE.
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and privileged material
​Unauthorized review, use, disclosure, or distribution is prohibited.
​If you receive this material/information in error, please contact the sender and destroy the material/information.

**Comment by dariomws** [comment]
Thanks @J-Fedor, thanks for this comment, it is good to know that this has been fixed.

Thanks again, for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @J-Fedor 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
