### ISSUE TITLE
Example uses wrong parameter name for database

### ISSUE THREAD

**Issue by MSIH** [MicrosoftDocs/office-docs-powershell#5892]
The example on the page is:
`Migrate-SPProjectDatabase -Name ProjectDB1 -SiteCollection "https://contoso1/sites/PWA"`

"Name" is not a valid parameter. The correct parameter is "DatabaseName"

Corrected example: 

`Migrate-SPProjectDatabase -DatabaseName ProjectDB1 -SiteCollection "https://contoso1/sites/PWA"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 783e34cd-4f2f-d0ac-7ede-6c7950e86c24
* Version Independent ID: 1d2ea596-f0b2-314d-b9e4-53b05ae1fe5c
* Content: [Migrate-SPProjectDatabase (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/migrate-spprojectdatabase?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Migrate-SPProjectDatabase.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Migrate-SPProjectDatabase.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and updating the documentation with PR. @MSIH Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
