### ISSUE TITLE
Need faster failure when no archive

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/office-docs-powershell#5894]
Obviously we should check to see if an archive exists or not before trying pull the stats, but it takes a full minute for the new command to fail trying to pull non-existent stats on an archive vs the old command.   Details below.

PS C:\> $t1 = Get-date
PS C:\> Get-MailboxStatistics -identity user@domain.com -archive
The Archive Mailbox is not enabled for user@domain.com.
    + CategoryInfo          : InvalidArgument: (user@domain.com:GeneralMailboxOrMailUserIdParameter) [Get-MailboxStatistics], MdbAdminTaskException
    + FullyQualifiedErrorId : [Server=SN6PR06MB4446,RequestId=3cb45429-97af-471a-b031-58b07ee2b79d,TimeStamp=6/12/2020 8:42:49 PM] [FailureCategory=Cmdlet-MdbAdminTaskException] 72A3102
   0,Microsoft.Exchange.Management.MapiTasks.GetMailboxStatistics
    + PSComputerName        : outlook.office365.com

PS C:\> $t2 = Get-date
PS C:\> ($t2-$t1).TotalSeconds
0.4763062
PS C:\>
PS C:\>
PS C:\> $t1 = Get-date
PS C:\> Get-EXOMailboxStatistics -identity user@domain.com -archive
Get-EXOMailboxStatistics : An error occurred while processing this request..
At line:1 char:1
+ Get-EXOMailboxStatistics -identity user@domain.com -archive
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ProtocolError: (:) [Get-EXOMailboxStatistics], Exception
    + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.Exchange.Management.RestApiClient.GetExoMailboxStatistics

PS C:\> $t2 = Get-date
PS C:\> ($t2-$t1).TotalSeconds
62.6119995
PS C:\>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68aa3776-5347-6299-e566-33f018a2e96c
* Version Independent ID: 9feff981-1e32-11f6-2417-062e09ddaa3a
* Content: [Get-EXOMailboxStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-exomailboxstatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-EXOMailboxStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-EXOMailboxStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
@J-Fedor, Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

You can also provide this feedback here:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
