### ISSUE TITLE
Windows Compatability

### ISSUE THREAD

**Issue by dy-nz** [MicrosoftDocs/office-docs-powershell#5900]
import-module ExchangeOnlineManagement -UseWindowsPowershell
allows only the new EXO cmdlets to work correctly for a Powershell 7 user.
All the legacy V1 cmdlets error with the message "not recognized".

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @dy-nz, thank you for your feedback.

PowerShell Core is not supported yet on the Exchange Online PowerShell v2 module. For more information:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
For news about when PS Core support gets GA please follow the Exchange Team blog.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @dy-nz 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
