### ISSUE TITLE
Where is the "no restriction" option for GiphyContentRating when using Set-Team?

### ISSUE THREAD

**Issue by jacobrastad** [MicrosoftDocs/office-docs-powershell#5902]
In the section for setting the GiphyContentRating it only states the values for "strict" and "moderate". Where is the option for the "no restriction"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd6bccff-1bef-c88c-ff70-2ccdfb48ecc0
* Version Independent ID: 01f33478-352d-c7ae-0c49-784fa1c1fd67
* Content: [Set-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/set-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-Team.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @jacobrastad, thank you for your feedback and help us to improve docs.microsoft.com.

The only two options that are available in Team settings until now are "Strict" and "Moderate". You can set "No restriction" on a messaging policy.
If you want to suggest more options, I need to kindly redirect you to this resource https://microsoftteams.uservoice.com/. There, your suggestion will reach the product team.

More information:
https://docs.microsoft.com/en-us/microsoftteams/messaging-policies-in-teams
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18565060-add-new-giphy-content-rating
https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/39712132-giphy-content-rating-of-no-restriction-has-disap

**Comment by jacobrastad** [comment]
Hi @dariomws 
Thank you for replying.

Perhaps I've misunderstood, but when I check the team-settings in the GUI in the windows desktop client I can set "Strict", "Moderate" and "No restriction". Therefore I assumed that I would be able to set that via Powershell aswell.

Attached is a printscreen of the settings via the windows client (in Swedish). The options shown are

- Strikt - en: strict
- Måttlig - en: moderate
- Tillåt allt innehåll - en: No restriction

![image](https://user-images.githubusercontent.com/6196028/84698134-94167b80-af4f-11ea-804b-42ac7a3de35b.png)

**Comment by dariomws** [comment]
Thanks for this information @jacobrastad. I verified in a demo tenant and I only had Strict and Moderate.

Now I have verified in another tenant and I see the 3 options there, but "Allow all content" instead of "No restrictions":
![image](https://user-images.githubusercontent.com/33589238/84700985-84d10700-af2a-11ea-97d0-1455c76db726.png)

Looks like it´s the same behavior we can see here:
https://techcommunity.microsoft.com/t5/microsoft-teams/ms-teams-giphy-settings-content-rating-quot-no-restriction-quot/m-p/1174030

I will try to get more information.

**Comment by dariomws** [comment]
Hi @jacobrastad, I have more information from the product group. They created an internal task to add this value to the GiphyContentRating parameter. It should be available in the coming weeks.

Thanks again, for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

**Comment by jacobrastad** [comment]
Hi @dariomws 
Thank you for the update and great that you will add the possibility to set it via PS.
