### ISSUE TITLE
Issues installing the module

### ISSUE THREAD

**Issue by sysadmin-scs** [MicrosoftDocs/office-docs-powershell#5904]
Just wanted to share my feedback in case it should be included in the documentation. When I first attempted to run the installation, I ran into this error on one of my servers:

WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'ExchangeOnlineManagement'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
 
But I was able to successfully install on my local machine. I eventually ran across this [webpage ](https://github.com/OneGet/oneget/issues/183) and buried in the comments is the suggestion to run

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Once I did so, I no longer encountered the error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @sysadmin-scs, thank you for your feedback and help us to improve docs.microsoft.com.

This issue was reported before:
https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5725
https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5743
https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5915
https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5978
https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6083

It´s related to PowerShellGet:
https://docs.microsoft.com/powershell/scripting/gallery/installing-psget

Seems that it was fixed in the last version, as we can see in the issues referenced above.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @sysadmin-scs 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
