### ISSUE TITLE
I am unable to launch ms teams/sign out 

### ISSUE THREAD

**Issue by uskiranj** [MicrosoftDocs/office-docs-powershell#5909]
I would like to launch teams via PS. 
Daily I have to manually logout and login, enter credential and sign in.  I want to automate these steps and no way I can do these.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @uskiranj How are you?
For your inquiry I need to kindly suggest [Microsoft Teams User Voice](https://microsoftteams.uservoice.com/) as here we are limited to documentation fixes and improvements.
Thank you

**Comment by yogkumgit** [comment]
@uskiranj  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
