### ISSUE TITLE
Incorrect Example

### ISSUE THREAD

**Issue by nashuatek** [MicrosoftDocs/office-docs-powershell#5912]
This page is about the cmdlet get-messagetracedetail yet the example provided is for the get-messagetrace cmdlet.

This example uses the Get-MessageTrace cmdlet to retrieve message trace information for messages with the Exchange Network Message ID value 2bbad36aa4674c7ba82f4b307fff549f send by john@contoso.com between June 13, 2018 and June 15, 2018, and pipelines the results to the Get-MessageTraceDetail cmdlet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f784c39-5041-578f-7d9f-5b38310cc89c
* Version Independent ID: 4ab7a6db-db36-c736-6ce5-2f0e74b0cf6a
* Content: [Get-MessageTraceDetail (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-messagetracedetail?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MessageTraceDetail.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MessageTraceDetail.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @nashuatek, thank you for your feedback and help us to improve docs.microsoft.com.

In the example, Get-MessageTrace pipes to Get-MessageTraceDetail, so both are using and it´s explained in the example description.
You can use it in this way, or you can use the same parameters directly on Get-MessageTraceDetail.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @nashuatek 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
