### ISSUE TITLE
One paragraph has a few misspelled words

### ISSUE THREAD

**Issue by damianscoles** [MicrosoftDocs/office-docs-powershell#5913]
The description on this page has some misspellings that should be fixed.

Original Text:
'Use the Execute-AzureADLabelSync cmdlet to start the synchronization of sensitivity labels into Azure Active Directory. This allows the applicaton of sensitivty labels to Microsoft Teams sites, Office 365 groups, and SharePoint sites. This cmdlet is required if you were using senstivity labels before September 2019. '

Spelling Corrected:
'Use the Execute-AzureADLabelSync cmdlet to start the synchronization of sensitivity labels into Azure Active Directory. This allows the application of sensitivity labels to Microsoft Teams sites, Office 365 groups, and SharePoint sites. This cmdlet is required if you were using sensitivity labels before September 2019. '

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85481bc5-c751-f601-fd3a-bd708e8031da
* Version Independent ID: a967fe50-c8ce-aea9-1fbc-92e3c461dedb
* Content: [Execute-AzureADLabelSync (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/execute-azureadlabelsync?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Execute-AzureADLabelSync.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Execute-AzureADLabelSync.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@damianscoles, fixed. In the future, you, too can make fixes like this yourself without the need to open a GitHub issue first. For more information, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
