### ISSUE TITLE
Incorrect information in first example

### ISSUE THREAD

**Issue by TrixM** [MicrosoftDocs/office-docs-powershell#5914]
Example 1 for `Enable-RemoteMailbox` states:

> To mail-enable an existing user and create an associated mailbox in the service, run the New-RemoteMailbox cmdlet and specify the identity of the existing user.

This is incorrect. **`New`**`-RemoteMailbox` is only used to create a *new user* in the Active Directory domain and an associated mailbox.

For mail-enabling an *existing* user, `Enable-RemoteMailbox` is the correct command. 

The incorrect line should be omitted in the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e223054e-7964-0e9d-1cc7-4e3a899287b7
* Version Independent ID: ef92e4a8-5138-e825-3ceb-469ad4c2bb98
* Content: [Enable-RemoteMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/enable-remotemailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Enable-RemoteMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Enable-RemoteMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@TrixM, I removed the offending sentence. In the future, you, too, can make changes like this without opening a GitHub Issue first. For more information, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing.
