### ISSUE TITLE
Using Distribution Lists, what is the intervall in which they get expanded?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#5915]
Hello,
when adding Users, they are instantly parsed for their requirements (EV/License).
When adding Groups, they are expanded on a regular intervall. For SFB on-prem this was 8hrs.
What is the intervall for DLs in Teams please?

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4128d55a-2a26-47be-04e7-6a71eece2143
* Version Independent ID: 7d0d9c25-c6f1-4ae3-b4e3-3b6de536ffa3
* Content: [New-CsCallQueue (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @tomkau Tom, is there a way we can get that information from the team? Thanks

**Comment by CLYVR** [comment]
Interval for DL expansion in Teams is same as SfB - 8 hours.  It will typically average less that this but that's the commitment.
Force a refresh by removing and then re-adding the DL to the CQ.

**Comment by get-itips** [comment]
> Interval for DL expansion in Teams is same as SfB - 8 hours. It will typically average less that this but that's the commitment.
> Force a refresh by removing and then re-adding the DL to the CQ.

Thanks for sharing that information @CLYVR
