### ISSUE TITLE
Connect with Service Principal?

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/office-docs-powershell#5921]
Is it possible to connect to Exchange Online using a service principal, similar to connecting to AzureAD with this command?

Connect-AzureAD -TenantId $tenantID -ApplicationId  $Application -CertificateThumbprint $thumb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d3f5e8b-3af1-22e4-6b11-8a3e159d3987
* Version Independent ID: 60f9a029-69f3-e65c-6816-fbd414790ce3
* Content: [Connect-ExchangeOnline (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps#examples)
* Content Source: [exchange/exchange-ps/exchange/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @JLambEJG, thank you for your feedback and help us to improve docs.microsoft.com.

This option is not available yet. More information here:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
"We're hard at work on Service Principal and Certificate Based Auth support to provide a solution to those wanting non-interactive scenarios (we will blog about this separately)."

I think it will be published soon, you can follow the Exchange Teams blog for updates.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @JLambEJG 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
