### ISSUE TITLE
Is it super hard to include return fields, or how to enumerate them?

### ISSUE THREAD

**Issue by pchatelle** [MicrosoftDocs/office-docs-powershell#5922]
The reference material on most powershell is really bad, don't know what is available as output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b7b09af-a0bd-d40f-a5f8-4acff3d49d2f
* Version Independent ID: 84ae7637-076e-891a-37c4-a9630e6d5c47
* Content: [Get-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamuser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @pchatelle How are you? Thanks for your feedback.
I will propose to extend the description of the article to include what is actually outputting.
If it gets approval, you will be able to see it on the online version. Thanks
