### ISSUE TITLE
Requirement of connecting to -admin url should be mentioned

### ISSUE THREAD

**Issue by AbhishekGarg** [MicrosoftDocs/office-docs-powershell#5926]
`Add-PnPSiteCollectionAppCatalog` does not work by usual method of connecting to target site via `Connect-PnPOnline` and executing the "Add" cmdlet.
It needs connection to the tenant `-admin` url, a fact noted in the [PnP-PowerShell issue](https://github.com/pnp/PnP-PowerShell/issues/2149#issuecomment-511433618).

As this is a departure from the usual method, and not something which is obvious, it should be mentioned in the docs page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6077b2-2003-44d4-1dc0-37513a3eaaba
* Version Independent ID: 80ae9151-994d-86f7-f071-ac52ab798adb
* Content: [Add-PnPSiteCollectionAppCatalog (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpsitecollectionappcatalog?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPSiteCollectionAppCatalog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPSiteCollectionAppCatalog.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @AbhishekGarg How are you?

Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), a member of the PnP community will handle your request there.
Thank you!

**Comment by AbhishekGarg** [comment]
Hello @get-itips, I am fine, thank you :)
Hope you are good as well!

Thank you for pointing me in the right direction. I'll raise an issue there.
I am not 100% sure if this issue can be solved only once the PnP docs are updated, or if this will remain as such. Please close if this should be closed.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @AbhishekGarg 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
