### ISSUE TITLE
SCC remove-label -forcedeletion

### ISSUE THREAD

**Issue by roderick-cloudlife** [MicrosoftDocs/office-docs-powershell#5927]
Looks like the parameter -forcedeletion is no longer recognized. Can this be confirmed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7118491-42f7-17eb-9707-026b3265ccb7
* Version Independent ID: ad50092c-4dda-e377-42df-55188d7ac5aa
* Content: [Remove-Label (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-label?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-Label.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-Label.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @roderick-cloudlife, thank you for your feedback and help us to improve docs.microsoft.com.

I confirmed that this parameter was removed and I´m updating the article.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @roderick-cloudlife Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
