### ISSUE TITLE
Only applicable to rather indicates where it's not applicable 

### ISSUE THREAD

**Issue by amortsell** [MicrosoftDocs/office-docs-powershell#5932]
I noticed a minor error in the documentation regarding the -SystemUpdate parameter. The documentation says it's only applicable to: SharePoint Online, while actually it's not applicable to SharePoint Online, but to all On Premises versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59ea3ece-81f8-2ec4-2435-00f96d0f9e6a
* Version Independent ID: ff0d8ea9-878c-7922-81e9-6a9272c8f2c3
* Content: [Set-PnPListItemPermission (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplistitempermission?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItemPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItemPermission.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @amortsell How are you?

Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), a member of the PnP community will handle your request there.
Thank you!

**Comment by amortsell** [comment]
Thanks @get-itips,

If I'm not mistaken this repository contains the documentation about the PnP cmdlets. Hence I think this is the right place for this issue, since it's regarding the documentation about the PnP cmdlet and not about the cmdlet itself, but maybe I was a bit unclear in my description. 

I can submit a PR myself with the corrections I find necessary, with a reference to this issue.

**Comment by get-itips** [comment]
> Thanks @get-itips,
> 
> If I'm not mistaken this repository contains the documentation about the PnP cmdlets. Hence I think this is the right place for this issue, since it's regarding the documentation about the PnP cmdlet and not about the cmdlet itself, but maybe I was a bit unclear in my description.
> 
> I can submit a PR myself with the corrections I find necessary, with a reference to this issue.

@amortsell 
You are right, however, the documentation for PnP cmdlets is directly reflected from PnP source code, from the link I referenced, if you want to submit a pull request to impact the documentation in this repo, you need to submit it against the source code in the dev branch of the repo I referenced, for example 
https://github.com/pnp/PnP-PowerShell/blob/dev/Commands/Lists/SetListItemPermission.cs

This is the only case, this behavior is only for PnP cmdlets.

(If  you submit a PR against the markdown article, it will be later replaced by a process that extracts the documentation from the .cs)

Hope this clarifies it to you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @amortsell Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
