### ISSUE TITLE
publish date not available for this article

### ISSUE THREAD

**Issue by rktiwari14** [MicrosoftDocs/office-docs-powershell#5933]
HI Team, 

Publish date is not mentioned in this article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3242437-7b78-ac6b-d0ef-e5c9116a5b1d
* Version Independent ID: 8ea324f5-a833-f877-3888-a8a703bebd97
* Content: [Get-CsUserPolicyAssignment (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-csuserpolicyassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-CsUserPolicyAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-CsUserPolicyAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @rktiwari14 How are you?
Do you mean _for example_ this?

![image](https://user-images.githubusercontent.com/36666927/85284590-d9faa480-b465-11ea-997c-48f8ae3e8648.png)


That field is not present in cmdlet's articles, you can look up the git history of the article [here](https://github.com/MicrosoftDocs/office-docs-powershell/commits/master/teams/teams-ps/teams/Get-CsUserPolicyAssignment.md).

Hope this information helps  you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @rktiwari14 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
