### ISSUE TITLE
Incomplete article

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5935]
This article is not complete

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ea6ebeb-dcc0-8e76-9e61-224f57db3a5f
* Version Independent ID: 30fad058-46e5-acb0-bb9f-1d87d6f349d5
* Content: [Get-SPOSiteUserInvitations (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositeuserinvitations?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteUserInvitations.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteUserInvitations.md)
* Service: **sharepoint-powershell**
* GitHub Login: @
* Microsoft Alias: ****

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@trent-green Hello Trent, can you kindly help us get missing information about this cmdlet? I appreciate.
