### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5939]
"are not supported.)."
There's an extra . I believe

Also, "You must be a SharePoint Online global Administrator to run this cmdlet." I guess it actually means you must be a SharePoint Online admin, or a global admin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1f56a10-dabe-a37e-9ccf-24fe58077d6a
* Version Independent ID: 86f1c91c-c475-fa6d-1708-b1093682caad
* Content: [Add-SPOGeoAdministrator (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spogeoadministrator?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOGeoAdministrator.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOGeoAdministrator.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for noticing @hwkwicre
