### ISSUE TITLE
Activity Alerts of type ElevationOfPrivilege are being retired.

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/office-docs-powershell#5941]
Please work with Engineering and update this article as it seems that the Activity Alerts of type ElevationOfPrivilege are being retired. 

I tried creating one in the portal and it will not show up after that, then I created one with Powershell (which also doesn't show up in the portal) that I can see it only if I specify it's Identity, otherwise running only the Get-ActivityAlert cmdlet is not returning it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ba01f2-25b3-a215-e5cc-2062c0f3d36d
* Version Independent ID: 0d1876a0-608d-c28c-4e94-7ce2fc9f44cd
* Content: [New-ActivityAlert (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-activityalert?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ActivityAlert.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ActivityAlert.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @Alex-Catalin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
