### ISSUE TITLE
Please document the -ShareData parameter

### ISSUE THREAD

**Issue by msftfdbk** [MicrosoftDocs/office-docs-powershell#5952]
Please document the -ShareData parameter for this cmdlet (as well as Set-CsOnlineVoicemailPolicy).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51ca829d-c578-00f9-5adf-7b490a7696d7
* Version Independent ID: 2d102e7f-cdea-b94a-43cf-b1d806cde3af
* Content: [New-CsOnlineVoicemailPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinevoicemailpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineVoicemailPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineVoicemailPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @msftfdbk Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by msftfdbk** [comment]
@yogkumgit  I’m sorry, but the new page [doesn’t provide any information](https://github.com/get-itips/office-docs-powershell/commit/5bdeff#diff-e47af804c951019d6d476690574d7c5bR155) about this parameter, just a stub with a description to be filled.

**Comment by get-itips** [comment]
> @yogkumgit I’m sorry, but the new page [doesn’t provide any information](https://github.com/get-itips/office-docs-powershell/commit/5bdeff#diff-e47af804c951019d6d476690574d7c5bR155) about this parameter, just a stub with a description to be filled.

We are waiting for internal information to fill the description of the parameter, as that it is taking some time the PR was merged but I'll create a new one once I get the missing description. Thanks.

**Comment by msftfdbk** [comment]
Alright.
