### ISSUE TITLE
Broken formatting in the Description section

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#5964]
Broken formatting in the Description section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 943ec445-d796-f169-7b20-521b1009869b
* Version Independent ID: f817f9ea-1d3c-a900-1fe4-63450f43a40e
* Content: [Get-CsOnlineDirectoryTenant (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedirectorytenant?view=skype-ps&source=docs)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for reporting @shivtorov
