### ISSUE TITLE
Missing content in SYNOPSIS section

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#5965]
Missing content in SYNOPSIS section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d3d5db-bd8f-911e-c1da-53bc0bc2574f
* Version Independent ID: d27f7976-d180-9254-0cbb-a7133bc08c97
* Content: [Get-CsTeamsMessagingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Get-CsTeamsMessagingPolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsTeamsMessagingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTeamsMessagingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit
