### ISSUE TITLE
Get-EXOMailbox Not Showing MailItemAccessed Enabled Mailboxes

### ISSUE THREAD

**Issue by mikeburns7** [MicrosoftDocs/office-docs-powershell#5966]
When attempting to retreive which mailboxes have the new MailItemAccessed logging enabled, using the Get-EXOMailBox command does not retrieve expected results

Running the same command using the legacy Get-Mailbox command produces the expected results

![image](https://user-images.githubusercontent.com/57635375/85301770-3cf43780-b476-11ea-9723-cb89143dd5f3.png)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @mikeburns7, thank you for your feedback and help us to improve docs.microsoft.com.

Get-EXOMailbox only returns a minimal set of properties:
Alias
DisplayName
DistinguishedName
EmailAddresses
ExchangeVersion
ExternalDirectoryObjectId
Guid
Id
Name
OrganizationId
PrimarySmtpAddress
RecipientType
RecipientTypeDetails
UserPrincipalName

Please, try with:
Get-EXOMailbox -Properties AuditOwner -ResultSize Unlimited | Where-Object {$_.AuditOwner -like 'MoveToDeletedItems'}
Or
Get-EXOMailbox -PropertySets Audit -ResultSize Unlimited | Where-Object {$_.AuditOwner -like 'MoveToDeletedItems'}

More information:
https://docs.microsoft.com/powershell/exchange/cmdlet-property-sets

**Comment by mikeburns7** [comment]
Both 
Get-EXOMailbox -Properties AuditOwner -ResultSize Unlimited | Where-Object {$_.AuditOwner -like 'MoveToDeletedItems'} 
and
Get-EXOMailbox -Properties AuditAdmin -ResultSize Unlimited | Where-Object {$_.AuditAdmin -like 'MoveToDeletedItems'}

Return Expected Results

When trying the same command, but using "-like 'MailItemsAccessed'" , results are not returned correctly. 

Please see the screenshot below. This clearly shows that the Get-EXOMailbox is not pulling the correct auditing settings. All results match between the two commands with the exception of "MailItemsAccessed"

![image](https://user-images.githubusercontent.com/57635375/85337470-8791a600-b4ae-11ea-9921-e9bfd39dda83.png)

**Comment by dariomws** [comment]
@mikeburns7 For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.
https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Also, you can report this in the following article:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623

Thank you!

**Comment by mikeburns7** [comment]
Ahh. Thanks for the clarification. I am looking to submit this issue to the team that programs the module. Thanks You!
