### ISSUE TITLE
Where is documentation of the cmdlets? 

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/office-docs-powershell#5967]
This only describes how to connect to the service. Where can I find the documentation of the cmdlets and more (training) material on how to use these?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54add98f-f5f7-74fe-7043-f55fc3699115
* Version Independent ID: c020556e-75d3-8d8b-00f2-5c1008b09c6e
* Content: [Security & Compliance Center PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/scc-powershell.md)
* Service: **o365-security-and-compliance**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@andrePKI, you can click on the **References** link or start typing any part of the cmdlet name in the search box.

![image](https://user-images.githubusercontent.com/33166947/85308359-fb5b9080-b465-11ea-911e-f440d1c6842c.png)

**Comment by andrePKI** [comment]
Well, you need to know the name of any of the cmdlets, right? It's about
getting started,  just connecting is not enough ... Especially because you
can't do Get-Command -Module ... because the name of the module is random.

Op ma 22 jun. 2020 17:54 schreef Chris Davis <notifications@github.com>:

**Comment by dariomws** [comment]
Hi @andrePKI, thanks for your feedback.

You can run Get-Module to get the module name and then use Get-Command if you want to list all the available cmdlets.

**Comment by andrePKI** [comment]
One could also add a reference on this page to point at the docs for the
cmdets. Please? I found that Sec & Compl cmdlets are intermixed with
Exchange Online cmdlets. In other words: needle in a haystack.

Op ma 22 jun. 2020 22:52 schreef Dario Woitasen <notifications@github.com>:

**Comment by chrisda** [comment]
@andrePKI, hundreds of Exchange cmdlet reference topics are shared between environments (versions of Exchange Server, ExO PowerShell, SCC PowerShell and standalone EOP PowerShell), so we made the decision to single-source them .

We've also been working on a way to select and filter the list of cmdlets by PowerShell environment. No ETA, but we are working on it.

**Comment by yogkumgit** [comment]
@dariomws  and @chrisda Thank you very much for the contribution and sharing this explanation. @andrePKI  Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
