### ISSUE TITLE
How can we move more than 3TB of one drive data to SharePoint online by SPMT?

### ISSUE THREAD

**Issue by guptarajesh001** [MicrosoftDocs/office-docs-powershell#5972]
Hi All, I have used SPMT to move more than 3TB of one drive data to SharePoint online by Powershell :
 ```
`Add-SPMTTask -SharePointSourceCredential  $creds -SharePointSourceSiteUrl  $Global:SPOUrl  -TargetSiteUrl $Global:SPOUrl -MigrateAll`
```
Add-SPMTTask -FileShareSource $Global:FileshareSource -TargetSiteUrl $Global:SPOUrl -TargetList $Global:TargetListName
Start-SPMTMigration -Verbose -ErrorAction SilentlyContinue . 
```
```

But I am getting below error:   
         

>     Task 273b3356-bdf6-4a7d-8364-4ab3d0cf9a0c did NOT pass the parameter validation, the error message is 'Source folder https://xyz-my.sharepoint.com/personal/abc_onmicrosoft_com/Documents does not exist.'
> Task 82b63dfb-8da1-4de7-abf5-76c8dafe14e7 did NOT pass the parameter validation, the error message is 'Username or password for source site https://xyz.sharep
> oint.com/sites/AgreeYaProfile is not correct'
> Migration finished, but some tasks failed! You can find the report and log at C:\Users\Administrator\AppData\Roaming\Microsoft\MigrationTool\.onmicrosoft.c
> om\WF_e6607816.

Can we use one drive Url as source site Url instead on onpremises site Url?

**Comment by yogkumgit** [comment]
Get-RetentionCompliancePolicy

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
@guptarajesh001 Rajesh, how are you?

Are you defining a OneDrive for Business location as source? So that would be like a SharePoint Online to SharePoint Online migration. AFAIK you can not perform that with SPMT as is intended from On-Premises.

Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @guptarajesh001 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
