### ISSUE TITLE
EnableAuthAdminReadSession is missing

### ISSUE THREAD

**Issue by rsparnaaij** [MicrosoftDocs/office-docs-powershell#5973]
[KB4559435](https://support.microsoft.com/en-us/help/4559435/) describes that EnableAuthAdminReadSession has been added and links for more info to the [Set-OrganizationConfig](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig) page. However, this parameter isn't discussed on this page.

A bit more clarification regarding this parameter would be nice as well (also on the KB article page), like for instance for what scenarios you’d want this and what the default is.

Thanks!
Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03895b30-2bb7-9e96-28db-def76ae59029
* Version Independent ID: 8056b3ee-4fab-3a5c-935b-a9d0e9ad82a4
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
Get-RetentionCompliancePolicy

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit
