### ISSUE TITLE
Loading EXO and SCC in the same session

### ISSUE THREAD

**Issue by mark3grahams** [MicrosoftDocs/office-docs-powershell#5974]
Is it possible to load Connect-ExchangeOnline and Connect-IPPSSession with in the same Powershell session?

Seems like they use the same PSSession.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @mark3grahams, thank you for your feedback.

I think it´s not possible at the moment. I should suggest that you post this question in the following article:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
We are limited to documentation issues and improvements.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @mark3grahams Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
