### ISSUE TITLE
Add multiple owners

### ISSUE THREAD

**Issue by Damien-GH** [MicrosoftDocs/office-docs-powershell#5982]
Hello,

On the "New-TeamChannel" -Teams- page, i saw a new parameter "-Owner".

So it's fully functionnal, thats fine. But i would like to add multiple owners (2,3....) 

However i can't get how to do that, would you help me please? 

`-Owner (available in private preview)
UPN of owner that can be specified while creating a private channel.`

Thanks you a lot :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd44b411-4b59-b90f-0b82-ad0a87652854
* Version Independent ID: 2c52cc4e-47a1-be0d-8860-1011adf061fd
* Content: [New-TeamChannel (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-teamchannel?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @serdarsoysal
* Microsoft Alias: **serdars**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Damien-GH 
Owner parameter is part of the private preview so it is currently under development and currently only accepts the UPN of one owner.
If you want to propose another behavior I need to kindly suggest to look for/open an entry in [Microsoft Teams UserVoice](https://microsoftteams.uservoice.com/), that way, it can reach the Product Team developing this feature.
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Damien-GH Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
