### ISSUE TITLE
QuarantineTypes missing 'Malware'

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/office-docs-powershell#5983]
Documentation is missing "Malware" as one of the supported QuarantineTypes.

I was surprised that "Malware" wasn't a supported value so I purposefully passed an unsupported value, so I could read the full list:

Specify one of the following enumerator names and try again:
Cannot process argument transformation on parameter 'QuarantineTypes'. Cannot convert value "Malwarekeith" to type
"Microsoft.Exchange.Management.FfoQuarantine.QuarantineMessageTypeEnum[]". Error: "Cannot convert value "Malwarekeith"
to type "Microsoft.Exchange.Management.FfoQuarantine.QuarantineMessageTypeEnum". Error: "Unable to match the
identifier name Malwarekeith to a valid enumerator name. Specify one of the following enumerator names and try again:
**Spam, TransportRule, Bulk, Phish, HighConfPhish, Malware, SPOMalware**""
    + CategoryInfo          : InvalidData: (:) [Get-QuarantineMessage], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-QuarantineMessage
    + PSComputerName        : outlook.office365.com

Thanks,
Keith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5640906-cca9-3396-743c-50bd490425d6
* Version Independent ID: 1407b140-ba39-3a26-1088-6b1c3ee719ce
* Content: [Get-QuarantineMessage (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-quarantinemessage?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/Get-QuarantineMessage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-QuarantineMessage.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and updating the documentation with PR. @mrkeiths Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
