### ISSUE TITLE
What permissions are required to run New-CsVideoInteropServiceProvider?

### ISSUE THREAD

**Issue by swinster** [MicrosoftDocs/office-docs-powershell#5984]
Once you have imported the SFB online module, connected to the remote MS 365 sub/tenant, and imported that remote session, what privalages do you actually need that allow the 
`CsVideoInteropServiceProvider` CmdLets to be imported? 

```
Import-Module SkypeOnlineConnector

$sfbSession = New-CsOnlineSession -OverrideAdminDomain "<tenant_name>.onmicrosoft.com"

Import-PSSession $sfbSession
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5da78125-3d7d-227d-d1ad-fa215b1a86bd
* Version Independent ID: 019ec793-3edb-056a-973d-32e0acb05ff3
* Content: [New-CsVideoInteropServiceProvider (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csvideointeropserviceprovider?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsVideoInteropServiceProvider.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsVideoInteropServiceProvider.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @swinster 
I used a Skype For Business admin and a Global Administrator and the cmdlets for -CsVideoInteropServiceProvider were imported and I could use them.
Hope this clarifies it to you

**Comment by swinster** [comment]
@get-itips so the question is "What permissions are required" 

Are we saying that the "Global Administrator" is the _lowest_ role that can be used to run these CmdLets?

**Comment by get-itips** [comment]
> @get-itips so the question is "What permissions are required"
> 
> Are we saying that the "Global Administrator" is the _lowest_ role that can be used to run these CmdLets?

no, Skype for Business admin as my previous message says.
Thanks!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @swinster Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
