### ISSUE TITLE
How to start Exchange Powershell on a Core installation.

### ISSUE THREAD

**Issue by Zyxian** [MicrosoftDocs/office-docs-powershell#5993]
The document was updated on 6/9/20 but doesn't include Exchange 2019 installed on a Core version of Windows Server 2019.
I got to this page searching for the command to start Exchange Powershell from the command line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 357c64fe-47a0-f804-5f09-f73ad1ac3e58
* Version Independent ID: ebc178ce-bf21-3902-c138-85d854089fc2
* Content: [Open the Exchange Management Shell](https://docs.microsoft.com/en-us/powershell/exchange/open-the-exchange-management-shell?view=exchange-ps&source=docs)
* Content Source: [exchange/docs-conceptual/open-the-exchange-management-shell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/open-the-exchange-management-shell.md)
* Service: **exchange-powershell**
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Zyxian, added.

Thanks for the feedback.

Closing
