### ISSUE TITLE
IsAgendaMailEnabled 

### ISSUE THREAD

**Issue by MIBadran** [MicrosoftDocs/office-docs-powershell#5997]
IsAgendaMailEnabled says its reserved for Microsoft internal use, while its a feature that can be turned on or off

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03895b30-2bb7-9e96-28db-def76ae59029
* Version Independent ID: 8056b3ee-4fab-3a5c-935b-a9d0e9ad82a4
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @MIBadran, thank you for your feedback and help us to improve docs.microsoft.com.

I think this parameter is not really available. You can enable or disable it, but you won´t see any impact on your tenant. Daily agenda emails are only available in Outlook.com.

**Comment by MIBadran** [comment]
Hi Dario

So if this setting in Office.com is not controlled by this parameter, then which one is?

[cid:image004.jpg@01D6537B.AB505620]

[Image]
[cid:image006.jpg@01D6537B.AB505620]

Mahmoud Badran

Consultant
MCS Canada
Office: +1 (289) 305-9099
Mobile: +1 (416) 258-2732
Fax: +1 (905) 568-1527
mbadran@microsoft.com<mailto:mbadran@microsoft.com>

**Comment by dariomws** [comment]
Hi @MIBadran,

I cannot see the pictures. Please, attach them to GitHub not replying to the mail. Thanks!

**Comment by MIBadran** [comment]
![emCapture](https://user-images.githubusercontent.com/29442211/86601493-65e4f400-bf6f-11ea-8be3-dd3a2416e0c4.JPG)

Hi Dario

attached here, i think it may be related to a mailbox parameter tho

**Comment by dariomws** [comment]
Interesting... I cannot see it in my demo tenant and one productive tenant. Both have IsAgendaMailEnabled:$true. In which tenant can you see this?

Also, please check this: https://outlook.uservoice.com/forums/313228--outlook-on-the-web-office-365/suggestions/10448178-emailed-alerts-for-calendar-events-or-daily-agenda.

I think you are a Microsoft employee, if you have a Microsoft alias you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html.

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=MIBadran

**Comment by MIBadran** [comment]
Thanks Dario! 
just linked the accounts together now :) 

so i could see the Agenda option in my Microsoft prod tenant, actually the feature is enabled in my mailbox since 2017 , so i assume it would be released long time ago, are you saying that this feature isn't available to the production tenants in Office 365??

![eCapture](https://user-images.githubusercontent.com/29442211/86604698-b5c5ba00-bf73-11ea-8d7d-082274badf44.JPG)

**Comment by dariomws** [comment]
Yes... I think so. Seems that it´s not available in Microsoft 365, I cannot see it in two different tenants and you can check the outlook.uservoice.com link to see that there are a lot of people requesting this feature.

**Comment by yogkumgit** [comment]
@MIBadran  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
