### ISSUE TITLE
Article is inaccurate for Skype for Business Online customers

### ISSUE THREAD

**Issue by MartinRinas** [MicrosoftDocs/office-docs-powershell#6]
Article is inaccurate for Skype for Business Online customers, SfBO does not allow you to edit all of these settings. TN previously had two versions of this article, one for on-prem and another for SfBO (showing only those values that could be edited in online). We need to bring this differenciation back to allow IT Pros to understand what they can edit in online and what not.

**Comment by kenwith** [comment]
Hi Martin - there is now one article per cmdlet name. There is an Applies To at both the article (top of article) and for each parameter. Which cmdlet are you referencing?

**Comment by kenwith** [comment]
Just to close this out, discussed with Martin and we do have the applies to, see screenshots. Happy to accept a pull request to add more details to description or call out any particular parameters for online. Closing this issue.
![2017-10-05_9-31-33](https://user-images.githubusercontent.com/27743960/31239158-0509f2ec-a9b1-11e7-9d7e-6f3b559a52f1.png)
![2017-10-05_9-33-22](https://user-images.githubusercontent.com/27743960/31239157-04f56c0a-a9b1-11e7-8d0c-6e9eade8c9a7.png)
