### ISSUE TITLE
CertificateThumbprint parameter not present in Connect-ExchangeOnline

### ISSUE THREAD

**Issue by Jim-Kay** [MicrosoftDocs/office-docs-powershell#6005]
I currently have v1.0.1 of ExchangeOnlineManagement, but when I try to use 'Connect-ExchangeOnline' with the '-CertificateThumbprint' parameter, PowerShell complains with the error:

> Connect-ExchangeOnline : A parameter cannot be found that matches parameter name 'CertificateThumbPrint'.

Is this functionality something that has not been released yet?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps&source=docs)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by HeSteIT** [comment]
Hi, same problem here.
v1.0.1 does not have the parameters in Connect-ExchangeOnline that are described in the article.

**Comment by dariomws** [comment]
Hi @Jim-Kay and @HeSteIT, thank you for your feedback.

This feature was released today:
https://techcommunity.microsoft.com/t5/exchange-team-blog/modern-auth-and-unattended-scripts-in-exchange-online-powershell/ba-p/1497387
You need to install version 2.0.3-Preview.

**Comment by HeSteIT** [comment]
Hi @dariomws, thank you for notifying.
Could you put that information into the docs? Because as I see it, there is no hint to the preview version of the module - that's why I tried with the 1.0.1 version last week :-)

**Comment by chrisda** [comment]
@Jim-Kay, @dariomws, this issue is being resolved in #6056 

Thanks for the feedback.

Closing
