### ISSUE TITLE
Article missed a restriction on the new-compliancesearch cmdlet

### ISSUE THREAD

**Issue by cablechewer** [MicrosoftDocs/office-docs-powershell#6008]
The Verb-complianceSearch cmdlets do not function with Advanced eDiscovery cases.  They only function properly with Core eDiscovery cases.  This should be called out in the text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1243572b-d36d-a15c-3d5f-e4bf971cd9ee
* Version Independent ID: 6694e76a-b1e0-9cc6-08ab-beb0cf388e75
* Content: [New-ComplianceSearch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ComplianceSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@cablechewer, done.

Thanks for the feedback.

Closing
