### ISSUE TITLE
Set-TeamPicture doesn't work if you are not owner of the team

### ISSUE THREAD

**Issue by koxo** [MicrosoftDocs/office-docs-powershell#6009]
I have try the new cmdlet Set-TeamPicture, but it doesn't work if you are not the owner of the teams.

Is it normal ? 

I don't see the owner of the team entering PowerShell command line to modify the picture team !

Best regards

Yannick

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @koxo How are you?
I could verify what you said. For feature requests, I need to kindly suggest [Microsoft Teams User Voice](https://microsoftteams.uservoice.com/) that way, your idea can reach the product team to change the current behavior of the cmdlet.
Thanks

**Comment by koxo** [comment]
Hi Andres !

I’m going to ask MS Teams to modify the cmdlet.

Best regards

Yannick

Yannick LANCHEC
Developpement & I.T.
Infrastructure & Directories

infos@koxo.net<mailto:infos@koxo.net?subject=Demande%20d'informations>

GSM : +33 (0)6 43 25 20 80






KoXo Développement
2 rue de Pen Ar C’hleuz
29000 Brest

[Logo-KoXo-Dev-PHPBB]

[msregisteredpartner]




De : Andres Mariano Gorzelany <notifications@github.com>
Envoyé : mardi 30 juin 2020 18:07
À : MicrosoftDocs/office-docs-powershell <office-docs-powershell@noreply.github.com>
Cc : Informations KoXo Dev <infos@koxo.net>; Mention <mention@noreply.github.com>
Objet : Re: [MicrosoftDocs/office-docs-powershell] Set-TeamPicture doesn't work if you are not owner of the team (#6009)


Hello @koxo<https://github.com/koxo> How are you?
I could verify what you said. For feature requests, I need to kindly suggest Microsoft Teams User Voice<https://microsoftteams.uservoice.com/> that way, your idea can reach the product team to change the current behavior of the cmdlet.
Thanks

**Comment by yogkumgit** [comment]
@koxo  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
