### ISSUE TITLE
Issue with the Command

### ISSUE THREAD

**Issue by lovyjain** [MicrosoftDocs/office-docs-powershell#6034]
[Enter feedback here]
Remove-PnPUserFromGroup -LoginName user@company.com -GroupName 'Marketing Site Members'

Instead of GroupName "Identity" is to be useed.
---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808c5ea9-a4cd-bb36-34ec-b126c78923f3
* Version Independent ID: 13478896-b5a7-d8f1-19aa-b653a91bcaf5
* Content: [Remove-PnPUserFromGroup (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpuserfromgroup?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPUserFromGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPUserFromGroup.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @lovyjain 
Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @lovyjain Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
