### ISSUE TITLE
Get-CsOnlineUser Filter issue

### ISSUE THREAD

**Issue by IngeHP** [MicrosoftDocs/office-docs-powershell#6035]
According to the docs:  _"The Filter parameter uses the same filtering syntax that is used by the Where-Object cmdlet"_. However, this doesn't seem to be the case for all situations.

Example 1:
`Get-CsOnlineUser -Filter { TeamsMeetingPolicy -eq "MyPolicy"} `
This returns all users who have been granted the given policy.

Example 2:
`$Policy = "MyPolicy"`
`Get-CsOnlineUser -Filter { TeamsMeetingPolicy -eq $Policy}`
This returns all Teams users.

When using `Get-CsOnlineUser | Where-Object { $_.TeamsMeetingsPolicy -eq ... }`, it returns the correct users with both variants.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41a216e9-0cb7-476d-8e0a-cce28974dd7b
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by shivtorov** [comment]
@IngeHP 
The syntax of "Filter" as such is the same as "Where-Object".
The difference is that Where-Object executes the condition scriptblock locally, but Get-CsOnlineUser is sending it to remote server for execution. Thus the difference with access to local variables.

You can use the following approach to resolve all variables locally before sending the condition to the server.

```
$Policy = "MyPolicy"
$filterString = 'TeamsMeetingPolicy -eq "{0}"' -f $Policy
Get-CsOnlineUser -Filter $filterString
```

**Comment by get-itips** [comment]
@shivtorov Thanks for sharing that example and explanation of the behavior.
@IngeHP I will propose adding an example to the article based on @shivtorov example, I could test it with TeamsMeetingPolicy as your scenario.

**Comment by IngeHP** [comment]
@shivtorov That explains it nicely. Thank you.
@get-itips Feel free to use this as an example.

**Comment by v-9suhap** [comment]
I am trying to filter out enterprisevoiceenabled user for certain locations ...filtering multiple value using AND OR filter is not giving correct results...any thoughts

**Comment by v-9suhap** [comment]
I am using parentheses, it is giving me correct results when I am not combining the OR conditions for all the locations but when I combine then it gives both the results True / False

**Comment by v-9suhap** [comment]
> Sounds like parentheses placed incorrectly. The expression should look like the following:
> 
> `Get-CsOnlineUser -Filter '(EnterpriseVoiceEnabled -eq $true) -and ((Location -eq "US") -or (Location -eq "AU"))'`

this helped

thanks.
