### ISSUE TITLE
Repeated?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6038]
"Displays information about existing site scripts. When no parameter is provided, this cmdlet returns the Id , Title , Description , and Version of each site script. When a site script ID is provided, this cmdlet also returns the Content , which is the JSON of the site script."

**Why is this paragraph repeated in this article?** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22ff33a5-2d76-efa5-5b18-1584e20195d8
* Version Independent ID: 329529cc-8b5a-b71d-0a3a-f686947cab4b
* Content: [Get-SPOSiteScript (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositescript?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScript.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScript.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @hwkwicre 
Those are the Synopsis and the Description, generally, they include very similar information but the Synopsis is usually shorter.
Will propose thru a pr to make it shorter.
Thanks
