### ISSUE TITLE
Missing something?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6039]
why is there a . in the first line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0c31fb5-6109-2669-a774-9f8872dcb85a
* Version Independent ID: 0b44b31b-b4ab-7334-c4a1-3fa61af31633
* Content: [Get-SPOMultiGeoExperience (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spomultigeoexperience?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoExperience.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoExperience.md)
* Service: **sharepoint-powershell**
* GitHub Login: @
* Microsoft Alias: ****

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for noticing.
