### ISSUE TITLE
More details needed

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#6049]
Show better example of hashtable for property matching and include what permissions are required in order to run this cmdlet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d731745-680b-fe7d-78fc-6757460f67b3
* Version Independent ID: 17045452-597a-b77e-897d-8af47dfae727
* Content: [New-PnPUPABulkImportJob (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpupabulkimportjob?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPUPABulkImportJob.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPUPABulkImportJob.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @danmyhre Dan, How are you?
Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @danmyhre Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by danmyhre** [comment]
The docs page shouldn't allow comments then

**Comment by get-itips** [comment]
> The docs page shouldn't allow comments then..this was a request for documentation updates

The Documentation for PnP cmdlets is inside the PnP cmdlets source code, on the repo I referenced, that is the reason I am redirecting you there, once a suggestion is added to the cmdlets source code (also documentation) a process later syncs it in this repo.
Hope this clarifies it to you, thank you!
