### ISSUE TITLE
New-PnPUPABulkImportJob

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#6050]
This cmdlet returns a 403 error unless you connect to the central admin site.  It doesn't work if you connect to the site that you want to house the import file and logs on.

Get-PnPUPABulkImportStatus : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ Get-PnPUPABulkImportStatus
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PnPUPABulkImportStatus], WebException
    + FullyQualifiedErrorId : System.Net.WebException,SharePointPnP.PowerShell.Commands.UserProfiles.GetUPABulkImportS
   tatus

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @danmyhre How are you?
Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @danmyhre Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
