### ISSUE TITLE
RulesQuota default

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/office-docs-powershell#6051]
Rulesquota defaults to 64kb on premises, but cloud provisioned mailboxes seem to default to 256kb now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e79e0e9-786b-dbfa-df44-9436545f00aa
* Version Independent ID: 153ce2d2-dab5-9c8f-c511-ee3bc8ee2dbc
* Content: [Set-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@chrislehr, I've determined that 64 KB is the default value in Exchange 2010 SP3RU30. 2013 CU23, 2016 CU17, 2019 CU6 and Exchange Online have default values of 256 KB. I updated the topic accordingly .

Thanks for the feedback.

Closing
