### ISSUE TITLE
Need to use the AppID GUID not displayname...

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/office-docs-powershell#6058]
When attempting to use Connect-ExchangeOnline and cert based auth to the registered application, the AppID needs to be the GUID of the application not its displayname. When attempting to use the Displayname, as suggested in the Example, the command fails to locate the app in the target tenant. Changing to the AppID of the registered app works first time

Please can you confirm and update accordingly ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-gb/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit
