### ISSUE TITLE
Connect-ExchangeOnline, Connect-AzAccount PS7 SHA256Cng error

### ISSUE THREAD

**Issue by peterruzicska** [MicrosoftDocs/office-docs-powershell#6059]
Applies to both: Connect-ExchangeOnline and Connect-AzAccount (exactly the same error)

In PS7 I cannot connect, only if I import the module with -UseWindowsPowerShell parameter.
LOG:

Version,Organization,ScriptName,ScriptExecutionGuid,CommandName,CommandParams,RecordCount,SentBytesCount,TotalLatencyMs,ErrorLog
v2,,,,Connect-ExchangeOnline,EnableErrorReporting;LogDirectoryPath;LogLevel,0,0,0,FullyQualifiedErrorId=System.ExceptionMicrosoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession;CategoryInfo=NotSpecified: (:) [New-ExoPSSession] Exception;ExceptionType=System.Exception;;ExceptionMessage=System.Exception: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core Version=4.0.0.0 Culture=neutral PublicKeyToken=b77a5c561934e089'.. \r\n ---> System.AggregateException: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core Version=4.0.0.0 Culture=neutral PublicKeyToken=b77a5c561934e089'.)\r\n ---> System.TypeLoadException: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core Version=4.0.0.0 Culture=neutral PublicKeyToken=b77a5c561934e089'.\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.CryptographyHelper.CreateSha256Hash(String input)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.LogReturnedToken(AuthenticationResult result)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.PostRunAsync(AuthenticationResult result)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenCommonAsync(String resource String clientId Uri redirectUri IPlatformParameters parameters UserIdentifier userId String extraQueryParameters String claims)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(String resource String clientId Uri redirectUri IPlatformParameters parameters)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.UserTokenProvider.GetAccessToken()\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.UserTokenProvider.GetAccessToken()\r\n   at Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession.ProcessRecord()\r\n   at System.Management.Automation.CommandProcessor.ProcessRecord()|

**Comment by shivtorov** [comment]
@peterruzicska 
"Exchange Online PowerShell" and "Exchange Online PowerShell V2" modules support only **Windows** PowerShell.

Refer to the following support statement:
https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-and-maintain-the-exchange-online-powershell-v2-module

> Currently, the latest version of PowerShell that's supported for the EXO V2 module is PowerShell 5.1. Support for later versions of PowerShell (and by definition, support for Linux or Mac) is a work in progress and will be announced soon.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@shivtorov Thank you very much for the contribution and sharing this explanation. @peterruzicska Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
