### ISSUE TITLE
Access denied. You do not have permission to perform this action or access this resource.

### ISSUE THREAD

**Issue by Oegl** [MicrosoftDocs/office-docs-powershell#6060]
I execute the following command for a modern teamsite site collection where I'm site collection admin and site owner.

_Get-PnPProvisioningTemplate -out SharingListTemplateFromSTG.xml -Handlers Lists -ListsToExtract "Site Assets"_

The list has no custom columns, inherits permission,... => nothing special, only oob DocumentLibrary, but I receive the following exception:

Get-PnPProvisioningTemplate : {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}
At line:1 char:1
+ Get-PnPProvisioningTemplate -out SharingListTemplateFromSTG.xml -Hand ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.GetProvisioningTemplate

Here are the full commands and exception:
![image](https://user-images.githubusercontent.com/65904352/86241014-7b8aa000-bba2-11ea-9fd5-2cadf5b2901b.png)

Thanks for your support!

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @Oegl How are you?
Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Oegl Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
