### ISSUE TITLE
Grant ServicePrincipal rights to a SharePoint document library?

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/office-docs-powershell#6064]
I am successfully connecting to SharePoint online using the function below, but the service principal doesn't have rights to write to a SharePoint online document library, even though the application/ClientID has the "SharePoint Administrator" role in the tenant. How can I provide read/write permissions to the serviceprincipal, as the site owner/admin?

```
Connect-PnPOnline
       -Url <String>
                        -ClientId <String>
                        -Tenant <String>
                        -Thumbprint <String>
```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @JLambEJG How are you?
Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @JLambEJG Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
