### ISSUE TITLE
Problem in Hybrid environment with "Exchange Online PowerShell V2"

### ISSUE THREAD

**Issue by ogouret** [MicrosoftDocs/office-docs-powershell#6065]
We have a lot of scripts in an hybrid environment, i try to migrate a first script to "Exchange Online PowerShell V2", and i have a strange behaviour, here is an extract in pseudo code we have :

Connect-ExchangeOnPrem
Connect-ExchangeOnline (using a prefix -> "o365")
Get-ExoCasMailbox ......
Disconnect-ExchangeOnline
Get-UMMailbox -> i should get "um mailbox" from on prem environment as i'm always connected to our "On Prem" server, instead i get the popup to connect online !

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hello @ogouret, how are you? For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products

Thank you!

**Comment by ogouret** [comment]
ok ,  i will do that, sorry for my mistake
