### ISSUE TITLE
The examples don't work.

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/office-docs-powershell#6071]
The examples don't work.  Running example 2 against exchange online returns an error, "Parameter set cannot be resolved using the specified named parameters."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c0b982-c393-9d32-0464-816e2d92cc51
* Version Independent ID: 1e4625c2-9d18-6dd2-78c3-a05b26657395
* Content: [New-EmailAddressPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-emailaddresspolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-EmailAddressPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-EmailAddressPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jordanmills, the introduction of the topic says:

> Use the New-EmailAddressPolicy cmdlet to create email address policies. In Exchange Online, email address policies are only available for Microsoft 365 Groups.

And both Example 1 and Example 2 start with:

> This example creates an email address policy in an on-premises Exchange organization that uses...

So it appears these are the only interesting parameters that work in Exchange Online:

- Name
- EnabledEmailAddressTemplates
- EnabledPrimarySMTPAddressTemplate
- IncludeUnifiedGroupRecipients
- ManagedByFilter
- Priority

**Comment by jordanmills** [comment]
Well... i missed that part.  I just checked at the top to see where it applied to exchange online.  Thanks.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @jordanmills Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
