### ISSUE TITLE
Usage in OneDrive for Business sites without being site collection admin

### ISSUE THREAD

**Issue by maps05** [MicrosoftDocs/office-docs-powershell#6072]
The documentation states the following:

_You must be a SharePoint Online administrator or Global Administrator and be a site collection administrator to run the Get-SPOUser cmdlet._

This is true for regular SPO sites but I've verified that for personal sites, i.e. OneDrive for Business, you can invoke this command **without** being a site collection admin.

Additionally, I do verify also that while you can list members of OneDrive 4 Business sites, certain information is misleading. E.g. an SPO admin executing

Get-SPOUser -Site 'PERSONAL_SITE_URL' | Select DislayName,IsSiteAdmin

leads to all users being listed but none is an admin, which is of course incorrect and easily verifiable by interface. The only exception where it works is of course when it's targeting the personal site of the SPO Admin executing it, since he's indeed a site collection admin.

Bottom line, I think it's worth addressing the usage of this command in OneDrive for Business, even if it's just stating that while you can execute without site collection admin, results seem to be not reliable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2412565f-011a-5665-7c3b-e3fe4eae0ee2
* Version Independent ID: 30fda315-30f6-09e0-342c-63940e05208b
* Content: [Get-SPOUser (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spouser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUser.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @maps05 How are you?
First of all, thanks for your feedback.

Tried different user roles based on your feedback to see if we have to impact the documentation and this is what I have observed:

With **both** a Global Administrator user and a SharePoint Online administrator only user

I could invoke `Get-SPOUser -Site 'PERSONAL_SITE_URL' | Select DislayName,IsSiteAdmin`

I experienced the same as you, if the user is not the SC Admin of the SC, results will be shown but different from what is expected (IsSiteAdmin will be false in all users)

So we can conclude that if you run the Get-SPOUser against a SC where you are not the administrator, you will be able to **invoke** the command but the results will not be as expected. Maybe we can find a better verb to use in 

> You must be a SharePoint Online administrator or Global Administrator and be a site collection administrator **to run** the Get-SPOUser cmdlet.
 
However is still true that you need those permissions, right? at least for a reliable result.

Will propose to change the phrase, if it gets approval, it will be on the published version of the article.

Thank you
