### ISSUE TITLE
Command need fix

### ISSUE THREAD

**Issue by TheGhetts** [MicrosoftDocs/office-docs-powershell#6074]
Command on site not work:
winrm set winrm/config/client/auth @{Basic="true"}

Should be:
winrm set winrm/config/client/auth '@{Basic="true"}'

I tested that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@TheGhetts, the command works as written in a **Command Prompt** and running it in a Command Prompt is called out. It never occurred to me to run a regular executable in PowerShell, which is where quotes are required.

This isn't the first issue about this. I'm wondering if I should have both PowerShell and a Command Prompt instructions.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
Topic has been refactored for the EXO V2 module. The prerequisites (including winrm) are now located at <https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#prerequisites-for-the-exo-v2-module>

 If you don't see the value `Basic = true`, you need to run this command **in a Command Prompt** (not in Windows PowerShell) to enable Basic authentication for WinRM:

  ```dos
  winrm set winrm/config/client/auth @{Basic="true"}
  ```

  **Note**: If you'd rather run the command in Windows PowerShell, enclose this part of the command in quotation marks: `'@{Basic="true"}'`.

Closing
