### ISSUE TITLE
Why this cmdlet is not available in the service?

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/office-docs-powershell#6075]
Customer wants to convert an Azure AD user to an Exchange MailUser without re-creation (dependencies to Sharepoint).
Any explaination why this cmdlet is blocked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 570ded68-5ff6-4160-ee40-7a5aff1a7e7e
* Version Independent ID: 50bcc128-c408-c907-d121-d3fb7909cff4
* Content: [Enable-MailUser (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/enable-mailuser?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Enable-MailUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Enable-MailUser.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @trudolf-msft, thank you for your feedback and help us to improve docs.microsoft.com.

I don't have this information but for example, Enable-Mailbox is not available because you have to enable the Exchange Online license in Microsoft 365 to enable a mailbox.

For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/.
There, your suggestion will reach the product team.

Similar request:
https://office365.uservoice.com/forums/264636-general/suggestions/19392346-exchange-hybrid-allow-enable-mailbox-disable-m

**Comment by trudolf-msft** [comment]
Hi Dario,

Thanks for your answer.
The cmdlet I meant is Enable-MailUser not Enable-Mailbox. So just convert an Azure AD user to an Exchange mail-enabled object.
And it works in Torus client but not for public admins. Can you raise this question to PG please?

[MultiTenant\DB6PR03MB3064] PS C:\Users > get-user mailuser2 | Enable-MailUser -DisplayName mailuser2 -Alias mailuser2 -PrimarySmtpAddress mailuser2@rud.onmicrosoft.com<mailto:mailuser2@rud.onmicrosoft.com>


Customer wants to convert an Azure AD user to an Exchange MailUser without re-creation (dependencies to Sharepoint).
Any explaination why this cmdlet Enable-MailUser is blocked?

Kind regards,
Thomas

Thomas Rudolf | Senior Premier Field Engineer | Messaging & Office 365
WW Lead - Offline Assessment Exchange Server Security
EMEA Modern Workplace People Ambassador
[cid:image001.png@01D65AE7.5173D820]

**Comment by dariomws** [comment]
@trudolf-msft Yes, I understood that you meant Enable-MailUser, just wanted to provide you some information. In the following link:
https://office365.uservoice.com/forums/264636-general/suggestions/19392346-exchange-hybrid-allow-enable-mailbox-disable-m
He is requesting the same for Enable-Mailbox, but you can see a comment requesting the same for Enable-MailUser.

I tried to get more information from the PG but I had no luck, my apologies.

**Comment by trudolf-msft** [comment]
DCR was filled but still no response:
https://o365exchange.visualstudio.com/DefaultCollection/O365%20Core/_workitems/edit/1615241

**Comment by chrisda** [comment]
Closing this issue as there's nothing to do in documentation.
