### ISSUE TITLE
The password entered exceeds the maximum length of '256'. Please reach out to your admin to reset the password

### ISSUE THREAD

**Issue by vagdevi17259** [MicrosoftDocs/office-docs-powershell#6077]
_**Tried the method mentioned in the Connect using an existing service principal and client-secret @ https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps**_ 

**But unable to connect to Exchange Online Powershell Error:**
New-ExoPSSession : AADSTS50052: The password entered exceeds the maximum length of '256'. Please reach out to your admin to reset the password.
Trace ID: 7ecaa03f-6999-4508-a2e6-91be7ad60000
Correlation ID: cd6ef50b-dd67-4d58-b3cb-4d422b252f17
Timestamp: 2020-07-03 19:15:29Z.
At C:\Users\vagdevi.pedalenka\Documents\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.3\ExchangeOnlineManagement.psm1:481 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession

**Script is using for making connection:**

$AuthenticationResult = Invoke-RestMethod -Uri https://login.microsoftonline.com/TenantID/oauth2/token?api-version=1.0 -Method Post -Body @{"grant_type" = "client_credentials"; "resource" = “https://outlook.office.com/”; "client_id" = "Client/Application ID in Azure"; "client_secret" ="Client_Secret"}

$securePass= ConvertTo-SecureString $AuthenticationResult.access_token -AsPlainText -Force
	$userCredentials = New-Object System.Management.Automation.PSCredential('XXX@tenant.com', $securePass)
	
Connect-ExchangeOnline -Credential $userCredentials

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hello @vagdevi17259, how are you? For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products.

Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @vagdevi17259 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it.
