### ISSUE TITLE
Get Move History from Get-EXOMailboxStatistics

### ISSUE THREAD

**Issue by nphtrung** [MicrosoftDocs/office-docs-powershell#6078]
Hi All,

This is probably a dumb question. Anyone knows how to get Move History using Exchange Online PowerShell V2 module?

Thanks in advance

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @nphtrung, thank you for your feedback.

Are you asking about the -IncludeMoveHistory parameter? I think it´s not available in Get-EXOMailboxStatistics. To request it and more information, please provide your feedback/comment here:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
https://office365.uservoice.com/forums/273493-office-365-admin?category_id=96338

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @nphtrung Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
