### ISSUE TITLE
How to remove a language?

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/office-docs-powershell#6080]
How is it possible to remove a language with LocaleSettings afterwards? I'm able to add and change languages, but not to remove a language. Also if completely rebuild the arraylist to just have the default language all other languages are still there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0b60455-890d-a34f-4801-8a48463094f4
* Version Independent ID: 1b20db7d-a508-8523-2309-a3d9f5d08dd7
* Content: [Set-Label (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Label.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Label.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @TobiasAT, thank you for your feedback and help us to improve docs.microsoft.com.

I have been tested it and I can add values, but not remove or change them. Let me try to get more information.

**Comment by TobiasAT** [comment]
Thanks @dariomws. To change an existing language just add the same language again with other values. The system will not add the same language a second time. The system replaces the existing values. 

Also a remark for the doc and the examples. I think you should add a remark for LocaleSettings the DisplayName AND Tooltip are required together. In your examples it seems you can set first the DisplayName and with a second command the Tooltip. In my case the system respond with an error if I try to set just one of them. Same if you add a new label via admin GUI, displayname and tooltip are required fields.

**Comment by dariomws** [comment]
@TobiasAT I tried that and couldn't edit the existing values.

I'm updating the example, I also saw that DisplayName and Tooltip should be used together. Check the pictures in the pull request.

I'm trying to get more information.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and updating the documentation with PR. @TobiasAT 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by TobiasAT** [comment]
@yogkumgit Wait! Why is the issue closed? What is with the initial question "How to remove a language?" Did I miss something?

**Comment by dariomws** [comment]
Hi @TobiasAT,

To remove the current values you need to provide empty values:
![image](https://user-images.githubusercontent.com/33589238/87328807-6e5ba280-c50c-11ea-9bd1-ae8ae93ac9f0.png)

I'll add an example to the article.

**Comment by TobiasAT** [comment]
Thanks @dariomws for the tip, that worked 👍 Just empty values, good to know.
