### ISSUE TITLE
The -MajorVersions argument contains an out-of-scope value of 20.

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/office-docs-powershell#6082]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/13634805/86560458-3f3bb300-bf99-11ea-961d-d7a5a751a92a.png)

The sample is in scope in SharePoint Server, but out of range in SharePoint Online. To avoid confusion, I think we should add a note that this sample is for SharePoint Server and SPO users must use greater than 100.

- ref
`Major versions   SharePoint Library Settings allows a range of 100-50000 major versions; SharePoint Server Library Settings allows a range of 1-50000 major versions.
`
https://support.microsoft.com/en-us/office/how-does-versioning-work-in-a-sharepoint-list-or-library-0f6cd105-974f-44a4-aadb-43ac5bdfd247?ui=en-us&rs=en-us&ad=us

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbab5a2d-0c37-bb2c-f2d9-989bc2a59d05
* Version Independent ID: 2f512ab6-be40-1fb2-9f8a-d1bc692537ce
* Content: [Set-PnPList (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplist?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPList.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @kefujino 
How are you?
Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @kefujino Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
