### ISSUE TITLE
Please return $PSSession from connect-exchangeonline

### ISSUE THREAD

**Issue by fpetereins** [MicrosoftDocs/office-docs-powershell#6083]
Enhancement: Please return $PSSession from connect-exchangeonline to further allow reuse of the session.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @fpetereins, thank you for your feedback.

For feature requests related to Exchange Online PowerShell v2, I need to kindly redirect you to this resource https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
Or
https://office365.uservoice.com/forums/273493-office-365-admin?category_id=96338

There, your suggestion will reach the product team.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @fpetereins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
