### ISSUE TITLE
Czech is listed as Turkish

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#6084]
Hello,

don't know where to field this, but the DisplayName for cs-CZ (Czech) is "Turkish (Turkey" (which is the previous entry).

Here the output:

```
Id                     : tr-TR
DisplayName            : Turkish (Turkey)
Voices                 : Seda
VoiceResponseSupported : False

Id                     : cs-CZ
DisplayName            : Turkish (Turkey)
Voices                 : Jakub
VoiceResponseSupported : False

```

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22fb169a-d0d6-8739-1a38-844fe3f3ec03
* Version Independent ID: c64dea3b-2813-67ec-fe19-608d5adc1eca
* Content: [Get-CsAutoAttendantSupportedLanguage (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantsupportedlanguage?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsAutoAttendantSupportedLanguage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsAutoAttendantSupportedLanguage.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DEberhardt David, we will try to pass this information to the team. Thanks

**Comment by get-itips** [comment]
@tomkau

**Comment by yogkumgit** [comment]
@tomkau Please help us here.

**Comment by pupara** [comment]
Thanks @yogkumgit and @DEberhardt. I am reaching out to team get this fixed.

**Comment by DEberhardt** [comment]
I know this is a minor (Displayname only) bug in a very specific niche of Office365 and the devs have probably other priorities, but I thought I follow up on all my open issues before the month is over and had a look at the output again:
```
Get-CsAutoAttendantSupportedLanguage | Where {$_.Id -EQ "Cs-CZ" -or $_.Id -EQ "tr-TR"} | FT ID,DisplayName,DisplayVoices

Id    DisplayName      DisplayVoices
--    -----------      -------------
tr-TR Turkish (Turkey) Seda
cs-CZ Turkish (Turkey) Jakub
```

No pressure, just wanted to see if it is still open 😺

**Comment by get-itips** [comment]
> Thanks @yogkumgit and @DEberhardt. I am reaching out to team get this fixed.

@pupara Can you confirm the team is aware of this?
As this is not a documentation issue, I just need to confirm that and we will proceed closing this. Thank you

**Comment by yogkumgit** [comment]
@pupara Please update. cc @Kateyanne

**Comment by get-itips** [comment]
> Thanks @yogkumgit and @DEberhardt. I am reaching out to team get this fixed.

Hello @pupara how are you? It seems _cs-CZ_ is still listed as _Turkish (Turkey)_ if you could inform the team @yogkumgit will proceed closing this issue as this is not doc related. Thank you! cc @tiburd

**Comment by yogkumgit** [comment]
@pupara Kindly help here. Thanks

**Comment by get-itips** [comment]
Hello @DEberhardt David, we could manage to inform about this.
@yogkumgit please close as this is not a documentation issue we can take care of.
