### ISSUE TITLE
CNG Certificates Do Not Work

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/office-docs-powershell#6092]
This page should have a massive note that CNG certificates cannot be used with the appid only method. I wasted several hours.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @JustinGrote, thank you for your feedback and help us to improve docs.microsoft.com.

You must create the self-signed certificate using one of the following methods:
https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#step-3-generate-a-self-signed-certificate
I think you cannot create a CNG certificate using these methods.

**Comment by JustinGrote** [comment]
@dariomws while true, it's not obvious that using a CNG cert (which is the default since Windows 2008) will not work, so adding a small banner right at that section saying that CNG certificates are not supported with the MSExchangeOnline module wouldn't hurt but make this aspect clear.

**Comment by dariomws** [comment]
Thank you @JustinGrote again for your feedback. We will take it into consideration, if we get more feedback about the CNG certificates we'll add a note to the article.
