### ISSUE TITLE
Missing the permissions required to run command

### ISSUE THREAD

**Issue by NeedsCoffee** [MicrosoftDocs/office-docs-powershell#6096]
Please could I ask that the permissions needed to run this command are added to the document. Would an account require full Global Admin? Or would Teams Service Admin be sufficient, or maybe less? And would it perhaps also require permissions in Skype for Business Online since this is a Cs cmdlet?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d149ca60-bfb7-5077-2643-1a08ad926cca
* Version Independent ID: 24754aee-bff2-fa16-e7e6-af45362fd916
* Content: [New-CsBatchPolicyAssignmentOperation (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csbatchpolicyassignmentoperation?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @NeedsCoffee how are you?
Tested this, and adding the minimum required roles to run this cmdlet thru a pull request.
Thank you
