### ISSUE TITLE
Scope for DialOutPolicy

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#6097]
Hello,

could I get clarification on the desired scope for the DialOutPolicies please?

For Skype we could apply matching patterns on voice routes that would work for us for Call Restrictions.
For Teams we are doing the same thing (for TDR, as we have the same mechanics available).

Are the CsDialOutPolicy intended to provide this functionality for Microsoft Calling Plans or can/should they be used for TDR as well?

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fab4e86c-f8f6-36fa-874c-756e5a88f0ae
* Version Independent ID: 307f2569-889a-b887-9536-d91d26fe184e
* Content: [Get-CsOnlineDialOutPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialoutpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialOutPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDialOutPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment]
@pupara Please help us in resolving this issue. Thanks.

**Comment by get-itips** [comment]
@pupara @tomkau can you please help us confirm if this cmdlet is only intended for Calling Plans? AFAIK it is not used on DR scenarios. Thank you

**Comment by yogkumgit** [comment]
@pupara Please update. cc @Kateyanne

**Comment by get-itips** [comment]
@DEberhardt David, have you seen this article? https://docs.microsoft.com/en-us/microsoftteams/outbound-calling-restriction-policies

**Comment by DEberhardt** [comment]
Hello,

I think I have had read the article. Re-reading it, I note that:
- It does not tell anything about support with/for Direct Routing
- It does mention rules not being able to be customized
- It does not list the restriction level with enough clarity to be useful (Does domestic include Emergency services calls if they are routed via the Voice Routing Policy...?)

All of the above drive previously established behaviors (i.E. adding matching patterns on Voice Routes) to facilitate Outbound voice routing. 

PS: The same is true for the Calling Line Identity - Using a CLI Policy results in multiple diversion headers which generates call drops upstream (only one header allowed, Teams currently sends two). Granted, this will need more investigation with the Carrier, but is currently blocking use of the policy

**Comment by get-itips** [comment]
Hello @DEberhardt David, I could get more information that this cmdlet also affects DR.

**Comment by get-itips** [comment]
@yogkumgit I think you can close this thread now.
