### ISSUE TITLE
New-InboxRule example

### ISSUE THREAD

**Issue by TimAbmgf** [MicrosoftDocs/office-docs-powershell#6100]
The example doesn't show where to put the actual mailbox to apply the new rule. So, does this mean you'd run a get-mailbox and pipe that mailbox to the new-inboxrule?

I just tried New-InboxRule by itself. I was prompted for **Name:**

So I just tried this:
New-InboxRule -name junk@**_domain.com_** -MarkAsRead $true

That worked for me. I suggest that the online article show the -Name in the example.

**Comment by TimAbmgf** [comment]
I take that back. When I tried to remove the rule I was running into problems

PS C:\Users\User> Remove-InboxRule -name junk@_domain.com_
A parameter cannot be found that matches parameter name 'name'.
    + CategoryInfo          : InvalidArgument: (:) [Remove-InboxRule], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Remove-InboxRule
    + PSComputerName        : outlook.office365.com

PS C:\Users\User> Remove-InboxRule -name junk@_Domain.Com_ junk@_Domain.Com_
A parameter cannot be found that matches parameter name 'name'.
    + CategoryInfo          : InvalidArgument: (:) [Remove-InboxRule], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Remove-InboxRule
    + PSComputerName        : outlook.office365.com


I started searching the Junk mailbox for the rule. It wasn't there
I searched ETRs. The rule wasn't there.
I searched my mailbox and found the rule was created for my mailbox (the account I was signed in with PowerShell)

I'm still looking for the right syntax to create a rule for a different mailbox.

**Comment by TimAbmgf** [comment]
I found it.
it's the -mailbox

New-InboxRule **_-mailbox_** junkmail@_domain.com_ -name 'markasread' -MarkAsRead $true

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @TimAbmgf, thank you for your feedback and help us to improve docs.microsoft.com.

I think you answered your own question. If you think there is something to update or improve in the article, please let us know.

Thanks again, for taking out some time to open the issue.

**Comment by TimAbmgf** [comment]
> Hi @TimAbmgf, thank you for your feedback and help us to improve docs.microsoft.com.
> 
> I think you answered your own question. If you think there is something to update or improve in the article, please let us know.
> 
> Thanks again, for taking out some time to open the issue.

Yes, I got the answer. I also see that yogkumgit assigned the item; so it's my impression the online doc will get updated :)

Thanks all.
