### ISSUE TITLE
DomainPairsCountInCategory definition

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/office-docs-powershell#6102]
The cmdlet's -Detailed switch mentions DomainPairsCountInCategory but does not provide any explanation about what this information means.

Could someone please review this concern and step up efforts to avoid making similar references in documentation?  I'm sure you will happily fix this issue and I realize it was an accident but it's time consuming to investigate then open a request to update; an explanation should have been included all along.

Thanks for your time,
Keith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e284a198-a0bc-3e39-6077-c2de30d54c4f
* Version Independent ID: 01eb0b27-7822-7e4d-ba89-a5b51c0996f4
* Content: [Get-PhishFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-phishfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-PhishFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-PhishFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by mrkeiths** [comment]
Hello,

I saw this request was just closed so I took a look at the cmdlet's documentation.

I don't see any additional info that describes what DomainPairsCountInCategory means.  I did I check too soon?

**Comment by chrisda** [comment]
@mrkeiths, yes; too soon. I merged the #6124 pull request that fixes the issue as you described, but I did not come here and close the issue. This must be a new thing where the Issue and the PR are somehow intelligent?

There were some other PRs that came in that I was trying to approve before I merged Master to Live (published). In this repo, everything takes way too long.
