### ISSUE TITLE
Non-boolean switch parameters are more difficult to work with; please stop coding these

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/office-docs-powershell#6103]
Non-boolean switch parameters like HiddenFromExchangeClientsEnabled and UnifiedGroupWelcomeMessageEnabled are more difficult to work with than boolean value parameters when dealing with migrations or working from CSV's or working programmatically. Its the simple concept of how data works. Instead of working from one unified data set, these types of parameters require separate data sets be broken out. Extremely inefficient. They create the requirement for additional work and steps in scripting and manual work for administrators who aim to automate processes. Please stop coding parameters this way and stick to boolean-based parameters that can be updated in bulk from a unified data set.

Thanks! Respectfully,

-Partners Everywhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d0c6338-f919-df9e-d3a9-1f8479e9aece
* Version Independent ID: 8962c0dc-72a3-208a-33de-6a89cd56b6fc
* Content: [Set-UnifiedGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @ckssaas, thank you for your feedback and help us to improve docs.microsoft.com.

For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/forums/273493-office-365-admin.
There, your suggestion will reach the product team.

**Comment by yogkumgit** [comment]
@ckssaas  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
