### ISSUE TITLE
Template parameter still not working

### ISSUE THREAD

**Issue by kpinel** [MicrosoftDocs/office-docs-powershell#6106]
We have an EDU license but am still unable to use the -Template parameter.
The result when attempting to create a new team is:
New-Team : A parameter cannot be found that matches parameter name 'Template'.
At line:1 char:30
+ New-Team -DisplayName LaDeDa -Template EDU_Class -Description "Test T ...

This still works in version 0.9.6
We are ramping up our class Team creation and am expecting to create a few hundred in the next few weeks. I was hoping to be able to do away with the old module for this as the new ones are much more efficient.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @kpinel 
-Template parameter is part of the Preview Module as the article for [New-Team](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps) says:

> IMPORTANT: Using this cmdlet to create a new team using a template is still in preview. You can install and use the preview module from the PowerShell test gallery. For instructions on installing and using the Teams PowerShell preview module, see Install the pre-release version of the Teams PowerShell module (https://docs.microsoft.com/microsoftteams/install-prerelease-teams-powershell-module).

You can find more information here https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-overview

**Comment by kpinel** [comment]
Thank you for that and apologies. Clearly I missed that somewhat important
line.

Kind regards,
Kevin
-------------------------------
If you're going to be passionate about something, be passionate about
learning

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @kpinel Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
