### ISSUE TITLE
Add Section on Configuring for Azure Automation

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/office-docs-powershell#6107]
I wrote an article for how to do this in Azure Automation, the info should be adapted here
https://git.io/AAExchangeAppOnly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @JustinGrote, thank you for your feedback and help us to improve docs.microsoft.com.

I'll check if we can add the information from the link to this article.

**Comment by dariomws** [comment]
Hi @JustinGrote, sorry for the delay.

I didn't get the approval to add this information to the article. Anyway, your article is public so anyone can access and take advantage of it.

Thanks again, for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @JustinGrote We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
