### ISSUE TITLE
Description of Get-MailboxAuditBypassAssociation is misleading

### ISSUE THREAD

**Issue by akhtarmughal-9** [MicrosoftDocs/office-docs-powershell#6108]
Get-MailboxAuditBypassAssociation actually returns all objects ( those with Audit bypass Enabled and Disabled )

you will need to run something like this to get a list of bypass

Get-MailboxAuditBypassAssociation  -ResultSize unlimited | ? {$_.auditbypassenabled -eq $true}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a3f050-9e32-afed-3ae0-23fd5c3c8396
* Version Independent ID: b0688e71-ccb0-835d-1730-681dece1f699
* Content: [Get-MailboxAuditBypassAssociation (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailboxauditbypassassociation?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Get-MailboxAuditBypassAssociation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MailboxAuditBypassAssociation.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@akhtarmughal-9, confirmed. I updated the topic.

Thanks for the feedback.

Closing
