### ISSUE TITLE
Get-RecoverableItems - Incorrect syntax in Example 1

### ISSUE THREAD

**Issue by JSHooper** [MicrosoftDocs/office-docs-powershell#6109]
Example 1 of the Get-RecoverableItems has the incorrect syntax of:

`Get-RecoverableItems -Identity laura@contoso.com -Subject -SubjectContains "FY17 Accounting" -FilterItemType IPM.Note -FilterStartTime "2/1/2018 12:00:00 AM" -FilterEndTime "2/5/2018 11:59:59 PM"`

I believe it should read:

`Get-RecoverableItems -Identity laura@contoso.com -SubjectContains "FY17 Accounting" -FilterItemType IPM.Note -FilterStartTime "2/1/2018 12:00:00 AM" -FilterEndTime "2/5/2018 11:59:59 PM"`

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by markjjo** [comment]
@JSHooper Thanks for the heads up. I have fixed and the updated version will be published by tomorrow. Next time, feel free to make this type of change yourself and then submit a pull request. Please see https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md
