### ISSUE TITLE
RecordingStorageMode Is not listed in documentation

### ISSUE THREAD

**Issue by MrHinsh** [MicrosoftDocs/office-docs-powershell#6114]
https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps

There is no documentation for "RecordingStorageMode" that is listed in the output. How do I set this value and what can I set it to?

![image](https://user-images.githubusercontent.com/5205575/86942030-929a3680-c13c-11ea-9875-5c4db59f3581.png)

#5668

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @MrHinsh Martin, how are you?

I am looking into this, so far I could get the two possible values that are Stream and OneDriveForBusiness, once I get the description for the parameter, I will update the article.

Thank you
