### ISSUE TITLE
Clarify if group policy assignment results in inherited policy setting for any new users added in the future to the group

### ISSUE THREAD

**Issue by philrice** [MicrosoftDocs/office-docs-powershell#6119]
Documentation is not clear as to if when you use  New-CsGroupPolicyAssignment to apply a policy to a group that it applies the Teams policies to each user in the group by propagating it down to each member as a one time operation (therefore requiring reapplication if the group membership changes)  or if the policy is then tied to that security group and members added in the future inherit that policy automatically.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f8afd4c-7828-e7e7-dddc-e14673396f39
* Version Independent ID: dabb388b-8614-4b69-4e0a-f0536ab2bab6
* Content: [New-CsGroupPolicyAssignment (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csgrouppolicyassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-CsGroupPolicyAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsGroupPolicyAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @philrice Phil, How are you ? 👍 

As the article says
 _This is used **to assign** a policy to a security group or distribution list._

From my point of view the policy is tied to the group so any new user added to the group will inherit the policy, besides that, decided to test to verify in my lab tenant:

Added a user to a group that was already assigned a policy thru this cmdlet, the assigned policy was inherited by the user, no need to re-apply the policy to the group.

Hope this clarifies it to you,

Thank you!

**Comment by philrice** [comment]
Hi

Yes I did my tests after wards also and found that new group members do indeed inherit the policy which would be the desired setting, but better if the documentation is made it clear as if it is left unspecified then it is feasible that the behaviour could have been that the policy is assigned to the group, the group membership expanded and then the policy applied to the users individually.

**Comment by get-itips** [comment]
> Hi Yes I did my tests after wards also and found that new group members do indeed inherit the policy which would be the desired setting, but better if the documentation is made it clear as if it is left unspecified then it is feasible that the behaviour could have been that the policy is assigned to the group, the group membership expanded and then the policy applied to the users individually.

Hello @philrice Phil, how are you?

I understand what you say here, however this is different from what happened for example with SfB on-premises policies, where they were actually "applied", imho, in this case "assign" is clear, **but as that can be clear to me maybe it is not clear for others**, so I will propose clarifying this thru a PR, if it gets approval, it will be shown on the published version of the article. Thank you
