### ISSUE TITLE
Connect-ExchangeOnline Fails To Work on SOME tenants

### ISSUE THREAD

**Issue by dawander** [MicrosoftDocs/office-docs-powershell#6120]
This is very strange and we have been unable to figure out whats different between tenants.  We have tried connecting to tenants with modern auth enabled/legacy auth disabled as well as both enabled.  There doesnt seem to be a connection but when it fails, we receive the following error message:  Import-PSSession : Data returned by the remote Get-FormatData command is not in the expected format.

We can open up 2 separate powershell instances and run Connect-ExchangeOnline against 2 different tenants.  One will work perfectly and the other throws the error above.  We have tried on multiple machines with the same results.  Support said there was nothing they could do and it would "just clear up in a few days."  We are unable to manage certain tenants because of this new condition.  It used to work great!  All modules are updated and even installed from scratch.

**Comment by dawander** [comment]
After further testing, I've been able to work around the issue.  Perhaps this is by design but it's not clear in the docs if that's the case.  And what's also strange is that it is not consistent across tenants.  When I use Connect-ExchangeOnline using a *.onmicrosoft.com global admin account, the cmdlet fails as per previous post.  However, if I run Connect-ExchangeOnline with a global admin with a *.domain.com global admin account, it works.  This is new behavior.  To work around the *.onmicrosoft.com global admin login, one can use the switch-DelegatedOrganization 'tenantname.onmicrosoft.com' and it will connect.   It's weird that it isn't the same on every tenant.  I can run the command using *.onmicrosoft.com credentials and it works.   It seems like things are in flux.  Where's the flux-capacitor when we need it.   Clarity on this would be super helpful.  Our powershell scripts are failing depending on the tenant.  Thanks guys.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dawander** [comment]
This appears to be resolved within the last 8 hours.  Thanks to the team for giving it attention.

**Comment by yogkumgit** [comment]
@dawander  Thank you very much for the contribution and sharing this explanation. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
