### ISSUE TITLE
Missing descriptions

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6122]
There are several {{Fill Description}} in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9dec50f-c0fd-2ae2-e8c6-2b7d2b35c3b8
* Version Independent ID: 48d543a5-18c5-e0dd-bcd9-86237b283189
* Content: [Clear-SPMetadataWebServicePartitionData (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/clear-spmetadatawebservicepartitiondata?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Clear-SPMetadataWebServicePartitionData.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Clear-SPMetadataWebServicePartitionData.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Thanks for reporting @hwkwicre
