### ISSUE TITLE
Maximum of Ten? What? where?

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/office-docs-powershell#6127]
Hi,

I'm unsure what "The Maximum limitation is 10" means in the description.

I was able to create 11 CsTeamEmergencyNumber objects with New-CsTeamsEmergencyObject.
I was able to add 11 numbers to the -EmergencyDialMask parameter when creating a New-CsTeamsEmergencyObject.

Can you clarify please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccb12d7a-24b0-fe77-c228-bdca8f9c4eb2
* Version Independent ID: d3f4a454-b6b6-2396-f52c-523512b23105
* Content: [New-CsTeamsEmergencyNumber (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencynumber?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsEmergencyNumber.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsEmergencyNumber.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @danny-levin
* Microsoft Alias: **dannyle**

**Comment by danny-levin** [comment]
+@Chen Chen (BUSINESS VOICE ROUTING)<mailto:chenc@microsoft.com> @Roy Kuntz<mailto:roykuntz@exchange.microsoft.com> to comment

(I just published this cmdlet on behalf of @Chen Chen (BUSINESS VOICE ROUTING)<mailto:chenc@microsoft.com>)

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by danny-levin** [comment]
Chen is no longer at Microsoft so adding Sudheer and Jundong to comment on this limit as I don’t remember.

From: Danny Levin <dannyle@microsoft.com>
Sent: Thursday, July 9, 2020 9:36 PM
To: MicrosoftDocs/office-docs-powershell <reply@reply.github.com>; MicrosoftDocs/office-docs-powershell <office-docs-powershell@noreply.github.com>; chenc@microsoft.com; Roy Kuntz <roykuntz@exchange.microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/office-docs-powershell] Maximum of Ten? What? where? (#6127)

+@Chen Chen (BUSINESS VOICE ROUTING)<mailto:chenc@microsoft.com> @Roy Kuntz<mailto:roykuntz@exchange.microsoft.com> to comment

(I just published this cmdlet on behalf of @Chen Chen (BUSINESS VOICE ROUTING)<mailto:chenc@microsoft.com>)

**Comment by get-itips** [comment]
Hello @danny-levin Danny, can you kindly confirm if you had any update ? Thanks

**Comment by kaishuipinggai** [comment]
Let me sync with my team and then we should either apply this restriction as a fix or update the doc here.

**Comment by get-itips** [comment]
> Let me sync with my team and then we should either apply this restriction as a fix or update the doc here.

Thank you

**Comment by TorrenManson** [comment]
Hi,

Are you suggesting that you would apply a limit to Teams to match the documentation? If I’m reading that correctly, I feel strongly that this isn’t the right approach. Ideally there wouldn’t be any restrictions on the number of items that can be configured, as far as emergency calling is concerned.

Thanks,
Torren

**Comment by kaishuipinggai** [comment]
We had a discussion with the team and we decided to remove "The Maximum limitation is 10"

I will create a new pull request for deleting this line.

**Comment by get-itips** [comment]
> We had a discussion with the team and we decided to remove "The Maximum limitation is 10"
> 
> I will create a new pull request for deleting this line.

This has been applied @yogkumgit please close

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @TorrenManson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
