### ISSUE TITLE
Unable to connect to SPO via Powershell

### ISSUE THREAD

**Issue by njmathews8** [MicrosoftDocs/office-docs-powershell#6130]
I am trying to connect to our SharePoint Tenant to provision OneDrive4Business but every attempt to connect receives the following error:

> Connect-SPOService : Cannot contact web site 'https://XXX-admin.sharepoint.com/' or the web site does not support
> SharePoint Online credentials. The response status code is 'Unauthorized'. The response headers are
> 'X-SharePointHealthScore=3, X-MSDAVEXT_Error=917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+f
> irst+browse+to+the+web+site+and+select+the+option+to+login+automatically.,
> SPRequestGuid=4b80649f-b049-9000-9a4a-c8166d31e08d, request-id=4b80649f-b049-9000-9a4a-c8166d31e08d,
> MS-CV=n2SAS0mwAJCaSsgWbTHgjQ.0, Strict-Transport-Security=max-age=31536000, SPRequestDuration=41, SPIisLatency=0,
> MicrosoftSharePointTeamServices=16.0.0.20224, X-Content-Type-Options=nosniff, X-MS-InvokeApp=1; RequireReadOnly,
> Content-Length=0, Content-Type=text/plain; charset=utf-8, Date=Thu, 09 Jul 2020 23:10:05 GMT, P3P=CP="ALL IND DSP COR
> ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI", Server=Microsoft-IIS/10.0,
> X-Powered-By=ASP.NET'.
> At line:1 char:1
> + Connect-SPOService -Url https://$orgName-admin.sharepoint.com -Creden ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Connect-SPOService], NotSupportedException
>     + FullyQualifiedErrorId : System.NotSupportedException,Microsoft.Online.SharePoint.PowerShell.ConnectSPOService

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @njmathews8 how are you?
Here we are limited to documentation changes and fixes, for your requests I would recommend
- Checking the permissions of the user you are providing to the cmdlet, there is an access denied in the error you shared.
- If that does not work please open a support ticket directly from your tenant, 

Hope this helps you in the right direction,
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @njmathews8 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
