### ISSUE TITLE
404 links

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6132]
There are 404 links on the page, such as Get-SPODataConnectionSetting and Get-SPODataConnectionSettingMetadata

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65bf2c0b-b0ec-2748-e47e-af66011efe30
* Version Independent ID: be3968f4-d766-0b45-384b-c51c47328a86
* Content: [SharePoint Online PowerShell](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit
