### ISSUE TITLE
Incorrect description

### ISSUE THREAD

**Issue by ksgopal4** [MicrosoftDocs/office-docs-powershell#6135]
Hi,

The text 'Use the New-LabelPolicy cmdlet to view sensitivity label policies in your organization.'. Seems wrong, perhaps cut and paste from Get-LabelPolicy?

Regards
Gopal
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2bb1433-09f3-644a-e1e1-76d4790e73c4
* Version Independent ID: 26b634b4-7bbf-8a6f-383a-4aa86f433a11
* Content: [New-Label (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-label?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-Label.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-Label.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment]
@ksgopal4, I fixed it But in the future, you, too, can make fixes like this directly without opening an Issue first. See <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
