### ISSUE TITLE
Question for Explaination for this Feature

### ISSUE THREAD

**Issue by lordmafi** [MicrosoftDocs/office-docs-powershell#6136]
Dear all,

I just wonder about two things. First of all, if I set the -EnableTranscriptionProfanityMasking to $true on Global it does not work by default as I check that the users do not have Global assigned by default. There is another CSOnlineVoicemailPolicy that is tagged "default" which is not editable. Now in an environment with >100k users how do I can enable TranscriptionProfanityMasking for everyone? Or specifically asked which policy works by default and how to adjust it?

Thanks in advance.

BR Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 718d3732-5ffd-0420-da3a-d4abd979d644
* Version Independent ID: 0050302b-0849-7f3c-32a0-5f751ac1d721
* Content: [Get-CsOnlineVoicemailPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinevoicemailpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineVoicemailPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineVoicemailPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @lordmafi Martin, how are you? :)

Did some tests in my lab and this is what I got:

Users by default show no value for OnlineVoicemailPolicy:

``` agorz@PENDULUM  ~  Get-CsOnlineUser debrab | ft displayname,OnlineVoicemailPolicy

DisplayName  OnlineVoicemailPolicy
-----------  ---------------------
Debra Berger
```

But, is this the Global or the Default predefined Voice Mail policies?

I could assign this demo user the Default one:

```  agorz@PENDULUM  ~  Get-CsOnlineUser debrab | ft displayname,OnlineVoicemailPolicy

DisplayName  OnlineVoicemailPolicy
-----------  ---------------------
Debra Berger Default
``` 

So that lead me to think that all users by default receive the global one, If I remove the assignment:

`Grant-CsOnlineVoicemailPolicy -Identity "sip:debrab@xxxxx.OnMicrosoft.com" -PolicyName $null`

``` agorz@PENDULUM  ~  Get-CsOnlineUser debrab | ft displayname,OnlineVoicemailPolicy

DisplayName  OnlineVoicemailPolicy
-----------  ---------------------
Debra Berger
```

So based on my tests users receive the Global policy by default.

It is true that the "Tag:Default" voice mail policy isn't editable.
It is also true that the "Global" has `EnableTranscriptionProfanityMasking` as false but it is editable.

did you observe something different?

Thanks

**Comment by get-itips** [comment]
@lordmafi Martin, have you seen my comment? Otherwise we will need to close this one, thanks!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and digging deep into it.  @lordmafi We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by lordmafi** [comment]
I am just wondering does the Profanity Masking only works with Exchange Online? We have Hybrid in place and activated it for on-prem mailboxes which is not working after waiting even a week for replication/activation.

**Comment by lordmafi** [comment]
It would be nice to have more clearity on this if there are any requirements to the mailbox.

**Comment by lordmafi** [comment]
The issue stays also how to assign it in huge enviroments as a default other than going through a script everytime someone onboards

**Comment by get-itips** [comment]
> I am just wondering does the Profanity Masking only works with Exchange Online? We have Hybrid in place and activated it for on-prem mailboxes which is not working after waiting even a week for replication/activation.

Hello @lordmafi Martin, how are you?
According to this, the transcription is also applied on an hybrid scenario:

![diagram](https://docs.microsoft.com/en-us/skypeforbusiness/sfbserver2019/media/plan-cloud-voice-mail-server1.png)
> Unanswered calls are handled as follows:

> For users homed in Skype for Business 2019 on premises, unanswered calls are sent by the on-premises Skype for Business Server to the online Cloud Voicemail service.
The service processes the voicemail, including transcription.
The service then deposits the voicemail in the Exchange mailbox of the user, whether the mailbox is on-premises or online.
Users can access their voicemail from either their Skype for Business or Outlook client.

However, Is this your scenario?

Also, I found more information about the default state of profanity masking here https://docs.microsoft.com/es-es/microsoftteams/set-up-phone-system-voicemail#setting-voicemail-policies-in-your-organization

Hope this information helps you.

**Comment by lordmafi** [comment]
Hi @get-itips Andres,
thanks for quick response, that was what I thought also. I did assign two user-based policies (Tag: TranscriptionProfanityMaskingEnabled) to me and another user and we did some testing, even after days it was still using bad words in the transcription. So I was wondering why it does not work if applied, only explanation I could think of, is that it is not working with on-prem mailboxes. I will set the global setting and test again.

**Comment by get-itips** [comment]
> Hi @get-itips Andres,
> thanks for quick response, that was what I thought also. I did assign two user-based policies (Tag: TranscriptionProfanityMaskingEnabled) to me and another user and we did some testing, even after days it was still using bad words in the transcription. So I was wondering why it does not work if applied, only explanation I could think of, is that it is not working with on-prem mailboxes. I will set the global setting and test again.

Ok looking forward to the results of that test, and also what are the software versions you have on-premises for sfb and Exchange ?

**Comment by lordmafi** [comment]
Exchange 2016 latest CU and sfb is online only. The user-based policies are not working I think we will create a ticket for it. Just will test the global setting.

**Comment by get-itips** [comment]
> Exchange 2016 latest CU and sfb is online only. The user-based policies are not working I think we will create a ticket for it. Just will test the global setting.

Martin, yes, I think it will be the best in this case, I will be very happy if you can share the outcome or resolution with us. I'll update the documentation with that valuable information if it is needed. 
Thanks for taking out some time to open the issue.

**Comment by yogkumgit** [comment]
@lordmafi Thanks for your conversation, please share your findings that can help improving this documentation. We are waiting to resolve this issues.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @lordmafi We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
