### ISSUE TITLE
CompleteAfter parameter issue

### ISSUE THREAD

**Issue by mramnet** [MicrosoftDocs/office-docs-powershell#6145]
In all examples of the CompleteAfter in Exchange Online, it always uses local time to the running administrator.  

Reference to this section from the parameter description:
_"In Exchange Online PowerShell, if you specify a date/time value without a time zone, the value is in Coordinated Universal Time (UTC)."_  
This doesn't appear to be true at all.  It uses local time.

For example, (abbreviated)
**New-MigrationBatch -CompleteAfter "7/30/2020 9:00PM"**
would result in the following parameters in the batch properties:
CompleteAfter              : 7/30/2020 9:00:00 PM
CompleteAfterUTC           : 7/30/2020 9:00:00 PM
And yes, it actually completes at the local time zone for me, 9PM local time PST. 

Running this as described (abbreviated example)
**New-MigrationBatch -CompleteAfter ((Get-Date "7/30/2020 9:00PM").ToUniversalTime())**
results in the following data in the batch properties:
CompleteAfter              : 7/31/2020 4:00:00 AM
CompleteAfterUTC           : 7/31/2020 4:00:00 AM

Something seems both wrong in the documentation on this page _and_ in the backend code.  The CompleteAfter and the CompleteAfterUTC shouldn't be the same, unless one is running this from that actual timezone.  However if I am required to input the UTC time for completion, the actual completion time is therefore wrong by the offset of the timezone, so would be breaking user expectation of actual completion time.

It's possible I'm missing something here, but it appears to be an issue.  This also affects the New-MoveRequest command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb26814-0698-3b82-c7cc-7150d1255fe3
* Version Independent ID: 47ce5d33-5483-8c8e-2aa2-532178bf466a
* Content: [New-MigrationBatch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @mramnet, thank you for your feedback and help us to improve docs.microsoft.com.

It's working for me as it's documented, at least with StartAfter:
![image](https://user-images.githubusercontent.com/33589238/87565901-a394fb80-c698-11ea-9cef-e377c233a98c.png)

I'm waiting now for the synchronization to finish, to test CompleterAfter using Set-MigrationBatch.

**Comment by mramnet** [comment]
If you provide the “CompleteAfter” as part of the New-MigrationBatch you can see the results right away, and one shouldn’t have to wait.  I can reproduce this at will.

**Comment by dariomws** [comment]
Tested it and -CompleteAfter works as it's documented:
![image](https://user-images.githubusercontent.com/33589238/87583455-5a51a580-c6b2-11ea-94e1-9279f6c93437.png)
![image](https://user-images.githubusercontent.com/33589238/87583597-997ff680-c6b2-11ea-8bdf-bd80a287b304.png)
![image](https://user-images.githubusercontent.com/33589238/87583761-d5b35700-c6b2-11ea-9799-18f050c16893.png)

The value is in UTC. Thank you so much for your help but I cannot update the article as I have evidence that it works as expected. If you still have issues, I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

**Comment by mramnet** [comment]
Actually you proved my issue.  The CompleteAfter and CompleteAfter UTC are the same.
So if you’re setting it to complete at 16:36, why is the UTC the same?  That’s an incorrect value.

**Comment by mramnet** [comment]
If I didn’t make my point clear before the issue is that when you’re presenting a command for a value to the system, both the UTC and the local time are the exact same in ALL your screenshots, which is 100% incorrect, unless you live in UTC.  I was just reporting on the CompleteAfter/CompleteAfterUTC as listed below but in all your screenshots, you can see that all the UTC values are incorrect.  That’s my point.

Yet in the documentation on the site, it insists that you must put in the UTC value, but that would also incorrect for LOCAL value.  There is something definitely awry here, or show me how this is supposed to be correct.

**Comment by dariomws** [comment]
StartAfter, StartAfterUTC, CompleteAfter, CompleterAfter values are all UTC. In my example, I provided the value in UTC and works as expected, so this looks good for me:
-------------------------------------------------------------------------------------------------------------------------------------------
Use the short date format that's defined in the Regional Options settings on the computer where you're running the command. For example, if the computer is configured to use the short date format mm/dd/yyyy, enter 09/01/2018 to specify September 1, 2018. You can enter the date only, or you can enter the date and time of day. If you enter the date and time of day, enclose the value in quotation marks ("), for example, "09/01/2018 5:00 PM".

In Exchange Online PowerShell, if you specify a date/time value without a time zone, the value is in Coordinated Universal Time (UTC).

To specify a date/time value for this parameter, use either of the following options:

Specify the date/time value in UTC: For example, "2016-05-06 14:30:00z".

Specify the date/time value as a formula that converts the date/time in your local time zone to UTC: For example, (Get-Date "5/6/2016 9:30 AM").ToUniversalTime(). For more information, see Get-Date.
-------------------------------------------------------------------------------------------------------------------------------------------

You can see in my examples that local time is 3 hours behind UTC.

Maybe I'm misunderstanding you, sorry.

**Comment by mramnet** [comment]
My ultimate point is that you're putting in a time for CompletAfter.  Are you on UTC?  What are your Powershell regional settings?  My Get-TimeZone shows a -08:00:00 offset.  So when I perform a -CompleteAfter via powershell it shouild show an appropriate different timezone like this:

CompleteAfter              : 7/15/2020 9:00:00 PM
CompleteAfterUTC           : **7/16/2020 4:00:00 AM**

But when it is performed with powershell, like all your screenshots provided above, the are the exact same timezone, and not converted to UTC:

CompleteAfter              : 7/15/2020 9:00:00 PM
CompleteAfterUTC           : **7/15/2020 9:00:00 AM**

The question and issue I'm asking here is -- why does this not convert to UTC when input is made using powershell?

Unless you are UTC all your screenshots for every single one of the UTC offsets above are the same, and they should be different.
CompleteAfter - LOCAL time zone
CompleteAfterUTC - UTC time zone

**Comment by dariomws** [comment]
Get-TimeZone shows a -03:00:00 offset here. In Exchange Online PowerShell, if you specify a date/time value without a time zone, the value is in UTC. In my examples, I add 3 hours after look at my local time, to provide it as UTC.

I agree that CompleteAfter and StartAfter could show us the local time, but it's not related to this article.

"The question and issue I'm asking here is -- why does this not convert to UTC when input is made using powershell?" I don´t understand this question.
For example, if you run:
- '-CompleteAfter "16/7/2020 4:00:00 AM"', you will set "7/16/2020 4:00:00 AM" (UTC)
- '-CompleteAfter "15/7/2020 9:00:00 AM"', you will set "7/15/2020 9:00:00 AM" (UTC)
It's always UTC.

If you want to provide local time, you need to run:
(Get-Date "5/6/2016 9:30 AM").ToUniversalTime()

Exchange Online PowerShell date/time is UTC, Windows PowerShell date/time is local time.

**Comment by mramnet** [comment]
It's ambiguous wording and process, that's why it's both documentation and service related.

If I follow the prescriptive guidance of the article and convert to UTC, the local time becomes the same as UTC, and therefore the actual batch will not complete at the EXPECTED time.  In my case it will run 8 hours late/early, because while the "CompleteAfterUTC" might be a correct time, it doesn't set the "CompleteAfter" correctly, therefore broken process.

It is related to this article because one must verify when these processes complete in a very absolute and precise way.  We can't guess or assume the time.  The UTC and local time should NEVER be the same, unless you happen to live in the actual UTC time zone.

It is both a problem with the article and the service, because the article insists on providing the time in UTC but I've never seen that actually work, because the conversion process never takes place.  It's always a local time.

Quote from the article:

In Exchange Online PowerShell, if you specify a date/time value without a time zone, the value is in Coordinated Universal Time (UTC).

```
To specify a date/time value for this parameter, use either of the following options:

Specify the date/time value in UTC: For example, "2016-05-06 14:30:00z".

Specify the date/time value as a formula that converts the date/time in your local time zone to UTC: For example, (Get-Date "5/6/2016 9:30 AM").ToUniversalTime(). For more information, see Get-Date.
```
This has to be precise and repeatable.

If I use the process above to move a mailbox at midnight tonight, I'd use the prescribed process:

(Get-Date "7/16/2020 12:01 AM").ToUniversalTime()
Full powershell would be 
New-MigrationBatch <data> -completeafter ((Get-Date "7/16/2020 12:01 AM").ToUniversalTime())

This would yield the following powershell results:

CompleteAfter              : 7/16/2020 7:01:00 PM
CompleteAfterUTC           : 7/16/2020 7:01:00 AM

That's absolutely incorrect and would be 7 hours late.

This is not tenant specific.  Either a problem with documentation or with code or both, as I stated... but not acceptable that this is inconsistent and imprecise.

**Comment by dariomws** [comment]
@mramnet sorry but I tried it and works as expected.

I wanted that my batch starts at 12:40, I need to provide the value on UTC, that's why I provide 15:40 to the -StartAfter parameter. It's what it's explained in the article.

**Comment by dariomws** [comment]
The only issue that I can see is that when you run Get-MigrationBatch, CompleteAfter and CompleteAfterUTC are both on UTC.

**Comment by mramnet** [comment]
Look, I get what you’re saying but there’s clearly a disparity.  I'll demonstrate all three possibilities here.

CHOICE 1 – using the GUI :: If I set a batch to complete at 9pm local in the GUI, it looks like this in powershell using "Get-MigrationBatch", and completes at 9pm as expected.

This option has a doubly-verified date/time for completion since both the UTC and local time are equivalent.  The batch completes as expected.
```
CompleteAfter    : 7/19/2020 9:00:00 PM
CompleteAfterUTC : 7/20/2020 4:00:00 AM
```

CHOICE 2 – using Powershell with local time:: If I set a batch to complete at 9pm local using powershell commands, it looks like this in Powershell using Get-MigrationBatch, and completes at 9pm as expected, yet the UTC time is incorrect.
IE – Set-MigrationBatch <params> -CompleteAfter "07/19/2020 9:00:00PM"

This result is confusing and misleading administratively since CompleteAfter and CompleteAfterUTC are not in sync, yet the service will use the local time ("CompleteAfter").
```
CompleteAfter    : 7/19/2020 9:00:00 PM
CompleteAfterUTC : 7/19/2020 9:00:00 PM  <- Wrong value
```

CHOICE 3 – using Powershell and converting to UTC :: If I set a batch to complete at 9pm local using the documented process on the page I’m submitting this error report for, using powershell, this is how it looks in the report:
IE - Set-MigrationBatch <params> -CompleteAfter ((Get-Date "07/19/2020 9:00:00PM").ToUniversalTime())

This is the version that strictly adheres to what is written and documented on this page.
```
CompleteAfter    : 7/20/2020 4:00:00 AM <- Wrong value
CompleteAfterUTC : 7/20/2020 4:00:00 AM <- Wrong value
```

I have no doubt that you set and expected a completion time based upon the UTC, but bear  in mind that the INPUT of the CompleteAfter parameter does not differentiate what time zone it is.  A conversion of a date string to universal time does nothing more than translate something to that time offset.   Using my example above for the time being "07/19/2020 9:00:00PM" … when you convert that using the following command:
(get-date "07/19/2020 9:00:00PM").ToUniversalTime()
You get the following result:
Monday, July 20, 2020 4:00:00 AM
So understand this is absolutely no different than using the following command:
New-MigrationBatch <params> -CompleteAfter "Monday, July 20, 2020 4:00:00 AM"
...which is absolutely not what is wanted here.

Side point… one shouldn’t have to double-work this.  If you’re going to tell me that in order for me to do this I need to manually offset what was set via ToUniversalTime, then that is ridiculous.  Look at this command (from my CHOICE 3 above):
Set-MigrationBatch <params> -CompleteAfter ((Get-Date "07/19/2020 9:00:00PM").ToUniversalTime())
I want this to complete at 9pm in my local time on that date.  You can clearly see it’s actually going to complete 7 hours late.  No question.  The webpage documentation here says convert to UTC but the result of that conversion is the wrong completion date/time.  That’s wrong.  The webpage documentation in my humble opinion should always say “when using powershell, always use the local time after verifying your time zone offset is correct”

This is the quote from the website:

```
To specify a date/time value for this parameter, use either of the following options:
•	Specify the date/time value in UTC: For example, "2016-05-06 14:30:00z".
•	Specify the date/time value as a formula that converts the date/time in your local time zone to UTC
```

If I convert to UTC there's no time zone information in the conversion, so the CompleteAfter gets a result that's 7 hours in the future, sets both CompleteAfter and CompleteAfterUTC as such, and the process never completes at the time I need (See CHOICE 3).  That is very bad.

And again, If I have to convert to UTC and then subtract 7 hours from that, why does the documentation say I need to do the conversion at all; why can't I just plug in the local time?  That's not what the documentation on this page says.

Final word here, I even tried using the first bullet point above and used the full date/time value in UTC
Just verifying the output, I did this -- I used an odd +2m just to make sure it was updating appropriately:
Get-Date "2020-07-19T21:02:00-07:00"
Result is "Sunday, July 19, 2020 9:02:00 PM"  (note: this is good, the same time +2m to what I wanted above in all my examples)
Set-MigrationBatch <params> -CompleteAfter "2020-07-19T21:02:00-07:00"
This is bullet #1 directly from above and from the website...
The result?

```
CompleteAfter    : 7/20/2020 4:02:00 AM
CompleteAfterUTC : 7/20/2020 4:02:00 AM
```

So that's exceptionally odd and also broken, would be 7 hours late.

**Comment by dariomws** [comment]
Thank you very much for your feedback, @mramnet. I'll pass it to the product team so they are aware of your ask.

**Comment by dariomws** [comment]
Hi @mramnet,

- CHOICE 1: I tested it and I agree, all seems to be good when you create the batch using the Admin Center, CompleterAfter and CompleterAfterUTC seems to have correct values.

- CHOICE 2: In my case, when I created the batch using New-MigrationBatch, it works as it's documented. But when I ran Get-, both StartAfter and StartAfterUTC were in UTC. The batch started and completed in UTC. Then I updated CompleterAfter using Set- and the same, it works as it's documented, and Get- showed me both in UTC.

- CHOICE 3: I tested it and It works as it's documented.

I sent this information to the product team so they are aware of it.

Thank you so much for your feedback.

**Comment by mramnet** [comment]
I never claimed to have an issue with StartAfter, so _why are you testing that_?  

And for Choice 2 and 3, specifically what commands did you run?  I gave you **specific** commands to enable reproduction of the issue.  Also, to be clear, I'm **not** claiming an issue with StartAfter.    If you're claiming that you tested it, I'd like to know specifically what you ran to test it, since I claim problems with CompleteAfter and you keep mentioning against StartAfter.  They are not the same thing.

The ultimate problem to solve here is I/we need precision on batch completion times.  Starting batches doesn't need precision and frankly I don't think many end-user admins care as much.  But when I need a batch to **complete** at 12:37PM local time I expect to have a powershell command that works **precisely**.  I get that you are saying it "works as documented" but you're not showing commands and results, where I am.  I can reproduce this and am being as detailed as possible.  Please tell me the commands and results on your end.

Even going back to your original screenshots, the evidence you provided, that's not in line with the webpage documentation.  You stated "7/15/2020 16:36 PM" but that is not specifying time zone, nor is to UTC.  That's effectively a "Choice 2" operation, and yes it will work just fine and complete just fine at the time you specify.  It presents an incorrect CompleteAfterUTC.  I want to know specifically what commands you ran for Choice3 to verify it.

Read this section, from the **-CompleteAfter** section on the webpage:

```
To specify a date/time value for this parameter, use either of the following options:
•	Specify the date/time value in UTC: For example, "2016-05-06 14:30:00z".
•	Specify the date/time value as a formula that converts the date/time in your local time zone to UTC
```
I did both of these and demonstrated results.  In your original screenshots above, you did not.  How exactly are you testing Choice3?

**Comment by dariomws** [comment]
The same should apply to StartAfter, this is why I'm testing both parameters.

I tested it also using "(Get-Date "5/6/2016 9:30 AM").ToUniversalTime()" but I didn´t add the screenshots here.

**Comment by mramnet** [comment]
So if as you say you are using "(Get-Date "5/6/2016 9:30 AM").ToUniversalTime()"  _of course that would run immediately when that date is 4 years in the past and you've passed that time_.  The fundamental reason why I am focusing on CompleteAfter is that this is the point where end-users are affected and _there must be absolute precision on the parameter's execution time_.  I can accept the synergy here of using StartAfter but we need to be very clear about expectation, action, and results (see below for the 4 rules).

So let me pose a question:  If I wanted a MigrationBatch to COMPLETE (not START, but COMPLETE) at precisely 7/16/2020 at 10pm PST - my local time - what exactly would be the command for that?  I've tested and failed against that, using the prescribed documentation, and shown all the details in the thread above to support.

Respectfully, if we test something, we need to provide the "understood" time it should complete, and the command line used to execute that command.  That way we can both cross check.
Saying that you did a Set-MigrationBatch -CompleteAfter AnyTimeAtAll and "it worked as expected" isn't informative, sorry.  My fundamental complaint here is that I EXPECT a batch to complete at precisely 9pm, the webpage SAYS to use a specific command for that, and the RESULT of that command doesn't show appropriately in Powershell, nor does it complete at the time expected.  If you test you need to provide:
1. The local time you expect the action to occur
2. The powershell command to support that action
3. The Get- commands to show the batch data after the batch is created/modified
4. The actual result of the action (did it really start or complete at that time)
Thank you...

**Comment by dariomws** [comment]
I sent this information to the product team so they are aware of it. We´ll close this issue but they added this task to their list.

Thank you so much for your feedback.

**Comment by dariomws** [comment]
@mramnet I have important information.

I didn't realize that there is a -TimeZone parameter. Each migration batch have their own time zone, the Admin Center set it but if you run New-MigrationBatch without -TimeZone the date/time parameters (CompleteAfter, CompleteAfterUTC, StartAfter, StartAfterUTC) will be UTC.

Also, is better to use “[DateTime]"7/30/2020 9:00PM Z"” or “[DateTime]"7/30/2020 9:00PM -700"” instead of “((Get-Date "7/30/2020 9:00PM").ToUniversalTime())”.

I'll update the article. Thanks again, for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

**Comment by mramnet** [comment]
Putting in the -Timezone parameter solely appears to change the local time references, which also appears to have no bearing on the actual resultant effect.

```
No -Timezone
StartAfter                 : 7/29/2020 10:00:00 AM
StartAfterUTC              : 7/29/2020 10:00:00 AM
CompleteAfter              : 7/29/2020 9:00:00 PM
CompleteAfterUTC           : 7/29/2020 9:00:00 PM

-Timezone is "Pacific Standard Time"
StartAfter                 : 7/29/2020 3:00:00 AM
StartAfterUTC              : 7/29/2020 10:00:00 AM
CompleteAfter              : 7/29/2020 2:00:00 PM
CompleteAfterUTC           : 7/29/2020 9:00:00 PM
```

Also I don't follow the "its better to use" reply.  In all cases, we must put in a UTC time, but it's logically backward to have to convert a local time to UTC and then be even more precise.  I understand that the code requires a UTC entry, but none of the "its better to use" examples provided result in 9pm time being actually _converted_ to UTC.

New-MigrationBatch ...data... -CompleteAfter "7/23/2020 4:00AM"
This works just fine.  I would agree that it's logically better to specify time zone, etc... but that just requires conversion and math and is logcally not really practical for admins.  More often than not, they know the local time for execution and have to convert it to UTC.  Hence...
New-MigrationBatch ...data... -CompleteAfter ((Get-Date "7/22/2020 9:00PM").ToUniversalTime())
Note that both of these result in the exact same processing time by exchange server (since I am -0700 in this case)

Adding the -Timezone parameter does help with visibly showing local time referenced.  That's perhaps the biggest callout here and thank you for that!

**Comment by dariomws** [comment]
Yes, -Timezone change the local time reference: StartAfter and CompleteAfter. StartAfterUTC and CompleteAfterUTC are UTC. It's clearly shown in your example. I'll apply some updates to the cmdlet articles to try to provide move detail about it.

About the UTC value requirement for the -CompleteAfter parameter, I cannot change it, and the product group has this feedback. Anyway, for this kind of feedback (feature request or update) I need to kindly redirect you to this resource https://office365.uservoice.com/.
There, your suggestion will reach the product team directly. Here we are limited to documentation issues and improvements.

Thanks!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @mramnet Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
