### ISSUE TITLE
RequiredVersion 2.0.3-Preview does not work in PowerShell 5.1

### ISSUE THREAD

**Issue by mvaneijken** [MicrosoftDocs/office-docs-powershell#6147]
Command `Install-Module -Name ExchangeOnlineManagement -RequiredVersion 2.0.3-Preview -AllowPrerelease` cannot be executed in Powershell 5.1. It gives the following error:

```
Install-Module : Cannot process argument transformation on parameter 'RequiredVersion'. Cannot convert value "2.0.3-Preview" to type "System.Version". Error: "Input string was not in a correct format."'
At line:1 char:64
+ ... -Name ExchangeOnlineManagement -RequiredVersion 2.0.3-Preview -AllowP ...
+                                                     ~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Install-Module], ParameterBindingArgumentTransformationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,Install-Module
```

PSVersionTable:

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

It works in PowerShell 7.1.0-preview.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @mvaneijken, thank you for your feedback and help us to improve docs.microsoft.com.

Exchange Online PowerShell v2 is only supported on PowerShell 5.1. It works for me:
![image](https://user-images.githubusercontent.com/33589238/87466846-5f005600-c5ed-11ea-8e9d-d8bb9e23349e.png)
Support for PowerShell Core will be added. More information here:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623

In v2.0.3-Preview only support for App-Only Authentication was added. More information:
https://www.powershellgallery.com/packages/ExchangeOnlineManagement/2.0.3-Preview

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @mvaneijken Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
