### ISSUE TITLE
Unable to reliably to use Connect-IPPSSession behind SNAT

### ISSUE THREAD

**Issue by DDog80sRocked** [MicrosoftDocs/office-docs-powershell#6154]
Hello wonderful GitHub community!  Our company just switched over to Active/Active firewalls and now our automated scripts to connect to Security and compliance powershell fail with error: "_The request for the Windows Remote Shell with ShellId <ID> failed because the shell was not found on the server. Possible causes are: the specified ShellId is incorrect or the shell no longer exists on the server. Provide the correct ShellId or create a new shell and retry the operation."_  According to MS documentation [here](https://docs.microsoft.com/en-us/powershell/exchange/mfa-connect-to-scc-powershell?view=exchange-ps#how-do-you-know-this-worked), this is due to the connection request using multiple source addresses.  Firewall team says they can't do source-based routing and won't change the SNAT having multiple IPs.  Do I have any options with Connect-IPPSSession or is there a way to successfully work around that?

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hello @DDog80sRocked, how are you? For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @DDog80sRocked Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
