### ISSUE TITLE
Unable to connect to MS365 with Modern Authentication on any platform that is not Windows

### ISSUE THREAD

**Issue by kai-h** [MicrosoftDocs/office-docs-powershell#6157]
New tenancies on MS365 now have modern authentication enabled by default for all users.
I am unable to connect to these tenancies from PowerShell on macOS as there is no way to configure modern authentication.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @kai-h, thank you for your feedback.

We are limited to documentation issues and improvements.

But I can tell you that Exchange Online team is working on support for PowerShell core (PS6 and PS7) for their PowerShell module:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623

Teams PowerShell is supported on PS core:
https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-overview

About Azure AD, the goal is to provide all the necessary Azure AD functionality via the Microsoft Graph PowerShell modules which are currently in preview https://developer.microsoft.com/en-us/graph/blogs/microsoft-graph-powershell-preview-now-on-powershell-gallery/. These modules install on PS5.1, PS6, and PS7.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @kai-h Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
