### ISSUE TITLE
Output does not match documention

### ISSUE THREAD

**Issue by JelleBroekhuijsen** [MicrosoftDocs/office-docs-powershell#6158]
The cmdlet does not seem to return an in-memory PnP Site Template but rather update the input file specified in $Path. Futhermore the cmdlet only seems to work when using an .xml template as input rather than a .pnp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4993195-5f25-b71d-6de7-69533fb63569
* Version Independent ID: f274bb8a-bb66-4bee-ac61-c88c2c3470bb
* Content: [Add-PnPListFoldersToProvisioningTemplate (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnplistfolderstoprovisioningtemplate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPListFoldersToProvisioningTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPListFoldersToProvisioningTemplate.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @JelleBroekhuijsen Jelle, how are you?

Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), a member of the PnP community will handle your request there.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @JelleBroekhuijsen Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
