### ISSUE TITLE
Inconsistancy in 2FA setups

### ISSUE THREAD

**Issue by crass00** [MicrosoftDocs/office-docs-powershell#6159]
When using the Exchange Online V2 powershell modules they do not behave the same on different machines.

On a non domained machine I can run connect-exchangeonline -userprincipalname myadminaccount@somewhere.com and it authenticates correctly

On a domained machine where I have a normal account and an admin account if I run the same command I get this output

New-ExoPSSession : User 'normalaccount@somewhere.com' returned by service does not match user 'myadminaccount@somewhere.com' in the request

Where 'normalaccount@somewhere.com is the account I am logged into the machine with.

If I use connect-exchangeonline  and manually enter in the username myadminaccount@somewhere.com then it with authenticate

When connecting with the later method the command Get-EXOMailbox works as do most others I have tried but Get-EXOMailboxPermission fails 

Get-EXOMailboxPermission : An error occurred while processing this request..
At line:1 char:1
+ Get-EXOMailboxPermission -identity auser@somewhere.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ProtocolError: (:) [Get-EXOMailboxPermission], Exception
    + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.Exchange.Management.RestApiClient.GetExoMailboxPe   rmission

This command works If I connect from a non domained machine so I think it's related to authetication.

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hello @crass00, how are you? For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @crass00 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
