### ISSUE TITLE
OverflowAction and TimeoutAction not aligning to UI

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#6160]
Hello,

the Overflow Action and TimoutAction have parameters that I cannot line up with what the Admin Center offers.
Could you clarify please?

-OverflowAction:
PARAMVALUE: DisconnectWithBusy | Forward | Voicemail | SharedVoicemail

-TimeoutAction
PARAMVALUE: Disconnect | Forward | Voicemail | SharedVoicemail

UI (same for both):
Disconnect (OA: DisconnectWithBusy / TA: Disconnect)
OR
Person in Organisation (Forward, UPN of UserAccount)
Voice App (Forward, UPN of ResourceAccount)
External PhoneNumber (Forward, TEL URI)

The UI has no option for VoiceMail or SharedVoicemail (only the Auto Attendant has).

Is this intentional (configuration of Voicemail and SharedVoiceMail only via PowerShell) or are UI and PS misaligned?

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4128d55a-2a26-47be-04e7-6a71eece2143
* Version Independent ID: 7d0d9c25-c6f1-4ae3-b4e3-3b6de536ffa3
* Content: [New-CsCallQueue (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment]
Hello @DEberhardt David, how are you?

Did some tests in my demo tenant and I do have the Voicemail option:

![image](https://user-images.githubusercontent.com/36666927/87831962-3b424780-c85b-11ea-878e-830a44a2ba80.png)

I configured the Queue using PowerShell, both forwarding to VoiceMail or SharedVoiceMail, the option "Voicemail" in the GUI persisted, so it seems that in the UI, the Voicemail option works for both.

Also tried all options and this is what I conclude:

**OverflowAction**
DisconnectWithBusy -> Disconnect in the UI
Forward (with OverFlowActionTarget with a guid) -> Redirect this call to Person in organization in the UI
Forward (with OverFlowActionTarget with a resource guid) -> Redirect this call to VoiceApp in the UI
Forward (with OverFlowActionTarget with a Tel: uri) -> Redirect this call to External Phone Number in the UI
Voicemail  (with OverFlowActionTarget with a guid) -> Redirect this call to voicemail in the UI
SharedVoicemail  (with OverFlowActionTarget with a Group Guid) -> Redirect this call to voicemail in the UI

Hope this information helps you,

Andres

**Comment by DEberhardt** [comment]
Thank you. The Voicemail does now show for me too (in CallQueues).
This wasn't the case when I checked my demo tenant when writing the post though.

I guess, some of the confusion comes up because you have 1 PS parameter for 3 UI options as well as 2 PS parameters for 1 UI option...
It would have been easier to either just call it "Forward" or to call it "ForwardToUser", "ForwardToApp", "ForwardToTel" and "ForwardToVoiceMail" and "ForwardToSharedVoicemail" instead... ;)

The background to this is that I am authoring PS scripts that wrap around this for UPNs as well as an Excel provisioning form for bulk Queue creationg (that spits out full PowerShell scripts).
I have to model the input for the latter with 5 different options, thereby loosing the alignment and look and feel to the UI.

**Comment by get-itips** [comment]
> Thank you. The Voicemail does now show for me too (in CallQueues).
> This wasn't the case when I checked my demo tenant when writing the post though.
> 
> I guess, some of the confusion comes up because you have 1 PS parameter for 3 UI options as well as 2 PS parameters for 1 UI option...
> It would have been easier to either just call it "Forward" or to call it "ForwardToUser", "ForwardToApp", "ForwardToTel" and "ForwardToVoiceMail" and "ForwardToSharedVoicemail" instead... ;)
> 
> The background to this is that I am authoring PS scripts that wrap around this for UPNs as well as an Excel provisioning form for bulk Queue creationg (that spits out full PowerShell scripts).
> I have to model the input for the latter with 5 different options, thereby loosing the alignment and look and feel to the UI.

@DEberhardt David, how are you? Thanks for returning and sharing your last feedback. I can understand your pain when building one liners PS commands using Excel, we can conclude that what we see today is a combination of two parameters and not only one.
Probably you know the resource but you could suggest an improvement in https://microsoftteams.uservoice.com/

**Comment by DEberhardt** [comment]
Hello,
yeah, I will live with that :)
Just need to add one more element to the Spreadsheet.

Are there any verifications I can do against Voicemail and SharedVoicemail to ensure I am linking the right resource?

Thanks,
David

**Comment by get-itips** [comment]
> Are there any verifications I can do against Voicemail and SharedVoicemail to ensure I am linking the right resource?

Can you please detail what would be "right" resource here? Thanks

**Comment by DEberhardt** [comment]
A Unified Group in this case. Get-UnifiedGroup is what I have found, though I would also need a connection to ExchangeOnline. Is there any other way to verify my target reliably?

**Comment by get-itips** [comment]
> A Unified Group in this case. Get-UnifiedGroup is what I have found, though I would also need a connection to ExchangeOnline. Is there any other way to verify my target reliably?

Hello David, that appears to be the current way we have, also, it seems the cmdlet will perform a basic validation

> Invalid overflow action target (9543afc5-7940-4946-a382-fc32db6a1765).
    + CategoryInfo          : NotSpecified: (:) [Set-CsCallQueue], OnlineCmdletException
    + FullyQualifiedErrorId : Unspecified,Microsoft.Rtc.Management.Hosted.CallQueue.SetCsCallQueueCmdlet
    + PSComputerName        : admined6.online.lync.com
