### ISSUE TITLE
Set-ProtectionAlert -NotifyUser Does Not Work as Expected

### ISSUE THREAD

**Issue by andrew951** [MicrosoftDocs/office-docs-powershell#6164]
When attempting to set the -NotifyUser, I get the following error message. $notifyuser is an array
`Get-ProtectionAlert -Identity "Suspicious email sending patterns detected" | Set-ProtectionAlert -NotifyUser $notifyuser`
```
The source was not found, but some or all event logs could not be searched.  Inaccessible logs: State.
    + CategoryInfo          : NotSpecified: (:) [Set-ProtectionAlert], SecurityException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.Office.CompliancePolicy.Tasks.SetProtectionA
   lert
    + PSComputerName        : nam02b.ps.compliance.protection.outlook.com
```

**Comment by dariomws** [comment]
Hi @andrew951, thank you for your feedback and help us to improve docs.microsoft.com. I'll report this to the product team.

**Comment by andrew951** [comment]
Hi @dariomws, I noticed that the pull request will change the -NotifyUser to an internal Microsoft command use only. Does that mean there is currently no way to modify who would be notified for an alert via Powershell?

**Comment by dariomws** [comment]
Hi @andrew951, thank for your comment.

I tested it and got the same message, so I decided to put this message (let's see if it's approved) because this parameter is not available at this moment, and send the information to the product group so they can check it.

**Comment by andrew951** [comment]
Can we reopen the issue to keep track on the missing functionality of NotifyUser?

**Comment by dariomws** [comment]
Hi @andrew951, thank you again for your help.

There is no ETA for this functionality, sorry about that. This is why we cannot keep this issue open until it's available.
