### ISSUE TITLE
ConditionalAccessPolicy Requires Interactive Session

### ISSUE THREAD

**Issue by gh05ted** [MicrosoftDocs/office-docs-powershell#6167]
It's not possible to run the following in a non-interactive PowerShell session:
`Set-SPOTenant -ConditionalAccessPolicy BlockAccess`
It instead provides an error:
`Set-SPOTenant : Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.`
When running interactively, it returns a confirmation prompt as follows, which cannot be bypassed with a -Force prompt (parameter cannot be found).
```
Confirm
Are you sure you want to perform this action?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):
```
Expected behavior is that the parameter responds to a -Force command, or does not require a prompt. Other parameters that I've tested don't have this behavior. Is there a way to bypass this prompt for non-interactive sessions?

**Comment by gh05ted** [comment]
Small addition: it also doesn't respect `-Confirm:$false`. Again, 'a parameter cannot be found that matches parameter name 'Confirm'.

**Comment by get-itips** [comment]
Hello @gh05ted how are you? Hope you are doing great.
I checked and as you say, this cmdlet does not supports -Force parameter. So for that inquiry I need to kindly suggest https://sharepoint.uservoice.com/ that way, your request can reach the product team so they add support for it.
Thank you

**Comment by gh05ted** [comment]
Thanks @get-itips. Raised: https://sharepoint.uservoice.com/forums/330318-sharepoint-administration/suggestions/40953460-enable-setting-conditionalaccesspolicy-without-int

**Comment by get-itips** [comment]
> Thanks @get-itips. Raised: https://sharepoint.uservoice.com/forums/330318-sharepoint-administration/suggestions/40953460-enable-setting-conditionalaccesspolicy-without-int

Great! will vote for it.

**Comment by yogkumgit** [comment]
@gh05ted  Thank you very much for your kind feedback also thanks for logging this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Comment by ATS-mcooke** [comment]
It doesn't make sense to have to "vote" to have the very basic and well-established -Confirm switch implemented.
