### ISSUE TITLE
Remove-CalendarEvents should include option to select one calendar entry for cancellation.

### ISSUE THREAD

**Issue by Zankur-me** [MicrosoftDocs/office-docs-powershell#6169]

**Comment by dariomws** [comment]
Hello @Zankur-me, thanks for your feedback. 

For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/.
There, your suggestion will reach the product team.

**Comment by yogkumgit** [comment]
@Zankur-me  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
