### ISSUE TITLE
Get-TeamChannel command is unable to return Membership Type property value for channels

### ISSUE THREAD

**Issue by aravindmunna** [MicrosoftDocs/office-docs-powershell#6172]
(Get-TeamChannel -GroupId $SrcGroupID) | Format-Table Id, DisplayName, Description, MembershipType

![image](https://user-images.githubusercontent.com/4700718/87655756-efa77500-c758-11ea-8a20-7385c158ca8d.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b48c32-ad79-4249-638b-f53f9d76397f
* Version Independent ID: 36d9cfe0-cf60-2fa1-41b4-6c6971042394
* Content: [Get-TeamChannel (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by get-itips** [comment]
Hello @aravindmunna 
How are you?
I see that, using the preview version of the module (1.1.3-preview) that is working so it is probably going to be fixed by the next stable version of the module.
![image](https://user-images.githubusercontent.com/36666927/87715954-7a519980-c784-11ea-9ff0-2055b5d1bc0f.png)

Hope this information helps you,

**Comment by aravindmunna** [comment]
@get-itips Hi , I'm doing good. Thank you very much for your response on this regard.

I was working on some automation script, while testing i was trying to differentiate public channels and private channels and tried using this property but unable to achieve so thought posting this issue..

Many Thanks..

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @aravindmunna Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
