### ISSUE TITLE
[!Note] not being correctly displayed

### ISSUE THREAD

**Issue by ptyx507** [MicrosoftDocs/office-docs-powershell#6177]
The [!Note] syntax doesn't appear to be rendering correctly. Might be a syntax issue on the md file itself for line 20.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4c7fa70-28da-2cbe-b7bb-7ae0b64414d0
* Version Independent ID: 94efecca-5f32-fbb4-f479-cac6683d081a
* Content: [Get-MailboxStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailboxstatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailboxStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MailboxStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ptyx507, known issue. We're working to fix it (a publishing platform issue) Until then, I modified the formatting.

Thanks for the feedback.

Closing
