### ISSUE TITLE
Applies to says "Skype for Business Online", but this is Teams meeting policy, hence applies to should say :"Microsoft Teams"

### ISSUE THREAD

**Issue by MSTejas** [MicrosoftDocs/office-docs-powershell#6179]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18b9baa8-da13-a24f-af31-91d63de13f08
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps&source=docs)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by MSTejas** [comment]
Applies to says "Skype for Business Online", but this is Teams meeting policy, hence applies to should say :"Microsoft Teams"

**Comment by get-itips** [comment]
Hello @MSTejas How are you?
Thanks for your feedback, please see [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/5405#issuecomment-624118384) 
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @MSTejas Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
