### ISSUE TITLE
Remove-dkimsigningconfig domain.com

### ISSUE THREAD

**Issue by tofkamp** [MicrosoftDocs/office-docs-powershell#6187]
I can create a new dkim signing config with powershell, get and set it to enabled. But how to remove it ?
If I run get-dkimsigningconfig, I get some dkim's configs for email domains which are gone.
There is no command to remove it. The domain is already removed from accepted-domains in the Exchange Admin Console.
Why is there a difference between accepted domains in EAC and the dkimsingningconfig ?
Please intergrate this in the console, and help the system-admin with the DNS settings, just like it is done for adding domains to 365.

**Comment by dariomws** [comment]
Hi @tofkamp, thank you for your feedback and help us to improve docs.microsoft.com.

If we have not enabled DKIM, Office 365 automatically creates a 1024-bit DKIM public key for all the custom domains and the associated private key which are stored internally in Microsoft datacenters. By default, Office 365 uses a default signing configuration for all domains that do not have a policy in place. This means that if DKIM is not manually setup, Office 365 will use its default policy and keys to enable DKIM. **Also, if we disable DKIM signing after enabling it, Office 365 will automatically apply the Office 365 default policy for this domain**.

The last sentence is the reason why you don't have a Remove-DkimSigningConfig cmdlet. You cannot completely remove it. If you still see the removed domain when you run Get-DkimSigningConfig, I need to kindly redirect you to support, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @tofkamp Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
