### ISSUE TITLE
MicrosoftTeams version 1.1.4 is incorrectly versioned and breaks backward compatibility

### ISSUE THREAD

**Issue by KirkMunro** [MicrosoftDocs/office-docs-powershell#6188]
I've tried reaching out other ways, but this issue has not been acknowledged yet, so I'm hoping that someone here can pass it on to the right folks.

On July 1st, the Microsoft Teams team released version 1.1.3-preview of their MicrosoftTeams module. This preview version contains functionality not available in the current release/stable version, including management of private groups, among other things. This release was also the first time that this team published a preview release into the PowerShell Gallery. Prior to this, their releases were published to an internal gallery that most folks don't know about.

On July 6th, the Microsoft Teams team released an update to their release/stable version. This release does not support management of private groups. When this was published, it was given a version number of 1.1.4, which is the successor to 1.1.3-preview.

**The way this was versioned is incorrect. It breaks the upgrade path for this module by breaking backwards compatibility because version 1.1.4 is not compatible with scripts that were previously written for 1.1.3-preview.**

I'm pretty sure I know why this happened. I suspect the Microsoft Teams team uses Azure DevOps to build their module, and has something in their build and release pipelines that grabs the latest version from the PowerShell Gallery (which was 1.1.3-preview at the time), and simply increments the build number, which resulted in version 1.1.4.

To correct this issue, they should:

1. Remove (hide) version 1.1.3-preview from the PowerShell Gallery.
1. Publish a new preview release that is versioned 1.2.0-preview, and make sure their preview pipeline increments off of the latest preview release (this would use 1.2.x version numbers).
1. Update the build/release pipelines for the stable version to increment off of the latest non-preview release (that would make it use 1.1.x versioning).
1. At a future time when the preview release is meant to replace the stable release, drop the -preview suffix, stay with the 1.2.x versioning, update the stable release pipeline (if necessary) to increment off of the latest stable release (which would be a 1.2.x version at this point), and start building previews off a 1.3.x version set.

Something along those lines anyway.

If someone could direct this message to the appropriate PM on the Microsoft Teams team, that would be appreciated.

**Comment by get-itips** [comment]
Hello @KirkMunro Kirk, how are you? Hope you are doing good.
Also noted this. We will need to close this for now as it is not a documentation issue, however, will try to forward this to the team as that was your intention.
Thanks for your feedback.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @KirkMunro Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
