### ISSUE TITLE
Get-CSOnlineTelephoneNumber -ExpandLocation

### ISSUE THREAD

**Issue by ZB-BT** [MicrosoftDocs/office-docs-powershell#6189]
Hello!

I'm doing some work with number assignment and am attempting to use the Get-CSOnlineTelephoneNumber with the ExpandLocation switch. 

The CmdLet by itself runs fine however when I use -ExpandLocation I get a NullReferenceException.

`PS C:\WINDOWS\system32> Get-CsOnlineTelephoneNumber -ExpandLocation

Object reference not set to an instance of an object.
    + CategoryInfo          : NotSpecified: (:) [Get-CsOnlineTelephoneNumber], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Rtc.Management.Hosted.Bvd.GetBvdTelephoneNumberCmdlet
    + PSComputerName        : admin2a.online.lync.com`

I did try a fresh install of the connector on another computer but I continue to get the same error. I've definitely used this switch in the past successfully so I'm not sure what might've changed.

Some details:
**PSVersion:** 5.1.17134.858
**C++ Redist:** Microsoft Visual C++ (2015-2019) Redistributable (x64) - 14.24.28127
**Connector Version:** 7.0.2374.2

Hopefully I'm just doing something dumb and can't tell. If anyone has any advice I'd really appreciate it.

Thanks for your time!

**Comment by get-itips** [comment]
Hello @ZB-BT How are you?
Tried and received the same error, however, tried specifying a `-TelephoneNumber` and did not receive an error.
In case you still receive an error I recommend opening a support ticket directly from your tenant.
Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ZB-BT Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
