### ISSUE TITLE
Submit-PnPSearchQuery documentation page should be updated to reflect Invoke-PnPSearchQuery

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/office-docs-powershell#6190]
The header and navigation link for this article show Submit-PnPSearchQuery as the name of this cmdlet. This naming convention is deprecated, and the new cmdlet name is Invoke-PnPSearchQuery.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd988f0-5cde-1e9e-a88e-21cc1fccfa5c
* Version Independent ID: 8c1f6c2d-c7d8-6762-da20-a7cc36e1b5ae
* Content: [Submit-PnPSearchQuery (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/submit-pnpsearchquery?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Submit-PnPSearchQuery.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Submit-PnPSearchQuery.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @joshtransient How are you?
how are you?

Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), a member of the PnP community will handle your request there. The documentation for PnP cmdlets is directly reflected from cmdlet's source code and then impacted on this repo.

Thank you!

**Comment by joshtransient** [comment]
This is a documentation issue, and I was linked here from the docs.microsoft.com page. If the button on docs.microsoft.com sends to the wrong place, then it needs to be updated.

**Comment by get-itips** [comment]
> This is a documentation issue, and I was linked here from the docs.microsoft.com page. If the button on docs.microsoft.com sends to the wrong place, then it needs to be updated.

You are 100% right, but for now I need to kindly redirect you and all the other users that open PnP issues to the right resource so you/they can have answers from the PnP maintainers. 
Hope this clarifies it to you. Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @joshtransient Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
