### ISSUE TITLE
Shouldn't this also apply to Microsoft Teams?

### ISSUE THREAD

**Issue by Ovyone** [MicrosoftDocs/office-docs-powershell#6193]
Shouldn't this also apply to Microsoft Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eefa80b-840f-d693-9876-7f20e641285d
* Version Independent ID: f8be06d4-86ff-ecda-e4b3-1f42e85f4909
* Content: [Get-CsExternalAccessPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csexternalaccesspolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsExternalAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsExternalAccessPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @Ovyone 
How are you?
Thanks for your feedback, please see [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/5405#issuecomment-624118384)
Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Ovyone Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
