### ISSUE TITLE
CdnType Private NotImplemented in GCC?

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/office-docs-powershell#6196]
I get a 'NotImplemented' exception when attempting to use this cmdlet with the CdnType of Private:\

```
PS C:\> Set-PnPTenantCdnEnabled -CdnType Private -Enable $true
Set-PnPTenantCdnEnabled : The method or operation is not implemented.
At line:1 char:1
+ Set-PnPTenantCdnEnabled -CdnType Private -Enable $true
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPTenantCdnEnabled], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Admin.SetTenantCdnEnabled
PS C:\> 
```

The tenant is in GCC so that might be a clue (or distraction).

Things I've tried: Bing
Thing I'll try next: Looking at the code...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fbc7344-3d65-6cf0-1a1a-7a7488ccb11a
* Version Independent ID: aa788a73-2de9-e8ae-42c1-52d969e5b287
* Content: [Set-PnPTenantCdnEnabled (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnptenantcdnenabled?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPTenantCdnEnabled.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPTenantCdnEnabled.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @sparkitect Jim, 
how are you?
Thanks for your feedback.
I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), a member of the PnP community will handle your request there. 
Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @sparkitect Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by sparkitect** [comment]
According to https://docs.microsoft.com/en-us/office365/enterprise/content-delivery-networks:
 ```
Note

The Office 365 CDN is only available to tenants in the Production (worldwide) cloud. Tenants in the **US Government**, China and Germany clouds do not currently support the Office 365 CDN.
```

Perhaps the documentation here should note that as well; the Applies To tag indicates only "SharePoint Online" which doesn't really distinguish between 'clouds'...

**Comment by get-itips** [comment]
> According to https://docs.microsoft.com/en-us/office365/enterprise/content-delivery-networks:
> 
> ```
> Note
> 
> The Office 365 CDN is only available to tenants in the Production (worldwide) cloud. Tenants in the **US Government**, China and Germany clouds do not currently support the Office 365 CDN.
> ```
> 
> Perhaps the documentation here should note that as well; the Applies To tag indicates only "SharePoint Online" which doesn't really distinguish between 'clouds'...

@sparkitect Jim, here is the document you have to create the issue against to

https://github.com/pnp/PnP-PowerShell/blob/master/Commands/Admin/SetTenantCdnEnabled.cs

https://github.com/pnp/PnP-PowerShell/issues

Thanks

**Comment by sparkitect** [comment]
@get-itips I humbly disagree: The command is working exactly as it is supposed to, given that it is _not supported_ in SharePoint Online **GCC**. 

However, the _documentation_ for the command fails to mention that it is not supported in SharePoint Online **GCC**.

**Comment by get-itips** [comment]
> @get-itips I humbly disagree: The command is working exactly as it is supposed to, given that it is _not supported_ in SharePoint Online **GCC**. 
> 
> However, the _documentation_ for the command fails to mention that it is not supported in SharePoint Online **GCC**.

Jim, I understand that, the thing is that *any* PnP related issue/feedback/comment has to be handled in that other repo I referenced.
Documentation for PnP cmdlets is then reflected here.
Please let me know if that clarifies it to you. Thank you.

**Comment by get-itips** [comment]
@sparkitect Jim, if you feel this other doc that you referenced needs a fix https://docs.microsoft.com/en-us/office365/enterprise/content-delivery-networks please, kindly open an issue against it (because it lives in another repository) Thank you!

**Comment by sparkitect** [comment]
> @sparkitect Jim, if you feel this other doc that you referenced needs a fix https://docs.microsoft.com/en-us/office365/enterprise/content-delivery-networks please, kindly open an issue against it (because it lives in another repository) Thank you!

No, that doc is correct in that is **does** mention that the Office 365 CDN is not supported in SharePoint Online **GCC** whereas this doc does not.

**Comment by get-itips** [comment]
Hello @sparkitect 
Jim, how are you?
Returning to this thread to summarize:

Essentially, the documentation for PnP cmdlets is synchronized into the _office-docs-powershell_ repo, that's why the feedback about it lands here, however, collaborators that handle PnP cmdlets (**including documentation**) work in this repo https://github.com/SharePoint/PnP-PowerShell/ that is the reason I redirected you there, so they can make the needed adjustments to the article based on your feedback.

If the article that you identify an issue is this https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnptenantcdnenabled?view=sharepoint-ps in the "applies to" section, probably a note should be added to the Set-PnPTenantCDNEnabled documentation stating the support about GCC, and that has to be done in the repo I referenced.

Can you kindly create the same issue in that other repo?

Please let me know if I misunderstood you in any way. 👍 

Thank you for your feedback Jim.

**Comment by sparkitect** [comment]
Thanks for the clarification, Andres.

I think the confusion comes form the fact that the page includes a button to ‘Submit and view feedback for this page’. If in fact the feedback for this page should be submitted elsewhere, perhaps that button should lead elsewhere as well.

I will try to find time to submit my feedback to the other repro, but perhaps something can be done so that this doesn’t continue to happen, as it’s a big waste of time for all of us…

Thanks,

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by get-itips** [comment]
> Thanks for the clarification, Andres. I think the confusion comes form the fact that the page includes a button to ‘Submit and view feedback for this page’. If in fact the feedback for this page should be submitted elsewhere, perhaps that button should lead elsewhere as well. I will try to find time to submit my feedback to the other repro, but perhaps something can be done so that this doesn’t continue to happen, as it’s a big waste of time for all of us… Thanks, 

@sparkitect Jim, I agree with you, I already reported that in the past and I understand is being taken care of. Thanks for your understanding and time expended.

**Comment by yogkumgit** [comment]
@sparkitect Thanks for understanding the situation. I am formally closing it here. Have a great day.
