### ISSUE TITLE
Example 4 Produces an error in Exchange Online

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/office-docs-powershell#6201]
Running 

New-ManagementScope -Name "Protected Exec Users" -RecipientRestrictionFilter "Title -like '*VP*'" -Exclusive; New-ManagementRoleAssignment -SecurityGroup "Executive Administrators" -Role "Mail Recipients" -CustomRecipientWriteScope "Protected Exec Users"

In Exchange Online will generate the error: "The management scope object Protected Exec Users is an exclusive scope, and it can't be specified as parameter CustomRecipientWriteScope."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2df47214-4ad2-4491-87f2-951ece1a02af
* Version Independent ID: 21406cd8-75b9-604b-de9d-7f2e54414644
* Content: [New-ManagementScope (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-managementscope?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ManagementScope.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ManagementScope.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @dkotars, thank you for your feedback and help us to improve docs.microsoft.com.

I tested it on my lab tenant and it works:
![image](https://user-images.githubusercontent.com/33589238/88594744-270b0100-d038-11ea-995b-898ddf4f99c3.png)

For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @dkotars Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
