### ISSUE TITLE
How do you remove ALL permissions from a mailbox?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/office-docs-powershell#6202]
Remove-MailboxPermission works great if you only want to remove one person's permission or have a csv file to pump in a list of users to remove but what if you just want to remove everyone who has permission?  I tried

`Get-MailboxPermission -Identity "user@Contoso.com" | Remove-MailboxPermission` 

and that does not work.  Also, the `-User` parameter doesn't accept wildcards or piped input.  Seems counter-intuitive to automation if you have to stop your script and manually look up accounts with access to enter one at a time for this command to work to remove all access.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bca33da-38fa-7312-f1a7-7776b6083fdf
* Version Independent ID: abb4e51e-0c72-1472-f820-4657d2c76543
* Content: [Remove-MailboxPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-mailboxpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-MailboxPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-MailboxPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @Canis-Lupis, thank you for your feedback.

-ResetDefault parameter is what you are looking for I think.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @Canis-Lupis Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by tdmarchetta** [comment]
I'm looking for a way to remove all users from a mailboxes permission. 
I would like to remove all of the mailbox delegations. Read and manage, Send As and Send on behalf 
---
Remove-MailboxPermission -Identity "joeuser@Contoso.com" -ResetDefault -Confirm:$false
---
This command only seems to remove read and manage. 
Any help would be greatly appreciated.

**Comment by dariomws** [comment]
@tdmarchetta it should also remove FullAccess. 

If it's not working as it's documented, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.
