### ISSUE TITLE
office-docs-powershell 

### ISSUE THREAD

**Issue by wedataintelligence** [MicrosoftDocs/office-docs-powershell#6203]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ae1495-235b-5e1d-0c73-932f3c28e5b7
* Version Independent ID: 52543c9c-2c4b-52bd-88a5-ebe2fafe62ce
* Content: [Get-ComplianceCase (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-compliancecase?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/Get-ComplianceCase.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-ComplianceCase.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @wedataintelligence, thank you for your feedback but I think you missed the detail about what you think we need to improve in this article.

We'll proceed to close this issue, if you want to provide us with more detail just came back here with another comment and we can open the issue again.

**Comment by yogkumgit** [comment]
@ Thank you very much for the contribution. @wedataintelligence  If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
