### ISSUE TITLE
Get-PnPHubSiteChild : The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator.

### ISSUE THREAD

**Issue by TheHailender** [MicrosoftDocs/office-docs-powershell#6205]
It seems that this command does not work if there are more than 5000 sites in the tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ec75a87-ea5a-c9c6-b15f-facb7c816760
* Version Independent ID: 002d95a1-c08e-9208-426f-9ca908079be1
* Content: [Get-PnPHubSiteChild (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnphubsitechild?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPHubSiteChild.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPHubSiteChild.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @TheHailender Jens

how are you?
Thanks for your feedback.
Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, a member of the PnP community will handle your request.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @TheHailender Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
