### ISSUE TITLE
A lot of parameters missing in description

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/office-docs-powershell#6206]
Compared to Set-CASMailbox this Set-CASMailboxplan documentation is missing a lot of parameters.
It only lists 
 [-ActiveSyncEnabled <Boolean>]
 [-ImapEnabled <Boolean>]
 [-PopEnabled <Boolean>]
when I do a get-casmailboxplan I get a lot more parameters that also correspond to the parameters available on set-CASMailbox:
MAPIEnabled                            
MapiHttpEnabled
EwsEnabled                              : 
EwsAllowOutlook                         :
EwsAllowMacOutlook                      :
EwsAllowEntourage
OWAEnabled
etc.

Can you please document them as well?
Or if they cannot be used give an explanation about that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dced9b81-f390-162a-a788-ae1455f57b49
* Version Independent ID: 8a0fb1a9-9a6b-f032-50dd-b0dcc2a13c20
* Content: [Set-CASMailboxPlan (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-casmailboxplan?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/set-CASMailboxPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/set-CASMailboxPlan.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @joergrenn, thank you for your feedback.

I confirm that the parameters you listed are the only ones available for this cmdlet:
![image](https://user-images.githubusercontent.com/33589238/88593591-2cffe280-d036-11ea-96da-6c1b99949729.png)

They are not available because you cannot use them. If you think some of them should be available,  I need to kindly redirect you to this resource https://office365.uservoice.com/. There, your suggestion will reach the product team.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @joergrenn Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by joergrenn** [comment]
A suggestion for this exists in the uservoice already for two years and nothing happens.
Very sad.

**Comment by yogkumgit** [comment]
@joergrenn  Thank you very much for your kind feedback. I agree with you and can understand your feelings. Uservoice requests follow certain norms. We have to wait for concerning team to evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
