### ISSUE TITLE
What about "'Microsoft Sync technology" protocol

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/office-docs-powershell#6207]
To my knowledge the  "'Microsoft Sync technology" is a new protcol used in newer versions of "outlook for ios or android" and the "new outlook for macOS".
Can this protocol also be blocked by client access rules?
Could you give some information about that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a161a14-001a-3bb0-64af-cdcd24708a3e
* Version Independent ID: df907b31-c01c-ff6d-2161-85e4e77a626d
* Content: [Set-ClientAccessRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-clientaccessrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-ClientAccessRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-ClientAccessRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@joergrenn, I don't know. Your best bet is to open a support ticket and ask.

**Comment by joergrenn** [comment]
@chrisda, sure I can do that. But shouldn't the documentation also say something about that? If there are protocols that the commands cannot block this would be good to know for administrators.

**Comment by chrisda** [comment]
@joergrenn, maybe. But let's see what they say when you open your support case and ask, "I want to use Client Access Rules to block the Microsoft Sync protocol (New Outlook for Mac and Outlook for IOS and Android)". That is a much more specific question and will get much more attention from the product team.

**Comment by joergrenn** [comment]
@chrisda my experience with the MS support has been mediocre at best. Most of the time the don't even understand the implications of a question. They are not connected to the product teams. 
I opened a ticket regarding this anyway and after some back and forth the answer was, you cannot block the microsoft sync protocol currently with client access rules.
And then there is always the suggestion that makes me furious, to open a user voice. This is BS and there are probably hundreds of thousands user voices and a dead end.
For this documentation I would suggest to at least mention that this other protocol exists and it cannot be blocked with client access rules.

**Comment by chrisda** [comment]
Instead of adding a note here, I felt it was more appropriate to add it to the main [Client Access Rules topic](https://docs.microsoft.com/Exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules).

If and when support for that protocol is added, I'll add to the Set-ClientAccessRule cmdlet reference topic.

Thanks for the feedback.

Closing
