### ISSUE TITLE
Overview link doesn't work

### ISSUE THREAD

**Issue by toffitomek** [MicrosoftDocs/office-docs-powershell#6213]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 719f5227-2b47-3487-99bb-222d18d43552
* Version Independent ID: e7833ab4-d2b1-5840-4f2c-dda86599d3af
* Content: [Microsoft Whiteboard Admin](https://docs.microsoft.com/en-us/powershell/module/whiteboard/?view=whiteboard-ps)
* Content Source: [whiteboard/whiteboard-ps/whiteboard/whiteboard.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/whiteboard/whiteboard-ps/whiteboard/whiteboard.md)
* Service: **whiteboard-powershell**
* GitHub Login: @tbrosman
* Microsoft Alias: **tbrosman**

**Comment by get-itips** [comment]
Thanks for reporting @toffitomek
