### ISSUE TITLE
Validate-RetentionRuleQuery - fails to do anything

### ISSUE THREAD

**Issue by robert5150** [MicrosoftDocs/office-docs-powershell#6214]
If i run: 

PS C:\Users\robert> Validate-RetentionRuleQuery 'from:"Ann Beebe" AND subject:northwind'

I get the below output: 

WARNING: The query string contains workload-specific properties. So, it should only be applied to workload which can understand these properties.

So while the command runs, it doesnt work in terms of validating the rule. 

Robert

**Comment by dariomws** [comment]
Hi @robert5150, thank you for your feedback and help us to improve docs.microsoft.com.

I have this comment from the product manager:
"The warning is actually exactly what the validation is supposed to do, it says this is not a KQL which will work for all workloads so it needs to only be used in the appropriate workload (EXO in this case)"

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @robert5150 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
