### ISSUE TITLE
Isolating why Connect-PnPOnline fails for some accounts?

### ISSUE THREAD

**Issue by breakpoint7** [MicrosoftDocs/office-docs-powershell#6215]
We've run into a scenario where Connect-PnPOnline fails for *some* accounts that are configured (as best we can tell) identically.  Using PnP version - SharePointPnPCoreOnline.3.23.2007

All these accounts succeed with -UseWebLogin and other variations of auth, but we're finding that the same call to pass creds will fail on *some* of the accounts.  All of them are setup the same in terms of AD enabled legacy and excluded from MFA.  It's not clear if this is a bug or there's some other difference.

For example making the same call with three identically configured accounts and passing creds:
Connect-PnPOnline -Url "https://mytenant.sharepoint.com" -Credentials $creds 
Error:  62@mytenant.com  :  The sign-in name or password does not match one in the Microsoft account system.
Error:  63@mytenant.com  :  The sign-in name or password does not match one in the Microsoft account system.
Success:  64@mytenant.com 

62@mytenant.com  :  Microsoft.SharePoint.Client.IdcrlException: The sign-in name or password does not match one in the Microsoft account system.
   at Microsoft.SharePoint.Client.Idcrl.IdcrlAuth.GetServiceToken(String securityXml, String serviceTarget, String servicePolicy)
...

Is there a recommended way to further isolate this (specific logs or tracing to show why it fails) or known issues that might cause the because?

**Comment by get-itips** [comment]
Hello @breakpoint7 
how are you?
Thanks for your feedback.
Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, a member of the PnP community will handle your request.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @breakpoint7 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
