### ISSUE TITLE
Get-PnPProvisioningTemplateFromWeb not centering text

### ISSUE THREAD

**Issue by sheykh-sleky** [MicrosoftDocs/office-docs-powershell#6222]
So, user error.  Right?  But when I issue "get-pnpprovisioningtemplate -out siteContent.xml" it runs and seems ok.  There is a webpart that has red, 'strong' and centered text.  When I apply that xml the text is red and strong just left justified.

What am I doing wrong?  What info can I provide?

PS G:\> Get-Module -Name Microsoft.Online.SharePoint.PowerShell -ListAvailable | Select Name,Version

Name                                   Version
----                                   -------
Microsoft.Online.SharePoint.PowerShell 16.0.20122.12000
Microsoft.Online.SharePoint.PowerShell 16.0.19515.0

PS G:\> Get-Module SharePointPnPPowerShellOnline -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

Name                          Version
----                          -------
SharePointPnPPowerShellOnline 3.21.2005.2

**Comment by get-itips** [comment]
Hello @sheykh-sleky 
how are you?
Thanks for your feedback.
Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, a member of the PnP community will handle your request.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @sheykh-sleky Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
