### ISSUE TITLE
Get-InboundConnector and Get-AdminAuditLogConfig not found?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/office-docs-powershell#6223]
Running ORCA gives a nice report, but the PowerShell console shows two error messages "The term '...' is not recognized as the name of a ..." for these 2 CmdLets.
I have 
```
PS C:\WINDOWS\system32> Update-Module ExchangeOnlineManagement
PS C:\WINDOWS\system32> Get-Module ExchangeOnlineManagement

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.1      ExchangeOnlineManagement            {Get-EXOCasMailbox, Get-EXOMailbox, Get-EXOMailboxFolderPe...

```
and no clue how to solve this.
Or is is not an issue, as the report seems to be generated fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83f2f405-907f-7bbe-8e60-b3c4eafc9368
* Version Independent ID: 41be33f7-b9ac-918a-41f6-8ed4d0d4c752
* Content: [Get-InboundConnector (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-inboundconnector?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-InboundConnector.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-InboundConnector.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @andrePKI, thank you for your feedback.

I cannot help you with ORCA here, we are limited to documentation issues and improvements but I can confirm that Get-InboundConnector and Get-AdminAuditLogConfig cmdlets are available in the Exchange Online PowerShell Module.
Please, check your configuration and permissions.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @andrePKI Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
