### ISSUE TITLE
Wondering ETA on Powershell 7 compatibility? 

### ISSUE THREAD

**Issue by VeloGeek** [MicrosoftDocs/office-docs-powershell#6225]
Greetings,

I was wondering what the roadmap is to having the Exchange Online v2 available for use with PowerShell 7?  I'm specifically looking into adding some EXO scripts to my Azure Shell environment but at the time of writing this it appears that is not possible.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell with modern authentication using V2 Module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @VeloGeek, thank you for your feedback.

We don't have this information here, but you can follow the Exchange Teams blog to news about the EXO V2 module:
https://techcommunity.microsoft.com/t5/exchange-team-blog/bg-p/Exchange
You can see in the blog that they're currently working on support for PowerShell Core, but there is no ETA.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @VeloGeek Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
