### ISSUE TITLE
winrm set does not work on Powershell 5

### ISSUE THREAD

**Issue by ankitjoshi8518** [MicrosoftDocs/office-docs-powershell#6230]
winrm set winrm/config/client/auth @{Basic="true"}
 THe above command does not workin Powershell v5

Details of my powershell version is as below:

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Running windows 10 pro

**Comment by get-itips** [comment]
Hello @ankitjoshi8518 Ankit, how are you?
Can you kindly share here the URL of the docs article you are talking about?
Thank you!

**Comment by ankitjoshi8518** [comment]
https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps

**Comment by get-itips** [comment]
You have to run that command in a command prompt shell

![image](https://user-images.githubusercontent.com/36666927/89328997-969a7500-d664-11ea-907e-dc4633503983.png)

Look at the formatting in the article

![image](https://user-images.githubusercontent.com/36666927/89329119-c3e72300-d664-11ea-99a9-7d6cf09ef60c.png)

Hope this helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ankitjoshi8518 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
