### ISSUE TITLE
Get-Team -User $null

### ISSUE THREAD

**Issue by evmc02** [MicrosoftDocs/office-docs-powershell#6235]
When running Get-Team, the -user parameter seems to take $null as a value without erroring...not sure if this is by design or not?

**Comment by get-itips** [comment]
Hello @evmc02 how are  you?
I could check that, when using $null as input for -User parameter, that behaves the same way as not using the -User parameter at all, this is probably intended by the Product Group, in case you want to propose another behavior, I need to kindly suggest sharing that idea to https://microsoftteams.uservoice.com/ where it can reach the team developing the module.
Many thanks sharing  your feedback,
Andrés

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @evmc02 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
