### ISSUE TITLE
Issue while setting the "EmailAddresses" value for an O365 group while authenticating with App only

### ISSUE THREAD

**Issue by AmaniSakr** [MicrosoftDocs/office-docs-powershell#6236]
I have an issue when i try to set the EmailAddresses value for a unified group while authenticating with app Id and certificate it throughs the following error

We failed to update the unified group. Please try again later.
    + CategoryInfo          : NotSpecified: (:) [Set-UnifiedGroup], TaskException
    + FullyQualifiedErrorId : [Server=DBAPR05MB7045,RequestId=766c42f5-10c0-49d6-8c03-92e9e01a4428,TimeStamp=7/28/2020 8:18 
   :54 AM] [FailureCategory=Cmdlet-TaskException] 9EBEDFD4,Microsoft.Exchange.Management.RecipientTasks.SetUnifiedGroup
    + PSComputerName        : outlook.office365.com

Ways to reproduce the issue:

**Connect to Exchange online with App ID and Certificate**
`$Session =Connect-ExchangeOnline -CertificateFilePath $Path -AppId $AppId -Organization $Organization -CertificatePassword $secPassword`

**Try to set the "EmailAddresses" value as following**

`Set-UnifiedGroup -Identity $GroupID -EmailAddresses:@{add="Test@domain.onmicrosoft.com"}`

**The following error will be through**

We failed to update the unified group. Please try again later.
    + CategoryInfo          : NotSpecified: (:) [Set-UnifiedGroup], TaskException
    + FullyQualifiedErrorId : [Server=DBAPR05MB7045,RequestId=d5a8b23d-fcca-4e0d-988e-714dabcadce1,TimeStamp=7/28/2020 8:26 
   :31 AM] [FailureCategory=Cmdlet-TaskException] 9EBEDFD4,Microsoft.Exchange.Management.RecipientTasks.SetUnifiedGroup
    + PSComputerName        : outlook.office365.com
---

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @AmaniSakr, thank you for your feedback.

For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @AmaniSakr Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by RoelVB** [comment]
@AmaniSakr Did you ever figure this out?
I'm experiencing the same with app authentication, but is works fine as user.

I'm pretty sure Microsoft blocks this call when you're authenticated as app, but cannot find any information about this anywhere.

**Comment by StevieBleeds** [comment]
I've been encountering the same issue. It's documented in the article below.

https://docs.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps

**Comment by chrisda** [comment]
I added a similar note at the top of the [CBA topic](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell):

> You can't use the procedures in this article to modify Microsoft 365 Groups ([Set-UnifiedGroup](../exchange-ps/exchange/Set-UnifiedGroup.md)). To use Microsoft Graph instead, see [Update grup](/graph/api/group-update).

**Comment by RoelVB** [comment]
@chrisda Through the Graph it's also impossible to update the EmailAddresses

**Comment by StevieBleeds** [comment]
I too have tried using Graph to do it and encountered the same challenge. The mail prop is read-only.
