### ISSUE TITLE
Parameter CertificatePassword missing

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/office-docs-powershell#6238]
I ran into an issue when connecting because Parameter CertificatePassword is missing!
You need to have a SecureString and pass this variable to cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by trudolf-msft** [comment]
![image](https://user-images.githubusercontent.com/43539433/88657472-46ef0300-d0d2-11ea-85b8-620cf8ba868c.png)

**Comment by dariomws** [comment]
Hi @trudolf-msft, thank you for your feedback.

-CertificatePassword parameter must be used if you are using a local certificate and it's documented in the article:
```powershell
Connect-ExchangeOnline -CertificateFilePath "C:\Users\johndoe\Desktop\automation-cert.pfx" -CertificatePassword (ConvertTo-SecureString -String "<My Password>" -AsPlainText -Force) -AppID "36ee4c6c-0812-40a2-b820-b22ebd02bce3" -Organization "contosoelectronics.onmicrosoft.com"
```

**Comment by dariomws** [comment]
@trudolf-msft I verified and the -CertificatePassword parameter was added yesterday to the article.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @trudolf-msft Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
