### ISSUE TITLE
* Recommended update to Teams PowerShell. Documentation is lacking.

### ISSUE THREAD

**Issue by ATXstables** [MicrosoftDocs/office-docs-powershell#6243]
regarding the link https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-release-notes

After reviewing and implementing the Set-TeamArchivedState it was unclear the documents were read only. However, there is another parameter with read only. 

#1) The documentation attempts to address the readonly for site members, but is not clear what happens when a site is archived and if it is visible to users.

#2) Setting the archived value to $false documentation could be improved by explaining what happens when the value is reverted to $true. e.g. when the archived site is set to $true, what other properties and methods are available? 

I realize these commandlets are new and ask for you to review.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b945cd2-8ea3-0d90-e168-7df26b1eebd9
* Version Independent ID: 84061af5-8d86-6ef5-0928-e7dcde75baae
* Content: [Set-TeamArchivedState (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/set-teamarchivedstate?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-TeamArchivedState.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-TeamArchivedState.md)
* Service: **teams-powershell**
* GitHub Login: @serdarsoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @ATXstables How are you?
I tested this to see if we need to change the documentation, first I ran

`Set-TeamArchivedState -GroupId 6ac9b942-b495-47d8-b963-89636cee56df -Archived:$true -SetSpoSiteReadOnlyForMembers:$true`

This, archived the Team and set the SharePoint site to Read Only only for members, for example the New and Upload buttons were not anymore present. IMHO the current description for SetSpoSiteReadOnlyForMembers fits.

I, then, ran
`Set-TeamArchivedState -GroupId 6ac9b942-b495-47d8-b963-89636cee56df -Archived:$false`

This, "unarchived" the Team and set the SharePoint site to a normal state, as expected.

I see also that the current description for the cmdlet explains what will be available once the team is archived

> This cmdlet is used to freeze all of the team activity, but Teams Administrators and team owners will still be able to add or remove members and update roles. 

Does this answers your inquiry?

Thank you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ATXstables Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
