### ISSUE TITLE
Parameter in Example 1 incorrect?

### ISSUE THREAD

**Issue by hrn111** [MicrosoftDocs/office-docs-powershell#6249]
I believe Example 1 on this support page is using an incorrect parameter.  
Example 1:  Get-MessageTrace **-MessageTraceId** 2bbad36aa4674c7ba82f4b307fff549f -SenderAddress john@contoso.com -StartDate 06/13/2018 -EndDate 06/15/2018 | Get-MessageTraceDetail

I believe it should be:  Get-MessageTrace **-MessageId** 2bbad36aa4674c7ba82f4b307fff549f -SenderAddress john@contoso.com -StartDate 06/13/2018 -EndDate 06/15/2018 | Get-MessageTraceDetail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f784c39-5041-578f-7d9f-5b38310cc89c
* Version Independent ID: 4ab7a6db-db36-c736-6ce5-2f0e74b0cf6a
* Content: [Get-MessageTraceDetail (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-messagetracedetail?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MessageTraceDetail.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MessageTraceDetail.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @hrn111, thank you for your feedback and help us to improve docs.microsoft.com.

If you are using also -SenderAddress I think the -MessageTraceId parameter is fine. Parameter description:
"The MessageTraceId parameter can be used with the recipient address to uniquely identify a message trace and obtain more details. A message trace ID is generated for every message that's processed by the system."

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @hrn111 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
