### ISSUE TITLE
Syntax error [winrm : Error: Invalid use of command line. Type "winrm -?" for help.]

### ISSUE THREAD

**Issue by arkayenro** [MicrosoftDocs/office-docs-powershell#6251]
same issue as #4884 just on a different page

winrm set winrm/config/client/auth @{Basic="true"}
should be...
winrm set winrm/config/client/auth '@{Basic="true"}'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@arkayenro, are you running the command from a Command Prompt (i.e., a DOS window) as described in the topic or from Windows PowerShell? PowerShell requires the quotes; a Command Prompt does not.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and updating the documentation with PR. @arkayenro Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
