### ISSUE TITLE
Connect-ExchangeOnline VisualStudio

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#6253]
> Module Version: 2..0.3-preview
> VisualStudio Code Version: 1.46.1
> VSCode PowerShell Module Version: v2020.6.0
> 

Running a command `Connect-ExchangeOnline -UserPrincipalName ( whoami /upn )` results in the error below:

![image](https://user-images.githubusercontent.com/5260172/88968953-cd653980-d2b8-11ea-8268-17231d9dc277.png)

`$Error[0] | select -ExpandProperty Exception`
 
> Message        : Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.. 
> TargetSite     : Microsoft.Exchange.Management.AdminApiProvider.Authentication.TokenInformation GetAccessToken()
> StackTrace     :    at Microsoft.Exchange.Management.AdminApiProvider.Authentication.UserTokenProvider.GetAccessToken()
>                     at Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession.ProcessRecord()
>                     at System.Management.Automation.CommandProcessor.ProcessRecord()
> Data           : {}
> InnerException : System.AggregateException: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral,
>                  PublicKeyToken=b77a5c561934e089'.)
>                   ---> System.TypeLoadException: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
>                     at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.CryptographyHelper.CreateSha256Hash(String input)
>                     at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.LogReturnedToken(AuthenticationResult result)
>                     at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.PostRunAsync(AuthenticationResult result)
>                     at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
>                     at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenCommonAsync(String resource, String clientId, Uri redirectUri, IPlatformParameters parameters,      
>                  UserIdentifier userId, String extraQueryParameters, String claims)
>                     at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(String resource, String clientId, Uri redirectUri, IPlatformParameters parameters,
>                  UserIdentifier userId)
>                     --- End of inner exception stack trace ---
>                     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>                     at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>                     at Microsoft.Exchange.Management.AdminApiProvider.Authentication.UserTokenProvider.GetAccessToken()
> HelpLink       :
> Source         : Microsoft.Exchange.Management.AdminApiProvider
> HResult        : -2146233088`

Module works just fine in the regular PowerShell

**Comment by tseward** [comment]
@YuriySamorodov Did you verify you're running PowerShell 3/4/5 and not Core?

https://code.visualstudio.com/docs/languages/powershell#_multiversion-support

**Comment by YuriySamorodov** [comment]
@tseward , indeed I was running PowerShell Core. Once I witched to PowerShell 5.1 I was able to connect.
Lots of thanks!
Feel free to close this case.

P.S. On a side note, do you happen to know if PowerShell Core support is going to be implemented anytime soon?

**Comment by tseward** [comment]
I don't know the timeline, but it is being worked on https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-and-maintain-the-exchange-online-powershell-v2-module.

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @YuriySamorodov Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
