### ISSUE TITLE
The example area for this command is empty

### ISSUE THREAD

**Issue by sparkf1** [MicrosoftDocs/office-docs-powershell#6254]
The example area for this command is empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34c44e10-c678-ca4a-2a37-25d733c7c103
* Version Independent ID: 5e931844-2def-11a9-fc57-eddb2216605b
* Content: [Test-CsInboundBlockedNumberPattern (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/test-csinboundblockednumberpattern?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Test-CsInboundBlockedNumberPattern.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Test-CsInboundBlockedNumberPattern.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for noticing and reporting @sparkf1
