### ISSUE TITLE
Declaring the policy types

### ISSUE THREAD

**Issue by jadesolis** [MicrosoftDocs/office-docs-powershell#6255]
Would be helpful if the policy type values could be shown, how they relate to the Teams Admin Center settings. 
For example _TeamsChannelsPolicy_ relate to the  "Teams policy" in TAC;  while _TeamsMeetingBroadcastPolicy_ is the "Teams live events policy"(?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f8afd4c-7828-e7e7-dddc-e14673396f39
* Version Independent ID: dabb388b-8614-4b69-4e0a-f0536ab2bab6
* Content: [New-CsGroupPolicyAssignment (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csgrouppolicyassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-CsGroupPolicyAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsGroupPolicyAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @jadesolis How are you?
Just wanted to let you know that I am handling this.

In advance:

TeamsAppSetupPolicy (App Setup Policy), TeamsCallingPolicy (Calling Policy), TeamsCallParkPolicy (Call Park Policy), TeamsChannelsPolicy (Teams Channel Policy), TeamsComplianceRecordingPolicy (Teams Recording Policy), TeamsEducationAssignmentsAppPolicy, TeamsMeetingBroadcastPolicy (Live Events Policy), TeamsMeetingPolicy (Meeting Policies), TeamsMessagingPolicy (Messaging Policies)
