### ISSUE TITLE
Not able to connect to O365 server using cmdlet 'Connect-ExchangeOnline' with proxy settings

### ISSUE THREAD

**Issue by prasadkpatil** [MicrosoftDocs/office-docs-powershell#6257]
Hello Team, 
I am trying to connect o365 server using Exchange EX0 V2 module below code -

```powershell
$username = '<name>@<domain>.onmicrosoft.com'
$password = '<password>'
$uri = 'https://outlook.office365.com/powershell-liveid/'

$secstr = New-Object -TypeName System.Security.SecureString
$password.ToCharArray() | ForEach-Object {$secstr.AppendChar($_)}
$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $username, $secstr

netsh winhttp set proxy 172.27.XXX.X:3128
$ProxyOptions = New-PSSessionOption -ProxyAccessType WinHttpConfig
Connect-ExchangeOnline -Credential $cred -PSSessionOption $ProxyOptions  
Disconnect-ExchangeOnline -Confirm:$false
````

I am getting following error -

```powershell
New-ExoPSSession : Object reference not set to an instance of an object.. 
At C:\Program 
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\1.0.1\ExchangeOnlineManagement.psm1:445 
char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Exchange.Management.ExoPowershellSnapin.NewEx 
   oPSSession
```

**I am able to connect with O365 using `New-PSSession`** using same credentails and same proxy settings. Here is code -
```powershell
$username = '<name>@<domain>.onmicrosoft.com'
$password = '<password>'
$uri = 'https://outlook.office365.com/powershell-liveid/'

$secstr = New-Object -TypeName System.Security.SecureString
$password.ToCharArray() | ForEach-Object {$secstr.AppendChar($_)}
$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $username, $secstr

netsh winhttp set proxy 172.27.XXX.X:3128
$ProxyOptions = New-PSSessionOption -ProxyAccessType WinHttpConfig
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri $uri -Authentication Basic -AllowRedirection -Credential $cred -SessionOption $ProxyOptions -ErrorAction Stop  
$temp=Import-PSSession $session -AllowClobber -CommandName Get-User,Get-Mailbox,ConvertFrom-Json -FormatTypeName *  
Remove-PSSession -Id $Session.Id 
````

And let me know if you required more information.

**Comment by prasadkpatil** [comment]
I set the proxy in Settings. Then imported proxy in PS script.  I am able to connect with O365 server.

```PowerShell
$ProxyOptions = New-PSSessionOption -ProxyAccessType IEConfig
Connect-ExchangeOnline -Credential $cred -PSSessionOption $ProxyOptions
```
In our current environment, we don't want to configure proxy at System level.
Waiting for your reply.

**Comment by dariomws** [comment]
Hi @prasadkpatil, thank you for your feedback.

For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

To give you some help in advance, the first example works for me:
![image](https://user-images.githubusercontent.com/33589238/89299355-e82f0980-d63c-11ea-8701-546b1d6e816f.png)

Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @prasadkpatil Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
