### ISSUE TITLE
Isn't it time this page mentioned Teams?

### ISSUE THREAD

**Issue by Coldry** [MicrosoftDocs/office-docs-powershell#6263]
The introduction of Teams and the steady migration of Skype service into Teams has been in play for some time now. The Set-CSUser command and others in it's set work for Teams as well as Skype but this page still only mentions Skype. That leaves us Teams Telephony adinistrators a little in the dark as to whether we're meant to be using these commands to administer Teams.

Or am I looking in the wrong place?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04a4a893-ff38-930b-20e5-31231b1859a7
* Version Independent ID: 53c97d7c-8c81-5387-011c-2aa97d64fe4e
* Content: [Get-CsUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by get-itips** [comment]
Hello @Coldry 
How are you?
Thanks for your feedback, please see [this comment](https://github.com/MicrosoftDocs/office-docs-powershell/issues/5405#issuecomment-624118384)
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Coldry Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
