### ISSUE TITLE
Powershell examples incorrect

### ISSUE THREAD

**Issue by KerryWilliamsMS** [MicrosoftDocs/office-docs-powershell#6270]
The page is for the cmdlet Get-PnPMicrosoft365Group but the examples show Get-Microsoft365Group
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpmicrosoft365group?view=sharepoint-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc6a450-2594-9b37-5b28-968a71eeb9d9
* Version Independent ID: 708b2e85-d65d-58f2-4c33-d168c45035cb
* Content: [Get-PnPMicrosoft365Group (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpmicrosoft365group?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPMicrosoft365Group.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPMicrosoft365Group.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @KerryWilliamsMS how are you?
Thanks for reporting.

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @KerryWilliamsMS Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
