### ISSUE TITLE
Problem with Delegated Access Permissions (DAP) partners

### ISSUE THREAD

**Issue by Staffanb88** [MicrosoftDocs/office-docs-powershell#6271]
I try to follow this guide and connect to tenent. https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-exchange-online-tenants-with-remote-windows-powershell-for-delegated?source=docs

Connection works good, but I can´t change anything because I got this error 

The user "************.onmicrosoft.com\"***My UPN address***" isn't assigned to any management roles.

**Comment by chrisda** [comment]
@Staffanb88, although the procedures for DAP partners are not documented yet, you can use the [EXO V2 module](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2), with the addition (I think) of adding the _DelegatedOrganization_ parameter and value.

Another thing to consider: the error might be describing the problem. Is your account a member of any Exchange Online [role groups](https://docs.microsoft.com/Exchange/permissions-exo/permissions-exo) (hence, will be assigned management roles) in the tenant? Organization Management is the big one that gives you god-like powers, but it can literally be any admin role group.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @Staffanb88 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by chrisda** [comment]
@Staffanb88, as you can now see, I've retired the DAP connection instructions you referenced in this issue, and the DAP instructions now redirect to <https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell>. Please try the instructions out, and report any issues back here. Thanks.
