### ISSUE TITLE
Possible error with date parameters?

### ISSUE THREAD

**Issue by bnp-nz** [MicrosoftDocs/office-docs-powershell#6279]
Hi,

I was trying to get details on a bunch of messages where MessageIDs were contained in a file. This didn't work (returned no results):

foreach($line in Get-Content .\MessageIDs.txt) {
Get-MessageTrace -MessageId $line }

this, however, worked:

foreach($line in Get-Content .\MessageIDs.txt) {
>> Get-MessageTrace -MessageId $line -StartDate 07/26/2020 -EndDate 07/28/2020 }

does this mean that this piece of documentation:

"You can use this cmdlet to search message data for the last 10 days. If you run this cmdlet without any parameters, only data from the last 48 hours is returned."

actually should be "...without any _date_ parameters..." ??

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e172c6ca-3f84-1839-4cff-29c68dbe32a9
* Version Independent ID: 50c55aeb-0311-ac5a-7468-b276835f6b67
* Content: [Get-MessageTrace (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-messagetrace?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MessageTrace.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MessageTrace.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @bnp-nz, thank you for your feedback.

That sentence is correct, you can run this cmdlet without any parameter, and all the messages from the last 48 hours will be returned. (max. of 1000000 results)

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @bnp-nz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by bnp-nz** [comment]
OK, thanks guys. Scratching my head as to why my initial command didn't work and why date parameters were required given that it was within 10 days (so therefore Get-HistoricalSearch wasn't required). I was also querying for specific MessageId so the query couldn't have returned a large number of results. I guess I'll play around with this and see if I can replicate the behaviour or come up with some pattern to explain my results.
