### ISSUE TITLE
Token Information

### ISSUE THREAD

**Issue by KFlipDev** [MicrosoftDocs/office-docs-powershell#6280]
Hello, the documentation says to get token via ADAL PowerShell. After reviewing the ADAL Module from here: https://www.powershellgallery.com/packages/ADAL.PS/5.2.7.2/Content/Get-AdalToken.ps1

We are unsure of how to retrieve a token as we do not know which Exchange endpoint to use for the scope.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#setup-app-only-authentication)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @KFlipDev, thank you for your feedback and help us to improve docs.microsoft.com.

"Connect using an existing service principal" section was removed 5 days ago. More information:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/6171
https://github.com/MicrosoftDocs/office-docs-powershell/pull/6281

I think you're talking about that section. Not supported yet.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @KFlipDev Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
