### ISSUE TITLE
TeamChannelUser CmdLets not available in 1.1.4

### ISSUE THREAD

**Issue by blindzero** [MicrosoftDocs/office-docs-powershell#6283]
Hi,
starting MicrosoftTeams version 1.0.18 or better should support TeamChannelUser cmdlets.
I have 1.1.4 installed and CmdLets are not available.

```
ModuleType Name                            Version
---------- ----                            -------
    Script Connect-MS365                   1.3.0
  Manifest Microsoft.PowerShell.Management 3.1.0.0
  Manifest Microsoft.PowerShell.Utility    3.1.0.0
    Binary MicrosoftTeams                  1.1.4
    Script PackageManagement               1.4.6
    Script posh-git                        0.7.3
    Script PowerShellGet                   1.0.0.1
    Script profile                         0.0
    Script PSReadline                      2.0.0
```

```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-CsBatchPolicyAssignmentOperation               1.1.4      MicrosoftTeams
Function        Get-CsGroupPolicyAssignment                        1.1.4      MicrosoftTeams
Function        Get-CsUserPolicyAssignment                         1.1.4      MicrosoftTeams
Function        New-CsBatchPolicyAssignmentOperation               1.1.4      MicrosoftTeams
Function        New-CsGroupPolicyAssignment                        1.1.4      MicrosoftTeams
Function        Remove-CsGroupPolicyAssignment                     1.1.4      MicrosoftTeams
Cmdlet          Add-TeamUser                                       1.1.4      MicrosoftTeams
Cmdlet          Connect-MicrosoftTeams                             1.1.4      MicrosoftTeams
Cmdlet          Disconnect-MicrosoftTeams                          1.1.4      MicrosoftTeams
Cmdlet          Get-CsPolicyPackage                                1.1.4      MicrosoftTeams
Cmdlet          Get-CsUserPolicyPackage                            1.1.4      MicrosoftTeams
Cmdlet          Get-CsUserPolicyPackageRecommendation              1.1.4      MicrosoftTeams
Cmdlet          Get-Team                                           1.1.4      MicrosoftTeams
Cmdlet          Get-TeamChannel                                    1.1.4      MicrosoftTeams
Cmdlet          Get-TeamsApp                                       1.1.4      MicrosoftTeams
Cmdlet          Get-TeamUser                                       1.1.4      MicrosoftTeams
Cmdlet          Grant-CsUserPolicyPackage                          1.1.4      MicrosoftTeams
Cmdlet          New-CsBatchPolicyPackageAssignmentOperation        1.1.4      MicrosoftTeams
Cmdlet          New-Team                                           1.1.4      MicrosoftTeams
Cmdlet          New-TeamChannel                                    1.1.4      MicrosoftTeams
Cmdlet          New-TeamsApp                                       1.1.4      MicrosoftTeams
Cmdlet          Remove-Team                                        1.1.4      MicrosoftTeams
Cmdlet          Remove-TeamChannel                                 1.1.4      MicrosoftTeams
Cmdlet          Remove-TeamsApp                                    1.1.4      MicrosoftTeams
Cmdlet          Remove-TeamUser                                    1.1.4      MicrosoftTeams
Cmdlet          Set-Team                                           1.1.4      MicrosoftTeams
Cmdlet          Set-TeamArchivedState                              1.1.4      MicrosoftTeams
Cmdlet          Set-TeamChannel                                    1.1.4      MicrosoftTeams
Cmdlet          Set-TeamPicture                                    1.1.4      MicrosoftTeams
Cmdlet          Set-TeamsApp                                       1.1.4      MicrosoftTeams
```

Anything special to get those?

Best & Thanks,
M.

**Comment by get-itips** [comment]
Hello @blindzero how are you?
You can see here that [those cmdlets](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes) belong to the Preview version of the module. (Currently, it is named 1.1.3-preview)
Hope this information helps you,

**Comment by blindzero** [comment]
@get-itips Thanks for that Link. Can somebody update this documentation https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps? It doesnt tell anything about this

**Comment by get-itips** [comment]
> @get-itips Thanks for that Link. Can somebody update this documentation https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps? It doesnt tell anything about this

Hello @blindzero how are you? There is a _Important note_ in that article that refers to the beta module, however I will try to improve it to make it clearer. Thanks

**Comment by claytonwalker** [comment]
Even with the note, it's not clear. Please add a specific version number or something like that. It would seem obvious that if the 1.1.3-preview includes a feature that the 1.1.4 GA release would also include it, but it doesn't. Googling the cmdlet name shows this has been in preview since at least 1.0.21 - what's going on?

install-module MicrosoftTeams -AllowPrerelease which is what's in the linked install instructions also doesn't solve the issue since the preview version is older than the latest GA release. I had to uninstall and use install-module MicrosoftTeams -RequiredVersion 1.1.3-preview -AllowPrerelease

**Comment by get-itips** [comment]
> Even with the note, it's not clear. Please add a specific version number or something like that. It would seem obvious that if the 1.1.3-preview includes a feature that the 1.1.4 GA release would also include it, but it doesn't. Googling the cmdlet name shows this has been in preview since at least 1.0.21 - what's going on?
> 
> install-module MicrosoftTeams -AllowPrerelease which is what's in the linked install instructions also doesn't solve the issue since the preview version is older than the latest GA release. I had to uninstall and use install-module MicrosoftTeams -RequiredVersion 1.1.3-preview -AllowPrerelease

Hello @claytonwalker I reported that recently to the team, I will propose to specify the RequiredVersion in the article and see if it gets merged, thank you
