### ISSUE TITLE
Example 2 not working

### ISSUE THREAD

**Issue by ParaGlideRocks** [MicrosoftDocs/office-docs-powershell#6284]
Example 2 is not working:

New-CsOnlineLisLocation -Location "Office 202, 2nd Floor" -CompanyName "Contoso" -HouseNumber 3910 -StreetName 163rd -StreetSuffix St -City Bellevue -StateOrProvince WA -CountryOrRegion US -PostalCode 98004 -Description "New civic address location" -Elin TEST_ELIN
**Object reference not set to an instance of an object.**
    + CategoryInfo          : NotSpecified: (:) [New-CsOnlineLisLocation], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Rtc.Management.Hosted.Lis.NewCsOnlineLisLocation
   Cmdlet
    + PSComputerName        : admined4.online.lync.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84b326a5-01d9-db88-b925-43e7259f26e4
* Version Independent ID: 3483eb1d-6fb6-a4de-45b2-24d6ba7ac5e8
* Content: [New-CsOnlineLisLocation (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinelislocation?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineLisLocation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineLisLocation.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @junya
* Microsoft Alias: **junya**

**Comment by get-itips** [comment]
Hello @kaishuipinggai Jundong how are you? I could verify that the 2nd example throws that error as @ParaGlideRocks says could this be due to the validation status?
This can be overcome by first creating the civic address using New-CsOnlineLisCivicAddress as the first example implies.

**Comment by ParaGlideRocks** [comment]
3w222e2222eesw22www2www22ezs

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by kaishuipinggai** [comment]
It needs to add the "CivicAddressId" parameter to pass the civic address id. I will update in the doc.

**Comment by get-itips** [comment]
> It needs to add the "CivicAddressId" parameter to pass the civic address id. I will update in the doc.

Thanks @kaishuipinggai Jundong, please link to this issue when creating the PR. Appreciate.

**Comment by kaishuipinggai** [comment]
@get-itips Sure will do. Thanks!

**Comment by kaishuipinggai** [comment]
After the discussion with team members we found a bug in our code and we are currently working on fixing it...So right now example 2 is not working, and customer will receive the error when they follow example 2. They might still be able to follow example 1. It won't affect the actually civic address / location creation and management functionalities.

I will keep you posted if the fix is checked in.

**Comment by get-itips** [comment]
> After the discussion with team members we found a bug in our code and we are currently working on fixing it...So right now example 2 is not working, and customer will receive the error when they follow example 2. They might still be able to follow example 1. It won't affect the actually civic address / location creation and management functionalities.
> 
> I will keep you posted if the fix is checked in.

@kaishuipinggai Jundong, can you give us the current status ? So I can now if a change is needed to the article or we can close this issue. Thanks

**Comment by get-itips** [comment]
Hello @kaishuipinggai Jundong, I tested and Example 2 is still throwing errors, can you update me ? Thank you!

**Comment by kaishuipinggai** [comment]
@get-itips Thanks for the followup. The fix is checked in yesterday. It should be ready in next week.

**Comment by get-itips** [comment]
Many thanks for the update @kaishuipinggai

**Comment by yogkumgit** [comment]
@get-itips and  @kaishuipinggai Thank you very much for the contribution and updating the documentation. @ParaGlideRocks 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ParaGlideRocks** [comment]
Hi all, I've just tried and it's not working yet. Can I ask which changes to the documentation?

**Comment by get-itips** [comment]
> Hi all, I've just tried and it's not working yet. Can I ask which changes to the documentation?

I've just ran the 2nd example and worked without issues.
