### ISSUE TITLE
How can we disable sharing entirely (for internal and external user) on OneDrive for business?

### ISSUE THREAD

**Issue by anomepani** [MicrosoftDocs/office-docs-powershell#6289]
we want to implement in my organization like disable internal/external sharing completely so that user can only use onedrive as data storage container without sharing feature at all.
microsoft's one drive team could work on this to make sharing disable option for INTERNAL and EXTERNAL.

For a bank and we need to manage any sharing. This is not a 'feature' that we can have for all our users
For healthcare industry we don't want to share confidential data shared using onderive in organization?

Is there a way to disable entire sharing in onedrive for business?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428a5954-392c-f7ad-bac4-553adf74e08e
* Version Independent ID: 44fdecf2-1977-3171-9d04-02c0fefb16c9
* Content: [Set-SPOTenant (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @anomepani how are you?
The sharing settings available are the ones that appear here https://admin.onedrive.com/?v=SharingSettings
I do not think you can disable internal sharing completely for example, as that is one of the uses of OneDrive, however you can suggest your idea here https://onedrive.uservoice.com/ where it will reach the product group.
Hope this information helps you,

**Comment by anomepani** [comment]
Thanks for your reply. I will suggest the idea in the user voice.

**Comment by yogkumgit** [comment]
@anomepani  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
