### ISSUE TITLE
Can not excute Set-UnifiedGroup with  App-only authentication 

### ISSUE THREAD

**Issue by cuicheng11165** [MicrosoftDocs/office-docs-powershell#6293]
PS C:\windows\system32> Connect-ExchangeOnline -CertificateThumbPrint "" -AppID "" -Organization ""

PS C:\windows\system32> Set-UnifiedGroup -Identity group2221@baron.space -AutoSubscribeNewMembers:$false
Active Directory operation failed on DM6PR01A05DC005.NAMPR01A005.prod.outlook.com. This error is not retriable.
Additional information: Insufficient access rights to perform the operation.
Active directory response: 00002098: SecErr: DSID-03150F94, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0
    + CategoryInfo          : NotSpecified: (:) [Set-UnifiedGroup], ADOperationException
    + FullyQualifiedErrorId : [Server=SL2PR03MB4539,RequestId=2dc2ddf5-5c7e-4a49-8993-a89a06f47264,TimeStamp=8/8/2020
   6:46:23 AM] [FailureCategory=Cmdlet-ADOperationException] 276E34A1,Microsoft.Exchange.Management.RecipientTasks.Se
  tUnifiedGroup
    + PSComputerName        : outlook.office365.com

PS C:\windows\system32> Set-UnifiedGroup -Identity group2221@baron.space -DisplayName "aaaaa"
Failed to retrieve executing user. Please try again later.
    + CategoryInfo          : NotSpecified: (:) [Set-UnifiedGroup], RecipientTaskException
    + FullyQualifiedErrorId : [Server=SL2PR03MB4539,RequestId=ab94f925-66c2-40bc-b089-c66baeccba7c,TimeStamp=8/8/2020
   6:47:12 AM] [FailureCategory=Cmdlet-RecipientTaskException] CAA7D44A,Microsoft.Exchange.Management.RecipientTasks.
  SetUnifiedGroup
    + PSComputerName        : outlook.office365.com

**Comment by dariomws** [comment]
Hello @cuicheng11165, thank you for your feedback.

For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @cuicheng11165 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
