### ISSUE TITLE
"The password entered exceeds the maximum length of '256'" error when using token authentication

### ISSUE THREAD

**Issue by LoungeFlyZ** [MicrosoftDocs/office-docs-powershell#6295]
When using an OAuth token for authentication i get the following error:

`An exception of type 'System.Management.Automation.RuntimeException' occurred in System.Management.Automation.dll but was not handled in user code: 'AADSTS50052: The password entered exceeds the maximum length of '256'. Please reach out to your admin to reset the password.`

**Repro**
_Note: you will need to register an AAD app and consent using an admin account. Per: https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps except instead of a certificate creating a secret._ 

```
if(!(Get-Package adal.ps)) { Install-Package -Name adal.ps }

$tenantId = "<TENANT ID>" 
$authority = "https://login.microsoftonline.com/$tenantId/"
$resourceUrl = "https://outlook.office365.com"

$clientId = "<APP ID>" 
$secret = "<SECRET>"

$clientSecret = ConvertTo-SecureString $secret -AsPlainText -Force
$response = Get-ADALToken -Resource $resourceUrl -ClientId $clientId -ClientSecret $clientSecret  -Authority $authority -TenantId $tenantId
$accessToken = $response.AccessToken
$secureAccessToken = ConvertTo-SecureString $accessToken -AsPlainText -Force

$AppCredential= New-Object System.Management.Automation.PSCredential("<UPN HERE>", $secureAccessToken)

Connect-ExchangeOnline -Credential $AppCredential

Get-EXOMailbox -ResultSize 10
```

When calling the Connect-ExchangeOnline command the error occurs.

**Comment by dariomws** [comment]
Hi @LoungeFlyZ, thank you for your feedback.

Same issue:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/6171

Connect using an existing service principal and client-secret is not supported yet. It was removed from the article 5 days ago. My apologies for any inconvenience.

**Comment by LoungeFlyZ** [comment]
@dariomws thanks for the heads up.  That is disappointing. We are currently blocked as there is no way to authenticate using the v2 commands from .net core.  Using the certificate method of authentication is also failing, see: https://github.com/MicrosoftDocs/office-docs-powershell/issues/6296

**Comment by dariomws** [comment]
For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

You can also provide feedback about this module either on the [blog](https://techcommunity.microsoft.com/t5/exchange-team-blog/modern-auth-and-unattended-scripts-in-exchange-online-powershell/ba-p/1497387) or in the Office 365 Admin/Exchange Admin [UserVoice forum](https://office365.uservoice.com/forums/273493-office-365-admin?category_id=96338).

**Comment by LoungeFlyZ** [comment]
@dariomws like i mentioned in the other issue.  Support will likely be a deadend and not worth the investment. 

i'll post links to these issues in the blog post.

**Comment by dariomws** [comment]
I replied to you in the other issue. Thanks!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @LoungeFlyZ Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by LoungeFlyZ** [comment]
@yogkumgit honestly, its not that helpful.  having a place to report bugs and issues about the powershell commands themselves would be helpful.  Just having this repo being about docs is good, but i am sure others are also looking for a place to report issues.  Doing that on a blog post is pretty bad IMHO.

**Comment by yogkumgit** [comment]
@LoungeFlyZ I agree with you. Currently, here we are helping only documentation update. Apologies, proceed to close it.

**Comment by dariomws** [comment]
@LoungeFlyZ When the Exchange Online PowerShell V2 module was in Preview, if you have any feedback, concerns, or are facing any issues, you could contact PG at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).
It's another option for you.

**Comment by GalRabin** [comment]
@dariomws 
@yogkumgit 
Any updates here?
It's really painful for our customer, Due to the fact that Microsoft planning to deprecate basic auth soon and we implement an unattended script.

**Comment by dariomws** [comment]
@GalRabin sorry but I don't have updates. Anyway, the correct place to get the latest updates about the EXO PowerShell module is the [Exchange Team Blog](https://techcommunity.microsoft.com/t5/exchange-team-blog/bg-p/Exchange).
