### ISSUE TITLE
Could not load type 'System.Security.Cryptography.SHA256Cng' when calling Connect-ExchangeOnline from netcore 3.1 

### ISSUE THREAD

**Issue by LoungeFlyZ** [MicrosoftDocs/office-docs-powershell#6296]
When calling the Connect-ExchangeOnline command from a dotnet core 3.1 project the following error occurs:

`'Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.. '`

**Repro**
_Note: You need to follow setting up an AAD App per https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps_

```
var clientId = "<APP ID>";
Runspace runspace = System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace();
runspace.Open();

using (PowerShell powershell = PowerShell.Create(runspace))
{
        var certPassword = "<CERT PASSWORD>";
        SecureString certPwd = new SecureString();
        foreach (char c in certPassword) { 
             certPwd.AppendChar(c);
        }

        var cmd = new PSCommand();
        cmd.AddCommand("Connect-ExchangeOnline");
        cmd.AddParameter("CertificateFilePath", @"MyCompanyName.pfx");
        cmd.AddParameter("CertificatePassword", certPwd);
        cmd.AddParameter("Organization", "<TENANT NAME e.g. contoso.onmicrosoft.com");
        cmd.AddParameter("AppId", clientId);

        powershell.Commands = cmd;
        var result = powershell.Invoke();
            
        if (powershell.Streams.Error.Count > 0 || result.Count != 1)
        { 
               throw new Exception("Fail to establish the connection"); 
        }
}
```

**Comment by LoungeFlyZ** [comment]
Possibly related:  https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1258

**Comment by dariomws** [comment]
Hi @LoungeFlyZ, thank you for your feedback.

For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

You can also provide feedback about this module either on the [blog](https://techcommunity.microsoft.com/t5/exchange-team-blog/modern-auth-and-unattended-scripts-in-exchange-online-powershell/ba-p/1497387) or in the Office 365 Admin/Exchange Admin [UserVoice forum](https://office365.uservoice.com/forums/273493-office-365-admin?category_id=96338).

**Comment by LoungeFlyZ** [comment]
@dariomws i'm not sure opening a support ticket will have any impact in this case. The v2 commands are in preview and likely not supported by the support team.  It would be a lot of work and back and forth for little to no progress i suspect.  

It seems odd that there isn't a place to report bugs, issues to the team who are building these modules.  This repo seems like a great place to do that.  

Perhaps @yogkumgit could manage reporting the bugs/issues reported to the team?

As modern auth is demanded more and more there will likely be a lot more people reporting issues/bugs here in the absence of another better location.

**Comment by dariomws** [comment]
@LoungeFlyZ It's true, my mistake, to report issues about the EXO V2 module the best place would be a support ticket. In this case, because it's related to the preview version, I think the best place to report this kind of feedback is:
https://techcommunity.microsoft.com/t5/exchange-team-blog/modern-auth-and-unattended-scripts-in-exchange-online-powershell/ba-p/1497387

I'll forward this information but I'm not able to provide you more support with this issue. Hope you understand.

I appreciate and encourage you to do the same in the future also if you think there are documentation issues or improvements.

Thank you again!

**Comment by dariomws** [comment]
Oh, I see that you left a comment on the blog some minutes ago. Thanks!

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @LoungeFlyZ Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
