### ISSUE TITLE
OrganizerOnly option is missing from AutoAdmittedUsers

### ISSUE THREAD

**Issue by abenzim** [MicrosoftDocs/office-docs-powershell#6298]
AutoAdmittedUsers should has the option to choose OrganizerOnly but it missing in the documantation.
Already available in SFBO PS session.
![image](https://user-images.githubusercontent.com/56136413/89732043-90d1d480-da54-11ea-8be1-caf7db7f3516.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18b9baa8-da13-a24f-af31-91d63de13f08
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for reporting @abenzim
