### ISSUE TITLE
Import-PnPTermGroupFromXml : Access denied. You do not have permission to perform this action or access this resource.

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/office-docs-powershell#6299]
Using XML file created with "Export-PnPTermGroupToXml" and xmlns:pnp="http://schemas.dev.office.com/PnP/2020/02/ProvisioningSchema 
I am a global admin and a Term Store Administrator but I keep getting error:
Import-PnPTermGroupFromXml : Access denied. You do not have permission to perform this action or access this resource.

Is there some extra instruction I did not see?
Thanks for the help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2234c93-be32-5af0-8f84-d7011588f3ac
* Version Independent ID: 470a21a4-8354-cff1-b59a-cd82742f47ba
* Content: [Import-PnPTermGroupFromXml (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/import-pnptermgroupfromxml?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Import-PnPTermGroupFromXml.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Import-PnPTermGroupFromXml.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by limcysam** [comment]
I am getting a similar issue too. Is there a resolution for this issue?

**Comment by get-itips** [comment]
Hello @Ofer-Gal How are you? 

Thanks for your feedback.
Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, a member of the PnP community will handle your request.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Ofer-Gal Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
