### ISSUE TITLE
Get-MailDetailAtpReport - Limited to 10,000 results

### ISSUE THREAD

**Issue by sayertherebel** [MicrosoftDocs/office-docs-powershell#6307]
Hello - It seems that Get-MailDetailAtpReport command of the Exchange Online V2 PowerShell module is limited to returning 10,000 results - Or perhaps the underlying webservice is? I cannot find any reference to this limitation in the docs or anywhere else online.

Regardless of the result page size set, attempting to go beyond 10,000 results in the message 'We cannot currently process your request, please wait a few minutes and try again."

I've tried this against two tenancies with the same issue.

E.g. 

![image](https://user-images.githubusercontent.com/14993566/89879306-a7923b80-dbba-11ea-98cf-e70120c42e74.png)

**Comment by dariomws** [comment]
Hi @sayertherebel, thank you for your feedback and help us to improve docs.microsoft.com.

I think that maybe you are misinterpreting Pagesize and Page parameters. If all of your messages fit on one page (due to a specific PageSize value, or the default value of 1000), the Page parameter is rather useless (there will be only one page). The smaller the PageSize value, the more likely you are to have multiple pages.
Maybe in your case, you have more than 5000 messages but less than 10000. You can check it running:
$result=Get-MailDetailAtpReport -PageSize 5000 -Page 2
$result.count
Or:
Get-MailDetailAtpReport -PageSize 5000 -Page 2 | Measure-Object

**Comment by dariomws** [comment]
More information:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/918
https://docs.microsoft.com/powershell/module/exchange/get-quarantinemessage#examples

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @sayertherebel Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by sayertherebel** [comment]
Thanks for the feedback, but I understand the relationship between page and pagesize -  As I indicated I have performed tests that show the page size is not the issue and I was just using 5000 as the quickest example to recreate what I'm seeing - there seems to be a hard limit on results returned at 10,000 being enforced, probably by the underlying web service, that is undocumented as far as I can tell. I have tried this with - now - three distinct tenancies, in each case you are unable to go beyond 10,000 results. Since the maximum page number is 1000, 20 is around the smallest practical page size you can utilise to test this, but in each tenancy I try I cannot go beyond page 500 (500x20=10,000). The customer is hitting this apparent limit before being able to retrieve all records for a given time window (e.g. there should be more than 10,000 records.)

![image](https://user-images.githubusercontent.com/14993566/90419692-d888d980-e0ae-11ea-9f8d-025cfe69433e.png)

If this is the case, I can look at working around it by adopting the script they've sourced to use a smaller, sliding time window.

Thanks

**Comment by dariomws** [comment]
Thanks for this information @sayertherebel, I'll try to get more information to check if this limit actually exists.
