### ISSUE TITLE
Link is not working in the article.

### ISSUE THREAD

**Issue by SanguptaMSFT** [MicrosoftDocs/office-docs-powershell#6316]
https://www.poshtestgallery.com/packages/MicrosoftTeams. 
the link which is mentioned in the article is not working and needs to be reviewed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b48c32-ad79-4249-638b-f53f9d76397f
* Version Independent ID: 36d9cfe0-cf60-2fa1-41b4-6c6971042394
* Content: [Get-TeamChannel (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&source=docs)
* Content Source: [teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @serdarsoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @SanguptaMSFT Thanks for noticing, I will remove the note including the link as [now the cmdlet is GA](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes), so it is not needed. Thanks
