### ISSUE TITLE
New-Mailbox -UserPrincipalName confmbx@contoso.com - A parameter cannot be found that matches parameter name '–UserPrincipalName'.

### ISSUE THREAD

**Issue by igor-shubin** [MicrosoftDocs/office-docs-powershell#6317]
When I try to run **New-Mailbox** command for **Exchange Online**, I get an error:
`A parameter cannot be found that matches parameter name '–UserPrincipalName'`

Is the parameter `UserPrincipalName `not longer valid? If so, should it be removed from the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaa52ae8-3d22-c045-d8f1-ef0ab8dca365
* Version Independent ID: 0dcef152-ab12-c711-742d-5d4e570ea075
* Content: [New-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-mailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/New-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@igor-shubin, the error that's presented when you try to create a new mailbox in Exchange Online by just typing `New-Mailbox` and stepping through the prompts mentions UserPrincipalName, but that's incorrect; the UserPrincipalName parameter is on-premises only (and is described as on-prem only in the topic).

```powershell
New-Mailbox
WARNING: A script or application on the remote computer OUTLOOK.OFFICE365.COM is sending a prompt request. When you are
 prompted, enter sensitive information, such as credentials or passwords, only if you trust the remote computer and the
 application or script that is requesting the data.

cmdlet New-Mailbox at command pipeline position 1
Supply values for the following parameters:
Name: Donald Trump
Password: *******
Cannot process command because of one or more missing mandatory parameters: UserPrincipalName.
```

The equivalent parameter to use in Exchange Online PowerShell is **MicrosoftOnlineServicesId**.

I just confirmed the minimally correct syntax to create a new mailbox in Exchange Online PowerShell is:

```powershell
New-Mailbox -Name "Donald Trump" -Password (ConvertTo-SecureString -String "P@s$w0rd1" -AsPlainText -Force) -MicrosoftOnlineServicesID dtrump@contoso.onmicrosoft.com
```

As the resulting warning states, you have 30 days to license the mailbox in the Microsoft 365 admin center or Azure AD PowerShell.

**Comment by igor-shubin** [comment]
@chrisda I'm sorry for my inattention . Thank you for the explanation.
