### ISSUE TITLE
Import-PSSession $Session -DisableNameChecking

### ISSUE THREAD

**Issue by JustineNicole2020** [MicrosoftDocs/office-docs-powershell#6319]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell with Basic authentication](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @JustineNicole2020, thank you for your feedback.

Please provide more detail about the issue, here we are limited to documentation issues and improvements. If you find something to improve in this article please let us know.

Also, I recommend that you use the new Exchange Online PowerShell module to connecto Exchange Online:
https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @JustineNicole2020 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
