### ISSUE TITLE
Still no support for Private Channels with New-TeamChannel cmdlet

### ISSUE THREAD

**Issue by Muxxx** [MicrosoftDocs/office-docs-powershell#6320]
Can we please get an update on this, as it's now August 2020 and the last update was from January for PowerShell public support. The current version (1.1.4) still doesn't include this support. Any updates would be great.

**Comment by get-itips** [comment]
Hello @Muxxx Stefano, how are you?
Here we handle documentation issues only, I could verify that `MembershipType` _parameter_ is present in the Public Preview version of the module (currently 1.1.3-preview) and not in the GA, maybe you want to explore it.
More information 

https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes

https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install

Hope this helps you,

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @Muxxx Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
