### ISSUE TITLE
Support for MFA?

### ISSUE THREAD

**Issue by stoff75** [MicrosoftDocs/office-docs-powershell#6321]
This cmdlet doesn't appear to have support for MFA? No matter which Skype module I use I can't get the credential to work when I have MFA enabled. So the only way for me to move my users from on-prem to online is by disabling MFA - **on an admin account** ? Regards // Kristoffer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c68752-3b36-518f-8cf1-7a4e2aa8cf15
* Version Independent ID: 98b9a798-e232-0b2c-ee0f-857071885c1d
* Content: [Move-CsUser (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Move-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Move-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by get-itips** [comment]
Hello @stoff75 Kristoffer how are you?

Have you already tried this?

> If the administrator account is MFA (Multi-Factor Authentication) enabled, do not specify the -Credential parameter. The administrator will be prompted for credentials.

Source: https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-from-on-premises-to-skype-for-business-online

Does it work for you that way?

**Comment by stoff75** [comment]
Hello @get-itips ,
I have tried that, without specifying credentials (even when establishing a ps-session with Skype Online Connector beforehand) I get the error "_Move-CsUser : Unable to locate Windows Live ID token from the provided credentials, or from Active Directory Federation Services (AD FS) credentials cache._", so that's not working either :( And this admin user is a Cloud only user.

**Comment by get-itips** [comment]
> Hello @get-itips ,
> I have tried that, without specifying credentials (even when establishing a ps-session with Skype Online Connector beforehand) I get the error "_Move-CsUser : Unable to locate Windows Live ID token from the provided credentials, or from Active Directory Federation Services (AD FS) credentials cache._", so that's not working either :( And this admin user is a Cloud only user.

I see, thanks for the feedback, will try to get information from the team in case we need to adjust the documentation to state this.

**Comment by get-itips** [comment]
@hirenshah1 Hiren, can you help me confirming this cmdlet does not supports MFA? Thank you, I appreciate.

**Comment by yogkumgit** [comment]
@hirenshah1 awaiting your response, please help. Thanks

**Comment by hirenshah1** [comment]
@stoff75 you have mentioned that admin is cloud only user. So it is not clear if the user has required admin rights for on premise also. Can you please check if all the required admin rights are enabled as per - 

https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/move-users-between-on-premises-and-cloud#prerequisites



Required administrative credentials
To move users between on premises and the cloud, you must use an account with sufficient privileges in both the on-premises Skype for Business Server environment as well as in the Microsoft 365 or Office 365 organization. You can either use one account that has all the necessary privileges, or you can use two accounts, in which case you would access the on-premises tools using on-premises credentials, and then in those tools you would supply additional credentials for a Microsoft 365 or Office 365 administrative account.

In the on-premises environment, the user performing the move must have the CSServerAdminstrator role in Skype for Business Server.

In Microsoft 365 and Office 365, the user performing the move must either be a Global Administrator or must have both Skype for Business Administrator and User Administrator roles..

You can check this full section.

**Comment by yogkumgit** [comment]
@hirenshah1 Thank you very much for sharing this explanation. @stoff75 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
