### ISSUE TITLE
Can't create teams with Template EDU_Class

### ISSUE THREAD

**Issue by MikaelBSB** [MicrosoftDocs/office-docs-powershell#6323]
[Enter feedback here]
When i want to create team with this command nothing happens :
       New-Team -DisplayName "Tech Reads"  -Template EDU_Class

but when i do this command it's OK : 
       New-Team -DisplayName "Tech Reads"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549c7d86-87b3-5c82-d2b3-a0cc0b4faa11
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @serdarsoysal
* Microsoft Alias: **serdars**

**Comment by Kaliyani** [comment]
I am also getting the same error.

`New-Team -DisplayName $teamName -Description $teamDescription -Visibility $teamVisibility -Template EDU_Class`

![image](https://user-images.githubusercontent.com/38673860/90190111-05ea3480-dddc-11ea-870f-f83c78bc5fbd.png)

I have installed below Microsoft Teams Powershell module

![image](https://user-images.githubusercontent.com/38673860/90190674-16e77580-dddd-11ea-9ccf-6dd351262957.png)

**Comment by MikaelBSB** [comment]
I have the same version for the module MicrosoftTeams (1.1.4) and  my version for Powershell is 5.1.19041.1

**Comment by Bart-Hoofd** [comment]
Regretfully, at this moment only the 0.9.6 module supports the -Template parameter; see https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps: 

_IMPORTANT: Using this cmdlet to create a new team using a template is still in preview. You can install and use the preview module from the PowerShell test gallery. For instructions on installing and using the Teams PowerShell preview module, see Install the pre-release version of the Teams PowerShell module (https://docs.microsoft.com/microsoftteams/install-prerelease-teams-powershell-module)._

I was hoping the 1.1.4 would finally have support, but apparently it still does not.

**Comment by get-itips** [comment]
Hello @MikaelBSB and @Kaliyani as @Bart-Hoofd kindly says here, the -Template parameter is part of the Public Preview module, which current version is 1.1.3-preview

Hope this information helps you

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @MikaelBSB Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Cryptolaemus** [comment]
> Regretfully, at this moment only the 0.9.6 module supports the -Template parameter; see https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps:
> 
> _IMPORTANT: Using this cmdlet to create a new team using a template is still in preview. You can install and use the preview module from the PowerShell test gallery. For instructions on installing and using the Teams PowerShell preview module, see Install the pre-release version of the Teams PowerShell module (https://docs.microsoft.com/microsoftteams/install-prerelease-teams-powershell-module)._
> 
> I was hoping the 1.1.4 would finally have support, but apparently it still does not.

So am I correct in understanding that the only way to get this to work is install version 0.9.6 until Microsoft finally gets these all integrated together in the latest release? It is baffling how things are in preview for longer than new features are released and published in the GA.

**Comment by MikaelBSB** [comment]
i have uninstall the module MicrosoftTeams 1.1.4 and install the version 1.1.3-preview. It works perfect for -Template parameter

**Comment by rickzeleznik** [comment]
This drove me nuts a while back.  Ended up having to do a lot of comparisons between the different module versions, but ultimately found the following for the "-template" parameter:

1.0.5: Does not have it
1.0.6: Does not have it
1.0.7: Does not have it
1.1.3: Has it!!
1.1.4: Does not have it
1.1.5: Does not have it
1.1.6 - 1.1.10:  Has it!

Havent checked beyond that, but my suspicion was that it will be there in all module versions after 1.1.6.  The stutter step on 1.1.3 was what confused me because I was assuming that  >1.1.3 would have it.
