### ISSUE TITLE
The Configuration parameter is not optional

### ISSUE THREAD

**Issue by pschaeflein** [MicrosoftDocs/office-docs-powershell#6325]
This cmdlet will fail unless the Configuration parameter is specified. The syntax diagram has the parameter in brackets ('[') which usually indicates an optional parameter.

In addition, the Configuration parameter is not shown in any examples.

Reference: https://github.com/pnp/PnP-PowerShell/issues/2587

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb60d43-31eb-d304-acdb-2f44c904dc63
* Version Independent ID: 728baaf2-dfef-a453-7959-84784229c413
* Content: [Get-PnPTenantTemplate (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnptenanttemplate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTenantTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPTenantTemplate.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @pschaeflein Paul,

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @pschaeflein Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
