### ISSUE TITLE
I want to use Powershell - what ist the Redirect Uri for?

### ISSUE THREAD

**Issue by mailgut** [MicrosoftDocs/office-docs-powershell#6330]
[Enter feedback here]

You write:
Redirect URI, select Web for the type of application you want to create. Enter the URI where the access token is sent to

I want to use Powershell v2 to script Exchange Online and was advised to follow a link to this website. You asks to fill up a Redirect uri for the token. But what server or cloud service i should use for this. Is there an example?

Is it outlook.office.com?

And why is this needet to use powershell v2 to  script Exchange Online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @mailgut, thank you for your feedback.

> I want to use Powershell v2 to script Exchange Online and was advised to follow a link to this website. You asks to fill up a Redirect uri for the token. But what server or cloud service i should use for this. Is there an example?
> 
> Is it outlook.office.com?

The redirect_uri is where authentication responses can be sent and received by your app or script. It should be an url to receive the token in the server or machine where you are running the script.

> 
> And why is this needet to use powershell v2 to script Exchange Online?

Because it's the only version that supports App-only authentication. For more information, see:
https://techcommunity.microsoft.com/t5/exchange-team-blog/modern-auth-and-unattended-scripts-in-exchange-online-powershell/ba-p/1497387

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @mailgut Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
