### ISSUE TITLE
Create Normilization Rule with New-CsVoiceNormalizationRule

### ISSUE THREAD

**Issue by ryu-sirius** [MicrosoftDocs/office-docs-powershell#6337]
Although normalization rules of a tenant dial plan can be added by using this cmdlet, it is recommended that you use the New-CsVoiceNormalizationRule (https://technet.microsoft.com/en-us/library/gg398240.aspx) cmdlet instead.

When I use the Get-CsVoiceNormalizationRule cmdlet, it does not return my existing Teams Voice Normalization Rules.  I am apprehensive to add normalization rules using the New-CsVoiceNormalizationRule cmdlet, knowing that manually added entries do not exist in the same scope.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6db6b98-1bab-a22a-2df5-a5c5fea5a6e6
* Version Independent ID: 545fa8ce-0abe-4921-04ef-3cd1bf496f24
* Content: [Set-CsTenantDialPlan (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cstenantdialplan?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTenantDialPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTenantDialPlan.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @ryu-sirius 
How are you? Hope you are doing good.

I can see that the sentence you copied from the article can be confusing as this article applies both to on-premises to online so I will try to come up with an improvement to it.

Please confirm me if you tried [this instructions](https://docs.microsoft.com/en-us/microsoftteams/create-and-manage-dial-plans#using-a-powershell-script) to list the rules associated to a tenant dial plan.

Thanks

**Comment by ryu-sirius** [comment]
I found the answer to my question in another document, shortly after posting this thread.

Use the -InMemory parameter to build the array item and add it via the New-CsTenantDialPlan command.  

There is an example of this at:  https://docs.microsoft.com/en-us/microsoftteams/create-and-manage-dial-plans#using-a-powershell-script

Thank you for the response, @get-itips .

**Comment by get-itips** [comment]
> I found the answer to my question in another document, shortly after posting this thread.
> 
> Use the -InMemory parameter to build the array item and add it via the New-CsTenantDialPlan command.
> 
> There is an example of this at: https://docs.microsoft.com/en-us/microsoftteams/create-and-manage-dial-plans#using-a-powershell-script
> 
> Thank you for the response, @get-itips .

Yes, that is exactly the same article I referenced, thanks for returning and sharing your feedback!

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ryu-sirius Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
