### ISSUE TITLE
Article not up to date

### ISSUE THREAD

**Issue by adamcball** [MicrosoftDocs/office-docs-powershell#6338]
This cmdlet has -EmergencyCallRoutingPolicy and -EmergencyCallingPolicy as options but they are not documented here. In addition, -OnlineVoiceRoutingPolicy is documented here but not a valid option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634ddbad-5f50-fed2-a334-9fed921b7394
* Version Independent ID: 749077d4-5b5e-9c37-4e31-100627b3fac9
* Content: [New-CsTenantNetworkSite (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cstenantnetworksite?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTenantNetworkSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTenantNetworkSite.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for noticing @adamcball
