### ISSUE TITLE
Microsoft teams beta module not available in PS test gallery and thus Add-TeamChannelUser  not available

### ISSUE THREAD

**Issue by sangitsdhar** [MicrosoftDocs/office-docs-powershell#6339]
HI,
I tried to install the microsoft teams beta module from the PS test gallery but it says that the module is not present. I need to use the Add-TeamChannelUser command to bulk add team members but am unable to use it in the official version and unable to find the beta module.

**Comment by get-itips** [comment]
Hello @sangitsdhar 
How are you?
The process to use the now called Public Preview module has changed, please see this articles

https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install

and

https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @sangitsdhar Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
