### ISSUE TITLE
microsoft teams beta version not available in PS INT gallery

### ISSUE THREAD

**Issue by sangitsdhar** [MicrosoftDocs/office-docs-powershell#6340]
[Enter feedback here]

The beta version of microsoft Teams is not available in PS INT gallery

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74381d05-2e95-4751-4285-752a46eb025f
* Version Independent ID: 2481b258-b593-e323-90f0-e9ca6e7797bf
* Content: [Add-TeamChannelUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @serdarsoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @sangitsdhar please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/6339#issuecomment-675091350

**Comment by yogkumgit** [comment]
closing via #6339
