### ISSUE TITLE
problem with powershell command Stop-SPOUserAndContentMove : Failed to stop move in progress

### ISSUE THREAD

**Issue by miha-alithya** [MicrosoftDocs/office-docs-powershell#6342]
Hi Everyone !

I used the command Start-SPOUserAndContentMove -UserPrincipalName user@xxx.com -DestinationDataLocation CAN to move an user to another geo location but it still " In progess 4/4 " since more than 24 hours. The OnDrive's is empty.

I tried to use the command Stop-SPOUserAndContentMove but I have an error : " Error Code: -50,Failed to stop the geo move for 'user@xxx.com'. The move is in-progress "

I check the OnDrive's user location with the commande Get-SPOUserOneDriveLocation -UserPrincipalName and it returns blank for MySiteUrl and 00000000-0000-0000-0000-000000000000 for Site ID.

So I check the user account on MSO365 admin console and he has well an OnDrive configured.

Somebeody know how to force stop the move and why this account return strange informations about his Siteurl and Site ID?

Thanks your help :)

Miha

**Comment by get-itips** [comment]
Hello @miha-alithya 
how are you? I think your inquiry will be better handled opening a support ticket, as here we are limited to documentation issues or improvements. So please open a support ticket directly from Office/Microsoft 365 Admin.
Thank you

**Comment by miha-alithya** [comment]
Hi @get-itips 
Thanks for your comment.
My bad, I tought it was for technical problem too.
I close this ticket.
