### ISSUE TITLE
skype cmdlets missing Syntax section

### ISSUE THREAD

**Issue by jeffreyxrh** [MicrosoftDocs/office-docs-powershell#6354]
There are various cmdlets in skype that are missing Syntax information, which will cause build errors.
Here is the build report:
![Capture](https://user-images.githubusercontent.com/22847442/90466599-c2c5f380-e144-11ea-8245-a4a1dc785c05.PNG)
The issue is not limited to only these files. Is this behavior expected?

**Comment by get-itips** [comment]
Hello @jeffreyxrh 
I am completing the sintax of one of those articles so we can check if the build fails, can you share the full list ?
Thanks

**Comment by jeffreyxrh** [comment]
There are 4 that I found:
skype\New-CsTeamsAppPermissionPolicy.md
skype\New-CsTeamsAppSetupPolicy.md
skype\Remove-CsTeamsPinnedApp.md
skype\Remove-CsVideoInteropServiceProvider.md

This one has an extra syntax tag: skype\Set-CsExternalUserCommunicationPolicy.md

**Comment by get-itips** [comment]
@jeffreyxrh added commits to the PR
