### ISSUE TITLE
Table for EXO Powershell page has getrecipient instead of get-EXORecipient for V2 cmdlet

### ISSUE THREAD

**Issue by solbkeston** [MicrosoftDocs/office-docs-powershell#6357]
The table is incorrect at the top of the article.  Note the getrecipient in the first column:

EXO V2 module cmdlet | Older related cmdlet
-- | --
Get-EXOMailbox | Get-Mailbox
GetRecipient | Get-Recipient

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@solbkeston, I fixed it. In the future, you, too, can make simple fixes like this directly without opening an Issue first. For more information, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing.
