### ISSUE TITLE
Search-MailboxAuditLog in EXO fails with "-LogonTypes external" option

### ISSUE THREAD

**Issue by bingoglossy** [MicrosoftDocs/office-docs-powershell#6358]
When trying to run **Search-MailboxAuditLog** with the "-LogonTypes external" option on EXO it throws:

**Cannot process argument transformation on parameter 'LogonTypes'. Cannot convert value "external" to type
"Microsoft.Exchange.Data.MultiValuedProperty`1[Microsoft.Exchange.Data.Directory.AuditScopes]". Error: "Failed to convert external from System.String to
Microsoft.Exchange.Data.Directory.AuditScopes. Error: System.FormatException: Error while converting string 'external' to result type
Microsoft.Exchange.Data.Directory.AuditScopes: Conversion failed due to invalid enumeration value. Please specify one of the following enumeration values and try
again. The possible enumeration values are 'Admin, Delegate, Owner'. ---> System.ArgumentException: Conversion failed due to invalid enumeration value. Please specify
one of the following enumeration values and try again. The possible enumeration values are 'Admin, Delegate, Owner'. ---> System.ArgumentException: Requested value
'external' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Microsoft.Exchange.Data.ValueConverter.InternalConvertStringToObject(String originalValue, Type resultType, IFormatProvider formatProvider, Object& result,
Exception& error)
   at Microsoft.Exchange.Data.ValueConverter.TryConvertValueFromString(String originalValue, Type resultType, IFormatProvider formatProvider, Object& result,
Exception& error)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.Data.ValueConverter.ConvertValueFromString(String originalValue, Type resultType, IFormatProvider formatProvider)
   at Microsoft.Exchange.Data.ValueConverter.TryParseConversion(Object originalValue, Type originalType, Type resultType, IFormatProvider formatProvider, Object&
result)"
    + CategoryInfo          : InvalidData: (:) [Search-MailboxAuditLog], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Search-MailboxAuditLog
    + PSComputerName        : outlook.office365.com**

so please update the documentation in alignment with the new result.

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d59cd7b8-488e-6f87-cbe0-3e7212c07a6f
* Version Independent ID: bc48c26f-0a3f-0511-088e-5a9a19650f43
* Content: [Search-MailboxAuditLog (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/search-mailboxauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Search-MailboxAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Search-MailboxAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bingoglossy, I removed the External value from the parameter description.

Thanks for the feedback.

Closing.
