### ISSUE TITLE
(verb)-TeamchannelUser unavailable in 1.1.4 of Module MicrosoftTeams.

### ISSUE THREAD

**Issue by CraigOnline** [MicrosoftDocs/office-docs-powershell#6363]
The commands (verb)-TeamchannelUser are unavailable in the 1.1.4 of Module MicrosoftTeams.
There is also no mention of a development (INTerim?) MicrosoftTeams module in PSGalleryINT.

I would like feedback please regarding the status and future of this command, or of any replacement command, to enumerate/audit all the objects in MSTeams.

reference page: https://docs.microsoft.com/en-us/powershell/module/teams/Get-TeamChannelUser?view=teams-ps

**Comment by get-itips** [comment]
Hello @CraigOnline how are you?

An update to the Get-TeamChannelUser article [is about to be merged](https://github.com/MicrosoftDocs/office-docs-powershell/pull/6345), as the home for the now called _Public Preview_ module is in the same PSGallery as the GA module.

You will find that cmdlet in the 1.1.3-preview (Public Preview module).

Please see here https://docs.microsoft.com/microsoftteams/teams-powershell-install#install-teams-powershell-public-preview
and here https://docs.microsoft.com/microsoftteams/teams-powershell-release-notes for more information.

Thank you

**Comment by CraigOnline** [comment]
Thankyou for the input @get-itips. 
Cheers ./cb
