### ISSUE TITLE
AutoForwardingMode parameter missing

### ISSUE THREAD

**Issue by itpro-tips** [MicrosoftDocs/office-docs-powershell#6365]
Hello,

A new parameter _-AutoForwardingMode_ is available for _Set-HostedOutboundSpamFilterPolicy_ but I don't see any documentation.
This parameter can be used in production ?
It is also available on [https://protection.office.com/antispam](https://protection.office.com/antispam) -> outbound

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6920a144-bebb-2d5a-d328-855e6a4613a4
* Version Independent ID: 35937201-f07b-7c3b-42f5-fd923c9adb04
* Content: [Set-HostedOutboundSpamFilterPolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-hostedoutboundspamfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-HostedOutboundSpamFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-HostedOutboundSpamFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@itpro-tips, a similar issue was raised in the regular anti-spam policy content [here](https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2612).

I've been able to determine that the new UI and parameters are available to everyone; however, they won't start doing anything until after September 1st. 

I was waiting for confirmation about exactly what the "Automatic: System-controlled" value means.

I'll update the corresponding cmdlet reference topics as well.

**Comment by chrisda** [comment]
Topic updated.

Thanks for the feedback.

Closing.
