### ISSUE TITLE
"Certificate is not accessible to the current user." error with CertificateFilePath and CertificatePassword

### ISSUE THREAD

**Issue by adzero** [MicrosoftDocs/office-docs-powershell#6371]
I'm trying to connect with an AppId and a self signed certificate as explained in the [documentation](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2). 

First, I tried using the **CertificateThumbprint** parameter with the certificate stored in my user account store, which is working fine. 

Then I switched to the other way using the exported pfx and its password with the  **CertificateFilePath** and **CertificatePassword**.  I can't figure out why I'm getting the following error : 

``New-ExoPSSession : Certificate is not accessible to the current user.``

I can open my pfx file with ``Get-PfxCertificate`` with the password. 

Could it be a bug or is there something I missed ?

**Comment by dariomws** [comment]
Hi @adzero, thank you for your feedback.

I cannot help you here as we are limited to documentation issues and improvements. I suggest that you put a comment in the following link:
https://techcommunity.microsoft.com/t5/exchange-team-blog/modern-auth-and-unattended-scripts-in-exchange-online-powershell/ba-p/1497387

At this link, I am unable to see users reporting this issue so I think it's a particular issue that you are experiencing.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @adzero Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ThePoShWolf** [comment]
I hate to comment on an old issue, but this was the top result when I searched for that very error. I was able to work around it by providing the fully qualified path to the certificate instead of a relative path.
