### ISSUE TITLE
Incorrect examples

### ISSUE THREAD

**Issue by 216rick** [MicrosoftDocs/office-docs-powershell#6372]
[Enter feedback here]
Examples are for Get-PnPTeamsTeam not New-PnPTeamsTeam.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 446c283c-88f3-5268-4647-5dc9fc02cc4e
* Version Independent ID: 0094ebb4-ca9a-147f-7f3f-fd63994397f3
* Content: [New-PnPTeamsTeam (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpteamsteam?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPTeamsTeam.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPTeamsTeam.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @216rick how are you?
Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @216rick Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
