### ISSUE TITLE
New-Team cmdlet does not recognise -Template parameter

### ISSUE THREAD

**Issue by rjmholt** [MicrosoftDocs/office-docs-powershell#6373]
From https://github.com/PowerShell/vscode-powershell/issues/2903.

---

Original issue:

Hi All,
it appears that I have VSC with preview extension properly running, but get the following

```
New-Team : Es wurde kein Parameter gefunden, der dem Parameternamen "Template" entspricht.
In C:\Users\kay\OneDrive\Documents\WindowsPowerShell\Scripts\KlassenErstellen.ps1:10 Zeichen:96
+ ... es -Mailnickname $mai -Owner $own -AllowGiphy $false -Template $tem `
+                                                          ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-Team], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.TeamsCmdlets.PowerShell.Custom.NewTeam
```

when executing `New-Team -DisplayName $nam -Description $des -Mailnickname $mai -Owner $own -AllowGiphy $false -Template $tem`

Anyone any idea?
thx
Kay

---

[The docs](https://docs.microsoft.com/en-us/powershell/module/teams/new-team) show `-Template` as being a possible parameter in the `-DisplayName` parameter set, so the above should not result in a parameter binding exception.

Also, the original reporter of this issue was unable to open a new issue in this repository: https://github.com/PowerShell/vscode-powershell/issues/2903#issuecomment-678438141. If that's intentional, this repository probably should not be where the product feedback link at the bottom of docs pages points.

**Comment by get-itips** [comment]
Hello @rjmholt Robert
Please see here https://github.com/MicrosoftDocs/office-docs-powershell/issues/6323#issuecomment-674589858

Template parameter is part of the Public Preview module, that version currently is 1.1.3-preview so be sure to be running that one on your system, if you want to use the -Template parameter.

Hope this clarifies it to you!

**Comment by rjmholt** [comment]
@xlupy let me know if this is ok to close

**Comment by xlupy** [comment]
Hi @get-itips ,
I´m not sure what component needs 1.1.3 - is it this?
![image](https://user-images.githubusercontent.com/70028848/91315582-22ad4180-e7b8-11ea-9b23-e3f081e9ed29.png)
Thanks again :-)

**Comment by get-itips** [comment]
Hello @xlupy 
I am afraid I can not help you regarding VSCode related requirements as this repo is limited to address issues in documentation of certain PowerShell modules, including Teams.
What I can tell you is that if you intend to use -Template parameter for New-Team cmdlet, you have to use version 1.1.3-preview of that module, more information on the links I provided earlier.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @rjmholt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by rjmholt** [comment]
@xlupy I think you're conflating a few unrelated things.

The PowerShell and PowerShell Preview extensions are VSCode extensions that allow you to edit and run PowerShell in VSCode. They have nothing to do with the Teams PowerShell module.

You can use the extension to run Windows PowerShell 5.1 or PowerShell 7, and I believe either can load and run the Teams module.

I believe the reason you are experiencing the issue you originally filed is that you need the [1.1.3-preview version](https://www.powershellgallery.com/packages/MicrosoftTeams/1.1.3-preview) of the Microsoft Teams module installed (by using `Install-Module` in PowerShell).

**Comment by rjmholt** [comment]
@yogkumgit @get-itips I work on the PowerShell team and am a maintainer of the PowerShell extension for VSCode, but had to open the issue here for @xlupy after they opened an issue in our repo, because this repository did not allow him to open an issue despite being the product feedback link in the docs page:

![image](https://user-images.githubusercontent.com/7009879/91335371-2673a080-e785-11ea-8d60-4fe2de6bbfa4.png)

I would suggest ensuring the product feedback link allows users to open issues or otherwise submit feedback so that I don't need to migrate and intermediate issues for you.

**Comment by get-itips** [comment]
Hello @rjmholt Robert,
I do not know why it didn't allow @xlupy to open an issue here as anyone can open issues in this repo.
Thanks for your feedback!
