### ISSUE TITLE
Get-TeamHelp doesn't work

### ISSUE THREAD

**Issue by SamZhangQingChuan** [MicrosoftDocs/office-docs-powershell#6374]
![image](https://user-images.githubusercontent.com/8025859/90950805-c1b7fd80-e487-11ea-990d-aba72c29f7bb.png)

**Comment by get-itips** [comment]
Hello @SamZhangQingChuan Yes, it was removed from the module according to https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes will create a PR to remove the article. Thank you!
