### ISSUE TITLE
Mount-SPContentDatabase will also create a database if it doesn't exist

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/office-docs-powershell#6375]
Instead of returning an error, `Mount-SPContentDatabase` will actually create a brand new blank content database if the specified database doesn't already exist. 

This can lead to hours of head-scratching trying to find "missing" site collections when a typo on a database name is made.

Ideally the behaviour could be changed, or a "-ErrorIfMissing" added, etc., but at the very least a mention here in big letters here in the docs would be great.

<3

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e5b70e0-6664-00dc-0083-89b2451fb344
* Version Independent ID: 99ad8c9d-f333-adda-b0fd-5c9cf426f66c
* Content: [Mount-SPContentDatabase (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/mount-spcontentdatabase?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Mount-SPContentDatabase.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Mount-SPContentDatabase.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @fowl2 James,
Thanks for your feedback, I could verify this on SHP2019, will make an edit to the article to improve it to warn about this.
Thanks again
