### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by azha23** [MicrosoftDocs/office-docs-powershell#6377]
Typo
"Mode also governs what functionality is avaiable in the Teams client. " should read
"Mode also governs what functionality is available in the Teams client. "
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0dd44c-bfc9-5f82-68c4-7b469129e8a5
* Version Independent ID: ea015ee3-54e2-e402-d533-c8a9a15557e8
* Content: [Grant-CsTeamsUpgradePolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsupgradepolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for reporting @azha23
