### ISSUE TITLE
Incorrect -CorrectionUri for Microsoft 365 GCC High

### ISSUE THREAD

**Issue by milesgratz** [MicrosoftDocs/office-docs-powershell#6378]
This article is incorrectly referencing the **DoD ConnectionUri**  instead of the **GCC High ConnectionUri**  in both sections below, currently ```https://l5.ps.compliance.protection.office365.us/powershell-liveid/``` but should be ```https://outlook.office365.us/powershell-liveid``` as per  [Connect-IPPSSession](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-ippssession?view=exchange-ps)

- [Connect to Security & Compliance PowerShell using MFA](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps#connect-to-security--compliance-powershell-using-mfa)

- [Connect to Security & Compliance Center PowerShell without using MFA](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps#connect-to-security--compliance-center-powershell-without-using-mfa)

![image](https://user-images.githubusercontent.com/17114534/90994835-b34d0d00-e57f-11ea-9297-237b95da3001.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by milesgratz** [comment]
Sorry, I believe the URI above is wrong for SCC (should be ```https://ps.compliance.protection.office365.us/powershell-liveid/```?) but hopefully we can update both this doc and the [Connect-IPPSSession](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-ippssession?view=exchange-ps) (#6379) at once with the correct URIs.

**Comment by chrisda** [comment]
@milesgratz, I fixed it. In the future, you can make updates yourself directly without opening a GitHub issue first. For more information, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
