### ISSUE TITLE
Incorrect -CorrectionUri for Microsoft 365 GCC High

### ISSUE THREAD

**Issue by milesgratz** [MicrosoftDocs/office-docs-powershell#6379]
Referencing #6378 because it looks like the [Connect-IPPSSession](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-ippssession?view=exchange-ps) docs are referencing the wrong -ConnectionUri as well. Based on an older commit, is the correct URI ```https://ps.compliance.protection.office365.us/powershell-liveid/``` ? 

![image](https://user-images.githubusercontent.com/17114534/90996739-42105880-e585-11ea-910a-01db989e7dc7.png)

![image](https://user-images.githubusercontent.com/17114534/90996654-05dcf800-e585-11ea-8588-476bf9550c09.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfa8b9c0-ec9c-4e11-0352-de8c5b0752a1
* Version Independent ID: 5383d152-988d-b1ee-4957-db5fb6213754
* Content: [Connect-IPPSSession (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-ippssession?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-IPPSSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Connect-IPPSSession.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@milesgratz, I fixed it. In the future, you can make updates yourself directly without opening a GitHub issue first. For more information, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
