### ISSUE TITLE
recoveryEnabled

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/office-docs-powershell#6382]
What does the recoveryEnabled attribute defines and what are the expected values for this attribute?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781f6cb6-e1b5-ef1d-b811-171d9d749f91
* Version Independent ID: b3a23a18-70af-d4c6-dd77-176f90d1d895
* Content: [Get-SPODataEncryptionPolicy (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spodataencryptionpolicy?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataEncryptionPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataEncryptionPolicy.md)
* Service: **sharepoint-powershell**
* GitHub Login: @
* Microsoft Alias: ****

**Comment by get-itips** [comment]
Hello @Larryngolog Pawel
Where are you seeing that attribute? in the output of this cmdlet?
Thanks

**Comment by Larryngolog** [comment]
Hello, yes, in the cmdlet output.

**Comment by get-itips** [comment]
@tseward Trevor, do you happen to know about this attribute?

**Comment by tseward** [comment]
@get-itips I do not, sorry.

**Comment by get-itips** [comment]
@trent-green Trent, can you help us here? I appreciate.

**Comment by get-itips** [comment]
@trent-green Can you please confirm the _recoveryEnabled_ attribute is related to the soft-delete feature of Azure KeyVault? 

https://docs.microsoft.com/en-us/azure/key-vault/general/soft-delete-overview

Thanks

**Comment by yogkumgit** [comment]
@AdwoodMicrosoft Kindly help. Thanks

**Comment by tiburd** [comment]
The cmdlet owner has been notified of this issue, but we don't have any updates at this time.
Thanks!

**Comment by tiburd** [comment]
@yogkumgit @get-itips
