### ISSUE TITLE
Need to document new Set-OrganizationConfig option OutlookGifPickerDisabled

### ISSUE THREAD

**Issue by philipzloh** [MicrosoftDocs/office-docs-powershell#6386]
`OutlookGifPickerDisabled` is default `$false` and can be set to `$true`. This disables the GIF Search (powered by Bing) feature built into the Outlook Web Compose page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03895b30-2bb7-9e96-28db-def76ae59029
* Version Independent ID: 8056b3ee-4fab-3a5c-935b-a9d0e9ad82a4
* Content: [Set-OrganizationConfig (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @philipzloh, thank you for your feedback.

Are you from Microsoft?
