### ISSUE TITLE
The commands is not working for me

### ISSUE THREAD

**Issue by robinvp90** [MicrosoftDocs/office-docs-powershell#6388]
Hi Team,

I was tried to create a channel using this syntax. but unfortunately, while I trying set membership type getting below error.

New-TeamChannel -GroupId 126b90a5-e65a-4fef-98e3-d9b49f4acf12 -DisplayName "Engineering" -MembershipType Private
https://docs.microsoft.com/en-us/powershell/module/teams/new-teamchannel?view=teams-ps
![image](https://user-images.githubusercontent.com/68440429/91129282-5fe5d680-e6c7-11ea-91fe-c3d462ad6897.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd44b411-4b59-b90f-0b82-ad0a87652854
* Version Independent ID: 2c52cc4e-47a1-be0d-8860-1011adf061fd
* Content: [New-TeamChannel (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-teamchannel?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @serdarsoysal
* Microsoft Alias: **serdars**

**Comment by oshihirii** [comment]
I am not an expert, but maybe try removing `1.1.4` and installing `1.1.3-preview` like in [this issue](https://github.com/MicrosoftDocs/office-docs-powershell/issues/6287)?

**Comment by robinvp90** [comment]
Yes it's working fine after installing 1.1.3-preview

![image](https://user-images.githubusercontent.com/68440429/91172566-0a76ed00-e6fa-11ea-9afb-29f289ca6341.png)

**Comment by get-itips** [comment]
Hello
@robinvp90 Yes exactly as @oshihirii has indicated, that parameter is part of the Public Preview module.
You can find more information here:
https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @robinvp90 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
