### ISSUE TITLE
What is the difference between New-ProtectionAlert and New-ActivityAlert?

### ISSUE THREAD

**Issue by oshihirii** [MicrosoftDocs/office-docs-powershell#6389]
What is the difference between:

[New-ProtectionAlert](https://docs.microsoft.com/en-us/powershell/module/exchange/new-protectionalert?view=exchange-ps)

> This cmdlet is available only in Security & Compliance Center PowerShell. For more information, see Security & Compliance Center PowerShell (https://docs.microsoft.com/powershell/exchange/scc-powershell).
> 
> Use the New-ProtectionAlert cmdlet to create alert policies in the Security & Compliance Center. Alert policies contain conditions that define the user activities to monitor, and the notification options for email alerts and entries in the Security & Compliance Center.

and:  

[New-ActivityAlert](https://docs.microsoft.com/en-us/powershell/module/exchange/new-activityalert?view=exchange-ps)

> This cmdlet is available only in Security & Compliance Center PowerShell. For more information, see Security & Compliance Center PowerShell (https://docs.microsoft.com/powershell/exchange/scc-powershell).
> 
> Use the New-ActivityAlert cmdlet to create activity alerts in the Security & Compliance Center. Activity alerts send you email notifications when users perform specific activities in Microsoft 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02fa4960-2504-de2d-c2b1-873afff9f800
* Version Independent ID: e4ff3e18-d1f9-8d87-f70d-6996ca0f9c35
* Content: [New-ProtectionAlert (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-protectionalert?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ProtectionAlert.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ProtectionAlert.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @oshihirii, thank you for your feedback and help us to improve docs.microsoft.com.

For more information about **alert policies** and **activity alerts** please see:
https://docs.microsoft.com/microsoft-365/compliance/alert-policies
https://docs.microsoft.com/microsoft-365/compliance/create-activity-alerts

In the first article you can see:
"**Alert policies** build on and expand the functionality of **activity alerts** by letting you categorize the alert policy, apply the policy to all users in your organization, set a threshold level for when an alert is triggered, and decide whether to receive email notifications."

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @oshihirii Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
