### ISSUE TITLE
Search-UnifiedAuditLog and Search-MailboxAuditLog Both Return No Results in 21vianet (Chinese) Tenant

### ISSUE THREAD

**Issue by franklesniak** [MicrosoftDocs/office-docs-powershell#6399]
Hi,

It seems we cannot retrieve audit logs from a China M365/O365 tenant. The commands Search-UnifiedAuditLog and Search-MailboxAuditLog both execute successfully, but return no results. Audit logging appears to be enabled.

We confirmed audit logging is enabled on a mailbox by running this command:
Get-Mailbox "somemailboxaddress@domain.com" | Format-List Name,Audit*

Is it expected that these commands do not return any results on a Chinese tenant?

More info including screenshot of audit settings in this thread: https://twitter.com/FrankLesniak/status/1298322873623486472?s=20

**Comment by dariomws** [comment]
Hi @franklesniak, for your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration with 21vianet, they will be able to help you as here we are limited to documentation issues and improvements.

More information: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products?view=o365-21vianet&tabs=phone#contact-support

Thank you!

**Comment by franklesniak** [comment]
Hi @dariomws, thank you for the reply. The reason that I opened an issue here on the Docs GitHub is that I was hoping to improve the documentation. That is, if these cmdlets are not expected to work on 21vianet, I felt it should be noted on the respective cmdlet pages.

That said, my team had temporary access to one of these tenants as part of a threat hunt exercise, so we cannot open a support with 21vianet as we normally would for the technical side of this issue.
