### ISSUE TITLE
Connecting to other tenants using Partner Delegated Admin

### ISSUE THREAD

**Issue by 1trevor** [MicrosoftDocs/office-docs-powershell#6402]
Can you please add instructions for how to connect to other tenants via partner delegated admin rights? Do you have to grant permissions for the service principal in each tenant you need to manage? How would you go about that?

When I try to connect to another organization using the -organization or -delegatedorganization parameters I get the following error message:

> AADSTS700016: Application with identifier 'XXXXXXXXXXXXXXXXX' was not found in the directory 'XXXXXXXX'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @1trevor, thank you for your feedback and help us to improve docs.microsoft.com.

To connect as an authorized partner to Exchange Online PowerShell you need to use the DelegatedOrganization parameter. For more information, see:
https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell
https://docs.microsoft.com/powershell/module/exchange/connect-exchangeonline

**Comment by 1trevor** [comment]
Hi @dariomws 

Those parameters work when using user account authentication, but they don't appear to work using the application authentication option described in the article. Should those parameters work the same with app authentication? When I try it I get the error that I listed above.

Thanks!

**Comment by dariomws** [comment]
@1trevor this feature is on preview, what is documented in this article is what works.
Anyway, if you want to get more information you can try here:
https://techcommunity.microsoft.com/t5/exchange-team-blog/modern-auth-and-unattended-scripts-in-exchange-online-powershell/ba-p/1497387

Thanks again, for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @1trevor Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
