### ISSUE TITLE
SharePoint 2019: Import-SPWeb fails with modern list

### ISSUE THREAD

**Issue by pluckyyau** [MicrosoftDocs/office-docs-powershell#6406]
How to solve the problem of "invalid child element 'ColumnWidth' in namespace 'urn:deployment-manifest-schema'."
Ref.
[https://docs.microsoft.com/en-us/answers/questions/64977/sharepoint-2019-import-spweb-fails-with-modern-lis.html](https://docs.microsoft.com/en-us/answers/questions/64977/sharepoint-2019-import-spweb-fails-with-modern-lis.html)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae171b60-a096-2eef-d096-2c560553ac54
* Version Independent ID: b825e536-7724-f08a-677b-8c36d9102ade
* Content: [Import-SPWeb (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/import-spweb?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Import-SPWeb.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Import-SPWeb.md)
* Product: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@pluckyyau this is a product bug. I would suggest opening a support case with Microsoft (support.microsoft.com) to identify a resolution to this issue.

**Comment by yogkumgit** [comment]
@pluckyyau Thank you for reporting this feedback here. This list is focused on content issues and I want to make sure your immediate product issue does not get lost in this list. If you would please open a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
