### ISSUE TITLE
Set-TeamArchivedState is not recognized

### ISSUE THREAD

**Issue by hlanchas** [MicrosoftDocs/office-docs-powershell#6408]
I would like to use this cmdlet to bulk archive more than 400 teams... but I get this error...

Set-TeamArchivedState : The term 'Set-TeamArchivedState' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Set-TeamArchivedState -GroupId 11fc4569-a9d0-4bd7-bdcd-4332a52c33ce - ...
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-TeamArchivedState:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8b945cd2-8ea3-0d90-e168-7df26b1eebd9
* Version Independent ID: 84061af5-8d86-6ef5-0928-e7dcde75baae
* Content: [Set-TeamArchivedState (teams)](https://docs.microsoft.com/es-es/powershell/module/teams/Set-TeamArchivedState?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-TeamArchivedState.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-TeamArchivedState.md)
* Service: **teams-powershell**
* GitHub Login: @serdarsoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @hlanchas Henar, how are you?
Please be sure you are running latest version of Teams PowerShell module, as the cmdlet is available both in 1.1.4 and 1.1.3-preview

More information here https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes

Thanks

**Comment by hlanchas** [comment]
We where running 0.9.6... I've updated and I'll try again. Thank you so much for your help!

**Comment by get-itips** [comment]
> We where running 0.9.6... I've updated and I'll try again. Thank you so much for your help!

Hello @hlanchas Henar, how are you? Can you please share an update so we can close this issue? Thank you

**Comment by hlanchas** [comment]
Yes, that was the problem! You can close the issue, thank you so much for your help...

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @hlanchas Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
