### ISSUE TITLE
Stuck in NotStarted for very long time 

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/office-docs-powershell#6412]
Hey, regarding new-csbatchpolicyassignmentoperation 
1: How long does it take before the batch is handled in the backend (queued in the status NotStarted) 
and why does it say NotStarted for several hours even though the policy has been assigned to the batch of users?
Would be good to update the site with expected values for this.
thanks
/Markus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d149ca60-bfb7-5077-2643-1a08ad926cca
* Version Independent ID: 24754aee-bff2-fa16-e7e6-af45362fd916
* Content: [New-CsBatchPolicyAssignmentOperation (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csbatchpolicyassignmentoperation?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by Jacob-Steentoft** [comment]
We're seeing the same wait times on our side for smaller groups of people, around 10-12, where the policy has not started yet.

**Comment by JohanssonMarkus** [comment]
@Jacob-Steentoft Sometimes it's handled direct but sometimes it takes up to 2 hours. 
Have you run larger set of users? Guess it's the same with larger batches?

**Comment by Jacob-Steentoft** [comment]
@JohanssonMarkus It has been around 5 hours with 2 batches. One with 14 users, and one with 401. Both are NotStarted.

Looking at the user profiles, the policy has been assigned for both batches.

**Comment by JohanssonMarkus** [comment]
@Jacob-Steentoft that is my experience as well. First it can take up to two hours before the batch is processes. 
But also when users has been updated status is NotStarted  for a very long time. So there are two items that would be good if MS can explain and improve.

**Comment by get-itips** [comment]
Hello @Jacob-Steentoft Jacob
How are you?
The last information I could get from the team was [this](https://github.com/MicrosoftDocs/office-docs-powershell/issues/5214#issuecomment-626899280)
I'll try to confirm if that information still applies,
Thanks

**Comment by get-itips** [comment]
Hello @Jacob-Steentoft How are you? Did you have chance to see my comment? Thank you

**Comment by Jacob-Steentoft** [comment]
@get-itips 
Sorry I missed your earlier message.
Our 2 batches closed when I checked it the next day. Wasn't aware that it was still in preview, but it worked well, just didn't update us with a status.

Thanks for the reply.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @JohanssonMarkus Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
