### ISSUE TITLE
Text says the command is for site collections, but the first sample is a subsite misidentified as a site collection

### ISSUE THREAD

**Issue by fselkirk** [MicrosoftDocs/office-docs-powershell#6416]
The text says this is for a top-level site (i.e. site collection). 

Example 1 says: 

> This example creates a new Microsoft 365 Group named "site1group" and connects site collection https://contoso.sharepoint.com/sites/site1...

https://contoso.sharepoint.com/sites/site1 is a subsite. 
https://contoso.sharepoint.com/sites is the site collection. 

Something needs correcting here. Perhaps we expanded the capabilities? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f97f530-5982-64b0-8cf5-02a9f361b75b
* Version Independent ID: f10aeefa-17b4-1929-8e89-b8a2b67ee5fa
* Content: [Set-SPOSiteOffice365Group (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Set-SPOSiteOffice365Group?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteOffice365Group.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteOffice365Group.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @fselkirk How are you?

https://contoso.sharepoint.com/sites/site1 is actually a site collection and /sites/ is the [managed path](https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-wssts/4c7a8d5a-4bcf-45a1-a414-2c9878e4a897#:~:text=2.1.&text=A%20managed%20path%20specifies%20a,paths%20and%20wildcard%20managed%20paths.).

for example

![image](https://user-images.githubusercontent.com/36666927/91726249-50a6d300-eb76-11ea-81fd-9423a6caa27c.png)

A subsite would be: https://contoso.sharepoint.com/sites/Site1/Subsite1/

for example:

![image](https://user-images.githubusercontent.com/36666927/91727144-9f08a180-eb77-11ea-8629-9294b9568ae8.png)

**Comment by fselkirk** [comment]
I have no idea where my brain was. You are completely right.

Frances Selkirk
Support Escalation Engineer | SharePoint Online and SharePoint Client Technical Support
fselkirk@Microsoft.com<mailto:fselkirk@Microsoft.com> | +1 (857) 453-6233 | Available Monday – Thursday: 11:00 – 18:00, ET (GMT -5 :00)
Manager: Floyd Mathias  floydm@microsoft.com<mailto:floydm@microsoft.com> | +1 (781) 487-6679
Backup: Brian Yau  brian.yau@microsoft.com<mailto:brian.yau@microsoft.com> |  +1 (781) 4876613

**Comment by get-itips** [comment]
> I have no idea where my brain was. You are completely right. Frances Selkirk Support Escalation Engineer | SharePoint Online and SharePoint Client Technical Support

No worries at all 👍 Thanks for getting back!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @fselkirk Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
