### ISSUE TITLE
Remove-TeamUser - Cannot validate argument 'Member' on Parameter 'Role'

### ISSUE THREAD

**Issue by JakeMoe** [MicrosoftDocs/office-docs-powershell#6429]
This appears to be a recurrence of #5479 which says it was fixed, updated, and closed.  I'm getting it now on module version 1.1.4.

When I try to remove a user from a Team and specify the role 'Member', I get the error below:

```
PS C:\Windows\system32> Remove-TeamUser -GroupId $team.GroupId -User $members[4].User -Role $members[4].Role
Remove-TeamUser : Cannot validate argument on parameter 'Role'. The argument "member" does not belong to the set "Owner" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At line:1 char:69
+ ...  -GroupId $team.GroupId -User $members[4].User -Role $members[4].Role
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-TeamUser], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.TeamsCmdlets.PowerShell.Custom.RemoveTeamUser
```

My current workaround is to omit the 'Role' parameter, which I believe effectively does the same thing?

**Comment by get-itips** [comment]
Hello @JakeMoe 
How are you? Thanks for your feedback.

What was fixed was the article, reflecting the current behavior, which is that, the "Member" value was removed as a possible value for -Role parameter and an example was added on how to remove a member effectively (indeed without specifying the Role parameter)

Hope this clarifies it to you, thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @JakeMoe Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
