### ISSUE TITLE
New-CsCallingLineIdentity to set a service number

### ISSUE THREAD

**Issue by bmomartins** [MicrosoftDocs/office-docs-powershell#6432]
Command does not seem to be working, resulting in:

The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing, ProcessRecord, and EndProcessing methods, and they can only be called from within the same thread.
Validate that the cmdlet makes these calls correctly, or contact Microsoft Customer Support Services.
    + CategoryInfo          : OperationStopped: (:) [New-CsCallingLineIdentity], PSInvalidOperationException
    + FullyQualifiedErrorId : AggregateException,Microsoft.Rtc.Management.Internal.NewCallingLineIdentityCmdlet
    + PSComputerName        : admin2e.online.lync.com

Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44879cab-fc84-1a8c-7a1d-b747c9d5c093
* Version Independent ID: 03768800-44a7-a670-0e84-a9f40f6b2cca
* Content: [New-CsCallingLineIdentity (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsCallingLineIdentity.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @bmomartins Bruno, how are you?
Can you please confirm that your tenant satisfies this condition?

> ServiceNumber must be a valid Service Number in the Skype for Business Online online telephone number inventory.

Thanks

**Comment by get-itips** [comment]
Hello @bmomartins Bruno, returning to ask you if you could see my question here, thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and digging deep into it.  @bmomartins We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by bmomartins** [comment]
> Hello @bmomartins Bruno, how are you?
> Can you please confirm that your tenant satisfies this condition?
> 
> > ServiceNumber must be a valid Service Number in the Skype for Business Online online telephone number inventory.
> 
> Thanks

That was the issue.

Thanks!

**Comment by get-itips** [comment]
> > Hello @bmomartins Bruno, how are you?
> > Can you please confirm that your tenant satisfies this condition?
> > > ServiceNumber must be a valid Service Number in the Skype for Business Online online telephone number inventory.
> > 
> > 
> > Thanks
> 
> That was the issue.
> 
> Thanks!

Thanks for returning to confirm, have a great day.
