### ISSUE TITLE
Request Additional Examples for Invoke-PnPQuery

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/office-docs-powershell#6433]
Could you please provide examples of other command combinations that can be used with Invoke-PnPQuery?

As an example, this is a really useful command for changing the list URL. 
#Get list & change URL
$List = Get-PnPList -Identity $ListName -Includes RootFolder;
$List.Rootfolder.MoveTo($NewListURL);
Invoke-PnPQuery;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0b9eb5d-0983-011a-0e66-26da329206f6
* Version Independent ID: 790e6b33-93bb-550f-2cf7-b8a8153bb864
* Content: [Invoke-PnPQuery (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/invoke-pnpquery?view=sharepoint-ps#examples)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Invoke-PnPQuery.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Invoke-PnPQuery.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @robertcaretta how are you?
Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

Thank you!

**Comment by robertcaretta** [comment]
Done. I submitted the request at that location.
