### ISSUE TITLE
Placeholders on page

### ISSUE THREAD

**Issue by Van-Fouran** [MicrosoftDocs/office-docs-powershell#6435]
The following documentation page contains placeholders in many areas.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dba33181-eb97-69f0-7643-68b20dac4cf6
* Version Independent ID: 85ed0193-8c1c-fca6-153b-dc4078d3085a
* Content: [Get-SPOTenantOrgRelation (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantorgrelation?view=sharepoint-ps#outputs)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantOrgRelation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantOrgRelation.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @Van-Fouran Felix, how are you?
Please see [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/4930#issuecomment-622012154).

Thanks

**Comment by Van-Fouran** [comment]
@get-itips Thank you for the answer. I did not realize the note at the top of the sections.
