### ISSUE TITLE
Get-PnPUPABulkImportStatus Doesn't Show Date/Time

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#6446]
Output does not show date/time of execution or status last updated date/time

**Comment by get-itips** [comment]
Hello @danmyhre Dan, how are you?
Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @danmyhre Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by danmyhre** [comment]
Should probably turn comments off in this section then.  This is not the standard way content on docs works.
