### ISSUE TITLE
Missing attributed in propertysets

### ISSUE THREAD

**Issue by ildjarnisdead** [MicrosoftDocs/office-docs-powershell#6447]
There are properties on a mailbox that are not in any propertyset of Get-EXOMailbox mentioned on this page (e.g. WhenCreated or IsDirSynced), except the 'All' Propertyset, which seems a bit resource-unfriendly if you only need one of those properties.
Is the list of PropertySets in the documentation not complete, or are these properties only available with the All PropertySet?

Joost
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9145396-cc72-6e54-4204-6867397e67ea
* Version Independent ID: ca86d515-e4d3-ce0f-11e3-87ddfda38b75
* Content: [Property sets in Exchange Online PowerShell V2 cmdlets](https://docs.microsoft.com/en-us/powershell/exchange/cmdlet-property-sets?view=exchange-ps#get-exomailbox-property-sets)
* Content Source: [exchange/docs-conceptual/cmdlet-property-sets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/cmdlet-property-sets.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ildjarnisdead, the property sets are meant to provide a logical grouping of properties for increased performance. You are correct in that properties that don't belong to a specific property set are available in All, and All is too big for improved performance, so we don't recommend it.

That's where the Properties parameter comes in. If you use the Properties parameter by itself, the properties in the Minimum property set (which are mostly identification properties) AND the properties you specify are returned in the results. If a specific property set only lacks a few properties that you're interested in, you can use the PropertySets parameter AND the Properties parameter to return the properties that you're interested in.

Does this make sense?

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @ildjarnisdead Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
