### ISSUE TITLE
With the Set-CsTeamsMeetingPolicy cmdlet, why is the -AllowAnonymousUsersToDialOut parameter disabled?

### ISSUE THREAD

**Issue by ThePangy** [MicrosoftDocs/office-docs-powershell#6453]
We are trying to enable the ability for guest participants to use the "call me at" feature when joining our Teams meetings. However, it appears that the parameter for this in the Set-CsTeamsMeetingPolicy cmdlet cannot be used. The documentation for this parameter says `[!NOTE] This parameter is temporarily disabled.`

How can we allow guests joining our Teams meetings to dial out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18b9baa8-da13-a24f-af31-91d63de13f08
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @ThePangy how are you?
The note [was added recently](https://github.com/MicrosoftDocs/office-docs-powershell/pull/5570).
I checked and still applies.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ThePangy Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ThePangy** [comment]
Hi @get-itips , @yogkumgit , appreciate the feedback. My question wasn't really on the documentation but on the functionality. We want this parameter set to $true so we have the functionality of our guests/anonymous users being able to dial out for audio. How can we enable this functionality if the cmdlet parameter is disabled?

**Comment by get-itips** [comment]
Hello @ThePangy afaik the feature is still in the works.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ThePangy Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
