### ISSUE TITLE
Template option in preview not exists

### ISSUE THREAD

**Issue by dreamMB** [MicrosoftDocs/office-docs-powershell#6460]
Hello, installing 1.1.3-preview module do not offer the Template option as per described in the document.

-Template: Note: this parameter is not supported in our 1.0 PowerShell release, only in Preview.
If you have an EDU license, you can use this parameter to specify which template you'd like to use for creating your group. Do not use this parameter when converting an existing group.

Is there any way to obtain that feature soon?

![image](https://user-images.githubusercontent.com/7676776/91960654-782ea480-ed0a-11ea-894c-5b1afb3891f2.png)

**Comment by dariomws** [comment]
Hi @dreamMB, thank you for your feedback and help us to improve docs.microsoft.com.

I tested it and seems that the parameter is available in the preview version:
![image](https://user-images.githubusercontent.com/33589238/92407818-17400b80-f112-11ea-8ce0-5bba3331dd9b.png)

More related issues:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/6373
https://github.com/MicrosoftDocs/office-docs-powershell/issues/6323
https://github.com/MicrosoftDocs/office-docs-powershell/issues/6106

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @dreamMB Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
