### ISSUE TITLE
Set-Team - MailNickname does not work properly

### ISSUE THREAD

**Issue by RemzoozmeR** [MicrosoftDocs/office-docs-powershell#6461]
I have been playing around with changing names and e-mail addresses on Teams. I have used the following: 

Set-Team -GroupId "ID" -DisplayName "New name" -MailNickname "New e-mail name"

Changing the name of the Team works just fine, it get`s changed in the group view for M365 admin center, the Team itself changes name and the SharePoint site changes name. The SharePoint site name change takes a bit of time, but it gets there. 
The only thing that does not change name, is the mail nickname. This stays the same. 

No error messages are appearing when running this command. 

I have been troubleshooting this and found out that I am able to send an e-mail to the old e-mail nickname, but not the new one. I have also been in the Admin Center for groups, and I am not able to see that the name has changed nor that there is an alias. Same issue in Exhange Admin Center. 

I have also waited for over one hour, and still no change. 

So it seems like the -MailNickname part is not working. 

I have found a workaround, that is to use Connect-ExhangeOnline and Set-UnifiedGroup -PrimarySmtpAddress - But I think that the one for Set-Team should be doing this, or am I wrong here? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd6bccff-1bef-c88c-ff70-2ccdfb48ecc0
* Version Independent ID: 01f33478-352d-c7ae-0c49-784fa1c1fd67
* Content: [Set-Team (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/set-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-Team.md)
* Service: **teams-powershell**
* GitHub Login: @serdarsoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @RemzoozmeR 
Thanks for your feedback.
I could reproduce what you said here. I'll try to pass this information along to the team.

**Comment by get-itips** [comment]
Hello @RemzoozmeR 
I managed to get some info from the team.
Using 1.1.9-preview, the `-MailNickName` parameter was honored and I could change the mail nickname, probably it will be in the next GA version of the module.
Hope this info helps you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @RemzoozmeR Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
