### ISSUE TITLE
Obsolete

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#6462]
Looks like this should be added to the documentation:
WARNING: The command 'Get-PnPAccessToken' is obsolete. Use Get-PnPGraphAccessToken instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa98588-07ef-34d7-c358-d2e4cc163b75
* Version Independent ID: 56124b45-0cec-6c38-227f-6b344909ce5a
* Content: [Get-PnPAccessToken (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpaccesstoken?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPAccessToken.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPAccessToken.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @danmyhre Dan, how are you?
Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @danmyhre Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
