### ISSUE TITLE
Update WorkflowTemplate property description

### ISSUE THREAD

**Issue by rsoakford** [MicrosoftDocs/office-docs-powershell#6465]
On [https://docs.microsoft.com/en-us/powershell/module/exchange/New-MigrationBatch](https://docs.microsoft.com/en-us/powershell/module/exchange/New-MigrationBatch), the property description for WorkflowTemplate says "The WorkflowControlFlags parameter . . ." - can this please be corrected/updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb26814-0698-3b82-c7cc-7150d1255fe3
* Version Independent ID: 47ce5d33-5483-8c8e-2aa2-532178bf466a
* Content: [New-MigrationBatch (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/New-MigrationBatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rsoakford, I fixed it. But in the future, you, too can make simple updates like this without opening a GitHub issue first. For instructions, see  <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
