### ISSUE TITLE
Module not available for running from different script

### ISSUE THREAD

**Issue by tegnatomm** [MicrosoftDocs/office-docs-powershell#6466]
I have a program that is used for creating Content Searches. Trying to get this to work for MFA. 

When the operation is ran from the program it calls a ps1 file and run the Connect-IPPSSession command it fails saying the module is not loaded. This is true for any command from this module.

When I run PS as an **admin** and use the Get-InstalledModule command I get:
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.0.1      ExchangeOnlineManagement            PSGallery            This is a General Availability (GA) release of Exchange Online PowerShell V2 module....

When I run PS as any other user and run the Get-InstalledModule command I get the same thing.
So I know that I have this module loaded and installed successfully.

If I use the PS ISE and run the script I am calling from my program from any user it runs just fine.

Now, here is the kicker, if I leave the PS session window open from when the program operation opens it and try the Get-InstalledModule command it cannot be found.  Nor can I import the module by name, path, even trying the loading the Microsoft.Exchange.Management.ExoPowershellModule.dll.  Nothing allows this module to load from this PS session

This sounds like some bug to me.  If this is not a bug then how do you load this module to work.

Thanks,
Tom
![ExchangeOnlineManagement](https://user-images.githubusercontent.com/70703390/92120192-be493e00-edc6-11ea-9099-5a7eacb906a7.JPG)

**Comment by dariomws** [comment]
Hi @tegnatomm, thank you for your feedback and help us to improve docs.microsoft.com.

Here we are limited to documentation issues and improvements. If you think that there is something to update or improve in the following article please let me know:
https://docs.microsoft.com/powershell/exchange/connect-to-scc-powershell

If you need more assistance, I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @tegnatomm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
