### ISSUE TITLE
Get-SiteMailbox still works online

### ISSUE THREAD

**Issue by JimKCode** [MicrosoftDocs/office-docs-powershell#6467]
The first paragraph is wrong. Site mailboxes were NOT removed from Exchange and the cmdlets still work in online. Please delete the paragraph because we've received an inquiry from a confused customer.

"This cmdlet is available only in on-premises Exchange. Site mailboxes were removed from Exchange Online and SharePoint Online in 2017."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ef53ffe-687c-1f27-d06c-2eedab6b56cd
* Version Independent ID: cab20afc-b175-84e6-9701-b7a30c1ac6e2
* Content: [Get-SiteMailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-sitemailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-SiteMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-SiteMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JimKCode, fixed.

Thanks for the feedback.

Closing
