### ISSUE TITLE
Filter parameter and its filtering syntax - no result for LIKE

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#6477]
Hello,

"The Filter parameter uses the same filtering syntax that is used by the Where-Object cmdlet."
First of all, think you for this switch, it is a time-saver. My search with "Where-Object" runs a little over 5 mins, whereas the Filter is finished in under 30s!

This is all great, but it only works for **-EQ** for me. **-LIKE** is not as successful

`Get-CsOnlineUser | Where-Object LineURI -Like "*$Number*"`
This returns an Object as my **$Number** is specified as part the LineURI string.

`Get-CsOnlineUser -Filter { LineURI -like "*$Number*" } `
This does **not** return anything, just finishes immediately.

Is -LIKE implemented for Filtering?
I had a quick look at Get-AzureADUser, and there the Filter is implemented as an **oData v3.0 filter statement** (which does not have LIKE, sadly...)

Thank you,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DEberhardt how are you?
This was discussed recently, please see [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/6035#issuecomment-651406576), that is why Example 6 was added.
Thank you for your feedback!

**Comment by DEberhardt** [comment]
Hello,

thank you. Example 6 is helpful when it comes to values in variables, though I do think this worked for me in my script. Will test :)

However, the LIKE operator was never mentioned anywhere. Will try output when adhering to the example and let you know my findings.

Thanks,
David

**Comment by get-itips** [comment]
@DEberhardt Ok David, let me know how it goes!

**Comment by DEberhardt** [comment]
Success! - Example 6 also holds for the Like operator :+1: 

`$filterString = 'LineURI -like "*{0}*"' -f $Number`

`Get-CsOnlineUser -Filter $filterString | Select UserprincipalName,LineURI`


Cheers!

**Comment by get-itips** [comment]
Thanks for returning and sharing your results @DEberhardt David!
