### ISSUE TITLE
-WhatIf Switch on New-ComplianceSecurityFilter

### ISSUE THREAD

**Issue by scottclarke1** [MicrosoftDocs/office-docs-powershell#6480]
Hi Guys

The -WhatIf parameter on `New-ComplianceSecurityFilter` doesn't work. I've just executed a command with the switch specified and rather simulating the result, the actual filter was created!

Thanks,

**Comment by dariomws** [comment]
Hi @scottclarke1, thank you for your feedback and help us to improve docs.microsoft.com.

It's well known and documented that in every Security & Compliance Center PowerShell cmdlet the Whatif switch doesn't work.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @scottclarke1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
