### ISSUE TITLE
when i run this command on education office 365 , it doesnt delete the team from team client application

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/office-docs-powershell#6481]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbc44a5-3c1b-f4b6-f01c-59c3533ea357
* Version Independent ID: 3bea8b08-ff9a-a7c3-bfbf-1e482982b09e
* Content: [Remove-Team (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/remove-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Remove-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Remove-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @jeffangama Jeff, how are you?
It could take a while to reflect the team removal, please can you check if you are running the latest GA PowerShell module, currently on 1.1.4 version.
If you still face issues please open a support ticket directly from your tenant. Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @jeffangama Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jeffangama** [comment]
indeed it took some time to remove. It works as expected removing the class / group. For some users the teams are still visible. I've a ticket on going with microsoft. Thank you for your answer
