### ISSUE TITLE
Submit-PnPSearchQuery not allowing 2 field as SortList

### ISSUE THREAD

**Issue by pratikgupta2** [MicrosoftDocs/office-docs-powershell#6484]
-SortList is not working with 2 parameter :

$sortlist=@{RefinableInt00='ascending' ; RefinableDate01='descending'}
Submit-PnPSearchQuery -Query 'Title:New' -MaxResults 50 -TrimDuplicates $false -SelectProperties 'Title' -SortList $sortlist

While its wokring just fine for : 

$sortlist=@{RefinableInt00='ascending'}
Submit-PnPSearchQuery -Query 'Title:New' -MaxResults 50 -TrimDuplicates $false -SelectProperties 'Title' -SortList $sortlist

**Comment by get-itips** [comment]
Hello @pratikgupta2 how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @pratikgupta2 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
