### ISSUE TITLE
Set-SPOTenant EnableAutoNewsDigest Parameter

### ISSUE THREAD

**Issue by solarfusionuk** [MicrosoftDocs/office-docs-powershell#6491]
According to MC215356, it should be possible to disable auto digest email at a tenant level via:
_Set-SPOTenant -EnableAutoNewsDigest $false_

Running this command gives the following error:
Set-SPOTenant : A parameter cannot be found that matches parameter name 'EnableAutoNewsDigest'

I have updated to the latest SPO PowerShell module version 16.0.20414.12000

**Comment by get-itips** [comment]
Hello @solarfusionuk 
Had no issues at all using that parameter on that version of the module

![image](https://user-images.githubusercontent.com/36666927/93350596-0c623680-f7f6-11ea-9c68-18229df5f6e6.png)

Please be sure that you have installed only one and the most updated version of the module.

**Comment by solarfusionuk** [comment]
Hi, 

Thanks for the info. I did indeed have multiple versions installed:

![image](https://user-images.githubusercontent.com/36865013/93437191-96c49c00-f8c3-11ea-8bfb-f2e42e009f3d.png)

The last one was an MSI install so needed to be uninstalled via control panel:

![image](https://user-images.githubusercontent.com/36865013/93437262-b065e380-f8c3-11ea-9b43-6c7afe0c1e18.png)

Then re-installed the new version:
![image](https://user-images.githubusercontent.com/36865013/93437758-413cbf00-f8c4-11ea-8677-ef4c687f8adf.png)

(Had some issues installing the new version, see: https://www.sharepointdiary.com/2019/02/import-module-could-not-load-type-microsoft-sharepoint-administration-designpackagetype-from-assembly.html)

I was then able to run: _Set-SPOTenant -EnableAutoNewsDigest $false_
