### ISSUE TITLE
Error - the site template is not supported for this operation

### ISSUE THREAD

**Issue by robertafreese** [MicrosoftDocs/office-docs-powershell#6492]
I am trying to enable the modern communication look on a site, and the error is not one covered in the documentation,

Enable-SPOCommSite : This action cannot be completed because the site template is not supported for this operation.
Select a compatible template: STS#0,EHS#1 . For more information, see https://spo.ms/EnableCommSite.

The site was created recently using the Team template but the customer wants to use full width sections and top site menu as with the communications template without provisioning a new site and moving all content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64aa60ad-9698-4926-1f9b-f441ae354a20
* Version Independent ID: 4c7ea433-77d3-22c9-9931-07ba83d0baca
* Content: [Enable-SPOCommSite (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Enable-SPOCommSite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @robertafreese How are you? Hope you are doing great.
The article currently says:

> Use this cmdlet to enable the modern communication site experience **in classic team sites**.

Which is essentially what the error is telling.

Hope this clarifies it.

Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @robertafreese Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
