### ISSUE TITLE
16.0.20414.12000 has the compatibility issue with redistributable SharePoint Client Components SDK 

### ISSUE THREAD

**Issue by takawazo** [MicrosoftDocs/office-docs-powershell#6494]
If redistributable SharePoint Client Components SDK has been installed when SharePoint Online management shell is installed, PowerShell will fail to load the assembly during the launch after the installation.  As a result, SPO management shell can't be used.
Product's recommendation is different, but it is worth noted that 16.0.20414.12000 has the compatibility issue.
Workaround is to delete the above SDK.
https://www.microsoft.com/en-us/download/details.aspx?id=42038

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b23d72-33ed-a6a1-a442-a5e5cf039f9f
* Version Independent ID: 4247cf37-3667-2007-7251-46ed80f58ef5
* Content: [Get started with the SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @takawazo Takahiro, how are you?
Will propose adding a note to the article about this. Thanks
