### ISSUE TITLE
Type TeamsAppPermissionPolicy not enabled

### ISSUE THREAD

**Issue by PhilipHaglund** [MicrosoftDocs/office-docs-powershell#6496]
I know it is not documented anywhere but we are really missing the possibility to assign TeamsAppPermissionPolicy for a target group using New-CsGroupPolicyAssignment.
Is the feature enabled in the TAP so we should contact our TAM for enablement or is it a planned feature update?
```powershell
New-CsGroupPolicyAssignment -GroupId $Group.ObjectId -PolicyName "Contoso - Approved Standard Apps" -PolicyType TeamsAppPermissionPolicy
```
![image](https://user-images.githubusercontent.com/14297750/92702572-a850f580-f351-11ea-9f93-95e980868b4c.png)

**Comment by get-itips** [comment]
Hello @PhilipHaglund Philip, how are you?
The list of supported policies is constantly updated, and probably `TeamsAppPermissionPolicy` will be added on the future. Sorry but I do not have more precision.
I checked and couldn't still assign it both using 1.1.6 GA Version and 1.1.5-preview version.
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @PhilipHaglund Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
