### ISSUE TITLE
Example Two.... description confusing

### ISSUE THREAD

**Issue by jadesolis** [MicrosoftDocs/office-docs-powershell#6498]
"Get-CsTeamsMeetingPolicy -Identity SalesPolicy
In Example 2, Get-CsTeamsMeetingPolicy is used to return the per-user meeting policy that has an Identity SalesPolicy."

I don't think the description matches the sample command snippet. The example returns all the parameters of the Teams Meeting Policy called "SalesPolicy", not return the per-user that has a Teams Meeting Policy called "SalesPolicy"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf19cb0-37fa-e1a4-20aa-5fe2c23d600e
* Version Independent ID: 6fa9a9b5-024b-677b-6c0b-3dba1c03602f
* Content: [Get-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @jadesolis how are you?
The "per user" here refers to the fact that these policies are assigned at per user level. The "per user" is a adjective of the policy in this case.
Hope this clarifies it to you. Thanks

**Comment by jadesolis** [comment]
Hello,
Thanks but I stand with my critique. The "per user" is a adjective has little bearing with the example context. Why not just describe it as it is, which is an example that returns all the parameters of the Teams Meeting Policy called "SalesPolicy

**Comment by get-itips** [comment]
Hello @jadesolis I created a Pull Requests adding your proposal to the article, however I am afraid it was not accepted by the team of reviewers. Thanks for your feedback and I encourage you to do the same in the future.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @jadesolis Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
