### ISSUE TITLE
Example for Type ExternalPstn and more questions :)

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#6502]
Hello,

may I query a few things please:

1.  Example 2 - Should this not be of the type ExternalPstn? (as it is a Phone Number?)
2.  ExternalPstn - How do I query this entity - in (Get-CsAutoAttendant).Operator reveals an object with the Type and an Id. If this is a PhoneNumber, what is the Object I need to target?
3.  Are there limitations on where Transcription can be enabled or is this available for all Object Types?
4.  Identity "Only PSTN numbers that are acquired and assigned through Skype for Business Online are supported." Does this statement still hold true?
5.  Can I get some clarification for HuntGroup, OrganizationalAutoAttendant and ApplicationInstance please?
ApplicationInstance refers to a ResourceAccount for either a CQ or an AA. What are HuntGroup and OrganizationalAutoAttendant for (and how would I query them?

Thank you,
David

EDIT: Changed - to numbers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 414be5d8-a999-2d93-c6e8-a60e6763eb7a
* Version Independent ID: 9dec1f94-908b-0992-c986-084449965df0
* Content: [New-CsAutoAttendantCallableEntity (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csautoattendantcallableentity?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DEberhardt 

1.  Will propose adding this to the article., thanks for noticing.
2. 
![image](https://user-images.githubusercontent.com/36666927/93629359-65240180-f9a5-11ea-84da-2de48924544b.png)

3. "Email transcription is only supported with shared voicemail callable entities", will propose adding this to the article.

4. Will try to get more information about this

5. As far as I know, Org AA were the first version of AA, and I think they are retired now.

**Comment by DEberhardt** [comment]
Hello Andres,
thank you for your response. Clarity around #1 and #3 is very appreciated :)

For #2, I was asking for a GET-Command that I could run against the Object to verify its validity
User (Get-AzureAdUser, Get-CsOnlineUser), ApplicationEndPoint (Get-CsOnlineApplicationEndPoint), etc.
Is ExternalPstn just that, a String, i.E. a Tel URI matching the pattern "^tel:\+\d"? (if so, I am good)

For #5, I think I can drop HuntGroup and OrgAutoAttendant then from my list?


Background: I am writing on a Script to create Auto Attendants with one command (New-TeamsAutoAttendant, Module TeamsFunctions) with default settings, an Operator (where I need that Callable Entity amongst other things) and a default Schedule.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and updating the documentation with PR. @DEberhardt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
