### ISSUE TITLE
Spelling correction in example (TeamPicture)

### ISSUE THREAD

**Issue by harp365** [MicrosoftDocs/office-docs-powershell#6504]
Set-TeamPicture -GroupId 2f162b0e-36d2-4e15-8ba3-ba229cecdccf -ImagePath c:\Image\TeamPictire.png

Needs to be:

Set-TeamPicture -GroupId 2f162b0e-36d2-4e15-8ba3-ba229cecdccf -ImagePath c:\Image\TeamPicture.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9785a323-0f76-2cc5-8ccd-da9b83c29973
* Version Independent ID: 5629326e-995c-4494-811f-80a0bb042233
* Content: [Set-TeamPicture (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-teampicture?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-TeamPicture.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-TeamPicture.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Thanks for reporting @harp365
