### ISSUE TITLE
Error in description of Add-PnPTeamsUser

### ISSUE THREAD

**Issue by abeggled** [MicrosoftDocs/office-docs-powershell#6505]
Add-PnPTeamsUser adds a user to a Teams and not a channel to a Teams. It looks like a copy/paste error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4bab214-5d6c-1dbd-a4be-ac1227135753
* Version Independent ID: da5bb93f-e562-844d-2e08-427c6321ee35
* Content: [Add-PnPTeamsUser (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpteamsuser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTeamsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTeamsUser.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @abeggled  how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @abeggled Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
