### ISSUE TITLE
AllowNdiStreaming

### ISSUE THREAD

**Issue by ivanja81** [MicrosoftDocs/office-docs-powershell#6511]
-AllowNDIStreaming
This parameter is reserved for internal Microsoft use.

This is i believe incorrect. It's not only for Microsoft internal use. NDI is supported and this policy is valid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @ivanja81 Ivan, how are you?
Thanks for reporting.

**Comment by ivanja81** [comment]
Hi,

Fine thank you.
