### ISSUE TITLE
ExchangeEnvironmentName to connect to Exchange Online PowerShell in sovereigns cloud

### ISSUE THREAD

**Issue by ZelMul** [MicrosoftDocs/office-docs-powershell#6513]
To connect to sovereign environment -ExchangeEnvironmentName parameter is needed.
Example for GCC High: 
`Connect-ExchangeOnline -Credential $UserCredential -ShowProgress $true -ConnectionUri https://outlook.office365.us/powershell-liveid/ -ExchangeEnvironmentName O365USGovGCCHigh`

[Information can be found here](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps) but could be reflected on this page in the examples of commands to connect.

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ZelMul, I think your example requires ExchangeEnvironmentName because you didn't use AzureADAuthorizationEndPointUri. If you use ConnectionUri and AzureADAuthorizationEndPointUri in the command, you should be able to connect without using ExchangeEnvironmentName.

Can you confirm?

**Comment by ZelMul** [comment]
@chrisda Yes this also work, I was following the section "Without using MFA" which doesn't mention AzureADAuthorizationEndPointUri nor ExchangeEnvironmentName and thus didn't work for me.

**Comment by chrisda** [comment]
@ZelMul, interesting. I thought AzureADAuthorizationEndPointUri was only required for multi-factor authentication (MFA). But you're saying it's required for non-MFA connections?

But I have a new angle for you: If you use the ExchangeEnvironmentName parameter, you don't need to use the ConnectionUri or AzureADAuthorizationEndPointUri parameters. That parameter has only recently been fully tested and approved in the EXO V2 module, so I'm updating the MFA and non-MFA connection instructions to use it exclusively.

Thanks for the feedback.

Closing
