### ISSUE TITLE
Group ID is not allowed in the property ModernGroupLocation of the command New-LabelPolicy

### ISSUE THREAD

**Issue by mbratukha** [MicrosoftDocs/office-docs-powershell#6514]
In the [docu](https://docs.microsoft.com/en-us/powershell/module/exchange/new-labelpolicy?view=exchange-ps#parameters) is written, that it's possible to use GUID as a value to the property `ModernGroupLocation` of the command `New-LabelPolicy`.
I'm getting the following exception when try to call it with a valid GUID of an existing group:
```powershell
The group 'e05952e1-fcd2-4704-9d5b-ced704cea1b9' is not a valid smtp address. Alias is not allowed in ModernGroup for LabelPolicy Commandlet.
    + CategoryInfo          : NotSpecified: (:) [New-LabelPolicy], InvalidGroupSmtpAddressException
    + FullyQualifiedErrorId : [Server=DB3EUR04WS013,RequestId=5884b881-97a7-4815-a282-ff4c5ed33122,TimeStamp=15.09.2020 12:24:52] [FailureCategory=Cmdlet-InvalidGroupSmtpAddressException] 805ADFF6,Microsoft.Office.CompliancePolicy.Tasks.NewLabelPolicy
    + PSComputerName        : eur04b.ps.compliance.protection.outlook.com
```

Is there any way to use GUIDs as written in docu?

**Comment by dariomws** [comment]
Hi @mbratukha, thank you for your feedback and help us to improve docs.microsoft.com.

I tested it and experienced the same behaviour. I'm going to apply an update to reflect this, let's see if it gets approval.

**Comment by mbratukha** [comment]
@dariomws thank you for quick response!

Could it be a feature request that it's possible to use also GUIDs for this command?
E.g. the command `New-RetentionCompliancePolicy` allows to do that.
It would be more consistent for `ExchangePowerShell` module.

**Comment by dariomws** [comment]
Hello @mbratukha, thanks for your feedback. 

For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/. There, your suggestion will reach the product team.

**Comment by mbratukha** [comment]
@dariomws thank you.

**Comment by mbratukha** [comment]
For those who would face the same requirements, there is a ticket here: https://feedbackportal.microsoft.com/feedback/idea/6c851739-eb88-ec11-a81b-0022484c51ef
