### ISSUE TITLE
Re-check examples

### ISSUE THREAD

**Issue by zumiek** [MicrosoftDocs/office-docs-powershell#6529]
Some1 needs to re-check the examples, they are not currently correct and doesn't correspond to the text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b777fcfe-c7da-0165-d6ac-74fc2db07daf
* Version Independent ID: 12045879-94af-fd90-66a0-8f3db00a579f
* Content: [Get-PnPListItem (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPListItem.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @zumiek 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @zumiek Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by codegard1** [comment]
This seems to be an issue with Github/MSDocs (?) and the way it is parsing the code in those examples. The below text was copy/pasted from https://pnp.github.io/powershell/cmdlets/Get-PnPListItem.html, but on render it changes to the text seen on the page that is the subject of this comment thread. 

> EXAMPLE 5
> Get-PnPListItem -List Tasks -Query "<View><Query><Where><Eq><FieldRef Name='GUID'/><Value Type='Guid'>bd6c5b3b-d960-4ee7-a02c-85dc6cd78cc3</Value></Eq></Where></Query></View>"
> Retrieves all available fields of list items based on the CAML query specified
> 
> EXAMPLE 6
> Get-PnPListItem -List Tasks -Query "<View><ViewFields><FieldRef Name='Title'/><FieldRef Name='Modified'/></ViewFields><Query><Where><Geq><FieldRef Name='Modified'/><Value Type='DateTime'><Today/></Value></Eq></Where></Query></View>"
> Retrieves all list items modified today, retrieving the columns 'Title' and 'Modified'. When you use -Query, you can add a clause to retrieve specific columns (since you cannot use -Fields)
