### ISSUE TITLE
OWAAllowUserChoiceOfSigningCertificate and OWASenderCertificateAttributesToDisplay not properly working.

### ISSUE THREAD

**Issue by chrismholmes1** [MicrosoftDocs/office-docs-powershell#6531]
For Exchange Online (Possibly other versions as well), the OWAAllowUserChoiceOfSigningCertificate option does not work if your Certificate Subject Alternative Name (RFC822 Name) email address does not match your OWA Email Address/Proxy Addresses.

In addition, I have tried every combination of OWASenderCertificateAttributesToDisplay with varying OIDs but can not find the correct answer.
Can we get an example added to this page that clearly defines which OIDs are supported?

Now there may be a possibility that the Powershell scripts are working properly, but their is a "miscalculation" on the programming side when it comes to using the SMIME plugins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ee7a9a0-19a7-b7cd-c874-fafa96b61221
* Version Independent ID: 42b0182c-ac1f-c405-8a9c-6bcbde41605f
* Content: [Set-SmimeConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-smimeconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-SmimeConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-SmimeConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @chrismholmes1, thank you for your feedback and help us to improve docs.microsoft.com.

I'm not sure if there is something to update in the article. I think it's better if you check these features with support.
I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

If you conclude with the support that a documentation improvement is requiered, we will certainly update this article with that valuable information.

Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @chrismholmes1 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
