### ISSUE TITLE
Get-TeamsAppInstallation : Error occurred while executing

### ISSUE THREAD

**Issue by MicahHarley** [MicrosoftDocs/office-docs-powershell#6533]
Using 1.1.5-preview, when I pass an UserID, the following error is returned:

Get-TeamsAppInstallation : Error occurred while executing 
Code: UnknownError
Message:
InnerError:
  RequestId: *********************
  DateTimeStamp: 2020-09-17T17:29:05
HttpStatusCode: UnknownError
At C:\Users\*****\Documents\TeamsPowerShell\test.ps1:6 char:9
+ $apps = Get-TeamsAppInstallation -UserId '********-****-****-****-*** ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-TeamsAppInstallation], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeamsAppInstallation

I've tried both a UPN and the UserId GUID returned from Get-TeamUser. Both show same error.

Cmdlet works fine when passing a TeamId.

Hoping to find apps installed in the user only context... i.e. no team installs.
Would be helpful to have require parameters and expected values for them documented.
Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24775e3b-4edb-a43d-2b86-723b648e9e55
* Version Independent ID: b1d4c5a9-783b-8dbd-d669-fe1fa0472167
* Content: [Get-TeamsAppInstallation (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamsappinstallation?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-TeamsAppInstallation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamsAppInstallation.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @MicahHarley 
As the article says this cmdlet is part of the public preview (and you are also as you say, using the public preview)
As the state of that version, the cmdlet may be subject to changes and probably needs adjustments.
I recommend checking [here](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes) to see when this cmdlet goes GA.
Also if you want your request to reach the product team please visit [here](https://microsoftteams.uservoice.com/) we are limited to documentation updates.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @MicahHarley Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
