### ISSUE TITLE
ConnectionUri for GCC-High

### ISSUE THREAD

**Issue by ewillman** [MicrosoftDocs/office-docs-powershell#6536]
Example ConnectionUri parameters are provided in the documentation, including one for that works for both "Microsoft 365 or Microsoft 365 GCC", however, this Uri fails when connecting to a GCCH tenant.  After trial and error I have found that the correct ConnectionUri to connect to the compliance center in GCC-High is https://ps.compliance.protection.office365.us/powershell-liveid/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 945ab2ea-22ae-814f-8898-fe84b7f29870
* Version Independent ID: 5383d152-988d-b1ee-4957-db5fb6213754
* Content: [Connect-IPPSSession (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-ippssession?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-IPPSSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Connect-IPPSSession.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ewillman, 3 weeks ago, I pulled the GCC High and DoD values and added a warning because they didn't work (#6436). Apparently, this was a known issue and easily identified, so they must have fixed it very recently. I added the GCC High and DoD values back.

Thanks for the feedback

Closing
