### ISSUE TITLE
Need for Release Notes: What's Changed

### ISSUE THREAD

**Issue by djtrustgod** [MicrosoftDocs/office-docs-powershell#654]
With each PnP release there is a need for release notes.  Going through source code and pull request to deduce what has changed is not really an option.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3240d3-6a7d-fc4b-62fd-d3a5375d8a4a
* Version Independent ID: 561212df-4dab-92b7-b634-57d53d313c6f
* Content: [PnP PowerShell overview](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* Service: **unspecified**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by nsshommo** [comment]
@VesaJuvonen Please look at this issue.

**Comment by VesaJuvonen** [comment]
PnP PowerShell changes are always covered in our PnP monthly release notes at https://dev.office.com/blogs/pnp-april-2018-update. We have been including all PnP PowerShell changes in our monthly summary for past 3 years and will keep on doing that also in future. You can always also have a look on the changelog.md file at the repository at https://github.com/SharePoint/PnP-PowerShell/blob/master/CHANGELOG.md.

You can follow [OfficeDev](https://twitter.com/OfficeDev/status/983355102017671173), [SharePoint](https://twitter.com/SharePoint/status/983375113453219840) or individuals in social media to get notified of the new documentation and releases. 

If there are some other ideas on where and how the changes should be shared, the input is always welcome. Closing this for now as release notes do exist and have existed for past 3 years.

**Comment by djtrustgod** [comment]
Thanks @VesaJuvonen

**Comment by DeanGross** [comment]
It would be helpful if those release notes were included in the docs.microsoft.com site. This site navigation should have a navigation link to make that content more easily accessed.

**Comment by DeanGross** [comment]
@VesaJuvonen i'm confused, it looks like the analyses has already been done and is available at https://github.com/SharePoint/PnP-PowerShell/blob/master/CHANGELOG.md. I'm just suggesting that the changelog page be linked to https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps so that it shows up in the master table of contents somehow
