### ISSUE TITLE
Get-MigrationBatch - execution as part of script in ISE - doesn't display return

### ISSUE THREAD

**Issue by LukePWilkins** [MicrosoftDocs/office-docs-powershell#6540]
I have the a script, which should initially get the names of the current Migration Batches in EOL migration portal.

A simple code block

cls
get-migrationbatch | select Identity
write-host "these are the migration batchs" 

In my experience, clears the screen, pauses and then displays the text. The return from get-migrationbatch isn't displayed
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d404737-9599-a21f-41f1-d31a0baa4fe6
* Version Independent ID: 440c9461-7510-e9bd-6d6c-ddd8fa2d06b4
* Content: [Get-MigrationBatch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @LukePWilkins, thank you for your feedback.

For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @LukePWilkins Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
