### ISSUE TITLE
There is no information about usagelocation

### ISSUE THREAD

**Issue by Cypher-Skif** [MicrosoftDocs/office-docs-powershell#6541]
[Enter feedback here]
Dear Team, I can't find here any mentions related with usage location. Please add information which propertyset I need to choose to see usagelocation property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9145396-cc72-6e54-4204-6867397e67ea
* Version Independent ID: ca86d515-e4d3-ce0f-11e3-87ddfda38b75
* Content: [Property sets in Exchange Online PowerShell V2 cmdlets](https://docs.microsoft.com/en-us/powershell/exchange/cmdlet-property-sets?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/cmdlet-property-sets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/cmdlet-property-sets.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Cypher-Skif, the property sets are not meant to include all of the output properties from a given cmdlet. Many (most?) of them are purposely not included.

If the property you want isn't isn't available in a property set, then use the Properties parameter (for example, `-Properties UsageLocation`).

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @Cypher-Skif Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
