### ISSUE TITLE
Maybe you can add a link here to how to Change existing rights.

### ISSUE THREAD

**Issue by Tolle3000** [MicrosoftDocs/office-docs-powershell#6542]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1a893c8-66de-1f8a-f8d2-aa573379e778
* Version Independent ID: 1c32c637-d003-820c-594f-a9adc9c353d9
* Content: [Add-MailboxFolderPermission (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/add-mailboxfolderpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @Tolle3000, thank you for your feedback and help us to improve docs.microsoft.com.

I think it's a good idea, I'm updating the article to add all the related cmdlets.
