### ISSUE TITLE
Template EDU_Class failing on preview

### ISSUE THREAD

**Issue by dreamMB** [MicrosoftDocs/office-docs-powershell#6543]
#6141 
## Document Details

Hi, we are running 1.1.5-preview module of MicrosoftTeams.
When trying to use the Template switch with the following command, the Team creation fails:
Get-UnifiedGroup "DEMOCLASSROOM_XP_TestClass_122_ALL" | % {New-Team -GroupId $_.ExternalDirectoryObjectId -Template "EDU_Class"}

% : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:53
+ ... _122_ALL" | % {New-Team -GroupId $_.ExternalDirectoryObjectId -Templa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ForEach-Object], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.ForEachObjectCommand

Running the same but without the Template switch, completes correctly:

Get-UnifiedGroup "TSTESSAIM_XP_TestClass_121_ALL" | % {New-Team -group $_.ExternalDirectoryObjectId}

GroupId                              DisplayName        Visibility  Archived  MailNickName       Description
-------                              -----------        ----------  --------  ------------       -----------
8b26f432-21dc-4812-b0e0-2d6cd193cbdf TSTESSAIM_XP_Te... Private     False     TSTESSAIM_XP_Te...

---

Is there any workaround for this? maybe release 1.1.3-preview to support the Template?

Thanks.
⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fff5e98-436e-f79c-e176-767f8de772e5
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by GaelBSB** [comment]
Yes, I confirm this is a real problem. We are lucky to have kept an environment with "poshtestGallery 1.0.18". 

But we would like to be able to evolve our version and benefit from all the latest advances without having to juggle between 2 versions.

Please release the "template" feature or put it on preview
Gael

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @dreamMB Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
