### ISSUE TITLE
Add-TeamChannelUser not recongnised

### ISSUE THREAD

**Issue by DerekSomerville** [MicrosoftDocs/office-docs-powershell#6549]
[Enter feedback here]
This function is not recognised and is not displayed when one does "get-command -Module microsoftteams". I have version 1.1.6 installed and I uninstalled and reinstalled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd91d571-ca88-5766-2666-d6a4d34cdbed
* Version Independent ID: 2481b258-b593-e323-90f0-e9ca6e7797bf
* Content: [Add-TeamChannelUser (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dbarrass** [comment]
Dear yogumgit,
I have exactly the same issue, been struggling with it all weekend, many reboots and attempt to fix it.
Here's a screenshot of my get-command -Module microsoftteams
I don't think Add-TeamChannelUser is the only cmdlet missing either
![missing cmdlets](https://user-images.githubusercontent.com/71651582/93777576-e46f3a80-fc1c-11ea-86f5-0a3cb0caa25e.PNG)

**Comment by cardenp** [comment]
Please, how do I get a version, beta or otherwise of the cmdlet Add-teamChannelUser. Ppl seem to have access to it from other fora. I have to add 240 ppl to 40 channels. Manually doing it makes MSTeams not fit for purpose.

**Comment by cardenp** [comment]
I fixed it. I uninstalled the current MSTeams module and ran this "Install-Module -Name MicrosoftTeams -RequiredVersion 1.1.3-preview -AllowPrerelease". Closed Powershell and reopened , it worked.

**Comment by DerekSomerville** [comment]
Hi cardenp, I tried this but it does not appear to work for me. I tried the below to uninstall, but I am not sure it worked.
Uninstall-Module MicrosoftTeams

**Comment by cardenp** [comment]
> Hi cardenp, I tried this but it does not appear to work for me. I tried the below to uninstall, but I am not sure it worked.
> Uninstall-Module MicrosoftTeams

This is the command I used, Derek "Uninstall-Module -Name MicrosoftTeams"

**Comment by dbarrass** [comment]
Hi Cardenp 
uninstall went ok (try it as Administrator immediately after restarting the shell)
install worked, I had to add -allowClobber for it to work
Restart shell (as admin)
and OMG it worked. I'd tried this with version 1.1.4 before and that didn't work so I did not do this with much hope.
Updating the microsoftTeams module made it disappear again
and now I can't get it back even if I repeat the steps NOOOOOOOO

**Comment by dbarrass** [comment]
Ok got it back
the secret it to uninstall (in admin) close powershell immediately - this was the secret as otherwise the uninstall didn't complete
Install v1.1.3 (as admin)
Close powershell again
reopen powershell (as admin) and there the command was, along with several other previously missing commands

**Comment by get-itips** [comment]
Hello @DerekSomerville how are you?

You can find more information on the difference between Public Preview and GA [here](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes). Specifically, the cmdlet you are trying to use is still part of the Public Preview version.
Also here is the instructions to install a [specific version](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install).
Hope this information helps you,

**Comment by dbarrass** [comment]
so what you're saying is that it's in 1.1.3-preview and 1.1.5-preview, but not the normal download.
I have to say Microsoft are doing an appalling job at making things clear. I have wasted literally days on this.
Anyway -  thank you for pointing this out :-) that's helped a lot
David

**Comment by DerekSomerville** [comment]
Great thanks all. I got the uninstall to work for me with -Force. I now have it working. Thanks for everyone's help.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DerekSomerville Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
