### ISSUE TITLE
Incomplete?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6552]
There is a "." under Applies to: SharePoint Online
So I believe that means it's incomplete?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7000bfcf-95b0-584e-1a42-b5d5202d82e1
* Version Independent ID: 00e03653-1983-a0ba-69c7-61ad80b4245a
* Content: [Set-SPOBrowserIdleSignOut (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spobrowseridlesignout?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBrowserIdleSignOut.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBrowserIdleSignOut.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for reporting @hwkwicre
