### ISSUE TITLE
Would it be helpful to add other site templates too?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6553]
"Identifies which base template to add the design to. Use the value 64 for the Team site template, and the value 68 for the Communication site template."
Maybe add a link or something to values of other templates, in case some admins would like to use other (classic) site templates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2abd7130-5fce-bda2-d84f-2a9640584962
* Version Independent ID: 7dea06e7-3411-8b9b-8eea-af3cbc4c3f43
* Content: [Add-SPOSiteDesign (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spositedesign?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteDesign.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteDesign.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for reporting @hwkwicre currently there is no article that mentions all the Template IDs, but probably, it will be included in the link I am adding to the article thru a pr. Thanks
