### ISSUE TITLE
 Specifies the start time

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6554]
Specifies the start time in UTC to search for monitoring errors (for example, 01032011:12:00).
This 01032011:12:00 isn't very clear, is it day/month/year/time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ce9c6a4-855b-77c4-422e-d7cce055c650
* Version Independent ID: 7a04945a-61f4-d2a8-7ed0-9d2a64bfaa2e
* Content: [Get-SPOAppErrors (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spoapperrors?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOAppErrors.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOAppErrors.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for reporting @hwkwicre
