### ISSUE TITLE
Command fails to update .pnp files

### ISSUE THREAD

**Issue by stukkendfc** [MicrosoftDocs/office-docs-powershell#6555]
This command does not have the desired effect on a .pnp file. Only when the extension is .xml does it include the folders. I've checked the modified date and time of an existing .pnp file, but it does not change after running the command. So in essence the example in the documentation seem to be incorrect, or I am doing something wrong.

**Comment by get-itips** [comment]
Hello @stukkendfc can you kindly link here the article you are referring to? Thanks

**Comment by stukkendfc** [comment]
> Hello @stukkendfc can you kindly link here the article you are referring to? Thanks

Hi, I refer to the documentation found here: 
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnplistfolderstoprovisioningtemplate?view=sharepoint-ps

When trying to update .pnp file, nothing happens. When trying to update .xml file, success.

**Comment by get-itips** [comment]
Hello @stukkendfc 
Oh I see you refer to a PnP cmdlet.
Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback or reply to your inquiry.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @stukkendfc Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
