### ISSUE TITLE
Typo: CVS instead of CSV

### ISSUE THREAD

**Issue by onephilote** [MicrosoftDocs/office-docs-powershell#6559]
This article says "CVS" instead of "CSV" in 5 locations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa414bb-ab53-b465-8783-cde05d7ac5e4
* Version Independent ID: f354bbc9-71c9-15b5-be86-a9df743e3df4
* Content: [Import-SPEnterpriseSearchThesaurus (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/Import-SPEnterpriseSearchThesaurus?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Import-SPEnterpriseSearchThesaurus.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Import-SPEnterpriseSearchThesaurus.md)
* Product: **sharepoint-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Thanks for reporting @onephilote
