### ISSUE TITLE
Missing -Name for the Import Module Command

### ISSUE THREAD

**Issue by systemsmaven** [MicrosoftDocs/office-docs-powershell#6565]
[Hi, You are missing the -Name part of the Import-Module command.  Your example reads: Import-Module ExchangeOnlineManagement

It should be "Import-Module -Name ExchangeOnlineManagement"

I just noticed it after rebuilding my system and having to reinstall all of my PS modules. :)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@systemsmaven, see this [PR](https://github.com/MicrosoftDocs/office-docs-powershell/pull/6390) about the exact same issue.

Name is a positional parameter and isn't absolutely required. I've used the command `Import-Module <ModuleName>` dozens if not hundreds of times over the years.

So are you saying the command doesn't work unless you use the `-Name` qualifier? If so, what are the circumstances?

**Comment by systemsmaven** [comment]
Hi @chrisda 

I just tried it without the -Name on a freshly build Window 10 1909 system.  Running PS as an Administrator and it would not install.  Here's the error:

PS C:\Windows\system32> import-module ExchangeOnlineManagement                                                          
import-module : The specified module 'ExchangeOnlineManagement' was not loaded because no valid module file was found   in any module directory.
At line:1 char:1
+ import-module ExchangeOnlineManagement
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ExchangeOnlineManagement:String) [Import-Module], FileNotFoundExce
   ption
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

It installed after adding -Name without issue.  Also, in this article the -Name is included:
https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-the-exo-v2-module

It's the article right before this article.

Thanks

**Comment by chrisda** [comment]
@chrisda, I just tried it on my (ancient, not fresh) Win 10 v2004 build.

```powershell
PS C:\WINDOWS\system32> Import-Module ExchangeOnlineManagement
PS C:\WINDOWS\system32> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.3      ExchangeOnlineManagement            {Get-EXOCasMailbox, Get-EXOMailbox, Get-EXOMailboxFolderPe...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...
```

So are you trying to install and load the module? Or just load the module?

**Comment by systemsmaven** [comment]
@chrisda Awww that's what I was.  I was doing both installing and loading.  My error... Trying to do too many things at once. :)

**Comment by chrisda** [comment]
@systemsmaven no worries. Interesting find. I'll make some type of note or indication in this and other related topics.

**Comment by systemsmaven** [comment]
@chrisda sounds good!  Have a great day!
