### ISSUE TITLE
LocaleId reference link incorrect

### ISSUE THREAD

**Issue by Muxxx** [MicrosoftDocs/office-docs-powershell#6569]
"
-LocaleId
Specifies the language of this site collection. For more information, see Locale IDs Assigned by Microsoft (https://go.microsoft.com/fwlink/p/?LinkId=242911).
"

This URL does not contain valid Locale IDs for use with the -LocaleId parameter. The LocaleId for English (United States) as per SharePoint Online is 1033, but that link not only doesn't mention a LocaleId, it refers to the Location ID as "0x0409"

The closest Microsoft Reference I could find is here: https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a. I would suggest pointing readers to something like that which refers to values that are going to be accepted by this parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c62bf4a-ac47-96ce-33fb-0d5ea9b178ae
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @Muxxx Stefano,
Thanks for your feedback, I can see that the link you share could be better, will propose thru a PR.
