### ISSUE TITLE
Import-Module wrong, use Install-Module

### ISSUE THREAD

**Issue by brettemery** [MicrosoftDocs/office-docs-powershell#6573]
### 

You say to INSTALL the module run: Import-Module -Name ExchangeOnlineManagement.

That is not correct, it's Run PowerShall As Administrator then run Install-Module -Name ExchangeOnlineManagement

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@brettemery, thanks for the feedback. I updated the topic.

Closing

**Comment by dariomws** [comment]
Hi @brettemery, thank you for your feedback.

I tested it and works without Run as Administrator:
![image](https://user-images.githubusercontent.com/33589238/95252831-eb3ca680-07f3-11eb-9173-fc3ffcdc096d.png)
