### ISSUE TITLE
PARAMVALUE: EncryptionParameters

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6574]
-EncryptionParameters
PARAMVALUE: EncryptionParameters
Can there be more explanations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6318fa57-5e0c-9339-f8d8-4ed6169e1033
* Version Independent ID: f9d39f09-e2bd-2db0-55f8-4510dbbd8810
* Content: [Submit-SPOMigrationJob (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/submit-spomigrationjob?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Submit-SPOMigrationJob.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Submit-SPOMigrationJob.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for your feedback @hwkwicre
