### ISSUE TITLE
Fill Description

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6576]
-Reserved
{{ Fill Reserved Description }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff34ec3c-ad28-7266-223d-9c60cb0486e6
* Version Independent ID: 0be56c12-346c-bc92-b2ad-36b48f8d2589
* Content: [Start-SPOUnifiedGroupMove (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/start-spounifiedgroupmove?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Start-SPOUnifiedGroupMove.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Start-SPOUnifiedGroupMove.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for reporting @hwkwicre
