### ISSUE TITLE
OptimizeDeviceDialling Parameter

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#6577]
Hello,

brushing up my Teams CmdLet knowledge, I now tackle Dial Plans. :)
To fully understand all they have to offer, I found the Parameter OptimizeDeviceDialling which does not have a Description in New-CsTenantDialPlan and Set-CsTenantDialPlan. I never used this switch before, nor did I have to use ExternalAccessPrefix...

I do not know how relevant this switch (and the corresponding ExternalAccessPrefix Parameter) are in Teams, so I did not want to propose a change to the doc just yet.
Set-CsDialPlan (for Skype) has had this description for it:

> Setting this parameter to True will apply the prefix in the ExternalAccessPrefix parameter to calls made outside the organization. This value can be set to True only if a value has been specified for the ExternalAccessPrefix parameter.

May I ask that a decision is made about this parameter, either to add a description or mark it as deprecated if that is truely the case :)

Thank you,
David

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f9dccd1-bc3b-6c14-eb66-2a566a71d94f
* Version Independent ID: 545fa8ce-0abe-4921-04ef-3cd1bf496f24
* Content: [Set-CsTenantDialPlan (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cstenantdialplan?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTenantDialPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTenantDialPlan.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for your feedback @DEberhardt David, will try to clarify thru a pr.
