### ISSUE TITLE
More info?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6591]
Only has PARAMVALUE
Should there be more info?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52bb492-d236-c3cb-212b-b937e397aaad
* Version Independent ID: 01fbd518-06fe-96cf-4a70-12e410107066
* Content: [Get-SPOSiteContentMoveState (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositecontentmovestate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteContentMoveState.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteContentMoveState.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for reporting @hwkwicre
