### ISSUE TITLE
PermanentlyDisable Switch

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/office-docs-powershell#6594]
It has been mentioned that "You can only use this switch on user mailboxes that aren't licensed and aren't on hold". But when we try to run it against a mailbox for whom we have removed the license, We get below error  

Disable-mailbox BiancaP -PermanentlyDisable
The operation couldn't be performed because object 'BiancaP' couldn't be found on 'MWHPR14A004DC12.NAMPR14A004.PROD.OUTLOOK.COM'

If we run this command with user having a license assigned then we get this issue 
Disable-mailbox BiancaP -PermanentlyDisable
Cannot Disable-Mailbox for 'BiancaP' because this user has a valid license.

I know as usual, you might ask us to open a support case, But this behavior is same across all mailboxes and across all the tenants. Can you please ask Engineering team to look into this and update document accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39a8c379-8598-c0e7-fb71-2a20124b9e26
* Version Independent ID: 1c7960eb-3661-e96c-a9d7-18218256d6a1
* Content: [Disable-Mailbox (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/disable-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Disable-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Disable-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @3novsan, thank you for your feedback and help us to improve docs.microsoft.com.

You cannot use it after removed the user's license because in this case, the mailbox is hard-deleted. More information:
https://support.microsoft.com/en-us/help/3158794/no-soft-deleted-mailbox-after-license-removal-in-office-365
https://github.com/MicrosoftDocs/office-docs-powershell/issues/5681
