### ISSUE TITLE
Set-CsTenantMigrationConfiguration not documented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#6599]
Empty article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbd76c9d-146e-776b-66b4-7bf2cd85dbc5
* Version Independent ID: 0d3ef43a-6d07-1e88-deda-8a92300334f0
* Content: [Set-CsTenantMigrationConfiguration (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cstenantmigrationconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTenantMigrationConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTenantMigrationConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for your feedback @shivtorov
