### ISSUE TITLE
Error adding team user to group

### ISSUE THREAD

**Issue by mwolfaardt** [MicrosoftDocs/office-docs-powershell#66]
While trying to add an external user to a group using `Add-TeamUser -GroupId 2928a3db-2d7b-4925-b4fc-6cdd0d66ef12 -Role Member  -User abc@xyz.com`

I receive the following error 
Add-TeamUser : Error occurred while executing 
Code: Request_ResourceNotFound
Message: Resource 'abc@xyz.com' does not exist or one of its queried reference-property objects are not present.
InnerError:
  RequestId: 2449be5c-5d30-48e5-9df5-79e818c9d77d
  DateTimeStamp: 2017-11-28T09:22:18
HttpStatusCode: Request_ResourceNotFound
At line:7 char:1
+ Add-TeamUser -GroupId 2928a3db-2d7b-4925-b4fc-6cdd0d66ef12 -Role Memb ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamUser], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.AddTeamUser

**Comment by kenwith** [comment]
I am not an expert on all the cmdlets (just focused on repo maintaining and subset of cmdlets). It seems like it cannot find the user abc@xyz.com in your tenant. Let's see if anyone else in the community that has more experience with these has experienced this. You can also open a support ticket and they can route this properly.

**Comment by mwolfaardt** [comment]
Thanks Yeah I changed the email, but it will be external guests that I invite

**Comment by ravgupms** [comment]
Currently, Add-TeamUser cmdlet doesn't support adding guest users.

**Comment by kenwith** [comment]
Thanks for the clarification Ravi! Closing this one out.

**Comment by arunpandianj** [comment]
Check your email Ids are valid and the user is exist or not
