### ISSUE TITLE
Unable to run SharePointOnline Module in Azure Function (PowerShell)

### ISSUE THREAD

**Issue by ImHermes** [MicrosoftDocs/office-docs-powershell#6602]
## Error
The SharePointOnlinePowerShell module appears to auto-loaded from the powershell gallery, however it's cmdlets are never made available by default.
Attempting Connect-SPOService returns the error: "The term 'Connect-SPOService' is not recognized as the name of a cmdlet, function, script file, or operable program"

## Expected behavior:
The ability to use Connect-SPOService and other SharePointOnlinePowerShell cmdlets in a PowerShell Azure function.

## Troubleshooting
When preceded by `Import-Module 'Microsoft.Online.SharePoint.PowerShell' -Force`, the response is "The remote server returned an error: (400) Bad Request" (#BadRequestError referenced below).

There is no clear documentation indicating the module's compatibility with Powershell core, Powershell 7 or Azure Functions.

### #BadRequestError 
ERROR: The remote server returned an error: (400) Bad Request.

Exception             : 
    Type       : System.Net.WebException
    Status     : ProtocolError
    Response   : System.Net.HttpWebResponse
    TargetSite : 
        Name          : GetResponse
        DeclaringType : System.Net.HttpWebRequest
        MemberType    : Method
        Module        : System.Net.Requests.dll
    StackTrace : 
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Online.SharePoint.PowerShell.SPOServiceHelper.IsTenantAdminSite(CmdLetContext context)
   at Microsoft.Online.SharePoint.PowerShell.SPOServiceHelper.InstantiateSPOService(Uri url, PSCredential credentials, PSHost host, String authenticationUrl, String clientTag, Boolean forceOAuth)
   at Microsoft.Online.SharePoint.PowerShell.ConnectSPOService.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Message    : The remote server returned an error: (400) Bad Request.
    Source     : System.Net.Requests
    HResult    : -2146233079
CategoryInfo          : NotSpecified: (:) [Connect-SPOService], WebException
FullyQualifiedErrorId : System.Net.WebException,Microsoft.Online.SharePoint.PowerShell.ConnectSPOService
InvocationInfo        : 
    MyCommand        : Connect-SPOService
    ScriptLineNumber : 30
    OffsetInLine     : 1
    HistoryId        : 1
    ScriptName       : ###redacted###
    Line             : Connect-SPOService -Url $spAdmin -Credential $cred

**Comment by get-itips** [comment]
Hello @ImHermes how are you?
Hope you are doing great.
In the article explaining how to get started with the SharePoint Online PowerShell module is specified that it is a **Windows PowerShell module**. Please see here https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/introduction-sharepoint-online-management-shell?view=sharepoint-ps

> The SharePoint Online Management Shell **is a Windows PowerShell module** that you can use to manage SharePoint settings at the organization level and site collection level.

(So AFAIK currently it can not run in Ps Core.)

Thanks, hope this info helps you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ImHermes Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mariussm** [comment]
In PowerShell 7 you can do the following:

Import-Module "$($PSScriptRoot)\Microsoft.Online.SharePoint.PowerShell\16.0.20616.12000\Microsoft.Online.SharePoint.PowerShell.dll" -DisableNameChecking -UseWindowsPowerShell
