### ISSUE TITLE
https://docs.microsoft.com/powershell/exchange/filter-properties

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/office-docs-powershell#6605]
The Get-UnifiedGroup cmdlet's -Filter does not allow filtering by AllowAddGuests. We have many organizations where the IT group will not enable guest access which significantly reduces the value proposition of Teams, especially in government organizations that largely collaborate with external parties. The justification is often an inability to easily control a small number of risky sharing scenarios. Other groups will disable end-user creation of Teams so they can manually ensure AllowGuestAccess is disabled before the owners get access, adding barriers to end user adoption.

Because  Get-UnifiedGroup does not allow filtering by AllowAddGuests, even getting a list of Teams with guest access enabled can be incredibly difficult/complicated in large environments because they must return the full list of teams and their properties and filter locally, running into timeouts and throttling limits.

**Comment by dariomws** [comment]
Hi @npherson, thank you for your feedback and help us to improve docs.microsoft.com.

For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/. There, your suggestion will reach the product team.

**Comment by npherson** [comment]
Hi @dariomws. Will the feedback for “this product” button on the docs page get redirected to uservoice at some point?

**Comment by dariomws** [comment]
@npherson I do not have that information, sorry.

**Comment by yogkumgit** [comment]
@npherson Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
