### ISSUE TITLE
I believe this statement is incorrect

### ISSUE THREAD

**Issue by vijaynikam** [MicrosoftDocs/office-docs-powershell#661]
To turn an existing Member into an Owner, first Add-TeamUser -Role Owner -User to add them to the owners list, then Remove-TeamUser -User foo to remove them from the members list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da0c53f2-1c62-14f6-6371-f54bf86b0c24
* Version Independent ID: aac162db-a9c0-fbfb-dd40-526e94d3bef8
* Content: [Add-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/Add-TeamUser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by nsshommo** [comment]
@vijaynikam Thanks for your valuable feedback.

@SamCosby Can you let me know how the article can be updated.

**Comment by kenwith** [comment]
@islubin might be able to provide guidance on the question too.

**Comment by islubin** [comment]
@kenwith there should be no need to remove the user from the member list - a user can be part of both the member and the owner list.

**Comment by kenwith** [comment]
@vijaynikam - can you confirm if you can add the role of Owner without first removing? It should work so if it doesn't we will need to track down if there is a bug. Thank you @islubin for your guidance!

**Comment by kenwith** [comment]
@vijaynikam - closing this one out based on information for @islubin . If you are experiencing different behavior than expected feel free to reopen this one and I can work with you to troubleshoot and figure out how we can submit a bug to the product team. Thanks for taking the time to submit feedback!
