### ISSUE TITLE
Cannot run Unregister-SPOHubSite on a deleted site

### ISSUE THREAD

**Issue by wobba** [MicrosoftDocs/office-docs-powershell#662]
I created a bunch of sites in my dev tenant and registered them as hub sites. I then deleted the sites without unregistering them. I also cleaned them out from my recycle bin.

The sites still list as hub sites with `Get-SPOHubSite`, and if I run `Unregister-SPOHubSite` on the sites, the call fails.

Seems to me you either should not be able to delete a hub site, or that it should also unregister if you delete it.

**Comment by VesaJuvonen** [comment]
This is a known issue in the underlying hub API logic, which will be addressed in upcoming releases. Closing this one from here and we can track this with the SharePoint/sp-dev-docs#1621 issue
