### ISSUE TITLE
LastUserActionTime and LastInteractionTime missing

### ISSUE THREAD

**Issue by ivanfioravanti** [MicrosoftDocs/office-docs-powershell#6622]
The old Get-MailboxStatistics had two very useful dates to understand if a mailbox is used by its owner or someone else. These are completely missing in the new Get-EXOMailboxStatistics, can you please read them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9145396-cc72-6e54-4204-6867397e67ea
* Version Independent ID: ca86d515-e4d3-ce0f-11e3-87ddfda38b75
* Content: [Property sets in Exchange Online PowerShell V2 cmdlets](https://docs.microsoft.com/en-us/powershell/exchange/cmdlet-property-sets?view=exchange-ps#get-exomailboxstatistics-property-sets)
* Content Source: [exchange/docs-conceptual/cmdlet-property-sets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/cmdlet-property-sets.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @ivanfioravanti, thank you for your feedback.

Here we are limited to documentation issues and improvements. To provide feedback about Exchange Online PowerShell module version 2, please go to the [Exchange Team blog](https://techcommunity.microsoft.com/t5/exchange-team-blog/bg-p/Exchange) or the [Office 365 Admin/Exchange Admin UserVoice forum](https://office365.uservoice.com/forums/273493-office-365-admin?category_id=96338).

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @ivanfioravanti Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
