### ISSUE TITLE
No Info on  Available RuleID's

### ISSUE THREAD

**Issue by netsenthil** [MicrosoftDocs/office-docs-powershell#6627]
[There is no information of Rule IDs available to run for the Repair-SPOSite and leads to a dead end.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70c2ac3c-a378-54a1-d5d3-e19689924a44
* Version Independent ID: 119de157-81c6-7896-8ae1-24f88b33e89d
* Content: [Repair-SPOSite (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/repair-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Repair-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Repair-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for your feedback @netsenthil
