### ISSUE TITLE
Example #26 is not complete

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#6628]
The ClientId is left as '' and the -Certificate parameter has nothing at all specified.  Unless I'm misunderstanding it, I think it looks like the author of that example stepped away from it and forgot to come back to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f461736e-8d54-f626-90bc-26fd8cc9758a
* Version Independent ID: 4451fe4c-df86-34a8-0db0-46a47e70b5a5
* Content: [Connect-PnPOnline (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment]
@JeremyTBradshaw Please indicate which document you are referring to. Thanks.

**Comment by JeremyTBradshaw** [comment]
Hi @yogkumgit I appear to have messed up the Document Details part of my initial post.  I've fixed it now.  And example 26 can be seen here to see what I mean:
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps#------------------example-26------------------

## ------------------EXAMPLE 26------------------
```powershell
Connect-PnPOnline -Url https://contoso.sharepoint.com -ClientId '' -Tenant 'contoso.onmicrosoft.com' -Certificate
```

**Comment by get-itips** [comment]
Hello @JeremyTBradshaw 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by JeremyTBradshaw** [comment]
Hey @get-itips , I'm actually talking about an issue with the documentation, not the cmdlet.  It's the example #26 that has a documentation issue.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @JeremyTBradshaw Your reaction is genuine, but we are helpless. That is how this process is set.  We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
