### ISSUE TITLE
Date format information is incorrect

### ISSUE THREAD

**Issue by gtimread** [MicrosoftDocs/office-docs-powershell#6630]
The date format information in this article is not correct. My local system's regional date format is set to dd/mm/yyyy (UK region settings) however running Get-MessageTrace in an EXO V2 PS session on my local system required entering the date in US mm/dd/yyyy format and returned the error "Invalid StartDate value. The StartDate can't be older than 10 days from today." when using the UK date format for the current day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b37e5f4f-c0bc-8cce-3d0b-971bcc118726
* Version Independent ID: 50c55aeb-0311-ac5a-7468-b276835f6b67
* Content: [Get-MessageTrace (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-messagetrace?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MessageTrace.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MessageTrace.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gtimread, can you confirm or deny the following behavior?

In the cloud-based service, if you specify a date/time value without a time zone, the value is in Coordinated Universal Time (UTC). To specify a date/time value for this parameter, use either of the following options:

- Specify the date/time value in UTC: For example, `"2016-05-06 14:30:00z"`.

- Specify the date/time value as a formula that converts the date/time in your local time zone to UTC: For example, `(Get-Date "5/6/2016 9:30 AM").ToUniversalTime()`. For more information, see [Get-Date](https://docs.microsoft.com/powershell/module/Microsoft.PowerShell.Utility/Get-Date).

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @gtimread Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
