### ISSUE TITLE
Example 2 typo error..

### ISSUE THREAD

**Issue by JimmyHang** [MicrosoftDocs/office-docs-powershell#6631]
There seems to be some typo error on the example 2 on this page:

* Get-PnPTeamsUser -Team MyTeam -User john@doe.com -Owner

It should be:

* Remove-PnPTeamsUser -Team MyTeam -User john@doe.com -Role Owner

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad6e2658-173b-86cd-b3f3-4ec9d5b6e91c
* Version Independent ID: ea10d61e-a3e0-011e-b276-9b4a86a4facb
* Content: [Remove-PnPTeamsUser (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpteamsuser?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPTeamsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPTeamsUser.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @JimmyHang 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @JimmyHang Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
