### ISSUE TITLE
Credential guard use case?

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/office-docs-powershell#6632]
In this article there is this statement:

"...Even when the connection to Exchange Online PowerShell uses modern authentication, the credentials are stored in a local file or a secret vault that's accessed at run-time."

Would configuring Credential Guard on a VM used to connect to EXO via MFA suffice from a baseline perspective? Anticipate this causing connectivity issues?

**Comment by dariomws** [comment]
Hi @jebalert, thank you for your feedback and help us to improve docs.microsoft.com.

Could you kindly confirm that article you are referring to? Thanks!

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and digging deep into it.  @jebalert We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
