### ISSUE TITLE
$Null no longer works for PolicyName to remove a policy from a batch of users

### ISSUE THREAD

**Issue by matthilt** [MicrosoftDocs/office-docs-powershell#6638]
$null does not seem to work to remove a policy from a batch of users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b185b8d0-fa84-7ea6-4531-cf4eb6cc26fd
* Version Independent ID: 24754aee-bff2-fa16-e7e6-af45362fd916
* Content: [New-CsBatchPolicyAssignmentOperation (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csbatchpolicyassignmentoperation?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @matthilt Matt, how are you?
I was able to use $null to batch unassign a policy, I used version 1.1.6 of the GA module.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @matthilt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
