### ISSUE TITLE
On-Premises links go to 404s

### ISSUE THREAD

**Issue by SteveClements** [MicrosoftDocs/office-docs-powershell#6639]
Both links to on-premises info go to 404s. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b815d4ba-337b-3edf-dbe5-85c373949dd4
* Version Independent ID: e85a164c-287a-a404-f798-e490ae802804
* Content: [New-PnPTenantSite (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnptenantsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPTenantSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPTenantSite.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @SteveClements 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @SteveClements Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
