### ISSUE TITLE
ContentFilter parameter is not exposed to the customers

### ISSUE THREAD

**Issue by agallego-css** [MicrosoftDocs/office-docs-powershell#6647]
The Article mentions that we have the parameter "ContentFilter" available.
Even details in example10 its use.

But connecting to EXO powershell, the parameter is not exposed to customers. we have tested in multiple tenants.

I believe the doc is wrong or out-dated (in case the parameter used to be available before).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68325010-9605-22b4-4b6c-b61f332dc321
* Version Independent ID: 47ce5d33-5483-8c8e-2aa2-532178bf466a
* Content: [New-MigrationBatch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-migrationbatch?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@agallego-css, it appears to be the other direction (newer, not older).

I, too, do not see the ContentFilter or ContentFilterLanguage parameters on the New-MigrationBatch cmdlet in my stock PROD E5 tenant. That information was recently updated in this [PR](https://github.com/MicrosoftDocs/office-docs-powershell/pull/6478) by @rahu-microsoft.

My guess is those parameters are coming (supposed to be here by now, but were delayed?). Or, it's something I accidentally published early.

**Comment by rahu-microsoft** [comment]
The feature is being rolled out. Currently a limited scope in PROD can see the new parameters.

**Comment by yogkumgit** [comment]
@agallego-css Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
