### ISSUE TITLE
Get-SPOTenantLogEntry with just start and end UTC time is not working

### ISSUE THREAD

**Issue by sprider** [MicrosoftDocs/office-docs-powershell#6648]
Hi,

I am trying to execute the following command but its throwing the below error:

Any idea? 

$endUTCTime = Get-SPOTenantLogLastAvailableTimeInUtc 
$startUTCTime = $endUTCTime.AddDays(-14) 
$tenantLogs = Get-SPOTenantLogEntry -StartTimeInUtc $startUTCTime -EndTimeInUtc $endUTCTime 

**Error**
<img width="803" alt="Screen Shot 2020-10-06 at 10 35 25 AM" src="https://user-images.githubusercontent.com/21008316/95223870-af87e980-07bf-11eb-92b1-46bde045d3c7.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700018e0-9a99-a273-db6a-00d8a08a80f6
* Version Independent ID: 83480c70-9a33-06a8-d9a8-a4189ad7af5d
* Content: [Get-SPOTenantLogEntry (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantlogentry?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantLogEntry.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantLogEntry.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @sprider Joseph, how are you?
As the article currently states

> This cmdlet is reserved for internal Microsoft use.

Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @sprider Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by sprider** [comment]
> Hello @sprider Joseph, how are you?
> As the article currently states
> 
> > This cmdlet is reserved for internal Microsoft use.
> 
> Hope this information helps you.

@get-itips @yogkumgit In this case are you planning to hide it from public view?

**Comment by get-itips** [comment]
Hello @sprider Joseph, how are you? I am afraid I do not have that information. In any case, you could propose here https://sharepoint.uservoice.com/ to reach the product team. Have a great day.

**Comment by sprider** [comment]
> Hello @sprider Joseph, how are you? I am afraid I do not have that information. In any case, you could propose here https://sharepoint.uservoice.com/ to reach the product team. Have a great day.

@get-itips I am doing good and hope the same from you. Sure, I will check in user voice. Let us close this.
