### ISSUE TITLE
Cmdlet deprecated

### ISSUE THREAD

**Issue by vincentkurmi** [MicrosoftDocs/office-docs-powershell#6654]
This cmdlet is deprecated. I think we should be able to see the information on the page. 
Here is the result of the creation request: "First generation provisioning is no longer supported. Please use the cmdlets which follow this format "*-CsCallQueue*" instead."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582cb912-2793-1823-a42f-8a6017fd30cd
* Version Independent ID: 72cc1d1e-7cbd-0977-63ea-c45f66c38d87
* Content: [New-CsHuntGroup (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cshuntgroup?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsHuntGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsHuntGroup.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @vincentkurmi 
Thanks for your feedback.
Will propose adding that to the article thru a pr.
Thanks
