### ISSUE TITLE
ShareData: Parameter description missing

### ISSUE THREAD

**Issue by Seilmeister** [MicrosoftDocs/office-docs-powershell#6659]
There's some vital information missing for our security office:

-ShareData
{{ Fill ShareData Description }}

Could you add the description please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed4847c2-e98f-00db-fe2c-aa0382b95a66
* Version Independent ID: dbea5fd4-8b55-dd74-dec9-62402d35aaf8
* Content: [Set-CsOnlineVoicemailPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/Set-CsOnlineVoicemailPolicy?redirectedfrom=MSDN&view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineVoicemailPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineVoicemailPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/6343

**Comment by yogkumgit** [comment]
Closing here, will be addressed in #6343
