### ISSUE TITLE
Set-SPOSiteOffice365Group throws access denied error

### ISSUE THREAD

**Issue by Martype** [MicrosoftDocs/office-docs-powershell#6660]
When I run this command, the desired O365 Group gets created, but the command however throws an access denied error and the sharepoint site does not get linked to the created group.

![image](https://user-images.githubusercontent.com/1420317/95446116-278d1580-0960-11eb-94a3-7cec59d2e343.png)

![image](https://user-images.githubusercontent.com/1420317/95446133-2c51c980-0960-11eb-88dd-3e58074c21dc.png)

![image](https://user-images.githubusercontent.com/1420317/95446733-ffea7d00-0960-11eb-8eb7-289b58c280e6.png)

**Comment by get-itips** [comment]
Hello @Martype how are you?
The article for [Set-SPOSiteOffice365Group](https://docs.microsoft.com/powershell/module/sharepoint-online/set-spositeoffice365group?view=sharepoint-ps) still states

> This cmdlet is currently in preview and is subject to change. It is not currently supported for use in production environments.

I'll try to confirm if that is currently true. Besides that, I was able to use the cmdlet and it shows as 365 group connected:

![image](https://user-images.githubusercontent.com/36666927/96274977-663d5400-0f8e-11eb-9dd1-e02e260c37e2.png)

![image](https://user-images.githubusercontent.com/36666927/96275112-95ec5c00-0f8e-11eb-8e2d-26d2617753cb.png)

I only needed to wait a little while to show "Yes" in 365 Connected.

Hope this information helps you,

**Comment by get-itips** [comment]
Also, be sure to run the cmdlet using the documented required permissions and that you use the latest version of the SharePoint Online PowerShell module.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Martype Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
