### ISSUE TITLE
Not just activesync devices .. it is all mobile devices

### ISSUE THREAD

**Issue by moatazelgamal** [MicrosoftDocs/office-docs-powershell#6663]
The documentation is inaccurate. The cmdlet will pull all mobile devices including modern clients that do not use activesync protocol.. this is evident from the "ClientType" attribute in the command results. 
![image](https://user-images.githubusercontent.com/10493814/95516207-82386880-0984-11eb-9ce6-7339d6f4c4d1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf20fa6e-0913-7b3e-f005-ec9f47bfabaa
* Version Independent ID: 4f92c9cb-49f8-6cab-3e70-560526eee99a
* Content: [Get-MobileDevice (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mobiledevice?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MobileDevice.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MobileDevice.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@moatazelgamal, I removed any/all unnecessary 'activesync' references from the various \*\-MobileDevice\* cmdlet topics.

Thanks for the feedback.

Closing.
