### ISSUE TITLE
Site swap in GUI For some tenants

### ISSUE THREAD

**Issue by brookehyde** [MicrosoftDocs/office-docs-powershell#6668]
Please update this to provide information that Replacing the root is available in the GUI in some tenants  the following was provided to me from Microsoft Support. 

Ensure the following: 
•	The site you select as the new root site must be a communication site (SITEPAGEPUBLISHING#0) or a modern team site that isn't connected to a Microsoft 365 group (STS#3) and where the publishing feature has never been activated.
•	The current root site can't be connected to a Microsoft 365 group.
•	When you replace the root site, both the current site and the new site can't be hub sites or associated with a hub. If either site is a hub site, unregister it as a hub site, replace the root site, and then re-register the site as a hub site. If either site is associated with a hub, disassociate the site, replace the root site, and then reassociate the site. 
•	Replacing the root site with another site replaces the entire site collection with the new site collection. If your current root site has subsites, they'll be archived.
•	The site you select as the new root site must be within the same domain as the current root site.
If the above is confirmed then follow the below steps:

•	Navigate to SharePoint admin center
•	In the upper right, make sure the All sites view is selected.
•	In the URL column, select to sort A to Z so the current root site appears at the top of the list.
•	Select the root site (https://contoso.sharepoint.com).
•	Select Replace site.
•	In the URL of the site you want to use box, enter the full or relative URL of the site that you want to become the new root site.
•	Select Save.
•	While the root site is being replaced, it might return a "not found" (HTTP 404) error for few minutes.
•	After you replace the root site, content must be recrawled to update the search index. This might take some time depending on factors such as the amount of content in these sites. Anything dependent on the search index might return incomplete results until the sites have been recrawled.
•	If the new root site was an organization news site, update the URL. Get a list of all organizational news sites

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32473b7b-386e-1440-6bfa-1a9b2413e2aa
* Version Independent ID: 54a60006-3d61-4bb9-a040-60fe77ef9f85
* Content: [Invoke-SPOSiteSwap (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/invoke-spositeswap?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md)
* Service: **sharepoint-powershell**
* GitHub Login: @WayneEwington
* Microsoft Alias: **waynewin**

**Comment by get-itips** [comment]
Hello @brookehyde 

Many thanks for your feedback.

I read the article and I found that some of the things you shared here are already in it

> • The site you select as the new root site must be a communication site (SITEPAGEPUBLISHING#0) or a modern team site that isn't connected to a Microsoft 365 group (STS#3) and where the publishing feature has never been activated.

_Information on the article:_

"If the target is the root site at https://tenant-name.sharepoint.com then the source site must be either a Modern Team Site (STS#3) or a Communication Site (SITEPAGEPUBLISHING#0)."

> • The current root site can't be connected to a Microsoft 365 group.

_Information on the article:_

"The source and target sites can't be connected to an Office 365 group."

> • When you replace the root site, both the current site and the new site can't be hub sites or associated with a hub. If either site is a hub site, unregister it as a hub site, replace the root site, and then re-register the site as a hub site. If either site is associated with a hub, disassociate the site, replace the root site, and then reassociate the site.

_Information on the article_

"They also can't be hub sites or associated with a hub. If a site is a hub site, unregister it as a hub site, swap the root site, and then register the site as a hub site."

> • Replacing the root site with another site replaces the entire site collection with the new site collection. If your current root site has subsites, they'll be archived.

This should be implied as subsites belong to the site being swapped and archived.

> • The site you select as the new root site must be within the same domain as the current root site.

Will propose clarifying that this cmdlet works to swap sites in the same SP Online Tenant.

Many thanks

**Comment by brookehyde** [comment]
The big omission is that it is in the GUI!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by get-itips** [comment]
> The big omission is that it is in the GUI! Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

Hello @brookehyde 
How are you?
That is documented here https://docs.microsoft.com/en-us/sharepoint/modern-root-site#replace-your-root-site

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @brookehyde Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
