### ISSUE TITLE
Please elaborate how and where the 'Label' setting is used

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/office-docs-powershell#6680]
Please clarify how and where the 'Label" setting is used. I understand that "The Label parameter specifies a descriptive label for the room" but how it is actually used, is it shown somewhere in Outlook or Outlook on the web? Future use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af332a3-efc1-49aa-24c2-64b5031a2420
* Version Independent ID: f47bc209-aa9e-f337-1cfa-b8a727a9f780
* Content: [Set-Place (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-place?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @JonesMikael, thank you for your feedback.

In the same way as FloorLabel, it's an additional description. As we can see in the synopsis, we use this cmdlet to add additional metadata, which provides a better search and room suggestion experience.
Using the example 2, you can use the label to search for the room used for interviews.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @JonesMikael Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by srinivasa247** [comment]
> Hi @JonesMikael, thank you for your feedback.
> 
> In the same way as FloorLabel, it's an additional description. As we can see in the synopsis, we use this cmdlet to add additional metadata, which provides a better search and room suggestion experience. Using the example 2, you can use the label to search for the room used for interviews.

Could you please add how or where the enduser should search for the rooms that is having label set as interviews? is it shown somewhere within room finder in Outlook or Outlook on the web?

**Comment by JeremyTBradshaw** [comment]
Agree, there's no explanation for where on the client side Label or FloorLabel will show up or be searchable.  If we're just reading this one article and know nothing else, then OK fine, yes we would assume that is what it's for.  But we're not just reading this page abstractly.
