### ISSUE TITLE
Feedback button points to Github for filing an issue instead of uservoice

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/office-docs-powershell#6681]
The Feedback button at the bottom of the page for "This product" points to GitHub to open an issue which will be closed by the docs team since apparently that feedback should go to uservoice.

![image](https://user-images.githubusercontent.com/22797301/95764325-ed7c8600-0c75-11eb-89ba-57f1cadab62a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://docs.microsoft.com/en-us/powershell/exchange/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/filter-properties.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @npherson, thank you for your feedback.

It's a well-known issue, but it still was not fixed. I'll send you feedback to have more votes. Thanks!

**Comment by npherson** [comment]
:-) Thanks, Dario!

**Comment by tseward** [comment]
_Product_ feedback will be closed, yes. The feedback button is designed to provide feedback on the document (i.e. incorrect information, missing information, out-of-date information, typos...).

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @npherson We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
