### ISSUE TITLE
Get-PnPUnifiedAuditLog needs pagination implemented

### ISSUE THREAD

**Issue by laimaKristol** [MicrosoftDocs/office-docs-powershell#6686]
[Enter feedback here]
Get-PnPUnifiedAuditLog is missing pagination. It only bring back results for the limit of two hours. There are no parameters to run through full log (of the day). 
Example on the page is also not workin, throws error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4dfc85c-3514-da5f-faa8-a3d3af39c306
* Version Independent ID: 6c221d26-e2ed-73f9-f55e-027862ef465d
* Content: [Get-PnPUnifiedAuditLog (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpunifiedauditlog?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPUnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPUnifiedAuditLog.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @laimaKristol 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @laimaKristol Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
