### ISSUE TITLE
AllowPlusAddressInRecipients 

### ISSUE THREAD

**Issue by machielvisser** [MicrosoftDocs/office-docs-powershell#6688]
The parameter AllowPlusAddressInRecipients is missing from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23add0a6-bb9c-15d2-a6eb-351ae0564522
* Version Independent ID: 8056b3ee-4fab-3a5c-935b-a9d0e9ad82a4
* Content: [Set-OrganizationConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @machielvisser, thank you for your feedback and help us to improve docs.microsoft.com.

This parameter was added 3 days ago. Thanks again, for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @machielvisser Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
