### ISSUE TITLE
Itentity type do not match in Get- and Complete- commands

### ISSUE THREAD

**Issue by uz-it** [MicrosoftDocs/office-docs-powershell#6689]
When running the command:
`Get-MigrationBatch -Status synced | Complete-MigrationBatch -Confirm:$false`
Getting followin error:
`"Cannot convert the "Batch-Name" value of type "Deserialized.Microsoft.Exchange.Data.Storage.Management.MigrationBatchId" to type "Microsoft.Exchange.Management.Migration.MigrationService.Batch.MigrationBatchIdParameter"`

The workaround is
`Get-MigrationBatch -Status synced | %{Complete-MigrationBatch -Identity $($_.identity).tostring() -Confirm:$false}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7f086ba-ff28-8c6b-4b2f-f19f70511c4b
* Version Independent ID: 28d4c38d-86e7-89bb-5c0f-c54d4e7fd721
* Content: [Complete-MigrationBatch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/complete-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Complete-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Complete-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @uz-it, thank you for your feedback and help us to improve docs.microsoft.com.

I think the description of Identity in both articles is fine. What you are trying to do depends on the Input and Output of each cmdlet:
![image](https://user-images.githubusercontent.com/33589238/97027791-a3c35380-1531-11eb-8cc3-f0cb8e19ca1d.png)
As you can see here, the output of Get-MigrationBatch is not compatible with the input of Complete-MigrationBatch.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @uz-it Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
