### ISSUE TITLE
Example missing

### ISSUE THREAD

**Issue by kumaarrahul** [MicrosoftDocs/office-docs-powershell#669]
The example is missing. Please update the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 307f4f37-0c59-8ec0-9846-cbe773f1cbaa
* Version Independent ID: e6816f67-00d9-7960-61ee-c45922e0bb94
* Content: [Grant-CsCallingLineIdentity (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by nsshommo** [comment]
@kumaarrahul Thanks for letting us know. It is under processing and soon be updated.

**Comment by kenwith** [comment]
All Skype cmdlets are undergoing audit and being tracked internally to make sure every cmdlet has an example and descriptions.
