### ISSUE TITLE
Get-Team met HttpRequestException issue

### ISSUE THREAD

**Issue by xuegao0112** [MicrosoftDocs/office-docs-powershell#6690]
Hi,
When I run the script below met this issue:
### Script:
$credential = Get-AutomationPSCredential -Name "AAAA"
Connect-MicrosoftTeams -Credential $credential
Write-Output "Started" 
$AllTeams = Get-Team -GroupID "xxxxx"
Write-Output $AllTeams
Disconnect-MicrosoftTeams

**### **_Issue:_****
10/15/2020 7:53:41 AM 	 Error 	 Get-Team : BadGateway in /teams/ endpoint
At line:9 char:13
+ $AllTeams = Get-Team -GroupID "c1dbd120-5a95-4d4b-b090-e067d4f5d8f3"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Team], HttpRequestException
    + FullyQualifiedErrorId : System.Net.Http.HttpRequestException,Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeam
 
I have many automation account and works in other environments just for one automation account, and they are all the same.  Then I found this issue: https://social.microsoft.com/Forums/SECURITY/en-US/e5aa0935-abc3-4897-a03e-c586287ac99b/powershell-badrequest?forum=msteams

Is there any backend issue happening?

**Comment by get-itips** [comment]
Hello @xuegao0112 how are  you?
Looks like you are running the Teams module inside an Azure Runbook, is that it? Does it work for you with the same credentials outside of it? Be sure to run the latest GA version of the module.
Other than that I do not identify any issue with the documentation.
Hope this gets you in the right direction.

**Comment by get-itips** [comment]
Hello @xuegao0112 returning to understand if you could see my comment.
Thanks
