### ISSUE TITLE
Listing Admin requirements would be helpful

### ISSUE THREAD

**Issue by ACarlockAKA** [MicrosoftDocs/office-docs-powershell#6693]
It would be helpful if the Admin requirements for each command were listed.  More companies are limiting Global Admin access and assigning separate administrative roles.  I was allocated Teams Admin Role, but Set-CSUser is only available with the Skype For Business Admin role.  It would have saved me and the Microsoft support engineer hours of troubleshooting if this was listed for these commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2648ec32-2716-4f6e-20f1-1a989aa8cc45
* Version Independent ID: 53e81f24-1e27-9c50-439b-7916e7d1045d
* Content: [SkypeForBusiness Module](https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps)
* Content Source: [skype/skype-ps/skype/skype.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/skype.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @ACarlockAKA Alex,

How are you? Hope you are doing great.

**Thanks for your feedback.**

If you do not have Skype for Business Online administrator role, for example, the Set-CsUser cmdlet will not be imported in your session when connecting, and that is probably what happened to you.

All -CS* cmdlets belong to the Skype For Business/Online PowerShell module and, at a minimum, you have to be assigned that role to be able to run them, this is described in the article on how to [Manage Skype for Business Online with PowerShell](https://docs.microsoft.com/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell) and you can also find that on cmdlet's articles like [New-CsOnlineSession](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinesession?view=skype-ps)

> Skype for Business Online administrator can run Skype for Business cmdlets to manage users, policies and configurations.

Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ACarlockAKA Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
