### ISSUE TITLE
Get-UserAnalyticsConfig and Set-UserAnalyticsConfig to be retired January 25, 2021

### ISSUE THREAD

**Issue by paul9955** [MicrosoftDocs/office-docs-powershell#6696]
I believe the two cmdlets Get-UserAnalyticsConfig and Set-UserAnalyticsConfig will be retired on or before January 25, 2021. Could you add a note about that to this topic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61176659-bd5c-de65-775b-cbb0b90871e1
* Version Independent ID: 4730f821-0ae9-dc49-2032-f27154f47bb0
* Content: [Get-UserAnalyticsConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-useranalyticsconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-UserAnalyticsConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-UserAnalyticsConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@paul9955, I added some information in relevant topics.

Thanks for the feedback.

Closing

**Comment by paul9955** [comment]
Thank you much for this very quick response!
 - Paul
