### ISSUE TITLE
Send-PMPMail

### ISSUE THREAD

**Issue by clemenda** [MicrosoftDocs/office-docs-powershell#6699]
In Exchange Online powershell, when I run a Send-PNPMail cmdlet to my own email address, it accepts the command but the email is not received and there is no sign of the email trace when tracking using Get-MessageTrace so it appears the email is not sent at all.  Has anyone else come across this issue?  I have tried authenticating on modern authentication for the Connect-PNPOnline and also tried using a Password for the Send-PNPMail cmdlet

**Comment by dariomws** [comment]
Hi @clemenda, thank you for your feedback.

I think you are running this cmdlet in the SharePoint PnP PowerShell module, and you are trying to send an e-mail via Office 365.

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues here, in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then synced from that repo into this one.

**Comment by clemenda** [comment]
Will do, thanks @dariomws
