### ISSUE TITLE
Obsolete parameters used in the examples

### ISSUE THREAD

**Issue by pramodghuge** [MicrosoftDocs/office-docs-powershell#6701]
The examples shown on the page contain invalid obsolete parameters viz **Title** and **Location**.
Getting the following error if the parameters are used.

WARNING: Parameter 'Title' is obsolete. Use -Identity with an Id instead.
WARNING: Parameter 'Location' is obsolete. Use -Identity with an Id instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84abb6cb-89e3-eeca-0f43-06255edd219a
* Version Independent ID: 15dfc257-8c5f-63d6-ffe7-f7a7163c25bf
* Content: [Remove-PnPNavigationNode (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpnavigationnode?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPNavigationNode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPNavigationNode.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @pramodghuge 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @pramodghuge Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
