### ISSUE TITLE
Invalid parameter -Title used instead of -Identity in Example 3 

### ISSUE THREAD

**Issue by pramodghuge** [MicrosoftDocs/office-docs-powershell#6702]
The command shown in Example 3 contains an invalid parameter -Title.
The correct parameter is -Identity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb2d3c28-638c-262d-b851-de589cedf3c0
* Version Independent ID: 3054989c-a9fb-74aa-9121-fdb24b1a3f65
* Content: [Remove-PnPList (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnplist?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPList.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @pramodghuge 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.
(So, Pull Requests created against the documentation on this repo, if merged, will be rewritten by that process)

Thank you!
