### ISSUE TITLE
This Copy-PnPFile command doesn't copy version history

### ISSUE THREAD

**Issue by thiagottss** [MicrosoftDocs/office-docs-powershell#6707]
This Copy-PnPFile command doesn't copy version history but the documentation page states the following:

-IgnoreVersionHistory
If provided, only the latest version of the document will be copied and its history will be discared. If not provided, all historical versions will be copied along.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85cba281-56e9-dfba-0ed8-df9a22029eaa
* Version Independent ID: 47c94158-6136-04ee-5fc0-712abcb1827a
* Content: [Copy-PnPFile (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/copy-pnpfile?view=sharepoint-ps#parameters)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Copy-PnPFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Copy-PnPFile.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @thiagottss 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @thiagottss Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
