### ISSUE TITLE
Grammar mistake

### ISSUE THREAD

**Issue by LuckyJC** [MicrosoftDocs/office-docs-powershell#6710]
The text in example 12 currently reads: "Extracts a provisioning template in Office Open XML from the current web, but only processes content types from the **to** given content type groups."

I believe it should read: "Extracts a provisioning template in Office Open XML from the current web, but only processes content types from the **two** given content type groups."

Simply change **"to"** to **"two"**.

Source page:
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps

Text located under Example 12 explaining -ContentTypeGroups

Hope this helps!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ad4221a-3c52-f126-164a-8e5a015e7dac
* Version Independent ID: c0c6ad38-e86c-cd0c-ac01-033791404e25
* Content: [Get-PnPProvisioningTemplate (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPProvisioningTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPProvisioningTemplate.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @LuckyJC 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @LuckyJC Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
