### ISSUE TITLE
Applies to - Need update

### ISSUE THREAD

**Issue by satishkr9506** [MicrosoftDocs/office-docs-powershell#6712]
[Enter feedback here]
As per article this policy applies to Skype and Lync however looks like Teams also honor this policy at least for Federation. So, I think, we should update the applies field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd619f4b-f02f-30f3-b5d0-5aa24d18990b
* Version Independent ID: 9ea501f0-f89a-8416-15c8-3d9bc55c4b80
* Content: [Grant-CsExternalAccessPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csexternalaccesspolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsExternalAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsExternalAccessPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @satishkr9506 
How are you? Thanks for your feedback.

I added this sentence some time ago to this article 

> Please note: althought the Applies to section does not mention it, this cmdlet also applies to Microsoft Teams.

This is because the Applies to metadata can't have it because of current limitations of the Docs engine. You can read more information [here](https://github.com/MicrosoftDocs/office-docs-powershell/pull/5887#issuecomment-643456643). 

Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @satishkr9506 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
