### ISSUE TITLE
Unattended script

### ISSUE THREAD

**Issue by GalRabin** [MicrosoftDocs/office-docs-powershell#6716]
I am trying to develop an unattended script using modern authentication methods.

The services I am trying to connect are:
1. Exchange online - Using the following command `Connect-ExchangeOnline`, Currently from the documentation I was able only to authenticate by unattended script by using CBA (Certificate-based authentication), There are missing details on how to connect using bearer token (Oauth2.0) which supplied to our script by 3-rd party, I find many different answers regarding this subject.

2. Security & Compliance Center PowerShell - Using the following command `Connect-IPPSSession`, Here I can't find any way to develop an unattended script (CBA, bearer token).

I will appreciate the comment on both subject, There are many missing details on that subject.

Thanks again

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @GalRabin, thank you for your feedback.

You can find more information about how to run unattended Scripts in Exchange Online PowerShell V2 in the following articles:
https://techcommunity.microsoft.com/t5/exchange-team-blog/modern-auth-and-unattended-scripts-in-exchange-online-powershell/ba-p/1497387
https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @GalRabin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by GalRabin** [comment]
@yogkumgit @dariomws 
Hi,
Thanks for the update but you didn't answer about `Security & Compliance Center PowerShell `. Is there any way to use unattended scripts?

**Comment by dariomws** [comment]
Hi @GalRabin, the product team answered this question in the following link:
https://techcommunity.microsoft.com/t5/exchange-team-blog/modern-auth-and-unattended-scripts-in-exchange-online-powershell/ba-p/1497387

'Jimmy Brothers
‎08-04-2020 08:52 AM
Will this authentication also work with Security & Compliance PowerShell?'

'Rob Whaley (EXCHANGE) Microsoft
‎08-10-2020 08:13 PM
@Jimmy Brothers Currently this module only supports Exchange Online at this time.'

**Comment by GalRabin** [comment]
@dariomws  @yogkumgit 
Thanks for the answer, Assuming Microsoft planning to drop Basic Auth support in mid-2021, What is the ETA for releasing such a version which supports Search and Compliance? (As partners we need time to adapt our content in accordance with Microsoft requirements)

Thanks appreciate your answer

**Comment by GalRabin** [comment]
@dariomws 
Hi,
I left a comment in the article, I will update here also if any news from there.

**Comment by dariomws** [comment]
@GalRabin thank you so much! I think it's a great idea to leave a comment here with the new information.

**Comment by mbratukha** [comment]
@GalRabin, could you please provide any feedback whether you was able to receive an answer the product team regarding S&C?

**Comment by jangojim** [comment]
Same thing here! I wonder if I can use something like...

Connect-IPPSSession -AppId $AppId -CertificateThumbprint $Thumbprint -Organization $MyOrganization

**Comment by chrisda** [comment]
Until Certificate and/or CertificateThumbprint parameters are added to Connect-IPPSSession, I don't think it will work. As of v2.0.6 Preview4 in both PowerShell 5.1 and PowerShell 7.x, those parameters are not available.

**Comment by jangojim** [comment]
I know it doesn't work, can someone explain why we received that from Microsoft then?!

Certificate based Authentication for Security and Compliance Center PowerShell
MC316448
With this update, which will improve the security of your tenant, Security & Compliance PowerShell will enable configuration of certificate-based authentication to allow unattended App-only access. 
When this will happen:
Rollout will begin in mid-February and is expected to be complete by early March.
How this will affect your organization:
If your organization is currently using "Basic authentication" for application access, you will need to migrate to certificate-based authentication prior to mid-February.
What you need to do to prepare:
To migrate to certificate-based authentication, follow these steps:
•	Step 1: Register the application in Azure AD
•	Step 2: Assign API permissions to the application
•	Step 3: Generate a self-signed certificate
•	Step 4: Attach the certificate to the Azure AD application
•	Step 5: Assign Azure AD roles to the application
Learn more:
•	Connect to Security & Compliance PowerShell
•	App-only authentication for unattended scripts in the EXO V2 module
Additional Information 
View this message in the Microsoft 365 admin center

**Comment by mbratukha** [comment]
I've raised a ticket on the Microsoft's Feedback platform regarding this issue: https://feedbackportal.microsoft.com/feedback/idea/15afa4c6-e988-ec11-a81b-0022484c51ef

It would be great if everybody who requires an app-only access to the S&C PowerShell could write a comment there with your use cases. It might reach the responsible Microsoft's engineers directly.

**Comment by chrisda** [comment]
All, you can connect to Security & Compliance Center PowerShell using the Connect-ExchangeOnline cmdlet IF you also use the _ConnectionURI_ parameter and value `https://ps.compliance.protection.outlook.com/powershell-liveid/` in the command. Try that and see if it works.

**Comment by mbratukha** [comment]
@chrisda, thank you very much for your response!
I can confirm that the access to SCC PowerShell is working even via app-only context (app ID + certificate).

**Comment by chrisda** [comment]
Version 2.0.6-Preview5 of the EXO V2 Module is now available, so the various Credential parameters are now available on Connect-IPPSSession, so certibicate-based/app-oly authentication is now fully available in Security & Compliance Center PowerShell.
