### ISSUE TITLE
New-CsTeamsIPPhonePolicy - missing description of two parameters

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#6718]
missing parameters:
-AllowHomeScreen
-AllowBetterTogether 

Module: MicrosoftTeams
Version: 1.1.6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4039b69-4975-ff03-ef7f-3c2c3cae797d
* Version Independent ID: afed6a8c-e934-fbf0-b15d-abb250fee3bc
* Content: [New-CsTeamsIPPhonePolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsipphonepolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsIPPhonePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsIPPhonePolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tonywoodruff
* Microsoft Alias: **anwoodru**

**Comment by get-itips** [comment]
Hello @shivtorov 
Thanks for reporting, I am looking into this.
