### ISSUE TITLE
Request to update the more details with Parameter -FilterStartTime and -FilterEndTime

### ISSUE THREAD

**Issue by srinivasa247** [MicrosoftDocs/office-docs-powershell#6720]
Hello Chris,

While referring the article, there is a confusion around what this the exact date that the parameters -FilterStartTime take for reference.

An email item in a mailbox has many timestamps to it as below:
1. Date sent / Date received for the mail item
2. Date that the mail item was actually deleted.
3. Date that the mail item was last modified.

It is unclear which of the above timestamps taken as reference, while reading the article.

So I ran the test in my lab, and found the reference taken here is LastModifiedTime of the item.

I request you to validate the same from your end once, and update the information in the article, to avoid any confusion for future readers.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21b1cd9d-df2e-d4d6-52e2-d3fbdfb9db9f
* Version Independent ID: e675173d-290a-dee0-62a4-5485cf3d2570
* Content: [Restore-RecoverableItems (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/restore-recoverableitems?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Restore-RecoverableItems.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Restore-RecoverableItems.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@srinivasa247, I believe you, and I've updated the topic accordingly.

Thanks for the feedback.

Closing.
