### ISSUE TITLE
Error in DisableSharingForNonOwners description.

### ISSUE THREAD

**Issue by marcjornet** [MicrosoftDocs/office-docs-powershell#6721]
[Enter feedback here]
There's an error on the description when applying the property of DisableSharingForNonOwners.
It specifies that only the site won't be shared by nonOwners, but it really prevents nonOwners from sharing files and folders.

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a453f6db-c1b0-3769-9972-d948616982df
* Version Independent ID: d9e27a2c-8408-95ba-6d88-46e63fe878a1
* Content: [Set-PnPSite (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSite.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Hello @marcjornet 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @marcjornet Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
