### ISSUE TITLE
Example 3 does not work

### ISSUE THREAD

**Issue by darwincr** [MicrosoftDocs/office-docs-powershell#6722]
PS C:\> Set-CsAutoAttendant -Instance $autoAttendant -verbose
Cannot bind parameter 'Instance'. Cannot convert value "Microsoft.Rtc.Management.Hosted.OAA.Models.AutoAttendant" to type "Microsoft.Rtc.Management.Hosted.OAA.Models.AutoAttendant". Error: "ArrayConverter cannot convert from 
Microsoft.Rtc.Management.Hosted.OAA.Models.CallFlow."
    + CategoryInfo          : InvalidArgument: (:) [Set-CsAutoAttendant], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Rtc.Management.Hosted.OAA.V2.SetCsAaCmdlet
    + PSComputerName        : adminau1.online.lync.com

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aedf07e-205e-ebe8-6351-1c1956f99b85
* Version Independent ID: c18defb2-97e8-1196-dc32-47260dad5c09
* Content: [Set-CsAutoAttendant (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csautoattendant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsAutoAttendant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsAutoAttendant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @darwincr thanks for reporting, I have checked and confirmed, will fix the example.
Thanks
