### ISSUE TITLE
Get-TeamChannelUser doesn't work

### ISSUE THREAD

**Issue by VjNi007** [MicrosoftDocs/office-docs-powershell#6723]
Get-TeamChannelUser -GroupId $groupId 
Get-TeamChannelUser : The term 'Get-TeamChannelUser' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path 
is correct and try again.
At line:1 char:1
+ Get-TeamChannelUser -GroupId bdd5fbe7-8d74-436e-8e8e-ce4374c6d504
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-TeamChannelUser:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by get-itips** [comment]
Hello @VjNi007 
Get-TeamChannelUser is available in the Public Preview version of the Microsoft Teams PowerShell module, you might be using the General Availability version.
More information here 
https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-overview
https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @VjNi007 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
