### ISSUE TITLE
Synopsis missing?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6724]
There's only a . under "Applies to: SharePoint Online"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4a46776-27da-2964-9835-d7064777ddb1
* Version Independent ID: 39bfe65b-ae44-2d4b-18ed-c30a404d6d4f
* Content: [Set-SPOMultiGeoExperience (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spomultigeoexperience?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMultiGeoExperience.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMultiGeoExperience.md)
* Service: **sharepoint-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by get-itips** [comment]
Thanks for reporting @hwkwicre
