### ISSUE TITLE
The article is in the wrong location; and broken link

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6725]
Module: SharePointOnlinePowerShell
Applies to: SharePoint Server 2013, SharePoint Server 2016

I believe this article should not be under SharePoint Online section?

Also "see the online documentation at https://go.microsoft.com/fwlink/p/?LinkId=251831 (https://go.microsoft.com/fwlink/p/?LinkId=251831)." the links are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 331eb9d4-5df3-bb1e-68b9-21a19672829c
* Version Independent ID: 79829894-60c7-8058-71c5-f9d275a1323f
* Content: [Set-SPODataConnectionSettingMetadata (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spodataconnectionsettingmetadata?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPODataConnectionSettingMetadata.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPODataConnectionSettingMetadata.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by hwkwicre** [comment]
Also this link has exactly the same problem: broken link and wrong location.
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spodataconnectionsetting?view=sharepoint-ps

**Comment by get-itips** [comment]
Hello @hwkwicre how are you?
You are right, the location of this cmdlet should not be in sharepoint-online folder, however, this has been reported in the past and it was decided by the team, not to move the article so the history won't be lost.
Will check the links that you report.
Thanks!
