### ISSUE TITLE
Connect-SPOService Global Administrator 401 Unauthorized

### ISSUE THREAD

**Issue by iyadzikra** [MicrosoftDocs/office-docs-powershell#6726]
Running the command: 
`Connect-SPOService -Url $siteURL -Credential $userCred`
using an account that has global administrator privileges. Any thoughts on what could be the reason?

**Comment by get-itips** [comment]
Hello @iyadzikra 
How are you? Hope you are doing good.
Here we are limited to documentation issues and changes, if you need support, I recommend opening a support ticket directly from your tenant.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @iyadzikra Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
