### ISSUE TITLE
About " -MaxReceiveSize" in Exchange Online

### ISSUE THREAD

**Issue by CarolWangMS** [MicrosoftDocs/office-docs-powershell#6733]
About " -MaxReceiveSize" in Exchange Online

Hi team,

it says 

-MaxReceiveSize
This parameter is available only in on-premises Exchange.
.....

Applies to: | Exchange Server 2010, Exchange Server 2013, Exchange Server 2016, Exchange Server 2019
-- | --

But this parameter should work for exchange online, just like -MaxSendSize. 

Thanks,
B. R
Carol

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f835af-5905-368a-df68-6646782ad807
* Version Independent ID: 153ce2d2-dab5-9c8f-c511-ee3bc8ee2dbc
* Content: [Set-Mailbox (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@CarolWangMS, OK. Fixed. In the future, you too can make simple fixes like this yourself without opening an Issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
