### ISSUE TITLE
Suggestion for the -AzureADAuthorizationEndpointUri parameter

### ISSUE THREAD

**Issue by sebfil** [MicrosoftDocs/office-docs-powershell#6734]
When you use multiple powershell runtimes with multiple tenants, you must specify 
-AzureADAuthorizationEndpointUri https://login.microsoftonline.com/{tenant-id}/v2.0

When you don't do this, you get an exception  "An item with the same key has already been added. Key: https://login.microsoftonline.com/organizations". 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 13d88f18-3cc8-5f18-8d61-ff7f5fa4e314
* Version Independent ID: 60f9a029-69f3-e65c-6816-fbd414790ce3
* Content: [Connect-ExchangeOnline (ExchangePowerShell)](https://docs.microsoft.com/de-de/powershell/module/exchange/connect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @sebfil, thank you for your feedback and help us to improve docs.microsoft.com.

I have tried to connect to 3 different tenants, and I didn't get this exception. Maybe you can provide more detail so I can reproduce this behaviour.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and digging deep into it.  @sebfil We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
