### ISSUE TITLE
Example 1 is empty

### ISSUE THREAD

**Issue by Bertug** [MicrosoftDocs/office-docs-powershell#6735]
Example 1 is empty on the page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cbf9e01-3daf-0a8c-f78c-5c9ba6dac01f
* Version Independent ID: 91f0f246-e6c5-c2e2-1569-7f27afb28c04
* Content: [Set-CsTeamsAppSetupPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsappsetuppolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsAppSetupPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsAppSetupPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @Bertug how are you?

Please see that the article currently says

> The existence of this cmdlet is being documented for completeness, but do not use this cmdlet. We require that all creation and modification of app setup polices (not including the assignment or removal of policies from users) happens in the Microsoft Teams & Skype for Business Admin Center to ensure that the policy matches your expectations for the end user experience.

Thanks for your feedback.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Bertug Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
