### ISSUE TITLE
Does the Bulk CSV method work for SharePoint Library / Folder Migrations

### ISSUE THREAD

**Issue by jasonwbaxter** [MicrosoftDocs/office-docs-powershell#6736]
Hi Team , 

I'm working on a powershell script to help migrate folders and sub folders out of a library into various sites etc.

The structure looks something like this
Library
-----Folder 
------Sub_Folder
-------Sub_Sub_Folder
-------Sub_Sub_Folder
-------Sub_Sub_Folder
-------Sub_Sub_Folder
-------Sub_Sub_Folder

Folder is a categorical division such as  Records.
Sub_folder is a customer code / Name
Sub_Sub_folder is a Document Type

When using the Bulk CSV method through the gui , my CSV works perfectly , 

When i try using the Powershell module with the same syntax in the powershell module it fails with the error message :Task GUID did NOT pass the parameter validation. the error message is 'The source library LibraryName does not exist on source site  i have tried a different library , different site , and confirmed that the library exists and that the internal SP name is being used , i even tested with a library that has not been renamed.

When i use the Migrate-all it finds the site no problem but when i am trying to specify a specific library / folder or Sub folder like

Library-->Folder A--> Folder 1 i get this error message , again using the GUI this CSV works.

So what is the difference between the GUI and the Powershell module? according to this page , i have the correct command.

 Add-SPMTTask -SharePointSourceSiteUrl $item.c1 -SharePointSourceCredential $Global:SPCredential -SourceList $item.c2   -SourceListRelativePath $item.c3   -TargetSiteUrl $item.c4   -TargetList $item.c5   -TargetListRelativePath $item.c6

thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e801cf9-c628-db13-e90b-935d5a74d76e
* Version Independent ID: 5fb69466-bfae-f263-80b0-ad585d59f0ae
* Content: [Add-SPMTTask (SharePointMigrationTool)](https://docs.microsoft.com/en-us/powershell/module/spmt/add-spmttask?view=spmt-ps)
* Content Source: [spmt/spmt-ps/spmt/Add-SPMTTask.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/spmt/spmt-ps/spmt/Add-SPMTTask.md)
* Service: **spmt-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by jasonwbaxter** [comment]
Here is a sample of the CSV i am using.

```
http://SourceSharePoint2013,Library,Subfolder/SubsubFolder1,https://SPONlineDestination,Documents,SubSubfolder1
http://SourceSharePoint2013,Library,Subfolder/SubsubFolder2,https://SPONlineDestination,Documents,SubSubfolder2
http://SourceSharePoint2013,Library,Subfolder/SubsubFolder3,https://SPONlineDestination,Documents,SubSubfolder3
http://SourceSharePoint2013,Library,Subfolder/SubsubFolder4,https://SPONlineDestination,Documents,SubSubfolder4
http://SourceSharePoint2013,Library,Subfolder/SubsubFolder5,https://SPONlineDestination,Documents,SubSubfolder5
http://SourceSharePoint2013,Library,Subfolder/SubsubFolder6,https://SPONlineDestination,Documents,SubSubfolder6
http://SourceSharePoint2013,Library,Subfolder/SubsubFolder7,https://SPONlineDestination,Documents,SubSubfolder7
http://SourceSharePoint2013,Library,Subfolder/SubsubFolder8,https://SPONlineDestination,Documents,SubSubfolder8
http://SourceSharePoint2013,Library,Subfolder/SubsubFolder9,https://SPONlineDestination,Documents,SubSubfolder9
```

**Comment by jasonwbaxter** [comment]
Seems this has now stopped working in the GUI as well since the update.

**Comment by get-itips** [comment]
Hello @jasonwbaxter Jason, how are you?
I am checking this if we need to update some article, is it giving you some of the known and documented [error codes](https://docs.microsoft.com/sharepointmigration/troubleshooting-common-spmt-issues#spmt-error-codes)?
Thanks

**Comment by JoanneHendrickson** [comment]
Hi Andres -- i am contacting the product team to help will ping you on email.

**Comment by get-itips** [comment]
> Hi Andres -- i am contacting the product team to help will ping you on email.

Many thanks Joanne.

**Comment by get-itips** [comment]
Hello @jasonwbaxter according to the team, nothing changed about folders between versions so apparently no documentation change will be needed. As we opened an internal channel, please continue through it to get help about this.
Thank you
@yogkumgit please close.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @JoanneHendrickson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
