### ISSUE TITLE
Description of -ChannelsInChatListEnabledType is not clear

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/office-docs-powershell#6742]
The description of -ChannelsInChatListEnabledType is:
Possible values are: DisabledUserOverride,EnabledUserOverride.

The description does not state what this parameter does. I am assuming it related to the Teams Admin setting of **On mobile devices, display favorite channels above recent chats**

Can this post be made clearer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd54bec8-d576-260c-7578-970e44de2d3b
* Version Independent ID: 8102a7bb-e0ef-0f8b-b9b8-67a45ecf076f
* Content: [New-CsTeamsMessagingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmessagingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsMessagingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsMessagingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for your feedback. @nikki-c
