### ISSUE TITLE
Example is incorrect.

### ISSUE THREAD

**Issue by damianscoles** [MicrosoftDocs/office-docs-powershell#6746]
The example provided has the cmdlet **Get-MailFlowStatusReport** instead of the actual cmdlet of the page which is **Get-CompromisedUserAggregateReport**.  Can the example be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fd3cd86-e196-cb9f-49aa-fd3b15e75124
* Version Independent ID: 3b92e320-708c-d1f5-a738-171d2f6b8da6
* Content: [Get-CompromisedUserAggregateReport (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-compromiseduseraggregatereport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-CompromisedUserAggregateReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-CompromisedUserAggregateReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@damianscoles, fixed. In the future, you too can make correction like this yourself without opening an Issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
