### ISSUE TITLE
Authentication using Access Tokens broken in version 1.1.6

### ISSUE THREAD

**Issue by ioamnesia** [MicrosoftDocs/office-docs-powershell#6751]
When trying to authenticate using the "-AadAccessToken -MsAccessToken -AccountId" it fails with this error:
Object reference not set to an instance of an object.

Reverting to v1.1.4 allows the authentication to work fine.

**Comment by get-itips** [comment]
Hello @ioamnesia thanks for your feedback, will try to pass this along to the team, as here, we are limited to documentation issues. Thanks again.

**Comment by get-itips** [comment]
Hello @ioamnesia 
I could get some information from the team.
`AADAccessToken` parameter will be dropped and `-AccessToken` and `-AccountId` are going to be used, this change is now available in the preview version of the Teams module (1.1.9-preview) and the documentation will reflect it once it becomes GA.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ioamnesia Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
