### ISSUE TITLE
Question regarding an example

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6754]
"in the form, https://server_name or https://server_name/sites/sitename"
That sounds like something from SharePoint Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4661450e-0e7f-619b-e820-0ba6acce4575
* Version Independent ID: 30fad058-46e5-acb0-bb9f-1d87d6f349d5
* Content: [Get-SPOSiteUserInvitations (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositeuserinvitations?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteUserInvitations.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteUserInvitations.md)
* Service: **sharepoint-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks for reporting!
