### ISSUE TITLE
Certificate parameter pointing to Azure Key Vault certificate

### ISSUE THREAD

**Issue by fernandoferrini** [MicrosoftDocs/office-docs-powershell#6757]
Dear,

Could you please confirm that, according to example 3 - Connect using a certificate object:

Connect-ExchangeOnline -Certificate <%X509Certificate2 Object%> -AppID "36ee4c6c-0812-40a2-b820-b22ebd02bce3" -Organization "contosoelectronics.onmicrosoft.com"

...it is possible to point to a certificate object stored in Azure Key Vault using EXOV2? And what is the exact property of the object to be used?

I uploaded a x509 certificate object (not x509certificate2) to Azure Key Vault and called with -Certificate parameter using several properties of the object: Certificate Version, Certificate Identifier, Serial Number, X.509 SHA-1 Thumbprint (in hex). None of them worked. It seems that we are unable to reach Azure Key Vault from EXOV2 at the moment. 

I´ll appreciate any feedback about it.

Regards,

Fernando.

**Comment by dariomws** [comment]
Hi @fernandoferrini, thank you for your feedback and help us to improve docs.microsoft.com.

I think the support to connect with a certificate object was added on September with the release of 2.0.3 version in General Availability, and you should be able to put the certificate in Azure Key Vault.

@navgupta1208 could you kindly help me to confirm this information? Thanks!

**Comment by dariomws** [comment]
> I uploaded a x509 certificate object (not x509certificate2) to Azure Key Vault and called with -Certificate parameter using several properties of the object: Certificate Version, Certificate Identifier, Serial Number, X.509 SHA-1 Thumbprint (in hex). None of them worked. It seems that we are unable to reach Azure Key Vault from EXOV2 at the moment.

Looking to this in more detail, I think you're trying to use/get the certificate in a wrong way. You need to use a X509Certificate2 Object with the -Certificate parameter. For example:
```
$vaultName = <YourKeyVault>
$cert = Get-AzKeyVaultCertificate -VaultName $vaultName -Name "ExchCBAAppCert"
$secret = Get-AzKeyVaultSecret -VaultName $vaultName -Name $cert.Name
$secretValueText = '';
$ssPtr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secret.SecretValue)
try {
    $secretValueText = [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($ssPtr)
} finally {
    [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ssPtr)
}
$secretByte = [Convert]::FromBase64String($secretValueText)
$x509Cert = new-object System.Security.Cryptography.X509Certificates.X509Certificate2
$x509Cert.Import($secretByte, "", "Exportable,PersistKeySet")
```

See example 2: https://docs.microsoft.com/powershell/module/az.keyvault/get-azkeyvaultcertificate#example-2--get-cert-and-save-it-as-pfx.

**Comment by dariomws** [comment]
It works:
![image](https://user-images.githubusercontent.com/33589238/97780287-7c3c3e80-1b62-11eb-8662-ebc6c5610186.png)

**Comment by fernandoferrini** [comment]
Thanks Darío, it worked. You can close the issue.

Regards,
