### ISSUE TITLE
Get-ExoRecipient -Properties * -- documentation suggests this is possible, but function fails

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/office-docs-powershell#6760]
![image](https://user-images.githubusercontent.com/6205899/97475829-a238c780-1945-11eb-85ac-17a7d1f629a4.png)

For the "-Properties" parameter, the documentation states `Wildcards ( * ) are supported.`, but when attempting to use this, the following occurs:
![image](https://user-images.githubusercontent.com/6205899/97475906-b7adf180-1945-11eb-967a-d55043a46463.png)

It looks like this parameter does not support a wildcard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1008bd7c-9280-f137-ef8f-d7be661ae846
* Version Independent ID: b72b5146-7acb-2859-fe7a-1e73d7ff79b4
* Content: [Get-EXORecipient (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-exorecipient?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-EXORecipient.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-EXORecipient.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@webash, in virtually any cloud-based filter, a leading \* is not allowed; trailing \* or \* between text values should always be OK. I don't think it was ever meant to support \* by itself.

Test it out and let me know what you find.

**Comment by davidtrevor23** [comment]
I have the same problem with Exchange Online. Wildcard does not work at all

```
Get-EXORecipient -Properties Recipient*
Get-EXORecipient : Some of requested properties are not valid. InvalidProperties = Recipient*
At line:1 char:1
+ Get-EXORecipient -Properties Recipient*
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ProtocolError: (:) [Get-EXORecipient], RestClientException
    + FullyQualifiedErrorId : Some of requested properties are not valid. InvalidProperties = Recipient*,Microsoft.Exchange.Management.RestApiClient.GetExoRecipient
```

**Comment by webash** [comment]
> @webash, in virtually any cloud-based filter, a leading * is not allowed; trailing * or * between text values should always be OK. I don't think it was ever meant to support * by itself.
> 
> Test it out and let me know what you find.

Understood @chrisda ; but ultimately the documentation is being a bit too vague, then.

**Comment by chrisda** [comment]
Looking into it. Asking knowledgeable parties about intent and how it works.

**Comment by chrisda** [comment]
I removed the statement about wildcards being supported from the parameter description.

Thanks for the feedback.

Closing
