### ISSUE TITLE
Provisioning for users that already have personal sites?

### ISSUE THREAD

**Issue by Craig-Humphrey** [MicrosoftDocs/office-docs-powershell#6761]
What happens if you request provisioning for a user that already has a personal site provisioned?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b3eac96-c242-c8fb-f9d6-4e3fe42f45ff
* Version Independent ID: 8173ce51-c1ef-50be-2069-1ccd3d0ab5b3
* Content: [Request-SPOPersonalSite (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/request-spopersonalsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @Craig-Humphrey Craig, how are you?
I tried that for you in my demo tenant, the cmdlet returned with no output as usual, I waited 24h and the site for the user did not appear to change.
Does that answers your question?
Thanks

**Comment by Craig-Humphrey** [comment]
Thanks @get-itips. Yeah, I tried the same thing - but just because visually nothing appeared to change on the users personal site, doesn't mean something hasn't changed in the background.

I just want to make sure it's OK to run this against all the users in my tenant and not worry about the ones that already have a personal site.

**Comment by get-itips** [comment]
> Thanks @get-itips. Yeah, I tried the same thing - but just because visually nothing appeared to change on the users personal site, doesn't mean something hasn't changed in the background.
> 
> I just want to make sure it's OK to run this against all the users in my tenant and not worry about the ones that already have a personal site.

Will try to reach the Team.

**Comment by WayneEwington** [comment]
Just confirming that a User can only have one OneDrive. As such we will "silently" ignore the request to provision another OneDrive if it already exists.

**Comment by get-itips** [comment]
> Just confirming that a User can only have one OneDrive. As such we will "silently" ignore the request to provision another OneDrive if it already exists.

Many thanks on the confirmation.

@yogkumgit please close

**Comment by Craig-Humphrey** [comment]
Awesome! Thanks @WayneEwington This time last year Damon and I were visiting you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Craig-Humphrey Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Craig-Humphrey** [comment]
Thanks @yogkumgit 
It would be nice if the documentation reflected @WayneEwington 's comment, so that other people looking to do the same thing don't have to hunt through the issues list to find the answer.

Thanks!
Craig

**Comment by get-itips** [comment]
> Thanks @yogkumgit
> It would be nice if the documentation reflected @WayneEwington 's comment, so that other people looking to do the same thing don't have to hunt through the issues list to find the answer.
> 
> Thanks!
> Craig

Will propose that thru a PR and we will see if it gets approval. Thank you
