### ISSUE TITLE
Import-RecipientDataProperty -SpokenName supported file formats

### ISSUE THREAD

**Issue by dtblodgett** [MicrosoftDocs/office-docs-powershell#6763]
The following command is used to import a recording of the spoken name for a user. 

`Import-RecipientDataProperty -Identity "Tony Smith" -SpokenName -FileData ([Byte[]]$(Get-Content -Path "M:\AudioFiles\TonySmith.wma" -Encoding Byte -ReadCount 0))`

The command supports .WMA and .PCM file formats. The Windows "Voice Recorder" app used to record in .WMA, but now records in .M4A format. It would be helpful for this command to accept the .M4A format so that users can use the tool provided in Windows for making a recording of their voice.

**Comment by dariomws** [comment]
Hello @dtblodgett, thanks for your feedback. 

For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/. There, your suggestion will reach the product team.

**Comment by dtblodgett** [comment]
I've submitted this feature request here:
[Import-RecipientDataProperty -SpokenName add support for M4A file format](https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/41794348-import-recipientdataproperty-spokenname-add-suppo)

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @dtblodgett Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
