### ISSUE TITLE
Get-TeamChannelUser : Channel not found

### ISSUE THREAD

**Issue by johanburati** [MicrosoftDocs/office-docs-powershell#6764]
I have installed the **MicrosoftTeams** module, version **1.1.5-preview**     

When using the **Get-Team** function it returns the expected results.

However when I use the **Get-TeamChannelUser** function with the <ins>exact same parameters</ins> as for the **Get-Team** function, 
it returns the following error: 

`Get-TeamChannelUser : Channel not found`

**Comment by johanburati** [comment]
I have tried with Channel s with Visibility set to either Public or Private, but none worked.

**Comment by get-itips** [comment]
Hello @johanburati 
When asked by the cmdlet for the -DisplayName parameter, did you input the name of the **channel** ? Because if you put the name of the Team, you receive the error that you described.
Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @johanburati Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
