### ISSUE TITLE
Page needs updating, missing some arguments such as SpaceType

### ISSUE THREAD

**Issue by mikedixson** [MicrosoftDocs/office-docs-powershell#6767]
Page needs updating, missing some arguments such as SpaceType

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af332a3-efc1-49aa-24c2-64b5031a2420
* Version Independent ID: f47bc209-aa9e-f337-1cfa-b8a727a9f780
* Content: [Set-Place (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-place?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by loryanstrant** [comment]
Not sure why this has been closed, as the SpaceType option is not listed:
![image](https://user-images.githubusercontent.com/51473494/202929028-778a8f4b-0cb6-462d-a4b2-313908c201ea.png)

**Comment by chrisda** [comment]
The referenced PR did add the parameter. I'm not sure why it didn't publish.

I added it again from a different direction (the private version of the repo). Let's see if that does it.
