### ISSUE TITLE
New-CsBatchPolicyPackageAssignmentOperation not Working anymore

### ISSUE THREAD

**Issue by gfournier04** [MicrosoftDocs/office-docs-powershell#6769]
Hi,

I have this problem for two weeks now, I can't assign any package through the Teams Module to any users of my tenant, I tried to reinstall the module on an other computer, I tried with the full mail @, I tried with the user ID but none of it is working.

The other commands works fine and I'm using the latest version (1.1.6)

I wonder if I'm the only one having this issue...

PS C:\WINDOWS\system32> New-CsBatchPolicyPackageAssignmentOperation -Identity 1900a2e2-3441-4857-b8fe-95df44b18808 -PackageName Education_Teacher
New-CsBatchPolicyPackageAssignmentOperation : Une ou plusieurs erreurs se sont produites.
Au caractère Ligne:1 : 1
+ New-CsBatchPolicyPackageAssignmentOperation -Identity 1900a2e2-3441-4 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-CsBatchPoli...gnmentOperation], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.TeamsCmdlets.PowerShell.Custom.NewCsBatchPolicyPacka
   geAssignmentOperation

Any help would be gladly accepted :) 

Cordially,

Gabe

**Comment by gfournier04** [comment]
Hello, is there any news concerning this issue ? Is it only me or is this a general problem ?

**Comment by get-itips** [comment]
Hello @gfournier04 
I tested the cmdlet to see if we need to impact any documentation based on your feedback, I am using module version 1.1.6, and had no issues at all.
I recommend opening a support ticket as here we are limited to documentation issues.
Hope this information helps you.
Thanks

**Comment by gfournier04** [comment]
Thanks a lot :) now I know the problem comes from me or my tenant.
I will try to fix my issue then
Best regards.

**Comment by get-itips** [comment]
> Thanks a lot :) now I know the problem comes from me or my tenant.
> I will try to fix my issue then
> Best regards.

Thanks for returning and sharing your feedback.
