### ISSUE TITLE
Teams PowerShell Preview Notes

### ISSUE THREAD

**Issue by BrianMcNeese** [MicrosoftDocs/office-docs-powershell#6771]
Please consider adding notes on each of these cmdlets indicating if they are currently only in the preview module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6804423b-8e08-5916-9355-6bebe8bb08b0
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [MicrosoftTeamsPowerShell Module](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @BrianMcNeese Brian, how are you?

That information was added here [Microsoft Teams PowerShell Release Notes - Cmdlet availability](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes#cmdlet-availability) recently.

Thanks for your feedback.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @BrianMcNeese Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
