### ISSUE TITLE
Missing parameters Set-CsTeamsMeetingPolicy

### ISSUE THREAD

**Issue by jakubZylak** [MicrosoftDocs/office-docs-powershell#6777]
Hi,
where i can find descriptions of these parameters Set-CsTeamsMeetingPolicy:

AllowIPAudio
AllowRecordingStorageOutsideRegion
AllowOrganizersToOverrideLobbySettings
AllowUserToJoinExternalMeeting
EnrollUserOverride
StreamingAttendeeMode
AllowBreakoutRooms
TeamsCameraFarEndPTZMode
AllowMeetingReactions

![Screenshot_1](https://user-images.githubusercontent.com/37347446/97811274-b8ae8e00-1c79-11eb-9f4d-5cac4f8ab485.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @jakubZylak 

How are you? AllowRecordingStorageOutsideRegion is already present in the [Set-CsTeamsMeetingPolicy](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps) article but not the others, adding them now, it can take some time for the article to be updated. Many thanks for your feedback.
