### ISSUE TITLE
New-PnPTeamsTeam wrong examples

### ISSUE THREAD

**Issue by PBuskermolen** [MicrosoftDocs/office-docs-powershell#6778]
Hello,

I just want to point out that the examples are wrong. They are about Get-PnPTeamsTeam but should be about New-PnPTeamsTeam.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f19f9ba-40cc-011b-5975-d3d6059769e3
* Version Independent ID: 0094ebb4-ca9a-147f-7f3f-fd63994397f3
* Content: [New-PnPTeamsTeam (SharePointPnPPowerShell)](https://docs.microsoft.com/en-gb/powershell/module/sharepoint-pnp/new-pnpteamsteam?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPTeamsTeam.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPTeamsTeam.md)
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @PBuskermolen 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @PBuskermolen Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
