### ISSUE TITLE
Remove  Set-CsTeamsInteropPolicy and New-CsTeamsInteropPolicy and update others.

### ISSUE THREAD

**Issue by kenwith** [MicrosoftDocs/office-docs-powershell#678]
The Set-CsTeamsInteropPolicy and New-CsTeamsInteropPolicy should be removed and the Grant, Remove, and Get should be updated with the following:

Also, we should update the remaining cmdlet topics for InteropPolicy to indicate that these are legacy cmdlets that will be retired. Furthermore:
•	These cmdlets will be replaced by TeamsUpgradePolicy, but during the transition they must still be used, in combination with TeamsUpgradePolicy (since some components honor interop and others honor upgrade)
•	Folks show only use 1 of the 3 instance where the values for chat and calling preferred clients are the same, and allow end user override =false.  The others are no longer valid supported configs.
•	If they customized their global interoppolicy, they should use remove-csteamsinteorppolicy to undo this.

**Comment by kenwith** [comment]
Removed the Set-CsTeamsInteropPolicy and New-CsTeamsInteropPolicy. @nsshommo  working on a PR to update the others as per PM. CC @arachmanGitHub

**Comment by nsshommo** [comment]
I am working on it.

**Comment by kenwith** [comment]
Saw this is live now! Thanks @nsshommo  and @arachmanGitHub . 

Here are links:

https://docs.microsoft.com/en-us/powershell/module/skype/get-csteamsinteroppolicy?view=skype-ps
https://docs.microsoft.com/en-us/powershell/module/skype/remove-csteamsinteroppolicy?view=skype-ps
https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsinteroppolicy?view=skype-ps

Closing this issue out.
