### ISSUE TITLE
New-CsGroupPolicyAssignment - Not applying anything

### ISSUE THREAD

**Issue by mrzyko** [MicrosoftDocs/office-docs-powershell#6794]
Is New-CsGroupPolicyAssignment released to early or is it me that is missing any steps.
I just cannot get New-CsGroupPolicyAssignment to work. 
I have a security group "Group1" and I want the members of that group to have a TeamsAppSetupPolicy "Policy1" applied. 
I am creating the policyassignment using the New-CsGroupPolicyAssignment

New-CsGroupPolicyAssignment -GroupId [groupid] -PolicyType TeamsAppSetupPolicy -PolicyName "Policy1" -Rank 1

And I believe I have given it the benefit of the doubt and waited 2 days, but still nothing applies. 

I can see the registration with
Get-CsGroupPolicyAssignment -PolicyType TeamsAppSetupPolicy

It pops up just fine. But using the Get-CsUserPolicyAssignment nothing ever gets applied to the users in that perticular group.

Is it a bug or is it me that is doing something wrong?

Documentation, that I try to follow:
https://docs.microsoft.com/en-us/microsoftteams/assign-policies#assign-a-policy-to-a-group

Best regards

Edit: Don't know if it is relevant, but it's an edu tenant

**Comment by philrice** [comment]
I have similar issues , also in a EDU tenant, were by a policy assignment we set back in July to our main staff groups  has stopped working. It was working without issues until late 2nd Nov or 3rd of Nov and now the a group assigned policy simply does not apply anymore. We have it assigned to 2 groups and both have stopped working without any changes being made to the configuration or related services that might effect it.
It certainly looks like something has changed in the last week that has broken this.

**Comment by get-itips** [comment]
Hello @mrzyko how are you?
I tested the cmdlet and had no issues to assign a policy to a group.
As here we are limited to documentation fixes, I suggest open a support ticket, they will be able to help you with your specific scenario.
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @mrzyko Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
