### ISSUE TITLE
-EnforceCapacity not documented

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/office-docs-powershell#6799]
When I execute `Get-CalendarProcessing | Select *` I can see the property `EnforceCapacity` This is currently undocumented. `Set-CalendarProcessing` also allows to pass the parameter `-EnforceCapacity $true` or `-EnforceCapacity $false` to the respective mailbox which again is missing any documentation here. I guess this is a new feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d95eb528-ab96-b415-981c-35d50c90dba0
* Version Independent ID: 0433f43b-538d-8000-a11d-69b4a5c97e0e
* Content: [Set-CalendarProcessing (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-calendarprocessing?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Weishaupt, thanks for the feedback. That new parameter (and another one) was waiting for approval to publish. Based on your feedback, I published the updates.
