### ISSUE TITLE
Document Update Request for the default value of parameter PublishEnabled

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/office-docs-powershell#6804]
Document Update Request for the default value of parameter PublishEnabled.

The value of parameter PublishEnabled is false by default and I confirmed this with engineering as oppose to what the documentation is saying as below and needs to be updated.

https://docs.microsoft.com/powershell/module/exchange/set-mailboxcalendarfolder

PublishEnabled
The PublishEnabled parameter specifies whether the specified calendar should be enabled for publishing. The default value is $true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 720289db-3b4d-a6f8-2fea-09317467bae2
* Version Independent ID: f987f693-7e54-d6f6-4f1a-49374b89550f
* Content: [Set-MailboxCalendarFolder (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxcalendarfolder?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-MailboxCalendarFolder.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@qaehtesh, I fixed it. But in the future, you too can make simple fixes like this yourself without the need to open an Issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell>. 

Thanks for the feedback.

Closing.

**Comment by qaehtesh** [comment]
Awesome, thank you Chris, i will take care of it onwards following above url
