### ISSUE TITLE
Parameter description Typo

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#681]
The description of the  -AGName param states "are being added", it should be "are being removed"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91e233cd-fcb2-61f7-497f-892750b8d911
* Version Independent ID: 4d8addc0-298a-e79d-6f20-c93dd7e4c1b6
* Content: [Remove-DatabaseFromAvailabilityGroup (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/remove-databasefromavailabilitygroup?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Remove-DatabaseFromAvailabilityGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Remove-DatabaseFromAvailabilityGroup.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
Submitted #757 for this.

**Comment by Techwriter40** [comment]
@bentoncity  Steve, who on the SQL Team can you ask about this parameter?

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

It looks like there was a merge request put in by Trevor that got approved and merged already so it looks like this is resolved. I am going to close this issue if this issue is not resolved please reopen the issue.
