### ISSUE TITLE
Suggest adding link to resume command

### ISSUE THREAD

**Issue by Lady-MCSE** [MicrosoftDocs/office-docs-powershell#6812]
Document is pretty good.  However there is a companion command to this one, which is to resume the service after it's been suspended. Suggest adding a link to that somewhere in this article.  

https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/resume-spenterprisesearchserviceapplication?view=sharepoint-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 543f3c98-c159-39db-dba3-2a5ad826dafe
* Version Independent ID: 72b0dab6-70e6-e2ba-dde6-160afe0d70f9
* Content: [Suspend-SPEnterpriseSearchServiceApplication (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/suspend-spenterprisesearchserviceapplication?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Suspend-SPEnterpriseSearchServiceApplication.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Suspend-SPEnterpriseSearchServiceApplication.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks for your feedback @Lady-MCSE
