### ISSUE TITLE
Link not clickable

### ISSUE THREAD

**Issue by dataCollegechurch** [MicrosoftDocs/office-docs-powershell#6814]
The link to this video isn't clickable [!Video https://www.youtube.com/embed/TMzHAWEQjlk]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b23d72-33ed-a6a1-a442-a5e5cf039f9f
* Version Independent ID: 4247cf37-3667-2007-7251-46ed80f58ef5
* Content: [Get started with the SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by dataCollegechurch** [comment]
submitted pull request

**Comment by get-itips** [comment]
> submitted pull request

can you link to it? thanks
