### ISSUE TITLE
RecordType entries should be further explained

### ISSUE THREAD

**Issue by qosobrin** [MicrosoftDocs/office-docs-powershell#6820]
Maybe you think RecordType entries are self explanatory but I do not feel like that 😄 .  Some times I have serious doubts of which one I should use. A couple of examples:

- is `SharePointFileOperation` also useful for folder activities? 
- for searching who deleted a file in a Microsoft 365 group, which RecordType should I use? `OneDrive` or `SharePoint`?

Of course I do not mean for you to answer these questions here. I think that a second page explaining the use of them as you did with the `Operations` parameter should be appreciated. Or maybe the same linked page would be enough.

Thank you very much.
Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75b757c9-b775-8294-91f7-870bead6a907
* Version Independent ID: 54ebab36-97bb-cd9f-6eb2-12198af885e2
* Content: [Search-UnifiedAuditLog (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/search-unifiedauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@qosobrin, I replaced the static list of values in the RecordType or RecordTypes parameter description with:

For details about the available values, see the RecordType property description in [Detailed properties in the audit log](https://docs.microsoft.com/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log).

In the following cmdlet reference topics:

- New-ActivityAlert
- Set-ActivityAlert
- Search-UnifiedAuditLog
- Get-UnifiedAuditLogRetentionPolicy
- New-UnifiedAuditLogRetentionPolicy
- Set-UnifiedAuditLogRetentionPolicy

Thanks for the feedback.

Closing.

**Comment by qosobrin** [comment]
Sorry to insist after closing the issue. With these changes now we do not have a reference of the available RecordTypes anywhere. I agree with your removing of the static list from the commandLet reference page but I think that data should be moved to the linked page, not completely removed.

Thank you very much.
Best regards.

**Comment by chrisda** [comment]
@qosobrin, believe it or not, those numbers in that topic are values for the RecordType parameter (you can use a numerical value or the text value). Coincidentally, I was speaking to the owner of that topic, and he suggested an even better target, which I used instead: <https://docs.microsoft.com/office/office-365-management-api/office-365-management-activity-api-schema#auditlogrecordtype>.

I was thinking of doing something like this a long time ago. It's difficult if not impossible to keep a long list of values like that synchronized between 6 different cmdlet reference topics. The target topic is now the one source of truth. In fact, the writer of <https://docs.microsoft.com/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log> is going to update the description for RecordType so it also points to <https://docs.microsoft.com/office/office-365-management-api/office-365-management-activity-api-schema#auditlogrecordtype>.

Also, be advised there are lots of **available** RecordType values, but many of them aren't hooked up, always return empty value, require external connectors, etc.

**Comment by qosobrin** [comment]
Thank you very much. It is much better now.

**Comment by chrisda** [comment]
Thanks for the feedback.

Closing
