### ISSUE TITLE
-TargetSharingEpr Missing

### ISSUE THREAD

**Issue by scottclarke1** [MicrosoftDocs/office-docs-powershell#6821]
-TargetSharingEpr as a parameter is missing from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffdead14-eab9-1f0e-4cf4-0036e9631b93
* Version Independent ID: 4b5f8e6a-4f93-859c-9360-708420f070dd
* Content: [Set-IntraOrganizationConnector (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-intraorganizationconnector?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-IntraOrganizationConnector.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-IntraOrganizationConnector.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@scottclarke1, added to New/Set-IntraOrganizationConnector. I copied and modified the existing description from New/Set-OrganizationRelationship, so [feel free to update the description](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md) if it's wrong.

Thanks for the feedback.

Closing
