### ISSUE TITLE
Error in command

### ISSUE THREAD

**Issue by theguru0** [MicrosoftDocs/office-docs-powershell#6826]
This:  Remove-SPClaimMapping "Email" | Get-SPIdentityProvider "LiveIDSTS"

Should be this I think:  Remove-SPClaimTypeMapping "Email" | Get-SPTrustedIdentityTokenIssuer "LiveIDSTS"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed910c3d-f022-8661-8efe-82ecf69b18d1
* Version Independent ID: cdc26b7d-89df-4b3e-329a-87e9dff7461b
* Content: [Remove-SPClaimTypeMapping (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/remove-spclaimtypemapping?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Remove-SPClaimTypeMapping.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Remove-SPClaimTypeMapping.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks for your feedback @theguru0
