### ISSUE TITLE
Please update the release notes to include changes in 2.0.4, as we're tracking a number of issues in 2.0.3

### ISSUE THREAD

**Issue by MushyMiddle** [MicrosoftDocs/office-docs-powershell#6827]
Please add change information for 2.0.4, or publish them as comments to this or other issues opened.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @MushyMiddle, thank you for your feedback and help us to improve docs.microsoft.com.

Version 2.0.4 is still in preview and the latest current (stable) release is 2.0.3. More information:
https://www.powershellgallery.com/packages/ExchangeOnlineManagement

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @MushyMiddle Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
