### ISSUE TITLE
Error on page

### ISSUE THREAD

**Issue by theguru0** [MicrosoftDocs/office-docs-powershell#6829]
[Enter feedback here]
-name doesn't seem to be a valid argument.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f874348e-9bde-381a-8736-e46233d88eea
* Version Independent ID: 10042bea-1a21-f423-db60-4c2f0703ff96
* Content: [Remove-SPTrustedRootAuthority (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/remove-sptrustedrootauthority?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Remove-SPTrustedRootAuthority.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Remove-SPTrustedRootAuthority.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Many thanks for your feedback @theguru0
