### ISSUE TITLE
cmdlet replacements not correct

### ISSUE THREAD

**Issue by paul9955** [MicrosoftDocs/office-docs-powershell#6832]
Hi, I submitted feedback a couple of weeks ago about two retiring cmdlets and you responded quickly -- thank you! It appears that the correction in the topic is not correct; I might have given you bad info. The edits are in this section:
https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#how-the-exo-v2-module-works in this table:

![image](https://user-images.githubusercontent.com/35980943/98875512-3cfad100-2431-11eb-8cb3-8fb37af81993.png)

This is incorrect, as there is no connection between briefing and MyAnalytics cmdlets. This should actually read as follows: 

Get-UserBriefingConfig   This cmdlet is being replaced by Get-UserAnalyticsConfig 
Set-UserBriefingConfig   This cmdlet is being replaced by Set-UserAnalyticsConfig 

Thank you, 
 -- Paul Schafer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@paul9955, OK. Updated as you described.

Thanks for the feedback.

Closing
