### ISSUE TITLE
What's the module name which has all these awesome commands?

### ISSUE THREAD

**Issue by Mike19130** [MicrosoftDocs/office-docs-powershell#6837]
Didn't see it on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2648ec32-2716-4f6e-20f1-1a989aa8cc45
* Version Independent ID: 53e81f24-1e27-9c50-439b-7916e7d1045d
* Content: [SkypeForBusiness Module](https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps)
* Content Source: [skype/skype-ps/skype/skype.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/skype.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @Mike19130 
You can find information on how to run these cmdlets in the introduction of the article:

> The following cmdlet references are for Skype for Business and Microsoft Teams. You can find information on installing the module for Skype for Business Online here: https://docs.microsoft.com/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell. If you are using Skype for Business Server then the cmdlets are available in the Skype for Business Server Management Shell and you can find information about it here: https://docs.microsoft.com/skypeforbusiness/manage/management-shell.

Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Mike19130 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
