### ISSUE TITLE
this article is incomplete.  not even a basic example.  :(

### ISSUE THREAD

**Issue by jdubyaeber** [MicrosoftDocs/office-docs-powershell#684]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a95f70-92ee-66e8-2cde-0d5b8551eb1e
* Version Independent ID: ab492b33-0d4e-778a-814a-ec7d7d918cf6
* Content: [Get-CsExternalUserCommunicationPolicy (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csexternalusercommunicationpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsExternalUserCommunicationPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsExternalUserCommunicationPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
@arachmanGitHub or @islubin  - do you know who could help @nsshommo with filling in the content?

**Comment by nsshommo** [comment]
@jdubyaeber Thanks for your suggestion. We are working on this.

**Comment by kenwith** [comment]
Just a quick update. This is in process to get examples for all Skype cmdlets. There are a number with no content and they will be updated.

**Comment by kenwith** [comment]
All Skype cmdlets are undergoing audit and being tracked internally to make sure every cmdlet has an example and descriptions.
