### ISSUE TITLE
Get-ExOMailboxFolderStatistics does not have a switch for 'IncludeAnalysis' - Update Example2

### ISSUE THREAD

**Issue by damianscoles** [MicrosoftDocs/office-docs-powershell#6841]
When you attempt to use the 'IncludeAnalysis' Switch, an error is thrown by the cmdlet:

_Get-ExOMailboxFolderStatistics : IncludeAnalysis is not a supported parameter.​
At line:1 char:1
+ Get-ExOMailboxFolderStatistics -Identity damian@practicalpowershell.c ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ProtocolError: (:) [Get-EXOMailboxFolderStatistics], RestClientException
    + FullyQualifiedErrorId : IncludeAnalysis is not a supported parameter.​,Microsoft.Exchange.Management.R
   estApiClient.GetExoMailboxFolderStatistics_

Can we get this removed from Example 2 of the cmdlet?  Also, the Get-Help for the cmdlet (v2.0.3 of ExchangeOnlineManagement) also lists this same switch in an example.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 082dca80-864a-0c24-f079-260a1004fb11
* Version Independent ID: b8cacf59-6ec6-bf43-acfb-871e251b2bb5
* Content: [Get-EXOMailboxFolderStatistics (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-exomailboxfolderstatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-EXOMailboxFolderStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-EXOMailboxFolderStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@damianscoles, done. The IncludeAnalysis parameter is available, but it returns the error you mentioned, so I included the parameter in the topic with the "reserved for internal Microsoft use" description. After a healthy investigation, there are ~16  of these "available, but don't work" parameters across ~5 of these Get-EXO cmdlets. I added and noted them accordingly.

Thanks for the feedback.

Closing
