### ISSUE TITLE
-ZapEnabled option not found?

### ISSUE THREAD

**Issue by duracellkonijn22** [MicrosoftDocs/office-docs-powershell#6842]
Hello

We are using Powershell to implement quick SPAM filter setting inside Office365, but recently we encountered the problem that the "-ZapEnabled" option is not found.

Is this option replaced with another option? On the document page here, the option is still available, but inside the command not anymore.

Thanks for feedback about this case.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164c3337-1862-be67-7e1d-ea8055b88791
* Version Independent ID: 3cb06add-3cb6-7cb8-779b-a681e03ab4fb
* Content: [Set-HostedContentFilterPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-hostedcontentfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by duracellkonijn22** [comment]
Hello

Thanks for the answer. The parameter is indeed completely gone. I've used it inside a powershell command but then i know now i can replace them with the two other parameters.

Kind regards

Hendrik
________________________________

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @duracellkonijn22 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
