### ISSUE TITLE
Not enough information to be successful 

### ISSUE THREAD

**Issue by Eric2XU** [MicrosoftDocs/office-docs-powershell#6843]
Due to a bug in the GUI I was not able to add a member to the case. I was relived to see a powershell cmdlet as a backup. That however was short lived. All this page says is to use Exchange Online Module. Note it doesnt say which one (the new v2 one or the old) nor does it bother to mention even after connecting using connect-exchangeonline you still must also use the following: 

Connect-IPPSSession -UserPrincipalName <UPN> [-ConnectionUri <URL>] [-PSSessionOption $ProxyOptions]

EVERY one of the compliance cmdlet docs pages should mention this as its not clear. I had to get MS Support involved to find this missing link. 

Please consider. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a16e2562-8b71-5e79-665d-09514fde6f26
* Version Independent ID: 2431c471-5d31-5c02-a070-7c3b50081250
* Content: [Add-ComplianceCaseMember (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/add-compliancecasemember?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Add-ComplianceCaseMember.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Add-ComplianceCaseMember.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Eric2XU, the first line of that topic (and every other Security & Compliance Center PowerShell only cmdlet reference topic) says:

> This cmdlet is available only in Security & Compliance Center PowerShell. For more information, see [Security & Compliance Center PowerShell](https://docs.microsoft.com/powershell/exchange/scc-powershell).

That brief topic contains everything you need to know, including a link to the [Connect to Security & Compliance Center PowerShell](connect-to-scc-powershell.md), which contains everything you need to know about how to connect.

**Comment by Eric2XU** [comment]
I still think you should make a note about it, the page saying it uses exchange module to someone who uses the exchange module would not realize to bother clicking the page that talks about how to connect to it. I mean these pages are to help people right? Here is a customer telling you this page failed to highlight an important fact. No only did this page fail me, it generated a call to support which I also believe is part of why these documents exist (to avoid such calls). I get it, I didnt read two pages deep to get the answer I was looking for, but how many more customers would do the same? This situation is unique due the fact these cmdlets are in the exchange module, if they were on their own module *(where the honestly should be) I would have went another link deep to find out how to install the module and connect.

**Comment by chrisda** [comment]
Essentially, what you're suggesting is replacing the existing "What is Security & Compliance Center PowerShell" link with a "How to connect to Security & Compliance Center PowerShell" link. Interesting idea. I'll think about it.

**Comment by chrisda** [comment]
Still thinking about it, but closing the issue for now.

Thanks for the feedback.
