### ISSUE TITLE
There isn't any command in "run this command in a Command Prompt:"

### ISSUE THREAD

**Issue by Ricasti** [MicrosoftDocs/office-docs-powershell#6852]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 020cb24c-1561-e16b-7652-88c9c40f5b11
* Version Independent ID: 8aeac288-74f9-36ea-3bbc-6e16399f7a34
* Content: [V1 module - Connect to Exchange Online PowerShell using MFA](https://docs.microsoft.com/en-us/powershell/exchange/v1-module-mfa-connect-to-exo-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/v1-module-mfa-connect-to-exo-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Ricasti, I presume you are referring to the third instance in the "Install the Exchange Online Remote PowerShell Module". That appeared to be a leftover reference that's no longer needed (all of that is already explained in the "What do you need to know before you begin?" section), so I removed it.

Thanks for the feedback.

Closing
