### ISSUE TITLE
  [-PreferenceMoveFrequency <TimeSpan>]  | upper limit

### ISSUE THREAD

**Issue by AbdallahmGalal** [MicrosoftDocs/office-docs-powershell#6856]
[Enter feedback here]

From a recent case opened with MS support, it was found that setting this value higher than 49.7 days is causing the MSExchangeRepl.exe to crash on all the DAG members. 

Upon investigation, it was found that the TimerConstructor when passed a value higher than 2^32-2 causes the service to crash with ArgumentOutOfRangeException

\\
[12:53:39] Exception: E0434F4D.System.ArgumentOutOfRangeException ("Time-out interval must be less than 2^32-2.")
[12:53:39] Dump 1 initiated: C:\Sources\Procdump(1)\msexchangerepl.exe_201112_125339.dmp
//

This limit is mentioned here as well.

https://docs.microsoft.com/en-us/dotnet/api/system.threading.timer.-ctor?view=net-5.0#System_Threading_Timer__ctor_System_Threading_TimerCallback_System_Object_System_TimeSpan_System_TimeSpan_

\\
Exceptions
ArgumentOutOfRangeException

The number of milliseconds in the value of dueTime or period is negative and not equal to Infinite, or is greater than MaxValue.
(Int32.MaxValue)
//

What i suggest to add an upper limit to the parameter in this doc. and not leaving it up to the user to set any time value. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525f60d1-1dbe-a6ab-e559-783808d84dfe
* Version Independent ID: da93731f-2fc2-5422-ea20-feda192a62d5
* Content: [Set-DatabaseAvailabilityGroup (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-databaseavailabilitygroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-DatabaseAvailabilityGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-DatabaseAvailabilityGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@AbdallahmGalal, based on what you are saying, is the existing statement in the parameter description valid or invalid?

To disable this feature, specify the value `([System.Threading.Timeout]::InfiniteTimeSpan)`.

**Comment by AbdallahmGalal** [comment]
Hi Chris,

I ‘ve not tested that personally but I assume yes, this parameter turns off the feature completely.

If you want to keep it running, then the admin should provide a value,  and this is left open in this doc. with no cap however in reality the value can’t be higher than 49.7 days as the max value for 32bit timespan object, otherwise the MSExchangeRepl service will start crashing with and this what I would like to be added here.


Thanks,
Abdallah

**Comment by chrisda** [comment]
Thanks, I'll leave that line in there.

I updated the topic as you described.

Thanks for the feedback.

Closing

**Comment by AbdallahmGalal** [comment]
When this will reflect in the online version?

**Comment by chrisda** [comment]
Sorry, I forgot to merge Master to Live. It should be visible within a few minutes.
