### ISSUE TITLE
Remove-ManagementRoleEntry doesn't accept value from pipeline in Exchange Online

### ISSUE THREAD

**Issue by itpro-tips** [MicrosoftDocs/office-docs-powershell#6858]
The parameter _Identity_ is indicated as _Accept pipeline input:_
In Exchange Online, this is not true:
`Cannot process argument transformation on parameter 'Identity'. Cannot convert value "Contacts-Creation" to type "Microsoft.Exchange.Configuration.Tasks.RoleEntryIdParameter"`

Another blog says the same: https://blog.rmilne.ca/2015/02/05/remove-multiple-management-role-entries-in-office-365/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d760744d-639f-d7d7-1825-d5002fb2bb1f
* Version Independent ID: 7fc35269-6374-d246-014c-72e7ca840225
* Content: [Remove-ManagementRoleEntry (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-managementroleentry?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-ManagementRoleEntry.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-ManagementRoleEntry.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@itpro-tips, you're right, but I'm unsure of what to do about it.

It turns out this is a remote PowerShell problem; using the Exchange Management Shell in an on-prem Exchange server works fine.

```powershell
Get-ManagementRoleEntry Level1-HelpDesk\Set-Mail* | Remove-ManagementRoleEntry
```

Running that same command while connected to the same server using remote PowerShell results in an error.

**Comment by yogkumgit** [comment]
@ Thank you very much forsharing this explanation. @itpro-tips If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
