### ISSUE TITLE
get-mailboxfolder doesn't work in EXO

### ISSUE THREAD

**Issue by nExoRek** [MicrosoftDocs/office-docs-powershell#6859]
examples show usage: get-MailboxFolder -identity Tony and get-MailboxFolder -identity Tony: to get the list of the folders.
i tired all combination - alias,primarySMTP,sam,upn with colon, without it, with colon and slash :\, only slash... 
it always returns:
Cannot convert value to type "Microsoft.Exchange.Configuration.Tasks.MailboxFolderIdParameter"

when running get-MailboxFolderStatistics i receive identites - and using these identities doesn't work as well. there definitely is some glitch is EXO and this commandlet.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b05294a-0b57-692a-1f91-abea30d4d07e
* Version Independent ID: e7c10ed6-8c11-6431-bdf2-f29b9d2b12a8
* Content: [Get-MailboxFolder (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailboxfolder?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailboxFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MailboxFolder.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@nExoRek, I can see the confusion. From the topic:

> Use the Get-MailboxFolder cmdlet to view folders in your own mailbox. Administrators can't use this cmdlet to view folders in other mailboxes (the cmdlet is available only from the MyBaseOptions user role).

I updated the examples to not specify the MailboxID. The way the examples were previously written, they would only work if you were the user 'Tony'. Since you're always operating on your own mailbox, you don't need to (or can't) specify the mailbox.

Thanks for the feedback.

Closing
