### ISSUE TITLE
Connection status

### ISSUE THREAD

**Issue by srekkas** [MicrosoftDocs/office-docs-powershell#6866]
How to get  Connect-ExchangeOnline status, so I can add some logic if application already connected or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@srekkas, you can use Get-PSSession to find the connection status:

```powershell
 PS C:\Users\chrisda> Get-PSSession

 Id Name            ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            ------------    ------------    -----         -----------------     ------------
  1 ExchangeOnli... outlook.offi... RemoteMachine   Opened        Microsoft.Exchange       Available

PS C:\Users\chrisda> Disconnect-ExchangeOnline
Disconnected successfully !
PS C:\Users\chrisda> Get-PSSession
PS C:\Users\chrisda>
```

**Comment by srekkas** [comment]
Ok, thanks
