### ISSUE TITLE
On this page the -filter switch takes about an example and then doesn't list an example.  No examples anywhere on the article

### ISSUE THREAD

**Issue by Wardo99** [MicrosoftDocs/office-docs-powershell#6867]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d30e4426-1f64-e5aa-4e40-f844ec04163e
* Version Independent ID: b2b90bad-0215-4569-72c3-5de4fed16a35
* Content: [Get-CsTeamsMeetingBroadcastPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csteamsmeetingbroadcastpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsTeamsMeetingBroadcastPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTeamsMeetingBroadcastPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for the feedback @Wardo99
