### ISSUE TITLE
Set-PnPListItem not working for Created, Modified or Editor

### ISSUE THREAD

**Issue by Craig-Humphrey** [MicrosoftDocs/office-docs-powershell#6870]
Not entirely sure if this is the right place (it seems to have sent me to the documentation GitHub, instead of the Uservoice...) but I'll log it here first (I know MS watch this and act on it) and then see if I can find something on Uservoice.

Back in the day, if you were using traditional SharePoint PowerShell to create new items in a list/library, you had to put Created, Author, Editor and Modified into a separate update statement, after the item had been created.

I'm now trying to do the same thing in PnP with SharePoint Online, but I'm finding that Created, Modified and Editor will not update.

Author is fine.

I should still be able to update these fields right?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3efa2d-f7d5-d9d0-d306-7707e4906065
* Version Independent ID: f30dd9c9-c9fc-f3f9-d5f4-ee4e1b8d3f53
* Content: [Set-PnPListItem (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItem.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
How are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by Craig-Humphrey** [comment]
Thanks @get-itips 

I found a an old report of this issue [HERE ](https://github.com/pnp/PnP-PowerShell/issues/2016)and a more recent one [HERE](https://github.com/pnp/PnP-PowerShell/issues/2916).  So sounds like it's a problem that's been around for a while and hasn't been addressed.

Perhaps the documentation could be updated, in the mean time, to reflect the short-coming?

Thanks
Craig

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Craig-Humphrey  as directed kindly open PnP cmdlets issues in that repository,  We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
