### ISSUE TITLE
Obsolete info

### ISSUE THREAD

**Issue by simon-scym** [MicrosoftDocs/office-docs-powershell#6872]
Hi there, the document suggest to use the Legacy Apps for the API Rights, unfortunately Exchange is no longer listed in the Legacy apps.  Can you update with the new way to do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@simon-scym, this is a known issue, and is already being tracked in #6865.

Thanks for the feedback.

Closing
