### ISSUE TITLE
API permissions - "Exchange" under "Supported legacy APIs" missing

### ISSUE THREAD

**Issue by borismilincic** [MicrosoftDocs/office-docs-powershell#6873]
The screenshot in step 2 is wrong. There is no "Exchange" under "Supported legacy APIs" anymore (it was there a couple of weeks ago). I found the Exchange API when I changed to the tab "APIs my organization uses" and searched for the API ID (00000002-0000-0ff1-ce00-000000000000 in this case). This should be reflected in the article.

Other question: As this was listed in the "Supported legacy APIs" section before, is there a date when this will stop working? If so, where is it documented? Is there a way to use other APIs when using a service principal to manage Exchange Online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Duplicate of #6865
