### ISSUE TITLE
Can't select 'Legacy Exchange API permissions' and / or Exchange.ManageAsApp

### ISSUE THREAD

**Issue by ronnyholtmaat** [MicrosoftDocs/office-docs-powershell#6874]
Hi,

When configuring in my AAD P1 tenant, following Step 2, Task number 5.

In the process of selecting API permissions, I can't select **Exchange** in the  **Supported legacy APIs** (no longer supported?)
Or _"In the Select permissions section that appears on the page, expand Exchange and select **Exchange.ManageAsApp**"_

Is there a Microsoft Graph API Alternative for App-only authentication for unattended scripts in the EXO V2 module?
Or for **Exchange.ManageAsApp** API permissions?

Or, how do we go about setting up App-only authentication for unattended scripts in the EXO V2 module without the Exchange Legacy API and with Microsoft Graph API

Thanks & greetings,

Ronny

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#step-2-assign-api-permissions-to-the-application)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Duplicate of #6865
