### ISSUE TITLE
Missing Cmdlet: Get-CsUnassignedNumber

### ISSUE THREAD

**Issue by psrarey** [MicrosoftDocs/office-docs-powershell#6876]
Modules:
  MicrosoftTeams v1.1.6
I've dug around some and don't find the subject cmdlet. Not even in the crumbs downloaded after session connect. 
I'm using other cmdlets in the SkypeForBusiness set that is no part of the Teams module, and they're working fine. 
Just the Get-CsUnassignedNumber cmdlet is missing.

**Comment by get-itips** [comment]
Hello @psrarey Paul

The cmdlet corresponds to SfB On-Premises

https://docs.microsoft.com/en-us/powershell/module/skype/get-csunassignednumber?view=skype-ps

> Applies to:
Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @psrarey Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
