### ISSUE TITLE
missed file size limit documentation

### ISSUE THREAD

**Issue by beliaev-maksim** [MicrosoftDocs/office-docs-powershell#6879]
No file size limit is mentioned in official docs. However this method does not allow to download large files
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1494ac7-090d-db80-ba26-5cdcc10d9eac
* Version Independent ID: e3837ec6-d90c-35c4-a563-4313ffb11fb6
* Content: [Get-PnPFile (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpfile?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFile.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
How are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by beliaev-maksim** [comment]
@get-itips ,
sure, will do, I reached current page from official MS site by clicking "Submit and view feedback for this page"

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @beliaev-maksim Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
