### ISSUE TITLE
Poor Performance

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#688]
Iunderstand what happens behind the scenes when running Update-SPProfilePhotoStore and generating 3 files for each user in the store takes time. However, could you please advise if there any way to speed up Update-SPProfilePhotoStore or what may affect its performance? I have tried to run this cmdlet  after updating 3 users only as well as having "NoDelete" set to true.
The performance appears to be very inconsistent. Once it would it take 5 minutes after single user update and the other time I would have to wait for 25 minutes for Update-SPProfilePhotoStore to complete runnig.
Is the process is being logged on so I can see if there any issues?

Your help is very much appreciated.

Thank you,
Yuriy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 381c8766-2135-0838-c5e8-f1b3d739ebef
* Version Independent ID: 9f5b0ee1-ef63-e27b-dca5-4412f7aa631a
* Content: [Update-SPProfilePhotoStore (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/update-spprofilephotostore?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Update-SPProfilePhotoStore.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Update-SPProfilePhotoStore.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@YuriySamorodov Thank you for this feedback

I want to make sure the inconsistence of this update gets addressed properly. Support can handle this issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
