### ISSUE TITLE
I am running SP2019 on an Azure SQL Managed Instance and the Example code that you provide on this page errors with this error:  Remove : The term 'Remove' is not recognized as the name of a cmdlet, function, script  file, or operable program. Check the spelling of the name, or if a path was included,  verify that the path is correct and try again.

### ISSUE THREAD

**Issue by rvahaver** [MicrosoftDocs/office-docs-powershell#6881]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af7eded9-6781-5917-4c8b-26b7fc29798e
* Version Independent ID: f791183e-71ea-e450-4137-5833d4d9161a
* Content: [Remove-SPSecureStoreApplication (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/remove-spsecurestoreapplication?view=sharepoint-ps&source=docs)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Remove-SPSecureStoreApplication.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Remove-SPSecureStoreApplication.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks for your feedback, the example has a typo, fixing thru a pull request.
