### ISSUE TITLE
Strong cryptography required before installing module

### ISSUE THREAD

**Issue by MSCM-GitHub** [MicrosoftDocs/office-docs-powershell#6882]
To install the module, I had to set strong cryptography. I used the help from this MS forum:
https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/trying-to-install-program-using-powershell-and/4c3ac2b2-ebd4-4b2a-a673-e283827da143

Quote:

1. Open Powershell and check for supported protocols by using[Net.ServicePointManager]::SecurityProtocol
2. Run the following 2 cmdlets to set .NET Framework strong cryptography registry keys:
Set strong cryptography on 64 bit .Net Framework (version 4 and above)

Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

set strong cryptography on 32 bit .Net Framework (version 4 and above)

Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

3. Restart Powershell and check again for supported protocol by using [Net.ServicePointManager]::SecurityProtocol

Apart from that, everything else was successful. Very good page. Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MSCM-GitHub, can you please describe your environment (Windows and PowerShell versions) and any error messages you received? The module has been available for a while, and yours is the first description of this problem. Thanks.

**Comment by MSCM-GitHub** [comment]
I am using Windows Server 2016 Standard v1607. And PS Version: 5.1.14393.3866.
To return to the original situation, I exported and deleted the keys I added.
Then in PS (as Administrator) (note, I added a quote mark (') at the start of each PS line to prevent detected formatting):
'>[Net.ServicePointManager]::SecurityProtocol
'Ssl3,Tls
'>Install-Module -Name ExchangeOnlineManagement -RequiredVersion 2.0.3
'WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
'PackageManagement\Install-Package : No match was found for the specified search criteria and module name
''ExchangeOnlineManagement'. Try Get-PSRepository to see all available registered module repositories.
'At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
'+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
'+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'+ CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
'+ FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
'>[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
'>[Net.ServicePointManager]::SecurityProtocol
'Tls12
'> Install-Module -Name ExchangeOnlineManagement -RequiredVersion 2.0.3
'>

No error is shown, and I can run the Install-Module command successfully.
I reapplied the exported registry keys.
In PS:
'>PS N:\> [Net.ServicePointManager]::SecurityProtocol
'Tls, Tls11, Tls12
'>Connect-ExchangeOnline -UserPrincipalName administrator@mscmltd.co.uk -ShowProgress $true
'Prompted for credentials.

**Comment by chrisda** [comment]
@MSCM-GitHub, so would you say that some type of note that says the following would be sufficient?

If you  get an error when you try to installing the module, run the following command:

```PowerShell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

**Comment by chrisda** [comment]
@MSCM-GitHub, any comments?

**Comment by MSCM-GitHub** [comment]
Hi @chrisda,

I would instruct like this:

"
If you get an error when you trying to install the module, run the following commands:

1: Check security protocols> [Net.ServicePointManager]::SecurityProtocol
2: Change security protocol to Tls1.2> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
3: Check security protocols> [Net.ServicePointManager]::SecurityProtocol
4: Install Exchange module: Install-Module -Name ExchangeOnlineManagement -RequiredVersion 2.0.3
5: Set strong cryptography on 64 bit .Net Framework (version 4 and above)> 
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
6: Set strong cryptography on 32 bit .Net Framework (version 4 and above)> 
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
7: Restart Powershell and check security protocols> [Net.ServicePointManager]::SecurityProtocol
"

Does this help?

**Comment by chrisda** [comment]
@MSCM-GitHub, yes it does. I updated the topic to the degree that I'm comfortable.

Thanks for the feedback.

Closing
