### ISSUE TITLE
Remove-CalendarEvents Without Cancellation 

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#6886]
Hi,

It looks like as of now `Remove-CalendarEvents` works the same way as if a real user cancels a meeting. Attendees get cancellation when a meeting gets removed with `Remove-CalendarEvents`. 
It would be great if `Remove-CalendarEvents` operates silently and does not generate cancellation.

Kind regards,
Yuriy

**Comment by get-itips** [comment]
Hello @YuriySamorodov how are you?
The [cmdlet help](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-calendarevents?view=exchange-ps) describes that meeting cancellations must be sent, if you want to propose another behavior I would suggest to submit the idea to [365 uservoice](https://office365.uservoice.com/).

Thanks

**Comment by yogkumgit** [comment]
@YuriySamorodov  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
