### ISSUE TITLE
The AllowRMSSupportForUnenlightenedApps switch is not applicable to on-premises Exchange.

### ISSUE THREAD

**Issue by svajda** [MicrosoftDocs/office-docs-powershell#6887]
The **AllowRMSSupportForUnenlightenedApps** switch of Set-ActiveSyncOrganizationSettings is not applicable to on-premises Exchange 2016/2019. Even if AllowRMSSupportForUnenlightenedApps is set to $true, the setting does not take effect in on-premises Exchange. This has been checked and validated on the source code level - feel free to contact me for details.

Please change the article so that the "Applies to" section for the AllowRMSSupportForUnenlightenedApps parameter shows only "Exchange Online". Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4042456f-c491-ad7d-e772-eef18ba6b0df
* Version Independent ID: 15a4ec1c-16b0-8516-ab4a-4564adac5c62
* Content: [Set-ActiveSyncOrganizationSettings (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-activesyncorganizationsettings?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-ActiveSyncOrganizationSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-ActiveSyncOrganizationSettings.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@svajda, I checked on an Exchange 2016 CU18 server and an Exchange 2019 CU7 server, and the _AllowRMSSupportForUnenlightenedApps_ parameter is available, whether it works or not, or whether it's supposed to be available or not.

I'll decorate the description accordingly; something like, "This parameter is available or functional only in the cloud-based service."

If/when the parameter is no longer available in Exchange 2016/2019, we can update the Applicable metadata and change the description to say the more standard, "This parameter is available only in the cloud-based service."

**Comment by chrisda** [comment]
Topic has been updated.

Thanks for the feedback.

Closing
