### ISSUE TITLE
Basic authentication still required for WinRM

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/office-docs-powershell#6888]
Modern authentication still requires Basic Authentication in the WinRM module.  This feels a lot like WINS service that Microsoft told us we could turn off... unless we used Exchange (which was every enterprise customer, who had WINS on).  How about the Server/Exchange team catch up and with this **core** functionality.

This is a very confusing documentation when SecureScore tell use to turn off Basic Authentication, but it breaks our management of Exchange even when we use V2!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@D-Jeffrey, you're right; it is confusing. But, we try to explain the situation in the [Prerequisites](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#prerequisites-for-the-exo-v2-module) section:

> WinRM needs to allow Basic authentication (it's enabled by default). We don't send the username and password combination, but the Basic authentication header is required to send the session's OAuth token, since the client-side WinRM implementation has no support for OAuth.

So, it's really more of a Windows PowerShell/WinRM thing than Exchange. It's unclear to me if eventual support for PowerShell 7 (currently in the Preview versions of the module) will eliminate this 'Basic auth for WinRM' requirement.

**Comment by chrisda** [comment]
Confirmed that the Basic auth dependency in WinRM is not going away. I'm asking the Secure Score folks if they can add some kind of explanation text to the results when Secure Score finds Basic auth enabled in WinRM. Not much more that I can do on my end or from a documentation perspective.

**Comment by D-Jeffrey** [comment]
Excellent, thanks for clearing up the opposing and confusing statements.

We will call this good and closed.

**Comment by yogkumgit** [comment]
@D-Jeffrey Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
