### ISSUE TITLE
Why is there an empty "PowerShell"

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6889]
As title says.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79aa5ead-5aef-c9f9-4802-944b32c9642e
* Version Independent ID: dfe8195a-d7ad-478d-dafd-574c6bb9e3e1
* Content: [Get-SPOGeoMoveCrossCompatibilityStatus (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spogeomovecrosscompatibilitystatus?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoMoveCrossCompatibilityStatus.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoMoveCrossCompatibilityStatus.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for your report @hwkwicre
