### ISSUE TITLE
Any Support for Azure Shell?

### ISSUE THREAD

**Issue by ashah7** [MicrosoftDocs/office-docs-powershell#6891]
There does not seem to be a Connect-IPPSession on the cloud shell?

**Comment by yogkumgit** [comment]
@ashah7 Please give the detail of the document you are referring to. Thanks.

**Comment by yogkumgit** [comment]
@ashah7 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
