### ISSUE TITLE
The "User" parameter for Get-EXOMailboxPermission is case sensitive

### ISSUE THREAD

**Issue by Nathaniel-Clark** [MicrosoftDocs/office-docs-powershell#6892]
`Get-EXOMailboxPermission "mailbox_owner@contoso.com" -User "Mailbox_Delegate@contoso.com"` returns the delegate user object along with their permissions:

Identity: Mailbox Owner
User: Mailbox_Delegate@contoso.com
AccessRights: {FullAccess}
IsInherited: False
Deny: False
InheritanceType: All

In this case, we can see that the delegate object has capital letters in their SMTP Address. If we use only lower case letters for the "-User" parameter and execute the same cmdlet then the following error occurs:

```
Get-EXOMailboxPermission "mailbox_owner@contoso.com" -User "mailbox_delegate@contoso.com"

Get-ExoMailboxPermission : An error occurred while processing this request..
     CategoryInfo          : ProtocolError: (:) [Get-EXOMailboxPermission], Exception
     FullyQualifiedErrorId : One or more errors occurred.,Microsoft.Exchange.Management.RestApiClient.GetExoMailboxPermission
```

The same error also occurs if you try to obtain the delegate user object using their name (in this example, Mailbox Delegate or mailbox delegate). The older cmdlet, Get-MailboxPermission, does not have this behavior. It returns the delegate user object in both scenarios and therefore it looks like this is a bug.  If this is the desired behavior, please consider updating the [documentation](https://docs.microsoft.com/en-us/powershell/module/exchange/get-exomailboxpermission?view=exchange-ps).

Exchange Online Management version: 2.0.3

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@Nathaniel-Clark, I'm told this is a known bug. But, I still added a note in the User parameter description.

Thanks for the feedback.

Closing
