### ISSUE TITLE
Example 1 incorrect

### ISSUE THREAD

**Issue by rakova17** [MicrosoftDocs/office-docs-powershell#6893]
Example 1 on this page is incorrect.

This:

Get-PnPRecycleBinItem | ? **FileLeafName** -like "*.docx" | Clear-PnpRecycleBinItem

Should be:

Get-PnPRecycleBinItem | ? **LeafName** -like "*.docx" | Clear-PnpRecycleBinItem

This was previously closed as an issue almost a year ago and I don't really get why: https://github.com/MicrosoftDocs/office-docs-powershell/issues/2770

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b3be08-c28b-f8a9-fc2f-418084aeac00
* Version Independent ID: 89967280-3b45-01d3-99c5-e9854da371fa
* Content: [Clear-PnPRecycleBinItem (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/clear-pnprecyclebinitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Clear-PnpRecycleBinItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Clear-PnpRecycleBinItem.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
How are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by rakova17** [comment]
Done, thank you: https://github.com/pnp/PnP-PowerShell/issues/3015

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @rakova17 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
