### ISSUE TITLE
Set-SPOSite parameter DisableFlows is invalid

### ISSUE THREAD

**Issue by ssandu** [MicrosoftDocs/office-docs-powershell#6894]
DisableFlows param is invalid in cmdlet Set-SPOSite when running on Group and OneDrive site collections. According to error message
Set-SPOSite : https://my.shell.com/personal/sanil_paul_shell_com is a OneDrive for Business site collection. The
only valid parameters for this type of site collection are '-Identity', '-AllowDownloadingNonWebViewableFiles',
'-AllowEditing', '-ConditionalAccessPolicy', '-DefaultLinkPermission', '-DefaultSharingLinkType',
'-DisableCompanyWideSharingLinks', '-LimitedAccessFileType', '-LockState', '-Owner', '-SharingAllowedDomainList',
'-SharingBlockedDomainList', '-SharingCapability', '-SharingDomainRestrictionMode',
'-ShowPeoplePickerSuggestionsForGuestUsers', '-StorageQuota', and '-StorageWarningLevel'.
We should write this on parameter properties/details.

**Comment by get-itips** [comment]
Thanks for your feedback, will propose that adding to the documentation.
