### ISSUE TITLE
 The allowable values are missing for the following parameters -BroadcastAttendeeVisibilityMode and -BroadcastRecordingMode 

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/office-docs-powershell#6898]
The allowable values are missing for the following parameters -BroadcastAttendeeVisibilityMode and -BroadcastRecordingMode 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88452508-477e-525e-f957-3130a918faa9
* Version Independent ID: acc5d34f-84ec-5dbf-99b7-736034433393
* Content: [Set-CsTeamsMeetingBroadcastPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingbroadcastpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingBroadcastPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingBroadcastPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for your feedback @nikki-c
