### ISSUE TITLE
-AllowImmersiveReader is missing

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/office-docs-powershell#6904]
the -AllowImmersiveReader is missing from CsTeamsGuestMessagingConfiguration
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11552ca9-2004-45a6-d9fb-c7a0334028f2
* Version Independent ID: 06f9ced8-acf3-3ec6-0df9-a121eb4f49b5
* Content: [Set-CsTeamsGuestMessagingConfiguration (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsguestmessagingconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsGuestMessagingConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsGuestMessagingConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for your feedback! @nikki-c
