### ISSUE TITLE
Cmdlet accepts displayname as identity value which is NOT UNIQUE!

### ISSUE THREAD

**Issue by chwilfing** [MicrosoftDocs/office-docs-powershell#6905]
The comdlet does not accept an useridvalue as parameter for the identity, it accepts exactly the displayname of a user which is - not unique! this means -

first of all - it's just stupid to not take userprincipalname or an object id which would be unique
second - the documentation is just wrong

it would be really great if somebody could fix the cmdlet, but it would be also very cool if somebody can fix the underlying problem. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2682266b-6d92-0218-1304-a42f0388933a
* Version Independent ID: c280f178-0724-5d16-37b4-db4b62da8ece
* Content: [Grant-CsTeamsAppSetupPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsappsetuppolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsTeamsAppSetupPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsTeamsAppSetupPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @chwilfing Christoph, how are you?
Here, we are limited to documentation changes, for your feedback, I need to ask you to visit and please create a [uservoice entry here](https://microsoftteams.uservoice.com/), that way, it can reach the product team behind the cmdlet.
Thank you

**Comment by yogkumgit** [comment]
@chwilfing Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
