### ISSUE TITLE
Outlook add-ins: Is there a limit for the the user list?

### ISSUE THREAD

**Issue by yobougaz** [MicrosoftDocs/office-docs-powershell#6912]
How many users can we have in the **-UserList** since we cannot add distribution groups?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c23be67f-a704-0f14-40df-6c174c8914e8
* Version Independent ID: ac2fc769-a7db-01e0-2590-68af5cfbbadd
* Content: [New-App (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-app?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-App.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-App.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@yobougaz @dariomws, in looking at the _UserList_ parameter description in [Set-App](https://docs.microsoft.com/powershell/module/exchange/new-app), the limit is 1000 users.

I'll add this information to the _UserList_ parameter description in New-App.

Thanks for the feedback.

Closing
