### ISSUE TITLE
deny user permission to modify distribution group in outlook web app 

### ISSUE THREAD

**Issue by sachinoda** [MicrosoftDocs/office-docs-powershell#6913]
Hi -I want limit /to restrict users to modify the distribution in the outlook web app group please help me with the power shell command

**Comment by chrisda** [comment]
@sachinoda, any sort of 'allow' or 'deny' in Exchange or Exchange Online always involves role-based access control (RBAC).

Does this topic help?

[How to prevent users from creating and managing distribution groups in Office 365](https://docs.microsoft.com/exchange/troubleshoot/groups-and-distribution-lists/prevent-users-create-manage-dg)

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @sachinoda Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
