### ISSUE TITLE
Feature request - ForceOAuth parameter for Connect-SPOService

### ISSUE THREAD

**Issue by mariussm** [MicrosoftDocs/office-docs-powershell#6915]
Currently it is not possible to run an Azure Function that loads the SharePoint module and use a user account to connect using Connect-SPOService. This is because the ForceOAuth parameter must be set in registry, and the registry is read only in Azure Functions.

There is no workaround other than patching the Microsoft.Online.SharePoint.PowerShell.dll, changing an if in InstantiateSPOService.

A very simple patch to Microsoft.Online.SharePoint.PowerShell.dll, adding a new parameter to Connect-SPOService called "ForceOAuth", that adds the ForceOAuth parameter to InstantiateSPOService, would solve this issue.

Also, even though functions are dotnetcore, the module runs just fine using Import-Module $moduleFile -DisableNameChecking **-UseWindowsPowerShell**

**Comment by get-itips** [comment]
Hello @mariussm Marius, how are you?
Here, we are limited to documentation issues, if you want your request to reach the product team, please visit [SharePoint Online uservoice](https://sharepoint.uservoice.com/) that way, it can reach the product team behind the module.
Thanks

**Comment by yogkumgit** [comment]
@mariussm Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
