### ISSUE TITLE
MailboxRegion parameter is not dedicated to MS

### ISSUE THREAD

**Issue by LuisEmilioR** [MicrosoftDocs/office-docs-powershell#6918]
-mailboxregion is not dedicated to Microsoft.

This parameter is key to create cloud mailbox on specific Geos, without it there is no other way to do it specially for Room, Equipment and other type of non human mailboxes.

Furthermore this parameter is available to users today.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1aa38f7-88eb-7d2e-0ed6-efc3186eb96b
* Version Independent ID: 0dcef152-ab12-c711-742d-5d4e570ea075
* Content: [New-Mailbox (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@LuisEmilioR, I updated the _MailboxRegion_ parameter description in New-Mailbox and Set-Mailbox. For reference, the _MailboxRegion_ parameter is also available on the following cmdlets, but I don't think it applies/works:

- New/Set-MailUser
- New/Set-UnifiedGroup (Microsoft 365 Groups)

Thanks for the feedback.

Closing
