### ISSUE TITLE
Add descriptions

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6922]
Some only has PARAMVALUE for example:

-DisableAppViews
PARAMVALUE: Unknown | Disabled | NotDisabled

I think it would be helpful to add (at least links to) explanations on what App Views is,
And other parameters that only has PARAMVALUE needs more explanations too.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c62bf4a-ac47-96ce-33fb-0d5ea9b178ae
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?preserve-view=true&view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks @hwkwicre
