### ISSUE TITLE
Issue with releasing memory after using Connect-ExchangeOnline - Disconnect-ExchangeOnline not releasing resources

### ISSUE THREAD

**Issue by ananimesh** [MicrosoftDocs/office-docs-powershell#6924]
We are trying to migrate to Exchange Online V2 module(EXO V2) from EXO V1. However, when we connect using the Connect-ExchangeOnline cmdlet, we observe the memory utilization goes to around ~200MB for the process.

We do this from C# code. However, doing the same from powershell.exe also gives us similar observation.

Post connect, we call the Disconnect-ExchangeOnline. We were under the impression calling the Disconnect-ExchangeOnline cmdlet should release the resources\memory. However. we don't see this happening. The memory utilization does not change.

Setting the CommandName parameter does use less memory. But still the memory is not getting released unless we exit the process.

Same connection establishing in V1 does not consume so much memory. For our solution we need to make continuous calls to O365 for different tenants. Our observation has been over a period of time this memory utilization keeps adding up and we end up running out of memory.

We tried to dispose the runspace, abort the thread etc. But unless the process is killed, the memory is not reclaimed.

We needed some pointers for this memory utilization. How can be make the EXO V2 connect call release the memory it has reserved?

**Comment by chrisda** [comment]
@ananimesh, I think your best chance for success is to open a support case.

**Comment by yogkumgit** [comment]
@ananimesh Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future

**Comment by victorguo** [comment]
@ananimesh I encountered the memory issue as well. Could you please let me know how you resolved the issue?

**Comment by tonipohl** [comment]
It seems this issue in EXO v2 is still existing. We are using EXO v2.0.6 and run still into the same memory issues, and there´s still no API existing... :(
Are there any news / real world experiences with the latest EXO V3 module?
https://learn.microsoft.com/en-us/powershell/exchange/whats-new-in-the-exo-module?source=recommendations&view=exchange-ps
Thx!

**Comment by chrisda** [comment]
Checking.

In the meantime, we do have a new article about using the v3 module and C# to connect to Exchange Online PowerShell:

https://learn.microsoft.com/powershell/exchange/connect-to-exo-powershell-c-sharp

I'm not sure if this helps.

**Comment by MiiChielHD** [comment]
We are also having the same issues with v3 module. I tried using a runspacepool instead of just a runspace in c#, but no improvement. The memory does not get released. This is really worrysome because we need to connect to the tenants constantly... Anyone found a solution yet?
