### ISSUE TITLE
What are the limitations when compare with Apply-PnPProvisioningTemplate command

### ISSUE THREAD

**Issue by ymihir** [MicrosoftDocs/office-docs-powershell#6925]
- [x] Question

`Get-SPOSiteScriptFromWeb` command will work as same as [Apply-PnPProvisioningTemplate](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/apply-pnpprovisioningtemplate?view=sharepoint-ps) command? Or any limitations are there with this command?

**Comment by get-itips** [comment]
How are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/questions [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ymihir Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
