### ISSUE TITLE
Applies To: and first paragraph contradiction

### ISSUE THREAD

**Issue by SuperTekBoy** [MicrosoftDocs/office-docs-powershell#6927]
The top of the article says "This cmdlet is available only in on-premises Exchange."

However, the applies to lists "Exchange Online"

It looks like this command might be available in Exchange Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a057e0e5-e897-e015-11ed-22cdbb6f7c43
* Version Independent ID: ee3ec571-bf8c-7623-92a8-538851427d54
* Content: [Import-RecipientDataProperty (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/import-recipientdataproperty?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Import-RecipientDataProperty.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Import-RecipientDataProperty.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SuperTekBoy, fixed.

Thanks for the feedback.

Closing
