### ISSUE TITLE
Incorrect info on documentation

### ISSUE THREAD

**Issue by jbros1** [MicrosoftDocs/office-docs-powershell#6929]
The arguments for the PrivacyMode parameter show as OptIn and OptOut on this page. However, the command requires they have a hyphen. So the arguments should be Opt-In and Opt-Out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523841fc-6df4-2d1a-ac10-4007855324d9
* Version Independent ID: 2dbcb7b6-bdb9-741e-e1f6-005b62b5907b
* Content: [Set-UserAnalyticsConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-useranalyticsconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UserAnalyticsConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-UserAnalyticsConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jbros1, it looks like the parameter description for PrivacyMode was corrected, but the example was not,. It is now.

Thanks for the feedback.

Closing

P.S. In the future, you too can make updates to topics without opening an Issue first. See >https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.
