### ISSUE TITLE
Note is not noticeable

### ISSUE THREAD

**Issue by cwidhelm** [MicrosoftDocs/office-docs-powershell#6930]
This should be in a note block.  I was trying to submit a pull request but the preview of the markdown was not working.

>[!Note]
>Note: After April 15, 2020, you can't use this cmdlet to manually move mailboxes within an Exchange Online organization. You can only use this cmdlet for migrating to and from Exchange Online.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ed5858-7a65-760f-95ef-4b6758b5f04e
* Version Independent ID: 9056b915-fe5d-d56b-ccdd-0d7c61f53293
* Content: [New-MoveRequest (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-moverequest?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-MoveRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MoveRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cwidhelm, Alerts don't work correctly in cmdlet reference topics. This is a known issue. For now, what I did is the best we can do.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @cwidhelm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
