### ISSUE TITLE
Information regarding Bookings incomplete

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/office-docs-powershell#6934]
First Booking is enabled by default (currently documentation disabled by default -> incorrect)
Second several new parameters are available but not yet documented.

PS C:\Users\trudolf> Get-OrganizationConfig | fl *bookings*
BookingsEnabled                             : True
BookingsEnabledLastUpdateTime               : 01.01.0001 00:00:00
BookingsPaymentsEnabled                     : False
BookingsSocialSharingRestricted             : False
BookingsAddressEntryRestricted              : False
BookingsAuthEnabled                         : False
BookingsCreationOfCustomQuestionsRestricted : False
BookingsExposureOfStaffDetailsRestricted    : False
BookingsNotesEntryRestricted                : False
BookingsPhoneNumberEntryRestricted          : False
BookingsMembershipApprovalRequired          : False

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23add0a6-bb9c-15d2-a6eb-351ae0564522
* Version Independent ID: 8056b3ee-4fab-3a5c-935b-a9d0e9ad82a4
* Content: [Set-OrganizationConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
This is being investigated in email.

**Comment by chrisda** [comment]
@trudolf-msft, any/all available Bookings parameters are now in the topic, most of the new ones without descriptions. Whether or not these parameters are meant to be available and are useful for anything is a different story.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this information. @trudolf-msft Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
