### ISSUE TITLE
Default domain .onmicrosoft.com is required 

### ISSUE THREAD

**Issue by AlexJPawlak** [MicrosoftDocs/office-docs-powershell#6935]
Hello! While your examples show clearly that "Connect-ExchangeOnline" is used with 'onmicrosoft.com' domain, can you stress or underline somehow that it is mandatory to use .onmicrosoft.com domain when accessing Exchange Online as application identity? 

Your "example" domains like contoso or others might drive people into thinking that any valid UPN would work in their example, like their main domain i.e. "mycompany.com". I have had that problem which ended up with Microsoft Support Call - only when trying to determine inner workings of Exchange Online we've figured out that the 'mycompany.onmicrosoft.com' should be used instead. Connecting to EXO worked fine, but there were cryptic permission issues when executing commands in App context

Thanks, hope this helps! 
Alex P

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@AlexJPawlak, sure. Do you have any suggestions about where it should go, and what exactly you want to say?

**Comment by AlexJPawlak** [comment]
I think a "Tip" baloon that you often use in docs would do. Right after examples showing "Certificate" and "CertificateThumbprint", a Tip saying

"When connecting to Exchange Online with Connect-ExchangeOnline module make sure you are using .onmicrosoft.com domain as Organization parameter value. Not doing so might introduce permission or access issues when accessing commands"

This tip, and also, I wish this was addressed by ExchangeOnlineManagement team so the problem never occurs in the first place :-) 

While we are at it, I think I'll try contributing myself - I'll be submitting a PR with this change, if, of course, you are OK with "material" statement portion of it - that indeed using .onmicrosoft.com is an advised way of connecting to Exchange Online

Thanks!

**Comment by AlexJPawlak** [comment]
@chrisda  uhm did I break docs pipeline with my pull request? I see quite a few errors there, hope it's OK - it's my first contribution to docs I hope I didn't mess it up!

**Comment by chrisda** [comment]
Nah, nothing like that. There's a repo-wide problem that has affected every pull request today (12/3); even very simple ones (and yours was pretty simple).

I've escalated, so I hope the problem gets fixed soon.

**Comment by chrisda** [comment]
Problem has been fixed. #6941 merged.

Thanks for the feedback.

Closing
