### ISSUE TITLE
Connect-ExchangeOnline Prefix Requirments

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#6940]
It looks like since ExchangeOnlineManagement 2.0.3 Microsoft have introduced a new check against prefix:
`if ($Prefix -notmatch '^[a-z0-9]+$') 
{
    throw "Use of any special characters in the Prefix string is not supported."
}`

That prevents from using underscores in prefix like ```o365_```:
![image](https://user-images.githubusercontent.com/5260172/101014918-a6c15300-3577-11eb-9554-b4eb46c4f094.png)

[Support page](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps) suggests a valid string cannot have spaces or EXO. No other requirements are mentioned there:
![image](https://user-images.githubusercontent.com/5260172/101015134-fa33a100-3577-11eb-8184-b23ec15f3070.png)

It is worth noting, that much shorter construct allows a use of any character except space:
`^\w+$`
![image](https://user-images.githubusercontent.com/5260172/101073387-6f22cd00-35b0-11eb-86ab-fa567e352b4b.png)

**Comment by chrisda** [comment]
It looks like this was addressed in #6943, so closing. Thanks for the feedback.

**Comment by YuriySamorodov** [comment]
Hi! This issue is quite different. I am wondering why this check has been implemented? Just wondering what might be wrong with underscores and hyphens in the Prefix. This is probably a question to Product Engineering Team...

**Comment by chrisda** [comment]
The topic has been updated to say "no funky characters". From a documentation perspective, that's all we can do. If you have questions about why the change was implemented or comments about the inefficiency of the RegEx that's used, I would suggest opening a support case.
