### ISSUE TITLE
Example 5 is incorrect

### ISSUE THREAD

**Issue by andypituch** [MicrosoftDocs/office-docs-powershell#6944]
Example 5 needs to use the identity of the migration endpoint and not the remote server name. I suppose if the identity and the remote server name are the same, it will work BUT if they aren't, it doesn't.

This: 
$MRSEndpoints = (Get-MigrationEndpoint).RemoteServer; Foreach ($MEP in $MRSEndpoints) {Test-MigrationServerAvailability -Endpoint $MEP}

Should be:
$MRSEndpoints = (Get-MigrationEndpoint).Identity; Foreach ($MEP in $MRSEndpoints) {Test-MigrationServerAvailability -Endpoint $MEP}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82b89b83-d3e2-876d-d3f5-0f902c891efa
* Version Independent ID: fecf67e7-3725-b7e0-db1d-b2d60d723403
* Content: [Test-MigrationServerAvailability (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/test-migrationserveravailability?view=exchange-ps#example-5)
* Content Source: [exchange/exchange-ps/exchange/Test-MigrationServerAvailability.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Test-MigrationServerAvailability.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@andypituch, I fixed it. In the future, you can too without opening an Issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
