### ISSUE TITLE
Descriptions

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6949]
-AllLocations
PARAMVALUE: SwitchParameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b582feac-4455-2457-8015-3a4259e05878
* Version Independent ID: 69c9947a-6e6a-d0b7-bad7-1c3bf48c5b25
* Content: [Get-SPOGeoStorageQuota (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spogeostoragequota?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoStorageQuota.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoStorageQuota.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks @hwkwicre
