### ISSUE TITLE
A couple questions

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#6953]
-CompatibilityLevel
The values for this parameter can be SharePoint Server. 
What does that mean?
Also:
For more information, see Resource Usage Limits on Sandboxed Solutions in SharePoint (https://msdn.microsoft.com/en-us/library/gg615462.aspx). 
The link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b6d2b1-788f-7139-c71b-b92d70d0cdbd
* Version Independent ID: 1b98f96f-942b-679d-b43f-1dc74da1e547
* Content: [New-SPOSite (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/new-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks @hwkwicre (The link is working at the time I tested)

**Comment by hwkwicre** [comment]
> Thanks @hwkwicre (The link is working at the time I tested)

I believe the reason it doesn't work is because when you click the link it includes ). after aspx

**Comment by get-itips** [comment]
> > Thanks @hwkwicre (The link is working at the time I tested)
> 
> I believe the reason it doesn't work is because when you click the link it includes ). after aspx

yep, on the published version only, i was testing thru gh. fixing. thanks
