### ISSUE TITLE
Command not working mentioned in the Page

### ISSUE THREAD

**Issue by mrpaddy35** [MicrosoftDocs/office-docs-powershell#6954]
Here is what output i am getting for the command specified,

PS C:\WINDOWS\system32> $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://smtp.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
New-PSSession : [smtp.office365.com] Connecting to remote server smtp.office365.com failed with the following error
message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:12
+ $Session = New-PSSession -ConfigurationName Microsoft.Exchange -Conne ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotin
   gTransportException
    + FullyQualifiedErrorId : AccessDenied,PSSessionOpenFailed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10052620-9909-c335-1913-fdf9db8ab16b
* Version Independent ID: e4be7843-4540-96fd-dcd8-09d6b91a4249
* Content: [Basic auth - Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/basic-auth-connect-to-exo-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mrpaddy35, most of the time, that error indicates an incorrect password. See the [troubleshooting](https://docs.microsoft.com/powershell/exchange/basic-auth-connect-to-exo-powershell#how-do-you-know-this-worked) section for more things to check.

Also, you'll want to get familiar with connecting to Exchange Online PowerShell using the [EXO V2 Module](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell). Basic authentication and therefore the connection method in the topic you referenced is going away in the [second half of 2021](https://developer.microsoft.com/office/blogs/deferred-end-of-support-date-for-basic-authentication-in-exchange-online/).

**Comment by chrisda** [comment]
@mrpaddy35 it's more simple than that: your _ConnectionUril_ value is wrong. It should be <https://outlook.office365.com/powershell-liveid/>, not <https://smtp.office365.com/powershell-liveid/> as shown in the error.

**Comment by mrpaddy35** [comment]
oh thanks alot, we can close this now
