### ISSUE TITLE
Example 4 is incorrect

### ISSUE THREAD

**Issue by harp365** [MicrosoftDocs/office-docs-powershell#6955]
example 4 should be:

Get-PnPList | Where-Object {$_.RootFolder.ServerRelativeUrl -like "*/lists/*"}

It was missing the leading wildcard *

Thanks

Henry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f48dcd7-1a3c-e8f1-309e-8f65b0ac0450
* Version Independent ID: baf42f0a-9e63-ec81-fefb-b1c8dde5672e
* Content: [Get-PnPList (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnplist?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPList.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by harp365** [comment]
Not sure why but the example correction does not show until I go to edit my post, so just for clarity it should be:

Get-PnPList | Where-Object {$_.RootFolder.ServerRelativeUrl -like "*/lists/*"}

**Comment by harp365** [comment]
In fact it keeps stripping wildcards out but there should be one at the beginning and end of the string after the like operator.

**Comment by get-itips** [comment]
Hello @harp365  How are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/SharePoint/PnP-PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @harp365 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
