### ISSUE TITLE
-OverwriteOdb parameter doesn't work

### ISSUE THREAD

**Issue by frankchen76** [MicrosoftDocs/office-docs-powershell#6961]
When my custom was trying this cmdlet with -OverwriteOdb, they error message to say this parameter isn't available. when I run get-help Start-SPOUserAndContentMove, I don't see -OverwriteOdb parameter list there. 

PS C:\WINDOWS\system32> get-help Start-SPOUserAndContentMove

NAME
    Start-SPOUserAndContentMove
    
SYNTAX
    Start-SPOUserAndContentMove [-UserPrincipalName] <string> [-DestinationDataLocation] <string> [[-PreferredMoveBeginDate] <datetime>] 
    [[-PreferredMoveEndDate] <datetime>] [[-Notify] <string>] [[-Reserved] <string>] [[-ValidationOnly]]  [<CommonParameters>]
    

ALIASES
    None
    

REMARKS
    None

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 371753bb-ec03-9607-8c2c-624e6087fb31
* Version Independent ID: b0a631e9-6afa-228d-1c4a-1912ee180604
* Content: [Start-SPOUserAndContentMove (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/start-spouserandcontentmove?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Start-SPOUserAndContentMove.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Start-SPOUserAndContentMove.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @frankchen76 Frank, how are you?
I tested using the latest module version (16.0.20616) and the parameter is not there, will remove from the article.
Thank you
