### ISSUE TITLE
MicrosoftTeams Powershell Library - applicationaccesspolicy cmdlets do not exist

### ISSUE THREAD

**Issue by lindseylanier** [MicrosoftDocs/office-docs-powershell#6962]
Need to allow applications to access online meetings on behalf of a user. Attempting to follow the guidance as per this doc - https://docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy, however am unable to locate the necessary commands in any of the PS library versions for MicrosoftTeams (as a global administrator).

New-CsApplicationAccessPolicy 
Grant-CsApplicationAccessPolicy

Was redirected to raise an issue here by Frank Peng (https://github.com/microsoftgraph/microsoft-graph-docs/issues/10911)

![image](https://user-images.githubusercontent.com/8949639/101634830-3a22da00-39f7-11eb-8f43-60706c2ab9f6.png)

**Comment by lindseylanier** [comment]
Any updates on this?

**Comment by get-itips** [comment]
Hello @lindseylanier 

How are you? Hope you are doing great.
Those cmdlets belong to the Skype for Business Online Connector, now part of the Microsoft Teams module, you have to load it as explained here https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install#install-the-skype-for-business-online-connector

Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @lindseylanier Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
