### ISSUE TITLE
Wrong command in examples for Get-PnPMicrosoft365Group

### ISSUE THREAD

**Issue by joelfmrodrigues** [MicrosoftDocs/office-docs-powershell#6963]
Command in examples is missing the "PnP" prefix
Get-Microsoft365Group should be Get-PnPMicrosoft365Group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af3e6955-1125-e2cb-8655-6e09a8daa277
* Version Independent ID: 708b2e85-d65d-58f2-4c33-d168c45035cb
* Content: [Get-PnPMicrosoft365Group (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpmicrosoft365group?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPMicrosoft365Group.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPMicrosoft365Group.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
How are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/pnp/powershell), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @joelfmrodrigues Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
