### ISSUE TITLE
Connect-SPOService: Could not load type 'System.Security.Cryptography.SHA256Cng' 

### ISSUE THREAD

**Issue by BerndKroon** [MicrosoftDocs/office-docs-powershell#6975]
There has been another post on this issue in the period jan-march 2020. The issue was not resolved. I ran into this error when  tried to follow textbooks to learn PowerShell and/or when I followed instruction how to upload a new theme design to a sharepoint site.

When I use this command on Windows PowerShell (from Windows 10), all works well. When I use it on Powershell 7 (from Windows 10), you get the error.

Now, what really disappoints me is that, while I only see advice to use PWS7 (core) and to stop using Windows Powershell, it is obvious that PWS7 is far from being error free. PWS7 (core) should not be promoted at the way to go as long as existing cmdlets do not work.

**Comment by tseward** [comment]
The production SPO cmdlets are not compatible with PowerShell Core as they use the .NET Framework. While there is not yet a replacement for the SPO cmdlets, depending on what your goal is, there are the pre-release PnP cmdlets that allow you manage SPO but targeting the site level:

https://www.powershellgallery.com/packages/PnP.PowerShell/

For a more analgous equivilent to SPO cmdlets, you can use the `m365` CLI.

https://pnp.github.io/cli-microsoft365/

Both the PnP.PowerShell and m365 CLI run on PowerShell Core (m365 runs on any popular shell, such as `zsh`, `bash`, and so on). Both of these are available for Linux and macOS, as well.

**Comment by yogkumgit** [comment]
@tseward Thank you very much for the contribution and sharing this explanation. @BerndKroon Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
