### ISSUE TITLE
Get-EXOMailboxPermission - Error when piping all mailboxes from Get-EXOMailbox

### ISSUE THREAD

**Issue by VShrubowich** [MicrosoftDocs/office-docs-powershell#6980]
When I first read about the new Get-EXO* cmdlets being optimized for bulk data retrieval scenarios, one of the first things I thought of is being able to see which mailboxes a user has access to.  However, when I try the following using version 2.0.3 of EXO V2, I get error after error:

```
PS> Get-EXOMailbox -ResultSize Unlimited | Get-EXOMailboxPermission -User User1@contoso.com

Get-EXOMailboxPermission : An error occurred while processing this request..
At line:1 char:40
+ ... sultSize Unlimited | Get-EXOMailboxPermission -User User1@contoso.com                                             
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ProtocolError: (:) [Get-EXOMailboxPermission], Exception
    + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.Exchange.Management.RestApiClient.GetExoMailboxPermission

Get-EXOMailboxPermission : An error occurred while processing this request..
At line:1 char:40
+ ... sultSize Unlimited | Get-EXOMailboxPermission -User User1@contoso.com
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ProtocolError: (:) [Get-EXOMailboxPermission], Exception
    + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.Exchange.Management.RestApiClient.GetExoMailboxPermission 
```

However, when using the following:
`Get-EXOMailbox -ResultSize Unlimited | Get-MailboxPermission -User User1@contoso.com`
I get all of the mailboxes that User1@contoso.com has access to.

When I try specific mailboxes instead of `-ResultSize Unlimited`, I find that the error occurs on the mailboxes that  User1@contoso.com doesn't have access to.  Is this the way Get-EXOMailboxPermission is supposed to work or will it eventually work the way Get-MailboxPermission does and not generate an error if the user does not have any permissions set on the target mailbox?  If the former, can the documentation page for Get-EXOMailboxPermission be updated to reflect that?

Thank you.

**Comment by tmalo627** [comment]
I'm experiencing same issue.

**Comment by dariomws** [comment]
Hi @VShrubowich and @tmalo627, thank you for your feedback and help us to improve docs.microsoft.com.

The best places to provide feedback about the EXO PS V2 are:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623
https://office365.uservoice.com/forums/273493-office-365-admin?category_id=96338
https://docs.microsoft.com/office365/admin/contact-support-for-business-products

It was working before:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4333
I think it should be reviewed before we update the article.

Please keep us posted here on the reply to feed whatever information you discover into the content.

Thank you again!

**Comment by yogkumgit** [comment]
@VShrubowich Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
