### ISSUE TITLE
This functionality seems Broken.

### ISSUE THREAD

**Issue by AnkitSDesai** [MicrosoftDocs/office-docs-powershell#6981]
I have followed this step and sounds like its not functioning.
It gives 401- Unauthorized even after successfully login using connect-pnp Online.
I have opened similar issue for PNP community as well.
https://github.com/pnp/PnP-PowerShell/issues/3028

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34a78fe1-1c93-1014-d773-29085ec97b9e
* Version Independent ID: c1f7a5e1-ab36-29ad-aa29-dbe72efa6b16
* Content: [Get-PnPContext (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpcontext?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPContext.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPContext.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
How are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues [here](https://github.com/pnp/powershell), in that repository, where a member of the PnP community will be able to correct the article with your feedback.
The documentation for PnP cmdlets is then sync from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @AnkitSDesai Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
