### ISSUE TITLE
Different number of messages in Quarantine from powershell(Get-QuarantineMessage) and Protection portal

### ISSUE THREAD

**Issue by N4v41** [MicrosoftDocs/office-docs-powershell#6982]
Hi, I've noted that the amount of messages that i get from the quarantine from powershell and the web interface are very different.
running this simple script below in powershell i get about 4489 messages in quarantine:
```
$pagen = 0
$QuarantineMessages = Get-QuarantineMessage -PageSize 1000 -Page $pagen
Write-Output $QuarantineMessages.count
Do{
$pagen++
$QuarantineMessages += Get-QuarantineMessage -PageSize 1000 -Page $pagen
Write-Output $QuarantineMessages.count
}while( $QuarantineMessages.Count -eq ($pagen * 1000))
Write-Output $QuarantineMessages.count
```
when i go to the web interface and roll i get the final count of 5576 messages
![image](https://user-images.githubusercontent.com/45365461/102286657-84381e00-3f17-11eb-9c60-31d387c26228.png)

is there any solution to get all messages in powershell ?

using Powershell core and default powershell i get the same result:
![image](https://user-images.githubusercontent.com/45365461/102286887-f90b5800-3f17-11eb-87d5-8f33ed4ea6be.png)
![image](https://user-images.githubusercontent.com/45365461/102286925-0de7eb80-3f18-11eb-9248-9661b53cbaf8.png)

**Comment by chrisda** [comment]
@N4v41, at this point, your best bet is to open a support case so the issue gets in front of engineers in the product team.  Sorry it took so long to respond.

Report any of your findings back here if there's anything we need to update in the documentation.

Thanks for the feedback.

Closing
