### ISSUE TITLE
 -Confirm:$false parameter is not working.

### ISSUE THREAD

**Issue by mhunecke** [MicrosoftDocs/office-docs-powershell#6983]
The -Confirm:$false is not working for the cmdlet New-InformationBarrierPolicy.
It still asking for confirmation. Please fix it.
Thanks.

![image](https://user-images.githubusercontent.com/33945695/102384710-c9a62b00-3fab-11eb-9d7e-005fed89d87e.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edf1d4f8-ff67-b39d-e710-f79b515d24f0
* Version Independent ID: 9307e1e5-9330-8674-3e8b-b95ec5b5b146
* Content: [New-InformationBarrierPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-informationbarrierpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-InformationBarrierPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-InformationBarrierPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mhunecke, I would recommend opening a support case about this.

**Comment by mhunecke** [comment]
Chris,

I'm Microsoft FTE.
I do not have a "Premier contract" to open a ticket.

Thanks.

**Comment by chrisda** [comment]
@mhunecke, from a documentation perspective, the best I can do is change the description of the Confirm parameter to say that it doesn't work on this cmdlet. Which I did.

**Comment by mhunecke** [comment]
Thank you !!!

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for updating the documentation with PR. @mhunecke Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
