### ISSUE TITLE
Get-DlpComplianceRule Common Parameter Support?

### ISSUE THREAD

**Issue by hbwheat** [MicrosoftDocs/office-docs-powershell#6986]
Hello, 
I'm having issues with with the Get-DlpComplianceRule common parameter "-PipelineVariable" being null on the other side of the pipe. I'm curious as to any other troubleshooting or that I can perform to determine if it's an issues or my specific instance for some reason.

**Comment by hbwheat** [comment]
The following command below returns nothing as unexpected while using the PipelineVariable common parameter. 

```
# returns null
Get-DLPComplianceRule "some rule" -PipelineVariable rule | %{$rule}
```

 I've been doing a workaround with using a foreach and variable assignment but it's not an ideal flow for powershell.

**Comment by hbwheat** [comment]
After more testing, I can achieve the similar result by piping to Select-Object and using the -pv parameter there.

**Comment by dariomws** [comment]
@hbwheat - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.
