### ISSUE TITLE
{{ Fill IncludeExecutionRuleGuids Description }}

### ISSUE THREAD

**Issue by hbwheat** [MicrosoftDocs/office-docs-powershell#6987]
Hey, 
Just curious if there is the non-templated block available for this section description of parameter: "-IncludeExecutionRuleGuids"

> {{ Fill IncludeExecutionRuleGuids Description }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d675f875-88fa-470c-ac3c-65ef056ab747
* Version Independent ID: 57cfdddf-6fd7-07c6-144d-5bafa9690bd5
* Content: [Get-DlpComplianceRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-dlpcompliancerule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-DlpComplianceRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-DlpComplianceRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hbwheat, that {{ Fill \<parameter\> Description }} indicates the parameter is available, the syntax/operation is not easily discoverable, and my requests for help/further information have fallen on deaf ears.

If you're interested in getting an actual description, I would suggest opening a support ticket.

**Comment by hbwheat** [comment]
@chrisda , thank you for the info! Sounds good, it is not crucial, but I might do that just to learn more. 

Attempting to flesh out the tooling is harder without knowing what some params are capable of /do.
