### ISSUE TITLE
-ContentContainsSensitiveInformation Param "Advanced" Syntax

### ISSUE THREAD

**Issue by hbwheat** [MicrosoftDocs/office-docs-powershell#6990]
Hello, 

I wanted post with an issue this time that might be a contribution... 

The -ContentContainsSensitiveInformation param current description is as follows: 

> This parameter uses the basic syntax @(@{Name="SensitiveInformationType1";[minCount="Value"],@{Name="SensitiveInformationType2";[minCount="Value"],...). For example, @(@{Name="U.S. Social Security Number (SSN)"; minCount="2"},@{Name="Credit Card Number"}).

The "basic" syntax is helpful for assigned a sensitive type to the rule for content contains. The "advanced" syntax is also possible with "and" and "or" for sub groups of sensitive types.

Formatting needs to be a hashtable but more complex types can be created from the cmdlt param too. :-) 

```
$contains_complex_types = @{
    operator = "And"
    groups = @(
        @{
            operator = "Or"
            name =  "PII Identifiers"
            sensitivetypes = @(
                @{
                    name = "Drug Enforcement Agency (DEA) Number"
                    maxconfidence = 100
                    minconfidence = 75
                    mincount = 1
                    maxcount = -1
                }
            )
        }
        @{
            operator = "Or"
            name =  "Medical Terms"
            sensitivetypes = @(
                @{
                    name = "International Classification of Diseases (ICD-9-CM)"
                    maxconfidence = 100
                    minconfidence = 75
                    mincount = 1
                    maxcount = -1
                }
                @{
                    name = "International Classification of Diseases (ICD-10-CM)"
                    maxconfidence = 100
                    minconfidence = 75
                    mincount = 1
                    maxcount = -1
                }
                )
        }  

    )
}

New-DLPComplianceRule -Name "Some Rule" -ContentContainsSensitiveInformation $contains_complex_types

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98894097-1935-bd41-7857-5309d31817ee
* Version Independent ID: c8e1fd27-2bd4-ea13-5493-cf39450b715e
* Content: [New-DlpComplianceRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-dlpcompliancerule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-DlpComplianceRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-DlpComplianceRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @hbwheat, thank you for your feedback and help us to improve docs.microsoft.com.

I am not convinced to add this information to the article, as I think we can achieve the same result using basic syntax. I'm not convinced that adding this information to the parameter description or as an example can add value to the article.

**Comment by GregoryWBryant** [comment]
After spending an hour Google searching I decided to view all comments on this page. I completely agree that this is helpful information. Much thanks to @hbwheat

**Comment by chrisda** [comment]
Dario is correct in that adding this information to the parameter description isn't a good idea (too long/complex for a parameter description). However, I added the information as a second example so the information/capability is at least captured.

Be advised that the ContentContainsSensitiveInformation parameter is available in the following cmdlets:

- New/Set-AppRetentionComplianceRule
- New/Set-AutoSensitivityLableRule<sup>\*</sup>
- New/Set-DlpComplianceRule<sup>\*</sup>
- New/Set-RetentionComplianceRule
- New/Set-SupervisoryReviewRule

<sup>\*</sup>Also contains a ExceptIfContentContainsSensitiveInformation parameter

This same issue is likely to affect those other cmdlets as well.
