### ISSUE TITLE
How do AAD Roles map to Exchange Online Roles?

### ISSUE THREAD

**Issue by tsp4axl** [MicrosoftDocs/office-docs-powershell#6992]
I am trying to write a function app to apply permissions to a Shared Mailbox. I can connect to exchange online using an Managed Identity just fine after giving it Exchange.ManageAsApp and Global Reader, but I do not have the Add-RecipientPermission and Add-MailboxPermission commands available to me. I believe its because I only have Global Reader role assigned, which is not the equivalent of a Recipient Manager in Exchange Online. Trying to avoid using the Exchange Administrator role. Any idea how I can grant my managed identity the necessary roles/permissions/access to manage the permissions on these shared mailboxes?
Thanks,
Anthony

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@tsp4axl, before I start, realize that conceptually, Azure AD role is equivalent to a role group in Exchange Online; Azure AD permission is equivalent to a role in Exchange Online (confusing, I know).

Using the information in [this topic](https://docs.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions). the following role and role groups in Exchange Online give access to the **AddRecipientPermission** and **Add-MailboxPermission** cmdlets:

```powershell
PS C:\Users\chrisda> $Perms = Get-ManagementRole -Cmdlet Add-RecipientPermission
PS C:\Users\chrisda> $Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}

Role            RoleAssigneeType RoleAssigneeName
----            ---------------- ----------------
Mail Recipients RoleGroup        Recipient Management
Mail Recipients RoleGroup        Organization Management

PS C:\Users\chrisda> $Perms = Get-ManagementRole -Cmdlet Add-MailboxPermission
PS C:\Users\chrisda> $Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}

Role            RoleAssigneeType RoleAssigneeName
----            ---------------- ----------------
Mail Recipients RoleGroup        Recipient Management
Mail Recipients RoleGroup        Organization Management
```

In terms of Azure AD permissions, other than Global Administrator, Global Reader, and Exchange Administrator, the only Azure AD roles that appear to flow through into Exchange Online are **Security Administrator** and **Security Reader**, and neither of those have the Mail Recipients role in Exchange Online assigned.

I suppose you could add the Mail Recipients role to the Security Administrator role group in Exchange Online.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @tsp4axl Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
