### ISSUE TITLE
New-CsVoiceNormalizationRule cannot be used directly to assign Normalization Rules to  DialPlans 

### ISSUE THREAD

**Issue by sheidl** [MicrosoftDocs/office-docs-powershell#6995]
Although this list and these rules can be created directly by using this cmdlet, we recommend that you create the normalization rules by the New-CsVoiceNormalizationRule (https://technet.microsoft.com/en-us/library/gg398240.aspx) cmdlet, which creates the rule and **assigns it to the specified tenant dial plan.**

New-CsVoiceNormalizationRule cannot be used directly to assign Normalization Rules to  DialPlans in SfbO and Teams, only in Sfb OnPrem.
As the article in question is about SfbO and Teams the wording here should be changed.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03d4b7d0-20e1-6538-093a-d7980ce8670a
* Version Independent ID: b2b7f60a-4cab-e495-5360-f02018ab8316
* Content: [New-CsTenantDialPlan (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cstenantdialplan?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTenantDialPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTenantDialPlan.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @sheidl 
Just to clarify, do you refer to the fact that after issuing a `New-CsVoiceNormalizationRule` you have to run `Set-CsTenantDialPlan -NormalizationRules` to actually associate a rule to a dial plan ?
Thanks

**Comment by yogkumgit** [comment]
@sheidl

**Comment by sheidl** [comment]
@get-itips: Yes, exactly what I meant. Not a big issue but some feedback from one of my picky customers which I promised to try to get improved,

@yogkumgit
