### ISSUE TITLE
New-MoveRequest note may be inaccurate

### ISSUE THREAD

**Issue by majorwitteman** [MicrosoftDocs/office-docs-powershell#6996]
The note below for the New-MoveRequest may not be accurate. My team is currently working on a troubleshooting case with an Office 365 Ambassador support representative who instructed us to run this command for our client and found that it does indeed work to initiate a move request within Exchange Online.

The command `New-MoveRequest useremail@domain.com` worked to initiate the move. It would seem either the specified date is incorrect, or this functionality is set to remain available.

> Note: After April 15, 2020, you can't use this cmdlet to manually move mailboxes within an Exchange Online organization. You can only use this cmdlet for migrating to and from Exchange Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ed5858-7a65-760f-95ef-4b6758b5f04e
* Version Independent ID: 9056b915-fe5d-d56b-ccdd-0d7c61f53293
* Content: [New-MoveRequest (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-moverequest?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/New-MoveRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MoveRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @majorwitteman, thank you for your feedback.

This operation is not supported but may work. It's there to let the reader know that they cannot use the cmdlet to perform a move within Exchange Online. If you have problems with a mailbox right now, you have to call support.

**Comment by dariomws** [comment]
More information here: https://techcommunity.microsoft.com/t5/exchange-team-blog/disabling-new-moverequest-for-local-mailbox-moves/ba-p/1214776

And there is an important wording in the sentence: "After April 15, 2020". So you can expect that the cmdlet works for internal moves now, but it can stop working anytime.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @majorwitteman Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Rickage90** [comment]
disappointed that this was removed it was very handy having the ability to fix issues with mailboxes without the need to rely on support :(
