### ISSUE TITLE
Passing Username to New-CsOnlineSession when authenticating with MFA?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#6997]
Hello,
with the Command `New-CsOnlineSession` now moving into MicrosoftTeams, the Username Parameter was removed.
In order to establish a Connection with MFA, I must not use the Credential parameter.

Calling New-CsOnlineSession without parameters provides a path to do that, though I cannot "pre-fill" the Username anymore.

Is there any way to pass a Username to the command (like `Connect-MicrosoftTeams -AccountId` does?)
I am trying to reduce the number of Authentication windows to 1 when connecting to multiple services?

I have raised an issue on the Docs that outline multiple connections to 365 services, but these do not cater for MFA.
https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3759

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2abd383-7815-9404-41ba-72bbedb5208a
* Version Independent ID: 88342584-33e2-47c6-baf1-81644d5cc7a5
* Content: [New-CsOnlineSession (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinesession?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineSession.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DEberhardt David, how are you?

I tested this on my lab, enabled MFA, connected to teams using `Connect-MicrosoftTeams -AccountId teamsadmin@tenant.com`, approved on the authenticator app and then issued `$sfbSession = New-CsOnlineSession` and `Import-PSSession $sfbSession`

I didn't need to specify an Account for New-CsOnlineSession, it took the already validated token of the Connect-MicrosoftTeams.

Hope this information helps you,

Andrés

**Comment by DEberhardt** [comment]
Ah! - This is interesting. I have found out that creating a session with New-CsOnlineSession from the MicrosoftTeams module will create a connection to Teams as well as for SkypeOnline...
Never tried it the other way round!
I shall go back to my Code and re-order its execution then.
Can probably confirm within the next two days as I have some time to tinker 👍 
Cheers!

**Comment by DEberhardt** [comment]
Follow-up question. OverrideAdmin domain is then also not needed anymore, I wager?
I mean, I could read it once connected to AzureAd anyways 😄

**Comment by DEberhardt** [comment]
Ok. More testing has commenced. OverrideAdminDomain is able to be read after AzureAdConnection, not a problem.
The Single Sign On however only works if there is only one sign-in available. 
I get a popup where I have to select the right account. No Authentication required (already signed-in) though in my request this list is already 10 Tenants long (and growing).

To really ensure connecting to the same service as the AzureAd and MicrosoftTeams connections, I would need to pass the Username to the command.

**Comment by DEberhardt** [comment]
Hello again,
I see a few PRs have been introduced already, thank you! 👍 

Recently I found a Sku I could not remove with my script as it was spelled slightly differently than advertised (Domestic Calling Plan 120 Minutes). I think there are two products out there: MCOPSTN5 and MCOPSTN_5 - This might not be intentional...

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
> Ok. More testing has commenced. OverrideAdminDomain is able to be read after AzureAdConnection, not a problem.
> The Single Sign On however only works if there is only one sign-in available.
> I get a popup where I have to select the right account. No Authentication required (already signed-in) though in my account list is already 10 Tenants long (and growing).
> 
> To really ensure connecting to the same service as the AzureAd and MicrosoftTeams connections, I would need to pass the Username to the command.

Thanks for the feedback @DEberhardt David.

**Comment by get-itips** [comment]
@yogkumgit This issue can be closed now. Thanks
