### ISSUE TITLE
Page and entry for New-CsOnlineSession missing

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#6998]
Hello,

wanted to raise an issue/question for `New-CsOnlineSession` as it was now added to MicrosoftTeams.
It is not linked in this page, nor is available as a separate page:
https://docs.microsoft.com/en-us/powershell/module/teams/new-csonlinesession?view=teams-ps

My question has been added to the Skype variant, which may not be the best thing, my apologies:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/6997

Can this be rectified please?

Cheers,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6804423b-8e08-5916-9355-6bebe8bb08b0
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [MicrosoftTeamsPowerShell Module](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @DEberhardt David,
How are you?
I will propose adding the cmdlet to this index article, and if it gets approval, it will be reflected on the published version of the article.

Thanks for your feedback.

**Comment by DEberhardt** [comment]
Thank you :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DEberhardt** [comment]
No, bit, this can stay closed^^
