### ISSUE TITLE
Import-Module MicrosoftTeams - No error received, yet no Module imported

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#6999]
Hello,

running `Import-Module MicrosoftTeams` sometimes results in the command completing without error, yet the Module is not imported at all.

Previously I could help myself with the `-Force` switch, though throughout testing today, this was not successful either!

My current workaround is as follows:
`Import-Module MicrosoftTeams -Force -Global`

Why is that?

PowerShell v7.2.0-preview.2 does not seem to be affected.
PowerShell v5.1 however is:
```
$PSVersionTable

Name                           Value                                                  
----                           -----                                                  
PSVersion                      5.1.19041.610                                          
PSEdition                      Desktop                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                
BuildVersion                   10.0.19041.610                                         
CLRVersion                     4.0.30319.42000                                        
WSManStackVersion              3.0                                                    
PSRemotingProtocolVersion      2.3                                                    
SerializationVersion           1.1.0.1                                                
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6804423b-8e08-5916-9355-6bebe8bb08b0
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [MicrosoftTeamsPowerShell Module](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @DEberhardt David, how are you?
Tested to see if we needed to maybe correct any article..
I also have 5.1.19041.610 PSVersion, I tested and could successfully import the module every time.
Hope this information helps you,
Thanks!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DEberhardt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
