### ISSUE TITLE
Unexpected Session timeouts occur with New-CsOnlineSession - SessionOptions/IdleTimeout not adhereed to 

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7000]
Hello,

I just remembered that it irked me in the Skype variant, though since that one is deprecated, I thought I raise it here:

I create a $SessionOption with the following command:
```
    $IdleTimeoutInMS = $IdleTimeout * 3600000
    if ($PSBoundParameters.ContainsKey('IdleTimeout')) {
      $SessionOption = New-PSSessionOption -IdleTimeout $IdleTimeoutInMS
    }
    else {
      $SessionOption = New-PSSessionOption -IdleTimeout 14400000
    }
```
$IdleTimeout is provided with the Command (value between 1 and 8 - representing the number of hours)

When calling `New-CsOnlineSession -SessionOption $SessionOption` the timeout is applied, however the Session times out regardless after an hour.

I have a feeling that this may not even be an issue with the command as the session, even if created a few minutes ago, sometimes times out unexpectedly (though I still have to test this fully against connection with MicrosoftTeams...)

Thanks,
David
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6804423b-8e08-5916-9355-6bebe8bb08b0
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [MicrosoftTeamsPowerShell Module](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @DEberhardt David, how are you?
We are limited here to documentation issues, for your inquiry to reach the team, I need to suggest https://microsoftteams.uservoice.com/ 
Thanks!

**Comment by DEberhardt** [comment]
Done: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/42287602-new-csonlinesession-does-not-adhere-to-sessionopti

**Comment by get-itips** [comment]
Great @DEberhardt David.
