### ISSUE TITLE
Descriptions

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#7004]
-EncryptionParameters
PARAMVALUE: EncryptionParameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28384eb-d10f-0aa4-6b31-e78827299301
* Version Independent ID: 03b99b02-a572-49c8-49e9-d6a2bc168483
* Content: [Get-SPOMigrationJobProgress (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spomigrationjobprogress?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMigrationJobProgress.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMigrationJobProgress.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for your feedback @hwkwicre
