### ISSUE TITLE
Set-CsTenantDialPlan description

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#7007]
Some issues with the article for this cmdlet:

- Example 2 does not make much sense with tenant dial plans due to Get-CsVoiceNormalizationRule reads non-tenant rules thus such identity could not exist
- Parameter "-Description". Explanation says `Maximum characters is 512`, but it should be `Description must have a length of at most 1040`
- Parameter "-ExternalAccessPrefix". Explanation says `The value of this parameter must match the regular expression [0-9]{1,4}. This means it must be a value one to four digits in length, with each digit being a number 0 through 9.`, but it should be `External access prefix must be no longer than 4 characters long and can contain only digits, "#" or a "*".`
- Parameter '-Identity'. Explanation refers to "sites" and "registrars", which are not relevant to the cloud.
- Parameter '-NormalizationRules'. Explanation says `The number of normalization rules cannot exceed 50 per TenantDialPlan`, but in fact my tenant dial plans have hundreds of rules each
- Parameter '-SimpleName'. Explanation refers to "Skype for Business Server", which is not relevant to tenant dial plans. Explanation says `This string can be up to 256 characters long`, but it should be `Maximum SimpleName length cannot exceed 49.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f9dccd1-bc3b-6c14-eb66-2a566a71d94f
* Version Independent ID: 545fa8ce-0abe-4921-04ef-3cd1bf496f24
* Content: [Set-CsTenantDialPlan (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cstenantdialplan?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTenantDialPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTenantDialPlan.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by shivtorov** [comment]
The same updates needed in article for New-CsTenantDialPlan cmdlet.

sample code to verify limits for the parameters:
```PowerShell
Set-CsTenantDialPlan Global -Description ("a"*2000)
Set-CsTenantDialPlan Global -ExternalAccessPrefix '12345'

New-CsTenantDialPlan -Identity test
Set-CsTenantDialPlan -Identity test -SimpleName ("t"*50)

# takes forever, but successfully configures the dial plan with 1000 rules
$rules = 1..1000 | foreach { New-CsVoiceNormalizationRule -Name "rule$_" -Pattern '^(1\d\d)$' -Translation '555$1' -Parent Global -InMemory }
Set-CsTenantDialPlan Global -NormalizationRules $rules
```

**Comment by DEberhardt** [comment]
Also have observed the "limit of 50" which looked to be quite arbitrary to me.
Following to see the conclusion on this as we have a requirement for more than 50 rules ourselves.

Use-case:
Non-consecutive or severely fragmented number of Extensions/Number ranges. (Sometimes even 1:1 assignments).

**Comment by get-itips** [comment]
Thanks for your feedback @shivtorov
