### ISSUE TITLE
Get-SPOTheme

### ISSUE THREAD

**Issue by CarlWilliams254** [MicrosoftDocs/office-docs-powershell#7011]
Get-SPOTheme doesn't do anything, just returns to prompt. It doesn't list anything as the document indicates
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ce4c41c-bd93-2314-b58d-195208a91f7b
* Version Independent ID: 1cb8f93c-284b-eb89-69b9-cfd0cdae82a8
* Content: [Get-SPOTheme (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotheme?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTheme.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTheme.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by tseward** [comment]
Until you add a custom theme, there will be no output.

Try adding the example as shown in [Add-SPOTheme](https://docs.microsoft.com/powershell/module/sharepoint-online/add-spotheme?view=sharepoint-ps), then run `Get-SPOTheme` again.

**Comment by CarlWilliams254** [comment]
Thanks for following up Trevor.

I found the issue. It’s because I didn’t start Shell as Admin. Why? Because it doesn’t work. I can start it as a regular user but when I right-click the icon and choose “run as administrator”, just a black, empty command screen opens. No prompt, no interactivity.

I can’t even uninstall it and readd it. It just hangs.

Isn’t that the most excellent thing ever? I’m so satisfied about attempting to try out cmdlets. Worked out great. ☹

I don’t suppose you know anyone well-versed with this type of issue? I suspect it’s a Win !0 thing (surprise) but have no idea what that entails.

CW

**Comment by tseward** [comment]
You don't need to (and shouldn't, unless you have a purpose to do so) launch as admin. The SPO cmdlets do not require local administrator rights.

But this is likely unrelated to the cmdlets themselves and more related to MSI installer issues.

**Comment by CarlWilliams254** [comment]
Thanks Trevor. But don’t you need to run as admin to perform theme changes etc.? However, I am the admin on my own machine so never really got why I need to run anything as admin.

This all being the case, do you know who can assist with this misbehaving app?

Tx

CW

**Comment by tseward** [comment]
No *-SPO* cmdlet requires local admin on the machine it is being run on. It requires the user connecting via `Connect-SPOService` to have the SharePoint Admin or Global Admin role, but again you don't need local admin on the machine.

You do need local admin if you're going to install it via the MSI (again, I don't recommend using it) or if you don't pass `-Scope CurrentUser` to `Install-Module`.

As for t-shooting general issues, I'd either post over at answers.microsoft.com or if you have a support contract with Microsoft, go that route instead.

**Comment by CarlWilliams254** [comment]
Thanks for the tip!!!!!! All these years I thought one always had to “Run as administrator”.

I just started it up, ran the connect then  Get-SPOHubSite and it actually returned a list of my hubs.

Merry Christmas to me. 😊

Cheers

Stay safe.

CW

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @CarlWilliams254 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it.
