### ISSUE TITLE
Get-ManagementRoleAssignment limit

### ISSUE THREAD

**Issue by SebastienGu** [MicrosoftDocs/office-docs-powershell#7013]
Our O365 Exchange setup has 46 Management Scopes for local branches with a few roles assigned to each.
My issue is when I run:
`Get-ManagementRoleAssignment -GetEffectiveUsers | select identity,user | Out-GridView`
It returns 1522 lines but some entries are missing, with some users showing only some scopes or not all roles.

To confirm, I did:
`Get-ManagementRoleAssignment -GetEffectiveUsers -RoleAssignee [User UPN] | select identity,user | Out-GridView`
This returns all entries for that user, with all scopes included.

I suspect a timeout because after I run the first command, if I run another one, PowerShell reconnects to the Exchange Module.
```
Get-ManagementRoleAssignment -GetEffectiveUsers | select identity,user | Out-GridView
Creating a new Remote PowerShell session using Modern Authentication for implicit remoting of "Get-ManagementRoleAssignment" command ...
```

I tried the -Verbose switch and to export to various formats, including CSV but it made no difference and I didn't get any extra information.
Checking the Event Viewer/Application and Services/Microsoft/Windows/Powershell/Operational, I saw this error message:

> Closing the remote server shell instance failed with the following error message  : The request for the Windows Remote Shell with ShellId  D5F4111E-B61C-47E3-A669-XXXXXXXX failed because the shell was not found on  the server. Possible causes are: the specified ShellId is incorrect or the shell  no longer exists on the server. Provide the correct ShellId or create a new  shell and retry the operation.

**Comment by dariomws** [comment]
@SebastienGu - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @SebastienGu Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
