### ISSUE TITLE
Command missing: New-Contact, Set-Contact

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7016]
Hello,

the following commands are missing:
* New-AzureAdContact (AzureAd)
* Set-AzureAdAccount (AzureAd)
* New-Contact (ExchangeOnlineManagement)
* Remove-Contact (ExchangeOnlineManagement)

```
PS C:\> Get-command -noun AzureADContact

CommandType     Name                                               Version    Source               
-----------     ----                                               -------    ------               
Cmdlet          Get-AzureADContact                                 2.0.2.129  AzureAdPreview       
Cmdlet          Remove-AzureADContact                              2.0.2.129  AzureAdPreview       


PS C:\> Get-command -noun Contact

CommandType     Name                                               Version    Source               
-----------     ----                                               -------    ------               
Function        Get-Contact                                        1.0        tmp_hcroih1x.2yk     
Function        Set-Contact                                        1.0        tmp_hcroih1x.2yk     


PS C:\> Get-command -noun MailContact

CommandType     Name                                               Version    Source               
-----------     ----                                               -------    ------               
Function        Get-MailContact                                    1.0        tmp_hcroih1x.2yk     
Function        New-MailContact                                    1.0        tmp_hcroih1x.2yk     
Function        Remove-MailContact                                 1.0        tmp_hcroih1x.2yk     
Function        Set-MailContact                                    1.0        tmp_hcroih1x.2yk     

```

If someone could tell me how I can create Contact objects (for use in Teams!) in AzureAd or in a specific Global Address List, I would appreciate it. I need to cover the full lifecycle: New/Get/Set/Remove
I am trying to solve a migration issue moving from Skype to Teams and create Contact Objects for Analog Devices we have in the organisation.

Thanks,
David

**Comment by DEberhardt** [comment]
Cross-promoted in **azure-docs-powershell-azuread** as well: https://github.com/Azure/azure-docs-powershell-azuread/issues/552

**Comment by get-itips** [comment]
Hello @DEberhardt David.

Have you tried with [New-MailContact](https://docs.microsoft.com/en-us/powershell/module/exchange/new-mailcontact?view=exchange-ps) and [Remove-MailContact](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-mailcontact?view=exchange-ps) ?

**Comment by DEberhardt** [comment]
I have managed to creating a Contact with `New-MailContact`, then using `Set-Contact` to add the Phone Number.
My use-case is to add Contact Objects (for Analog Devices) for use in the Teams Global Address list and finding Objects by Name and Extensions.

However, I feel, the whole procedure is not well documented:
- An Example Page would be good to demonstrate the whole process for Contact objects in general
OR
- Clean availability of all PowerShell commands

The latter can be achieved either with an Alias to the existing commands or with introduction of dedicated Cmdlets to enable people to find them.

**Comment by get-itips** [comment]
Hello @DEberhardt David. How are you?

> An Example Page would be good to demonstrate the whole process for Contact objects in general

This in particular I think would fit in another repo (https://docs.microsoft.com/en-us/MicrosoftTeams/), you can always propose an improvement to documentation.

> Clean availability of all PowerShell commands

I know the team behind the Teams PowerShell module is constantly working on adding new features, as I always say, the best thing to do in this case is create a [uservoice](https://microsoftteams.uservoice.com/) entry so it reaches the team.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DEberhardt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DEberhardt** [comment]
Hello, FYI
UserVoice entry created - more general in phrasing, but no takers yet:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/42449707-powershell-commands-for-contact-objects-common-ar
