### ISSUE TITLE
Command missing? Get-TeamsIPPhone, Set-TeamsIPPhone, New-TeamsIPPhone, Remove-TeamsIPPhone

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7017]
Hello,

browsing through the Admin Center I found that there is a section for IP Phones now:
![image](https://user-images.githubusercontent.com/44290340/103459761-3be77100-4d09-11eb-8bb6-3482eb7a85a3.png)
NOTE: The linked "learn more" article does not answer the below

How would I query these via PowerShell (Module Skype has Get-CsCommonAreaPhone, but that is for an OnPrem object). In Teams this is a User (so `Get-AzureAdUser` and `Get-CsOnlineUser` will list the object, but how do I filter for it?)

Specifically:
- **How do I query (GET) Common Area Phones?**<br />`Get-AzureAdUser`, yes, but do I have to filter for licenses or will they have a specific ObjectType?
- **How do I create new Common Area Phones?**<br />Are they registering directly via log-in. In terms of licensing, I needed to create a `New-AzureAdUser` before, can these be staged (bound to a specific device ID, MAC?)
- **How do I remove a CAP?**<br />In the lifecycle of things, I may want to block a specific device or even remove it completely
- **How are Conference Phones different here (apart from the license)**<br />What is the differentiating factor for a User/CAP/Conference Phone to show up in the above lists respectively. This can't be the tag as it would have to be assigned a pre-existing tag. How is the list above generated for _All Phones, User Phones, Common area phones, Conference phones_ respectively? Is it the Sign-in mode?

I am in the process of writing all 4 commands for Common Area Phones for my TeamsFunctions (emulating `New-CsCommonAreaPhone`, but for Teams), but will need to ascertain exactly what makes a CAP different from a normal User and a Conference Phone in order to proceed. I would also love to do the same with Conference Phones (or have a more generic `New-TeamsIPPhone` to create either which one)

FYI, my current scope for `New-TeamsCommonAreaPhone` (New-TeamsCAP):
- `New-AzureAdUser` to create the Object (UPN, DisplayName)
- Assign Common Area Phone license (if available in the Tenant)
- Assign IP Phone Policy, Calling Policy, Call Park Policy (if provided)
- Inform Admin with Warnings if Sign-in mode of effective IP Phone Policy is not "CommonAreaPhoneSignIn"

Thanks,
David

PS: In the Exchange 2010 GUI, the run PS-commands were shown so that we could learn instinctively how to do the same in PowerShell, I am missing this approach now for the O365 world and see a lot of discrepancies between Admin Center and PowerShell. Any way this could be fed back to the Product Team please?

**Comment by shivtorov** [comment]
sidenote:
Jeff's blog is my goto source of info about all Lync-...-Teams phones.
http://blog.schertz.name/2020/04/common-area-phones-in-microsoft-teams/

**Comment by get-itips** [comment]
Hello @DEberhardt David, how are you?
Have you already seen [this article](https://docs.microsoft.com/en-us/microsoftteams/set-up-common-area-phones) ? Does that helps answer your questions?
AFAIK currently there aren't cmdlets to handle -IPPhones using the MicrosoftTeams PowerShell, please use https://microsoftteams.uservoice.com/ to propose to the team to work on them.
Thank you

**Comment by DEberhardt** [comment]
Jeffs blog is a must-read indeed :) (and a have-read already...)
Same goes for the Common Area Phone article.

However, it doesn't go into that much detail on how to identify these special users via PowerShell.
For Example, Resource Accounts are able to be queried with Get-CsOnlineApplicationInstance as well as with Get-AzureAdUser and Get-CsOnlineUser. Going by the AzureAdUser Object I can read the Department name, as it has to be "Microsoft Communication Application Instance", otherwise the Resource Account isn't working

What I am after is the same for a Common Area Phone, Conference Phone or Meeting Room.
A Parameter on the AzureAdUser (ObjectType, MemberType) or the CsOnlineUser.

I can try to reverse engineer this on a few examples (but have hoped to avoid that effort of comparing multiple objects just to find a distinctive commonality). I think it would be beneficial if someone could define the cornerstones of "This is a Common Area Phone/Conference Phone/MeetingRoom". I believe it can't simply be the SignInMode of the assigned TeamsIPPhonePolicy... (lookup for multiple tenants may take too much time to find a meaningful dataset of my two handful of devices)

**Comment by DEberhardt** [comment]
Uservoice created: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/42369073-teams-ip-phones-query-distinction-and-powershel

**Comment by get-itips** [comment]
> Uservoice created: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/42369073-teams-ip-phones-query-distinction-and-powershel

Voted. ;)

> However, it doesn't go into that much detail on how to identify these special users via PowerShell.

Unfortunately, I do not have a CAP/CAP License to test this, probably checking the `AssignedPlan` attribute outputted by `Get-CsOnlineUser`.

Thanks

**Comment by DEberhardt** [comment]
The license alone can be an indicator for a CAP, yes, but Conference Phones and Meeting Room phones have to have an E1/E3/E5 license due to the requirement of a mailbox. The only distinction I currently found is the SignInMode between all three, but I cannot query all the Effective SignInMode for each CsOnlineUser with a Script that performs like the Admin Center does (it would have to run through all users and query the policy assigned (or the global one) individually).

I mean I could be fancy and create myself a custom object (hashtable) enumerating all TeamsIPPhonePolicies, filter the ones that have CommonAreaPhoneSignIn for example, then filter all CsOnlineUsers against the policies that match... (would definitely be faster), but would have hoped that this is already in development or thought about.

It also doesn't solve the problem of the Global policy (which could give me results for all, if that is set as the default)
I cannot exclude the Global policy however, unless the tenant does have a policy assigned to all object...

This is why I am asking for a distinguishing characteristic to cleanly filter for these devices.

**Comment by get-itips** [comment]
Hello @DEberhardt David.

I understand what you mean, that is maybe the need for some specific cmdlets to manage CAP devices on Teams will be welcomed. 

**Thanks**

**Comment by yogkumgit** [comment]
@DEberhardt  Thank you very much for your kind feedback and logging this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
