### ISSUE TITLE
Get-AzureADDirectoryRoleMember - to update

### ISSUE THREAD

**Issue by SebastienGu** [MicrosoftDocs/office-docs-powershell#7018]
Since it's now possible to assign Security Groups to an Azure Role It would be good to update **Get-AzureADDirectoryRoleMember**
https://docs.microsoft.com/en-us/azure/active-directory/roles/groups-concept 

We are testing the Security Group based roles but reporting is difficult both with the UI (I raised a separate ticket with MS) and with PowerShell.
It would make sense to have the same parameter as Get-ManagementRoleAssignment to see all users assigned to the role: Get-AzureADDirectoryRoleMember **-GetEffectiveUsers**

**Comment by chrisda** [comment]
@SebastienGu, sorry; wrong location for this issue. Azure AD cmdlets are documented here: 

<https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/Get-AzureADDirectoryRoleMember.md>

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @SebastienGu Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
