### ISSUE TITLE
New-JournalRule cmdlet not available in ExchangeOnline V2

### ISSUE THREAD

**Issue by ananimesh** [MicrosoftDocs/office-docs-powershell#7022]
It appears the New-JournalRule cmdlet is not available in ExchangeOnline V2. When trying to use this cmdlet I get the error,
'**The term 'New-JournalRule' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.**'

I get the error after importing the V2 module and connecting. Also, get the same error when trying to use the cmdlet in PS implicit remoting. 
Import-Module "ExchangeOnlineManagement.psd1" -Verbose
Connect-ExchangeOnline
(Invoke-Command -Session (Get-PSSession) -ScriptBlock {New-JournalRule})

**Comment by ananimesh** [comment]
Actually I found out I was able to see the cmdlet when I connected using the UPN - '**Connect-ExchangeOnline -UserPrincipalName**'. However, when trying to connect using the app, it was not showing up.

I thought I had to do something with my app configured. The app role in AD was '**Global Reader**'. I changed it to '**Exchange Administrator**' and it worked. 

I did not know the EXO V2 had the capability to restrict the cmdllet could be restricted based on the Role. 
Is there some documentation regarding this already?

**Comment by ananimesh** [comment]
I will be nice to have some documentation explaining what roles bring in which cmdlets.

**Comment by Tammychmarney** [comment]
ACCOUNT ADMINISTRATOR SETTINGS SANDRA E CHMARNEY sechmarney@outlook.com single account users in CANADA using ENGLISH LANGUAGE ON ALL SERVICES INCLUDING APPLE CANADA

**Comment by Tammychmarney** [comment]
Go to GITHUB CANADA REGION ROGERS YAHOO MAIL

**Comment by dariomws** [comment]
Hi @Tammychmarney, thank you for your feedback.

For more information about how permissions work in Exchange Online, please see the following article:
https://docs.microsoft.com/en-us/exchange/permissions-exo/permissions-exo

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @ananimesh Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
