### ISSUE TITLE
Get-EXORecipient Anr Parameter Unexpected Results

### ISSUE THREAD

**Issue by exactmike** [MicrosoftDocs/office-docs-powershell#7025]
![image](https://user-images.githubusercontent.com/6854516/103681281-439b5580-4f55-11eb-803d-6e26cedcd5d4.png)

The "-Anr" parameter  in Get-EXORecipient does not seem to work as expected.  Instead of returning matching recipient objects it seems to always return all objects (subject to the normal limit of only returning 1000 objects when -ResultSize is not specified).  This is in contrast to the behavior of Get-Recipient -Anr which works as expected:

![image](https://user-images.githubusercontent.com/6854516/103682595-16e83d80-4f57-11eb-9348-9f540692e3a0.png)

(Interestingly, Get-EXOMailbox -Anr parameter works as expected)

**Comment by dariomws** [comment]
Hi @exactmike, thank you for submitting your feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

You can also write a comment on the product team blog about this issue: https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-general-availability-of-the-exchange-online/ba-p/1436623. 

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @exactmike Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
