### ISSUE TITLE
Command not valid for teams

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/office-docs-powershell#7026]
This command does not work for teams; you have to use the undocumented command New-TeamsRetentionComplianceRule

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e8e582d-6b99-0a36-59e4-954e622154ce
* Version Independent ID: bb512026-47d0-a419-d56a-1aa3ca57b255
* Content: [New-RetentionComplianceRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-retentioncompliancerule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-RetentionComplianceRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-RetentionComplianceRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@stephenc01, I'm told that the \*TeamsChatLocation\* and \*TeamsChannelLocation\* parameters in the *-RententionCompliancePolicy cmdlets are the backend components of the current UI M365 Compliance center and/or Security & Compliance Center.

The \*-TeamsRetentionCompliancePolicy/Rule cmdlets were deprecated some time ago, but appear to still linger.

So are you saying that New/Set-RetentionCompliancePolicy allow you to select Teams locations, but you need to use New/Set-TeamsRetentionComplianceRule to get the retention rules to work properly?

**Comment by stephenc01** [comment]
> 
> 
> @stephenc01, I'm told that the *TeamsChatLocation* and *TeamsChannelLocation* parameters in the *-RententionCompliancePolicy cmdlets are the backend components of the current UI M365 Compliance center and/or Security & Compliance Center.
> 
> The *-TeamsRetentionCompliancePolicy/Rule cmdlets were deprecated some time ago, but appear to still linger.
> 
> So are you saying that New/Set-RetentionCompliancePolicy allow you to select Teams locations, but you need to use New/Set-TeamsRetentionComplianceRule to get the retention rules to work properly?

Hey, @chrisda. This was part of MSCase 23287620. *RetentionCompliancePolicy does not work for teams location.

`Description: This code produces the error below. $name = "Default XX Year Retention Teams [XX2]" $pol = New-RetentionCompliancePolicy -Name $name -TeamsChatLocation "XXXXXX" New-RetentionComplianceRule -Name $name -RetentionDuration 1825 -Policy $pol.Guid.Guid -RetentionDurationDisplayHint "Years" -RetentionComplianceAction "KeepAndDelete" -ExpirationDateOption "CreationAgeInDays" The parent policy 'FFO.extest.microsoft.com/Microsoft Exchange Hosted Organizations/XXXXXX.onmicrosoft.com/Configuration/Default XX Year Retention Teams [XX2]' is a Teams policy. Configuring non-Teams supported parameters of this rule are not allowed. + CategoryInfo : NotSpecified: (:) [New-RetentionComplianceRule], ErrorModifyingT...ameterException + FullyQualifiedErrorId : [Server=BN3NAM04WS024,RequestId=7f9c346e-987e-43b1-927e-bc5500874f38,TimeStamp=12/12/2020 5:29:03 PM] [FailureCategory=Cmdlet-ErrorModifyingT eamsRuleWithNonTeamsAllowedParameterException] E08251C8,Microsoft.Office.CompliancePolicy.Tasks.NewRetentionComplianceRule + PSComputerName : nam04b.ps.compliance.protection.outlook.com`

**Comment by chrisda** [comment]
@stephenc01, could the cause of this error be the RetentionDurationDisplayHint and ExpirationDateOption parameters don't apply to Teams retention? That's the vibe I'm getting...

**Comment by yogkumgit** [comment]
@stephenc01 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
