### ISSUE TITLE
How is -CertificateFilePath/CertificatePassword working without private key?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#7027]
I'm unsure how it works that we don't need the private key included in the PFX file.  I've tested and confirmed that yes it does work exactly as described in the example, but I'm scratching my head as to how.  If we were doing client assertion, my understanding is that we'd be signing the JWT which would require the private key.  That obviously isn't what's happening here.  So now then, I'm confused, what is happening here?

I feel like this is less secure and as I've stated on TechCommunity, and to the EXO V2 feedback email address, I wish -CertificateFilePath and -CertificatePassword options would be removed from this module.  But in the meantime, I'd like to know what's happening here that makes it so the private key is not required in the PFX file.

I also double-checked that it continues to work even after I've deleted the certificate from my cert:\CurrentUser\My store, so I know the module isn't just using the PFX to figure out which certificate in my local store it needs to go an get the private key from.  So again, scratching my head as to what is happening here when we use the PFX option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#step-2-assign-api-permissions-to-the-application)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @JeremyTBradshaw, thank you for your feedback.

I think the best place to reach the product team and get this information is the blog:
https://techcommunity.microsoft.com/t5/exchange-team-blog/modern-auth-and-unattended-scripts-in-exchange-online-powershell/ba-p/1497387
I see that you left several comments there.

**Comment by JeremyTBradshaw** [comment]
@dariomws I will do that, but I don't necessarily think my issue is misplaced here whereas the example in the article is relevant to the question.  I guess it doesn't matter since it's not up to me anyway and clearly I'm just expressing frustration through a few different channels.  So maybe I'll step away and defuse then reassess.

**Comment by dariomws** [comment]
Thank you for your reply @JeremyTBradshaw!

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @JeremyTBradshaw If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by JeremyTBradshaw** [comment]
@yogkumgit to be clear, no explanation was provided whatsoever. I was simply diverted elsewhere, by someone who isn't internal to Microsoft.  It's fine that this is closed, I don't even care anymore, but I'm not in agreement that any explanation or solution was provided.

**Comment by JeremyTBradshaw** [comment]
@dariomws @yogkumgit and anyone else who comes along and sees this issue.  FYI I was mistaken, and in fact, in the examples, the private key is indeed included the exported PFX file.  The issue I was raising, it non-existing.

From the [New-SelfSignedCertificate page](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps), it is confirmed that the default value for the -KeyExportPolicy **ExportableEncrypted**.  I think I had an assumption (not really an active thought, just autopilot assumption) that the policy was defaulted to "NonExportable".

[Export-PfxCertificate](https://docs.microsoft.com/en-us/powershell/module/pkiclient/export-pfxcertificate?view=win10-ps) exports the private key, unless the certificate is marked as private key being NonExportable, which was not the case in the example's 1st command.

So the issue I was raising is not an issue at all, it was just me stuck in my own way with an underlying, incorrect assumption (which made an @$$ out of ~"u" and~ "me" (just me), as the saying goes).
🤦‍♂️

**Comment by dariomws** [comment]
Thanks for coming back with us! Nice to know that it's actually not an issue.
