### ISSUE TITLE
Need a "Please Note" for DeliverMessageAfterScan setting

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/office-docs-powershell#7033]
Need a "Please Note" for DeliverMessageAfterScan setting that if the URL is bad the entire message will not be delivered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a1f9fa-7dd6-ebf1-3e64-ef47bd3962b2
* Version Independent ID: 5ea9bde3-9fe9-8ae1-0992-b12223c4d7c4
* Content: [New-SafeLinksPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-safelinkspolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-SafeLinksPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-SafeLinksPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jmmowrer, done. In the future, you too can make changes like this directly without opening an Issue first. See <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>. 

Also the _DeliveryMessageAfterScan_ parameter is available on New-SafeLinksPolicy and Set-SafeLinksPolicy, so I made the same  update in both topics.

Thanks for the feedback.

Closing
