### ISSUE TITLE
Step 2 clarifications

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/office-docs-powershell#7034]
Regarding "Step 2: Assign API permissions to the application": it would be helpful to clarify that is default "Microsoft Graph / User.Read" permission required, or can it it be safely removed? If it needs to stay, please instruct on the Manifest syntax - need to have comma between multiple requiredResourceAccess elements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ArttuArstila, do the recent updates to the topic clarify anything? The topic as written should describe any/all permissions that are required.

**Comment by ArttuArstila** [comment]
Hi! Thanks for asking. I don't think it's not quite there yet, there is no comment about what to do for the  "Microsoft Graph / User.Read" permission that appears for the new app by default. It also affects how the JSON should be edited (where to add the comma) etc. Probably familiar stuff for those editing app registrations a lot, but this might be the first time for many EXO admins.

**Comment by chrisda** [comment]
@ArttuArstila, I stepped through the procedures as written very recently, and I never even saw "Microsoft Graph / User.Read" permissions. I presume this is because the Step 2 instructions for manually editing the manifest *replace* whatever existing permissions are created by default for the new app?

I'm describing the situation correctly, then I'm not sure what documentation updates are required, other than possibly a note for Step 2 that says:

> [!NOTE]
> The procedure in this section replaces any default permissions that were automatically configured for the new app. You don't need these default permissions.

What do you think?

**Comment by ArttuArstila** [comment]
Thanks for reply @chrisda! That sounds good, but I cannot yet see that clarification on the page:
https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#step-2-assign-api-permissions-to-the-application

**Comment by chrisda** [comment]
@ArttuArstila, that's because I didn't do it yet. But, I can tell from your response that you approve. So I did it.

Thanks for the feedback.

Closing
