### ISSUE TITLE
More RBAC roles to be added?

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/office-docs-powershell#7035]
Current list of supported RBAC roles is quite short. They do not support a proper least privilege model of using only pure Exchange RBAC instead of these too powerful AADroles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#step-2-assign-api-permissions-to-the-application)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ArttuArstila, interesting point, but nothing that can be fixed by documentation updates.

Your best bet is to create a suggestion at <https://office365.uservoice.com/> or open a support case.

**Comment by ArttuArstila** [comment]
Thanks, you are correct.
