### ISSUE TITLE
Confirm behaviour of parameter -AllowOrganizersToOverrideLobbySettings

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/office-docs-powershell#7036]
I believe this parameter -AllowOrganizersToOverrideLobbySettings has no effect.  It's legacy from previous lobby controls.  Can this be confirmed and updated.  The lobby options are in full control of the meeting organizer and they cannot be prevented from altering them.

So the text entry of "Set this parameter to true to enable Organizers to override lobby settings" is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @thewrabbit how are you?
I am looking into this... Thanks

**Comment by get-itips** [comment]
Hello @thewrabbit I tested this and apparently as you say, it has no effect currently, however, I would like to have confirmation from @tomkau
Tom, can you help us here? Thanks

**Comment by get-itips** [comment]
Hello, @tomkau can you kindly help as get a confirmation here? Thank you!
