### ISSUE TITLE
New-CsOnlineSession no longer supports the documented -OAuthAccessToken parameter

### ISSUE THREAD

**Issue by happywino** [MicrosoftDocs/office-docs-powershell#7040]
Using the MicrosoftTeams module 1.1.6 and 1.1.10 preview New-CsOnlineSession doesn't have the -OathAccessToken parameter, without this parameter we are unable to authenticate to SFBO using a Service Principal token.

**Comment by get-itips** [comment]
Hello @happywino how are you?
The parameter has been removed from documentation [in a recent update.](https://github.com/MicrosoftDocs/office-docs-powershell/pull/7012) as the parameter has been, as you said, removed from the cmdlet.
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @happywino Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
