### ISSUE TITLE
Documentation pages for Get-/Set-/Grant-/Remove-CsTeamsFeedbackPolicy are missing

### ISSUE THREAD

**Issue by EricHindrichsen** [MicrosoftDocs/office-docs-powershell#7047]
Hi,

As the title suggests, from all the *-CsTeamsFeedbackPolicy cmdlets only New-CsTeamsFeedbackPolicy seems to have a documentation page. Where are the others?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e9c02c-2fa2-52b2-2898-71ddda3eaf21
* Version Independent ID: f5fbed81-ebc2-9dfa-d180-3704696cb3aa
* Content: [New-CsTeamsFeedbackPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsfeedbackpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsFeedbackPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsFeedbackPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @EricHindrichsen Eric, how are you? Currently working on adding those articles. Thanks for reporting.

**Comment by EricHindrichsen** [comment]
That's great news, thank you!

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________
