### ISSUE TITLE
SharePoint PowerShell Documentation

### ISSUE THREAD

**Issue by RVAHaver01** [MicrosoftDocs/office-docs-powershell#7048]
None of the SharePoint PowerShell documentation has been updated to include the commands for when you are using an Azure Managed SQL instance.  Please update the documentation or share with me what that documentation is.

**Comment by tseward** [comment]
Can you expand upon what you're asking for? How does your Azure Managed SQL instance relate to SharePoint PowerShell?

And is this for SharePoint Server? I would assume so given you're talking about a SQL MI. Again, not sure how that would alter SharePoint Server cmdlet usage since you don't "sign in" to the module.

**Comment by RVAHaver01** [comment]
SharePoint 2016 and 2019 now support running on a SQL MI in stead of using a SQL Server.  I have these two environments running in Azure against SQL MI and they are running just fine.  However, the SharePoint Server PowerShell command documentation has not been updated to include the arguments or examples required to do this.  In order for me to setup these environments I had to query the actual PowerShell for the arguments required.

In many cases you have to use the SQL MI Host name and Database Credentials verses the Database Server name and the SQL Account Name and password.

There are many things (especially in 2019) that can only be done via PowerShell that having examples for when you are using SQL MI it would make life easier.

**Comment by tseward** [comment]
@RVAHaver01 OK, so you're asking for a doc improvement, but have you looked at https://docs.microsoft.com/en-us/sharepoint/administration/deploy-azure-sql-managed-instance-with-sharepoint-servers-2016-2019?

**Comment by RVAHaver01** [comment]
Yes I have however that only takes care of the initial run of the PS Config.  If someone would walk thru the complete configuration of SP2019 you would quickly understand what I am talking about.  I think I have found a but with the new-spsite command because it errors if it is the root site but works just fine if it is any other site.  Mount-SPContentDatabase does not work and I have MS Support case # 23600754 in now because I am trying to do a test upgrade to SP2016 and that command does nothing but error.

**Comment by get-itips** [comment]
Hello @RVAHaver01 how are you?

I was going to suggest opening a support ticket however, you already have an open support ticket, can you please kindly keep us posted here on the resolution, so if we identify that an improvement to [Mount-SPContentDatabase](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/mount-spcontentdatabase?view=sharepoint-ps) article, we can use that to feed that article.
I am suspecting that you are specifying the SQL auth database credentials to that cmdlet using `-DatabaseCredentials` right?

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @RVAHaver01 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future

**Comment by RVAHaver01** [comment]
Yes I am but still getting an error stating it does not have permissions to the Master database.  This is an example where we need to update the documentation showing examples of when you are using SQL Managed Instances because trying to use the SQL Auth arguments don’t always work.

Regards
David Haver
Manager, Infrastructure Services – Digital
Cherry Bekaert LLP
(O) 804-794-3491 | (D) 804-673-5762 | (C) 804-690-7669  <= The best number to reach me during COVID-19 times

**Comment by get-itips** [comment]
Hello @RVAHaver01 
How are you?
I think, in that case, that the article that could be improved is the one that @tseward shared with you.
That article is in another documentation repository, can you open an issue there with your suggestion? 

https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues

I think we can also benefit from the result of the ticket you have opened, in case any improvement to that article is identified.

Thank you for your feedback.

**Comment by RVAHaver01** [comment]
I have opened the issue.

Regards
David Haver
Manager, Infrastructure Services – Digital
Cherry Bekaert LLP
(O) 804-794-3491 | (D) 804-673-5762 | (C) 804-690-7669  <= The best number to reach me during COVID-19 times
