### ISSUE TITLE
Correct way for IPv6

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/office-docs-powershell#7052]
I have a rule to disable EAC and PS from outside the network, as recommended.
This worked until we upgraded the routers to IPv6.  
What's the correct way to include the v4 and v6 subnets in a cmd like this:
`New-ClientAccessRule -Name "Restrict EAC Access" -Action DenyAccess -AnyOfProtocols ExchangeAdminCenter -ExceptAnyOfClientIPAddressesOrRanges 192.168.10.1/24`

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43667016-c662-727c-4566-9356330b0665
* Version Independent ID: decd796f-a731-2289-87d7-ee173788025c
* Content: [New-ClientAccessRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-clientaccessrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ClientAccessRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ClientAccessRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by GLComputing** [comment]
Should also be added to this doc:
https://docs.microsoft.com/en-us/exchange/clients/client-access-rules/procedures-for-client-access-rules?view=exchserver-2019&source=docs

**Comment by chrisda** [comment]
@GLComputing, done.

Thanks for the feedback.

Closing
