### ISSUE TITLE
HTTP 403 Error when creating a session with New-CsOnlineSession (MicrosoftTeams)

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7058]
Hello,

recently, when creating a session with New-CsOnlineSession, I get - intermittently - this:

`Session creation failed: Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The WinRM clien t received an HTTP status code of 403 from the remote WS-Management service. For more information, s ee the about_Remote_Troubleshooting Help topic.`

I say intermittently, because I cannot pinpoint exactly why that is. I even tried opening a whole new PowerShell window (ISE) before running my connect commands (`Connect-AzureAd`, then `Connect-MicrosoftTeams`, then (my) `Connect-SkypeOnline` (which runs `New-CsOnlineSession`).

I had this earlier when creating a session to tenant A then disconnected everything, then connect to Tenant B that it tried to sign me in with the Credentials from tenant A (no solution to that yet as it would require https://github.com/MicrosoftDocs/office-docs-powershell/issues/6997 (even without MFA))

This site here [Diagnose Problems with the Skype for Business Online Connector](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/diagnose-problems-with-the-skype-for-business-online-connector) has helped me a lot over the years, but I don't think there is one yet for the new method.

Can one please be created (and then link it to [skype/skype-ps/skype/New-CsOnlineSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineSession.md)
Covering the 403 issue, how to cleanly disconnect a session and maybe also clean reconnect?

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2abd383-7815-9404-41ba-72bbedb5208a
* Version Independent ID: 88342584-33e2-47c6-baf1-81644d5cc7a5
* Content: [New-CsOnlineSession (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinesession?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineSession.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DEberhardt David

I use the cmdlet a lot and I do not receive such error, I think the best, in that case, is opening a support ticket in your tenant and ask for help there.

Also, the document you recommend to create/improve is in another repository, so you will have to propose it here https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues

Thanks

**Comment by DEberhardt** [comment]
This only happens if you have an existing session to Azure, then try to connect to a different Skype online tenant.

It is a matter of cleanly closing existing sessions

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by get-itips** [comment]
> This only happens if you have an existing session to Azure, then try to connect to a different Skype online tenant. It is a matter of cleanly closing existing sessions Get Outlook for Android<https://aka.ms/ghei36>

Thanks for returning and sharing that feedback.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DEberhardt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
