### ISSUE TITLE
Reconnect to a Session created with New-CsOnlineSession

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7059]
Hello,

recently, when creating a session with New-CsOnlineSession in MicrosoftTeams, `Enable-CsOnlineSessionForReconnection` is not available anymore. Has the functionality been captured in the new Command? (It doesn't look like it has...)

The behaviour is as follows.
After 60mins (when using Session options set to 4hrs, this drops to 15 or sometimes 5 minutes...)
Putting the SessionOption to the side, I have a consistent timeout of 60mins and I currently cannot recover the session.

Once timed out, a credential dialog appears with the username "oauth" filled in and no password (I cannot find any documentation on what to do here, simply clicking OK does not work).
When clicking cancel, a new credential dialog appears, without a username filled in and - I think - This is running the -Credential parameter that does not work for me when using MFA. So I click cancel again.

The only recourse I currently have is to cleanly disconnect and connect again.

Is there a way to reconnect?

Thanks,
David

PS: Behaviour with New-CsOnlineSession (SkypeOnlineConnector) and Enable-CsOnlineSessionForReconnection was that I simply ran: `Get-CsTenant` and it prompted me for modern auth (only password needs to be entered) and it would re-establish the connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2abd383-7815-9404-41ba-72bbedb5208a
* Version Independent ID: 88342584-33e2-47c6-baf1-81644d5cc7a5
* Content: [New-CsOnlineSession (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinesession?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineSession.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DEberhardt David, I know that the team behind Teams/Skype cmdlets is constantly working on improving it, so probably the next versions will take care of reconnection, in case you want your idea to reach the team, please don't hesitate to create and submit it [here](https://microsoftteams.uservoice.com/).

**Comment by DEberhardt** [comment]
Hi, Think I have already done that^^
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/42287602-new-csonlinesession-does-not-adhere-to-sessionopti
😄

**Comment by yogkumgit** [comment]
@DEberhardt Thank you very much for your kind feedback. As per your comment, you have already raised a User Voice. Thank you.. Now, concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback
