### ISSUE TITLE
RetentionDuration not up to date

### ISSUE THREAD

**Issue by ammicule** [MicrosoftDocs/office-docs-powershell#7060]
Hi!
The -RetentionDuration information is out of date, as the only options are <=twelve months:
![image](https://user-images.githubusercontent.com/77338046/104325484-5c75af00-54f1-11eb-8804-93a7affb018b.png)
and currently, in a tenant, we can see the following:
![image](https://user-images.githubusercontent.com/77338046/104325550-6c8d8e80-54f1-11eb-8078-99c90e3a98e3.png)
Which is a lot more than just 12 months.

Have a great day!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 648ba896-7420-c38d-6a6a-464b71ef4473
* Version Independent ID: a99950aa-bee3-5ea2-bce2-25299035d753
* Content: [New-UnifiedAuditLogRetentionPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-unifiedauditlogretentionpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-UnifiedAuditLogRetentionPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-UnifiedAuditLogRetentionPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ammicule, confirmed that the TenYears value was missing, so I added it. This also affects the New-UnifiedAuditLogRetentionPolicy cmdlet, so I also added it there.

Thanks for the feedback.

Closing
