### ISSUE TITLE
Step 5 UI changed. Can't find app in users list

### ISSUE THREAD

**Issue by yuri-wisestamp** [MicrosoftDocs/office-docs-powershell#7068]
The UI looks different today:
![image](https://user-images.githubusercontent.com/5073294/104470151-10466f80-55c2-11eb-815c-f80549689bc4.png)

When clicking _here_, searching for Exchange Admin and clicking, we're getting to a screen similar to what the docs show:
![image](https://user-images.githubusercontent.com/5073294/104470474-6b786200-55c2-11eb-9f6b-bd739585064d.png)

 but cant find the registered app in the list, thus can't assign anything,

**Comment by ZA-Ray** [comment]
I'm also battling to get this step working - glad I'm not the only one.  I was wondering if Azure AD Premium licensing is needed, but there is no mention of this on the page.

**Comment by dg42xyz** [comment]
Also having this issue, any workaround available?

**Comment by dariomws** [comment]
Hi @yuri-wisestamp, thank you for your feedback.

Could you kindly put the link to the article you are referring? I couldn't find it. Thanks!

**Comment by ZA-Ray** [comment]
hi @dariomws , this is it:
[https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps](url)

**Comment by yuri-wisestamp** [comment]
@dariomws https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps

**Comment by dariomws** [comment]
@yuri-wisestamp @ZA-Ray @dg42xyz, this is how it looks now when you click on **Add assignments**. You need to click on **No member selected** and there you can select the app.
![image](https://user-images.githubusercontent.com/33589238/106122880-fcf5e100-6137-11eb-8be5-6ffdb1f87db1.png)
I'll update the article.

**Comment by ZA-Ray** [comment]
Hi @dariomws, initially I thought I was using the wrong tool as I was in https://aad.portal.azure.com/ and your screenshot shows https://portal.azure.com/.  Navigating from https://aad.portal.azure.com/ I found i could search and add my app.  I then tried aad.portal.azure.com, and to my surprise again found that I could find my app.  This definitely wasn't working a few days ago when I first tried this.  ;-)  But happy it's working now!  Many thanks.

**Comment by chrisda** [comment]
I just completed a major overhaul of [the topic](https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2) with lots of screenshots to match the current UI. I, to agree that several weeks ago when I started, something was amiss; Step 5 didn't work at all as described. Whatever mojo the Azure AD team was working through seems to have cleared up.

At least for me in my tenant. Please comment here if your UI doesn't match.
