### ISSUE TITLE
Get-SPOuser cmdlet get throtled if you have more than 3000 users in a site

### ISSUE THREAD

**Issue by Mr-K07** [MicrosoftDocs/office-docs-powershell#7070]
Issue: Get-spouser does not retrieve all the users in a site collection even after using the -limit all parameter
Expected behavior : retrieve all users from the site collection

Details: when I run the get-spouser ... I get no result. If I get a Fiddler I can see that after about 3000+ events I get 429. I have to mention that we are a mid / large company and in some site collections we have over 3000 users, internals + externals

**Comment by get-itips** [comment]
Hello @Mr-K07 how are you?
As here we are limited to documentation issues, the best thing to do in your scenario is to open a support ticket directly from your tenant.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Mr-K07 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
