### ISSUE TITLE
Type AppleSensitivityLabel 

### ISSUE THREAD

**Issue by arnauvc** [MicrosoftDocs/office-docs-powershell#7075]
In the -ApplySensitivityLabel parameter, there's a typo:

The Appl**e**SensitivityLabel parameter specifies which label to use for the autolabel policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3248996-72e7-6206-484c-d6e778ed8918
* Version Independent ID: da9bd1a9-5632-1cb9-334f-a6db781f62ff
* Content: [New-AutoSensitivityLabelPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-autosensitivitylabelpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-AutoSensitivityLabelPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@arnauvc, I fixed it. In the future, you too can make updates like this yourself without opening an Issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>. 

Thanks for the feedback.

Closing

**Comment by arnauvc** [comment]
Hi Chris,

Thank you very much, I was not aware of that and I'm not used to doing
this. I'll take it into account :)

Best regards,

Arnau

Missatge de Chris Davis <notifications@github.com> del dia dj., 14 de gen.
2021 a les 17:39:
