### ISSUE TITLE
Using Parameter ActiveSync does only return EAS devices and not includes them

### ISSUE THREAD

**Issue by thepill** [MicrosoftDocs/office-docs-powershell#7076]
The parameter description for `ActiveSync` ([here](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mobiledevice?view=exchange-ps#parameters)) says,

> The ActiveSync switch specifies whether to include mobile devices that synchronize with Exchange ActiveSync. You don't need to specify a value with this switch.

 that mobile devices using active-sync will be **included** in the result, but actually using `ActiveSync` (exchange online) only returns active-sync devices.

![image](https://user-images.githubusercontent.com/8901210/104569077-26e7d780-5651-11eb-8b6d-8ca0127b0cca.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf20fa6e-0913-7b3e-f005-ec9f47bfabaa
* Version Independent ID: 4f92c9cb-49f8-6cab-3e70-560526eee99a
* Content: [Get-MobileDevice (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mobiledevice?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MobileDevice.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MobileDevice.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@thepill, I fixed it is as you described.

It's interesting that the same ActiveSync switch exists in the Get-MobileDeviceStatistics and Get-EXOMobileDeviceStatistics cmdlet topics, and both of those descriptions match what you're describing.

Thanks for the feedback.

Closing
