### ISSUE TITLE
-Credential does not allow admin account anymore

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#7090]
Hi
On Teams module (1.1.6) I'm trying to open the session using the command:
New-CsOnlineSession -Verbose -Credential firstname.lastname@company.com

That unfortunately fail with error:
**New-CsOnlineSession : Cannot bind parameter 'Credential'. Cannot convert the "firstname.lastname@company.com" value of type "System.String" to type "System.Management.Automation.PSCredential".**

But this page says I should be able to use the account:
"_Type a Skype for Business Online **administrator account name, such as "admin@contoso.com", or** enter a PSCredential object, such as one returned by the Get-Credential cmdlet._"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2abd383-7815-9404-41ba-72bbedb5208a
* Version Independent ID: 88342584-33e2-47c6-baf1-81644d5cc7a5
* Content: [New-CsOnlineSession (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinesession?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineSession.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by tseward** [comment]
You need to pass a credential object. I.e.

```
$cred = Get-Credential -Username fLast@contoso.com
New-CsOnlineSession -Credential $cred
```

You can also do:

    New-CsOnlineSession -Credential (Get-Credential)

Passing a string value to `New-CsOnlineSession -Credential` would never be valid since it is expecting a `Credential` object.

**Comment by Petri-X** [comment]
That is true @tseward. But as I stated on my comment, the documentation tells I should be able to use also the admin account on that parameter.

So is there an error on document after the CMDLet has been moved into Teams PS Module?

**Comment by tseward** [comment]
@Petri-X documentation error. I submitted a PR for correction.
