### ISSUE TITLE
Processing data from remote server api.interfaces.records.teams.microsoft.com failed

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#7091]
Hi,

When opening new session to Skype online using Teams PS module (ver. 1.1.6) and following command;
**$s = New-CsOnlineSession -OverrideAdminDomain  company.onmicrosoft.com -Verbose**

But that fails with following error:

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
VERBOSE: Performing the operation "New-CsOnlineSession" on target "Establishing a PowerShell session connected to the
environment.".
VERBOSE: Reconnect MicrosoftTeams
VERBOSE: OverrideAdminDomain = company.onmicrosoft.com
VERBOSE: AdminDomain =
VERBOSE: Discovering Powershell endpoint Uri
VERBOSE: Initializing remote session.
VERBOSE: TargetPsServerFqdn = admin1e.online.lync.com
VERBOSE: ConnectionUri =
https://api.interfaces.records.teams.microsoft.com/OcsPowershellOAuth/admin1e.online.lync.com?AdminDomain=
**New-CsOnlineSession : Processing data from remote server api.interfaces.records.teams.microsoft.com failed with the following error message: adminDomain** For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:6
 .+ $s = New-CsOnlineSession -OverrideAdminDomain  company.onmicrosoft.com ...
 .+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], PSRemotingTransportException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession

**New-CsOnlineSession : Processing data from remote server api.interfaces.records.teams.microsoft.com failed with the following error message: adminDomain** For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:6
.+ $s = New-CsOnlineSession -OverrideAdminDomain  company.onmicrosoft.com ....
.+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-CsOnlineSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Open.Te
   ams.SfbOnline.CsSession.NewCsOnlineSession
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

What could be the reason for this?
Is it expected that adminDomain should be empty?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2abd383-7815-9404-41ba-72bbedb5208a
* Version Independent ID: 88342584-33e2-47c6-baf1-81644d5cc7a5
* Content: [New-CsOnlineSession (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinesession?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineSession.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @Petri-X 
I was able to successfully use OverrideAdminDomain while trying to reproduce to see if any documentation change was needed

![image](https://user-images.githubusercontent.com/36666927/105080737-de685980-5a56-11eb-980d-72cd511aa781.png)

**Comment by Petri-X** [comment]
Yes, it looks that the issue was on O365 site. Support team told that they did a "object synchronization on backend". And it looks that it solved the issue. Of course we have no clue about this, and if something can be done on the module site to be better to manage exceptions.

But my fire is over now ;)

**Comment by get-itips** [comment]
> Yes, it looks that the issue was on O365 site. Support team told that they did a "object synchronization on backend". And it looks that it solved the issue. Of course we have no clue about this, and if something can be done on the module site to be better to manage exceptions.
> 
> But my fire is over now ;)

Glad to hear that. Have a nice day!
