### ISSUE TITLE
ZapEnabled not found

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/office-docs-powershell#7095]
Hello,

I notice issue #6842 reported the documentation talks about ZapEnabled switch. The related issue says, that switch has been replaced. I can confirm the parameter is not available when using Exchange Basic auth and the newer Exchange Online powershell module.

However, this page reports this switch exists with no indication it has been replaced, and I do not see any pending pull requests to update the page.

Edit: said it was available when it should have read, "is not available"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164c3337-1862-be67-7e1d-ea8055b88791
* Version Independent ID: 3cb06add-3cb6-7cb8-779b-a681e03ab4fb
* Content: [Set-HostedContentFilterPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-hostedcontentfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by jonwbstr** [comment]
Derp moment, the page says it's deprecated. Friday brain. ignore me.

**Comment by chrisda** [comment]
@jonwbstr, as you've discovered, it's a balancing act when a parameter is removed or replaced. I typically don't remove a deprecated parameter until it's truly gone (unavailable to me on a standard, stock tenant). If it's available, regardless of whether it works or it's fallen out of favor, I'll leave the parameter and description in the topic, typically with the language that you saw ("available, but don't use this anymore"). Removing available but unfavored parameters brings it's own set of issues: people will open GitHub issues or support cases asking why this available parameter isn't documented.

All of this being said, I, too see in my stock tenant that ZAPEnabled is now truly gone, so I'll remove it from New/Set-HostedContentFilterPolicy. So your issue did have some merit.

**Comment by jonwbstr** [comment]
I appreciate that approach.

I should have checked the paramer notes. In the past parameters have been
deprecated and the descript changed to say it no longer works, but left in
to prevent automations from breaking.

Old stuff has to be removed eventually!

I am not against leave it as is for a bit, so someone trying to figure out
where the parameter went, has something to find like I should have done. 😁

**Comment by chrisda** [comment]
Nothing left to do, so closing.
