### ISSUE TITLE
Incorrect documenation

### ISSUE THREAD

**Issue by DEWallen** [MicrosoftDocs/office-docs-powershell#7105]
AccessRules seems to be documented incorrectly... it is simply a duplicate of the item below it

AccessRules: The host names or FQDNs in the certificate's Subject Alternative Name field.
CertificateDomains: The host names or FQDNs in the certificate's Subject Alternative Name field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50bd33ef-bb55-5dcc-2267-ea9551e8976e
* Version Independent ID: c4cfade2-6787-e167-9dd2-9ae6f6489ac4
* Content: [Get-ExchangeCertificate (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-exchangecertificate?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-ExchangeCertificate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-ExchangeCertificate.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DEWallen, yes. It looks like a copy/paste error. I fixed it.

Thanks for the feedback.

Closing
