### ISSUE TITLE
Connect-ExchangeOnline Erroring when using App-only auth and -DelegatedOrganization

### ISSUE THREAD

**Issue by gesbeckj** [MicrosoftDocs/office-docs-powershell#7109]
We are getting an error specifically when using app-only auth and specifying a delegated organization. Interactive auth works for both our tenancy and our delegated tenants. However, app-only auth only works for our tenancy. We are unable to use app-only auth to connect to our delegated clients. 

There is nothing in this document about this scenario being un-supported but it looks like there is a techcommunity that suggests it may be unsupported https://techcommunity.microsoft.com/t5/exchange-team-blog/modern-auth-and-unattended-scripts-in-exchange-online-powershell/ba-p/1497387/page/2

 Can this document be updated to accurately reflect if connecting using app-only auth and specifying a delegated organization should work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gesbeckj, I confirmed that delegation is (still) not supported. I added a note to the topic.

Thanks for the feedback.

Closing
