### ISSUE TITLE
Workspace value for Type parameter

### ISSUE THREAD

**Issue by gable44** [MicrosoftDocs/office-docs-powershell#7120]
The -Type parameter has **Workspace** value too but its probably limited to Exchange Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f835af-5905-368a-df68-6646782ad807
* Version Independent ID: 153ce2d2-dab5-9c8f-c511-ee3bc8ee2dbc
* Content: [Set-Mailbox (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gable44, confirmed. And the Workspace value is cloud-only; not available in Exchange 2019 or Exchange 2016. I added the value to the topic.

Thanks for the feedback.

Closing.
