### ISSUE TITLE
Wrong limitation "Cloud only" in description.

### ISSUE THREAD

**Issue by arodir** [MicrosoftDocs/office-docs-powershell#7121]
The following paragraph is quoted from the SourceFolder parameter description:
_"PurgedItems: (Cloud only) The Recoverable Items\Purges folder. This folder contains items that have been purged from the Recoverable Items folder (hard-deleted items)."_

The mentioned limitation "Cloud only" is incorrect as this also works in OnPremise Exchange 2019 environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21b1cd9d-df2e-d4d6-52e2-d3fbdfb9db9f
* Version Independent ID: e675173d-290a-dee0-62a4-5485cf3d2570
* Content: [Restore-RecoverableItems (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/restore-recoverableitems?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Restore-RecoverableItems.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Restore-RecoverableItems.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@arodir, confirmed. I updated Restore-RecoverableItems and also Get-RecoverableItems.

Thanks for the feedback.

Closing
