### ISSUE TITLE
Get-EXOMailbox fails with pipe and Select

### ISSUE THREAD

**Issue by tudorh** [MicrosoftDocs/office-docs-powershell#7128]
When running the command:
Get-EXOMailbox -Resultsize Unlimited | Select-Object -First 3

The results are returned but a terminal error is presented:

Get-EXOMailbox : The pipeline has been stopped.
At C:\Users\mikeb\Documents\Untitled1.ps1:3 char:2
+ Get-EXOMailbox -Resultsize Unlimited | Select-Object -First 3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ProtocolError: (:) [Get-EXOMailbox], PipelineStoppedException
+ FullyQualifiedErrorId : The pipeline has been stopped.,Microsoft.Exchange.Management.RestApiClient.GetExoMailbox`

This prevents a script from continuing to run.
If you run this same query using the traditional 'Get-Mailbox' command, no error is returned.

**Comment by dariomws** [comment]
@tudorh - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @tudorh Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
