### ISSUE TITLE
Graph or no Graph

### ISSUE THREAD

**Issue by warwickofthegh** [MicrosoftDocs/office-docs-powershell#7142]
Are we going with Get-PnPGraphAccessToken or Get-PnPAccessToken? both seem to work currently

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1ceca08-0508-204d-58bb-0dca368196a5
* Version Independent ID: 3135e575-fe8b-453d-0a70-2c32cc6e6044
* Content: [Get-PnPGraphAccessToken (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpgraphaccesstoken?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPGraphAccessToken.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPGraphAccessToken.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @warwickofthegh 

how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @warwickofthegh Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
