### ISSUE TITLE
New-ComplianceSearchAction does not run -export swtich

### ISSUE THREAD

**Issue by OrtacDemirel** [MicrosoftDocs/office-docs-powershell#7143]
hi,

In this article 
https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearchaction?view=exchange-ps
New-ComplianceSearchAction includes  Export  switch  for on-premises Exchange server 2016.

I get error
[PS] C:\Windows\system32>New-ComplianceSearchAction -SearchName "Project X" -Export
A parameter cannot be found that matches parameter name 'Export'.

I have mailbox import-export and search permissions and  can export email from ECP panel.

**Comment by dariomws** [comment]
Hi @OrtacDemirel, thank you for your feedback.

In the description of the parameter you can find:
"This parameter is available only in the cloud-based service.

This parameter requires the Export role in the Security & Compliance Center. By default, the Export role is assigned only to the eDiscovery Manager role group."

**Comment by OrtacDemirel** [comment]
> Hi @OrtacDemirel, thank you for your feedback.
> 
> In the description of the parameter you can find:
> "This parameter is available only in the cloud-based service.
> 
> This parameter requires the Export role in the Security & Compliance Center. By default, the Export role is assigned only to the eDiscovery Manager role group."

thank you. 

But at the beginning of this article:
https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearchaction?view=exchange-ps

It says  "This cmdlet is available in on-premises Exchange "

**Comment by dariomws** [comment]
Thank you again for your comment @OrtacDemirel.

The whole sentence states:
"This cmdlet is available in on-premises Exchange and in the cloud-based service. Some parameters and settings may be exclusive to one environment or the other."

**Comment by dariomws** [comment]
> In the description of the parameter you can find:
> "This parameter is available only in the cloud-based service.
> 
> This parameter requires the Export role in the Security & Compliance Center. By default, the Export role is assigned only to the eDiscovery Manager role group."

As the description states, the -Export switch/parameter is exclusive to the cloud service.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @OrtacDemirel Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
