### ISSUE TITLE
NullReferenceException calling connect-microsoftTeams using certificate authentication

### ISSUE THREAD

**Issue by BoBladm** [MicrosoftDocs/office-docs-powershell#7145]
When executing the lines below I  get a NullReferenceException.

I am using the 1.1.10-Preview version of the MicrosoftTeams powershell module, if I run Excactly the same using the 1.1.6 general release version it works fine.
I am trying the prerelease version to see if an other problem is solved in the prerelease version. (trying to to use new-csonlinesession in combination with the connect-microsoftteams using certificate #7154 )

$tenantID = 'MyownTenantname.onmicrosoft.com'

$appID = 'My-Correct-AppID'

Connect-MicrosoftTeams -CertificateThumbprint MyCertificateThumb -ApplicationId $appID -TenantId $tenantID
Connect-MicrosoftTeams : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-MicrosoftTeams -CertificateThumbprint MyCertificateThumb ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], NullReferenceException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams
 
Connect-MicrosoftTeams : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-MicrosoftTeams -CertificateThumbprint MyCertificateThumb ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MicrosoftTeams], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams

**Comment by get-itips** [comment]
Hello @BoBladm how are you? Hope you are doing good.

Here, we are limited to documentation issues. The best, in this case, would be to either open a support request or raise an idea [here](https://microsoftteams.uservoice.com/) so it reaches the team behind the development of the Teams PowerShell module, new versions of the module are constantly being released and I am pretty sure the team will welcome any feedback to improve it.

I hope this gets you in the right direction to answer your inquiry.

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @BoBladm Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
