### ISSUE TITLE
new-csonlinesession after connect-microsoftteams using certificate failing

### ISSUE THREAD

**Issue by BoBladm** [MicrosoftDocs/office-docs-powershell#7154]
Hi

We are trying to do some automated scripting towards Teams, but as we have a mandatory MFA requirement we are looking towards defining an app in azure ad giving permissions and the connect using certificate. That approach is working fine as long as it only involves Teams powershell commands. We do however have the need to run get-csonlineuser and move-csuser in order to manipulate the teams migration status of individual users. in order to do that I need to run the new-csonlinesession
From what I have been able to find it should be possible to do that without specifying any credentials, and it should then use the session from the connect-microsoftteams command.
If I do that i do however get the following error. Am i missing something or is this an error? Anyone hvae comments & Ideas?
I am using the MicrosoftTeams powershell module 1.1.6 I have tried to upgrade to the 1.1.10-preview version but that did break the connectmicrosof teams using certificate. (I wrote an other issue on that #7145)

$tenantID = 'MyTenant.onmicrosoft.com'

$appID = 'MyAppID'

Connect-MicrosoftTeams -CertificateThumbprint MyCertThumb -ApplicationId $appID -TenantId $tenantID

$session = New-CsOnlineSession 

Import-PSSession $session –AllowClobber

New-CsOnlineSession : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The WinRM client cannot process the request. The authentication mechanism requested by the client is not supported by the
 server or unencrypted traffic is disabled in the service configuration. Verify the unencrypted traffic setting in the service configuration or specify one of the authentication mechanisms supported by the server.  To use Kerberos, specify the computer nam
e as the remote destination. Also verify that the client computer and the destination computer are joined to a domain. To use Basic, specify the computer name as the remote destination, specify Basic authentication and provide user name and password. Possi
ble authentication mechanisms reported by server: For more information, see the about_Remote_Troubleshooting Help topic.
At C:\Users\MyPath\ConnectTeams_2.ps1:8 char:12
+ $session = New-CsOnlineSession
+            ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], PSRemotingTransportException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
 
New-CsOnlineSession : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The WinRM client cannot process the request. The authentication mechanism requested by the client is not supported by the
 server or unencrypted traffic is disabled in the service configuration. Verify the unencrypted traffic setting in the service configuration or specify one of the authentication mechanisms supported by the server.  To use Kerberos, specify the computer nam
e as the remote destination. Also verify that the client computer and the destination computer are joined to a domain. To use Basic, specify the computer name as the remote destination, specify Basic authentication and provide user name and password. Possi
ble authentication mechanisms reported by server: For more information, see the about_Remote_Troubleshooting Help topic.
At C:\Users\MyPath\ConnectTeams_2.ps1:8 char:12
+ $session = New-CsOnlineSession
+            ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-CsOnlineSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
 
Import-PSSession : Cannot validate argument on parameter 'Session'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At C:\Users\MyPath\ConnectTeams_2.ps1:10 char:18
+ Import-PSSession $session –AllowClobber
+                  ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Import-PSSession], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.ImportPSSessionCommand

**Comment by yogkumgit** [comment]
closing via 7145
