### ISSUE TITLE
Is there a way to retrieve email invites stored in a site FROM a user?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#7155]
This retrieves email invites stored in the ContosoWeb1 site to the user with email address someone@example.com
But is there a way to retrieve email invites stored in the ContosoWeb1 site FROM the user with email address someone@example.com?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4661450e-0e7f-619b-e820-0ba6acce4575
* Version Independent ID: 30fad058-46e5-acb0-bb9f-1d87d6f349d5
* Content: [Get-SPOSiteUserInvitations (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositeuserinvitations?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteUserInvitations.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteUserInvitations.md)
* Service: **sharepoint-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @hwkwicre how are you? Hope you are doing good.
AFAIK not that I am aware of, you can propose that to https://sharepoint.uservoice.com/
Thank you

**Comment by yogkumgit** [comment]
@hwkwicre Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
