### ISSUE TITLE
Missing command

### ISSUE THREAD

**Issue by badsector-82** [MicrosoftDocs/office-docs-powershell#7156]
Enable-Mailbox command is not imported. Only Enable-RemoteMailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b57b66-2364-0e9d-e627-5eeb77238675
* Version Independent ID: 78fd7932-06f9-37c7-8928-250b3884d89e
* Content: [Connect to Exchange servers using remote PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-servers-using-remote-powershell?redirectedfrom=MSDN&view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@badsector-82, the topic that's referenced in this issue doesn't mention either cmdlet.

The [Enable-Mailbox](https://docs.microsoft.com/powershell/module/exchange/enable-mailbox) topic describes the cmdlet as available in Exchange 2010 to Exchange 2019 and Exchange Online.

The [Enable-RemoteMailbox](https://docs.microsoft.com/powershell/module/exchange/enable-remotemailbox) topic describes the cmdlet as available in Exchange 2010 to Exchange 2019 (on-premises only).

I tried both cmdlets in remote PowerShell  (not Exchange Management Shell) connections to Exchange 2010 SP3 RU30, Exchange 2013 CU23, Exchange 2016 CU19, and Exchange 2019 CU8, and they were both available.

In a connection to Exchange Online PowerShell, Enable-Mailbox was available, but Enable-RemoteMailbox was not, just like the documentation says.

So what's the issue?

**Comment by badsector-82** [comment]
> So what's the issue?

The issue was that not all exchange commands were being imported. It turned out that are imported only commands that the account used for the connection has rights for. Which is logical and awesome but I found it the hard way. Also this could be used to test what commands each exchange role enables. In conjunction with Get-ManagementRole I was able to find the solution which requires least privilege rights for my needs. So sorry for bothering you, but it could probably be useful to mention that account dependency somewhere in the article.

**Comment by chrisda** [comment]
@badsector-82, interesting suggestion. I'm surprised that hasn't come up in all this time. I added a similar bullet to the What do you need to know before you begin? section of all Exchange-related PowerShell connection topics:

 - After you connect, the cmdlets and parameters that you have or don't have access to is controlled by role-based access control (RBAC). For more information, see [Exchange Server permissions](https://docs.microsoft.com/exchange/permissions/permissions).

**Comment by badsector-82** [comment]
Thank you and again sorry for the trouble!
