### ISSUE TITLE
Legacy Module

### ISSUE THREAD

**Issue by JBines** [MicrosoftDocs/office-docs-powershell#7163]
Install-Module SharePointPnPPowerShellOnline 

needs to be changed to:

Install-Module -Name PnP.PowerShell

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3240d3-6a7d-fc4b-62fd-d3a5375d8a4a
* Version Independent ID: 561212df-4dab-92b7-b634-57d53d313c6f
* Content: [PnP PowerShell Overview](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @JBines Joshua, how are you? Hope you are doing good.

Thanks for your feedback!

I was going to propose thru a pull request an update to this article however I could get information from the PnP community team and they are already working on a complete overhaul of the PnP documentation, including this article, so we can expect an update in the next couple of weeks. In the meantime, and you probably already know, you can get the documentation here https://github.com/PnP/PowerShell/.

Thank you and have a nice day!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @JBines Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
