### ISSUE TITLE
Get-Mailbox piped into Set-Mailbox or Set-CASMailbox does stupid things

### ISSUE THREAD

**Issue by mwl-aotc** [MicrosoftDocs/office-docs-powershell#7166]
Running a simple command to increase message size limits for existing accounts in our tenant (names anonymized)

```
> get-mailbox -ResultSize unlimited| set-mailbox -MaxReceiveSize 100MB -MaxSendSize 100MB
The operation couldn't be performed because 'John Doe' matches multiple entries.
    + CategoryInfo          : NotSpecified: (:) [Set-Mailbox], ManagementObjectAmbiguousException
    + FullyQualifiedErrorId : [Server=BY5PR09MB5332,RequestId=cbbeaf91-2c16-4ce9-a18f-e5beba273942,TimeStamp=1/26/2021 6:35:17 PM] [FailureCategory=Cmdlet-ManagementObj 
   ectAmbiguousException] E5DDAC9B,Microsoft.Exchange.Management.RecipientTasks.SetMailbox
    + PSComputerName        : outlook.office365.com
 
The operation couldn't be performed because 'Bob Smith' matches multiple entries.
    + CategoryInfo          : NotSpecified: (:) [Set-Mailbox], ManagementObjectAmbiguousException
    + FullyQualifiedErrorId : [Server=BY5PR09MB5332,RequestId=33ef9380-c2af-409e-bf5d-8426402500ae,TimeStamp=1/26/2021 6:39:16 PM] [FailureCategory=Cmdlet-ManagementObj 
   ectAmbiguousException] D6424067,Microsoft.Exchange.Management.RecipientTasks.SetMailbox
    + PSComputerName        : outlook.office365.com

This also occurs if a single account is selected by UPN:
> get-mailbox john.doe@jud.state.ma.us |set-mailbox -MaxReceiveSize 100MB -MaxSendSize 100MB
The operation couldn't be performed because 'John Doe' matches multiple entries.
    + CategoryInfo          : NotSpecified: (:) [Set-Mailbox], ManagementObjectAmbiguousException
    + FullyQualifiedErrorId : [Server=BY5PR09MB5332,RequestId=6c500fd0-cb2a-4544-9c67-76ff1f7455fe,TimeStamp=1/26/2021 8:05:00 PM] [FailureCategory=Cmdlet-ManagementObj 
   ectAmbiguousException] E5DDAC9B,Microsoft.Exchange.Management.RecipientTasks.SetMailbox
    + PSComputerName        : outlook.office365.com
```
 
Sure enough, in our tenant there are two users with the same DisplayName "John Doe", but all of the name-based globally unique attributes that are the only things that would make sense to use as a key are, in fact, unique:
```
> get-mailbox "John Doe" | select userprincipalname,displayname,name,id

UserPrincipalName            DisplayName     Name            Id               
-----------------            -----------     ----            --               
john.doe@jud.state.ma.us     John Doe        John Doe        John Doe  
john.w.doe@jud.state.ma.us   John Doe        John W Doe      John W Doe
```

It appears even on a piped-in object, set-mailbox and set-casmailbox are keying on DisplayName and trying to fetch their own copy of the object, rather than either simply using the piped object directly or keying off of something unique that would be sensible to use as a key.

**Comment by dariomws** [comment]
Hi @mwl-aotc, thank you for your feedback.

I test it on my lab, and it seems to be working:
![image](https://user-images.githubusercontent.com/33589238/106254257-4822f900-61f7-11eb-9a9e-75fe4806ddff.png)

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @mwl-aotc Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
