### ISSUE TITLE
Exchange Online - PowerShellV2+Unattended: Get-PublicFolder fails

### ISSUE THREAD

**Issue by pmaItelio** [MicrosoftDocs/office-docs-powershell#7169]
Hi, 
I try to implement a powershell script, that gathers EXO information like Mailboxes and PublicFolders.
First attempt was to connect via BasicAuth but as there are some downsides for unattended sessions, so we decided to use an App/Certificate combination.

Everything works fine, but the PublicFolders - incase the certificate is used.
If I use the "old" web based BasicAuth, everything works as expected.

It seems that some internal mapping is missing (Get-Publicfolder to internal Mailbox), incase using a certificate.

Permissions should be fine:
I set 'Global Reader' as role member and later I also tried 'Company Adminsistrator'

Required resource access:
    - 'Exchange.ManageAsApp'
	- 'Calendars.Read.All'
	- 'Mail.Read.All'
	- 'Contacts.Read.All'
	- 'Contacts.Read'
	- 'MailboxSettings.Read.All'
	- 'MailboxSettings.Read'
	- 'Place.Read.All'
	- 'full_access_as_app'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@pmaItelio, I encourage you to open a support case about this. Exchange.ManageAsApp should be the only permission you need.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for the sharing this explanation. @pmaItelio Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
