### ISSUE TITLE
New-CsBatchPolicyAssignmentOperation missing parameters

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#7170]
there are two issues with this article:

1. lots of parameters are missing in SYNTAX section. 

it should be `New-CsBatchPolicyAssignmentOperation [-OperationName <String>] -Identity <String[]> -PolicyType <String> [-AdditionalParameters <Hashtable>] [-PolicyName <String>] [-Break] [-HttpPipelineAppend <SendAsyncStep[]>] [-HttpPipelinePrepend <SendAsyncStep[]>] [-Proxy <Uri>] [-ProxyCredential <PSCredential>] [-ProxyUseDefaultCredentials] [-WhatIf] [-Confirm] [<CommonParameters>]`

2. For some strange reason, the content web-page [https://docs.microsoft.com/en-us/powershell/module/teams/new-csbatchpolicyassignmentoperation](https://docs.microsoft.com/en-us/powershell/module/teams/new-csbatchpolicyassignmentoperation) does not show sections "PARAMETERS" and "INPUTS" from the Content Source `New-CsBatchPolicyAssignmentOperation.md` file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b185b8d0-fa84-7ea6-4531-cf4eb6cc26fd
* Version Independent ID: 24754aee-bff2-fa16-e7e6-af45362fd916
* Content: [New-CsBatchPolicyAssignmentOperation (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csbatchpolicyassignmentoperation?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsBatchPolicyAssignmentOperation.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks @shivtorov for raising this, will add missing parameters, about 2.: I've been fixing a markdown formatting error that causes bad rendering of the article, will try to fix it on this pr. Thanks again

**Comment by shivtorov** [comment]
@get-itips , thanks for looking into that.
Article `Get-CsBatchPolicyAssignmentOperation` missing the same parameters
