### ISSUE TITLE
Get-Team - missing parameter description NumberOfThreads

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#7181]
Parameter `NumberOfThreads` is not listed in the article

MicrosoftTeams module version 1.1.6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38da792-01bc-28ad-7727-794075e150c9
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Thanks @shivtorov , adding it.
