### ISSUE TITLE
Remove-CsGroupPolicyAssignment missing parameters

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#7183]
Missing parameters:

- Break
- HttpPipelineAppend
- HttpPipelinePrepend
- Proxy
- ProxyCredential
- ProxyUseDefaultCredentials
- WhatIf
- Confirm
- PassThru

MicrosoftTeams module version 1.1.6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 895fefaa-b36e-4e93-3d31-d728dd226957
* Version Independent ID: fe242340-e31d-1d57-c851-f093dddc4b4c
* Content: [Remove-CsGroupPolicyAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/remove-csgrouppolicyassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Remove-CsGroupPolicyAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Remove-CsGroupPolicyAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks @shivtorov
