### ISSUE TITLE
New-CsGroupPolicyAssignment missing parameters

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#7184]
Missing parameters:

- Break
- HttpPipelineAppend
- HttpPipelinePrepend
- Proxy
- ProxyCredential
- ProxyUseDefaultCredentials
- WhatIf
- Confirm
- PassThru

MicrosoftTeams module version 1.1.6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c9ed10e-cc6a-67d3-cd50-6c537dbcdf42
* Version Independent ID: dabb388b-8614-4b69-4e0a-f0536ab2bab6
* Content: [New-CsGroupPolicyAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csgrouppolicyassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-CsGroupPolicyAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsGroupPolicyAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks again @shivtorov
