### ISSUE TITLE
Get-CsUserPolicyAssignment missing parameters

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#7185]
Missing parameters:

- InputObject
- Break
- HttpPipelineAppend
- HttpPipelinePrepend
- Proxy
- ProxyCredential
- ProxyUseDefaultCredentials

MicrosoftTeams module version 1.1.6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3898f54-71f3-44c6-8412-c3eeee517aa7
* Version Independent ID: 8ea324f5-a833-f877-3888-a8a703bebd97
* Content: [Get-CsUserPolicyAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-csuserpolicyassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-CsUserPolicyAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-CsUserPolicyAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks @shivtorov
