### ISSUE TITLE
Undocumented Skype/Teams cmdlets

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#7186]
It looks like the following cmdlets are not documented.

- Get-CsCloudCallDataConnection
- Get-CsDefaultCatalogApp
- Get-CsGlobalCatalogApp
- Get-CsInboundExemptNumberPattern
- Get-CsOnlineAudioConferencingRoutingPolicy
- Get-CsTeamsAppPreset
- Get-CsTeamsMigrationConfiguration
- Get-CsTeamsNetworkRoamingPolicy
- Get-CsTeamsNotificationAndFeedsPolicy
- Get-CsTeamsPinnedApp
- Get-CsTeamsShiftsAppPolicy
- Get-CsTeamsShiftsPolicy
- Get-CsTeamsSurvivableBranchAppliance
- Get-CsTeamsSurvivableBranchAppliancePolicy
- Get-CsTeamsTargetingPolicy
- Get-CsTeamsUpdateManagementPolicy
- Get-CsTeamsVdiPolicy
- Get-CsTeamsVerticalPackagePolicy
- Get-CsTenantCatalogApp
- Get-CsTenantNetworkConfiguration
- Get-CsTenantNetworkPostalCode
- Grant-CsOnlineAudioConferencingRoutingPolicy
- Grant-CsPolicy
- Grant-CsTeamsShiftsPolicy
- Grant-CsTeamsSurvivableBranchAppliancePolicy
- Grant-CsTeamsUpdateManagementPolicy
- Grant-CsTeamsVdiPolicy
- Grant-CsTeamsVerticalPackagePolicy
- Invoke-CsUserPreferredDataLocationSync
- New-CsCloudCallDataConnection
- New-CsDefaultCatalogApp
- New-CsGlobalCatalogApp
- New-CsHybridTelephoneNumber
- New-CsInboundExemptNumberPattern
- New-CsOnlineAudioConferencingRoutingPolicy
- New-CsTeamsAppPreset
- New-CsTeamsCallingPolicy
- New-CsTeamsNetworkRoamingPolicy
- New-CsTeamsShiftsPolicy
- New-CsTeamsSurvivableBranchAppliance
- New-CsTeamsSurvivableBranchAppliancePolicy
- New-CsTeamsUpdateManagementPolicy
- New-CsTeamsVdiPolicy
- New-CsTenantCatalogApp
- New-CsTenantNetworkPostalCode
- Remove-CsDefaultCatalogApp
- Remove-CsGlobalCatalogApp
- Remove-CsHybridTelephoneNumber
- Remove-CsInboundExemptNumberPattern
- Remove-CsOnlineAudioConferencingRoutingPolicy
- Remove-CsTeamsAppPreset
- Remove-CsTeamsCallingPolicy
- Remove-CsTeamsNetworkRoamingPolicy
- Remove-CsTeamsNotificationAndFeedsPolicy
- Remove-CsTeamsShiftsPolicy
- Remove-CsTeamsSurvivableBranchAppliance
- Remove-CsTeamsSurvivableBranchAppliancePolicy
- Remove-CsTeamsTargetingPolicy
- Remove-CsTeamsUpdateManagementPolicy
- Remove-CsTeamsVdiPolicy
- Remove-CsTenantCatalogApp
- Remove-CsTenantNetworkConfiguration
- Remove-CsTenantNetworkPostalCode
- Set-CsDefaultCatalogApp
- Set-CsGlobalCatalogApp
- Set-CsInboundExemptNumberPattern
- Set-CsOnlineAudioConferencingRoutingPolicy
- Set-CsTeamsAppPreset
- Set-CsTeamsMigrationConfiguration
- Set-CsTeamsNetworkRoamingPolicy
- Set-CsTeamsNotificationAndFeedsPolicy
- Set-CsTeamsShiftsAppPolicy
- Set-CsTeamsShiftsPolicy
- Set-CsTeamsSurvivableBranchAppliance
- Set-CsTeamsSurvivableBranchAppliancePolicy
- Set-CsTeamsTargetingPolicy
- Set-CsTeamsUpdateManagementPolicy
- Set-CsTeamsUpgradeStatus
- Set-CsTeamsVdiPolicy
- Set-CsTenantCatalogApp
- Set-CsTenantNetworkConfiguration
- Set-CsTenantNetworkPostalCode
- Switch-CsOnlineApplicationEndpoint

MicrosoftTeams module version **1.1.6**

**Comment by get-itips** [comment]
Hello @shivtorov thanks for reporting, will look into this.

**Comment by get-itips** [comment]
(Please ignore the related PR, made a typo)

**Comment by vincentkurmi** [comment]
My issue below is covered by this one.
https://github.com/MicrosoftDocs/office-docs-powershell/issues/7397

**Comment by Atreidae** [comment]
Hi team,
This issue has been open since Jan and we still don't have much in the way of documentation on the SBA cmdlets. 
Especially as the SBA process itself is sparsely documented and the PowerShell module is also missing documentation.

![image](https://user-images.githubusercontent.com/8736291/131928511-b7447929-fb30-4780-9cd0-eaf26c400834.png)


Little hard to recommend the solution to customers when we don't know how it works. :/

Can we get an update on these please?

**Comment by ykuijs** [comment]
Any update on this issue?

**Comment by yogkumgit** [comment]
@JensTrier and @get-itips Kindly address this issue. Thanks

**Comment by JensTrier** [comment]
This more than a year old and TPM is now at 4.3.0. Spot-checking I can see that some of these cmdlets have been documented. Someone needs to do the exercise again against current situation and see what is left.

**Comment by shivtorov** [comment]
@JensTrier, I'm the person who opened this GitHub issue initially a year ago.

As of 2022-05-24 (24 May 2022), the following Microsoft Teams 4.3.0 articles are missing:

| CommandType | Name                                          | Version | Source         |
| ----------- | --------------------------------------------- | ------- | -------------- |
| Function    | Get-CsCloudCallDataConnection                 | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsDefaultCatalogApp                       | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsGlobalCatalogApp                        | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineAudioConferencingRoutingPolicy    | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlinePowerShellEndpoint                | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTeamsAppPreset                          | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTeamsFilesPolicy                        | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTeamsMigrationConfiguration             | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTeamsNotificationAndFeedsPolicy         | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTeamsPinnedApp                          | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTeamsShiftsAppPolicy                    | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTeamsSurvivableBranchAppliance          | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTeamsSurvivableBranchAppliancePolicy    | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTeamsTargetingPolicy                    | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTeamsUpdateManagementPolicy             | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTeamsVdiPolicy                          | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTeamsWorkLoadPolicy                     | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTenantCatalogApp                        | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsTenantNetworkConfiguration              | 4.3.0   | MicrosoftTeams |
| Function    | Grant-CsOnlineAudioConferencingRoutingPolicy  | 4.3.0   | MicrosoftTeams |
| Function    | Grant-CsPolicy                                | 4.3.0   | MicrosoftTeams |
| Function    | Grant-CsTeamsFilesPolicy                      | 4.3.0   | MicrosoftTeams |
| Function    | Grant-CsTeamsSurvivableBranchAppliancePolicy  | 4.3.0   | MicrosoftTeams |
| Function    | Grant-CsTeamsUpdateManagementPolicy           | 4.3.0   | MicrosoftTeams |
| Function    | Grant-CsTeamsVdiPolicy                        | 4.3.0   | MicrosoftTeams |
| Function    | Grant-CsTeamsWorkLoadPolicy                   | 4.3.0   | MicrosoftTeams |
| Function    | Invoke-CsInternalPsTelemetry                  | 4.3.0   | MicrosoftTeams |
| Function    | Invoke-CsUserPreferredDataLocationSync        | 4.3.0   | MicrosoftTeams |
| Function    | Move-CsInternalHelper                         | 4.3.0   | MicrosoftTeams |
| Function    | New-CsCloudCallDataConnection                 | 4.3.0   | MicrosoftTeams |
| Function    | New-CsDefaultCatalogApp                       | 4.3.0   | MicrosoftTeams |
| Function    | New-CsGlobalCatalogApp                        | 4.3.0   | MicrosoftTeams |
| Function    | New-CsHybridTelephoneNumber                   | 4.3.0   | MicrosoftTeams |
| Function    | New-CsOnlineAudioConferencingRoutingPolicy    | 4.3.0   | MicrosoftTeams |
| Function    | New-CsTeamsAppPreset                          | 4.3.0   | MicrosoftTeams |
| Function    | New-CsTeamsFilesPolicy                        | 4.3.0   | MicrosoftTeams |
| Function    | New-CsTeamsSurvivableBranchAppliance          | 4.3.0   | MicrosoftTeams |
| Function    | New-CsTeamsSurvivableBranchAppliancePolicy    | 4.3.0   | MicrosoftTeams |
| Function    | New-CsTeamsUpdateManagementPolicy             | 4.3.0   | MicrosoftTeams |
| Function    | New-CsTeamsVdiPolicy                          | 4.3.0   | MicrosoftTeams |
| Function    | New-CsTeamsWorkLoadPolicy                     | 4.3.0   | MicrosoftTeams |
| Function    | New-CsTenantCatalogApp                        | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsDefaultCatalogApp                    | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsGlobalCatalogApp                     | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsHybridTelephoneNumber                | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsOnlineAudioConferencingRoutingPolicy | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsTeamsAppPreset                       | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsTeamsFilesPolicy                     | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsTeamsNotificationAndFeedsPolicy      | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsTeamsSurvivableBranchAppliance       | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsTeamsSurvivableBranchAppliancePolicy | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsTeamsTargetingPolicy                 | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsTeamsUpdateManagementPolicy          | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsTeamsVdiPolicy                       | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsTeamsWorkLoadPolicy                  | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsTenantCatalogApp                     | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsDefaultCatalogApp                       | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsGlobalCatalogApp                        | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsInternalOnlinePowerShellEndpoint        | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsOnlineAudioConferencingRoutingPolicy    | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsAppPreset                          | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsFilesPolicy                        | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsMigrationConfiguration             | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsNotificationAndFeedsPolicy         | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsShiftsAppPolicy                    | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsSurvivableBranchAppliance          | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsSurvivableBranchAppliancePolicy    | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsTargetingPolicy                    | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsUpdateManagementPolicy             | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsUpgradeStatus                      | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsVdiPolicy                          | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsWorkLoadPolicy                     | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTenantCatalogApp                        | 4.3.0   | MicrosoftTeams |
| Function    | Switch-CsOnlineApplicationEndpoint            | 4.3.0   | MicrosoftTeams |
| Cmdlet      | Get-MultiGeoRegion                            | 4.3.0   | MicrosoftTeams |
| Cmdlet      | Get-Operation                                 | 4.3.0   | MicrosoftTeams |

**Comment by pbafna03** [comment]
Hi @shivtorov, 

Thanks for the updated list, I don't think we need separate issues to be created. Just probably need to refine it more. 

I believe a bunch of these are either deprecated or not supported and will be removed from Teams PowerShell Module as well soon. So those we can ignore. The recent list of those at https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-supported-versions#deprecated-cmdlets. 

Any leftovers need to be actioned.

**Comment by shivtorov** [comment]
Hi @pbafna03,

Thanks for pointing out that according to https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-supported-versions#deprecated-cmdlets the following cmdlets are deprecated (see the table below).

However, I would like to highlight that none of the "deprecated" cmdlets are listed in the above message.
Thus, the whole list above should be considered as "leftovers" that "need to be actioned."

**List of deprecated cmdlets:**

| CommandType | Name                                               | Version | Source         |
| ----------- | -------------------------------------------------- | ------- | -------------- |
| Function    | Clear-CsOnlineTelephoneNumberReservation           | 4.3.0   | MicrosoftTeams |
| Function    | Disable-CsOnlineDialInConferencingUser             | 4.3.0   | MicrosoftTeams |
| Function    | Enable-CsOnlineDialInConferencingUser              | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineApplicationEndpoint                    | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineDialInConferencingUserInfo             | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineDialInConferencingUserState            | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineDirectoryTenant                        | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineDirectoryTenantNumberCities            | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineTelephoneNumber                        | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineTelephoneNumberAvailableCount          | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineTelephoneNumberInventoryAreas          | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineTelephoneNumberInventoryCities         | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineTelephoneNumberInventoryCountries      | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineTelephoneNumberInventoryRegions        | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineTelephoneNumberInventoryTypes          | 4.3.0   | MicrosoftTeams |
| Function    | Get-CsOnlineTelephoneNumberReservationsInformation | 4.3.0   | MicrosoftTeams |
| Function    | New-CsOnlineApplicationEndpoint                    | 4.3.0   | MicrosoftTeams |
| Function    | New-CsOnlineAudioFile                              | 4.3.0   | MicrosoftTeams |
| Function    | New-CsTeamsAppPermissionPolicy                     | 4.3.0   | MicrosoftTeams |
| Function    | New-CsTeamsAppSetupPolicy                          | 4.3.0   | MicrosoftTeams |
| Function    | Remove-CsOnlineApplicationEndpoint                 | 4.3.0   | MicrosoftTeams |
| Function    | Search-CsOnlineTelephoneNumberInventory            | 4.3.0   | MicrosoftTeams |
| Function    | Select-CsOnlineTelephoneNumberInventory            | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsOnlineApplicationEndpoint                    | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsAppPermissionPolicy                     | 4.3.0   | MicrosoftTeams |
| Function    | Set-CsTeamsAppSetupPolicy                          | 4.3.0   | MicrosoftTeams |
| Function    | Test-CsOnlineLisCivicAddress                       | 4.3.0   | MicrosoftTeams |

CC: @get-itips, @JensTrier, @yogkumgit

**Comment by pbafna03** [comment]
@shivtorov - thanks, we can remove the non-supported ones as well. They are also going away for e.g. Get-CsTenantCatalogApp

**Comment by mababode** [comment]
seeing the following documented soon is appreciated:
Get-/Set-/New-/Grant-CsTeamsUpdateManagementPolicy

**Comment by yogkumgit** [comment]
@pbafna03 Please comment. Thanks

**Comment by shivtorov** [comment]
> Following are deprecated/not supported
> 
> * Invoke-CsUserPreferredDataLocationSync
> * Switch-CsOnlineApplicationEndpoint
> * Grant-CsPolicy

@pbafna03 , do you want to publish this list to https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-supported-versions#deprecated-cmdlets

**Comment by pbafna03** [comment]
> > Following are deprecated/not supported
> > 
> > * Invoke-CsUserPreferredDataLocationSync
> > * Switch-CsOnlineApplicationEndpoint
> > * Grant-CsPolicy
> 
> @pbafna03 , do you want to publish this list to https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-supported-versions#deprecated-cmdlets

Done!

**Comment by yogkumgit** [comment]
@get-itips and @pbafna03 Thank you very much. @shivtorov Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
