### ISSUE TITLE
Set-CsTeamsCallingPolicy - missing params

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#7187]
Missing description for parameters:

- AllowTranscriptionForCalling
- Description
- LiveCaptionsEnabledTypeForCalling
- SpamFilteringEnabledType

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8fa7e55-c3b1-7b37-f395-736ec82868a0
* Version Independent ID: 4630697b-375e-85f2-25b1-b944bc6dad5f
* Content: [Set-CsTeamsCallingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @shivtorov thanks for reporting!
