### ISSUE TITLE
New/Set-CsTeamsMeetingPolicy params

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#7188]
Missing description of parameters:

- AllowMeetingRegistration
- AllowRecordingStorageOutsideRegion
- AllowScreenContentDigitization
- AllowTrackingInReport
- LiveCaptionsEnabledType
- RecordingStorageMode
- RoomAttributeUserOverride
- SpeakerAttributionMode
- WhoCanRegister

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01163bb5-1bea-54e9-4592-bf19256f2101
* Version Independent ID: 7a7a44a1-e01e-da96-d1a0-a876487dcb4c
* Content: [New-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for reporting!

**Comment by Kateyanne** [comment]
Reopened per Michelle Nappa 'SpeakerAttributionMode parameter is still missing a description. It just lists the possible values'

**Comment by ParaGlideRocks** [comment]
Hi Team,
please add a brief description to parameters that are not intended for internal purposes and not just which values they can assume.

**Comment by yogkumgit** [comment]
@get-itips

**Comment by JohanssonMarkus** [comment]
Come on, it can't take several month to update this :(

**Comment by JohanssonMarkus** [comment]
Another thing is for the AllowMeetingRegistration it mention values to set are Everyone/EveryoneInCompany
![image](https://user-images.githubusercontent.com/32453241/117423265-d3abd480-af20-11eb-86b2-3fb0ac7a3ac4.png)

But I think it should be True/False? Please correct and add a description as well what this controll?
![image](https://user-images.githubusercontent.com/32453241/117423375-f3db9380-af20-11eb-825a-699fbd14a578.png)

**Comment by Petri-X** [comment]
Would be nice to know how your team is planned to work with the documentation? Is it only when someone is complaining, the documentation is fixed? At the moment there following parameters without any comment for new-csteamsmeetingpolicy:

- AllowCarbonSummary
- AllowMeetingCoach
- AllowMeetingRegistration
- AllowTrackingInReport
- AllowUserToJoinExternalMeeting
- LiveStreamingMode
- MeetingInviteLanguage1
- MeetingInviteLanguage2
- MeetingRecordingExpirationDays
- RoomPeopleNameUserOverride
- SpeakerAttributionMode

So these are PS module 2.3.1. I haven't take a look to preview modules at all. So in that sense it is expected to have documentation ready.

The other thing is more general. When looking for the first lines on your pages, quite many are still referring to:
Module: SkypeForBusiness
Applies to: Skype for Business Online
But we speak about the Teams PS module.
