### ISSUE TITLE
Set-CsTeamsMeetingConfiguration params

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#7189]
Missing description of parameter **DisableAppInteractionForAnonymousUsers**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2996298d-f48d-345e-6344-00c8c20a864c
* Version Independent ID: 6a2286fc-2924-8223-35c5-f16e6786ff45
* Content: [Set-CsTeamsMeetingConfiguration (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for reporting @shivtorov
