### ISSUE TITLE
Get-DlpComplianceRule - Weird condition group hierarchy

### ISSUE THREAD

**Issue by arnauvc** [MicrosoftDocs/office-docs-powershell#7190]
Hi, I'm trying to script a sort of backup of the policies and rules for Endpoint DLP, but when I was trying to get information about the different condition groups and Sensitive Info Types inside the rules I got a weird behaviour.

If the condition group has a custom name, like this one:
![image](https://user-images.githubusercontent.com/5579758/106282944-9230cc80-6241-11eb-9b98-36992cd6cccd.png)

The output from the PS cmdlet shows like this:
`(Get-DlpComplianceRule -Identity "TEST_DATOS_PERSONALES_HIGH").ContentContainsSensitiveInformation`

![image](https://user-images.githubusercontent.com/5579758/106283663-7e399a80-6242-11eb-894c-fd0fb28232ac.png)
Where you can see the collection of groups (and acces them) and the operator. Which it's what I would expect.

But if the condition group has the default name, like this:
![image](https://user-images.githubusercontent.com/5579758/106283819-b04afc80-6242-11eb-8076-c84359f67733.png)

Then the output of the same cmdlet changes:
![image](https://user-images.githubusercontent.com/5579758/106285032-43386680-6244-11eb-99aa-181667e86d28.png)
It shows directly the content of the condition group, without having a way to acces its name or operator, which of course it's not the expected output.

I've been able to reproduce this issue on different policies and the same behaviour happens.

Information:

```
ModuleType Version    Name                                ExportedCommands                                                                                                                                                     
---------- -------    ----                                ----------------                                                                                                                                                     
Script     0.0        EXOPSSession                        {Connect-EXOPSSession, Connect-IPPSSession, Get-OrgNameFromUPN, Test-Uri}
```
```
Get-Host | Select-Object Version # Powershell Version

Version       
-------       
5.1.14409.1005
```

```
Windows 10 Enterprise 1909
OsBuild: 18363.1316

**Comment by dariomws** [comment]
@arnauvc - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @arnauvc Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
