### ISSUE TITLE
New-CsOnlineAudioFile returns empty ID

### ISSUE THREAD

**Issue by BohrenAn** [MicrosoftDocs/office-docs-powershell#7196]
Hi All,
When i try to Upload an Audiofile with New-CsOnlineAudioFile i get a return with an empty id. I think there is something wrong here.

PS C:\> Import-Module MicrosoftTeams
PS C:\> $sfbSession = New-CsOnlineSession -OverrideAdminDomain icewolfch.onmicrosoft.com
PS C:\> Import-PSSession $sfbSession 

PS C:\> #Upload Audio File New-CsOnlineAudioFile
PS C:\> $content = Get-Content "E:\Temp\CallQueueDemo02.mp3" -Encoding byte -ReadCount 0
PS C:\> $audioFile = New-CsOnlineAudioFile -FileName "CallQueueDemo02.mp3" -Content $content -Tenant "46bbad84-29f0-4e03-8d34-f6841a5071ad"
PS C:\> $audioFile
Id            :
FileName      : CallQueueDemo02.mp3
ApplicationId :

With the Import-CsOnlineAudioFile it works. 
PS C:\> #Upload Audio File Import-CsOnlineAudioFile
PS C:\> $content = Get-Content "E:\Temp\CallQueueDemo02.mp3" -Encoding byte -ReadCount 0
PS C:\> $audioFile = Import-CsOnlineAudioFile -ApplicationId "HuntGroup" -FileName "CallQueueDemo02.mp3" -Content $content
PS C:\> $audioFile
Id            : d902b622f6da4d43b2ed7a0013ad72a5
FileName      : CallQueueDemo02.mp3
ApplicationId : HuntGroup

Regards
Andres

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb13f13-b5c1-bb36-9f73-49f1acf5f197
* Version Independent ID: 81058714-af07-7c3a-be46-bebeec57cbbb
* Content: [New-CsOnlineAudioFile (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlineaudiofile?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineAudioFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineAudioFile.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by DEberhardt** [comment]
yep. I fell into that as well :)

`New-CsOnlineAudioFile` _creates_ a new file. If you want to upload one, you need to use `Import-CsOnlineAudioFile`
I never managed to get anything from `New`, but I have made [`Import-TeamsAudioFile`](https://github.com/DEberhardt/TeamsFunctions/blob/main/docs/Import-TeamsAudioFile.md) from it, simplifying its use :)

**Comment by BohrenAn** [comment]
As you look into this. The Maximum File Size that can be uploaded is less than 1 MB (around 850 KB) and via the GUI you can upload an Audio File with 5MB. That should be the same Size

Regards
Andres

**Comment by BohrenAn** [comment]
I propose to change the Example, so it's more clear what's its purpose

#Create AudioFile Object
$content = Get-Content ""C:\Media\Welcome.wav" -Encoding byte -ReadCount 0
$AudioFile = New-CsOnlineAudioFile -FileName "Welcome.wav" -Content $content 

#Upload Audio File 
$Upload = Import-CsOnlineAudioFile -ApplicationId "HuntGroup" -FileName $AudioFile.FileName -Content $AudioFile.Content

**Comment by DEberhardt** [comment]
This works just as well:
```
$File = "C:\temp\Welcome.wav"
$FileName = Split-Path $File -Leaf
$content = Get-Content $File -Encoding byte -ReadCount 0
$Upload = Import-CsOnlineAudioFile -ApplicationId "HuntGroup" -FileName $FileName -Content $content
```
You don't necesarily need New-CsOnlineAudioFile

**Comment by BohrenAn** [comment]
@DEberhardt 

Yes, NOW i know that you don't explicitly need New-CsOnlineAudioFile. But i have talked with several Collegues and they all didn't understand why "New-CsOnlineAudioFile" exists.
And i believe the Example in the Documentation for New-CsOnlineAudioFile is not very helpful. 
IMHO: With my Proposal it would be much more understandable.

Regards
Andres

**Comment by get-itips** [comment]
Hello @BohrenAn Andres and @DEberhardt David, I hope you are doing good.

The description for `New-CsOnlineAudioFile` has the clue:

> The New-CsOnlineAudioFile cmdlet creates a new audio file for use with the **Organizational Auto Attendant (OAA) service**.

Organizational Auto Attendants were the first introduced generation of AA.

Not so long ago if you tried to use `-CsOrganizationalAutoAttendant` cmdlets, an error would be thrown with something like this

> First generation provisioning is no longer supported. Please use the cmdlets which follow this format “*-CsAutoAttendant*” instead.

The cmdlets `-CsOrganizationalAutoAttendant` were removed recently. And maybe `New-CsOnlineAudioFile` will follow.

What I will propose is to add a sentence to use `Import-CsOnlineAudioFile` instead.

Thank you all
