### ISSUE TITLE
Retired and archived.

### ISSUE THREAD

**Issue by DanielWahlgren** [MicrosoftDocs/office-docs-powershell#7197]
Please update this documentation to reflect the transfer from SharePointPnPPowerShellOnline to pnp.powershell.
https://github.com/pnp/PnP-PowerShell -> https://github.com/pnp/powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3240d3-6a7d-fc4b-62fd-d3a5375d8a4a
* Version Independent ID: 561212df-4dab-92b7-b634-57d53d313c6f
* Content: [PnP PowerShell Overview](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @DanielWahlgren Daniel, how are you?
Please, see https://github.com/MicrosoftDocs/office-docs-powershell/issues/7163#issuecomment-769354071
@yogkumgit please close, thanks
