### ISSUE TITLE
Opening line needs a spell check

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/office-docs-powershell#7198]
"Get's the built-in maping files" should be "Gets the built-in mapping files"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddaacf4a-8cc6-252c-03a8-b1c202522d99
* Version Independent ID: f3200d8c-d12c-84ec-f18a-7124618aea9a
* Content: [Export-PnPClientSidePageMapping (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/export-pnpclientsidepagemapping?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Export-PnPClientSidePageMapping.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Export-PnPClientSidePageMapping.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @joshtransient Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by joshtransient** [comment]
Cool. As always, I pressed the "Submit and view feedback for this page" button, and this is the second or third time someone has posted this caveat. I'm gonna continue to submit fixes like this until that button doesn't exist, or until the button goes where it needs to.
