### ISSUE TITLE
As the new Image column type release, how pnp powershell updates value for this column

### ISSUE THREAD

**Issue by UnaZheng15** [MicrosoftDocs/office-docs-powershell#7205]
hi,

As the new Image column type release, but the pnp powershell seems not supports it, we have not found any way to add value for this column type. Could you help share the command or anyway to update it. 
![image](https://user-images.githubusercontent.com/60872157/106701666-fc6eb600-6621-11eb-9ab0-e5f618231997.png)

Thanks in advance.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb227d8-a123-5ecf-4329-60b287f48013
* Version Independent ID: a1969a78-7325-8946-c27f-8320b7bbed75
* Content: [Add-PnPListItem (SharePointPnPPowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPListItem.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @UnaZheng15 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @UnaZheng15 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
