### ISSUE TITLE
To update the Group logo from a file placed in SP Site

### ISSUE THREAD

**Issue by yahookevin** [MicrosoftDocs/office-docs-powershell#7206]
I'm trying to update a Team site logo from a image file placed in the same site.
Is this possible via Set-PnPUnifiedGroup?
I've tried something like this-
Set-PnPUnifiedGroup -Identity $group -GroupLogoPath "https://***sharepoint.com/sites/ProjectSite/SiteAssets/GreenBlock.JPG"

**Comment by get-itips** [comment]
Hello @yahookevin Kevin, how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your issue with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @yahookevin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
