### ISSUE TITLE
LinkType "EventSubscribers" is not supported

### ISSUE THREAD

**Issue by spplante** [MicrosoftDocs/office-docs-powershell#7207]
When specifying the linktype option **EventSubscribers** while running the **Get-UnifiedGroupLinks** command, the command returns "Invalid value for LinkType parameter."

This should be available in order to get members with the option "Receive only replies to you and group events" checked for a specific group, but now since the only supported linktype is **Subscribers** I can only get the members with the option "Receive all emails and events" checked...

The documentation needs to be updated or the PowerShell command fixed, thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a66e3b7-94f5-f1f1-3b95-4fd8337b15b3
* Version Independent ID: c849c0a5-96f0-fd15-2991-b75b02169424
* Content: [Get-UnifiedGroupLinks (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-unifiedgrouplinks?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-UnifiedGroupLinks.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-UnifiedGroupLinks.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@spplante, I confirmed that the value EventSubscribers is shown as a valid value for the LinkType parameter in the error message when you enter an unsupported value:

 ```powershell
PS C:\Users\chrisda> Get-UnifiedGroupLinks -Identity demoone -LinkType oienfoiwn
Cannot process argument transformation on parameter 'LinkType'. Cannot convert value "oienfoiwn" to type
"Microsoft.Exchange.Management.RecipientTasks.LinkType". Error: "Unable to match the identifier name oienfoiwn to a
valid enumerator name. Specify one of the following enumerator names and try again:
Members, Owners, Subscribers, Aggregators, EventSubscribers"
    + CategoryInfo          : InvalidData: (:) [Get-UnifiedGroupLinks], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-UnifiedGroupLinks
    + PSComputerName        : outlook.office365.com
```

Yet as you described, when you try to use the value EventSubscribers, you get the `Invalid value for LinkType parameter.` error.

I updated the topic (and the Add-UnifiedGroupLinks and Remove-UnifiedGroupLinks topics).

I highly encourage you to open a support case about this. Meanwhile, I'll send this issue to some feature owners to see what they say.

**Comment by spplante** [comment]
My question right now is how am I supposed to get members that are only subscribed to calendar events (not subscribers) if PowerShell does not support EventSubscribers and documentation just needs to be updated?

Is there any other way all at to get this? All I am trying to do is retrofit all Teams on my tenant with **AlwaysSubscribeMembersToCalendarEvents** set to **false**, but since that settings doesn't affect existing members that are already subscribed I want to detect them and remove them also.

**Comment by chrisda** [comment]
@spplante, seeking clarification. Meanwhile, your best course of action is to open a support case and ask that exact same question.

**Comment by chrisda** [comment]
Documentation as been updated to remove EventSubscribers. @spplante, feel free to report back here with the results of your support case if we need to further update documentation.

Thanks for the feedback.

Closing
