### ISSUE TITLE
Filter support for "MailboxRegion" in Get-EXOMailbox

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#7208]
Would be useful if this cmdlet supported filtering on the mailboxregion property

https://docs.microsoft.com/en-us/powershell/module/exchange/get-exomailbox?view=exchange-ps

**Comment by dariomws** [comment]
@danmyhre - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Exchange better. They keep a close tab on user feedback, and it would be awesome if you could add your voice in User Voice https://office365.uservoice.com/.

You might find others have made a similar request that you can add to or open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by yogkumgit** [comment]
@danmyhre Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Comment by danmyhre** [comment]
@dariomws 
https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/42725063-add-support-for-filtering-on-mailboxregion-propert
