### ISSUE TITLE
Set-SPODisableSpacesActivation - Documentation not available/Missing

### ISSUE THREAD

**Issue by ganesh-sanap** [MicrosoftDocs/office-docs-powershell#7209]
## Category

- [x] Additional article idea
- [x] Question

## Question

When the documentation for `Set-SPODisableSpacesActivation` cmdlet  would become available?

**Comment by get-itips** [comment]
Hello @ganesh-sanap Ganesh, thanks for reporting, will propose adding the article thru a pr.
