### ISSUE TITLE
Example syntax error

### ISSUE THREAD

**Issue by Pher0ah** [MicrosoftDocs/office-docs-powershell#7210]
[Enter feedback here]
Example shows -Identity; when the command actually takes -Identities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 453e99be-6c14-edf4-5710-f24aa696bfcc
* Version Independent ID: 14c7c972-0980-21ce-63e1-d928d8e25997
* Content: [Remove-CsOnlineApplicationInstanceAssociation (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/remove-csonlineapplicationinstanceassociation?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Remove-CsOnlineApplicationInstanceAssociation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Remove-CsOnlineApplicationInstanceAssociation.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for reporting @Pher0ah
