### ISSUE TITLE
Teams PowerShell module blocks client updates

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#7217]
Hi,

Not sure if anybody has informed to you, but when running Teams PS module it have a log handle open to:
**%localappdata%\microsoft\teams\powerShell**

The same results using handle:
```
C:\>\ handle.exe c:\Users\userid\AppData\Local\Microsoft\Teams\

Nthandle v4.22 - Handle viewer
Copyright (C) 1997-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

powershell.exe     pid: 17540  type: File           D80: C:\Users\userid\AppData\Local\Microsoft\Teams\Powershell\TeamsPowershell_20210204185132.log
powershell.exe     pid: 1780   type: File           D58: C:\Users\userid\AppData\Local\Microsoft\Teams\Powershell\TeamsPowershell_20210205113624.log
powershell.exe     pid: 11268  type: File           D5C: C:\Users\userid\AppData\Local\Microsoft\Teams\Powershell\TeamsPowershell_20210205114038.log
```

This problem appears especially when trying to run different client versions using the "Teams Windoes.exe" file:
1. Quite current Teams client
2. Start new Teams client using Teams WIndows.exe

This is blocking the client upgrades, so would you be so kind and move the log file away from client path. It is also not so good idea to mix clients and admin tools in this way.

**Comment by tseward** [comment]
@Petri-X since this is not a docs bug, I would suggest opening a [Teams Uservoice](https://microsoftteams.uservoice.com/) or open a support case with Microsoft via admin.microsoft.com.

**Comment by Petri-X** [comment]
Ok, so to nowhere ? :)

I actually though as on Gallery site there is a link:
![image](https://user-images.githubusercontent.com/43988151/107159583-c327a480-6999-11eb-81d2-e805f0f1ce39.png)
That I could send feedback using this path. But lets see what UV could do.

Have a nice day.

**Comment by DEberhardt** [comment]
If this holds true it would explain why my client is "stuck" all the time.
Now where is that spitting tea emoji? ;)

**Comment by Petri-X** [comment]
Yes I wrote it into VoicelessUser. But it looks pretty much like a black hole. I just could hope that someone sees that. Also, on the category for "bugs", Teams PS module is not even listed there.

So it is kind of useless to report the issues. But thank you for asking :)

**Comment by yogkumgit** [comment]
@Petri-X  Thank you very much for your kind feedback and following the advise of experts and reporting this to a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
