### ISSUE TITLE
New-Team : Error occurred while executing Code: Request_ResourceNotFound

### ISSUE THREAD

**Issue by expta** [MicrosoftDocs/office-docs-powershell#7225]
I created an App Registration in Azure AD which uses certificate-based auth so I can run a Teams script as a scheduled task. I've given the app the highest permissions to read directory data, create group and teams. I can Get-Team and Set-Team, but when I run New-Team I get the following error:

PS C:\> New-Team

cmdlet New-Team at command pipeline position 1
Supply values for the following parameters:
DisplayName: TestTeam
New-Team : Error occurred while executing
Code: Request_ResourceNotFound
Message: Resource '569ab4b2-80c3-4476-9d2e-34aa4d4d5f5e' does not exist or one of its queried reference-property objects are not present.
InnerError:
  RequestId: 1f55a916-d0b3-4758-99c5-27946372fde0
  DateTimeStamp: 2021-02-06T02:06:57
HttpStatusCode: Request_ResourceNotFound
At line:1 char:1
. + New-Team
. + ~~~~~~~~
   . + CategoryInfo          : NotSpecified: (:) [New-Team], ApiException
   . + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.NewTeam

PS C:\>

This works fine if I use Connect-MicrosoftTeams, but I need the script to run as a Scheduled Task.

**Comment by expta** [comment]
I discovered that you must assign the owner at the time the Team is created when using certificate-based authentication. This is not a requirement when using interactive login to Connect-MicrosoftTeams.

Please add this to the documentation and/or update the error message.

**Comment by get-itips** [comment]
Hello @expta Jeff, how are you?
I could reproduce, I am adding a note to the documentation.
Thanks for reporting.
