### ISSUE TITLE
Cmdlet not respecting -WarningAction SilentlyContiune 

### ISSUE THREAD

**Issue by DevJonBirkett** [MicrosoftDocs/office-docs-powershell#7226]
When Grant-CsTeamsUpgradePolicy finds settings that would be superceded by TeamsUpgradePolicy, the warning messages are not being supressed by the -WarningAction SilentlyContinue parameter on the cmdlet

So for example:
Grant-CsTeamsUpgradePolicy -identity $user -PolicyName UpgradeToTeams  -WarningAction SilentlyContinue
Is still reporting warning messages to the screen. 

This could well be by design, if so it would be helpful to add a note saying this is expected behaviour. 
**Suggested wording:**
"Note: This warning messages are not effected by the -WarningAction global parameter". 
**Suggested place:**
Just above "Example" title where the page describes this functionality. 

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6f141e1-2a79-03df-25e5-4e107388d3aa
* Version Independent ID: ea015ee3-54e2-e402-d533-c8a9a15557e8
* Content: [Grant-CsTeamsUpgradePolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsupgradepolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DevJonBirkett Jon, how are you?
I could reproduce, will propose adding a note to the article.
Thanks
