### ISSUE TITLE
Cleanup parameter list boxes, repeated information on page

### ISSUE THREAD

**Issue by briann5545** [MicrosoftDocs/office-docs-powershell#7227]
There are 8 boxes on this page that list all the parameters for the Set-Mailbox command, however these lists appears to be duplicates with only the 2nd parameter in each list as unique.  The page needs cleaned up?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f835af-5905-368a-df68-6646782ad807
* Version Independent ID: 153ce2d2-dab5-9c8f-c511-ee3bc8ee2dbc
* Content: [Set-Mailbox (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@briann5545, you touched on the reason for separate syntax blocks: each contains at least one parameter that can't be used together with others. Set-Mailbox is one of the largest cmdlets in the Exchange universe in terms of the total number of parameters. It's like playing "Where's Waldo" to try to find the unique parameters in each block. I spent some time right after the migration cleaning the syntax blocks up, and removing those that didn't have any unique parameters (if you can believe it, there were actually more syntax blocks!).

Syntax blocks are determined in code, and are picked up by whatever utility/process we use to document cmdlet reference topics (currently, the New-MarkdownHelp and Merge-MarkdownHelp cmdlets in the [platyPS](https://github.com/PowerShell/platyPS) module).

For more information about syntax blocks (a.k.a., parameter sets), see [Parameter sets in Exchange PowerShell](https://docs.microsoft.com/powershell/exchange/exchange-cmdlet-syntax?view=exchange-ps#parameter-sets-in-exchange-powershell).

If you can find any parameter sets that have zero unique parameters in them, I'll make sure they're investigated and likely removed.

**Comment by chrisda** [comment]
Nothing to do, so closing
