### ISSUE TITLE
Minimal Use

### ISSUE THREAD

**Issue by dvickery** [MicrosoftDocs/office-docs-powershell#7229]
This page would be improved with sample output, e.g:

SourceDataLocation DestinationDataLocation CompatibilityStatus
------------------ ----------------------- -------------------
EUR                           GBR                                   Warning
EUR                           NAM                                 Warning
GBR                           EUR                                   Incompatible
GBR                           NAM                                 Compatible 

Also, can you provide advice on how to proceed if the CompatabilityStatus is Warning or Incompatible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79aa5ead-5aef-c9f9-4802-944b32c9642e
* Version Independent ID: dfe8195a-d7ad-478d-dafd-574c6bb9e3e1
* Content: [Get-SPOGeoMoveCrossCompatibilityStatus (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spogeomovecrosscompatibilitystatus?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoMoveCrossCompatibilityStatus.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoMoveCrossCompatibilityStatus.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by kingabnt** [comment]
Issues

**Comment by get-itips** [comment]
Hello @dvickery David, how are you?
Cmdlet documentation does not include sample output. Probably a place where some advice could be added would be [this other page](https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-microsoft-365?view=o365-worldwide) or [this](https://docs.microsoft.com/en-us/microsoft-365/enterprise/move-sharepoint-between-geo-locations?view=o365-worldwide) one. where you will find more procedural articles.
Would you be so kind in creating an issue against any of those articles so it is handled by that other repo team?
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @dvickery Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
