### ISSUE TITLE
the correct word would be Syntax, not sintax

### ISSUE THREAD

**Issue by jeff2work** [MicrosoftDocs/office-docs-powershell#7233]
Multiple uses of sintax instead of syntax

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a552efca-0c18-3b2a-fa6e-af1ed276ea08
* Version Independent ID: 82f50727-a66f-4faa-1df5-0932ab8f1b7b
* Content: [Set-CsSlaConfiguration (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csslaconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsSlaConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsSlaConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment]
@DEberhardt Thank you very much for the contribution and updating the documentation with PR. @jeff2work Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
