### ISSUE TITLE
Inaccurate information or incorrectly-configured ParameterSets on Start-SPOSiteContentMove cmdlet

### ISSUE THREAD

**Issue by Lee-Myhre** [MicrosoftDocs/office-docs-powershell#7248]
The Parameters section does not match the Examples. The Parameters shows DestinationUrl and DestinationDataLocation as 
 mutually-exclusive and part of separate parameter sets; the Description underlines this by showing that the ParameterSets are each labeled with only one of these two parameters. Example 3 shows these two parameters being used together, which should be impossible given the information from the Parameters and Description section.

Either the Parameters and Description sections are correct, and the Example does not correctly describe a valid usage of this cmdlet; or else the Example reflects the correct intended use of these parameters, and the Parameters and Description sections are inaccurate (and/or indicate a bug that will prevent this usage).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcefde58-301b-06d3-d59c-5cbc2ca54283
* Version Independent ID: a54c713c-4995-30d6-c500-bd13152e8190
* Content: [Start-SPOSiteContentMove (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/start-spositecontentmove?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteContentMove.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteContentMove.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for reporting @Lee-Myhre
