### ISSUE TITLE
Set-MailboxRegionalConfiguration -DomainController

### ISSUE THREAD

**Issue by maettle** [MicrosoftDocs/office-docs-powershell#7252]
-DomainController isn't aviable in Exchange 2016 on this command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573e63b4-b27b-5b7b-9269-78d308fd64d3
* Version Independent ID: 57b35909-0381-1181-58bb-2262c33576d1
* Content: [Set-MailboxRegionalConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxregionalconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxRegionalConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-MailboxRegionalConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@maettle, I tested on Exchange 2010 SP3 RU30, Exchange 2013 CU23, Exchange 2016 CU19, and Exchange 2019 CU8, and the DomainController parameter is available on the Set-MailboxRegionalConfiguration cmdlet.

Other than different CUs, we could be talking about an RBAC permissions issue. From [this topic](https://docs.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions), run the following commands to see what you get:

```powershell
$Perms = Get-ManagementRole -Cmdlet Set-MailboxRegionalConfiguration -CmdletParameters DomainController
$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}
```

These are my results. The User Options role, which is assigned to the Help Desk and Organization Management role groups is what gives access to that cmdlet/parameter combination.

```powershell
Role         RoleAssigneeType RoleAssigneeName
----         ---------------- ----------------
User Options        RoleGroup Help Desk
User Options        RoleGroup Organization Management
```

**Comment by maettle** [comment]
@chrisda with your commands I was able to track down the problem to insufficient permissions. Thank you!
