### ISSUE TITLE
Add new markdown lint rule to fail when SharePoint is misspelled

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/office-docs-powershell#7257]
As title says because this would stop changes like in #7256 being needed in future

**Comment by DEberhardt** [comment]
Shouldn't VScode extensions like Spellchecker automatically pick this up?
I know PascalCase words like `SharePoint` are treated as `Share` and `Point` which both are in the dictionary. All other iterations would be flagged there anyway.

Don't know if there are additional lint rules available to add checking for specific words though (still learning on that topic so happy to add to my knowledge mesh :))

**Comment by kilasuit** [comment]
Not everyone uses VSCode so you cannot enforce it via that mechanism just in case you get the hardcore notepad dev (which yes, they definitely still exist) but it should be added there too for those that do.

But markdown lint rules for this is a common & easy to add approach that ensures you get the error as part of the build which allows for it to be always caught, not just sometimes caught which is what you'd get with a VSCode workspace setting

**Comment by get-itips** [comment]
Hello @kilasuit Ryan, how are you? hope you are doing good.
We can only make changes to the text content in articles, not to the underlying spell check rules, however, I'll try to pass this recommendation to the team.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @kilasuit Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
