### ISSUE TITLE
Use List of Multiple Users not working

### ISSUE THREAD

**Issue by ihntremmel** [MicrosoftDocs/office-docs-powershell#7260]
created a text file and followed the instructions, get back "Cannot bind argument to parameter 'Identity' because it is null."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d193a89-ffbc-90ab-990e-0e36b7845496
* Version Independent ID: 12a028e5-d1ce-12ab-2da8-c46d4815754c
* Content: [Enable or disable access to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/disable-access-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by DEberhardt** [comment]
Hello, Could you give us an example to better verify where the problem might be?
I don't want to investigate in the wrong direction ;)

**Comment by ihntremmel** [comment]
David,

No problem.  In this section: [https://docs.microsoft.com/en-us/powershell/exchange/disable-access-to-exchange-online-powershell?view=exchange-ps#use-a-list-of-specific-users](https://docs.microsoft.com/en-us/powershell/exchange/disable-access-to-exchange-online-powershell?view=exchange-ps#use-a-list-of-specific-users) there is the code:
`$NPS = Get-Content "C:\My Documents\NoPowerShell.txt"` and
`$NPS | foreach {Set-User -Identity $_.MicrosoftOnlineServicesID -RemotePowerShellEnabled $false}`

When I attempted to perform these with a txt document that contained one UPN per line while connected to Exchange Online, I received:

> Cannot bind argument to parameter 'Identity' because it is null.
for each line of my txt document. I grabbed users via powershell and exported to a csv, and then saved as txt (ms-dos) from Excel. In Notepad++, it looks like one UPN per line with no abnormal characters.

**Comment by DEberhardt** [comment]
Hello,
I see. It looks like the TXT file does not have a Column header "MicrosoftOnlineServicesID" as the command would expect. This is common for CSV files (which result in PowerShell importing the content as an Object and the keys can be called by subsequent CmdLets. It references something here that doesn't exist, therefore it fails.

Two way around this:
````powershell
$NPS = Get-Content "C:\My Documents\NoPowerShell.txt"
$NPS | foreach { Set-User -Identity $_ -RemotePowerShellEnabled $false }
````
alt
````powershell
# This is an alternative method that protects from malicious code in a line in the TXT as $_ represents the whole line.
# If $_ is not a UPN, piping it to Set-User will fail
$NPS | foreach { $_ | Set-User -RemotePowerShellEnabled $false }
````

or

Edit your NoPowerShell.txt file to have `MicrosoftOnlineServicesID` in the first line. This now enable PowerShell to identify headers and the Identity being correctly picked up. You can then run the example as is.
````powershell
$NPS = Get-Content "C:\My Documents\NoPowerShell.txt"
$NPS | foreach {Set-User -Identity $_.MicrosoftOnlineServicesID -RemotePowerShellEnabled $false}
````
Sadly, I cannot test this myself right now to confirm it working.


In any case, it could and should be called out cleaner in the Example.
Don't know which way to go to raise the PR, can someone confirm whether my alternative would be suitable?

**Comment by ihntremmel** [comment]
Thanks @DEberhardt. I had brought it up in the hopes that the information would get clarified if necessary so people in the future would not run into the same issues.
Cheers

**Comment by dariomws** [comment]
@ihntremmel @DEberhardt thank you for your feedback and comments. It should be live in the next couple of days.
