### ISSUE TITLE
Please update the doc site with new settings available

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/office-docs-powershell#7263]
Information is missing for the following settings, please update the page. 
AllowScreenshotCollection
AllowEmailCollection
AllowLogCollection

thanks
/Markus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa66e57e-734d-a869-41c6-385331fc5dc7
* Version Independent ID: 99e0b26c-c256-7238-bef6-52c3e7db38cf
* Content: [Set-CsTeamsFeedbackPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsfeedbackpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsFeedbackPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsFeedbackPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for reporting @JohanssonMarkus
