### ISSUE TITLE
Size issue - 1MB WAV should be under the limit of 5?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7266]
Hello,

I am investigating why my script broke down when using Import-CsOnlineAudioFile:
````
Import-TeamsAudioFile : Importing file failed - Please check file size and 
compression ratio. If in doubt, provide in WAV Format. Exception: Sending data to a remote 
command failed with the following error message: The current deserialized object size 
of the data received from the remote client computer exceeded the allowed maximum 
object size. The current deserialized object size is 10572800. The allowed maximum 
object size is 10485760. For more information, see the about_Remote_Troubleshooting 
Help topic.
````
The first part of this is my own Error Message, the second part is the Exception thrown by Import-CsOnlineAudioFile.
Running the command by hand with the following steps results in the same error:

````powershell
$File = "D:\Code\Testing\AudioFile.wav"
$content = Get-Content $File -Encoding byte -ReadCount 0

      $parameters = $null
      $Parameters += @{ 'ApplicationId' = $ApplicationId }
      $Parameters += @{ 'FileName' = "$FileName" }
      $Parameters += @{ 'Content' = $Content }
      $Parameters += @{ 'ErrorAction' = 'STOP' }
      $AudioFile = Import-CsOnlineAudioFile @Parameters
````

I tried to find an issue with the length and compare to the 5MB limit, and all looks OK:
````powershell
❯ (Get-ChildItem $File).Length
1018290
❯ $content.length
1018290
❯ $content.length -lt 5242880
True

````
I get that some MP3 and WMV files may be over the Limit (`The allowed maximum object size is 10485760`) as they are compressed, but WAV should not have any compression and should result in the same length as the file (as evidenced above)

Am I missing something, or is there an issue with the CmdLet?

For reference - Importing the same file in the Admin Center works without issue!

Thanks,
David

PS: $ApplicationId is "HuntGroup", i.E. for a CQ

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a65371d7-e254-1bf7-e3f3-035d294fe1cd
* Version Independent ID: cc63afcc-727b-c972-eb11-21d6a15f1d0e
* Content: [Import-CsOnlineAudioFile (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Import-CsOnlineAudioFile.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DEberhardt David, This appears not to be an issue with the cmdlet but with PS Remoting anyway as this is not a documentation issue I can handle, I'll try to pass this information on.
Thank you!

**Comment by get-itips** [comment]
Also, if you can, you can open a support ticket so this reaches the team :)

**Comment by DEberhardt** [comment]
Will do. Thanks. :)

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DEberhardt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DEberhardt** [comment]
Raised: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/42773060-import-csonlineaudiofile-does-not-import-audio-fil
