### ISSUE TITLE
Get-CsOnlineTelephoneNumber ResultSize defaults not documented

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#7290]
The Get-CsOnlineTelephoneNumber article does not describe the default ResultSize limit.
Currently, if we run `Get-CsOnlineTelephoneNumber` without any parameters, the cmdlet returns first 500 objects only (and no warning indicating output truncated).

Please add a note that says about this 500 objects limit.

PS. sample code to get all results:

`Get-CsOnlineTelephoneNumber -ResultSize ([int]::MaxValue)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 692aad2a-bc29-6c7d-b5bf-82164fcfda85
* Version Independent ID: 31943e3e-3089-3e45-c013-b88f2409e3e2
* Content: [Get-CsOnlineTelephoneNumber (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for reporting @shivtorov
