### ISSUE TITLE
update New-CsOnlineSchedule article to replace legacy OAA with AA

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#7291]
`New-CsOnlineSchedule` creates scheduled that can be used for:
- CsOrganizationalAutoAttendant
- CsAutoAttendant

CsAutoAttendant replaced legacy CsOrganizationalAutoAttendant

Suggested changes to the article:

1) in the "DESCRIPTION" and "RELATED LINKS" section replace all references to legacy CsOrganizationalAutoAttendant with new CsAutoAttendant

2) Example 5 - first two lines should be deleted, as they are not relevant to line 3 in the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93094674-2964-b558-4543-ac3f60ee1e8f
* Version Independent ID: 5b46aa89-0965-e0d2-6e73-e831651e0271
* Content: [New-CsOnlineSchedule (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlineschedule?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineSchedule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineSchedule.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for reporting @shivtorov
