### ISSUE TITLE
Example 5 contains wrong CAML query

### ISSUE THREAD

**Issue by sagar4u** [MicrosoftDocs/office-docs-powershell#7292]
[Enter feedback here]
Example 5 in the document contains just GUID and it is not actual CAML query.
Example 5 supposed to show valid CAML query

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b777fcfe-c7da-0165-d6ac-74fc2db07daf
* Version Independent ID: 12045879-94af-fd90-66a0-8f3db00a579f
* Content: [Get-PnPListItem (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPListItem.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @sagar4u 

how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!
