### ISSUE TITLE
ConditionalAccessPolicy

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/office-docs-powershell#7293]
Hello,

Seems the "ConditionalAccessPolicy: ReadOnly" blocking .txt or .log files on unmanaged PC's if use Webmail,
While PDF or Word files displayed just fine... any explanation for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022da80e-29cd-f6b5-aa00-48e2d16c4be8
* Version Independent ID: c3353c03-e416-f693-104f-6b6f5955b721
* Content: [Set-OwaMailboxPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@lightupdifire, I would suggest opening a support case on this. If you find anything that requires a content update, report back here, and we'll make the update.

**Comment by lightupdifire** [comment]
@chrisda 
I will open a Support ticket, but if it is a Real limitation, would be good to include in the document information about this limitation, you agree?

**Comment by chrisda** [comment]
@lightupdifire, yes. Absolutely. The support case will confirm whether this is a known limitation that needs to be documented, or some type of bug that will get fixed (and will therefore not require documentation updates).

Report back here with their findings.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @lightupdifire Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
