### ISSUE TITLE
Confusing sentence

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#7313]
This example stops the ability to "moves the movement" of the objects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e77d7e6-f1bb-0922-b149-7718fc99c6a7
* Version Independent ID: c0fcf89d-6a61-4ba6-e600-b18dae362716
* Content: [Stop-SPOUserAndContentMove (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/stop-spouserandcontentmove?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Stop-SPOUserAndContentMove.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Stop-SPOUserAndContentMove.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for reporting @hwkwicre
