### ISSUE TITLE
UTF 8 or 16?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/office-docs-powershell#7319]
This article states we must use UTF 16: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-keyword-dictionary?view=o365-worldwide#modifying-an-existing-keyword-dictionary

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2b0ab96-73c6-e6f6-562b-35ac3c9c2c0a
* Version Independent ID: 46f7615a-a8e0-4e24-64eb-26815c40dcfa
* Content: [Set-DlpKeywordDictionary (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-dlpkeyworddictionary?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-DlpKeywordDictionary.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-DlpKeywordDictionary.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Mike-Crowley, I updated New-DlpKeywordDictionary and Set-DlpKeywordDictionary from UTF-8 to UTF-16.

Thanks for the feedback.

Closing.

**Comment by Mike-Crowley** [comment]
Thanks - I see there are both code samples and paragraphs that still reference 8, but i guess its still working through the change process?

**Comment by chrisda** [comment]
Correct. There have been some publishing issues the last few days, but I made the change and it is coming.
