### ISSUE TITLE
1MB or 100KB Dictionary size?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/office-docs-powershell#7320]
This other article states the file size limit is 1MB, vs the 100KB listed here.

https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-keyword-dictionary?view=o365-worldwide#modifying-an-existing-keyword-dictionary

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2b0ab96-73c6-e6f6-562b-35ac3c9c2c0a
* Version Independent ID: 46f7615a-a8e0-4e24-64eb-26815c40dcfa
* Content: [Set-DlpKeywordDictionary (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-dlpkeyworddictionary?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-DlpKeywordDictionary.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-DlpKeywordDictionary.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
This is related to #6009.

**Comment by chrfox** [comment]
1MB is the most recent update, go with the 1 MB

**Comment by chrisda** [comment]
Topic updated to 1 MB limit.

Thanks for the feedback.

Closing
