### ISSUE TITLE
-Batch missing on Set-PnpListItem

### ISSUE THREAD

**Issue by nhadro** [MicrosoftDocs/office-docs-powershell#7321]
I installed "Install-Module -Name PnP.PowerShell -RequiredVersion 1.3.0" and when I try to use "Set-PnPListItem" there is no parameter for Batch.

Is this available on for the latest stable version?

**Comment by get-itips** [comment]
Hello @nhadro 

how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your inquiry with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @nhadro Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
