### ISSUE TITLE
TerminatingError: "429 in /v1.0/teams/ endpoint"

### ISSUE THREAD

**Issue by kpinel** [MicrosoftDocs/office-docs-powershell#7322]
Seeing the above error regularly since updating to 1.1.11

Error in its entirety in the transcript
```
PS>TerminatingError(New-Team): "429 in /v1.0/teams/ endpoint"
>> TerminatingError(): "System error."
>> $global:?
False
```

It wasn't so common in 1.1.10 but we never had the first line

have reverted to 1.1.9 as it appears more stable.

We require the preview modules to create class teams as well as for managing Skype for Business but, currently only seeing this error when creating a new team

**Comment by kpinel** [comment]
New development and not sure if it is related but a progress bar now appears for each thread. Pretty pointless if the script is part of an automated process.
The progress bar shows the 10 latest threads, I think and only appears this way with an ambiguous search
![image](https://user-images.githubusercontent.com/875143/108647868-6c77aa00-7505-11eb-9c6b-ed4e5f2b66e1.png)
Search was:
Get-Team | ?{$_.Description -eq "KYB301_21se1:Situated Creative Practice Project" -or $_.DisplayName -eq "KYB301_21se1:Situated Creative Practice Project"}
This is done because our staff tend to change the descriptions quite regularly. We've made ammends for this but there's still a need for this search

**Comment by get-itips** [comment]
Hello @kpinel 
How are you? Hope you are doing good.
Here we are limited to documentation issues, please be aware that Public Preview versions are development versions subject to changes.

Thank you

**Comment by kpinel** [comment]
Thanks for that. Sadly this was the only place for for responding.
The reason for the public review is that we are a university and the only way to use the education templates is the preview version

**Comment by get-itips** [comment]
> Thanks for that. Sadly this was the only place for responding.
> The reason for the public review is that we are a university and the only way to use the education templates is the preview version

I can understand that. I would keep an eye on the releases of new GA versions of the Teams PowerShell module to check again if the feature is included.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @kpinel Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
