### ISSUE TITLE
Exchange Online Management v2 Powershell - v2.0.4 Non-Stored Credential issue

### ISSUE THREAD

**Issue by dehavenba** [MicrosoftDocs/office-docs-powershell#7326]
With the latest update/version of the Exchange Online powershell module a **major** behavior change was implemented that is not called out accurately in the documentation. When connecting to Exchange Online, the new module behavior relies upon the local authentication library (MSAL) for credential lookup even if you specify a credential to be used. For admins that login with one account to their machine and then use a second account to perform administrative duties, this can break functionality in day to day operations, especially in scenarios where ADFS is in play. To allow an admin to connect with their designated account, first you have to connect w/ Connect-AzureAD, then you can run Connect-ExchangeOnline and utilize the preferred credential. 

Fiddler Data Capture:
Connect-AzureAD Example:

resource	https://graph.windows.net
client_id	1b730954-1685-4b74-9bfd-dac224a7b894
response_type	code
haschrome	1
redirect_uri	urn:ietf:wg:oauth:2.0:oob
client-request-id	d264865b-6b5b-480b-b199-518d35871c81
prompt	login
x-client-SKU	PCL.Desktop
x-client-Ver	3.19.7.16602
x-client-CPU	x64
x-client-OS	Microsoft Windows NT 10.0.18363.0
site_id	501358
display	popup

Connect-ExchangeOnline

scope	https://outlook.office365.com/.default openid profile offline_access
response_type	code
client_id	fb78d390-0c51-40cd-8e17-fdbfab77341b
redirect_uri	https://login.microsoftonline.com/organizations/oauth2/nativeclient
claims	{"access_token":{"xms_cc":{"values":["cp1"]}}}
client-request-id	46eb85d3-8da7-41b6-846e-5d82e787db6b
x-client-SKU	MSAL.Desktop
x-client-Ver	4.23.0.0
x-client-CPU	x64
x-client-OS	Microsoft Windows NT 10.0.18363.0
prompt	select_account
code_challenge	D6xU_KfNatR18EWEy3EOvcJO_F2Qbo7oSNOqNosQ3P0
code_challenge_method	S256
state	51d87226-68d4-4e8c-887c-8aedb9d42403c8e1eca1-5df8-422c-9b68-88cb563d6eb7

**Comment by dariomws** [comment]
@dehavenba - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @dehavenba Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dehavenba** [comment]
This is not a tenant specific item/issue, this is new behavior built into
the tools by Microsoft. Thus why I submitted this feedback to have the
documentation updated to reflect the new behavior.
- Bruce D

**Comment by dariomws** [comment]
@dehavenba thank you again for your comment.

Yes, the product team is aware of that. I redirected you to support because it's the best place to report issues like this one. Here we are limited to documentation issues and improvements.
