### ISSUE TITLE
Unable to connect to Exchange Online using ExO 2.0.4 and PowerShell 7.1.2 on macOS 10.15.7

### ISSUE THREAD

**Issue by kyanar** [MicrosoftDocs/office-docs-powershell#7327]
Attempting to use the ExchangeOnlineManagement module in PS 7.1.2 on macOS Catalina results in Modern Auth prompt being followed immediately by the error

     | This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either
     | not installed or unavailable for this system.

Issue was first identified at https://github.com/PowerShell/PowerShell/issues/11188 and the PowerShell team have summarily dismissed it as an Exchange Online team issue.

**Comment by slabber** [comment]
@kyanar I have just commented in https://github.com/PowerShell/PowerShell/issues/11188

There is a workaround here 

```
Install-Module -Name PSWSMan

# Requires root access to install, Install-WSMan can be run directly if already running as root
sudo pwsh -Command 'Install-WSMan'
```

Restart powershell

**Comment by dariomws** [comment]
Hi @kyanar and @slabber, thank you for your feedback.

I asked internally, and the product team is aware and working on it. Sadly I cannot provide more information like when we would have some news about it.

If you haven't done it yet, you can also report this to exocmdletpreview[at]service[dot]microsoft[dot]com (The email address is purposefully obfuscated to avoid spam).

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @kyanar Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
