### ISSUE TITLE
Register-SPMTMigration missing functionality in the documentation

### ISSUE THREAD

**Issue by ygeorgiev-varna** [MicrosoftDocs/office-docs-powershell#7329]
Hello,

In the documentation for the SPMT PS module

https://docs.microsoft.com/en-us/powershell/module/spmt/register-spmtmigration?view=spmt-ps

is missing -MigrateWithoutRootFolder switch which is important for the group share migrations. 

BR

**Comment by get-itips** [comment]
Thanks for reporting @ygeorgiev-varna
