### ISSUE TITLE
ContentFilter Parameter it's doesn't exists for Exchange Online

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/office-docs-powershell#7331]
Trying this out:

```Powershell
Install-Module ExchangeOnlineManagement -AllowClobber -Force
Connect-ExchangeOnline
Get-Help New-MigrationBatch
```

Brings 10 Parameter Sets but in none of them, it's said or explicitly mentions that this parameter is only applicable for On-Premises and not for the Exchange Online Environment as mentioned.

Please double-check this and make corrections in order to fix this issue.
![242922](https://user-images.githubusercontent.com/5489996/108749621-a648b080-7505-11eb-8339-ae400a3216d0.gif)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68325010-9605-22b4-4b6c-b61f332dc321
* Version Independent ID: 47ce5d33-5483-8c8e-2aa2-532178bf466a
* Content: [New-MigrationBatch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@j0rt3g4, the help that's available at the command line is always going to lag behind what's available on the web. It's the same content; it just takes a while for the code check-in process to happen.

**Comment by j0rt3g4** [comment]
Hello @chrisda  I'm glad to talk to you again!.

I've got some tickets regarding this and the issue is true. The customer is willing to use the contentFilter parameter and it's available on the web, and not even updating into the latest ExchangeOnlineManagement doesn't contain this filter.

So What else should I be thinking if the documentation for the cmdlet itself is not showing the parameter but online do? is it something related to the versions? what version should be the correct to have this parameter online?

**Comment by chrisda** [comment]
If the web version of the topic is incorrect, we can fix it. That fix will take a long time to get checked back into code, that code deployed to datacenter servers, etc.

Not helping in all of this is: it's been a really long time since we've checked help files back into code. I know that very recently (last week) a check-in was done.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @j0rt3g4 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
