### ISSUE TITLE
New-team cmdlet error: property is missing a required prefix/suffix

### ISSUE THREAD

**Issue by Didier-VR** [MicrosoftDocs/office-docs-powershell#7333]
Hello, it seems to be impossible to create a new Microsoft Teams team using the New-Team cmdlet, when group naming policies are active in the O365 tenant.

I receive following error:
![image](https://user-images.githubusercontent.com/79573805/108984886-b5a83500-7690-11eb-822e-6a5d995c6d3e.png)

The naming policy enforces that group names are formatted as "GRP-[COMPANY]-[groupname]". Creating a team in the Teams client works fine, but creating a team in PowerShell fails. I have tried different combinations for the DisplayName (e.g. "groupname", "COMPANY-groupname", "GRP-COMPANY-groupname", ...), but no success.

This error was previously reported ([#1625](https://github.com/MicrosoftDocs/office-docs-powershell/issues/1625)), where the poster was advised to contact support; however, I believe the issue is in the code (code not recognizing the presence of a prefix in the DisplayName value).

**Would it be possible to add support for prefix and suffix in the New-Team cmdlet?** Either integrated in the DisplayName value, or using separate -Prefix and -Suffix parameters? It is not an option for us to disable the naming policy.

FYI, I'm using (preview) version 1.1.11 of the MicrosoftTeams module.
I tried executing the New-Team cmdlet both with my O365 Teams admin, and with a regular user account that has the required permissions to create a team in Teams. The error is the same for both accounts.

Best regards,
Didier

**Comment by get-itips** [comment]
Hello @Didier-VR Didier, how are you?
Here, we are limited to help with documentation changes and fixes, I am afraid I can not be of more help regarding issues encountered using the Teams PowerShell module. Also, please be aware that the Preview version of the module is the development version and is subject to changes.

For this:
> Would it be possible to add support for prefix and suffix in the New-Team cmdlet? Either integrated in the DisplayName value, or using separate -Prefix and -Suffix parameters? It is not an option for us to disable the naming policy.

The best way to reach the team would be https://microsoftteams.uservoice.com/ so they consider this idea for upcoming versions.

Hope this information helps you,

**Comment by Didier-VR** [comment]
Thanks for your answer.

I have posted a message on User Voice (https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/42820038-not-possible-to-create-a-team-with-powershell-new), I'll see if this gets implemented.

**Comment by Didier-VR** [comment]
Hi, I wanted to post an update about this issue, since I managed to create a Team with the New-Team cmdlet, and I think my issue was related to the documentation.

When a naming policy is active, the parameter MailNickName apparently is **mandatory**. It has to respect the naming policy, just like the DisplayName. Even when it's the same as the DisplayName, it has to be included when the cmdlet is executed.

From the documentation on docs.microsoft.com, I thought that the MailNickName (or the "Alias" on the unified O365 group that is created) is optional; when no value is given, it is defined automatically, based on the DisplayName. This doesn't seem to happen when a naming policy is enabled.

I have updated my User Voice post with this info.

Best regards,
Didier

**Comment by yogkumgit** [comment]
@get-itips

**Comment by yogkumgit** [comment]
Reminder @get-itips

**Comment by get-itips** [comment]
> Hi, I wanted to post an update about this issue, since I managed to create a Team with the New-Team cmdlet, and I think my issue was related to the documentation.
> 
> When a naming policy is active, the parameter MailNickName apparently is **mandatory**. It has to respect the naming policy, just like the DisplayName. Even when it's the same as the DisplayName, it has to be included when the cmdlet is executed.
> 
> From the documentation on docs.microsoft.com, I thought that the MailNickName (or the "Alias" on the unified O365 group that is created) is optional; when no value is given, it is defined automatically, based on the DisplayName. This doesn't seem to happen when a naming policy is enabled.
> 
> I have updated my User Voice post with this info.
> 
> Best regards,
> Didier

Thanks @Didier-VR for your feedback, will test this and improve the article if needed.
