### ISSUE TITLE
EXO 2.0.4 Errors in Powershell Transcripts

### ISSUE THREAD

**Issue by JAK1047** [MicrosoftDocs/office-docs-powershell#7334]
Since upgrading to 2.0.4 we're seeing constant Import-Module errors whenever we run Connect-ExchangeOnline. The errors appear to not be terminating though since the cmd itself still works.

>>PS>Import-Module C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.4\netFramework\ExchangeOnlineManagement.psm1 -Cmdlet Get-EXORecipient;Get-EXORecipient -ResultSize 1
>> TerminatingError(Import-Module): "A positional parameter cannot be found that accepts argument 'Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.4\netFramework\ExchangeOnlineManagement.psm1'."
>> TerminatingError(Import-Module): "A positional parameter cannot be found that accepts argument 'Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.4\netFramework\ExchangeOnlineManagement.psm1'."
A positional parameter cannot be found that accepts argument 'Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.4\netFramework\ExchangeOnlineManagement.psm1'.

This is just from the Connect-ExchangeOnline. Get-EXORecipient was never run, so not sure why that's appearing as well.

**Comment by dariomws** [comment]
@JAK1047 - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by JAK1047** [comment]
Understood I went ahead and created a ticket. I'll keep this thread updated as I get a response.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @JAK1047 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
