### ISSUE TITLE
teams 1.1.11 get-csbatchpolicyassignmentoperation missing parameters

### ISSUE THREAD

**Issue by woolfep** [MicrosoftDocs/office-docs-powershell#7336]
when trying this latest version of the teams module I noticed that get-csbatchpolicyassignmentoperation only now allows for  the status parameter, when i go digging into the module i see that there another function get-csbatchpolicyassignmentoperation1 which appears to hold the identity parameter.  Unfortunately when importing the module this function isn't imported. how can I use it?

**Comment by ITMonkey78** [comment]
+1 same issue. The command has no parameters other than -status
Get-CsBatchPolicyAssignmentOperation -OperationId 908131e5-022d-4322-9852-73df363ac5fb
Get-CsBatchPolicyAssignmentOperation : A parameter cannot be found that matches parameter name 'OperationId'.
At line:1 char:38

**Comment by woolfep** [comment]
I found a workaround  that works umtil microsoft fix it (presented it to microsoft in a case)  in the Microsoft.teams.configapi.cmd let’s.psm1 files comment out line 48 and I comment line 43, when you import the module after this the secondary cmdlet get-csbatchpolicyassignmentoperation1 will be available and will give you the functionality you need. (P.s. make sure to do this in BOTH of the psm1 files with the same name

**Comment by get-itips** [comment]
> when trying this latest version of the teams module I noticed that get-csbatchpolicyassignmentoperation only now allows for the status parameter, when i go digging into the module i see that there another function get-csbatchpolicyassignmentoperation1 which appears to hold the identity parameter. Unfortunately when importing the module this function isn't imported. how can I use it?

Hello @woolfep how are you?
Remember that 2.0.0 is the current General Availability version and 1.1.11-preview is a Public Preview version of the Teams PowerShell module.
Said that, in 2.0.0 `Get-CsBatchPolicyAssignmentOperation` accepts `Identity` and `Status` as parameters, as the documentation states currently.
Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @woolfep  Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
