### ISSUE TITLE
When group is created, there are no owners nor members in it, although I added them using as ArrayOfStrings? 

### ISSUE THREAD

**Issue by mvanders** [MicrosoftDocs/office-docs-powershell#7337]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff78b7f4-0927-27d0-0b1d-5bd00bb93d26
* Version Independent ID: 321cb4f2-43a1-1732-e429-3432af07a511
* Content: [New-PnPMicrosoft365Group (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpmicrosoft365group?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPMicrosoft365Group.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPMicrosoft365Group.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @mvanders 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your inquiry with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @mvanders Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
