### ISSUE TITLE
Most of the -Bookings* parameters are missing descriptions

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/office-docs-powershell#7339]
Please fill in the descriptions of the `-Bookings*` related parameters so that we can know what they do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23add0a6-bb9c-15d2-a6eb-351ae0564522
* Version Independent ID: 8056b3ee-4fab-3a5c-935b-a9d0e9ad82a4
* Content: [Set-OrganizationConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @webash, thank you for your feedback.

I'm trying to get more information about these parameters. Please give me some days.

**Comment by webash** [comment]
Hey @dariomws - any update? :)

**Comment by dariomws** [comment]
My apologies @webash. I still don't have any update. I´ll keep you posted once we have it.

**Comment by chrisda** [comment]
Seeking clarification from the product team. Responsible party identified, and I'm waiting for more information.

**Comment by dariomws** [comment]
@chrisda do you have any updates? Thanks!

**Comment by yogkumgit** [comment]
@chrisda Any update?

**Comment by chrisda** [comment]
All of the Bookings parameters are now described.

Thanks for the feedback.

Closing
