### ISSUE TITLE
batching not working in the stable release

### ISSUE THREAD

**Issue by JosephJojo** [MicrosoftDocs/office-docs-powershell#7340]
The example 5 mentioned in this article is not working in the stable build of PnP PowerShell. If batching feature is not available for the stable build then it is not mention it in this article so others won't be get confused. Otherwise it is better to mention the required version on PnP PowerShell Module.

As from the github issue https://github.com/pnp/powershell/issues/327 it specified that this feature were removed from Stable build and moved in to the 1.3.14-nightly release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3efa2d-f7d5-d9d0-d306-7707e4906065
* Version Independent ID: f30dd9c9-c9fc-f3f9-d5f4-ee4e1b8d3f53
* Content: [Set-PnPListItem (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItem.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @JosephJojo 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your inquiry with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @JosephJojo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
