### ISSUE TITLE
ShowInTeamsSearchAndSuggestions is this parameter working?

### ISSUE THREAD

**Issue by inseu** [MicrosoftDocs/office-docs-powershell#7341]
The documentation should be updated. The ShowInTeamsSearchAndSuggestions is not working.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5143fcd-9f3c-9f5d-2bdf-50b97f6a98ff
* Version Independent ID: 01f33478-352d-c7ae-0c49-784fa1c1fd67
* Content: [Set-Team (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Thanks for your feedback @inseu
