### ISSUE TITLE
Examples not showing properly

### ISSUE THREAD

**Issue by JohnGGeo** [MicrosoftDocs/office-docs-powershell#7342]
On github, the query appears properly however in the doc site it appears not all the query is appearing. For example look at example 6. It references 
Get-PnPListItem -List Tasks -Query "<View><ViewFields><FieldRef Name='Title'/><FieldRef Name='Modified'/></ViewFields><Query><Where><Geq><FieldRef Name='Modified'/><Value Type='DateTime'><Today/></Value></Eq></Where></Query></View>"
In github however the example on the actual doc.microsoft.com page doesn't show this way.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b777fcfe-c7da-0165-d6ac-74fc2db07daf
* Version Independent ID: 12045879-94af-fd90-66a0-8f3db00a579f
* Content: [Get-PnPListItem (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPListItem.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @JohnGGeo 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @JohnGGeo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
