### ISSUE TITLE
How do you suppress the 'disconnected successfully' message for the Powershell ExchangeOnlineMangement v2 disconnect-exchangeonline cmd?

### ISSUE THREAD

**Issue by PeteMitch99** [MicrosoftDocs/office-docs-powershell#7344]
[Enter feedback here]

How do you suppress the 'disconnected successfully' message? It appears in the console window not matter what method i use to suppress it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3520ee8b-4c1b-5cf1-677e-9dcd14d88ea1
* Version Independent ID: 219014fd-5626-e1bf-aac4-b321bbdaa465
* Content: [Disconnect-ExchangeOnline (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/disconnect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@PeteMitch99, this should work: 

```powershell
Disconnect-ExchangeOnline -Confirm:$false
```

**Comment by PeteMitch99** [comment]
Hi Chris, thanks for the response.

This command does not suppress that message. Neither does anything else:

I can't suppress the 'Disconnected successfully !' message when using
Disconnect-ExchangeOnline from a PowerShell window using any of the
provided switches.

This pollutes my output stream for automation XML returns and is very
frustrating.

This can be easily replicated by running the below line (you do not even
need to be connected first):

$Output_Detail = Disconnect-ExchangeOnline -confirm:$False -ea
SilentlyContinue -WarningAction SilentlyContinue| out-null

the console window output is:

PS C:\WINDOWS\system32> $Output_Detail = Disconnect-ExchangeOnline
-confirm:$False -ea SilentlyContinue -WarningAction SilentlyContinue|
out-null
Disconnected successfully !

   1. Can you explain why this stream can't be redirected.
   2. Can you supply a switch in 'Disconnect-ExchangeOnline' to turn this
   message off.


Also logged here:

https://github.com/MicrosoftDocs/office-docs-powershell/issues/7346

Let me know if I need to open and o365 ticket for it.

**Comment by chrisda** [comment]
Got it. Checking.

**Comment by PeteMitch99** [comment]
After debugging the MS code i'll answer this myself. Its a write-host. Since PS 5.1 this is output to the information stream - so just the console but not the output stream.

Fine unless you are writing automation for a product that scrapes the console output (like Service now). 

So this works.

$Output_Detail += Disconnect-ExchangeOnline -confirm:$False -InformationAction Ignore

Would make more sense if it was included in the -Confirm:$false switch though.

**Comment by chrisda** [comment]
@PeteMitch99, interesting. When I try to run that command directly, I get an error:

 ```powershell
PS C:\> Disconnect-ExchangeOnline -Confirm:$false -InformationAction Ignore
Write-Host : The value Ignore is not supported for an ActionPreference variable. The provided value should be used
only as a value for a preference parameter, and has been replaced by the default value. For more information, see the
Help topic, "about_Preference_Variables."
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.4\netFramework\ExchangeOnlineManagement.psm1:704 char:17
+                 Write-Host "Disconnected successfully !"
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Host], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException,Microsoft.PowerShell.Commands.WriteHostCommand
```

So do you need to use that syntax in a script along with the Write-Host cmdlet?

**Comment by PeteMitch99** [comment]
Ah maybe you are right and still needs fixing. It should work from what I
understand here:

https://adamtheautomator.com/powershell-write-host/

The command I was originally running was:
Disconnect-ExchangeOnline -InformationAction Ignore -WarningAction
SilentlyContinue -ErrorAction SilentlyContinue

But I think what I happening is the '-ErrorAction SilentlyContinue' is
killing the '-InformationAction Ignore' Error Message.

So yes it still needs fixing.

**Comment by PeteMitch99** [comment]
```
PS C:\Users\adm\Documents> $error.clear()

PS C:\Users\adm\Documents> Disconnect-ExchangeOnline -InformationAction Ignore -ErrorAction SilentlyContinue -Confirm:$false

PS C:\Users\adm\Documents> $error
Write-Host : The value Ignore is not supported for an ActionPreference variable. The provided value should be used only as a value for a preference parameter, and has been replaced by the default value. For more information, see the Help 
topic, "about_Preference_Variables."
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.4\netFramework\ExchangeOnlineManagement.psm1:704 char:17
+                 Write-Host "Disconnected successfully !"
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Host], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException,Microsoft.PowerShell.Commands.WriteHostCommand
```
 This is what is happening.

**Comment by PeteMitch99** [comment]
`Disconnect-ExchangeOnline -InformationAction Ignore -ErrorAction Continue -Confirm:$false`
Shows error
`Disconnect-ExchangeOnline -InformationAction Ignore -Confirm:$false -ErrorAction SilentlyContinue`
hides error
`
PS C:\Users\adm\Documents> Disconnect-ExchangeOnline -InformationAction SilentlyContinue -Confirm:$false -ErrorAction SilentlyContinue
Removed the PSSession ExchangeOnlineInternalSession_3 connected to outlook.office365.com
Disconnected successfully !
`
just displays the 'Successfully Disconnected!' Message

**Comment by chrisda** [comment]
I'm OK with updating documentation with `Disconnect-ExchangeOnline -InformationAction Ignore -Confirm:$false -ErrorAction SilentlyContinue` as an option to hide any/all response text, unless hiding this and other possible errors is somehow dangerous? An error disconnecting likely indicates that you're still connected.

**Comment by PeteMitch99** [comment]
Hi @chrisda , thanks for the response.

First, before the documentation I think you or someone else in MS needs to prove the following:

When it fails on the write-host lines of the exchange-onlinemanagement module when it is connected, and gives the below error, is it ending the sessions correctly and just erroring on the write-host lines? Also is it then continuing to run the rest of the lines in the module, including if multiple sessions are open? 

If connect-exchange online has been run multiple times before so there are lots of sessions open - it would normally be expected to shut all of these sessions. 

```
PS C:\Users\adm\Documents> $error[0].InvocationInfo.Line
                        Write-Host "Removed the PSSession $($session.Name) connected to $($session.ComputerName)"
```

As it is a separate module calling different functions I am not so sure - it my have a separate $erroractionpreference. If the cmd was running all the code I would expect to see at least one error for the 'remove session' write-host, and then another error for the 'Successfully Disconnected!' write-host Message. When i type $error afterwards, I don't, I just see the first error. So I believe the module may stop on the first error? If this was the case the command would not be doing its job.

It may by better to ask the team designing the module to code in a suppress switch, similar to the '-showbanner:$false' switch in the connect-exchangeonline cmd. Then for the write-host lines code [if ($something -eq $false') {don't write-host} else {do}).

I have opened a o365 premier ticket for this as well.

I am using Powershell 5.1 by the way.

**Comment by PeteMitch99** [comment]
Or just use write-output instead of write-host so the output can be redirected\captured in 5.1....

```
$hello = write-host "Hello"
$hello2 = Write-output "Hello2"
```

`'disconnect-exchangeonline 6>&1'`

 to redirect the information stream doesn't work either btw.

**Comment by PeteMitch99** [comment]
```
#DEMO failing Disconnect-ExchangeOnline

$ErrorActionPreference = "stop"
$error.clear()
$newline = "`r`n" 

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

import-module exchangeonlinemanagement

#Creds for any exchange
$cred = Get-Credential
Connect-ExchangeOnline -Credential $cred
Connect-ExchangeOnline -Credential $cred

"Look I have 2+ Exchange PS sessions open:"
get-pssession
$newline

"i'll run Disconnect-ExchangeOnline to disconnect them both - with -InformationAction Ignore -Confirm:$false -ErrorAction SilentlyContinue"
Disconnect-ExchangeOnline -InformationAction Ignore -Confirm:$false -ErrorAction SilentlyContinue
$newline

"Looks like the command has not completed property - looks like it only shut one connection. it suppose to shut them all in PS loop:"
get-pssession
$newline

"These are the PS errors - note there is only one - the loop killing all connections in the MS code has exited because of the error:"
$newline
$error
$newline

"Stacktrace - Gosh, the write-host is in the MS code:"
$error[0].ScriptStackTrace
$newline

"CONCLUSION: Write host line in MS Exchange module is stopping the module and '-ErrorAction SilentlyContinue' necessary to suppress the console output is unfortunatly suppressing the fact the command fails."
"Note I have no control over this write-host as it is in the MS code"
"This is not a workaround - as the output is suppressed but the command fails."
```

**Comment by PeteMitch99** [comment]
Update: MS Premier support have accepted this is an issue and will fix it in upcoming EXO v2 module release. They can helpfully give me no ETA.

**Comment by chrisda** [comment]
@PeteMitch99 cool. For the last several versions of the module, there are typically 2 to 3 Preview versions before that version is released publicly, and the whole process typically takes several months. It's likely that your fix will be in the next Preview version of the 2.0.5 version of the module, which will then follow through to the public 2.0.5 version.

Since there will be no documentation impact for this (it will just start working), I'm going to close this issue. But, feel free to reopen in the future as needed.

Thanks for the feedback.

Closing

**Comment by JeremyTBradshaw** [comment]
Thanks @PeteMitch99  and @chrisda .  Glad to see this issue got the heat it needed to be on the list to resolve.  I just emailed the EXO cmdlet preview feedback address this afternoon as well.  Now if only Connect-IPPSSession could get some REST love so I could stop having to use Basic auth for unattended... that would be great too.  Best would be somehow SCC PowerShell gets sunset and MS Graph takes over for that.
