### ISSUE TITLE
Instructions for installation AND uninstallation??

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/office-docs-powershell#7345]
Installation (https://pnp.github.io/powershell/articles/installation.html) and uninstallation (????) guidance should be referenced here. 

From this site: https://pnp.github.io/powershell/articles/installation.html there are no instructions for uninstallation !?!?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4caea3e-8503-e348-ad70-ea769e7ceecd
* Version Independent ID: 858766e1-3dc3-b00d-217f-adbab5b63867
* Content: [PnP.Powershell Module](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/sharepoint-pnp.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/sharepoint-pnp.md)
* Service: **sharepoint-powershell**
* GitHub Login: @erwinvanhunen
* Microsoft Alias: ****

**Comment by get-itips** [comment]
Hello @angoo-atea 

how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @angoo-atea Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
