### ISSUE TITLE
Link suggestion to troubleshoot why some Cmdlets are unavailable

### ISSUE THREAD

**Issue by v-chilso** [MicrosoftDocs/office-docs-powershell#7347]
Suggest to link to https://docs.microsoft.com/en-us/powershell/exchange/find-exchange-cmdlet-permissions?view=exchange-ps for troubleshooting why certain Cmdlets are not available after connecting to Exchange Online in (Windows/Core) PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@v-chilso, OK, done. I added a sentence and link to the this existing statement in the What do you need to know before you begin? section:

> After you connect, the cmdlets and parameters that you have or don't have access to is controlled by role-based access control (RBAC). For more information, see [Permissions in Exchange Online](https://docs.microsoft.com/exchange/permissions-exo/permissions-exo).

Due to publishing problems on our end, you might not see the updated topic for a while.

Thanks for the feedback.

Closing
