### ISSUE TITLE
-RemoveSharePointLocationException

### ISSUE THREAD

**Issue by jluce512** [MicrosoftDocs/office-docs-powershell#7348]
When you remove a site from the -removeSharePointLocationException it never goes back on retention.

**Comment by get-itips** [comment]
Hello @jluce512 how are you?
Do you refer to which article? can you put the URL here? maybe the article for Set-DlpCompliancePolicy?
I created a test dlp policy, chose All SharePoint sites and excluded a site, and then successfully removed the site using the parameter removeSharePointLocationException, let me know if I understood you correctly.
Thanks

**Comment by jluce512** [comment]
The article I was referring to is set-retentioncompliancepolicy I set one to addsharepointlocationexception did some maintenance on some file versions, then reran the script with a removesharepointlocationexception.  The site is removed, but when you check the site in SharePoint Admin Center you no longer see This Site has a compliance policy to block deletion:

The site below has never had any exception.  The site I did put the exception to had this notification before the site was excluded.  When the site was removed from the exclusion that notification does not reappear.
[cid:image001.png@01D70F3D.167F9280]

**Comment by get-itips** [comment]
> The article I was referring to is set-retentioncompliancepolicy I set one to addsharepointlocationexception did some maintenance on some file versions, then reran the script with a removesharepointlocationexception. The site is removed, but when you check the site in SharePoint Admin Center you no longer see This Site has a compliance policy to block deletion: The site below has never had any exception. The site I did put the exception to had this notification before the site was excluded. When the site was removed from the exclusion that notification does not reappear. 

Hello @jluce512 how are you? Hope you are doing good, in that case, the best option would be to open a support ticket to understand why the site did not get the policy to block deletion again, as here we are limited to documentation changes and fixes.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @jluce512 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
