### ISSUE TITLE
Query Example and CAML reference

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/office-docs-powershell#7349]
Please add a real example for using -Query (example 6).  The existing example is essentially useless.  Also, the parameter section references CAML but the related links section doesn't mention it at all.  Maybe link to https://docs.microsoft.com/en-us/sharepoint/dev/schema/query-schema

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b777fcfe-c7da-0165-d6ac-74fc2db07daf
* Version Independent ID: 12045879-94af-fd90-66a0-8f3db00a579f
* Content: [Get-PnPListItem (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPListItem.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPListItem.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @Skatterbrainz How are you?
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Skatterbrainz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
