### ISSUE TITLE
-CompleteAfter and -StartAfter are not available in Exchange 2019, Exchange 2016 and Exchange 2013

### ISSUE THREAD

**Issue by admartini200** [MicrosoftDocs/office-docs-powershell#7352]
[-CompleteAfter and -StartAfter are not available in Exchange 2019, Exchange 2016 and Exchange 2013 - please update article]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68325010-9605-22b4-4b6c-b61f332dc321
* Version Independent ID: 47ce5d33-5483-8c8e-2aa2-532178bf466a
* Content: [New-MigrationBatch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@admartini200, I checked Exchange 2013 CU23, Exchange 2016 CU19, and Exchange 2019CU8, and they're available to me:

```powershell
[PS] C:\>Get-ManagementRoleEntry *\New-MigrationBatch -Parameters CompleteAfter,StartAfter

Name                           Role                      Parameters
----                           ----                      ----------
New-MigrationBatch             Migration                 {AllowIncrementalSyncs, AllowUnknownColumnsInCSV, ArchiveOn...
```

Can you confirm or deny?

 Whether those parameters are supposed to be available or whether they function is a different story.

**Comment by chrisda** [comment]
#7352 mentions that these parameters actually work in Exchange 2019 CU8. If that's the case I can add this text to the description:

> This parameter is available or functional only in Exchange 2019 or Exchange Online.

Comments?

**Comment by chrisda** [comment]
@admartini200, I assume silence is golden, so I'm going to close the issue.

If you have more information, feel free to reopen this issue.

Thanks for the feedback.

Closing

**Comment by t-deman** [comment]
Exchange 2019 CU11.  -startAfter is not proposed/not recognized on the command "set-migrationbatch". 

But it's present in the Help.

**Comment by chrisda** [comment]
@t-deman, I have an Exchange 2019 CU11 Mar22SU test server, and they're definitely available. Per the previous discussion, whether they're supposed to be available or whether they work is another story.
