### ISSUE TITLE
Set "End meetings early or start late" on individual mailboxes

### ISSUE THREAD

**Issue by RichMath** [MicrosoftDocs/office-docs-powershell#7357]
It would seem that the "Set-MailboxCalendarConfiguration" would be a logical place to set up this option. It can be done from OWA and Outlook, and it looks like the setting (once made) effects the change for the mailbox no matter if the client uses OWA or Outlook, or if they access the mailbox from a client machine different to the one on which the change was made. That would imply that the option is made either on the mailbox or on the AD object.

Will this setting be incorporated in this cmdlet's parameter set?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9153892d-ff85-6117-7566-3ce55fff57c9
* Version Independent ID: 463efb5b-6bb0-97eb-bd51-f2e12cefc703
* Content: [Set-MailboxCalendarConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxcalendarconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
@RichMath - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Microsoft 365 better. They keep a close tab on user feedback, and it would be awesome if you could add your voice in User Voice https://office365.uservoice.com/.

You might find others have made a similar request that you can add to or open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by yogkumgit** [comment]
@RichMath Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
