### ISSUE TITLE
PS module install command

### ISSUE THREAD

**Issue by nalhemyariirexorg** [MicrosoftDocs/office-docs-powershell#7363]
[Enter feedback here]
is missing from the page, will be useful to add it so we can start using the commands

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f98d029-8c45-af5e-1527-290690fa1283
* Version Independent ID: e7833ab4-d2b1-5840-4f2c-dda86599d3af
* Content: [MicrosoftWhiteboardAdmin Module](https://docs.microsoft.com/en-us/powershell/module/whiteboard/?view=whiteboard-ps)
* Content Source: [whiteboard/whiteboard-ps/whiteboard/whiteboard.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/whiteboard/whiteboard-ps/whiteboard/whiteboard.md)
* Service: **whiteboard-powershell**
* GitHub Login: @tbrosman
* Microsoft Alias: **tbrosman**

**Comment by get-itips** [comment]
Hello, @nalhemyariirexorg thanks for reporting!
