### ISSUE TITLE
This page would benefit from more detail on how to install pre-requisites and get started

### ISSUE THREAD

**Issue by terryclancy** [MicrosoftDocs/office-docs-powershell#7364]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10052620-9909-c335-1913-fdf9db8ab16b
* Version Independent ID: e4be7843-4540-96fd-dcd8-09d6b91a4249
* Content: [Basic auth - Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/basic-auth-connect-to-exo-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@terryclancy, the connection method described in that topic is on the way out (Basic auth). The current method (and at some point, the only method when Basic auth connections are disabled) is described in [Connect to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell) and it's ancillary topics:

[App-only authentication for unattended scripts in the EXO V2 module](https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2).

[About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2)

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @terryclancy Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
