### ISSUE TITLE
Get-EXORecipientPermission does not work with Global Reader permission

### ISSUE THREAD

**Issue by pmhesse10p** [MicrosoftDocs/office-docs-powershell#7365]
We have created a [Global Reader](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#global-reader) account in order to run some PowerShell scripts to help with maintenance and security reviews.

One of the tools we are running is the [CrowdStrike CRT](https://github.com/CrowdStrike/CRT), a reporting tool that examines Azure Active Directory and Exchange Online, and creates lists of hard-to-find or hard-to-expose permissions and settings. 

In CRT, one of the commands, "SendAsGranted", runs this command to do Get-EXORecipientPermission against every mailbox in the domain. The specific line is:
`$DelegateSendPerms += Get-EXOMailbox -ResultSize Unlimited -ErrorAction SilentlyContinue | Get-EXORecipientPermission -ErrorAction Stop | Where-Object {$_.Trustee -ne "NT AUTHORITY\SELF"}`

When running this script as a Global Administrator, it works. When running the script as a Global Reader, it fails. 

I ran the command `Get-EXORecipientPermission -UserPrincipalName user@domain.name` manually as the Global Reader account and this was the output (after a substantial delay):

> Get-EXORecipientPermission : Error while querying REST service. HttpStatusCode=401
> ErrorMessage={"error":{"code":"Unauthorized","message":"User is not allowed to call
> Get-RecipientPermission","innererror":{"message":"User is not allowed to call
> Get-RecipientPermission","type":"Microsoft.Exchange.Admin.OData.Core.ODataServiceException"}}}
> At line:1 char:1
> \+ Get-EXORecipientPermission -UserPrincipalName user@domain.na ...
> \+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     \+ CategoryInfo          : ProtocolError: (:) [Get-EXORecipientPermission], RestClientException
>     \+ FullyQualifiedErrorId : An error occurred while processing this request.,Microsoft.Exchange.Management.RestApiCl
>    ient.GetExoRecipientPermission

I believe that the Get-EXORecipientPermission command should be able to be run as Global Reader, and this should be fixed.

**Comment by dariomws** [comment]
Hi @pmhesse10p, thank you for your feedback.

I tested it and found that the Get-RecipientPermissions cmdlet is not available as Global Reader neither. Here we are limited to documentation issues and improvements. To request features updates or additions, I have to redirect you to another channel.

I know the product teams are always looking for user feedback and how to make Exchange Online better. They keep a close tab on user feedback, and it would be awesome if you could add your voice in User Voice https://office365.uservoice.com/.

You might find others have made a similar request that you can add to or open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by yogkumgit** [comment]
@pmhesse10p Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Comment by pmhesse10p** [comment]
> Hi @pmhesse10p, thank you for your feedback.
> 
> I tested it and found that the Get-RecipientPermissions cmdlet is not available as Global Reader neither. Here we are limited to documentation issues and improvements. To request features updates or additions, I have to redirect you to another channel.
> 
> I know the product teams are always looking for user feedback and how to make Exchange Online better. They keep a close tab on user feedback, and it would be awesome if you could add your voice in User Voice https://office365.uservoice.com/.
> 
> You might find others have made a similar request that you can add to or open a new one. Let us know here if you do so we can up-vote your request.
> 
> Thank you for your contribution to make the docs better! Much appreciated!

Unfortunately that uservoice site seems to be shut down. Any other places to raise this request?

**Comment by dariomws** [comment]
In addition to the suggested channels you have already seen, you can use the [product team's blog](https://techcommunity.microsoft.com/t5/exchange-team-blog/bg-p/Exchange).
