### ISSUE TITLE
Prequisites?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/office-docs-powershell#7366]
"This cmdlet is available only in the cloud-based service." What does that mean? I.e. I am connecting to Exchange Online from an on-premises computer, but the cmdlet is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75b757c9-b775-8294-91f7-870bead6a907
* Version Independent ID: 54ebab36-97bb-cd9f-6eb2-12198af885e2
* Content: [Search-UnifiedAuditLog (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/search-unifiedauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@andrePKI, the cloud-based service typically means Exchange Online PowerShell; if a cmdlet is available in Security & Compliance Center PowerShell only, we'll call that out as such.

If you are well and truly connected to Exchange Online PowerShell, it comes down to permissions (role-based access control, a.k.a. RBAC). Taken from [this topic](https://docs.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions), run the following command to see the role group memberships that give access to that cmdlet:

```powershell
$Perms = Get-ManagementRole -Cmdlet Search-UnifiedAuditLog; $Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}
```
This is the output from two different organizations that I have access to:

```powershell
Role       RoleAssigneeType RoleAssigneeName
----       ---------------- ----------------
Audit Logs RoleGroup        Compliance Management
Audit Logs RoleGroup        Organization Management
Audit Logs RoleGroup        Records Management

Role                 RoleAssigneeType RoleAssigneeName
----                 ---------------- ----------------
View-Only Audit Logs RoleGroup        Compliance Management
View-Only Audit Logs RoleGroup        Organization Management
```

So, you need to be a member of the Compliance Management, Organization Management, or Records Management role groups to see the cmdlet.

To see if you have any of the required roles assigned to you, replace <UserIdentity> with your username and run the following command:

```powershell
Get-ManagementRoleAssignment -RoleAssignee <UserIdentity> -Delegating $false | Format-Table -Auto Role,RoleAssigneeName,RoleAssigneeType
```

**Comment by andrePKI** [comment]
Excellent information, thank you! Unfortanately I can't run Get-ManagementRoleAssignment due to lacking permissions as well - a kind of chicken-egg situation here. But at least I now have something I can ask from my Exchange admins ;-)
Would be nice though if the text "You need to be assigned permissions..." stood out a little more. We lazy people don't read that well but scan the page and pick out the promising bits, like in which module the cmdlet resides, then jump right off to the examples...

**Comment by chrisda** [comment]
@andrePKI, I'll take that under advisement. As you can imagine, that's a lot of work across ~1300 cmdlet reference topics...

 Thanks for the feedback.

Closing
