### ISSUE TITLE
Exchange Hybrid mode - Remote\Office 365 mailbox: Set-Mailbox cmdlet throws no error when updating only the primary SMTP address

### ISSUE THREAD

**Issue by TalismanM** [MicrosoftDocs/office-docs-powershell#7372]
1. Create Remote\Office 365 mailbox.
2. Add second smtp address.
3. Wait for synchronization to complete.
4. Connect to Exchange Online via PowerShell.
5. Use cmdlet Set-Mailbox to set the second smtp address as Primary\Reply address.
**Result:** No error. The second smtp address is set as Primary\Reply address.
6. Run synchronization and wait till it completes.
**Result:** The changes made on step 5 will be reverted and the Primary\Reply address specified in the on-premises AD will be set.

Note: I understand that I need to update the Remote\Office 365 mailbox in on-premises AD or using on-premises Exchange. And I have scripts which execute updates in on-premises Exchange when update in Online Exchange fails with a specific error. But when updating only the primary SMTP address no errors occur. It is by design or a BUG?

Note: You can also change the Primary\Reply address to another one in the Online Exchange admin center and the ADSync problem described above will reoccur.

**Comment by SergeTechnician** [comment]
Facing the very same issue. Could anyone provide any insight on this point? Seems to be quite a major bug.

**Comment by mr-spacecat** [comment]
@yogkumgit Any updates? The same issue happens when manually updating proxy addresses of AADConnect-synced users in hybrid environments.
1. Add a new smtp address to a user mailbox in Exchange Online admin center.
2. Run AAD Ccnnect delta sync cycle.
3. The proxyAddresses attribute reverts to old value from on-premises. New smtp address is GONE!

Exchange should forbid changing proxyAddresses of synced users online. Maybe this writeback mechanism is supposed to handle the case, but it doesn't work https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized#exchange-hybrid-writeback.

**Comment by dariomws** [comment]
@TalismanM and @mr-spacecat - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Here we are limited to documentation issues and improvements.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @TalismanM Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
