### ISSUE TITLE
New-ComplianceSearch command not importing with ExchangeOnlineManagement module

### ISSUE THREAD

**Issue by ChrisB9907** [MicrosoftDocs/office-docs-powershell#7376]
Installed the module on both PowerShell 5.1 and on PowerShell 7, that did not help. It almost seems like it doesn't want to import  some of the commands. Tested this with the current version 2.0.4 and the preview 9 version of 2.0.4. Screenshot shows a command that is found here https://docs.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps#how-do-you-know-this-worked to test the connection worked, using the method of connecting with MFA found in the same article.

![image](https://user-images.githubusercontent.com/60661129/110049456-b2ebb680-7d06-11eb-9ddf-0d20673e9f2d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f7f0a23-5b87-02f2-5bce-eddc3413f7f4
* Version Independent ID: 6694e76a-b1e0-9cc6-08ab-beb0cf388e75
* Content: [New-ComplianceSearch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ComplianceSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by ChrisB9907** [comment]
Quick findings update, so it appears that the working command and all other commands imported by the Connect-IpPsSession command go to a temp directory.

![image](https://user-images.githubusercontent.com/60661129/110050742-66ee4100-7d09-11eb-801f-4eab0d738d68.png)

**Comment by chrisda** [comment]
@ChrisB9907, a couple of things:

If you connect successfully without connection errors, then it's most likely a role based access control (RBAC) issue. For the New-ComplianceSearch cmdlet, you need the Compliance Search role, which according to the [permissions topic](https://docs.microsoft.com/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center) is assigned to the following role groups in the Security & Compliance Center by default:

  - Compliance Administrator
  - Compliance Data Administrator
  - eDiscovery Manager
  - Organization Management
  - Security Operator

If you're getting connection errors, check your prerequisites in [Prerequisites for the EXO V2 module](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#prerequisites-for-the-exo-v2-module).

**Comment by ChrisB9907** [comment]
I have security administrator role on my account, which I thought covers it. Interesting enough, just tried the command and it is now showing up..... the other admin who tried it with me yesterday said it is showing up for him as well now. No changes to roles or anything else was made as far as we know.

**Comment by chrisda** [comment]
@ChrisB9907, I'm glad it worked out. Back in my admin days, when something suddenly started working again, my explanation was "unusual sunspot activity". It sounds like there was some kind of backend issue that was corrected.

Thanks for the feedback.

Closing
