### ISSUE TITLE
ConfigurationOnly backup often needs "-Force"

### ISSUE THREAD

**Issue by cloudgreen** [MicrosoftDocs/office-docs-powershell#7378]
I believe some information about the following should be added:

If the farm is medium sized or bigger, you usually have to use the **-Force** parameter when doing a **ConfigurationOnly** backup. This is because SharePoint miscalculates the size of the backup to include basically everything, even though the **ConfigurationOnly** parameter is specified. This took me ages to figure out.

I am using SharePoint 2016.

For reference, see:
https://social.technet.microsoft.com/Forums/en-US/3356f9a3-8b5b-4970-b400-3da34fa69c4d/backup-sharepoint-2010-farm-configuration-settings-only-get-an-error-for-not-enough-disk-space-when?forum=sharepointadminprevious

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59323fec-1d97-74d4-e815-ed2c941dd8bd
* Version Independent ID: c292dbf7-d1c5-7a3b-cc32-0d9b8fb06a8a
* Content: [Backup-SPFarm (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/backup-spfarm?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Backup-SPFarm.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Backup-SPFarm.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @cloudgreen 
How are you? Actually, there is a note about that currently in the article:

> ### -Force
> Specifies to proceed with a backup operation even if the estimation is that the backup directory does not have sufficient space to hold the entire backup.

Thank you for your feedback.

**Comment by cloudgreen** [comment]
Hi @get-itips!

All good, thank you. I hope you are well too. :)

The existing note is good, but it is too vague. I think it needs to be clearer that _-ConfigurationOnly_ often (always?) wrongly estimates the backup size to be way too big, and that the only way to be able to run the _-ConfigurationOnly_ backup at all is to also use _-Force_. This took me hours to figure out, and I'm not alone, as you can see by the forums... :)

I see two good options:

1. The best option is that the _-ConfigurationOnly_ switch includes a small notice about the estimation problem, and that -Force needs to be used

or

2. The -Force note could say:

**-Force**
"Specifies to proceed with a backup operation even if the estimation is that the backup directory does not have sufficient space to hold the entire backup. Note that a _-ConfigurationOnly_ backup often miscalculates the backup to be a lot bigger than it actually is, erroneously including content databases in the estimate, so _-Force_ has then to be used to be able to execute it at all."

Thanks for considering it!

**Comment by get-itips** [comment]
Will propose an improvement to the article and let's see if it gets approval.
Thanks @cloudgreen
