### ISSUE TITLE
ComplianceSearchAction deleted but not gone.

### ISSUE THREAD

**Issue by vitorbencini** [MicrosoftDocs/office-docs-powershell#7381]
When you remove a compliance search action with **Remove-ComplianceSearchAction** cmd the job disappears from eDiscovery however I am unable to submit another search action. Best scenario would be if a deleted search actions is deleted from front-end and backend as well. I guess this has to do with the maximum concurrent exports per user of 3 reported here. 
https://docs.microsoft.com/en-us/microsoft-365/compliance/limits-ediscovery20?view=o365-worldwide 

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad8adee-7f9d-757b-2069-95ecab232747
* Version Independent ID: c71194df-8f65-15aa-3ed2-b370b8c3f629
* Content: [New-ComplianceSearchAction (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearchaction?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@vitorbencini, do you have a content update in mind that would help with this? If not, it sounds like you're asking for a feature update, which is best done at <https://office365.uservoice.com/>.

**Comment by yogkumgit** [comment]
@vitorbencini Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
