### ISSUE TITLE
ComplianceSearchAction clear backend status/errors

### ISSUE THREAD

**Issue by vitorbencini** [MicrosoftDocs/office-docs-powershell#7382]
When you submit a New-ComplianceSearchAction it may take several hours to complete a export job and that is fine. However  when a Content Match Query syntax is correct but it conflicts with backend capabilities, it may not always be clear the problem is caused by a query or the parameter you have in your search, perhaps a more clear error would help that. Microsoft engineer instructed to separate query and correct, which helped, but don`t want to raise a case for every query that does not match the backend capabilities. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad8adee-7f9d-757b-2069-95ecab232747
* Version Independent ID: c71194df-8f65-15aa-3ed2-b370b8c3f629
* Content: [New-ComplianceSearchAction (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearchaction?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@vitorbencini, do you have a content update in mind that would help with this? If not, it sounds like you're asking for a feature update, which is best done at <https://office365.uservoice.com/>.

**Comment by yogkumgit** [comment]
@vitorbencini Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
