### ISSUE TITLE
Set-MailboxRegionalConfiguration error in example

### ISSUE THREAD

**Issue by atki-tb** [MicrosoftDocs/office-docs-powershell#7385]
Example 3 will throw an error due to bad date format:

Set-MailboxRegionalConfiguration -Identity "Alice Jakobsen" -Language da-dk -DateFormat "dd-mm-yyyy" -LocalizeDefaultFolderName

Suggested fix:

Set-MailboxRegionalConfiguration -Identity "Alice Jakobsen" -Language da-dk -DateFormat "dd-MM-yyyy" -LocalizeDefaultFolderName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573e63b4-b27b-5b7b-9269-78d308fd64d3
* Version Independent ID: 57b35909-0381-1181-58bb-2262c33576d1
* Content: [Set-MailboxRegionalConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxregionalconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxRegionalConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-MailboxRegionalConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@atki-tb, fixed as you described. In the future, you too can make changes like this directly without opening a GitHub Issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
