### ISSUE TITLE
This command isn't part of Exchange Modules

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/office-docs-powershell#7387]
Which version of the Exchange Module includes this function?

PS C:\> Get-ExternalInOutlook
Get-ExternalInOutlook : The term 'Get-ExternalInOutlook' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-ExternalInOutlook
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ExternalInOutlook:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d1a9469-a3f4-22ea-0c6a-9ac7be12d4cf
* Version Independent ID: e0646316-d374-aee7-49e9-7145354beb1d
* Content: [Get-ExternalInOutlook (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-externalinoutlook?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-ExternalInOutlook.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-ExternalInOutlook.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dneto-ame** [comment]
Same here.

**Comment by chrisda** [comment]
Know issue. Released very, very recently during the middle of a big publishing outage that we had. Availability of the Get/Set-ExternalInOutlook cmdlets is being worked on.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this information. @NickDorak Kindly have patience, update will be available in near future.  We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
