### ISSUE TITLE
Setting TransferTarget values

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#7389]
When querying a user's online voicemail settings, the TransferTarget attribute is a System.Object.  Typically, in the Set cmdlet you also have to pass an object to set an object, but when I attempt this, I get an error

$o=Get-CsOnlineVoicemailUserSettings -Identity 'user@domain.com'

Set-CsOnlineVoicemailUserSettings -Identity 'user@domain.com' -TransferTarget $o.TransferTarget

A transfer target with specified URI (Microsoft.Rtc.Management.Hosted.Voicemail.Models.TransferTarget) was not found
or does not belong to your tenant.
    + CategoryInfo          : NotSpecified: (:) [Set-CsOnlineVoicemailUserSettings], OnlineVoicemailCmdletException
    + FullyQualifiedErrorId : Unexpected exception encountered while executing cmdlet.,Microsoft.Rtc.Management.Hosted
   .Voicemail.SetCsOnlineVoicemailUserSettingsCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

I discovered that this works for users

Set-CsOnlineVoicemailUserSettings -Identity 'user@domain.com' -TransferTarget 'sip:anotherUser@domain.com'

and this works for the TelUri

Set-CsOnlineVoicemailUserSettings -Identity 'user@domain.com' -TransferTarget '18003334444'

but any attempts to try and set values for CallQueue or AutoAttendant do not work

Some examples of how to do this would be really useful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8aee06d-30f5-4dd9-4d65-82cfca32849b
* Version Independent ID: fa87b9ae-bea0-17cd-c5a7-9efaac8f7392
* Content: [Set-CsOnlineVoicemailUserSettings (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoicemailusersettings?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineVoicemailUserSettings.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @sarollins how are you?
I see that you are passing an object, -TransferTarget is expecting a String (like the other examples that you shared), what happens if you use a String to specify the CQ or AA?
Thanks

**Comment by sarollins** [comment]
This is what I get when setting to an Auto Attendant

Set-CsOnlineVoicemailUserSettings -Identity ***@***.***' -TransferTarget '24FCA582-2B31-435A-B68E-827358C246A3'
A transfer target with specified URI (24FCA582-2B31-435A-B68E-827358C246A3) was not found or does not belong to your
tenant.
    + CategoryInfo          : NotSpecified: (:) [Set-CsOnlineVoicemailUserSettings], OnlineVoicemailCmdletException
    + FullyQualifiedErrorId : Unexpected exception encountered while executing cmdlet.,Microsoft.Rtc.Management.Hosted
   .Voicemail.SetCsOnlineVoicemailUserSettingsCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com


And to a Call Queue

Set-CsOnlineVoicemailUserSettings -Identity ***@***.***' -TransferTarget 'A9AF4823-F9CA-47E7-99A7-6CAEA2B9F563'
A transfer target with specified URI (A9AF4823-F9CA-47E7-99A7-6CAEA2B9F563) was not found or does not belong to your
tenant.
    + CategoryInfo          : NotSpecified: (:) [Set-CsOnlineVoicemailUserSettings], OnlineVoicemailCmdletException
    + FullyQualifiedErrorId : Unexpected exception encountered while executing cmdlet.,Microsoft.Rtc.Management.Hosted
   .Voicemail.SetCsOnlineVoicemailUserSettingsCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

**Comment by get-itips** [comment]
Hello @sarollins 
When I specified the resource account identity associated with the CQ or AA I got a different error 

> The application (fbae3717-19ab-4121-890e-4exxxbcd33) is currently not supported for transfer target.

Will try to confirm this and in any case adjust the article.

Thanks

**Comment by shivtorov** [comment]
looks like it is the documentation issue.
we need to know the correct format for TransferTarget parameter.

When I set transfer destination using GUI, the values for `CallAnswerRule` and `TransferTarget` are as follows:

```
VoicemailEnabled                         : True
PromptLanguage                           : en-AU
OofGreetingEnabled                       : False
OofGreetingFollowAutomaticRepliesEnabled : False
OofGreetingFollowCalendarEnabled         : False
ShareData                                : False
CallAnswerRule                           : PromptOnlyWithTransfer
DefaultGreetingPromptOverwrite           :
DefaultOofGreetingPromptOverwrite        :
TransferTarget                           : TenantId=931beaf2-XXXX-XXXX-XXXX-563743d082fc, SipUri=, TelUri=, ObjectId=0180c25a-0786-XXXX-XXXX-aed6ebda62b7, Type=ApplicationEndpoint
```

Currently, documentation says "Value of this parameter should be a SIP URI of another user, an auto attendant, or a hunt group (call queue) in your organization" and there are two issues here:

* auto attendants and hunt groups don't have SIP URIs (only their resource accounts have SIP URI)
* cmdlet does not actually accept SIP URI of the resource accounts

@sarollins , if your auto-attendants/call-queues have a phone number associated, then you can transfer call to that phone number for now:

```
Set-CsOnlineVoicemailUserSettings -Identity sip:user1@domain.com -CallAnswerRule PromptOnlyWithTransfer -TransferTarget +123456789
```

**Comment by get-itips** [comment]
thanks @shivtorov 
@tomkau Tom, can you help me confirm the correct (if supported) way of setting a AA & CQ as TransferTarget?
Thank you!

**Comment by get-itips** [comment]
Hello everyone on this thread.
I have been further testing this.
It seems that currently, only users (also guests users) and telephone numbers can be set as TransferTargets. Will propose an edit to the article and we'll see if it gets approval.

**Comment by shivtorov** [comment]
In GUI, we definitely can specify call queue's resource account.

![image](https://user-images.githubusercontent.com/31003608/120810977-de44a280-c58e-11eb-8420-d6c7ec9ee9d7.png)

in PS, the configured destination looks like this:

![image](https://user-images.githubusercontent.com/31003608/120811273-22d03e00-c58f-11eb-9c06-7c0e872b0189.png)

**Comment by get-itips** [comment]
Thanks @shivtorov CQs did not appear in my tenant in the GUI, will review

**Comment by shivtorov** [comment]
> CQs did not appear in my tenant in the GUI

no, we can't specify **CQ** as target for anything. we specify target = **Resource Account** of CQ.
Resource accounts are the objects that returned by running Get-CsonlineapplicatoinInstace

![image](https://user-images.githubusercontent.com/31003608/120812291-30d28e80-c590-11eb-9880-61707f7ab3f1.png)

**Comment by get-itips** [comment]
Yes sorry, I meant the resource account, but it appears in the gui now, thanks.
What is clear is that, if I specify the id of the resource account, it is recognized by the cmdlet, as it returns in the error the applicationid associated but it says it is not currently supported (at least using PS)
