### ISSUE TITLE
Which versions of Outlook are supported

### ISSUE THREAD

**Issue by expta** [MicrosoftDocs/office-docs-powershell#7394]
Please list the minimum version of Outlook that supports this new feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba41cae3-da51-0a3d-1652-bce98452d4dc
* Version Independent ID: a2d20c87-6277-a868-3c2e-e2fe225e6f17
* Content: [Set-ExternalInOutlook (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-externalinoutlook?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-ExternalInOutlook.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-ExternalInOutlook.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@expta, the currently supported versions are Outlook on the web and Outlook for iOS and Android. I updated the topic with this information.

Thanks for the feedback.

Closing
