### ISSUE TITLE
Set-TeamPicture - Group Invalid Error

### ISSUE THREAD

**Issue by geekpankaj1811** [MicrosoftDocs/office-docs-powershell#7398]
Hello,

I am getting and error "Requested group is Invalid" while trying to set the Team Picture. I am passing the GroupID but in the error some additional guid is appended to the GroupID which is strange. 

Regards,
Pankaj BAJPAI
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9785a323-0f76-2cc5-8ccd-da9b83c29973
* Version Independent ID: 5629326e-995c-4494-811f-80a0bb042233
* Content: [Set-TeamPicture (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-teampicture?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-TeamPicture.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-TeamPicture.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @geekpankaj1811 
I tested this to see if we need to correct the documentation however I could use and set a Team Picture successfully, please be sure to be running the General Availability version (currently 2.0.0).
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @geekpankaj1811 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
