### ISSUE TITLE
All Skype For Business modules removed in MicrosoftTeams module since v2.0.0

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/office-docs-powershell#7399]
Hi all,
(CC: @pupara as the most frequent editor)

I'm certainly not the first one to go crazy, but it seems since you pushed v2.0.0 around 6-7 days ago, none of the Skype For Business Online PowerShell commands work when you only have the MicrosoftTeams module installed because they've been removed... (?)

Looking back at the SFBO documentation, there is this line - [LINK TO PAGE](https://github.com/pupara/office-docs-powershell/blob/patch-3/skype/skype-ps/skype/New-CsOnlineSession.md)
**With Teams PowerShell Module New-CsOnlineSession has been deprecated and is no longer required to connect Skype for Business Online. It has been replaced with Connect-MicrosoftTeams**

The line was added/changed at the same time of the V2 release around 6 days ago. This implies that we just have to run Connect-MicrosoftTeams, however doing that doesn't bring them back.

I know it would never work, but I've even tried running this with no luck
````PowerShell
$Session = Connect-MicrosoftTeams
Import-PSSession $Session
````

Is there something we're all missing? Because I can't see it in any documentation.
It's like everything has just been stripped out during the last merge by mistake.

**Comment by get-itips** [comment]
Hello @jantoney 
How are you?

You do not need to run Import-PSSession to import SfB cmdlets anymore, you just need to run Connect-MicrosoftTeams [as the article](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams) for that cmdlet specifies.

Thank you,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @jantoney Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
