### ISSUE TITLE
Certificate generation documentation error

### ISSUE THREAD

**Issue by duchaineo1** [MicrosoftDocs/office-docs-powershell#7400]
Hi there, 

In [https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps]( https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps) in the Appendix step 3 where the certificate is generated, if someone were to copy-paste the chunk of code the password of the .pfx would not be what the user intend since it's a string in double-quotes containing a $. Per [this documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.1) the $w0rd1234 part would be treated as a variable and expanded to nothing. Either it should be single-quotes or escaped but I feel an escaped $ risks to confuse new users.  

Thanks, 

Olivier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@duchaineo1, you described the problem accurately, but I would contend the point of those examples isn't to copy/paste and run directly; you're likely going to change the .pfx filename/path and use a password of your own choosing.

So, I modified the password to not contain a $.

Thanks for the feedback.

Closing
