### ISSUE TITLE
Occasional timeouts creating Teams from script

### ISSUE THREAD

**Issue by kpinel** [MicrosoftDocs/office-docs-powershell#7404]
This has improved since 1.1.11 where it happened all the time.

Received 2 automation errors yesterday morning. Both errors are the same time in different sessions. The next one created 1.5 hours later worked fine
>> TerminatingError(New-Team): "429 in /v1.0/teams/ endpoint"
>> TerminatingError(): "System error."
>> $global:?
False

The team is created and owner set but there appears to be a timeout responding back to the cmdlet so that it can continue.

Going to add some further debugging to the script to see if I can get further information as I haven't been able to replicate it at the command line.

**Comment by get-itips** [comment]
Hello @kpinel how are you? hope you are doing good.
Here, we are limited to documentation issues, is there an article that you see needs a correction? If not, I kindly recommend opening a support ticket.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @kpinel Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
