### ISSUE TITLE
Microsoft TEAMS Powershell module 2.0.0 extreme slow

### ISSUE THREAD

**Issue by biphi** [MicrosoftDocs/office-docs-powershell#7407]
I have installed the new MicrosoftTeams Powershell Module and a experience a extreme slowlyness with this new module.

The command get-csonlineuser took with the old module V1.1.6 around **~750 Milliseconds**

With Version 2.0.0 it takes about **~23 Seconds**

Please investigate as soon as possible...in larger environments this has a huge impact!

**Comment by biphi** [comment]
It's getting more and more worse. I need to switch back to the old Version as this new Module is breaking all scripts with high amount of Users 60k+

**Comment by get-itips** [comment]
Hello @biphi 
how are you? Hope you are doing good.
Here, we are limited to documentation issues, improvements and fixes, for this I would recommend opening a support ticket directly from your tenant.
Thank you

**Comment by biphi** [comment]
Hi,

thanks anyway.
I have opened a support ticket.
