### ISSUE TITLE
Add new Teams tabs

### ISSUE THREAD

**Issue by dan11990** [MicrosoftDocs/office-docs-powershell#7408]
Hi,

I am using MicrosoftTeams to create a new team in Teams. I can't find any way in MicrosoftTeams package to create a tab in the newly created team/channel? Is there any way to do it?

Thanks!

**Comment by get-itips** [comment]
Hello @dan11990 
How are you? Hope you are doing good.

Not in the MicrosoftTeams module, however, you can take a look at the PnP module, (please be aware I did not test it myself), there is a cmdlet that might do what you want https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpteamstab?view=sharepoint-ps

@yogkumgit please kindly close this.
