### ISSUE TITLE
Custom SearchBox on O365 Suitebar - Base CSS class hiding this in responsive mode

### ISSUE THREAD

**Issue by bhanuchintha** [MicrosoftDocs/office-docs-powershell#7409]
Hi Team,

We have hidden the Enterprise search box in our SP site collection and introduced the custom search box in the same position using SPFx extension & CSS. This is working perfectly fine in desktop mode. But, in responsive mode for screen resolutions below 1024px - Default SP css class ".s_b_beed2cf1" is hiding this with the style overflow:hidden. We can overide this style - But, as per the Microsoft best practices, we cannot override this css class and leads to non-compliance. We hope this is a product bug - Even after removing the enterprise search box using the PS command provided by MS - why the css class is not respecting the command that is being executed. Can you please let us know the work around here.

Set-PnPSearchSettings -SearchBoxInNavBar Hidden -Scope Site

![image](https://user-images.githubusercontent.com/19674673/110829761-7e579c00-82be-11eb-8238-a965b1829ada.png)

Thanks & Regards,
Bhanu
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5c408b-d870-3e9c-471d-d727ea8a1757
* Version Independent ID: 9959321e-6df3-8cb0-6b82-9c7bb8b49083
* Content: [Set-PnPSearchSettings (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsearchsettings?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSearchSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPSearchSettings.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by tseward** [comment]
Are you manipulating the Suitebar? If so, that's unsupported.

**Comment by bhanuchintha** [comment]
Hello @tseward , We are not manipulating the suite bar, we have just created a custom search box using the Fabric control in the SPFX extension (header) and used CSS to position our own custom search box in the place of OTB Enterprise search box. 

Now, All is working fine in desktop mode. But, in responsive mode for screen resolutions below 1024px - This custom search box getting hidden with the base css class definition. 

So, we feel that the PS script that is responsible for hiding the enterprise search box should actually take care of this base css class definition also to make overflow:hidden removed.

Thanks,
Bhanu

**Comment by yogkumgit** [comment]
@tseward

**Comment by tseward** [comment]
@bhanuchintha I would recommend opening this feedback up via a support case on admin.microsoft.com since this isn't a doc-related issue but rather a product one. That being said, using CSS overrides like you are do fall under the unsupported category.

I would look into the OOTB controls/options you have with the enterprise search (i.e. using the PnP Search v4 webparts, creating a custom search results page which the top search bar can be configured to point at).

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @bhanuchintha Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
