### ISSUE TITLE
Forgot Private Channel and Custom Apps Switch

### ISSUE THREAD

**Issue by lexyart** [MicrosoftDocs/office-docs-powershell#7413]
Hello,

on MicrosoftTeams Module V1.1.6 they forgot at new-team and set-team a switch for
AllowAddPrivateChannels and AllowUploadCustomApps.

Someone knows a trick or hiddenswitch?

Best regards

**Comment by get-itips** [comment]
Hello @lexyart how are you?
Is there any specific article in the documentation that you think needs a correction or a fix?
The team behind the Teams Ps module is adding new features with every release, in case you want your request to get to the team please open a suggestion here https://microsoftteams.uservoice.com/

**Comment by yogkumgit** [comment]
@lexyart  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
