### ISSUE TITLE
MailboxMovePublishedScopes error on New-OrganizationRelationship

### ISSUE THREAD

**Issue by andy-rwalker** [MicrosoftDocs/office-docs-powershell#7416]
When trying to create new Organization Relationship with more than 1 MailboxMovePublishedScopes getting error:

```powershell
Number of scopes specified '2' exeeds the allowed limit '1'.     + CategoryInfo          : InvalidOperation: (XXXXXXXX:String) [New-OrganizationRelationship], MailboxMigrationScopeOverLimitException     + FullyQualifiedErrorId : [Server=PR3P193MB0777,RequestId=0ba78611-c8d5-462a-87a9-c3871652ba93,TimeStamp=3/12/2021 2:33:59 PM] [FailureCategory=Cmdlet-MailboxMigrat     ionScopeOverLimitException] 3724FBFA,Microsoft.Exchange.Management.SystemConfigurationTasks.NewOrganizationRelationship     + PSComputerName        : outlook.office365.com
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61bdc5c8-91af-66ca-cc94-3127fea1b8c3
* Version Independent ID: 29ec4bea-aa01-8f74-f820-adb77c57aa4f
* Content: [New-OrganizationRelationship (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-organizationrelationship?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-OrganizationRelationship.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-OrganizationRelationship.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for  sharing this explanation. @andy-rwalker Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
