### ISSUE TITLE
Do not return all delegates

### ISSUE THREAD

**Issue by Mangego** [MicrosoftDocs/office-docs-powershell#7417]
[Enter feedback here]
The cmd-let do not return all user only a maximum of four users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e2f0b48-664e-1fd9-b208-3892b2a87bc3
* Version Independent ID: 7a0f90ee-22e4-75c8-7043-584c232ceb4d
* Content: [Get-CsUserDelegates (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csuserdelegates?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsUserDelegates.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsUserDelegates.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by get-itips** [comment]
Hello @Mangego 
How are you?
I tested this on my lab to see if we had to correct the article, the cmdlet returns correctly  more than four users, maybe you probably did not expand de property Delegates while getting the result?

`Get-CsUserDelegates -User meganb@contoso.com| select -ExpandProperty delegates`

Hope this helps you,

**Comment by Mangego** [comment]
Hello Andres
Thanks for your answer, I did try all commands I could think of but didn't get all members. But ended at last with this command: (Get-CSPersistentChatRoom -identity "name of chatroom" | select -expandproperty members) and that worked to.

/Magnus

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Mangego If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
