### ISSUE TITLE
Missing description for the -DomainName parameter

### ISSUE THREAD

**Issue by drdenson** [MicrosoftDocs/office-docs-powershell#7418]
Hi Team - appears to be a missing parameter description in this article for parameter DomainName.  Can this be corrected?  Please reach out to my MS alias if you have any questions.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb1bcd1-e164-db1e-e45a-dd0accd8afa6
* Version Independent ID: e08ff564-4170-905c-9e97-edf37e860b3f
* Content: [Set-AuthServer (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-authserver?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-AuthServer.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-AuthServer.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Dean, per our email conversation, if you don't have any input about this parameter, I'm closing the issue. It's a known fact that this (and many other parameters) are not documented. See the end of <https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429> about available vs. undocumented vs. missing.

Thanks for the feedback.

Closing
