### ISSUE TITLE
Get-CsOnlineUser Exception "Tenant Domain is empty"

### ISSUE THREAD

**Issue by spainja** [MicrosoftDocs/office-docs-powershell#7419]
With the MicrosoftTeams PowerShell module v2.0.0, New-CsOnlineSession is now deprecated and replaced by Connect-MicrosoftTeams. After a successful Connect-MicrosoftTeams, Get-CsOnlineUser returns the following error:

Exception calling "GetSteppablePipeline" with "1" argument(s): "Exception calling "GetRemoteNewCsOnlineSession" with
"1" argument(s): "Tenant Domain is empty""
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.0.0\net472\SfBORemotePowershellModule.psm1:9474 char:13
+             $steppablePipeline = $scriptCmd.GetSteppablePipeline($myI ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CmdletInvocationException

**Comment by get-itips** [comment]
Hello @spainja How are you? Hope you are doing good.
I've seen that error but when you use for example Connect-MicrosoftTeams using CBA, when you use interactive login the Skype cmdlets will work ok.
In any case, here, we are limited to documentation changes and fixes, will try to pass this feedback to the team behind the module.
Thank you

**Comment by spainja** [comment]
Thanks. I'd be happy to submit feedback to the developers as well. Would you please let me know where to do that? Jeff.

**Comment by get-itips** [comment]
> Thanks. I'd be happy to submit feedback to the developers as well. Would you please let me know where to do that? Jeff.

Please submit your inquiry here https://microsoftteams.uservoice.com/

**Comment by spainja** [comment]
Thanks. User Voice feedback submitted. You might consider adding a banner to the documentation that the MicrosoftTeams module v2.0.0 doesn't work properly with certain Skype for Business Online cmdlets when connecting with certificate authentication.

**Comment by get-itips** [comment]
@spainja Jeffry, thanks for your feedback!

**Comment by yogkumgit** [comment]
@spainja Thank you very much for your kind feedback and logging this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Comment by RowanAdvisors** [comment]
I mean this is the repo linked to on the Powershell Gallery.  So either include someone from the product team on this repo.  UserVoice or submitting a ticket to MS Support is useless.  I have at least 3 open tickets with support that have been open for > month.
