### ISSUE TITLE
Example section unfinished

### ISSUE THREAD

**Issue by VladimirGluten47** [MicrosoftDocs/office-docs-powershell#7422]
PowerShell example: "Insert example commands for example 1."
PowerShell description: "Insert descriptive text for example 1."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03316ed4-3574-15cd-3776-59ff6a363152
* Version Independent ID: b5a2130a-0443-ed77-e854-5c4039ebe93f
* Content: [Get-CsOnlineDialinConferencingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialinConferencingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDialinConferencingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by VladimirGluten47** [comment]
On second look the topic introduction and descriptions are also unfinished.

**Comment by shivtorov** [comment]
duplicate for #5240

**Comment by get-itips** [comment]
Thanks for reporting, yes, it has been a long-standing issue however I could get some more information and I'll propose an update to the article.
