### ISSUE TITLE
What Permissions is needed for Get-TeamChannel

### ISSUE THREAD

**Issue by BohrenAn** [MicrosoftDocs/office-docs-powershell#7423]
What Role is needet to run Get-TeamChannel

Teams Admin Roles
https://docs.microsoft.com/en-us/microsoftteams/using-admin-roles

PS C:\> Get-TeamChannel -GroupId 30dae3d8-97bf-430b-8be6-7867a6a079b3
Get-TeamChannel : Error occurred while executing
Code: NotFound
Message: Failed to execute Skype backend request GetThreadS2SRequest.
InnerError:
  RequestId: 24f81e6c-fb62-4aba-8148-f94a604cbbdc
  DateTimeStamp: 2021-03-15T15:28:44
HttpStatusCode: NotFound
In Zeile:1 Zeichen:1
+ Get-TeamChannel -GroupId 30dae3d8-97bf-430b-8be6-7867a6a079b3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-TeamChannel], ApiException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeamChannel

Example above with "Teams Communications Administrator"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a290dbfc-3b69-2be6-a4b7-71f3f03bd004
* Version Independent ID: 36d9cfe0-cf60-2fa1-41b4-6c6971042394
* Content: [Get-TeamChannel (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @BohrenAn 
How are you? Hope you are doing good.
I tested this in my lab, I was able to run successfully the `Get-TeamChannel` cmdlet using a "Teams Communications Administrator". Please be sure to be running the most up-to-date General Availability version of the Teams PowerShell module (2.0.0).
Hope this information helps you,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @BohrenAn Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
