### ISSUE TITLE
Missing parameter "-EnableCORS"

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#7430]
Hi, 

I was not able to found any clarification to parameter:
-EnableCORS

How that could be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88845a18-3c61-4321-f35a-7bedbe81cdc2
* Version Independent ID: 971d3596-6073-727b-ae99-39880f6d921f
* Content: [Set-CsAutodiscoverConfiguration (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csautodiscoverconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsAutodiscoverConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsAutodiscoverConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by get-itips** [comment]
Thanks for your feedback @Petri-X
