### ISSUE TITLE
Using the Token generated by AAD using MSAL.js, with Connect-MicrosoftTeams -AadAccessToken cmdlet

### ISSUE THREAD

**Issue by Sa3d94** [MicrosoftDocs/office-docs-powershell#7434]
I'm trying to get the user's consent in the client side using MSAL.js to be able to configure their Microsoft Teams in PowerShell Core.

I get the token successfully, but when i use it inside PowerShell Core with the cmdlet Connect-MicrosoftTeams -Aadaccesstoken -AccountID, the PowerShell prints the Tenant ID as follows, as if i am connected to Microsoft Teams(It doesn't tell me whether i am connected or not).

The Problem is that, when i try to Execute any cmdlet in the MicrosoftTeams Modules, it shows the below error

**When i use the token generated on the Client Side in  PowerShell Core**
`
Account             Environment Tenant                               TenantId

-------             ----------- ------                               --------

"Email is Here" AzureCloud  "Tenant_ID_isHere"  "Tenant_ID_isHere" 
`
**The error That i get when i execute any cmdlet**
`
Line |

9474 |              $steppablePipeline = $scriptCmd.GetSteppablePipeline($myI …

     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

     | Exception calling "GetSteppablePipeline" with "1" argument(s): "Exception calling "GetRemoteNewCsOnlineSession" with "1" argument(s): "Run either Connect-MicrosoftTeams or new-csonlinesession before running

     | cmdlets."" 
`

** Package.json**
`
"@azure/msal-angular": "^1.1.1",
    "@microsoft/microsoft-graph-client": "^2.1.0",
    "@microsoft/microsoft-graph-types": "^1.24.0",
 
`
**My Configuration**
`
export const OAuthSettings = {
appId:'My_App_ID',

  
     redirectUri: 'http://localhost:4200',
     scopes: [
       
"https://graph.microsoft.com/.default"

 ],

prompt : 'consent'
}; 
`
**The consent Prompt that the user Gets**
![Question](https://user-images.githubusercontent.com/60856679/111323935-b05f5a00-8640-11eb-94c6-b543a3231dd4.PNG)

I don't know what seems to be the issue, and according to my speculations, i think it might be one of the below scenarios

- The Access Token that gets generated using the MSAL.js can't be used with PowerShell Core  cmdlets (-AadAccessToken)
- I am using the wrong Permission API in my Azure Active Directory
- PowerShell Core doesn't support this kind of Authentication

Please help me to figure out whether this is possible to do or not, and if so please tell me how to achieve it.

**Comment by Sa3d94** [comment]
I gave my Application on Azure an API permission which is Directory.AccessAsUser.All, and i was able to login in PowerShell Core using the Connect-MicrosoftTeams -AadAccessToken cmdlets

I was able to run commands like Get-Team successfully, but i can't execute all cmdlets though. Is there any way that i can grant access to be able to execute cmdlet like Get-CsOnlinePSTNGateway  ?

**Comment by linlidialpad** [comment]
@Sa3d94 What is the permission/scope you are using to display the following permission (Access MicrosoftTeams and and Skype for Business data as the signed in user)?
![Screen Shot 2021-03-17 at 5 02 38 PM](https://user-images.githubusercontent.com/57730092/111554071-dcfb9a80-8742-11eb-89d9-3cab45c14ff0.png)

**Comment by linlidialpad** [comment]
+1 for the question. I was able to run `Get-Team` but not commands like `Get-CsOnlineUser` and `Set-CsUser`. Getting the same error as described in the issue. I'm wondering what's the scope/permission needed to ask user's for consent in order to run these old SkypeForBusiness commands. If this approach is not supported yet, do you have a timeline when this will work?

**Comment by linlidialpad** [comment]
@yogkumgit Any update on this or should I ask the question somewhere else? Would really appreciate your help on this.

**Comment by Sa3d94** [comment]
@linlidialpad The Permission that i'm using is Skype and Teams Tenant Admin API and the Scope is user_impersonation.

**Comment by Sa3d94** [comment]
> @yogkumgit Any update on this or should I ask the question somewhere else? Would really appreciate your help on this.

+1

**Comment by linlidialpad** [comment]
@Sa3d94 It's odd that I could find the `Skype and Teams Tenant Admin API` in the app's API permission page. Does it fall under `Microsoft Graph`  or `Skype for Business`? What's the uri for this scope? Thanks.

**Comment by vinayramegowda** [comment]
Hi @linlidialpad you can find the end point under all api's
![image](https://user-images.githubusercontent.com/53648006/112225425-e1fba500-8c80-11eb-9444-612570ea4007.png)

**Comment by get-itips** [comment]
Hello @Sa3d94 
How are you? hope you are doing good.
I could reproduce, and this was also reported in the past, although here we are limited to documentation changes, I will try to pass this information to the team behind the Ps module.
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Sa3d94 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
