### ISSUE TITLE
Analste

### ISSUE THREAD

**Issue by SABAHDEGU** [MicrosoftDocs/office-docs-powershell#7438]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b57b66-2364-0e9d-e627-5eeb77238675
* Version Independent ID: 78fd7932-06f9-37c7-8928-250b3884d89e
* Content: [Connect to Exchange servers using remote PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-servers-using-remote-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-servers-using-remote-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SABAHDEGU, what's the question or comment?

**Comment by chrisda** [comment]
Nothing to do.

Closing
