### ISSUE TITLE
Command not available in Exchange Online

### ISSUE THREAD

**Issue by OSuperfly** [MicrosoftDocs/office-docs-powershell#7442]
Hi Team,

I'm currently in the process migrating OnPrem Exchange public folders to M365.
My problem is, that the provided PowerShell script "Sync-ModernMailPublicFolders.ps1" referres to the EXO Powershell command "Remove-EXOSyncMailPublicFolder" but this seems not to be available anymore?

So the execution of "Sync-ModernMailPublicFolders.ps1" results in:

(translated)
RemoveMailEnabledPublicFolder : The name "Remove-EXOSyncMailPublicFolder" was not recognized as the name of a cmdlet, function, script file, or executable program. Check the spelling of the name or whether the path is correct (if included) and try again.

Other referred EXO cmds which are not available are:

- New-EXOSyncMailPublicFolder
- Set-EXOMailPublicFolder

I'm stuck in the migration so any help would be appreciated.
Oliver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a21a8d17-4e73-0bfb-4515-a89198a3179a
* Version Independent ID: cdb39b9e-e686-6115-9352-1e6b789fb537
* Content: [Remove-SyncMailPublicFolder (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-syncmailpublicfolder?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-SyncMailPublicFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-SyncMailPublicFolder.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by OSuperfly** [comment]
Hi chrisda,

thanks a lot for your hint and the explanation how the script handles the "Remove-SyncMailPublicFolder".
But...
unfortunately if I try to execute one of the cmdlets in the Exchange Online Powershell it is not found?!

Remove-SyncMailPublicFolder
![image](https://user-images.githubusercontent.com/80822304/111509851-70d26400-874d-11eb-98f3-01a39b4723ce.png)

Any ideas?

**Comment by chrisda** [comment]
No access to a cmdlet is typically a role based access control (RBAC) problem. If you're a member of the Organization Management role group in Exchange Online, you should have access to the cmdlet.

For more information, see <https://docs.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions>

**Comment by OSuperfly** [comment]
thx a lot for directing me in the right direction
![image](https://user-images.githubusercontent.com/80822304/111520328-4934c900-8758-11eb-8f39-5e0f03f8d21d.png)

**Comment by OSuperfly** [comment]
Hi chrisda,

thanks again for your professional analysis and quick help to solve my problem!

I couldn't have come to a solution to the problem any faster!
I think that the M365 support would not have been able to help (I opened a case but was stuck at 1st level). 

Thx
Oliver/Germany
