### ISSUE TITLE
Doesn't work if only one owner in the group!

### ISSUE THREAD

**Issue by mvanders** [MicrosoftDocs/office-docs-powershell#7444]
When trying to use this function when there is only 1 owner left in the group, it returns no error BUT ALSO DOESN'T REMOVE the owner from the group!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b326628d-0c5a-7c8f-b53d-44f0cec9cf09
* Version Independent ID: 70d36efc-45c3-db3f-8728-68e0f915f6d0
* Content: [Remove-PnPMicrosoft365GroupOwner (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpmicrosoft365groupowner?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPMicrosoft365GroupOwner.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPMicrosoft365GroupOwner.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @mvanders Marc,
How are you? to open PnP issues I need to kindly redirect you to [this other repo](https://github.com/pnp/powershell)
Thank you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @mvanders Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
