### ISSUE TITLE
Get-messagetracedetail requires MessagetraceId

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/office-docs-powershell#7445]
Get-messagetracedetail requires MessagetraceId (it will fail if not specified) but how (where) is a customer supposed to find the MessagetraceId. This article should specify where to find the MessageTraceId in my opinion.
(We should actually be able to run Get-MessageTraceDetail in combination with only the message-Id) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690f2980-4a4e-7efd-fe5e-29c551c02e6f
* Version Independent ID: 4ab7a6db-db36-c736-6ce5-2f0e74b0cf6a
* Content: [Get-MessageTraceDetail (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-messagetracedetail?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MessageTraceDetail.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MessageTraceDetail.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeroenDronkers, I added where to find the MessageTraceId value in the description of the MessageTraceId parameter.

The "We should actually be able to run Get-MessageTraceDetail in combination with only the message-Id" statement is more of a feature request, so you should do that at <https://office365.uservoice.com/>.

Thanks for the feedback.

Closing
