### ISSUE TITLE
Step 5 - Why do we need Azure AD roles?

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/office-docs-powershell#7451]
Can we include details on why the Azure AD roles are need?  Security teams are querying why API permissions assignment are not enough?  much like peopleAPI  access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @bakerm00, thank you for your feedback.

I think this is the explanation you are looking for:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/6992

Please let me know if you need more help.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @bakerm00 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
