### ISSUE TITLE
Adding a security group using email address doesn't work!

### ISSUE THREAD

**Issue by mvanders** [MicrosoftDocs/office-docs-powershell#7452]
When trying to execute the following, I got no error, but nothing gets added either:
Add-PnPGroupMember -Group "EG-TF-NCAP_P Visitors" -EmailAddress "_STAFF_EXTERNAL@acea.be"

It works for O365/M365 groups but not for security groups apparently?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a2a33fa-0ed0-9ffd-bd58-6a79633836df
* Version Independent ID: 4281e940-02e1-2c7b-1107-9b75fa29f24f
* Content: [Add-PnPGroupMember (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpgroupmember?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPGroupMember.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPGroupMember.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @mvanders 
How are you? to open PnP issues I need to kindly redirect you to [this other repo](https://github.com/pnp/powershell)
Thank you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @mvanders Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mvanders** [comment]
Dear @yogkumgit 
Thx, I posted it here: https://github.com/pnp/powershell/issues/538 following your recommendation.
