### ISSUE TITLE
Set-ExternalInOutlook should have the option to add domains and all subdomains to the allowed list

### ISSUE THREAD

**Issue by mariosaelikeit** [MicrosoftDocs/office-docs-powershell#7453]
Example should be:
Set-ExternalInOutlook -AllowList @{Add="*contoso.com"}

We can't be expected to manually add all subdomains to this allowed list.

**Comment by chrisda** [comment]
@mariosaelikeit, keep in mind that the maximum number of allow list entries is 30, so the number of domains that you need to enter isn't that bad.

You can add each domain like this:

```powershell
Set-ExternalInOutlook -AllowList @{Add="a.contoso.com","b.contoso.com","c.contoso.com",...}
```

or store each domain on a separate line in a text file:

```text
a.contoso.com
b.contoso.com
c.contoso.com
...
```

and then run these commands:

```powershell
$x = Get-Content "<PathAndFileName>.txt"
$x | foreach {Set-ExternalInOutlook -AllowList @{Add=$_}}

I'm not sure one method is better than the other, they both involve the list of domains (one list is vertical; the other horizontal).

If you're asking for a feature improvement to allow wildcards in the domain names (which could also affect the maximum number of entries), I suggest that you open a support case (all we can do here is update documentation).

**Comment by mariosaelikeit** [comment]
@chrisda, unfortunately 30 entries is not enough for my organisation. In any case, I understand your response. I was hoping that the wildcard scenario was forgotten in the documentation.

I will open a support case for this.
