### ISSUE TITLE
Parameter '-SkipImportSession' doesn't exist

### ISSUE THREAD

**Issue by hairyken** [MicrosoftDocs/office-docs-powershell#7455]
This page lists '-SkipImportSession' as a parameter from 2.0.4-Preview2, but this parameter isn't available in 2.0.4 (release version). Looks like the parameter has been removed from one of the previews...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13d88f18-3cc8-5f18-8d61-ff7f5fa4e314
* Version Independent ID: 60f9a029-69f3-e65c-6816-fbd414790ce3
* Content: [Connect-ExchangeOnline (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hairyken, confirmed. The parameter was in Preview2 and Preview6, but not in Preview9 and not in the public release of 2.0.4. I removed it from the topic.

Thanks for the feedback.

Closing
