### ISSUE TITLE
Minor typo in New-MailboxImportRequest documentation

### ISSUE THREAD

**Issue by rhymeswithmogul** [MicrosoftDocs/office-docs-powershell#7457]
In the documentation for the `New-MailboxImportRequest` cmdlet, you have the following snippet:

> `New-MailboxImportRequest User2 -FilePath \\server\share\User1.pst -IsArchive -TargetRootFolder /`
> 
> This example imports a .pst file into Kweku's archive folder[...]

The code block says "User2", but in the description, the user's name is given as Kweku.  While the example is still understandable, hese two names should be the same for clarity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1521bf62-ae37-50f3-3cf7-3ec385399f96
* Version Independent ID: 1ad16056-d5c5-a815-c6d6-8e38b96fdbd8
* Content: [New-MailboxImportRequest (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-mailboximportrequest?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-MailboxImportRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MailboxImportRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rhymeswithmogul, fixed. In the future, you too can make changes like this without the need to open an Issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
