### ISSUE TITLE
Connect-Exchangeonline -DelegatedOrganization not working

### ISSUE THREAD

**Issue by IldAmourBonjamin** [MicrosoftDocs/office-docs-powershell#7458]
I can connect to a delegated tenant using
```
$ConnectionUri = "https://ps.outlook.com/powershell-liveid?DelegatedOrg=$TenantDefaultDomainName"
    
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri $ConnectionUri -Credential $Office365Credentials -Authentication Basic -AllowRedirection 
Import-PSSession $Session -AllowClobber
```
This brings about it's own issues, it seems to me that this is the old way of doing it so I wanted to try using Connect-Exchange as it should support it according to the microsoft reference.

Reference: https://docs.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps

Steps to recreate: `Connect-ExchangeOnline -DelegatedOrganization $TenantDefaultDomainName -Credential $MyOffice365PartnerCredentials
`

Error message

```
New-ExoPSSession : One or more errors occurred.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.4\netFramework\ExchangeOnlineManagement.psm1:475 char
:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession
```

**Comment by chrisda** [comment]
@IldAmourBonjamin, this is a shot in the dark, but try using the -UserPrincipalName parameter with Connect-ExchangeOnline:

```powershell
Connect-ExchangeOnline -DelegatedOrganization $TenantDefaultDomainName -UserPrincipalName <MyOffice365PartnerUPN>
```

**Comment by IldAmourBonjamin** [comment]
> ```powershell
> -DelegatedOrganization $TenantDefaultDomainName
> ```

That works! And while connected with connect-exchangeonline commands like get-mailboxfolderstatistics also work as my hunch said! Quite a good shot in the dark, i've seen no reference of it needing that paramter to connect, any idea as to why it works?

**Comment by chrisda** [comment]
@IldAmourBonjamin, the EXO V2 module only connects using Modern authentication, but the password storage experience varies based on whether you use the UserPrincipalName parameter vs. Credential. Perhaps that has something to do with it.

**Comment by IldAmourBonjamin** [comment]
Works properly when adding the -UserPrincipalName parameter
