### ISSUE TITLE
Parameter StartMigrationAutomaticallyWhenNoScanIssue is ignored

### ISSUE THREAD

**Issue by gruering** [MicrosoftDocs/office-docs-powershell#7460]
Setting the parameter StartMigrationAutomaticallyWhenNoScanIssue to $false has no effect. When I register a new session for analysis only by using the ScanOnly and StartMigrationAutomaticallyWhenNoScanIssue parameters the migration immediately starts after a successful scan.

The global SpmtSettings.txt contains  "StartMigrationIfNoScanIssue": false.
The local GlobalSettings.csv file list Start Migration If No Scan Issue,True despite using the StartMigrationAutomaticallyWhenNoScanIssue $false parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e84226d2-c4c1-7cc0-3eab-dc0fe86fbaa9
* Version Independent ID: 73bb0f00-1909-6eb1-3a8c-247149480c9a
* Content: [Register-SPMTMigration (SharePointMigrationTool)](https://docs.microsoft.com/en-us/powershell/module/spmt/register-spmtmigration?view=spmt-ps)
* Content Source: [spmt/spmt-ps/spmt/Register-SPMTMigration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/spmt/spmt-ps/spmt/Register-SPMTMigration.md)
* Service: **spmt-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by gruering** [comment]
The problem only occurs when I am adding multiple tasks to the migration session. With a single task the migration does not start automatically.

**Comment by get-itips** [comment]
Hello @gruering 
How are you? Hope you are doing good.
Here, we are limited to documentation fixes and improvements, for your inquiry I would need to kindly ask you to open a support ticket directly from your tenant to report this.
Also please be sure to be running the latest general availability version of [SPMT](https://docs.microsoft.com/sharepointmigration/new-and-improved-features-in-the-sharepoint-migration-tool).
Thank you

**Comment by gruering** [comment]
Actually the documentation is wrong because the parameter does not what it is supposed to do.
I have implemented a workaround using reflection which allows me the override the wrong parameter.
Hopefully it gets fixed for another release.
