### ISSUE TITLE
Some cmdlets from MicrosoftTeams v2.0.0 are not working in Azure Function context

### ISSUE THREAD

**Issue by erwanolivo** [MicrosoftDocs/office-docs-powershell#7464]
Using PowerShell v7 in an Azure Function v3 context, I am not able to run some cmdlet from the MicrosoftTeams v2.0.0 modules (related to the old skypeonlineconnector modules), raising an exception :

`Exception calling "GetSteppablePipeline" with "1" argument(s): "Object reference not set to an instance of an object."`

It does work in my own environment.

### Example
___
```
Connect-MicrosoftTeams -Credential $cred

#Raise an exception
try {
    $user = Get-CsOnlineUser -Identity "herve.losse@###.onmicrosoft.com" -ErrorAction Stop
}
catch {
    Write-Host $_.Exception.Message
}

#Works
try {
    $teams = Get-Team -ErrorAction Stop
}
catch {
    Write-Host $_.Exception.Message
}
```

This issue is also referenced [here](https://github.com/Azure/azure-functions-powershell-worker/issues/611#issuecomment-802995902), in the Azure Function PowerShell project.

**Comment by get-itips** [comment]
Hello @erwanolivo 
How are you? hope you are doing good.
I could reproduce, and this was also reported in the past, although here we are limited to documentation changes, I will try to pass this information to the team behind the Ps module.
Thanks

**Comment by awill4457** [comment]
Hi Team, I would like to provide some assistance here in providing the information so we can get this resolved.
### Certificate based authentication
Generated a new enterprise application in Azure, following this guide https://learntechfuture.com/2020/08/17/connect-exchange-online-v2-via-certificate-auth-for-automation/ - for API permissions, assigned "Skype and Teams Tenant Admin API" - "application_access" and "application_access_custom_sba_appliance"

Ran Install-Module MicrosoftTeams
Ran _Connect-MicrosoftTeams -CertificateThumbprint CERTIFICATETHUMBPRINT -ApplicationId APPLICATIONID -TenantId TENANTID_
Ran _Get-TeamUser -GroupId GROUPID_ - ran successfully
Ran _Get-CsOnlineUser_
Got error:
**Exception calling "GetSteppablePipeline" with "1" argument(s): "Exception calling "GetRemoteNewCsOnlineSession" with "1" argument(s): "Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The WinRM client cannot process the request. The authentication mechanism requested by the client is not supported by the server or unencrypted traffic is disabled in the service configuration. Verify the unencrypted traffic setting in the service configuration or specify one of the authentication mechanisms supported by the server. To use Kerberos, specify the computer name as the remote destination. Also verify that the client computer and the destination computer are joined to a domain. To use Basic, specify the computer name as the remote destination, specify Basic authentication and provide user name and password. Possible authentication mechanisms reported by server: For more information, see the about_Remote_Troubleshooting Help topic.""At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.0.0\net472\SfBORemotePowershellModule.psm1:9474 char:13**

It seems very strange that when I run an almost identical command for Connect-ExchangeOnline with the same application and certificate, this works perfectly, and yet the teams powershell module does not work at all

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
> Hello @erwanolivo
> How are you? hope you are doing good.
> I could reproduce, and this was also reported in the past, although here we are limited to documentation changes, I will try to pass this information to the team behind the Ps module.
> Thanks

I could get some information from the team behind the module, they are aware of this and are working on it. Hope this information helps everyone here.
@yogkumgit please close this issue as it is not documentation-related. Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @erwanolivo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by danielbecker** [comment]
Just in case anyone else stumbles upon this issue: There's a new version of the package (2.3.1) that fixed the issue for me. https://www.powershellgallery.com/packages/MicrosoftTeams/2.3.1

**Comment by tsf89** [comment]
@danielbecker Can you shed a little more information about this? How are you connecting? And are Cs commands working?
I am doing exactly as @awill4457 is describing for a unattended powershell script. But even with version 2.3.1 of the Teams module, it is not working.

I can run for example Get-Team with no problems. But not for example Get-CsAutoattendant.
I am getting the following error:

`Get-CsOnlineSession : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following
error message : The WinRM client received an HTTP status code of 403 from the remote WS-Management service. For more in
formation, see the about_Remote_Troubleshooting Help topic.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\SfBORemotePowershellModule.psm1:63 char:22
+     $remoteSession = & (Get-CsOnlineSessionCommand)
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CsOnlineSession], PSRemotingTransportException
    + FullyQualifiedErrorId : PSRemotingTransportException,Microsoft.Teams.ConfigApi.Cmdlets.GetCsOnlineSession

Invoke-Command : Cannot validate argument on parameter 'Session'. The argument is null or empty. Provide an argument th
at is not null or empty, and then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\SfBORemotePowershellModule.psm1:1780 char:38
+ ...    -Session (Get-PSImplicitRemotingSession -CommandName 'Get-CsAutoAt ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Command], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeCommandCommand`

**Comment by danielbecker** [comment]
The only cmdlets I'm using are `Connect-MicrosoftTeams`, `New-CsOnlineVoiceRoute`, and `New-CsOnlineVoiceRoutingPolicy` for now.

**Comment by tsf89** [comment]
@danielbecker Could i get you to test if Get-CsAutoAttendant is returning any results for you or if you get the above error aswell?
If you get results, which API permissions have you given the Azure App you are using for the Powershell authentication?

**Comment by danielbecker** [comment]
As far as I know, I was provided with a new and clean account by our it team.

**Comment by danielbrowne** [comment]
I am experiencing the same problem. Using 2.3.2-preview I can connect and run newer commands such as Get-Team without a problem, but running the older commands such as Get-CsOnlineUser (which work correctly with basic auth) fail.

```
Get-CsOnlineSession : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The WinRM client cannot 
process the request. The authentication mechanism requested by the client is not supported by the server or unencrypted traffic is disabled in the service 
configuration. Verify the unencrypted traffic setting in the service configuration or specify one of the authentication mechanisms supported by the server.  To use 
Kerberos, specify the computer name as the remote destination. Also verify that the client computer and the destination computer are joined to a domain. To use 
Basic, specify the computer name as the remote destination, specify Basic authentication and provide user name and password. Possible authentication mechanisms 
reported by server: For more information, see the about_Remote_Troubleshooting Help topic.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.2\net472\SfBORemotePowershellModule.psm1:63 char:22
+     $remoteSession = & (Get-CsOnlineSessionCommand)
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CsOnlineSession], PSRemotingTransportException
    + FullyQualifiedErrorId : PSRemotingTransportException,Microsoft.Teams.ConfigApi.Cmdlets.GetCsOnlineSession
 
Invoke-Command : Cannot validate argument on parameter 'Session'. The argument is null or empty. Provide an argument that is not null or empty, and then try the 
command again.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.2\net472\SfBORemotePowershellModule.psm1:9490 char:38
+ ...    -Session (Get-PSImplicitRemotingSession -CommandName 'Get-CsOnline ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Command], ParentContainsErrorRecordException
```

**Comment by tsf89** [comment]
@danielbrowne I have opened a support ticket with Microsoft on this, and according to 1st level support not all Skype module features have been completely developed/moved to the Teams module yet. They have no ETA on when all features will be available.

I would recommend opening a support case so we can raise awareness on this issue and get it prioritized.

They have forwarded my support ticket to
