### ISSUE TITLE
Get-CsOnlineUser - Exception calling "GetSteppablePipeline" with "1" argument(s) .. Tenant Domain is empty

### ISSUE THREAD

**Issue by aspnet4you** [MicrosoftDocs/office-docs-powershell#7469]
I am running the powershell script in Azure Automation Runbook and using MicrosoftTeams module.

Call to Connect-MicrosoftTeams with -TenantId -CertificateThumbprint and -applicationid works fine. I am using Azure Service Principal with certificate authentication.

But, when I call Get-CsOnlineUser very next line I am awarded with an error - Exception calling "GetSteppablePipeline" with "1" argument(s): "Exception calling "GetRemoteNewCsOnlineSession" with "1" argument(s): "Tenant Domain is empty"" (Exception calling "GetRemoteNewCsOnlineSession" with "1" argument(s): "Tenant Domain is empty" (Exception calling "GetRemoteNewCsOnlineSession" with "1" argument(s): "Tenant Domain is empty" (Tenant Domain is empty)))

Any reason Get-CsOnlineUser or Get-CsOnlineUser -Filter {TenantId -eq "my-tanent-id"} would not work?

Interestingly, I can call Get-TeamUser and I get valid respone but Get-CsOnlineUser would error out!

If I use Credential parameter as opposed to CertificateThumbprint, Get-CsOnlineUser works but for security best practice I would not use credential.
$connection = (Connect-MicrosoftTeams -TenantId "my-tanent-id" -Credential $Credential)

I hope Microsoft either fix the issue or update the documentation explaining why  Get-CsOnlineUser does not work with certificate authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6804423b-8e08-5916-9355-6bebe8bb08b0
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [MicrosoftTeamsPowerShell Module](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by danielmeridew-mto** [comment]
Having the same issue.

**Comment by get-itips** [comment]
Hello @aspnet4you 
https://github.com/MicrosoftDocs/office-docs-powershell/issues/7464#issuecomment-811248583

**Comment by aspnet4you** [comment]
I am not seeing any tangible response from Microsoft on this issue! It's impacting many people after merging Skype  for Business with Teams powershell module. Don't understand why they didn't think of backward compatibility!

Problem with the use of credential is, it conflicts with Conditional Access policy. I can't trust Azure regional IP as trusted location.

**Comment by danielmeridew-mto** [comment]
I’ll do the same – thanks.

**Comment by orandev** [comment]
Hello,
For those of you with the issue and who don't need a proxy to access O365 URLs, could you test like that please?

Connect-MicrosoftTeams -TenantId 'yourdomain.com' -ApplicationId xxx -CertificateThumbprint xxx

(instead of your tenant GUID)

**Comment by danielmeridew-mto** [comment]
If by "yourdomain.com" you are talking about the initial O365 domain, I have tried this and it doesn't work, albeit a different error.

I haven't got access to machine for testing this now, will reply back with error next week.

**Comment by aspnet4you** [comment]
@danielmeridew-mto,
Thanks for the suggestion on using tenant initial domain. I tried but it didn't work. Got different error message though. I have not spent time to analyze what the error means! Any help would be appreciated.

This is the line of code that error out-
$Users = Get-CsOnlineUser -Filter {TenantId -eq "aspnet4you2.onmicrosoft.com"}

Error message:
Exception calling "GetSteppablePipeline" with "1" argument(s): "Exception calling "GetRemoteNewCsOnlineSession" with "1" argument(s): "Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The WinRM client received an HTTP status code of 403 from the remote WS-Management service. For more information, see the about_Remote_Troubleshooting Help topic."" (Exception calling "GetRemoteNewCsOnlineSession" with "1" argument(s): "Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The WinRM client received an HTTP status code of 403 from the remote WS-Management service. For more information, see the about_Remote_Troubleshooting Help topic." (Exception calling "GetRemoteNewCsOnlineSession" with "1" argument(s): "Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The WinRM client received an HTTP status code of 403 from the remote WS-Management service. For more information, see the about_Remote_Troubleshooting Help topic." (Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The WinRM client received an HTTP status code of 403 from the remote WS-Management service. For more information, see the about_Remote_Troubleshooting Help topic.)))

**Comment by danielmeridew-mto** [comment]
I have tested and receive the same error when using tenant initial domain value rather than tenant ID value:

Exception calling "GetSteppablePipeline" with "1" argument(s): "Exception calling "GetRemoteNewCsOnlineSession" with "1" argument(s): "Connecting to remote server 
api.interfaces.records.teams.microsoft.com failed with the following error message : The WinRM client cannot process the request. The authentication mechanism requested by the client is not 
supported by the server or unencrypted traffic is disabled in the service configuration. Verify the unencrypted traffic setting in the service configuration or specify one of the authentication       
mechanisms supported by the server.  To use Kerberos, specify the computer name as the remote destination. Also verify that the client computer and the destination computer are joined to a domain.    
To use Basic, specify the computer name as the remote destination, specify Basic authentication and provide user name and password. Possible authentication mechanisms reported by server: For more     
information, see the about_Remote_Troubleshooting Help topic.""

**Comment by get-itips** [comment]
> Hello @aspnet4you
> [#7464 (comment)](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7464#issuecomment-811248583)

I could get some information from the team behind the module, they are aware of this and are working on it. Hope this information helps everyone here.
@yogkumgit please close this issue as it is not documentation-related. Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @aspnet4you Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by danielbecker** [comment]
Just in case anyone else stumbles upon this issue: There's a new version of the package (2.3.1) that fixed the issue for me. https://www.powershellgallery.com/packages/MicrosoftTeams/2.3.1

**Comment by sarollins** [comment]
After installing the 2.3.1 module, I no longer get the GetSteppablePipeline error when trying to execute a Skype for Business cmdlet, I now get

Get-CsOnlineSession : Tenant Domain is empty
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\SfBORemotePowershellModule.psm1:63 char:22
+     $remoteSession = & (Get-CsOnlineSessionCommand)
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CsOnlineSession], ArgumentException
    + FullyQualifiedErrorId : ArgumentException,Microsoft.Teams.ConfigApi.Cmdlets.GetCsOnlineSession

Invoke-Command : Cannot validate argument on parameter 'Session'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\SfBORemotePowershellModule.psm1:9490 char:38
+ ...    -Session (Get-PSImplicitRemotingSession -CommandName 'Get-CsOnline ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Command], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeCommandCommand

**Comment by Sebalbers** [comment]
> After installing the 2.3.1 module, I no longer get the GetSteppablePipeline error when trying to execute a Skype for Business cmdlet, I now get
> 
> Get-CsOnlineSession : Tenant Domain is empty
> At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\SfBORemotePowershellModule.psm1:63 char:22
> $remoteSession = & (Get-CsOnlineSessionCommand)
> ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
> + CategoryInfo : NotSpecified: (:) [Get-CsOnlineSession], ArgumentException
> + FullyQualifiedErrorId : ArgumentException,Microsoft.Teams.ConfigApi.Cmdlets.GetCsOnlineSession
> 
> Invoke-Command : Cannot validate argument on parameter 'Session'. The argument is null or empty. Provide an argument
> that is not null or empty, and then try the command again.
> At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\SfBORemotePowershellModule.psm1:9490 char:38
> -Session (Get-PSImplicitRemotingSession -CommandName 'Get-CsOnline ...
> ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
> + CategoryInfo : InvalidData: (:) [Invoke-Command], ParentContainsErrorRecordException
> + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeCommandCommand

I am experiencing the same issue as this.

**Comment by ColBrubaker** [comment]
> 
> 
> > After installing the 2.3.1 module, I no longer get the GetSteppablePipeline error when trying to execute a Skype for Business cmdlet, I now get
> > Get-CsOnlineSession : Tenant Domain is empty
> > At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\SfBORemotePowershellModule.psm1:63 char:22
> > $remoteSession = & (Get-CsOnlineSessionCommand)
> > ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
> > 
> > * CategoryInfo : NotSpecified: (:) [Get-CsOnlineSession], ArgumentException
> > * FullyQualifiedErrorId : ArgumentException,Microsoft.Teams.ConfigApi.Cmdlets.GetCsOnlineSession
> > 
> > Invoke-Command : Cannot validate argument on parameter 'Session'. The argument is null or empty. Provide an argument
> > that is not null or empty, and then try the command again.
> > At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\SfBORemotePowershellModule.psm1:9490 char:38
> > -Session (Get-PSImplicitRemotingSession -CommandName 'Get-CsOnline ...
> > ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
> > 
> > * CategoryInfo : InvalidData: (:) [Invoke-Command], ParentContainsErrorRecordException
> > * FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeCommandCommand
> 
> I am experiencing the same issue as this.

@sarollins @Sebalbers Once upgraded to the 2.3.1 module, I received this error as well. Reconnecting to Teams with the TenantId switch fixed that: 

`Connect-MicrosoftTeams -TenantId <TenantId>`

I can now run Get-CsOnlineSipDomain, etc. commands successfully.

Cheers

**Comment by olsonnn** [comment]
Same issue with 2.4 preview ;(

**Comment by joergrenn** [comment]
Why has this ticket been closed, although the issue still persists?
I am having the same issue trying to access with a certificate Connect-MicrosoftTeams -TenantId <TenantId> -ApplicationId <ApplicationId> -CertificateThumbprint <CertificateThumbprint>
