### ISSUE TITLE
More info on this would also be good

### ISSUE THREAD

**Issue by alorman** [MicrosoftDocs/office-docs-powershell#747]
Even just example code would be  helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc910c40-6577-8d7b-476c-1234e836706c
* Version Independent ID: ab8f028f-d0f6-25c0-98d0-7f24806744dc
* Content: [Unregister-CsOnlineDialInConferencingServiceNumber (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/unregister-csonlinedialinconferencingservicenumber?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Unregister-CsOnlineDialInConferencingServiceNumber.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Unregister-CsOnlineDialInConferencingServiceNumber.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by nsshommo** [comment]
@alorman Thanks for your feedback. It will be added soon.

@kenwith Do you know who can help me on this?

**Comment by kenwith** [comment]
@tonysmit or @islubin  - do you happen to know who owns the *-CsOnlineDialInConferencingServiceNumber?

**Comment by islubin** [comment]
Oscar, as part of the side thread I spun up with him.

**Comment by kenwith** [comment]
Relates to: https://github.com/MicrosoftDocs/office-docs-powershell/issues/561

**Comment by tonysmit** [comment]
Adding Oscar.

Sent with only my thumbs.
________________________________

**Comment by alorman** [comment]
All;
Here's an example code that MSFT support forwarded to me. 
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_sfbonline-mso_o365b/skype-for-business-admin-center-unassign-service/854f2f96-9f98-4fa4-951d-514f8e2df0ad

It worked for me, providing that I logged into the cmdlet with the procedure for two factor, found here:
https://blogs.technet.microsoft.com/solutions_advisory_board/2017/04/27/connect-to-office-365-services-with-multifactor-authentication-mfa-and-powershell/

**Comment by kenwith** [comment]
@alorman - this is really great info. Would you want to add the examples that support provided a Pull Request so you get ['contributor'](https://github.com/MicrosoftDocs/office-docs-powershell/graphs/contributors) credit or should @nsshommo go ahead and add those and add Related Links to the items you provided?

**Comment by alorman** [comment]
Sure, I'll go ahead and do that and issue a PR.
Thanks
alex
