### ISSUE TITLE
Set-PnPMicrosoft365Group : Deserialization of reference types without parameterless constructor is not supported

### ISSUE THREAD

**Issue by prossum** [MicrosoftDocs/office-docs-powershell#7474]
I use pnp.powershell in Azure Automation runbooks.
pnp.powershell - version 1.4.0

 ----------------
```
$servicePrincipalConnection=Get-AutomationConnection -Name $connectionName
$siteToOpen = "https://<my-company>-admin.sharepoint.com"
$adminCtx = Connect-PnPOnline -Url $siteToOpen `
                -ClientId $servicePrincipalConnection.ApplicationId `
                -Tenant $servicePrincipalConnection.TenantId `
                -Thumbprint $servicePrincipalConnection.CertificateThumbprint `
                -ReturnConnection
$TeamTitle = <my team>
$myGroup = Get-PnPMicrosoft365Group -Connection $adminCtx -Identity "$($TeamTitle)" -IncludeSiteUrl
"Group: $($TeamTitle) - with site: $($myGroup.SiteUrl)"
Set-PnPMicrosoft365Group -Identity $myGroup -HideFromAddressLists $true
```
-----------------
The Get-PnPMicrosoft365Group succeeds, as I see the output including the site Url.
With the next line I get this error:

```
Set-PnPMicrosoft365Group : Deserialization of reference types without parameterless constructor is not supported. Type 
'<>f__AnonymousType20`2[System.Nullable`1[System.Boolean],System.Nullable`1[System.Boolean]]'
At line:35 char:1
+ Set-PnPMicrosoft365Group -Identity $myGroup -HideFromAddressList ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-PnPMicrosoft365Group], NotSupportedException
    + FullyQualifiedErrorId : 
System.NotSupportedException,PnP.PowerShell.Commands.Microsoft365Groups.SetMicrosoft365Group

```
Is this a bug or am I doing something wrong?

**Comment by prossum** [comment]
Should I also post this to https://github.com/pnp/powershell/issues ?

**Comment by get-itips** [comment]
Hello @prossum 
How are you? to open PnP issues I need to kindly redirect you to [this other repo](https://github.com/pnp/powershell)
Thank you.

**Comment by prossum** [comment]
The issue is now posted here: https://github.com/pnp/powershell/issues/530

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @prossum Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
