### ISSUE TITLE
Placeholder for Description is shown for two parameters

### ISSUE THREAD

**Issue by arodir** [MicrosoftDocs/office-docs-powershell#7478]
The following parameters' descriptions show a placeholder instead of the actual description:

-ShowOnlineArchiveEnabled
This parameter is available only in the cloud-based service.

**{{ Fill ShowOnlineArchiveEnabled Description }}**

-MessagePreviewsDisabled
This parameter is available only in the cloud-based service.

**{{ Fill MessagePreviewsDisabled Description }}**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022da80e-29cd-f6b5-aa00-48e2d16c4be8
* Version Independent ID: c3353c03-e416-f693-104f-6b6f5955b721
* Content: [Set-OwaMailboxPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@arodir, known issue. The availability of a parameter doesn't necessarily mean the parameter is supposed to be available or that it works correctly.

So do those parameters work correctly for you?

**Comment by chrisda** [comment]
Known issue that the parameter description is blank.

Thanks for the feedback.

Closing
