### ISSUE TITLE
Example 2

### ISSUE THREAD

**Issue by jhventer** [MicrosoftDocs/office-docs-powershell#7480]
Explanation reads "_Sets the SharePoint Online Storage Quota on the NORTH CENTRAL US location to 1 TeraBytes (1Tb)._" but should be 1 [Gigabyte.]
![image](https://user-images.githubusercontent.com/5450299/112175699-21ce7800-8c00-11eb-8f94-0bf395bd1b8c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0453dac7-2ba8-7e84-59bc-452a3634ebc8
* Version Independent ID: b65f9bd4-d144-9a29-0360-fd7604c5c228
* Content: [Set-SPOGeoStorageQuota (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spogeostoragequota?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOGeoStorageQuota.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOGeoStorageQuota.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for reporting! @jhventer
