### ISSUE TITLE
Wildcard for InternetWebProxyBypassList not accepted

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/office-docs-powershell#7486]
Hi,

the article states that the parameter InternetWebProxyBypassList accepts Wildcards. Within my tests I've found out that Wildcards are not available - the parameter does not accept it:

![image](https://user-images.githubusercontent.com/23408264/112338855-6ec55380-8cbf-11eb-8175-25b932d66554.png)

Can you verify if this should really work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aaf56c8-31b0-1d9b-52c0-93c898008ed8
* Version Independent ID: 391f6946-03dd-5ccb-a4f6-fb11b5f8fcc2
* Content: [Set-ExchangeServer (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-exchangeserver?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-ExchangeServer.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-ExchangeServer.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@myfope, I see that you're talking about the Accept wildcard characters attribute. That attribute value is read/calculated from code. From what I can tell over the last 3 years, that value was (in retrospect, incorrectly) "True" only until very recently. So, I changed it to "False".

Generally speaking, I would say trust the actual parameter text description more that that specific attribute when it comes to wildcard support. The existing description makes no mention of wildcard support.

Thanks for the feedback.

Closing
