### ISSUE TITLE
Can we get a bit more clarification what does the NumberOfThreads does for get-team

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#7487]
Hi,

Currently you have wrote
"_Specifies the number of threads to use. The accepted values range from 1 to 20._"
for Get-Team
But what does that really mean? What threads? Local or on Cloud side? When shall I use 1 or 20?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38da792-01bc-28ad-7727-794075e150c9
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @Petri-X I'll work on a better description for the parameter. Thanks
