### ISSUE TITLE
Feature Request to Teams PowerShell module - decrease the amount of traffic returned from servers

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#7491]
Hi there,
Has anybody of you proposed to limiting number of attributes what different "get-" CMDlets are returned from servers? For example when run:
**get-csonlineuser john.doe@company.com**
That gives 199 attributes back. With single users searches this is not big issue. But how about 20k users or even more?

The solution could be having a "properties" parameter added. And with that admins could define what parameters s/he needs. And by default there is coming only few defaults.

That would have a business case to you I believe, as that would simplifying the searches on servers site, and most likely makes the searches to happen faster.

**Comment by shivtorov** [comment]
Hey @Petri-X 
It would be nice to have a modern version of the module that will allow such things as filtering.
But I would be surprise if Microsoft will do any time soon (coming years).

In the meantime, you can do this today by explicitly using PS Remoting. I know it's ugly and limited in many aspects, but at least it is something that is available today and it works.

Try the following example that executes column filtering server-side and then downloads only the final results.

Slow code: Client-side filtering

```PowerShell
Import-PSSession (New-CsOnlineSession)
Get-CsOnlineUser | Select-Object InterpretedUserType -Unique
```

Fast-code - server-side filtering
```PowerShell
Import-PSSession (New-CsOnlineSession)
Invoke-Command -Session (Get-PSSession) -ScriptBlock { Get-CsOnlineUser | Select-Object InterpretedUserType -Unique }
```

Above examples are for Microsoft Teams v 1.1.6 in Windows PowerShell 5.1

**Comment by get-itips** [comment]
Hello @Petri-X how are you? Hope you are doing good.
We appreciate the feedback, however, as you might know, we are limited here to documentation issues and improvements.
I also appreciate your contribution @shivtorov for Petri and everyone that might be on the same page.
Thanks

**Comment by Petri-X** [comment]
@shivtorov 
Sorry to say, but module 1.1.6 is history already, and we have started to use module version 2.0.0. "New-csOnlineSession" is not available anymore.

@get-itips 
I believe that is a bit problematic. There has been no clear clarification into where the GitHub should be used, when sometimes this is helping errors on the documentation, but sometime PS module issues are listed on GitHub. Are  you able to clarify that somehow? I'm preferring to use GitHub possibilities to report PS issues as well. :)

**Comment by get-itips** [comment]
@Petri-X Sure Petri, I'll try to do my best to give you the requested information: You can have more information [here](https://github.com/MicrosoftDocs/office-docs-powershell)  and [here](https://docs.microsoft.com/en-us/contribute/).
Also a [bit of history](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs) 👍

**Comment by shivtorov** [comment]
@Petri-X 

> @shivtorov
> Sorry to say, but module 1.1.6 is history already, and we have started to use module version 2.0.0. "New-csOnlineSession" is not available anymore.

Congratulations with upgrading to v.2.0.0!!!

```PowerShell
Connect-MicrosoftTeams
Invoke-Command -Session (Get-PSSession) -ScriptBlock { Get-CsOnlineUser | Select-Object InterpretedUserType -Unique }
```

🤦‍♂️

**Comment by get-itips** [comment]
I passed this information along, @yogkumgit please close this as it is not documentation-related. Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Petri-X Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Petri-X** [comment]
@shivtorov 
Sorry to say, but you need to clarify that a bit more  :D 
As when I'm running:

```
PS C:\> Connect-MicrosoftTeams
Account                     Environment Tenant      TenantId
teamsAdmin@company.com      AzureCloud  9bfcd....   9bfcd....

PS C:\> Get-PSSession
PS C:\>  
```





At least I'm getting nothing for PS Session. So I'm not sure if the "connect-MicrosoftTeams" is a PSSession(?). But as you also referring, it would be ten times better to have this into PS module directly. AD team has made like following:
`Get-ADUser -Identity UserA -Properties *`
or the -properties could look like
`Get-ADUser -Identity UserA -Properties emailAddress, telephoneNumber`

**Comment by get-itips** [comment]
> I passed this information along, @yogkumgit please close this as it is not documentation-related. Thanks

@yogkumgit please close this thread as it is not documentation specific and I already passed this feedback along.
