### ISSUE TITLE
SiteIDs description needs more detail

### ISSUE THREAD

**Issue by cablechewer** [MicrosoftDocs/office-docs-powershell#7496]
If you are searching for Sites where the names include the dash/minus character you will get no hits.  You have to double the characters.

For example my lab tenant contains the site:
"https://contoso.sharepoint.com/sites/cats-are-cool"

If you run:
search-unifiedauditlog -startdate 3/3/2021 -enddate 4/4/2021 -siteids "https://contoso.sharepoint.com/sites/cats-are-cool"
you will get zero hits.

If you run:
search-unifiedauditlog -startdate 3/3/2021 -enddate 4/4/2021 -siteids "https://contoso.sharepoint.com/sites/cats--are--cool"
you get many hits.

This parameter is treating - as a special character.  You have to include two of them to tell the cmdlet that you mean to include one as a literal.

This behaviour also affects the Audit Log search on compliance.microsoft.com and protection.office.com because they run this cmdlet under the hood.

I would suggest a Note be added to the description of this parameter explaining that you need to double the dashes to have them treated properly.  The Help for the GUI should also be updated.

Chrispol@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75b757c9-b775-8294-91f7-870bead6a907
* Version Independent ID: 54ebab36-97bb-cd9f-6eb2-12198af885e2
* Content: [Search-UnifiedAuditLog (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/search-unifiedauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cablechewer, I added information to the SiteIds parameter description as you described.

Thanks for the feedback.

Closing
