### ISSUE TITLE
SFB and Teams PS modules have been merged - doc referenced two separate modules

### ISSUE THREAD

**Issue by oksanaMS** [MicrosoftDocs/office-docs-powershell#7498]
SFB and Teams PS modules have been merged, this article https://docs.microsoft.com/en-us/powershell/teams/?view=teams-ps suggests there are two separate modules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82bf8ef2-fd7a-6f93-b6da-85a3ceb31ead
* Version Independent ID: 5f42884e-b6e3-a568-a5b0-a573f699b12b
* Content: [Microsoft Teams cmdlet help reference](https://docs.microsoft.com/en-us/powershell/teams/?view=teams-ps&source=docs)
* Content Source: [teams/docs-conceptual/index.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/docs-conceptual/index.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Thanks for your feedback @oksanaMS
