### ISSUE TITLE
MicrosoftTeams PS 2.0 takes 3 min to load

### ISSUE THREAD

**Issue by DeyvLauzon** [MicrosoftDocs/office-docs-powershell#7499]
The new version of the Teams module takes 3 minutes to import with import-module. This is impacting all of our automation scripts. Am I the only one that expericences this?

**Comment by get-itips** [comment]
@DeyvLauzon Hello, how are you? hope you are doing good.
We are limited here to documentation changes and improvements, I'll try to pass this message on.
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DeyvLauzon Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
