### ISSUE TITLE
SPO PowerShell Overview Section

### ISSUE THREAD

**Issue by maadarani** [MicrosoftDocs/office-docs-powershell#75]
Hello,

The SPO PowerShell Overview Section should not be a subsection of On-premises. For users, it will be confusing on how to use it. Rather than having it as heading 3, I would promote it to its own heading, add more description on how to use it, like they need to download and install the SharePoint Online Management Shell, with a brief description on how to use it.

Mike

**Comment by kenwith** [comment]
@Techwriter40 owns this topic and can take a look. Thanks for the feedback!

**Comment by kenwith** [comment]
hi @maadarani  - I was able to connect with @Techwriter40 and he really appreciated your suggestion and will keep it in mind in the future. For now he will keep the same heading structure and will circle back in future if he changes the structure. Thanks for your feedback!

**Comment by maadarani** [comment]
NP; let me know if you need any help in the write up.

Regards,
Mike Maadarani | mike@maadarani.com<mailto:mike@maadarani.com> | www.maadarani.com<http://www.maadarani.com/> | (613) 263-2442
[cid:image004.png@01D38A40.ADD3DF40]<https://mvp.microsoft.com/en-us/mvp/Mike%20Maadarani-5001227> [untitled] <http://www.linkedin.com/pub/mike-maadarani/3/268/93>  [images] <http://twitter.com/mikemaadarani>
