### ISSUE TITLE
Update the Disable-CsOnlineSipDomain page to include Teams. 

### ISSUE THREAD

**Issue by TeamsTechBear** [MicrosoftDocs/office-docs-powershell#7500]
I would like to see the Disable-CsOnlineSipDomain page updated to include all the things that disabling the SIP domain that users are using for Skype for Business Online and Teams will affect for Teams. Customers seem to move towards the idea that it's ok to disable all SIP domains because the documentation only says that users won't be able to federate with Teams and everything else is for Skype for Business Online. Below is the section I'm talking about on the docs page. 

IMPORTANT This cmdlet should not be run for domains that contain users hosted in Skype for Business Online. Any users in a sip domain that are already provisioned online will cease to function if you disable the online sip domain:

- Their SIP addresses will be removed.
- All contacts and meetings for these users hosted in Skype for Business Online will be deleted.
- These users will no longer be able to login to the Skype for Business Online environment.
- If these users use Teams, they will no longer be able to inter-operate with Skype for Business users, nor will they be able to federate with any users in other organizations.

**Comment by get-itips** [comment]
Thanks, will propose an improvement to the note.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and updating the documentation with PR. @TeamsTechBear Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by TeamsTechBear** [comment]
Thanks!

Sincerely,
Nicholas Bear
FastTrack Engineer
Microsoft FastTrack Center                                        Office: (469) 775-1056
http://fasttrack.microsoft.com<http://fasttrack.microsoft.com/>                                   nickbear@Microsoft.com<mailto:nickbear@Microsoft.com>
***@***.***D73825.9269ED80]

FastTrack Center Service Description<http://technet.microsoft.com/en-us/library/office-365-onboarding-benefit.aspx>

Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Ffasttrack&data=02%7C01%7CStephen.Sorenson%40microsoft.com%7C30b601ad1b734e47bd2d08d84a2c38e2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637340901098822428&sdata=6e3azxDHC7Xdu%2FQ7RWZxinzS6lWRgdIbzS35odW%2FsQ4%3D&reserved=0> | Learn about Edge<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fedge&data=02%7C01%7CStephen.Sorenson%40microsoft.com%7C30b601ad1b734e47bd2d08d84a2c38e2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637340901098822428&sdata=kplUS5WxErPul23OY54Kbn%2BkSF8aUgc4PvDC7D8kUdM%3D&reserved=0>


--My goal is to offer you the best possible experience with the Microsoft FastTrack Center.
If you need any assistance that I am unable to offer, please contact my Lead: Phillip Gerdes at ***@***.******@***.***>.
