### ISSUE TITLE
Max Resultsize

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/office-docs-powershell#7511]
I don't understand why in first paragraph limit is 100000 but the maximum pagesize is 5000.
Further I am receiving an error (throttling) when specifying the parameter to high.
I suggest to reduce the max value to 10.000

![image](https://user-images.githubusercontent.com/43539433/112811310-38e7ec80-907c-11eb-93da-38519ea82260.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b37e5f4f-c0bc-8cce-3d0b-971bcc118726
* Version Independent ID: 50c55aeb-0311-ac5a-7468-b276835f6b67
* Content: [Get-MessageTrace (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-messagetrace?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MessageTrace.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MessageTrace.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@trudolf-msft, there's nothing we can do from a documentation perspective for your request. To get action on a feature update request, I would suggest opening a support case.

**Comment by yogkumgit** [comment]
@trudolf-msft Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
