### ISSUE TITLE
Restore-RecoverableItems can only target original mailbox

### ISSUE THREAD

**Issue by adagioajanes** [MicrosoftDocs/office-docs-powershell#7514]
We are attempting to recover a user's emails with Restore-RecoverableItems. We are using this as opposed to using the 'Search-Mailbox' cmdlet. 

We do not want to restore the items to the original user's mailbox, but there is no option to target another mailbox and folder.

Can we re-implement that functionality in Restore-RecoverableItems?

**Comment by dariomws** [comment]
@adagioajanes - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Exchange Online PowerShell module better. They keep a close tab on user feedback, and it would be awesome if you could add your voice in the following channels:
https://support.microsoft.com/en-us/topic/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by yogkumgit** [comment]
@adagioajanes Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
