### ISSUE TITLE
Connect-MicrosoftTeams new version 2.0.0

### ISSUE THREAD

**Issue by pmatthews05** [MicrosoftDocs/office-docs-powershell#7518]
I have recently downloaded the latest version of MicrosoftTeams and I'm still having difficulties trying to connect to my tenant.

Using PowerShell 7.1 I'm able to connect just calling `Connect-MicrosoftTeams` that uses MFA. However I'm unable to connect using  AppID and CertificateThumbprint.

`Connect-MicrosoftTeams -TenantId $TenantId -ApplicationId $AppId -CertificateThumbprint:$Thumbprint`

or AadAccessToken
```ps
#Sign in with Service Principal
$graphToken = az account get-access-token --resource-type aad-graph | ConvertFrom-Json
Connect-MicrosoftTeams -AadAccessToken:$($graphToken.accessToken) -AccountId:$UPN -TenantId:$TenantID
```

It seems to connect, but any following calls such as `Get-CsTeamsMeetingPolicy -Identity Global` throws an error message.

```
ParentContainsErrorRecordException: .\PowerShell\Modules\MicrosoftTeams\2.0.0\netcoreapp2.1\SfBORemotePowershellModule.psm1:13118:13
 Line |
13118 |              $steppablePipeline = $scriptCmd.GetSteppablePipeline($myI …
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Exception calling "GetSteppablePipeline" with "1" argument(s): "Exception calling "GetRemoteNewCsOnlineSession" with "1" argument(s): "Run either Connect-MicrosoftTeams or
      | new-csonlinesession before running cmdlets.""
```

I want to be able write a script that is done via app only Service Principal. I'm unable to find documentation on how to do this, or what permissions are required for an app only Service Principal.

**Comment by cowlinb6** [comment]
I'm getting the same issue, is there any update on this?

**Comment by get-itips** [comment]
Hello @pmatthews05 Paul, please see here https://github.com/MicrosoftDocs/office-docs-powershell/issues/7464#issuecomment-811248583 and https://github.com/MicrosoftDocs/office-docs-powershell/issues/7469

**Comment by awill4457** [comment]
> Hello @pmatthews05 Paul, please see here [#7464 (comment)](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7464#issuecomment-811248583) and #7469

@get-itips I'm not sure why you keep pointing people to other issues where people are pointing out the exact same issue, and there is no resolution. This keeps going around in circles, and what is MEANT to be a working solution is not working at all for the CS side of the commands

Can we please get an actual update on what is happening with the teams powershell module? First I'd suggest starting by using some actual words explaining what API permissions are required so we can make this thing work!

**Comment by get-itips** [comment]
> > Hello @pmatthews05 Paul, please see here [#7464 (comment)](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7464#issuecomment-811248583) and #7469
> 
> @get-itips I'm not sure why you keep pointing people to other issues where people are pointing out the exact same issue, and there is no resolution. This keeps going around in circles, and what is MEANT to be a working solution is not working at all for the CS side of the commands
> 
> Can we please get an actual update on what is happening with the teams powershell module? First I'd suggest starting by using some actual words explaining what API permissions are required so we can make this thing work! 

Hello @awill4457 Alex how are you? I can understand, however here we are limited to deal with documentation issues/feedback, not product ones, besides that, I am already trying to pass this message on to the product team behind the module. Thank you

**Comment by pmatthews05** [comment]
@get-itips fair enough that you deal only with the documentation, however perhaps the documentation should contain a link to where to raise an issue about the product as well as issue with the documentation.

It appears from the links you have put there is definitely a problem with the product connecting with Service Principal, which is a problem with the product. 

The issue I have with the documentation then is that I do not know what permissions I need to give an Service Principal.

**Comment by get-itips** [comment]
> @get-itips fair enough that you deal only with the documentation, however perhaps the documentation should contain a link to where to raise an issue about the product as well as issue with the documentation.

Hello Paul, I sent this feedback to the team behind Docs.

> It appears from the links you have put there is definitely a problem with the product connecting with Service Principal, which is a problem with the product.
> 
> The issue I have with the documentation then is that I do not know what permissions I need to give an Service Principal.

Paul, I could get some information from the team behind the module, they are aware of this and are working on it. Hope this information helps you.

**Comment by hootmartin** [comment]
Hello @get-itips ,
hope you're doing well!

I am facing the same issue. Can you get any info from the team behind the module about when a fix could be available? A rough indicator if we are talking about days, weeks or months would be very valuable!

Thank you!

**Comment by get-itips** [comment]
> Hello @get-itips ,
> hope you're doing well!
> 
> I am facing the same issue. Can you get any info from the team behind the module about when a fix could be available? A rough indicator if we are talking about days, weeks or months would be very valuable!
> 
> Thank you!

I am sorry, I am afraid I have no more information than that.
@yogkumgit please close this issue.

**Comment by YuriySamorodov** [comment]
@get-itips And me! And me! Same issue =( Looks like the whole MicrosoftTeams module is screwed...

**Comment by get-itips** [comment]
@yogkumgit please close this issue.
