### ISSUE TITLE
RecommendedPolicyType flag is not documented.

### ISSUE THREAD

**Issue by qqii** [MicrosoftDocs/office-docs-powershell#7522]
Instances can be found here: https://github.com/MicrosoftDocs/office-docs-powershell/search?q=RecommendedPolicyType

Also sometimes the accepted values are listed and sometimes they are not.

**Comment by chrisda** [comment]
@qqii, RecommededPolicyType parameter documented in the following cmdlets:

-  New-AntiPhishPolicy
- New-HostedContentFilterPolicy
- New-HostedOutboundSpamFilterPolicy
- New-MalwareFilterPolicy
- New-SafeAttachmentPolicy
- New-SafeLinksPolicy

Thanks for the feedback.

Closing
