### ISSUE TITLE
Document needs to be updated to reflect Modern Auth

### ISSUE THREAD

**Issue by JRVcr** [MicrosoftDocs/office-docs-powershell#7525]
[Enter feedback here]
This command in the article--

Connect-SPOService -Url https://contoso-admin.sharepoint.com -Credential admin@contoso.com

--should become--

Connect-SPOService -Url https://contoso-admin.sharepoint.com

SPOService will no longer (by default) allow pre-Modern Auth.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b23d72-33ed-a6a1-a442-a5e5cf039f9f
* Version Independent ID: 4247cf37-3667-2007-7251-46ed80f58ef5
* Content: [Get started with the SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @JRVcr how are you? The 

> To connect with multifactor authentication (MFA)

section already uses the method you are proposing.

Thanks!!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @JRVcr Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
