### ISSUE TITLE
What is expected results from get-teamsapp?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#7533]
Hi team,

When running the cmdlet get-teamsapp and comparing the results to the output what GUI (Teams Admin center) is offering. I have the following findings:
F1) get-teamsapp seems to be not returning the application which are blocked, is that correct?
F2) Even I'm comparing the allowed apps there is differences, some apps are:
  - visible only on GUI: Bulletins, Milestones, PowerApps, etc...
  - visible only on CMDLet: BATL Assessments, Broadcast QnA, Camera, Saved, Search, Walkie Talkie, etc...

Are you able to share the logic how this should be working?
Blocking/Allowing individual apps is only be available on GUI, or have I missed some instructions (again)?

PS Module version is 2.0.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8b48634-5434-fe5f-f033-e52e4d5993d3
* Version Independent ID: ceb23f70-6ffa-5dda-00ff-c1be6a7a9a78
* Content: [Get-TeamsApp (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamsapp?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-TeamsApp.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamsApp.md)
* Service: **teams-powershell**
* GitHub Login: @joeyglocke
* Microsoft Alias: **joglocke**

**Comment by get-itips** [comment]
Hello @Petri-X 
How are you? tested on my tenant:

> F1) get-teamsapp seems to be not returning the application which are blocked, is that correct?

I could return blocked apps using Get-TeamsApp

>F2) Even I'm comparing the allowed apps there is differences, some apps are:
>visible only on GUI: Bulletins, Milestones, PowerApps, etc...
>visible only on CMDLet: BATL Assessments, Broadcast QnA, Camera, Saved, Search, Walkie Talkie, etc...

I could get those apps using either the GUI or the Ps module.

>Blocking/Allowing individual apps is only be available on GUI, or have I missed some instructions (again)?

It seems that for now there isn't a way to block by Ps.

What I saw were differences in the total number of apps returned by GUI vs Ps, there were more results in the Get-TeamsApp output, will try to pass this information along to the team.

Thank you for your feedback.

**Comment by get-itips** [comment]
@Petri-X I could get some more information, It seems that TAC only shows the one that can be blocked.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Petri-X Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
