### ISSUE TITLE
getting 403 when using Add-PnPSiteCollectionAdmin

### ISSUE THREAD

**Issue by vayinapurapu** [MicrosoftDocs/office-docs-powershell#7538]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba2dc727-d438-3510-19c1-f4c05580afcb
* Version Independent ID: 8ea210be-0cb9-99a2-fd56-edd14a861d00
* Content: [Add-PnPSiteCollectionAdmin (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpsitecollectionadmin?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPSiteCollectionAdmin.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPSiteCollectionAdmin.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by vayin** [comment]
PS C:\WINDOWS\system32> Add-PnPSiteCollectionAdmin -Owners "vayinapurapu@pepsico.com"
Add-PnPSiteCollectionAdmin : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ Add-PnPSiteCollectionAdmin -Owners "vayinapurapu@pepsico.com"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPSiteCollectionAdmin], WebException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Site.AddSiteCollectionAdmin

**Comment by get-itips** [comment]
Hello @vayinapurapu 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @vayinapurapu Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
