### ISSUE TITLE
wrong link for Connect-IPPssession

### ISSUE THREAD

**Issue by xieming95** [MicrosoftDocs/office-docs-powershell#7539]
[Enter feedback here]

**For detailed syntax and parameter information, see Connect-IPPSSession**

The link for Connect-IPPSSession will navigate to page of Connect-ExchangeOnline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Security & Compliance Center PowerShell using the EXO V2 module](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-scc-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@xieming95, fixed. In the future, you too can make fixes like this without opening a GitHub Issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
