### ISSUE TITLE
-OneDriveSharedByMemberOf parameter missing

### ISSUE THREAD

**Issue by BSiefferman** [MicrosoftDocs/office-docs-powershell#7540]
I am missing the -OneDriveSharedByMemberOf parameter and a few others even after being on the latest version 2.0.4 of the Exchange Online PowerShell V2 module. How would I get this cmdlet to be displayed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cee91383-5198-3793-28c3-f79c233556c2
* Version Independent ID: 01fc839a-d2e6-45ea-b58e-d696b74d02a2
* Content: [Set-DlpCompliancePolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-dlpcompliancepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@BSiefferman, the version of the EXO V2 module only affects the cmdlets that are actually in the module (see [here]<https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#how-the-exo-v2-module-works>. The vast majority of cmdlets in the Exchange Online PowerShell or Security & Compliance Center PowerShell universe are only available after you connect to your organization via remote PowerShell.

We recently published a bunch of new parameters for New/Set-DlpCompliancePolicy. It's possible that the parameters haven't been distributed to all of the data centers yet, or some of the parameters might be in some level of Preview (not available to everyone).

[RBAC](https://docs.microsoft.com/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center) might also play a role. Apparently, the OneDriveSharedByMemberOf parameter requires any of the following roles (all of which are assigned to the Organization Management role group by default):

- Organization Configuration
- Compliance Admin
- Security Admin
- DLP Compliance Management

**Comment by yogkumgit** [comment]
@BSiefferman Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
