### ISSUE TITLE
Parameters MaxTotalSizeInBytes and UsageDatabaseEnabled have no or incorrect description

### ISSUE THREAD

**Issue by ykuijs** [MicrosoftDocs/office-docs-powershell#7548]
In the parameter explanations of this cmdlet parameter descriptions are missing or incorrect (placeholder):

- MaxTotalSizeInBytes has no description
- UsageDatabaseEnabled has a placeholder text as description instead of the actual description: "{{Fill UsageDatabaseEnabled Description}}"

The Get-Help for this cmdlet has the same info:

```
    -MaxTotalSizeInBytes <Int64>
        
        
        Required?                    false
        Position?                    named
        Default value                None
        Accept pipeline input?       False
        Accept wildcard characters?  false
        
    -WhatIf [<SwitchParameter>]
        Displays a message that describes the effect of the command instead of executing the command. For more information, type the following command: `get-help about_commonparameters`
        
        Required?                    false
        Position?                    named
        Default value                False
        Accept pipeline input?       False
        Accept wildcard characters?  false
        
    -UsageDatabaseEnabled [<SwitchParameter>]
        {{Fill UsageDatabaseEnabled Description}}
        
        Required?                    false
        Position?                    named
        Default value                False
        Accept pipeline input?       False
        Accept wildcard characters?  false
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aff3c03-0e0a-4cc4-e666-2b2935d68614
* Version Independent ID: bf63cb46-1b2d-d673-ec4e-a2eab0fca58d
* Content: [Set-SPUsageDefinition (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spusagedefinition?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks for your feedback @ykuijs
