### ISSUE TITLE
No Property MembershipType in Cmdlet Get-TeamChannel

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#7549]
The PS Cmdlet Get-TeamChannel illustrates an example to retrieve all private Teams channels of a Team (see [Example 2](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps#example-2))
However, there is no such property `MembershipType`
```powershell
Connect-MicrosoftTeams
$TeamName = "Manufacturing Teams"
$GroupId = (Get-Team -DisplayName $TeamName).GroupId
Get-TeamChannel -GroupId $GroupId | Get-Member 
```
```
PS C:\Temp> Get-TeamChannel -GroupId $GroupId | Get-Member


   TypeName: Microsoft.TeamsCmdlets.PowerShell.Custom.Model.Channel

Name        MemberType Definition                    
----        ---------- ----------                    
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()             
GetType     Method     type GetType()                
ToString    Method     string ToString()             
Description Property   string Description {get;set;} 
DisplayName Property   string DisplayName {get;set;} 
Id          Property   string Id {get;set;}  
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a290dbfc-3b69-2be6-a4b7-71f3f03bd004
* Version Independent ID: 36d9cfe0-cf60-2fa1-41b4-6c6971042394
* Content: [Get-TeamChannel (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by Markus-Hanisch** [comment]
I had some issues uninstalling the MicrosoftTeams module. I installed the module in different $PSModulePath's.
With the current user, it always imported v1.1.4 instead of the also installed prerelease version.

After uninstalling all versions of MicrosoftTeams PowerShell module and reinstalling the latest Prerelease version v2.2.0-preview it works.
Sorry for confusion.
```powershell
Uninstall-Module -Name MicrosoftTeams -AllVersions
Install-Module -Name MicrosoftTeams -AllowPrerelease
```

**Comment by get-itips** [comment]
@Markus-Hanisch Markus, thanks for returning and sharing that you found the property.
@yogkumgit please close this
