### ISSUE TITLE
Installation - No valid module file was found

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/office-docs-powershell#7551]
Does not detail how to handle inconsistent module directory list when trying to install the ExchangeOnlineManagement module.

> Import-Module : The specified module 'ExchangeOnlineManagement' was not loaded because no valid module file was found in any module directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#update-the-exo-v2-module)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by icelava** [comment]
Scratch this; I previously had installed EXO module and used it ok, but now it appears to be _gone_ from my system. Tried to install the module again but hitting more fundamental errors with PowerShellGet. Need to work that out first.

**Comment by icelava** [comment]
For posterity sake, it appears the "mis-location" of PackageManagement 1.4.7 module causes PowerShell package management system to mess up really bad.

https://stackoverflow.com/questions/65482945/corrupt-packagemanager-unable-to-find-module-providers-powershellget

**Comment by chrisda** [comment]
@icelava, I'm glad you were able to figure it out. 

Closing
