### ISSUE TITLE
PnP App Only Permissions for creating TeamSites

### ISSUE THREAD

**Issue by petercarson** [MicrosoftDocs/office-docs-powershell#7552]
Working on getting my Teams Provisioning open source project working with the App Only certificate based authentication. I had been doing all my early work with Communication Sites as they are quick and easy to provision. Started doing some testing and realized it isn’t working with Team Sites. Looking for some help or guidance.

I have a simple test script that I'm working with that authenticates with a local certificate. It creates a communication site fine, but not a Team site. I'm thinking it has to do with the groups behind this. It's not provisioning a Team just yet. Below is the script, error, and permissions. Thoughts?

Thanks,
Peter

Connect-PnPOnline -Tenant $tenant -ClientId $clientID -Thumbprint $thumbprint -Url $URL
$web = Get-PnPWeb
$web

$siteTitle = "pstest8"
$siteURL = https://envisionitdev.sharepoint.com/sites/$siteTitle
$alias = $siteTitle
$owner = pcarson@envisionitdev.onmicrosoft.com

# New-PnPSite -Type CommunicationSite -Title $siteTitle -Url $siteURL -Owner $owner

New-PnPSite -Type TeamSite -Title $siteTitle -Alias $alias -IsPublic 

New-PnPSite : Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.

 
![API Permissions](https://user-images.githubusercontent.com/24392271/113880506-8c97bb80-9789-11eb-863f-b9c1c52d8afd.png)

**Comment by petercarson** [comment]
Strange, switched my development machine for other reasons, installed the latest PnP.PowerShell, and its working fine now. Not sure what changed, but not looking like an issue now. I do want to dig into the permissions needed and scale those back to the required, so I'll update and close when I get a chance to do that.

**Comment by get-itips** [comment]
Hello @petercarson 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @petercarson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
