### ISSUE TITLE
Doesn't work if current global catalog is unavailable

### ISSUE THREAD

**Issue by agowa338** [MicrosoftDocs/office-docs-powershell#7559]
This command doesn't work if exchange already reports "Could not find any available Global Catalog in forest <forestNameHere>"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8133b060-7aea-fa78-f4ac-5523792682fc
* Version Independent ID: 84313c38-ef18-a1e7-40b9-a092915e2b11
* Content: [Set-ADServerSettings (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-adserversettings?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-ADServerSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-ADServerSettings.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@agowa338, I believe it. From [Exchange Server 2019 system requirements](https://docs.microsoft.com/Exchange/plan-and-deploy/system-requirements?view=exchserver-2019#network-and-directory-server-requirements-for-exchange-2019) and [Exchange Server 2016 system requirements](https://docs.microsoft.com/Exchange/plan-and-deploy/system-requirements?view=exchserver-2016#network-and-directory-server-requirements-for-exchange-2016):

> The Active Directory site where you install the Exchange Server must contain at least one writeable domain controller that's also a global catalog server, or the installation will fail. Furthermore, you can't install the Exchange server and then remove the domain controller from the Active Directory site.

**Comment by agowa338** [comment]
Well, we have an exchange server where just the management shell refuses to accept any command as it says that there is no global catalog server. But the ECP and connecting locally (using the snapin) works just fine.
Just the implicit remoting powershell (exchange management shell) is failing because it says that there is no global catalog.

But we have a global catalog in place. Commandlets like "Set-ADServerSettings" should either have a note for how to connect locally (without implicit remoting) or just also work in situations where it currently throws this exception...

**Comment by chrisda** [comment]
@agiwa338, if you're saying that the Exchange Management Shell or remotely connecting to the Exchange Server doesn't work, and the only way you can do anything is by manually loading the snap-in using Add-PSSnapIn, I highly suggest that you open a support case. Something is dreadfully wrong.

**Comment by agowa338** [comment]
Well, opening a MS support case is not my decision. Esp. After the last MS support cases we had together with that customer didn't end that well. That was partly Microsofts and partly the customers fault.

But this is outside of the scope of this issue.
For this issue I'd just like to request to add a hint that this command doesn't work if the above error is thrown as many websites link  to this command and recommend "pinning" an available domain controller using it. Without mentioning that this needs to be done using the PSSnapIn.
I think it's valuable for disaster recovery scenarios and therefore it should be added to the article.

(Or at least update the article about that error message and provide meaningful explanation why the remoting version of the exchange commands complain about a missing global catalog server even though it's not an issue with the SnapIn and therefore obviously not required... As well as what exactly gets validated here so that we as administrators have a change of understanding and mitigating the issue)

**Comment by chrisda** [comment]
@agowa338, I'm sorry that the customer had a previous negative experience with Microsoft Support, but the best way forward is for them to open a support case to get to the bottom of what's going on AND to see if updates to the documentation are required.

Manually loading the snap-in is always available, but we HIGHLY do not recommend it as it completely bypasses role-based access control (RBAC), so we don't want to encourage that scenario.

Feel free to report back here with any finding from the support case.

I'm closing this issue, but feel free to re-open it.

Thanks for the feedback.

Closing
