### ISSUE TITLE
Performance issues between SFBO and Teams powershell modules

### ISSUE THREAD

**Issue by dappleby300** [MicrosoftDocs/office-docs-powershell#7560]
Hi,

There seems to be a sizable reduction in performance when switching to the new Teams Powershell module from the SFBO one.

```
Connect-MicrosoftTeams

PS> Measure-Command { Grant-CsTeamsCallingPolicy -Identity:"vvvvvvvnn@example.org" -PolicyName:$null }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 13
Milliseconds      : 712
Ticks             : 137125621
TotalDays         : 0.000158710209490741
TotalHours        : 0.00380904502777778
TotalMinutes      : 0.228542701666667
**TotalSeconds      : 13.7125621**
TotalMilliseconds : 13712.5621
```

Compared with the SFBO module

```
$sfbSession = New-CsOnlineSession -Credential $o365Cred -OverrideAdminDomain "$sfboOrgName.onmicrosoft.com"
Import-PSSession $sfbSession  | Out-Null

PS> Measure-Command { Grant-CsTeamsCallingPolicy -Identity:"vvvvvvvnn@example.org" -PolicyName:"Test-Policy" }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 3
Milliseconds      : 329
Ticks             : 33294699
TotalDays         : 3.853553125E-05
TotalHours        : 0.00092485275
TotalMinutes      : 0.055491165
**TotalSeconds      : 3.3294699**
TotalMilliseconds : 3329.4699
```

This seems to occur consistently when using the Grant-cs* and set-cs* cmdlets. I have seen the Teams module take up to 2 minutes to execute commands the older Skype for Business Online Module would do in 3 seconds or less.

Powershell on Windows Server 2019.

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by biphi** [comment]
Hi,
i have also raised this already in another post:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/7407

**Comment by biphi** [comment]
i had to switch back to the old module accelerate my scripts again.

**Comment by darwincr** [comment]
Also experiencing issues with this
in my case it takes more than 30 seconds to run a get-csonlineuser for a single user

This problem becomes painful when you have Powershell scripts that take hours to complete

I noticed SFBO powershell even tough it still works is no longer available for download
Is it going to stop working?

**Comment by get-itips** [comment]
Hello @dappleby300 I'll try to pass this information on to the team behind the module, as here we are limited to documentation issues, also if you want you can open a support ticket from your tenant.
Hope this information helps you,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @dappleby300 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
