### ISSUE TITLE
Incorrect word in second paragraph

### ISSUE THREAD

**Issue by et01267** [MicrosoftDocs/office-docs-powershell#7562]
The word "complimentary" used in this document (e.g., in the second paragraph) should be "complementary".  Completely different meaning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a47ca7d5-2598-0c06-03fd-854f94cf6bbe
* Version Independent ID: a57408f6-16ca-3fcb-0c04-48a7a5f9942d
* Content: [New-ApplicationAccessPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-applicationaccesspolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@et01267 , fixed. In the future, you too can make simple fixes like this yourself without opening a GitHub issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
