### ISSUE TITLE
Connect-MicrosoftTeams for a delegated admin requires MFA even though it is on the MFA whitelist

### ISSUE THREAD

**Issue by wimvanhouts** [MicrosoftDocs/office-docs-powershell#7563]
As a delegated admin of my customer, I want to configure his Teams installation using powershell for some automated tasks. The customer's tenant has MFA enabled and conditional access as well, but, my IP address is on the MFA whitelist. When I use the powershell cmdlet Connect-MicrosoftTeams, it still requires a login via MFA. The cmdlet returns "Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access" or other errors alike. The "location" part is linked to the conditional access I believe, which would indeed require MFA from my location, but, that same IP address is in the whitelist. Why does this cmdlet not take into account MFA whitelist settings?

**Comment by get-itips** [comment]
Hello @wimvanhouts how are you? Hope you are doing good.
Analyzed your inquiry, and I think the best would be to open a support ticket from the tenant, to understand why is it not taking into account the whitelist settings, as here we are limited to documentation fixes and improvements. 
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @wimvanhouts Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
