### ISSUE TITLE
Help Files for *PnPAzureAD* Cmdlets Missing

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#7575]
Hi,

There are help files for *PnPAAD* cmdlets, however those are considered outdated:
![image](https://user-images.githubusercontent.com/5260172/114222464-4a33d180-9977-11eb-8b89-786ccb9a327d.png)

When running Get-Help against any PnPAzureAD cmdlet, it looks like there is not much details:
![image](https://user-images.githubusercontent.com/5260172/114222605-78b1ac80-9977-11eb-8411-3c3a25eabcca.png)

https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpazureaduser gives 404 error.

Is there any way you can generate missing files?

Thanks in advance,
Yuriy

**Comment by YuriySamorodov** [comment]
#7576

**Comment by get-itips** [comment]
Hello @YuriySamorodov 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by YuriySamorodov** [comment]
Thanks @get-itips!
Will do. Was not aware of the current workflow.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @YuriySamorodov Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
