### ISSUE TITLE
"BypassScopeCheck" doesn't exist?

### ISSUE THREAD

**Issue by Panzerbjrn** [MicrosoftDocs/office-docs-powershell#758]
I am trying to use Get-InboxRule on Exhange 2010, and the BypassScopeCheck paramater doesn't exist. I get this error:
A parameter cannot be found that matches parameter name 'BypassScopeCheck'.
    + CategoryInfo          : InvalidArgument: (:) [Get-InboxRule], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-InboxRule
    + PSComputerName        : exchange2.corporation.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb7d356a-b903-45af-7390-008a3c98d1e1
* Version Independent ID: 8822c739-073e-597b-a30f-7bc56e9e6d42
* Content: [Get-InboxRule (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-inboxrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-InboxRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-InboxRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nsshommo** [comment]
@Panzerbjrn Thanks for your valuable feedback. We are working on this.

@chrisda Do you know who can help me on this?

**Comment by chrisda** [comment]
@Panzerbjrn, the Exchange cmdlet reference topics are now single-sourced between Exchange 2010, 2013, 2016, Exchange Online, Exchange Online Protection, and Security & Compliance Center, you'll need to check the 'Applicable' property value on the parameter.

In this case, the BypassScopeCheck parameter is described as being applicable to Exchange 2016 and Exchange Online in the GitHub topic, and is only showing as Exchange 2016 on docs.microsoft.com, so there's no expectation that it's available in Exchange 2010.

**Comment by zaicnupagadi** [comment]
Hey Guys, I'm having troubles in finding it in Exchange Online as well, got exactly the same issue as Panzerbjrn described - is this an expected behaviour?

**Comment by chrisda** [comment]
@zaicnupagadi, the BypassScopeCheck parameter is available to me in a US E5 Exchange Online tenant. You get it from the "Security Group Creation and Membership" role, which is assigned to the "Organization Management" role group by default. You can confirm this by running these commands:

```
$Perms = Get-ManagementRole -Cmdlet Get-InboxRule -CmdletParameters BypassScopeCheck
$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}
```
