### ISSUE TITLE
Modify default value of AutomaticServiceUpdateEnabled

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/office-docs-powershell#7584]
Default value for existing tenants
AutomaticServiceUpdateEnabled: false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebaffb3-b4a1-9ba1-d6cb-cea3befecc89
* Version Independent ID: 8b7b857e-4090-d865-79dc-5e14f6fa7748
* Content: [Set-IRMConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-irmconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-IRMConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-IRMConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by trudolf-msft** [comment]
It seems the value is just for newer tenants (enabled by default) but not for older/existing ones.

**Comment by chrisda** [comment]
@trudolf-msft, I removed the statement about which value is the default. If we're going to talk about "new" and "existing" tenants, we need a date (month/year is fine).

Thanks for the feedback.

Closing
