### ISSUE TITLE
Different output in the "Results" property

### ISSUE THREAD

**Issue by uz-it** [MicrosoftDocs/office-docs-powershell#7586]
Please compare output in the "Results" property:

1. 

   ```powershell
   Get-ComplianceSearchAction -Case CaseID37 -Purge | fl
   
   RunspaceId : 53eab20f-483c-4d55-a7f1-4ac0f89c7df1
   SearchName : CaseID37_Search7
   EstimateSearchRunId : f3a17a1e-21bb-4c1b-82bd-08d8fd9ed002
   EstimateSearchJobId : 9e707ddf-f73d-4550-823c-08d8fd9ecf49
   ActionVersion :
   Results : Purge Type: HardDelete; Item count: 0; Total size 0; Details: {}
   Errors :
   Action : Purge
   ValidDuration : 00:10:00
   JobId : 2e54bd43-0dd5-423b-766c-08d8fda10abc
   Name : CaseID37_Search7_Purge
   CreatedTime : 12-04-2021 10:52:18
   LastModifiedTime : 12-04-2021 10:53:02
   JobStartTime : 12-04-2021 10:52:18
   JobEndTime : 12-04-2021 10:53:02
   Description :
   CreatedBy : Administrator - Me
   RunBy : Administrator - Me
   TenantId : 2cxxyyxxa-7xx6-4yy9-axx8-ffxxyyxxc7
   NumBindings : 0
   Status : Completed
   ExchangeLocation :
   PublicFolderLocation :
   SharePointLocation :
   OneDriveLocation :
   ExchangeLocationExclusion :
   PublicFolderLocationExclusion :
   SharePointLocationExclusion :
   OneDriveLocationExclusion :
   JobRunId : 94fe325c-9abe-4b1c-6d94-08d8fda10ac0
   Retry : False
   AllowNotFoundExchangeLocationsEnabled : False
   JobOptions : 272
   JobProgress : 100
   CaseId : d1eded85-fc68-455f-972d-06f6db70374c
   CaseName :
   PagingState :
   Identity : 94fe325c-9abe-4b1c-6d94-08d8fda10ac0
   ContentURL :
   ResultInEOP : False
   AzureBatchFrameworkEnabled : True
   IsValid : True
   ObjectState : New
   ```

and this:

2. 

   ```powershell
   Get-ComplianceSearchAction -Identity "CaseID37_Search7_Purge" | fl
   
   RunspaceId : 53eab20f-483c-4d55-a7f1-4ac0f89c7df1
   SearchName : CaseID37_Search7
   EstimateSearchRunId : f3a17a1e-21bb-4c1b-82bd-08d8fd9ed002
   EstimateSearchJobId : 9e707ddf-f73d-4550-823c-08d8fd9ecf49
   ActionVersion :
   Results : Purge Type: HardDelete; Item count: 26; Total size 1371699; Details: {Location: user1@domain.dk; Item count: 1; Total size: 55477; Failed count: 0; ,
   Location: user2@domain.dk; Item count: 1; Total size: 55267; Failed count: 0; ,
   Location: user3@domain.dk; Item count: 1; Total size: 55247; Failed count: 0; ,
   Location: user4@domain.dk; Item count: 1; Total size: 55214; Failed count: 0; ,
   Location: user5@domain.dk; Item count: 1; Total size: 55205; Failed count: 0; ,
   Location: user6@domain.dk; Item count: 1; Total size: 55201; Failed count: 0; ,
   Location: user7@domain.dk; Item count: 1; Total size: 55200; Failed count: 0; ,
   Location: user8@domain.dk; Item count: 1; Total size: 55195; Failed count: 0; ,
   Location: user9@domain.dk; Item count: 1; Total size: 55193; Failed count: 0; ,
   Location: user10@domain.dk; Item count: 1; Total size: 55186; Failed count: 0; ,
   Location: user11@domain.dk; Item count: 1; Total size: 55117; Failed count: 0; ,
   Location: user12@domain.dk; Item count: 1; Total size: 55083; Failed count: 0; ,
   Location: user13@domain.dk; Item count: 1; Total size: 55048; Failed count: 0; ,
   Location: user14@domain.dk; Item count: 1; Total size: 55019; Failed count: 0; ,
   Location: user15@domain.dk; Item count: 1; Total size: 55005; Failed count: 0; ,
   Location: user16@domain.dk; Item count: 1; Total size: 54982; Failed count: 0; ,
   Location: user17@domain.dk; Item count: 1; Total size: 54979; Failed count: 0; ,
   Location: user18@domain.dk; Item count: 1; Total size: 54931; Failed count: 0; ,
   Location: user19@domain.dk; Item count: 1; Total size: 54925; Failed count: 0; ,
   Location: user20@domain.dk; Item count: 1; Total size: 54914; Failed count: 0; ,
   Location: user21@domain.dk; Item count: 1; Total size: 54875; Failed count: 0; ,
   Location: user22@domain.dk; Item count: 1; Total size: 53934; Failed count: 0; ,
   Location: user23@domain.dk; Item count: 1; Total size: 52984; Failed count: 0; ,
   Location: user24@domain.dk; Item count: 1; Total size: 36955; Failed count: 0; ,
   Location: user25@domain.dk; Item count: 1; Total size: 36369; Failed count: 0; ,
   Location: user26@domain.dkk; Item count: 1; Total size: 34194; Failed count: 0; }
   Errors :
   Action : Purge
   ValidDuration : 00:10:00
   JobId : 2e54bd43-0dd5-423b-766c-08d8fda10abc
   Name : CaseID37_Search7_Purge
   CreatedTime : 12-04-2021 10:52:18
   LastModifiedTime : 12-04-2021 10:53:02
   JobStartTime : 12-04-2021 10:52:18
   JobEndTime : 12-04-2021 10:53:02
   Description :
   CreatedBy : Administrator - Me
   RunBy : Administrator - Me
   TenantId : 2cxxyyxxa-7xx6-4yy9-axx8-ffxxyyxxc7
   NumBindings : 26
   Status : Completed
   ExchangeLocation : {All}
   PublicFolderLocation :
   SharePointLocation :
   OneDriveLocation :
   ExchangeLocationExclusion :
   PublicFolderLocationExclusion :
   SharePointLocationExclusion :
   OneDriveLocationExclusion :
   JobRunId : 94fe325c-9abe-4b1c-6d94-08d8fda10ac0
   Retry : False
   AllowNotFoundExchangeLocationsEnabled : False
   JobOptions : 272
   JobProgress : 100
   CaseId : d1eded85-fc68-455f-972d-06f6db70374c
   CaseName : CaseID37
   PagingState :
   Identity : 94fe325c-9abe-4b1c-6d94-08d8fda10ac0
   ContentURL :
   ResultInEOP : False
   AzureBatchFrameworkEnabled : True
   IsValid : True
   ObjectState : New
   ```

**Comment by chrisda** [comment]
@uz-it, here's what I can see:

- Results line: Identity contains values for the following properties; Case contains 0/blank values for the same properties:
  -  ItemCount 26
  - Total size 1371699
  - Details: {Location: user1@domain.dk; Item count: 1; Total size: 55477; Failed count: 0; ,
- Location: These 14 lines are present in the Identity output but not in the Case output:

  Location: user2@domain.dk; Item count: 1; Total size: 55267; Failed count: 0; ,
  Location: user3@domain.dk; Item count: 1; Total size: 55247; Failed count: 0; ,
  Location: user4@domain.dk; Item count: 1; Total size: 55214; Failed count: 0; ,
  Location: user5@domain.dk; Item count: 1; Total size: 55205; Failed count: 0; ,
  Location: user6@domain.dk; Item count: 1; Total size: 55201; Failed count: 0; ,
  Location: user7@domain.dk; Item count: 1; Total size: 55200; Failed count: 0; ,
  Location: user8@domain.dk; Item count: 1; Total size: 55195; Failed count: 0; ,
  Location: user9@domain.dk; Item count: 1; Total size: 55193; Failed count: 0; ,
  Location: user10@domain.dk; Item count: 1; Total size: 55186; Failed count: 0; ,
  Location: user11@domain.dk; Item count: 1; Total size: 55117; Failed count: 0; ,
  Location: user12@domain.dk; Item count: 1; Total size: 55083; Failed count: 0; ,
  Location: user13@domain.dk; Item count: 1; Total size: 55048; Failed count: 0; ,
  Location: user14@domain.dk; Item count: 1; Total size: 55019; Failed count: 0; ,
  Location: user15@domain.dk; Item count: 1; Total size: 55005; Failed count: 0; ,
  Location: user16@domain.dk; Item count: 1; Total size: 54982; Failed count: 0; ,
  Location: user17@domain.dk; Item count: 1; Total size: 54979; Failed count: 0; ,
  Location: user18@domain.dk; Item count: 1; Total size: 54931; Failed count: 0; ,
  Location: user19@domain.dk; Item count: 1; Total size: 54925; Failed count: 0; ,
  Location: user20@domain.dk; Item count: 1; Total size: 54914; Failed count: 0; ,
  Location: user21@domain.dk; Item count: 1; Total size: 54875; Failed count: 0; ,
  Location: user22@domain.dk; Item count: 1; Total size: 53934; Failed count: 0; ,
  Location: user23@domain.dk; Item count: 1; Total size: 52984; Failed count: 0; ,
  Location: user24@domain.dk; Item count: 1; Total size: 36955; Failed count: 0; ,
  Location: user25@domain.dk; Item count: 1; Total size: 36369; Failed count: 0; ,
  Location: user26@domain.dkk; Item count: 1; Total size: 34194; Failed count: 0; }

- NumBindings property: 0 in Case output; 26 in Identity output.
- ExchangeLocation property: Blank in Case output; {All} in Identity output.
- CaseName property: Blank in Case output; CaseID37 in Identity output.

Is there an expectation that the output from the Identity, Preview, Purge, and Export parameters is the same?

**Comment by uz-it** [comment]
@chrisda 
I have no expectations, just can see the difference in the output. If it is by design, so it just need to be documented.

Nice to have addition to the command:
add: -SearchName property to be able to filter Actions by search name.

**Comment by chrisda** [comment]
@uz-it, the description for the Case parameter says "reserved for  internal Microsoft use", which means you aren't supposed to use it. Out of curiosity, do you get the same information with the Identity command if you also use the Details switch?

**Comment by chrisda** [comment]
@uz-it, I updated the Identity parameter description to say that more details are returned in the results, and I updated the Case parameter description.

For your nice to have suggestion, I can't do anything about that here in documentation. I would suggest that you open a support  case.

Thanks for the feedback.

Closing
