### ISSUE TITLE
Mistake in Example 1

### ISSUE THREAD

**Issue by m600ant** [MicrosoftDocs/office-docs-powershell#759]
Example 1 states " Get-ActiveSyncDeviceStatistics -Identity TonySmith "  This is incorrect as the -identity parameter is for the <ActiveSyncDeviceIdParameter> not the user,   it should be  Get-ActiveSyncDeviceStatistics -mailbox TonySmith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9d90b2-695e-59b0-92c2-ab9bcf43a78e
* Version Independent ID: 5647aff0-b7e9-a057-a63d-03b667a8c4b4
* Content: [Get-ActiveSyncDeviceStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/devices/get-activesyncdevicestatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/devices/Get-ActiveSyncDeviceStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/devices/Get-ActiveSyncDeviceStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nsshommo** [comment]
@m600ant Thanks for letting us know.

@chrisda Can you please confirm me so I can update this one?

**Comment by chrisda** [comment]
Fixed

**Comment by nsshommo** [comment]
Thanks.
