### ISSUE TITLE
Forward to Channel | Parameter ChannelId and ChannelUserObjectId missing

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7593]
Hello,

I know the feature is not yet released, but the Parameters are already present on the Command.

- Documentation of Forwarding to Channel in general 

Parameters in Particular are missing.

- ChannelId 
- ChannelUserObjectId

I presume this will be the same for Set-CsCallQueue

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b26bf80-4e1f-4172-e003-29fd1a28928c
* Version Independent ID: 7d0d9c25-c6f1-4ae3-b4e3-3b6de536ffa3
* Content: [New-CsCallQueue (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@DEberhardt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
