### ISSUE TITLE
the example section is empty

### ISSUE THREAD

**Issue by FadJee** [MicrosoftDocs/office-docs-powershell#760]
can you please review the example section as it is empty

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8cb1ce3-02eb-3219-cfbd-c2ee9e686ec3
* Version Independent ID: 76cbff88-ed92-b07a-4242-78e6d21eb1b2
* Content: [Remove-SPDistributedCacheServiceInstance (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/Remove-SPDistributedCacheServiceInstance?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Remove-SPDistributedCacheServiceInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Remove-SPDistributedCacheServiceInstance.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@FadJee Thank you for your feedback

It looks like this issue has been resolved by Trevor. I am going to close this issue. If this is not resolved please reopen the issue.
