### ISSUE TITLE
Erroneous example

### ISSUE THREAD

**Issue by jasonhsewell** [MicrosoftDocs/office-docs-powershell#7601]
The Get-DlpSiDetectionsReport [documentation](https://docs.microsoft.com/en-us/powershell/module/exchange/get-dlpsidetectionsreport?view=exchange-ps) contains the following erroneous example. This example generates an error because StartDate is not a valid parameter for the Get-DlpSiDetectionsReport commandlet.

    Get-DLPSiDetectionsReport -SensitiveType 0e9b3178-9678-47dd-a509-37222ca96b42 -StartDate 4/1/2019 -EndDate 4/8/2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 601d8f7c-e528-98e3-9471-bc12c5bfb1fb
* Version Independent ID: c885419d-a9c0-f715-0da4-9372662b974d
* Content: [Get-DlpSiDetectionsReport (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-dlpsidetectionsreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-DlpSiDetectionsReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-DlpSiDetectionsReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jasonhsewell, fixed.

Thanks for the feedback.

Closing
