### ISSUE TITLE
get-safelinksdetailreport case sensitivity

### ISSUE THREAD

**Issue by coproyer** [MicrosoftDocs/office-docs-powershell#7604]
I've always been led to believe that PowerShell is case insensitive however, the documentation at https://docs.microsoft.com/en-us/powershell/module/exchange/get-safelinksdetailreport?view=exchange-ps does not state that case sensitivity for parameter values is a pre-requisite.  For example,

> `get-safelinksdetailreport -startdate 04-11-2021 -enddate 04-13-2021 -action blocked`

returns no results whereas

> `get-safelinksdetailreport -startdate 04-11-2021 -enddate 04-13-2021 -action Blocked`

returns expected results.

The documentation, including examples at the page and within `get-help get-safelinksdetailreport`, uses CamelCase however makes no notation that CamelCase is _required_.  Evaluation of either parameter values should be case insensitive or the documentation should be updated to reflect the CamelCase requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74c0d51f-873f-8a82-69b9-f27fb31b3eaf
* Version Independent ID: aad53fd4-dee4-bbb4-4135-2c974e688968
* Content: [Get-SafeLinksDetailReport (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-safelinksdetailreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-SafeLinksDetailReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-SafeLinksDetailReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@coproyer, that value should not be case sensitive. I suggest that you open a support case and see what they say. Report back here and we'll update the topic as necessary.

**Comment by coproyer** [comment]
As expected, having access only to the O365 Support from the adminportal, that route returned totally anticipated results: "we'll notify the Exchange product team of the issue and in the meantime ask to have the documentation updated to note the case sensitivity issue."



Michael Royer
IT Security Officer
Department of Information Technology * City of Pasadena<http://www.cityofpasadena.net/>
+1 (626) 744-7929 * ***@***.******@***.***>

[cid:554245fb-148d-41df-8c22-f449f04614d9] Using Microsoft Teams<https://teams.microsoft.com/>?  Click ***@***.***> to chat with me on Microsoft Teams.

**Comment by chrisda** [comment]
Yikes. I don't want to update the documentation for a bug that they're going to fix, only to modify the topic again after they fix it. I'd rather wait a bit until we find out what's going on.
