### ISSUE TITLE
Remove-MailboxPermissions Manual Errors

### ISSUE THREAD

**Issue by Mattheww65** [MicrosoftDocs/office-docs-powershell#7614]
Some switch descriptions not showing, for example:

{{ Fill BypassMasterAccountSid Description }}
{{ Fill GroupMailbox Description }}
{{ Fill SoftDeletedMailbox Description }}

Browsers tested: Firefox 87.0, Edge 89.0.774.76

Also, a clearer description for AccessRights would be appreciated. Its not really the rights required to perform the operation, but the rights that will be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f0820df-de2a-1032-8e9d-ab0a91ec9a25
* Version Independent ID: abb4e51e-0c72-1472-f820-4657d2c76543
* Content: [Remove-MailboxPermission (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-mailboxpermission?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Remove-MailboxPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-MailboxPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by Mattheww65** [comment]
![image](https://user-images.githubusercontent.com/73503344/114790265-afa20c80-9d41-11eb-8835-5fd14e7efaaf.png)
![image](https://user-images.githubusercontent.com/73503344/114790282-b892de00-9d41-11eb-8266-63d62947ce09.png)
![image](https://user-images.githubusercontent.com/73503344/114790304-c6486380-9d41-11eb-8d1b-e149a60d0bdf.png)

**Comment by chrisda** [comment]
@Mattheww65, let's break it down:

- **Empty parameter descriptions**: I believe you. See the end of <https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429>. Are these parameters available to you? Do they work as you expect?

- **Clearer description for AccessRights parameter**: Agreed and done. Updates will publish tomorrow Th 4/15 mid morning latest.

**Comment by Mattheww65** [comment]
Morning @chrisda 

We need to use -SoftDeletedMailbox switch to remove permissions when a mailbox is soft deleted. Just done some basic testing and without that switch, the command cannot find the soft-deleted mailbox. See screenshot below.

![image](https://user-images.githubusercontent.com/73503344/114889085-0867b880-9dc7-11eb-8a60-86db534d7be5.png)

**Comment by chrisda** [comment]
@Mattheww65, excellent. I added descriptions for SoftDeletedMailbox and GroupMailbox.

**Comment by chrisda** [comment]
Of course you used Bing to find this, right ;-)? I added a parameter description.

Now that all items have been fixed, I'm closing this issue.

Thanks for the feedback.
