### ISSUE TITLE
PowerShell help not available in MicrosoftTeams v2.x

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7617]
Hello,

don't know where to best put this, but since upgrading to MicrosoftTeams v2.0.0, the builtin help system does not work anymore.

I have a valid and open connection to MicrosoftTeams (and have run a SkypeOnline CmdLet to establish the PSSession), but the below doesn't tell me what is broken.

```powershell
❯ Get-help Set-CsCallQueue
Get-help : Cannot get Help from a remote runspace, because the runspace has not been opened.  Open the runspace
by running an implicit remoting command, and then try running the command to get Help again.
At line:1 char:1
+ Get-help Set-CsCallQueue
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Help], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.GetHelpCommand

```

Help is appreciated to fix (if client issue) or forward to correct team (if Module issue).

Cheers,
David

**Comment by get-itips** [comment]
Hello @DEberhardt David, **thanks**, will try to pass this on, as here we are limited to documentation fixes.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DEberhardt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Mohamad-Attar** [comment]
Hello @yogkumgit , I can't find the comment, can you please post it again? Thanks in advance
