### ISSUE TITLE
LocaleSettings for Visual Marking text

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/office-docs-powershell#7618]
How can the text for Visual Markings (headers, footer and watermark) be provided in alternate languages ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf754e37-7113-f7d1-ad1e-ef0c3eb5b5e7
* Version Independent ID: 1b20db7d-a508-8523-2309-a3d9f5d08dd7
* Content: [Set-Label (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Label.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Label.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bholzmmc, it appears the LocaleSettings parameter only affects the label name and Tooltip.

In the Security & Compliance Center, can you configure locale-specific values for the header, footer, and watermark? If not, then you probably can't do it using the cmdlet, either.

If you would like to see such functionality added, I would suggest opening a support case and asking for it.

**Comment by yogkumgit** [comment]
@bholzmmc Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
