### ISSUE TITLE
Why is this cmdlet not present in the new versions of MicrosoftTeams powershell module? We can find it in older versions only 1.1.3?

### ISSUE THREAD

**Issue by Mr-K07** [MicrosoftDocs/office-docs-powershell#7626]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd91d571-ca88-5766-2666-d6a4d34cdbed
* Version Independent ID: 2481b258-b593-e323-90f0-e9ca6e7797bf
* Content: [Add-TeamChannelUser (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @Mr-K07 how are you? Hope you are doing good.
I can not say why it is not present in the latest General Availability version, probably the team pulled it to improve it in the -preview version, but I do not know exactly.
