### ISSUE TITLE
Need to update EventType parameter's definition for Get-MailDetailATPReport command.

### ISSUE THREAD

**Issue by goyoshid** [MicrosoftDocs/office-docs-powershell#7631]
**Summary**
`EventType` parameter's definition for Get-MailDetailATPReport command is not up to date even though valid values for the parameter has changed recently.
Please update valid values and descriptions for updated EventType paramter.

**Details**
Current document says the valid values for EventType are below:
```
Advanced phish filter
Anti-spoof: Intra-org
Anti-spoof: external domain
ATP-generated URL reputation
Domain impersonation
Brand impersonation
General phish filter
Malicious URL reputation
Phish ZAP
User impersonation
Anti-malware engine
Anti-malware policy file type block
ATP-generated file reputation
ATP safe attachments
ATP safe links
File Detonation
Malware ZAP
Office 365 file reputation
AtpDocumentMalware
AvDocumentMalware
```

However, we get following error when using almost all of the parameters listed above, except "Anti-malware engine" and "File Detonation".
```
> Get-MailDetailATPReport -EventType "Advanced phish filter"
Invalid input: Advanced phish filter [CustomInternalValidate, GetMailDetailATPReport.cs:140]
    + CategoryInfo          : InvalidArgument: (:) [Get-MailDetailATPReport], ValidationException
    + FullyQualifiedErrorId : [Server=BY5PR10MB4321,RequestId=30b277f5-996f-4cf6-9b80-87085593fc75,TimeStamp=4/16/2021
    5:51:16 PM] [FailureCategory=Cmdlet-ValidationException] C29C83C5,Microsoft.Exchange.Management.FfoReporting.GetM
  ailDetailATPReport
    + PSComputerName        : outlook.office365.com
```
(*) Please see uploaded fiile [PowerShell_transcript_20210417030302.txt](https://github.com/MicrosoftDocs/office-docs-powershell/files/6327133/PowerShell_transcript_20210417030302.txt) for test results for all of the currently listed parameters.

After investigation, confirmed that following new values are valid input for EventType parameter:
```
Message passed
General filter
Impersonation brand
Spoof external domain
Spoof DMARC
Impersonation domain
File Detonation
File Reputation
File detonation reputation
Fingerprint matching
Spoof intra-org
Advanced filter
Anti-malware Engine
Mixed analysis detection
URL malicious reputation
URL detonation
URL detonation reputation
Impersonation user
Campaign
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a47576-e439-efc4-6a22-c9c6a11edbe3
* Version Independent ID: bd26162f-3fde-657a-0eb1-c6b49fbdccc7
* Content: [Get-MailDetailATPReport (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-maildetailatpreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailDetailATPReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MailDetailATPReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@goyoshid, thanks for the legwork. Topic updated as you described.

Closing

**Comment by goyoshid** [comment]
@chrisda 
Thank you for your quick work.
