### ISSUE TITLE
Syntax is incorrect for URL string

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/office-docs-powershell#7634]
The syntax is incorrect for the URL string as it is missing the double quotes

it needs to be in the following format or does not work

Get-PnPFile -Url "/sites/Automation/Shared Documents/test.csv" 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1494ac7-090d-db80-ba26-5cdcc10d9eac
* Version Independent ID: e3837ec6-d90c-35c4-a563-4313ffb11fb6
* Content: [Get-PnPFile (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpfile?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFile.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @nikki-c 
How are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @nikki-c Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
