### ISSUE TITLE
Get-Team -DisplayName returns partial matches

### ISSUE THREAD

**Issue by rjohanneson** [MicrosoftDocs/office-docs-powershell#7636]
Using the get-team -displayName "Team Name" returns teams that do not exactly match the supplied team name.

Example:
Get-Team -displayname "Art 4MS" -archived $false | select GroupID, DisplayName

GroupId                              DisplayName              
-------                              -----------              
deleted English Language Arts 4MS
deleted Art 4MS

Based on the documentation the command above should not have returned the first team listed in the results.

**Comment by get-itips** [comment]
Hello @rjohanneson thanks for your feedback, I could reproduce so I will propose a different wording for the Get-Team article.
Thanks again

**Comment by tos-kamiya** [comment]
Hi,

I have several teams that I manage with sequential numbers, and I am trying to add members with a script such as:

Connect-MicrosoftTeams
foreach($u in $users){
    Get-Team -DisplayName $team_Name | Add-TeamUser -User $u -Role Member
}

I didn't know that Get-Teams does fuzzy matching, so when I ran the above script, I got surprising results.

Can you please provide an option for exact matching other than this fuzzy matching?

**Comment by tos-kamiya** [comment]
Solution?

I changed the team names from Software Engineering-1, Software Engineering-2, Software Engineering-3, to something like Software Engineering-Bunny, Software Engineering-Pony, Software Engineering-Penguin.

**Comment by tos-kamiya** [comment]
Thank you for delving into the issue in such detail. While I personally have been mindful to avoid this behavior and haven't faced the same problem, I genuinely sympathize with others who have encountered the same issue.

As you rightly pointed out, it would be desirable to change this behavior. However, from what I've observed, it's often a traditional stance of MS not to alter behaviors, even if they are bugs, that might impact existing applications.
