### ISSUE TITLE
Update with StreamingModeEnabled

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/office-docs-powershell#7637]
There is no documentation about 
property: StreamingModeEnabled

And in the headline it mention this policy is for Skype for business but it also affect Teams right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by JohanssonMarkus** [comment]
Hey, @get-itips 
I noticed the parameter is available when running Get-CsTeamsMeetingPolicy

PS C:\> Get-CsTeamsMeetingPolicy -Identity global |select id*, AllowMeetingRegistration,WhoCanRegister,AllowEngagementReport,StreamingModeEnabled

Identity                 : Global
AllowMeetingRegistration : True
WhoCanRegister           : EveryoneInCompany
AllowEngagementReport    : Enabled
StreamingModeEnabled     :

However in the Set-CsTeamsMeetingPolicy the option is missing so not only the docs needs to be updated but also the ps module. How can I as an admin toogle the possibility to off/disabled? 

PS C:\> Set-CsTeamsMeetingPolicy -SpeakerAttributionMode
SpeakerAttributionMode  StreamingAttendeeMode   ScreenSharingMode

This is my version.

PS C:\> (Get-Module microsoftteams).version

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      0      -1

**Comment by get-itips** [comment]
Hello @JohanssonMarkus 
Markus, thanks for your clarification, what you saw in the output for `Get-CsTeamsMeetingPolicy` is a property, not necessarily a parameter that should be available in the `Set-`, usually when this happens, maybe the property is not generally available to be settable.
Hope this information helps you,
Andrés

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @JohanssonMarkus Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
