### ISSUE TITLE
Change Site Collection URL from C#

### ISSUE THREAD

**Issue by TomekPi** [MicrosoftDocs/office-docs-powershell#7643]
Is there an equivalent for Start-SPOSiteRename command in CSOM C#?
Or is there any other way to change SPO Site Collection URL from code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 833251ee-5a0c-fb40-7424-eb6ad7a25444
* Version Independent ID: 1751767f-1d8a-7750-35b9-725b5a3ad705
* Content: [Start-SPOSiteRename (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/start-spositerename?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteRename.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteRename.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @TomekPi how are you? Hope you are doing good!
Here, we are limited to documentation changes and improvements for PowerShell content.
Maybe a good start to find out what you are looking for could be this [another resource](https://github.com/SharePoint/sp-dev-docs)
Hope this helps you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @TomekPi Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
