### ISSUE TITLE
How can I filter by MailboxPermission?

### ISSUE THREAD

**Issue by TsuMakoto** [MicrosoftDocs/office-docs-powershell#7657]
I'm using `Get-EXOMailbox -RecipientTypeDetails SharedMailbox -ResultSize Unlimited`.
However, it takes too long to retrieve and times out.
So I would like to filter by mailbox members.
How can I narrow down the number of retrievals using `Get-EXOMailboxPermission` or other methods?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75cb7bca-b0ec-5cb0-ef5b-98fece1cd9de
* Version Independent ID: 24006ac8-9938-6dfd-738f-b66ef7e1174f
* Content: [Get-EXOMailbox (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-exomailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-EXOMailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-EXOMailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @TsuMakoto, thank you for your feedback.

How many shared mailboxes do you have? Exchange Online PowerShell V2 module has a much better performance compared to V1. For more information, please see:
https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#properties-and-property-sets-in-the-exo-v2-module
https://techcommunity.microsoft.com/t5/exchange-team-blog/faster-and-more-reliable-exchange-online-management-using/ba-p/1198604

I think you can also try with the -Filter parameter. Please check that you are also using the latest version of the EXO PowerShell module.
