### ISSUE TITLE
Issue using Connect-IPPSSession with DelegatedOrganization parameter for some (not all) tenants

### ISSUE THREAD

**Issue by thesauce98** [MicrosoftDocs/office-docs-powershell#7658]
Using new EXOv2 module, with my own MFA enabled partner admin account.  Trying to connect to Security and Compliance center via powershell for all of my tenants I have delegated admin permissions to.  Out of 60 tenants, 16 connect successfully while the rest give me the message "Access Denied" as seen below.
`Connect-IPPSSession -UserPrincipalName myself@mydomain.com -DelegatedOrganization mytenant.com`
```
WARNING: Your connection has been redirected to the following URI:
"https://nam04b.ps.compliance.protection.outlook.com/Powershell-LiveId?DelegatedOrg=mytenant.com&amp;BasicAuthToOAuthCon
version=true;PSVersion=5.1.19041.906"
New-ExoPSSession : Connecting to remote server nam04b.ps.compliance.protection.outlook.com failed with the following
error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.
At C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.4\netFramework\ExchangeOnlineManagement.psm1:475 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-ExoPSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Exchang
   e.Management.ExoPowershellSnapin.NewExoPSSession
```

Strangely, for the tenants that give me the access denied message with SCC -  if I connect just to Exchange with delegatedOrganization set, it connects just fine.
 `Connect-ExchangeOnline -UserPrincipalName myself@mydomain.com -DelegatedOrganization mytenant.com`

I'm not sure if there's a setting or permission issue that would be preventing me from connecting to SCC for all these tenants I have DAP to.  It's very strange that some connect, but most do not.  And I cannot find any similarities or differences with the tenants that work verse the ones that don't.

**Comment by thesauce98** [comment]
Tried both, no luck.  

First command did not work because "get-credential" is for basic authentication, and does not prompt for modern authentication.  My account is MFA enabled - as per Microsoft's terms for partners - all accounts with delegated admin permissions must use MFA.

Second command also did not work and resulted in same exact response - "Access is denied".  Additionally, this command also results in "Access is denied" for the few tenants that did successfully connect when using the Conenct-IPPSSession method.  So this method does not work any tenant.

**Comment by chrisda** [comment]
@thesauce98, the next step is to open a support case.

**Comment by thesauce98** [comment]
@chrisda I was afraid it would come to that.  What would be the best method to do that?  I wasn't sure if I should open a case through the Partner Center portal, or some other way that would get to the correct department/person who could assist with this.

**Comment by chrisda** [comment]
Partner Center portal sounds OK.

**Comment by yogkumgit** [comment]
@thesauce98 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
