### ISSUE TITLE
Conflicting information in the description of the -Alias option

### ISSUE THREAD

**Issue by zaaj** [MicrosoftDocs/office-docs-powershell#7665]
the stanza describing the -Alias option states that if you create a recipient and do not specify an email address, the Alias value will be used to generate the primary email address.  The last sentence of the stanza states that the Alias value never updates or generates the primary email address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f835af-5905-368a-df68-6646782ad807
* Version Independent ID: 153ce2d2-dab5-9c8f-c511-ee3bc8ee2dbc
* Content: [Set-Mailbox (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@zaaj , the last line of the Alias parameter descriptions says this, which is accurate:

> The Alias parameter never generates or updates the primary email address of a mail contact or a mail user.

For mailboxes, the Alias parameter is able to generate the primary email address.

**Comment by yogkumgit** [comment]
@zaaj Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
