### ISSUE TITLE
Missing parameter documentation in Set-MailboxRegionalConfiguration

### ISSUE THREAD

**Issue by mnadvornik** [MicrosoftDocs/office-docs-powershell#7666]
The description for the ``-Archive`` Parameter ist missing in the Documentation for the PowerShell Command ``Set-MailboxRegionalConfiguration``
Since the documentation shows the Placeholder ``{{ Fill Archive Description }}`` it seems like this is a mistake.

Would be great if this can be corrected

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573e63b4-b27b-5b7b-9269-78d308fd64d3
* Version Independent ID: 57b35909-0381-1181-58bb-2262c33576d1
* Content: [Set-MailboxRegionalConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxregionalconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxRegionalConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-MailboxRegionalConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mnadvornik, see the discussion in <https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429>. Do you use this parameter? Does it work as you expect?

**Comment by chrisda** [comment]
Empty parameter descriptions are a known issue.

Thanks for the feedback.

Closing
