### ISSUE TITLE
Need to specify Library

### ISSUE THREAD

**Issue by ingepepe** [MicrosoftDocs/office-docs-powershell#7670]
In EXAMPLE 1, you can read:

```
Resolve-PnPFolder -SiteRelativePath "demofolder/subfolder"
Creates a folder called subfolder in a folder called demofolder located in the root folder of the site.
If the folder hierarchy does not exist, it will be created.
```

If entered like this, I get the following error:

```
Resolve-PnPFolder : Access denied. You do not have permission to perform this action or access this resource.
At line:1 char:1
+ Resolve-PnPFolder -SiteRelativePath "demofolder/subfolder"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Resolve-PnPFolder], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.ResolveFolder
```

When entering the path WITH the library on it:

`Resolve-PnPFolder -SiteRelativePath "Shared Documents/demofolder/subfolder"`

It works:

```
Name      Type   Items/Size Last Modified        
----      ----   ---------- -------------
subfolder Folder          0 2021-04-22 5:22:17 PM
```

Please update the example and the parameter description to reflect the need to include the library name in the path

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f4725f2-8dd3-0424-ef84-6609a027059e
* Version Independent ID: db127d3e-160f-25de-784e-79b26b7f8b68
* Content: [Resolve-PnPFolder (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/resolve-pnpfolder?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Resolve-PnPFolder.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Resolve-PnPFolder.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @ingepepe 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ingepepe Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
