### ISSUE TITLE
Azure App Permissions Documentation

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/office-docs-powershell#7673]
Can you document what Azure App permissions are required to run this command "Get-PnPFlowEnvironment"? Our environment requires us to start with the base minimal set of permissions. From a security perspective we need this documented for each cmdlet.

This is what we have to start...
![image](https://user-images.githubusercontent.com/1613085/115786286-32e8e100-a386-11eb-8237-4f1424fe8d39.png)

This is the error I receive...
![image](https://user-images.githubusercontent.com/1613085/115786756-db974080-a386-11eb-82a9-6745d9f9c5d7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2072acab-0070-4b73-7567-98e33a7281f2
* Version Independent ID: f7741f9f-bc33-17ca-9d88-412791eba12b
* Content: [Get-PnPFlowEnvironment (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpflowenvironment?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFlowEnvironment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFlowEnvironment.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @robertcaretta 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!
