### ISSUE TITLE
Export-CsAutoAttendantHolidays only saves dates, not actions

### ISSUE THREAD

**Issue by mwilens** [MicrosoftDocs/office-docs-powershell#7675]
In Module MicrosoftTeams 2.0 it would be convenient that Export-CsAutoAttendantHolidays could also be saving the action and greeting (even if only TTS)

**Comment by get-itips** [comment]
Hello @mwilens how are you?
Here, we are limited to documentation fixes and improvements, hope I could help you.
Thanks

**Comment by mwilens** [comment]
thanks for informing me, I created an uservoice at:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/43321176-export-and-import-autoattendantholidays-actions-an
