### ISSUE TITLE
MicrosoftTeams 2.2.0-preview import failure - MacOS

### ISSUE THREAD

**Issue by Nestorfish** [MicrosoftDocs/office-docs-powershell#7679]
Module MicrosoftTeams 2.2.0-preview fails to import:

<pre>
PowerShell 7.2.0-preview.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /Users/me> Get-InstalledModule -AllVersions MicrosoftTeams

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.1.0-preview        MicrosoftTeams                      PSGallery            Microsoft Teams cmdlets module for Windows PowerShell and PowerShell Core.…
2.2.0-preview        MicrosoftTeams                      PSGallery            Microsoft Teams cmdlets module for Windows PowerShell and PowerShell Core.…

PS /Users/me> Import-Module -Name MicrosoftTeams
Import-Module: The given assembly name or codebase was invalid. (0x80131047)
PS /Users/me> Import-Module -RequiredVersion 2.1.0 MicrosoftTeams
PS /Users/me> Test-ModuleManifest .local/share/powershell/Modules/MicrosoftTeams/2.1.0/MicrosoftTeams.psd1
WARNING: The module manifest member 'ModuleToProcess' has been deprecated. Use the 'RootModule' member instead.

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     2.1.0      preview    MicrosoftTeams                      {Add-TeamUser, Connect-MicrosoftTeams, Disconnect-MicrosoftTeams, Get-Team…}

PS /Users/me> Test-ModuleManifest .local/share/powershell/Modules/MicrosoftTeams/2.2.0/MicrosoftTeams.psd1
Test-ModuleManifest: The module manifest 'netcoreapp2.1\Microsoft.TeamsCmdlets.PowerShell.Custom.dll' could not be processed because it is not a valid PowerShell module manifest file. Remove the elements that are not permitted: /Users/me/.local/share/powershell/Modules/MicrosoftTeams/2.2.0/MicrosoftTeams.psd1
Test-ModuleManifest: The specified NestedModule entry 'netcoreapp2.1\Microsoft.Teams.ConfigAPI.Cmdlets.psd1' in the module manifest '/Users/me/.local/share/powershell/Modules/MicrosoftTeams/2.2.0/MicrosoftTeams.psd1' is invalid. Try again after updating this entry with valid values.

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     2.2.0      preview    MicrosoftTeams                      {Add-TeamUser, Connect-MicrosoftTeams, Disconnect-MicrosoftTeams, Get-MultiGeoRegion…}
</pre>

MacOS Big Sur 11.2.3
Powershell 7.2.0-preview.5

**Comment by sulbig** [comment]
I was having a similar issue on Windows just now. Had to open the 'Modules/MicrosoftTeams/2.2.0/MicrosoftTeams.psd1' file and replace all instances of "netcoreapp2.1" with "netcoreapp3.1". Perhaps the issue is similar on macOS?

**Comment by sulbig** [comment]
I can confirm the same issue exists in the same file on macOS.

**Comment by Nestorfish** [comment]
Fixed in 2.3.0
