### ISSUE TITLE
GCC High/DoD MetaDataUrl value incorrect

### ISSUE THREAD

**Issue by aandrew129** [MicrosoftDocs/office-docs-powershell#7680]
Recently confirmed with MS support that Example 3 value of ..."-MetadataUrl https://login.microsoftonline.us/FederationMetadata/2006-12/FederationMetadata.xml" is incorrect. 

GCC High and DoD environments should use the commercial endpoint of "https://nexus.microsoftonline-p.com/federationmetadata/2006-12/federationmetadata.xml"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 735c19cd-ae78-cd92-6fb7-48f99264700e
* Version Independent ID: 853c38f7-536f-a642-9073-074954684c58
* Content: [Set-FederationTrust (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-federationtrust?view=exchange-ps#example-3)
* Content Source: [exchange/exchange-ps/exchange/Set-FederationTrust.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-FederationTrust.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@aandrew129, OK. Done.

Thanks for the feedback.

Closing
