### ISSUE TITLE
Setting External Email Flag

### ISSUE THREAD

**Issue by hs-uol** [MicrosoftDocs/office-docs-powershell#7685]
Please can you advise if this can be applied to a subset of a tenancy (a group of users) rather than tenancy wide, to allow testing.

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba41cae3-da51-0a3d-1652-bce98452d4dc
* Version Independent ID: a2d20c87-6277-a868-3c2e-e2fe225e6f17
* Content: [Set-ExternalInOutlook (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-externalinoutlook?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-ExternalInOutlook.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-ExternalInOutlook.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hs-uol, judging by the lack of a specific mailbox identifier in the cmdlet, the setting appears to be organization-wide, not selective.

**Comment by hs-uol** [comment]
Thanks @chrisda. I also managed to confirm directly with Microsoft Support today.

**Comment by yogkumgit** [comment]
@hs-uol Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
