### ISSUE TITLE
LinkType "EventSubscribers" is not documented

### ISSUE THREAD

**Issue by larspassic** [MicrosoftDocs/office-docs-powershell#7687]
When running Get-Help -Name Add-UnifiedGroupLinks, there is a value for the LinkType parameter called "EventSubscribers" please add documentation for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1061fe5-43fc-5677-49fe-1cee4163659a
* Version Independent ID: 08387a45-1c88-9803-8168-fb9079130b9d
* Content: [Add-UnifiedGroupLinks (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/add-unifiedgrouplinks?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Add-UnifiedGroupLinks.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@larspassic, the Add-UnifiedGroupLinks cmdlet has been updated on the web to remove that value. The same topic is also used for help at the command line, but there's always a lag.

Thanks for the feedback.

Closing
