### ISSUE TITLE
Example 3 is invalid

### ISSUE THREAD

**Issue by SharePointOz** [MicrosoftDocs/office-docs-powershell#7688]
The example 3 on this document is not valid since -FromRecycleBin is no longer a parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1478cc6-1cef-7ebc-1bc8-4f2c88996c5d
* Version Independent ID: b28c262d-dc7f-e7bf-5d6c-3bea6f2aa473
* Content: [Remove-PnPTenantSite (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnptenantsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPTenantSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPTenantSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello! @SharePointOz Neville 👍 

How are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @SharePointOz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by SharePointOz** [comment]
Thanks @yogkumgit & @get-itips
