### ISSUE TITLE
LinkType "EventSubscribers" is not documented

### ISSUE THREAD

**Issue by larspassic** [MicrosoftDocs/office-docs-powershell#7689]
I have a situation where I need to perform a management task on all of the EventSubscribers of a UnifiedGroup. When I use Get-Help -Name Get-UnifiedGroupLinks, there is a value called "EventSubscribers" however when I try to use this value with Get-UnifiedGroupLinks -LinkType, I receive an error message: _"Invalid value for LinkType parameter."_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a66e3b7-94f5-f1f1-3b95-4fd8337b15b3
* Version Independent ID: c849c0a5-96f0-fd15-2991-b75b02169424
* Content: [Get-UnifiedGroupLinks (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-unifiedgrouplinks?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-UnifiedGroupLinks.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-UnifiedGroupLinks.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@larspassic, see related Issue [7207](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7207). The content on the web has been updated to remove EventSubscribers as a possible value for the LinkType parameter. Although this same content is used for help at the command line (`Get-Help <Cmdlet>`), there's always a lag. The content on the web is always more up-to-date than the help at the command line.

As per the other issue, if you need to get a list of only subscribers to the group, please open a support case and ask how you're supposed to do that without the EventSubscribers value for the LinkType parameter.

**Comment by yogkumgit** [comment]
@larspassic Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
