### ISSUE TITLE
Explanation for error message "Access to the requested resource is forbidden." is missing

### ISSUE THREAD

**Issue by EricHindrichsen** [MicrosoftDocs/office-docs-powershell#7691]
Hi,

When running Get-MyAnalyticsFeatureConfig I'm getting the error message "Access to the requested resource is forbidden." for some of my users. Now, I'm running it as a global admin, and I can get (and set) the config for most of my users, so I'm guessing that this error message means something else other than missing permissions (e.g. user never initialized MyAnalytics, user doesn't have the proper license…).

Can you please add an explanation for that error message to the page, since it seems to be happening quite often?

Thanks!

Kind regards,
Eric

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17a8e022-3001-159b-ed74-6f8f65d83f7e
* Version Independent ID: 085da135-7076-d0ff-f0c9-47edb46fc5d7
* Content: [Get-MyAnalyticsFeatureConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-myanalyticsfeatureconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MyAnalyticsFeatureConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by EricHindrichsen** [comment]
Hi @chrisda, do you need any more input from my side?

**Comment by chrisda** [comment]
@EricHindrichsen, if you have the required permissions as described in the topic and you still get the error, then your best course of action is to open a support case for the users where the action is failing.

**Comment by yogkumgit** [comment]
@EricHindrichsen Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
