### ISSUE TITLE
Please provide Example that uses the Identity Parameter

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/office-docs-powershell#7693]
As Title - Please provide Example that uses the Identity Parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0dce05-8bfd-0bfa-3753-0eb193852703
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @kilasuit Ryan, how are you? hope you are doing good 👍 
I have been digging into this, it seems that currently, the `-Identity` parameter is not ready, the team behind the module is working on this and, as soon as it is, I'll update the article including an example using the `-Identity` parameter.
Thank you

**Comment by yogkumgit** [comment]
@pupara Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@pbafna03 @get-itips Kindly address this issue. Thanks

**Comment by yogkumgit** [comment]
@pbafna03 @get-itips Please comment. Thanks

**Comment by pbafna03** [comment]
It is only supported for non *-Cs cmdlets till now.

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
> It is only supported for non *-Cs cmdlets till now.

Thanks @pbafna03 as that is already noted in the description, I think adding an example that will not work for *-Cs cmdlets is not the best at this time, when the functionality is extended for all the cmdlets, I'll propose an example. Thanks @kilasuit
