### ISSUE TITLE
List of permission in PNP Management Powershell

### ISSUE THREAD

**Issue by stuart-drysdale** [MicrosoftDocs/office-docs-powershell#7698]
Hi
there seems to be way more permission than we would like to apply in our tenant when all we are trying to achieve is grant permissions to a user to use SP credentials to connect to a site collection and perform functions with file, folders, lists,  permissions etc. They don't need all the rest.

How do we restrict this?

Thanks

Stuart

**Comment by get-itips** [comment]
Hello @stuart-drysdale  how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by stuart-drysdale** [comment]
@get-itips,

Thanks for that, I will post there

**Comment by stuart-drysdale** [comment]
@get-itips,

Thanks for that, I will post there
