### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by JAK1047** [MicrosoftDocs/office-docs-powershell#7705]
The document states how to generate error logs for error reporting via email, but not where to actually report it. Contacting Owners via the Powershell Gallery link gets you no response and after opening a ticket I was told they were unsure who the owners were. Is there a correct address to use for error reporting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JAK1047, try the following email address:

> exocmdletpreview[at]service[dot]microsoft[dot]com

The email address is purposefully obfuscated to avoid spam.

**Comment by JAK1047** [comment]
Is the correct method to ask via a GitHub Issue to receive that like I did then? Some guidance on proper next steps when encountering an error may be best added if there is a section on error reporting via email on that doc.

**Comment by JAK1047** [comment]
Ahh thank you. Would it make sense to update the doc to include that part under the error reporting section as well? I didn't think to look specifically under Linux considering it was unrelated to what I was looking to report.

**Comment by chrisda** [comment]
@JAK1047, I added the email address in that Report bugs section.

Thanks for the feedback.

Closing
