### ISSUE TITLE
Missing Parameter "-DomainController"

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/office-docs-powershell#7715]
The current Version does not document the parameter "-DomainController".  This parameter is required, if you move Users in a Single-Forest/Multi-Domain  topology  to Skype for Business Online or Teams. and cannot start the commandlet in the user-domain.
Move-CSUser searches for users only in the current domain. there is no parameter to set the scope to "forest". Exchange has such an option with "Set-ADServerSettings -ViewEntireForest".  
With Skype for Business you have to specify the DC of the users domain

Frank

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22159e01-061b-499a-fe99-3fe19bed57e9
* Version Independent ID: 98b9a798-e232-0b2c-ee0f-857071885c1d
* Content: [Move-CsUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Move-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Move-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by get-itips** [comment]
Thanks @FrankCarius Frank for reporting.
