### ISSUE TITLE
Time range boundries/duration

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/office-docs-powershell#7716]
It looks like the Time range can be provided in any boundaries but trying to use the boundaries not aligned with the 15 minute range will return error when using such Time range in New-CsOnlineSchedule.

Please clarify the following:
- A time range must be aligned with 30/60-minutes boundaries. - shouldn't this be 15/30/45/60 minute boundaries? 
- A time range can span from one minute to 24 hours. - how can a time range span from one minute if you can only set  minimum 15 minute intervals? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4150d9-182d-2f4c-df94-4c6fe57fc944
* Version Independent ID: 2fce288f-0d08-abfc-cbf2-bff3851f635f
* Content: [New-CsOnlineTimeRange (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinetimerange?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineTimeRange.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsOnlineTimeRange.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @Larryngolog Paweł how are you? Hope you are doing great.

Those statements were probably aligned to OAAs, I could verify what you said while trying to use those time ranges with `New-CsOnlineSchedule`, will update the article accordingly.

Thanks for the feedback that improves the docs.
