### ISSUE TITLE
Permissions no longer available

### ISSUE THREAD

**Issue by trentcioran** [MicrosoftDocs/office-docs-powershell#7718]
In **Step 2** Office 365 Exchange Online is no longer provided as an option and consequently Exchange.ManageAsApp can not be selected/added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@trentcioran, are you saying that step 2 in Step 2 where you enter the GUID value on the Manifest page no longer works?

```json
"requiredResourceAccess": [
   {
      "resourceAppId": "00000002-0000-0ff1-ce00-000000000000",
      "resourceAccess": [
         {
            "id": "dc50a0fb-09a3-484d-be87-e023b12c6440",
            "type": "Role"
         }
      ]
   }
],
```

**Comment by trentcioran** [comment]
Hi @chrisda , 

No, what I was pointing out is that when adding permissions you are indicated to select Office 365 Online and then add the permission Exchange.ManageAsApp, but Office 365 Online is no longer an option available in the Request API permissions selection APIs, not even shown in the legacy APIs so either it is no longer possible (making this document invalid) or the name of the API changed and the document needs update.

**Comment by chrisda** [comment]
@trentcioran, the topic was rewritten to account for the fact that you can't select Exchange.ManageAsApp in the UI anymore. Known issue.

Are you talking about the reference in step 2 in the [Set up app-only authentication](https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#set-up-app-only-authentication) section?

The title and link of that step is: [Assign Exchange Online API permissions to the application](https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#step-2-assign-api-permissions-to-the-application).

Once you click the link, all of the information in that target section should be correct.

The text below the link title says:

> An application object has the default permission `User.Read`. For the application object to access Exchange Online resources, it needs to have the Application permission `Exchange.ManageAsApp`.

That is effectively what you are doing in [Step 2: Assign Exchange Online API permissions to the application](https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#step-2-assign-api-permissions-to-the-application).

I can find no text in the topic that says, "select Office 365 Online" or "add the Exchange.ManageAsApp permission".

If you configure the Manifest pages as described, it should add everything for you.

**Comment by trentcioran** [comment]
Thank you! that made it. Sorry for letting this without response for so long.
