### ISSUE TITLE
In Exchange Online, the Identity parameter does not accept GUID

### ISSUE THREAD

**Issue by Jeremy919** [MicrosoftDocs/office-docs-powershell#7719]
In Exchange Online, the Identity parameter does not accept GUID.  Please update the documentation accordingly.  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80741fad-e384-0205-6827-8cb83ea8fdf1
* Version Independent ID: 76fb7d41-3729-dd2b-f483-b9dc87a29a38
* Content: [Remove-MobileDevice (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-mobiledevice?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-MobileDevice.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-MobileDevice.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Jeremy919, if the Identity parameter in Remove- doesn't accept a GUID value, then Identity in Get- should also not accept GUIDs.

Can you confirm?

Also, the output of the following Get-MobileDevice command should show a GUID value and an ExchangeGUID value. Does one work but not the other?

```powershell
Get-MobileDevice | Format-Table Name,Guid,ExchangeGuid
```

**Comment by Jeremy919** [comment]
@chrisda - I stand corrected.  Both Get- and Remove- do work with the GUID.  Thank you very much for your prompt reply and guidance!  This issue can be closed.

**Comment by chrisda** [comment]
Great! Closing.
