### ISSUE TITLE
-GenerateRingingWhileLocatingUser attribute is decommissioned 

### ISSUE THREAD

**Issue by gautam0107** [MicrosoftDocs/office-docs-powershell#7721]
[Enter feedback here]

-**GenerateRingingWhileLocatingUser** (Ringback Bot) attribute is decommissioned but still, it is mentioned in our documents which need to be modified. It is creating confusion between our customers. Please check the below article:

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/352acb5a91ecf769d2b7a3bea482873c06da3e33

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a99ede2-bbc2-c56d-6fb0-33db74417f54
* Version Independent ID: cf4bfc0e-fd8d-d5ca-5432-798af72a8885
* Content: [Set-CsOnlinePSTNGateway (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinepstngateway?view=skype-ps#feedback)
* Content Source: [skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @gautam0107 thanks for reporting, this has been already removed in https://github.com/MicrosoftDocs/office-docs-powershell/pull/7729
@yogkumgit please close

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @gautam0107 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
