### ISSUE TITLE
Set-CsAutoAttendant Missing Parameter

### ISSUE THREAD

**Issue by LFChrisM** [MicrosoftDocs/office-docs-powershell#7724]
In the latest MicrosoftTeams 2.3.0 power shell module it appears the Set-CsAutoAttendant -instance parameter is missing.

as outlined in https://docs.microsoft.com/en-us/powershell/module/skype/set-csautoattendant

![image](https://user-images.githubusercontent.com/83740239/117233875-4bb5c400-ae67-11eb-8c72-4560f0d8ec81.png)

**Comment by LFChrisM** [comment]
Thanks that’s good news,

Will update and see how I go.

Kind regards,
Chris Muir


Chris Muir
System Administrator
Tel:
***@***.***
Web:www.lifeflight.org.au
Postal Address:     PO Box 15166, City East, QLD 4002
This communication including any file attachments is intended solely for the use of the individual or entity to whom it is addressed. If you are not the intended recipient, or the person responsible for delivering this communication to the intended recipient, please immediately notify the sender by email and delete the original transmission and its contents. Any unauthorised use, dissemination, forwarding, printing, or copying of this communication including any file attachments is prohibited. It is your responsibility to scan this communication including any file attachment for viruses and other defects. To the extent permitted by law, LifeFlight Australia Ltd and its associates will not be liable for any loss or damage arising in any way from this communication including file attachments.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @LFChrisM Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
