### ISSUE TITLE
Set-CsCallQueue -Identity xxxxx -User >> Bad Request

### ISSUE THREAD

**Issue by seb07-cloud** [MicrosoftDocs/office-docs-powershell#7725]
![image](https://user-images.githubusercontent.com/16953863/117249119-59585300-ae41-11eb-9af6-2f616c7aad28.png)

Set-CsCallQueue doesnt accept ObjectID for -User

![image](https://user-images.githubusercontent.com/16953863/117249206-7ee55c80-ae41-11eb-9618-6d57a9dfed6b.png)
![image](https://user-images.githubusercontent.com/16953863/117249240-8b69b500-ae41-11eb-9cad-6f7d76b99294.png)

![image](https://user-images.githubusercontent.com/16953863/117249435-de436c80-ae41-11eb-85de-0bf63b307acb.png)

**Comment by get-itips** [comment]
Hello @seb07-cloud how are you?
Looks like it changed in `2.3.1`:

> Name       : Users
> Definition : Deserialized.System.Collections.ObjectModel.ObservableCollection`1[[System.Guid, mscorlib,
>              Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] {get;set;}

Hope this information helps you,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @seb07-cloud Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
