### ISSUE TITLE
Update the link for country code

### ISSUE THREAD

**Issue by Neeraj-6596** [MicrosoftDocs/office-docs-powershell#773]
Link does not work - http://go.microsoft.com/fwlink/?LinkId=615951

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b243c23-4c18-7a05-4856-1fad04318204
* Version Independent ID: 56bd83d2-caf0-5e0c-1963-2e5b87810e9a
* Content: [Search-CsOnlineTelephoneNumberInventory (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/Search-CsOnlineTelephoneNumberInventory?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Search-CsOnlineTelephoneNumberInventory.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Search-CsOnlineTelephoneNumberInventory.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by nsshommo** [comment]
@Neeraj-6596 Thanks for letting us know. We are working on this.

**Comment by kenwith** [comment]
@tonysmit is helping us track this down and we will get this fixed. Thanks for reporting @Neeraj-6596 ! @nsshommo - we might just be able to update the fwlink to point to the right location or we might need a pull request if there are changes to the docs. Thanks for follow through!

**Comment by nsshommo** [comment]
Submitted PR on this one. Trying to find similar articles.

**Comment by kenwith** [comment]
@nsshommo - merged https://github.com/MicrosoftDocs/office-docs-powershell/pull/932 and closing this one until we can get link resolved.
