### ISSUE TITLE
Get-CsUserPolicyAssignment performance degradation

### ISSUE THREAD

**Issue by gregg79** [MicrosoftDocs/office-docs-powershell#7733]
On the same machine this function takes 2-2.5 seconds to run with version 1.1.6, 14.5-15.5 seconds with version 2.0.0, and 4-4.5 seconds with version 2.3.0.

Since there is not currently a way to get group-based policy assignment data for multiple users using a single command, I am forced to query user by user. With 19,000 active users the speeds in 1.1.6 were barely fast enough to query all users within 12 hours. My specific use case could tolerate up to about 18 hours, but not the slower speeds in all 2.x versions.

**Comment by get-itips** [comment]
Hello @gregg79 how are you? Hope you are doing good 👍 
Here, we are limited to documentation fixes and improvements, for your particular inquiry the best would be to open a support ticket directly from your tenant.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @gregg79 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
