### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by tkitsupport** [MicrosoftDocs/office-docs-powershell#7736]
First Example has a typo in
-FileName"  should be -FileName " (space is incorrectly after the speechmarks instead of before

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b138fd60-8659-108a-2770-0b7beceafd48
* Version Independent ID: cd079e2f-a3b3-c81b-163b-5cba8d2e8c9c
* Content: [Import-ExchangeCertificate (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/import-exchangecertificate?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Import-ExchangeCertificate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Import-ExchangeCertificate.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@tkitsupport, fixed. In the future, you too can directly fix issues like this without opening a GitHub Issue first.  For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
