### ISSUE TITLE
Set-CsOnlineLisLocation not working

### ISSUE THREAD

**Issue by SGurjitsk** [MicrosoftDocs/office-docs-powershell#7739]
We need to amend the numbers for our ELIN field but the below commands are not working at all.
We have also tried the phone number with " " 
Can someone help please we have already validated the address etc. 

ValidationStatus         : Validated
NumberOfVoiceUsers       : 0
NumberOfTelephoneNumbers : 0
===================================

Command used : 
Set-CsOnlineLisLocation -CivicAddressId 3e8c8fff-4a81-4bc0-b7ba-b14f72eab43c -ELIN +443000xxxxx

Error: 
WARNING: Correlation id for the request is cdf0c5ad-db4b-4a66-xxxxx
WARNING: BVD correlation id for the request is cdf0c5ad-db4b-4a66-xxxxx
Unable to update record
    + CategoryInfo          : NotSpecified: (System.Object[]:Object[]) [Set-CsOnlineLisLocation], BvdCmdletException
    + FullyQualifiedErrorId : Unspecified,Microsoft.Rtc.Management.Hosted.Lis.SetCsOnlineLisLocationCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com
===================================
I know Civic address is for not validated but still tried it. 
Command Used: 
Set-CsOnlineLisCivicAddress -CivicAddressId 3e8c8fff-4a81-4bc0-b7ba-xxxxxxx -ELIN +443000xxxxx

Error: 
Unable to update a validated Civic Address 3e8c8fff-4a81-4bc0-b7ba-xxxxxxx
    + CategoryInfo          : NotSpecified: (System.Object[]:Object[]) [Set-CsOnlineLisCivicAddress], BvdCmdletException
    + FullyQualifiedErrorId : Unspecified,Microsoft.Rtc.Management.Hosted.Lis.SetCsOnlineLisCivicAddressCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

Thanks in advance .

**Comment by get-itips** [comment]
Hello @SGurjitsk how are you? hope you are doing good 👍 
Is there any specific article that you see needs correction? as here we are limited to documentation fixes and improvements.
Maybe the best in your scenario would be to open a support ticket directly from your tenant.
Thank you,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @SGurjitsk Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
