### ISSUE TITLE
Required Authorization/Connection Type to utilize this function

### ISSUE THREAD

**Issue by jarvann** [MicrosoftDocs/office-docs-powershell#7740]
When I try to access the Add-PnPTeamsTeam function through an Azure Function using:

`Connect-PnPOnline -Tenant [tenant].onmicrosoft.com -ClientId [appid] -Thumbprint [thumbprint] -Url https://[tenant].sharepoint.com`

I get the following error:
![image](https://user-images.githubusercontent.com/14030665/117507065-92cdb300-af54-11eb-9e22-902bdd39889d.png)

I am wondering if the Doc needs updating to specify which connection methods are permitted, or if the function needs to be updated to allow for "Application" API permissions to execute it. 

Any Help appreciated, Thanks!

Cory Loriot
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bee7c71-2eba-39cf-aab7-69ace2f91606
* Version Independent ID: f80d7a85-658f-632a-0b9f-fff9341a8ce1
* Content: [Add-PnPTeamsTeam (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpteamsteam?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTeamsTeam.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTeamsTeam.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by jarvann** [comment]
Actually... it seems like it doesn't work regardless of how I generate the connection. using 1.5.35 version of PnP.PowerShell

![image](https://user-images.githubusercontent.com/14030665/117506970-72055d80-af54-11eb-9bbb-0f0d515ecba6.png)

**Comment by get-itips** [comment]
Hello @jarvann Cory, how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by jarvann** [comment]
I will do that. Thank you for responding!
