### ISSUE TITLE
Grant change does not stick

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#7746]
I issue a Grant-CsTenantDialPlan

PS D:\> Grant-CsTenantDialPlan -Identity 'dsmith@abc.com' -PolicyName 'Calgary'

No error is indicated, but when I issue a Get command, the TenantDialPlan is not updated

PS D:\> Get-CsOnlineUser -Identity 'dsmith@abc.com' | select TenantDialPlan

TenantDialPlan
    -   -   -   -  -

This is very hit/miss and there seems to be no rhyme or reason as to when it does or does not work and we have a client that is doubting the reliability of our product to automate these PowerShell cmdlets

I would like to add that we've waited up to 4 hours, thinking that some synchronization has to take place, but still the grant does not seem to work.

In one case, the O365 UI shows the change, but still PowerShell does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb40b45f-5982-fcca-66fa-8fa03f723648
* Version Independent ID: 72abb3bd-b9d5-6b10-04f7-d46f3bd49688
* Content: [Grant-CsTenantDialPlan (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-cstenantdialplan?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsTenantDialPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsTenantDialPlan.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @sarollins 
I tried to reproduce to see if we need to edit any article but could not, as here we are limited to documentation changes and fixes, the best in your scenario is to open a support ticket directly form your tenant.
Hope this information helps you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
