### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by JakeMoe** [MicrosoftDocs/office-docs-powershell#7749]
Important link in blue at the top of the page goes to a 404 page:

https://www.poshtestgallery.com/packages/MicrosoftTeams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49821e2-bc94-5125-03e0-a31c650f48ca
* Version Independent ID: 2c52cc4e-47a1-be0d-8860-1011adf061fd
* Content: [New-TeamChannel (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/new-teamchannel?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Thanks for reporting @JakeMoe
