### ISSUE TITLE
New-CsTeamsComplianceRecordingPolicy, Get-CsTeamsComplianceRecordingPolicy is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by jay1927** [MicrosoftDocs/office-docs-powershell#7750]
I have installed MicrosoftTeams module 2.3.1 and login as tenant admin. ' Also New-CsTeamsComplianceRecordingPolicy' command showing in the module "MicrosoftTeams" but when executing getting following message. Please assist.

The term 'New-CsTeamsComplianceRecordingPolicy' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
+ CategoryInfo : ObjectNotFound: (New-CsTeamsComplianceRecordingPolicy:String) [], CommandNotFoundExcepti
on
+ FullyQualifiedErrorId : CommandNotFoundException
+ PSComputerName : api.interfaces.records.teams.microsoft.com

**Comment by get-itips** [comment]
Hello @jay1927 how are you? Hope you are doing good.
I also have 2.3.1 version and I can run that cmdlet, please be sure to be running only one version of the Teams PowerShell module as that could be your issue.
![image](https://user-images.githubusercontent.com/36666927/118502859-54b85800-b6e7-11eb-93b4-511b68108872.png)

Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @jay1927 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
