### ISSUE TITLE
Formatting change needed

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/office-docs-powershell#7758]
You have the following two attributes displayed on the same line. They need to be on separate lines

[-AllowOrganizersToOverrideLobbySettings <Boolean>][-AllowUserToJoinExternalMeeting <String>]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @nikki-c how are you? In the markdown both parameters are in different lines, it's the rendered article that puts them together, will try to split them in a PR but not sure if it will correct the published version.
Thank you!
