### ISSUE TITLE
what is ayla?

### ISSUE THREAD

**Issue by WillemVerwijs** [MicrosoftDocs/office-docs-powershell#7759]
What is ayla\ in example 1? please make the text in the example more clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 898a7767-d713-4b9a-de97-0c7d787aaa07
* Version Independent ID: fe68ba74-2819-98d3-5e23-960e2501050e
* Content: [Get-MailboxRestoreRequest (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailboxrestorerequest?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailboxRestoreRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MailboxRestoreRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@WillemVerwijs. it's a person's first name. I updated the text to clarify.

Thanks, for the feedback.

Closing
