### ISSUE TITLE
Set-CsTeamsAppSetupPolicy -PinnedAppBarApps , add new pin does not work

### ISSUE THREAD

**Issue by VelinGeorgiev** [MicrosoftDocs/office-docs-powershell#7767]
[Enter feedback here]
Can please someone give me a clear explanation how to use this with -PinnedAppBarApps? The commandlet throws error no matter what I try.

How to reproduce?
```
$s = Get-CsTeamsAppSetupPolicy | select PinnedAppBarApps

$pinnedApps = $s[0].PinnedAppBarApps

$m =  New-Object PSCustomObject –Property @{Id='14d6962d-6eeb-4f48-8890-de55454bb136';Order=6}

$pinnedApps.Add($m)

Set-CsTeamsAppSetupPolicy -PinnedAppBarApps $pinnedApps
```

Expected:
- Adds new pinned app to the Global app setup policy

Actual:
```
Unable to cast object of type 'System.Management.Automation.PSCustomObject' to type 'Microsoft.Rtc.Management.WritableConfig.Policy.Teams.PinnedApp'.
    + CategoryInfo          : NotSpecified: (:) [Set-CsTeamsAppSetupPolicy], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException,Microsoft.Rtc.Management.Internal.SetTeamsAppSetupPolicyCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com
```

### Tell me please how to cast to your internal object in my script?!. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cbf9e01-3daf-0a8c-f78c-5c9ba6dac01f
* Version Independent ID: 91f0f246-e6c5-c2e2-1569-7f27afb28c04
* Content: [Set-CsTeamsAppSetupPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsappsetuppolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsAppSetupPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsAppSetupPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by VelinGeorgiev** [comment]
Anyone?

**Comment by VelinGeorgiev** [comment]
Anyone?

**Comment by get-itips** [comment]
Hello @VelinGeorgiev Velin, how are you?
Please see this note that is included in the cmdlet's article

> The existence of this cmdlet is being documented for completeness, but do not use this cmdlet. We require that all creation and modification of app setup polices (not including the assignment or removal of policies from users) happens in the Microsoft Teams & Skype for Business Admin Center to ensure that the policy matches your expectations for the end user experience.

Thanks

**Comment by VelinGeorgiev** [comment]
Thanks for your answer Andreas @get-itips ! 

Imagine I have ten tenants with 200 app setup policies I want to change. It makes absolutely no sense for me to go and change each one them manually. In fact it will take forever for me to do it by hand clicking on fancy UI screens.

Having cmdlet for completeness that does not fully work is worst than having nothing since people like me will attempt to use it and then left with the impression they wasted their time.

Anyway thanks for your time, I appreciate it.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @VelinGeorgiev If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
