### ISSUE TITLE
Please correct the documentation on AllowAnonymousAccess

### ISSUE THREAD

**Issue by miguelisidoro** [MicrosoftDocs/office-docs-powershell#7768]
Please check the correct syntax at:

https://social.technet.microsoft.com/Forums/sharepoint/en-US/55cc1134-6f15-4fc4-9cf7-677ad053aec6/setspwebapplication-allowanonymousaccess?forum=sharepointadminprevious

$ap = New-SPAuthenticationProvider -AllowAnonymous
Set-SPWebApplication http://sharepoint -Zone Default -AuthenticationProvider $ap

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf89184c-fadb-9c62-9f9e-bd6134c6cbd0
* Version Independent ID: 2dfe0b5c-80e7-c237-a6f3-24e3e74b8b86
* Content: [Set-SPWebApplication (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spwebapplication?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPWebApplication.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Set-SPWebApplication.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks for reporting! @miguelisidoro
