### ISSUE TITLE
 MicrosoftTeams powershell 2.3.1 getting error

### ISSUE THREAD

**Issue by harshdamaniahd** [MicrosoftDocs/office-docs-powershell#7773]
When trying to setup policy , I am getting error
Get-CsOnlineSession : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The WinRM client cannot process the request. Basic
authentication is currently disabled in the client configuration. Change the client configuration and try the request again. For more information, see the about_Remote_Troubleshooting Help
topic.

 Grant-CsTeamsAppPermissionPolicy -PolicyName "HR App Policy" -Identity d72f6b50-ac7-470a-80b8-919ab8b3232e

**Comment by get-itips** [comment]
Hello @harshdamaniahd how did you connect to Teams PowerShell?

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and digging deep into it.  @harshdamaniahd We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
