### ISSUE TITLE
EnableSafeLinksForTeams parameter is not working anymore

### ISSUE THREAD

**Issue by wiseleaf23** [MicrosoftDocs/office-docs-powershell#7785]
The EnableSafeLinksForTeams parameter is not working anymore:

```
A parameter cannot be found that matches parameter name 'EnableSafeLinksForTeams'.
    + CategoryInfo          : InvalidArgument: (:) [New-SafeLinksPolicy], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-SafeLinksPolicy
    + PSComputerName        : outlook.office365.com
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a1f9fa-7dd6-ebf1-3e64-ef47bd3962b2
* Version Independent ID: 5ea9bde3-9fe9-8ae1-0992-b12223c4d7c4
* Content: [New-SafeLinksPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-safelinkspolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-SafeLinksPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-SafeLinksPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@wiseleaf23, Safe Links for Teams is only available to Technology Adoption Partner (TAP) customers. The disappearance of the parameter was likely a correction. And the parameter description currently says this:

> **Note**: As of March 2020, this parameter is in Preview and is available only for members of the Microsoft Teams Technology Adoption Program (TAP).

**Comment by T13nn3s** [comment]
I'm also here to report this 'issue'. Is there a possibility to bring this parameter back in the `New-SafeLinksPolicy`? 

We have scripted the configuration for Defender for Office 365, and now this parameter is not working anymore, we have to log in manually in to every tenant in order to enable this option on the Safe-links policy. 

Thanks in advance!

**Comment by chrisda** [comment]
@T13nn3s, if you're in the Teams TAP program, you should have access to the parameter. If you are and you don't, I highly encourage you to open a support case.

If the parameter was available to customers who weren't part of the TAP Preview, that was a mistake. The fact that the parameter went away for non-TAP members should be considered a correction of that mistake.
