### ISSUE TITLE
set-CSExternalAccessPolicy - effect on Teams users

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/office-docs-powershell#7786]
https://support.microsoft.com/en-us/topic/keeping-students-safe-while-using-teams-for-distance-learning-f00fa399-0473-4d31-ab72-644c137e11c8#:~:text=To%20maintain%20student%20safety%2C%20you,to%20keep%20the%20environment%20safe.

as per the page above the section - How to prevent external access (federation) of students the csexternalaccesspolicy with the parameter of EnableFederationAccess set to false can prevent federation to Teams users.

The current page relating to Set-CSExternalAccessPolicy makes no mention of the settings impacts on Teams.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fe1d21-20a0-9b8e-f08c-caf788005f9b
* Version Independent ID: 486050c0-de7f-31d4-f09e-78324336eb26
* Content: [Set-CsExternalAccessPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-gb/powershell/module/skype/set-csexternalaccesspolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsExternalAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsExternalAccessPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for reporting @thewrabbit
