### ISSUE TITLE
limited to 10,000 members

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/office-docs-powershell#7787]
I tried to use this command, but it failed;

The change that you're trying to make contains 13975 distinguished name values. This exceeds the limit of 10000 DN
values.
    + CategoryInfo          : NotSpecified: (:) [Update-DistributionGroupMember], ADOperationException
    + FullyQualifiedErrorId : [Server=DB3PR0302MB3388,RequestId=c9fc8033-97d4-43d6-95aa-5be5e2072fa8,TimeStamp=18/05/2
   021 11:08:48] [FailureCategory=Cmdlet-ADOperationException] 7AD20693,Microsoft.Exchange.Management.RecipientTasks.
  UpdateDistributionGroupMember

Please add this limit.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18125af8-f8f7-a031-2a8f-270907d34b54
* Version Independent ID: 3e873980-c99b-0cfb-1e8a-0af4314d2d97
* Content: [Update-DistributionGroupMember (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/update-distributiongroupmember?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Update-DistributionGroupMember.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Update-DistributionGroupMember.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@anwarmahmood1, OK. Done.

Thanks for the feedback.

Closing
