### ISSUE TITLE
OverflowAction & TimeoutAction "Voicemail" still available?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7788]
Hello,

Voicemail cannot be configured in the Admin Center any longer.  UPN are not accepted anymore - only Group Names/Mail Nicks.
The Option "Voicemail" there purely references "SharedVoicemail".

```
-OverflowAction
PARAMVALUE: DisconnectWithBusy | Forward | Voicemail | SharedVoicemail

-TimeoutAction
PARAMVALUE: DisconnectWithBusy | Forward | Voicemail | SharedVoicemail
```

Can this be clarified please?

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ade68d-5dc0-c598-a659-8b018cef3e26
* Version Independent ID: 67efa086-edb0-2828-cc14-4c245290e4f3
* Content: [Set-CsCallQueue (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DEberhardt 
Noticed that in the portal, the Voicemail option description changed from "Search for a voicemail" to "Search for an Office 365 Group" (for reference https://github.com/MicrosoftDocs/office-docs-powershell/issues/6160#issuecomment-660352622)

Tested then in `2.3.1` and SharedVoiceMail is accepted when specifying a group id, Voicemail is also still accepted but could not find a valid combination.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DEberhardt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DEberhardt** [comment]
Hello,
this isn't about SharedVoicemail, but about forwarding a call to a Users' Voicemail. This was an option earlier and is now suspiciously absent...

**Comment by get-itips** [comment]
> this isn't about SharedVoicemail, but about forwarding a call to a Users' Voicemail. This was an option earlier and is now suspiciously absent...

I am sorry David I am afraid I did not get to use it in the past, have you ever get it working to forward to a single user's voicemail? I suspect this was always intended to a group voicemail (more info https://docs.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue)

**Comment by DEberhardt** [comment]
It was possible in the past, hence me asking whether the functionality was removed?

**Comment by get-itips** [comment]
I understand @DEberhardt will try to confirm and opening a ticket is also a good idea.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DEberhardt Hope this comment is helpful for you. As advised please open a support ticket. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
