### ISSUE TITLE
Teams AC Pin

### ISSUE THREAD

**Issue by jesslyn-omm** [MicrosoftDocs/office-docs-powershell#7800]
The info is masked in PowerShell. The PIN should display or be removed from results

**Comment by yogkumgit** [comment]
@jesslyn-omm Please indicate which document you are referring to. Thanks

**Comment by jesslyn-omm** [comment]
Get-CsOnlineDialInConferencingUser
https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps

**Comment by get-itips** [comment]
Hello @jesslyn-omm how are you? I could see that you refer to the output of the cmdlet, however, we are limited here to documentation issues and improvements, I could redirect you to [this resource](https://support.microsoft.com/en-us/topic/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a) to submit that kind of feedback.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @jesslyn-omm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
