### ISSUE TITLE
Example 1 needs a little adjustment

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/office-docs-powershell#7801]
If you run example 1 in most mid-sized (or larger) environments, there is a high probably that the default -Identity will throw errors on the second half due to ambiguous names.  Best to specify the DistinguishedName property for the input of Get-MailboxAutoReplyConfiguration when possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59541ba2-e471-96ae-a4c8-db59f7420426
* Version Independent ID: cefe33a8-d461-5c4c-55f4-b7ff918b9a2a
* Content: [Get-MailboxAutoReplyConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailboxautoreplyconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailboxAutoReplyConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MailboxAutoReplyConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Skatterbrainz, I think the intent of the Identity values in the example is to use the Alias value, which should be unique in the organization. But, most Alias value are not as friendly (chrisda, billg, etc.).

I updated the examples to use 'tony@contoso.com', which as the email address should also be unique. Distinguished Name (or GUID) are the big guns, but are a bit unwieldly.

Thanks for the feedback.

Closing
