### ISSUE TITLE
EnableOutlookEvents

### ISSUE THREAD

**Issue by stoff75** [MicrosoftDocs/office-docs-powershell#7803]
No documentation for what "_EnableOutlookEvents_" does?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23add0a6-bb9c-15d2-a6eb-351ae0564522
* Version Independent ID: 8056b3ee-4fab-3a5c-935b-a9d0e9ad82a4
* Content: [Set-OrganizationConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by stoff75** [comment]
![image](https://user-images.githubusercontent.com/6229114/118972840-4aa98a00-b971-11eb-9f69-ab4180a1d4bb.png)

**Comment by stoff75** [comment]
Thank you @chrisda . The reason I'm asking about this is the newly introduced ability to shorten events/meetings in Outlook/Exchange Online. The official blog post about this on https://techcommunity.microsoft.com/t5/outlook-blog/new-settings-in-outlook-give-everyone-a-break-between-meetings/ba-p/2276514 specifies the commands needed to enable it and also the cmdlet to check it, "Get-OrganizationConfig | fl *event*". But when I execute that I get the extra "EnableOutlookEvents" toggle which isn't in his screenshot or documentet anywhere as far as I can see. And since the feature isn't working for us even 4 days after I enabled it I'm thinking it may have something to do with that toggle?

**Comment by chrisda** [comment]
@stoff75, if the feature isn't working for you, I would highly recommend opening a support case. Report back here if there are any updates required in the parameter descriptions for Set-OrganizationConfig.

**Comment by SRE93** [comment]
Hi there, the parameter -EnableOutlookEvents exists in Set-OrganizationConfig

**Comment by chrisda** [comment]
@stoff75, @SRE93, confirmed. I added the parameter to the topic and described it.

Thanks for the feedback.
