### ISSUE TITLE
Please provide alternative method instead of leaving the user at a dead-end

### ISSUE THREAD

**Issue by W0GER** [MicrosoftDocs/office-docs-powershell#7807]
At the top of the article it states "This cmdlet is available only in on-premises Exchange." Which is great, but please offer a solution to Exchange Online users who need to export an Archive database. The way your documentation is today, this leaves me at a dead-end; there is no alternative for me to follow. There has to be a way to export a mailbox from Exchange Online without having to setup on-premise solution. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4e08e4f-0fe9-af32-49ff-de431c3ec4f4
* Version Independent ID: 17968567-deae-9f14-abc9-741f58a04bcc
* Content: [New-MailboxExportRequest (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-mailboxexportrequest?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-MailboxExportRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MailboxExportRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@W0GER, your best option is to open a support case.
