### ISSUE TITLE
Cannot set templateid when creating a teams template using -templateid or -body

### ISSUE THREAD

**Issue by DaveFSP** [MicrosoftDocs/office-docs-powershell#7825]
I am creating a teams template and have a json template that looks like this
```
{
  "templateId": "templateid",
  "displayName": "templatename",
  "description": "templatedescription",
  "visibility": "Private",
  "channels": [
    {
      "id": "General",
      "displayName": "General",
      "isFavoriteByDefault": true,
      "tabs": [ ]
    }
  ],
  "memberSettings": {
    "allowCreateUpdateChannels": false,
    "allowDeleteChannels": false,
    "allowAddRemoveApps": false,
    "uploadCustomApp": false,
    "allowCreateUpdateRemoveTabs": false,
    "allowCreateUpdateRemoveConnectors": false,
    "allowCreatePrivateChannels": false
  },
  "guestSettings": {
    "allowCreateUpdateChannels": false,
    "allowDeleteChannels": false
  },
  "messagingSettings": {
    "allowUserEditMessages": false,
    "allowUserDeleteMessages": false,
    "allowOwnerDeleteMessages": false,
    "allowTeamMentions": false,
    "allowChannelMentions": false
  },
  "funSettings": {
    "allowGiphy": false,
    "allowStickersAndMemes": false,
    "allowCustomMemes": false
  },
  "discoverySettings": {
    "showInTeamsSearchAndSuggestions": false
  },
  "apps": [
    {
      "id": "0d820ecd-def2-4297-adad-78056cde7c78"
    },
    {
      "id": "com.microsoft.teamspace.tab.planner"
    }
  ],
  "icon": "https://statics.teams.cdn.office.net/evergreen-assets/teamtemplates/icons/default_tenant.svg",
  "shortDescription": "description"
}
```
I have set the template name in and i run it using `New-CsTeamTemplate -Locale en-GB -Body (Get-Content $templateLocation | Out-String)` the template gets created successfully however a different id to the one i have given it gets set.
Is there anyway to set the id so when deploying to different environments the same id gets given to the template?
I have also tried with the other way of using -templateid as a parameter but that produces the same results

**Comment by get-itips** [comment]
Hello @DaveFSP how are you?
Here, we are limited to documentation fixes, is there any article you see needs a fix? can you link it here?
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DaveFSP Considering the nature of the issue, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
