### ISSUE TITLE
A little bit advice

### ISSUE THREAD

**Issue by FrostDK01** [MicrosoftDocs/office-docs-powershell#7837]
[**If the filter contains system values (for example, $true, $false, or $null), use single quotation marks ' ' instead.**]
Things like _'(CustomAttribute12 -eq $cat) -and (alias -ne $null)'_ or _'(CustomAttribute12 -eq '$cat') -and (alias -ne $null)'_ can not work properly.

It could be better if the usage of escape characters can be added to the article: 
_"(CustomAttribute12 -eq 'cat') -and (alias -ne `$null)"_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 330f40d6-b8bb-a1f2-61b7-d66ad94fdeac
* Version Independent ID: 58962a12-4310-4a16-3afe-6baee0cc19f2
* Content: [Get-Recipient (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-recipient?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Get-Recipient.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-Recipient.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@FrostDK01, I agree that the sentence by itself is confusing and/or incorrect. But it's correct in context:

> Enclose the whole OPath filter in double quotation marks " ". If the filter contains system values (for example, `$true`, `$false`, or `$null`), use single quotation marks ' ' instead.

Also note the last bullet in the description:

> Value is the property value to search for. Enclose text values and variables in single quotation marks (`'Value'` or `'$Variable'`). If a variable value contains single quotation marks, you need to identify (escape) the single quotation marks to expand the variable correctly. For example, instead of `'$User'`, use `'$($User -Replace "'","''")'`. Don't enclose integers or system values (for example, `500`, `$true`, `$false`, or `$null`).

I went around and around with this and did some heavy testing and rewriting ~ a year ago. 40 cmdlets contain the Filter parameter, and they all use this same description

**Comment by chrisda** [comment]
I was having difficulty finding the previous issue, but this is it: <https://github.com/MicrosoftDocs/office-docs-powershell/issues/4206>
