### ISSUE TITLE
Missing parameter: -GenerateRingingWhileLocatingUser

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#7838]
Hi,

On the PS we are able to set:
Set-CsOnlinePSTNGateway -GenerateRingingWhileLocatingUser
But on the documentation this is not clarified at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a99ede2-bbc2-c56d-6fb0-33db74417f54
* Version Independent ID: cf4bfc0e-fd8d-d5ca-5432-798af72a8885
* Content: [Set-CsOnlinePSTNGateway (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinepstngateway?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @Petri-X how are you? please see [here](https://github.com/MicrosoftDocs/office-docs-powershell/pull/7729)
The parameter is not present in `2.3.1`

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Petri-X Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
