### ISSUE TITLE
Clarify action intended to clean up user mailboxes

### ISSUE THREAD

**Issue by jbostoen** [MicrosoftDocs/office-docs-powershell#7839]
"A maximum of 10 items per mailbox can be removed at one time. Because the capability to search for and remove messages is intended to be an incident-response tool, this limit helps ensure that messages are quickly removed from mailboxes. This action isn't intended to clean up user mailboxes."

Perhaps it's worth mentioning what action IS intended nowadays?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad8adee-7f9d-757b-2069-95ecab232747
* Version Independent ID: c71194df-8f65-15aa-3ed2-b370b8c3f629
* Content: [New-ComplianceSearchAction (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearchaction?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jbostoen, you best option is to open a support case and ask that question.

If you're handy with PowerShell, you create a script that loops through the mailbox 10 items at a time searching for the items that you want to remove and removing them until they're all gone.
