### ISSUE TITLE
Request for additional options to cmdlet, Remove-CalendarEvents

### ISSUE THREAD

**Issue by jeanzy1** [MicrosoftDocs/office-docs-powershell#7840]
For decades as an Exchange/O365 administrator I am asked to cancel a reoccurring meeting from a separated user's calendar or someone on LOA,  I would love to have the option to select by QueryMeetingType, reoccurring, and an option, by QuerySubject and just cancel that one meeting.  That way the rest of the calendar is left intact for either Legal hold or when a user returns from LOA.  Admins would not have to "get into the user's mailbox" for privacy reasons, legal reasons, etcetera. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e391a2ce-71ef-bf07-c9bb-0d8cb322f57e
* Version Independent ID: 5e1a15c4-4f78-c1df-e119-901340e720f6
* Content: [Remove-CalendarEvents (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-calendarevents?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-CalendarEvents.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-CalendarEvents.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jeanzy1, your best course of action is to open a support case and ask the same question.
