### ISSUE TITLE
MicrosoftTeams Powershell 2.3.1 errors using Connect-MicrosoftTeams to create session

### ISSUE THREAD

**Issue by jmcarthurcorr** [MicrosoftDocs/office-docs-powershell#7842]
Since the cutover to using the new connection method, the Teams cmdlets have been unreliable. The past two days I can't connect at all and I'm getting the following errors on an up-to-date Win10 machine running PS version 5.1.19041.906, and MicrosoftTeams version 2.3.1.

```
PS C:\users\jmcarthur> Get-CsOnlineUser $upn
Get-CsOnlineSession : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The connection to the specified remote host
was refused. Verify that the WS-Management service is running on the remote host and configured to listen for requests on the correct port and HTTP URL. For more information, see
the about_Remote_Troubleshooting Help topic.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\SfBORemotePowershellModule.psm1:63 char:22
+     $remoteSession = & (Get-CsOnlineSessionCommand)
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CsOnlineSession], PSRemotingTransportException
    + FullyQualifiedErrorId : PSRemotingTransportException,Microsoft.Teams.ConfigApi.Cmdlets.GetCsOnlineSession

Invoke-Command : Cannot validate argument on parameter 'Session'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\SfBORemotePowershellModule.psm1:9490 char:38
+ ...    -Session (Get-PSImplicitRemotingSession -CommandName 'Get-CsOnline ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Command], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeCommandCommand
```

**Comment by jmcarthurcorr** [comment]
Reinstalling the module has fixed this for now, but as mentioned, some days the module works and others it does not.

**Comment by get-itips** [comment]
Hello @jmcarthurcorr Jared, how are you? hope you are doing great.
Here, we are limited to documentation fixes, if you experience issues as you described, the best would be to open a support ticket directly from your tenant.
Hope this information helps you.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @jmcarthurcorr Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
