### ISSUE TITLE
query for finding mailboxes using a policy is wrong

### ISSUE THREAD

**Issue by poundy** [MicrosoftDocs/office-docs-powershell#7844]
The example to retrieve mailboxes using a policy is incorrect. It requires a DN. The simplest query that I use is:

```powershell
Get-Mailbox -ResultSize unlimited -Filter "AddressBookPolicy -eq '$((Get-AddressBookPolicy "<PolicyToSearchFor>").DistinguishedName)'"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9be59747-da94-86da-ed22-d3c7069b1ea6
* Version Independent ID: 9f3d2cd4-c865-cdab-42e4-ab6c0cd763b8
* Content: [Remove-AddressBookPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-addressbookpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-AddressBookPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-AddressBookPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@poundy, confirmed. I updated the topic with your example.

Thanks for the feedback.

Closing
