### ISSUE TITLE
Inconsistency on WhoCanRegister parameter

### ISSUE THREAD

**Issue by lebosch** [MicrosoftDocs/office-docs-powershell#7846]
The description of the WhoCanRegister parameter explains that EveryoneInCompany is the default value, but the table below shows Everyone as default value. I think this also should be EveryoneInCompany.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by lebosch** [comment]
Thanks for your response @get-itips . I notice that the page has been updated and shows the default value consistently. Although I don't think the information displayed is correct. I provisioned a new M365 tenant and noticed that the default setting is EveryoneInCompany. This seems to be the case on all tenants I checked.
![image](https://user-images.githubusercontent.com/84965045/121041932-7de27a80-c7b3-11eb-92f3-55419ecf202c.png)

**Comment by get-itips** [comment]
> Thanks for your response @get-itips . I notice that the page has been updated and shows the default value consistently. Although I don't think the information displayed is correct. I provisioned a new M365 tenant and noticed that the default setting is EveryoneInCompany. This seems to be the case on all tenants I checked.
> ![image](https://user-images.githubusercontent.com/84965045/121041932-7de27a80-c7b3-11eb-92f3-55419ecf202c.png)

Thanks for returning and sharing that information, I'll try to verify that. Thanks again

**Comment by dariomws** [comment]
Hi, sorry for intruding, but when I create a new Meeting Policy with New-CsTeamsMeetingPolicy "Everyone" is the default value:
![image](https://user-images.githubusercontent.com/33589238/122377050-035cec00-cf65-11eb-9e13-cf35a07a4f59.png)

"Everyone in the organization" (EveryoneInCompany) is the default value when you create a Meeting Policy from the Admin Center:
![image](https://user-images.githubusercontent.com/33589238/122377449-62bafc00-cf65-11eb-9bdc-548f68434b03.png)

**Comment by lebosch** [comment]
@dariomws Checked on my side. You are right. Seems to be a difference in how the MeetingPolicy is being created. The behavior on the global policy seems similar to policies created from the Admin Center.

**Comment by get-itips** [comment]
Just tested with `2.4.0-preview` and `2.3.1` and after creating a new TeamsMeetingPolicy the default in my case is EveryoneInCompany

I am trying to confirm with the team behind the module as based on your feedback I now think we could get different defaults in different tenants?

**Comment by dariomws** [comment]
@get-itips very strange...

**Comment by get-itips** [comment]
More information, the default _seems_ to be inherited from the setting that is currently set in the Global policy. Trying to confirm and if that is true, will add a note to the parameter.

**Comment by get-itips** [comment]
> More information, the default _seems_ to be inherited from the setting that is currently set in the Global policy. Trying to confirm and if that is true, will add a note to the parameter.

I could confirm this is what happens in the practice. However, as this issue is for the Set- and the edit should be done in the New- article, we can close this one @yogkumgit

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @lebosch Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
