### ISSUE TITLE
Get-MessageTraceDetail We cannot currently process your request, please wait a few minutes and try again

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#7852]
Pretty sure this is a wrong place to report, but still... Perhaps someone will be able to help me understand how to overcome this issue.
Long story short: I am having a really hard times while exporting message trace from Office365. Basically speaking I am trying to export 24 hours worth of data and it errors out after 17 minutes 30 seconds. I have double checked that and it seems like it errors out exactly after that specific time.
The command is like the following:
```
StartDate = Get-Date 2021-05-26
$EndDate = $StartDate.AddDays(1)
$pageSize = 5000

do
{
    Write-Output "Getting page $page of messages..."
    $messagesThisPage = Get-MessageTrace -StartDate $StartDate -EndDate $EndDate -PageSize $pageSize -Page $page
     
    Write-Output "There were $($messagesThisPage.count) messages on page $page..."
    $messageList += $messagesThisPage
     
    $page++
}
until ($messagesThisPage.count -lt $pageSize)
```

A error is the following:
```
We cannot currently process your request, please wait a few minutes and try again.
At C:\Users\adm-ysamorodov\AppData\Local\Temp\tmp_xvllfm34.gvo\tmp_xvllfm34.gvo.psm1:25736
char:9
+         $steppablePipeline.End()
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-MessageTrace], FfoReportingExceptio
   n
    + FullyQualifiedErrorId : [Server=CO6PR14MB4500,RequestId=4bd37bab-b241-4066-8ece-0fb588
   abbff0,TimeStamp=5/28/2021 3:43:14 PM] [FailureCategory=Cmdlet-FfoReportingException] F9
  3DD5F0,Microsoft.Exchange.Management.FfoReporting.GetMessageTrace
    + PSComputerName        : outlook.office365.com
 ```

One more thing to note is Fiddler showing error 500 every now and then while the script is running

Nothing changes if I do a 4 hour batch only or change page size. It always errors out after 17 minutes and 30 seconds

**Comment by chrisda** [comment]
@YuriySamorodov, you should open a support case and ask there.

**Comment by YuriySamorodov** [comment]
Ah, sorry. Forgot to set this one as resolved.
It appears there was a Database problem on Microsoft side.
