### ISSUE TITLE
Reverse engineering Team & Channel from ChannelId

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7854]
Hello,

Get-CsCallQueue returns an Object including the ChannelId of a TeamsChannel.
How would one be able to query which Team this channel is in, with only the Channel Id?

I humbly submit `Get-TeamAndChannel` (https://github.com/DEberhardt/TeamsFunctions/blob/main/Private/Functions/Get-TeamAndChannel.ps1) but was wondering whether there _is_ an easier way :)

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2523879-a846-25cf-c296-1f8b27b8c8dd
* Version Independent ID: 9a704476-5542-7035-b2fd-4463dbfa755f
* Content: [Get-CsCallQueue (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DEberhardt David, how are you?
Is there any article that you feel needs a fix? as here we are limited to documentation fixes.
Thanks for sharing your script, for others to see here looking for the same!
Thanks

**Comment by DEberhardt** [comment]
Well, there is no specific article about this that I could pinpoint to improve based on the above.
I could write a blog post to highlight the steps I have undertaken to get to which Team & Channel is used on Call Queues.

Just wanted confirmation whether there is, in fact, a documented way I did not (yet) find :)

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DEberhardt  If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
