### ISSUE TITLE
Prefix is not adding prefix to all the cmdlets/functions

### ISSUE THREAD

**Issue by VikasSukhija** [MicrosoftDocs/office-docs-powershell#7859]
Import-Module MicrosoftTeams -Prefix SOL
Prefix only prefixes the teams command, all the cs functions are not prefixed when importing the module.

Name              : Microsoft.TeamsCmdlets.PowerShell.Custom
Path              : C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\Microsoft.TeamsCmdlets.PowerShell.Custom.dll
Description       :
ModuleType        : Binary
Version           : 2.3.1.0
NestedModules     : {}
ExportedFunctions :
ExportedCmdlets   : {Add-TeamChannelUser, Add-TeamsAppInstallation, Add-TeamUser, Get-LicenseReportForChangeNotificationSubscription...}
ExportedVariables :
ExportedAliases   :

**Comment by get-itips** [comment]
Hello @VikasSukhija 
This has already been reported, please see [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7579#issuecomment-822657676)
Thanks

**Comment by VikasSukhija** [comment]
The other issue is closed  and no resolution is there.
Many customers use this in their old scripts.

**Comment by get-itips** [comment]
> The other issue is closed and no resolution is there.
> Many customers use this in their old scripts.

Hello @VikasSukhija 
The best in this situation is to open a support ticket, as here we are limited to documentation/articles fixes.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @VikasSukhija Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
