### ISSUE TITLE
Documentation for 2.3.2-preview Connect-MicrosoftTeams with -AccessTokens feature is inadequate

### ISSUE THREAD

**Issue by djryanj** [MicrosoftDocs/office-docs-powershell#7866]
The current documentation around how to implement the new -AccessTokens feature is inadequate. Currently, it reads this:

```ps
$graphtoken = #Get MSGraph Token for following for resource  "https://graph.microsoft.com" and scopes "AppCatalog.ReadWrite.All", "Group.ReadWrite.All", "User.Read.All";
$teamstoken = #Get Teams resource token for resource id "48ac35b8-9aa8-4d74-927d-1f4a14a0b239" and scope "user_impersonation";

Connect-MicrosoftTeams -AccessTokens @($graphtoken, $teamstoken) -AccountId $adminaccount

Account                 Environment 	Tenant                                TenantId                         
-------                 -----------  ------------------------------------  ------------------------------------
user@contoso.com        AzureCloud   xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx  xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

Getting the tokens referenced is non-trivial. A complete working example to do just that would be ideal, but also acceptable would be pointers to the correct set of cmdlets or flows needed to complete actually getting the tokens with the correct scopes.

**Comment by elpamyelhsa** [comment]
When requesting a scope you need the following:
teamstoken uses scope "48ac35b8-9aa8-4d74-927d-1f4a14a0b239/.default"
graphtoken uses scope "https://graph.microsoft.com/.default"

Also, you will need to use the Azure Portal to make an "App Registration", Goto "API permissions":

```
"Add permissions", "APIs my organization uses", "Skype and Teams Tenant Admin API", "Delegated permissions", "user_impersonation"
"Add permissions", "Microsoft Graph", Tick the following: "AppCatalog.ReadWrite.All", "Group.ReadWrite.All", "User.Read.All"
```
Then "Certificates & secrets", "Client secrets" and save the secret.

Hope this helps.

**Comment by get-itips** [comment]
Hello @djryanj how are you? Hope you are doing good.
`-AccessTokens` is part of 2.3.2-preview, the documentation reflects what is currently available in the GA version of the module.
I have no precision but `-AccessTokens` will be probably soon in GA and the corresponding article will be updated.
Thank you!

**Comment by get-itips** [comment]
Hello @djryanj 
Thanks for returning and sharing more information.
The errors received when trying to invoke -Cs* cmdlets after connecting were already reported, and I passed the information to the team behind the module and they are aware. I also understand that, as you could identify, the method to connect using tokens will be improved/changed soon, so hopefully we will be able to update the article according to that.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @djryanj Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
