### ISSUE TITLE
Move-PnPFile does not move over a person field value and a taxonomy field value

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/office-docs-powershell#7874]
I use:
`Move-PnPFile -SourceUrl "DPCDocuments/01-RFP Completion Checklist_505486.docx" -TargetUrl "OldDPCDocuments/01-RFP Completion Checklist_505486.docx" -Overwrite -Connection $siteConn -Force`
in a script, It works well with text fields and the system fields but one person field value and one taxonomy field value do not move over. 
The source and target have the same content type.
After a while it started working
But now I get error "is checked out for editing by .." 
How can I force check in before the move?

**Comment by get-itips** [comment]
Hello @Ofer-Gal 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!
