### ISSUE TITLE
Get-ExternalInOutlook doesn't work in Shared Mailbox

### ISSUE THREAD

**Issue by cupntea** [MicrosoftDocs/office-docs-powershell#7876]
Hi!
After we enabled Get-ExternalInOutlook we noticed that only regular mailboxes display [External] tag, but Shared mailboxes don't have it.
Is it a bug or a feature?

**Comment by chrisda** [comment]
@cupntea, your best bet is to open a support case and ask there.

**Comment by cupntea** [comment]
@chrisda no offense, but knowing how exchange support are treating those request, it's unlikely I'll get a coherent response even after a month of emails exchange explaining what I actually need.

**Comment by chrisda** [comment]
@

**Comment by chrisda** [comment]
@cupntea, sorry for the delay. I was having difficulty getting a response.

The up-to-date consensus is that this works on regular mailboxes (clearly) and shared mailboxes, but not Microsoft 365 Group mailboxes.

Can you confirm or deny?

**Comment by cupntea** [comment]
@chrisda as far as I remember it simply didn't work for Shared mailboxes.
Ok, I will create a support ticket with Microsoft.

**Comment by yogkumgit** [comment]
@cupntea Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
