### ISSUE TITLE
Set-CsExternalAccessPolicy cannot be found

### ISSUE THREAD

**Issue by vasgupta** [MicrosoftDocs/office-docs-powershell#7894]
[The command Set-CsExternalAccessPolicy cannot be found in powershell even though I have installed the module Microsoft Teams and it is clearly a function of that module.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fe1d21-20a0-9b8e-f08c-caf788005f9b
* Version Independent ID: 486050c0-de7f-31d4-f09e-78324336eb26
* Content: [Set-CsExternalAccessPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csexternalaccesspolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsExternalAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsExternalAccessPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @vasgupta I could find the cmdlet, please be sure to be running the last version of Teams PowerShell and also having only one version installed.
Hope this information helps you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @vasgupta hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
