### ISSUE TITLE
Unable to Connect-ExchangeOnline 2.0.5 using VSCode

### ISSUE THREAD

**Issue by baldieavenger** [MicrosoftDocs/office-docs-powershell#7895]
Hi,
When updating to the latest ExchangeOnlineManagement module, i'm unable to get the pop out to sign in. This works fine with 2.0.3 and in ISE / PowerShell.
Running 5.1 Powershell, 1.56.2 (system setup) Code.
Attached Diagnostic logs when both versions for comparison and a screenshot of the creds pop up Im expecting.
Thanks!
John

[CodeLogs20210604.zip](https://github.com/MicrosoftDocs/office-docs-powershell/files/6607604/CodeLogs20210604.zip)

Also registered with the PowerShell module repo: https://github.com/PowerShell/vscode-powershell/issues/3396

**Comment by andschwa** [comment]
Hey @baldieavenger, could you test 2.0.4 of their module? It would help narrow down the issue, telling us if if the bug appeared between 2.0.3 and 2.0.4, or 2.0.4. and 2.0.5, instead of the wider range 2.0.3 to 2.0.5. Thanks!

**Comment by baldieavenger** [comment]
Hey Andrew,

It does impact 2.0.4, I assumed 2.0.5 would fix it but it hasnt but we have an exclusion is our module update script now to stick with 2.0.3! 
Tested with a colleague and on a server so not just my local impacted.
Thanks! John

**Comment by baldieavenger** [comment]
Hi Andrew,
Anything more you need from me to dig into this?
Thanks!
John

**Comment by andschwa** [comment]
Hey @yogkumgit, any chance you have looked at this? I haven't yet.

**Comment by dariomws** [comment]
Hi @baldieavenger, thank you for your feedback.

I tested it and seems to be working with PowerShell ISE:
![image](https://user-images.githubusercontent.com/33589238/124085907-ca3a7680-da50-11eb-8ca1-181623902745.png)

Also with VS Code:
![image](https://user-images.githubusercontent.com/33589238/124097906-51d9b280-da5c-11eb-9326-af8512331d21.png)

**Comment by dariomws** [comment]
Hi @baldieavenger, thank you for your feedback.

I've tested it and it's working for me.

VS Code:
![image](https://user-images.githubusercontent.com/33589238/124098482-e0e6ca80-da5c-11eb-8aed-9c4b9fe8fec8.png)

ISE:
![image](https://user-images.githubusercontent.com/33589238/124098743-1f7c8500-da5d-11eb-8e79-905f3356a095.png)

**Comment by baldieavenger** [comment]
Looks like its due to "System.Windows.Forms"
https://github.com/PowerShell/vscode-powershell/issues/3394#issuecomment-872416633

**Comment by dariomws** [comment]
Thanks for sharing, @baldieavenger.

Do you think there is something to improve in the documentation for this module? It seems that it's a very specific issue. Here we are limited to documentation issues and improvements.

**Comment by baldieavenger** [comment]
HI Dario,

No, id think its not documentation related thnaks! Looks like you can close this! 

Thanks,

John

**Comment by dariomws** [comment]
@baldieavenger Thank you for your contribution to make the docs better! Much appreciated!

@yogkumgit could you kindly close this issue? Thanks!

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @baldieavenger Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
