### ISSUE TITLE
Get-CsCallQueue Statistics value always 0

### ISSUE THREAD

**Issue by elpamyelhsa** [MicrosoftDocs/office-docs-powershell#7896]
The Get-CsCallQueue has a property named "Statistics" that returns a "Current queue size" value. As of a few weeks ago this value is now only returning 0 even when this queue is not empty. 

`echo (Get-CsCallQueue -name "NodeOne Support").Statistics.StatValue `
Attached is a full output showing the incorrect line: 
`Statistics : Current queue size = 0`

Is this a problem that can be fixed, or is there a new way to get this data?

Tested using both MicrosoftTeams Connector 2.3.1 & 2.3.2-preview
Tested using both Powershell 5.1 and Powershell 7
Tested using Credential Login (Since Tokin Login is also broken for Get-CsCallQueue)

[Get-CSCallQueue.txt](https://github.com/MicrosoftDocs/office-docs-powershell/files/6607607/Get-CSCallQueue.txt)

**Comment by get-itips** [comment]
Hello @elpamyelhsa how are you? Hope you are doing good. 👍 
Here, we are limited to documentation fixes and improvements, I'll try to pass this on.
Thank you!

**Comment by yogkumgit** [comment]
@ Thank you very much for the comment. @elpamyelhsa If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
