### ISSUE TITLE
2.3.2preview Get-Cs commands do not work using AccessTokens login.

### ISSUE THREAD

**Issue by elpamyelhsa** [MicrosoftDocs/office-docs-powershell#7897]
Being able to use software to automate a login is important for scripting and automation. As of MicrosoftTeams-2.3.2preview the login has been updated to use AccessTokens. But once connected using AccessTokens no CS commands can be executed.

Using Microsoft Teams 2.3.2preview Powershell 

Connecting with AccessTokens will connect, but requesting the Get-CsCallQueue will show an error:
```
PS> Connect-MicrosoftTeams -AccountId "myadminuser@mydomain.onmicrosoft.com" -AccessTokens @($graph_token, $access_token) -TenantDomain "mydomain.com.au" 

Account                                   Environment Tenant                               TenantId
        -------                                   ----------- ------                               --------
myadminuser@mydomain.onmicrosoft.com AzureCloud  e10ffc30-46a9-46bb-bbfb-xxxxxxxxxxxe10ffc30-46a9-46bb-bbfb-xxxxxxxx

PS> Get-CsCallQueue | Select-Object -Property Name,Statistics

Get-CsOnlineSession : Run Connect-MicrosoftTeams before running cmdlets.
```

Using Microsoft Teams 2.3.1 Powershell 

On the other hand, Connecting with Username/Password will allow the command to run normally.
```
PS> $User = "myadminuser@mydomain.onmicrosoft.com"
PS> $PWord = ConvertTo-SecureString -String "[myNon-MFAPassowrd]" -AsPlainText -Force
PS> $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
PS> Connect-MicrosoftTeams -Credential $Credential

Account                                   Environment Tenant                               TenantId
        -------                                   ----------- ------                               --------
myadminuser@mydomain.onmicrosoft.com AzureCloud  e10ffc30-46a9-46bb-bbfb-xxxxxxxxxxxe10ffc30-46a9-46bb-bbfb-xxxxxxxx

PS> Get-CsCallQueue | Select-Object -Property Name | ConvertTo-Json

[
    {
        "Name":  "NodeOne Accounts"
    },
    {
        "Name":  "NodeOne Support"
    }
]
```

**Comment by DEberhardt** [comment]
> Replicating a working condition on v2.3.1 proves that permissions are correct, but just in the interest of full disclosure... The account in question still has the "Skype For Business Online Legacy Administrator" role (in addition to the Teams Administrator Role) without which these commands wont work...

interesting. Don't know if this helps, but I know that the PsSession allowing the `-Cs...`-CmdLets to work needs to be created prior. This _usually_ happens stealthily in the background, but I am wondering whether this is where it fails for you here.

After running `Connect-MicrosoftTeams` and executing any Cs-CmdLet (I use `Get-CsPresencePolicy` for performance reasons - see [`Use-MicrosoftTeamsConnection`](https://github.com/DEberhardt/TeamsFunctions/blob/main/Private/Functions/Use-MicrosoftTeamsConnection.ps1) for details) is the PsSession created? (Query with `Get-PsSession` before and after).

If the session does not get created correctly, then I would presume that this is a limitation with the preview version...

**Comment by get-itips** [comment]
Hello @elpamyelhsa how are you? hope you are doing good.
This has been reported several times, as it is not a documentation issue, I am afraid I can not be of further help, however, I already passed this information on to the team behind the module.
Thank you!

**Comment by elpamyelhsa** [comment]
Thanks get-itips, is there an official place to open a ticket for this fault. I had opened one on Microsoft 365 and was sent to this repo to report the issue, but if a better place exists it is getting urgent as the non-preview Teams Connector is also affected by this and this has broken things.

**Comment by get-itips** [comment]
> Thanks get-itips, is there an official place to open a ticket for this fault. I had opened one on Microsoft 365 and was sent to this repo to report the issue, but if a better place exists it is getting urgent as the non-preview Teams Connector is also affected by this and this has broken things.

Hello @elpamyelhsa ! Thanks for your reply.
I would recommend opening a support ticket directly from your tenant and notifying about this.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @elpamyelhsa Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
