### ISSUE TITLE
No download link

### ISSUE THREAD

**Issue by tkmamedov** [MicrosoftDocs/office-docs-powershell#7905]
There is no download as PDF link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c916371e-aef0-f91e-e04d-16110358a306
* Version Independent ID: bd073f8e-ba80-25ed-0fe4-286641e9f043
* Content: [Exchange Server PowerShell (Exchange Management Shell)](https://docs.microsoft.com/en-us/powershell/exchange/exchange-management-shell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-management-shell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-management-shell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@tkmamedov, are you saying that there used to be a Download as PDF link, but it went away?

**Comment by yogkumgit** [comment]
@tkmamedov We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by tkmamedov** [comment]
> @tkmamedov, are you saying that there used to be a Download as PDF link, but it went away?

Sorry for late reply.
There is no any link to download the Exchange Server PowerShell documentation as one PDF file like on this page https://docs.microsoft.com/en-us/exchange/exchange-server?view=exchserver-2019 (![image](https://user-images.githubusercontent.com/10899421/141691035-ef81e6b1-cc1b-479e-82ff-c1902bb162cb.png).

It would be great if this feature appear.
But I see that Microsoft is going to disable this feature for some reasons. I don't understand why. I think sometimes it's very useful to have an opportunity to read a doc in PDF.

**Comment by chrisda** [comment]
@tkmamedov, typically, when a feature like this goes away, it usually has something to do with security, accessibility, or both.

Wasn't the major problem with PDF download it would take the entire content set and convert it to PDF for download (depending on how the table of contents was laid out)?
