### ISSUE TITLE
Question about unsubscribing group members to calendar events

### ISSUE THREAD

**Issue by einue** [MicrosoftDocs/office-docs-powershell#7912]
How can I unsubscribe already existing group members from group calender events?

I guess that AlwaysSubscribeMembersToCalendarEvents works only for new members.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80326e44-6beb-8983-57ab-8333608c504b
* Version Independent ID: 8962c0dc-72a3-208a-33de-6a89cd56b6fc
* Content: [Set-UnifiedGroup (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @einue, thank you for your feedback.

Please check [Remove-UnifiedGroupLinks](https://docs.microsoft.com/powershell/module/exchange/remove-unifiedgrouplinks).

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @einue Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
