### ISSUE TITLE
Discovery Management role group should be eDiscovery Manager

### ISSUE THREAD

**Issue by bybytaren** [MicrosoftDocs/office-docs-powershell#7920]
I believe this article refers to a role group which does not exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f7f0a23-5b87-02f2-5bce-eddc3413f7f4
* Version Independent ID: 6694e76a-b1e0-9cc6-08ab-beb0cf388e75
* Content: [New-ComplianceSearch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ComplianceSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bybytaren, confirmed. This affects about 9 other cmdlet reference topics, all of which I updated.

Thanks for the feedback.

Closing

**Comment by chrisda** [comment]
Actually, upon further review, the case was a bit more subtle. The following cmdlets are available both in Exchange Server PowerShell AND Security & Compliance Center PowerShell:

- Get-ComplianceSearch
- Get-ComplianceSearchAction
- New-ComplianceSearch
- New-ComplianceSearchAction
- Remove-ComplianceSearch
- Set-ComplianceSearch
- Start-ComplianceSearch
- Stop-ComplianceSearch

I changed the note to say:

> In on-premises Exchange, this cmdlet is available in the Mailbox Search role. By default, this role is assigned only to the Discovery Management role group.

The requirements in Security & Compliance Center PowerShell for those cmdlets isn't nearly as strict (required role assigned to many role groups, including Organization Management).
