### ISSUE TITLE
It would be nice to give slight hint what IPPS is

### ISSUE THREAD

**Issue by HenkPoley** [MicrosoftDocs/office-docs-powershell#7921]
Just in case I run into the obvious use case of whatever Connect-**IPPS**Session does in the future. 

"Oh, this clearly needs an IPPS session, let me find that thing back"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 945ab2ea-22ae-814f-8898-fe84b7f29870
* Version Independent ID: 5383d152-988d-b1ee-4957-db5fb6213754
* Content: [Connect-IPPSSession (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-ippssession?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-IPPSSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Connect-IPPSSession.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@HenkPoley, I'm not sure if knowledge of 'IPPS' is important. The important point is: you use Connect-ExchangeOnline to connect to Exchange Online PowerShell, and you use Connect-IPPSSession to connect to Security & Compliance Center PowerShell or standalone (no Exchange Online mailboxes) Exchange Online Protection (EOP) PowerShell (e.g., NOT Exchange Online PowerShell). Semi-ridiculously, one cmdlet could be named Connect-A and the other Connect-B; the name itself isn't important (although it would be difficult to remember which one to use). 

Breaking it down, I'm confident that 'PS' stands for PowerShell, as in the cmdlet Get-PSSession. I would presume IP stands for 'information protection', but that's a guess. So 'IPPS' means 'information protection PowerShell'.

Does that help?

**Comment by yogkumgit** [comment]
@HenkPoley Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
