### ISSUE TITLE
Insufficient examples

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/office-docs-powershell#7922]
Article needs more examples showing proper use of parameters. The simple example provided creates a search service application with default database name having undesirable GUID in the database name. Please provide examples using the -DatabaseName parameter. Article also lacks any reference to creating the required proxy using New-SPEnterpriseSearchServiceApplicationProxy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90a0c66a-1511-9ddd-ecb0-ad0e30974d6a
* Version Independent ID: 0c037896-9742-b831-75a2-14264774dbc1
* Content: [New-SPEnterpriseSearchServiceApplication (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spenterprisesearchserviceapplication?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchServiceApplication.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPEnterpriseSearchServiceApplication.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks @SharePointBlackBelt for your feedback, will propose an improvement to the article.
