### ISSUE TITLE
"Unable to remove user as it wasn't found. User will be skipped"

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/office-docs-powershell#7924]
The basic command is returning "Unable to remove user as it wasn't found. User will be skipped" and does not remove the admin. 

Set-PnPTenantSite -identity https://nexvortex1-my.sharepoint.com/personal/alatessa_nexvortex_com -owners "user1@domain.com"

Get-PnPSiteCollectionAdmin
Id Title         LoginName                                            Email
33 User 1 i:0#.f|membership|user1@domain.com   user1@domain.com 

remove-PnPsiteCollectionAdmin -owners "user1@domain.com"
WARNING: Unable to remove user as it wasn't found. User will be skipped.

Remove-PnPsiteCollectionAdmin -owners @("user1@domain.com")
WARNING: Unable to remove user as it wasn't found. User will be skipped.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c60b3ab8-60f6-9e25-39f0-c0805919193a
* Version Independent ID: d7fc1520-6de6-08f5-50a4-d3e8f0dfc620
* Content: [Remove-PnPSiteCollectionAdmin (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpsitecollectionadmin?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPSiteCollectionAdmin.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPSiteCollectionAdmin.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @ckssaas Chris, how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by ckssaas** [comment]
Done. Thanks

https://github.com/pnp/powershell/issues/820#issue-923041764

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ckssaas If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
