### ISSUE TITLE
Get-EXOMailboxFolderStatistics no longer includes the ParentFolderId property.

### ISSUE THREAD

**Issue by nadcraker** [MicrosoftDocs/office-docs-powershell#7925]
`Get-MailboxFolderStatistics` (the old cmdlet) used to return a property called `ParentFolderId`. The new `Get-EXOMailboxFolderStatistics` does not. I was using this data to build a treeview relationship of a user's mailbox. 

How can we use the new `Get-EXOMailboxFolderStatistics` cmdlet to get the parent folder of mailbox folders?

**Comment by dariomws** [comment]
Hi @nadcraker, thank you for your feedback.

I understand that there is no way with Get-EXOMailboxFolderStatistics, and you should use Get-MailboxFolderStatistics to get the parent folder.

If you want to provide product feedback to add features (parameters) you can use the following options:
- https://techcommunity.microsoft.com/t5/exchange-team-blog/bg-p/Exchange
- https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#report-bugs-and-issues-for-the-exo-v2-module
