### ISSUE TITLE
Update for documentation of Microsoft Teams powershell module.

### ISSUE THREAD

**Issue by ZeffyReport** [MicrosoftDocs/office-docs-powershell#7933]
Can this documentation please be updated to reflect the updated module which has been made available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6804423b-8e08-5916-9355-6bebe8bb08b0
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [MicrosoftTeamsPowerShell Module](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @ZeffyReport how are you?
Can you kindly detail what you see is missing/wrong from the page you opened the issue for?
Take into account that the documentation reflects the latest GA version of the module.
Thanks!

**Comment by ZeffyReport** [comment]
https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps looks like it still refers to the 1.1.6 module commands and not the latest (2.3.1) module version.

**Comment by yogkumgit** [comment]
@get-itips Please review

**Comment by get-itips** [comment]
Hello @ZeffyReport 
I have been analyzing this, the article you reference is automatically generated based on the cmdlet articles already present in the teams folder, currently there are also some Public Preview articles and also some deprecated ones (to inform users about this), and cmdlets from 2.3.1. Please also take into account that you will also find _SfB-module_ cmdlet articles [here](https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps).
Also, there are some open PRs that will add some more cmdlets to this list, so once published, you will be able to see them listed.
Hope this information helps you, thanks for your feedback.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ZeffyReport Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
