### ISSUE TITLE
Set-MailboxAutoReplyConfiguration cant read scandinavian characters.

### ISSUE THREAD

**Issue by rikisorsa** [MicrosoftDocs/office-docs-powershell#7935]
I've created a powershell script that removes all licences and group memberships from a person when he/she is leaving the company and adds an automatic reply to their mailbox. Everything else is going fine, except when i added Scandinavian letters into the hardcoded auto-reply.

    if ( "y" -eq $Automaattivastaus) {
    $Username = Read-Host -Prompt "Nimi automaattivastaukseen"
    $Paivamaara = Read-Host -Prompt "Milloin henkilön työsuhde on päättynyt?"
    $Vastaanottaja = Read-Host -Prompt "automaattivastaus, Mihin sähköpostiin ottaa yhteyttä"

    set-MailboxAutoReplyConfiguration -identity $Email -AutoReplyState Enabled -InternalMessage  "Henkilön $Username palvelussuhde on päättynyt $Paivamaara. Pyydän kääntymään hänen työtehtäviensä hoitoon liittyvissä asioissa sovelletaan Lakia yksityisyyden suojasta työelämässä (759/2004)."

"snippet from auto reply PyydÃ¤n kÃ¤Ã¤ntymÃ¤Ã¤n hÃ¤nen tyÃ¶tehtÃ¤viensÃ¤ hoitoon liittyvissÃ¤ asioissa." As you can see the characters break. If anyone would have the solution how to fix this I would be grateful.

**Comment by dariomws** [comment]
@rikisorsa - thank you for submitting feedback.

I think the best way forward is to open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @rikisorsa Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
