### ISSUE TITLE
Errors in the code explanations

### ISSUE THREAD

**Issue by GoranLindgrenGbgStad** [MicrosoftDocs/office-docs-powershell#7936]
Saw at least four errors in the code examples. Explanations referred to wrong file name extensions. 
![image](https://user-images.githubusercontent.com/47183112/122064022-15b61900-cdf1-11eb-86e7-3840eb8f06d7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc5b5ab2-722d-04a7-e97a-196b24e8888e
* Version Independent ID: 86b3d2ff-be86-42e6-6bd1-6735525f180e
* Content: [Rename-PnPFile (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/rename-pnpfile?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Rename-PnPFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Rename-PnPFile.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @GoranLindgrenGbgStad 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @GoranLindgrenGbgStad Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
