### ISSUE TITLE
Setting AutoMapping option to true for non-FullAccess rights is not allowed.

### ISSUE THREAD

**Issue by nidelius** [MicrosoftDocs/office-docs-powershell#7945]
Our workflow:

We have a mailbox to which PDFs are sent. These are manually processed by 2 employees who has full access to the shared mailbox. About 50 persons are in need of the PDF files and sometimes there are delays or these 50 persons need instant access to the PDF files in the mailbox. Therefor we granted Authenticated Users ReadPermission for this shared mailbox. Fine.

BUT every user that wants to access the box needs to go into their outlook settings and add the mailbox manually.

I'd like to be able to automate this. **But this is not possible by design** why?
Add-MailboxPermission -identity ordererkannande -User USER@DOMAIN.ORG -AccessRights 'ReadPermission' -AutoMapping:$true

Setting AutoMapping option to true for non-FullAccess rights is not allowed. AutoMapping=true option can only be used t
ogether with FullAccess permission.
    + CategoryInfo          : InvalidOperation: (:) [Add-MailboxPermission], InvalidOperationException
    + FullyQualifiedErrorId : [Server=AM9P192MB0904,RequestId=685d9bfe-adca-4f51-b54e-1393d29a75ba,TimeStamp=2021-06-1
   6 14:43:18] [FailureCategory=Cmdlet-InvalidOperationException] 1E1E450,Microsoft.Exchange.Management.RecipientTask
  s.AddMailboxPermission
    + PSComputerName        : outlook.office365.com

**Comment by nidelius** [comment]
Adding it manually here is not user friendly:

Let the users add the shared mailbox under the primary mailbox manually. To do it, click File tab > Choose Account Settings, then select Account Settings from the menu. > Select the Email tab and choose the account to Change. > Choose More Settings > Advanced > Add. > Type the shared email address and click OK. After that, the shared mailbox will appear under the primary mailbox in a few minutes.

![image](https://user-images.githubusercontent.com/142629/122242240-72820400-cec3-11eb-9215-b533bbd8b10d.png)

**Comment by dariomws** [comment]
Hi @nidelius, thank you for your feedback.

I cannot answer why but you can find more information here:
https://support.microsoft.com/topic/auto-mapping-doesn-t-work-as-expected-in-an-office-365-hybrid-environment-21eaea30-c19e-6b2f-ad25-e24e3b6f193d

Here we are limited to documentation issues and improvements.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @nidelius Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by chrisda** [comment]
@nidelius, late to the party, but I can 100% confirm that auto-mapping requires Full Access permissions on the mailbox.

You might find a solution for creating/modifying Outlook profiles in this blog post:

<https://techcommunity.microsoft.com/t5/outlook-global-customer-service/zeroconfigexchange-automating-the-creation-of-an-outlook-profile/ba-p/389691>
