### ISSUE TITLE
Identity parameter only takes ExchangeGuid

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#7946]
I would submit a PR, but you probably want to re-word the entire parameter description to make it right. It doesn't accept the various properties and the examples don't actually work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0404960d-05e8-6e6f-8063-ebed163ecefd
* Version Independent ID: d79b2d09-a176-d22e-e5ad-49a8fa22df2a
* Content: [Start-ManagedFolderAssistant (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/start-managedfolderassistant?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Start-ManagedFolderAssistant.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeremyTBradshaw, let's set the stage a bit.

That cmdlet is available in Exchange 2010 through 2019 and Exchange Online. So which environment are you talking about?

As an observation, Exchange PowerShell is pretty consistent about parameter types and accepted values. The Identity parameter is of type MailboxOrMailUserIdParameter, so I would be surprised if it didn't accept other guaranteed unique identifiers (in particular, DistinguishedName).

In an E5 tenant, I tried the following Identity values for a mailbox and they all worked without error or any sort of acknowledgement, so I presume it actually worked:

- Name
- Alias
- DistinguishedName
- Guid
- ExchangeGuid
- PrimarySmtpAddress
- LegayExchangeDN
- SamAccountName

Comments?

**Comment by JeremyTBradshaw** [comment]
Hi @chrisda ,

I am referring to EXO specifically.  Give it a try and see what I mean.  Agreed I should have been clear on where I'm referring to.

**Comment by JeremyTBradshaw** [comment]
@chrisda I guess my luck was just really bad and this seems to be related to certain mailboxes in Exchange Online which have archive mailboxes enabled.  This is the most official explanation I can find: https://docs.microsoft.com/en-us/archive/blogs/timmcmic/office-365-start-managedfolderassistant-in-office-365

But for me, the issue is there even for long-standing-archive-enabled mailboxes, not just newly-archive-enabled.  In any event, I was sloppy with this one, and am happy to close it and forget about it as an undocumented feature.  Thanks and sorry to have wasted your cycles.

**Comment by chrisda** [comment]
@JeremyTBradshaw, I added a note to the Identity parameter description based on your findings.

Thanks.
