### ISSUE TITLE
Teams module 2.x - Auth Challenges

### ISSUE THREAD

**Issue by prlipscombe** [MicrosoftDocs/office-docs-powershell#7951]
Can the auth in the module be revised to operate in a consistant way with all other Microsoft Pwershell admin modules (connect-azuread, connect-exchangeonline, connect-msolservice for example)

Connect-Teams will only correctly authenticate using "conneced windows accounts" - Settings>Accounts>Access Work or School for example.
![image](https://user-images.githubusercontent.com/15944333/122381234-9b0c0b80-cf60-11eb-8926-370dbcc8d826.png)

The other MS modules allow you to enter and use a specific admin account and will also trigger MFA prompts as required.

**Comment by get-itips** [comment]
Hello @prlipscombe how are you?
Here, we are limited to documentation changes and improvements, for your request, I would suggest https://microsoftteams.uservoice.com/
Hope this information helps you,

**Comment by yogkumgit** [comment]
@prlipscombe Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
