### ISSUE TITLE
No details on which segment the users are in

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#7952]
This cmdlet is missing a key piece of information and the docs don't say how to get this - the segment that a user is part of. This is different than the policy they are linked to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9cecf1a-7ec5-06ae-6e47-43d804e3a473
* Version Independent ID: af1b46d5-bf75-8588-6b45-11b1ed353deb
* Content: [Get-InformationBarrierRecipientStatus (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-informationbarrierrecipientstatus?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-InformationBarrierRecipientStatus.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-InformationBarrierRecipientStatus.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @danmyhre, thank you for your feedback.

Once you get the policy's GUID with this cmdlet, you can use `Get-InformationBarrierPolicy -ExOPolicyId <GUID> | fl AssignedSegment` to verify the segment this user belongs to.

For more information, see [Define information barrier policies](https://docs.microsoft.com/microsoft-365/compliance/information-barriers-policies) and [Get-InformationBarrierPolicy](https://docs.microsoft.com/powershell/module/exchange/get-informationbarrierpolicy).

**Comment by danmyhre** [comment]
That is different. It is possible people are part of segments but not a policy.

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
Very similar to the other issue, you know what segment a user belong to verifying the AD property. If a segment is not assigned to a policy there is no information barrier applied to that segment and the users who belong to it.

For more information, see [Define information barrier policies](https://docs.microsoft.com/microsoft-365/compliance/information-barriers-policies).

If you want to request a new feature, I know the product teams are always looking for user feedback and how to make Exchange better. They keep a close tab on user feedback, and it would be awesome if you could add your feedback in the Exchange Team Blog: https://techcommunity.microsoft.com/t5/exchange-team-blog/bg-p/Exchange
Here we are limited to documentation issues and improvements.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @danmyhre Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
