### ISSUE TITLE
Users that are part of segment

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#7953]
No details on how to get the users that are part of a segment. Please add specifics on how to accomplish this basic task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a447d7aa-7227-75ae-6bb7-071af8f77012
* Version Independent ID: 7f10b8ff-4784-395d-872a-85b2c6522bda
* Content: [Get-OrganizationSegment (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-organizationsegment?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-OrganizationSegment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-OrganizationSegment.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @danmyhre, thank you for your feedback.

You cannot get that information with this cmdlet. As the segments are defined by Azure Active Directory properties, you can use AAD cmdlets to get that information.

For example, if you define the following segment:
New-OrganizationSegment -Name "HR" -UserGroupFilter "Department -eq 'HR'"

You can run the following command in AAD PowerShell module:
Get-AzureADUser -Filter "Department eq 'HR'"

**Comment by danmyhre** [comment]
How do you actually verify / see the segment that is assigned to the user? This is critical for working with this solution. Running a query against AAD is not the same.

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
Hi @danmyhre, as an AD property defines the segments, you can look for the users with that property. They are actually in the segment.

If you want to request a new feature, I know the product teams are always looking for user feedback and how to make Exchange better. They keep a close tab on user feedback, and it would be awesome if you could add your feedback in the Exchange Team Blog: https://techcommunity.microsoft.com/t5/exchange-team-blog/bg-p/Exchange
Here we are limited to documentation issues and improvements.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @danmyhre Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
