### ISSUE TITLE
Teams Powershell module unable to display account sign-in dialog

### ISSUE THREAD

**Issue by prlipscombe** [MicrosoftDocs/office-docs-powershell#7954]
In contract to all other MS powershell modules, the Teams Powershell module (version 2.3.1) is unable to dispay its sign-in account selection dialog should it be invoked after a windows system form is created.

I've distilled my code down to this to demonstrate
```
Add-Type -AssemblyName System.Windows.Forms
[System.Windows.Forms.Application]::EnableVisualStyles()

$frmNewForm = New-Object system.Windows.Forms.Form

Connect-MicrosoftTeams -Verbose
```

The -Verbose option when connecting to Teams shows me that its got that far and presumbaly has attempted to connect. However, nothing is ever displayed and the script will never progress further.

You can swap Connect-MicrosoftTeams for Connect-AzureAD, and they work perfectly.

Granted, code can be re-ordered to avoid this issue. But that's just avoiding the unexpected interaction thats present only in this module and none of the others (ExchangeOnline, MSOLService etc).

**Comment by get-itips** [comment]
Hello @prlipscombe how are you?
Here, we are limited to documentation changes and improvements, for your request, I would suggest https://microsoftteams.uservoice.com/
Hope this information helps you,

**Comment by yogkumgit** [comment]
@prlipscombe  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
