### ISSUE TITLE
Get-OwnerlessGroupPolicy and Set-OwnerlessGroupPolicy

### ISSUE THREAD

**Issue by mark3grahams** [MicrosoftDocs/office-docs-powershell#7959]
Get-OwnerlessGroupPolicy and Set-OwnerlessGroupPolicy are part of ExchangeOnlineManagement 2.0.5.

However, this does not appear to be documented or to actually work as far as I can test.

Is this supposed to be working?

**Comment by chrisda** [comment]
@mark3grahams, the feature itself is in Private Preview (invite only).

So, because the cmdlets are in the EXO V2 module code, anyone who downloads the module has access to them. But, they won't work unless you're part of the Private Preview.

**Comment by mark3grahams** [comment]
Yeah, I have since found this out. I do not think the release note for 2.0.5 called this out as Preview only.

**Comment by yogkumgit** [comment]
@mark3grahams Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
