### ISSUE TITLE
No instruction how to apply a change to all identities

### ISSUE THREAD

**Issue by andybrandt** [MicrosoftDocs/office-docs-powershell#7963]
I would expect a description here on how to change a parameter in all identities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8fa7e55-c3b1-7b37-f395-736ec82868a0
* Version Independent ID: 4630697b-375e-85f2-25b1-b944bc6dad5f
* Content: [Set-CsTeamsCallingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @andybrandt Andy, how are you?

Well, that depends on how is your tenant configured, but Global covers all users that do not have a policy explicitly assigned.
(and the example in the article configures a parameter for the Global policy)

Hope this information helps you

**Comment by andybrandt** [comment]
I know that and I know about Global. What I was unable to do is change these parameters for other policies.

**Comment by get-itips** [comment]
Hello @andybrandt Andy, how are you?
Ok I understand better now, will propose adding another example.
Thanks

**Comment by andybrandt** [comment]
While you are at it you may consider adding that some policies visible when one does Get-CsTeamsCallingPolicy can not be changed (eg. "Tag:AllowCalling").
