### ISSUE TITLE
Submit-PnPTeamsChannelMessage - ChannelMessage.ReadWrite.All no longer available

### ISSUE THREAD

**Issue by TheMasterPrawn** [MicrosoftDocs/office-docs-powershell#7966]
ChannelMessage.ReadWrite.All is no longer available from the Azure AAD app permissions list. When I try and run 

```ps1
Submit-PnPTeamsChannelMessage -Team "2020 Interns" -Channel "Mig1" `
     -Message "<strong>A bold new message</strong>" -ContentType Html
```
On my own tenant I get an error 

```ps1
Submit-PnPTeamsChannelMessage: Missing role permissions on the request. API required one of 'Teamwork.Migrate.All, ChannelMessage.ReadWrite.All'. Roles on the request 'User.ReadWrite.All, Group.ReadWrite.All'
```

I think MSFT might have removed this on purpose. Please advise ?

**Comment by get-itips** [comment]
Hello @TheMasterPrawn Rob,
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @TheMasterPrawn Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
