### ISSUE TITLE
Teams 2.4.0 ApplicationId and CertificateThumbprint not available

### ISSUE THREAD

**Issue by SnappyFPV** [MicrosoftDocs/office-docs-powershell#7967]
Want to test 2.4.0 preview to check if the cs command issues gone with CBA https://github.com/MicrosoftDocs/office-docs-powershell/issues/6737 but it looks like the parameters for certificate based authentication is completly gone?!? 

```
Connect-MicrosoftTeams -ApplicationId $AppID -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId
Connect-MicrosoftTeams : A parameter cannot be found that matches parameter name 'ApplicationId'.
```

How should i run unattended teams ps in a mfa enviroment? when also application authentication isn't available?

Thanks

**Comment by get-itips** [comment]
Hello @SnappyFPV how are you?
Here, we are limited to documentation changes and improvements, said that the scenario you described has already been reported and already passed this information on to the team behind the module.
Hope this information helps you,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @SnappyFPV Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
