### ISSUE TITLE
HTTP 401 on Exchange Online cmdlets when running in app-only mode

### ISSUE THREAD

**Issue by niharaobsec** [MicrosoftDocs/office-docs-powershell#7970]
Receiving a 401 error on some EXO cmdlets when running in app-only mode.
The app that was authorized into the tenant consented to the Exchange.ManageAsApp scope and the service principal has been assigned to the Exchange Admin role. Are there additional scopes that are required? 

```
Install-Module -Name ExchangeOnlineManagement -RequiredVersion 2.0.4 -Force
Connect-ExchangeOnline -CertificateFilePath '<path_to_cert>' -CertificatePassword (ConvertTo-SecureString -String '<password>' -AsPlainText -Force) -AppID <app_id> -Organization 'tenant.onmicrosoft.com'


Get-EXOMailbox -ResultSize unlimited
Get-EXOMailbox: Error while querying REST service. HttpStatusCode=401 ErrorMessage={"error":{"code":"Unauthorized","message":"User is not allowed to call Get-Mailbox","innererror":{"message":"User is not allowed to call Get-Mailbox","type":"Microsoft.Exchange.Admin.OData.Core.ODataServiceException"}}}

Get-Mailbox -ResultSize Unlimited
Get-Mailbox: The term 'Get-Mailbox' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by niharaobsec** [comment]
This appears to have been because the role that was assigned to the Service Principal was Security Administrator, which is a supported role per the official documentation https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#step-5-assign-azure-ad-roles-to-the-application but errors with the following cmdlets:
`Get-RemoteDomain, Get-Mailbox, Get-OrganizationConfig, Get-OwaMailboxPolicy, Get-AdminAuditLogConfig, Get-SharingPolicy`

Is the documentation incorrect?

![image](https://user-images.githubusercontent.com/48263193/123142016-de0d2980-d40d-11eb-9457-c53459d1cb5e.png)

**Comment by dariomws** [comment]
Hi @niharaobsec, thank you for your feedback.

Security Administrator is supported, but it doesn't have the roles to run the cmdlets you need. For more information, see the following similar issue:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/6992

Please let me know if you need more help.

**Comment by niharaobsec** [comment]
@dariomws Thanks for your response!
Would be nice if the documentation called that out, especially as the questions appears to have come up more than once on here.

**Comment by niharaobsec** [comment]
@dariomws Are there a different set of roles that apply to these cmdlets:

```
Get-SafeLinksPolicy
Get-AtpPolicyForO365
Get-SafeAttachmentPolicy
Get-TransportRule

```

**Comment by chrisda** [comment]
@niharaobsec, those cmdlets are 100% Exchange Online PowerShell related. Global administrator and Exchange administrator will definitely give you access to those cmdlets.

**Comment by chrisda** [comment]
@niharaobsec, I updated the topic with the following note:

>  The Global administrator and Exchange administrator roles provide the necessary permissions for any Exchange-related tasks, including recipient management and protection features (anti-spam, anti-malware, etc). The Security administrator role doesn't not have the necessary permissions for these same Exchange-related tasks.

Thanks for the feedback.

Closing

P.S. Feel free to reopen this Issue as necessary
