### ISSUE TITLE
2 new parameters have been added in 2019

### ISSUE THREAD

**Issue by sritodi** [MicrosoftDocs/office-docs-powershell#7973]
2 new parameters have been added in 2019

ExcludeMidDialogRequests
ExcludeTypingNotifications

**Comment by get-itips** [comment]
Hello @sritodi can you please detail what cmdlet you are referring to? Thanks

**Comment by sritodi** [comment]
https://docs.microsoft.com/en-us/powershell/module/skype/new-csdiagnosticsfilter?view=skype-ps

> Hello @sritodi can you please detail what cmdlet you are referring to? Thanks
