### ISSUE TITLE
Document return value

### ISSUE THREAD

**Issue by FoundryFounder** [MicrosoftDocs/office-docs-powershell#7976]
For me, New-AuthenticationPolicy returns the inserted object, which is invaluable for knowing results of the cmdlet as well as for subsequent commands.  It would be helpful to have that documented, avoiding experimentation to figure it out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 908e737b-0193-5dff-2845-17e8e02e54b3
* Version Independent ID: 0ea67145-62bc-67fb-f7ba-dbd0b384ebe6
* Content: [New-AuthenticationPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-authenticationpolicy?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/New-AuthenticationPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-AuthenticationPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @FoundryFounder, thank you for your feedback.

Typically, we don't spend time documenting output properties for cmdlets because a) they change frequently and without warning, b) they often contain unmodifiable or datacenter-centric values (in other words, those properties don't correspond to parameters in the New-* or Set-* cmdlets), and c) that's a level of customization we have historically not wanted to do. The only exception to this rule is reporting cmdlets; we document those as thoroughly as possible.

**Comment by FoundryFounder** [comment]
Dario:  Thanks for your response.  
Regarding not documenting output properties:  I have mixed feelings about the policy, but OK.  Certainly can be a bit of work to document everything.  Would it be better therefore if the "Outputs" heading was simply removed from the page?  Therefore, removing the implication that there is information missing from the page.  
Thanks!
J

**Comment by dariomws** [comment]
@FoundryFounder thank you for understanding. Something that I can add is that you can see some cmdlets with the following sentence in the output section:
"To see the return types, which are also known as output types, that this cmdlet accepts, see [Cmdlet Input and Output Types](https://go.microsoft.com/fwlink/p/?linkId=616387). If the Output Type field is blank, the cmdlet doesn't return data."
It's doing programmatically and automatically using a utility that we use to dump cmdlets to topics. So what you see now is what this tool returns for this cmdlet.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @FoundryFounder Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
