### ISSUE TITLE
Parameter correction

### ISSUE THREAD

**Issue by SuperTekBoy** [MicrosoftDocs/office-docs-powershell#7979]
This first line is inaccurate. This works in Exchange Online as well.

-IncludeHidden
This parameter works only in on-premises Exchange.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89048c92-34d5-d96e-c982-515f319a304d
* Version Independent ID: 47a23a34-3ee2-1874-3ce7-03e3219e2e16
* Content: [Get-InboxRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-inboxrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-InboxRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-InboxRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SuperTekBoy, confirmed. It can be tricky with parameters as sometimes they're _available_, but they aren't supposed to be or they don't work properly. Not the case here, but it happens. And when it does, you'll get a statement like that in the description (the Applicable: value for the parameter only considers availability and not functionality for technical reasons). Typically, I'll use language like:

> This parameter is available or functional only in ...

The fact that this parameter description doesn't use that language is a bit of a red flag.

I updated the parameter description.

Thanks for the feedback.

Closing
