### ISSUE TITLE
Provice the ability to use explicit remoting with v2 module

### ISSUE THREAD

**Issue by LuisEmilioR** [MicrosoftDocs/office-docs-powershell#7981]
Provide the ability to create powershell sessions for legacy commands without automatically importing it. This will give the option to use the newly created session on invoke-command for explicit remoting.
As managing multiple Exchange environments we have processes that need to create multiple simultaneous sessions to different environments and use explicit remoting to consume specific sessions as needed.
v2 module now creates and automatically imports the session which makes it impossible to integrate with current scripts.

**Comment by chrisda** [comment]
@LuisEmilioR, all we can do here is fix/update documentation.

I suggest that you either open a support request or send a message to this email address asking for the features that you want: 

exocmdletpreview[at]service[dot]microsoft[dot]com

Email address obfuscated to help reduce spam.

Thanks for the feedback.

Closing
