### ISSUE TITLE
Please add 'hint' 

### ISSUE THREAD

**Issue by VivekRYagnik** [MicrosoftDocs/office-docs-powershell#7982]
Hi Team,

I was using 'app only' authentication for unattended scripts with EXO V2 module - and encountered strange problem around connecting with Exchange Online - the issue was I was able to login into Exchange from my desktop machine but wasn't able to do the same from a machine deployed on cloud. I created Microsoft support ticket for the same ([Case #:25591918]) and they took more than a month to identify that '-organization' parameter should ideally be sub-domain of 'onmicrosoft.com'. This is already documented https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps as 'Tip' - but this page is hidden into the ocean of documents - so it would help others if we can add the same 'Tip' above -organization' parameter that's documented on https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps

Thanks.

Vivek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13d88f18-3cc8-5f18-8d61-ff7f5fa4e314
* Version Independent ID: 60f9a029-69f3-e65c-6816-fbd414790ce3
* Content: [Connect-ExchangeOnline (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Connect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@VivekRYagnik OK. Done.

Thanks for the feedback.

Closing
