### ISSUE TITLE
Get-CsTenantNetworksite -Filter does not expect Odata syntax?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7989]
Hello Team,

I am trying to create a script (`Find-TeamsEmergencyCallRoute`) that queries a Site or a Subnet, finds the ECRP and follows through with resolution until the Gateway (I have the same for the normal call route via OVP: `Find-TeamsUserVoiceRoute` already). However, I am struggling with Step 1: Lookup for the Site by Name:

I am working off of the (working) [CmdLets ](https://aka.ms/teams-dec-deck)to create these artifacts, but I cannot re-query them...

## Issue 1 - RESOLVED
Listed here only for visibility. Was "Query by Identity fails with spaces in the Name"
> Resolved - had trailing space in the Name - opened #7990 instead.

This affects Identity, NetworkSiteId and Description parameter. 
```powershell
❯ $Site = "Los Angeles"
❯ $Site
Los Angeles
❯ Get-CsTenantNetworksite -Identity $Site
Cannot find "TenantNetworkSite" "Los Angeles" because it does not exist.
    + CategoryInfo          : ResourceUnavailable: (Los Angeles:String) [Get-CsTenantNetworkSite], KeyNotFoundExceptio
   n
    + FullyQualifiedErrorId : MissingItem,Microsoft.Rtc.Management.Internal.GetTenantNetworkSiteCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com
❯ Get-CsTenantNetworksite -Identity "$Site"
Cannot find "TenantNetworkSite" "Los Angeles" because it does not exist.
    + CategoryInfo          : ResourceUnavailable: (Los Angeles:String) [Get-CsTenantNetworkSite], KeyNotFoundExceptio
   n
    + FullyQualifiedErrorId : MissingItem,Microsoft.Rtc.Management.Internal.GetTenantNetworkSiteCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com
```
Query with Identity doesn't work and it doesn't matter whether I use quotation marks or not.

```powershell
❯ Get-CsTenantNetworksite -Identity "Site1"


Identity                   : Site1
RunspaceId                 : 828f41bc-8860-431d-9e7b-f4335b4a6609
Subnets                    :
Postalcodes                :
NetworkSiteID              : Site1
Description                : Network Site 1
NetworkRegionID            : EMEA
LocationPolicy             :
EnableLocationBasedRouting : False
SiteAddress                :
EmergencyCallRoutingPolicy : ECRP1
EmergencyCallingPolicy     : ECP1
NetworkRoamingPolicy       :
```
However, querying Sites without spaces in the name works fine. I think, either the Identity Parameter is not correctly implemented, or `New-CsTenantNetworkSite` allows spaces in the Identity when it shouldn't.
Can you confirm?

## Issue 2 - Query by Filter does not return a result
Query with * in the name returns something, though can afterwards not be filtered further with Where-Object
```powershell
❯ $Site = "Los Angeles"
❯ $Site
Los Angeles
❯ Get-CsTenantNetworksite -Filter "Identity eq '$Site'"
❯ 
❯ Get-CsTenantNetworksite -Filter "Los Angeles"
❯ 
❯ Get-CsTenantNetworksite -Filter "Los Angeles*"


Identity                   : Los Angeles
RunspaceId                 : 828f41bc-8860-431d-9e7b-f4335b4a6609
Subnets                    :
Postalcodes                :
NetworkSiteID              : Los Angeles
Description                : Los Angeles
NetworkRegionID            : US
LocationPolicy             :
EnableLocationBasedRouting : False
SiteAddress                :
EmergencyCallRoutingPolicy :
EmergencyCallingPolicy     :
NetworkRoamingPolicy       :

Identity                   : Los Angeles del Rio
RunspaceId                 : 828f41bc-8860-431d-9e7b-f4335b4a6609
Subnets                    :
Postalcodes                :
NetworkSiteID              : Los Angeles del Rio
Description                : Network Site 2
NetworkRegionID            : US
LocationPolicy             :
EnableLocationBasedRouting : False
SiteAddress                :
EmergencyCallRoutingPolicy :
EmergencyCallingPolicy     :
NetworkRoamingPolicy       :
```
Filter ONLY finds the Site if I place it with a *, however, an exact match by name is not able to be found. I have tried numerous filter statements that adhere to the ODATA syntax to get to it, but to no avail. Normally I would just filter to get a handful results, then pipe to `Where-Object` to narrow it down to one. This though also fails to work! I think there is something wrong here...

So for now, I can query Network Sites only if they do not have a space in the name.

I submit this for validation, as the coffee may not yet have kicked in and my brain is not fully up to speed yet...
I shall continue to tackle the other requirement I have put myself to: Querying by Subnet.

In terms of Documentation issues, could we get some filter examples here please? 😄 
If indeed I am using these correctly and there _is_ an issue with the Commands, could you forward this to the dev team please?

Thank you,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1570dd32-8edb-178a-3519-d3a37e10b69b
* Version Independent ID: dd1fc7a5-32df-5f97-c750-a2dc0dc7a6f6
* Content: [Get-CsTenantNetworkSite (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-cstenantnetworksite?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsTenantNetworkSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTenantNetworkSite.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by DEberhardt** [comment]
ok. I think I should have waited for proper coffee propagation^^
I seem to have created the Site with a trailing space!

```poweshell
❯ Get-CsTenantNetworksite -Identity "Los Angeles "

Identity                   : Los Angeles
RunspaceId                 : c7d2b651-bd8a-4e37-a639-c8277d87e995
Subnets                    :
Postalcodes                :
NetworkSiteID              : Los Angeles
Description                : Los Angeles
NetworkRegionID            : US
LocationPolicy             :
EnableLocationBasedRouting : False
SiteAddress                :
EmergencyCallRoutingPolicy :
EmergencyCallingPolicy     :
NetworkRoamingPolicy       :

```

Issue 1 is not an issue - Issue 2 however still stands

**Comment by get-itips** [comment]
Hello @DEberhardt David, how are you?

About "Issue 2"

When you say ODATA you mean _OPATH syntax_? if it is not mentioned, like for example in [Exchange's Get-Mailbox](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailbox?view=exchange-ps), it is not implemented that way.

> Filter ONLY finds the Site if I place it with a *

I could not reproduce that:

```powershell
  Get-CsTenantNetworksite -Filter "Los Angeles"


Identity                   : Los Angeles
RunspaceId                 : 930f990c-4ab6-41ac-8695-ccf3fb3b3ca9
Subnets                    :
Postalcodes                :
NetworkSiteID              : Los Angeles
Description                : Los Angeles
NetworkRegionID            :
LocationPolicy             :
EnableLocationBasedRouting : False
SiteAddress                :
EmergencyCallRoutingPolicy :
EmergencyCallingPolicy     :
NetworkRoamingPolicy       :

```

**Comment by DEberhardt** [comment]
Hello, all well here in the UK :)

I seem to have filed this away as ODATA - like the Examples 4 and 5 as in:

[Get-AzureAdUser](https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureaduser?view=azureadps-2.0) -Filter "UserPrincipalName eq 'John@domain.com'"

If it goes by another name, I am missing bits of information 😄 

I will try again - this time without the trailing spaces...

**Comment by DEberhardt** [comment]
Tried `Get-CsTenantNetworkSite` again just now:
```powershell
 David  C:\                                                                                                18:52:42
❯ Get-CsTenantNetworkSite -Filter "Los*" | Select Identity

Identity
--------
Los Angeles
Los Angeles del Rio
Los Libros


 David  C:\                                                                                                18:52:57
❯ Get-CsTenantNetworkSite -Filter "Los" | Select Identity
 David  C:\                                                                                                18:53:04
❯ Get-CsTenantNetworkSite -Filter "Los Libros"


Identity                   : Los Libros
RunspaceId                 : bb206760-e0cc-4aa3-a457-ddaf4ffbd604
Subnets                    :
Postalcodes                :
NetworkSiteID              : Los Libros
Description                : Network Site 3
NetworkRegionID            : US
LocationPolicy             :
EnableLocationBasedRouting : False
SiteAddress                :
EmergencyCallRoutingPolicy :
EmergencyCallingPolicy     :
NetworkRoamingPolicy       :



 David  C:\                                                                                                18:57:06
❯
```

It looks as if `-Filter` doesn't filter with a string alone... only with a '*' (it does return something if it finds an exact match however...)

As there is no example for the Filter, I have to guess what works... what is the default for the -Filter parameter?

**Comment by get-itips** [comment]
@DEberhardt David, can you kindly detail me the version of Teams Ps are you using for those tests? Thank you

**Comment by DEberhardt** [comment]
I should be on v2.3.1 - never updated since the TimeZone issue was fixed

```powershell

PowerShell Module Paths
C:\Users\David\Documents\WindowsPowerShell\Modules
C:\Program Files\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
c:\Users\David\.vscode\extensions\ms-vscode.powershell-preview-2021.7.0\modules

PowerShell Version Table

Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PowerShell Host

Name             : Visual Studio Code Host
Version          : 2021.7.0
InstanceId       : 953ef41e-c755-4e72-ab42-37f396d8ef75
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-GB
CurrentUICulture : en-GB
PrivateData      : Microsoft.PowerShell.EditorServices.Services.PowerShellContext.EditorServicesPSHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

Installed NET Frameworks



PSChildName                      Version        Release
-----------                      -------        -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.04084      528372
Full                             4.8.04084      528372
Client                           4.0.0.0



Relevant Modules (installed)

ModuleType Version   Name
---------- -------   ----
    Binary 2.0.2.135 AzureAD
    Binary 2.0.2.136 AzureADPreview
    Binary 2.3.1     MicrosoftTeams



Relevant Modules (loaded)

ModuleType Version   Name
---------- -------   ----
    Binary 2.0.2.135 AzureAd
    Binary 2.3.1     MicrosoftTeams
    Script 21.7.11   TeamsFunctions

```
