### ISSUE TITLE
New-CsTenantNetworkSite allows Identity to have trailing spaces

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7990]
An Entity created with a String for Identity allows trailing spaces to be configured.
This may lead to issues with querying Sites later with Get-CsTenantNetworkSite (#7989)

Should a note be added to `-Identity` to state this or is this something that should be trimmed by this CmdLet upon entry?
One for the Devs?

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6244e0e-8738-3a25-d829-032164a880df
* Version Independent ID: 749077d4-5b5e-9c37-4e31-100627b3fac9
* Content: [New-CsTenantNetworkSite (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cstenantnetworksite?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTenantNetworkSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTenantNetworkSite.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DEberhardt David,
I could verify that it accepts trailing spaces as you mention. However, as I verified in https://github.com/MicrosoftDocs/office-docs-powershell/issues/7989 I could successfully filter also with the trailing spaces, and without using *.
Please let me know if I understood you well.
Thanks

**Comment by DEberhardt** [comment]
Yes, it does work with trailing spaces, both creation and query.
I do think this should be trimmed as it is very prone to issues this way - white-space seems to be my windmill (especially when tired! 😉 )

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @DEberhardt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
