### ISSUE TITLE
New-MailboxSearch -Name "Hold-tailspintoys" -SourceMailboxes bcollins -SearchQuery '"Patent" AND "Project tailspintoys"' 

### ISSUE THREAD

**Issue by s4vishwa** [MicrosoftDocs/office-docs-powershell#7993]
-SearchQuery cmd not valid when running new-mailboxsearch

**Comment by chrisda** [comment]
@s4vishwa, it sounds like this the same problem as #7994, where the account you were using was not part of the discovery management group.

If this is wrong, feel free to reopen this issue.

Thanks for the feedback.

Closing
