### ISSUE TITLE
Not available

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/office-docs-powershell#7997]
This cmdlet is not available in Exchange Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5afe8f19-b64e-354f-b363-e040db2a1e8c
* Version Independent ID: 0d5fde8a-2882-c935-1af4-e9c31c216fd4
* Content: [Get-GlobalAddressList (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-globaladdresslist?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-GlobalAddressList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-GlobalAddressList.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@danmyhre, are you sure? It's available to me in my tenant. From the topic:

> In Exchange Online, this cmdlet is available only in the Address Lists role, and by default, the role isn't assigned to any role groups. To use this cmdlet, you need to add the Address Lists role to a role group (for example, to the Organization Management role group).

Try running the following commands and see what you get:

```powershell
$Perms = Get-ManagementRole -Cmdlet Get-GlobalAddressList
$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}
```

**Comment by danmyhre** [comment]
good call, sorry, the tenant I was connected to didn't have this modification yet. I should have verified that. Tested on a different one and it is there.  Thanks!
