### ISSUE TITLE
Since when does WinRM work on macOS and is a requirement for this module?  More over the module only shows support for DESK, not CORE.

### ISSUE THREAD

**Issue by rjbokleman** [MicrosoftDocs/office-docs-powershell#8002]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by rjbokleman** [comment]
The installation instructions say that WinRM is required.  It also says that this works on macOS.  Also the module only shows DESK being supported despite the article and doesn't show support for CORE on macOS.

**Comment by chrisda** [comment]
@rjbokleman, I'll take any suggested updates that you want to provide for MacOS installation instructions and requirements.

**Comment by yogkumgit** [comment]
@chrisda
