### ISSUE TITLE
Set-CsCallQueue  -ChannelUserObjectId param documentation improvement 

### ISSUE THREAD

**Issue by dappleby300** [MicrosoftDocs/office-docs-powershell#8005]
Hi,

Can the documentation regarding the Set-CsCallQueue  -ChannelUserObjectId  parameter please be improved. 
Currently it just states: "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)." which is not very helpful.

Ideally it would be good if the description answered the following questions;

1. An example of how to obtain said GUID. Get-CsOnlineUser  (ObjectID?)?
2. What permissions/context does that UserObjectID need to have?

For example is it the user object ID of the team owner? member? which one if multiple? does it matter which one is used? and does it tie the user to the channel/call queue somehow (in other words if that user is deleted will the call queue link be broken?)

It seems to matter when using a private channel so how would someone determine the best possible UserObjectID to use? 

The Teams Admin centre doesn't require that so it must be being obtained somehow.

**Comment by get-itips** [comment]
Hello @dappleby300 I am looking into this.

**Comment by yogkumgit** [comment]
@get-itips

**Comment by Edgar81** [comment]
Any news on this?

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and updating the documentation with PR. @dappleby300 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
