### ISSUE TITLE
Add-PnPNavigationNode - Provide an example of how to create a Label

### ISSUE THREAD

**Issue by mcpsmith** [MicrosoftDocs/office-docs-powershell#8006]
Please add documentation on how to create a Label in the navigation node (vs a Link). 

I had to figure it out for myself. Use -url "http://linkless.header/" to create a Label instead of a Link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c007e403-dce1-34d8-b422-11ab4630305c
* Version Independent ID: eaf106fc-2d67-d98d-b276-e17045277b55
* Content: [Add-PnPNavigationNode (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpnavigationnode?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPNavigationNode.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPNavigationNode.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by mcpsmith** [comment]
Thanks - I've added it to the repo you linked to.
