### ISSUE TITLE
Typo in registry edit instructions

### ISSUE THREAD

**Issue by Rick-415** [MicrosoftDocs/office-docs-powershell#8007]
The following instruction to permanently enable strong cryptography in the Microsoft .NET Framework version 4.x or later (x64)  has a typo:
_

> Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Type DWord -Value '1'

There should be a backslash between "Microsoft" and ".NetFramework

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-and-maintain-the-exo-v2-module)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Rick-415, OK. Fixed.

For future reference, you too can make changes like this yourself. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
