### ISSUE TITLE
Saving Teams Channel Chats before removing the Team

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/office-docs-powershell#8013]
I was able to drill down to the Get-PnPTeamsChannelMessage and found out I can get the content.
I found out there are replies associated with each message but there is no ".Replies" in the intellisense. is this not done yet? or did I miss something?

Also do I really need to save the posts before removing the group? are they saved somewhere else I can get to if I am asked to get out of an archive.

**Comment by get-itips** [comment]
Hello @Ofer-Gal 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Ofer-Gal Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
