### ISSUE TITLE
Missing description for -IncludeOrgContent

### ISSUE THREAD

**Issue by dickscheel** [MicrosoftDocs/office-docs-powershell#8016]
The section of this page that documents the -IncludeOrgContent parameter has what appears to be a placeholder for the Description part. Currently, it just says "{{ Fill IncludeOrgContent Description }}".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f7f0a23-5b87-02f2-5bce-eddc3413f7f4
* Version Independent ID: 6694e76a-b1e0-9cc6-08ab-beb0cf388e75
* Content: [New-ComplianceSearch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ComplianceSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dickscheel, known issue. See the discussion in #7429 . Do you use this parameter? Does it work as you expect?

**Comment by dickscheel** [comment]
Thanks, Cris. I don't use this parameter. I was just browsing around Microsoft docs to see what kind of tools exist for Exchange Server admins, and I happened to run across this one.

**Comment by yogkumgit** [comment]
@dickscheel as suggested, it is a known issue. Closing. Thanks
