### ISSUE TITLE
Add-TeamChannelUser -Role Owner doesn't work

### ISSUE THREAD

**Issue by Jedi2mk** [MicrosoftDocs/office-docs-powershell#8020]
Hello, there, Add-TeamChannelUser -Role Owner doesn't work. What's the correct command line, then?
```
Add-TeamChannelUser -GroupId **groupid** -DisplayName "Q and A" -User user@ubisoft.com -Role Owner
Add-TeamChannelUser : Failed to find the user on the channel roster. Add-TeamChannelUser
At line:1 char:1
+ Add-TeamChannelUser -GroupId **groupid** -Di ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamChannelUser], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.TeamsCmdlets.PowerShell.Custom.AddTeamChannelUser
```
user@ubisoft.com is listed with `Get-TeamChannelUser -GroupId **groupid** -DisplayName "Q and A".`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd91d571-ca88-5766-2666-d6a4d34cdbed
* Version Independent ID: 2481b258-b593-e323-90f0-e9ca6e7797bf
* Content: [Add-TeamChannelUser (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @Jedi2mk how are you?
I checked to see if we needed to adjust the article, however, I could reproduce it, the cmdlet is still part of the preview module (not the General Availability), I will try to pass this information on.
Thanks for your feedback,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Jedi2mk Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
