### ISSUE TITLE
Get-User missing cmdlet

### ISSUE THREAD

**Issue by RyanSmith-00** [MicrosoftDocs/office-docs-powershell#8026]
Hi, after installing "Install-Module -Name ExchangeOnlineManagement -Force" the cmdlet Get-User is no longer available. How can we pull back the information needed with out Get-User?

```powershell
Get-Mailbox -ResultSize Unlimited | ?{$_.HiddenFromAddressListsEnabled -eq $false} | Get-User | Select DisplayName,FirstName,LastName,Phone,MobilePhone,WindowsEmailAddress,Company,Title 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c916371e-aef0-f91e-e04d-16110358a306
* Version Independent ID: bd073f8e-ba80-25ed-0fe4-286641e9f043
* Content: [Exchange Server PowerShell (Exchange Management Shell)](https://docs.microsoft.com/en-us/powershell/exchange/exchange-management-shell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-management-shell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-management-shell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@RyanSmith-00, a couple of different points/questions:

- The EXO V2 module is for Exchange Online, not Exchange Server. The EXO V2 module just connects you to Exchange Online PowerShell. After you install the module (which it sounds like you did), you connect to your tenant using Connect-ExchangeOnline as described in [Connect to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell).

- After you connect, role based access control (RBAC) takes over, but the **Get-User** cmdlet should be available to you. As described in this topic: [Find the permissions required to run any Exchange cmdlet](https://docs.microsoft.com/en-us/powershell/exchange/find-exchange-cmdlet-permissions), copy the following command and run it as-is AFTER you connect to ExO PowerShell:

  ```powershell
  $Perms = Get-ManagementRole -Cmdlet Get-User; $Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}
  ```
  I get tons of results (typical for most Get- cmdlets: Organization Management, View-Only Organization Management, Security Reader, Recipient Management, etc.).
Comments?

**Comment by chrisda** [comment]
Closing due to lack of response.

Thanks for the feedback
