### ISSUE TITLE
Remove-CalendarEvents should also be able to decline meetings to which the user was invited

### ISSUE THREAD

**Issue by adagioajanes** [MicrosoftDocs/office-docs-powershell#8029]
We are retiring a conference room, but we still have many meetings scheduled for the room. I wanted to 'Remove-CalendarEvents' so the room would send declines to everyone who hasn't changed their conference room.

Remove-CalendarEvents should have a flag to also decline all meetings to which the user was invited.

**Comment by chrisda** [comment]
@adagioajanes, that sounds more like a feature request. Your best bet is to open a support case.

[Set-CalendarProcessing](https://docs.microsoft.com/powershell/module/exchange/set-calendarprocessing) can prevent people from reserving the room, but I don't think the change affects existing meetings. For example:

```powershell
Set-CalendarProcessing -Identity "Room A" -AllBookInPolicy $false -AllRequestInPolicy $false
```

**Comment by adagioajanes** [comment]
@chrisda, I think then there may be an issue with the feedback links in the documentation. When viewing the page, at the bottom, there is an option for submitting and viewing feedback for 'This product' and 'This page'. Clicking 'This product' brought me here.
Because Microsoft announced they are changing how product feedback is gathered, I figured, since it is linked this way, that this is now where we are supposed to post feedback about the product, not just the documentation.
It is extremely NOT OBVIOUS that a support case is the correct channel for this, when I am linked to post here. If that is the case, then I will submit a new issue stating all of this. ;)
