### ISSUE TITLE
-DelegatedOrganization flag has never worked, it should be removed from the Docs

### ISSUE THREAD

**Issue by david-tap** [MicrosoftDocs/office-docs-powershell#8030]
Connect-IPPSSession has never worked with the "-DelegatedOrganization" flag, presumably since the Security and Compliance team felt delegated permissions are not secure enough. Regardless of the "why", since I haven't seen any recent communication from Microsoft indicating that Security and Compliance will support delegated auth, the flag is misleading and should be removed from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 945ab2ea-22ae-814f-8898-fe84b7f29870
* Version Independent ID: 5383d152-988d-b1ee-4957-db5fb6213754
* Content: [Connect-IPPSSession (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-ippssession?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-IPPSSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Connect-IPPSSession.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@david-tap, I changed the description to "reserved for internal Microsoft use."

Thanks for the feedback.

Closing
