### ISSUE TITLE
problem with new-team command

### ISSUE THREAD

**Issue by ghrabawy** [MicrosoftDocs/office-docs-powershell#8031]
Hello
i try to create a new team with the following command:
$disp_name = "Hello World1"
$Tgroup = New-Team -DisplayName $disp_name -Template EDU_Class

and i have this error

New-Team: Error occurred while executing
Code: BadGateway
Message: Failed to execute backend request.
InnerError:
RequestId: 46ed8c17-6ada-45ef-8418-80f3ad1aa3a0
DateTimeStamp: 2021-07-08T08:09:13
HttpStatusCode: BadGateway

what is the problem?
and what is the solution?
thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fff5e98-436e-f79c-e176-767f8de772e5
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @ghrabawy how are you? hope you are doing good.
Here, we are limited to documentation changes, improvements, and fixes.
Anyway, tried to reproduce but couldn't, please be sure to be running the last version of the Teams PowerShell module.
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ghrabawy Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
