### ISSUE TITLE
Incorrectly documented event types for phish/malware for Get-MailTrafficATPReport

### ISSUE THREAD

**Issue by NotAdam** [MicrosoftDocs/office-docs-powershell#8033]
Trying to pull data about zapped emails with Get-MailTrafficATPReport, but passing `-EventType ZAP` or `-EventType "Phish ZAP"` doesn't work and results in the following:

```powershell
Get-MailTrafficATPReport -StartDate 06/01/2021 -EndDate 07/09/2021 -Direction Inbound,Outbound -EventType "ZAP"
Invalid input: ZAP [CustomInternalValidate, GetMailTrafficATPReport.cs:165]
    + CategoryInfo          : InvalidArgument: (:) [Get-MailTrafficATPReport], ValidationException
```

Checking the real time detections report in M365 Defender does show zapped emails for this time period. Running the following to get all the event types returns only a subset of what is documented:

```powershell
Get-MailTrafficATPReport -Direction inbound,outbound -StartDate 06/01/2021 -EndDate 07/09/2021 | select EventType | sort-object -Property EventType -Unique

EventType
---------
Advanced filter
Anti-malware Engine
File detonation
File detonation reputation
General filter
Impersonation brand
Mailbox intelligence impersonation
Message passed
Spoof DMARC
Unknown
URL detonation
URL detonation reputation
URL malicious reputation
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccd6fed8-6da5-310e-9773-fe2ad0b3146f
* Version Independent ID: 02171fa8-5e5c-0ce9-36d0-c057961ba86f
* Content: [Get-MailTrafficATPReport (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailtrafficatpreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailTrafficATPReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MailTrafficATPReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@NotAdam, I found a vast list of possible EventType values in code, and I script-o-matically threw them at the EventType parameter. I updated the topic with any value that didn't return an error.

This list is identical to the list of values that was already documented in  [Get-MailDetailATPReport](https://docs.microsoft.com/en-us/powershell/module/exchange/get-maildetailatpreport). Of course, my testing method can't find unknown values, so there might be some missing. And, I confirmed the value Unknown doesn't work.

I also took the opportunity to script-o-matically test the EventType parameter in the 15 other **Get-\*Report** cmdlets and update the description with the accepted values.

Many of the older cmdlets do use a subset of the values found by `Get-MailFilterListReport -SelectionTarget EventTypes` . But,  newer cmdlets appear to be picking up their values from different sources (often, spaces in the value names).

Thanks for the feedback.

Closing
