### ISSUE TITLE
Access is denied for connection with Certificate.

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/office-docs-powershell#8035]
I followed the instructions in your [docs](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2#step-5-assign-azure-ad-roles-to-the-application) To make my appID a "Exchange Administrator"
and also [Here](https://www.azure365pro.com/rename-office-365-unified-groups/) 

Then Used the statement:

```powershell
`$exchangeConn = Connect-ExchangeOnline -AppId $ClientId -CertificateFilePath $certPath -CertificatePassword  $CertPass -Organization $org -DelegatedOrganization $org`
```

But I keep getting the error in

```powershell
PowerShell\Modules\ExchangeOnlineManagement\2.0.5\netCore\ExchangeOnlineManagement.psm1:475:30 
`Line |
 475 |  … PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Connecting to remote server outlook.office365.com failed with the following error message : Access is denied. For
     | more information, see the about_Remote_Troubleshooting Help topic.`
```

What else should I do to be able to work on 365 Exchange?

**Comment by chrisda** [comment]
@Ofer-Gal per the tip in the introduction in the topic:

> App-only authentication does not support delegation. Unattended scripting in delegation scenarios is supported with the Secure App Model. For more information, go [here](https://docs.microsoft.com/powershell/partnercenter/multi-factor-auth#exchange).

![image](https://user-images.githubusercontent.com/33166947/125364167-e11d7a80-e326-11eb-8d99-24c8871714f9.png)

**Comment by Ofer-Gal** [comment]
So have -CertificateFilePath and -CertificatePassword  options if it needs to be done another way?

**Comment by chrisda** [comment]
It's delegated access that doesn't work with certificate-based authentication. The various methods to identify the certificate work great, as long as the account is in the tenant that you're trying to manage. And, we've determined that you must use an .onmicrosoft.com account in the connect commands. The call-out for this has increased in prominence over the last several months as more people have encountered issues:

> In the Connect-ExchangeOnline commands, be sure to use an .onmicrosoft.com domain in the Organization parameter value. Otherwise, you might encounter cryptic permission issues when you run commands in the app context.

**Comment by Ofer-Gal** [comment]
In my script I mostly use the PnP.Powershell. Any way I can use the token I get from Connect-PnPOnline to connect to ExchangeOnlineManagement?
All I need is to rename groups. 
It would be great if EVERYTHING was possible with MS graph (Like promised) :-)

**Comment by chrisda** [comment]
I don't think so. Your best bet is to open a support case and present your scenario. Report back here if there's anything we can clarify in the documentation.
