### ISSUE TITLE
Example 4 :  description is incorrect\misleading.  It will change Global OVRP. 

### ISSUE THREAD

**Issue by kch2001** [MicrosoftDocs/office-docs-powershell#8037]
"Example 4 assigns the per-user online voice routing policy RedmondOnlineVoiceRoutingPolicy to all the users in the tenant, except any that have an explicit policy assignment"

The above is misleading/incorrect statement.  
Get-CsOnlineUser | Grant-CsOnlineVoiceRoutingPolicy -PolicyName "RedmondOnlineVoiceRoutingPolicy" 
This doesn't assign the per-user online voice routing policy(OVRP) to "RedmondOnlineVoiceRoutingPolicy"  This changes Global OVRP to RedmondOnlineVoiceRoutingPolicy. Global OVRP  is used if a user doesn't have OVRP set.  

If above cmdlet is ran, the users without the per-user online voice routing policy will still not have the per-user OVRP set.  However, the calls will be routed using Global OVRP.  We have tested in our tenant. 

I saw another person asking whether newly created person after the above cmdlet is run will be effected or not.  Since it is changing Global OVRP, newly created person will be effected too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58aa424-e87c-e4cb-d6a3-49a0d842f831
* Version Independent ID: 8d1e09fa-7896-56e8-c294-8cac6c35d8d3
* Content: [Grant-CsOnlineVoiceRoutingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @kch2001 how are you? Hope you are doing good 👍 

In your description, you mentioned example 4, however, you included the cmdlet example from Example 3. The cmdlet in example 4 is

`Grant-CsOnlineVoiceRoutingPolicy -PolicyName "RedmondOnlineVoiceRoutingPolicy" -Global`

Please correct me if I misunderstood you in any way,

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @kch2001 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by kch2001** [comment]
> Hello @kch2001 how are you? Hope you are doing good 👍
> 
> In your description, you mentioned example 4, however, you included the cmdlet example from Example 3. The cmdlet in example 4 is
> 
> `Grant-CsOnlineVoiceRoutingPolicy -PolicyName "RedmondOnlineVoiceRoutingPolicy" -Global`
> 
> Please correct me if I misunderstood you in any way,
> 
> Thank you

Sorry, I just saw your message today.  I forgot that I submitted this. 

Typo in my original message:  I was talking about  "Grant-CsOnlineVoiceRoutingPolicy -PolicyName "RedmondOnlineVoiceRoutingPolicy" -Global" -not example 3.    **This changes Global OVRP.**  This doesn't assign all users in the tenant to this OVRP without explicit policy assignment.  The difference will be any future users without explicit policy assignment will be effected.

**Comment by yogkumgit** [comment]
@get-itips Please comment.

**Comment by get-itips** [comment]
@kch2001 
Thanks for returning and clarifying, will propose to update the description.
