### ISSUE TITLE
Parameter -IgnoreLegalHold 

### ISSUE THREAD

**Issue by GJUNIOR74** [MicrosoftDocs/office-docs-powershell#8038]
-ignorelegalhold parameter doesn't exist on Exchange Online cmdlet, article must be reviewed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc998569-646c-cd20-c3cd-b5d07e6f62ee
* Version Independent ID: b7d7d129-9092-8e7d-5bc1-e49e24b54603
* Content: [Remove-MailUser (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-mailuser?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-MailUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-MailUser.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@GJUNIOR74, the description of the parameter starts with:

> This parameter is available only in on-premises Exchange.

And the `Applicable:` property in the YAML section says:

> Applicable: Exchange Server 2010, Exchange Server 2013, Exchange Server 2016, Exchange Server 2019

So, there's nothing to update.

Comments?

**Comment by chrisda** [comment]
Closing due to lack of response.

Thanks for the feedback.
