### ISSUE TITLE
Remove-TeamChannelUser - Failed to find the user on the channel roster

### ISSUE THREAD

**Issue by rwkt** [MicrosoftDocs/office-docs-powershell#8041]
The cmd `Remove-TeamChannelUser` returns the following error even though the user is a member of the **private** channel.

```
Remove-TeamChannelUser : Failed to find the user on the channel roster. Remove-TeamChannelUser
At line:1 char:1
+ Remove-TeamChannelUser -GroupId 0dea739f-3ab2-4f05-858f-c5de33e2ddb0  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-TeamChannelUser], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.TeamsCmdlets.PowerShell.Custom.RemoveTeamChannelUser
```
Version details
```
PS C:\Windows\system32> Get-InstalledModule MicrosoftTeams
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.4.0-preview        MicrosoftTeams                      PSGallery            Microsoft Teams cmdlets module for Windows PowerShell and PowerShell Core....
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87a158a7-c33c-f57c-4556-8a44de42abc9
* Version Independent ID: 383ea288-abe0-28d2-10b8-7683a7eb1541
* Content: [Remove-TeamChannelUser (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/remove-teamchanneluser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Remove-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Remove-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @rwkt how are you?
I checked to see if we needed to adjust the article, however, I could reproduce it, **the cmdlet is still part of the preview module only** (not the General Availability), I will try to pass this information on.
Thanks for your feedback,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @rwkt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
