### ISSUE TITLE
Adding multiple objects with set-retentioncompliancepolicy -addexchangelocation

### ISSUE THREAD

**Issue by jreyes4949** [MicrosoftDocs/office-docs-powershell#8044]
https://docs.microsoft.com/en-us/powershell/module/exchange/set-retentioncompliancepolicy?view=exchange-ps#parameters

I see in the documentation it shows to add multiple users with the following syntax: "Value1","Value2",..."ValueN".

my question is can an array variable or hash table be used instead? if not, is there a limit to the number of items that can be added in a single request or is the limit the same as the Retention policy's inclusion/exclusion limits?

**Comment by chrisda** [comment]
@jreyes4949, the parameter Type value is MultiValuedProperty. This means a lot of clear, specific things in Exchange Online PowerShell, but not so much in Security & Compliance Center PowerShell, other than the fact that you can enter multiple values separated by commas.

To try to answer your specific questions:

- I doubt you can use an array variable or hash table. I'm sure you can use a text file (for example, Users.txt) that contains one user per line and then the following command

  ```powershell
  $x = Get-Content C:\data\Users.txt
  ```

- Limit in single request should be the same as the retention policy's limits.

**Comment by yogkumgit** [comment]
@jreyes4949 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
