### ISSUE TITLE
Set-SafeAttachmentPolicy Enable parameter

### ISSUE THREAD

**Issue by stuartmaxwell** [MicrosoftDocs/office-docs-powershell#8045]
The docs say that the `-Enable` parameter is not used: "This parameter isn't used. To enable or disable a safe attachment policy, use the Enabled parameter on the New-SafeAttachmentRule or Set-SafeAttachmentRule cmdlets."

But I found that unless this parameter was used, the policy showed as being turned off in the UI. When using `-Enable` with the `New-SafeAttachmentRule` or `Set-SafeAttachmentRule` cmdlets, I found that the Policy was still in a disabled state. The fix was to use: `Set-SafeAttachmentPolicy -Identity "Policy name" -Enable $true`

Note that this feedback also applies to the `New-SafeAttachmentPolicy` cmdlet. The `-Enable $true` parameter needs to be used if you want the policy to be enabled without having to enable it afterwards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19fa1e8d-d534-52ee-86a3-47c49028313f
* Version Independent ID: 835eccbb-abe6-a0d0-2457-53a39b5a6057
* Content: [Set-SafeAttachmentPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-safeattachmentpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-SafeAttachmentPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@stuartmaxwell, interesting.

In my tenant, which is nothing special, there is no Enable/Enabled/State/Disable/Disabled parameter on Set-SafeAttachmentRule, nor is there any evidence of that parameter in documentation or code. So, that description must have been a simple copy/paste error (ALL other policy/rule cmdlets behave that way).

But, testing returned weird results:

- I created a new Safe Attachments policy in the M365 Defender portal <https://security.microsoft.com/safeattachmentv2>, and it was (of course) enabled by default. This is the result in the Exchange Online PowerShell:

  ```powershell
    PS C:\> Get-SafeAttachmentPolicy "chrisda test" | FL Enable

  Enable : False

  PS C:\> Get-SafeAttachmentRule "chrisda test" | FL State

  State : Enabled
  ```

  Not the mismatch in values.

- I disabled the policy in the UI. This is the result in the Exchange Online PowerShell:

  ```powershell
  PS C:\> Get-SafeAttachmentPolicy "chrisda test" | FL Enable
  
  Enable : False
  
  PS C:\> Get-SafeAttachmentRule "chrisda test" | FL State
  
  State : Disabled
  ```

- I tried enabling the same policy in PowerShell using the Set-SafeAttachmentPolicy cmdlet while the State value was still Disabled in Get-SafeAttachmentRule. **No effect**; the policy in the UI still appears disabled.

  ```powershell
  PS C:\> Get-SafeAttachmentPolicy "chrisda test" | FL Enable
  
  Enable : True
  
  PS C:\> Get-SafeAttachmentRule "chrisda test" | FL State
  
  State : Disabled
  ```

So it appears that you can only enable/disable an existing Safe Attachments policy (the combination of the policy and rule) in the UI?

**Comment by stuartmaxwell** [comment]
Hi @chrisda - try this:

`get-help set-safeattachmentpolicy`

You can see in the help text that there is definitely an `-Enable` parameter:

```

SYNTAX
    Set-SafeAttachmentPolicy [-Identity] <SafeAttachmentPolicyIdParameter> [-Action 
    <SafeAttachmentAction>] [-ActionOnError <Boolean>] [-AdminDisplayName <String>] 
    [-Confirm] [-Enable <Boolean>] [-Redirect <Boolean>] [-RedirectAddress <SmtpAddress>] 
    [-WhatIf] [<CommonParameters>]
```

The problem is that the docs say that the parameter isn't used, but in my testing you **need** to use it to enable the policy from PowerShell.

**Comment by chrisda** [comment]
@stuartmaxwell, I see what's going on now.

You use the [Enable-SafeAttachmentRule](https://docs.microsoft.com/powershell/module/exchange/enable-safeattachmentrule) and [Disable-SafeAttachmentRule](https://docs.microsoft.com/powershell/module/exchange/disable-safeattachmentrule) cmdlets to enable/disable the policy in the UI (the **complete** policy, which is a combination of the policy and the rule in PowerShell).

That's what changes the State property value on the rule.

I updated the description of the Enable parameter on Set-SafeAttachmentPolicy to say:

> This parameter isn't used. To enable or disable an existing Safe Attachments policy (the combination of the safe attachment policy and safe attachment rule in PowerShell), use the Enable-SafeAttachmentRule or Disable-SafeAttachmentRule cmdlets.

As I showed in my testing, the value of the Enable property on Get-SafeAttachmentPolicy and use of the Enable parameter or Set-SafeAttachmentPolicy is irrelevant when it comes to showing the policy as enabled or disabled in the UI (the **complete** policy, which is a combination of the policy and the rule in PowerShell).

Orphaned policies in PowerShell without a corresponding rule don't function and aren't meant to be shown in the UI.

**Comment by stuartmaxwell** [comment]
Hi again @chrisda 

Thanks for pointing out the `Enable-SafeAttachmentRule` and `Disable-SafeAttachmentRule` cmdlets and updating the docs to reference them. But I think I confused the issues a bit and wanted to clarify a couple of points to show exactly why the docs are still incorrect after the change you have made.

The first point is the terminology. This is a bit confusing and it was only after all the testing I did that I figured out exactly what I was seeing in the UI: 
![image](https://user-images.githubusercontent.com/1298583/126093231-2110b8b6-2b2e-429c-a9ed-de2a14c7be56.png)

I think we were both mixing terms between Rules and Policies, but it is starting to make more sense to me now. Even so, it still seems backwards - in the UI you create the rule first and then configure the policy, but in PowerShell you create the policy first and then link it to a rule.

The second point is that I did the same test as you did in your first response, and I got different results. I created a new Safe Attachments policy in the M365 Defender portal and yes, it was also enabled by default. However, the results I got with PowerShell were different to yours, and I think I know why. I'm guessing when you created the policy in the UI, you did not select an action on the Settings page. It defaults to "Off" and if you leave it as "Off" then the Policy will not show as being enabled in PowerShell. If you set it to any of the other settings, e.g. Block, Replace, etc, then the policy will show as being enabledd in PowerShell.

```PowerShell
Get-SafeAttachmentPolicy "test policy" | fl enable

Enable : True

Get-SafeAttachmentRule "test policy" | fl state

State : Enabled
```

Notice there's no mismatch in values.

Then I also disabled the rule in the UI and got the following results in PowerShell:

```PowerShell
Get-SafeAttachmentPolicy "test policy" | fl enable

Enable : True

Get-SafeAttachmentRule "test policy" | fl state

State : Disabled
```

This is also a different result to your testing. With my testing, the policy remains enabled but the rule changes to a disabled state. To re-enable the rule from PowerShell, the only way to do it is to use the `Enable-SafeAttachmentRule` which you pointed out in your previous. In my first post, I incorrectly said that the "Set-SafeAttachmentRule" had an `-Enable` parameter - sorry, I was wrong about that.

```PowerShell
Set-SafeAttachmentRule -Enable $true
Set-SafeAttachmentRule: A parameter cannot be found that matches parameter name 'Enable'.

Enable-SafeAttachmentRule "test policy"

Get-SafeAttachmentRule "test policy" | fl State

State : Enabled
```

However, I still believe the docs are not yet correct as the `-Enable` parameter is definitely used (and needed) by the `New-SafeAttachmentPolicy` and the `Set-SafeAttachmentPolicy` cmdlets. Here's some further testing to demonstrate what I mean:

First create a new policy and then link it to a new rule without using the `-Enable` parameter:

```PowerShell
New-SafeAttachmentPolicy -Name "another test" -Action "Block" -Redirect $true -RedirectAddress "email@example.com" -ActionOnError $true

Name         Action Enable IsDefault
----         ------ ------ ---------
another test Block  False  False

New-SafeAttachmentRule -Name "another test" -SafeAttachmentPolicy "another test" -RecipientDomainIs "example.com"

Name         State   Priority SafeAttachmentPolicy Comments
----         -----   -------- -------------------- --------
another test Enabled 2        another test

Get-SafeAttachmentPolicy "another test" | fl Enable

Enable : False

Get-SafeAttachmentRule "another test" | fl State

State : Enabled
```

At this point, if you look in the GUI, the rule will have a status of "On" with a green light next to it, but if you click on it and look at the blade, you'll see that the "Safe Attachments detection response" will be set to "Off" instead of the "Block" setting it should be.

This is where the `-Enable` parameter is required to enable the policy:

```PowerShell
Set-SafeAttachmentPolicy "another test" -Enable $true

Get-SafeAttachmentPolicy "another test" | fl Enable

Enable : True
```

Now go back to the UI, look at the policy and you'll see the "Safe Attachments detection response:" setting is now correctly set to "Block" and it will have a green light next to it. You can toggle this setting by with the `-Enable` parameter of the `Set-SafeAttachmentPolicy` cmdlet again:

```PowerShell

Set-SafeAttachmentPolicy "another test" -Enable $false

Get-SafeAttachmentPolicy "another test" | fl Enable

Enable : False
```

And check the UI again and the "Safe Attachments detection response:" setting is back to "Off" again.

Note that the `Enable-SafeAttachmentRule` cmdlet has no effect on the policy since the rule is already enabled:

```PowerShell
Enable-SafeAttachmentRule "another test"

Get-SafeAttachmentPolicy "another test" | fl Enable

Enable : False
```

So going back to my original post, which after re-reading it is not as clear as it should have been, the following docs are still incorrect:

[New-SafeAttachmentPolicy](https://docs.microsoft.com/en-us/powershell/module/exchange/new-safeattachmentpolicy?view=exchange-ps) and [Set-SafeAttachmentPolicy](https://docs.microsoft.com/en-us/powershell/module/exchange/set-safeattachmentpolicy?view=exchange-ps): The `-Enable` parameter is definitely needed - it is the only way to enable a policy from PowerShell. You either need to use the `-Enable $true` parameter when creating the policy with the `New-SafeAttachmentPolicy` or you need to use it after the policy has been created with the `Set-SafeAttachmentPolicy` cmdlet.

Here's a demo:

```PowerShell
New-SafeAttachmentPolicy -Name "test one" -Action "Block" -Redirect $true -RedirectAddress "email@example.com" -ActionOnError $true

Name     Action Enable IsDefault
----     ------ ------ ---------
test one Block  False  False

❯ Get-SafeAttachmentPolicy "test one" | fl Enable

Enable : False


❯ Set-SafeAttachmentPolicy "test one" -Enable $true

❯ Get-SafeAttachmentPolicy "test one" | fl Enable

Enable : True


❯ New-SafeAttachmentPolicy -Name "test two" -Action "Block" -Redirect $true -RedirectAddress "email@example.com" -ActionOnError $true -Enable $true

Name     Action Enable IsDefault
----     ------ ------ ---------
test two Block  True   False

❯ Get-SafeAttachmentPolicy "test one" | fl Enable

Enable : True
```

Sorry, that's such a long post, but I wanted to be thorough since my first post caused a bit of confusion. 

Cheers.
Stuart

**Comment by chrisda** [comment]
@stuartmaxwell, everything you said is correct. Fundamentally, here's how it all breaks down:

- `-Enable $true` on New/Set-SafeAttachmentPolicy is required for recognition of the Action parameter value. If  `-Enable $false` (the default value), the value of Action is ignored.
- `Enable $false` on New/Set-SafeAttachmentPolicy corresponds to the **Off** value for **Safe Attachments unknown malware response** in the UI. Originally, `-Action Allow` was misidentified as the **Off** value for **Safe Attachments unknown malware response** in the UI. It should have been **Monitor**.

So, I update the Action and Enable parameter descriptions as follows:

> The Action parameter specifies the action for the safe attachment policy. Valid values are:
>
> - Allow: Deliver the message if malware is detected in the attachment and track scanning results. This value corresponds to **Monitor** for the **Safe Attachments unknown malware response** property of the policy in the admin center.
> ...
>
> The value of this parameter is meaningful only if the value of the Enable parameter is also $true (the default value is $false).
>
> To specify no action for the safe attachment policy (corresponds to **Off** for the **Safe Attachments unknown malware response** property of the policy in the admin center), use the Enable parameter with the value $false.

> The Enable parameter works with the Action parameter to specify the action for the safe attachment policy. Valid values are:
>
> - $true: The Action parameter specifies the action for the Safe Attachment policy.
> - $false: This is the default value. Attachments are not scanned by Safe Attachments, regardless of the value of the Action parameter. This value corresponds to **Off** for the **Safe Attachments unknown malware response** property of the policy in the admin center.
>
> To enable or disable a complete Safe Attachments policy in the admin center (the combination of the rule and the corresponding associated policy in PowerShell), use the Enable-SafeAttachmentRule or Disable-SafeAttachmentRule cmdlets.

Thanks for your hard work on this.

**Comment by stuartmaxwell** [comment]
Thanks @chrisda  - this was a useful exercise!
