### ISSUE TITLE
NonEditingAuthor

### ISSUE THREAD

**Issue by mark-tsc** [MicrosoftDocs/office-docs-powershell#8047]
The persission DeleteOwnedItems ist missing at the role NonEditingAuthor. 

Should be changed from:
_NonEditingAuthor: CreateItems, FolderVisible, ReadItems_
to:
_NonEditingAuthor: CreateItems, FolderVisible, ReadItems, DeleteOwnedItems_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1a893c8-66de-1f8a-f8d2-aa573379e778
* Version Independent ID: 1c32c637-d003-820c-594f-a9adc9c353d9
* Content: [Add-MailboxFolderPermission (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/add-mailboxfolderpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mark-tsc, confirmed.

![image](https://user-images.githubusercontent.com/33166947/125660616-7d9bdbe3-3a8a-42d8-a6f9-a4afb4d3c4f4.png)

Also affects the following topics, so I updated them, too:

- Set-MailboxFolderPermission
- Add-PublicFolderClientPermission
-  Remove-PublicFolderClientPermission

Thanks for the feedback.

Closing
