### ISSUE TITLE
Install-Module MicrosoftTeams: `cannot be installed … because it is not a properly-formed module`

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/office-docs-powershell#8048]
Hello

It is really a big shame: almost every time we want to install any PowerShell module from Microsoft (mostly related to Azure / O365), we get errors that are due to Microsoft not working properly. 

It's especially bad when a Microsoft PowerShell module can't update itself and one has to ask Google and end up following some tutorial from a private blog to get the work done 😢

###### Install-Module MicrosoftTeams: `cannot be installed … because it is not a properly-formed module`

This is the full story:
```
Install-Module MicrosoftTeams

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y

PackageManagement\Install-Package : The module 'MicrosoftTeams' cannot be installed or updated because it is not a properly-formed module. At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : InvalidManifestModule,Test-ValidManifestModule,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

Why does the Microsoft PowerShell Module of MicrosoftTeams 'Docs' not tell anything about installing the Module if it is so annoying?
Does Mircosoft itself have the same issues? Does Mircosoft expect their **customers(!)** to ask Google to get up and running the Mircosoft's Administrator-tools?

Thanks a lot, kind regards,
Thomas

**Comment by get-itips** [comment]
Hello @schittli Thomas, how are you? Hope you are doing good.
To check if we need to adjust any documentation, I tried to reproduce it but I could not. Both with GA and Public Preview versions. From the cmdlet you included I could guess the GA version was being installed, did you use Ps 7 or 5.1?
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @schittli Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
