### ISSUE TITLE
Missing parameter InlineCredential

### ISSUE THREAD

**Issue by MartinC-at-DS** [MicrosoftDocs/office-docs-powershell#8051]
The documentation offers this parameter:
* Connect-ExchangeOnline -InlineCredential

However this is not available:
Connect-ExchangeOnline : A parameter cannot be found that matches parameter name 'InlineCredential'.
At line:1 char:24
+ Connect-ExchangeOnline -InlineCredential

ExchangeOnlineManagement  was installed today

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MartinC-at-DS, are you using PowerShell 7? That parameter is only available in the EXO V2 module in PowerShell 7.

**Comment by MartinC-at-DS** [comment]
No I wasn't, that would explain the behaviour I was experiencing.
I can see it is well described in the docs, unfortunately I had jumped straight to using an example.
I'll read the docs more carefully in future :)

**Comment by chrisda** [comment]
OK. Thanks for the feedback.

Closing
