### ISSUE TITLE
-whatif flag in the New-ApplicationAccessPolicy cmdlet

### ISSUE THREAD

**Issue by jreed5** [MicrosoftDocs/office-docs-powershell#8053]
If the -whatif flag isn't usable in the New-ApplicationAccessPolicy cmdlet, then this needs to be notated in big, bold fonts. It really needs to be removed from the cmdlet command options as well though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a47ca7d5-2598-0c06-03fd-854f94cf6bbe
* Version Independent ID: a57408f6-16ca-3fcb-0c04-48a7a5f9942d
* Content: [New-ApplicationAccessPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-applicationaccesspolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jreed5, the topics on the web are also used for help on the command line, where all formatting goes away.

The only words in the description of WhatIf are:

>  The WhatIf switch doesn't work on this cmdlet.

WhatIf and Confirm area WindowsPowerShell thing, and are included on every type of cmdlet except Get\-.

**Comment by chrisda** [comment]
Nothing left to do.

Closing
