### ISSUE TITLE
Identity

### ISSUE THREAD

**Issue by farzadtehranian** [MicrosoftDocs/office-docs-powershell#8056]
What is Identity, how to create those? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f193d2b-d756-e08c-1770-03820c9561c9
* Version Independent ID: fd69e6c8-f461-dd78-cfaa-2426d1112283
* Content: [New-CsTeamsNetworkRoamingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsnetworkroamingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsNetworkRoamingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsNetworkRoamingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @TristanChen-msft
* Microsoft Alias: **jiaych**

**Comment by get-itips** [comment]
Hello @farzadtehranian how are you? Hope you are doing good.
The identity is the _Unique identifier of the policy_ (to be created), I'll make a correction to the documentation.
Let me know if I understood you well.
Thanks

**Comment by farzadtehranian** [comment]
Hello, What? I didn’t understand what you mean. What are you talking about? Would you mind please explain to me?Best Regards,Farzad Tehranian From: Andres Mariano GorzelanySent: Friday, July 23, 2021 1:54 PMTo: MicrosoftDocs/office-docs-powershellCc: FarzadTR; MentionSubject: Re: [MicrosoftDocs/office-docs-powershell] Identity (#8056) Hello @farzadtehranian how are you? Hope you are doing good.The identity is the Unique identifier of the policy (to be created), I'll make a correction to the documentation.Let me know if I understood you well.Thanks—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by get-itips** [comment]
Hello @farzadtehranian how are you? You asked what  is identity so I replied that identity is the Unique identifier of the policy (to be created).
Let me know if I understood you well, thank you
