### ISSUE TITLE
Unauthorized Error When Using Get-EXORecipientPermission

### ISSUE THREAD

**Issue by bmkaiser** [MicrosoftDocs/office-docs-powershell#8058]
After activating my **Exchange Administrator** Azure AD role in Privileged Identity Management, I cannot use `Get-EXORecipientPermission`. I get an error that I am not authorized. If I use the non-EXO version of the cmdlet, it functions correctly.

I'm using the most recent version of the Exchange Online Management module (version 2.0.5). The screenshot below is for Windows PowerShell 5.1, but the issue also occurs when using PowerShell 7.1.3. Issue appears to be with the REST service.

It's unclear how best to let the product team know about these issues now that User Voice has been retired for use by Microsoft.

![image](https://user-images.githubusercontent.com/5446414/125814752-042a3266-6dc9-4c8b-b0e3-0fc0853079c2.png)

Error text:

```PowerShell
Get-EXORecipientPermission : Error while querying REST service. HttpStatusCode=401
ErrorMessage={"error":{"code":"Unauthorized","message":"User is not allowed to call
Get-RecipientPermission","innererror":{"message":"User is not allowed to call
Get-RecipientPermission","type":"Microsoft.Exchange.Admin.OData.Core.ODataServiceException"}}}
At line:1 char:1
+ Get-EXORecipientPermission -Identity $identity
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ProtocolError: (:) [Get-EXORecipientPermission], RestClientException
    + FullyQualifiedErrorId : An error occurred while processing this request.,Microsoft.Exchange.Manag
   ement.RestApiClient.GetExoRecipientPermission
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 201c8f92-cffb-8d52-ab07-ccd1cc4f680d
* Version Independent ID: abc1c16d-93b5-1ee2-6e59-422b56e62983
* Content: [Get-EXORecipientPermission (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-exorecipientpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-EXORecipientPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-EXORecipientPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bmkaiser, send email to exocmdletpreview[at]service[dot]microsoft[dot]com.

Be sure to include the log files in your email message. To generate the log files, replace <Path to store log file> with the output folder you want, and run the following command:

```powershell
Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All
```

Or, you can open a support case (v2.0.5 of the module is in full mainstream support).

**Comment by bmkaiser** [comment]
Thank you, @chrisda. I've just tried to replicate the issue and found it's no longer occurring. If it occurs again, I'll be sure to follow your advice for log capture and reporting.
