### ISSUE TITLE
Delimiter to denote relative path to folder

### ISSUE THREAD

**Issue by gasperj** [MicrosoftDocs/office-docs-powershell#8062]
The examples use a back slash ( "\" ) as the path delimiter. Those result in "Set-PnPFolderPermission: File Note Found." error. 
If is use a forward slash as the path delimiter ( "/" ) the command completes successfully.

PS R:\> Set-PnPFolderPermission -List $doclib -Identity "$doclib\$user" -Group 'MyGroup_Add' -AddRole 'Add-Only'
Set-PnPFolderPermission: File Not Found.
PS R:\> Set-PnPFolderPermission -List $doclib -Identity "$doclib/$user" -Group 'MyGroup_Add' -AddRole 'Add-Only'
PS R:\>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852744c0-227a-a258-2206-7ac0ae744f20
* Version Independent ID: 8421d321-6408-d97a-6618-6fd0be96d31d
* Content: [Set-PnPFolderPermission (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpfolderpermission?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPFolderPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPFolderPermission.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @gasperj Joe,

how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @gasperj Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
