### ISSUE TITLE
Add-PublicFolderClientPermission 

### ISSUE THREAD

**Issue by 273Kelvin** [MicrosoftDocs/office-docs-powershell#8063]
On the Website Page, the documented permissions for the NonEditingAuthor Role for Add-PublicFolderClientPermission are: CreateItems, DeleteOwnedItems, FolderVisible, ReadItems.

However, in powershell if I connect a session to Exchange in the cloud and type  get-help Add-PublicFolderClientPermission -Detailed, then the documented permissions for the NonEditingAuthor Role for Add-PublicFolderClientPermission returned are: CreateItems, FolderVisible, ReadItems.

In test, the website version seems to reflect what happens, but that's not to say which is actually correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba50ae21-6a22-22be-58b5-7c145b394d2b
* Version Independent ID: 1cad51a8-c5a6-24db-55b1-bd4a094552c6
* Content: [Add-PublicFolderClientPermission (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/add-publicfolderclientpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Add-PublicFolderClientPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Add-PublicFolderClientPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@273Kelvin, the topics on the web are always going to be the most up-to-date. There's nothing we can do about that.

Those topics are used for help at the command line, but they need to be converted into XML, combined into the Help-* .dll.XML files, checked back into code, and then (for the cloud) distributed to all the datacenters.

There's really nothing we can do about the lag.

**Comment by 273Kelvin** [comment]
Thanks Chris.

On a related matter regarding Add-PublicFolderClientPermission, the webpage documentation for the – AccessRight Parameter says You can specify individual folder permissions or roles, which are combinations of permissions. You can specify multiple permissions and roles separated by commas.

When I use,
$Mypermissions = “CreateItems, FolderVisible”
Add-PublicFolderClientPermission -Identity "\My Public Folder" -User Chris -AccessRights $Mypermissions

Powershell automatically works out that this is the same as the Contributor Role and adds the permissions as “Contributor”

Similarly if I use,
$Mypermissions = “ReadItems”
Add-PublicFolderClientPermission -Identity "\My Public Folder" -User Chris -AccessRights $Mypermissions

Powershell adds the permissions as “ReadItems”

But if I use
$Mypermissions = “ReadItems,CreateItems, FolderVisible”
Add-PublicFolderClientPermission -Identity "\My Public Folder" -User Chris -AccessRights $Mypermissions

Powershell fails, reporting that “Cannot process argument transformation on parameter 'AccessRights'. Cannot convert value "ReadItems CreateItems FolderVisible" to type
"Microsoft.Exchange.Management.StoreTasks.MailboxFolderAccessRight[]”

In experimentation, it seems that PowerShell is

  *   allowing the use of any of the documented Roles, and
  *   allowing a list of multiple individual Rights only where the list equates to one of the pre-defined Roles, and
  *   allowing the use of any single Right (any of which I guess may be classified as a Custom Role)

What I want to set is a Custom Role including the rights “ReadItems, CreateItems, FolderVisible” but it doesn’t work. Ive checked using the O365 Website and can set a user to this Custom Role, so its not as if it’s an Exchange limitation.

Could you please advise if I’m perhaps using the wrong syntax for the multiple Rights?

Regards,

Neil Dubout

**Comment by chrisda** [comment]
@273Kelvin, it looks like a simple formatting issue. Quotes around each value works:

```powershell
[PS] C:\>$x = "ReadItems","CreateItems","FolderVisible"

[PS] C:\>$x

ReadItems
CreateItems
FolderVisible
```

Or, the parameter value without quotes also works: `-AccessRights ReadItems,CreateItems,FolderVisible`.

**Comment by yogkumgit** [comment]
@273Kelvin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
