### ISSUE TITLE
Verification of RawCanonicalName as filterable attribute

### ISSUE THREAD

**Issue by jimbobmcgee** [MicrosoftDocs/office-docs-powershell#8068]
Can someone clarify the documentation regarding the filterable property, `RawCanonicalName`?  The documentation suggests that wildcards are accepted here, but `canonicalName` is a *constructed attribute* within AD, which I assume means it is not stored or indexed within AD, but generated on the fly.  

Consider...

````
Set-DynamicDistributionList 'My DDL' -RecipientFilter "RawCanonicalName -like 'contoso.com/baseOU/OU1/*' -or RawCanonicalName -like 'contoso.com/baseOU/OU2/*'" -RecipientContainer 'contoso.com/baseOU'
````

Based on the documentation, the above *might* be considered valid syntax for a dynamic list comprising user mailboxes in two specific organisational units `baseOU/OU1` and `baseOU/OU2`.

However, in many other cases, querying this attribute fails with `A Filter was passed that uses constructed attributes.`

````
Get-Recipient -RecipientPreviewFilter "RawCanonicalName -like 'contoso.com/baseOU/OU1/*' -or RawCanonicalName -like 'contoso.com/baseOU/OU2/*'" -OrganizationalUnit 'contoso.com/baseOU'

Get-ADObject -LDAPFilter '(|(canonicalName=contoso.com/baseOU/OU1*)(canonicalName=contoso.com/baseOU/OU2/*))'
````

I appreciate that the documentation does not explicitly refer to `Get-Recipient`, but `Get-Recipient -RecipientPreviewFilter` is a commonly-accepted means to test the filter of a dynamic distribution list (i.e. one created with `New-DynamicDistributionList`):

````
Get-DynamicDistributionList 'My DDL' | %{ Get-Recipient -RecipientPreviewFilter ($_.RecipientFilter) -OrganizationalUnit ($_.RecipientContainer) }
````

This commonly-accepted test *will* fail with the `A Filter was passed that uses constructed attributes` error.

Creating or modifying the dynamic distribution list (i.e. with `New-DynamicDistributionList` or `Set-DynamicDistributionList`) does *not* fail when `-RecipientFilter` uses `RawCanonicalName`; both the `RecipientFilter` and `LdapRecipientFilter` properties appear to be "correctly" set.

But, if Exchange is internally using the `LdapRecipientFilter` to determine the list members (as might logically make sense), isn't it *also* going to receive this error, resulting in a dynamic list with no members, or some unseen internal error?

Or is Exchange doing some additional logic behind the scenes to compensate for this (ab)use of the `canonicalName` attribute?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3762ada1-99d6-fa6d-fbd7-524003f8c3b2
* Version Independent ID: 03e801b7-fa14-b5fb-8600-131c9e73292f
* Content: [Filterable properties for the RecipientFilter parameter](https://docs.microsoft.com/en-us/powershell/exchange/recipientfilter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/recipientfilter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/recipientfilter-properties.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jimbobmcgee, fundamentally, is your question about finding members of dynamic distribution groups? That is explained [here](https://docs.microsoft.com/exchange/recipients/dynamic-distribution-groups/view-dynamic-distribution-group-members):

```powershell
$group = "Full Time Employees"
Get-Recipient -RecipientPreviewFilter (Get-DynamicDistributionGroup $group).RecipientFilter
```

A few years ago, testing revealed that the _RawCanonicalName_ property was accepted (that is, did not generate an error) by the  RecipientFilter parameter. It's possible that the values that are usefu/valid/accepted by the _RawCanonicalName_ property need some carlification.

**Comment by jimbobmcgee** [comment]
Hi @chrisda; thanks for looking in...

> fundamentally, is your question about finding members of dynamic distribution groups

No, my question is about building a dynamic distribution group comprising users/mailboxes in two (or more) separate OUs.  The *RawCanonicalName* property looked like the most likely approach.

So far, I've considered...

 1. *Passing a `string[]` to `Set-DynamicDistributionGroup -RecipientContainer`*
     This obviously fails because `-RecipientContainer` is a `string`, not a `string[]` (this *is* as per documentation);  I guess it is synonymous with `-SearchBase` in other, more AD-centric cmdlets

 2. *Passing  `-RecipientFilter "(RecipientContainer -eq 'contoso.com/baseOU/OU1') -or (RecipientContainer -eq 'contoso.com/baseOU/OU2')"`*
     Suggested in a third-party forum, this *reads* like it would be correct, but actually *fails*, because it only finds *dynamic distribution lists* that have been created with the matched `-RecipientContainer` -- it is really only comparing with the AD attribute *msExchDynamicDLBaseDN*, which is where Exchange stores the `-RecipientContainer` parameter value for the list.  The documentation is technically correct here (the third-party forum was incorrect), although the *usefulness* of being able to filter on that property is questionable.

 3. *Passing `-RecipientFilter "(DistinguishedName -like '*OU=OU1,OU=baseOU,DC=contoso,DC=com') -or (DistinguishedName -like '*OU=OU2,OU=baseOU,DC=contoso,DC=com')"`*
     This falls foul of the constraint that `-like` wildcards have to appear on the right of the term, not on the left, so is a non-starter

 4. *Passing `-RecipientFilter "(RawCanonicalName -like 'contoso.com/baseOU/OU1/*') -or (RawCanonicalName -like 'contoso.com/baseOU/OU2/*')"`*
     This is the one we are discussing here.

Assuming the documentation is *correct*, attempt 4 should work, but I don't seem to be getting the results I expected from it.  It's like the list has no members:

 * No-one seems to get an email when that dynamic group is used
 * Outlook/OWA does not show the `List contains about XX recipients` MailTip, like it does with other dynamic groups

Further investigation of that shows that every other attempt to query this (i.e. with `Get-Recipient` and `Get-ADObject`) all result in the `A Filter was passed that uses constructed attributes` error.  Since I *know* that `Get-Recipient` throws up on that filter, I'm positing that the reason I'm not getting the results I expect (and the documentation implies) is that, internally, Exchange is hitting the same error and swallowing it.

What I can't be sure of, is whether:

 1. Exchange processes the `RawCanonicalName` property correctly, but I've done something wrong with my filter, so I'm not getting any results
 2. Exchange processes the `RawCanonicalName` property correctly, but whatever informs Outlook/OWA's MailTip does not, so *only* Outlook is showing the wrong result (but, in general, sent mail is correct)
 3. Exchange doesn't process the `RawCanonicalName` property correctly, but swallows the error, so neither Outlook nor sent mail is correct -- *this would indicate a documentation error*

...hence why I'm asking for the clarification.


Also, without wanting to detract from the original question...

> finding members of dynamic distribution groups? That is explained [here](https://docs.microsoft.com/exchange/recipients/dynamic-distribution-groups/view-dynamic-distribution-group-members):

Sorry to be *that guy* but, since you brought it up,I'm not sure *that* article is entirely correct, either.  `Get-Recipient -RecipientPreviewFilter` on its own is not enough to retrieve the right results -- you also need to pass `-OrganizationalUnit` as well, if a `-RecipientContainer` was supplied to `New-DynamicDistributionGroup` or `Set-DynamicDistributionGroup`.

If you don't pass `-OrganizationalUnit`, then `Get-Recipient` will return *all* users/mailboxes that match the `-RecipientPreviewFilter`, regardless of where they are in the OU tree, ignoring the limiting `-RecipientContainer` property.

In general, since all my users are in OUs, the command that works for me is:

````
$group = (Get-DynamicDistributionGroup "Full Time Employees")
Get-Recipient Get-Recipient -RecipientPreviewFilter ($group.RecipientFilter) -OrganizationalUnit ($group.RecipientContainer) 
````

That said, given how `contoso.com/Users` isn't an OU, it's a *container*, the best I can get to is the somewhat torturous:

````
$group = (Get-DynamicDistributionGroup "Full Time Employees")
Get-Recipient -RecipientPreviewFilter ($_.RecipientFilter) | Where-Object { 
    $_.DistinguishedName -ilike "*,$($group.RecipientContainer,DistinguishedName)" 
}
````

...but even that probably has edge cases I haven't considered.

**Comment by chrisda** [comment]
@jimbobmcgee:

- As you can see from the linked pull request, I corrected/updated the topic <https://docs.microsoft.com/exchange/recipients/dynamic-distribution-groups/view-dynamic-distribution-group-members> with the information you provided.
- For the goal of creating a DDG with multiple OU's as filters, have you considered using a normal distribution group with multiple DDGs as members, each using a different OU as a filter? That should work.

Honestly, if you want answers to your RawCanonicalName and/or how to filter by multiple OU questions, you'll need to open a support case.

**Comment by jimbobmcgee** [comment]
Thanks @chrisda.

> As you can see from the linked pull request, I corrected/updated the topic

Yes, that looks fine.

> have you considered using a normal distribution group with multiple DDGs as members

Was hoping to avoid so as not to confuse my end-users with more lists than necessary, but yes, that is where I'll probably have to go.

> you'll need to open a support case.

Appreciated, but no-one's going to foot the bill for that, for me, which is why I was going the route of asking whether the documentation was known to be correct.  

As it stands, there is simply no way for me to test without simply *doing* (which has its own internal politics), as the accompanying `Get-Recipient` cmdlet doesn't accept the `RawCanonicalName` property in its `-RecipientPreviewFilter`.

> A few years ago, testing revealed that the RawCanonicalName property was accepted (that is, did not generate an error) by the RecipientFilter parameter. 

This at least clears up that the documentation *only* confirms that using this property does not throw an error at the time the cmdlets are called (i.e. using it passes validation), not that it necessarily *works* as implied.  There might be some additional wording that could indicate this.

> It's possible that the values that are usefu/valid/accepted by the RawCanonicalName property need some carlification.

Is it likely that this clarification would ever be made?


Maybe the most-appropriate update to this documentation might be a reference/footnote, which you use to caveat the constructed AD attributes.  Something along the lines of:

*1. Property is based on a constructed Active Directory attribute, and does not correctly resolve all members when used in conjunction with `Get-Recipient -RecipientPreviewFilter`; however it does correctly resolve in (email policies|dynamic distribution groups)*

...but that, of course, would require you to know for certain what the behaviour actually *is*.

**Comment by chrisda** [comment]
@jimbobmcgee, one part I forgot to comment on:

You can always hide the dynamic distribution groups from the GAL so users can see them, and therefore won't be confused by them.

I added the following comment to the RawCanonicalName entry:

> Property is based on a constructed Active Directory attribute, and does not correctly resolve all members when used in conjunction with `Get-Recipient -RecipientPreviewFilter`.

I think we're done?

**Comment by jimbobmcgee** [comment]
@chrisda; I think that's fair.  I'm still trying to get a test audience together to determine whether RawCanonicalName actually works as advertised.  The doc changes are reasonable, though.

Thanks for your time.
