### ISSUE TITLE
Limits on Excluded domains and senders?

### ISSUE THREAD

**Issue by cablechewer** [MicrosoftDocs/office-docs-powershell#8074]
Are there limits on the number of Excluded Senders or Excluded domains?  If so can we get them documented in the description of each of these parameters of the command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15695a77-5d00-89d9-fba9-74de36ffd4cf
* Version Independent ID: 0e0863e8-82e8-0709-4204-bb406266b2f9
* Content: [Set-AntiPhishPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-antiphishpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cablechewer, according to [regular content](https://docs.microsoft.com/microsoft-365/security/office-365-security/set-up-anti-phishing-policies#impersonation-settings-in-anti-phishing-policies-in-microsoft-defender-for-office-365), the limit is approx. 1000 entries per list.

I updated the parameter descriptions in New- and Set- accordingly.

Thanks for the feedback.

Closing
