### ISSUE TITLE
Not working for Private Channel sites

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/office-docs-powershell#8075]
When using this cmdlet to apply a Site Design to a SharePoint site that was automatically created for a Private Channel in Teams, absolutely nothing happens :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f214cc0-a9b0-8a5a-9bb0-1ad59268a4ba
* Version Independent ID: 449d38c8-f0c8-e524-c4db-961e80fb80fc
* Content: [Invoke-SPOSiteDesign (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Invoke-SPOSiteDesign?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteDesign.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteDesign.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by tseward** [comment]
This isn't supported for Private Channel sites.

In general, Private Channel sites should be kept "hands off". Any setting changes, permissions included, should be done via Teams only. The site only serves as a document storage location for that particular Private Channel.

**Comment by sparkitect** [comment]
What about Columns and Content Types? These are **required** by many customers, for many reasons (e.g. Records Management, Process Automation, etc.) and I'm afraid this will make Private Channels unusable for quite a few of them...

**Comment by sparkitect** [comment]
Also, I'm sure it was considered, and is likely way too late, but:
If all that is needed is a 'document storage location' why not create and secure a Document Library in the original site, rather than creating a whole new SharePoint site?
