### ISSUE TITLE
Execute-AzureADLabelSync: Description is not entirely correct & clarification needed

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/office-docs-powershell#8078]
The documentation for Execute-AzureADLabelSync states:

```
This cmdlet is required if you were using sensitivity labels before September 2019.
```

Which is not entirely correct. I did some testing with newly created tenants and I'm not able to enable sensitivity labels for Groups and SharePoint Sites as long as I did not run the cmdLet.

Furthermore running `Execure-AzureAdLabelSync` is required per this [docs article "How to enable sensitivity labels for containers and synchronize labels"](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#how-to-enable-sensitivity-labels-for-containers-and-synchronize-labels)

Could you please clarify the usage of this command and please add the expected time for this command to complete. In my testing I did see changes happening within 24 hours to more than a week.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3403f8e2-7176-69b2-f36d-dbf4222c1418
* Version Independent ID: a967fe50-c8ce-aea9-1fbc-92e3c461dedb
* Content: [Execute-AzureADLabelSync (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/execute-azureadlabelsync?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Execute-AzureADLabelSync.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Execute-AzureADLabelSync.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@andikrueger, I believe you. I'm told that if you need to use the Execute-AzureADLabelSync cmdlet and/or the label sync takes more than 24 hours, you should open a support case.

Adding @cabailey for visibility.

**Comment by chrisda** [comment]
@andikrueger, I'm closing the issue. If you file a support case and the result uncovers and update that we need to make to the documentation, feel free to comment here and/or reopen the issue.

Thanks for the feedback.
