### ISSUE TITLE
Set-SPOSite with -ConditionalAccessPolicy throws error AuthContextStrength does not exist

### ISSUE THREAD

**Issue by LPopov17** [MicrosoftDocs/office-docs-powershell#8079]
Using Set-SPOSite with -ConditionalAccessPolicy throws an error: "**_Set-SPOSite : Field or property "AuthContextStrength" does not exist"_**

Examples

Set-SPOSite -Identity Sitename -ConditionalAccessPolicy AllowLimitedAccess

This used to work for the past years without any problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c62bf4a-ac47-96ce-33fb-0d5ea9b178ae
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @LPopov17 
I could reproduce, however, here, we are limited to documentation fixes and improvements. Will try to pass this on, thanks for the feedback!

**Comment by aspnet4you** [comment]
Facing same issue. Set-SPOSite is broken!!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @aspnet4you Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
