### ISSUE TITLE
Improper apostrophe handling in Get-EXORecipient -Filter

### ISSUE THREAD

**Issue by PeteA52** [MicrosoftDocs/office-docs-powershell#8082]
`Get-EXORecipient -Filter "displayName -eq 'O''Brien, Laurie L'"` fails with

Get-EXORecipient : The numbers of operators and operands don't match, please modify your filter.

Get-Recipient with the same filter works as expected.

**Comment by chrisda** [comment]
@PeteA52 I recommend one or both of the following actions:
- Report an issue at `exocmdletpreview[at]service[dot]microsoft[dot]com`, be sure to include the log files in your email message. To generate the log files, replace \<Path to store log file\> with the output folder you want, and run the following command:

  ```powershell
  Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All
  ```

- Open a support case.

**Comment by yogkumgit** [comment]
@PeteA52 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
