### ISSUE TITLE
Get-Team unreliable / returning incomplete results

### ISSUE THREAD

**Issue by robinmalik** [MicrosoftDocs/office-docs-powershell#8086]
Hi,

We have multiple issues with the Get-Team cmdlet in the MicrosoftTeams module (v2.3.0). Like many organisations, we're programmatically creating Teams based on organisational data (e.g. one Team to support one Dept/Module/some other business unit). 

However, Get-Team often fails to return Teams that we have previously created (and do still exist in Microsoft-land). This makes the data untrustworthy and very difficult to deal with. 

This problem can surface in multiple ways: 

1. **Running "Get-Team" to retrieve all teams** 
    - Results are often incomplete. When this happens, there are usually around 1-5 'missing' from what we expect, out of around 4000 Teams. 
    - [Problem 1 Demonstration script and output below](#user-content-problem1script).
 
2. **Running "Get-Team -MailNickName" to query for a specific Team.** 
    - We can run a loop 100 times (with 3 second wait) and it fails to find the Team 100 times. The next day, the Team is found 100 times. Sometimes for example, it's found only 95 times out of 100. It is unreliable.
    - Under the hood, it's using the Graph API. Here's an example of a Team that exists, has an associated UnifiedGroup with ResourceProvisioningOptions=Team):

        ```
        Get-Team -MailNickName 'thisisateam' -Verbose -Debug

        VERBOSE: Done performing authorization
        VERBOSE: Executing Get-Team for parameters GroupId: , User: , Archived: , Visibility: , DisplayName: , MailNickName: thisisateam
        DEBUG: Making an api call to the uri: https://graph.microsoft.com/beta/groups?$filter=resourceProvisioningOptions/Any(x:x eq 'Team')&$top=20&$count=true&$search="mailNickname:thisisateam"
        DEBUG: Returning 0 teams
        VERBOSE: Retrieving groups list
        VERBOSE: Done retrieving groups, getting team properties
        VERBOSE: Done processing Get-Team
        ```
    - [Problem 2 Demonstration script and output below](#user-content-problem2script).
------------------------------------

### Problem 1 Demonstration Script <a href="#user-content-problem1script" id="problem1script">#</a>
```
$LoopCount = 1
$Loops = 10
$WaitTimeSeconds = 400
do
{
    if($AllTeams) { $PreviousLoopData = $AllTeams }
 
    Write-Output "Get-Team Attempt $LoopCount | $(Get-Date -Format 'yyyy-MM-dd-HH-mm-ss')"
    try
    {
        $AllTeams = Get-Team -ErrorAction Stop
        Write-Output "    - Total Teams Found: $($AllTeams.Count)"
 
        if($PreviousLoopData)
        {
            $Diffs = Compare-Object -ReferenceObject $PreviousLoopData -DifferenceObject $AllTeams -Property MailNickName
            $NewButNotReally = $Diffs | Where-Object { $_.SideIndicator -eq '=>' } | Select-Object -Expand MailNickName
            if($NewButNotReally)
            {
                Write-Output "    - Comparison between previous loop and this loop suggests the following Teams have been CREATED: $($NewButNotReally -join ', ')"
            }
            $DeletedButNotReally = $Diffs | Where-Object { $_.SideIndicator -eq '<=' } | Select-Object -Expand MailNickName
            if($DeletedButNotReally)
            {
                Write-Output "    - Comparison between previous loop and this loop suggests the following Teams have been DELETED: $($DeletedButNotReally -join ', ')"
            }
        }
    }
    catch
    {
        Write-Output "    - $($_.Exception.Message) | $($_.FullyQualifiedErrorId)"
    }
    Start-Sleep -Seconds $WaitTimeSeconds
    $LoopCount++
} until ($LoopCount -ge 11)
```

**Output:**
```
Get-Team Attempt 1 | 2021-07-19-12-52-11
    - Total Teams Found: 4557
 
Get-Team Attempt 2 | 2021-07-19-13-01-52
Total Teams Found: 4556
    - Comparison between previous loop and this loop suggests the following Teams have been DELETED: 20BSPN54_11
 
Get-Team Attempt 3 | 2021-07-19-13-11-38
    - One or more errors occurred. | System.AggregateException,Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeam
 
Get-Team Attempt 4 | 2021-07-19-13-21-05
    - Total Teams Found: 4555
    - Comparison between previous loop and this loop suggests the following Teams have been CREATED: 20BSPN54_11
    - Comparison between previous loop and this loop suggests the following Teams have been DELETED: 21CVP335, 20PIB621
 
Get-Team Attempt 5 | 2021-07-19-13-31-38
    - Total Teams Found: 4554
    - Comparison between previous loop and this loop suggests the following Teams have been CREATED: 21CVP335, 20PIB621
    - Comparison between previous loop and this loop suggests the following Teams have been DELETED: 20CVB115, 21PSP900_3, 21CXP302
 
Get-Team Attempt 6 | 2021-07-19-13-42-13
    - Total Teams Found: 4557
    - Comparison between previous loop and this loop suggests the following Teams have been CREATED: 20CVB115, 21PSP900_3, 21CXP302
 
Get-Team Attempt 7 | 2021-07-19-13-51-54
    - One or more errors occurred. | System.AggregateException,Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeam
 
Get-Team Attempt 8 | 2021-07-19-14-03-15
    - Total Teams Found: 4557
 
Get-Team Attempt 9 | 2021-07-19-14-12-44
    - One or more errors occurred. | System.AggregateException,Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeam
 
Get-Team Attempt 10 | 2021-07-19-14-22-13
    - Total Teams Found: 4557
 ```

### Problem 2 Demonstration Script <a href="#user-content-problem2script" id="problem2script">#</a>
```
# Prove the Team exists and confirm MailNickName attribute:
Get-Team -GroupId '9e65f365-c96b-4a68-9057-54ee3f10aba0' -Verbose | Format-List *

# Now query for the Team using the MailNickName attribute:
$Attempt = 1
$Found = 0
$NotFound = 0
do
{
    try
    {
        Write-Output "Get-Team attempt $Attempt"
        $Team = Get-Team -MailNickName '21CVB079' -ErrorAction Stop -Verbose 
        if($Team)
        {
            Write-Host "    - Found" -ForegroundColor Green
            $Found++
        }
        else
        {
            Write-Host "    - Not Found" -ForegroundColor Red
            $NotFound++
        }
        $Attempt++
        Start-Sleep -Seconds 3
    }
    catch
    {
        Write-Output "Error getting Team. Will not count."
        $Attempt++
        Start-Sleep -Seconds 3
    }
}
until($Attempt -eq 101)

Write-Output "Team was found: $Found times"
Write-Output "Team was NOT found: $NotFound times"
```

**Comment by js-ware** [comment]
It isn't just Teams powershell Get-Teams, I'm seeing this problem in the Exchange Online V2 powershell module with Get-UnifiedGroup.  Even running a simple (Get-UnifiedGroup -ResultSize unlimited).count command to get the total number of groups results in wildly different numbers, from a few hundred to a few thousand.  I'm also seeing my session token timing out very frequently, every few minutes, resulting in this message:

Creating a new Remote PowerShell session using Modern Authentication for implicit remoting of "Get-UnifiedGroup" command ...

It used to be that would only happen once an hour or so.

**Comment by get-itips** [comment]
Hello @robinmalik Robin, how are you? Hope you are doing good. 👍 
I read and analyzed your very detailed post, thanks, however, here, we are limited to documentation fixes and improvements, I will try to pass this on to the team behind the module.
Thanks

**Comment by robinmalik** [comment]
Hi, thanks for the reply. I had noticed that some technical support was still given in this repo, so decided to try my luck as I've not managed to get any help from other Microsoft support areas so far. Hopefully you can reach the right people, even if it's an acknowledgement that this is a known issue, or by design (to drop requests when under overloaded).

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @robinmalik Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by robinmalik** [comment]
@js-ware I think this is throttling related, but the MicrosoftTeams PowerShell module just doesn't expose any of that information/feedback that's actionable. 

I can essentially break my tenancy by running `Get-Team` twice within roughly 10 minutes; that is, run it twice and then try doing `Get-Team -DisplayName "xyz"`, nothing is returned even when the Team exists. Infact, if you sit at the command prompt and keep running that single command from a shell manually (up key, enter, so roughly once a second), it'll return nothing for a number of attempts and then it'll return a result, and then nothing again. 

On a small number of occasions, calling `Get-Team -DisplayName 'xyz' -ErrorAction Stop`  I was able to catch an exception that really does suggest throttling. Snipped, but refers to error 429:

```
{
        "Exception":  {
                          "Message":  "429 in /v1.0/teams/ endpoint",
                          "Data":  "System.Collections.ListDictionaryInternal",
                          "InnerException":  null,
                          "TargetSite":  "Microsoft.TeamsCmdlets.PowerShell.Custom.Model.Team GetTeamWithGroupAttributes(System.String, System.String, System.String)",
                          "StackTrace":  "   at Microsoft.TeamsCmdlets.PowerShell.Custom.TeamsCmdlet.GetTeamWithGroupAttributes(String cmdletName, String uriSuffix, String groupId) in D:\\a\\1\\s\\src\\Microsoft.TeamsCmdlets.PowerShell.Custom\\TeamsCmdlet.cs:line 171\r\n   at Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeam.ProcessRecord() in D:\\a\\1\\s\\src\\Microsoft.TeamsCmdlets.PowerShell.Custom\\GetTeam.cs:line 192\r\n   at System.Management.Automation.CommandProcessor.ProcessRecord()",
                          "HelpLink":  null,
                          "Source":  "Microsoft.TeamsCmdlets.PowerShell.Custom",
                          "HResult":  -2146233088
                      },
        "TargetObject":  null,
        "CategoryInfo":  {
                             "Category":  0,
                             "Activity":  "Get-Team",
                             "Reason":  "HttpRequestException",
                             "TargetName":  "",
                             "TargetType":  ""
                         },
```

... but this is not consistent - most of the time the commands just return nothing so I can't catch anything.
