### ISSUE TITLE
Macros not filled in correctly

### ISSUE THREAD

**Issue by BenHagueNZ** [MicrosoftDocs/office-docs-powershell#8090]
Both -SiteExternalSharingControlType
{{ Fill SiteExternalSharingControlType Description }} and
 -SqlAssetCondition
{{ Fill SqlAssetCondition Description }} 
look like they should be doing some sort of macro expansion that hasn't worked correctly.
![Screenshot 2021-07-22 155934](https://user-images.githubusercontent.com/82684093/126588359-fa188544-3f80-418d-8c73-30bfca9dc2d7.png)

**Comment by get-itips** [comment]
Hello @BenHagueNZ how are you?
-SiteExternalSharingControlType update is on the way, and I am looking for the other parameter description.
Thank you

**Comment by cabailey** [comment]
Not sure why this was assigned to me - I'm not the owner for PowerShell docs.

**Comment by get-itips** [comment]
Hello @BenHagueNZ 
You can now see live the `SiteExternalSharingControlType` description both in `New-Label` and `Set-Label`.
About `SqlAssetCondition` I could get information that it will be removed soon from the cmdlet.
Thank you
@yogkumgit please close.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @BenHagueNZ Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
