### ISSUE TITLE
cmdlet / module is not there anymore

### ISSUE THREAD

**Issue by yannara** [MicrosoftDocs/office-docs-powershell#8091]
PS C:\Windows\system32> Import-Module ExchangeOnlineManagement
Import-Module : The specified module 'ExchangeOnlineManagement' was not loaded because no valid module file was found i
n any module directory.
At line:1 char:1
+ Import-Module ExchangeOnlineManagement
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ExchangeOnlineManagement:String) [Import-Module], FileNotFoundExce
   ption
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

PS C:\Windows\system32> Connect-ExchangeOnline
Connect-ExchangeOnline : The term 'Connect-ExchangeOnline' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct a
nd try again.
At line:1 char:1
+ Connect-ExchangeOnline
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-ExchangeOnline:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32>
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@yannara, is the EXO V2 module installed per <https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#install-and-maintain-the-exo-v2-module>?

**Comment by chrisda** [comment]
Closing due to lack of response.
