### ISSUE TITLE
-DisplayName and -MailNickName do not accept non-URL characters

### ISSUE THREAD

**Issue by Bart-Hoofd** [MicrosoftDocs/office-docs-powershell#8093]
The -DisplayName and -MailNickname parameters for Get-team do not accept non-URL characters (such as &); instead they throw the below error:

_Get-Team -DisplayName 'String containing an & in it'_
will result in:
_Get-Team : Error occurred while executing
Code: BadRequest
Message: There is an unterminated string literal at position 35 in '"displayName:String containing an '._

When converting the -Displayname of-MailNickName string using _[System.Web.HttpUtility]::UrlEncode()_ this error is resolved, and the search results in the correct output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38da792-01bc-28ad-7727-794075e150c9
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @Bart-Hoofd how are you? Hope you are doing good.
Here, we are limited to documentation changes and fixes, is there any special fix you see in the Get-Team article? Otherwise, I would suggest opening your feedback here https://microsoftteams.uservoice.com/ where It can reach the team behind the module.
Thanks for your feedback.

**Comment by yogkumgit** [comment]
@Bart-Hoofd Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
