### ISSUE TITLE
Description is inaccurate for SharePoint

### ISSUE THREAD

**Issue by pagejustin** [MicrosoftDocs/office-docs-powershell#8095]
The User Profile Service in SharePoint dictates what photo is displayed in SharePoint.

While there may be options to sync the services, the SP UPS can become disconnected and using the set/remove commands in EXO doesn't propagate the changes to SharePoint.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7be034d-0d10-d4e6-fa01-4dc8e6aa6259
* Version Independent ID: e1765bb9-508a-dfe2-c514-1c754f3751d0
* Content: [Remove-UserPhoto (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-userphoto?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-UserPhoto.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Remove-UserPhoto.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@pagejustin, I presume this issue also affects Add-UserPhoto?

Do you have any specific guidance about what to say and where to say it within the topic?

**Comment by pagejustin** [comment]
Specifically, our tenant is having a conflict with the process documented here: https://support.microsoft.com/en-us/office/information-about-profile-picture-synchronization-in-microsoft-365-20594d76-d054-4af4-a660-401133e3d48a.

The SP UPS is not retrieving the photo from EXO so any images hosted through EXO are different from the photos hosted from the SP UPS. While they should be the same, we have learned that there are separate photo stores. SharePoint's photos are served from:  https://<tenantname>-my.sharepoint.com/user%20photos.

We have a case open with Microsoft exploring this issue stating the following problem:

- Regarding the aforementioned article step 2: "SharePoint Online creates a small, medium, and large thumbnail photo from the picture that was returned from Exchange Online..."
- Exchange Online and Azure AD have the correct photo, the SharePoint User Profile Service does not.
- How do we force a new request from the SharePoint User Profile Service from Exchange Online?
- We want to overwrite the photos that users may have changed.

Other tenants have experienced this problem and doing a search on https://techcommunity.microsoft.com you can find more instances of orgs trying to ensure the sync is working (example: https://techcommunity.microsoft.com/t5/sharepoint/sharepoint-online-user-photo-sync/m-p/23832)

**Comment by pagejustin** [comment]
I found an article that describes when the photo does sync to SharePoint. A requirement is the affected user must browse to a SharePoint dependent resource. I have verified this with users in our environment.

https://threewill.com/user-photo-sync-behavior-in-office-365/

"The image will never show up until the user whose profile image was changed visits his/her My Site (or any page that shows the large thumbnail image) after the profile image has been changed. If a user doesn’t go to their profile page (My Site), profile image changes won’t sync to SharePoint."

**Comment by chrisda** [comment]
@pagejustin, great! I added the following text to the DESCRIPTION section of **Set-UserPhoto** and **remove-UserPhoto**:

> **Note**: Changes to the user photo won't appear in SharePoint until the affected user visit their profile page (My Site) or any SharePoint page that shows their large thumbnail image. 

Thanks for the feedback.

Closing (feel free to reopen as necessary).
