### ISSUE TITLE
New-MigrationBatch: A parameter cannot be found that matches parameter name 'AllowIncrementalSyncs'

### ISSUE THREAD

**Issue by dfsaqwe** [MicrosoftDocs/office-docs-powershell#8100]
Attempting to run batch with this flag, get error:

A parameter cannot be found that matches parameter name 'AllowIncrementalSyncs'.
    + CategoryInfo          : InvalidArgument: (:) [New-MigrationBatch], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-MigrationBatch
    + PSComputerName        : outlook.office365.com

Please remove if not valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68325010-9605-22b4-4b6c-b61f332dc321
* Version Independent ID: 47ce5d33-5483-8c8e-2aa2-532178bf466a
* Content: [New-MigrationBatch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dfsaqwe, that parameter is identified as on-premises Exchange only.  I tested in Exchange 2013 CU23, Exchange 2016 CU21, and Exchange 2019 CU10, and it's available.

Are you trying to use it in Exchange Online PowerShell? If you're using Exchange Server, it might be an RBAC problem. See [Find the permissions required to run any Exchange cmdlet](https://docs.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions) for steps to troubleshoot.

**Comment by chrisda** [comment]
Closing due to lack of response.
