### ISSUE TITLE
CsTeamsMessagingPolicy -AllowVideoMessages 

### ISSUE THREAD

**Issue by kyokujitsu** [MicrosoftDocs/office-docs-powershell#8102]
I've spotted a new switch with no documentation in CsTeamsMessagingPolicy. I suspect it'll allow video messages, is there further information available?

BR

**Comment by get-itips** [comment]
Hello @kyokujitsu how are you?
You are right, the parameter is there, however, in the Public Preview of the module, in the GA one it is not there yet.
The documentation will be updated when the parameter goes GA.
Thank you!

**Comment by kyokujitsu** [comment]
Hi @get-itips,
I see, thank you.
