### ISSUE TITLE
Preview notification of parameter -Template

### ISSUE THREAD

**Issue by Bart-Hoofd** [MicrosoftDocs/office-docs-powershell#8103]
The -Template parameter is no longer in preview since at least PowerShell v1.1.6. Update of the documentation to reflect that would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fff5e98-436e-f79c-e176-767f8de772e5
* Version Independent ID: b3377099-854a-50d0-0fe1-bbdd7ddec332
* Content: [New-Team (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @Bart-Hoofd I am looking into this. Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and updating the documentation with PR. @Bart-Hoofd Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Bart-Hoofd** [comment]
Hi Yogesh,

Thanks for updating the documentation!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
