### ISSUE TITLE
Unclear API Permissions needed

### ISSUE THREAD

**Issue by PsychoData** [MicrosoftDocs/office-docs-powershell#8106]
The **AccessTokens** parameter section is unclear. Is this to authenticate as a user? as an App? 

Depending on what kind of authentication - you could add some of the permissions requires as either Delegated or Application. 

Additionally, at one point it says "add all of the listed permissions" which is again unclear if you are trying to setup an Application to do this, or you are not very familiar that the Delegated Permissions will need the user to authenticate them. 

Perhaps we could just set up a sample application with the correct permissions and include a screenshot and/or table? 

![image](https://user-images.githubusercontent.com/3719116/126811165-f658b7b3-c71c-40fa-8e5c-0a0fd1057b96.png)

| Microsoft Graph                  | Delegated | User.ReadWrite.All       |
|----------------------------------|-----------|--------------------------|
| Microsoft Graph                  | Delegated | Group.ReadWrite.All      |
| Microsoft Graph                  | Delegated | AppCatalog.ReadWrite.All |
| Skype And Teams Tenant Admin API | Delegated | user_impersonation       |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0dce05-8bfd-0bfa-3753-0eb193852703
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by yogkumgit** [comment]
@AdwoodMicrosoft Please help us in resolving this issue. Thanks

**Comment by mariussm** [comment]
Following. I can not get this to work. Have tried both client credential grant and delegated flows. Documentation is clear enough I think - it just doesn't **work**. :(

**Comment by PhilipHaglund** [comment]
Any update from Microsoft regarding this? Why is Teams using different methods than Exchange, Azure AD, Graph etc to Connect non-interactively?

**Comment by mariussm** [comment]
I have a working solution here: https://github.com/MicrosoftDocs/office-docs-powershell/pull/8788#issuecomment-1013935274

**Comment by PhilipHaglund** [comment]
> I have a working solution here: [#8788 (comment)](https://github.com/MicrosoftDocs/office-docs-powershell/pull/8788#issuecomment-1013935274)

Thank you! But that's still using interactive logon. Need some sort of ETA when non-interactive (Application Permission) will be available.

**Comment by mariussm** [comment]
Sure it is non-interactive. It uses ROPC, which is a non-interactive OIDC flow. However, it does require a user, and does not work with an app only context using client credential flow.

**Comment by PhilipHaglund** [comment]
> Sure it is non-interactive. It uses ROPC, which is a non-interactive OIDC flow. However, it does require a user, and does not work with an app only context using client credential flow.

Hmm maybe I need to investigate further. Just a question regarding using the ROPC account, can MFA be activated or should it be excluded from that?

**Comment by mariussm** [comment]
The user account must be excluded from MFA in conditional access.

**Comment by yogkumgit** [comment]
@PsychoData Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by PsychoData** [comment]
@yogkumgit perhaps I misunderstood, but they just talked about whether or not you could have an application permission/ non-interactive authorization flow

It seems that they ended up agreeing that ROPC does not technically have to be an interactive login flow if the user is excluded from MFA.

I don't see what any of that has to do with the initial reason of this issue, which centered around how to authenticate with access token and which permissions that would require from an application point of view etc.

This is you is not about the technical aspect of whether you can authenticate, but rather the docs as I found them saying "just add all the permissions that you need to authenticate, and then authenticate" but never saying which permissions it is you need to do that. 

I would request that this be reopened, and actually addressed, and not closed four more times

**Comment by LycheeYum** [comment]
Of the four (4) permissions available in the Skype and Teams Tenant Admin API, which are required?

**Comment by yogkumgit** [comment]
@get-itips

**Comment by yogkumgit** [comment]
@pbafna03 @get-itips Kindly address this issue. Thanks

**Comment by PsychoData** [comment]
> Of the four (4) permissions available in the Skype and Teams Tenant Admin API, which are required?
> 
> Also, there is a requirement for a username and password. Could the requirement be explained? Does an admin need to hard-code their credentials here?

@LycheeYum This is not the place for this add-on question, friend. If you want to ask about Connect-MicrosoftTeams and those API Permissions, you should be able to follow [this link](https://github.com/MicrosoftDocs/office-docs-powershell/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20ed0dce05-8bfd-0bfa-3753-0eb193852703%0A*%20Version%20Independent%20ID%3A%2050e0366c-46b0-71da-b6f6-f422adaad785%0A*%20Content%3A%20%5BConnect-MicrosoftTeams%20(MicrosoftTeamsPowerShell)%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpowershell%2Fmodule%2Fteams%2Fconnect-microsoftteams%3Fview%3Dteams-ps)%0A*%20Content%20Source%3A%20%5Bteams%2Fteams-ps%2Fteams%2FConnect-MicrosoftTeams.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-docs-powershell%2Fblob%2Fmain%2Fteams%2Fteams-ps%2Fteams%2FConnect-MicrosoftTeams.md)%0A*%20Service%3A%20**teams-powershell**%0A*%20GitHub%20Login%3A%20%40SerdarSoysal%0A*%20Microsoft%20Alias%3A%20**serdars**) and fill out the form
