### ISSUE TITLE
Support for Announcement missing

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#8107]
Hello,

Noticed that the configuration of a MenuOption for Announcement is not yet documented. Reverse-engineering from a configured AutoAttendant has led me to try creating one with New-CsAutoAttendantMenuOption and I found a path:
- Parameter Action, Value `Announcement` missing
- Example for Announcement missing
- Parameter Prompt (required when Parameter Action is Announcement)

Since it is fresh in my mind, I will try to submit a PR in a few minutes.

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 858f1935-b42f-f0c4-3530-759e1fba3fa5
* Version Independent ID: 227ff950-f035-0e33-c67c-d794c04dc175
* Content: [New-CsAutoAttendantMenuOption (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csautoattendantmenuoption?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendantMenuOption.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsAutoAttendantMenuOption.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by DEberhardt** [comment]
PR is in: https://github.com/MicrosoftDocs/office-docs-powershell/pull/8108

**Comment by get-itips** [comment]
Hello @DEberhardt David, I guess this will be resolved when your PR is merged ;)

**Comment by DEberhardt** [comment]
Closed as #8108  is merged :)
