### ISSUE TITLE
EVERYTIHNG MS BUILDS IS GENIUS.  EVERYTHING THEY CREATE TO TRY AND TRAIN YOU TO USE IT IS APPPAAAAAUUUUUUULLLLLLLINNNNNNNGGGGGGGGG

### ISSUE THREAD

**Issue by kerstinshields** [MicrosoftDocs/office-docs-powershell#8110]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b23d72-33ed-a6a1-a442-a5e5cf039f9f
* Version Independent ID: 4247cf37-3667-2007-7251-46ed80f58ef5
* Content: [Get started with the SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by yogkumgit** [comment]
@kerstinshields Please write your comment and let us know what kind of document update you are suggesting. Thanks

**Comment by yogkumgit** [comment]
@kerstinshields We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
