### ISSUE TITLE
Check if user is assigned to a policy or not?

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/office-docs-powershell#8111]
I can assign and unassign a policy to user with the Grant-CsApplicationAccessPolicy cmdlet.
But how can I check or verify if a policy is currently assigned to a user or not?
Can you please document how that works?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9aec3f1-ac1c-b913-559e-9960755c21de
* Version Independent ID: 37893c2f-5fe1-825b-dc17-78f36c30978d
* Content: [Grant-CsApplicationAccessPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csapplicationaccesspolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsApplicationAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsApplicationAccessPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @frankpeng7
* Microsoft Alias: **frpeng**

**Comment by frankpeng7** [comment]
Yep @get-itips that's the right way as far as I know. Use `Get-CsOnlineUser` and filter by name if needed.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @frankpeng7 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by joergrenn** [comment]
@get-itips thanks this works
@yogkumgit  please add the information to the documentation. would help everyone

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
@yogkumgit You can close this. Thanks
