### ISSUE TITLE
Microsoft.SharePoint.MigrationTool.PowerShell does not migrate files without major version

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/office-docs-powershell#8113]
I use Microsoft.SharePoint.MigrationTool.PowerShell to migrate 2013 Library to SPO folder in a library and found out that all the files that did not have a major version, did not migrate.
Is there a flag I should use to make it migrate?

Thank you

**Comment by get-itips** [comment]
Hello @Ofer-Gal 
I tried to reproduce to see if we need to adjust any doc, but couldn't, can you detail the options used in the Register-SPMTMigration? thanks

**Comment by Ofer-Gal** [comment]
Register-SPMTMigration -SPOCredential $Global:SPOCredential -Force -PreserveUserPermissionsForSharePointSource $false 
Is there a settings to force all the files? I did not find it
Thank you

**Comment by get-itips** [comment]
Is there any entry in the log file about those files not being migrated?
Also be sure to be running the latest version of the spmt module.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and digging deep into it.  @Ofer-Gal We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
