### ISSUE TITLE
Unattended EXO: Example uses local machine rather than current user certificate store

### ISSUE THREAD

**Issue by iyerusad** [MicrosoftDocs/office-docs-powershell#8115]
https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#step-3-generate-a-self-signed-certificate

I spent a bit amount of time wondering why couldn't get this basic tutorial to work - it was only when I exported the certificate and tested using pfx file that I realized the command wasn't seeing the certificate (that was located in my localmachine cert store, not current user cert store).

This documentation appendix suggests creating a certificate in the LocalMachine cert store.

> ```ps
> # Create certificate
> $mycert = New-SelfSignedCertificate -DnsName "contoso.org" -CertStoreLocation "cert:\LocalMachine\My" -NotAfter (Get-Date).AddYears(1) -KeySpec KeyExchange
> ```

In my testing, the certificate would not be used when identifying via thumbprint (e.g. when using `Connect-ExchangeOnline` cmdlet). The cmdlet would spawn a browser window prompting for user login (not the behavior of app-only authentication) - the certificate/authentication was not found.

Additionally, further up in the page the document states:

> The certificate should be installed in the user certificate store.

Suggested change:
----

The code snippet should likely be updated to (use `Cert:\CurrentUser\My` path):
```ps
$mycert = New-SelfSignedCertificate -DnsName "contoso.org" -CertStoreLocation "Cert:\CurrentUser\My" -NotAfter (Get-Date).AddYears(1) -KeySpec KeyExchange
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#step-5-assign-azure-ad-roles-to-the-application)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@iyerusad, I updated the topic as you described.

Thanks for the feedback.

Closing
