### ISSUE TITLE
Error: Set-MalwareFilterPolicy doesn't have a parameter EnableFileFilter

### ISSUE THREAD

**Issue by mozilla0** [MicrosoftDocs/office-docs-powershell#8116]
There's an error in the cmdlets (Version 2.0.5) for ExchangeOnlineManagement. In the description page of the cmdlets it's written, that **-EnableFileFilter** give you the chance to enable custom attachments file types filter, but **Set-MailwareFilterPolicy** doesn't recognize the parameter **-EnableFileFilter**

It's written as example 2:
`Set-MalwareFilterPolicy -Identity Default -EnableFileFilter $true -FileTypes $FileTypesAdd`

![error_Set-MalwareFilterPolicy_EnableFileFilter](https://user-images.githubusercontent.com/17600172/127101235-762a3722-6c1c-4b54-b22a-9c6498c66b62.jpg)

**Comment by ogagnon96** [comment]
It does exactly the same for ExchangeOnlineManagement version 2.0.4, and for the powershell command New-MalwareFilterPolicy for the same 2 versions

**Comment by chrisda** [comment]
Investigating. The FileTypes parameter is still available, which leads me to believe that EnableFileFilter is now permanently turned on. But I'm attempting to confirm. The removal of EnableFileFilter must have happened rather recently (last confirmed sighting I have is 6/28).

**Comment by chrisda** [comment]
@mozilla0, @ogagnon96, I confirmed that the disappearance of the EnableFileFilter parameter was accidental and temporary. It should come back within the next few days.

**Comment by ogagnon96** [comment]
Thank you !

**Comment by yogkumgit** [comment]
@mozilla0 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
