### ISSUE TITLE
The Overview and Introduction pages are nearly identical

### ISSUE THREAD

**Issue by sloh-ms** [MicrosoftDocs/office-docs-powershell#8117]
There appear to be two pages that are only slightly different from each other.  Was this an accidental duplication?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03f9b8-7a1f-81e7-e8c2-0286f0cd3ffb
* Version Independent ID: 931924d1-2be2-bc20-41a6-0b86fc65db07
* Content: [Microsoft Teams cmdlet reference](https://docs.microsoft.com/en-us/powershell/teams/intro?view=teams-ps)
* Content Source: [teams/docs-conceptual/intro.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/docs-conceptual/intro.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @sloh-ms thanks for your feedback, I am looking into this.

**Comment by yogkumgit** [comment]
@JensTrier @get-itips Kindly address this issue. Thanks

**Comment by JensTrier** [comment]
@yogkumgit Sorry, not my area.

**Comment by yogkumgit** [comment]
@get-itips Please comment. Thanks

**Comment by yogkumgit** [comment]
@dstrome @get-itips any update.
