### ISSUE TITLE
Cannot set protection alert policy following these instructions

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/office-docs-powershell#8121]
The Set-ProtectionAlert commandlet throws an error no matter which identity format is used.

The documentation says to use GUID, ID or DN - but none of these work.

It always throws an error:
##### WARNING: An unexpected error has occurred and a Watson dump is being generated: There is no rule matching identity '2d161684-8def-403c-9df6-f20c66c64161'

This identity is the immutableID, GUID and ExchangeObjectID.

The same error is thrown if you supply the ID or DistinguishedName.

I've checked and the ID's of these default alert policies are the same between tenancies.

`17d51759-88e1-40c1-8df3-20bcf2e43057 | Elevation of Exchange admin privilege`
`2a244387-17f7-458b-81a1-87e75520dfa6 | Priority accounts' mail flow is unhealthy`
`2d161684-8def-403c-9df6-f20c66c64161 | Form flagged and confirmed as phishing`

#### Error thrown using DistinguishedName
WARNING: An unexpected error has occurred and a Watson dump is being generated: There is no rule matching identity 'FFO.extest.microsoft.com/Microsoft Exchange Hosted Organizations/f00ed340-8f84-4eb4-83f3-0075a22b262e/Configuration/Form flagged and confirmed as phishing'.
There is no rule matching identity 'FFO.extest.microsoft.com/Microsoft Exchange Hosted Organizations/f00ed340-8f84-4eb4-83f3-0075a22b262e/Configuration/Form flagged and confirmed as phishing'.    + CategoryInfo          : NotSpecified: (:) [Set-ProtectionAlert], ErrorRuleNotFoundException    + FullyQualifiedErrorId : Microsoft.Exchange.Management.UnifiedPolicy.ErrorRuleNotFoundException,Microsoft.Office.CompliancePolicy.Tasks.SetProtectionAlert    + PSComputerName        : aus01b.ps.compliance.protection.outlook.com

#### Error thrown using ID - Form flagged and confirmed as phishing

`Set-ProtectionAlert -Identity "Form flagged and confirmed as phishing" -NotifyUser $NotifyAddress`

WARNING: An unexpected error has occurred and a Watson dump is being generated: There is no rule matching identity 'Form flag
ged and confirmed as phishing'.
There is no rule matching identity 'Form flagged and confirmed as phishing'.
    + CategoryInfo          : NotSpecified: (:) [Set-ProtectionAlert], ErrorRuleNotFoundException
    + FullyQualifiedErrorId : Microsoft.Exchange.Management.UnifiedPolicy.ErrorRuleNotFoundException,Microsoft.Office.Compl 
   iancePolicy.Tasks.SetProtectionAlert
    + PSComputerName        : aus01b.ps.compliance.protection.outlook.com

The "Get-ProtectionAlert" command works perfectly fine with any of these identifiers, but even passing the output from Get-ProtectionAlert does not work, as it simply passes the GUID through.

#### Passing the output from Get-ProtectionAlert to Set-ProtectionAlert doesn't work either.

`Get-ProtectionAlert "Form flagged and confirmed as phishing" | Set-ProtectionAlert -NotifyUser $NotifyAddress`

WARNING: An unexpected error has occurred and a Watson dump is being generated: There is no rule matching identity 'f00ed340-
8f84-4eb4-83f3-0075a22b262e\Form flagged and confirmed as phishing'.
There is no rule matching identity 'f00ed340-8f84-4eb4-83f3-0075a22b262e\Form flagged and confirmed as phishing'.
    + CategoryInfo          : NotSpecified: (:) [Set-ProtectionAlert], ErrorRuleNotFoundException
    + FullyQualifiedErrorId : Microsoft.Exchange.Management.UnifiedPolicy.ErrorRuleNotFoundException,Microsoft.Office.Compl 
   iancePolicy.Tasks.SetProtectionAlert
    + PSComputerName        : aus01b.ps.compliance.protection.outlook.com

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93dccbe5-dd7c-d0e5-3d5d-079cc7638ec3
* Version Independent ID: 872b0669-f30d-3ce9-cd09-9eaa4e86c86e
* Content: [Set-ProtectionAlert (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-protectionalert?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-ProtectionAlert.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-ProtectionAlert.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@anthonynz, I did some testing:

```powershell
PS C:\> Get-ProtectionAlert -Identity "Chrisda Content search deleted" | FL Name,DistinguishedName,GUID

Name              : Chrisda Content search deleted
DistinguishedName : CN=Chrisda Content search deleted,CN=Configuration,CN=fabrikam.com,OU=Microsoft Exchange Hosted Organizations,DC=FFO,DC=extest,DC=microsoft,DC=com
Guid              : f911629e-44bd-4d70-b519-d7f527be08e5

PS C:\> Set-ProtectionAlert -Identity "Chrisda Content search deleted" -NotifyUser a@contoso.com

PS C:\> Set-ProtectionAlert -Identity "CN=Chrisda Content search deleted,CN=Configuration,CN=fabrikam.com,OU=Microsoft Exchange Hosted Organizations,DC=FFO,DC=extest,DC=microsoft,DC=com" -NotifyUser b@contoso.com

PS C:\> Set-ProtectionAlert -Identity "f911629e-44bd-4d70-b519-d7f527be08e5" -NotifyUser c@contoso.com
```

No errors. It would be highly unusual if the Identity parameter for a cmdlet didn't accept the DN value.

I'm using PowerShell 5.1 on Windows 10 Enterprise V21H1 x64 with EXO V2 module version 2.0.5.

What is your environment?

**Comment by anthonynz** [comment]
Hi @chrisda,  thanks for testing.

Sorry I've been working on a different project and just came back to this.

I have a similar environment as you - Win 10 Pro 21H1, PowerShell 5.1, Exchange Online v2 module 2.0.5.

I now know what I have done wrong, I was attempting to update the notification address on the Default Alert policies. 

Apparently this is not possible via PowerShell.  I can't fathom why we can't update the alert policies with the Set-ProtectionAlert command, it seems like a pretty simple task.

Anyone know a way to update the notify addresses via PowerShell if not with the set-protectionalert commandlet?

Cheers,
Anthony

**Comment by yogkumgit** [comment]
@anthonynz If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by anthonynz** [comment]
Thanks @yogkumgit,  it is already noted in the document

`Note: You can't use this cmdlet to edit default alert policies. You can only modify alerts that you created using the New-ProtectionAlert cmdlet.`

So it's more of a failing or inadequacy in the commandlet itself.

It would be great if you could pass feedback on to the engineering team who own the commandlet.
While it's understandable that most properties of the "Default" alerts should be read-only, it would be useful if we could modify the customisable properties from the command line instead of using the UI.
UI work risks introducing human error, and it's in a web browser - nobody enjoys working in a sluggish web browser.

**Comment by yogkumgit** [comment]
@chrisda
