### ISSUE TITLE
Documentation issue - Supported protocol combinations

### ISSUE THREAD

**Issue by PM735** [MicrosoftDocs/office-docs-powershell#8122]
Hello

Trying to create a rule below

**New-ClientAccessRule "test" -Priority 3 -Enabled $false -Action DenyAccess -AnyOfProtocols OutlookWebApp -ExceptAnyOfAuthenticationTypes BasicAuthentication**

Getting the error 

**New-ClientAccessRule: Chosen authentication type and protocol combination is invalid. See 'https://go.microsoft.com/fwlink/p/?linkid=869219' for supported combinations.**

BasicAuthentication is listed as a supported method for OutlookWebApp.

What is the problem and where the supported combinations are documented?

**Comment by chrisda** [comment]
@PM735, checking. This **might** have something to do with the [planned retirement of Basic auth](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-february-2021-update/ba-p/2111904) and/or [Security Defaults](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults).

That topic is the documentation for the AuthenticationType/Protocol combinations (<https://docs.microsoft.com/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules#authentication-types-and-protocols-in-client-access-rules>), but it's clear that updates are required.

**Comment by PM735** [comment]
Hello

I can confirm that the same issue occurs when I specify ADFSAuthentification instead of BasicAuthentication.
I get the same error that the combination of the protocol and authentication method is not supported.
I can also confirm that the command was tested on two different O365 tenants with default settings and we got the same error.

Is this an error in the documentation or in Exchange Powershell?

**Comment by yogkumgit** [comment]
@chrisda

**Comment by yogkumgit** [comment]
@PM735 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
