### ISSUE TITLE
Get-WhiteboardOwners keep returning same results with -ContinuationToken

### ISSUE THREAD

**Issue by vellabati** [MicrosoftDocs/office-docs-powershell#8124]
[Enter feedback here]
Unable to get the results, calls returning the same results even with ContinuationToken 
          $wbo = Get-WhiteboardOwners -Geography Worldwide -ContinuationToken $CT
         $CT = $wbo.continuationToken    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8175b620-52d8-8c18-d742-8b0c69437e55
* Version Independent ID: 10b25fd1-3443-1f53-2692-3491cd9bf322
* Content: [Get-WhiteboardOwners (MicrosoftWhiteboardAdmin)](https://docs.microsoft.com/en-us/powershell/module/whiteboard/get-whiteboardowners?view=whiteboard-ps)
* Content Source: [whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md)
* Service: **whiteboard-powershell**
* GitHub Login: @shlevari
* Microsoft Alias: **shlevari**

**Comment by get-itips** [comment]
Hello @vellabati how are you?
I tested this to see if we had to correct any documentation. However I could reproduce, as here we are limited to documentation fixes, will try to pass this on, however, opening a support ticket directly from your tenant would be good. Thanks!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @vellabati Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
