### ISSUE TITLE
Typo "InformationBarrierPolicy"→"New-InformationBarrierPolicy"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-docs-powershell#8126]
![new-informationbarrierpolicy_j](https://user-images.githubusercontent.com/40815708/127472772-7bc46f34-3b51-445c-b984-acb68d367b7c.png)

Link to article:
Tell us where exactly a problem occurs.
"https://docs.microsoft.com/ja-jp/powershell/module/exchange/policy-and-compliance/new-informationbarrierpolicy?view=exchange-ps"

Problem:
What's wrong with the article?
Typo "InformationBarrierPolicy"→"New-InformationBarrierPolicy"

related: https://github.com/MicrosoftDocs/feedback/issues/2669

#PingMSFTDocs

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: edf1d4f8-ff67-b39d-e710-f79b515d24f0
* Version Independent ID: 9307e1e5-9330-8674-3e8b-b95ec5b5b146
* Content: [New-InformationBarrierPolicy (ExchangePowerShell)](https://docs.microsoft.com/ja-jp/powershell/module/exchange/new-informationbarrierpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-InformationBarrierPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-InformationBarrierPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hyoshioka0128, the fix was made in English. It's only a matter of time before the updated topic is localized into other languages.

 <https://docs.microsoft.com/en-us/powershell/module/exchange/new-informationbarrierpolicy>

**Comment by yogkumgit** [comment]
@TinaMcN Please look into it. Thanks

**Comment by TinaMcN** [comment]
Adding @Soran-M who manages localization of Exchange PowerShell content

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Thanks. It has changed to an untranslated page now..
"https://docs.microsoft.com/ja-jp/powershell/module/exchange/new-informationbarrierpolicy?view=exchange-ps"
![new-informationbarrierpolicy_j](https://user-images.githubusercontent.com/40815708/128432893-71f60ea1-ddc1-4ad7-b076-2815407ac360.png)

**Comment by TinaMcN** [comment]
@Soran-M, can you please investigate why the content is appearing in English on the live site.   It is the same for other Exchange powershell topics, and seems to be affecting all languages, not just Japanese.  @hyoshioka0128 thanks for alerting us to that.

**Comment by yogkumgit** [comment]
@Soran-M Any update?

**Comment by yogkumgit** [comment]
@Soran-M Please revert with the update. Thanks

**Comment by yogkumgit** [comment]
@tiburd Please help us here. Thanks

**Comment by hyoshioka0128** [comment]
@yogkumgit @TinaMcN  - Fixed.
Closed #2669 .
