### ISSUE TITLE
ActivityBasedAuthenticationTimeoutWithSingleSignOnEnabled - Supported for EXO or not?

### ISSUE THREAD

**Issue by PM735** [MicrosoftDocs/office-docs-powershell#8131]
This article says that the parameter below is supported for Exchange Online.

**ActivityBasedAuthenticationTimeoutWithSingleSignOnEnabled**

However another Microsoft article says it is NOT supported for Exchange Online.

<https://support.microsoft.com/topic/description-of-the-activity-based-authentication-timeout-for-owa-in-office-365-0c101e1b-020e-69c1-a0b0-26532d60c0a4>

Which statement is true?

**Comment by PM735** [comment]
Hello again,
I had a separate ticket with O365 Support #26876407 and they affirmed that the parameter below is supported and functional in Exchange Online.

ActivityBasedAuthenticationTimeoutWithSingleSignOnEnabled 

Thus the change would need to be reversed and rather applied to the article below.

https://support.microsoft.com/topic/description-of-the-activity-based-authentication-timeout-for-owa-in-office-365-0c101e1b-020e-69c1-a0b0-26532d60c0a4

**Comment by yogkumgit** [comment]
@chrisda

**Comment by yogkumgit** [comment]
@chrisda please help.

**Comment by chrisda** [comment]
OK. Fixed. Closing.
