### ISSUE TITLE
ActivityBasedAuthenticationTimeoutWithSingleSignOnEnabled incorrect description?

### ISSUE THREAD

**Issue by PM735** [MicrosoftDocs/office-docs-powershell#8133]
Quote: "_The ActivityBasedAuthenticationTimeoutWithSingleSignOnEnabled parameter specifies whether to keep single sign-on enabled._"

It seems the description is incorrect ant the parameter rather enables or disables timeout when single sign-on enabled.

Please confirm/correct

**Comment by chrisda** [comment]
@PM735 , I updated the descriptions for ActivityBasedAuthenticationTimeoutEnabled, ActivityBasedAuthenticationTimeoutInterval, and ActivityBasedAuthenticationTimeoutWithSingleSignOnEnabled.

Thanks for the feedback.

Closing (feel free to reopen as necessar).

If you want to modify the parameter descriptions yourself, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.
