### ISSUE TITLE
Allow filtering of the get- and Remove-PnPFileVersion command

### ISSUE THREAD

**Issue by rbishop-etq** [MicrosoftDocs/office-docs-powershell#8135]
Currently the command to "Remove-PnPFileVersion" only provides two options: remove file versions one at a time, or remove ALL saved versions of a given file.
I have been able to find no functional method of using filtering inside powershell to only grab all file versions older than a certain date, or a RANGE of versions. Filtering methods such as piping it to "where-object" simply do not function as expected.
Please improve this to allow us to more easily clear out versions that are between certain version numbers, or all versions older than a given value or date, so we arent forced to remove versions one at a time when OneDrive/Sharepoint has been saving 500+versions and we only want to remove everything older than a week or so.

**Comment by get-itips** [comment]
Hello @rbishop-etq 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by rbishop-etq** [comment]
@get-itips 
Okay i can do that. Where is the most appropriate spot within there to post this - "Discussions" or "Issues" maybe?
Thanks

**Comment by rbishop-etq** [comment]
@get-itips 
So should i post it under "Issues" or "Pull Requests"?

Thanks for the help

**Comment by get-itips** [comment]
I would say you could submit your idea to "Issues".

**Comment by rbishop-etq** [comment]
Okay i have added it there using the format/template that system provided.
Thanks!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @rbishop-etq Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
