### ISSUE TITLE
AccessTokens paramters for Teams graph API

### ISSUE THREAD

**Issue by vFrohn** [MicrosoftDocs/office-docs-powershell#8136]
Regarding the paramter "-AccessTokens" when you are asked to "11. Add all the listed permissions."

It would be helpful if it where to say if you need to choose "delegated permissions" or "Application permissions" after du select "Skype and Teams Tenant Admin API" 

In my case I used "Delegated Permission" and selected the only one there was: "Access Microsoft Teams and Skype for Business data as the signed in user"

I would suggest adding the following:

**11. Select "Delegated Permission" again
12. Select "Access Microsoft Teams and Skype for Business data as the signed in user"**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0dce05-8bfd-0bfa-3753-0eb193852703
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps#parameters)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @vFrohn Christian, how are you?
Please kindly see https://github.com/MicrosoftDocs/office-docs-powershell/issues/8194#issuecomment-909343996

**Comment by yogkumgit** [comment]
@vFrohn If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
