### ISSUE TITLE
Microsoft Teams Powershell module 2.3.1 - Get-CSOnlineUser OR Get-CSOnlineApplicationInstance performance degraded after few days

### ISSUE THREAD

**Issue by bijaykush** [MicrosoftDocs/office-docs-powershell#8142]
I have used Microsoft Teams Module 2.3.1 to get the application instances of a tenant in an application. I have built the application in .Net Core using Powershell.exe and deployed it in Azure Virtual Machine. 
PS Command: Get-CSOnlineApplicationInstance executed through C# process in powershell.exe. 

Issues:
The response time was only 16-17 seconds at the first of deployment. And after a week or 2 weeks, I experienced that it took more than 1 min.

It happens also with other PS Commands for MS Teams Module like New-CsOnlineApplicationInstance, etc

I am wondering if we can resolve it by using any other version of the MS Teams module.

**Comment by DEberhardt** [comment]
As best as I can tell (running `Get-CsOnlineUser` and `Get-CsOnlineApplicationInstance` regularly), it is very situational.
I think it is dependent on the busyness of the Server. I have measurements of `Get-CsOnlineUser` between 400ms and 7+s right now, depending on load. On average however, I am getting about 900ms (when calling with the `Identity` Parameter and querying one specific item)

Previous versions of the module have some issues. For example, v2.0.0 had a bug that, if your machine wasn't in UTC timezone, the Command would take 15+s

Before v2, the Connection method with v1.1.6 and higher was not as stable as I would have liked (I stuck to the SkypeOnlineConnector which is now no longer working)

To answer your question, I wouldn't advise using older versions of the module. New updates however, may have some improvements for the connectivity

**Comment by bijaykush** [comment]
@DEberhardt 
Thank you for the detailed explanation. I have used the latest version i.e. 2.4.1 preview of the MS Teams Module. Seems like much better with the response time. Its been approx 4-5 days of these changes, response time is fine.
