### ISSUE TITLE
What does the default language in inbound spam filter translate into?

### ISSUE THREAD

**Issue by PekkaPek** [MicrosoftDocs/office-docs-powershell#8146]
Hello

I wonder, what the outcome language is when you set parameter EndUserSpamNotificationLanguage to Default (Set-HostedContentFilterPolicy cmdlet).

[Set-HostedContentFilterPolicy cmdlet](https://docs.microsoft.com/en-us/powershell/module/exchange/set-hostedcontentfilterpolicy?view=exchange-ps) page says that

> The default value is Default, which means end-user spam quarantine notifications use the default language of the cloud-based organization.

[Configure anti-spam policies in EOP](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies?view=o365-worldwide#configure-end-user-spam-notifications) page says in the other hand

> Language: Click the drop down an select an available language from the list. The default value is Default, which means English.

I think they are speaking the same setting. I wonder which is the correct one.

Regards,
PekkaPek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164c3337-1862-be67-7e1d-ea8055b88791
* Version Independent ID: 3cb06add-3cb6-7cb8-779b-a681e03ab4fb
* Content: [Set-HostedContentFilterPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-hostedcontentfilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-HostedContentFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@PekkaPek, same question asked last year in the repo of that [Configure anti-spam policies](https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-your-spam-filter-policies#configure-end-user-spam-notifications) topic:

 <https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2362>

I updated the _EndUserSpamNotificationLanguage_ parameter description in New-HostedContentFilterPolicy and Set-HostedContentFilterPolicy to say:

> The default value is Default, which means English.

Thanks for the feedback.

Closing
