### ISSUE TITLE
-ExcludeContent Switch doesn't work for Get-CsAutoAttendant

### ISSUE THREAD

**Issue by darwincr** [MicrosoftDocs/office-docs-powershell#8147]
Why -ExcludeContent Switch doesn't work?

**Get-CsAutoAttendant -Identity $aa.Identity -ExcludeContent**

```
Parameter set cannot be resolved using the specified named parameters.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\SfBORemotePowershellModule.psm1:1800 char:9
+         $steppablePipeline.End()
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-CsAutoAttendant], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Rtc.Management.Hosted.OAA.V2.GetCsAaCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8eda0b1-3667-3124-946f-bbc581120725
* Version Independent ID: 450eaa1b-b14b-c248-790e-13eb583e434b
* Content: [Get-CsAutoAttendant (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsAutoAttendant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsAutoAttendant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @darwincr how are you?
Tested this, looks like that it will throw that only if you specify the identity, the same happens for example for First and Skip.
Will try to improve the article stating this.
Thank you!
