### ISSUE TITLE
You are not permitted to modify parameter: MeetingRecordingExpirationDays

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#8148]
Hi,
When running the command:
**PS C:\> Set-CsTeamsMeetingPolicy -Identity "Test policy" -MeetingRecordingExpirationDays 2**
We are getting the error:
**You are not permitted to invoke Set-CsTeamsMeetingPolicy with the following parameters:
MeetingRecordingExpirationDays**

This is related to change where Teams meetings recordings are stored into OneDrive instead of Streams. Documentation says nothing about this error. Our aim is of course testing this before all users are affected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by smokey7722** [comment]
I can confirm I see this as well in multiple tenants I administer.

**Comment by get-itips** [comment]
Hello @Petri-X please see

> You can use PowerShell to modify “MeetingRecordingExpirationDays.” This can be done after September 1, once the setting is present in PowerShell, even though the feature is not yet enabled. An example command is: "Set-CsTeamsMeetingPolicy -Identity Global -MeetingRecordingExpirationDays 50.”

Source https://docs.microsoft.com/en-us/microsoftteams/cloud-recording

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Petri-X Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
