### ISSUE TITLE
When will Connect-IPPSSession get -Certificate* parameter support

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#8149]
I'm hoping to find out if/when Microsoft will add support for app-only, certificate/client credential authentication for Connect-IPPSSession, like has already been added for Connect-ExchangeOnline.  Any ideas on ETA that can be shared here?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebcb7e5d-c0aa-f4f3-e6d5-914219d16dff
* Version Independent ID: 36d9a36f-fbdf-e4a1-45d7-51cc1a65643b
* Content: [Connect to Security & Compliance Center PowerShell using the EXO V2 module](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps#how-do-you-know-this-worked)
* Content Source: [exchange/docs-conceptual/connect-to-scc-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-scc-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeremyTBradshaw, nothing to share. Your best bet is to open a support case about this.

**Comment by JeremyTBradshaw** [comment]
Thanks, it was a shot in the dark.

**Comment by JeremyTBradshaw** [comment]
Putting it here.

# MC316448 (Published Jan 21, 2022)

> ## Certificate based Authentication for Security and Compliance Center PowerShell
> With this update, which will improve the security of your tenant, Security & Compliance PowerShell will enable configuration of certificate-based authentication to allow unattended App-only access. 
> 
> ### When this will happen:
> 
> Rollout will begin in mid-February and is expected to be complete by early March.

**Comment by JeremyTBradshaw** [comment]
And re-closing.

**Comment by JeremyTBradshaw** [comment]
@chrisda This worked!  Thanks very much for the tip.  Note, and this maybe obvious to many, with the Office 365 Exchange Online API's application permission Exchange.ManageAsApp + Exchange Administrator role (assigned to the Enterprise App / ServicePrincipal) I only got access to these commands:

```PowerShell
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Delete-QuarantineMessage                           1.0        tmp_2jjokwj4.gen
Function        Get-DeviceComplianceDetailsReport                  1.0        tmp_2jjokwj4.gen
Function        Get-DeviceComplianceDetailsReportFilter            1.0        tmp_2jjokwj4.gen
Function        Get-DeviceCompliancePolicyInventory                1.0        tmp_2jjokwj4.gen
Function        Get-DeviceComplianceReportDate                     1.0        tmp_2jjokwj4.gen
Function        Get-DeviceComplianceSummaryReport                  1.0        tmp_2jjokwj4.gen
Function        Get-DeviceComplianceUserInventory                  1.0        tmp_2jjokwj4.gen
Function        Get-DeviceComplianceUserReport                     1.0        tmp_2jjokwj4.gen
Function        Get-Group                                          1.0        tmp_2jjokwj4.gen
Function        Get-QuarantineMessage                              1.0        tmp_2jjokwj4.gen
Function        Get-QuarantineMessageHeader                        1.0        tmp_2jjokwj4.gen
Function        Get-Recipient                                      1.0        tmp_2jjokwj4.gen
Function        Get-User                                           1.0        tmp_2jjokwj4.gen
Function        Preview-QuarantineMessage                          1.0        tmp_2jjokwj4.gen
Function        Release-QuarantineMessage                          1.0        tmp_2jjokwj4.gen
```

But with the Compliance Administrator AAD role assigned, I then got access to most of the other commands.  I'm not sure if AAD roles alone cover off the requirements for all of the possible SCC cmdlets, but checked/confirmed that in https://compliance.micrososoft.com, I can't assign roles in there to Service Principals.  I'm thinking there could be some gaps here with the export-enabled role entries, but that's just a hunch and no biggie as this functionality covers more than I've been needing so far.

Thanks again.  This is great.

**Comment by JeremyTBradshaw** [comment]
@chrisda are you familiar with Message Center message MC316448?  It is completely lacking any information about HOW Microsoft plans to rollout app-only certificate authentication for the Security and Compliance Center.  It simply links to these two pages which show nothing of what you shared with me:

Learn more:

[Connect to Security & Compliance PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-scc-powershell?view=exchange-ps)
[App-only authentication for unattended scripts in the EXO V2 module](https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)

[Additional information](https://docs.microsoft.com/powershell/exchange/connect-to-scc-powershell?view=exchange-ps)

I would like to know - is Connect-IPPSSession being updated, or will the new functionality just be advertised with Connect-ExchangeOnline's documentation.  Any idea?

PS.  That Message Center announcement is driving me nuts! 🍻

**Comment by chrisda** [comment]
@JeremyTBradshaw, due to the upcoming demise of Basic auth and the MC post, it only makes sense that Connect-IPPSSession will be updated to support CBA.

You'll note that this issue (and others) are tagged with the "CBA SCC" label, so it's easy for me to come back and add any new information.

**Comment by JeremyTBradshaw** [comment]
Thank you.  I will try to be patient and wait for the updates to come.  The MC post says to Act by Feb 20th, but no info for what that means.

**Comment by chrisda** [comment]
Version 2.0.6-Preview5 of the EXO V2 Module is now available, so the various Credential parameters are now available on Connect-IPPSSession, so certibicate-based/app-oly authentication is now fully available in Security & Compliance Center PowerShell.
