### ISSUE TITLE
-AutoMapping default value confusion

### ISSUE THREAD

**Issue by jeremy-berry** [MicrosoftDocs/office-docs-powershell#815]
The -AutoMapping parameter states in the description that the default value is $true, but states 'None' in the properties table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb509e0a-2371-d5b8-6462-c0f29e6c8152
* Version Independent ID: b8fdd337-395d-0c42-4ff1-9a0969a9d578
* Content: [Add-MailboxPermission (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/add-mailboxpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Add-MailboxPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Add-MailboxPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Fixed
