### ISSUE TITLE
-Confirm switch does not work for Remove-SPOSite and Remove-SPODeletedSite

### ISSUE THREAD

**Issue by LuckyLub** [MicrosoftDocs/office-docs-powershell#8153]
In SharePointOnlinePowerShell for the commands `Remove-SPOSite` and `Remove-SPODeletedSite`, the -Confirm switch does not seem to work. When using them I still get prompted for confirmation, similair to not using the switch.

```
Name                                   Version
----                                   -------
Microsoft.Online.SharePoint.PowerShell 16.0.21411.12000
```

**Comment by get-itips** [comment]
Hello @LuckyLub 
How are you? tested to see if we have to impact any documentation, with the same exact version and did not experience that.
Keep in mind there is now a [newer version](https://www.powershellgallery.com/packages/Microsoft.Online.SharePoint.PowerShell/16.0.21513.12000) of the module.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @LuckyLub Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
