### ISSUE TITLE
Connect-MicrosoftTeams error in Azure function (VS Code)

### ISSUE THREAD

**Issue by takagim** [MicrosoftDocs/office-docs-powershell#8154]
I get an error when I run the Connect-MicrosoftTeams command when debugging with VSCode.
An error is output, but the process to O365 can be executed correctly.
Similarly, when the Connect-ExchangeOnline command is executed, no error occurs and the process to O365 can be executed correctly.

Code:
- run.ps1
#$credential = $env:SSF_Credential
#$passcode = $env:SSF_Passcode
$credential = "xxxx@aaaa.onmicrosoft.com"

#$password = $passcode | ConvertTo-SecureString -key (1..16)
$password = ConvertTo-SecureString "xxxxxx" -asplaintext -force
$LiveCred = New-Object System.Management.Automation.PSCredential $credential, $password

#Connect-ExchangeOnline -Credential $LiveCred -ShowBanner:$false
Connect-MicrosoftTeams -Credential $LiveCred

- requirements.psd1
@{
    # For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'.
    # To use the Az module in your function app, please uncomment the line below.
    #'Az' = '6.*'
    'ExchangeOnlineManagement' = '2.*'
    'MicrosoftTeams' = '2.*'
}

Error:
[2021-08-06T07:39:40.854Z] Executed 'Functions.G0010' (Failed, Id=ee296b0e-f6f5-4999-b7f2-af536686b62a, Duration=5830ms)
[2021-08-06T07:39:40.856Z] System.Private.CoreLib: Exception while executing function: Functions.G0010. System.Private.CoreLib: Result: Failure
Exception: The type 'System.Collections.Generic.Dictionary`2[[Microsoft.TeamsCmdlets.Powershell.Connect.Common.Endpoint, Microsoft.TeamsCmdlets.PowerShell.Connect, Version=2.3.1.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3],[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' is not supported for serialization or deserialization of a dictionary. Keys must be strings.
Stack:    at Microsoft.PowerShell.Commands.JsonObject.ProcessDictionary(IDictionary dict, Int32 depth, ConvertToJsonContext& context)
[2021-08-06T07:39:40.858Z]    at Microsoft.PowerShell.Commands.JsonObject.ProcessValue(Object obj, Int32 currentDepth, ConvertToJsonContext& context)
[2021-08-06T07:39:40.859Z]    at Microsoft.PowerShell.Commands.JsonObject.ProcessCustomObject[T](Object o, Int32 depth, ConvertToJsonContext& context)

Environment:
Windows 10 21H1
VS Code 1.59.0
  Japanese Language Pack 
  Azure Functions 1.4.1
  Powershell V2021.6.2
  Azure Account v0.9.8
  Azure Resource v0.4.0

**Comment by get-itips** [comment]
Hello @takagim how are you? Hope you are doing good.
Here we are limited to documentation fixes and improvements, is there any article that you think needs a fix?

Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @takagim Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
