### ISSUE TITLE
Error processing request - Getting members properties

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#8156]
I'm getting the following error just trying to get the members of this cmdlet

Get-CsOnlineDialInConferencingUser | Get-Member

   TypeName: Deserialized.Microsoft.Rtc.Management.Hosted.Cbd.ConferencingUser

Name                  MemberType   Definition
----                  ----------   ----------
GetType               Method       type GetType()
ToString              Method       string ToString(), string ToString(string format, System.IFormatProvider formatPr...
PSComputerName        NoteProperty string PSComputerName=api.interfaces.records.teams.microsoft.com
PSShowComputerName    NoteProperty bool PSShowComputerName=False
RunspaceId            NoteProperty guid RunspaceId=84e24115-e490-43ce-a77e-d8efbc6c5774
AllowPstnOnlyMeetings Property     System.Boolean {get;set;}
AllowTollFreeDialIn   Property     System.Boolean {get;set;}
BridgeId              Property     System.Guid {get;set;}
BridgeName            Property     System.String {get;set;}
ConferenceId          Property     System.Int32 {get;set;}
Identity              Property     Deserialized.Microsoft.Rtc.Management.AD.UserIdParameter {get;set;}
LeaderPin             Property     System.String {get;set;}
ServiceNumber         Property     System.String {get;set;}
SipAddress            Property     System.String {get;set;}
Tenant                Property     System.Guid {get;set;}
TollFreeServiceNumber Property      {get;set;}
Error processing request.
    + CategoryInfo          : ObjectNotFound: (:) [Get-CsOnlineDialInConferencingUser], BvdCmdletException
    + FullyQualifiedErrorId : Error processing request.,Microsoft.Rtc.Management.Hosted.Cbd.GetCsOnlineDialinConferenc
   ingUserCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

I'm currently using 2.3.1 of the MicrosoftTeams module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a78c07b-1a7e-b36c-e3c1-8e610638ff79
* Version Independent ID: 02174a2a-5102-5479-f72f-c9bf0691bf9b
* Content: [Get-CsOnlineDialInConferencingUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @sarollins how are you?
I could reproduce. however, here, we are limited to documentation changes and improvements so I can not help with it, The best in this scenario would be to open a support request from your tenant.
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
