### ISSUE TITLE
Clarification of Parameter Behaviour

### ISSUE THREAD

**Issue by davidkench** [MicrosoftDocs/office-docs-powershell#8158]
Following some very useful clarifications provided by Kwame Owusu I would suggest further information would be useful in determining the expected behaviours of a few parameters under the Set-CalendarProcessing cmdlet.  Kwame was able to locate and provide details from <https://techcommunity.microsoft.com/t5/exchange-team-blog/automatic-processing-of-recurring-meeting-requests-with/ba-p/587507>.

I would suggest this should be updated and posted to a more official channel than an Exchange blog from 2011.

Maybe the parameter at <https://docs.microsoft.com/powershell/module/exchange/set-calendarprocessing> could be updated as below?

-AllowConflicts

The AllowConflicts parameter specifies how conflicting meeting requests are actioned. Valid values are:

- $true: Conflicts are allowed.  The recurring meeting series is accepted regardless of whether any of the meeting occurrences within the series conflict with existing bookings. Where conflicts occur within the series, the occurrences will be declined but no decline notification emails will be sent to the organizer. Any values set under -ConflictPercentageAllowed or -MaximumConflictInstances are ignored.
- $false: Conflicts aren't allowed. This is the default value. The recurring meeting series is declined if any conflicts occur within the recurring meeting series, unless the values set under -ConflictPercentageAllowed or -MaximumConflictInstances are higher than the default “0”. Where the percentage or number of conflicts within the series is lower than the set value, the recurring meeting series is accepted, but the conflicting occurrences are declined. If the -EnableResponseDetails is set to True, the organizer will receive a decline notification email for each declined occurrence. If the percentage or number of conflicts within the series is higher than the set value, the recurring meeting series is declined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d95eb528-ab96-b415-981c-35d50c90dba0
* Version Independent ID: 0433f43b-538d-8000-a11d-69b4a5c97e0e
* Content: [Set-CalendarProcessing (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-calendarprocessing?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@davidkench, sounds good to me. I added what you said with a little editorial license.

<https://github.com/MicrosoftDocs/office-docs-powershell/pull/8161/files>

In the future, you can make changes like this directly in the topic (no need to open a GitHub issue first). See <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
