### ISSUE TITLE
Get-Team -MailNickName does not return exact value as documented. Works as a filter. 

### ISSUE THREAD

**Issue by DaveClarkey** [MicrosoftDocs/office-docs-powershell#8165]
See attached
![Screenshot 2021-08-10 093758](https://user-images.githubusercontent.com/48498285/128787601-34b386a5-36ce-4a49-89df-331a41743da8.jpg)
![Screenshot 2021-08-10 093949](https://user-images.githubusercontent.com/48498285/128787606-c14beaf9-41dc-4ac5-9cfe-65b41c7e2496.jpg)

Documentation: https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps

![Screenshot 2021-08-10 094659](https://user-images.githubusercontent.com/48498285/128788073-38367364-e9cb-4081-9c22-d4c201c53700.jpg)

**Comment by get-itips** [comment]
Hello @DaveClarkey 
How are you? Hope you are doing good.
Currently the article has a note clarifying that

> Note
Get-Team may return multiple results matching the input and not just the exact match for attributes like DisplayName/MailNickName. This is known behavior.

However I will propose removing the exact match sentence from the parameter description.

Thanks
