### ISSUE TITLE
Get-SPOSiteScriptFromWeb does not include Quick Launch, no AddNavLink in output

### ISSUE THREAD

**Issue by JesperGSimonsen** [MicrosoftDocs/office-docs-powershell#8166]
When running Get-SPOSiteScriptFromWeb and using -IncludedLists like below the output json does not include any AddNavLink actions

$adminUPN="user@domain.com"
$userCredential = Get-Credential -UserName $adminUPN -Message "Type the password."
$adminSiteUrl = "https://domain-admin.sharepoint.com"
$siteUrl = "https://domain.sharepoint.com/sites/FutureOptions/"
$Lists = "Shared Documents", "Lists/New Idea"

Connect-SPOService -Url $adminSiteUrl -Credential $userCredential

Get-SPOSiteScriptFromWeb -WebUrl $siteUrl -IncludeBranding -IncludeSiteExternalSharingCapability -IncludeRegionalSettings -IncludedLists ($Lists)

This is the case for all sites I have tried with.
There are no warnings or errors from the command. 

[FutureOptionsOutput.txt](https://github.com/MicrosoftDocs/office-docs-powershell/files/6960026/FutureOptionsOutput.txt)
![FutureOptionsQuickLaunch](https://user-images.githubusercontent.com/14795081/128832080-e966e645-bdc0-4b6b-8c90-6be2167e617f.PNG)

**Comment by get-itips** [comment]
Hello @JesperGSimonsen Jesper, how are you?
I could see that, will review if a note is necessary to the article for the cmdlet.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and updating the documentation with PR. @JesperGSimonsen Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
