### ISSUE TITLE
Teams private channel messages info missing

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/office-docs-powershell#8167]
Please provide the commands needed to work with retention compliance policies Teams private channel messages
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adaea894-fecc-16d3-0c4d-7971eda68b4b
* Version Independent ID: 4fe92cc7-84bf-2404-5481-4575b9d5d174
* Content: [Set-RetentionCompliancePolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-retentioncompliancepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-RetentionCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment]
Hi @ssmiller60, thank you for your feedback.

I understand that manage retention policy for Teams private channels is not available yet. And it seems that retention policies for Teams private channels were not fully rolled out yet:
https://www.microsoft.com/microsoft-365/roadmap?filters=In%20development%2CRolling%20out&searchterms=70582

**Comment by ssmiller60** [comment]
I am aware of the roadmap but please check a test azure environment, it has
been rolled out.  It is live in our prod GCC environment.

Thanks
Sam

**Comment by dariomws** [comment]
Hi @ssmiller60, it could be rolled out to several tenants, I agree. Anyway, not option to manage retention policies using the PowerShell module yet.

**Comment by ssmiller60** [comment]
Ok thanks for the clarification

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @ssmiller60 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
