### ISSUE TITLE
New-SPOSiteGroup arguments

### ISSUE THREAD

**Issue by simoniscasesensitive** [MicrosoftDocs/office-docs-powershell#817]
I appreciate the presence of a dedicated PowerShellcmdlet for this purpose, but dislike a few things about it.

-PermissionLevel shouldn't be a required property, I almost always create groups without permission to the root of a Site Collection, and use them later to assign access to a specific resource. Creating them and granting them a made-up near-zero permission is mucky.
- I need to be able to assign an Owner group, and set values for visibility and who is allowed to change membership.  Setting custom description text used to be straightforward and now isn't. 

These are the .Owner (only possible in Set-SPOSiteGroup), .Description, .AllowMembersEditMembership, and .OnlyAllowMembersViewMembership attributes on-premises.

**Comment by nsshommo** [comment]
@simoniscasesensitive Thanks for your feedback.

**Comment by simoniscasesensitive** [comment]
This is what I'm doing in CSOM right now, I think we can agree it'd be much easier if this was a switch on a standard CMDlet!
`
#Create new Group
$NewGroup = New-Object Microsoft.SharePoint.Client.GroupCreationInformation
$NewGroup.Title = $GroupName     
$NewGroup.Description = $DescriptionText
$Group = $clientContext.web.SiteGroups.Add($NewGroup)
$clientContext.ExecuteQuery()

write-host  -f Green "User Group" $GroupName "has been added"

# We've added a new group, and SPO is a bit of a gowl, so we'll have to refresh the list of groups each time
$ExistingGroups = $ThisWeb.SiteGroups
$clientContext.Load($ExistingGroups)
$clientContext.ExecuteQuery()

# Now get the new group and set Owner, visibility and who can add users
$NewlyCreatedGroup = $ExistingGroups | where {$_.Title -eq $GroupName}
$clientContext.Load($NewlyCreatedGroup)
$clientContext.ExecuteQuery()

$NewlyCreatedGroup.AllowMembersEditMembership = $false
$NewlyCreatedGroup.OnlyAllowMembersViewMembership = $false
$NewlyCreatedGroup.Owner = $GroupOwner
$NewlyCreatedGroup.Update()
$clientContext.ExecuteQuery()
`

**Comment by AndreaBarr** [comment]
@simoniscasesensitive Thank you for this feedback

We apricate your suggestion for SPO and I wan to make sure it gets the correct attention. 

I know the product teams are always looking for user feedback and how to make the OneDrive / SharePoint better. They keep a close tab on User Voice [https://sharepoint.uservoice.com](https://sharepoint.uservoice.com) and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too. 
 
Thank you for your contribution to make the docs better! Much appreciated!
