### ISSUE TITLE
EO cmdlet list needed

### ISSUE THREAD

**Issue by heidihendry** [MicrosoftDocs/office-docs-powershell#818]
I cam here looking for a list of Exchange Online cmdlets. I've clicked on various links but I keep going around in circles. Is there a List of Exchange Online cmdlets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceeb00d4-65da-0ea5-8089-f16a2f348eb7
* Version Independent ID: 0f4286f0-13dc-0f83-3943-4c51fd715f94
* Content: [Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nsshommo** [comment]
@heidihendry Thanks for letting us know your query. Very soon you will have your answer.

@chrisda Do you know who can help on this one?

**Comment by chrisda** [comment]
@heidihendry, we realize the current presentation of all Exchange-related cmdlets jammed together isn't ideal. We're working on a filtering method so when you arrive at https://docs.microsoft.com/powershell/exchange/ and select a workload (for example, Exchange Online), you'll only see the cmdlet topics and procedures that are related to that workload. We hope to have that working soon.

**Comment by RiskyRogue** [comment]
This was my bookmarked page for Exchange Online cmdlets.  Where have they gone?  A search hasn't produced anything useable. Seriously?

**Comment by chrisda** [comment]
@RiskyRogue, we discussed at great length the choice to eliminate the "bucket" or "link farm" topics that we used for Exchange cmdlet reference topics on TechNet. Actually, the choice was rather simple, because if we tried to split out the topics by audience on GitHub/docs.microsoft.com, we would have lost single-sourcing of the cmdlet reference topics (and there are ~500 cmdlets shared between on-premises Exchange and Exchange Online.

We're still working on a filtering method so when you arrive at https://docs.microsoft.com/powershell/exchange/, you can select Exchange Online so you'll only see the cmdlet topics and procedures that are related to Exchange Online. We hope to have that working soon.

Thanks for the feedback.

**Comment by Kristaf** [comment]
@chrisda, that all sounds good to me the only problem is when I navigate to the link you have provided and select Exchange Online PowerShell it takes me to a single page with no list of commands. Just this single page. https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell so where do we look for the commands?

**Comment by chrisda** [comment]
@Kristaf, the commands are available under the Reference dropdown that's present 'below the line' in the left-hand pane. There are no lists of commands.

**Comment by chrisda** [comment]
@salinao we made the decision to not maintain the static list topics of cmdlets. It was always part of the plan to have a filtering mechanism where you selected the version of Exchange, and the cmdlets under Reference were filtered based on that selection. But, we're having difficulty implementing that in a way that's compatible with the single-source nature of Exchange cmdlet topics that are shared between multiple versions. For example, if we wanted 6 copies of Get-User in 6 separate folders (and a 7th after Exchange 2019), it would have worked great. We're still working on it.

**Comment by nati0** [comment]
`$UserCredential = Get-Credential

$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection



$test = Import-PSSession $Session -DisableNameChecking

$Test.ExportedCommands`

**Comment by Jaguar83** [comment]
Links come straight back here. NOT FIXED!!!
