### ISSUE TITLE
-HiddenFromAddressListsEnabled

### ISSUE THREAD

**Issue by davidkench** [MicrosoftDocs/office-docs-powershell#8180]
-HiddenFromAddressListsEnabled
The HiddenFromAddressListsEnabled parameter specifies whether the Microsoft 365 Group appears in the global address list (GAL) and other address lists in your organization. Valid values are:

$true: The Microsoft 365 Group is hidden from the GAL and other address lists. The group can still receive messages, but users can't search for or browse to the group in Outlook or Outlook on the web. Users also can't find the group by using the Discover option in Outlook on the web. For users that are members of the Microsoft 365 Group, the group will still appear in the navigation pane in Outlook and Outlook on the web if HiddenFromExchangeClientsEnabled property is NOT enabled.
$false: The Microsoft 365 Group is visible in the GAL and other address lists. This is the default value.

Is this still the case?  I have read on some forums that this changed so $true is now the default?

Thanks.

David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80326e44-6beb-8983-57ab-8333608c504b
* Version Independent ID: 8962c0dc-72a3-208a-33de-6a89cd56b6fc
* Content: [Set-UnifiedGroup (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@davidkench, I tested in my regular ol' E5 tenant by creating a new public M365 Group and a new private M365 Group, in the M365 admin center (apparently, you can't create them in the new EAC) and the value of the _HiddentFromAddressListsEnabled_ property for both was `False`.

Perhaps I should just remove that "This is the default value" sentence?

**Comment by davidkench** [comment]
Hi Chris,

No, I think having tested, that does still hold true.  That is "false" is the default.

Thanks,

David

**Comment by chrisda** [comment]
@davidkench, OK. I removed the offending sentence.

Thanks for the feedback.

Closing
