### ISSUE TITLE
MeetingRecordingExpirationDays max value is incorrect

### ISSUE THREAD

**Issue by rimroot** [MicrosoftDocs/office-docs-powershell#8181]
The description for MeetingRecordingExpirationDays max value is incorrect. Max supported value is 9999. It does allow to set it higher, but then it completely breaks meeting policy and it does not even show the policy in Teams admin center with the error message. Moreover for all users who have this policy where MeetingRecordingExpirationDays max value set higher than 9999 "Calls" button disappears from teams client. Please update the description because we had an incident where "Calls" disappeared for users. By the way "Calls" button disappears only if user signs out and signs in, or clears Teams cache.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @rimroot 
How are you? Hope you are doing good.
I could get more information, setting this value currently is disabled.
Also please read here for more information https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#auto-expiration-of-teams-meeting-recordings

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @rimroot Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
