### ISSUE TITLE
New-DistributionGroup should applies to ExO as well.

### ISSUE THREAD

**Issue by naminakao** [MicrosoftDocs/office-docs-powershell#819]
"Applies to" section of New-DistributionGroup page does not have Exchange Online. I think New-DistributionGroup is available for Exchange Online too.

Page Title: New-DistributionGroup 
URL: https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/New-DistributionGroup?view=exchange-ps

**Comment by nsshommo** [comment]
@naminakao Thanks for your feedback. We are working on this and will let you know update very soon.

@Chrisda Do you know who can help me on this one?

**Comment by chrisda** [comment]
There appears to be a problem displaying the 'applicable' (topic) and 'Applicable' (parameter) values for 'Exchange Online' and 'Office 365 Security & Compliance Center'. The values are in the topics on GitHub, but they aren't displayed on docs.microsoft.com. We're looking into it.

**Comment by chrisda** [comment]
@naminakao, this issue has been fixed for all Exchange cmdlet reference topics. Thanks for your feedback.
