### ISSUE TITLE
Example how to aquire AccessTokens

### ISSUE THREAD

**Issue by BohrenAn** [MicrosoftDocs/office-docs-powershell#8194]
Hi there,

Could you please be more Specific on how to aquire the AccessTokens?
Preferably an Example with MSAL.PS.
Is it an Interactive Flow? How can we connect with a non interactive flow (apart from the -Credential Parameter) ?
If using the Credential Parameter is it still using Basic Auth?

#AzureAD
Connect-AzureAD -ApplicationId $AppID -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId
#ExchangeOnline
Connect-ExchangeOnline -AppID $AppID -CertificateThumbprint $CertificateThumbprint -Organization $TenantId
#MicrosoftTeams
Connect-MicrosoftTeams -ApplicationId $AppID -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId

Why was ApplicationID and CertificateThumbprint removed? Would be nice if there is some consistency across diffrent M365 PowerShell Modules.

Regards
Andres

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0dce05-8bfd-0bfa-3753-0eb193852703
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by stredoux** [comment]
https://get-itips.capazero.net/posts/teams-powershell-token-auth

**Comment by BohrenAn** [comment]
Thank's for the Link,
I know that one already. But here i have several Problems:

https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps 
 #Get MSGraph Token for following for resource  "https://graph.microsoft.com" and scopes "AppCatalog.ReadWrite.All", "Group.ReadWrite.All", "User.Read.All";
#Get Teams resource token for resource id "48ac35b8-9aa8-4d74-927d-1f4a14a0b239" and scope "user_impersonation";

In the Article https://get-itips.capazero.net/posts/teams-powershell-token-auth
He is stating, that he is using APPLICATION Permissions (Not mentioned in the Microsoft Docs)
"Directory.ReadWrite.All", "Directory.Read.All"

Also the Permissions "application_access_custom_sba_appliance" and "application_access" are APPLICATION Permissions.
That does not fit the Microsoft Docs Documentation

Obviously that's not right. As i am not able to Connect with that Code.

I am using MicrosoftTeams PowerShell Module 2.5.0
![Teams_AccessTokens_01](https://user-images.githubusercontent.com/45082822/129850917-1b6bbf95-ef61-472d-b3e7-00300ee7c7cb.jpg)
![Teams_AccessTokens_02](https://user-images.githubusercontent.com/45082822/129850922-754097e6-2f88-425b-aa02-f7c164b921f9.jpg)

Regards
Andres

**Comment by lazedo** [comment]
also trying `2.5.0`. when using `Connect-MicrosoftTeams  -AccessTokens @($GraphAccessToken , $TeamsAccessToken) -TenantId $tenant` i get `Not supported tenant type.` not sure if this is something that should work (working with office developer account) with the proper tenant

**Comment by rich2099** [comment]
I walso would like to add that the instructions for Connect-MicrosoftTeams with access tokens dont seem to work. Is this is bug or are the instructions not correct? The clarification about the exact permissions required in Graph and Skype & Teams API would be great as well.

**Comment by stredoux** [comment]
I have done some tests and its working on MictosoftTeams ver 2.3.2 [https://www.powershellgallery.com/packages/MicrosoftTeams/2.3.2-preview](url)

As its been documented .... Sample Code : 

`$tokenBody = @{  
   Grant_Type    = "client_credentials"  
   Scope         = "48ac35b8-9aa8-4d74-927d-1f4a14a0b239/.default"  
   Client_Id     = $clientId  
   Client_Secret = $clientSecret  
}   
$TeamsTokenResponse = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$tenantName/oauth2/v2.0/token" -Method POST -Body $tokenBody -ContentType "application/x-www-form-urlencoded"

$clientId = "<AppID>"  
$clientSecret = "<AppSecret>"  
$tenantName = "<TenandId or Domain>"  
$tokenBody = @{  
   Grant_Type    = "client_credentials"  
   Scope         = "https://graph.microsoft.com/.default"  
   Client_Id     = $clientId  
   Client_Secret = $clientSecret  

}   
$graphTokenResponse = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$tenantName/oauth2/token" -Method POST -Body $tokenBody -ContentType "application/x-www-form-urlencoded"

Connect-MicrosoftTeams -AccessTokens @($graphTokenResponse.access_token, $TeamsTokenResponse.access_token ) -AccountId $clientId -TenantId $tenantName`

**Comment by rich2099** [comment]
You shouldn't need the Tenant ID nor the Account ID with 2.5.0 correct? I believe JWT token has all that information within it. I think intention with 2.5.0 is that you simply need to perform `Connect-MicrosoftTeams -AccessTokens @($GraphAccessToken , $TeamsAccessToken)` assuming you have the successfully gathered the tokens, you should then be connected.

**Comment by stredoux** [comment]
As far as I could understand , If you need to add the Account Id of the person/application  you used to get the tokens , and if you use an application to authenticate they do request  an Tenant ...

**Comment by rich2099** [comment]
HI @yogkumgit , would you have any feedback for us on this?

**Comment by get-itips** [comment]
Hello @BohrenAn how are you?
I could get some information from the team that they are aware and a fix is planned.
Thank you

**Comment by fxlite** [comment]
Handling access tokens outside the module is fine, but they expire  after 1h by default. When it was built into the module, it handles re-acquisition for you as it already has all the info. It now means we have to write logic to handle expiring access tokens...

The changelog doesn't seem to indicate why passing appid and certificate thumbprint was removed in favour of static access token parameter.

**Comment by stredoux** [comment]
> Handling access tokens outside the module is fine, but they expire after 1h by default. When it was built into the module, it handles re-acquisition for you as it already has all the info. It now means we have to write logic to handle expiring access tokens...
> 
> The changelog doesn't seem to indicate why passing appid and certificate thumbprint was removed in favour of static access token parameter.

So when you run the command it does not want you to add the -accountid parameter : Connect-MicrosoftTeams -AccessTokens @($graphTokenResponse.access_token, $TeamsTokenResponse.access_token )

**Comment by paulbk914** [comment]
> > Handling access tokens outside the module is fine, but they expire after 1h by default. When it was built into the module, it handles re-acquisition for you as it already has all the info. It now means we have to write logic to handle expiring access tokens...
> > The changelog doesn't seem to indicate why passing appid and certificate thumbprint was removed in favour of static access token parameter.
> 
> So when you run the command it does not want you to add the -accountid parameter : Connect-MicrosoftTeams -AccessTokens @($graphTokenResponse.access_token, $TeamsTokenResponse.access_token )

I'm getting the same issue. I've retrieved access tokens successfully but the only parameter is allows when using -accesstokens is -TenantId. When I provide the tenant ID (i've tried both the tenant GUID as well as the tenant name), i get: Connect-MicrosoftTeams : Not supported tenant type.

**Comment by stredoux** [comment]
@fxlite @yogkumgit Any News on the above  ? When can we expect a fix ?

**Comment by get-itips** [comment]
> Hello @BohrenAn how are you?
> I could get some information from the team that they are aware and a fix is planned.
> Thank you

@yogkumgit As indicated here, I could get information from the team that, they are aware and planning a fix. We can close this for now.

**Comment by BohrenAn** [comment]
@get-itips 
I would still like to have a clarification about the needed Permissions and an example how to get the AccessTokens.

Regards Andres

**Comment by yogkumgit** [comment]
@BohrenAn Thank you for reporting this feedback here. If you would please open a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by stredoux** [comment]
@yogkumgit  We have been saying this since the start that there is a bug...... now after how many weeks we need to l;og a call to the support. Really .......

**Comment by rich2099** [comment]
I agree with @stredoux, someone @yogkumgit (?) should be able to confirm whether this is a documentation error or a bug. I have no case open with Microsoft on this.
