### ISSUE TITLE
There is no Get-SPTrustedIdentityProvider cmdlet

### ISSUE THREAD

**Issue by bbronisz** [MicrosoftDocs/office-docs-powershell#8195]
This document mentions Get-SPTrustedIdentityProvider cmdlet but it doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bc9b30-eb41-47b7-eae4-c427c2d8701a
* Version Independent ID: 71c48622-f832-8dff-a894-01e6eb298456
* Content: [Add-SPClaimTypeMapping (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/add-spclaimtypemapping?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Add-SPClaimTypeMapping.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Add-SPClaimTypeMapping.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks for reporting @bbronisz
