### ISSUE TITLE
TlsCertificateName: Let's Encrypt certificate - same issuer, same subject

### ISSUE THREAD

**Issue by jbostoen** [MicrosoftDocs/office-docs-powershell#8199]
I miss info on how to replace an expiring (Let's Encrypt) certificate with a new one using Set-SendConnector.

The TLSCertificateName parameter expects `<i>issuer<s>subject` ; but this is the same for the new certificate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0644aa0f-eb28-7812-8633-35616cb5b1c3
* Version Independent ID: f6d12f37-77ef-6e54-eb42-49deba407e20
* Content: [Set-SendConnector (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-sendconnector?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-SendConnector.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-SendConnector.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jbostoen, did you try to use the second method in the description?

>  Or, after you run **Get-ExchangeCertificate** to find the thumbprint value of the certificate, run the command `$TLSCert = Get-ExchangeCertificate -Thumbprint <Thumbprint>`, run the command `$TLSCertName = "<I>$($TLSCert.Issuer)<S>$($TLSCert.Subject)"`, and then use the value `$TLSCertName` for this parameter.

The Thumbprint value of the renewed certificate should be different than the expiring one.

**Comment by jbostoen** [comment]
@chrisda This works for the actual $TLSCert part, but it will result in the same issuer and same subject?

Is it possible to somehow specify the exact certificate or a thumbprint in the Set-SendConnector ?

**Comment by yogkumgit** [comment]
@chrisda

**Comment by chrisda** [comment]
@jbostoen, your best way forward is to open a support case. Report back here if any documentation updates are required.

**Comment by yogkumgit** [comment]
@jbostoen  Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
