### ISSUE TITLE
Connect-MicrosoftTeams -AccessTokens  not working

### ISSUE THREAD

**Issue by stredoux** [MicrosoftDocs/office-docs-powershell#8203]
Connect-MicrosoftTeams : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Connect-MicrosoftTeams -AccessTokens @($graphtoken, $teamstoken) -AccountId User@company.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-MicrosoftTeams], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams

**Comment by lazedo** [comment]
tried with `Connect-MicrosoftTeams -AccessTokens @($graphtoken, $teamstoken) -TenantId $tenant`, getting different error. https://github.com/MicrosoftDocs/office-docs-powershell/issues/8194#issuecomment-904567505

**Comment by get-itips** [comment]
Hello @stredoux 
please see https://github.com/MicrosoftDocs/office-docs-powershell/issues/8194#issuecomment-909343996

**Comment by Jeroen-G-JYZ** [comment]
Not solved in 2.5.2-preview.

> Hello @stredoux
> please see [#8194 (comment)](https://github.com/MicrosoftDocs/office-docs-powershell/issues/8194#issuecomment-909343996)

**Comment by get-itips** [comment]
@Jeroen-G-JYZ As said in the comment, the team is aware and working on it.
As here we are limited to documentation changes and improvements, we will need to close this issue for now.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @stredoux Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
