### ISSUE TITLE
Wrong max value for MeetingRecordingExpirationDays?

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/office-docs-powershell#8204]
MeetingRecordingExpirationDays: _"Specifies the number of days before meeting recordings will expire and move to the recycle bin. Value can be from 1 to 99,999 days."_

In our organization we set the value to maximum of 99999 and the change broke Teams meeting and chat functionality. We raised a ticked to MS support, and they instructed that the correct max value should be 9999. Changing that value in our policy fixed the issue. If it is truely so, perhaps the doc needs updating?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @ArttuArstila how are you?
Please read my comment here https://github.com/MicrosoftDocs/office-docs-powershell/issues/8181#issuecomment-900555657

**Comment by ArttuArstila** [comment]
Thanks. So it was mistakenly enabled to be modifiable by Microsoft too early?

**Comment by get-itips** [comment]
Hello @ArttuArstila I do not know at that level of detail, I am sorry, however, when it will be enabled again it should be as the article says currently if for some reason the behavior is different I'll push a change to the article. Thanks for your feedback.

**Comment by ArttuArstila** [comment]
Got it, thanks for investigating!
