### ISSUE TITLE
Missing Set-CsUser command?

### ISSUE THREAD

**Issue by 2ndcahl** [MicrosoftDocs/office-docs-powershell#8205]
It seems that the Microsoft Teams command Set-CsUser is not documented. I know that it shares it's name with the Skype for Business command and they do (more or less?) the same thing, but I would still expect to see it listed in the commands for the MicrosoftTeams PowerShell module.

Or am I missing the reason for the Set-CsUser not to be in the Teams Microsoft documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6804423b-8e08-5916-9355-6bebe8bb08b0
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [MicrosoftTeamsPowerShell Module](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @2ndcahl how are you?
Hope you are doing good.
Thanks for your feedback. We are aware of the cmdlet not listed there, that index is automatically generated from the cmdlets that are in the Teams folder, that is the reason you will find it here https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps instead. 
Thanks for your feedback.

**Comment by 2ndcahl** [comment]
Thanks for your response @get-itips 
I'm simply confused about not seeing Set-CSUser as part of the Teams module documentation, as the command is part of the Teams module.

**Comment by get-itips** [comment]
Yes, but please remember that `Set-CsUser` belonged to the Skype module that is the reason the article is on that folder, probably in the future if the content is re-structured it will be listed in that index file.
thank you!
