### ISSUE TITLE
Missing SMTP information

### ISSUE THREAD

**Issue by useyourblinker** [MicrosoftDocs/office-docs-powershell#8206]
Dear Microsoft,

Does this Allow list match the email Header or Envelope, or "either" or "both"?

It would seem like - just as for a transport rule you might want to match an Envelope (and not the header) when making exceptions - you'd want to know in this case that the Envelope is doing the work. Else if it's the header - shouldn't that at least be listed someplace?

Generally DMARC should take care of this in spoofing circumstances, but phishers can be very tricky. It would be useful to at least understand where this is 'matching' the email address.

Some clarity here would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba41cae3-da51-0a3d-1652-bce98452d4dc
* Version Independent ID: a2d20c87-6277-a868-3c2e-e2fe225e6f17
* Content: [Set-ExternalInOutlook (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-externalinoutlook?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-ExternalInOutlook.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-ExternalInOutlook.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@useyourblinker, checking.

**Comment by chrisda** [comment]
@useyourblinker, it's the email header address, a.k.a. 5322.From, From, P2 sender, etc.

I updated the parameter description accordingly.

Thanks, for the feedback.

Closing.
