### ISSUE TITLE
New-PnPPersonalSite

### ISSUE THREAD

**Issue by jakerobinson** [MicrosoftDocs/office-docs-powershell#8208]
There is no `New-PnPPersonalSite` cmdlet, and this seems like a duplicate of the cmdlet `Get-PnPPersonalSite` and `Request-PnPPersonalSite`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a754d47-ac07-fef3-614c-1f9fc1c7a68f
* Version Independent ID: 69d2df01-0d5c-88b6-cc18-ca1e2c67f8e4
* Content: [New-PnPPersonalSite (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnppersonalsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPPersonalSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/New-PnPPersonalSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hellol @jakerobinson 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by jakerobinson** [comment]
Will do, thanks!

**Comment by jakerobinson** [comment]
Out of curiosity, how would I have known to submit this in the other repo? I now have to resubmit the same request in another repo, doubling the time I've spent reporting a bug. Please don't interpret this as me being angry, I would just like to help improve your processes! :heart:
