### ISSUE TITLE
Add-PnpJavascript Enhancement Request

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/office-docs-powershell#821]
Would it be possible to add an additional scope to these two commands so javascript could be injected into a single web page?  Add-PnPJavaScriptLink; Add-PnPJavaScriptLink

**Comment by nsshommo** [comment]
@robertcaretta Thanks for your question. We will get back with your answer very soon.

**Comment by VesaJuvonen** [comment]
We do understand the business scenario behind of this request, but this is unfortunately not possible as these cmdlets add JavaScript to Web.UserCustomAction or Site.UserCustomActions collections depending on the defined scope. There's no similar collection in the page level, which could be used to identify the JavaScript file only to be rendered in a single page. You can, however, add simple if statement on your JavaScript file which is either in Site or Web scope and execute the actual business logic when the end user is on a specific page.
