### ISSUE TITLE
Add-TeamChannelUser cmdlet no longer exists in module MicrosoftTeams

### ISSUE THREAD

**Issue by andyp081** [MicrosoftDocs/office-docs-powershell#8212]
I'm running v2.5.0 of the MicrosoftTeams module which appears to have had the Add-TeamChannelUser cmdlet removed. [MS documentation](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps) indicates it was in one of their previous versions. 

Is there another cmdlet that's replaced Add-TeamChannelUser to add a user (or owner) to private teams channels?

**Comment by discocow** [comment]
There seem to be several cmdlets missing - I'm also not able to access  set-TeamTargetingHierarchy or  Get-TeamTargetingHierarchyStatus which should be in the same module. Current MS [documentation ](https://docs.microsoft.com/en-us/microsoftteams/set-up-your-team-hierarchy) references them but they aren't recognized in 2.5

**Comment by andyp081** [comment]
I've downgraded to module v2.4.1 preview that's allowed me access to the *TeamChannelUser & *TeamTargetingHierachy* cmdlets.

Just ran these 2 commands
1. Uninstall-Module -name MicrosoftTeams -allversions -confirm -force
2. Install-Module -Name MicrosoftTeams -RequiredVersion 2.4.1-preview -AllowPrerelease

After installing v2.4.1 preview

PS C:\WINDOWS\system32> get-command -module MicrosoftTeams -noun *TeamTargetingHie*,teamchanneluser

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-TeamChannelUser                                 2.4.1      MicrosoftTeams
Cmdlet          Get-TeamChannelUser                                  2.4.1      MicrosoftTeams
Cmdlet          Get-TeamTargetingHierarchyStatus              2.4.1      MicrosoftTeams
Cmdlet          Remove-TeamChannelUser                          2.4.1      MicrosoftTeams
Cmdlet          Remove-TeamTargetingHierarchy                2.4.1      MicrosoftTeams
Cmdlet          Set-TeamTargetingHierarchy                        2.4.1      MicrosoftTeams


> There seem to be several cmdlets missing - I'm also not able to access set-TeamTargetingHierarchy or Get-TeamTargetingHierarchyStatus which should be in the same module. Current MS [documentation ](https://docs.microsoft.com/en-us/microsoftteams/set-up-your-team-hierarchy) references them but they aren't recognized in 2.5

**Comment by get-itips** [comment]
Hello @discocow how are you?
`Add-TeamChannelUser` is part of the `-Preview` branch of the Teams Ps module, as the article says.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @andyp081 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
