### ISSUE TITLE
Nested Objects display differently depending how Auto Attendant was queried

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#8217]
Hello,

I have found a peculiar bug in `Get-CsAutoAttendant` - When querying Auto Attendants by Name, the output is different than when queried by ID:

```powershell
❯ $AA = Get-CsAutoAttendant -Name "AA Reception"         

❯ $AA


Identity                        : 4948bc16-2f42-48b0-8195-8efa5c6e3505
TenantId                        : 73bc6539-b4fe-429c-97b6-fbc1b6ada80b
Name                            : AA Reception
LanguageId                      : nl-NL
VoiceId                         : Female
DefaultCallFlow                 : AA Reception Default call flow
Operator                        :
TimeZoneId                      : W. Europe Standard Time
VoiceResponseEnabled            : False
CallFlows                       : AA Reception After hours call flow
Schedules                       : Business Hours Schedule
CallHandlingAssociations        : AfterHours(1)
Status                          :
DialByNameResourceId            :
DirectoryLookupScope            :
ApplicationInstances            : {8646edc5-b788-4e3c-80b8-95e9b9903152}
GreetingsSettingAuthorizedUsers : {}


❯ $AA.CallFlows.Greetings.AudioFilePrompt | FL *


IsAudioFileAlreadyUploaded : True
Id                         : b89575250ce64722830b8eaa7071a56f
MarkedForDeletion          : False
FileName                   :
Content                    :
DownloadUri                :
ApplicationId              :
IsInvokedByTenantAdmin     : False


❯ $AA = Get-CsAutoAttendant 4948bc16-2f42-48b0-8195-8efa5c6e3505

❯ $AA.CallFlows.Greetings.AudioFilePrompt | FL *


IsAudioFileAlreadyUploaded : True
Id                         : b89575250ce64722830b8eaa7071a56f
MarkedForDeletion          : False
FileName                   : voicemail.mp3
Content                    :
DownloadUri                : https://prd00noameussbmsstr001.blob.core.windows.net/73ad6539b4fe429c98b6fbc1b6ada80b/b89575250ce64722830b8eaa7071a56f?sv=2015-12-11&sr=b&sig=tZ%2FjsEe 
                             FtKnVOVEaszNO0RfK2Td9ZpWBMVaEvEPcfKg%3D&se=2021-08-20T12%3A47%3A41Z&sp=r
ApplicationId              :
IsInvokedByTenantAdmin     : False

```
Parameters Filename and DownloadUri do not show properly when queried by name, but work fine if queried by ID

I am after the DownloadUri for my use-case (`Get-TeamsAutoAttendant -Detailed` and `Get-TeamsAutoAttendantAudioFile` respectively). There is no option to download an existing Audio File in the Admin Center btw...

Thanks,
David

PS: Since this is from a Customers tenant of mine, I have changed the GUIDs for Id,Tenant, DownloadUri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8eda0b1-3667-3124-946f-bbc581120725
* Version Independent ID: 450eaa1b-b14b-c248-790e-13eb583e434b
* Content: [Get-CsAutoAttendant (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsAutoAttendant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsAutoAttendant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DEberhardt 
I tried that, and if I specify -IncludeStatus, the information you are looking for, is there:

![image](https://user-images.githubusercontent.com/36666927/131547262-33379254-9952-4862-b918-a1e990eb331c.png)

This is with `2.5.1`.

Hope this helps you,

**Comment by DEberhardt** [comment]
Interesting. Something is definitely amiss here then:
```powershell
❯ $AA1 = Get-CsAutoAttendant -NameFilter 'AA Reception'
❯ $AA2 = Get-CsAutoAttendant -NameFilter 'AA Reception' -IncludeStatus

❯ $AA1.CallFlows.Greetings.AudioFilePrompt | FL *

IsAudioFileAlreadyUploaded : True
Id                         : 40acaf2d8cf748f882ab93d6b2b63b17
MarkedForDeletion          : False
FileName                   :
Content                    :
DownloadUri                :
ApplicationId              :
IsInvokedByTenantAdmin     : False

❯ $AA2.CallFlows.Greetings.AudioFilePrompt | FL *

IsAudioFileAlreadyUploaded : True
Id                         : 40acaf2d8cf748f882ab93d6b2b63b17
MarkedForDeletion          : False
FileName                   : voicemail.mp3
Content                    :
DownloadUri                : https://prd00noameussbmsstr001.blob.core.windows.net/73ad6539b4ab429c97b6fbc1b6ada80b/40ac
                             af2d8cf748f882ab93d6b2b63b17?sv=2015-12-11&sr=b&sig=h9Fu6SwuS0Z4FA36lIrY%2Fn4%2BxjvJ8vUtOp
                             ch%2BD5APIo%3D&se=2021-08-31T21%3A14%3A47Z&sp=r
ApplicationId              :
IsInvokedByTenantAdmin     : False
```
so far so good.... but:

```powershell
❯ $AA3 = Get-CsAutoAttendant -Identity $AA1.Identity
❯ $AA4 = Get-CsAutoAttendant -Identity $AA1.Identity -IncludeStatus
Parameter set cannot be resolved using the specified named parameters.
    + CategoryInfo          : InvalidArgument: (:) [Get-CsAutoAttendant], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Rtc.Management.Hosted.OAA.V2.GetCsAaCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

❯ $AA3.CallFlows.Greetings.AudioFilePrompt | FL *

IsAudioFileAlreadyUploaded : True
Id                         : 40acaf2d8cf748f882ab93d6b2b63b17
MarkedForDeletion          : False
FileName                   : voicemail.mp3
Content                    :
DownloadUri                : https://prd00noameussbmsstr001.blob.core.windows.net/73ad6539b4ab429c97b6fbc1b6ada80b/40ac
                             af2d8cf748f882ab93d6b2b63b17?sv=2015-12-11&sr=b&sig=ozNTSkJ1c5kcaQUewTYj%2FWeVuWYG%2FGZu8f
                             nGdRmvNGs%3D&se=2021-08-31T21%3A04%3A30Z&sp=r
ApplicationId              :
IsInvokedByTenantAdmin     : False
```

I am concluding from this, that:
- Querying with -Identity always runs `-IncludeStatus`(?)
- Querying with -NameFilter only returns the status if you run it with `-IncludeStatus`
- The [Parameter] Inizialisation for `-IncludeStatus` does not include a Line for the ParameterSet for Identity?

**Comment by get-itips** [comment]
@DEberhardt I see, however, hopefully, if you use `Identity` you do not need `IncludeStatus`

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DEberhardt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DEberhardt** [comment]
As Uservoice is no longer active, I had opened a ticket in the tenant regarding this.
The engineer directed me to the Feedback Hub inside the tenant to report these issues, so I have.
If anything comes of this, I will open another issue to propose documentation changes.
