### ISSUE TITLE
[BUG] [SP MgntShell] Additions to this Web site have been blocked

### ISSUE THREAD

**Issue by mikeparkie** [MicrosoftDocs/office-docs-powershell#8219]
I orginainly posted in here but did get any response, please let me know if you want me to raise with support: 
https://www.reddit.com/r/sharepoint/comments/oqtl1d/sp_mgntshell_additions_to_this_web_site_have_been

I'm after some advice on how to handle this error. The error occurs because the original site was renamed, so it's a redirect site template. I get the following error when pulling the site urls directly into a variable and setting the site collection admin.

```
Adding Site Collection Admin for: https://tenant.sharepoint.com/sites/sitename
Set-SPOUser : Additions to this Web site have been blocked.
Please contact the administrator to resolve this problem.
At line:4 char:5
Set-SPOUser -Site $Site -LoginName $Account -IsSiteCollectionAdmi ...
CategoryInfo : NotSpecified: (:) [Set-SPOUser], ServerException
FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.SetSP
```
The command
`Connect-SPOService http://tenant-admin.sharepoint.com
$Sites = Get-SPOSite -Limit ALL
Foreach ($Site in $Sites)
{
Write-host "Adding Site Collection Admin for:" $Site.URL
Set-SPOUser -Site $Site -LoginName $Account -IsSiteCollectionAdmin $True
}`

Although it errors, running Get-PnPSiteCollectionAdmin shows me it has indeed added the account to the site collection admins anyway. I didn't want the noise in the logs.

**Comment by get-itips** [comment]
Hello @mikeparkie Mike, how are you? Hope you are doing good.
Tested this and I could repro with the latest version of the SP Mgmt Shell, however, here, we are limited to documentation fixes and improvements. What you could do is filter the Get-SPOSite like this

`get-sposite -limit ALL | ?{$_.Template -ne "RedirectSite#0"}`

Hope this helps you,

**Comment by mikeparkie** [comment]
Thanks @get-itips, I'm good thanks. I appreciate you taking the time to respond. I agree, I could filter it out as suggested, but I believe it's a bug. I'll raise a support ticket so the PG gets the feedback.
