### ISSUE TITLE
New-Label -ExternalSharingControlType broken

### ISSUE THREAD

**Issue by mhupfauer** [MicrosoftDocs/office-docs-powershell#8226]
Creating new labels via PowerShell results in failures when trying to set the ExternalSharingControlType to ExternalUserAndGuestSharing as per documentation.

```powershell
Encountered exception: Microsoft.Exchange.Management.UnifiedPolicy.InvalidSiteLabelSettingValueException: SiteLabel setting key 'ExternalSharingControlType' has an invalid value 'externaluserandguestsharing'
   at Microsoft.Office.CompliancePolicy.Validators.LabelValidator.ValidateContainerLabelSiteSettings(LabelAction action, OrganizationId organizationId, UnifiedPolicyCmdletLogger cmdletLogger, Boolean isUnm
anagedDeviceAccessSet, Boolean isE5Tenant, List`1 protectionLevels)
   at Microsoft.Office.CompliancePolicy.Validators.LabelValidator.ValidateSiteSettings(LabelAction action, OrganizationId organizationId, UnifiedPolicyCmdletLogger cmdletLogger, Boolean isE5Tenant, List`1 
protectionLevels, Nullable`1 isEnableValidationsOfContainerLabelProtectSite, Nullable`1 isNewLabelActionValidationsEnabled)
   at Microsoft.Office.CompliancePolicy.Tasks.NewLabel.InternalValidate()
```

**Comment by LudwigVanGysel** [comment]
We have the same issue at one of our customers. We confirm this behavior also on the development tenant.

**Comment by chrisda** [comment]
@mhupfauer, @LudwigVanGysel your best bet is to open a support case. If this is a transient problem, then no updates to documentation are required. If the support case reveals something that should be noted in the documentation, report back here.

**Comment by yogkumgit** [comment]
@mhupfauer  Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
