### ISSUE TITLE
Get-Team doesn't always return all teams

### ISSUE THREAD

**Issue by ACarlockAKA** [MicrosoftDocs/office-docs-powershell#8227]
We have 2666 teams according to admin.teams.microsoft.com.  When I run Get-Team | export-csv .\TeamsReport.csv -notypeinformation I only get about 2662 teams.  Sometimes more, sometimes less.  the same happens even if I just run Get-Team and copy/paste the results from the PowerShell screen into Notepad or Excel where I can count the output.  This seems like a bug.

**Comment by get-itips** [comment]
Hello @ACarlockAKA Alex, how are you?
Here, we are limited to documentation changes and improvements, I'll try to pass the message.
Thanks

**Comment by yogkumgit** [comment]
@ACarlockAKA Thank you for reporting this feedback here. This list is focused on content issues and I want to make sure your immediate product issue does not get lost in this list. If you would please open a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
