### ISSUE TITLE
Label type?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#8228]
There are several types of labels in O365, I'm assuming that this is for Retention labels but this is not explicitly stated. Please update the text to make the type of label unambiguous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d96eadd-522c-fed2-d867-aae9596b5371
* Version Independent ID: 561744f4-8bef-38a4-fccd-4aff02175e8d
* Content: [Get-ComplianceTag (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-compliancetag?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-ComplianceTag.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-ComplianceTag.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DeanGross, you're right, it's retention labels. I updated the description in this and the other \*-ComplianceTag cmdlet topics.

Thanks for the feedback.

Closing.
