### ISSUE TITLE
SharePoint module bug

### ISSUE THREAD

**Issue by NunzioArdi** [MicrosoftDocs/office-docs-powershell#8229]
When i user this command, It tells me `False` while the person is well admin.
```Powershell
(Get-SPOUser -Site 'https://contoso-my.sharepoint.com/personal/username_contoso_com' -LoginName 'username2@consoto.com').IsSiteAdmin
```
Visible on this page, https://contoso-admin.sharepoint.com/_layouts/15/TenantProfileAdmin/ProfMngr.aspx
In **Manage site collection owners** as describedhere: https://docs.microsoft.com/en-us/sharepoint/manage-user-profiles#add-and-remove-admins-for-a-users-onedrive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e45fe794-97e2-c5c0-ebed-a6f46ae39624
* Version Independent ID: 3e502565-ef4a-989c-d020-ca5a55011f3e
* Content: [Intro to SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/introduction-sharepoint-online-management-shell?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/introduction-sharepoint-online-management-shell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/introduction-sharepoint-online-management-shell.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @NunzioArdi 
How are you?
Here, we are limited to documentation fixes and improvements. However, I tried to reproduce but couldn't

![image](https://user-images.githubusercontent.com/36666927/131377056-eba07ce8-8ef1-4c40-8ddc-73bf20c7c945.png)

Let me know if I understood you well.

Thanks

**Comment by NunzioArdi** [comment]
Hello @get-itips 
Sorry but I didn't find where to go to report a bug.
Could you please tell me? Thanks

**Comment by get-itips** [comment]
Hello @NunzioArdi If you still face that with the latest version of the module you could try opening a support request from your tenant. Hope this information helps you.

**Comment by NunzioArdi** [comment]
Hello @get-itips The problem only occurs for disabled accounts. The change is effective but the command returns False.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @NunzioArdi Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
