### ISSUE TITLE
Set-SPOSite : You do not have required licenses to perform this operation. Please read here for licensing related requirements :  https://docs.microsoft.com/en-US/sharepoint/authentication-context-example

### ISSUE THREAD

**Issue by aspnet4you** [MicrosoftDocs/office-docs-powershell#8236]
I am try run Set-SPOSite to set ConditionalAccessPolicy AuthenticationContext on SharePoint site but I am receiving the following error-

"Set-SPOSite : You do not have required licenses to perform this operation. Please read here for licensing related requirements :  https://docs.microsoft.com/en-US/sharepoint/authentication-context-example"

I am using a user with Global Admin role in Azure AD and Microsoft 365 E5 Developer (without Windows and Audio Conferencing) valid license. Interestingly, I used the same account and ran the same command about a month ago and it was working then!

I do think I have the proper license and it was working just fine. Any idea what may have changed with Set-SPOSite?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c62bf4a-ac47-96ce-33fb-0d5ea9b178ae
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by aspnet4you** [comment]
@yogkumgit- any update on this issue?

**Comment by aspnet4you** [comment]
This issue has been resolved, I can use set-sposite command with Microsoft 365 E5 Developer (without Windows and Audio Conferencing) license. This issue can be closed.

Just to share the info, I have stayed away from using authentication context as it impacted other processes and  Microsoft is yet to catch up with the impacted resources.

**Comment by ictjobi** [comment]
Similar to @ostolawork, I've attempted to run...

`Set-SPOSite -Identity https://[mytenant].sharepoint.com/sites/[mysite] -BlockDownloadPolicy $true -ExcludeBlockDownloadPolicySiteOwners $true`

...but am continually receiving the 'You do not have required licenses to perform this operation' error.

I've attempted to run this query with an unlicensed / E3 licensed / E5 licensed Global Admin account, and have left days between running the query after each license change but still my query fails. As well, I've installed the latest version of Microsoft's SharePoint PowerShell module on a second device but this hasn't fixed the issue.

@yogkumgit, sorry to drag up an old thread but are you able to share any information or advice regarding this issue please?

Thank you in advance 👍
