### ISSUE TITLE
Set-SPOTenant -DisableAddShortcutsToOneDrive - Still warning for public preview?

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/office-docs-powershell#8237]
If this command is now in General Access then the warning message about Public Preview should be removed/amended.

_PS C:\WINDOWS\system32> Set-SPOTenant -DisableAddShortcutsToOneDrive $True
WARNING: Users in your organization will no longer be able to add new shortcuts to their OneDrive while the feature is in Public Preview. However, existing shortcuts will remain functional._

**Comment by get-itips** [comment]
Hello @angoo-atea how are you?
I could get the information that the message is going to be removed soon from the cmdlet output.
Other than that, as here we are limited to documentation fixes @yogkumgit you can close this.
Thanks for the feedback!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @angoo-atea Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
