### ISSUE TITLE
-ProfileDBServer Definition is Incorrect

### ISSUE THREAD

**Issue by Patrick-Gaul** [MicrosoftDocs/office-docs-powershell#8243]
This page has an incorrect definition of the **-ProfileDBServer** parameter. It describes it as a database name. It should be a Server name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96316135-abf3-c1b7-e01f-0942874efde7
* Version Independent ID: c859a385-3067-a82c-ff7e-1bfb389ee12b
* Content: [New-SPProfileServiceApplication (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spprofileserviceapplication?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPProfileServiceApplication.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPProfileServiceApplication.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks for your feedback @Patrick-Gaul
