### ISSUE TITLE
Folder where the message was delivered

### ISSUE THREAD

**Issue by badsector-82** [MicrosoftDocs/office-docs-powershell#8245]
Get-MessageTraceDetail | Where {$_.Event -eq "Deliver"} returns "The message was successfully delivered." as a value for the "Detail" attribute. But this doesn't state to which folder the message was delivered. Is it right to assume that this value say the message was delivered to Inbox? If I sent a spam message it says "The message was delivered to the Junk Email folder". Please confirm this in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690f2980-4a4e-7efd-fe5e-29c551c02e6f
* Version Independent ID: 4ab7a6db-db36-c736-6ce5-2f0e74b0cf6a
* Content: [Get-MessageTraceDetail (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-messagetracedetail?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MessageTraceDetail.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MessageTraceDetail.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@badsector-82, I don't think the level of detail extends to specific folders within the mailbox. For example, spam messages are first delivered to the Inbox, and then moved into the Junk Email folder by the hidden Inbox rule named Junk E-mail Rule (as long as the rule is enabled).

You can also configure Inbox rules to move messages with certain characteristic to a designated folder, or even delete the message. But even then, the message is delivered to the Inbox before being moved or deleted.

So, yeah, I would say "The message was successfully delivered" means the message was delivered to the Inbox. What happens after that, message trace can't tell. If you would like a definitive answer, I would suggest opening a support case.

**Comment by yogkumgit** [comment]
@badsector-82 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
