### ISSUE TITLE
Get-MigrationUser -status IncrementalFailed is missing in the documentation

### ISSUE THREAD

**Issue by rsedlacz** [MicrosoftDocs/office-docs-powershell#8246]
Get-MigrationUser -status IncrementalFailed
is missing from the list of Microsoft.Exchange.Data.Storage.Management.MigrationBatchStatus values

Get-MigrationUser -status IncrementalFailed

`Get-MigrationUser -status IncrementalFailed

Identity                                 Batch                          Status                    LastSyncTime
--------                                 -----                          ------                    ------------
uwe.egly@tuwien.ac.at                    Move-users-DAG1-1              IncrementalFailed         25.08.2021 15:06:09`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d404737-9599-a21f-41f1-d31a0baa4fe6
* Version Independent ID: 440c9461-7510-e9bd-6d6c-ddd8fa2d06b4
* Content: [Get-MigrationBatch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@rsedlacz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
