### ISSUE TITLE
Single user not found

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#8252]
Having trouble setting DistributionList / User attributes

Every time I attempt to set these values, I get an error like

Single user not found (9ff75dfd-dfd9-4a1d-b75b-205f26cc3303).
    + CategoryInfo          : NotSpecified: (:) [Set-CsCallQueue], OnlineCmdletException
    + FullyQualifiedErrorId : Unspecified,Microsoft.Rtc.Management.Hosted.CallQueue.SetCsCallQueueCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

Even something as simple as this does not work

$o = Get-CsCallQueue -Identity "a9af4823-f9ca-47e7-99a7-6caea2b9f563" | Select Users
Set-CsCallQueue -Identity "a9af4823-f9ca-47e7-99a7-6caea2b9f563" -Users $o.Users

I've Googled this and the examples I find aren't real world examples, unless you are expected to build the entire array from scratch even if you want to add/delete a single user/group.

I've followed similar syntax to the below for other array parameters in other cmdlets

$o = Get-CsCallQueue -Identity "a9af4823-f9ca-47e7-99a7-6caea2b9f563" | Select DistributionLists
$o.DistributionLists.Remove([GUID]"536f8ddc-8321-419c-b1d5-29f45ccfccaa")
Set-CsCallQueue -Identity "a9af4823-f9ca-47e7-99a7-6caea2b9f563" -DistributionLists $o.DistributionLists

I've tried this in 2.3.1 and 2.5.0 with neither version working

What am I doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ade68d-5dc0-c598-a659-8b018cef3e26
* Version Independent ID: 67efa086-edb0-2828-cc14-4c245290e4f3
* Content: [Set-CsCallQueue (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @sarollins 
How are you? I tested what you are trying to achieve in version `2.5.1`:

```
$cq=Get-CsCallQueue -Identity 56088345-3fb8-423f-b95b-f2ccb039a645 | select users
$cq.Users.Remove([GUID]"a4ff1388-0d20-4e03-abab-9a0798b7e33c")
Set-CsCallQueue -Identity 56088345-3fb8-423f-b95b-f2ccb039a645 -Users $cq.Users
```

and I could successfully remove a user from the list of users

Let me know if I understood you well. Thanks

**Comment by get-itips** [comment]
> How about a DistributionList?

I could also use the same procedure for DLs

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
