### ISSUE TITLE
New-CsGroupPolicyAssignment -PolicyType TeamsAppPermissionPolicy missing

### ISSUE THREAD

**Issue by Rowdy** [MicrosoftDocs/office-docs-powershell#8256]
We are rolling out Teams slowly and created a couple of different Teams App Permission Policies. Unfortunately these groups can not be assigned to groups via the New-CsGroupPolicyAssignment.

I guess this is a problem for a lot of companies which are using multiple Permission Policies within their company.

**Comment by get-itips** [comment]
Hello @Rowdy how are you?
Here, we are limited to documentation fixes and improvements, your inquiry I think is best suited for https://microsoftteams.uservoice.com/
Thank you

**Comment by yogkumgit** [comment]
@Rowdy  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
