### ISSUE TITLE
DatacenterAdminsOnly info missing

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/office-docs-powershell#8257]
info on the field DatacenterAdminsOnly is missing.  This is defaulted to false, what does true mean and how is it set?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43667016-c662-727c-4566-9356330b0665
* Version Independent ID: decd796f-a731-2289-87d7-ee173788025c
* Content: [New-ClientAccessRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-clientaccessrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ClientAccessRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ClientAccessRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ssmiller60, are you talking about the DatacenterAdminsOnly **property** in the output of Get-ClientAccessRule (or the "here's what you just did" output of New-ClientAccessRule)? If so, there are a couple of issues:

1. Typically, we don't document the properties that are shown in the output of a Get cmdlet. The list of properties is:
   - Too volatile (changes frequently).
   - Is full of properties that don't correlate to user-configurable parameters in the corresponding New/Set cmdlets. This is particularly true in Microsoft 365 (cloud) environments.

   The only exception to this rule is reporting cmdlets. We try to document the full output of those.

2. This doesn't happen too often, but the actual name of this parameter would indicate that this property isn't meant to be user-configurable.

I just checked an E5 tenant, and New-ClientAccessRule and Set-ClientAccessRule don't have a visible parameter named DatacenterAdminsOnly.

So, I'll state that there's nothing to document

**Comment by yogkumgit** [comment]
@ssmiller60 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
