### ISSUE TITLE
New-TenantAllowBlockListItems: A parameter cannot be found that matches parameter name 'action'

### ISSUE THREAD

**Issue by phlakvest** [MicrosoftDocs/office-docs-powershell#8258]
It appears -action isn't a valid parameter.  I can add -block, but I don't see any way to add an allow entry.

**Comment by get-itips** [comment]
Hello @phlakvest 
Please see here https://docs.microsoft.com/en-us/powershell/module/exchange/new-tenantallowblocklistitems?view=exchange-ps that an `-Allow` parameter is available.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @phlakvest Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
