### ISSUE TITLE
Commands missing from MicrosoftTeamsPowershell

### ISSUE THREAD

**Issue by HorridMutilation** [MicrosoftDocs/office-docs-powershell#8259]
Get-Command -module microsoftteams does not return Add-TeamChannelUser yet the cmdlet is listed here
https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps

This is with the latest version, 2.5.0

It seems this was an issue in the past as well
https://github.com/MicrosoftDocs/office-docs-powershell/issues/6549

**Comment by get-itips** [comment]
@HorridMutilation How are you? That cmdlet is part of the -Preview branch of the Teams PowerShell module. (the ones identified with -preview in the module version)
Hope this information helps you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @HorridMutilation Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
