### ISSUE TITLE
Get-CsTenant with v2.5.0 - Output object changed - Parameters lost?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#8260]
Hello,

with v2.5.0 of MicrosoftTeams, the output was refactored. While I welcome the switch to the AutoRest query, I lament the lost of backwards compatibility.
> Modernized versions of Get-CsTenant and Get-CsOnlineUser (with -identity parameter only) have been released. They no longer emit deprecated properties and have some formatting changes compared to their remoting counterparts.

- [ ] How to query this with the `Identity` Switch? - This does not work for me... 
Furthermore, I do not want to use the Switch, I want to query the output for the currently connected tenant only.
- [ ] How to query this without the `Identity` Switch? - The statement above does not work for this command.
Calling it without any switches will result in the new Object being displayed. How does one now receive the legacy output?
- [ ] Parameter `LastSyncTimeStamp` was interesting for troubleshooting DirSync issues. What should replace this now?
Where could I query this information now from (with the modules AzureAd/AzureAdPreview or MicrosoftTeams)?
- [ ] Parameter `Identity` changed - I used this to query the `HostedMigrationOverrideURL` which does not seem to be needed any longer? can I safely retire it?

Thank you,
David

Track & Link: https://github.com/DEberhardt/TeamsFunctions/issues/95

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b281face-3456-9f04-2a49-21e46f33272f
* Version Independent ID: e62b6323-aba4-5286-70f0-fcccd8cf23be
* Content: [Get-CsTenant (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-cstenant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTenant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DEberhardt David.

I think the `(with -identity parameter only)` comment that you extracted from the release notes, is only about the `Get-CsOnlineUser` cmdlet, but I'll try to confirm.

I understand what you say about the parameters or information now gone, however, that seems more suitable for [uservoice](https://microsoftteams.uservoice.com/) as here we are limited to documentation changes and improvements.

Please let me know if I understood you correctly.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DEberhardt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DEberhardt** [comment]
Uservoice is no longer open for Teams. Through an incident raised in the tenant, I was instructed to use the Feedback hub inside the tenant to report this, as it goes to the design team rather than the support team.
I will open an issue for this one as well (have fed back a few other open things already) and will update here if I gain any more information where a documentation change would be beneficial.

Thanks,
David
