### ISSUE TITLE
Get-CsOnlineUser - Output refactored, valuable parameters lost?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#8261]
Hello,

with v2.5.0 of MicrosoftTeams, the output was refactored. While I welcome the switch to the AutoRest query, I lament the lost of backwards compatibility.
> Modernized versions of Get-CsTenant and Get-CsOnlineUser (with -identity parameter only) have been released. They no longer emit deprecated properties and have some formatting changes compared to their remoting counterparts.

**Issue**: Calls with Switch Identity return different Object
**Workaround**: Call without switch Identity (OK)

As I would want to use the new output, I have found a few drawback based on the new Output object, or to be more precise, the parameters now missing/removed. May I have clarification on new object please?:

- [ ] Parameter `ObjectId` removed: 
Parameter was used to find Users (ObjectAd from AzureAd-Object and CsOnlineUser-Object were congruent!)
  - [ ] **How to replace ObjectId (with Identity?)**
- [ ] Parameter `VoicePolicy` removed: 
I have multiple scripts built on the table outlining the configuration in the [Migrate to Direct Routing ](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-migrating#user-provisioning-end-state-for-various-pstn-connectivity-options) document.
  - [ ] **How do I identify the Voice Configuration Type now correctly?**
- [ ] Parameter `TelephoneNumber` removed: 
  - [ ] **How to identify a Calling Plan Number?**
  - [ ] Follow up: **How will I be able to identify a Operator Connect Number?**
- [ ] Parameter `LineUri`: Output changed, TEL URI displayed without "tel:+" prefix!
The output format is used to model input format for SET-CmdLets.
  - [ ] Will this have an impact for `Set-CsUser` and others?
- [ ] Policy Parameters - Output changed from String to Object. 
  - [ ] What is the expected use for displaying an Object here, rather than the singularly assigned Name/Id?
  - [ ]  `TenantDialPlan` - This generates issues with Scripts using `$CsUser.TenantDialPlan` for queries, not for T/F assignment queries, but for the actual name for further use...
  now: `if ($CsUser.TenantDialPlan) {$CsUser.TenantDialPlan.Name} else {}`
  - [ ] `OnlineVoiceRoutingPolicy` - Output changed from String to Object, but works fine with String query?!
Is this the desired behavior and has this been missed from `TenantDialPlan` and other policies?
What is the expected use for displaying an Object here, rather than the singularly assigned Online Voice Routing Policy?
  - [ ] Other policy parameters... (all?): Wide ranging impact to multiple scripts if not documented properly. 
Which Parameters are affected here? All ending in `-Policy`?

Thank you,
David

PS: These are just for the most important parameters, I have not dug into all potentially used parameters yet

Track & Link: https://github.com/DEberhardt/TeamsFunctions/issues/95

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by Markus-Hanisch** [comment]
@DEberhardt 
I currently face the same issue. I maintain the Direct Routing for users. Therefore, the following attributes of the Cmdlets **Get-CsOnlineUser** and **Set-CsUser** are crucial in order to verify settings:
`-OnPremLineURI`
`-Phone`
`-EnterpriseVoiceEnabled`
`-HostedVoicemail`

I raised a Microsoft support ticket. Finally, I had to figure it out myself. I found out that the attribute's output is available in the PSVersion 2.3.1 of the MicrosoftTeams PowerShell module, but is not available in the PSVersion 2.5.0.

Therefore, I rolled back to v2.3.1

```powershell
Uninstall-Module -Name 'MicrosoftTeams'
Install-Module -Name 'MicrosoftTeams' -RequiredVersion '2.3.1'
```

@yogkumgit 
The Microsoft Teams PowerShell module must continue to include this outputs. I cannot even verify current or modified settings by means of **Get-CsOnlineUser** at the moment.
There was no notification in the admin center / message center on this vast Cmdlet changes ....
However, rolling back an older PS module version is not an satisfying option. 
Installing several PS module versions side by side is also not satisfying.
What is the reason why these outputs are not included / available anymore?

**Comment by DEberhardt** [comment]
Markus, the output as before is still available in v2.5.0 - you have to drop `-Identity` from the Cmdlet call and just run `Get-CsOnlineUser UserPrincipalName@domain.com` to get it.

That said, since Friday last week, v2.5.0 has been retracted, making v2.3.1 the most recent version. :)

**Comment by Markus-Hanisch** [comment]
@DEberhardt 
Hmm, okay.
In my opinion not really self-explaining and not annouced or mentioned in advance or at least by means of a warning when using that attribute.
The PnP PowerShell proceeded that way. So you were aware of upcoming changes.

I will try your approach without the `-Identity` parameter tomorrow and also inform the Microsoft support agent of my support case *lol*

**Comment by DEberhardt** [comment]
I don't really have any more information than what has been published. This particular nugget is in the Release notes :smile: 

In the meanwhile v2.5.1 has been published, but no information is yet given on potential changes from v2.5.0: https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-release-notes

**Comment by fxlite** [comment]
It's utterly bizarre that not specifying the -Identity parameter brings back the "deprecated properties". I'm not aware of this esoteric behaviour being mirrored in any other modules. Also, these "deprecated properties" are particularly pertinent to Team Direct Routing (onpremlineuri, hostedvoicemail etc.) and Direct Routing isn't deprecated...

**Comment by DEberhardt** [comment]
'tis unusual but not unwelcome to have this workaround. Technically, I find it kinda neat. If someone on this forum knows how this is coded please let me know.
I do agree though that these things should be firmly on the pre-release track until they are thoroughly tested and documented. Documentation and communication should come before the release, not months after...

**Comment by get-itips** [comment]
@DEberhardt David, with `2.5.1` and `2.5.2-preview` the outputted properties seem to be back.

**Comment by get-itips** [comment]
@DEberhardt I could confirm that the team is working on getting missing properties back in the following releases.

@yogkumgit please close.
