### ISSUE TITLE
Missing information on how to remove Guest members

### ISSUE THREAD

**Issue by gemsfounders** [MicrosoftDocs/office-docs-powershell#8262]
Since guests have a User Principal Name constructed from the email address in the form:
username_domain#EXT#@tenantname.onmicrosoft.com

The command doesn't run successfully please see below error output. 

PS C:\Users\remotelearning_xxx> Remove-TeamUser -GroupId 5d558f85-bd09-40c9-8529-29dxxx16372 -User username.s_xxx_schelearning.com#EXT#@contoso.onmicrosoft.com
Remove-TeamUser : No account or login hint was passed to the AcquireTokenSilent call.
At line:1 char:1
+ Remove-TeamUser -GroupId 5d558f85-bd09-40c9-8529-29dxxx16372 -User p ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-TeamUser], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.Powershell.Connect.Exceptions.AadAuthenticationFailedException,Microsoft.TeamsCmdlets.PowerShell.Custom.RemoveTeamUser

PS C:\Users\remotelearning_xxx>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d1eab6-ffac-e7a7-bc88-e61a74baba31
* Version Independent ID: a8181f1a-e575-410a-d5a4-0214c427b92d
* Content: [Remove-TeamUser (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/remove-teamuser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Remove-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Remove-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
@gemsfounders How are you?

I was able to remove a guest using the original email/identity used to invite him, for example

`Remove-TeamUser -GroupId 8942159d-d08b-4c81-99a2-92535b8ecac8 -User BrianJ@M365xXXXX.onmicrosoft.com`

Hope this helps you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @gemsfounders Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
