### ISSUE TITLE
Get-CsOnlineDialInConferencingUser - Error processing request

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#8264]
Sometime in late July when we submitted this PowerShell request, we would get partial results before getting this error

Get-CsOnlineDialInConferencingUser | Select AllowPstnOnlyMeetings, AllowTollFreeDialIn, ServiceNumber, SipAddress, TollFreeServiceNumber

AllowPstnOnlyMeetings : False
AllowTollFreeDialIn : True
ServiceNumber : 13127548028
SipAddress : <sip:stest2@unimaxlab.com>
TollFreeServiceNumber :

AllowPstnOnlyMeetings : False
AllowTollFreeDialIn : True
ServiceNumber : 13127548028
SipAddress : <sip:stest@unimaxlab.com>
TollFreeServiceNumber :

AllowPstnOnlyMeetings : False
AllowTollFreeDialIn : True
ServiceNumber : 13127548028
SipAddress : <sip:cgibson@unimaxlab.com>
TollFreeServiceNumber :

Error processing request.
    + CategoryInfo : ObjectNotFound: (:) [Get-CsOnlineDialInConferencingUser], BvdCmdletException
    + FullyQualifiedErrorId : Error processing request.,Microsoft.Rtc.Management.Hosted.Cbd.GetCsOnlineDialinConferenc
   ingUserCmdlet
    + PSComputerName : api.interfaces.records.teams.microsoft.com

Now, when I execute the same PowerShell, I just get the exception error

Get-CsOnlineDialInConferencingUser

Error processing request.
    + CategoryInfo          : ObjectNotFound: (:) [Get-CsOnlineDialInConferencingUser], BvdCmdletException
    + FullyQualifiedErrorId : Error processing request.,Microsoft.Rtc.Management.Hosted.Cbd.GetCsOnlineDialinConferenc
   ingUserCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

This issue is present in both 2.3.1 and 2.5.0 of the MicrosoftTeams module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a78c07b-1a7e-b36c-e3c1-8e610638ff79
* Version Independent ID: 02174a2a-5102-5479-f72f-c9bf0691bf9b
* Content: [Get-CsOnlineDialInConferencingUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
