### ISSUE TITLE
Will the Update-CsAutoAttendant cmdlet refresh Dial by Ext as well?

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/office-docs-powershell#8265]
Hi,

Will the Update-CsAutoAttendant cmdlet refresh Dial by Ext as well?

It does take a long while for this to come through. Even though Get-CsOnlineUser picks up the changes within 5mins.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6454551-f327-273d-225f-f32d20673e87
* Version Independent ID: dcedb664-3d7c-2018-0117-310d6a8a5425
* Content: [Update-CsAutoAttendant (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/update-csautoattendant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Update-CsAutoAttendant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Update-CsAutoAttendant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @haneef95 how are you?

According to the article, it seems that 

> Currently, it repairs the Dial-by-Name recognition status of an auto attendant.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @haneef95 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
