### ISSUE TITLE
Update document for removing Redirect Sites

### ISSUE THREAD

**Issue by wizneeraj** [MicrosoftDocs/office-docs-powershell#8274]
[Enter feedback here]
Remove-SPOSite does not work on site templates of type Redirectsite#0. We need to unlock the site first and then run the remove command to delete the site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb398dd-f241-3e00-9171-cc85d234e02d
* Version Independent ID: 6051ced3-d740-be87-58c5-7fe9f40ed99e
* Content: [Remove-SPOSite (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @wizneeraj I was able to use `Remove-SPOSite` against a site with template `Redirectsite#0` 

![image](https://user-images.githubusercontent.com/36666927/133304868-660a1f05-f7d2-4ccf-ac5f-fd2076a1e516.png)

The `LockState` of the site was `ReadOnly`.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @wizneeraj Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
