### ISSUE TITLE
Missing documentation for BackgroundImage parameter

### ISSUE THREAD

**Issue by skille** [MicrosoftDocs/office-docs-powershell#828]
Set-OMEConfiguration –Identity <OMEConfigurationIdParameter> –BackgroundColor "<Hexadecimal color code>"

Example:
Set-OMEConfiguration -Identity "OME Configuration" -BackgroundColor "#ffffff"

Example reverting back to default:
Set-OMEConfiguration -Identity "OME configuration" -BackgroundColor $null

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aabcc26e-242d-1342-24af-a419a129e91d
* Version Independent ID: 110aa234-6fb0-ff5c-fe5c-10b86147b9ce
* Content: [Set-OMEConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/Set-OMEConfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/encryption-and-certificates/Set-OMEConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@skille, I added the missing BackgroundColor parameter to the topic. Thanks.
