### ISSUE TITLE
Remove-CsVideoInteropServiceProvider is not recognized as the name of a cmdlet, function, script file or operable program

### ISSUE THREAD

**Issue by RichDaMan** [MicrosoftDocs/office-docs-powershell#8285]
**Remove-CsVideoInteropServiceProvider** is not working as a valid command within the MicrosoftTeams module v2.5.1

![Remove-CsVideoInteropServiceProvider Error](https://user-images.githubusercontent.com/680024/131874600-637744d2-d180-4c2e-a65d-87ba4236689f.png)

**Comment by get-itips** [comment]
Hello @RichDaMan how are you?
I've seen similar issues when not using a Global Admin, not saying this is the case but can you confirm please which admin role you used? Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and digging deep into it.  @RichDaMan We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
