### ISSUE TITLE
Feedback on Set-CsCallQueue -ChannelUserObjectID

### ISSUE THREAD

**Issue by lozyevans** [MicrosoftDocs/office-docs-powershell#8286]
[Enter feedback here]
The documentation isnt clear what GUID is required for -ChannelUserObjectId
It simply states "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)." 
The GUID that is actually required is a GUID of a user who is a team owner/admin not the team GUID. 
It would be useful to have this as an example or define where the GUID should be sourced.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ade68d-5dc0-c598-a659-8b018cef3e26
* Version Independent ID: 67efa086-edb0-2828-cc14-4c245290e4f3
* Content: [Set-CsCallQueue (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-CsCallQueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @lozyevans the article has been updated to expand that description.
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @lozyevans Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
