### ISSUE TITLE
No details for "SummarizedBy" parameter

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/office-docs-powershell#8292]
This commandlet documentation does not explain this parameter:

-SummarizeBy
{{ Fill SummarizeBy Description }}

<https://docs.microsoft.com/powershell/module/exchange/get-advancedthreatprotectiondocumentreport>

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0268c7f-8a78-c46d-717a-dc88b4e9307a
* Version Independent ID: 56e6b1ac-5304-0f03-ba51-52b75687bae1
* Content: [Get-AdvancedThreatProtectionDocumentReport (ExchangePowerShell)](https://docs.microsoft.com/en-gb/powershell/module/exchange/get-advancedthreatprotectiondocumentreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionDocumentReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionDocumentReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@anthonynz, available parameters in this state are a known issue. See [Issue 7429](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for an explanation.

So are you actually trying to use the parameter? Did it work as expected? Or are you pointing out that's the description is empty?

**Comment by chrisda** [comment]
@anthonynz, I added the description.

Thanks for the feedback.

Closing
