### ISSUE TITLE
-EnableSafeLinksForTeams seems now to be GA

### ISSUE THREAD

**Issue by directorcia** [MicrosoftDocs/office-docs-powershell#8299]
This document says for the option -EnableSafeLinksForTeams:

Note: As of March 2020, this parameter is in Preview and is available or functional only for members of the Microsoft Teams Technology Adoption Program (TAP).

but it seems it is now GA - https://techcommunity.microsoft.com/t5/microsoft-teams-blog/announcing-general-availability-of-safe-links-for-microsoft/ba-p/2588677

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb5774c-e5a6-62e3-ca36-8f9a9fef4230
* Version Independent ID: 1f9c9751-e9f0-a4bd-40de-7ba68739610a
* Content: [Set-SafeLinksPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-safelinkspolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-SafeLinksPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@directorcia, done. I also made the same fix in Set-SafeLinksPolicy.

Thanks for the feedback.

Closing
