### ISSUE TITLE
WinRM Basic auth is Required but it's not listed.

### ISSUE THREAD

**Issue by jdelforno** [MicrosoftDocs/office-docs-powershell#8300]
This page is misleading. 

Basic Authentication - which I'll remind you, is a security risk as per Microsoft's own blogs - via WinRM is usually disabled in an enterprise environment.

Microsoft has also recommended disabling Basic Authentication at the Exchange Level.

The EXOv2 module listed on this page should represent that with WinRM Basic Authentication disabled, only 9 commands are available.

The assumption, reading this page, is that keeping up with modern security practices will still grant you full access to all Exchange Commands however, this is definitely not the case.

At the very least, the section "How do you know this worked" should include that WinRM with Basic Authentication is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by pkbullock** [comment]
+100 what are the options here, i can see that AccessTokens doesnt work and the older SkypeForBusiness module is no longer available. 😮

**Comment by chrisda** [comment]
@jdelforno, @pkbullock, the first bullet in the "What do you need to know before you begin?" section says:

> - The requirements for installing and using the EXO V2 module are described in [Install and maintain the EXO V2 module](exchange-online-powershell-v2.md#install-and-maintain-the-exo-v2-module).

That topic goes into detail about why Basic auth in WinRM is required in the [Prerequisites](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#prerequisites-for-the-exo-v2-module) section:

> - WinRM needs to allow Basic authentication (it's enabled by default). We don't send the username and password combination, but the Basic authentication header is required to send the session's OAuth token, since the client-side WinRM implementation has no support for OAuth.

The connection topic is a balance between those trying to connect for the first time and those who connect often. Prior to the existence of the EXO V2 Module, all of the prerequisite information was in the Connection topic, but it seemed cleaner and less cluttered to have it in main EXO V2 Module topic.

If you want to attempt to eliminate the Basic auth in WinRM requirement, I would suggest opening a support case.

From what I understand, the fundamental problem of client-side WinRM not supporting OAuth is a problem in both PowerShell 5.x and 7.x.

**Comment by yogkumgit** [comment]
@jdelforno Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
