### ISSUE TITLE
Set-CsUserCallForwardingSettings applicable for Teams?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#8305]
Hello,

may I get clarification on whether these settings also apply to Teams?
![image](https://user-images.githubusercontent.com/44290340/132507310-8d5b41ff-a5ea-47a2-ba77-436c5b058dbd.png)

They are available in the Client and the Admin Center, and I would assume this to be the PowerShell CmdLet to do this, yet it only calls out Skype For Business 2019 as the Scope.

Thank you,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51c11092-ff62-1597-16b2-0ee351825b7e
* Version Independent ID: 38e763e5-1ed2-a9e5-8eca-32daf8dd3050
* Content: [Set-CsUserCallForwardingSettings (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csusercallforwardingsettings?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsUserCallForwardingSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsUserCallForwardingSettings.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by get-itips** [comment]
Hello @DEberhardt 
I couldn't find the cmdlet on Teams PowerShell... 
Let me know if I understood you well

**Comment by DEberhardt** [comment]
Me neither. Question is, is it missing or not?
I would think it is :)

**Comment by get-itips** [comment]
Hello @DEberhardt It isn't a cmdlet from the Teams PowerShell, it is only applicable for Skype For Business on-premises.
Thanks

**Comment by DEberhardt** [comment]
To the Tenant feedback provider system, I go. 🛩️  #please-close
