### ISSUE TITLE
Set-CsUserCallForwardingSettings - Multiple Parameters not described

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#8306]
Hello,

### Example 3 

The Parameter `TeamDelegateRingWaitTime` is listed in Example 3 but not described (`DelegateRingWaitTime`, however, is). 
Is this a typo, or is this a separate Parameter for Teams?

Regarding its value, when looking at the same functionality in the admin center I find that this time can only be configued in 10s intervals between 10s and 60s.

Is the example misleading (5s?), can this be set more granularly in PowerShell, or does this not apply/apply differently to Teams ( #8305 )

### Example 4 
Three parameters that are also not described in the Parameterlist:
- `DisableForwarding`
- `UnansweredToVoicemail`
- `UnansweredWaitTime`

Additionally, `UnansweredToOther` is missing too

Thank you,
David

PS: I cannot find the Command in the MicrosoftTeams PowerShell Module, so I cannot cross-reference with available parameters there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51c11092-ff62-1597-16b2-0ee351825b7e
* Version Independent ID: 38e763e5-1ed2-a9e5-8eca-32daf8dd3050
* Content: [Set-CsUserCallForwardingSettings (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csusercallforwardingsettings?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsUserCallForwardingSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsUserCallForwardingSettings.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by get-itips** [comment]
Hello @DEberhardt David, how are you?
As we saw on https://github.com/MicrosoftDocs/office-docs-powershell/issues/8305 This is a cmdlet exclusive of SfB Server.
Said that, TeamDelegateRingWaitTime is indeed described in the article, also found UnansweredToVoicemail, DisableForwarding, UnansweredWaitTime and UnansweredToOther.

Let me know if I understood you well.

**Comment by DEberhardt** [comment]
So it transpires I was copying the value and searching with the copied trailing space only getting one result.
And it might also transpire that I must have been quite tired not finding the parameters^^.

**Comment by get-itips** [comment]
> So it transpires I was copying the value and searching with the copied trailing space only getting one result.
> And it might also transpire that I must have been quite tired not finding the parameters^^.

Do not worry ;) have a good day
