### ISSUE TITLE
weblogin parameter

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#831]
It would be helpful if the -useweblogin parameter discussion mentioned that this needed when Multi Factor authentication is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f910a5c-5883-6394-19a3-4cf1670c431f
* Version Independent ID: 4451fe4c-df86-34a8-0db0-46a47e70b5a5
* Content: [Connect-PnPOnline (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by nsshommo** [comment]
@DeanGross Thanks for your comment. We are looking into this matter and will let you know what we can do about it.

**Comment by VesaJuvonen** [comment]
Will be fixed in June 2018 content refresh for PnP PowerShell cmdlets. Thanks, @DeanGross for reporting, appreciated.
