### ISSUE TITLE
Text under the -VisibleMeetingUpdateProperties parameter.

### ISSUE THREAD

**Issue by scottbutton** [MicrosoftDocs/office-docs-powershell#8311]
The text under VisibleMeetingUpdateProperties parameter says "There are three scenarios where meeting update messages" but there are 4 bullet point scenarios. It's a minor point, I know, thought I'd flag it 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23add0a6-bb9c-15d2-a6eb-351ae0564522
* Version Independent ID: 8056b3ee-4fab-3a5c-935b-a9d0e9ad82a4
* Content: [Set-OrganizationConfig (ExchangePowerShell)](c)
* Content Source: [exchange/exchange-ps/exchange/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@scottbutton, fixed. In the future, you too can make fixes like this yourself without opening an Issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.

Closing
