### ISSUE TITLE
There was no information on adding html text to a page section with Add-PnPClientSideText referencing the html from a file 

### ISSUE THREAD

**Issue by nirmala24** [MicrosoftDocs/office-docs-powershell#8312]
Hi,
**Cannot find any information on adding html content referencing a file with Add-PnPClientSideText instead of a variable.**

**Usual**
$newSection = Add-PnPClientSidePageSection -Page $pageame -SectionTemplate OneColumn -Order 1 -ErrorAction stop
$sHTML = '<h2>Headertext</h2>'
$newSection = $pageame .Sections | Where-Object {$_.Type -eq 'OneColumn' -and $_.order -eq 1}
$null = Add-PnPClientSideText -Page $pageame -Text $sHTML -Section 1 -Column 1 -ErrorAction stop

**What I would like to do is:**
$newSection = Add-PnPClientSidePageSection -Page $pageame -SectionTemplate OneColumn -Order 1 -ErrorAction stop
$sHTML = Provide a location of the .html file to refer to 
$newSection = $pageame .Sections | Where-Object {$_.Type -eq 'OneColumn' -and $_.order -eq 1}
$null = Add-PnPClientSideText -Page $pageame -Text $sHTML -Section 1 -Column 1 -ErrorAction stop

Is there a way passing .html file to refer to get the Text for a ClientSide Page.

Thanks,
Nirmala

**Comment by get-itips** [comment]
Hello @nirmala24 

how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @nirmala24 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
