### ISSUE TITLE
Engine tokens are not used with Add-PnPDataRowsToSiteTemplate

### ISSUE THREAD

**Issue by guillaume-kizilian** [MicrosoftDocs/office-docs-powershell#8313]
When using Get-PnPSiteTemplate, in the template, tokens are used to make the sitegroups more generic :
- {groupsitetitle}
- {groupsitename}
- {associatedownergroupid}
- ...

![image](https://user-images.githubusercontent.com/6792560/132685668-648b3517-7723-4ff4-b25b-022f48148498.png)
![image](https://user-images.githubusercontent.com/6792560/132686463-bf54025a-ee81-411a-aedf-9ad4449cba16.png)

Works like a charm, however those tokens are not used when adding datarows with Add-PnPDataRowsToSiteTemplate to the same template, making it inconsistent and unusable when creating a new site.

![image](https://user-images.githubusercontent.com/6792560/132686284-d95709b6-c2b7-43c3-a84e-d931b47bd989.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5b1f7fc-f25b-3ae7-550f-dbda983bb508
* Version Independent ID: 4dc444d7-ca83-1930-61a8-73e3cd75d29f
* Content: [Add-PnPDataRowsToSiteTemplate (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpdatarowstositetemplate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPDataRowsToSiteTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPDataRowsToSiteTemplate.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by yogkumgit** [comment]
Hello @guillaume-kizilian 
how are you?
Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests here : https://github.com/PnP/PowerShell/, in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.
The documentation for PnP cmdlets is then synced from that repo into this one.
Thank you!
