### ISSUE TITLE
Object is not in valid state for this operation or there is a delay in propagation

### ISSUE THREAD

**Issue by dietrichmeyer** [MicrosoftDocs/office-docs-powershell#8323]
My batch size is 1 user for testing. I started the cmdlet about 16 hours ago.  The expanded state indicates "Object is not in valid state for this operation or there is a delay in propagation".  ErrorCount equals CompletedCount, both are 1.  There's no way to get at an error except for 'object is not in a valid state'.  This cmdlet seems pretty useless.

My goal is to put users into a different  Teams app permission policy group, e.g. from some group I created to IT-Admins.  Eventually I will be moving some users from Global to a new group that I just created.  Mabye you can't move users into IT-Admin in batch mode.  Maybe I have to remove users from an existing permission group before I can put them into another group?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44ec2119-d178-b9f8-3199-481ecd84eea3
* Version Independent ID: 6e814ba4-7680-12b5-10ee-f7c71865cd71
* Content: [Get-CsBatchPolicyAssignmentOperation (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-csbatchpolicyassignmentoperation?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-CsBatchPolicyAssignmentOperation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-CsBatchPolicyAssignmentOperation.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by dietrichmeyer** [comment]
Update:  Our SIP addresses do not match our UPNs. Typically everything M365 related uses UPNs, but I remember documentation said use SIP addresses.  I switched to SIP address and no errors. 'User not found' would have been a more helpful error message than 'object is not in a valid state.'

**Comment by get-itips** [comment]
Glad to hear you could resolve it. @dietrichmeyer 
Thanks to your post, I noticed that not all parameter descriptions were showing for New-CsBatchPolicyAssignmentOperation cmdlet.
