### ISSUE TITLE
Documentation description for parametar is missing - EnableForwardingAddressSyncForMailboxes

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/office-docs-powershell#8326]
Documentation description for parametar is missing - EnableForwardingAddressSyncForMailboxes

Kind regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23add0a6-bb9c-15d2-a6eb-351ae0564522
* Version Independent ID: 8056b3ee-4fab-3a5c-935b-a9d0e9ad82a4
* Content: [Set-OrganizationConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hkusulja, available parameters in this state are a known issue. See [Issue 7429](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for an explanation.

So are you trying to use this parameter? Does it work as you expect? Or are you just pointing out that the description is empty?

**Comment by chrisda** [comment]
@hkusulja, I added the following description for the parameter:

> This parameter is reserved for internal Microsoft use.

Thanks for the feedback.

Closing
