### ISSUE TITLE
Why is the -WhatIf switch even defined here?

### ISSUE THREAD

**Issue by partlythomas** [MicrosoftDocs/office-docs-powershell#8328]
Why is the -WhatIf switch even defined here?
If it is not a working option for the cmdlet, why is it defined at the page at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae09acf-5413-eb3c-e4c7-2481b7b178f5
* Version Independent ID: d0d555a7-de13-0173-7a8c-e13587b334bc
* Content: [Set-User (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-user?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-User.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-User.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@partlythomas, valid question. A small percentage of the thousands of parameters on Exchange cmdlets are available, but don't work correctly (deprecated features, tied to previous versions, etc.). What's unusual is this is basically a common Windows PowerShell parameter that's available on most every New/Set/Remove cmdlet in every product.

If you would like to see this parameter truly removed from this cmdlet (at which point we'll also remove it from the topic), I would suggest opening a support case.

**Comment by yogkumgit** [comment]
@partlythomas Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
