### ISSUE TITLE
Please clarify how long this process takes

### ISSUE THREAD

**Issue by michaelblumenthal** [MicrosoftDocs/office-docs-powershell#833]
I've tried this cmdlet, and it executes successfully, but I don't see the cross-site navigation appear.  I understand from reading this article http://sympmarc.com/2018/03/28/office-365-hub-sites-are-here-a-few-tips/ that it could take 2 hours for the changes to appear.  It would be great to mention that in this document. Also, it would be helpful to explicitly say what the UX changes are, even if it is just by referencing this blog post: https://techcommunity.microsoft.com/t5/SharePoint-Blog/SharePoint-hub-sites-new-in-Office-365/ba-p/109547 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 114697af-1b15-2582-49af-7ae2a8fe1cb0
* Version Independent ID: 6ed31c1e-1706-318b-5030-0e74dd9e875e
* Content: [Register-SPOHubSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/register-spohubsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Register-SPOHubSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Register-SPOHubSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by nsshommo** [comment]
@michaelblumenthal Thanks for your valuable feedback. We are looking into this matter.

**Comment by Techwriter40** [comment]
@VesaJuvonen a PnP cmdlet for review .

**Comment by AndreaBarr** [comment]
@michaelblumenthal Thank you for this feedback

I am going to get this over to the PowerShell team for investigation and updating. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hello @michaelblumenthal thanks for your feedback.
I created a pull request to improve the article, adding a link to more information on Hub Sites and a note on expected times for the changes to be reflected.
Thank You

**Comment by yogkumgit** [comment]
@trent-green  Please merge the PR #3427

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @michaelblumenthal  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@officedocsbot close
