### ISSUE TITLE
MeetingRecordingExpirationDays: value of -1

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/office-docs-powershell#8331]
This says that MeetingRecordingExpirationDays can be set to 1 to 99,999... however, this documentation says you should set it to -1 to 'disable' automatic expiration.

Suggested edit:
Value can be from 1 to 99,999 days to automatically expire recording files. Value can be set to -1 to disable automatic expiration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for your feedback! @npherson
