### ISSUE TITLE
Folders with a different language from Cpanel's webmail

### ISSUE THREAD

**Issue by vitorliduario** [MicrosoftDocs/office-docs-powershell#8333]
I've tried all the methods and none work.

**Comment by yogkumgit** [comment]
@vitorliduario Please indicate which document you referring and what is your feedback to improve it. Thanks.

**Comment by yogkumgit** [comment]
@vitorliduario We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
