### ISSUE TITLE
Whitelist just your organizations O365 emails, such as no-reply@sharepointonline.com?

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/office-docs-powershell#8335]
On these examples, is there a way to specify just your organizations O365's alerts? I want users who get an O365 SharePoint Online notification from no-reply@sharepointonline.com to trust it internally, but not if its spoofed or from an external organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba41cae3-da51-0a3d-1652-bce98452d4dc
* Version Independent ID: a2d20c87-6277-a868-3c2e-e2fe225e6f17
* Content: [Set-ExternalInOutlook (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-externalinoutlook?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-ExternalInOutlook.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-ExternalInOutlook.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@eschrader, I thought there was already some level of general, unconfigurable allow/whitelisting going on for internal status notifications? Or are you saying that legitimate no-reply@sharepointonline.com messages are getting incorrectly tagged as external?

Issues:
- There's no way to differentiate between internal and external senders using this feature.
- The email address that's checked in the allow list is the From address (a.k.a. 5322.From or P2 address in the message body) which is going to be the same for real notifications vs. spoofed notifications from malicious external senders. So, if you configure no-reply@sharepointonline.com in the allow list, good and bad messages from this sender won't be tagged as external.

But, the [spoof intelligence insight](https://docs.microsoft.com/microsoft-365/security/office-365-security/learn-about-spoof-intelligence) should catch any spoof attempts for legit senders like no-reply@sharepointonline.com. You'll just need to periodically monitor to make sure it's working properly.

Comments?

**Comment by yogkumgit** [comment]
@eschrader Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
