### ISSUE TITLE
Microsoft sync technology - Mobile Device Mailbox Policy and  ActiveSync Device Access Rule

### ISSUE THREAD

**Issue by arbilus** [MicrosoftDocs/office-docs-powershell#8343]
Hello, 

This is my first post ! 

If I create a new Mobile Device Mailbox Policy with New-MobileDeviceMailboxPolicy or New-ActiveSyncMailboxPolicy and do a Set-CASMAilbox -ActiveSyncMailboxPolicy to attribute this policy to a specific mailbox and if the user of this mailbox is using Outlook for iOS or Outlook for Android then the policy will not be working, is it right ? 

Because in my opinion if Outlook for iOS or Outlook for Android is using Microsoft sync technology and not ActiveSync for the data synchronisation then Powershell commands like New-MobileDeviceMailboxPolicy / New-ActiveSyncMailboxPolicy or New-ActiveSyncDeviceAccessRule will not be working because it's only for ActiveSync. Am I right ? 

Regards, 
@rbilus

**Comment by chrisda** [comment]
@arbilus, lo and behold, a few of the mobile device mailbox policy settings actually do apply to Outlook for iOS and Android. For more information, see [Leveraging Exchange Online mobile device policies](https://docs.microsoft.com/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/secure-outlook-for-ios-and-android#leveraging-exchange-online-mobile-device-policies).

I'll update the respective parameter descriptions in the \*-MobileDeviceMailboxPolicy cmdlet reference topics.

**Comment by arbilus** [comment]
Thank you for the update.

**Comment by yogkumgit** [comment]
@arbilus Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
