### ISSUE TITLE
Get-DynamicDistributionGroupMember Help Topic URI Missing

### ISSUE THREAD

**Issue by PFarrell216** [MicrosoftDocs/office-docs-powershell#8346]
**Get-Help Get-DynamicDistributionGroupMember -online** returns the following:

Get-Help: The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help topic is not specified in the command code or in the help file for the command.

Searched for other topics about this cmdlet, only found a few unrelated closed issues from August. Apologies if this is mentioned/known elsewhere.

**Comment by chrisda** [comment]
@PFarrell216, that feature is currently in Private Preview. The cmdlet help content has not yet been checked into Exchange Code.

**Comment by yogkumgit** [comment]
@PFarrell216 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
