### ISSUE TITLE
Description of NoCompression flag is missing

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/office-docs-powershell#8348]
Description of NoCompression flag is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc49cf3f-058c-01dc-3f37-f0d1c11ce088
* Version Independent ID: 28cd035a-d309-7227-f63c-03dbb55a734e
* Content: [Export-SPMetadataWebServicePartitionData (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/export-spmetadatawebservicepartitiondata?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Export-SPMetadataWebServicePartitionData.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Export-SPMetadataWebServicePartitionData.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @repton-infinity how are you?
Thanks for your feedback, I tested this, and as you can suspect, the export is done uncompressed, will add that to the article.
thank you
