### ISSUE TITLE
MaskBits - What happens when I do not provide the Mask?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#8350]
Hello,

`MaskBits` is listed with no default value (as expected) but as optional (not expected).

No explanation is given on what happens if the Mask is not provided?
- Is it set to 32 or 128 respectively only taken this individual address?
- Is it set to 0 to take the whole subnet?

I haven't had an opportunity to try it out, but as it was something that was not clear from reading, I thought I raise regardless.

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c6a50ee-08c4-35c7-9bf7-01ab3d606fd1
* Version Independent ID: 68a5a8fb-e982-d6ce-c92b-0cc304e9655b
* Content: [New-CsTenantTrustedIPAddress (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cstenanttrustedipaddress?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTenantTrustedIPAddress.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTenantTrustedIPAddress.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by DEberhardt** [comment]
PS: This entry does not state what it is applicable for... Judging from the word "Tenant" in the Noun, I assume - just like all others it is applicable for Skype Online.
Should this be added to the header?

**Comment by get-itips** [comment]
Hello @DEberhardt David,
the article mentions that

> The IP address is in IPv4 format, and the maskbits is set to 32 by default.

**Comment by DEberhardt** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/pull/8410

**Comment by yogkumgit** [comment]
@get-itips
