### ISSUE TITLE
LocationPolicy is listed, though not available

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#8351]
Hello,

raising against the correct Cmdlet now :)

```powershell
❯ new-CsTenantNetworkSite -Description
Description                 NetworkRoamingPolicy        LocationPolicy              Debug
EmergencyCallRoutingPolicy  EmergencyCallingPolicy      AsJob                       InformationAction
WhatIf                      Tenant                      ErrorAction                 OutBuffer
EnableLocationBasedRouting  InMemory                    InformationVariable         ErrorVariable
Confirm                     Identity                    OutVariable                 PipelineVariable
NetworkRegionID             NetworkSiteID               Verbose                     WarningAction
SiteAddress                 Force                       WarningVariable
```

- [ ] `LocationPolicy` is still there and I think it can be removed - functionality is superceded by ECP and ECRP, correct?
- [ ] `NetworkRoamingPolicy` could use a little statement that it can be queried with `Get-CsTeamsNetworkRoamingPolicy`
- [ ] `NetworkRoamingPolicy` is not sorted alphabethically
- [ ] `SiteAddress` could have an example
- [ ] `SiteAddress`: When would I use this and why?

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6244e0e-8738-3a25-d829-032164a880df
* Version Independent ID: 749077d4-5b5e-9c37-4e31-100627b3fac9
* Content: [New-CsTenantNetworkSite (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-cstenantnetworksite?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTenantNetworkSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTenantNetworkSite.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @DEberhardt 

I see LocationPolicy there in `2.6.0` version of the module.
There is an example using SiteAddress in the article, however, tried to use it but seems does not get saved, will try to dig into that.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @DEberhardt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
