### ISSUE TITLE
Inactive Mailboxes as Exchange Locations

### ISSUE THREAD

**Issue by cburtbcit** [MicrosoftDocs/office-docs-powershell#8354]
It should be noted in the section of this page about the -ExchangeLocation flag that the addresses of inactive mailboxes must be preceded with a period ("."), else the command will be unable to locate the recipient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ee25f1c-d3bf-82b6-40ce-dbf4acd052dd
* Version Independent ID: 46187cd1-47cd-f7c4-4720-e612eb370884
* Content: [New-CaseHoldPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-caseholdpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-CaseHoldPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-CaseHoldPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cburtbcit, fixed. I also updated the AddExchangeLocation and RemoveExchangeLocation parameter descriptions in Set-CaseHoldPolicy.

Thanks for the feedback.

Closing
