### ISSUE TITLE
{{ Fill AdoptPreexisting Description }}

### ISSUE THREAD

**Issue by gkneale** [MicrosoftDocs/office-docs-powershell#8355]
Is there an ETA for when each instance of "{{ Fill AdoptPreexisting Description }}" will be updated with details?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68325010-9605-22b4-4b6c-b61f332dc321
* Version Independent ID: 47ce5d33-5483-8c8e-2aa2-532178bf466a
* Content: [New-MigrationBatch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gkneale, available parameters in this state are a known issue. See [Issue 7429](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for an explanation.

Are you trying to use this parameter? Is there content elsewhere that mentions using this parameter? Or are you just pointing out that the description is empty?

**Comment by gkneale** [comment]
Hello Chris,

Both.

The documentation is incomplete, and I would like to know more about these
parameters to see if they apply or would be beneficial to the batches I am
creating. They are not referenced anywhere else on the Internet (that I
know of).

**Comment by chrisda** [comment]
@gkneale, the best way to get an answer is to open a support case and ask a) what this parameter is for and b) is this parameter supposed to be available.

**Comment by yogkumgit** [comment]
@gkneale Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
