### ISSUE TITLE
Duplicated BaseViewId in Events list after applied PnP Site Template

### ISSUE THREAD

**Issue by aikensam** [MicrosoftDocs/office-docs-powershell#8358]
[Enter feedback here]

BEFOFRE apply a PnP template:

get-pnpview -List E9E6AC62-B573-4972-AD89-8900F6CF9D89 |fl Title,Id,*base*

Title      : Calendar
Id         : b6193ae5-07c9-4274-abf0-7c88678b1ab8
BaseViewId : 2

Title      : All Events
Id         : 1f5c97d3-bdd5-458b-8a79-5907db57e5ca
BaseViewId : 1

Title      : Current Events
Id         : 68d0c3f9-34dc-4f87-9a4c-b13019febc8e
BaseViewId : 3

AFTER applied a PnP site template with Events list:

get-pnpview -List E9E6AC62-B573-4972-AD89-8900F6CF9D89 |fl Title,Id,*base*

Title      : Calendar
Id         : c8719b93-b5aa-4559-9773-13b269925094
BaseViewId : 1

Title      : All Events
Id         : 28745d11-8c07-43ca-b48c-4c7659df5b93
BaseViewId : 1

Title      : Current Events
Id         : adb3ce50-51ba-457a-95c4-6922b6bac54e
BaseViewId : 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f32fdf8-99da-9bdb-013c-c4385ab506d3
* Version Independent ID: 0c3c20da-7b4a-cfd9-fbfc-f715a93a8ae1
* Content: [Invoke-PnPTenantTemplate (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/invoke-pnptenanttemplate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Invoke-PnPTenantTemplate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Invoke-PnPTenantTemplate.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by aikensam** [comment]
The causes Events Webpart not showing category issue (https://github.com/MicrosoftDocs/office-docs-powershell/issues/8358). After applied PnP site template, all views' BaseViewIds equal to 1.  

 <img width="921" alt="category missing" src="https://user-images.githubusercontent.com/13567454/133919705-122fe3b2-6aa9-414d-9335-7d9da9171bc1.png">

Because  all views' BaseViewIds equal to 1, first GetById api call returns a wrong view and then RenderListFilterData in second GetById api call returns nothing (0 byte). Then javascript line 5110 throws errror and cannot render a list of category choices.

Seems it relates to 
https://github.com/pnp/pnpframework/blob/39d966e09c30db771aca2fafbf702fc82a498597/src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
![image](https://user-images.githubusercontent.com/13567454/133919859-b8dab1ad-b96b-4407-b6f8-fab64f47d020.png)

When create SPView with viewType = 524288 (ViewType.Calendar), Calendar view's BaseViewId is 2. When create SPView with viewType = 524288+8193, Calendar view's BaseViewId is 1 and causes above category issue.

**Comment by yogkumgit** [comment]
Hello @aikensam  
how are you?
Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests here: https://github.com/PnP/PowerShell/ in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.
The documentation for PnP cmdlets is then synced from that repo into this one.
Thank you!
