### ISSUE TITLE
invalid characters in the URL

### ISSUE THREAD

**Issue by GeorgeBSapphire** [MicrosoftDocs/office-docs-powershell#8359]
Hello

I keep receiving 
![image](https://user-images.githubusercontent.com/91066140/133999974-acd7fd39-74bd-4d96-b031-96b6a4b251ce.png)
probably as the site URL has &20 in it
Any ideas?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85cba281-56e9-dfba-0ed8-df9a22029eaa
* Version Independent ID: 47c94158-6136-04ee-5fc0-712abcb1827a
* Content: [Copy-PnPFile (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/copy-pnpfile?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Copy-PnPFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Copy-PnPFile.md)
* Service: **sharepoint-powershell**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **pamgreen**

**Comment by yogkumgit** [comment]
@GeorgeBSapphire Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests here: https://github.com/PnP/PowerShell/ in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.
The documentation for PnP cmdlets is then synced from that repo into this one.
Thank you!
