### ISSUE TITLE
What is the separator for the dial mask?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#8370]
Hello,

I thought I had read this somewhere already, but now I do not find a record of it anywhere.
**How is the String for the Dial Mask to be separated?**

The Admin Center volunteers:
> An emergency dial mask is a normalization rule that defines the digits that users can dial for an emergency call. A dial mask maps to an emergency dial string, which is a number used to make an emergency call.

The Help file does not help ☹️  - No examples or description of any parameters.

May I ask to:
- Add an example with a Dial Mask that illustrates how they are to be separated? (Comma, Semicolon, etc.)
- Describe the separator also on the parameter.

Thank you,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4d46af-d78b-c5ff-77ce-fc2ab0098958
* Version Independent ID: d3f4a454-b6b6-2396-f52c-523512b23105
* Content: [New-CsTeamsEmergencyNumber (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencynumber?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsEmergencyNumber.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsEmergencyNumber.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @danny-levin
* Microsoft Alias: **dannyle**

**Comment by DEberhardt** [comment]
Just could run the cmdlet the first time, here is the result:
```powershell
❯ New-CsTeamsEmergencyCallRoutingPolicy -Identity "ECRP-TEST" -Description "TEST" -AllowEnhancedEmergencyServices $TRUE -EmergencyNumbers @{add=$nr001};
Invalid format for Dial mask 911,999,000. Dial mask must be list of numbers separated by semicolon. Each number string
must be made of the digits 0 through 9 and can be from 1 to 10 digits in length.
    + CategoryInfo          : InvalidArgument: (Microsoft.Rtc.M...llRoutingPolicy:TeamsEmergencyCallRoutingPolicy) [Ne
   w-CsTeamsEmergencyCallRoutingPolicy], ArgumentException
    + FullyQualifiedErrorId : CustomValidationFailed,Microsoft.Rtc.Management.Internal.NewTeamsEmergencyCallRoutingPol
   icyCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com
```

**Comment by get-itips** [comment]
Thanks @DEberhardt David, will add detail to the article.
