### ISSUE TITLE
Strange Syntax section

### ISSUE THREAD

**Issue by mmascolino** [MicrosoftDocs/office-docs-powershell#8391]
Should the syntax section here really be [ ]?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31ec43d9-dd2a-2939-5781-1b667978c280
* Version Independent ID: a0f55083-bbab-71c8-cf8b-26126c0265e0
* Content: [Get-RecipientStatisticsReport (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-recipientstatisticsreport?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Get-RecipientStatisticsReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-RecipientStatisticsReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mmascolino, that cmdlet has no parameters. If you look at the topic on GitHub, it doesn't look like that:

<https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-RecipientStatisticsReport.md>

There are only 13 cmdlets out of ~1300 that have no parameters. I randomly checked a couple of them, and they all have that weird `[ ]` syntax.

[Get-ADServerSettings](https://docs.microsoft.com/powershell/module/exchange/get-adserversettings)

[Get-PolicyConfig](https://docs.microsoft.com/en-us/powershell/module/exchange/get-policyconfig)

So it appears to be a quirk with docs.microsoft.com publishing.

**Comment by yogkumgit** [comment]
@mmascolino Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
