### ISSUE TITLE
Request time out - Creating a user instance

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#8406]
I'm having trouble trying to create an instance of this object using a user

I've verified that the user I want to use is EnterpriseVoiceEnabled (and have used this same user in the O365 Teams portal)

Get-CsOnlineUser 'awhite@unimaxlab.com' | Select enterp*,ObjectId

EnterpriseVoiceEnabled ObjectId
---------------------- --------
                  True dc07a49e-2c4d-4bcb-a7ad-ce5b493834bc

But get a timeout when executing the following

$op = New-CsAutoAttendantCallableEntity -Identity "dc07a49e-2c4d-4bcb-a7ad-ce5b493834bc" -Type User
Could not parse exception message <html><head><title>500 - The request timed out.</title></head><body>  <font color
="#aa0000">         <h2>500 - The request timed out.</h2></font>  The web server failed to respond within the
specified time.</body></html>
    + CategoryInfo          : NotSpecified: (:) [New-CsAutoAttendantCallableEntity], OnlineCmdletException
    + FullyQualifiedErrorId : Unspecified,Microsoft.Rtc.Management.Hosted.OAA.V2.NewCsAaCallableEntityCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 414be5d8-a999-2d93-c6e8-a60e6763eb7a
* Version Independent ID: 9dec1f94-908b-0992-c986-084449965df0
* Content: [New-CsAutoAttendantCallableEntity (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csautoattendantcallableentity?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by dariomws** [comment]
Hi @sarollins, thank you for your feedback.

I have tested it and works for me:
![image](https://user-images.githubusercontent.com/33589238/136920138-7c6c6bbe-7031-446b-8c1c-890629065eea.png)

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
