### ISSUE TITLE
Command not supported in versions later than 2010

### ISSUE THREAD

**Issue by GRJ78** [MicrosoftDocs/office-docs-powershell#8409]
What's the purpose of mentioning that this command also applies to Exchange versions later than 2010 and then state that it has been replaced by Managed Availability? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f42db18c-b5df-315c-05d6-b683e6426171
* Version Independent ID: ec9f562e-cfa1-1ae4-4c98-d6a45fd1739f
* Content: [Test-ActiveSyncConnectivity (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/test-activesyncconnectivity?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Test-ActiveSyncConnectivity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Test-ActiveSyncConnectivity.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@GRJ78, it's a problem of availability vs. functionality. Test-ActivitySyncConnectivity is available in all of those versions, but it's only functional/supported/preferred in Exchange 2010 or for compatibility in co-existence environments that contain Exchange 2010 (Exchange 2013 or Exchange 2016).

**Comment by yogkumgit** [comment]
@GRJ78 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
