### ISSUE TITLE
List as Admin the plugins installed on the Outlook of the users  

### ISSUE THREAD

**Issue by arbilus** [MicrosoftDocs/office-docs-powershell#8420]
Hello, 

I didn't find a solution, that's why I'm asking here. 
Is there a solution (I guess in Powershell), to list the Outlook plugins installed on the Outlook of the users of my organisation ? 

N.B : I'm not speaking about the "COM Add-ins", but the Outlook add-ins which can be installed on the Microsoft Store. 

Thank you for your time. 

Regards, 
Alexandre

**Comment by dariomws** [comment]
Hi @arbilus, thank you for your feedback.

I have tested it and works for me:
![image](https://user-images.githubusercontent.com/33589238/136920138-7c6c6bbe-7031-446b-8c1c-890629065eea.png)

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by arbilus** [comment]
Hello, thank you for your answers 👍 . No problem I understand. I've done a deep search but I didn't see any solutions. I will do a ticket, thank you for the advise :)
