### ISSUE TITLE
SendFromAliasEnabled

### ISSUE THREAD

**Issue by maxlittleton** [MicrosoftDocs/office-docs-powershell#8430]
Is the "SendFromAliasEnabled" section still accurate about this feature is still in preview? I see in the roadmap it is in "rolling out" status and I can find no up-to-date information on if this feature is now safe to use as it has a pretty stern warning about degraded performance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23add0a6-bb9c-15d2-a6eb-351ae0564522
* Version Independent ID: 8056b3ee-4fab-3a5c-935b-a9d0e9ad82a4
* Content: [Set-OrganizationConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@maxlittleton  If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
