### ISSUE TITLE
Add-TeamChannelUser throws error 

### ISSUE THREAD

**Issue by flowt-au** [MicrosoftDocs/office-docs-powershell#8434]
PS 7.1
"2.4.1-preview"

eg
Add-TeamChannelUser -GroupId aaa-bbb-ccc -DisplayName "TestPowershellPrivate" -User some.student@myschool.nsw.edu.au -Role Owner

Results in error
BadRequest Message: Invalid OData type specified: "Microsoft.Teams.Core.aadUserConversationMember"

Adding the same user as a Member works fine but attempting to change them into an Owner (after waiting a while) fails. 

There is already one owner of that Private Channel (added directly via Teams app when the channel was created there).

** This used to work in an earlier version of MicrosoftTeams.  **

Thanks,
Murray

**Comment by dariomws** [comment]
Hi @flowt-au, thank you for your feedback.

As the article says this cmdlet is part of the public preview. As the state of that version, the cmdlet may be subject to changes and probably needs adjustments. I recommend checking [here](https://docs.microsoft.com/microsoftteams/teams-powershell-release-notes) to see when this cmdlet goes GA. Also if you want your request to reach the product team please visit [here](https://microsoftteams.uservoice.com/) we are limited to documentation updates.

You can also give it a try with the latest public preview version:
https://www.powershellgallery.com/packages/MicrosoftTeams/2.5.2-preview

**Comment by flowt-au** [comment]
@yogkumgit Thanks for that. Yes, conforming that v `2.5.2-preview` works. Here's hoping the `Add-TeamChannelUser` soon makes it into the GA version. :-)
