### ISSUE TITLE
Exchange Online PowerShell V2 M1 support

### ISSUE THREAD

**Issue by kjacobsen** [MicrosoftDocs/office-docs-powershell#8445]
Hi,

Following the steps outlined, I cannot connect to Exchange Online from a M1 MacBook Pro. I get the following error:

```powershell
Exception: /Users/kjacobsen/.local/share/powershell/Modules/ExchangeOnlineManagement/2.0.5/netCore/ExchangeOnlineManagement.psm1:475
Line |
 475 |  …             $PSSession = New-ExoPSSession -ExchangeEnvironmentName $E …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-and-maintain-the-exo-v2-module)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kjacobsen, I recently added WSMan installation instructions for Linux per Issue #8419. Try the WSMan installation steps in the [Linux](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#linux) as described below. Let me know how it goes.

> After you install PowerShell 7, do the following steps:
>
> 1. Run PowerShell as superuser: `sudo pwsh`
> 2. In the PowerShell superuser session, run the following commands:
>
>    ```powershell
>    Install-Module -Name PSWSMan
>
>    Install-WSMan
>    ```
>
>    If prompted, accept PSGallery as the source for the cmdlets.
>
> Now you can do the [regular PowerShell prerequisites](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#prerequisites-for-the-exo-v2-module) and [install the EXO V2 module](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#install-the-exo-v2-module).

**Comment by yogkumgit** [comment]
@kjacobsen Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by kjacobsen** [comment]
Hey, Just to claidy, that the documentation still doesn't work for me.

**Comment by kjacobsen** [comment]
Also tried:

```
PS /Users/kjacobsen> Update-module -Name PSWSMan

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value
by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS /Users/kjacobsen> Install-WSMan
Install-WSMan: Failed to select the necessary library, the host isn't macOS, Linux based on GLIBC or musl, or OpenSSL isn't installed
PS /Users/kjacobsen>
```

**Comment by kjacobsen** [comment]
Ok, so running `Install-WSMan` works when run from terminal, but not from iTerm. Checked `$ENV:Path` and everything looks ok. From my quick look, `Install-WSMan` must be doing something weird to detect the operating system.

Running `Connect-ExchangeOnline` works in Terminal, but not iTerm.

**Comment by kjacobsen** [comment]
Any reason this was closed again? Definitely seems to be a PATH issue or something related.

**Comment by yogkumgit** [comment]
@kjacobsen We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
