### ISSUE TITLE
MicrosoftTeams certificate auth has been removed from preview

### ISSUE THREAD

**Issue by abt10** [MicrosoftDocs/office-docs-powershell#8473]
Hello,

the certificate authentication has been removed from MicrosoftTeams preview.
Is it still an option and will it ever be supported/used in stable version?

Thanks

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @abt10 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
