### ISSUE TITLE
ISE freezes/locks up when loading either the MSOnline/ or exchange online powershell when loading from ISE

### ISSUE THREAD

**Issue by BelowAll** [MicrosoftDocs/office-docs-powershell#8478]
First time submitting a bug /issue on here for this not sure of the proper way

Issue:
ISE freezes/locks up when loading either the MSOnline/ or exchange online powershell when loading from ISE

How to reproduce:
Launch ISE, 
run the following

`Import-Module $((Get-ChildItem -Path $($env:LOCALAPPDATA+"\Apps\2.0") `
-Filter Microsoft.Exchange.Management.ExoPowershellModule.dll -Recurse ).FullName`
|?{$_ -notmatch "_none_"} | select -First 1)

$EXOSession = New-ExoPSSession

Import-PSSession $EXOSession`

leave session open for about 30-60 mins, try to interact with ISE & its completley frozen. You have to kill it via task manager.

I have had this happen on multiple machines & in multiple tenants, various versions etc...seems to only effect ISE, not regular Powershell.

the first time i noticed it was a few years ago. but that was only on the MSOnline Module, now it seems to be happening on multiple ones

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @BelowAll Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
