### ISSUE TITLE
Add the Safe Link policy object properties

### ISSUE THREAD

**Issue by Bargenish** [MicrosoftDocs/office-docs-powershell#8493]
Adding the Policy object schema and properties could be a nice-to-have addition (as being [done](https://docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0) for other objects)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3482ca00-a1bf-ae16-87a5-6c3c8639942d
* Version Independent ID: 368a63c0-8e5a-3fd7-36e6-a9c3b1ae6e50
* Content: [Get-SafeLinksPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-safelinkspolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-SafeLinksPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-SafeLinksPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
@Bargenish, I have been looking over the documented parameters on the Set- article and it seems that the only one missing is LocalizedNotificationTextList.
Usually, when a property is not available to be modified, it's reserved for internal use.

**Comment by chrisda** [comment]
Based on the link in the original issue, it appears Bargenish is asking for objects/methods that are available in MSGraph. Not sure that's doable.

**Comment by Bargenish** [comment]
@chrisda that's not what I was asking, 
When calling the `Get-SafeLinksPolicy` there are several more fields that are not a part of the `Set-SafeLinksPolicy` and there is no description regarding those fields.
I only added a ref to one of the MSGraph objects as an example for an object with descriptive information regarding all fields that are being returned as part of the response.

**Comment by dariomws** [comment]
@Bargenish, thank you. The only missed parameter I found is LocalizedNotificationTextList. There are others with creation and modifications date that I think don't need explanation.
Did you find another parameter/attribute?

**Comment by chrisda** [comment]
@Bargenish, got it. Thanks for the clarification. Unfortunately, the answer is going to be about the same: we don't document every last output property on Get- cmdlets. Of course, any configurable parameters on New- and Set- will be visible in the output of Get- (sometimes, with different names), but there are often other visible properties, which could correspond to datacenter-only features, deprecated features, features not yet released, etc.

Coming from the other direction as Dario describes, if Get- shows a property that's available on New- or Set- as a parameter, we'll definitely document that parameter in New- or Set-.
