### ISSUE TITLE
New-QuarantinePolicy Example 2 isn't working

### ISSUE THREAD

**Issue by JAmler** [MicrosoftDocs/office-docs-powershell#8507]
Hello,

if I try to run example 2 I get this error:

```powershell
Cannot process argument transformation on parameter 'EndUserQuarantinePermissions'. Cannot convert value
"[PermissionToBlockSender: True
PermissionToDelete: True
PermissionToDownload: False
PermissionToPreview: True
PermissionToRelease: False
PermissionToRequestRelease: True
PermissionToViewHeader: False ]" to type "Microsoft.Exchange.Data.Quarantine.QuarantinePermissions". Error: "Cannot
convert the "[PermissionToBlockSender: True
PermissionToDelete: True
PermissionToDownload: False
PermissionToPreview: True
PermissionToRelease: False
PermissionToRequestRelease: True
PermissionToViewHeader: False ]" value of type "Deserialized.Microsoft.Exchange.Data.Quarantine.QuarantinePermissions"
to type "Microsoft.Exchange.Data.Quarantine.QuarantinePermissions"."
+ CategoryInfo : InvalidData: (:) [New-QuarantinePolicy], ParameterBindin...mationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,New-QuarantinePolicy
+ PSComputerName : outlook.office365.com
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9fe91ff-c0d0-2e05-132b-c8dc2dd5d7fc
* Version Independent ID: 9adb041d-c4ed-92df-8221-b6ad079a1606
* Content: [New-QuarantinePolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-quarantinepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-QuarantinePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-QuarantinePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Kindly update.

**Comment by n0rbie** [comment]
Also having the same issue.

**Comment by chrisda** [comment]
Still looking into it. Nothing to report so far.

**Comment by chrisda** [comment]
The EndUserQuarantinePermissions parameter is definitely not working. There are plans to fix it, but no ETA, so I removed any examples in New/Set-QuarantinePolicy that used it, and I changed the description of the EndUserQuarantinePermissions parameter to "reserved for internal Microsoft use".

Thanks for the feedback.

Closing
