### ISSUE TITLE
New-ExoPSSession - Create Powershell Session is failed using OAuth

### ISSUE THREAD

**Issue by pinigo-tr** [MicrosoftDocs/office-docs-powershell#8508]
Hi,

Please pay attention that once connecting to ExchangeOnline using `Connect-ExchangeOnline  -UserPrincipalName`
You may get the following exception and then you'll need to update the registry settings below:

**Exception**:

```powershell
New-ExoPSSession: C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\netCore\ExchangeOnlineManagement.psm1:475
Line |
 475 |  … PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro …                                                                                     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                       | Create Powershell Session is failed using OAuth                                              
```

**Solution**:

```text
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client] “AllowBasic”=dword:00000001
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@pinigo-tr Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
