### ISSUE TITLE
New-TenantAllowBlockListItems: A parameter cannot be found that matches parameter name 'Allow'

### ISSUE THREAD

**Issue by beercity** [MicrosoftDocs/office-docs-powershell#8518]
A prior issue #8258 was opened for problems with the -Allow parameter. It was suggested to use -Allow instead of -Action Allow.
-Allow does not work either.

This is a pretty critical cmdlet to have working because of the Secure By Default changes that are rolling out to tenants now. With this command not working, this creates a much higher amount of manual work.

**Comment by dariomws** [comment]
Hi @beercity, thank you for your feedback.

Allow parameter worked for me:
![image](https://user-images.githubusercontent.com/33589238/140034256-865dd54b-2b56-40e0-9733-1f4562a878ca.png)

But please have in mind that this cmdlet is still in preview, please check the note at the begging of the article.

Thank you again!

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @beercity Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
