### ISSUE TITLE
Get-CsTenant - modern version lacks information

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/office-docs-powershell#8524]
From the release notes of v2.5.1 of the Teams Online PowerShell module:
"Modernized versions of Get-CsTenant and Get-CsOnlineUser (with -identity parameter only) have been released.
They no longer emit deprecated properties and have some formatting changes compared to their remoting counterparts."

Get-CsTenant used to return the DomainUrlMap attribute showing domains that had finished background provisioning for Skype Online (and Teams).
Sometimes, especially when users have been activated with Skype licenses prior to setting up Skype for the domain, this provisioning does not occur, or takes a long time to be done.
This information is important when troubleshooting telephony with Direct Routing since telephony will never work unless the provisioning is complete.

Since this attribute was removed, we do not have any way of quering if the backend provisioning is completed, so we'd like either the attribute returned, or an alternate way of determining the provisioning status.

**Comment by dariomws** [comment]
Hi @donlassini, thank you for your feedback.

There is a note about this issue in the following article:
https://docs.microsoft.com/microsoftteams/direct-routing-connect-the-sbc

The note:
"In addition to the domain registered in your tenant, it's important that there's a user with that domain and an assigned E3 or E5 license. If not, you'll receive the following error:
Can not use the "sbc.contoso.com" domain as it was not configured for this tenant."

Once you assign the license, you should be able to add the sbc after a few minutes, but it could take 24 hours.

**Comment by donlassini** [comment]
Thank you - I am aware of that requirement. This is not about the requirements, but monitoring for success.

The issue is - when we did everything we had to, we could see in the .domainurlmap attribute if backend provisioning for the domain had finished. So we used that to see if we still had to wait.

"....you should be able to add the sbc after a few minutes, but it could take 24 hours."
**That's** what we could monitor - if that had completed, the domain would be listed in that attribute, so by script, we could immediately see if it would work or not.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @donlassini Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
