### ISSUE TITLE
Perhaps incorrect function on Teams PS module [2.6.0]

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#8526]
Hey,

Not sure, but for me this looks a bit odd function:

```
PS C:\> Get-Command Grant-CsPolicy

CommandType     Name                        Version    Source
-----------     ----                        -------    ------
Function        Grant-CsPolicy              2.6.0      MicrosoftTeams
```

Could it be so, there should be the definition of what policy that applies?

**Comment by dariomws** [comment]
Hi @Petri-X, thank you for your feedback.

This cmdlet and others were reported a few months ago so the product team is aware of it:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/7186

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @Petri-X Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
