### ISSUE TITLE
Get-UnifiedGroup powershell commandlet does not renew the access token for long running queries

### ISSUE THREAD

**Issue by RayGHeld** [MicrosoftDocs/office-docs-powershell#8527]
This commandlet does not renew the access token for a long running query causing people with many groups in their tenant to not be able to finish the request.  The commandlet should detect an expired token and renew while performing paging.

**Comment by dariomws** [comment]
@RayGHeld - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @RayGHeld 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by RayGHeld** [comment]
I opened this on behalf of a customer who put in a support ticket to our team.

**Comment by dariomws** [comment]
Thank you @RayGHeld.

The best way to report these issues is with a support ticket, and if your customer has done it that's all. Here we are limited to documentation issues and improvements.
