### ISSUE TITLE
*-CS cmdlets not recognized

### ISSUE THREAD

**Issue by wagenveld** [MicrosoftDocs/office-docs-powershell#8530]
After upgrading to Windows 11 and installing the latest MicrosoftTeams module (also tried preview) none of the CS cmdlets are recognized. 
Get-CsMeetingRoom
Get-CsMeetingRoom : The term 'Get-CsMeetingRoom' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Get-CsMeetingRoom
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-CsMeetingRoom:String) [Get-CsMeetingRoom], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I've tried connecting using Connect-MicrosoftTeams -UseDeviceAuthentication to no avail. According to Get-Command they are available: 
Function        Get-CsIPPhonePolicy                                2.6.1      MicrosoftTeams
Function        Get-CsMeetingConfiguration                         2.6.1      MicrosoftTeams
Function        Get-CsMeetingMigrationStatus                       2.6.1      MicrosoftTeams
Function        Get-CsMeetingRoom                                  2.6.1      MicrosoftTeams
Function        Get-CsMobilityPolicy                               2.6.1      MicrosoftTeams

**Comment by dariomws** [comment]
Hi @wagenveld, thank you for your feedback.

I have Windows 11 on my machine and I can use version 2.6.0 with the CS cmdlets.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @wagenveld 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
