### ISSUE TITLE
No documentation for AllowCartCaptionsScheduling

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#8533]
Hi,

Microsoft has released the support for Cart Captions:
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=70588

And PS version 2.6.0 support following parameter:
Set-CsTeamsMeetingPolicy -AllowCartCaptionsScheduling
But unfortunately there are no documentation available for this parameter.

rgs
Petri-x

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
#8544

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution. @Petri-X Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
