### ISSUE TITLE
10 item limit on Purge needs to be increased

### ISSUE THREAD

**Issue by JohnIPFX** [MicrosoftDocs/office-docs-powershell#8538]
As this is a replacement for the deprecated search-mailbox - the 10-item limit increases the time required to clean up a users mailbox from minutes to weeks due to time per purge (approx 1-2mins per 10  items) as well as connection issues while running a looping script.

Is there a feature request for this limit to be raised to be more in line with how search-mailbox used to work?

**Comment by dariomws** [comment]
Hi @JohnIPFX, thank you for your feedback.

For feature requests, I suggest that you try with [Tech Community](https://techcommunity.microsoft.com/) as here we are limited to documentation issues and improvements.

**Comment by yogkumgit** [comment]
@JohnIPFX Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
