### ISSUE TITLE
Be nice if you would specify what Module you need to include

### ISSUE THREAD

**Issue by RickFoster** [MicrosoftDocs/office-docs-powershell#8545]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5afe8f19-b64e-354f-b363-e040db2a1e8c
* Version Independent ID: 0d5fde8a-2882-c935-1af4-e9c31c216fd4
* Content: [Get-GlobalAddressList (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-globaladdresslist?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-GlobalAddressList.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-GlobalAddressList.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@RickFoster, I presume you're trying to connect to Exchange Online PowerShell? Exchange PowerShell has many hundreds of cmdlets that are shared between on-premises Exchange Sever and Exchange Online. The Exchange Online only cmdlet topics have an alert in the introduction about the [EXO V2 module](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2). I didn't want to add that same banner to shared cmdlet topics, as it seemed kind of insulting to people with on-premises Exchange.

**Comment by RickFoster** [comment]
Thanks for replying, I did find I needed to use EXO, but it took some more searching.

While I have your attention 😉  what causes the Get-GlobalAddressList to only return the “RecipientFilter” but no Recipients (see insert below)?

Any help is much appreciated, thanks

Rick Foster
Data Manager
520-225-6309
Tucson Unified School District


***@***.***

**Comment by chrisda** [comment]
I never thought of it that way before. I guess it makes sense that the actual list of recipients isn't stored in the GAL object, because the RecipientFilter defines who's in the GAL, and that could change from moment to moment.

**Comment by yogkumgit** [comment]
@RickFoster Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
