### ISSUE TITLE
ArchiveName doesn't work in Outlook

### ISSUE THREAD

**Issue by deividfoggi** [MicrosoftDocs/office-docs-powershell#8552]
Regarding the parametero _-ArchiveName_ the doc states the following:

The ArchiveName parameter specifies the name of the archive mailbox. This is the name displayed to users in **Outlook** and Outlook Web App.

But Outlook ignores it and uses the pattern "Online Archive - PrimarySMTPAddress". Outlook on the web respect the value you insert using the parameter -ArchiveName.

Is this doc incorrect or is there a bug in Outlook? Please consider the same for Enable-Mailbox cmdle.t

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f835af-5905-368a-df68-6646782ad807
* Version Independent ID: 153ce2d2-dab5-9c8f-c511-ee3bc8ee2dbc
* Content: [Set-Mailbox (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@deividfoggi, not completely related to your question, but here's what I determined through testing:

- The default archive names are slightly different based on Exchange version:
  - Exchange Online: `In-Place Archive -<Display Name>` (note the missing space after '-')
  - Exchange 2016 and 2019: `In-Place Archive -<Display Name>` (note the missing space after '-')
  - Exchange 2013: `In-Place Archive - <Display Name>`
  - Exchange 2010: `Personal Archive - <Display Name>`
 - ArchiveName on Set-Mailbox works fine in on-prem Exchange and Exchange Online to update the name of an existing archive.

But you're saying that the name of the archive in Outlook is always `Online Archive - PrimarySMTPAddress`? Can you give me some more context about where you see the archive name in Outlook? And you're saying that the custom name is shown in those same situations in Outlook on the web (OWA)?

**Comment by chrisda** [comment]
I think I figured it out. In addition to updating the default names as previously described, I added the following text in Enable-Mailbox and Set-Mailbox:

In Outlook in Exchange Online, the value of this parameter is ignored. The name of the archive mailbox that's shown in the folder list is `Online Archive - <PrimarySMTPAddress>`.

**Comment by deividfoggi** [comment]
Hi Chris,

You got it. Thanks to adjust the doc.

Regards.

**Comment by yogkumgit** [comment]
@deividfoggi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
