### ISSUE TITLE
Issue with Grant-CsTenantDialPlan

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/office-docs-powershell#8554]
** This seems to be the Microsoft Docs GitHub, but I can't seem to find the MicrosoftTeams PowerShell module github to log an actual issue. If this isn't the correct GitHub account, can you please point me to it.

--- 

When trying to add or remove a Tenant Dial Plan using `Grant-CsTenantDialPlan` to/from a resource account I'm hitting the following errors. 

Other testing/notes
- Tested under PowerShell v5.1 using an elevated PowerShell ISE on Windows 11 21H2 22000.258
- Only applies to resource accounts (user accounts are OK - Except V2.6.1-Preview)
- Tested on the following Microsoft Teams PowerShell module versions
  - V2.3.0 - Working OK
  - V2.5.1 - Error as below
  - V2.6.0 - Error as below 
  - V2.6.1(Preview) - Error as below

### Error for V2.5.1 & V2.6.0
When running the command `Grant-CsTenantDialPlan -Identity "$UserUPN" -PolicyName $null` you get the following error
```
Grant-CsTenantDialPlan : [ClientError] : User does not exist
At line:1 char:1
+ Grant-CsTenantDialPlan -Identity "$UserUPN" -PolicyName $null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Grant-CsTenantDialPlan], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Teams.ConfigApi.Cmdlets.GrantCsTenantDialPlan
```

### Error for V2.6.1-Preview
When running the command `Grant-CsTenantDialPlan -Identity "$UserUPN" -PolicyName $null` you get the following error
```
The term 'Grant-CsUserPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
````
However when running the command `Get-Command -Module MicrosoftTeams`, it's showing `Grant-CsTenantDialPlan` as there and available

**Comment by dariomws** [comment]
@jantoney - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @jantoney Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
