### ISSUE TITLE
Wrong text

### ISSUE THREAD

**Issue by skrubbeltrang** [MicrosoftDocs/office-docs-powershell#8556]
The page states:
-Identity
The Identity parameter specifies the DLP policy you want to remove. 

The Get-DlpPolicy CmdLet does not remove DLP policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7affb903-e8d2-d47b-2028-342cf76136cc
* Version Independent ID: b2b85792-5021-0b20-ae26-bf129d69acca
* Content: [Get-DlpPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-dlppolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-DlpPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-DlpPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@skrubbeltrang, fixed. In the future, you too can make fixes like this yourself; no need to open an Issue first. For instructions, go [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md).

Thanks for the feedback.

Closing
