### ISSUE TITLE
Clarify Example 1 + Enabled parameter

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/office-docs-powershell#8566]
When discussing the -Enabled parameter, and in Example 1 should note that disabling the junk mail folder configuration **will have no effect for Exchange Online mailboxes** (the Enabled $false parameter is ignored by Exchange Online Protection as documented [here](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes?view=o365-worldwide)). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e95bf3-e9dc-b528-b4ce-8dae3db5f141
* Version Independent ID: e6bf871e-eb81-ef60-9454-6f895e1bccde
* Content: [Set-MailboxJunkEmailConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxjunkemailconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxJunkEmailConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-MailboxJunkEmailConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hudish, I clarified Example 1 and elsewhere re: enabling/disabling the junk email rule and the effect on mailboxes in on-premises Exchange vs. the cloud.

Thanks for the feedback.

Closing
