### ISSUE TITLE
Print AllowTeamsConsumer in the output

### ISSUE THREAD

**Issue by ParaGlideRocks** [MicrosoftDocs/office-docs-powershell#8567]
The status of the property AllowTeamsConsumer is not listed when you run the cmdlet.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b929fe13-9ac8-ce73-f331-5c4ce1d08640
* Version Independent ID: 4042cf42-2b7b-f3f1-34a6-fc615c78229b
* Content: [Get-CsTenantFederationConfiguration (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-cstenantfederationconfiguration?view=skype-ps&source=docs)
* Content Source: [skype/skype-ps/skype/Get-CsTenantFederationConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTenantFederationConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by BJGGut3** [comment]
Both AllowTeamsConsumer and AlowTeamsConsumerInbound show for me in version 2.6.0

**Comment by dariomws** [comment]
@BJGGut3, thank you for your feedback and the confirmation that you can see these parameters now.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @ParaGlideRocks Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
