### ISSUE TITLE
PSSessionOption not working

### ISSUE THREAD

**Issue by gh0stwalker** [MicrosoftDocs/office-docs-powershell#8578]
I created a new PSSession Option:
_$pso = New-PSSessionOption -IdleTimeout -1_

But when I use the command it fails:
Connect-ExchangeOnline -PSSessionOption $pso

    Connect-ExchangeOnline : Cannot retrieve the dynamic parameters for the cmdlet. Method invocation failed because [Microsoft.Exchange.Management.AdminApiProvider.Utility] does not contain a method
    named 'IsCloudShellEnvironment'.
    At line:1 char:1
    + Connect-ExchangeOnline -PSSessionOption $pso
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidArgument: (:) [Connect-ExchangeOnline], ParentContainsErrorRecordException
        + FullyQualifiedErrorId : GetDynamicParametersException,Connect-ExchangeOnline

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gh0stwalker, send your logs to the following email address using the following procedure:

When you report an issue at `exocmdletpreview[at]service[dot]microsoft[dot]com`, be sure to include the log files in your email message. To generate the log files, replace \<Path to store log file\> with the output folder you want, and run the following command:

```powershell
Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All

**Comment by gh0stwalker** [comment]
@chrisda Not sure what I did, but it's working now. I did do an update of the module so it's possibly that.

**Comment by yogkumgit** [comment]
@gh0stwalker Thanks. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
