### ISSUE TITLE
Get-CsOnlineUser consumes all RAM in large tenant

### ISSUE THREAD

**Issue by jformacek** [MicrosoftDocs/office-docs-powershell#8580]
Hello,
I have tenant with 230K+ Teams users. Need to load subset of information about all of them to external system. Running the following:

```powershell
$users=Get-CsOnlineUser -ResultSize unlimited `
| select sipaddress,UserPrincipalName,TeamsUpgradeEffectiveMode,`
 TeamsMeetingPolicy,TeamsCallingPolicy
```
Using MicrosoftTeams module 2.6.0.
On machine with 16GB RAM, running this command consumes all RAM and powershell session crashes. On machine with 48GB RAM, it causes WinRM to crash.
Problem is likely caused by the fact that command does not send retrieved users to pipeline as they are read from tenant, but keeps them in memory until complete resultset is retrieved, before sending the object to pipeline.

MicrosoftTeams module version 2.3.1 worked fine and we were able to run command above with consumption of <2GB of RAM.

Question: is there a way how to process all users in tenant with latest of module without excessive RAM consumption, similar to how it's don in 2.3.1

Thanks
Jiri

**Comment by dariomws** [comment]
@jformacek - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @jformacek 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
