### ISSUE TITLE
AllowTeamsConsumerInbound parameter missing

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#8581]
**[MC296208](https://portal.office.com/adminportal/home?#/MessageCenter/:/messages/MC296208) Chat with users with Teams personal accounts** states as follows:

> If you would like to opt-out from this functionality you would be able to do so via the Teams admin portal under the External Access section. Optionally you could use PowerShell commands to opt-out all users or individual users from this functionality. 
> 
> Settings to update:
> 
> Tenant level: CsTenantFederationConfiguration
> 
> AllowTeamsConsumer
> AllowTeamsConsumerInbound
> User level: CsExternalAccessPolicy
> 
> EnableTeamsConsumerAccess
> EnableTeamsConsumerInbound

The parameter AllowTeamsConsumerInbound is missing.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06796aa5-dd45-a0e9-b6f1-c2786abd8036
* Version Independent ID: 1ef8e42a-4405-5e99-b2ac-547d60b53a70
* Content: [Set-CsTenantFederationConfiguration (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by BJGGut3** [comment]
I was able to use both the AllowTeamsConsumer and AllowTeamsConsumerInbound parameters with version 2.6.0

**Comment by Markus-Hanisch** [comment]
@BJGGut3 
You got me wrong. 
These parameters can be used. However, they are not mentioned in the Cmdlet documentation.

**Comment by BJGGut3** [comment]
> @BJGGut3 You got me wrong. These parameters can be used. However, they are not mentioned in the Cmdlet documentation.

I see - apologies

**Comment by dariomws** [comment]
Hi @Markus-Hanisch, thank you for your feedback.

@tomkau, could you kindly help here? Thanks!

**Comment by yogkumgit** [comment]
@tomkau Please help us in resolving this issue. Thanks

**Comment by dariomws** [comment]
@Markus-Hanisch @BJGGut3 work is in progress. You'll see the updates in this article a few hours after the following pull request is merged:
https://github.com/MicrosoftDocs/office-docs-powershell/pull/8667

**Comment by yogkumgit** [comment]
closing via 8667,
