### ISSUE TITLE
Get-CsTenantFederationConfiguration missing parameters

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/office-docs-powershell#8582]
I couldn't retrieve an equivalent in the Teams PowerShell module documentation and because the Skype PowerShell module documentation of [Set-CsTenantFederationConfiguration](https://docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps) already states the parameter [-AllowTeamsConsumer <Boolean>] I presume that this documentation applies to Teams PowerShell as well.
Therefore, the [Get-CsTenantFederationConfiguration](https://docs.microsoft.com/en-us/powershell/module/skype/get-cstenantfederationconfiguration?view=skype-ps) documentation should also state the parameters that got returned by means of PowerShell:
```powershell
PS C:\WINDOWS\System32> Connect-MicrosoftTeams
PS C:\WINDOWS\System32> Get-CsTenantFederationConfiguration | Get-Member -MemberType Properties


   TypeName: Deserialized.Microsoft.Rtc.Management.WritableConfig.Settings.Edge.TenantFederationSettings

Name                                MemberType   Definition                                                                                                   
----                                ----------   ----------                                                                                                   
XsAnyAttributes                     NoteProperty string XsAnyAttributes=                                                                                      
XsAnyElements                       NoteProperty string XsAnyElements=                                                                                        
AllowedDomains                      Property     Deserialized.Microsoft.Rtc.Management.WritableConfig.Settings.Edge.AllowAllKnownDomains {get;set;}           
AllowFederatedUsers                 Property     System.Boolean {get;set;}                                                                                    
AllowPublicUsers                    Property     System.Boolean {get;set;}                                                                                    
AllowTeamsConsumer                  Property     System.Boolean {get;set;}                                                                                    
AllowTeamsConsumerInbound           Property     System.Boolean {get;set;}                                                                                    
Anchor                              Property     System.String {get;set;}                                                                                     
BlockedDomains                      Property     Deserialized.Microsoft.Rtc.Internal.XsdClassGenerator.ListWithEvents`1[[Microsoft.Rtc.Management.WritableC...
DataSource                          Property     System.String {get;set;}                                                                                     
Element                             Property     System.String {get;set;}                                                                                     
Identity                            Property     System.String {get;set;}                                                                                     
Key                                 Property     System.String {get;set;}                                                                                     
ScopeClass                          Property     System.String {get;set;}                                                                                     
SharedSipAddressSpace               Property     System.Boolean {get;set;}                                                                                    
TreatDiscoveredPartnersAsUnverified Property     System.Boolean {get;set;}                                                                                    
TypedIdentity                       Property     System.String {get;set;}                                                                                    

```

relates to: #8581 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b929fe13-9ac8-ce73-f331-5c4ce1d08640
* Version Independent ID: 4042cf42-2b7b-f3f1-34a6-fc615c78229b
* Content: [Get-CsTenantFederationConfiguration (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-cstenantfederationconfiguration?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsTenantFederationConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTenantFederationConfiguration.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by dariomws** [comment]
Hi @Markus-Hanisch, thank you for your feedback.

I'm trying to get more information about AllowTeamsConsumerInbound.

**Comment by Markus-Hanisch** [comment]
@dariomws 
In issue #8581 I habe added the related message center ID.

**Comment by dariomws** [comment]
@Markus-Hanisch, yes I read it but, what TeamsConsumerInbound does? I can suppose that it allows or deny inbound communications from Teams Consumer accounts but I want to confirm. We can use it with Set/New-CsExternalAccessPolicy either.

**Comment by Markus-Hanisch** [comment]
Thank you for your support in here, @dariomws

**Comment by dariomws** [comment]
Fixing type:
"We can't use it with Set/New-CsExternalAccessPolicy either."

**Comment by yogkumgit** [comment]
@tomkau Please help us in resolving this issue. Thanks

**Comment by tiburd** [comment]
17 November 2021: I sent email to tomkau.

**Comment by dariomws** [comment]
Same as https://github.com/MicrosoftDocs/office-docs-powershell/issues/8581.

**Comment by yogkumgit** [comment]
closing as same as 8581
