### ISSUE TITLE
Set-MailboxAutoReplyConfiguration - cannot set starttime and endtime

### ISSUE THREAD

**Issue by LesAtGamma** [MicrosoftDocs/office-docs-powershell#8592]
I'm using the ExchangeOnlineManagement v2.0.6-preview3 module, and we have the Basic Auth disabled in WinRM.

I can set the out of office reply to enabled, disabled, and scheduled fine. BUt when I try to set the start or end time, it errors:

Verify-Waiting : {"error":{"code":"UnsupportedMediaType","message":"A supported MIME type could not be found that matches the acceptable MIME types for the request. The supported type(s) 'text/plain' do not match any of the acceptable MIME types 
'application/json'.","innererror":{"message":"A supported MIME type could not be found that matches the acceptable MIME types for the request. The supported type(s) 'text/plain' do not match any of the acceptable MIME types 
'application/json'.","type":"Microsoft.OData.ODataContentTypeException","stacktrace":"   at Microsoft.OData.MediaTypeUtils.GetContentTypeFromSettings(ODataMessageWriterSettings settings, ODataPayloadKind payloadKind, ODataMediaTypeResolver 
mediaTypeResolver, ODataMediaType& mediaType, Encoding& encoding)\r\n   at Microsoft.OData.ODataMessageWriter.EnsureODataFormatAndContentType()\r\n   at Microsoft.OData.ODataMessageWriter.SetOrVerifyHeaders(ODataPayloadKind payloadKind)\r\n   at 
Microsoft.OData.ODataMessageWriter.WriteToOutput(ODataPayloadKind payloadKind, Action`1 writeAction)\r\n   at Microsoft.Exchange.Admin.OData.Core.Handlers.BatchHandler.Process(IODataRequestMessage requestMessage, IODataResponseMessage responseMessage)\r\n  
 at Microsoft.Exchange.Admin.OData.Core.Handlers.RequestHandler.Process(Stream requestStream)"}}}
At C:\...\tmpEXO_jmk1jaw1.4f0.psm1:863 char:32
+                 $isRetryable = Verify-Waiting $retryCount $_
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Verify-Waiting
 
Deserialize-BatchRequest : Cannot bind argument to parameter 'BatchResponse' because it is null.
At C:\...\tmpEXO_jmk1jaw1.4f0.psm1:13063 char:38
+             Deserialize-BatchRequest $BatchResponse
+                                      ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Deserialize-BatchRequest], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Deserialize-BatchRequest

**Comment by chrisda** [comment]
@LesAtGamma, since the v2.0.6 module is in Preview, use the following procedure to ask your question:

 ## Report bugs and issues for the EXO V2 module

When you report an issue at `exocmdletpreview[at]service[dot]microsoft[dot]com`, be sure to include the log files in your email message. To generate the log files, replace \<Path to store log file\> with the output folder you want, and run the following command:

```powershell
Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All
```

**Comment by LesAtGamma** [comment]
Thanks @chrisda - I've attached the generated log file.

As mentioned in my initial post, we're not using Basic Auth, but I'm authenticating using a certificate.

[EXOCmdletTelemetry-20211115-092339.csv](https://github.com/MicrosoftDocs/office-docs-powershell/files/7537478/EXOCmdletTelemetry-20211115-092339.csv)

**Comment by chrisda** [comment]
@LesAtGamma, did you send the attached log to that email address I showed you? That's where/how you get support, in particular since you're using a preview version of the module. We just update documentation here.

**Comment by LesAtGamma** [comment]
Thanks @chrisda - I have now!

**Comment by yogkumgit** [comment]
@LesAtGamma Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
