### ISSUE TITLE
How long do we need to wait

### ISSUE THREAD

**Issue by RascoPK** [MicrosoftDocs/office-docs-powershell#8594]
I am constantly getting error: Access Denied

How should we wait for permissions to replicate?

My full error:
New-ExoPSSession : Connecting to remote server outlook.office365.com failed with the following error message : Access
is denied. For more information, see the about_Remote_Troubleshooting Help topic.
At C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\netFramework\ExchangeOnlineManagement.psm1:475 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-ExoPSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Exchang
   e.Management.ExoPowershellSnapin.NewExoPSSession

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=%28ir__1s0ydsjsgwkft2xwkk0sohzg232xi2l0vj021g0200%29%287593%29%281243925%29%28je6NUbpObpQ-ps4lsqdM.0_11NUHJklrFw%29%28%29&irclickid=_1s0ydsjsgwkft2xwkk0sohzg232xi2l0vj021g0200#setup-app-only-authentication&ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-ps4lsqdM.0_11NUHJklrFw&epi=je6NUbpObpQ-ps4lsqdM.0_11NUHJklrFw)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@RascoPK, make sure that you're using the latest version of the module (v2.0.5) and send information using the instructions below:

## Report bugs and issues for the EXO V2 module

When you report an issue at `exocmdletpreview[at]service[dot]microsoft[dot]com`, be sure to include the log files in your email message. To generate the log files, replace \<Path to store log file\> with the output folder you want, and run the following command:

```powershell
Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All
```

**Comment by RascoPK** [comment]
I am getting this error message: 

"
Set-ExoAppSettings : A parameter cannot be found that matches parameter name 'ExchangeEnvironmentName'.
At C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.6\netFramework\ExchangeOnlineManagement.psm1:600 char:186
+ ... kPerformance $TrackPerformance.Value -ExchangeEnvironmentName $Exchan ...
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-ExoAppSettings], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Exchange.Management.RestApiClient.SetExoAppSettings
"

**Comment by chrisda** [comment]
@RascoPK, so it appears you updated to the v2.0.6-Preview3 version of the module, which basically prevents you from getting help by opening a support case. Send a message and your logs to that email address I provided earlier.

**Comment by yogkumgit** [comment]
@RascoPK Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
