### ISSUE TITLE
Replacing Transport Rule Allow and Block list with TABL

### ISSUE THREAD

**Issue by Raj-MCITP** [MicrosoftDocs/office-docs-powershell#8596]
We have bunch of Sender address and domains with blocked and allowed (bypass spam) list and planning to replace with TABL. what exactly will be benefit and how many New-TenantAllowBlockListItems can be created per tenant ? 

25 New-TenantAllowBlockListItems can be created with 20 entries in each ? and a max of only 500 senders can only be added per tenant as a blocked or Allowed senders/domain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60b5c4e-7698-eefc-e515-ff6c59689e05
* Version Independent ID: 66daa134-52e6-dc2d-52f7-920718a6f0ff
* Content: [New-TenantAllowBlockListItems (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-tenantallowblocklistitems?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-TenantAllowBlockListItems.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by andypunt** [comment]
That is correct for Blocks. Allows are slightly different in that they must be added via the submission process and it is managed by the system. If we agree with the FP and are able to update the system so that it naturally allows the item, the allow will be removed.

**Comment by yogkumgit** [comment]
@chrisda Please add your comment. Thanks

**Comment by chrisda** [comment]
@yogkumgit, I have no comment. Andy was the feature owner of TABL.

**Comment by yogkumgit** [comment]
@chrisda Please tag Andy here. I am not sure about his Github alias. Thanks

**Comment by chrisda** [comment]
The previous comment (andypunt) was Andy.

**Comment by yogkumgit** [comment]
@andypunt Please help. Thanks

**Comment by andypunt** [comment]
As stated, I no longer work on that team, but I already answered the question. Not sure what else there was.

**Comment by yogkumgit** [comment]
@Raj-MCITP Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
