### ISSUE TITLE
Set-CsOnlineDialInConferencingUser Can't Modify Conference ID in manual mode with " -ConferenceId 8271964" Parameter

### ISSUE THREAD

**Issue by platinarock** [MicrosoftDocs/office-docs-powershell#8597]
Set-CsOnlineDialInConferencingUser

[Can't Modify Conference ID in manual mode with " -ConferenceId 8271964" Parameter]

When i modified conference ID in manual mode , conference ID stay at '0' value .

Have you an idea for this ? 

Thanks 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1346667-4316-343c-df7e-62bd41182d0a
* Version Independent ID: 626fd6f0-1a91-cae2-b5ca-083688a2ce39
* Content: [Set-CsOnlineDialInConferencingUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinedialinconferencinguser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineDialInConferencingUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineDialInConferencingUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by dariomws** [comment]
@platinarock - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @platinarock Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
