### ISSUE TITLE
"Filter users based on an existing attribute" Examples do not work.

### ISSUE THREAD

**Issue by jeff-bb** [MicrosoftDocs/office-docs-powershell#8603]
Cannot process argument transformation on parameter 'Identity'. Cannot convert the "X" value of type "Deserialized.Microsoft.Exchange.Data.Directory.Management.User" to type "Microsoft.Exchange.Configuration.Tasks.UserIdParameter".

As written, the example does not work. I've modified locally to use "foreach {Set-User -Identity $_.WindowsEmailAddress -RemotePowerShellEnabled $false}", which does work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d193a89-ffbc-90ab-990e-0e36b7845496
* Version Independent ID: 12a028e5-d1ce-12ab-2da8-c46d4815754c
* Content: [Enable or disable access to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/disable-access-to-exchange-online-powershell?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/disable-access-to-exchange-online-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jeff-bb, confirmed. Topic updated.

Thanks for the feedback.

Closing
