### ISSUE TITLE
Will this CMDLet become available sometime?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#8609]
Hi,

Just looking for the ways to avoid 100s mouse clicks when trying customize the policies for controlling available applications. Then I found this page, but you did not share so much hope by:
_...but do not use this cmdlet..._

May I ask what is the future of this?

On the test environment I was playing with it shortly, but I could't get the reason of why this is to you so big **no no**. For example, when you use "AllowedAppList" on the types, then application IDs on the apps defines which of them are allowed and all others are blocked. And if there are no application IDs then all apps are blocked.

Isn't so that you could have the same statement for all of the CMDLets? :D

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf9ea1f-5e73-ff38-3df0-e0b277d22814
* Version Independent ID: 12c6accc-f355-33e0-0479-418e141efb74
* Content: [Set-CsTeamsAppPermissionPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsapppermissionpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsAppPermissionPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsTeamsAppPermissionPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
Hi @Petri-X, thank you for your feedback.

I'm trying to get more information about this cmdlet.

**Comment by yogkumgit** [comment]
@dariomws

**Comment by yogkumgit** [comment]
@JensTrier Kindly comment. Thanks

**Comment by JensTrier** [comment]
This is not my area, but I've pinged the person I believe owns this cmdlet

**Comment by yogkumgit** [comment]
@JensTrier kindly let us know, whom to approach for this issue. Thanks
CC : @tiburd

**Comment by JensTrier** [comment]
I'm told that the cmdlet will continue to have this status. Nothing more to add.

**Comment by Petri-X** [comment]
@JensTrier that is super sad news :(
Especially now when the latest changes on Teams apps visibility to end users. We just would like to have full control to the apps.

**Comment by yogkumgit** [comment]
@Petri-X We do understand your disappointment. As no action required here, I proceed to close this. Thanks for the feedback, Kindly keep posting the same in the future as also.
