### ISSUE TITLE
Improvement for Get-TeamsApp is required

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#8614]
Hi Teams PS team,

Do you have any plans to get more attributes out using the "Get-TeamsApp"? Today we are only getting the following: **ExternalId**, **Id**, **DisplayName** and **DistributionMethod**.

But when looking for the TAC there are lot of other details from the apps. One of the critical attribute I'm hunting is the publisher. I should be able to separate Microsoft's packages and 3rd party apps.

thanks

**Comment by dariomws** [comment]
@Petri-X - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Microsoft Teams better. They keep a close tab on user feedback and it would be awesome if you could add your voice in the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to making the docs better! Much appreciated!

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @Petri-X Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
