### ISSUE TITLE
Permissions necessary to run this command

### ISSUE THREAD

**Issue by carloxsf** [MicrosoftDocs/office-docs-powershell#8620]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75b757c9-b775-8294-91f7-870bead6a907
* Version Independent ID: 54ebab36-97bb-cd9f-6eb2-12198af885e2
* Content: [Search-UnifiedAuditLog (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/search-unifiedauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by carloxsf** [comment]
Looking in to the requirements to run this command appear to be ExchangeAdmin or Log viewer but is not specified in the doc. If you do not have this permition you will not see the command as available.

**Comment by chrisda** [comment]
@carloxsf, thankfully, this is an Exchange Online cmdlet, so the bottom of the description has this statement:

> You need to be assigned permissions before you can run this cmdlet. Although this topic lists all parameters for the cmdlet, you may not have access to some parameters if they're not included in the permissions assigned to you. To find the permissions required to run any cmdlet or parameter in your organization, see [Find the permissions required to run any Exchange cmdlet](https://docs.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions).

The advice in that topic works really well; you can see any/every role group and role that gives permissions to the cmdlet (including custom roles/role groups that we couldn't possibly know about).

We've never specifically called out every role/role group that gives access to a cmdlet; that would be a nightmare to maintain.

**Comment by yogkumgit** [comment]
@carloxsf Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
