### ISSUE TITLE
Errors connecting to teams via AccessTokens

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#8623]
I'm using version 2.6 of the MicrosoftTeams PowerShell module and trying to connect using the new AccessTokens parameter

I followed the instructions in the AccessTokens section to configure applications in O365 and found this article to be of help also - https://get-itips.capazero.net/posts/teams-powershell-token-auth

When I attempt tokens using client_credentials, I get the following error

Connect-MicrosoftTeams -AccessTokens @($graphTokenApp.access_token, $teamsTokenApp.access_token)
Connect-MicrosoftTeams : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-MicrosoftTeams -AccessTokens @($graphTokenApp.access_token, $ ...
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], NullReferenceException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams

Connect-MicrosoftTeams : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-MicrosoftTeams -AccessTokens @($graphTokenApp.access_token, $ ...
    + CategoryInfo          : NotSpecified: (:) [Connect-MicrosoftTeams], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoft
   Teams

these are my tokens

$graphTokenApp.access_token
eyJ0eXAiOiJKV1QiLCJub25jZSI6IjJNWldYUFIySDNjVXNySHJveThaMUcwTVplX1R2ZFVsenRTN3hUdi01UDgiLCJhbGciOiJSUzI1NiIsIng1dCI6Imwzc1EtNTBjQ0g0eEJWWkxIVEd3blNSNzY4MCIsImtpZCI6Imwzc1EtNTBjQ0g0eEJWWkxIVEd3blNSNzY4MCJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hNWMzMmQ0My01ZDZmLTQxYTEtYTNkYS0xMzkwMTUzODY5YjYvIiwiaWF0IjoxNjM3MjkxMTE5LCJuYmYiOjE2MzcyOTExMTksImV4cCI6MTYzNzI5NTAxOSwiYWlvIjoiRTJaZ1lQaDZTZnBsei90SHRWYzIxVXhYellpeEJRQT0iLCJhcHBfZGlzcGxheW5hbWUiOiJHcmFwaFRva2VuQXBwIiwiYXBwaWQiOiIyYTU1NjE4NS0wZDNhLTQwNGItYjBjMy1kY2VlOTc2MmZmM2IiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hNWMzMmQ0My01ZDZmLTQxYTEtYTNkYS0xMzkwMTUzODY5YjYvIiwiaWR0eXAiOiJhcHAiLCJvaWQiOiI4ZGQ3ZTdlMy1mMDllLTQwMGQtYmRjOC04OWZhNzA2NjdhNjMiLCJyaCI6IjAuQVJnQVF5M0RwVzlkb1VHajJoT1FGVGhwdG9WaFZTbzZEVXRBc01QYzdwZGlfenNZQUFBLiIsInJvbGVzIjpbIkFwcENhdGFsb2cuUmVhZFdyaXRlLkFsbCIsIkdyb3VwLlJlYWRXcml0ZS5BbGwiLCJVc2VyLlJlYWQuQWxsIl0sInN1YiI6IjhkZDdlN2UzLWYwOWUtNDAwZC1iZGM4LTg5ZmE3MDY2N2E2MyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6ImE1YzMyZDQzLTVkNmYtNDFhMS1hM2RhLTEzOTAxNTM4NjliNiIsInV0aSI6Im1GdUgyRnBHX1VXbHpHXzh0aHA5QUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjA5OTdhMWQwLTBkMWQtNGFjYi1iNDA4LWQ1Y2E3MzEyMWU5MCJdLCJ4bXNfdGNkdCI6MTQ0MTIwODkwMH0.QZAjJLoWB5eTY3oUr1pnVos3ZMur26XSB45XNcFz2NAq4kiZcjdUAq-hDi0-2rTn0s5cFA1UWDonRyi6ZXNRbMhuJVrXyRDeq2JMIlpQ9TIRzW6jg6poL4ixQExP4_Ot8bVuWu7iPsTU2eJihts5fe91kw3xm2-dBIPaKNmJ_mC-Bi995oZGRw38fPvi5I_QAq-7Hbb_6bnvP_nGOV7S0IdJJgBoxSXtRBws2B4_Dla52h25LtKBgkLFcXirLnRRLv23sMTtcYbzHUfnxC7EIIkt79b0_7Fuf_LNrw5E1hrQRlowykW-NlUEu8jmF5q_rV7uks6GIYHBVgfuGkVbGg

$teamsTokenApp.access_token
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Imwzc1EtNTBjQ0g0eEJWWkxIVEd3blNSNzY4MCIsImtpZCI6Imwzc1EtNTBjQ0g0eEJWWkxIVEd3blNSNzY4MCJ9.eyJhdWQiOiI0OGFjMzViOC05YWE4LTRkNzQtOTI3ZC0xZjRhMTRhMGIyMzkiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hNWMzMmQ0My01ZDZmLTQxYTEtYTNkYS0xMzkwMTUzODY5YjYvIiwiaWF0IjoxNjM3MjkxMTE5LCJuYmYiOjE2MzcyOTExMTksImV4cCI6MTYzNzI5NTAxOSwiYWlvIjoiRTJaZ1lGaHluNkhBL05MUE9OV1BJVXVtV1FxbEF3QT0iLCJhcHBpZCI6IjJhNTU2MTg1LTBkM2EtNDA0Yi1iMGMzLWRjZWU5NzYyZmYzYiIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2E1YzMyZDQzLTVkNmYtNDFhMS1hM2RhLTEzOTAxNTM4NjliNi8iLCJvaWQiOiI4ZGQ3ZTdlMy1mMDllLTQwMGQtYmRjOC04OWZhNzA2NjdhNjMiLCJyaCI6IjAuQVJnQVF5M0RwVzlkb1VHajJoT1FGVGhwdG9WaFZTbzZEVXRBc01QYzdwZGlfenNZQUFBLiIsInJvbGVzIjpbImFwcGxpY2F0aW9uX2FjY2Vzc19jdXN0b21fc2JhX2FwcGxpYW5jZSIsImFwcGxpY2F0aW9uX2FjY2VzcyJdLCJzdWIiOiI4ZGQ3ZTdlMy1mMDllLTQwMGQtYmRjOC04OWZhNzA2NjdhNjMiLCJ0ZW5hbnRfY3RyeSI6IlVTIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6Ik5BIiwidGlkIjoiYTVjMzJkNDMtNWQ2Zi00MWExLWEzZGEtMTM5MDE1Mzg2OWI2IiwidXRpIjoibDlrQUxBbDRpazYzNHYzajNpQ0RBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiMDk5N2ExZDAtMGQxZC00YWNiLWI0MDgtZDVjYTczMTIxZTkwIl19.YdLM035FVXUdGjAZQre7Oagz5Vjhpr8_mN3k3eZWQik3CrGahOxedgBEQAcD9xEeA4eZPNHB1vVRT6rs8tN9O5ZPEcCrx6VEC_rvHNRNRWN2wCPU8TSI9p-l6Bos92tECJFkNd51Rbm59iyf9d2nIrhiUjazTe1gHMNFF-UJEocV0AUulKU3wxnQ-honYitXylz4G4DPKPlanhi7fkn_KQlptkrvHFgDURkWf5L4mAQeP4hKE3-t56Z5diQOLFcmHwWw1D29YYHpxZX5iSFf_-Gl34uvvms4f5cOdYXgvithJChTn1l1gUS0cIS8fd0ps-ta5ZVXR1n0zpuKRBGROA

and this is the code for acquiring the tokens

$tokenBody = @{
   grant_type    = "client_credentials" 
   scope         = "https://graph.microsoft.com/.default"
   client_id     = $graphTokenAppClientId
   client_secret = $graphTokenAppSecret
}
$graphTokenApp = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$tenantId/oauth2/v2.0/token" -Method POST -Body $tokenBody

$tokenBody = @{
   grant_type    = "client_credentials"
   scope		 = "48ac35b8-9aa8-4d74-927d-1f4a14a0b239/.default"
   client_id     = $graphTokenAppClientId
   client_secret = $graphTokenAppSecret
}
$teamsTokenApp = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$tenantId/oauth2/v2.0/token" -Method POST -Body $tokenBody

If I attempt using user credentials, my error is

Connect-MicrosoftTeams -AccessTokens @($graphTokenUser.access_token, $teamsTokenUser.access_token)
Connect-MicrosoftTeams : The provided tokens must have less than 180 seconds difference in the time range of
expiration.
At line:1 char:1
+ Connect-MicrosoftTeams -AccessTokens @($graphTokenUser.access_token,  ...
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], ArgumentException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams

Connect-MicrosoftTeams : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-MicrosoftTeams -AccessTokens @($graphTokenUser.access_token,  ...
    + CategoryInfo          : NotSpecified: (:) [Connect-MicrosoftTeams], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoft
   Teams

and these tokens are

$graphTokenUser.access_token
eyJ0eXAiOiJKV1QiLCJub25jZSI6ImtaTENHX183Q0pLUXBLcm5SOWloc1lWN0ZRRktJVFFGbzJsb0hSQ1h6M1kiLCJhbGciOiJSUzI1NiIsIng1dCI6Imwzc1EtNTBjQ0g0eEJWWkxIVEd3blNSNzY4MCIsImtpZCI6Imwzc1EtNTBjQ0g0eEJWWkxIVEd3blNSNzY4MCJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hNWMzMmQ0My01ZDZmLTQxYTEtYTNkYS0xMzkwMTUzODY5YjYvIiwiaWF0IjoxNjM3MjkwOTU4LCJuYmYiOjE2MzcyOTA5NTgsImV4cCI6MTYzNzI5NTA5NCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkUyWmdZTkNhWWw3WjZCWDJzcGM5YkhQTUE1VWxUaHMrSmNwR0hMWCtjN3FvNWt5d2t5Y0EiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkdyYXBoVG9rZW5Vc2VyIiwiYXBwaWQiOiJlZjI2NzYwMy1mNzBlLTQzZjktODg0ZS04NmQyNmE3NGYzYmYiLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6IkFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvZSIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjUwLjIyMC44MS4xODYiLCJuYW1lIjoiVEhFIEFkbWluIiwib2lkIjoiNTI1NGUzNmItZjg5Zi00ZTI5LTkzYTctYmNjOGZhMTIyZmJmIiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDNCRkZEOTM5NEEzOTgiLCJyaCI6IjAuQVJnQVF5M0RwVzlkb1VHajJoT1FGVGhwdGdOMkp1OE85X2xEaUU2RzBtcDA4NzhZQU1JLiIsInNjcCI6IkFwcENhdGFsb2cuUmVhZFdyaXRlLkFsbCBHcm91cC5SZWFkV3JpdGUuQWxsIFVzZXIuUmVhZCBVc2VyLlJlYWQuQWxsIHByb2ZpbGUgb3BlbmlkIGVtYWlsIiwic3ViIjoidjFjbG92aF9aZ0NnTFJSak0yb2RwUW91Yk9jRmRMaVJPRzlyRjdBeTRHOCIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6ImE1YzMyZDQzLTVkNmYtNDFhMS1hM2RhLTEzOTAxNTM4NjliNiIsInVuaXF1ZV9uYW1lIjoiYWRtaW5AdW5pbWF4bGFiLmNvbSIsInVwbiI6ImFkbWluQHVuaW1heGxhYi5jb20iLCJ1dGkiOiI0LTV3RU1ydTZreTM3ZkFpTnA0dUFRIiwidmVyIjoiMS4wIiwid2lkcyI6WyJmZTkzMGJlNy01ZTYyLTQ3ZGItOTFhZi05OGMzYTQ5YTM4YjEiLCI2MmU5MDM5NC02OWY1LTQyMzctOTE5MC0wMTIxNzcxNDVlMTAiLCJmZGQ3YTc1MS1iNjBiLTQ0NGEtOTg0Yy0wMjY1MmZlOGZhMWMiLCI2OTA5MTI0Ni0yMGU4LTRhNTYtYWE0ZC0wNjYwNzViMmE3YTgiLCJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX3N0Ijp7InN1YiI6IkZMT3liZFZUaERIMlc5cVdJNG9CRmZ4cTBRVTZTU1JRZTF4VlBvS3JuaW8ifSwieG1zX3RjZHQiOjE0NDEyMDg5MDB9.q__J5NV0rQk9HZtNXAK7DocuP_1VCicA6rcVRTWDKyRUNTqIH-PmJ4lD_SxMQ5jhFELEqm0D3Bne2DScak43fUWpwsEUZhAKCgH4Bc74gWz0yxDHNSsvNH2s_hUMOPG_YzE4r_34I5mo3FyskPCpkDWT1FWCMSSMfaqmy-oFCt6bEMdVVzcI7aUTCziJjpPwCYU8EwRIJMl1Wj8NVNB5hAQvO_3zvtGU0R_WER_wneLb0WNXDdxrCYtd7w7ePJZvyQq2UFMOPNFB84iR_CaQm55Y5ZsY36AcG3Wm9VfUAaTPh7NoCbL06yiJdCMcTOdLovNe05GZ7UrZ8q4RPTCqNg

$teamsTokenUser.access_token
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Imwzc1EtNTBjQ0g0eEJWWkxIVEd3blNSNzY4MCIsImtpZCI6Imwzc1EtNTBjQ0g0eEJWWkxIVEd3blNSNzY4MCJ9.eyJhdWQiOiI0OGFjMzViOC05YWE4LTRkNzQtOTI3ZC0xZjRhMTRhMGIyMzkiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hNWMzMmQ0My01ZDZmLTQxYTEtYTNkYS0xMzkwMTUzODY5YjYvIiwiaWF0IjoxNjM3MjkwOTU5LCJuYmYiOjE2MzcyOTA5NTksImV4cCI6MTYzNzI5NjM4MywiYWNyIjoiMSIsImFpbyI6IkFTUUEyLzhUQUFBQWc5RWJvd2g0cWJ6UHF5elFvcTU1VkpoRXNLbVFNNnVRbmxVMUFhU1pmMVE9IiwiYW1yIjpbInB3ZCJdLCJhcHBpZCI6ImVmMjY3NjAzLWY3MGUtNDNmOS04ODRlLTg2ZDI2YTc0ZjNiZiIsImFwcGlkYWNyIjoiMSIsImZhbWlseV9uYW1lIjoiQWRtaW4iLCJnaXZlbl9uYW1lIjoiSm9lIiwiaXBhZGRyIjoiNTAuMjIwLjgxLjE4NiIsIm5hbWUiOiJUSEUgQWRtaW4iLCJvaWQiOiI1MjU0ZTM2Yi1mODlmLTRlMjktOTNhNy1iY2M4ZmExMjJmYmYiLCJwdWlkIjoiMTAwM0JGRkQ5Mzk0QTM5OCIsInJoIjoiMC5BUmdBUXkzRHBXOWRvVUdqMmhPUUZUaHB0Z04ySnU4TzlfbERpRTZHMG1wMDg3OFlBTUkuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiZEVBSjliSWdBRzlNYll3RjI0SUdrS2RmRHlKZTRaUnYxc3hYc1gwYk9vbyIsInRlbmFudF9jdHJ5IjoiVVMiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiTkEiLCJ0aWQiOiJhNWMzMmQ0My01ZDZmLTQxYTEtYTNkYS0xMzkwMTUzODY5YjYiLCJ1bmlxdWVfbmFtZSI6ImFkbWluQHVuaW1heGxhYi5jb20iLCJ1cG4iOiJhZG1pbkB1bmltYXhsYWIuY29tIiwidXRpIjoiNC01d0VNcnU2a3kzN2ZBaU81NHVBUSIsInZlciI6IjEuMCIsIndpZHMiOlsiZmU5MzBiZTctNWU2Mi00N2RiLTkxYWYtOThjM2E0OWEzOGIxIiwiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiZmRkN2E3NTEtYjYwYi00NDRhLTk4NGMtMDI2NTJmZThmYTFjIiwiNjkwOTEyNDYtMjBlOC00YTU2LWFhNGQtMDY2MDc1YjJhN2E4IiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il19.kzCTb5kh6pDcxv_nUzxwjJgLrfHfKTYDV0_vUpl3yquutIaNlqf5RrJuyDJnYIKSbYZ1YZ-8BKyr486supIbUeTJwj0sUR7VeBMcGolxmWyEcN24tQNTGi5-J0uyCNy0rgR9C4n7fOXL2w0ct3-qB38rYwa5Vml2Yxrcw8qiuQtO4R5lYit90qJFbDcSvjWSEIdCtOr1TUe3EYGBflSD7VCPoID9PE5g5lVHHqRhF8vHneaW2X6wY3zS-QXtqxlZkBoEbt7Y0b4sZy3YI90FXWkRRewuDX4M7T9SzTV8gll6hmALEHPLcI4vlbPzlCTRoBYEfZkQ1luRRD9aJY_wQQ

and the way these tokens are acquired are

$tokenBody = @{
   grant_type    = "password"
   username	  	 = $userName
   password	  	 = $password
   scope         = "https://graph.microsoft.com/.default"
   client_id     = $graphTokenUserClientId
   client_secret = $graphTokenUserSecret
}
$graphTokenUser = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$tenantId/oauth2/v2.0/token" -Method POST -Body $tokenBody

$tokenBody = @{
   grant_type    = "password"
   username		 = $userName
   password		 = $password
   scope		 = "48ac35b8-9aa8-4d74-927d-1f4a14a0b239/.default"
   client_id     = $graphTokenUserClientId
   client_secret = $graphTokenUserSecret
}
$teamsTokenUser = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$tenantId/oauth2/v2.0/token" -Method POST -Body $tokenBody

What am I doing wrong on the application token and why are my user tokens not working, even though they are created right after each other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0dce05-8bfd-0bfa-3753-0eb193852703
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by nikolas-x** [comment]
There were some details posted here:

https://techcommunity.microsoft.com/t5/teams-developer/authenticating-with-an-access-token-connect-microsoftteams/m-p/2233794/page/4

Basically, tokens generated by MSAL now have a randomised 0-30 minutes added to their expiry time (i.e. now they can expire between 60 to 90 mintes) so as to reduce simultaneous refresh requests. However this was not communicated to those developing the Powershell functionality. This module requires that the two supplied tokens must expire within 180 seconds of one another. Another user worked around this by generating token A and then regenerating token B until they got one that matched. This is obviously very undesirable but the ETA on a fix is January 2022.

**Comment by dariomws** [comment]
Hi @nikolas-x @sarollins, thank you for your feedback.

This is a well-known issue, the product team is aware of it. If you want to report it the best way forward is if you open a service ticket in your tenant.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by nikolas-x** [comment]
Hi @dariomws 

Thanks for the information. This issue was addressed in version 3.0 of the Teams module according to the patch notes but if I come across it again I will report it.

**Comment by dariomws** [comment]
Some more information:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/8194

If you share your result after trying it, I will appreciate it. Thanks!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by MatsAnd** [comment]
Hi @yogkumgit, 
I had the same issue when connecting with a service principal, so I reached out to Microsoft support about this, and got this response:

> I discussed with the software engineer managers yesterday on regards this as mentioned you are the second customer which is telling me this.
> He responded me that this is due an regression and that is the reason that is working only on 2.3.1-preview as they are currently fixing it, he also mentioned: "Currently we support access tokens only for users and not for application yet".

When asked for an ETA on when support for service principals/applications is re-added, i got the following ETA:

> It will be fore March 2022, I have shared all this feedback with the software engineering manager but currently that is the estimated time for resolution.
