### ISSUE TITLE
More information required regarding audio file format plus removal instructions missing.

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/office-docs-powershell#8628]
We tried implementing SpokenName last week and according to the page, it accepts two formats. WMA and PCM. The command only accepts the WMA file however I'm not sure any checking other than extension is done. The file was uploaded however after leaving it for about 3 days, it still does not appear in the users contact card. The flag indicates it being set when we query the account but that's it. I feel more information about the file format should be included or possibly a check after uploading if the file format was accurate.

Secondly, there is no way to remove the audio file according to the documentation. There is a -RemoveSpokenName flag under Set-MailUser and Set-Mailbox however these apply to on-prem Exchange only. There is no way to remove the file on Exchange Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a057e0e5-e897-e015-11ed-22cdbb6f7c43
* Version Independent ID: ee3ec571-bf8c-7623-92a8-538851427d54
* Content: [Import-RecipientDataProperty (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/import-recipientdataproperty?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Import-RecipientDataProperty.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Import-RecipientDataProperty.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MarcLaf, I did some testing.

- There's more going on than just file extension checking. I renamed a .txt file to .wma, and the cmdlet didn't buy it; I got an "This isn't a valid WMA file" error.
- I'm going out on a limb and saying that PCM isn't supported; only WMA based on the error. FWIW, I got this same error in Exchange Server.
- To remove the spoken name, you should open a support case. Report back here if with any useful information.

**Comment by MarcLaf** [comment]
@chrisda Thanks for looking into this. Even if the WMA is accepted, there's no indication that it's going to work (as in my current tests). Is there any way to find out if this is indeed supported on EXO? I'm wondering now if it's how I exported the WMA. The page indicates version 9 voice and I think I may not have version 9 codec and finding it has been a bit tricky. Once I can track down the proper codec for exporting I will update this thread.

**Comment by chrisda** [comment]
@MarcLaf, don't hesitate to open the support case, which will get the question directly in front of people who need to provide answers. You're right in that it might not work (anymore?) in ExO. The fact that you can't remove values using Set-Mailbox etc. is ominous.

**Comment by MarcLaf** [comment]
@chrisda I think you may have hit on something with "might not work anymore". Apparently WMA 9 support was removed many years ago. According to Wikipedia "With the removal of Windows Media DRM in the Windows 10 Anniversary Update, Windows Media Encoder 9 is no longer compatible with the current version of Windows as of May 2017." So I'm wondering if this is just a deprecated feature and that's probably why there's very limited support for EXO (such as removing said files).

**Comment by yogkumgit** [comment]
@MarcLaf Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
