### ISSUE TITLE
New-QuarantinePolicy issue

### ISSUE THREAD

**Issue by JakubK64** [MicrosoftDocs/office-docs-powershell#8629]
Hello,

I've just try to create Quarantine Policy via PowerShell. Maybe I'm missing something, but -EndUserQuarantinePermissionsValue are not working correct from my perspetive.

In docs you said that required order looks like this:
PermissionToAllowSender
PermissionToBlockSender
PermissionToDelete
PermissionToDownload
PermissionToPreview
PermissionToRelease
PermissionToRequestRelease
PermissionToViewHeader

So if we want to create policy let's say for limited access permissions we should use 106 numbers, as example said:

"The values for the preset end-user permission groups are described in the following list:

No access: Binary = 0000000, so use the decimal value 0.
Limited access: Binary = 01101010, so use the decimal value 106.
Full access: Binary = 11101100, so use the decimal value 236."

I run the command as following:
`Set-QuarantinePolicy -Identity "ArticleQuarantinePolicy" -EndUserQuarantinePermissionsValue 106 -EsnEnabled $true`

And I get following results
```
AdminDisplayName                       : 
AdminNotificationFrequencyInDays       : 3
AdminNotificationLanguage              : Default
AdminNotificationsEnabled              : False
AdminQuarantinePermissionsList         : {}
CustomDisclaimer                       : 
EndUserQuarantinePermissions           : [PermissionToBlockSender: False
                                         PermissionToDelete: False
                                         PermissionToDownload: True
                                         PermissionToPreview: True
                                         PermissionToRelease: False
                                         PermissionToRequestRelease: True
                                         PermissionToViewHeader: False ]
```

As you can see **Block Sender** or **Delete** have value "False", **Download** has value "True", which is different than LimitedAccess Permisionss should be.

Same with other examples I tested. For exmaple let's say that I want to configure permissions like this:

PermissionToAllowSender - "0"
PermissionToBlockSender - "1"
PermissionToDelete - "1"
PermissionToDownload - "0"
PermissionToPreview - "0"
PermissionToRelease - "0"
PermissionToRequestRelease - "1"
PermissionToViewHeader - "1"

Binary number - 01100011, decimal number - 99. Let's see how it works:

`Set-QuarantinePolicy -Identity "ArticleQuarantinePolicy" -EndUserQuarantinePermissionsValue 99 -EsnEnabled $true
Get-QuarantinePolicy -Identity "ArticleQuarantinePolicy"`

```
AdminDisplayName                       : 
AdminNotificationFrequencyInDays       : 3
AdminNotificationLanguage              : Default
AdminNotificationsEnabled              : False
AdminQuarantinePermissionsList         : {}
CustomDisclaimer                       : 
EndUserQuarantinePermissions           : [PermissionToBlockSender: False
                                         PermissionToDelete: True
                                         PermissionToDownload: True
                                         PermissionToPreview: True
                                         PermissionToRelease: False
                                         PermissionToRequestRelease: False
                                         PermissionToViewHeader: False ]
```

As you can see there is completly different set of permissions.

**Comment by chrisda** [comment]
@JakubK64, I received information that the order of properties was wrong. The correct order (highest to lowest, which I find easier to deal with) is:

|Permission|Decimal value|Binary value|
|---|:---:|:---:|
|PermissionToViewHeader|128|10000000|
|PermissionToDownload|64|01000000|
|PermissionToAllowSender|32|00100000|
|PermissionToBlockSender|16|00010000|
|PermissionToRequestRelease|8|00001000|
|PermissionToRelease|4|00000100|
|PermissionToPreview|2|00000010|
|PermissionToDelete|1|00000001|

So, Limited access is 00011011 or 27 and Full access is 00010111 or 23.

So, your 99 example is really:

|Permission|Value|
|---|:---:|
|PermissionToViewHeader|0|
|PermissionToDownload|1|
|PermissionToAllowSender|1|
|PermissionToBlockSender|0|
|PermissionToRequestRelease|0|
|PermissionToRelease|0|
|PermissionToPreview|1|
|PermissionToDelete|1|

Which basically corresponds to the output you received, except it appears that the PermissionToAllowSender permission and value is not used, and we already knew that PermissionToViewHeader = 0 doesn't really do anything.

```powershell
PermissionToBlockSender: False
PermissionToDelete: True
PermissionToDownload: True
PermissionToPreview: True
PermissionToRelease: False
PermissionToRequestRelease: False
PermissionToViewHeader: False
```

I updated New-QurantinePolicy, Set-QuarantinePolicy, and [this topic](https://docs.microsoft.com/microsoft-365/security/office-365-security/quarantine-policies#use-the-enduserquarantinepermissionsvalue-parameter) accordingly.

Please close the issue if this is satisfactory.

**Comment by yogkumgit** [comment]
@JakubK64 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
