### ISSUE TITLE
Update Param Arg

### ISSUE THREAD

**Issue by Ryu-Syrius** [MicrosoftDocs/office-docs-powershell#8631]
Show Banner takes a boolean argument

https://docs.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps#syntax

[-ShowBanner <boolean>]

**Comment by chrisda** [comment]
@Ryu-Syrius, I disagree. I checked all the way back to v1.0.1 of the module, and ShowBanner has always been a switch parameter as described, which means:

- `-ShowBanner` or `ShowBanner:$true` do the same thing.
- Not using ShowBanner or `-ShowBanner:$false` *should* hide the banner, but the banner is shown by default, so not using ShowBanner actually shows the banner.

That's a bit weird, but the end result is:

- To show the banner, don't use ShowBanner at all, or use `-ShowBanner` or `-ShowBanner:$true`.
- To hide the banner, use `-ShowBanner:$false`.

OK?

**Comment by Ryu-Syrius** [comment]
Understood.  Thank you for the clarification.
