### ISSUE TITLE
Bad example causes an error

### ISSUE THREAD

**Issue by gregiare** [MicrosoftDocs/office-docs-powershell#8632]
The third example to silently disconnect causes the following error.

> The value Ignore is not supported for an ActionPreference variable. The provided value should be used
> only as a value for a preference parameter, and has been replaced by the default value. For more information, see the
> Help topic, "about_Preference_Variables."

See $Error after running the command. Is there a way to silently disconnect with out causing any output and without causing any errors?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3520ee8b-4c1b-5cf1-677e-9dcd14d88ea1
* Version Independent ID: 219014fd-5626-e1bf-aac4-b321bbdaa465
* Content: [Disconnect-ExchangeOnline (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/disconnect-exchangeonline?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Disconnect-ExchangeOnline.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gregiare, what version of the module and in what environment are you running? I just tried this in Windows PowerShell 5.1 running the module version 2.0.6-Preview3 and it worked fine.

But your question touches on something much older; I added that example based on Issue #7344. So, the command worked in v2.0.4, and the fix to make the output completely silent (no more "Disconnected Successfully!" text) was made to v2.0.5, which is the current version.

**Comment by yogkumgit** [comment]
@gregiare Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
