### ISSUE TITLE
It is unclear on the syntax required to use a Label as a predicate

### ISSUE THREAD

**Issue by mike-pshell** [MicrosoftDocs/office-docs-powershell#8640]
It is unclear on the syntax required to use a Label  as a predicate.
For the -ContentContainsSensitiveInformation option it provides:

Example for sensitivity label: labels = @(@{name ="Confidential"; type ="Sensitivity";})

I found that to use a label, requires it to be nested (in hash table in a hash table in a hash table).
This is the syntax that worked for me:
@(@{operator = "And"; groups = @(@{operator="Or";name="Default";labels=@(@{name="Confidential";type="Sensitivity"})})})

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98894097-1935-bd41-7857-5309d31817ee
* Version Independent ID: c8e1fd27-2bd4-ea13-5493-cf39450b715e
* Content: [New-DlpComplianceRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-dlpcompliancerule?view=exchange-ps#syntax)
* Content Source: [exchange/exchange-ps/exchange/New-DlpComplianceRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-DlpComplianceRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@mike-pshell, I updated the description as you stated.

Thanks for the feedback.

Closing
