### ISSUE TITLE
Description Missing for Parameter "DomainName"

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/office-docs-powershell#8642]
Hi,

the parameter DomainName does not have a description. Only the text {{ Fill DomainName Description }} is there. Could you update the correct description?

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb1bcd1-e164-db1e-e45a-dd0accd8afa6
* Version Independent ID: e08ff564-4170-905c-9e97-edf37e860b3f
* Content: [Set-AuthServer (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-authserver?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-AuthServer.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-AuthServer.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@myfope, see [Issue 7429](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for a greater explanation of why parameters with empty descriptions exist.

Are you using this parameter? Do you think you need to?

**Comment by myfope** [comment]
@chrisda Within the article the parameter will be used to configure HMA for OnPremises Exchange if we are on a system where HCW was run after September 2020 in this line:

`Set-AuthServer -Identity "EvoSTS - {GUID}" -DomainName "Tenant Domain" -IsDefaultAuthorizationEndpoint $true
Set-OrganizationConfig -OAuth2ClientProfileEnabled $true`

But I'm not sure what is with "Tenant Domain" meant?
The tenantname.onmicrosoft.com domain?
Our primary E-Mail Domain?

**Comment by chrisda** [comment]
@myfope, did you get that line of code from a Microsoft article? If so, where?

**Comment by myfope** [comment]
@chrisda I thought I had opened this issue related to this docs article where the command is listed: [https://docs.microsoft.com/en-us/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication?view=o365-worldwide#enable-hma](url)

It is listed within this section:

> If the EXCH version is Exchange 2016 (CU18 or higher) or Exchange 2019 (CU7 or higher) and hybrid was configured with HCW downloaded after September 2020, run the following command in the Exchange Management Shell, on-premises:

`Set-AuthServer -Identity "EvoSTS - {GUID}" -DomainName "Tenant Domain" -IsDefaultAuthorizationEndpoint $true
Set-OrganizationConfig -OAuth2ClientProfileEnabled $true`

**Comment by chrisda** [comment]
Well, they're certainly related. I'm asking for a definitive answer.

**Comment by chrisda** [comment]
@myfope, I'm told the DomainName value is "contoso.onmicrosoft.com".  I'm also told that updates to both topics are forthcoming (either directly or something that will be emailed to me that I'll need to incorporate).

**Comment by yogkumgit** [comment]
@myfope Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
