### ISSUE TITLE
Get-CsAutoAttendant, CsOnlineAudioFile filename is empty

### ISSUE THREAD

**Issue by darwincr** [MicrosoftDocs/office-docs-powershell#8649]
When I try to retrieve the CsOnlineAudioFile associated with an auto-attendant I am not able to, I can only get the ID of the CsOnlineAudioFile object but I cannot retrieve the filename with this information

This must be an issue with powershell as the filename is clearly visible from the Teams Admin Center
How can I retrieve the Filename for the CsOnlineAudioFile that is associated with an Auto-Attendant?

The same issue is not present on the CsCallQueue object, just with the CsAutoAttendant

Can you help?

AudioFileID is present:
($CsAutoAttendantList |Where {$_.Name -eq 'AA-TestRGS-0'}).DefaultCallFlow.Greetings.AudioFilePrompt.Id

AudioFileName is not present:
($CsAutoAttendantList |Where {$_.Name -eq 'AA-TestRGS-0'}).DefaultCallFlow.Greetings.AudioFilePrompt.FileName

AudioFileID is present:
($CsAutoAttendantList |Where {$_.Name -eq 'AA-TestRGS-0'}).DefaultCallFlow.Menu.Prompts.AudioFilePrompt.Id

AudioFileName is not present:
($CsAutoAttendantList |Where {$_.Name -eq 'AA-TestRGS-0'}).DefaultCallFlow.Menu.Prompts.AudioFilePrompt.FileName

AudioFileName is present:
($CsCallQueuesList |Where {$_.Name -eq 'CQ-Test'}).WelcomeMusicFileName

AudioFileName is present:
($CsCallQueuesList |Where {$_.Name -eq 'CQ-Test'}).MusicOnHoldFileName

**Comment by dariomws** [comment]
Hi @darwincr, thank you for your feedback.

Did you try with [Export-CsOnlineAudioFile](https://docs.microsoft.com/powershell/module/skype/export-csonlineaudiofile)?

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @darwincr Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
