### ISSUE TITLE
MailboxRegion parameter needs updateing

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/office-docs-powershell#8653]
Currently for the parameter -MailboxRegion the description states
'This parameter is reserved for internal Microsoft use.'

This should be updated to state
This parameter is used to set the geo-location of the group in a multi-geo environment'
See reference 
https://docs.microsoft.com/microsoft-365/enterprise/multi-geo-add-group-with-pdl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03921866-8345-7e01-e873-3ec191191fbf
* Version Independent ID: cb374ec2-99c3-7186-66ed-c037a678e946
* Content: [New-UnifiedGroup (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@nikki-c, I added a description for the MailboxRegion parameter in the New-UnifiedGroup and Set-UnifiedGroup topics.

Thanks for the feedback.

Closing
