### ISSUE TITLE
How to test this cmdlet (Get-CsUserCallingSettings)?

### ISSUE THREAD

**Issue by vincentkurmi** [MicrosoftDocs/office-docs-powershell#8656]
Hello, 

I tried to test this cmdlet. But I don't see how to do it. 
I have the latest release 3.0.0. and the cmdlet is not available. 

`PS C:\windows\system32> Get-InstalledModule`
`Version    Name                                Repository           Description `                                                                                                                                                        
`-------    ----                                ----------           -----------                                                                                                                  `                                 
`3.0.0      MicrosoftTeams                      PSGallery            Microsoft Teams cmdlets module for Windows PowerShell and PowerShell `

`PS C:\windows\system32> Get-CsUserCallingSettings -Identity bud.spencer@kurmihyb.onmicrosoft.com`
`Get-CsUserCallingSettings : The term 'Get-CsUserCallingSettings' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.`
`At line:1 char:1`
`+ Get-CsUserCallingSettings -Identity bud.spencer@kurmihyb.onmicrosoft. ...`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-CsUserCallingSettings:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

Some files are listed here:
[https://www.powershellgallery.com/packages/MicrosoftTeams/3.0.0](url)

- net472\bin\docs\Get-CsUserCallingSettings.md
- net472\exports\Get-CsUserCallingSettings.ps1
- netcoreapp3.1\bin\docs\Get-CsUserCallingSettings.md
- netcoreapp3.1\exports\Get-CsUserCallingSettings.ps1

So I tried to get the help 

`PS C:\windows\system32> Get-Help Get-CsUserCallingSettings`
`Get-Help : Get-Help could not find Get-CsUserCallingSettings in a help file in this session. To download updated help topics type: "Update-Help". To get help online, search for the help topic in the TechNet library at https:/go.microsoft.com/fwlink/?LinkID=107116.`
`At line:1 char:1`
`+ Get-Help Get-CsUserCallingSettings`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoundException
    + FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand`

I said OK, I will use the latest preview release. In this way, I uninstalled my module and tried to install the 2.6.2-preview. 
But here is the result: 

`PS C:\windows\system32> Install-Module -Name MicrosoftTeams -RequiredVersion 2.6.2-preview -AllowPrerelease`
`Install-Module : Cannot process argument transformation on parameter 'RequiredVersion'. Cannot convert value "2.6.2-preview" to type "System.Version". Error: "Input string was not in a correct format."`
`At line:1 char:54`
`+ ... ll-Module -Name MicrosoftTeams -RequiredVersion 2.6.2-preview -AllowP ...`
`+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Install-Module], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Install-Module`

Now I don't have any idea. Can you help me to try the documented cmdlet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df45e75e-7c61-00c6-2884-1eb13a6545d0
* Version Independent ID: 0f75412a-f70d-1ed0-0fca-d1448d75c186
* Content: [Get-CsUserCallingSettings (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-csusercallingsettings?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-CsUserCallingSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Get-CsUserCallingSettings.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@vincentkurmi Thanks for the feedback and reaching out!. 

The Get-CsUserCallingSettings cmdlet is not part of TPM 3.0.0, since the cmdlet is labelled as Preview and the 3.0.0 module is a GA module. 

So as you assumed, you'll have to continue using 2.6.2-preview for now. I tried installing 2.6.2-preview on my machine using the documented cmd (like what you tried) and it worked fine for me. I used PowerShell on Windows 11 (5.1.22000.282). Sorry, don't have an idea on what could be the reason it fails for you.

`
PS 02-12-2021 09:01:00 C:\> Install-Module -Name MicrosoftTeams -RequiredVersion 2.6.2-preview -AllowPrerelease
Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
PS 02-12-2021 09:05:28 C:\>
`

**Comment by vincentkurmi** [comment]
Thanks a lot for the feedback. I will try again on a different platform.

**Comment by vincentkurmi** [comment]
The answer was here: #29999

**Comment by JensTrier** [comment]
BTW updated Get cmdlet is in 3.0.1-preview module just released. There is also Set cmdlet now. Documentation is being published

**Comment by vincentkurmi** [comment]
Yes thank you, I just saw it as well. I am trying to install it. 
BTW I don't know how to be notified by a new release.
