### ISSUE TITLE
Get-TransportConfig

### ISSUE THREAD

**Issue by TCM69** [MicrosoftDocs/office-docs-powershell#8659]
I have EXO v2 installed, and get-command -module ExchangeOnlineManagement does not list Get-TransportConfig as an available command, however page say this applies to Exchange Online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 948eb635-e7ee-c29f-9da9-20d53f52aed9
* Version Independent ID: eac78e0a-a643-c324-f2e8-ea7eddf5a20b
* Content: [Get-TransportConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-transportconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-TransportConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-TransportConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@TCM69, first things first: few cmdlets are actually baked into the module, so you must [connect to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell) to see the vast majority of Exchange Online cmdlets.

if you're using the latest "regular" version of the module (v2.0.5), Set-TransportConfig should be available to you after you connect (tested and confirmed).

If you're using the very latest version (v2.0.6-Preview3), you only see all available cmdlets after you connect if you use the UseRPSSession switch in the Connect-ExchangeOnline command. If you don't use that switch, you'll see a truncated list of the most used cmdlets that have been optimized to use a REST API back-end (meaning, WinRM on your local PC doesn't require Basic authentication to be enabled).

I have pending updates related to all of this, so I'll push them live today.

**Comment by yogkumgit** [comment]
@TCM69 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by TCM69** [comment]
Thanks. I removed my preview module of ExchangeOnlineManagement and installed latest production build and now it works. Should have though of this before...
