### ISSUE TITLE
Get-CsEffectiveTenantDialPlan, Add Attribute handling

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/office-docs-powershell#8663]
**Received Message (No Attribute handling):**
`Get-CsEffectiveTenantDialPlan`

> Cannot display the prompt for "Identity" because type "Microsoft.Rtc.Management.AD.UserIdParameter" cannot be loaded.

**Expected Message:**
`Get-CsEffectiveTenantDialPlan`

> cmdlet Get-CsEffectiveTenantDialPlan command pipeline position 1
> Supply values for the following parameters:
> Identity: 

**Workaround**
`Get-CsEffectiveTenantDialPlan -Identity [Username]`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a0c2ac-fb7d-1e55-280b-3c67a826b573
* Version Independent ID: 6eb4cdbf-85bf-1153-add1-a746ef19c838
* Content: [Get-CsEffectiveTenantDialPlan (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-cseffectivetenantdialplan?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsEffectiveTenantDialPlan.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsEffectiveTenantDialPlan.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by dariomws** [comment]
Hey @weyCC81, same here:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/33589238/145781706-0ffe6393-f4ec-44c6-b7cd-7a9e7f9db2f9.png">

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @weyCC81 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
