### ISSUE TITLE
Expand description about Basic Auth. and Modern Auth.

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/office-docs-powershell#8664]
**Part 1** - Basic Auth Disabled on Tenant
> If basic authentication is not enabled, legacy *-Cs cmdlets will not function properly. 
> For Remote PowerShell, basic authentication is necessary.

What commands are not working if Basic Auth. is disabled?
I have tested 95% of all "Get-Cs*" with Teams Powershell (Version 3.0.0) without any error while Basic Auth. was disabled.

**Part 2** - App-Only Authentification
> -CertificateThumbprint (Removed from version 2.4.1-preview)
> This parameter has been removed from version 2.4.1-preview.

When will this be supported for our unattended Scripts as Basic Auth. will the deprecated soon?
(https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-june-2021-update/ba-p/2454827)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0dce05-8bfd-0bfa-3753-0eb193852703
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by vincentkurmi** [comment]
Hi @weyCC81, 

I am working on the same topic and as you can see, it doesn't work on y side. 

![image](https://user-images.githubusercontent.com/52075388/145187031-5fe8e57f-9921-4975-842d-0b6f641fb406.png)

Regards, 

Vincent

**Comment by vincentkurmi** [comment]
Just to be sure, you have two configurations, one for the service and one for the client. The basic authentication must be enabled for the client. 

![image](https://user-images.githubusercontent.com/52075388/145188151-529632b9-6d38-4d5d-aeaf-a6ec2ecff217.png)

**Comment by weyCC81** [comment]
Hi @vincentkurmi 

I am not able to reproduce this issue, but I did not change any settings on the client.
What I did is the following on my Demo-Tenant:
- Microsoft 365 > Settings > Services > Modern authentication > Disable everything expected of Modern Auth (first Entry)
- Azure AD > Conditional Access > User: Admin which I use in Script, Condition: Client App for Basic Auth, Action: Block

Verification on Demo-Tenant:
- Check Sign-In Log form Admin which I use in Script => I found just Modern Auth.

> I do not have any object in PSTN Gateway or Meeting Room but can run the command sucessfully

**Comment by vincentkurmi** [comment]
Ok, for me the warning below was only relative to Remote Powershell and WinRM. But you are right, I think this point needs to be clarify in the documentation. 

![image](https://user-images.githubusercontent.com/52075388/145365668-9fc5c86e-01f8-41da-9f0a-087295525d1d.png)

**Comment by dariomws** [comment]
Hi @weyCC81 and @vincentkurmi,

I understand that work is in progress to suppress the requirement for basic authentication on *-Cs cmdlets. Stay in touch here:
https://docs.microsoft.com/microsoftteams/teams-powershell-release-notes

**Comment by weyCC81** [comment]
Hi @dariomws 
In regards to **Part 2 - App-Only Authentification**

Will this be release soon?
or is it possible to use Connect-MgGraph with App-Only and aquire the AccessTokens this way?

**Comment by dariomws** [comment]
@weyCC81, I understand that the use of AccessTokens parameter is supported.

More information:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/8194

And the token refresh issue was fixed on 3.0.0:
https://docs.microsoft.com/microsoftteams/teams-powershell-release-notes

**Comment by weyCC81** [comment]
Hi @dariomws

Where can i find the official documentation of that with a certificate instead of a client secret, which i can send to the customer?

_Is there really no simple option to connect with a certificate as app-only like:
•	Connect-MgGraph is able to do it
•	Connect-ExchangeOnline is able to do it
•	Connect-AzureAD is able to do it_

**Comment by dariomws** [comment]
@weyCC81, authentication using a certificate was removed on version 2.4.1-preview. To connect from an unattended script you should use the -AccessTokens parameter instead.

**Comment by vincentkurmi** [comment]
As explained in this issue #8623, the -AccessTokens parameter still has some limitations. 
For me, at the date, the only serious way to be connected to Teams is to use the -Credential parameter.
I tried many times the AccessTokens without any success. 

The issue here, is the customers see the documentation and they require to us to use accesstoken, which seems to be not possible before march. 
Is it possible to add a note somewhere in the documentation to help us?

**Comment by dariomws** [comment]
I'll check if we can add a note here about the limitation for applications.

**Comment by weyCC81** [comment]
> @weyCC81, authentication using a certificate was removed on version 2.4.1-preview. To connect from an unattended script you should use the -AccessTokens parameter instead.

Why?, this makes not sense and Microsoft wants to deprecate basic auth. => looks not like they are ready...

**Comment by dariomws** [comment]
@weyCC81, AccessTokens don't use basic auth, it uses OAuth.

**Comment by vincentkurmi** [comment]
> I'll check if we can add a note here about the limitation for applications.

Hi @dariomws, did you get a confirmation for this note?

**Comment by dariomws** [comment]
@vincentkurmi, no yet, I'm working on it.

**Comment by mariussm** [comment]
Can someone please see if they can actually get AccessTokens way of connecting to work? I have tried both delegated flows (implicit flow for testing) and client credential grant without success.

```PowerShell
$tenantid = "95877aab-f66b-4cd0-98a0-1218634664fa"
$clientid = "f32d4a9a-a0c6-4cd7-a002-22d64a27d7a8"
$clientsecret = "rA47.....PB.pr9ke~hbF"
$username = "admin@abc.OnMicrosoft.com"
$password = "..."





#
# Implicit flow test
#

$url = "https://login.microsoftonline.com/$tenantid/oauth2/v2.0/authorize?client_id=$clientid&response_type=token&redirect_uri=http%3A%2F%2Flocalhost:8888&scope=https://graph.microsoft.com/.default&response_mode=fragment&state=12345&nonce=678910"
$url | set-clipboard 

# Paste the url you are redirected to here:
$url2 = "http://localhost:8888/#access_token=eyJ0eXAiOiJKV1Qm4VK_cvCBYk3vQ&token_type=Bearer&expires_in=4642&scope=profile+openid+email+https%3a%2f%2fgraph.microsoft.com%2fAppCatalog.ReadWrite.All+https%3a%2f%2fgraph.microsoft.com%2fGroup.ReadWrite.All+https%3a%2f%2fgraph.microsoft.com%2fUser.Read+https%3a%2f%2fgraph.microsoft.com%2fUser.Read.All+https%3a%2f%2fgraph.microsoft.com%2fUser.ReadWrite.All+https%3a%2f%2fgraph.microsoft.com%2f.default&state=12345&session_state=105dab9c-ec4d-4406-a652-70fe928c0eb1"
$graphtoken = (($url2 -split "\#")[1] -split "&" | where {$_ -like "access_token=*"}).replace("access_token=","")

$url = "https://login.microsoftonline.com/$tenantid/oauth2/v2.0/authorize?client_id=$clientid&response_type=token&redirect_uri=http%3A%2F%2Flocalhost:8888&scope=https://api.interfaces.records.teams.microsoft.com/.default&response_mode=fragment&state=12345&nonce=678910"
$url | set-clipboard 

# Paste the url you are redirected to here:
$url2 = "http://localhost:8888/#access_token=eyJ0eXAiOiJKV1QSycQhQplOA6-ztCkMACNt-7CAw&token_type=Bearer&expires_in=5327&scope=https%3a%2f%2fapi.interfaces.records.teams.microsoft.com%2fuser_impersonation+https%3a%2f%2fapi.interfaces.records.teams.microsoft.com%2f.default&state=12345&session_state=105dab9c-ec4d-4406-a652-70fe928c0eb1"
$teamstoken = (($url2 -split "\#")[1] -split "&" | where {$_ -like "access_token=*"}).replace("access_token=","")

Connect-MicrosoftTeams -AccessTokens @($graphtoken, $teamstoken)






#
# Client credential grant test
#

$url = "https://login.microsoftonline.com/$tenantid/oauth2/v2.0/token"
$body = "client_id=$clientid&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&client_secret=$clientsecret&grant_type=client_credentials"
$graphtoken = Invoke-RestMethod -Method Post -Uri $url -Body $body -ContentType "application/x-www-form-urlencoded"  | select -exp access_token

$url = "https://login.microsoftonline.com/$tenantid/oauth2/token"
$body = "client_id=$clientid&resource=48ac35b8-9aa8-4d74-927d-1f4a14a0b239&client_secret=$clientsecret&grant_type=client_credentials"
$teamstoken = Invoke-RestMethod -Method Post -Uri $url -Body $body -ContentType "application/x-www-form-urlencoded"  | select -exp access_token

# $graphtoken = #Get MSGraph Token for following for resource  "https://graph.microsoft.com" and scopes "AppCatalog.ReadWrite.All", "Group.ReadWrite.All", "User.Read.All";
# $teamstoken = #Get Teams resource token for resource id "48ac35b8-9aa8-4d74-927d-1f4a14a0b239" and scope "user_impersonation";

Connect-MicrosoftTeams -AccessTokens @($graphtoken, $teamstoken)
```

**Comment by mariussm** [comment]
Got it working with access token actually. Added PR: https://github.com/MicrosoftDocs/office-docs-powershell/pull/8788

**Comment by weyCC81** [comment]
Finally i get the answer form Microsoft (Developer Team), i think i am sharing this so not everybody has to open a Ticket and can find it in the documentation. It is far from what i wished and hopping for March 2022 with Certificate Authentication.

_(Solution is yet to test/verifiy)_

> **Solution:**
> o	Please refer to these solutions: https://skype.visualstudio.com/SBS/_wiki/wikis/IC3%20ConfigAPI%20Wiki/23643/Access-Tokens?anchor=token-generation-using-app-credentials
> o	However, it is not supported yet to sign in as a service principal (March 2022 is the expected time to be in GA)  and the other workarounds above provided are not yet fully supported. The only workaround that will work right now is in the possible workarounds section below -- but might not fullied the customer needs. Please notice that signing in as a service principle will be supported around March 2022. 
>
> **Possible workaround**
> **Requirements:**
> It is essential to update the PowerShell module to a version later than 2.3.2-preview.
> It is essential to have Microsoft graph permissions as follows:
> "AppCatalog.ReadWrite.All", "Group.ReadWrite.All", "User.Read.All"
>
> **Workaround:**
> It is first required to have User_Impersonation from the Skype and Teams Admin API:
> Afterwards, open PowerShell, and uninstall teams
> `Uninstall-Module -Name MicrosoftTeams`
> Close PowerShell
> Open Powershell as admin, and run
> `Install-Module -Name PowerShellGet -Repository PsGallery -Force`
> Close PowerShell
> `Install-Module -Name MicrosoftTeams -RequiredVersion 2.3.2-preview -AllowPrerelease`
> Then we modify the original script to the following:
> `$clientId = "< clientId >" `
> `$clientSecret = "redacted for my privacy here you put your client secretid" `
> `$tenantName = "< tenantName >" `
> `$resource = https://graph.microsoft.com/ `
> `$tokenBody = @{ `
> `   Grant_Type    = "client_credentials"` 
> `   Scope         = https://graph.microsoft.com/.default `
> `   Client_Id     = $clientId `
> `   Client_Secret = $clientSecret `
> `}  `
> `$graphTokenResponse = Invoke-RestMethod -Uri https://login.microsoftonline.com/$tenantName/oauth2/v2.0/token -Method POST -Body $tokenBody`
> `$resource = https://api.interfaces.records.teams.microsoft.com` 
> `$tokenBody = @{ `
> `   Grant_Type    = "client_credentials"`
> `   Scope         = "48ac35b8-9aa8-4d74-927d-1f4a14a0b239/.default"`
> `   Client_Id     = $clientId`
> `   Client_Secret = $clientSecret`
> `}  `
>
> `$TeamsTokenResponse = Invoke-RestMethod -Uri https://login.microsoftonline.com/$tenantName/oauth2/v2.0/token -Method POST -Body $tokenBody`
> `Connect-MicrosoftTeams -AccessTokens @($graphTokenResponse.access_token,$TeamsTokenResponse.access_token) -AccountId <Admin Account email>`
>
> In this way, you will connect to Powershell using the access token.
> Keep in mind the importance of the use of the module 2.3.2-preview as the accountid parameter is needed and is missing in other modules.
> **Also, Important note:**
>
> Cs powershell cmdlets will fail using accesstoken auth
> 
> You will hit a WinRM expected error using cs cmdlets
>

**Comment by Dan-Newton** [comment]
> Cs powershell cmdlets will fail using accesstoken auth

This is disappointing, I have a requirement for a cs cmdlet to run in an Azure Runbook and sounds like will still need to wait until March for GA but even then this seems slightly uncertain to work.

**Comment by mr-frostschutz** [comment]
> Got it working with access token actually. Added PR: #8788

Can you explain how you got this working? With version 3.0.0?

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
Hi everyone,

Could you please leave a comment here to summarize the limitations that you think the cmdlet has? I understand that -AccessTokens parameter is working. There is also a new example provided by the community in the article.

Thanks.

**Comment by lazedo** [comment]
@dariomws unattended doesn't work (access token with service account). tenant `A` creates application and publishes, tenant `B`  installs the application, `B` admin consents on permissions. tenant `A` cannot get authorized to work on tenant `B`

**Comment by CATgwalker** [comment]
> Hi everyone,
> 
> Could you please leave a comment here to summarize the limitations that you think the cmdlet has? I understand that -AccessTokens parameter is working. There is also a new example provided by the community in the article.
> 
> Thanks.

Hello, 

In short, the connection is a mess using certificate based authentication/service principal/application registration. The behavior of Connect-MicrosoftTeams using AccessTokens is not consistent with the certificate based authentication for Exchange & SharePoint Online modules for unattended access. Additionally, the VOIP cmdlets do not support application-only context of  certificate based authentication/service principal/application registration and only support delegated context for some cmdlets.

**Comment by Skatterbrainz** [comment]
I agree with CATgwalker's comment above. Consistency would be very helpful.

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
@lazedo @CATgwalker @Skatterbrainz, thank you for your feedback.

I'll try again to get more clarity about this feature as it was not included yet in 4.0 as far as I can see.

**Comment by weyCC81** [comment]
We have a Change Request with the Microsoft 365 Support which has been accepted, waiting for details...
We requested the following features:
- Ability to Disable Basic Auth. not just in the Tenant but also on the Client
- Ability to use Certificate as a new Authentication Method with Modern Auth.

**Comment by dariomws** [comment]
Hi everyone,

All of these features are under consideration and you should expect the product team to release them in the coming weeks. Sadly I cannot provide an ETA but some of them should arrive soon.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @weyCC81 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
