### ISSUE TITLE
SfBPowerShellSessionViaTeamsModule session availability is Busy

### ISSUE THREAD

**Issue by stephenwolf94** [MicrosoftDocs/office-docs-powershell#8669]
Hi everyone,

When using multithreading for Teams PowerShell sessions, there is an error saying that "The session SfBPowerShellSessionViaTeamsModule_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, api.interfaces.records.teams.microsoft.com is not available to run commands.  The session availability is Busy"
When trying the exact same commands using 2 PowerShell windows it's working perfectly.
Does anyone know how the Teams Powershell module is managing the sessions (where the context is stored and how to parallelize sessions)?
The same kind of issues seems to appear with AzureAD Powershell module.

Thanks!

Regards,

Stephen

**Comment by dariomws** [comment]
Hi @stephenwolf94, thank you for your feedback.

There is a limit of 3 concurrent sessions per credential in the different Microsoft 365 services for PowerShell, and I think 10 concurrent sessions per tenant.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @stephenwolf94 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
