### ISSUE TITLE
Get-CSOnlineUser Prompting for WinRM Basic Authentication

### ISSUE THREAD

**Issue by ardentgregadmin** [MicrosoftDocs/office-docs-powershell#8691]
After connecting to MicrosoftTeams using the MicrosoftTeams Module, Get-CSOnlineUser returns the following error.
```
Get-CsOnlineUser : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following
error message : The WinRM client cannot process the request. Basic authentication is currently disabled in the client
configuration. Change the client configuration and try the request again
```
When will this command work without the need of basic auth? The exchange online cmdlet now works without basic auth so I'm hoping this is on the roadmap for teams.

**Comment by vincentkurmi** [comment]
This issue #8664 is also on this topic.

**Comment by dariomws** [comment]
Hi @ardentgregadmin, thank you for your feedback.

This is on the roadmap, yes, but I cannot provide an ETA now. Please check the following website for any updates:
https://docs.microsoft.com/microsoftteams/teams-powershell-release-notes

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @ardentgregadmin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
