### ISSUE TITLE
New-CsTeamsEmergencyCallingPolicy references ECRP 

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#8696]
Can't raise a PR right now, but it looks as if this was posted from the ECRP and not updated (Example1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fe9f7ba-98ec-1f20-7154-de77e6a38543
* Version Independent ID: 81e7837c-3c13-b6f1-2e89-6bb9e822dde6
* Content: [New-CsTeamsEmergencyCallingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencycallingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @danny-levin
* Microsoft Alias: **dannyle**

**Comment by DEberhardt** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/pull/8706

**Comment by JensTrier** [comment]
Thanks, I'll create a PR to fix this

**Comment by JensTrier** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/pull/8722

**Comment by JensTrier** [comment]
Didn't realized your PR.

**Comment by DEberhardt** [comment]
no worries, closed mine as I've seen you have covered it already

**Comment by JensTrier** [comment]
my changes have been merged, feel free to close this issue
