### ISSUE TITLE
Some parameters are not described correctly

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/office-docs-powershell#8700]
Some parameters are not described correctly. Please update.

Example:
UserIsMemberOf
This parameter is reserved for internal Microsoft use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43667016-c662-727c-4566-9356330b0665
* Version Independent ID: decd796f-a731-2289-87d7-ee173788025c
* Content: [New-ClientAccessRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-clientaccessrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ClientAccessRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-ClientAccessRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Per offline email discussion, this appears to be about the age-old problem of "parameter is available, but shouldn't be or doesn't work", which a description of "reserved for internal Microsoft use" is supposed to placate.

Next step was to open a support case to see if the "reserved for internal Microsoft use" parameters can be removed if they aren't supposed to be available.

So, closing.
