### ISSUE TITLE
AllRequestInPolicy: $true of $false is default ?

### ISSUE THREAD

**Issue by sgrienen** [MicrosoftDocs/office-docs-powershell#8721]
Hi,

[...]
-AllRequestInPolicy

The AllRequestInPolicy parameter specifies whether to allow all users to submit in-policy requests to the resource mailbox. Valid values are:

**$true:** All users are allowed to submit in-policy requests to the resource mailbox. These requests require approval by a resource mailbox delegate if the AllBookInPolicy parameter is set to $false **(the default value is $true).**
**$false:** All users can't submit in-policy requests to the resource mailbox. **This is the default value.**

Which one is the right ? Thanks a lot !
Stéphane

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d95eb528-ab96-b415-981c-35d50c90dba0
* Version Independent ID: 0433f43b-538d-8000-a11d-69b4a5c97e0e
* Content: [Set-CalendarProcessing (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-calendarprocessing?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@sgrienen, I can see how that would be confusing. It should read (change in bold):

 > The AllRequestInPolicy parameter specifies whether to allow all users to submit in-policy requests to the resource mailbox. Valid values are:
>
> - $true: All users are allowed to submit in-policy requests to the resource mailbox. These requests require approval by a resource mailbox delegate if the AllBookInPolicy parameter is set to $false (the default value **of AllBookInPolicy** is $true).
> - $false: All users can't submit in-policy requests to the resource mailbox. This is the default value.

I updated the topic accordingly.

Thanks for the feedback.

Closing

**Comment by sgrienen** [comment]
Dear Chris,

Thanks for answering, but I'm still confused, why "This is the default
value" under $false ?

Cheers,
Stéphane



Le ven. 17 déc. 2021 à 02:40, Chris Davis ***@***.***> a
écrit :

**Comment by chrisda** [comment]
@sgrienen, the default value of the AllRequestInPolicy property from Get-CalendarProcessing on any/every mailbox is $false. 

I ran the following commands on an Exchange 2019 server and in an E5 tenant:

```powershell
$x = Get-Mailbox -ResultSize unlimited
$x | foreach {Get-CalendarProcessing -Identity $_.Identity | Format-Table Identity,AllRequestInPolicy}
```

The result for every mailbox was False: user mailboxes, room mailboxes, equipment mailboxes, etc..

**Comment by yogkumgit** [comment]
@sgrienen Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
