### ISSUE TITLE
improper table display in chromium browsers

### ISSUE THREAD

**Issue by exactmike** [MicrosoftDocs/office-docs-powershell#8727]
the table in this article does not display properly in chromium browsers.  The right hand columns are cut off in the display.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://docs.microsoft.com/en-us/powershell/exchange/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/filter-properties.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@exactmike, I don't think it displays "correctly" (rather, completely) in any browser: you need to use the left and right arrow keys to scroll the entire width of the table.

This is a longstanding issue. I've been told there isn't anything we can do about it.

**Comment by yogkumgit** [comment]
@exactmike Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
