### ISSUE TITLE
Domain information missing from output

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/office-docs-powershell#8733]
None of the examples listed in the document, nor anything else we've tried returns Domain information in the output. In addition, using -Domain All causes no data to be returned. So can you please clarify whether this is still an available data field, and update the examples accordingly?

Here's sample output:

PSComputerName     : outlook.office365.com
RunspaceId         : a35cca59-8bb2-400e-9db6-a0a0be01686f
PSShowComputerName : False
Organization       : michev.onmicrosoft.com
Date               : 19/12/2021 00:00:00
EventType          : Message passed
Direction          : Outbound
MessageCount       : 1
VerdictSource      : NotSpam
SummarizeBy        :
PivotBy            :
StartDate          : 01/01/0001 00:00:00
EndDate            : 01/01/0001 00:00:00
AggregateBy        :
Index              : 0

While we're on the subject, might also address the StartDate/EndDate values :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccd6fed8-6da5-310e-9773-fe2ad0b3146f
* Version Independent ID: 02171fa8-5e5c-0ce9-36d0-c057961ba86f
* Content: [Get-MailTrafficATPReport (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailtrafficatpreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailTrafficATPReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MailTrafficATPReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@michevnew, I don't know if this answers your questions, but I've made some updates to the topic based on testing:

- The following values are returned in the output:
  - Date
  - Event Type
  - Direction
  - Verdict Source
  - Message Count
- The Domain parameter doesn't appear to take the value 'All', but you can use Get-AcceptedDomain to see all accepted domain values, and you can enter multiple values separated by commas.
- StartDate and EndDate need to be used together, and you need to use UTC, either directly or via `(Get-Date "5/6/2021 9:30 AM").ToUniversalTime()`

**Comment by michevnew** [comment]
Thanks Chris, that would do.
