### ISSUE TITLE
Connect-MicrosoftTeams does not work on consecutive runs of Azure Powershell Function

### ISSUE THREAD

**Issue by m-doniec** [MicrosoftDocs/office-docs-powershell#8735]
Hello, I'm trying to connect to Teams from Azure Powershell Function.
Even though I do disconnect in a try{}finally{} block with Disconnect-MicrosoftTeams, I am not able to connect on the next run of the function.
I have already checked removing sessions/runspaces, but to no avail.
It works for the first run after deployment/functionapp restart.
The goal is to have the function triggered by a timer so it can run every night.

`$PWord = ConvertTo-SecureString -String $password -AsPlainText -Force`
`$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $user, $PWord`
`$teamsConnectRes = Connect-MicrosoftTeams -Credential $Credential  `

$teamsConnectRes is empty during second run and then I get an error while trying to get policies.

`$policies = Get-CsTeamsAppPermissionPolicy`

Error:
`2021-12-22T22:08:54.991 [Error] ERROR: Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : 粀栢Ǯ For more information, see the about_Remote_Troubleshooting Help topic.Exception             :Type             : System.Management.Automation.Remoting.PSRemotingTransportExceptionErrorCode        : -2144108173TransportMessage : The WinRM client cannot process the request because it received an HTML error packet. ErrorRecord      :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : 粀栢Ǯ For more information, see the about_Remote_Troubleshooting Help topic.HResult : -2146233087CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureExceptionTargetSite       :Name          : ThrowOnErrorsDeclaringType : Microsoft.Teams.ConfigApi.Cmdlets.PowershellUtilsMemberType    : MethodModule        : Microsoft.Teams.ConfigAPI.Cmdlets.private.dllStackTrace       :at Microsoft.Teams.ConfigApi.Cmdlets.PowershellUtils.ThrowOnErrors(PowerShell powershell)at Microsoft.Teams.ConfigApi.Cmdlets.PSCommands.Microsoft.Teams.ConfigApi.Cmdlets.IPSCommands.NewPSSession(String uri, PSCredential psCredential, String name, PSSessionOption sessionOption)at Microsoft.Teams.ConfigApi.Cmdlets.TrpsSessionBuilder.CreatePSSessionAndUpdateSessionStore(Uri configApiEndpoint, String configApiToken, Uri targetPsServerEndpoint, String adminsteredDomain, String microsoftTeamsModuleVersion, String configApiPowershellModuleVersion, PSSessionOption sessionOption)at Microsoft.Teams.ConfigApi.Cmdlets.TrpsSessionBuilder.Microsoft.Teams.ConfigApi.Cmdlets.ITrpsSessionBuilder.EstablishNewCsOnlineSessionAfterConnect(PSSessionOption sessionOption)at Microsoft.Teams.ConfigApi.Cmdlets.TrpsSessionPsCmds.GetSession()at Microsoft.Teams.ConfigApi.Cmdlets.TrpsPSCmdlet.CreateTrpsPipelineProcessor()at Microsoft.Teams.ConfigApi.Cmdlets.TrpsPSCmdlet.getProcessor(FlightingCommandInfo commandInfo, Boolean isFlighted, Boolean expectingPipelineInput)at Microsoft.Teams.ConfigApi.Cmdlets.TrpsPSCmdlet.ProcessRecord()at System.Management.Automation.CommandProcessor.ProcessRecord()Message          : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : 粀栢Ǯ For more information, see the about_Remote_Troubleshooting Help topic.Source           : Microsoft.Teams.ConfigAPI.Cmdlets.privateHResult          : -2146233087CategoryInfo          : ResourceUnavailable: (:) [Write-Error], PSRemotingTransportExceptionFullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,GetTeamsAppPermissionPolicyUsersUpnsInvocationInfo        :MyCommand        : GetTeamsAppPermissionPolicyUsersUpnsScriptLineNumber : 181OffsetInLine     : 32HistoryId        : 1ScriptName       : C:\home\site\wwwroot\TeamsPolicyFunction\run.ps1Line             : $userListFromTeamsPolicy = GetTeamsAppPermissionPolicyUsersUpns -teamsPolicyName $teamsPolicyNamePositionMessage  : At C:\home\site\wwwroot\TeamsPolicyFunction\run.ps1:181 char:32+ … amsPolicy = GetTeamsAppPermissionPolicyUsersUpns -teamsPolicyName $te …+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\TeamsPolicyFunctionPSCommandPath    : C:\home\site\wwwroot\TeamsPolicyFunction\run.ps1InvocationName   : GetTeamsAppPermissionPolicyUsersUpnsCommandOrigin    : InternalScriptStackTrace      : at Get-CsTeamsAppPermissionPolicy<Process>`

**Comment by dariomws** [comment]
Hi @m-doniec, here we are limited to documentation issues and improvements.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @m-doniec Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
