### ISSUE TITLE
Bug ? - Set-OutboundConnector

### ISSUE THREAD

**Issue by arbilus** [MicrosoftDocs/office-docs-powershell#8739]
Hello, 

I'm facing an issue with a send connector in Exchange Online and something strange is happening. 
Even if this send connector is used "From Office 365 to Exchange server Organization" for all recipient who is in the accepted domains configured in Exchange Online, all e-mails sent from Office 365 to Internet domains (like @gmail.com for exemple...) are using this send connector. Which should be not the case... 

After analysis in my opinion it seems that even if "-AllAcceptedDomains" is on "$true", "-RecipientDomains" is priorly used. Which could explain why even if in our send connector we specified "AllAcceptedDomains" on $true, and the parameter "-RecipientDomains" is on "*", this send connector is also used for "From Office 365 to Internet". Am I right or did I miss something ?  

The send connector is configured like that : 

> RunspaceId                    : xxxxxxxxxxxxxxxxxxxxxxx
Enabled                       : True
UseMXRecord                   : False
Comment                       : EOP vers le Relais SMTP (sans Transport Rules et pour tous les domaines acceptés)
                                IP : XX.XX.XX.XX
ConnectorType                 : OnPremises
ConnectorSource               : AdminUI
RecipientDomains              : {*}
SmartHosts                    : {XXXXXrelais-smtpXXXXX}
TlsDomain                     : 
TlsSettings                   : CertificateValidation
IsTransportRuleScoped         : False
RouteAllMessagesViaOnPremises : True
CloudServicesMailEnabled      : True
AllAcceptedDomains            : True
SenderRewritingEnabled        : False
TestMode                      : False
LinkForModifiedConnector      : 00000000-0000-0000-0000-000000000000
ValidationRecipients          : {XXXXX@XXXX.XX}
IsValidated                   : False
LastValidationTimestamp       : 19/10/2020 18:38:28
AdminDisplayName              : 
ExchangeVersion               : 0.1 (8.0.535.0)
Name                          : EOP outbound To Relais SMTP ‎‎‎(IP)‎‎‎
DistinguishedName             : CN=EOP outbound To Relais SMTP ‎‎‎(IP)‎‎‎,CN=Transport Settings,CN=Configuration,CN=XXXXXXXXX
Identity                      : EOP outbound To Relais SMTP ‎‎‎(IP)‎‎‎
ObjectCategory                : XXXXXXXXXXXXXXXXXXXXXXXExch-SMTP-Outbound-Connector
ObjectClass                   : {top, msExchSMTPOutboundConnector}
WhenChanged                   : 15/11/2020 16:29:06
WhenCreated                   : 12/10/2020 13:58:30
WhenChangedUTC                : 15/11/2020 15:29:06
WhenCreatedUTC                : 12/10/2020 11:58:30
ExchangeObjectId              : XXXXXXXXXXXXXXXXXXXXXXXXXX
OrganizationalUnitRoot        : XXXXXXXXXXXXXXXXXXXXXXXXXX
OrganizationId                : XXXXXXXXXXXXXXXXXXXXXXXXXX
Id                            : EOP outbound To Relais SMTP ‎‎‎(IP)‎‎‎
Guid                          : XXXXXXXXXXXXXXXXXXXXXXXXXX
OriginatingServer             : XXXXXXXXXXXXXXXXXXXXXXXXXX.PROD.OUTLOOK.COM
IsValid                       : True
ObjectState                   : Unchanged

**Comment by chrisda** [comment]
@arbilus, you should open a support case about this. If anything documentation related comes out of it, report back here.

**Comment by yogkumgit** [comment]
@arbilus Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
