### ISSUE TITLE
Setting LineURI with extension no longer work in version 3.0.1-preview

### ISSUE THREAD

**Issue by Veers01** [MicrosoftDocs/office-docs-powershell#8742]
When I try to set a new lineURI (or OnPremLineURI) for a user with a extension (ex: tel:+11234567890;ext=1234), I have the error: 

```PS C:\> set-csuser -identity xxxx@yy.com -EnterpriseVoiceEnabled $True -HostedVoicemail $True -LineURI "tel:+11234567890;ext=1234"
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsUserGenerated : 11234567890 is assigned to another user
Au caractère C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.0.1\net472\custom\PsExt\Set-CsUserModern.ps1:51 : 13
+             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsUserGene ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : ({ UserId = xxxx...onaryOfString }:<>f__AnonymousType80`2) [Set-CsUserGenerated_Set], Exception
    + FullyQualifiedErrorId : BadArgument,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsUserGenerated_Set```

It like the extension part is not use to check if another user have already this number. All my user have the same phone number and a different extension.

This function is working as intented in version 3.0.0

**Comment by JensTrier** [comment]
Thanks for reporting this! We'll investigate.

In the meantime feel free to try out the new cmdlet for setting phone numbers on users and resource accounts https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps

**Comment by JensTrier** [comment]
I'm told we have fixed this and it will be available with the next release.

**Comment by yogkumgit** [comment]
@Veers01 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
