### ISSUE TITLE
Domain attribute missing?

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#8743]
I'm running v3.0.0 of the MicrosoftTeams PowerShell module and PowerShell 5.1.  I noticed when I do a

Get-CsTenant | Get-Member, I no longer see the Domains attribute listed

Get-CsTenant | Get-Member

   TypeName: Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.Tenant

Name                             MemberType Definition
- -                              - - - - -  - - - - -
Equals                           Method     bool Equals(System.Object obj)
GetHashCode                      Method     int GetHashCode()
GetType                          Method     type GetType()
ToJson                           Method     Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonNode ToJson...
ToJsonString                     Method     string ToJsonString()
ToString                         Method     string ToString()
AssignedPlan                     Property   Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.IAssignedPlan[] Assig...
City                             Property   string City {get;set;}
CompanyPartnership               Property   Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ICompanyPartnership[]...
CompanyTags                      Property   string[] CompanyTags {get;set;}
Country                          Property   string Country {get;set;}
CountryAbbreviation              Property   string CountryAbbreviation {get;set;}
DirSyncEnabled                   Property   System.Nullable[bool] DirSyncEnabled {get;set;}
DisplayName                      Property   string DisplayName {get;set;}
PostalCode                       Property   string PostalCode {get;set;}
PreferredLanguage                Property   string PreferredLanguage {get;set;}
ProvisionedPlan                  Property   Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.IProvisionedPlan[] Pr...
ServiceInfo                      Property   string ServiceInfo {get;set;}
ServiceInstance                  Property   string ServiceInstance {get;set;}
SipDomain                        Property   string[] SipDomain {get;set;}
StateOrProvince                  Property   string StateOrProvince {get;set;}
Street                           Property   string Street {get;set;}
TeamsUpgradeEffectiveMode        Property   string TeamsUpgradeEffectiveMode {get;set;}
TeamsUpgradeNotificationsEnabled Property   System.Nullable[bool] TeamsUpgradeNotificationsEnabled {get;set;}
TeamsUpgradeOverridePolicy       Property   string TeamsUpgradeOverridePolicy {get;set;}
TeamsUpgradePolicyIsReadOnly     Property   string TeamsUpgradePolicyIsReadOnly {get;set;}
TenantId                         Property   string TenantId {get;set;}
VerifiedDomains                  Property   Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ITenantVerifiedSipDom...
WhenChanged                      Property   System.Nullable[datetime] WhenChanged {get;set;}
WhenCreated                      Property   System.Nullable[datetime] WhenCreated {get;set;}

A co-worker of me gets totally different results, using the same versions of PowerShell and MicrosoftTeams and we are both using the same basic authentication credentials to connect to MicrosoftTeams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b281face-3456-9f04-2a49-21e46f33272f
* Version Independent ID: e62b6323-aba4-5286-70f0-fcccd8cf23be
* Content: [Get-CsTenant (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-cstenant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTenant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by sarollins** [comment]
Since writing this, I have un-installed and re-installed version 3.0.0 of the PowerShell module, but still do not see Domains as a valid attribute.  And another co-worker of mine sees the same behavior on their computer, using my same credentials and also another user (same token credentials though)

**Comment by dariomws** [comment]
Hi @sarollins, thank you for your feedback.

I'm not sure if I understand this. I have run this command on a demo tenant and I can see SipDomain and VerifiedDomains. I do not have a Domains attribute.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
