### ISSUE TITLE
Unexpected number of results found for query 2

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#8744]
I'm running version 3.0.0 of the MicrosoftTeams PowerShell module.  In previous versions of the module, this used to work

Set-CsOnlineVoiceUser -Identity 'user@company.com' -TelephoneNumber '+16123999524' -LocationID 'C315C078-0C35-43C7-865B-757CE0C5C740'

When I do this in 3.0.0, I get the following error

Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsUserGenerated : Unexpected number of results found for query 2
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.0.0\net472\custom\Set-CsOnlineVoiceUserV2.ps1:26 char:13
+             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsUserGene ...
    + CategoryInfo          : InvalidOperation: ({ UserId = asmi...onaryOfString }:<>f__AnonymousType75`2) [Set-CsUser
   Generated_Set], Exception
    + FullyQualifiedErrorId : InternalServerError,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsUserGenerat
   ed_Set

We have clients who have been waiting for Modern Authentication support and now if we tell them that it is now supported via tokens, but they cannot update their voice users, they are no better off than before

BTW, I get this error if I use Basic Authentication or the new Token suport

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a67361-4862-a925-2515-fe2738c204d1
* Version Independent ID: fee47d08-63ff-edfe-e845-c8928f5d2acd
* Content: [Set-CsOnlineVoiceUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineVoiceUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineVoiceUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by dariomws** [comment]
Hi @sarollins, thank you for your feedback.

Here we are limited to documentation issues and improvements and I don't have an environment to test this command. I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
