### ISSUE TITLE
Get-DLPDetailReport EndDate parameter does not include results from that day

### ISSUE THREAD

**Issue by SimpleInfoSec** [MicrosoftDocs/office-docs-powershell#8752]
The StartDate and EndDate parameters behave differently with this cmdlet. The StartDate parameter includes all results **on or after** the specified date, however the EndDate parameter only includes results before that date, **not on it**. This leads to missing data in the specified range as data from the EndDate is excluded. 

Example: If the StartDate is 01/01/2022 (MM/DD/YYYY) and the EndDate is 01/03/2022, the results returned will be from January 1st - 2nd, and do not include results from January 3rd. If you change the EndDate to 01/04/2022, the results returned will be from January 1st - 3rd.

**Comment by SimpleInfoSec** [comment]
After reading through some other closed comments, it appears this is not the place to submit bugs, so I'm closing this and will open a support request.

**Comment by chrisda** [comment]
@SimpleInfoSec, could we be dealing with a UTC thinghere? Many of the date-related parameter descriptions in cloud-based cmdlets contain this information:

> To specify a date/time value for this parameter, use either of the following options:
>
> - Specify the date/time value in UTC: For example, "2021-05-06 14:30:00z".
> - Specify the date/time value as a formula that converts the date/time in your local time zone to UTC: For example, `(Get-Date "5/6/2021 9:30 AM").ToUniversalTime()`. For more information, see [Get-Date](https://docs.microsoft.com/powershell/module/Microsoft.PowerShell.Utility/Get-Date).

Does this affect the results?
