### ISSUE TITLE
Example contains a typo

### ISSUE THREAD

**Issue by cablechewer** [MicrosoftDocs/office-docs-powershell#8767]
The example currently shows:

```powershell
"Set-RetentionComplianceRule -Identity "Internal Company Rule" -RetentionDuration 180 RetentionDurationDisplayHint Days"
```

There should be a - placed before RetentionDurationDisplayHint just like there is on RetentionDuration.  Without it the command cannot be copied and pasted.

It should look like this to get the syntax right:

```powershell
"Set-RetentionComplianceRule -Identity "Internal Company Rule" -RetentionDuration 180 -RetentionDurationDisplayHint Days"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1940291b-6ed0-8a96-f4fc-2023ed745b92
* Version Independent ID: 8e867428-172f-309d-3bd2-491138e32341
* Content: [Set-RetentionComplianceRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-retentioncompliancerule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-RetentionComplianceRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-RetentionComplianceRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cablechewer, fixed. Interestingly enough, that same typo was also present in the example in Set-AppRetentionComplianceRule.

In the future, you too can fix things like this yourself; no need to open a GitHub issue first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md).

Thanks for the feedback.

Closing
