### ISSUE TITLE
ContentMatchQuery available properties

### ISSUE THREAD

**Issue by cablechewer** [MicrosoftDocs/office-docs-powershell#8768]
This article currently links to https://docs.microsoft.com/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference as part of the description for ContentMatchQuery.  I believe it should also link to https://docs.microsoft.com/microsoft-365/compliance/keyword-queries-and-search-conditions.
This second article is a more complete list of properties that can be queried, but I don't think it is an exhaustive list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1940291b-6ed0-8a96-f4fc-2023ed745b92
* Version Independent ID: 8e867428-172f-309d-3bd2-491138e32341
* Content: [Set-RetentionComplianceRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-retentioncompliancerule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-RetentionComplianceRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-RetentionComplianceRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cablechewer, the ContentMatchQuery parameter exists in 9 other cmdlets (including New-RetentionComplianceRule), and they all contain the same text and link:

> This parameter uses a text search string or a query that's formatted by using the Keyword Query Language (KQL). For more information about KQL, see [Keyword Query Language (KQL) syntax reference](https://docs.microsoft.com/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference).

That additional link you suggest appears to be tailored for eDiscovery. So are you saying the addition should go into New/Set-RetentionComplianceRule only?

These are the other affected cmdlets/topics:

- New-AppRetentionComplianceRule
- New-CaseHoldRule
- New-ComplianceSearch
- New-HoldComplianceRule
- Set-AppRetentionComplianceRule
- Set-CaseHoldRule
- Set-ComplianceSearch
- Set-HoldComplianceRule

**Comment by cablechewer** [comment]
I was suggesting it because it offers a much larger list of properties people can search.

I am beginning to wonder if there is any value to saying "for a larger, but still incomplete, list of properties you can search please see this eDiscovery article."

According to a couple of other articles you should be able to search anything eDiscovery can and all the Managed Properties in SPO/ODfB.


I need to sort out some stuff from the articles below that I discussed with my teammates:
[2:56 PM] Jon Bradley
that is from this article I believe Manage the search schema in SharePoint - SharePoint in Microsoft 365 | Microsoft Docs<https://docs.microsoft.com/en-us/sharepoint/manage-search-schema>
Manage the search schema in SharePoint - SharePoint in Microsoft 365
Learn about the search schema and how you can view, create, or change managed properties, and map crawled properties to managed properties to create a customized search experience.

[2:57 PM] Jon Bradley
Configure retention settings to automatically retain or delete content - Microsoft 365 Compliance | Microsoft Docs<https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-settings?view=o365-worldwide>
Configure retention settings to automatically retain or delete content - Microsoft 365 Compliance
Understand the settings you can configure in a retention policy or retention label policy to keep what you want and get rid of what you don't want.

[2:58 PM] Melanie Morales
i had a similar situation with my customer who was doing KQL queries for event based retention pg stated: "For SharePoint, crawled properties and custom properties aren't supported for these KQL queries and you must use only predefined managed properties for documents. However, you can use mappings at the tenant level with the predefined managed properties that are enabled as refiners by default (RefinableDate00-19, RefinableString00-99, RefinableInt00-49, RefinableDecimals00-09, and RefinableDouble00-09). For more information, see Overview of crawled and managed properties in SharePoint Server<https://docs.microsoft.com/en-us/SharePoint/technical-reference/crawled-and-managed-properties-overview>, and for instructions, see Create a new managed property<https://docs.microsoft.com/en-us/sharepoint/manage-search-schema#create-a-new-managed-property>."
like 2
Overview of crawled and managed properties in SharePoint Server - SharePoint Server
Learn about the default managed properties, their settings, and the default mapping between crawled and managed properties.


Thanks

Chris

**Comment by chrisda** [comment]
@cablechewer, OK. I added the link to the topic that you identified.

Thanks for the feedback.

Closing
