### ISSUE TITLE
Incomplete "set-label" documentation

### ISSUE THREAD

**Issue by IPFR33LY** [MicrosoftDocs/office-docs-powershell#8770]
Set-label does not properly specify what can be used within the "label action" key.

Unable to do multi line label markings for use inside documents footers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf754e37-7113-f7d1-ad1e-ef0c3eb5b5e7
* Version Independent ID: 1b20db7d-a508-8523-2309-a3d9f5d08dd7
* Content: [Set-Label (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Label.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Label.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@IPFR33LY, the current description of the LabelActions parameter in New/Set-Label is "reserved for internal Microsoft use".

Are you saying this is (now) incorrect? It must have been true at some point...

**Comment by IPFR33LY** [comment]
@chrisda 

My mistake. It's been a long day. I didn't even see that part. 🤣

I was messing with it all day. Thanks for pointing that out.

I should ask though. Is it possible to do multi-line markings with sensitivity labels? I noticed there's the ability to remove multi-line markings.

**Comment by chrisda** [comment]
@IPFR33LY, I don't know. You might check the regular label documentation at <https://docs.microsoft.com/microsoft-365/compliance/>; if you can do it in the UI, you can almost certainly do it in PowerShell. Another option would be to open a support case and ask.
