### ISSUE TITLE
WSMan Install on Mac/Linux

### ISSUE THREAD

**Issue by drewhjelm** [MicrosoftDocs/office-docs-powershell#8778]
Can you please make the WSMan section a bit more clear that it applies to both Linux and Mac? The instructions on this page kind of make it seem like with Mac you don't need to install WSMan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-and-maintain-the-exo-v2-module)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@drewhjelm, thanks for pointing this out. I thought I made updates for Mac soon after the updates for the Linux section.

From what I can tell, the only difference between the Linux and Mac instructions are Mac also requires the installation of OpenSSL (at least according to the [Installing PowerShell on macOS](https://docs.microsoft.com/powershell/scripting/install/installing-powershell-on-macos) article that we refer to).

Other than that, I just copied the instructions from the Linux section.

After the updates are visible, feel free to make any updates/corrections as you see fit. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md).

Thanks for the feedback.

Closing
