### ISSUE TITLE
Clarification on "... route all calls to ..."

### ISSUE THREAD

**Issue by pmehrwald** [MicrosoftDocs/office-docs-powershell#8791]
Hi,

in the article it says 
`This example creates a treatment that will route all calls to the number range +1 (555) 333-0000 to +1 (555) 333-9999 to the announcement service, where the audio file MainAnnouncement.wav will be played to the caller.`
as well as
`This example creates a treatment that will route all calls to the number +1 (555) 222-4444 to the user user@contoso.com.`

However, this is not fully correct, because only unassigned numbers are routed to the targets. The article and the function are named like that, but it's a little bit misleading when it says, that **all calls**  are routed there.

best regards,
Philipp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 658b2b6e-3511-9e38-6cdf-8bbbbc555b31
* Version Independent ID: 9834824a-3466-2c04-0a5c-bdc0472b2561
* Content: [New-CsTeamsUnassignedNumberTreatment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csteamsunassignednumbertreatment?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@pmehrwald  Thanks for the feedback! Great point and I agree. I'll change the text for the example to include that caveat and also call it out in the Notes section

**Comment by yogkumgit** [comment]
@pmehrwald Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
