### ISSUE TITLE
Clear Telephone number error

### ISSUE THREAD

**Issue by StoukSword** [MicrosoftDocs/office-docs-powershell#8792]
When I am using this command to clear the user's telephone number.

`Set-CsOnlineVoiceUser -Identity user@domain.com -TelephoneNumber $null`

I have an error this error

Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsUserGenerated : Value cannot be null.
Parameter name: Value cannot be null or empty.

**Comment by JensTrier** [comment]
Thanks for feedback! 

I don't know which version of Teams PS Module you are using, but I'm not able to repro the issue on the latest GA module 3.0.0. In that version Set-CsOnlineVoiceUser -Identity user@domain.com -TelephoneNumber $null works for me.

You could also try using the new Teams PS cmdlet [Remove-CsPhoneNumberAssignment](https://docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps) to remove the phone number.
