### ISSUE TITLE
Connect-IPPSSession as App Registration

### ISSUE THREAD

**Issue by pheeling** [MicrosoftDocs/office-docs-powershell#8798]
Hi,
Does Connect-IPPSSession Support App Only Authentication? We want to use SCC Powershell for creating labels within multiple tenants and not creating a user on each tenant for doing this.

Thanks for feedback.

Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 945ab2ea-22ae-814f-8898-fe84b7f29870
* Version Independent ID: 5383d152-988d-b1ee-4957-db5fb6213754
* Content: [Connect-IPPSSession (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-ippssession?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-IPPSSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Connect-IPPSSession.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@pheeling, it does not. I would suggest opening a support case and asking about it, which will get the issue in front of people who can make decisions.

**Comment by yogkumgit** [comment]
@pheeling Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mbratukha** [comment]
@pheeling we would appreciate any comment, if you were able to get any answer from Microsoft support, because we are considering similar approach to use app-only access to the SCC PowerShell to make some automations.

**Comment by pheeling** [comment]
@mbratukha unfortunately not. The support engineer stated to me it's by design but the request is still open. So my goal is either to get an understanding if there are cmdlet's which could be used with another connections option. Till now we still use username, password and exclude it from our CA policies.

**Comment by mbratukha** [comment]
@pheeling thank you for the quick response!

We have analyzed this situation a bit deeply and have figured out that the cmdlet `Connect-IPPSSession` is capable to kind of "re-use" an existing access token after sign-in via `Connect-AzAccount` (from  the `Az` PS-module) or `Connect-AzureAD` (from the `AzureAD` PS-module).
The trick is to provide the property `UserPrincipalName`. Here is an example that has worked for us:

``` powershell
Connect-AzureAD -TenantId {tenant-id} -AccountId {upn}

Connect-IPPSSession -UserPrincipalName {upn}
``` 

The cmdlet `Connect-AzureAD` is capable to be initialized via an access token by providing the property `AadAccessToken` or `MsAccessToken`.
We've tested it, but the cmdlet `Connect-IPPSSession` does not see an existing access token and prompts a user to provide the credentials.
Also, we have tried to use the properties `AccessToken`, `GraphAccessToken` and `MicrosoftGraphAccessToken` of the cmdlet `Connect-AzAccount` - it does not work too.

Our investigations show, that the cmdlet `Connect-IPPSSession` seems to rely on a data cached in a local browser after signing in. The execution of the command `Connect-AzureAD` or `Connect-AzAccount` with a valid access token does not keep anything in the local browser.

Does anybody know another approach to force the cmdlet `Connect-IPPSSession` to use an existing access token (with user context)?
Any working approach would make it possible to use a refresh token in the automation scenarios.

**Comment by yogkumgit** [comment]
@pheeling Thank you very much for the contribution and sharing this explanation. Here, we are limited to documentation fixes and improvements only. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mbratukha** [comment]
@pheeling, it's seems to be possible even via app-only context: https://github.com/MicrosoftDocs/office-docs-powershell/issues/6716#issuecomment-1045114219

@yogkumgit, would it be possible to extend the official documentation, that this approach is also mentioned there?

**Comment by chrisda** [comment]
Version 2.0.6-Preview5 of the EXO V2 Module is now available, so the various Credential parameters are now available on Connect-IPPSSession, so certibicate-based/app-oly authentication is now fully available in Security & Compliance Center PowerShell.

**Comment by pheeling** [comment]
> Version 2.0.6-Preview5 of the EXO V2 Module is now available, so the various Credential parameters are now available on Connect-IPPSSession, so certibicate-based/app-oly authentication is now fully available in Security & Compliance Center PowerShell.

thanks @chrisda amazing work
