### ISSUE TITLE
SFB but it is using Teams

### ISSUE THREAD

**Issue by MrVP** [MicrosoftDocs/office-docs-powershell#8799]
Some confusion on my part.  I see it uses the SFB module, but this is a Teams command.
Is there a date when this page was created/updated?

Thanks,
V

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b9d346-239b-d6e8-f2b9-56c8d3fba78f
* Version Independent ID: 6f6152d4-841e-9fcc-9ab8-d2aa74b6d5fe
* Content: [Get-CsTeamsCallingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csteamscallingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsTeamsCallingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTeamsCallingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by dariomws** [comment]
Hi @MrVP, thank you for your feedback.

You can see the latest updates on this article if you select Edit (top right of the screen) and then History.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @MrVP Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
