### ISSUE TITLE
Online only or no?

### ISSUE THREAD

**Issue by JasenHicks7** [MicrosoftDocs/office-docs-powershell#8805]
These lines seem to conflict with one another.

Applies to: Exchange Server 2013, Exchange Online
This cmdlet is available or functional only in the cloud-based service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f94b78-3cf4-2200-fae8-b85664ba01ce
* Version Independent ID: 0036d9e4-4a4d-8113-269f-801728138f5d
* Content: [Test-Message (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/test-message?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Test-Message.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Test-Message.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JasenHicks7, the "Applies to" value on the cmdlet or individual parameters is a mechanical, remorseless inventory of where the cmdlet/parameter is **available**, with no consideration whether it's supposed to be available there, or whether or not it actually works in that environment. That metadata is important for converting the markdown topics to MAML XML for code check-in and help at the command line (`Get-Help <cmdlet>`).

The text in the actual description attempts to clarify if there's an availability vs. functionality issue. The text:

> This cmdlet is available or functional only in the cloud-based service.

Attempts to describe that the cmdlet only works in Exchange Online, even though it's also available in Exchange 2013.

Does this make sense?

**Comment by JasenHicks7** [comment]
Thank you for the clarification, I had some customers asking directly about that, appreciate the fast feedback.
