### ISSUE TITLE
Set-CsUserCallingSettings UnansweredTargetType do nothing

### ISSUE THREAD

**Issue by zephyr2k7** [MicrosoftDocs/office-docs-powershell#8806]
The command Set-CsUserCallingSettings is not accepting "DoNothing" option as a UnansweredTargetType as is possible to set throught the Teams GUI, the error say:

Cannot validate argument on parameter 'UnansweredTargetType'. The argument "$False" does not belong to
 the set "SingleTarget,Voicemail,MyDelegates,Group" specified by the ValidateSet attribute. Supply an
 argument that is in the set and then try the command again.

would be possible to set the UnansweredDelay and the UnansweredTargetType to "Do nothing" ?

**Comment by yogkumgit** [comment]
@zephyr2k7 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
