### ISSUE TITLE
Set-MgUserPhotoContent vs set-userphoto

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/office-docs-powershell#8810]
Does this achieve the same result? Perhaps it should be mentioned in the article?

https://docs.microsoft.com/powershell/module/microsoft.graph.users/set-mguserphotocontent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197acba5-5e7c-4fbe-f7c2-3dd9984ba278
* Version Independent ID: 633fe153-b3ce-c1ec-1e61-2fe7a323d436
* Content: [Set-UserPhoto (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-userphoto?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UserPhoto.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-UserPhoto.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Kindly help us with your comment. Thanks

**Comment by chrisda** [comment]
No comment.

**Comment by chrisda** [comment]
@Mike-Crowley, I have no idea what the relationship is between the Exchange \*-UserPhoto and Microsoft Graph *-MGUserPhoto[Content] cmdlets are. Nevertheless, I added appropriate links to the Graph cmdlets in the Exchange cmdlet topics.

Thanks for the feedback.

Closing
