### ISSUE TITLE
How long between CNAME status checks?  Any way to invoke one manually?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#8814]
Just wondering....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f40df04f-087d-8a08-2074-cb259c564ad1
* Version Independent ID: 4d489f4e-54d5-c882-6cbd-497f80d2d92f
* Content: [Get-DkimSigningConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-dkimsigningconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-DkimSigningConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-DkimSigningConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeremyTBradshaw, unknown. You should open a support case and ask.

**Comment by JeremyTBradshaw** [comment]
Thanks.  Will close this now.
