### ISSUE TITLE
Get-MailDetailATPReport doesn't show all spam emails from external domain

### ISSUE THREAD

**Issue by balaji-blg** [MicrosoftDocs/office-docs-powershell#8818]
Is there any cmdlet to get all spam mails in a cmdlet ? We were using Get-MailDetailSpamReport but it is removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a47576-e439-efc4-6a22-c9c6a11edbe3
* Version Independent ID: bd26162f-3fde-657a-0eb1-c6b49fbdccc7
* Content: [Get-MailDetailATPReport (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-maildetailatpreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailDetailATPReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MailDetailATPReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@balaji-blg, I'm told the best way to proceed is for you to open a support case about this.

**Comment by yogkumgit** [comment]
@balaji-blg Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
