### ISSUE TITLE
Cmdlet to set basic call forwarding is not working

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/office-docs-powershell#8823]
Assuming a user is setup for voice and has the default setting to send all unanswered calls to voicemail with a delay of 20 seconds, the following cmdlet will not work.  

Set-CsUserCallingSettings -Identity dcaputo@enableuc.com -IsForwardingEnabled $True -ForwardingType immediate -ForwardingTargetType singletarget -ForwardingTarget "+14165551212"

It results in a failure because of the fact the user has unanswered calls going to voicemail.  If the user sets the unanswered calls to "Do Nothing" then the above cmdlet works.  

This cmdlet needs to be fixed so that it will work without having the user make a manual change.  

Dino

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31cb9cc1-fa53-871b-aead-ff43bf5eacee
* Version Independent ID: 5e56da56-6255-3751-d1ca-6dc49c2c1376
* Content: [Set-CsUserCallingSettings (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-CsUserCallingSettings.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@dinocaputo Thanks for the feedback! Please send me offline or post here, the state the user is in as expressed with get-csusercallingsetting prior to getting the error by issuing the cmd above and also please provide the full error.

**Comment by dinocaputo** [comment]
User Call Settings are configured as follows:
***@***.***

Goal - Admin wishes to set Call Forwarding for a user to an external phone number and runs the following PowerShell

***@***.***

Suspect its complaining about the fact that user has unanswered calls set to goto voicemail which is the case.  However, this failure defeats the entire point of this new cmdlet and what administrators want.
If I change my unanswered options to the "Do nothing" the above cmdlet works.  However this is not an acceptable workaround
***@***.***

Happy to validate further scenarios.  Let me know here or via email or on Teams.
Dino

**Comment by JensTrier** [comment]
I have chatted to @dinocaputo offline and have taken his feedback. You can close this item.

**Comment by yogkumgit** [comment]
@dinocaputo Hope the discussion was helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
