### ISSUE TITLE
Partner unable to connect to customer's tenant via Connect-IPPSSession -DelegatedOrganization @customerdomain.com

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/office-docs-powershell#8829]
Hello,
I'm trying to connect to the Compliance endpoint for one of my customers, however am unable to do so. Access to all other endpoints are working fine. Should partners be able to access customer's Compliance endpoint, and is there any documentation that I'm unable to find on this regard?
![image](https://user-images.githubusercontent.com/47151300/150101302-f744d218-1251-4ce0-8368-de790205be46.png)
Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 945ab2ea-22ae-814f-8898-fe84b7f29870
* Version Independent ID: 5383d152-988d-b1ee-4957-db5fb6213754
* Content: [Connect-IPPSSession (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/connect-ippssession?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Connect-IPPSSession.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Connect-IPPSSession.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@asdcristi, I don't think it works. The description of the DelegatedOrganization parameter says, "reserved for internal Microsoft use". For the definitive answer, you could open a support ticket and ask.

As a complete and utter shot in the dark, you could also try using the BypassMailboxAchoring switch in the command (by itself and together with DelegatedOrganization). But I don't expect it to work.

**Comment by yogkumgit** [comment]
@asdcristi Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
