### ISSUE TITLE
How to find the messagetraceid and then add this to the cmdlet

### ISSUE THREAD

**Issue by ruscoe888** [MicrosoftDocs/office-docs-powershell#8830]
This may be very simple, but i am unable to find the specific messagetraceid for a specific mail.
It would be helpful to add how to do this, either here or on get-messagetracedetail help page, or both pages?

Thanks
Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b37e5f4f-c0bc-8cce-3d0b-971bcc118726
* Version Independent ID: 50c55aeb-0311-ac5a-7468-b276835f6b67
* Content: [Get-MessageTrace (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-messagetrace?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MessageTrace.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MessageTrace.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ruscoe888, I did some testing. To find the MessageTraceId value, you'll need to first run Get-MessageTrace (or another cmdlet; see below) to get the value.

Frankly, MessageTraceId isn't very interesting in Get-MessageTrace; you can use other, much more friendly values to identify the message/entry.

Of course, we don't have that luxury in Get-MessageTraceDetail where MessageTraceId and RecipientAddress are required to identify the message trace entry.

I changed the description of the parameter in Get-MessageTraceDetail to say this:

> The MessageTraceId parameter filters the results by the message trace ID value of the message. This GUID value is generated for every message that's processed by the system (for example, c20e0f7a-f06b-41df-fe33-08d9da155ac1).
>
> The MessageTraceId value is also available in the output of the following cmdlets:
>
> - Get-MailDetailATPReport
> - Get-MailDetailDlpPolicyReport
> - Get-MailDetailEncryptionReport
> - Get-MailDetailTransportRuleReport
> - Get-MessageTrace

I did a similar update for Get-MessageTrace, but that last cmdlet mentioned is Get-MessageTraceDetail.

Does this make sense?

**Comment by yogkumgit** [comment]
@ruscoe888 Hope this comment is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
