### ISSUE TITLE
Cannot run Get-Whiteboard cmdlet with Global Reader role

### ISSUE THREAD

**Issue by alexiq** [MicrosoftDocs/office-docs-powershell#8836]
I see that running the Get-Whiteboard cmdlet requires Global Tenant Admin role.  This cmdlet is a "Get" verb and should be runnable buy a user with the Global Reader role.  Can this be fixed?

https://docs.microsoft.com/en-us/powershell/module/whiteboard/get-whiteboardowners?view=whiteboard-ps

**Comment by dariomws** [comment]
@alexiq - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Microsoft Whiteboard better. They keep a close tab on user feedback and it would be awesome if you could add your voice in the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/forum/e01e264c-1f1c-ec11-b6e7-0022481f8472#.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to making the docs better! Much appreciated!

**Comment by dariomws** [comment]
Some more information:
https://docs.microsoft.com/powershell/module/whiteboard/

**Comment by alexiq** [comment]
@dariomws, thank you for the recommendation.  I have submitted on the user feedback portal.  
https://feedbackportal.microsoft.com/feedback/idea/a044683a-b282-ec11-a81b-6045bd7bf64c
Take care.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @alexiq Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
