### ISSUE TITLE
Set-CsPhoneNumberAssignment page update

### ISSUE THREAD

**Issue by garinh77** [MicrosoftDocs/office-docs-powershell#8838]
At the beginning of the page the Syntax for the PS says:
Set-CsPhoneNumberAssignment
   -Identity <String>
   -**EnterpriseVoice** 

However, later in the document, the syntax for Enterprise Voice is  "-**EnterpriseVoiceEnabled**"

This page does not explain how to set -HostedVoiceMail which I assume will no longer be done through the Set-CSUser cmdlet

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-gb/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@garinh77 Thanks for the feedback! I have made the change and it will be updated when the PR is merged.

**Comment by JensTrier** [comment]
@garinh77 this has now been fixed. Please feel free to close this issue

**Comment by garinh77** [comment]
Thanks @JensTrier
