### ISSUE TITLE
Get-ComplianceSearch | Ft Items, Size - returning 0 

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/office-docs-powershell#8841]
When running `Get-ComplianceSearch | Ft Name, RunBy, Status, Items, Size, ContentMatchQuery` Items and Size are not returned, and they will be displayed as 0 for both columns, even though there is data in the full list results

```powershell
Name                      RunBy          Status      Items  Size    ContentMatchQuery
----                      -----          ------      -----  ----    -----------------                                                                    
teams chat                Admin          Completed     0      0     kind:im AND kind:microsoftteams(c:c)(date=2021-08-31..2021-11-01)                    
teams channel public      Admin          Completed     0      0     channel1Public
```
Can this be rectified or can we know why it's behaving like this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eec2d115-a551-f2b5-8c27-cf8d0e06cd93
* Version Independent ID: 5e9904c3-7043-eee9-9896-7b6cec4efae4
* Content: [Get-ComplianceSearch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-compliancesearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-ComplianceSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-ComplianceSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@asdcristi, that sounds like a bug. You should open a support case. Report back here with any findings.

**Comment by yogkumgit** [comment]
@asdcristi Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by luckman212** [comment]
@asdcristi Did you ever get resolution on this? I'm running into what appears to be the same issue- `Get-ComplianceSearch` cmdlet reporting `0` for `Items` yet in Purview on the web, clearly there are items found...

<img width="869" alt="image" src="https://user-images.githubusercontent.com/1992842/196297067-2520cf0f-7a00-4265-8403-803d48b8223a.png">

<img width="913" alt="image" src="https://user-images.githubusercontent.com/1992842/196297140-0186cc4d-5f5c-41a2-9117-fb552786946d.png">

**Comment by chrisda** [comment]
@luckman212, same advice: open a support ticket and report back here with any findings.

You should be using v3.0.0 of the Exchange Online PowerShell module now.

**Comment by asdcristi** [comment]
@luckman212 was able to get them to populate with the below, however don't remember exactly what was the solution:

$results = @()
$compl=Get-ComplianceCase
foreach ( $compliencecase in $compl )     {
    $compliancesearches=Get-ComplianceSearch -Case $($compliencecase.identity) -ResultSize unlimited
   
    foreach($compliancesearch in $compliancesearches){
    $result = Get-ComplianceSearch $($compliancesearch.name)
   
    $results+= $result
    }
    $results| Select-object name,casename,caseid,createdby,runby,createdtime,lastmodifiedtime,description,status,contentmatchquery,exchangelocation,publicfolderlocation,sharepointlocation,onedrivelocation,exchangelocationexclusion,PublicFolderLocationExclusion,sharepointlocationexclusion,onedrivelocationexclusion,successresults,searchstatistics,size,items,itclsems,unindexeditems,unindexedsize,errors | Out-GridView
    }

**Comment by luckman212** [comment]
Thanks @chrisda - Upgrading to EXO v3 module seems to have fixed the problem. What's the best place to watch for announcements like this? I missed this (apparently major) release completely.

**Comment by chrisda** [comment]
@luckman212, I was hoping there was a Message Center post about the new version of the module, but I didn't see one.

Periodically running the following command will show any updates to the module, and will allow you to see where you're at:

```powershell
Find-Module ExchangeOnlineManagement -AllVersions -AllowPreRelease
```
