### ISSUE TITLE
Issue with the text that explains the example

### ISSUE THREAD

**Issue by dbagleyusf** [MicrosoftDocs/office-docs-powershell#8843]
Either there is extraneous text following Example 1, or there was an additional example being described that does not exist.

> This example modifies the existing rule named Sales Team Disclaimer transport rule by adding the condition that the sender of the message is a member of the Sales Department group.

> This example sets the FromMemberOf parameter to a value of Sales-Group, which specifies that the rule is applied if the sender of the message is a member of the Sales-Group distribution group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f48ae8ec-b719-c4db-c259-02e4f9e779b5
* Version Independent ID: 96f609a7-578e-5568-adb3-61f483997870
* Content: [Set-TransportRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-transportrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-TransportRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-TransportRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Yeah, that second statement appears to be left over after some updates, so I removed it. The first statement matches the code example.

Thanks for the feedback.

Closing
