### ISSUE TITLE
"CsPhoneNumberAssignment" still in public preview?

### ISSUE THREAD

**Issue by vincentkurmi** [MicrosoftDocs/office-docs-powershell#8848]
Hi, 

Is it still in public preview or can we use it in production?
Same question for the cmdlet: "Remove-CsPhoneNumberAssignment"

![image](https://user-images.githubusercontent.com/52075388/150832717-89069845-37a0-4540-9943-19b0077d28e3.png)

Thanks in advance. 

Regards, 

Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@vincentkurmi Yes, feel free to use both Set and Get in production and report any issues you find. The cmdlets is in the GA module, but we keep the preview note on the PS cmdlet doc pages for now.
