### ISSUE TITLE
No way to set a $NULL phonenumber for Direct Routing Users

### ISSUE THREAD

**Issue by dinocaputo** [MicrosoftDocs/office-docs-powershell#8852]
SO with this new cmdlet it seems not possible to have a user enabled for EnterpriseVoice with no assigned PhoneNumber.  This is a common scenario for Direct Routing customers where they want users to be able to make outbound calls but not have a DID.  This is also a common scenarios supporting Call Queues where users need to be EnterpriseVoiceEnabled to be an agent but don't need to have a DID.  

I hope this scenario was considered and there is a workaround available or is being addressed shortly.  Happy to provide more feedback if required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@dinocaputo Thanks for the feedback! I think I can repro the issue, but I'll reach out to you offline to confirm. Please feel free to close this issue

**Comment by dinocaputo** [comment]
Worked with Jens and found the issue.  Docs will be updated to avoid confusion for this scenario.  For users that are already EV enabled, you will have to run Remove-CsPhoneNumberAssignment first and the run Set-CsPhoneNumberAssignment -Identity user@domain.com -EnterpriseVoiceEnabled $True
