### ISSUE TITLE
There is no way to get unlimited results from Get-CalendarDiagnosticObjects

### ISSUE THREAD

**Issue by Ramadel** [MicrosoftDocs/office-docs-powershell#8860]
I can only ever get 1000. This sort of makes this command worthless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3e0524b-e92d-eefb-5416-557620edfb39
* Version Independent ID: 7afae510-9006-4667-5756-92714f0b08f0
* Content: [Get-CalendarDiagnosticObjects (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-calendardiagnosticobjects?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-CalendarDiagnosticObjects.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-CalendarDiagnosticObjects.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Ramadel, the ResultSize parameter description states the 1000 result limit, so there's not much to do from a documentation perspective.

Your best way forward is to open a support case.

**Comment by Ramadel** [comment]
OK. That's pretty frustrating that they don't tell anyone how to increase the hard 1000 limit. They don't even say, "No, you can't."

**Comment by yogkumgit** [comment]
@Ramadel Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
