### ISSUE TITLE
Specifying "-ItemClass "IPM.Appointment"" still produces results that do not match IPM.Appointment

### ISSUE THREAD

**Issue by Ramadel** [MicrosoftDocs/office-docs-powershell#8861]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3e0524b-e92d-eefb-5416-557620edfb39
* Version Independent ID: 7afae510-9006-4667-5756-92714f0b08f0
* Content: [Get-CalendarDiagnosticObjects (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-calendardiagnosticobjects?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-CalendarDiagnosticObjects.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-CalendarDiagnosticObjects.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by Ramadel** [comment]
This is in regards to trying to get a list of recurring meetings for different users. Since there's no way to actually do that directly, I have to use this module. But if I have no way to cut down on results over 1000 (which are most users), then I can't do this at all.

**Comment by chrisda** [comment]
@Ramadel, your best way forward is to open a support case about this. It sounds like a bug.

**Comment by Ramadel** [comment]
Already did, and showed them this page.
