### ISSUE TITLE
Incorrect parameter naming

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/office-docs-powershell#8862]
On the parameter details below, two appears that don't seem to exist:
- OutboundPSTNNumberTranslationRulesList
- OutboundTeamsNumberTranslationRulesList

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a99ede2-bbc2-c56d-6fb0-33db74417f54
* Version Independent ID: cf4bfc0e-fd8d-d5ca-5432-798af72a8885
* Content: [Set-CsOnlinePSTNGateway (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinepstngateway?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by JensTrier** [comment]
@TheITguy666 Thanks for the feedback! See it, will get it fixed.

**Comment by JensTrier** [comment]
The fix is in this PR #8869 made by Filipp

Feel free to close this issue

**Comment by yogkumgit** [comment]
@TheITguy666 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
