### ISSUE TITLE
Set-CsPhoneNumberAssignment doesn't process number with extension correctly

### ISSUE THREAD

**Issue by PieFie** [MicrosoftDocs/office-docs-powershell#8868]
Set-CsPhoneNumberAssignment -Identity <upn> -PhoneNumber '<number>;ext=<extension>' -PhoneNumberType DirectRouting where PhoneNumber is in the E.164 form ex +3221231212;ext=1234 yield an error:
- Update failed for user '<removed id>'. Please try again

When remove te "+" (plus-sign) (ex. 3221231212;ext=1234) the command succeed, but generate a wrong LineURI:
- tel:3221231212;ext=1234
- Shown in Teams Admin as '+tel:3221231212;ext=1234'

Expected LineURI, based on working accounts:
- tel:+3221231212;ext=1234
- Shown in Teams Admin as '+32 2 123 12 12 ext. 1234'

PS: Examples based on a Belgian phonenumbers (numbers are fictive)

**Comment by JensTrier** [comment]
@PieFie Thanks for the feedback!

I tried using your sample phone number and it works for me using this cmdlet "Set-CsPhoneNumberAssignment -Identity user@contoso.dk -PhoneNumber "+3221231212;ext=1234" -PhoneNumberType DirectRouting

Please send me offline the actual PS cmdlet you use and the error result you see and we'll investigate.

**Comment by PieFie** [comment]
@JensTrier Thanks to have a look.
How can I offline contact you?

Anyhow: I use the same command as you do, but with the UPN/Email and Phonenumber for the users (I have more accounts with the same issue).

The only return I get is (ObjectID  is of the user I try to set his number):

Code       Message
----       -------
BadRequest Update failed for user 'Removed ObjectID'. Please try again

**Comment by JensTrier** [comment]
@PieFie please send to  jens.trier AT microsoft.com

**Comment by JensTrier** [comment]
Working with @PieFie offline on this. This issue can be closed

**Comment by PieFie** [comment]
Close Issue as handeling this offline

**Comment by emiliaus68** [comment]
@PieFie can you please share the solution of this problem ? I'm having exactly the same issue... Thx

**Comment by JensTrier** [comment]
@emiliaus68 we are still investigating the root cause. Please send me your details offline to the e-mail address above and I can confirm whether you're hitting same issue.
