### ISSUE TITLE
Missing text under -CompletePublicFolderMigrationWithDataLoss

### ISSUE THREAD

**Issue by Corina-github** [MicrosoftDocs/office-docs-powershell#8870]
Hi, 

At the moment, the KB is showing this info : 
-CompletePublicFolderMigrationWithDataLoss
This parameter is available only in the cloud-based service.

{{ Fill CompletePublicFolderMigrationWithDataLoss Description }}

We were interested in using that option with a customer and would appreciate it if the KB could be updated to also include that description. It looks like there was a plan to include it, but didn't get updated just yet so it's only showing the placeholder instead.  

Thank you!
Corina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7f086ba-ff28-8c6b-4b2f-f19f70511c4b
* Version Independent ID: 28d4c38d-86e7-89bb-5c0f-c54d4e7fd721
* Content: [Complete-MigrationBatch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/complete-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Complete-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Complete-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Corina-github, parameter descriptions in the state are a known issue. See comments [in this similar issue](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for a detailed explanation.

I would suggest opening a support case and asking if/how that parameter works. If it's functional and meant to be available, report back here and I'll create a real description. If it's not supposed to be available and/or doesn't work (yet?), I can add "reserved for internal Microsoft use" as the description.

**Comment by Corina-github** [comment]
Hi Chris,

I'm with the CSS internal team, so I'll check with the PF SPM and get back
to you with the feedback. Wasn't aware there's a known issue with the
parameter descriptions in general and thought it was a mishap on this KB,
so thought to give a heads up.
Thanks for the prompt reply!
Corina

**Comment by Batre-MSFT** [comment]
@chrisda Please change add "reserved for internal Microsoft use" as the description. Thank you :-)

**Comment by chrisda** [comment]
Done. #8877.

Thanks for the feedback.

Closing
