### ISSUE TITLE
Information Missing

### ISSUE THREAD

**Issue by arnauvc** [MicrosoftDocs/office-docs-powershell#8871]
Good morning,

Parameters -IncludeDetails and IncludeElements have not description nor examples on how to use it. 

Could you please provide some?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439c6b6a-4a1b-3cc9-2f65-b39a6dc40717
* Version Independent ID: 737ff20a-02e8-7807-fef8-1c2dc98d79a7
* Content: [Get-DlpSensitiveInformationType (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-dlpsensitiveinformationtype?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-DlpSensitiveInformationType.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-DlpSensitiveInformationType.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@arnauvc, parameter descriptions in the state are a known issue. See comments [in this similar issue](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for a detailed explanation.

Availability vs. functionality of a parameter are two different things. The parameters are definitely available, but are they supposed to be? Do they work? Are you trying to use the parameters, or are you just pointing out that the descriptions are empty?

If you're trying to use the parameters, I would suggest opening a support case and asking if/how they work. If they're functional and meant to be available, report back here and I'll create real descriptions. If they're not supposed to be available and/or do work (yet?), I can add "reserved for internal Microsoft use" as the descriptions.

**Comment by arnauvc** [comment]
Hi @chrisda , I get your point but I must admit amb personally a bit disappointed. My clients pay to use Microsofts products and I/they would expect it to be well documented.

It seems kinda odd to me that I'm the one responsabile for opening a support case to know how it works...

Anyway, thank you for you response and I'll get back here if I get a usefull response from the support team
