### ISSUE TITLE
MailboxMovePublishedScopes missing description

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/office-docs-powershell#8873]
A critical paremeter used with tenant to tenant mailbox migration and the description is missing.
Please know that Microsoft documents and articles reference this.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61bdc5c8-91af-66ca-cc94-3127fea1b8c3
* Version Independent ID: 29ec4bea-aa01-8f74-f820-adb77c57aa4f
* Content: [New-OrganizationRelationship (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-organizationrelationship?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-OrganizationRelationship.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-OrganizationRelationship.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Karr, which parameter are you talking about?

**Comment by chrisda** [comment]
@Karr, OK I added descriptions for the MailboxMovePublishedScopes, MailboxMoveCapability, and OAuthApplicationID parameters per the information in [this topic](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration).

Thanks for the feedback.

Closing
