### ISSUE TITLE
Trying to replace Set-CsUser but getting error using Set-CsPhoneNumberAssignment

### ISSUE THREAD

**Issue by bendingunit** [MicrosoftDocs/office-docs-powershell#8875]
Hi,
I'm getting this error trying to assign a number that was previously set up at NFON:

`Set-CsPhoneNumberAssignment -Identity test.user@xxxxxxx.xxx -PhoneNumber +4930xxxxxxxxxxx -PhoneNumberType DirectRouting
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNumberAssignment : The server responded with a Request Error, Status: NotFound
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.1.0\net472\custom\PsExt\Set-CsPhoneNumberAssignment.ps1:41 char:9
         Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNumberA ...
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: ({ Identity = te...iceEnabled =  }:<>f__AnonymousType82`5) [Set-CsPhoneNumberAssignment_Set], UndeclaredResponseException
     FullyQualifiedErrorId : NotFound,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsPhoneNumberAssignment_Set

---`

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@bendingunit 

thanks for the feedback! Is that test.user a newly licensed user or a user that has been licensed for long time? You can see that kind of error, if the user has not been fully provisioned in our back-end systems. Waiting some time will allow you to assign the number.

**Comment by bendingunit** [comment]
The user is already active and licensed since several months.

**Comment by JensTrier** [comment]
To investigate this further I need information about the user, i.e. SIPaddress or UPN. If you are interested in this, please send it to me offline at jens.trier AT microsoft.com

**Comment by bendingunit** [comment]
sorry for wasting your precious time!  i found a typo as the underlying cause ;D

**Comment by JensTrier** [comment]
No worries @bendingunit!! Rather too much feedback than too little, so keep it coming.
