### ISSUE TITLE
Section regarding 'Changes in "-Filter" parameter' spectacularly unclear

### ISSUE THREAD

**Issue by et01267** [MicrosoftDocs/office-docs-powershell#8881]
The section headed by 'Changes in "-Filter" parameter' seems to contain bogus / wrong information.

For example, the comparison operator shown is 'eq' when the actual syntax is '-eq', and the whole expression should be in curly braces.

Also, there is this nonsense:  

> AssignedPlans eq 'MCO' - for contains checks.

I don't think you can use 'eq' (or '-eq') to do a contains check.   You would need to use a different operator.   Note that I am entering a separate bug report about the -Filter info which claims that that you can use any Where-Object syntax; but this is wrong.   Therefore, if you change this section to use some other operator for the comparison/test, please make sure that it is actually a valid operator to use in the -Filter context.

Please have someone who actually knows how PowerShell (and this command) actually works review (and verify via actual testing) all your examples.

The only thing worse than no documentation is wrong documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by dariomws** [comment]
Hi @et01267, thank you for your feedback.

@isrumnon, could you kindly help here? Thanks!

**Comment by isrumnon** [comment]
@et01267 @dariomws  Thanks for the feedback. We are working on the documentation changes for the same

**Comment by yogkumgit** [comment]
@isrumnon Kindly update and help us in closing this issue. Thanks

**Comment by isrumnon** [comment]
We've made documentation changes for more clarity, hope that helps. Do let us know if something is still unclear.
