### ISSUE TITLE
-Filter documentation incorrectly claims it works the same as Where-Object

### ISSUE THREAD

**Issue by et01267** [MicrosoftDocs/office-docs-powershell#8882]
The -Filter section claims:

> The Filter parameter uses the same filtering syntax that is used by the Where-Object cmdlet

This is incorrect.  In my testing, I have found that '-match' does not work and gives this error:
```
  26 |  Get-CsOnlineUser -Filter {(Enabled -eq $True) -and ((HostingProvider  .
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Query not supported for
     | operator: "-match" query: "(Enabled -eq $True) -and ((HostingProvider -eq "SRV:") -or
     | (InterpretedUserType -match 'error|needs|disabled|misconfigured')) " position: "81""
```
Please document which operators are actually supported in the '-Filter' - **Or perhaps this is a bug in the module?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by dariomws** [comment]
Hi @et01267, thank you for your feedback.

@isrumnon, could we provide more information? Thanks!

**Comment by isrumnon** [comment]
Hi @eloka080677 @dariomws , this is a bug in our system and we are targeting to support the old format soon. We are targeting end of March to reintroduce the old formats. We temporarily support only OPATH syntax (examples below) or we can deflight your tenant from our recent changes if that helps. Do let us know if you want to go with the second option. Thanks

examples of new syntax:

"-eq" now replaced with "eq", 
"-ne" replaced with "ne"
"-and" replaced with "and"
"-or" replaced with "or"
"-lt" replaced with "lt"
"-gt" replaced with "gt"

**Comment by et01267** [comment]
Hmm - I'm not sure which is worse:  
- Introducing a breaking change to the code that should have been obvious to any QA (which you evidently didn't do)
- Not advertising the fact that you deployed this breaking change
- Not documenting the new behavior (even if it is broken) by indicating that this is a change to a different syntax
- Not fixing it IMMEDIATELY when you realized it was broken in production.  End of March?  Give me a break!

I vote for the last one.   Are there any adults around?

Fortunately, I'm just issuing ad hoc commands, but I'm sure there are people with production software that depend on the syntax that was so capriciously broken.

**Comment by isrumnon** [comment]
@et01267 apologies for the inconvenience. We just very recently discovered this change in our system which was unintended and were trying to figure out a plan to mitigate this issue. For now we can rollback the change for affected tenants and have started to do the same. Can you please share your tenant ID so we can make sure your tenant has been included in our rollback list? Thanks!

**Comment by yogkumgit** [comment]
@isrumnon

**Comment by isrumnon** [comment]
@et01267 we have rolled out the change and most of the tenants should be able to use the old syntax format barring a few tenants that have already switched to the newer format

To your primary question on the "-match" operator - This is not supported insider the "-Filter" parameter. We will update the Get-CsOnlineUser documentation stating the same

**Comment by yogkumgit** [comment]
@et01267 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
