### ISSUE TITLE
-HostedVoiceMail

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/office-docs-powershell#8883]
Hi, Any reason the parameter -HostedVoiceMail has not been included? Will we still have to use Set-CsUser for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by SvenBell** [comment]
Would also be nice if -HostedVoiceMail was automatically set to enable by default with a user is assign a Phone System license like this happens when you assign a Calling plan. Why would you assign this license on not want it enabled?

**Comment by SvenBell** [comment]
Answering my own question via Set-CsUser Doco Ref.  https://docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps 

> -HostedVoiceMail

> When set to True, enables a user's voice mail calls to be routed to a hosted version of Microsoft Exchange Server. In addition, setting this option to True enables Skype for Business users to directly place a call to another user's voice mail.
> 
> **Note: Using this parameter will be deprecated for Teams users and it is not required anymore to set it for Microsoft Teams users.**

**Comment by JensTrier** [comment]
@SvenBell Thanks for the feedback! Yes, Cloud Voicemail is automatically provisioned. I'll update the documentation to make that clear.

**Comment by JohnGGeo** [comment]
Along the same lines is enterprisevoiceenabled also set to true? As I guess if you set a number wouldn't you also want that set to true by default, the docs show the default as none.

**Comment by JensTrier** [comment]
@JohnGGeo it is. Please see https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps#description
