### ISSUE TITLE
Examples don't work in PowerShell, only in Windows PowerShell

### ISSUE THREAD

**Issue by robdy** [MicrosoftDocs/office-docs-powershell#8896]
All the examples use:
```
Get-Content (...) -Encoding byte
```
which doesn't exist in PowerShell 6+. It should be:
```
Get-Content (...) -AsByteStream
```

I can volunteer to send a PR for that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a65371d7-e254-1bf7-e3f3-035d294fe1cd
* Version Independent ID: cc63afcc-727b-c972-eb11-21d6a15f1d0e
* Content: [Import-CsOnlineAudioFile (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Import-CsOnlineAudioFile.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@robdy Thanks for the feedback!  If you have time, yes please add another example on how it should it be done on PowerShell 6+.

best regards
    Jens

**Comment by yogkumgit** [comment]
@robdy Thank you very much for the contribution and updating the documentation with PR. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
