### ISSUE TITLE
EndUserQuarantinePermissionsValue difference

### ISSUE THREAD

**Issue by rafaelborter** [MicrosoftDocs/office-docs-powershell#8902]
"EndUserQuarantinePermissionsValue" with "New-QuarantinePolicy" gives a different result than "Set-QuarantinePolicy", although the parameter is identical (00010111).
Can it be that "New-QuarantinePolicy" does not configure the "EndUserQuarantinePermissionsValue" correctly?

_Example 1 (New-QuarantinePolicy + Set-QuarantinePolicy)_

```powershell
New-QuarantinePolicy -Name "t1" -AdminNotificationFrequencyInDays 3 -AdminNotificationLanguage Default -AdminNotificationsEnabled $False -EndUserSpamNotificationFrequencyInDays 3 -EndUserSpamNotificationLanguage Default -ESNEnabled $True -QuarantineRetentionDays 15`
`Set-QuarantinePolicy -id "t1" -EndUserQuarantinePermissionsValue 00010111
```

**Result**

```powershell
EndUserQuarantinePermissions           : [PermissionToBlockSender: True
                                         PermissionToDelete: True
                                         PermissionToDownload: True
                                         PermissionToPreview: True
                                         PermissionToRelease: True
                                         PermissionToRequestRelease: False
                                         PermissionToViewHeader: False ]
```

_Example 2 (Only New-QuarantinePolicy)_

```powershell
`New-QuarantinePolicy -Name "t2" -AdminNotificationFrequencyInDays 3 -AdminNotificationLanguage Default -AdminNotificationsEnabled $False -EndUserQuarantinePermissionsValue 00010111 -EndUserSpamNotificationFrequencyInDays 3 -EndUserSpamNotificationLanguage Default -ESNEnabled $True -QuarantineRetentionDays 15
```

**Result**

```powershell
EndUserQuarantinePermissions           : [PermissionToBlockSender: True
                                         PermissionToDelete: True
                                         PermissionToDownload: True
                                         PermissionToPreview: True
                                         PermissionToRelease: True
                                         PermissionToRequestRelease: True
                                         PermissionToViewHeader: False ]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53115fda-2ef7-c359-93f2-f04231659e09
* Version Independent ID: 40a9b12a-0941-fcc3-0515-dbe996c35cbf
* Content: [Set-QuarantinePolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-quarantinepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-QuarantinePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-QuarantinePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rafaelborter, yikes. I did some testing, and my results even differ from yours.

```PowerShell
New-QuarantinePolicy -Name "chrisda test"

EndUserQuarantinePermissions : [PermissionToBlockSender: False
                               PermissionToDelete: False
                               PermissionToDownload: False
                               PermissionToPreview: False
                               PermissionToRelease: False
                               PermissionToRequestRelease: False
                               PermissionToViewHeader: True ]
```

This equates to 00x11011 (that x value for PermissionToAllowSender isn't shown and doesn't matter).

```PowerShell
New-QuarantinePolicy -Name "chrisda test2" -EndUserQuarantinePermissionsValue 00010111

EndUserQuarantinePermissions           : [PermissionToBlockSender: True
                                         PermissionToDelete: True
                                         PermissionToDownload: True
                                         PermissionToPreview: True
                                         PermissionToRelease: True
                                         PermissionToRequestRelease: True
                                         PermissionToViewHeader: False ]
```

The result equates to 01x11111, not 00x10111

```PowerShell
Set-QuarantinePolicy -Identity "chrisda test2" -EndUserQuarantinePermissionsValue 00010111

EndUserQuarantinePermissions           : [PermissionToBlockSender: True
                                         PermissionToDelete: True
                                         PermissionToDownload: True
                                         PermissionToPreview: True
                                         PermissionToRelease: True
                                         PermissionToRequestRelease: False
                                         PermissionToViewHeader: False ]
```

This result equates to 01x10111, not , not 00x10111.

Something else is going on. Testing reveals that you can set the following permissions independently of any/all others:

- ViewHeader (10000000)
- Download (01000000)
- BlockSender (00010000)
- Delete (00000001)

The remaining values seem to interfere/interact with each other:

For example, 00001000 should only set RequestRelease to true, but also sets ViewHeader, and Download to true as if you entered 11001000.

I'll try to find out what's going on.

**Comment by rafaelborter** [comment]
@chrisda 
Thanks for the feedback. If I use the decimal value instead of the binary value, I still get the wrong configuration.

I want to set the following configuration:
`EndUserQuarantinePermissions : [PermissionToBlockSender: True
                               PermissionToDelete: True
                               PermissionToDownload: True
                               PermissionToPreview: True
                               PermissionToRelease: True
                               PermissionToRequestRelease: False
                               PermissionToViewHeader: False ]`

With the value the configuration is not correct, I have to use mandatory "Set-QuarantinePolicy" for it to be adjusted. Whether I set 23 or the binary value at the "Set-QuarantinePolicy" does not matter. It works both. Only with "New-QuarantinePolicy" neither 23 nor the binary value works.

`PS C:\> New-QuarantinePolicy -Name "t1" -AdminNotificationFrequencyInDays 3 -AdminNotificationLanguage Default -AdminNotificationsEnabled $False -EndUserSpamNotificationFrequencyInDays 3 -EndUserSpamNotificationLanguage Default -ESNEnabled $True -QuarantineRetentionDays 15


RunspaceId                             : 5698b72d-1b5f-4890-8b26-bf784136422b
AdminDisplayName                       :
AdminNotificationFrequencyInDays       : 3
AdminNotificationLanguage              : Default
AdminNotificationsEnabled              : False
AdminQuarantinePermissionsList         : {}
CustomDisclaimer                       :
EndUserQuarantinePermissions           : [PermissionToBlockSender: True
                                         PermissionToDelete: True
                                         PermissionToDownload: False
                                         PermissionToPreview: True
                                         PermissionToRelease: False
                                         PermissionToRequestRelease: True
                                         PermissionToViewHeader: False ]
EndUserSpamNotificationFrequencyInDays : 3
EndUserSpamNotificationLanguage        : Default
ESNEnabled                             : True
QuarantinePolicyType                   : QuarantinePolicy
QuarantineRetentionDays                : 15
Identity                               : t1
Id                                     : t1
IsValid                                : True
ExchangeVersion                        : 0.20 (15.0.0.0)
Name                                   : t1
DistinguishedName                      : CN=t1,CN=Quarantine Settings,CN=Transport Settings,CN=Configuration,CN=issandbox6.onmicrosoft.com,
                                         CN=ConfigurationUnits,DC=CHEP278A002,DC=PROD,DC=OUTLOOK,DC=COM
ObjectCategory                         : CHEP278A002.PROD.OUTLOOK.COM/Configuration/Schema/ms-Exch-Hosted-Content-Filter-Config
ObjectClass                            : {top, msExchHostedContentFilterConfig}
WhenChanged                            : 2/24/2022 1:09:46 PM
WhenCreated                            : 2/24/2022 1:09:46 PM
WhenChangedUTC                         : 2/24/2022 12:09:46 PM
WhenCreatedUTC                         : 2/24/2022 12:09:46 PM
ExchangeObjectId                       : e80b15ee-12fc-4ea5-8aab-ad7ef5212c2e
OrganizationalUnitRoot                 : issandbox6.onmicrosoft.com
OrganizationId                         : CHEP278A002.PROD.OUTLOOK.COM/Microsoft Exchange Hosted Organizations/issandbox6.onmicrosoft.com -
                                         CHEP278A002.PROD.OUTLOOK.COM/ConfigurationUnits/issandbox6.onmicrosoft.com/Configuration
Guid                                   : e80b15ee-12fc-4ea5-8aab-ad7ef5212c2e
OriginatingServer                      : ZRAP278A02DC005.CHEP278A002.PROD.OUTLOOK.COM
ObjectState                            : Unchanged

PS C:\> Set-QuarantinePolicy -id "t1" -EndUserQuarantinePermissionsValue 00010111
PS C:\> Get-QuarantinePolicy -id "t1" | fl EndUserQuarantinePermissions

EndUserQuarantinePermissions : [PermissionToBlockSender: True
                               PermissionToDelete: True
                               PermissionToDownload: True
                               PermissionToPreview: True
                               PermissionToRelease: True
                               PermissionToRequestRelease: False
                               PermissionToViewHeader: False ]

PS C:\> New-QuarantinePolicy -Name "t2" -AdminNotificationFrequencyInDays 3 -AdminNotificationLanguage Default -AdminNotificationsEnabled $False -EndUserQuarantinePermissionsValue 23 -EndUserSpamNotificationFrequencyInDays 3 -EndUserSpamNotificationLanguage Default -ESNEnabled $True -QuarantineRetentionDays 15


RunspaceId                             : 5698b72d-1b5f-4890-8b26-bf784136422b
AdminDisplayName                       :
AdminNotificationFrequencyInDays       : 3
AdminNotificationLanguage              : Default
AdminNotificationsEnabled              : False
AdminQuarantinePermissionsList         : {}
CustomDisclaimer                       :
EndUserQuarantinePermissions           : [PermissionToBlockSender: True
                                         PermissionToDelete: True
                                         PermissionToDownload: False
                                         PermissionToPreview: True
                                         PermissionToRelease: True
                                         PermissionToRequestRelease: False
                                         PermissionToViewHeader: False ]
EndUserSpamNotificationFrequencyInDays : 3
EndUserSpamNotificationLanguage        : Default
ESNEnabled                             : True
QuarantinePolicyType                   : QuarantinePolicy
QuarantineRetentionDays                : 15
Identity                               : t2
Id                                     : t2
IsValid                                : True
ExchangeVersion                        : 0.20 (15.0.0.0)
Name                                   : t2
DistinguishedName                      : CN=t2,CN=Quarantine Settings,CN=Transport Settings,CN=Configuration,CN=issandbox6.onmicrosoft.com,
                                         CN=ConfigurationUnits,DC=CHEP278A002,DC=PROD,DC=OUTLOOK,DC=COM
ObjectCategory                         : CHEP278A002.PROD.OUTLOOK.COM/Configuration/Schema/ms-Exch-Hosted-Content-Filter-Config
ObjectClass                            : {top, msExchHostedContentFilterConfig}
WhenChanged                            : 2/24/2022 1:10:28 PM
WhenCreated                            : 2/24/2022 1:10:28 PM
WhenChangedUTC                         : 2/24/2022 12:10:28 PM
WhenCreatedUTC                         : 2/24/2022 12:10:28 PM
ExchangeObjectId                       : d42e8598-1e52-44bb-b9ac-b8e6756da9f1
OrganizationalUnitRoot                 : issandbox6.onmicrosoft.com
OrganizationId                         : CHEP278A002.PROD.OUTLOOK.COM/Microsoft Exchange Hosted Organizations/issandbox6.onmicrosoft.com -
                                         CHEP278A002.PROD.OUTLOOK.COM/ConfigurationUnits/issandbox6.onmicrosoft.com/Configuration
Guid                                   : d42e8598-1e52-44bb-b9ac-b8e6756da9f1
OriginatingServer                      : ZRAP278A02DC005.CHEP278A002.PROD.OUTLOOK.COM
ObjectState                            : Unchanged

PS C:\>`

**Comment by chrisda** [comment]
@rafaelborter, we are in agreement about the default values for EndUserQuarantinePermissionsValue:

|Permission|Binary|Decimal|
|:---|:---:|:---:|
PermissionToBlockSender: True|1|16|
PermissionToDelete: True|1|1|
PermissionToDownload: False|0|0|
PermissionToPreview: True|1|2|
PermissionToRelease: False|0|0|
PermissionToRequestRelease: True|1|8|
PermissionToViewHeader: False|0|0|
|**Total**|00011011|27|

According to your latest post, these are the permissions that you want:

|Permission|Binary|Decimal|
|:---|:---:|:---:|
PermissionToBlockSender: True|1|16|
PermissionToDelete: True|1|1|
PermissionToDownload: True|1|64|
PermissionToPreview: True|1|2|
PermissionToRelease: True|1|4|
PermissionToRequestRelease: False|0|0|
PermissionToViewHeader: False|0|0|
|**Total**|01010111|87|

Note that this configuration is different than the original value that we were dealing with (00010111 or 23). Either way, it's better to test using the end result that you want (which basically makes the default values irrelevant).

Here is my command output (which matches what you want):

```powershell
PS C:\Users\chrisda> New-QuarantinePolicy -Name "chrisda test 4" -EndUserQuarantinePermissionsValue 87

...
EndUserQuarantinePermissions           : [PermissionToBlockSender: True
                                         PermissionToDelete: True
                                         PermissionToDownload: True
                                         PermissionToPreview: True
                                         PermissionToRelease: True
                                         PermissionToRequestRelease: False
                                         PermissionToViewHeader: False ]
...
```

Here's futher testing/confirmation using Set- to first blank out all the permissions to False ('clear the board' so to speak), and then set the value to your desired permissions (87):

```powershell
PS C:\Users\chrisda> Set-QuarantinePolicy -Identity "chrisda test 4" -EndUserQuarantinePermissionsValue 0; Get-QuarantinePolicy -Identity "chrisda test 4" | FL EndUserQuarantinePermissions

EndUserQuarantinePermissions : [PermissionToBlockSender: False
                               PermissionToDelete: False
                               PermissionToDownload: False
                               PermissionToPreview: False
                               PermissionToRelease: False
                               PermissionToRequestRelease: False
                               PermissionToViewHeader: False ]

PS C:\Users\chrisda> Set-QuarantinePolicy -Identity "chrisda test 4" -EndUserQuarantinePermissionsValue 87; Get-QuarantinePolicy -Identity "chrisda test 4" | FL EndUserQuarantinePermissions

EndUserQuarantinePermissions : [PermissionToBlockSender: True
                               PermissionToDelete: True
                               PermissionToDownload: True
                               PermissionToPreview: True
                               PermissionToRelease: True
                               PermissionToRequestRelease: False
                               PermissionToViewHeader: False ]
```

So, I think it's working as expected. I think what we both learned is to not use binary values for the parameter, and to be very careful when comparing the output of the cmdlet vs. the order that you need to enter the values (they are very different, and it gets confusing very quickly).

**Comment by chrisda** [comment]
@yogkumgit, this one should be OK to close.
