### ISSUE TITLE
Missing "SkipDomainValidation" switches

### ISSUE THREAD

**Issue by crackermania** [MicrosoftDocs/office-docs-powershell#8903]
Hi,

Based on this article : https://docs.microsoft.com/en-us/powershell/module/exchange/add-recipientpermission?view=exchange-ps add-recipientpermission should have below switch 

[-SkipDomainValidationForMailContact]
[-SkipDomainValidationForMailUser]
[-SkipDomainValidationForSharedMailbox] 

I'm using it almost 5 months without any issue and suddenly it's missing from the switch.

Any changes recently at MS side? Im using ExchangeOnlineManagement version 2.0.5.

Thanks.

**Comment by blacktirion** [comment]
Same problem here. I was using 2.0.4 and have tried on the newer pre-releases. This isn't a module version issue, it's a commands being returned back from Exchange issue.

Why would this feature be turned off? It is crucial during migrations and needs to be fixed ASAP.

**Comment by blacktirion** [comment]
@kellybos 
Can you enlighten us as to why this was changed? The last commit to the documentation was yours, so maybe you can tell us what's going on.

**Comment by crackermania** [comment]
> @kellybos Can you enlighten us as to why this was changed? The last commit to the documentation was yours, so maybe you can tell us what's going on.

aha.. now the documentation are updated and consider it's not support anymore? No announcement and features remove suddenly.. or I'm missing some announcement here...

**Comment by yogkumgit** [comment]
@crackermania Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
