### ISSUE TITLE
Remove-CSPhoneNumberAssignment -RemoveAll parameter does not remove phone number

### ISSUE THREAD

**Issue by marmstrong94** [MicrosoftDocs/office-docs-powershell#8904]
When using the Remove-CSPhoneNumberAssignment cmdlet, the listed "RemoveAll" parameter does not remove the OnPremLineURI attribute from the user. I currently still need to use Set-CSUser and set -OnPremLineURI to $null.
![OnPremLineURI](https://user-images.githubusercontent.com/18495391/152450389-84813ba9-f655-404e-9b67-7d7e297e51b2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3e0d4c-afea-582b-ed0a-f61d89f9016f
* Version Independent ID: e355f395-5cc4-b9db-1932-ce9b898b5c6d
* Content: [Remove-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@marmstrong94  Thanks for the feedback!

What is your scenario regarding the origin of the OnPremLineUri? Also did you allow for some delay between the remove cmdlet and looking via Get-CsOnlineUser?

If the LineUri attribute is managed online, the Set-CsPhonenumberAssignment will set the OnpremLineURI and Remove-CsPhoneNumberAssignment -RemoveAll will clear it again.

If the LineUri attribute is managed/coming from on-premises Active Directory, the Remove-CsPhoneNumberAssignment -RemoveAll cmdlet will issue an error message saying that you first need to clear the phone number on-premises.

**Comment by michalsvora** [comment]
Hi, seems I hit similar issue. 
I would say the cmdlet removes the OnPremLineURI if the user is licensed for EV but not in case the user already lost the license.  It's probably also the case of @marmstrong94 as the user on screenshot has EV disabled. 
Basically the command _"Remove-CsPhoneNumberAssignment -Identity TeamsPhone@asdfg.com -RemoveAll"_ finishes for unlicensed user without any error but the OnPremLineURI is there even after a week.
We assign the OnPremLineURI with script during provisioning so not via AD. 

I wonder that Set-CSUser and set -OnPremLineURI to $null still works for @marmstrong94 because I'm getting error for unlicensed users since weeks. 
_Set-CsUser : Cannot modify the parameter: "OnPremLineURI" because it is restricted for the user service plan: MCOProfessional._
thanks for help

**Comment by marmstrong94** [comment]
@JensTrier 

I've traditionally set the OnPremLineURI via the Set-CsUser command with the -OnPremLineURI parameter for a given user--so not coming from AD. I allowed for some delay, but not much, I've historically seen the results somewhat quickly with the Set-CsUser commands. If that's different now, that might be good to note in the docs.

I do have the same issues as @michalsvora where if the user is unlicensed, I can't remove the phonenumber. At least that was true with Set-CsUser. I would have to relicense a user and wait a while before I could remove their number. Which is difficult.

I'd be willing to conduct testing if needed.

**Comment by DEberhardt** [comment]
`Remove-CsPhoneNumberAssignment -RemoveAll` also does not disable EV if no PhoneNumber is present on the User anymore...

**Comment by yogkumgit** [comment]
@JensTrier Please reply

**Comment by DEberhardt** [comment]
> are you able to set the flag to false using Set-CsPhoneNumberAssignment -EnterpriseVoiceEnabled $false

My testing was hampered by inconsistent results across tenants.
On some tenants I was able to do so, on others, it simply did not want to disable EV.

This would be a classic example of having to use the `-Force`  😄

**Comment by DEberhardt** [comment]
As in `Remove-CsPhoneNumberAssignment -RemoveAll -Force` to clean an object regardless of status (Removal of OnPremLineUri, LineUri, TelephoneNumber, EnterpriseVoiceEnabled flag). There is also a DIRSYNC issue I have in the back of my mind that would be good if we can address this one (OnPremLineUri cannot be set/changed/removed if object is moved from Skype and OnPremLineUri is set via DirSync...)
