### ISSUE TITLE
Set-CsPhoneNumberAssignment Errors

### ISSUE THREAD

**Issue by Lukasbbg** [MicrosoftDocs/office-docs-powershell#8905]
Hi,
I am trying out the new Set-CsPhoneNumberAssignment for usage in my Organisation, yet all I get are errors.

When I try to set a number to a account one of three things happens:
1. Error: BadRequest - Telephone Number '()' is not found from tenant '()'  | using PhoneNumberType OperatorConnect
2. Error: BadRequest - User '()' lacks appropriate licenses to assign a 'CallingPlan' number | Using PhoneNumberType CallingPlan
3. When I use PhoneNumberType DirectRouting nothing happens. Aftere a while of progressing (I guess) i get a new command line but the number is not assigned

Also by trying to use the Command - Set-CsPhoneNumberAssignment -Identity '()' -EnterpriseVoiceEnabled $true | I get this:
![image](https://user-images.githubusercontent.com/99027803/152540444-b402a1a5-24b5-49f5-b383-f4d5e0351283.png)
(...) Is that normal?

Same goes for Remove-CsPhoneNumberAssignment if I try to remove a number from a already existing and working account. When I use it with CallingPlan, OperatorConnect or DirectRouting I always get Error: BadRequest - Telephone Number '()' is not found from tenant '()'
When I try -RemoveAll it works.

So: Where can I lookup what PhoneNumberType I am using? Am I donig something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@Lukasbbg Thanks for the feedback

You as the administrator basically need to know what type of phone number you are going to assign. This article discuss the the 3 different options https://docs.microsoft.com/en-us/microsoftteams/pstn-connectivity

There are some requirements to assigning phone numbers of the different types. These include licensing on the user and also availability of a phone number in your tenant of a certain type. This page talks about this for Calling Plan and Operator Connect https://docs.microsoft.com/en-us/microsoftteams/assign-change-or-remove-a-phone-number-for-a-user. For Direct Routing it is here https://docs.microsoft.com/en-us/microsoftteams/direct-routing-enable-users

So for Operator Connect and Calling Plan you need to acquire your phone numbers before they can be assigned. It doesn't sound like you have done so based on the first 2 errors.

If you use Set-CsPhoneNumberAsisignment on a user with a Direct Routing number and the cmdlet succeeds, i.e. no error is shown, then the number is assigned and you should be able to see it displayed by Get-CsOnlineUser after a delay.

Just checking: in the cmdlet examples you give you are using '()' for identity. Is that for privacy reasons? For the actual cmdlet calls these needs to be the Identity of the user, i.e. user1@contoso.com. If you use real identities the Set-PSPhoneNumberAssignment -EnterpriseVoiceEnabled $true cmdlet should work.

**Comment by Lukasbbg** [comment]
@JensTrier Thanks for the quick answer

First: sorry for the inconvenience, I am still learning al this stuff and only working in this field since 5 months.
Second: Your commend really helped me. Could you tell me which tag is for the telephone number? Is it the LineURI?
I got these when I use Get-CsOnlineUser
LineURI
OnPremLineURI (I guess thats for Azure?)
Phone (In the Mail section --> I guess signature)

And yes I am useing () for privacy reasons. To ad the Set-PSPhoneNumberAssignment -EnterpriseVoiceEnabled $true did work without all the text this time.

Thank you!

**Comment by JensTrier** [comment]
@Lukasbbg Thanks for the background. LineUri is what is storing the phone number on a user.

**Comment by JensTrier** [comment]
@zaichornik Thanks for bringing this up! Your suggested approach is correct. I'll update the PS cmdlet documentation page to reflect the same.

**Comment by JB-1** [comment]
Hello @JensTrier,
Is there a place I can get all the possible error codes (Code, Message pairs) that are returned? 

Out of curiosity, I was wondering why a try catch block approach wasn't used?

try{
Set-CsPhoneNumberAssignment -Identity user1@contoso.com -PhoneNumber +12065551234 -PhoneNumberType CallingPlan  -ErrorAction Stop
}catch{
# Log the error
}

**Comment by JensTrier** [comment]
@JB-1 Unfortunately, there is not such a place. I'll take the feedback to the team.

**Comment by DimaRazb** [comment]
Why this new commandlet works so poor?
![Untitled](https://user-images.githubusercontent.com/29647985/164284539-3f08167f-a993-4daf-b427-9808b69afebf.png)

**Comment by JensTrier** [comment]
@DimaRazb Thanks for the feedback. What is the specific issue you want to bring up?

**Comment by JB-1** [comment]
Can we get a success code back when the commadlet assigns a number.  Something like this:
Code: Success
Message: Telephone Number 'xxxxxxxxxxx' has been assigned to user UserName@domain.ext 
Also, any luck on getting that list of error codes?

**Comment by DimaRazb** [comment]
Hello @JensTrier,
It should work from the first time, what if I'm doing scripting and assigning the numbers in a bulk? The previous commandlet we used didn't have such a thing and was **reliable**.

**Comment by JensTrier** [comment]
@JB-1 Success is implicit in the sense that no error message is returned. We are not planning to change that. However we are planning to generate an exception, when an error occurs. Please stay tuned.

@DimaRazb I understand the issue now. I looked at our telemetry and you are hitting a known issue that we are in the process of fixing. In your tenant you have a hybrid/on-premises phone number with an extension and the same base as your Calling Plan phone number, i.e. CP number 12345 and a hybrid number 12345;ext=1234.

**Comment by zaichornik** [comment]
Hi, 
One question regarding _Set-CsPhoneNumberAssignment_ command.
Is it possible to assign the **same number to 2 different accounts** (either employee or resource account) in _DirectRouting_ mode in the same tenant ?
In other words - are there any internal validation for assignment uniqueness regarding the phone numbers?

Sorry if that is answered somewhere already or documented (refer to docs if any).

Thanks in advance.

**Comment by JensTrier** [comment]
@zaichornik No, it is not possible. There is uniqueness validation.

What is your scenario?

**Comment by zaichornik** [comment]
Hi @JensTrier,

A new question from my side with slightly different accent, but related to _Set-CsPhoneNumberAssignment_ command.

The question is for _Get-CsOnlineUser_ -Filter "**whenCreated | whenModified**"

The specified filters in bold was deprecated / forbidden recently by Microsoft, but at the same time - they are a cornerstones  for developing custom tools for administering a Teams environment/tenant. 

Are you planning to support them again or these are not part of the future plan. If not, probably there is a good reason behind.

I am sorry if this thread is not the write place for this question, but did not find other.

Thanks.

**Comment by zaichornik** [comment]
Hi @isrumnon, 

Thanks for your rapid feedback.

What about _whenCreated_ AzureAD attribute, are you planning to bring it back to the game as well ?
