### ISSUE TITLE
Links on this page are an infinite loop

### ISSUE THREAD

**Issue by BlitzkriegSoftware** [MicrosoftDocs/office-docs-powershell#8906]
Clicking on https://docs.microsoft.com/en-us/powershell/teams/?view=teams-ps, returns to this page, and not to a list of command-lets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82bf8ef2-fd7a-6f93-b6da-85a3ceb31ead
* Version Independent ID: 5f42884e-b6e3-a568-a5b0-a573f699b12b
* Content: [Microsoft Teams cmdlet help reference](https://docs.microsoft.com/en-us/powershell/teams/?view=teams-ps)
* Content Source: [teams/docs-conceptual/index.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/docs-conceptual/index.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @BlitzkriegSoftware, thank you for your feedback.

I cannot find the link you are referring on this article. You can click on Reference to see the list of cmdlets.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and digging deep into it.  @BlitzkriegSoftware We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
