### ISSUE TITLE
This cmdlet is no longer supported?

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#8918]
I'm running the 3.1.0 version of the MicrosoftTeams PowerShell module and when I attempt to run this cmdlet on one of our test servers, I get the following error

PS C:\Users\test> Grant-CsHostedVoicemailPolicy -Identity "user@abc.com" -PolicyName ""
Invoke-CsDeprecatedError : This cmdlet is no longer supported, please consult public documentation
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.1.0\net472\exports\ProxyCmdletDefinitions.ps1:21317
char:9
+         $steppablePipeline.Process($_)
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-CsDeprecatedError

PS C:\Users\test> Get-InstalledModule -Name MicrosoftTeams

Version    Name                                Repository           Description
3.1.0      MicrosoftTeams                      PSGallery            Microsoft Teams cmdlets module for Windows Power...

On another server that has 3.1.0, when I execute the exact same cmdlet, it does not fail (using the same login credentials)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a74dcac3-4509-56cf-1d21-715b564d7eee
* Version Independent ID: 43fb3a07-83c9-fa3d-b446-074c53faeeb3
* Content: [Grant-CsHostedVoicemailPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-cshostedvoicemailpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsHostedVoicemailPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsHostedVoicemailPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by dariomws** [comment]
Hi @sarollins, thank you for your feedback.

For Microsoft Teams you should use Grant-CsOnlineVoicemailPolicy. For more information, see https://docs.microsoft.com/microsoftteams/manage-voicemail-policies.

**Comment by sarollins** [comment]
So, we're grabbing 2 attributes from the Get-CsOnlineUser cmdlet.  One is the HostedVoicemailPolicy, the other is the OnlineVoicemailPolicy.  We've been using the Grant-CsOnlineVoicemailPolicy cmdlet to set the OnlineVoicemailPolicy and the Grant-CsHostedVoicemailPolicy for the HostedVoicemailPolicy values

**Comment by dariomws** [comment]
@sarollins, please use the following article to set Voicemail policies for Microsoft Teams:
https://docs.microsoft.com/microsoftteams/manage-voicemail-policies

HostedVoicemailPolicy is used, for example, to configure Microsoft Cloud Voicemail service for your Skype for Business on-premises users:
https://docs.microsoft.com/skypeforbusiness/hybrid/configure-cloud-voicemail
