### ISSUE TITLE
ClearAutoMapping

### ISSUE THREAD

**Issue by jonsmith40** [MicrosoftDocs/office-docs-powershell#8920]
The ClearAutoMapping switch documentation is unclear. Using it only throws an error. Please validate the documentation and give viable examples

**Comment by chrisda** [comment]
@jonsmith40, are we talking about ClearAutoMapping on the Remove-MailboxPermission cmdlet?

This parameter is available or functional only in the cloud-based service.

The ClearAutoMapping switch specifies that the mailbox is automatically mapped (auto-mapped) by Autodiscover only into the mailbox owner's Outlook profile. You don't need to specify a value with this switch.

The mailbox isn't auto-mapped to other users who have FullAccess permission to the mailbox.

To re-add auto-mapping capability on the mailbox for other users, run the command: `Add-MailboxPermission -Identity <MailboxIdentity> -AccessRights FullAccess -AutoMapping $true`.

**Comment by chrisda** [comment]
@jonsmith40, sorry. I thought I responded to this before I went on vacation.

According to [this article](https://docs.microsoft.com/outlook/troubleshoot/profiles-and-accounts/remove-automapping-for-shared-mailbox), it appears that when you add Full Access permissions to a mailbox, you need to disable auto-mappping **at that time** for it to work. If you didn't then you need to start over:

> To disable automapping, use Windows PowerShell to remove full access permissions from the user for the mailbox, and then add back full access permissions to the user. When you add back full access permissions to the user, use the AutoMapping:$false parameter. 

Granted, this article is talking about shared mailboxes, but based on your colleague's experience, it sounds like that's what's happening.

It makes you wonder what the point of having ClearAutoMapping on Remove-MailboxPermission is?

**Comment by chrisda** [comment]
@jonsmith40, further research reveals that the ClearAutoMapping switch is meant to exclude the mailbox from auto-mapping for ALL users who have Full Access permission to the mailbox. So, if 50 users have Full Access permission to the John Doe mailbox, the following command should prevent the John Doe mailbox from being automatically opened/added to the Outlook profiles of the 50 users:

```PowerShell
Remove-MailboxFolderPermission -Identity "John Doe" -ClearAutoMapping
```

Does this make sense, and does it work as intended?
