### ISSUE TITLE
Get-MobileDevice / Get-MobileDeviceStatistics document is incorrect

### ISSUE THREAD

**Issue by sgtwtf** [MicrosoftDocs/office-docs-powershell#8923]
The details for the -Identity switch are incorrect and the first example you have listed shows an incorrect usage.

The first example is "Get-MobileDeviceStatistics -Identity TonySmith" You can not use display name with that switch according to your own article. Only with the -mailbox switch can display name be used.
![image](https://user-images.githubusercontent.com/7502836/152866324-ab5b37bb-ee20-4129-b87e-bd14d59c5f61.png)

Also -Identity says you can use DeviceID and GUID. that is also incorrect.  GUID works fine but DeviceID is not it should Read "ID" or "Identity"
![image](https://user-images.githubusercontent.com/7502836/152869542-6eed416f-f316-475b-bc0f-e1cad4873bce.png)
![image](https://user-images.githubusercontent.com/7502836/152870472-bb9d4835-bd4c-41e9-bd64-e2fdb890a7a8.png)

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d1678b-3597-59a2-0f16-63948c3853d2
* Version Independent ID: 35ffe226-1c51-81a5-7ddc-b7439f6f3480
* Content: [Get-MobileDeviceStatistics (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mobiledevicestatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MobileDeviceStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MobileDeviceStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@sgtwtf, thanks for pointing that out. The Identity parameter is of Type MobileDeviceIdParameter, and exists in these cmdlets:

 - Clear-MobileDevice
 - Get-MobileDevice
 - Remove-MobileDevice
 - Get-MobileDeviceStatistics
 
You're correct in that DeviceID is not supported, but GUID is. However, other identifier values are also supported. I tested Get-MobileDevice and Get-MobileDeviceStatistics, and I updated the Identity parameter descriptions as follows:

> You can use the following values that uniquely identifies the mobile device:
>
> - Identity (`<Mailbox Name>\ExchangeActiveSyncDevices\<MobileDeviceObjectName>` for example, `TonySmith\ExchangeActiveSyncDevices\REST§Outlook§5eec4e931e0748a263512fd73770d5ac`)
> - Distinguished name (DN)
> - GUID (same as ExchangeObjectId)

I also updated any/all examples that used the Identity parameter.
