### ISSUE TITLE
Gallatin Conntection Issue for Exchange Online Powershell Module v2

### ISSUE THREAD

**Issue by jackbob2020110** [MicrosoftDocs/office-docs-powershell#8927]
follow the doc, create the azure app and grant permisson and upload cert, added aad roles as Exchange Administrator as SPN. run the command:

```powershell
Connect-ExchangeOnline -ExchangeEnvironmentName O365China -AppId f9684132-be1f-45da-835a-e296116f7cb8 -CertificateThumbprint XXXXX -Organization "XXXXXX.partner.onmschina.cn" -Verbose

New-ExoPSSession : Processing data from remote server partner.outlook.cn failed with the following error message: [AuthZRequestId=2f19e449-d15e-48f3-8cb3-9555bcbeaf][FailureCategory=AuthZ-CmdletAccessDeniedException] The application **f9684132-be1f-45da-835a-e296116f7cb8** isn't assigned to any management roles. Please check online documentation for assigning Directory Roles to Azure AD Application. For more information, see the about_Remote_Troubleshooting Helpvtopic.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\netFramework\ExchangeOnlineManagement.psm1:475 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-ExoPSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Exchange.Management.ExoPowershellSnapin.New
   ExoPSSession
```

with the same steps on WW instance, no issue found. please help, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@jackbob2020110 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.

**Comment by jackbob2020110** [comment]
ok, thanks!
