### ISSUE TITLE
Resource Accounts

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/office-docs-powershell#8932]
With Teams PS Module 3.0, 3.1 and 3.1.1, Grant-CsOnlineVoiceRoutingPolicy no longer appears to work on Resource Accounts.  I've tried with both powershell 5.1 and 7.2.1 with zero success and results with the following:
Grant-CsUserPolicy_GrantExpanded: C:\Users\user\OneDrive\Documents\PowerShell\Modules\MicrosoftTeams\3.1.0\netcoreapp3.1\custom\PsExt\Grant-CsUserOrTenantPolicy.ps1:61
Line |
  61 |              Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPo …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | User does not exist

Currently the only way I can apply a voice routing policy to a Resource Account is to down grade the Teams Module to 2.6.0
K.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58aa424-e87c-e4cb-d6a3-49a0d842f831
* Version Independent ID: 8d1e09fa-7896-56e8-c294-8cac6c35d8d3
* Content: [Grant-CsOnlineVoiceRoutingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by Korbyn72** [comment]
additional note, get-csonlineuser for the resource account name works, and it is assigned the Phone Standard - Virtual User license.  I also tried removing the policy from another resource account that has been working for months, with the same "User does not exist" result.

**Comment by Rh1-no** [comment]
I can also confirm that I am having the same issue with the last few iterations of TeamsPS. 

I have the issue with both new and existing RA's and have to resort to downgrading to 2.6 for it to work for me. 

`Grant-CsOnlineVoiceRoutingPolicy -Identity 'RA_SIP' -PolicyName "Policy_name"
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPolicy : User does not exist
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.1.1\net472\custom\PsExt\Grant-CsUserOrTenantPolicy.ps1:61 char:13
+             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPo ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = ...ntUserRequest }:<>f__AnonymousType56`3) [Grant-CsUserPolicy_GrantExpanded], Ex 
   ception
    + FullyQualifiedErrorId : ClientError,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GrantCsUserPolicy_GrantExpanded
`

As per the documentation I have also tried the account in other formats such as  SIP address, UPN and the user's Active Directory display name and get the same error.

**Comment by Korbyn72** [comment]
The issue was resolved Thursday morning for all 3.x teams ps modules.  About an hour AFTER I redid customer documentation for  with the 2.6 module...  at the same time having another cx migrating from lync to downgrade from 2.6to 2.3.1 as the move csuser broke...  really hope for more stability and consistency at some point, keeping up and keeping everyone functioning is quite maddening

Sent from my mobile device
________________________________

**Comment by dariomws** [comment]
Hi all,

Thank you for your feedback.

I have tested it with 3.1.1 in a lab tenant and it works for me.

If you still have this issue, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @Korbyn72 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Korbyn72** [comment]
I did call in a log a support case, they responded with using set-csonlinevoic.... completely wrong command and purpose...  eventually they saw the light and escalated internally to engineering and closed my case.

Sent from my mobile device
________________________________

**Comment by Korbyn72** [comment]
You can reclose the case, I posted 7-10 days ago that it was fixed, but I believe it was from posting here and talking to Support was a waste of 48 hours

Sent from my mobile device
________________________________

**Comment by olanga** [comment]
It is so frustrating... We run Teams PS Module 3.1.1 and today we have been hit by the same issue with ressource accounts:
Grant-CsTenantDialPlan -Identity $UPN -PolicyName "Policy"
Grant-CsUserPolicy : User does not exist
FullyQualifiedErrorId : ClientError,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GrantCsUserPolicy_GrantExpanded

**Comment by dariomws** [comment]
@olanga, please try the latest version of the module (4.4.1).
