### ISSUE TITLE
OnlineDialOutPolicy empty

### ISSUE THREAD

**Issue by rhrotman** [MicrosoftDocs/office-docs-powershell#8935]
As of the 3.x version of this module, the Get-CsOnlineUser command doesn't show any output for the OnlineDialOutPolicy attribute anymore, which prevents us from checking if the right DialOutPolicy was granted. We use this to limit the number of users who can make international phone calls.

E.g. when granted the policy DialoutCPCInternationalPSTNDomestic, it should show:
OnlineDialOutPolicy : DialoutCPCInternationalPSTNDomestic
Instead it's now blank. Verified with version 2.6.0 of the module that the information was still there.

**Comment by andreprakash** [comment]
We have the same issue, it affects Teams PowerShell Module 3.x (tested with 3.0, 3.1 and 3.1.1). We are required to use an earlier PS-Module to ensure that calling is only allowed for certain users.

**Comment by andreprakash** [comment]
> I know that's only a workaround. But if you are really stuck, you can still request the full list of users.

Somehow, I do not see any objectid being returned and if using the get-csonlineuser command the OnlineDialOutPolicy is empty too...
![image](https://user-images.githubusercontent.com/99743066/154697274-e61833f0-5cd5-4ca8-a202-203bb08f1d63.png)

**Comment by vincentkurmi** [comment]
Hi @andreprakash, 

I tried on several tenants and when I don't specify an identifier, I always have the old attributes.
I am little bit concern that we don't have all the same behavior. 

![image](https://user-images.githubusercontent.com/52075388/154703421-8ff14e5b-ca9b-4db2-a689-803863443f44.png)

**Comment by vincentkurmi** [comment]
I installed the latest version 3.2.0-preview and now I have your behavior. So we can assume, they decided to remove the previous behavior. But anyway the OnlineDialOutPolicy is still empty. 

![GetCSOnlineUser3_2_0-preview](https://user-images.githubusercontent.com/52075388/154716630-73e344b3-61f9-46bf-818c-a1fb04fbd8e0.png)

![GetCSOnlineUser3_1_1](https://user-images.githubusercontent.com/52075388/154716747-62266807-acde-41e1-9a57-09c03419b136.png)

In the new version it takes a lot of time, but it can be relative to the preview release.

**Comment by donlassini** [comment]
Workaround that also returns the policy but where you still retrieve only one user:
```
PS> Get-CsOnlineUser -Filter "Userprincipalname -eq '$upn'"|fl OnlineDialOutPolicy

OnlineDialOutPolicy : DialoutCPCandPSTNDomestic
```

**Comment by dariomws** [comment]
Hi @rhrotman, thank you for your feedback.

This issue is well known and we are expecting a fix by end of March. Please follow up on the linked issues for more information.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @rhrotman Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
