### ISSUE TITLE
HostedVoiceMail replacement

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#8939]
We've been updating our product to use the new Set-CsPhoneNumberAssignment, but do not see how to set the HostedVoiceMail attribute and even though HostedVoiceMail is still an option in the Set-CsUser cmdlet, when we attempt to use it, we get the error that "HostedVoiceMail is not a supported property"

Set-CsPhoneNumber does not list this as a valid parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76cebc8c-7403-8981-a993-ed1079eb513c
* Version Independent ID: 015533c1-6a15-3dc1-083d-3370bdc3915d
* Content: [Set-CsUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by JensTrier** [comment]
@sarollins Thanks for the feedback! HostedVoiceMail is not needed to be set for Microsoft Teams users and that's why the parameter is not available on Set-CsPhoneNumberAssignment. I'm in the process of updating the Cloud Voicemail documentation to make this clear.

Feel free to close this issue.

**Comment by sarollins** [comment]
Documentation to be updated that this field is not needed for Teams Users

**Comment by sarollins** [comment]
Documentation to be updated that this field is not needed for Teams Users

**Comment by yogkumgit** [comment]
@sarollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by cgskreddy** [comment]
If you want to prevent calls from going to voicemail, create a "Teams Calling Policy", configure "AllowedVoicemail" attribute as "AlwaysDisabled" and assign it to the account. By default the global policy is applied with which calls are redirected to the voicemail if not answered. You can refer to [Set-CsTeamsCallingPolicy (SkypeForBusiness) | Microsoft Docs](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps) for more information.
