### ISSUE TITLE
New-CsAutoAttendant Example 3 not valid

### ISSUE THREAD

**Issue by heintonny** [MicrosoftDocs/office-docs-powershell#8944]
I think Example 3 in New-CsAutoAttendant is no longer valid.

https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsAutoAttendant.md

When I try to create two Attendant who share the same Schedule I get this error message:

```
New-CsAutoAttendant: After hours schedules should not be shared by multiple auto attendants.
```

**Comment by dariomws** [comment]
Hi @heintonny, thank you for your feedback.

The only error I found in example 3 is executing New-CsAutoAttendantMenu cmdlet:
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/33589238/155305830-5e4dbf6c-2416-466a-a10c-7caec3298cf0.png">

I had to add the last parameter:
$dcfMenu = New-CsAutoAttendantMenu -Name "Default menu" -Prompts @($dcfMenuPrompt) -EnableDialByName -DirectorySearchMethod ByName

As you can see, both AA were assigned to the same schedule:
<img width="940" alt="image" src="https://user-images.githubusercontent.com/33589238/155306003-d3b1011f-2ca9-4219-9059-74154c6b3329.png">

Are you using the latest version of the module? (3.1.1)
