### ISSUE TITLE
Teams PS: Ensure compatibility across tenant versions

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/office-docs-powershell#8947]
Sometimes cmdlets changes are released that depend on the tenant version; hence, the same cmdlet could work with one tenant, and fail with another, if the latter has not been upgraded.

Given that we have automatic solutions that log on to e.g. customers' or or own tenants, and given that we cannot query for the tenant version ourselves, I suggest that all functions that require specific tenant versions first check that version, and if the tenant has not been upgraded, then the function should fall back and use the old implementation.

I agree that it would cost more to maintain, but it's really a pain having to create a working platform that supports both.
Also, given that the window where older versions are still working is shrinking (we were recently informed that old versions might not work as of April 2022).

**Comment by DEberhardt** [comment]
We are facing the same issue across multiple tenants.
The Admin experience with the MicrosoftTeams module leaves many admins with a shrinking hairline (and I don't think that is purely age-related 😉 )

Backwards compatibility was always one of Microsofts strong believes, I hope this has not changed for the Cloud.

Can I ask that the changes that are introduced silently are communicated better and more openly, especially ones that impact the behavior of CmdLets please? Could they be tied to the PowerShell Module Version so we know that the same behavior is experienced with the same version? 

Thank you,
David

**Comment by dariomws** [comment]
Hi @donlassini, thank you for your feedback.

Here we are limited to documentation issues and improvements. For this kind of feedback, I suggest you use the new portal (Microsoft feedback):
https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

**Comment by yogkumgit** [comment]
@DEberhardt Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised as here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
