### ISSUE TITLE
Update TrustedOrganizations on Set-InboundConnector (and other relevant places)

### ISSUE THREAD

**Issue by stanalek** [MicrosoftDocs/office-docs-powershell#8950]
TrustedOrganization description currently shows:
{{ Fill TrustedOrganizations Description }}

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0730732-c585-4e29-a923-a1b5c9fb5bbb
* Version Independent ID: 66a7125a-149a-e485-e10d-a745ff0dbe95
* Content: [Set-InboundConnector (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-inboundconnector?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/Set-InboundConnector.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-InboundConnector.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@stanalek, empty parameter descriptions like that are a known issue. The parameter is definitely available, but should it be? Does it work? See more about the issue [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).

So can you vouch for this parameter? Do you know how it works and if it works? If so, you can easily add a description. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

**Comment by yogkumgit** [comment]
@stanalek Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
