### ISSUE TITLE
Using SPMT Powershell cmdlets when SPOnline does not allow legacy sign-in methods

### ISSUE THREAD

**Issue by GarthMartin** [MicrosoftDocs/office-docs-powershell#8951]
Trying to use SPMT PS cmdlets to migrate file shares to SPO.  Our sandbox tenant allows legacy sign-in methods, however the production build does not.  Our PS scripts are failing with "Cannot contact web site ‘https://tenant-admin.sharepoint.com/’ or the web site does not support SharePoint Online credentials. The response status code is ‘Unauthorized'” errors, which I am fairly confident is related to the sign-on method.

Does SPMT support AppOnly credentials?  I have not found anything indicating that it does.  Could we use Connect-PnPOnline somehow to make this work?  Note that our PS scripts are running under a windows service unattended, so no user intervention is possible.

**Comment by get-itips** [comment]
Hello @GarthMartin 
The current methods of authentication are the ones described in the article https://docs.microsoft.com/en-us/powershell/module/spmt/register-spmtmigration

>-SPOCredential
The credentials are used to connect the SharePoint Online tenant. If no credentials are passed in, use ADAL OAuth2. Important: If you are using multifactor authentication on your tenant, do not use the -SPOCredential parameter. The ADAL dialog will prompt for authentication and MFA.

**Comment by gapito** [comment]
hi, i am trying to use register-spmtmigration without the -spocredentials flag but the command is just completed without the ADAL dialog.
