### ISSUE TITLE
set-CsOnlineDialInConferencingUser Reset Leader Pin

### ISSUE THREAD

**Issue by blggmitch** [MicrosoftDocs/office-docs-powershell#8952]
Can't seem to find anywhere if you can resetleaderpin manually .
Here is the script in full.. Set-CsOnlineDialInConferencingUser -id amos.marble@contoso.com -ResetLeaderPIN 
It only allows the pin to be auto generated.  
Any ideas?

Thanks

**Comment by dariomws** [comment]
Hi @blggmitch, thank you for your feedback.

I think you may find the following article useful:
https://docs.microsoft.com/microsoftteams/reset-the-audio-conferencing-pin-in-teams

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @blggmitch Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by blggmitch** [comment]
I was aware of that MS article. I was trying to make it so we could manually assign/create our own pin and not have it auto generated.
Thanks

**Comment by dariomws** [comment]
Hi @blggmitch,

I understand there is no way to assign your custom PIN. Here we are limited to documentation issues and improvements.

I know the product teams are always looking for user feedback and how to make Microsoft Teams better. They keep a close tab on user feedback and it would be awesome if you could add your voice in the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to making the docs better! Much appreciated!

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @blggmitch Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
