### ISSUE TITLE
StartDate and EndDate do have default values

### ISSUE THREAD

**Issue by tylermontneyacc** [MicrosoftDocs/office-docs-powershell#8953]
After a lengthy case with Microsoft Support, I determined the reason `Get-MessageTraceDetail` did not return data for "older" entries is because `StartDate` and `EndDate` must be specified. It appears `StartDate` is 48 hours ago, and `EndDate` is now. [Get-MessageTrace](https://docs.microsoft.com/en-us/powershell/module/exchange/get-messagetrace?view=exchange-ps) suggests this to be true:

> If you run this cmdlet without any parameters, only data from the last 48 hours is returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690f2980-4a4e-7efd-fe5e-29c551c02e6f
* Version Independent ID: 4ab7a6db-db36-c736-6ce5-2f0e74b0cf6a
* Content: [Get-MessageTraceDetail (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-messagetracedetail?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MessageTraceDetail.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-MessageTraceDetail.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@tylermontneyacc, OK, I added the following text to the StartDate and EndDate parameter descriptions:

> If don't use the StartDate and EndDate parameters, only data from the last 48 hours is returned.

Thanks for the feedback.

Closing
