### ISSUE TITLE
Various errors calling Connect-MicrosoftTeams

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#8955]
We are trying to help a client of ours who, when the attempt to connect using this cmdlet, they get the following errors

$user = 'user@domain.com'
$pw = 'aPassword'
$cred = New-Object System.Management.Automation.PSCredential($user,  (ConvertTo-SecureString $pw -AsPlainText -Force))
Connect-Microsoftteams -Credential $cred
Connect-Microsoftteams : One or more errors occurred.
At line:4 char:1
+ Connect-Microsoftteams -Credential $cred
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AggregateException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams
 
Connect-Microsoftteams : An error occurred while sending the request.
At line:4 char:1
+ Connect-Microsoftteams -Credential $cred
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], HttpRequestException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams
 
Connect-Microsoftteams : The underlying connection was closed: An unexpected error occurred on a send.
At line:4 char:1
+ Connect-Microsoftteams -Credential $cred
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], WebException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams
 
Connect-Microsoftteams : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
At line:4 char:1
+ Connect-Microsoftteams -Credential $cred
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], IOException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams
 
Connect-Microsoftteams : An existing connection was forcibly closed by the remote host
At line:4 char:1
+ Connect-Microsoftteams -Credential $cred
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], SocketException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams
 
Connect-Microsoftteams : Object reference not set to an instance of an object.
At line:4 char:1
+ Connect-Microsoftteams -Credential $cred
    + CategoryInfo          : NotSpecified: (:) [Connect-MicrosoftTeams], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams

If they enter Connect-MicrosoftTeams and enter the credential information specified by the variables, they do properly get connected, so we know their credentials work and we know that there is no firewall blocking connection to O365

Tls1.2 is enabled also

**Comment by dariomws** [comment]
@sarollins, thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
