### ISSUE TITLE
Incorrect information about AutomateProcessing parameter values

### ISSUE THREAD

**Issue by Jones-Bones** [MicrosoftDocs/office-docs-powershell#8956]
AutomateProcessing  parameter explanation has a small mistake where AutoUpdate and AutoAccept explanations are flipped around.

From earlier documentation:

> The AutomateProcessing parameter enables or disables calendar processing on the mailbox. Valid values are:
>
>- None: Calendar processing is disabled on the mailbox. Both the resource booking attendant and the Calendar Attendant are disabled on the mailbox.
> - AutoUpdate: Only the Calendar Attendant processes meeting requests and responses. Meeting requests are tentative in the calendar until they're approved by a delegate. Meeting organizers receive only decisions from delegates.
> - AutoAccept: Both the Calendar Attendant and resource booking attendant are enabled on the mailbox. This means that the Calendar Attendant updates the calendar, and then the resource booking assistant accepts the meeting based upon the policies. Eligible meeting organizers receive the decision directly without human intervention (free = accept; busy = decline).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d95eb528-ab96-b415-981c-35d50c90dba0
* Version Independent ID: 0433f43b-538d-8000-a11d-69b4a5c97e0e
* Content: [Set-CalendarProcessing (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-calendarprocessing?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-CalendarProcessing.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-CalendarProcessing.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Jones-Bones, the current (wrong?) descriptions were based on a recent update:

<https://github.com/MicrosoftDocs/office-docs-powershell/pull/8842>

That update was based on Exchange 2016/2019 behavior.

Comments?

**Comment by chrisda** [comment]
@Jones-Bones, FWIW, I switched the descriptions back as you described; they had been that way for years and years before the recent change, including being blogged about by other people. I can't believe that they've been incorrect for all this time, which is why I changed them back.

Thanks for the feedback.

Closing
