### ISSUE TITLE
Get the Phone Number Type of assigned phone numbers

### ISSUE THREAD

**Issue by vincentkurmi** [MicrosoftDocs/office-docs-powershell#8959]
Hi, 

Regarding the attribute "PhoneNumberType". 
"The type of phone number to assign to the user or resource account. The supported values are DirectRouting, CallingPlan and OperatorConnect."

We can define the type when we set the phone number, that's pretty clear for that point. But do we have a way to get the info of an existing user? I mean, how do we know the type of phone numbers already assigned? 

Thanks in advance for your help. 

Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@vincentkurmi Thanks for the feedback. In the Teams admin center you can see the phone number type if you go to Users -> Manage users -> User details and look under Account.

**Comment by vincentkurmi** [comment]
Thanks for the prompt answer, but we don't use the admin center. No way to get it through PowerShell?

**Comment by JensTrier** [comment]
Not currently as far as I know

**Comment by vincentkurmi** [comment]
Ok we will try a way to keep the info. Thanks.
