### ISSUE TITLE
Microsoft Teams PowerShell Version 3.1.1 Get-CsOnlineUser Fails if user has apostrophe in UPN

### ISSUE THREAD

**Issue by GarmanK** [MicrosoftDocs/office-docs-powershell#8962]
Microsoft Teams PowerShell Version 3.1.1 Get-CsOnlineUser Fails if user has apostrophe in UPN

I couldn't get the text to format correctly here, so please see the screenshot. 
![image](https://user-images.githubusercontent.com/98784624/154096557-32669679-0955-40e3-ac30-89e634c02622.png)

**Comment by isrumnon** [comment]
Hi @GarmanK we're tracking this bug here [Bug 2761898] and will get the fix deployed by the end of this week

**Comment by dariomws** [comment]
Hi @isrumnon,

I've tested it and I have the same problem here. In addition, using the display name is not working for me in 3.1.1:
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/33589238/154910834-5f10de15-7bb2-4364-b057-0b6704955949.png">

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
@isrumnon, could you deploy the fix for this issue? Thanks!

**Comment by isrumnon** [comment]
Hi @GarmanK @dariomws this fix has been rolled out. Please do confirm.

**Comment by dariomws** [comment]
Thanks, @isrumnon. If the user has an apostrophe in UPN, it's working for me now. But I cannot use the Display Name yet.

**Comment by isrumnon** [comment]
@dariomws Using the "-identity" parameter now only allows Guid/SIP address/UPN. Alias and Display Name have been dropped.

**Comment by dariomws** [comment]
@isrumnon, I'll update the article.

**Comment by dariomws** [comment]
@isrumnon, I see it's updated. Thanks!

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution. @GarmanK Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
