### ISSUE TITLE
Minor edit/update to URL anchor

### ISSUE THREAD

**Issue by tu-n-tran** [MicrosoftDocs/office-docs-powershell#8963]
Hi on this page there are three examples and they're numbered 1,2, 1. I believe it's supposed to be 1,2,3. I came across this as I'm trying to provide a URL to the 3rd example but since it's labeled 1, the URL/anchor refers it back to the first. I just thought I'd bring it to your attention. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d467ff3f-e206-3e0f-d3e1-87f79c03ba20
* Version Independent ID: a0592470-94b5-fd12-ca80-85763c181329
* Content: [Enable-App (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/enable-app?view=exchange-ps#example-1)
* Content Source: [exchange/exchange-ps/exchange/Enable-App.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Enable-App.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@tu-n-tran, fixed.

In the future, you too can make changes like this yourself. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md>.

Thanks for the feedback.

Closing

**Comment by tu-n-tran** [comment]
Oh that’s good to know. I’ll do that!

Tu Tran
ITIL Managing Professional, CISSP, Prosci®, Security+ CE
(858) 909-3977 | ***@***.***
Microsoft
________________________________
