### ISSUE TITLE
Missing and/or wrong information on the Get-CsOnlineUser page

### ISSUE THREAD

**Issue by vlethiec** [MicrosoftDocs/office-docs-powershell#8973]
Hi all, 

I started to study the new module 3.1.1 compared to the module 2.6.0. 
I found some issues in the documentation.

# Attributes renamed/replaced

- The "Enabled" attribute has been renamed "AccountEnabled". 
- The "ProxyAddresses" attribute has been renamed "ProxyAddress", and only contain SMTP values
- The "ShadowProxyAddresses" attribute has been renamed "ShadowProxyAddress"
- The "OnPremSIPEnabled" has not been renamed. 

# Deprecated Attributes

I didn't find the following attributes:
- OnPremDomainName
- OnPremisesUserPrincipalName
- OnPremSamAccountName
- OnPremSecurityIdentifier
- RemoteMachine

The following attributes are not mentioned as deprecated but not available in 3.1.1

- ApplicationAccessPolicy                
- ObjectId
- OnPremHostingProvider
- OnPremLineURIManuallySet
- TeamsCarrierEmergencyCallRoutingPolicy
- TeamsEnhancedEncryptionPolicy
- TeamsFilesPolicy
- TeamsNetworkRoamingPolicy

Identity is mentioned deprecated but still available and ObjectId not deprecated but no more available. I think there is problem.
The format "edea4d46-2692-427c-8df6-38262acafecd" cannot disappear that's the key. 

# New User Attributes

- A new attribute is missing "IsSipEnabled"

# Other topics

- The "HostedVoiceMail" attribute is mentioned twice. 
- The "WindowsEmailAddress" is associated with a '*' does it mean something?

And finally, something really strange, we don't have the same attributes when we target one user or the full list. 

![image](https://user-images.githubusercontent.com/52075388/154510107-8f67be70-bfb0-40e3-8a08-373275c55bd8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by vincentkurmi** [comment]
We also find some impacts on existing attributes: 
- The SIP prefix has been removed from "SipAddress" and "SipProxyAddress"
- The DialPlan and LocationPolicy are now empty

It could be great to have a note on these points.

**Comment by vincentkurmi** [comment]
The next commit clarifies the major points, thanks for that. 
https://github.com/isrumnon/office-docs-powershell-new/commit/2bebf4de4882c901c0605647c7b7d6d39ec8d8f5

**Comment by vincentkurmi** [comment]
Hi @isrumnon, 

Can you help me to understand this comment? 
![image](https://user-images.githubusercontent.com/52075388/155288077-c4456c44-752f-40b7-adc1-3a904d860d60.png)
Source: https://github.com/MicrosoftDocs/office-docs-powershell/issues/8960

It means the differences between a single query and bulk queries, as described below, is targeted  to be fixed for end of march?
![image](https://user-images.githubusercontent.com/52075388/155288488-6591e289-db97-48af-9f29-14af13ab809b.png)

Thanks in advance for the help.

**Comment by isrumnon** [comment]
Hi @vincentkurmi yes that is correct - while we have modernized the point queries, the bulk queries are slightly lagging behind and is targeted to be completed by the end of March by which the results should be consistent across both point and bulk queries

**Comment by vlethiec** [comment]
Can be closed with the latest version of the page.
