### ISSUE TITLE
Teams PowerShell Module 3.1.1 - Get-CsOnlineDialInConferencingUser empty result

### ISSUE THREAD

**Issue by andreprakash** [MicrosoftDocs/office-docs-powershell#8974]
The command `Get-CsOnlineDialInConferencingUser -identity userprincipalname` gives back an empty result. 
If using the command without any identity (`Get-CsOnlineDialInConferencingUser`) a list of all users is returned correctly but take a long time to read out all the users settings.

If adding "-force" to the command it works as expected (`Get-CsOnlineDialInConferencingUser -identity userprincipalname -force `), even though the documentation says the -force option is deprecated.

I only tested it with Teams PowerShell Module 3.1.1

**Comment by amonzerol** [comment]
Same thing is happening on my side.

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
Hi @andreprakash and @amonzerol, thank you for your feeback.

Could you kindly test it again with the 4.0 module version?

**Comment by amonzerol** [comment]
It works on my end, thank you !

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @amonzerol Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
