### ISSUE TITLE
Grant-CsTeamsMeetingPolicy fails on disabled user

### ISSUE THREAD

**Issue by eblingus** [MicrosoftDocs/office-docs-powershell#8975]
Get-csonlineuser for disabled user works just fine.
Grant-CsTeamsMeetingPolicy for same user fails with 'Management object not found' error.
This creates a situation where a disabled user (which I can't delete because of company policy)  prevents me from removing assigned Teams policies, which means I can no longer delete those policies.  It's a minor use case, but still very annoying.

**Comment by gcouper** [comment]
I am getting a similar thing with Set-csuser

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
Hi @eblingus and @gcouper, thank you for your feedback.

Are you talking about disabled accounts synchronized via Azure AD Connect or inactive mailboxes?

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and digging deep into it.  @eblingus We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
