### ISSUE TITLE
Possible bug when using Get-TeamChannelUser with a -DisplayName that includes a hyphen 

### ISSUE THREAD

**Issue by eleighty** [MicrosoftDocs/office-docs-powershell#8981]
When attempting to automate the populating of our Teams channels, it was discovered that if the -DisplayName includes a hyphen in it, PowerShell encounters an error (see attached image). We tested the same script on numerous other Teams channels, the only ones coming back with this error were the ones with hyphens in the display name

![Get-TeamChannelUser Error](https://user-images.githubusercontent.com/99033438/154742060-71bc4877-7d5f-4fb3-8173-c3a0630d5922.png)
.

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
Hi @eleighty, thank you for your feedback.

I confirm this error. I want to check if this cmdlet is still in preview, please check the note in the description. I'll try to confirm it.

**Comment by eleighty** [comment]
Afternoon Dario!

Thank you for looking into this, yes, it is a part of the Public Preview for Microsoft Teams.

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
@eleighty @yogkumgit, I'm waiting for confirmation here. Sorry for the delay.

**Comment by eleighty** [comment]
@dariomws thanks for the update!

**Comment by yogkumgit** [comment]
@dariomws

**Comment by yogkumgit** [comment]
@pbafna03 @dariomws Kindly address this issue. Thanks

**Comment by yogkumgit** [comment]
@dariomws Please comment. Thanks

**Comment by dariomws** [comment]
@yogkumgit, this was fixed in a previous release. We can close this issue.

![image](https://user-images.githubusercontent.com/33589238/178488072-55c16470-67ec-4a0b-bf7b-62f6dd854477.png)
