### ISSUE TITLE
Set-CsOnlineApplicationInstance deprecated - what about switch ApplicationId?

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#8986]
Hello,

I am using `Set-CsOnlineApplicationInstance` in a [script of mine](https://github.com/DEberhardt/TeamsFunctions/blob/main/docs/New-TeamsResourceAccountAssociation.md) to validate the Application Type and, if used with `-Force` also change it, which (may not be recommended but does work well):

```powershell
# Changing Application Type
try {
  $null = Set-CsOnlineApplicationInstance -Identity $Account.ObjectId -ApplicationId $(GetAppIdFromApplicationType $DesiredType) -ErrorAction Stop
}
catch {
  Write-Error -Message "'$($Account.UserPrincipalName)' - Application type does not match and could not be changed! Expected: '$DesiredType' - Please change manually or recreate the Account" -Category InvalidType -RecommendedAction 'Please change manually or recreate the Account'
  continue
}
```

Considering that the CmdLet is now deprecated, what does this mean for this use case?
Do Resource Accounts now always require recreation?

Thank you,
David

PS: Same question for changing the DisplayName of a Resource Account

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc6081b-f6d4-f2c3-b12e-5f4df83c31e6
* Version Independent ID: 5cf5edef-643f-10a1-8247-4e14d06ff675
* Content: [Set-CsOnlineApplicationInstance (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlineapplicationinstance?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by DEberhardt** [comment]
From `Set-CsOnlineVoiceUser`

> Note: This cmdlet will be deprecated and no longer supports the ability to add extensions to telephone numbers (for example, "tel:+61281234567;ext=5110"). Use the new [Set-CsPhoneNumberAssignment](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment) cmdlet instead.

Should the message be clarified here?

**Comment by JensTrier** [comment]
@DEberhardt thanks for the feedback on the use case of changing resource account type using Set-CsOnlineApplicationInstance cmdlet. Let me research this and get back.

**Comment by yogkumgit** [comment]
PR #9036

**Comment by yogkumgit** [comment]
@DEberhardt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
