### ISSUE TITLE
"-CompleteAfter" option is not available in on-premises Exchange.

### ISSUE THREAD

**Issue by j-ky7** [MicrosoftDocs/office-docs-powershell#8987]
Following this page, "-CompleteAfter" cmdlet option is available for on-premises Exchange.
Actually, this option is available only in the cloud-based service(Exchange Online).
In past, the below history clearly stated that this option is not supported in on-premises.

https://github.com/MicrosoftDocs/office-docs-powershell/blob/12d1a002d2a6789a0d08ce0f105375e20b35b577/exchange/exchange-ps/exchange/New-MigrationBatch.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c40dcb69-e0ef-375b-db4f-c42bd2f684d2
* Version Independent ID: 30d2b295-a394-e801-0f72-87b6257a13a0
* Content: [Set-MigrationBatch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@j-ky7, availability vs. functionality are two different things. I just checked on my Exchange 2019 CU11 and 2016 CU22 test servers (Exchange 2013 CU23 server wasn't working), and the CompleteAfter parameter is 100% available on Set-MigrationBatch. Whether it's supposed to be, or whether it actually works is a different story.

The "Applicable:" values for the parameter show availability without any concern for functionality. The parameter description (words/sentences) describe availability in cases where functionality and availability don't align.

So, it sounds like I need to add the following note to the parameter description:

> This parameter is available or functional only in the cloud-based service.

And I presume this issue also affects the CompleteAfter parameter on New-MigrationBatch?

**Comment by j-ky7** [comment]
@chrisda , thank you for your comment. 
I totally agree with the below suggestion. The issue is also applied to New-MigrationBatch cmdlet.

-----
So, it sounds like I need to add the following note to the parameter description:

>>This parameter is available or functional only in the cloud-based service.

And I presume this issue also affects the CompleteAfter parameter on New-MigrationBatch?
