### ISSUE TITLE
Set-CsPhoneNumberAssignment: Request Error, Status: NotFound

### ISSUE THREAD

**Issue by DMoenks** [MicrosoftDocs/office-docs-powershell#8989]
In accordance to Microsoft's announcement to retire some Skype/Teams cmdlets for phone configuration sometime in April 2022, we started testing the soon-to-be-used cmdlets, but encountered similar errors as mentioned in #8875. The affected user account is licensed and can be retrieved by its SIP address with other cmdlets successfully, e.g. _Get-CsOnlineUser_ or _Get-CsOnlineVoiceUser_.
Differing from the linked issue, we can't find any typos in the cmdlet's parameter values. In addition, calling the same cmdlet with another SIP address, but keeping other parameter values, works as expected.

The affected user account was licensed for about half an hour on the first try and about two hours on the last try, which usually provided enough time between licensing and follow-up when using the _Set-CsUser_ cmdlet.

```powershell
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNumberAssignment : The server responded with a Request Error, Status: NotFound
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.1.1\net472\custom\PsExt\Set-CsPhoneNumberAssignment.ps1:41 char:9
+         Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNumberA ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = wa...iceEnabled =  }:<>f__AnonymousType82`5) [Set-CsPhoneNumberAssignment_Set], UndeclaredResponseException
    + FullyQualifiedErrorId : NotFound,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsPhoneNumberAssignment_Set
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@DMoenks thanks for the feedback. Please send me the actual failing cmdlet with the user and the parameters offline at jens.trier AT microsoft.com and I'll have a look.

**Comment by DMoenks** [comment]
@JensTrier
Details were provided by email, in addition to results from running _Get-CsOnlineVoiceUser_ for the same user account for comparison

**Comment by DMoenks** [comment]
The source of the error was identified in system traces after providing additional details and is currently being investigated. As this error message only occurs semi-sporadically, the issue is closed.

**Comment by tbakrf** [comment]
I am having this issue now as well - this was working just 2 weeks ago. 
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNumberAssignment : The server responded with a Request Error,
Status: NotFound
At C:\Program
Files\WindowsPowerShell\Modules\MicrosoftTeams\3.1.1\net472\custom\PsExt\Set-CsPhoneNumberAssignment.ps1:41 char:9
+         Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNumberA ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = te...iceEnabled =  }:<>f__AnonymousType82`5) [Set-CsPhon
   eNumberAssignment_Set], UndeclaredResponseException
    + FullyQualifiedErrorId : NotFound,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsPhoneNumberAssignment_
   Set
