### ISSUE TITLE
Set-CsPhoneNumberAssignment - BadRequest Service is unavailable. Please try again

### ISSUE THREAD

**Issue by olanga** [MicrosoftDocs/office-docs-powershell#8992]
We are running PS MicrosoftTeams 3.1.1 and recently started using Set-CsPhoneNumberAssignment.
Very often we face error  "Service is unavailable". Any idea where is it coming from?

```
Set-CsPhoneNumberAssignment -Identity $UPN -PhoneNumber +49123456789 -PhoneNumberType DirectRouting

Code            Message                                                         
------          --------------
BadRequest      Service is unavailable. Please try again
```

**Comment by ckarawani** [comment]
Seeing similar performance issues with `3.1.1` with performing queries using filters.

**Comment by olanga** [comment]
After many more tests it looks like "Service is unavailable" problem is user specific.
I have now 2 users where Set-CsPhoneNumberAssignment always fails. These users are on Teams for months, had phone numbers assigned before and have phone license assigned.
Also "Remove-CsPhoneNumberAssignment -Identity $UPN -RemoveAll" fails for these users.

**Comment by JensTrier** [comment]
@olanga thanks for the feedback. Please send me the details offline at jens.trier AT microsoft.com and I'll have a look what's going on with these users.

**Comment by olanga** [comment]
Additional information. "Old" command still work for 2 users where Set-CsPhoneNumberAssignment fails
Set-CsUser -Identity $UPN -OnPremLineURI tel:+49123456789
Set-CsUser -Identity $UPN -LineURI tel:+49123456789

**Comment by ElazarOhayon** [comment]
Teams module 3.1.1 new Resource account + virtual user the same issue.


BadRequest Update failed for user.....

**Comment by JensTrier** [comment]
@ElazarOhayon feel free to send me the details offline, but if it is a new resource account you might need to wait a bit before trying to assign the phone number

**Comment by Volker1211** [comment]
I'm currently experiencing this issue in Module 4.0.0, too. Is there any news on this?

**Comment by JensTrier** [comment]
@Volker1211 Thanks for the feedback. The recommended approach is to open a Microsoft support case and they will work with you to root cause what is going on.

**Comment by olanga** [comment]
The issue has been resolved by Microsoft support. 
Apparently it was due to duplicate BVD values for our users.

**Comment by ckarawani** [comment]
hello @olanga what does BVD stand for?

**Comment by JensTrier** [comment]
@olanga thanks for update. Please feel free to close the issue

**Comment by olanga** [comment]
Business Voice Directory
The only information I found was below article in German:
https://www.msxfaq.de/teams/pbx/bvd_business_voice_directory.htm

**Comment by olanga** [comment]
closing...
