### ISSUE TITLE
Sporadic Timeouts/Errors when getting running Cmdlets (Sometimes returning MI_RESULT_FAILED)

### ISSUE THREAD

**Issue by ckarawani** [MicrosoftDocs/office-docs-powershell#8994]
Something as simple as running:

`Get-CsOnlineUser -ResultSize 1 | Select Identity` will sometimes hang or eventually fail with the message:

`Processing data for a remote command failed with the following error message: MI_RESULT_FAILED For more information, see the about_Remote_Troubleshooting Help topic.`

This happens more often with `2.3.1` but happens a lot with the use of filters in 3.x

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
Hi @ckarawani, thank you for your feedback.

If you are still experiencing this issue with version 4.0 of the Teams PowerShell Module, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @ckarawani Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ckarawani** [comment]
thanks @yogkumgit and @dariomws for your feedback. The folks who support 365 don't really provide much support / response times for Powershell Modules. So far this issue has been quite transient, so I'll keep an eye out for it. 

As it stands it no longer occurs on any version. So you may close and I can reference this if it happens in the future and perhaps we can add a note to the doc.
