### ISSUE TITLE
How to set "Notes"?

### ISSUE THREAD

**Issue by gable44** [MicrosoftDocs/office-docs-powershell#8995]
How to set notes with Set-DistributionGroup?

With the New-DistributionGroup cmd you can set notes.

https://docs.microsoft.com/powershell/module/exchange/new-distributiongroup

> ### - Notes
>
> The Notes parameters specifies additional information about the object. If the value contains spaces, enclose the value in quotation marks (").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42e2373d-198f-dba7-285c-66a2a5f384c4
* Version Independent ID: 3329c2f3-bf2d-111a-02dc-ce6d52d8164f
* Content: [Set-DistributionGroup (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-distributiongroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-DistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-DistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gable44, have you tried using the Set-Group cmdlet? That has a Notes parameter. Just be sure to use a non-email property to identify the group with Set-Group (for example, don't use Alias or EmailAddress; use Name or UserPrincipalName).

**Comment by gable44** [comment]
@chrisda Yes, thank you but I taught its a workaround :)

**Comment by chrisda** [comment]
@gable44, well, if it works, it works. It could be that the Exchange admin center calls that Set-Group cmdlet to do its thing. Often, multiple different cmdlet calls are used to do what appears to be a seamless, single operation in the UI.

**Comment by chrisda** [comment]
Solution achieved.

Thanks for the feedback.

Closing
