### ISSUE TITLE
Confusing Verbiage for Recent Unified Group Notice

### ISSUE THREAD

**Issue by CATgwalker** [MicrosoftDocs/office-docs-powershell#9002]
This verbiage is confusing and unclear for people that are not familiar with 'contexts'. I suggest clarifying the messaging to refer to "service principal authentication", "certificate based authentication", or "App-only authentication for unattended scripts"  as it is referenced in the Exchange Online release notes for 2.0.3. 

There also doesn't seem to be a correlating way to remove users from groups via Microsoft Graph Powershell. It would be more helpful for the link to point to documentation on how to accomplish what the referring page does albeit through Microsoft Graph, rather than dumping to a generic overview page for Microsoft Groups.

> **Note**: Remove-UnifiedGroupLinks is not supported under the ApplicationID context. Instead of this cmdlet, we recommend using Microsoft Graph to create Microsoft 365 groups in that context. For more information, see [Overview of Microsoft 365 groups in Microsoft Graph](https://docs.microsoft.com/graph/office365-groups-concept-overview).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c927c29-65b9-2633-4d44-7a73e052efc4
* Version Independent ID: cdc7b8b3-daf4-3e34-8dce-615128a25904
* Content: [Remove-UnifiedGroupLinks (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-unifiedgrouplinks?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-UnifiedGroupLinks.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Remove-UnifiedGroupLinks.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@CATgwalker, OK. Fixed. If you don't like the topic links that I used, feel free to add/remove/modify directly. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
