### ISSUE TITLE
Verify your code

### ISSUE THREAD

**Issue by ahammadah** [MicrosoftDocs/office-docs-powershell#901]
I quoted your code in the second Example above and embedded the part: -Permanent $true in one of my commands, and it kept throwing an error till I figured out it should be -Permanent:$true
I should've not blindly copy pasted the code from here..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c2fcd6e-73de-a00c-0296-5dbad6541977
* Version Independent ID: 4303e5b7-a703-daa4-a747-6ac202460c9f
* Content: [Remove-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/remove-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Remove-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Remove-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nsshommo** [comment]
@ahammadah Thanks for letting us know. We are working to update this example.

@chrisda Can you please check Example 2?

**Comment by chrisda** [comment]
@ahammadah, @nsshommo, I confirmed that the Permanent parameter on Remove-Mailbox is, in fact, Boolean ($true or $false) as described. I tested a command on a 2010 and 2016 server that contained "-Permanent $true" and "-Permanent $false" and they both worked without error for me.

Are you using the command as part of a script or reading a value from a text or CSV file? I found [this issue](https://social.technet.microsoft.com/Forums/sharepoint/en-US/d077c19f-9aac-4845-82f0-6e4cdfd5f837/using-boolean-properties-with-newaduser-and-importcsv?forum=winserverpowershell) for a completely unrelated cmdlet that required something other than the default syntax for a Boolean parameter value to work correctly.

In Exchange PowerShell, the only parameters that routinely require the colon (:) between the parameter name and value are switch parameters (for example -Confirm:$false).

**Comment by kenwith** [comment]
@nsshommo - this is really great info from @chrisda. Would you capture it in a PR to the Notes section of the cmdlet and ask Chris to review. This would be a great use case for open source and transparent system really improving the experience.
