### ISSUE TITLE
Linux Pwsh 7.X.X / MS 2.6.0 Import-CsOnlineAudioFile freezes

### ISSUE THREAD

**Issue by felixfafard** [MicrosoftDocs/office-docs-powershell#9014]
Since 18-02-2022, the "Import-CsOnlineAudioFile" command with Powershell on Linux and MicrosofTeams Module version 2.6.0 does not work.

It freezes indefinitely after Import-CsOnlineAudioFile. It does work on Windows with the same Powershell and module version  (7.2.1 & 2.6.0).

This was tested on different machines and different Microsoft 365 tenants. 

Is anyone else experiencing this issue? I contacted the Microsoft support, but they simply stated that Powershell on Linux was not "supported".

**Steps to reproduce**
Env.: 
- Linux (tested on Centos 7)
- PowerShell 7.2.1
- Microsoft Teams module 2.6.0

```
Import-module MicrosoftTeams -RequiredVersion 2.6.0
$password = ConvertTo-SecureString "<password>" -AsPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential("<username>", $password )
Connect-MicrosoftTeams -Credential $cred

$GetContent = Get-Content -Raw  -Path "<path-to-audio-file>" -AsByteStream
$ImportCsOnlineAudioFile = Import-CsOnlineAudioFile -FileName "<filename>" -Content $GetContent -ApplicationId "HuntGroup" -Verbose
```

**Comment by dariomws** [comment]
Hi @felixfafard, thank you for your feedback.

Here we are limited to documentation issues and improvements. Anyway, I can recommend you to try the latest version of the Teams PowerShell module:
https://www.powershellgallery.com/packages/MicrosoftTeams/3.1.1

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @felixfafard Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
