### ISSUE TITLE
character "&" in "Alias" attribute is not supported via AAD Connect.

### ISSUE THREAD

**Issue by joibarr** [MicrosoftDocs/office-docs-powershell#9020]
This document states that "&" character is supported in the "Alias" attribute to be synced from AAD Connect to EXO. However, in a current scenario with a customer, the "&" is being changed for an underscore character. After discussing this topic with Nuno Alexandre MSODS Beta Engineer, our AdminWebService via Proxy Calc will always change this unsupported characters for an underscore . 
This public document is not consistent with what our service does. 
You can contact me if something is required - joibarr@microsoft.com
I'm attaching the screen shot from our Proxy Calculation.cs to provide more clarity.
![Captura de ecrã 2022-02-28 111445](https://user-images.githubusercontent.com/72282326/155974308-9d251b2e-9188-4fee-b457-1f52260d97bf.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f835af-5905-368a-df68-6646782ad807
* Version Independent ID: 153ce2d2-dab5-9c8f-c511-ee3bc8ee2dbc
* Content: [Set-Mailbox (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Discussed via email and updated Alias parameter accordingly. The & character is supported in the Alias value as described, but bad things happen in Azure AD Connect synchronization if the Alias value contains an &.

Thanks for the feedback.

Closing
