### ISSUE TITLE
FeatureTypes attribute

### ISSUE THREAD

**Issue by Cristina-Cajal** [MicrosoftDocs/office-docs-powershell#9021]
Hello,

I'm checking a Microsoft Teams user with Office 365 E3 and Standard Microsoft Teams Phone System licenses assigned but unable to dial phone numbers (he gets a license issue message), whose FeatureTypes attribute is null.
I see other users whose Feature Types attribute is {PhoneSystem, Teams}, and they are able to dial phone numbers.

Can FeatureTypes attribute be modified directly through Powershell, to set is as {PhoneSystem, Teams} (which command?)? Or it should be modified anywhere else inside Microsoft and it's just showed here, and I'm missing it?

Same problem with DialPlan attribute (it is null for the non-working user).

Thanks and regards,
Cristina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by dariomws** [comment]
Hi @Cristina-Cajal, thank you for your feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @Cristina-Cajal Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
