### ISSUE TITLE
-AllowedFileTypes Parameter has no effect

### ISSUE THREAD

**Issue by Richard-Tang** [MicrosoftDocs/office-docs-powershell#9028]
I set up a test Exchange server that, when receiving an email with an outreach image, would say "something in this email has been blocked to protect your privacy. To re-enable blocking, click here."

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/30547741/156097236-208428b0-6dc1-45a1-a295-acdfe4fbf691.png">

I found the relevant problem document in Microsoft Documentation:https://social.microsoft.com/Forums/zh-CN/a6cb5218-0f57-4358-af3b-2a7e066fbb3d/20026201022044525252203203034038544311696529224050384592749027?forum=exchangeserverzhchs

I made changes to PowerShell with new documentation, but nothing worked.

```powershell
Set-OwaMailnboxPolicy -Identity Default -WebReadyFileType ".png"
```

<img width="605" alt="image" src="https://user-images.githubusercontent.com/30547741/156097442-940b21f7-882a-4e71-8935-0df8de6175fc.png">

When I set it up like this, it still says "Something in this email has been blocked to protect your privacy. To re-enable blocking, click here."

Maybe the documentation is wrong?

exchange version:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/30547741/156097811-65945b29-2c7c-4e94-8a7f-688564a338cf.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022da80e-29cd-f6b5-aa00-48e2d16c4be8
* Version Independent ID: c3353c03-e416-f693-104f-6b6f5955b721
* Content: [Set-OwaMailboxPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Richard-Tang, you should open a support case.
