### ISSUE TITLE
ExchangePowershell in PowerShell Gallery

### ISSUE THREAD

**Issue by JohnLBevan** [MicrosoftDocs/office-docs-powershell#9029]
There's a module called ExchangePowershell in the PS Gallery: https://www.powershellgallery.com/packages/ExchangePowerShell
That module is a non-MS solution, but happens to use the same name.
I suspect a lot of people download that by mistake when trying to work with the module documented here; especially as the MS version of this module is often referred to by a different name (Exchange Management Shell).
It may be worth adding a link to "how to install" this module and putting a note regarding the non-MS module to help avoid such confusion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18e37f04-f815-b82b-2cbd-910424c4a721
* Version Independent ID: 5a8f45ca-3d30-7fe6-cca3-0297f300dced
* Content: [ExchangePowerShell Module](https://docs.microsoft.com/en-us/powershell/module/exchange/?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/exchange.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/exchange.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JohnLBevan, that sounds reasonable to me. I added a call-outs in:

- <https://docs.microsoft.com/powershell/module/exchange/>
- <https://docs.microsoft.com/powershell/exchange/exchange-management-shell>

Thanks for the feedback.

Closing
