### ISSUE TITLE
Preview Flag Removed

### ISSUE THREAD

**Issue by NHawk257** [MicrosoftDocs/office-docs-powershell#9031]
The _-Preview_ flag has been removed from this command. It is removed in some spots in the document but not all and still shows up in an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad8adee-7f9d-757b-2069-95ecab232747
* Version Independent ID: c71194df-8f65-15aa-3ed2-b370b8c3f629
* Content: [New-ComplianceSearchAction (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearchaction?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@NHawk257, I just tested in my stock E5 tenant, and the Preview switch was available to me on Get-ComplianceSearchAction and New-ComplianceSearchAction. Does this statement from New-ComplianceSearchAction explain what's going on?

> In Security & Compliance Center PowerShell, this parameter requires the Preview role. By default, this role is assigned only to the eDiscovery Manager role group.
