### ISSUE TITLE
What does this do when Teams Only?

### ISSUE THREAD

**Issue by RABurnettMCSE** [MicrosoftDocs/office-docs-powershell#9033]
-AllowCalling fails when in Teams only

**Comment by yogkumgit** [comment]
@RABurnettMCSE Please indicate which document you are referring to and what is your feedback. Thanks

**Comment by dariomws** [comment]
Hi @RABurnettMCSE, thank you for your feedback.

I think you are talking about Set-CsTeamsCallingPolicy. In the article the description of this parameter is:
"Controls interop calling capabilities. Turning this on will allow Skype for Business users to have one-on-one calls with Teams users and vice-versa.

Note: This parameter is disabled."

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @RABurnettMCSE Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
