### ISSUE TITLE
Set-CsUser doesn't throw catchable exceptions in Teams PowerShell module 3.1.1

### ISSUE THREAD

**Issue by DMoenks** [MicrosoftDocs/office-docs-powershell#9037]
As phone number assignment with Set-CsPhoneNumberAssignment still fails in some cases (#8989), we stayed with version 3.1.1 of the module, while still using Set-CsUser. We're receiving "interesting" results when trying to handle exceptions though, e.g. when duplicate or incorrect phone numbers are provided for the cmdlet parameters:

Example 1, partly expected:
```powershell
try {
    Set-CsUser -Identity existing.sip-address@example.com -OnPremLineURI "tel:+4912345" -EnterpriseVoiceEnabled $true
}
catch {
    'Error!'
}

Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsUserGenerated : 4912345 is assigned to another user
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.1.1\net472\custom\PsExt\Set-CsUserModern.ps1:51 char:13
+             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsUserGene ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = Sara...onaryOfString }:<>f__AnonymousType86`2) [Set-CsUserGenerated_Set], Exception
    + FullyQualifiedErrorId : BadArgument,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsUserGenerated_Set
```

Example 2, not expected:
```powershell
try {
    Set-CsUser -Identity existing.sip-address@example.com -OnPremLineURI "tel:+4912345" -EnterpriseVoiceEnabled $true -ErrorAction Stop
}
catch {
    'Error!'
}

Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsUserGenerated : 4912345 is assigned to another user
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.1.1\net472\custom\PsExt\Set-CsUserModern.ps1:51 char:13
+             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsUserGene ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = Sara...onaryOfString }:<>f__AnonymousType86`2) [Set-CsUserGenerated_Set], Exception
    + FullyQualifiedErrorId : BadArgument,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsUserGenerated_Set
```

Example 3, totally not expected:
```powershell
try {
    Set-CsUser -Identity existing.sip-address@example.com -OnPremLineURI "tel:+4912345" -EnterpriseVoiceEnabled $true -ErrorAction Stop -PassThru
}
catch {
    'Error!'
}

Error!
```

Although the last version successfully catches the exception, it ends up in non-configured user accounts even when there are no exceptions:

```powershell
try {
    Set-CsUser -Identity existing.sip-address@example.com -OnPremLineURI "tel:+4967890" -EnterpriseVoiceEnabled $true -ErrorAction Stop -PassThru
}
catch {
    'Error!'
}

Identity                    : CN=2b3de85b-bb49-4a9e-9c90-e89650c1f528,OU=6868843b-f012-4c95-a18e-bab826cca9ac,OU=OCS Tenants,DC=lync2e001,DC=local
VoicePolicy                 : 1
VoiceRoutingPolicy          :
ConferencingPolicy          : 110
PresencePolicy              :
DialPlan                    : 50
LocationPolicy              :
ClientPolicy                :
ClientVersionPolicy         :
ArchivingPolicy             :
ExchangeArchivingPolicy     : Uninitialized
PinPolicy                   :
ExternalAccessPolicy        : 1
MobilityPolicy              : 1
UserServicesPolicy          :
CallViaWorkPolicy           :
ThirdPartyVideoSystemPolicy :
HostedVoiceMail             : False
HostedVoicemailPolicy       : 1
IPPhonePolicy               :
HostingProvider             : sipfed.online.lync.com
RegistrarPool               : 534892446
Enabled                     : True
SipAddress                  : SIP:existing.sip-address@example.com
LineURI                     : tel:+4967890
EnterpriseVoiceEnabled      : True
ExUmEnabled                 : False
HomeServer                  :
DisplayName                 : <redacted for privacy>
SamAccountName              : <redacted for privacy>
```
For clarification: Although the last attempt _seems_ successful, the user account is not configured at all afterwards. Removing the error handling parameters allows for successful configuration, causing problems in case of errors again though.

If the "issue" is caused by lacking PowerShell knowledge, please let me know and feel free to close it. I'm pretty sure that exception handling worked as expected in version 2.3.1 of the module though.

**EDIT:**

* Updated the examples for clarification

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76cebc8c-7403-8981-a993-ed1079eb513c
* Version Independent ID: 015533c1-6a15-3dc1-083d-3370bdc3915d
* Content: [Set-CsUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by Briggidy** [comment]
I'm also not able to catch the exception with Get-CsOnlineUser either.  please let me know if I need to open a new issue.

Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get-CsUser : userId was not found
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.1.1\net472\custom\PsExt\Get-CsUserList.ps1:39 char:13
+             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get-CsUser -Id ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = a5...olicy = False }:<>f__AnonymousType53`6) [Get-CsUser
   _Get], Exception
    + FullyQualifiedErrorId : NotFound,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsUser_Get

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
Hi @DMoenks and @Briggidy, thank you for your feedback.

Could you kindly try again with the 4.0 version module?

@DMoenks, please use Set-CsPhoneNumberAssignment instead of Set-CsUser.

Thanks!

**Comment by DMoenks** [comment]
I can't recognize any difference with version 4.0.0 of the module, the examples provided above still apply.

Even though _Set-CsPhoneNumberAssignment_ would be the cmdlet to use in the very near future, our production scripts aren't yet able to handle its "exceptions", as they're technically no _Exception_ objects, but rather _SkypeTelephoneNumberMgmtErrorResponse_ objects. This is fine by itself, but obviously needs adopted handling and is a different topic.

While we update our scripts to work with _Set-CsPhoneNumberAssignment_, our production scripts using _Set-CsUser_ broke due to recent changes, leaving us with the short-hand decision to either handle multiple module versions on our admin workstations or roll back to an older version for some admins.
None of the latter is a code issue, it's rather an organizational issue, that's true, but personally I haven't encountered such a case in years.

I very much understand, support and even welcome deprecating previous methods while providing new methods. but changing previous methods to this extent honestly caught me off guard, especially as it's no preview version but a release version of the module.

**Comment by Briggidy** [comment]
@dariomws it's still not working in 4.0.0. for me either.  

I had to downgrade another machine to 2.6.0 to get something else working and can confirm it's working as expected in 2.6.0

Here is the error:

<code>Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get-CsUser : userId was not found</code>
<code>At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.0.0\net472\custom\PsExt\Merged_custom_PsExt.ps1:1836 char:13</code>
<code>+             $user = Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get-Cs ...</code>
<code>+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</code>
<code>    + CategoryInfo          : InvalidOperation: ({ Identity = fi...et = Extended }:<>f__AnonymousType58`7) [Get-CsUser_Get], Exception</code>
<code>    + FullyQualifiedErrorId : NotFound,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsUser_Get</code

**Comment by dariomws** [comment]
Thanks for your feedback guys.

To be honest, I'm trying to help here, but we are limited to documentation improvements. If there is something that I can do for you in docs let me know.
If you need more support, you should use standard support channels.

My apologies and I hope you understand.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @DMoenks Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DMoenks** [comment]
@yogkumgit, @dariomws 
Thanks for the hint, I honestly didn't even consider that when I followed a _Submit feedback for this product_ link in the documentation. In my mind, the "product" referred to by the link was the Teams PowerShell module, not the documentation itself.
I will turn to standard Microsoft support channels for issue resolution, as advised. Therefore, I consider this GitHub issue as closed on my end as well.

**Comment by DMoenks** [comment]
Closed after unintended reopening
