### ISSUE TITLE
Update Example 1

### ISSUE THREAD

**Issue by HTEredrock** [MicrosoftDocs/office-docs-powershell#904]
Example should read `Add-PnPTenantCdnOrigin -OriginUrl /sites/site/subfolder -CdnType Public` 
And not `Add-PnPTenantCdnOrigin -Url /sites/site/subfolder -CdnType Public`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3b6781-410b-bdc8-0e8e-fa67a0569cf2
* Version Independent ID: d1abc1ba-6432-79d7-8365-855ad11ea1a7
* Content: [Add-PnPTenantCdnOrigin (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnptenantcdnorigin?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTenantCdnOrigin.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPTenantCdnOrigin.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by VesaJuvonen** [comment]
Will be fixed with the June 2018 content update for PnP cmdlets - thanks @HTEredrock for reporting, appreciated.
