### ISSUE TITLE
What to use instead of depreciated

### ISSUE THREAD

**Issue by Pam-SP** [MicrosoftDocs/office-docs-powershell#9040]
I noticed this parameter is now depreciated in set-team
-ShowInTeamsSearchAndSuggestions
The parameter has been deprecated.

What should be used instead?  I'm noticing really unpredictable behavior in how Teams displays a public Team in the Suggested Teams (under Join or Create a Team).  It is my understanding this is returned by Graph.  I've had some success in the past by PowerShelling a public team from -ShowInTeamsSearchAndSuggestions to $false then back to $true to get it to show up there...but now, that parameter isn't available anymore.  

If anyone has any suggestions, I'd really appreciate it.  Also if you have any further information on how the Team Suggestions works and if there is anyway to help the public teams show up there, that would be amazing.  Thank you.

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
Hi @Pam-SP, thank you for your feedback.

The private Team Discoverability feature was dropped 2 years ago. Public Channels are always discoverable and Private Channels are the opposite.

For different reasons, it's not possible to change from public to private and vice-versa. You can provide your feedback to request this feature here:
https://feedbackportal.microsoft.com/feedback/idea/bba11aa7-a585-ec11-a81b-0022484cf5bc

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @Pam-SP Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Pam-SP** [comment]
Thank you for your answer but I find this to not answer my question.  I don't want to make a Private Team discoverable.  I am changing a Team from private to Public which you can do either through Edit Team in Teams or by Set-Team - <Team Name> -Visibility Public.  I have changed a Team from private to public many times.  

My issue is that once the team is set to Public,  while you can search for that Team and it shows up as expected and discoverable is fine, this Team never automatically shows up in the "Suggested" teams.  The Suggestion part is allegedly coming from Graph and I can only think there is a hidden property that is set when the Team is private that does not get reset when it is switched to public.  I thought it was the -ShowInTeamsSearchAndSuggestions

**Comment by dariomws** [comment]
@Pam-SP, my apologies but I'm not understanding your request.

Here we are limited to documentation issues and improvements. If there is an article where we can help please let me know.

If you are requesting a feature, you could add your voice in the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472.
