### ISSUE TITLE
Example shows EnableSafeLinksForClients but that parameter is not shown.

### ISSUE THREAD

**Issue by markisback** [MicrosoftDocs/office-docs-powershell#9049]
I assume it's legacy and replaced with EnableSafeLinksForO365Clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74c9eaef-98d2-8659-662a-91d0db5cb7bd
* Version Independent ID: 5c52e976-3cd2-b176-008f-37d0c628834e
* Content: [Set-AtpPolicyForO365 (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-atppolicyforo365?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@markisback, fixed. You're right about the wrong parameter being used in the example. The description of the example doesn't talk about Office apps, and the default value EnableSafeLinksForO365Clients is $true, so I just removed the offending parameter from the example. It's now just:

 ```powershell
Set-AtpPolicyForO365 -EnableATPForSPOTeamsODB $true
```

Thanks for the feedback.

Closing
