### ISSUE TITLE
EnableScheduleOwnerPermissions

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/office-docs-powershell#9053]
Missing details about -EnableScheduleOwnerPermissions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d110c7ad-29fb-d612-eaf3-5fec070035f5
* Version Independent ID: e39e22b3-0070-ad6e-df9f-5c7ead508359
* Content: [Set-CsTeamsShiftsPolicy (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftspolicy?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsTeamsShiftsPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsShiftsPolicy.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by yogkumgit** [comment]
@dariomws
