### ISSUE TITLE
Add-SPShellAdmin grants dbo_owner role???

### ISSUE THREAD

**Issue by egor-yudkin** [MicrosoftDocs/office-docs-powershell#906]
In the description section there is the following statement: 
"However, the result of running this cmdlet is that the user specified with the UserName parameter will have the dbo_owner role access on the affected databases as described above. Therefore, you should carefully plan which users are given this access."
I don't think this statement is correct, at least for SharePoint 2013. After running the cmdlet, a user will be added to SharePoint_Shell_Access database role, which is included in SPDataAcess role, but not in "dbo_owner" (I have to point out that "dbo_owner" role is not a thing, anyway).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c30c2c93-f238-cc97-6c24-fe4d8e0650f5
* Version Independent ID: 2d458263-4211-90d8-a004-a7c440ec1bb6
* Content: [Add-SPShellAdmin (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/add-spshelladmin?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Add-SPShellAdmin.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Add-SPShellAdmin.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by nsshommo** [comment]
@egor-yudkin Thanks for your valuable comment. We are working to update as necessary.

**Comment by tseward** [comment]
We need to be clear on this one. The cmdlet has two behaviors. If the SPDataAccess role exists, it uses that. If it *does not* exist, it indeed does add the user to db_owner.

**Comment by Techwriter40** [comment]
@tseward Trevor what needs to be changed in this sentence then?? thanks 

 "However, the result of running this cmdlet is that the user specified with the UserName parameter will have the dbo_owner role access on the affected databases as described above. Therefore, you should carefully plan which users are given this access."

**Comment by tseward** [comment]
@Techwriter40 I might phrase it like this:

"However, the result of running this cmdlet is that the user specified with the UserName parameter will have the SPDataAccess role, if it exists, or db_owner role, if the SPDataAccess role does not exist, on the affected databases as described above. Therefore, you should carefully plan which users are given this access."
