### ISSUE TITLE
IsInternal parameter is not related to the Antispam agents. 

### ISSUE THREAD

**Issue by hewei-msft** [MicrosoftDocs/office-docs-powershell#9064]
IsInternal parameter description has the mention about the antispam agents.  However this is not the case.  The Antispam agent does not use this parameter for their logic.   Therefore the "antispam agents" should be removed from the IsInternal parameter description

**Comment by yogkumgit** [comment]
@hewei-msft Thank you very much for the contribution and updating the documentation with PR. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
