### ISSUE TITLE
EXO module "Version 2.0.6 Preview5 or later" doesn't exist publicly yet.

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/office-docs-powershell#9066]
While it's nice to see something at all actually updated, the purple note at the top that states:

> Note
> 
> The features and procedures described in this article require the following versions of the EXO V2 module:
> 
> - Exchange Online PowerShell (Connect-ExchangeOnline): Version 2.0.3 or later.
> - Security & Compliance Center PowerShell (Connect-IPPSSession): Version 2.0.6 Preview5 or later.
>
> For instructions on how to install or update the module, see [Install and maintain the EXO V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-and-maintain-the-exo-v2-module).

Is a little misleading at present.  There is no such "preview5" in existence on PowerShell Gallery.  The Message Center post MC316448 says that everyone had to act by February 20th, yet that has come and gone and nothing has happened from Microsoft's end yet.

What gives?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by JeremyTBradshaw** [comment]
Sorry, I'm back tracking here but I'm sure it will be available soon, so I'm OK to not pursue this issue.

**Comment by chrisda** [comment]
Version 2.0.6-Preview5 of the EXO V2 Module is now available, so the various Credential parameters are now available on Connect-IPPSSession, so certibicate-based/app-oly authentication is now fully available in Security & Compliance Center PowerShell.
