### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by stevecharon** [MicrosoftDocs/office-docs-powershell#9067]
folder is incorrectly spelled as "forder" in Example 4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573e63b4-b27b-5b7b-9269-78d308fd64d3
* Version Independent ID: 57b35909-0381-1181-58bb-2262c33576d1
* Content: [Set-MailboxRegionalConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxregionalconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxRegionalConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailboxRegionalConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@stevecharon, fixed. In the future, you too can make fixes like this without opening an Issue first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
