### ISSUE TITLE
May want to change context

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/office-docs-powershell#9068]
You may want to change this statement :

The owner you specify for this parameter must be a mailbox, mail user or mail-enabled security group (a mail-enabled security principal that can have permissions assigned). You can use any value that uniquely identifies the owner. For example:

CSS has elevated to PG and they have stated that owner must be mailbox or mail users. MESG not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73241a5f-aabf-89a3-ce35-6c790b0a10cd
* Version Independent ID: 8742e952-e7d1-1bcf-73cd-c6fec3ec483b
* Content: [New-DistributionGroup (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-distributiongroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-DistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-DistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dkotars, I tried the following steps in Exchange 2010, 2013, 2016, 2019 and Exchange Online (E5 tenant):

- Verified that there was an existing distribution group (DG) and a mail-enabled security group (MESG).
- Created a new MESG with myself as the only member.
- Used Set-DistributionGroup to change the value of ManagedBy on the existing DG and MESG to the new MSEG.
  - The only environment where this didn't work was Exchange 2010, where I got this error:

    > The group "contoso.com/Users/Marketing Department" can't be managed by recipient
"contoso.com/Users/SG 02". The owner of the group should have the following recipient type
details: UserMailbox,LegacyMailbox,SharedMailbox,MailUser,LinkedMailbox,RemoteUserMailbox,RemoteSharedMailbox,MailContact,User

- Logged off and back on again and then attempted to change a benign property on the DG or MESG where the new MESG was now the owner (for example, set a value on the CustomAttribute10 property). It worked just fine.
  - If the MESG owner of the group wasn't passing permissions correctly, I would have expected an error.

So, I think I've established two points:

- 100% you can assign an MESG as the owner of a DG or another MESG in all Exchange environments except Exchange 2010. Is this what the PG desires? Who knows? But you can do it.
- Members of the MSEG as the owner of the group have the power to make changes to the group.

Where it likely falls apart is if the MESG has members that are not security principals (security princpals = users, mail users, other MESGs, etc.). If that MESG has mail contacts or DGs as members, they certainly can't have permissions to do anything to the group.

One of the reasons I did all of this testing is I remember doing similar testing a long time ago, and I wanted to make sure nothing had changed.

Comments?

**Comment by dkotars** [comment]
I this particular case, we had MESG with MESG as an owner and tested with member of owning MESG - in Exchange Online. For this particular case, end user was using Outlook to manage MESG group membership.  In that list they only saw themselves as a group member and not an owner, despite being a member of the owning MESG group.  If you explicitly made the mail user an owner, they would show as owner.  

I was able to duplicate this behavior in EXO lab environment, so we had case open to CSS, which was able to duplicate the behavior. They escalated this to PG and they stated that for MESG, to manage as owner, the mailbox needs to be explicit member. 

Perhaps this just doesn't work in Outlook, managing the MESG, but in many cases this is how our customers have users manage memberships.  Perhaps the guidance in the article stands if you're using ECP, AAD, or ADUC in hybrid, but not every customer is going to want to give users that access.

I guess maybe we can't clarify in the article if that's the case.

**Comment by chrisda** [comment]
@dkotars, now that's very interesting and definitely worth clarifying! I added the following note to the ManagedBy parameter description in New/Set-DistributionGroup:

> **Note**: Group management in Outlook doesn't work when the owner is a mail-enabled security group. To manage the group in Outlook, the owner must be a mailbox or a mail user.

Thanks for the feedback.

Closing
