### ISSUE TITLE
Poor Examples

### ISSUE THREAD

**Issue by curspice** [MicrosoftDocs/office-docs-powershell#907]
The documentation doesn't include an example for the use of the most commonly used parameter in my experience, X509CertificateName.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e2b003-51ed-8624-07d8-e30d6ebc6c8e
* Version Independent ID: 246383d8-41d0-1c15-0233-c10778e28dd5
* Content: [Set-ImapSettings (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-imapsettings?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access/Set-ImapSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access/Set-ImapSettings.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nsshommo** [comment]
@curspice Thanks for your suggestion. We will think about it.

@chrisda Can you help me on this one?

**Comment by chrisda** [comment]
@curspice, I added a 5th example that uses X509CertificateName. I also added a similar example to Set-PopSettings. If you would like to improve the example, feel free to edit it. Thanks for the feedback.
