### ISSUE TITLE
Get-CsTenantBlockedCallingNumbers replacement for 3.1.1?

### ISSUE THREAD

**Issue by rmichalskinw** [MicrosoftDocs/office-docs-powershell#9070]
I recently updated to 3.1.1 and found that we cannot find/use the CSTenantBlockingCallingNumbers commands. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881abf2b-1a4f-9c79-0804-d0d8877ae2a7
* Version Independent ID: 705e3888-5a5d-588a-d0f1-31b152260976
* Content: [Set-CsTenantBlockedCallingNumbers (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cstenantblockedcallingnumbers?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTenantBlockedCallingNumbers.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTenantBlockedCallingNumbers.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@rmichalskinw thanks for the feedback. I tried running both Get/Set-CsTenantBlockedCallingNumbers in my test tenant on TPM 3.1.1 and newly released TPM 4.0.0 and it works for me. If it continues to fail for you, my recommendation is that you open a Microsoft support case and work with them to solve it.

**Comment by yogkumgit** [comment]
@rmichalskinw Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
