### ISSUE TITLE
Set-MailboxMessageConfiguration SignatureHTML has no effect in UI

### ISSUE THREAD

**Issue by caspChristian** [MicrosoftDocs/office-docs-powershell#9073]
Using `Set-MailboxMessageConfiguration` to set `SignatureHTML` does not have any effect in UI.

This might be the same as #8537
But that issue was closed without any change. (and no explanation, which is just unacceptable)

If it is really true that "Multi signatures" MC305463 broke functionality in `Set-MailboxMessageConfiguration` then There should be documentation that explains when it does not work, and and what should be used instead. (As it is now it `SignatureHTML` does not do what it says it does)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d9fd24-705e-4fa4-7ab0-9c35c31b013e
* Version Independent ID: 9cab50c8-7f41-40e2-ae3f-1be6ae94b28e
* Content: [Set-MailboxMessageConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxmessageconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@caspChristian, it's exactly the same issue as #8537, so I'm closing this issue as a duplicate. Check back on that other issue for progress.

**Comment by caspChristian** [comment]
@chrisda Yeah, totally fine, as long as you don't close that issue again without actually documenting or fixing the actual issue ;)

(please note that at the time #8537 was closed)
