### ISSUE TITLE
Get-AdvancedThreatProtectionDocumentReport deprecated?

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/office-docs-powershell#9079]
Hi folks,

Can you please confirm if this commandlet is deprecated?  

There is no mention of it becoming deprecated in the docs, and the commandlet has not provided any warning that the command will become deprecated in the future (as has been the precedence with other deprecated commandlets).

At the moment the command does not run and results in an error from outlook.office365.com:
`We cannot currently process your request, please wait a few minutes and try again.`

FullyQualifiedErrorId : [Server=MEAPR01MB2421,RequestId=85b81df5-a926-4090-a3bd-8887c12a69f7,TimeStamp=10/03/2022 12:40:12 am] [FailureCategory=Cmdlet-FfoReportingException] 60318414,Microsoft
   .Exchange.Management.FfoReporting.GetATPDocumentReport

There appears to be no other way to get this information exported into a useful format for reporting.
Can you please advise an alternative command that generates the same output?

Cheers,
Anthony

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0268c7f-8a78-c46d-717a-dc88b4e9307a
* Version Independent ID: 56e6b1ac-5304-0f03-ba51-52b75687bae1
* Content: [Get-AdvancedThreatProtectionDocumentReport (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-advancedthreatprotectiondocumentreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionDocumentReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-AdvancedThreatProtectionDocumentReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@anthonynz, checking.

**Comment by anthonynz** [comment]
Thanks Chris,  

I should also clarify...
- this error has persisted for the past couple of weeks.
- O365 support suggested the command is deprecated.
- I'm sure it was working in December.

**Comment by chrisda** [comment]
@chrisda, wouldn't you know it, I had changes stating that this cmdlet was being deprecated (and other related updates) that were parked in a branch waiting to be published. I published them (PR will be referenced in this issue).

Thanks for the feedback.

Closing

**Comment by chrisda** [comment]
Yes:

- Get-AdvancedThreatProtectionDocumentDetail: This cmdlet will be deprecated. Use the [Get-ContentMalwareMdoDetailReport](https://docs.microsoft.com/powershell/module/exchange/get-contentmalwaremdodetailreport) cmdlet instead.
- Get-AdvancedThreatProtectionDocumentReport: This cmdlet will be deprecated. Use the [Get-ContentMalwareMdoAggregateReport](https://docs.microsoft.com/powershell/module/exchange/get-contentmalwaremdoaggregatereport) cmdlet instead.

**Comment by anthonynz** [comment]
Brilliant thanks, you have been more informative than Office 365 support.

I look forward to seeing the two new commands released to production, is there an ETA on them going live?

I can see they're physically present in the ExchangeOnlineManagement V2 module, but currently do not function.

Get-ContentMalwareMdoAggregateReport
Get-ContentMalwareMdoDetailReport

**Comment by chrisda** [comment]
The new ContentMalwareMdo cmdlets are likely in the process of being rolled out. I see them in my stock PROD E5 tenant (no flighting or Preview), so if you don't see them yet, I presume you'll see them shortly.
