### ISSUE TITLE
MicrosoftTeams 4.0.0 - created resource accounts without applicationid for call queue or autoattendant

### ISSUE THREAD

**Issue by dtavb** [MicrosoftDocs/office-docs-powershell#9087]
screnario:

using powershell 5.1
permissions: skype for business and teams administrator

[...]
	$appID = "11cd3e2e-fccb-42ad-ad00-878b93575e07"
	$upn= "ra-cq-1@contoso.com"
	$name= "ra-cq-1"

New-CsOnlineApplicationInstance -UserPrincipalName $upn -DisplayName "$name" -ApplicationId $appID
[...]

script runs without error message.

output of:  Get-CsOnlineApplicationInstance  | Where-Object { $_.UserPrincipalName -eq $upn } 

ApplicationId     : 
DisplayName       :  ra-cq-1
ObjectId          : 9876
PhoneNumber       : 
TenantId          : 1234
UserPrincipalName : ra-cq-1@contoso.com

in TAC the field for "resource account type" is empty as the powershell-attribute ApplicationId.
If you manually select the type and click save in TAC, the change is not persistent: TAC gives you the feedback of success, but if you check the resource account via powershell or TAC, the field is empty again. It does not matter to wait 24 hours or an other amount of time.

summary:
if you use New-CsOnlineApplicationInstance, the created resource accounts are useless and you must delete it.

**Comment by JensTrier** [comment]
@dtavb Thanks for the feedback. I can repro the issue with missing ApplicationId on Get-CsOnlineApplicationInstance in TPM 4.0.0. I have reported it internally. If you do Get-CsOnlineApplicationInstance -Identities <ObjectId> you will see the ApplicationId

In TAC when you Edit the resource account, the resource account type is not shown, unless you have associated the resource account to a Call Queue or Auto Attendant. If you do Assign on the resource account, you will see that TAC understands what application type the application instance was created with.

Feel free to close this issue.

**Comment by dtavb** [comment]
Hey JensTrier, thank you for your hint with the TAC.

Maybe I have taken the wrong way to get the ApplicationId, but the output of both code-snippets is the same without ApplicationId, but the resource account has never been assigned to an callqueue or autoattendant. 

1) calling via ObjectId
$ai = Get-CsOnlineApplicationInstance  | Where-Object { $_.UserPrincipalName -eq $upn }
Get-CsOnlineApplicationInstance -Identity $ai.ObjectId

2) calling via where-object
Get-CsOnlineApplicationInstance  | Where-Object { $_.UserPrincipalName -eq $upn }

But you are right: if I test it with an assigned resource account, the output is the same as you have described. Thanks for this information.

One last question: 
if you create resource accounts (attributes appID, name, upn) with powershell, the AppliacationId is empty. After you have assigned this resource account to a callqueue or autoattendant, the ApplicationId is shown with "Get-CsOnlineApplicationInstance -Identity". In TPM 4.0.0 the attribute ApplicationId is mandatory and thats why I am confused. Why should I set an ApplicationId with New-CsOnlineApplicationInstance?

**Comment by dtavb** [comment]
Hey JensTrier, thank you alot for your explanation. I am using this in the same way, with some bug fixing my azure automation runbooks are running with TPM 4.0.0 again.
