### ISSUE TITLE
Get-EXOMailbox -UserPrincipalName returns wrong mailbox, seems to also look in EmailAddresses attribute

### ISSUE THREAD

**Issue by JosefStrasserACP** [MicrosoftDocs/office-docs-powershell#9088]
The Get-EXOMailbox cmdlet with the UserPrincipalName parameter seems to also search in the EmailAddresses attribute of mailboxes.

I'm having a customer with an AzureAD user, whos UPN is added to another users mailbox emailaddresses (for whatever reason ^^). In this constellation, the behaviour of the Get-EXOMailbox cmdlet leads to a lot of trouble, when using the UPN as an identical identifier and reference at searching for an AzureAD users mailbox.

Anyone confirms this?
Can this be in any way an expected behaviour or is it just a bug?

Used PS module version: 2.0.5

**Comment by dariomws** [comment]
@JosefStrasserACP - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @JosefStrasserACP Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
