### ISSUE TITLE
LocationId parameter not mandatory + typo in example

### ISSUE THREAD

**Issue by Niehweune** [MicrosoftDocs/office-docs-powershell#9090]
- In the first parameterset (syntax), parameter LocationId isn't mandatory, so should be enclosed in square brackets 
- Example 4 has "null" instead of "$null" for the LocationId parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@Niehweune Thanks for the feedback!

I'll change the syntax section. For your second point, it is actually null you need to set it to to remove the location

**Comment by Niehweune** [comment]
Oh right, it's supposed to be an acual **string** 'null'. Maybe add quotes then, to avoid confusion with a $null value.

Come to think of it, pwsh evaluates +12065551224 as an Int64, so when cast to string this would drop the '+' (which has the same net effect here, though).

**Comment by JensTrier** [comment]
Change is in this PR https://github.com/MicrosoftDocs/office-docs-powershell/pull/9096

Feel free to close this issue
