### ISSUE TITLE
Does not honor error handling with Try Catch

### ISSUE THREAD

**Issue by southwick7320** [MicrosoftDocs/office-docs-powershell#9093]
After updating scripts to this cmdlet Try/Catch is no longer honored for a failed number assignment. 

PS C:\Users> Try{Set-CsPhoneNumberAssignment -identity '<testaccount>' -PhoneNumber +'<duplicatenumber>' -PhoneNumberType directrouting -ErrorAction stop }Catch{Write-output 'Error Response'}

Code       Message
----       -------
BadRequest Telephone Number '+<duplicatenumber>' has already been assigned to another user

Our work around has been to use an if statement to take action if an error is returned, but this feels outside of best practice for PowerShell error handling.

**Comment by JensTrier** [comment]
@southwick7320 Thanks for the feedback! I've forwarded your feedback to the team responsible for the cmdlets.

Feel free to close this issue.

**Comment by yogkumgit** [comment]
@southwick7320 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
