### ISSUE TITLE
Can't pipe into Set-UserBriefingConfig?

### ISSUE THREAD

**Issue by uclnj** [MicrosoftDocs/office-docs-powershell#9097]
Attempting to disable briefing email for all users but cannot pipe identities into this command.  Is there a reason Account pipeline input was set to false other than forcing admins to disable each account individually?

**Comment by dariomws** [comment]
Hi @uclnj, thank you for your feedback.

This is because this cmdlet does not accept a PowerShell object as input. You should specify a string with the following pattern:
"[a-zA-Z0-9!#$%*+\-/?^_`.{|}~]+@([a-zA-Z0-9\-]+\.)+[a-zA-Z]{2,4}"

It should be the UPN or PrimarySmtpAddress.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @uclnj Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
