### ISSUE TITLE
Wrong parameter in example 2

### ISSUE THREAD

**Issue by shivask** [MicrosoftDocs/office-docs-powershell#910]
Parameter in the example 2 is incorrect. Please change "-Identity" to "-InstanceId"
Get-PnPClientSideComponent -Page Home -InstanceId a2875399-d6ff-43a0-96da-be6ae5875f82

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 957300cf-4822-f1e7-5428-454b300e7984
* Version Independent ID: 0adb9dbb-262a-2999-d013-ba750e2321a1
* Content: [Get-PnPClientSideComponent (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpclientsidecomponent?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPClientSideComponent.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPClientSideComponent.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by nsshommo** [comment]
@shivask Thanks for the good catch. We are working to update as necessary.

**Comment by VesaJuvonen** [comment]
Will be fixed with June 2018 content refresh for PnP cmdlets - thanks @shivask for reporting.
