### ISSUE TITLE
Azure Automation - Unable to load "ieframe.dll"

### ISSUE THREAD

**Issue by madshaun1984** [MicrosoftDocs/office-docs-powershell#9100]
I've deployed the 4.0.0 MicrosoftTeams powershell module to Azure Automation, and have written a RunBook to assign a policy to a teams user to be used as part of our onboarding process. However, when running the playbook on Azure I'm getting the following error,

`Connect-MicrosoftTeams : Unable to load DLL 'IEFRAME.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) At line:15 char:1 + Connect-MicrosoftTeams -Credential $credential + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : AuthenticationError: (:) [Connect-MicrosoftTeams], DllNotFoundException + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams`

None of the documentation specifies that this module isn't compatible with being Run without a hybrid worker.

Can someone clarify if this should be working / is an issue, or if its just not documented that a hybrid worker is required please?

**Comment by dariomws** [comment]
@madshaun1984 - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @madshaun1984 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
