### ISSUE TITLE
EXO module "Version 2.0.6 Preview5 or later" not available to install/download

### ISSUE THREAD

**Issue by stefs987** [MicrosoftDocs/office-docs-powershell#9102]
Just over a week ago this page was updated to reference version 2.0.6 preview 5 to support connecting to the Security and Compliance Center using an application/certificate.

However this version doesn't appear to be available; the latest version in the PowerShell gallery is still 2.0.6 preview 4.

We are desperately awaiting this change due to internal policies around using service accounts, so would be really grateful if there was an update on availability. As noted in opened and closed issue #9066 this was mentioned in Message Center post MC316448, and app/cert auth was planned by late Feb/early March. 

There was a lot of hope/excitement to see the docs updated but unfortunately they are currently incorrect as 2.0.6 preview 5 isn't available still.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by JeremyTBradshaw** [comment]
@stefs987 thanks for carrying the torch 🔥.

**Comment by michevnew** [comment]
It's out now

**Comment by stefs987** [comment]
Just spotted it! Great :)
