### ISSUE TITLE
provide an example for the userids filter

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/office-docs-powershell#9117]
It isn't apparent how you would identify a user; their Exchange Distinguished Name, a GUID? Email?  Please specify UserPrincipalName and use an example;

`eg -UserIds MeganB@contoso.onmicrosoft.com`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75b757c9-b775-8294-91f7-870bead6a907
* Version Independent ID: 54ebab36-97bb-cd9f-6eb2-12198af885e2
* Content: [Search-UnifiedAuditLog (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/search-unifiedauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Search-UnifiedAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@anwarmahmood1, I updated the description to say:

> The UserIds parameter filters the log entries by the account (UserPrincipalName) of the user who performed the action. For example, laura@contoso.onmicrosoft.com.

In the future, you too can make changes like this directly without opening an Issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md>.

Thanks for the feedback.

Closing
