### ISSUE TITLE
Number Length in Examples

### ISSUE THREAD

**Issue by JohnGGeo** [MicrosoftDocs/office-docs-powershell#9118]
Examples has the incorrect length of E164 number and the example description doesn't match.

Set-CsPhoneNumberAssignment -Identity user4@contoso.com -PhoneNumber "+1425551000;ext=100" -PhoneNumberType DirectRouting
This example assigns the Direct Routing phone number +1 (425) 555-1000;ext=100 to the user user4@contoso.com

$pn=Set-CsPhoneNumberAssignment -Identity user5@contoso.com -PhoneNumber "+1425551000;ext=100" -PhoneNumberType DirectRouting
$pn
Code       Message
----       -------
BadRequest Telephone Number '+1425551000;ext=100' has already been assigned to another user

In this example the assignment cmdlet fails, because the phone number "+1425551000;ext=100" has already been assigned to another user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps#example-6)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@JohnGGeo Thanks for the feedback. Fixed it in https://github.com/MicrosoftDocs/office-docs-powershell/pull/9120

Feel free to close the issue
