### ISSUE TITLE
Some Teams PS Cmdlets are not working from Azure Cloud Shell (token or 404 error)

### ISSUE THREAD

**Issue by czendler** [MicrosoftDocs/office-docs-powershell#9119]
Hello,

We are experiencing issues while running SOME Teams PS commands from Azure Cloud Shell

Affected commands (one we already identified):
<img width="1122" alt="TeamsPSError" src="https://user-images.githubusercontent.com/16116173/158818243-07917bd4-19f2-4540-a3d8-4aac97ba2872.png">
As you can see, commands like Get-Team works fine.

Previously for above commands we received 404 error, its probably related to Teams Module version
![404](https://user-images.githubusercontent.com/16116173/158818278-84cb8cca-e9dd-4b5d-8eb6-aa326e63d352.png)

**Comment by dariomws** [comment]
Hi @czendler, thank you for your feedback.

Did you follow these instructions?

"If you want to use Cs* cmdlets, you first need to connect to Teams by using the Connect-MicrosoftTeams -UseDeviceAuthentication command."

**Comment by czendler** [comment]
> Hi @czendler, thank you for your feedback.
> 
> Did you follow these instructions?
> 
> "If you want to use Cs* cmdlets, you first need to connect to Teams by using the **Connect-MicrosoftTeams -UseDeviceAuthentication** command."

Works!!, my bad
Thanks
