### ISSUE TITLE
Connect-SPOService AuthenticationUrl and ClientTag Parameters

### ISSUE THREAD

**Issue by tommymaynard** [MicrosoftDocs/office-docs-powershell#912]
Both the AuthenticationUrl and ClientTag parameters for Connect-SPOService include an indication that their respective descriptions should be filled in. This really should happen, as there's questions from teammates about the difference between the AuthenticationUrl and the Url parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85cea8f8-239d-1f73-f13a-a5a3148b66e5
* Version Independent ID: ca809b64-206c-4dfa-7c79-b0a45979e953
* Content: [Connect-SPOService (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by nsshommo** [comment]
@tommymaynard Thanks for your query. We are looking into this matter.

**Comment by kenwith** [comment]
@tommymaynard - we are working on an audit and finding people with the right knowledge to fill in missing content. It would be great if you have some knowledge on this cmdlet to submit a Pull Request with the information. There is a readme on the main page of this repo on how to make and submit edits. Thanks for reporting and if you aren't sure this will be included in the audit so no worries but if you have some knowledge it would be really appreciated.

**Comment by tommymaynard** [comment]
I would've been happy to submit a PR with the missing information; however, it's not information I know. I'm not exactly sure, how I ended up on that page -- perhaps it was a coworker -- but I opened this issue from that page base on there being information that seems it should've been included. Sorry I can't be of more help!

**Comment by XabiBeltza** [comment]
Microsoft. How hard is to find someone from development able to fill in the appropriate description? It's been  3 months!

**Comment by kenwith** [comment]
@VesaJuvonen @Techwriter40 - this is part of queue for Office cmdlets but seems people are struggling to understand this cmdlet. Do either of you know someone that can get this filled in?

**Comment by VesaJuvonen** [comment]
Thanks, everyone for your input. Parameter details have been now added. Getting missing information on the documents is simply dependent on available resources and parameters, so we do apologize for the delay on still missing details from other cmdlets. In this particular case, both missing parameters are really an edge case scenarios used mainly by Microsoft internally, so they have not blocked anyone on using these cmdlets. Good to get them included in the documentation still.
