### ISSUE TITLE
Set-UserPhoto not availablle in ExchangeOnlineManagent 2.0.6

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#9123]
Hi,

It looks like ```Set-UserPhoto``` cmdlet became unavailable in the PowerShell module ```ExchangeOnlineManagement 2.0.6```
![image](https://user-images.githubusercontent.com/5260172/158878272-3245aadd-359d-4e5f-93d0-4012528b220b.png)

However. it **does**  appear in ```ExchangeOnlineManagement 2.0.5```

![image](https://user-images.githubusercontent.com/5260172/158878227-23237e54-81cc-4db3-9cb4-215a0f3d78bc.png)

Just wondering if you can get in touch with the concerned team regarding this issue?

Thanks in advance,
Yuriy

**Comment by chrisda** [comment]
@YuriySamorodov, if you use v2.0.6 to connect without using the -UseRPSSession switch, they you are using the short list of ~250 REST API backed cmdlets as described here:

<https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#updates-for-version-206>

It would appear that Get/Set-UserPhoto is not supported in REST API only mode (yet).

If your Connect-ExchangeOnline command includes -UseRPSSession, the Get/Set-UserPhoto cmdlets should be available.
