### ISSUE TITLE
Different results based on authentication used

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#9128]
When calling Get-CsTenant, we get different results based on the type of authentication used to connect to Teams

When using basic authentication, we see this

Get-CsTenant | Select City, CountryAbbreviation, DisplayName, PostalCode, StateOrProvince, Street, VerifiedDomains

City                       :
CountryAbbreviation        : US
DisplayName                : **** Systems Corporation
PostalCode                 : 55402
StateOrProvince            : mn
Street                     :
VerifiedDomains            : {****.com, ****.mail.onmicrosoft.com, ****.onmicrosoft.com}

But when using the token authentication (using the same user used for basic authentication), we see this

Get-CsTenant | Select City, CountryAbbreviation, DisplayName, PostalCode, StateOrProvince, Street, VerifiedDomains

City                       : Minneapolis
CountryAbbreviation        : US
DisplayName                : **** Systems Corporation
PostalCode                 :
StateOrProvince            : mn
Street                     :
VerifiedDomains            :

This is true in versions 3.1.1 and 4.0.0 of the MicrosoftTeams module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b281face-3456-9f04-2a49-21e46f33272f
* Version Independent ID: e62b6323-aba4-5286-70f0-fcccd8cf23be
* Content: [Get-CsTenant (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-cstenant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsTenant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsTenant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by isrumnon** [comment]
Hi @sarollins fix for this issue is in the pipeline and should be fixed soon - expected by next week

**Comment by yogkumgit** [comment]
@isrumnon Please update and help us in resolving this issue. Thanks

**Comment by sarollins** [comment]
It looks like version 4.1.0 fixes this issue
