### ISSUE TITLE
Get-CsOnlineUser, what is the correct way to find users based on policies (PS 3.1.1)

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#9139]
Hi,
I tried to found our users based on the meeting policies, using the following PS commands:
```
Get-CsOnlineUser -Filter "TeamsMeetingPolicy -eq '*RestrictedAnonymousAccess*'" | ft sipa*
Get-CsOnlineUser -Filter { TeamsMeetingPolicy -eq "RestrictedAnonymousAccess" } | ft sipa*
```
But both of them returns empty results.

When I run the following command:
```
Get-CsOnlineUser -Filter { TeamsMeetingPolicy -ne $null } | ft sipa*, TeamsMeetingPolicy
```
I'm getting a list of users and their Teams Meeting Policy is marked as:
```
TeamsMeetingPolicy
------------------
RestrictedAnonymousAccess
RestrictedAnonymousAccess
RestrictedAnonymousAccess
RestrictedAnonymousAccess
```

Anybody have an idea what is the correct filter to find users based on their policies?

**Comment by isrumnon** [comment]
Hi @Petri-X we have fixed this issue in TPM 4.0.1

**Comment by RG9900** [comment]
This command used to work for me in Feb 2022 and not working any longer. I never understand why Microsoft makes things harder?   Can anyone advise how can I make this command working?

#List of all @mydomain.gov.au domain users who do NOT have FederationAndPICDefault policy 

Get-CsOnlineUser -Filter {UserPrincipalName -like "*@mydomain.gov.au" -and Enabled -eq $True -and ExternalAccessPolicy -ne "FederationAndPICDefault"} | Select UserPrincipalName, SipAddress, Alias, ExternalAccessPolicy, TeamsUpgradeEffectiveMode, Description, City, Office, PostalCode, StreetAddress, Phone | Export-Csv C:\TEMP\AllUsersWhoDoNotHaveFederationandPICDefault_27052022.csv

**Comment by isrumnon** [comment]
Replied on the other ticket. Thanks
