### ISSUE TITLE
Set-place cmdlet not available

### ISSUE THREAD

**Issue by landang-tyme** [MicrosoftDocs/office-docs-powershell#9146]
I already install the latest version Exchange Online Management but the cmdlet Set-Place not available

ModuleType Version    PreRelease Name                                ExportedCommands
Script     2.0.6      Preview3   ExchangeOnlineManagement            {Get-EXOCasMailbox, Get-EXOMailbox, Get-EXOMailbo…

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af332a3-efc1-49aa-24c2-64b5031a2420
* Version Independent ID: f47bc209-aa9e-f337-1cfa-b8a727a9f780
* Content: [Set-Place (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-place?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Set-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@landang-tyme, there are a few cmdlet baked into the module itself, but even those do cmdlets absolutely nothing for you until you connect to Exchange Online PowerShell as described here:

<https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell>

If you're connected but you're still having problems accessing the cmdlet, it could be an RBAC (permissions issue).

**Comment by landang-tyme** [comment]
Hi Chris,

I have tried after connect Exchange Online PowerShell. I also have Global Administrator permission on my tenant.

**Comment by landang-tyme** [comment]
Hi Chris, I have run this script to check permission but still not see the cmdlet in there
![image](https://user-images.githubusercontent.com/102142322/159823331-7d4804ed-e53d-4b62-b0c9-07a0fb97ca7e.png)

**Comment by chrisda** [comment]
Strange. If you're in Organization Management or Recipient Management, you should see it. And to be clear, we are talking about 100% cloud, right? No on-prem or hybrid? And not delegated management?

**Comment by landang-tyme** [comment]
Yes, it's totally in cloud.

**Comment by chrisda** [comment]
It should be available. I would suggest creating a new, temporary admin account with no permissions customizations and try using that account.

Otherwise, I would suggest opening a support ticket.

**Comment by landang-tyme** [comment]
Hi Chris,

Thank you for your advise, I will try and feedback later.
