### ISSUE TITLE
Export-CsOnlineAudioFile is not usable for uploading?

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/office-docs-powershell#9147]
I have successfully uploaded an audio file using the Import-CsOnlineAudioFile.
But exporting the file back seems to get a different format unusable to Import again:
$content=Export-CsOnlineAudioFile -Identity <> -ApplicationId huntgroup
[System.IO.File]::WriteAllBytes("test.wav", $content)

Either options give me the same error "Audio file content is not supported"
(directly from the export)
Import-CsOnlineAudioFile -ApplicationId HuntGroup -FileName $audiofile.FileName -Content $content
(or from a saved file)
$contentFile = Get-Content "test.wav" -Encoding byte -ReadCount 0
Import-CsOnlineAudioFile -ApplicationId HuntGroup -FileName "test.wav" -Content $contentFile

**Comment by JensTrier** [comment]
@TheITguy666 Thanks for the feedback. Please open a Microsoft support case and they will work with you to get to the bottom of this.

**Comment by TheITguy666** [comment]
@yogkumgit 
MS support confirmed today: The file that you get from the command export-csonlineaudiofile is not a supported format to be able to upload using the import-csonlineaudiofile.

**Comment by yogkumgit** [comment]
Closing this as #9183 is linked. thanks
