### ISSUE TITLE
Set-CsCallQueue "SharedVoiceMail" behaviour

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/office-docs-powershell#9148]
This PS command seems to have different behaviors that trigger error messages

**ISSUE #1**. After running  this
Set-CsCallQueue -Identity <id> -TimeoutThreshold 30 -TimeoutAction 0
If you ran this command you get an error:
Set-CsCallQueue -Identity <id> -TimeoutThreshold 30 -TimeoutAction SharedVoicemail -TimeoutActionTarget <teamID> -TimeoutSharedVoicemailAudioFilePrompt <audiofile> -TimeoutSharedVoicemailTextToSpeechPrompt $null
>> Only one prompt could be used for timeout shared voicemail. Please give correct parameter value.

But this one works without errors:
Set-CsCallQueue -Identity <id> -TimeoutThreshold 30 -TimeoutAction SharedVoicemail -TimeoutActionTarget <teamID> -TimeoutSharedVoicemailAudioFilePrompt $null -TimeoutSharedVoicemailTextToSpeechPrompt "<tts prompt>"

And this one will also not get any error, although it sets an empty TTS
Set-CsCallQueue -Identity <id> -TimeoutThreshold 30 -TimeoutAction SharedVoicemail -TimeoutActionTarget <teamID> -TimeoutSharedVoicemailAudioFilePrompt $null -TimeoutSharedVoicemailTextToSpeechPrompt $null

**ISSUE #2**, if you ran this
Set-CsCallQueue -Identity <id> -TimeoutThreshold 30 -TimeoutAction 3 -TimeoutActionTarget <teamID> -TimeoutSharedVoicemailAudioFilePrompt <> -TimeoutSharedVoicemailTextToSpeechPrompt "some TTS here"
running this ones will generate the error
Set-CsCallQueue -Identity <id> -TimeoutThreshold 30 -TimeoutAction 3 -TimeoutActionTarget <teamID> -TimeoutSharedVoicemailAudioFilePrompt <audioID>
>> Only one prompt could be used for timeout shared voicemail. Please give correct parameter value

Set-CsCallQueue -Identity <id> -TimeoutThreshold 30 -TimeoutAction 3 -TimeoutActionTarget <teamID> -TimeoutSharedVoicemailAudioFilePrompt <audioID> -TimeoutSharedVoicemailTextToSpeechPrompt $null
>> Only one prompt could be used for timeout shared voicemail. Please give correct parameter value

And even if I clear the TTS
Set-CsCallQueue -Identity <id> -TimeoutThreshold 30 -TimeoutAction 3 -TimeoutActionTarget <teamID> -TimeoutSharedVoicemailTextToSpeechPrompt $null
I am not able to change it to audio prompt
Set-CsCallQueue -Identity <id> -TimeoutThreshold 30 -TimeoutAction 3 -TimeoutActionTarget <teamID> -TimeoutSharedVoicemailAudioFilePrompt <audioID>
>> Only one prompt could be used for timeout shared voicemail. Please give correct parameter value

**ISSUE #3**
same as #2 but it happens when you set audioprompt and want to change to TTS "directly"

**IsSUE #4**
same happens for -OverFlowSharedVoicemail*

The **Workaround** to set to audio prompt, seems to change the TimeoutAction so you can set the sharevoicemail correctly
Set-CsCallQueue -Identity <id> -TimeoutThreshold 30 -TimeoutAction 0
Set-CsCallQueue -Identity <id> -TimeoutThreshold 30 -TimeoutAction 3 -TimeoutActionTarget <teamID> -TimeoutSharedVoicemailAudioFilePrompt <audioID>

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
Hi @TheITguy666,

A few comments about your examples:
- The TimeoutActionTarget represents the target of the timeout action. If the TimeoutAction is set to Forward, this parameter must be set to a Guid or a telephone number with a mandatory ‘tel:’ prefix. If the TimeoutAction is set to SharedVoicemail, this parameter must be set to an Office 365 Group ID.
- The TimeoutSharedVoicemailAudioFilePrompt parameter indicates the unique identifier for the Audio file prompt which is to be played as a greeting to the caller when transferred to shared voicemail on timeout. This parameter becomes a required parameter when TimeoutAction is SharedVoicemail and TimeoutSharedVoicemailTextToSpeechPrompt is null.
- The TimeoutSharedVoicemailTextToSpeechPrompt parameter indicates the Text-to-Speech (TTS) prompt which is to be played as a greeting to the caller when transferred to shared voicemail on timeout. This parameter becomes a required parameter when TimeoutAction is SharedVoicemail and TimeoutSharedVoicemailAudioFilePrompt is null.
- Please try setting a real value for TimeoutSharedVoicemailAudioFilePrompt or TimeoutSharedVoicemailTextToSpeechPrompt as per the documentation.

**Comment by dariomws** [comment]
Hi @TheITguy666,

Now I understand your point. I'll report this to the product team.

Thanks!

**Comment by dariomws** [comment]
@yogkumgit, this issue was reported to the product team.

**Comment by yogkumgit** [comment]
@pbafna03 @dariomws Kindly comment. Thanks

**Comment by pbafna03** [comment]
Looping in @CLYVR

**Comment by yogkumgit** [comment]
@CLYVR Please update

**Comment by CLYVR** [comment]
@yogkumgit @pbafna03 @dariomws @TheITguy666 - Thanks for the info.

I have opened a bug with the team and they will investigate.

2881639 -  Set-CsCallQueue - can't change from TTS/Prompt or Prompt/TTS without changing routing action to something else first

**Comment by yogkumgit** [comment]
@CLYVR  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
