### ISSUE TITLE
Powershell command to Journal All messages  | Recipient $null

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/office-docs-powershell#9158]
Please update the Article for creating Journal rule for all messages in office 365, where we have to make recipient null.

```powershell
New-JournalRule -Name "Brokerage Communications" -JournalEmailAddress "Brokers Journal Mailbox" -Scope Global -Recipient $null -Enabled $true
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb41f05-13aa-f810-2ade-c6d471488132
* Version Independent ID: d98cedc5-ee51-58ef-4809-73d7b348918f
* Content: [New-JournalRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-journalrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-JournalRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-JournalRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by ansred** [comment]
@chrisda you are correct, when using "`New-JournalRule`" it's not required to enter "`-Recipient`"

However, if you created a journal rule with -Recipient, and then you wish to update that for all users, you will need to use "Set-JournalRule" with -Recipient $null

**Comment by chrisda** [comment]
@ansred, got it. Thanks.

I added the following lines to the descriptions of the Recipient parameter:

**New-JournalRule**:

> To journal messages from all recipients, don't use this parameter.

**Set-JournalRule**:

> To journal messages from all recipients, use the value $null for this parameter.

Thanks for the feedback.

Closing.

**Comment by robinpoulose1** [comment]
Thank you all for your effort and input ! !

**Comment by robinpoulose1** [comment]
Resolved!
