### ISSUE TITLE
Examples using old parameters

### ISSUE THREAD

**Issue by LarsDEu** [MicrosoftDocs/office-docs-powershell#9160]
Hi there

We found some mistakes in the examples (specific 2, 4 and 5) on this page. The example are still using the old parameters like -PstnUsages instead of -OnlinePstnUsages &  -Instance.

Regards
Lars

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0060de4-7fb0-b86a-d85f-33544226595e
* Version Independent ID: 0d2ac31e-fb2f-2d71-f7ca-a4ba5950a4e8
* Content: [Set-CsOnlineVoiceRoute (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceroute?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineVoiceRoute.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsOnlineVoiceRoute.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@dariomws
