### ISSUE TITLE
Get-ExternalInOutlook

### ISSUE THREAD

**Issue by MPSTechDir** [MicrosoftDocs/office-docs-powershell#9162]
Would like to have a viewable parameter in the Get-ExternalInOutlook command "AllowList". This way, all entries are viewable and not the first 4 entered.

**Comment by yogkumgit** [comment]
@dariomws

**Comment by dariomws** [comment]
@MPSTechDir - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Microsoft products better. They keep a close tab on user feedback and it would be awesome if you could add your voice to the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to making the docs better! Much appreciated!

**Comment by yogkumgit** [comment]
@MPSTechDir Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
