### ISSUE TITLE
 Connect-IPPSSession from ExchangeOnlineManagement v2.0.5 won't accept -CertificateFilePath or -Certificate as valid parameters

### ISSUE THREAD

**Issue by acitatorq** [MicrosoftDocs/office-docs-powershell#9164]
In spite of the contents of the office Microsoft Documention, such as:

- https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps
- https://docs.microsoft.com/en-us/powershell/module/exchange/connect-ippssession?view=exchange-ps

Connect-IPSSession from EXO v2.0.5 module doesn't accept the parameters to set up certificate base authentication, and therefore, doesn't support app-only authentication for unattended scripts using the Security & Compliance Center PowerShell:

```powershell
PS /Users/alberto.cita/CA> Get-InstalledModule                         

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.3.0                PSWSMan                             PSGallery            Module to install and manage the forked WSMan client libraries for Linux and macOS.…
2.2.5                PowerShellGet                       PSGallery            PowerShell module with commands for discovering, installing, updating and publishing the PowerShell artifacts like …
2.0.5                ExchangeOnlineManagement            PSGallery            This is a General Availability (GA) release of Exchange Online PowerShell V2 module.…

_PS /> Connect-IPPSSession -CertificateFilePath "file.pfx" -CertificatePassword (ConvertTo-SecureString -String "mypassword" -AsPlainText -Force) -AppID "********-****-****-****-**********" -Organization "myorg.onmicrosoft.com" -_
Connect-IPPSSession: A parameter cannot be found that matches parameter name 'CertificateFilePath'.
```

This works perfectly with the Connect-ExchangeOnline command, though

According to [MC316448], this was going to be released by the Feb/March timeframe.
Could somebody share an ETA for the availability of certificate based auth for Connect-IPPSSession, please?

**Comment by chrisda** [comment]
@acitatorq, indeed it won't. You need v2.0.6-Preview5 or later for that to work. From the [App-only authentication for unattended scripts in the EXO V2 module](https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2) topic (big note at the very top):

 > [!NOTE]
> The features and procedures described in this article require the following versions of the EXO V2 module:
>
> - **Exchange Online PowerShell (Connect-ExchangeOnline)**: Version 2.0.3 or later.
> - **Security & Compliance Center PowerShell (Connect-IPPSSession)**: Version 2.0.6 Preview5 or later.
>
> For instructions on how to install or update the module, see [Install and maintain the EXO V2 module](exchange-online-powershell-v2.md#install-and-maintain-the-exo-v2-module).

**Comment by acitatorq** [comment]
Thanks @chrisda,
My bad... I missed that, I'm sorry.
I just updated and recheck... the error message for the same command now is different:

PS > Connect-IPPSSession **-CertificateFilePath** "/Users/alberto.cita/CA/pwsh.pfx" -CertificatePassword (ConvertTo-SecureString -String "mypasswd" -AsPlainText -Force) -AppID "myappid" -Organization "myorg.onmicrosoft.com"                                           
**Connect-ExchangeOnline: A parameter cannot be found that matches parameter name 'CertificateThumbprint'.**

So it looks like something might still be missing... or need some fine tunning (as the error message refers to the CertificateThumbprint parameter while the cmdlet uses the CertificateFilePath parameter instead)

**Comment by acitatorq** [comment]
Thank you very much for the advice.
I will do so.
