### ISSUE TITLE
get-csonlineuser only returning 168 users (expect 25.000!)

### ISSUE THREAD

**Issue by Fimlore** [MicrosoftDocs/office-docs-powershell#9166]
When running Get-CSonlineuser without filters, and with a resultset (also when run whitout) does not return all expected users.  In fact, it just returns 168 our of our 25.621 users

When Querying with Teams module 2.6.1, the correct amount is returned. Teams Module 4.0 is returning just a (very small) subset.
even with -resultset set to 999999, it is not returnin all users

**Comment by isrumnon** [comment]
Hi @Fimlore we'll look into this issue. Can you share you tenant id? (you can dm me that detail here isrumnon@microsoft.com)

**Comment by Fimlore** [comment]
ran the commands again today, now it seems to return the correct amount again.
