### ISSUE TITLE
Duplicate attributes listed and resultsize unlimited

### ISSUE THREAD

**Issue by zcmott** [MicrosoftDocs/office-docs-powershell#9167]
Under the -filter section there are duplicate attributes listed that could be removed to shorten the section.
Under the -resulstsize section unlimited doesn't work anymore on the powershell module 4.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@dariomws

**Comment by zcmott** [comment]
@dariomws thanks, looks like the article has been updated and corrected since i have posted the feedback.
