### ISSUE TITLE
Expected Reason Codes

### ISSUE THREAD

**Issue by henrynr** [MicrosoftDocs/office-docs-powershell#9170]
We have a need to act on some users with specific Reason codes returned by this cmdlet and ignore others.  Is there a list somewhere of the expected reason codes that could be returned by the Get-BlockedSenderAddress cmdlet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809fd21b-8bdf-aefc-8009-d9c4454d34ff
* Version Independent ID: 15c13ed0-ee87-ddba-34e3-fead3acdb532
* Content: [Get-BlockedSenderAddress (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-blockedsenderaddress?view=exchange-ps#inputs)
* Content Source: [exchange/exchange-ps/exchange/Get-BlockedSenderAddress.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-BlockedSenderAddress.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@henrynr If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
