### ISSUE TITLE
Cannot use "Get-ATPPolicyForO365" when connect to Exchange online with ExchangeOnlineManagement 2.0.5

### ISSUE THREAD

**Issue by Kylex0407** [MicrosoftDocs/office-docs-powershell#9174]
When connecting to Exchange Online with Basic auth, I could run the "Get-ATPPolicyForO365" command successfully.

When using  ExchangeOnlineManagement 2.0.5, I cannot use the "Get-ATPPolicyForO365" command:

Get-ATPPolicyForO365 : The term 'Get-ATPPolicyForO365' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Is this an expected behavior or missed?
![Q A_Kyle_10-43-21](https://user-images.githubusercontent.com/66714240/160058286-67a456d8-8f44-4b6a-8c3d-fdb6546c4d58.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e871d1c7-ca8f-2d65-b051-c69a485fd8cd
* Version Independent ID: 7b572cae-090a-13e8-8845-9bf4de3fbcb4
* Content: [Get-AtpPolicyForO365 (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-atppolicyforo365?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-AtpPolicyForO365.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-AtpPolicyForO365.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Kylex0407, the lack of that cmdlet shouldn't have anything to do with the EXO V2 Module, as long as you're sure that you're running v2.0.5 and not one of the Preview versions of v2.0.6 (in which case you should add the -UseRPSSession switch to the command).

It's possible there might be some kind of temporary problem that can only be solved by a support ticket.

If you can see and access the **Global settings** (gear) button on the following pages, then the cmdlet should be available to you:

<https://security.microsoft.com/safeattachmentv2>

<https://security.microsoft.com/safelinksv2>

**Comment by Kylex0407** [comment]
Ok, thanks for your reply.
