### ISSUE TITLE
`Set-CsTeamsMeetingPolicy` `-LiveStreamingMode` parameter not in the doc

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/office-docs-powershell#9175]
Hi,

Could this RTMP broadcast feature be documented here please?

Additionally, some information on whether this feature uses Microsoft's servers to stream or the user's local machine to stream to the RTMP destination would be good. (if not on this page, on another page)

Kind regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by yogkumgit** [comment]
@dariomws
