### ISSUE TITLE
Remove-ManagementRoleEntry does not accept pipeline in Exchange online

### ISSUE THREAD

**Issue by technonath** [MicrosoftDocs/office-docs-powershell#9177]
Remove-ManagementRoleEntry does not accept pipelines in remote Exchange online powershells
so you should add a note to warn this before example 2

for verification read more here:

https://blog.rmilne.ca/2015/02/05/remove-multiple-management-role-entries-in-office-365/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d760744d-639f-d7d7-1825-d5002fb2bb1f
* Version Independent ID: 7fc35269-6374-d246-014c-72e7ca840225
* Content: [Remove-ManagementRoleEntry (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-managementroleentry?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-ManagementRoleEntry.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Remove-ManagementRoleEntry.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@technonath, what I did was add the following note after the example:

 > **Note**: Exchange Online PowerShell requires the complex syntax as described, and the same command also works in the Exchange Management Shell in on-premises Exchange servers. The Exchange Management Shell supports much simpler syntax for the same result, but the command doesn't work in Exchange Online PowerShell: `Get-ManagementRoleEntry "Tier 1 Help Desk\New-* | Remove-ManagementRoleEntry`.

Thanks for the feedback.

Closing
