### ISSUE TITLE
Disclaimer regarding exported file format

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/office-docs-powershell#9183]
Details on issue #9147 
Better write some disclaimer that the exported audio file has a little difference from the support audio files by call queues.
You can not use the content on[ import-csonlineaudiofile](https://docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps) as is and needs to be converted by the MS supported audio formats 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9628a1c2-c7d3-cff5-4049-30ecd65e02dc
* Version Independent ID: c6c34c02-4e8b-ea0c-c0d3-e767063af0a5
* Content: [Export-CsOnlineAudioFile (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/Export-CsOnlineAudioFile?view=skype-ps)
* Content Source: [skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/export-csonlineaudiofile.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@TheITguy666 Please provide the Microsoft support case/reference number, so I can follow-up on this

**Comment by TheITguy666** [comment]
[Case #:30310338]

**Comment by JensTrier** [comment]
I'll investigate and update as necessary

**Comment by TheITguy666** [comment]
@JensTrier 
Final answer from MS support case:
```
"Having consulted with the internal Team confirm the below answer to your queries. 

What is the export-csonlineaudiofile useful for?: 
-------- The Export-CsOnlineAudioFile cmdlet downloads an existing Auto Attendant (AA), Call Queue (CQ) service or Music on Hold audio file
Was supposed to be like this?: Yes 
Is it planned to work in the future?:  
------Not for now 
Is there a chance to use powershell to convert it to a supported audio to be used by import-csonlineaudiofile?: 
 -----No such plan for now 

Please if you need any clarification, do not hesitate to revert, we will be glad to assist.
```
I asked to close the ticket. The command has little use for my case as I wanted to use to generate a new call queue from an existing one :(

**Comment by yogkumgit** [comment]
@JensTrier Please update and help us in resolving this issue. Thanks

**Comment by JensTrier** [comment]
We do support importing exported audio files. The catch is that an exported audio file is always in WAV format, so should be saved as such. I have a PR out to update the documentation to reflect this

**Comment by yogkumgit** [comment]
@TheITguy666 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by TheITguy666** [comment]
@yogkumgit 
I have open an incident at MS  Ticket #30310338 that was closed with the opposite statement:
"Hello Luis,
Thank you for the response.

The cmdlet import-csonlineaudiofile is not designed to be reused. I sincerely apologize for the inconveniences you must have experienced, and I understand it would have eased the business process if you are able to reuse the cmdlet import-csonlineaudiofile

As you requested for the ticket to be archived, I will proceed to close the ticket.  Please feel free to revert, in the future if you experience any technical issues, we will be glad to assist.

Here is a summary of the issue:

Issue Description:
Export-CsOnlineAudioFile is not usable for uploading?

You were informed that the cmdlet import-csonlineaudiofile is not reusable to import file that have already been exported form the system, as these will alter the file format and properties. 

Please do have a great day

Best Regards,
Uthman
Support Engineer Microsoft 365 
For Microsoft Customer Service & Support "

**Comment by TheITguy666** [comment]
But you are right.
It was a bit misleading since the file is stored with the original name (example: music.wma or music.mp3) I assumed that the export-csonline audiofile would get the same.
It works if you define the filename as .wav when uploading

Thanks for clarifying. It was more efficient than the 3 weeks with MS Support

Maybe a statement informing that the exported content is always WAV could help since the import-csonlineaudiofile supports 3 formats (but at the end it converts to wav ?)

**Comment by JensTrier** [comment]
Yes, that statement is in this PR https://github.com/MicrosoftDocs/office-docs-powershell/pull/9243
