### ISSUE TITLE
Get-CsOnlineUser erroneous docs and inconsistent results with filter

### ISSUE THREAD

**Issue by M0rfic** [MicrosoftDocs/office-docs-powershell#9185]
Hi

 1. The `-Filter` attribute section seems to have suffered a _copy-paste error_ having attributes listed multiple times and somewhat intertwined (possibly starting with the section highlighted in red but I'm not 100% sure):
 
![image](https://user-images.githubusercontent.com/909971/160456536-5ffbef38-e1ce-47f7-8fc7-f1626a160498.png)

 2. `Get-CsOnlineUser` returning inconsistent data with `-Filter`

**Context**: I have a requirement to retrieve all the "(resource accounts) or (users with assigned phone numbers)". For this issue, I have created 1 test user with a phone number, and 2 resource accounts out of which I've assigned a number to one of them.

**Problem**: After upgrading to MicrosoftTeams module v4.0.0 things don't work as they used to. For starters, `InterpretedUserType -eq 'PureOnlineApplicationInstance'` is no longer supported by the filter, and `Get-CsOnlineApplicationInstance` returns blanks for `ApplicationId` so I can not deduce whether it's a call queue or auto-attendant:

![image](https://user-images.githubusercontent.com/909971/160459407-0d22e76a-b4b1-47e8-8f65-b64a39c6217c.png)

So my solution is to use `Get-CsOnlineUser` in conjunction with a filter for `(LineURI or OwnerUrn)`. However I'm not getting the expected results.

- if I run `Get-CsOnlineUser -Filter { (LineURI -ne $null) } -Resultsize 100 -ErrorAction Stop | Select-Object UserPrincipalName, LineURI`, I correctly get back the users or resource accounts which have a phone number assigned (please note the user highlighted in red):

![image](https://user-images.githubusercontent.com/909971/160459747-0507c78e-b75d-48a7-8c1c-ae611fa5f43b.png)

- next, if I expand the filter to also include resource accounts without phone numbers by running `Get-CsOnlineUser -Filter { (LineURI -ne $null -or OwnerUrn -eq  "urn:trustedonlineplatformapplication:ce933385-9390-45d1-9512-c8d228074e07" -or OwnerUrn -eq "urn:trustedonlineplatformapplication:11cd3e2e-fccb-42ad-ad00-878b93575e07") } -Resultsize 100 -ErrorAction Stop | Select-Object UserPrincipalName, LineURI`, I incorrectly get back just the resource accounts, without the user that had a phone number (highlighted in red above)

![image](https://user-images.githubusercontent.com/909971/160459987-14d05766-b1ac-4f37-a0a1-9a3b9bebe9b5.png)

What am I missing?

Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by isrumnon** [comment]
Hi @M0rfic on the documentation bits - thanks for pointing this out. We'll have it corrected.
On Get-CsOnlineUser returning inconsistent data we'll look into it and update you

**Comment by joergrenn** [comment]
I am also seeing issues with the -Filter attribute in the 4.0.0 module.
I want to filter for "ApplicationAccessPolicy".
Is this not supported anymore?

**Comment by isrumnon** [comment]
@joergrenn can you please try on the latest version of TPM? this works for us.

**Comment by joergrenn** [comment]
@isrumnon 
> can you please try on the latest version of TPM? this works for us.

I just tried with Version 4.1.0 of the Teams Powershell module.
Does not work for me:
I look up the available Application Access policies in the tenant:
`Get-CsApplicationAccessPolicy`
Identity    : Tag:Test-CsAppPolicy
AppIds      : {a8257864-7045f-4854-845e-82eb545454523}
Description : App Policy Test
Then I want to figure out which users it is assigned to:
`Get-CsOnlineUser -Filter "ApplicationAccessPolicy -eq 'Test-CsAppPolicy'"`
`Get-CsOnlineUser -Filter "ApplicationAccessPolicy -eq 'Tag:Test-CsAppPolicy'"`
`Get-CsOnlineUser -Filter "ApplicationAccessPolicy -eq 'App Policy Test'"`
I get no results for any of these commands.
However if I do a 
`Get-CsOnlineUser -Filter "ApplicationAccessPolicy -like '*'"`
I get all users that have a Policy assigned.

I would like to get all users with a specifiy ApplicationAccessPolicy. Is my syntax wrong?

**Comment by yogkumgit** [comment]
@isrumnon Please update and help us in resolving this issue. Thanks

**Comment by isrumnon** [comment]
@joergrenn 
PolicyProperty comparison works only when "Authority" is provided in the value. For ex: -Filter "TeamsMessagingPolicy -eq '<Authority>:<Value>'" "Authority" can contain any of these two values: Host or Tenant for a policy type (PreCanned/Default configurations provided by feature team are referred to as Host configurations while Admin-created configurations are considered Tenant configurations)

**Comment by M0rfic** [comment]
@isrumnon & @yogkumgit thanks for taking the time to reply and the updates. @yogkumgit it's helpful for the first part which was addressed, while for the second I still don't know if it's something I'm doing wrong or a bug with the module. Still getting the same behaviour with 4.1.0, and if at all possible, I'd be grateful for any suggestions/hints/etc.

Kind regards

**Comment by joergrenn** [comment]
@isrumnon thanks.
I wasn't aware of the "autority" information.  It works now when providing the "authority" information.
But I could swear in the past it worked also without. :)
