### ISSUE TITLE
Get-CsOnlineLisLocation no longer accepts "unlimited" as a value for the parameter -ResultSize.

### ISSUE THREAD

**Issue by youcefnb** [MicrosoftDocs/office-docs-powershell#9191]
MicrosoftTeams Module 4.0

Get-CsOnlineLisLocation no longer accepts "unlimited" as a value for the parameter -ResultSize.  Error message indicates that it should accept it: 

"Get-CsOnlineLisLocation : The specified ResultSize value 0 is invalid. Please provide a positive number or 'Unlimited'."

PS C:\bin\e911prov> Get-CsOnlineLisLocation -ResultSize 'Unlimited' -Force
Get-CsOnlineLisLocation : Cannot process argument transformation on parameter 'ResultSize'. Cannot convert value
"Unlimited" to type "System.Int64". Error: "Input string was not in a correct format."
At line:1 char:37
+ Get-CsOnlineLisLocation -ResultSize 'Unlimited' -Force
+                                     ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-CsOnlineLisLocation], ParameterBindingArgumentTransformationExcept
   ion
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-CsOnlineLisLocation

**Comment by JensTrier** [comment]
@youcefnb Thanks for the feedback. I'll follow-up internally and change the PS documentation as needed.

Feel free to close this issue.

**Comment by youcefnb** [comment]
I don't think this is just a documentation problem. The actual module's error asks users to uses "unlimited" as a value, so that needs to be resolved too.

**Comment by yogkumgit** [comment]
@youcefnb Thanks.
