### ISSUE TITLE
Get-QuarantineMessage has an undocumented default date criteria

### ISSUE THREAD

**Issue by tberta** [MicrosoftDocs/office-docs-powershell#9196]
Hello,
When listing the Quarantined messages matching some criterion, I see that by default, this cmdlet retrieve only the messages from the 14 last days (according to what I have observed). To retrieve older messages, I need to specify a date parameter like `-StartReceivedDate (Get-Date).AddDays(-30)`
Could you please document this limit / default value?

Thanks in advance 👍

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 90bd1486-77e2-d370-4cd8-16701e6b9568
* Version Independent ID: 1407b140-ba39-3a26-1088-6b1c3ee719ce
* Content: [Get-QuarantineMessage (ExchangePowerShell)](https://docs.microsoft.com/fr-fr/powershell/module/exchange/get-quarantinemessage?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-QuarantineMessage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-QuarantineMessage.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@tberta, I finally got a response.

As you pointed out, the max value is 30 days. Apparently, you can enter values larger/older than that, but they're ignored and only 30 day's worth of data is returned.

The retention period also comes into play: some items are kept for 30 days, some for only 15 days as described [here](https://docs.microsoft.com/microsoft-365/security/office-365-security/quarantine-email-messages).

So, I added the following text to the StartReceivedDate parameter:

> By default, if you don't use the StartReceivedDate and EndReceivedDate parameters, the command will return data for the last 16 days. The maximum value for this parameter is 30 days. If you use a value that's older than 30 days, the value is ignored and only data for the last 30 days is returned.

And no, that 16 days value isn't a typo; I was told the value was or is in the process of being changed from 14 days to 16 days.

Thanks for the feedback.

Closing

**Comment by tberta** [comment]
Thank you for the follow up and added explanation 👍🏻
