### ISSUE TITLE
Grant-CsTeamsCallingPolicy does not work if used from pipe with contents from Get-CsOnlineUser

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/office-docs-powershell#9199]
Grant-CsTeamsPolicy does not work correctly if you run it inside a scope that has piped data from Get-CsOnlineUser.

First make a variable setting a user's UPN:
```
PS> [string]$UPN = "<user's UPN>"
PS>
```

Do a single test where you clear the policy from the user:
```
PS> Grant-CsTeamsCallingPolicy -Identity $UPN -PolicyName $Null -ErrorAction SilentlyContinue
PS>
```

Do 10 repeated tests:
```
PS> 1..10 | ForEach-Object {
  Grant-CsTeamsCallingPolicy -Identity $UPN -PolicyName $Null -ErrorAction SilentlyContinue
}
PS>
```

Do it for a user retrieved through Get-CsOnlineUser:
```
PS> Get-CsOnlineuser -Identity $UPN | ForEach-Object {
  Grant-CsTeamsCallingPolicy -Identity $_.UserPrincipalName -PolicyName $Null -ErrorAction SilentlyContinue
}
Grant-CsTeamsCallingPolicy : [ClientError] : User policy update failed with message: The user was not provisioned successfully.
Parameter name: 73306f84-de78-4824-9be0-2377d13148ad
At line:2 char:3
+   Grant-CsTeamsCallingPolicy -Identity $_.UserPrincipalName -PolicyNa ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Grant-CsTeamsCallingPolicy], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Teams.ConfigApi.Cmdlets.GrantCsTeamsCallingPolicy
PS>
```

Do it without using any data from the Get-CsOnlineUser just to prove the point.
Note that we don't use the retrieved object for anything at all, we just get it and do a grant on a different object:
```
PS> Get-CsOnlineuser | Select-Object -First 1 | ForEach-Object {
  Grant-CsTeamsCallingPolicy -Identity $UPN -PolicyName $Null -ErrorAction SilentlyContinue
}
Grant-CsTeamsCallingPolicy : [ClientError] : User policy update failed with message: The user was not provisioned successfully.
Parameter name: 73306f84-de78-4824-9be0-2377d13148ad
At line:2 char:3
+   Grant-CsTeamsCallingPolicy -Identity $UPN -PolicyName $Null -ErrorA ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Grant-CsTeamsCallingPolicy], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Teams.ConfigApi.Cmdlets.GrantCsTeamsCallingPolicy
```

**Comment by ruchiagrawal9221** [comment]
Hi Dan,
upon investigation, we found that the user is "PureOnlineTeamsOnlyUserNotLicensedForService"
Could you please check if user has been provisioned with license?

**Comment by ruchiagrawal9221** [comment]
Hello,
upon investigation, we found that the user is "PureOnlineTeamsOnlyUserNotLicensedForService"
Could you please check if user has been provisioned with license?

**Comment by donlassini** [comment]
This actual user is a service account for a workflow; the user has been given a license Virtual Phone System license, and that should be sufficient.
But no matter how the user is configured, the Grant-CsTeamsCallingPolicy cmdlet still behaves differently - which is what I am reporting in.

**Comment by donlassini** [comment]
Hmm, I have just tested this again, and now it works as expected. I will investigate further but will close the ticket.
Thank you for your time.
