### ISSUE TITLE
Get-SupervisoryReviewPolicyReport output field definitions

### ISSUE THREAD

**Issue by FBrownMSFT** [MicrosoftDocs/office-docs-powershell#920]
We should include an example of the output of report cmdlets and a definition of terms in the output.  Without definitions of these terms, customers do not understand what these are and this generates a call to CSS.  

For example in the SupervisoryReviewPolicy report, what does Tag Type mean?  Tag Types returned in the report are: Compliant, Non-Compliant, Questionable, Resolved, HitPolicy, InPurview, New-Reviewed, Not-Reviewed.  While most may be self explanatory, others are not... for example what is "InPurView"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2235a7d2-d0b4-e0a4-a5a1-f26ea8985cbf
* Version Independent ID: b1a39982-a9d8-d621-6c7b-d8d1b1fa9ee5
* Content: [Get-SupervisoryReviewPolicyReport (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/reporting/get-supervisoryreviewpolicyreport?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/reporting/Get-SupervisoryReviewPolicyReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/reporting/Get-SupervisoryReviewPolicyReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nsshommo** [comment]
@FBrownMSFT Thanks for your feedback. We are working on this.

@chrisda Can you help me closing this one?

**Comment by chrisda** [comment]
@FBrownMSFT I updated the Tag Types description, located the feature owner, and told her to make any correction directly in the topic. I would assume no corrections means I got it right.

Thanks for the feedback.
