### ISSUE TITLE
How to Disable "Edit in grid view" PnP Provisining

### ISSUE THREAD

**Issue by HiighQ** [MicrosoftDocs/office-docs-powershell#9206]
Greetings,

i habe got the assgnment to build a list where the "Edit in grid view" is hidden.
Now i know how to do it using the PnP Module:
`$List = Get-PnPList -Identity $ListName $list.DisableGridEditing = $True $List.Update() Invoke-PnPQuery`

But my colleague want me to do that directly in the XML Site Template but i cant seem to find a Atribute for this cause.

Greatfull for any help!
For more infos Please Let me know.

**Comment by get-itips** [comment]
Hello @HiighQ 

how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!
