### ISSUE TITLE
Support for edit Manifest before migration in SPMT file server to SPO migration

### ISSUE THREAD

**Issue by ekreddy** [MicrosoftDocs/office-docs-powershell#9207]
Team,

IS there any way to edit Manifest.XML file before SPMT task upload files to SPO . I try to but I could see **Start-SPMTMigration** is creating XML file and immediatly uploading to SPO.

Is anthing I am misssing or can any help to edit the XML file.

SO I can attach some columns to xml before upload.

**Comment by get-itips** [comment]
Hello @ekreddy Koti,

Here, we are limited to documentation fixes.
It seems your inquiry might need to add that feature to SPMT, so the best is to send your feedback here https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472

That way, it can reach the product team.

Thank you!

**Comment by get-itips** [comment]
@yogkumgit
