### ISSUE TITLE
Wrong description of StartDate and EndDate

### ISSUE THREAD

**Issue by jgriff500** [MicrosoftDocs/office-docs-powershell#9208]
This page indicates StartDate and EndDate are the dates of meeting.  However, when running the Powershell command, it is the modify date of the meeting:

[PS] >Get-CalendarDiagnosticObjects -Identity $h.Name -StartDate 03/20/2022 -EndDate 4/1/2022 | Where-Object {$_.ParentDisplayName -eq "Calendar"}

WARNING: Using filter 'StartDate and EndDate'. Items with **OriginalLastModifiedTime** between StartDate 3/20/2022 12:00:00 AM and EndDate 4/1/2022 12:00:00 AM will be returned.
WARNING: Streamable properties values may be truncated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3e0524b-e92d-eefb-5416-557620edfb39
* Version Independent ID: 7afae510-9006-4667-5756-92714f0b08f0
* Content: [Get-CalendarDiagnosticObjects (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-calendardiagnosticobjects?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-CalendarDiagnosticObjects.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-CalendarDiagnosticObjects.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jgriff500, fixed. If you want to modify the fixes or clarify anything, see the edit instructions here:

<https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md>

Thanks for the feedback.

Closing
