### ISSUE TITLE
Issue - Exchange Online Connector Validation via PowerShell

### ISSUE THREAD

**Issue by ansred** [MicrosoftDocs/office-docs-powershell#9213]
Greetings,

**Subject:**
Issue - Exchange Online Connector Validation via PowerShell

**Component:**
Exchange Online - Connector - PowerShell

**KB:**
- https://docs.microsoft.com/en-us/powershell/module/exchange/validate-outboundconnector

**Details:**
The issue only happens when using "Validate-OutboundConnector" via PowerShell.

For example, when validating a connector from the GUI, it works fine and then the validation status gets updated you view the settings shows the timestamp of the validation that it was success.
![image](https://user-images.githubusercontent.com/5244872/161421186-b427138c-abd3-4c6a-bc61-238066e51e34.png)

However, if you run the validation on the same connector via PowerShell, it doesn't reflect the successful status, even though PowerShell shows the complete trace of the validation task it was successful.
![image](https://user-images.githubusercontent.com/5244872/161421246-00f54d7d-746d-4e85-8957-d41311092716.png)

**Note:**
I tested it many times to confirm, and the issue persists as a bug or maybe a parameter that is missing.

**Assumption:**
That the PowerShell command Validate-OutboundConnector" missing the final confirmation that triggers to update the timestamp, as in in the GUI it exists, when you get validation status is successful, it asks to you click on "Done" in the bottom, and that updates the timestamp right away.

![image](https://user-images.githubusercontent.com/5244872/161421384-0f472f51-5ab3-4f7c-8dce-01324788a023.png)

Please advise.

**Comment by ansred** [comment]
ID: efefe237-2a27-5d47-ceb0-7337a7e297b9
Version Independent ID: 369d414e-8d22-f665-8afe-326ae338b448
Content: [Validate-OutboundConnector (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/validate-outboundconnector?view=exchange-ps)
Content Source: [exchange/exchange-ps/exchange/Validate-OutboundConnector.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Validate-OutboundConnector.md)
Service: exchange-powershell
GitHub Login: @chrisda
Microsoft Alias: chrisda

**Comment by ansred** [comment]
@chrisda I agree.

I created a support ticket and replicated the issue with the support person, he's checking with engineering and product.

For ref # Ticket #30470906 

I will keep you posted once I hear back.

**Comment by ansred** [comment]
Update:

We found the issue.

We have set manually via PowerShell the values for (`-IsValidated`) + (`-LastValidationTimestamp`)
https://docs.microsoft.com/en-us/powershell/module/exchange/set-outboundconnector


That wasn't mentioned in the Validate command page, as it should be related or referenced.

I would recommend to add a note in the 
https://docs.microsoft.com/en-us/powershell/module/exchange/validate-outboundconnector

That `validate-outboundconnector` is only to validate the connector but won't set the validation status/timestamp values, with that you have do `set-outboundconnector -IsValidated $true -LastValidationTimestamp  (Get-Date).ToUniversalTime()`

Result:
![image](https://user-images.githubusercontent.com/5244872/162289390-51a77109-328f-4a14-a967-dcf9342eec8f.png)

**Comment by chrisda** [comment]
@ansred, thanks very much.

I added your note to the SYNOPSIS section of Validate-OutboundConnector and added some text to the descriptions of the IsValidated and LastValidationTimeStamp parameters in Set-OutboundConnector.

Thanks for the feedback.

Closing
