### ISSUE TITLE
'Get-MailTrafficTopReport' is not recognized

### ISSUE THREAD

**Issue by slueders-bag** [MicrosoftDocs/office-docs-powershell#9214]
**Error with ExchangeOnlineManagement 2.05:**
_Get-MailTrafficTopReport : The term 'Get-MailTrafficTopReport' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again._

Is the command replaced by another one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe9394f-b28f-a41e-b007-1e7977bdbb44
* Version Independent ID: 5d401ce1-edba-2599-f2df-e3de71444a93
* Content: [Get-MailTrafficTopReport (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailtraffictopreport?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Get-MailTrafficTopReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-MailTrafficTopReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@slueders-bag, yes. Get-MailTrafficTopReport has been replaced by [Get-MailTrafficATPReport](https://docs.microsoft.com/powershell/module/exchange/get-mailtrafficatpreport) and [Get-MailDetailATPReport](https://docs.microsoft.com/powershell/module/exchange/get-maildetailatpreport).

For more information, see the last entry in the big table here:

[Email security report changes in the Microsoft 365 Defender portal](https://docs.microsoft.com/microsoft-365/security/office-365-security/view-email-security-reports#email-security-report-changes-in-the-microsoft-365-defender-portal)

**Comment by slueders-bag** [comment]
@chrisda thank you very much for letting me know this so quickly. Of course the issue can be closed now. Thanks again for the quick clarification. 👍🏼
