### ISSUE TITLE
Configuring the global quarantine policy with PowerShell

### ISSUE THREAD

**Issue by slueders-bag** [MicrosoftDocs/office-docs-powershell#9215]
**Error in ExchangeOnlineManagement 2.0.5:**

Configuring the global quarantine policy is not possible anymore:

```powershell
Get-QuarantinePolicy -QuarantinePolicyType "GlobalQuarantinePolicy" | Set-QuarantinePolicy -EndUserSpamNotificationFrequencyInDays 1
```

This cmdlet has worked in the past but now an error is thrown:

```powershell
The operation couldn't be performed because object 'outdoorchef.onmicrosoft.com\DefaultGlobalPolicy' couldn't be found on 'DB8P278A04DC004.CHEP278A004.PROD.OUTLOOK.COM'.
    + CategoryInfo          : NotSpecified: (:) [Set-QuarantinePolicy], ManagementObjectNotFoundException
    + FullyQualifiedErrorId : [Server=GV0P278MB0434,RequestId=5e109753-59c0-4e8c-a898-797723d38d5f,TimeStamp=4/4/2022 9:10:02 AM] [FailureCategory=Cmdlet-ManagementObjectNotFoundException] 923E69E8,Mic
   rosoft.Exchange.Management.SystemConfigurationTasks.SetQuarantinePolicy
    + PSComputerName        : outlook.office365.com
```

Regarding example 2 of the reference <https://docs.microsoft.com/powershell/module/exchange/set-quarantinepolicy#example-2> also does not work any longer

**Comment by chrisda** [comment]
@slueders-bag, I just tried your command in my E5 tenant, and it worked fine. In particular, the first part of the command by itself also worked fine:

```powershell
Get-QuarantinePolicy -QuarantinePolicyType "GlobalQuarantinePolicy"
```

Perhaps something else is going on? What version of PowerShell are you using and on what platform?

I used PowerShell 5.1 and also 7.2.2 (not ISE) on a Windows 11 computer. I'm using the ExO Module v2.0.6-Preview5 (with the _-UseRPSSession_ switch), but that shouldn't matter.

**Comment by slueders-bag** [comment]
I used 7.2.2 on Windows 10 with EXO v2.0.5.
The first part also works fine, but then the set cmdlet throws an error that the policy couldn`t be found. I will give it a try with the preview version now.

**Comment by yogkumgit** [comment]
@slueders-bag Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
