### ISSUE TITLE
Get-CsOnlineUser: different results since March 25th, 2022

### ISSUE THREAD

**Issue by fgrueninger** [MicrosoftDocs/office-docs-powershell#9216]
Hi,

so before March 25th 2022, 07:10 CET, the following used to work flawlessly:

```
PS C:\Users\User\Desktop> Get-CsOnlineUser -Filter { LineURI -like "tel:+1*"} | Ft LineUri, WhenChanged

LineUri          WhenChanged
-------          -----------
tel:+122233440   24.10.2021 22:46:21
tel:+122233441   30.07.2021 20:16:59
tel:+122233442   05.03.2022 11:25:02
```

Since March 25th 2022, 07:10 CET (without upgrading my PS module), I was getting this error: 

```
PS C:\Users\User\Desktop> Get-CsOnlineUser -Filter { LineURI -like "tel:+1*"} | Ft LineURI, WhenChanged
Get-CsOnlineUser : Phone number has non digit chars. tel:+
At line:1 char:1
+ Get-CsOnlineUser -Filter { LineURI -like "tel:+1*"} | Ft LineURI, When ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ PageSize = , ...et = Extended }:<>f__AnonymousType81`11) [Get-CsOnlineUser], Exception
    + FullyQualifiedErrorId : BadArgument,Microsoft.Teams.ConfigApi.Cmdlets.GetCsOnlineUser
```
	
Okay, so apparently Microsoft deployed something. I changed my command to this - however, now the **`WhenChanged`** parameter is empty:

```
PS C:\Users\User\Desktop> Get-CsOnlineUser -Filter { LineURI -like "+1*"} | Ft LineUri, WhenChanged

LineUri          WhenChanged
-------          -----------
tel:+122233440 
tel:+122233441 
tel:+122233442 
```
In the meantime I upgraded to MicrosoftTeams 4.1.0 , and the behavior is still the same.

Microsoft, what have you done? I have two tenants that are affected by this, and interestingly my dev tenant still behaves the "old" way (as shown in the first command).

Why is the **`WhenChanged`** parameter empty when using a filter?

**Comment by yogkumgit** [comment]
@isrumnon

**Comment by isrumnon** [comment]
@fgrueninger WhenChanged when used for Filtering or when viewed in the bulk output (without using -Identity parameter) is now available in preview, you can raise a support request with your tenant information to get this enabled this for your tenant

**Comment by isrumnon** [comment]
@yogkumgit we can go ahead and close this ticket

**Comment by fgrueninger** [comment]
@isrumnon can you please please tell me when this bug is going to be fixed for all tenants (without raising support requests)?

**Comment by isrumnon** [comment]
@fgrueninger this will be generally available for all tenants by November end

**Comment by fgrueninger** [comment]
Still not fixed unfortunately. Microsoft, when are you finally going to fix this?!
