### ISSUE TITLE
EnableLitigationHoldForMigration - missing parameter description

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/office-docs-powershell#9217]
{{ Fill EnableLitigationHoldForMigration Description }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3957794-72d5-b97d-7154-42a0ad6da89d
* Version Independent ID: 8fdfada5-0dca-43ca-3f00-d4293d585f5e
* Content: [Set-MailUser (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailuser?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailUser.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@asdcristi, are you bringing this up because you're trying to use the parameter and expect it to work? Or are you just pointing out that the description is empty?

For an explanation of why there are empty parameters, see [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).

**Comment by asdcristi** [comment]
@chrisda only pointing out that the description is empty. Thank you

**Comment by chrisda** [comment]
@asdcristi, in that case, I'll say, "Thanks for pointing that out" and close the issue.

**Comment by asdcristi** [comment]
Hey Chris, I think the best thing to do would be to include the description is used parameters. This one is an actively used one, as detailed below:
"Non-hybrid target tenants can modify the quota on the Recoverable Items folder for the MailUsers prior to migration by running the following command to enable Litigation Hold on the MailUser object and increasing the quota to 100 GB: Set-MailUser -EnableLitigationHoldForMigration. Note this will not work for tenants in hybrid."
https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide

I understand there might me internally reserved cmdlets, however ones that are actively used, and also recommended by other articles, should be documented.

**Comment by chrisda** [comment]
@asdcristi, bingo. You're absolutely right. The whole point of exposing those new but unknown parameters is to force a discussion like this.

Description added:

 > The EnableLitigationHoldForMigration switch is used in cross-tenant mailbox migrations to increase the quota on the Recoverable Items folder to 100 GB (and also enable Litigation Hold) prior to migration. You don't need to specify a value with this switch.
>
> This feature is not available in hybrid tenants.
