### ISSUE TITLE
Get-CsOnlineUser -ResultSize is not working as its supposed to be - TPM 4.1.0

### ISSUE THREAD

**Issue by poshdude** [MicrosoftDocs/office-docs-powershell#9218]
Hi,

With 4.1.0, the -ResultSize parameter appears to be caching the entire tenant before returning the number of items passed to the parameter. 

```
# e.g. with TPM 2.3.1
Measure-Command {$u = Get-CsOnlineUser -ResultSize 1}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 199
Ticks             : 11997937
TotalDays         : 1.38865011574074E-05
TotalHours        : 0.000333276027777778
TotalMinutes      : 0.0199965616666667
TotalSeconds      : 1.1997937
TotalMilliseconds : 1199.7937

@($u).count
1

# e.g. with TPM 4.1.0 on the same tenant
Measure-Command {$u = Get-CsOnlineUser -ResultSize 1}

Days              : 0
Hours             : 0
Minutes           : 6
Seconds           : 18
Milliseconds      : 110
Ticks             : 3781101561
TotalDays         : 0.00437627495486111
TotalHours        : 0.105030598916667
TotalMinutes      : 6.301835935
TotalSeconds      : 378.1101561
TotalMilliseconds : 378110.1561

@($u).count
1

```

**Comment by jformacek** [comment]
This is exactly what I observe as well - causes large RAM consumption on bigger tenants

**Comment by get-itips** [comment]
Hello @poshdude Jam, how are you?
Here, we are limited to **documentation/articles** fixes. The best for your inquiry would be to open a support ticket from your tenant, that way, it can reach the team for resolution.
Thank you

**Comment by poshdude** [comment]
Hi @get-itips Andres.  I'm seeing this has started working now for some tenants but not others so hopefully something is being rolled out in the background.  From experience, the support ticket route does not yield great results when reporting issues with TPM commands .  Can you advise if there is a better thread on GitHub for raising TPM issues with the developers? Thanks.

**Comment by get-itips** [comment]
Hello @poshdude Jam,
I also tested this to check but could not repro, I obtained almost the same performance.
Said that, other good resource to reach the product team is the Teams feedback portal https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

Hope this information helps you

**Comment by poshdude** [comment]
Hi @get-itips Andres,

I still see this happening for some of the larger tenants that we manage.  Thanks for sharing the link - I'll try posting on there.

Regards,
Jam
