### ISSUE TITLE
recent changes to the -phone parameter

### ISSUE THREAD

**Issue by technonath** [MicrosoftDocs/office-docs-powershell#9224]
-Phone
The Phone parameter specifies the user's office telephone number.

Note: In Exchange Online, you can't use this parameter. Instead, use the TelephoneNumber parameter on the Set-AzureAdUser cmdlet in Azure AD PowerShell.

It would be helpful to
a)  put a purple background panel on the note to bring in line with other documentation style
b)  Please explain the reason for this recent change - because as exchange admin is the only console that supports fully customisable RBAC (office365 admin console does not support custom RBAC and Azure AD requires a premium license for custom roles)  so you can no longer create a delegated role for updating user contact information  - What a backwards step.

It is annoying that Microsoft just changed this behaviour with no official explanation - the only mention I could find was https://office365itpros.com/2021/05/11/set-user-stops-working/

If it’s a security problem for Set-User to update telephone numbers, why is it OK for Set-AzureADUser to do the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae09acf-5413-eb3c-e4c7-2481b7b178f5
* Version Independent ID: d0d555a7-de13-0173-7a8c-e13587b334bc
* Content: [Set-User (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-user?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-User.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-User.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@technonath, I did the update to the Phone and MobilePhone parameter descriptions in [May, 2021](https://github.com/MicrosoftDocs/office-docs-powershell/commit/f537f11b12e6857c8b0833dcb21469b8c3ec1626). Discussion about this is also available [here](https://techcommunity.microsoft.com/t5/exchange/update-modify-users-phone-information-on-exchange-online/m-p/2339697).

Regarding why it isn't alert formatted (purple), I would call that an editorial decision. I know 100% that alert formatting works fine in the DESCRIPTION section, and it might also work fine in individual parameter descriptions, but unless a longstanding bug has been recently fixed, alert formatting does not work in the SYNOPSIS section.

And, the other thing to keep in mind about Exchange-related cmdlet reference topics is: that same topic is used both on the web (pretty) and on the command line for `Get-Help <CmdletName>` (not so pretty). I just try to keep things simple and not use lots of formatting that will get lost in the conversion from web to command line, anyway.

**Comment by technonath** [comment]
Thank you for explaining the alert formatting decision.  on the main point I still find it very annoying and unacceptable though that if this is the official documentation for the product - why there is no explanation for the reason behind this change or recommendations on how to delegate this role now that it has been changed. It just smacks of MS can't be bothered and just change things with no explanation.  Please can you find someone from the product team to give an actual explanation please.

**Comment by chrisda** [comment]
Yeah, sorry; I have no explanation for that. Typically, 'significant' changes are always preceded by a Message Center post. I'm not sure why that didn't happen in this case, other than describing the problem gave attackers a roadmap that they could try on other properties?

**Comment by yogkumgit** [comment]
@technonath Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
