### ISSUE TITLE
Cmdlets not in latest Module release

### ISSUE THREAD

**Issue by markdmac** [MicrosoftDocs/office-docs-powershell#9237]
Why is Microsoft going to retire module versions older than 4.x.x when the version 2.3.1 has more cmdlets in it?  Specifically the Get-TeamChannel and Get-TeamChannnelUser? How are we supposed to manage the channels and their membership if the latest module is incomplete?

The support page for Get-TeamChannel does not indicate this is a pre-release cmdlet only and probably should if the commands will not be converted to the latest module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a290dbfc-3b69-2be6-a4b7-71f3f03bd004
* Version Independent ID: 36d9cfe0-cf60-2fa1-41b4-6c6971042394
* Content: [Get-TeamChannel (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by Rash-598** [comment]
Hey @markdmac 

We verified the latest version 4.1.0 and these cmdlets are present. Please check the below screenshot
![image](https://user-images.githubusercontent.com/34190894/161905166-dea86d48-2690-4dda-b386-e6ee3dbbd06a.png)
Can you please share the issue details ?

**Comment by ITMonkey78** [comment]
Found an issue with the latest modules ONLY loading the 24 available cmdlets when the module is first imported - the CS functions are not being made available.
removing and re-importing the module appears to resolve the issue and export all 583 cmdlets and functions

This can be replicated but does not appear to occur every time 

![Teams module](https://user-images.githubusercontent.com/18490295/164191382-1a48513a-dc4e-4043-a1ba-d29c4b53f3f5.png)
![Reloaded Teams module](https://user-images.githubusercontent.com/18490295/164191648-bdec10b4-7ec8-4dd5-acd1-9247cffc15a6.png)

**Comment by pbafna03** [comment]
@ITMonkey78 - which PowerShell version are you seeing this with?

**Comment by ITMonkey78** [comment]
>$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ITMonkey78** [comment]
this might be related, as I also occasionally get this error when importing the module.

```
Exception calling "Init" with "0" argument(s): "Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0,
Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file
specified."
At C:\Users\<redacted>\Documents\WindowsPowerShell\Modules\MicrosoftTeams\4.2.0\net472\Microsoft.Teams.ConfigAPI.Cmdle
ts.psm1:46 char:3
+   $instance.Init();
+   ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

You cannot call a method on a null-valued expression.
At C:\Users\<redacted>\Documents\WindowsPowerShell\Modules\MicrosoftTeams\4.2.0\net472\Microsoft.Teams.ConfigAPI.Cmdle
ts.psm1:47 char:3
+   Export-ModuleMember -Function $instance.FunctionsToExport.Split("," ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

Not getting this error isnt an indication that the module has loaded correctly though, as i can import the module without getting this error and still only have 24 cmdlets available without the functions

**Comment by pbafna03** [comment]
Hi @ITMonkey78 

These look like some dependency conflict, could you maybe get a support request initiated with details of Get-Module when the error is coming. With that the team would be able to check/suggest more.

**Comment by yogkumgit** [comment]
@markdmac Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
