### ISSUE TITLE
Get-CsOnlineuser -Filter "userPrincipalName -like '*@somedomain.at'" does not work anymore

### ISSUE THREAD

**Issue by websta911** [MicrosoftDocs/office-docs-powershell#9239]
Hi, 
since I got the "loveletter" forcing me  to change to the Teams Module  greater 4.x in June I need help fixing that issue.

 Get-CsOnlineUser : Specified method is not supported.

I am currently using 2.3.1 and it is working without issues.
We are using a Powershell managementagent  in MIM for the Teams Policies so that call is made quite often.

we have 30 000 accounts in the tenant from  2 different domains and I need only the 3 000 from 1 domain to to some things to them.
Since the "-like" Parameter changed it's functionality that it only accepts an 'search*' and not '*search' I have not been able to get the same result in 4.1.0 that I have gotten in 2.3.1, that is only the accounts from this one domain. SecondDomain is "@s.somedomain.at"

I tried  -Filter "userPrincipalName -eq '*@somedomain.at'" because that is something that works for  the 'assignedPlan' in the documentation but I had no luck. 

Do I really have to get all 30 000 User and filter them locally?
Thank you for your help.

**Comment by get-itips** [comment]
Hello @websta911 I am looking into this

**Comment by websta911** [comment]
Hello @pbafna03 

I assume that Filtering on "Company" could be a possibility to filter between users from different domains.
But, it is not as reliable because I am not filtering for a domain but for a property which can be set on both domains.
So carefully used it is a possibility but not nearly reliable as filtering for the domain. 

If that is something that can be made available quicker than the Domain filter solution I would take it. 
thanks

**Comment by pbafna03** [comment]
@yogkumgit  - pls assign this to @isrumnon

**Comment by isrumnon** [comment]
@websta911 we're working on re-introducing filtering based on Company and will have it ready soon. Will keep you updated

**Comment by yogkumgit** [comment]
@isrumnon

**Comment by isrumnon** [comment]
Hi @websta911 we'll have this change implemented by mid May. Hope this information helps

**Comment by yogkumgit** [comment]
@websta911 We appreciate any feedback and hope this information is helpful. We proceed to close this issue for now. Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by isrumnon** [comment]
Hi @websta911 this change is now implemented and should be working

**Comment by websta911** [comment]
Hi, thank you very much, it seems to work.  It still is considerably slower than the old query 30.2 Seconds vs 197.1692169  Seconds, but it is alright.
OLD
measure-command {$csuser = Get-CsOnlineUser -Filter {Userprincipalname -like "*@domain.com"} -ResultSize 10000} : 30.2 Seconds 
vs. 
NEW
Measure-Command {$csu1 = get-csonlineuser -Filter {Company -eq 'My-Company'}}  : 197.1692169 Seconds

I do not know if that if of any interest to you, I just wanted to point it out in case you do not know and like me try to make code faster.
Thank you we will survive the deprecation of old Microsoftteams Powershell modules now.
