### ISSUE TITLE
Examples are wrong.

### ISSUE THREAD

**Issue by curspice** [MicrosoftDocs/office-docs-powershell#924]
Example 3 is redundant with Example 1.  All examples are invalid in that the -Identity must be the FQDN, and the examples don't show an FQDN, such as "casarray.contoso.org".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb3c2ae-13eb-e223-4d3e-a5fb5e35a037
* Version Independent ID: 6b4a983d-0183-3409-2f02-2636cce76bc9
* Content: [Remove-ClientAccessArray (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access-servers/remove-clientaccessarray?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access-servers/Remove-ClientAccessArray.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access-servers/Remove-ClientAccessArray.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@curspice, I did some testing on a 2010 SP3 RU20 server. What I found is: the Name value does work as an identifier for Get/Set/Remove-ClientAccessArray, _but only if the value doesn't contain spaces_. If the name contains spaces, you get an error saying the name is not a valid value for the identity. I tested these other identifier values, and they all worked: ExchangeLegacyDN, FQDN, DistinguishedName, and GUID, so I modified all *-ClientAccessArray topics accordingly.

I also agree that the examples in Remove-ClientAccessArray were redundant, so now there's only one, and it uses the FQDN value as you suggested.

Thanks for the feedback.
