### ISSUE TITLE
Strange Error-Message - System.Exception: [ClientError] : Invalid input parameters forest

### ISSUE THREAD

**Issue by dtavb** [MicrosoftDocs/office-docs-powershell#9241]
We are actually staging a lot of users day for day.

Yesterday, early evening (17:00 Zurich Time) these cmdlets are ended with this message:
Exception             : System.Exception: [ClientError] : Invalid input parameters forest
TargetObject          : { Identity = abc@contoso.com, PolicyType = TeamsCallHoldPolicy, body = 
                        Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.SingleGrantUserRequest }
CategoryInfo          : InvalidOperation: ({ Identity = ma...ntUserRequest }:<>f__AnonymousType61`3) 
                        [Grant-CsUserPolicy_GrantExpanded], Exception
FullyQualifiedErrorId : ClientError,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GrantCsUserPolicy_GrantExpanded
ErrorDetails          : Invalid input parameters forest
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Grant-CsUserPolicy<Process>, 
                        C:\Modules\User\MicrosoftTeams\net472\internal\Merged_internal.ps1: line 12854
                        at Grant-CsUserOrTenantPolicy<Process>, 
                        C:\Modules\User\MicrosoftTeams\net472\custom\PsExt\Merged_custom_PsExt.ps1: line 2322
                        at Grant-CsUserOrTenantPolicy<Process>, 
                        C:\Modules\User\MicrosoftTeams\net472\exports\ProxyCmdletDefinitions.ps1: line 67483
                        at Grant-CsTeamsCallHoldPolicy<Process>, 
                        C:\Modules\User\MicrosoftTeams\net472\exports\ProxyCmdletDefinitions.ps1: line 22308
                        at <ScriptBlock>, <No file>: line 234
PipelineIterationInfo : 0 1

affected cmdlets:
Grant-CsTeamsCallingPolicy
Grant-CsTenantDialPlan
Grant-CsTeamsCallHoldPolicy

example: Grant-CsTeamsCallingPolicy -Identity $user -PolicyName "$callingpolicy"

successful cmdlets:
Grant-CsOnlineVoiceRoutingPolicy

example: Grant-CsOnlineVoiceRoutingPolicy -Identity $user -PolicyName "$voiceroutingpolicy"

This mornging the affected cmdlets are working again.

my used TPM: 4.0.0
Here on reddit an other user with 4.1.0 with the same strange error message:
https://www.reddit.com/r/MicrosoftTeams/comments/twy15y/powershell_strange_errors_grantcstenantdialplan/

What means this message "Exception : System.Exception: [ClientError] : Invalid input parameters forest" ?

Thanks!

**Comment by vlethiec** [comment]
Hi @dtavb, 
We discussed this point here.
"Teams PowerShell Module Grant Policy Commands have suddenly started throwing exceptions - TPM 4.1.0" #9229

No answer from Microsoft, but the issue looks solved now.

**Comment by dtavb** [comment]
hey, thanks for sharing the information.
