### ISSUE TITLE
.ObjectId parameter not working for TeamPowerShell Module 4.0.0

### ISSUE THREAD

**Issue by muringclub** [MicrosoftDocs/office-docs-powershell#9242]
When executing the line below as given in the examples. 
**$RAObjectId = (Get-CsOnlineApplicationInstance -Identity aa@contoso.com).ObjectId**

An error has been thrown with a message 
"New CsTeamsUnassignedNumberTreatment : Empty Target is not allowed."

This error is occurring when the example is executed using the TeamPowerShell Module 4.0.0

To overcome the error we switch the .ObjectId into .Identity
**$RAObjectId = (Get-CsOnlineApplicationInstance -Identity aa@contoso.com).Identity**

Also the **$RAObjectId = (Get-CsOnlineApplicationInstance -Identity aa@contoso.com).ObjectId**  line seems to be running fine from  TeamPowerShell Module 3.0.0

Requesting for the team to update the documentation to prevent confusion. Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 658b2b6e-3511-9e38-6cdf-8bbbbc555b31
* Version Independent ID: 9834824a-3466-2c04-0a5c-bdc0472b2561
* Content: [New-CsTeamsUnassignedNumberTreatment (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/new-csteamsunassignednumbertreatment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@muringclub Thanks for the feedback! I'm not able to repro this issue using either TPM 4.0.0 or 4.1.0 on PS 7.2.2. On both systems I see the resource account ObjectId in the $RAObjectId variable. My recommendation is that you open a Microsoft support case to get to the bottom of what's going on.

**Comment by sagius-pingco** [comment]
I have seen this as well; it is dependent on tenancy, which is a pain. My workaround for this has been to create an ObjectId NoteProperty when it does not exist on the CsOnlineUser object and regex the ObjectId from the Identity field.

The issue became apparent as of v4.0.0.

**Comment by yogkumgit** [comment]
@muringclub Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
