### ISSUE TITLE
Set-CsPhoneNumberAssignment gives incorrect error output when user not licensed

### ISSUE THREAD

**Issue by gvnwht** [MicrosoftDocs/office-docs-powershell#9244]
Output from failed Set-CsPhoneNumberAssignment doesnt give exception - I note there is another case for that problem, but I also see that the output is not clear - the Messagesays - "The user already has a telephone number set in the on-premises Active Directory and synchronized to the cloud" that is not correct, in fact the user does not have adequate licensing - the MCOEV AssignedPlan CapabilityStatus is 'Deleted'..

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++	 
MicrosoftTeams module version 4.1.0   

Set-CsPhoneNumberAssignment -Identity aaa.bbb@ccc.com -PhoneNumber +1234566789  -PhoneNumberType DirectRouting
              
**The user already has a telephone number set in the on-premises Active Directory and synchronized to the cloud. To manage this user's telephone number in the cloud, first clear the phone number in the on-premises directory and synchronize to Active Directory.**
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
MicrosoftTeams module version 3.1.1                 

et-CsUser -Identity  aaa.bbb@ccc.com -OnPremLineURI tel:+1234566789 
WARNING: OnPremLineURI will be deprecated. Please use LineURI to update user's phone number.
Set-CsUserGenerated_Set: C:\Users\me\Documents\PowerShell\Modules\MicrosoftTeams\3.1.1\netcoreapp3.1\custom\PsExt\Set-CsUserModern.ps1:51
Line |
  51 |              Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsUserGene …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | **User doesn't hold valid MCOEV plan.**
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by JensTrier** [comment]
@gvnwht Thanks for the feedback. Please open a Microsoft support case so they can work with you to get to the bottom of this.

**Comment by JensTrier** [comment]
@gvnwht Thanks for the feedback! I can repro this. Will notify the correct team. Feel free to close this issue.

**Comment by rmichalskinw** [comment]
Also having this issue - need the error updated to show that the user is not licensed appropriately. The error should be the same as 2.6.1: 

![image](https://user-images.githubusercontent.com/79276399/163237417-0d137010-1fe0-4e28-b198-95226092fdde.png)

**Comment by rmichalskinw** [comment]
> @gvnwht Thanks for the feedback! I can repro this. Will notify the correct team. Feel free to close this issue.

Any update?

**Comment by yogkumgit** [comment]
@JensTrier

**Comment by JensTrier** [comment]
@gvnwht @rmichalskinw Thanks for the patience. The cmdlet has been fixed to report the correct error message, when the user is not licensed. Feel free to close the issue(s) when you have confirmed the fixed behavior.

**Comment by yogkumgit** [comment]
@gvnwht Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
