### ISSUE TITLE
Set-CsTenantDialPlan fails when trying to work with NormalizationRules

### ISSUE THREAD

**Issue by sagius-pingco** [MicrosoftDocs/office-docs-powershell#9246]
## Issue
Error thrown when attempting to run cmdlet Set-CsTenantDialPlan to CRUD Normalization Rules on Version 4.0.0 and 4.1.0 of the MicrosoftTeams module. Error Message below:

> Unable to cast object of type 'System.Management.Automation.PSCustomObject' to type 'Microsoft.Rtc.Management.WritableConfig.Policy.Voice.NormalizationRule'.

## PowerShell Output
```
# Create Dummy Arrays for CRUD Operation
$existingRules = @()
$newRules = @()

# Create Rule and add to $newRules Array
$rule1 = New-CsVoiceNormalizationRule -Identity 'MyLittleTest/0' -Pattern '^(\d+)$' -Priority 10 -Translation '+$1' -InMemory
$newRules += $rule1

# Attempt Set-CsTenantDialPlan cmdlet
Set-CsTenantDialPlan -Identity MyLittleTest -NormalizationRules @{Remove=$existingRules; Add=$newRules} # Failure occurs here

# Confirm Variable Type (Created by MicrosoftTeams Module)
$rule1.GetType()|FL IsPublic, Name, BaseType

Output:
IsPublic : True
Name     : PSObject
BaseType : System.Object
```

I don't believe the issue is the actual object created by New-CsVoiceNormalizationRule, but more how the Set-CsTenantDialPlan cmdlet handles the call. To make this more interesting, this doesn't affect all tenancies!

My workaround so far has been to rollback to 3.1.1 in which it will run without error for all tenancies that I have confirmed problematic and non-problematic so far.

**Comment by JensTrier** [comment]
@sagius-pingco Thanks for the feedback! I tried below on TPM 4.1.0 on both PS 5.1.22000.282 and 7.2.2 and it worked for me.

`# Create Dummy Arrays for CRUD Operation
$existingRules = @()
$newRules = @()

# Create Rule and add to $newRules Array
$rule1 = New-CsVoiceNormalizationRule -Identity 'Test1/1' -Pattern '^(\d+)$' -Priority 10 -Translation '+$1' -InMemory
$newRules += $rule1

# Attempt Set-CsTenantDialPlan cmdlet
New-CsTenantDialPlan TestDP
Set-CsTenantDialPlan -Identity TestDP -NormalizationRules @{Remove=$existingRules; Add=$newRules}
`

**Comment by sagius-pingco** [comment]
Hi @pbafna03,

Thanks for the update. Will test today and advise. Most appreciated.

**Comment by JensTrier** [comment]
@sagius-pingco was this fixed for you?

**Comment by sagius-pingco** [comment]
> @sagius-pingco was this fixed for you?

Hi @JensTrier, the issue has not reoccurred, so I would say it has been resolved. Thank you!
