### ISSUE TITLE
Set-Team | No paramter to set allow member upload of custom apps

### ISSUE THREAD

**Issue by Akadelvo** [MicrosoftDocs/office-docs-powershell#9247]
In Teams GUI there is an option to set allow member **upload** custom apps.
For all other options there is an powershell paramter to set that option, why not for the option discribed above?

Best regards.

![Teams-AllowUploadCustomAppsGitHub](https://user-images.githubusercontent.com/1497063/162161272-5db4439a-c1c6-44de-9401-24ef1c8d0387.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5143fcd-9f3c-9f5d-2bdf-50b97f6a98ff
* Version Independent ID: 01f33478-352d-c7ae-0c49-784fa1c1fd67
* Content: [Set-Team (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/set-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @Akadelvo 
How are you?
Here, we are limited to documentation changes, fixes and improvements.
For feature requests and feedback, the best would be to submit an idea in the feedback for Teams 

https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

Hope this information helps you

**Comment by yogkumgit** [comment]
@Akadelvo Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
