### ISSUE TITLE
Tenant Roles need to run the command

### ISSUE THREAD

**Issue by kdkendall** [MicrosoftDocs/office-docs-powershell#9249]
Hi

What tenant roles are needed to run the command? It does not seem to be documented.
My account has the Teams Administrator and User Administrator role, but when I run the command it says "You are not authorized to perform this action".
If i run it will a Global Admin account it works fine.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788f9cf8-ffbb-f580-8624-2dbf895ec6a4
* Version Independent ID: c4b468e0-6cde-d565-7c28-54f953d2ad94
* Content: [Grant-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Grant-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Grant-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @kdkendall 
You can see in this article that Teams Administrator has required permissions https://docs.microsoft.com/en-us/microsoftteams/using-admin-roles

I also have just checked and, with a user member of Teams Administrator role (only role that this user has) I could use this cmdlet.
Be sure to be running latest GA version of the module.

Hope this information helps you,

**Comment by get-itips** [comment]
@yogkumgit
