### ISSUE TITLE
no "SkipDomainValidation" switch??!

### ISSUE THREAD

**Issue by MilanGajicBuva** [MicrosoftDocs/office-docs-powershell#9250]
I can not believe that one would remove this. 
I understand this does not affect most of the client base, but removing this for a large company mid migration (2-year just to synch the data) is almost sabotage ! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905b56a4-91c2-700a-4faf-a1cb66bda24a
* Version Independent ID: 0b002a83-d61f-7cbe-78db-a317d1377d8c
* Content: [Add-RecipientPermission (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/add-recipientpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Add-RecipientPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Add-RecipientPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MilanGajicBuva, I suggest you open a support ticket. All we do here is fix documentation.

**Comment by yogkumgit** [comment]
@MilanGajicBuva Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
