### ISSUE TITLE
New-Mailbox, errors out saying UserPrincipalName is required, when the command syntax is actually missing MicrosoftOnlineServicesID.

### ISSUE THREAD

**Issue by craigwb** [MicrosoftDocs/office-docs-powershell#9257]
New-Mailbox, errors out saying UserPrincipalName is required, when the command syntax is actually missing MicrosoftOnlineServicesID.

![image](https://user-images.githubusercontent.com/7943431/162324344-b5527d41-300c-46d5-a086-151c6358b0f2.png)

**Comment by chrisda** [comment]
@craigwb, the UserPrincipalName parameter is marked as on-prem only, AND it says to use MicrosoftOnlineServicesID in the cloud instead:

> This parameter is available only in on-premises Exchange.
>
> The UserPrincipalName parameter specifies the logon name for the user account. The UPN uses an email address format: `username@domain`. Typically, the domain value is the domain where the user account resides.
> 
> In the cloud-based service, use the MicrosoftOnlineServicesID parameter instead.

So, if you try to use UserPrincipalName in the cloud, you're getting the standard 'parameter not found' error, which is to be expected.

So, from a documentation perspective, what is there to do?

**Comment by chrisda** [comment]
Closing issue.

Thanks for the feedback.
