### ISSUE TITLE
Online documentation is wrong for Get-CsOnlineUser

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/office-docs-powershell#9261]
The documentation for Get-CsOnlineUser is not updated in the official site (possibly also the case for other cmdlets).

This page https://docs.microsoft.com/en-us/powershell/teams/?view=teams-ps
tells you to go to this page https://docs.microsoft.com/powershell/module/skype
and that page seems to contain the documentation for the original Skype Online version of the PowerShell module.

The documentation lists "-DomainController" as an option but in Teams PS v4.1.0 the option is called "UsePreferredDC".
The documentation also lists a "-Credential" parameter but that option is not in the module.

There could be other cmdlets where the functions have changed but the documentation has not.

**Comment by get-itips** [comment]
> This page https://docs.microsoft.com/en-us/powershell/teams/?view=teams-ps tells you to go to this page https://docs.microsoft.com/powershell/module/skype and that page seems to contain the documentation for the original Skype Online version of the PowerShell module.
> 

Hello @donlassini 

The SfBO cmdlets has its own path in the documentation repository, however, SfBO cmdlets were incorporated some time in the past into the Teams PowerShell module, and most of them, are also used for Teams, in this repository, they will remain for the moment, in the current path.

also, in https://docs.microsoft.com/en-us/powershell/teams/?view=teams-ps there is a link to the [Microsoft Teams cmdlet reference](https://docs.microsoft.com/en-us/powershell/teams/intro?view=teams-ps)

> The documentation lists "-DomainController" as an option but in Teams PS v4.1.0 the option is called "UsePreferredDC". The documentation also lists a "-Credential" parameter but that option is not in the module.
> 

The description for both parameters has changed recently stating the deprecation state of them and they will be removed from the article in upcoming updates.
I'll create a PR to add `-UsePreferredDC`, thank you

> There could be other cmdlets where the functions have changed but the documentation has not.

Thanks, documentation is constantly evolving, if you recognize others please do open a issue detailing what you see is outdated, your contributions make Docs better.
