### ISSUE TITLE
CsCallingLineIdentity cmdlets throw error when used for resource account

### ISSUE THREAD

**Issue by rhrotman** [MicrosoftDocs/office-docs-powershell#9265]
Since a few days (as of version 4.x of the Microsoft Teams PowerShell module?), I get an error message when I try to create or update a CallingLineIdentity.

**Error message:**
```
New-CsCallingLineIdentity : The method or operation is not implemented.
At line:1 char:1
+ New-CsCallingLineIdentity -Identity 'IdentityName'...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ConfigType = ...Configuration }:<>f__AnonymousType66`4) [New-CsCallingLineIdentity], Exception
    + FullyQualifiedErrorId : ClientError,Microsoft.Teams.ConfigApi.Cmdlets.NewCsCallingLineIdentity
```

**Commands executed:**
```
New-CsCallingLineIdentity -Identity 'IdentityName' -CallingIDSubstitute Resource -ResourceAccount <GUID> -CompanyName 'CompanyName'
Set-CsCallingLineIdentity -Identity 'IdentityName' -CallingIDSubstitute Resource -ResourceAccount <GUID> -CompanyName 'CompanyName' (after creating an unconfigured Calling Line Identity)
```

The error message doesn't occur when I omit the **CallingIDSubstitute** parameter, so this parameter seems to be the culprit, but this parameter is required in our scenario. We use Direct Routing, so this seems to be the only way for us to create Calling Line Identities.

**Comment by Benzmann88** [comment]
i had the same exact problem today
i tryed it with Teams Module 4.0.0 and 4.1.0, but no luck.

i then tried to run it on a different PC, that had Teams Module 2.6.0 and it worked !
i was able to run it without an error.

**Comment by pbafna03** [comment]
Hi @rhrotman  & @Benzmann88, 

Can you please try this again with versions 4.x.x, it will be good to do a fresh Connect-MicrosoftTeams before trying it out. This was due to a feature being flighted which ran into this issue and has been de-flighted now.

Thanks,

**Comment by rhrotman** [comment]
Yes, I can confirm this works again now in version 4.x.x. Thank you for the fast response!
