### ISSUE TITLE
"BposSAllModality" needs to be documented

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/office-docs-powershell#9266]
This cmdlet refers to the Global (org-wide default) policy as "BposSAllModality". This needs to be documented. The admin UI and all the other cmdlets use the actual name, not "BposSAllModality" so it's pretty confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3898f54-71f3-44c6-8412-c3eeee517aa7
* Version Independent ID: 8ea324f5-a833-f877-3888-a8a703bebd97
* Content: [Get-CsUserPolicyAssignment (MicrosoftTeamsPowerShell)](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csuserpolicyassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-CsUserPolicyAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsUserPolicyAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @npherson Nash, how are you?

Actually, "MeetingPolicy" are the ones returned by `Get-CsConferencingPolicy` if you look at the output of that cmdlet you can see **there is a Global** and all of the rest, start with BposS

```
Identity : Global
Identity : Tag:BposSAllModality
Identity : Tag:BposSAllModalityNoVideo
Identity : Tag:BposSAllModalityMinVideoBW
[...]
```

These were back from the days [of SFBO](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-policies-in-your-organization/set-up-conferencing-policies-for-your-organization). Not to be confused with TeamsMeetingPolicy that indeed are for Teams.

So BposSAllModality is not Global (Org Wide Default), in this case.

I also could verify this

>if an effective policy is not returned, this indicates that the effective policy for the user is either the tenant global default policy (if set) or the system global default policy.

applying the Global (Org Wide Default) TeamsMeetingPolicy to a user.


Thank you

**Comment by get-itips** [comment]
@yogkumgit
