### ISSUE TITLE
Sometimes have to run Disconnect-MicrosoftTeams before connection "works"

### ISSUE THREAD

**Issue by dsolodow** [MicrosoftDocs/office-docs-powershell#9272]
It seems like a connection times out or gets "broken" after a period.
Calling Teams cmdlets throws a "You must call the Connect-MicrosoftTeams cmdlet before calling any other cmdlets."
If you then call 
```powershell
Connect-MicrosoftTeams -AccountID myUPN@domain
```
It appears to complete successfully, but other Teams cmdlets continue to throw the "You must call the Connect-MicrosoftTeams...." error.
If I then run:
```powershell
Disconnect-MicrosoftTeams
Connect-MicrosoftTeams -AccountID myUPN@domain
```
Everything seems normal

Teams version 4.1.0
Windows 10 21H2 x64
Windows PowerShell

**Comment by pbafna03** [comment]
Hi @dsolodow - which cmdlets are you seeing this with? And what's the time gap between Connect- & the cmdlet run which gives the error?

**Comment by dsolodow** [comment]
I see this with pretty much any cmdlets from the module I use. I'll have to do some further testing to get time gaps, but here's an example from just now:
![image](https://user-images.githubusercontent.com/7574074/163398964-6f8ce796-4038-4ba8-b8b2-4654b9162eac.png)

**Comment by get-itips** [comment]
Hello @dsolodow Damien, how are you?
As here, we are limited to documentation fixes, I tried to reproduce with those exact cmdlets in that order to understand if any change to documentation under this repository is needed however I couldn't.
Also using 4.1.0 (but yesterday 4.2.0 came out)

Be sure to have only one version of the module installed at any time.

Other than that, I do not identify a documentation or article fix.

Thank you!

**Comment by dsolodow** [comment]
Is there a different repo for issues for the MicrosoftTeams module itself? Everything I see points me here. :(

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @dsolodow Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
