### ISSUE TITLE
Unspecified parameter EnhancedEmergencyServiceDisclaimer

### ISSUE THREAD

**Issue by JohnGGeo** [MicrosoftDocs/office-docs-powershell#9273]
Seeing a unspecified parameter present in set-csteamsemergencycallingpolicy, new-csteamsemergencycallingpolicy.
This is also visible in get-csteamsemergencycallingpolicy.
It doesn't seem to show a disclaimer in the client but looking for documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600b453c-8a25-4c1d-3ccc-8ad9070c84fd
* Version Independent ID: afcaa2cc-3505-f358-a15e-f970ddac33f9
* Content: [Set-CsTeamsEmergencyCallingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsemergencycallingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JohnGGeo** [comment]
Update: It does show a prompt at the top of the calls page if the parameter is set to a string,
<img width="782" alt="image" src="https://user-images.githubusercontent.com/7240495/163412853-b9cad97a-dd79-4d40-b6a5-119d634c8497.png">
So the message there was set via powershell, however it'd be nice to note when it shows etc as I already had a location set so is it a message that would appear each fresh launch now? I assume me clicking ok would make it go away until my cache is cleared or something...

**Comment by get-itips** [comment]
Hello @JohnGGeo John, thanks for adding the screenshot, yes working on adding the description for this parameter
