### ISSUE TITLE
Get-TeamChannel and channel's email address

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#9274]
Hi,
Does anybody knows if coming versions from the Teams PS module could save our time, and give the email address from the channel, if that is mail enabled? Currently we are getting only:
**Id
DisplayName
Description
MembershipType**
Which is not too much :D

**Comment by get-itips** [comment]
Hello @Petri-X how are you?
It's true, that cmdlet does not return that information. Sounds like a great feedback, I'll try to pass this on however I recommend adding a feedback item here https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472
Thank you!

**Comment by yogkumgit** [comment]
@Petri-X  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
