### ISSUE TITLE
SpokenName feature deprecated

### ISSUE THREAD

**Issue by MiBurtan** [MicrosoftDocs/office-docs-powershell#9276]
SpokenName feature has been deprecated also in Outlook WIN32
internal reference: 2689663

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a057e0e5-e897-e015-11ed-22cdbb6f7c43
* Version Independent ID: ee3ec571-bf8c-7623-92a8-538851427d54
* Content: [Import-RecipientDataProperty (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/import-recipientdataproperty?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Import-RecipientDataProperty.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Import-RecipientDataProperty.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MiBurtan, fair point, but the Import-RecipientDataProperty and Export-RecipientDataProperty cmdlets are still available.

I removed the second sentence from the introduction:

> The user's picture and spoken name are available in the global address (recipient properties), contact card, reading pane, and meeting requests in Outlook.

So now I guess the topic is accurate?

**Comment by MiBurtan** [comment]
thank you, Chris! it sure is better now :D 
so, if the cmdlet parameter is still available, but the feature itself is deprecated, the doc should still contain the info on the parameter, right? 

I guess it would come down to the cmdlet owners to announce this, namely that the parameter will not take any affect.

**Comment by chrisda** [comment]
If the only change is lack of availability of the user's spoken name in Outlook, then I wouldn't say the feature is deprecated. The user can still have a spoken name value on their account/mailbox, no? And Exchange admins can still use Import-RecipientDataProperty to add a spoken name, and Export-RecipientDataProperty download an existing spoken name?

Or perhaps I'm misunderstanding.

What would be beneficial for the topic is to mention the Outlook version (build number) where spoken name visibility went away. I'm sure there are many customers who aren't using the latest and greatest version of Outlook, so it still works for them.

**Comment by chrisda** [comment]
I'm going to close this issue. The topic has been updated to remove reference to spoken name and Outlook, so now the topic is technically accurate.
