### ISSUE TITLE
Component values

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/office-docs-powershell#9277]
Please double-check all values for component parameter.

Example:

Export-MailboxDiagnosticLogs: |Microsoft.Exchange.Data.StoreObjects.ObjectNotFoundException|Logs for component 'OOFRules' weren't found in mailbox
Identity:'Gert Rudolf'. Available logs: 'MFN, CalendarActiveSharees, ReplicateAttendees, CalendarReplication,
AcceptCalendarSharingInvite, VisibleMeetingMessageProcessing, CalendarSharingInitialView, ScheduledFolder, Sharing,
TriggerSharingSyncAsNeeded, CalendarSharingPreAcceptCache, OnlineMeetings, MeetingMessageType,
CalendarSharingMeetingMessageProcessingAgent, SweepRules, InternalCalendarSharingMigration, CalendarSharingLocalFolder,
ActionProcessingAgent, AttendeeListReplicationAssistant, FreeBusyPublishingAssistantQuickLog,
SharingMigrationAssistant, TimeProfile, DefaultViewIndexer, SharingSyncAssistant, MRM, BirthdayAssistant,
DelegateRulesManagement, RemindersAssistant, MeetingMessageProcessingAgent, CalendarPermissions, Calendar,
OOF,HoldTracking,SubstrateHoldTracking'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a14c168-36d5-ae55-ce5c-7231c25335cb
* Version Independent ID: 7453ae2a-0865-f36c-b237-4b2106ecfbad
* Content: [Export-MailboxDiagnosticLogs (ExchangePowerShell)](https://review.docs.microsoft.com/en-us/powershell/module/exchange/export-mailboxdiagnosticlogs?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Export-MailboxDiagnosticLogs.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Export-MailboxDiagnosticLogs.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@trudolf-msft, here's what I've come up with so far:

- In my E5 test tenant (100% PROD; no flighing, no SDF), only the following values work (don't return errors):
  -  ActionProcessingAgent
  - BirthdayAssistant
  - CalendarPermissions
  - CalendarSharingLocalFolder
  - DefaultViewIndexer
  - FreeBusyPublishingAssistantQuickLog
  - HoldTracking
  - InternetCalendar
  - MRM
  - OnlineMeetings
  - OOFRules
  - RemindersAssistant
  - SharingMigrationAssistant
  - SharingSyncAssistant
  - SubstrateHoldTracking
  - SweepRules
  - TimeProfile

- The remaining values from your error list don't work:
  - AcceptCalendarSharingInvite
  - AttendeeListReplicationAssistant
  - Calendar
  - CalendarActiveSharees
  - CalendarReplication
  - CalendarSharingInitialView
  - CalendarSharingMeetingMessageProcessingAgent
  - CalendarSharingPreAcceptCache
  - DelegateRulesManagement
  - InternalCalendarSharingMigration
  - MeetingMessageProcessingAgent
  - MeetingMessageType
  - MFN
  - OOF
  - ReplicateAttendees
  - ScheduledFolder
  - Sharing
  - TriggerSharingSyncAsNeeded
  - VisibleMeetingMessageProcessing

- On my Exchange 2019 and Exchange 2016 test servers, only the following values work:
  - CalendarPermissions
  - Hold Tracking

- On my Exchange 2013 test server, only the value HoldTracking works.

- On my Exchange 2010 test server, none of those values work. No help from the error message, either:

  `Logs for component 'owdnfio' weren't found in mailbox 'John Doe'. Available logs: ''`

Comments? I have a feeling that the list of available logs is different based on the mailbox type. I would presume regular user mailbox has the most available, but shared mailboxes or room/equipment mailboxes would only have a subset.

**Comment by chrisda** [comment]
It's also worth noting that the list of available values (which is worded to indicate the values listed aren't exhaustive) only differs from my recent test by one "bad" value: InternetCalendarSharingMigration.

**Comment by yogkumgit** [comment]
@trudolf-msft Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
