### ISSUE TITLE
PowerShell 4.2.0 Displaying Wrong Error - Set-CsPhoneNumberAssignment

### ISSUE THREAD

**Issue by rmichalskinw** [MicrosoftDocs/office-docs-powershell#9281]
We upgraded to PowerShell 4.2.0 in the hopes that the Set-CsPhoneNumberAssignment errors were fixed, but they are not. Users who are missing the Phone System license are displaying the following: 

FAILED | BadRequest The user 'd2960676-bad7-4d7b-96e5-a5ec9066b82b' already has a telephone number set in the on-premises Active Directory and synchronized to the cloud. To manage this user's telephone number in the cloud, first clear the phone number in the on-premises directory and synchronize to Active Directory. 

When using PowerShell 3.1.1 the correct error is displayed: 

FAILED | BadRequest User 'd2960676-bad7-4d7b-96e5-a5ec9066b82b' lacks appropriate licenses to assign a 'DirectRouting' number. 

Since Microsoft is forcing companies to move to 4.x.x we need the errors displayed to be correct and valuable. We are not willing to upgrade to the 4.x.x PowerShell if the errors are not correct. 

User account for testing was created today and have never been on-prem or had a number assigned to it.

**Comment by pbafna03** [comment]
Hi @rmichalskinw, 

Can you please try this with 4.2.0 again once, there were few improvements done around this. 

Thanks,

**Comment by rmichalskinw** [comment]
@pbafna03 - this has been confirmed: 

![image](https://user-images.githubusercontent.com/79276399/163582795-05caa95e-a0e3-4438-bea7-f192c7fd9073.png)
