### ISSUE TITLE
Parameter MTREnabled missing from Docs page

### ISSUE THREAD

**Issue by alex-marrero** [MicrosoftDocs/office-docs-powershell#9284]
Set-Place documentation page is missing parameters that are in the latest release of the EchangeOnlineManagement module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af332a3-efc1-49aa-24c2-64b5031a2420
* Version Independent ID: f47bc209-aa9e-f337-1cfa-b8a727a9f780
* Content: [Set-Place (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-place?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@alex-marrero, the Set-Place cmdlet isn't baked into the module itself, so it's more about which version you're using and how you're connecting:

- v2.0.6-Preview5

  Are you using the UseRPSSession switch in the Connect-ExchangeOnline command? That lets you see all cmdlets and parameters as normal.

  If you'e not using the UseRPSSession switch, then you would only have access to the ~250+ cmdlets that use the new REST API. This is all explained [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#updates-for-version-206).

- v2.0.5 (latest production version)

  Nothing special to describe.

I just tested in my own E5 tenant, and the only undocumented parameter I see is MTREnabled.

What do you see that's undocumented?

**Comment by chrisda** [comment]
MTREnabled parameter added and described in PR #9373 .

Thanks for the feedback.

Closing

**Comment by HSteindl** [comment]
Thanks for adding this. However the hedescription is not helpful at all, since it does not explain what this parameter actually does? Is it just for providing additional information in Outlook's roomfinder, does it change anything within the room mailbox, etc.
In other words: What is the difference between setting this to $true vs $false.
