### ISSUE TITLE
Get-CsOnlineSchedule result limit of 100 since 4.x.x

### ISSUE THREAD

**Issue by MicheleBomello** [MicrosoftDocs/office-docs-powershell#9285]
since module version 4.x.x, the Get-CsOnlineSchedule will only return the first 100 results.

also tested with 4.2.0

with module 4.x.x
```
(Get-CsOnlineSchedule).count
100
```

with module 3.1.1
```
(Get-CsOnlineSchedule).count
172
```

**Comment by yinzh798** [comment]
Can you please try this again with version 4.x.x? It will be good to do a fresh Connect-MicrosoftTeams before trying it out. This was due to a feature being flighted which ran into this issue and has been de-flighted now.

**Comment by MicheleBomello** [comment]
I tested it again. It works now. Thank you very much.
