### ISSUE TITLE
LineURI filters failing when there are non-numerical characters for Get-CSOnlineUser in 4.1.0

### ISSUE THREAD

**Issue by lgaudreau** [MicrosoftDocs/office-docs-powershell#9286]
My tenant uses the 'tel:+1xxxxxxxxxx;ext=xxxx' format with direct routing, and I have no way to filter by phone number using the 4.1.0 module.

I've tried these formats so far:
```
$Number = "tel:+1xxxxxxxxx;ext=xxxx"
$filter = 'LineURI -eq "{0}"' -f $Number
Get-CsOnlineUser -Filter $filter
```

Result:

`Get-CsOnlineUser: Phone number has non digit chars. tel:+1xxxxxxxxx;ext=xxxx`

This filter works fine in the MicrosoftTeams 2.6.0 module, but fails in 4.1.0:

```
Get-CsOnlineUser -Filter 'LineURI -eq "tel:+1xxxxxxxxx;ext=xxxx"'
```
Result:
```
Get-CsOnlineUser: Phone number has non digit chars. tel:+1xxxxxxxxx;ext=xxxx
```
If I remove the "tel:+" part, it still fails due to the extension.
If I search by username, LineURI is returned in the format "1xxxxxxxxxx;ext=xxxx"

Is there another format I can try for the filter, or how can I search for a specific number?

**Comment by isrumnon** [comment]
Hi @lgaudreau this is a know issue which we are working on fixing soon

**Comment by lgaudreau** [comment]
Thank you, @isrumnon.  From my own testing and via a support ticket for a non-related Teams issue, I found the following:

For some reason this filter works:
`Get-CSOnlineUser -Filter {lineUri -like 'tel:+1xxxxxxxxxx*'}`

But this one does not:
`Get-CSOnlineUser -Filter {lineUri -like '*xxxxxxxxxx*'}`

**Comment by yogkumgit** [comment]
@isrumnon

**Comment by isrumnon** [comment]
Hi @lgaudreau the wild card operator is now only supported when used for filtering at the end of the value (i.e., Starts With) with the only exception being filtering on AssignedPlans

**Comment by yogkumgit** [comment]
@lgaudreau Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by isrumnon** [comment]
Hi @lgaudreau Filtering on lineuri with ext based numbers should now be working

**Comment by lgaudreau** [comment]
Excellent, thank you @isrumnon.  I'm out of office this week but will be able to test when I return on Monday.  Cheers!
