### ISSUE TITLE
PQMT: [Exchange] When send an email online, "FromIP" field should be blank, but it is not blank

### ISSUE THREAD

**Issue by Saki-Yufu** [MicrosoftDocs/office-docs-powershell#9305]
![20220418_1](https://user-images.githubusercontent.com/103729056/163918089-6821a5e8-6947-4494-b4ae-dd64b456c529.png)
[Document URL]
https://docs.microsoft.com/powershell/module/exchange/get-messagetrace

[Description]
When send an email online, "FromIP" field should be blank, but it is not blank.
The document says "For outgoing messages from Exchange Online, the value is blank" about "-FromIP".
However, when send email online and get information about emails with Get-MessageTrace command on PowerShell, "FromIP" column is not blank.
You should change or delete the sentence on the docs to match the actual behavior.
Please refer to the attached file (20220418_1.png).

[Actual result]
-FromIP
The FromIP parameter filters the results by the source IP address. For incoming messages, the value of FromIP is the public IP address of the SMTP email server that sent the message. **For outgoing messages from Exchange Online, the value is blank.**

[Expected result]
-FromIP
The FromIP parameter filters the results by the source IP address. For incoming messages, the value of FromIP is the public IP address of the SMTP email server that sent the message. 

[Repro step]
1. Access to Outlook on the web.
2. Click "New message". Enter any recipient, any subject, and text. Click "Send".
3. Launch PowerShell as Administrator. PS should be a latest version.
4. Type the following command to install Exchange online management module.
	PS> Install-Module -Name ExchangeOnlineManagement -RequiredVersion 2.0.5
5. Type the following command to import the module.
	PS> Import-Module ExchangeOnlineManagement
6. Type the following command and enter any address and password, to sign in to Exchange online management with the one used in the step 1-2.
	PS> Connect-ExchangeOnline
7. Type the following command. To get sending / receiving information of emails using Get-MessageTrace, and export those as .csv file.
	PS> Get-MessageTrace | Export-Csv -Path <path>
	e.g. PS> Get-MessageTrace | Export-Csv -Path C:\Users\User\Desktop\getmesssagetrace.csv
	* It may take some time before the email information can be obtained by Get-MessageTrace.
8. Open the created csv file. Find the info for email which is sent in the step 2. Check "FromIP" column.

[Source] 
Japan Internal Feedback 

[Copied from]
https://microsoft.sharepoint.com/:li:/t/ntojapan/pqmt/E3ldEnx5YzhKiYo6LYRXw8kBCbfN-nViyFUvMfxoV07AvQ?e=iOEwK0

**Comment by chrisda** [comment]
@Saki-Yufu, thank you for the detailed explanation. I removed the offending sentence as you described.

Thanks for the feedback.

Closing
