### ISSUE TITLE
New-TeamsApp Forbidden issue

### ISSUE THREAD

**Issue by bhushangholave** [MicrosoftDocs/office-docs-powershell#9317]
Trying to upload new teams app through our AD user.
Its working from UI but from PowerShell its throwing forbidden issue.
I checked the permission for this user in AD but its still not working.
Below are the details.
```
Connect-MicrosoftTeams -Credential $credential
New-TeamsApp : Error occurred while executing New-TeamsApp
Code: Forbidden
Message: User not authorized to perform this operation. UserId: 'xxxx-xxxx-xx-xxx-xxxxxxxxx', TenantId: 'xxxxx-xxxx-xxxx-xxx-xxxx'
InnerError:
  RequestId: 81bdee93-f41f-4f4a-a208-9bb8bfd1e783
  DateTimeStamp: 2022-04-20T09:38:12
HttpStatusCode: Forbidden
```

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @bhushangholave this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
