### ISSUE TITLE
Get-DlpDetailReport Not Returning correct value of 'SensitiveInformationCount'

### ISSUE THREAD

**Issue by mevaibhav83** [MicrosoftDocs/office-docs-powershell#9331]
Powershell command Get-DlpDetailReport generating incorrect count at “SensitiveInformationCount”, SensitiveInformationCount from powershell does not match with count display at ‘Activity Explorer’. 

Issue has observed with almost all sensitivity type especially when there is high count of match but pattern is not clear. 

$filedate = (Get-Date -Format "ddMMyyyy") 
Get-DlpDetailReport -StartDate 04/19/2022 -EndDate 04/21/2022 -Source EXCH -DlpCompliancePolicy "LIVE-GLOBAL-DLP-POLICY-MATCH" | select Date, DlpComplianceRule, Title, Actor, Action, SensitiveInformationType, SensitiveInformationCount, SensitiveInformationConfidenceLevel, DlpCompliancePolicy, SensitiveInformationConfidence, Index, UserAction, Justification | where {($_.Actor -eq 'user@domain.com')} | Export-Csv "c:\temp\dlpdetailreport_$filedate.csv" 

![image](https://user-images.githubusercontent.com/13334884/164752802-0d883a6d-2df6-4f0c-9921-b5d9e4c5836b.png)

**Comment by mevaibhav83** [comment]
Below is my finding from investigation:

'SensitiveInformationCount' from Get-DlpDetailReport is not unique match count vs. count from 'activity explorer' is unique match count so Get-DlpDetailReport need fixing to return unique match count (same as 'activity explorer' report) to align with 'activity explorer' report.

**Comment by chrisda** [comment]
@mevaibhav83, your best way forward is to open a support case about this.

**Comment by yogkumgit** [comment]
@mevaibhav83 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
