### ISSUE TITLE
TPM 4.x.x - Get-CsOnlineUser does not return any results when using Filter and OnlineVoiceRoutingPolicy

### ISSUE THREAD

**Issue by poshdude** [MicrosoftDocs/office-docs-powershell#9335]
Hi,

The documentation [https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps](url) lists OnlineVoiceRoutingPolicy as an attribute which supports Filter.  I am not seeing this to be the case.  

Running the commands below does not return any results.
```
Get-CsOnlineUser -Filter { OnlineVoiceRoutingPolicy -eq '<OnlineVoiceRoutingPolicy>' } 

#OR

Get-CsOnlineUser -Filter "OnlineVoiceRoutingPolicy -eq '<OnlineVoiceRoutingPolicy>'"

#OR

Get-CsOnlineUser -Filter "OnlineVoiceRoutingPolicy -like 'OVP*' "
```

This seems to work, although its of limited usefulness

```
Get-CsOnlineUser -Filter  { OnlineVoiceRoutingPolicy -ne $null }
```

Thanks.

**Comment by isrumnon** [comment]
Hi @poshdude there has been some slight modifications to Filtering based on Policy attributes:

PolicyProperty comparison works only when "Authority" is provided in the value. 
For ex: -Filter "TeamsMessagingPolicy -eq '<Authority>:<Value>'" "Authority" can contain any of these two values: Host or Tenant for a policy type (configurations that are provided by default are referred to as Host configurations while admin-created configurations are considered Tenant configurations). 
The following are more examples:
- Filter "TeamsMessagingPolicy -eq 'Host:EduStudent'"
- Filter "TeamsMessagingPolicy -eq 'Tenant:TestDemoPolicy'"

**Comment by poshdude** [comment]
Hi @isrumnon Isaiah,  thanks for the response , good to and this does work for me.  I guess the documentation is a little out of date? 

BR

**Comment by noobadmin07** [comment]
> Hi,
> 
> 
> 
> The documentation [https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps](url) lists OnlineVoiceRoutingPolicy as an attribute which supports Filter.  I am not seeing this to be the case.  
> 
> 
> 
> Running the commands below does not return any results.
> 
> ```
> 
> Get-CsOnlineUser -Filter { OnlineVoiceRoutingPolicy -eq '<OnlineVoiceRoutingPolicy>' } 
> 
> 
> 
> #OR
> 
> 
> 
> Get-CsOnlineUser -Filter "OnlineVoiceRoutingPolicy -eq '<OnlineVoiceRoutingPolicy>'"
> 
> 
> 
> #OR
> 
> 
> 
> Get-CsOnlineUser -Filter "OnlineVoiceRoutingPolicy -like 'OVP*' "
> 
> ```
> 
> 
> 
> This seems to work, although its of limited usefulness
> 
> 
> 
> ```
> 
> Get-CsOnlineUser -Filter  { OnlineVoiceRoutingPolicy -ne $null }
> 
> ```
> 
> 
> 
> Thanks.

Hi How do you enabled the enterprisevoicenabled and onpremlineUri? 

can you advise the right command? 

thank you

**Comment by isrumnon** [comment]
@noobadmin07 you can reference this document for more context on this topic 
https://docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps
