### ISSUE TITLE
Can you make -StatusMailRecipients available?

### ISSUE THREAD

**Issue by TheSecAtlas** [MicrosoftDocs/office-docs-powershell#9339]
Good morning, 

I am trying to get some sort of email feedback for the Powershell Content Search modules. Whether its from the content search creation or the purge section. `-StatusMailRecipients` looks like it would work for my use case.

If this can not be done, can you point me in the direction of a way to receive notifications from the content search from powershell module?

**Comment by chrisda** [comment]
@TheSecAtlas, anything related to content search should be explained here:

<https://docs.microsoft.com/microsoft-365/compliance/content-search>

I would say: don't put too much hope in unavailable parameters. If you can find answers for what you're trying to do, the next step would be to open a support ticket. All we do here is fix documentation.
