### ISSUE TITLE
Teams Module - Get-Cs* commands throws instead of silently returning $null (prior to 2.6.0) when the queried resource doesn't exist

### ISSUE THREAD

**Issue by tushdeore** [MicrosoftDocs/office-docs-powershell#9346]
Get-Cs* command is broken with the recent Teams module (4.0.0, 4.1.0).
The Get-Cs* commands throw an exception instead of silently returning $null (prior to 2.6.0) when the queried resource doesn't exist, and we were relying on this to check whether to create the resource or not. 
So, we handled it differently now with Teams module 4.0.0, where we are checking a particular text in the error message in exceptions and deciding whether to create a new resource or not.
for example, for Get-CsTeamsComplianceRecordingPolicy we were getting exceptions with messages containing 'Cannot find "TeamsComplianceRecordingPolicy"', and the script only creates the policy when the exception message got this particular text.

This was working fine till march last week when we released scripts compatible with Teams Module 4.0.0,
but those are also broken now as the exception for Teams Module 4.0.0 for Get-Cs* suddenly changed and our logic of resource existence check failed.

Could you please let us know the definite solution for checking resources exist 
Or
Restore the behavior prior to 2.6.0 where The Get-Cs* commands do not throw an exception and silently return $null.

**Comment by tushdeore** [comment]
Hi @pbafna03,
I tried version 4.2.0, getting the exception if the policy does not exist, earlier it was returning $null silently.

`PS C:\Users\Administrator> $recordingPolicy = Get-CsTeamsComplianceRecordingPolicy -Identity "DummyPolicyName"`
`Get-CsTeamsComplianceRecordingPolicy : "DummyPolicyName" not found`
`At line:1 char:1`
`$recordingPolicy = Get-CsTeamsComplianceRecordingPolicy -Identity "Du ...`
`CategoryInfo          : InvalidOperation: ({ ConfigType = ...emaVersion =  }:<>f__AnonymousType19`4) `[Get-CsTeamsComplianceRecordingPolicy], Exception
FullyQualifiedErrorId : ClientError,Microsoft.Teams.ConfigApi.Cmdlets.GetCsTeamsComplianceRecordingPolicy`

`PS C:\Users\Administrator>`

My question was is there any definitive way to check whether resources exist or not rather than making this decision based on exceptions. 
Also, we observed that this exception also changed a couple of times for Version 4.0.0 so we cannot rely on the exception.

**Comment by pbafna03** [comment]
@tushdeore - Something like Get-CsTeamsComplianceRecordingPolicy -Filter "DummyPolicyName" can be used to check existence.

**Comment by tushdeore** [comment]
@pbafna03 Yes it worked, this is exactly what I was looking for.
Thank you so much :)

**Comment by yogkumgit** [comment]
@tushdeore If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
