### ISSUE TITLE
Is [Set/Remove]-CsPhoneNumberAssignment CMDLets really for hybrid setups? (PS mod 4.2)

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#9347]
Hi,
Just tested the new number assignment on Teams PS module 4.2:
`PS C:\> remove-CsPhoneNumberAssignment -Identity jane.doe@company.com -PhoneNumber +3581234567
 -PhoneNumberType DirectRouting`

But I'm getting output from that:
```
Code    : BadRequest
Message : The user 'a7....e2' already has a telephone number set in the on-premises Active
          Directory and synchronized to the cloud. To manage this user's telephone number in the cloud, first clear the
           phone number in the on-premises directory and synchronize to Active Directory.
```

This outcome support the documentations as well:
[Microsoft Docs: Set-CsPhoneNumberAssignment](https://docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps) which says:
_If a user or resource account has a phone number set in Active Directory on-premises and synched into Microsoft 365, you can't use Set-CsPhoneNumberAssignment to set the phone number. You will have to clear the phone number from the on-premises Active Directory and let that change sync into Microsoft 365 first_

But if I remove the numbers from on-prem, then our Skype does not detect that number, but also as our SBC is checking the number from AD that will lose it as well.

So the question is, is it expected that we need to do much more to get this new PS to be used than just update the scripts? For example change our Azure AD synchronization to become two-way sync for Skype related items? If that is the case, should that be mentioned on somewhere? Or have you misunderstood something very badly :D

**Comment by JensTrier** [comment]
@Petri-X Thanks for the feedback. I can see you raised this feedback via the admin portal also. I'll reply there.

**Comment by Petri-X** [comment]
I see, I cannot hide?? :D  
LOL

**Comment by JensTrier** [comment]
No :-)

**Comment by JensTrier** [comment]
We connected offline. Feel free to close this issue.

**Comment by Petri-X** [comment]
Big thanks @JensTrier !

If others gets lost, on hybrid setup you should control EnterpriseVoiceEnabled $True/$False only on Teams PS module for PSTN. Rest of the work use still Skype's own PS module on-premises.
