### ISSUE TITLE
TPM 4.2.0 still delivering legacy values for some Tenants

### ISSUE THREAD

**Issue by poshdude** [MicrosoftDocs/office-docs-powershell#9353]
Hi,

For some of the tenants I manage, Get-CsOnlineUser command in TPM 4.2.0 is still delivering legacy value for some properties.

```
$u = Get-CsOnlineUser -Identity <UPN>
$u.Identity
CN=945befxx-xxxx-xxxx-xxxx-xxxx32cd11b9,OU=a2axxx-xxxx-xxxxx-xxxx-xxxx379573ea,OU=OCS Tenants,DC=lync4a001,DC=local

# expected value (modern)
945befxx-xxxx-xxxx-xxxx-xxxx32cd11b9
```

Please advise as I have uplifted scripts to now expect the ObjectId value in Identity.

Thanks.

**Comment by pbafna03** [comment]
Hi @poshdude, 

Can you please raise a support request with the tenant information (Tenant id etc.) This could be if the tenant is or have been enabled for Regionally Hosted Meetings for Skype for Business Online. 

Thanks,

**Comment by poshdude** [comment]
Hi,

Thanks for the response.  Is that something that should not be switched on any more?  What is it that I need to be asking for when I raise the support request? 

Thanks,

**Comment by pbafna03** [comment]
@poshdude - you can raise the support request with the above issue described & the tenant information. Team would be able to suggest next steps based on the tenant details.

**Comment by yogkumgit** [comment]
@poshdude Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
