### ISSUE TITLE
Most Parameters aren't working anymore

### ISSUE THREAD

**Issue by JAmler** [MicrosoftDocs/office-docs-powershell#9355]
Hello,
the cmdlet worked normaly before, but now it says most paramters can't be found.

For example these are not working:
    -EnableMailboxIntelligence $true `
    -EnableMailboxIntelligenceProtection $true 
    -EnableOrganizationDomainsProtection $true 
    -EnableSimilarDomainsSafetyTips $true 
    -EnableSimilarUsersSafetyTips $true 
    -EnableSpoofIntelligence $true 
    

One example failure for EnableMailboxIntelligence Paramter:
A parameter cannot be found that matches parameter name 'EnableMailboxIntelligence'.
2022-04-27T11:20:38.8985775Z At C:\Users\VssAdministrator\AppData\Local\Temp\tmp_x45t5zea.tqk\tmp_x45t5zea.tqk.psm1:58084 char:9
2022-04-27T11:20:38.8986979Z +         $steppablePipeline.End()
2022-04-27T11:20:38.8987381Z +         ~~~~~~~~~~~~~~~~~~~~~~~~
2022-04-27T11:20:38.8988123Z     + CategoryInfo          : InvalidArgument: (:) [Set-AntiPhishPolicy], ParameterBindingException
2022-04-27T11:20:38.8988780Z     + FullyQualifiedErrorId : NamedParameterNotFound,Set-AntiPhishPolicy
2022-04-27T11:20:38.8989451Z     + PSComputerName        : outlook.office365.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15695a77-5d00-89d9-fba9-74de36ffd4cf
* Version Independent ID: 0e0863e8-82e8-0709-4204-bb406266b2f9
* Content: [Set-AntiPhishPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-antiphishpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JAmler, are you using v2.0.6-Preview3 or later of the EXO V2 module?

If so, be sure to use the -UseRPSSession switch in your Connect-ExchangeOnline command. If you don't, then you're only getting the REST-API backed cmdlets/parameters that are currently available. For more information see: [Updates for version 2.0.6](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#updates-for-version-206).

I checked in my tenant, and those parameters are definitely still available to me.

**Comment by yogkumgit** [comment]
@JAmler Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
