### ISSUE TITLE
Get-CsOnlineUser: LastName not available

### ISSUE THREAD

**Issue by Edgar81** [MicrosoftDocs/office-docs-powershell#9356]
Based on the docs, the LastName field is available in Teams PowerShell Module 4.2.0 and later. However, when I run the code below, the output doesn't contain the LastName field.

Import-Module MicrosoftTeams -RequiredVersion 4.2.0;

Connect-MicrosoftTeams;

try
{
   Get-CsOnlineUser -Identity upn_goes_here;
}
finally
{
   Disconnect-MicrosoftTeams;
}

**Comment by pbafna03** [comment]
Hi @Edgar81, 

Can you please check this with the latest Teams PowerShell Module version 4.3.0?

Thanks,

**Comment by Edgar81** [comment]
Hi @pbafna03 It works with 4.3.0. Could you please also update the docs? I see it's been changed from 4.2.0 to 4.2.1, but there's still 4.2.0 for LastName in the second part of the page.

Thank you!

**Comment by yogkumgit** [comment]
@pbafna03

**Comment by pbafna03** [comment]
@yogkumgit  - this is already updated in the relevant page, please go ahead with closing this.

**Comment by yogkumgit** [comment]
@Edgar81 If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
