### ISSUE TITLE
Incorrect Information

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/office-docs-powershell#9380]
Your site says "All email addresses in the global address list (GAL) are automatically considered as trusted senders, so you don't need to add them to the list."
Unfortunately, this is not completely true. If an email address is spoofed, then this is inaccurate. There are legitimate cases for address spoofing. In our case, we use a 3rd party email service to send a newsletter to staff and consultants. Our Exec Team wants images to automatically load for all staff. However, we can't add the spoofed address to the Safe Senders List because this command produces an error when trying to add an address from the same domain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e95bf3-e9dc-b528-b4ce-8dae3db5f141
* Version Independent ID: e6bf871e-eb81-ef60-9454-6f895e1bccde
* Content: [Set-MailboxJunkEmailConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxjunkemailconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxJunkEmailConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailboxJunkEmailConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DontNeedNoGit, so what would you update that statement to say?

**Comment by DontNeedNoGit** [comment]
Ideally, there would be a solution to this situation! Why prevent this in the first place?

In the meantime, it should probably be put into one of the colored boxes to say "**Please note:** we do not currently have a way to add email addresses from the same domain as the recipient's mailbox to the Safe Sender's List. It is usually unnecessary to do this for any addresses in the Global Address List. However, there is not a solution on the occasions when this could be desired (for example: spoofed emails)."

I'd suggest adding a similar note here:
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes

**Comment by chrisda** [comment]
Does adding the spoofed sender in the Tenant Allow/Block List achieve what you're looking for?

https://docs.microsoft.com/microsoft-365/security/office-365-security/manage-tenant-allows#create-spoofed-sender-allow-entries-using-microsoft-365-defender

**Comment by DontNeedNoGit** [comment]
No. That only prevents it from going to the Junk Email folder. It does not have any impact on the loading of images in Outlook ("Don't download pictures automatically in standard HTML email messages" in the Outlook Trust Center > Automatic Download settings).

**Comment by DMoenks** [comment]
The section in question should probably read "All **mailboxes** in the global address list (GAL) are automatically considered as trusted senders, so you don't need to add them to the list", as there's a difference between an email sent by an internal mailbox with email address X and an external sender with address X, spoofing is spoofing after all.

The probably suggested, way cleaner solution to the original issue might be to configure the third-party service for authenticated email delivery, allowing it to send an email from within the tenant, as described in [How to set up a multifunction device or application to send email using Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365). Another approach might be using [Use the Outlook mail REST API](https://docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0) if the other service supports it. SPF might also be something to look at.
But that's rather a support topic, not a documentation topic...

**Comment by chrisda** [comment]
Thanks @DMoenks. My next suggestion was going to be SPF, since it sounds like the third-party service is sending email as if from your own domain.

<https://docs.microsoft.com/microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing>

<https://docs.microsoft.com/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing>

If you still can't get your desired result, I would recommend opening a support ticket, and report any documentable findings back here.

In the meantime, I'll update the description based on the feedback. I'm tempted to blend the 'mailboxes' comment with the idea that you simply can't add addresses from the same domain as the recipient's mailbox.

**Comment by DontNeedNoGit** [comment]
Spoofed or not, it's still a mailbox in the GAL. So, only changing to that doesn't really clarify anything. 

I appreciate the other ideas, but you can't auth a shared mailbox. It's irrelevant anyway because 3rd party email marketing services don't allow you to change how they send. So, I couldn't use the auth or the rest api and use their service.

We've already updated our SPF record. Messages arrive in staff Inboxes (not Junk). The Executive team wants images to load for all of these emails the first time tha they're opened. The only way that I know to affect that behavior is to either completely disable the option not to download images from all external senders--a huge security issue--or to add the address to the safe senders list. If this powershell command would simply function for internal addresses, then we'd be all set. 

I've already opened a ticket with Microsoft Support, but they're terribly slow, especially to get to anyone slightly knowledgable.

**Comment by yogkumgit** [comment]
@DMoenks Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
