### ISSUE TITLE
Get-SPOSite -Filtering variables issue

### ISSUE THREAD

**Issue by ealmonte32** [MicrosoftDocs/office-docs-powershell#9384]
I've tried so many different ways and thought this was related to and maybe fixed with the PR from this issue: https://github.com/MicrosoftDocs/office-docs-powershell/issues/6431

But seems to still be an issue or this might be a new issue with the filtering..

I am writing a script that as it goes through some active directory users from a list I feed it, it needs to find their SPOSite personal Url, and I then do what I need to do with the resulting output...

But, the Filter does not seem to work when the Owner value is entered as a variable, even when quotes are used to expand the value..

Screenshot below shows all three different ways of putting the value, as you can see, only when the Owner/email address is entered manually as the value does it actually return the Owner with Url...

![image](https://user-images.githubusercontent.com/24350198/166609262-71edc16c-5371-455c-9b62-5be5dff1e662.png)

**Comment by get-itips** [comment]
Hello,

You can construct the filter like this

`get-sposite -filter "Owner -like '$($userUPN)'"`

Hope this information helps you,

**Comment by ealmonte32** [comment]
@get-itips 
Andres,
Thanks, this worked.
I think this should be documented at https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-sposite?view=sharepoint-ps

**Comment by yogkumgit** [comment]
@get-itips
