### ISSUE TITLE
validate-outboundconnector

### ISSUE THREAD

**Issue by LubomirHozak** [MicrosoftDocs/office-docs-powershell#9385]
While using the validate-outboundconnector commandlet I found out, that it would be much easier if I could also specify the senders email address, because the default O365ConnectorValidation@tenantName.onmicrosoft.com is using the tenant default domain and not the custom domain which I need to test. Please think about introducing additional parameter to be able to use one of the custom domains.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efefe237-2a27-5d47-ceb0-7337a7e297b9
* Version Independent ID: 369d414e-8d22-f665-8afe-326ae338b448
* Content: [Validate-OutboundConnector (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/validate-outboundconnector?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Validate-OutboundConnector.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Validate-OutboundConnector.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@LubomirHozak, we can't handle feature requests here, just updates to documentation.

Your bet way forward is to open a support ticket.
