### ISSUE TITLE
Session Timeout for MSOnline

### ISSUE THREAD

**Issue by VishwaA2000** [MicrosoftDocs/office-docs-powershell#9403]
Hi,
     How long a session established with Connect-MsolService will last?. Is there any official docs regarding this. Does it inherit the timeout configuration of PSSessionSessionOption?

**Comment by yogkumgit** [comment]
@VishwaA2000 Please indicate which document you are referring to. Thanks

**Comment by VishwaA2000** [comment]
Hi, I was working on msoniline recently but there's no document/discussion regarding session msonline session like this (https://docs.microsoft.com/en-us/answers/questions/195338/extend-idle-timeout-for-exchange-online-powershell.html) for exchange online. I am just wondering Is there session timeout for msonline? Is there a way to extend idle timeout for it like specified for exchange?

**Comment by chrisda** [comment]
@VishwaA2000, it will likely work, but long-running scripts are best handled by certificate-based authentication (also known as CBA or app-only authentication), which is available for both Exchange Online PowerShell and Security & Compliance Center PowerShell:

<https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2>

**Comment by yogkumgit** [comment]
@VishwaA2000 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
