### ISSUE TITLE
Private items still visible in OWA after removing access.

### ISSUE THREAD

**Issue by christianellwood** [MicrosoftDocs/office-docs-powershell#9405]
In Example 3, the command does not remove access to Private items on Outlook on the web. It does work in client however.

Example 3
Set-MailboxFolderPermission -Identity ayla@contoso.com:\Calendar -User ed@contoso.com -AccessRights Editor -SharingPermissionFlags Delegate
In Exchange Online, this example removes access to private items for an existing delegate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b48ac9a9-ae8b-7656-49b3-b0fcbc862dae
* Version Independent ID: cc3abf30-b1d7-3ca0-ca3a-5437bf8ad7fb
* Content: [Set-MailboxFolderPermission (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxfolderpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxFolderPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailboxFolderPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@christianellwood, you should open a support ticket about this. Folder permissions are folder permissions and it should work in both places.

**Comment by yogkumgit** [comment]
@christianellwood Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
