### ISSUE TITLE
Add Grant-CsOnlineVoiceRoutingPolicy and Grant-CsTenantDialPlan to cmdlet references for Microsoft Teams

### ISSUE THREAD

**Issue by avellanedgar** [MicrosoftDocs/office-docs-powershell#9407]
Customers are getting confused about the **Grant-CsOnlineVoiceRoutingPolicy** and **Grant-CsTenantDialPlan** as they are referenced in Direct Routing docs for Teams, but are not being referenced in the Teams Powershell commands. 

Suggestion would be to add these 2 commands to the cmdlet references for Microsoft Teams, https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6804423b-8e08-5916-9355-6bebe8bb08b0
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [MicrosoftTeamsPowerShell Module](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @avellanedgar 
how are you?
The index is auto-generated from the cmdlets that are under the Teams/ path, the cmdlets you mention are under a different path because they belonged to the Skype For Business Online module, currently, they will stay there but I understand that in the future this could change.
Hope this information helps you,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @avellanedgar Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
