### ISSUE TITLE
-Path variable

### ISSUE THREAD

**Issue by JoeAlanis** [MicrosoftDocs/office-docs-powershell#941]
states: C:\Inutepub\wwwroot\MyWebApplication; 
probably meant: C:\inetpub\wwwroot\MyWebApplication

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6316f255-a35c-8a88-2459-bdf8dd0a3787
* Version Independent ID: fdbaf4a2-51b1-7e63-4b15-48327f1c8915
* Content: [New-SPWebApplication (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spwebapplication?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPWebApplication.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPWebApplication.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
this has been updated. thanks for the catch!!!
