### ISSUE TITLE
Feature Request -- Add-PnpSiteColumnToList

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/office-docs-powershell#942]
Please forgive me is this is covered in the current set of commands, however I could not find the exact command I was looking for.

I would like to be able to apply a site column to a document library WITHOUT using custom content types. The site column I would like to apply is of type "Managed Metadata".

Why? The reason I am shying away from the content types is because once you activate custom content types on a modern library it deactivates a users ability to create Word, Excel, PowerPoint and OneNote files using the online editor. You lose that functionality. My goal is to require the metadata but give the end user the flexibility to create whatever kind of file they choose.

**Comment by robertcaretta** [comment]
I think I figured it out??
$field1 = Get-PnPField -Identity "MyCustomSiteColumn";
Add-PnPField -List "TEST" -Field $field1;

**Comment by nsshommo** [comment]
@robertcaretta Thanks for your commenting here. By sharing your experience here, you are helping many others.

**Comment by VesaJuvonen** [comment]
Hi Rob, that's indeed the model. That will add the field from the site level to the list without content type.
