### ISSUE TITLE
Incorrect signature for MicrosoftTeams.psd1 in v4.3.0

### ISSUE THREAD

**Issue by MrDmig** [MicrosoftDocs/office-docs-powershell#9426]
Not possible to update the module by using Update-Module cmdlet cause of a signature mismatch. Workaround - Install-Module cmdlet with -SkipPublisherCheck parameter just to bypass signature tests.

It's easy to check the signature:

Get-AuthenticodeSignature .\MicrosoftTeams.psd1

    Directory: C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.3.0

SignerCertificate                         Status                      Path

385856F7AB96024DA600A7BD6118F6C5386A5368  HashMismatch                MicrosoftTeams.psd1

Status                 : HashMismatch
StatusMessage          : The contents of file C:\Program Files\WindowsPowerShell\Modules\Microso
                         ftTeams\4.3.0\MicrosoftTeams.psd1 might have been changed by an unautho
                         rized user or process, because the hash of the file does not match the
                         hash stored in the digital signature. The script cannot run on the spec
                         ified system. For more information, run Get-Help about_Signing.

Please, re-apply a signature for the file.

**Comment by pbafna03** [comment]
Hi @MrDmig, 

Can you please try with the 4.3.1-preview release? 

Also, what's the locale set in the machine giving this error?

Thanks,

**Comment by MrDmig** [comment]
Hi @pbafna03,

4.3.1-preview works well for me. I've successfully updated the module by the "Update-Module" cmdlet with "-AllowPrerelease" parameter. I double checked the MicrosoftTeams.psd1 file with the Get-AuthenticodeSignature cmdlet and there was a valid signature. 
I don't think that locale settings affect that behavior. Anyway, there is "ru-Ru" locale. 

Best regards.

**Comment by yogkumgit** [comment]
@MrDmig Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
