### ISSUE TITLE
Get-CsOnlineUser   issue

### ISSUE THREAD

**Issue by bbteam17** [MicrosoftDocs/office-docs-powershell#9427]
Hi everyone,

my env:

![envInfo](https://user-images.githubusercontent.com/32478068/168264472-4321dd21-12c8-4105-af80-0c8865a592d1.png)

try to Search all Assigned Number via Get-CsOnlineUser , but result  could not contain all number    

a user  assigned with  ...3516 but the number   is not   in  the  full list .

![result](https://user-images.githubusercontent.com/32478068/168268881-d3da3a1d-7e5b-4210-a8bb-1cc79855ac70.png)

any idea  about this case  ?

**Comment by isrumnon** [comment]
@bbteam17 my team will look into it and get back to you on this

**Comment by bbteam17** [comment]
Hi @isrumnon   I cant find your  name in Teams or anywhere  please sent to me  a mail then I will share all information with you .
thx . bbteam17@gmail.com

**Comment by bbteam17** [comment]
@isrumnon  I wrote in  Teams    tenantId and user identity . 
thx

**Comment by yogkumgit** [comment]
@isrumnon

**Comment by yogkumgit** [comment]
@isrumnon Kindly update. Thanks

**Comment by isrumnon** [comment]
@bbteam17 we've created a bug for this and will look into it in the near furure

**Comment by yogkumgit** [comment]
@bbteam17 Thank you very much for your kind feedback. Considering your valuable feedback, as mentioned it is listed as future work item. Concerning team will evaluate and take the appropriate action, as per their schedule. Here we are limited to documentation fixes and improvements only. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
