### ISSUE TITLE
get-recipientpermission requires the mail recipients admin role to see it

### ISSUE THREAD

**Issue by arkayenro** [MicrosoftDocs/office-docs-powershell#9428]
get-recipientpermission requires the mail recipients admin role to see/use it, not the reader type roles, so global reader and view-only users cannot see these (send-as) permissions without us giving them significantly more access than they should have.

they can see full-access, send on behalf, and folder permissions, with global reader, just not send-as because of this

is there a reason you need need to give someone significantly more access than necessary to read these permissions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c48b1ec-0c52-da92-9151-d8f8f783254d
* Version Independent ID: 99320675-7f03-1201-fe5b-245221a61be1
* Content: [Get-RecipientPermission (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-recipientpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-RecipientPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-RecipientPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@arkayenro, it is a bit odd that Get-RecipientPermission isn't available in a read/view only role (like View-Only Organization Management).

But, all we do here is fix documentation. You should open a support ticket and explain the problem. That will get the issue in front of the people who can fix it.

**Comment by arkayenro** [comment]
sorry about that, will use the support channel.
