### ISSUE TITLE
Cant Assign Number BadRequest Telephone Number '+xxx55502600' has already been assigned to another user

### ISSUE THREAD

**Issue by darwincr** [MicrosoftDocs/office-docs-powershell#9432]
Cant assign a phone number, no matter what i do i get this error

**Set-CsPhoneNumberAssignment -Identity $Object.ObjectId -PhoneNumber +xxx55502600 -PhoneNumberType DirectRouting**

BadRequest Telephone Number '+xxx55502600' has already been assigned to another user

if i do a **Get-CsPhoneNumberAssignment -PhoneNumber +xxx55502600** i get this

TelephoneNumber         : +xxx55502600
NumberType              : DirectRouting
ActivationState         : Activated
AssignedPstnTargetId    : c29b96ec-0d16-4a08-a9a1-e8b93cbd3ab1
Capability              : {ConferenceAssignment, VoiceApplicationAssignment, UserAssignment}
CivicAddressId          : 00000000-0000-0000-0000-000000000000
IsoCountryCode          : 
LocationId              : 00000000-0000-0000-0000-000000000000
LocationUpdateSupported : True
PortInOrderStatus       : 
PstnAssignmentStatus    : VoiceApplicationAssigned
PstnPartnerId           : 
PstnPartnerName         : 

But i cant find any user  or resource account that is assigned this number
'c29b96ec-0d16-4a08-a9a1-e8b93cbd3ab1' -in (Get-CsOnlineUser -ResultSize 2147483647).Identity
'c29b96ec-0d16-4a08-a9a1-e8b93cbd3ab1' -in (get-CsOnlineApplicationInstance -ResultSize 2147483647).ObjectId

I have no idea what object id 'c29b96ec-0d16-4a08-a9a1-e8b93cbd3ab1'  is

**Comment by JensTrier** [comment]
@darwincr I think the best approach is for you to open a Microsoft support case and they will work with you to sort out what's going on here.

**Comment by yogkumgit** [comment]
@darwincr Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by miklak101** [comment]
I'm having this exact same issue, has Microsoft resolved your issue yet?

**Comment by JensTrier** [comment]
@miklak101 please open a Microsoft support case and they will work with you to solve this.

**Comment by miklak101** [comment]
we opened our case two days ago, I was just checking here to see if there was a known fix yet so that the Microsoft engineer working on our case might have something to refer to.

**Comment by JensTrier** [comment]
Sorry to hear it is taking so long time. Please tell the support engineer to escalate the case, if not already done.

**Comment by yogkumgit** [comment]
@darwincr Do you have any input to update the documentation with? Thanks

**Comment by yogkumgit** [comment]
@darwincr We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by wwodzien** [comment]
I just had this issue, had a number assigned to what looked like old auto attendant for EXO UM (not sure how the porting team at MS was able to see this resource account, I could not, just saw that the number was assigned to an identity GUID I could not find).  MS porting team opened an internal ticket with MS support and somehow wacked the stale entry.
