### ISSUE TITLE
"Exchange" link at top is a 404

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/office-docs-powershell#944]
The link is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b640892-b0a1-4f20-1e25-fe5f0e97f5b6
* Version Independent ID: 51774b36-90fa-1d9a-5800-1a54d9f70590
* Content: [Get-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailbox?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Get-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@chrisweis, currently, all Exchange cmdlet reference topics are grouped together under a single 'Exchange' moniker. That may or may not change, but we're definitely working on a mechanism that allows you to select an Exchange version (2010, 2013, 2016, Exchange Online, Office 365 Security & Compliance Center, or Exchange Online Protection) that filters the list of cmdlets based on your selection. Once we get that worked out, I'm pretty sure the link would start working.

But, even if the link was working, it won't take you anywhere interesting; you are effectively at the final destination that would be provided by the link.

In the Skype PowerShell cmdlet reference topics, if you click on the corresponding 'Skype' link at the top of a cmdlet ref topic (for example, in https://docs.microsoft.com/powershell/module/skype/add-cssladelegates), it simply takes you to the top of the Skype cmdlet reference node (https://docs.microsoft.com/powershell/module/skype/).

That link is likely a requirement of the repo, but doesn't provide anything interesting in our implementation. Exchange is further complicated by the fact that 500+ cmdlet reference topics are shared between the various flavors of on-premises Exchange Server and the cloud-based services, yet we need to only have one version of the topic for sanity's sake.

Thanks for the feedback.

**Comment by dariomws** [comment]
The Exchange module link issue was fixed this week. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
