### ISSUE TITLE
identity value

### ISSUE THREAD

**Issue by arkayenro** [MicrosoftDocs/office-docs-powershell#9452]
for exchange online

the biggest issue with using alias\name as the Identity is that it will fail (matches multiple entries) if a soft deleted object with that same alias exists in your tenant - the name part will not matter.

eg a soft deleted mailbox from and old user who had an alias of fred.smith will double up with an active mailbox for new user who now has the alias fred.smith

if you use the RequestGuid value from the Get-MailboxImportRequest it will always work and bypasses whatever is causing it to check for the double ups

would it be possible to include something about this under the -Identity section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e426cd63-051f-6602-d04d-428902095b0d
* Version Independent ID: 4ec6d2ad-2afe-4a4d-9b02-48291e606bcc
* Content: [Get-MailboxImportRequestStatistics (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailboximportrequeststatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailboxImportRequestStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-MailboxImportRequestStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
OK. I added this:

**Note**: In Exchange Online, the alias of a soft-deleted mailbox might match the alias of an active mailbox. To ensure uniqueness, use the RequestGuid value from the output of the Get-MailboxImportRequest cmdlet for the value of this parameter.

If you want to improve it, you can do it directly after it publishes (after you see it in the topic). For instructions, see [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
