### ISSUE TITLE
Simpler Examples

### ISSUE THREAD

**Issue by Arne-RFA** [MicrosoftDocs/office-docs-powershell#9454]
[Enter feedback here]

https://docs.microsoft.com/en-us/powershell/module/exchange/remove-mailboxrepairrequest?view=exchange-ps#example-1
Get-MailboxDatabase -Identity "EXCH-MBX-01" | Get-MailboxRepairRequest | Remove-MailboxRepairRequest
A simpler form would be  
Get-MailboxRepairRequest -Database "EXCH-MBX-01"  | Remove-MailboxRepairRequest"

https://docs.microsoft.com/en-us/powershell/module/exchange/remove-mailboxrepairrequest?view=exchange-ps#example-2
Get-MailboxDatabase -Identity "EXCH-MBX-02" | Get-MailboxRepairRequest | Format-List Identity
A simpler form would be  
Get-MailboxRepairRequest -Database "EXCH-MBX-02"  |  Format-List Identity

I leave example-3 as an exercise for the Microsoft author

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb90d652-6389-b81d-ee92-147fbe6e2607
* Version Independent ID: 5ccfedb4-f815-bcae-5a47-196c8577f454
* Content: [Remove-MailboxRepairRequest (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/remove-mailboxrepairrequest?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-MailboxRepairRequest.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Remove-MailboxRepairRequest.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Arne-RFA, fixed as you described.

In the future, you too can make updates like this yourself without opening a GitHub issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md>.

Thanks for the feedback.

Closing
