### ISSUE TITLE
Which Module version to run against  GCCH Environment 

### ISSUE THREAD

**Issue by ckarawani** [MicrosoftDocs/office-docs-powershell#9459]
There is missing specific documentation around which versions of TPM are supported for GCCH environments. 

For example, seems we cannot use 4.0.0 or up on GCCH yet?

```
Connect-MicrosoftTeams -TeamsEnvironmentName TeamsGCCH
```

Returns the following Error:

```
Message        : Invalid Teams Environment name for Migration API
ParamName      :
TargetSite     : Void setMigrationEndPoint(System.String, Microsoft.TeamsCmdlet
                 s.Powershell.Connect.Models.AzureEnvironment)
Data           : {}
InnerException :
HelpLink       :
Source         : Microsoft.TeamsCmdlets.PowerShell.Connect
HResult        : -2147024809
StackTrace     :    at Microsoft.TeamsCmdlets.Powershell.Connect.Models.TeamsEn
                 vironment.setMigrationEndPoint(String teamsEnvironmentName,
                 AzureEnvironment azureEnvironment)
                    at Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicroso
                 ftTeams.BeginProcessing()
```

Is there somewhere documenting the max version that can be used for GCCH Environments?

**Comment by pbafna03** [comment]
Hi @ckarawani, 

Will get the error checked, however irrespective of that are you able to run the cmdlets (which are not migration related)?

**Comment by ckarawani** [comment]
hello @pbafna03, yes the session still initializes and cmdlets are returning correctly as you suspected. 
I wasn't sure if GCCH is supported or not on later TPM versions given it works despite this error being thrown.

**Comment by ckarawani** [comment]
hey @pbafna03 and @pbafna03, this error is re-occuring with modules > 4.0.0 can you please add to version document what is the highest version we can run against a GCCH environment?
