### ISSUE TITLE
-Settings parameter not reserved for Microsoft

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/office-docs-powershell#9461]
This feedback applies to both New-LabelPolicy and Set-LabelPolicy cmdlets

It mentions that -Settings parameter is reserved for Microsoft. This is incorrect this is used to configure the mandatory, default and justification settings for the label policy

Full details
- Mandatory label required
- Mandatory label Power Bi
- Mandatory label with groups and site labels
- Disable mandatory label in Outlook
- Justification to downgrade
- Default labels for files
- Default label for Outlook 
- Default label for Groups and sites
- Default label for PowerB

See example

```powershell
(Get-LabelPolicy -Identity d6d59712-8daa-4d41-a7db-5ecef0cb25b8).settings
Returns
[powerbimandatory, false]
[siteandgroupmandatory, false]
[mandatory, false]
[siteandgroupdefaultlabelid, 53b33ef2-621e-4d62-a684-02365aaee0ac]
[outlookdefaultlabel, defa4170-0d19-0005-0001-bc88714345d2]
[requiredowngradejustification, true]
[defaultlabelid, defa4170-0d19-0005-0003-bc88714345d2]
[disablemandatoryinoutlook, false]
[powerbidefaultlabelid, defa4170-0d19-0005-0002-bc88714345d2]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09fce2ba-cb1a-6148-6ee7-d246711b1e68
* Version Independent ID: aadb493c-9d19-9d76-769f-a336a394e3f7
* Content: [New-LabelPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-labelpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-LabelPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-LabelPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking. I changed the Setting and Settings parameter descriptions to "reserved for internal Microsoft use" back at the end of March per product team feedback (they were previously empty).

**Comment by yogkumgit** [comment]
@chrisda Kindly update, thanks.

**Comment by chrisda** [comment]
Nothing to report.

**Comment by yogkumgit** [comment]
@chrisda Please comment. Thanks

**Comment by yogkumgit** [comment]
@chrisda if it is a known issue, can we proceed to close it. Kindly guide. Thanks

**Comment by yogkumgit** [comment]
@chrisda Please guide and suggest. Thanks

**Comment by chrisda** [comment]
@nikki-c, if you haven't already, I would highly recommend that you open a support ticket about this. By definition, if something is available in the UI, it's also available in PowerShell.
