### ISSUE TITLE
"ProxyPool" option in "Move-CsUser" is not properly described.

### ISSUE THREAD

**Issue by lyncjp** [MicrosoftDocs/office-docs-powershell#9465]
The "ProxyPool" option is described as follows, which makes it seem as if it is no longer necessary to use it.

>\-ProxyPool
This parameter has been deprecated and should not be used.  

In practice, however, it is necessary if there are multiple Edge Servers with federation enabled. Moving online without the "ProxyPool" option will fail with the following error.

>Move-CsUser : Multiple federated Edge Servers have been defined in the current topology. Specify the ProxyPool
parameter to indicate which Registrar pool should be used to proxy this user for deployments running earlier versions.
Edge Server FQDNs found:"XXXX-240edg.XXXXXXXX.local, XXXX-250edg.XXXXXXXX.local"
At line:1 char:1
\+ Move-CsUser -Identity sip:user05@XXXXXXXX.click -Target sipfed.on ...
\+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    \+ CategoryInfo          : InvalidOperation: (CN=user05,OU=o...XXXXXX,DC=local:OCSADUser) [Move-CsUser], MoveUserException
    \+ FullyQualifiedErrorId : MoveError,Microsoft.Rtc.Management.AD.Cmdlets.MoveOcsUserCmdlet

This was confirmed on Skype for Business Server 2015 with the latest CU applied. Please describe an explanation that it is required for some configurations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22159e01-061b-499a-fe99-3fe19bed57e9
* Version Independent ID: 98b9a798-e232-0b2c-ee0f-857071885c1d
* Content: [Move-CsUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Move-CsUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Move-CsUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by get-itips** [comment]
Hello @lyncjp how are you?

Please note that 

> Federation can only be enabled for a single Edge pool. If you have multiple Edge pools, select one to use as the federating Edge pool.

Source https://docs.microsoft.com/en-us/skypeforbusiness/migration/configure-federation-routes-and-media-traffic

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @lyncjp Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by lyncjp** [comment]
But in this description, multiple Edges are allowed.

> If you want to deploy multiple federation Edge Server to be active concurrently (that is, not a migration scenario), verify that all federated partners are using Skype for Business Server. 
Source https://docs.microsoft.com/en-us/skypeforbusiness/migration/configure-federation-routes-and-media-traffic

**Comment by get-itips** [comment]
@lyncjp Hello how are you? That is referring to multiple edge **servers** versus multiple edge **pools**

**Comment by lyncjp** [comment]
Federate settings are per pool. The actual case where this warning appears is when federate is enabled for multiple edge pools. A single edge pool configuration containing multiple edge servers will not be warned. I thought the description was about multiple edge pools, although it describes multiple edge servers.
If each site uses a different SIP domain, I don't see a problem with having a federated edge pool for each site.

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
@lyncjp how are you? To clarify, in your scenario, you have 1 edge pool with multiple edge servers, right?

**Comment by get-itips** [comment]
Hello @lyncjp could you see my last question here?

I managed to contact the product team about this, and they suggest to open a support request, as the message you received while trying to use Move-CsUser **is not expected** and something specific to your scenario _might_ be causing this. 
If, as a result of opening the case, any improvement to the article is required, I'll be proposing it.

**Comment by shivtorov** [comment]
@get-itips , in all production deployments customers always have at least two central sites. Each site includes at least one Front End pool and one Edge pool. In most cases, both Edge pools enabled for federation (to provide automatic DR capability)

In all my SFBS-to-Teams migration projects, I have to use `ProxyPool` param

**Comment by lyncjp** [comment]
@get-itips Sorry to late. 
> how are you? To clarify, in your scenario, you have 1 edge pool with multiple edge servers, right?
No, multiple edge pool in topology.

**Comment by get-itips** [comment]
@lyncjp I see, please see my comment [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/9465#issuecomment-1176239714) as the product team confirmed that the federation path should be unique.
I also worked in several deployments and I understand that scenario can show up, I am not sure if this changed recently, unfortunately I do not have right now such a lab. If you open the support request and as a result a documentation change is required, I'll be happily doing it.
Thank you
