### ISSUE TITLE
MicrosoftTeams PowerShell module version 4.2.0 - get-csonlineuser and grant-csteamsmeetingbroadcastpolicy cmdlets in PowerShell ISE do not autocomplete "-erroraction", but it does seem to work

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/office-docs-powershell#9466]
previous versions supported erroraction parameter [didn't record which version]

In PowerShell ISE, try
`try {$TeamsUser = Get-CsOnlineUser -Identity doesnotexist@contoso.onmicrosoft.com -erroraction stop}catch{"not found"}`

The command appears to work - it only enters the "catch" statements when it should - but PowerShell ISE does not offer autocomplete for the erroraction parameter.

**Comment by get-itips** [comment]
Hello @anwarmahmood1 I could autocomplete ErrorAction if I type "-Er" for example, hope this information helps you, as here we are limited to documentation fixes.
