### ISSUE TITLE
Need solution for clients with large user base

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#9468]
We have a client that has approximately 180K users.  When issuing this command, sometimes it takes 3 1/2 hours to complete, for only 33K corresponding users.  Is there a plan to implement the -Skip -Top parameters for this cmdlet also?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a78c07b-1a7e-b36c-e3c1-8e610638ff79
* Version Independent ID: 02174a2a-5102-5479-f72f-c9bf0691bf9b
* Content: [Get-CsOnlineDialInConferencingUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @sarollins 
Thanks for your feedback, here, we are limited to documentation fixes and improvements, I'll try to pass this feedback on.
Thanks again,

**Comment by yogkumgit** [comment]
@sarollins Thank you very much for your kind feedback. As mentioned issue is reported to PG.  Concerning team will evaluate and take the appropriate action, as per their schedule. Here we are limited to documentation fixes and improvements only. We proceed here to close it. Thanks again for taking out some time and sharing your feedback
