### ISSUE TITLE
 Descrption missing for -ShareRootPath Paramter

### ISSUE THREAD

**Issue by samrajcse** [MicrosoftDocs/office-docs-powershell#9469]
I am trying to export the PST via Compliance Powershell command. I am looking for help and don't see any documentation. Please update  [-ShareRootPath <String>] Parameter description.
If I am using this command,
New-ComplianceSearchAction -SearchName "Sam-Test1" -ShareRootPath \\172.31.102.55\share

Error message:
A parameter cannot be found that matches parameter name 'ShareRootPath'.
    + CategoryInfo          : InvalidArgument: (:) [New-ComplianceSearchAction], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotF

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad8adee-7f9d-757b-2069-95ecab232747
* Version Independent ID: c71194df-8f65-15aa-3ed2-b370b8c3f629
* Content: [New-ComplianceSearchAction (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearchaction?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by samrajcse** [comment]
Hi @chrisda ,
I am running against the 2019 Exchange Onprem server and I am getting this error. I have provided Exchange Subsystem Permission to share as well.

**Comment by chrisda** [comment]
@samrajcse, I checked on my Exchange 2019 CU12 May22SU  build, and that parameter is available to me. Using the procedures in [this topic](https://docs.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions#use-powershell-to-find-the-permissions-required-to-run-a-cmdlet):

```powershell
[PS] C:\>$Perms = Get-ManagementRole -Cmdlet New-ComplianceSearchAction -CmdletParameters ShareRootPath
[PS] C:\>$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleA
ssigneeType,RoleAssigneeName}

Role           RoleAssigneeType RoleAssigneeName
----           ---------------- ----------------
Mailbox Search        RoleGroup Discovery Management
Mailbox Search             User Exchange Online-ApplicationAccount
Mailbox Search        RoleGroup Organization Management
```

It appears the Mailbox Search role gives access to that parameter, and the **Discovery Management** and **Organization Management** role groups have that role assigned.

So are you a member of either of those role groups?

**Comment by chrisda** [comment]
Correction: The Mailbox Search role is NOT assigned to Organization Management by default; it's ONLY assigned to Discovery Management. That's likely why you can't use the parameter. Add yourself to Discovery Management or add the Mailbox Search role to Organization Management, then logoff and log back on.

**Comment by yogkumgit** [comment]
@samrajcse Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
