### ISSUE TITLE
Confirmation on Get-EXO... cmdlets

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/office-docs-powershell#9472]
Hello,

In reviewing the output of some of the Get-EXO... cmdlets, they do not retrieve the same amount of data as the original cmdlets - like "Get-Mailbox" or "Get-Recipient".

Is there a plan to add parity for each of the new cmdlets to provide the correct configuration/values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SeanTGeoghegan, I suggest you ask your question at the EXO V2 module support alias:

exocmdletpreview[at]service[dot]microsoft[dot]com

Get-Mailbox probably has 200+ properties in its output, many of which have no corresponding configuration parameter in New-Mailbox or Set-Mailbox.

**Comment by yogkumgit** [comment]
@SeanTGeoghegan Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
