### ISSUE TITLE
Policy Authority Not Returned in GCCH Environment when performing Get-CsOnlineUser

### ISSUE THREAD

**Issue by ckarawani** [MicrosoftDocs/office-docs-powershell#9476]
There seems to be missing documentation around the different response structure when performing a `Get-CsOnlineUser` on Commercial vs GCCH Environment. 

These changes look like they were introduced in TPM 4 and up. 

In a Commercial Environment, getting a user's policies returns the policy as an object that contains both the `name` and `Authority`

>**NOTE:** Actual values below have been changed and are not real production values.. 

`Get-CsOnlineUser -Identity 'ckarawani@contoso.com' | Select EnterpriseVoiceEnabled, LineUri, TenantDialPlan, TeamsCallingPolicy, OnlineVoiceRoutingPolicy, TeamsEmergencyCallingPolicy, TeamsEmergencyCallRoutingPolicy | ConvertTo-Json`

Notice in **Commercial** Policies are returned as objects containing Authority/Name Pair:

```JSON
{
  "EnterpriseVoiceEnabled": true,
  "LineUri": "tel:+1514444444;ext=444",
  "TenantDialPlan": {
    "Authority": "Tenant",
    "Name": "NA Dial Plan"
  },
  "TeamsCallingPolicy": {
    "Authority": "Host",
    "Name": "AllowCallingPreventForwardingtoPhone"
  },
  "OnlineVoiceRoutingPolicy": {
    "Authority": "Tenant",
    "Name": "Intl"
  },
  "TeamsEmergencyCallingPolicy": {
    "Authority": "Tenant",
    "Name": "ZIRO Emergency CallingPolicy"
  },
  "TeamsEmergencyCallRoutingPolicy": {
    "Authority": "Tenant",
    "Name": "ZIRO Call Routing Policy"
  }
}
```

Whereas in a GCCH Environment, the same command will return the Policies as **strings**:

Ex:

```JSON
{
  "EnterpriseVoiceEnabled": true,
  "LineURI": "tel:+1666666666"
  "TenantDialPlan": "NorAm-TenantDialPlan",
  "TeamsCallingPolicy": null,
  "OnlineVoiceRoutingPolicy": "UnRestricted",
  "TeamsEmergencyCallingPolicy": null,
  "TeamsEmergencyCallRoutingPolicy": null
}
```

**Comment by yogkumgit** [comment]
@isrumnon Kindly update. Thanks

**Comment by yogkumgit** [comment]
@ckarawani Hope this is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
