### ISSUE TITLE
Get-CsOnlineUser -Filter command doesn't work in MS Teams PowerShell

### ISSUE THREAD

**Issue by RG9900** [MicrosoftDocs/office-docs-powershell#9478]
Below commands used to work for me in MS Teams PowerShell in Feb 2022 and it's not working any longer. I never understand why Microsoft makes things harder rathan than making it easy? I've updated MS Teams module to 4.3.0 and trying to run the same command but throws me error. Can anyone advise how can I make these commands working?

# Get List of all active users in my domain who do NOT have FederationAndPICDefault policy 

Get-CsOnlineUser -Filter {UserPrincipalName -like "*@mydomain.gov.sg" -and Enabled -eq $True -and ExternalAccessPolicy -ne "FederationAndPICDefault"} | Select UserPrincipalName, SipAddress, Alias, ExternalAccessPolicy | Export-Csv C:\TEMP\AllUsersWhoDoNotHaveFederationandPICDefault_27052022.csv

# Get List of all active users in my domain who have FederationAndPICDefault policy only

Get-CsOnlineUser -Filter {UserPrincipalName -like "*@mydomain.gov.sg" -and Enabled -eq $True -and ExternalAccessPolicy -eq "FederationAndPICDefault"} | Select UserPrincipalName, SipAddress, Alias, ExternalAccessPolicy,  | Export-Csv C:\TEMP\AllUsersExternalAccessPolicyasGlobal_28Feb2022v2.csv

Can anyone test this in your environment (just replace @mydomain.gov.sg with your domain name).  

Thanks

**Comment by isrumnon** [comment]
Hi @RG9900 we currently do not support 'ends with' with UserPrincipalName i.e., Get-CsOnlineUser -Filter UserPrincipalName -like "*@mydomain.gov.sg" 
Instead, can you consider using one of the below approaches:
1. Use Company filter: Get-CsOnlineUser -Filter Company -like "*abcCompany" 
2. Alternative query to the one you were using:
$users = Get-CsOnlineUser -Filter {AccountEnabled -eq $True -and ExternalAccessPolicy -ne 'FederationAndPICDefault'} | Select UserPrincipalName, SipAddress, Alias, ExternalAccessPolicy, TeamsUpgradeEffectiveMode, Description, City, Office, PostalCode, StreetAddress, Phone
$users | Where-Object {$_.UserPrincipalName -like "*@mydomain.gov.au"} 
| Export-Csv C:\TEMP\AllUsersWhoDoNotHaveFederationandPICDefault_27052022.csv

**Comment by RG9900** [comment]
Let me clarify and be more specific. 

We have two domains. Domain1 has 200K users. Domain2 has 800K users. Both domains fall under same Tenant. 

All domain1 users are SfB On-Prem users, they are in Island mode and they do have Teams account. All domains2 users are Teams-Only mode users, no SfB On-Prem accounts. So we are in a Hybrid environment. 

Most users in Domain1 are having 'FederationAndPICDefault' policy. However some users have different policies other than 'FederationAndPICDefault'. All Domain1 users should have 'FederationAndPICDefault' policy. So the aim is to find out those Domain1 users who do not have 'FederationAndPICDefault' policy and move them onto 'FederationAndPICDefault' policy to streamline. So the first step is to find them out. That’s where the issue is. 

Now, we can’t use where-object command as we have about one million objects in AD in total. We have no choice but to use Filter command for faster results. 

In another words, I can’t use below command, as it would query and filter from 1 million objects. 

$users = Get-CsOnlineUser -Filter {AccountEnabled -eq $True -and ExternalAccessPolicy -ne 'FederationAndPICDefault'}

That is why I was doing Get-CsOnlineUser -Filter {UserPrincipalName -like "*@mydomain1.gov.sg" -and Enabled -eq $True -and ExternalAccessPolicy -ne "FederationAndPICDefault"}

Basically, I like to get list of all users in Domain1 who are active users (not terminated accounts) and who do NOT have FederationAndPICDefault policy. How can I get the list. Can you provide me query for that?


For Domain2 users (800K), all users should be on ‘NoFederationAndPIC’ policy. However there are some users who are having some other type of policy. So we like to get a list of those domain2 users, that way we can then streamline them too and assign them onto ‘NoFederationAndPIC’ policy.  

So, I like to get list of all users in Domain2 who are active users (not terminated accounts) and who do NOT have ‘NoFederationAndPIC’ policy. How can I get the list. Can you provide me query for that?

I do not understand your comments…  Can you clarify?  “we currently do not support 'ends with' with UserPrincipalName i.e., Get-CsOnlineUser -Filter UserPrincipalName -like "[*@mydomain.gov.sg](mailto:*@mydomain.gov.sg)" ….”

Sorry, I do not understand this either, Get-CsOnlineUser -Filter Company..?   I tried to Google “Get-CsOnlineUser -Filter Company” but I don’t find such parameter. 

Below command was working beautifully, why it is not working now?

Get-CsOnlineUser -Filter {UserPrincipalName -like "*@mydomain1.gov.sg" -and Enabled -eq $True -and ExternalAccessPolicy -ne "FederationAndPICDefault"} | Select UserPrincipalName, SipAddress, Alias, ExternalAccessPolicy | Export-Csv C:\TEMP\AllUsersWhoDoNotHaveFederationandPICDefault_27052022.csv


Thanks

**Comment by RG9900** [comment]
Let me clarify and be more specific.

We have two domains. Domain1 has 200K users. Domain2 has 800K users. Both domains fall under same Tenant.

All domain1 users are SfB On-Prem users, they are in Island mode and they do have Teams account. All domains2 users are Teams-Only mode users, no SfB On-Prem accounts. So we are in a Hybrid environment.

Most users in Domain1 are having 'FederationAndPICDefault' policy. However some users have different policies other than 'FederationAndPICDefault'. All Domain1 users should have 'FederationAndPICDefault' policy. So the aim is to find out those Domain1 users who do not have 'FederationAndPICDefault' policy and move them onto 'FederationAndPICDefault' policy to streamline. So the first step is to find them out. That’s where the issue is.

Now, we can’t use where-object command as we have about one million objects in AD in total. We have no choice but to use Filter command for faster results.

In another words, I can’t use below command, as it would query and filter from 1 million objects.

$users = Get-CsOnlineUser -Filter {AccountEnabled -eq $True -and ExternalAccessPolicy -ne 'FederationAndPICDefault'}

That is why I was doing Get-CsOnlineUser -Filter {UserPrincipalName -like "*@mydomain1.gov.sg" -and Enabled -eq $True -and ExternalAccessPolicy -ne "FederationAndPICDefault"}

Basically, I like to get list of all users in Domain1 who are active users (not terminated accounts) and who do NOT have FederationAndPICDefault policy. How can I get the list. Can you provide me query for that?

For Domain2 users (800K), all users should be on ‘NoFederationAndPIC’ policy. However there are some users who are having some other type of policy. So we like to get a list of those domain2 users, that way we can then streamline them too and assign them onto ‘NoFederationAndPIC’ policy.

So, I like to get list of all users in Domain2 who are active users (not terminated accounts) and who do NOT have ‘NoFederationAndPIC’ policy. How can I get the list. Can you provide me query for that?

I do not understand your comments… Can you clarify? “we currently do not support 'ends with' with UserPrincipalName i.e., Get-CsOnlineUser -Filter UserPrincipalName -like "[*@mydomain.gov.sg](mailto:*@mydomain.gov.sg)" ….”

Sorry, I do not understand this either, Get-CsOnlineUser -Filter Company..? I tried to Google “Get-CsOnlineUser -Filter Company” but I don’t find such parameter.

Below command was working beautifully, why it is not working now?

Get-CsOnlineUser -Filter {UserPrincipalName -like "*@mydomain1.gov.sg" -and Enabled -eq $True -and ExternalAccessPolicy -ne "FederationAndPICDefault"} | Select UserPrincipalName, SipAddress, Alias, ExternalAccessPolicy | Export-Csv C:\TEMP\AllUsersWhoDoNotHaveFederationandPICDefault_27052022.csv

Thanks

**Comment by isrumnon** [comment]
Hi @RG9900 thanks for the explanation and helping understand your issue better. Unfortunately filtering based on UserPrincipalName using the wildcard operator (*) at the beginning of the value (this is what I meant by 'ends with') is currently not supported in TPM versions 3 and above. 
Can you please contact me on email or Teams so we can walk you through some of our mitigation options?

**Comment by RG9900** [comment]
Hi Isaiah,

I received your comments in my email from notifications@github.com, not from you. Could you please provide me your email ID where I can reply to you directly. I don't want to reply from my email to notifications@github.com or mention@noreply.github.com

Thanks

**Comment by RG9900** [comment]
We are in agreement on a short and longer term solution.
