### ISSUE TITLE
Get-CsOnlineUser -LdapFilter swallowing LineUri

### ISSUE THREAD

**Issue by ssteiner** [MicrosoftDocs/office-docs-powershell#9479]
I'm using `Get-CsOnlineUser` commandlet with the `-LdapFilter` parameter. 
And I noted that all of a sudden (I could've sworn this wasn't the case last week), not all my users that have a `LineUri` have it returned.

If I extract the users that have an empty `LineUri` when I use `-LdapFilter` one by one (so `Get-CsOnlineUser -Identity upn-of-user`), they do have the LineUri filled out.

So why is the PS Module (I'm using 4.3.0) suddenly not returning the LineUri? In the Teams Admin Console, all users that have a number show up with the number.

**Comment by yogkumgit** [comment]
@ssteiner Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
