### ISSUE TITLE
Missing semi-colon in Example 2

### ISSUE THREAD

**Issue by clamb123** [MicrosoftDocs/office-docs-powershell#9481]
Missing a ; in example 2, should be

Set-ResourceConfig -ResourcePropertySchema @{Add="Room/TV"**;**Remove="Equipment/Laptop"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79e6173e-1c0a-6877-91f6-c99b099f5c0b
* Version Independent ID: ec6499aa-971b-f252-afda-2561496b80da
* Content: [Set-ResourceConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-resourceconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-ResourceConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-ResourceConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@clamb123, fixed.

In the future, you too can make updates like this directly in the topic. No need to open a GitHub Issue first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
