### ISSUE TITLE
Sync-CsOnlineApplicationInstance cmdlet is currently returning an issue "An item with the same key has already been added." 

### ISSUE THREAD

**Issue by juniorccs** [MicrosoftDocs/office-docs-powershell#9494]
[Enter feedback here]
When executing this command, now we see a message "An item with the same key has already been added." 
I am not if it's related to the Teams Module version 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e18f62f-cdb9-a279-146a-ccd65f879799
* Version Independent ID: 4b3dd955-71e5-c849-ab94-1f8a8f46d587
* Content: [Sync-CsOnlineApplicationInstance (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/sync-csonlineapplicationinstance?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Sync-CsOnlineApplicationInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Sync-CsOnlineApplicationInstance.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @xixian73
* Microsoft Alias: **xixian**

**Comment by get-itips** [comment]
Hello @juniorccs how are you?
The best in your scenario would be to open a support ticket from your tenant, as here we are limited to documentation fixes.
Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @juniorccs Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
