### ISSUE TITLE
Teams module 4.4.1: Get-CsAutoAttendantHolidays shows DateTimeRanges as empty

### ISSUE THREAD

**Issue by ruudvanstrijp** [MicrosoftDocs/office-docs-powershell#9500]
I am using MicrosoftTeams module 4.4.1 and I notice Get-CsAutoAttendantHolidays always seems to return the 'DateTimeRanges' as empty. I have tried it with three types of date ranges:
- 1 day holiday without specific times (12.00AM 2/6/2022 - 12.00AM 3/6/2022)
- 2 day holiday without specific times (12.00AM 2/6/2022 - 12.00AM 4/6/2022)
- 1 day holiday with specific times (2.00AM 2/6/2022 - 9.00PM 2/6/2022)

All of these show up empty:
PS C:\GitHub\PowerShell-Scripts> Get-CsAutoAttendantHolidays 21eaca4d-0a11-xxxx-xxxx-xxxxxxxxx
WARNING: All date-time range bounds are listed in 'dd/MM/yyyy HH:mm' format.

Year           : 2022
Name           : 2jun
DateTimeRanges :
Greetings      : TextToSpeechPrompt=2-3 jun closed
CallAction     : Action=DisconnectCall

I haven't tested this command with any older modules, so I don't know if this used to work in earlier versions or not.

**Comment by JensTrier** [comment]
@ruudvanstrijp They are there, but you need to explicitly look at them like in the 2 examples below

`PS 02-06-2022 09:36:20 C:\> (Get-CsAutoAttendantHolidays -Identity a780e9b0-dc93-4977-83a0-418d312c9e03).DateTimeRanges
WARNING: All date-time range bounds are listed in 'dd/MM/yyyy HH:mm' format.

Start : 03-06-2022 00:00
End   : 07-06-2022 00:00

PS 02-06-2022 09:36:35 C:\> $holiday=Get-CsAutoAttendantHolidays -Identity a780e9b0-dc93-4977-83a0-418d312c9e03
WARNING: All date-time range bounds are listed in 'dd/MM/yyyy HH:mm' format.
PS 02-06-2022 09:37:06 C:\> $holiday.DateTimeRanges

Start : 03-06-2022 00:00
End   : 07-06-2022 00:00

PS 02-06-2022 09:37:12 C:\>
`

Feel free to close this issue, if above is fine.

**Comment by ruudvanstrijp** [comment]
Thanks for your fast response! I'm happy to see this isn't a bug, but it's working by design.
Would it be possible to update the documentation at https://docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantholidays?view=skype-ps explaining this behavior?

**Comment by yogkumgit** [comment]
@JensTrier

**Comment by JensTrier** [comment]
@ruudvanstrijp thanks for the suggestion.

@yogkumgit not my area, but I've made the change in one of my upcoming PR's.

**Comment by yogkumgit** [comment]
@ruudvanstrijp Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
