### ISSUE TITLE
New-ComplianceSearch - just the hard way of doing work

### ISSUE THREAD

**Issue by ChrisNic817** [MicrosoftDocs/office-docs-powershell#9509]
Searching a single mailbox using this PowerShell command is convoluted and ridiculous.
The Compliance methods are not designed around actually searching individual mailboxes or working with small data sets like searching mailboxes.   

The split should be reinitialized and put Search-Mailbox back into the environment so one mailbox can be searched and use Compliance Searches for true and real data set style searches.   When it takes me days to figure out how to do a simple search of a mailbox for a specific email because the search method is too complex to be setup quickly it is a tool that has no real value.

If I need to do a Compliance Search for legal purposes for many mailboxes across my organization then I will dig into this tool but for a quick search of a specific mailbox this is just too much work.    I don't know who made this decision or who is thinking this is a good thing just never has worked on the smaller side.

**Comment by chrisda** [comment]
@ChrisNic817, you should open a support ticket about this. All we can do here is fix documentation.

**Comment by yogkumgit** [comment]
@ChrisNic817 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
