### ISSUE TITLE
Grant-TeamsRecorderPolicy error Invalid input parameters forest

### ISSUE THREAD

**Issue by ThomasPerezBlanco** [MicrosoftDocs/office-docs-powershell#9519]
Hello,

I still have the same problem as incident  #9229 .
We use European servers, the correction has been deployed on our servers?
Additional Info: I'm using module version 4.4.1.

Thanks.

Cordially,

Thomas PEREZ.

**Comment by AllStarzes** [comment]
Same here! After Update the module of version 4.4.1 `New-CsTeamsMeetingPolicy : Invalid input parameters missing X-MS-Forest header`

**Comment by j-hinks** [comment]
having similar issues on this side with New-CsTenantDialPlan, Grant-CsTeamsComplianceRecordingPolicy and Get-CsOnlineSipDomain

**Comment by JEVNINO** [comment]
Same issue here using 4.1.0 and my colleague is using 4.2.0 & tested with 4.4.1 and same issue with Grant-CsTeamsUpgradePolicy, GrantCsOnlineVoiceRoutingPolicy & Grant-CsTenantDialPlan. 

Invalid input parameters forest

**Comment by sbusst** [comment]
I have the same issue with:
Grant-CsTeamsComplianceRecordingPolicy
New-CsTenantDialPlan
Get-CsOnlineSipDomain
It's becoming urgent

**Comment by pbafna03** [comment]
@yogkumgit - you can close this one, this was resolved yesterday.
