### ISSUE TITLE
Teams PowerShell Module (4.4.1) Grant Policy Commands - Grant-CsTeamsVideoInteropServicePolicy: Invalid input parameters forest

### ISSUE THREAD

**Issue by CldEng-DT** [MicrosoftDocs/office-docs-powershell#9520]
My team is currently doing testing on the PexipCVI and they have a new team member to add and when I went to grant access to the policy like I did the others(using GA), I had issues with the cmdlets.  saw on issue 9229 very similar issues and as I was running an older version of the Teams PS module (4.0.0), I updated to 4.4.1.  cmdlets seems to work, but when I go to add the user in question (and I tried others as well), I get an error regarding invalid input parameters forest

![image](https://user-images.githubusercontent.com/95640026/172621848-78ead5e6-4944-403b-9267-132dbf577526.png)

I tried to downgrade the module to previous (4..3.0/4.2.0) versions but same issue.. with 4.1.0, i had the same api error as reported in issue 9229....  This is present from either PS 5.1 or 7.2

Any clue in how this can be resolved ?  This is the last testing phase before this is rolled out to all our users.

**Comment by justokin** [comment]
Having the exact same issue in 4.2

**Comment by rmichalskinw** [comment]
My tenant and customers are also facing this issue. I opened a Sev-A ticket and was told that the work around was to manually assign policies via the TAC. They reduced my ticket severity despite the fact that manually assigning policies to hundreds of users is not workable in the TAC.

**Comment by et01267** [comment]
Yes - no workaround in our case since we are managing voice routes for 1000s of users in 100s of tenants via delegated credentials on our servers.   Also opened Sev A case and Microsoft have acknowledged that others have done the same.

**Comment by rmichalskinw** [comment]
Issue appears to be resolved me and my customers.

**Comment by JEVNINO** [comment]
Confirmed I closed out of my PowerShell session re-launched and confirmed all is working as directed.

**Comment by ckarawani** [comment]
just curious, has anyone ever gotten any traction with 365 Support on these types of pwsh issues? I opened a ticket with them, and despite an advisory being eventually opened AND finally closed, they still never got back to me and the ticket is still open.

**Comment by rmichalskinw** [comment]
> just curious, has anyone ever gotten any traction with 365 Support on these types of pwsh issues? I opened a ticket with them, and despite an advisory being eventually opened AND finally closed, they still never got back to me and the ticket is still open.

Thankfully my company has Premier Support who have been far and away better than the typical O365 support. I got a call within 20 minutes of my ticket and then email updates ever ~30 minutes or so.

**Comment by et01267** [comment]
Yes, Premier Support lets you bypass 2 or 3 layers of drones, and you get constant (24x7) unctuous solicitations from various support engineers, case managers, and the like.   However, your problem will take just as long to get fixed, and you almost never get to talk to anyone who actually knows anything from first-hand experience with the issue (either code or devops).

**Comment by ckarawani** [comment]
thanks @rmichalskinw and @et01267 for the feedback!
