### ISSUE TITLE
Get-CSOnlinePSTNGateway, Get-CsOnlineSipDomain and Get-CsMeetingRoom don't work anymore on 4.0.0 and more

### ISSUE THREAD

**Issue by vlethiec** [MicrosoftDocs/office-docs-powershell#9521]
Hi, 

We have a lot of issues on customer tenants with the following cmdlets (not exhaustive). 

- Get-CSOnlinePSTNGateway
- Get-CsOnlineSipDomain
- Get-CsMeetingRoom

This issue appeared some hours ago and only on module 4.0.0 and more. 

Regards, 

Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572daa95-a813-8e96-6c18-23f0d84c57b7
* Version Independent ID: fe47ac10-32ad-7d48-20d2-aca82622483b
* Content: [Get-CsOnlinePSTNGateway (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/Get-CSOnlinePSTNGateway?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlinePSTNGateway.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlinePSTNGateway.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by maximonstre** [comment]
Magic
