### ISSUE TITLE
Current Exchange Online PowerShell module not completely Signed

### ISSUE THREAD

**Issue by ivassallo19** [MicrosoftDocs/office-docs-powershell#9526]
Page: https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell

Product: Exchange Online PowerShell

I'm not sure I have a way to exactly prove this.

We are operating an environment with AppLocker, and our admin accounts with an Execution Policy of AllSigned.
When using the latest ExchangeOnlineManagement module, 2.0.5, and get to running Connect-ExchangeOnline, it complains:

```
Import-PSSession : Files cannot be loaded because running scripts is disabled on this system. Provide a valid certificate with which to sign the files.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\netFramework\ExchangeOnlineManagement.psm1:484 char:40
+ ... oduleInfo = Import-PSSession $PSSession -AllowClobber -DisableNameChe ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-PSSession], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.ImportPSSessionCommand
```

Is this due to a portion of this module using scripts that aren't signed?
I would rather not resort to allowing all local scripts to run, and I understand that dealing with modules can write scripts to the User\AppData\Local\Temp location, which is a hotspot for malware.

**Comment by chrisda** [comment]
@ivassallo19, I'm not sure it's the module itself or the remote PowerShell connection element that's the culprit. It might be the remote PowerShell connection.

Even back in the 'no module' connection days (`2009 until now), you needed to do `Set-ExecutionPolicy RemoteSigned` to connect to Exchange Online PowerShell (see (here)[https://docs.microsoft.com/powershell/exchange/basic-auth-connect-to-exo-powershell#what-do-you-need-to-know-before-you-begin]).

That requirement has been carried forward to the EXO V2 module as discussed [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#prerequisites-for-the-exo-v2-module).

So, are you able to set your execution policy to RemoteSigned instead of AllSigned?

**Comment by ivassallo19** [comment]
@chrisda Thanks for the reply.
Yes it seems you are correct. Whenever Import-PSSession is invoked it displays this error.
So the problem is not with the Exchange module but with PowerShell itself.
I probably need to find another area to raise this.

But to answer your points. Although setting the policy to RemoteSigned isn't a good security practice, given the documentation states it is required, I set this policy for my machine. And now I get a different error which is related to AppLocker blocking dynamically created files stored in \AppData\Local\Temp\.

**Comment by chrisda** [comment]
@ivassallo19, yeah, the remote PowerShell session will create temporary files, and I don't think there's anything we can do about that.

Version 2.0.6-Preview6 of the module has ALL cmdlets available as REST API backed. That means you don't need to have Basic auth enabled in WinRM. All of this is explained [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#updates-for-version-206).

You can try using v2.0.6-Preivew6 and connect **without** using the UseRPSSession switch so you're using the REST API versions of the cmdlets. I doubt it will help (for example, RemoteSigned is still required), but it's worth a try.

**Comment by yogkumgit** [comment]
@ivassallo19 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
