### ISSUE TITLE
IsMemberAllowedToEditContent missing information

### ISSUE THREAD

**Issue by libach81** [MicrosoftDocs/office-docs-powershell#9527]
The command IsMemberAllowedToEditContent is missing information on what it does. Currently says {{ Fill IsMemberAllowedToEditContent Description }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80326e44-6beb-8983-57ab-8333608c504b
* Version Independent ID: 8962c0dc-72a3-208a-33de-6a89cd56b6fc
* Content: [Set-UnifiedGroup (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@libach81, empty parameter descriptions are a known issue. See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for an explanation.

So, are you just pointing out that the description is empty, or do you have other information (content, blog posts, etc.) that this parameter is alive and working?

**Comment by yogkumgit** [comment]
@libach81 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Borgquite** [comment]
@lilbach81 Could IsMemberAllowedToEditContent control the group-level setting described here? https://office365itpros.com/2022/11/14/outlook-groups-folders-rules/#Group-Level_Setting
