### ISSUE TITLE
Session Unexpectedly Expires After 1 Hour

### ISSUE THREAD

**Issue by mikemartin1090** [MicrosoftDocs/office-docs-powershell#953]
I was tasked with running a rather large script that I've seen take up to 8 hours (a modified version of https://gallery.technet.microsoft.com/office/Office-365-Mobile-Device-1523900f Office 365 Mobile Device Report). After successfully connecting using the method described above on a server that requires MFA, I noticed that after 1 hour, I was getting some errors in my logs and then around the 60 minute mark I got prompted to enter my credentials. An hour later, I was again prompted for my credentials. Is this expected?

Script started at 6:47 PM.
Script began generating this error over and over at 7:43 PM for one minute: "Starting a command on the remote server failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic."
Script prompted for my auth again at 7:45.

My main concern is that after I entered my credentials again, the script actually had skipped 137 mailboxes due to the error happening over and over. 

To get around this, I ended up using a server that has it's public IP on my conditional access IP whitelist and using the old (reliable) method:

```
$session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "https://outlook.office365.com/powershell-liveid/" -Credential $cred -Authentication Basic -AllowRedirection
Import-PSSession $session
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nsshommo** [comment]
@mikemartin1090 Thanks for your feedback and query. We are looking about this issue and will get back to you very soon.

**Comment by chrisda** [comment]
@mikemartin1090, did you use the -UserPrincipalName parameter with your account name in the Connect-EXOPSSession command? Apparently, omitting that parameter can cause the one hour timeout that you experienced.

**Comment by mikemartin1090** [comment]
@chrisda At first I did NOT have that specified, HOWEVER even when specifying, I still get the same results. 

Right at 1 hour and 4 minutes into the script, I receive the following command over and over for ~2 minutes - "Starting a command on the remote server failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic." Followed by "Starting a command on the remote server failed with the following error message : The I/O operation has been aborted because of either a thread exit or an application request. For more information, see the about_Remote_Troubleshooting Help topic." 3 times.

Then the script beings logging out correctly, and then approximately 1 hour and 4 minutes later, the exact same message pops up for ~2 minutes followed by the I/O operation message another 3 times.

Any other ideas?

**Comment by chrisda** [comment]
@mikemartin1090 is the account that your using to connect to Exchange Online PowerShell the same account that you're using to log on to your local computer and run the script? If they're different, try using the same account for both.

**Comment by chrismartell84** [comment]
Hello all, we just enabled MFA for all o365 admins and we (Exchange Admins) are suffering big time, as described before the session seems to end in about 1 hour does not matter if we are running something, in our case when we do a Search-mailbox to move high volumes of information, it fails after 1 hour and we see the session "broken", if we reconnect and run the search-mailbox again it starts from scratch. We tried login into a computer with the admin account so the same AD account is used everywhere but same problem, we also used the -UserPrincipalName param with same result.
It seems like we will need to change the Access Token Lifetime in AzureAD but I will highly prefer to have this fixed from the Exchange Module side, the old method used to work excellent! we missed it already :(

**Comment by mikemartin1090** [comment]
@chrisda I've used the same account and still no luck.

@chrismartell84 I've implemented the "Trusted IPs" [as described here](https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-mfasettings#trusted-ips) and you can still use the old-school methods of connecting while in the office. No need to turn off MFA for the admins or mess up your scripts. If you have servers in a datacenter, be sure to whitelist that public IP as well.

**Comment by moreaboutmatt** [comment]
Any news on getting over the 60 minute timeout? It's killing our PF admin scripts to add permissions to lots of folders.

**Comment by chrisda** [comment]
@moreaboutmatt, I just added the workaround (Trusted IPs) to the topic as described by @mikemartin1090 in the previous comment in the thread. Apparently, that is the only available fix at this time.

Thanks for the feedback.

**Comment by mikemartin1090** [comment]
Nice - at least people will have an idea now of why it errors out after an hour.

**Comment by Brewcmas** [comment]
@chrisda to my understanding that workaround is only for those of us that are connected to the intranet.   For those of us that connect remotely and are not connected to the intranet - this workaround doesn't work. 

Has there been any updates on this since June 12, 2018?  Or are we still going to be bogged down by the 1 Hour Time Out - causing larger scripts to have missing data chunks?

**Comment by chrisda** [comment]
@Brewcmas, you might try the script using the new PowerShell V2 module (which also supports MFA): https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.

Try your original script to see if it works as is. If not, perhaps replacing Get-Mailbox with Get-EXOMailbox and Get-MobileDeviceStatistics with Get-EXOMobileDeviceStatistics will help the script finish in under an hour and thus avoid the problem?

**Comment by jforet1** [comment]
Tried updating to 2.0.3-Preview of the ExchangeOnlineManagement module but still encounter the timeout issue. I was able to get around it in by checking the connection state inside of a loop and restoring it if it finds it in a broken state.

```ps
$username = "replaceme@contoso.com"
Connect-ExchangeOnline -UserPrincipalName $username

$mailboxes = Get-Mailbox -ResultSize:unlimited -Filter "RecipientTypeDetails -eq 'UserMailbox'"

$mailboxes | ForEach-Object {
    $connectionstatus = Get-PSSession | Where-Object {$_.ConfigurationName -like "Microsoft.Exchange"}
    if ($connectionstatus.State -ne "Opened") {
        Connect-ExchangeOnline -UserPrincipalName $username
    }
    #do stuff here
}
```

https://gist.github.com/jforet1/78eaa80136e31549346586a61dc9b949
