### ISSUE TITLE
Teams PowerShell Set-CsPhoneNumberAssignment no -WhatIf switch

### ISSUE THREAD

**Issue by keithmweaver** [MicrosoftDocs/office-docs-powershell#9530]
The Teams PowerShell command Set-CsPhoneNumberAssignment does not have a -WhatIf switch. This should be added so scripts can be tested first before committing changes.

**Comment by JensTrier** [comment]
We have added it to our backlog, but currently no ETA.

Feel free to close this issue.

**Comment by yogkumgit** [comment]
@JensTrier Thank you very much for sharing this explanation. @keithmweaver  as this is in the plan and future work item we proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by keithmweaver** [comment]
@JensTrier or @yogkumgit, any update on this?

**Comment by yogkumgit** [comment]
@keithmweaver As there is no ETA, please keep checking. Thanks for your patience.
