### ISSUE TITLE
Teams PowerShell Get-CsCallQueue fails on 4.x.x but works on 3.1.1

### ISSUE THREAD

**Issue by Maymne** [MicrosoftDocs/office-docs-powershell#9534]
We have a less privileged account which we are using to query our call center's Teams call queue, so that they have an easily visible dashboard and are more aware of when to panic. This works great with the 3.1.1 version of the module, but fails with 3.2.0-preview or any version of 4.x.x through the currently released 4.4.1. As this works fine with 3.1.1, we'd rather not grant the account more permissions and decrease our overall security.

Example with 3.1.1:
Get-CsCallQueue -verbose
VERBOSE: EnabledForFlight: False, AutoRestCommandInfo: False
VERBOSE: Correlation Id: bb78a84b-910a-4979-a48c-d201afeb1026
VERBOSE: Correlation Id: bb78a84b-910a-4979-a48c-d201afeb1026
WARNING:  ConferenceMode is turned on for this callqueue. <much text continues as queue statistics are displayed>

Example with 4.4.1:
Get-CsCallQueue -Verbose
VERBOSE: EnabledForFlight: True, AutoRestCommandInfo: True
Get-CsCallQueue: Access Denied.

Apparently something about how it works with EnabledForFlight/AutoRestCommandInfo enabled makes it fail to process and work with the queues. Is this something we can easily fix, either by disabling the EFF/ARCI or by granting some explicit permission to the account to allow it to query the queue statistics?

**Comment by Maymne** [comment]
Checked this against 4.4.3-preview and still access denied. Slightly different error, as it gives the line and doesn't note EFF/ARCI anymore.

Get-CsCallQueue -Verbose
Get-CsCallQueue_Get: USERPROFILE\Documents\PowerShell\Modules\MicrosoftTeams\4.4.3\custom\PsExt\Merged_custom_PsExt.ps1:842
Line |
 842 |          $result = Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get-CsCa …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access Denied.

**Comment by yinzh798** [comment]
Thanks for reporting this issue. We are from Microsoft Teams. Could you please go to Office 365 Admin Center portal->Users->Active Users, and see which Role is assigned to the "less privileged account"? (eg. Global Reader, Global Administrator, etc)

**Comment by Maymne** [comment]
The account is currently in the roles of Helpdesk Administrator and Teams Device Administrator.

**Comment by yinzh798** [comment]
Helpdesk Administrator was mistakenly granted permission to run Get-CsCallQueue cmdlet in the past. We have fixed this issue in the recent release. If you want less privileged account to run Get-CsCallQueue cmdlet, please assign either of these two roles to the user.

Teams Administrator
Teams Communication Administrator

**Comment by Maymne** [comment]
Ah, that makes good sense. It never made perfect sense to me why it worked, but I'll let our security team decide what they want to choose as their new available and correct options. Thanks for the response!
