### ISSUE TITLE
Password is still required to generate token?

### ISSUE THREAD

**Issue by vlethiec** [MicrosoftDocs/office-docs-powershell#9535]
Hi all, 

I have two questions/remarks regarding the connection with access token. 

1. Password still required
According to the chapter "Example 4: Connect to MicrosoftTeams using Accesstokens"
The login and password are still required for the token generation. It means our clients still need to give us the credential of the service account. Is it really relevant? Did I miss something?

2. No way to bypass the MFA with the token
When we enable the MFA, the tokens cannot be generated anymore. 

```
PS C:\WINDOWS\system32> [string]$uri = "https://login.microsoftonline.com/{0}/oauth2/v2.0/token" -f $tenantid
$body = "client_id={0}&scope=https://graph.microsoft.com/.default&username={1}&password={2}&grant_type=password&client_secret={3}" -f $clientid, $username, [System.Net.WebUtility]::UrlEncode($password), [System.Net.WebUtility]::UrlEncode($clientsecret)
$graphtoken = Invoke-RestMethod $uri -Body $body -Method Post -ContentType "application/x-www-form-urlencoded" -ErrorAction SilentlyContinue | Select-object -ExpandProperty access_token

Invoke-RestMethod : {"error":"invalid_grant","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you 
moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.\r\nTrace ID: 
37e5f527-20ee-414e-99ea-84fc408a0000\r\nCorrelation ID: 50a33e17-665d-447a-bd17-088dbb3be5ce\r\nTimestamp: 2022-06-13 
16:51:44Z","error_codes":[50076],"timestamp":"2022-06-13 16:51:44Z","trace_id":"37e5f527-20ee-414e-99ea-84fc408a0000","correlation_id":"50a33e17-665d-447a-b
d17-088dbb3be5ce","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}
At line:3 char:15
+ ... raphtoken = Invoke-RestMethod $uri -Body $body -Method Post -ContentT ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

```

How to be able to propose secure connections to our customers, with a such behavior?
Did I miss something Andrès @get-itips, I know you're good on that topic. 

Thanks for your help. 

Regards, 

Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0dce05-8bfd-0bfa-3753-0eb193852703
* Version Independent ID: 50e0366c-46b0-71da-b6f6-f422adaad785
* Content: [Connect-MicrosoftTeams (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps#example-4-connect-to-microsoftteams-using-accesstokens)
* Content Source: [teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Connect-MicrosoftTeams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @vlethiec Vincent, how are you?

Yes, currently, those are requirements.

@pbafna03 are you able to add more information on this?

Thanks

**Comment by pbafna03** [comment]
Application/SPN based authentication is also work in progress and will be available soon.

**Comment by get-itips** [comment]
> Application/SPN based authentication is also work in progress and will be available soon.

Thanks @pbafna03 for your comments
