### ISSUE TITLE
Timeframe for policy deployment is worded in a confusing way

### ISSUE THREAD

**Issue by drdenson** [MicrosoftDocs/office-docs-powershell#9542]
Hi, working with the PG on this feature, it was relayed that the time it takes for graph to see the changes take effect is incorrect.  It currently states it could take longer than 1 hour.  It should read, it could take UP TO 1 hour.  Affected line from the doc below.

https://docs.microsoft.com/graph/auth-limit-mailbox-access
Note: Changes to application access policies **can take longer than 1 hour** to take effect in Microsoft Graph REST API calls, even when Test-ApplicationAccessPolicy shows positive results.

Please confirm this update with the applicable feature owner.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a47ca7d5-2598-0c06-03fd-854f94cf6bbe
* Version Independent ID: a57408f6-16ca-3fcb-0c04-48a7a5f9942d
* Content: [New-ApplicationAccessPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-applicationaccesspolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@drdenson, I find no matches to the word "hour" anywhere in the New-ApplicationAccessPolicy topic (or any of the other \*-ApplicationAccessPolicy topics), so there's nothing to correct.

If you're asking for updates to <https://docs.microsoft.com/graph/auth-limit-mailbox-access>, you're in the wrong place.

Comments?

**Comment by chrisda** [comment]
OK. Closing.
