### ISSUE TITLE
Move-CsMeetingRoom still relevant for MTR?

### ISSUE THREAD

**Issue by vlethiec** [MicrosoftDocs/office-docs-powershell#9546]
Hi, 

For the cmdlets "Get-CsMeetingRoom", "enable-csmeetingroom", "disable-csmeetingroom" and "set-csmeetingroom", we have the following note:

"Note: This cmdlet is not supported for managing Microsoft Teams Rooms. You must use the methods described in the [Microsoft Teams Rooms](https://docs.microsoft.com/en-us/microsoftteams/rooms) documentation to manage Microsoft Teams Rooms."

But for "move-csmeetingroom", we don't have this note. I think it is an oversight, right?

Regards, 

Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a45db2f-2fe4-6ace-76ea-19dd94590b8c
* Version Independent ID: 370170a5-4ffd-bd24-d185-bab2b1f1e151
* Content: [Move-CsMeetingRoom (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/move-csmeetingroom?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Move-CsMeetingRoom.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Move-CsMeetingRoom.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by pbafna03** [comment]
Hi @vlethiec, 

Move-CsMeetingRoom cmdlet is not present in the Teams PowerShell Module and hence that note was not added for it. But yes, it is also not supported for managing Microsoft Teams Rooms. Methods mentioned in https://docs.microsoft.com/en-us/microsoftteams/rooms/ are the supported ways to manage Microsoft Teams Rooms.

Regards,
