### ISSUE TITLE
Unable to get cmdlet: Get-CscallQueue details when connected via new-PSSession

### ISSUE THREAD

**Issue by velikantisreekanth** [MicrosoftDocs/office-docs-powershell#9549]
Hi Team,
Unable to connect to Get-CscallQueue cmdlet when connected via new-PSSession.
It works well when the script is executed from the PowerShell ISE but not when connected via session endpoint. I am using the Teams module 4.4.1 version.
cmdlets used to connect to remote session:
$so = New-PSSessionOption -SkipCNCheck -SkipCACheck
Enter-PSSession -ComputerName servername -UseSSL -ConfigurationName 'configfilename' -Authentication NegotiateWithImplicitCredential -SessionOption $so
Once connected to remote computer, when I execute the cmdlet:

Get-CsCallQueue -NameFilter $queueName -ErrorAction SilentlyContinue

received the Exception message: "The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing, ProcessRecord, and EndProcessing methods, and they can only be called from within the same thread. Validate that the cmdlet makes these calls correctly,or contact Microsoft Customer Support Services." 

any insights about this can help.

Thanks.

**Comment by pbafna03** [comment]
Hi @velikantisreekanth, 

The remoting cmdlets in Teams PowerShell Module are deprecated now, please use the modern cmdlets in 4.x.x.

**Comment by yogkumgit** [comment]
@velikantisreekanth Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by velikantisreekanth** [comment]
> Hi @velikantisreekanth,
> 
> The remoting cmdlets in Teams PowerShell Module are deprecated now, please use the modern cmdlets in latest 4.x.x versions.

Hi @pbafna03,

Thanks. I am using latest modules version 4.4.1. I am using connect-MicrosoftTeams cmdlet for connecting to Teams and process the input but when the script executes the line Get-CscallQueue , its erroring out. The use of remote session is to allow end users to have certain functions exported as modules and execute them based on the usage instead of scheduling the script in server to process the data and wait till the scheduler runtime. 
script used:
$so = New-PSSessionOption -SkipCNCheck -SkipCACheck
Enter-PSSession -ComputerName servername -UseSSL -ConfigurationName 'configfilename' -Authentication NegotiateWithImplicitCredential -SessionOption $so
after connecting to remote computer, below is the script executed which is enclosed in a function.
 Connect-MicrosoftTeams -Credential $Cred 
$checkteam = Get-Team -DisplayName $Teamname
if($checkteam){
$checkteam= $checkteam | where {$_.DisplayName -eq $Teamname}
$teamGroupID=$checkteam.GroupID
$allChannels=Get-TeamChannel -GroupId $teamGroupID
#assign team Channel ID from the Channel Name
$teamchannel= $allChannels | where {$_.DisplayName -eq $channelName}
if($teamchannel){
$teamChannelID= $teamchannel.id
$teamChannelUserID = (Get-TeamChannelUser -GroupId $teamGroupID -DisplayName $channelName -Role Owner).UserId
if($teamChannelUserID){
**$QueuesByName = Get-CsCallQueue -NameFilter $queueName -ErrorAction SilentlyContinue** # erroring out at this line.
#$QueuesByName = $QueuesByName |? {$_.Name -eq "$($queueName)"}
$QueuesByName = $QueuesByName | Where-Object Name -eq "$($queueName)"
if($QueuesByName){

Set-CsCallQueue `
-Name $queueName `
-ChannelId $teamChannelID `
-ChannelUserObjectId $teamChannelUserID[0] `
-DistributionList $teamGroupID `
-Identity $QueuesByName.Identity `
| Out-Null
}
}
}
}

Let me know if this can be validated?
Thanks.

**Comment by yogkumgit** [comment]
@pbafna03

**Comment by yogkumgit** [comment]
@pbafna03 Please comment. Thanks

**Comment by pbafna03** [comment]
Hi @velikantisreekanth , 

The best course of action for this would be to report this via the M365 Support channels, the relevant teams can connect and help debug/figure this out. Ref - https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide 

Thanks,

**Comment by yogkumgit** [comment]
@velikantisreekanth Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
