### ISSUE TITLE
Command typo

### ISSUE THREAD

**Issue by nekkron** [MicrosoftDocs/office-docs-powershell#9553]
Under "Troubleshoot installing the EXO V2 module" and bullet "You receive the following error:" the command "Get-PSReporitory" doesn't exist. The correct command is "Get-PSRepository"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@nekkron, fixed. In the future, you too can make changes like this directly. No need to open a GitHub issue first. Instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feeback.

Closing
