### ISSUE TITLE
Retention Policy created as case hold policy

### ISSUE THREAD

**Issue by ma261065** [MicrosoftDocs/office-docs-powershell#9569]
While testing, and also based on feedback from Product Group, if the -RetentionComplianceAction parameter is omitted, the Retention Policy is created as a "UniH" instead of a "mbx" policy (Refer to MS-internal Issue 2673745 on o365exchange.visualstudio.com).

This should be called out somewhere in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e8e582d-6b99-0a36-59e4-954e622154ce
* Version Independent ID: bb512026-47d0-a419-d56a-1aa3ca57b255
* Content: [New-RetentionComplianceRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-retentioncompliancerule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-RetentionComplianceRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-RetentionComplianceRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
OK. Done.

Thanks for the feedback.

Closing
