### ISSUE TITLE
Limit Search Scope

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#957]
When I search other sections of docs.microsoft.com, the search scope is limited to that topic,  it would be helpful if this occurred when we searched the PnP content

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3240d3-6a7d-fc4b-62fd-d3a5375d8a4a
* Version Independent ID: 561212df-4dab-92b7-b634-57d53d313c6f
* Content: [PnP PowerShell overview](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* Service: **unspecified**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by nsshommo** [comment]
@DeanGross Thanks for your query. We will get back to you soon.

@VesaJuvonen Can you help me on this one?

**Comment by VesaJuvonen** [comment]
@nsshommo, @kenwith - issue is around the Search capability in the docs.microsoft.com and ask is around targeting the search properly for the content set. This is a request on the docs.microsoft.com platform, not on the PnP PowerShel. 

@DeanGross - Feedback noted and search is not scoped on the PowerShell topic. As the Office PowerShell is all stored in one content set, most likely we can scope the search to that, but not specifically for example to the Teams PowerShell inside of this content set. We'll see what we can do here depending on the capabilities within the platform. Thanks for the suggestion.

**Comment by kenwith** [comment]
@DeanGross - thank you for the feedback and I will take this to the team that wrangles the platform.

Some things I can suggest for search. Check out the PowerShell Module Browser: https://docs.microsoft.com/en-us/powershell/module/

The PnP cmdlets will not show up there yet but we can get them added if @VesaJuvonen decides he would want them there.

If you are on GitHub you can use the Find File at the top of the main repo and type in part of a cmdlet and it will show you everything in the repo that matches. If you are on the PnP page on docs.microsoft.com (https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps) and expand the Reference and PnP you can filter for a specific cmdlet.

Hope these help in the meantime and I will surface this feedback. Thanks for contributing @DeanGross !
