### ISSUE TITLE
Incorrect information regarding the support for Office 365 operated by 21Vianet

### ISSUE THREAD

**Issue by jinzheng-msft** [MicrosoftDocs/office-docs-powershell#9570]
Hello , 

In this document it says 
"This cmdlet is available in Office 365 operated by 21Vianet, but it won't return any results."

However, we are able to run this cmdlet and retrieve Mailbox Audit log in Office 365 operated by 21Vianet through powershell.

It looks like the information needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5b200b-dd1b-c217-81f2-c955ed68e5a0
* Version Independent ID: bc48c26f-0a3f-0511-088e-5a9a19650f43
* Content: [Search-MailboxAuditLog (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/search-mailboxauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Search-MailboxAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Search-MailboxAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
OK. Statement removed. In the future, you too can make changes like this yourself. No need to open a GitHub issue first. For instructions, see [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
