### ISSUE TITLE
Feature request: Connect using AppID, CertificateThumbPrint,TenantName

### ISSUE THREAD

**Issue by joenstrup** [MicrosoftDocs/office-docs-powershell#9572]
App-only is supported by i.e. following modules:
 - AZ
 - PNP.PowerShell
 - ExchangeOnline/Security&Compliance
 - Graph

Please also have this option to connect using AppID, CertificateThumbPrint and TenantName, as security-wise current token method requires a App Reg with Client Secret and a service account/user. 

With the option to use an App Reg with certificate, we can remove the account requirement and just use an App. Also, this is how every other module is doing it.

This is an issue!

**Comment by chrisda** [comment]
@joenstrup, you should open a support ticket about this so your request gets in front of the people who can actually do something about it.
