### ISSUE TITLE
Possible error in document

### ISSUE THREAD

**Issue by jt980** [MicrosoftDocs/office-docs-powershell#958]
In the Description portion, the third bullet says: "Copy messages from the source mailbox and delete them from the target mailbox."  This may be incorrect or needs to be separated into two bullet points.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c6c666-7221-7984-82a5-d731fee0ac3d
* Version Independent ID: 6970ac1a-0aaa-c625-24db-e3db2296b6f8
* Content: [Search-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/search-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Search-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nsshommo** [comment]
@jt980 Thanks for your feedback. We are looking about this matter.

**Comment by chrisda** [comment]
@jt980, I removed the problematic third bullet (which was basically restating the same thing as the first two bullets).

Thanks for your feedback.
