### ISSUE TITLE
Update the trace limit from 50000 to 100000.

### ISSUE THREAD

**Issue by TomonoriAbe** [MicrosoftDocs/office-docs-powershell#9587]
The results of the tracking are currently available for 100000 acquisitions. Please update the limit from 50000 to 100000.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c38a9b3d-3c15-3a0f-dc38-4ee357e0c800
* Version Independent ID: 4e5c08ec-a2d4-63a4-27f0-e08445f64f8a
* Content: [Start-HistoricalSearch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/start-historicalsearch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Start-HistoricalSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Start-HistoricalSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@TomonoriAbe, OK fixed. In the future, you too can make changes like this yourself without opening a GitHub issue first. For instructions, see [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md). 

Thanks for the feedback.

Closing
