### ISSUE TITLE
Teams is incorrectly identifying internal users with a 2nd identity provider as external

### ISSUE THREAD

**Issue by JosefAschauerSky** [MicrosoftDocs/office-docs-powershell#9593]
we have ~50 accounts synced to azure which have 2 identity issuers, one of it is ExternalAzureAD, ie:

PS C:\Windows\system32> (Get-MgUser -UserId [jo.placeholder@placeholder.de).identities

Issuer                                                  IssuerAssignedId                          SignInType
------                                                   ----------------                              ----------
ExternalAzureAD                                                                                      federated
placeholderglobal.onmicrosoft.com   jo.placeholder@placeholder.de   userPrincipalName

even though these accounts are to be treated as internals, teams is detecting these as externals. This started some time this year, we cannot add them to any shared teamchannel:

PS C:\Windows\system32> add-TeamChannelUser -DisplayName "SSTC - somesharedteamchannel" -GroupId 4acbd5a3-1xx4-x258-bca7-18f9a14xxx
d4 -User jo.placeholder@placeholder.de

add-TeamChannelUser : Error occurred while executing Add-TeamChannelUser
Code: BadRequest
Message: Externally authenticated users and guest users are not allowed in shared channels
InnerError:
  RequestId: cf5c9208-5019-421c-9f9f-cfa4deeada70
  DateTimeStamp: 2022-06-08T10:41:43
HttpStatusCode: BadRequest
In Zeile:1 Zeichen:1

+ add-TeamChannelUser -DisplayName "notrevealed" -GroupId 4acbd5a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamChannelUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Teams.PowerShell.TeamsCmdlets.ErrorHandling.ApiException,Microsoft.Teams.Power
   Shell.TeamsCmdlets.AddTeamChannelUser

This is buggy behavior. The main identity of these accounts is belonging to us, the 'ExternalAzureAD' identity is federated to some other company additionally. But these accounts are treated as they would be externally identified at first priority and not correctly identified as internal accounts as everyone else

**Comment by JosefAschauerSky** [comment]
Anything on this? 
This is a aad synced user, his first identity is internal. The second identity is ExternalAzureAD federated. 
If we try to add him to a shared channel, add-TeamChannelUser incorrectly identifies him as solely externally federated, ignoring his internal identity.

**Comment by JosefAschauerSky** [comment]
support suggested me to raise this in github. Great.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
@JosefAschauerSky I understand, however, we are limited to documentation articles fixes here.
