### ISSUE TITLE
Article missing description for -Archive parameter

### ISSUE THREAD

**Issue by awesomecogs** [MicrosoftDocs/office-docs-powershell#9609]
The article has the text `{{ Fill Archive Description }}` instead of a real description for that parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63846d33-ce4d-ff4e-c23b-8ca1b6a3904f
* Version Independent ID: b22a5a91-cf3c-6043-79dd-74382262d49f
* Content: [Get-MailboxRegionalConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailboxregionalconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailboxRegionalConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-MailboxRegionalConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@awesomecogs, empty parameter descriptions are a known issue. Availability of a parameter and functionality of a parameter are two different things. See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for more details.

So, are you trying to use this parameter, possibly from guidance in other content, or are you just pointing out that the description is empty?

**Comment by yogkumgit** [comment]
@awesomecogs Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
