### ISSUE TITLE
Related links is referring to the same page

### ISSUE THREAD

**Issue by TheGhost2804** [MicrosoftDocs/office-docs-powershell#9617]
The related links section is refering to the same page, this should be the Get-OrganizationConfig command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23add0a6-bb9c-15d2-a6eb-351ae0564522
* Version Independent ID: 8056b3ee-4fab-3a5c-935b-a9d0e9ad82a4
* Content: [Set-OrganizationConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OrganizationConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-OrganizationConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@TheGhost2804, believe it or not, up until ~3 years ago, every Exchange-related cmdlet reference topic needed a link to itself in Related Links so `Get-Help <Cmdlet> -Online` would work.  That link now lives in the `online version` metadata attribute.

Only 26 out of 1300+ Exchange-related cmdlet reference topics have anything in the Related Links section, so I just removed the link from the topic.

Thanks for the feedback.

Closing
