### ISSUE TITLE
CsMeetingRoom functions cmdlet is no longer supported?

### ISSUE THREAD

**Issue by ITUCguy** [MicrosoftDocs/office-docs-powershell#9621]
MicrosoftTeams PowerShell module 4.4.1 (and 4.5.0 installed today) and when I attempt to run this cmdlet independently and in scripts on our production SfB servers, I get the following error:

PS C:\Windows\system32> Get-CsMeetingRoom
Get-CsMeetingRoom : This cmdlet is no longer supported, please consult public documentation
At line:1 char:1
+ Get-CsMeetingRoom
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Microsoft.Teams.ConfigApi.Cmdlets.GetCsMeetingRoom

Just yesterday 30 June 2022 CsMeetingRoom functions were working as I transitioned and migrated some rooms to Teams, including exporting an overall list using Get-CsMeetingRoom.

I see no public documentation regarding this command being deprecated, in releases notes and it is still listed as a function in the 4.5.0 Teams module package details.  What is the cause of this Microsoft?

**Comment by pbafna03** [comment]
Hi @ITUCguy, 

The *-CsMeetingRoom cmdlets are not supported for managing Microsoft Teams Rooms. You can use the methods described in the [Microsoft Teams Rooms](https://docs.microsoft.com/en-us/microsoftteams/rooms) documentation to manage Microsoft Teams Rooms.

References: 
https://docs.microsoft.com/en-us/microsoftteams/rooms/ 
https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-supported-versions#deprecated-cmdlets 
https://docs.microsoft.com/en-us/powershell/module/skype/get-csmeetingroom

Thanks,

**Comment by ITUCguy** [comment]
Hi, referencing documentation has already been noted.  The comment is not helpful. Please reopen. 
Reference: https://www.powershellgallery.com/packages/MicrosoftTeams/4.5.0: Enable/Disable/Get-CsMeetingRoom are listed as functions of as Teams Module 4.5.0. Need the ability to use the functions Get-CsMeetingRoom to move existing Skype for Business conference room to Teams. Existing scripts are no longer functioning.
