### ISSUE TITLE
Unable to run CsApplicationAccessPolicy from PWSH [MacBook]

### ISSUE THREAD

**Issue by raguravindran** [MicrosoftDocs/office-docs-powershell#9622]
[Unable to run CsApplicationAccessPolicy from PWSH [MacBook]]

When trying to initiate any command related to CsApplicationAccessPolicy
New-CsApplicationAccessPolicy
Get-CsApplicationAccessPolicy

The tenant **nowdomain.onmicrosoft.com** throws Session error. Even after valid login (as Admin).

<img width="1427" alt="Screenshot 2022-07-04 at 12 51 23 PM" src="https://user-images.githubusercontent.com/36010645/177102663-f714fe5e-0760-4ff1-8ef8-e6f0db6ec9b4.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6533a7d-ddc4-eef1-cca6-0ee4786163ef
* Version Independent ID: 8958282d-6816-c8c3-cd0b-07b50681aacf
* Content: [Get-CsApplicationAccessPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csapplicationaccesspolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsApplicationAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsApplicationAccessPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @frankpeng7
* Microsoft Alias: **frpeng**

**Comment by raguravindran** [comment]
Versions and Modules available.

<img width="1180" alt="Screenshot 2022-07-04 at 12 52 00 PM" src="https://user-images.githubusercontent.com/36010645/177102803-3a935257-f386-492e-bb4f-87500d3f6890.png">

**Comment by pbafna03** [comment]
Hi @raguravindran, 

Can you please try with the latest Teams PowerShell Module version.  Older versions like 2.5.0 are deprecated, ref - https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-supported-versions. 

Thanks,

**Comment by raguravindran** [comment]
@pbafna03 Thank you, after update it worked. closing this issue
