### ISSUE TITLE
Latitude and Longitude are not reserved

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/office-docs-powershell#9623]
Latitude and Longitude params are not reserved. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41db135-d54b-b89b-73b1-8b2773d45eb3
* Version Independent ID: 3483eb1d-6fb6-a4de-45b2-24d6ba7ac5e8
* Content: [New-CsOnlineLisLocation (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinelislocation?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsOnlineLisLocation.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsOnlineLisLocation.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by JensTrier** [comment]
@TorrenManson thanks for the feedback! I'll fix it.

**Comment by JensTrier** [comment]
Fixed in PR 9626

**Comment by yogkumgit** [comment]
#9626

**Comment by yogkumgit** [comment]
@TorrenManson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
