### ISSUE TITLE
Get-DistributionGroupMember/Get-DynamicDistributionGroupMember behave differently in Windows vs Linux/CentOS (impact: performance)

### ISSUE THREAD

**Issue by miegie-a** [MicrosoftDocs/office-docs-powershell#9634]
**Exchange Online Powershell:** 
Get-DistributionGroupMember/Get-DynamicDistributionGroupMember cmdlets behave differently in Windows vs Linux/CentOS. 
This difference has a huge negative impact on performance for Linux/CentOS implementation.

setup:
- in EXO tenancy, create a group (distribution group, mail-enabled security group or dynamic distribution group) with at least 10k members
- setup app-only authentication in Azure AD for EXO V2 PS
- use powershell 7.2.x for Windows and Linux/CentOS
- use Exchange Online Management v2.0.5 for Windows and Linux/CentOS
- connect to EXO with Connect-ExchangeOnline through app-only authentication
- using Measure-Command against Get-DistributionGroupMember/Get-DynamicDistributionGroupMember with "unlimited results" to return all members (10k+)

expected results:
- in our tests where we use 25k members for a given group
- Windows measurements ~= Linux measurements (accounting for acceptable level of variances)
- Windows measurements in various environments yielded ~110s (give or take)
- Linux measurements in various environments yielded ~110s (give or take)

actual results:
- in our tests where we use 25k members for a given group
- Windows measurements is much much faster than Linux measurements (degradation is by 7 times)
- Windows measurements in various environments yielded ~110s (give or take)
- Linux measurements in various environments yielded ~700s (give or take)

NOTE:
- curiously from Jun 27 to around Jul 4 11:30am PST, Linux cmdlets were able to operate on par with Windows cmdlets.  After Jul 4 11:30am, Linux cmdlets were operating very poorly

We have turned on logging as instructed in the README.MD.   In Windows, there's only telemetry logs generated and operates as expected.    In Linux, the GET cmdlet failed and also mysteriously requested password for the group as well.  
The failure was
"WARNING: An error caused a change in the current set of domain controllers.
Get-DistributionGroupMember: Server YTBPR01A07DC001.CANPR01A007.PROD.OUTLOOK.COM doesn't belong to partition CANPRD01.PROD.OUTLOOK.COM."

**Comment by chrisda** [comment]
@miegie-a, try using v2.0.6-Preivew6 of the module. You have a few of different things to try:

- Connect using the `-UseRPPSSession` switch.
- Connect without using the `-UseRPPSSession` switch so you're using the REST API versions of the cmdlets.
- Connect using app-only authentication

Compare/contrast the results in both Windows and Linux (where possible) and report back here with your findings.

The differences in regular and REST API mode differences are explained [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#updates-for-version-206).

**Comment by miegie-a** [comment]
Hi,

we have tried v2.0.6-Preview6, also thinking of the same thought line.
when using 2.0.6 remote powershell Session (UseRPSession switch), the behaviour is like 2.0.5 and the Linux based call/query performs very poorly.   I didn't subject it with debugging and i'm not sure if it "crashes" the same way with a DC error.

NOTE that the crash only happens when in full debugging.  the Linux cmdlets do actually work and respond back with the correct data results when not in debugging.  of course, performance is terrible.

**Comment by miegie-a** [comment]
Hi again.

with using 2.0.6-Preview6, when using the default connection by not adding the UseRPSession switch, the Get-DistributionGroupMember/Get-DynamicDistributionGroupMember cmdlet call just simply crashes when the results are long enough that it does some "internal paging".

See error for both Windows and Linux 2.0.6-Preview6.

**Get-DistributionGroupMember: Ex6086AE|Microsoft.Exchange.Data.Directory.ADInvalidHandleCookieException|Active Directory operation failed on
YQXPR01A07DC002.CANPR01A007.PROD.OUTLOOK.COM. Additional information: Active Directory rejected paged search cookie because a cookie handle was discarded
by a Domain Controller or a different LDAP connection was used on subsequent page retrieval. Paged search needs to be restarted and will succeed.
Additional information: The parameter is incorrect. Active directory response: 00000057: LdapErr: DSID-0C090B19, comment: Error processing control, data 0,
v4563.**

**Comment by chrisda** [comment]
@miegie-a, you should send this information to exocmdletpreview[at]service[dot]microsoft[dot]com. They should be able to help you.
