### ISSUE TITLE
Get-team's MailNickName example is a bit misleading

### ISSUE THREAD

**Issue by rikumus** [MicrosoftDocs/office-docs-powershell#9639]
In [Example 3](https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps#example-3) reg. MailNickName parameter the info text should be updated so that it describes the functionality more as a filter. This is written in parameter's description later in document, but would be good to update this to Example 3 as well. If you compare to Example 4, there it is mentioned for DisplayName parameter properly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38da792-01bc-28ad-7727-794075e150c9
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Thanks for your feedback!
