### ISSUE TITLE
port

### ISSUE THREAD

**Issue by mlafita-agropro** [MicrosoftDocs/office-docs-powershell#9641]

**Comment by chrisda** [comment]
@mlafita-agropro, can you be more specific? Which topic are you talking about?

**Comment by mlafita-agropro** [comment]
Hi,

Sorry I’ve opened the issue by error, please close the issue.

Thanks!

Marc Lafita
Technical Business Analyst
[https://veggadigital.com/assets/email/vegga_advanced_farming_logo.png]
***@***.******@***.***>
+34 873 407 887<tel:+34%20873%20407%20887>
veggadigital.com<https://www.veggadigital.com>
[https://veggadigital.com/assets/email/linkedIn.png]<https://www.linkedin.com/company/veggadigital>  [https://veggadigital.com/assets/email/instagram.png] <https://www.instagram.com/veggadigital/>   [https://veggadigital.com/assets/email/facebook.png] <https://www.facebook.com/VEGGA-107640835248022>
Polígon Industrial, C/ de la Coma 2
25243 El Palau d'Anglesola | Lleida
Este mensaje y sus ficheros adjuntos van dirigidos exclusivamente a su destinatario y pueden contener información confidencial sujeta a secreto profesional. No está permitida su reproducción o distribución sin la autorización expresa de Agropro Digital Farmin SL. Si usted no es el destinatario final, por favor elimínelo e infórmenos por esta vía. De acuerdo con la LOPD, le informamos que sus datos personales y dirección e-mail forman parte de un fichero, cuyo responsable es Agropro Digital Farming SL, siendo la finalidad del mismo la gestión de carácter comercial y el envío de comunicados comerciales sobre nuestros productos o servicios. Si lo desea, podrá ejercer sus derechos de acceso, rectificación, cancelación y oposición de sus datos, enviando un mensaje a la dirección siguiente: ***@***.******@***.***> indicando en la línea del asunto el derecho que desea ejercer.
