### ISSUE TITLE
Impossible to remove GroupNotificationOverride once set?

### ISSUE THREAD

**Issue by moverton28** [MicrosoftDocs/office-docs-powershell#9647]
By default, the GroupNotificationOverride setting for a Teams user is blank, until set via the Set-CsUserCallingSettings cmdlet. Once set I can't seem to find any way to unset it again. I don't know if this is an issue or if it's just me being green and missing something. I've tried setting it to null in a few different ways but have had little success? What should I do if I no longer want an override to be in place and would prefer the freedom of having per-group notification settings?

**Comment by moverton28** [comment]
Thank you, much appreciated, thought I was going a little bit mad!

**Comment by JensTrier** [comment]
No you were not :-)
