### ISSUE TITLE
No example of using Import-PnPTaxonomy with a file containing terms

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/office-docs-powershell#966]
Hi
There are two ways of using this command.
The first way of just including the terms has an example.
The second way, using a file containing terms has no example.
Regards
Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36c52515-b901-5928-cbe1-641b0c21f975
* Version Independent ID: 700c3b55-3841-f8fc-3fc1-5dad4b6dc7be
* Content: [Import-PnPTaxonomy (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/import-pnptaxonomy?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Import-PnPTaxonomy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Import-PnPTaxonomy.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by erwinvanhunen** [comment]
Thank you @NPrice99. Added in PR https://github.com/SharePoint/PnP-PowerShell/pull/1606

**Comment by VesaJuvonen** [comment]
Closed based on the update from @erwinvanhunen as PR is merged.
