### ISSUE TITLE
Missing unit & syntaxe detail

### ISSUE THREAD

**Issue by Elgger** [MicrosoftDocs/office-docs-powershell#9660]
[Missing Lat & Long unit and syntaxe : Do we need to type 48°53'36.9"N or 48.893590 ??? This info is also missing on TAC]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21f2e75-d4b3-e068-e32e-0d9f41a5fd89
* Version Independent ID: 54531cfa-2f4b-590e-0b74-4227849d95ae
* Content: [Set-CsOnlineLisCivicAddress (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlineliscivicaddress?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineLisCivicAddress.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsOnlineLisCivicAddress.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by JensTrier** [comment]
@Elgger Thanks for the feedback. The format is decimal degrees https://en.wikipedia.org/wiki/Decimal_degrees. I'll update the docs to make it clear.

Feel free to close this issue.

**Comment by yogkumgit** [comment]
PR #9695  is merged. @Elgger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
