### ISSUE TITLE
{{ Fill CanHaveCloudCache Description }}

### ISSUE THREAD

**Issue by scottbutton** [MicrosoftDocs/office-docs-powershell#9664]
Hi there,

There's an attribute description to update on this page. The CanHaveCloudCache description hasn't been completed and shows "{{ Fill CanHaveCloudCache Description }}" instead. Just wanted to flag with you to update with what this actually means.

Cheers, Scott.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b97f5cab-4128-451d-c78a-8f217a5f79c5
* Version Independent ID: c8dff44f-4ae1-2d58-f18c-bc1fa9ab571d
* Content: [Set-AcceptedDomain (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-accepteddomain?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-AcceptedDomain.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-AcceptedDomain.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@scottbutton, duly noted. Empty parameter descriptions are a known issue. Availability vs. functionality can be very different. See [here(https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for an explanation.

So, you aren't trying to use the parameter (possibly from documentation elsewhere)? You're just pointing out that it's empty?

**Comment by yogkumgit** [comment]
@scottbutton as it is a known issue and in state of  work in progress. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
