### ISSUE TITLE
CustomAlertText with newly added FileTypeAction does not make sense

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/office-docs-powershell#9666]
Hi,

I think there  is some confusion about the parameters here. The parameter _CustomAlertText_ allows to define the setting which Text can be used within the replaced Malware Alert Text.txt file and applies to Exchange Online. Additionally the article says: _This parameter is only meaningful when the Action parameter value is DeleteAttachmentAndUseCustomAlert._
But the Action parameter is no longer available within the cloud based service.
AFAIK it was replaced 20days ago with the change from @chrisda by _FileTypeAction_

As we have used in the past this configuration multiple times in the cloud and it no longer works I'm sure that the _CustomAlertText_ parameter is only valid for Exchange Server 2013, Exchange Server 2016, Exchange Server 2019 and no longer for Exchange Online. This would make sense as within the parameter _FileTypeAction_ with the option _Quarantine_ the article says correctly: Quarantine the message. Whether or not the recipient is notified depends on the quarantine notification settings in the quarantine policy that's selected for the policy by the QuarantineTag parameter.

Can someone review the article here?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76492554-a89b-db9e-d68c-e706cc2babe9
* Version Independent ID: e72f7a07-bf76-0487-9c7b-fb79b2fe9c41
* Content: [Set-MalwareFilterPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-malwarefilterpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MalwareFilterPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@myfope, thanks for pointing that out. I went through New/Set-MalwareFilterPolicy for the recent changes, but I missed the following parameters:

- CustomAlertText in New and Set.
- EnableInteralSenderNotifications in New.

I fixed those parameters so they're now on-premises Exchange only.

OK?

**Comment by myfope** [comment]
Hi Chris,

this sounds fine - yes thanks!

-Peter

**Comment by yogkumgit** [comment]
@myfope Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
