### ISSUE TITLE
Grant-CsTeamsCallingPolicy - Does not work with licensed Resource Accouns

### ISSUE THREAD

**Issue by Riche98** [MicrosoftDocs/office-docs-powershell#9669]
Unable to assign calling policies to resource accounts with the Teams powershell module now. Just returns the error 'User can't be granted this policy.' 

Grant-CsTeamsCallingPolicy -Identity "Faulty_Test_For_MS@test.onmicrosoft.com" -PolicyName AllowCalling

```
Grant-CsTeamsCallingPolicy : User can't be granted this policy
At line:1 char:1
+ Grant-CsTeamsCallingPolicy -Identity "Faulty_Test_For_MS@XXXXX. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = Fa...ntUserRequest }:<>f__AnonymousType72`3) [Grant-CsTe
   amsCallingPolicy], Exception
    + FullyQualifiedErrorId : ClientError,Microsoft.Teams.ConfigApi.Cmdlets.GrantCsTeamsCallingPolicy
```

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Riche98 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
