### ISSUE TITLE
Similar to the previous issue

### ISSUE THREAD

**Issue by walidelmorsy** [MicrosoftDocs/office-docs-powershell#9673]
Hi team,

thanks for correcting the previous issue with Exchange Location. I believe there is another fix required for the One Drive location parameters (OneDriveSharedBy) as we need to specify (All) as an input which is not an accepted input for (OneDriveSharedBy):

![image](https://user-images.githubusercontent.com/55671976/178854068-f726c842-2dfe-4e71-9b3b-d92de2ea59dd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64d46b9d-594b-e24e-4964-71dab360cd28
* Version Independent ID: a6b0658b-cbda-6d29-59f1-d1189208c72a
* Content: [New-DlpCompliancePolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-dlpcompliancepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-DlpCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by walidelmorsy** [comment]
@chrisda Understood, but we need a parameter to accept "All" as a value, according to my testing, "OneDriveSharedBy" does not.

**Comment by chrisda** [comment]
@walidelmorsy, you should open a support ticket. All is definitely available in OneDriveLocation (site-based) but not in OneDriveSharedBy/OneDriveSharedByMemberOf (user-based).

**Comment by walidelmorsy** [comment]
@chrisda that is what I said. In the article it says “don’t use OneDriveLocation parameter”, which I think it should be corrected.

**Comment by yogkumgit** [comment]
@chrisda Please comment. Thanks

**Comment by chrisda** [comment]
OK. I figured it out and updated the topics accordingly:

- OneDriveLocation does act like ExchangeLocation, except it isn't locked down as tight. It accepts the value All or site URLs that it can verify (the way the parameter behaves in most other cmdlets). When you create a new DLP policy in PowerShell, the default value of OneDriveLocation is All, which means: Include all OneDrive for Business sites in this policy.
- [ExceptIf]OneDriveSharedBy and [ExceptIf]OneDriveSharedByMemberOf restrict the policy to specific sites based on associated users (individuals or group members) and prevent the policy from applying to sites of specific users or group members.
- In Set-DlpCompliancePolicy, you can use `-RemoveOneDriveLocation All` to remove ODfB sites from the policy, or `-AddOneDriveLocation -All` to add ODfB sites to the policy if you created the policy with `-OneDriveLocation $null`.

OK?

**Comment by yogkumgit** [comment]
@walidelmorsy Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
