### ISSUE TITLE
Remove-UnifiedGroupLinks throws incorrect exception when trying to remove owners

### ISSUE THREAD

**Issue by simonwolton** [MicrosoftDocs/office-docs-powershell#9674]
Hi,

When running: `Remove-UnifiedGroupLinks -LinkType Owners -Identity <UnifiedGroupPrimarySmtpAddress> -Links user@contoso.com`, an incorrect exception is thrown when `user@contoso.com` is not an owner of the O365 group. For context, this was a freshly created group within the same script.

### Expected result
Exception is thrown: `user@contoso.com is not listed as an owner of the O365 group` (or similar exception)

### Actual result
The following exception gets thrown :
`You can't remove the owner from this group because the person you're removing is currently the only owner. You need to promote another member to owner before you proceed.`

The exception is highly misleading since the issue isn't that the person being removed is the only owner, the issue is that they aren't an owner at all.

![image](https://user-images.githubusercontent.com/15790206/178973594-a94e8d68-9dfd-4a4c-a9b6-df2050ebc3d4.png)

**Comment by chrisda** [comment]
@simonwolton, your best path forward is to open a support ticket.

**Comment by yogkumgit** [comment]
@simonwolton Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
