### ISSUE TITLE
No translation of this page to French (fr-ca or fr-fr)

### ISSUE THREAD

**Issue by philliprenouf** [MicrosoftDocs/office-docs-powershell#9683]
I had to share this document with my public sector customer and we discovered there is no French version of this page. This is especially difficult since the reason they needed the page is for the right syntax to configure multiple languages for the Teams Meeting invite. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bf080-1e20-1411-0d9e-41f559b883d8
* Version Independent ID: 6a37be44-d957-2b7a-a563-53332cf59098
* Content: [Set-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Hello @philliprenouf I am looking into this

**Comment by get-itips** [comment]
Ok I managed to report this to the corresponding translation team.

**Comment by yogkumgit** [comment]
@get-itips Please tag/mention the loc team here.

**Comment by tiburd** [comment]
@philliprenouf 

Hi,

Because you are internal to Microsoft, please report a translation bug on the Global Services' Hub website:

- [https://globalservices.powerappsportals.com/Global/](https://globalservices.powerappsportals.com/Global/) 

Thank you!

cc: @yogkumgit
