### ISSUE TITLE
link  would be nice

### ISSUE THREAD

**Issue by petersonal2** [MicrosoftDocs/office-docs-powershell#9684]
In the description to the "Configure-EnterpriseApplication.ps1" some pointing link would be nice to add. I am looking for this, and not finding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6cd7dfe-c3e8-b150-143e-ee63c2c077dd
* Version Independent ID: 4546a968-bf64-1eae-1205-e89c4b2161f9
* Content: [Test-OAuthConnectivity (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/test-oauthconnectivity?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Test-OAuthConnectivity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Test-OAuthConnectivity.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@petersonal2 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
