### ISSUE TITLE
`Set-LabelPolicy` cmdlet does not apply any label to a team

### ISSUE THREAD

**Issue by mbratukha** [MicrosoftDocs/office-docs-powershell#9685]
We are currently in investigation of capabilities how to automate the assignment of sensitivity labels to teams (O365 groups).

As of documentation we came up to use the cmdlet `Set-LabelPolicy`, which is mentioned [here](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide#use-powershell-for-sensitivity-labels-and-their-policies).

Unfortunately, after successful execution of this command:
``` PowerShell
Set-LabelPolicy -Identity "{label-policy-id}" -AddModernGroupLocation "MBTestSetLabelPolicy01@****.onmicrosoft.com"
```

the label does not appear in the target team and its team site. Also, it's not visible in any of the admin centers (Teams or SharePoint).
Even MS Graph says that a team does not have any label assigned:
![image](https://user-images.githubusercontent.com/1413357/179179179-137e653f-c2f5-4d6b-9bc7-4aedbdbae6ad.png)

The label does not appear even after 24 hours.

At the same time the S&C Center shows that the label is assigned:
![image](https://user-images.githubusercontent.com/1413357/179181324-f00864b5-329d-4a90-80af-2c87347dbe7f.png)

Do we miss anything here?

Additionally, we have found several other possibilities to set a sensitivity label to a team:
* via cmdlet `Set-UnifiedGroup` of the EXO V2:
   ``` PowerShell
   Set-UnifiedGroup -Identity "{group-id}" -SensitivityLabelId "{label-id}"
   ```
* via cmdlet `Set-PnpSite` of the PnP PowerShell:
   ``` PowerShell
   Set-PnpSite -Identity $site -SensitivityLabel "{sensitivity-label-id}"`
   ```
* via cmdlet `Set-SPOSite` of the SharePoint Online PowerShell:
   ``` PowerShell
   Set-SPOSite -Identity $site -SensitivityLabel "{sensitivity-label-id}"`
   ```
* via Graph API by patching the property `assignedLabels` of a group

The first two do not work, i.e. the same behavior as when `Set-LabelPolicy` is used: no errors, label appears only in S&C Center, but in the team/site itself is not visible.

The only last two seems to work right: the label is assigned to team and its site, also Graph API delivers it too. The only confusion is, that this assignment does not appear in S&C Center (is it right so?).

Our questions are:
* is the cmdlet `Set-LabelPolicy` a proper way to set a sensitivity label to a container (group or site)?
* is it a proper way to assign a sensitivity label to a team via `Set-SPOSite` cmdlet? Does it have any side-effects?

Any tip would be very appreciated.

**Comment by chrisda** [comment]
@mbratukha, you should open a support ticket and ask there.

**Comment by yogkumgit** [comment]
@mbratukha Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
