### ISSUE TITLE
Escaping Special Characters in DisplayName

### ISSUE THREAD

**Issue by jeff-bb** [MicrosoftDocs/office-docs-powershell#9688]
They appear require being urlencoded, likely for submission against graph. I think the preference would be to have this solved in the Teams cmdlet BUT the documentation can at least be updated.

For example, if searching for a Team with Get-Team -DisplayName "AB&C", it would require the search to be sent as Get-Team -DisplayName "AB%26C"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38da792-01bc-28ad-7727-794075e150c9
* Version Independent ID: cb290aa5-ce28-10a4-f17c-cc5db6edc706
* Content: [Get-Team (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-Team.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-Team.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by shivtorov** [comment]
probably, you can add an addtional example that is using `[uri]::EscapeDataString('AB&C')` which seems producing required encoding `AB%26C`
