### ISSUE TITLE
Cannot run Get-CsTeamsIPPhonePolicy command unless you have full Teams Administrator role

### ISSUE THREAD

**Issue by poshdude** [MicrosoftDocs/office-docs-powershell#9691]
Hi,

I would like to ask if this behaviour can be changed.  Its not possible to run some Get-CsTeamsxxxxPolicy commands at the moment unless you have been assigned the full Teams Administrator role.  Get is a read-only operation so it would be useful to be able to read (see) the policy settings even if you don't want to be able to Set (change) any settings. 

```
Get-CsTeamsIPPhonePolicy
Get-CsTeamsIPPhonePolicy : You are not authorized to perform this action
At line:1 char:1
+ Get-CsTeamsIPPhonePolicy
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ConfigType = ...emaVersion =  }:<>f__AnonymousType25`3) [Get-CsTeamsIPPhonePolicy], Exception
    + FullyQualifiedErrorId : Unauthorized,Microsoft.Teams.ConfigApi.Cmdlets.GetCsTeamsIPPhonePolicy
```

Is it possible to authorize running Get-CsTeamsxxxxPolicy commands for roles other than full Teams Administrator role?

Thanks!

**Comment by get-itips** [comment]
Hello @poshdude Jam, how are you?
What role did you use to try that cmdlet?
I've just used a Teams Communications Support Specialist to run the cmdlet and it worked.

**Comment by poshdude** [comment]
Hi,

I found it worked when I have Teams Administrator but but not when I have
Teams Communication Administrator. I didn't explore the other RBAC roles as
these are the two we are typically using to support our clients.

**Comment by get-itips** [comment]
Hello @poshdude 
I could verify that, if using a _Teams Communication Administrator_ you can not run the cmdlet.
Teams PS still does not work with Custom RBAC and the default ones can not be customized so you'll have to use other roles.
Hope this information helps you,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @poshdude Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by poshdude** [comment]
Hi,

Thanks for the feedback.  Understood this is by design and not something that is going to changed.  I think it be worth exposing the limitation between the different Teams RBAC roles for running against Get Policy commands for awareness.  I have a matrix I can share, let me know where would be the best place to open an issue to share this.

![Teams RBAC Roles vs Get Policy Commands Authorization](https://user-images.githubusercontent.com/96589527/181492266-bf962ea0-13da-4c48-b1da-e084edf8dfb1.jpg)

**Comment by get-itips** [comment]
@poshdude Probably against this article https://docs.microsoft.com/en-us/microsoftteams/using-admin-roles in this repo https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues
