### ISSUE TITLE
There seem to be typo graphical error in the German version of the new join by id feature in Teams meeting invite. 

### ISSUE THREAD

**Issue by Tayolateef** [MicrosoftDocs/office-docs-powershell#9696]
There seem to be typo graphical error in the German version of the new join by id feature in Teams meeting invite.  Besprchungs-ID needs to be Besprechungs-ID as the letter "e" is missing. 
![2022-07-06 14_26_56-Unbenannt - Besprechung (2)](https://user-images.githubusercontent.com/66221362/179698052-cfbfda83-69ae-4cc2-914e-494822c110f5.png)

**Comment by yogkumgit** [comment]
@samanthaw Please help us in resolving this issue. Thanks

**Comment by samanthaw** [comment]
Deferring to @Soran-M

**Comment by DMoenks** [comment]
As far as I know, the typo was already acknowledged as an issue and posted as an _Advisory_ in the _Service Health_ overview of Microsoft 365 admin center for any tenant containing German user accounts, including an announcement for a fix in an upcoming update. I'm unable to provide the matching ID though, as I don't have access to an admin center right now.

**Comment by yogkumgit** [comment]
@Soran-M Please comment. Thanks

**Comment by yogkumgit** [comment]
@Tayolateef Hope Dominik's comment is helpful for you.  We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
