### ISSUE TITLE
Unable to run Set-CsOnlineEnhancedEmergencyServiceDisclaimer with -Force switch

### ISSUE THREAD

**Issue by MattTheDev** [MicrosoftDocs/office-docs-powershell#9701]
I'm able to repro the following on versions 4.5.1, 4.5.0, and 4.4.1. I was going to submit an ICM - but wasn't sure what team to engage there. This place seemed the easiest / most direct.

Input: Set-CsOnlineEnhancedEmergencyServiceDisclaimer -CountryOrRegion $regionCode -Force
Output: Get-CsOnlineEnhancedEmergencyServiceDisclaimer : A parameter cannot be found that matches parameter name 
'ForceAccept'.

I've tried -Force, -ForceAccept, and both. The only way to run this cmdlet now is via attended input .. which isn't viable for our use case. Any assistance would be super helpful.

edit: I've tried across machines as well.

**Comment by JensTrier** [comment]
@MattTheDev Thanks for the feedback! I can repro it. I'll create an internal bug report to the address the issue.

Feel free to close this issue.

**Comment by yogkumgit** [comment]
@MattTheDev  Thank you very much for your kind feedback. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
