### ISSUE TITLE
Timeout errors using tokens

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#9703]
Due to the existing Filter parameter not supporting "like" adequately to get a subset of users, we are executing PS script like this:

Get-CsOnlineUser | Where { $_.Identity -like '0*' -or $_.Identity -like '1*' } | Select $userAttrs | Export-Csv $usersFileName -Encoding 'UTF8'

At clients with a large user base, after nearly 2 hours (sometimes more), PS finally returns the following error

System.Management.Automation.Remoting.PSRemotingTransportException: Processing data from remote server localhost failed with the following error message: The WSMan provider host process did not return a proper response.  A provider in the host process may have behaved improperly. For more information, see the about_Remote_Troubleshooting Help topic.

What can we do to avoid this if the client says that they cannot use basic authentication to connect to O365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by isrumnon** [comment]
Hi @sarollins can you please raise a support ticket regarding this issue?

**Comment by yogkumgit** [comment]
@sarollins Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
