### ISSUE TITLE
Get-CsUserCallingSettings fails when a delegate has been deleted from AzureAD

### ISSUE THREAD

**Issue by dappleby300** [MicrosoftDocs/office-docs-powershell#9704]
Hi,

The Get-CsUserCallingSettings fails when a user is removed from office 365. If it cannot lookup the object id the whole command fails;

Example;

`PS > Get-CsUserCallingSettings -Identity user@example.org`
`Get-CsUserCallingSettings : Exception occured while trying to resolve delegate identity. Fix the identity before trying again. 63xxxxb-exx1-4xx-bcbd-0dxxxxxf1942`

To reproduce add a delegate to a user and then delete the delegate from Office 365.

The only way to fix this is via the Teams client

**Comment by JensTrier** [comment]
@dappleby300 Thanks for the feedback. Yes, this is a known issue that we are working to address. The work-around is to remove the delegate using the ObjectId being shown.

An example:

Assume delegator@contoso.com with ObjectId 8480c6e7-0507-4eaa-8394-bc46aefba8ec has delegate@contoso.com with ObjectId 481efae7-f1c9-407f-8cf4-6ee41049fae3 as a delegate.

delegate@contoso.com is removed from Microsoft 365 (soft-delete which means the account stays around for 30 days).

Get-CsUserCallingSettings -identity delegator@contoso.com will show
Get-CsUserCallingSettings : Exception occurred while trying to resolve delegate identity. Fix the identity before trying again. 481efae7-f1c9-407f-8cf4-6ee41049fae3

The work-around is to use Remove-CsUserCallingDelegate with the ObjectId, like Remove-CsUserCallingDelegate -Identity delegator@contoso.com -Delegate 481efae7-f1c9-407f-8cf4-6ee41049fae3

The work-around also works for the reverse scenario.

When the user is hard-deleted (after 30 days or explicitly), the situation cures itself.

Feel free to close this issue.

**Comment by yogkumgit** [comment]
@dappleby300 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dappleby300** [comment]
Thanks for the info.
