### ISSUE TITLE
REFER's

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/office-docs-powershell#9707]
Not sure if this is a bug or by design, but I can't seem to get OutboundPstnNumberTranslationRules working on REFER's.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d954f43-a404-2c5d-34ff-7e007f0742a1
* Version Independent ID: 39faba28-6a75-5ff9-a241-6dd30bd0673a
* Content: [Set-CsTeamsTranslationRule (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamstranslationrule?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsTranslationRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsTranslationRule.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@Korbyn72 Thanks for the feedback. Please open a Microsoft support case with SBC traces etc and they will work with you to investigate what's going on.

**Comment by Korbyn72** [comment]
I can/will likely do that, but it should be know whether these rules only apply to TO and FROM, and REFER is ignored.

**Comment by yogkumgit** [comment]
@JensTrier

**Comment by JensTrier** [comment]
@Korbyn72 checked with the team and the InboundPSTNNumberTranslationRules and OutboundPSTNNumberTranslationRules don't apply to REFERs.

**Comment by yogkumgit** [comment]
@Korbyn72 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
