### ISSUE TITLE
Need to add some note to indicate that Basic Auth is still required if the end users use security & compliance cmdlet since connect-ippssession is required for them

### ISSUE THREAD

**Issue by frankchen76** [MicrosoftDocs/office-docs-powershell#9711]
Need to add some note to indicate that Basic Auth is still required if the end users use security & compliance cmdlet since connect-ippssession is required for them. customers are confused that since v2.0.6 preview doesn't need basic auth, they though connect-ippssession doesn't need as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#prerequisites-for-the-exo-v2-module)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@frankchen76, updates per referenced PR. Updated topics should publish by ~ 4:00 PM PDT M 7/25.

Thanks for the feedback.

Closing
