### ISSUE TITLE
Set-UnifiedGroup module missing from exchangeonlinemanagement 2.0.6

### ISSUE THREAD

**Issue by SabRom** [MicrosoftDocs/office-docs-powershell#9714]
Hello,

The title said it all.

When installing exchangeonlinemanagement 2.0.6, I seem to be missing multiple "unified group" related cmdlet

see : 

![mstsc_gv3UNXjQaK](https://user-images.githubusercontent.com/62282959/180726948-055321e7-fc7b-4d9e-9ef6-a99f9ce09157.png)
![powershell_JSQ8WCrLK4](https://user-images.githubusercontent.com/62282959/180726954-3e98aa1a-c682-449b-b53c-7963e0029db9.png)

**Comment by jorgytim** [comment]
I have verified the same, removed all previous exchangeonlinemanagement modules and installed only v2.0.6preview6, no unifiedgroup cmdlets are available now.

**Comment by chrisda** [comment]
@SabRom, @jorgytim, were you connecting using the _UseRPPSSession_ switch? Or were you not using the _UseRPPSSession_, which forces you to use [REST API mode](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#updates-for-version-206)?

I connected to my plain E5 tenant in 'regular' _UseRPPSSession_ mode in PowerShell 5.1, and all expected Microsoft 365 Group cmdlets were available to me:

```powershell
PS C:\Users\jdoe> get-command *-*UnifiedGroup*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Add-UnifiedGroupLinks                              1.0        tmp_qyauvtg4.aqq
Function        Get-UnifiedGroup                                   1.0        tmp_qyauvtg4.aqq
Function        Get-UnifiedGroupLinks                              1.0        tmp_qyauvtg4.aqq
Function        New-UnifiedGroup                                   1.0        tmp_qyauvtg4.aqq
Function        Remove-UnifiedGroup                                1.0        tmp_qyauvtg4.aqq
Function        Remove-UnifiedGroupLinks                           1.0        tmp_qyauvtg4.aqq
Function        Set-UnifiedGroup                                   1.0        tmp_qyauvtg4.aqq
Function        Undo-SoftDeletedUnifiedGroup                       1.0        tmp_qyauvtg4.aqq
```

When I connected in REST API mode, there were cmdlets missing:

```powershelll
PS C:\Users\jdoe> get-command *-*UnifiedGroup*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Add-UnifiedGroupLinks                              1.0        tmpEXO_yewv2bnq.efq
Function        Get-UnifiedGroup                                   1.0        tmpEXO_yewv2bnq.efq
Function        Get-UnifiedGroupLinks                              1.0        tmpEXO_yewv2bnq.efq
Function        Remove-UnifiedGroupLinks                           1.0        tmpEXO_yewv2bnq.efq
```

From the previously linked topic about v2.0.6:

> - Virtually all of the available remote PowerShell cmdlets in Exchange Online are now backed by the REST API. Some cmdlets might temporarily appear or disappear from availability using the REST API as we find and fix issues.

**Comment by yogkumgit** [comment]
@SabRom Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
