### ISSUE TITLE
The parameter "Enabled" in the Get-AntiPhishPolicy is not relevant

### ISSUE THREAD

**Issue by mariammorgan** [MicrosoftDocs/office-docs-powershell#9715]
The parameter "Enabled" in the Get-AntiPhishPolicy is not relevant, and consequently modifying the same with Set-AntiPhishPolicy won't change anything.

When we turn on or off any antiphishing policy from the GUI and we need to check its status  ( ie enabled/disabled ) from PS we should use the command get-antiphishingrule | fl state

 **Reference**:
 When you modify an anti-phishing policy, settings related to the name, priority, enabled or disabled, and recipient filters modify the anti-phish rule. All other settings modify the associated anti-phish policy.https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-anti-phishing-policies-eop#:~:text=When%20you%20modify%20an%20anti%2Dphishing%20policy%2C%20settings%20related%20to%20the%20name%2C%20priority%2C%20enabled%20or%20disabled%2C%20and%20recipient%20filters%20modify%20the%20anti%2Dphish%20rule.%20All%20other%20settings%20modify%20the%20associated%20anti%2Dphish%20policy
 
the switch -enabled in set-antiphishpolicy is not referring that policy is enabled or not ( actually not used ) as
When we turn on or off any antiphishing policy from the GUI and we need to check its status  ( ie enabled/disabled ) from PS we should use the command get-antiphishrule | fl state
 Reference:When you modify an anti-phishing policy, settings related to the name, priority, enabled or disabled, and recipient filters modify the anti-phish rule. All other settings modify the associated anti-phish policy.https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-anti-phishing-policies-eop#:~:text=When%20you%20modify%20an%20anti%2Dphishing%20policy%2C%20settings%20related%20to%20the%20name%2C%20priority%2C%20enabled%20or%20disabled%2C%20and%20recipient%20filters%20modify%20the%20anti%2Dphish%20rule.%20All%20other%20settings%20modify%20the%20associated%20anti%2Dphish%20policy.

 when we run get-antiphishingpolicy | fl enabled  

 it is enabled by default once the policy created.
The parameter "Enabled" in the Get-AntiPhishPolicy is not relevant, and consequently modifying the same with Set-AntiPhishPolicy won't change anything.
 From this  article -Enabled parameter specifies whether the policy is enabled. Valid values are:$true: The policy is enabled. This is the default value.$false: The policy is disabled.https://docs.microsoft.com/powershell/module/exchange/new-antiphishpolicy#:~:text=Exchange%20Online%20Protection-,%2DEnabled,-The%20Enabled%20parameter

so the article  need to be updated as it is very confusing and not accurate
 

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15695a77-5d00-89d9-fba9-74de36ffd4cf
* Version Independent ID: 0e0863e8-82e8-0709-4204-bb406266b2f9
* Content: [Set-AntiPhishPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-antiphishpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-AntiPhishPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mariammorgan, not to get picky, but there's no Enabled _parameter_ on Get-AntiPhishPolicy, so there's nothing to fix there.

The real correction, as you described, is required in the Enabled parameter description on New-AntiPhishPolicy and Set-AntiPhishPolicy, which I did:

- **New-AntiPhishPolicy**:

  > This parameter is reserved for internal Microsoft use.
  >
  > To create a disabled anti-phishing policy (the combination of the antiphish rule and the associated antiphish policy), use `-Enabled $false` on the **New-AntiPhishRule** cmdlet.
  >
  > To enable or disable an existing anti-phishing policy, use the **Enable-AntiPhishRule** or **Disable-AntiPhishRule** cmdlets.
  >
  > In the output of the **Get-AntiPhishRule** cmdlet, whether the anti-phishing policy is enabled or disabled is visible in the State property.

- **Set-AntiPhishPolicy**:

  > This parameter is reserved for internal Microsoft use.
  >
  > To enable or disable an existing anti-phishing policy (the combination of the antiphish rule and the associated antiphish policy), use the **Enable-AntiPhishRule** or **Disable-AntiPhishRule** cmdlets.
  >
  > To create a disabled anti-phishing policy, use `-Enabled $false` on the **New-AntiPhishRule** cmdlet.
  >
  > In the output of the **Get-AntiPhishRule** cmdlet, whether the anti-phishing policy is enabled or disabled is visible in the State property.

OK?

**Comment by mariammorgan** [comment]
@chrisda  thank you, it is clear now

**Comment by yogkumgit** [comment]
@mariammorgan Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
