### ISSUE TITLE
Get-CsOnlineUser missing uservalidationerrors

### ISSUE THREAD

**Issue by LuisEmilioR** [MicrosoftDocs/office-docs-powershell#9718]
When running Get-Csonlineuser and returning more than one user the results are missing the property uservalidationerrors. This does not happen when working with a single identity.

For example if you run "Get-csonlineuser -identity userUPN", uservalidationerrors is included in the results

Instead when running "Get-CsOnlineUser -filter {AccountEnabled -eq $true}" the results do not include this property.

I think it has something to do with the object returned with each command Selected.Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.UserMas and Selected.Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.User respectively.

This is impacting the organization reports as we depend on this in order to take remediate actions.

This is happening on MicrosoftTeams module veersion 4.5.0

**Comment by LuisEmilioR** [comment]
As a matter fact below is the entire list of properties missing when running the above mentioned command:

CountryAbbreviation
LastProvisionTimeStamps
LastPublishTimeStamps
LastSyncTimeStamp
OptionFlags
RegistrarPool
ServiceInstance
SipProxyAddress
TeamsMediaLoggingPolicy
UserValidationErrors
WhenCreated

**Comment by isrumnon** [comment]
Hi @LuisEmilioR we're working on changes to reintroduce these relevant properties by November timeframe for cases when not using the "-Identity" parameter

**Comment by yogkumgit** [comment]
@isrumnon Thank you very much for sharing this information. @LuisEmilioR Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by isrumnon** [comment]
Hi @LuisEmilioR reaching out to you regarding a use case in Teams PowerShell Module - Do you have a requirement to filter based on UservalidationErrors?
