### ISSUE TITLE
Exchange Online v2 services

### ISSUE THREAD

**Issue by idontknowwhattocallit** [MicrosoftDocs/office-docs-powershell#9721]
This cmdlet isn't available in the Exchange Online v2 services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80326e44-6beb-8983-57ab-8333608c504b
* Version Independent ID: 8962c0dc-72a3-208a-33de-6a89cd56b6fc
* Content: [Set-UnifiedGroup (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@idontknowwhattocallit, I just connected to Exchange Online PowerShell using the _UseRPSSession_ switch in v2.0.6-Preview6 and it was available to me.

Of course, you must be actually [connected to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell) for any cmdlets to work. There are a few cmdlets actually baked into the module itself, but those are useless until you actually connect to a tenant.

Also, if you're using a Preview version of v2.0.6 without the  _UseRPSSession_ switch, you're connecting in REST API mode. All of the cmdlets should be available, but a few might temporarily disappear as issues are found and fixed as described [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#updates-for-version-206).

Finally, there's this note at the top of the topic:

> **Note**: You can't use this cmdlet to modify Microsoft 365 Groups if you connect using certificate based authentication (also known as CBA or app-only authentication for unattended scripts). You can use Microsoft Graph instead. For more information, see [Update group](https://docs.microsoft.com/graph/api/group-update).

**Comment by idontknowwhattocallit** [comment]
Yep, it looks like it's just 2.0.6 that's broken.  I downgraded to 2.0.5 and it's working without basic auth.

**Comment by yogkumgit** [comment]
@idontknowwhattocallit Thank you very much for the feedback. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
