### ISSUE TITLE
Missing Get-CsTeamsAppPermissionPolicy on page

### ISSUE THREAD

**Issue by JoeSzo** [MicrosoftDocs/office-docs-powershell#9723]
It looks like there's no entry for Get-CsTeamsAppPermissionPolicy on this page. Can one be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6804423b-8e08-5916-9355-6bebe8bb08b0
* Version Independent ID: aa669763-6470-cc61-ea8d-52aee886f986
* Content: [MicrosoftTeamsPowerShell Module](https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps)
* Content Source: [teams/teams-ps/teams/teams.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @JoeSzo 

This index file only lists the article files that exist under the teams/ folder in the repository.
You will find it on this one instead https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps

Also please take note of this 

>NOTE: The existence of this cmdlet is being documented for completeness, but do not use this cmdlet. We require that all creation and modification of app permission polices (not including the assignment or removal of policies from users) happens in the Microsoft Teams & Skype for Business Admin Center to ensure that the policy matches your expectations for the end user experience.
