### ISSUE TITLE
Example 2 doesn't work in powershell 7

### ISSUE THREAD

**Issue by erichenson** [MicrosoftDocs/office-docs-powershell#9727]
I'm using powershell 2 and Example 2 returns this error:

$UserList = Get-CASMailbox -Filter "HasActiveSyncDevicePartnership -eq `$true -and -not DisplayName -like 'CAS_{*'" | Get-Mailbox
Exception: Unable to index into an object of type "System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.IEnumerable`1[System.String]]".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d1678b-3597-59a2-0f16-63948c3853d2
* Version Independent ID: 35ffe226-1c51-81a5-7ddc-b7439f6f3480
* Content: [Get-MobileDeviceStatistics (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mobiledevicestatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MobileDeviceStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-MobileDeviceStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by erichenson** [comment]
the "| Get-Mailbox" should be removed from the first line.

**Comment by chrisda** [comment]
@erichenson, fixed.

In the future, you too can make updates like this directly in the topic. For instructions see [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).

Thanks for the feedback.

Closing
