### ISSUE TITLE
Related link is no longer valid

### ISSUE THREAD

**Issue by Divya-RP** [MicrosoftDocs/office-docs-powershell#9735]
[Enter feedback here]

The related links is not found :https://docs.microsoft.com/en-us/powershell/module/skype/grant-csteamsmedialoggingpolicy 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d630c7f-0b0b-1699-c5cb-b1787dda521e
* Version Independent ID: 06f74bc0-0863-b2f9-3cc8-48e8df6822b8
* Content: [Grant-CsTeamsMediaLoggingPolicy (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-in/powershell/module/teams/grant-csteamsmedialoggingpolicy?view=teams-ps&source=docs)
* Content Source: [teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md)
* Service: **teams-powershell**
* GitHub Login: @LeoKuhorev
* Microsoft Alias: **leokukharau**

**Comment by get-itips** [comment]
fixed in https://github.com/MicrosoftDocs/office-docs-powershell/pull/9744
