### ISSUE TITLE
Error When Using -Identity Flag for Get-EXOMailboxDeviceStatistics

### ISSUE THREAD

**Issue by obizii** [MicrosoftDocs/office-docs-powershell#9740]
When using the -Identity flag as stated in the documentation, with either the DeviceID or GUID, an error is received.

Get-EXOMobileDeviceStatistics : An error occurred while processing this request..
At line:1 char:1
+ Get-EXOMobileDeviceStatistics -Identity SOMEIDENTITY
    + CategoryInfo          : ProtocolError: (:) [Get-EXOMobileDeviceStatistics], Exception
    + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.Exchange.Management.RestApiClient.GetExoMobileDeviceStatistics

**Comment by chrisda** [comment]
@obizii, the Type value on Identity in Get-ExOMobileDeviceStatistics is 'String' which is not helpful. In the original Get-MobileDeviceStatistics cmdelt on which the ExO cmdlet is based, is 'MobileDeviceIdParameter', and has this description:

> You can use the following values that uniquely identifies the mobile device:
>
> - Identity (`<Mailbox Name>\ExchangeActiveSyncDevices\<MobileDeviceObjectName>` for example, `CarlosM\ExchangeActiveSyncDevices\REST§Outlook§5eec4e941e0748a264512fd83770d5ac`)
> - Distinguished name (DN)
> - GUID (same as ExchangeObjectId)

Instead of Identity, you can use the Mailbox parameter to identify the user by easier values (Name, Alias, etc.).

The version of the module you're using is also a consideration. If you're using v2.0.6-PreviewX, you need to use the _UseRPPSSession_ switch when you connect; otherwise, you're using REST API backed cmdlets. This is all explained [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#updates-for-version-206).

I would suggest using Get-MailboxDeviceStatistics with an Identity value that you can confirm, and then try that same value with Get-EXOMailboxDeviceStatistics.

Report back here with your findings. It might be as simple as the Identity description in Get-EXOMailboxDeviceStatistics is wrong, and needs to be more like Get-MailboxDeviceStatistics.

**Comment by yogkumgit** [comment]
@obizii Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by 666thor** [comment]
> @obizii Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

I have the same error. I can use a Guid from any mobile device (Get-MobileDevice) with the Get-MobileDeviceStatistics -Identity <GUID> cmdlet and retrieve a result. But when I use it with Get-EXOMobileDeviceStatistics -Identity <GUID>, it shows an error that the object cannot be found. According to the documentation using the Guid should be possible - and it has been possible in the past, but now no longer.

Get-EXOMobileDeviceStatistics -Identity <GUID>

`Get-EXOMobileDeviceStatistics -Identity <GUID>

Get-EXOMobileDeviceStatistics : An error occurred while processing this request..
{"error":{"code":"NotFound","message":"Error executing request. ","details":[{"code":"Context","target":"","message":"E
x0FBD0C|Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException|The mobile device
<GUID> cannot be found."}],"innererror":{"message":"Error executing request.
","type":"Microsoft.Exchange.Admin.OData.Core.ODataServiceException","stacktrace":"   at Microsoft.Exchange.Admin.Libra
ry.AdminDirectInvokeProviderBase`3.HandleDirectInvokeCmdletExecutionException(DirectInvokeCmdletExecutionException
directInvokeCmdletExecutionException)\r\n   at
Microsoft.Exchange.Admin.Library.AdminDirectInvokeProviderBase`3.ExecuteAdminCmdlet[TCmdlet,TResult](IDictionary`2
parameters, Action`1 additionParameterDelegate, String parameterSet, Action`1 cmdletInitializationDelegate)\r\n   at
Microsoft.Exchange.Admin.Library.Exo.MobileDeviceStatisticsProvider.GetMobileDeviceStatisticsByIdentity(QueryCon ...
In Zeile:1 Zeichen:1
+ Get-EXOMobileDeviceStatistics -Identity <GUID> ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Protokollfehler: (:) [Get-EXOMobileDeviceStatistics], Exception
    + FullyQualifiedErrorId : Mindestens ein Fehler ist aufgetreten.,Microsoft.Exchange.Management.RestApiClient.GetEx
   oMobileDeviceStatistics`
   
   Tested with 2.0.5 and 2.0.6-Preview7.

**Comment by 666thor** [comment]
> > @obizii Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
> 
> I have the same error. I can use a Guid from any mobile device (Get-MobileDevice) with the Get-MobileDeviceStatistics -Identity cmdlet and retrieve a result. But when I use it with Get-EXOMobileDeviceStatistics -Identity , it shows an error that the object cannot be found. According to the documentation using the Guid should be possible - and it has been possible in the past, but now no longer.
> 
> Get-EXOMobileDeviceStatistics -Identity
> 
> `Get-EXOMobileDeviceStatistics -Identity
> 
> Get-EXOMobileDeviceStatistics : An error occurred while processing this request.. {"error":{"code":"NotFound","message":"Error executing request. ","details":[{"code":"Context","target":"","message":"E x0FBD0C|Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException|The mobile device cannot be found."}],"innererror":{"message":"Error executing request. ","type":"Microsoft.Exchange.Admin.OData.Core.ODataServiceException","stacktrace":" at Microsoft.Exchange.Admin.Libra ry.AdminDirectInvokeProviderBase`3.HandleDirectInvokeCmdletExecutionException(DirectInvokeCmdletExecutionException directInvokeCmdletExecutionException)\r\n at Microsoft.Exchange.Admin.Library.AdminDirectInvokeProviderBase`3.ExecuteAdminCmdlet[TCmdlet,TResult](IDictionary`2 parameters, Action`1 additionParameterDelegate, String parameterSet, Action`1 cmdletInitializationDelegate)\r\n at Microsoft.Exchange.Admin.Library.Exo.MobileDeviceStatisticsProvider.GetMobileDeviceStatisticsByIdentity(QueryCon ... In Zeile:1 Zeichen:1
> 
> * Get-EXOMobileDeviceStatistics -Identity  ...
> * ```
>     + CategoryInfo          : Protokollfehler: (:) [Get-EXOMobileDeviceStatistics], Exception
>     + FullyQualifiedErrorId : Mindestens ein Fehler ist aufgetreten.,Microsoft.Exchange.Management.RestApiClient.GetEx
>    oMobileDeviceStatistics`
>    
>    Tested with 2.0.5 and 2.0.6-Preview7.
>   ```

Tested with EXO version 1.0.1, and it works fine there.

**Comment by 666thor** [comment]
https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#version-101

1.0.1: "Get-EXOMobileDeviceStatistics cmdlet now supports the Identity parameter."

But with version 2.x this is broken, actually with version 2.0.3, 2.0.4, and 2.0.5, as well as 2.0.6-PreviewX.

Is there any chance this gets fixed at some point?

**Comment by chrisda** [comment]
@666thor, see [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#report-bugs-and-issues-for-the-exo-v2-module) for how to capture and collect logs, and send that information to: exocmdletpreview[at]service[dot]microsoft[dot]com.
