### ISSUE TITLE
Links is not working 

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/office-docs-powershell#9742]
THe link to referens dokument is not working. Also it would be good if you could document how long it will take for this policy to be applied to a targeted user. 1h-72h (what MS always refer to as "normal") is not really enough to be doing a fault analysis with end user. 
/Markus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d630c7f-0b0b-1699-c5cb-b1787dda521e
* Version Independent ID: 06f74bc0-0863-b2f9-3cc8-48e8df6822b8
* Content: [Grant-CsTeamsMediaLoggingPolicy (MicrosoftTeamsPowerShell)](https://docs.microsoft.com/en-us/powershell/module/teams/grant-csteamsmedialoggingpolicy?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md)
* Service: **teams-powershell**
* GitHub Login: @LeoKuhorev
* Microsoft Alias: **leokukharau**

**Comment by get-itips** [comment]
Link was fixed in https://github.com/MicrosoftDocs/office-docs-powershell/pull/9744

I'll pass the feedback about replication times.
