### ISSUE TITLE
Resetting winrm auth

### ISSUE THREAD

**Issue by rkearneyrpc** [MicrosoftDocs/office-docs-powershell#9743]
If the winrm baisc auth setting is temporary, the page should also indicate how to capture original setting, or set it back to default.

is basic auth in winrm also required for updates?  that shoudl be specified too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-and-maintain-the-exo-v2-module)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rkearneyrpc, the WinRM auth setting is not temporary, unless you're using v2.0.6-Preview5 or later with REST API backed cmdlets as described [here](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#updates-for-version-206).

The temporary thing is this Note:

> You must temporarily enable WinRM to run the following WinRM commands. You can enable WinRM by running the command: `winrm quickconfig`.

Which, I guess is for those who have WinRM completely disabled, but need to turn on Basic auth?

Honestly, I didn't have much to do with the addition of that Note. I don't understand how you could have WinRM disabled, turn it on to configure Basic auth, but then disable WinRM again? How could you connect if WinRM is disabled?

Would it be less confusing to change the note to something like this:

> The following commands require that WinRM is enabled. To enable WinRM, run the following command:  `winrm quickconfig`.

**Comment by rkearneyrpc** [comment]
> Would it be less confusing to change the note to something like this:
> 
> > The following commands require that WinRM is enabled. To enable WinRM, run the following command:  `winrm quickconfig`.

That sounds perfect!

**Comment by chrisda** [comment]
OK. Done.

Thanks for the feedback.

Closing
