### ISSUE TITLE
Teams module 4.6.0: Get-CsOnlineUser RegistrarPool value is not shown when returning multiple users 

### ISSUE THREAD

**Issue by horsi3** [MicrosoftDocs/office-docs-powershell#9751]
The RegistrarPool value appears when you look up a single teams user account, but when the query returns multiple users, the same value is blank for all users which otherwise do show the value when done seperately.

![image](https://user-images.githubusercontent.com/102339348/182515854-2f332b8a-2949-4693-b82b-d8a9c4689662.png)

**Comment by isrumnon** [comment]
Hi @horsi3 RegistrarPool is a legacy attribute that we will be deprecating soon for all our Teams customers (unless you have some OnPrem presence) so this will not be removed from the single user queries as well in the future

**Comment by horsi3** [comment]
> Hi @horsi3 RegistrarPool is a legacy attribute that we will be deprecating soon for all our Teams customers (unless you have some OnPrem presence) so this will be removed from the single user queries as well in the future

OK thanks for that. That's interesting because this is so far the only attribute that distinguishes between a room and a user account for us, maybe i'm doing something wrong. I'll log a ticket with 365 support on that one.
Cheers :)

**Comment by isrumnon** [comment]
For this scenario you may choose to use a new Parameter we've introduced called AccountType. 

This parameter is added to Get-CsOnlineUser starting from TPM 4.5.1 to indicate the user type. The possible values for the AccountType parameter are:

User - to query for user accounts.
ResourceAccount - to query for app endpoints or resource accounts. (like your room account)
Guest - to query for guest accounts.
Unknown - to query for a user type that is not known.

**Comment by horsi3** [comment]
> For this scenario you may choose to use a new Parameter we've introduced called AccountType.
> 
> This parameter is added to Get-CsOnlineUser starting from TPM 4.5.1 to indicate the user type. The possible values for the AccountType parameter are:
> 
> User - to query for user accounts. ResourceAccount - to query for app endpoints or resource accounts. (like your room account) Guest - to query for guest accounts. Unknown - to query for a user type that is not known.

Thanks I did notice that attribute but our room accounts still appear as 'User' accounttype. Is there a cmdlet within powershell that lets you change that to 'ResourceAccount' ? The problem I appear to have is that our resource accounts are not being recognized as such when we sync them to AAD and assign a room license.

**Comment by isrumnon** [comment]
@pbafna03 are you aware of such a cmdlet?

**Comment by pbafna03** [comment]
This might be helpful - https://docs.microsoft.com/en-us/microsoftteams/rooms/with-office-365?tabs=existing-account%2Cazure-active-directory2-password%2Cactive-directory2-license#create-a-resource-account 

Best would be to reach out to support with the specific details, they'll be able to help better.

**Comment by horsi3** [comment]
Thanks, yeah, i've followed all the documentation already but no luck. I'll see if 365 support can find a solution.
Thanks again.
