### ISSUE TITLE
Typo. Sentence should read: "Sweep rules run a[t] regular intervals to help keep your Inbox clean."

### ISSUE THREAD

**Issue by SubhMSFT** [MicrosoftDocs/office-docs-powershell#9758]
Sentence reads: Sweep rules run a regular intervals to help keep your Inbox clean.
Should read: Sweep rules run at regular intervals to help keep your Inbox clean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5783e9b5-c56b-f92f-0d52-2265136381d9
* Version Independent ID: 8f2a8fc3-af9c-9cf4-dfa7-b602aca74c98
* Content: [Get-SweepRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-sweeprule?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/Get-SweepRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-SweepRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SubhMSFT, fixed. The same typo also existed in New-SweepRule.

In the future, you too can make changes like this yourself. No need to open an Issue about it first. For instructions, see:

<https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md>

Thanks for the feedback.

Closing
