### ISSUE TITLE
Name of the module

### ISSUE THREAD

**Issue by TCorrege** [MicrosoftDocs/office-docs-powershell#976]
I would appreciate if module name was referenced in the document...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f089a8d5-643e-527e-3f5e-93ee4b7660e0
* Version Independent ID: 848584ea-f6f0-340d-f65d-c58ee19181ed
* Content: [Get-DistributionGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/get-distributiongroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Get-DistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Get-DistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@TCorrege, Exchange Server and anything Exchange related in the cloud (Exchange Online, Office 365 Security & Compliance Center, Exchange Online Protection) don't use the concept of PowerShell modules per-se. All connections are done via remote PowerShell. Even when you open the Exchange Management Shell directly on an Exchange Server, you're actually remoting into the server itself. And for the cloud workloads, you can only use remote PowerShell to connect.

That being said, we're working on a way to filter the cmdlet reference topics and Exchange PowerShell conceptual/procedural topics by workload (Exchange 2010, 2013, 2016, ExO SCC or EOP).

Until then, you should be able to use the Applies To: field at the top of every topic to verify which version of Exchange the topic applies to.

Thanks for the feedback.
