### ISSUE TITLE
-PrivateKeyExportable

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/office-docs-powershell#9760]
-PrivateKeyExportable
The PrivateKeyExportable parameter specifies whether the new self-signed certificate has an exportable private key, and controls whether you can export the certificate from the server (and import the certificate on other servers). Valid values are:

Can we change the verbiage? You would also use -PrivateKeyExportable when requesting a certificate from a CA, not just self-signed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c94a635-7439-5bc2-3a1a-7661d79b24b8
* Version Independent ID: b608c709-cc1b-6b1f-e78f-6bab62072364
* Content: [New-ExchangeCertificate (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-exchangecertificate?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ExchangeCertificate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ExchangeCertificate.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dkotars, the PrivateKeyExportable parameter on Import-ExchangeCertificate is generic as you're requesting.

I did a bunch of testing/rewriting of certificate content for the Exchange 2016 wave. I can't say I remember the circumstances, but I made it clear that PrivateKeyExportable is meaningful only for self-signed certificates, both in the text you quoted, and this statement:

> This parameter is only meaningful for new self-signed certificates.

I can see from the parameter sets that PrivateKeyExportable is available for both requests and new (self-signed) certificates.

After you get the certificate from the CA, wouldn't you use PrivateKeyExportable on the Import-ExchangeCertificate command when you install it on the Exchange server? Does the CA really care whether you want the private key to be exportable or not (would they even allow that)?

**Comment by dkotars** [comment]
Hi Chris -

Just had a customer that followed this guidance to request a new exchange 2016 certificate:

$txtrequest = New-ExchangeCertificate -GenerateRequest [-FriendlyName <DescriptiveName>] -SubjectName C=<CountryOrRegion>[,S=<StateOrProvince>,L=<LocalityOrCity>,O=<Organization>,OU=<Department>],CN=<HostNameOrFQDN> [-DomainName <Host1>,<Host2>...] [-KeySize <1024 | 2048 | 4096>] [-Server <ServerIdentity>]
[System.IO.File]::WriteAllBytes('<FilePathOrUNCPath>\<FileName>.req', [System.Text.Encoding]::Unicode.GetBytes($txtrequest))

As per this article: https://docs.microsoft.com/en-us/exchange/architecture/client-access/create-ca-certificate-requests?view=exchserver-2016

They then imported the cert using the command Import-ExchangeCertificate -FileData ([System.IO.File]::ReadAllBytes('<FilePathOrUNCPath>')) [-Password (ConvertTo-SecureString -String '<Password> ' -AsPlainText -Force)] [-PrivateKeyExportable <$true | $false>] [-Server <ServerIdentity>]

With the -PrivateKeyExportable $true flag.  When they attempted to export the cert and install on another Eschange server, the cert was not importable. 

Did the same in my test environment with Digicert, my New-ExchangeCertificate request without the -PrivateKeyExportable flag did not allow me to export after running the import with the -PrivateKeyExportable $true.  

It DID allow me to export when I sent the initial request with the -PrivateKeyExportable $true parameter.  Perhaps it is specific to the CA, but I reached out to some Exchange Team, peers and they had mentioned that, yes, you need to add the -PrivateKeyExportable $true parameter when running the initial request.

**Comment by chrisda** [comment]
OK. Fixed.

Thanks for the feedback.

Closing
