### ISSUE TITLE
-TargetWebUrl

### ISSUE THREAD

**Issue by ivan-wolfhelm** [MicrosoftDocs/office-docs-powershell#977]
Can you use the '-TargetWebUrl' switch with this PS command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a99ae6ea-f1ca-1d6f-bdda-abc8cf4082ae
* Version Independent ID: 066c87bc-6767-ae13-7f31-d9591f7e0536
* Content: [Add-SPOTheme (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Add-SPOTheme?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTheme.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTheme.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by VesaJuvonen** [comment]
That is not supported. This cmdlet is for adding theme to the tenant level, not for activating theme in the site level.
