### ISSUE TITLE
Missing shared channel options

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/office-docs-powershell#9771]
There is no information about the new parameters for this cmdlet - 

AllowSharedChannelCreation                    
AllowChannelSharingToExternalUser         
AllowUserToParticipateInExternalSharedChannel 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a705a9a-ef02-2453-6267-e0b2908a2ad9
* Version Independent ID: 1a93b451-ab23-3290-0c36-bb8498d01bdb
* Content: [New-CsTeamsChannelsPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-CsTeamsChannelsPolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment]
Thanks for your feedback!
