### ISSUE TITLE
Update documentation to show that SignatureHTML and SignatureText may be incorrect

### ISSUE THREAD

**Issue by benrfairless** [MicrosoftDocs/office-docs-powershell#9780]
Please refer to the changes made to Set-MailboxMessageConfiguration here: https://github.com/MicrosoftDocs/office-docs-powershell/commit/010ecfb815b9b57777b24154d755b0ab6e0a87f9. 

Similar changes should be made to the documentation on Get-MailboxMessageConfiguration for consistency, so that people know that the information in SignatureHTML and SignatureText is not accurate if roaming signatures are enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6cc612f-3d7c-8f61-ec3c-7c260c3780d3
* Version Independent ID: 42cdbe28-2e04-ddf1-aa75-d0164ef32645
* Content: [Get-MailboxMessageConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailboxmessageconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-MailboxMessageConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-MailboxMessageConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@benrfairless, OK. Done.

Thanks for the feedback.

Closing
