### ISSUE TITLE
Syntax errors on Export-ExchangeCertificate Example text

### ISSUE THREAD

**Issue by petermuhroads** [MicrosoftDocs/office-docs-powershell#9781]
Your code doesn't work!  The "example code 2" contains -BinaryEncoded twice.  

Also, I keep getting an error:

      A positional parameter cannot be found that accepts argument '[System.IO.File]::WriteAllBytes'.

Can't you just make this easier to use, especially since removing functionality from EMC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53414a2-974c-c887-3fee-2c166105973a
* Version Independent ID: 2a07c560-eceb-25df-f736-c10251ec3e9b
* Content: [Export-ExchangeCertificate (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/export-exchangecertificate?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Export-ExchangeCertificate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Export-ExchangeCertificate.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@petermuhroads, thanks for catching the double -BinaryEncoded thing.

There are two separate commands in Example 2 (and Example 4). I added a carriage return between each command to clarify. When I ran each command one at a time, the commands worked.

I also took the liberty of placing a carriage return before all examples that use `[System.IO.File]::WriteAllBytes` commands for clarity in all other cmdlet topics.

OK?

**Comment by petermuhroads** [comment]
Yes, thank you!  I’m sure that will help!  

 

I ended up using MMC with Certificate snap in to complete my work today, but hopefully next time I can go back to my preferred Exchange methods.

**Comment by yogkumgit** [comment]
@petermuhroads Thanks.  If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
