### ISSUE TITLE
RecipientFilter parameter for EXO DDGs doesn't allow wildcard prefixes

### ISSUE THREAD

**Issue by rbishop-etq** [MicrosoftDocs/office-docs-powershell#9783]
https://docs.microsoft.com/en-us/powershell/exchange/recipientfilter-properties?view=exchange-ps#filterable-recipient-properties 
As explained on this page, 
"In Exchange Online PowerShell, you can't use the wildcard as a prefix (for example, "Property -like '*abc'") is not allowed"

Please change this - we need to be able to use wildcards in any part of the string when using the "-like" operator, and this limitation preventing wildcard prefixes should be removed so we can more correctly utilize the "-like" operator as it was designed. Currently this "-like" operator only functions in a "startswith" manner since we cant put wildcards at the start of the value and search for the given string in ANY portion of the field being checked.
We need to use these in dynamic membership rules including DDGs to set memberships based on various fields.

**Comment by chrisda** [comment]
@chrisda, all we can do here is fix documentation. Your best path forward is to open a support ticket.

**Comment by rbishop-etq** [comment]
Hi,
Not sure what you mean. On the article are two options: submit feedback for "this product" and "this page". I selected the "This product" one in order to give feedback on the actual product/function and was taken here where i submitted this "New Issue" which was the only button available for submitting a new record. If this is not the correct spot to give feedback for the PRODUCT as opposed to the page only, then the link needs to be corrected.

**Comment by rbishop-etq** [comment]
@chrisda not sure if you meant to direct your comment to somebody else, as you only tagged yourself.
I opened this issue by selecting the option on that page to submit feedback on "THIS PRODUCT" as opposed to submitting feeback on "This Page", so if there is another more appropriate way to submit feedback on the product/function then that link will need to be updated.

**Comment by chrisda** [comment]
Funny how I tagged myself. I thought the ability to leave product feedback was turned off in this repo. I guess not.

But, the best path forward is still to open a support ticket.

**Comment by yogkumgit** [comment]
@rbishop-etq Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by rbishop-etq** [comment]
Please fix the page to have the product feedback option take you to the correct spot.

**Comment by rbishop-etq** [comment]
@chrisda please stop closing this. If the page is directing me HERE to submit feedback on the product and this is incorrect as you say, then the page does have a flaw that needs to be corrected.

**Comment by chrisda** [comment]
@rbishop-etq, I can leave it open if you like. Be advised that this has been an issue since we first moved onto the GitHub platform back in early 2018, and there is no solution to date.

**Comment by yogkumgit** [comment]
@rbishop-etq hope you understand this limitation. We proceed here to close it. We appreciate your contribution in improving the documentation. Thanks for taking out some time to open the issue. .
