### ISSUE TITLE
Bunch of Powershell parameters with no description provided

### ISSUE THREAD

**Issue by Harikumar77** [MicrosoftDocs/office-docs-powershell#9796]
There are PowerShell parameters for the New-DLPComplianceRule with no description provided.  For eg.  -ContentFileTypeMatches
{{ Fill ContentFileTypeMatches Description }}, ContentIsShared, DocumentCreatedBy etc.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98894097-1935-bd41-7857-5309d31817ee
* Version Independent ID: c8e1fd27-2bd4-ea13-5493-cf39450b715e
* Content: [New-DlpComplianceRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-dlpcompliancerule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-DlpComplianceRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-DlpComplianceRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Harikumar77, empty parameter descriptions are a known issue. Availability vs. functionality for parameters are two different things. See [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) for more explanation.

So are you trying to use these parameters, possibly from the direction of blog posts or other content, or are you just pointing out that the description are empty?

**Comment by Harikumar77** [comment]
Thank you Chris for your response.  I shared the article with a customer to use some of those parameters which has a blank description.

Thanks
Hari

**Comment by yogkumgit** [comment]
@Harikumar77  as it is a known issue and in state of work in progress. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
