### ISSUE TITLE
Return Types/Objects Not Documented

### ISSUE THREAD

**Issue by kirkpabk** [MicrosoftDocs/office-docs-powershell#980]
The return types/objects appear to not be documented.  Expected returned samples...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502427ff-b3ec-a619-ab19-ee4b4ef86854
* Version Independent ID: 05a343a1-64ff-51d2-8eb0-e0dc41efea9f
* Content: [Get-SPEnterpriseSearchTopology (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spenterprisesearchtopology?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Get-SPEnterpriseSearchTopology.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Get-SPEnterpriseSearchTopology.md)
* Service: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@kirkpabk thank you for your submission.  If you are referring to the Input or Output sections, these are part of the schema template, but we do not use them, so they are left blank intentionally.  thank you.
