### ISSUE TITLE
Set-CsPhoneNumberAssignment execution quotas and double verification of the assignment

### ISSUE THREAD

**Issue by zaichornik** [MicrosoftDocs/office-docs-powershell#9806]
Dear Team, 

I have 2 questions in **DirectRouting** scenario:

1) Are there any executions quotas within a time range for _Set-CsPhoneNumberAssignment_  ?

2) Do I need to double check the configuration/assignment made during exec of  _Set-CsPhoneNumberAssignment_ with the additional command _Get-CsPhoneNumberAssignment_ (with combination of  _ActivationState_   & _PstnAssignmentStatus_    parameters. Or lack of any exceptions / errors during execution of _Set-CsPhoneNumberAssignment_  is sufficient? 

Note: Since I have custom management of the state of the phone number and the Number management+Set-CsPhoneNumberAssignment are part of 1 system transaction - single command run is the only option. 

Thanks in advance.

**Comment by JensTrier** [comment]
@zaichornik Thanks for the feedback/questions.

Ad 1) not that I'm aware of. If you hit anything that smells like this, please open a Microsoft support case with details and they will investigate what's going on.

Ad 2) If Set-CsPhoneNumberAssignment succeeds, i.e. does not report any error, the phone number has been assigned, so there is no need to check it afterwards.

**Comment by yogkumgit** [comment]
@zaichornik Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
