### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by gotfondue** [MicrosoftDocs/office-docs-powershell#981]
-InternalUrl
The ExternalURL parameter specifies the URL that's used to connect to the virtual directory from outside the firewall.

I think this is incorrect, and should read:

-InternalUrl
The InternalURL parameter specifies the URL that's used to connect to the virtual directory from inside the firewall.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7366ac44-ae0f-6924-7f1f-db30b2292808
* Version Independent ID: 54d78b94-576b-c7ce-525c-e5e85836898d
* Content: [Set-EcpVirtualDirectory (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/client-access-servers/Set-EcpVirtualDirectory?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/client-access-servers/Set-EcpVirtualDirectory.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/client-access-servers/Set-EcpVirtualDirectory.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gotfondue, you're correct, and I fixed it as you described. In the future, if you have proposed changes to Exchange cmdlet reference topics (or any topics on docs.microsoft.com, for that matter) you are more than welcome to edit the topic directly by clicking the Edit button (the pencil). Someone will review your pull request and accept it if your proposed changes are correct (or reject them with an explanation if they aren't correct).

Thanks for the feedback.
