### ISSUE TITLE
About the description on the -Scope parameter of the New-ComplianceSearchAction command

### ISSUE THREAD

**Issue by komiyamo** [MicrosoftDocs/office-docs-powershell#9811]
The documentation states that the -Scope parameter is only meaningful for content searches where IncludeUnindexedItemsEnabled is $True, is this still something to consider?

![image](https://user-images.githubusercontent.com/84306478/185279170-50ee05e5-64b6-46e0-8b1e-0b974acd4e0e.png)

Currently, there is no parameter in the New-ComplianceSearch command that specifies IncludeUnindexedItemsEnabled, and I could not find a scenario where IncludeUnindexedItemsEnabled would be $false.

https://docs.microsoft.com/powershell/module/exchange/new-compliancesearch

If this is not a particular consideration at this time, it would be less confusing to not include this note.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad8adee-7f9d-757b-2069-95ecab232747
* Version Independent ID: c71194df-8f65-15aa-3ed2-b370b8c3f629
* Content: [New-ComplianceSearchAction (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearchaction?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ComplianceSearchAction.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ComplianceSearchAction.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@komiyamo, note removed.

Thanks for the feedback.

Closing
