### ISSUE TITLE
EnableMobileMailboxPolicyWhenCAInplace param description is missing

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/office-docs-powershell#9812]
Hello,

The Set-ActiveSyncOrganizationSettings cmdlet's EnableMobileMailboxPolicyWhenCAInplace parameter does not have a description.

I can't find any additional documentation elsewhere that explains its purpose or how it works.

Could someone please update as appropriate?

Thank you,
Keith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4042456f-c491-ad7d-e772-eef18ba6b0df
* Version Independent ID: 15a4ec1c-16b0-8516-ab4a-4564adac5c62
* Content: [Set-ActiveSyncOrganizationSettings (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-activesyncorganizationsettings?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-ActiveSyncOrganizationSettings.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-ActiveSyncOrganizationSettings.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mrkeiths, see the explanation [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) about empty parameter descriptions. Availability vs. functionality are two different things.

Unless other content sources contain scenarios that use this parameter, I wouldn't worry about it.

If you really want to know, you can open a support ticket.

**Comment by mrkeiths** [comment]
Ok. Thanks Chris.  I understand that certain params are reserved for internal MSFT use.  I've always interpreted this to mean there are special use-cases that justify exposing, but customers should avoid using unless told to do so directly by MSFT.

I know there are many cmdlets and even more params but it sure would be great if the various Product Groups made more of an investment to maintain documentation (to avoid confusion and not consume my time, or your time discussing).

In this case, the param I reported appears to have a placeholder and seemed to me as though it were overlooked (almost as if a template was used).  But based on your response in #7429, you are recommending these be treated the same as 'reserved'.

I'll accept your explanation.  Like you say, I can always open a case.  You answered my question and may close this request.

Thank you for your time,
Keith
