### ISSUE TITLE
Whiteboard PS module returns whiteboards stored in Azure storage only

### ISSUE THREAD

**Issue by chris4182** [MicrosoftDocs/office-docs-powershell#9813]
The WhileBoard module only returns the whiteboards stored in Azure storage,, but with the latest change in storage from Azure to OneDrive, any newly created WhiteBoards are not returned

**Comment by Ahemmad** [comment]
Thanks Chris for posting it, Observed same. Wanted to move Whiteboards from One user to other but we were managed to move whiteboards stored in Azure but not from OneDrive.

**Comment by get-itips** [comment]
Hello @chris4182 how are you?
I'll try to pass this information however, here, we are limited to documentation fixes and improvements.
Thanks
