### ISSUE TITLE
Export-ActivityExplorerData does not recognize the outputformat parameter.

### ISSUE THREAD

**Issue by dr00208** [MicrosoftDocs/office-docs-powershell#9814]
Export-ActivityExplorerData does not recognize the outputformat parameter.

Export-ActivityExplorerData -StartTime "08/18/2022 07:15 AM" -EndTime "08/18/2022 11:08 AM" -outputformat JSON

Export-ActivityExplorerData : A parameter cannot be found that matches parameter name 'outputformat'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f188a25-7afc-f6cf-5d2a-5bc9fd08ca1f
* Version Independent ID: 33ed55ee-de0e-2c0c-2141-9a21083392cd
* Content: [Export-ActivityExplorerData (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/export-activityexplorerdata?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Export-ActivityExplorerData.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Export-ActivityExplorerData.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dr00208, confirmed. I removed all direct and indirect references.

Thanks for the feedback.

Closing
