### ISSUE TITLE
IsMemberAllowedToEditContent parameter missing description

### ISSUE THREAD

**Issue by gkneale** [MicrosoftDocs/office-docs-powershell#9822]
Parameter details are missing.

-IsMemberAllowedToEditContent
{{ Fill IsMemberAllowedToEditContent Description }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80326e44-6beb-8983-57ab-8333608c504b
* Version Independent ID: 8962c0dc-72a3-208a-33de-6a89cd56b6fc
* Content: [Set-UnifiedGroup (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gkneale, empty parameter descriptions are a know issue. Availability vs. functionality are two different things. For an explanation, see [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486) about empty parameter descriptions. Availability vs. functionality are two different things.

So are you trying to use this parameter, possibly from the direction of a blog post or other content, or are you just pointing out that the description is empty?

**Comment by yogkumgit** [comment]
@gkneale As mentioned this is a known issue, hope the comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
