### ISSUE TITLE
Incorrect sample code

### ISSUE THREAD

**Issue by kekici** [MicrosoftDocs/office-docs-powershell#9828]
[Enter feedback here]

Set-TransportAgent "Test App" -Priority 3 -TransportService -FrontEnd

this should be 

Set-TransportAgent "Test App" -Priority 3 -TransportService FrontEnd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e04710-69e6-f8b9-e999-606dea918253
* Version Independent ID: a07c4a95-849f-5701-945d-97b61680ec3b
* Content: [Set-TransportAgent (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-transportagent?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-TransportAgent.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-TransportAgent.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by kekici** [comment]
Also on the same documnetation we shoult tell

TransportService is optional parameter.

**Comment by chrisda** [comment]
@kekici, I corrected the typo in the example. 

Thank for the feedback.

Closing
