### ISSUE TITLE
Set-SPOSiteScript requires Identity parameter?

### ISSUE THREAD

**Issue by aaronmi** [MicrosoftDocs/office-docs-powershell#983]
Does Set-SPOSiteScript require "-Identity" parameter?
The document at https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Set-SPOSiteScript?view=sharepoint-ps does not list the parameter. However when executing Set-SPOSiteScript, it prompts for Identity parameter input.

What about Set-SPOSiteDesign?

**Comment by VesaJuvonen** [comment]
Fixed now.
