### ISSUE TITLE
The URL https://technet.microsoft.com/library/mt587091.aspx to connect to Security and Compliance is incorrect

### ISSUE THREAD

**Issue by andshill7** [MicrosoftDocs/office-docs-powershell#984]
To connect to the Security and Compliance centre, the URI needs to be https://ps.compliance.protection.outlook.com/powershell-liveid/. This is detailed in the following URL: 
https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e86a033-a386-9720-6ef8-a98b6681ec52
* Version Independent ID: 46bd22ba-d92e-c781-fdc6-5a0303985bd8
* Content: [Get-DlpSensitiveInformationTypeRulePackage (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/get-dlpsensitiveinformationtyperulepackage?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpSensitiveInformationTypeRulePackage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-dlp/Get-DlpSensitiveInformationTypeRulePackage.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@andshill7, the TechNet URL https://technet.microsoft.com/library/mt587091.aspx is supposed to redirect to https://docs.microsoft.com/powershell/exchange/office-365-scc/office-365-scc-powershell. I can't make the fix myself, but I've taken the necessary steps to get it fixed. It's a really simple fix, and it should be resolved quickly.

Thanks for the feedback.
