### ISSUE TITLE
Adding locations via script clarification

### ISSUE THREAD

**Issue by cloudhal** [MicrosoftDocs/office-docs-powershell#9857]
The article states several times:
You can enter multiple values separated by commas. If the values contain spaces or otherwise require quotation marks, use the following syntax: "Value1","Value2",..."ValueN".
This works if manually entering a command, however for 100's or entries clearly this is not practical. If using this syntax in a script it does not work, i.e. if you manually create a string variable containing "Value1","Value2",..."ValueN".

**Comment by yogkumgit** [comment]
@cloudhal Please indicate which document /article you are referring to Thanks

**Comment by chrisda** [comment]
@cloudhal, without knowing which topic you're talking about, that looks like Exchange cmdlet text. I can say that you should be able to create a variable with any number of entries and then use that entry for the parameter value like this:

```powershell
$x = "value1","value2,"value3",..."valueN"

... -Parameter $x
```

**Comment by cloudhal** [comment]
> @cloudhal, without knowing which topic you're talking about, that looks like Exchange cmdlet text. I can say that you should be able to create a variable with any number of entries and then use that entry for the parameter value like this:
> 
> ```powershell
> $x = "value1","value2,"value3",..."valueN"
> 
> ... -Parameter $x
> ```

Sorry I was referring to Set-RetentionCompliancePolicy https://docs.microsoft.com/en-us/powershell/module/exchange/set-retentioncompliancepolicy?view=exchange-ps

cmdlet doesn't seem to support pipe or using a variable when adding locations, which makes it unusable in scripts or larger environments.

**Comment by chrisda** [comment]
@cloudhal, you should open a support ticket. That will get this issue in front of decisions makers and people who are capable of fixing the problem (and also puts them on notice that there's a problem). Fundamentally, any parameter where Type = MultiValuedProperty should support the syntax that I described.

I would also suggest trying different types of identifiers (all of the same kind) to see if that makes a difference. For example, if you were using Name values, try using EmailAddress or (the big gun) DistinguishedName values.

**Comment by cloudhal** [comment]
OK thanks @chrisda

**Comment by yogkumgit** [comment]
@cloudhal Thanks.  If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
