### ISSUE TITLE
Basic Auth Query

### ISSUE THREAD

**Issue by smitz1** [MicrosoftDocs/office-docs-powershell#9858]
Hi,

Does this module support certificate auth and an Azure App ?

Is it planned ?

**Comment by yogkumgit** [comment]
@smitz1 Please indicate which document/article you are referring to. Thanks

**Comment by smitz1** [comment]
The Connect-MicrosoftTeams commmand, with Basic auth going away on 1st Oct we have been following microsoft atcicle to ceate an Azure App where we add a cert and authenticate to o365 via the private cert. Is this coming ?

**Comment by pbafna03** [comment]
Hi @smitz1, 

2 updates: 

(a) With versions 4.x.x or later, enablement of basic authentication is not needed anymore in Commercial Environments.

(b) App based authentication is work in progress and upcoming. 

Thanks,

**Comment by yogkumgit** [comment]
@smitz1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
