### ISSUE TITLE
Can we suppress/remove this article for now?

### ISSUE THREAD

**Issue by CLYVR** [MicrosoftDocs/office-docs-powershell#9865]
Hi there - is there any way we can suppress/hide this article?  These features aren't ready for public consumption yet  - target launch is CY23Q1. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5336097c-e78a-61d1-be38-fb7642ec9b38
* Version Independent ID: f6b4b3d3-7cad-d0af-5f10-ce9f0d98cf79
* Content: [New-CsTeamsVoiceApplicationsPolicy (MicrosoftTeamsPowerShell)](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsvoiceapplicationspolicy?view=teams-ps&branch=main)
* Content Source: [teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by ruudvanstrijp** [comment]
Interesting to see this early documentation. It doesn't contain any ability to change Business Hours or Holidays, only the greetings for those scenario's. I hope this feature will be added though, one of the main self-service requests is changing your own holidays.

Not sure if this comment is in the right place here, but I wouldn't know how else to raise this question.

**Comment by get-itips** [comment]
Hello @CLYVR I am looking into this.

**Comment by CLYVR** [comment]
@tiburd THANK YOU!  Greatly appreciated.  I will reach out in CY23Q1 when this feature is expected to go live to have the page visible in searches and such.
