### ISSUE TITLE
Email user with telephone number information

### ISSUE THREAD

**Issue by ranukher** [MicrosoftDocs/office-docs-powershell#9868]
Currently the Teams admin center (GUI) allows you to send email to the user when you assign or change their number, is there a same option available in Powershell or graph API?
I have attached a sample email
![phone_num](https://user-images.githubusercontent.com/107161406/188303029-3d18e49d-4e5a-4a2e-8541-a0886e971b4d.png)

**Comment by JensTrier** [comment]
@ranukher thanks for the feedback. This functionality is not integrated into the assignment cmdlet, you'll need to send the e-mail out of band. However we have heard similar feedback from others and are looking into it. No guarantee or ETA :-)

Feel free to close this issue
