### ISSUE TITLE
Basic authentication won't connect anymore

### ISSUE THREAD

**Issue by omarmallat** [MicrosoftDocs/office-docs-powershell#9874]
It looks like Basic authentication won't connect anymore. You can opt in to reenable it, but god knows till when it remains open. and here is the main question to get a permanent solution:
How to automate exchange commands (PowerShell, Graph, SDK...) from azure web app (webjobs) or azure function apps or any other options but not a VM or server? we have no physical server, nor a VM in our environment so here are my limitations:
1. Basic authentication stopped working, and it's not an option anymore. This was the only option to execute exchange PowerShell commands from azure web app or function app.
2. In modern authentication, you rely on the ExchangeOnlineManagement that must be installed prior to any call. since I work on web app, or function app, I cannot install it.
3. there is no .net Exchange SDK.
4. MS Graph lack Exchange functions.

So what is the solution to execute Exchange command? Maybe the solution is available but I'm not aware of it.
Case: Upon the expiration of an user account, I need to call some MS Graph to change some user properties, and since Graph cannot yet perform Exchange Online functions, I'm using currently ExchangeOnlineManagement powershell to setup an auto reply message, so sender can know the email account is no longer monitored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10052620-9909-c335-1913-fdf9db8ab16b
* Version Independent ID: e4be7843-4540-96fd-dcd8-09d6b91a4249
* Content: [Basic auth - Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/basic-auth-connect-to-exo-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/basic-auth-connect-to-exo-powershell.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@omarmallat, you should open a support case and ask your questions. Report anything you find that we can add to the documentation here.

**Comment by DMoenks** [comment]
@omarmallat, if using alternative Azure services is a viable option for you, using an Azure automation runbook might be something to look at. As far as I can tell, they provide many features also available in Azure function apps, but in addition allow for additional PowerShell modules to be installed and then used within scripts.

Doing so allows to use the authentication method described in [App-only authentication for unattended scripts in the EXO V2 module](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps). You might also take a glance at [DMoenks/exchange-online-automatic-replies](https://github.com/DMoenks/exchange-online-automatic-replies) where I used this for a similar use case in a production scenario and I'm quite pleased with how this authentication method works for everyday use.

**Comment by DMoenks** [comment]
After giving it a second thought, I don't know what could be done from a documentation perspective in this case, as the Exchange Online PowerShell documentation already has an article on unattended usage for automation scenarios, as linked in the previous comment. How this scenario can be implemented with Azure services seems highly specific and, although both Azure and Exchange Online are Microsoft products, might not fit in Exchange Online documentation.

**Comment by omarmallat** [comment]
Somehow I agree with you asking why this question is on the documentation side! Surely, you better understand the scope of these documents. But let me just make a suggestion.
Consider a user who opens the documentation to understand and clarify options on how to connect to Exchange Online Management.
The documentation explains two options, Connect-ExchangeOnline which requires pre-installation and New-PSSession which does not require installation, but has recently stopped working with Basic Authentication.
Readers who cannot install the module are left without options. I think a small hint on Azure automation is really helpful and is worth mentioning.
You just gave me the solution, after me asking... but if that link to azure automation was in the documentation, I won't ask :)
Thank you very much.

**Comment by DMoenks** [comment]
I feel you, as I'm just an Exchange Online administrator myself, working for a company other than Microsoft, so I faced the same challenge myself some time ago. And it is from this perspective, that I doubt mentioning specific implementation approaches might help.
Sure, both are Microsoft products, so this might provide a reason to do so. But I suppose there's a fine line between providing one specific implementation approach in combination with another Microsoft product and having other people request implementation approaches for other cloud services or third-party automation suites.

I might very well be mistaken with this point of view, of course. This is merely an opinion, nothing more.

**Comment by chrisda** [comment]
@omarmallat I would suggest that you edit the topic directly to say what you want to say, where you want to say it, and link to what you want to link to. It's quite easy; instructions are [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/README.md).
