### ISSUE TITLE
Error's happening with Set-CsPhoneNumberAssignment and Remove-CsPhoneNumberAssignment

### ISSUE THREAD

**Issue by j-hinks** [MicrosoftDocs/office-docs-powershell#9875]
Hi,

We have noticed this afternoon that when trying to run the following commands, we are getting back Service Unavailable or Unknown Error:

Set-CsPhoneNumberAssignment -Identity <<SipAddress>> -PhoneNumber <<UsersDDI>> -PhoneNumberType DirectRouting

Tried this with multiple users and telephone numbers, getting the same issue, plus different office 365 tenants.

**Comment by JensTrier** [comment]
@j-hinks thanks for the feedback. Please open a Microsoft support case and provide date/time and tenant id and they will investigate it.
