### ISSUE TITLE
Example 2 misleading

### ISSUE THREAD

**Issue by pstakuu** [MicrosoftDocs/office-docs-powershell#9876]
The believe the second example on this page:

https://docs.microsoft.com/powershell/module/exchange/set-mailboxautoreplyconfiguration#example-2

is misleading as:

Set-MailboxAutoReplyConfiguration -Identity tony@contoso.com -AutoReplyState Enabled -InternalMessage "Internal auto-reply message." -ExternalMessage "External auto-reply message."

Will only work if the -ExternalAudience parameter had already been provided in a previous command against the mailbox, and set to Known or All, as indicated by the details of the -ExternalMessage parameter:

The value of this parameter is meaningful only when both of the following conditions are true:

The AutoReplyState parameter is set to Enabled or Scheduled.

The ExternalAudience parameter is set to Known or All.

I suggest it be replaced with this:

Set-MailboxAutoReplyConfiguration -Identity tony@contoso.com -AutoReplyState Enabled -InternalMessage "Internal auto-reply message." -ExternalMessage "External auto-reply message." -ExternalAudience All

With the description being updated to:

This example configures Automatic Replies for Tony's mailbox to be sent and includes an internal and an external message, and specifies the external message be sent to any external address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47db52ff-7c4b-3051-5414-3e1288216c1e
* Version Independent ID: 0e49597f-47e8-ec2a-9e1b-46bc465643cb
* Content: [Set-MailboxAutoReplyConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxautoreplyconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxAutoReplyConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailboxAutoReplyConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by pstakuu** [comment]
And I'm also realizing how many times I've probably set the external message with powershell and not specified that 🤦

**Comment by chrisda** [comment]
@pstakuu, done.

Thanks for the feedback.

Closing.
