### ISSUE TITLE
Substrate Only Agent': 'Organization "M365xxxxxxx.onmicrosoft.com" is not licensed for Exchange email functionality. Cmdlet usage is restricted.

### ISSUE THREAD

**Issue by ilantom** [MicrosoftDocs/office-docs-powershell#9879]
I created an AAD group, installed ExchangeOnlineManagement, ran 

>Set-UnifiedGroup groupName -HiddenGroupMembershipEnabled 

but I see the error:

```
The following error occurred during validation in agent 'Substrate Only Agent': 'Organization
"M365xxxxxxx.onmicrosoft.com" is not licensed for Exchange email functionality. Cmdlet usage is restricted.'
```

What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80326e44-6beb-8983-57ab-8333608c504b
* Version Independent ID: 8962c0dc-72a3-208a-33de-6a89cd56b6fc
* Content: [Set-UnifiedGroup (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
The \*-UnifiedGroup cmdlets are for Microsoft 365 groups:

<https://support.microsoft.com/office/learn-about-microsoft-365-groups-b565caa1-5c40-40ef-9915-60fdb2d97fa2>

Their relationship to AAD groups is vague, at least to me.

**Comment by yogkumgit** [comment]
@ilantom Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
