### ISSUE TITLE
Undocumented Teams cmdlets

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#9890]
The following cmdlets/functions from MicrosoftTeams module v.4.7.0 are not documented:

- Get-AssociatedTeam
- [Get|New]-CsCloudCallDataConnection
- Move-CsInternalHelper
- Set-CsInternalOnlinePowerShellEndpoint
- Invoke-CsInternalPsTelemetry
- [Get|Grant|New|Remove|Set]-CsOnlineAudioConferencingRoutingPolicy
- Get-CsOnlinePowerShellEndpoint
- [Get|Grant|New|Remove|Set]-CsTeamsEventsPolicy
- [Get|Grant|New|Remove|Set]-CsTeamsFilesPolicy
- [Get|Set]-CsTeamsMigrationConfiguration
- [Get|Remove|Set]-CsTeamsNotificationAndFeedsPolicy
- [Get|Grant|New|Remove|Set]-CsTeamsRoomVideoTeleConferencingPolicy
- [Get|Set]-CsTeamsShiftsAppPolicy
- [Get|New|Remove|Set]-CsTeamsSurvivableBranchAppliance
- [Get|Grant|New|Remove|Set]-CsTeamsSurvivableBranchAppliancePolicy
- [Get|Remove|Set]-CsTeamsTargetingPolicy
- [Get|Grant|New|Remove|Set]-CsTeamsUpdateManagementPolicy
- [Get|Grant|New|Remove|Set]-CsTeamsVdiPolicy
- [Get|Grant|New|Remove|Set]-CsTeamsWorkLoadPolicy
- Get-CsTenantNetworkConfiguration
- Get-MultiGeoRegion
- Get-Operation
- [Get|Remove]-SharedWithTeam
- Get-SharedWithTeamUser
- Get-TeamAllChannel
- Get-TeamIncomingChannel

Note: I checked that these cmdlets/functions are not listed as unsupported or deprecated in <https://docs.microsoft.com/microsoftteams/teams-powershell-supported-versions>

**Comment by shivtorov** [comment]
@pbafna03

**Comment by pbafna03** [comment]
Thanks @shivtorov for creating a fresh list. We'll reach out to the relevant teams. 

[Get|Grant|New|Remove|Set]-CsTeamsEventsPolicy is coming up in with https://github.com/MicrosoftDocs/office-docs-powershell/pull/9845 

Few of the above cmdlets are internal and don't need to be documented: 
Move-CsInternalHelper
Set-CsInternalOnlinePowerShellEndpoint
Invoke-CsInternalPsTelemetry

**Comment by yogkumgit** [comment]
@shivtorov and @pbafna03 #9895 is merged, waiting for #9845. Thanks

**Comment by pbafna03** [comment]
A whole bunch also coming in https://github.com/MicrosoftDocs/office-docs-powershell/pull/9842

**Comment by yogkumgit** [comment]
@shivtorov all three PR are merged. Hope these updates are helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
