### ISSUE TITLE
GlobalReadingPanePosition deprecated for cmdlet Set-MailboxMessageConfiguration 

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/office-docs-powershell#9902]
<Couldn't submit this internally using review.docs.microsoft.com>

GlobalReadingPanePosition deprecated for cmdlet Set-MailboxMessageConfiguration since moving to OWA React, however it is still around in public documentation causing customer confusion at times thus raising this request to update/remove this parameter from documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d9fd24-705e-4fa4-7ab0-9c35c31b013e
* Version Independent ID: 9cab50c8-7f41-40e2-ae3f-1be6ae94b28e
* Content: [Set-MailboxMessageConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxmessageconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@qaehtesh, a couple of considerations:

- The Exchange cmdlet reference topics are single-sourced. So, the Set-MailboxMessageConfiguration topic applies to Exchange Server 2010 - 2019 plus Exchange Online. The GlobalReadingPanePosition parameter is/was available in Exchange 2016, Exchange 2019, and Exchange Online.

  So, you're saying that parameter is gone from all three of those environments? Or is it just gone from Exchange Online?

- Availability and functionality are two different things. I just checked in a bone-stock PROD E5 tenant (no SDF, no flighting), and also on an E16 CU23Aug22SU and an E19 CU12Aug22SU server, and the GlobalReadingPanePosition parameter is available. Now, whether it actually works or does anything useful is a completely different story.

  For parameters in the "available but doesn't work" state, we typically set the description to "This parameter is reserved for internal Microsoft use", until such time as the parameter actually goes away, which rarely happens.

Comments?

**Comment by qaehtesh** [comment]
Thank you Chris,
This change is Exchange Online only since moving from JMM to OWA React.
The React version of new parameter is GlobalReadingPanePositionReact which is currently UI only and not available in Powershell

There is work item for this however haven't moved from a while and documentation keeps confusing customer so I am hoping we could make clear that for EXO this parameter is obsolete.
Work Item 107823<https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/107823>: Parameter GlobalReadingPanePosition deprecated for cmdlet Set-MailboxMessageConfiguration

Regards,
Qazi

________________________________

**Comment by chrisda** [comment]
So, this is a situation where the parameter is available but doesn't work in ExO, and is available and does work in on-prem.

I added the following text to the beginning of the description:

> This parameter is functional only in Exchange 2016 and Exchange 2019.

OK?

**Comment by qaehtesh** [comment]
sure, that would work!
I would have gone with "This parameter is not functional in Exchange online" or "The parameter functional in Exchange On-Premise Only" instead of specifying specific Exchange versions because later if someone finds this working in Exchange2013 or mixed environment may get confused, or when a newer exchange on-premise comes then we have keep adding versions.

Regards,
Qazi​‌
________________________________

**Comment by chrisda** [comment]
You raise some good points. I changed it to:

> This parameter is functional only in Exchange 2016 or later. It doesn't work in Exchange Online.

**Comment by qaehtesh** [comment]
Awesome, thank you!!!
________________________________
