### ISSUE TITLE
‎Exchange Online PowerShell V1 Module End of Life?‎ 

### ISSUE THREAD

**Issue by himanshugawande** [MicrosoftDocs/office-docs-powershell#9908]
Currently I am using some of the Exchange Online PowerShell v1 module cmdlet such as "Get-Mailbox", "Get-MailboxPermission" to interact and fetch data from Exchange Online.

After reading the below provided blog, we changed our authentication mechanism to Exchange Online via PowerShell from Basic Auth to Modern Auth by using Exchange Online EXO v2 module cmdlets.

Reference: https://docs.microsoft.com/powershell/exchange/v1-module-mfa-connect-to-exo-powershell 

![image](https://user-images.githubusercontent.com/60377982/190377076-fc5f5170-b459-4340-ace4-0ad48e2298cf.png)

So I have just changed the authentication to EXO v2 module, rest I am still using the V1 module cmdlets.

What I want to know:
As the blog mentions, The ability to connect to Exchange Online PowerShell using this version of the module will end on December 31, 2022.

So, is it just that basic auth will be deprecated and we can still be able to use module V1 cmdlets with modern auth or the whole Module V1 will be deprecated, i.e. V1 module cmdlets won't be functional after 31-Dec-2022.

**Comment by chrisda** [comment]
@himanshugawande, there no Exchange cmdlets are baked into the V1 module itself. The only purpose of the V1 module was to connect using MFA/2FA.

In your screenshot, you'll see support for the V1 module ended at the end of August. Honestly, there's really no reason to use the V1 module anymore. Use the V2/V3 (just released today) version of the module. It supports modern auth with and without MFA/2FA and has a few cmdlets baked into it (Get-VivaInsightSettings). Plus, it now supports certificate-based auth (CBA) for unattended scripts in both Exchange Online PowerShell and Security & Compliance PowerShell.

**Comment by yogkumgit** [comment]
@himanshugawande Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
