### ISSUE TITLE
Exchange Online Protection Documentation is extremely difficult if not impossible to locate

### ISSUE THREAD

**Issue by Rabbit994** [MicrosoftDocs/office-docs-powershell#991]
Where is old list of "These are commandlets for Exchange Online Protection"? I'm attempting to do something so simple of read in a list of IPs from CSV file and feed to Exchange Online Protection and no longer know what commands are because documentation is gone (or hasn't been properly indexed by Google)

Also, lumping it under "Exchange" is not acceptable. Exchange Online Protection while applies to Exchange isn't really "Exchange" product since there is no on premise equivalent. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7292d05-d927-6e62-bbe5-7d784e8382cb
* Version Independent ID: 0a39ea35-9321-ca7c-9af2-bd0846ed79b2
* Content: [Exchange Online Protection PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/exchange-eop/exchange-online-protection-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-eop/exchange-online-protection-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-eop/exchange-online-protection-powershell.md)
* Service: **eop**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Rabbit994, We're working on a mechanism that filters the Exchange cmdlet reference topics by workload (Exchange Server 2010/2013/2016, Exchange Online, Office 365 Security & Compliance Center, or Exchange Online Protection). It's coming, but it's taking longer than we thought. That's the closest we can get to the former "link farm"/"bucket" topics that used to exist on TechNet for Exchange cmdlet reference topics.

Thanks for the feedback.
