### ISSUE TITLE
Offline Address Book commands are not available in Exchange Online PowerShell v2 module

### ISSUE THREAD

**Issue by pholdridge** [MicrosoftDocs/office-docs-powershell#9919]
I've tried to use this command but it's not an existing command in V2 powershell module for Exchange Online
Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08334d1f-4776-c4fb-8a68-dacf201daafb
* Version Independent ID: ad05f12f-b914-4ce8-6c1e-3825d0896661
* Content: [Get-OfflineAddressBook (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-offlineaddressbook?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-OfflineAddressBook.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-OfflineAddressBook.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@pholdridge, first thing to check:

> In Exchange Online, this cmdlet is available only in the Address Lists role, and by default, the role isn't assigned to any role groups. To use this cmdlet, you need to add the Address Lists role to a role group (for example, to the Organization Management role group). For more information, see [Add a role to a role group](https://docs.microsoft.com/Exchange/permissions/role-groups#add-a-role-to-a-role-group).

**Comment by yogkumgit** [comment]
@pholdridge Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
