### ISSUE TITLE
RetryDistribution switch description on Set-DlpCompliancePolicy

### ISSUE THREAD

**Issue by DeepRaj98** [MicrosoftDocs/office-docs-powershell#9926]
The RetryDistribution switch redistributes the policy to all OneDrive for Business and SharePoint Online locations => Does it not work for Exchange Online Locations? Should this be redefined to reflect the various supported workloads' environments?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cee91383-5198-3793-28c3-f79c233556c2
* Version Independent ID: 01fc839a-d2e6-45ea-b58e-d696b74d02a2
* Content: [Set-DlpCompliancePolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-dlpcompliancepolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-DlpCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@DeepRaj98, the description has been updated to say:

> The RetryDistribution switch redistributes the policy to all Exchange, OneDrive for Business, and SharePoint Online locations.

Thanks for the feedback.

Closing
