### ISSUE TITLE
Update Release Notes for ExchangeOnlineManagement

### ISSUE THREAD

**Issue by robinmalik** [MicrosoftDocs/office-docs-powershell#9928]
Put the release notes for the Exchange module on the page. These are already stored in the latest preview version of `ExchangeOnlineManagement.psd1`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@robinmalik, the existing [Release notes section](https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#release-notes) in the topic has only ever talked about GA (non-Preview) versions of the module. The latest version of the module was a) in Preview (v2.0.6-PreviewX) for a long time, and b) had significant changes between some of the Preview versions.

And, just today, the v3.0.0 GA version of the module was released, and it's so different that it has [its own special section](https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#updates-for-version-300-the-exo-v3-module).

Is that sufficient? Or are you looking for something else?

**Comment by robinmalik** [comment]
@chrisda Ah, thanks for the heads up! 2.0.6 Preview 8 was the latest when I checked first thing this morning (UK time anyway). It makes adding the other preview notes somewhat moot now so I'll mark this as closed.
