### ISSUE TITLE
Microsoft Teams 4.7.1-Preview - Access Denied with CS Commands using Certificate Based Auth

### ISSUE THREAD

**Issue by eximo84** [MicrosoftDocs/office-docs-powershell#9929]
- Installed 4.7.1-Preview module
- Created App registration as per article
- Created Self Signed Cert
- Uploaded Cert
- Granted App Registration Teams Administrator role
- Connected using App ID, Thumbnail and Tenant ID
- Connection fine

running Get-CSOnlineUser or Get-CsBatchPolicyAssignmentOperation i get Access Denied

Documentation states no API permissions are required for -CS* commands.

Granted API permissions and Skype/Teams API permissions as below

![image](https://user-images.githubusercontent.com/25502878/191291256-4dae14e6-40e7-4d42-9672-fc0447d00398.png)

Still get access denied

**Comment by pbafna03** [comment]
Hi @eximo84, 

Can you please try with removing "application_access_custom_sba_appliance" permission. Post removing the permission, after a few minutes please do Disconnect-MicrosoftTeams and then Connect-MicrosoftTeams with the cert. 

Get-CsOnlineUser should work, Get-CsBatchPolicyAssignmentOperation is not supported yet with Application-based auth. 

Thanks,

**Comment by eximo84** [comment]
> Hi @eximo84,
> 
> Can you please try with removing the "application_access_custom_sba_appliance" permission. Post removing the permission, after a few minutes please do Disconnect-MicrosoftTeams and then Connect-MicrosoftTeams with the cert.
> 
> Get-CsOnlineUser should work, Get-CsBatchPolicyAssignmentOperation is not supported yet with Application-based auth.
> 
> Thanks,

I have removed the "application_access_custom_sba_appliance" and it is now working. Although i do wonder if i just didnt give it enough time maybe?   I would assume based on the documentation, if my script is only using -CS* commands then i dont need any API permissions assigned to my App Registration?

Are any of the CsBatchPolicyAssignmentOperation commands working?  If not is there a timeline on when they are due to be working with this auth method?

Is there an alternative method for auth where CsBatchPolicyAssignmentOperation commands will work?

**Comment by pbafna03** [comment]
Yes, for *-Cs cmdlets currently there are no additional API permissions needed. 

Support for application-based auth in more cmdlets will be gradually rolled out over next couple of months. In the meanwhile, other authentication mechanisms mentioned in [Connect-MicrosoftTeams](https://learn.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps) can be used.

**Comment by yogkumgit** [comment]
@eximo84 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
