### ISSUE TITLE
Clarification on the use of plain text passwords within code

### ISSUE THREAD

**Issue by AAdamCCox** [MicrosoftDocs/office-docs-powershell#9942]
The article states "as we all know, storing user credentials locally is not a good security practice", but then with no caveats goes on to immediately show an example doing precisely that:

`ConvertTo-SecureString -String "<MyPassword>" -AsPlainText`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication in Exchange Online PowerShell and Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@AAdamCCox, it would seem the whole point of the procedures in that topic is automation (no user intervention).

With 'connect using a local certificate' method, you basically have 3 ways to enter the password for the CertificatePassword parameter:

- `(ConvertTo-SecureString -String '<password>' -AsPlainText -Force)`.
- Before you run the command, store the password as a variable (for example, `$password = Read-Host "Enter password" -AsSecureString`), and then use the variable (`$password`) for the value.
- `(Get-Credential).password` to be prompted to enter the password securely when you run the command.

Two out of three options involve being prompted for the password, which would seem to defeat the purpose of automation.

The remaining connection methods ('connect using a certificate thumbprint' and 'connect using a certificate object') don't require a password.

So are you saying that adding a note like this to the 'connect using a local certificate' method is the fix?

> [!NOTE]
> Unless you want to be prompted for the password, this method stores the password locally.

Or should I replace that CertificatePassword value with one of the two 'prompt me' options for the password (likely, the last one)?

**Comment by AAdamCCox** [comment]
Hi @chrisda yes I think a note like that would make it clear that there's no automated _and_ secure way to use a local certificate PFX file, making this approach unsuitable for production use.

Since it might be recommended only while manually testing a PFX, perhaps switching the example to use `Get-Credential` would also be appropriate? Given that in that context, automation isn't the goal, yet we can still show a best practice approach for handling passwords securely.

**Comment by chrisda** [comment]
@AAdamCCox, thanks for the suggestions.

I moved 'connect using a local certificate' **after** 'connect using a certificate thumbprint' and 'connect using a certificate object' to deemphasize IT, and I added the following note to it:

   > [!NOTE]
  > Using a **ConvertTo-SecureString** command to store the password of the certificate locally defeats the purpose of a secure connection method for automation scenarios. Using a **Get-Credential** command to prompt you for the password of the certificate securely isn't ideal for automation scenarios. In other words, there's really no automated _and_ secure way to connect using a local certificate.

OK?

**Comment by AAdamCCox** [comment]
Looks good, thanks!
