### ISSUE TITLE
Set-CsPhoneNumberAssignment : Access Denied

### ISSUE THREAD

**Issue by Rowan-Ramasray** [MicrosoftDocs/office-docs-powershell#9961]
Hello,

When doing a phone number assignment using Microsoft Teams PowerShell and a SPN i get a access denied error.... 

**Detailed error:**

```powershell
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNumberAssignment : Access Denied.
At C:\Program Files\PowerShell\Modules\MicrosoftTeams\4.7.1\custom\Merged_custom_PsExt.ps1:1298 char:13
+             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNum …
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: ({ Identity = abcd…seVoiceEnabled =  }:<>f__AnonymousType100`5) [Set-CsPhoneNumberAssignment_Set], RestException`1
+ FullyQualifiedErrorId : Forbidden,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsPhoneNumberAssignment_Set
```

**How to reproduce:**
1. Create a SPN in Azure AD and assign the Global Administrator role
2. Install Teams Module 4.7.1
3. Connect to Teams using this script:
```powershell
$ClientSecret   = "…"
$ApplicationID = "00000000-0000-0000-0000-000000000000"
$TenantID = "YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY"

$graphtokenBody = @{   
   Grant_Type    = "client_credentials"   
   Scope         = "https://graph.microsoft.com/.default"   
   Client_Id     = $ApplicationID   
   Client_Secret = $ClientSecret   
}  

$graphToken = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$TenantID/oauth2/v2.0/token" -Method POST -Body $graphtokenBody | Select-Object -ExpandProperty Access_Token 

$teamstokenBody = @{   
   Grant_Type    = "client_credentials"   
   Scope         = "48ac35b8-9aa8-4d74-927d-1f4a14a0b239/.default"   
   Client_Id     = $ApplicationID   
   Client_Secret = $ClientSecret 
} 

$teamsToken = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$TenantID/oauth2/v2.0/token" -Method POST -Body $teamstokenBody | Select-Object -ExpandProperty Access_Token 

Connect-MicrosoftTeams -AccessTokens @("$graphToken", "$teamsToken")`
```
5. Assign Phone number using:
```powershell
Set-CsPhoneNumberAssignment -Identity example@contoso.com -PhoneNumber +00000000 -PhoneNumberType "DirectRouting"`
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b911670-8e3f-f86a-90ac-bde691d49e8c
* Version Independent ID: 4b1d9835-8e81-d04b-57ec-12a537dbeaeb
* Content: [Set-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by JensTrier** [comment]
@Rowan-Ramasray thanks for the feedback! I'll take a look

**Comment by pbafna03** [comment]
@Rowan-Ramasray - SPN / Application based auth is not yet supported for Set-CsPhoneNumberAssignment and will be enabled soon.  Ref - https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication#cmdlets-supported.

**Comment by yogkumgit** [comment]
@Rowan-Ramasray Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by pbafna03** [comment]
Hi @Rowan-Ramasray - You can try this now.

**Comment by captainhook** [comment]
@Rowan-Ramasray did you manage to get this working?

**Comment by Westy619** [comment]
Has anyone confirmed this works? I'm still getting the same error as the OP via application based auth.

**Comment by pbafna03** [comment]
Hi @Westy619, 

It does work for *-CsPhoneNumberAssignment  cmdlets, if you are getting an unauthorized error - please check if you have a relevant [Azure AD role](https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles) assigned to the app used.

**Comment by Westy619** [comment]
Hi @pbafna03, can you advise on the specific Azure AD roles? I've assigned it Teams Administrator as I assumed that would be all that is required.

**Comment by pbafna03** [comment]
> Hi @pbafna03, can you advise on the specific Azure AD roles? I've assigned it Teams Administrator as I assumed that would be all that is required.

Yeah that should be sufficient.  Can you please share the screenshot of the error if it's still coming post AAD role assignment.

**Comment by Westy619** [comment]
Hi @pbafna03 Sure, the command returns the below error: 

Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNumberAssignment : Invalid credential
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\5.3.0\custom\Merged_custom_PsExt.ps1:1326 char:13
+             $result = Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set- ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = Ri...iceEnabled =  }:<>f__AnonymousType106`5) [Set-CsPhoneNumberAssignment_Set], RestException`1
    + FullyQualifiedErrorId : Unauthorized,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsPhoneNumberAssignment_Set

**Comment by Westy619** [comment]
Hi @pbafna03, sure, the command returns the following error:

```powershell
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsPhoneNumberAssignment : Invalid credential
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\5.3.0\custom\Merged_custom_PsExt.ps1:1326 char:13
+             $result = Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set- ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = Ri...iceEnabled =  }:<>f__AnonymousType106`5) [Set-CsPhoneNumberAssignment_Set], RestException`1
    + FullyQualifiedErrorId : Unauthorized,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsPhoneNumberAssignment_Set
```

**Comment by pbafna03** [comment]
Thanks @Westy619, is this error also coming when tried from a fresh PowerShell window/session? Also which method is used to authenticate - Access token or Certificate Thumbprint etc.? 

The above error generally comes when the token is expired.

**Comment by pbafna03** [comment]
Also @Westy619 - Check if by any chance you have the "application_access_custom_sba_appliance" permission assigned to Skype and Teams Tenant Admin API. If yes, remove it and post removing the permission, after a few minutes please do Disconnect-MicrosoftTeams and then Connect-MicrosoftTeams.

**Comment by Westy619** [comment]
Thanks @pbafna03. I had both "application_access_custom_sba_appliance" and "application_access" via the Skype and Teams Tenand Admin API. I ended up removing both permissions completely and confirmed cs commands are now working.
