### ISSUE TITLE
No reference for connecting to USGovDoD using app-only (CBA) for Connect-ExchangeOnline

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/office-docs-powershell#9962]
existing recommendations in examples doe not apply or work. Throws winRM errors.

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@jebalert, interesting this hasn't come up before, but the Connect-ExchangeOnline commands require `-ExchangeEnvironmentName O365USGovGCCHigh` or `-ExchangeEnvironmentName O365USGovDoD` just like the [regular connection instructions](https://learn.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell). Fortunately, there's nothing different/special required to actually set up CBA in GCC High or DoD.

**Comment by yogkumgit** [comment]
@jebalert Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
