### ISSUE TITLE
Connect-ippssession doesn't work with a certificatethumbprint

### ISSUE THREAD

**Issue by deontaljard1** [MicrosoftDocs/office-docs-powershell#9965]
Using ModuleVersion 3.0

After setting up the App registration and permissions with the self signed certificate I cannot connect with :

       Connect-Ippssession  -CertificateThumbPrint "mycertthumhere" -AppID "myappid" -Organization "myorg.OnMicrosoft.com"

It launches a user auth prompt.

Working connection methods :

       Connect-exchangeonline -CertificateThumbPrint "mycertthumhere" -AppID "myappid" -Organization "myorg.OnMicrosoft.com"

       Connect-IPPSSession -CertificateFilePath "C:\temp\mycert.pfx" -CertificatePassword (Get-Credential).password -AppID "myappid" -Organization "myorg.OnMicrosoft.com"

Thanks 
Deon

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication in Exchange Online PowerShell and Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps&source=docs)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@deontaljard1, you should open a support ticket. Report back here with any useful information.

**Comment by deontaljard1** [comment]
Thanks Chris, will do that

**Comment by JustInnIO** [comment]
I have the same problem on two Windows Server 2019. On Windows 10/11 clients it works.

**Comment by chrisda** [comment]
@JustInnIO, interesting script. If possible, I would replace the `Set-Content...-Encoding Byte` command with `[System.IO.File]::WriteAllBytes` it works with any/all versions of PowerShell from 2.0 to 7.x; `-Encoding Byte` ends at PowerShell 5.1.

```powershell
[System.IO.File]::WriteAllBytes($CertPath, $Cert) | Write-Verbose
```
