### ISSUE TITLE
Parameter -emailaddresses in Set-Unified Group does not exist

### ISSUE THREAD

**Issue by lynx002** [MicrosoftDocs/office-docs-powershell#9966]
Document specifies -emailaddresses as a parameter for Set-Unified group, but no such property exists in the module (using ExchangeOnlineManagement 3.0.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80326e44-6beb-8983-57ab-8333608c504b
* Version Independent ID: 8962c0dc-72a3-208a-33de-6a89cd56b6fc
* Content: [Set-UnifiedGroup (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@lynx002, I tried in Windows PowerShell 5.1 and PowerShell 7.2.6 with and without-UseRPSSession, and that parameter was available to me in all four cases.

So, we could be dealing with RBAC issues. What are the results of the following commands for you?

```powershell
$Perms = Get-ManagementRole -Cmdlet Set-UnifiedGroup -CmdletParameters EmailAddresses

$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}
```

In my organization, the output of those commands looks like this (obvious custom role groups removed):

```console
Role            RoleAssigneeType RoleAssigneeName
----            ---------------- ----------------
Mail Recipients RoleGroup        Recipient Management
Mail Recipients RoleGroup        Organization Management
```

**Comment by lynx002** [comment]
Hi Chris,

I am now able to use the command correctly. I don't know what could have
caused the error initially as I used the same module version and user at
all times.

I apologize for any inconvenience I may have caused and thank you for your
time.


- Daniel Arias

**Comment by chrisda** [comment]
No problem. I thought it could have been a REST API vs. remote PowerShell cmdlets thing.

Thanks for the feedback.

Closing
