### ISSUE TITLE
Accidental acces to DiscoverySearchMailbox

### ISSUE THREAD

**Issue by falk-22** [MicrosoftDocs/office-docs-powershell#9967]
In the documentation is stated that the PolicyScopeGroupID parameter only accepts recipients that are security principals, so I cannot put a shared mailbox account here directly.
For me this does not matter, because I always use Application Access policies with mail enabled security groups and I only use the AccessRight "RestrictAccess" to allow the application only access to mailboxes that are members of the security groups. 
If I use Test-ApplicationAccessPolicy to check whether the policy works as expected, everything seems to be fine, the app has only access to the mailbox which is member of the security group, except one mailbox: The DiscoverySearchMailbox.
I understand that I cannot put the DiscoverySearchMailbox directly as recipient in the PolicyScopeGroupID, but If I'm restricting the application to only one dedicated mailbox, why has the application access to the DiscoverySearchMailbox as well?

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a47ca7d5-2598-0c06-03fd-854f94cf6bbe
* Version Independent ID: a57408f6-16ca-3fcb-0c04-48a7a5f9942d
* Content: [New-ApplicationAccessPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-applicationaccesspolicy?view=exchange-ps&preserve-view=true)
* Content Source: [exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@falk-22, you should open a support ticket and ask. Report back here with any information that can help in the documentation.
