### ISSUE TITLE
Does PolicyScopeGroupID support AzureAD groups?

### ISSUE THREAD

**Issue by andersidahl** [MicrosoftDocs/office-docs-powershell#9971]
PolicyScopeGroupID is somewhat unclear. Can AzureAD groups be used?
Would be good to give some examples on grouptypes recommended for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a47ca7d5-2598-0c06-03fd-854f94cf6bbe
* Version Independent ID: a57408f6-16ca-3fcb-0c04-48a7a5f9942d
* Content: [New-ApplicationAccessPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-applicationaccesspolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-ApplicationAccessPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by DMoenks** [comment]
As far as I know, the documentation is as detailed as possible in this regard: Values for the **PolicyScopeGroupID** parameter must be security principles by definition of Exchange Online. The only group type usable in this regard would be mail-enabled security groups, which disqualifies Azure AD groups. The introduction of the following article could pose as some form of confirmation for this: [Learn about groups and access rights in Azure Active Directory](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/concept-learn-about-groups)

**Comment by chrisda** [comment]
@DMoenks is correct: mail-enabled security groups are the only types of groups that you can use with the parameter.

On the whole, I found the entire description a bit lacking, so I clarified and reorganized. Hopefully, that will help:

> The PolicyScopeGroupID parameter specifies the recipient to define in the policy. Valid recipient types are security principals in Exchange Online (users or groups that can have permissions assigned to them). For example:
> 
> - Mailboxes with associated user accounts (UserMailbox)
> - Mail users, also known as mail-enabled users (MailUser)
> - Mail-enabled security groups (MailUniversalSecurityGroup)
> 
> You can use any value that uniquely identifies the recipient. For example:
> 
> - Name
> - Distinguished name (DN)
> - Display name
> - Email address
> - GUID
> 
> To verify that a recipient is a security principal, run either of the following commands: `Get-Recipient -Identity <RecipientIdentity> | Select-Object IsValidSecurityPrincipal` or `Get-Recipient -ResultSize unlimited | Format-Table -Auto Name,RecipientType,RecipientTypeDetails,IsValidSecurityPrincipal`.
> 
> You can't use recipients that aren't security principals with this parameter. For example, the following types of recipients won't work:
> 
> - Discovery mailboxes (DiscoveryMailbox)
> - Dynamic distribution groups (DynamicDistributionGroup)
> - Distribution groups (MailUniversalDistributionGroup)
> - Mail contacts (MailContact)
> - Mail-enabled public folders (PublicFolder)
> - Microsoft 365 Groups (GroupMailbox)
> - Resource mailboxes (RoomMailbox or EquipmentMailbox)
> - Shared mailboxes (SharedMailbox)
> 
> If you need to scope the policy to shared mailboxes, you can add the shared mailboxes as members of a mail-enabled security group.

**Comment by andersidahl** [comment]
Thanks for the reply and the clarification. 

If only mail-enabled security groups are supported - that means a cloud only environment do not support this feature, since mail-enabled security groups needs to be synced from on-prem?

**Comment by chrisda** [comment]
@andersidahl, not at all. You can create and use mail-enabled security groups in cloud-only environments. See [here](https://learn.microsoft.com/microsoft-365/admin/create-groups/compare-groups).
