### ISSUE TITLE
Are the limitations listed for the UnifiedGroup cmdlets still accurate?

### ISSUE THREAD

**Issue by SaskaTune** [MicrosoftDocs/office-docs-powershell#9972]
In my recent testing, Set-UnifiedGroup appears to be working with certificate based authentication (CBA).  Is the limitation noted on this page specific to certain versions of the Exchange Online module?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication in Exchange Online PowerShell and Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#feedback)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@SaskaTune, apparently nothing has changed. You might find that some parameters work, but many still do not, so our position about 'not supported' is still in effect.

**Comment by yogkumgit** [comment]
@SaskaTune Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
