### ISSUE TITLE
Enabling SRS on outbound partner connector

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/office-docs-powershell#9976]
This article says: "as Partner connectors already have SRS rewriting enabled.:"
This is incorrect. Partner connectors by default don't have SRS rewriting enabled, therefore this is confusing.

Affects SenderRewritingEnabled parameter description on both New-OutboundConnector and Set-OutboundConnector.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5c2bf2a-0ecb-498b-c8c4-fa62d3bc3c12
* Version Independent ID: 77817c9e-4089-fd82-f20a-30923625d5fa
* Content: [New-OutboundConnector (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-outboundconnector?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-OutboundConnector.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-OutboundConnector.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeroenDronkers, I removed the incorrect statement from the SenderRewritingEnabled parameter description on New-OutboundConnector and Set-OutboundConnector.

Thanks for the feedback.

Closing
