### ISSUE TITLE
Sender rewriting with partner connector

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/office-docs-powershell#9977]
[The statement "This parameter is only effective for OnPremises connectors as Partner connectors already have SRS rewritting enabled", is incorrect since this feature cannot be enabled on a partner connector]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5c2bf2a-0ecb-498b-c8c4-fa62d3bc3c12
* Version Independent ID: 77817c9e-4089-fd82-f20a-30923625d5fa
* Content: [New-OutboundConnector (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-outboundconnector?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-OutboundConnector.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-OutboundConnector.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Knowing that this issue affects the SenderRewritingEnabled parmeter on both New-OutboundConnector and Set-OutboundConnector, closing this issue as a duplicate of #9976.

Thanks for the feedback.
