### ISSUE TITLE
Filter dynamic groups on employeetype

### ISSUE THREAD

**Issue by naitmare01** [MicrosoftDocs/office-docs-powershell#9988]
I want to be able to filter dynamic groups on employeeType with Azure AD Cloud sync.
Don't know if this is the correct place for this feature request, please send me in the right way.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3762ada1-99d6-fa6d-fbd7-524003f8c3b2
* Version Independent ID: 03e801b7-fa14-b5fb-8600-131c9e73292f
* Content: [Filterable properties for the RecipientFilter parameter](https://learn.microsoft.com/en-us/powershell/exchange/recipientfilter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/recipientfilter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/recipientfilter-properties.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@naitmare01, your best path forward is to open a support ticket about this.

**Comment by yogkumgit** [comment]
@naitmare01 Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
