### ISSUE TITLE
what for onprem

### ISSUE THREAD

**Issue by WillemVerwijs** [MicrosoftDocs/office-docs-powershell#9989]
What would be the command for SfB 2019 on-prem?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68d9f375-9d34-2b3a-18da-ba0c3f5e6430
* Version Independent ID: ba24e413-c5c5-916c-3686-bd3905ca8516
* Content: [Get-CsUserActivitiesReport (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/get-csuseractivitiesreport?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-CsUserActivitiesReport.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Get-CsUserActivitiesReport.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by get-itips** [comment]
Hello @WillemVerwijs 
cmdlet is not available for Server version of SfB.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @WillemVerwijs Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
