### ISSUE TITLE
PowerShell examples are missing $PSItem in foreach Loop

### ISSUE THREAD

**Issue by satyajit321** [MicrosoftDocs/office-docs-powershell#9990]
Incorrect Sample: $NPS | foreach {Set-User -RemotePowerShellEnabled $false}

Corrected Sample: $NPS | foreach {Set-User  $_ -RemotePowerShellEnabled $false}

If you are using a Object as input: Then we need to select
$DSA | foreach {Set-User  $_.Name  -RemotePowerShellEnabled $false}

$_ or $PSItem needs to be used to reference the item passed via the Pipe.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d03c6ce2-687b-e138-939b-413014d1c81a
* Version Independent ID: 9fe6c492-d0fe-e454-6574-06de8cd31a21
* Content: [Control remote PowerShell access to Exchange servers](https://learn.microsoft.com/en-us/powershell/exchange/control-remote-powershell-access-to-exchange-servers?view=exchange-ps&viewFallbackFrom=exchange-ps%22%20%5Cl%20%22use-the-exchange-management-shell-to-enable-or-disable-remote-powershell-access-for-a-user)
* Content Source: [exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@satyajit321, topic updated.

Thanks for the feedback.

Closing
